### ISSUE TITLE
Can’t get Top Level Inner Hits with search results in 6.x

### ISSUE THREAD

**Issue by benbenwilde** [elastic/elasticsearch#34425]
I'm trying to execute a query that returns a set of results while also including an independently filtered set of inner hits for those results.

This was easy in version 2.x, since I could add a top level inner hits section to the request with it's own independent filter. This way, I could return only the inner hits that I needed without changing the query.

Now in 6.x, the only way I see that I can do this is by making two separate round trip requests to the cluster which is definitely not ideal.

How can do this in a single request?

- - - - - - - - - - -

Here is the request I was successfully using in 2.x, that i would like to replicate in 6.x:
`POST index1/parent/_search`
```
{
    "from": 0,
    "size": 100,
    "sort": [
        {
            "time": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "thingIds": [
                            "thing/345"
                        ]
                    }
                }
            ]
        }
    },
    "inner_hits": {
        "comments": {
            "type": {
                "child": {
                    "query": {
                        "terms": {
                            "doc.userId": [
                                "u/1234"
                            ]
                        }
                    },
                    "size": 1000
                }
            }
        }
    }
}
```

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by benbenwilde** [comment]
@jasontedor yes I have done so [here](https://discuss.elastic.co/t/cant-get-top-level-inner-hits-with-search-results-in-6-x/151716), but to no avail. I've seen other similar questions go unanswered in the forums so I don't have much hope.

You must be very familiar with the codebase, can you *confirm that top-level inner_hits was removed*? It was indeed removed from the documentation and the .NET SDK (NEST) with no mention of alternatives. If it was really removed, are you aware of any alternative? 

*The key here is that I need to search and query a set of documents, and simultaneously return those documents' inner_hits via an independent query (in the same request).*

If there is no way to do this currently, I would like to *request it as a feature* in a coming release. Even if we have to workaround it for now, it would be incredibly valuable in the future.

Thank you for your time, it is very appreciated!

**Comment by benbenwilde** [comment]
Okay, I was able to get this to work by messing with the query a little bit.

Basically, since there is no top level inner hits anymore, and they now have to be attached to a has child section of the parent query, you have to add the child query to a has child query on the parent query. To do this without impacting the original parent query, all you have to do is add the query again in a logical OR NOT, i.e. `parent_query && (has_child_query || !has_child_query)`. Then just attach the inner hits clause to the first has child query.

--- 

Here is a full example - 
Elasticsearch 2.x request:
`POST index1/parent/_search`
```
{
    "from": 0,
    "size": 100,
    "sort": [
        {
            "time": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "thingIds": [
                            "thing/345"
                        ]
                    }
                }
            ]
        }
    },
    "inner_hits": {
        "comments": {
            "type": {
                "child": {
                    "query": {
                        "terms": {
                            "userId": [
                                "u/1234"
                            ]
                        }
                    },
                    "size": 1000
                }
            }
        }
    }
}
```

Elasticsearch 6.x request:
(note that parent and child both have the same `_type` of "_doc" (to support ES 6.x indices with single mapping), and I'm using a custom `type` field to differentiate)
`POST index1/_doc/_search`
```
{
    "from": 0,
    "size": 100,
    "sort": [
        {
            "time": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "type": {
                                        "value": "parent"
                                    }
                                }
                            },
                            {
                                "terms": {
                                    "groupIds": [
                                        "groups/345"
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "has_child": {
                                    "type": "child",
                                    "query": {
                                        "terms": {
                                            "userId": [
                                                "u/1234"
                                            ]
                                        }
                                    },
                                    "inner_hits": {
                                        "name": "userCalls"
                                    }
                                }
                            },
                            {
                                "bool": {
                                    "must_not": [
                                        {
                                            "has_child": {
                                                "type": "child",
                                                "query": {
                                                    "terms": {
                                                        "userId": [
                                                            "u/1234"
                                                        ]
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```
