### ISSUE TITLE
question: ES response size limitations | 502 bad gateway

### ISSUE THREAD

**Issue by omurbekjk** [elastic/elasticsearch#34438]
We have large data in ES, we send request with the size limit: 1,000 and we do pagination to get remaining results.
Sometimes we get 502 bad gateway, hard to debug what went wrong.
I assumed if the response size is too large maybe the server is failing to serve it.
Also we do aggregation with the size limit: 10 000.

1. What is the recommended size for es query and aggregation?
2. How should we handle aggregation queries when we do pagination?

**Comment by vladimirdolzhenko** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
