### ISSUE TITLE
Docs: Path-style access is currently not working

### ISSUE THREAD

**Issue by milanage** [elastic/elasticsearch#34439]
This is a request to make it clear in current [S3 repo setting documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-s3-repository.html) that path-style access is not working, so that users don't expect, for example HTTP request of creating repository being sent to "endpoint/bucket".

Link [#31608](https://github.com/elastic/elasticsearch/issues/31608)

**Comment by original-brownbear** [comment]
I'm closing this. With https://github.com/elastic/elasticsearch/pull/41966 now merged it is possible to set whether or not to use path style access with any S3 repo.
