### ISSUE TITLE
documents with empty strings are not considered in terms aggregation when "map" execution hint is specified

### ISSUE THREAD

**Issue by vanga** [elastic/elasticsearch#34434]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**Description of the problem including expected versus actual behavior**:
https://discuss.elastic.co/t/aggregation-using-execution-hit-map-automatically-filtered-empty-string-key/95445/2
Issue is same as mentioned in above discuss post.
if I index a doc with empty string `{"email": ""}`, it's not considered in terms agg response when `execution_hint: "map"`.

**Steps to reproduce**:
```
PUT test/_mapping/test
{
  "properties": {
    "email": {
      "type": "keyword"
    }
  }
}
```
```

POST test/test/
{
    "email": ""
}
```
```
POST test/_search?size=0
{
   "aggregations": {
      "aggregation_name": {
         "terms": {
            "field": "email",
            "execution_hint": "map",
            "missing": "N/A"
         }
      }
   }
}
```

I expect the behavior to not change based on what execution_hint I am using.
But, maybe the underlying implementation prevents returning the `""` bucket?
Are there any workarounds? 
Thanks.

**Comment by rjernst** [comment]
I have a suspicion this is due to the inverted index not having any values for the field (since tokenization of the empty value would result in zero tokens), but doc values stores the original empty string as is. Could someone from @elastic/es-search-aggs confirm that?
