### ISSUE TITLE
aggregation repeatedly to sum value

### ISSUE THREAD

**Issue by zzRicky** [elastic/elasticsearch#34447]
#### i got a wrong sumValue, the sumValue calc duplicate
```
request:

AggregationBuilder groupAgg = AggregationBuilders.terms("sku_id").field("itemList.skuId");
AggregationBuilder subSumAgg = AggregationBuilders.sum("sum_sku_cnt").field("itemList.skuCnt");

TermsAggregationBuilder termsBuilder = (TermsAggregationBuilder) groupAgg;
searchRequestBuilder.addAggregation(termsBuilder.subAggregation(subSumAgg));

response:
Double sumValue = ((InternalSum)valueMap.get("sum_sku_cnt")).getValue();

expected: 
    AA = 1
    BB = 1
but got:
    AA = 2
    BB = 2
```

#### my document json schema
```
{
  orderMain: {
     orderId: 2018090900000001,
     userNick: 'testuser'
  },
  itemList: [
     {
       skuId: 'AA',
       skuCnt: 1
     },
     {
       skuId: 'BB',
       skuCnt: 1
     }
  ]
}
```

**Comment by spinscale** [comment]
please ask questions like this on our [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) as we try to use this forum for bugs only (even if this seems to look like a bug to you, it is not).

If you want to aggregate on items within an array I highly suggest you to take a look at the [nested type](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/nested.html) and [nested aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-nested-aggregation.html) and then ask for more about that in the forum.

Thanks a lot! One more hint: If you provide a fully reproducible example in your forum post including index creation, mappings, sample documents and a full blown query that can be easily copied and pasted into the console using curl or the kibana console, it is much more likely that you will get help - even though it will take some more time on your side to prepare this. See https://www.elastic.co/help
