### ISSUE TITLE
[CI] Task :x-pack:plugin:ccr:qa:multi-cluster-with-non-compliant-license:followClusterTestCluster#wait task fails

### ISSUE THREAD

**Issue by andrershov** [elastic/elasticsearch#34449]
This job https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/177/console has failed because of CCR task.
The actual failure message 
```
Starting process 'command 'kill''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+periodic/x-pack/plugin/ccr/qa/multi-cluster-with-non-compliant-license Command: kill -9 101980
```
is not descriptive.

Probably there was a timeout of 5 seconds on this task, because there is 5 seconds gap between last log message and jstack output
```
|    [2018-10-14T06:53:59,020][INFO ][o.e.t.TransportService   ] [node-0] publish_address {127.0.0.1:37717}, bound_addresses {[::1]:35156}, {127.0.0.1:37717}
|
|  [jstack]
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
|    2018-10-14 06:54:04
|    Full thread dump Java HotSpot(TM) 64-Bit Server VM (11+28 mixed mode):
```

**Comment by martijnvg** [comment]
I have not seen a recent failed build failing because of the wait task timing out in a ccr qa test. Also the build logs are gone and there is not enough information in the issue itself to investigate. I'm closing this issue for now.
