### ISSUE TITLE
Mounting Elastic Search storage to Azure Storage ( Files )

### ISSUE THREAD

**Issue by rifaterdemsahin** [elastic/elasticsearch#34455]
**Elasticsearch version** (`bin/elasticsearch --version`):
"version" : {
    "number" : "6.3.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "424e937",
    "build_date" : "2018-06-11T23:38:03.357887Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },

[xxxx@yyyy ~]$  cat /etc/*-release
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)

**Description of the problem including expected versus actual behavior**:

1.  We have having latency issues where it takes 20 seconds to full index 120 documents.
2.  We are using Azure files storage to mount as storage to our elastic search to persist its data.

**Steps to reproduce**:
Running our microservices are creating necessary documents in elastic search

**Provide logs (if relevant)**:
Also we are seeing the Azure storage usage with 1GB but the actual elastic search query of shard data shows much less.
this shows 5 megabyte  curl -XGET 'localhost:9200/_cat/indices?v'
Azure shows 1 GB usage

As the quota was 1 GB as well today increased the quota but could not locate the reason for the issue.

Reference Implementation
https://azure.microsoft.com/es-es/blog/introducing-elasticsearch-with-azure-file-storage/

**Comment by polyfractal** [comment]
Hi @rifaterdemsahin, this looks like a good candidate for posting on the [Elasticsearch Discuss Forums](https://discuss.elastic.co/c/elasticsearch).  We try to reserve Github issues for bug reports.  This looks to be a latency issue related to how Azure FS is implemented.

We generally do nor recommend network attached storage.  E.g. a [small blurb from the Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html#_disks)

> Finally, avoid network-attached storage (NAS). People routinely claim their NAS solution is faster and more reliable than local drives. Despite these claims, we have never seen NAS live up to its hype. NAS is often slower, displays larger latencies with a wider deviation in average latency, and is a single point of failure.

Not an Azure expert, but it appears Azure FS is basically a SMB 3.0 shared file system, which fits with the above warning about NAS and higher latency.

[A more recent tutorial about setting up on Azure](https://www.elastic.co/blog/deploying-elasticsearch-on-microsoft-azure) recommends using Premium Storage, which I believe equates to local instance-attached SSDs.
