### ISSUE TITLE
[watcher] Provide Capability To Compress Attachments In Emails Generated By Watcher

### ISSUE THREAD

**Issue by MorrieAtElastic** [elastic/elasticsearch#34466]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):6.2.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

-provide a capability to compress attachments to emails generated by watches. This seems like a reasonable capability, given that watcher attachments could become quite large.  

-the ability to compress attachments would make it easier for attachments to go through firewalls and other email filters having maximum email and/or email attachment size limits. 

-at the present time there is no such capability and little in the way of workaround when confronted with such limites.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
