### ISSUE TITLE
[watcher/docs] Query a remote cluster is also possible by Cross Cluster Search

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#34470]
The [current docs](https://www.elastic.co/guide/en/x-pack/current/input-http.html#_querying_external_elasticsearch_clusters) indicate that to query a remote cluster, the http input can be used.   It should be noted there ([or maybe better here](https://www.elastic.co/guide/en/x-pack/current/input-search.html)) that Cross Cluster Search is also possible.

**Comment by lcawl** [comment]
The 6.3 and later version of that documentation is here: https://www.elastic.co/guide/en/elastic-stack-overview/master/input-http.html
