### ISSUE TITLE
Request the ability to get a shard's history 

### ISSUE THREAD

**Issue by Gunnerva** [elastic/elasticsearch#34485]
**Describe the feature**:
Please add the ability via an API call to get the history of a shard.  Add the ability to see which nodes it has been on, when it was moved, why it was moved, etc....

**Elasticsearch version** (`bin/elasticsearch --version`):
6.1.1

**Comment by jasontedor** [comment]
What is the use case for this beyond what monitoring already provides?

**Comment by Gunnerva** [comment]
They would like a deeper history of the shard movements then what is provided via monitoring currently.  The idea is that they would like to run statistics on how ES moves shards around and then judge how efficient ES is handling this balancing.

They would like to use this data to tweak hot/warm see if they need to add more nodes, etc...

**Comment by jasontedor** [comment]
I am still not understanding what is missing from the shard documents in the monitoring index that does not already provide what is being requested here. Can you please help me understand this?

> The idea is that they would like to run statistics on how ES moves shards around and then judge how efficient ES is handling this balancing.

I think this can be done with queries on the monitoring index.

**Comment by dliappis** [comment]
No further feedback received. @Gunnerva  if you have the requested information please add it in a comment and we can look at re-opening this issue.
