### ISSUE TITLE
Curator snapshot directly to amazon Glacier

### ISSUE THREAD

**Issue by lordcf** [elastic/elasticsearch#34509]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by ywelsch** [comment]
duplicates https://github.com/elastic/elasticsearch/issues/12500#issuecomment-375013311

**Comment by ywelsch** [comment]
no, it's not, as Glacier is not a good fit for the storage access patterns of our current snapshotting functionality (see comment that I linked to). A prerequisite for enabling direct Glacier support would be to decouple storage of metadata and data. We have no immediate plans to work on this.
