### ISSUE TITLE
Clear read only flag on indexes once disk space is available

### ISSUE THREAD

**Issue by dmitrymurashenkov** [elastic/elasticsearch#34510]
Currently elastic makes indexes read only if disk filled over 95% by setting flag on index:

`
index.blocks.read_only_allow_delete: true
`

Once we clean up the disk and space is available again - flag has to be cleared manually. For example like this:
`
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
`

It would be nice to have some automatic way to handle this situation.

Seems it would require some additional flag to tell us that this index was locked because of the low disk space and not explicitly by user.

**Comment by DaveCTurner** [comment]
Thanks for opening this issue @dmitrymurashenkov. The same idea was more recently suggested in #39334 and we discussed that as a team and agreed it was a good idea. There's little point in having both issues open, so although this one was opened first we added our collective thoughts in 
https://github.com/elastic/elasticsearch/issues/39334#issuecomment-467891057, so I am closing this as a duplicate. Please continue any discussion of this idea over on #39334.
