### ISSUE TITLE
must_not queries on nested types should also return parents without children 

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#34522]
This came from:  https://discuss.elastic.co/t/range-query-has-weird-results/149359

This query is supposed to return documents where there is not any nonAvailability as well as those that do not fall in the range. However, this query only returns documents that have nonAvailability values. Any documents with '[]' values (unlimited availability) do not return.

```http
"query": {
  "nested" : {
   "path" : "nonAvailability",
   "query" :  {
    "bool" : {
     "must_not" : [{
      "range" : {
       "nonAvailability.date" : {
        "gte" : "2018-07-01",
        "lt" : "2018-07-03",
        "relation" : "within"
       }
      }
     }]
    }
   }
  }
}
```

**Comment by mayya-sharipova** [comment]
One thing we can do is:
First get all parents are they are now returned  and join them with parents without any nested docs.

We can get all parents without any nested docs with the following query:

```http
GET _search
{
  "query": {
    "not": {
      "nested": {
        "path": "nonAvailability",
        "query": {
          "exists": {
            "field": "nonAvailability.date"
          }
        }
      }
    }
  }
}
```

**Comment by cbismuth** [comment]
Looks interesting! I’d like to work on this one.

**Comment by mayya-sharipova** [comment]
@cbismuth  Thank you for working on this. Now I am thinking about this, and it is a little more complex than I thought. We need to add parents without any children docs only in the case of `must_not` query on children. Also the query to find all parents without any children is not simple. 

I would like to ask @jimczi opinion on this. Jim is it really worth doing this considering complexity?

**Comment by jimczi** [comment]
The `must_not` clause is in a `nested` context so it can only match children documents. The `nested`  query only sees children document in the `innerQuery` and I don't think we should change that. 
One way to circumvent this limitation is to flip the `bool` and `nested` query:
```
{
	"query": {
		"bool": {
			"must_not": [
				{
					"nested" : {
						"path" : "nonAvailability",
						"query": {
							"range" : {
    							"nonAvailability.date" : {
        							"gte" : "2018-07-01",
        							"lt" : "2018-07-03",
        							"relation" : "within"
    							}
							}
						}
					}
				}
			]
		}
	}
}
```
This way the `must_not` clause is executed at the parent level and parent without children can match.

**Comment by mayya-sharipova** [comment]
After investigation with @jimczi, we have decided not to implement anything on the elasticsearch side, as it doesn't worth the complexity. Instead the user can address his problem with one of the following ways depending on his expectations regarding parents with mixed children (that satisfy and don't satisfy `must_not` criterion). 
**First** reversing nested and must. This will return parents without any children and parents that have children satisfying `must_not` criterion, but will miss some parents that have both children that satisfy and don't satisfy `must_not` criterion:

```js
{
  "query": {
    "bool": {
      "must_not": [
        {
          "nested": {
            "path": "nonAvailability",
            "query": {
              "range": {
                "nonAvailability.date": {
                  "gte": "2018-07-01",
                  "lt": "2018-07-03",
                  "relation": "within"
                }
              }
            }
          }
        }
      ]
    }
  }
}
``` 

**Second** is to combine the original query with another bool query that will give us parents without children. The query will be more complex but it should return all necessary parents.

```js
{
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must_not": {
              "nested": {
                "path": "nonAvailability",
                "query": {
                  "exists": {
                    "field": "nonAvailability.date"
                  }
                }
              }
            }
          }
        },
        {
          "nested": {
            "path": "nonAvailability",
            "query": {
              "bool": {
                "must_not": [
                  {
                    "range": {
                      "nonAvailability.date" : {
                        "gte" : "2018-07-01",
                        "lt" : "2018-07-03",
                        "relation" : "within"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
