### ISSUE TITLE
Unable to query after refresh

### ISSUE THREAD

**Issue by CrazyBeeline** [elastic/elasticsearch#34523]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.6.8

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):ubuntu-14.04

**Description of the problem including expected versus actual behavior**:
When I use  bulkrequest  index to  update some of the original data，
After refresh, the data queried is not the updated data, but the data that is not updated.
Consult the community God is my problem or bug?
Looking forward to your reply.

**Comment by jasontedor** [comment]
Without a reproduction, it will be difficult for us to validate the veracity of this issue. Would you be able to share a reproduction?

**Comment by jasontedor** [comment]
No additional feedback, closing.
