### ISSUE TITLE
Use fuzzy transpositions with an english stemmer

### ISSUE THREAD

**Issue by alexandremottet** [elastic/elasticsearch#34529]
**Describe the feature**:

Have the ability to detect fuzzy transpositions like "sahde" to "shade" when using an english stemmer

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2

**Plugins installed**: [] None

**JVM version** (`java -version`): java: command not found

**OS version** (`uname -a` if on a Unix-like system): Linux 4609d58f2f21 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I have the following documents :

```
{
  "title": "Understanding shading",
  "language": "en"
}
```
```
{
  "title": "Understanding shade",
  "language": "en"
}
```

I want to be able to search for a "sahde" title (with the misspelling) and have the two previous documents in the result.

With a default index, the following search queries will work and I will get the document with ```shade``` in it : 
```shade```, ```hsade```, ```sahde```, ```shdae```, ```shaed```

With an index that use an english stemmer, the following search queries will work and I will get the document with ```shade``` and ```shading``` in it :
```shade```, ```hsade```, ```shdae```

But the following queries will have no result :
```sahde```, ```shaed```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 0. Start the docker container
```docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elastic -d docker.elastic.co/elasticsearch/elasticsearch:6.4.2```

 1. Create the index ```PUT /teststemmer```
 ```
 {
  "settings": {
    "analysis": {
      "filter": {
        "english_stemmer": {
          "type":       "stemmer",
          "language":   "english" 
        }
      },
      "analyzer": {
        "english": {
          "tokenizer":  "standard",
          "filter": [
            "lowercase",
            "english_stemmer"
          ]
        }
      }
    }
  }
}
 ```

 2. Create the field mapping ```PUT /teststemmer/_mapping/article```
```
{
    "properties": {
        "title": {
            "type": "text",
            "analyzer": "english"
        }
    }
}
```

 3. Add the two documents

 4. Do this query ```POST /teststemmer/_search```
```
{
  "query": {
    "multi_match" : {
      "query" : "sahde",
      "fields" : [ "title" ],
      "fuzziness" : "1",
      "fuzzy_transpositions": true
    }
  }
}
``` 

**Provide logs (if relevant)**:

**Comment by alexandremottet** [comment]
My guess is that the stemmer filter is apply before the fuzziness algorithmic.

**Comment by romseygeek** [comment]
You're correct that fuzziness is applied after the stemmer.  Fuzzy queries work by expanding the output of the analysis chain against the terms dictionary, and there isn't really any way of doing things the other way around.

The english stemmer normalizes both `shade` and `shading` to `shade`, but normalizes `sahde` to `sahd`, which means that it is two edits away from `shade`, hence the miss.  You can try increasing the fuzziness factor to 2, but that of course has the trade-off of decreasing the precision of your results.

**Comment by romseygeek** [comment]
BTW, my usual response to issues with the english stemmer is to recommend trying the snowball stemmer and see if that helps, but it looks as though both of them leave the 'e' on the end of 'shade', so that won't help.

**Comment by alexandremottet** [comment]
Ok, thanks for the tips, I will try it.
I mainly wanted to know if it was possible to have an option to do the fuzzy stuff before the stem algorithm.
I've was thinking that having the fuzziness algorithm before the stemming was more logical but maybe I'm wrong.
