### ISSUE TITLE
We need restart tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#34524]
Right now we have "upgrade" tests but we don't have "restart" tests. It'd be good to have tests that assert that restarts work. Without them it is *possible* for us to break starting the current version of Elasticsearch  with a data directory made by the current version of Elasticsearch. That sounds far fetched when I type it but we've made mistakes like that. We caught them we we backported the change and added upgrade tests.

I think the simplest way to accomplish this is to use the change the rolling upgrade tests and the full cluster restart tests to work when "upgrading" from the current version. That isn't perfect because you still have to know to write a restart/upgrade test for a change that might cause restarts to fail but lets solve one thing at a time.

**Comment by atorok** [comment]
This is now implemented in  #39102
