### ISSUE TITLE
Tests for "flavor switching"

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#34526]
Right now we have tests for upgrading and in #34524 I proposed that we add tests for restarting. But we have very few tests for what I've been calling "flavor switching". It'd be nice to have test that starts the oss distribution of Elasticsearch, then stops that, installs that default distribution and starts that with a basic license, stops that, then installs gold license, etc, etc. It'd enable things like ssl as it goes. That way we have a test of going from these things disabled to these thing enabled. There are other secenarios along those lines, but a test like this'd be a good start.

**Comment by atorok** [comment]
I think #30904 will make this easier to accomplish.

**Comment by mark-vieira** [comment]
The OSS distribution is going away so this is OBE.
