### ISSUE TITLE
SQL: COUNT(column) takes into account NULLs

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34549]
Currently `COUNT(column)` has the same behavior as `COUNT(*)` when it comes to handling `NULL`s which is incorrect. The former should exclude them while the latter should not. This is further exacerbated when dealing with filtering (`HAVING`) and when dealing with missing/`NULL` groups.

The root of the problem is mapping count to the bucket count which doesn't take into account null groups (in which case the count should be 0).

**Comment by astefan** [comment]
Fixed as part of https://github.com/elastic/elasticsearch/issues/30285
