### ISSUE TITLE
SQL: Optimize constant queries to avoid doing any searches

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34579]
`SELECT 1 FROM foo` doesn't return any data from foo; rather it only displays the constant based on the number of items inside foo.
This can be optimized by using the _count API and thus avoid doing any searches.

**Comment by nik9000** [comment]
Would that be all that useful though? I mean, if this is a common idiom then, yeah, but it doesn't strike me as common.

**Comment by wchaparro** [comment]
Superceded by ES|QL
