### ISSUE TITLE
SQL: NULLS FIRST/LAST defaults

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34585]
Once #34550 is fixed the defaults for NULLS FIRST/LAST need to be changed.
According to both [Postgres](https://www.postgresql.org/docs/10/static/queries-order.html) and [Oracle](https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#SQLRF55368):

> NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

While for queries this is added, currently due to the way composite aggs work, for grouping the order is reversed. This needs to be aligned in the future.

**Comment by wchaparro** [comment]
Superceded by ES|QL
