### ISSUE TITLE
Add support for missing in ScriptSortBuilder

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34597]
`FieldSortBuilder` allows handling of null values through `missing` (`_first` and `_last`). 
As scripts can return `null`, the same feature would be quite convenient to have in `ScriptSortBuilder` since otherwise, scripts always have to return a non-`null` value which is tricky to position (first vs last).

**Comment by jimczi** [comment]
We discussed this internally and we agreed that this is something we want to support. This will allow scripts used in sort to return null values and we'll translate the value automatically based on the type of the field and the value used in the `missing` option.

**Comment by affanv14** [comment]
I'd like to take this on

**Comment by astefan** [comment]
Following @rjernst reply in the [PR opened for this issue](https://github.com/elastic/elasticsearch/pull/37513#issuecomment-465314108), I want to provide some more background to help with a decision for this issue.

In SQL, an user can do `SELECT first_name, SQRT(languages) AS sq FROM employees ORDER BY sq ASC NULLS FIRST` and the result would place the null values (missing values) - the square root of languages - as first in the result and after them order the rest of the results by the square root of the "languages" numeric values.

There are also functions in SQL that return string values (think of CONCAT, SUBSTRING etc) and when applied on missing values it would return a "missing" value.

The ORDER BY a function example above is basically using the `"sort": [{"_script": {"script": {` script sorting to work its magic. For functions that return numerics, we could use in scripts the Double min value or max value to place the missing values as first or last, but for strings there is no mechanism at the moment.

The _missing values in sorting_ functionality I believe is also inconsistent in Elasticsearch:
- it exists for simple fields
- it doesn't exist for `composite` aggs, but this is tracked [here](https://github.com/elastic/elasticsearch/issues/34221)
- it doesn't exist for script sorting

**Comment by rjernst** [comment]
> it doesn't exist for script sorting

That is by design. Scripts are meant to be an advanced feature that allows the user to completely control the behavior of an API (in this case, generating the value used for sorting documents). There is no need for `missing` in scripts because the scripts can return whatever they want (including using min/max values to mimic first/last behavior).

**Comment by jimczi** [comment]
We discussed this issue internally and decided that we'll not implement this feature. The script sort implies that the script must return a value for every document, there are multiple strategies that can be implemented when a field is missing so it is more flexible to implement them directly in the script. However for the case where creating a missing value in the script is not possible (string sort) we agreed that the solution should be to use two scripts sort, one responsible for sorting missing values first or last and the second one to tiebreak documents that create a value for the script. The solution could look like this:

```
sort" : [
      {
        "_script" : {
            "type" : "number",
            "script" : {
                "lang": "painless",
                # returns 1 if a field is missing, 0 otherwise (missing last)
                "source": "if (doc['country'].isEmpty() || doc[`city'].isEmpty()) { return 1; } else { return 0;}",
            },
            "order" : "asc"
        }
    },
    {
        "_script" : {
            "type" : "string",
            "script" : {
                "lang": "painless",
                "source": "doc['country'].value + "-" + doc[`city']",
            },
            "order" : "asc"
        }
    }
}
```
