### ISSUE TITLE
Throwing errors on bad filter arguments based on types

### ISSUE THREAD

**Issue by decima** [elastic/elasticsearch#34604]
I didn't encountered any problem running this filter:
```
PUT /my_index
{
    "settings": {
        "analysis" : {
            "analyzer" : {
                "my_analyzer" : {
                    "tokenizer" : "standard",
                    "filter" : ["standard", "lowercase", "my_snow"]
                }
            },
            "filter" : {
                "my_snow" : {
                    "type" : "snowball",
                    "langage" : "French"
                }
            }
        }
    }
}
```
(example taken from the documentation but misstyped on language/langage)
and 9 months later, we discovered that the snowball applied was English(default). 

It would have been great if elasticsearch prevented us :
"Illegal argument, unexpected [langage]" (or something like this).

**Comment by romseygeek** [comment]
This is part of a larger issue, which is that we don't have a good way of checking for misspelt or spurious analysis parameters in general, partly because they're defined using Settings rather than XContent.

**Comment by romseygeek** [comment]
Closing in favour of #41299, which deals with the wider problem rather than this specific issue.
