### ISSUE TITLE
SQL: add tests for RLIKE

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#34609]
At the moment, there are no tests for RLIKE. Testing quickly few things, seems to work, but would be good to have tests to ensure nothing breaks in the meantime.

**Comment by TomasNovo** [comment]
We can have a look on this one

**Comment by costin** [comment]
@TomasNovo sure, go ahead. Please see the contributing guide lines.

Thanks,

P.S. Not sure what do you mean by "we" but all contributors need to sign the CLA.

**Comment by astefan** [comment]
To take into consideration a similar problem like https://github.com/elastic/elasticsearch/issues/39931, for RLIKE as well.

**Comment by matriv** [comment]
Would be nice to revisit the classes Like/RLike as well.
`RLike` has a String `pattern` field which also exists in the parent `RegexMatch` class.
Also the `Like` has a field of type `LikePattern` but with the same name `pattern` which might
cause confusion.

/cc @costin Was maybe a purpose on this ^^ ?

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/7562d6eeeb77c04794002649fe726f4b3a9a398b
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/150d1332cf56337a1187fa01e6922d475a79f40a
7.0 (7.0.0): https://github.com/elastic/elasticsearch/commit/41eed003b2eacc790e0eff6592bb508ba63432e7
6.7 (6.7.1):  https://github.com/elastic/elasticsearch/commit/ca745dbb4f42e4256146ecdc3e9412ca49b41191
