### ISSUE TITLE
SQL : Support 'IN' clause

### ISSUE THREAD

**Issue by Johnb21** [elastic/elasticsearch#34622]
Currently, there is no ability to use the 'IN' clause within an elasticsearch SQL statement. The error returned is:

`{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Don't know how to translate In In[field_name{f}#530,[value]]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Don't know how to translate In In[field_name{f}#530,[value]]"
  },
  "status": 500
}`

Under the hood, this would translate into a `terms` condition with the field name and a comma separated array for the value:

`
'terms': {
  'field_name.keyword': [comma,separated,values],
}
`

**Comment by andyb-elastic** [comment]
Hi, implementation of `IN` with a list of values is in progress (#32955, #34581) so I'm going to close this. If those issues don't cover the use case you have in mind, can you provide more detail and we'll re-open this issue. Thanks
