### ISSUE TITLE
Improve IndexNotFoundException message - specify the index name

### ISSUE THREAD

**Issue by atapin** [elastic/elasticsearch#34628]
Currently I see the following stacktrace in logs: `Caused by: org.elasticsearch.index.IndexNotFoundException: no such index`. This makes finding a root cause hard in case of multiple indices. I suggest to populate the default error message with a missing index name:
```java
class IndexNotFoundException ... {
    public IndexNotFoundException(String index, Throwable cause) {
        super("no such index: " + index , cause);
        setIndex(index);
    }

    public IndexNotFoundException(Index index, Throwable cause) {
        super("no such index: " + index.toString(), cause);
        setIndex(index);
    }
}
```

**Comment by s1monw** [comment]
we include the index already in the toString etc. in ElasticsearchException. I still think it makes sense to include it in the way you suggested. do you wanna open a PR for this?

**Comment by atapin** [comment]
@s1monw yes, sounds great.

**Comment by atapin** [comment]
@s1monw I'm getting the error on `gradle check`:
```
FAILURE: Build failed with an exception.

* What went wrong:
JAVA7_HOME required to run tasks:
  :modules:reindex:oldEs2Fixture
  :modules:reindex:oldEs1Fixture
  :modules:reindex:oldEs090Fixture
```
Are these tasks mandatory? May be they can be skipped somehow.

**Comment by s1monw** [comment]
@atapin I think we are making progress to not require java7 for it. at this point it's necessary. You can just go and open a PR and we run tests for you on there.

**Comment by atapin** [comment]
@s1monw done

**Comment by s1monw** [comment]
@atapin we removed that java 7 requirement here https://github.com/elastic/elasticsearch/pull/34646
you should be able to run the build now.
