### ISSUE TITLE
Can highlight fields return line number?

### ISSUE THREAD

**Issue by bearsmall** [elastic/elasticsearch#34632]
can highlight fields return line number when getting the search result ?

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
