### ISSUE TITLE
[ILM] Add ILM action for freezing an index

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#34630]
When frozen indices are implemented (https://github.com/elastic/elasticsearch/issues/34352) we should add a new action to ILM so a user can freeze indices in the cold phase. The actual implementation of the action will depend on the final API for frozen indices.

**Comment by s1monw** [comment]
@colings86 is this still stalled? Can you point me to what needs to be done to close this issue?

**Comment by colings86** [comment]
@s1monw Since frozen indices is not implemented this is no longer stalled so I'll remove the label. Thanks for pointing this out. 

In terms of what needs to be done to have a freeze index action in ILM, we will need to implement a new ILM action and an `AsyncActionStep` to call the freeze API (it looks from the docs like the freeze API only returns when the index is frozen so I don't think we'll need a subsequent step to check the action has been completed like in other ILM actions). We will also need to update the allowed actions in the cold phase to allow the new freeze action. The `ForcemergeAction` might be a good template to use to see how an action is implemented.

**Comment by talevy** [comment]
@simonw I'm happy to help.

**Comment by talevy** [comment]
implementation can be found in this PR: https://github.com/elastic/elasticsearch/pull/36910
