### ISSUE TITLE
"can not write type [class java.math.BigInteger]" error for script parameters

### ISSUE THREAD

**Issue by bobbyi** [elastic/elasticsearch#34656]
Using ES 6.1.2 (on JVM 1.8.0_121), the following query works on a single-node cluster (unzipping the server dist and running on my laptop), but fails on our production multi-node cluster with "can not write type [class java.math.BigInteger]":

```
curl http://<host>:9200/<index>/<doctype>/_search -H 'Content-Type: application/json' -d '
{
   "query":{"match_all":{ } },
   "size":0,
   "aggs":{
      "the_agg":{
         "sum":{
            "script":{
               "lang":"painless",
               "inline":"params.limit",
               "params":{
                  "limit":100000000000000000000000000
               }
            }
         }
      }
   }
}
'
```

If I change the parameter from 100000000000000000000000000 to 100000000000000000000000000.0 or 1E+26 it works (presumably because it treats the value as a double instead of a BigInteger). However, that's not really a useable workaround for me because I simplified this example from an application case where I don't have direct control over the JSON serialization.

I saw issue #32395 (a related issue about BigIntegers) and @mayya-sharipova 's comments there, but I'm not sure if the commits for that issue also fix this one since that one is about source filtering.

I saw issue #26364 and the comments from @jdconrad / @nik9000 there . I'm not sure if this is duplicate or a closely related issue. It seems that the solution there was to write the application in Java with the Transport Client that will write the JSON so the value looks like a double, but I don't think that is a possible solution for everyone and think that there is an actual bug here in that the above query using curl does not work.

**Comment by rjernst** [comment]
I believe this was fixed by https://github.com/elastic/elasticsearch/pull/32888

**Comment by svobom57** [comment]
I experienced a similar issue while running this script:
```ruby
{
        bool: {
          filter: [
            {
              terms: {
                postcodes: postcode_fragments
              }
            },
            {
              nested: {
                path: 'locations',
                query: {
                  bool: {
                    filter: [{ term: { "locations.category_ids": category_id } }]
                  }
                },
                inner_hits: {
                  size: 100,
                  script_fields: {
                    distance_in_miles: {
                      script: {
                        params: { lat: latitude, lon: longitude },
                        source: <<-SCRIPT
                          double distanceInMeters = doc['locations.location'].arcDistance(params.lat, params.lon);
                          double distanceInMiles = distanceInMeters / 1609;
                          BigDecimal.valueOf(distanceInMiles).setScale(1, RoundingMode.HALF_UP)
                        SCRIPT
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      }
```
on AWS multi-node cluster 2 out of 3 nodes would be returning an error saying:
`"can not write type [class java.math.BigDecimal]"`.

This wasn't happening locally on a single node cluster.

The issue was mitigated by using `.floatValue()` on the last line of the script:
```
   BigDecimal.valueOf(distanceInMiles).setScale(1, RoundingMode.HALF_UP).floatValue()
```

We're running ElasticSearch `7.1` on AWS.
