### ISSUE TITLE
Improve rest-api-spec test runner to fail tests that use headers but don't list them in the skip section

### ISSUE THREAD

**Issue by estolfo** [elastic/elasticsearch#34650]
I'm raising this issue after submitting a [pull request](https://github.com/elastic/elasticsearch/pull/34551) to add `headers` to the `skip` section of some tests that were missing it. I'm requesting that the Elasticsearch test runner fail tests that use features--specifically `headers`-- but don't include those features in the `skip` section.

I became aware of this issue when the Ruby client tests were failing against the latest `rest-api-spec` tests because some tests used headers but didn't specify `features: headers` in the `skip` section. The Ruby client doesn't support headers and wasn't able to properly skip these tests.

**Comment by estolfo** [comment]
cc @elastic/es-clients

**Comment by javanna** [comment]
I opened #34735
