### ISSUE TITLE
[Painless] custom LM relevance equation not possible in Similarity context without acess to query terms

### ISSUE THREAD

**Issue by lemontheme** [elastic/elasticsearch#34679]
Hi,

I'm trying to gauge whether elasticsearch is a good fit for future projects by taking a deep dive into the Painless API. We're an NLP shop with tight deadlines. The prospect of being able to write custom similarity functions *without* having to create a full-blown Java plugin is prettttty interesting.

So, one of the things I'm looking into is whether it's possible to implement a custom [language model](https://www.elastic.co/blog/language-models-in-elasticsearch)-based Similarity. For example: a similarity that defines relevance in terms of the Kulback-Leibler divergence between a document generation and a [query generation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#lm_jelinek_mercer) model. In order to do this though, I need access to the terms that occur in the query, something which the Painless API currently does not provide for in the [Similarity context](https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-similarity-context.html#painless-similarity-context), or in any context, for that matter. In fact, I can't really see how 'Scriped Similarities' (as demonstrated [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#scripted_similarity)) allow for much more than writing variations on the TF-IDF weighting scheme.

Unless I'm missing something (please tell me if I am; I would realllly like to be able to use elasticsearch) – would it be possible to open up access to the `query` variable in the Similarity context?

Apologies in advance if it's unclear what I'm asking for. What it comes down to, I suppose, is that Scripted Similarities don't really feel like first-class relevance functions at the moment. Their scope seems to be the individual terms in the term vector, which is pretty restrictive.

**Comment by atorok** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by lemontheme** [comment]
No worries. I'll hop over to the forum then!
