### ISSUE TITLE
[CI] GetUserPrivilegesResponseTests fails

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#34671]
log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/6/console

REPRODUCE WITH:
```
 ./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=7374C845561C5B75 \
  -Dtests.class=org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests \
  -Dtests.method="testSerialization" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CL \
  -Dtests.timezone=Pacific/Ponape \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

another seed to reproduce locally ```-Dtests.seed=FD8FA9CE99873F9```

Relates to #33928

**Comment by albertzaharovits** [comment]
@vladimirdolzhenko the failure is using commit c1c447a which is an ancestor of  aeb3cda which I've pushed to fix https://github.com/elastic/elasticsearch/issues/34631 .
I'll be closing this, please reopen if you believe I'm mistaking.
