### ISSUE TITLE
Should we rename leader_cluster to remote_cluster in CCR APIs?

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#34682]
In some of the CCR APIs, we need to refer to the remote cluster alias of the cluster that holds the leader index. We have been calling this the `leader_cluster` For example:

```
PUT /<follower_index>/_ccr/follow
{
  "leader_cluster" : "<leader_cluster>",
  "leader_index" : "<leader_index>"
}
```

Should we rename this to `remote_cluster` instead? This is more consistent with the terminology of the remote cluster infrastructure, and it avoids using the terminology leader cluster which is not really a concept in CCR (we have leaders at the index level, not the cluster level).

**Comment by jasontedor** [comment]
@bleskes @martijnvg Your input would be appreciated here.

**Comment by martijnvg** [comment]
@jasontedor I agree, `remote_cluster` matches better the current remote cluster infrastructure terminology.

**Comment by bleskes** [comment]
+1 to the suggestion. It feels more natural now that we split the config into two fields. I feel that the `leader_index` field naming is enough to convey what the intention of the API is and agree that we better align the cluster field with the remote cluster terminology.
