### ISSUE TITLE
[DOCS] Add SAML troubleshooting doc

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#34690]
There's a handful of common setup issues for SAML that create confusion for users, but are hard to solve technically.

A trouble shooting document for SAML may help users understand how to work through these problems.

Specific examples:

### Incorrect ACS URL
The error
```
org.elasticsearch.ElasticsearchSecurityException: Cannot find any matching realm for
[SamlPrepareAuthenticationRequest{realmName=null,
assertionConsumerServiceURL=https://my.kibana.url/api/security/v1/saml}]
```
can usually be resolved by either changing the `sp.acs` in the elasticsearch config, or the `xpack.security.public.*` settings in kibana. The correct choice between those options _depends_, but can be documented.

### Incorrect IdP Id or Metadata
```
org.elasticsearch.ElasticsearchSecurityException: 
Cannot find metadata for entity [your:entity.id] in [metadata.xml] 
```
We're looking for `idp.entity_id` ("your:entity_id") in the configured metadata file ("metadata.xml"), but can't find it.
Either ther entity id has been configured incorrectly, or the wrong metadata file is being used.

### Want to login with standard Kibana username/password
Sometimes users are surprised when turning on SAML prevents logging in with a Kibana username & password. [We document how to do this](https://www.elastic.co/guide/en/elastic-stack-overview/6.3/saml-kibana.html#_supporting_saml_and_basic_authentication_in_kibana) but I think it's worth having it as a specific section in the trouble shooting.

### Authentication fails with confusing error
```
unable to authenticate user [<unauthenticated-saml-user>]
for action [cluster:admin/xpack/security/saml/authenticate]
```
The use of `unauthenticated-saml-user` here sometimes confuses people (which is understandable - it wasn't a great choice of error message).
This simply means that we failed to process the incoming saml authentication message for some reason. (It says "unauthenticated-saml-user" because we don't actually know the userid that the message is intended to be for until we've successfully processed it).
To diagnose _why_ authentication failed, the admin needs to check the Elasticsearch logs.

### IdP rejected authentication
```
Authentication to realm my-saml-realm failed - 
Provided SAML response is not valid for realm saml/my-saml-realm 
(Caused by ElasticsearchSecurityException[SAML Response is not a 'success' response:
Code=urn:oasis:names:tc:SAML:2.0:status:AuthnFailed Message=null Detail=null])
 ```
(In some cases the `Code` might be a different error identifier).

This means that there was a problem in the Identity Provider side, and it sent an error code back to the Elastic stack.
Because the `Message` and `Detail` are both `null`, it is not possible to diagnose the problem here. The IdP admin will need to consult the logs/documentation for the IdP to see why it sent an error  code.

**Comment by jkakavas** [comment]
We could add that the ACS are matched as strings and not as canonicalized URLs  in the `Incorrect ACS URL` section - I find myself mentioning this a lot. 

We could possibly add a section on how to enable the trace logging and what kind of troubleshooting information they could find in the logs

Finally we could add a section explaining what `Signature cannot be verified` means (although I must admit I don't see many issues where the problem were misconfigured Keys )

**Comment by evensonic** [comment]
It would also be helpful to show which log level(s) to change and how to change them.
