### ISSUE TITLE
SQL return null pointer when only nested field

### ISSUE THREAD

**Issue by czjxy881** [elastic/elasticsearch#34698]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.4.0
**Plugins installed**: []
x-pack
**JVM version** (`java -version`):
1.8
**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
+ SQL return null pointer when only has nested field

**Steps to reproduce**:
+ this can be reproduce on demo.elastic.co https://demo.elastic.co/app/kibana#/dev_tools/console

```
POST _xpack/sql?format=json
{
  "query":"SELECT products.price, products.product_id FROM orders WHERE order_id=519894"
}
```
![image](https://user-images.githubusercontent.com/3929477/47283590-914a7280-d616-11e8-903b-771201b1b8c5.png)
+ we found the cause of this problem is the `store_fields` in translate, it shouldn't be null when nested query
![image](https://user-images.githubusercontent.com/3929477/47283636-b50db880-d616-11e8-93fe-17618eac3205.png)

**Comment by albertzaharovits** [comment]
Thank you @czjxy881 for reporting this!
This is, however, a known bug and it is tracked in https://github.com/elastic/elasticsearch/issues/30054.
I'll be closing this as a duplicate.
