### ISSUE TITLE
[CCR] Limit the write buffer by memory rather than op count

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#34705]
Currently we stop sending read requests if the number of operation waiting to sent as a write bulk is higher than a given number. That was the simplest to implement but it makes it harder to reason about a good value - the ultimate goal of setting a limit is to protect against memory consumption. I think we should move to a byte sized based limit.

/cc @jasontedor @martijnvg

**Comment by jasontedor** [comment]
This was part of the initial plan, we should implement this now indeed. I discussed this with @martijnvg in another channel and he will proceed with the implementation.

One thing I'm unsure of is this should be a *move* to a byte-sized based limit as opposed to having the possibility of either (and enforcing both). I lean towards the latter.
