### ISSUE TITLE
Bug: cluster routing allocation exclude setting after node restart

### ISSUE THREAD

**Issue by redlus** [elastic/elasticsearch#34707]
Hi,

We're experiencing a weird behavior on our cluster after one of the nodes restarted (OOM exception): a new cluster setting appears which excludes this node from the allocation of shards, i.e. `"cluster.routing.allocation.exclude._name": "elasticsearch-cold-2"`.

**Elasticsearch version**:
6.3.2

**Plugins installed**:
ingest-geoip
ingest-user-agent
mapper-murmur3
mapper-size
repository-azure
repository-gcs
repository-s3

**JVM version**:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**OS version**:
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After one of the cluster nodes restarted (encountered an OOM exception), re-joined the cluster and all delayed unassigned shards have recovered, we've noticed that the cluster still moves shards away from that node. Following some investigation, we noticed a new setting showed up under `_cluster/settings`:
```
{
  "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "exclude": {
            "_name": "elasticsearch-cold-2"
          }
        }
      }
    }
  }
}
```

**Steps to reproduce**:
 1. Ramp up a cluster with several data nodes.
 2. Wait for a node to crash (...)
 3. Enjoy your new setting under `_cluster/settings`

We have no idea why this setting showed up, and have definitely not PUT it ourselves. The fact this setting continues to exist even after the cluster has gone green (under `_cluster/health`) is even more disturbing and demands manual inspection.

Why does this happen?
How do we prevent it from happening again?

Thanks

**Comment by albertzaharovits** [comment]
Hi @redlus 

This looks like outside-Elasticsearch intervention. Probably the same "someone" that restarted the JVM process on OOMing. That is, "someone" called:
```
curl -X PUT "localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
  "transient" : {
    "cluster.routing.allocation.exclude._name" : "<name of the node I have restarted>"
  }
}
'
```
Do you have the logs from when this happened?

**Comment by redlus** [comment]
@albertzaharovits You're right, the Helm chart included such a setting which included a bug upon starting the node. Thanks for the hint.
