### ISSUE TITLE
[CCR] Fetches/indexing/writes/reads/bulks in status fields vs readers in task params

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#34703]
The status reports for the following tasks often refer to fetches (`number_of_successful_fetches`,`number_of_failed_fetches`, `total_fetch_time_millis`,`fetch_exceptions`). We also have a similar term (which is identical in meaning) call reads (`number_of_concurrent_reads`). We also have the generic `operations_received` and `total_transferred_bytes` and `last_requested_seq_no`.

On the write sides we have `bulk` (`number_of_successful_bulk_operations`, `number_of_failed_bulk_operations`) and `writes` (`number_of_concurrent_writes`, `number_of_queued_writes` <-- note the different semantics here).

I think we should align our terminologies across the various places. I personally like the `read` versus `write` and `bulk` vs `ops`. Howabout:

- `number_of_succesful_bulk_reads` 
- `number_of_failed_bulk_reads`
- `total_bulk_read_time`
- `number_of_ongoing_bulk_reads` 
- `total_operations_read`
- `total_bytes_read`
- `last_requested_seq_no_for_reads`
- `number_of_successful_bulk_writes`
- `number_of_failed_bulk_writes`
- `number_of_ongoing_bulk_writes` 
- `number_of_queued_ops_to_write` (not too happy with this one)

/cc @jasontedor @martijnvg

**Comment by bleskes** [comment]
@chrisronline FYI. What ever ends up being deciding here will need a quick update on the UI side.

**Comment by bleskes** [comment]
@jasontedor @martijnvg and me iterated on this and came up with the following namings. I mark this as a blocker for 6.5.0:

```
Stats

remote_cluster
leader_index
follower_index
shard_id
leader_global_checkpoint
leader_max_seq_no
follower_global_checkpoint
follower_max_seq_no
last_requested_seq_no
outstanding_read_requests
outstanding_write_requests
write_buffer_size(_in_bytes)
write_buffer_operation_count
follower_mapping_version
total_read_time_millis
total_read_remote_exec_time_millis
successful_read_requests
failed_read_requests
operations_read
bytes_read
total_index_time_millis
successful_write_requests
failed_write_requests
operations_written
read_exceptions
time_since_last_read_millis

Params

remote_cluster
leader_index
max_read_request_operation_count ***
max_read_request_size
max_write_request_operation_count ***
max_write_request_size
max_outstanding_read_requests
max_outstanding_write_requests
max_write_buffer_size
max_write_buffer_count
max_retry_delay
read_poll_timeout
```

**Comment by chrisronline** [comment]
Looks good.

I'm going to list the fields we are using in the UI and my best guess as to the new field name:

- `fetch_exceptions` -> `read_exceptions`
- `time_since_last_fetch_millis` -> `time_since_last_read_millis`
- `number_of_operations_indexed` -> `operations_read`

The rest seem unchanged.

Is this accurate on terms of the renames?
