### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by wangzhenhui1992** [elastic/elasticsearch#34700]
**Describe the feature**:
As the document is shown on elastic website below:
 [https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-requests.html#java-rest-low-usage-request-options](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-requests.html#java-rest-low-usage-request-options)

Using the code below , we should be able to create a `RequestOptions`,but it had a compile error because of `HeapBufferedResponseConsumerFactory`.

The source in [RestClientDocumentation.java](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/test/java/org/elasticsearch/client/documentation/RestClientDocumentation.java) is right of course because it imported the class with`import HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory`  

But for developers it will not be automatically imported in Eclipse. and I need to read the ElasticSearch java resource to find and import the class or go to github to read the sample. 

So, I want to improve it and make it more developer friendly that every beginner can use it with copy simply.

**Code on website**
```
private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    builder.setHttpAsyncResponseConsumerFactory(           
        new HeapBufferedResponseConsumerFactory(30 * 1024 * 1024 * 1024));
    COMMON_OPTIONS = builder.build();
}
```
**Code in RestClientDocumentation.java**
```
import org.elasticsearch.client.HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory;
...
...
private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    builder.setHttpAsyncResponseConsumerFactory(           
        new HeapBufferedResponseConsumerFactory(30 * 1024 * 1024 * 1024));
    COMMON_OPTIONS = builder.build();
}
```

**Code modified**
```
import org.elasticsearch.client.HttpAsyncResponseConsumerFactory.;
...
...
private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    builder.setHttpAsyncResponseConsumerFactory(           
        new HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory(30 * 1024 * 1024 * 1024));
    COMMON_OPTIONS = builder.build();
}
```

**Comment by albertzaharovits** [comment]
In the interest of brevity and for conformance with all the other example snippets, I think it's better to keep it simple and not include import statements in the snippets . If the project is set up correctly I think the IDE should be able to resolve imports.

**Comment by wangzhenhui1992** [comment]
@albertzaharovits 
Thank you for you response.I want to modify the Java source and make the document like below.
```
private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    builder.setHttpAsyncResponseConsumerFactory(           
        new HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory(30 * 1024 * 1024 * 1024));
    COMMON_OPTIONS = builder.build();
}
```
It will not show the import statements in the snippets even if I do modify the import statements, because  the document just quote the previous part of RestClientDocumentation.java, right?

**Comment by wangzhenhui1992** [comment]
@albertzaharovits Thank you!
PR : #34727
