### ISSUE TITLE
Data path and migration ES 2.x -> 5.x -> 6.x

### ISSUE THREAD

**Issue by bsibaud** [elastic/elasticsearch#34717]
**Elasticsearch version** (`bin/elasticsearch --version`):

2.3.5 -> full cluster upgrade -> 5.5.2 -> reindex + full cluster upgrade -> 6.2.4 (without plugin)

(same issue with 2.4.6 -> full cluster upgrade -> 5.6.10 -> reindex + rolling upgrade -> 6.2.4 anyway)

**Plugins installed**: []

**JVM version** (`java -version`): 

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

CentOS 7 (amd64)

**Description of the problem including expected versus actual behavior**:

It looks like
- ES 2.x reads/writes in "path.data / cluster.name"  directory
- ES 2.x migrated into ES 5.x,  reads/writes in "path.data / cluster.name"  directory too
- but new installation of ES 5.x reads/writes in "path.data" directory
(so ES 5.x is able to read/write in both "path.data/cluster.name" and "path.data" directories)
- migrated or new ES 6.x reads/writes in "path.data" directory only.

So indices migrated from ES 2.x to 5.x (and reindexed) are not available in ES 6.x.

I needed to move files from "path.data / cluster.name" into "path.data" to recover previous indices.

As far as I know, this caveat is not mentioned in Breaking Changes or Upgrade process.
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html only mentions "You must delete or reindex any indices created in 2.x before upgrading." but that's not enough (you need to reindex, but also to move data on disk or change your path.data).

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. install ES 2.3.5 mono-node
 2. insert a document
 3. stop and full cluster upgrade to ES 5.5.2
 4. insert new document
 5. reindex former document from ES 2.3.5 to be ES 6.x compatible
 6. stop and full cluster upgrade to ES 6.2.4
 7. insert new document
 8. list indices: only the last document from ES 6.x is available (because data from ES 2.x/5.x is stored in  "path.data / cluster.name" and ES 6.x has started to store in "path.data" only).

**Comment by DaveCTurner** [comment]
Duplicates https://github.com/elastic/elasticsearch/issues/32661 (which at least links to the places in the breaking changes docs that this is mentioned). It's a valid point but we already have an issue open for this.
