### ISSUE TITLE
HttpAsyncResponseConsumerFactory uses an int to store the size in bytes

### ISSUE THREAD

**Issue by bwf93** [elastic/elasticsearch#34723]
**Elasticsearch version** 6.4.1

We have a custom plugin that we developed ourselves

**JVM version** (`java -version`): Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

**OS version** (`uname -a` if on a Unix-like system): 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

The class HttpAsyncResponseConsumerFactory has a buffer limit that is the number of bytes that its buffer can hold.  If you try setting this buffer to a size of around 300 MB the buffer size will overflow since it is stored as an int.  This should be a long so that a large buffer can be allocated.  If a request returns a large JSON document this can exceed the largest size that can be requested with an int.

**Comment by javanna** [comment]
good point @bwf93 , have you closed the issue intentionally? I had a look at this and I think the reason is that `org.apache.http.nio.util.SimpleInputBuffer` accepts an `int` as `bufferSize` constructor arguments. This looks fishy though.
