### ISSUE TITLE
Simplify if-clause by getting rid of redundant comparison

### ISSUE THREAD

**Issue by atapin** [elastic/elasticsearch#34740]
https://github.com/elastic/elasticsearch/blob/183c32d4c39948e037a7fb44dccf31ab0d60d3c3/server/src/main/java/org/elasticsearch/action/support/AutoCreateIndex.java#L75

Can be replaced with:
```
if(!autoCreate.autoCreateIndex) {
```

**Comment by atapin** [comment]
@vladimirdolzhenko @s1monw 
Full text search by term `== false` throughout the project gives 100+ occurrences. Can this be a convention?

**Comment by atapin** [comment]
67 occurrences of `== true`. That looks strange in the code.

**Comment by colings86** [comment]
We prefer using `if (X == false)` to `if (!X)` as it can be easy to miss the `!` in an expression when reading through code which can lead to misunderstandings and mistakes.

As for the occurrences of `== true` this may also be for readability but I do not know as I'd have to look at all the cases to be sure.

Given the above and given that I don't think either of these cases will cause any explicit issues or bugs when running Elasticsearch I hope you don't mind if I close this issue.


Also, please don't randomly ping people on issues. Issues will be followed up by someone interested/familiar with the area in question and random pings add noise especially if the person being pinged is not relevant to the discussion.
