### ISSUE TITLE
How to boost certain fields in a custom '_all' field when use a match query

### ISSUE THREAD

**Issue by laoyao789** [elastic/elasticsearch#34742]
Elasticsearch version 6.4.0
some segment about mappings

"product_name": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart",
           "boost": 10,
           "copy_to": "keyword_query"
        },
"standard": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart",
          "copy_to": "keyword_query"
        }，
"keyword_query":{
          "type":"text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart"
        },

I boost  'product_name' filed at index-time,  use  match query with 'keyword_query' field,  'product_name' filed not be boosted

**Comment by dakrone** [comment]
Hi @laoyao789,

We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!
