### ISSUE TITLE
Some documented KV Filter options are not supported in 6.4.2

### ISSUE THREAD

**Issue by martinwaite** [elastic/elasticsearch#34744]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.4.2, Build: default/rpm/04711c2/2018-09-26T13:34:09.098244Z, JVM: 1.8.0_191

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux myhost 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Some of the documented configuration options for KV Filter ingress processor are not supported.

"recursive" and "allow_duplicate_values" options cannot be used.

**Steps to reproduce**:

1. recursive option:
```
cat kv.json
{
  "description": "KV",
  "processors": [
    {
      "set" : {
        "field": "pipeline",
        "value": "kv"
      }
    },
    {
      "kv": {
        "recursive": false,
        "field": "kv",
        "prefix": "kv_",
        "value_split": "=>'",
        "field_split": "',",
        "ignore_missing": true,
        "trim_value": "'"
      }
    }
  ]
}

curl -X PUT http://myhost:9200/_ingest/pipeline/kv -H "Content-Type: application/json" -T kv.json
{"error":{"root_cause":[{"type":"parse_exception","reason":"processor [kv] doesn't support one or more provided configuration parameters [recursive]","header":{"processor_type":"kv"}}],"type":"parse_exception","reason":"processor [kv] doesn't support one or more provided configuration parameters [recursive]","header":{"processor_type":"kv"}},"status":400}
```

 2. allow_duplicate_values option

```
 cat kv.json
{
  "description": "KV",
  "processors": [
    {
      "set" : {
        "field": "pipeline",
        "value": "kv"
      }
    },
    {
      "kv": {
        "allow_duplicate_values": true,
        "field": "kv",
        "prefix": "kv_",
        "value_split": "=>'",
        "field_split": "',",
        "ignore_missing": true,
        "trim_value": "'"
      }
    }
  ]
}

curl -X PUT http://myhost:9200/_ingest/pipeline/kv -H "Content-Type: application/json" -T kv.json
{"error":{"root_cause":[{"type":"parse_exception","reason":"processor [kv] doesn't support one or more provided configuration parameters [allow_duplicate_values]","header":{"processor_type":"kv"}}],"type":"parse_exception","reason":"processor [kv] doesn't support one or more provided configuration parameters [allow_duplicate_values]","header":{"processor_type":"kv"}},"status":400}
```

**Provide logs (if relevant)**:

**Comment by spinscale** [comment]
is it possible that you took those options from the [logstash docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/kv-processor.html) as they are not mentioned in the [elasticsearch kv processor docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/kv-processor.html)?

**Comment by martinwaite** [comment]
Indeed that seems to be the case.

Both the links you sent point to the elasticsearch version - the logstash
version is here:

https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html

Sorry to waste your time - please close the issue.

regards,
Martin

**Comment by spinscale** [comment]
thanks a bunch for confirming (and sorry for the link mess), appreciate the quick feedback!
