### ISSUE TITLE
[DOCS]: "Auditing Security Events" gray code box can be confusing

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#34757]
https://www.elastic.co/guide/en/elastic-stack-overview/current/auditing.html

The layout here has led to some confusion.  The darker gray box draws the eye and users have set the audit outputs without enabling "xpack.security.audit.enabled" because they overlooked the lighter shaded box above it (even with the big IMPORTANT warning).  This is an easy thing to miss if your eye goes directly to the code block.  Maybe a code block for the xpack.security.audit.enabled setting would avoid the issue?

**Comment by jrodewig** [comment]
This issue is now visible at https://www.elastic.co/guide/en/elastic-stack-overview/6.7/auditing.html.

It looks like this was solved in 7.0: https://www.elastic.co/guide/en/elastic-stack-overview/7.0/auditing.html

Might still be worth changing for 6.7 and earlier though.

**Comment by debadair** [comment]
[docs issue triage]

Closing as won't fix. We are only updating version 6.7 and earlier of the docs to fix critical issues.
