### ISSUE TITLE
SQL: Support null handling for all functions

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#34752]
Binary logic operators currently throw an Exception when null is involved:
```SELECT true or null, false or null, null or null, true and null, false and null, null and null;```
throws:
```
java.sql.SQLDataException: Found 6 problem(s)
line 1:8: '||' requires type BOOLEAN not NULL
line 1:22: '||' requires type BOOLEAN not NULL
line 1:37: '||' requires type BOOLEAN not NULL
line 1:51: '&&' requires type BOOLEAN not NULL
line 1:66: '&&' requires type BOOLEAN not NULL
line 1:82: '&&' requires type BOOLEAN not NULL
```

Double check all functions and handle DataType.NULL in a common place (if possible).

**Comment by costin** [comment]
Relates to #34826, i.e. this should be handled in the optimizer.
