### ISSUE TITLE
I hope that elasticsearch can also be used on Android mobile phones.

### ISSUE THREAD

**Issue by ithjz** [elastic/elasticsearch#34788]
I hope that elasticsearch can also be used on Android mobile phones.

Are there any APK downloads related to elasticsearch?

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.
We do not support Elasticsearch running directly on Android, nor do we provide APK downloads.

There are a number of ways to use Elasticsearch within an Android Application, but such discussions are better suited to our [forums](https://discuss.elastic.co/). If you can ask your question there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help with your question.
As such, I hope you don't mind that I close this.
