### ISSUE TITLE
Incorrect xhyve vm login instructions in Docker guide

### ISSUE THREAD

**Issue by cachance7** [elastic/elasticsearch#34817]
**Elasticsearch version**: 6.4.2 (current)

**Plugins installed**: []

**OS version**: OSX 10.13.6

**Docker For Mac version**:  18.06.1-ce-mac73 (26764)

**Description of the problem**:

The following page now states an incorrect command to run to log into the xhyve virtual machine for setting `vm.max_map_count` in recent Docker for Mac releases. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Listed command: 
`screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`

Working command:
`screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty`

**Comment by dliappis** [comment]
Thanks for the report @cachance7 !

I raised https://github.com/elastic/elasticsearch/pull/35755 to address this.
