### ISSUE TITLE
SQL: Implement XPackFeatureSet & co

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34821]
Currently SQL doesn't register its own `XPackFeatureSet` which while not critical, doesn't provide rich metadata about the plugin

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/00e6fec718b7e1ae9c3c9ec2968a5af4b51870b9
6.6.0 (6.x): https://github.com/elastic/elasticsearch/commit/32015f76d8842e3f4b49d0692ce09baa6983fb24
https://github.com/elastic/elasticsearch/commit/fc9485511f41a54f1761e61617e957115e73c241
