### ISSUE TITLE
SQL: migrate/enable left-over tests IT tests

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34824]
During the various code moves, some integration tests got left behind and are currently not being ran.
In particular the action tests (under `org.elasticsearch.xpack.sql.action`) compile but do not run and their testing infrastructure is not working.
This needs to be fixed (potentially through mocking).

**Comment by matriv** [comment]
Issue has been fixed with #37300.
SqlLicenceIT still not working and tracked with #37320.
