### ISSUE TITLE
Ingest-attachment plugin in elasticsearch 6.1.2 takes double the time than mapper-attachments in 2.3.2

### ISSUE THREAD

**Issue by ropal** [elastic/elasticsearch#34849]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.2

**Plugins installed**: [analysis-phonetic, ingest-attachment]

**JVM version** (`java -version`): 1.8.0.171

**OS version** (`uname -a` if on a Unix-like system): Windows 2012 R2

**Description of the problem including expected versus actual behavior**:  Attachment indexing is much slower in ES 6.1.2 using ingest-attachment plugin when compared to mapper-attachments in 2.3.2 version. Taking almost double the time which has reduced the indexing performance after upgrading from 2.3.2 to 6.1.2. 

**Steps to reproduce**:

 1.   Index attachments using both mapper-attachment and ingest-attachment plugin. Time difference of almost double the time taken by ingest attachment can be viewed. 
2.    Heap allocated : 4GB

**Provide logs (if relevant)**:
For a 20MB txt file following are the time taken by the plugins:
Ingest-attachment-6.1.2 -----------> 2.562 seconds
Mapper-attachment-2.3.2 --------->  1.668 seconds

**Comment by shamzeer** [comment]
This issue apparently is worse as the file size grows. anything less than on the order of 100K is at par with mapper plugin. However as the fiel size grows to 5MB/10MB etc, the performance lags 3/5 fold in some cases.

**Comment by dadoonet** [comment]
Do you remove the BASE64 content in the pipeline? If not, do you change the default mapping for this field? 
If not, you are probably indexing a big BASE64 text as a text and as a keyword, which is probably not a good thing.
My 2 cents.

**Comment by ropal** [comment]
We are removing it from the _source using the excludes as shown below:
`{
"mappings":
      {"test_type":
         {"_source": 
            {
             "excludes": ["data"]  
            }
       }
    }
}`

and in the pipeline we have given the target_field as below.

`{
  "description" : "attachment data",
  "processors": [{
        "attachment": {
            "field": "data",
            "target_field": "data_1",
            "indexed_chars": -1,
            "ignore_missing": true
        }
    }]
}`

**Comment by dadoonet** [comment]
Could you try to add a [remove processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html) in your pipeline to remove the field `data`?

**Comment by shamzeer** [comment]
Thanks for the suggestion.There is some improvement when remove processor is used. Though there is still lag, remove processor helps in gaining some. This also reduces the storage space needed.
Perhaps there is some lag expected in ingest attach compared to the mapper parser, due to the additional overhead in copy to pipeline etc?

**Comment by dadoonet** [comment]
Yes. There is a difference in how things are done. Also note that indexation process in older version vs newer versions might be different. Doc values can be computed at index time where they were not in 2.x series IIRC.

**Comment by martijnvg** [comment]
Closing as no further information was provided and @dadoonet assessment makes sense.
