### ISSUE TITLE
difference in ingesting object via standard syntax[{}] against dot[.] seperated syntax

### ISSUE THREAD

**Issue by sebastianTC** [elastic/elasticsearch#34842]
**Elasticsearch version** (`bin/elasticsearch --version`): 
6.4.2

**Plugins installed**: []

**JVM version** (`java -version`):
Java x64 8.0.1910.12

**OS version** (`uname -a` if on a Unix-like system): 
Windows 7 and Debian 9.5

**Description of the problem including expected versus actual behavior**:
**Expected:**
When autocreating a index via posting a object in the following too cases there shouldn't be any difference after getting the data back via GET command:

case 1:
`POST /test1/_doc/test1
{
  "testobject":{
    "testproperty":"testvalue"
  }
}`

case 2:
`POST /test2/_doc/test2
{
  "testobject.testproperty":"testvalue"
}`

**What happenes:**
The same mapping is generated. This is fine.:

case 1:
`{
  "test1": {
    "mappings": {
      "_doc": {
        "properties": {
          "testobject": {
            "properties": {
              "testproperty": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`

case 2:
`{
  "test2": {
    "mappings": {
      "_doc": {
        "properties": {
          "testobject": {
            "properties": {
              "testproperty": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}`

The data which I see after requesting via GET is different in both cases:

case 1 correctly as object: 
`{
  "_index": "test1",
  "_type": "_doc",
  "_id": "test1",
  "_version": 1,
  "found": true,
  "_source": {
    "testobject": {
      "testproperty": "testvalue"
    }
  }
}`

case 2 in dot separated syntax:
`{
  "_index": "test2",
  "_type": "_doc",
  "_id": "test2",
  "_version": 2,
  "found": true,
  "_source": {
    "testobject.testproperty": "testvalue"
  }
}`

Where does the dot syntax come from, when the mapping is the same?

**Steps to reproduce**:
 1. Open Kibana Dev Tools/Console

 2. Send `POST /test1/_doc/test1
{
  "testobject":{
    "testproperty":"testvalue"
  }
}`
 3. Send `POST /test2/_doc/test2
{
  "testobject.testproperty":"testvalue"
}
`
 4. Check the mappings with `GET /test1/_mapping/_doc/` and `GET /test1/_mapping/_doc/`
     They should be the same.
 5. Request the save data with `GET /test1/_doc/test1` and `GET /test2/_doc/test2`
     They will be in a different syntax.

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
hi @sebastianTC , you simply get back what you initially posted. Elasticsearch stores the original document and returns it at retrieval time as-is. This behaviour sounds correct to me.
