### ISSUE TITLE
Rollover Index Cron Scheduler

### ISSUE THREAD

**Issue by sachinfrayne** [elastic/elasticsearch#34841]
**Describe the feature**: Cron style scheduler for the Rollover Index API.

Atomically run the Rollover Index API on a schedule, a `time_of_day` condition, so to speak.

**Comment by jasontedor** [comment]
This is one piece of functionality that index lifecycle management will enable, roughly. Can you share why that is not enough?

**Comment by gwbrown** [comment]
@sachinfrayne It seems like ILM will fulfill this request once we implement https://github.com/elastic/elasticsearch/issues/37325, so I'm going to close this issue in favor of that one. Please reopen this if I've missed something.
