### ISSUE TITLE
[ML] Address parsing deprecated and removed features in Datafeed Config

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#34858]
Relates to the Job in Index feature branch.

Part of the motivation behind the migration project was to avoid the problem of parsing a datafeed that uses deprecated then removed features throwing an error. This remains an issue after migration as the config including search and aggs is [parsed](https://github.com/elastic/elasticsearch/blob/feature-jindex-6x/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/persistence/DatafeedConfigProvider.java#L488) on GET. For the UI this means the datafeed cannot be displayed as the GET request will fail making it difficult to identify and fix the problem. The document can be read directly from elasticsearch if its name and location is known.  

For REST GET requests where JSON is returned the config does not have to be parsed, internally the document is parsed for unmarshalling but this is not necessary for returning raw JSON. Additionally deprecation checks could be made by trying to parse the config and returning any deprecations in a warning header or by marking up the JSON object.

**Comment by droberts195** [comment]
This is fixed by #36117 and #36233.
