### ISSUE TITLE
Document LDAP realms are only required on coordinating nodes

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#34866]
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/configuring-ldap-realm.html makes no mention which nodes are required to have the LDAP realm configured for successful authentication and authorization. Many just configure the realm on all nodes. Could the node requirements be clarified in the docs? Specifically from my testing, it is only required to have LDAP realms configured on coordinating nodes for auth which greatly simplifies configuration, especially for large clusters.

@mellieA

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

**Comment by jkakavas** [comment]
This is not entirely true. All nodes that handle client requests need to have the realm configuration. If the es cluster is only meant to be accessible via the coordinating node then this is true but I dont think we can/should generalize , at least not without pointing out that in doing so the rest of the nodes cant authenticate user requests

**Comment by jrodewig** [comment]
Thanks @jkakavas. I've closed #48637 based on this comment.
