### ISSUE TITLE
Naming convention for static final variables with mutable internal state

### ISSUE THREAD

**Issue by j-haj** [elastic/elasticsearch#34872]
How should we name static final variables with mutable internal state? Does it matter if the internal state is visible to the user?

As an example, we have the names `DEPRECATION_LOGGER` and `deprecationLogger` throughout the codebase. We should pick a naming convention, document it, and stick to it throughout the codebase. This topic has cropped up in several discussions (e.g., #34279).

**Comment by nik9000** [comment]
I use the rules from the [google java style](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names). Not that they are perfect but it is nice to be able to point to them.

**Comment by talevy** [comment]
We discussed this on FixItFriday and agreed that the google java style for this convention is nice.
I've opened https://github.com/elastic/elasticsearch/pull/34887 to address the lowercasing of the static final variable naming for DeprecationLoggers
