### ISSUE TITLE
ILM DELETE API fails when policy is being used by an index

### ISSUE THREAD

**Issue by bmcconaghy** [elastic/elasticsearch#34875]
When a policy is being used, a DELETE call just fails.  It would be nice to a param (`force=true` or something like it) so that the API would just delete a policy even if it is being used by indices.

**Comment by colings86** [comment]
I think this is a strong feature and not something we should change. A policy being deleted from under an indexes feet is a big problem and breaks that index so I think we should always enforce that a policy is not used in order for it to be deleted. However, one improvement we could make here is to make the error message explain why the delete failed and the list indexes that are still using the policy

**Comment by talevy** [comment]
> However, one improvement we could make here is to make the error message explain why the delete failed and the list indexes that are still using the policy

The exception that is thrown does return an explanation of why the delete failed. Although, it only lists one index that is causing the problem, not all. Although I think that is "good enough", do we want to enhance this message to include all indices and/or provide these indices in more structured format using ElasticsearchException params?
