### ISSUE TITLE
SQL: QueryTranslator improvements

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34874]
`QueryTranslator` currently is somewhat inconsistent in chaining multiple scripts together demanding that each individual translator handles the aggregation/scripting and pure query translation.
This needs to be revised so that the `QueryTranslator` handles the infrastructure and knows what method to call on each translator (scripting - for aggs or `ScriptQuery` or the query itself).

**Comment by wchaparro** [comment]
Superceded by ES|QL
