### ISSUE TITLE
[CCR] Define a good default for the soft delete retention policy

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#34908]
Currently the default for `index.soft_deletes.retention.operations` setting is zero. Before we release 6.5.0 we should come up with a reasonable default. Coming up with a good default is tricky, because the `index.soft_deletes.retention.operations` setting is operation based, but we should settle on a number that allows for soft deleted documents to stay around long enough for CCR while at the same time keeping in mind that keeping soft deleted documents do consume resources.

**Comment by bleskes** [comment]
We can also have non straight forward options for the default - things like 25% of the current doc count with a maximum of 1M (numbers are just illustrative).

**Comment by dnhatn** [comment]
I opened #34943 for a time-based policy. I will work on a ratio-based policy.

**Comment by dnhatn** [comment]
How about implementing a size-based retention policy? We can translate the configured size to a number of operations by estimating the average size of operations. It's not entirely accurate but good enough. @bleskes WDYT?

And suppose we have both age-based and size-based policies, the final decision is ANDed (like the translog policy) or ORed?

**Comment by dnhatn** [comment]
Using 0 as the default retention is also not good for peer-recovery with soft-deletes enabled. This is equivalent to disable translog retention.

**Comment by dnhatn** [comment]
Closes in favor of #37165.
