### ISSUE TITLE
Update _ilm policy CRUD APIs to be behind _ilm/policy namespace

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#34929]
there are multiple cluster-level APIs for ILM that reside behind the `_ilm` URL path.

Endpoints like:

- _ilm/start
- _ilm/stop
- _ilm/status

The above conflict with the get-policy API _ilm/<policy-name> where a policy name can be 
"start", "stop", or "status".

This can be fixed by moving the CRUD APIs to be behind the _ilm/policy/ path prefix.

So

 GET/DELETE/PUT _ilm/policy/<index-names>

**Comment by colings86** [comment]
Note that the plan was to move the policy CRUD APIs (Put, get, delete lifecycle policy) to the `_ilm/policy` namespace. The stop start and status APIs should stay where they are
