### ISSUE TITLE
HLRC ILM Documentation

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#34935]
All the ILM APIs were implemented in the client: https://github.com/elastic/elasticsearch/issues/33100.

They all have stubs for future documentation.

Real client documentation for how to use the client to talk to ILM is still needed

**Comment by colings86** [comment]
@gwbrown @talevy Can this be closed off now?

**Comment by gwbrown** [comment]
Yes, the docs were added in:
Explain: #35803 
Remove policy from index: #35759 
Retry policy: #35715 
Start/Stop/Status: #35762 
Delete Policy: #35664 
Get Policy: #35612 
Put Policy: #35457
