### ISSUE TITLE
Elasticsearch Node fails to rejoin cluster on restart in 6.4.x when SSL configured on transport and no license installed

### ISSUE THREAD

**Issue by bsturg** [elastic/elasticsearch#34931]
**Elasticsearch version** (`bin/elasticsearch --version`):  
6.4.x

**Plugins installed**: []
none

**JVM version** (`java -version`):
java 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system):
Centos 7.3
Linux elastic1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Configuration:  2 nodes in a cluster.  Only elasticsearch is installed.
.
Starting in 6.4.x (verified it did not exist in 6.3.x), if SSL is implemented on elasticsearch transport and if a license has not been implemented on a cluster, the cluster starts and both nodes join.  
 -- This is an invalid configuration since license is not installed, but the behavior changed from previous versions.
.
When a node is restarted, it will not be allowed to rejoin a cluster.
.
In order to allow the node to rejoin the cluster, the other nodes in the cluster must be restarted.

**Steps to reproduce**:
#Install 6.4.2 from rpm

rpm -i elasticsearch-6.4.2.rpm
systemctl daemon-reload
systemctl enable elasticsearch.service

#Generate .p12 - ca and cert

cd /usr/share/elasticsearch
bin/elasticsearch-certutil ca
bin/elasticsearch-certutil cert --ca elastic-stack-ca.p12
copy .p12 to elasticsearch config

es=/etc/elasticsearch
mkdir ${es}/certs
chown -R elasticsearch:elasticsearch ${es}/certs
cp elastic-certificates.p12 ${es}/certs
chown -R elasticsearch:elasticsearch ${es}/certs
chmod 644 ${es}/certs/*
ls -l ${es}/certs

#clean up logs and start with a brand new empty db

rm -rf /var/lib/ela*/nodes
rm -f /var/log/elast*/*
start elasticsearch and watch logs; once the handshake is completed between master nodes, restart a node

systemctl start elasticsearch
tail -f /var/log/el*/*cluster.log

Restart one node;  it will not join the cluster.

Errors seen on node:
[WARN ][o.e.x.s.t.n.SecurityNetty4ServerTransport] [brian-node2] exception caught on transport layer [NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/192.168.200.178:49532}], closing connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake

**Provide logs (if relevant)**:
[try2.tar.gz](https://github.com/elastic/elasticsearch/files/2520475/try2.tar.gz)

@inqueue

**Comment by jaymode** [comment]
where are you configuring ssl in your settings? What other settings have you configured?

**Comment by gpanula** [comment]
I have also encountered this bug.  My understanding is the SSL is now part of the basic license per https://www.elastic.co/products/x-pack/open

Configs bits from _/etc/elasticsearch/elasticsearch.yml_
```
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/certs/elastic-certificates.p12
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /etc/elasticsearch/certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: /etc/elasticsearch/certs/elastic-certificates.p12
```

Explicitly set license to basic
```
xpack.license.self_generated.type: basic
```

Using a single certificate for the nodes created with the _elasticsearch-certutil_ utility

Dedicated master nodes can leave and rejoin the cluster without an issue.  But other dedicated roles can only join the cluster if a master has not yet been elected.  i.e. minimum_masters set to 2 and only one master running.

Once a master has been elected, other non-master roles can **not** join the cluster.

**Comment by gpanula** [comment]
Maybe useful bit from elected master's log when a new master tried to join the cluster.

```
Caused by: java.lang.IllegalStateException: handshake failed with {i-0435f7d28253346f9}{TZ6EyTmhQiarzEm_Z-RuHA}{ZGGY-z3cQ5uIRO6U7XK5cg}{1.2.6.154}{1.2.6.154:9300}{aws_availability_zone=us-east-1a, xpack.installed=true}
        at org.elasticsearch.transport.TransportService.handshake(TransportService.java:400) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.transport.TransportService.lambda$connectToNode$4(TransportService.java:331) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:543) ~[elasticsearch-6.4.2.jar:6.4.2]
        ... 9 more
Caused by: org.elasticsearch.transport.RemoteTransportException: [i-0435f7d28253346f9][10.225.196.154:9300][internal:transport/handshake]
Caused by: org.elasticsearch.ElasticsearchSecurityException: missing authentication token for action [internal:transport/handshake]
        at org.elasticsearch.xpack.core.security.support.Exceptions.authenticationError(Exceptions.java:18) ~[?:?]
```

**Comment by gpanula** [comment]
Error persists with version 6.4.3
```
Caused by: java.lang.IllegalStateException: handshake failed with {i-0cd1ed6437cffe351}{FNhm7WZnRMq5y2JLL9KdYg}{_PCd1tfGQkKdnLTjp_MCFw}{1.2.6.232}{1.2.6.232:9300}{aws_availability_zone=us-east-1d, xpack.installed=true}
        at org.elasticsearch.transport.TransportService.handshake(TransportService.java:400) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.transport.TransportService.lambda$connectToNode$4(TransportService.java:331) ~[elasticsearch-6.4.3.jar:6.4.3]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:543) ~[elasticsearch-6.4.3.jar:6.4.3]
        ... 9 more
Caused by: org.elasticsearch.transport.RemoteTransportException: [i-0cd1ed6437cffe351][1.2.6.232:9300][internal:transport/handshake]
Caused by: org.elasticsearch.ElasticsearchSecurityException: missing authentication token for action [internal:transport/handshake]
```

**Comment by inqueue** [comment]
Secure communications is only included with a Gold or Platinum license- see https://www.elastic.co/subscriptions and click Security. 

What makes this issue particularly strange is ES will start successfully and form a multi-node cluster with transport TLS configured while operating under a Basic license, though TLS is not actually enabled--which is expected under that license. However, a node that is restarted is unable to join the cluster without a full cluster restart as mentioned in the original description. 

I really like that ES, under a Basic license, ignores `security` settings because it means you don't have to restart the cluster to enable security when a Gold or Platinum is installed. A way to improve the experience would be to allow a node to rejoin the cluster under the same configuration.

**Comment by jaymode** [comment]
> My understanding is the SSL is now part of the basic license per https://www.elastic.co/products/x-pack/open 

@gpanula TLS (SSL) is not part of the basic license. The code is open, as in we are developing it in a repository that is publicly accessible. However, certain features like TLS are still licensed and require a higher license level than basic.

That said, if TLS is enabled on a cluster with a basic license, you'll probably encounter some odd behavior. I suggest you remove the TLS settings when operating with a basic license.

**Comment by gpanula** [comment]
Ahhh, my fault for not scrolling down far enough in the announcement.   Thank you for the clarification.
