### ISSUE TITLE
Include template name used in _meta of index mapping

### ISSUE THREAD

**Issue by wasserman** [elastic/elasticsearch#34946]
**Include template name used in _meta for mapping**:
I find it handy to know which template matched at the time a given index was created.  I personally started to include it in my templates to make it easier to be sure if a template was matched at index time or if it was auto-generated via some default.  It'd be great if this was injected automatically by Elastic, either at template creation or index creation.

**Comment by colings86** [comment]
The `_meta` object is reserved as a object that the user can specify and will not be touched by the index and mappings APIs. This is important so the user has complete control on that object. We discussed this in FixItFriday and we feel that this is not something that we want to add to the `_meta` object for the reasons above. Adding this elsewhere also did not feel right to us at this stage as this is not a use case we have seen come up. 

I'll leave this issue open for a little while for feedback to see if other users also have this need.

**Comment by wasserman** [comment]
Here's my scenario. I may have templates matching patterns like:
- filebeat-*
- filebeat-apache-*
- filebeat-nagios-*

Then I'll add new indices like:
- cached-test-data-*
- filebeat-tomcat-*

The filebeat-tomcat one may be added through dynamic logic via Logstash and the {type} variable.
I later create a template for filebeat-tomcat-* , but as I look back over my data I see field type inconsistencies.  It would be nice to know which indices were created via the template filebeat-* pattern vs filebeat-tomcat-*.  Knowing the actual template and version has historical value and can prevent an unnecessary deep dive.

In the cached-test-data-* scenario I got bitten by having no template being used by noticing that it was using five shards instead of the three I typically use.

Perhaps this can be stored in a similar way as the settings.index.version.created field?  Isn't this read-only meta stored by the system?

Possibly something like this:
```
"settings": {
  "index": {
    "template_used": { 
      "name": "template-name",
      "version": "template-version"
    }
  }
}
```

Then the templates used can be reviewed by doing something like:
`GET _all/_settings/index.template*`

**Comment by dliappis** [comment]
Given that there hasn't been much additional feedback for over 1 month, I am going to close this, however, if there are more people having feedback we can look at opening it again.
