### ISSUE TITLE
Using a missing filter for attributes of a nested object always returns an empty set

### ISSUE THREAD

**Issue by pfleidi** [elastic/elasticsearch#3495]
Hi there,

I was trying to use the `exists`/`missing` filters when I stumbled upon this behavior: When I use the `missing` filter for nested objects, it always returns an empty set if the containing nested object is missing, too.

Here is my document mapping:

```javascript
{
  "site": {
    "properties": {
      "host": {
        "type": "string",
        "index": "not_analyzed",
        "omit_norms": true,
        "index_options": "docs"
      },
      "ip": {,
        "type": "string",
        "index": "not_analyzed",
        "omit_norms": true,
        "index_options": "docs"
      },
      ...
      "modules": {
        "type": "nested",
        "properties": {
          "module_id": {
            "type": "integer"
          },
          "name": {
            "type": "string",
            "index": "not_analyzed",
            "omit_norms": true,
            "index_options": "docs"
          },
          ...
        }
      }
    }
  }
}
```

My Document looks like this:

```javascript
{
  "host": "6c1bb1fb58e8c48cabbd1e4382e55871f31ad776.com",
  "ip" : "0.0.0.0",
  ...
  "modules": [ ]
}
```

If I now use a query with a  nested filter to select every document where modules.name is missing, I only get an empty set.

```javascript
{
  "query": {
    "filtered": {
      "query": { "match_all": { } },

      "filter": {
        "nested": {
          "path": "modules",
          "query": {
            "filtered": {
              "query": { "match_all": { } },

              "filter": {
                "missing": { "field": "modules.name" }
              }

            }
          }
        }
      }
    }
  }
}
```

It seems to work if I submit a document which contains a module:

```javascript
{
  "host": "6c1bb1fb58e8c48cabbd1e4382e55871f31ad776.com",
  "ip" : "0.0.0.0",
  ...
  "modules": [ { "version" : "foo" } ]
}

```

When using documents where the modules object isn't empty, use a `missing` filter which looks for "deeper" missing attributes seems to work, too.

```javascript
{
  "query": {
    "filtered": {
      "query": { "match_all": { } },

      "filter": {
        "nested": {
          "path": "modules",
          "query": {
            "filtered": {
              "query": { "match_all": { } },

              "filter": {
                "missing": { "field": "modules.foo.bar.baz" }
              }

            }
          }
        }
      }
    }
  }
}
```

I was expecting, that a `missing` filter also returns documents if the containing nested object is missing or empty.

Update: Wrapping an `exists` filter in a `not` filter doesn't return any documents, either.

**Comment by caseywebdev** [comment]
I just ran into this. The workaround highlighted by @drewish feels pretty clunky though :confused:

**Comment by clintongormley** [comment]
Here's a simple recreation that describes the problem:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "nested"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "foo": {
        "bar": "bar"
      }
    }
    
    PUT t/t/2
    {
      "xyz": "xyz"
    }
    
This request matches doc 2, because it has a nested doc which is missing the field, but not doc 1 because it has no nested docs:

    GET t/_search
    {
      "query": {
        "nested": {
          "path": "foo",
          "query": {
            "missing": {
              "field": "foo.baz"
            }
          }
        }
      }
    }
    
This workaround works correctly for both docs:

    GET t/_search
    {
      "query": {
        "not": {
          "nested": {
            "path": "foo",
            "query": {
              "exists": {
                "field": "foo.bar"
              }
            }
          }
        }
      }
    }

@martijnvg @jpountz is this fixable?

**Comment by jpountz** [comment]
It is not fixable, unless the missing query can detect it is being used within a nested query, which I would like to avoid at all costs. We don't index missing fields in documents, only existing fields, so the `missing` query is internally implemented as the negation of an `exists` query. This raises problems as described here given that putting the `not` inside of the `nested` query has a totally different effect than putting it outside as your workaround does.

I think the way to fix this trap would be to deprecate the `missing` query in favor of explicit negations of the `exists` query.

**Comment by clintongormley** [comment]
@jpountz ++ makes sense.

Closing in favour of #14112

**Comment by snkiran** [comment]
GET article_info/article/_search
{
   "fields": [
      "media_type"
   ],
   "query": {
      "filtered": {
         "query": {
            "query_string": {
               "query": "pdf_url:.pdf"
            }
         },
         "filter": {
            "range": {
               "mediadate": {
                  "from": "02-22-2016",
                  "to": "02-24-2016"
               }
            }
         }
      }
   },
   "size": 0,
   "aggs": {
      "days": {
         "date_histogram": {
            "field": "mediadate",
            "interval": "day",
            "format": "MM-dd-yyyy"
         },
         "aggs": {
            "art_count": {
               "terms": {
                  "field": "media_type",
                 "order" : { "_term" : "desc" }
               }
            }
         }
      }
   }
}

but i need to display all the missing or null values in the result or output

**Comment by snkiran** [comment]
this is the result output:
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 10,
      "successful": 10,
      "failed": 0
   },
   "hits": {
      "total": 856,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "days": {
         "buckets": [
            {
               "key_as_string": "02-22-2016",
               "key": 1456099200000,
               "doc_count": 854,
               "art_count": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                     {
                        "key": "wire",
                        "doc_count": 92
                     },
                     {
                        "key": "web",
                        "doc_count": 223
                     },
                     {
                        "key": "service",
                        "doc_count": 92
                     },
                     {
                        "key": "blog",
                        "doc_count": 539
                     }
                  ]
               }
            },
            {
               "key_as_string": "02-23-2016",
               "key": 1456185600000,
               "doc_count": 1,
               "art_count": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                     {
                        "key": "web",
                        "doc_count": 1
                     }
                  ]
               }
            },
            {
               "key_as_string": "02-24-2016",
               "key": 1456272000000,
               "doc_count": 1,
               "art_count": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                     {
                        "key": "web",
                        "doc_count": 1
                     }
                  ]
               }
            }
         ]
      }
   }
}

**Comment by spati-java** [comment]
Since the "not" is deprecated , you can use the must not . 

POST /my_index/my_type/_search
{
    "filter": {
        "bool": {
            "must_not": [
               {
                   "nested": {
                      "path": "path_to_nested_doc",
                      "query": {
                          "match_all": {}
                      }
                   }
               }
            ]
        }
    }
}

**Comment by manuprasanth** [comment]
This works for me

GET /type/_search?pretty=true
{
  "query": {
    "bool": {
      "must_not": [
        {
          "nested": {
            "path": "outcome",
            "query": {
              "exists": {
                "field": "outcome.outcomeName"
              }
            }
          }
        }
      ]
    }
  }
}

**Comment by CSantiStSup** [comment]
Any update on this ? the query from @manuprasanth does not return any document for me, while some of my nested elements are empty. What I find even stranger is that if I do the same query with _must_ instead of _mustnot_, I get the correct output (my empty elements are not returned).
