### ISSUE TITLE
HLRC: extend tasks API to include getByTaskId 

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#34962]
It is currently not possible to fetch task by given taskID
task api has to be extended to allow that - this is used for instance in migration API or whenever wait_for_completion flag is set to false 

refers #29827

**Comment by hub-cap** [comment]
It looks like this is one of the few OSS APIs that have not yet been implemented. Its on the original ticket here #27205 under the tasks api, so im going to close this ticket out. Ty for the investigation.
