### ISSUE TITLE
ILM shrink action should filter by _id, not _name

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#35043]
Currently when setting a single node allocation for the ILM shrink action, we filter by `_name`. This will cause problems now that the hostname is used for the node name (since a user running ES multiple times on their dev machine will have nodes with the same name).

We should switch to filtering by `_id` instead, since it is unique.

**Comment by talevy** [comment]
closed by https://github.com/elastic/elasticsearch/pull/35061
