### ISSUE TITLE
DOC 5.6 system-call-filter-check grammar

### ISSUE THREAD

**Issue by yuanxuzhang** [elastic/elasticsearch#35075]
It seems to need a full point after "attacks on Elasticsearch" in [DOC 5.6 system-call-filter-check](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/system-call-filter-check.html)

**Comment by romseygeek** [comment]
Thanks for raising the issue @yuanxuzhang! It's not a separate file any more, but the full stop is still missing in bootstrap-checks.asciidoc in master.
