### ISSUE TITLE
Add grok patterns to support hostnames with underscores

### ISSUE THREAD

**Issue by jsoriano** [elastic/elasticsearch#35081]
Current `HOSTNAME` grok pattern doesn't support hostnames with underscores.

As discussed in a [PR to add this to the logstash plugin](https://github.com/logstash-plugins/logstash-patterns-core/pull/107#issuecomment-219770878), the RFC doesn't accept underscores, but they are actually possible at least on Linux (see https://github.com/elastic/beats/issues/8814), and when they are part of DNS records or in host:port patterns.

I think that `HOSTNAME` should accept underscores, or new patterns should be added to handle the cases where underscores could be present.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
