### ISSUE TITLE
The uninstaller won't work if heap size is changed in settings manually.

### ISSUE THREAD

**Issue by zavr-1** [elastic/elasticsearch#35103]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_192-ea

**OS version** (`uname -a` if on a Unix-like system): Win 10

**Description of the problem including expected versus actual behavior**:

The installer won't work after manually changing the heap size to value > 50%. 

**Steps to reproduce**:

 1. install es with msi installer
 2. change config/jvm.options to have heap size > 50% of available memory
 3. try to uninstall with remove program - nothing happnes
 4. try to uninstall with cmd and log - see suggestion "we recommend leaving > 50% memory" and not uninstalling.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Please reopen this issue on elastic/windows-installers.
