### ISSUE TITLE
SQL: Allow ordering of groups based on aggregates

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#35118]
Due to the way composite aggs are currently implemented, one can sort only by the its keys. This is limiting as a good portion of use cases need to do just that:
`GROUP BY countries ORDER BY COUNT(*)`

**Comment by TimHeckel** [comment]
This would be so beneficial -- is this planned for `6.6.0`? I haven't tried, but I assume it's not baked in `6.5.0` correct? I know it's not working in` 6.4.1`.

**Comment by alexfrancoeur** [comment]
@costin also interested, is this something we're still targeting for 6.6?

**Comment by costin** [comment]
No, there was too much work for this to make it into 6.6; it will be addressed in a future version.

**Comment by Kels** [comment]
Is there a workaround ? Canvas seems hard to use without the possibility to limit results after an order by counting

**Comment by alexfrancoeur** [comment]
Nice @costin !👌

**Comment by aananthagovindarajan** [comment]
Composite Aggregation is a very nice feature, it allows to paginate over the distinct values of the field but however sort by only "key/term". Are there any plans to support sort by doc_count desc?  The Composite Aggregation docs, is not capturing the absence of sort by doc_count desc support which the majority of the users interested in.
