### ISSUE TITLE
Search Query Method in document

### ISSUE THREAD

**Issue by wangzhenhui1992** [elastic/elasticsearch#35116]
**Describe the feature**:
In the introduction of Routing in SearchAPIs, it uses a POST request to submit a Query Search.
Of course it goes well because ElasticSearch supports both GET request and POST request for Search.
However , for beginners, it is more easier to understand if using a GET request and it will be consistent with [GettingStarted] as well as the following section [Request Body Search]

**The page on website of Elastic**:
[https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html)

**Script shown on the page**
```
POST /twitter/_search?routing=kimchy
{
    "query": {
        "bool" : {
            "must" : {
                "query_string" : {
                    "query" : "some query string here"
                }
            },
            "filter" : {
                "term" : { "user" : "kimchy" }
            }
        }
    }
}
```

**Comment by mayya-sharipova** [comment]
@wangzhenhui1992  Thank you for submitting the issue and thinking about it.  To me it looks like it doesn't matter much.   But if you think it matters, you are welcome to submit a PR for this documentation section.

**Comment by wangzhenhui1992** [comment]
@mayya-sharipova 
Thank you for replying. I have submitted the PR #35117 .

**Comment by cbuescher** [comment]
@mayya-sharipova @wangzhenhui1992 I will close this issue, arguments against doing this are mentioned in #35117.
