### ISSUE TITLE
Ingest Processors must use certain data structures for simulate API to work

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#35138]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2

**Description of the problem including expected versus actual behavior**:

When using the simulate pipeline API, a document is serialized using `WriteableIngestDocument.toXContent`, which in turn calls `IngestDocument.deepCopyMap(ingestDocument.getSourceAndMetadata());`, which in turn calls `IngestDocument.deepCopy()` - this method only allows for a very limited set of objects to be deepcopied. However an ingest processor has no limits configured to what is allowed or not allowed and regular operations work where as this only fails in the simulate API.

I am not sure if it makes a lot of sense to open up the method for further serialization or to maybe throw an exception if this a certain data type is not supported, or just document this?

I stumbled over this in https://github.com/spinscale/elasticsearch-ingest-opennlp/issues/27

**Comment by jakelandis** [comment]
@spinscale - in the specific case of spinscale/elasticsearch-ingest-opennlp#27 , would adding support for `Set` in deepCopy resolve the issue ?

I believe this only impacts source code / plugins that manipulates the `IngestDocument` using `Set` (or other non supported data types).  

I do think `Set` (and possibly other common data types) should be supported, else we are limiting plugin authors unnecessary. However, I believe a workaround would be for the plugin explicitly convert the unsupported data types to a supported data type (e.g Set -> ArrayList) prior to adding it to the ingest document.

**Comment by spinscale** [comment]
that's how I fixed it for now, converting the set into a list, see https://github.com/spinscale/elasticsearch-ingest-opennlp/commit/a8b3ad70554697b5d58d238d549374f9164f5704

and yeah, supporting a set would solve this, but that's always a game of catch-up.

**Comment by HiDAl** [comment]
Hey @spinscale!
I'm checking out some old issues and it looks like this is not happening anymore (implemented in #63067). If you're ok with it, I'll close it.
