### ISSUE TITLE
A chromium archive from the X-Pack reporting plugin is considered infected by the "Mirai" unix trojan by ClamAV

### ISSUE THREAD

**Issue by jarthod** [elastic/elasticsearch#35154]
**Kibana version**: 6.4.2
**OS version**: Ubuntu server 18.04

**Description of the problem including expected versus actual behavior**:

I recently added a daily [clamav](https://www.clamav.net/) scan to my servers and was surprised to get a report from a file inside the X-Pack plugin:

```
/usr/share/kibana/node_modules/x-pack/plugins/reporting/.chromium/chromium-503a3e4-linux.zip: Unix.Trojan.Mirai-5932143-0 FOUND
```
I couldn't find the reporting folder in this repo though so I'm not sure where it's located? Is this file coming from you? This might be a false positive as I've seen similar reports: https://forum.snapcraft.io/t/clamav-found-mirai-trojan-in-slack-snap/7194/7
But if it is you may want to warn clamav to they can fix the issue, or at least confirm this so people knows they can ignore this warning (when they find this issue) or delete this file (If I don't use the report plugin I guess I can delete this file?)

**Steps to reproduce**:

 1. Install kibana from official repository (x-pack is included by default? I dont remember installing it) 
 2. `cd /usr/share/kibana/node_modules/x-pack/plugins/reporting/.chromium`
 3. `clamscan --max-filesize=4000M --max-scansize=4000M`

Thanks.

**Comment by jasontedor** [comment]
Heya, thanks for the report. This repository is for Elasticsearch and you're reporting an issue about Kibana. However, rather than redirect you to the Kibana repository, could I ask you to please disclose this via our [security disclosure](https://www.elastic.co/community/security) process?
