### ISSUE TITLE
5.6.7, somtimes produce TaskCancelledException when using tribe node

### ISSUE THREAD

**Issue by lintiven49** [elastic/elasticsearch#35159]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.6.7

**Plugins installed**: ['']

**JVM version** (`java -version`): jdk 8

**OS version** (`uname -a` if on a Unix-like system): linux

**Description of the problem including expected versus actual behavior**:

![image](https://user-images.githubusercontent.com/4494734/47855957-e6f5fa80-de20-11e8-9bf4-2e37f28cc216.png)

**Comment by jkakavas** [comment]
Hi 

Please don't post images of text as they are hard to read, may not display
correctly for everyone, and not searchable.

Can you please add some more information on when and under what circumstances you have observed this issue?

**Comment by andrershov** [comment]
No further feedback received. @lintiven49 if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
