### ISSUE TITLE
SQL: when using wildcard expand the nested fields automatically

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#35167]
```
sql> select * from test;
   groupName
---------------
fans

sql> select *, user.* from test;
   groupName   |  user.first   |   user.last
---------------+---------------+---------------
fans           |John           |Smith
```

`user` is a `nested` field.
The scenarios above should be equivalent? This will offer a better user experience, more in line with SQL.
Should this also include the [case of `select user from test`](https://github.com/elastic/elasticsearch/issues/30063), where `user` will be expanded automatically?

**Comment by wchaparro** [comment]
Superceded by ES|QL
