### ISSUE TITLE
Rolling-upgrade test runner stops too many nodes

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35177]
When investigating #34950 I tried running the `REPRODUCE WITH` line and it failed for an unrelated reason. A simpler reproduction is to run:

    ./gradlew :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestRunner -Dtests.class=org.elasticsearch.upgrades.RecoveryIT

This fails because it starts up three nodes, stops two of them, starts another one, and the two nodes that result from this aren't enough to form the cluster again. It should only stop one of them. Log excerpt:

```
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oldClusterTestRunner
==> Test Summary: 1 suite, 4 tests, 2 ignored (2 assumptions)
   [junit4] JVM J0:     0.32 ..     5.75 =     5.43s
   [junit4] Execution time total: 5.77 sec.
   [junit4] Tests summary: 1 suite, 4 tests, 2 ignored (2 assumptions)

> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oldClusterTestCluster#node2.stop
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oldClusterTestCluster#node0.stop
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#prepareCluster.cleanShared
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#clean
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#createCwd
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#checkPrevious SKIPPED
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#stopPrevious SKIPPED
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#extract
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#configure
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#start
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#wait

> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#wait FAILED
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oneThirdUpgradedTestCluster#stop
> Task :qa:rolling-upgrade:v6.6.0-SNAPSHOT#oldClusterTestCluster#node1.stop
```

However running the whole BWC test does pass:

    ./gradlew :qa:rolling-upgrade:bwcTest -Dtests.class=org.elasticsearch.upgrades.RecoveryIT

**Comment by matriv** [comment]
Another failure seems related to this (3 nodes stopped)
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc+next/BWC_VERSION=7.4.0,nodes=general-purpose/64/console
https://scans.gradle.com/s/3kb2exjmmwskg

**Comment by mark-vieira** [comment]
We have a number of frequent failures related to rolling upgrade tests. It seems when this goes wrong the whole suite fails as the cluster never reports as green.

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:qa:rolling-upgrade:*%27.%0A%3E%20There%20were%20failing%20tests.%20See%20the%20report%20at:%20*&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1565817736347&search.startTimeMin=1565212936347&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-420

@atorok any chance this is just something funky with `ClusterFormationTasks` and that test clusters will sort this out?

**Comment by atorok** [comment]
These tests now use the testclsuters plugin that has a totally different way of dealing with upgrading the nodes so this should no longer be applicable.
