### ISSUE TITLE
Better definition around what _cat apis can take a query param and what can't

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#35180]
**Describe the feature**:

It would be very helpful if there was more robust documentation around the query string parameter for _cat api calls. I see in some cases you can query on a field value like : **_cat/indices?v&health=yellow** but you can't always do that. For instance trying to get a list of shards that only apply to the a specific node
**GET _cat/shards?v&node=1234** doesn't work. And although it would be a bigger win for these all to work I understand that is a larger feature. It would just be nice to specify where and when you can use query parameters and which ones you could use.

**Comment by DaveCTurner** [comment]
This is a good point. In the short term, we can and should improve the documentation of the specific APIs mentioned here. In the longer run we hope to have something more automated that will help us to ensure all the parameters for this sort of API are documented, but this is a long way off.

**Comment by debadair** [comment]
I think this has been addressed by the API formatting that was done--I think that just needs to be verified & this issue can be closed.

**Comment by lockewritesdocs** [comment]
Thanks for the context @debadair.

@DaveCTurner, the `cat` API documentation provides some information around [numeric formats](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat.html#numeric-formats) and how to build a query for that datatype.

Both the [cat indices](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-indices.html#cat-indices-api-example) and [cat shards](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-shards.html#cat-shards-api-example) APIs provide usage examples. The former contains only a single example, and could be enhanced to contain additional examples that users would find useful. For example:
```
GET _cat/indices?health=yellow
```
For the `cat shards` API, we could enhance the examples by explaining the returned parameters more. For example, explaining in this [example with a single index](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-shards.html#cat-shards-api-example-single) what each returned value correlates to. We indicate in the introduction that the `cat shards` API returns for each node "...if it's a primary or replica, the number of docs, the bytes it takes on disk, and the node where it’s located." Perhaps it bears repeating that information in the context of an example?

These changes are fairly nominal, but I'm happy to make them if they would prove helpful to our users.

P.S. - I find it curious that the `cat indices` API is used to return shard count. I would expect that the `cat shards` API would provide that information.

**Comment by DaveCTurner** [comment]
IMO we don't need more examples. I think this issue dates back to a time when we didn't list the query parameters at all in these docs (see, e.g. [how we described `GET _cat/indices` in 5.6](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-indices.html)). Now that we've got a list of the parameters I think this issue is resolved, assuming of course we've verified that the docs are complete.

> I find it curious that the cat indices API is used to return shard count. I would expect that the cat shards API would provide that information.

The idea is roughly that `GET _cat/X` returns one line per X: each line returned by `GET _cat/shards` is for a single shard, whereas `GET _cat/indices` returns a line per index instead.

The number of shards is a pretty important property of an index, and is useful for interpreting other stats like the total size of the index. A 50GB index with a single shard is good, whereas a 50GB index with 100 shards is bad.

**Comment by lockewritesdocs** [comment]
Thanks for the context @DaveCTurner! I'm new to Elastic and still learning, so this type of information is really helpful. 

Considering the API overhaul since this issue was created, can we consider this one closed?

**Comment by lockewritesdocs** [comment]
> Now that we've got a list of the parameters I think this issue is resolved, assuming of course we've verified that the docs are complete.

I double-checked the command options for these commands, and I agree that this issue is resolved. I'll mark it as closed.
