### ISSUE TITLE
Check mustache syntax at watcher creation time

### ISSUE THREAD

**Issue by matschaffer** [elastic/elasticsearch#35189]
**Describe the feature**:

We had a case recently where we forgot a closing `{{/ctx.payload.clusters}}` on a watch.

This caused the watch to fail execution and essentially silence the alert until someone checked the kibana management UI.

While we should be doing better validation of watch changes, it could also be helpful if watcher validated mustache syntax when `PUT`ing the watch definition and returned some sort of 4xx in the event of a syntax error.

Opening this bug specifically about mustache templates in actions, but I could see this potentially applying to painless transformations if that's not being checked already.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
