### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT failures. _ilm/policy?

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#35209]
A number of failures in this suite on the 6.x branch.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+default-distro/51/console

What they all have in common is this error in the message:
```
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:45439], URI [/_ilm/policy], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [policy]"}],"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [policy]"},"status":400}
```

Does not reproduce with the commands emitted by the test failures, I've included them below for completion.

<details>
  <summary>Click to expand reproduce commands</summary>
REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=bulk/60_deprecated/Deprecated parameters should produce warning in Bulk query}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=range/10_basic/Float range}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=snapshot.get/10_basic/Get missing snapshot info succeeds when ignore_unavailable is true}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=mget/60_realtime_refresh/Realtime Refresh}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.get_mapping/50_wildcard_expansion/Get test-* with wildcard_expansion=all}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/150_rewrite_on_coordinator/Ensure that we fetch the document only once}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/160_exists_query/Test exists query on object inner field in empty index}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but type and index do}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=tasks.list/10_basic/tasks_list headers}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13#mixedClusterTestRunner \
  -Dtests.seed=635BFF7DFF024FE1 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.get_settings/10_basic/Get /{index}/_settings/{name,name}}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=Africa/Cairo \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8
</details>

**Comment by talevy** [comment]
thanks for opening this @davidkyle. I am running the check locally with my fix

```diff
--- a/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java
+++ b/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java
@@ -534,7 +534,8 @@ public abstract class ESRestTestCase extends ESTestCase {
             Response response = adminClient().performRequest(new Request("GET", "/_ilm/policy"));
             policies = entityAsMap(response);
         } catch (ResponseException e) {
-            if (RestStatus.METHOD_NOT_ALLOWED.getStatus() == e.getResponse().getStatusLine().getStatusCode()) {
+            int statusCode = e.getResponse().getStatusLine().getStatusCode();
+            if (RestStatus.METHOD_NOT_ALLOWED.getStatus() == statusCode || RestStatus.BAD_REQUEST.getStatus() == statusCode) {
                 // If bad request returned, ILM is not enabled.
                 return;
             }
```

**Comment by talevy** [comment]
pushed. this should be fixed. will watch and close out this issue if solved

commit in 6.x: https://github.com/elastic/elasticsearch/commit/4748741bad185209dd98ff749f7ddaa4f1769044

**Comment by talevy** [comment]
fixed
