### ISSUE TITLE
HEAD endpoint should return size of a document

### ISSUE THREAD

**Issue by DAVIDFlavien** [elastic/elasticsearch#35212]
**Describe the feature**:

We were planning to use `HEAD` request on a document like following: `/:index/:type/:id` to get the size of a document to avoid using the [Mapper Size Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html) to populate the `_size` field for one some reasons:
- We can't afford to restart all our nodes only to add a new plugin
- It will increase the size of all our documents

It appears that when doing a GET request like this:
`curl -XGET 'http://localhost:9200/:index/:type/:id' -I` we manage to get the size in the `Content-Length` header.
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1670
Connection: keep-alive
```
 However, the `HEAD` endpoint only return if the document exists. It would be nice to return as well some useful information such as the size (there is a TODO on this in your code).

https://github.com/elastic/elasticsearch/blob/66de6c3b82e8b3db9f392e3ae9b411a1e87ca381/core/src/main/java/org/elasticsearch/rest/action/get/RestHeadAction.java#L58-L69

**Comment by nik9000** [comment]
@DAVIDFlavien what version are you seeing this behavior in? I believe this is fixed.

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch/pull/23186

**Comment by jasontedor** [comment]
This is clearly referring to an old version, `RestHeadAction` does not even exist anymore as it was removed exactly the in the PR #23186 that @nik9000 refers to.

Note:

```
15:10:43 [jason@totoro:~] $ curl -H "Content-Type: application/json" -XPUT localhost:9200/i/_doc/1?pretty=true -d '{"field":"value"}'
{
  "_index" : "i",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
15:15:46 [jason@totoro:~] $ curl -v -XGET localhost:9200/i/_doc/1?pretty=true
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> GET /i/_doc/1?pretty=true HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 135
< 
{
  "_index" : "i",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "field" : "value"
  }
}
* Connection #0 to host localhost left intact
15:16:01 [jason@totoro:~] $ curl -v -I localhost:9200/i/_doc/1?pretty=true
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> HEAD /i/_doc/1?pretty=true HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
content-type: application/json; charset=UTF-8
< content-length: 135
content-length: 135

< 
* Connection #0 to host localhost left intact
15:16:05 [jason@totoro:~] $
```
