### ISSUE TITLE
Add an additional merges endpoint for _nodes/stats/indices to make it more consistent with response

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#35215]
## The problem

[Our docs](https://github.com/elastic/elasticsearch/blob/master/docs/reference/cluster/nodes-stats.asciidoc#indices-statistics) describe that `merge` is a supported metric for `_nodes/stats/indices`.

However, the response uses the `merges` key e.g.:

API request:

```
_nodes/stats/indices/merge
```

Response excerpt:

```
"indices": {
        "merges": {
          "current": 7,
          "current_docs": 34687316,
          "current_size_in_bytes": 12354299600,
          "total": 13161,
          "total_time_in_millis": 20034705,
          "total_docs": 583555241,
          "total_size_in_bytes": 229829445744,
          "total_stopped_time_in_millis": 2992,
          "total_throttled_time_in_millis": 12743646,
          "total_auto_throttle_in_bytes": 27419423
        }
      }
```

## Suggestion

We discussed some approaches in [this closed PR](https://github.com/elastic/elasticsearch/pull/34945#discussion_r229349974) but rejected them as we don't want to break users relying either on the existing endpoint or `merges` in the response.

To avoid breaking backwards compatibility, what if we register an additional handler for `_nodes/stats/indices/merges`, using the same mechanism as in [RestAnalyzeAction](https://github.com/elastic/elasticsearch/blob/d6e44129b1cbe77562195f970716ec024f210865/server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestAnalyzeAction.java#L52-L58)?

**Comment by dliappis** [comment]
cc @danielmitterdorfer / @cbuescher

**Comment by debadair** [comment]
[docs issue triage]

The docs are currently correct as implemented. If an additional handler is added, the change should include an update to make the endpoint consistent with the response.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
