### ISSUE TITLE
Function Score with Filters

### ISSUE THREAD

**Issue by impguard** [elastic/elasticsearch#35227]
I need to search for a particular set of content, scaling the score by the recency of the content. The easiest way to do that is with a function_score query:

```
  function_score: {
    query: {
      some...query...
    },
    functions: [
      {
        gauss: {
          created_at: { scale: '180d', offset: '1d', decay: 0.3 },
        },
      },
    ],
  },
```

However, this query is merely a small piece of a much larger query that searches across multiple different content types across multiple indices, so I would like to filter my documents so that this query isn't performed on docs that don't match. Something like this:

```
  function_score: {
    query: {
      some...query...
    },
    filter: {
      only...if...filter...matches
    }
    functions: [
      {
        gauss: {
          created_at: { scale: '180d', offset: '1d', decay: 0.3 },
        },
      },
    ],
  },
```

This causes an error currently, because filter isn't an accepted keyword within a function_score query. So, instead, I'm ok duplicating the filter:

```
  function_score: {
    query: {
      <some query with the following filter>
      filter: { <some filter> }
    },
    functions: [
      {
        gauss: {
          filter: { <same filter> },
          created_at: { scale: '180d', offset: '1d', decay: 0.3 },
        },
      },
    ],
  },
```

This doesn't work with the following error:

```
[parsing_exception] unknown field [created_at]
```

For documents that should be filtered out (they're in different indices with different schemas). Is this a bug? Is there any way to even use the function score filter when I want to nest it within other queries? I've tried wrapping the function score query within a bool query that filters out the docs I don't care about, and I can guarantee the the remaining docs will have a "created_at" field. I still get this parsing error when running those docs through the query.

This seems like a pretty big limitation for the function_score query when querying across multiple distinct indices.

**Comment by impguard** [comment]
I'm thinking #18892 is the current approach moving forward?

**Comment by mayya-sharipova** [comment]
@impguard Thanks for reporting this issue.  It is indeed an issue with function score query. 
We have already got this issue opened here: https://github.com/elastic/elasticsearch/issues/33558
I am closing this issue as it is a duplicate.
