### ISSUE TITLE
Reindex Api support a self-signed remote source.

### ISSUE THREAD

**Issue by nivpenso** [elastic/elasticsearch#35237]
Reindexing API is an amazing feature that allows moving data between one cluster to another. 
The main pain with it now is that SSLed clusters must have a valid signed certificate. There is no way to tell the API to ignore the certificate verification. My suggestion is to add an additional field to a remote source option in the Reindex API and provide a boolean parameter that asks whether the verify the certificate or not (the default should be true)

**Comment by jkakavas** [comment]
Thanks for opening this @nivpenso . I will be closing this issue in favor of #29755. The use case described in this issue would be satisfied by the approach suggested in #29755

**Comment by tvernum** [comment]
> SSLed clusters must have a valid signed certificate.

To be clear, we _recommend_ SSL on the http port, but we only _require_ it on the transport port.
Reindex uses the http port, so it is possible (though not recommended) to reindex from a remote cluster without needing to handle certificates.

We do intend to make this easier per the plan in https://github.com/elastic/elasticsearch/issues/29755, but the current situation is not quite as you describe it.
