### ISSUE TITLE
High CPU usage while bulk indexing

### ISSUE THREAD

**Issue by motherhubbard** [elastic/elasticsearch#35248]
I have raised this issue previously:

https://github.com/elastic/elasticsearch/issues/31830

The discussion went over here:
https://discuss.elastic.co/t/high-cpu-usage-while-bulk-indexing/135023

The only time I received a response on the discussion was when I raised a git ticket in July and now despite regular updates from me the discussion item has closed.

I consider this a bug as the high CPU usage happens only when I am bulk indexing quite a few documents. I do not believe Elastic should behave this way and I am keen to understand why it does. Apologies for raising the ticket here but as the discussion went nowhere and I believe it is a bug it seemed like the only option left to me.

After some investigation I do not believe this to be caused by the datadogs monitoring solution.

Any help will be much appreciated.

**Comment by dakrone** [comment]
Given that this is a year old, I think it is a bit stale, so I am going to close this. If it occurs again, a new discussion on discuss.elastic.co would be the best place to get started diagnosing it.
