### ISSUE TITLE
SQL: Simplify expression optimization

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#35270]
A common case in the optimizer is improving predicate expressions which tend to be `Function`s. However when this is referred through its id and that id changes, the plan becomes inconsistent.
For example `SELECT COALESCE(null, 1) AS c FROM ... HAVING c > 100`

The optimizer will optimize the `Coalesce` definition but `HAVING c > 100` will still use the old script definition (now residing in the scalar reference).
This is a recurrent issue that affect all rules and proved to create bugs in the past due to old references lying around. In the above case it's even more problematic since the old id is not used (and thus the query does not blow up) but the old script is.

**Comment by costin** [comment]
relates #29853

**Comment by matriv** [comment]
The issue has been resolved with the refactoring of the NamedExpression: #49570.
