### ISSUE TITLE
Feature Request: Support listening on a unix socket

### ISSUE THREAD

**Issue by dominic-p** [elastic/elasticsearch#35283]
**Describe the feature**:
The title pretty much says it all. Sorry if this is already supported or I missed something obvious. I'm pretty new to Elasticsearch. I looked at [the docs here](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html) and I didn't see it mentioned.

I find administration a lot simpler when I can configure services that aren't supposed to be exposed publicly to listen on unix domain sockets instead of TCP ports.

Benefits include:
- Security is easier because access can be restricted simply by setting file permissions.
- I have read that performance is better.
- Probably others I haven't thought of.

This seems like a common need in the Elastic community. See [this request](https://github.com/elastic/kibana/issues/1652) for Kibana and [this one for APM](https://github.com/elastic/apm-server/issues/689).

**Comment by jasontedor** [comment]
Duplicates #21377. That issue is from two years ago, so the time is appropriate for us to consider this again. I’m not saying that we’ll come to a different conclusion, yet we can certainly discuss it again internally to see where are.

**Comment by dominic-p** [comment]
Sorry I missed the original question. Yeah, domain sockets make the most sense for a single node deployment (not the main focus of elasticsearch as I understand it). But, it would be nice for that use case. Thanks for your consideration.

**Comment by jasontedor** [comment]
> Yeah, domain sockets make the most sense for a single node deployment (not the main focus of elasticsearch as I understand it).

Yeah the overarching philosophy here though is that we do not build features for single-node deployments.

**Comment by s1monw** [comment]
@dominic-p thanks for opening this and explaining your idea. From our perspective not much has changed from the issues #21377 as well as the decision we made back then. The main aspect why we don't consider this a feature that we want to support is the single node nature of the feature. Elasticsearch is a distributed system and single node use cases can be an invariant but shouldn't be special-cased, we never added anything that only works only for the 1 node case.

**Comment by dominic-p** [comment]
Thanks for taking the time to explain your reasoning. I appreciate that.

**Comment by ihakh** [comment]
> The main aspect why we don't consider this a feature that we want to support is the single node nature of the feature

I am not using the elasticsearch right now
but it is not a bad thing to have this feature:

- this has to be done one time and any future release will support this
- there is no problem with this feature naturally (due to its nature) be available in single node
