### ISSUE TITLE
Minor bug in "Java High Level REST Client->Search Scroll API" documentation

### ISSUE THREAD

**Issue by vmaldosan** [elastic/elasticsearch#35307]
### The problem
While reading about the Search Scroll API, I saw what I believe is a minor bug in the [Full example section](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-search-scroll.html#java-rest-high-search-scroll-example):

```
...
SearchHit[] searchHits = searchResponse.getHits().getHits();
while (searchHits != null && searchHits.length > 0) { (2)
    SearchScrollRequest scrollRequest = new SearchScrollRequest(scrollId); (3)
    scrollRequest.scroll(scroll);
    searchResponse = client.scroll(scrollRequest, RequestOptions.DEFAULT);
    scrollId = searchResponse.getScrollId();
    searchHits = searchResponse.getHits().getHits();
    (4)
}
...
```
and then:
> (4) Process the returned search results

I might be mistaken, but if we process _searchHits_ where (4) is placed right now, we'd lose the first batch of results.

### The solution
Place (4) before _searchHits_ is updated with a new batch of results.

**Comment by vladimirdolzhenko** [comment]
Thank you for your interest to Elasticsearch but I don't think it's a bug - it means you can put processing code for `searchResponse` at `(4)` (it is the next line after `searchHits`) like we do [Async execution](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-search-scroll.html#java-rest-high-search-scroll-async) and many other places.

**Comment by vmaldosan** [comment]
Thanks, I was misled by the sentence "Process the returned search results", which it seems to point at _searchHits_.
