### ISSUE TITLE
Auto complete with filters

### ISSUE THREAD

**Issue by spencerfontein** [elastic/elasticsearch#35324]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by spencerfontein** [comment]
Hi,

we are trying to achieve auto complete, which we have achieved by suggest and fuzziness with the edge-ngram. We have roles for specific users and those roles determine whether the user can see specific subsets of a document. Is there anyway we can implement auto complete with filters? and also since Context Suggestion is deprecated is there something which will replace it?

**Comment by colings86** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
