### ISSUE TITLE
Documentation clarification around PUT or POST for _xpack/license API

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#35341]
The documentation [here](https://github.com/elastic/elasticsearch/edit/6.4/docs/reference/licensing/update-license.asciidoc) uses both PUT and POST for the `/_xpack/license` API endpoint.  Though both currently work, this can be confusing, and if one of the verbs is preferred (PUT?) could the documentation please reflect that by omitting the other?

**Comment by jrodewig** [comment]
[docs issue triage]
