### ISSUE TITLE
Watcher: DRY for waiting for watcher to start/stop in Integration tests

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#35348]
The following tests all perform similar (same?) logic to busy wait start and stop Watcher: 

* SmokeTestWatcherWithSecurityIT
* SmokeTestWatcherWithSecurityClientYamlTestSuiteIT
* SmokeTestWatcherTestSuiteIT
* WatcherRestIT
* XDocsClientYamlTestSuiteIT
* XPackRestIT

Ideally there wouldn't be so much copy paste as evident by https://github.com/elastic/elasticsearch/pull/35271.

**Comment by nik9000** [comment]
We've been wanting to move the watcher docs from the `x-pack/docs` folder to the `docs` folder and one of the blockers is having a consistent way to do this waiting. I intend to work on it at some point so I'm assigning it to me. But if anyone else is keen to work on it I'm happy to give it up and talk through what I've been thinking.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
