### ISSUE TITLE
Java High Level Rest client supports search after api?

### ISSUE THREAD

**Issue by bilalsha** [elastic/elasticsearch#35359]
Does Java high level rest client supports search after api?

**Comment by vladimirdolzhenko** [comment]
Hi @bilalsha ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
