### ISSUE TITLE
vm.max_map_count bootcheck should be conditional on the use of index.store.type=mmapfs

### ISSUE THREAD

**Issue by rubin55** [elastic/elasticsearch#35377]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.4.3, Build: default/tar/fe40335/2018-10-30T23:17:19.084789Z, JVM: 1.8.0_191

**Plugins installed**: []
none

**JVM version** (`java -version`):
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux c061993b6527 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Currently, when Elasticsearch boots up and detects it is not just running on localhost, it will invoke the bootchecks mechanism to make sure various things are sanely configured. One of those checks is for the value of `vm.max_map_count` to be at least `262144`. 

By default, Elasticsearch sets `index.store.type` to `fs` which means that Elasticsearch will select the performance-optimal index store type for the platform it's currently running on (see: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html for details about the possible store types).

The value of `vm.max_map_count` is only relevant when index.store.type=mmapfs; Consequently, When an Elasticsearch instance is configured to use another store type like `niofs` or `simplefs`, it should not check for the value of `vm.max_map_count` because the value is irrelevant to the niofs and simplefs storage types.

**Steps to reproduce**:
 
 0. Run `sysctl -w vm.max_map_count=10000`
 1. Set `index.store.type: niofs` in `elasticsearch.yml`
 2. Set `network.host: _site_` in `elasticsearch.yml`
 3. Start Elasticsearch and observe log output
 4. Watch ERROR message from bootchecks mechanism due to vm.max_map_count being to low despite the fact you're not using the `mmapfs` index store type.

**Provide logs (if relevant)**:

**Comment by rubin55** [comment]
Ow wait a minute.. https://github.com/elastic/elasticsearch/commit/bdfcc326d7ee351390fb26f928261926c39ae6ff 

Nothing to see here, move along.. I will test this `node.store.allow_mmapfs` setting you speak of and report back any successes as such..

**Comment by danielmitterdorfer** [comment]
Based on your comments in https://github.com/elastic/elasticsearch/pull/32421, I see you are about to check a nightly snapshot build of Elasticsearch 6.5.0 with `node.store.allow_mmapfs` set to `false`. We'll keep this issue open for now but that setting should likely help in your case.

**Comment by rubin55** [comment]
I mananged to test with 6.5.0-SNAPSHOT and can confirm that the allow_mmapfs setting is picked up by Elasticsearch. Furthermore, when deploying in a non-standalone fashion, I can confirm that the bootcheck for vm.max_map_count is skipped and the masters come up.

**Comment by danielmitterdorfer** [comment]
Thanks for checking and confirming it here @rubin55. Given your positive feedback, I'm closing this issue.
