### ISSUE TITLE
Misleading error message on has_parent query

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#35383]
Elasticsearch version 6.4.2

The `has_parent` query returns misleading error messages, referring to field `type` rather than field `parent_type`:

```
    "type": "illegal_argument_exception",
    "reason": "[has_parent] requires 'type' field"
```

and 

```
    "type": "parsing_exception",
    "reason": "[has_parent] query does not support [type]",
```

To reproduce:

```
POST _search
{
  "query": {
    "has_parent": {
    }
  }
}
```

and

```
POST _search
{
  "query": {
    "has_parent": {
      "type": "test"
    }
  }
}
```

**Comment by jimczi** [comment]
The issue was [fixed](https://github.com/elastic/elasticsearch/pull/31182) on master but never backported to 6x. It is backported now so I am closing this issue. Thanks for reporting @fkelbert .
