### ISSUE TITLE
[ILM] Create API to view the steps of a policy

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#35404]
**Problem Statement**

We have a [Move-To-Step API](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/ilm-move-to-step.html) that allows an advanced administrator to manually override the policy execution plan. It allows overriding which step in the policy is to be executed.

Without reading the code, it is almost impossible to know all the available steps one can move to.

**Proposed Solution**
Introduce a new API, maybe called Get Steps API.

```
GET _ilm/steps/<policy-id>
```

This will return something that shows the compiled view of the policy

```
{
  "policy": {
    "phases": {
      "hot": {
        "steps": [ "attempt_rollover", "complete" ]
      },
      "warm": {
        "steps": [ "readonly", "forcemerge", "segment-count", "readonly", "set-single-node-allocation", "check-shrink-allocation", "shrink", "shrunk-shards-allocated", "copy_execution_state", "aliases", "is-shrunken-index", "allocate", "check-allocation"  ]
        }
      },
   }  
}
```

other issues: Knowing step keys is useful for working with the API, but it isn't useful in understanding why one would want to move to that step. What does that step do?

**Comment by talevy** [comment]
Closing because this type of visibility into the underlying code may do more harm than good

**Comment by dakrone** [comment]
Reopening this, I think we may end up wanting this for diagnostic/support purposes

**Comment by dakrone** [comment]
Closing this in favor of #58128 which would remove the need to know these implementation detail steps.
