### ISSUE TITLE
Term Query Not Working For Fields With Spaces

### ISSUE THREAD

**Issue by refayathaque** [elastic/elasticsearch#35424]
Hello,

I am using AWS Elasticsearch 6.3 and trying to perform term queries on text fields that have spaces in them, unfortunately, it is not working. I would really appreciate your advice. Below is a code sample of my query. 

`{
    "query": {
      "bool": {
        "filter": {
          "bool": {
            "must": [
              {
                "terms": {
                  "orga": [ "acf", "acl" ]
                }
              },
              {
                "terms": {
                  "orgb": [ "asa", "asfr", "clinical center", "dab" ]`

^ Clinical Center is not being found...

Thank you,

**Comment by softwaredoug** [comment]
I would recommend posting full steps for recreating, as in

- Configure the index
- Index 1-2 docs
- Issue your search demonstrating the error

My sense is its possible "clinical center" is probably being tokenized into terms `[clinical]` and `[center]`

**Comment by cbuescher** [comment]
Hi @refayathaque! As @softwaredoug already said, this is probably cause by the way you have set up tokanization or your analysis chain. In general, your question is better suited to the support forums over at https://discuss.elastic.co.  We prefer to use Github issues only for bug reports and feature  requests, and we think it's more likely this is a question than a bug  report. I'm closing this as an issue here, but encourage you to ask this  question in the forum instead. Many thanks.
