### ISSUE TITLE
SQL: Lock-down JDBC driver at API/class level

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#35437]
Currently, JDBC driver is internally split into multiple packages which forces internal classes to be made public in order for them to be reused.
This has the unfortunate side-effect of exposing internal classes which, as the code evolves, will change and cause problems onto the users that incorrectly rely on them.
As history showed time and time again, the best way to avoid this is to not expose the classes in the first place.
This is more or less the case and by putting all classes inside one package, we can tighten the visibility of the classes to the expense of readability.
However as the work around `INTERVAL` showed, evolving the code base is significantly easier if the changes only happen internally.
As the user needs to know only about the `Driver`, `DataSource` and dedicated types, these are essentially the only classes needed.
As an alternative, we could introduce an `internal` prefix while maintaining most packages in place.

**Comment by jasontedor** [comment]
> As an alternative, we could introduce an internal prefix while maintaining most packages in place.

Whatever we do here, let us try to be consistent. We have previously considered and for the time-being are not using this approach within the Elasticsearch codebase. This might change someday where we can use an internal package name, or use annotations. For now, we are relying on documentation and the appropriate visibility where possible.

**Comment by costin** [comment]
Thanks Jason.
