### ISSUE TITLE
Test framework integration tests are not run by Gradle

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35435]
Commit 8936061f32474e029ad18d9c65d5686848578e42 adds [`public class InternalTestClusterIT extends ESIntegTestCase`](https://github.com/elastic/elasticsearch/commit/8936061f32474e029ad18d9c65d5686848578e42#diff-6bfb3f21b6eb827af7b26ea52b1be3f3R31) but as far as I can tell this does not run as part of `./gradlew check`. Adding `fail("test");` to the test method does not cause `./gradlew check` to fail.

There are not very many derivatives of `ESIntegTestCase` under `:test:framework`, but there are _some_, and I think these are also not running.

**Comment by atorok** [comment]
Once #35861 is merged, I will extend it to check for this scenario as well.

**Comment by rjernst** [comment]
@DaveCTurner The framework tests don't have integration tests. Tests ending in IT running without a real cluster are something we specially setup in `:server` for the `integTest` task.

**Comment by DaveCTurner** [comment]
Today there are at least these two suites:

- https://github.com/elastic/elasticsearch/blob/5c11b8612a0528b54a2bff118a0764874a312b00/test/framework/src/test/java/org/elasticsearch/test/test/SuiteScopeClusterIT.java
- https://github.com/elastic/elasticsearch/blob/5c11b8612a0528b54a2bff118a0764874a312b00/test/framework/src/test/java/org/elasticsearch/test/test/TestScopeClusterIT.java

**Comment by rjernst** [comment]
Sorry, I wasn't trying to say they don't necessarily exist, but instead that there is no task to run them.
