### ISSUE TITLE
Bug - ParsedReverseNested should implements ReversNested but not Nested interface

### ISSUE THREAD

**Issue by miiit** [elastic/elasticsearch#35449]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.4.2
**Plugins installed**: []

**JVM version** (`java -version`):
1.8.131
**OS version** (`uname -a` if on a Unix-like system):
Opensuse 15

**Description of the problem including expected versus actual behavior**:
ParsedReverseNested should implements ReversNested but not Nested interface.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Open IDE
 2. Look at the class **org.elasticsearch.search.aggregations.bucket.nested.ParsedReverseNested**
 3. Check interface (Currently the class implements Nested interface)

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Thanks @miiit, this is indeed confusing, it should be `ReversNested`. I will open a PR with a correction shortly.
