### ISSUE TITLE
Doc issue: incorrect syntax of Composite Aggregation#Sub Aggregations example

### ISSUE THREAD

**Issue by voidlps** [elastic/elasticsearch#35445]
**Elasticsearch version** : 6.x

**Description of the problem including expected versus actual behavior**:

In this page:
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-aggregations-bucket-composite-aggregation.html#_sub_aggregations

it should be "aggs" in the request, in the doc wrongly use "aggregations",
that is, should be changed to:
`
GET /_search`  
`{
    "aggs" : {
        "my_buckets": {
            "composite" : {
                 "sources" : [
                    { "date": { "date_histogram": { "field": "timestamp", "interval": "1d", "order": "desc" } } },
                    { "product": { "terms": {"field": "product" } } }
                ]
            },
`   **"aggs"**:  `{
                "the_avg": {
                    "avg": { "field": "price" }
                }
            }
        }
    }
}
`

**Comment by dliappis** [comment]
@voidlps I tried with both `aggs` and `aggregations` and got the same result. Did you receive an error yourself?

**Comment by polyfractal** [comment]
++ to what @dliappis said.  `aggs` or `aggregations` are allowed.  From [the aggregation docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html#_structuring_aggregations):

> The `aggregations` object (the key `aggs` can also be used) in the JSON holds the aggregations to be computed.

Unless you actually got an error I think this issue can be closed.

**Comment by voidlps** [comment]
Thanks, I realized now the errors come from another issue related to Composite Aggregation which doesn't apply to v6.2, not related to the syntax.  Please close this issue
