### ISSUE TITLE
Add a node filter to _cat/shards API

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#35467]
I would be useful to be able to filter `_cat/shards` on a per-node basis, similar to how you can filter per index pattern. Using `grep` is certainly a viable option, but allowing to filter at the API level would a.) conserve bandwidth, and b.) transitively give more functionality in Kibana's Console.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
