### ISSUE TITLE
Feature request: Normalize timelion graph with sparse data, and also split by top N values for a specified field.

### ISSUE THREAD

**Issue by pixrrs** [elastic/elasticsearch#35475]
**Describe the feature**:

This was discussed with Jason Alcorn in a support request. When it turned out what I wanted to do is not currently possible, they suggested filing a feature request.

I'm working with a sparse data set that I need to normalize to count-per-minute, similar to what's done here:
https://www.elastic.co/blog/sparse-timeseries-and-timelion

I also want to split the graph by a field. So far, the only way I've found to make this work is to plot each tool of interest separately, but that's both unwieldy and inflexible. 

What I expect when I do a split on the data in the right place is to get something that looks the same as if I made individual queries for the top N contributors, but that doesn't seem possible. 

Some things I tried in the demo site: 
(1) 
> .es(index=sys_rpg_tabledump_queue-*).if(eq, 0, null, .es(metric="sum:count", index=sys_rpg_tabledump_queue-*)).label("normalized total for all tools").fit(scale).scale_interval(1m).multiply(-1).bars().trim().title("no split")

This shows the normalized count for everything, and has values around 500,000

(2) 
> .es(split=tool:3, index=sys_rpg_tabledump_queue-*).if(eq, 0, null, .es(metric="sum:count", split=tool:3, index=sys_rpg_tabledump_queue-*)).fit(scale).scale_interval(1m).multiply(-1).bars().trim().title("split in both")

Here I put the split by tool in both calls to .es and somehow the totals for the top 3 tools are around 800,000

(3) 
> .es(index=sys_rpg_tabledump_queue-*).if(eq, 0, null, .es(metric="sum:count", index=sys_rpg_tabledump_queue-*, split=tool:3)).fit(scale).scale_interval(1m).bars().trim().multiply(-1).title("split in if")

Here I only put the split in the .es call within the if statement. You don't see any split in the graph, but I'm assuming it might be showing just the top tool since the numbers are around 300,000

(4) 
> .es(index=sys_rpg_tabledump_queue-*, split=tool:3).if(eq, 0, null, .es(metric="sum:count", index=sys_rpg_tabledump_queue-*)).fit(scale).scale_interval(1m).bars().trim().multiply(-1).title("split in 1st")

Here I only put the split in the 1st .es call, and you can see the top 3 tools, but somehow the values are around 1,500,000

(5) 
> .es(index=metricbeat-*).if(eq, 0, null, .es(metric="sum:apache.status.bytes_per_sec", q=host.name:gke-prod-demo-elastic--default-pool-2-6c749820-w1w7, index=metricbeat-*)).label("normalized total for 2-6c749820-w1w7").fit(scale).scale_interval(1m).multiply(-1).bars(stack=true).trim().title("individual queries"), .es(index=metricbeat-*).if(eq, 0, null, .es(metric="sum:apache.status.bytes_per_sec", q=host.name:gke-prod-demo-elastic--default-pool-1-8c155651-v29q, index=metricbeat-*)).label("normalized total for 1-8c155651-v29q").fit(scale).scale_interval(1m).multiply(-1).bars().trim().title("individual queries"), .es(index=metricbeat-*).if(eq, 0, null, .es(metric="sum:apache.status.bytes_per_sec", q=host.name:gke-prod-demo-elastic--default-pool-0-57d2bcba-jn8r, index=metricbeat-*)).label("normalized total for 0-57d2bcba-jn8r").fit(scale).scale_interval(1m).multiply(-1).bars().trim().title("individual queries")

Here I have a separate query for each of 3 host names. This seems to get the right numbers, but it's long and messy and you have to know the host names you want to split on.

**Comment by jasontedor** [comment]
Heya @pixrrs, thanks so much for you interest. Timelion is not handled on this repository though, but instead on the [Kibana/repository](https://github.com/elastic/kibana). Would you mind taking this as an HTTP 302 redirect and re-opening the issue there?

**Comment by pixrrs** [comment]
Ah, thanks for the info!
