### ISSUE TITLE
Support "_source" in input docs for a more-like-this query

### ISSUE THREAD

**Issue by ehaubert** [elastic/elasticsearch#35509]
From the documentation on the more_like_this query, like parameter:

The syntax to specify documents is similar to the one used by the [Multi GET API]
(https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html).

I would expect in this case, that 
```
     "like" : {
                "_index" : "test",
                "_type" : "_doc",
                "_id" : "2",
                "_source" : ["field3", "field4"]
            }
```

would only use "field3" and "field4" from test/_doc/2 as the inputs to the more_like_this query.   This is currently not supported:

```
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "failed to parse More Like This item. unknown field [_source]"
      }
    ],
```
This would allow restricting the input document source to only those fields being searched.

**Comment by markharwood** [comment]
The description says "is similar to" but not "is identical to". It is is similar in that it is an array of objects with `_index`, `_type` and `_id` parameters.

>This [source filtering] would allow restricting the input document source to only those fields being searched.

The second example in the MLT docs shows how to define the list of required fields alongside the Multi-GET-style list of docs.

Does this address your concern?

**Comment by ehaubert** [comment]
Perhaps I'm misunderstanding the documentation, but I don't think so.

The second example shows how to define the list of required fields in the target documents.

```
    "query": {
        "more_like_this" : {
            "fields" : ["name.first", "name.last"]
        }
}
```

But this does not restrict which fields are used from the source documents.  It is possible to construct artificial documents by manually passing in the fields of interest:

```
"query": {
    "more_like_this": {
        "like": {
                "_index" : "marvel",
                "_type" : "quotes",
                "doc" : {
                    "name": {
                        "first": "Ben",
                        "last": "Grimm"
                    },
                    "_doc": "You got no idea what I'd... what I'd give to be invisible."
                  }
            },
        }
    }
}
```

If I understand, you are suggesting that the caller create an artificial document with the fields of interest.   This is a work-around for documents with highly structured or concise fields, where the caller has the full text available  like tags, categories, etc, but is less desirable for full-text searches.   
Even for a single snippet/abstract type search this starts getting ugly:

```
"query": {
    "more_like_this": {
        "like": {
                "_index" : "my_library",
                "_type" : "scientific_journals",
                "doc" : {
                      "snippet" : "This is a study about very complicated things.  We did research, and got some results, and after that we analyzed them.  Some of our results were better than other results. It is also important to consider all the other research that has been done in our field recently and not-so-recently.  So we'll talk about that for a while also. Words, words, ......"
                  }
            },
        }
    }
}
```

This  limits the MLT to fields where the caller has the text.  It also makes the call extremely bulky when doing a MLT over several documents with longer useful fields.

**Comment by markharwood** [comment]
>The second example shows how to define the list of required fields

The second example in [the current docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html) I was referring to was this:

	GET /_search
	{
		"query": {
			"more_like_this" : {
				"fields" : ["title", "description"],
				"like" : [
				{
					"_index" : "imdb",
					"_type" : "movies",
					"_id" : "1"
				},
				{
					"_index" : "imdb",
					"_type" : "movies",
					"_id" : "2"
				},
				"and potentially some more text here as well"
				],
				"min_term_freq" : 1,
				"max_query_terms" : 12
			}
		}
	}

Are we talking about the same thing here?

**Comment by markharwood** [comment]
>Empirically, I do not believe the existing "fields" is tied to which fields are used from the documents specified 

Works for me: 

	DELETE test
	PUT /test/_doc/1
	{
	   "title" : "title1",
	   "author" : "author1",
	  "description" : "descriptionShared"
	}
	PUT /test/_doc/2
	{
	   "title" : "title2",
	   "author" : "author2",
	  "description" : "descriptionShared"
	}

	//Does not match
	GET /test/_search
	{
		"query": {
			"more_like_this" : {
				"fields" : ["title", "author"],
				"like" : [
				{
					"_index" : "test",
					"_type" : "_doc",
					"_id" : "1"
				}
				],
				"min_term_freq" : 1,
				"min_doc_freq": 1, 
				"max_query_terms" : 12
			}
		}
	} 

	//Does match
	GET /test/_search
	{
		"query": {
			"more_like_this" : {
				"fields" : ["title", "description"],
				"like" : [
				{
					"_index" : "test",
					"_type" : "_doc",
					"_id" : "1"
				}
				],
				"min_term_freq" : 1,
				"min_doc_freq": 1, 
				"max_query_terms" : 12
			}
		}
	}

**Comment by ehaubert** [comment]
Hmm, I get no matches on either of those.  Maybe it has changed in more recent versions?  I'm stuck on 5.x, because of the changes to how synonym files are parsed on the 6.x and beyond.

I'm seeing both generate the same underlying query:
```
GET /test/_validate/query?explain=true
{
	"query": {
		"more_like_this" : {
			"fields" : ["title", "author"],
			"like" : [
			{
				"_index" : "test",
				"_type" : "_doc",
				"_id" : "1"
			}
			],
			"min_term_freq" : 1,
			"min_doc_freq": 1, 
			"max_query_terms" : 12
		}
	}
} 
```
produces
```
{
  "valid": true,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "explanations": [
    {
      "index": "test",
      "valid": true,
      "explanation": "like:null -_uid:_doc#1"
    }
  ]
}
```

**Comment by markharwood** [comment]
OK. If you're happy that the current docs describe current behaviour correctly I'd like to close this issue which is about adding "_source" support.
There may be a different issue worth raising with 5.x functioning correctly but if it's working in 6.x I would guess it's a known issue that was already fixed.

**Comment by ehaubert** [comment]
In the example you posted (which I can't replicate), it is working better.  I don't know that shows the current documentation is sufficient. 

The underlying feature request was to be able to specify which fields from the input documents are used for input, independent of which fields are being searched in the MLT query.  The example you posted forces both to be the same.  That is better than what I'm seeing in 5.x, but not what I was trying to get at, either.

**Comment by ehaubert** [comment]
I agree that the idea behind MLT is simplicity, but would argue that it is also treating the source document as an abstraction.  

Termvectors has the same complexity as my fake document example above: the caller needs to have and provide the source text.

**Comment by markharwood** [comment]
>the caller needs to have and provide the source text.

Nope - see https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#_example_generating_term_vectors_on_the_fly

**Comment by ehaubert** [comment]
I don't think I understand what you are saying;  term vectors lets you generate the most 'interesting' terms on a given doc/field/blob of text/etc.

In order to use that in a query, you have to make two queries:
1) Get the terms in the source doc/field(s) of interest
2) Generate a query on the target index/fields of interest.

Or are you saying it is possible to do that in a single step?

**Comment by markharwood** [comment]
>I don't think I understand what you are saying

No, you've got it.
I was just correcting the part where you said "the caller needs to have and provide the source text."
I assumed you meant the client has to fetch the _full_ text first. It only needs to supply the doc id and it gets back just the interesting terms - so avoids transferring what could be megabytes over the wire.

**Comment by ehaubert** [comment]
OK.   Those two steps are exactly what MLT does; just right now, without letting you control the fields in play on the source documents.

There is already some coordination behind the scenes, because the input document mappings don't necessarily match the searched documents, or even be documents at all.

**Comment by ehaubert** [comment]
After today's discussion, it feels like that part is missing with or without my proposal?  What is the current mapping? title-to-title, description-to-description?    Historically, I think it was whole document X specified fields.

If the current mapping is field based, do the artificial documents need to have the same fields as those being searched? That wasn't the case historically, and I don't see it mentioned in the current docs.   Likewise, what about the "like": "some blank text without a doc" cases? That doesn't specify a field at all.

Also, if there is currently some notion of field mapping, how does that affect the number of terms in the underlying query? In the older cross-fields model, then you could easily end up selecting all "interesting" terms from one base field; those might or might not exist at all in another field, right?  So does field X field generate the required number of interesting terms on each field?

**Comment by markharwood** [comment]
It's admittedly vague. There's also [issues with highlighting](https://github.com/elastic/elasticsearch/issues/26357) which again is perhaps a good reason to opt for client-side construction of queries from the outputs of TermVector calls.
I know there has been a long-standing desire to revisit MLT design but I couldn't find any issues outlining a proposal.

**Comment by ehaubert** [comment]
+1.  
I think the TV approach short-circuits the purposes of having MLT in the first place, and unscientifically, it feels like a popular feature - at least, I've run into it 'in the wild' a few times now.  That being said,  for highly structured data, I am more likely to use a set of constant-score queries based on the actual values, and what you are suggesting isn't so different.   (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-constant-score-query.html)

I hadn't properly  thought through what the field mapping would look like, and doing that cleanly would be important.   Can we keep this open for a bit, and I'll get back to you after Thanksgiving?

**Comment by dliappis** [comment]
@ehaubert Don't want to put too much pressure but we tend to close open issues in need of additional feedback after 1 month of inactivity; do you still want to think about this, or should we close it?

**Comment by ehaubert** [comment]
After a month of sitting on this - I still think that being able to specify MLT field-per-field makes sense.    The most significant terms from one field aren't necessarily populated in another,  and this is particularly true for structured, or mixed  structured/unstructured data.  

Consider the case of ecommerce data: there might be a blobby text snippet, and 10 tagged fields describing color, material, price, etc.  Which would be more similar -another document with all the snippets matching, or another with the most significant terms from the blobby text?  The answer entirely depends the quality of the text vs the tagging.

The paradigm that has been used elsewhere in the API would be to specify the field as a tier in the query:

`"query": {
		"more_like_this" : {
			"target_field_name" : {
			"like" : [
			{
				"_index" : "test",
				"_type" : "_doc",
				"_id" : "1",
                                 "fields" : ["source", "fields", "to", "pull", "from"]
			}
			],
			"min_term_freq" : 1,
			"min_doc_freq": 1, 
			"max_query_terms" : 12
		}
	}`

Although expanding it thus gets verbose when there are multiple target fields:

``"query": {
		"more_like_these" : [ 
			{"target_field_name" : {
			"like" : [
			{
				"_index" : "test",
				"_type" : "_doc",
				"_id" : "1",
                                 "fields" : ["source", "fields", "to", "pull", "from"]
			}
			],
			"min_term_freq" : 1,
			"min_doc_freq": 1, 
			"max_query_terms" : 12
		} ]
	}``
etc

Thoughts?

**Comment by markharwood** [comment]
After some internal discussion we felt that that using a JSON-based field mapping syntax would be potentially complex and not as powerful/flexible as what could be achieved with small amounts of client-side code to assemble Boolean queries from selected fields in an example document.

I'll add some docs to the MLT query pointing out that the TermVectors API is another way to get the "interesting" terms from an example document and these can be combined with your choice of structured fields in custom code to create more tailored "MLT" type queries.
