### ISSUE TITLE
[CI] TasksClientDocumentationIT testCancelTasks fails in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#35514]
The `TasksClientDocumentationIT#testCancelTasks` test failed in CI. I was unable to reproduce this issue but it seems interesting as the task was already cancelled somehow.

Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/203/consoleFull

Reproduce line:

```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=95E5C18ABF7AD273 -Dtests.class=org.elasticsearch.client.documentation.TasksClientDocumentationIT -Dtests.method="testCancelTasks" -Dtests.security.manager=true -Dtests.locale=en-GB -Dtests.timezone=EST -Dcompiler.java=11 -Druntime.java=8
```

Failure:

```
java.lang.AssertionError: 
Expected: <[]>
     but: was <[[pz8Vyo5YTxmBo10WkrHmxg][5170] failed, reason [ElasticsearchException[Elasticsearch exception [type=illegal_state_exception, reason=task with id 5170 is already cancelled]]]]>
	at __randomizedtesting.SeedInfo.seed([95E5C18ABF7AD273:727604953DD61AAA]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.client.documentation.TasksClientDocumentationIT.testCancelTasks(TasksClientDocumentationIT.java:189)
```

**Comment by jaymode** [comment]
I muted this test in 634bc9d4ea5

**Comment by hendrikmuhs** [comment]
Another failure on `6.x`:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/182/consoleFull

**Comment by hendrikmuhs** [comment]
I backported this to `6.x`: https://github.com/elastic/elasticsearch/commit/a2087d3973bd2adf0eb5bfce9f6ecec3e695aec6

**Comment by dakrone** [comment]
I recently re-enabled this on master, I'm going to close this for now but if it occurs again we should re-open this and I'll take a look.
