### ISSUE TITLE
indices.breaker.total.limit is not word

### ISSUE THREAD

**Issue by koala775** [elastic/elasticsearch#35525]
**Describe the feature**:
As see in offical website:
![image](https://user-images.githubusercontent.com/35438579/48461984-41279000-e811-11e8-967d-3ca1a0cf104e.png)
but when my request include aggregation with a large number of data still OOM.

**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.0

**JVM version** (`java -version`):
jdk_1.8.152

**OS version** (`uname -a` if on a Unix-like system):
linux

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.aggregation  query frequently
 2.OOM

**Provide logs (if relevant)**:
![image](https://user-images.githubusercontent.com/35438579/48462228-5b15a280-e812-11e8-8856-31859ec9def7.png)

**Comment by markharwood** [comment]
To progress this we will need examples of the particular aggregations you are attempting. Please provide the JSON of the offending queries.

**Comment by polyfractal** [comment]
Hi @koala775, I'm going to close this issue due to lack of response.  If you can provide some more information that might help us debug the issue, please feel free to add it and re-open the issue.  Thanks!
