### ISSUE TITLE
Typo on pagerduty account section

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#35572]
Looks like this doc has a bug:
https://www.elastic.co/guide/en/elastic-stack-overview/6.5/actions-pagerduty.html#pagerduty-event-trigger-incident-attributes

In the `Pagerduty Action Attributes` Section under the `account` section it says `service_key_api` but it should be `service_api_key`

**Comment by tlrx** [comment]
Good catch! I created #35589
