### ISSUE TITLE
SQL: translating a query using "AND" conditions for the same field generates an error

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#35583]
A query of the form `WHERE my_field=10 AND my_field=50` would not translate successfully to an ES query:

```
{
    "error": {
        "root_cause": [
            {
                "type": "planning_exception",
                "reason": "Cannot generate a query DSL for SELECT my_field FROM test WHERE my_field=10 AND my_field=20"
            }
        ],
        "type": "planning_exception",
        "reason": "Cannot generate a query DSL for SELECT my_field FROM test WHERE my_field=10 AND my_field=20"
    },
    "status": 400
}
```

but the query itself would work if being executed with `/_xpack/sql`.

**Comment by astefan** [comment]
Not a bug. In this particular case (`my_field=10 AND my_field=50`) the condition of the query will always be `false` which means it will be a local execution (there won't be a query executed against ES indices) thus no query that `translate` can generate.

**Comment by costin** [comment]
I think for successful plans that end up being folded to a Local relationship, we should provide a more meaningful message instead of reporting it as an error.
@astefan can you please raise an issue for that?
