### ISSUE TITLE
Build failed with `kill failed: No such process`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35587]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=centos/59/console

This build failed. I am not wholly sure why, but suspect it could be this:

```
kill: sending signal to 22127 failed: No such process
...
Execution failed for task ':x-pack:qa:full-cluster-restart:without-system-key:v5.6.14-SNAPSHOT#oldClusterTestCluster#node0.stop'.
```

22127 was indeed the PID of `node0` in this cluster, but it looks from its log like it started up normally and did a bunch of stuff that one might expect a node to do. Possibly this is a Gradle-concurrency issue leading to attempting to shut it down twice? I'm tentatively labelling this as `:Core/Build` for that reason.

**Comment by jasontedor** [comment]
I wonder if the node was OOM killed or otherwise died abnormally.

**Comment by dliappis** [comment]
> I wonder if the node was OOM killed or otherwise died abnormally.

The worker was immutable and by the time this got triaged the worked had been retired. I opened an infra ticket to store `/var/log/{messages,syslog}` or `journalctl` output as required per OS to store important information e.g. about Linux OOM getting triggered.

**Comment by jdconrad** [comment]
This doesn't reproduce, and there isn't enough information here to do further investigation, so I'm going to close this.  If we have future failures similar to this we need to be more diligent in collecting information directly from the host as @dliappis suggested.
