### ISSUE TITLE
Watcher: Description field added potentially searchable

### ISSUE THREAD

**Issue by toddferg** [elastic/elasticsearch#35595]
**Describe the feature**:  I think it would be handy to have a called out description field in the watcher.  I know that it can currently be done somewhat in the metadata field.  But I think it would be handy to have a description field that is searchable in case of a lot of watchers.

**Comment by jakelandis** [comment]
This sounds like a good enhancement.

**Comment by spinscale** [comment]
metadata is currently searchable, see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/watches.json#L55-L58

**Comment by abprash** [comment]
@toddferg I would like to pick this up. Can i start working on this?

**Comment by abprash** [comment]
Hi @spinscale , @toddferg , wanted to double check if any documentation or unit test changes would be necessary for this change.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
