### ISSUE TITLE
Set cluster.routing.allocation.enable to "all"

### ISSUE THREAD

**Issue by spattnaik23** [elastic/elasticsearch#35617]
Shouldn't cluster.routing.allocation.enable be set to all when re-enabling routing allocation after upgrade?
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.5/rolling-upgrades.html

**Comment by spattnaik23** [comment]
Setting it to null resulted in errors. Primary shard failed to get activated. "all" helped with this issue.

**Comment by ywelsch** [comment]
@spattnaik23 can you provide a series of steps to reproduce this? Thank you.

> Setting it to null resulted in errors.

what kind of errors?

**Comment by spattnaik23** [comment]
I followed all the steps in the Rolling Upgrades guide (link provided above).
Received errors saying "Primary shard activation failed."

**Comment by ywelsch** [comment]
@spattnaik23 sorry, but this error report here is not actionable. It is missing all the information that's requested when opening an issue (e.g. ES version, ...) and there is no error message "Primary shard activation failed" emitted by our system. As this sounds more like a configuration problem than a bug, your question is better suited for the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for confirmed bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
