### ISSUE TITLE
breaker vs breakers in /_nodes/stats API

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#35615]
**Elasticsearch version** (`bin/elasticsearch --version`): all versions

**Description of the problem including expected versus actual behavior**:
Inconsistency in `GET /_nodes/stats/breaker` API vs its output.

In the output, **breakers** is shown as plural, but the API requires singular **breaker**, and when using `GET /_nodes/stats/breakers`, gets:
```
request [/_nodes/stats/breakers] contains unrecognized metric: [breakers] -> did you mean [breaker]?
```

All the other stats are consistent between its API and the output. for example
indices, os, process, jvm, network, transport, http, fs, and thread_pool

And the next hierachical level under indices are all consistent too, ie singluar vs plural. Except this breaker vs breakers.

**Comment by debadair** [comment]
The API docs use the singular for the metric name. Rather than a doc issue, I think the point was that the response contains an element called _breakers_ rather than the singular, but that's consistent with the naming scheme & is probably by design. Removing the docs label.

**Comment by Leaf-Lin** [comment]
Sorry, I probably was not clear in my original post.
The output from `GET _nodes/stats/breaker` shows:
```
"breakers" : {
        "request" : {
          "limit_size_in_bytes" : 374125363,
          "limit_size" : "356.7mb",
          "estimated_size_in_bytes" : 0,
          "estimated_size" : "0b",
          "overhead" : 1.0,
          "tripped" : 0
        },
       ...
```

Note the plural in the output. But all the other stats have exactly the same API. 
This is probably an ECS area?
