### ISSUE TITLE
LocalExporter leaks a licence state listener

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35627]
Today, `LocalExporter` removes its `licenseChanged()` method from the licence state listener when closed:

https://github.com/elastic/elasticsearch/blob/816e6f6a08be821d8ec01b51bf383544d1e341b0/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java#L155

However in fact this does nothing, because it involves a new `Runnable` that is different from the one we added earlier. The fix is fairly trivial, but writing the test for the fix has overflowed my stack of yaks so I'm spilling it out here.

**Comment by rayz2007** [comment]
Hi! I'd like to help on this issue

**Comment by DaveCTurner** [comment]
Thanks @rayz2007, go for it.

**Comment by markquis91** [comment]
Hi @rayz2007 and @DaveCTurner is this still being worked on? If not I will take it.

**Comment by DaveCTurner** [comment]
No word from @rayz2007 so it seems not. Please go ahead @markquis91.

**Comment by jasontedor** [comment]
@rayz2007 @markquis91 thanks for your interest although we have opened a fix for this in #36308.
