### ISSUE TITLE
OptOutQueryCache leaks a licence state listener

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35628]
Today, `OptOutQueryCache` adds a listener for changes to licence state:

https://github.com/elastic/elasticsearch/blob/816e6f6a08be821d8ec01b51bf383544d1e341b0/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/accesscontrol/OptOutQueryCache.java#L46

It does not, however, remove this listener when closed. Possibly this is related to this forum issue: https://discuss.elastic.co/t/post-upgrade-issues-6-4-2-es-heap-running-away-6-5-0-too/151096/24 (although I don't understand the full chain of events that leads from this to an OOM).

**Comment by jasontedor** [comment]
Will be closed by #36308.
