### ISSUE TITLE
Configuration files in /etc should probably not be group-writable

### ISSUE THREAD

**Issue by jcassee** [elastic/elasticsearch#35634]
This issue was opened to get wider discussion after a [conversation on the forum](https://discuss.elastic.co/t/debian-package-creates-configuration-file-writable-by-the-elasticsearch-process/156748/2).

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.4.3, Build: default/deb/fe40335/2018-10-30T23:17:19.084789Z, JVM: 10.0.2

**Plugins installed**: none

**JVM version** (`java -version`):
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 
Linux elk-test 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04)

**Description of the problem including expected versus actual behavior**:

Configuration files installed in `/etc/elasticsearch` are group-writable:
```
$ ls -l /etc/elasticsearch
drwxr-s---  2 root elasticsearch 4096 Nov 14 00:33 ./
drwxr-xr-x 98 root root          4096 Nov 14 01:06 ../
-rw-rw----  1 root elasticsearch  207 Nov 14 00:32 elasticsearch.keystore
-rw-rw----  1 root elasticsearch 2869 Oct 31 00:22 elasticsearch.yml
-rw-rw----  1 root elasticsearch 3009 Oct 31 00:22 jvm.options
-rw-rw----  1 root elasticsearch 6380 Oct 31 00:22 log4j2.properties
-rw-rw----  1 root elasticsearch  473 Oct 31 00:22 role_mapping.yml
-rw-rw----  1 root elasticsearch  197 Oct 31 00:22 roles.yml
-rw-rw----  1 root elasticsearch    0 Oct 31 00:22 users
-rw-rw----  1 root elasticsearch    0 Oct 31 00:22 users_roles
```

This means these files are writable by the elasticsearch process itself. I think removing the group write bit would be safer and less surprising to an administrator.

The group write bits were added in #20966 in order to allow operators to change the configuration without being root. However, as far as I known this is not usual practice and should probably not be the default. Also, many configuration settings can be changed using the [Cluster Update Settings API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html).

**Comment by jasontedor** [comment]
>This means these files are writable by the elasticsearch process itself.

On the filesystem level they are, but the Elasticsearch process drops permissions at startup and after dropping permissions we can not write to these files.

**Comment by rjernst** [comment]
As was noted on the linked discuss issue, [this is intentional](https://github.com/elastic/elasticsearch/pull/20966#pullrequestreview-4499012), and as Jason points out, the Elasticsearch process cannot write to the directory due to our security manager configuration.

@jcassee Thanks for opening this, but I think we should close this as not a bug. Based on the above explanation, do you agree?

**Comment by jcassee** [comment]
@rjernst I was surprised and a bit shocked when I looked at the config directory. The use of the Java [security manager configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html#modules-scripting-other-layers) is not immediately apparent. My reasoning is that the principle of least surprise trumps a convenience for specific local admin procedures, especially in the area of security.

That said, even a closed ticket is a good Google target for other people who wonder the same thing. :smile: I'm fine with closing the issue.
