### ISSUE TITLE
SQL: Allow MIN() and MAX() aggregate functions to operate also on arguments of type keyword

### ISSUE THREAD

**Issue by MagnusAnde** [elastic/elasticsearch#35639]
Allow `MIN()` and `MAX()` aggregate functions to operate
also on arguments of type keyword (and eventually also text) apart from the numeric and date.

This would simplify queries using GROUP BY returning columns of type keyword (and eventually text) that is not part of the group by statement. This would also harmonize with the expected behavior from persons used to sql in for example Sql Server.

```sql
select max(fieldOfTypeKeyword) from someIndex group by otherFieldOfTypeKeyword
```

This would return the last value in alphabetic order for the field `fieldOfTypeKeyword` in the group defined by the group by statement. The min() function would do the inverse.

**Comment by costin** [comment]
_added minor formatting to your post_

Thanks for the suggestion. This would essentially translate `MAX` and `MIN` into a more generic `FIRST` and `LAST` aggregate function (as it expands beyond numeric types and thus their meaning is slightly different).

We could support this through a `terms` agg with a size of 1.
