### ISSUE TITLE
SQL: Perform lazy evaluation of mismatched mappings

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#35659]
Especially in the logging case, it is common to have mappings with some inconsistencies yet these fields are never used in the result, e.g.:
```sql
SELECT longitude, latitude, dateTime 
FROM "mike_location*"
ORDER BY dateTime
LIMIT 1
```
returns

> Unexpected error from Elasticsearch: [verification_exception] Found 1 problem(s) line 2:6: [mike_location*] points to indices with incompatible mappings; field [previous_location] is mapped in [2] different ways: [object] in [mike_location], [geo_point] in [mike_location-v2]

While the message is correct, note that the problematic fields are not used.
Such queries should be allowed since the problematic fields are never used and thus can be safely ignored.

**Comment by alexfrancoeur** [comment]
cc: @elastic/kibana-canvas
