### ISSUE TITLE
Proposed simplifications to _suggest

### ISSUE THREAD

**Issue by anneveling** [elastic/elasticsearch#3565]
Recent changes to configure field suggestions (see http://www.elasticsearch.org/blog/you-complete-me/) are a step forward, but may be improved as follows.

I would suggest a default configuration that would work on any field (i.e. no special configuration needed in the mapping file).

Calling a suggest for a field would look like this:

curl -X POST localhost:9200/hotels/_suggest -d '{
  "text": "m",
  "field": "title"
}'

This would work on using all emitted tokens for the "title" field, whatever is specified there (analyzers, whether or not to lowercase, split) and autosuggest words from it. It's likely this would be too slow and indeed FSTs need to be stored at index time, and may need to be in the mapping file. If so, then not as a different type, but as an add-on flag:

{
  "mappings": {
    "hotel": {
      "properties": {
        "title": { "type": "string", "store_suggest_fsts": true}
      }
    }
  }
}

Note that the suggester would use the same field (query) analyzer on the input, so to also split the query!

This means that typing in "state un" would be analyzed in 2 tokens: "state" and "un" (because the title field is a default "string"). For both words the suggester could suggest alternatives, but by default it could do it only for the last word (assuming the user is still typing there). This could then match the word "union" if there is a document with "State of the Union" as the title. (of course also many other "un*" words).

This is different than the current implementation, because there the suggester only works for full matches from the beginning of the field: if we would have a "title_suggest": {"type":"completion"} field, then typing in "state un" would find NOTHING, because there is no title that matches "state un*"

This is better because it could work with 0 or very limited configuration, and also fits the use case of actual suggestions better (where we are not merely matching against a simple prefixable field, but against freetext).

It would be nice if the suggester could then also boost the "union" completion because there is a colocated "state" match, but that is left as an exercise for the ElasticSearch gurus ;-)

By deferring the definition of the atoms to match against to the existing, flexible analyzers, this gives this much more control. We could even add fuzziness or stemming to the match targets...

WDYT

**Comment by clintongormley** [comment]
Closing in favour of #13692
