### ISSUE TITLE
[CI] LongGCDisruptionTests testNotBlockingUnsafeStackTraces failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#35686]
`org.elasticsearch.test.disruption.LongGCDisruptionTests testNotBlockingUnsafeStackTraces` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/239/console

The error is:

```
06:45:56 ERROR   32.0s J3 | LongGCDisruptionTests.testNotBlockingUnsafeStackTraces <<< FAILURES!
06:45:56    > Throwable #1: java.lang.RuntimeException: suspending node threads took too long
06:45:56    > 	at __randomizedtesting.SeedInfo.seed([398753F563ED0502:3B941B4A47C3BD6B]:0)
06:45:56    > 	at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:118)
06:45:56    > 	at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:149)
06:45:56    > 	at java.lang.Thread.run(Thread.java:748)
```

This doesn't reproduce locally for me:

```
./gradlew :test:framework:test \
  -Dtests.seed=398753F563ED0502 \
  -Dtests.class=org.elasticsearch.test.disruption.LongGCDisruptionTests \
  -Dtests.method="testNotBlockingUnsafeStackTraces" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-ZA \
  -Dtests.timezone=America/Fort_Nelson \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by ywelsch** [comment]
@original-brownbear can you have a look at this? Thank you.

**Comment by original-brownbear** [comment]
On it :)

**Comment by droberts195** [comment]
The same test also failed last Saturday on the 6.x branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/65/console

It's the same exception:

```
22:15:09 ERROR   32.0s J1 | LongGCDisruptionTests.testNotBlockingUnsafeStackTraces <<< FAILURES!
22:15:09    > Throwable #1: java.lang.RuntimeException: suspending node threads took too long
22:15:09    > 	at __randomizedtesting.SeedInfo.seed([233B903DA45135A3:2128D882807F8DCA]:0)
22:15:09    > 	at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:118)
22:15:09    > 	at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:149)
22:15:09    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by original-brownbear** [comment]
It does not seem entirely impossible that we are just getting unlucky here and the suspender thread simply doesn't get scheduled often enough when running multiple parallel JVMs. I added some logging in https://github.com/elastic/elasticsearch/pull/35702 that should make it completely clear where the problem lies here.

**Comment by original-brownbear** [comment]
This is a really strange failure. It happened once in `master` and once in `6.x` in a 24h period on the 19th and 20th of Nov. Before that it happened in 2017 more than a year earlier.
=> I would vote closing this. We now have better logging that should allow for tracking the issue down if needed, but I don't see what action I can take here unless it fails again.

**Comment by ywelsch** [comment]
> We now have better logging that should allow for tracking the issue down if needed, but I don't see what action I can take here unless it fails again.

I agree

**Comment by benwtrent** [comment]
Failed again in build: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-7&&immutable/30/consoleFull

```
02:37:31 ERROR   31.9s J4 | LongGCDisruptionTests.testNotBlockingUnsafeStackTraces <<< FAILURES!
02:37:31    > Throwable #1: java.lang.RuntimeException: suspending node threads took too long
02:37:31    > 	at __randomizedtesting.SeedInfo.seed([6AB1F3531F128FA:4B8578A15DF9093]:0)
02:37:31    > 	at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:124)
02:37:31    > 	at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:149)
02:37:31    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by markharwood** [comment]
[Build stats ](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22testNotBlockingUnsafeStackTraces%22%20AND%20class:org.elasticsearch.test.disruption.LongGCDisruptionTests'),sort:!(time,desc))) tracking

**Comment by original-brownbear** [comment]
I think I was able to track this down and fix it in https://github.com/elastic/elasticsearch/pull/39261:)
