### ISSUE TITLE
Allow for 'grace period expiration' before shard reallocation?

### ISSUE THREAD

**Issue by diranged** [elastic/elasticsearch#3569]
It would be really useful to allow for a 'grace period' between when ES notices that a particular node has gone down, and shard-reallocation begins. There are times when we might want to do a quick restart of an ES node ... or take one down for a full reboot ... and we don't want to do a re-allocation of shards because thats a very IO-intensive operation. In our case, we also use the Zookeeper plugin, and a shard-reallocation is triggered by a short communication break between the ES nodes and Zookeeper.

**Comment by cfeio** [comment]
+1, We would really love to see a configurable time out also. In an unplanned outage we would prefer to  be able to configure not have replicas reassigned and shuffled, as this leads to a lot of data moving. As far as I know I am not aware of such a setting.

**Comment by shyem** [comment]
+1, this would be really helpful for us as we have a massive amount of data in our ELK cluster and since we already have 1 replica available still there is no point of duplicating that one more time.

**Comment by jpountz** [comment]
Fixed via https://github.com/elastic/elasticsearch/pull/11712
