### ISSUE TITLE
Documentation inconsistencies for Query String Query -> auto_generate_phrase_queries

### ISSUE THREAD

**Issue by weberhofer** [elastic/elasticsearch#35729]
**Elasticsearch version** 6.x:
There is an inconsistency between https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-dsl-query-string-query which says: "auto_generate_phrase_queries -> Defaults to false"

And the changelog for 6.x:
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html
saying "The auto_generate_phrase_queries parameter for the query_string query has been removed, use an explicit quoted query instead. If provided, it will be ignored and issue a deprecation warning."

I guess, that this setting nowadays doesn't make any difference (is that right?). This should be noted in the documentation, too.

**Comment by cbuescher** [comment]
@weberhofer good point, the setting will definitely be ignored starting with the next major release (master branch), at least it should be removed there. I will take a look what the current state is on the 6.x branches as well.

**Comment by cbuescher** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/35734
