### ISSUE TITLE
SQL: Implement IFNULL(expr1, expr2) function

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#35749]
Implement IFNULL a variant of COALESCE used by MySQL but also other DBs.
It's also included in the ODBC spec as system function:
//https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/system-functions?view=sql-server-2017

Relates to #34956

**Comment by costin** [comment]
Please update the description in #34956 as well. Thanks.
