### ISSUE TITLE
Feature request: Shard-level row limiting for efficient (but approximate) deep pagination

### ISSUE THREAD

**Issue by pontus-mp** [elastic/elasticsearch#35776]
### What
We would like it to be possible to limit the number of rows returned from each shard during queries.

### Why
[Deep pagination is demanding in distributed systems](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html), but it's theoretically possible to sacrifice a bit of accuracy to make this a lot faster. By carefully reducing the number of rows returned from each shard, you can get (fairly) accurate results but with a much smaller workload.

You can find a discussion about this in Solr: https://issues.apache.org/jira/browse/SOLR-5611

**Comment by polyfractal** [comment]
I'm not positive if it is identical in practice, but I would guess that [`terminate_after` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#_parameters_4) gives much the same effect?  `terminate_after` tells the shard to stop collecting results after `n` documents have been collected

**Comment by pontus-mp** [comment]
`terminate_after` didn't work as expected when I experimented with it. I did a test with `offset=100`, `size=200`, which (if I understand things correctly) should collect 300 hits per shard. However, using `terminate_after=300` with an otherwise unchanged query resulted in very different hits.

I assume it's more intended as a circuit breaker which does not consider scoring when triggered, or similar?

**Comment by jimczi** [comment]
`terminate_after` stops the collection after `n` documents have been collected regardless of how they rank in the query. The costly part of deep pagination is that each shard needs to return the top N documents starting from 0 no matter what `from` is. The feature that is proposed here is to return a top N per shard where N is less than the total requested `size`. The idea is that the contribution to the final top N is spread among the shards if the rank of documents is randomly distributed. 

I have some concerns with this approach. I understand it can help to speed up the retrieval of a deep page but how can you ensure a consistent pagination if retrieving the next deep page can completely invalidate the top N of the previous page ? With this solution it would be possible to return the same document on two different pages which makes the pagination less useful.
I also don't think we should encourage deep pagination like that, we have other solutions that are more scalable and that does not require to sacrifice precision. A feature like [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html) for instance allows to efficiently walk deep into a search, why not using that ?

**Comment by pontus-mp** [comment]
`search_after` is great when you are doing things like iterating over entire result sets, but implementing good pagination for user-facing search functionality ends up being quite challenging. Using "next-only" pagination is simple, but that tends to frustrate users.

The shard-level limit might seem quite dangerous at first, but you can do things like having no limit for the first X pages and then using a limit that will still give you 99.9% accuracy as you go deeper into the result set. Shutterstock actually does this, apparently quite successfully!

I'm not suggesting that there should be some built-in "fuzzy-pagination" function in elasticsearch, but rather that the tools are available for that.

**Comment by jimczi** [comment]
We don't plan to work on this feature so I am closing this issue, we have solutions for deep pagination (`search_after`, `scroll`)  that don't affect precision. It is still possible to implement the proposed solution but we think that it would be more consistent to do it in a plugin rather than in the `_search` endpoint.
