### ISSUE TITLE
[Monitoring] Make LocalExporter::openBulk Async

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#35797]
This is a spin-off from #35765 and #35743, but specifically targeting the `LocalExporter` bulk initialization code.

Like #35765 is doing with the `HttpExporter::openBulk`, the `LocalExporter::openBulk` initialization code needs to be made truly, fully async as well.

**Comment by ekalgolas** [comment]
Can I work on this?

**Comment by pickypg** [comment]
@ekalgolas I was going to start work on this issue early next week, and it depends on the work done in #35765, which is not yet merged. It's probably best to find another issue.

**Comment by ekalgolas** [comment]
ohk sure no worries
