### ISSUE TITLE
Lower `ulimit -n` from 65536 to 65535 for increased compatibility

### ISSUE THREAD

**Issue by martel** [elastic/elasticsearch#35839]
Please consider lowering open files limit by 1 for increased compatibility with Amazon Linux which sets 65535 limit by default in its _/etc/security/limits.d/amazon-limits.conf_:

```
#Added by amzn-ami-acc.xml recipe.
* hard nofile 65535
* soft nofile 65535
```

Related to:
https://github.com/elastic/elasticsearch/issues/17430

**Comment by jasontedor** [comment]
@martel Thanks for raising this! We have made this change in #37537.
