### ISSUE TITLE
Invalid order of tasks when sort by column running_time in /_cat/tasks

### ISSUE THREAD

**Issue by krzotr** [elastic/elasticsearch#35840]
**Elasticsearch version**:
6.5.1

**JVM version**
1.8.0

**OS version**
Debian 9 (Linux debian 4.9.0-8-amd64)

**Description of the problem including expected versus actual behavior**:

I tried to sort all Elasticsearch tasks from longest running time to shortest `/_cat/tasks?v&s=running_time:desc`. Please check below column `running_time`.

```
GET /_cat/tasks?v&s=running_time:desc

action                         task_id                      parent_task_id               type      start_time    timestamp running_time ip           node
cluster:monitor/tasks/lists[n] 6t3Zvq1-Qni0yV3LF3JWog:34915 6t3Zvq1-Qni0yV3LF3JWog:34914 direct    1542927706982 23:01:46  71.5micros   192.168.1.27 6t3Zvq1
cluster:monitor/tasks/lists    6t3Zvq1-Qni0yV3LF3JWog:34914 -                            transport 1542927706982 23:01:46  223.7micros  192.168.1.27 6t3Zvq1
indices:data/write/index       6t3Zvq1-Qni0yV3LF3JWog:34911 -                            transport 1542927706980 23:01:46  1.4ms        192.168.1.27 6t3Zvq1
indices:data/write/bulk[s]     6t3Zvq1-Qni0yV3LF3JWog:34912 6t3Zvq1-Qni0yV3LF3JWog:34911 transport 1542927706981 23:01:46  1.3ms        192.168.1.27 6t3Zvq1
indices:data/write/bulk[s][p]  6t3Zvq1-Qni0yV3LF3JWog:34913 6t3Zvq1-Qni0yV3LF3JWog:34912 direct    1542927706981 23:01:46  1.2ms        192.168.1.27 6t3Zvq1
```

As i mentioned before, longest to shortest `running_time`, `1ms` > `7micros`.

Received order of tasks is wrong: 71.5micros, 223.7micros, 1.4ms, 1.3ms, 1.2ms

Expected result: 1.4ms, 1.3ms, 1.2ms, 223.7micros, 71.5micros

I have tested in production environment `5.6.12` and see the same wrong order.

**Steps to reproduce**:

 1. Go to `/_cat/tasks?v&s=running_time:desc`
 2. check order of tasks (column `running_time`)

**Comment by jasontedor** [comment]
This is [documented behavior](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/cat.html#numeric-formats):

> The human values are not sortable numerically, so in order to operate on these values where order is important, you can change it.
