### ISSUE TITLE
SQL: Implement missing time conversions in JDBC driver

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#35846]
Currently the Jdbc driver lacks conversion to the JDK 8 `java.time` types, namely `LocalDate/Time/DateTime` and `OffsetDateTime/Time`.

This needs fixing and also worth checking whether we're missing any other obvious type.

**Comment by matriv** [comment]
Closing this as I think this is covered with the implementation of DATE & TIME types. @costin feel free to reopen if something more is needed.
