### ISSUE TITLE
Documentation request: conditionals in ingest pipelines

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#35845]
Currently for every processor, the `if` section states only:

> Conditionally execute this processor.

...but does not say _how_ a conditional should be written (e.g. "It's Painless!").  It would be super-useful to have a page of typical/useful examples and some information about how to write conditionals.

**Comment by jakelandis** [comment]
@robin13 - the doc was running a bit late w/r/t the feature's introduction. The doc is there now : https://www.elastic.co/guide/en/elasticsearch/reference/6.5/ingest-conditionals.html

Closing as resolved by https://github.com/elastic/elasticsearch/pull/35044
