### ISSUE TITLE
SQL: all sql requests return null pointer exception

### ISSUE THREAD

**Issue by liujin1993** [elastic/elasticsearch#35875]
I hava a crontab job which send sql request every minute. It runs well for some time, but suddenly all sql requests return 500 null pointer exception. It recover only after I  restart the whole cluster!

![image](https://user-images.githubusercontent.com/31949674/48964774-e1d43780-efe9-11e8-91ef-fc52a4bc8700.png)

**Comment by costin** [comment]
Hi,
can you please provide more information about the query you are making and how many times it runs before getting this error? Does anything show up in the logs?

Also you are running on 6.4.2, I recommend upgrading to the latest 6.5.1 as there have been many enhancements to SQL that aren't in 6.4.x line.

**Comment by liujin1993** [comment]
@costin  hi, I am sorry that i do not know how this bug is triggered, and the error log is all in the image. There is no more information I can find.
the sql is simple: select percentile(total_cost) as total_cost from adserver-2018.11.23 where "@timestamp">'xxx' and "@timestamp" < 'xxx'

**Comment by costin** [comment]
@liujin1993 can you please upgrade and see whether the issue occurs? would it be possible to log the results from the cronjob to get a sense of then this occurs (maybe it's a timeout issue?).

P.S. You can use `BETWEEN` for min/max comparison: `WHERE @timestamp BETWEEN 'aaa' AND 'bbb'`

**Comment by matriv** [comment]
Closing this as there is no update for long time.
@liujin1993 Feel free to re-open if you still face this issue.
