### ISSUE TITLE
[mapper_parsing_exception] No handler for type [string] declared on field

### ISSUE THREAD

**Issue by ietuday** [elastic/elasticsearch#35899]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.0.4

**Description of the problem including expected versus actual behavior**:
I using elastic search for my ecoomerce project but it showing following error: 
"Error: [mapper_parsing_exception] No handler for type [string] declared on field [category]"

**Steps to Reproduce** : 

I am using mongoosastic. Following is the code of Schema :
var mongoose = require('mongoose');
var mongoosastic = require('mongoosastic');
var Schema = mongoose.Schema;

var ProductSchema = new Schema({
    category: { type: Schema.Types.ObjectId, ref: 'Category'},
    name: String,
    price: Number,
    image: String
});

ProductSchema.plugin(mongoosastic, {
    hosts: [
        'localhost:9200'
    ],
});

module.exports =  mongoose.model('Product', ProductSchema);

When I try to create map between MongoDB and Elastic replica of Products. It shows the error.

**Provide logs (if relevant)**:
  
status: 400,
  displayName: 'BadRequest',
  message:
   '[mapper_parsing_exception] No handler for type [string] declared on field [category]',
  path: '/products/_mapping/product',
  query: {},
  body:
   '{"product":{"properties":{"category":{"type":"string"},"name":{"type":"string"},"price":{"type":"double"},"image":{"type":"string"}}}}',
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category]"}],"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
****************************************************************************************************************
Thanks in advance

**Comment by jimczi** [comment]
The issue is in `mongoosastic, `string` is replaced by `keyword` and `text` in Elasticsearch since 5x so I guess that the project needs to be updated. I'd advise to open an issue in https://github.com/mongoosastic/mongoosastic.

**Comment by ietuday** [comment]
OK, Thanks

**Comment by gkhabas76** [comment]
@francois46090 @ietuday have you guys found out the solution??

**Comment by francois46090** [comment]
Hi,

not yet, unfortunetly. I think it's the different version of mongoose and
elasticSearch.


Stéphanie François




Le mer. 2 janv. 2019 à 20:40, Govinda Khabas <notifications@github.com> a
écrit :

**Comment by iitsuraj** [comment]
reference => https://github.com/mongoosastic/mongoosastic#geo-mapping
var ProductSchema = new Schema({
    category: {type: Schema.Types.ObjectId, ref: Category, es_type:'text'},
    name: {type: String, es_type:'text' },
    price : {type:Number,es_type:'long'},
    image: {type: String, es_type:'text'},
});
It work for me
