### ISSUE TITLE
SQL: split the metrics by successful/failed/total

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#35894]
At the moment XPackFeatureSet functionality reports data for query types (having, order by, group by etc) as a total. Would be better to have these being each reported as successful/failed/total. This means that the metric type itself needs to be passed down to the verifier.

**Comment by costin** [comment]
@eskibars thoughts about the above? would that impact you in any way? the global total/failed/successful metrics would still be available but the idea here is to have them also per feature.
Is this something you think it's worth doing?

**Comment by eskibars** [comment]
I'm not sure how much incremental value there is with this vs number of fields generated (field explosion).  I can't think of a lot of questions I could answer with this that I couldn't answer without it, but if there are ideas, let's chat about them.

**Comment by wchaparro** [comment]
Superceded by ES|QL
