### ISSUE TITLE
Allow different co-ordinate systems for geometric objects.

### ISSUE THREAD

**Issue by keedon** [elastic/elasticsearch#3590]
It looks like elasticsearch only allows WGS-84 coordinates for geometric objects, the application I'm currently working on uses OSGB-36 which throws an exception when you try to insert a node with co-ordinates outside of the allowed range for WGS-84

Thanks

**Comment by desruisseaux** [comment]
Just in case the information may be of some use: Apache SIS 0.6 can create Mercator, Transverse Mercator, Lambert Conical and Stereographic map projections for a Coordinate Reference System defined in Well Known Text (WKT) format. It supports both version 1 and 2 of WKT. Apache SIS 0.7 (to be released in one or two months) will add support for EPSG codes, datum shifts and a few more map projections.

**Comment by clintongormley** [comment]
@nknize would you consider adding support for different coordinate systems?

**Comment by desruisseaux** [comment]
If there is any interest to start a thread or a wiki page on this subject, I may be able to help with some proposals on the coordinate transformations part.

**Comment by zmays** [comment]
Please update the documentation - if one sends anything but wgs84, for example, web mercator, like this:
`{"location":{"type":"GeometryCollection","crs" : {
          "type" : "name",
          "properties" : {
            "name" : "urn:ogc:def:crs:EPSG::3857"
          }
        },"geometries":[{"type":"MultiPolygon","coordinates":[ [ [ [ -11458202.599282084, 3936157.3620158276 ], [ -11459165.477255989, 3936155.366018667 ], [ -11459163.694921646, 3935177.6040588915 ], [ -11458202.66477565, 3935177.7214682177 ], [ -11458202.599282084, 3936157.3620158276 ] ] ], [ [ [ -11458202.599282084, 3936157.3620158276 ], [ -11457239.720985424, 3936159.277695415 ], [ -11457237.807021441, 3937140.8780615395 ], [ -11458202.533897068, 3937137.0839141724 ], [ -11458202.599282084, 3936157.3620158276 ] ] ] ]
}]}}`
this is the message one gets:
`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [location]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [location]",
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": null
    }
  },
  "status": 400
}`

Which takes a long time to figure out what is going on.

**Comment by Sue-Gallagher** [comment]
Closed by #29305
