### ISSUE TITLE
[ILM] Mechanism to bypass rollover and move to next action for indices where indexing is complete

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#35944]
At the moment ILM will wait indefinitely for the rollover conditions to be met before allowing the index to progress on its lifecycle. This is exactly what we should expect to happen in most cases but sometimes the user will decommission an index (stop indexing to it entirely). This can be for a few reasons:

* The user is no longer indexing from that source
* The user has changed indexing strategy and is indexing to a completely different index pattern with a different alias now

In these cases there is currently no good way for the user to indicate that the index is "complete" and it should continue to move through its lifecycle.

One idea here would be to introduce a new index setting named something like `index.lifecycle.index_complete` which the rollover steps can look at to determine that a rollover is not needed and they can return complete without checking the rollover conditions or performing rollover. The check could error if the write alias is still present on the index so ILM has some confidence that the index is not being used.

This setting could also be used in the CCR use-case to indicate that the leader index has been rolled over so when replicated to the follower index the follower would know to move passed the hot phase when the following index has caught up with the leader.

**Comment by gwbrown** [comment]
As https://github.com/elastic/elasticsearch/pull/36235 and https://github.com/elastic/elasticsearch/pull/36620 have been merged (+ backported appropriately), we can close this issue now.
