### ISSUE TITLE
[Docs] Add a warning to the default max number of shards allowed in a cluster

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#35943]
The `cluster.shards.max_per_node` setting has been added in #34021 & #34892 as a soft limit on the number of shards that are allowed in a cluster, with the default ratio of 1,000 shards per node.

I do not question this default value but I think that we should make it really clear in the doc (under a WARNING section or something) that this default value could already be too high for many clusters. The risk I see here is people interpreting that "it is OK to have 1,000 shards on 1 Elasticsearch node" because this is the max default value we propose.

**Comment by tlrx** [comment]
@gwbrown I'm raising this to your attention :)

**Comment by gwbrown** [comment]
This is a great point, thanks for bringing it up.  I'll add this note shortly.
