### ISSUE TITLE
Move security audit logs to use ILM and write aliases

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#35941]
Once ILM is complete we should move the security audit log indexes over so they use write aliases to index and also have them use ILM to manage rolling over and deleting the indexes.

For now this work is stalled waiting for the ILM feature to be completed

/cc @bmcconaghy @bleskes

**Comment by jaymode** [comment]
We're planning to deprecate the index audit trail in 6.x and remove it in 7.0 once https://github.com/elastic/beats/issues/8831 has been implemented so I do not think we should invest time in switching this over to use ILM.

**Comment by bleskes** [comment]
cool. I'm good to close.
