### ISSUE TITLE
Watcher: Prevent storing of unbounded watch records

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#35997]
**Describe the feature**: Right now, every watch execution creates a so called watch record, which contains detailed information about the returned data to inputs, the execution of the condition and optionally the actions.

If the data returned by an action or an input is big, then the created watch record will also be big. There are certain watches, where the watch record can grow unbounded because it is querying the watch history and every document in there is being added to the current watch record.

I think we should think to find a way to cap those big watch records (even though we are losing information), to make sure loading/searching those will not lead to memory issues. I am unsure on top of my head if this makes sense in watcher itself or if there are some Elasticsearch features we could explore.

**Comment by dakrone** [comment]
Closing in favor of #94745
