### ISSUE TITLE
LLREST: Add RestClient.builder(java.util.Collection<Nodes> nodes)

### ISSUE THREAD

**Issue by Zanfas** [elastic/elasticsearch#36006]
The tittle is quite self-explaining. It would be convienent to have a direct way to pass a collection of nodes as argument of the RestClient.builder method. In some situations, the nodes that will be used by the client can only be known at runtime and you can't use the RestClient.builder(Node … nodes) method.

Currently, I have to do an ugly thing like that (tested code) :

```
Node fakeNode = new Node(HttpHost.create("http://localhost:9200"))) // Non-sense params
this.elasticClient = new RestHighLevelClient(RestClient.builder(fakeNode));
this.elasticClient.getLowLevelClient().setNodes(nodes); // Real nodes
```

Note : the fake node can have any configuration, it seems it does not matter. The machine I used for the test did not run the ElasticSearch service.

**Comment by nik9000** [comment]
@Zanfas, I've retitle the issue and edited the description to use code blocsk to make it a little cleaner.

Could you do something like:
```
this.elasticClient = new RestHighLevelClient(RestClient.builder(nodes.toArray(new Node[0]));
```

That isn't as efficient because you need to allocate an array or two but it does get the job done.

Personally, I like having a `Collection` based API but I'm sure we need it here.

**Comment by Zanfas** [comment]
Yes, It works and it also works with a cast : (Node []) nodes.toArray(). I don't why I had a problem with these two ways yesterday and not today.

Thank you for your help (but still, it would be great to be able to provide a Collection) :)
