### ISSUE TITLE
JUnit tests extending ESSingleNodeTestCase can cause Maven surefire-plugin to fail build

### ISSUE THREAD

**Issue by arjansh** [elastic/elasticsearch#36003]
When running JUnit tests using Elasticsearch 6.5.1's test framework in an Apache Maven build (which uses the maven surefire-plugin for executing the tests), the test can fail when one of the test classes extends the `org.elasticsearch.test.ESSingleNodeTestCase` class.

In my case I was using Elasticsearch 5.6.3 with Maven surefire-plugin 2.22.0, java version "1.8.0_152" on a Windows 10 machine.

**Steps to reproduce**:

1. Within a Maven project which uses a the maven surefire-plugin to run its unit tsest, create a JUnit test which extends the `org.elasticsearch.test.ESSingleNodeTestCase` class.
2. Create another JUnit test class.
3. Make sure the maven surefire-plugin execute the JUnit test which extends the `org.elasticsearch.test.ESSingleNodeTestCase` class first when executing the test.
4. Now build the project using `mvn package`.

I created a project on github which can be built to reproduce the problem: [elasticsearch-surefire-test](https://github.com/arjansh/elasticsearch-surefire-test).

**Stacktrace during Maven build**:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project elasticsearch-surefire-test: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Work\git\elasticsearch-surefire-test\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] access denied ("java.util.PropertyPermission" "*" "read,write")
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] access denied ("java.util.PropertyPermission" "*" "read,write")
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I assume this is caused by the fact that the `org.elasticsearch.test.ESSingleNodeTestCase` class sets a custom SecurityManager for the JVM and the Maven surefire-plugin can't handle that.

Also I'm not sure if I should also (or instead) log this issue at the Maven surefire-plugin project.

**Comment by nik9000** [comment]
`ESSingleNodeTestCase` is really for testing plugin interactions with deep parts of Elasticsearch and, for the most part, we use [randomizedtesting](https://labs.carrotsearch.com/randomizedtesting.html) for these tests so I'm not particularly surprised it doesn't work outside of there. Most tests that actually use the access to the internal bits of Elasticsearch that `ESSinlgeNodeTestCase` provides are difficult to debug because they have to do evil things to put the node in a weird state.

I suppose the question is "what do you want this for?" If you want a convenient way to start up Elasticsearch for testing your own code, something like the [elasticsearch maven plugin](https://github.com/alexcojocaru/elasticsearch-maven-plugin) is probably going to serve you better because it is designed for that. If you are developing an Elasticsearch plugin then the gradle build tools that we publish might be the way to go. Or randomized runner in maven if you aren't a gradle fan.

I can't speak to whether or not this is a surefire bug. I'm fairly sure we won't actively support using `ESSingleNodeTestCase` or `ESIntegTestCase` in surefire either way. If it works, great, but we might break it at any time because we don't test it because we don't use it.

**Comment by nik9000** [comment]
I'm going to close this issue as something we won't fix because, well, we won't make `ESSingleNodeTestCase` work with surefire.
