### ISSUE TITLE
unable start 'elasticsearch-service-x64' service after installed Java 11

### ISSUE THREAD

**Issue by johnhu2018** [elastic/elasticsearch#36018]
This looks more of Java issue than elasticsearch. after installed Java JDK 11, elasticsearch service unable to start. Error log show
CreateJavaVM Failed
The system cannot find the file specified.
Failed to start Java
ServiceStart returned 4

Java 11 is new, no past posting on this version, and no JRE 11 yet, it still use JRE 8u191.

Any suggestions or similar experience? 

Thanks in advance for any help!

John

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
