### ISSUE TITLE
SQL: SUM\AVG  FUNCTION CAN NOT WORK WITH LIKE

### ISSUE THREAD

**Issue by zouming123** [elastic/elasticsearch#36039]
In 6.5,  SQL: SUM\AVG  FUNCTION CAN NOT WORK WITH LIKE
the  sql which like below is not work.

eg；
select avg(salary), sum(salary) from emp where first_name like 'G%'

**Comment by matriv** [comment]
Aslo valid in master (7.0.0) and 6.x
