### ISSUE TITLE
Docker TLS encryption docs still refers to elasticsearch-platinum image

### ISSUE THREAD

**Issue by lio-p** [elastic/elasticsearch#36058]
Elastic stack version: 6.5

The following documentation page: https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html refers to the Docker image:  `docker.elastic.co/elasticsearch/elasticsearch-platinum:6.5.1`

I think now it should be `docker.elastic.co/elasticsearch/elasticsearch:6.5.1`

**Comment by javanna** [comment]
There's a PR opened that should fix this: #35890 .

**Comment by jasontedor** [comment]
Closed by #35890
