### ISSUE TITLE
Option to Zip Snapshots into a Large File Instead of Many Small Files 

### ISSUE THREAD

**Issue by mahaffey** [elastic/elasticsearch#36076]
**Describe the feature**:

For my use case as an ELK stack, each day is its own index. Once an index is greater than x days old, I take a snapshot and send it to AWS S3. This sends S3 many small files, some of which are only a few bytes in size. I would like to be able to further archive these to S3 Glacier after another period of time in order to save on storage costs.

The issue is that archiving from S3 standard storage to S3 Glacier storage results in 40KB of metadata for each object (file), which of course I would be charged for. 40KB times thousands of small byte sized files would result in tons of uneccessary expenses/overhead. If each index snapshot was zipped into one large file (probably in the many MB range in size) this could be a feasible long term archival solution.

I also would not want to affect the abilty to restore them easily with the snapshot restore API.

Thanks

**Comment by ywelsch** [comment]
We discussed this today in the distrib sync. Support for zipping the files would not play well with the incremental nature of the snapshot/restore functionality, which works at the per segment file level. There are other reasons as well why we're not supporting direct backups to Glacier, see https://github.com/elastic/elasticsearch/issues/12500#issuecomment-375013311. There are ways however to reduce the number of files (reducing the number of indices, force merging shards, ...).
