### ISSUE TITLE
Audit filter in log4j2 not taking effect when "xpack.security.audit.logfile.events.include" specifying multiple events.

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#36096]
**Elasticsearch version** (`bin/elasticsearch --version`):
Tested on both 6.2.3 and 6.2.4, both of them have this issue.

**Plugins installed**: []
x-pack

**JVM version** (`java -version`):
1.8.0_161

**OS version** (`uname -a` if on a Unix-like system):
Linux 4db072fad34a 4.9.125-linuxkit 

**Description of the problem including expected versus actual behavior**:
Inconsistent audit filter behaviour when using  "xpack.security.audit.logfile.events.include" vs  "xpack.security.audit.logfile.events.exclude".

**Steps to reproduce**:
Essentially I want to filter the audit log with this line `appender.audit_rolling.filter.regex.regex = .*`
For now, I use .* which means that should apply to all the audit trail generated from xpack.security.audit.logfile.events

When I have different events included in elasticsearch.yml file, the output in audit log should all be empty, as I have filter out everything. But it's not true for some of the scenarios below.

**In `elasticsearh.yml` file:**
```
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.emit_request_body: true 
#xpack.security.audit.logfile.events.include  #[1]
xpack.security.audit.logfile.events.include: [authentication_success, run_as_granted]  #[2]
xpack.security.audit.logfile.events.include: [authentication_success]  #[3]
xpack.security.audit.logfile.events.exclude: [authentication_success, run_as_granted]  #[4]
xpack.security.audit.logfile.events.exclude: [authentication_success]  #[5]
xpack.security.audit.logfile.events.exclude: ""  #[6]
```

**In `x-pack/log4j2properties` file:**
```
logger.xpack_security_audit_logfile.name = org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail
logger.xpack_security_audit_logfile.appenderRef.console.ref = console
logger.xpack_security_audit_logfile.level = info

logger.xpack_security_audit_logfile.appenderRef.audit_rolling.ref = audit_rolling
logger.xpack_security_audit_logfile.additivity = false
appender.audit_rolling.type = RollingFile
appender.audit_rolling.name = audit_rolling
appender.audit_rolling.fileName = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_access.log
appender.audit_rolling.layout.type = PatternLayout
appender.audit_rolling.layout.pattern = [%d{ISO8601}] %m%n
appender.audit_rolling.filePattern = ${sys:es.logs.base_path}${sys:file.separator}${sys:es.logs.cluster_name}_access-%d{yyyy-MM-dd}.log
appender.audit_rolling.policies.type = Policies
appender.audit_rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.audit_rolling.policies.time.interval = 1
appender.audit_rolling.policies.time.modulate = true
appender.audit_rolling.filter.regex.type = RegexFilter
appender.audit_rolling.filter.regex.onMatch = DENY
appender.audit_rolling.filter.regex.regex = .*   
appender.audit_rolling.filter.regex.onMisMatch = ACCEPT
```

The expected behaviour is that no matter which line I included in [1]..[6], all output should be the same.

[1] not specifying the events.include at all, **works**
[2] specifying multiple events in the events.include, **fails** <-- this is unexpected.
[3] specifying only one event in events.include, **fails** <-- this is unexpected.
[4] sepcfiying multiple events in the events.exclude, **works**
[5] specifying only one event in events.exclude, **works**
[6] specifying null in events.exclude, **works**

**Comment by albertzaharovits** [comment]
@Leaf-Lin I understand that
```
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: [authentication_success, run_as_granted]
```
in **elasticsearch.yml**, together with
```
appender.audit_rolling.filter.regex.type = RegexFilter
appender.audit_rolling.filter.regex.onMatch = DENY
appender.audit_rolling.filter.regex.regex = .*   
appender.audit_rolling.filter.regex.onMisMatch = ACCEPT
```
in **config/x-pack/log4j2.properties** does not produce the expected behavior which is to not print the audit events to elasticsearch_access.log .

I was not able to reproduce this in 6.2.4 .

**Comment by Leaf-Lin** [comment]
Could you ensure this line is included in the elasticsearch.yml file as well?
`xpack.security.audit.logfile.events.emit_request_body: true`

I haven't tried 6.2.2, but can confirm 6.2.3 and 6.2.4 both exhibit the same issue.
Btw, my original post was edited. When only one event was included, [3] doesn't work either.

**Comment by albertzaharovits** [comment]
Using a fresh ES 6.2.3, `bin/elasticsearch-plugin install x-pack`:

In **elasticsearch.yml** :
```
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: [authentication_success, run_as_granted]
xpack.security.audit.logfile.events.emit_request_body: true
```
together with:
```
appender.audit_rolling.filter.regex.type = RegexFilter
appender.audit_rolling.filter.regex.onMatch = DENY
appender.audit_rolling.filter.regex.regex = .*   
appender.audit_rolling.filter.regex.onMisMatch = ACCEPT
```
in **config/x-pack/log4j2.properties** .
run
`./bin/x-pack/setup-passwords interactive`
and 
`curl -u elastic -X GET 'localhost:9200'`
and
**logs/elasticsearch_access.log** is empty (no reproduction).

**However I think I know what the problem is**: the `appender.audit_rolling.filter.regex.regex` setting has trailing whitespaces.

**Comment by albertzaharovits** [comment]
We have narrowed the issue down on a separate channel.
The problem was that bulk requests contain end-of-line in the request body, which the `.*` will not match by default. Instead the `(?s).*` [1] regex should be used instead.

Thank you Leaf for the perseverance to replicate the issue!

[1] https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#DOTALL
