### ISSUE TITLE
SQL: wrong number of items in rows for interval statement with GROUP BY

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#36110]
The following statement:
```
SELECT MONTH(birth_date) AS m, MONTH(birth_date + INTERVAL '1-2' YEAR TO MONTH) AS f FROM test_emp GROUP BY birth_date ORDER BY birth_date ASC LIMIT 5
```
will return an extra value in each row, besides those described in the `columns` object:
```
{"columns":[{"name":"m","type":"integer"},{"name":"f","type":"integer"}],"rows":[[2,4,"1952-02-27T00:00:00.000Z"],[4,6,"1952-04-19T00:00:00.000Z"],[5,7,"1952-05-15T00:00:00.000Z"],[6,8,"1952-06-13T00:00:00.000Z"],[6,8,"1952-06-29T00:00:00.000Z"]]}
```

**Comment by cbismuth** [comment]
I'll have a look at this one.

**Comment by cbismuth** [comment]
Hi, I can't setup a smooth development workflow to work on this. I've created a topic on [discuss.elastic.co](https://discuss.elastic.co/t/debugsqlspec-and-integration-tests/), it would be great if someone could help. Thanks :+1:

**Comment by bpintea** [comment]
This has been fixed in the meantime and works with current master.
