### ISSUE TITLE
Regarding mapping a column of existing index to open nlp pipeline

### ISSUE THREAD

**Issue by Neel-Gagan** [elastic/elasticsearch#36146]
Hi, 

i have been tryping to use opn-nlp plugin in my extising index. 
The index [test] had been crated using the fscrawler and i want to apply NLP onto the content field of my index [test]. 

Elasticsearch version-6.4.2
OS version-Windows 8
pluginused-open-nlp 

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
