### ISSUE TITLE
Ingest Node: Drop processor is ignored with on_failure

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36151]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**: If a `drop` processor is used within `on_failure` of another processor, it seems to be ignored.

**Steps to reproduce**:

```
PUT _ingest/pipeline/pipeline1
{
  "processors": [
    {
      "fail": {
        "message": "failed",
        "on_failure": [
          {
            "drop": {}
          }
        ]
      }
    }
  ]
}

PUT foo/bar/1?pipeline=pipeline1
{
  "foo": "bar"
}

# this document exists, but should not
GET foo/bar/1
```

This example looks somewhat artifical, but it might make more sense with another `if` in the drop and maybe a `grok` processor instead of `fail` - I just picked those to shorten the example.

original issue in the [discuss forum](https://discuss.elastic.co/t/drop-processor-does-not-appear-to-work-in-elastic-search-6-5-0-with-grok/158914)

**Comment by ajazam** [comment]
I am the person who originally created the forum issue. I had to sanitize the code to remove company specific information.
