### ISSUE TITLE
Simulate Ingest API: Drop processor cannot be verified

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36150]
**Describe the feature**: Using the simulation API for custom pipelines, it is not possible to find out, if a document would be dropped

Create a pipeline that drops all documents

```
PUT _ingest/pipeline/droppipeline
{
  "processors": [
    {
      "drop": {}
    }
  ]
}

PUT foo/bar/1?pipeline=droppipeline
{
  "message": "123"
}

# document does not exist
GET foo/bar/1
```

However running the simulate API does not indicate that the document will not be created

```
POST _ingest/pipeline/droppipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": "text"
      }
    }
  ]
}

```

returns

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_type",
        "_id" : "_id",
        "_source" : {
          "message" : "text"
        },
        "_ingest" : {
          "timestamp" : "2018-12-03T10:16:52.719501Z"
        }
      }
    }
  ]
}

```

**Comment by original-brownbear** [comment]
Just a small hint for tracking this down: I think this work in the initial version in https://github.com/elastic/elasticsearch/pull/32278#issuecomment-407013588 when I manually tested it.

**Comment by roncohen** [comment]
just ran into this. Looks like it's still a problem in 7.3.
How about simply not including dropped docs in the simulate response?

**Comment by martijnvg** [comment]
> How about simply not including dropped docs in the simulate response?

Yes, I think either returning `{}` or `null` as array element in case a doc is dropped is good.
