### ISSUE TITLE
Reporting to email feature free?

### ISSUE THREAD

**Issue by LinguaFranca0** [elastic/elasticsearch#36154]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by LinguaFranca0** [comment]
Hi, does anyone use Reporting (to email via pdf) feature on Kibana 6.x? If so, is it a basic (X-pack) feature or licensed (?
According to https://www.elastic.co/products/stack/reporting,Reporting to Email is done by combining the **reporting** and **alerting** capabilities.
However, on https://www.elastic.co/subscriptions, it appears alerting feature is licensed? Can anyone please confirm this, and also provide any suggestions for Reporting (to email via pdf) for free?
Thanks, John

**Comment by astefan** [comment]
@LinguaFranca0, please ask this question on https://discuss.elastic.co/ where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on https://discuss.elastic.co/.

Thank you for your understanding.
