### ISSUE TITLE
SQL: CONCAT should return NULL when the field involved has a NULL value?

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36169]
SQL Server 2017, by default, will consider [`null` values in `CONCAT()` function as empty strings](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-2017) and return a non-null value. But, it also offers the option of changing this setting by using `CONCAT_NULL_YIELDS_NULL` setting. They do warn, though, that this option will be `ON` in a future version of SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/statements/set-concat-null-yields-null-transact-sql?view=sql-server-ver15. The [preview docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-concat-null-yields-null-transact-sql?view=sql-server-ver15) for SQL Server 2019 does still have the option default as `OFF` (so `null` is considered empty string).

PostgreSQL will also "ignore" null values and treat them as empty strings: https://www.postgresql.org/docs/11/functions-string.html

**Comment by nik9000** [comment]
Generally I'd do what PostgreSQL does unless PostgreSQL is being crazy. It looks like PostgreSQL is fairly reasonable:
```
test=# SELECT CONCAT(NULL) = '';
 ?column? 
----------
 t
(1 row)

test=# SELECT CONCAT('a', NULL, 'b');
 concat 
--------
 ab
(1 row)
```


This looks like what SQL Server does by default too. That warning in the PostgreSQL docs seem to be about if you end up with a `NULL` array and you pass it to `CONCAT` with the `VARIADIC` keyword.

**Comment by matriv** [comment]
Weirdly enough for the `||` operator postgres behaves differently:
```
test=# select null || 'marios' is null;
 ?column?
----------
 t
(1 row)
```

**Comment by matriv** [comment]
I would vote to stick with PostgreSQL behaviour as well here.

**Comment by costin** [comment]
+1. Let's go with Postgres.

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/2ed6ab9648cb6d93d6c27fe9b0db3e5a5c57e91e
6.x (6.6.0): https://github.com/elastic/elasticsearch/commit/e18771011e3c60d07b7338997fc6e62dc3f30aaa
