### ISSUE TITLE
Why I used Wildcard query ，start with "*" and end with "*" is also so fast too!!!

### ISSUE THREAD

**Issue by ennian001** [elastic/elasticsearch#36201]
Why I used Wildcard query ，start with "*" and end with "*" is also so fast too!!!
but as the official document says "In order to prevent extremely slow wildcard queries, a wildcard term should not start with one of the wildcards * or ?"
My field size is about 100 characters and my test data is about 15Gb.
could you give me an example of a situation where it's going to be slow，plz?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by ennian001** [comment]
oh thinks for your remind~~~

**Comment by ennian001** [comment]
oh thinks for your remind~~~
