### ISSUE TITLE
SQL: support CASE (WHEN) expression

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36200]
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/case-transact-sql?view=sql-server-2017

Simples use case: `SELECT (CASE WHEN (value = 1) THEN 'yes' ELSE 'no' END) AS decision FROM test`

**Comment by matriv** [comment]
Backported to `7.x` with 67d4e399c274e4123b4ba7ac90fe9438994d803e

**Comment by joey-91** [comment]
Despite improvements I'm unable to make this query work, 

SELECT
SUM(CASE WHEN "verb" = 'invite-phone' THEN 1 ELSE 0 END) as force
FROM "events-*"

Are there plans to add this functionality?

Thanks

**Comment by astefan** [comment]
@joey-91 that is a separate use case unfortunately, that comes with its own challenges. There is a github issue already created for that, for some time now: https://github.com/elastic/elasticsearch/issues/37271

**Comment by rameshkr1994** [comment]
Hi new here for elastic search ;
need help 👍 
[https://discuss.elastic.co/t/how-can-we-convert-join-query-into-elastic-search/197783/2](url)

please go through this link and help 


Thanks
