### ISSUE TITLE
Mapping: Index coercion configuration is ignored

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36227]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**:

When setting the index level coercing setting `"index.mapping.coerce": true` mentioned at https://www.elastic.co/guide/en/elasticsearch/reference/6.5/coerce.html#coerce-setting - it is ignored when documents are indexed.

**Steps to reproduce**:

```
PUT foo
{
  "settings": {
    "index.mapping.coerce": true
  }
}

GET foo

PUT foo/doc/1
{
  "date": "12345678"
}

GET foo/_mapping

```

the last mapping call returns a text multi field instead of a number

```
{
  "foo" : {
    "mappings" : {
      "doc" : {
        "properties" : {
          "date" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```

When setting the coercion on the field in the mapping and leaving out the global index option, everything works as expected.

**Comment by jimczi** [comment]
I think this is expected, `coerce` defaults to true for all fields but it doesn't influence how the dynamic mapping will infer types for unknown fields. It works from the datatype of a field to determine the kind of inputs that are accepted not the other way around. If you want to dynamically detect numbers inside strings you can activate the [numeric detection](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#numeric-detection) (disabled by default) in the dynamic field mapping.
