### ISSUE TITLE
[CI] ForecastIT#testSingleSeries fails reproducibly on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#36258]
First seen in this PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/1289/consoleFull

This reproduces for me on master:

```
./gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner -Dtests.seed=3B7BFF05D7416702 -Dtests.class=org.elasticsearch.xpack.ml.integration.ForecastIT -Dtests.method="testSingleSeries" -Dtests.security.manager=true -Dtests.locale=fr -Dtests.timezone=Cuba -Dcompiler.java=11 -Druntime.java=8
```

Failure:
```
> Throwable #1: java.lang.AssertionError:
   > Expected: <1544007600000L>
   >      but: was <1544009400000L>
   >    at __randomizedtesting.SeedInfo.seed([3B7BFF05D7416702:5C63C1FD2F7DCD17]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.ml.integration.ForecastIT.testSingleSeries(ForecastIT.java:103)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by cbuescher** [comment]
I haven't found many recent failures like this in the CI mails so far, so I guess its only this specific seeds problem and I'm keeping the test unmuted for now.

**Comment by droberts195** [comment]
I think this is probably a side effect of elastic/ml-cpp#327 and will cause a lot of failures.  I will mute the test.

**Comment by droberts195** [comment]
Muting commits are:

* a3c1c6938a374dda7de0ad48ae35d3842c6805fe in master
* 62e5a0cce734a2f25f76f1de0b28aa00c3ec108a in 6.x
* 20fed29bbde11c4feb08c3410a7a92be30778406 in 6.5

**Comment by hendrikmuhs** [comment]
elastic/ml-cpp#327 changed the bucket timestamps the forecast is created, before it was at the beginning of a bucket, now it is in the middle.

This perfectly explains the error: `1544009400000` is 30 minutes after `1544007600000` and the bucket span of the test is 1 hour. 

The test needs to be adjusted.

**Comment by jdconrad** [comment]
A few more:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/305/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/101/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/101/console
