### ISSUE TITLE
Weekly date math not calculating correctly

### ISSUE THREAD

**Issue by untergeek** [elastic/elasticsearch#36265]
This is true with Elasticsearch versions 5.6.12 and 6.5.0 when executed on 2018-12-04 or 2018-12-05

```
# GET <test-commit-{now/w+4w{YYYY-ww}}>
GET %3Ctest-commit-%7Bnow%2Fw%2B4w%7BYYYY-ww%7D%7D%3E
```
yields:
```
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "test-commit-2018-01",
        "index_uuid": "_na_",
        "index": "test-commit-2018-01"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "test-commit-2018-01",
    "index_uuid": "_na_",
    "index": "test-commit-2018-01"
  },
  "status": 404
}
```
Note that it is `2018-01` instead of `2019-01`

If I change and run with `+5w` it returns `2019-02`.  Somewhere in there the date math is incorrectly calculated.

**Comment by pgomulka** [comment]
thank you for raising this @untergeek and @32328254  
all versions before 7.0 are using joda-time internally, therefore the format in a pattern you provide should be  
`# GET <test-commit-{now/w+4w{xxxx-ww}}>`
where `x` means weekyear and `w` a week in a weekyear
https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

The format you provide is compatible with java-time and will work in elasticsearch version >7.0
`# GET <test-commit-{now/w+4w{YYYY-ww}}>`
`Y` - weekyear and `w` a week in a weekyear
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by pgomulka** [comment]
I am also going to follow up and update the documentation so that this information is more clear.
For the time beeing I will close that issue. If you need more help  feel free to open and comment.

**Comment by 32328254** [comment]
ok，thanks
