### ISSUE TITLE
Elasticsearch store.size and pri.store.size does not updated after creating an index

### ISSUE THREAD

**Issue by YuvalPruss** [elastic/elasticsearch#36274]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.11

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): Linux elasticsearch 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 Linux

**Description of the problem including expected versus actual behavior**:

When I'm creating an index, I'm looking at the cat indices path with `http;//localhost:9200/_cat/indices/<indexes>` for the store.size which the index takes, and it's always takes only 324 bytes, thought after 10 seconds approximately the store.size is updated to the real storage size of the index.

I tried to `flush` the index, I tried to `forcemerge` the index and to `refresh` the index. nothing changed. The `store.size` only gets updated only after 10 seconds, no matter what.
Not only that, the `_stats` path of the index (`http;//localhost:9200/<indexes>/_stats`) also show the wrong storage size (in the `store` key).

Maybe important note: this index created from a template.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create index, something like:

```
curl -XPUT http://127.0.0.1:9200/<index_name>
```

 2. Insert some documents into the index, something around 35 documents in our case.

 3. Try to request the indices cat output:

```curl -XGET http://localhost:9200/_cat/indices/<indexes>```

**Provide logs (if relevant)**:

**Comment by andrershov** [comment]
Thanks very much for your interest in Elasticsearch.

Elasticsearch caches store size and performs refresh
each index.store.stats_refresh_interval, which is exactly 10 seconds
by default. Consider changing this setting.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by YuvalPruss** [comment]
Thanks for the answer @andrershov !
There is an REST request I can perform to refresh the stats by myself?
