### ISSUE TITLE
SQL: incorrect error message when the field name is used as projection and not being specified in the GROUP BY

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36321]
`SELECT YEAR(date), date FROM test GROUP BY YEAR(date);`

will throw an error (which is expected, since the field is not used in the grouping), but rather incorrect one (should refer to `date` as not being in the `GROUP BY` list):

```
sql> SELECT YEAR(date), date FROM test GROUP BY YEAR(date);
Server error [Server encountered an error [Cannot find group [date]]. [SqlIllegalArgumentException[Cannot find group [date]]
        at org.elasticsearch.xpack.sql.util.Check.notNull(Check.java:36)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:353)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:196)
```

**Comment by matriv** [comment]
This issue is fixed as currently the error returned is: 
```
line 1:26: Cannot use non-grouped column [birth_date], expected [YEAR(birth_date [Z])]
```

Should we improve that? Maybe the `expected` part is confusing as the expression is already in the select.

**Comment by matriv** [comment]
Closing this, There is no exception thrown, but an error message as mentioned in the previous comment. @astefan feel free to reopen if you think the error message should be improved.
