### ISSUE TITLE
Allow use partial name placeholder in dynamic mapping

### ISSUE THREAD

**Issue by exe-dealer** [elastic/elasticsearch#36337]
I have a convention that localized fields should have locale suffix like `name_ru` `name_kk` `name_en` and I want them be searchable by single field `name_i18n`. This can be achieved by `copy_to` mapping option

```json
{
  "mappings": {
    "_doc": {
      "properties": {
        "name_ru": { "type": "keyword", "copy_to": "name_i18n" },
        "name_kk": { "type": "keyword", "copy_to": "name_i18n" },
        "name_en": { "type": "keyword", "copy_to": "name_i18n" },
        "name_i18n": { "type": "text" }
      }
    }
  }
}
```

But I cant know all the possible fields ahead, I just have a convention. So I need this mapping to be dynamic and I need to extract the `name` part from `name_ru` to use it for `copy_to` . I think this feature can be designed in the following way 

```json
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [{
        "i18n": {
          "match": "*_i18n",
          "mapping": {
            "type": "text"
          }
        }
      }, {
        "rukken": {
          "match": ".*_(ru|kk|en)$",
          "match_pattern": "regex",
          "mapping": {
            "type": "keyword",
            "copy_to": "{name/(.*)_(?:ru|kk|en)$}_i18n" // here it is
          }
        }
      }]
    }
  }
}
```

I suggest to implement regex-based placeholder like `{name/REGEX}`. Regex should execute against field name, and placeholder should resolve to first captured group. Now I have to use elasticsearch fork with hardcoded {name-3} placeholder which just trims last 3 chars from field name

**Comment by exe-dealer** [comment]
Is it possible to implement this logic as plugin?

**Comment by mayya-sharipova** [comment]
Adding `team-discuss` label to see if we want to implement it on the Elasticsearch level.

**Comment by mayya-sharipova** [comment]
We have an initial discussion on this issue in our meeting.
While we encourage the usage of the `copy_to` parameter, we would not like to have a regex here. This use case looks to be very specific (e.g. first captured group).

One thing we have considered is to implement several hierarchical conditions under a single match, something like this:

```js
{
  "match_pattern": "regex",
  "match": {
    "pattern": ".*_(ru|kk|en)$",
    "match": [
      {
        "pattern": "xxx_(ru|kk|en)$",
        "mapping": {
          "copy_to": "xxx_i18n"
        }
      },
      {
        "pattern": "yyy_(ru|kk|en)$",
        "mapping": {
          "copy_to": "yyy_i18n"
        }
      }
    ]
  }
}
```
We still need to evaluate if it is worth implementing it  (if it relatively easy to implement).

**Comment by exe-dealer** [comment]
I figured out how to implement this logic as mapper plugin and avoid elasticsearch forking, so this issue is not so actual for me as it was.

**Comment by javanna** [comment]
Thanks for getting back to us. I would tend to close this issue given that you found a way to implement it and we got no other requests around this. Please leave comments if you think we should reconsider.
