### ISSUE TITLE
Elasticsearch logs don't contain a timezone

### ISSUE THREAD

**Issue by wyukawa** [elastic/elasticsearch#36347]
**Describe the feature**:
Elasticsearch logs don't contain a timezone.
```
[2018-12-07T14:04:49,200][INFO ][o.e.c.m.MetaDataIndexTemplateService] [SOMEHOST] adding template [kibana_index_template:.kibana] for index patterns [.kibana]
```
If you use a filebeat easticsearch module and collect elasticsearch logs, you can't see a log in kibana log ui at local time.
https://www.elastic.co/guide/en/beats/filebeat/6.5/filebeat-module-elasticsearch.html

If you want to see a log at local time, you need to use date processor.
https://www.elastic.co/guide/en/elasticsearch/reference/master/date-processor.html

I think it's better to add timezone to elasticsearch logs as the default setting like this.
```
[2018-12-07T14:04:49,200 +0900][INFO ][o.e.c.m.MetaDataIndexTemplateService] [SOMEHOST] adding template [kibana_index_template:.kibana] for index patterns [.kibana]
```

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.1

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
CentOS 7.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Elasticsearch uses Log4j2 as its logging framework and logging is configured in `config/log4j2.properties`. If you want to include the timezone in your Elasticsearch log output you are free to customize the out-of-the-box configuration that comes with Elasticsearch. For more details please refer to the [Log4j2 PatternLayout docs](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout).
