### ISSUE TITLE
Tag v6.5.2 is missing

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#36348]
For various tools and automated testing, we rely on github release tags (e.g. `v6.5.2`) , but one is missing for 6.5.2

**Comment by colings86** [comment]
Thanks for raising this @synhershko. I've added the tag now, see: https://github.com/elastic/elasticsearch/tree/v6.5.2

**Comment by synhershko** [comment]
Thanks @colings86 !

**Comment by synhershko** [comment]
@colings86 happened again for 6.5.4 :)

**Comment by colings86** [comment]
@synhershko looks like it has since been added: https://github.com/elastic/elasticsearch/tree/v6.5.4
