### ISSUE TITLE
[Docs] Document SAML integration with ADFS

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#36352]
It would be helpful to have some documentation around the specifics of SAML integration with ADFS, as per this discuss post: https://discuss.elastic.co/t/saml-authentication-error/150522

**Comment by jkakavas** [comment]
I don't know how I feel about this. SAML can be frustrating to configure, I give them that. However, I don't know what part of this Discuss thread is ADFS specific. They had configured their IDP (ADFS) to release one SAML NameID format and their SP (Elasticsearch) to wait for another. This could have happened for any combination of SAML IdP and SAML SP. 
Assuming that this is the same customer that thinks our blog post makes SAML configuration look too easy when it's actually not, well `It depends` :). In some cases it's as simple as it's presented to be there. For all other cases, @tvernum has done a great job documenting all knobs, switches, and more in the [SAML Guide](https://www.elastic.co/guide/en/elastic-stack-overview/6.5/saml-guide.html) which is supposed to be the source of truth for the  SAML realm configuration.

- Were they aware of the SAML Guide ? 
- Had they actually ready it?
- Was there a specific question they had after reading it or that wasn't covered in there?


Even if this was an ADFS specific thing, we have discussed a couple of times the possibility to add IdP specific instructions for SAML and I'm still rather reluctant to do so for a couple of reasons:

1. Where do we stop ? ADFS ? Auth0 and Okta ? Ping ? more ?
1. This will only be helpful if it is maintained regularly. IdPs make updates also, change configurations, defaults etc. If we host outdated instructions, it will probably do more harm than good. 
1. I think this will give out the impression that we "support" this configuration and I fear that support will start getting requests to support ADFS too.

**Comment by sscarduzio** [comment]
Did anyone eventually write that blog post?

**Comment by debadair** [comment]
Closing as fixed/won't fix in the docs.
