### ISSUE TITLE
Debian apt release file missing again?

### ISSUE THREAD

**Issue by cybert79** [elastic/elasticsearch#36356]
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.be.debian.org/debian stretch InRelease
Hit:3 http://ftp.be.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.be.debian.org/debian stretch Release
Ign:5 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Err:6 https://artifacts.elastic.co/packages/6.x/apt stable Release

Reading package lists... Done
E: The repository 'https://artifacts.elastic.co/packages/6.x/apt stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by rjernst** [comment]
Since this does not reproduce I'm going to close. In the future please first post questions like this on the [forums](https://discuss.elastic.co). There's an active community there that should be able to help.

**Comment by andybr0** [comment]
I fixed this issue by modifying apt proxy conf :

Acquire::https::Proxy "https://ip:port";

to 

Acquire::https::Proxy "http://ip:port";

Hope it helps
