### ISSUE TITLE
Geohash Grid Aggregation - Option to Return Latitude/Longitude Bounding Box

### ISSUE THREAD

**Issue by doc987** [elastic/elasticsearch#36413]
The geohash_grid bucket aggregation (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html) returns the geohash as the "key" property.  It would be nice if there was an option to get equivalent latitude and longitude bounding box (GeoJSON bounding box is [west,south,east,north] https://tools.ietf.org/html/rfc7946#section-5) either in addition, or as a replacement for the hash.

Note that the bounding box mentioned here is the the same box as the geohash, which is not necessarily the same as computing the minimum bounding box of the data in that Geohash using the geo_bounds aggregation.

**Comment by imotov** [comment]
@doc987 could you describe the use case for this bounding box?

**Comment by Destroy666x** [comment]
Mostly a QoL change - getting it instantly rather than having to use another library to decode the geohash. And why would you get it? To use it for Google Maps Javascript API, for example, it has functions to pan to or fit bounding box while hash doesn't matter.

**Comment by imotov** [comment]
I see, so basically use outside of Elasticsearch DSL (which already supports using geohashes, returned by aggs for for filtering).

**Comment by doc987** [comment]
Agree.
