### ISSUE TITLE
minimum_wire_compatibility_version

### ISSUE THREAD

**Issue by panchen66** [elastic/elasticsearch#36419]
Excuse me , see on localhost:9200，"minimum_wire_compatibility_version" : "5.6.0" ,it means The minimum version of the client is 5.6.0 ？ i use transport/elasticsearch/transport-netty4-client 5.6.13 jar to connect 6.5.2 elastic server is failed. the error is "org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{fr2uK0OpS0yBigqnUrRzqw}{127.0.0.1}{127.0.0.1:9300}]" ,then elastic server is no logs?

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
