### ISSUE TITLE
Bitset as datatype

### ISSUE THREAD

**Issue by aananthagovindarajan** [elastic/elasticsearch#36420]
Do we have any plans to support bitset as datatype which redis do. Since lucene already have its own implementation of [roaringbitmap](https://www.elastic.co/blog/frame-of-reference-and-roaring-bitmaps) additionally if you people expose as a datatype it will really helpful for 

1.  Some [advance analytics](https://amplitude.com/blog/2016/01/14/measuring-active-users). 
2. The current implementation of TermsAggregation is not the accurate one. If we have a roaring bitmap implementation for numeric fields(including long) then the bitmap containing the all unique terms can be transferred to another shard by this way accuracy can be achieved.

**Comment by not-napoleon** [comment]
Hello @aananthagovindarajan.  We discussed this in Fixit Friday on 2018-12-14, and don't feel that a bitset field makes sense right now.  The use cases described in the linked article are primarily analytics use cases.  What you're talking about sounds more like a bitset per shard, not per document (which is what a datatype mapping would suggest).

That said, the frequency analysis type aggregations described (e.g. how many users took an action twice in a week) are worth talking about in more detail.  I think you could get at some of those with existing aggregations, but it's not straight forward, and I don't know if the performance would be acceptable on large data sets.

I'm going to close this issue, but I encourage you to open an issue focused specifically on the "advanced analytics" you'd like to do, and we can discuss that with the analytics team.  Please focus on the types of queries and reports you'd like to run, not the specific implementation.

Thanks!
