### ISSUE TITLE
FeatureRequest: Should XContentBuilder support java.sql.Timestamp?

### ISSUE THREAD

**Issue by bringyou** [elastic/elasticsearch#36424]
`java.sql.Timestamp` extends `java.util.Date`, and `java.util.Date` is built-in supported by `XContentBuilder`, but since `XContentBuilder` get writers from it's static map, we can't use that wirter to support `java.sql.Timestamp`, neither do `java.sql.Date`.

> private void unknownValue(Object value, boolean ensureNoSelfReferences) throws IOException {
        if (value == null) {
            nullValue();
            return;
        }
        Writer writer = WRITERS.get(value.getClass());
       // ...
}

Should `XContentBuilder` support all subclasses of `java.util.Date`, or more broadly, should all built-in writers in  `XContentBuilder` support their subclasses?

**Comment by rjernst** [comment]
I'm not sure XContentBuilder should support java.util.Date at all. This is a legacy class, and we have been migrating all of elasticsearch to use the Java 8 Time api. But these can also be plugged in already via SPI with `XContentBuilderExtension`.

**Comment by bringyou** [comment]
I'm sorry that I didn't make it clearly. I was using `QueryBuilders.rangeQuery` to build searchRequest for `RestHighLevelClient`,  just like this code:
`boolQuery().filter(rangeQuery("created").lt(aTimestampValue))`
but I had to parse my value from `java.sql.Timestamp` to `String` or `ZonedDateTime`, if not, I'll get a exception like this

> java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.sql.Timestamp

After debugging, I found that queries were parsed by `XContentBuilder`, and it has built-in support for `java.util.Date`, the superclass of `java.sql.Timestamp`, in his static statement:
```java
static {
        Map<Class<?>, Writer> writers = new HashMap<>();
        writers.put(Date.class, XContentBuilder::timeValue);
        writers.put(Calendar.class, XContentBuilder::timeValue);
        writers.put(GregorianCalendar.class, XContentBuilder::timeValue);
}
```
 So I wonder if there is any possible that writers in `XContentBuilder` can support subclasses, just like the case of `java.sql.Timestamp` and `java.util.Date`?

**Comment by rjernst** [comment]
Supporting subclasses can't work generically. Serialization has to know and support the exact type, or there could be data loss. If subclasses of java.util.Date were serialized to date, they would be deserialized back into Date, not sql.Timestamp.

Why do you have a java.sql.Timestamp in the first place?

**Comment by bringyou** [comment]
@rjernst That's true, I didn't realize that, so forgive my ignorance. BTW, we used to accept timestamp as api parameter and pass them to mysql for query,  so api paramenter can not be changed even though we migrate to es.
