### ISSUE TITLE
[Docs] Scripting languages other than Painless are no longer supported

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#36430]
The documentation on [Watcher Script Condition](https://www.elastic.co/guide/en/elastic-stack-overview/6.5/condition-script.html) still mentions the possibility of using different scripting languages in a number of places. As of Version 6.0, however, [Painless is the only supported scripting language](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_scripting_changes.html).

**Comment by rjernst** [comment]
Painless is the only scripting language provided in Elasticsearch, but that does not mean it is the only one support. For other scripts contexts, `expression` scripts may be used. And in any script context, a custom script engine may be used (ie what used to be called "native" scripts).

I'm going to close this as I do not think there is anything to update.
