### ISSUE TITLE
SQL: CLI returns Intervals in ISO instead of SQL format

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#36432]
The CLI doesn't parse the given strings, rather returns them as they are which, for intervals, means the internal format (ISO) is used instead of the desired one (SQL).
The formatting code gets called however since the strings are not parsed, they don't match either as date or interval.

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/7507af29fa0ae8569e3551d7815fc55afe5af014
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/e80c5f3d6b28c2f78f8194a29e4e8a2122867cfd
