### ISSUE TITLE
Error using two synonym file filters with overlapping tokens in same chain

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#36433]
This was originally reported in https://discuss.elastic.co/t/invalid-synonym-rule-when-using-two-files/158603 and I think its worth discussing
whether it is a bug or at least an unexpected behaviour that we could try tackling in a future enhancement.

The situation is as follows: two distinct, e.g. language specific synonym files are used, like in the discuss issue.

`en_synonyms file` :
```
cereal, semolina, wheat
```
`fr_synonyms file `:
```
ble, cereale, wheat
```

Now, using those in separate synonym filters like so:
```
PUT test_index
{
  "mappings": {
    "wheat": {
      "properties": {
        "description": {
          "type": "text",
          "fields": {
            "synonyms": {
              "type": "text",
              "analyzer": "syn_text"
            },
            "keyword": {
             "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  },
  "settings": {
    "number_of_shards": 1,
    "analysis": {
      "filter": {
        "en_synonyms": {
          "type": "synonym",
          "tokenizer": "keyword",
          "synonyms_path" : "en_synonyms.txt"
        },
        "fr_synonyms": {
          "type": "synonym",
          "tokenizer": "keyword",
          "synonyms_path" : "fr_synonyms.txt"
        }
      },
      "analyzer": {
        "syn_text": {
          "tokenizer": "standard",
          "filter": ["lowercase", "en_synonyms", "fr_synonyms" ]
        }
      }
    }
  }
}
```

Results in the following error:
```
"type": "illegal_argument_exception",
    "reason": "failed to build synonyms",
    "caused_by": {
      "type": "parse_exception",
      "reason": "Invalid synonym rule at line 1",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "term: wheat analyzed to a token (cereal) with position increment != 1 (got: 0)"
      }
    }
```

The same works with in-place `synonyms` definition, also when the two files are simply concatenated into one and only one filter is used.
There might be reasons for this behaviour in which case we might want to document it better, but at least to me the behaviour is irritating.

**Comment by jimczi** [comment]
>  I think its worth discussing
whether it is a bug or at least an unexpected behaviour that we could try tackling in a future enhancement.

This is partially fixed by https://github.com/elastic/elasticsearch/pull/34331 which accepts this configuration in master. However I wonder if we should not throw an explicit error instead. The fix in master is to ignore the preceding synonym filters when we build the synonyms so this works in some cases (single term synonyms) but could lead to strange behavior in others (multi term synonyms, double expansion, ...). It should not be difficult to merge two synonym files together (we accept duplicates in the input) so it would be more consistent to rely on a single synonym filter per analyzer. 
@romseygeek WDYT ?

**Comment by romseygeek** [comment]
I allowed this specifically in #34331 following some discussion on the mailing list about synonyms.  One of future paths I'd like to take is to allow the synonym filter to apply a type name other than `SYNONYM` to its emitted tokens.  You could have one synonym filter that applies 'exact' synonyms, and then one that applies hypo- or hypernyms instead, and you can then boost the resulting terms differently in the query builder.  This requires that we allow multiple synonym filters to be chained, and that they are independent.

**Comment by jimczi** [comment]
Ok this makes sense, thanks for explaining @romseygeek . Can we close this issue then ?

**Comment by cbuescher** [comment]
@romseygeek @jimczi thanks for the explanation, if its already in the pipeline for the next minor I'm happy to close. Just opened this to track the question in the discuss issue.
