### ISSUE TITLE
SQL: Move ODBC docs into the main SQL repo

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#36436]
For consistency, the ODBC docs should be moved inside the SQL ones potentially rearrange them slightly.

/cc @debadair

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/0b1cb5300ed88119b9098335db5e2cee6fa29f0f
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/ab90cc57743bd7207a98c18e6acddecb497791f0
6.6 (6.6.0): https://github.com/elastic/elasticsearch/commit/66b6558207e9b5182883f2e8278b6fba144b42d7
