### ISSUE TITLE
Customize primary key _id has a bug

### ISSUE THREAD

**Issue by Crab2died** [elastic/elasticsearch#36463]
When I use the Customize _id like "67co3sPYTAqpbHjH-NGixw.oTdjHXGxQParPjh9f1YxZA", the key has a **dot(.)** concat with 2 Strings , insert index is ok, but when I use the GET api `GET my-index/my-type/67co3sPYTAqpbHjH-NGixw.oTdjHXGxQParPjh9f1YxZA` to query the record with _id,
the result is(I am sure the record is exist)
```
{
  "_index": "my-index",
  "_type": "my-type",
  "_id": "67co3sPYTAqpbHjH-NGixw.oTdjHXGxQParPjh9f1YxZA",
  "found": false
}
```
ES version 6.3.1

**Comment by Crab2died** [comment]
I doubt that is routing key , I upsert the record routing key is first half of the **dot(.)** ( 67co3sPYTAqpbHjH-NGixw), and I'm call the GET api use the default routing key

**Comment by matriv** [comment]
Are you sure that the index is refreshed?
You can refresh with `POST my-index/_refresh` and check again.

**Comment by lwjli** [comment]
> I doubt that is routing key , I upsert the record routing key is first half of the **dot(.)** ( 67co3sPYTAqpbHjH-NGixw), and I'm call the GET api use the default routing key.

If you index with the routing key, then get with identical routing key (or you will not find it), and search with identical routing key (for faster response from single shard).

**Comment by matriv** [comment]
@Crab2died I tried to reproduce this but I can get the document:
```
curl -H 'Content-Type: application/json' -XGET localhost:9200/my_index/my_type/67co3sPYTAqpbHjH-NGixw.oTdjHXGxQParPjh9f1YxZA
{"_index":"my_index","_type":"my_type","_id":"67co3sPYTAqpbHjH-NGixw.oTdjHXGxQParPjh9f1YxZA","_version":1,"found":true,"_source":
{
"text": "My document"
}
}
```

**Comment by matriv** [comment]
@Crab2died You're welcome.
I'm closing it then. Feel free to re-open if there is still an issue.

**Comment by matriv** [comment]
@Crab2died You're welcome.
I'm closing it then. Feel free to re-open if there is still an issue.
