### ISSUE TITLE
SQL: the assertions being made for float and double numbers in the test SQL infra have a too big delta

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36483]
The assertions we make for floating numbers [here](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/JdbcAssert.java#L223) have a delta that's too big for some tests, especially the `SCORE()` function tests like [this one](https://github.com/elastic/elasticsearch/blob/6fbc166afd75776363ebba897fcf032ce8a9d999/x-pack/plugin/sql/qa/src/main/resources/docs.csv-spec#L712) where a 1.0d/f rounding is significant.

**Comment by TomasNovo** [comment]
I will have a lock at this one

**Comment by astefan** [comment]
@TomasNovo we really appreciate your interest in this bug fix, but this one kind of stalls another PR. As such, a PR is already up for review.

**Comment by astefan** [comment]
CC @javanna

**Comment by javanna** [comment]
thanks a lot @astefan !

**Comment by astefan** [comment]
Master (7.0.0): https://github.com/elastic/elasticsearch/commit/1270d85ae19b9405b3949ab17d4a50b02c96ea77
6.x (6.6.0): https://github.com/elastic/elasticsearch/commit/eeedcf6b3042103e38516db95815908f7d33dd85
