### ISSUE TITLE
Document that cluster must have 1+ ingest nodes for monitoring to work

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#36508]
Based on https://discuss.elastic.co/t/no-monitoring-data-collected/160348/:

For Monitoring to work, at least one of the nodes in the Monitoring cluster must be an Ingest node. Otherwise, users will see an error like this in their Elasticsearch logs:

> Caused by: java.lang.IllegalStateException: There are no ingest nodes in this cluster, unable to forward request to an ingest node.

We should document this requirement for Monitoring in the appropriate place(s), even though by default all ES nodes are Ingest nodes.

**Comment by jakelandis** [comment]
I believe that this is documented here: https://www.elastic.co/guide/en/elasticsearch/reference/master/es-monitoring-exporters.html#es-monitoring-templates

> Beginning in 6.0, the ingest pipeline feature is a requirement on the monitoring cluster; you must have node.ingest enabled on at least one node.

Are there other places this should be documented ?

**Comment by lcawl** [comment]
We've added it to the following pages as well:
https://www.elastic.co/guide/en/kibana/master/monitoring-metricbeat.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/configuring-metricbeat.html
