### ISSUE TITLE
Pagerduty Integration Not accepting default_account

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#36512]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

Setting up the Pagerduty integration using dynamic settings and it appears that the `default_account` setting isn't working correctly.

```
PUT _cluster/settings
{
  "persistent": {
    "xpack": {
      "notification": {
        "pagerduty": {
          "default_account": "watcher-default"
          
        }
      }
    }
  }
}
```

Then When you try to send to a to an account that doesn't exists:
```
  "actions": {
     "notify-pagerduty": {
        "throttle_period": "5m",
        "pagerduty": {
            "account": "elasticsearchzzz-logs",
            "description": "STG - Force Merge Hasn't Run in 6 Hours"
        }
    }
```
This results in a different account being notified other then the default_account defined.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
