### ISSUE TITLE
SQL: Move away from TimeZone to ZoneId

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#36536]
Currently, SQL uses internally `TimeZone` however with the move to `java.time` we're now dealing with both `TimeZone` and `ZoneId`. To whatever extent possible, we should move to the latter for consistency.

**Comment by spinscale** [comment]
just for the record: There is `TimeZone.toZoneId()`, that might ease transition at some points

**Comment by costin** [comment]
Right except there are some gotchas with ZoneId vs ZoneOffset which I think might be a better candidate.
`TimeZone` for "Z", "UTC" and "GMT" always returns a `ZoneId` not `ZoneOffset.Z` which causes the `ZonedDateTime.toString()` to not be ISO compliant which is unexpected especially when moving away from Joda.

**Comment by spinscale** [comment]
you could try with `ZoneId.normalized()`

**Comment by costin** [comment]
Danke, that will come handy.

**Comment by costin** [comment]
Closed by 59d2525 and b376edf
