### ISSUE TITLE
_cat API "size" params doesn't take effect

### ISSUE THREAD

**Issue by LoadingZhang** [elastic/elasticsearch#36533]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**JVM version** (`java -version`): 1.8.181

**OS version** (`uname -a` if on a Unix-like system): CentOS 7.3

**Description of the problem including expected versus actual behavior**:

I access "_cat/indices?h=*&size=k", but es return accurate number of count not take unit.
Did  I use these params in wrong way?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
