### ISSUE TITLE
RPM package does not list "java" as a dependency

### ISSUE THREAD

**Issue by chmarr** [elastic/elasticsearch#36568]
**Elasticsearch version** (`bin/elasticsearch --version`):
```
Version: 6.4.3, Build: default/rpm/fe40335/2018-10-30T23:17:19.084789Z, JVM: 1.8.0_192
Version: 6.5.3, Build: default/rpm/159a78a/2018-12-06T20:11:28.826501Z, JVM: 1.8.0_192
```

**Plugins installed**: Not relevant

**JVM version**: Not relevant

**OS version**: Not relevant

**Description of the problem including expected versus actual behavior**:

The elasticsearch RPM package does not have a "Requires" dependency on java. If java is not installed, but being installed in a single transaction, rpm does not know how to order those two and thus may attempt to install elasticsearch before java is installed and ready.

This results in a failure in the PREINST scripts which check for the presence of the java binary. Simply attempting a re-install after java was installed clears the issue, but does complicate automated installations.

**Steps to reproduce**:

Don't have java installed. Attempt to install the elasticsearch RPM using `rpm` or `yum` along with the java package in one command. This *may* trigger the issue, but might not, as it's dependent on the way rpm decides to order those. Installing those two along with a heap of other packages *may* help trigger it.

**Suggested fix**

Add "java", or "jre" to the `Requires` list in the RPM spec file. If it must be "Java 8", then use "java-1.8.0" or "jre-1.8.0". Those capabilities are given in the "Provides" section of both Oracle java RPMs and OpenJDK RPMs.

**Provide logs (if relevant)**: Not relevant

**Comment by jasontedor** [comment]
Thanks for your interest, and sorry for the trouble. We do recognize this is a problem and are still exploring how we are going to solve this. It turns out that this issue is already being considered under #31845. Would it be that you could join us there?
