### ISSUE TITLE
Add reverse nested query

### ISSUE THREAD

**Issue by Derya** [elastic/elasticsearch#36576]
There doesn't seem to be a way to break out of the nesting level in a query definition that's being defined in a filter aggregation. Normally we'd never need a reverse nested query, since any actual references to fields happen at the end of our query when all the compound/joining stuff is done. But if I'm filtering some nested documents, how can I filter on the parent document's properties? As a simple example of where I'd need to use this:

```
{
  "aggs": {
    "OP0_nest": {
      "nested": { "path": "events" },
      "aggs": {
        "OP0_custom_filter": {
          "filter": {
            "bool": {
              "should": [
                { "term": { "events.color": "orange" } },
                { "term": { "customer_id": 35 } }
              ]
            }
          },
          "aggs": {
            "OP0_op": {
              "avg": { "field": "events.coord_y" }
            }
          }
        }
      }
    }
  }
}
```

This query doesn't work, because that `customer_id` term that wants to reference the parent doc is not allowed. But, if we had a way to break out and refer back to it, this would be easy to solve.

**Comment by Derya** [comment]
Actually I thought about this a bit more and I feel like this must not be such a rare use case. Even if this were in the `query` clause instead of in `aggs`, there are other more complicated kinds of queries that might want to reference parent fields further down the tree... Is there some other way to accomplish this?

**Comment by cbuescher** [comment]
@Derya while discussing this issue I found and old issue (https://github.com/elastic/elasticsearch/issues/16380) that looks like it discusses the same topic. https://github.com/elastic/elasticsearch/issues/16380#issuecomment-183760673 suggests copying the data you want to filter on from the parent document to the nested docs. Since nested aggregations are already complex as is we'd like to propose this instead of adding another feature. I hope you don't mind me closing this issue. Please let us know if this doesn't help with your use case.

**Comment by Derya** [comment]
I considered doing just that, actually. Including the top level data I needed in the nested documents would of course solve the problem but it's not feasible in this case unfortunately. Compared to other cases where we might have just flattened the structure, there's just a lot of different stuff at the top level and also on average an awful lot of entries in the nested level per top level entry. So I think even if it were possible, it may not have been desirable to begin with. Though I suppose if I had no other choice, it's be worth performance testing.

The reason it is not feasible in this case is that my mapping is for an Elassandra index, and the realities of how the underlying Cassandra table needs to be updated preclude a flattened structure.

Ultimately we just can't do queries that involve OR, NOR, etc those two levels. We can still make AND queries just by filtering twice at two different levels in the aggregation, so that's a plus at least, but other than that I wasn't really able to work around this problem in any other way.

**Comment by cbuescher** [comment]
Thanks for the clarification and I'm sorry to hear that copying the information in your case isn't feasible. Its good to hear this in case asks for a kind of "reverse nested query" get more frequent. I'm not sure a solution with the current datastructures in Lucene would be possible, at least not in a trivial way, but if there are more cases like this in the future it is certainly worth digging a little deeper.
