### ISSUE TITLE
SQL:: Unable To Aggregate and Like in statement

### ISSUE THREAD

**Issue by Johnb21** [elastic/elasticsearch#36572]
Elasticsearch 6.5

I am trying to use the SQL Component with a pretty basic query that uses a combination of a SUM aggregate function and a LIKE filter.

```
SELECT SUM(amount) as total_amount
FROM res
WHERE id = '1234'
AND description LIKE '%desc'

```

If i remove the aggregate, I get each line item with no errors. This tells me the `LIKE` is working properly. The same is true removing the LIKE filter and running it with just the SUM aggregate. It works.

When I use both like the query above, I get the following error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Cannot evaluate script for expression LikePattern[%desc,\u0000]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Cannot evaluate script for expression LikePattern[%desc,\u0000]"
  },
  "status": 500
}
```

**Comment by tpcred** [comment]
I'll try to tackle this one.

**Comment by astefan** [comment]
@Johnb21 thank you for the report, but this was already reported before [here](https://github.com/elastic/elasticsearch/issues/36161). Closing as a duplicate.
