### ISSUE TITLE
Should we note the versions that you can connect to for remote clusters?

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#36589]
At the moment the documentation on [remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/modules-remote-clusters.html#remote-cluster-settings) does not contain any information on the version restrictions for the remote clusters. Should we add a note to the page that describes that for a local cluster on `N.latest` you can connect to a remote clusters on version `N-1.latest` and `N+1.latest`?

**Comment by bleskes** [comment]
We discussed it on fix it friday. It is a great point that we need to get a clearer story documented. That said, the remote cluster infra is not the right level for it. CCS has a totally different story than CCR (where lucene file may be copied). We will open up a CCS specific issue. The CCR BWC aspect is still in the works and is covered by the CCR roadmap.
