### ISSUE TITLE
Aggregation Pagination Composite VS Include Partion

### ISSUE THREAD

**Issue by gary-harpaz** [elastic/elasticsearch#36583]
Hi,

At my company we use a terms aggregation with include: partition number to paginate the results.
I noticed that in newer versions you have a composite aggregation which also allows pagination.
Which do you think is a better solution?
Is there a performance difference between the methods?

Thanks,

Gary

**Comment by tlrx** [comment]
Hi, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
