### ISSUE TITLE
Forcemerge operation failing to include second digit

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#36616]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**:

When executing a forcemerge operation it would appear that the check to see if it should proceed to the max_num_segments works, but the actual FM operation only includes the first digit. For example if you were to issue the cmd:

`POST nginx-2018.12.05.14.00-1/_forcemerge?max_num_segments=20` 

It would forcemerge each shard to 2 segments opposed to the defined 20. Obviously this causes a large amount of resource utilization. I have tested this against several indices and all show the same result.

Now if the index already had only 20 segments then this would return immediately. So I believe it is in the execution step.

**Steps to reproduce**:

 1. Create an index
 2. Get it to create 30 segments per shard
 3. Try to forcemerge the index down to 25 segments and it should actually reduce it to 2 per shard

**Comment by danielkasen** [comment]
Actually I think I am misreading these numbers. It would appear that it always tries to force merge down to 1. Did we remove the option to pass a number to this in the 6.5 release and not document it? This is causing a serious strain on our cluster.

**Comment by javanna** [comment]
> It would appear that it always tries to force merge down to 1. Did we remove the option to pass a number to this in the 6.5 release and not document it? This is causing a serious strain on our cluster.

Yes, that is the case, sorry for the very late reply, see #31689 .
