### ISSUE TITLE
ILM should support variables in rollover_alias

### ISSUE THREAD

**Issue by vbohata** [elastic/elasticsearch#36627]
I have checked the docs about ILM beta feature for ES 7 and found it is probably not possible to use some kind of variables in rollover_alias names.

For us it is a must have feature. We use index names like:
- machines1-winevent-security-filebeat-6.3.0-2018.12
- machines1-winevent-system-filebeat-6.3.0-2018.12

Indexing via logstash.

Index patterns are matching by "*-winevent-*-*-*-*". It is not possible to use a fixed rollover_alias name as we limit access to indexes by permissions. So it is not possible to rollover it to single index.

If not another way I propose to add support for some kind of variable matching or "wildcard selector" like:
rollover_alias: %1-%2-%3-%4-%5, where %1 matching the first *, %2 the second *, so totally matching "machines1-winevent-security-filebeat".

Btw. as it has to be bootstraped first is there any plan to add logstash support for rollover indexes or somehow doing autobootstrap in elasticsearch?

Probably auto-bootstrap would solve this problem easily as first write to nonexistent "machines1-winevent-security-filebeat-6.3.0" could create a new alias and index "machines1-winevent-security-filebeat-6.3.0-0001".

**Comment by fpompermaier** [comment]
From [documentation](https://www.elastic.co/guide/en/beats/filebeat/master/ilm.html#setup-ilm-rollover_alias-option) rollover_alias is by default filebeat-{agent.version} but if I set

setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat-{agent.version}"
setup.ilm.pattern: "{now/d}-000001"

the index name is not the expected one (i.e. filebeat-7.1.0-2019.05.21-000001) but the index is created with name filebeat-{agent.version}..is it a problem of the documentation or is it a bug?

**Comment by gwbrown** [comment]
@fpompermaier That is not an Elasticsearch issue, as Elasticsearch doesn't know what the `agent.version` is. Could you ask that question on the [Beats discussion forums](https://discuss.elastic.co/c/beats), or if you are confident that it's a bug, [open an issue on the Beats repo](https://github.com/elastic/beats/issues/new/choose)?

**Comment by fpompermaier** [comment]
Sorry for posting in the wrong place. I've opened an issue on the github repo at https://github.com/elastic/beats/issues/12233

**Comment by dakrone** [comment]
Closing this as with the introduction of data streams this has become far less necessary.

**Comment by fpompermaier** [comment]
Ok..but how do I migrate to data streams in an existing setup..?

**Comment by andreidan** [comment]
@fpompermaier the next minor release will come with a `migrate to datastream` API. More details are available [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-migrate-to-data-stream.html)

**Comment by fpompermaier** [comment]
Ok thanks

**Comment by Tommmster** [comment]
We have a use case regarding the use of `{index}` placeholder in the `rollover_alias` setting. We'll provide a PR in the upcoming days / weeks. From our point of view, using it for aliases but not for rollover is inconsistent if you consider the case of not using Data Streams (i.e being able to delete / write / update) documents to "older" backing indices.

**Comment by JahanviAcquia** [comment]
We also have a use case of using indices and not data streams as documents are not time base events. I need a mechanism to use rollover_alias. and allowing {index} with rollover alias will help us with multiple indices. This is required feature and very helpful one
