### ISSUE TITLE
SQL: stop sending JDBC type in the drivers protocol

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#36635]
For historical reasons, for the drivers protocol we send `jdbc_type` parameter which however is not used anywhere. Since each driver needs to do the mapping between the es type and their supported type, it seems unlikely it will used anytime soon.

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/659326fdd63097626a82d2f004a446482a042cd7
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/ac284e8c346c4eac5538068ff8506515ea20e396
