### ISSUE TITLE
Add API to download a binary field

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#36669]
Currently, the only way to get a binary field is to get a json response that contains binary field, encoded in base64.

This would be great to add an API which enables to download only a binary field.
A nice option would be to precise if content is encoded, decoded (from base64), or gziped.

Example API : 
`GET /index/type/id/binary_field?format=decoded`

And result is the content in binary_field, decoded.

This feature is particularly interesting for big binary fields, on the client side, to be able to stream the binary content to process it, store it in a file, or display it in a web application.

**Comment by imotov** [comment]
> Currently, the only way to get a binary field is to get a json response that contains binary field, encoded in base64.

You can also get it in [CBOR or SMILE](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_content_type_requirements) formats, which seems to be reacher in functionality and less prone to abuse. 

I would agree that having a single field as an output would be a bit easy to parse, but there are several issues with that including handling content type, simplifying usage of the server for delivering malicious content and other ways of abuse that makes me uneasy about implementing such feature.

**Comment by fbaligand** [comment]
Hi @imotov ,

Thanks for your answer and suggestion for CBOR/SMILE formats. As I see in documentation and upon my tests, it seems that these formats are only supported for indexing documents, and not for getting documents.
If I'm wrong, I'm very interested by a simple query example that gets a document with CBOR/SMILE format.

That said, concerning this issue : 
- for the content-type, an easy way to deal with that is to simply return `Content-Type: application/octet-stream` header. Then, it client's responsibility to know what content type is.
- an option for content-type, is to support a query parameter that specifies which field contains the content-type to return (this is optional). Particularly useful when binary is stored through ingest attachment plugin.
- concerning malicious content, I don't see a special server problem : the content is decoded (or not) and returned as it is. Given that content is not processed server-side, IMHO, it has no malicious impact on server.

**Comment by imotov** [comment]
> If I'm wrong, I'm very interested by a simple query example that gets a document with CBOR/SMILE format.

```
curl -XDELETE "http://localhost:9200/bintest?pretty"
curl -XPUT "http://localhost:9200/bintest?pretty" -H 'Content-Type: application/json' -d'{
  "mappings":{
    "_doc":{
      "_source": {
        "excludes": ["blob"]
      },
      "properties":{
        "blob":{
          "type":"binary",
          "store":"true"
        }
      }
    }
  }
}'
curl -XPUT "http://localhost:9200/bintest/_doc/1?pretty" -H 'Content-Type: application/json' -d'{
  "blob": "LS0tLT4gWWF5ISEhIEl0IFdvcmtzISEhIDwtLS0tLQo="
}'
echo "Test for CBOR using Accept header"
curl -XGET "http://localhost:9200/bintest/_doc/1?stored_fields=blob" -H 'Accept: application/cbor'
echo
echo "Test for SMILE using format parameter"
curl -XGET "http://localhost:9200/bintest/_doc/1?stored_fields=blob&format=SMILE"
```

**Comment by fbaligand** [comment]
Thanks for the example! Very instructive!
Nice to see that blob is not base64-encoded in CBOR and SMILE formats.

To go back to this issue, CBOR/SMILE formats are nice alternatives, but I find that having a direct download is helpful to simply get a binary content, without to deal with complex SMILE/CBOR formats, particularly to stream the binary content on the client side.

**Comment by imotov** [comment]
> particularly to stream the binary content on the client side.

I don't think elasticsearch would be a good solution for that. Please see https://github.com/elastic/elasticsearch/issues/25146#issuecomment-311330133 for a detailed explanation and related discussion. In this particular case, you might be better off storing large binary content outside of elasticsearch and delivering it using a specialized streaming server, while indexing only metadata for this content in elasticsearch.

I am concerned that having direct downloads could lure users into using elasticsearch for types of workloads that it was never designed for and cannot efficiently support at scale at the moment. It is not going to be a good user experience that we are striving for.

**Comment by fbaligand** [comment]
Well, I understand that Elasticsearch is not designed to be a binary datastore.
But it is designed to be a document datastore. And with official ingest-attachment-plugin, you can ingest a binary document to a Elasticsearch document, with both text content and binary content.
This is my concern for this issue.
And so, both to download binary content and full text content, an API to download one specific field is particularly useful.
 To speak about use case, you typically either get meta-data informations, or get binary content or get full text content. In real life, from an application, you never get meta-informations and binary content.
That's why I think this API would be very useful, finally both for binary fields and long text fields.

**Comment by imotov** [comment]
> To speak about use case, you typically either get meta-data informations, or get binary content or get full text content. In real life, from an application, you never get meta-informations and binary content.
That's why I think this API would be very useful, finally both for binary fields and long text fields.

I agree, in a typical search use case an application typically delivers one subset of fields for the result list and another subset of fields when a user navigates to a particular document. However, for the non-binary use case, this is handled by [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html) and [stored fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-stored-fields.html). Do you find this functionality inadequate for your needs?

**Comment by fbaligand** [comment]
For full text fields, this is sufficient for most needs. Then there some times where you just want content without any structure around (json, smile or cbor). 
A good example is X-Pack reporting in Kibana: when you download CSV file  from a report, you get it from an elasticsearch document. 
In that particular case, we just need to get csv content, without json structure around. And as Csv could be big, streaming is helpful

**Comment by jasontedor** [comment]
We discussed this during our weekly team discussion meeting and at this time we do not see a compelling enough reason to add APIs here. One note: you can get a gzipped response by sending the `Accept-Encoding` header indicating that the client wants `gzip`. It is also worth noting that it would be possible to add the APIs being requested here in a plugin.

**Comment by fbaligand** [comment]
Sad to hear that... :(
