### ISSUE TITLE
what units of redis.info.cpu.used.sys field

### ISSUE THREAD

**Issue by ypc123ypc** [elastic/elasticsearch#36690]
when i use metricbeat to monitor my redis server , i holp use cpu fields to complete my chart, but i don't know what the units of these cpu fields are.
![redis_cpu](https://user-images.githubusercontent.com/16789056/50069962-36dd2500-0207-11e9-9a0d-0f938bec3725.png)

**Comment by tvernum** [comment]
Hi @ypc123ypc, thanks for your interest in Elasticsearch and Beats.

This looks like a question about metricbeat, but Elastic reserves GitHub issues for tracking bugs and feature requests. For questions like these, could you please head over to our [discussion forum](https://discuss.elastic.co/c/beats/) where we can provide better support.

I'm going to close this ticket, but there's an active community on the forums, and I'm sure someone will be able to answer your question.

Thank you.
