### ISSUE TITLE
SQL: Change docs to describe function aliases consistently

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#36692]
Currently we have mixed approaches for function aliases. For some we list them normally as another function (e.g. NVL and ISNULL). For others we don't mention them at all, and for some we mention the aliases in the section describing the function with its primary name.

Let's decide on a consistent approach and make the appropriate changes.

**Comment by matriv** [comment]
After discussion we decided to list each alias separately when the name is quite different (example IF_NULL/NVL, or NOW/CURRENT_TIMESTAMP but keep the aliases in the format of `DAY_OF_WEEK/DAYOFWEEK/DOW` when the name aliases are without the underscores or just an abbreviation).

**Comment by astefan** [comment]
@matriv Ok to close this one?

**Comment by matriv** [comment]
Yes!
Changes have been made to satisfy our decision in #36918
