### ISSUE TITLE
[Docs] Explanation for the simple analyzer in the completion suggester as default seems outdated

### ISSUE THREAD

**Issue by svola** [elastic/elasticsearch#36715]
The documentation of the available mapping parameter for the type `completion` contains an outdated explanation. 
By reading this explanation a user could be mislead into thinking that the `standard` analyzer still uses the `_english_` stopword list by default. 

https://github.com/elastic/elasticsearch/blob/6.5/docs/reference/search/suggesters/completion-suggest.asciidoc#mapping

```
analyzer

The index analyzer to use, defaults to simple. In case you are wondering why we did not opt for the standard analyzer: We try to have easy to understand behavior here, and if you index the field content At the Drive-in, you will not get any suggestions for a, nor for d (the first non stopword).

```

It looks like the explanation why the `simple` analyzer is used instead of the `standard` analyzer is outdated. 
In Elasticsearch versions prior to 1.0 the `standard` analyzer used the `_english_` stopword list as default.  

https://www.elastic.co/guide/en/elasticsearch/reference/0.90/analysis-standard-analyzer.html

This was changed subsequently but the documentation for the completion suggester is still based on the old version. Now the standard analyzer uses an empty stopword list by default. 

https://www.elastic.co/guide/en/elasticsearch/reference/1.3/analysis-standard-analyzer.html

This part of the documentation was written 5 years ago, so it's pretty likely that it didn't get updated to reflect the implementation changes in the standard analyzer.

https://github.com/elastic/elasticsearch/blame/6.5/docs/reference/search/suggesters/completion-suggest.asciidoc#L50

**Comment by cbuescher** [comment]
@svola I think it makes sense to simply remove the explanation. Would that make sense? We still use "simple" as the default, but I don't think going into the details and explaining the historical reason for this choice makes sense. I opened #36720 to simply remove.

**Comment by svola** [comment]
Thanks @cbuescher!
Yes, I guess removing the explanation would be the easiest for now. 

The key message of the explanation is interesting though.
We could add a note later about the effect of a stopword filter in a completion context with a new example. 
That might be relevant for users who want to choose another analyzer.
