### ISSUE TITLE
Rename feature_vector to feature_map?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#36723]
With the new vector field (#33022), there is concern that users are going to be confused with `dense_vector`/`sparse_vector` on the one hand and `feature_vector` on the other hand, which share similar names even though they have nothing in common.

In the search meeting, we discussed renaming `feature_vector` to `feature_map` instead, which still nicely conveys the information that this is a multivalued version of the `feature` field but without introducing confusion with the `dense_vector` and `sparse_vector` fields.

We agreed to create an issue with the `discuss` label to get this idea validated by a wider audience in Fixit Thursday/Friday.

None of these fields are released yet so there is no concern around backward compatibility.

Thoughts?

**Comment by mayya-sharipova** [comment]
Inserting links here for: [feature](https://www.elastic.co/guide/en/elasticsearch/reference/master/feature.html) and [feature_vector](https://www.elastic.co/guide/en/elasticsearch/reference/master/feature-vector.html)

Ad also I was wondering if can call `feature_vector` just `features`? 
Another alternative is `rank_features` (this is how Vespa calls them).

**Comment by jpountz** [comment]
I like `rank_features`.
