### ISSUE TITLE
Shrink operation error message text "must be a" is doubled.

### ISSUE THREAD

**Issue by raulk89** [elastic/elasticsearch#36729]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.3

**Plugins installed**: [ingest-attachment]

**JVM version** (`java -version`): 1.8.0_191

**OS version** (`uname -a` if on a Unix-like system): 3.10.0-957.1.3.el7.x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

```
PUT my_source_index
{
    "settings": {
        "index.number_of_shards" : 4
    }
}

PUT /my_source_index/_settings
{
  "settings": {
    "index.routing.allocation.require._name": "dc1-etelastic", 
    "index.blocks.write": true 
  }
}

POST my_source_index/_shrink/my_target_index?copy_settings=true
{
  "settings": {
    "index.routing.allocation.require._name": null,
    "index.blocks.write": null,
    "index.number_of_shards": 3
  }
}
```

And the error is as follows, note that **"must be a"** is doubled.
> 
> "type": "illegal_argument_exception",
>     "reason": "the number of source shards [4] **must be a must be a** multiple of [3]"

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Thanks for the report @raulk89.
