### ISSUE TITLE
[CI] Two integration tests fail with timeout

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36759]
The test run in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/125/console has two integration test failures, in one of them a node waits 30 second a delete-index response that does not happen and in the other a index creation response is not acked.

Maybe there is more in the logs that I am not seeing, thus I am assigning this to the distributed team. I could not reproduce locally on osx or Linux, even with several test runs.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/125/console

Reproduction lines

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=192D893B4271B516 \
  -Dtests.class=org.elasticsearch.search.fetch.subphase.highlight.HighlighterSearchIT \
  -Dtests.method="testPostingsHighlighterNumberOfFragments" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt-MT \
  -Dtests.timezone=SystemV/AST4ADT \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=192D893B4271B516 \
  -Dtests.class=org.elasticsearch.action.bulk.BulkWithUpdatesIT \
  -Dtests.method="testThatInvalidIndexNamesShouldNotBreakCompleteBulkRequest" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv \
  -Dtests.timezone=SystemV/AST4 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Link to plain text logs https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/125/consoleText

**Comment by original-brownbear** [comment]
We also have this in the logs:

```
[ant:junit4] ERROR: JVM J0 ended with an exception: Forked process returned with error code: 137. Very likely a JVM crash.  See process stderr at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/server/build/testrun/integTest/temp/junit4-J0-20181218_041755_3389570922749597950294.syserr
	at com.carrotsearch.ant.tasks.junit4.JUnit4.executeSlave(JUnit4.java:1542)
	at com.carrotsearch.ant.tasks.junit4.JUnit4.access$000(JUnit4.java:123)
	at com.carrotsearch.ant.tasks.junit4.JUnit4$2.call(JUnit4.java:997)
	at com.carrotsearch.ant.tasks.junit4.JUnit4$2.call(JUnit4.java:994)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

`137` => we ran oom here => closing this since it's def. an infra issue. We had quite a few Gradle JVMs die on err `137` randomly+recently.
