### ISSUE TITLE
Specialize ValueCountAggregator depending on type of ValuesSource

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#36752]
The `value_count` aggregation uses the [`bytesValue()`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/ValueCountAggregator.java#L69) of its `ValuesSource`.  This is simple/convenient since all the different types implement it, and ValueCount doesn't need to specify what kind of ValuesSource it expects.

But the downside is that when `value_count` is counting up [float/doubles](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/fielddata/plain/AtomicDoubleFieldData.java#L57) or [longs](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/fielddata/plain/AtomicLongFieldData.java#L97) we are converting the numerics to Strings first.

This is [pretty slow](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java#L317), and creates a ton of temporary garbage due to all the string manipulation:

![image](https://user-images.githubusercontent.com/1224228/50130725-05874800-024d-11e9-8d83-6ad4135736bd.png)

Since `value_count` doesn't actually need the value, just the count of values in the field, it wouldn't be too difficult to specialize the aggregator so that slightly different versions are used for each type of ValuesSource.  Then it can call the appropriate method (`doubleValues()`, etc) and avoid all the string casting.

**Comment by amishra123** [comment]
hi there, I would like to work on this :).

**Comment by polyfractal** [comment]
@amishra123 sure, have at it :)

Fair warning, I only skimmed over the various parts of code when opening this issue, so it may be trickier than I thought once you get deep into the guts of it.

**Comment by talevy** [comment]
hi @amishra123, are you still interested in tackling this?

**Comment by xjtushilei** [comment]
I have encountered the same problem. 
The valuecount performance is too bad. 
Can I comment out this part of the code?  Especially to sort the array, etc.

**Comment by polyfractal** [comment]
Hi @xjtushilei, afraid it's not that easy :)  The data is actually already pre-sorted (most doc values are sorted when they are indexed, or if they are a single-valued field there is no sorting at all).  

There's not an easy/simple way to fix this, since we'll need specialized version for each data type.  Fetching the bytes value (and resulting string casting) is simple because it applies to all data types.  But to make it more efficient, we need the aggregator to create a specialized internal aggregator that knows how to use strings vs longs vs geo points, etc.

**Comment by polyfractal** [comment]
Ah, I see the sort you are referring to.  Yes, the purpose of this issue is to remove this sorting behavior, which I agree is unnecessary.  :)

It's a side effect of how the aggregation framework is structured, and not as simple as just removing the `sort()` though.  This part of the code is used by other aggregations which rely on the sorted behavior.  It isn't needed for `value_count`, but is needed for other aggs.

The reason this is happening is because `value_count` accepts any data type (`ValuesSourceType.ANY`).  The only method that all the different ValuesSources share is `bytesValue()`, which returns or converts the values into a byte representation.  For some fields (like strings) the data is already in a bytes format and no work is done.  Other fields like numerics are converted to strings first, which then needs to be re-sorted.  

Which is all redundant work for `value_count`.

So the purpose of this ticket is to introduce new, specialized forms of ValueCount for each data type.  These could be either distinct aggregators like how we do it with terms aggs (e.g. `LongValueCountAggregator`, `StringValueCountAggregator`, etc), or a specialized leaf collector inside the single aggregator.  In either case, these specializations would only work with a certain `ValuesSourceType`, and could thus call the "native" data access method (`longValues()`, `doubleValues()`) and avoid the need to fall back on the generic `bytesValue()` method.

I hope that helps!  The answer is basically: yes, the sorting and string conversion is totally unnecessary for `value_count`, but it'll take a little bit of work to change this behavior because of how the agg framework is structured.

**Comment by xjtushilei** [comment]
Thanks for your help. I will try it.

**Comment by xjtushilei** [comment]
https://github.com/elastic/elasticsearch/pull/54854  related

**Comment by nik9000** [comment]
Closed by #54854
