### ISSUE TITLE
Typeless index call can fail against an index with a custom type.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#36811]
Using the typeless index APIs can result in an error when the index contains a custom type name that is not `_doc`. The issue seems to arise when the index call introduces a mapping update.

The following gist demonstrates the problem: https://gist.github.com/jtibshirani/0929faf60bd78c794aeb01cc08d04c73.

The same issue also applies to typeless document update calls.

**Comment by jtibshirani** [comment]
@jpountz would you be able to look at this issue, as a continuation of #35790?

**Comment by benwtrent** [comment]
I ran into this same issue when calling a typeless `_reindex` against an index that had dynamically created fields. 

Recreation steps: https://gist.github.com/benwtrent/2e3ea1e87746f58f557898869fd95e77

**Comment by jpountz** [comment]
@jtibshirani Absolutely, I'm putting it on top of my TODO list.
