### ISSUE TITLE
[eng2] mapping type consistency 

### ISSUE THREAD

**Issue by mrklaney** [elastic/elasticsearch#36843]
Minor fix which is not exactly wrong conceptually, but slide 15 shows two different mapping types instead of just the (preferred) _doc.    It _is_ wrong in that the actually logserver* indices use _doc.   Could just be a typo.

<img width="764" alt="screen shot 2018-12-19 at 8 22 13 am" src="https://user-images.githubusercontent.com/1714853/50229296-3a87bd80-0367-11e9-9de4-8f29dc1cc131.png">
 
easy fix  to change to

<img width="742" alt="screen shot 2018-12-19 at 8 33 21 am" src="https://user-images.githubusercontent.com/1714853/50229953-c4845600-0368-11e9-95d3-d0d131b7b250.png">

**Comment by jasontedor** [comment]
Heya, I think this could go to another repository (you know which one). 😇
