### ISSUE TITLE
long field datatype accept double value 

### ISSUE THREAD

**Issue by liuxun666** [elastic/elasticsearch#36875]
**Elasticsearch version 6.2.4**
My  index has a  long datatype field,But when someone index a double value, ES still receives it.This value displays as long when using elasticsearch-head and other plugins to view it, but when I use Java client to get this value use getSourceAsMap() I get a double.And then I get a class error.Because such a small amount of data and data beyond my control have polluted the entire index, is there any way for me to reject these documents? plz.

**Comment by tvernum** [comment]
Hi @liuxun666, thank you for your interest in Elasticsearch.

Elastic uses GitHub for tracking bugs and clear feature requests, but this looks like a question.

Could you please ask questions such as these on our [discussion forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. There is an active community there who will be able to assist you in sorting this out.

In the mean time, you might want to read up on the [coerce](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/coerce.html) mapping parameter. 

Thank you.
