### ISSUE TITLE
[ML] Delayed data annotation - span whole bucket

### ISSUE THREAD

**Issue by pheyos** [elastic/elasticsearch#36888]
For a single missed document, the generated annotation has `start time` = `end time` (= `bucket start time`). The annotation should better span the whole bucket in which the missing document was detected.

**Comment by benwtrent** [comment]
This actually points out a flaw in how the time windows are calculated. It should adjust the windows so that the start is always at the beginning of the first bucket and the end is always at the end of the last bucket. 

I will cook something up.
