### ISSUE TITLE
Units inconsistencies in logs

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#36896]
Currently (`master`) in the Elasticsearch server log we see lines like these:

```
[2018-12-19T09:14:11,136][INFO ][o.e.m.j.JvmGcMonitorService] [es1_1] [gc][2375] overhead, spent [260ms] collecting in the last [1s]
```

Notice the durations in these lines, 260ms and 1s. Would it be possible to normalize the unit here, perhaps to ms? That would make parsing these durations a lot easier.

**Comment by jasontedor** [comment]
I am not in favor of this. I think that Beats should aim to support the same units that Elasticsearch can output here, both for time values and for byte size values.

**Comment by ycombinator** [comment]
Thanks Jason. Perhaps this issue becomes moot when https://github.com/elastic/elasticsearch/issues/31244 is implemented?

**Comment by jasontedor** [comment]
@ycombinator Yes, if we can reach agreement on how to proceed there. It would help with this issue though indeed as then these values could be mapped as duration types.

**Comment by jasontedor** [comment]
@ycombinator Is it okay to close this issue then?
