### ISSUE TITLE
monitoring: alerts may be sent to the wrong email with multiple clusters

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#36917]
Monitoring alerts may be sent to the wrong email when a monitoring cluster is monitoring more then 1 cluster. 

Given 3 (or more) clusters:
* A monitoring cluster - clusterA
* A normal cluster - clusterB
* A nomral cluster - clusterC

clusterB and clusterC are shipping monitoring data to clusterA
clusterB has a default email defined 
clusterC has a default email defined

If clusterB raises an alert, the email to which that alert gets sent is not guaranteed to be clusterB's admin. It may get sent to clusterC's admin. 

The issue here is how the Watch finds the email to send the alert to. The Watch assumes that in the `.monitoring-kibana-6-*` there is only 1 default email. Which is always true for the local case, but for a monitoring cluster monitoring many clusters there may be many default emails (one per cluster).  The watch pulls the most recent default email that is found, irrespective of the source cluster. (see the query below).

There are two choices to fix this:
1) Honor the origin's clusters admin email
2) Honor the monitoring cluster's admin email

In both case, we should consider falling back to the other if not set. 

@pickypg suggested possibly updating the watch to the following (which I believe is option 1 without a fallback)
```
  "bool": {
      "filter": [
          { "term": { "type": "{{ctx.metadata.cluster_uuid}}" } },
          { "term": { "type": "kibana_settings" } }
        ]
      }
    }
```    
-------------

To reproduce:

This is a docker compose test bed with 3 ES and 3 Kibana instances. 
* 9200/5601 - the monitoring cluster
* 9201/5602 - data cluster 1
* 9202/5603 - data cluster 2

unzip the following zip file: [es_kibana_monitoring.zip](https://github.com/elastic/elasticsearch/files/2700825/es_kibana_monitoring.zip)
run `docker-compose up  --force-recreate`

Once the all the containers are up, from bash run (this is how the Watches pull the email address):
```
for i in {1..120}; do curl -s -XGET "http://localhost:9200/.monitoring-kibana-6-*/_search?_source_include=kibana_settings.xpack&pretty" -H 'Content-Type: application/json' -d'
{
  "size": 1, 
  "query": {
    "bool": {
      "filter": {
        "term": {
          "type": "kibana_settings"
        }
      }
    }
  },
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ]
}' | grep default_admin_email; sleep 1; done
```
(note the above is querying the monitoring cluster, which is where the watches are actually run)

You should see the email flapping between the two email addresses associated with the two clusters shipping data (this is the bug):
```
"default_admin_email" : "kb_cluster2@example.com"
"default_admin_email" : "kb_cluster2@example.com"
"default_admin_email" : "kb_cluster2@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster1@example.com"
"default_admin_email" : "kb_cluster2@example.com"
"default_admin_email" : "kb_cluster2@example.com"
"default_admin_email" : "kb_cluster2@example.com"
```              

If you want to see the watch actually fire make a data cluster turn yellow
```
curl -XPUT "http://localhost:9201/test_index" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 10
  }
}'
```
and fix the alert (for another email)
```
curl -XDELETE "http://localhost:9201/test_index"
```
It may take a few tries to get unlucky.

Open a browser to http://localhost:1080 and view who it is sent to.

**Comment by jakelandis** [comment]
> There are two choices to fix this:
> 1) Honor the origin's clusters admin email
> 2) Honor the monitoring cluster's admin email

I tend to favor option 2 (with a fall back) since the email is a Kibana setting not an ES setting. If a client has many ES clusters they wish to monitor and those clusters don't have an associated Kibana instance, option 1 may be a breaking change. Technically this bug allows a single kibana+ES cluster to monitor many Kibana-less clusters today if and only if the monitoring cluster is monitoring itself with a default email. I worry that if we fix this with option 1 (with out a fall back) that it will break monitoring for Kibana-less clusters. 

Also option 2 can greatly simplify deployments with many ES clusters, since it is only 1 email to configure. 

However, if option 2 is implemented, then a fall back to the origin's cluster admin email is a must to allow for multi-tenant monitoring. 

Further, I believe that for option 2, a change would be needed in Kibana to allow an option to always publish it's settings to the `.monitoring-kibana-6-*` indicies. Currently (if I understand correctly), Kibana will only publish it's settings if the attached ES has monitoring enabled. Which would mean that without a change to Kibana, and we implemented option2 the only way it would work is if the monitoring cluster monitored itself to allow publishing it's own default email.

@pickypg @ycombinator - thoughts ?

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
