### ISSUE TITLE
span_or containing span_first's on different fields not working as expected

### ISSUE THREAD

**Issue by fuzing** [elastic/elasticsearch#36969]
Elasticsearch versions: replicated with 6.5 -> 7.0-alpha2.    Probably goes back earlier.

Note: this is simply the query portion as a JS object (i.e. it is transmitted to the ES server as proper JSON) - 

`       query: {
          span_or: {
            clauses: [
              {
                span_first: {
                  match: {
                    span_term: {"title": {value: "abc", boost: 1}}
                  },
                  end: 10,
                }
              },
              {
                span_first: {
                  match: {
                    span_term: {"subtitle": {value: "abc", boost: 1}}
                  },
                  end: 10,
                }
              }
            ]
          }
        }
`

This query causes the following error:
   query_shard_exception -> failed to create query
   illegal argument exception -> Clauses must have same field

The way I read the error it appears that ES is complaining about the different field names (i.e. "title" vs. "subtitle" in the two span_first queries).    Is this the expected behavior?   If so, then how would one achieve the following result?:

- get the union of results matching the search term "abc" on fields "title" and "subtitle", ranked using span_first heuristics (i.e. terms matched closest to the beginning of the field score higher).

Thank you!

**Comment by jimczi** [comment]
We reserve github for confirmed bugs and feature request and prefer to use the [forum](https://discuss.elastic.co/c/elasticsearch) for general questions so I hope you don't mind if I close this issue.
Regarding your question you need to use the [`field_masking_span`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-field-masking-query.html) query which is an adapter to use multiple fields in a `span_or/span_near` query.
