### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by joemantk** [elastic/elasticsearch#36992]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Listening for transport dt_socket at address: 1044
Version: 6.4.0, Build: default/zip/595516e/2018-08-17T23:18:47.308994Z, JVM: 1.8.0_162

**Plugins installed**: [] none

**JVM version** (`java -version`):
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Windows 10 Pro

**Description of the problem including expected versus actual behavior**:

refresh is not working
adding document then deleting the documnet then refresh and then adding it again showing version conflict

**Steps to reproduce**:

run the following curl commands

 1. curl -XPUT -H "Content-Type:Application/json" 127.0.0.1:9200/myindex/mytype/3?version=44'&'version_type=external_gte  -d'{"name":"myname"}'
 2. curl -XDELETE -H "Content-Type:Application/json" 127.0.0.1:9200/myindex/mytype/3
 3. curl -XPOST  -H "Content-Type:Application/json" 127.0.0.1:9200/myindex/_refresh
 4.  curl -XPUT -H "Content-Type:Application/json" 127.0.0.1:9200/myindex/mytype/3?version=43'&'version_type=external_gte  -d'{"name":"myname"}'

**Provide logs (if relevant)**:
{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[mytype][3]: version conflict, current version [45] is higher than the one provided [43]","index_uuid":"YGOuxxDJQyir5ZcSTYVtXA","shard":"4","index":"myindex"}],"type":"version_conflict_engine_exception","reason":"[mytype][3]: version conflict, current version [45] is higher than the one provided [43]","index_uuid":"YGOuxxDJQyir5ZcSTYVtXA","shard":"4","index":"myindex"},"status":409}

If I ran the last curl command after 1 minute it works fine
I expect the refresh to allow me to update immediately and not have to wait for index.gc_deletes to pass
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html

Thanks,
Tal

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This behavior is correct and expected. The versions of deleted documents will be maintained for at least the `index.gc_deletes`  time interval. You can disable `gc_deletes` by setting `index.gc_deletes` to `-1`.

We'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by joemantk** [comment]
Thank you for the replay
I do not think I will be able to change the index.gc_deletes value because sometimes it is not my ES cluster, sometimes I'm just hosted there
My main question was why refresh 
as state in https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html
does not work as it is describe in the documentation 
I will use the forum to find an answer
Thanks,
