### ISSUE TITLE
service files belong in /lib/systemd/system not /usr/lib/systemd/system on debian/ubuntu

### ISSUE THREAD

**Issue by jsoref** [elastic/elasticsearch#36994]
**Elasticsearch version**: 6.5.4

**Plugins installed**: []

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04.1 LTS

**Description of the problem including expected versus actual behavior**:

Debian and Ubuntu expect systemd files to be in `/lib/systemd/system`:
https://unix.stackexchange.com/questions/206315/whats-the-difference-between-usr-lib-systemd-system-and-etc-systemd-system

The package currently installs into:
`/usr/lib/systemd/system/elasticsearch.service`

**Steps to reproduce**:

 1. install ubuntu18.04
 2. `sudo -i`:
```sh
echo deb http://artifacts.elastic.co/packages/6.x/apt stable main> /etc/apt/sources.list.d/elastic-6.x.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D27D666CD88E42B4
apt update
apt install -y elasticsearch
dpkg -S /usr/lib/systemd/system/elasticsearch.service
```

**Comment by rjernst** [comment]
My understanding is systemd services provided by packages (like elasticsearch) go under `/usr/lib/systemd/system` (and the linked thread seems to confirm this understanding). So I think this is currently correct. @jsoref Could you please clarify what you see as incorrect in the current elasticsearch packages?

**Comment by jsoref** [comment]
On most of my Ubuntu Bionic systems, there is no `/usr/lib/systemd/system` directory at all -- except on the systems where I've installed elasticsearch, in which case that directory was created just for the elasticsearch service.

Files are installed into `/lib/systemd/system`:
```
accountsservice: /lib/systemd/system/accounts-daemon.service
gce-compute-image-packages: /lib/systemd/system/google-accounts-daemon.service
acpid: /lib/systemd/system/acpid.path
acpid: /lib/systemd/system/acpid.service
acpid: /lib/systemd/system/acpid.socket
apache2: /lib/systemd/system/apache2.service.d/apache2-systemd.conf
apache2: /lib/systemd/system/apache2.service
apache2: /lib/systemd/system/apache2.service.d
apache2: /lib/systemd/system/apache2@.service
apache2: /lib/systemd/system/apache2.service.d/apache2-systemd.conf
apache2: /lib/systemd/system/apache2.service.d
apache2: /lib/systemd/system/apache-htcacheclean.service
apache2: /lib/systemd/system/apache-htcacheclean@.service
apparmor: /lib/systemd/system/apparmor.service
apport: /lib/systemd/system/apport-autoreport.path
apport: /lib/systemd/system/apport-autoreport.service
apport: /lib/systemd/system/apport-forward@.service
apport: /lib/systemd/system/apport-forward.socket
apt: /lib/systemd/system/apt-daily.service
apt: /lib/systemd/system/apt-daily.timer
apt: /lib/systemd/system/apt-daily-upgrade.service
apt: /lib/systemd/system/apt-daily-upgrade.timer
at: /lib/systemd/system/atd.service
systemd: /lib/systemd/system/autovt@.service
systemd: /usr/lib/systemd/user/basic.target
systemd: /lib/systemd/system/basic.target
lvm2: /lib/systemd/system/blk-availability.service
systemd: /usr/lib/systemd/user/bluetooth.target
systemd: /lib/systemd/system/bluetooth.target
systemd: /lib/systemd/system/stop-bootlogd.service
systemd: /lib/systemd/system/bootlogd.service
systemd: /lib/systemd/system/bootlogs.service
systemd: /lib/systemd/system/bootmisc.service
certbot: /lib/systemd/system/certbot.service
certbot: /lib/systemd/system/certbot.timer
...
```

Eventually Debian and Ubuntu will switch and the directory you're currently using will be the correct place, but for the time being, it isn't where things are placed. It works, it's just atypical.

**Comment by rjernst** [comment]
It follows the guidance from systemd documentation, though. Given that debian/ubuntu will be switching to /usr and the package currently works, I'm inclined to close this issue. Otherwise, when they do switch, we would then be reverting this change, but since we only produce a single deb file for all deb based distributions, older distributions would then have it again in the "wrong place".

**Comment by danielmitterdorfer** [comment]
Thanks for raising the topic @jsoref but I agree with the reasoning of @rjernst. Hence I hope you don't mind I am closing this.
