### ISSUE TITLE
Metricbeat [6.3] - missing metricbeat.modules fields

### ISSUE THREAD

**Issue by RotemEmergi** [elastic/elasticsearch#36991]
Hi ,

I am using elasticsearch & kibana & logstash version 6.3.2 .

I am using metricbeat 6.3 version and want to use to following  modules :  
1. module: mysql  
I  am trying to connect to secure mysql with cert and I can't want work with that because in the metricbeat-reference-yml.html it's missing .
"https://www.elastic.co/guide/en/beats/metricbeat/6.3/metricbeat-reference-yml.html" 
2.module: redis 
I am trying to connect to secure redis that work with ssl in port 6380 and I get this error : "redis/redis.go:45	Error retrieving INFO stats: read tcp x.x.x.x:47324->x.x.x.x:6380: read: connection reset by peer" also in the metricbeat-reference-yml.html there is missing fields .
3. module: zookeper -
I want to connect to zookeper  with username and password and it's missing in the metricbeat-reference-yml.html  .

Thanks

**Comment by atorok** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
