### ISSUE TITLE
[CCR] Handle index conflict with a 409 status code

### ISSUE THREAD

**Issue by sebelga** [elastic/elasticsearch#37020]
When we try to create a follower index with the same name as an existing index, we get a `400` response:

```
{
    "error": {
        "root_cause": [
            {
                "type": "resource_already_exists_exception",
                "reason": "index [my-follower-index/t1Z8bS8JRJuFi74flH7r6w] already exists",
                "index_uuid": "t1Z8bS8JRJuFi74flH7r6w",
                "index": "my-follower-index"
            }
        ],
        "type": "resource_already_exists_exception",
        "reason": "index [my-follower-index/t1Z8bS8JRJuFi74flH7r6w] already exists",
        "index_uuid": "t1Z8bS8JRJuFi74flH7r6w",
        "index": "my-follower-index"
    },
    "status": 400
}
```

We would need a `409` conflict status in order to handle better this error on the UI.

**Comment by ywelsch** [comment]
It's the same status code that's returned when you create an index for which there is already an index with same name.

> We would need a 409 conflict status in order to handle better this error on the UI.

Can you elaborate on this?

**Comment by sebelga** [comment]
The `400` bad request status code is generic. As the Elasticsearch API does not provide error codes we would need a more specific status for this use case (the `409` conflict seems the most appropriate) so we can better handle the error in Kibana (proper error message with its translation).

**Comment by martijnvg** [comment]
The 400 response code is what Elasticsearch returns when a request fails with a `resource_already_exists_exception` exception in all APIs. 
If the UI encounters a `resource_already_exists_exception` exception while executing the put follow api then that is clear enough to display an error message?

**Comment by sebelga** [comment]
After talking with @martijnvg and he confirmed we can rely on the `resource_already_exists_exception ` I close this ticket as the UI will use that information for the error message.
