### ISSUE TITLE
The exception message tells you the problem. Index settings can no longer be set through `elasticsearch.yml`. You need to actually set these in your index (or indirectly by creating indexes with templates).

### ISSUE THREAD

**Issue by Raininging** [elastic/elasticsearch#37029]
The exception message tells you the problem. Index settings can no longer be set through `elasticsearch.yml`. You need to actually set these in your index (or indirectly by creating indexes with templates).

_Originally posted by @rjernst in https://github.com/elastic/elasticsearch/issues/18073#issuecomment-215898684_
yean,just remove 'index.number_of_replicas' from elasticsearch.yml.It`s ok

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
