### ISSUE TITLE
[CCR] The stats for an unknown index return a 200 status

### ISSUE THREAD

**Issue by sebelga** [elastic/elasticsearch#37021]
When we try to access the stats for a follower index that does not exist, we receive a `200` status with the following response

```
GET /unknown/_ccr/stats

Status 200
{
    "indices": []
}
```

To be consistent with other APIs and follow REST standards, it should return a `404` status.

If we try the same with the `/_stats` API we do get the correct status

```sh
GET /unknown/_stats

Response
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index [unknown]",
                "resource.type": "index_or_alias",
                "resource.id": "unknown",
                "index_uuid": "_na_",
                "index": "unknown"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index [unknown]",
        "resource.type": "index_or_alias",
        "resource.id": "unknown",
        "index_uuid": "_na_",
        "index": "unknown"
    },
    "status": 404
}
```

**Comment by kradygithub** [comment]
Hi，here is my question:
 I try to use python to put data to es6.5.3, I found there is something different between 5.x and 6.x, When I try to put data with fixed “_id” item,I got the error msg:
[_id] is a metadata field and cannot be added inside a document

I want to fixed the id item to set the join relations parent and child.

Everyone knows the answer?


Waiting...

**Comment by martijnvg** [comment]
@sebelga Makes sense, this should be fixed.
