### ISSUE TITLE
Elasticsearch head requests return 403 when made to readonly index.

### ISSUE THREAD

**Issue by paulrblakey** [elastic/elasticsearch#3703]
Elasticsearch head requests return 403 when made to readonly index.

curl recreation of issue here.

https://gist.github.com/paulrblakey/6580888

issue originally opened with [ruflin/elastica](https://github.com/ruflin/Elastica/issues/457)

**Comment by tlrx** [comment]
Setting  `read_only: true` on an index blocks:
- any write operation such as indexing/deleting/updating a document
- any read & write operation on index metadata such as checking if the index exists, checking if a type exists, and also reading or updating the settings/aliases/warmers/mappings (and many more) of the index.

As a workaround, you can set `index.block.write: true`. This will block all write operation on the index but you will still be able to check for existance or update the settings/mappings etc.

Related to #2833, #5855, #5876, #8102

**Comment by elvarb** [comment]
@tlrx Will this workaround to set "index.block.write: true" not fulfill the need to make the data read only?

For logging data, protecting the json documents is what is needed and stopping writes (and hopefully updates and deletes as well) fulfills that need.

To protect whole indexes, for example for debugging of the health of the index or whatever "elasticsearch" related need comes up, by making the whole index read only.
