### ISSUE TITLE
discovery-ec2 plugin doesn't work with ec2 vpc endpoint

### ISSUE THREAD

**Issue by laod** [elastic/elasticsearch#37050]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.5.4, Build: default/rpm/d2ef93d/2018-12-17T21:17:40.758843Z, JVM: 1.8.0_191

**Plugins installed**: 

This cluster isn't forming yet so I can't get a _cat/plugins. Instead:

```
[centos@ip-10-128-64-225 ~]$ ls -l /usr/share/elasticsearch/plugins/
total 4
drwxr-xr-x. 2 root root 4096 Dec 27 20:47 discovery-ec2
[centos@ip-10-128-64-225 ~]$ ls -l /usr/share/elasticsearch/plugins/discovery-ec2/
total 6632
-rw-r--r--. 1 root root  850229 Dec 27 20:47 aws-java-sdk-core-1.11.187.jar
-rw-r--r--. 1 root root 3159983 Dec 27 20:47 aws-java-sdk-ec2-1.11.187.jar
-rw-r--r--. 1 root root  284184 Dec 27 20:47 commons-codec-1.10.jar
-rw-r--r--. 1 root root   62050 Dec 27 20:47 commons-logging-1.1.3.jar
-rw-r--r--. 1 root root   30334 Dec 27 20:47 discovery-ec2-6.5.4.jar
-rw-r--r--. 1 root root  736658 Dec 27 20:47 httpclient-4.5.2.jar
-rw-r--r--. 1 root root  327373 Dec 27 20:47 httpcore-4.4.5.jar
-rw-r--r--. 1 root root   46968 Dec 27 20:47 jackson-annotations-2.6.0.jar
-rw-r--r--. 1 root root 1165323 Dec 27 20:47 jackson-databind-2.6.7.1.jar
-rw-r--r--. 1 root root   11358 Dec 27 20:47 LICENSE.txt
-rw-r--r--. 1 root root   86403 Dec 27 20:47 NOTICE.txt
-rw-r--r--. 1 root root    1502 Dec 27 20:47 plugin-descriptor.properties
-rw-r--r--. 1 root root    1249 Dec 27 20:47 plugin-security.policy
```

**JVM version** (`java -version`):

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux ip-10-128-64-225.us-west-2.compute.internal 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When using a vpc endpoint url for ec2 (example: vpce-somehash-aphlsvfe-us-west-2a.ec2.us-west-2.vpce.amazonaws.com) the ec2 discovery plugin fails. If I add a hosts entry mapping the appropriate non-vpc ec2 endpoint (ec2.us-west-2.amazonaws.com) to the vpc endpoint ip address it works.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Configure elasticsearch normally adding the following ec2-discovery config:

```
discovery.zen.hosts_provider: ec2
discovery.zen.minimum_master_nodes: 2
discovery.ec2.groups: <security group>
discovery.ec2.endpoint: <vpc ec2 endpoint url>
```

 2. Start elasticsearch

 3. Observe exception in log:

`Exception while retrieving instance list from AWS API: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: 3db49e60-a260-48d1-a8f7-b1d342c2dc67)`

Note that these credentials work unchanged after adding the hosts entry.

**Provide logs (if relevant)**:

**Comment by ywelsch** [comment]
My guess is that the AWS SDK (which we internally use) does not properly compute the signer based on the endpoint that is passed, as it cannot derive the correct region from the custom endpoint (see https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/AwsHostNameUtils.java#L57-L64). This is also why your workaround works. There are multiple options here:
1) expose the regionId that is to be used for signing. This adds more complexity to the client and more options to configure our system, with the potential of additional misconfigurations.
2) file an enhancement request for the AWS SDK so that it recognizes these URLs (`vpce.amazonaws.com`) and properly derives the region.

**Comment by laod** [comment]
I will file an RFE for it with aws. Thank you.
