### ISSUE TITLE
SQL: Count distinct doesn't recognize that a string field has a keyword version

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#37087]
If a field is indexed as both as string and keyword, `count(DISTINCT field)` is using string version instead of the keyword version. To reproduce:

```
DELETE test

PUT test/doc/1
{
  "name": "foo",
  "category": "A"
}

POST _xpack/sql?format=text/plain
{
  "query": "SELECT count(DISTINCT name.keyword) as names, category FROM test GROUP BY category"
}

POST _sql/translate
{
  "query": "SELECT count(DISTINCT name) as names, category FROM test GROUP BY category"  
}
```

**Comment by astefan** [comment]
Not an issue anymore. Fixed with https://github.com/elastic/elasticsearch/pull/37176/files#diff-5d7529d13a2ef47d436ea2aa577e0c52R432. Closing.
