### ISSUE TITLE
elastic6.5.1 导入时差问题

### ISSUE THREAD

**Issue by Zoomtoo** [elastic/elasticsearch#37093]
原始数据在mysql中，同步数据我用的logstach，同步完成后，原始数据类型是datetime的字段，
到es中，比原来快了5个小时，尝试过在logstach的jdbc配置文件input中加入jdbc_default_timezone，也尝试过利用filter-ruby加入字段，减少5个小时，但并未见效，请问是什么原因，我的配置文件应该怎么写？
我的配置文件内容如下：

input {
    stdin{
    }
    jdbc {
      # 数据库
      jdbc_connection_string => "jdbc:mysql://xxxx:xxxx/bigdata?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull"
      jdbc_user => "xxx"
      jdbc_password => "xxx"
      # mysql驱动解压的位置
      jdbc_driver_library => "/home/elk1/software/logstash-6.5.3/logstash-core/lib/jars/mysql-connector-java-8.0.13.jar"
       # mysql驱动类
      jdbc_driver_class => "com.mysql.jdbc.Driver"
      jdbc_paging_enabled => "true"
      jdbc_page_size => "50000"
      #可以使用sql文件的方式
      #statement_filepath => "config-mysql/tag.sql"
      #要同步的表
      statement => "select * from axh_active_user limit 5"
      schedule => "*/3 * * * *"
      #索引type
      type => "active"
      #索引设置时区
      jdbc_default_timezone => "Asia/Shanghai"
    }
}

filter{
    date {
    match => ["add_time","UNIX_MS"]
    target => "@timestamp"   
  }
  ruby { 
   code => "event.set('timestamp', event.get('@timestamp').time.localtime - 5*60*60)" 
 }
 ruby {
   code => "event.set('@timestamp',event.get('timestamp'))"
 }
 mutate {
   remove_field => ["timestamp"]
 }
}
output {
    elasticsearch {
        hosts => "xxxx:xxxx"
        #索引名称
        index => "test"
        document_id => "%{id}"
        user => "u"
        password => "p"
        "document_type" => "%{type}"
    }
    stdout {
        codec => json_lines
    }
}

**Comment by Zoomtoo** [comment]
求给位指导，上面减5个小时的5x60x60星号没显示出来

**Comment by tvernum** [comment]
Google Translate:
> The original data is in mysql, the logstach I use to synchronize the data. After the synchronization is completed, the original data type is the datetime field.
To es, 5 hours faster than the original, tried to add jdbc_default_timezone in logstach jdbc configuration file input, also tried to use filter-ruby to join the field, reduce 5 hours, but it did not work, what is the reason? How should I write my configuration file?
My configuration file reads as follows:

[snip]

> Seeking guidance, the 5x60x60 asterisk minus 5 hours above is not shown.

**Comment by tvernum** [comment]
Hi @Zoomtoo, Thanks very much for your interest in Elasticsearch and Logstash.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There is a specific [Chinese forum](https://discuss.elastic.co/c/in-your-native-tongue/chinese) (中文提问与讨论) which may be particularly useful for you.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by Zoomtoo** [comment]
> Hi @Zoomtoo, Thanks very much for your interest in Elasticsearch and Logstash.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.
> 
> There is a specific [Chinese forum](https://discuss.elastic.co/c/in-your-native-tongue/chinese) (中文提问与讨论) which may be particularly useful for you.
> 
> There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
> 
> Thank you.

yes, i know, thanks!
