### ISSUE TITLE
Deprecate/remove common_terms query and cutoff_frequency

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#37096]
The [`common_terms`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html) query and the [`cutoff_frequency`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-cutoff) option of the `match` query are a good way to speed up search without removing stop words. However in Elasticsearch 7 we have another alternative that can automatically skip non-competitive documents based on the maximum score of each term in the query. This new method doesn't require any configuration (no cutoff frequency) and can be much faster than the `common_terms` alternative if the total number of hits that matches the query is not tracked. 
For this reason I wonder if we could/should deprecate/remove the other alternatives (`common_terms` and `cutoff_frequency`), they should not be needed anymore since we have a better alternative that doesn't require to set a cutoff frequency while still being able to speed up queries with high frequency terms.

**Comment by jimczi** [comment]
We discussed this offline and agreed that we should deprecate and remove since it is redundant with the MAX_SCORE optimization that will land in Elasticsearch 7.0. It's too late to deprecate in 6.x so the plan is to deprecate these features in 7x and remove in 8.

**Comment by ogryniuk** [comment]
Hi there,
I am interested in contributing to this project and have two questions:
1. **Specific**: Does this issue require any actions or is it simply a discussion of things to do in future? 
I would like to work on it but it discusses possible changes to different versions of Elasticsearch and I wonder how to carry them out if this Elasticsearch repository has only one single version...

2. **General**: How to request an issue to be assigned to you and avoid doing it for nothing which can happen when another contributor also gets interested and commit before you?

**Comment by camilin87** [comment]
I created a PR to address this issue

https://github.com/elastic/elasticsearch/pull/37479

I'm not sure it is all that is needed.

Can you please review it.
