### ISSUE TITLE
[DOCS] Document Global Ordinals in Detail

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#37092]
Relates to https://github.com/elastic/elasticsearch/issues/23101

In that issue, we documented `eager_global_ordinals` and we loosely document the purpose global ordinals. However, do not document when global ordinals actually gets used, which makes it more predictable for people to understand why their memory usage may go up for doc value fields.

Examples that may surprise users are implied by the existing documentation, but calling them out would be helpful.

Using any `keyword` fields with `doc_values` enabled (default) and `text` fields with `fielddata` enabled (not default).

- Sorting
- Aggregating
- Scripting

Having the caveats of global ordinals documented should lead to a little better understanding, and it may hopefully help us to reduce their usage overall.

**Comment by kiju98** [comment]
Maybe it's even better mentioning that the global ordinals are are monitored in the `fielddata` stats (see https://discuss.elastic.co/t/global-ordinals-performance-and-size-on-heap/158320/2)
