### ISSUE TITLE
[CI] JDK Download failures in :distribution:docker:buildDockerImage

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#37103]
This is happening every three to four hours now, always with OS `SLES 12-SP4, Linux 4.12.14-95.3-default`.  `buildDockerImage` fails with the following output:

```
Step 4/28 : RUN curl -s https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz | tar -C /opt -zxf -
 ---> Running in b371736ff4de
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl -s https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz | tar -C /opt -zxf -' returned a non-zero code: 2
```

Quoting @tvernum:
```
Another JDK download issue.
This one is starting to look like it could be a real problem.

If it keeps happening it might make sense to download the tgz to a file first so we can check size/integrity etc (which will at least give us some idea of how far it’s getting before it fails)
Maybe we could even retry the download if it did fail.
```

**Comment by davidkyle** [comment]
These failures are still occurring regularly with the same error as above.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+periodic/113/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/38/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/165/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu8,nodes=virtual&&linux/165/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/493/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/165/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu11,nodes=virtual&&linux/165/console

**Comment by atorok** [comment]
This fails consistently in CI on sles see : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/ I was not able to reproduce it locally on our vagrant SLES images.

**Comment by atorok** [comment]
Turns our our sles image in CI didn't have docker networking configured properly. 
This was fixed and the docker image is build correctly .

**Comment by atorok** [comment]
This had to do with changes to the download URLs and it's now back to normal.

**Comment by talevy** [comment]
This may not be the same problem, but a similar issue with fetching JDK was run into here:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=fedora-28/25/console

```
:distribution:docker:buildDockerImage (Thread[Execution worker for ':' Thread 6,5,main]) started.

> Task :distribution:docker:buildDockerImage
Task ':distribution:docker:buildDockerImage' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'docker''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+6.7+multijob-unix-compatibility/os/fedora-28/distribution/docker Command: docker build build/docker --pull --no-cache --tag elasticsearch:6.7.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch:6.7.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch-full:6.7.0-SNAPSHOT
Successfully started process 'command 'docker''
Sending build context to Docker daemon  148.1MB

Step 1/28 : FROM centos:7 AS builder
7: Pulling from library/centos
Digest: sha256:184e5f35598e333bfa7de10d8fb1cebb5ee4df5bc0f970bf2b1e7c7345136426
Status: Downloaded newer image for centos:7
 ---> 1e1148e4cc2c
Step 2/28 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Running in cd9139b499f3
Removing intermediate container cd9139b499f3
 ---> 72bdde349f54
Step 3/28 : ENV JAVA_HOME /opt/jdk-11.0.2
 ---> Running in a65652a20b5c
Removing intermediate container a65652a20b5c
 ---> 1deb0ca8f3c9
Step 4/28 : RUN curl --retry 8 -s https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz | tar -C /opt -zxf -
 ---> Running in add015bcc0dd
connection error: desc = "transport: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout"


> Task :distribution:docker:buildDockerImage FAILED
```

looks like it timed out reaching the URL?
