### ISSUE TITLE
Cannot uninstall Debian package on non-systemd machine

### ISSUE THREAD

**Issue by wolf99** [elastic/elasticsearch#37138]
**Elasticsearch version**:
```shell
$ curl -XGET 'localhost:9200'
{
  "name" : "0uaFEGY",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "IUnb_AZJSIyM1IaxC2cMJQ",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "d2ef93d",
    "build_date" : "2018-12-17T21:17:40.758843Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Plugins installed**: none

**JVM version**:
```shell
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**OS version**: Ubuntu 18.04 [WSL]

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

1. Install elasticsearch from the APT repository, per https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

2. Configure running with SysV init as per doc linked in step 1.

3. Ensure elasticsearch is running:
```shell
$ sudo -i service elasticsearch status
 * elasticsearch is running
```

4. Attempt `$sudo apt purge --autoremove elasticsearch`

**Expected behaviour**
APT successfully uninstalls elasticsearch

**Actual behaviour**
```shell
$ sudo apt purge --autoremove elasticsearch
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  elasticsearch*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 168 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 37566 files and directories currently installed.)
Removing elasticsearch (6.5.4) ...
Stopping elasticsearch service...System has not been booted with systemd as init system (PID 1). Can't operate.
dpkg: error processing package elasticsearch (--remove):
 installed elasticsearch package pre-removal script subprocess returned error exit status 1
System has not been booted with systemd as init system (PID 1). Can't operate.
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Errors were encountered while processing:
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I have attempted the commands suggested by the output, but as the system does not use systemd, these do not have the desired effect.

```shell
$ sudo systemctl daemon-reload
[sudo] password for you:
System has not been booted with systemd as init system (PID 1). Can't operate.
$ sudo systemctl enable elasticsearch.service
Synchronizing state of elasticsearch.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable elasticsearch
Created symlink /etc/systemd/system/multi-user.target.wants/elasticsearch.service → /usr/lib/systemd/system/elasticsearch.service.
$ sudo systemctl start elasticsearch
System has not been booted with systemd as init system (PID 1). Can't operate.
$ sudo apt purge --autoremove elasticsearch
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  elasticsearch*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 168 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 37566 files and directories currently installed.)
Removing elasticsearch (6.5.4) ...
Stopping elasticsearch service...System has not been booted with systemd as init system (PID 1). Can't operate.
dpkg: error processing package elasticsearch (--remove):
 installed elasticsearch package pre-removal script subprocess returned error exit status 1
System has not been booted with systemd as init system (PID 1). Can't operate.
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Errors were encountered while processing:
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by wolf99** [comment]
Thanks for the info @dliappis 
I have uninstalled by manually following the steps from the script that pertained to my system from the `prerm` and `postrm` scripts from https://github.com/elastic/elasticsearch/tree/master/distribution/packages/src/common/scripts

Additionally, I needed to manually remove the elasticsearch script from `/etc/init.d/` after the `sudo update-rc.d -f elasticsearch remove` command.
This solved my issue.

I hadn't seen the Supported Systems page you mentioned before I installed, but if I had I would likely have assumed that Ubuntu compatibility meant WSL compatibility. In that regard it might be worth an asterisk note there to indicate that that is not actually the case.
This would then help for others with the same question  😃

**Comment by dliappis** [comment]
Thank you for the suggestion. A note will be added in the support matrix clarifying the WSL situation.

**Comment by dreddnafious** [comment]
@wolf99 I have the same issue and am trying to understand exactly what you did to uninstall. Any chance you could be a bit more explicit?

**Comment by wolf99** [comment]
Sorry @dreddnafious this is from 2 years ago, I don't recall this at all.

**Comment by dreddnafious** [comment]
that's alright @wolf99 , thanks for responding.

**Comment by fontanka16** [comment]
Can one run the removal script step-by-step by any chance? And skip the steps that fails? Perhaps that is more of a Linux question though.

**Comment by daliusberdikslis** [comment]
> Thanks for the info @dliappis
> I have uninstalled by manually following the steps from the script that pertained to my system from the `prerm` and `postrm` scripts from https://github.com/elastic/elasticsearch/tree/master/distribution/packages/src/common/scripts
> 
> Additionally, I needed to manually remove the elasticsearch script from `/etc/init.d/` after the `sudo update-rc.d -f elasticsearch remove` command.
> This solved my issue.
> 
> I hadn't seen the Supported Systems page you mentioned before I installed, but if I had I would likely have assumed that Ubuntu compatibility meant WSL compatibility. In that regard it might be worth an asterisk note there to indicate that that is not actually the case.
> This would then help for others with the same question 😃

Also I removed files `ls -l /var/lib/dpkg/info | grep -i elasticsearch` located in `/var/lib/dpkg/info`

**Comment by parkerault** [comment]
For anyone else running into this issue, the easiest solution is to edit the prerm script at `/var/lib/dpkg/info/elasticsearch.prerm` and change lines 26 and 27 to `false`:
```sh
# Debian ####################################################
            remove)
                STOP_REQUIRED=true #change to false
                REMOVE_SERVICE=true #change to false
            ;;
```
This will prevent the script from trying to run systemctl and you can `sudo apt remove --purge elasticsearch` to completely remove the package.

**Comment by fontanka16** [comment]
@dliappis Is there a way to track when support for WSL will come around if ever?

**Comment by mark-vieira** [comment]
> @dliappis Is there a way to track when support for WSL will come around if ever?

Supporting installation of our Linux packages in a WSL environment isn't on our roadmap. If the workaround above solves your issues, great, otherwise I'd suggest running Elasticsearch via another packaging type (archive, or Docker).

**Comment by vctsvz** [comment]
> For anyone else running into this issue, the easiest solution is to edit the prerm script at `/var/lib/dpkg/info/elasticsearch.prerm` and change lines 26 and 27 to `false`:
> 
> ```shell
> # Debian ####################################################
>             remove)
>                 STOP_REQUIRED=true #change to false
>                 REMOVE_SERVICE=true #change to false
>             ;;
> ```
> 
> This will prevent the script from trying to run systemctl and you can `sudo apt remove --purge elasticsearch` to completely remove the package.

Thanks for the solution. I decided to simplify a little

`sed -i "s|STOP_REQUIRED=true|STOP_REQUIRED=false|;s|REMOVE_SERVICE=true|REMOVE_SERVICE=false|" /var/lib/dpkg/info/elasticsearch.prerm;`
