### ISSUE TITLE
analysis-icu IcuTokenizerFactory does not compile

### ISSUE THREAD

**Issue by Pyppe** [elastic/elasticsearch#37135]
**Elasticsearch version** (`bin/elasticsearch --version`): `6.5.4`

**Plugins installed**: [`analysis-icu`]

**JVM version** (`java -version`): `1.8.0_172`

**OS version** (`uname -a` if on a Unix-like system): `Darwin Kernel Version 18.2.0` (macOS Mojave 10.14.2)

**Description of the problem including expected versus actual behavior**:
`IcuTokenizerFactory` does not compile

DISCLAIMER: We've got a custom scala sbt build pipeline for our own elasticsearch plugins, and we also depend on the `analysis-icu` plugin. Thus, I'm not 100% sure this applies to elasticsearch's own gradle build, but as far as I can tell, the problem should be the same regardless of build environment.

**Provide logs (if relevant)**:
```
[error] org/elasticsearch/index/analysis/IcuTokenizerFactory.java:95:  com.ibm.icu.text.BreakIterator cannot be converted to com.ibm.icu.text.RuleBasedBreakIterator
[error]                             return super.getBreakIterator(script);
```

Now, the problem is the return type of:
```java
@Override
public RuleBasedBreakIterator getBreakIterator(int script) {
    if (breakers[script] != null) {
        return (RuleBasedBreakIterator) breakers[script].clone();
    } else {
        return super.getBreakIterator(script);
    }
}
```

AFAICT, the return type should be kept as the generic `BreakIterator` of parent type.

**Comment by jimczi** [comment]
What version of Lucene are you using in your plugin ? The signature of the function changed in Lucene 7.4 and Elasticsearch 6.5.4 uses Lucene 7.5.0 so I suspect that you're using a version of Lucene older than 7.4 ?

**Comment by Pyppe** [comment]
Thank you, that was indeed the underlying reason!

This issue can be closed. Sorry for the inconvenience.
