### ISSUE TITLE
rollover Index documentation has broken sentence

### ISSUE THREAD

**Issue by CvR42** [elastic/elasticsearch#37145]
The documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-rollover-index.html contains the following broken sentence:
> In this scenario, the original index will have their rollover alias will be added to the newly created index, and removed from the original (rolled-over) index.

I also suspect that the phrase [alias'] a little bit further on in the text has a superfluous ['] (I am using [] as quote marks here to make the error report more readable.)

**Comment by gwbrown** [comment]
@romansorin Hi, I see you made a commit fixing this issue to your fork, would you be interested in opening a PR to contribute that change to elastic/elasticsearch?

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This error is still in the documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-rollover-index.html#rollover-index-api-desc
