### ISSUE TITLE
[ILM] Index with wildcard in ILM explain returns 500 on cloud

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#37153]
Seen on cloud 6.6 (`90a342f`) deployments:

```
GET /*/_ilm/explain
```
![image](https://user-images.githubusercontent.com/1965714/50705331-52ba3680-100f-11e9-906f-de40d5a100c9.png)

```
GET /*bana/_ilm/explain
```
![image](https://user-images.githubusercontent.com/1965714/50705302-3c13df80-100f-11e9-803c-6310c085eea2.png)

**These requests work locally on the same version.**

Related to https://github.com/elastic/kibana/issues/28087

**Comment by talevy** [comment]
Closing due to this being unfortunate, but expected, behavior. Security returns this response since it is assuming the request is of a different type when ILM is disabled.

**Comment by pcsanwald** [comment]
removing version label as this isn't addressed in 6.6.0
