### ISSUE TITLE
403 for no index permission from _cat/indices call

### ISSUE THREAD

**Issue by bmcconaghy** [elastic/elasticsearch#37190]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:
When calling `_cat/indices` with no index list, indices for which the user does not have privileges simply omit the docs count and storage size information.  However, calling the same API _with_ an index for which the user does not have privileges (`_cat/indices/index_you_cant_see_info_for`) returns a 403 error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "action [indices:monitor/stats] is unauthorized for user [billy]"
      }
    ],
    "type": "security_exception",
    "reason": "action [indices:monitor/stats] is unauthorized for user [billy]"
  },
  "status": 403
}
```

I think the API should behave the same in either case, just return the data without storage size and docs count.

**Comment by javanna** [comment]
This is by design: empty indices are considered as a wildcard expression (same as specifying *), which is expanded to all the indices that the current user is authorized for. When specifying a concrete index though, you will get an error back like you noticed. I am pretty sure that this is documented somewhere, but I can't seem to find where anymore. Maybe somebody from @elastic/es-security can chime in.

**Comment by bmcconaghy** [comment]
@javanna This behavior is asymmetrical though.  Users _can_ see indices that they don't have permissions for when they don't specify an index list.  Seems to me that those indices should just be filtered out and then the behavior would be more consistent.

**Comment by javanna** [comment]
@bmcconaghy I see what you mean, I agree with you.

**Comment by albertzaharovits** [comment]
> @javanna This behavior is asymmetrical though. Users can see indices that they don't have permissions for when they don't specify an index list. Seems to me that those indices should just be filtered out and then the behavior would be more consistent.

I agree as well. I think the prob is in `RestIndicesAction` https://github.com/elastic/elasticsearch/blob/9ceb218d8597ed7aa565ce2b0e1d8f10d137c96a/server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java#L126 . I have an idea of a simple fix for this, but _cat APIs probably need some cleansing overall.

**Comment by rhass** [comment]
@albertzaharovits The `_cat/shards` call seems to be affected by this same bug.
