### ISSUE TITLE
Determine behavior for dynamic remote cluster compress and ping schedule settings

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#37201]
In PR #37200 the remote cluster compress and ping schedule settings are made dynamic. This is because it is currently impossible to configure them when adding a new remote cluster.

However, if these settings are now dynamically updated on their own, nothing will happen. We need to determine what behavior we want here.

Do we want:

1. To leave them dynamic, but they will only have an impact when you initialize a new remote cluster? The documentation needs to reflect this.

or

2. Add cluster listeners. And if you change one of these settings, they will reinitialize the impacted remote cluster.

**Comment by jasontedor** [comment]
@tbrooks8 I noticed this a few weeks ago too. I think that we need to re-initialize the impacted cluster (teardown the existing connections and re-establish them).

**Comment by s1monw** [comment]
> (teardown the existing connections and re-establish them).

++
