### ISSUE TITLE
Phrase queries combined with synonyms don't work for reversed words (slop > 2)

### ISSUE THREAD

**Issue by joeri-mesens** [elastic/elasticsearch#37232]
**Elasticsearch version**: 6.5.4

**Plugins installed**: []

**JVM version** : 1.8.0_191

**OS version**: OS-X 10.14.2

**Description of the problem including expected versus actual behavior**:

Phrase query "foo bar" with slop > 2 does not match "bar foo" when there's a synonym on one of the query words. **Important: Bug is within Lucene 7.5.0 and is solved from 7.6.0** (see https://issues.apache.org/jira/browse/LUCENE-8531). Upgrading to Lucene 7.6.0 should solve this issue (but might cause other issues ;-).

**Steps to reproduce**:

 1. Create a simple index with synonyms:

`curl -X PUT http://localhost:9200/zork  -H 'Content-Type: application/json'  -d '{
    "settings": {
        "index": {
            "analysis": {
                "analyzer": {
                    "synonym": {
                        "tokenizer": "standard",
                        "filter": [
                            "my_synonyms"
                        ]
                    }
                },
                "filter": {
                    "my_synonyms": {
                        "type": "synonym_graph",
                        "synonyms": [
                        	"developer, software engineer"
                        	]
                    }
                }
            }
        }
    },
    "mappings": {
        "jobs": {
            "properties": {
                "title": {
                    "type": "text",
                    "analyzer": "standard"
                }
            }
        }
    }
}'`

 2. Add two documents:

`curl -X PUT http://localhost:9200/zork/jobs/1 -H 'Content-Type: application/json' -d '{"title": "PHP Web developer"}'`

and

`curl -X PUT http://localhost:9200/zork/jobs/2 -H 'Content-Type: application/json' -d '{"title": "Web developer (PHP)"}'`

 3. Search:

without synonym analyzer: 2 results

`curl -X POST  http://localhost:9200/zork/_search  -H 'Content-Type: application/json'  -d '{
    "query": {
        "match_phrase": {
            "title": {
            	"query": "php developer",
	            "slop": 5,
	            "analyzer": "standard"
            }
        }
    }
}'`

with synonym analyzer: 1 result

`curl -X POST  http://localhost:9200/zork/_search  -H 'Content-Type: application/json'  -d '{
    "query": {
        "match_phrase": {
            "title": {
            	"query": "php developer",
	            "slop": 5,
	            "analyzer": "synonym"
            }
        }
    }
}'`

**Comment by jaymode** [comment]
Given that this issue is fixed in Lucene 7.6 and the next version of 6.x will be released using Lucene 7.6 (https://github.com/elastic/elasticsearch/pull/36722), I am going to close this issue.

cc @jimczi in case I missed something.

**Comment by jimczi** [comment]
This is the relevant issue in Lucene: https://issues.apache.org/jira/browse/LUCENE-8531
As @jaymode noticed, the fix is already present in a Lucene release (7.6) and will be available in the next version of Elasticsearch 6.x.
Thanks for reporting @joeri-mesens !

**Comment by joeri-mesens** [comment]
Glad next 6.x version will use Lucene 7.6, and so will be my customer :-) Thanks!
