### ISSUE TITLE
[DOCS] Optimize certification documentation

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#37235]
**Describe the feature**:

This URL contains a list of objectives/tasks that users must know how to do during their certification exam:

https://training.elastic.co/exam/elastic-certified-engineer

Since users are limited to using our documentation search during their certification exam (i.e. they do not have access to external search sites), we should verify that we have appropriate coverage for all of those tasks (and good search results).

Currently, the exam pertains to Elasticsearch 6.5.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by lockewritesdocs** [comment]
This issue relates to the Elastic education team and not the Docs team. Marking this as closed.
