### ISSUE TITLE
When using "span_multi" with wildcard, always return "exceeds maxClauseCount ..." 

### ISSUE THREAD

**Issue by dylanf-ingenium-tech-com** [elastic/elasticsearch#37241]
**Elasticsearch version** (`bin/elasticsearch --version`):6.4.3

**Plugins installed**: [None]

**JVM version** (`java -version`): Java 8 

**OS version** (`uname -a` if on a Unix-like system):Win 2012/R2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

When using "span_multi" with wildcard, prefix or regex, always return "exceeds maxClauseCount [ Boolean maxClauseCount is set to 1024" 

How ever it works if change the * to ? in wildcard

{ "span_multi": {"match" : {
                    

                    
                    "wildcard" : { "rawdoc.exact" :  { "value" : "drawing*"} }
                    
                    
                  }

**Provide logs (if relevant)**:

**Comment by dylanf-ingenium-tech-com** [comment]
Query:
GET _search
{
             "from" : 0, "size" : 10000,
             "_source":["dr", "divisionid","documenttype"],
                 "query": {
                    "bool": {
                      "filter": [
                        {
                          "term": { "dr":  "201800967723" }
                        }
                        ,         
        { 
          "bool" : {
            "should" : [ 
              
              
              
        { 
            "span_near" : {
                "clauses" : [
                        
                  { "span_term" : { "rawdoc.exact" : "plan" } } , 
    
                  { "span_multi": {"match" : {
                    

                    
                    "wildcard" : { "rawdoc.exact" :  { "value" : "drawing*"} }
                    
                    
                  }
                    
                    
                  }}
    
                ],
                "slop" : 5,
                "in_order" : false
            }
        }
        
            ]  
          }
        }
        
                      ]
                     
                   }
                 }
             }
            
                          
Result:

{
  "took": 208,
  "timed_out": false,
  "_shards": {
    "total": 15,
    "successful": 13,
    "skipped": 0,
    "failed": 2,
    "failures": [
      {
        "shard": 0,
        "index": "doc_less_stemming",
        "node": "9C3XU-W7Qfy4UKTSIgA1mQ",
        "reason": {
          "type": "runtime_exception",
          "reason": "runtime_exception: [rawdoc.exact:drawing* ] exceeds maxClauseCount [ Boolean maxClauseCount is set to 1024]"
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}

**Comment by matriv** [comment]
@dylanf-ingenium-tech-com Have you checked out the warning note at the bottom of the page here: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl-span-multi-term-query.html ?
Rewriting to `top_terms_*` or using `index_prefixes` may help.

Another option would be to set the `indices.query.bool.max_clause_count` setting to a higher value than 1024 which is the default, but this option should be used carefully as it might have impact on the performance of the cluster.

**Comment by jimczi** [comment]
This is expected, you should use the `index_prefixes` option in the mapping to ensure that prefixes are indexed, you can also use a different rewrite method for your prefix query. The limit was added to prevent wild expansion that can exhaust the memory on the node. Considering that this limit is documented and that you can workaround the issue I hope you don't mind that I close this issue.
