### ISSUE TITLE
ElasticsearchStatusException thrown where IndexNotFoundException expected

### ISSUE THREAD

**Issue by Olard** [elastic/elasticsearch#37265]
**Elasticsearch version** (`bin/elasticsearch --version`):  6.5.1

**Plugins installed**: none

**JVM version** (`java -version`): 9.0.4

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

I expected that the RestHighLevelClient parses the error code and throws the correct exception type (IndexNotFoundException). This would be useful to determine what exactly happened programmatically (currently the error type is hidden in the exception message which would be messy to parse)

**Steps to reproduce**:

 1. Start elasticsearch server
 2. Perform search on non existing index via the RestHighLevelClient
 3. thrown exception is ElasticsearchStatusException with a message containing the correct type

**Comment by matriv** [comment]
As far as I can see the `RestHighLevelClient` in both sync and async requests always parses the Response returned by the low level client and creates an `ElasticsearchStatusException` from it with the proper type and message.

**Comment by hub-cap** [comment]
The reason this happens is that the response is sent over http to the client, and the client only has a message to work with. The client gets the same thing you would get from issuing a curl command, 

```
 % curl localhost:9200/foo/_doc/1
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [foo]","resource.type":"index_expression","resource.id":"foo","index_uuid":"_na_","index":"foo"}],"type":"index_not_found_exception","reason":"no such index [foo]","resource.type":"index_expression","resource.id":"foo","index_uuid":"_na_","index":"foo"},"status":404}%
```

There is something to be said about better exception handling on the client, but until we can do this across the board for every exception, we are stuck with what we have. When we start to work on client side code generation (not soon, heh), then I will try my best to have better, concrete exceptions thrown from the methods. But until then you should be parsing the error responses.

**Comment by Olard** [comment]
Ok, thank you : ), I just thought that it is odd that the type is already parsed, but only used to build the message instead of instantiating the specific type. As an intermediary solution it would be cool if the already parsed type could be retrieved via a getter so that you don't need to parse it yourself.

**Comment by abhidemon** [comment]
The problem with this way of throwing exceptions is that I cannot really write a logic for handling the case wherein the index already exists. 
Unless I parse the msg ofcourse.
