### ISSUE TITLE
The Phrase Suggester should return the score of the input phrase

### ISSUE THREAD

**Issue by raphael0202** [elastic/elasticsearch#37270]
When using the Phrase Suggester, each suggestion is returned with its associated score.
The `confidence` parameter is used as a threshold applied to each suggestion. According to the documentation:
```
Only candidates that score higher than the threshold will be included in the result. For instance a confidence level of 1.0 will only return suggestions that score higher than the input phrase.
```
Using the `threshold` parameter, we can filter out suggestions for that the suggester is not confident about. However, we still don't know *how* confident the suggester is, we only have a rough idea given the `threshold` we provided.
To have this information, the suggester should return either the score of the input phrase or the `candidate_score / input_phrase_score` ratio.

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
