### ISSUE TITLE
Scorers are being created under filter context, while they shouldn't

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#37290]
Running a terms query on an IP datatype field under the filter context seems to create scorers and slow down searches - although no scoring should be applied in this case. We have confirmed this by running the query under `profile: true` and seeing `"build_scorer": 37845185684,` for said query clause.

Using 6.5.4 and confirmed with few other earlier versions as well.

See full details here: https://discuss.elastic.co/t/filter-context-and-build-scorers/160725

**Comment by jimczi** [comment]
Thanks @synhershko , 

> We have confirmed this by running the query under profile: true and seeing "build_scorer": 37845185684, for said query clause.

Scorers are created for queries and filters, the name is misleading. I answered in the [forum](https://discuss.elastic.co/t/filter-context-and-build-scorers/160725/2?u=jimczi), let's continue the discussion there since the behavior reported here is expected.

**Comment by synhershko** [comment]
Thanks @jimczi! will reply there
