### ISSUE TITLE
Queries executing during atomic index deletion and alias swap fail

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#37323]
Currently it's possible in Elasticsearch to delete an index at the same time as
an alias is added for the old name, for example, with the index `foo` and `bar`
that contain identical data, deleting `bar` and replacing it with an alias to
`foo` in an atomic operation like so:

``` json
POST /_aliases
{
    "actions" : [
        { "add":  { "index": "foo", "alias": "bar" } },
        { "remove_index": { "index": "bar" } }
    ]
}
```

This is considered an "atomic" operation, however, any in-flight search requests
that were currently executing on the `bar` index will fail when the index is
deleted.

It would be nice if ES would:

- block (queue) new search requests
- wait until all ongoing queries against the `bar` index have completed
- delete the `bar` index
- allow the queued queries to proceed, re-routing to the newly created index

This would allow the atomic operation to occur without any query disruption.

**Comment by colings86** [comment]
Would it work to take this a bit further even and say that a node waits for either 30 seconds or for all in-flight search requests to be complete before removing the shard form the node when it sees the index removed form the cluster state?

**Comment by dakrone** [comment]
> Would  it work to take this a bit further even and say that a node waits for  either some timeout (10 seconds?) or for all in-flight search requests  to be complete before removing the shard form the node when it sees the  index removed form the cluster state?

I think that would introduce some tricky semantics around an index being deleted in the state but not on disk, and then the node failing over (maybe not with index tombstones?). Even with a timeout though, how would we ensure that there aren't any 3 minute queries currently executing? On the other hand, we probably don't want to wait 10 hours (longest I have seen a query execute successfully) before performing a deletion/alias swap...

**Comment by colings86** [comment]
> Even with a timeout though, how would we ensure that there aren't any 3 minute queries currently executing? On the other hand, we probably don't want to wait 10 hours (longest I have seen a query execute successfully) before performing a deletion/alias swap...

Yeah this was the reason I suggested a timeout. I think its acceptable for us to wait a small amount of time for in-flight requests and then time out ones which are taking too long since we expect most search requests on a single shard to execute quite quickly and we can't wait forever.

**Comment by tugberkugurlu** [comment]
@dakrone may I ask why you wouldn't execute the below one instead:

```
POST /_aliases
{
    "actions" : [
        { "remove": { "index": "bar", "alias": "bar" }},
        { "add":  { "index": "foo", "alias": "bar" } }
    ]
}
```

AFA I understand, this should allow you to serve for in-flight requests as well as directing the upcoming ones to the new index (i.e. `foo`). TBH, I haven't validated this assumption yet. Therefore, take this with a pinch of salt :) However, based on my research so far, this should allow you to handle in-flight requests with the disadvantage that you need to handle index deletion later through some other logic (e.g. after 1 hour, delete any index which doesn't have an alias, etc.).

**Comment by ldematte** [comment]
Forwarded to the search team; this seems to be coordination between search and index, but it is failing on the search side of things.

**Comment by javanna** [comment]
We have no plans to work on this. Closing.
