### ISSUE TITLE
Doc: Close and then pause before unfollow

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#37336]
Minor doc suggestion.

"must be paused and closed before invoking the unfollow API" suggests that the follower index must be paused and then closed before calling unfollow.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.x/java-rest-high-ccr-ccr-unfollow.html#java-rest-high-ccr-ccr-unfollow-request
https://www.elastic.co/guide/en/elasticsearch/reference/6.x/ccr-post-unfollow.html

It actually expects the follower index to be closed first and then paused before calling unfollow.  Maybe we can just switch the ordering of the words around "paused and closed" -> "closed and paused" in the 2 places?

**Comment by dnhatn** [comment]
@ppf2 Thanks for reporting this.

Although it's possible to close then pause before unfollow, we indeed recommend users to pause then close before unfollow to avoid unnecessary noise.
