### ISSUE TITLE
Assign default pipelines in monitoring index templates

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#37334]
Currently the Monitoring `HttpExporter` adds the `pipeline` parameter to every bulk index request: https://github.com/elastic/elasticsearch/blob/9fd4d6ba4be313e722f475b6d72e7d2c3ceb2cbd/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/http/HttpExporter.java#L565

Further, the pipeline name is selected using the version of the monitoring index templates (2, 6, etc.): https://github.com/elastic/elasticsearch/blob/9fd4d6ba4be313e722f475b6d72e7d2c3ceb2cbd/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/monitoring/exporter/MonitoringTemplateUtils.java#L112-L114

With https://github.com/elastic/elasticsearch/pull/32286, we can now set the default pipeline within each monitoring index template itself and remove this bit of code.

**Comment by ycombinator** [comment]
@pickypg pointed out that the `LocalExporter` adds the `pipeline` parameters to every index request as well:

https://github.com/elastic/elasticsearch/blob/9fd4d6ba4be313e722f475b6d72e7d2c3ceb2cbd/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalBulk.java#L78-L80

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
