### ISSUE TITLE
CI: CRUDDocumentationIT.testReindex constantly fails on Windows

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37343]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/171/console

## Reproduction line 
```
./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=A9C06FFC5EF7E3F4 -Dtests.class=org.elasticsearch.client.documentation.CRUDDocumentationIT -Dtests.method="testReindex" -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=America/Montserrat -Dcompiler.java=11 -Druntime.java=8
```

## Example relevant log:
[see here](https://gist.github.com/atorok/b921ca838e2da6aa925e29fa027e353e)

## Frequency
Constantly

**Comment by hub-cap** [comment]
This test was fixed in a57571045ee404468ea5b311033b8b8aae4b89dd. the windows build is still failing, but not for this rest test after this commit, i verified by checking the time of the builds vs the time of my commit. build 172 was the last build broken by this.
