### ISSUE TITLE
SQL: Introduce proper SQL DATE type

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37340]
In the spirit of #36440, ES SQL should be able to support a proper, date-only data type. As ANSI SQL already defines one through `DATE` once #36440 complete, ES SQL could have `DataType.DATE` added to describe a DATE only type.

Being a new date-time type, all date-related functionalities would need to take it into account:

a.  grouping and histograms
The latter in particular should have the minimum interval of 1 day
b. date-time functions
As most work on the date component this is mainly a validation task
c. date-time math
Adding or extracting an interval. Worth looking into whether `DATE`-`DATE` makes sense or whether we should add a date function (e.g. `DATE_DIFF`).

**Comment by matriv** [comment]
Created a new issue: #37692 to track the `DATE` -` DATE` functionality.
