### ISSUE TITLE
[Docs] List all existing ingest pipeline (GET _ingest/pipeline)

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#37367]
It is not documented how it is possible to retrieve all existing ingest pipelines, i.e., the effect of `GET _ingest/pipeline`.

I propose to add a corresponding section to the [Get Pipeline API](https://www.elastic.co/guide/en/elasticsearch/reference/master/get-pipeline-api.html) documentation.

**Comment by jakelandis** [comment]
@vladdypwnz , yes please. It should likely at the bottom of [Get Pipeline API](https://www.elastic.co/guide/en/elasticsearch/reference/master/get-pipeline-api.html), and we should also document the other ways to view other pipelines.  This isn't too dis-similar to other get API's. 

```
GET _ingest/pipeline
GET _ingest/pipeline/my-pipeline1,my-pipeline2
GET _ingest/pipeline/my-pipeline*
```

**Comment by vladdypwnz** [comment]
Ok, so you want  to add the various ways of obtaining the pipeline .
Should I just add the commands and results obtained for each one ?
 Would you like a description for each command or any additional info ? Also, in which part of code does the html for the Pipeline Api reside ? I searched in the /docs but couldn't find out where..

**Comment by dakrone** [comment]
Hi @vladdypwnz 

> Should I just add the commands and results obtained for each one?

You can probably put one example (perhaps of getting a single pipeline) and then mention that wildcards are supported, or you can retrieve all by leaving the pipeline name off.

> Would you like a description for each command or any additional info?

A description of each is nice, with an example of the output for one of APIs.

> Also, in which part of code does the html for the Pipeline Api reside?

This should be added to the bottom of https://github.com/elastic/elasticsearch/blob/master/docs/reference/ingest/apis/get-pipeline.asciidoc (`docs/reference/ingest/apis/get-pipeline.asciidoc`)

**Comment by debadair** [comment]
[docs issue triage]
