### ISSUE TITLE
Rollup: DELETE a rollup does not fully delete the rollup (bug)

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#37387]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.0

**JVM version** (`java -version`): 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
When I delete a rollup, it is not fully deleted, because I get an error when I try to recreate it

**Steps to reproduce**:
1. create a rollup
```
PUT _xpack/rollup/job/sensor
{
    "index_pattern": "kibana_sample_data_logs",
    "rollup_index": "sensor_rollup",
    "cron": "*/30 * * * * ?",
    "page_size" :1000,
    "groups" : {
      "date_histogram": {
        "field": "timestamp",
        "interval": "1h",
        "delay": "7d"
      },
      "terms": {
        "fields": ["agent.keyword"]
      }
    },
    "metrics": [
        {
            "field": "bytes",
            "metrics": ["min", "max", "sum"]
        }
    ]
}
```

2. delete the rollup
`DELETE _xpack/rollup/job/sensor`

3. recreate the rollup (with the same name)
```
PUT _xpack/rollup/job/sensor
{
    "index_pattern": "kibana_sample_data_logs",
    "rollup_index": "sensor_rollup",
    "cron": "*/30 * * * * ?",
    "page_size" :1000,
    "groups" : {
      "date_histogram": {
        "field": "timestamp",
        "interval": "1h",
        "delay": "7d"
      },
      "terms": {
        "fields": ["agent.keyword"]
      }
    },
    "metrics": [
        {
            "field": "bytes",
            "metrics": ["min", "max", "sum"]
        }
    ]
}
```

In the last step, I get the following error : 
```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Cannot create rollup job [sensor] because job was previously created (existing metadata)."
      }
    ],
    "type": "status_exception",
    "reason": "Cannot create rollup job [sensor] because job was previously created (existing metadata)."
  },
  "status": 409
}
```

**Comment by jimczi** [comment]
This is expected, see https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-delete-job.html. When a job is deleted, that only removes the process that is actively monitoring and rolling up data. It does not delete any previously rolled up data.

**Comment by jimczi** [comment]
This is linked, currently you have to delete the index to remove the data **and** the metadata associated. If you want to only delete the metadata you'll need to remove the `_meta` section of the index mapping. We are aware that this is not very user friendly so we have an [issue ](https://github.com/elastic/elasticsearch/issues/31347) opened to simplify this operation.

**Comment by fbaligand** [comment]
Thanks for complementary information. The new option suggested in #31347 issue would be great!

By the way, if I understand well, it is a bad idea to remove `_meta` section in rollup index, without remove data into it ?
My aim is to "update" rollup job, by deleting it, then recreate it with enhanced configuration.
