### ISSUE TITLE
Incorrect thread pool when registering Search related handlers to TransportService

### ISSUE THREAD

**Issue by hydrogen666** [elastic/elasticsearch#37392]
In this PR [#33732](https://github.com/elastic/elasticsearch/pull/33732), you guys add a thread_pool `search_throttled`,  register search related actions to thread_pool `SAME` (the `DIRECT_EXECUTOR_SERVICE`). When you apply this patch to branch [v6.x](https://github.com/elastic/elasticsearch/blob/6.x/server/src/main/java/org/elasticsearch/action/search/SearchTransportService.java) in [this commit](https://github.com/elastic/elasticsearch/commit/761f4c12e27), you forgot change the execution thead_pool of search related action to the `SAME`.  Is this by design or just a mistake?

**Comment by colings86** [comment]
@hydrogen666 This is indeed something that got missed. Would you be willing to work on a PR that fixes this?

**Comment by hydrogen666** [comment]
> this
[#37427](https://github.com/elastic/elasticsearch/pull/37427) PR here

**Comment by hydrogen666** [comment]
> @hydrogen666 This is indeed something that got missed. Would you be willing to work on a PR that fixes this?

[#37427](https://github.com/elastic/elasticsearch/pull/37427)
I've fixed this.

**Comment by s1monw** [comment]
@hydrogen666 how did you find out about this bug? can you give me some insights?

**Comment by hydrogen666** [comment]
@s1monw i was just reading the code about PR [#33732](https://github.com/elastic/elasticsearch/pull/33732) on master and 6.x...noting special
