### ISSUE TITLE
Indexing throughput drop after types removal issues deprecation messages

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#37411]
https://github.com/elastic/elasticsearch/pull/36549 introduced deprecation messages when types are used in _bulk APIs.

This has caused major throughput drops in our standard nightly benchmarks (that use a [_doc type](https://github.com/elastic/rally-tracks/blob/c59234cd922300f095c6f31567373586c564b703/geopoint/index.json#L7)) like the one seen here https://elasticsearch-benchmarks.elastic.co/#tracks/geopoint/nightly/30d:

![image](https://user-images.githubusercontent.com/1754575/51107784-8b6cc380-17f8-11e9-82e2-b833fd7864fd.png)

Other tracks affected are [http_logs](https://elasticsearch-benchmarks.elastic.co/#tracks/http-logs/nightly/30d), [nyc_taxis](https://elasticsearch-benchmarks.elastic.co/#tracks/nyc-taxis/nightly/30d), [noaa](https://elasticsearch-benchmarks.elastic.co/#tracks/noaa/nightly/30d), [geonames][(https://elasticsearch-benchmarks.elastic.co/#tracks/geonames/nightly/30d) and [nested](https://elasticsearch-benchmarks.elastic.co/#tracks/nested/nightly/30d).

The deprecation logger is [suppressing duplicate messages](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/logging/DeprecationLogger.java#L149) hence there is only one entry in the log file:

```
$ cat rally-benchmark_deprecation.log
[2019-01-14T11:05:37,399][WARN ][o.e.d.a.b.BulkRequest    ] [rally-node-0] [types removal] Specifying types in bulk requests is deprecated.
```

IMO a deprecated feature shouldn't cause a performance regression (at least not that magnitude) until it gets removed.

**Comment by colings86** [comment]
I think we need to change the code [here](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java#L430) so it only makes this call one for the bulk request and not every time the `add()` method is called? Alternatively we could modify the deprecation logger to not duplicate deprecation warnings form the same call site in the warning headers for the response within the same request but that might be a much harder change

**Comment by markharwood** [comment]
>I think we need to change the code here so it only makes this call one for the bulk request

Makes sense. Bulk indexing is likely the main source of repeated deprecated events.
