### ISSUE TITLE
Elasticsearch node on 7.0 alpha is not booting (Upgrade from 6.1.2)

### ISSUE THREAD

**Issue by shamzeer** [elastic/elasticsearch#37429]
Elasticsearch version (bin/elasticsearch --version): 7.0.0 alpha1

Plugins installed: [analysis-phonetic, ingest-attachment]

JVM version (java -version): 1.8.0.181

OS version (uname -a if on a Unix-like system): Windows 2012 R2

Description of the problem including expected versus actual behavior: We have disabled "_all" field in our mappings in ElasticSearch 6.1.2. We have created indices and indexed data into it. The following is an example of the mapping.

{
  "testindex": {
    "mappings": {
      "type": {
        "_all": {
          "enabled": false
        },
        "properties": {
          "title": {
            "type": "text"
          },
          "description": {
            "type": "text"
          }
        }
      }
    }
  }
}

Everything is fine with ElasticSearch 6.1.2. But when we upgrade to Elasticsearch 7.0.0 alpha 1, ElasticSearch boot up failed with the following error.

org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_all : {enabled=false}]

Is there a way to ignore it (_all) while booting up?
Or is there a way to update the mapping to remove the _all field?

Looking for a solution other than mandating re-index of data.

Please provide your suggestions. Thanks.

**Comment by shamzeer** [comment]
Thanks very much for considering this.

**Comment by jpountz** [comment]
@dakrone The approach looks good to me. I would just ensure that `enabled` is actually `false` when removing `_all` from the map? Can you open a PR and assign me as a reviewer?

**Comment by jimczi** [comment]
@jpountz, we agreed with @dakrone that the @elastic/es-search team will handle this issue ;)
I'll open a new pr with the approach that @dakrone took and let's discuss the failing upgrade test there.

**Comment by markwalkom** [comment]
@shamzeer we'd like to thank you for your contribution to 7.0! do you mind dropping an email to community@elastic.co so we can arrange to send you out a gift? :)
