### ISSUE TITLE
SQL: incorrect interval reading with more than 3 fractional second digits

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#37423]
The interval parsing yields incorrect results when fractional second part is on more than 3 digits:
```
sql> select interval -'22 22:21:20.19182' day to second;
INTERVAL '22 22:21:20.19182' DAY TO SECOND
------------------------------------------
PT-550H-21M-39.182S
```

instead of expected result: `PT-550H-21M-20.191S`.

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/cea81b199dcb92bf80fb42a87fb4817a4f63d890
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/d0fb8dc1c7d27cf53478d1b666d09fd91c884c78
6.6 (6.6.1): https://github.com/elastic/elasticsearch/commit/ffd3aa19e3c2e9a54a7a3310042560382b6620f1
