### ISSUE TITLE
Avoid deprecation warnings due to monitoring index templates.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37442]
When putting and getting templates, monitoring currently uses the old typed APIs. In particular, the type name is included in the mapping definition, and when communicating over REST, the parameter `include_type_name=true` is specified.

When we soon deprecate the typed put + get templates calls on master, this will result in us issuing deprecation warnings when the monitoring `http` exporter is used. This won't be a great experience for users, as they'll receive deprecation warnings that are out of their control to fix. Note that if the `http` exporter needs to be able to connect to a 6.7 cluster, then `include_type_name` should be explicitly provided and set to `false`, since `include_type_name` defaults to `true` in 6.7 (whereas on master it defaults to `false`).

**Comment by kesslerm** [comment]
The new parameter `include_type_name` breaks remote monitoring if the remote cluster is still on an older version of Elasticsearch.

**Comment by jtibshirani** [comment]
@kesslerm I don't think this is a supported configuration. From https://www.elastic.co/guide/en/elastic-stack-overview/current/how-monitoring-works.html:

> In general, the monitoring cluster and the clusters being monitored should be running the same version of the stack. A monitoring cluster cannot monitor production clusters running newer versions of the stack.

When deciding how to tackle warnings in monitoring, we relied on this restriction (that the remote cluster must be upgraded first).

**Comment by jtibshirani** [comment]
Closing this issue, as it was addressed in the linked PRs.
