### ISSUE TITLE
Shortcut counts on exists queries

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#37475]
`TopDocsCollectorContext` is already able to shortcut hit counts on `match_all` and `term` queries when there are no deletions. It would be nice to also shortcut `exists` queries, especially because running a `match_all` query on an index that has nested documents runs a DocValueFieldExists query under the hood on the `_seq_no` field.

This would only work on indices without deletions and fields that are indexed: fields indexed with terms can use `Terms#getDocCount` and fields indexed with points can use `PointValues#getDocCount`.

**Comment by cbuescher** [comment]
@jpountz working on this, while adding tests to QueryPhaseTests, I discovered the following section in Lucenes IndexSearchers#count method: https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L339
This covers the MatchAllDocsQuery and TermQuery in much the same way as `TopDocsCollectorContext#shortcutTotalHitCount` but could also benefit from addind a section handling the DocValuesFieldExistsQuery, wdyt?

**Comment by jpountz** [comment]
Unfortunately this optimization is unsafe for Lucene because Lucene doesn't enforce that you are indexing the same data in an indexed and a doc-value field that share the same name. This is something that Elasticsearch enforces however: if a field is indexed and doc-valued, then indexed documents are exactly the same as doc-valued documents.

**Comment by cbuescher** [comment]
Thanks, thats unfortunate. Do we wrap or overwrite Lucenes IndexSearch in ES in a consistent way somewhere so we could add this optimization only on our side?

**Comment by jpountz** [comment]
@cbuescher We never use IndexSearcher#count to my knowlegde (maybe we should make it a forbidden API in a separate change?). Counting only occurs in `TopDocsCollectorContext#shortcutTotalHitCount`.
