### ISSUE TITLE
[CI] AckClusterUpdateSettingsIT.testOpenIndexNoAcknowledgement failure in 6.x.

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37478]
Console log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1009/console

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=DDCD0CFE4089823B \
  -Dtests.class=org.elasticsearch.cluster.ack.AckClusterUpdateSettingsIT \
  -Dtests.method="testOpenIndexNoAcknowledgement" \
  -Dtests.security.manager=true \
  -Dtests.locale=ru \
  -Dtests.timezone=MST7MDT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Error:
```
14:55:53 FAILURE 1.02s J1 | AckClusterUpdateSettingsIT.testOpenIndexNoAcknowledgement <<< FAILURES!
14:55:53    > Throwable #1: java.lang.AssertionError: 
14:55:53    > Expected: <true>
14:55:53    >      but: was <false>
14:55:53    > 	at __randomizedtesting.SeedInfo.seed([7ABE71845CCEB933:3E81959B91F9E62B]:0)
14:55:53    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:55:53    > 	at org.elasticsearch.cluster.ack.AckClusterUpdateSettingsIT.testOpenIndexNoAcknowledgement(AckClusterUpdateSettingsIT.java:171)
14:55:53    > 	at java.lang.Thread.run(Thread.java:748)
```

Couldn't manage to reproduce locally (40 iterations)

Failed once again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/984/console

**Comment by costin** [comment]
Still happening on the CI
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1110/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/586/console

**Comment by droberts195** [comment]
This happened again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1149/console

I muted the test in 6.x in 20bf1ebecd006cac9f62699f2fa730fffe1289c9

**Comment by tlrx** [comment]
This is the same issue as #32767 and #34053. I'm going to disable all the tests in AckClusterUpdateSettingsIT (as it has been done in master) and add a note to #33673.
