### ISSUE TITLE
Include plugins with each elasticsearch/logstash installation for ease of use in air gapped network

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#37476]
Hi, 

Please can you bundle the correct version of each elasticsearch and logstash plugin with each install. For the sake of saving 100MB disk space, it is annoying to do offline install when we run a cluster in an airgapped network. As we add more clients and run multiple clusters, doing multiple offline installs on each cluster is going to become more of a chore. Bundling the plugins with each install will make it easier for us to when we upgrade or deploy a new cluster.

Thanks

**Comment by jasontedor** [comment]
Sorry, but which plugins are you asking specifically? And either way, we are unlikely to do this because everyone is going to have a different set of plugins that they would want included in such packaging.

**Comment by jasontedor** [comment]
No additional feedback, closing.
