### ISSUE TITLE
clean shutdown - disable shard allocation and sync flush on node shutdown

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#37482]
Hi, 

Would it be possible to add an option to elasticsearch.yml, so when we shutdown the elasticsearch service with systemctl stop, elasticsearch catches the shutdown signal and does a graceful shutdown. Elastic could then disable shard allocation and do a sync flush before terminating, then re-enable shard allocation when it starts. 

The option in elasticsearch.yml could enable and disable this feature.

Thanks

**Comment by ywelsch** [comment]
Elasticsearch already flushes when doing a clean shutdown (SIGTERM instead of SIGKILL). Given that you're probably talking about a one node cluster, I'm not sure what you want to achieve by disabling / enabling shard allocation?

**Comment by jasontedor** [comment]
> Would it be possible to add an option to elasticsearch.yml, so when we shutdown the elasticsearch service with systemctl stop, elasticsearch catches the shutdown signal and does a graceful shutdown. 

As @ywelsch mentions, on a clean shutdown we flush. And when you stop the service with `systemctl stop`, we do a clean shutdown:

https://github.com/elastic/elasticsearch/blob/d2ef93dff175ba22406054bf78137679a0e7990c/distribution/packages/src/common/systemd/elasticsearch.service#L46-L47

**Comment by ebadyano** [comment]
No further feedback received. @mbudge if you have any further comments to the responses above please add it and we can look at re-opening this issue.
