### ISSUE TITLE
Need to elaborate on the version conflict error

### ISSUE THREAD

**Issue by jkelastic** [elastic/elasticsearch#37546]
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

The documentation should also include 

This warning is for a document that had no changes. Any other documents with changes will still get updated during this warning, source version <= destination, missing documents will get created." 

I didn't use "conflicts": "proceed", got

      "id": "HSaTemcBUPODKO5X5YBO",
      "cause": {
        "type": "version_conflict_engine_exception",
        "reason": "[test][HSaTemcBUPODKO5X5YBO]: version conflict, current version [4] is higher or equal to the one provided [1]",
        "index_uuid": "KCYr7WiDQIOnQK3XhFFgOw",
        "shard": "4",
        "index": "new_twitter"
      },
      "status": 409

My documents still got updated. From my testing it looks like we can ignore the warning.

**Comment by henningandersen** [comment]
@jkelastic I wonder if following happened: you reindexed a relatively small set of docs (one batch only?) and one of the docs failed with above error but the rest of the docs were indexed OK?

The way reindex works is by reading out a batch of docs from source and then index those docs in one bulk request. Bulk indexing does best effort, indexing all docs that can go in and returning errors for those that conflict.

If you did not specify "conflicts": "proceed" reindex will then terminate afterwards. But all docs in the last batch will have been attempted indexed.

If you agree that this explains what you saw maybe we can move to closing this issue? Or do you still feel the docs need to be more precise on this?

**Comment by jrodewig** [comment]
[docs issue triage]

Closing this issue. Please re-open if more discussion or action is needed.
