### ISSUE TITLE
Restore ability to define 3rd party endpoint in the repository-s3 plugin

### ISSUE THREAD

**Issue by Max0r** [elastic/elasticsearch#37613]
In Elastic5 it was possible to define a provider other than AWS in the repository-s3 plugin as documented [here](https://www.elastic.co/guide/en/elasticsearch/plugins/5.6/repository-s3-repository.html#repository-s3-endpoint).

This does not seem to be possible in the current release. I use a different S3 provider and would love to see that functionality return.

Thanks!

**Comment by ywelsch** [comment]
It's still possible, but is configured in a different way, [see the docs](https://www.elastic.co/guide/en/elasticsearch/plugins/6.5/repository-s3-client.html), in particular `endpoint`. Please ask questions like these on the [discuss forums](https://discuss.elastic.co), we use Github mainly for feature requests and verified bugs.
