### ISSUE TITLE
Please add a License to documentation

### ISSUE THREAD

**Issue by Kronuz** [elastic/elasticsearch#37616]
**Describe the feature**:

Elasticsearch doesn't seem to come with a specific license for the documentation, please add one to the documentation source code.

**Comment by jtibshirani** [comment]
Hi @Kronuz, the documentation is actually already licensed. Overall we treat documentation as code, which means that documentation falls under the same license as the other code with which it resides. For example, the docs in the `elasticsearch/docs` directory are licensed under Apache 2.0.

Hopefully that helps answer your question, please let us know if anything is still unclear.

**Comment by DaveCTurner** [comment]
Also asked on [the discussion forum](https://discuss.elastic.co/t/documentation-license/164852) which I think is a better place for any follow-up discussion.
