### ISSUE TITLE
Add docker packaging tests

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#37617]
Now that we have our docker distribution in the elasticsearch repo, we should add packaging tests (of some sort) that ensure the bits inside the docker distribution work as intended. This would help with changes like #37243 to allow confidence in the change.

**Comment by atorok** [comment]
Other than  checking that basic functionality is there, we don't rely have checks similar to other packaging tests for docker, so I think we should close this in favor of #38053

**Comment by atorok** [comment]
I'm going to re-open this based on the discussion we had around  #38053 and #39515. 
The mentioned  issue and PR add a minimal REST test for docker, but we decided we also want to run the relevant java packaging tests on a container running the docker image, either via changing the entry point or exec-ing into the container.  
We expect most checks that deal with file location, permissions etc to be relevant.
