### ISSUE TITLE
ElasticSearch is not honoring CORS configuration

### ISSUE THREAD

**Issue by mvid** [elastic/elasticsearch#37623]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: []

**JVM version** (`java -version`): No java version found. Running in Docker.

**OS version** (`uname -a` if on a Unix-like system): 4.9.125-linuxkit
Docker image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4

**Description of the problem including expected versus actual behavior**:

I have an ElasticSearch node that is coming up in a docker-compose cluster locally.
This is the dockerfile:

```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4

ADD elasticsearch.yml config/elasticsearch.yml
```
And this is the elasticsearch.yml:

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
http.cors.enabled: true
http.cors.allow-origin: "*"

```
I have verified that the configuration file is in the docker instance.

However, when I provide an Origin header in a request to the node (from an origin that is not the node), it returns a 403 forbidden. When I provide an origin header with Origin: "localhost:9200", I get a normal response.
When trying from a javascript client, I get
Access to XMLHttpRequest at '[http://localhost:9200/'](http://localhost:9200/%27) from origin 'http://localhost:8005' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I can't find any documentation in ElasticSearch docs about something I should be doing differently. What am I doing wrong?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a dockerfile based on an existing Elastic docker image. 
 2. Add an elasticsearch.yml with http.cors configurations enabled
 3. Start the container, send a request with an origin other than "localhost:9200"
4. Receive a 403 response

**Provide logs (if relevant)**:
No relevant logs found in the elasticsearch output

**Comment by ACPrice** [comment]
Same issue here! Would love to find a solution.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

I also tried to reproduce what you're stating but was not successful. With your configuration the following request issued from the machine where the Docker container is running, produced a valid response:

```
curl -v -H 'Content-Type: application/json' -H 'Origin: http://localhost:5555' localhost:9200/_cluster/health?pretty
```

Out of curiosity I tried a more specific CORS configuration:

```
http.cors.enabled: true
http.cors.allow-origin: "http://4.4.4.4:5555"
```

rebuilt the container and tried a positive and a negative case. First the positive case:

```
curl -v -H 'Content-Type: application/json' -H 'Origin: http://4.4.4.4:5555' localhost:9200/_cluster/health?pretty
```

worked just fine, whereas

```
curl -v -H 'Content-Type: application/json' -H 'Origin: http://4.4.4.4:9999' localhost:9200/_cluster/health?pretty
```

produced:

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET /_cluster/health?pretty HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Origin: http://4.4.4.4:9999
>
< HTTP/1.1 403 Forbidden
* no chunk, no close, no size. Assume close to signal end
<
• Closing connection 0
```

(i.e. as expected)

**Comment by TakodaS** [comment]
I have the same issue as @anilkumar2273702
