### ISSUE TITLE
I would like to contribute to this Project.

### ISSUE THREAD

**Issue by ShumailAhmed123** [elastic/elasticsearch#37640]
Hi,

My name is Shumail Ahmed and I am a Computer Science student. I am in the last year of graduation. I am writing this because I would like to contribute to this project. In university, I am studying about the "Open Source" software.
My teacher has given me a task to contribute to the GitHub in any project, which relates to my interest and according to my level of skills.
I found this project and I think I will be able to contribute to this project with some online research and with your little help.

Thanks
Shumail Ahmed

**Comment by danielmitterdorfer** [comment]
Hi @ShumailAhmed123! Thanks for your interest in Elasticsearch. Please start by reading our [contribution guide](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) and specifically the section [Contributing as part of a class](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class).
