### ISSUE TITLE
[CI] checkstyle task failed with StackOverflowError

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#37647]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/192/
Failed due to checkstyle task running into a StackOverflowError scanning `CRUDDocumentationIT.java`:

    [ant:checkstyle] [ERROR] /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java:0:
     java.util.regex.Matcher caused a java.lang.StackOverflowError for pattern '{1}' (you may be scanning a binary file instead of text?). [SnippetLength]

Did not reproduce locally with

    ./gradlew client:rest-high-level:checkstyleTest

**Comment by jakelandis** [comment]
Closing, please re-open if happens again and we can investigate more.

**Comment by original-brownbear** [comment]
I'm seeing this locally in `master` as of today.
