### ISSUE TITLE
[CI] SetPriorityActionTests has invalid test for testNonPositivePriority

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#37652]
Zero is a valid value according to the class under test but `testNonPositivePriority` is expecting an exception. 

Build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/290/console

Reproduce with:

    ./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=9FD1CC17D355FD0D -Dtests.class=org.elasticsearch.xpack.core.indexlifecycle.SetPriorityActionTests -Dtests.method="testNonPositivePriority" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=es-DO -Dtests.timezone=Asia/Katmandu -Dcompiler.java=11 -Druntime.java=8

**Comment by markharwood** [comment]
Muted in 468bae29f7df81df5d44f1e8324468584be9b3e6

**Comment by costin** [comment]
Cherry-picked the commit for 6.x in https://github.com/elastic/elasticsearch/commit/1b85b19d43a6abdf84587e6baa07eeee67332084
