### ISSUE TITLE
[CI] CompositeRolesStoreTests stalls indefinitely

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#37657]
Stalls in the `testNegativeLookupsAreCached` test.

Build:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1392/console

Reproduced with

    ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=C0AE2ED0439D26F6 -Dtests.class=org.elasticsearch.xpack.security.authz.store.CompositeRolesStoreTests -Dtests.method="testNegativeLookupsAreCached" -Dtests.security.manager=true -Dtests.locale=ja-JP -Dtests.timezone=America/Recife -Dcompiler.java=11 -Druntime.java=8

Maybe related to recent change to test subject class ff0f5402558b986756ee3a7ccceb7dd6cc514620

**Comment by markharwood** [comment]
Note happening on 6.x too: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1089/console

**Comment by markharwood** [comment]
Muted on 6.x in 08341c77dd43f037e4fa1bf98c3015a75fffa61d

**Comment by albertzaharovits** [comment]
Muted on master as well f349372fbafde7dedfbe03064e0fa7f5393
