### ISSUE TITLE
[CI] minio fails due to port clashes

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37680]
Looks like minio is failing again due to clashes with already opened port.
This seems to have been already handled through 
https://github.com/elastic/elasticsearch/issues/32701 and https://github.com/elastic/elasticsearch/issues/32208 but it still occurred in master.

For example:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1411/console
```
Unable to start the server: Port :36076 is already in use.
```

It doesn't seem like the port is hardcoded:
https://github.com/elastic/elasticsearch/blob/7394892b4c36f44d5addb2abd2dbca7453cb2d79/plugins/repository-s3/build.gradle#L205

Maybe it's a race condition when gradle runs in parallel?

**Comment by atorok** [comment]
We don't yet run this part in parallel.
It's odd that we hit a race condition here, but the code as it's written would theoretically allow for it. 
We could use the testfixtures plugin https://github.com/elastic/elasticsearch/blob/7394892b4c36f44d5addb2abd2dbca7453cb2d79/buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java
to start minio in a docker container. That would take care of port allocation and mappings.

**Comment by original-brownbear** [comment]
@atorok went for a slightly less exciting solution for now in https://github.com/elastic/elasticsearch/pull/37747 for the time being. I'd be all for using Docker here though in general :)

**Comment by original-brownbear** [comment]
Reopening this as it's still failing with the current solution, I'm on it fixing it for good in #37783 now though.

**Comment by original-brownbear** [comment]
Fix is incoming for `6.x`, will back port this today or tomorrow :)

**Comment by original-brownbear** [comment]
Fixed in 6.x via 4b6678f
