### ISSUE TITLE
latexmath elements are not rendered in docs

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#37718]
The asciidoc file includes the formula of this function:
```
===== rational
latexmath:[rational(value,k) = value/(k + value)]

[source,js]
--------------------------------------------------
"script" : {
    "source" : "rational(doc['likes'].value, 1)"
}
--------------------------------------------------
// NOTCONSOLE
```

However it is not rendered in HTML: https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-script-score-query.html#_rational.

cc @mayya-sharipova

**Comment by mayya-sharipova** [comment]
@jpountz  Thanks Adrien for noticing this.  After talking to the docs team, I have decided to use plain text instead. 
Looks like after we switch to Asciidoctor, we will be able to use `latexmath`

**Comment by jpountz** [comment]
Thanks @mayya-sharipova  for looking!
