### ISSUE TITLE
[ML] Support Composite aggregations in the datafeed

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#37757]
Composite aggregations provide a way to stream all buckets similar to scroll search. For Terms aggs this means high cardinality fields can be used in the datafeed without some of those terms being lost due to the limitation the size parameter.

**Comment by benwtrent** [comment]
For supporting composite aggs, I am working on it with the following restrictions:

- The composite agg MUST be the top level agg
- Only ONE composite agg is allowed
- The composite agg must contain exactly ONE date_histogram data source

The other aggregation restrictions of requiring a `max` agg on the timstamp field remains. 

The other bucketing sources of the composite agg can be used as fields in the detectors. Meaning having a `terms` group by source, the terms field could be a partition field or influencer. 

I am not 100% about supporting the geotile_grid data source for composite aggs. We can allow it, but there won't be any special handling yet. So the values would just be written out as `x/y/zoom` strings (just like the bucket key value).

**Comment by benwtrent** [comment]
Composite aggs for datafeeds has been added as experimental https://github.com/elastic/elasticsearch/pull/69970
