### ISSUE TITLE
Built-in role "watcher_admin" doesn't grant write access.

### ISSUE THREAD

**Issue by gecharita** [elastic/elasticsearch#37761]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --6.4.3`):

**Plugins installed**: []

**JVM version** (`1.8.0_201`):

**OS version** (`Linux Mint 18.3, Cinnamon 3.6.7, 64-bit`):

**Description of the problem including expected versus actual behavior**:

The [documentation](https://www.elastic.co/guide/en/elastic-stack-overview/6.4/built-in-roles.html) says that the **watcher_admin** role:
`Grants write access to the .watches index, read access to the watch history and the triggered watches index and allows to execute all watcher actions.`

When I get the role, I can see that there is **no write** access configured:
`
 "watcher_admin" : {
    "cluster" : [
      "manage_watcher"
    ],
    "indices" : [
      {
        "names" : [
          ".watches",
          ".triggered_watches",
          ".watcher-history-*"
        ],
        "privileges" : [
          "read"
        ]
      }
    ]
`

**Comment by tvernum** [comment]
This is a docs issue.
`watcher_admin` has never granted write access to `.watches` (despite what the docs say).

See: https://github.com/elastic/elasticsearch/commit/71852c72151fadf69319eb3185fe666f1675b5b0/

**Comment by albertzaharovits** [comment]
Closed in https://github.com/elastic/stack-docs/pull/190
