### ISSUE TITLE
SQL: add sql protocol tests for txt, csv and tsv formats

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#37771]
Apart from the JSON, YAML, CBOR and SMILE formats, es-sql can also return results in txt, csv or tsv formats. Tests need to be added to `SqlProtocolTestCase` to include these formats, as well.

Left-over from https://github.com/elastic/elasticsearch/issues/36882.

**Comment by wchaparro** [comment]
Superceded by ES|QL
