### ISSUE TITLE
SQL: Optimize HISTOGRAM(CAST(some_datetime AS DATE))

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37776]
For:
```
SELECT HISTOGRAM(CAST(some_datetime AS DATE)) as h, count(*) FROM t GROUP BY h
```
There is no need to create a painless script to implement the casting.
The `QueryTranslator` already calculates an interval that its a multiple of days.
The CAST is still needed for the outputs of the projection though since the user needs to receive
dates and not datetimes.

**Comment by wchaparro** [comment]
Superceded by ES|QL
