### ISSUE TITLE
LoggerMessageFormat overloading of format() mixup

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37806]
There are two signature for format:
`public static String format(final String messagePattern, final Object... argArray)`
`public static String format(final String prefix, final String messagePattern, final Object... argArray)`

When trying to call: 
```
String samVar = "awesome";
format("my {} message", samVar);
```
you're calling the 1st one, because of the String there, instead of the second and the result would be:
```
my {} messageawesome
```
So to call it correctly for this case you need:
```
format(null, "my {} message", samVar);
```

Can we change the name of the 1st one to something like `formatWithPrefix` to avoid this behaviour?

**Comment by pgomulka** [comment]
relates #https://github.com/elastic/elasticsearch/issues/20987
possibly we will remove it

**Comment by pgomulka** [comment]
duplicate of https://github.com/elastic/elasticsearch/issues/20987
