### ISSUE TITLE
IndexShardIT#testMaybeFlush can fail with an assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37896]
I'm unfortunately not able to reproduce the failure locally. It looks like this failure has popped up several times in the past week.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/203

Command to reproduce: 
```
./gradlew :server:integTest \
  -Dtests.seed=3A64AFFFD9CA1AAE \
  -Dtests.class=org.elasticsearch.index.shard.IndexShardIT \
  -Dtests.method="testMaybeFlush" \
  -Dtests.security.manager=true \
  -Dtests.locale=sk-SK \
  -Dtests.timezone=America/Puerto_Rico \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
FAILURE 11.3s J2 | IndexShardIT.testMaybeFlush <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([2B2E0E5775CFD50D:AA2BF0A3B9B18341]:0)
   > 	at org.elasticsearch.index.shard.IndexShardIT.lambda$testMaybeFlush$3(IndexShardIT.java:380)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
   > 	at org.elasticsearch.index.shard.IndexShardIT.testMaybeFlush(IndexShardIT.java:377)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by jtibshirani** [comment]
I temporarily muted the test in 58301ead6d23fe943a8ea02376ff5ef99768f42b.

**Comment by dnhatn** [comment]
I looked at this failure. This test failed few times over the last two months since CI became slow. It seems that we triggered a flush, but CI was too slow to finish it in several seconds. I added the flush stats and commit stats and unmuted this test in https://github.com/elastic/elasticsearch/commit/ed460c28159172b4ea06800dc909ed72a5ace800. We should have a good clue if this test fails again.
