### ISSUE TITLE
TasksIT#testTransportBulkTasks can fail with an assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37893]
I wasn't able to reproduce this failure locally. It looks like this test first started failing yesterday, and has failed several times since then.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=virtual&&linux/202/

Command to reproduce: 
```
./gradlew :server:integTest \
  -Dtests.seed=6C5864EE064FF190 \
  -Dtests.class=org.elasticsearch.action.admin.cluster.node.tasks.TasksIT \
  -Dtests.method="testTransportBulkTasks" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-QA \
  -Dtests.timezone=NST \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Relevant excerpt from the logs:
```
FAILURE 1.84s J2 | TasksIT.testTransportBulkTasks <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<1> but was:<2>
   > 	at __randomizedtesting.SeedInfo.seed([6C5864EE064FF190:80DDA65124BCAB4B]:0)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.TasksIT.testTransportBulkTasks(TasksIT.java:345)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jtibshirani** [comment]
I temporarily muted the test in https://github.com/elastic/elasticsearch/commit/827ed1214634161742ec08c7b4dd1968dcca6b74.

**Comment by original-brownbear** [comment]
I think the correct link to the build that failed here is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=virtual&&linux/202/

**Comment by jtibshirani** [comment]
Thanks @original-brownbear for the correction, I've updated the issue description with the right link.
