### ISSUE TITLE
xpack.security.audit.logfile.events.ignore_filters not work

### ISSUE THREAD

**Issue by iwasnobody** [elastic/elasticsearch#37905]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
Linux es-master-node-3 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:
kibana .security_audit_log-* can still find audit log with roles: superuser after set the following config in elasticsearch.yml

xpack.security.enabled: true
xpack.license.self_generated.type: trial
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12
xpack.security.audit.enabled: true
xpack.security.audit.outputs: [ index ]
xpack.security.audit.logfile.events.ignore_filters.policy1.roles: [ "superuser" ]
xpack.security.authc.accept_default_password: false
xpack.ml.enabled: false
xpack.monitoring.collection.enabled: true
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by iwasnobody** [comment]
I found the config is for control audit log file in the disk. I can't find any config to control audit log index.
https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html
Is it not support right now?

**Comment by albertzaharovits** [comment]
@iwasnobody 

> I found the config is for control audit log file in the disk. I can't find any config to control audit log index.
https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html
Is it not support right now?

Yes, you are right audit ignore policies are not supported for the index audit output type, only for the logfile output type: https://www.elastic.co/guide/en/elastic-stack-overview/current/audit-log-output.html#audit-log-ignore-policy .

Moreover the index audit output type will be deprecated in 6.7 and removed in 7.
