### ISSUE TITLE
Split package between rest-client and rest-high-level-client makes it impossible to use elasticsearch clients in java 11 module path applications

### ISSUE THREAD

**Issue by tomdw** [elastic/elasticsearch#37901]
**Elasticsearch version** 6.4.3

**Plugins installed**: []

**JVM version** adoptopenjdk 11

**Description of the problem including expected versus actual behavior**:

When you want to use the java high level rest client as automatic module on the module path of jdk 11 this is made impossible. Reason is a split package between org.elasticsearch.client:elasticsearch-rest-client:6.4.3 and org.elasticsearch.client:elasticsearch-rest-high-level-client:6.4.3 with the following error as result:

`reads package org.elasticsearch.client from both elasticsearch.rest.high.level.client and elasticsearch.rest.client`

Expected design: no split packages between jars, e.g. use org.elasticsearch.client.rest and org.elasticsearch.client.high.level.rest as packages

**Steps to reproduce**:

1. create a java application on running on the module path
2. require elasticsearch.rest.high.level.client in the module-info.java
3. require elasticsearch.rest.client in the module-info.java
4. use the client
5. try to compile it with jdk 11 (using e.g. maven-compiler-plugin version 3.8.0)

**Comment by iverase** [comment]
Hi @tomdw,

Please refer to the support matrix located  here:

https://www.elastic.co/support/matrix#matrix_jvm

As you can see, jdk 11 is only supported in Elasticsearch version 6.5.x. Therefore this is a non-issue and as such, I hope you don't mind that I close this.

**Comment by iverase** [comment]
I misunderstood the issue, this is related with the client and I am not sure if this is a set up that we support. I assign the issue to the corresponding group.

**Comment by swidom-exparency** [comment]
Has there been any progress on this?  It is a problem for me too.  I have a REST API client for my app that sits on top of the Elasticsearch REST API's (both High Level and non-High Level.)  I am trying to use --patch-module without much success and am wondering if anyone has a pom.xml that they can share that resolves the JDK 11 compile issue.  There are numerous split package problems besides the REST API's too, just as an FYI.

**Comment by r862** [comment]
Is there any update on this?

**Comment by xingkuan** [comment]
i run into this issue as well. Any update?  -Thanks.

**Comment by swidom-exparency** [comment]
I have no update and never heard back from ElasticSearch.   I ended up having to go back to Java 8.
-Steve
    On Friday, June 26, 2020, 01:10:35 AM CDT, xingkuan <notifications@github.com> wrote:  
 
 


i run into this issue as well. Any update? -Thanks.

**Comment by jbaker-dstl** [comment]
Is there an update on this issue?

**Comment by UkonnRa** [comment]
+1 Any update?

**Comment by andreibaptista** [comment]
Any update?

**Comment by pugnascotia** [comment]
Hi folks. We are in the process of writing a new Java Elasticsearch client that will be separate from the Elasticsearch server codebase, which should solve these problems.

**Comment by philkra** [comment]
This is the new Java client: https://github.com/elastic/elasticsearch-java

**Comment by andreibaptista** [comment]
> Hi folks. We are in the process of writing a new Java Elasticsearch client that will be separate from the Elasticsearch server codebase, which should solve these problems.

Perfect @pugnascotia, please give us updates

**Comment by ChrisHegarty** [comment]
Hi, seems we have a new Java Client, as above, so what is the status of this issue?   ( FYI - I am in the process of preparing the Elasticsearch code base for modularization and am running straight into this split package issue, see #78166 ). What can be done in the Elasticsearch main feature branch to resolve the split package issue?

**Comment by ChrisHegarty** [comment]
The server package has been renamed to avoid collision with any rest client, see #81984

**Comment by swallez** [comment]
@ChrisHegarty so I guess we can now close this issue?

**Comment by ChrisHegarty** [comment]
No objection from me.
