### ISSUE TITLE
Completion suggest: support setting different weights per input

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#3791]
The completion suggest field mapper today only supports setting a global weight which will be the same for all inputs. It could be useful to support setting different weights per input, depending on how well they match the suggestion.

**Comment by aykut** [comment]
+1

**Comment by clintongormley** [comment]
The new completion suggester coming in 2.1.0 allows you to index an array of suggestions, each suggestion with its own weight:

    POST {INDEX_NAME}/{TYPE_NAME}
    {
    "suggest_name": [
      {
        "input": "name1",
        "contexts" : [...],
        "weight": 7
      },
      {
        "input": "name2",
        "contexts" : [...].
        "weight": 14
      }
      ]
      ...
    }

Closing

**Comment by mikeholczer** [comment]
@clintongormley did supporting indexing an array of suggestions for a document actually get in the product? I don't see it in the documentation for 2.1 nor 5.5. Also the classes in NEST nuget package don't seem to support it.

**Comment by mikeholczer** [comment]
Sorry, I do now see it in the documentation. When using NEST, I guess I would define the suggestion property of the class representing the document to be an Array of CompletionField?
