### ISSUE TITLE
SQL: support for ODBC timedate functions

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#37927]
Drivers are meant to report support for the functions implemented by the driver+data source.

Out of the timedate group, we are missing still the following:
- [x] CURRENT_DATE
- [x] CURRENT_TIME
- [x] CURDATE
- [x] CURTIME
- [x] DATE_TRUNC
- [x] DATE_PART
- [x] NOW
- [x] TIMESTAMPADD
- [x] TIMESTAMPDIFF
- [x] TODAY

See https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/time-date-and-interval-functions for details.

**Comment by astefan** [comment]
High-level view over the functions support: https://github.com/elastic/elasticsearch/issues/30007

**Comment by costin** [comment]
@matriv can you please look into adding the current variants for SQL DATE?

**Comment by matriv** [comment]
@bpintea `NOW()` is already implemented (alias to `CURRENT_TIMESTAMP()`)

**Comment by matriv** [comment]
Introducing `CURRENT_TIME/CURTIME` requires to introduce the `TIME` data type first: #38174

**Comment by matriv** [comment]
All listed functions are implemented.
