### ISSUE TITLE
FullClusterRestartIT tests and QueryBuilderBWCIT#testQueryBuilderBWC fail

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37920]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1588/console

These reproduce for me, the error is always along the lines of "The parameter include_type_name should be provided and set to false to be compatible with the next major version":

```
REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.7.0#oldClusterTestRunner \
  -Dtests.seed=A526EBB7B1417226 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testSearch" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=America/Managua \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.7.0#oldClusterTestRunner \
  -Dtests.seed=A526EBB7B1417226 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testNewReplicasWork" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=America/Managua \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.7.0#oldClusterTestRunner \
  -Dtests.seed=A526EBB7B1417226 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testShrink" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=America/Managua \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.7.0#oldClusterTestRunner \
  -Dtests.seed=A526EBB7B1417226 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testShrinkAfterUpgrade" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=America/Managua \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.7.0#oldClusterTestRunner \
  -Dtests.seed=A526EBB7B1417226 \
  -Dtests.class=org.elasticsearch.upgrades.QueryBuilderBWCIT \
  -Dtests.method="testQueryBuilderBWC" \
  -Dtests.security.manager=true \
  -Dtests.locale=it \
  -Dtests.timezone=Australia/Darwin \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by DaveCTurner** [comment]
I think this might be a consequence of other failures in `6.x` presently holding the last good commit back. In particular, 14adf8adf9ae810aea6a2831223af40b18fd098d is not yet included in the last good commit in `6.x`.

**Comment by droberts195** [comment]
> I think this might be a consequence of other failures in `6.x` presently holding the last good commit back

I've seen these tests fail in PR builds today and I don't think PR builds use last good commit?

My theory for how this is broken is that #37838 was merged to `6.x` at about the same time that #37796 was merged to `master`.  So they both passed all the PR checks with the other absent, but after merging they had to work together and didn't.  It's just a theory though, I have no proof...

**Comment by javanna** [comment]
I've seen it in two PRs in a row as well, which is why I went and muted them straight-away.

**Comment by DaveCTurner** [comment]
> I don't think PR builds use last good commit?

Apologies, yes, this is the case.

**Comment by jtibshirani** [comment]
Thank you @javanna and @martijnvg for fixing this, and sorry for these failures! I'll take a look at the fixes and may follow-up with a couple tweaks.
