### ISSUE TITLE
SQL: Implement HAVING filtering for FIRST/LAST

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37938]
Currently because of the usage of TopHits aggregation `FIRST` and `LAST` cannot be used in a `HAVING` clause of a `GROUP BY` query.

Currently TopHits aggregation don't allow bucket selectors (which is what a HAVING cause would translate to.

Relates to #35639
Depends on #73429

**Comment by faunleaf** [comment]
if this feature is pending? I think, to support this feature, new `first`/`last` aggregations should be implemented.

New `first`/`last` aggregations need two necessary fields: `value` and `time`. They maybe used as follows:

```
POST /exams/_search
{
  "size": 0,
  "aggs": {
    "last_grade": {
      "last": {
        "value": {
          "field": "grade"
        },
        "time": {
          "field": "timestamp"
        }
      }
    }
  }
}
```

Which yields a response like:

```
{
  ...
  "aggregations": {
    "last_grade": {
      "value": 70.0
    }
  }
}
```

Also, the new `first`/`last` aggregations need to be implemented like `sum`/`max`/`min` aggregations. Unlike `top_hits`, they can be used in `bucket_path` of `bucket_script`/`bucket_selector`/`bucket_sort`.

**Comment by faunleaf** [comment]
After implementing the new `first`/`last` aggregations, the `FIRST`/`LAST` function in eql can be changed to use this two aggregations.

So, to support `FIRST` and `LAST` be used in a `HAVING` clause of a `GROUP BY` query, the `bucket_selector` may help. At the same time, `bucket_sort` may help to support `FIRST` and `LAST` be used in a `ORDER BY` clause.

**Comment by caiomelo22** [comment]
Hi! Can I try to solve this issue?

**Comment by matriv** [comment]
Hi @caiomelo22 ,

Thank you for your interest in contributing!
Inline with common open source practices, we would like to no longer block and attribute issues, but rather invite anyone with a concrete proposal to simply submit a PR. No one likes duplicating work, but please consider that chances of concurrent PRs are low - especially for longer standing issues - and quality will trump over submission order.

**Comment by wchaparro** [comment]
Superceded by ES|QL
