### ISSUE TITLE
Changing date ingest processor to Java time also changes date index naming

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#37935]
The date ingest processor was changed to allow Java time formats prefixed with `8` in #37407, but the default time format is still Joda after this change.  To match what has been done for mappings in version 7 the default time format for ingest should be Java time, so that formats with and without an `8` prefix are treated identically.

I opened #37934 to make this change (as I want to test that the ML file structure finder works with it in v7).  However, while making this change I found that changing the default for date processing in ingest also affects index naming with the date index name processor.  After a brief chat with @spinscale I am raising this issue for further discussion of whether extra measures need to be taken regarding index naming by the date index name processor through the 6.x -> 7.x upgrade.  I can imagine it might cause problems for Beats?

Relates #27330

**Comment by jsoriano** [comment]
I have created an issue in Beats to track tasks around this https://github.com/elastic/beats/issues/10433

**Comment by droberts195** [comment]
We discussed this in the ES core infra meeting and it seems that there is no particular problem with the date index name processor, so I will close this issue.
