### ISSUE TITLE
SQL: return more understandable error when not grouping by a histogram

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#37952]
Testing on 6.6.0.

Consider using SQL to query for a 1-minute histogram, e.g. across a default metricbeat index (and the default time field, `@timestamp`).

```
GET /_xpack/sql?format=txt
{
  "query": """
  SELECT HISTOGRAM("@timestamp", INTERVAL 1 MINUTE) AS h FROM "metricbeat-*" GROUP BY h
  """
}
```

This correctly returns.  However, when omitting `GROUP BY ...` as in:

```
GET /_xpack/sql?format=txt
{
  "query": """
  SELECT HISTOGRAM("@timestamp", INTERVAL 1 MINUTE) FROM "metricbeat-*"
  """
}
```

We get:

```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Unknown output attribute HISTOGRAM(@timestamp){g->2644358}#2644358"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Unknown output attribute HISTOGRAM(@timestamp){g->2644358}#2644358"
  },
  "status": 500
}
```

We should clean up the error here so it's easier for a user to understand what they've done wrong.

**Comment by astefan** [comment]
master(7.0.0): https://github.com/elastic/elasticsearch/commit/6968f0925b3304a66516916cf69d4bcb9749ea30
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/4cf0391aab1bc6e6bed990121f0316179b5bbf30
6.6 (6.6.1): https://github.com/elastic/elasticsearch/commit/d05c24c2df6cb1b3e7aa11b906af991d1edfd601
