### ISSUE TITLE
SQL: SUM FUNCTION CAN NOT WORK WITH "*"

### ISSUE THREAD

**Issue by GuilleCoduri** [elastic/elasticsearch#37972]
Hi, 
Currently, multiplication within a sum is not supported.
I tried it in version 7.0-alpha. Could it be supported in later versions?

Simples use case:  `SELECT SUM(PRICE * QTY) FROM test GROUP BY XXX`

**Comment by matriv** [comment]
Closing this as a duplicate of #29980.
Currently no expression other than plain fields (columns) is allowed inside aggregate functions.
