### ISSUE TITLE
SQL: reintroduce columnar utility for internal data transfer

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37998]
Due to its tabular structure, a columnar format would suite well the edge data while offering the advantage of better data packing.
A schema of int,double,short is better packed as an array of int, one of double and one of short vs a list of the three types promoted as objects.
This utility called `Page` used to exist and we should reintroduce it back - especially for tables with a lot of columns, it will provide a more compact memory representation.

**Comment by wchaparro** [comment]
Superceded by ES|QL
