### ISSUE TITLE
Composite Aggregation using Java Rest High-level Client

### ISSUE THREAD

**Issue by mahendra-s** [elastic/elasticsearch#38020]
**Describe the feature:** ***Composite Aggregation using Java Rest High-level Client***
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4
Our solution is built using Java Rest High-level client and we are using most of all services from this library.

As of now from "org.elasticsearch.client" % "elasticsearch-rest-high-level-client" % "6.5.4" there is no way to create composite aggregation request.

Please suggest alternative solution or any plan to incorporate this function

**Comment by mahendra-s** [comment]
pinging @javanna

**Comment by javanna** [comment]
hi @mahendra-s have you tried using `CompositeAggregationBuilder`. Not sure if I am missing something but what made you think that composite aggs are not supported in the high-level REST client?

**Comment by tke** [comment]
Currently the aggregations are mostly discoverable through the `org.elasticsearch.search.aggregations.AggregationBuilders` helpers, however there isn't one for `CompositeAggregationBuilder` - this may be why @mahendra-s  hasn't found the builder?

**Comment by mahendra-s** [comment]
Correct. Thank you @javanna @tke.
