### ISSUE TITLE
Ensure 6.x BWC compatibility when searching indices with nanosecond fields

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#38028]
Once #37755 is merged we need to ensure backwards compatibility.

With the current state of #37755 there would be no BWC compatiblity, as a 6.7 coordinating node would not know the difference. The sort field would be treated as a regular numeric field.

Also the 6.7 mapping code does not know what `type: date_nanos` is. I am not sure how a 6.7 would react here.

We could implement a simple safeguard like preventing index creation if the minimum node version is below 7 or we could port the nanosecond conversion logic to 6.7.0. Maybe there are more options that I am not seeing.

Also, this might impact current CCS refactorings.

**Comment by jimczi** [comment]
IMO this is a non-issue since you shouldn't have a `nanosecond` field in a cluster that is not fully migrated to 7x ?

**Comment by jpountz** [comment]
Another option could be to document that sorting across date and nanoseconds fields is only a best-effort and only works if all data nodes are on 7.x and in the same cluster.

**Comment by spinscale** [comment]
Closing for now as we decided to pursue another strategy with the nano fieldmapper.
