### ISSUE TITLE
Update API Partial doc update some fields only if not "noop"

### ISSUE THREAD

**Issue by najdanovicivan** [elastic/elasticsearch#38057]
I am using the ElasticSearch as Database and I have documents which editors can modify in the admin panel and in order to display accurate data on reload I am sending the request with refresh='true'

I need to keep details about last modification which user modified it from what IP and Set the date when item was last time modded. Those information should not be updated if status of the document is 'noop'

What I'm currently doing is sending one request to updated without refreshing the index the data and if don't get 'noop' result I send another request to set those informations with refresh='true'

if will be great if it is possible to pass another partial document with those values which will be updated only if result is 'updated' so that there is no need to send 2 requests.  

```
....
{
  "doc":{
     "field_1" : "value 1",
     "field_2" : "value 2",
     .....
  },
 "doc-if-updated" : {
     "modder_username" : "user",
     "modder_ip" : "127.0.0.1",
     "date_modded": "1990-01-01 00:00:00"
  }
}
```
'doc-if-updated' might not be the best name for the parameter but I set it like that for the demonstration purpose

**Comment by markharwood** [comment]
Hi @najdanovicivan
I'm not certain there's a need for what you describe. Presumably you could apply any changes with a script, determining if a noop was the case otherwise including the who+when info all as part of the same single update request?

**Comment by najdanovicivan** [comment]
I know it is possible to do it via script but this having being able to pass values as parameter will make sending things much easier.

**Comment by ywelsch** [comment]
Conditional updates might be the better solution here (see `_version` field in https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html and https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docs-index_.html#index-versioning). This also prevents the case where multiple users might be concurrently editing the same data and overriding each other's changes. The UI will store the version of the document that is being displayed, and when changes to the doc are submitted to ES, you submit those conditionally on the current version being the one that was displayed to the user when making the change.

**Comment by markharwood** [comment]
@najdanovicivan - this issues has been open a while and the pessimistic locking controls that @ywelsch described look to offer the controls you'd need. 
I'm assuming this issue is now closed but can reopen if you still have a concern.
