### ISSUE TITLE
Run minimal REST tests and the core X-Pack REST tests against our Docker images

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#38053]
Today in our build we produce Docker images although our testing for them is currently minimal. We have added framework in #37754 to be able to use the images in tests. This issue is a placeholder to make it possible to run our core REST tests and core X-Pack REST tests against our Docker images. The core REST tests should be straightforward yet the X-Pack REST tests will require some orchestration since we need to add users, manipulate the keystore, set up certificates, and otherwise make it possible to run the default distribution in the way that the X-Pack REST tests expect.

**Comment by atorok** [comment]
We decided in the team that it's not worth to run the entire test suit. Instead we will only run a few minimal rest test and cover the rest with packaging tests as described in #37617.
