### ISSUE TITLE
sub index to efficiency is so slow

### ISSUE THREAD

**Issue by Mrliu-l** [elastic/elasticsearch#38082]
Es service has Twenty index. That lead to query data is too slow. Es querys data in deffierent index is asyn or 
asyn？I want to get some Resolvent.

**Comment by markharwood** [comment]
Sorry, this is not a place for general questions. It is for reporting bugs or feature requests.
Our [forums](https://discuss.elastic.co/c/elasticsearch) are the place to raise questions.
