### ISSUE TITLE
[CI] Fedora 27 packaging tests failing for 5.6

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#38092]
These have been failing for a couple of days now with the following error message:
```
not ok 238 [UPGRADE] install old version
not ok 238 [UPGRADE] install old version
# (from function `install_package' in file /project/build/bats/utils/packages.bash, line 73,
# (from function `install_package' in file /project/build/bats/utils/packages.bash, line 73,
#  in test file /project/build/bats/tests/80_upgrade.bats, line 53)
#  in test file /project/build/bats/tests/80_upgrade.bats, line 53)
#   `install_package -v $(cat upgrade_from_version)' failed
#   `install_package -v $(cat upgrade_from_version)' failed
# error: elasticsearch-5.3.3.rpm: tag[43]: BAD, tag 1096 type 5 offset 20256 count 121 len 484
# error: elasticsearch-5.3.3.rpm cannot be installed
# error: elasticsearch-5.3.3.rpm: tag[43]: BAD, tag 1096 type 5 offset 20256 count 121 len 484
# error: elasticsearch-5.3.3.rpm cannot be installed
```

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/320/console for an example

**Comment by rjernst** [comment]
This is a known issue:
https://github.com/elastic/elasticsearch/issues/34087

Unfortunately there is nothing we could do except skip these bad versions, which seems to be most of 5.x (the latest 5.6 release doesn't seem to suffer from it). I'm going to close this and propose separately shutting down this job, or making it on demand, as it pretty constantly fails and isn't useful at this point given the unlikeliness of doing another 5.6 release.

**Comment by jasontedor** [comment]
Maybe we can take a gentler approach and remove Fedora 27 and Fedora 28 from the packaging tests in the 5.6 branch?

**Comment by rjernst** [comment]
I'm fine with that. I will open a PR.
