### ISSUE TITLE
Provide an upgrade path for the .tasks index from 7.x to 8.x

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#38107]
The `.tasks` index is currently used to store information about past reindex / update-/delete-by-query requests, delete ML job actions, and index upgrade requests. As we currently only support index compatibility with the previous major ES version, upgrading across major versions might require a full reindex. For security and watcher indices, we have solved this problem by using aliases, marking indices temporarily as read-only, and then issuing a reindex, swapping the alias and removing the original index. For `.tasks`, this is a little bit more tricky as the reindex process uses `.tasks`, the index it tries to reindex.

**Comment by gwbrown** [comment]
This is addressed by https://github.com/elastic/elasticsearch/pull/78951 - in that case, since the reindex is internal, we can safely wait for completion of the reindex, and thus there's no need to create a `.tasks` document for the reindex. I'm going to close this issue.
