### ISSUE TITLE
SQL: Introduce SQL TIME type

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#38174]
ES SQL should have DataType.TIME added to describe a TIME only type to conform to ANSI SQL.

Being a new time type, all date-related functionalities would need to take it into account:

a. grouping and histograms
The latter in particular should have the max interval of 1 day
b. date-time functions
As most work on the date component this is mainly a validation task
c. date-time math
Adding or extracting an interval. Worth looking into whether DATETIME-TIME

**Comment by costin** [comment]
Thanks - let's schedule this for 7.x

**Comment by matriv** [comment]
Backported to `7.x` with 899ed2bf816b62d8f8e141b7325bb0f6ce9f5e93
