### ISSUE TITLE
REST client -  Response.getWarnings() does not decode escaped quotes

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#38189]
I ran into a failing test scenario where the Java string logged server-side with the `DeprecationLogger.deprecatedAndMaybeLog` failed to match the same string when materialized client-side using `Response. getWarnings()`.
The string in question had quotes eg:

    public static final String DEPRECATION_MESSAGE = "Don't use \"type\" please";

which is encoded to HTTP headers by the logging framework with slashes around the quotes eg `Don't use \"type\" please`
When deserialized on the client the slashes are not decoded meaning our test fails because `Don't use \"type\" please` != `Don't use "type" please`

**Comment by markharwood** [comment]
I made a start on the required decoder function but have yet to figure out where to put it. DeprecationLogger felt the most natural place alongside the encoder but the HLRC build has checks to reject classes that refer to this server-side class.
Either way a gist with the necessary function and test code is here: https://gist.github.com/markharwood/aa5215d0b7128c23d93904774a51e937

**Comment by jakelandis** [comment]
We discussed this briefly today in our team sync, and believe that best path forward here is to simply ensure we don't quotes inside quotes. Ideally use `[]` where applicable. Leaving this issue open until we are
 
* Confident that we got them all
* Have an assertion in `DeprecationLogger.deprecatedAndMaybeLog` to fail if we encounter escaped quotes

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
