### ISSUE TITLE
DocsClientYamlTestSuiteIT.test {yaml=reference/analysis/analyzers/lang-analyzer/line_1353} fails on 6.x with incorrect offset

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#38188]
Here's the relevant log:

```
  1> [2019-02-01T08:26:18,320][ERROR][o.e.s.DocsClientYamlTestSuiteIT] [test] This failing test was generated by documentation starting at reference/analysis/analyzers/lang-analyzer.asciidoc:line_1353. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
  2> REPRODUCE WITH: ./gradlew :docs:integTestRunner -Dtests.seed=D68E75796C96A039 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/analysis/analyzers/lang-analyzer/line_1353}" -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=CST -Dtests.distribution=oss-zip -Dcompiler.java=11 -Druntime.java=8
FAILURE 2.60s | DocsClientYamlTestSuiteIT.test {yaml=reference/analysis/analyzers/lang-analyzer/line_1353} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [reference/analysis/analyzers/lang-analyzer:1316]: expected:<{token=⁉, start_offset=2245, end_offset=2246, type=<EMOJI>, position=6560}> but was:<{token=⁉, start_offset=2245, end_offset=2247, type=<EMOJI>, position=6560}>
   > 	at __randomizedtesting.SeedInfo.seed([D68E75796C96A039:5EDA4AA3C26ACDC1]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:406)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:383)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: expected:<{token=⁉, start_offset=2245, end_offset=2246, type=<EMOJI>, position=6560}> but was:<{token=⁉, start_offset=2245, end_offset=2247, type=<EMOJI>, position=6560}>
   > 	at org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT$CompareAnalyzers.execute(DocsClientYamlTestSuiteIT.java:198)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:399)
   > 	... 38 more
```

This *does* reproduce on 6.x for me with:

```
./gradlew :docs:integTestRunner -Dtests.seed=D68E75796C96A039 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/analysis/analyzers/lang-analyzer/line_1353}" -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=CST -Dtests.distribution=oss-zip -Dcompiler.java=11 -Druntime.java=8
```

**Comment by polyfractal** [comment]
Took a quick look, and it appears that the "reimplemented" persian analyzer is failing because it doesn't match the actual `persian` analyzer.  It comes from this section:

```
The `persian` analyzer could be reimplemented as a `custom` analyzer as follows:

PUT /persian_example
{
  "settings": {
    "analysis": {
      "char_filter": {
        "zero_width_spaces": {
            "type":       "mapping",
            "mappings": [ "\\u200C=> "] <1>
        }
      },
      "filter": {
        "persian_stop": {
          "type":       "stop",
          "stopwords":  "_persian_" <2>
        }
      },
      "analyzer": {
        "rebuilt_persian": {
          "tokenizer":     "standard",
          "char_filter": [ "zero_width_spaces" ],
          "filter": [
            "lowercase",
            "decimal_digit",
            "arabic_normalization",
            "persian_normalization",
            "persian_stop"
          ]
        }
      }
    }
  }
}
```

Unfortunately, that exhausts my debugging skills on this one, since it dives into the composition of the analyzer itself :)

**Comment by cbuescher** [comment]
This also reproduces on current master (5e71102562b5b19940a628074a0de9de5faf43a1). I'm suprised the failure only reproduces with the given seed (D68E75796C96A039) but not with a lot of other random seeds. I didn't expect that from a test related to the documentation.

**Comment by cbuescher** [comment]
>  I'm suprised the failure only reproduces with the given seed (D68E75796C96A039) but not with a lot of other random seeds. I didn't expect that from a test related to the documentation.

After diving into the DocClientYamlTestSuiteIT a little furhter, this is explainable by CompareAnalyzers#execute testing the analyzers with a random unicode sequences separated by spaces.

**Comment by mayya-sharipova** [comment]
The problem with this symbol `\u200C` in a test string, that **SHOULD** be  substituted with space in the rebuilt Persian analyzer, but it is not.

Correcting this line `"mappings": [ "\\u200C=> "] <1>`  to `"mappings": [ "\\u200C=>\\u0020"] <1>`  in 
[lang-analyzer](https://github.com/elastic/elasticsearch/blob/master/docs/reference/analysis/analyzers/lang-analyzer.asciidoc) solves the problem.

@cbuescher  do you want to create a PR for this change in `lang-analyzer.asciidoc`?

**Comment by atorok** [comment]
This still fails on all branches: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/38

**Comment by benwtrent** [comment]
Looks like 7.0 missed the backport: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-unix-compatibility/os=ubuntu-14.04&&immutable/30/console

**Comment by markharwood** [comment]
[Build tests](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'DocsClientYamlTestSuiteIT%20AND%20test:%22test%20%7Byaml%3Dreference%2Fanalysis%2Fanalyzers%2Flang-analyzer%2Fline_1353%7D%22'),sort:!(time,desc))) link for tracking
