### ISSUE TITLE
Make it possible to use the high level rest client with modularized (jigsaw) applications

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#38299]
Right now it's not possible to write a modularized java application that talks with Elasticsearch using the High Level Rest Client.  This came out of the discussion in #28984.

Since the HLRC depends on server, the application has to `require elasticsearch` because some of the classes that one would use are in Server, like `SearchSourceBuilder`. 
This won't work because server also has an `org.elasticsearch.client` package. 
The Module system doesn't allow this. 

There are other modules that one would have to require, like `org.apache.http.HttpHost` so these will also have to work as modules.

**Comment by laurent-thiebaud-gisaia** [comment]
Any news about it, or a known workaround?

**Comment by atorok** [comment]
Sorry @laurent-thiebaud-gisaia, no updates so far. 
We do plan to work on it but can't promise anything about when that will happen.

**Comment by bsevindi** [comment]
Any updates on this?

**Comment by rtenhove** [comment]
This just bit me as well. Considering that Java 9 was released over three years ago, and JPMS is not going away, can't we please get a fix for this?

**Comment by mark-vieira** [comment]
Just to clarify, you _can_ use the HLRC in conjunction with a application that leverages JPMS, it just has to be placed on the classpath and not the module path, yes?

**Comment by tomdw** [comment]
@mark-vieira no, as soon as one of your modules on the module path uses the code of the HLRC that HLRC jar needs to be on the modulepath. Ar least as automatic module or of course as explicit module.

**Comment by mark-vieira** [comment]
Understood. We could in theory shade the elasticsearch JAR into the HLRC JAR, at which point JPMS should be happy as all the `org.elasticsearch.client` code is in the same JAR (aka module). Alpar brought up a good point, I'm not sure if the Apache HTTP client is compatible.

**Comment by mortharia** [comment]
Any updates or workaround?

**Comment by mark-vieira** [comment]
The HLRC has been replaced with the new [Java client](https://github.com/elastic/elasticsearch-java). The new client has no dependency on Elasticsearch so this is no longer an issue.
