### ISSUE TITLE
[CI] Periodic matrix tests fail FIPS8 with :x-pack:plugin:security:cli:testingConventions

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38322]
Looks like all of the recent failures are related to failing the `:x-pack:plugin:security:cli:testingConventions` task.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/

e.g. in this build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/222/consoleFull
```
11:10:51 > Task :x-pack:plugin:security:cli:testingConventions FAILED
11:10:51 Test classes are not included in any enabled task ():
11:10:51 Build cache key for task ':x-pack:plugin:security:cli:testingConventions' is 11e64d8aa2514b12ec5f552dc1b56b17
11:10:51   * org.elasticsearch.xpack.security.cli.CertGenUtilsTests
11:10:51   * org.elasticsearch.xpack.security.cli.CertificateGenerateToolTests
```

**Comment by jkakavas** [comment]
This should be resolved in https://github.com/elastic/elasticsearch/pull/38546
