### ISSUE TITLE
Docs: Drop inline callouts

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#38335]
We've [not](https://github.com/elastic/docs/pull/566) going to support inline callouts in asciidoctor. We're going to need to drop all of them from all branches of our docs before we can build them with asciidoctor. We use them fairly frequently in the SQL docs but they are rare otherwise.

**Comment by nik9000** [comment]
Inline callouts look like this:
```
----
POST <1> /_search/scroll <2>
----
<1> words
<2> other words
```

In asciidoctor all callouts have to be at the end of the line.

**Comment by nik9000** [comment]
Right *now* we don't have an enforcement mechanism to make sure that we can build the docs with asciidoctor. It wouldn't pass anyway because of a couple of this and one other strange failure in the reference docs. We also *can't* current run asciidoctor in CI, but I'm working on that too.

**Comment by nik9000** [comment]
> Maybe it's the inline callouts that are problematic but end-of-line ones are fine?

Indeed, it is just inline callouts that aren't supported. End of line callouts are just fine. It'd be a disaster not to support them. It is bad enough not to support inline callouts but getting support for them is fairly painful because there isn't a "proper" extension point for these to turn them on.

**Comment by costin** [comment]
Might be a separate thing but maybe it makes sense to raise an issue with asciidoctor - I'm curious why it isn't supported considering in general asciidoctor > asciidoc; I would assume there's some technical challenge in place?
Just curious I guess.
Anyway, is there anything the SQL team can do to help out with this issue?

**Comment by nik9000** [comment]
> Might be a separate thing but maybe it makes sense to raise an issue with asciidoctor - I'm curious why it isn't supported considering in general asciidoctor > asciidoc; I would assume there's some technical challenge in place?

I've opened it with them and they aren't too keen on it from a "this'll break things" and a "this'll slow it down" standpoint. They've left it open but I don't think I'll get an extension point to implement it any time soon.

>  Anyway, is there anything the SQL team can do to help out with this issue?

If you'd like to rewrite the bits that use an inline callout that'd be great! We'd need to backport those changes "all the way" to zap all of the callouts. That is actually fairly difficult because CI is upset about backports before 6.4 right now. I'll be working later this week to fix that up. But if you'd like to do the PRs for that it'd be lovely!

**Comment by nik9000** [comment]
I've been able to successfully backport back to 6.2. I'll work on continuing the backport of this soon!

**Comment by nik9000** [comment]
Eclipsed by #41128
