### ISSUE TITLE
NetworkDisruption.removeAndEnsureHealthy does not guarantee that all connections in the cluster are restored

### ISSUE THREAD

**Issue by andrershov** [elastic/elasticsearch#38348]
While working on `testNetworkPartitionRemovalRestoresConnections`, I've noticed that the test sometimes failed, claiming that connection between some pair of nodes is not restored.
This test calls `clearDisruptionScheme`, which in turn call `disruptionScheme.removeAndEnsureHealthy`. After this method call, it's assumed that all connection should be restored.

In the case of `NetworkDisruption` to ensure the health of the cluster two methods are called:
1) `ensureNodeCount` - this method sends health request to master nodes with awaitNodes = clusterSize. 
2) `ensureFullyConnectedCluster` - iterates over all nodes in the cluster and connects them to the nodes in their cluster state.

There are 2 expectations after `ensureNodeCount` method call:
1) Master is elected and has added disconnected nodes to the cluster state.
2) Other nodes have applied this cluster state and the second method will restore connectivity between all nodes in the cluster.

Both of them are wrong:
1) ensureNodeCount can return before the master node detects the failure during network disruption, so right after this method call cluster state can exclude the node from the cluster state.
2) Even if the master has already properly detected the failure and re-connection and ensureNodeCount returns after it, there is no guarantee that this cluster state is already applied to other nodes in the cluster.

The workaround  in `testNetworkPartitionRemovalRestoresConnections` is to use `assertBusy` when checking the state of connections, however, this is not the behaviour expected from `removeAndEnsureHealthy` method.

**Comment by mark-vieira** [comment]
It's not clear to me that this is an issue for the delivery team.

Could someone from @elastic/es-distributed comment on whether a) this is still an issue or b) whether this has build implications or is simply something that needs to be addressed in this specific test?

**Comment by pxsalehi** [comment]
Closing this since we don't see the problem happening often enough to warrant investigating the issue.
