### ISSUE TITLE
[CI] 5.6 Packaging tests fail adding Centos Box

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38356]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/332/consoleFull

The last three builds seem to have failes with:
```
12:37:05 ==> centos-6: Adding box 'elastic/centos-6-x86_64' (v20190203.0.0) for provider: virtualbox
12:37:05 The box you're attempting to add already exists. Remove it before
12:37:05 adding it again or add it with the `--force` flag.
12:37:05 
12:37:05 Name: elastic/centos-6-x86_64
12:37:05 Provider: virtualbox
12:37:05 Version: 20190203.0.0
12:37:05 :qa:vagrant:vagrantCentos6#update FAILED
12:37:05 :qa:vagrant:vagrantCentos6#update (Thread[Task worker for ':',5,main]) completed. Took 4.994 secs.
12:37:05 
12:37:05 248 actionable tasks: 248 executed
12:37:05 FAILURE: Build failed with an exception.
```

**Comment by cbuescher** [comment]
This job is still failing for the same reasons: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/344/console

**Comment by tvernum** [comment]
Still failing
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/373/console
```
02:45:29 ==> centos-6: Updating 'elastic/centos-6-x86_64' with provider 'virtualbox' from version
02:45:29 ==> centos-6: '20190127.0.0' to '20190217.0.0'...
02:45:30 ==> centos-6: Loading metadata for box 'https://vagrantcloud.com/elastic/centos-6-x86_64?access_token='
02:45:31 ==> centos-6: Adding box 'elastic/centos-6-x86_64' (v20190217.0.0) for provider: virtualbox
02:45:31 The box you're attempting to add already exists. Remove it before
02:45:31 adding it again or add it with the `--force` flag.
```

**Comment by hub-cap** [comment]
I have cleaned up the machines that recently failed. The cleanup process is to remove the box from vagrants ` ~/.vagrant.d/boxes/` folder. The fact that this happens across many nodes makes me feel suspect about it just being random. I will continue to monitor this and see if i can draw any conclusions.

**Comment by romseygeek** [comment]
Failed on an Ubuntu machine this time
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/385/console

```
==> ubuntu-1404: Adding box 'elastic/ubuntu-14.04-x86_64' (v20190217.0.0) for provider: virtualbox
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.
```

**Comment by romseygeek** [comment]
And again on Ubuntu:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/386/console

**Comment by romseygeek** [comment]
In fact it looks as though the 5.6 packaging tests have been failing with this error since the beginning of this week.

**Comment by hub-cap** [comment]
yea its not just 5.6, its any of these tests. This time it failed on ubuntu, not centos. Im investigating some automation that cleans up old vms now to see if that is the culprit. More info to come

**Comment by hub-cap** [comment]
vagrant was quite confused. I stopped all vagrant vms from the 5.6 job folder and deleted the workspace directory. it sorted itself out. Builds are green again.

**Comment by droberts195** [comment]
This failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/429/console, this time for CentOS 7:

```
11:54:05 ==> centos-7: Checking for updates to 'elastic/centos-7-x86_64'
11:54:05     centos-7: Latest installed version: 20190224.0.0
11:54:05     centos-7: Version constraints: 
11:54:05     centos-7: Provider: virtualbox
11:54:05 ==> centos-7: Updating 'elastic/centos-7-x86_64' with provider 'virtualbox' from version
11:54:05 ==> centos-7: '20190224.0.0' to '20190303.0.0'...
11:54:06 ==> centos-7: Loading metadata for box 'https://vagrantcloud.com/elastic/centos-7-x86_64?access_token=...'
11:54:07 ==> centos-7: Adding box 'elastic/centos-7-x86_64' (v20190303.0.0) for provider: virtualbox
11:54:07 The box you're attempting to add already exists. Remove it before
11:54:07 adding it again or add it with the `--force` flag.
```

It seems that the VM version is updated every few weeks and always requires manual cleanup on the Jenkins workers when this happens.  Is there a place where `--force` could be added to the build scripts to avoid this?

**Comment by hub-cap** [comment]
oh geez, again!? The `--force` I dont think works because they end up in a state where the boxes both dont and do exist depending on if you try to delete or add it (delete, does not exist, add, already exists, tableflips). This only happens on 5.6, maybe I should outline the steps for cleanup and try not to sneeze on the build as it may topple! cc @jakelandis to help with whether its worth our time to try to fix this or keep cleaning it up until 5.6 is a thing of the past.

**Comment by danielmitterdorfer** [comment]
It has failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/437/console. I agree with @hub-cap's reasoning: If this only happens only on `5.6` then it is probably ok to document the cleanup steps for the time being. I wonder whether we can be proactive about the cleanup though to avoid spurious build failures?

**Comment by danielmitterdorfer** [comment]
Another instance in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/438/console:

```

12:02:16 Successfully started process 'command 'vagrant''
12:02:18 ==> centos-6: Checking for updates to 'elastic/centos-6-x86_64'
12:02:18     centos-6: Latest installed version: 20190217.0.0
12:02:18     centos-6: Version constraints: 
12:02:18     centos-6: Provider: virtualbox
12:02:20 ==> centos-6: Updating 'elastic/centos-6-x86_64' with provider 'virtualbox' from version
12:02:20 ==> centos-6: '20190217.0.0' to '20190310.0.0'...
12:02:21 ==> centos-6: Loading metadata for box 'https://vagrantcloud.com/elastic/centos-6-x86_64?access_token='
12:02:22 ==> centos-6: Adding box 'elastic/centos-6-x86_64' (v20190310.0.0) for provider: virtualbox
12:02:22 The box you're attempting to add already exists. Remove it before
12:02:22 adding it again or add it with the `--force` flag.
```

I have removed all 5.6-related VMs with `vagrant destroy $VM_ID` on the worker `worker-862475`.

**Comment by jkakavas** [comment]
This failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/447/console, worker is ` worker-844165` , have we documented the steps to clean this up @hub-cap @danielmitterdorfer ?

**Comment by davidkyle** [comment]
2 more failures

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/449/console  (worker 844165)
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/450/consoleFull
 (worker 854308)


It looks like worker-862475 is the only machine successfully building now after @danielmitterdorfer's clean up. Can you share the steps please

**Comment by jaymode** [comment]
Another https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/460/console. Is there something we can do to make this more reliable?

**Comment by romseygeek** [comment]
And another https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/461/console

**Comment by markharwood** [comment]
Another case: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+packaging-tests/480/

**Comment by danielmitterdorfer** [comment]
> have we documented the steps to clean this up @hub-cap @danielmitterdorfer ?

As I've mentioned in https://github.com/elastic/elasticsearch/issues/38356#issuecomment-471509428, I did the following for all 5.6-related VMs (those are VMs that are located in the 5.6 Jenkins workspace):

```
vagrant destroy $VM_ID
```

To obtain the list of VMs managed by Vagrant, you can issue:

```
vagrant global-status
```

**Comment by rjernst** [comment]
Since the 5.6 CI jobs have been shut down now that 7.0 is released, I believe we can close this.
