### ISSUE TITLE
Make a Java HLRC client version of ShardsAcknowledgedResponse

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#38355]
Currently JAVA HLRC `RolloverResponse` and `CreateIndexResponse` use a server's `ShardsAcknowledgedResponse`.

per @hub-cap's comment
WRT declareAcknowledgedAndShardsAcknowledgedFields, i think we can do something client side thats small and similar? Do we have (m)any classes in o.e.client.indicies using it? Maybe we can put a parent class in o.e.client.indicies that is similar in how it functions

relates to #38039

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
