### ISSUE TITLE
Watcher: remove rest_total_hits_as_int

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#38387]
In 7.x the total hits in the search response were changed (#33028). To preserve compatibility watcher set `rest_total_hits_as_int` (#35848) to true by default to opt-out of the new response format (#36115). 

Prior to 8.x Watcher needs to define a strategy to properly deprecate, and possibly re-write existing watches to no longer have `rest_total_hits_as_int` as the default (in 7.x it can be changed per watch, but defaults to true if not set). The strategy also needs to account for any other Elastic stack components, such as monitoring and beats that may use Watcher hit counts.

**Comment by jakelandis** [comment]
Reminder to update the documentation to use total.value when this change is implemented: https://github.com/elastic/elasticsearch/pull/65874

@jimczi - are there still plans to remove and/or deprecate `rest_total_hits_as_int` for 8.0 ?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
