### ISSUE TITLE
http://example.com/ba*,-bar,-baz/_search will search over index foo

### ISSUE THREAD

**Issue by ccw-morris** [elastic/elasticsearch#3839]
Create three indexes: foo, bar, and baz.
Submit a search request using the URL: http://example.com/ba*,-bar,-baz/_search. This performs a search over all indices.

The logic of the MetaData.convertFromWildcards() method is as follows:
First token is ba* - expand that into bar and baz and add them to the result set.
Second token is a negation of bar so it removes that.
Third token is a negation of baz so it removes that to leave an empty set.

The problem is that an empty index set is also generated by http://example.com/_search.

There is later logic in PlainOperationRouting.computeTargetedShards() that treats the empty set as a request to search every index, including the index foo and the two indices that have been explicitly removed.

The proposed solution is:
1. RestSearchAction.parseSearchRequest() to detect when request.param("index") is null and to explicitly populate the indices array with "_all". Both /_all/_search and /_search then follow the exact same logical path - this may avoid future bugs.
2. PlainOperationRouting.computeTargetedShards() should treat an empty concreteIndices array as a null search.

**Comment by clintongormley** [comment]
And, this searches all indices including bar and baz:

    GET *,-bar,-baz/_search

While this search all indices except bar and baz:

    GET -bar,-baz/_search

**Comment by qwerty4030** [comment]
I was able to reproduce this on latest master with the following:
```
PUT foo/foo-type/foo-doc
{}
PUT bar/bar-type/bar-doc
{}
PUT baz/baz-type/baz-doc
{}
GET  foo,-foo/_search

response:
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "-foo",
        "index_uuid": "_na_",
        "index": "-foo"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_expression",
    "resource.id": "-foo",
    "index_uuid": "_na_",
    "index": "-foo"
  },
  "status": 404
}
```
Took a quick look at the code... l'll make a PR shortly with the fix.

@clintongormley While I was investigating this I noticed the following request resulted in a similar error:
```
GET  foo,+foo/_search

response:
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": " foo",
        "index_uuid": "_na_",
        "index": " foo"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": " foo",
    "index_uuid": "_na_",
    "index": " foo"
  },
  "status": 404
}
```
However this error is slightly different than with `GET  foo,-foo/_search`: it has `"resource.type": "index_or_alias"` instead of `"resource.type": "index_expression"`. Also notice `"index": " foo"` has a space before `foo`. I guessed this might be something to do with URL encoding and tried the following:
```
GET  foo,%2Bfoo/_search

response:
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "+foo",
        "index_uuid": "_na_",
        "index": "+foo"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_expression",
    "resource.id": "+foo",
    "index_uuid": "_na_",
    "index": "+foo"
  },
  "status": 404
}
```
This is the same error as with `GET  foo,-foo/_search` so that confirmed my suspicion. Is this a bug with ES or kibana/sense? Got the same behavior when I tried this with curl and an ES 2.3 cluster.

**Comment by qwerty4030** [comment]
Would the indices be resolved differently if the `+` was removed? If not what is the purpose of it?
`GET  foo,+foo/_search` vs `GET  foo,foo/_search`
`GET  foo,+ba*/_search` vs `GET  foo,ba*/_search`
`GET  foo/_search` vs `GET  +foo/_search`
`GET  ba*,+f*,-foo/_search` vs `GET  ba*,f*,-foo/_search`

**Comment by gerits** [comment]
There still seems to be a problem here. When I run the following query it won't work. But if I switch the position of the indices it works. 
non working: GET /-foo,*/_search
working: GET /*,-foo/_search

It seems the - sign is not interpreted correctly as in following example.
Not working: GET /-foo,+bar/_search
working: GET /-*foo,+bar/_search

This is for version 5.0.2

**Comment by javanna** [comment]
Hi @gerits yes that is correct. It's a feature, not a bug, see #20898. The negation has an effect only if there is a preceding wildcard expression. The implicit negation that we had before led to unexpected results, especially when e.g. deleting indices.
