### ISSUE TITLE
Add setting for lazily loading terms index offheap

### ISSUE THREAD

**Issue by jainankitk** [elastic/elasticsearch#38390]
Lucene is [adding support](https://issues.apache.org/jira/browse/LUCENE-8635) for loading terms index offheap using mapped files. Elasticsearch should expose settings to specify list of fields that can be initialized offheap. That will prevent JVM OOM issues for many users by loading index for big fields like "_id" offheap. For example:

<index_name>/_settings --data
'{
    "settings":{
       "index.lazily_load_fst_fields_offheap": ["_id"]
     }
}'

Is the best way to pass it though IndexWriterConfig to the underlying lucene DirectoryReader [here](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L583)? Does this setting needs to be passed from other places in the code?

**Comment by jainankitk** [comment]
Lucene 8.1 supports reader attributes via [LUCENE-8671](https://issues.apache.org/jira/browse/LUCENE-8671). Thanks @s1monw!!
Should we expose index level elasticsearch setting to control the fields which are off/on heap?

**Comment by s1monw** [comment]
I don't think we should do this on any read-write engine. I also don't think we should expose this level of granularity to the user by allowing a setting. I am already working on a solution for read-only engines to not load it by default.

**Comment by jainankitk** [comment]
>I don't think we should do this on any read-write engine. I am already working on a solution for read-only engines to not load it by default.

Thanks @s1monw for making this change. While having this as default for read-only engine is good, it is still relevant for read-write engines with low update ratio compared to read. Maybe, we can use the ratio of deleted documents to searchable documents for making that decision?

>I also don't think we should expose this level of granularity to the user by allowing a setting.

I totally agree that user should not be exposed to such granular setting. And, as mentioned [here](https://github.com/apache/lucene-solr/pull/601#discussion_r264373499) earlier, we should add cluster level/index level boolean setting, which if set, puts PK eligible fields offheap. Non PK eligible fields are anyways offheap by default.
