### ISSUE TITLE
[Enhancement Request] ILM execution metrics

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#38452]
Here are things that can help building a better GUI for administrators in order to trace ILM:

Administrators will rely on ILM to keep the costs and performance of the cluster by handling data as it ages. These are critical goals and so the administrator wants to discover:
1. **Failures** - The user wants to know how many indices are in error phase as indication to having indices that didn't progress to the right lifecycle phase and need attention. And which indices are in ERROR state. It can be beneficial to have a timestamp or time since the index got into ERROR state
2. **Progression** - It can be useful for the user to see progression for index lifecycle and identify which indices has aged data. Since in different policies there will be subsets of the phases, it might be beneficial to use the first the common indicator of time since rollover. At any given time the user would expect to have a certain number of indices that had null for time since rollover and according to the policy the number of indices that are X time after rollover
Another good thing to know is how long an action took per index.  
3. **Other interesting metrics** Knowing how many segments the were forced merged by policy for this index; how many shards were shrink by the policy for this index and how many shards were reallocated by the policy for this index is useful to see that the policy is doing significant work and achieving tidier cluster

**Comment by dakrone** [comment]
Closing this as we now have a way of tracking this information, the `.ilm-history` index, which can be used for these sort of metrics.
