### ISSUE TITLE
Default javatime string formatter in date_histo differs from joda

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#38471]
It looks like the new javatime default formatter for `date_histogram` (and maybe elsewhere?) appends the timezone verbatim to the string.  This differs from how joda did it, which was to append the offset.

Example:

```js
PUT my_index/_doc/1?refresh
{
  "date": "2015-10-01T00:30:00Z"
}

PUT my_index/_doc/2?refresh
{
  "date": "2015-10-01T01:30:00Z"
}

GET my_index/_search?size=0
{
  "aggs": {
    "by_day": {
      "date_histogram": {
        "field":     "date",
        "interval":  "day",
        "time_zone": "America/Edmonton"
      }
    }
  }
}
```

In 6.5, the default formatter for `key_as_string` returned `-06:00` as the timezone component:

```js
{
 ...
  "aggregations" : {
    "by_day" : {
      "buckets" : [
        {
          "key_as_string" : "2015-09-30T00:00:00.000-06:00",
          "key" : 1443592800000,
          "doc_count" : 2
        }
      ]
    }
  }
}
```

But on master, it now returns `America/Edmonton`
```js
{
 ...
  "aggregations" : {
    "by_day" : {
      "buckets" : [
        {
          "key_as_string" : "2015-09-30T00:00:00.000America/Edmonton",
          "key" : 1443592800000,
          "doc_count" : 2
        }
      ]
    }
  }
}

```

**Comment by spinscale** [comment]
so, the default printer is using `.appendZoneOrOffsetId()` - we should probably use something like `.appendOffset("+HH:MM", "Z")` here to be sure we do not use the zone id

**Comment by pgomulka** [comment]
we could solve this as @spinscale suggest, but should this apply to: 
- `DocValueFormat.DateTime` only? (would create a new formatter)
- `DateFieldMapper.DEFAULT_DATE_TIME_FORMATTER` ? This is the one that is being set to `DocValueFormat.DateTime` in `ValueType`
-  for the `strict_date_optional_time||epoch_millis` - the scope of change would be even bigger
- or for all formatters?

**Comment by pgomulka** [comment]
also wondering if the same should apply to parsing `formatters` . Do we expect to parse dates with zoneId instead of offset at all?
At the moment when parsing `2017-02-01T08:02:00.000-01:00`, because it has `.appendZoneOrOffsetId()`  the returned Temporal will have `zone` but it won't have `offset`. 

`TemporalQueries.offset().queryFrom(            
DateFormatters.STRICT_DATE_OPTIONAL_TIME_FORMATTER.parse("2017-02-01T08:02:00.000-01:00"))` -> null

`TemporalQueries.zone().queryFrom(
    DateFormatters.STRICT_DATE_OPTIONAL_TIME_FORMATTER.parse("2017-02-01T08:02:00.000-01:00"))` -> "-01:00"
