### ISSUE TITLE
Remove 'template field' from parsing logic in IndexTemplateMetaData

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#38502]
Parsing the `template` field has been deprecated a long time in `IndexTemplateMetaData.Builder.fromXContent(...)` method and should be removed.

Originates from: https://github.com/elastic/elasticsearch/pull/38448#issuecomment-460732375

**Comment by jakelandis** [comment]
This should only be merged to 7.x since we have some internal clients on 6.x that still use the `template` field

**Comment by PnPie** [comment]
Hello,
I created a PR for this ;)

**Comment by dakrone** [comment]
Closing this since the PR that removed it has been merged.
