### ISSUE TITLE
Some Elasticsearch CLI tools should write logs to the log file

### ISSUE THREAD

**Issue by andrershov** [elastic/elasticsearch#38522]
Currently, all Elasticsearch CLI tools are writing logs to the console.
This might be ok for the tools that are not doing destructive actions to data or metadata being stored in the cluster.
However, tools like `elasticsearch-node` and `elasticsearch-shard` can perform destructive actions.
These tools warn the user about data loss, but they leave no traces about the execution fact in the log files.
So for such kind of tools, we propose to write tool output to the log file (along with the output to the console).

There are 2 options:
1) Write to the log file, Elasticsearch itself is using.
2) Write to the dedicated tools log file.

Elasticsearch is writing a lot of logs, and the retention policy of 1 to 7 days is typical. So after this period of time, our support engineers won't be able to deduce something from the logs, because they are gone.
So our proposal is to have a dedicated log file for the tools.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
