### ISSUE TITLE
Act on version 8 related asserts

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#38556]
We have  a number of assertions for checking that we did not pump to version 8 yet. 
I am in the process of muting them thus this issue to track them.
This is necessary so we can merge #38514 and get builds going. 

- `ResyncReplicationRequest`, `MetaDataCreateIndexService`, `RemoteClusterAware` and `RemoteClusterAware` added by @jasontedor 
- `MetaStateService` added by  @andrershov

**Comment by jasontedor** [comment]
@DaveCTurner Can you clean up the last remaining version 8 assertion in the code base? It's currently commented out:

https://github.com/elastic/elasticsearch/blob/a0513217dba5d964bf176c8f409baccfbd25359b/server/src/main/java/org/elasticsearch/gateway/MetaStateService.java#L120-L125

so there's some dead code there that theoretically can be cleaned up and removed.

**Comment by jasontedor** [comment]
There's an assertion in this block of code too:

https://github.com/elastic/elasticsearch/blob/a0513217dba5d964bf176c8f409baccfbd25359b/server/src/main/java/org/elasticsearch/gateway/MetaStateService.java#L130-L153

**Comment by DaveCTurner** [comment]
Sure, I opened https://github.com/elastic/elasticsearch/pull/52412.

**Comment by DaveCTurner** [comment]
@jasontedor I merged #52646. Since you say that this was the last remaining assertions here, should we close this issue now?
