### ISSUE TITLE
SQL: support `date_nanos` data type

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#38562]
Dates with nanoseconds precision are now supported in ES and a new data type has been introduced (`date_nanos`).
SQL needs to support this type - likely, not by adding a different type (at least for the user) but by extending the precision of a particular date.

**Comment by matriv** [comment]
Once this is introduced the CURRENT_TIMESTAMP(x)/CURRENT_TIME(x) x > 3 should be also fixed and this comment should be removed: https://github.com/elastic/elasticsearch/pull/40669/files#diff-b91ca24147aa7c0d4371fa129d3e51bdR190

Also, currently the `now` stored in the `Configuration` is set with `ZonedDateTime.now(zoneId)` so the precision is microseconds. Instead, a `Clock` with duration of 1 nanosecond should be used.
