### ISSUE TITLE
Elasticsearch 7.0.0-alpha2 elasticsearch-plugin \Common is not expected at this time.

### ISSUE THREAD

**Issue by krisavi** [elastic/elasticsearch#38578]
**Elasticsearch version**
Version: 7.0.0-alpha2, Build: unknown/unknown/a30e8c2/2018-12-17T12:33:32.311168Z, JVM: 1.8.0_172

**JVM version**
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

**OS version** 
Windows Server 2012 R2 Datacenter

**Description of the problem including expected versus actual behavior**:
Expected to have plugin installed like it worked in previous version.

**Steps to reproduce**:
Upgraded from 6.3.2 to 7.0.0-alpha2 and during install when used old config it ran into errors. 
Turned off geoip ingest plugin let the install to finish. Thought I can enable it again after install, but it seems it is not working. 
```
>"C:\Program Files\Elastic\Elasticsearch\7.0.0-alpha2\bin\elasticsearch-plugin.bat" install ingest-geoip
\Common was unexpected at this time.
```
Did not upgrade Java, from google search it seemed that at some point java update caused similar issues, but this time Java was not updated.
Not sure if it is due to this error, but new version does not start.
```
[2019-02-07T17:30:24,021][ERROR][o.e.b.Bootstrap          ] [TDOSNELIN016] node validation exception
[1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.zen.ping.unicast.hosts, discovery.zen.hosts_provider, cluster.initial_master_nodes] must be configured
[2019-02-07T17:30:24,025][INFO ][o.e.n.Node               ] [TDOSNELIN016] stopping ...
[2019-02-07T17:30:24,126][INFO ][o.e.n.Node               ] [TDOSNELIN016] stopped
[2019-02-07T17:30:24,126][INFO ][o.e.n.Node               ] [TDOSNELIN016] closing ...
[2019-02-07T17:30:24,144][INFO ][o.e.n.Node               ] [TDOSNELIN016] closed
[2019-02-07T17:30:24,149][INFO ][o.e.x.m.p.NativeController] [TDOSNELIN016] Native controller process has stopped - no new native processes can be started
```

**Comment by krisavi** [comment]
Tracing it a bit down the rabbithole, it seems there is issue with elasticsearch-env.bat
When running elasticsearch-cli.bat manually last rows are:
```bat
>set ES_DISTRIBUTION_TYPE=zip
\Common was unexpected at this time.
>  for /f "tokens=* usebackq" %a in (`""C:\Program Files (x86)\Common Files\Oracle\Java
\javapath\java.exe" -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory""`) do set
 ES_TMPDIR=%a
```
These are coming from elasticsearch-env.bat

```bat
set ES_DISTRIBUTION_TYPE=zip

if not defined ES_TMPDIR (
  for /f "tokens=* usebackq" %%a in (`"%JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory""`) do set ES_TMPDIR=%%a
)
```
There seems to be extra " before %JAVA% and also one after "org.elasticsearch.tools.launchers.TempDirectory"
Since inner quotation is not escaped, it will cause problems with starting and ending string values.

I got it to work by changing last rows in elasticsearch-env.bat to
```bat
if not defined ES_TMPDIR (
  for /f "tokens=* usebackq" %%a in ('%JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory"') do set ES_TMPDIR=%%a
)
```
using ' instead of \`" and "`

**Comment by Mpdreamz** [comment]
Thanks for reporting this @krisavi a quick reproduction failed on my end though.

Using `JAVA_HOME`: `"C:\Program Files\Java\jdk-11.0.1\bin\java.exe"`

```
"c:\Temp\elasticsearch-7.0.0-alpha2 space\bin\elasticsearch-plugin.bat" install ingest-geoip
```

Installs fine on my end. Both `ES_HOME` and `JAVA_HOME` having spaces in their paths. 

Will try and mimic your environment more closely next

**Comment by Mpdreamz** [comment]
Can reproduce if no `JAVA_HOME` is set and is inferred from the `java.exe` location in `PATH`.

**Comment by Mpdreamz** [comment]
Thanks again for reporting @krisavi I've opened https://github.com/elastic/elasticsearch/pull/38624 to address this applying your fix.
