### ISSUE TITLE
[CI] IndexActionTests.testIndexActionExecuteSingleDoc Fails

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#38581]
2> REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:unitTest -Dtests.seed=CEACAAD7B7542031 -Dtests.class=org.elasticsearch.xpack.watcher.actions.index.IndexActionTests -Dtests.method="testIndexActionExecuteSingleDoc" -Dtests.security.manager=true -Dtests.locale=es-419 -Dtests.timezone=Africa/Abidjan -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.05s | IndexActionTests.testIndexActionExecuteSingleDoc <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: map containing ["@timestamp"->"2019-02-07T17:18:30.820305Z"]
   >      but: map was [<@timestamp=2019-02-07T17:18:30.820Z>, <foo=bar>]
   >    at __randomizedtesting.SeedInfo.seed([CEACAAD7B7542031:7903D0E951B5DC99]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.watcher.actions.index.IndexActionTests.testIndexActionExecuteSingleDoc(IndexActionTests.java:330)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tbrooks8** [comment]
It is possible that the fix for this is related to https://github.com/elastic/elasticsearch/issues/38511.

**Comment by atorok** [comment]
This failed again in intake : https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch+master+intake/1935/console

**Comment by pgomulka** [comment]
I mute that in master, 7.0 and 7.1 until fixed
