### ISSUE TITLE
[CI] RetentionLeaseIT.testRetentionLeasesSyncOnRecovery Fails

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#38588]
```
./gradlew :server:integTest \
  -Dtests.seed=293744DFE76BD608 \
  -Dtests.class=org.elasticsearch.index.seqno.RetentionLeaseIT \
  -Dtests.method="testRetentionLeasesSyncOnRecovery" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-HN \
  -Dtests.timezone=America/Lima \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/228/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/228/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-28/229/console

**Comment by dimitris-athanasiou** [comment]
Another occurrence in `6.7`: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=sles-12/4/console

There is an open PR for muting this: #38589
