### ISSUE TITLE
Support for splitting segments across multiple locations

### ISSUE THREAD

**Issue by jensfogh** [elastic/elasticsearch#38612]
I have some large indices, where ~70-80% of the storage is used by the stored fields (_source).
My idea is to use, something similar to lucenes [FileSwitchDirectory](https://lucene.apache.org/core/4_6_0/core/org/apache/lucene/store/FileSwitchDirectory.html) to move the stored fields file (.fdt) to another file location.

The indices is running in a cloud setup, thus the reason for wanting to move 70-80% of the indices, is to place them on slower but cheaper disks.
The reason I dont want to move the entire indices to slower disks, is because I would expect the performance penalty to be significantly smaller, if we can keep everything except the stored fields on the faster disks.
This because the stored fields only are used, when returning results, and it would thus only be for i.e. the top 10 hits it would be required to go to the cheaper slower disks.

As the stored fields are such a large percentage of the required storage, I think it would be a nice compromise to enable.

[Reference to forum discussion on this topic](https://discuss.elastic.co/t/is-it-possible-to-move-fdt-file-to-external-disk/167139)

**Comment by DaveCTurner** [comment]
We discussed this today as a team and concluded that this idea has merit but would on balance be a bad idea. We rely heavily on the detailed semantics of the filesystem to operate on the files under each shard as a whole, and splitting the files across multiple filesystems would make this tricky-to-impossible to do correctly. In the distant past we _did_ allow shards to span disks and some of us still bear the scars of the bugs that arose from that 🐛
