### ISSUE TITLE
Remove the "xpack" namespace from the REST API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#38623]
@Mpdreamz noticed that some APIs still include the "xpack" namespace in their name. We should remove it. See https://github.com/elastic/elasticsearch/tree/7.x/x-pack/plugin/src/test/resources/rest-api-spec/api.

Relates #35958

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch/pull/38625 to address this.
