### ISSUE TITLE
Index lifecyle error

### ISSUE THREAD

**Issue by TrueBurn** [elastic/elasticsearch#38647]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.6.0, Build: default/deb/a9861f4/2019-01-24T11:27:09.439740Z, JVM: 10.0.2

**Plugins installed**: 
discovery-ec2
ingest-geoip
ingest-user-agent
repository-s3

**JVM version** (`java -version`):
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I create an index template. Then create an index lifecycle policy and attach the policy to the template. I then send data via logstash and the index is created attached the index template and policy but then I get an index lifecycle error. (illegal_argument_exception: index.lifecycle.rollover_alias [prod-zgapplication] does not point to index [prod-zgapplication])

**Steps to reproduce**:

Index Template:
`
{
  "order": 0,
  "version": 1,
  "index_patterns": [
    "prod-zgapplication*"
  ],
  "settings": {
    "index": {
      "lifecycle": {
        "name": "prod-zgapplication",
        "rollover_alias": "prod-zgapplication"
      },
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "message_field": {
            "path_match": "message",
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "norms": false
            }
          }
        },
        {
          "string_fields": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "norms": false,
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      ],
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "@version": {
          "type": "keyword"
        },
        "geoip": {
          "dynamic": true,
          "properties": {
            "ip": {
              "type": "ip"
            },
            "location": {
              "type": "geo_point"
            },
            "latitude": {
              "type": "half_float"
            },
            "longitude": {
              "type": "half_float"
            }
          }
        }
      }
    }
  },
  "aliases": {}
}
`

Index Lifecycel policy:
`
{
    "policy": {
        "phases": {
            "hot": {
                "min_age": "0ms",
                "actions": {
                    "rollover": {
                        "max_age": "30d",
                        "max_size": "50gb"
                    }
                }
            },
            "delete": {
                "min_age": "30d",
                "actions": {
                    "delete": {}
                }
            }
        }
    }
}
`

Logstash output:
`
output {
    elasticsearch {
		hosts => [***]
		index => "prod-zgapplication"
		ilm_enabled => true
		ilm_rollover_alias => "prod-zgapplication"
		ilm_pattern => "{now/d}-00001"
		ilm_policy => "prod-zgapplication"
	}
}
`

Index Settings:
`
{
  "index.blocks.read_only_allow_delete": "false",
  "index.priority": "1",
  "index.query.default_field": [
    "*"
  ],
  "index.write.wait_for_active_shards": "1",
  "index.lifecycle.name": "prod-zgapplication",
  "index.lifecycle.rollover_alias": "prod-zgapplication",
  "index.refresh_interval": "5s",
  "index.number_of_replicas": "1"
}
`
Error screenshot
![image](https://user-images.githubusercontent.com/38687879/52503509-677d8180-2bee-11e9-8d82-bf19ec29759a.png)

**Comment by dakrone** [comment]
Hi @TrueBurn,

We reserve Github issues for feature requests and bug reports. The issue here is that you have set the alias setting to tell ILM which alias to use, but have not created the alias. You should create the index with the setting:

```json
"aliases": {
  "prod-zgapplication":{
    "is_write_index": true
  }
}
```

For the future, please use https://discuss.elastic.co for issues like this!
