### ISSUE TITLE
[CI] SimpleClusterStateIT testIndicesOptions failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#38745]
This has failed twice over the last week: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/223/console

and then again today in a PR

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8010/console

The failure is the same: 
```
20:17:29 FAILURE 0.75s J0 | SimpleClusterStateIT.testIndicesOptions <<< FAILURES!
20:17:29    > Throwable #1: java.lang.AssertionError: 
20:17:29    > Expected: is <1>
20:17:29    >      but: was <2>
20:17:29    > 	at __randomizedtesting.SeedInfo.seed([816343E7777D5AE4:407A45CD64145436]:0)
20:17:29    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
20:17:29    > 	at org.elasticsearch.cluster.SimpleClusterStateIT.testIndicesOptions(SimpleClusterStateIT.java:264)
20:17:29    > 	at java.lang.Thread.run(Thread.java:748)
```

but this doesn't reproduce locally with the same seed

**Comment by talevy** [comment]
I've opened #38752 to help us understand why this failed since all we know is that
the index was not closed:

```
 1> [2019-02-05T07:20:00,429][INFO ][o.e.c.m.MetaDataIndexStateService] [node_s0] closing indices [fuu/I2r-FpYFTFCQsXqQRwkoYQ]
  1> [2019-02-05T07:20:00,588][INFO ][o.e.c.m.MetaDataIndexStateService] [node_s0] completed closing of indices []
```

**Comment by ywelsch** [comment]
This test hasn't failed in recent months, and is possibly fixed by other improvements -> closing.
