### ISSUE TITLE
SQL: Use doc value only for dates, potentially keyword, use _source for everything else

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#38776]
For better support of sparse data, outside dates (which are tricky due to date formatting) and potentially keywords (due to potential use of normalizers), numbers and strings (`text`) should be picked from the source.
Source is already used for `text` which means when one such field is used, the underlying source is already uncompressed; skipping doc values for such cases would not incur any significant cost.
Further more for large mappings, this would minimize the amount of docvalues needed.

**Comment by astefan** [comment]
I think this one is not valid anymore, following the merge of https://github.com/elastic/elasticsearch/pull/44062.
