### ISSUE TITLE
default to strict dynamic types when dynamic mapping is disabled

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch#3877]
When dynamic mapping is disabled (`index.mapper.dynamic: false`), I think it would be good to default all types to `dynamic: strict` so unknown fields won't cause a dynamic mapping update.

I was just mixed up by this because I thought disabling dynamic mapping would prevent new fields from being created, not just new types.  The combination of disabled dynamic mapping and a strict dynamic setting is what I thought the default was.

At the very least, we should document strict dynamic on the dynamic mapping page so one could see that is also required to prevent dynamic field mapping.  Currently the strict dynamic documentation is buried in the object type docs.

**Comment by clintongormley** [comment]
Given that this hasn't happened yet, the docs have been improved, and we're planning on removing types (https://github.com/elastic/elasticsearch/issues/15613), i'm going to close this issue
