### ISSUE TITLE
Faster inner hits when collapsing/sorting by same field

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#38778]
Hi,

I don't really know how collapse works underneath, but if it does like I guess, then this optimization should work. 

How I think it works:
Build a bitset after all the filter/sort is done. 
Go through the bitset and get the doc_value of `collapse_field` which isn't yet in `collapse_values` until you reach the `limit`.
Then for each `collapse_value` do another query with `{term: {collapse_field: collapse_value}}` and changing the `sort`.

Reason: the query/filter is too expensive to repeat for each inner_hits.

Solution: (only when collapse+sort on same field.
When you build the first bitset,  it's already filtered+sorted. So instead of keeping only `top_doc()` for each `collapsed_value` now you keep `top_docs(x)`. And then you can resort each innerhits in-memory since they're small.

Example query below:

```
GET /twitter/_search
{
    "query": {},
    "collapse" : {
        "field" : "user", 
        "inner_hits": {
            "name": "last_tweets", 
            "size": 5, 
            "sort": [{ "date": "asc" }] 
        },
        "max_concurrent_group_searches": 4 
    },
    "sort": ["user"]
}
```

Hope it makes sense.

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

>I don't really know how collapse works underneath, but if it does like I guess, then this optimization should work.

That's not how it works I'm afraid. However if you're interested in the implementation details [this ](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/apache/lucene/search/grouping/CollapsingTopDocsCollector.java) is probably the best place to start.

If you have further questions about implementation details the more appropriate forum would be to open a topic on the [forums](https://discuss.elastic.co/) 

Closing this issue (although feel free to re-open if you have demonstrable performance enhancements!)
