### ISSUE TITLE
Bug: "bin/elasticsearch --version" kills elasticsearch's main process

### ISSUE THREAD

**Issue by redlus** [elastic/elasticsearch#38786]
After running "bin/elasticsearch --version" on a dedicated master node or on a dedicated data node (on separate occasions) kills elastic's main process.

**Elasticsearch version**:
6.3.2

**Plugins installed**:
ingest-geoip
ingest-user-agent
mapper-murmur3
mapper-size
repository-azure
repository-gcs
repository-s3

**JVM version**:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**OS version**:
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
All elasticsearch nodes are running on Docker containers under Kubernetes. Connecting to a node using `"kubectl exec -it POD_NAME bash"` and then running `"bin/elasticsearch --version"` kills the process with the following message:
```
[root@tier1-elasticsearch-warm-0 elasticsearch]# bin/elasticsearch --version
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Killed
command terminated with exit code 137
```

[Docker documentation states](https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137) this exit code is the result of a kernel `kill -9`.

Needless to say, this is odd behavior, especially considering it is the documented way to check elasticsearch's version before reporting an issue here 😲

**Comment by jasontedor** [comment]
Are you applying memory limits to the container, and what are they? What have you configured the heap size to?

**Comment by redlus** [comment]
Hey @jasontedor
The master is running on m5.xlarge (4 cores and 16gb memory) with 8gb of heap. The warm nodes are running on r5.xlarge (4 cores and 32gb memory) with 24gb heap. None of them have any memory limitation for the memory nor cpu.

**Comment by jasontedor** [comment]
That is enough to get in trouble here. Running Elasticsearch with an 8 GB heap, and then starting *another* Elasticsearch process to get the version will also use an 8 GB heap. If things like swap are disabled, that is not going to fit. Similarly for the 24 GB twice into 32 GB case. I am hesitant to try to trap this in `bin/elasticsearch` because parsing options is done within Elasticsearch, and needs to be that way, and I would not want to duplicate the logic in the shell scripts.

**Comment by redlus** [comment]
Thanks for the quick reply.
Running an instance of elasticsearch (with all the requested resources) just to get the version is odd in my opinion, but I understand your point in not wanting to trap it in bin/elasticsearch. If this is not going to change, I'd consider amending the documentation here when submitting a new issue - and ask to get the version using an HTTP GET request to one of the nodes in the cluster.

**Comment by not-napoleon** [comment]
I'm removing the `feedback_needed` label here since it looks like our questions were answered.

**Comment by pugnascotia** [comment]
@rjernst is this issue addressed now that the CLI is implemented in Java, option handling happens in the CLI, and we set CLI-specific JVM options for a small heap etc?

**Comment by rjernst** [comment]
Yes, this should be addressed by the cli refactoring. Running any command on the cli now starts with a small heap, so it should not cause OOM the way it used to.
