### ISSUE TITLE
Problems importing :libs:elasticsearch-ssl-config project in Eclipse

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38800]
I have encountered this problem since the `libs/ssl-config/` project was added a few weeks ago when trying to import this and dependent subprojects. 

## Things I did to reproduce:
* checkout a clean clone of the elasticsearch repo
* run `./gradlew eclipse` (this currently uses Gradle Version 5.1.1)
* "import existing projects" in Eclipse

## Symptoms:
* the generated `libs/ssl-config/src/main/.classpath` file is missing a section defining the code "src" directory and an entry for the dependency on the `:libs:core` project:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="output" path="build-eclipse"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
</classpath>
```
* as a consequence, the `:modules:reindex` project is missing classes that should get imported from `libs/ssl-config/` (e.g. PemKeyConfig etc..)

## Current workaround:
* after manually adding the "java" directory and adding a project dependency to ":lib:core" to the project, the Eclipse workspace looks fine. This changes the `libs/ssl-config/src/main/.classpath` file to look like the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="java"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry combineaccessrules="false" kind="src" path="/:libs:core"/>
	<classpathentry kind="output" path="build-eclipse"/>
</classpath>
```
My Eclipse Version: 2018-12 (4.10.0)

The workaround  currently works for me but it would be nice to get this fixed so people (expecially external contributors) can import the project after just running `./gradlwe eclipse`.

**Comment by atorok** [comment]
Fixed in #39074
