### ISSUE TITLE
[Docs]Clarify that snapshot and restore "compatibility" is not a replacement for proper migration steps

### ISSUE THREAD

**Issue by adoerrES** [elastic/elasticsearch#38816]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.0

**Plugins installed**: [] N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): All supported ones

**Description of the problem including expected versus actual behavior**:

The documentation for Snapshot and Restore [says the following](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_version_compatibility) about versions and compatibility:

```
A snapshot contains a copy of the on-disk data structures that make up an index. This means that snapshots can only be restored to versions of Elasticsearch that can read the indices:

    A snapshot of an index created in 5.x can be restored to 6.x.
    A snapshot of an index created in 2.x can be restored to 5.x.
    A snapshot of an index created in 1.x can be restored to 2.x. 
```

...and some users are interpreting the statement `A snapshot of an index created in 5.x can be restored to 6.x.` to mean that this can be used as a migration path to upgrade Elasticsearch.  

That is, some interpret this to mean they do not need to manually address the breaking changes between 5.3 and 6.6 (for example), and that they do not need to take steps like running the Upgrade Assistant to address changes in the system indices, etc.

It would be helpful if the cited portion of the documentation above could clarify that "compatibility" is simply referring to Elasticsearch being able to read the older version's Lucene index version - and "compatibility" does not mean that a snapshot / restore between versions will automatically resolve all required migration steps and breaking changes.  The proper [migration documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) should still be followed for that.

**Comment by DaveCTurner** [comment]
Thanks @adoerrES, seems like a reasonable request. Would you care to open a PR with your suggested changes?
