### ISSUE TITLE
Modify core storage of Elastic search

### ISSUE THREAD

**Issue by code4passion** [elastic/elasticsearch#38820]
I am new to ES project and i am trying to understand the code.  What am trying to do is instead of ES writing to DISK, i want to write to some other place. Ex amazon S3. I know that this is not ideal, but I have my own reasons for this. 

Can someone point me to the code where i can start changing this? Any guidance will he helpful.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
