### ISSUE TITLE
CI builds fail when targeting the 5.5 branch

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#38823]
I'm trying to backport for documentation fixes back to 1.3. I've got back as far as 5.5. Now the builds are failing because they can't load the env variables from the `.ci/java-versions.properties`:
```
18:15:35 [EnvInject] - Injecting environment variables from a build step.
18:15:35 [EnvInject] - [ERROR] - The given properties file path '.ci/java-versions.properties' doesn't exist.
18:15:35 [EnvInject] - [ERROR] - Missing file path was resolved from pattern '.ci/java-versions.properties' .
18:15:35 [EnvInject] - [ERROR] - Problems occurs on injecting env vars as a build step: java.io.IOException: The given properties file path 
```

Should we make these files just to make CI happy? Should I try and skip this on versions that far back? I'm not sure I have the right kind of control for that though....

**Comment by jasontedor** [comment]
@nik9000 No need for backport PRs here, use your best judgement and cherry-pick and push.

**Comment by nik9000** [comment]
Got it!
