### ISSUE TITLE
ActionResponse should implement ToXContentObject

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#3889]
He should across the board implement `ToXContent` and all responses should implement is without surrounding `start/endObject`. I started doing one of them in this PR: https://github.com/elasticsearch/elasticsearch/pull/3871 but as @martijnvg pointed out we should have all of them being consistent about it.

**Comment by clintongormley** [comment]
@s1monw @javanna @cbuescher Have we made progress on this? Is there still more work to be done?

**Comment by javanna** [comment]
We didn't make any progress, I think it's still a nice to have, not super important though. In theory it should be about moving `ToXContent` response creation code from `RestAction`s to `ActionResponse`s.

**Comment by javanna** [comment]
Also some related bits [here](https://github.com/elastic/elasticsearch/issues/16347#issuecomment-183332285)

**Comment by javanna** [comment]
This is related to the parsing effort we have been making for the High Level REST Client. We can definitely fix it as we go. @tlrx what do you think?

**Comment by tlrx** [comment]
I agree, would be nice to fix that.

**Comment by javanna** [comment]
I updated the title of this issue as at this point ActionResponse should implement `ToXCOntentObject` and not `ToXContent`

**Comment by rjernst** [comment]
We discussed this issue in core/infra today. While it is certainly an admirable goal, and may be nice to have, forcing all ActionResponses to have xcontent representations has not been a priority for over 7 years. In practice, the responses that need xcontent get it through other subclasses, and transport actions are often separated from the REST side that needs xcontent, so in many cases it is not necessary. Given that, we don't plan to work on this.
