### ISSUE TITLE
Explore Littles Law for automatic / dynamic queue sizes

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#3890]
we currently use static defaults for queues on threadpools. It might be worth looking into things like http://en.wikipedia.org/wiki/Little's_law for the queue sizes...

**Comment by clintongormley** [comment]
@s1monw is this still of interest to you?

**Comment by s1monw** [comment]
we can close and reopen if we pick it up

**Comment by dakrone** [comment]
@clintongormley I actually had a feature branch for this from last year, though it's likely succumbed to bitrot by now.

**Comment by clintongormley** [comment]
We're reviving this effort

**Comment by aanchal9** [comment]
Is it still an issue?

**Comment by javanna** [comment]
@aanchal9 yes it is, there is a PR open that closes it (#23844). Why are you asking?

**Comment by aanchal9** [comment]
It was assigned to me on CodeTriage so I asked.

**Comment by jasontedor** [comment]
If you're looking for an issue, instead of using CodeTriage, I would recommend looking at our contributing guidelines, and finding issues that have at least the adoptme label, and the low-hanging-fruit label if you're just getting started.

**Comment by aanchal9** [comment]
Ok thanks. That is of great help. Will look into contributing guidelines.
