### ISSUE TITLE
Add limited search capabilities to snapshots

### ISSUE THREAD

**Issue by s-nel** [elastic/elasticsearch#38932]
Add limited search capabilities to snapshots

Use cases:
1. Want to find the most recent snapshot
2. Want to find the most recent _successful_ snapshot
3. Want to show a list of snapshots and page through them

When snapshots are automated to be taken periodically the number of snapshots quickly exceeds what is scalable to be retrieved in a single response with `_snapshot/<repo>/_all`

Justification:
Other operational APIs (e.g. [task APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html)) already have filtering capabilities

**Comment by DaveCTurner** [comment]
We started to discuss this today but timed out before reaching any meaningful conclusion. We will revisit it at a later date.

**Comment by ywelsch** [comment]
We had a discussion on this today and would like to gather more feedback from the community about the filtering capabilities and their use cases. We feel generally positive though about adding simple filtering capabilities (for example index names and status). Sorting is already done today by most recent snapshot first, which looks to be sufficient for the purposes outlined in the opening post.

**Comment by original-brownbear** [comment]
I think we covered effectively all of these now in some form in https://github.com/elastic/elasticsearch/issues/74350 => closing this as implemented.
