### ISSUE TITLE
reindex-client references elasticsearch-ssl-config:jar:7.0.0-beta1 which is missing in maven central

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#38944]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.0-beta1

**Plugins installed**:
none

**JVM version** (`java -version`):
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin xxx.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

**Description of the problem including expected versus actual behavior**:
reindex-client references elasticsearch-ssl-config:jar:7.0.0-beta1 which is missing in maven central

```
The POM for org.elasticsearch:elasticsearch-ssl-config:jar:7.0.0-beta1 is missing, no dependency information available

Could not resolve dependencies for project ... : Could not find artifact org.elasticsearch:elasticsearch-ssl-config:jar:7.0.0-beta1 in elastic-lucene-snapshots (http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/83f9835)
```

**Steps to reproduce**:

Try "mvn clean install" on a pom that includes

```
...
<repositories>
    <repository>
      <id>elastic-lucene-snapshots</id>
      <name>Elastic Lucene Snapshots</name>
      <url>http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/83f9835</url>
      <releases><enabled>true</enabled></releases>
      <snapshots><enabled>false</enabled></snapshots>
    </repository>
  </repositories>
...
<dependency>
      <groupId>org.elasticsearch.plugin</groupId>
      <artifactId>reindex-client</artifactId>
      <version>7.0.0-beta1</version>
</dependency>
...
```

**Comment by dadoonet** [comment]
Got the same issue. Posting here a workaround in case someone else is getting this.

```xml
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>7.0.0-beta1</version>
    <exclusions>
        <exclusion>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>reindex-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by tvernum** [comment]
The required jar file is available as `modules/reindex/elasticsearch-ssl-config-7.0.0-beta1.jar` in the elasticsearch 7.0.0-beta1 install.
It depends on elasticsearch-core (as a compile dependency) and nothing else.

The build has been corrected so this will be published to maven in future releases.
