### ISSUE TITLE
Error: [parsing_exception] [constant_score] query does not support [query]

### ISSUE THREAD

**Issue by codeashish247** [elastic/elasticsearch#38957]
"constant score query doesn't support query" error is coming when i am trying to run the following code.

```
client.search({
    index: ['index1','index2'],
    body: {
        from: 0, size: 20,
        query: {
            "constant_score": {
                boost: 1.0,
                "query": {
                    query_string: {
                        query: str,
                        fields: ['field_1']
                    }
                }
            }
        }
    },
});


```

**Comment by ebadyano** [comment]
@codeashish247 Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
