### ISSUE TITLE
Cannot apply settings to all indices

### ISSUE THREAD

**Issue by ferronrsmith** [elastic/elasticsearch#38964]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.0-beta1
**OS version** (`uname -a` if on a Unix-like system):
docker
**Description of the problem including expected versus actual behavior**:

Cannot apply settings to all indices

**Steps to reproduce**:

```bash
curl -X PUT \
  http://localhost:9200/_settings \
  -H 'Content-Type: application/json' \
  -d '{
    "index.blocks.read_only_allow_delete": null
}'
```

Returns the error below :

**Provide logs (if relevant)**:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index [null]",
                "resource.type": "index_expression",
                "resource.id": "_all"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index [null]",
        "resource.type": "index_expression",
        "resource.id": "_all"
    },
    "status": 404
}
```

Refer to doc : https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-update-settings.html

> The REST endpoint is /_settings (to update all indices) or {index}/_settings to update one (or more) indices settings. The body of the request includes the updated settings, for example:

**Comment by ebadyano** [comment]
I am able to reproduce the behaviour when elasticsearch instance doesn't have any indexes. If I have at least one index I cannot reproduce this error.

We might want to have a slight more clear error message than `no such index [null]` for such cases (when there are no indexes)?

@ferronrsmith Just to confirm, are you able reproduce this error when you have more than 0 indexes?

**Comment by gwbrown** [comment]
I also see the same behavior - this call works if any indices exist, but fails with `index_not_found_exception` if there are none.

This also occurs on the latest commit of 6.7, but I haven't checked any earlier than that.

**Comment by ferronrsmith** [comment]
@ebadyano confirmed; it only happens when cluster has no indices.

**Comment by hub-cap** [comment]
It looks like [this](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L232-L236) is where the resolution is happening and failing. I think we should check to see if any indices exist and if not, throw a `IndexNotFoundException(String message, String name)`, and put some information in the message regarding no indices existing. 

This would be a great starter issue for someone who wanted to contribute.

**Comment by Eunovo** [comment]
I would like to solve this as my stater issue. How do I get started?
