### ISSUE TITLE
ILM: Index wildcard pattern does not work for retry API when there are step errors

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#38987]
6.6.0

When there are no step errors for the indices requested using the retry api, it will return a response indicating as such.

POST logstash-app1*/_ilm/retry

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "cannot retry an action for an index [logstash-app1-2019.02.15.19-000002] that has not encountered an error when running a Lifecycle Policy"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "cannot retry an action for an index [logstash-app1-2019.02.15.19-000002] that has not encountered an error when running a Lifecycle Policy"
  },
  "status": 400
}
```

When there are actually step errors for the indices that are covered as part of the wildcard pattern, the same retry request throws a Bad Request error as if it no longer knows how to process the wildcard pattern.  (If I then issue the retry against individual indices logstash-app1-2019.02.15.19-000001, logstash-app1-2019.02.15.19-000002, etc..), the retry works.  So this is specific to using wildcard pattern to tell the retry API to retry on multiple indices covered by the wildcard pattern.

POST logstash-app1*/_ilm/retry

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "index [logstash-app1] does not exist"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "index [logstash-app1] does not exist"
  },
  "status": 400
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
