### ISSUE TITLE
ILM: Including "aging" information in Explain lifecycle API

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#38988]
6.6.0

I can see this feature being useful for admins in the field.

Imagine an admin is not seeing indices getting deleted from the cluster per their ILM policy and are wondering how much longer is left on the clock before ILM will consider the indices meeting the "age" requirement for deletion.

Currently, we have this information in the TRACE logging level

```
checking for index age to be at least [20m] before performing actions in the "delete" phase. Now: 1550263112, lifecycle date: 1550262751, age: [6m/360s]
```

It will be helpful to include this in the explain lifecycle API output as well (i.e., how much time is left before it will attempt to execute the next action without requiring admins to do their own time calculations) so that enabling trace logging is not necessary.

**Comment by gwbrown** [comment]
You can determine this from the current explain response, although I can certainly see how it's not immediately obvious, and should probably be documented better than it is.  The `lifecycle_date` or `lifecycle_date_millis` fields contain the "reference" date used.

`GET /*/_ilm/explain?human`:
```json
{
  "indices": {
    "test-000001": {
      "index": "test-000001",
      "managed": true,
      "policy": "my_policy",
      "lifecycle_date": "2019-02-15T22:25:03.953Z", <1>
      "lifecycle_date_millis": 1550269503953,
      "phase": "new",
      "phase_time": "2019-02-15T22:25:04.098Z",
      "phase_time_millis": 1550269504098,
      "action": "complete",
      "action_time": "2019-02-15T22:25:04.098Z",
      "action_time_millis": 1550269504098,
      "step": "complete",
      "step_time": "2019-02-15T22:25:04.098Z",
      "step_time_millis": 1550269504098
    }
  }
}
```

<1> is the date that's checked against `min_age` from the policy. So enabling trace logging isn't strictly necessary to get this information, although including the current delta in the explain API output, and/or documenting this better, would probably be good to do.

**Comment by ppf2** [comment]
Thanks for the info!  Adding something like a "time until next phase" field to the explain output will be nice.
