### ISSUE TITLE
May I know why negative weight in function score will be deprecated?

### ISSUE THREAD

**Issue by mucun1988** [elastic/elasticsearch#38997]
Regarding this `Setting a negative [weight] in Function Score Query is deprecated and will throw an error in the next major version`, I would love to know more about the motivation of doing this. 

I have used negative weight in many of my queries, and I think it is very useful. 

Suppose it is really the case in the future that we cannot use negative weight in function score, are we going to introduce some other ways to achieve the same effect?

Thanks,
Matt

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
