### ISSUE TITLE
[CI] testRetentionLeaseIsRenewedDuringRecovery fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#39011]
`CcrRetentionLeaseIT#testRetentionLeaseIsRenewedDuringRecovery` is failing frequently. 

Some CI instances:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/744/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1383/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/744/console

```
FAILURE 21.4s J4 | CcrRetentionLeaseIT.testRetentionLeaseIsRenewedDuringRecovery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value greater than <1550430923773L>
   >      but: <1550430923773L> was equal to <1550430923773L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.lambda$testRetentionLeaseIsRenewedDuringRecovery$3(CcrRetentionLeaseIT.java:269)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:858)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:832)
   > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseIsRenewedDuringRecovery(CcrRetentionLeaseIT.java:253)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Relates #38829

**Comment by dnhatn** [comment]
I have muted this test in master, 7.x, 7.0 and 6.7.

**Comment by jasontedor** [comment]
Thanks @dnhatn, I will take a look soon.

**Comment by benwtrent** [comment]
@jasontedor it seems that the fix did not work, or made another issues visible.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1654/console

**Comment by jasontedor** [comment]
@benwtrent At a glance, that looks like a different issue. Would you mind opening a new issue, and muting the test again? Sorry, I am mobile right now otherwise I would do that sort of work without burdening you for it.
