### ISSUE TITLE
[DOC][Mapping]Version only sentences.

### ISSUE THREAD

**Issue by taku333** [elastic/elasticsearch#39024]
I think that it is difficult to understand sentences only with the next version.
When you mouse over it will display sentences.
Please consider whether it is better to change.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
![image](https://user-images.githubusercontent.com/16697482/52932410-efa01b80-3392-11e9-80a5-e48fd7b48fdf.png)

**Comment by danielmitterdorfer** [comment]
@debadair this is probably done via docs infrastructure. Any thoughts on this one?

**Comment by taku333** [comment]
What happened to this matter?
