### ISSUE TITLE
Painless script_exception : _source : null_pointer_exception

### ISSUE THREAD

**Issue by HFarah** [elastic/elasticsearch#39047]
Hello,
I am working with version elasticsearch 6.5.4, I added a  new field to my existing index and I want to give it a value equal to the sum of some other fields. I used the following query in Kibana but it does not work, only the first field of the addition operation is recognized : 

POST my_index/_update_by_query 
{
 "script": {
    "lang": "painless",
    "source": "ctx._source['num_attractivity']=ctx._source['num_comments']+ctx._source['num_comments']"
  },
  "query": {
    "match_all": {}
  }
}

Result : 
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "runtime error",
        "script_stack": [
          "ctx._source['num_attractivity']=ctx._source['num_comments']+ctx._source['num_comments']",
          "                                                                       ^---- HERE"
        ],
        "script": "ctx._source['num_attractivity']=ctx._source['num_comments']+ctx._source['num_comments']",
        "lang": "painless"
      }
    ],
    "type": "script_exception",
    "reason": "runtime error",
    "script_stack": [
      "ctx._source['num_attractivity']=ctx._source['num_comments']+ctx._source['num_comments']",
      "                                                                       ^---- HERE"
    ],
    "script": "ctx._source['num_attractivity']=ctx._source['num_comments']+ctx._source['num_comments']",
    "lang": "painless",
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": null
    }
  },
  "status": 500
}

thank you.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
