### ISSUE TITLE
Weird error using AWS Elasticsearch with Laravel and this package

### ISSUE THREAD

**Issue by megusta420** [elastic/elasticsearch#39065]
Also using this one package: https://github.com/elasticquent/Elasticquent

Here is my dotenv:

> ES_HOST=search-****-w3skhs3k55*****trko6qhjsxq.eu-central-1.es.amazonaws.com
> ES_PORT=443
> ES_SCHEME=https

I'm getting this error while trying to add an index:

> {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic Og=="}

But! All works okay when I'm creating index/adding json document to AWS ES directly via rest client without any additional headers which described in exception! What am I missing?

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
