### ISSUE TITLE
Time zone not same

### ISSUE THREAD

**Issue by ankit22550** [elastic/elasticsearch#39061]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
 6.4
**Plugins installed**: []
6.4
**JVM version** (`java -version`):
1.8
**OS version** (`uname -a` if on a Unix-like system):
Centos
**Description of the problem including expected versus actual behavior**:
Hello Team,
my logs coming on multiple time zone and when I create the alert file using a command option its print multiple time zones in an alert so we are unable to get it to convert in single time zone.

below alert file, I am using.

** 
name: RP EFA IRT OCI AVG Response Time
type: metric_aggregation
index: exchange-zone*
pipe_alert_text: true
 
use_local_time: true
 
doc_type: fluentd
 
alert_text_type: alert_text_only
 
filter:
- term:
    _type: fluentd 
 
- query:
    query_string:
        query: "middleware: \"reverseproxy\" AND flow: \"efa\" AND path_split.0: \"irt\" AND (path_split.1: \"prod\" OR path_split.1: \"prodoc\") AND path_split.2: \"ci\""
 
buffer_time:
    minutes: 5
 
metric_agg_key: response_time
metric_agg_type: avg
max_threshold: 5
 
alert_subject: "ALERT on RP-EFA irt at {}"
alert_subject_args:
  - "@timestamp"
 
alert_text: '{{"date": "{0}", "rulename": "RP EFA IRT OCI AVG Response Time", "service": "IRT", "country": "OCI", "alert_value": {1}, "threshold": {2}, "error_details" : "AVG Response time longer than threshold", "dashboard": "IRT Dashboard" }}'
alert_text_args:
  - "@timestamp"
  - response_time_avg
  - max_threshold
  
alert:
- "email"
- "command"
 
command: "tee -a /elastalert_monitoring/testing-$(date '+%%Y-%%m-%%d').json"
**

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
