### ISSUE TITLE
Whitelist java.util.UUID.randomUUID() in painless scripts

### ISSUE THREAD

**Issue by oliverhenlich** [elastic/elasticsearch#39080]
This is a feature request to have `java.util.UUID.randomUUID()` whitelisted in painless scripts.

Has this method been intentionally left off the whitelist? If so, why?

Here are several attempts I've made to understand why this method is not whitelisted and to find workarounds for it. In a nutshell, I need to use it in a reindex call.

* I've tried to get input from @nik9000 and @markwalkom in the following forum posts about this.
* https://discuss.elastic.co/t/need-to-generate-uuid-in-painless-script/165318
* https://discuss.elastic.co/t/question-about-painless-whitelist/165523
* https://stackoverflow.com/questions/54682324/how-to-generate-a-uuid-in-elasticsearch-reindex-painless-script

Cheers
Oliver

**Comment by danielmitterdorfer** [comment]
@jdconrad can you please have a look at this one?

**Comment by oliverhenlich** [comment]
Hi @jdconrad @danielmitterdorfer,

Have you had a chance to look at this? Would this be a small change that could be rolled out in a point release? 

One of the major features we need to implement is blocked on this.

**Comment by jdconrad** [comment]
@oliverhenlich My apologies for the delayed response - I didn't see this had been assigned to me.  

Unfortunately, due to certain issues with the defaults for generated random values in the JVM we opted to not whitelist any related methods.  However, given this is a fairly common request, I will discuss options with other devs for an implementation that can be used in Painless moving forward.

**Comment by oliverhenlich** [comment]
Hi @jdconrad, 

Thanks for getting back on this. Have you had a chance to discuss possible options? Out of curiosity, what are the issues with the jdk defaults for generating random UUIDs. My understanding is that `java.util.UUID` uses `SecureRandom` internally. Is this problematic?

**Comment by jdconrad** [comment]
@oliverhenlich I'm still working on the best solution for this.  My understanding is that SecureRandom uses dev/random by default and in rare cases it's possible that dev/random blocks which is the main problem.

**Comment by oliverhenlich** [comment]
Thanks @jdconrad. Yeah that's why we start all our vms with `-Djava.security.egd=file:/dev/./urandom`.

**Comment by jdconrad** [comment]
This is available now from (https://github.com/elastic/elasticsearch/pull/45148).
