### ISSUE TITLE
GC logs in relative path - logs/gc.log - not using path.logs setting

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch#39091]
`jvm.options` file always writes gc logs to `logs/gc.log`, which is written to the `jvm.options` file in a distribution by the following gradle task: https://github.com/elastic/elasticsearch/blob/9a34b20233b7b780dc14c9781c998d7f34f2333e/distribution/build.gradle#L444.

`logs/gc.log` is a relative path based on where the invocation of the Elasticsearch process happens. For example, Elasticsearch started with `bin/elasticsearch.bat` on Windows will always write the GC log to a sibling `log` directory of `bin`:

```
|
---- bin
       |
       ---- elasticsearch.bat
---- logs
       |
       ---- gc.log
```

I would have expected for gc.log to be written to the same directory as the configured `path.logs` in the `elasticsearch.yml` file.

Can I suggest a new setting of `ES_PATH_LOGS` within the `elasticsearch-env.bat` script, based on `path.logs` in `elasticsearch.yml`, alternatively adopt an environment variable solution similar to as suggested here: https://github.com/elastic/elasticsearch/issues/39090

Somewhat related: The Windows Installer pushed a change to ensure that the `logs/` directory exists (https://github.com/elastic/windows-installers/pull/260) - arguably this should belong in the main Elasticsearch server codebase - ensuring that directories exist before attempting to write to them.

**Comment by jasontedor** [comment]
That's not quite right. For the package distributions, the default is `/var/log/elasticsearch/gc.log`.

> Can I suggest a new setting of `ES_PATH_LOGS` within the `elasticsearch-env.bat` script, based on `path.logs` in `elasticsearch.yml`

I would prefer that we not get into the business of parsing `elasticsearch.yml` outside of Elasticsearch itself. *Maybe* someday when we have JVM-based launcher, but most definitely not in a world where we would have to do that parsing in command line scripts.

Note that there is more complexity to the Elasticsearch logs than merely the `path.logs` settings. Their location can also be controlled through `log4j2.properties`. I would not want us to also have to inspect `log4j2.properties`.

> I would have expected for gc.log to be written to the same directory as the configured `path.logs` in the `elasticsearch.yml` file.

This is not an unreasonable expectation. However, in most cases, users stick with the defaults and then maybe we don't need to worry about complicated packaging machinery for the edge? 

What the specific situations that you are running into such that this is a problem (that the GC logs default to logs/gc.log in the archive distributions)?

**Comment by danielmitterdorfer** [comment]
We discussed this in this week's core/infra sync and we share the general sentiment of the comment above but we're definitely happy to hear more feedback about this.

**Comment by codebrain** [comment]
OK, fair enough. I didn't realise there were other potential log paths as well, looks like we have:

- ES logs
- Log4j logs
- Java GC logs

All can be configured for separate paths and with different mechanisms! Not an easy one to solve.
