### ISSUE TITLE
Update problem in version 6.1: Update API does not work as expected

### ISSUE THREAD

**Issue by masoudjahromi** [elastic/elasticsearch#39120]
in version 6.1, when I want to update the age field, it deletes the other fields in the index and only age field will be remain. this problem doesn't occur in version 6.0.

> my package version: version 6.1

- $endpoint->getURI()

```
/player/player/65152/_update"
```

- $endpoint->getBody()

```
array:1 [▼
  "doc" => array:1 [▼
    "age" => 21
  ]
]
```

```php5
    /**
     * updating a model
     *
     * @param Searchable|BaseModel $model
     */
    public function updated($model)
    {
        if ($model->getDirty()) {
            $partial['doc'] = $model->getDirty();
            $id = $model->getKeyName();
            $this->elasticSearch->update([
                'index' => $model->getSearchIndex(),
                'type'  => $model->getSearchType(),
                'id'    => $model->$id,
                'body'  => $partial,
            ]);
        }
    }
```

**Comment by henningandersen** [comment]
@masoudjahromi thanks for reporting this, sounds like something that should work.

We tried reproducing this problem in both elasticsearch 6.1.0 and 6.6.x without luck. Following steps worked fine:

```
curl -XPOST localhost:9200/test/test/id1?pretty -d '{ "test": 1 }' -H "Content-Type: application/json"
curl -XPOST localhost:9200/test/test/id1/_update?pretty -d '{"doc" : { "test2": 1 }}' -H "Content-Type: application/json"
curl localhost:9200/test/test/id1?pretty
{
  "_index" : "test",
  "_type" : "test",
  "_id" : "id1",
  "_version" : 2,
  "found" : true,
  "_source" : {
    "test" : 1,
    "test2" : 1
  }
}
```

Would you be able to provide exact steps taken using curl commands to reproduce this so that we can retry the same exact steps? Preferably on 6.6.1 if possible.

**Comment by henningandersen** [comment]
@masoudjahromi thanks for your interest in elasticsearch. Given that we have not heard back from you on above, I am going to close this issue. If you still want to pursue this, please provide the information asked for and reopen this issue.

**Comment by masoudjahromi** [comment]
> @masoudjahromi thanks for your interest in elasticsearch. Given that we have not heard back from you on above, I am going to close this issue. If you still want to pursue this, please provide the information asked for and reopen this issue.

Thanks, my problem was solved. thank you :)
