### ISSUE TITLE
Log a Warning if NioSelector Thread is Blocked for an Extendend Period of Time

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#39128]
Inspired by https://github.com/elastic/elasticsearch/pull/39118 (dead-lock in transport callback that wasn't so easy to track down).

Currently the resolve the callback listeners passed to e.g. `org.elasticsearch.action.ActionRequestBuilder#execute(org.elasticsearch.action.ActionListener<Response>)` in the the same thread that calls `Selector.select`. This has the unfortunate issue, that if the operations in the callbacks block, they introduce latency into all IO that is handled via the `Selector` whose thread is blocked.
E.g. this showed up in a set of requests seemingly being blocked for 30 s and then suddenly continuing in https://github.com/elastic/elasticsearch/issues/37965#issuecomment-463720753 and was much harder to debug than it should be.

I think we should keep track of how long the select loop (org.elasticsearch.nio.NioSelector#singleLoop`) is blocked and log a warning if it is blocked for more than a few hundred `ms`.

cc @DaveCTurner @tbrooks8

**Comment by original-brownbear** [comment]
Another example of where this would've been a helpful tool : https://github.com/elastic/elasticsearch/issues/39658 :)

**Comment by tbrooks8** [comment]
I don't think that `NioSelector` is the perfect place for this as it is (theoretically) used in production and a long GC would trigger this. Additionally, we do not have logging in the `nio` lib. I opened a WIP #39729 PR to add this to the test event handler for the mock nio transport which would still identify issues with blocking on the network thread.

**Comment by original-brownbear** [comment]
@tbrooks8 true, `NioSelector` might not be the optimal place (+ it wouldn't cover Netty I guess). I guess we could just put the logic for marking the timestamp of the last read in `org.elasticsearch.transport.TcpTransport#inboundMessage` and log if we get anything long-running there. At least all the problems/deadlocks that we ran in so far as well as #39658 should've been caught by that.

That said :tada: #39729, that's already gonna be very helpful. Still, I think it would be great having this in production too since last week alone I looked into two separate production issues that showed weird latencies in the network and that would've been much easier to debug with a warning for blocking on the IO thread.

> and a long GC would trigger this.

Is this a problem though? I mean either this is super rare and can be correlated to GC warning logging anyway when investigating or if it's frequent then the cluster/node is in trouble regardless and it really isn't all that bad, imo. I don't really see much of a downside to getting some (sort-of) false positives here?

**Comment by tbrooks8** [comment]
> Still, I think it would be great having this in production too since last week alone

Sounds like this would be good to discuss. Since it has the team-discuss label we can talk about it the next time it comes up.

**Comment by original-brownbear** [comment]
Closing #39729 is as far as we want to o here :)

**Comment by Bukhtawar** [comment]
Hi @original-brownbear We saw an issue with 6.8 where the master pings got delayed in responding after having received it. Similarly data node probably processed a ping late. https://discuss.elastic.co/t/delay-in-processing-fault-detection-pings/235572

While I think logging helps with debugging a great deal, even it be for a GC I guess that would be fine to answer questions on pings getting delayed resulting in disconnections
