### ISSUE TITLE
Cannot update on Debian

### ISSUE THREAD

**Issue by SoftCreatR** [elastic/elasticsearch#39165]
```
E: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.6.1.deb  404  Not Found [IP: 151.101.114.222 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

When trying to open it in the browser:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.6.1.deb
</Key>
<RequestId>CA6D397DBDE5C166</RequestId>
<HostId>
sJVeq3Vr8b5Tokq/16z5HmlFGyTW31EVOSpylyrVOdeVuq1gu6XCEfoeD0rFPsYl/sthM1dpYvM=
</HostId>
</Error>
```

**Comment by tvernum** [comment]
I don't have a debian box handy to test on right now, but the URL is working for me.
```
$ curl --head 'https://artifacts.elastic.co/packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.6.1.deb'
HTTP/1.1 200 OK
Last-Modified: Tue, 19 Feb 2019 15:54:19 GMT
ETag: "c5ac66211efb3dc083482f2d19cbfb15-22"
Content-Type: application/octet-stream
Accept-Ranges: bytes
Age: 163
Content-Length: 114046698
Accept-Ranges: bytes
Date: Wed, 20 Feb 2019 07:37:31 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-syd18934-SYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1550648252.997567,VS0,VE0
server: ElasticInfrastructure
```
```
$ nslookup artifacts.elastic.co
(snip)
Non-authoritative answer:
artifacts.elastic.co	canonical name = dualstack.elastic.map.fastly.net.
Name:	dualstack.elastic.map.fastly.net
Address: 151.101.30.222
```

It's possible that it took some time to be available in the CDN - we'll look into what might have happened there - but in the mean time can you confirm whether it's now working?

**Comment by user34545** [comment]
Hi @tvernum 
I tried what you did:
`$ curl --head 'https://artifacts.elastic.co/packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.6.1.deb'
HTTP/2 404 
content-type: application/xml
accept-ranges: bytes
date: Wed, 20 Feb 2019 07:45:02 GMT
via: 1.1 varnish
age: 56951
x-served-by: cache-hhn1536-HHN
x-cache: HIT
x-cache-hits: 42
x-timer: S1550648702.206627,VS0,VE0
server: ElasticInfrastructure
content-length: 337`

`$ nslookup artifacts.elastic.co
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
artifacts.elastic.co    canonical name = dualstack.elastic.map.fastly.net.
Name:   dualstack.elastic.map.fastly.net
Address: 151.101.66.222`

DNS should not be the problem I think (at least this time).

**Comment by SoftCreatR** [comment]
For me, it's working now.

**Comment by tvernum** [comment]
It looks like there could be a CDN issue then.
My request was served from `151.101.30.222` / `cache-syd18934-SYD`

Yours was `151.101.66.222` / `cache-hhn1536-HHN` so it looks like the content hasn't made it to the Frankfurt (HHN) CDN servers.
I'll follow up.

**Comment by user34545** [comment]
Hi @tvernum,
I can confirm that this works now.

**Comment by atorok** [comment]
CC @elastic/infra
