### ISSUE TITLE
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [db-3] fatal error in thread [elasticsearch[db-3][clusterApplierService#updateTask][T#1]], exiting

### ISSUE THREAD

**Issue by jiangtao007** [elastic/elasticsearch#39222]
![image](https://user-images.githubusercontent.com/26705490/53149681-5dde1b80-35e9-11e9-9a5a-f45f1e4b1462.png)

**Comment by jiangtao007** [comment]
hi,I don't know what has happened to my ES.I have build a ES cluster,when i imported data to the ES,one of the nodes stopped and now i can not  start it . is there anyone cloud help me ?thanks a lots

**Comment by dadoonet** [comment]
You should ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

**Comment by colings86** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
