### ISSUE TITLE
[CI] Test Failure CcrRetentionLeaseIT.testRetentionLeaseIsRenewedDuringRecovery

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#39268]
Build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1654/console

Unable to reproduce locally:
```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=BF18D99722E0EC18 -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT -Dtests.method="testRetentionLeaseIsRenewedDuringRecovery" -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=America/Moncton -Dcompiler.java=11 -Druntime.java=8
```
Failure trace:
```
11:47:02 FAILURE 29.4s J4 | CcrRetentionLeaseIT.testRetentionLeaseIsRenewedDuringRecovery <<< FAILURES!
11:47:02    > Throwable #1: java.lang.AssertionError: 
11:47:02    > Expected: a value greater than <1550771187477L>
11:47:02    >      but: <1550771187477L> was equal to <1550771187477L>
11:47:02    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:47:02    > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.lambda$testRetentionLeaseIsRenewedDuringRecovery$3(CcrRetentionLeaseIT.java:267)
11:47:02    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:868)
11:47:02    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:842)
11:47:02    > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseIsRenewedDuringRecovery(CcrRetentionLeaseIT.java:254)
11:47:02    > 	at java.lang.Thread.run(Thread.java:748)
11:47:02    > 	Suppressed: java.lang.AssertionError: 
```

Possibly related to https://github.com/elastic/elasticsearch/issues/39011

**Comment by jasontedor** [comment]
I think it's a race condition in the test and I know how to address it. I will try to get to in the next few days. I am so sorry to the team for the disruption caused by this test.

**Comment by markharwood** [comment]
[Build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT%20AND%20test:testRetentionLeaseIsRenewedDuringRecovery%20AND%20stacktrace:%22Expected:%20a%20value%20greater%20than%22'),sort:!(time,desc))) link

**Comment by jasontedor** [comment]
This test has not failed since the fix that I pushed last night.
