### ISSUE TITLE
SQL: change the default precision for CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#39288]
For `CURRENT_TIMESTAMP` function at the moment we have the following documentation example:

```
SELECT CURRENT_TIMESTAMP AS result;

         result
------------------------
2018-12-12T14:48:52.448Z
```

Which isn't entirely correct, because the lack of a precision, defaults it to `0`. The `0` precision means no milliseconds are returned.

**Comment by matriv** [comment]
In my opinion we should change the behaviour, as for example PostgreSQL behave like:
```
postgres=# select current_timestamp;
       current_timestamp
-------------------------------
 2019-02-22 10:55:28.484944+02
(1 row)
```

**Comment by bpintea** [comment]
I would also favor one of the two solutions: present meaningful millis with precision 3, or stop at seconds with default precision 0.

**Comment by costin** [comment]
It seems to me that there's no clear rule regarding precision and it's to the operating system/implementation. On one hand I like the default precision (0 in this case) however I can see how, based on the existing behavior, the millis are expected hence why I propose to change, for current_timestamp, the precision to 3.

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/dbb93310b083226c96e4bde3eef0079eb01cbca9
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/542e2c55f6849c973b502e3669c0843325ed732a
7.0 (7.0.0): https://github.com/elastic/elasticsearch/commit/3a84ccc9ef8c9e7c4c28df9ae0297d1e55735004
6.7 (6.7.0):  https://github.com/elastic/elasticsearch/commit/5dc5c6a31a3e785bcf443245af206f38b2f06b8c
