### ISSUE TITLE
[Monitoring] Cluster alerts need to be updated for hits.total changes

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#39322]
We need to update the cluster alert watches to handle the hits total changes.

https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/resources/monitoring/watches/elasticsearch_cluster_status.json#L132

**Comment by chrisronline** [comment]
cc @elastic/stack-monitoring

**Comment by chrisronline** [comment]
One option here is to change the watcher code to default to the 6.x total format behind a flag and users can manually turn the flag off if they want their watches to respect the 7.x total format

**Comment by jakelandis** [comment]
> One option here is to change the watcher code to default to the 6.x total format behind a flag and users can manually turn the flag off if they want their watches to respect the 7.x total format

@chrisronline - it should already do this. Here is the plan to support the hits.total changes: https://github.com/elastic/elasticsearch/issues/36115#issuecomment-445895083 , and https://github.com/elastic/elasticsearch/issues/38387.

**Comment by chrisronline** [comment]
Oh nice, so we're good to close this probably @jakelandis?

**Comment by jakelandis** [comment]
@chrisronline I think so, unless there was an issue you caught, or you wanted to proactively change the internal watches used by monitoring.  #38387 is labeled as blocker for 8.0 so we won't forget to address this sometime in the 7.x series.

**Comment by chrisronline** [comment]
Nah, I think those tickets encompass the work as far as I was considering.

Thanks!
