### ISSUE TITLE
Feature Request: Return tag or field value in bulk import http response 

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#39360]
Hi,

Would it be possible to add a field or tag when doing an index with bulk import?
The user could either set a tag or specify a field and elastic returns the field value in the bulk import http response.

{ "index" : { "_index" : "domains", "_type" : "_doc", "_id" : "1", "tag": "google.com" } }
{ "domain" : "google.com" }

So when we index something we get the ID and the TAG in the bulk import http response. We could cache the tag value and ID in redis/memcache so we can quickly retrieve this when doing an upsert/update the next day.

`{
   "took": 30,
   "errors": false,
   "items": [
      {
         "index": {
            "_index": "test",
            "_type": "_doc",
            "_id": "1",
            "tag": "google.com",
            "_version": 1,
            "result": "created",
            "_shards": {
               "total": 2,
               "successful": 1,
               "failed": 0
            },
            "status": 201,
            "_seq_no" : 0,
            "_primary_term": 1
         }
      }
]
]`

This would be very very useful as it would allow us to do bulk index and de-duplicate without manually setting a document ID to the hash of the domain. Instead we could do the bulk import without specifying a document ID, but instead get the new document ID and value of the tag from the bulk index response, which we can cache in redis or memcache so we can quickly lookup the domain's document ID without doing a slower elastic query. 

Of course if the tag value isn't cached we would lookup the ID in elastic.
If users loose the cached ID to tag/field value correlation, they could use the scroll to iterate through all documents and reload ID's and target values to the cache.

Even better would to create or upsert depending on whether a tag or field value exists in the index , so the user wouldn't need to lookup cached ID's or specify hashes as document ID's. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

**Comment by jasontedor** [comment]
There have been requests similar to this before. See for example #35739. That one is quite recent, and I don't think our position is going to have evolved at all since then. Note that the responses to a bulk request are returned in the same order as the documents in the request, so you can maintain and align these client side after the response is returned, even with auto-generated IDs.

**Comment by mbudge** [comment]
You are getting multiple requests for this feature because it will be useful.

**Comment by jasontedor** [comment]
@mbudge Thanks for the feedback. We can not implement every feature that appears useful, nor every feature asked for by popular demand. We have design goals and a development philosophy, and we try to orient our efforts towards features that meet our goals consistent with our philosophy. For this one, it can be done entirely client side, with doing it on the server adding no value whatsoever. Yet, doing so would increase the surface area of our APIs. Among other constraints, we aim to add surface area to our APIs only when they add significant value, and are complex to do client side. A feature that we say yes to is hard for us to ever take back; we have to maintain it at the expense of other features. This one does not cross those thresholds for us.
