### ISSUE TITLE
gcs-repository: Fails with socket closed

### ISSUE THREAD

**Issue by wuurrd** [elastic/elasticsearch#39366]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4

**Plugins installed**: [repository-gcs]

**JVM version** (`java -version`):
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux elasticsearch-0 4.14.65+ #1 SMP Thu Oct 25 10:42:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When doing daily snapshots, approximately 1/3 of them fail to complete with a socket closed exception when talking to GCS (usually on the largest indexes). Expected it never to fail.

```{
  "snapshots": [
    {
      "snapshot": "curator-20190219004204",
      "uuid": "AnImHa38RhevQc17mkihcA",
      "version_id": 6050499,
      "version": "6.5.4",
      "indices": [
          ...
      ],
      "include_global_state": false,
      "state": "PARTIAL",
      "start_time": "2019-02-19T00:42:04.971Z",
      "start_time_in_millis": 1550536924971,
      "end_time": "2019-02-19T00:58:30.262Z",
      "end_time_in_millis": 1550537910262,
      "duration_in_millis": 985291,
      "failures": [
        {
          "index": "<redacted>",
          "index_uuid": "<redacted>",
          "shard_id": 0,
          "reason": "IndexShardSnapshotFailedException[com.google.cloud.storage.StorageException: Socket closed]; nested: StorageException[Socket closed]; nested: SSLProtocolException[Socket closed]; nested: SocketException[Socket closed]; ",
          "node_id": "yQLAAU2QTN6ORtWRIhqsFQ",
          "status": "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards": {
        "total": 246,
        "failed": 1,
        "successful": 245
      }
    }
  ]
}
```

The error above looks like https://github.com/googleapis/google-cloud-java/issues/4162 . It looks like ES is running version 1.55.0 https://github.com/elastic/elasticsearch/blob/a7c3d5842a5d6448fcf71d436ceedf823f58d5c4/plugins/repository-gcs/build.gradle < 1.59.0

**Steps to reproduce**:

 1. Have an index of approximately 15gb size with 3 shards, 1 replica, 1 segment / shard. Run the snapshots from GCS
 2. Daily snapshot backups
 3. Will fail ~ 1/3 of the time

**Comment by hoffoo** [comment]
I am also seeing this issue, shards failing intermittently

**Comment by ywelsch** [comment]
@wuurrd thanks for reporting this and the link to googleapis/google-cloud-java#4162. Are you interested in contributing a PR to update the GCS dependencies?

Based on what's reported in the above ticket, the workaround seems to be not to use JDK 11, but use JDK 8 instead.

**Comment by wuurrd** [comment]
https://github.com/elastic/elasticsearch/pull/39748

**Comment by wuurrd** [comment]
PR Merged
