### ISSUE TITLE
Support for ignore_throttled parameter in /_xpack/sql request

### ISSUE THREAD

**Issue by bpiper** [elastic/elasticsearch#39377]
Currently adding an `ignore_throttled=false` parameter to a `/_xpack/sql` request results in this error:

`request [/_xpack/sql] contains unrecognized parameter: [ignore_throttled]`

It therefore seems to be impossible (though happy to be proven wrong on this) to query frozen indices using SQL.  I'm guessing there are also other options (e.g. from `IndicesOptions`) that aren't supported yet for SQL queries but possibly could be.

**Comment by costin** [comment]
Thanks for raising this. I've created a dedicated issue regarding support for frozen indices in SQL (#39390).

Likely going forward a user would not have to specify `ignore_throttled` or other search parameters - the SQL engine should automatically detect the type of index used and create the appropriate search. To follow the frozen indices semantics, potentially one could specify the intent in the query through a dedicated keyword:

`SELECT * FROM THROTTLED / FROZEN test`

**Comment by bpiper** [comment]
Thanks @costin , that sounds ideal.  Automatic detection would certainly be desirable in my use case.
