### ISSUE TITLE
java.lang.NoSuchFieldError: LUCENE_8_0_0

### ISSUE THREAD

**Issue by liuxyshcn** [elastic/elasticsearch#39387]
**Describe the feature**:
Wrong LUCENE version number in elasticsearch-7.0.0-beta1.jar

org.elasticsearch.Version.jave(126) turns out to be like below:
    public static final Version V_7_0_0 = new Version(V_7_0_0_ID, org.apache.lucene.util.Version.LUCENE_8_0_0);
But the latest LUCENE version is 7.7.0.
There is no LUCENE_8_0_0 in org.apache.lucene.util.Version.java

**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.0-beta1 to 7.0.0-alpha2

**Plugins installed**: []

**JVM version** (`java -version`):
1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Elasticsearch 7 will use Lucene 8 once it is released. The current build already contains the Lucene 8 snapshot.
If I'mnot mistaken, the above version line shouldn't cause any issues on your side, so I think we can close this. Please reopen if you are having trouble with the above e.g. in compiling or running the beta.

**Comment by liuxyshcn** [comment]
I am just starting to learn to use elasticsearch and trying to get some document from elastic server using java code in the first picture
![image](https://user-images.githubusercontent.com/48007162/53396550-af1e4e80-39df-11e9-9a27-0cad7464c295.png)
It turns out to be error where I run the code as an application.
![image](https://user-images.githubusercontent.com/48007162/53396618-e1c84700-39df-11e9-907f-e2f1543e1621.png)

If you are correct,maybe you can tell me how to fix the problem.

**Comment by cbuescher** [comment]
@liuxyshcn sure, no problem. But such questions are better suited for the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. Lets have that discussion there. Thanks.

**Comment by liuxyshcn** [comment]
@cbuescher Thanks for your reply and I've created a new topic as https://discuss.elastic.co/t/java-lang-nosuchfielderror-lucene-8-0-0/169959. Would you please take some time to give a look at it?
