### ISSUE TITLE
LUCENE_8_0_0

### ISSUE THREAD

**Issue by liuxyshcn** [elastic/elasticsearch#39388]
I am just starting to learn to use elasticsearch and trying to get some document from elastic server using java code in the first picture
![image](https://user-images.githubusercontent.com/48007162/53396550-af1e4e80-39df-11e9-9a27-0cad7464c295.png)
It turns out to be error where I run the code as an application.
![image](https://user-images.githubusercontent.com/48007162/53396618-e1c84700-39df-11e9-907f-e2f1543e1621.png)

If you are correct,maybe you can tell me how to fix the problem.

_Originally posted by @liuxyshcn in https://github.com/elastic/elasticsearch/issues/39387#issuecomment-467336657_

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
