### ISSUE TITLE
[Docs] Info regarding rolling upgrade is incomplete

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#39392]
In https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes.html
but also for all versions starting from 6.0 until now, there is a missing bullet point for the exception of latest release of previous major which can be done with rolling upgrade.
For `6.x` versions: `5.6` to `6.x`
For `7.x` versions: `6.7` to `7.x`.

**Comment by polyfractal** [comment]
@matriv I'm not entirely sure I understand what the issue is.  Has this been resolved?  @debadair do you know if this has been resolved as part of https://github.com/elastic/elasticsearch/pull/39944?

**Comment by matriv** [comment]
@polyfractal Indeed this has been resolved.

**Comment by matriv** [comment]
Fixed as part of #39944
