### ISSUE TITLE
Creating a repository-gcs snapshot with wait_for_completion=true results in a gateway time-out message

### ISSUE THREAD

**Issue by Winterflower** [elastic/elasticsearch#39398]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: [repository-gcs]

**JVM version** (`java -version`): 
java version "1.8.0_201"
**OS version** (`uname -a` if on a Unix-like system):
Darwin Kernel Version 18.2.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Install and configure repository-gcs plugin
 2. Register a GCS repository with snapshot API 
 3. Try to upload a snapshot using `wait_for_completion`,
```
PUT /_snapshot/my_gcs_repository/snapshot_1?wait_for_completion=true
```
Expected: Kibana console waits until upload is complete and then displays a success message. 

Actual: Kibana displays error. ES logs display success.

**Provide logs (if relevant)**:
Kibana displays the following error message

```
{
  "statusCode": 504,
  "error": "Gateway Time-out",
  "message": "Client request timeout"
}
```

But the Elasticsearch logs show that the snapshot was completed successfully 

```
[2019-02-26T14:31:16,588][INFO ][o.e.s.SnapshotsService   ] [_P5inNz] snapshot [my_gcs_repository:snapshot_1/<redacted>] started
[2019-02-26T14:34:11,573][INFO ][o.e.s.SnapshotsService   ] [_P5inNz] snapshot [my_gcs_repository:snapshot_1/<redacted>] completed with state [SUCCESS]
```
No error messages in the Kibana logs.

**Comment by original-brownbear** [comment]
@Winterflower isn't this just the Kibana request timeout kicking in? I recently tried snapshotting on GCS for another issue in `6.5.x` and `wait_for_completion=true` worked just fine. Does the equivalent request fail (or go on forever) for you from the command line via `curl` or so as well?

**Comment by Winterflower** [comment]
You're right @original-brownbear ! It's just the Kibana timeout kicking in. The request completes just fine. We can close this issue :)
