### ISSUE TITLE
[Docs] Update instruction for upgrading elasticsearch

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#39393]
In https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html
and also for versions `7.x` and `7.0` the version references should be updated from 6.x to 7.x, and new entries in the table should be added.

**Comment by polyfractal** [comment]
This looks to have been fixed in https://github.com/elastic/elasticsearch/pull/39944.  Closing :)
