### ISSUE TITLE
Guide not very readable smartphone portrait

### ISSUE THREAD

**Issue by mfn** [elastic/elasticsearch#3939]
The elasticsearch guides with the menu to the right don't look very good in portrait mode:

![Portrait mode example](http://i.imgur.com/zWKUgla.png) .

In general, space is used very generous on the small screen.

I tried to poke around myself but had to realize https://github.com/elasticsearch/docs/blob/master/resources/styles.css does not contain the media queries. If someone could point me to the right version of main.css being used ... thanks.

**Comment by javanna** [comment]
I think this is solved with the new [website](http://www.elastic.co/guide/en/elasticsearch/reference/current/search.html), looks much better now, closing!
