### ISSUE TITLE
SQL: Support Frozen indices

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#39390]
Introduced in 6.6, frozen indices support searches within certain constraints.
SQL should be able to detect them and run queries around them. Even better, it should chose the correct search options (such as `pre_filter_shard_size`).

Related to #39377

**Comment by astefan** [comment]
I would be in favor of giving the user the option (or explicit consent) that they want to search such an index. Just like ES itself "asks" for such a [special consent](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/_searching_a_frozen_index.html) through `ignore_throttled` parameter. And this should apply for searches over wildcard named indices as well.
