### ISSUE TITLE
[FR] RestClient should discovery all coordinating nodes automatically

### ISSUE THREAD

**Issue by bringyou** [elastic/elasticsearch#39402]
In the current version of `RestClient`, it will only connect the nodes we passed via builder.
```java
public static RestClientBuilder builder(HttpHost... hosts) {
        return new RestClientBuilder(hostsToNodes(hosts));
}
```
Should `RestClient` discovery all (coordinating) nodes automatically, by calling some apis itself to find all (coordinating) nodes, like the [nodes info](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html)? Consider that when we add some coordinating nodes dynamically, our applications in the client side should be re-compiled(or restart if we use some configuration center) to use those nodes. If `RestClient` has such a feature, things will be wonderful. And this feature can be disabled by default, if we worry about the compatibility

**Comment by javanna** [comment]
This feature is already available, it's called sniffer, and it is available as an additional dependency. See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/sniffer.html .
