### ISSUE TITLE
CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#39437]
The test `CoordinatorTests testDiscoveryUsesNodesFromLastClusterState` failed on CI today with an OOM:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2262/consoleFull

It reproduces locally using:
```
./gradlew :server:unitTest \
  -Dtests.seed=B59E6E6C9C7ABB73 \
  -Dtests.class=org.elasticsearch.cluster.coordination.CoordinatorTests \
  -Dtests.method="testDiscoveryUsesNodesFromLastClusterState" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=Pacific/Ponape \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Build stats shows that it does not fail recently.

<details>
  1> [2019-02-27T18:34:42,070][INFO ][o.e.c.c.CoordinatorTests ] [testDiscoveryUsesNodesFromLastClusterState] after test
ERROR    120s J7 | CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState <<< FAILURES!
   > Throwable #1: java.lang.OutOfMemoryError: GC overhead limit exceeded
   > 	at __randomizedtesting.SeedInfo.seed([B59E6E6C9C7ABB73:D3835B0AE155B36C]:0)
   > 	at java.util.Optional.of(Optional.java:108)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$2.nextState(CoordinatorTests.java:2197)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.isLinearizable(LinearizabilityChecker.java:228)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.lambda$isLinearizable$0(LinearizabilityChecker.java:213)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker$$Lambda$3610/1501875111.test(Unknown Source)
   > 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
   > 	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649)
   > 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
   > 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
   > 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
   > 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
   > 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
   > 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
   > 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   > 	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.isLinearizable(LinearizabilityChecker.java:213)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$Cluster.stabilise(CoordinatorTests.java:1445)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$Cluster.stabilise(CoordinatorTests.java:1369)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState(CoordinatorTests.java:1081)
</details>

cc @DaveCTurner

**Comment by tlrx** [comment]
Similar failure with  `CoordinatorTests.testAckListenerReceivesNackFromLeader`

```
/gradlew :server:unitTest -Dtests.seed=8FC69D8461D852BA -Dtests.class=org.elasticsearch.cluster.coordination.CoordinatorTests -Dtests.method="testAckListenerReceivesNackFromLeader" -Dtests.security.manager=true -Dtests.locale=kk -Dtests.timezone=America/Lima -Dcompiler.java=12 -Druntime.java=11
```

in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/42/consoleFull

**Comment by ywelsch** [comment]
@tlrx this is caused by https://github.com/elastic/elasticsearch/pull/36943. Can you comment out the line (I think 1445) that calls `isLinearizable` in `CoordinatorTests.java` (and backport to 7.x and 7.0)? The only other option would be to mute all `CoordinatorTests`, which is far worse.

**Comment by henningandersen** [comment]
Both succeeds with the optimizations in PR https://github.com/elastic/elasticsearch/pull/38561 though `testAckListenerReceivesNackFromLeader` also succeded on my master checkout (the original one did fail).

**Comment by tlrx** [comment]
As @ywelsch suggested, I commented out the following line in master, 7.x and 7.0 branches:

```
// See https://github.com/elastic/elasticsearch/issues/39437
//assertTrue("history not linearizable: " + history, linearizabilityChecker.isLinearizable(spec, history, i -> null));
```

See commits 9be914cfece721d630abc875d54bd9184788369f, 4dd274b51d348a5b1755cfcce3067df5032b5f3f and 41463c42d32f271c4e33b496797fa33d6c2b1f52
