### ISSUE TITLE
gradlew idea failed on branch 6.1

### ISSUE THREAD

**Issue by imqishi** [elastic/elasticsearch#39434]
I try to learn source code but cannot build for idea...it seems that my gradle version is higher? Is there a way to handle this? Thanks.

```
QiShi-MBP:elasticsearch qishi$ git clean -xdf
Removing .gradle/
Removing buildSrc/.gradle/
Removing buildSrc/build-bootstrap/
QiShi-MBP:elasticsearch qishi$ ./gradlew idea
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :benchmarks
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at build_9qjdudfvwej23hggqdxk4uiue.run(/Users/qishi/code/elasticsearch/benchmarks/build.gradle:31)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/qishi/code/elasticsearch/benchmarks/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > JAVA_HOME must be set to build Elasticsearch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s

QiShi-MBP:elasticsearch qishi$ gradle -v

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Mac OS X 10.14.3 x86_64
```

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a question about how to build Elasticsearch, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

To get you started, the key part of the error is:

> JAVA_HOME must be set to build Elasticsearch

and the instructions to help you get set up are here:
- https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase

Please read through that document and then head to the [forums](https://discuss.elastic.co/) to ask any questions you have.

Thank you.
