### ISSUE TITLE
Execute watch api should redirect to node that actually holds the watch

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#39435]
If the execute watch api, executes an existing watch, then the execute watch api call should occur on a node that actually holds that watch. 

Currently the execute watch api execution occurs always on the coordinating node. In case of executing an existing watch, the execute watch api, executes a get request to fetch the source of the watch and then execute that on the coordinating node.

This change would help use cases where for example only nodes with .watch shards are allowed to send emails. Currently in these use cases the execute watch api only works if the execute watch request is send to specific nodes and if someone is using the execute watch api from Kibana, there is no real control over to what node the request is send to.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
