### ISSUE TITLE
Could not dynamically add mapping for field

### ISSUE THREAD

**Issue by dengkx** [elastic/elasticsearch#39432]
data:{"vip.code":"234","vip.code.name":"lilei"}
error:Exception in thread "main" MapperParsingException[Could not dynamically add mapping for field [vip.code.name]. Existing mapping for [vip.code] must be of type object but found [text].]

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Here you already indexed some text content under `vip.code` probably. But let discuss that on discuss.elastic.co.
