### ISSUE TITLE
AuthenticationServiceTests.testInvalidToken() fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#39465]
`AuthenticationServiceTests.testInvalidToken()` failed on `6.7` today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+intake/257

This is the first failure in the past 6 months.

I reproduces locally with:
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=18A19736D2A51DC \
  -Dtests.class=org.elasticsearch.xpack.security.authc.AuthenticationServiceTests \
  -Dtests.method="testInvalidToken" \
  -Dtests.security.manager=true \
  -Dtests.locale=nl-NL \
  -Dtests.timezone=America/Campo_Grande \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

<details>
14:59:52   1> [2019-02-27T10:59:44,068][INFO ][o.e.x.s.a.AuthenticationServiceTests] [testInvalidToken] before test
14:59:52   1> [2019-02-27T10:59:44,947][ERROR][o.e.x.s.a.AuthenticationServiceTests] [authc_test] unexpected exception
14:59:52   1> java.lang.IllegalArgumentException: Cannot authenticate using token from version [0.0.0.Beta3]
14:59:52   1> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$12(TokenService.java:445) ~[main/:?]
14:59:52   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
14:59:52   1> 	at org.elasticsearch.xpack.security.authc.TokenService$KeyComputingRunnable.doRun(TokenService.java:1452) [main/:?]
14:59:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
14:59:52   1> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
14:59:52   1> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
14:59:52   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
14:59:52   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
14:59:52   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
14:59:52   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
14:59:52   1> [2019-02-27T10:59:44,949][INFO ][o.e.x.s.a.AuthenticationServiceTests] [testInvalidToken] after test
14:59:52 ERROR   0.90s J4 | AuthenticationServiceTests.testInvalidToken <<< FAILURES!
14:59:52    > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=327, name=elasticsearch[authc_test][security-token-key][T#1], state=RUNNABLE, group=TGRP-AuthenticationServiceTests]
14:59:52    > 	at __randomizedtesting.SeedInfo.seed([18A19736D2A51DC:2615402061C09C84]:0)
14:59:52    > Caused by: java.lang.AssertionError: unexpected exception: Cannot authenticate using token from version [0.0.0.Beta3]
14:59:52    > 	at __randomizedtesting.SeedInfo.seed([18A19736D2A51DC]:0)
14:59:52    > 	at org.elasticsearch.xpack.security.authc.AuthenticationServiceTests.lambda$testInvalidToken$32(AuthenticationServiceTests.java:1181)
14:59:52    > 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69)
14:59:52    > 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$1(AuthenticationService.java:260)
14:59:52    > 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69)
14:59:52    > 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$getAndValidateToken$3(TokenService.java:316)
14:59:52    > 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69)
14:59:52    > 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69)
14:59:52    > 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$12(TokenService.java:445)
14:59:52    > 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
14:59:52    > 	at org.elasticsearch.xpack.security.authc.TokenService$KeyComputingRunnable.doRun(TokenService.java:1452)
14:59:52    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:59:52    > 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:59:52    > 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:59:52    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
14:59:52    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:59:52    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:59:52    > 	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by jaymode** [comment]
Fixed by 4d13db278a758a1ac58136892797af72d158f18e. @tvernum you'll want to incorporate this into your backport of #38881
