### ISSUE TITLE
SQL: hide the geo_point columns for ODBC

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#39471]
The columns of type `geo_point` should also be hidden in `SYS COLUMNS` for the `ODBC` clients, just like `nested` and `object` (similar to https://github.com/elastic/elasticsearch/issues/37801).

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/9e0df64b2d36c9069dfa506570468f0522c86417
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/ba44f28340704ca9e696b4eab6aba6b90199ca66
7.0 (7.0.0): https://github.com/elastic/elasticsearch/commit/0eb22f79c21b97c6086e501aecf41117730e2732
6.7 (6.7.0): https://github.com/elastic/elasticsearch/commit/185054c3d176639dd5984911d4f30d4014473342
6.6 (6.6.2): https://github.com/elastic/elasticsearch/commit/a82456662c6b7423f316740ca0cb6ad8d5b7912f
