### ISSUE TITLE
indicate to Restart Elasticsearch whenever plugin is installed

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#39487]
When you install a plugin, sometimes you take it that it is enabled upon installation, but in reality, you need to restart Elasticsearch to activate it, as it is instructed in the [guide](https://www.elastic.co/guide/en/x-pack/5.6/installing-xpack.html)

it would be nice if we can add some text to guide users to restart Elasticsearch.

```
$ ./bin/elasticsearch-plugin install mapper-size
-> Downloading mapper-size from elastic
[=================================================] 100%   
-> Installed mapper-size
$ 
```

**Comment by williamrandolph** [comment]
It should be easy to add a message after successfully installing a plugin along the lines of `After installation, the node must be restarted before the plugin becomes visible.`

**Comment by qlchan24** [comment]
Hi I can try to implement this!
