### ISSUE TITLE
Documentation > Security API > Get User Privileges

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch#39491]
The documentation link in the REST API JSON file leads to a 404 on the documentation site:

https://github.com/elastic/elasticsearch/blob/d7c5d8049afa2edea2cf13c1ec423647bea6cae5/x-pack/plugin/src/test/resources/rest-api-spec/api/security.get_user_privileges.json#L3

On calling the API endpoint it appears to work on `6.5.0`+ clusters:

Request:

`GET /_xpack/security/user/_privileges?pretty=true&error_trace=true HTTP/1.1`

Response:

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 363

{
  "cluster" : [
    "all"
  ],
  "global" : [ ],
  "indices" : [
    {
      "names" : [
        "*"
      ],
      "privileges" : [
        "all"
      ]
    }
  ],
  "applications" : [
    {
      "application" : "app-f-fb2ecea6",
      "privileges" : [
        "p1-f-fb2ecea6"
      ],
      "resources" : [
        "*"
      ]
    }
  ],
  "run_as" : [ ]
}
```

**Comment by codebrain** [comment]
Suggest we include a full JSON example, similar to this: https://github.com/elastic/elasticsearch/blob/d7c5d8049afa2edea2cf13c1ec423647bea6cae5/x-pack/plugin/src/test/resources/rest-api-spec/test/privileges/40_get_user_privs.yml#L88

**Comment by debadair** [comment]
Closing as fixed.

**Comment by lucabelluccini** [comment]
The PR https://github.com/elastic/elasticsearch/pull/36292/files implements an HLRC API `_xpack/security/user/_privileges` (or `_security/user/_privileges`) but we do not document it.

We document the `_has_privileges` API (https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-has-privileges.html).

**Comment by lucabelluccini** [comment]
CC @elastic/es-security

**Comment by lcawl** [comment]
I have created https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-get-user-privileges.html in master, 7.x, and 7.13 branches
