### ISSUE TITLE
SQL: MIN and MAX could work better with date fields

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#39492]
At the moment, MIN and MAX for a `date` field will return a double value. This is because Elastisearch's own  `stats` aggregation computes the values and returns them as `double`.

```
sql> select min(birth_date), max(birth_date) from test_emp;
min(birth_date)|max(birth_date)
---------------+---------------
-5.631552E11   |-1.575936E11
```

We could improve this behavior by automatically CASTing the `double` value returned to a `long` and then to a `date`.

**Comment by matriv** [comment]
Backported to `7.x` with 17b8b54d5e11c2edc0beeee7db790c6129a7aa91
to `7.0` with 46aeda98f88f04fd81790a029d0cc61f66c706ed
to `6.7` with eb195672f43a8b4662a9023283e4b9d68b919d21
to `6.6` with 6b8e84e78f81cf45110f6eb03d123e268a7bd3f3
