### ISSUE TITLE
Files authorization with Xpack

### ISSUE THREAD

**Issue by Bhanuji95** [elastic/elasticsearch#39507]
Hello Guys,

I am working on building up a search engine with elasticsearch which will be used for searching files and folders from a dfs cluster. I indexed all of them to elasticsearch using fscrawler. But now I have an issue with authorization of those files which will be accessed from elasticsearch. I want to integrate my active directory and wants the existing users roles to be applied. I found a way with Xpack. But their roles privileges in AD will get applied with xpack when they search for a file or folder in elasticsearch?

Please someone help me out with this. Thank you

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
