### ISSUE TITLE
Functionbeat

### ISSUE THREAD

**Issue by Bhanuji95** [elastic/elasticsearch#39508]
Hello 

Can you anyone tell me how to index data into elasticsearch using functionbeat?

I want to index my cloudwatch logs directly to my elasticsearch. I configured and ran functionbeat which has created a lamba function but when running that lamba function I am getting license error as below.
"2019-02-28T13:33:30.501Z	INFO	[license-manager]	licenser/manager.go:265	Cannot retrieve license, retrying later, error: error from server, response code: 0"

Please suggest

**Comment by cbuescher** [comment]
Hi @Bhanuji95. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
