### ISSUE TITLE
RecoveryDuringReplicationTests.testDoNotWaitForPendingSeqNo failed

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#39510]
The test `RecoveryDuringReplicationTests.testDoNotWaitForPendingSeqNo()` failed on CI:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/267/consoleFull

It does not reproduce with:
```
./gradlew :server:unitTest \
  -Dtests.seed=F8E8B6147433686D \
  -Dtests.class=org.elasticsearch.index.replication.RecoveryDuringReplicationTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

Relevant log: 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2915431/consoleText.txt)

**Comment by gwbrown** [comment]
Failed again today https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+periodic/137/console

Looks like it fails ~1-3 times/day

**Comment by dnhatn** [comment]
I opened #39595.
