### ISSUE TITLE
Reset max_retries counter before executing routing commands

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#39546]
We respect allocation deciders, including the `MaxRetryAllocationDecider`, when executing reroute commands. If you specify `?retry_failed=true` then the retry counter is reset, but not until after trying to execute the reroute commands. This means that if an allocation has repeatedly failed, but you want to take control and assign a shard to a particular node to work around the repeated failures, you cannot just do this:

```
POST /_cluster/reroute?retry_failed=true
{
  "commands": [
    {
      "allocate_replica": {
        "index": "blahblah",
        "shard": 2,
        "node": "node-4"
      }
    }
  ]
}
```

~The command is rejected by the `MaxRetryAllocationDecider`, then the retry counter is reset, then Elasticsearch tries in vain to allocate the shard to a node of its choosing, hitting the retry limit again.~ Correction: The command is rejected by the `MaxRetryAllocationDecider` which stops the whole reroute process.

The workaround today is:

- disable allocation
- reset the retry counter with a bare `POST /_cluster/reroute?retry_failed=true`
- execute the desired reroute command with another call to `POST /_cluster/reroute`
- re-enable allocation

I think we should reset the retry counter before executing the reroute commands here:

https://github.com/elastic/elasticsearch/blob/4ca241b78a80f92d5443caf6c943243b166515f5/server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java#L338-L348

cf https://discuss.elastic.co/t/shard-allocation-says-max-retry-but-fails-to-allocate-on-retry-failed-true/170396

**Comment by hpandeycodeit** [comment]
@DaveCTurner I will work on this

**Comment by vigyasharma** [comment]
@DaveCTurner, @hpandeycodeit If this is still open, I'd like to pick it up.

**Comment by DaveCTurner** [comment]
This is still open and we haven't heard from @hpandeycodeit in a while so please go ahead @vigyasharma.

**Comment by tffnd** [comment]
First time trying to contribute to open-source. What is the best way to approach this issue?

**Comment by vigyasharma** [comment]
@tffnd I have the changes with tests ready for this issue, will raise a PR shortly
