### ISSUE TITLE
invalid_type_name_exception","reason":"Document mapping type name can't start with '_'

### ISSUE THREAD

**Issue by bulkerke** [elastic/elasticsearch#39554]
I'm running ElasticSearch 5.4 on Laravel 5.5

When i run php artisan elastic:index to index the indices I get following error:

```
[In Connection.php line 610:
                                                                               
  {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"Doc  
  ument mapping type name can't start with '_', found: [_doc]"}],"type":"inva  
  lid_type_name_exception","reason":"Document mapping type name can't start w  
  ith '_', found: [_doc]"},"status":400}   ]
```

my index is called ah_index_dev2_de

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Here with this version _doc type name can not be used.
