### ISSUE TITLE
IndexShardIT#testPendingRefreshWithIntervalChange fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#39565]
IndexShardIT#testPendingRefreshWithIntervalChange fails on both master and 7.x. Failure does not seem to reproduce with the same seed.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/365/console

```
./gradlew :server:integTest -Dtests.seed=170A6D9A6824A5B4 -Dtests.class=org.elasticsearch.index.shard.IndexShardIT -Dtests.method="testPendingRefreshWithIntervalChange" -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Africa/Libreville -Dcompiler.java=11 -Druntime.java=8
```

```
05:20:11 FAILURE 0.17s J3 | IndexShardIT.testPendingRefreshWithIntervalChange <<< FAILURES!
05:20:11    > Throwable #1: java.lang.AssertionError
05:20:11    > 	at __randomizedtesting.SeedInfo.seed([DF23BE067FF20969:44A0A86926C59400]:0)
05:20:11    > 	at org.elasticsearch.index.shard.IndexShardIT.testPendingRefreshWithIntervalChange(IndexShardIT.java:771)
05:20:11    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by javanna** [comment]
@s1monw I wonder if #39462 has something to do with this failure which appeared yesterday, approximately around its merge time.

**Comment by javanna** [comment]
I muted this test on both master and 7.x

**Comment by dnhatn** [comment]
I am able to reproduce this. I will work on the fix.

**Comment by andrershov** [comment]
The test failed again https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/332/console. It's only one new test failure, not muting the test to gather more stats. @dnhatn can you look at the failure, please?

**Comment by dnhatn** [comment]
CI: https://scans.gradle.com/s/klpfc2tr7ohzw
