### ISSUE TITLE
FullClusterRestartIT testClosedIndices failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#39576]
Discovered in a PR build this failure reproduces for me on master commit b199968f9764da25a3fa756979da645bba4db23d

`
./gradlew :qa:full-cluster-restart:v7.1.0#bwcTest -Dtests.seed=766D6095B5232D99 -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testClosedIndices" -Dtests.security.manager=true -Dtests.locale=ro -Dtests.timezone=Indian/Mayotte -Dcompiler.java=11 -Druntime.java=8
`

```
FAILURE 6.23s | FullClusterRestartIT.testClosedIndices <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: null
   >      but: was <{shards={0=[{node=null, recovery_source={bootstrap_new_history_uuid=false, type=EXISTING_STORE}, unassigned_info={reason=INDEX_CLOSED, at=2019-03-01T16:29:11.479Z, allocation_status=fetching_shard_data, delayed=false}, index=testclosedindices, relocating_node=null, state=UNASSIGNED, shard=0, primary=true}, {node=null, recovery_source={type=PEER}, unassigned_info={reason=INDEX_CLOSED, at=2019-03-01T16:29:11.479Z, allocation_status=no_attempt, delayed=false}, index=testclosedindices, relocating_node=null, state=UNASSIGNED, shard=0, primary=false}]}}>
   >    at __randomizedtesting.SeedInfo.seed([766D6095B5232D99:3C8036DDE4034432]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.upgrades.FullClusterRestartIT.assertClosedIndex(FullClusterRestartIT.java:1045)
   >    at org.elasticsearch.upgrades.FullClusterRestartIT.testClosedIndices(FullClusterRestartIT.java:993)
```

Nothing of interest in the logs, attaching here for completeness
[node1.log](https://github.com/elastic/elasticsearch/files/2920287/node1.log)
[node0.log](https://github.com/elastic/elasticsearch/files/2920288/node0.log)

**Comment by DaveCTurner** [comment]
Similar failure here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/1089/consoleText
