### ISSUE TITLE
Elasticsearch query error due to data storage error

### ISSUE THREAD

**Issue by hesmile** [elastic/elasticsearch#39599]
#### Basic Information：
Elasticsearch Version：5.6.0
Server * 3：CPU * 8 + 16G 
Index Shards：3
Index Replicas：1
Data Size：+-100G

#### Description
Recently, When querying base on Id,  sometimes there is no result, sometimes there is result.
I guess there is a problem with the elasticsearch data store.
I want to know if this issue has been fixed in 5.6 later

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
