### ISSUE TITLE
[Rollup] Support filtering of metrics

### ISSUE THREAD

**Issue by ochart2** [elastic/elasticsearch#39604]
Feature request:

Ability to filter/define metrics for more specific rollups.
Same to how we can define new fields/metrics on a histogram.

Example:

`A_and_B`: I only want to count field A if field B is defined
`Success`: A field where s == 'OK'

Is something like this possible?

**Comment by polyfractal** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/38837
