### ISSUE TITLE
Can not install respository-s3 plugin using different methods

### ISSUE THREAD

**Issue by nzarif** [elastic/elasticsearch#39601]
Hi,
I have installed Elasticsearch-6.5.4 and have a single local node. I am trying to captures a snapshot from my local node. I have installed AWS plugin but I am unable to install repository-s3 plugin. Installing the plugin using `sudo ./plugin install repository-s3` in `/usr/share/elasticsearch/bin` does not work and gives this error:
`ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
`
I have also tried this using an https proxy and got the same error.
I also tried downloading the .zip file and install it offline or install it from the HTTP address but this error occurs:
`ERROR: Plugin [repository-s3] must be at least a jvm or site plugin`
I tried this with the latest version of the plugin (6.6.1) and 6.5.4 which is my Elasticsearch's version and also 5.6.15 which is an older version. All of them came up with the same error.

What am I doing wrong?

**Comment by dadoonet** [comment]
Could you run it with `--verbose`?

> I also tried downloading the .zip file

From which location?

**Comment by nzarif** [comment]
I also tried `--verbose` and got the same error. I used this link for downloading the plugin:
[https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.6.1.zip](url)

**Comment by dadoonet** [comment]
Could you share the full output with the verbose parameter please?

Also the version you downloaded must match your elasticsearch version.

**Comment by nzarif** [comment]
when I run the command below:
`sudo ./plugin install --verbose repository-s3`
I get this error:
`-> Installing repository-s3...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.1/repository-s3-2.3.1.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.1/repository-s3-2.3.1.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.1/repository-s3-2.3.1.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information`

**Comment by nzarif** [comment]
Considering the version match, I have tried downloading the plugin that matches my elasticsearch and installing the files using the command below, but I get the following error:
`sudo ./plugin install file:////home/niloofar/Downloads/repository-s3-6.5.4.zip`
output:
`-> Installing from file:////home/niloofar/Downloads/repository-s3-6.5.4.zip...
Trying file:////home/niloofar/Downloads/repository-s3-6.5.4.zip ...
Downloading ............................................DONE
Verifying file:////home/niloofar/Downloads/repository-s3-6.5.4.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [repository-s3] must be at least a jvm or site plugin`
I have tried this command with --verbose and I get the same result.

**Comment by dadoonet** [comment]
It sounds like you have an old `plugin` manager. Probably you mixed some installation files or did a wrong upgrade. The way to install a plugin is described in this documentation: https://www.elastic.co/guide/en/elasticsearch/plugins/6.5/installation.html

It should be:

```sh
sudo bin/elasticsearch-plugin install [plugin_name]
```

This is not an elasticsearch issue but a wrong configuration or installation. 
Fix your installation. 
If you don't succeed, please ask for help on discuss.elastic.co where we can give a better support.
