### ISSUE TITLE
Buggy custom fuzziness using AUTO:[low],[high]

### ISSUE THREAD

**Issue by fadijabi** [elastic/elasticsearch#39614]
Hello,

I am using elasticsearch v6.6.1 and I still feel that custom fuzziness using AUTO:[low],[high] is still defaulting to AUTO or something.

I have a field named "featuretype" of type "keyword" and if I execute

`GET my_index/_search { "query": { "match": { "featuretype": { "query": "Uniy", "operator": "AND", "fuzziness": "auto:5,8", "prefix_length": 1, "fuzzy_transpositions": false } } } }`

I still get results where featuretype are "Unit" although I did a mistake "Uniy". As per my understanding AUTO:5,8 will

0..4
Must match exactly

5..7
One edit allowed

greater than 7
Two edits allowed

The expected result is not to match any result as in this case. 
Any help is appreciated?

**Comment by cbuescher** [comment]
@fadijabi thanks, I think I found the issue and opened a PR to fix this.
