### ISSUE TITLE
Provide REST API Spec JSON for request body parameters

### ISSUE THREAD

**Issue by jacobwgillespie** [elastic/elasticsearch#39613]
The `rest-api-spec` is awesome for the high-level REST endpoints and parameters, but omits the definition of the bodies that those endpoints accept.  Especially for the `/_search` endpoint, it would be very useful to have a JSON spec for things like `query` and `aggregations`, with all the different aggregations and their parameter types.  This would allow for generating type-safe API clients in other languages.

As an example, I have a toy project [`elastic-ts`](https://github.com/jacobwgillespie/elastic-ts) that was created by reading the HTML documentation online and porting that by hand to TypeScript types, for instance:

https://github.com/jacobwgillespie/elastic-ts/blob/master/src/types/aggregations.ts

Obviously this is not a sustainable way to maintain such a library, so it would cool if there was a programatic way to read things like the aggregations and query schemas.  As far as I can tell, there's no way to do this today short from reading the Java source and looking for instances of `ObjectParser`.

**Comment by javanna** [comment]
Relates to, and possibly duplicates #25152 .

**Comment by jacobwgillespie** [comment]
> Relates to, and possibly duplicates #25152 .

Not 100% sure on this, but I'm not sure if OpenAPI/Swagger have the fidelity to describe the valid API responses, for instance, request parameters that can have properties from either set A or B depending on another field value plus common properties from set C, or the recursive structure of nested aggregations where certain aggregations cannot be be nested underneath others.

In my particular use-case, I'm okay with the API description not following a preexisting spec so long as it's structured.

**Comment by codebrain** [comment]
Please checkout the comment from @mpdreamz - https://github.com/elastic/elasticsearch/issues/25152#issuecomment-356878843

There is a typescript generator prototype here: https://github.com/elastic/elastic-client-generator

**Comment by javanna** [comment]
I am leaning towards closing this, as #25152 is the issue where the possibilities have been discussed. We may not go with OpenAPI or Swagger after all, but I think that this issue has the exact same goal as #25152 , which is to have some kind of spec for request body to be provided in our APIs, and possibly for responses returned as well. Please feel free to reopen if you think that I misunderstood what you proposed.
