### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT timeout on Darwin

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#39618]
This test suite has timed out on the last 3 CI runs on darwin:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-darwin-compatibility/51/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/51/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-darwin-compatibility/50/console

```
ERROR   1.25s | MixedClusterClientYamlTestSuiteIT.test {p0=search/160_exists_query/Test exists query on _id field} <<< FAILURES!
   > Throwable #1: java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Comment by tvernum** [comment]
Cluster logs from `7.0` branch, build 50
[mixedClusterLogs.zip](https://github.com/elastic/elasticsearch/files/2924387/mixedClusterLogs.zip)

**Comment by tvernum** [comment]
[darwin70-build50.txt](https://github.com/elastic/elasticsearch/files/2924390/darwin70-build50.txt)

**Comment by abhinavsagar** [comment]
@tvernum Can you provide some more information like whether you are using single node cluster and you os configuration etc.

Maybe you can use **ulimit -c unlimited** then restart the instance and provide the core dump once it fails again?

**Comment by jaymode** [comment]
There are disk issues with the darwin ci worker that these tests run, which is most likely the culprit here. Closing this for now as there is nothing actionable at the moment.
