### ISSUE TITLE
Strict dynamic mapping with a field of type date

### ISSUE THREAD

**Issue by nishantsaini** [elastic/elasticsearch#39625]
**Elasticsearch version**: 6.4.0

**JVM version**: 1.8.0_181

**OS version**: 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When using `"dynamic": "strict"` in mapping at document level, unable to index new document with correct date matching the specified format for a date field.
**Steps to reproduce**:

1. Create a new index using the following mapping:
```json
PUT test
{
  "mappings": {
    "_doc": {
      "dynamic": "strict",
      "properties": {
        "created ": {
          "type": "date",
          "format": "yyyy/MM/dd"
        }
      }
    }
  }
}
```

2. Index a new document
```json
PUT test/_doc/1
{
  "created": "2016/01/01"
}
```
On following the above steps, step 2 results in the following error even though the field `created` is present in the mapping and the input date matches the format specified for the field as well:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "strict_dynamic_mapping_exception",
        "reason": "mapping set to strict, dynamic introduction of [created] within [_doc] is not allowed"
      }
    ],
    "type": "strict_dynamic_mapping_exception",
    "reason": "mapping set to strict, dynamic introduction of [created] within [_doc] is not allowed"
  },
  "status": 400
}
```
**Expected result**: 
The document should get indexed.

**Special Notes:**
Removing `"dynamic": "strict"` from the mapping above results in the correct behaviour.
Replacing to `"dynamic": false` allows to index the document but the data against the field `created` get saved in `_source` but doesn't get indexed. For e.g. range query doesn't return the expected document.

**Comment by dadoonet** [comment]
Note: this has been reported as well on discuss where I believe this is the best place to start: https://discuss.elastic.co/t/dynamic-mapping-strict-and-date-data-type-es-6-4/170667/1

**Comment by nishantsaini** [comment]
@dadoonet 
Well I started that topic on discuss but haven't received any response there. It would be helpful if you could mark someone there who could explain about the behaviour. I felt it as a bug so I thought of reporting here as well.

**Comment by dadoonet** [comment]
Read [this](https://discuss.elastic.co/t/about-the-elasticsearch-category/21) and specifically the "Also be patient" part.

It's fine to answer on your own thread after 2 or 3 days (not including weekends) if you don't have an answer. But here you just opened the question 5 hours ago.

**Comment by nishantsaini** [comment]
Thanks and sorry for being impatient. Took a note of it. :)

**Comment by matriv** [comment]
@nishantsaini The field name ` "created ": {` has a trailing whitespace

**Comment by nishantsaini** [comment]
@matriv 
Thanks. Yes my silly mistake.

Closed the issue.
