### ISSUE TITLE
High level REST client parameters look wrong due indirectness and side effects

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#39666]
Using the high-level request client, this is how code to build a request with parameters appears today:

```java
        final Request request = new Request(HttpPut.METHOD_NAME, endpoint);
        final RequestConverters.Params parameters = new RequestConverters.Params(request);
        parameters.withWaitForActiveShards(putFollowRequest.waitForActiveShards());
        request.setEntity(createEntity(putFollowRequest, REQUEST_BODY_CONTENT_TYPE));
```

This looks wrong because `parameters` appears to be unused. That is, we create a `RequestConverter.Params` object, mutate it, and then it appears nothing happens to it. This code is not broken though, because what is happening behind the scenes is that `request` is being mutated when methods on `parameters` are invoked. This indirectness and methods having side effects on another object lead to code that does not appear correct at first glance, and is more confusing than it should be; it looks wrong. Instead, I propose an alternative like:

```java
        final Request request = new Request(HttpPut.METHOD_NAME, endpoint);
        RequestConverters.Params parameters = new RequestConverters.Params();
        parameters.withWaitForActiveShards(putFollowRequest.waitForActiveShards());
        request.setParameters(parameters);
        request.setEntity(createEntity(putFollowRequest, REQUEST_BODY_CONTENT_TYPE));
```

This makes apparent that the `parameters` are actually used, and that they have an effect on the `request` object through explicit invocation. I believe this makes it more transparent what is occurring.

**Comment by hub-cap** [comment]
This makes way more sense. Ive added good first issue to this in case someone wants to pick it up. Feel free to assign me to a PR if anyone does pick it up.

**Comment by vedantseta** [comment]
@hub-cap I am on it. Will be sending a PR soon.

**Comment by kutty-kumar** [comment]
@vedantseta have you started working on this yet? if not i would like to pick this up.

**Comment by kutty-kumar** [comment]
@jasontedor  please check the above merge request.

**Comment by dwlizlo** [comment]
@kutty-kumar are you still working on this? Are you good with me picking this one up?

**Comment by ojasgulati** [comment]
@jasontedor @hub-cap Hello is anyone working on this issue? if not I would like to work on this. Also could you please guide me a little bit how should I get started? 😃

**Comment by jasontedor** [comment]
@ojasgulati There is a PR in progress; let us give the author of that PR a chance to bring it to completion.
