### ISSUE TITLE
Example rescore plugin sorted order is not used

### ISSUE THREAD

**Issue by henrywallace** [elastic/elasticsearch#39665]
Looking at the comment on the example rescore plugin here:

https://github.com/elastic/elasticsearch/blob/93034aff49df8ae0b6b15c311b0f369357f86534/plugins/examples/rescore/src/main/java/org/elasticsearch/example/rescore/ExampleRescoreBuilder.java#L163-L175

The `sortedByDocId` variable is not used anywhere. Is this comment vestigial, or the pipes not connected?

While on this topic, can this loop be explained?

https://github.com/elastic/elasticsearch/blob/93034aff49df8ae0b6b15c311b0f369357f86534/plugins/examples/rescore/src/main/java/org/elasticsearch/example/rescore/ExampleRescoreBuilder.java#L181-L185

**Comment by jimczi** [comment]
Thanks for reporting @henrywallace , this looks like a bug, the for loop should use the order of the `sortedByDocId` array otherwise the assumption that doc ids are ordered is broken.
I guess that the rest test is too simple to hit the issue, would you be interested in fixing this ?

**Comment by henrywallace** [comment]
@jimczi I'd be very happy to give this a shot.

Any intuition on the second while loop? Where it seems we traverse the leaves. I'll be happy to add a comment to that as well.

**Comment by jimczi** [comment]
> Any intuition on the second while loop? Where it seems we traverse the leaves. I'll be happy to add a comment to that as well.

It seems ok to me, we're trying to find the leaf responsible for the current doc and since docs are sorted (or should be sorted ;) ) we can advance the iterator until we find it.

**Comment by jtibshirani** [comment]
Hello @henrywallace, I wanted to check if you were still interested in submitting a PR?

**Comment by pmpailis** [comment]
A [PR ](https://github.com/elastic/elasticsearch/pull/100189) to address the above has now been merged. In addition to changing from `topDocs` to `sortedByDocId` when iterating through the docids, we also added a test to cover the case described in this ticket.
