### ISSUE TITLE
Encountered a retryable error. Will Retry with exponential backoff ；code=>400 vs 6.5.1

### ISSUE THREAD

**Issue by sunchanglong1991** [elastic/elasticsearch#39674]
version:  6.5.1
Plugins :  logstash-output-elasticsearch
OS version: centos 7.0
java -version: 1.8.0

I am using Logstash to transferring data to Elasticsearch.

logstash.conf

Description: 
`input {
  udp {
    port => 55144
    type => "log"
  }
}
output {
  stdout { codec => rubydebug }

  elasticsearch {
        hosts => ["******"]
        index => "alarm"
        document_type => "udp"
        manage_template => true
        template => "/etc/template/logstash_***.json"
        template_name => "***_template"
        template_overwrite => true
    } 
}`

After starting logstash it just keeps giving logs like below:

> [2019-03-05T06:30:00,457][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"http://elasticsearch.topesc:9200/_bulk"}
> [2019-03-05T06:30:01,546][ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"http://elasticsearch.topesc:9200/_bulk"}
> 

the output  _**Codec => ruby ​​debug**_ can output log data, but logstash.outputs.elasticsearch reports an error with

[ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff {:code=>400, : Url=>"http://******:9200/_bulk"}

Elasticsearch does not have any log output,In addition, Elasticsearch is starting and has no error message about this.

Can you please give some advice on this? Thanks very much!

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
