### ISSUE TITLE
[ML] Delete Forecast : REST JSON inconsistency

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch#39673]
The documentation (https://www.elastic.co/guide/en/elasticsearch/reference/6.5/ml-delete-forecast.html) indicates that `<forecast_id>` is optional, and the REST JSON specification indicates this too (https://github.com/elastic/elasticsearch/blob/9e8cfbb40d7596eb56151fc8a30234fb336c0a43/x-pack/plugin/src/test/resources/rest-api-spec/api/ml.delete_forecast.json#L19).

The issue is, however, is that the `RestDeleteForecastAction` registration only registers URLs that contain the `<forecastid>` parameter (https://github.com/elastic/elasticsearch/blob/fc76bcbfe0a3c3874271f9d8f3443187e91f6941/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestDeleteForecastAction.java#L24).

The .NET client, when calling a URL without the `<forecastid>` defaults to a `DELETE` verb on `_xpack/ml/anomaly_detectors/<job_id>/_forecast`. The server then responds with a `405` error and that the endpoint accepts a `POST` - at this point the server likely assumes this request was intended to post a record - albeit an incorrect assumption.

In the meantime I have patched the REST JSON spec locally to make `<forecastid>` a required field and everything then works as expected: https://github.com/elastic/elasticsearch-net/blob/4aa8ad121cd4830afe98f1dbcdcc3790fd2e291d/src/CodeGeneration/ApiGenerator/RestSpecification/XPack/MachineLearning/xpack.ml.delete_forecast.patch.json

---

Can a fix be considered along the lines of:
- Register correct REST endpoint url for `DELETE` action.
or
- Make `<forecastid>` required.

**Comment by droberts195** [comment]
> * Register correct REST endpoint url for `DELETE` action

This should be the fix, as the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-delete-forecast.html) are clear that not specifying `<forecastid>` is permitted.

We should also check that the HLRC is works when no forecast ID is supplied.
