### ISSUE TITLE
Feature request for simple_query_string flag names

### ISSUE THREAD

**Issue by maziyarpanahi** [elastic/elasticsearch#39735]
Hi,

This is a feature request following up the conversation here: https://discuss.elastic.co/t/query-string-needs-an-excludes-option/166427

Considering most users know how to create Query Strings by using `AND` `OR` operations, is it possible to allow the use of `AND` `OR` instead of `+` `|`? Obviously, if the developers decide to enable this option to switch those symbolic flags to string flags, otherwise by default it can be what it is right now.

Thank you.
Maziyar

**Comment by glgomess** [comment]
Hi there! Can i work on this?

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
