### ISSUE TITLE
how to put Geo_type mapping with JsonObject

### ISSUE THREAD

**Issue by SenalChen** [elastic/elasticsearch#39733]
Hi @iverase, can I use :
IndexResponse createData(Client client, String jsonObject,
String index, String type, String id);
to put Geo_type and other mappings?
I used Map resolve this issue,but I also don't know how to save PolygonBuilder to a Object and then Object to json, and then put json to Elasticsearch, if u see this issue, pls tell how to do it.Thank you very much!

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
