### ISSUE TITLE
multi_match query crashes with NumberFormatException

### ISSUE THREAD

**Issue by eltu** [elastic/elasticsearch#3975]
When execute this simple example it crashes:

    curl -XPUT http://localhost:9200/blog/post/1?pretty=1 -d '{"foo":123, "bar":"xyzzy"}'

    curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query": {"multi_match": {"fields": ["foo", "bar"], "query": "xyzzy", "useDisMax": true}}}'

stack trace:
{
"error" : "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[BIXGo8_wTEiO9jVc0KjZ_w][blog][1]: SearchParseException[[blog][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\": {\"multi_match\": {\"fields\": [\"foo\", \"bar\"], \"query\": \"xyzzy\", \"useDisMax\": true}}}]]]; nested: NumberFormatException[For input string: \"xyzzy\"]; }{[BIXGo8_wTEiO9jVc0KjZ_w][blog][0]: SearchParseException[[blog][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\": {\"multi_match\": {\"fields\": [\"foo\", \"bar\"], \"query\": \"xyzzy\", \"useDisMax\": true}}}]]]; nested: NumberFormatException[For input string: \"xyzzy\"]; }{[BIXGo8_wTEiO9jVc0KjZ_w][blog][4]: SearchParseException[[blog][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\": {\"multi_match\": {\"fields\": [\"foo\", \"bar\"], \"query\": \"xyzzy\", \"useDisMax\": true}}}]]]; nested: NumberFormatException[For input string: \"xyzzy\"]; }{[BIXGo8_wTEiO9jVc0KjZ_w][blog][2]: SearchParseException[[blog][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\": {\"multi_match\": {\"fields\": [\"foo\", \"bar\"], \"query\": \"xyzzy\", \"useDisMax\": true}}}]]]; nested: NumberFormatException[For input string: \"xyzzy\"]; }{[BIXGo8_wTEiO9jVc0KjZ_w][blog][3]: SearchParseException[[blog][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\": {\"multi_match\": {\"fields\": [\"foo\", \"bar\"], \"query\": \"xyzzy\", \"useDisMax\": true}}}]]]; nested: NumberFormatException[For input string: \"xyzzy\"]; }]",
"status" : 400
}

**Comment by felipelrz** [comment]
@clintongormley, what if I do want to include numeric fields in a multi_match query? What is the best approach, in this particular case?

**Comment by clintongormley** [comment]
Hmm, the more I think about this, the more I think that we should handle this better.

A query string query like:

    GET /t/_validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "bar 1",
          "fields": ["text","num"],
          "lenient": true
        }
      }
    }

results in:

    "(text:bar) (text:1 | num:[1 TO 1])"

while the equivalent multi-match just ignores the `num` field completely:

    "((text:bar text:1))"

However, a multi-match query for just a number seems to work:

    GET /t/_validate/query?explain
    {
      "query": {
        "multi_match": {
          "query": "1",
          "fields": ["text","num"],
          "lenient": true
        }
      }
    }

    "(num:[1 TO 1] | text:1)"

Possibly, when using the `lenient` option on numeric fields, we should apply a whitespace analyzer to the string and discard anything which isn't a number.

**Comment by bleskes** [comment]
The `lenient` flag current let you ignore values that don't fit specific fields (like when you try to search a numeric field with a string value that doesn't convert to a number). We discussed it and we feel this is good enough. It would be an overkill to try to parse the string looking for numbers in it. I'm closing this as I think @eltu 's issue is covered by this. @clintongormley if you feel differently, I think we should have a different issue for it and re-discuss.

**Comment by jreinke** [comment]
The `lenient` parameter seems to be ignored when using `cross_fields` type and multiple numeric fields:

```
curl -XPUT http://localhost:9200/blog/post/1?pretty=1 -d '{"foo":123, "bar":"xyzzy", "baz":456}'
```
**Search is OK with 1 numeric field**
```
curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query": {"multi_match": {"type": "cross_fields", "query": "xyzzy", "lenient": true, "fields": ["foo", "bar"]}}}'
```
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.30685282,
    "hits" : [ {
      "_index" : "blog",
      "_type" : "post",
      "_id" : "1",
      "_score" : 0.30685282,
      "_source":{"foo":123, "bar":"xyzzy", "baz":456}
    } ]
  }
}
```
**Search fails with 2 numeric fields**
```
curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query": {"multi_match": {"type": "cross_fields", "query": "xyzzy", "lenient": true, "fields": ["foo", "bar", "baz"]}}}'
```
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "number_format_exception",
      "reason" : "For input string: \"xyzzy\""
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "blog",
      "node" : "0TxGVVWsSu2qX63hZdOv2w",
      "reason" : {
        "type" : "number_format_exception",
        "reason" : "For input string: \"xyzzy\""
      }
    } ]
  },
  "status" : 400
}
```

Am I missing something?

**Comment by FabianKoestring** [comment]
`lenient` works perfectly for me.
