### ISSUE TITLE
Release tests failing: elasticsearch.yml (No such file or directory)

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#39753]
This build failed:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/526/consoleText

```
* What went wrong:
Execution failed for task ':qa:full-cluster-restart:v8.0.0#oldClusterTestCluster#node0.configure'.
> java.io.FileNotFoundException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/qa/full-cluster-restart/build/cluster/v8.0.0#oldClusterTestCluster node0/elasticsearch-8.0.0-SNAPSHOT/config/elasticsearch.yml (No such file or directory)
```

The master release tests seem to be persistently failing with this message.

**Comment by droberts195** [comment]
This is still failing in the same way.  Every release tests build fails like this so I won't paste all the links, but the most recent is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/534/console

**Comment by jkakavas** [comment]
These are still failing, latest: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/558/consoleText

**Comment by davidkyle** [comment]
Another 
```
> java.io.FileNotFoundException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/qa/full-cluster-restart/build/cluster/v8.0.0#oldClusterTestCluster node0/elasticsearch-8.0.0-SNAPSHOT/config/elasticsearch.yml (No such file or directory)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/563/console
