### ISSUE TITLE
Watcher documentation for Slack action is out-of-date

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#39760]
If you configure `elasticsearch.yml` per the instructions on [Configuring Watcher to Send Messages to Slack](https://www.elastic.co/guide/en/watcher/current/configuring-slack.html), you'll get a couple errors when you try to start Elasticsearch.

> Suppressed: java.lang.IllegalArgumentException: unknown setting [watcher.actions.slack.service.account.team1.message_defaults.from] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

> Suppressed: java.lang.IllegalArgumentException: unknown setting [watcher.actions.slack.service.account.team1.url] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

After discussion with @hub-cap and @jakelandis, I found that you need to configure the Slack account via secure settings (per the [Elastic Stack Overview Slack Action docs](https://www.elastic.co/guide/en/elastic-stack-overview/master/actions-slack.html#configuring-slack)) instead of via `elasticsearch.yml`.

Should we update the existing ES docs to have the same information as the Elastic Stack docs? Or just remove the outdated info and link to them instead?

**Comment by jrodewig** [comment]
@cjcenizal I've opened up #40410 to address this in the current Elasticsearch docs: https://www.elastic.co/guide/en/elastic-stack-overview/master/actions-slack.html#configuring-slack

I believe this is actually old Watcher documentation:
https://www.elastic.co/guide/en/watcher/current/configuring-slack.html

Having trouble digging up the source docs, but I think it's worth updating there as well.

**Comment by jrodewig** [comment]
Chatted with @debadair, and we agreed to not update the watcher documentation in the standalone x-pack docs.

However, #40410 should fix it for any support docs.
