### ISSUE TITLE
Rollup `delay` does not accept calendar time

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#39766]
Trying to set a calendar delay (`1M`, etc) fails because we proactively try to validate the value with a simple fixed-time parser.  This is buggy since we need to allow calendar time in case the interval is also calendar.  We should probably also prevent the user from setting mismatched intervals and delay types, but that might warrant a different bug :)

I think all we need to do is [loosen the validation](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rollup/job/DateHistogramGroupConfig.java#L111) to also check for calendar, but I haven't looked closely yet.

Reproduction:

```
{
 "index_pattern": ".k*",
 "rollup_index": "vvfdvdf",
 "cron": "0 0 0 ? * 7",
 "page_size": 1000,
 "groups": {
   "date_histogram": {
     "interval": "60m",
     "delay": "1M",
     "time_zone": "UTC",
     "field": "canvas-workpad.@timestamp"
   }
 }
}
```
Throws:

```
Request failed with a error. [x_content_parse_exception] Failed to build [date_histogram] after last required field arrived
* [1:171] [groups] failed to parse field [date_histogram]
* [1:171] [date_histogram] failed to parse field [field]
* Failed to build [date_histogram] after last required field arrived
* failed to parse setting [delay] with value [1M] as a time value: unit is missing or unrecognized
```

/cc @cjcenizal

**Comment by not-napoleon** [comment]
@csoulios This looks like we should just close it as won't fix, do you agree?

**Comment by csoulios** [comment]
@not-napoleon  I agree. This is a minor bug, more probably an incovenience. Since there is a workaround to it (use fixed interval), let's close it with "won't fix".

**Comment by not-napoleon** [comment]
Closing, won't fix.
