### ISSUE TITLE
Improve Watcher stop/start/restart API logging

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#39774]
6.6.0

We currently write very little information to the logs when the Watcher stop/stop/restart APIs are called.  Even at the trace level, we do not write anything about the start process when Watcher start/restart API is called.  The restart API only logs the following:

```
[2019-03-06T16:45:39,963][INFO ][o.e.x.w.WatcherService   ] [<node>] stopping watch service, reason [watcher manually marked to shutdown by cluster state update]
```
But it does not provide an indication of whether the stop is actually successfully or when the service is finally stopped.   It will be helpful to have additional logging at the INFO level when these APIs are called.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
