### ISSUE TITLE
Cannot start Elasticsearch 6.6.1 as a Windows service

### ISSUE THREAD

**Issue by glucaci** [elastic/elasticsearch#39784]
Elasticsearch version 6.6.1-oss installed from .zip on Windows Server 2016 Datacenter 10.0.14393 / 56GB RAM

`JAVA_HOME` is set as System Variable
```
elasticsearch-service.bat install

Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk-11.0.2"
-XX:+UseConcMarkSweepGC;-XX:CMSInitiatingOccupancyFraction=75;-XX:+UseCMSInitiatingOccupancyOnly;-XX:+AlwaysPreTouch;-server;-Xss1m;-Djava.awt.headless=true;-Dfile.encoding=UTF-8;-Djna.nosys=true;-Djdk.io.permissionsUseCanonicalPath=true;-Dio.netty.noUnsafe=true;-Dio.netty.noKeySetOptimization=true;-Dio.netty.recycler.maxCapacityPerThread=0;-Dlog4j.shutdownHookEnabled=false;-Dlog4j2.disable.jmx=true;-Dlog4j.skipJansi=true;-XX:+HeapDumpOnOutOfMemoryError;-Xmx14336m;-Xms14336m
The service 'elasticsearch-service-x64' has been installed.
```
Logs after `elasticsearch-service.bat start`
```
[2019-02-22 21:10:10] [info]  [21880] Commons Daemon procrun (1.1.0.0 64-bit) started
[2019-02-22 21:10:10] [info]  [21880] Running 'elasticsearch-service-x64' Service...
[2019-02-22 21:10:10] [info]  [19200] Starting service...
[2019-02-22 21:10:10] [error] [13880] CreateJavaVM Failed
[2019-02-22 21:10:10] [error] [13880] The system cannot find the file specified.
[2019-02-22 21:10:10] [error] [19200] Failed to start Java
[2019-02-22 21:10:10] [error] [19200] ServiceStart returned 4
[2019-02-22 21:10:10] [info]  [21880] Run service finished.
[2019-02-22 21:10:10] [info]  [21880] Commons Daemon procrun finished
```
Stderr and stdout has no aditional information.

Java options from `elasticsearch-service.bat manager`
```
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+AlwaysPreTouch
-server
-Xss1m
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-Djna.nosys=true
-Djdk.io.permissionsUseCanonicalPath=true
-Dio.netty.noUnsafe=true
-Dio.netty.noKeySetOptimization=true
-Dio.netty.recycler.maxCapacityPerThread=0
-Dlog4j.shutdownHookEnabled=false
-Dlog4j2.disable.jmx=true
-Dlog4j.skipJansi=true
-XX:+HeapDumpOnOutOfMemoryError
-Xmx14336m
-Xms14336m
-Delasticsearch
-Des.path.home=c:\elasticsearch-6.6.1
-Des.path.conf=E:\ElasticConfig
-Des.distribution.flavor=oss
-Des.distribution.type=zip
```

If i start `bin\elasticsearch.bat` from comand line is working. 
Before I installed the full version (6.6.1) also from .zip and had no problem.

_Originally posted by @glucaci in https://github.com/elastic/elasticsearch/issues/21917#issuecomment-466553905_

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be troubleshooting or a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by Nasidiqi** [comment]
Hi, 

I installed elasticsearch 7.5.1 on windows 10 using msi installer and it does not start when i test using localhost:9200.


log file has this error:
Java HotSpot(TM) 64-Bit Server VM (25.181-b13) for windows-amd64 JRE (1.8.0_181-b13), built on Jul  7 2018 04:01:33 by "java_re" with MS VC++ 10.0 (VS2010)
Memory: 4k page, physical 16484100k(9020924k free), swap 25921284k(15882124k free)
CommandLine flags: -XX:CMSInitiatingOccupancyFraction=75 -XX:ErrorFile=logs/hs_err_pid%p.log -XX:GCLogFileSize=67108864 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:InitialHeapSize=2147483648 -XX:MaxHeapSize=2147483648 -XX:MaxNewSize=715829248 -XX:MaxTenuringThreshold=6 -XX:NewSize=715829248 -XX:NumberOfGCLogFiles=32 -XX:OldPLABSize=16 -XX:OldSize=1431654400 -XX:+PrintFlagsFinal -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseGCLogFileRotation -XX:-UseLargePagesIndividualAllocation -XX:+UseParNewGC 
Heap
 par new generation   total 629120K, used 22369K [0x0000000080000000, 0x00000000aaaa0000, 0x00000000aaaa0000)
  eden space 559232K,   4% used [0x0000000080000000, 0x00000000815d8698, 0x00000000a2220000)
  from space 69888K,   0% used [0x00000000a2220000, 0x00000000a2220000, 0x00000000a6660000)
  to   space 69888K,   0% used [0x00000000a6660000, 0x00000000a6660000, 0x00000000aaaa0000)
 concurrent mark-sweep generation total 1398144K, used 0K [0x00000000aaaa0000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 2178K, capacity 4480K, committed 4480K, reserved 1056768K
  class space    used 245K, capacity 384K, committed 384K, reserved 1048576K


What to do to resolve this issue?

**Comment by MohitRane** [comment]
Did anyone found solution?
