### ISSUE TITLE
ClassCastException returned when calling Watcher Stats API endpoint

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#39780]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.3

**Plugins installed**: []

**JVM version** (`java -version`): 

java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Windows 10 Pro 64 bit.

```powershell
> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0
```

**Description of the problem including expected versus actual behavior**:

ClassCastException returned when calling Watcher Stats API endpoint:

>  "java.util.concurrent.FutureTask cannot be cast to org.elasticsearch.xpack.watcher.execution.ExecutionService$WatchExecutionTask"

**Steps to reproduce**:

As part of the integration tests for the .NET client, the [Watcher Stats API tests](https://github.com/elastic/elasticsearch-net/blob/7bef2ca95e0b58662e2cc46192e3698ddff7de0a/src/Tests/Tests/XPack/Watcher/WatcherStats/WatcherStatsApiTests.cs) (`GET /_xpack/watcher/stats/_all?pretty=true&error_trace=true`) return the following error response:

```json
Seeing a Watcher related error when running the .NET client integration tests against 6.5.3. The test for getting the watcher stats (`GET: /_xpack/watcher/stats/_all?pretty=true&error_trace=true`) is returning:

{
  "_nodes" : {
    "total" : 1,
    "successful" : 0,
    "failed" : 1,
    "failures" : [
      {
        "type" : "failed_node_exception",
        "reason" : "Failed node [Rn1e1D_ET9qY10uO80BpNA]",
        "node_id" : "Rn1e1D_ET9qY10uO80BpNA",
        "caused_by" : {
          "type" : "class_cast_exception",
          "reason" : "java.util.concurrent.FutureTask cannot be cast to org.elasticsearch.xpack.watcher.execution.ExecutionService$WatchExecutionTask"
        }
      }
    ]
  },
  "cluster_name" : "ephemeral-cluster-fc0970",
  "manually_stopped" : false,
  "stats" : [ ]
}
```

This looks like it might be an internal exception as opposed to an exception initiated by the action of the test. 

The test [sets up a watch as part of the setup](https://github.com/elastic/elasticsearch-net/blob/7bef2ca95e0b58662e2cc46192e3698ddff7de0a/src/Tests/Tests/XPack/Watcher/WatcherStats/WatcherStatsApiTests.cs#L35-L57) and then [executes that watch just before calling the Watcher Stats API endpoint](https://github.com/elastic/elasticsearch-net/blob/7bef2ca95e0b58662e2cc46192e3698ddff7de0a/src/Tests/Tests/XPack/Watcher/WatcherStats/WatcherStatsApiTests.cs#L63-L76). Since the tests that run against an `XPackCluster` can run concurrently however, it is entirely possible that there are other watches with specific states that could also be returned in the Watcher Stats response which is causing this error, so it _may_ not reproduce with just the watch that is set up; I've run this test a few times in isolation and not seen the error response.

**Comment by jasontedor** [comment]
I opened #39821.
