### ISSUE TITLE
How can i store 128-array and then get similar by euclidian distance?

### ISSUE THREAD

**Issue by psyapathy** [elastic/elasticsearch#39786]
Hello all!
How can i store 128-array and then get similar by euclidian distance?

I have few 128array like:
[1.0, 2.0, 3.0 ...... 128.]

I want store them in elasticsearch and than search most similar array for array [1.1, 2.0, 3.2 .... 128.3] by euclidian distance.

Is it possible?

I saw that now we are working on [dense_vectors](https://github.com/mayya-sharipova/elasticsearch/commit/63be842d9c59b0e863dfef4d67c4cc5a733acb81)
But this is now for beta and quering will be possible in 7.1.1

Thank you advance for reply!

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
