### ISSUE TITLE
Docs: SQL updates

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#39794]
A list of doc fixes that we'd like to address:

- [ ] How SQL performs exact value matching
- [ ] Scroll vs Composite Aggs (non-grouped vs grouped queries)
- [ ] Expand MATCH/QUERY and other full-text search queries

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by lockewritesdocs** [comment]
This issue is 3+ years old and hasn't had updates, so I'm closing it. Feel free to reopen if the appropriate area team has resources to contribute.
