### ISSUE TITLE
SQL: don't fold constants if it results in non-json serializable script params 

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#39798]
We are currently folding constants as much as we can, which can sometimes results in generating parameters that cannot be serialized either by json or by both json and stream IO. To understand the issue, consider the following example:

```
DELETE test
PUT test
{
  "mappings": {
      "properties": {
        "timestamp": {
          "type": "date"
        }
      }
  }
}

PUT test/_doc/1
{
  "timestamp": "2019-03-05T21:23:19.000Z"
}

POST _sql?format=txt
{
  "query": "SELECT timestamp AS a  FROM test WHERE timestamp + INTERVAL '1' DAY > CONVERT('2019-03-05T21:23:19.000Z', SQL_TIMESTAMP)"
}
```

This example works and returns one result as expected. However, if we run the `_sql/translate` command on it and try to execute it against elastic we will get no results:

```
POST _sql/translate
{
  "query": "SELECT timestamp AS a  FROM test WHERE timestamp + INTERVAL '1' DAY > CONVERT('2019-03-05T21:23:19.000Z', SQL_TIMESTAMP)"
}

POST test/_search
{
  "size" : 1000,
  "query" : {
    "script" : {
      "script" : {
        "source" : "InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.gt(InternalSqlScriptUtils.add(InternalSqlScriptUtils.docValue(doc,params.v0),InternalSqlScriptUtils.intervalDayTime(params.v1,params.v2)),params.v3))",
        "lang" : "painless",
        "params" : {
          "v0" : "timestamp",
          "v1" : "PT24H",
          "v2" : "INTERVAL_DAY",
          "v3" : "2019-03-05T21:23:19.000Z"
        }
      },
      "boost" : 1.0
    }
  },
  "_source" : false,
  "stored_fields" : "_none_",
  "docvalue_fields" : [
    {
      "field" : "timestamp",
      "format" : "epoch_millis"
    }
  ],
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}
```

The reason for the failure is in the `v3` parameter of the script:
```
InternalSqlScriptUtils.nullSafeFilter(
  InternalSqlScriptUtils.gt(
    InternalSqlScriptUtils.add(
      InternalSqlScriptUtils.docValue(doc,params.v0),
      InternalSqlScriptUtils.intervalDayTime(params.v1,params.v2)
    ),
    params.v3
  )
)
 ```
The third parameter is ZonedDateTime object which can be serialized over stream IO and therefore can be sent over in a search request. As a result the query doesn't fail when it is executed inside SQL. However, when we try to generate JSON request the resulted `ZonedDateTime` object in third parameter is serialized as the string ` "2019-03-05T21:23:19.000Z"` which is passed to `InternalSqlScriptUtils.gt(..., ....)` that compares this string and `ZonedDateTime` returned by `add(...)` and returns `false`. A similar problem exists if we replace  `> CONVERT('2019-03-05T21:23:19.000Z', SQL_TIMESTAMP)` with `< NOW()`. `NOW()` generates `ZonedDateTime` which is serialized as a string and we again end up with string to date comparison.

The problem is even more pronounced with geo objects in `geosql` branch since there is no support for stream io serialization of these objects at the moment, so if `ST_WKTTOSQL('POINT (10 20))` is folded as a script parameter, such request would only work on a single node and file in a distributed environment where search requests (with painless parameters) are serialized and sent to another machine. 
 
I am not really sure what's the best way to deal with this. So, I would like to solicit ideas and start a discussion on how to deal with it.

**Comment by imotov** [comment]
I just discovered an additional related complication that kicks in if we have more data than fits on a single page. If we have a folded ConstantProcessor that needs to be serialized, it [will try to serialize](https://github.com/elastic/elasticsearch/blob/15515a616ebb8dc9d1fa100baab2641b09b92776/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/processor/ConstantProcessor.java#L29) the wrapped constant as a genericValue. That works only for some types. To reproduce:
```
DELETE test
PUT test
{
  "mappings": {
      "properties": {
        "timestamp": {
          "type": "date"
        }
      }
  }
}

PUT test/_doc/1
{
  "timestamp": "2019-03-05T21:23:19.000Z"
}

PUT test/_doc/2
{
  "timestamp": "2019-03-05T21:23:19.000Z"
}

PUT test/_doc/3
{
  "timestamp": "2019-03-05T21:23:19.000Z"
}

PUT test/_doc/4
{
  "timestamp": "2019-03-05T21:23:19.000Z"
}

POST _sql
{
  "query": "SELECT timestamp + INTERVAL '1' DAY AS a  FROM test",
  "fetch_size": 2
}
```
This will generate the error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Unexpected failure retriving next page"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Unexpected failure retriving next page",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "can not write type [class org.elasticsearch.xpack.sql.expression.literal.IntervalDayTime]"
    }
  },
  "status": 500
}
```

```
[elasticsearch] Caused by: java.io.IOException: can not write type [class org.elasticsearch.xpack.sql.expression.literal.IntervalDayTime]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:758) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.expression.gen.processor.ConstantProcessor.writeTo(ConstantProcessor.java:29) ~[?:?]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:994) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.expression.gen.processor.BinaryProcessor.writeTo(BinaryProcessor.java:30) ~[?:?]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:994) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.execution.search.extractor.ComputingExtractor.writeTo(ComputingExtractor.java:54) ~[?:?]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:994) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteableList(StreamOutput.java:1113) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.execution.search.ScrollCursor.writeTo(ScrollCursor.java:61) ~[?:?]
[elasticsearch]         at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:994) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.session.Cursors.encodeToString(Cursors.java:75) ~[?:?]
[elasticsearch]         ... 31 more
```

Please note that the error message `Unexpected failure retriving next page` is misleading since we are not retrieving the next page yet here, we are just preparing the cursor to retrieve this page later on.

**Comment by costin** [comment]
This issue actually bumped into two bugs, both related to some degree to serialization:
1. ConstantProcessor handling of complex objects - see #39875
2. serialization `ZoneDateTime` to a human/json-friendly format - incoming PR.

**Comment by imotov** [comment]
> serialization ZoneDateTime to a human/json-friendly format - incoming PR

I think serialization actually works, it's deserialization on the painless side is where we fail.

**Comment by costin** [comment]
Forgot to update the second PR: https://github.com/elastic/elasticsearch/pull/39911

**Comment by imotov** [comment]
This approach works for geosql as well. Closing.
