### ISSUE TITLE
Logging of MapperParsingException

### ISSUE THREAD

**Issue by dr0i** [elastic/elasticsearch#39832]
Feature request:
<TL;DR>We would like to decrease the amount of _query_ log messages, while at the same time not missing dropped documents when _indexing_.</TL;DR>

Indexing a document using the java api may result in a `MapperParsingException` (MPE). When bulk-indexing, the problematic document is logged by elasticsearch , but only if the elasticsearch log level is set to `debug`. This produces a lot of "query"-debug log messages (for us 0.5GB daily) coming from problematic queries. While these are deliberately ignored by us, the important `MPE` occurs very rarely (and then it produces little log messages, maybe 0.5KB).

Two possibilities come into mind:
1. increase log level to at least `info` when an `MPE` occurs
2. as 1. could vice versa be annoying for people who don't care so much of dropped information when indexing it would be very smart to be able to configure separately a log level for a) query and b) indexing.

The first option(increasing log level) would be easy to implement.

**Comment by mayya-sharipova** [comment]
@dr0i Thanks for filling the issue.

Firstly, we are wondering why do you need to analyze logs to look for `MapperParsingException`?  We return exceptions to clients, so you can just analyze the results from your requests:
e.g.:
```js
        "error": {
          "type": "mapper_parsing_exception",
          "reason": "failed to parse field [my_long] of type [long]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "For input string: \"wrong_input\""
          }
        }
```
Is there any exception that doesn't get returned to a client, but you can see in the logs?

Secondly, elasticsearch configuration has `log4j2.properties` file that allows you to configure log level per class. For example, you can set up `debug` level to bulk indexing like this:

```java
logger.shard_bulk.name = org.elasticsearch.action.bulk.TransportShardBulkAction
logger.shard_bulk.level = debug
```

**Comment by dr0i** [comment]
@mayya-sharipova Thx for this input - configuring log level per class sounds like the solution for my issue! I will try this.

Re: catching MapperParsingException: I had the impression that catching Exceptions of BulkRequests don't return this exception (at least not for version 5.6.3).

I will let you know if it works.

**Comment by dr0i** [comment]
Uh - you are completeley right!
Even the Exceptions of BulkRequests _are indeed_  returned, as `WARN` via the `BulkResponse.class` (even also returning the `id` of the document). How could I miss that?
Sorry for this unnecessary question here and thanks again for your help!
