### ISSUE TITLE
[docs] Upgrade page assumes on-prem, is incorrect for Cloud

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#39849]
**Describe the feature**:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

This page has a table claiming that one may perform a rolling upgrade from 5.6 to 6.x. However this is true only for on-prem. In Cloud, a full restart is required.

This is due to some technical details of how SSL is implemented on 5.6 in Cloud. There is a caveat about SSL on the doc page, but someone with a Cloud cluster who reads it would assume they were covered, because technically SSL is enabled in Cloud. Irrespective of this, the main problem is the table. That's what people will see when the skim the doc, so that will be their takeaway. My suggestion would be to change the table cell to something like "Full Restart (Cloud) / Rolling Restart (on-prem, SSL-enabled)".

**Comment by debadair** [comment]
[docs issue triage]
