### ISSUE TITLE
[CI] BuildExamplePluginsIT testCurrentExamplePlugin fails in FIPS JVM

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#39855]
`BuildExamplePluginsIT testCurrentExamplePlugin` was failing globally for a long time, but most problems were fixed in #38899.  However, it still consistently fails in the FIPS JVM:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/285/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/285/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/286/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/286/console

The error is:

```
    Execution failed for task ':integTestCluster#wait'.
    > Failed to locate seed node transport file [/tmp/junit7423325524789213283/build/cluster/integTestCluster node0/elasticsearch-8.0.0-SNAPSHOT/logs/transport.ports]: timed out waiting for it to be created after 40 seconds
```

**Comment by tvernum** [comment]
That the build is failing on _this_ integration test is coincidental. It's actually failing on _all_ integration tests due to #38013.

I need to look into _exactly why_.

**Comment by tvernum** [comment]
I have tracked it down, and it's actually a pretty big deal.

It turns out that up until #38013 and #39732, the `ClusterFormationTasks` would use `JAVA_HOME` (not `compiler.java` or `runtime.java`) to run the integration test cluster.

That means our `integTest` tasks have never run on a FIPS JVM until now. And they don't work.

**Comment by tvernum** [comment]
If we get agreement that we want to keep using `runtime.java`, I think it might be worth closing this issue, and opening a general "Make Integration tests work on FIPS" issue.

**Comment by danielmitterdorfer** [comment]
There have been ~ 30 more of these test failures over the weekend; mentioning each and every one of them here will just add noise IMHO but the failure can be reproduced with the following reproduction line (assuming a FIPS JVM is installed at `$JAVA8FIPS_HOME`):

```
export RUNTIME_JAVA_HOME=$JAVA8FIPS_HOME
./gradlew :example-plugins:painless-whitelist:integTest
```

I agree with @tvernum's proposal that we should aim to make our integrations work in a FIPS JVM. However, I do wonder whether for the time being we want to implement a workaround to restore the old behavior to avoid spurious build failures.
