### ISSUE TITLE
Could I apply multiple pipelines in 1 Elasticsearch index?

### ISSUE THREAD

**Issue by godlockin** [elastic/elasticsearch#39871]
ES v6.5.2, 3 nodes ... (will append other useful info if necessary)

I met a use case that when I insert data into my index, I need to do several things:
1. check if 2 field exists, if not set the default for it
2. auto add timestamp of insert time

the mapping I used:
> {
  "mappings": {
    "_doc": {
      "properties": {
        "id": {
          "type": "keyword"
        },
        "ingest_timestamp": {
          "type": "date"
        },
        "pDate": {
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis",
          "type": "date"
        },
        "pDateTime": {
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis",
          "type": "date"
        },
        "sentiment": {
          "type": "keyword"
        },
        "appName": {
          "type": "keyword"
        }
      }
    }
  },
  "settings": {
    "number_of_replicas": 0,
    "number_of_shards": 1,
    "default_pipeline": "defaultSentimentConditionPipeline"
  }
}

some functional fields ignore, the fields I need to check & set default is 'appName' and 'sentiment', fake code like:

> if sentiment == '' || sentiment == null
  sentiment = "neutral"

if appName == '' || appName == null
  appName = "myApp"

and I also need to set the 'ingest_timestamp' as the doc's insert time, which I applied the pipeline as

> "timestamp_pipeline": {
"description": "Add insert timestamp",
"processors": [
{
"set": {
"field": "ingest_timestamp",
"value": "{{_ingest.timestamp}}"
}
}
]
}

now this is a block in front of me that how can I add these 3 works into 1 pipeline as there are several data import jobs which I can't handle all of their logic. I've tried the pipeline config like this, but somehow it doesn't work :(

> "defaultSentimentConditionPipeline": {
"description": "set default sentiment condition pipeline",
"processors": [
{
"pipeline": {
"if": "ctx.sentiment == '' || ctx.sentiment == null",
"name": "defaultSentimentPipeline"
}
}
,
{
"pipeline": {
"if": "ctx. appName == '' || ctx. appName == null",
"name": "defaultAppNamePipeline"
}
}
,
{
"set": {
"field": "ingest_timestamp",
"value": "{{_ingest.timestamp}}"
}
}
]
}

> "defaultSentimentPipeline": {
"description": "set default sentiment",
"processors": [
{
"set": {
"field": "sentiment",
"value": "neutral"
}
}
]
}

> "defaultAppNamePipeline": {
"description": "set default appname",
"processors": [
{
"set": {
"field": "appName",
"value": "myApp"
}
}
]
}

any suggestions for this folks?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
