### ISSUE TITLE
use json processor to deal with json array?

### ISSUE THREAD

**Issue by SuperNoobTao** [elastic/elasticsearch#39902]
**Elasticsearch version** (`bin/elasticsearch --version`):5.5

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):

**Steps to reproduce**:

Hello，I have a problem when i used . I want to use json processor to deal with a jaon array like this:
[{\"foo\": 2000},{\"foo\": 2001}]  . But it can not  work. Is it just support json object instead of json array?
if so , how to deal with json array? writing a custom pipeline processor?

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
