### ISSUE TITLE
Build fails to configure Minio Tests

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#39919]
We see build failures on 6.6 builds e.g. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=amazon/164/console. Similarly, BWC tests that involve 6.6 also fails to build the 6.6 branch, e.g. in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+corretto-periodic/ES_BUILD_JAVA=java11,label=amazon/65/console). Here is an example build failure output:

```
15:19:40 > Could not get unknown property 'composeUp' for project ':plugins:repository-s3' of type org.gradle.api.Project.
15:19:40 Publishing build scan...
15:19:40 
15:19:40 * Try:
15:19:40 Run with --debug option to get more log output. Run with --scan to get full insights.
15:19:40 
15:19:40 * Exception is:
15:19:40 org.gradle.api.GradleScriptException: A problem occurred evaluating project ':plugins:repository-s3'.
[...]
]15:19:40 Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'composeUp' for project ':plugins:repository-s3' of type org.gradle.api.Project.
15:19:40 	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
15:19:40 	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.getMissingProperty(BasicScript.java:155)
15:19:40 	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
15:19:40 	at org.gradle.groovy.scripts.BasicScript.getProperty(BasicScript.java:64)
15:19:40 	at build_daop56ntt2y5e8m21e5tj4k9z.run(/var/lib/jenkins/workspace/elastic+elasticsearch+6.6+multijob-unix-compatibility/os/amazon/plugins/repository-s3/build.gradle:171)
15:19:40 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
15:19:40 	... 119 more
```

This has been introduced in #38973 which I have reverted in 3d5f521a848 on branch `6.6` as a first measure. @talevy can you please look at this?

**Comment by talevy** [comment]
thanks for reverting the change @danielmitterdorfer! Definitely unexpected

**Comment by talevy** [comment]
I am inclined to leave it reverted in 6.6 pending further guidance from @original-brownbear.

**Comment by original-brownbear** [comment]
@talevy phew, unless @atorok knows of a quick fix here (note that this passed CI just fine before merging) I'd be inclined to simply give up and close this since it's `6.6` and the effort to make it work is probably not worth it?

**Comment by talevy** [comment]
thanks Armin. I'll wait for Alpar's feedback here, but I expect this will be ok to close. If no update by tomorrow, I will simply close.

**Comment by atorok** [comment]
Some of the test fixtures changes are not backpacked that far back, so I suspect it's failing because there's a missing change to handle CI workers without docker. 
Not convinced it's worth the effort to backport.

**Comment by original-brownbear** [comment]
thanks @atorok => closing this then :)

**Comment by talevy** [comment]
thanks all. I had good intentions 😄no point in working more
