### ISSUE TITLE
[Rollup] Support other metrics (percentiles)

### ISSUE THREAD

**Issue by mrebmeister** [elastic/elasticsearch#39912]
Capability to define new metrics like percentiles and percentile ranks in rollup indices.

**Comment by polyfractal** [comment]
Hi @mrebmeister, thanks for the ticket.  We agree, it would be great to support percentiles, cardinality, etc.  We have an open ticket tracking that feature enhancement here: https://github.com/elastic/elasticsearch/issues/33214

I'm going to close this in favor of #33214
