### ISSUE TITLE
Failing tests :test:framework:unitTest 

### ISSUE THREAD

**Issue by Sandmannn** [elastic/elasticsearch#39939]
Trying to run the basic test suite on Windows 10, during the task ` Task :test:framework:unitTest` following tests are not passing: 

```
org.elasticsearch.transport.nio.SimpleMockNioTransportTests.testTimeoutPerConnection
org.elasticsearch.transport.nio.SimpleMockNioTransportTests.testTcpHandshakeTimeout
org.elasticsearch.transport.nio.SimpleMockNioTransportTests.testTcpHandshakeConnectionReset
```

This comment https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java#L1926-L1934 hints that maybe these tests are platform dependent. In case some specific features of my system are needed I would be happy to provide.

**Comment by jtibshirani** [comment]
Hi @Sandmannn, these tests should pass on Windows 10 (and are passing now in our CI).

Would you be able to head over to our [discuss forums](https://discuss.elastic.co/) and start a topic that includes the errors you're seeing, as well as some basic information about your set-up (OS information, Java version, elasticsearch branch)? We prefer to use the discuss forums for this sort of debugging, which is likely specific to your machine configuration.

**Comment by Sandmannn** [comment]
Hi, yes, lets close this issue if this is wrong place to address it. I confirm that it is most likely something specific to my machine.
