### ISSUE TITLE
[docs] xpack.monitoring.collection.cluster.stats.timeout seems to be not Dynamic in current document

### ISSUE THREAD

**Issue by dharada** [elastic/elasticsearch#39947]
Docs for `xpack.monitoring.collection.cluster.stats.timeout` should be updated ?  (confirmation needed)
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/monitoring-settings.html#monitoring-collection-settings

It seems we can set  `xpack.monitoring.collection.cluster.stats.timeout` dinamically by cluster setting API.

like this

```
PUT /_cluster/settings
{
    "persistent" : {
        "xpack.monitoring.collection.cluster.stats.timeout" : "20s"
    }
}
```
but according to the current document, it is **NOT** Dynamic.

**Elasticsearch version** (`bin/elasticsearch --version`): ES 6.4.2

**Plugins installed**: []

**JVM version** (`java -version`): java 8

**OS version** (`uname -a` if on a Unix-like system):  Linux

**Description of the problem including expected versus actual behavior**:

Could you please confirm the current document is correct or not?  (if not correct, please revise it.)

**Comment by jakelandis** [comment]
> Docs for xpack.monitoring.collection.cluster.stats.timeout should be updated ? 

Indeed they do need an update. A quick check shows that many (most/all?) settings listed on that page are indeed dynamic but not listed as such. The page should be probably be changed to state all (but if any) settings are dynamic.
