### ISSUE TITLE
Elasticsearch5.6.12 Memery OOM

### ISSUE THREAD

**Issue by 32328254** [elastic/elasticsearch#39945]
Platform:centos
system:Centos7.2
Elasticesearch Version:5.6.12
java_version:1.8.0_144

jvm configuration：jvm heap:31g -XX:+UseG1GC

elasticearch configuration:
     action.destructive_requires_name: true
     indices.breaker.fielddata.limit: 40%
     indices.breaker.request.limit: 20%
     indices.breaker.total.limit: 50%
     indices.fielddata.cache.size: 30%
     indices.memory.index_buffer_size: 20%
     indices.memory.max_index_buffer_size: 2gb
     indices.memory.min_index_buffer_size: 128mb
     indices.recovery.max_bytes_per_sec: 800mb
     indices.requests.cache.size: 1%
     indices.store.throttle.max_bytes_per_sec: 800mb
     indices.store.throttle.type: none

The result of my analysis with the MAT tool is java.util.HashMap loaded by occcupy 8885297936(27.26%)bytes，io.netty.channel.socket.nio.NioSocketChannel $NiosocketChannelUnsafe loaded by java.net.FactoryURLClassLoader occupy 4311466624(13.23%)bytes.

**Comment by 32328254** [comment]
The analyzed data can be downloaded here：
URL：https://pan.baidu.com/s/1_kPdssWbxlLtCCFu01BQcA 
password：wlgl

**Comment by colings86** [comment]
@32328254  Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
