### ISSUE TITLE
Include a third highlight encoder

### ISSUE THREAD

**Issue by jdrossl** [elastic/elasticsearch#39979]
**Describe the feature**:

When using a field configured to use the `html_strip` char filter, it would be really useful to have a highlight encoder that also removes the html tags to provide only clean text.

Current result with `html` encoder:

```
"highlight": {
  "body_html": [
    "&lt;&#x2F;p&gt; &lt;h3&gt;&lt;em&gt;Maecenas&lt;&#x2F;em&gt; &lt;strong&gt;<em>faucibus&lt;&#x2F;strong&gt;</em> &lt;span style=&quot;text-decoration: line-through;&quot;&gt;mollis"
    ]
}
```

Expected result with the new encoder:

```
"highlight": {
  "body_html": [
    "Maecenas <em>faucibus</em> mollis"
   ]
}
```

There is so many people asking about this online and it could be a really simple solution instead of having to process each snippet on the client side

**Comment by jimczi** [comment]
I don't think this is the role of an encoder to remove the html tags. Encoders can be use to escape text for HTML output but removing the tags is out of the scope of this class IMO. The `html_strip` filter does not change the original text so I wonder if it could be useful to provide this filter as an [ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-processors.html) that you could use to store the raw text,  @elastic/es-core-features ?

**Comment by jakelandis** [comment]
@jdrossl - So the origin data contains HTML tags, and you wish to store a version without the HTML markup ?  If it is simple, like in the example, then [gsub processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/gsub-processor.html) may get you what you want. 

I would be [very hesitant](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags) to attempt to write an HTML extraction processor.

**Comment by jdrossl** [comment]
hi @jakelandis, my use case is this: I have a field with HTML content, when indexing I use the `htmp_strip` filter to remove the HTML tags from the index and be able to full text search on the contents, however during highlighting I need to get snippets without any HTML tags. With the `default` encoder sites would break and with the `html` decoder users would get a lot of HTML stuff that they don't care about. As a workaround, we ended duplicating the field before indexing to have a copy with the original markup and one with only text

**Comment by jakelandis** [comment]
> As a workaround, we ended duplicating the field before indexing to have a copy with the original markup and one with only text

Where and how do you do that duplication today ?

**Comment by jdrossl** [comment]
In our application, we copy the field with a different name that will be indexed as a `keyword` and remove the HTML markup from the original field. So for queries & highlight we use the original field (to get the right results and no markup in the snippets) and for any other purpose we use the copied field with the original content.

This was the only solution we found and we ended up not using the `html_strip` filter and wasting index space just to get highlights without markup.

**Comment by jimczi** [comment]
Thanks for answering @jakelandis and @jdrossl for explaining ;). If you're already able to remove the markup in your application can you apply it on the highlighted response instead of duplicating the field at index time ? We could also allow custom encoder via plugins in order to allow any kind of transformations/removals but I think that the default encoders should remain simple. Encoders are not aware of the char filters and analyzers that are used to index the text so removing markups could delete a snippet entirely. 
IMO the duplicate field solution is better and the compression that we apply on the stored fields should mitigate the growth of the index size. Can you share the mapping that you currently use ? Why are you using the `keyword` type for the field without the markup ?

**Comment by jdrossl** [comment]
hi @jimczi, we are using `keyword` on the copy of the field (the original is being analyzed as text), I know the encoders don't have anything to do with the filters but if there was an encoder that removes the markup before inserting the highlight tags they would work perfectly together. There are a couple of reasons to not handle the snippets in the client side:
- snippets might not have the full markup because of the size limit, so that could make hard to make sure everything is removed correctly
- the original markup of the field could use the same tag that is added by the highlighter so the snippet might have no highlight after all or more than one (from the user's perspective)

**Comment by martijnvg** [comment]
Some time ago a `html_strip` processor was added: https://www.elastic.co/guide/en/elasticsearch/reference/master/htmlstrip-processor.html

I think that should fix the problem here. I think the issue can be closed?

**Comment by javanna** [comment]
Seems like a workaround was provided. We have no plans to further work on this issue, closing.
