### ISSUE TITLE
[CI] MonitoringBulkRequestTests.testAddRequestContent

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#39980]
This reproduces, may have been caused by https://github.com/elastic/elasticsearch/pull/39888

On master 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/872/console

On 7.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/68/console

[build-periodic-7.x-68.txt.zip](https://github.com/elastic/elasticsearch/files/2958857/build-periodic-7.x-68.txt.zip)

```
  1> [2019-03-12T02:03:16,742][INFO ][o.e.x.m.a.MonitoringBulkRequestTests] [testAddRequestContent] before test                                                                                
  1> [2019-03-12T02:03:16,755][INFO ][o.e.x.m.a.MonitoringBulkRequestTests] [testAddRequestContent] after test                                                                                 
FAILURE 0.03s J7 | MonitoringBulkRequestTests.testAddRequestContent <<< FAILURES!              
   > Throwable #1: java.lang.AssertionError:   
   > Expected: "qxHU"                          
   >      but: was "_doc"                      
   >    at __randomizedtesting.SeedInfo.seed([3E7752DEB7B82078:6BF9E9DF11928659]:0)            
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)                        
   >    at org.elasticsearch.xpack.monitoring.action.MonitoringBulkRequestTests.testAddRequestContent(MonitoringBulkRequestTests.java:136)                                                     
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)      
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                    
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                            
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)                          
   >    at java.base/java.lang.Thread.run(Thread.java:834)    
```

The seed is all that's needed, the compiler version doesn't matter

```
./gradlew :x-pack:plugin:monitoring:unitTest -Dtests.seed=3E7752DEB7B82078 -Dtests.class=org.elasticsearch.xpack.monitoring.action.MonitoringBulkRequestTests -Dtests.method="testAddRequestContent" -Dtests.security.manager=true -Dtests.locale=wo -Dtests.timezone=Chile/EasterIsland -Dcompiler.java=12 -Druntime.java=11
```

It looks like it's still trying to use custom types https://github.com/elastic/elasticsearch/blob/bec0a193675c648e162ce03c55b02305a5f2ba8d/x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/action/MonitoringBulkRequestTests.java#L136

**Comment by cbuescher** [comment]
@jakelandis this still seems to fail on 7.0 and 7.x, is the fix on those branches as well? 
e.g.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/72/console

**Comment by jakelandis** [comment]
@cbuescher - I am working on the back ports.  Just got a passing 7.x and will have 7.0 a bit later today.
