### ISSUE TITLE
[docs] 6.6.0 release note has a typo

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#40020]
https://www.elastic.co/guide/en/kibana/current/release-highlights-6.6.0.html#_support_for_multiple_elasticsearch_nodes says `Simply set elasticsearch.host`, but the correct parameter is `elasticsearch.hosts`

**Comment by jasontedor** [comment]
@TomonoriSoejima These are in the Kibana release notes and this is a Kibana setting. Would you please reopen this issue on the [Kibana](https://github.com/elastic/kibana) repository?

**Comment by TomonoriSoejima** [comment]
No problem and https://github.com/elastic/kibana/issues/33218 is created.
