### ISSUE TITLE
[docs] xpack.monitoring.history.duration doesn't accept month

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#40021]
https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-settings.html has 
```
xpack.monitoring.history.duration
Sets the retention duration beyond which the indices created by a Monitoring exporter are automatically deleted. Defaults to 7d (7 days).

This setting has a minimum value of 1d (1 day) to ensure that something is being monitored, and it cannot be disabled.
```
I tested with `1m` and `1M` to set it to 1 month on Elasticsearch 6.6.0 but they produced the following error:
```
 “org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: failed to parse value [1m] for setting [xpack.monitoring.history.duration], must be >= [24h]”
```
Looks like both `m` and `M` are considered as minutes and I see it accepts `h` and `s`.

I think it would be better if it is added to document that `xpack.monitoring.history.duration` accepts only `d` for days, `h` for hours, `m` and `M` for minutes, `s` for seconds but not months.

**Comment by kiju98** [comment]
Pinging @elastic/es-docs

**Comment by jasontedor** [comment]
The way that we typically denote this in the docs is by linking to the `TimeValue` settings page which explains exactly what units are supported. That is what I think we should do here, and what I think we should do in general, to avoid repeating the same sentence over and over.

**Comment by jasontedor** [comment]
For anyone on the @elastic/es-core-features team that wants to pick this up, see `follow-request-body.asciidoc` for an example of how we denote this elsewhere in the docs.
