### ISSUE TITLE
[DOCS] Monitoring with metricbeat didn't mention master node setup is required.

### ISSUE THREAD

**Issue by reilee** [elastic/elasticsearch#40026]
In [Collecting Elasticsearch monitoring data with Metricbeat](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html)

I was following that manual but in the end I cannot see monitoring data in Kibana.
Finally I found that you must setup metricbeat on current master node first, or Kibana monitoring view cannot show anything.

It would be great if you can mention this in the documentation.

**Comment by jdconrad** [comment]
@elastic/es-core-features Should this be moved to the beats repo?

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by lucabelluccini** [comment]
I've raised an associated issue for the Metricbeat Elasticsearch module with the explanation: https://github.com/elastic/beats/issues/24541

I think we should add a "warning" on both places (ES docs & MB docs):
- https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html
- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
