### ISSUE TITLE
Kibana6 - search bar & query features - strange work

### ISSUE THREAD

**Issue by maxozerov** [elastic/elasticsearch#40045]
**Describe**: 
Search in the search bar does not work  -  until the option is turned on/off 
Options:  **"Turn on query features".**

**Elasticsearch version**:
`Version: 6.6.2, Build: default/deb/3bd3e59/2019-03-06T15:16:26.864148Z, JVM: 1.8.0_201`

**Plugins installed**: 
`ingest-geoip`

**JVM version**:
```java version "1.8.0_201"```

**OS version**:
`Ubuntu 16.04.6 LTS`
`Linux 4.4.0-116-generic #140-Ubuntu x86_64 GNU/Linux`

**Description of the problem**:

Search in the _search bar_ does not work - until the option is turned **on** or **off**
Options: "Turn on query features"

_Change Settings: Management -> Advanced Setting -> search: queryLanguage - did not bring results._  (Lucene or kuery)

For example:
* search `keyId: "Test"`, or just `"Test"` from search bar in Dashboard - is not successfull! 
No Results.
Dashboard (Visualize - Linked to Saved Search with pattern "Exception")
So, View query Request : 
```
{
	"query_string": {
		"query": "\"Exception\"",
		"analyze_wildcard": true,
		"default_field": "*"
	}
}
```
* Next, turn on "Turn on query features"
the search now is successfully all searched and highlighted.
And Request now with filter (all ok)
```
{
	"filter": [{
		"bool": {
			"should": [{
				"match_phrase": {
					"keyId": "Test"
				}
			}]
		}
	}]
}
```
* Next, turn off "Turn on query features"
everything is still ok - everything works:
```keyId: "Test"``` or just ```"Test"``` is successfully searched and highlighted.
Request now is:
```
{
	"query": {
		"bool": {
			"must": [{
					"query_string": {
						"query": "keyId: \"Test\"",
						"analyze_wildcard": true,
						"default_field": "*"
					}
				},
				{
					"query_string": {
						"query": "\"Exception\"",
						"analyze_wildcard": true,
						"default_field": "*"
					}
				}
			]
		}
	}
}
```
So, all works until close browser.
If open the new browser window - it does not work again (after reopen)
Request does not contain ```keyId: "Test"``` 
You have to turn on "Turn on query features" again (or turn on and then off)  and search works - and so on in a circle.

**Comment by jdconrad** [comment]
@maxozerov Thank you for submitting this issue.  This repository is for issues related directly to Elasticsearch.  Would you please re-submit this issue to the Kibana repository (https://github.com/elastic/kibana)?

**Comment by maxozerov** [comment]
@jdconrad yeah, sorry, mix up repo). Ok, I'm re-submit this issue to the Kibana repository.
