### ISSUE TITLE
Elastic Search as a Windows Service with network.host set to _global_

### ISSUE THREAD

**Issue by saxenark** [elastic/elasticsearch#40057]
Hi,

I want to know how to install ElasticSearch as a windows service with the network.host set so that all of my dev machines can access the service over 9200 port.

I figured out that we can do this with the -E network.host=0.0.0.0 using ElasticSearch.bat but can't understand how to do this when used as a windows service.

Thanks,

**Comment by jdconrad** [comment]
@saxennark This would be more appropriate as a discuss issue.  Please use https://discuss.elastic.co/c/elasticsearch to ask your question.  Thanks!
