### ISSUE TITLE
[Docs] Documentation missing for ingest node metrics

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#40063]
IN the documentation there is a general phrase about ingest metrics under node stats. Could we document the ingest metrics returned by `GET _nodes/stats/ingest?filter_path=nodes.*.ingest`

**Comment by jakelandis** [comment]
Specifically here: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#ingest-stats

"On top of these overall ingest statistics, these statistics are also provided on a per pipeline basis." is a bit vague. 

We should be more explicit here that each pipeline has a `count`, `time_in_millis`, `current`, `failed`, and possibly provide helpful filter commands to look for just a single pipeline.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving this open as it's still relevant.
