### ISSUE TITLE
Synonym 

### ISSUE THREAD

**Issue by leguma** [elastic/elasticsearch#40077]
**Elasticsearch version**: 6.6.1
**Severity**: Very low
**Description**:
- Synonym file parse errors when valid.
- Synonyms ignored in lenient mode when they shouldn't be.

This incorrect behavior can occur when using a filter, such as a stop filter, before applying a synonym filter. In many cases, ignoring these rule is completely fine because the synonym in question truly is unreachable. However, there are some cases in which a dynamic filter may introduce a value that would normally match the synonym rule, therefore the rule should *not* be ignored.

**Reproduction**:
```
PUT /example
{
	"settings": {
		"analysis": {
			"filter": {
				"english_stop": {
					"type": "stop",
					"stopwords": "_english_"
				},
				"english_stemmer": {
					"type": "stemmer",
					"language": "english"
				},
				"stemmed_synonyms": {
					"type": "synonym",
					"synonyms": "and=>and,mountain"
				}
			},
			"analyzer": {
				"stemmed_english_synonym_analyzer": {
					"type": "custom",
					"tokenizer": "standard",
					"filter": [
						"lowercase",
						"english_stop",
						"english_stemmer",
						"stemmed_synonyms"
					]
				}
			}
		}
	}
}
```

Response:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "failed to build synonyms"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to build synonyms",
        "caused_by": {
            "type": "parse_exception",
            "reason": "Invalid synonym rule at line 1",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "term: and was completely eliminated by analyzer"
            }
        }
    },
    "status": 400
}
```

Or if in lenient mode:
> [INFO ][o.e.i.a.ESSolrSynonymParser] [6llgS4Y] Synonym rule for [and] was ignored

In this case, the synonym map contains a word "and" that is perceived to be removed by the English stop filter. However, there are valid inputs to the English stemmer that return "and", such as "ande", which the stemmed synonym map could then enhance relevancy/retrieval. 

Granted, there are not many words in English whose stemmed value collides with the stop filter, but I have no idea about other languages.

**Comment by Sanket-Valani** [comment]
Similar error
**Elasticsearch version:** 7.7.0

`
PUT /test_index
{
  "settings": {
    "index" : {
      "analysis" : {
        "filter" : {
          "synonym_filter" : {
            "type" : "synonym",
            "synonyms_path" : "analysis/synonyms.txt"  
          }
        },
        "analyzer" : {
          "synonym_analyzer" : {
            "tokenizer" : "custom_ngram",
            "filter" : ["lowercase", "synonym_filter"] 
          }
        },
        "tokenizer":{
          "custom_ngram":{
            "type": "ngram",
            "min_gram": 5,
            "max_gram": 30
          }
        }
      }
    },
    "max_ngram_diff": 50
  },
  "mappings": {
    "properties": {
      "text": { 
        "type": "text",
        "analyzer": "synonym_analyzer"
      }
    }
  }
}
`
synonyms.txt:
`
address, city, country, region, postal_code
identifier => id
`

output:
`
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "failed to build synonyms"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to build synonyms",
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "Invalid synonym rule at line 1",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "term: city was completely eliminated by analyzer"
      }
    }
  },
  "status" : 400
}

`

**Comment by Sanket-Valani** [comment]
Similar error
**Elasticsearch version:** 7.7.0

```
PUT /test_index
{
  "settings": {
    "index" : {
      "analysis" : {
        "filter" : {
          "synonym_filter" : {
            "type" : "synonym",
            "synonyms_path" : "analysis/synonyms.txt"  
          }
        },
        "analyzer" : {
          "synonym_analyzer" : {
            "tokenizer" : "custom_ngram",
            "filter" : ["lowercase", "synonym_filter"] 
          }
        },
        "tokenizer":{
          "custom_ngram":{
            "type": "ngram",
            "min_gram": 5,
            "max_gram": 30
          }
        }
      }
    },
    "max_ngram_diff": 50
  },
  "mappings": {
    "properties": {
      "text": { 
        "type": "text",
        "analyzer": "synonym_analyzer"
      }
    }
  }
}
```
synonyms.txt:
```
address, city, country, region, postal_code
identifier => id
```

output:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "failed to build synonyms"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to build synonyms",
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "Invalid synonym rule at line 1",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "term: city was completely eliminated by analyzer"
      }
    }
  },
  "status" : 400
}
```

**Comment by Sanket-Valani** [comment]
This happens because **and** is getting removed by tokenizer or by some filter which is before synonyms filter.

So for the above thing to work adjust the filter order so that **and** does not get removed before it reaches to synonyms filter.

**Comment by cbuescher** [comment]
Hi @leguma, sorry for the long radio silence, this got lost somewhere on the way, just circling back on some synonym-related issues. 
You are right that in this particular case you describe, a filter (in this case the "english_stemmer" can potentially re-introduce token surface forms that otherwise would be removed, and we cannot detect that and assume a certain synonym rule cannot match. 
We introduced erroring on unreachable synonym rules because otherwise users where not aware that their analysis filter chain would prevent those rules from ever matching. Your example shows an edge case where it might be useful to still keep this rule in "lenient" mode, however I'm reluctant to call this a very common case. 
I'd like to close this case for now and keep this caveat in mind. Most of the times it should be possible to work around issues like this by re-orderning the filter as suggested. If you disagree please feel free to reopen again.
