### ISSUE TITLE
Assertion in ReplicationTracker.java breaks build

### ISSUE THREAD

**Issue by a139786** [elastic/elasticsearch#40093]
git clone
cd elasticsearch
./gradlew assemble
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.2.1
  OS Info               : Linux 4.4.175-94.79-default (amd64)
  JDK Version           : 11 (Oracle Corporation 11.0.2 [OpenJDK 64-Bit Server VM 11.0.2+9])
  JAVA_HOME             : /usr/java/jdk-11.0.2
  Random Testing Seed   : C3F65B31829A0195
=======================================
 :server:compileJava
fails with:
/opt/src/java/elasticsearch/server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java:334: error: package Version does not exist
        assert Version.CURRENT.major <= 8 : "throw an exception instead of returning EMPTY on null";
 
required git diff to fix:
git diff
diff --git a/server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java b/server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
index 702b829193b..a1d1912c308 100644
--- a/server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
+++ b/server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
@@ -19,6 +19,7 @@

 package org.elasticsearch.index.seqno;

+import org.elasticsearch.Version;
 import com.carrotsearch.hppc.ObjectLongHashMap;
 import com.carrotsearch.hppc.ObjectLongMap;
 import org.elasticsearch.action.ActionListener;

**Comment by ywelsch** [comment]
This has since been fixed (see fd70883e264), please pull the latest changes.
