### ISSUE TITLE
Provide an additional docs count metric on top level Elasticsearch documents in _cat/indices?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#40122]
This keeps coming up from time to time.  The count differences reported by various different APIs in Elasticsearch have often been a source of confusion.  Just a few examples:

https://github.com/elastic/elasticsearch/issues/25868
https://github.com/elastic/elasticsearch/issues/17319
https://github.com/elastic/elasticsearch/issues/27502
https://discuss.elastic.co/t/cat-indices-docs-count-is-way-above-actual-document-count/81934/3
https://discuss.elastic.co/t/-cat-indices-docs-count-does-not-match-indice--count-why/49966

In short, different APIs return different counts (by design) depending on whether they are returning counts at the Lucene level vs. Elasticsearch level.  For example:

Lucene level counts (includes nested documents)
- GET /_cat/indices
- GET /<index_name>/_stats

Elasticsearch level counts (only top level documents)
- GET /<index_name>/_count
- GET /_cat/count
- Reindex Tasks API output (and .tasks)

While this is expected and not a bug, I am curious if there's anything we can do in the product to clarify this further.

In some larger organizations, the admins of Elasticsearch may not be the ones developing the application.  The admins may not know if a specific index contains nested documents (or what that even means).  They might just be tasked to run the reindex API to index data between clusters (and to confirm that the counts are the same afterwards).  In this case, there is a tendency to look at the counts in the output of the reindex API, and then compare with the count in the original index using _cat/indices.  If there are nested fields in the mappings, then these counts will always be different.  Also, if an admin is calculating the reindexing rate using the total doc count and duration reported by the reindex API, this rate can appear to be very slow because it doesn't account for the indexing of all the additional nested documents in Lucene.  Have we considered reporting the Lucene level doc count as well in the reindex API output?

While we have now documented the [doc count caveats](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html
) of using the highly popular _cat/indices API output, it seems like it can be helpful to also clarify the same for the other API calls that return doc count information (few examples below).

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

Have we considered adding another option (?h=) to _cat/indices to allow admins to show the Elasticsearch top level counts alongside the Lucene level docs.count?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
