### ISSUE TITLE
Docs for FIPS 140-2 has an edit_url artifact

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#40131]
I haven't tried to dig in and tell where this is coming from or what it's intended to link to, but at the bottom of https://www.elastic.co/guide/en/elasticsearch/reference/current/fips-140-compliance.html#_limitations , the docs read
> The SAML Realm cannot decrypt and consume encrypted Assertions or encrypted attributes in Attribute Statements from the SAML IdP. :edit_url: https://github.com/elastic/elasticsearch/edit/6.6/docs/reference/settings/security-settings.asciidoc

**Comment by jkakavas** [comment]
Hey @lcawl , this doesn't look like it's part of the asciidoc file, do you have any ideas why the `:edit_url:` is rendered as text ? IIUC, this is the "edit" icon that is rendered on the right hand side of each section and points to the asciidoc source in the repo, but this is the last part in this file so there is no section that follows here.. 

Could it be that this is missing/excessive white space ?

**Comment by lcawl** [comment]
The same problem exists in these pages:
https://www.elastic.co/guide/en/elasticsearch/reference/master/ciphers.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/separating-node-client-traffic.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/security-settings.html
...
Might be related to some clean up of the edit links (e.g. https://github.com/elastic/docs/pull/642), I'll investigate further.

**Comment by nik9000** [comment]
It [looks](https://github.com/elastic/built-docs/blob/bb5bf93e21275876affa8e42461c988a1418ac3c/html/en/elasticsearch/reference/master/ciphers.html#L723) to me like `edit_url` has been in `ciphers.html` for as long as I have the history for it.

**Comment by lcawl** [comment]
The problematic pages that I've found so far seem to be fixed by adding blank lines as in https://github.com/elastic/elasticsearch/pull/40161
