### ISSUE TITLE
The parent_id query should support multiple parent IDs

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch#40136]
Currently the `parent_id` query does not allow to specifiy multiple parent document IDs (that's why it's **not** called `parent_ids`). Such a query can, of course, be rephrased as a `has_parent` wrapped around an `ids` query. 
But given that there's a substantial performance penalty, why not accept arrays of IDs as values for `parent_id.id` :question:

**Comment by Celend** [comment]
Any progress?

**Comment by javiergom** [comment]
Any update ?

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
