### ISSUE TITLE
Cluster MultiSearch query slow

### ISSUE THREAD

**Issue by zhaoqiqang199** [elastic/elasticsearch#40191]
I've had a problem that's a problem lately.
When using MultiSearch queries, queries are fast if there is only one condition, slower if multiple conditions are used, and sometimes as slow as 5 seconds
The cluster is configured with 13 nodes and 64 Shard, with 36 indexes and 200 million documents in the cluster, of which the number of index documents to be retrieved is about 12 million.
The idea of whether to provide some queries?
think you~

**Comment by cbuescher** [comment]
Hi @zhaoqiqang199 ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
