### ISSUE TITLE
searchAfter cannot work with terminateAfter properly

### ISSUE THREAD

**Issue by ujfjhz** [elastic/elasticsearch#40201]
elastic version : 6.4.2

Let's say page size is 10, shard count is 1, the matched total hits is 100.
If we set terminateAfter to 10, we can optain the first page. Then we use searchAfter to get the second page, will get nothing. It seems the docs before searchAfter offset also increased the collect count, so it terminate more earlier than it should be.

**Comment by jimczi** [comment]
Hi @ujfjhz, we reserve github for verified bugs and feature requests so I hope you don't mind if I close this issue. I also see that somebody (is that you ? ;) ) asked the exact same question in the discuss [forum](https://discuss.elastic.co/t/searchafter-cannot-work-with-terminateafter-properly/172946) so I answered there.
