### ISSUE TITLE
 Problem when creating an index not analyzed, to perform term searches in texts

### ISSUE THREAD

**Issue by elvisases** [elastic/elasticsearch#40226]
Verifying documentation yesterday I see that for my problem of looking for a string of characters by term I need to create in the index the field as not analyzed, but when doing it as it indicates this documentation generates error. This is the documentation https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html 
This is the query they say they use.

PUT / my_store
{
    "mappings": {
        "products": {
            "properties": {
                "productID": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        }
    }

}

And this is the error that this generates.

{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "No handler for type [string] declared on field [productID]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [products]: No handler for type [string] declared on field [productID]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "No handler for type [string] declared on field [productID]"
    }
  },
  "status": 400
}

Verify and say that there is no string already in elasctic, that it is text itself, but it generates another error saying that for the index only true or false is accepted.

**Comment by dadoonet** [comment]
The documentation you linked to says:

> This information applies to version 2.x of Elasticsearch. For the most up to date information, see the current version of the Elasticsearch Reference.

string does not exist anymore in 6.x.

But please ask your question on discuss.elastic.co where we can definitely help you.
This space is for confirmed bugs that has been discuss on discuss.elastic.co.

I'm closing the "issue".
