### ISSUE TITLE
Data sync issue when action add/delete

### ISSUE THREAD

**Issue by thundercrawl** [elastic/elasticsearch#40236]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4
**Plugins installed**: []
safeguard
**JVM version** (`java -version`):
sun jdk 1.8
**OS version** (`uname -a` if on a Unix-like system):
centos 7.3
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

--------Issues description--------
We have realtime document databases sync to elasticsearch to do search etc work, 
After finish the production codes, we established a test framework to test it.
We found in following situation the test failed.
A document add to server then after a short delay  < 1s, then we found the document failed 
to delete
Is there way to solve this issue ？ we just add a retry mechanism, that not reasonable way to
solve it,  that depend on the system behavior.
IF the system is so busy, the situation will be more bad.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
