### ISSUE TITLE
ILM Rollover Alias Issues

### ISSUE THREAD

**Issue by triggerman86** [elastic/elasticsearch#40235]
Elasticsearch 6.6

When playing around with ILM, it appears ILM throws an error with the rollover policy I have defined (just as a test), when the alias is assigned via the _aliases API. The error in the response is noted below.

If I instead, apply the alias at index creation, everything works as expected. Not sure if this behavior is a misunderstanding on my part, or a potential bug.

Thanks.

Steps to recreate:

```json
PUT _ilm/policy/apache_policy
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_docs": 100
          }
        }
      }
    }
  }
}

PUT _cluster/settings
{
    "transient" : {
        "indices.lifecycle.poll_interval" : "5s"
    }
}

PUT _template/apache_logs
{
  "index_patterns": ["apache_logs-*"],                 
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.lifecycle.name": "apache_policy",    
    "index.lifecycle.rollover_alias": "apache"    
  }
}

PUT apache_logs-000001

POST /_aliases
{
  "actions": [
    {
      "add": {
        "index": "apache_logs-000001",
        "alias": "apache",
        "is_write_index": true
      }
    }
  ]
}

GET apache_logs-000001/_ilm/explain
```

The response I get back is as follows:

```json
{
  "indices" : {
    "apache_logs-000001" : {
      "index" : "apache_logs-000001",
      "managed" : true,
      "policy" : "apache_policy",
      "lifecycle_date_millis" : 1553045919932,
      "phase" : "hot",
      "phase_time_millis" : 1553045919998,
      "action" : "rollover",
      "action_time_millis" : 1553045919998,
      "step" : "ERROR",
      "step_time_millis" : 1553045921674,
      "failed_step" : "check-rollover-ready",
      "step_info" : {
        "type" : "illegal_argument_exception",
        "reason" : "index.lifecycle.rollover_alias [apache] does not point to index [apache_logs-000001]",
        "stack_trace" : """
java.lang.IllegalArgumentException: index.lifecycle.rollover_alias [apache] does not point to index [apache_logs-000001]
	at org.elasticsearch.xpack.core.indexlifecycle.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:92)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:128)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:244)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggered(IndexLifecycleService.java:199)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:164)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:192)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

"""
      },
      "phase_execution" : {
        "policy" : "apache_policy",
        "phase_definition" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_docs" : 100
            }
          }
        },
        "version" : 17,
        "modified_date_in_millis" : 1553043546316
      }
    }
  }
}
```

Deleting the index and starting over by bootstraping the index with the method below works:

```json
PUT apache_logs-000001
{
  "aliases": {
    "apache": {
      "is_write_index": true
    }
  }
}
```

**Comment by dakrone** [comment]
@triggerman86 what happened is that when you initially created the index, it immediately attempted to execute the policy, but couldn't because the alias doesn't exist (since it was created shortly after the index).

You can use the [ILM retry](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/ilm-retry-policy.html) API to retry the operation which *should* retry the step, and ILM will see that the alias now exists, moving it out of the ERROR step).

**Comment by triggerman86** [comment]
@dakrone Ahh I see what I have overlooked. Behaving as expected then. Thanks.

**Comment by lbouquinUniv** [comment]
I have the same problems. I try to use IML retry and it's doesn't work 

**Create ilm policy**
`PUT /_ilm/policy/test_rollover_policy
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_size": "2mB"
            , "max_docs": 1000
            , "max_age": "1d"
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}`

**create template**
`PUT _template/test_template_rollover
{
  "index_patterns": ["*-ker-roolover-*"], 
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.lifecycle.name": "test_rollover_policy", 
    "index.lifecycle.rollover_alias": "test-alias-rollover" 
  }
}`

**Create index with aliases**
`PUT /rollover-000001
{
  "aliases": {
    "test-alias-rollover":{
      "is_write_index": true
    }
  }
}
`
**get  GET filebeat-7.4.2-ker-roolover-000001/_ilm/explain**

`{
  "indices" : {
    "filebeat-7.4.2-ker-roolover-000001" : {
      "index" : "filebeat-7.4.2-ker-roolover-000001",
      "managed" : true,
      "policy" : "test_rollover_policy",
      "lifecycle_date_millis" : 1582560410665,
      "phase" : "hot",
      "phase_time_millis" : 1582560414227,
      "action" : "rollover",
      "action_time_millis" : 1582560416266,
      "step" : "ERROR",
      "step_time_millis" : 1582560420029,
      "failed_step" : "check-rollover-ready",
      "step_info" : {
        "type" : "illegal_argument_exception",
        "reason" : "index.lifecycle.rollover_alias [test-alias-rollover] does not point to index [filebeat-7.4.2-ker-roolover-000001]",
        "stack_trace" : """
java.lang.IllegalArgumentException: index.lifecycle.rollover_alias [test-alias-rollover] does not point to index [filebeat-7.4.2-ker-roolover-000001]
	at org.elasticsearch.xpack.core.indexlifecycle.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:92)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:133)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:270)
	at org.elasticsearch.xpack.indexlifecycle.IndexLifecycleService.triggered(IndexLifecycleService.java:213)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:168)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:196)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

"""
      },
      "phase_execution" : {
        "policy" : "test_rollover_policy",
        "phase_definition" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "2mb",
              "max_age" : "1d",
              "max_docs" : 1000
            }
          }
        },
        "version" : 8,
        "modified_date_in_millis" : 1582560390297
      }
    }
  }
}`

**Comment by andreidan** [comment]
@lbouquinUniv Thanks for trying out ILM. I think you'll have to assign the `test-alias-rollover` alias to `filebeat-7.4.2-ker-roolover-000001`. The statement you used above does not achieve this (the index name is `rollover-000001`)
```
Create index with aliases
PUT /rollover-000001 { "aliases": { "test-alias-rollover":{ "is_write_index": true } } } 
```
We appreciate these steps are a bit cumbersome though and are actively looking at options to make this setup more user friendly in the future.

**Comment by lbouquinUniv** [comment]
ok i change it but I have another issue manage false
```
PUT /_ilm/policy/test_rollover_policy
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_size": "2mB"
            , "max_docs": 1000
            , "max_age": "1d"
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

PUT _template/test_template_rollover
{
  "index_patterns": ["roolover-*"], 
  "settings": {
    "number_of_shards": 2,
    "number_of_replicas": 2,
    "index.lifecycle.name": "test_rollover_policy", 
    "index.lifecycle.rollover_alias": "test-alias-rollover"
  }
}

```
```
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : "rollover-000001", "alias" : "test-alias-rollover"} }
    ]
}

GET rollover-000001/_ilm/explain
```

result 

> {
>   "indices" : {
>     "rollover-000001" : {
>       "index" : "rollover-000001",
>       "managed" : false
>     }
>   }
> }
> 

In kibana rollover-* exist and logstash fill it

**Comment by dakrone** [comment]
@lbouquinUniv you have a typo in your template:

```
"index_patterns": ["roolover-*"],
                here --^
```

In the future however, these sorts of questions should be directed to our user forums at https://discuss.elastic.co.

**Comment by lbouquinUniv** [comment]
correct it butrollover doesn't     work. no error message.

**Comment by iamhritik** [comment]
@dakrone Do we still need to assign the `test-alias` alias to index `test-index-0001` for setting up ILM in elasticsearch ?
Elasticsearch version: 8.6.0
