### ISSUE TITLE
date_histogram.extended_bounds is meaningless???

### ISSUE THREAD

**Issue by ChesterZheng** [elastic/elasticsearch#40246]
"aggs": {
    "date_histogram":{
      "date_histogram": {
        "field": "sold_date",
        "interval": "month",
        "format": "yyyy-MM-dd",
        "min_doc_count": 0,
        "extended_bounds":{
          "min": "2017-01-01",
          "max": "2017-12-31"
        }
      }
    }
  }

The result is 

{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 8,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "date_histogram": {
      "buckets": [
        {
          "key_as_string": "2016-05-01",
          "key": 1462060800000,
          "doc_count": 1
        },
        {
          "key_as_string": "2016-06-01",
          "key": 1464739200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-07-01",
          "key": 1467331200000,
          "doc_count": 1
        },
        {
          "key_as_string": "2016-08-01",
          "key": 1470009600000,
          "doc_count": 1
        },
        {
          "key_as_string": "2016-09-01",
          "key": 1472688000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-10-01",
          "key": 1475280000000,
          "doc_count": 1
        },
        {
          "key_as_string": "2016-11-01",
          "key": 1477958400000,
          "doc_count": 2
        },
        {
          "key_as_string": "2016-12-01",
          "key": 1480550400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-01-01",
          "key": 1483228800000,
          "doc_count": 1
        },
        {
          "key_as_string": "2017-02-01",
          "key": 1485907200000,
          "doc_count": 1
        },
        {
          "key_as_string": "2017-03-01",
          "key": 1488326400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-04-01",
          "key": 1491004800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-05-01",
          "key": 1493596800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-06-01",
          "key": 1496275200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-07-01",
          "key": 1498867200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-08-01",
          "key": 1501545600000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-09-01",
          "key": 1504224000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-10-01",
          "key": 1506816000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-11-01",
          "key": 1509494400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-12-01",
          "key": 1512086400000,
          "doc_count": 0
        }
      ]
    }
  }
}

I set the extended_bounds.min="2017-01-01" and extended_bounds.max="2017-12-31", but the result is out of my setting range.  The minimum result is less than I limit.
I know the extended_bounds is to limit a range, but the result is seems to return from minimum to maximum of my index. Why?
If you know, please help me to solve this problem.
Thanks a lot.

**Comment by matriv** [comment]
This setting will allow you to build empty buckets for ranges outside of the the results of the query, see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#search-aggregations-bucket-histogram-aggregation-extended-bounds), but it doesn't work as a date range filter for your query.

You'll need to apply a proper filter with this [date range](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#ranges-on-dates) using a "search" part in your query together with the "aggs" part.

**Comment by polyfractal** [comment]
@matriv is correct, the `extended_bounds` option just "extends" the range to the specified bounds.  For example, this is useful if you want to display a full month's calendar, but there is only a single entry.  Extended bounds will make sure the entire month is returned in the response (with empty buckets) to simplify client-side rendering.  Otherwise the client would have to fill in all the empty bucket itself.

If you want to limit the range, you'll have to use a range query as mentioned.

In the future, please ask these sorts of questions on the [Elasticsearch forums](https://discuss.elastic.co/c/elasticsearch).  We try to reserve Github for bugs and enhancement requests.  Thanks!

**Comment by ChesterZheng** [comment]
Thanks @matriv ,  I probably got it. I've appended a query filter to this sample, the result is what i want.

**Comment by ChesterZheng** [comment]
Thanks @polyfractal, I'll try to ask this kind of questions on th es forums next time.
