### ISSUE TITLE
SQL: tests improvement

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#40245]
Am thinking here about a templating approach where, given a certain (simple) query, functions (from the FunctionRegistry) could be placed in these templates and tested.

For example:
`SELECT [function] FROM test GROUP BY [function]`
`SELECT [function] FROM test GROUP BY [function] ORDER BY [function]`
`SELECT [function] AS some_alias_name FROM test GROUP BY some_alias_name`
etc

Basically, pick up all the functions from the function registry, and generate functions with the relevant parameters (some functions have optional parameters) and place them inside the templates and run each of them.

Maybe, to ease the parameters generation, we could define in a static file _possible values_ for parameters **for each function** the testing mechanism above will pick up random values from these already defined ones and use in the templates. These static files could also include other functions, to cover the nested functions scenario.

For starters, we should do this in such a way that the generated queries:
- don't throw exceptions
- have at least one result (to account for a possibly incorrect set of parameters)

**Comment by wchaparro** [comment]
Superceded by ES|QL
