### ISSUE TITLE
Support dynamically setting index.codec on open indices

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#40243]
Feature request:
According to [this blog post](https://www.elastic.co/blog/store-compression-in-lucene-and-elasticsearch) it's possible to set `index.codec` on the node level, so you can move shards onto a node with a different setting **and** when you call `_optimize`, it will be rewritten with the new codec.

The post doesn't mention any other restrictions (like you can't write to the shard which is written with a different codec than the node setting), so I guess Lucene handles just fine if you have a mixed setting (ie you have segments written with different codecs).
If that's true, I guess setting `index.codec` should be a dynamic setting, so this should work:

```
curl -H "Content-Type: application/json" -XPUT 'http://localhost:9200/events_20190318/_settings' -d '{"index.codec": "best_compression"}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Can't update non dynamic settings [[index.codec]] for open indices [[events_20190318/pWT4l08MS52Mw4JyW7rbnQ]]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Can't update non dynamic settings [[index.codec]] for open indices [[events_20190318/pWT4l08MS52Mw4JyW7rbnQ]]"
  },
  "status" : 400
}
```

If this setting would be dynamic, it would make it possible to rewrite "cold" indices with a better compression, but without the need to dedicate complete nodes with a different `index.codec` setting.

**Comment by ywelsch** [comment]
There is another (non-obvious) technical limitation here. Lucene requires the codec to be set when the `IndexWriter` object, which is responsible for indexing into Lucene, is created (see https://lucene.apache.org/core/8_0_0/core/org/apache/lucene/index/IndexWriterConfig.html#setCodec-org.apache.lucene.codecs.Codec-). This means that dynamically changing this setting in Elasticsearch on an allocated shard would require reinitializing its writer capabilities (as well as reader capabilities, which depend on them), pause the existing indexing / search flow, etc. This would require extra coordination and add substantial complexity to the code.

**Comment by bra-fsn** [comment]
When is this created? I mean is it created on:
- index open (starting up, close/open)
- forcemerge/optimize
?
Could it be moved down in Lucene to make it possible to modify on the fly with an already created IndexWriter?
This could be like zfs, where modifying options takes effect only for newly written data. In this case the new codec would be used only when opening a new segment.

**Comment by ywelsch** [comment]
This is IMO a valid feature request for Lucene. Pinging @jpountz here for input.

**Comment by jpountz** [comment]
> I guess Lucene handles just fine if you have a mixed setting (ie you have segments written with different codecs).

This is correct. Every segment records the codec that has been used to write it in its `SegmentInfo`, and this is later used at read-time to know how to read segment files.

> Could it be moved down in Lucene to make it possible to modify on the fly with an already created IndexWriter?

I'm a bit reluctant to expose such a feature as it could expose us to bugs where half the segment is written with a codec and the other half with another codec.

I'd suggest to close it as a "won't fix" if that works for you @ywelsch. While the ability to change the codec on an existing index would be nice, the cost/risk outweighs benefits in my opinion.
