### ISSUE TITLE
Javadoc Rest Client Bad Link for unreleased branches

### ISSUE THREAD

**Issue by bigdamhero** [elastic/elasticsearch#40259]
I found a bad link, I am unsure where this should be reported. 

Page: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-javadoc.html

Bad link points to: https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/8.0.0-alpha1/index.html.

**Comment by dadoonet** [comment]
Yeah. Those links are only working for released versions.
For example, this one is accurate: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.0/java-rest-high-javadoc.html

**Comment by javanna** [comment]
Links should work for released as well as unreleased versions, at least they used to, not sure what happened that breaks them, see https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/Versions.asciidoc

**Comment by javanna** [comment]
Seems like master is in prerelease state, I think it should be set back to unreleased, thoughts @debadair @lcawl ?

**Comment by debadair** [comment]
Yes, it should be unreleased. Opened https://github.com/elastic/elasticsearch/pull/40470 to fix.
