### ISSUE TITLE
Ingest Node: misleading deprecation notice

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#40265]
Given the following pipelines:
```
PUT /_ingest/pipeline/foo
{
  "processors": [
    {
      "script": {
        "inline": "ctx.foo = 'bar'"
      }
    }
  ]
}
```
^^ correctly results in a deprecation notice `#! Deprecation: Deprecated field [inline] used, expected [source] instead`

However, if adding/deleting/modifying a new pipeline (any pipeline) : 
```
PUT /_ingest/pipeline/test
{
  "processors": []
}
```
^^ will also result in `#! Deprecation: Deprecated field [inline] used, expected [source] instead`

This is misleading since the `test` pipeline doesn't even include a script processor. This is essentially an implementation leak that on additions/deletions/modifications to a single pipeline, that all pipelines get reconstructed. 

Ideally only the deprecation's for the pipeline that is currently being added/deleted/modified would be returned.

**Comment by martijnvg** [comment]
The last request doesn't result in a deprecation warning anymore in master. Only the first request does. I think we can close this issue.
