### ISSUE TITLE
Better document when BKD vs PrefixTree geoshapes are used

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#40266]
BKD-backed geoshapes are enabled by default in 6.6+, but the legacy PrefixTrees can be used if any of the deprecated settings are configured (`precision`, `tree`, etc).

There are a few hints about this in the documentation, but it isn't immediately obvious and could be confusing for users.  Especially if they are migrating an existing index over to 6.6+ hoping to use the new BKD trees... but reindex with the same settings (like a configured `precision`) and accidentally opt back into the legacy trees.

I think we should add a section or callout near the top of geoshape docs that clearly defines when BKD and PrefixTrees are used.

Probably add a note somewhere in the breaking changes that mentions or links to the above section too.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by jrodewig** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/76582
