### ISSUE TITLE
Update commons-logging to 1.2

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#40305]
Would be nice if we can upgrade `commons-logging` library.

```
compile group: 'commons-logging', name: 'commons-logging', version: '1.2'
```

Asking that because I have a project which depends on `rest-client:7.0.0-beta1` which is using `commons-logging:1.1.3`.
Of course I can definitely solve the problem on my end but that'd be nice if we can depend on the latest versions (1.2 was released in Jul 05, 2014).

```
Dependency convergence error for commons-logging:commons-logging:1.1.3 paths to dependency are:
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.0.0-beta1
    +-org.elasticsearch.client:elasticsearch-rest-client:7.0.0-beta1
      +-commons-logging:commons-logging:1.1.3
and
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-fr.pilato.elasticsearch.crawler:fscrawler-framework:2.7-SNAPSHOT
    +-org.apache.logging.log4j:log4j-jcl:2.11.2
      +-commons-logging:commons-logging:1.2
```

**Comment by jaymode** [comment]
It would be worthwhile to see if we can get lucene to upgrade versions as well since I believe that the origin of the older version comes from lucene, https://github.com/apache/lucene-solr/blob/2ae4746365c1ee72a0047ced7610b2096e438979/lucene/ivy-versions.properties#L59

**Comment by dadoonet** [comment]
I agree that'd be good. That said here the dependency is on the `rest-client` which does not depend on Lucene AFAIK.

**Comment by yrodiere** [comment]
As far as I can see, the upgrade is now possible without any fear of depending on multiple versions of commons-logging, because Lucene 9.1 relies on commons-logging 1.2: https://github.com/apache/lucene/blob/releases/lucene/9.1.0/versions.lock#L6
