### ISSUE TITLE
SQL: Improve analysis/comparison of functions with optional arguments

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#40313]
The Analyzer fails to take into account functions with optional arguments when doing basic comparisons: `ROUND(x) != ROUND(x, 0)`.
This makes sense since outside a function definition, it is impossible to determine what the rules however potentially this can be formalized by extending functions to indicate whether they have optional arguments and what these are.

The issue poses a problem when trying to resolve functions based on already existing functions which have been resolved.

Related to #40242

**Comment by wchaparro** [comment]
Superceded by ES|QL
