### ISSUE TITLE
Add tags to all "stats" related APIs

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#4031]
All APIs that end up contributing to stats, would be great to have a a common way to associate them with a group of tags. This is similar to the feature of "groups" we have in the search API, it just needs to be consistent across all the APIs. Then, one can get the stats for a specific tag (and it might be used in other places).

APIs that make sense to have it for: `index`, `delete`, `get`, `search`, `percolate`, `refresh` (and `suggest` if we add it).

Note, with refresh API, where it also executes in a scheduled manner, maybe it can execute "under" a tag called `_scheduled`.

**Comment by clintongormley** [comment]
Nobody seems to have shown an interest in this issue. I wonder if we really need this? @kimchy ?

**Comment by clintongormley** [comment]
Closing for now.  Can reopen if there is any interest
