### ISSUE TITLE
Why doesn’t _cat/recovery honor the bytes=XX in the URI?

### ISSUE THREAD

**Issue by slmingol** [elastic/elasticsearch#40335]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

```
$ rpm -qi elasticsearch | grep Vers
Version     : 6.5.4
```

**Plugins installed**: []

**JVM version** (`java -version`):

```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I'm trying to change the units for the following API call:

```
GET /_cat/recovery?bytes=gb
```

The docs around the cat API imply that you can do this, but the recovery endpoint doesn't seem to work with this. The units are always shown in bytes.

Example:

```
GET '_cat/recovery?bytes=gb&v&h=index,shard,time,type,stage,source_node,target_node,files,files_recovered,files_percent,bytes_total,bytes_percent' | grep -v done | head
index                             shard time  type           stage source_node     target_node     files files_recovered files_percent bytes_total  bytes_percent
filebeat-6.5.1-2019.03.06         0     2.7h  peer           index rdu-es-data-01e rdu-es-data-01b 268   262             97.8%         218212992946 85.2%
filebeat-6.5.1-2019.03.06         1     2.7h  peer           index rdu-es-data-01a rdu-es-data-01e 277   276             99.6%         228721023484 98.6%
filebeat-6.5.1-2019.03.05         1     2.1h  peer           index rdu-es-data-01d rdu-es-data-01b 271   262             96.7%         203869559392 77.1%
```

REF: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html 1

I asked this Q over on the forums and it was mentioned that this appears to be a bug, specifically here in the code - https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/main/java/org/elasticsearch/rest/action/cat/RestRecoveryAction.java#L167-L170.

Link to the forum Q: https://discuss.elastic.co/t/why-doesnt-cat-recovery-honor-the-bytes-xx-in-the-uri/173241/2

> These values are returned as numbers, not as ByteSizeValues, so the ?bytes= parameter doesn't apply. Could you open an issue on Github, @slmingol?

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Thanks for the report and sorry for the issue.

Relates #17064

**Comment by slmingol** [comment]
Also shows up in 7.0.0-alpha1/futurversion.

**Comment by jasontedor** [comment]
I opened #40379.

**Comment by slmingol** [comment]
I found this bug through your pioneers program, is there something you're suppose to do as the bug finder to trigger anything on that front?
