### ISSUE TITLE
testPersistJobOnGracefulShutdown_givenTimeAdvancedAfterNoNewData fails in CI

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#40347]
See for instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2681/console:

```
PersistJobIT.testPersistJobOnGracefulShutdown_givenTimeAdvancedAfterNoNewData <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <3L>
   >      but: was <2L>
   > 	at __randomizedtesting.SeedInfo.seed([C160B2CEC8C02C80:FBCEB963A0930D87]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.ml.integration.PersistJobIT.testPersistJobOnGracefulShutdown_givenTimeAdvancedAfterNoNewData(PersistJobIT.java:114)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The following line does not reproduce:

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner -Dtests.seed=C160B2CEC8C02C80 -Dtests.class=org.elasticsearch.xpack.ml.integration.PersistJobIT -Dtests.method="testPersistJobOnGracefulShutdown_givenTimeAdvancedAfterNoNewData" -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Manaus -Dcompiler.java=11 -Druntime.java=8
```

Similar-looking failure at:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2682/console

Opening this issue to mute the test.

**Comment by DaveCTurner** [comment]
Test muted in aab8d7bc0d96e040883abd7f10af66b1e4a1be35

**Comment by davidkyle** [comment]
This also failed on the 7.x branch. Muted in 1265a15b75fe8ce44fb426acd802b65fb2201506

```
java.lang.AssertionError: 
Expected: <3L>
     but: was <2L>
	at __randomizedtesting.SeedInfo.seed([27F44E82D1206A6E:1D5A452FB9734B69]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.PersistJobIT.testPersistJobOnGracefulShutdown_givenTimeAdvancedAfterNoNewData(PersistJobIT.java:114)
```


https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/88/console

**Comment by gwbrown** [comment]
This also failed on 7.0: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-unix-compatibility/os=oraclelinux-6/87/console

Muted on 7.0 with f38f7dce1e94d2f0f6e6f5e4db6dcf760fd0368c as well

**Comment by gwbrown** [comment]
And 6.7: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=fedora-28/85/console

Muted on 6.7 with 20e344a58df4a39cc09b7f5c7670f5fe04b797da
