### ISSUE TITLE
SQL: Metric aggs on date fields return double

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#40376]
```SELECT YEAR(MAX(date)) FROM test```

throws ClassCastException.

**Comment by costin** [comment]
Related to #39492

**Comment by costin** [comment]
I think this fixed #39429 as well.

**Comment by matriv** [comment]
Backported to `7.x` with 17b8b54d5e11c2edc0beeee7db790c6129a7aa91
to `7.0` with 46aeda98f88f04fd81790a029d0cc61f66c706ed
to `6.7` with eb195672f43a8b4662a9023283e4b9d68b919d21
to `6.6` with 6b8e84e78f81cf45110f6eb03d123e268a7bd3f3
