### ISSUE TITLE
ThreadContext's Transient headers are not transient

### ISSUE THREAD

**Issue by sscarduzio** [elastic/elasticsearch#40391]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.6.2, Build: default/tar/3bd3e59/2019-03-06T15:16:26.864148Z, JVM: 9.0.4

**Plugins installed**: [test-plugin]

**JVM version** (`java -version`):
java version "9.0.4"

**OS version** (`uname -a` if on a Unix-like system):
docker.elastic.co/elasticsearch/elasticsearch:6.6.1

**Description of the problem including expected versus actual behavior**:
I expect that the lifetime of a transient header will span the lifetime of a request (or connection). 
Instead, a transient header set in the previous request, survives into the next request, and because transient headers are immutable (why?), an IllegalArgumentException is thrown.

**Steps to reproduce**:

 1. Unpack Elasticsearch
 2. Create a test plugin which only adds a transient header  whenever a request arrives 
 3. Run elasticsearch 
 4. Send two or more HTTP requests with curl to Elasticsearch
 5. See the exception saying that a transient header with that name already exists

**Provide logs (if relevant)**:
Experimented with a tiny plugin, by only adding an action filter:
```java
 new ActionFilter.Simple(){
      @Override
      public int order() {
        return 0;
      }

      @Override
      protected boolean apply(String action, ActionRequest request, ActionListener<?> listener) {
        threadPool.getThreadContext().putTransient("test-transient", System.currentTimeMillis());
        return true;
      }
    };
```

```bash
curl -vvv https://localhost:9200/*/_search
curl -vvv https://localhost:9200/*/_search
```
```
[2019-03-23T17:07:49,905][WARN ][o.e.c.InternalClusterInfoService] [EuhQC3i] Failed to execute IndicesStatsAction for ClusterInfoUpdateJob
java.lang.IllegalArgumentException: value for key [test-transient] already present
	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.putTransient(ThreadContext.java:557) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.access$900(ThreadContext.java:403) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext.putTransient(ThreadContext.java:301) ~[elasticsearch-6.6.2.jar:6.6.2]
```

**Comment by jasontedor** [comment]
Heya, I think there are some misunderstandings here, sorry that these concepts are not clear nor particularly well documented. However, if you take a look at the class-level Javadocs for `ThreadContext` it might help clear some things up. You need to be stashing the current context, and transient merely means that the headers are not serialized across the network. Since there is not a bug here, I would ask that if you have follow-up questions to please use the forums.

**Comment by sscarduzio** [comment]
Thank you @jasontedor, I followed up on this in the forum as suggested.
https://discuss.elastic.co/t/threadcontext-api/173694
