### ISSUE TITLE
Percolate query ignores "name" parameter

### ISSUE THREAD

**Issue by tlinhart** [elastic/elasticsearch#40405]
**Elasticsearch version** (`bin/elasticsearch --version`): `6.5.4`

**Plugins installed**: `[analysis-icu]`

**JVM version** (`java -version`): `openjdk version "11.0.1" 2018-10-16`

**OS version** (`uname -a` if on a Unix-like system): `Linux 7a321a3f5b0f 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Deployed as a customized Docker image (following [the documented procedure](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html#_c_customized_image)) with only `analysis-icu` plugin installed beyond the default.

**Description of the problem including expected versus actual behavior**:

According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/query-dsl-percolate-query.html#_parameters_10) (and [given example](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/query-dsl-percolate-query.html#_specifying_multiple_percolate_queries)), providing the `name` parameter in percolate query should result in `_percolator_document_slot` field being suffixed with that value if multiple percolate queries are supplied. However, it's not the case and the field is suffixed with the `field` parameter value as if no `name` was provided. Also, the documentation is inconsistent in specifying if the parameter name should be `name` or `_name`.

**Steps to reproduce**:

Issue the percolate query request for two existing documents from `my_index` index (from Kibana Dev Tools):

```
GET watchers/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "percolate": {
            "field": "watcher.query",
            "index": "my_index",
            "type": "_doc",
            "id": "5bf8b8aee6b3da2b8d9f5be8",
            "name": "name1"
          }
        },
        {
          "percolate": {
            "field": "watcher.query",
            "index": "my_index",
            "type": "_doc",
            "id": "5bdaf10f67c85d283c174ad9",
            "name": "name2"
          }
        }
      ]
    }
  }
}
```

Response:

```
{
  "took" : 17,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "watchers",
        "_type" : "_doc",
        "_id" : "5c988b8adc112234588a07b5",
        "_score" : 2.0,
        "_source" : {
          "watcher.query" : {
            "bool" : {
              "must" : {
                "match_all" : { }
              },
              "filter" : {
                "bool" : {
                  "must" : [
                    {
                      "geo_distance" : {
                        "distance" : "2000m",
                        "gps" : {
                          "lat" : 50.132179,
                          "lon" : 14.510528
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "watcher.user_id" : "5b85318b036be43903b294de",
          "watcher.search_id" : "5c988b8adc112234588a07b5",
          "watcher.period" : "immediate"
        },
        "fields" : {
          "_percolator_document_slot_watcher.query" : [
            0
          ]
        }
      }
    ]
  }
}
```

The `fields` object contains `_percolator_document_slot_watcher.query`, however there should be keys like `_percolator_document_slot_name1` and `_percolator_document_slot_name2` present.

What actually works for my use case but is not documented (at least in the context of percolate query) is providing the `_name` parameter. This works just like any other [named queries](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/search-request-named-queries-and-filters.html) resulting in `matched_queries` key in the output:

Request:

```
GET watchers/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "percolate": {
            "field": "watcher.query",
            "index": "my_index",
            "type": "_doc",
            "id": "5bf8b8aee6b3da2b8d9f5be8",
            "_name": "name1"
          }
        },
        {
          "percolate": {
            "field": "watcher.query",
            "index": "my_index",
            "type": "_doc",
            "id": "5bdaf10f67c85d283c174ad9",
            "_name": "name2"
          }
        }
      ]
    }
  }
}
```

Response:

```
{
  "took" : 21,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "watchers",
        "_type" : "_doc",
        "_id" : "5c988b8adc112234588a07b5",
        "_score" : 2.0,
        "_source" : {
          "watcher.query" : {
            "bool" : {
              "must" : {
                "match_all" : { }
              },
              "filter" : {
                "bool" : {
                  "must" : [
                    {
                      "geo_distance" : {
                        "distance" : "2000m",
                        "gps" : {
                          "lat" : 50.132179,
                          "lon" : 14.510528
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "watcher.user_id" : "5b85318b036be43903b294de",
          "watcher.search_id" : "5c988b8adc112234588a07b5",
          "watcher.period" : "immediate"
        },
        "fields" : {
          "_percolator_document_slot_watcher.query" : [
            0
          ]
        },
        "matched_queries" : [
          "name2",
          "name1"
        ]
      }
    ]
  }
}
```

**Comment by jimczi** [comment]
I confirmed that is a bug, the `name` parameter is not copied when the query is rewritten:
https://github.com/elastic/elasticsearch/blob/62f0895424f44742f59bab87ee645b3f46159e1b/modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java#L558
@tlinhart would you be interested in providing a pull request to fix this ? This would be a great starter issue for someone who wanted to contribute.

**Comment by tlinhart** [comment]
Hi @jimczi, yeah, I may give it a try. It just might take some time to setup the environment etc. I guess [CONTRIBUTING.md](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) is the starting point, right?

**Comment by jimczi** [comment]
Thanks @tlinhart ,

> I guess CONTRIBUTING.md is the starting point, right?

It is yes.

**Comment by gurkankaymak** [comment]
Hi @jimczi, are you sure this is a bug?

I've tried with both version 6.5.4 and master, and both of them worked as stated in the documentation, the result contains the name as suffix `_percolator_document_slot_query1`

if you could help me to reproduce the error case, i would be happy to provide a pull request to fix

**Comment by jimczi** [comment]
@gurkankaymak the docs example works because it uses "fake" documents in the query. The bug described here is triggered only when documents are retrieved from an already stored document:
````
{
          "percolate": {
            "field": "watcher.query",
            "index": "my_index",
            "type": "_doc",
            "id": "5bdaf10f67c85d283c174ad9",
            "name": "name2"
}
````

**Comment by gurkankaymak** [comment]
thanks @jimczi, I opened a pull request #40843
