### ISSUE TITLE
Escape characters added to $variables$ break ability to set filters in URLs.

### ISSUE THREAD

**Issue by robcowart** [elastic/elasticsearch#40402]
**Elasticsearch version** (`bin/elasticsearch --version`):

6.6.1 (worked in 6.2 and some later versions, not sure where the change occurred)

**Plugins installed**: []

None

**JVM version** (`java -version`):

Official container

**OS version** (`uname -a` if on a Unix-like system):

Official container

**Description of the problem including expected versus actual behavior**:

Using the generated `$variable$` previously enabled filters to be set in a custom URL. These escape characters now break this ability, resulting in filters such as...
![image](https://user-images.githubusercontent.com/10326954/54906661-0f6fb580-4ee4-11e9-8db7-87cb7ca64cd9.png)

There now seems to be no way to use these variables to consistently set filters.

**Comment by colings86** [comment]
@robcowart It seems like this might be a problem you are seeing in Kibana? If so would you mind opening an issue on the [Kibana Repository](https://github.com/elastic/kibana/issues)?

**Comment by robcowart** [comment]
Well I guess that depends. If the $variables$ are generated by ML engine, which is part of Elasticsearch, and the escape characters are inserted there, then it is an Elasticsearch issue.

Can you confirm that the variables are not generated in any part of the Elasticsearch part of ML, and that the escape characters are not added until Kibana?

**Comment by peteharverson** [comment]
@robcowart the custom URL functionality in the ML plugin is solely used on the Kibana side. It is still possible to use the `$variable$` syntax in the filters part of the URL. I wonder if you have hit an issue with escaping of certain characters which are being substituted for the `$variable$` parts of the drilldown URL, or if there has been a subtle change to the syntax of the URLs between 6.2 and 6.6.2?

Would you be able to reopen this issue in the [Kibana repository](https://github.com/elastic/kibana/issues)? It would help if you could add the JSON for the `custom_urls` part of the ML job (you can copy that from the JSON tab for that job in the ML Job Management page. Also for the screenshot you pasted in above, what are the exact values from the anomaly record that should be going into the filter - I wonder if they contain backward slashes for example?

**Comment by robcowart** [comment]
Thanks for the additional info @peteharverson . Issue opened https://github.com/elastic/kibana/issues/33784
