### ISSUE TITLE
Add ignore_above option for ICUCollationKeywordFieldMapper

### ISSUE THREAD

**Issue by clement-tourriere** [elastic/elasticsearch#40413]
ICUCollationKeywordFieldMapper is not derived from KeywordFieldMapper, but from FieldMapper, so it doesn't have the `ignore_above` configuration. 

The use case is to be able to add a sort field for specific language, ignoring long values. 
For the moment the only solution is to perform this check in the client and separate the `sort` field from the `keyword` field.  

I can provide a PR for this feature.

**Comment by jtibshirani** [comment]
@clement-tourriere to check my understanding of your use case: would you expect that `ignore_above` be applied to the input value, before collation is run?

**Comment by clement-tourriere** [comment]
In fact my use case is to be able to configure a max length on text field indexed with a sort "sub field" https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html. The use case is to ignore long field (considering that they are not sortable) and in the worst case to protect against lucene byte-ref limit https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html.

It might be more logical to apply the `ignore_above` check after collation instead of the input value.

**Comment by jtibshirani** [comment]
@clement-tourriere thanks for the additional details. I could also see an argument for applying `ignore_above` before collation -- this matches the behavior for `keyword` fields, where we check `ignore_above` against the input before any `normalizer` is applied. I've asked other team members for their thoughts on this issue as well.

**Comment by jpountz** [comment]
+1 to support `ignore_above` like `keyword` and make it behave similarly, ie. check the length of the original string rather than the collation. @clement-tourriere you suggested the opposite but I suspect you would be fine with this behavior, wouldn't you?

**Comment by clement-tourriere** [comment]
Yes, it would be absolutely fine for our use case to check the length before collation ;)

**Comment by jtibshirani** [comment]
Great, now that we are clear on that I will take a look at your PR.
