### ISSUE TITLE
FieldMapper Script Multiple

### ISSUE THREAD

**Issue by EliuFlorez** [elastic/elasticsearch#40425]
Hello team, I have a small problem more than anything to be able to establish multiple script since previously I could establish it in 2.4 with

```
module.registerScript(NextOccurrenceSearchScript.SCRIPT_NAME, NextOccurrenceSearchScript.Factory.class);
module.registerScript(HasOccurrencesAtSearchScript.SCRIPT_NAME, HasOccurrencesAtSearchScript.Factory.class);
```

in the new version 6.6 you have an example? I am new and I have more than 2 weeks and nothing. :frowning: 

[https://discuss.elastic.co/t/fieldmapper-multiple-scripts/173825](https://discuss.elastic.co/t/fieldmapper-multiple-scripts/173825)

**Comment by jimczi** [comment]
Hi @EliuFlorez ,
you don't need to duplicate your posts, the discuss forum is the right place to ask this question so I am going to close this issue and I'll use the discuss forum to answer your question.
