### ISSUE TITLE
Add search preference as per index setting

### ISSUE THREAD

**Issue by malpani** [elastic/elasticsearch#40431]
[Search preference](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html) gives knobs for ordering the replica/primary copies against which search should be executed. Today, search dsl allows for a global preference attribute which applies against all indices in the payload. However, as single search can span across multiple indices, I wanted to introduce an optional per index setting to control search preference at individual index levels.

**Feature request/proposed change summary:**
1. An additional per index setting `index.search_preference` which allows for different preference modes at index level
2. Is there value in making search preference pluggable which will allow easier experimentation of routing preferences?
 
**Conflict Resolution:**
If search dsl contains a preference that conflicts with the new index setting `index.search_preference` , I feel the index setting should win, given index settings are more of an admin controlled decision based on careful shard placements
 
**Use case/Background:**
I have a hybrid cluster where some nodes are slow with spinning disks and others are ssd based fast nodes. For most indices on fast nodes, I would like to enforce `adaptive_replica_selection` or `round_robin` as `index.search_preference` but some of the indices on my cluster are on slow hardware I want to enforce `primary_first` (now deprecated) or explicit string based routing to ensure high cache/mmap hits

I would love to get some feedback on this request and will also be happy to contribute a PR if this sounds useful.

**Comment by jimczi** [comment]
>  I want to enforce primary_first (now deprecated) or explicit string based routing to ensure high cache/mmap hits

I don't really understand why you'd give the same search preference to all your queries. What is the point of having replicas if you route all your queries to the primaries ? If some shards are slower the `adaptive_replica_selection` should handle this nicely without the need to add a new index setting. Also note that `adaptive_replica_selection` is a cluster setting that cannot be set per query and I don't think we should allow to change this value in the search preference.

**Comment by malpani** [comment]
> I don't really understand why you'd give the same search preference to all your queries.

The use case is cold read only indices on spinning disks. By `primary_first` i ensure that better utilization - off heap mmaped files are not being swapped out, on heap caches are not staggered etc.

I am trying to understand the opposite, in what scenarios will someone give different search preferences for the same index across different queries? 
ie. Would it be better to give an option to fix this at index levels which is what this feature request aims at.

> What is the point of having replicas if you route all your queries to the primaries ? 
Besides the performance, replica ensures search availability and durability, essentially this feature gives us passive replicas
* Availability - For any transient failures when the node drops/goes OOM/network flip etc., the query will get retried on the next copy as decided by search preference (passive replica in my case)
* Durability - The replica still protects from fault tolerance of permanent node failures (yes as these are read only i can restore from snapshot too but it would not meet the availability point) 

> Also note that adaptive_replica_selection is a cluster setting that cannot be set per query and I don't think we should allow to change this value in the search preference.

You are right, `adaptive_replica_selection` is cluster wide, as it needs to track historic response times etc. which would break if turned on just at query level. The refined idea for `adaptive_replica` would be the cluster wide setting turns on stats collection but `index.search_preference` can take on different modes and use those stats or even allow a plugin to come up with its own preference

**Comment by jimczi** [comment]
> The use case is cold read only indices on instances with high disk to memory ratio (eg. 40 TB storage v/s 128 GB RAM). By primary_first i ensure better utilization - off heap mmaped files are not being swapped out, on heap caches are not staggered etc.

If you have a high disk to memory ratio I doubt that different queries will hit the same page on disks. In fact with this setup I wonder if this would not have the inverse effect of slowing down queries since you'd have more IOs than if you spread the traffic on multiple cold nodes. 

> I am trying to understand the opposite, in what scenarios will someone give different search preferences for the same index across different queries?
ie. Would it be better to give an option to fix this at index levels which is what this feature request aims at.

The custom string value is often used with session id or user names, this way identical queries within a session have more chance to return the same result and/or be retrieved from the cache. The assumption here is that queries in a single session are related so the probability that they'll hit the same page/cache is higher. Kibana for instance uses the session id of the user to fill the search preference when they send queries to Elasticsearch.

> Besides the performance, replica ensures search availability and durability, essentially this feature gives us passive replicas

This is based on the assumption that hitting the same replicas on different queries should be faster. I don't think this is true for cold nodes where there is a high disk to memory ratio. Have you tried the 
`adaptive_replica_selection` ? Sorry to repeat but this looks like the perfect candidate to route queries when you have nodes with different configurations and indices.

**Comment by malpani** [comment]
Thanks for the sessionId example. 

> I wonder if this would not have the inverse effect of slowing down queries since you'd have more IOs than if you spread the traffic on multiple cold nodes.

Guess it depends on the number of cold nodes. To describe my setup in more detail 
* 10 hot nodes
* 5 cold nodes
* 5 shards per index rotating hourly. (application logs)
Normally cold indices never get queries, unless there is an adhoc investigation. In steady state, i expect each cold node to contain 1 primary and passive replica per index. For such scenarios, i was thinking passive replica will ensure better gains.

I do see your reasoning and this feature may not be helpful to many people v/s letting `adaptive_replica_selection`  figure out the preferences. I will also try `adaptive_replica_selection` once again.

**Comment by jimczi** [comment]
You should also take a look at a new feature added in 6.6 called [`frozen indices`](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/frozen-indices.html) which aims at reducing the cost of keeping this old indices that are queried very rarely.

**Comment by malpani** [comment]
How does `adaptive_replica_selection` work for frozen indices? Does it end up loading the searchers/transient memory on both primary and replica depending on who gets the request? Wondering if `primary_first` index level setting might the best fit for search preference among frozen indices to avoid this duplication?

**Comment by jimczi** [comment]
> Wondering if primary_first index level setting might be a good fit for search preference among frozen indices to avoid this duplication?

Frozen indices are lazily loaded on a per request basis and the memory is released at the end of the request. As stated above you can control which replicas is responsible for the request with a custom search preference so I am going to close this issue. We can continue this discussion in the [forum](https://discuss.elastic.co/c/elasticsearch) if you want further questions.

**Comment by malpani** [comment]
@jimczi - here is the patch I am using as it works better for the above use case v/s adaptive_replica in case this direction might be of use to someone
[perIndexSearchPrerenceOverridePatch.txt](https://github.com/elastic/elasticsearch/files/3035644/perIndexSearchPrerenceOverridePatch.txt)

I am able to fix and override (any search dsl specified) strategies on a per index basis using 
`curl -H "Content-Type: application/json" -XPUT localhost:9200/cold_2017-12-23/_settings -d '{"index.routing.search_preference": "_primary_first"}'`
