### ISSUE TITLE
The indices have been exchanged between the two clusters in one machine

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#40465]
**Elasticsearch version** : All
**JVM version** :  1.8.0_45
**OS version** :  linux
**Description **
Suppose we deploy two instances of elasticsearch service on same machine, for example cluster1, cluster2. 
we both set configuration as follow in elasticsearch.yml of both two instances:
1. node.max_local_storage_nodes : 2
2. path.data: /data1/es_data/

steps are as follow:
- we create an index separately in each cluster, those indices's distribution is as follows:
[cluster1 ] :index1
[cluster2 ] :index2
we find that data path of cluster1 is /data1/es_data/nodes/0/indices/*, and data path of cluster2 is /data1/es_data/nodes/1/indices/*
- we shut down both of two clusters, then restart cluster2,  lastly restart cluster1. the order of startup is very important.
As a result, those indices's distribution changes:
[cluster1 ] :index2
[cluster2 ] :index1
index1 should exist in cluster1, but exists in cluster2, and index2 exactly the Opposite.

**Reason **
 We observe such a fact: after we restart cluster of cluster2 first, cluster2 regards /data1/es_data/nodes/0/indices/* as its data.path. cluster1 regards /data2/es_data/nodes/1/indices/* as its data.path. the indices have been exchanged between the two clusters, it is unacceptable. The problem is here: https://github.com/elastic/elasticsearch/blob/4469cf0db81e74c63e2ff2eb5970039a541d1adf/server/src/main/java/org/elasticsearch/env/NodeEnvironment.java#L265 
we can see that cluster2 is restarted  firstly, it obtains /data1/es_data/nodes/0/indices/. then cluster1 restarts, it tries to set possibleLockId=0, but fails, it can only set possibleLockId=1, as the result, cluster1 regards /data2/es_data/nodes/1/indices/* as its data.path. it may be unreasonable that the data.path is uncertainly

**Solution**
in elasticsearch.yml, we can set "node.id: 0/1", so the data path of each node is very clear.

**Comment by jasontedor** [comment]
Actually we would discourage using this setting like this. In fact, our documentation says:

>The <<data-path,data path>> can be shared by multiple nodes, even by nodes from different
clusters. This is very useful for testing failover and different configurations on your development
machine. In production, however, it is recommended to run only one node of Elasticsearch per server.

We use this in testing indeed, but we think that using this functionality in production is dangerous. This is why in a previous major version we changed the default value for this setting to one. It it too easy to get yourself in trouble, of the sort that you're getting into, by using this functionality. I would encourage you to instead use a separate data path per cluster.

Therefore, I don't think we should complicate this already dangerous functionality. Instead, I would prefer that we continue to discourage its usage.

**Comment by kkewwei** [comment]
@jasontedor, I agree with your opinion, we can set different data.path in config file of two instances of the same machine, then it solves. In product, that we deploy two instances of the same machine has very little probability of happening, but this does happen. I think we may be avoid it at the level if code. can we solve it by letting 
`/data1/es_data/nodes/xxx/indices/*` be determined, for example we can set xxx to be cluster.name.    it avoids this problem when setting same data.path.

**Comment by jasontedor** [comment]
I am not sure if it's worth it, for then we have to go through a transition from the current format to the new format with a deprecation period, adding upgrade code to migrate from one to the other, and then eventual rejection code when we see the old format. It also complicates the situation for users that want to change their cluster name.

**Comment by jasontedor** [comment]
We discussed this discussed this amongst the core/infra team and agreed that we do not want to make any changes along the lines discussed here. Instead, we think that you should use separate data paths for each cluster, as [previously proposed](https://github.com/elastic/elasticsearch/issues/40465#issuecomment-476760606). For example, you could:

```
$ mkdir /data1/es_data/cluster1
$ mkdir /data1/es_data/cluster2
```

and set `path.data: /data1/es_data/cluster1` for nodes in `cluster1` and `path.data: /data1/es_data/cluster2` for nodes in cluster2. Then you would not have this problem.
