### ISSUE TITLE
Plugins missing in 6.7

### ISSUE THREAD

**Issue by ZeusF1** [elastic/elasticsearch#40506]
**Elasticsearch version** (`bin/elasticsearch --version`):
elasticsearch-6.7.0-1.noarch
**Plugins installed**: [which i whould like to instal atleast :-P ]
ingest-geoip
ingest-user-agent
**JVM version** (`java -version`):
java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Centos 7
Linux 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
```
/usr/share/elasticsearch/bin/elasticsearch-plugin list
```
no output
no plugins
```
/usr/share/elasticsearch/bin/elasticsearch-plugin list -v
Plugins directory: /usr/share/elasticsearch/plugins
```

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Elastisearch requere to remove and (re-)install plugins
 2. no plugins for version 6.7 ()
 3.

```
/usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip && /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-user-agent
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin ingest-geoip
```

**Comment by jasontedor** [comment]
Heya, please see the [migration guide for 6.7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.7.html#breaking_67_plugin_changes) which covers this.

**Comment by awo0917** [comment]
我的es7.3也有同样的问题

**Comment by BartolottiLuca** [comment]
> Heya, please see the [migration guide for 6.7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.7.html#breaking_67_plugin_changes) which covers this.

@jasontedor the link is not working anymore and I'm facing this issue, any suggestion?

**Comment by jasontedor** [comment]
@BartolottiLuca Sorry for that, I have corrected the link.
