### ISSUE TITLE
Upgrades to 6.7 didn't restart all services

### ISSUE THREAD

**Issue by OrangeDog** [elastic/elasticsearch#40512]
Possibly there's a separate place to report packaging bugs?
I'm using the packages from https://artifacts.elastic.co/packages/6.x/apt on Ubuntu Bionic.

Upgrades to 6.7.0 (logstash, elasticsearch, kibana) successfully installed, but only the kibana service restarted. This means it stopped working as it requires elasticsearch 6.7 to be running.

> Status changed from yellow to red - This version of Kibana requires Elasticsearch v6.7.0 on all nodes. I found the following incompatible nodes in your cluster: v6.6.2 @ 127.0.0.1:9200 (127.0.0.1)

Either all package postinst should restart/reload the service (probably preferred for security updates) or none of them should.

**Comment by jasontedor** [comment]
We [document](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/rpm.html#rpm-configuring) that you can set `RESTART_ON_UPGRADE` to `true` and Elasticsearch would be restarted when you upgrade.
