### ISSUE TITLE
Log ILM actions

### ISSUE THREAD

**Issue by mikemadden42** [elastic/elasticsearch#40552]
I originally described this feature on discuss [here](https://discuss.elastic.co/t/location-of-ilm-logs/174180).  I was asked to create an issue for this feature.

We've started setting up ILM in our Elastic Stack 6.6.1 cluster. I was wondering where ILM actions are logged. For example, if I setup ILM to delete certain indices older than 2 weeks, where can I see which indices where deleted?

Across our various clusters we have thousands of indices, and it would be nice to have a log of which logs are getting removed.

**Comment by dakrone** [comment]
@mikemadden42 we do log ILM things that you can see (in great verbosity, adjust to your liking) with:

```
PUT /_cluster/settings
{
  "transient": {
    "logger.org.elasticsearch.xpack.core.indexlifecycle": "TRACE",
    "logger.org.elasticsearch.xpack.indexlifecycle": "TRACE"
  }
}
```

Is that sufficient for your use case?

**Comment by mikemadden42** [comment]
Thanks @dakrone .  The settings you mentioned looked promising.  Would the more verbose ILM logs appear in the main Elasticsearch log?

**Comment by dakrone** [comment]
Yes that's correct

**Comment by dakrone** [comment]
I'm going to close this for now, since we have a solution, if it doesn't work out we can always re-open this.
