### ISSUE TITLE
SQL: LIKE not treating whitespaces correctly -- version 6.7.0

### ISSUE THREAD

**Issue by broodfusion** [elastic/elasticsearch#40557]
**Elasticsearch version** (`bin/elasticsearch --version`): `6.7.0`

**Plugins installed**: []

**JVM version** (`java -version`): 
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): `MacOS Mojave 10.14.4`

**Description of the problem including expected versus actual behavior**:
I noticed that when using `LIKE`, in this case `LIKE 'B 4E%'`, under the hood it's no longer using a wildcard query, but instead `query_string` (from the translate API):
```
"bool" : {
      "must" : [
        {
          "query_string" : {
            "query" : "B 4E*",
            "fields" : [
              "station.keyword^1.0"
            ],
            "type" : "best_fields",
            "default_operator" : "or",
            "max_determinized_states" : 10000,
            "enable_position_increments" : true,
            "fuzziness" : "AUTO",
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "phrase_slop" : 0,
            "escape" : false,
            "auto_generate_synonyms_phrase_query" : true,
            "fuzzy_transpositions" : true,
            "boost" : 1.0
          }
        },
```
Problem I'm having is that my `LIKE` clause above has whitespaces and it's not treated correctly as it was before with the `wildcard`. I believe that because of the whitespace I have above, the query is trying to match on `B` or `4E%`, but I want `B 4E%`...

The hacky solution I came up with was to replace the whitespaces with underscore, so `B 4E%` became `B_4E%` which then gave me the expected response data. 

Can anyone please advise on this issue? Thanks

**Comment by astefan** [comment]
@broodfusion nice catch. Indeed, we broke something with one of our PRs.

**Comment by broodfusion** [comment]
@astefan ok so it is a bug, for a second there I thought this change was intentional. Thanks

**Comment by astefan** [comment]
@broodfusion LIKE and RLIKE should work only on exact fields, that is `keyword` fields. If a field is `text` but it does have a `keyword` sub-field (a very common practice in ES world) without a normalizer, we will automatically use that sub-field.
Given this restriction, the ES queries to be used in these cases are `wildcard` (for LIKE) and `regexp` (for RLIKE).

I'm working on a PR to document this, as well.

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/1bba887d481b49db231a1442922f1813952dcc67
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/dfe4c6c568975c9145f70c61ab312d0b2981f5df
7.0 (7.0.0): https://github.com/elastic/elasticsearch/commit/822570ead50795ac8444bb7edb372a9558feca20
6.7 (6.7.2): https://github.com/elastic/elasticsearch/commit/7801c9fe8cde20be5249a061f246c9afb1fa652f
