### ISSUE TITLE
Support for geohash_grid in composite aggs

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#40568]
[geohash_grid](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search-aggregations-bucket-geohashgrid-aggregation.html) seems like a natural fit for a composite agg source. Being able to iterate over geo buckets could open up some interesting use cases.

**Comment by henargv** [comment]
Is this enhancement already implemented? Thanks!!

**Comment by benwtrent** [comment]
@henargv not yet. I personally have not had any cycles yet to take a stab at it. 

I am not 100% sure if it will be straight forward or not, but the current composite aggs in `org.elasticsearch.search.aggregations.bucket.composite` provide good examples of how this needs to be implemented.

**Comment by polyfractal** [comment]
@benwtrent I believe this can be closed, correct?

**Comment by benwtrent** [comment]
I think so. `geotile_grid` covers it :)
