### ISSUE TITLE
shared allocation, synchronization and merged segements  at the same time after inverted-index ineffective

### ISSUE THREAD

**Issue by karlspace7** [elastic/elasticsearch#40577]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): CentOS

**Description of the problem including expected versus actual behavior**:
When the index is written in large quantities, shared allocated, synchronized and merged segments at the same time. After that, the search is invalid and the inverted index is invalid.

**Provide logs (if relevant)**:
no output error log

**Comment by HeatoN7** [comment]
I've had similar problems when I use es5.4.
No error logs may be a problem with your log output configuration.
The problem core is that too many threads execute at the same time causing write index exceptions, perhaps this will also affect the previous index, making the old index unavailable.
Do these operations separately, not simultaneously! When you rebuild, it's better to written finish, then redistribute, then synchronize at last.
Try to upgrade your es to a new version, they have better performance.

**Comment by karlspace7** [comment]
thanks your answer
