### ISSUE TITLE
[DOCS] Document "can not run elasticsearch as root" check

### ISSUE THREAD

**Issue by dharada** [elastic/elasticsearch#40570]
**Describe the feature**: this is not feature request.

**Elasticsearch version** (`bin/elasticsearch --version`):  6.7 (current version)

**Plugins installed**: []
**JVM version** (`java -version`):
**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

It seems no official document is provided about "Remove allow running as root" in bootstrap checks part.  (sorry, if I miss something.  are there something for undocumented intentional?)
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/bootstrap-checks.html

I think it should be better to indicate in the official docs explicitly.
(or intentionally undocumented? )

PR of "Remove allow running as root"
- https://github.com/elastic/elasticsearch/pull/18694/files

(ref)
https://discuss.elastic.co/t/why-is-it-elasticsearch-is-not-allowed-to-run-as-root/60413

**Comment by tvernum** [comment]
@dharada Technically, the "can not run elasticsearch as root" check isn't a _Bootstrap Check_, (it's just a check that happens on start up).

However, it seems you are correct that we don't have a page for it and it would probably be helpful to explain to users that this check exists and we don't provide a way to by-pass it.

**Comment by dharada** [comment]
Thanks for the clarification. :)  @tvernum 

That check logic is implemented in org.elasticsearch.bootstrap.Bootstrap class.  so I thought it is a part of  _Bootstrap Check_. sorry for misunderstanding.!

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

**Comment by lockewritesdocs** [comment]
We document in the [ES security principles](https://www.elastic.co/guide/en/elasticsearch/reference/current/es-security-principles.html#security-not-root-user) that users should run with a dedicated, non-root user. Closing this issue, which hasn't been updated for 3+ years.
