### ISSUE TITLE
Ingest node time period processor

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#40615]
Users often model events using a start and end time as two different fields on a document. It is often advantageous to determine the difference in duration for those two dates.

This enhancement request is to create a `period` processor that can read two input fields in date form and calculate the period of time between the dates as a `long` value in the time unit chosen.

Since the date values may be affected by timezone offsets, and requires a different pattern for obtaining inputs from the ingest document, the thought is to build this as a separate processor from the planned duration processor (#39857) which only deals with general spans of time not related to a contextual date. The period processor would take dates and offsets into account to ensure that time changes are accurately calculated. Additionally, having separate duration and period processor implementations would allow for clarifying the differences in semantics between the two.

An example:
```json
{
  "period": {
    "start_field": "time.begin",
    "end_field": "time.end",
    "to_unit": "seconds",
    "target_field": "time.in_seconds"
  }
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
