### ISSUE TITLE
Elasticsearch aggregation query ignores parent filter when setting min_doc_count to 0 in child terms aggregation

### ISSUE THREAD

**Issue by m5tt** [elastic/elasticsearch#40621]
If i run this query in Elasticsearch, it returns a bucket set aggregating on field `name`. Not returning any document that has a `type` field of **1** This is correct.

```
{:size=>0,
 :aggs=>
  {:agg=>
    {:filter=>{:term=>{"type"=>1}},
     :aggs=>{:agg=>{:terms=>{:field=>"name", :min_doc_count=>1}}}}}}
```

Now if i run this exact same query, changing _only_ `min_doc_count` to **0**. Then it _ignores_ the parent filter aggregation and returns _all_ documents, regardless of type. 

```
{:size=>0,
 :aggs=>
  {:agg=>
    {:filter=>{:term=>{"type"=>1}},
     :aggs=>{:agg=>{:terms=>{:field=>"name", :min_doc_count=>0}}}}}}
```

If i reverse the query, ie the filter aggregation nested inside the terms, then it doesnt work regardless of the `min_doc_count` setting. 

I understand this is documented [Here:](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html)

> Setting  `min_doc_count` = `0`  will also return buckets for terms that didn’t match any hit. However, some of the returned terms which have a document count of zero might only belong to deleted documents or documents from other types, so there is no warranty that a  `match_all`  query would find a positive document count for those terms.

**However there _must_ be a way to build a aggregation query that returns documents with a doc_count 0 which are _also_ filtered by a filter aggregation.**

I am using Elasticsearch 6.x, and using it through the Elasticsearch Rails gem.

**Comment by jimczi** [comment]
> However there must be a way to build a aggregation query that returns documents with a doc_count 0 which are also filtered by a filter aggregation.

The `terms` aggregation returns buckets not documents so with `min_doc_count` set to 1 you ensure that all buckets contains at least one document that match the query and the aggregation filter. Now if you set `min_doc_count` to 0 this means that you also want to take into account terms that don't appear in any of the documents that match the query **and** the agg filter. I don't see how it would be possible to return a term with a doc_count of 0 if it appears in a document that match the filter aggregation, the fact that it matches the filter implicitly sets the doc_count to at least 1 for the term.

**Comment by m5tt** [comment]
I'm not sure i follow this logic. 

All i want, is a list of buckets with `doc_count >= 0` that does not include documents i previously filtered out.

Logically, i feel like this is how it should work. If i have a list of _all_ documents A. Then i run a aggregation filter i should end up with a reduced document list B. Now i run a terms aggregation, which groups documents from list B into buckets on some attribute. 

The resulting list of buckets should not include documents from the original list A.

Example, i run a filter aggregation that matches all documents provided they do not match a `type` of `t`. Then i run nested terms aggregation on `type`. 

The resulting list of buckets should _not_ include a bucket with a `key` `t`. 

Again to reiterate all i want, is a list of buckets with `doc_count >= 0` that does not include documents i previously filtered out.

Maybe `min_doc_count` is the wrong way to go about this, but there _must_ be some way in doing this.

**Comment by jimczi** [comment]
Ok thanks for explaining. There are multiple ways to perform what you want. Here's one way to do it with the `filters` aggregation and the  `other_bucket_key` option:
```
{
    "size": 0,
    "aggs": {
        "messages": {
            "filters": {
                "other_bucket_key": "neg",
                "filters": {
                    "pos": {
                        "term": {
                            "type": "1"
                        }
                    }
                }
            },
            "aggs": {
                "terms": {
                    "terms": {
                        "field": "name"
                    }
                }
            }
        }
    }
}
```
This query will create a `pos` bucket for documents that match the filter and a bucket `neg` for documents that don't match. The nested `terms` aggregation will compute the top N for each of these buckets.
I am going to close this issue because we reserve github for verified bugs and feature requests. If you have further questions we can continue to discuss in the [forum](https://discuss.elastic.co/c/elasticsearch).
