### ISSUE TITLE
Add "origin" string (or metadata) to CreateSnapshotRequest

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#40638]
In #38461 we are working towards a snapshot lifecycle management where snapshots can automatically be taken. One thing that would be helpful, however, is to know how a snapshot originated (like which policy created the snapshot).

It would be great if we could extend the `CreateSnapshotRequest` (and optionally the REST layer) to allow providing an "origin" (or metadata, if we want to be more generic) string when creating the snapshot. This would then show up when the snapshot was listed from the repository.

/cc @original-brownbear

**Comment by ywelsch** [comment]
I would prefer to have a general-purpose `_meta` field ([like we have for mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html)) rather than an "origin" field.

**Comment by gwbrown** [comment]
This has been implement in https://github.com/elastic/elasticsearch/pull/41281.
