### ISSUE TITLE
SQL: Allow TIME data type in GROUP BY & HISTOGRAM

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#40639]
Currently `TIME` data type is internally modelled as `OffsetTime` which is not treated correctly by ES scripting modules which causes queries like:
```
SELECT count(*) FROM test GROUP BY CAST(date_created AS TIME);
```
and
```
SELECT HISTOGRAM(CAST(birth_date AS TIME), INTERVAL '10' MINUTES) as h, COUNT(*) FROM t GROUP BY h
```
to fail.

To correctly implement this `TIME` -> OffsetTime must be converted to Long for the scripting purposes and converted back to `OffsetTime` when values are extracted from ES response.

**Comment by wchaparro** [comment]
Superceded by ES|QL
