### ISSUE TITLE
Analysis Synonym: Shared on node level + auto reload from file system

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#4063]
Two important changes to synonyms:

- Share the synonym FST on the node level, keyed by the `Settings`, so if there are multiple indices sharing the same settings, they would also share the same FST.

- Using the new file watcher service, we can automatically reload synonyms if configured on the file system and changed. Might make sense to have a "reloadble" token filter support for other cases where we are interested in it.

This is a great candidate to backport to 0.90 if implemented.

**Comment by clintongormley** [comment]
Closing in favour of #8961
