### ISSUE TITLE
[CI] WatchMetadataTests#testWatchMetadata test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#40631]
```
  1> [2019-03-28T15:09:36,596][INFO ][o.e.x.w.t.i.WatchMetadataTests] [testWatchMetadata] after test
FAILURE 1.06s J7 | WatchMetadataTests.testWatchMetadata <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value greater than <0L>
   >      but: <0L> was equal to <0L>
   >    at __randomizedtesting.SeedInfo.seed([1D60679C9809AF1C:8A18F6576683372E]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.watcher.test.integration.WatchMetadataTests.testWatchMetadata(WatchMetadataTests.java:65)
   >    at java.lang.Thread.run(Thread.java:748)
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/561/console

Does not reproduce with the random seed, but this test does fail when executed locally with `-Dtests.iters=x`.

**Comment by droberts195** [comment]
This failed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/136/console

I muted the test on master in 6df64d26c5230da5d67a4b59df749da451d0f080

**Comment by martijnvg** [comment]
I backported the @droberts195's commit to 7.x, 7.0 and 6.7 branches too, because this test failed on these branches as well.

**Comment by gwbrown** [comment]
https://github.com/elastic/elasticsearch/pull/40658 has been merged to all currently maintained branches after a week of running in master with no failures in this test, so I'm closing this issue.
