### ISSUE TITLE
Geo distance query builder ignoring unit of measurement

### ISSUE THREAD

**Issue by Schachte** [elastic/elasticsearch#40645]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): mac os x latest

**Description of the problem including expected versus actual behavior**:

I'm trying to generate a `geo_distance` filter from my OGC filter and it seems as if the unit is being ignored, even if I hardcode it.

## Java

```
boolQueryBuilder.must(
          geoDistanceQuery(ANY_GEO_MAPPING)
              .point(coords[0].getOrdinate(1), coords[0].getOrdinate(0))
              .distance(filter.getDistance(), DistanceUnit.FEET));
      return boolQueryBuilder;
```

## Resulting JSON

```
{
  "bool" : {
    "must" : [
      {
        "geo_distance" : {
          "anyGeo" : [
            -107.908977,
            41.306675
          ],
          "distance" : 663.5960582256,
          "distance_type" : "arc",
          "validation_method" : "STRICT",
          "ignore_unmapped" : false,
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}

```

## Expectation:

In this case, I'd expected `"distance" : 663.5960582256` to be suffixed with `feet` or `ft`

https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#distance-units

**Comment by ebadyano** [comment]
Java client input is always converted to a double in meters. So `663.5960582256` should be equal to the original distance `filter.getDistance()` in `feet` converted to `meters`. @Schachte  Are you seeing any issues related to this automatic conversion?

**Comment by imotov** [comment]
Just in case I tested it with the following parameters:
```
QueryBuilders.geoDistanceQuery("test")
    .distance(10, DistanceUnit.FEET)
    .point(GeoPoint.parseFromLatLon("1,1"));
```
And got back
```
{
  "geo_distance" : {
    "test" : [
      1.0,
      1.0
    ],
    "distance" : 3.048,
    "distance_type" : "arc",
    "validation_method" : "STRICT",
    "ignore_unmapped" : false,
    "boost" : 1.0
  }
}
```
as expected (10 feet is indeed 3.048 metter)

**Comment by Schachte** [comment]
Thanks guys. I was not aware that automatic conversion was happening. I misread the docs and saw 
`"distance" : "200km",` thinking I would see the unit of measurement in the response. Thanks!
