### ISSUE TITLE
[DOCS] Create task related to backing up your cluster

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#40663]
Per https://github.com/elastic/stack-docs/issues/226#issuecomment-467223735 the documentation about "Upgrading the Stack" (https://www.elastic.co/guide/en/elastic-stack/7.0/upgrading-elastic-stack.html) says:

> Back up your data. You cannot roll back to an earlier version unless you have a snapshot of your data. For information about creating snapshots, see Snapshot and Restore.

That "Snapshot and Restore" is a reference page (https://www.elastic.co/guide/en/elasticsearch/reference/7.0/modules-snapshots.html) and it would be better to refer users to a task-oriented page like https://www.elastic.co/guide/en/elasticsearch/guide/2.x/backing-up-your-cluster.html which can walk users through a typical set of steps to back up their cluster. 

See also https://github.com/elastic/stack-docs/issues/226#issuecomment-467344557

**Comment by debadair** [comment]
[docs issue triage]

**Comment by debadair** [comment]
Closing as fixed.
