### ISSUE TITLE
I have a problem “Read-only file system”

### ISSUE THREAD

**Issue by iture123** [elastic/elasticsearch#40670]
**Describe the feature**:

**Elasticsearch version** (6.6.2):

**Plugins installed**: []

**JVM version** (1.8.0_131):

**OS version** (centos 6.5):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.One node have  10 hard drives.What should I do when one hard is ”Read-only file system”?
 2.The used  space of the failed hard disk is 6%.
 

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests. The discussion forums
are beter suited to these sorts of troubleshooting and problem diagnosis
conversations.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

Thank you.
