### ISSUE TITLE
Continuation to issue 40572

### ISSUE THREAD

**Issue by kowndinyav** [elastic/elasticsearch#40716]
I am not sure how to re-open the same issue, So creating a new issue for: https://github.com/elastic/elasticsearch/issues/40572

Please refer to issue 40572 for the detailed bug description and the resolution suggested by @jimczi 

If I remove, empty inner_hits, reply document snippets are not returned. Please try the same at your end once. If my understanding is wrong, could you please share the query that returns both comments and replies without missing any of the matching snippets. That would be immensely helpful

**Comment by danielmitterdorfer** [comment]
@kowndinyav thank your for your interest in Elasticsearch. I think it would make sense to continue the discussion in #40572 and therefore I am going to close this issue. Can you please add your comment on the original issue? Thank you! :)
