### ISSUE TITLE
SQL input for Watcher

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#40737]
SQL input would make Watcher more accessible for new users. 
Currently there are 2 main skills the user need to develop a watch:
- Elasticsearch search and aggregations
- Painless scripting for watcher advances conditions

Adding a SQL input to watcher (which hopefully is a not a big effort) will give users the power to develop watches with all the power of searches and most of aggregations + the main set of conditions for a single and array values without scripting

**Comment by jakelandis** [comment]
We discussed this and came to the conclusion that this would result in a fairly large effort and would not introduce any new functionality. Its a pretty significant undertaking and only addresses parts of the difficulty new users have with Watcher.  Additionally there are some [other efforts](https://www.elastic.co/blog/alerting-in-the-elastic-stack) in the this space that should help with creating alerts in a more user friendly manner.
