### ISSUE TITLE
Bulk Index Api bandwidth efficiency 

### ISSUE THREAD

**Issue by Arcabard** [elastic/elasticsearch#40749]
When using the Bulk Send API to index a large amount off entries using the "action" index
```
{"index": {"_index": "x", "_type": "_doc"}}
{x:0}
{"index": {"_index": "x", "_type": "_doc"}}
{x:0}
{"index": {"_index": "x", "_type": "_doc"}}
{x:0}
{"index": {"_index": "x", "_type": "_doc"}}
{x:0}
{"index": {"_index": "x", "_type": "_doc"}}
{x:0}
```
begins consuming a fairly large amount of bandwidth quickly.

It would be much better for bandwidth and processing speed to be able to specify how many following records this action applies to 
```
{"index": {"_index": "bank_accounts", "_type": "account",__records__:3}}
{x:0}
{x:0}
{x:0}
```
Avoiding a gigajillion if statements and the excessive  padding

I apologize if this is something you can already do, as I did not find any documentation as such.

\o/

**Comment by jasontedor** [comment]
Do you have some evidence to support this being a bottleneck? I would not expect this to be where the bulk (pun!) of the time is spent, as instead actually executing the indexing requests would be where the bulk of the time is spent. Further, if the bandwidth is truly a problem here, have you tried gzip compression on the HTTP payload?

**Comment by Arcabard** [comment]
I don`t have a rig set up I can test such a change easily on!
 
Sending 3 000 000 entries the extra padding added 132MB to the payload and 132MB of string concatenation in the programming processing my data.

It is probably trivial ( but may not be ? ) but I am sure skipping a few million if statements does add to the time spent processing on the index.

It would be a nice feature and would make ES slightly faster and more efficient for a lot of people sending a lot of preloaded data that's been processed locally.

**Comment by jasontedor** [comment]
> I don`t have a rig set up I can test such a change easily on!

I am not looking for a test of the change so much as I am looking for evidence of this being a bottleneck.

We tend to minimize the complexity and surface area of our APIs, as it only leads to more room for user-confusion, code for us to maintain, and bugs on our end. Absent a compelling reason, our bias would be not introduce a change like this.

> Sending 3 000 000 entries the extra padding added 132MB to the payload and 132MB of string concatenation in the programming processing my data.

This does not sound like much overhead to me, only 46 bytes per entry. It would be interesting to know how much more time this causes in processing on the client side, and whether or not that can be optimized away. The tradeoff here is you have to do extra processing client side to prepare the format that you propose, so it might be a wash anyway.

> It is probably trivial ( but may not be ? ) but I am sure skipping a few million if statements does add to the time spent processing on the index.

Sure, it probably adds time, but in proportion to the time that would be spent indexing, it's almost surely negligible (this is my gut, I don't have any data to back it up).

**Comment by jasontedor** [comment]
Thanks for your interest and feature proposal. Absent a compelling reason to make this change, I don't think we'll be making any changes along the lines suggested here. We are happy to reconsider this based on more feedback, so don't take me closing this issue as a sign that the conversation is done, only as an indication that for now we won't be implementing this.
