### ISSUE TITLE
Re-support featrue shadow replica and copy segment to replica with lucene-replicator

### ISSUE THREAD

**Issue by zhichen** [elastic/elasticsearch#40767]
Our need is to reduce the cost of copy storage and the flexibility of data nodes and storage.
So we are considering the implementation of the shadow replica. The replica delay based on the primary shard flush can be seen for a long time, in order to shorten the visible time of the replica. We found that Lucene's author, Michael McCandless made a simple framework for physical replication - Lucene-replicator (http://blog.mikemccandless.com/). Our main idea is that the primary shard writes data to NFS, and copies the nrt segment to the replica through the Lucene-replicator framework, and the replica is read-only.

Will the community working on this featrue again?

**Comment by DaveCTurner** [comment]
Duplicates https://discuss.elastic.co/t/questions-about-shadow-replica/175146 - I will answer on the forum.
