### ISSUE TITLE
Reject port ranges in `discovery.seed_hosts`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#40786]
Today Elasticsearch accepts, but silently ignores, port ranges in the `discovery.seed_hosts` setting:

```
discovery.seed_hosts: 10.1.2.3:9300-9400
```

Silently ignoring part of a setting is trappy and we should instead reject this setting if it contains port ranges like this.

**Comment by Hohol** [comment]
I'd like to work on this. Could you assign me please?

**Comment by DaveCTurner** [comment]
Hi @Hohol, I can't assign issues outside of the Elastic organisation, but you're welcome to work on this.

**Comment by Hohol** [comment]
@DaveCTurner I've made a PR https://github.com/elastic/elasticsearch/pull/41404
