### ISSUE TITLE
provide isolation to system indices

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#40802]
**Describe the feature**: Make "system" indices actually reserved in some capacity. Currently only the naming (start with a `.`) sets them apart from any other index in the cluster. They have no real isolation; they can easily (and mistakenly) have mapping overridden, deleted, etc. 

Maybe add something in the index settings to serve as metadata, eg. `system_owned: true`. This could be used to prevent normal operations from applying to these indices, and require a special url parameter to be set in order to make modifications.

Steps to reproduce a "system" index: `PUT .my_system_index`

**Comment by jasontedor** [comment]
@jpcarey We have plans along these lines, but they are in very early stages. In the future it is likely that we will close this issue in favor of another issue that outlines our plan for true system indices as a first-class concept.

**Comment by jpcarey** [comment]
Adding one additional item for consideration, the search API uses wildcard functionality for expansion on index names. There is no (easy) way to search all indices, while excluding system indices (eg. `*/_search`).

**Comment by jasontedor** [comment]
Thanks for the feedback, that specific item is included in our thinking on system indices already. 😄

Please keep the suggestions coming!

**Comment by jaymode** [comment]
I'm going to close this issue in favor of #50251
