### ISSUE TITLE
ERROR: Temporary file directory [${ES_TMPDIR}] does not exist or is not accessible

### ISSUE THREAD

**Issue by rif** [elastic/elasticsearch#40812]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.0.0-rc2, Build: default/tar/f076a79/2019-04-02T17:20:40.380908Z, JVM: 12

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After upgrading from beta1 to rc1 I got this error message that is still showing up in rc2:
```bash
~/elasticsearch-7.0.0-rc2$ ES_PATH_CONF=/home/riddle/es/config bin/elasticsearch
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
ERROR: Temporary file directory [${ES_TMPDIR}] does not exist or is not accessible
```
Meanwhile just switching directory to beta1 the same commoand above runs fine. So I can run beta1 but not rc1 or rc2.

I tried creating a /tmp/es directory and exporting ES_TMPDIR=/tmp/es but it did not help.

**Steps to reproduce**:

 1. Download rc2, extract and cd into elasticsearch-7.0.0-rc2 (the issue appeared since rc1)
 2. Execute ES_PATH_CONF=/home/riddle/es/config bin/elasticsearch toi get the error
 3. CD back top beta2 to have es start successfuly

**Provide logs (if relevant)**:
ERROR: Temporary file directory [${ES_TMPDIR}] does not exist or is not accessible

**Comment by jasontedor** [comment]
Thanks for the report. This was caused by a commit that was intended to be reverted from the 7.0.0 branch but was not. That commit has now been reverted in 11357bbee48fa45897f8450f760045d5f9ea0c62.
