### ISSUE TITLE
Repository name with commas can't be retrieved

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#40817]
Add a repository with commas in name:

```
POST /_snapshot/test,with,comma
{
  "type" : "fs",
  "settings" : {
    "location" : "/tmp/es-backups"
  }
}
```

Attempting to retrieve information about this repository returns an error:
```
 GET /_snapshot/test,with,comma
```
or encoded
```
 GET /_snapshot/test%2Cwith%2Ccomma
```
returns
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "repository_missing_exception",
        "reason" : "[test] missing"
      }
    ],
    "type" : "repository_missing_exception",
    "reason" : "[test] missing"
  },
  "status" : 404
}
```

Could we disallow commas in repository name to prevent this from happening?

**Comment by ywelsch** [comment]
> Could we disallow commas in repository name to prevent this from happening?

yes, we can put some naming restrictions in place.
