### ISSUE TITLE
SQL: document the limitations around parsing

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#40836]
When https://github.com/elastic/elasticsearch/pull/33902 has been merged, a limit has been added in the parser to prevent lengthy complex queries to generate a StackOverflowError. This means that not all SQL queries will work in ES SQL.
This issue is proposing to document this limit in the [Limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-limitations.html) page.

**Comment by matriv** [comment]
This is closed as part of #41787.
@astefan any objections?
