### ISSUE TITLE
Ranking Evaluation API: Support for getting specification or ratings from other index

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#40865]
Summarizing and combining some ideas from #20439 and #30839 since they seem related:

There are requests to load either the ranking evaluation specification (either including the document ratings or not) from an auxilliary index instead of having to specify them in the request (e.g. similar to what the Terms Filter supports with the "lookup" mode).

* possible advantages: reducing complexity of the request, persist the specification, reducing network overhead
* potential disadvantages: might create unwanted dependency to some sort of index format, including potential bwc issues with previuos index format. Also "spawning" internal requests inside the cluster (like the Terms Query lookup mechanism) complicate the execution model

Additional extension of this idea from #30839: Provide some means to use queries to collect certain document and automatically attach a rating to it.
Example:

```
    {
       "ratings":[
          {
             "query":{
                "more_like_this":{
                   "fields":[ "title", "description" ],
                   "like":[{ "_index":"my_index",  "_type":"doc", "_id":"doc2"}]
                }
             },
             "rating":3
          }
       ]
    } 
```

Some thoughts on the later: While this looks neat, it opens several questions around data quality

* How sure am I that the documents a query fetches are really of low/high quality?
* How much bias does this introduce into my gold standard that I evaluate against? 
* Does this create bad feedback loops because sampling data that I'm sure has a certain "quality" and then tuning the rest of my search towards it will probably 
skew the resulting system towards these cases? )
* questions around more complexity in the execution model like with the above

**Comment by javanna** [comment]
There are no concrete plans to work on this issue. Closing.
