### ISSUE TITLE
Expose license expiration fields in GET _license API response

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#40872]
We are working towards using Metricbeat to collect Elasticsearch monitoring information instead of Elasticsearch collecting this internally (as has traditionally been the case).

One of the pieces of monitoring information that is collected is a cluster's license. This information is indexed in `type: cluster_stats` documents in `.monitoring-es-*` indices, under the `license` field.

When using internal collection the `ClusterStatsCollector` generates this license field in the monitoring doc by calling `license.toInnerXContent()`:

https://github.com/elastic/elasticsearch/blob/cd8dd04103ec0bb8fcbbc6e39e9c8a679175b29a/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/collector/cluster/ClusterStatsMonitoringDoc.java#L143

This method adds `expiry_date` and `expiry_date_in_millis` fields:

https://github.com/elastic/elasticsearch/blob/cd8dd04103ec0bb8fcbbc6e39e9c8a679175b29a/x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java#L404

As such, these two fields get indexed under the `license` field in `.monitoring-es-*` docs with `type: cluster_stats`.

However, when using Metricbeat collection, Metricbeat calls the `GET _license` API. This API currently doesn't expose the `expiry_date` and `expiry_date_in_millis` fields. As a result Metricbeat cannot collect these fields and index them into `.monitoring-es-*` documents of `type: cluster_stats`.

**Comment by ycombinator** [comment]
Hey @jkakavas any updates on this enhancement? Thanks!

**Comment by jkakavas** [comment]
No ,not really. I hadn't realized this is urgent , is this blocking some other work?

**Comment by cachedout** [comment]
@jkakavas Since @ycombinator isn't online right now I'll jump in. :) We need this merged in order to get the Stack Monitoring parity tests passing again.

**Comment by tvernum** [comment]
@jkakavas is out for a few days, I'll get a PR up for this.

**Comment by tvernum** [comment]
@ycombinator @cachedout 
There seems to be a misunderstanding here. The `GET /_license` API already includes an expiry field _unless_ the license is non-expiring (auto generated basic license).
I don't think there's anything we need to do for this.
