### ISSUE TITLE
`cluster_block_exception` should contain the read-only index name

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#40870]
**Elasticsearch version**: `Version: 7.0.0-rc2, Build: default/tar/7e5c520/2019-04-01T00:56:38.137034Z, JVM: 12`

**JVM version**: 
``` text
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**OS version**: `Darwin MacBook-Pro.localdomain 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

**Description of the problem including expected versus actual behavior**: If the `.security` index is read-only, the application privileges API response does not identify the problematic index name in the response.

**Request**
``` json
PUT /_security/privilege/
{
  "myapp": {
    "read": {
      "actions": [
        "data:read/*",
        "action:login"
      ],
      "metadata": {
        "description": "Read access to myapp"
      }
    }
  }
}
```
**Response**
``` json
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
  },
  "status": 403
}
```
This can be especially confusing for things like kibana logs:

`{"type":"log","@timestamp":"2019-03-23T02:01:15Z","tags":["security","error"],"pid":28144,"message":"Error registering Kibana Privileges with Elasticsearch for kibana-.kibana: [cluster_block_exception] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];, with { suppressed={ 0={ type=\"cluster_block_exception\" & reason=\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\" } & 1={ type=\"cluster_block_exception\" & reason=\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\" } & 2={ type=\"cluster_block_exception\" & reason=\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\" } } }"}`

**Steps to reproduce**:
 1. Set `.security` index to read only
    ``` json
    PUT .security/_settings
    {
        "index": {
        "blocks": {
            "read_only_allow_delete": "true"
            }
        }
    }
    ```
 2. Issue the `_security/privilege/` Request from above, and observe the response

**Comment by ielatif** [comment]
I want to pick up this please. Any suggestions on where to begin to make a fix ? A class entry point would be nice.

**Comment by codebird** [comment]
@ielatif I am on it. I still need to make sure all tests are good.

**Comment by ielatif** [comment]
thx @codebird I will look into your code to see how you fix it.

**Comment by megakoresh** [comment]
@jpcarey Sorry to post on closed issue, but if this happens on security index, there is seemingly no way to revert it - even elastic superuser is not authorized to edit the settings (presumably because authorizing it requires some write - maybe audit). So since this happened to us now, how do I reset the flag?

**Comment by jasontedor** [comment]
@megakoresh Can you open a topic on the [forums](https://discuss.elastic.co). As you seem aware, closed issues are not particularly effective for getting help, and in general we don't use GitHub for troubleshooting. If there is a verified bug here, we could open an issue later, but we'd prefer to try to help you on the forums.
