### ISSUE TITLE
In hierarchical documents, under certain scenarios, snippets for descendant documents don't turn up

### ISSUE THREAD

**Issue by kowndinyav** [elastic/elasticsearch#40882]
Once the issue is closed, comments are not heard. So creating a new issue for - https://github.com/elastic/elasticsearch/issues/40572

Thanks @jimczi for the query. With this I could get comments and replies as expected but I have few queries.

When I first time wrote the query, I did not have empty "inner_hits" fragment. When reply documents were not turning up in highlights section, it was a guess work to add the empty inner_hits as it was not clear from documentation how to resolve this. So, why is it required to add an additional dummy inner_hits for reply documents to turn-up?

Also, the clash that you are referring to is between two different "match" sections inside "should". One match is for matching documents for comment fields and the other one is matching reply fields. As an end user of elastic search, my expectation was that it should have worked without the additional inner_hits. Is this some implementation issue that is addressed in 5.1+ releases already?

For me the issue with adding a random name for inner_hits is that it breaks certain assumptions that we make while parsing the response. Essentially we go by type name.

**Comment by jimczi** [comment]
> Once the issue is closed, comments are not heard.

I replied in the original issue. If you have any further questions please open a topic in the [discuss forum](https://discuss.elastic.co/c/elasticsearch).
