### ISSUE TITLE
match_phrase_prefix NOT working as expected for other languages

### ISSUE THREAD

**Issue by kasiselvamk** [elastic/elasticsearch#40907]
**Elasticsearch version** (`bin/elasticsearch --version`): latest version

**Plugins installed**: [NA]

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system): ubuntu-latest

**Description of the problem including expected versus actual behavior**:

match_phrase_prefix NOT working as expected for other languages
when in insert below words;
 "word" : "க்ஷுத்ரஸ்வாஸம்"
 "word" : "க்ஷேத்திரம்"
"word" : "க்ஷேமதண்டுலம்"
**and try to search with character "க்" it is returning above word's --> which is not expected.
Please follow below easy step to reproduce,
please help on how to resolve this issue.....**
example:-
"க்ஷேத்திரம்" -->unicode rep.
க
்
ஷ
ே
த
்
த
ி
ர
ம
்
**Steps to reproduce**:

**Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.**

 1. create index as given.
 2.insert data 
 3.run search 

 1. create index as given.

PUT /tamil_example
{
  "settings": {
    "analysis": {
      "filter": {
        "tamil_stop": {
          "type": "stop",
          "stopwords": "_none_"
        },
        "tamil_keywords": {
          "type": "keyword_marker",
          "keywords": []
        },
        "tamil_stemmer": {
          "type": "stemmer",
          "language": "minimal_english"
        }
      },
      "analyzer": {
        "tamil_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "decimal_digit",
            "tamil_keywords",
            "indic_normalization",
            "tamil_stop",
            "tamil_stemmer"
          ]
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "word": {
          "type": "text",
          "analyzer": "tamil_analyzer"
        }
      }
    }
  }
}

 2.insert data 

PUT tamil_example/_doc/1
{
       "word" : "க்ஷுத்ரஸ்வாஸம்"
}
PUT tamil_example/_doc/2
{
     "word" : "க்ஷேத்திரம்"
}
PUT tamil_example/_doc/3
{
    "word" : "க்ஷேமதண்டுலம்"
}

 3.run search :-
GET tamil_example/_search
{
  "query": {
    "match_phrase_prefix": {
      "word": "க்"
    }
  }
}
Out put ------> Below output is NOT expected., it should return empty search.
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 0.2876821,
    "hits" : [
      {
        "_index" : "tamil_example",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 0.2876821,
        "_source" : {
          "word" : "க்ஷேத்திரம்"
        }
      },
      {
        "_index" : "tamil_example",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 0.2876821,
        "_source" : {
          "word" : "க்ஷுத்ரஸ்வாஸம்"
        }
      },
      {
        "_index" : "tamil_example",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 0.2876821,
        "_source" : {
          "word" : "க்ஷேமதண்டுலம்"
        }
      }
    ]
  }
}

**Provide logs (if relevant)**:

**Comment by kasiselvamk** [comment]
can some one help on this above issue..

**Comment by jimczi** [comment]
@kasiselvamk , this is the expected behavior. `க்ஷு` is a grapheme composed of four unicode points: `க`,  ்,  `ஷ`, `ு`. This unicode points are encoded in utf8 and indexed as is so a prefix query that starts with `க` will match a term like `க்ஷு`. Graphemes are composed of multiple characters (codepoint) and the boundary between other graphemes depends on the rules defined for the language. The icu library can detect grapheme boundaries but I don't think there is a way to normalize these inputs into an encoding that would separate graphemes. I wonder if we could have an  `edge_ngram` filter that works at the grapheme level (identify graphemes in a term) but such filter would belong to Lucene, probably in the icu module. I also wonder why do you think that this is an issue, a prefix query with a single character in tamil is ambiguous so you could maybe allow prefix queries only when there are at least 2 or 3 characters in the query ?

**Comment by kasiselvamk** [comment]
@jimczi , Thanks for your explanation it helps me understand the data/this is more likely the behavior. let me try using edge_ngram tokenizer .
i need this, to search words starring with given character (ex. `க்ஷு`,...)

Can you advice any better way to do this search other than `edge_ngram`

**Comment by jimczi** [comment]
I thought that the ICU character break iterator would recognize `க்ஷு` as a grapheme but I was wrong. The default UAX-29 that ICU implements does not recognize this extended grapheme so the only solution is to write custom rules for the tamil language. I am not aware of any resource that exposes this extended rules but it probably exists somewhere if you can search in tamil directly ;). `edge_ngram` will have the same problem so this is not a solution for your issue which in my opinion requires a special plugin to extend break iterator rules to recognize this extended characters.

**Comment by kasiselvamk** [comment]
@jimczi , There is issue in ICU library for such characters , i tried below code to print boundary's
using `ICU4J v 64.1`(which supports `Unicode v 12.0` )

import com.ibm.icu.text.BreakIterator;
import com.ibm.icu.util.ULocale;
public class ICU4JExample {
	 public static void main(String args[]) {
		  ULocale uL = new ULocale(**"ta_IN"**);
	          String stringToExamine =   "க்ஷேத்திரம்";
	          BreakIterator boundary = BreakIterator.getCharacterInstance(uL);
	          boundary.setText(stringToExamine);
	          boundary = BreakIterator.getCharacterInstance(uL);
	          boundary.setText(stringToExamine);
	          int start = boundary.first();
			  for (int end = boundary.next();
	                  end != BreakIterator.DONE;
	                  start = end, end = boundary.next()) {
					System.out.println(stringToExamine.substring(start,end));
	             }
	 }
}
output:-
`க்`
`ஷே`
`த்`
`தி`
`ர`
`ம்`

Now got the issue & where to fix it. Let me report to icu; 
http://site.icu-project.org/bugs/
& try to keep posting.
Thank you.

**Comment by kasiselvamk** [comment]
created an incident with icu; https://unicode-org.atlassian.net/browse/ICU-20557

**Comment by jimczi** [comment]
thanks @kasiselvamk  , the behavior described for the match phrase query is expected so I hope you don't mind if I close this issue. Please open a new topic in the discuss [forum](https://discuss.elastic.co/c/elasticsearch) and put the link here if you have further questions.
