### ISSUE TITLE
Azure Repo settings issue in 7.0 upgrade

### ISSUE THREAD

**Issue by lgwapnitsky** [elastic/elasticsearch#40911]
Conversation started in forums [here](https://discuss.elastic.co/t/azure-repo-settings-issue-in-7-0-upgrade/175456/2)

I'm running Elastic Stack 6.7.1 and per Kibana's 7.0 Upgrade Assistant ( Management -> 7.0 Upgrade Assistant ), I'm being told that Azure Repository settings have changed, but my config files have none of the specific entries mentioned in the documentation 2. Granted, this is showing up as a warning, so I'm not sure if I can proceed or not.

![image](https://user-images.githubusercontent.com/647444/55652315-27371b80-57b9-11e9-99a5-7d2a739ab14d.png)

Nothing in config file, but have established (and successfully used) the following:

```
bin/elasticsearch-keystore add azure.client.default.account
bin/elasticsearch-keystore add azure.client.default.key

```

**Comment by original-brownbear** [comment]
@lgwapnitsky did you check that you don't have `cloud.azure.storage.` (for your key and account) settings for these nodes in the keystore maybe?

**Comment by original-brownbear** [comment]
I'm closing this one since I didn't hear back from you @lgwapnitsky, but please feel free to reopen if still relevant.
