### ISSUE TITLE
Low level REST client marks arbitrary node as dead when the connection pool is exhausted

### ISSUE THREAD

**Issue by amirhadadi** [elastic/elasticsearch#40925]
**Elasticsearch version** 6.3.2

**Plugins installed**: []

**JVM version**: 1.8.144

**OS version**: Linux 3.13.0-88-generic #135-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

When `HttpAsyncClientBuilder::maxConnTotal` is exceeded, a leasing request is placed for a connection by `AbstractNIOConnPool` with a deadline derived from `HttpAsyncClientBuilder::connectionRequestTimeout`. If the deadline is reached, a TimeoutException is propagated to the REST client reaching the `failed(Exception failure)` callback in `RestClient::performRequestAsync` which marks the node as dead.
However, the failure is a result of the connection pool in its entirety being exhausted and not the node itself having any issue.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
