### ISSUE TITLE
Phonetic plugin seem's to skip token and return incorrect offset

### ISSUE THREAD

**Issue by scandinave** [elastic/elasticsearch#40924]
****Elasticsearch version** (`bin/elasticsearch --version`):**

6.7
****Plugins installed**: []**

analysis-icu
analysis-phonetic
**JVM version** (`java -version`):

Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

****OS version** (`uname -a` if on a Unix-like system):**

Debian 9.8

****Description of the problem including expected versus actual behavior**:**

I send a corpus of word to analyse by elasticsearch. ELK return an array of token two by two. The phoneme and the original token. Both should have the same offset. I'm my case, at some point, this is not the case. For example, this is a result I obtains : 

```
{
        "token": "F",
        "start_offset": 48678,
        "end_offset": 48679,
        "type": "<ALPHANUM>",
        "position": 9115
    },
    {
        "token": "f",
        "start_offset": 48678,
        "end_offset": 48679,
        "type": "<ALPHANUM>",
        "position": 9115
    },
    {
        "token": "a's",
        "start_offset": 48680,
        "end_offset": 48683,
        "type": "<ALPHANUM>",
        "position": 9116
    },
    {
        "token": "W",
        "start_offset": 48685,
        "end_offset": 48687,
        "type": "<ALPHANUM>",
        "position": 9117
    },
    {
        "token": "we",
        "start_offset": 48685,
        "end_offset": 48687,
        "type": "<ALPHANUM>",
        "position": 9117
    }
```

We clearly see that no phoneme is generated for `a's` token

This is the list of all words that cause this problem in my set with nysiis encoder: 

- a's
- aus
- ash
- az
- awos

And with defaut metaphone : 
- why
- 1a
- h96
- h2o
- 4w
- 17w
- 345ooo
- wwii
- w03
- yyy
- y12
- 66a
- w5655
- 050.00.0w
- 44w
- 800þ1000
- w03000.0

****Steps to reproduce**:**

 1. The mapping i use in elk
```
PUT phonetic_sample
{
    "settings": {
        "index": {
            "analysis": {
                "filter": {
                    "ban_number": {
                        "mode": "include",
                        "type": "keep_types",
                        "types": [
                            "<ALPHANUM>"
                        ]
                    },
                    "my_phonetic": {
                        "replace": "false",
                        "type": "phonetic",
                        "encoder": "nysiis"
                    },
                    "english_stop": {
                        "type": "stop",
                        "stopwords": "_english_"
                    }
                },
                "analyzer": {
                    "my_analyzer": {
                        "filter": [
                            "lowercase",
                            "english_stop",
                            "ban_number",
                            "my_phonetic"
                        ],
                        "tokenizer": "standard"
                    }
                }
            }
        }
    }
```
 2. The query i make
```
GET phonetic_sample/_analyze
{
     "analyzer": "my_analyzer",
     "text": "a's aus ass ash az"
}
```
We can see no phoneme is produce. No error. Just original token return. Did i missed something in the utilisation of this plugin? Or returning this is a normal behavior in case the encoder can not process the token?

**Comment by romseygeek** [comment]
It looks as though this may be an error in the commons-codec NYSIIS implementation.  According to this page (http://www.dropby.com/NYSIIS.html), `AUS` should be converted to `A`; however, the Java code as implemented here (https://github.com/apache/commons-codec/blob/master/src/main/java/org/apache/commons/codec/language/Nysiis.java) seems to miss the last step of the algorithm, 'Add original first character of name as first character of key'.

The lucene Phonetic filter returns the original token if the encoder returns an empty string, which is why you're getting those back.  I think your best bet is probably to open an issue on commons-codec.

**Comment by scandinave** [comment]
Maybe, but i have also this problem with metaphone algorithme.

**Comment by javanna** [comment]
Closing this as there is no evidence that this needs to be addressed in Elasticsearch. Please add comments if you have more info or believe this should stay open.
