### ISSUE TITLE
Array Datatype with `"index_options": "offsets"` and third-party analyzer(both ik and hanlp) make highlighting dislocated

### ISSUE THREAD

**Issue by Voleking** [elastic/elasticsearch#40922]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 6.6.1, Build: default/tar/1fd8f69/2019-02-13T17:10:04.160291Z, JVM: 11.0.1

**Plugins installed**: [elasticsearch-analysis-ik-6.6.1, elasticsearch-analysis-hanlp-6.6.1]

**JVM version** (`java -version`):
bash: java: command not found?
Dockerfile
```
FROM elasticsearch:6.6.1

ENV VERSION 6.6.1
RUN bin/elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v$VERSION/elasticsearch-analysis-ik-$VERSION.zip
RUN bin/elasticsearch-plugin install -b https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v$VERSION/elasticsearch-analysis-hanlp-$VERSION.zip
```

**OS version** (`uname -a` if on a Unix-like system):
Linux 0273da61aef4 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Array Datatype with `"index_options": "offsets"` and third-party analyzer(both ik and hanlp) make highlighting dislocated.

**Steps to reproduce**:

 1. `DELETE my_index`
 2. 
```
PUT my_index
{
  "mappings": {
    "fulltext": {
      "properties": {
        "text": {
          "type": "text",
          "index_options": "offsets",
          "analyzer": "ik_smart"
        }
      }
    }
  }
}
```
 3.
```
POST my_index/fulltext/1
{
  "text": [
    "蒋介石晚年标准造像，供报刊在节庆期间与重要场合悬挂使用。",
    "蒋氏去台后，晚年很少穿军装，此幅照片上的蒋身佩勋章，仅为节日礼仪。"
  ]
}
```
4. 
```
POST my_index/fulltext/_search
{
  "query": { 
    "query_string": {
      "query": "节日"
    }
  }, 
  "highlight": {
    "fields": {
      "*": {}
    },
    "require_field_match": "false"
  }
}
```

result:
```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.2876821,
    "hits" : [
      {
        "_index" : "my_index",
        "_type" : "fulltext",
        "_id" : "1",
        "_score" : 0.2876821,
        "_source" : {
          "text" : [
            "蒋介石晚年标准造像，供报刊在节庆期间与重要场合悬挂使用。",
            "蒋氏去台后，晚年很少穿军装，此幅照片上的蒋身佩勋章，仅为节日礼仪。"
          ]
        },
        "highlight" : {
          "text" : [
            "蒋氏去台后，晚年很少穿军装，此幅照片上的蒋身佩勋章，仅<em>为节</em>日礼仪。"
          ]
        }
      }
    ]
  }
}
```
excepted:
```
...
"highlight" : {
          "text" : [
            "蒋氏去台后，晚年很少穿军装，此幅照片上的蒋身佩勋章，仅为<em>节日</em>礼仪。"
          ]
}
...
```

**Comment by Voleking** [comment]
Well, seems like third-party analyzer issue https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/24, any help is welcome.

Since it is a plugin issue, feel free to close it.

**Comment by Voleking** [comment]
看了下，ik 的 offset 错在最末尾的词或者标点等没有出现在分词结果中的时候, offset 的更新操作被忽略

**Comment by jimczi** [comment]
Hi @Voleking , the issue seemed to be in the non-official plugins that you installed so I am going to close this issue. Fee free to reopen if the investigation in https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/24 reveals a bug in Elasticsearch.
