### ISSUE TITLE
repository-s3 fails with current Minio versions

### ISSUE THREAD

**Issue by stefan-as** [elastic/elasticsearch#40968]
**Elasticsearch version**
```
Package: elasticsearch
Version: 6.7.1
```

**Plugins installed**:
repository-s3

**JVM version** (`java -version`):
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
S3-Snapshots against a current Minio S3 server does not work any longer.

**Steps to reproduce**:

 1. Upgrade Minio S3 server to RELEASE.2019-04-04T18-31-46Z

**Provide logs (if relevant)**:
```
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>master.dat</Key><BucketName>tests-u7qDIFZFQoWRbWAvjPXzLA</BucketName>
  <Resource>/tests-u7qDIFZFQoWRbWAvjPXzLA/master.dat</Resource><RequestId>159385F93FA0AA48</RequestId><HostId>738461e2-77c5-4f66-a155-848be6c5f0b3</HostId></Error>
```

There is also a corresponding Minio bug report claiming that there are Bucket names in use that are not valid: https://github.com/minio/minio/issues/7497

**Comment by DaveCTurner** [comment]
I tried running the test suite against the quoted version of Minio and saw no failures:

```diff
diff --git a/plugins/repository-s3/build.gradle b/plugins/repository-s3/build.gradle
index 37acbe0..5365595 100644
--- a/plugins/repository-s3/build.gradle
+++ b/plugins/repository-s3/build.gradle
@@ -142,7 +142,7 @@ if (useFixture) {
     outputs.file(minioDockerfile)
     doLast {
       minioDockerfile.parentFile.mkdirs()
-      minioDockerfile.text = "FROM minio/minio:RELEASE.2019-01-23T23-18-58Z\n" +
+      minioDockerfile.text = "FROM minio/minio:RELEASE.2019-04-04T18-31-46Z\n" +
               "RUN mkdir -p /minio/data/${s3PermanentBucket}\n" +
               "ENV MINIO_ACCESS_KEY ${s3PermanentAccessKey}\n" +
               "ENV MINIO_SECRET_KEY ${s3PermanentSecretKey}"
```

The cause of the error is unclear from the linked issue, but seems to be saying that this bucket name is invalid. I don't think there's any action to be taken at the Elasticsearch end since Elasticsearch passes the bucket name straight through to the SDK.

**Comment by DaveCTurner** [comment]
I also tried running the test suite using the bucket name `tests-u7qDIFZFQoWRbWAvjPXzLA` and it fails on Minio version `2019-01-23T23-18-58Z` so I don't think this is a regression.

**Comment by stefan-as** [comment]
Issues was solved by minio https://github.com/minio/minio/issues/7497#issuecomment-489984290
