### ISSUE TITLE
elasticsearch.exceptions.ConnectionTimeout with Flask

### ISSUE THREAD

**Issue by loicquirion** [elastic/elasticsearch#40982]
Hi guys, I'm getting this error (elasticsearch.exceptions.ConnectionTimeout) after writing a simple search engine using Flask and Elasticsearch.

Can someone help me?

Here's my code from my app.py file:

```
from flask import Flask, render_template, request
from elasticsearch import Elasticsearch

app = Flask(__name__)
es = Elasticsearch(host='localhost', port=9200)


@app.route('/')
def home():
    return render_template('search.html')

@app.route('/search/results', methods=['GET', 'POST'])
def search_request():
    search_term = request.form["input"]
    res = es.search(
        index="scrape-codif",
        size=20,
        request_timeout=30,
        body={
            "query": {
                "multi_match" : {
                    "query": search_term,
                    "fields": [
                        "name",
                        "description",
                        "price",
                        "tags"
                    ]
                }
            }
        }
    )
    return render_template('results.html', res=res)


if __name__ == '__main__':
    app.secret_key = '************'
    app.run(debug=True, host='localhost', port=5000)

```

Thanks a lot in advance! :)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
