### ISSUE TITLE
ES 6.6.1 Upgrade. MetaDataIndexUpgradeService doesn't identify version of the index correctly

### ISSUE THREAD

**Issue by barsen** [elastic/elasticsearch#40987]
We suspect that MetaDataIndexUpgradeService incorrectly identifies version of the index in upgrade check.
It looks for only on meta data field: creationVersion

We have the index that was originally created in version 2.1 then reindexed to 5.1 when we look at index settings it is indicated:
{
  "syncrofy.index" : {
    "settings" : {
      "index" : {
        "creation_date" : "1461881062889",
        "analysis" : {
          "analyzer" : {
            "default" : {
              "type" : "whitespace"
            }
          }
        },
        "number_of_shards" : "10",
        "number_of_replicas" : "3",
        "uuid" : "cWWK7BwiRD2RlMm1C1xChA",
        "version" : {
          "created" : "2010199",
          "upgraded" : "5040099"
        }
      }
    }
  }

When I check version of all underlying  segments and shards I see that they have Lucene version 6.6.1 which is what ES 5 was using.

As far as I understand this index should not prevent us from upgrading to version 6.6 but it does right now.

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by ywelsch** [comment]
Sorry for the late reply here, but it sounds as if you copied over the `index.version.created` setting from the original index before reindexing? ES uses that field to determine if an upgrade is possible.
