### ISSUE TITLE
Self-intersecting shape reports strange error

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#40998]
In 6.6.2 I tried the following commands to index a shape with a hole that touches its edge:

```
PUT /i
{
  "mappings": {
    "_doc": {
      "properties": {
        "f": {
          "type": "geo_shape"
        }
      }
    }
  }
}

POST /i/_doc
{
  "f": {
    "coordinates": [
      [
        [
          0,
          0
        ],
        [
          2,
          0
        ],
        [
          1,
          1
        ],
        [
          1,
          2
        ],
        [
          2,
          0
        ],
        [
          2,
          3
        ],
        [
          0,
          3
        ],
        [
          0,
          0
        ]
      ]
    ],
    "type": "Polygon"
  }
}
```

This yielded the following response:

```
# 400 Bad Request
# {
#   "status": 400,
#   "error": {
#     "caused_by": {
#       "reason": "at least 4 polygon points required",
#       "type": "illegal_argument_exception"
#     },
#     "reason": "failed to parse field [f] of type [geo_shape]",
#     "root_cause": [
#       {
#         "reason": "failed to parse field [f] of type [geo_shape]",
#         "type": "mapper_parsing_exception"
#       }
#     ],
#     "type": "mapper_parsing_exception"
#   }
# }
```

I think this shape should indeed be rejected since it is self-intersecting at `[2,0]`, but the exception message seems wrong since there are enough points.

~I tried the same commands in 7.0.0-rc1 and this shape was accepted, which I also think shouldn't be the case.~ (edit, not true, see below)

The shape in question looks like this:

<img width="138" alt="Screenshot 2019-04-09 at 09 38 22" src="https://user-images.githubusercontent.com/5058284/55786109-89d73280-5aab-11e9-9729-886964484eab.png">

Derived from the issue reported here: https://discuss.elastic.co/t/failed-to-create-valid-geo-shape/175975

**Comment by DaveCTurner** [comment]
My test against 7.0.0-rc1 was flawed, sorry. I tried again and it was rejected as expected, but I got a different rejection message:

```
# 400 Bad Request
# {
#   "status": 400,
#   "error": {
#     "caused_by": {
#       "reason": "first and last points of the linear ring must be the same (it must close itself): lats[0]=0.0 lats[2]=3.0",
#       "type": "illegal_argument_exception"
#     },
#     "reason": "failed to parse field [f] of type [geo_shape]",
#     "root_cause": [
#       {
#         "reason": "failed to parse field [f] of type [geo_shape]",
#         "type": "mapper_parsing_exception"
#       }
#     ],
#     "type": "mapper_parsing_exception"
#   }
# }
```

**Comment by iverase** [comment]
This error is due to the polygon hitting this part of the code which is introduced to handle complex polygons over the date line:

https://github.com/elastic/elasticsearch/blob/68149b6058a720ec891974e8a6982c5e480fb9f1/server/src/main/java/org/elasticsearch/common/geo/builders/PolygonBuilder.java#L439

The logic tries to split the polygon and generates an invalid one (first and last point are not equal). In this case there is not enough points and we get the error above, in other cases error looks like:

```
 IllegalArgumentException[first and last points of the linear ring must be the same (it must close itself)
```

I wonder if we just need to close the generated polygon.
