### ISSUE TITLE
Scripted Metrics Aggregation failed after the first request

### ISSUE THREAD

**Issue by Daemonyz** [elastic/elasticsearch#40996]
**Describe the feature**: Request failed using the scripted metrics, often sucess for the first time and failed receiving response for latter requests.

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.10

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. I want to do the aggregation, and the metric aggregation is to merge the text fields into a new text field.
 2. I use the init_script, map_script, reduct_script as the scripted metrics.
 3. Often the first request can response but failed for the latter term query.

**Provide logs (if relevant)**:

**Comment by polyfractal** [comment]
@Daemonyz Can you provide the error/exception and the init/map/reduce scripts?  Without more information there isn't much we can do to help. :)

I'm not sure of your use-case, but if you're just trying to concatenate fields together into a single new field, the [terms aggregation supports scripting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script), which can be used to aggregate "combined keys"

**Comment by Daemonyz** [comment]
> @Daemonyz Can you provide the error/exception and the init/map/reduce scripts? Without more information there isn't much we can do to help. :)
> 
> I'm not sure of your use-case, but if you're just trying to concatenate fields together into a single new field, the [terms aggregation supports scripting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script), which can be used to aggregate "combined keys"

Thanks for your reply, I tried to change the heapsize in the jvm.option, from 4g to 12g, and then it works, the aggregation procedure can work with expectation efficiently.

What puzzles me is that, how will the heapsize config in jvm.options affect the performance of aggregation procedure? And are there any good suggestions about the config, except "as large as possible until 24G"?

**Comment by polyfractal** [comment]
In this case it depends on what your scripted agg is doing.  All the intermediate results are store in-memory, on the heap.  So if the aggregation is expensive, or is embedded deeply in an aggregation tree (e.g. the total search request generates many buckets) it adds up to a lot of temporary memory usage.

This is a general phenomenon that other aggregations run into as well, not necessarily unique to scripted metric.  But it can be made worse since scripted metrics are user-defined, and there's nothing stopping you from doing something very expensive (maintaining large maps, etc).

**Comment by polyfractal** [comment]
I'm going to close this, since it appears to be a generic memory issue which isn't really related to the aggregation itself (just aggregation operation in general, and scripting).
