### ISSUE TITLE
ES JAVA API : select field1,field2,count(*) from table order by count(*)

### ISSUE THREAD

**Issue by pgm-rookie** [elastic/elasticsearch#41002]
My code is like below:

    SearchQuery searchQuery = queryBuilder.addAggregation(
    AggregationBuilders.terms("f1").field("field1").size(Integer.MAX_VALUE).subAggregation(
    AggregationBuilders.terms("f2").field("field2").size(Integer.MAX_VALUE))).build();
    AggregatedPage<AccessLog> aggPage = (AggregatedPage<AccessLog>) this.accessLogRepository.search(searchQuery);
    StringTerms agg = (StringTerms) aggPage.getAggregation("f1");
    //get datas
    List<StringTerms.Bucket> buckets = agg.getBuckets();
    if(!CollectionUtils.isEmpty(buckets)) {
        for(StringTerms.Bucket bucket : buckets){
            StringTerms an = (StringTerms)bucket.getAggregations().asMap().get("f2");
            List<StringTerms.Bucket> ans = an.getBuckets();
            if(!CollectionUtils.isEmpty(buckets)) {
                for(StringTerms.Bucket anBucket : ans){
                    UserActionRankListVO vo = new UserActionRankListVO();
                    vo.setActionName(anBucket.getKeyAsString());
                    vo.setCount((int)anBucket.getDocCount());
                    vo.setMobile(bucket.getKeyAsString());
                    list.add(vo);
                }
            }
        }
    }

I should get all data, add into list and then sort, like this:

    list.sort((v1, v2) -> v2.getCount() - v1.getCount());

How should i do using ES JAVA API , like "select field1,field2,count(*) from table order by count(*)" in mysql or oracle , thanks !

**Comment by jimczi** [comment]
Hi @pgm-rookie , please ask questions like these on the [discuss forums](https://discuss.elastic.co/c/elasticsearch), we use Github mainly for feature requests and verified bugs.
