### ISSUE TITLE
Prevent .kibana index to be restored from 5.x to 6.x to avoid RED Kibana

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#41017]
### Problem Description
`RestoreService` doesn't check for `.kibana` index being restored from a snapshot repository having `.kibana` on an incompatible version needing [migration](https://www.elastic.co/guide/en/kibana/current/migrating-6.0-index.html). As a result upon restore maybe accidentally, it causes the Kibana to go RED. If the cluster is already on 6.x it shouldn't let the restore of incompatible .kibana index to go through

**Comment by jasontedor** [comment]
As far as Elasticsearch is concerned, the `.kibana` index is an *external* index. It has no knowledge of the internal semantics of the .kibana index, and whether or not an index in a snapshot is safe to be restored into the current version or not. That is, for now, wholly determined by the user executing the restore.

**Comment by Bukhtawar** [comment]
@jasontedor  Do you think it makes sense to have a check on the mapping type in general for any index and throw a `warning` calling out future deprecation and functionality like `Kibana` which would most likely break on restore and maybe also add a `force` flag on such restores.

**Comment by cbuescher** [comment]
@Bukhtawar @jasontedor going through unlabeled issues atm, from the scope of the question I have a feeling this discussion is better suited for the Kibana repo (https://github.com/elastic/kibana/). Would you mind closing and reopen the issue there if you agree (and maybe cross-link this issue for our view of things)?

**Comment by jasontedor** [comment]
Ultimately I think the way to deal with this is through the notion of system indices which is currently in a brainstorming phase. The idea behind system indices is they are implemented behind the scenes as indices, but not exposed to users via the usual index APIs (index, search, snapshot/restore, etc.). Instead, for each system index there will be an associated plugin that exposes only the APIs necessary for that system index to serve its purpose. The .kibana index would be a system index, and there would be `kibana_system_index` plugin that dictates the APIs of the .kibana index, including the restore properties. That plugin can then validate on restore whether or not the index being restored matches any requirements the `kibana_system_index` needs to enforce (e.g., mapping version, etc.).
