### ISSUE TITLE
Merge FieldMapper and MappedFieldType

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#41058]
MappedFieldType had originally been split out of FieldMapper in order to work around problems that having multiple types in the same index introduced. Now that we introduced the guarantee that every index has at most one type, we could merge MappedFieldType and FieldMapper together.

**Comment by jpountz** [comment]
Both @javanna and @romseygeek are exploring features that wouldn't require doing anything at index time, they would only leverage `MappedFieldType` for search-time logic, so maybe we shouldn't merge actually?

**Comment by romseygeek** [comment]
I think we could still do some re-organising here.  For example, FieldMapper has the `parseCreateField` method on it which is used for indexing, while MappedFieldType has all the various `xxxQuery` methods on it, for searching - I think it might make sense for those to be the other way round?

**Comment by jtibshirani** [comment]
A note that `flattened` fields currently take advantage of the `FieldMapper`/ `MappedFieldType` distinction. We create a new `MappedFieldType` on-the-fly inside `FieldTypeLookup` to support searches on the subfields.

**Comment by romseygeek** [comment]
I opened a separate issue for the re-organisation: https://github.com/elastic/elasticsearch/issues/56814

I think we can close this one though?

**Comment by jtibshirani** [comment]
Closing in favor of #56814, feel free to reopen if you disagree!
