### ISSUE TITLE
Frequent OutOfMemoryErrors in Builds

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41061]
There seem to be a few instances of builds endings with OutOfMemoryErrors lately.

Some recent ones:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+artifactory/273/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3057/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/350/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/126/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-14.04&&immutable/99/console

Builds end with something like:
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
runbld>>> DURATION: 1798455ms
runbld>>> STDOUT: 102612179 bytes
runbld>>> STDERR: 0 bytes
runbld>>> WRAPPED PROCESS: FAILURE (1)
```

**Comment by cbuescher** [comment]
And another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3062/console

**Comment by cbuescher** [comment]
This one looks slightly different but I'll add it here to get a better overview of things:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+artifactory/283/console

```
* What went wrong:
Java heap space

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
runbld>>> DURATION: 2055497ms
runbld>>> STDOUT: 106231627 bytes
runbld>>> STDERR: 0 bytes
runbld>>> WRAPPED PROCESS: FAILURE (1)
```

**Comment by atorok** [comment]
I suspect that this is the Gradle client module that is running out of memory here no the daemon, because there's no demon crashed message. 
We  got a heap of 64M configured there via a Gradle upgrade in 530e1e389d4 . 
The new test runner might be creating more pressure, will try to increase it.

**Comment by cbuescher** [comment]
Also: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/1030/console

**Comment by polyfractal** [comment]
Two more: 

- a `Java heap space` failure on 7.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1008/
- a `OutOfMemoryError` on master: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3074

**Comment by jrodewig** [comment]
Another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/698/

**Comment by atorok** [comment]
Looking at some failures after #41031 were merged and seems no heapdump was produced which seems to confirm this is a problem on the client.

**Comment by danielmitterdorfer** [comment]
We see another instance of this in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-7&&immutable/113/console

It fails with:

```
Gradle Test Executor 54 finished executing tests.
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid32651.hprof ...
Heap dump file created [169289336 bytes in 1.669 secs]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

Inspecting the resulting heap dump we see almost all of the memory (124 out of 128MB) taken up by instances of `org.gradle.internal.logging.events.StyledTextOutputEvent` so to me this seems related to Gradle accumulating log events in the background.

**Comment by danielmitterdorfer** [comment]
There is also another instance of this failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-6/113/console. The assessment is identical to the failure above hence I'll omit the details.

**Comment by atorok** [comment]
Another failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3174/

**Comment by mark-vieira** [comment]
Certainly the way that test runners ship log output to the client has changed. It's not surprising the Gradle native daemon->client communication creates more garbage. I'm wondering if the recent change to remove `--info` will also help here. One side-effect of the Gradle test runner migration was that we ended up creating _a lot_ more test output.

**Comment by atorok** [comment]
Looking at build logs it looks like this stopped happening after the cleanup.
