### ISSUE TITLE
Query Terms Null or []

### ISSUE THREAD

**Issue by EliuFlorez** [elastic/elasticsearch#41097]
Hi guys, you know I have a problem with a query in "Terms" where the query is:

```
GET /user/_search
{
  "query": {
    "terms" : { 
      "user" : ["user-1"]
    }
  }
}
```
something so simple but it does not return anything. I put an example of index and response.

Mapper:
```
PUT /user/_doc/1
{
  "user" : "user-1"
}

PUT /user/_doc/2
{
  "user" : "user-2"
}

PUT /user/_doc/3
{
  "user" : "user-3"
}
```
Query Failed:
```
GET /user/_search
{
  "query": {
    "terms" : { 
      "user" : ["user-1"]
    }
  }
}
```
Respose Failed:
```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
When removing "-" from terms, the result is returned but I need it to be exact, since it will be used for location queries where it must be exact, because if only "california" is indicated, it can return results from the US and California. Mexico.

Query Success:
```
GET /user/_search
{
  "query": {
    "terms" : { 
      "user" : ["1"]
    }
  }
}
```
Response Success:
```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "user",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "user" : "user-1"
        }
      }
    ]
  }
}
```
I use Terms since you can specify several locations in the same query.
I hope you help me.
Greetings.

**Comment by dnhatn** [comment]
By default, a string is [tokenized](https://www.elastic.co/guide/en/elasticsearch/reference/current/analyzer.html) into terms using the standard analyzer. 

```
GET _analyze
{
  "text": "user-1"
}
```

```
{
  "tokens" : [
    {
      "token" : "user",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "<ALPHANUM>",
      "position" : 0
    },
    {
      "token" : "1",
      "start_offset" : 5,
      "end_offset" : 6,
      "type" : "<NUM>",
      "position" : 1
    }
  ]
}
```

If you want an exact match, you should the keyword analyzer instead.

```
GET _analyze
{
  "analyzer": "keyword", 
  "text": "user-1"
}
```

```
{
  "tokens" : [
    {
      "token" : "user-1",
      "start_offset" : 0,
      "end_offset" : 6,
      "type" : "word",
      "position" : 0
    }
  ]
}
```

----
Please be patient in waiting for responses to your question and refrain from pinging multiple times asking for a response or openning multiple topics for the same question. This is a community forum, it may take time for someone to reply to your question. For more information please refer to the [Community Code of Conduct](https://www.elastic.co/community/codeofconduct) specifically the section "Be patient".

Thanks very much for your interest in Elasticsearch.
