### ISSUE TITLE
Publish github releases (instead of just tags) - for notifications

### ISSUE THREAD

**Issue by security-feedi** [elastic/elasticsearch#41105]
Since I din't find a elasticsearch announce mailing list to get notified of new releases I use github's "watch releases" feature on this repo, but since the releases are just tagged and not declared as actual releases subscribers of that feature never actually get any notification (like with the elastic/beats repo).

Could you make make releases out of the tags in the future?

similar to
https://github.com/elastic/logstash/issues/10081

**Comment by jasontedor** [comment]
Thanks for the feedback, we will start doing this with our next set of releases. Feel free to subscribe to releases to receive notification of when that is. 😇
