### ISSUE TITLE
[ML] Find a way to include painless for tests

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#41109]
In the feature branch `feature-ml-data-frame-analytics` we were testing a bit of functionality that performs a reindex and uses painless to add a field. In order to test that we had to add 

```
testCompile project(':modules:lang-painless')
```

in `x-pack/plugin/ml/build.gradle`.

After merging master into the feature branch, the precommit task was failing with jar hell as painless depends on asm 5.1 but security and the featureAwareTask depend on asm 7.1.

Not being able to find a way around this I have temporarily removed that test in 0bf8ede18492c7a350eed1c29b8984fd95069ea1.

However, I would like to bring that test back if possible. For this I request help from @elastic/es-core-infra to sort the jar problems.

**Comment by tomcallahan** [comment]
Removing discuss label as it seems @dimitris-athanasiou already connected with @jasontedor on this one, but re-add or reach out if you need help!

**Comment by dimitris-athanasiou** [comment]
The suggestion of looking at how SQL dealt with a similar issue did not work in this case so I am still looking for help with this.

**Comment by droberts195** [comment]
It seems that SQL avoided the problem by not including the painless module in integration test clusters.  But the data frame analytics integration tests really need to make use of painless to accurately test what will be happening in production.

The clash only occurs in the precommit task, so if we were able to declare the dependency like:

```
testCompileButNotPrecommitCompile project(':modules:lang-painless')
```

then that would solve it.  But we don't know enough about the build system to know if something that achieves this effect is possible.

**Comment by atorok** [comment]
I'll take a look at the build side of this. Precommit should check the run-time behavior, it shouldn't be different, so something feels wrong.

**Comment by atorok** [comment]
It seems to me the build is correct on this one. We use not only different versions of but also different distributions of asm. Painless uses `org.ow2.asm:asm-debug-all:5.1` and  security uses `org.ow2.asm:asm:7.1` and the two do produce jar hell:
```
class: org.objectweb.asm.AnnotationVisitor
jar1: /home/alpar/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-debug-all/5.1/dde860d586960d55a87cd52c4fc1f5059c89cbc6/asm-debug-all-5.1.jar
jar2: /home/alpar/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/7.1/fa29aa438674ff19d5e1386d2c3527a0267f291e/asm-7.1.jar
```

I was under the impression that the same jar hell checks are ran in the test fw and startup, so @rjernst  why would this trigger only in precommit and are we find with that?  These don't seem to be shadowed. 

The jar hell can be silenced for the tests by excluding one or the other, e.x. to exclude asm from security: 
```
testCompile(project(path: xpackModule('security'), configuration: 'testArtifacts')) {
        exclude group: "org.ow2.asm"
}
```

**Comment by rjernst** [comment]
The problem is trying to include painless as a compile dependency. Why is that needed? There shouldn't be anything in the painless code that is needed directly; it should be used through the rest/transport api. There is no issue when starting the server because painless and ML are loaded in different classloaders, and can therefore have different versions of asm.

**Comment by jaymode** [comment]
Looking at the test in question shows that painless was added as a testCompile dependency so that painless and reindex could be used within an internal cluster, not an actual external test cluster. Could this test be converted to use an external cluster?

**Comment by dimitris-athanasiou** [comment]
@jaymode The test is mocking persistent task states that would otherwise be very time sensitive to reproduce in a normal cluster. Practically, those tests would be flakey all the time.

**Comment by rjernst** [comment]
Can the test be converted to a unit test? Having painless loaded in the same classloader as xpack will never work due to asm.

**Comment by dimitris-athanasiou** [comment]
The test would lose much of its effectiveness as a unit test.

I raised the issue to get help about how we could make the test work as is. If the answer is that it is not possible, it's fine, I'll see what we can do with the test.

But it feels wrong not to be able to test something so that precommit works.
The test runs successfully, it's just precommit that fails.

**Comment by atorok** [comment]
The test works because plugins get loading into different class-loaders but the jar hell in percommit doesn't make that distinction. Does the test use anything from security that needs asm, or do you need to test security in this context at all ?  If neither is the case, you could get around this by explicitly excluding asm from security.

**Comment by rjernst** [comment]
> The test works because plugins get loading into different class-loaders but the jar hell in percommit doesn't make that distinction.

Internal cluster tests (ie ESIntegTestCase) do not use different classloaders for plugins. The jarhell does matter, even for the tests, for the same reasons we have jarhell for production: we cannot trust which class is actually loaded if there are multiple of the same class on the classpath.

**Comment by atorok** [comment]
@rjernst how come the jar hell check didn't trigger when running the tests then ? I was under the impression that we run jar hell with the tests too

**Comment by rjernst** [comment]
It should have tripped at runtime, I would have to see a reproduction to understand why it didn't. You can verify my statements about plugins not being in different classloaders for ESIntegTestCase by looking at the Node protected constructor which takes "classpathPlugins".

**Comment by dimitris-athanasiou** [comment]
We've moved a long way since this issue was raised. I don't think this is relevant any more.
