### ISSUE TITLE
[DOCS] Document setting eligibility for `elasticsearch-keystore add` and `elasticsearch-keystore add-file`

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#41113]
As of this writing, our [secure settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html) docs do not indicate that `elasticsearch-keystore add` and `elasticsearch-keystore add-file` should only be used for specific settings.

As a result, some users may assume that keystore can be used for any setting wished.

**Comment by debadair** [comment]
Closing as fixed. Secure settings page notes that only designated settings should be added to the keystore.
