### ISSUE TITLE
Add back _primary* search preferences

### ISSUE THREAD

**Issue by awick** [elastic/elasticsearch#41115]
We run large time based clusters with 1 primary and 1 replica on each node.   We liked the primary* search options so that no extra heap or disk cache is used when searching, only the primary is loaded.  With out the primary options, my assumption is now it is possible if multiple searches are done that multiple primary and replicas of every index could be loaded on every machine.  For those of us with low volume of search that search a large amount of data, this would cut our memory cache/heap in almost 1/2.

The "The cache-related benefits of these options can also be obtained using _only_nodes, _prefer_nodes, or a custom string value instead." from the online docs doesn't apply to us since every node has a shard for disk capacity and speed.

Am I thinking about this wrong?

**Comment by DaveCTurner** [comment]
This question is better suited for [the discussion forum](https://discuss.elastic.co/c/elasticsearch), so I hope you don't mind if I close it. Could you open a thread in the forum and link to it from here?

**Comment by awick** [comment]
@DaveCTurner Its a feature request, or those must be discussed first on the forum?

**Comment by awick** [comment]
https://discuss.elastic.co/t/add-back-primary-search-preferences/176598
