### ISSUE TITLE
Creating Index without type in Java throws ClassCastException

### ISSUE THREAD

**Issue by AlexKovalevich** [elastic/elasticsearch#41120]
**Bug report**
**Elasticsearch version** 7.0.0
**Plugins installed**: []
**JVM version** Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode):
**OS version** Windows 10 1809:
**Description of the problem including expected versus actual behavior**:
Creating index from from Java API using new ES 7 typeless schema throws ClassCastException.

**Steps to reproduce**:

```
Client esClient; //initialized as PreBuiltTRansportClient
String indexName = "dummyindex"; // any index name
String schema; //example taken from https://www.elastic.co/guide/en/elasticsearch/reference/master/dynamic.html

schema = "{\n" +
        "  \"mappings\": {\n" +
        "    \"dynamic\": false, \n" +
        "    \"properties\": {\n" +
        "      \"user\": { \n" +
        "        \"properties\": {\n" +
        "          \"name\": {\n" +
        "            \"type\": \"text\"\n" +
        "          },\n" +
        "          \"social_networks\": { \n" +
        "            \"dynamic\": true,\n" +
        "            \"properties\": {}\n" +
        "          }\n" +
        "        }\n" +
        "      }\n" +
        "    }\n" +
        "  }\n" +
        "}";


IndicesAdminClient indices = esClient.admin().indices();
indices.prepareCreate(indexName).setSource(schema , XContentType.JSON);

```

//throws 

```
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.util.Map (java.lang.Boolean and java.util.Map are in module java.base of loader 'bootstrap')

	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:383)
	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:367)
	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:338)
	at org.elasticsearch.action.admin.indices.create.CreateIndexRequestBuilder.setSource(CreateIndexRequestBuilder.java:191)
```

The reason is that 

```
org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java
line 383: mapping(entry1.getKey(), (Map<String, Object>) entry1.getValue());
```
tries to cast json entry1 to Map
however "dynamic": false gets returned as boolean False.

**Comment by dnhatn** [comment]
It's an example for the REST API, not the transport client. Transport client was deprecated and replaced by high-level rest client.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thanks very much for your interest in Elasticsearch.

**Comment by AlexKovalevich** [comment]
> It's an example for the REST API, not the transport client
Are you referring the whole example or the mapping example?

Is mapping client specific now?

**Comment by dadoonet** [comment]
See related discussion at https://github.com/elastic/elasticsearch/issues/40897
