### ISSUE TITLE
NoSuchMethodError for client.updateByQuery(...)

### ISSUE THREAD

**Issue by adityarar** [elastic/elasticsearch#41148]
**Elasticsearch version** (`6.7.1`):

**JVM version** (`1.8.0_121`):

**OS version** (`windows-7`):

**Description of the problem including expected versus actual behavior**:
While issuing a request to update by query using `RestHighLevelClient.updateByQuery(UpdateByQueryRequest, RequestOptions)`, I get the following error:

```
java.lang.NoSuchMethodError: org.elasticsearch.index.reindex.BulkByScrollResponse.fromXContent(Lorg/elasticsearch/common/xcontent/XContentParser;)Lorg/elasticsearch/index/reindex/BulkByScrollResponse;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1385)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1726)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:442)
	at org.elasticsearch.client.RestHighLevelClient.updateByQuery(RestHighLevelClient.java:556)
```

After searching around I found out that I might be using an older version of elastic-search. To confirm the above used versions, I placed the following dependencies as first entries in my `pom.xml` :

```
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>6.7.1</version>
        </dependency>
        <dependency>
		<groupId>org.elasticsearch.client</groupId>
		<artifactId>elasticsearch-rest-high-level-client</artifactId>
		<version>6.7.1</version><!--$NO-MVN-MAN-VER$ -->
	</dependency>
```

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

In your case, it looks as though you have compiled against one version of
elasticsearch, but are running with a different version on the classpath.

**Comment by adityarar** [comment]
Sure!! I have raised a question [here](https://discuss.elastic.co/t/nosuchmethoderror-for-client-updatebyquery/176647).
