### ISSUE TITLE
painless script not working for 6.7.0

### ISSUE THREAD

**Issue by HAK-CODE** [elastic/elasticsearch#41167]
**Describe the feature**:
Hi,
I am using painless in elasticsearch version 6.7 as an example shows how to pick up a value like
doc['field'].value. It was working great in version 6.4, now t not even picking up the field (returning null) while the field is there and I verified it by using expression.
Regards,
HAK

**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.0

**Description of the problem including expected versus actual behavior**:
Painless is not getting an existing field from the index while same example doc['filed'].value is working fine on 6.4. Expression is also working fine on 6.7.0.

**Steps to reproduce**:

 1. Use any numeric field from any index.
 2. Use language painless.
 3. Preview the result and than verify it same from language expression.

![using_painless](https://user-images.githubusercontent.com/16891410/56062831-2721b780-5d87-11e9-9382-df660b561dfc.png)
![using_expression](https://user-images.githubusercontent.com/16891410/56062830-26892100-5d87-11e9-9147-f8aba79144fc.png)

**Comment by merlinv** [comment]
+1 for the issue.
I got a similar error when executing painless scripting in a search query.
Type: "illegal_state_exception",
Reason: "A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!"
Although I checked all document and ensured they don't contain the null field, the error is kept showing.

**Comment by jdconrad** [comment]
Apologies for the delay.  Will look into this soon.

**Comment by jdconrad** [comment]
@HAK-CODE Are there any errors associated with the scripts you're running in your log files?

@merlinv You might be able to isolate the document that is causing issues by doing something like 

```if (doc['your_field_name'].size() == 0) throw new RuntimeException("" + doc['some_unique_identifier_field']```

**Comment by HAK-CODE** [comment]
i am not getting any error but no document were shows under my criteria
even though documents are there. i jad attached screenshots for reference.
Regards,
HAK

**Comment by HAK-CODE** [comment]
Hey,

I just signed the petition "James Frith: Investigation into bullying policy
at Broadoak High School Bury, Lancashire and GMP full investigation" and
wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/YSMvQRFzHw

Thanks!
Hammad

**Comment by jdconrad** [comment]
Closing this as I was unable to figure out how to reproduce this effectively.
