### ISSUE TITLE
create elasticsearch client throws netty illegalstateexception in server enviroment

### ISSUE THREAD

**Issue by dodolzg** [elastic/elasticsearch#41176]
The error info

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.transport.TransportClient]: Factory method 'elasticsearchClient' threw exception; nested exception is java.lang.IllegalStateException: availableProcessors is already set to [4], rejecting [4]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
        ... 112 more
Caused by: java.lang.IllegalStateException: availableProcessors is already set to [4], rejecting [4]
        at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
        at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
        at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:85)
        at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:140)
        at org.elasticsearch.transport.Netty4Plugin.lambda$getTransports$0(Netty4Plugin.java:93)
        at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:177)
        at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:257)

And I add "System.setProperty("es.set.netty.runtime.available.processors", "false");"
`public static void main(final String[] args) {`
`System.setProperty("es.set.netty.runtime.available.processors", "false");`
`SpringApplication springApplication = new SpringApplication(Application.class);`
`springApplication.addListeners(new ApplicationPidFileWriter("sns.pid"));`
`springApplication.run(args);`
`}`

It works in my local enviroment(oracle jdk1.8), but does not work in server 
enviroment(openjdk1.8).
I am not sure whether the jdk version matters? If not, how to solve the error?Thanks.

OS: Centos
Springboot: 2.0.6
Elasticsearch: 6.3.1

Maven dependency

> <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-elasticsearch</artifactId>
            <version>3.1.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
            <version>2.0.6.RELEASE</version>
        </dependency>

Application.properties
> spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.repositories.enabled=true

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by dodolzg** [comment]
> Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thanks.
Finally I added the parameters in the start bash, and it worked.
> -Des.set.netty.runtime.available.processors=false"
 
I thought that the main function code 'System.setProperty("es.set.netty.runtime.available.processors", "false");' should be loaded first.

**Comment by tetsushiawano** [comment]
maybe need to set like below.
```
	static {
		System.setProperty("es.set.netty.runtime.available.processors", "false");
	}
```
