### ISSUE TITLE
Range fields created in 5x can miss documents when upgraded to 6x

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#41184]
Doc values support for `*_range` fields has been added in 6.x to speed up queries that match a big range in conjunction with a more restrictive clause. In such case the query on the range fields uses the doc values (instead of the indexed points) to check if documents match the range or not.  However range fields created in 5x have their doc values flag set to true even though this version does not build these doc values. When upgrading indices to 6x the flag remain true and the node thinks that doc values are available for these fields. This leads to queries that can miss documents depending on the clauses that are used in conjunction with the range query. This issue is only in 6x (indices are compatible with version N-1).

**Comment by javanna** [comment]
We haven't gotten around to fixing this one, and there are no plans on fixing it as it affects 6.x only which is no longer being developed/released.
