### ISSUE TITLE
Incorrect date value (pushed back by 3 months) stored in index

### ISSUE THREAD

**Issue by varunsharma27** [elastic/elasticsearch#41190]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 17.10

**Description of the problem including expected versus actual behavior**:
Value of date field with custom formatting `YYYY/MM/DD hh:mm:ss a` is pushed back by 3 months and this messes up with all the queries. `_source` remains intact as JSON is saved as-is in Elasticsearch.
![image](https://user-images.githubusercontent.com/18154526/56126826-b4296400-5f73-11e9-9a0e-b567974f670b.png)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Set index mapping:
```
PUT date-test
{
  "mappings": {
    "doc": {
      "properties": {
        "INCIDENTDATE": {
          "type": "date"
        },
        "INCIDENTDATETIME": {
          "type": "date",
          "format": "YYYY/MM/DD hh:mm:ss a"
        },
        "INCIDENTID": {
          "type": "long"
        }
      }
    }
  }
}
```
 2. Put Data:
```
PUT date-test/doc/663183
{
  "INCIDENTDATETIME": "2018/04/27 03:11:00 PM",
  "INCIDENTDATE": "2018-04-27T00:00:00.000Z",
  "INCIDENTID": 663183
}
```
 3. Run the agg to get `actual` stored value of `INCIDENTDATETIME`
```
GET date-test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "_id": "663183"
          }
        },
        {
          "range": {
            "INCIDENTDATE": {
              "gte": 1523833200000,
              "lte": 1525042800000,
              "format": "epoch_millis"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "dateHist:INCIDENTDATETIME": {
      "date_histogram": {
        "field": "INCIDENTDATETIME",
        "interval": "1h",
        "min_doc_count": 1
      }
    }
  }
}
```
The time is pushed back by 3 months:
![image](https://user-images.githubusercontent.com/18154526/56126772-952ad200-5f73-11e9-866e-e976bdbad22a.png)

You may also change to `range` filter to `INCIDENTDATETIME` and no documents would be returned in that case.
**Provide logs (if relevant)**: None

**Comment by markharwood** [comment]
`DD` in date formats is day-of-year. 
`dd` is day-of-month.

Annoying, but as per [spec](https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html) 

Closing this as a config issue.
