### ISSUE TITLE
SQL: extending the grammar

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41195]
* [x] at the moment we support `FIRST/LAST` functions which have an equivalent meaning with `MIN/MAX` for String fields. We should [allow `MIN/MAX` for strings](https://github.com/elastic/elasticsearch/issues/35639) and delegate to `FIRST/LAST` functions.
* [x] TRUNC/TRUNCATE function is available in many RDBs. We support this one in the TRUNCATE form, but Oracle, Postgresql supports the TRUNC variant. We should consider simply adding an alias for the already available TRUNCATE function.
* [ ] ATAN2(param1, param2) should be equivalent to ATAN(param1 / param2) called with two parameters and MySQL allows the `ATAN` function to receive one or two parameters.
* [x] maybe consider adding a `TRIM(param)` function that should be the equivalent of `LTRIM(RTRIM(param))`.

**Comment by costin** [comment]
Adding to the list
* [ ] TOP - as a synonym to LIMIT

**Comment by matriv** [comment]
ATAN with two arguments seems to be supported [MySQL thing](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_atan2)
where as [MS-SQL server only supports the one arg version](https://docs.microsoft.com/en-us/sql/t-sql/functions/atan-transact-sql?view=sql-server-ver15). Currently there is no need to support atan() with 2 args, therefore I'm closing this issue as the rest of the enhancements are implemented.
