### ISSUE TITLE
Non-minimum weight node picked during allocation with explain enabled

### ISSUE THREAD

**Issue by vigyasharma** [elastic/elasticsearch#41194]
#### Problem

The cluster allocation algorithm attempts to assign a shard to minimum weight node in `decideAllocateUnassigned`. This gets missed when allocation explain is enabled, due to a short circuit on minimum weight node check. 

```java
if (currentWeight > minWeight && explain == false) {
    continue;
}
```

When `explain == true`, we proceed even if `currentWeight > minWeight`. However, downstream code assumes `currentWeight <= minWeight` and does not check it again [here](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L936-L938)

#### Proposed Fix

Change [this condition](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L936) to

```java
...
} else if (currentWeight < minWeight) {
    updateMinNode = true;
} else {
    updateMinNode = false;
}
```

I suppose `explain=true` can only be passed in manual reroutes, so this does not affect regular allocations. We should still fix this for consistency in explain API behavior.

**Comment by henningandersen** [comment]
@vigyasharma this does indeed look like a problem, thanks for reporting it.

Would you be interested in submitting the fix as a pull request (preferably including a test demonstrating the issue)?

**Comment by vigyasharma** [comment]
@henningandersen Sure, I'll take this up.

**Comment by DaveCTurner** [comment]
@vigyasharma are you still interested in addressing this?
