### ISSUE TITLE
CONTAINS query support for BKD-based geoshapes

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#41204]
`contains` relationship for the new BKD-based geoshapes is dependent on https://issues.apache.org/jira/browse/LUCENE-8620 merging into Lucene.

After that is merged, we need to expose this option in Elasticsearch and make it work with existing queries.  The `contains` relationship also needs to fail for indexes created in previous versions as the index does not contain enough information.

**Comment by dave-nm** [comment]
Am I understanding [this comment](https://issues.apache.org/jira/browse/LUCENE-8620?focusedCommentId=16925508&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16925508) correctly to indicate that this functionality has been merged into Lucene?
