### ISSUE TITLE
Decouple HLRC from server dependencies

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#41228]
Currently the (High Level Rest Client) HLRC has a dependency on the Elasticsearch server jar. 

Ideally the HLRC would not require that dependency. This may require considerable amounts of refactoring and may also scope creep into better handling of backwards and forward compatibility w/r/t the client against different versions of the server.

**Comment by jasontedor** [comment]
Why might there be scope creep here? We should endeavor to avoid that.

**Comment by jakelandis** [comment]
Scope creep may be the incorrect phrase here since we haven't really defined the complete scope of the work, only the outcome. I called it out explicitly so we when the work is planned we correctly assess the amount of work needed (if any) to address bwc/fwc concerns that come from the decoupling.

**Comment by jesinity** [comment]
it seem linked to this one #29184

**Comment by pan3793** [comment]
Any update?

**Comment by jakelandis** [comment]
Closing this issue as https://github.com/elastic/elasticsearch-java has been released and does not have a compile time dependency on Elasticsearch server code.
