### ISSUE TITLE
Elastcsearch 7 randomly slow search

### ISSUE THREAD

**Issue by nenad007** [elastic/elasticsearch#41231]
Elasticsearch Version: 7.0.0
OpenJDK Runtime Environment (build 1.8.0_201-b09)
Centos 7 Linux  3.10.0-957.5.1.el7.x86_64

After upgrade from Elasticsearch 6.7 to 7.0 it randmly took 500 - 1000 ms to deliver the result instead 9 - 12 ms. This happen mostly during 5 seconds and repeat it around 3 times per minute. 
It's a very small dataset of 40K records, that fit completely into the memory.

**Steps to reproduce**:

```
PUT dating
{
    "mappings": {
      "profile": {
        "properties": {
          "appid": {
            "type": "text"
          },
        "first_name": {
            "type": "text"
          },
         "country": {
            "type": "text"
          },
           "geo_pt": {
            "type": "geo_point"
          },
          "last_update_dt": {
            "type": "date"
          },
         "member_id": {
            "type": "integer"
          },
           "mstatus": {
            "type": "byte"
          },
          "is_hidden": {
            "type": "byte"
          },
           ...
```

```
{
                  "size": 100,
                  "from": 0,
                  "script_fields": {
                    "geo_distance": {
                        "script": {
                            "params": {
                                "lat": xxx,
                                "lon": xxx
                            },
                            "source": "doc[\'geo_pt\'].arcDistance(params.lat, params.lon)"
                        }
                    }
                  },
                  "_source": [
                    "first_name",
                    "last_request_dt",
                    "geo_distance"
                  ],
                  "sort": [
                    { "member_id" : {"order" : "desc"} }
                  ],
                  "query": {
                    "bool": {
                      "filter": [
                        {
                            "term": {
                              "mstatus": 1
                            }
                        },
                        {
                            "terms": {
                              "appid": [ xxx, xxx]
                            }
                        },
                        "term": {
                          "country": "xxx"
                        }
                      ]
                      , "must_not": [
                                {
                                  "term": {
                                    "is_hidden": 1
                                  }
                                }, 
                                {
                                  "term": {
                                    "member_id": xxx
                                  }
                                }
                                ]
                    }                    
                  }
                }
```

**Comment by matriv** [comment]
Could you please provide some more information here?
The sentence "This happen mostly during 5 seconds and repeat it around 3 times per minute." is a bit unclear. Did it happen the first 5 seconds after 7.0.0 was up and running? You continued to fire up this query and with a frequency of ~ 3 times per minute it runs slowly?

Is you cluster fully upgraded to 7.0.0 or there are still nodes running on 6.7?
How much Heap size have you configured for your cluster?
Could you check from the logs if there is something unusual when the query becomes slow?
Could you check if there is GC activity during this period that leads to the slow response?

**Comment by matriv** [comment]
I'm closing the issue here and I'd like to ask you to ask this question in the [Elasticsearch forums](https://discuss.elastic.co/c/elasticsearch) by providing also the additional info that has been requested. If there is an actual issue/bug discovered we can then proceed to open a GitHub issue.
Would be great also, to post here the url of the topic once it's opened in the Elasticsearch forums.

Generally, I'd like to ask you to post these sorts of questions on the Elasticsearch forums. We try to reserve Github for bugs and enhancement requests. Thanks you!
