### ISSUE TITLE
es 6.6.2 write data loss

### ISSUE THREAD

**Issue by tanruixing88** [elastic/elasticsearch#41246]
flink  write 1200000000 documents to es 6.6.2  may lead data loss 100000000 documents， but es5.4.1 version has all documents， both write method is same.  The index mapping is 
"properties": {
          "col1": {
            "type": "long"
          },
          "col10": {
            "type": "long"
          },
          "col11": {
            "type": "long"
          },
          "col12": {
            "type": "long"
          },
          "col13": {
            "type": "long"
          },
          "col14": {
            "type": "long"
          },
          "col15": {
            "type": "long"
          },
          "col16": {
            "type": "long"
          },
          "col17": {
            "type": "long"
          },
          "col18": {
            "type": "long"
          },
          "col19": {
            "type": "long"
          },
          "col2": {
            "type": "long"
          },
          "col3": {
            "type": "long"
          },
          "col4": {
            "type": "long"
          },
          "col5": {
            "type": "long"
          },
          "col6": {
            "type": "long"
          },
          "col7": {
            "type": "long"
          },
          "col8": {
            "type": "long"
          },
          "col9": {
            "type": "long"
          },
          "userId": {
            "type": "long"
          }

**Comment by tanruixing88** [comment]
must write 1200000000 docs，if write little data ， the problem can not happened

**Comment by matriv** [comment]
I'm closing the issue here and I'd like to ask you to post this question in the [Elasticsearch forums](https://discuss.elastic.co/c/elasticsearch. If there is an actual issue/bug discovered we can then proceed to open a GitHub issue.

Thank you!
