### ISSUE TITLE
Add support for if_seq_no and if_primary_term to ingest

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#41255]
Currently version and version type are accessible in pipeline:

```
{
  "set": {
    "field": "_version",
    "value": "{{field1}}"
  },
  "set": {
    "field": "_version_type",
    "value": "{{field2}}"
  }
}
```

However both are deprecated in a favor of `if_seq_no` and `if_primary_term`.
Ingest should support these new method of performing optimistic locking in ingest as well:

```
{
  "set": {
    "field": "_if_seq_no",
    "value": "{{field1}}"
  },
  "set": {
    "field": "_if_primary_term",
    "value": "{{field2}}"
  }
}
```

**Comment by kiawin** [comment]
Hi @martijnvg, would like to give it a try to this issue if that's ok with you :)

**Comment by martijnvg** [comment]
@kiawin yes, please go ahead and give this a try :)

**Comment by mariaral** [comment]
Hey @kiawin are you still interested in this issue? If not, I could work on this.

**Comment by kiawin** [comment]
@mariaral Thank for the interest, please go ahead :)

**Comment by mariaral** [comment]
@martijnvg I just added a PR regarding this feature. Please have a look.
