### ISSUE TITLE
java.lang.ClassNotFoundException: org.elasticsearch.action.GenericAction

### ISSUE THREAD

**Issue by LuomingXu** [elastic/elasticsearch#41260]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0..0

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_191

**OS version** (`uname -a` if on a Unix-like system): windows 10 1809(17763.437)

**Description of the problem including expected versus actual behavior**:

in powershell use command ".\elasticsearch.bat" to start elasticsearch and see this problem
![image](https://user-images.githubusercontent.com/24503603/56219254-057f4380-6099-11e9-86d7-a8ef6cef6391.png)
![image](https://user-images.githubusercontent.com/24503603/56219284-0f08ab80-6099-11e9-9fb7-3be86605f421.png)

i unzip elasticsearch-7.0.0.jar to find "org.elasticsearch.action.GenericAction" class, but i can't find it. 

![image](https://user-images.githubusercontent.com/24503603/56219541-82122200-6099-11e9-8a70-0df68005ac3a.png)

so, is this a <font color=red>BUG<font>?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

just run command ".\elasticsearch.bat", you could see this problem in win10. 
want some help....

**Provide logs (if relevant)**:

**Comment by matriv** [comment]
Do you get the same if you go on dir up and execute:
```...\elasticsearch-7.0.0\> .\bin\elasticsearch.bat``` ?

**Comment by LuomingXu** [comment]
@matriv Same

![image](https://user-images.githubusercontent.com/24503603/56259981-b7edef80-6107-11e9-8bb9-f8ea18dda3d6.png)

**Comment by LuomingXu** [comment]
i have download your Linux version and maven version, they don't have org.elasticsearch.action.GenericAction either. 

![image](https://user-images.githubusercontent.com/24503603/56332367-a1f13500-61c2-11e9-8258-ce10397f6b72.png)

this package only has 55 files, but the same package in 6.7.1 it has 56 files.
![image](https://user-images.githubusercontent.com/24503603/56332430-e8df2a80-61c2-11e9-9abb-a76493810249.png)

I think it is a file lose BUG. 
Waiting for a new version to solve this.

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

The GenericAction class was combined into Action in 7.0. The fact something is still trying to load it means you have a class that was compiled for an older version of elasticsearch being loaded. I recommend you try completely removing elasticsearch and installing fresh, including plugins.

For future issues like this we'd like to first direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.

**Comment by LuomingXu** [comment]
@rjernst  okay~
