### ISSUE TITLE
Deprecate + remove support for chained multi-fields.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#41267]
Currently it is possible to define multi-fields within a multi-field:
```
PUT my_index
{
  "mappings": {
    "properties": {
      "city": {
        "type": "text",
        "fields": {
          "raw": { 
            "type":  "keyword",
            "fields": {
              "as_double": {
                "type":  "double"
              }
            } 
          }
        }
      }
    }
  }
}
```

This behavior was probably unintentional and is not well-tested. We could not think of a good use case for chained multi-fields and would like to deprecate + remove support for the behavior.

Relates to #11053.

**Comment by jpountz** [comment]
+1

**Comment by jtibshirani** [comment]
Chained multi-fields were deprecated in #41926 (backported to 7.x in #423300, and removed in #42333.
