### ISSUE TITLE
[enrich] Ensure unique ID's when creating an enrich index from multiple sources 

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#41312]
The tentative plan to implement moving data from a source index to a .enrich index is to leverage re-index. If two or more source indexes share a common `_id` they may override each other in the final .enrich index. We should implement an ingest node pipeline to remove the `_id` from the documents going to the .enrich index to allow Elasticsearch to auto-generate the id. We should also consider preserving the original `_id` in a document field in case that value is desired key into the enrichment. Perhaps `_source_id` (assuming that isn't already a decorate value) ?

**Comment by davidkong0987** [comment]
Hi! _source_id doesn't seem to work for me, is it preserved under a different field?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
