### ISSUE TITLE
Trial license upgrade fail

### ISSUE THREAD

**Issue by wuyinan0126** [elastic/elasticsearch#41327]
**Describe the feature**: Trial license upgrade fail

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): centos 6

**Description of the problem including expected versus actual behavior**:

I applied a trial license online, and get an email reply. I tried to upgrade the license with the json file but failed. Below is the command.
```
[root@yinan-es-node ~]# curl -XPUT -u elastic 'http://10.0.1.13:9200/_license?pretty' -H "Content-Type: application/json" -d @te-only-***-gmail-com-non_production-7989edbf-b613-4e9f-b65d-2fa2507f46a5-v5.json
Enter host password for user 'elastic':
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException: Short read of DER length"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException: Short read of DER length",
    "caused_by" : {
      "type" : "invalid_key_spec_exception",
      "reason" : "java.security.InvalidKeyException: IOException: Short read of DER length",
      "caused_by" : {
        "type" : "invalid_key_exception",
        "reason" : "IOException: Short read of DER length"
      }
    }
  },
  "status" : 500
}
```
This is my cluster info: 
```
[root@yinan-es-node ~]# curl -XGET 'http://10.0.1.13:9200/_license?pretty'
{
  "license" : {
    "status" : "active",
    "uid" : "b10e251c-10ca-4a57-b638-c445f2f4d50f",
    "type" : "basic",
    "issue_date" : "2019-04-08T01:40:15.943Z",
    "issue_date_in_millis" : 1554687615943,
    "max_nodes" : 1000,
    "issued_to" : "es-0y2xfjh5",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
```

**Comment by cbuescher** [comment]
Hi @wuyinan0126 ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
