### ISSUE TITLE
Root script query can run on nested documents

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#41339]
Originated from #41323

A script query mixed with a nested query can sometimes execute on nested documents. 
For instance the following query:
````
{
   "query" : {
      "bool" : {
         "must" : [
            {
               "script" : {
                  "script" : {
                     "source" : "doc['x'].value == 0",
                     "lang" : "painless"
                  }
               }
            },
            {
               "nested" : {
                  "query" : {
                     "match_all": {}
                  },
                  "path" : "nested"
               }
            }
         ]
      }
   }
}
````
will eventually evaluate `doc['x'].value == 0` on nested documents. In terms of matching this is not an issue since these matches are discarded by the other mandatory clause (the `nested` query can only match parent document) but it can be unexpected for users. This is especially true now that we throw an error when trying to access a value on a missing field. 
The workaround is to add a protective test in the script to eliminate documents (and in this case nested documents) missing the field: `if (doc['x'].value == 0) { return false }` but this is unintuitive for fields that are present in all root documents. 
I wonder if we should try to fix it or warn against it in the documentation.

**Comment by jimczi** [comment]
Normally script score queries are never executed on a document that doesn't match the other mandatory clause (what we call two-phase queries) so this shouldn't happen in practice. However in Lucene 8 the scorer for mandatory clauses does not leverage the two-phase execution so this is why this issue popped in Elasticsearch 7 for the first time. Note that even a query like the one below will eventually execute the script on nested document:
````
{
   "query" : {
      "bool" : {
         "must" : [
            {
               "script" : {
                  "script" : {
                     "source" : "doc['x'].value == 0",
                     "lang" : "painless"
                  }
               }
            },
            {
               "terms" : {
                  "title": "hello"
               }
            }
         ]
      }
   }
}
`````

 I opened https://issues.apache.org/jira/browse/LUCENE-8770 because this is the root cause but I think we can also add a protection in the ScriptScoreQuery to ensure that the first phase eliminates nested documents entirely.

**Comment by jpountz** [comment]
LUCENE-8770 needs to be addressed anyway, but I don't think there is any way around this issue but documentation: there will always be some cases that will trigger the evaluation of the script on nested documents. Attempting to avoid this in all cases would force us to disable some query optimizations, I don't think this is the right trade-off.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.
