### ISSUE TITLE
Stack Security Tutorial Documentation Improvement

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#41348]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0
**JVM version** (`java -version`): 1.8
**OS version** (`uname -a` if on a Unix-like system): OS X 10.14.3

**Description of the problem including expected versus actual behavior**:
The stack security tutorial documentation is here:
https://www.elastic.co/guide/en/elastic-stack-overview/current/security-getting-started.html

Experimenting with this process on a fresh install, I discovered that if one uses a platinum license instead of a trial license (one of the earliest steps), the tutorial can no longer be followed because Elasticsearch refuses to start properly without TLS. In particular, this causes it to become impossible to run the setup passwords utility.

It also makes it impossible to follow the stack TLS tutorial (which might be a reasonable thing for a user to attempt at given the error mentions TLS). That tutorial involves multiple nodes and has as a prerequisite that security already be setup and working, including initial passwords being generated.

It is of course fully possible to generate the TLS certificates for the first node, and configure it to use them, according to instructions elsewhere. However, in terms of the tutorials, this deviation prevents following them further.

It might be an idea to rethink the order in which the steps are run, perhaps even going so far as to ditch the separation between the two tutorials and include TLS setup early on. This would permit platinum license holders to participate, should they feel uncomfortable using a trial license. I have experienced issues in the past when moving from the trial license to the platinum license, particularly around TLS. So I advocate early exposure. Moreover I think even non-platinum users should be getting to grips with TLS; you can't really have a secure cluster without it!

**Comment by lcawl** [comment]
This is a good suggestion and it applies to basic licenses in 7.1 and later too.  Thanks!

**Comment by lcawl** [comment]
The tutorials have been significantly revamped (e.g. see https://www.elastic.co/guide/en/elastic-stack-overview/master/encrypting-internode-communications.html). They now assume that a basic license is used (instead of a trial license).

**Comment by debadair** [comment]
[docs issue triage]

Closing as fixed.
