### ISSUE TITLE
Document how to use the G1 garbage collector

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#41358]
The [Elasticsearch 6.5.0 release blog](https://www.elastic.co/blog/elasticsearch-6-5-0-released) mentions support for JDK 11 and G1GC. The product [support matrix](https://www.elastic.co/support/matrix#matrix_jvm) shows support for JDK 11 for Elasticsearch versions 6.5.x-7.0.x. This is all great news.

What is missing is official documentation on how to use the G1 collector and where to configure it. Specifically, G1 is **only** supported when using JDK 11 or higher (JDK 12 is supported as of 6.7.x) in versions of Elasticsearch that support those JDKs. There have been reports of users configuring G1 under JDK 8 which is **not** a supported configuration. E.g.:

```
[2019-04-16T21:07:52,944][INFO ][o.e.n.Node] [node.name] version[6.5.4], pid[6203], 
build[default/rpm/d2ef93d/2018-12-17T21:17:40.758843Z], OS[Linux/3.10.0-
957.1.3.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_191/25.191-b12]

[2019-04-16T21:07:52,944][INFO ][o.e.n.Node] [node.name] JVM arguments [-Xms30g, -
Xmx30g, -XX:+UseG1GC, -XX:+AlwaysPreTouch, -Djava.awt.headless=true, -
Dfile.encoding=UTF-8,
```

Documenting when to use G1 would be a big bonus. For example, "Try G1 when the use case is ... or when heap utilization performance charts look like ..."

@jpcarey

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.

**Comment by lucabelluccini** [comment]
It would be great to have the supported GC in the support matrix, depending on ES version & JDK.

**Comment by jrodewig** [comment]
Going to close this issue.

With #49123, we now default to G1GC for JDK 14+. With #59667, Elasticsearch 7.11+ ergonomically adjusts G1GC options based on heap size.

While users can manually adjust G1GC options, I don't think we should encourage it or document it in depth. That effort can be covered in #53889.
