### ISSUE TITLE
X-Opaque-ID support and JSON logging improvement

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#41350]
JSON logging implementation used at the moment (v7) is pretty simplistic and there is almost no way to modify or extend the way the messages are logged.
The goal is to refactor the implementation to allow:
- [x] following more know  `log4j.JSONLayout` style where additional fields can be added [(serach for "To include any custom field") ](https://logging.apache.org/log4j/2.x/manual/layouts.html) 
- [ ] adding additional fields which could be hardcoded in a log4j configuration, looked up (as per previous `log4j.JSONLayout`) or calculated and populated from plugins. Not sure we need that - haven't noticed plugin authors asking for this.
- [ ] possibility to override fields format (different log timestamp format, overriding class (component) formatting etc) Again, do we need this?
- [x] adding `X-Opaque-Id` for Deprecated Logging #34127
- [x] move SlowLog fields from message  field to independent JSON fields.
- [ ] reconfigure Slow Logs to exclude fields from logs #22683
- [ ] move markers (from `PrefixLogger`) from message to its own field in a JSON log message

**Comment by pgomulka** [comment]
In regards to slow logs improvements. This will allow to define custom first level fields in JSON logs. It should make logs more readable, easier to parse too and consistent with Deprecated logging which will have x-opaque-id field.
So previously the slow log would have the fields in a `message field` like here:
```
{
  "type": "index_indexing_slowlog",
  "timestamp": "2019-01-29T08:35:54,170+0100",
  "level": "WARN",
  "component": "i.i.s.index",
  "cluster.name": "distribution_run",
  "node.name": "node-0",
  "cluster.uuid": "oqKkg2eoQh2P_KrKliI3DA",
  "node.id": "U7rdLkcqR9eRvOiyLmr_qQ",
  "message": "[index1/PJlGJFFURIO1zIboktQMUw] took[4.6ms], took_millis[4], type[_doc], id[1], routing[], source[{\"somefield\":\"somevalue\"}]"
}
```
but we could have these as an independent fields in a log JSON 
```
{
  "type": "index_indexing_slowlog",
  "timestamp": "2019-04-18T17:38:13,786+0200",
  "level": "WARN",
  "component": "i.i.s.index",
  "cluster.name": "distribution_run",
  "node.name": "node-0",
  "message": "[index4/TgJiha3aRpOIc2xSicpRNA]",
  "took": "34.2ms",
  "took_millis": "34",
  "doc_type": "doc",
  "id": "3",
  "routing": "null",
  "source": "{\"network\":{\"name\":\"lo0\",\"in\":{\"errors\":0,\"dropped\":0,\"bytes\":77666873,\"packets\":244595},\"out\":{\"packets\":244595,\"bytes\":77666873,\"errors\":0,\"dropped\":0}}}",
  "cluster.uuid": "tTSMxUc9SdGfEcgxP185nw",
  "node.id": "IICzgflIRnuC_B1D0y7fqw"
}
```

**Comment by cachedout** [comment]
cc: @elastic/beats and @elastic/stack-monitoring

**Comment by ycombinator** [comment]
Thanks @cachedout and @pgomulka. As you put up ES PRs for these improvements, just @-mention me in them and I'll put up corresponding Beats PRs for the parsing bits in the Filebeat ES module.
