### ISSUE TITLE
Sporadic failure of BulkRejectionIT. testBulkRejectionAfterDynamicMappingUpdate

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#41363]
This test has failed three times in a single day so there might be something going on.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'test%20:%20%22testBulkRejectionAfterDynamicMappingUpdate%22'),sort:!(time,desc))

https://scans.gradle.com/s/4hnxzwvhv2cly/tests/kyv2y2z3r4v7m-jic22iqysng2u

**Comment by droberts195** [comment]
This is still happening, for example:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/376/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-12/350/console

Does not reproduce locally using:

```
./gradlew :server:integTest --tests "org.elasticsearch.action.bulk.BulkRejectionIT.testBulkRejectionAfterDynamicMappingUpdate" \
  -Dtests.seed=F7BF87C77710351B \
  -Dtests.security.manager=true \
  -Dtests.locale=tt \
  -Dtests.timezone=SystemV/PST8 \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

I muted the test on master in c3b1f8ddbd00a8fc344b8e5e24a8d3da9951dc23

**Comment by droberts195** [comment]
Also muted in 7.x in 7e2aec022d8079c01b3917fec8f307fb3e4ba137

**Comment by droberts195** [comment]
The 7.x failure was https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1159/console
