### ISSUE TITLE
null_pointer_exception when filters aggregation is empty

### ISSUE THREAD

**Issue by noamkush** [elastic/elasticsearch#41408]
**Elasticsearch version**: 7.0.0 (reproducible on official docker)

The following request:
```json
GET _search
{
  "aggs": {
    "my_filters": {
      "filters": {}
    }
  }
}
```

Results in:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```
Workaround is easy but it should probably be fixed.

**Comment by polyfractal** [comment]
I see where the NPE is happening, it's during our parsing of keyed vs unkeyed filters agg.  Thanks for the bug report!

Fix should be easy, but it looks like the filters agg is using the old style parsing code.  I'm going to take a whack at refactoring it into the static parsers in addition to fixing the NPE.  PR to follow.
