### ISSUE TITLE
Nori(Korean) tokenizer removes the decimal point.

### ISSUE THREAD

**Issue by munkyu** [elastic/elasticsearch#41401]
unlike standard analyzer, nori analyzer removes the decimal point.

Elasticsearch version (bin/elasticsearch --version): 6.6.2

Plugins installed: [ analysis-nori ]

JVM version (java -version): java version "1.8.0_192"

Description of the problem including expected versus actual behavior:

Steps to reproduce:

1. Korean (nori) Analysis Install
bin/elasticsearch-plugin install analysis-nori

2. test each analyzer 

GET _analyze
{
  "analyzer": "standard",
  "text": ["10.1 inch monitor"]
}
// result
{
  "tokens" : [
    {
      "token" : "10.1",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "<NUM>",
      "position" : 0
    },
    {
      "token" : "inch",
      "start_offset" : 5,
      "end_offset" : 9,
      "type" : "<ALPHANUM>",
      "position" : 1
    },
    {
      "token" : "monitor",
      "start_offset" : 10,
      "end_offset" : 17,
      "type" : "<ALPHANUM>",
      "position" : 2
    }
  ]
}

GET _analyze
{
  "analyzer": "nori",
  "text": ["10.1 인치 모니터"]
}

{
  "tokens" : [
    {
      "token" : "10",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "1",
      "start_offset" : 3,
      "end_offset" : 4,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "인치",
      "start_offset" : 5,
      "end_offset" : 7,
      "type" : "word",
      "position" : 2
    },
    {
      "token" : "모니터",
      "start_offset" : 8,
      "end_offset" : 11,
      "type" : "word",
      "position" : 3
    }
  ]
}

I do not know if this is a policy, nori tokenizer removes "." character by default.
In this case, it is difficult to index the keywords including the decimal point.
The only way I find is to put it in the user dictionary, which is impossible to put all decimal points in the dictionary.

I would appreciate it if review this issue and let me know if there is any other good way to solve this.

**Comment by jimczi** [comment]
The Korean tokenizer removes punctuations entirely and group characters of the same class together, this is why `10` and `1` are separated from hangul. There is no special rule to handle numerics with floating points, however the Japanese tokenizer has an option to preserve punctuations so we could probably have the same in Nori. With this option the output would be `10`, `.`, `1`, `인치`, ...
I hope you don't mind if I close this issue but the Korean module is in [Lucene](https://issues.apache.org/jira/projects/LUCENE/issues/LUCENE-8755?filter=allopenissues) so please open a new issue in Lucene if you are interested in that option ?

**Comment by munkyu** [comment]
Thanks for the reply! I opened the new issue in Lucene: https://issues.apache.org/jira/browse/LUCENE-8784
