### ISSUE TITLE
ILM: Allow set replicas to be defined multiple times within a phase

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#41417]
Consider the use case of disabling replicas before force merge (not an uncommon practice to save on IO for very large indices).  Currently set replicas is part of the allocate action, and each action can only be defined once within a phase.  This means that if the user disables replicas before force merge in the warm phase, they will have to wait for min_age (might be many days) for the cold phase before they can use allocate there to reset replicas.

We may want to consider:
1.  Separating out set replicas into its own action
2. Then add an exception to allow set replicas action to be defined multiple times within a phase.

**Comment by gwbrown** [comment]
I can definitely see the utility of this, but allowing an action to be defined multiple times within a single phase isn't possible in the current ILM architecture.

As I said though, this is definitely something that would be useful, and it's worth thinking about other ways we might be able to accomplish the same thing.  One option that comes to mind is just bundling this as an opt-in with additional parameter/parameters into the existing force-merge action (and any other actions this might be useful for), although that's likely not the only path we could take.

**Comment by dakrone** [comment]
It's more complicated because we say in ILM that we (Elasticsearch) are responsible for determining the best order to execute things, as soon as we would allow multiple steps within a phase, we have to have ordered phases that follow user order rather than our internal order.

I agree that I can see the utility of this, and maybe we can discuss other solutions (like the one Gordon proposed).

**Comment by ppf2** [comment]
+1 I like the idea of an opt-in flag where we will manage this automatically for the end user :)

**Comment by jasontedor** [comment]
> Consider the use case of disabling replicas before force merge (not an uncommon practice to save on IO for very large indices).

Taking a step back, I am not sure that this is something that we want to encourage. It leaves users without replicas during for an extended period of time (on large shards) and at risk of not having any copies available should the primary go offline, or more fatally if the primary is lost.

**Comment by dakrone** [comment]
We discussed this today and decided that there are a few things we don't want to do:

- introduce ordered ILM actions
- introduce a way for users to sabotage themselves on accident by removing replicas at unscheduled intervals

Additionally, while it may reduce IO in that force merging is not performed on multiple shards, it would still then require more network IO to re-sync any replicas created after dropping replicas and then performing thi merge.

Given those things, we decided that we don't want to pursue this currently.
