### ISSUE TITLE
SQL: Implement aggregate functions on literals

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41412]
At the moment, aggregate functions don't work with literals (constants). For example `SELECT MAX(123)` or `SELECT gender FROM test_emp GROUP BY gender HAVING 123000 > MAX(salary)`.

**Comment by Luegg** [comment]
I think this issue can be closed by now:

`SELECT MAX(123)` returns
```
   MAX(123)    
---------------
123            
```

`SELECT gender FROM test_emp GROUP BY gender HAVING 123000 > MAX(salary)` returns
```
    gender     
---------------
null           
F              
M              
```
