### ISSUE TITLE
Non-default OpenPGP key file location for RPM repository causes issues

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/elasticsearch#41429]
**OS version** (`uname -a` if on a Unix-like system):

```Shell
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"
$ uname -a
Linux $hostname 4.4.175-94.79-default #1 SMP Thu Feb 21 16:03:55 UTC 2019 (047a6d3) x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

On openSUSE and SUSE Linux Enterprise, zypper can successfully use the RPM repo with metadata signature checking enabled. However, it seems to be that the provided OpenPGP key at https://artifacts.elastic.co/GPG-KEY-elasticsearch is at a non-default location.

For Zypper, this does not matter because it can be configured with the `gpgkey` option. Other software might not be as flexible to configure this and expects the key at https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml.key.

SUSE Manager 3.2.6 can not be configured to download the OpenPGP key from a custom URL when mirroring a repository. I already discussed this with the SUSE Support and SUSE Manager developers and the result is that:

1. Costumers either disable the "Has Signed Metadata?". This seems to be even recommended in vendor documentation for such cases.
2. The key has to be provided at the default location: https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml.key

The SUSE Support suggests that the RPM repo should be changed to provide the key at the default location to use metadata signature checking. This is why I open this issue.

**Steps to reproduce**:

1. On SUSE Manager 3.2.6 follow https://wiki.microfocus.com/index.php/SUSE_Manager/Custom_channel_and_repo to add the Elastic repository as repository in SUSE Manager. Check the check box "Has Signed Metadata?" to enable it.

  `spacecmd repo_details` should say something like this:

  ```Shell
  $ spacecmd repo_details "Elastic repository for 6.x packages"
  INFO: Connected to https://suse-manager.example.net/rpc/api as spacecmd 
  Repository Label: Elastic repository for 6.x packages 
  Repository URL: https://artifacts.elastic.co/packages/6.x/yum 
  Repository Type: yum 
  Repository SSL Ca Certificate: None 
  Repository SSL Client Certificate: None 
  Repository SSL Client Key: None
  ```

2. Add the repository in SUSE Manager to a software channel.

  `spacecmd softwarechannel_details` should say something like this:

  ```Shell
  $ spacecmd softwarechannel_details third_party-elastic-6.x-sles12-sp4-pool-x86_64
  INFO: Connected to https://suse-manager.example.net/rpc/api as admin
  Label:              third_party-elastic-6.x-sles12-sp4-pool-x86_64
  Name:               Third party - Elastic 6.x - SLES12-SP4-Pool for x86_64
  Architecture:       x86_64
  Parent:             third_party-sles12-sp4-pool-x86_64
  Systems Subscribed: 0
  Number of Packages: 456

  Summary
  -------
  Third party - Elastic 6.x - SLES12-SP4-Pool for x86_64

  GPG Key:
  GPG Fingerprint:
  GPG URL:
  GPG CHECK:          False

  Repos
  -----
  Elastic repository for 6.x packages
  ```

  In the software channel configuration, "Security: GPG" is for configuring the repo signing of this channel. It is not related to the signing of the upstream repositories included in the channel.

  https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/advanced.topics.security.html

3. Synchronize the channel from the upstream repository.

   ```Shell
   $ spacewalk-repo-sync -c third_party-elastic-6.x-sles12-sp4-pool-x86_64
   10:33:14 ======================================
   10:33:14 | Channel: third_party-elastic-6.x-sles12-sp4-pool-x86_64
   10:33:14 ======================================
   10:33:14 Sync of channel started.
   10:33:15 ChannelException: GPG key retrieval failed: [Errno 14] HTTP Error 404 : https://artifacts.elastic.co/packages/6.x/yum//repodata/repomd.xml.key
   10:33:15 Total time: 0:00:01
   ```

I also tested with https://artifacts.elastic.co/packages/7.x/yum -> Same result, https://artifacts.elastic.co/packages/7.x/yum//repodata/repomd.xml.key is not available.

**Workaround and impact**:

Unchecking "Has Signed Metadata?" allows the repo to be synced. This leaves one protection layer in place which is the RPM package signing. However, all repo metadata is unchecked leaving only the transport security (HTTPS) protection in place. This could for example allow an MITM to prevent further updates to get visible to us or with delay.

**Solution**:

Provide the OpenPGP key (additionally at):

https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml.key
https://artifacts.elastic.co/packages/7.x/yum/repodata/repomd.xml.key

instead of just at:

https://artifacts.elastic.co/GPG-KEY-elasticsearch

**Comment by rjernst** [comment]
This is now implemented for both 6.x and 7.x repos. For example, the following url now works for 7.x:
https://artifacts.elastic.co/packages/7.x/yum/repodata/repomd.xml.key

**Comment by ypid-geberit** [comment]
Works nicely, thank you!

```
# spacewalk-repo-sync -c third_party-elastic-7.x-updates-x86_64                                                                                                                            
10:55:54 ======================================                                                                                                                                               
10:55:54 | Channel: third_party-elastic-7.x-updates-x86_64                                                                                                                                    
10:55:54 ======================================
10:55:54 Sync of channel started.                               
Retrieving repository 'third_party-elastic-7.x-updates-x86_64' metadata -------------------------------------------------------------------------------------------------------------------[\$
                                     
New repository or package signing key received:
                              
  Repository:       third_party-elastic-7.x-updates-x86_64
  Key Name:         Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>
  Key Fingerprint:  46095ACC 8548582C 1A2699A9 D27D666C D88E42B4
  Key Created:      2013-09-16T17:07:54 CEST                    
  Key Expires:      (does not expire)                                 
  Subkey:           AB6B7FCB60D31954 2013-09-16 [does not expire]     
  Rpm Name:         gpg-pubkey-d88e42b4-52371eca                                
                                      
                                       
Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): a
Retrieving repository 'third_party-elastic-7.x-updates-x86_64' metadata ................................................................................................................[done$
Building repository 'third_party-elastic-7.x-updates-x86_64' cache .....................................................................................................................[done$
All repositories have been refreshed.                             
10:56:08 Repo URL: https://artifacts.elastic.co/packages/7.x/yum
10:56:08     Packages in repo:               668          
10:56:09     No new packages to sync.          
10:56:09                         
10:56:09   Patches in repo: 0.                                                                                                                                                                
10:56:09 Sync completed.                                                                                                                                                                      
10:56:09 Total time: 0:00:15
```
