### ISSUE TITLE
[docs] need some content for search_throttled indices

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#41465]
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-threadpool.html says 

search_throttled
For count/search/suggest/get operations on search_throttled indices. Thread pool type is fixed_auto_queue_size with a size of 1, and initial queue_size of 100.

But there is no information about `search_throttled indices`, but I assume it has something to do with frozen index as `search_throttled` shows up in the doc below.

https://www.elastic.co/guide/en/elasticsearch/reference/master/frozen-indices.html

If my assumption is correct, it would be good to mention `frozen index` as a side note in 
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-threadpool.html

**Comment by wchrisdean** [comment]
[doc issue triage]
