### ISSUE TITLE
ES 7.0 Docker image - OpenJDK 12 - Warnings on plugin install

### ISSUE THREAD

**Issue by pctj101** [elastic/elasticsearch#41478]
Run the following
```
docker run -ti --rm elasticsearch:7.0.0 /bin/sh
sh-4.2# /usr/share/elasticsearch/bin/elasticsearch-plugin install -b repository-s3
```

Get the following warnings:
```
-> Downloading repository-s3 from elastic
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/usr/share/elasticsearch/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
```

As a reference
```
sh-4.2# /usr/share/elasticsearch/jdk/bin/java --version
openjdk 12 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**Comment by astefan** [comment]
@pctj101 From your snippet I think it's missing the last line: `-> Installed repository-s3` which means the plugin should have been installed already and the warning you see there is only that, a warning. This is normal behavior.

What's your concern?

**Comment by pctj101** [comment]
At first glance it looked like a true failure which was falsely claiming to be a success. 

It may be a symptom of seeing so many warning lines that I didn’t naturally believe in the success message. Surely with so much warning something is bound to break in runtime (even if all the files landed on disk). 

A message which says don’t worry we expect the following messages would be cool. (In case a root cause fix isn’t easy to implement)

**Comment by pctj101** [comment]
I also thought oh, how do I grant those permissions for runtime? But maybe in reality it’s only warning about the installation using deprecated APIs. 

Hard to be sure only looking at the success message.

**Comment by astefan** [comment]
@pctj101 if you call `elasticsearch-plugin install --help`, the output will mention what `-b` option is doing:
```
-b, --batch        Enable batch mode explicitly, automatic confirmation of
                     security permission
```

**Comment by pctj101** [comment]
Agreed. However I can tell you that I had the impression that regardless of the install state, such permission warning referred to possible runtime failures. 

Anyways I believe I’ve said enough from a user perspective. 

Product design has its reasons and speaking only for myself I am happy that I now understand the messages. :)

**Comment by pctj101** [comment]
I admit it has been more than a year since I touched that Docker file and had since forgotten the content of that help message.

**Comment by jasontedor** [comment]
> Surely with so much warning something is bound to break in runtime (even if all the files landed on disk).

The warnings are deliberate, as plugins (even our own plugins!) are considered untrusted code by Elasticsearch, and the plugin is requesting elevated privileges over and above what is granted by default. When you install the plugin in non-batch mode, these warnings are followed by a prompt to accept or reject these elevated privileges for the plugin. Only in batch mode is the acknowledgement not required. Whether or not the plugin is installed in `batch` mode we feel it is important to surface these elevated privileges to the user so that they can decide whether or not to continue with using the plugin based on their security standards.

As with any CLI tool, the exit status here of zero would be indicative of success, and otherwise would be non-zero if a failure did actually occur.
