### ISSUE TITLE
Add a weight for documents in percentiles aggregations

### ISSUE THREAD

**Issue by romainneutron** [elastic/elasticsearch#41479]
This is a feature request:

The same way it's possible to compute a weighted average of a doc property using the "Weighted Avg Aggregation", I would like to be able to compute a Weighted Percentile Aggregation.

It seems it's impossible to achieve at the moment without re-implementing the whole percentile algorithm with scripts.

I think it has already been discussed in the past here https://github.com/elastic/elasticsearch/issues/8094

**Comment by jpountz** [comment]
What is your high-level use-case? #8094 mentioned it was about trying to "reduce the number of documents by grouping them". If your use-case is the same then it would be addressed by #33214.

**Comment by romainneutron** [comment]
My use case is about collecting points with variable sample rate: ie let's collect page load time:

| Load Time  | Sample Rate |
| ------------- | ------------- |
| 200  | 0.343  |
| 250  | 0.15  |
| 230  | 0.10  |
| 5000  | 0.92  |

It's easy to convert the sample rate to a weight, it's the direct inverse (`1 / sample_rate`), so I can use the WeightedAverage to calculate the average load time taking the sample rate into account.
In the same manner, I'd like to compute the percentile aggregation.

**Comment by jpountz** [comment]
Thanks for the details. I'm closing in favor of #33214 then, which would give the ability to directly index an histogram of load times into Elasticsearch, which could later be used in the percentiles aggregation.
