### ISSUE TITLE
Fix cyclic dependency between xpack-core and license-tools modules

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#41497]
Currently xpack-core module depends on the license-tools module and the license-tools module depends on xpack-core module. 

I think to remove the cyclic dependency,  the org.elasticsearch.license.licensor.LicenseSigner class should be moved from license-tools to xpack-core; then the xpack-core will no longer need to depend on license-tools?

Originates from #41064.

**Comment by atorok** [comment]
This is a cyclic dependency only in eclipse terms that does not distinguish between main and test dependencies. x-pack tests depend on license-tools. 
This will no longer be relevant if #44075 merges.

**Comment by mark-vieira** [comment]
@nik9000 is this still a concern or is Eclipse with Buildship able to cope with this now?

**Comment by nik9000** [comment]
Its now part of our standard Eclipse configuration to switch loops in the dependencies from build failures to build warnings. Its a manual step you have to do after importing the project. So, yeah, we can ignore this. Its pretty low down the list of things weird about eclipse.
