### ISSUE TITLE
Enhancement to custom plugin example documentation

### ISSUE THREAD

**Issue by joshjanoski** [elastic/elasticsearch#41494]
This is a documentation enhancement request for the following page:

https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html

When trying to get started with one of the custom plugin examples referenced on that page here: 

https://github.com/elastic/elasticsearch/tree/master/plugins/examples

I had trouble getting the examples to compile properly based on the information given. I later found out that gradle is the recommended way to compile the plugin examples and that Maven can also be used per this blog post: https://www.elastic.co/blog/how-to-develop-your-own-security-extensions-and-custom-realms-for-elasticsearch.

I would like to see the examples page updated with some basic instructions for using gradle and/or maven to compile the examples so that getting started with the plugin examples is easier. The information for doing this seems to be out there, but it isn't on this page and requires some hunting to find all of it.

Thank you for considering this enhancement!

**Comment by debadair** [comment]
[docs issue triage]

**Comment by williamrandolph** [comment]
Thank you for reporting this. If you don't mind, I will copy your comment to #15280 and close this ticket, since both tickets involve improving the same sparse documentation page.
