### ISSUE TITLE
accessibility of includeInAll field (in field mappers)

### ISSUE THREAD

**Issue by karol-gwaj** [elastic/elasticsearch#4150]
all field mappers that implement AllFieldMapper.IncludeInAll interface also define includeInAll field, there is no public getter for that field. 

do you think it will be good idea to add it to it to  AllFieldMapper.IncludeInAll interface:
```java
    public interface IncludeInAll extends Mapper {

        Boolean includeInAll(); // addidtional method to return includeInAll flag

        void includeInAll(Boolean includeInAll);

        void includeInAllIfNotSet(Boolean includeInAll);
    }
```

i need it for my external plugin

**Comment by rjernst** [comment]
I don't think we should make `IncludeInAll` any more complicated than it already is. Instead, we should remove it altogether. There should be no inheritance, it should be a direct setting on fields.
