### ISSUE TITLE
[docs] size description should be updated to clarify shard_size 

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#41520]
https://www.elastic.co/guide/en/elasticsearch/reference/6.6/search-aggregations-bucket-terms-aggregation.html says 

> By default, the node coordinating the search process will request each shard to provide its own top size term buckets

and the example below shows each shard returns their top 5 terms when size is 5. But the same page also says 

> The shard_size parameter can be used to minimize the extra work that comes with bigger requested size. When defined, it will determine how many terms the coordinating node will request from each shard.

and
 
> The default shard_size will be size if the search request needs to go to a single shard, and (size * 1.5 + 10) otherwise

Because the `shard_size` has a default value, I think the 1st quoted sentence should be "By default, the node coordinating the search process will request each shard to provide its own top `shard_size` term buckets" and the example should show each shard return 17 terms (5 * 1.5 + 10 if Elasticsearch truncates) instead of 5.

**Comment by colings86** [comment]
> "By default, the node coordinating the search process will request each shard to provide its own top shard_size term buckets"

Agreed

> the example should show each shard return 17 terms (5 * 1.5 + 10 if Elasticsearch truncates) instead of 5.

This one is tricky since coming up with an example that shows what we need it to show, in a way thats understandable to the reader, and isn't too long is surprisingly difficult. Maybe instead of changing the example we can make it clearer in the example that we are effectively setting `shard_size` to 5 so we can illustrate the point?

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

**Comment by jrodewig** [comment]
@nik9000 recently updated these docs with https://github.com/elastic/elasticsearch/pull/79205 (thanks!). I'm going to close this issue. Thanks!
