### ISSUE TITLE
Deprecate using 0 value for `min_children` in `has_child` query

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41548]
This is a follow-up to #41347 which changed the allowed minimum value for `min_children` in `has_child` query from 0 to 1.
Starting on 7.x we should emmit a warning if users are using this value. Tests should be adapted accordingly.

**Comment by cbuescher** [comment]
@codebird you mentioned you'd like to take a shot at this too, happy to help if you have questions.

**Comment by codebird** [comment]
Yep @cbuescher I am on it

**Comment by cbuescher** [comment]
Closed by #41555
