### ISSUE TITLE
Aggregations: Outdated error message for allowed characters in aggregation names

### ISSUE THREAD

**Issue by walterra** [elastic/elasticsearch#41567]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 8.0.0-SNAPSHOT, Build: default/tar/f0fac9f/2019-04-14T10:20:15.677116Z, JVM: 12

**Plugins installed**: 

`repository-gcs-8.0.0-SNAPSHOT.zip`

**JVM version** (`java -version`):

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

macOS 10.14.4 (18E226)

**Description of the problem including expected versus actual behavior**:

The error message for allowed characters in an aggregation name doesn't match the actually allowed characters.

Since the PR #6708 aggregation names "are now able to use any character except `[`, `]`, and `>`". However, the error messages says `"Invalid aggregation name [invalid_agg[]]. Aggregation names must be alpha-numeric and can only contain '_' and '-'"`

**Steps to reproduce**:

In Kibana Dev Console the following triggers the error message, note the `[` character in the aggregation name.

```
GET farequote-2019/_search
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "invalid[": {
      "avg": {
        "field": "responsetime"
      }
    }
  },
  "size": 0
}
```

To reiterate: Elasticsearch itself works as expected, it's just the error message that's misleading!

**Comment by ielatif** [comment]
Can I pick it up please?

**Comment by polyfractal** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/41573.  Thanks for the report @walterra!
