### ISSUE TITLE
[DOCS] Update text for chunk size

### ISSUE THREAD

**Issue by gchaps** [elastic/elasticsearch#41591]
The wording regarding the value for `chunk_size` setting needs to be fixed.  For example, the [Snapshot and restore page](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-snapshots.html) says this:

> The chunk size can be specified in bytes or by using size value notation, i.e. 1g, 10m, 5k.

The wording implies that if the value is just a number, it will be treated as bytes. Actually a number+unit is required, so to specify something in bytes, the user must input `1024B`.

This wording appears in multiple places: https://github.com/elastic/elasticsearch/search?q=%22specified+in+bytes+or+by+using+size+value+notation%22&unscoped_q=%22specified+in+bytes+or+by+using+size+value+notation%22

**Comment by wchrisdean** [comment]
@gchaps I want to change the language to the following for the `chunk_size` language. I just need a confirmation that this is accurate:

Big files can be broken down into chunks during snapshotting if needed. The chunk size can be specified in bytes or by
 using size value notation, **i.e. 1gb, 10mb, 5kb, 500b.** Defaults to `null` (unlimited chunk size).

I just want to ensure - is this the correct notation language for determining chunk_size? If so I can apply these to the three examples linked above.

**Comment by gchaps** [comment]
@wchrisdean Our style guide is 1 GB, 10 MB, 5 KB, 500 B.

@jen-huang Can you review the content for technical accuracy?

**Comment by jen-huang** [comment]
@gchaps From my testing this is accurate. Number **and** unit is required, even for bytes.

**Comment by wchrisdean** [comment]
Cool, I can use this to apply the right information, and use the caps as described in the style guide.
