### ISSUE TITLE
[DOCS] Update version-specific documents with restrictions on fuzzy matching when using synonyms

### ISSUE THREAD

**Issue by rwaight** [elastic/elasticsearch#41592]
**Description**:  Back-port the documentation updates from [PR #40783](https://github.com/elastic/elasticsearch/pull/40783) to version specific pages.  The reason for this issue is that we’ve updated the `master` docs page of [the Fuzziness section under Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-query.html#query-dsl-match-query-fuzziness) which states:
> Note that fuzzy matching is not applied to terms with synonyms, as under the hood these terms are expanded to a special synonym query that blends term frequencies, which does not support fuzzy expansion.

However, this paragraph is **only** in the `master` page, not in any version specific page (i.e., it is not mentioned in the [equivalent 6.2 docs page](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-match-query.html#query-dsl-match-query-fuzziness).  With that said, based on [issue #25518](https://github.com/elastic/elasticsearch/issues/25518), this appears to be applicable to all versions.

**Comment by debadair** [comment]
Cherry-picked all the way back to the 6.0 branch.
