### ISSUE TITLE
Elasticsearch 7.0.0 update request throws an exception when using retry_on_conflict parameter

### ISSUE THREAD

**Issue by reply2swami** [elastic/elasticsearch#41625]
Elasticsearch version (`bin/elasticsearch --version`):7.0.0

Plugins installed: [] analysis-phonetic, ingest-attachment

JVM version (`java -version`):1.8.0.201

OS version (`uname -a` if on a Unix-like system):Windows 2012 R2

Description of the problem including expected versus actual behavior: The update operation with retry_on_conflict parameter is throwing an exception.

Steps to reproduce:
1. POST request to create the index.
curl -XPOST "http://host:port/testindex/_doc/1" -H 'Content-Type: application/json' -d'
{  
   "doc":{  
      "first_name":"test_first"
   }
}'
Response:
{
  "_index" : "testindex",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}

2. POST request to update.

curl -XPOST "http://host:port/testindex/_update/1" -H 'Content-Type: application/json' -d'
{  
   "doc":{  
      "first_name":"test_first_new_name"
   },
   "doc_as_upsert":true,
   "retry_on_conflict":2
}'

Response:
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "[6:4] [UpdateRequest] unknown field [retry_on_conflict], parser not found"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[6:4] [UpdateRequest] unknown field [retry_on_conflict], parser not found"
  },
  "status": 400
}

**Comment by dnhatn** [comment]
@reply2swami Thank you for reporting this.

This is a bug where `retry_on_conflict` is not registered in the XContent Parser of UpdateRequest. We will work on the fix soon.

You can provide `retry_on_conflict` using a URL parameter as a workaround for this issue.

```
curl -XPOST "http://host:port/testindex/_update/1?retry_on_conflict=2" -H 'Content-Type: application/json' -d'
{
"doc":{
   "first_name":"test_first_new_name"
   },
  "doc_as_upsert":true,
}'
```

**Comment by dnhatn** [comment]
I took a closer look at the documentation of[ update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) and realized that we only support "retry_on_conflict" provided via a query parameter (i.e., URL parameter) not in the body of a request. Thus I am closing this as a non-issue.

Thanks very much for your interest in Elasticsearch.

**Comment by reply2swami** [comment]
Hi dnhatn,

Thanks for taking this up. 
Yes, as you have mentioned, it works when we use it as a URL parameter.

**Comment by FilipeBorges1993** [comment]
Hi, 
Any progress on the topic ?! 
For updating we need to send as URL parameter?!!

**Comment by chovy** [comment]
So what's the solution guys?

**Comment by reply2swami** [comment]
Hi, as mentioned above, it works when we use it as a URL parameter. Thanks.

**Comment by BARERM** [comment]
This BUG still exists today.
Elasticsearch Version:7.4.2.
