### ISSUE TITLE
Elastic 7.0.0 Bundled with JDK

### ISSUE THREAD

**Issue by sathishk** [elastic/elasticsearch#41629]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): MacOSX

**Description of the problem including expected versus actual behavior**:
I download the tar distribution of the elastic search installation. One difference between the previous version and 7.0.0 is that It is bigger than previous tar files. Later I noticed that Java is bundled with distribution so that we don't need to set JAVA_HOME explicitly. But my doubt is that Elastic needs just java runtime right ?. If so, We should include **JRE, not the JDK**. 
<img width="449" alt="Screen Shot 2019-04-29 at 11 51 50 AM" src="https://user-images.githubusercontent.com/1736813/56879201-338b5d00-6a75-11e9-92ae-923db20f5a53.png">

**Comment by jasontedor** [comment]
Having the JDK available is useful for purposes such as debugging. Additionally, Oracle no longer produces distributions that are JRE-only since JDK 11. We are considering using `jlink` to produce a custom smaller distribution but at this time have not concluded that it is worth it.
