### ISSUE TITLE
Join validation throttling

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#41632]
Each join request to the master results in the master sending the whole cluster state to the joining node in order to validate the join. If the cluster state is large and there are many nodes joining simultaneously then today there doesn't seem to be anything limiting the amount of heap that the serialised copies of these join validation messages might consume. In particular, if you perform a full cluster restart and start the master nodes last then the elected master might repeatedly run out of heap while it is trying to re-form the cluster.

I propose limiting the number of in-flight join validation attempts to allow the master to push back instead of overloading itself.

**Comment by DaveCTurner** [comment]
Note that this is only likely to be a problem for cluster states that are much larger than we normally recommend anyway (many 10s of MBs) and for clusters with hundreds of nodes. Note also that the state included in the join validation message is not compressed or shared like it is with cluster state publications.

**Comment by DaveCTurner** [comment]
We discussed this today and decided that the assumed failure mechanism seems like it could occur, although we never got a heap dump to confirm that this was what was happening in this case. Fixing it is not a priority: we don't think we've seen this failure very often (if at all before this one case) and it would be tricky to reproduce in the test suite.

I'm marking this as `help wanted` to invite further investigation from the community.

**Comment by ywelsch** [comment]
As this hasn't come up in recent times (so looks to be less of an actual issue), I will close this.
