### ISSUE TITLE
SQL: Add CSV Separator option

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#41634]
** Current feature : **
Using Elasticsearch 7.0.0
Using SQL with format=csv will return data separated with comma ","
When expected separator on French OS will likely expect ";" meaning the CSV file won't open properly

** Requested feature **:
Ability to specify the separator to use for example : ?format=csv&csvSeparator=%3B

Example : 
```
POST /_sql?format=csv
{
    "query": "SELECT * FROM test"
} 

#this returns this which won't work if the separator is not a coma: 
user,value
John Smith,1
Bob ; Smith,2

#we would want " POST /_sql?format=csv&csvSeparator=%3B " which should return
user;value
John Smith;1
"Bob ; Smith";2

```

**Comment by fbaligand** [comment]
I would love this new option!

**Comment by sopascampeao** [comment]
Hello @jguay as part of an assignment for college, i would like to implement this. Let me know if you agree.

**Comment by fbaligand** [comment]
@sopascampeao @jguay @rjernst 
Any news on this issue?
We are very interested by this feature in my company, to be able to generate CSV files as attachments in emails sent by Watcher API.
The aim is then to open CSV files with Microsoft Excel. And when your locale is "French", Microsoft Excel automatically uses ";" as column separator in CSV files.
So without this feature, when we open a CSV file with Microsoft Excel, whole line is in one cell :(
