### ISSUE TITLE
Get Date by evaluating date math expression

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#41655]
I want to determine what Date Elasticsearch will use if i specify a datemath expression.

e.g.: `now/M-1M`

However, I can't find any way to actually calculate the date using Elasticsearch's REST APIs or the Java rest client.

Use case:
I need to sew in data from another source, but don't know how far back to look if my start time in ES is `now/M-1M'.  So I can't align the two datasources time ranges.

**Comment by Deltharis** [comment]
Any news on this? Is there a way to resolve datemath using REST API or Java client/library?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).

**Comment by Deltharis** [comment]
So... is this possible in the Java client? I don't believe this issue was rest client specific, original post mentions wanting to be able to do it in either.
