### ISSUE TITLE
Document HLRC not supporting recursive calls in callback

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#41669]
we are not supporting HLRC calls from within callbacks on hlrc's async calls
calls like are blocking and end up with timeouts.

**Comment by javanna** [comment]
If I read this correctly, we are not supporting blocking calls from within async calls, meaning from within listener callbacks. That is bad practice, it makes sense to state this explicitly in the docs though.

**Comment by wchrisdean** [comment]
[doc issue triage]
