### ISSUE TITLE
SQL: Upgrade to JDK 11 HttpClient 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#41675]
With 8.0 requiring JDK 11, it makes sense to upgrade the venerable `HttpURLConnection` to the newly introduced `HttpClient` inside the JDBC driver.
While at it, it makes sense to also move to an async approach in order to prepare for future non-blocking APIs such as [ADBA](https://blogs.oracle.com/java/jdbc-next:-a-new-asynchronous-api-for-connecting-to-a-database) and [R2DBC](https://github.com/r2dbc).

**Comment by mp911de** [comment]
Note: R2DBC requires Java 8.

**Comment by costin** [comment]
"Oracle stops work on ADBA"
https://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/2019-September/000529.html

**Comment by wchaparro** [comment]
Superceded by ES|QL
