### ISSUE TITLE
[CI] loading openjdk-12.0.1_linux-x64_bin with wrong extension

### ISSUE THREAD

**Issue by ielatif** [elastic/elasticsearch#41688]
CI build is tring to load openjdk-12.0.1_linux-x64_bin with xml extension instead of  tar.gz and getting Read timed out.

>  [7.0.1] > Configure project :benchmarks
>  [7.0.1] =======================================
>  [7.0.1] Elasticsearch Build Hamster says Hello!
>  [7.0.1]   Gradle Version        : 5.2.1
>  [7.0.1]   OS Info               : Linux 4.13.0-36-generic (amd64)
>  [7.0.1]   Compiler JDK Version  : 12 (Oracle Corporation 12.0.1 [OpenJDK 64-Bit Server VM 12.0.1+12])
>  [7.0.1]   Compiler java.home    : /var/lib/jenkins/.java/openjdk12
>  [7.0.1]   Runtime JDK Version   : 1.8 (Oracle Corporation 1.8.0_212 [Java HotSpot(TM) 64-Bit Server VM 25.212-b10])
>  [7.0.1]   Runtime java.home     : /var/lib/jenkins/.java/java8
>  [7.0.1]   Gradle JDK Version    : 12 (Oracle Corporation 12.0.1 [OpenJDK 64-Bit Server VM 12.0.1+12])
>  [7.0.1]   Gradle java.home      : /var/lib/jenkins/.java/openjdk-12.0.1-linux
>  [7.0.1]   Random Testing Seed   : BBB7DF024034B19B
>  [7.0.1] =======================================
>  [7.0.1] 
>  [7.0.1] FAILURE: Build failed with an exception.
>  [7.0.1] 
>  [7.0.1] * Where:
>  [7.0.1] Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/distribution/bwc/bugfix/build/bwc/checkout-7.0/distribution/build.gradle' line: 275
>  [7.0.1] 
>  [7.0.1] * What went wrong:
>  [7.0.1] Could not determine the dependencies of task ':distribution:extractLinuxJdk'.
>  [7.0.1] > Could not resolve all files for configuration ':distribution:jdk_linux'.
>  [7.0.1]    > Could not resolve jdk:linux:12.0.1.
>  [7.0.1]      Required by:
>  [7.0.1]          project :distribution
>  [7.0.1] 
>  [7.0.1]       > Could not resolve jdk:linux:12.0.1.
>  [7.0.1] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
>  [7.0.1]          > Could not get resource 'https://download.oracle.com/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.xml'.
>  [7.0.1]             > Could not GET 'https://download.oracle.com/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.xml'.
>  [7.0.1]                > Read timed out

**Comment by jasontedor** [comment]
Hi, the behavior here is correct. This is part of our Gradle resolution works, first looking for metadata in an associated `.xml` file. In this case, it's not the non-existence of that file that caused the failure, but rather a network error occurred that cause the read to timeout rather than return with a 404 which would have led Gradle to continue attempting to download the `.tar.gz`. We do rebuild our CI images periodically to automatically include these build-time dependencies in our CI images, to reduce the chance that we encounter network errors during the build.
