### ISSUE TITLE
[Doc] Document automatic ordering of ILM actions

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#41729]
On this [page](https://www.elastic.co/guide/en/elasticsearch/reference/current/_actions.html), it will be helpful to:

1.  Put a note at the top of this page to indicate that ILM will automatically order the actions within a phase, i.e., users do not have to worry about what actions to list first in a phase.  In fact, users cannot influence the ordering themselves.  And that the actions listed within each phase on this page are in the order consistent with the automatic ordering (see part 2 below).

2.  Currently, on this page, we list the actions within each phase in an undetermined order.  It will be helpful to list these using an ordering that is consistent with the automatic ordering used in our code.  

For example, for warm phase, the automatic ordering is:  Unfollow, SetPriority, Allocate, ForceMerge, ReadOnly, Shrink.  

But these actions are listed in the doc in the order: SetPriority, Allocate, ReadOnly, ForceMerge, ShrinkAction, Unfollow

**Comment by gwbrown** [comment]
We originally decided not to document this order because we did not want to guarantee it to be consistent between minor or even patch versions, as changing it may be necessary as part of a (theoretical) bugfix.

However, I don't think we've had to do this yet, so it's worth revisiting this discussion now that ILM has had some time in the wild.

**Comment by gwbrown** [comment]
However, it would be good to at least add a note to this page that the order is automatically determined by ILM and cannot be influenced by changing the policy.

**Comment by ppf2** [comment]
>it would be good to at least add a note to this page that the order is automatically determined by ILM and cannot be influenced by changing the policy

I do see the concern about having to keep the docs in sync when our code changes.  I think it can be sufficient to have this note so end users will know that they don't have to order these manually. thx!
