### ISSUE TITLE
Flagging of Dynamically Created Fields 

### ISSUE THREAD

**Issue by jamestutton** [elastic/elasticsearch#41735]
**Feature**

I have recently been working around the area of dynamic fields in elastic mappings and wondering if other people could see a benefit it some sort of flag being set against items that get generated dynamically.   My Reasoning being in ideal world all fields should be defined  and set correctly but when processing new logs the dynamic feature can be useful.

So what I'm proposing would be when a dynamic mapping is created it gets a flag such as "auto_created":
```
 "filename" : {
            "type" : "text",
            "flag": "auto_created",  <------
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
```

This way when someone is reviewing mappings you can quickly check for the flag and review and tweak the auto created mappings.  Then simple remove the flag or even set a different one perhaps depending on workflow.

**Comment by markharwood** [comment]
Thanks for this proposal.
There is a challenge in adding this sort of metadata into the mapping definition itself. Currently what is reported in the GET mapping API is content that can be passed to the PUT mapping api so adding a derived property like "auto_created" would lose some of that symmetry.

In terms of what you can do today, we do log which templates were in effect when an index is created so a diff of the contents of that template and the current index mapping would give you an indication of which fields were introduced by dynamic mapping.

Another way of introspecting the growth of a mapping in more detail is to make use of the "exists" query in aggregations. Using [this example](https://gist.github.com/markharwood/45b8d66778322e26f5891c96cd060592) you can see when the field `foo` was first introduced. The same syntax could be used for all fields in a mapping to plot a timeline of when fields were introduced.

On balance, with these available workarounds and the difficulties in adding "autocreated" to the mapping definition we're not sure that the proposed feature is something we want to take forward.
