### ISSUE TITLE
Wrong error message when configuring security

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elasticsearch#41764]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.1 GA

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): MacOS

**Description of the problem including expected versus actual behavior**:
- I added `xpack.security.enabled: true` while with basic license without starting a trial first,
- I tried to set a password using `./bin/elasticsearch-setup-passwords auto`, got this error  `Unexpected response code [403] from calling GET http://127.0.0.1:9400/_security/_authenticate?pretty`
ERROR: X-Pack Security is not available. even though I enabled security in the yml file, I think the error should be **The cluster doesn't have the license to use security. Either start a trial or update the license**
- After figuring I forgot to start a trial license, I removed `xpack.security.enabled: true` from the yml file
-  Started a trial, then tried to repeat the process of setting a password, but got this error: 
```
Failed to authenticate user 'elastic' against http://127.0.0.1:9400/_security/_authenticate?pretty
Possible causes include:
 * The password for the 'elastic' user has already been changed on this cluster
 * Your elasticsearch node is running against a different keystore
   This tool used the keystore at /Users/alona/7-0/elasticsearch-7.0.1/config/elasticsearch.keystore

ERROR: Failed to verify bootstrap password
```
While I was on basic there were no signs it created a password, I think it should not have set a password when I was using basic license.

**Comment by tvernum** [comment]
Given that there are no longer any licenses that do not permit security, I'm closing this issue.

However, for completeness in the second step, the full message you should have received is:
```
Unexpected response code [403] from calling GET http://127.0.0.1:9200/_security/_authenticate?pretty
It doesn't look like the X-Pack security feature is available on this Elasticsearch node.
Please check if you have installed a license that allows access to X-Pack Security feature.

ERROR: X-Pack Security is not available.
```
We could probably clean up the wording there, but it is explicit about this being a license problem.

> While I was on basic there were no signs it created a password, I think it should not have set a password when I was using basic license.

It doesn't.
I think it is more likely that you ran into the second part of the error:
```
* Your elasticsearch node is running against a different keystore
```
