### ISSUE TITLE
After Downgrade vpm 7.0.0 to 6.7.1 Error "Unexpected field [cluster_uuid_committed]"

### ISSUE THREAD

**Issue by jhoelzl** [elastic/elasticsearch#41780]
Hello,

i made an update from Elasticsearch 6.7.1 to 7.0.0, but experienced some issues, therefore i downgraded back to 6.7.1. However, now i get the error:

> [2019-05-03T07:40:35,983][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [Uh_tm8N] uncaught exception in thread [main]
> 
> 
> org.elasticsearch.bootstrap.StartupException: ElasticsearchException[java.io.IOException: failed to read [id:22, file:/usr/share/elasticsearch/data/nodes/0/_state/global-22.st]]; nested: IOException[failed to read [id:22, file:/usr/share/elasticsearch/data/nodes/0/_state/global-22.st]]; nested: IllegalArgumentException[Unexpected field [cluster_uuid_committed]];
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:22, file:/usr/share/elasticsearch/data/nodes/0/_state/global-22.st]
> 
> 
> 	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:304) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:112) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:57) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:88) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	... 6 more
> 
> 
> Caused by: java.io.IOException: failed to read [id:22, file:/usr/share/elasticsearch/data/nodes/0/_state/global-22.st]
> 
> 
> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:298) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:112) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:57) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:88) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	... 6 more
> 
> 
> Caused by: java.lang.IllegalArgumentException: Unexpected field [cluster_uuid_committed]
> 
> 
> 	at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1270) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1300) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1291) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:196) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:294) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:112) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:57) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:88) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
> 
> 
> 	... 6 more

So, when i remove the docker volume including the elasticsearch data and start a new/fresh one, it works again, but, of course, i want to use my existing data again.

Do you have any suggestions?

**Comment by tvernum** [comment]
> i made an update from Elasticsearch 6.7.1 to 7.0.0, but experienced some issues, therefore i downgraded back to 6.7.1

We don't ever support version downgrades of Elasticsearch. If you want to be able to rollback an upgrade you need to have a snapshot of the old cluster (or, in some cases, a copy of the old data directory).

Perhaps we could help resolve the issues you had with 7.0, and allow you to roll forwards instead?  
If you'd like to attempt than, then please open a topic on our  [forums](https://discuss.elastic.co/). This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

Since the situation you've found yourself in is not a supported path, there isn't really a bug or feature request for us to resolve here. As such I hope you don't mind if I close this issue.
 
Thank you.
