### ISSUE TITLE
Documenting http filtering settings defaults and inherit from transport filtering settings

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#41790]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.1 (official docker image used but it's not version or installation specific)
**Steps to reproduce**
2 scenarios : 

A. Scenario with elasticsearch.yml
 1. On 3 nodes cluster (fourth IP is kibana's), on elasticsearch.yml use :
```
xpack.security.transport.filter.enabled: true
xpack.security.transport.filter.allow: [ "172.18.0.2/32", "172.18.0.3/32", "172.18.0.4/32", "172.18.0.5/32"]
xpack.security.transport.filter.deny: "_all"
```
 2. Observe that GET _cluster/settings?include_defaults shows http filtering is now in place in defaults cluster settings:
```
(...) "security" : {
        "dls_fls" : {
          "enabled" : "true"
        },
        "transport" : {
          "filter" : {
            "allow" : [
              "172.18.0.2/32", (...)
        "http" : {
          "filter" : {
            "allow" : [
              "172.18.0.2/32",
```
This also is working per those settings transport AND http filtering are active

B. Scenario with cluster settings update API (potentially more confusing)
1- Start a 3 node clusters (no ip filtering)
2- Add IP filtering : 
```
PUT _cluster/settings
{
  "persistent": {
    "xpack.security.transport.filter.enabled": true,
    "xpack.security.transport.filter.allow": [
      "172.18.0.2/32",
      "172.18.0.3/32",
      "172.18.0.4/32",
      "172.18.0.5/32"
    ],
    "xpack.security.transport.filter.deny": "_all"
  }
}
```
3- Check the output of cluster settings : 
```
GET _cluster/settings?include_defaults
```
**-> Nothing will clearly indicate that http filtering is in place** (defaults shows no filtering and persistent settings shows only transport filtering), yet ip filtering is active for http.

To be able to disable http filtering, it will be necessary to define it : 
```
PUT _cluster/settings
{
  "persistent": {
    "xpack.security.http.filter.enabled": false
  }
}
```

The behaviour is not clear from current [documentation](https://www.elastic.co/guide/en/elastic-stack-overview/7.0/ip-filtering.html#_http_filtering)

**Comment by jguay** [comment]
Another precision - transport.filter.enabled is not inherited onto http.filter.enabled
So if you run this on a cluster with no ip filtering, you effectively enable http filtering for 4 ip addresses listed
```
PUT _cluster/settings
{
  "persistent": {
    "xpack.security.transport.filter.enabled": false,
    "xpack.security.transport.filter.allow": [
      "172.18.0.2/32",
      "172.18.0.3/32",
      "172.18.0.4/32",
      "172.18.0.5/32"
    ],
    "xpack.security.transport.filter.deny": "_all"
  }
}
```

**Comment by kunisen** [comment]
Please let me add 1 URL reference.
this behavior is explained by @tvernum, see this [SSH ticket comment](https://github.com/elastic/support-support-help/issues/1343#issuecomment-483909775),
and that SSH ticket was closed and bumped to this one.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

**Comment by rwaight** [comment]
This issue also impacts the docker images in version `6.8.0`

**Comment by jakommo** [comment]
Had a user reporting this again today and I can still repro on 7.11.
@jrodewig is this still on your radar? I think a simple warning on the docs page would be enough.

**Comment by jakommo** [comment]
Started a PR to get this rolling, feel free to reword @jrodewig
