### ISSUE TITLE
SQL: valid column size for geo types 

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#41809]
`SYS TYPES` answer contains as the 3rd column the type "precision": `The maximum column size that the server supports for this data type. [...] For string data, this is the length in characters.`.

Since the geo types are currently encoded as text types, their corresponding value should be either that of `KEYWORD` (32766) or `TEXT` (2147483647). This is currently set to 0.

**Comment by imotov** [comment]
Fixed by #41869
