### ISSUE TITLE
SQL: wrong number of values for columns

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#41811]
The queries that contain a duplicate column will only return once the value in a row.
Example: 
`select emp_no, first_name, emp_no from employees` will return:
```
{"columns":[{"name":"emp_no","type":"text","display_size":2147483647},{"name":"first_name","type":"text","display_size":2147483647},{"name":"emp_no","type":"text","display_size":2147483647}],"rows":[["10001","Georgi"]]}
```

**Comment by astefan** [comment]
Just for the record, this issue manifests itself in a nastier way in case `format=txt` (as in `/_sql?format=txt`):


```
{
    "error": {
        "root_cause": [
            {
                "type": "index_out_of_bounds_exception",
                "reason": "Index 1 out of bounds for length 1"
            }
        ],
        "type": "index_out_of_bounds_exception",
        "reason": "Index 1 out of bounds for length 1"
    },
    "status": 500
}
```

@emasab thank you for providing the PR and apologies for the delay on looking at it. We plan on having a look and validate shortly.

**Comment by emasab** [comment]
@astefan you're welcome, I'm pleased to contribute

**Comment by matriv** [comment]
`master` : 097ea36581a751605fc4f2088319d954ce35b5d1
`7.x` : 87156ad93badeaa9af0ba90252eef7ef2b561ce2
`7.4.` : 79f1e536a117bde8e6c3dd297a2f69b0e805f131
`6.8` : b3c48546c78c325952e8405fc60b7e6a7f590ca8
