### ISSUE TITLE
Validation should be added within Tokenizer block

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#41813]
**Elasticsearch version** (`bin/elasticsearch --version`): Tested against 7.0.0 and 7.0.1, I believe I've seen it in previous versions too but not tested recently/here.

**Plugins installed**: only `repository-s3`

**JVM version** (`java -version`):  

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

`Linux myhost 4.19.0-041900-generic #201810221809 SMP Mon Oct 22 22:11:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```cat /etc/upstream-release/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**: Test the examples.

You can add any valid json within the tokenizer blocks and it appears to not to be validated as valid parameters and just goes ignored/unused.

```
PUT /my-validation-test?include_type_name=true
{
  "settings": {
    "analysis": {
      "analyzer": {
        "custom_analyzer": {
          "tokenizer": "custom_tokenizer"
        }
      },
      "tokenizer": {
        "custom_tokenizer": {
          "type": "path_hierarchy",
          "delimiter": "/",
          "jimbob": "harry"
        }
      }
    }
  }
}
```

even some more nested json

```
PUT /my-validation-test?include_type_name=true
{
  "settings": {
    "analysis": {
      "analyzer": {
        "custom_analyzer": {
          "tokenizer": "custom_tokenizer"
        }
      },
      "tokenizer": {
        "custom_tokenizer": {
          "type": "path_hierarchy",
          "delimiter": "/",
          "any_text_you_want": {
            "even": {
              "nested": "works"
            }
          }
        }
      }
    }
  }
}
```

Failing silently or ignoring invalid parameters is a bad user experience, so we should validate and reject instead.

This came to light by a bad usage of `search_analyzer` within a tokenizer block that had no effect but looked like it did,eg:

```
      "tokenizer": {
        "custom_tokenizer": {
          "type": "path_hierarchy",
          "delimiter": "/",
          "search_analyzer": "keyword"
        },
```

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This duplicates #41299 and other issues linked therein.
