### ISSUE TITLE
Path-style S3 access is deprecated

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#41816]
It was recently [announced](https://forums.aws.amazon.com/ann.jspa?annID=6776) that path-style access to S3 is deprecated will be rejected by S3 starting 2020-09-30. However, since https://github.com/elastic/elasticsearch/pull/34721 (i.e. 7.0), the `repository-s3` plugin exclusively uses path-style access, to make it easier to use Minio-backed repositories. This needs a re-think.

**Comment by messense** [comment]
Hitting this issue with Alibaba Cloud OSS service (S3 alike service), it only supports virtual host style access.

**Comment by original-brownbear** [comment]
IMO, as nice as it was to get rid of this config option, we should simply add back the setting to choose between path and DNS style access.
I don't think we can determine the correct access pattern on the fly in a stable way and it's not that hard to make the correct choice of setting as a user with a little documentation on the compatibility of this anyway.

**Comment by messense** [comment]
Adding the config option back would be great. Thanks!

**Comment by original-brownbear** [comment]
We discussed this during today's team sync. The fact that AWS will stop supporting the path style access pattern makes the solution build in https://github.com/elastic/elasticsearch/pull/34721 not viable long term.

I will open a PR (to go into `7.2+`) shortly that adds back the option to choose path style access and default it to false and add documentation of this breaking change accordingly.
