### ISSUE TITLE
Documentation for Removal of Internal Version

### ISSUE THREAD

**Issue by akshaymaniyar** [elastic/elasticsearch#41822]
Elasticsearch version: 7.0.1 (7 and above)

The documentation for internal versioning should be updated to clearly state that internal versioning won't work anymore.

https://www.elastic.co/guide/en/elasticsearch/reference/7.1/docs-index_.html#_version_types

The doc still says
internal - Only index the document if the given version is identical to the version of the stored document.

Which is not valid anymore.

Was advised to open an issue here when asked on this discuss [thread](https://discuss.elastic.co/t/relation-between-version-seq-no-and-primary-term/179647/6?u=akshaymaniyar)

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by akshaymaniyar** [comment]
*bump*

**Comment by debadair** [comment]
Closing as fixed.
