### ISSUE TITLE
[Question\Sugestion] Support WKT point conversion to geo_point type

### ISSUE THREAD

**Issue by 4nonym0us** [elastic/elasticsearch#41821]
Having WKT `POINT` support only for `geo_shape` and not for `geo_point` is a bit confusing because WKT specification has GeoPoint representation.

Would't it be good to have an option to use WKT's point syntax `POINT (X, Y)` for `geo_point` for consistency as support even for more complex WKT primitives and multipart geometries is already present for `geo_shape`?

**Comment by Hohol** [comment]
I'm working on this issue.
@imotov, `geo_point` field can actually contain an array of `geo_point`.
Does it mean we need to support something like WKT's `MULTIPOINT`? Or simply supporting `POINT` is enough?

**Comment by imotov** [comment]
@Hohol I think just point should be enough to start with. If you use WellKnownText parser, you can try parsing the string as WKT and then throw an exception if it is not a Point. We can expand it later to MultiPoints and other geometries if there is a need.

**Comment by Hohol** [comment]
@imotov, PR is ready for review
https://github.com/elastic/elasticsearch/pull/44107
