### ISSUE TITLE
High Level Rest Client: Allow to retrieve the original JSON search response

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#41833]
**Describe the feature**: Some might consider this a bug, but I think this is more of a feature request.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.1

When calling `toXContent()` on a `SearchResponse`, the output will never match the original output as if `_search` was called. The reason for this is, that the keys of the aggregations are containing the type of the aggregation - which makes sense to not loose this information.

However if I would like to implement some sort of 'pass-through` from Elasticsearch to the original client with a web application, then the Elasticsearch response gets altered compared to the original response.

The code responsible for this is in https://github.com/elastic/elasticsearch/blob/7.0/server/src/main/java/org/elasticsearch/search/aggregations/ParsedAggregation.java#L64 where the typed key is part of the aggregation name.

I think it makes sense to allow this to be configurable, but I am happy to proven otherwise :-)

My current workaround is to create the search request using the HLRC, then copying some code from `RequestConverters` into my code and then use the Low Level Rest Client to execute the request and retrieve a standard `Response`, which I then return to the client.

```java
SearchRequest request = search(queryBuilder, postFilterQuery, from, aggs);
BytesRef source = XContentHelper.toXContent(request.source(), XContentType.JSON, ToXContent.EMPTY_PARAMS, true).toBytesRef();

Request lowLevelRequest = new Request(HttpPost.METHOD_NAME, INDEX + "/_search");
// createContentType is copied from RequestConverters, as all methods are protected
lowLevelRequest.setEntity(new NByteArrayEntity(source.bytes, source.offset, source.length, createContentType(XContentType.JSON)));

client.getLowLevelClient().performRequestAsync(lowLevelRequest, listener);
```

**Comment by javanna** [comment]
> the Elasticsearch response gets altered compared to the original response

The Elasticsearch response is the one received, but the client has to set the `typed_keys` parameter to `true`. It is true that the parsed classes don't allow to print their content out without typed keys, which is the problem you are encountering. Can't you ignore the type if it does not matter to you? The separator we use is `#`. Ideally, using low level client for this type of things is the best solution. When you use the high-level REST client you pay the price of parsing responses, which is a waste if all you need is the raw response.

**Comment by spinscale** [comment]
the `#` character can be a bit tricky with some templating languages on the client side.

The double parsing is a good reason to stick with the low level client however.

Please close, if you think it does not make sense to invest any time in.

**Comment by javanna** [comment]
On one hand it could be nice to expose a way to execute high-level requests and retrieving their raw responses without paying the price of parsing responses, but when I look at the manual code required to do it, only a few lines, I think that it's easy enough to do so externally. And making it easier to retrieve raw responses from high level client would mean that people realize less and less about the double parsing problem. I would lean towards leaving things as they are, if you don't mind.

**Comment by dadoonet** [comment]
> but when I look at the manual code required to do it, only a few lines, I think that it's easy enough to do so externally.

Would it be a good thing to add this in the documentation?

**Comment by javanna** [comment]
> Would it be a good thing to add this in the documentation?

Yes it would not be bad for sure.
