### ISSUE TITLE
SQL: Extend Translate API response

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#41856]
Currently, the translate API response only returns the query DSL itself without any other information.
This can be problematic because it does not indicate:
1. the indices against which the query needs to be ran (which leads to mistakes such as #34594)
2. the indices options (for example whether frozen indices are searched or not)
3. does not allow any metadata such as comments (for example if the query is incomplete due to local sorting - currently we're forced to throw an exception but it would be valuable to allow the query to pass in while mentioning the information in the details - see #41144).

A quick example would be to retrofit the response to be more like:
```json
{
  "warnings" : "...",
  "indices" : "users,usrs",
  "query" : "{ ... }"
}
```

The biggest issue this brings is backwards compatibility and whether we can introduce this in the 7.x line or wait for 8.x considering it's a breaking change.

**Comment by paulcarey** [comment]
For aggregations, it would be useful to include a mapping between column names in the SQL query and the corresponding aggregation name.

For example, a query like ` select avg(foo) as myfoo ...` will produce DSL like the following

```"aggregations" : {
        "262032680" : {
          "avg" : {
            "field" : "foo"
          }
        },
``` 
which is tricky / not possible to confidently map to the corresponding column name.

**Comment by wchaparro** [comment]
Superceded by ES|QL
