### ISSUE TITLE
Issue with ping(cors)

### ISSUE THREAD

**Issue by gordal18** [elastic/elasticsearch#41866]
client.ping({
		  requestTimeout: 60000,
	}, function (error) {
		  if (error) {
			console.error('elasticsearch cluster is down!');
	 } else {
		console.log("connection established")
	 }
});

With this code, I can see this kind of issue.

### Access to XMLHttpRequest at 'https://xxxxxx/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:8080, *', but only one is allowed.
How can I fix this problem?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
