### ISSUE TITLE
[Feature request] Add a way to configure watcher email account via API

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#41876]
**Describe the feature**:
Can we consider to add a way to configure watcher email account via API?
Currently, it seems we can only set it in `elasticsearch.yml` and perform a rolling restart to make it effective.

**Comment by lucabelluccini** [comment]
Hello @kunisen ! 
Which settings you would like to change via API?

At the moment, it is possible to configure an account via API, but the `smtp.password` setting is no more allowed on 7.x. It was allowed on 6.7.

```
PUT _cluster/settings
{
  "persistent": {
    "xpack.notification.email.account.mygmail.profile": "standard",
    "xpack.notification.email.account.mygmail.smtp.starttls.enable": true,
    "xpack.notification.email.account.mygmail.smtp.host": "smtp.gmail.com",
    "xpack.notification.email.account.mygmail.smtp.port": 587,
    "xpack.notification.email.account.mygmail.smtp.user": "email@email.email",
    "xpack.notification.email.account.mygmail.smtp.password": "yourpassword"
  }
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
