### ISSUE TITLE
[Question] Elasticsearch 7.0.0 set  ssl.certificate_authorities error

### ISSUE THREAD

**Issue by sweetpotatoman** [elastic/elasticsearch#41878]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):7.0.0

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_191"  
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)  
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):Linux xpos 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
An error message occurred after the configuration file was modified：
`/etc/elasticsearch/elasticsearch.yml`
**The following has been added**
xpack.security.enabled: true
xpack.monitoring.enabled: true
xpack.graph.enabled: true
xpack.watcher.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.ssl.key: my-application.key
xpack.ssl.certificate: my-application.crt
xpack.ssl.certificate_authorities: ["ca.crt"]

`error screenshot`
![image](https://user-images.githubusercontent.com/30063721/57282762-48ed3080-70e0-11e9-9c58-66a61e72c73d.png)

**Comment by DaveCTurner** [comment]
Hi @sweetpotatoman, this kind of question is better suited for the [discussion forum](https://discuss.elastic.co/c/elasticsearch). We prefer to keep GitHub issues only for confirmed bug reports and feature requests. Please could you open a thread on the forum with your question?

Also please don't post screenshots of text. They're impossible to search or quote in a response and are unreadable by those of us who use screen-readers. Instead just copy the text and format it appropriately.
