### ISSUE TITLE
Pick a logo and run with it

### ISSUE THREAD

**Issue by bean5** [elastic/elasticsearch#41872]
**Describe the feature**:
At the following URLs, you can see various logos used by various related products. Some are defaults, old, or new. Making them more consistent would be awesome!

https://hub.docker.com/_/elasticsearch?tab=description&page=1
https://hub.docker.com/_/logstash?tab=description&page=1
https://hub.docker.com/_/kibana?tab=description&page=1

**Comment by jasontedor** [comment]
Thanks for the report. This is not really the right repository for this, andI've opened an internal issue for this.

**Comment by bean5** [comment]
I figured you'd know where to put it. Thanks @jasontedor !
