### ISSUE TITLE
Fix cluster API documentation

### ISSUE THREAD

**Issue by fpompermaier** [elastic/elasticsearch#41885]
In the cluster API the following NOTE is wrong (I think):

node filters run in the order in which they are given, which is important if using filters that remove nodes from the set. For example _all,master:false means all the nodes except the master-eligible ones, but master:false,_all means the same as **_all** because the _all filter runs after the master:false filter.

It should be:

node filters run in the order in which they are given, which is important if using filters that remove nodes from the set. For example _all,master:false means all the nodes except the master-eligible ones, but master:false,_all means the same as **master:false** because the _all filter runs after the master:false filter.

**Comment by astefan** [comment]
@fpompermaier for this one, I don't think you are right.

`master: false` removes from the set of nodes those that are master eligible, and `_all` adds back all the nodes, because `_all` is evaluated after `master:false`. It's a combination of removing master eligible nodes and adding **all** nodes (in this order), which means `_all` in the end.

**Comment by astefan** [comment]
Also, when putting `master:false` as the first filter, it's more or less a useless one because the filtering starts from an empty set of nodes and it's like removing the master eligible nodes from an empty set of nodes.

**Comment by fpompermaier** [comment]
Actually I'm trying the following requests on http://demo.elastic.co/app/kibana (7.0.0) but the documented statements are not true..

GET _nodes/_all # OK, returns all 9 nodes
GET _nodes/master:true # OK, returns all 3 master nodes
GET _nodes/_all,master:true == GET _nodes/master:true,_all  == GET _nodes/_all 
From documentation, GET _nodes/_all,master:true should be == GET _nodes/master:true

Am I wrong?

**Comment by astefan** [comment]
@fpompermaier you are right and we might have a bug in our code. Looking into it. And I'm re-opening this issue. Thank you for your diligence on this issue.

**Comment by astefan** [comment]
This is fixed in 8.0.0 with https://github.com/astefan/elasticsearch/commit/0ab141c4113407bef573f323c087f62b57ccd5f7 and in 7.2.0 with https://github.com/elastic/elasticsearch/commit/912c6bdbfff805c5c93f22c4be41708cae76a031.
