### ISSUE TITLE
 OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will like

### ISSUE THREAD

**Issue by liujintao-123** [elastic/elasticsearch#41881]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):Version: 7.0.1, Build: oss/deb/e4efcb5/2019-04-29T12:56:03.145736Z, JVM: 1.8.0_201

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_201"

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by liujintao-123** [comment]
![image](https://user-images.githubusercontent.com/49513123/57288662-79d36280-70ec-11e9-9223-da11464a8813.png)

**Comment by liujintao-123** [comment]
Hi, what's wrong with that? Can anybody help me?

**Comment by liujintao-123** [comment]
![image](https://user-images.githubusercontent.com/49513123/57288848-dd5d9000-70ec-11e9-902a-604f80b41e66.png)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
