### ISSUE TITLE
Canvas is part of xpack security (ELK 7.0.0 )

### ISSUE THREAD

**Issue by sharathmankala** [elastic/elasticsearch#41883]
ELK 7.0.0 Canvas is part of xpack security?
i.e Canvas for free for ELK 7.0.0

Thanks in Advance,
Sharath Mankala.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Have a look at https://www.elastic.co/subscriptions. Canvas is available with the free Basic license.
