### ISSUE TITLE
how to output _id field in elasticsearch-sql-cli command line?

### ISSUE THREAD

**Issue by byronhe** [elastic/elasticsearch#41891]
how to output `_id` field in elasticsearch-sql-cli command line ?

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
