### ISSUE TITLE
Support ssl.truststore.password in JDBC driver

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#41909]
To be consistent with the rest of the Elastic stack, it will be great for the JDBC driver to support `ssl.truststore.password` and `ssl.keystore.password` settings.  Currently, the JDBC driver expects these setting names to be `ssl.truststore.pass` and `ssl.keystore.pass` and will reject `ssl.truststore.password` and `ssl.keystore.password` settings.

**Comment by matriv** [comment]
Should we just replace `pass` with `password` or support both?

**Comment by wchaparro** [comment]
Superceded by ES|QL
