### ISSUE TITLE
Fresh install crashes before it starts

### ISSUE THREAD

**Issue by Sophivorus** [elastic/elasticsearch#41912]
**Elasticsearch version**

Elasticsearch 6.5.4

**Plugins installed**

None

**JVM version**

```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**OS version**

Ubuntu 14.04.5

**Description of the problem including expected versus actual behavior**:

I'm trying to install Elasticsearch 6.5 on my DreamHost VPS running Ubuntu 14.04 (the old version of Elasticsearch is because I'm interested in installing a [MediaWiki extension](https://www.mediawiki.org/wiki/Extension:CirrusSearch) that requires it).

I downloaded and extracted the Elasticsearch 6.5 tarball, which according to the [JVM support matrix](https://www.elastic.co/support/matrix#matrix_jvm), requires OpenJDK 11. My VPS was running an old Java version, so I downloaded OpenJDK 11 and set the following to both my .bash_profile and .bashrc:

```
export JDK_HOME=/path/to/jdk
export JAVA_HOME=/path/to/jdk
export PATH=/path/to/jdk/bin:$PATH
```

Now when I run `java -version` from my SSH console, I get version 11. So far so good. But when I run `./bin/elasticsearch` as per [the install instructions](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/zip-targz.html), I get the following two lines and then my console crashes:

```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
```

I can find no logs anywhere or any clue as to why it crashes. I suspect that maybe Elasticsearch  is trying to write files somewhere my VPS is forbidding, because before I figured out what versions I needed, I tried installing the latest Elasticsearch (which comes bundled with the latest OpenJDK and is not supported on Ubuntu 14.04) and got the same warnings and crash.

Anyone has a clue on what may be going on or how to find out?? Any help is appreciated, thanks!

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
