### ISSUE TITLE
How to customize the score according to the number of documents that satisfy the query criteria?

### ISSUE THREAD

**Issue by microxsr** [elastic/elasticsearch#41928]
I have a problem that has been bothering me for a long time.
Data is a one-to-many relationship,stored using `Nested`.I use `script_score` to customize the score. I want to set the score in Nested query based on the total number of sub-items that satisfy the criteria.But only found `doc`  and `_score` , couldn't get `total`?
I just want to get the number of sub-items that satisfy the criteria when nesting queries to calculate the scores, and then sort them by the scores.
What should I do?

**Elasticsearch version** :5.4.3

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
