### ISSUE TITLE
RestHighLevelClient in spring boot 2.1.x doesn't allow a spring cloud task to finish successfully 

### ISSUE THREAD

**Issue by VernonG07** [elastic/elasticsearch#41929]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Tested with 6.4.2 through 7.0.0

**JVM version** (`java -version`):
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
Including elasticsearch-rest-high-level-client on the classpath for a spring-boot, spring cloud task service does not properly close and therefor doesn't die after the task is complete.

Removing Elasticsearch from the classpath allows the spring cloud task to function correctly and die after the task is finished.

**Steps to reproduce**:

1. Clone https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/timestamp
2. Run the application - The service dies after it prints the timestamp
3. Add 
```
                <dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-high-level-client</artifactId>
			<version>7.0.0</version>
		</dependency>
```
4. Re-run the application - The service now stays alive

**Notes**
With:
Spring Cloud Task - Finchley.SR3
Spring Boot - 2.0.x
Rest High Level Client - 6.4.2
The app functions as intended.
With:
Spring Cloud Task - Greenwich.SR1
Spring Boot -2.1.x
Rest High Level Client - 6.4.2
The app exhibits the problematic behavior

**Comment by dadoonet** [comment]
When using springboot with 
elasticsearch, you need to be explicit with some transitive dependencies as SpringBoot declares a version 6.4... 

Basically you can put this in your `pom.xml`:

```
<properties>
  <elasticsearch.version>7.0.0<elasticsearch.version>
</properties>
```

See documentation here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-customize-dependency-versions

Could you next time ask on discuss.elastic.co instead?

**Comment by astefan** [comment]
@VernonG07 I don't think this has anything to do specifically with Elasticsearch. From what I remember, Spring (and Spring Boot) do have ways to define/configure "destroy" like behavior for each of its components (beans). And the HLRC makes no exception imo.
Have a look [here](https://medium.com/@sourav.pati09/how-to-use-java-high-level-rest-client-with-spring-boot-to-talk-to-aws-elasticsearch-2b6106f2e2c) for an example - Step 6.

**Comment by huangdeyao** [comment]
thinks; 
i got it
```
       <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.1.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch -->
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>7.1.1</version>
        </dependency>
```
