### ISSUE TITLE
Alias and terms filter with lookup

### ISSUE THREAD

**Issue by ofavre** [elastic/elasticsearch#4198]
The lookup mechanism of the `terms` filter is not alias aware.

I have an index with multiple shards, and an alias on it with a routing key.
The `terms` filter using the lookup mechanism sais it uses the current index by default.
I expect it to work on the alias from the path I ran the query against, but since I get random failures, I suspect the filter of using the id as routing key (the default way) for the term lookup instead of the alias routing key.

By chance in my setup I know what index to provide, but if the query is run against multiple indices, there is no way to get the default behavior.

**Comment by clintongormley** [comment]
Not sure when this was fixed, but it works in 2.0
