### ISSUE TITLE
slow down in SearchBenchmarkTask

### ISSUE THREAD

**Issue by chenbihuan** [elastic/elasticsearch#41988]
In the method `private void runIterations(int iterations, boolean addSample)` of `SearchBenchmarkTask `, `System.nanoTime() ` is frequently called in a nested loop. It may cause slow downs. It is better to call `System.currentTimeMillis` if its precision is also acceptable.

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Elasticsearch and raising this. There are several places where we use `System#nanoTime()` in `SearchBenchmarkTask` and I think they make sense there.

Here we busy-wait to ensure we hit the targeted throughput (e.g. we expect a response every 15ms and get one every 13ms, we will busy-spin for 2ms):

https://github.com/elastic/elasticsearch/blob/c9d04ccb3a13eeaccdf056df0243477d06da013d/client/benchmark/src/main/java/org/elasticsearch/client/benchmark/ops/search/SearchBenchmarkTask.java#L62-L64

Here we do the actual measurement and `System#nanoTime()` is the usual approach to do it. While the [guarantees in the docs are vague](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--) the underlying clock is *usually* a monotonic clock that offers a much higher resolution than `System#currentTimeMillis()` (usually in the range of 10s of nanoseconds). Finally, the call that we are measuring is expected to take milliseconds and calling `System#nanoTime()` at that granularity is [fine](https://shipilev.net/blog/2014/nanotrusting-nanotime/).

https://github.com/elastic/elasticsearch/blob/c9d04ccb3a13eeaccdf056df0243477d06da013d/client/benchmark/src/main/java/org/elasticsearch/client/benchmark/ops/search/SearchBenchmarkTask.java#L65-L67

Based on that grounds the use of `System#nanoTime()` here is fine IMHO and as such I'm going to close this issue.
