### ISSUE TITLE
How to skip first N results while using scroll API

### ISSUE THREAD

**Issue by Starwalker2000** [elastic/elasticsearch#41991]
We are using scroll API to get large resultset. I'd like to fetch results from a specific position (eg from the 10000-th result) rather than from the very first one.
Since the `from` parameter is not allowed while using scroll API, I have to really fetch the first 10000 results and ignoring them. It is very time-consuming and very performance-costly.

Is it possible to accept the `from` parameter while starting a scroll query and skip the first N results internally by elasticsearch?

**Comment by MasterWang6** [comment]
hi,tom

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
