### ISSUE TITLE
Support scripted pipeline calls

### ISSUE THREAD

**Issue by peterpramb** [elastic/elasticsearch#42008]
**Describe the feature**:

Currently only the ```pipeline``` processor can be used to execute other pipelines, but it currently does not support templating (see #39955).

To allow for dynamic pipeline chaining it would be helpful to introduce a new pipeline call in ```painless``` to explicitly trigger the execution of a specific pipeline. The expectation is that the call will return after execution as the ```pipeline``` processor does.

Would this be possible at all?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
