### ISSUE TITLE
Default search.max_buckets setting blocking Elasticsearch monitoring to load nodes data

### ISSUE THREAD

**Issue by jehutywong** [elastic/elasticsearch#42001]
Elasticsearch Version: 7.0.1
Kibana Version: 7.0.1

**Plugins installed**: []

JDK 8

**OS version** (`uname -a` if on a Unix-like system):
Centos 7 x86_64

**Description of the problem including expected versus actual behavior**:
In Kibana -> monitoring-> nodes, the table list show "No items found", other views in monitoring work. It turns out that the default 10000 search.max_buckets setting is blocking the list to load.

updated limit to 20000 even don;t enough. 30000 works for me

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. i have 56 nodes in the cluster
 2. go to Kibana -> monitoring-> nodes, you will see "No items found"

**Provide logs (if relevant)**:
sample log:
Caused by: org.elasticsearch.search.aggregations.MultiBucketConsumerService$TooManyBucketsException: Trying to create too many buckets. Must be less than or equal to: [10000] but was [10016]. This limit can be set by changing the [search.max_buckets] cluster level setting.

Reference:
https://discuss.elastic.co/t/elasticsearch-monitoring-no-data-in-nodes-view/180104

**Comment by jpountz** [comment]
Thanks for reporting this issue, it is a valid one. I'm moving it to elastic/kibana#36892.
