### ISSUE TITLE
CLI tools need their own jvm options

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#42021]
We provide various CLI tools, most of which are lightweight and perform relatively quick operations. By default, we do not set any java options when we launch the jvm to run these tools so they run with the JDK's default options and on current JVMs the values are decided by [ergonomics](https://docs.oracle.com/en/java/javase/12/gctuning/ergonomics.html). On a linux machine with 64GB of ram the following options are selected by OpenJDK 12.0.1:

```
   size_t InitialHeapSize                          = 1056964608                                {product} {ergonomic}
   size_t MaxHeapSize                              = 16869490688                               {product} {ergonomic}
```

These values are in bytes and correspond to approximately a minimum of 1GB and a max of 16GB. While this might seem harmless, there are cases when these tools are run on machines where a node is already consuming almost all of the memory and the invocation of this tool triggers the oomkiller and takes down the node inadvertently.

Given this, we should provide a jvm.options file specifically for CLI tools so that they can be even more lightweight and safer to use where memory may already be an issue.

**Comment by rjernst** [comment]
I'm not sure we need the configurability of jvm options for cli tools? Rather, we could use defaults for clis (or things we set explicitly, eg small heap size we set explicitly). Having these configurable would add the potential for confusion between the different options files.
