### ISSUE TITLE
Rename rollup.get_jobs REST API to rollup.get_job

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#42026]
The [`rollup.get_jobs`](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/src/test/resources/rest-api-spec/api/rollup.get_jobs.json) end point should be named `rollup.get_job` for consistency with other endpoints which can return multiple values.  Also, the `id` should accept a wildcard or comma separated values, rather than just an `id` or `'all'`

**Comment by csoulios** [comment]
We are currently refactoring rollups and we introduce many improvements and changes. Since those APIs will be heavily modified, we would rather not make small changes like this now. Therefore, I am closing this issue.
