### ISSUE TITLE
[ML] ml.close_job specification inconsistency

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch#42055]
The ml.close_job REST JSON specification changed format from `6.6.0` to `6.7.0` and introduced an optional body declaration:

https://github.com/elastic/elasticsearch/blob/c80da0429c886fee92ddbc0b793a30e12638f652/x-pack/plugin/src/test/resources/rest-api-spec/api/ml.close_job.json#L32

```
    "body": {
      "description" : "The URL params optionally sent in the body",
      "required": false
    }
```

The .NET client API generator produced a binary compatibility issue between versions `6.6.0` and `6.7.0`, since the presence of a `body` element signifies that the endpoint uses a serialisable object in the request body.. This incompatibility was caught, and a patched specification was introduced in the .NET specification:

https://github.com/elastic/elasticsearch-net/blob/6.x/src/CodeGeneration/ApiGenerator/RestSpecification/XPack/MachineLearning/xpack.ml.close_job.replace.json

Would it be possible to remove this `body` declaration?

**Comment by davidkyle** [comment]
The close job endpoint has always supported body parameters the spec in `ml.close_job.json` was incorrect. I updated the spec when I refactored a rest test into a yml test and that required the spec to be updated for the yml test to pass (#37825), my bad I should have pinged the clients team sorry. 

Is this a problem in 7.x and later?

**Comment by codebrain** [comment]
No need to apologise - the quirk with the specifications is that if there is a *required* request body then we have the `body` declaration in the spec, if its optional then we don't include it, and we don't include it if the parameters can be either in the request url or in the request body.

I know, its not very sensible, but its what we live with!

This would be the same in all versions, so yes, `7.x` would need patching as well.

Thanks!

**Comment by benwtrent** [comment]
@codebrain @davidkyle can this be closed?
