### ISSUE TITLE
Revisit use of dependency substitution rules

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#42093]
We use [dependency substitution rules](https://github.com/elastic/elasticsearch/blob/16a2c4246fb5956d3f9020a2bc0dc827fcf7b3da/build.gradle#L211-L214) to replace external module dependencies declared in our build scripts with the corresponding project dependency.

While this is a worthwhile and powerful feature it has some costs associated with it. Firstly, simply adding these rules to the build accounts for a significant portion of build configuration time simply considering the sheer number of subprojects and configurations that we have in the build.

Second, when we use dependency substitution rules Gradle can no longer defer all dependency resolution to task execution. Because of the potential for any module in the dependency graph to be swapped out for a project dependency Gradle must resolve the full dependency graph during task graph calculation to determine if a configuration includes a project dependency, and thus a dependency on that configuration implies a corresponding task dependency.

Reading the comment in the root build script it's not completely clear to me exactly why this approach is necessary. I suggest we discuss this further to see if there are ways we can eliminate this complexity and performance cost from the build.

**Comment by mark-vieira** [comment]
After discussing with with @rjernst I think we can probably eliminate this and instead put some conditional logic [here](https://github.com/elastic/elasticsearch/blob/e7b49268e6662c9ab83e3e6965a7de0cb6b34f7d/buildSrc/src/main/groovy/org/elasticsearch/gradle/plugin/PluginBuildPlugin.groovy#L154-L166) to ensure that when used "externally" we rely on module dependencies but within the elasticsearch build itself we simply use project dependencies. We can then just use project dependencies across the board within the build and remove all need for dependency substitutions.

**Comment by atorok** [comment]
+1
