### ISSUE TITLE
Add pipeline name to ingest metadata

### ISSUE THREAD

**Issue by peterpramb** [elastic/elasticsearch#42106]
**Describe the feature**:

When using multiple chained pipelines it would be helpful to provide access to the currently running pipeline's name, something like `_ingest.pipeline`.

This can be used in error messages or for building up a list of traversed pipelines without the need to hardcode the current name into the pipeline itself (which likely will be forgotten to update when the pipeline is renamed).

**Comment by peterpramb** [comment]
Additionally, when an exception is propagated to a parent pipeline, the name of the pipeline where the exception originally occured would be useful as well (in the exception handler).

**Comment by jbaiera** [comment]
@peterpramb In the interest of keeping the issue scope limited, could you open a new issue for including the pipeline name when throwing an exception?

**Comment by peterpramb** [comment]
Of course, sorry,
