### ISSUE TITLE
Machine Learning not working with non-wildcarded alias and cross cluster search

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#42113]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.1
**Plugins installed**: []
None
**Description of the problem including expected versus actual behavior**:
Rollup caps endpoint and aliases on remote clusters

Any ML job based on cross cluster search and an alias like "cluster_two:monitoring-es" fails. This was narrowed down to the following which also fails : 
```
GET cluster_two:monitoring-es/_rollup/data
```

stack trace : 
```
{"type": "server", "timestamp": "2019-05-08T13:22:37,462+0000", "level": "DEBUG", "component": "r.suppressed", "cluster.name": "cluster0", "node.name": "es0", "cluster.uuid": "rTFY3KlpRa-FCxIuwHzxdA", "node.id": "ywH_S8sjS76Gar0m7v1fdg",  "message": "path: /cluster_two:monitoring-es/_rollup/data, params: {pretty=, index=cluster_two:monitoring-es}" , 
"stacktrace": ["org.elasticsearch.index.IndexNotFoundException: no such index [cluster_two:monitoring-es]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:747) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:699) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:655) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:163) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:142) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:102) ~[elasticsearch-7.0.1.jar:7.0.1]",
"at org.elasticsearch.xpack.rollup.action.TransportGetRollupIndexCapsAction.doExecute(TransportGetRollupIndexCapsAction.java:49) ~[?:?]",
...
```

This seems to come from[ this code](https://github.com/elastic/elasticsearch/blob/7.0/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L695-L699)

**Steps to reproduce**:

 1. set up [cross cluster search](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html)
 2. On cluster_two add an index alias
 3. On cluster_one, add pattern "cluster_two:aliasname" and check data can be read from Discover
 4. Define any ML job against this patter will fail to start data feed ("cluster_two:aliasname*" works around)
 5. Also the following will fail when not wildcarded:
```
GET cluster_two:aliasname/_rollup/data
```

**Comment by droberts195** [comment]
The problem with rollup caps is fixed by #43923 in 6.8.2 and 7.2.1.

There is a further problem with permissions required for scroll to work in CCS that can affect ML datafeeds, detailed in #43974.  But for a user who has permission to read the cluster state this problem is resolved by #43923.
