### ISSUE TITLE
Node-level `cluster.max_shards_per_node` has no effect

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#42137]
We only look at the value of `cluster.max_shards_per_node` taken from the cluster metadata which, if unset, defaults to 1000:

https://github.com/elastic/elasticsearch/blob/d8417dcb8c4322003078b8daf22fa82b9c230949/server/src/main/java/org/elasticsearch/indices/IndicesService.java#L1477

This means that setting `cluster.max_shards_per_node` in `elasticsearch.yml` has no effect, but most other dynamic settings can also be set statically like this, so this caught me by surprise.

Relates #34021
Relates https://discuss.elastic.co/t/180785

**Comment by jasontedor** [comment]
Duplicates #40803
