### ISSUE TITLE
`scaled_float` got problem when handing decimal

### ISSUE THREAD

**Issue by pinopino** [elastic/elasticsearch#42136]
reproduced on elasticsearch version 6.7.0
steps as follows:
1. `scaling_factor` set to 10000 cause i got a price with 4 digit right behind the decimal point 
```
PUT test
{
	"settings": {
		"number_of_shards": 1
	},
	"mappings": {
		"test_type": {
			"properties": {
				"price": {
					"type": "scaled_float",
					"scaling_factor": 10000
				}
			}
		}
	}
}
```
2.  the big number , 1000010605575631.5317
```
PUT test/test_type/1
{ "price": 1000010605575631.5317 }
```
3. 
```
POST test/test_type/_search
{
	"size": 0,
	"aggs": {
		"average": {
			"avg": {
				"field": "price"
			}
		}
	}
}
```
I expect to get a price of 1000010605575631.5317 back, instead the result of POST shows me:
```
{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 0,
        "hits": [ ]
    },
    "aggregations": {
        "average": {
            "value": 922337203685477.6
        }
    }
}
```

**Comment by Hohol** [comment]
> scaled_float - a floating point number that is backed by a long, scaled by a fixed double scaling factor.

Looks like `10000106055756315317` is too big to be stored as `long`.
`Long.MAX_VALUE = 9223372036854775807` - this value is used instead.

**Comment by pinopino** [comment]
exactly and thx @Hohol , seems like i misunderstood something basic, 
so i close this issue.
