### ISSUE TITLE
document_type defined in monitoring exporter

### ISSUE THREAD

**Issue by davtex** [elastic/elasticsearch#42145]
Hello,

I have just upgraded ELK to 7.0.1 and I keep getting the following deprecation log even though document_type is not defined in my elasticsearch output:

> [2019-05-14T19:58:55,462][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch bulk_path=>"/_monitoring/bulk?system_id=logstash&system_api_version=7&interval=1s", ssl_certificate_verification=>false, password=><password>, hosts=>[https://XXX:9200, https://XXX:9200], cacert=>"/etc/logstash/XX.crt", sniffing=>false, manage_template=>false, id=>"64e7e48a3b2537f41d7e25367fd8dcde234ec680d2f988c61baa5aa2ce05691f", user=>"monitor", ssl=>true, document_type=>"%{[@metadata][document_type]}", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_89d57c5e-0a8b-42d3-bbc6-66a6d2c3dcf9", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ilm_enabled=>"auto", ilm_rollover_alias=>"logstash", ilm_pattern=>"{now/d}-000001", ilm_policy=>"logstash-policy", action=>"index", sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}

As you can see from bulk_path and user, this is not a standard elasticsearch output, but rather a elasticsearch output used by monitoring exporter that we use in our setup that is ocnfigured as follows:

# ES connection string
xpack.monitoring.elasticsearch.hosts: ["https://XXX:9200", "https://XXX:9200"]

# ES trusted CAs list
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/etc/logstash/XXX.crt"
# ES monitoring credentials
xpack.monitoring.elasticsearch.username: "monitor"
xpack.monitoring.elasticsearch.password: "XXX"

Since document_type is not used anymore by ES7, it should not be used used by LS7 when monitoring exporter is configured.

**Comment by tvernum** [comment]
Hi @davtex, thanks very much for your interest in the Elastic Stack.

This appears to be an issue related to Logstash, rather than Elasticsearch.
We appreciate the feedback you have provided, but we cannot action it from this repository - would you be willing to open your issue in the [Logstash repo](https://github.com/elastic/logstash/issues) instead?

Thank you.

**Comment by davtex** [comment]
@tvernum: Yes, that makes complete sense. Perhaps I should refrain from submitting issues later at night :D. Will re-create in Logstash repo.
