### ISSUE TITLE
TopHitsAggregationBuilder adds duplicate _score sort clauses

### ISSUE THREAD

**Issue by soinio** [elastic/elasticsearch#42154]
**Elasticsearch version** 6.5.4, also current master

**Description of the problem**:

When using High Level Rest Client Java API to produce search query, using
`AggregationBuilders.topHits("th").sort("_score", SortOrder.DESC)`
causes query to contain duplicate sort clauses:
```
                        "sort": [
                            {
                                "_score": {
                                    "order": "desc"
                                }
                            },
                            {
                                "_score": {
                                    "order": "desc"
                                }
                            }
                        ],
```
This also seems to break search, causing many scores to return as null.

It seems that this is because at the following locations ifs are missing their elses:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregationBuilder.java#L233-L236
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregationBuilder.java#L250-L253

Simple work around is to use directly `AggregationBuilders.topHits("th").sort(SortBuilders.scoreSort().order(SortOrder.DESC))`.

**Comment by Hohol** [comment]
It looked trivial, so I've made a PR https://github.com/elastic/elasticsearch/pull/42179
