### ISSUE TITLE
Compatability: ES 6.1 and ES 7.1 cross cluster search 

### ISSUE THREAD

**Issue by vvvprabhakar** [elastic/elasticsearch#42171]
I'm trying to do a cross cluster search across two major versions, where few nodes are in 6.1 and few are 7.1, any idea on how it works?

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
