### ISSUE TITLE
unclear fsync documentatiom

### ISSUE THREAD

**Issue by cristifalcas** [elastic/elasticsearch#42183]
**Describe the feature**:

`By default, Elasticsearch fsyncs and commits the translog every 5 seconds if index.translog.durability is set to async or if set to request (default) at the end of every index, delete, update, or bulk request. `

I think the first "By default" needs to go. 

The meaning is really convoluted now

**Comment by dnhatn** [comment]
I opened https://github.com/elastic/elasticsearch/issues/42183 to improve the document. Thanks @cristifalcas.
