### ISSUE TITLE
[Question] Is it compatible with Dat and IPFS?

### ISSUE THREAD

**Issue by DaniellMesquita** [elastic/elasticsearch#42185]

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
