### ISSUE TITLE
The "include-tagged" tag in the doc failed to link to Java code

### ISSUE THREAD

**Issue by atparting** [elastic/elasticsearch#42192]
In the API doc, all "include-tagged" tag failed to link to code successfully.
example, In the [create_index.asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/java-rest/high-level/indices/create_index.asciidoc) , The fourth line shows `include-tagged::{doc-tests-file}[{api}-request]`, But shouldn't it shows `CreateIndexRequest request = new CreateIndexRequest("twitter"); // <1>`? Why did it not get the contents of the [IndicesClientDocumentationIT.java](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java) file?
Who can tell me why? Thank you.

**Comment by atparting** [comment]
> Pinging @elastic/es-docs

404 page not found zzz

**Comment by lcawl** [comment]
I do see that `CreateIndexRequest ...` in https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-create-index.html
Could you please clarify what you expect but do not see?

**Comment by atparting** [comment]
I browse the [asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/java-rest/high-level/indices/create_index.asciidoc) document directly, I think I'm mistaken. This document is not for browsing directly, but for generating real document.

**Comment by dnhatn** [comment]
@atparting ok, thank you for your interest in Elasticsearch.
