### ISSUE TITLE
[CI] MonitoringTribeTests failed due to setting SetOnce twice

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#42216]
`MonitoringTribeTests` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=redhat-8/200/console

The underlying error was:

```
Caused by: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.apache.lucene.util.SetOnce.set(SetOnce.java:69)
	at org.elasticsearch.xpack.core.XPackPlugin.setSslService(XPackPlugin.java:158)
	at org.elasticsearch.xpack.core.XPackPlugin.<init>(XPackPlugin.java:144)
	... 49 more
```

This did not reproduce locally using:

```
./gradlew :x-pack:qa:tribe-tests-with-license:unitTest \
  -Dtests.seed=6A86CE6E79045B0C \
  -Dtests.class=org.elasticsearch.xpack.monitoring.MonitoringTribeTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Since it's a double setting of a `SetOnce` I also tried to reproduce by running the whole suite:

```
./gradlew :x-pack:qa:tribe-tests-with-license:unitTest \
  -Dtests.seed=6A86CE6E79045B0C
```

That didn't reproduce either.

**Comment by tvernum** [comment]
Relates: #42004

**Comment by matriv** [comment]
Another failure here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=redhat-8/211/consoleFull

**Comment by tvernum** [comment]
This issue is **on hold** because our RHEL8 builds were breaking unexpectedly, so they're not currently included in the unix matrix builds.

**Comment by dakrone** [comment]
Tribes is no longer a thing, so I am going to close this since it's almost two years old.
