### ISSUE TITLE
elastic search 1.6.1 memory leak

### ISSUE THREAD

**Issue by p4tooo** [elastic/elasticsearch#42218]
Hi,

In project I maintanent is used Nest client verion 1.6.1. 
I have this code:

```
public Models.Order.ProductDto GetProductFromElastic(long ean)
        {
            const string documentType = "commerceproducts";
            var esQuery = new SearchDescriptor<CommerceProduct>();
            esQuery.Index("commerceprodukter_alias");
            esQuery.Type("commerceproducts");
            esQuery.From(0);
            esQuery.Sort(y => y.OnField("_score"));

            esQuery.Query(x => x.MatchAll());
            esQuery.Filter(f => f.And(new FilterDescriptor<CommerceProduct>().Terms("_type", new[] { documentType })));
            esQuery.Query(x => x.Filtered(ff => ff.Filter(f => f.Term("ean", ean))));

            var result = elasticClient.Search<CommerceProduct>(esQuery);
            return result.Hits.Any() ? OrderMapper.Map<Models.Order.ProductDto>(result.Hits.First().Source) : null;
        }
```

It is possible, there is memory leak? After few deys it raised to almost 2GB on local env.
In production enviroment to 17Gb. 
I tried update to version 1.9.2, just need some time to test it.
Also I tried to profile it with dotMemory, but I can not see nothing relevant.

Can you help me.

**Comment by jasontedor** [comment]
For the NEST client, can you try [elastic/elasticsearch-net](https://github.com/elastic/elasticsearch-net)? I am not sure that you would get support for such an old version, yet that repository is a better place to try than the Elasticsearch repository.
