### ISSUE TITLE
MTermVector Java High Level Client Misses Fields Property

### ISSUE THREAD

**Issue by bisztray** [elastic/elasticsearch#42232]
elasticsearch-rest-high-level-client - 7.0.1

Expected vs Actual Behaviour AND steps to reproduce:

1. Create a MultiTermVectorsRequest and add a single TermVectorsRequest WITH a field. 

```
MultiTermVectorsRequest termVectorsRequest = new MultiTermVectorsRequest();

TermVectorsRequest textRequest = new TermVectorsRequest("index", "id");
textRequest.setFields("text");
textRequest.setTermStatistics(true);
textRequest.setFieldStatistics(false);
textRequest.setPositions(false);
textRequest.setOffsets(false);
termVectorsRequest.add(textRequest);

MultiTermVectorsResponse mtermvectors = client.mtermvectors(termVectorsRequest, RequestOptions.DEFAULT);

```

2. When sending to the Java High Level Client, after transformation to low-level REST client format, the fields property is missing! 

When converting to the low-level REST request in internalPerformRequest() within RestHighLevelClient.java it can be inspected that the body of the request will be the following:

```
{
    "docs": [
        {
            "_index": "index",
            "_id": "id",
            "positions": false,
            "offsets": false,
            "field_statistics": false,
            "term_statistics": true
        }
    ]
}
```

Then this is sent to the server. 

3. The elastic search will return no term vectors, since no field was given. And this renders the High Level Java Client useless for multiple term vector retrieval.

**Comment by hub-cap** [comment]
Thanks for finding this. This would be a good first issue if you are interested in contributing. Otherwise it might be a bit before it gets fixed, since it is a good first contributor issue.

**Comment by sukumaar** [comment]
@hub-cap  I would like to pick this

**Comment by hub-cap** [comment]
@sukumaar awesome! go ahead and assign yourself, thanks for helping out!!!!

**Comment by sukumaar** [comment]
@hub-cap Thank you, can you please assign it to me ? I think I do not have access to do it so

**Comment by hub-cap** [comment]
hmm, it looks as if i cannot assign someone who is not in our org, sorry. But there is some chat here that shows you started, so :+1: 	to continue.

**Comment by ojasgulati** [comment]
@sukumaar are you working on this?

**Comment by sukumaar** [comment]
@ojasgulati I was stuck at some exception so halted working on it. Thanks for working on it.

**Comment by peonone** [comment]
@ojasgulati I'd like to pick it, the guidance here #42877 is clear to me.
