### ISSUE TITLE
Does type long does not support custom time zones in ES5.X

### ISSUE THREAD

**Issue by BIYS** [elastic/elasticsearch#42270]
my query :
```
{
  "aggregations": {
    "dateVspAggs": {
      "date_histogram": {
        "field": "timestamp",
        "interval": "day",
        "time_zone": "+08:00",
        "order": {
          "_key": "asc"
        },
        "keyed": false,
        "min_doc_count": 0,
        "extended_bounds": {
          "min": 1551369600000,
          "max": 1554047999999
        }
      }
    }
  }
}
```

when i execute this query on ES5.6.4,response error like this:
```
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "Field [timestamp_] of type [long] does not support custom time zones"
}
],
"type": "search_phase_execution_exception",
"reason": "all shards failed",
"phase": "query",
"grouped": true,
"failed_shards": [
{
"shard": 0,
"index": "xbody.hik_smart_metadata-201902-01~07",
"node": "ytXqsnmdSqmbKwEyw22fXg",
"reason": {
"type": "illegal_argument_exception",
"reason": "Field [timestamp_] of type [long] does not support custom time zones"
}
}
]
},
"status": 400
}
```

however this query can execute successfully in ES2.X.
Does type long does not support custom time zones in ES5.X?

**Comment by polyfractal** [comment]
You'll need to map the [field as a Date](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) to use things like time zones.  I'm not sure how/why this was working in 2.x, either you actually have the field mapped as a `date` or Elasticsearch was more lenient of bad mappings at the time.

In the future, questions like this tend to be best asked on the [Discuss Forums](https://discuss.elastic.co/).  Thanks!
