### ISSUE TITLE
Search result fields do not have consistent ordering

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#42307]
GetResult encapuslates a single result document from a search. In order to output the fields of the document, it iterates over the DocumentField objects. This iteration is over values of a HashMap. We should change this to be consistent, either through sorting the field names, or using a consistently ordered data structure.

**Comment by jpountz** [comment]
@rjernst why is it a problem?

**Comment by sandmannn** [comment]
a fix would be related to replacing `HashMap` with `TreeMap` in the `GetResults` and in its constructor calls, or?

**Comment by rjernst** [comment]
I had originally thought this would matter for consistent results in testing, but now realize we do this in many places, and json parsing of results won't care about ordering since objects are inspected by key.
