### ISSUE TITLE
Composite Aggregation source should have same name restrictions as aggregations

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#42339]
Aggregations disallow certain characters when naming fields: `[`, `]`, `>` are not allowed, see `VALID_AGG_NAME` in `AggregatorFactories`.

The value source in composite aggregation however allows those characters. For consistency it would be good if the same restrictions apply.

Side affects (possible, please check if applicable):

- Data Frames, fixed in #42292
- Rollup groups (@polyfractal)
- SQL (@costin)

**Comment by polyfractal** [comment]
I think this could affect Rollup indirectly.  We use the field's name as part of the aggregation name, so if there is a field that contains illegal characters we'd have to translate those to safe alternatives.  I don't think it'd be difficult to do (and wouldn't have any bwc problems since it'd be a runtime swap).

**Comment by eduardomaksoud** [comment]
Hi, i'm new to open-source coding. Can i work on this issue?

**Comment by imotov** [comment]
@eduardomaksoud welcome! I think the best place to start would to familiarize yourself with [contributing guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class). Nobody is assigned to this issue at the moment and it looks like a good simple issue to start.

**Comment by eduardomaksoud** [comment]
Thank you. Just finished reading the contributing guidelines and building the project. Looking forward to raise a PR soon.

**Comment by eduardomaksoud** [comment]
@imotov I opened a PR with what I could solve. Since this is my first contribution, it would be really helpful if you could point out if I did something wrong. I had issues while performing the bwc tests so i tested my code with "gradlew :server:test --tests org.elasticsearch.search.*"

**Comment by eduardomaksoud** [comment]
Hi @polyfractal. Recently I made a few changes to add name restrictions in the Composite Aggreggation value source. I'm a bit confused on how this would affect rollup jobs so I created a job based on the example below. Then I tried placing illegal characters in a few places to see if that would be an issue, but nothing worked and it just created the jobs normally. Could you help me with this? Where should an illegal character come from in this case?
```
curl -X PUT "localhost:9200/sensor/_doc/1?pretty" -H "Content-Type: application/json" -d "{
    \"timestamp\": \"2015-01-01T12:10:30.123456789Z\",
    \"temperature\": 200, 
    \"voltage\": 5.2, 
    \"node\": 1
}"
```

```
curl -X PUT "localhost:9200/sensor/_doc/2?pretty" -H "Content-Type: application/json" -d "{
    \"timestamp\": \"2016-01-01T12:10:30.123456789Z\",
    \"temperature\": 201,
    \"voltage\": 5.9,
    \"node\": 1  
}"
```

```
curl -X PUT "localhost:9200/_rollup/job/sensor?pretty" -H "Content-Type: application/json" -d "{
            \"index_pattern\": \"sensor\",
            \"rollup_index\": \"sensor_rollup\",
            \"cron\": \"*/30 * * * * ?\",
            \"page_size\": 1000,
            \"groups\": { 
                \"date_histogram\": {
                    \"field\": \"timestamp\",
                    \"interval\": \"60m\"
                },
                \"terms\": {
                    \"fields\": [\"node\"]
                }
            },
            \"metrics\": [ 
                {
                    \"field\": \"temperature\",
                    \"metrics\": [ \"min\", \"max\", \"sum\" ]
                },
                {
                    \"field\": \"voltage\",
                    \"metrics\": [ \"avg\" ]
                }
            ]
}"
```

**Comment by imotov** [comment]
@eduardomaksoud, polyfractal will not be able to help you with this issue. I am afraid, you are stuck with me on this one. Where did you try placing illegal characters?

**Comment by wchaparro** [comment]
closing as not planned
