### ISSUE TITLE
index template

### ISSUE THREAD

**Issue by mynameiscode** [elastic/elasticsearch#42337]
ES version:6.5.4
When I get the index mapping, the message field appears twice and the type is different. This affects my query results.
DSL like:

`PUT _template/xxx-log/
{
    "order" : 1,
    "version" : 1,
    "index_patterns" : [
      "xxx-log-*"
    ],
    "settings" : {
      "index" : {
        "number_of_shards" : "20",
        "number_of_replicas" : "1"
      }
    },
    "mappings" : {
      "log" : {
        "properties" : {
          "timestamp" : {
            "type" : "date"
          },
          "level" : {
            "type" : "keyword"
          },
          "host" : {
            "type" : "keyword"
          },
          "ip" : {
            "type" : "text"
          },
          "messsage" : {
            "type" : "text",
            "analyzer": "ik_max_word"
          },
          "logger" : {
            "type" : "text",
            "analyzer": "ik_max_word"
          },
           "tag" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    },
    "aliases" : { }
  }`

when get index mapping , the response like(just show pice) :

`"logger" : {
            "type" : "text",
            "analyzer" : "ik_max_word"
          },
          "message" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "messsage" : {
            "type" : "text",
            "analyzer" : "ik_max_word"
          }`

**Comment by romseygeek** [comment]
Hi @mynameiscode, could you please post the exact requests you make to elasticsearch so that we can reproduce this?

**Comment by mynameiscode** [comment]
1. create index template
`PUT _template/xxx-log/ { "order" : 1, "version" : 1, "index_patterns" : [ "xxx-log-*" ], "settings" : { "index" : { "number_of_shards" : "20", "number_of_replicas" : "1" } }, "mappings" : { "log" : { "properties" : { "timestamp" : { "type" : "date" }, "level" : { "type" : "keyword" }, "host" : { "type" : "keyword" }, "ip" : { "type" : "text" }, "messsage" : { "type" : "text", "analyzer": "ik_max_word" }, "logger" : { "type" : "text", "analyzer": "ik_max_word" }, "tag" : { "type" : "text", "fields" : { "keyword" : { "type" : "keyword", "ignore_above" : 256 } } } } } }, "aliases" : { } }`

2. put a doc
`PUT /xxx-log-2019-05-22/log/1
{"timestamp": "2019-05-24T14:43:32.856+0800", "level": "INFO", "host": "localhost.localdomain", "ip": "172.17.0.1",  "message": "java.io.FileNotFoundException加载文件path resource  cannot be opened because it does not exist", "logger": "java.io.FileNotFoundException加载文件path resource  cannot be opened because it does not exist", "tag": "EVENT"}`

3. get mapping and view message field.The message field appears twice and the type is different
`GET /xxx-log-2019-05-22/_mapping`

4. query dsl to test
`POST /xxx-log-2019-05-22/log/_search
{
  "query": {
    "match": {
      "message": "FileNotFoundException"
    }
  }
}`

**Comment by mynameiscode** [comment]
when i change the message field to another name such as msg, there is no problem. So i guess if there samething with the message has default common rule or config.

**Comment by romseygeek** [comment]
I think it's a misspelling - you've defined the field as `messsage` with an extra `s`?

**Comment by mynameiscode** [comment]
Thank you very much, forgive me for making a very low-level mistake.
