### ISSUE TITLE
High Level client dont include `ignore_throttled` as parameter

### ISSUE THREAD

**Issue by kfuksman** [elastic/elasticsearch#42358]
SearchRequest don't include ignore_throttled=false in the request.

` SearchRequest searchRequest = new SearchRequest();
        searchRequest.indicesOptions(IndicesOptions.fromOptions(true, true,
                true, false, searchRequest.indicesOptions().allowAliasesToMultipleIndices(),
                searchRequest.indicesOptions().forbidClosedIndices(), searchRequest.indicesOptions().ignoreAliases(), false));
    SearchResponse response = client.search(searchRequest, RequestOptions.DEFAULT);
 `

**Comment by ds-perfit** [comment]
Same issue here. 
It is not possible to query frozen indices.
