### ISSUE TITLE
Add benchmark for painless vs expression scripts

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#42395]
The implementation of expression scripts is difficult to keep in line with changes meant to make painless more performant. Additionally, since expressions are (essentially) a subset of painless, it would be nice to eventually remove them. However, before this can be done, we need to know painless has been brought up to par on performance with expression scripts.

This issue is to add a set of micro benchmarks (and maybe rally tracks as well) that we can monitor and compare the difference in performance between painless and expression scripts.

**Comment by stu-elastic** [comment]
Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
