### ISSUE TITLE
Some words do not understanding in the document.

### ISSUE THREAD

**Issue by qq253498229** [elastic/elasticsearch#42416]
https://www.elastic.co/guide/en/elasticsearch/client/java-api/6.2/java-docs-bulk-processor.html

```
.setBackoffPolicy(
            BackoffPolicy.exponentialBackoff(TimeValue.timeValueMillis(100), 3)) 
```

> Set a custom backoff policy which will initially wait for 100ms, increase exponentially and retries up to three times.

I don't quite understand the meaning of this sentence.
What the "increase exponentially" means?
Can anyone give an example?

**Comment by qq253498229** [comment]
Then I found an example of default.

```
sets backoffPolicy to an exponential backoff with 8 retries and a start delay of 50ms. The total wait time is roughly 5.1 seconds.
```

How did this 5.1 seconds work out?

**Comment by dadoonet** [comment]
Better to ask questions on discuss.elastic.co.

Basically it says that after a failure, it waits for 100ms before retrying.
If it fails again, it waits then 200ms before retrying.
Then it waits 400ms. Something along those lines.

If you still don't get it, let's talk on discuss.
