### ISSUE TITLE
Better document and motivate dedicated master nodes

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#42422]
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html does not seem to do a good job in explaining and, in particlar, *motivating* dedicated master nodes.

A google search for "elasticsearch dedicated master nodes" mainly returns results for AWS ES. Granted, a search for "elasticsearch dedicated master-eligible nodes" returns the above page, but I would argue that people would rather search for the former. Maybe this is just a search-engine optimization issue, but nevertheless I think a google search should definitely be able to find the primary Elastic documentation.

Happy to discuss.

**Comment by DaveCTurner** [comment]
@fkelbert I just did a Google search for `Elasticsearch dedicated master nodes` and the top hits for me were, in order:

- AWS ES docs for Dedicated Master Nodes
- Elastic's own docs on node types (current version, 7.1)
- Two posts on the Elastic forum re. dedicated master nodes
- Elastic's own docs on node types (version 6.3)
- Elastic's own docs on node types (version 1.4)
- Three more forum posts

Are you saying that your results are less Elastic-heavy, or is this issue opened because you'd prefer the official docs to be the top hit rather than the second one?

Also the motivation is here:

> Indexing and searching your data is CPU-, memory-, and I/O-intensive work which can put pressure on a node’s resources. To ensure that your master node is stable and not under pressure, it is a good idea in a bigger cluster to split the roles between dedicated master-eligible nodes and dedicated data nodes.

> While master nodes can also behave as coordinating nodes and route search and indexing requests from clients to data nodes, it is better not to use dedicated master nodes for this purpose. It is important for the stability of the cluster that master-eligible nodes do as little work as possible.

Can you explain more clearly what more detail you would find useful? Could you suggest some alternative wording?

**Comment by DaveCTurner** [comment]
We haven't yet had a response to the clarification questions above, so I'm closing this. Feedback is still welcome, @fkelbert, and we'll reopen this issue if needed.

**Comment by fkelbert** [comment]
Sorry @DaveCTurner . Is just didn't get around to look into this further.

The search results order is the same for me. However, I would argue that elastic.co should be the very first hit.

The underlying problem I really see is that in the field we too often encounter clusters with all nodes having all roles (default) and `minimum_master_nodes: 1` (default) (I am aware that this problem will go away with ES 7).

In terms of the docs, I find that the actual recommendation of running three dedicated master-eligible nodes is missing. I feel that other recommendations (run dedicated master-eligible nodes in the first place) are hidden between the lines (within what you have quoted). I would like these recommendations and best practices to be more explicit.

What I would like to read is something like the following:

> ## Dedicated master nodes
> 
> In larger deployments, we recommend running three dedicated master-eligible nodes and removing the `master` role from all remaining nodes of the cluster. This is important for the stability of the cluster. (Then go on to also mention `minimum_master_nodes` for ES <= 6). (Maybe give some more explanation as to why this is so important).
> 
> (Add in here: excerpt from the docs that you posted)
>

**Comment by DaveCTurner** [comment]
Thanks @fkelbert, I see what you mean. I don't know what kind of SEO magic we might need to do to displace the top hit, but I think we can work your suggestion into the page.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by fkelbert** [comment]
Great stuff, thank you for your efforts!
