### ISSUE TITLE
Cannot reproduce failures in 7.x with JDK11

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#42421]
When investigating #40174 I tried the given `REPRODUCE WITH` line on 7.x (b189596631b8bf22c2d963b95c2dedf2d8a3a824):

```
./gradlew :server:integTest \
  -Dtests.seed=2A58B98CB4ABA8E \
  -Dtests.class=org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT \
  -Dtests.method="testRerouteOccursOnDiskPassingHighWatermark" \
  -Dtests.security.manager=true \
  -Dtests.locale=prg \
  -Dtests.timezone=Asia/Damascus \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

The build failed as follows:

```
1: Task failed with an exception.
-----------
* Where:
Build file '/home/davidturner/elasticsearch/benchmarks/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > the compiler java.home must be set to a JDK installation directory for Java 12 but is [/home/davidturner/jdk-11] corresponding to [11]
```

Deleting the ` -Dcompiler.java=11` and `-Druntime.java=11` options allows me to run this test (albeit using JDK12).

**Comment by rjernst** [comment]
@mark-vieira Can you take a look at this? It seems like we shouldn't be caring about `compiler.java` anymore, maybe we can remove it?

**Comment by mark-vieira** [comment]
> It seems like we shouldn't be caring about compiler.java anymore, maybe we can remove it?

We probably don't, but the build only enforces a _minimum_ version so you could use a newer one. What I'm wondering is how it was ever reported to be 11 if in fact we require 12?

**Comment by rjernst** [comment]
Perhaps CI passed it in as JAVA_HOME?

**Comment by mark-vieira** [comment]
Ah, I think the repro line predates us bumping the required compiler version to Java 12. I'm not sure there's a whole lot we can do for "historical" repro lines in cases like this. Paul ran into a similar situation today where he attempted to run a repro line that used the `:unitTest` task which has since been renamed.

**Comment by atorok** [comment]
@mark-vieira looks like we should close this one ?

**Comment by mark-vieira** [comment]
Yeah, don't think there's anything to follow up on here.
