### ISSUE TITLE
Partial ES S3 snapshots with INTERNAL_SERVER_ERROR 

### ISSUE THREAD

**Issue by nvsajeeva** [elastic/elasticsearch#42420]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.4
**Plugins installed**: []
repository-s3

**JVM version** (`java -version`):
1.8.0_181

**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.5.1804 (Core) 
3.10.0-862.3.2.el7.x86_64

**Description of the problem including expected versus actual behavior**:
Our ES cluster consists of 3 master nodes and 4 data nodes. It contains around 6300+ shards. 
Snapshot repository is configured pointing to an S3 bucket. When a snapshot is taken,  one or two shards fail, making it a partial snapshot. 
Shards which happen to fail have no pattern. At a time it can be a shard in index A, next time it can be a shard in index B

**Provide logs (if relevant)**:

>         {
>           "index" : "IDX1",
>           "index_uuid" : "IDX1",
>           "shard_id" : 3,
>           "reason" : "IndexShardSnapshotFailedException[Failed to write file list]; nested: IOException[com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: X; S3 Extended Request ID: X), S3 Extended Request ID: X]; nested: AmazonS3Exception[The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: X; S3 Extended Request ID: X)]; ",
>           "node_id" : "-lmVU9lxS1SL3lTgeFP1JA",
>           "status" : "INTERNAL_SERVER_ERROR"
>         }

> [2019-05-23T01:20:44,600][WARN ][o.e.s.SnapshotShardsService] [data-4] [[X][3]][s3_repository:curator-prod-20190523010005/X] failed to snapshot shard
> org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: Failed to write file list
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository$Context.finalize(BlobStoreRepository.java:994) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1230) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:810) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:412) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:98) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:355) [elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: X; S3 Extended Request ID: X), S3 Extended Request ID: X
>         at org.elasticsearch.repositories.s3.S3BlobContainer.move(S3BlobContainer.java:177) ~[?:?]
>         at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeAtomic(ChecksumBlobStoreFormat.java:138) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository$Context.finalize(BlobStoreRepository.java:992) ~[elasticsearch-6.2.4.jar:6.2.4]
>         ... 10 more
>         Suppressed: java.nio.file.NoSuchFileException: Blob [pending-index-2] does not exist
>                 at org.elasticsearch.repositories.s3.S3BlobContainer.deleteBlob(S3BlobContainer.java:116) ~[?:?]
>                 at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeAtomic(ChecksumBlobStoreFormat.java:142) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.repositories.blobstore.BlobStoreRepository$Context.finalize(BlobStoreRepository.java:992) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1230) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:810) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:412) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:98) ~[elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:355) [elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.4.jar:6.2.4]
>                 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
>                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
>                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
>                 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: X; S3 Extended Request ID: X
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[?:?]
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247) ~[?:?]
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194) ~[?:?]
>         at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1870) ~[?:?]
>         at org.elasticsearch.repositories.s3.S3BlobContainer.lambda$move$6(S3BlobContainer.java:172) ~[?:?]
>         at org.elasticsearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:57) ~[?:?]
>         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
>         at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:56) ~[?:?]
>         at org.elasticsearch.repositories.s3.S3BlobContainer.move(S3BlobContainer.java:171) ~[?:?]
>         at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeAtomic(ChecksumBlobStoreFormat.java:138) ~[elasticsearch-6.2.4.jar:6.2.4]
>         at org.elasticsearch.repositories.blobstore.BlobStoreRepository$Context.finalize(BlobStoreRepository.java:992) ~[elasticsearch-6.2.4.jar:6.2.4]

**Comment by original-brownbear** [comment]
This isn't an issue anymore, the functionality works differently now and the method throwing here `move` doesn't even exist anymore in 6.4+ thanks to https://github.com/elastic/elasticsearch/commit/6e0a6d115ec086834ee7612d18c3fe39b5569f88 => closing here, upgrading to a newer version should resolve your issue.
