### ISSUE TITLE
MonitoringWithWatcherRestIT is flaky and has been muted for too long

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#42439]
There is a qa project that smoke tests monitoring with watcher using an external cluster. This QA project has one real test suite that has been muted for over 1 year (2018-01-15). There does not seem to be another issue to track this or has anyone made progress on this test.

Given this, I believe the test needs to be evaluated for its usefulness. If it is useful it should be fixed with some sense of priority or we should remove the QA project if the test is not needed.

**Comment by jakelandis** [comment]
I'll evaluate this. There are on-going efforts to un-mute some of these tests.

**Comment by dakrone** [comment]
This test no longer exists.
