### ISSUE TITLE
Kibana Devtools field autocompletion broken in 7.0.1

### ISSUE THREAD

**Issue by Jamalarm** [elastic/elasticsearch#42434]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.1

**Plugins installed**: None

**JVM version** (`java -version`): Unknown - Managed Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Unknown - Managed Elastic Cloud

**Description of the problem including expected versus actual behavior**:

Autocompletion of field names in the Kibana Dev Tools query editor appears non functional in version 7.0.1. Index name completion still works.

**Steps to reproduce**:

Open the dev tools and start building a query like:

```
POST myIndex/_search
{
  "query": {
    "term": {
      "FIELD": {
        "value": "VALUE"
      }
    }
  }
}
```

Placing the cursor at the beginning of `"FIELD" : {` and typing used to present a list of fields that were available in this index. Now there is no autocomplete at all.

**Comment by jasontedor** [comment]
Hi, sorry for the trouble that you’re having. Could you re-open this on the [elastic/kibana](https://github.com/elastic/kibana) repository though?

**Comment by Jamalarm** [comment]
Ah! Apologies, didn't realise they were different repos.
I've raised https://github.com/elastic/kibana/issues/36983
