### ISSUE TITLE
Async "stop data frame" request should respond with acknowledgement status

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#42450]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0

**Description of the problem including expected versus actual behavior**:
When you send a `stop data frame transform` API request without any query parameters specified, the `stop` request should be performed asynchronously. This means, it is expected that (if successful) a response is returned immediately with the contents:
```
{
  "acknowledged": true
}
```

If the query parameter `wait_for_completion` is set to `true`, we expect that when a response is returned from the API request, the `stop` operation has finished and the contents of the response are:
```
{
  "stopped": true
}
```

Currently, the response content for the `stop` request is `{ "stopped": true }` even if `wait_for_completion` is not specified or has the value `false`.

**Steps to reproduce**:
 1. Create a data frame transform
 2. Stop the data frame transform using the `POST _data_frame/transforms/<some_transform_id>/_stop` API, without specifying the `wait_for_completion` query parameter or specifying it with the value `false`
3. Notice that the response content says `{ "stopped": true }` instead of `{ "acknowledged": true }`

**Provide logs (if relevant)**:

**Comment by hendrikmuhs** [comment]
I verified: `_start` _waits_ for the task been started, `_stop` as said only if `wait_for_completion` is set.

I agree `_stop` behaves inconsistent.

However I find it strange if 
 - `_start` and `_stop` behave different
 - `_stop` returns different results depending on the parameter

I suggest to change it all to `acknowledged`.

**Comment by hendrikmuhs** [comment]
https://github.com/elastic/elasticsearch/pull/42589 implements:

```
"acknowledged": true
```

for both `_start` and `_stop` ignoring the fact that we know in some cases a more exact answer
