### ISSUE TITLE
Doc: Add note on ILM setup when using Logstash and Beats

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#42469]
We have users trying to set up ILM for Logstash and Beats.  Some of them started by reviewing the ILM guide on Elasticsearch side first.   The problem is that when they get to this page (https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-lifecycle-policy.html) and the 2 subpages, they believe they have to first bootstrap Logstash indices because this is what these pages suggest.

However, if they do so, when they get to set up the Logstash Elasticsearch output later on to enable ILM integration, the manual bootstrapping ended up causing Logstash to fail to create the right index names as part of the integration.

It will be helpful to put up an important note on https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-lifecycle-policy.html and its 2 subpages to tell users that Logstash and Beats will take care of setting up the policy for the appropriate indices.  In other words, the 2 steps (and related subpages) specified under the "set the policy for an index" paragraph do not apply when using ILM with Logstash and Beats.  And also link to these relevant pages as part of the notice:

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-ilm

https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html

@adoerrES @jakelandis

**Comment by debadair** [comment]
[docs issue triage]
