### ISSUE TITLE
Allow the default from email address in Watcher/monitoring templates

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#42460]
Currently the monitoring templates default the email "from" to be equal to the "to" address. This is done to ensure a valid "from" address. However, if a user defined a default email in ES, e.g.
```
    email_defaults:
            from: red@example.com
```
It is not honored. One can simply change the watch, but due to how the watches and templates are implemented any updates to ES may overwrite the custom configuration. 

I believe the ideal situation here may be to introduce the defaults as part of the context (e.g. ctx.default.email.from) and use mustache if-exists to prefer the default but fallback to the to address. 

To help explain the proposal, using a normal Watch, we can use use the metadata to emulate the var.email_recipient and a proposed new part of the context ctx.default.email.from

```
PUT _xpack/watcher/watch/_execute
{
  "watch": {
    "metadata": {
      "default_email_from": "red@example.com",
      "vars_email_recipient": "blue@example.com"
    },
    "trigger": {
      "schedule": {
        "interval": "15s"
      }
    },
    "input": {
      "simple": {}
    },
    "actions": {
      "send_email": {
        "email": {
          "to": "{{ctx.metadata.vars_email_recipient}}",
          "from": "{{#ctx.metadata.default_email_from}}{{ctx.metadata.default_email_from}}{{/ctx.metadata.default_email_from}}{{^ctx.metadata.default_email_from}}{{ctx.metadata.vars_email_recipient}}{{/ctx.metadata.default_email_from}}",
          "subject": "Watcher Notification",
          "body": "body"
        }
      }
    }
  }
}
```

In the example above, the from defaults from red@example.com unless you remove default_email_from in the metadata, then it will fall back to blue@example.com. Watcher would only inject the default.email.from if one exists (red@example.com), else it would fall back to the "to" address (blue@example.com)

Related https://github.com/elastic/elasticsearch/pull/32962

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
