### ISSUE TITLE
Empty index with completion suggesters returns null suggestions

### ISSUE THREAD

**Issue by kylelyk** [elastic/elasticsearch#42473]
**Elasticsearch version**: 6.4.2

**Plugins installed**: []

**JVM version**: java 11.0.1 2018-10-16 LTS

**OS version**: Darwin Kernel Version 18.2.0

When searching completion suggestions on a new index with no documents added, a different response is returned from when searching on na index with no documents matching.

Also a side note is that the example `PUT music` call in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) does not work.

**Steps to reproduce**:

```
PUT music
{
    "mappings": {
      "_doc": {
        "properties" : {
            "suggest" : {
                "type" : "completion"
            },
            "title" : {
                "type": "keyword"
            }
        }
      }
        
    }
}
```

```
POST music/_search?pretty
{
    "suggest": {
        "song-suggest" : {
            "prefix" : "v", 
            "completion" : { 
                "field" : "suggest" 
            }
        }
    }
}
```

Returns:

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  }
}
```

```
PUT music/_doc/1?refresh
{
    "suggest" : [
        {
            "input": "Nevermind",
            "weight" : 10
        },
        {
            "input": "Nirvana",
            "weight" : 3
        }
    ]
}
```

```
POST music/_search?pretty
{
    "suggest": {
        "song-suggest" : {
            "prefix" : "v", 
            "completion" : { 
                "field" : "suggest" 
            }
        }
    }
}
```

Returns 

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "song-suggest": [
      {
        "text": "v",
        "offset": 0,
        "length": 1,
        "options": []
      }
    ]
  }
}
```

This is a problem since `SearchResponse.getSuggest()` in the JDK will return `null` in the first case and the proper `Suggest` object in the second case. I would expect it to always return `Suggest` object in both cases.

**Comment by cbuescher** [comment]
Thanks for raising this issue. I could reproduce this on 6.7 and I guess its also still on 7.x and master. 

> Also a side note is that the example `PUT music` call in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) does not work.
The docs you linked to are from version 7.1 where we removed the need for the "_doc" type level in the request. The [6.8 docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-suggesters-completion.html) and earlier version still have the type, so they should work as expected.

**Comment by cbuescher** [comment]
Note from a discussion with the team: we should also try to look into making the behavior for `terms` and `phrase` suggesters similar to this, meaning there is no difference in response between running a suggestion on a on a new index with no documents to running it on an index with documents that don't produce any suggestions.
