### ISSUE TITLE
Remote reindex api path prefix not supported in 5.2

### ISSUE THREAD

**Issue by iit2009060** [elastic/elasticsearch#42494]
**ES Version 5.2** 

**Java Version 1.8.0_181**

**OS Linux Version 4.4.92** 

**The path prefix was not supported in elasticsearch 5.2 reindex remote api.**:

**Steps to reproduce**:

We are using host url to the reindex api  in the format **http://host:port/pathPrefix** on 5.2
When we initiate the api we received this error 
<img width="676" alt="Screenshot 2019-05-24 at 2 29 16 PM" src="https://user-images.githubusercontent.com/3364075/58316045-54ef2700-7e30-11e9-8331-5e5ea9e70148.png">
But when we checked the master branch code of the elasticsearch it had supported **pathPrefix**  for future version. 
<img width="1652" alt="Screenshot 2019-05-24 at 2 05 56 PM" src="https://user-images.githubusercontent.com/3364075/58316116-78b26d00-7e30-11e9-8b08-07b890f86440.png">

Is it possible to have this similar  change on 5.2 version

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

New or existing features cannot be added to release versions of the tool. as this feature has been already added to a release version, your best option if you need it is to upgrade to a version that contains such feature, that is 6,4+.

Note as well that version 5.2 is not maintained any more:

https://www.elastic.co/support/eol

As such, I hope you don't mind that I close this.

**Comment by iit2009060** [comment]
Is it possible for me to contribute on this , as this is a small change and we are highly dependent on the reindex api for the migration. All our cluster url have pathPrefix.

**Comment by polyfractal** [comment]
We don't generally backport changes to old versions unless it is a critical security fix, and that's doubly true for EOL versions.  Sorry :(

Not as convenient, but running a manual scroll search and indexing those results will provide more flexibility.  It's essentially the same as what the remote reindex is doing.  Most of the language clients provide scroll and bulk helpers.
