### ISSUE TITLE
i think you have mapped and throttling error on 403 instead of 503

### ISSUE THREAD

**Issue by jhonyourangel** [elastic/elasticsearch#42496]
elastic search v 6.x.x

i think you have mapped and throttling error on 403 instead of 503

can you check

**Comment by jimczi** [comment]
It is difficult to infer what the issue is with this description. Can you be more specific ? Which API are you talking about ? An example with the requests that you execute in the cluster and their output would greatly help.

**Comment by javanna** [comment]
Closing due to lack of feedback, feel free to reopen or add a comment with the requested info so we can have another look at it.
