### ISSUE TITLE
Add option to output nanoseconds in date ingest processor

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#42523]
Since version 7.0 Elasticsearch mappings can support nanosecond precision timestamps via the `date_nanos` type.  But the date ingest processor only outputs millisecond precision, so any nanosecond precision timestamp that is extracted via the date ingest processor is truncated to millisecond precision.

The reason why this happens is that the output format of the date ingest processor is hardcoded to `yyyy-MM-dd'T'HH:mm:ss.SSSXXX`.

Switching the date ingest processor to always output nanosecond precision timestamps might be a step too far - date fields would become more verbose, use more storage and might potentially cause backwards compatibility problems.

However, it would be nice if the ingest date processor had an option to output nanosecond precision timestamps if the user specifically asked for that.

**Comment by martijnvg** [comment]
We discussed this and it makes sense to make the output format configurable.
In this particular case a format using nanoseconds can be used. In other cases when even less granularity than ms is needed, this can then also be configured (which then allows storing the data more efficiently in the index). The default output format should remain `yyyy-MM-dd'T'HH:mm:ss.SSSXXX`.

**Comment by archon810** [comment]
We'd like to use microseconds and are running into the same issue. Can we give this one a bump please?

**Comment by archon810** [comment]
Bueller?

**Comment by archon810** [comment]
To be released in 7.10.0 and 8.0.0, correct?
