### ISSUE TITLE
Docs: Clarify how to store a search template

### ISSUE THREAD

**Issue by kat257** [elastic/elasticsearch#42530]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-search-template.html

Clarify in search template doc where it refers to storing a search template in a **Note** as a preregistered template (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#pre-registered-templates). Clarify example for storing a search template.  Add link as appropriate from **How to use scripts** doc.

**Comment by kat257** [comment]
@untergeek, would you take a look at the issue I've opened and see if you see it the way I do? I think that "storing a search template" is in the preregistered template section, referenced from a link inside a note. If I am not understanding the problem, I will update this issue.

**Comment by untergeek** [comment]
We currently have no example or documentation on how to store a search template. This ought to be in the scripting docs as well as the search template docs. They can be linked together however you see appropriate.

**Comment by untergeek** [comment]
## This is how to store a search template
```
POST _scripts/my_search_template
{
  "script": {
    "lang": "mustache",
    "source": {
      "query": {
        "match": {
          "{{my_field}}": "{{my_value}}"
        }
      }
    }
  }
}
```

## This is how to search against a stored template

```
GET my_index/_search/template
{
  "id": "my_search_template",
  "params": {
    "my_field": "fieldname",
    "my_value": "expected value"
  }
}
```

## The problem
The current documentation has examples of _searching_ with a stored search template, but none on how to actually store one.

**Comment by jrodewig** [comment]
@untergeek I opened #45817 to address this. My hope is that it'll help by adding an explicit search template reference section to our Scripting docs. It also rearranges and retitles the examples in Search Templates so storing and searching search templates is more prominent.

Please feel free to leave feedback!
