### ISSUE TITLE
range query is not working in elasticsearch JAVA Client API

### ISSUE THREAD

**Issue by yamunabm** [elastic/elasticsearch#42599]
Hello,

I am using ES 6.6.0 version.
I have two indices, both the indices have the fallowing field :
"ts": {
            "type": "date"
          }

able to query from one index and not from the other.

If i execute the below query through ES curl API then it works but it is not working when i execute the same query through java client API
`{
          "range": {
            "ts": {
              "from": 1559001262497,
              "to": 1559009262497,
              "include_lower": true,
              "include_upper": true,
              "boost": 1.0
            }
          }
        }`

Please suggest what could be the reason
Thanks
Yamuna

**Comment by cbuescher** [comment]
Hi again @yamunabm, as stated in the other issue recently opened by you, we prefer the support forums at https://discuss.elastic.co for general usage questions like this. Github issues should be used for bug reports and feature requests, so I'm closing this as well encourage you to ask this question in the forum instead.
