### ISSUE TITLE
Aggregations are not working in ES when doc_values=false

### ISSUE THREAD

**Issue by yamunabm** [elastic/elasticsearch#42597]
Hello,

1. Initially we were using ES 2.4.1 and doc_values=false for long datatype:
   and Aggregations were fine with the below configuration.
   "ts": {
          "norms": {
            "enabled": false
          }, 
          "index": "not_analyzed", 
          "type": "long",
          "doc_values":false
        }
2. Upgraded ES version to 6.6.0 and Aggregations are not working with the below configurations :
"ts": {
          "type": "long",
          "doc_values":false
        }

When we saw field data says its disabled on text field but not for long. Why aggregations are not working then.

Thanks

**Comment by cbuescher** [comment]
@yamunabm aggregations need doc_values to be turned on. [Fielddata](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html) should only be possible and necesssary for text fields, if aggregations are required. For long fields you need to enable doc_values in 6.6.0. If you have further questions, please use our support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by yogeshbelur** [comment]
Hi

Is this a compatibility ? I dont find any document in ES says field data being disabled for non text fields in ES.
