### ISSUE TITLE
[GEO] GeoShape.orientation response value

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch#42608]
What is the expected response value for `GeoShape.orientation`? Should it be the same as the ingested one, e.g. `orientation: ccw` or is the orientation value changed internal to e.g. `right` and hence returned?

Thanks in advance :)

https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
