### ISSUE TITLE
Default boost added of 2.2?

### ISSUE THREAD

**Issue by slumx** [elastic/elasticsearch#42625]
**Describe the feature**:

**Elasticsearch version**: 7.1

**Plugins installed**: [ICU]

**JVM version**: 9.0.1

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
When no boost is added (index or query) the explanation still says there is a boost 
of 2.2.

**Steps to reproduce**:
follow the steps described here 
https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-create-index.html
and here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-query-document.html
and do a query with explain
```
GET /customer/_search?pretty=true&q=doe&explain=true
```
Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by slumx** [comment]
Ok, maybe the title was wrong. I don't want a default boost. When doing nothing ES or Lucene adds a boost of 2.2, this seems like a bug?

**Comment by slumx** [comment]
Figured it out, i think?. It seems that lucene removed (k1 + 1) from the bm25 similarity, so this os added as a boost instead in ES. 
see https://issues.apache.org/jira/browse/LUCENE-8563
