### ISSUE TITLE
How to split single document array into multiple documents?

### ISSUE THREAD

**Issue by douniwan5788** [elastic/elasticsearch#42622]
How to split
```
/index_from/1
{
    "foo": [
        1,2,3,4
    ]
}
```
into
```
/index_to/1
{
    "bar": 1
}
/index_to/2
{
    "bar": 2
}
/index_to/3
{
    "bar": 3
}
/index_to/4
{
    "bar": 4
}
```
I can use [ Watcher APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/watcher-api.html) `index action` to achive this, but I can't avoid overriding already exist `index_to` document with same `_id`. is there a way to do a `"update action"` or `"upsert action"` by  Watcher APIs ? or any better idea?

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
