### ISSUE TITLE
Replace internal table with external idf table

### ISSUE THREAD

**Issue by oldJonny** [elastic/elasticsearch#42634]
I got one problem:
The idf value calculated by es is not what I want since my whole data is corresponding to one specific industry(insurance firm actually). More specifically, those quite important keywords appeared so many times that their idf values are very low.

Therefore, may I ask is there any way to replace the internal idf table with my own prepared idf table directly? 

Thx a lot, guys

**Comment by oldJonny** [comment]
In other words, may I change the value of term.docFreq ?

**Comment by cbuescher** [comment]
No, you cannot do this without rolling your own [Lucene similarity](https://lucene.apache.org/core/7_0_0/core/index.html?org/apache/lucene/search/similarities/Similarity.html) implementation (or [tweak one of the existing ones](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html) if thats possible, but this is pretty much a danger zone). I would strongly advise using one of the [existing ones](https://www.elastic.co/guide/en/elasticsearch/reference/current/similarity.html) and tweak the relevance of certain terms e.g. by boosting those terms in your application. The later is a question better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
