### ISSUE TITLE
Remove the transport client

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#42638]
Before 5.0, the transport client (or "java client") was the only official way from java to connect to an Elasticsearch cluster. In 5.0, the low level rest client was added, in 6.0 the high level rest client, and in 7.0 the HLRC was made feature complete (most apis are implemented). Also in 7.0, the transport client was deprecated, in favor of the high level rest client.

This is a meta issue to track removal of the transport client from 8.0. In addition to the actual removal, there are several cleanups that become possible like removing many of the request builder classes, as most are not used for internal node-to-node requests.

**Comment by rjernst** [comment]
The transport client has been removed. Any leftover remnants can be remove as they are found.

**Comment by deanjo** [comment]
Hello ~
I want to know why remove tansport client . HTTP1.1 that I know uses the text protocol and does not support multiplexing , so I think there is a huge performance difference between jest client and tansport client in high concurrency scenarios
