### ISSUE TITLE
[CI] LangMustacheClientYamlTestSuiteIT.test {yaml=lang_mustache/30_search_template/Test with new response format} failed

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#42664]
`LangMustacheClientYamlTestSuiteIT.test {yaml=lang_mustache/30_search_template/Test with new response format}` failed on my PR build and seems unrelated:

https://scans.gradle.com/s/axrx54rul6s3c/tests/wvxejxkegxw3s-v3qw2yd63iq4w

```
java.lang.AssertionError: 
Failure at [lang_mustache/30_search_template:148]: hits.total.value didn't match expected value:
              hits.total.value: expected [0] but was [1]
```

Did not reproduce locally with the reproduction line.

**Comment by talevy** [comment]
popped up in my PR test run as well. muting this test here #42730
