### ISSUE TITLE
Multiple test failures related to openldap 

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#42672]
On 6.8 intake build there were multiple failures related to openldap
https://scans.gradle.com/s/zdiv57ecxvhxw
```
Error Message
Expected the actual value for port 636 to be in system property test.fixtures.openldap.tcp.636
Stacktrace
java.lang.AssertionError: Expected the actual value for port 636 to be in system property test.fixtures.openldap.tcp.636
	at __randomizedtesting.SeedInfo.seed([8E80842EF7F9652:C78C4FBFF0809A5C]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.elasticsearch.test.OpenLdapTests.getFromProperty(OpenLdapTests.java:301)
	at org.elasticsearch.test.OpenLdapTests.<clinit>(OpenLdapTests.java:51)
	at 
```
does not reproduce for me
```
./gradlew :x-pack:qa:openldap-tests:unitTest -Dtests.seed=8E80842EF7F9652 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.OpenLdapUserSearchSessionFactoryTests -Dtests.method="testUserSearchWithBindUserOpenLDAP" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=EET -Dcompiler.java=12 -Druntime.java=8
```

**Comment by jkakavas** [comment]
Hey @mark-vieira , could this have to do something with your changes to the TestFixturesPlugin in #42649 yesterday?

These ports should have been set as system properties by `TestFixturesPlugin#configureServiceInfoForTask`

**Comment by mark-vieira** [comment]
#42649 wasn't backported to 6.8 so that would be unrelated here.

Looks like the 6.8 intake builds have been fine since that one failure so I think this was just some kind of Docker compose hiccup. I'm going to close this for now. Feel free to reopen if this occurs again.

**Comment by craigtaverner** [comment]
Happened once today https://gradle-enterprise.elastic.co/s/vnzhyefc6muno/tests/:x-pack:qa:openldap-tests:test/org.elasticsearch.xpack.security.authc.ldap.OpenLdapUserSearchSessionFactoryTests/testUserSearchWithBindUserOpenLDAP?top-execution=1

Since this only happened once, and this issue is from 2019, I will not open the issue again unless I see a second failure.

Also it did not reproduce locally with:

    ./gradlew ':x-pack:qa:openldap-tests:test' --tests "org.elasticsearch.xpack.security.authc.ldap.OpenLdapUserSearchSessionFactoryTests.testUserSearchWithBindUserOpenLDAP" -Dtests.seed=E02AE52B2910766D -Dtests.locale=es-US -Dtests.timezone=MIT -Druntime.java=17
