### ISSUE TITLE
NullPointerException while building on macOS

### ISSUE THREAD

**Issue by a-fatah** [elastic/elasticsearch#42682]
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "11.0.2" 2019-01-15

**OS version** (`uname -a` if on a Unix-like system): Darwin Abduls-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: I am trying to build elasticsearch locally using macOS and I had jdk 8 installed already but it was complaining so I had to install jdk 11 using sdkman but now build process is throwing NullPointerException as mentioned in the logs.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. install java 11 using sdkman on macOS
 2. clone elasticsearch repo
 3. run `./gradlew assemble`

**Provide logs (if relevant)**:
`
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/abdulfatah/Documents/GitHub/elasticsearch/modules/reindex/build.gradle' line: 128

* What went wrong:
A problem occurred evaluating project ':modules:reindex'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

**Comment by a-fatah** [comment]
Here is the stack trace
```
Caused by: java.lang.NullPointerException
        at org.elasticsearch.gradle.BuildPlugin.getJavaHome(BuildPlugin.groovy:329)
```

and JAVA_HOME IS `/Users/abdulfatah/.sdkman/candidates/java/current`

**Comment by jasontedor** [comment]
Hi, this was fixed yesterday. Please pull the latest.

Relates #42630
