### ISSUE TITLE
Facing the cause "cannot evaluate script for expression StringQueryPredicate"

### ISSUE THREAD

**Issue by shubham-agarwal-ngi** [elastic/elasticsearch#42698]
**Elasticsearch version** - 6.6.0
**JVM version** -1.8 
**OS version**  window server 2012 R2

I am running the below query using the xpack api
{
"query":"Select role as \"role\" , sum(customerincome ) as \"sum_customerincome\" FROM message_index where (Query('role:Son') OR Query('role:Wife')) GROUP BY role"	
}

but facing the below error,

"root_cause": [
            {
                "type": "sql_illegal_argument_exception",
                "reason": "Cannot evaluate script for expression StringQueryPredicate[role :Son,]"
            }
        ]

please advice.

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
