### ISSUE TITLE
Some weird or inconsistent behaviour of returning named query

### ISSUE THREAD

**Issue by DevCeN** [elastic/elasticsearch#42697]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.24

**JVM version** (`java -version`): 1.8.0_192

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
When querying with named queries, the expected behaviour is to see the names of the matched queries to appear in the "matched_queries" field in the result ONLY when the named queries are matched. This does not seem to be the case for must_not query type.

**Steps to reproduce**:
1. Create the index
```
{"properties": {"fA": {"type": "text"}}}
```
2. Put a document
```
{"fA": "1"}
```
3. Find a document that must not have field fA (should return nothing):
```
{"query": {
  "bool": {
    "must_not": {
      "exists": {
        "field": "fA",
        "_name": "INSIDE MUST NOT"
      }
}}}}
```
Result (PASS):
```
{"hits": {"hits": []}}
```
4. Find a document that must not have field fB (should return the document with INSIDE MUST NOT):
```
{"query": {
  "bool": {
    "must_not": {
      "exists": {
        "field": "fB",
        "_name": "INSIDE MUST NOT"
      }
}}}}
```
Result (FAIL - **not getting the matched named query**):
```
{"hits": {"hits": [{"_source": {"fA": "1"}}]}}
```
5. Find a document that must have field fA (should return the document with INSIDE EXISTS):
```
{"query": {
  "bool": {
    "must": {
      "exists": {
        "field": "fA",
        "_name": "INSIDE EXISTS"
      }
}}}}
```
Result (PASS - **get the matched named query**):
```
{"hits": {"hits": [{
  "_source": {"fA": "1"},
  "matched_queries": ["INSIDE EXISTS"]
}]}}
```
6. Find a document that must not have field fB **workaround to get the matched named query** (should return the document with both INSIDE MUST NOT and OUTSIDE MUST NOT):
```
{"query": {
  "bool": {
    "must": {
      "bool": {
        "must_not": {
          "exists": {
            "field": "fB",
            "_name": "INSIDE MUST NOT"
          }
        },
        "_name": "OUTSIDE MUST NOT"
      }
}}}}
```
Result (PARTIALLY PASS - **get the matched named query, but not the INSIDE MUST NOT one?**):
```
{"hits": {"hits": [{
  "_source": {"fA": "1"},
  "matched_queries": ["OUTSIDE MUST NOT"]
}]}}
```
7. Find a document that should have field fA but not field fB **with workaround** (should return the document with both named queries):
```
{"query": {
  "bool": {
    "should": [{
      "exists": {
        "field": "fA",
        "_name": "INSIDE EXISTS"
      }},{
      "bool": {
        "must_not": {
          "exists": {
            "field": "fB",
            "_name": "INSIDE MUST NOT"
          }
        },
        "_name": "OUTSIDE MUST NOT"
      }
}]}}}
```
Result (PARTIALLY PASS - **get both the matched named queries but not the INSIDE MUST NOT one?**):
```
{"hits": {"hits": [{
  "_source": {"fA": "1"},
  "matched_queries": ["OUTSIDE MUST NOT", "INSIDE EXISTS"]
}]}}
```
8. Find a document that should have field fA but not field fA **with workaround** (should return the document with just INSIDE EXISTS):
```
{"query": {
  "bool": {
    "should": [{
      "exists": {
        "field": "fA",
        "_name": "INSIDE EXISTS"
      }},{
      "bool": {
        "must_not": {
          "exists": {
            "field": "fA",
            "_name": "INSIDE MUST NOT"
          }
        },
        "_name": "OUTSIDE MUST NOT"
      }
}]}}}
```
Result (FAIL - **Bugged to return INSIDE MUST NOT now?**):
```
{"hits": {"hits": [{
  "_source": {"fA": "1"},
  "matched_queries": ["INSIDE EXISTS", "INSIDE MUST NOT"]
}]}}
```

**Comment by jimczi** [comment]
Named queries execute the query in isolation so in this example:
 ````
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "fB",
                    "_name": "exists"
                }
            }
        }
    }
}
````
the named query is:
````
  "exists": {
     "field": "fB",
      "_name": "exists"
   }
````
which explains why it appears in the `matched_queries` of document that **contains** a field named `fB`. 

The solution, that you already outlined, is to put the named query at the `bool` level in order to take the `must_not` clause into account:
`````

**Comment by DevCeN** [comment]
I get that from your explanation now how the mechanism behind has caused this weird behaviour, as the name is attached to the "field" rather than the "query" itself, which also explained situation 8. above why "INSIDE MUST NOT" appeared in the result. The workaround (or "solution" as you put it), is to use a different construct in order to know whether a `must_not` query is matched or not. Comparing

```
{
  "bool": {
    "must": {
      "exists": {
        "field": "fA",
        "_name": "MUST EXISTS"
      }
}}}
```
to obtain in `matched_queries` that the named query (works for `must`, `should`) matched but the following
```
{
  "bool": {
    "must": {
      "bool": {
        "must_not": {
          "exists": {
            "field": "fB"
          }
        },
        "_name": "MUST NOT EXISTS"
      }
}}}
```
as a "solution" for `must_not` query is very much counter intuitive to use the feature.

Also, when issuing nested `must_not` query, the "solution" above would populate "MUST NOT EXISTS" into the parent `matched_queries` as well as in the nested child's `matched_queries`, is this a bug then?
