### ISSUE TITLE
how to set close auto create mapping when index data?

### ISSUE THREAD

**Issue by jaccborn** [elastic/elasticsearch#42701]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): 1.8.0_212

**OS version** (`uname -a` if on a Unix-like system): Linux VM-0-41-ubuntu 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. i want update es from 5.3.2 to 7.1, i see the doc, the mapping type is remove,and i discover there is no need to create mapping,the es will auto create mapping, but it's not i want, for example,the location  actully i need geo_point type, but auto create mapping is float.

![image](https://user-images.githubusercontent.com/12455286/58625543-4196fc80-8305-11e9-9c79-9118d731c002.png)

in the es 5.3.2  the mapping like 
![image](https://user-images.githubusercontent.com/12455286/58625590-5a9fad80-8305-11e9-8297-dabd86be666b.png)

2.in the past,first i create the mapping, and create the index data,so  i  try to custom create mapping,and it successful, but when i create the index data,it's something wrong.
![image](https://user-images.githubusercontent.com/12455286/58626045-617af000-8306-11e9-9979-71ed78303c5d.png)

i have try the dynamic parameter.but it not go into effect.that look like when create index data, it will be auto create a template mapping.
![image](https://user-images.githubusercontent.com/12455286/58626116-96874280-8306-11e9-8e7e-47e4f1b5d84b.png)

what's more,i can't use mapping api to modify it.

how can i set the mapping autocreate close. i can't find it in doc.

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by jaccborn** [comment]
> Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds
> of things to the [forums](https://discuss.elastic.co/). If you can stop
> by there, we'd appreciate it. This allows us to use GitHub for verified
> bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forums](https://discuss.elastic.co/)
> that should be able to help get an answer to your question. As such, I
> hope you don't mind that I close this.

Thank you for your reply, thank you for your contribution to open source, I wish you a smooth job, happy every day!
