### ISSUE TITLE
ElasticSearch - Shards not splitting equally

### ISSUE THREAD

**Issue by YakobovLior** [elastic/elasticsearch#42704]
Hello,
I'm running an RPM based on-prem cluster with 21 data nodes:
![image](https://user-images.githubusercontent.com/33580144/58627915-097dc280-82e1-11e9-8342-bf77afb7b10c.png)

As shows, one node specifically has very high load, while logstashes complaining on bulk retries issue due to many writes to this node:
![image](https://user-images.githubusercontent.com/33580144/58628046-61b4c480-82e1-11e9-9fd9-08d462395ef4.png)

Correspondingly, this node gets excessive GC operations: (data nodes are 30GB heap, CMS GC)
![image](https://user-images.githubusercontent.com/33580144/58628136-a2acd900-82e1-11e9-93ef-24d12b857f98.png)

So I wrote a short script to see the spread of active shards (from today which getting writes) among the cluster, and for some reason us-elkdb15 is having much more indices than the others:
![image](https://user-images.githubusercontent.com/33580144/58628628-e94f0300-82e2-11e9-9dec-b63c6237b443.png)

Any explanation to this behavior? the high load on this node causes significant performance issues to the cluster.

Thanks,
Lior

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
