### ISSUE TITLE
High Level Rest Client should return the @timestamp in specified time zone when a query is performed..

### ISSUE THREAD

**Issue by Ravindranath2511** [elastic/elasticsearch#42705]
High Level Rest Client should return the **@timestamp** or any date type field data in specified time zone when a query is performed. As of now the timezone returned is UTC which can be parsed. But it will be useful if the specified timezone is returned.

**Comment by jasontedor** [comment]
Hi @Ravindranath2511, a reproducible example would help us understand your intentions. It makes it easier for us to reason about what you're asking about, and if we agree that the change should be made, ensures we have fulfilled the requirements of the request. Can you clarify through a reproducible example?

**Comment by Ravindranath2511** [comment]
When i create a search request and execute queries, for example:
`SearchRequest searchRequest = new SearchRequest("indexName");
SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
searchSourceBuilder.query(QueryBuilders.matchAllQuery());
searchRequest.source(searchSourceBuilder);
SearchResponse searchResponse = client.search(searchRequest, RequestOptions.DEFAULT);
SearchHits hits = searchResponse.getHits();
SearchHit[] searchHits = hits.getHits();
for (SearchHit hit : searchHits) {
System.out.println("Response:" + hit);
}`

This search request of matchAllQuery give me a response of:
`Response:{
  "_index" : "indexName",
  "_type" : "doc",
  "_id" : "1022557",
  "_score" : 1.0,
  "_source" : {
    "type" : "databaselog",
    "@timestamp" : "2019-05-24T11:11:42.393Z",
    "currtime" : "2019-05-23T17:01:34.000Z",
    "@version" : "1"
  }
}`

In  the response of Search request @timestamp and currtime are DATE type of fields and they are received in UTC time zone.
So, I am suggesting to make user to specify the timezone of the DATE type fields in the response.
For example,
If i want all the DATE type fields in the response hits to show in UTC+5:30 time zone, all the DATE type fields should automatically change to the UTC+5:30 time zone.

**Comment by dadoonet** [comment]
Elasticsearch never changes the _source document. It's sent back as you ingested it.

**Comment by jasontedor** [comment]
Thanks for clarifying so that we can understand the issue more completely before responding. As @dadoonet mentions, we *never* modify source, so what you put is what you get, `_source` comes back exactly as the document that was indexed.

**Comment by Ravindranath2511** [comment]
@dadoonet @jasontedor , I am using 6.8.0 ELK version and the DATE type field changes its timezone in the response hits. Below is the image of the same document in KIBANA which is in the browser timezone:
![InkedJustification001_LI](https://user-images.githubusercontent.com/30999772/58681511-523d8600-838a-11e9-9a34-73fa39e56104.jpg)

**Comment by dadoonet** [comment]
> its timezone in the response hits.

I think that if you click on the small arrow and look at the JSON, you will see the "original" value. Am I correct?

If so that's clearly an end user modification which is happening after the response is sent by Elasticsearch. I mean that Kibana did that for you. It's not elasticsearch responsability IMHO.

**Comment by Ravindranath2511** [comment]
@dadoonet Yes, i agree with you that when i see it in kibana(DISCOVER TAB) it shows my timezone(browser's). But when i query for the same document using JHLRC or DEV TOOLS(in kibana) it gives me UTC time zone as i mentioned above comment.

Please go through the below response from the DEV TOOLS(kibana):
`{ "_index" : "test_errorlog", "_type" : "doc", "_id" : "1022557", "_version" : 1, "_seq_no" : 7382, "_primary_term" : 1, "found" : true, "_source" : { "type" : "databaselog", "@timestamp" : "2019-05-24T11:11:42.393Z", "currtime" : "2019-05-23T17:01:34.000Z", "@version" : "1" } }`

Please go through the below response from the JHLRC query:
`Response:{ "_index" : "indexName", "_type" : "doc", "_id" : "1022557", "_score" : 1.0, "_source" : { "type" : "databaselog", "@timestamp" : "2019-05-24T11:11:42.393Z", "currtime" : "2019-05-23T17:01:34.000Z", "@version" : "1" } }`

In the above responses the **currtime** and **@timestamp** fields are displayed in UTC timezone.

And below is response in the DISCOVER TAB(kibana):
![InkedJustification001_LI](https://user-images.githubusercontent.com/30999772/58720918-1ee21200-83f1-11e9-89a0-299d08d861cf.jpg)
In this response(DISCOVER TAB) browser's time zone is used. So it is displayed correctly.

I am suggesting that there should be a mechanism that, While quering a doc or index(using JHLRC or DEV TOOLS), user should be able to specify the timezone. So by that specified time zone elasticsearch should automatically convert the DATE type fields in the response doc(s) to the user specified timezone and get displayed. By this we can eliminate manual date parsing in JHLRC powered applications.
