### ISSUE TITLE
Elasticsearch 6.7.1 query string shows documents that do not have specified key

### ISSUE THREAD

**Issue by misrasuraj** [elastic/elasticsearch#42743]
Elastic version: 6.7.1

Plugins installed: Defaults

JVM version: jdk1.8.0_191

OS version: Windows 10

I am using the query string to get some documents. After executing the query string, in addition to the actual documents, it gives those documents also which does not have the key against which data is filtered. This was not the case when I was using 6.4.2 elastic version. The official site does not have any information regarding that.

My query looks like - "* AND ( properties.foreignKeys.referenceTableId :(file_datatypes) OR properties.primaryKeyMetadata.referenceTables :(file_datatypes) )". It shows the documents that has properties.foreignKeys: null and properties.primaryKeyMetadata: null, in json

**Comment by matriv** [comment]
Could you please run the query with explain using a matching document: https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-explain.html

**Comment by misrasuraj** [comment]
I am using alias search and when I used explain it throws exception: 
"type": "illegal_argument_exception",
 "reason": "no write index is defined for alias [discovery]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
---------------------------------
Just to show the insight of the object that I am getting for above query:
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 8,
    "successful": 8,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 2.5606477,
    "hits": [
      {
        "_index": "dedb57e2-31f5-4fe9-b190-f993ffa58296",
        "_type": "dedb57e2-31f5-4fe9-b190-f993ffa58296",
        "_id": "file_datatypes",
        "_score": 2.5606477,
        "_source": {
          "@type": "Entity",
          "id": "file_datatypes",
          "name": "datatypes",
          "nameInSource": "datatypes",
          "type": "Table",
          "searchable": true,
          "properties": {
            "@type": "TableProperty",
            "sourceId": "file",
            "createdDateTime": 1559316108959,
            "lastUpdatedDateTime": 1559316108959,
            "aliases": null,
            "tags": null,
            "dataSourceConnectionName": "file",
            "dataSourceConnectionType": "Flat File",
            "entitySchemaPropertiesMap": null,
            "entityTranslatorPropertiesMap": null,
            "sourceConnectionName": "file",
            "schema": "",
            "childNames": [
              "name",
              "item_name"
            ],
            "sourceType": "Connection",
            "childIds": [
              "file_datatypes_name",
              "file_datatypes_item_name"
            ],
            "foreignKeys": null,
            "primaryKeyMetadata": null,
            "relationshipObjectList": []
          },
          "version": 0,
          "entityAdditionalInfo": null
        }
      }
    ]
  }
}

**Comment by misrasuraj** [comment]
The query was "* AND ( properties.foreignKeys.referenceTableId :(file_datatypes) OR properties.primaryKeyMetadata.referenceTables :(file_datatypes) )" So if you see above json here "foreignKeys": null,
"primaryKeyMetadata": null but still I get this document.

**Comment by misrasuraj** [comment]
One more observation, Since I am using the alias to fetch the records from several indexes in one go. Few of the indexes do not have the mapping information for the field that is used in the query string and this issue is occurring only for those indexes.

**Comment by jimczi** [comment]
> Since I am using the alias to fetch the records from several indexes in one go. Few of the indexes do not have the mapping information for the field that is used in the query string and this issue is occurring only for those indexes.

Ok then you might be affected by this bug:
https://github.com/elastic/elasticsearch/issues/41022

It is fixed in `6.7.2` so can you try to upgrade and see if this fixes the issue ?

**Comment by romseygeek** [comment]
@misrasuraj can you get the full stack trace from the `illegal_argument_exception` you were seeing when using `explain`?  That sounds like a different bug that we need to look into.

**Comment by jimczi** [comment]
No feedback, hence closing. Please reopen if you can reproduce in a more recent version.
