### ISSUE TITLE
Adding an output example and output description for slowlog would be useful for users

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#42746]
**Adding an output example and output description for slowlog would be useful for users**
In [current slowlog documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html) 
there are explanation about logger configuration but no examples or explanations about the actual output. I believe this can help users to better use the log

One interesting point to consider is giving an example with `x-opaque-id` in order to explain how this client header can be used to trace the source of slow queries

**Comment by pgomulka** [comment]
@yaronp68 I totally missed this issue - I have slightly improved the docs on slowlogs and deprecation
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/index-modules-slowlog.html
deprecation section:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/logging.html
Let me know if that is good enough? Can we improve?

**Comment by wchrisdean** [comment]
[doc issue triage]
