### ISSUE TITLE
Elasticsearch 7.1.1 disable _source don't reduce storage space

### ISSUE THREAD

**Issue by discolt** [elastic/elasticsearch#42747]
**Elasticsearch version** : 7.1.1
**Plugins installed**: default
**JVM version** (`java -version`): JDK8
**OS version** : MACOS

**Description of the problem including expected versus actual behavior**:

Test index storage physical spaces cost for the same schema and data with different settings .

w_default： with all default settings
w_best_compression： addition  best_compression for _source
w_default_no_source:  disable _source store

![image](https://user-images.githubusercontent.com/1684341/58695597-5ee0cf00-83c8-11e9-9c8d-fd719080bff5.png)

We found no_source index was no significant reduction in storage overhead. But settings actually works.
![image](https://user-images.githubusercontent.com/1684341/58695670-90599a80-83c8-11e9-9c2b-ea49b4f336fb.png)

**Comment by matriv** [comment]
Hi @discolt,

This a question better suited to the support forums at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Would be great if you could also provide the
mappings for those indices.

Many thanks.
