### ISSUE TITLE
io.netty.buffer.PoolArena$HeapArena Biggest object?  why? version is 5.2.0

### ISSUE THREAD

**Issue by jiafeijiang** [elastic/elasticsearch#42755]
![image](http://res.in.goldenmob.com/img/61f6139bd31c44598c95c2308ad17c32/58a95c1975cb4f18ad98e52cc598d242.jpg)

**Comment by matriv** [comment]
Hi @jiafeijiang,

- This a question better suited to the support forums at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. 

- Moreover, your question currently is lacking context. Please include information regarding your cluster setup and configuration, along with your network layout and configuration. 

- It would be also helpful to provide some information regarding the workload against your cluster: are you doing indexing/updates/queries and how many concurrent clients are doing each?

- Are you using any specific app (e.g.: some other product from the elastic stack) for the data ingestion?

Thank you!
