### ISSUE TITLE
Boosting context suggestions using decimal numbers results in parse exception

### ISSUE THREAD

**Issue by fucking-signup** [elastic/elasticsearch#42776]
**Elasticsearch version**: 7.0.1

**Plugins installed**: []

**JVM version**: 1.8.0_141

**OS version**: Darwin iMac.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

When using a context suggester, an exception is raised when using decimal numbers in boost field at query time. However, it works just fine with the whole numbers.

It is expected that boosting using decimal numbers would work as it helps to decrease scores of irrelevant documents for example by applying a boost of `0.00001`.

**Steps to reproduce**:

1. Create a mapping
```
PUT /tags
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "suggest": {
        "type": "completion",
        "contexts": [
          {
            "name": "used_by_blog_ids",
            "type": "category"
          }
        ]
      }
    }
  }
}
```

2. Index a document
```
PUT /tags/_doc/1
{
  "suggest": {
    "input": "Best practices",
    "weight": 3,
    "contexts": {
      "used_by_blog_ids": [
        "1",
        "2"
      ]
    }
  }
}
```

3. Search
```
POST /tags/_search 
{
  "suggest": {
    "property_suggestion": {
      "prefix": "bes",
      "completion": {
        "field": "suggest",
        "size": 10,
        "contexts": {
          "used_by_blog_ids": [
            {
              "context": "1",
              "boost": 0.0001
            }
          ]
        }
      }
    }
  }
}
```

Would result in:

```
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "category context must be a string, number or boolean"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "tags",
        "node": "d3JT7BIRRNCKHozgQ1o27g",
        "reason": {
          "type": "x_content_parse_exception",
          "reason": "category context must be a string, number or boolean"
        }
      }
    ],
    "caused_by": {
      "type": "x_content_parse_exception",
      "reason": "category context must be a string, number or boolean",
      "caused_by": {
        "type": "x_content_parse_exception",
        "reason": "category context must be a string, number or boolean"
      }
    }
  },
  "status": 400
}
```

**Comment by jimczi** [comment]
The parser expects an integer which is why the exception is thrown. However the underlying query handles boost values as floats so technically it shouldn't be difficult to support. Though I wonder why you'd need this since you can also use big boosts on contexts that are more important ?

**Comment by fucking-signup** [comment]
I think the problem is that context suggesters don't have something like `must_not` filter, so I tried applying boosts with decimal numbers as a workaround.

Let's consider a group chat:

We need an autocomplete when adding new members to the chat. Autocomplete should suggest only members that aren't in this group chat already. We could've stored chat ids as a context where users are members of the chat and then simply filtered all users that are members of the chat from suggestions.

Something like `must_not` filter would've been an easy solution to this problem, we just need to exclude 1 chat id.

**Comment by jimczi** [comment]
> Something like must_not filter would've been an easy solution to this problem, we just need to exclude 1 chat id.

The completion suggester considers each context independently so it is not possible to filter contexts based on suggestions that appear in another one (`must_not`). If you need to apply boolean logic to your suggestions you should use a regular field and the `bool` query to apply the logic you want.

**Comment by fucking-signup** [comment]
That's what I was initially trying to do but the documentation mentioned that there is a better solution for autocomplete and it was a completion suggester (and context suggester).

I see there is a new `search_as_you_type` field type landed in ElasticSearch 7.2, looks like it better suits my needs and I will give it a try.

Thanks for the help :)

**Comment by cbuescher** [comment]
@jimczi is this (allowing decimal numbers for context boosts) something we want to pursue further or do you think we can close this issue? I'd be leaning to the later since there seem to be other ways achieving the goal here.

**Comment by jimczi** [comment]
+1 to close, I don't see a lot of traction for this feature ;).
