### ISSUE TITLE
[DOCS] ES Upgrade table formatting is broken

### ISSUE THREAD

**Issue by jaijhala** [elastic/elasticsearch#42805]
This is in regards to the Elasticsearch upgrade table documented here - https://www.elastic.co/guide/en/elasticsearch/reference/6.8/setup-upgrade.html

It looks like for all 6.x versions, it shows up like this - 

<img width="784" alt="Screen Shot 2019-05-31 at 4 29 09 PM" src="https://user-images.githubusercontent.com/16711084/58740020-a82e2000-83c2-11e9-8402-0bcbde66d145.png">

Whereas for 5.x versions, it shows up nicely like - 

<img width="760" alt="Screen Shot 2019-05-31 at 4 28 41 PM" src="https://user-images.githubusercontent.com/16711084/58740028-b7ad6900-83c2-11e9-8649-b95c46f92e47.png">

I wonder if it's related to the Docs build transition that we did recently. 

--Jai

**Comment by jrodewig** [comment]
This is a variation of the issue solved with elastic/elasticsearch/42254. For whatever reason, I didn't catch this in the 6.x branches.

Fixed with https://github.com/elastic/elasticsearch/commit/19e3d5e21e52eebfcdd9b0f675bb293352d73560

Will close after I can confirm the changes are live.

**Comment by jrodewig** [comment]
This is fixed from 6.0 to 6.x now.
