### ISSUE TITLE
Sorting nested_filters don't cache filters properly

### ISSUE THREAD

**Issue by henryptung** [elastic/elasticsearch#42813]
The problem seems to originate in v5.x. I can submit a PR later today with the proposed fix, but would request a backport to v6.x (ideally, v6.4.x) specifically since that's what we're currently building against (not sure what the procedure is for backported fixes).

**Elasticsearch version** (`bin/elasticsearch --version`): v6.4.0

**Plugins installed**: [search-guard](https://github.com/floragunncom/search-guard), custom internal plugins

**JVM version** (`java -version`):
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux <hostname> 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Oct 9 17:27:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

Expect nested filters under `sort` to reuse already-computed filter entries in the query cache (considering [recommendation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting) to repeat query filter under sort). Instead, nested filters are recomputed into the [Lucene default cache](https://github.com/apache/lucene-solr/commit/db6083e2557dbf137f5f91ed4c085ebb886f67e4) due to the following change:

https://github.com/elastic/elasticsearch/commit/a4b5fbedb886f85837a48c4a895f9c7d9a8c4094

This causes extra cache churn and poor performance. For reference, when testing with a fork of ES 6.4.0 pushing the ES query cache down through `QueryShardContext`, performance improved from ~22 seconds to ~3-4 seconds on a heavy query.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create any index with a nested mapping containing a sortable (e.g. numeric) field.
 2. Index documents with IDs `row-{i}`, each with two subdocuments with field values `{i}` and `-{i}`.
 3. Set breakpoint on [this line](https://github.com/elastic/elasticsearch/commit/a4b5fbedb886f85837a48c4a895f9c7d9a8c4094#diff-027f5b2091ccafba0df417a1c7db46a8R149).
 3. Issue queries filtering for and sorting on subdocuments with positive values only. Repeat until caching occurs.
 4. Observe the default Lucene query cache being used, rather than the `ElasticsearchLRUQueryCache`.

**Comment by jimczi** [comment]
Good catch @henryptung ! I agree that we should use the ES query cache in the searcher that is used for nested sort filter. 

> The problem seems to originate in v5.x. I can submit a PR later today with the proposed fix, but would request a backport to v6.x (ideally, v6.4.x) specifically since that's what we're currently building against (not sure what the procedure is for backported fixes).

Thanks and please open a pr on master first so that we can backport afterward. However we release only patch version in 6x so 6.4.x won't be possible but we can discuss whether we should backport to 6.8.x (the latest version in this major) when the fix is ready.

**Comment by henryptung** [comment]
@jimczi Hey, so there are some delays on my end regarding CLA stuff, but would it be possible for you or an ES dev to make the change instead? It's pretty straightforward, basically just about piping down a hook for initializing query cache + caching strategy through `QueryShardContext`.

On a separate side note, we also just ran into https://github.com/elastic/elasticsearch/commit/3d5f113ada63b9175631e6ad1ef1645dc8f5f275 - if you make a v6.8.x patch release, would humbly request a backport of that fix as well.

**Comment by henryptung** [comment]
@jimczi Actually, sorry for unfamiliarity here - what's the usual cadence for legacy patch releases? Just curious re: scheduling whether we should wait for an artifact or try to hack around it in the meantime.

**Comment by jimczi** [comment]
This [link](https://www.elastic.co/fr/downloads/past-releases#elasticsearch) should give you an idea of the cadence of releases, however we don't communicate around release dates so I can only say that we would like to release 6.8.1 "soon".
