### ISSUE TITLE
Skip processing queries sitting in the queue beyond a timeout

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#42837]
ES often doesn't knows automatically when a client request times out, but if the client tells the ES what timeout it plans to use, this information can be used to protect the service from brown-outs as when the backlog is huge clients might timeout and issue a retry wasting useful work already done and re-issuing a fresh request thereby flooding the queue.
The idea is to to reject a request if it stays in the queue beyond a request time-out (indicative of the timeout configured at client)

**Comment by Bukhtawar** [comment]
Another option that might make sense would be to allow clients to switch to a LIFO search queues instead of starting to reject requests

**Comment by javanna** [comment]
The search API as well as other APIs support automatic cancellation on connection close. Elasticsearch does not need to know what the client timeout is, but it reacts to the underlying connection being closed by cancelling all the related tasks. I believe this achieves the same goal described in this issue.
