### ISSUE TITLE
CreateIndexRequest with waitForActiveShards(ActiveShardCount.ALL) times out

### ISSUE THREAD

**Issue by nov1n** [elastic/elasticsearch#42846]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1.

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "11.0.1" 2018-10-16

**OS version** (`uname -a` if on a Unix-like system): 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
The create index request with `waitForActiveShards(ActiveShardCount.ALL)` times out with exception: `Exception in thread "main" java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]`.

Setting wait `waitForActiveShards` to `ActiveShardCount.DEFAULT`, or 1 works.

**Steps to reproduce**:

Step 1:
`docker run -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.1.0`

Step 2:
```
package com.mycompany.app;

import java.io.IOException;
import java.util.UUID;
import org.apache.http.HttpHost;
import org.elasticsearch.action.support.ActiveShardCount;
import org.elasticsearch.client.RequestOptions;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.client.indices.CreateIndexRequest;
import org.elasticsearch.client.indices.CreateIndexResponse;
import org.elasticsearch.common.xcontent.XContentType;

public class Repro {
  private static RestHighLevelClient client;

  public static void main(String[] args) throws IOException {
    String index = "{\"settings\":{\"number_of_shards\" : 1, \"number_of_replicas\": 1}}";
    HttpHost elasticsearchHost = new HttpHost("localhost", 9200);
    client = new RestHighLevelClient(RestClient.builder(new HttpHost(elasticsearchHost)));

    CreateIndexResponse response =
        client
            .indices()
            .create(new CreateIndexRequest(UUID.randomUUID().toString())
                    .waitForActiveShards(ActiveShardCount.ALL)
                    .source(index, XContentType.JSON),
                RequestOptions.DEFAULT);
  }
}
```

Step 3: Wait 30 seconds for it to time out.

**Provide logs (if relevant)**:
```
{"type": "server", "timestamp": "2019-06-04T12:42:28,382+0000", "level": "INFO", "component": "o.e.c.m.MetaDataCreateIndexService", "cluster.name": "docker-cluster", "node.name": "94911a5e9a71", "cluster.uuid": "CCOmnb5lSdOW3ZndJtkL1w", "node.id": "Q4I86GN9RyS405upH84n5w",  "message": "[a5d1c328-83fc-44d6-abf2-1cbb1969eb2c] creating index, cause [api], templates [], shards [1]/[1], mappings []"  }
```

**Comment by jasontedor** [comment]
Heya, you've started a single node, yet you're asking for there to be a replica (which will never be able to be assigned, since you only have a single node). Therefore not all shards can be active, so the all condition in wait for active shards all can not be met. The request times out waiting for this to happen, which per the previous, is expected. If you have additional questions, please use the forums as we reserve GitHub for bug reports and feature requests.
