### ISSUE TITLE
[ML] Check for missing delete tasks and recreate during nightly maintenance

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#42840]
When an ML job is deleted a task is created to delete all the things that need deleting.  However, this is not a persistent task, only a node-specific task.  If the node running that task is shut down before the deletion completes then the job is left in a partially deleted state.

One option to fix this would be to make the deletion task a persistent task.  However, this is a huge amount of development work.

A simpler alternative could be to have the nightly maintenance action check for jobs in the `deleting` state that don't have a corresponding deletion task, and start a new deletion task for them.

**Comment by benwtrent** [comment]
>A simpler alternative could be to have the nightly maintenance action check for jobs in the `deleting` state that don't have a corresponding deletion task, and start a new deletion task for them.

I am all for that. 

A persistent task seems like overkill.
