### ISSUE TITLE
[ML] record `lat_lon` detector results as geo_point 

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#42862]
When writing back `actual` and `typical`, the mapping is a `double` for the `record` result type. This means that even if `lat_long` detector was being used, the results could not be queried via any of the supported geo functionality in ES.

Making `actual` and `typical` a multi-mapped field where one is `geo_point` would cause parsing issues as the expected format between a `double` and a `geo_point` differ.

We may need to add a new field `actual_geo` and `typical_geo` that has a `geo_point` mapping. If we do this, then `record` entries would be able to be queried and aggregated as regular geo points.

**Comment by droberts195** [comment]
Fixed by #47050
