### ISSUE TITLE
Enable building with the JDK 13 compiler

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#42895]
We continually advance to the latest compiler as new versions of the JDK are released. However, we are prevented from trying to build with JDK 13 at this time since Gradle does not yet support JDK 13 (gradle/gradle#8681). This is a placeholder to enable building with the JDK 13 compiler when upstream addresses the issues that are preventing Gradle from supporting JDK 13.

Relates 18e74cb92e4cf977d5a117941d818e11ea35d031

**Comment by atorok** [comment]
Look like JDK 13 will be supported in Gradle `6.0` only, due in a couple of months.

**Comment by mark-vieira** [comment]
We're no longer blocked on this since we've upgraded to Gradle 6.0.

**Comment by jasontedor** [comment]
I opened #50004.

**Comment by jbaiera** [comment]
Leaving a comment here regarding compatibility with ES-Hadoop. I'll start testing on JDK 13 for the master branch (hopefully Scala behaves). Will the 7.x branch build tools jar retain its current compiled-for version?

**Comment by jasontedor** [comment]
@jbaiera Yes.

**Comment by jbaiera** [comment]
Testing Java 13 with the ES-Hadoop build is done. All green!
