### ISSUE TITLE
FsRepositoryTests#testSnapshotAndRestore reproducibly fails

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#42905]
Only two failures I can see so far but this reproduces locally with the reported reproduction line:

**master:** https://scans.gradle.com/s/iyzbahgiwlozo/tests/nfxodyych4uas-q3xmc2ojf2vps
**7.x:** https://scans.gradle.com/s/623accnw2wayg/tests/nfxodyych4uas-q3xmc2ojf2vps

**Comment by mark-vieira** [comment]
Test has been muted in both `master` and `7.x`.

**Comment by original-brownbear** [comment]
Doesn't look like this was introduced by a very recent change, it fails all the way back to `7.2`, tracking it down now.

**Comment by mark-vieira** [comment]
Thanks @original-brownbear. There's only been 2 failures in the past 30 days and they both happened this week. Perhaps simply coincidence.

https://build-stats.elastic.co/goto/ea44de95a90f31fa5b9dc5a90fd89a32

**Comment by original-brownbear** [comment]
This is the new test added in https://github.com/elastic/elasticsearch/pull/42213 and it never passed for this seed.

**Comment by original-brownbear** [comment]
So no coincidence there :) it's new.
