### ISSUE TITLE
actionGet  interrupted

### ISSUE THREAD

**Issue by lovelivestyle1102** [elastic/elasticsearch#42918]
when i use the client.prepareGet().execute().actionGet() api to get the result,there is a IllegalStateException future got interrupted.

**Comment by tvernum** [comment]
Hi @lovelivestyle1102
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests. The discussion forums
are beter suited to these sorts of troubleshooting and problem diagnosis
conversations.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

Thank you.
