### ISSUE TITLE
[DOCS] Add Homebrew installation instructions 

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#42914]
Update the installation info to:

- Add brew as an installation option on the main [install page](https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html)
- Add a topic called "Install Elasticsearch on macOS with Homebrew" for the brew instructions and give it the anchor [[brew]]

To use brew to install the stack components, users will first need to “tap” the Elastic Homebrew repo.

**Comment by mcrawshaw** [comment]
Any idea when this will be available for elasticsearch version 8.x?
