### ISSUE TITLE
Add sql rest support for prepared statement

### ISSUE THREAD

**Issue by bputt** [elastic/elasticsearch#42916]
**Describe the feature**:
When issuing an SQL query via REST, it would be helpful to implement prepared statement support to help address potential for malformed queries/sql injection.

Example:
```
{
    "query": "SELECT * FROM mytable WHERE cola = ? and colb = ?",
    "args": [ "foo", "bar" ]
}
```

**Comment by XAKEPEHOK** [comment]
+1 for it. IMHO, without prepared statements, Elastic SQL implemention is not safe in production. I am use only translate API for making native Elastic query

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/45b8bf619aecb1c03d7bc0cf06928dcc36005a66
7.x (7.7.0): https://github.com/elastic/elasticsearch/commit/2908b7e5fcdbee099494f7af8a7192d17aa6f238
