### ISSUE TITLE
Pre-built packages for ppc64le architecture contribution

### ISSUE THREAD

**Issue by junawaneshivani** [elastic/elasticsearch#42926]
Hi all, I have been able to build elasticsearch 6.5.4, logstash 6.5.4 and kibana 6.5.4 from source on ppc64le architecture. I would like to find out how can I contribute to make the .deb packages available for ppc64le architecture here https://artifacts.elastic.co/packages for direct installation. Any help would be highly appreciated.

**Comment by jasontedor** [comment]
Thank you for your interest and offer to contribute. At this time though, we do not intend to support `ppc64le`. We prefer to not take on contributions that we do not intend to support because it can end up being confusing to our users, and it's difficult for us to us maintain.
