### ISSUE TITLE
Add if support for sql query

### ISSUE THREAD

**Issue by bputt** [elastic/elasticsearch#42959]
**Describe the feature**:
It would be helpful to enable support for IF statements in the SELECT portion of the SQL query

Examples:
```
// Straightforward comparison
SELECT IF(colA = 'foo', 'FOO', 'bar') as colA

// Regexp comparison
SELECT IF(colA ~* '.*foo.*', 'FOO', 'bar') as colA

// Like comparison
SELECT IF(colA LIKE '%foo%', 'FOO', 'bar') as colA

// Not like comparison
SELECT IF(colA NOT LIKE '%foo%', 'bar', 'FOO') as colA
```

**Comment by matriv** [comment]
@ebadyano The functionality has been introduced with: #41420.

The function is actually called `IIF` (as in MS-SQL server) and you can find the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/sql-functions-conditional.html#sql-functions-conditional-iif).

Another alternative is to user the ANSI-SQL [CASE](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/sql-functions-conditional.html#sql-functions-conditional-case).

Please pay attention that although the `LIKE/NOT LIKE` are supported, the `~*` is currently not supported.
