### ISSUE TITLE
[DOCS] Add CCR Stats Collector to Monitoring Collectors page

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#42967]
This page lists all Monitoring collectors that run within Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/es-monitoring-collectors.html.

We should add documentation for the CCR stats collector as well, viz. https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/collector/ccr/StatsCollector.java

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
