### ISSUE TITLE
geo_shape orientation always returned as "LEFT" or "RIGHT"

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#43020]
Relates: #42608

**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0. But have tested as far back as 5.6.15

**Plugins installed**: []

**JVM version** (`java -version`):

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Windows 10 Pro 64 bit.

```
> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**Description of the problem including expected versus actual behavior**:

The orientation of a `geo_shape` field datatype mapping is always returned as uppercase `"LEFT"` or `"RIGHT"`, irrespective of the original accepted input value e.g. 

- `"cw"`, `"clockwise"`, `"left"` (and uppercase variants) for `"LEFT"`
- `"ccw"`, `"counterclockwise"`, `"right"` (and uppercase variants) for `"RIGHT"`

A couple of observations:

1. It may be unexpected to return `"LEFT"` or `"RIGHT"` when this is not the original input.
2. Using an uppercase value in the response is a little unusual when compared to other enum values returned by Elasticsearch, which are typically snake cased. ~The only other enum value that I am aware of that is uppercase is [`SimpleQueryStringFlag`](https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/main/java/org/elasticsearch/index/query/SimpleQueryStringFlag.java#L29)~ (there are others). I would have expected the casing of the value in the response to be consistent with other enum values.  

**Steps to reproduce**:

 1. Create index with `geo_shape` field mapping and an orientation `cw`

```json
PUT http://localhost:9200/default_index?pretty=true 
{"mappings":{"properties":{"geo_shape_field":{"orientation":"cw","type":"geo_shape"}}}}
```

 2. Get the index mapping and observe that the `"orientation"` value is `LEFT`

```json
GET http://localhost:9200/default_index/_mapping?pretty=true

{
  "default_index" : {
    "mappings" : {
      "properties" : {
        "geo_shape_field" : {
          "type" : "geo_shape",
          "orientation" : "LEFT"
        }
      }
    }
  }
}
```

**Comment by talevy** [comment]
We discussed this and decided that it is likely that we are deprecating the orientation parameter (https://github.com/elastic/elasticsearch/issues/15317), so we will treat this as a documentation problem and make sure to make it clear that this is expected behavior.
