### ISSUE TITLE
[CI] ShardSizeTermsIT.testNoShardSizeTermOrderDouble

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#43040]
Failed on master once here:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/18/console

with:
```
java.lang.AssertionError: 
Expected: <8L>
     but: was <3L>
	at __randomizedtesting.SeedInfo.seed([F688A226AA20AF15:6341D5542888518A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.search.aggregations.bucket.ShardSizeTermsIT.testNoShardSizeTermOrderDouble(ShardSizeTermsIT.java:379)
```
Reproduction line:
```
./gradlew :server:integTest --tests "org.elasticsearch.search.aggregations.bucket.ShardSizeTermsIT.testNoShardSizeTermOrderDouble" -Dtests.seed=F688A226AA20AF15 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=nl-NL -Dtests.timezone=SystemV/EST5EDT -Dcompiler.java=12 -Druntime.java=11
```
did not work out for me, neither did more extensive test running (1000+ runs).

Given that this only failed once, I left it unmuted in case further test failures could provide valuable input.

**Comment by polyfractal** [comment]
Chatted briefly about this failure in weekly meeting.  Haven't looked at it yet, but whenever we get to it we should probably add checks for shard failures.  E.g. a shard failure would return partial results and fail assertions.

Probably applies to many such agg tests.

**Comment by csoulios** [comment]
This test has not failed for more than 1 year (since February 7th 2020)
Also, related to https://github.com/elastic/elasticsearch/issues/42893 the integration test will be replaced by an `AggregatorTestCase`
