### ISSUE TITLE
[ML] Data frame ID string should be validated

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#43043]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.2.0

Currently, data frame ID string are not validated when the data frame is created. We probably want something similar to what's 
currently in place with ML job IDs, which is:
 - only allow lowercase alphanumeric (a-z and 0-9), hyphens or underscores
 - must start and end with alphanumeric
 - maximum length of 64 characters

**Comment by sophiec20** [comment]
Note that trying to stop or get a named data frame will fail if the data frame ID contains a `comma`. However `GET .../_all` will show this. Consistency in behaviour is required. Limiting to follow the anomaly detection validation pattern will allow us to more easily enforce consistency and also allow us to use the data frame id as the default dest index in the UI.


All the data frames in the following output exist.
```
# GET _data_frame/transforms/Aalto-Set,älä3
{
  "error" : {
    "root_cause" : [
      {
        "type" : "resource_not_found_exception",
        "reason" : "Transform with id [Aalto-Set,älä3] could not be found"
      }
    ],
    "type" : "resource_not_found_exception",
    "reason" : "Transform with id [Aalto-Set,älä3] could not be found"
  },
  "status" : 404
}


# GET _data_frame/transforms/Aalto-Setälä
{
  "count" : 1,
  "transforms" : [
    {
...
}


# GET _data_frame/transforms/test
{
  "count" : 1,
  "transforms" : [
    {
...
}


# POST _data_frame/transforms/Aalto-Set,älä3/_stop
{
  "error" : {
    "root_cause" : [
      {
        "type" : "resource_not_found_exception",
        "reason" : "Transform with id [Aalto-Set,älä3] could not be found"
      }
    ],
    "type" : "resource_not_found_exception",
    "reason" : "Transform with id [Aalto-Set,älä3] could not be found"
  },
  "status" : 404
}


# POST _data_frame/transforms/test/_stop
{
  "acknowledged" : true
}


# POST _data_frame/transforms/Aalto-Setälä/_stop
{
  "acknowledged" : true
}

```

**Comment by benwtrent** [comment]
I agree that the ID should be validated on PUT, I created a PR to restrict it similarly to ML jobs as it handles these scenarios already. 

ID length is also an issue as we create DOCs by concatenating the ID with some prefix and doc IDs have a length limit of 512 bytes

**Comment by sophiec20** [comment]
@benwtrent Can we get the lowercase check in place please. One of the goals was to confirm with job_id .. and also in the UI to use the transform name as the default dest index.

**Comment by sophiec20** [comment]
closing - `transform_id` is now validated in the same way as `job_id`.

@dimitris-athanasiou please apply to data frame analytics.
