### ISSUE TITLE
Elasticsearch over HTTPS Channel

### ISSUE THREAD

**Issue by manoj4321** [elastic/elasticsearch#43044]
Hello,
I am currently working on communication of elasticsearch, fscrawler and kibana over HTTPS channel. I am pretty much successfull in it. For this, I used self signed certificates and followed the documentation given on home site of elasaticsearch. 

Problem is that, I am able to access HTTPS service of elasticsearch from a different working station (let's say machine X) which in the same network as the server, but machine X doesn't have the self signed certificate that I used on server machine. My doubt is how I am able to access the service of elasticsearch from X machine, since i don't have self signed certificate installed there. The whole purpose of HTTPS then goes in vain. 

NOTE:- I need to add exception in the browser to access elasticsearch's service as it says certificate is not trusted.

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
