### ISSUE TITLE
Inconsistent segment stats with soft-deletes

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43103]
Segment stats are currently inconsistent when it comes to (soft-)deletes. The number of deletes are counted in a different way for non-searchable committed segment infos than for searchable ones, e.g. soft-deletes are not treated as deletes in committed segment infos.

We should make sure to have segment infos record the number of soft deletes as well, so that we return consistent numbers, and preferably also return information regarding the count of soft-deletes vs hard-deletes in the API.

**Comment by dnhatn** [comment]
I opened https://github.com/elastic/elasticsearch/pull/43126 to propose the fix for the delete count issue.

**Comment by dnhatn** [comment]
> and preferably also return information regarding the count of soft-deletes vs hard-deletes in the API.

At first glance, these numbers would be useful. However, soft-deletes and hard-deletes are exclusive. If soft-deletes is enabled, we won't have hard-deletes (except situations where we hit non-abortable exceptions during indexing) and vice versa.

**Comment by ywelsch** [comment]
ok, sounds good.
