### ISSUE TITLE
[Sniffer] add cluster_name check in ElasticsearchNodesSniffer

### ISSUE THREAD

**Issue by heirish** [elastic/elasticsearch#43137]
Seems now high level rest client with sniffer enabled doesn't check the cluster name when sniffing. 
That would cause a problem if elasticsearch is deployed in environments using Docker containers where IP addresses could change.

for example,  client was connect to cluster A, then cluster A is down and a new cluster B is started, 
and cluster B occupies some IP that cluster A had. 
If cluster name is not checked, after the next sniffing, the client will connect to cluster B.

For Server side, 
there are multi elasticsearch 7.0.0 clusters in a single namespace of kubernetes. 

For Client side,
Now I am using Hight Level Rest Client Java API in my project to access one cluster, with sniffer  enabled.

```pom.xml
 <dependency>
     <groupId>org.elasticsearch.client</groupId>
     <artifactId>elasticsearch-rest-high-level-client</artifactId>
     <version>7.0.0</version>
 </dependency>
 <dependency>
     <groupId>org.elasticsearch.client</groupId>
     <artifactId>elasticsearch-rest-client-sniffer</artifactId>
     <version>7.0.0</version>
</dependency>
```

```java
String[] ESHost = esClusterInfo.getHosts().toArray(new String[0]);
List<HttpHost> transportAddressList = new ArrayList<>();
for (String host : ESHost) {
    transportAddressList.add(new HttpHost(host, esClusterInfo.getPort(), "http"));
}
RestClientBuilder builder = RestClient.builder(transportAddressList.toArray(new HttpHost[transportAddressList.size()]));
client = new RestHighLevelClient(builder);
sniffer = Sniffer.builder(client.getLowLevelClient()).build();
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
