### ISSUE TITLE
[TEST] SslMultiPortTests failing on 7.x

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43141]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/16/consoleText

https://gradle.com/s/zudrwwx3tyrgi

Relevant exception:

```
 java.lang.IllegalArgumentException: value
        at __randomizedtesting.SeedInfo.seed([E2E5B6E4A3D8F189:5242019AEA205556]:0)
        at org.elasticsearch.bootstrap.JavaVersion.parse(JavaVersion.java:48)
        at org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests.lambda$getProtocols$1(SslMultiPortTests.java:439)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests.getProtocols(SslMultiPortTests.java:439)
        at org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests.testThatTransportClientWithOnlyTruststoreCannotConnectToClientProfile(SslMultiPortTests.java:312)
```

The fix might be to use `java.specification.version` instead of `java.version` for parsing, or directly use `JavaVersion.current()`

**Comment by davidkyle** [comment]
More of this sort of thing: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/44/console

Checking build stats there have been a number of failures all periodic builds run on openjdk13 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/43/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&amp;&amp;linux&amp;&amp;docker/40/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/39/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&amp;&amp;linux&amp;&amp;docker/38/console
...


In fact the build hasn't succeed in some time
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/

**Comment by mayya-sharipova** [comment]
More recent failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/2/console

**Comment by matriv** [comment]
One more failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/26/console

**Comment by andrershov** [comment]
Another one https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/90/console

**Comment by ebadyano** [comment]
more failures: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/38/console

**Comment by ebadyano** [comment]
and another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/95/console

**Comment by jkakavas** [comment]
reopening until #44017 is backported to 7.3 as this is still going to fail there

**Comment by ebadyano** [comment]
Another failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/97/consoleFull
