### ISSUE TITLE
[Documentation] Watcher ssl/tls settings do not fallback to defaults as we state in the docu

### ISSUE THREAD

**Issue by radoondas** [elastic/elasticsearch#43151]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.X

**Plugins installed**: [] not relevant

**JVM version** (`java -version`): not relevant

**OS version** (`uname -a` if on a Unix-like system): not relevant

**Description of the problem including expected versus actual behavior**:
In the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/notification-settings.html#ssl-notification-settings) we state that ssl/tls settings for watcher fallback to defaults.

`You can configure the following TLS/SSL settings. If the settings are not configured, the Default TLS/SSL Settings are used.`

This is not correct and documentation should be fixed.
Thanks.

**Comment by debadair** [comment]
[docs issue triage]
