### ISSUE TITLE
Add Force Merge to hot lifecycle phase

### ISSUE THREAD

**Issue by mud5150** [elastic/elasticsearch#43165]
**Add Force Merge to hot lifecycle phase**:
For time series data it makes sense that you may want to do a force merge on an index in the hot phase after rollover occurs. Seems pretty straight forward but if you want more information LMK.

**Comment by dakrone** [comment]
> For time series data it makes sense that you may want to do a force merge on an index in the hot phase after rollover occurs.

@mud5150 will doing a hot phase with a `rollover` action and then having a "warm" phase with no `min_age` set so that it performs the force merge immediately after the rollover happens work? You can do that currently. Is there a reason the force merge would need to happen in the hot phase?

**Comment by mud5150** [comment]
It could work, however in my particular instance all phases are in use. In my instance "hot" servers hold 28 days of data. Warm servers (slower disks) hold the rest of the year and still get a good amount of user queries. Cold nodes have slow disks and high ratio of storage to memory, use frozen indices, etc. It's not a problem for me to have curator force merge the index after the rollover happens, I just thought the above seems like a reasonable use case.

**Comment by dakrone** [comment]
We discussed this and decided to allow the force merge action in the hot phase, with a small caveat. We will require that the `rollover` action also be present (since rollover will occur prior to the force merge).
