### ISSUE TITLE
Range filter execution fielddata should work on non-numeric type

### ISSUE THREAD

**Issue by zsiddique** [elastic/elasticsearch#4318]
Hey,

You can sort on non-numeric type (string in our case) so why cant you do range filter using the same fielddata?  It seems currently the range filter option fielddata is just a rename of the numeric_range range filter.  Also the current docs dont mention the fact it only works on numeric.

Currently with the 1.0.0Beta2 it fails if you try a range fielddata query with the following
```
QueryParsingException[[index] [range] filter field [date.untouched] is not a numeric type]; }]"
```
Thanks
Zuhaib

Edit:
I see lucene has "FieldCacheRangeFilter" for this support but that currently ES uses TermRangeFilter.

**Comment by jpountz** [comment]
Closing: we removed the execution option in 2.0. Range execution through fielddata might come back, but with automatic detection of whichever is more efficient as opposed to using an option.
