### ISSUE TITLE
date histogram cache?

### ISSUE THREAD

**Issue by liujin1993** [elastic/elasticsearch#43185]
We hava huge amount of date histogram query, so i want to know whether the partial result of date histogram query can be cached.
For example, i query avg(cost) of last 1 hour group by 1m interval at 01:00, and then i do a same query at 01:01. Can the result of 00:01~01:00 be cached? It can save CPU resource in a great measure
Thanks!

**Comment by markharwood** [comment]
Issues opened here are intended to be bug reports or feature requests.
If you are looking for general advice in using elasticsearch please use our [discuss forums ](https://discuss.elastic.co/c/elasticsearch)
