### ISSUE TITLE
IndexStatsIT.testConcurrentIndexingAndStatsRequests failing test

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#43195]
on 7.1 the test failed once
```
./gradlew :server:integTest --tests "org.elasticsearch.indices.stats.IndexStatsIT.testConcurrentIndexingAndStatsRequests" \
  -Dtests.seed=CCA7BD7C1D8451E9 \
  -Dtests.security.manager=true \
  -Dtests.locale=pt-BR \
  -Dtests.timezone=Europe/Tallinn \
  -Dcompiler.java=12 \
  -Druntime.java=8
```
does not reproduce
https://scans.gradle.com/s/jywbjmkjzylke/

stacktrace:
```

Caused by:
--
java.lang.AssertionError:
Expected: <CREATED>
but: was <UPDATED>
at __randomizedtesting.SeedInfo.seed([CCA7BD7C1D8451E9]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.indices.stats.IndexStatsIT.lambda$testConcurrentIndexingAndStatsRequests$4(IndexStatsIT.java:1138)


```
unlikely that the test itself created same index twice. Could it be that the cleanup was missed somehow?

**Comment by ywelsch** [comment]
Relevant log lines:

```
1> [2019-06-13T11:52:22,583][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [test/wh0A-R3ySkyuTWzQbgjV7w] create_mapping [type]
  1> [2019-06-13T11:53:01,933][WARN ][o.e.c.InternalClusterInfoService] [node_s0] Failed to update shard information for ClusterInfoUpdateJob within 15s timeout
  1> [2019-06-13T11:53:06,063][INFO ][o.e.c.s.MasterService    ] [node_s0] node-left[{node_s1}{UN9q9PgtRN-sa0dfULAGVw}{mFFvPjXmRTuhPPbwUTDt5w}{127.0.0.1}{127.0.0.1:32827} followers check retry count exceeded], term: 1, version: 127, reason: removed {{node_s1}{UN9q9PgtRN-sa0dfULAGVw}{mFFvPjXmRTuhPPbwUTDt5w}{127.0.0.1}{127.0.0.1:32827},}
  1> [2019-06-13T11:53:06,066][INFO ][o.e.c.s.ClusterApplierService] [node_s0] removed {{node_s1}{UN9q9PgtRN-sa0dfULAGVw}{mFFvPjXmRTuhPPbwUTDt5w}{127.0.0.1}{127.0.0.1:32827},}, term: 1, version: 127, reason: Publication{term=1, version=127}
```

Similar to https://github.com/elastic/elasticsearch/issues/42502#issuecomment-501676072, this is unrelated to the actual test case. The nodes seem to be freezing during the test, with fault detection of the 2 nodes noticing that the respective other is not responding. This does not look to be anything specific to this test, and rather indicates an infrastructure problem with the CI machines. Given that this is on the 7.1 branch, which is not receiving many updates anymore, makes it even more likely that this is unrelated to the actual code that's running (given that we had 2 reports on the same day, with no prior ones). I'm closing this out as I don't think there's anything we can investigate here w.r.t. the specific test failure.
