### ISSUE TITLE
Inconsistent query behavior with multi_field and string value

### ISSUE THREAD

**Issue by azell** [elastic/elasticsearch#4320]
I am seeing inconsistent behavior in ES 0.90.7 when storing a string directly in a multi_field, versus as a hash of attributes.  Relevant gists:

https://gist.github.com/azell/7746233
https://gist.github.com/azell/7746253

The only difference in the above two gists is the JSON document published to ES.  In the former, the string is directly associated with its value:
  "name" : "test me"

In the latter, the string is associated with a hash which contains its value:
    "name" : { "value" : "test me" }

Performing a search against the multi_field field without the default name ("name.untouched") returns 1 result in the former, but 0 in the latter.  Is this intended?  Ref http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-core-types.html#string :

The string type also support custom indexing parameters associated with the indexed value. For example:

{
    "message" : {
        "_value":  "boosted value",
        "_boost":  2.0
    }
}

The mapping is required to disambiguate the meaning of the document. Otherwise, the structure would interpret "message" as a value of type "object". The key _value (or value) in the inner document specifies the real string content that should eventually be indexed. The _boost (or boost) key specifies the per field document boost (here 2.0).

**Comment by clintongormley** [comment]
This is still broken in 2.0

**Comment by jimferenczi** [comment]
The quick and easy solution would be what @azell proposed: " the code should rewind the ParserContext to the START_OBJECT token before calling Mapper.parse". Unfortunately the json parser is forward only and there is no way to rewind it. This is a clear blocker which makes the low hanging fruit higher ;). We could add the object to the context and check in all the field mappers that accept multi fields (or copy_to) if the value is populated or not but this would complicate the mapping even more.

**Comment by clintongormley** [comment]
thanks for looking at this @jimferenczi. i think we should close in favour of https://github.com/elastic/elasticsearch/issues/15388
