### ISSUE TITLE
ILM may get stuck waiting for segment count to reach expected number

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#43245]
When ILM attempts a force merge it immediately moves to a step that waits until the segment count reaches the expected number. However, it's possible for a force merge to silently stop (for example, if the shard being merged moves to a different node the force merge does not continue on the new node).

This can lead to the index being stuck indefinitely in the the `SegmentCountStep`.

**Comment by gaocx2000cn** [comment]
About 'Make ILM force merging best effort (#43246)'

There are cluster with 3 shards on 3 data node, forcemerge with max_num_segments=1 against Elasticsearch7.0.1 cluster will spend twice as much time as Elasticsearch6.8.13 cluster.
Is this a bug?
