### ISSUE TITLE
Add explanation of relocating shard state.

### ISSUE THREAD

**Issue by kat257** [elastic/elasticsearch#43244]
https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html
Issue raised: 
Cristina Albu [12:17 PM]
I was researching the possible shards statuses and found 3 types: `Starting`, `Initializing` and `Unassigned`. But folks also talk about `Relocating` and `Unavailable`. Are their statuses on their own or do they fall under `Unassigned`’? Also, are there any other that I am missing?
Response:
Nhat Nguyen  [4 minutes ago]
@Cristina A shard copy can be in one of these four states: unassigned, initializing, started and relocating. I think people call “unavailable” for “unassigned” but we prefer using  “unassigned”. A relocating shard is a started shard but is being relocated to another node.

**Comment by abhiroj** [comment]
can this issue be assigned to me?

**Comment by jrodewig** [comment]
These states were documented with #45392. Closing this issue.
