### ISSUE TITLE
term query OOM

### ISSUE THREAD

**Issue by zwbVsA** [elastic/elasticsearch#43270]
**Describe the feature**:

**Elasticsearch version 6.5.3

**Plugins installed**: []

**JVM version1.8(`java -version`):

**OS version linux 3.10.0-862.11.6.el7.x86_64

**Description of the problem including expected versus actual behavior**:

every day has 1000W data，i query one month using termQuery cause OOM.
this is the dsl 
{
	"from": 0,
	"size": 10,
	"query": {
		"bool": {
			"filter": [
				{
					"bool": {
						"must": [
							{
								"term": {
									"type": {
										"value": "01",
										"boost": 1.0
									}
								}
							},
							{
								"term": {
									"value": {
										"value": "D5961EA6F5F5F98034C8A",
										"boost": 1.0
									}
								}
							}
						],
						"adjust_pure_negative": true,
						"boost": 1.0
					}
				}
			],
			"adjust_pure_negative": true,
			"boost": 1.0
		}
	},
	"sort": [
		{
			"hitTime": {
				"order": "desc"
			}
		},
		{
			"_id": {
				"order": "desc"
			}
		}
	]
}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
