### ISSUE TITLE
Make response filter_path work with the flat_settings option of _cluster/settings

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#43290]
I wish to filter the output from the `_cluster/settings` API with `filter_path`. For example, this works like this
```
curl -X GET "localhost:9200/_cluster/settings?pretty&include_defaults&filter_path=defaults.xpack.security.*"
```
But if I want to flatten the settings like this
```
curl -X GET "localhost:9200/_cluster/settings?pretty&include_defaults&filter_path=defaults.xpack.security.*&flat_settings"
```
it no longer works (returns empty).

Generally, can `filter_path` be made to traverse dot names and work in a mix scenario of dot names and objects?

**Comment by rjernst** [comment]
`filter_path` is used to filter the json response. It works in your first example because the setting keys become part of the json structure. To filter on setting names for the settings request specifically, use `settings_filter`.

**Comment by albertzaharovits** [comment]
_Reopening since I'm not sure you get notifications on a closed issue._

Hi @rjernst , _settings_filter_ filters **out** the set of settings rendered, whereas `filter_path` specifies the pattern to render, ignoring everything else.

The use case I am having is a way to get (for a backup) the settings from the cluster state as a "nice" JSON. In this use case it is important for the JSON to be pretty. So in this case, pretty means flat names (no inner hashes) and a minimal set of settings (filter out everything else).

What do you think?

**Comment by rjernst** [comment]
`filter_path` and `settings_filter` serve different purposes. Since `filter_path` operates solely on the json response; I don't think it should have any interaction with `flat_settings`.

It sounds like you want a way to either negate the settings filter, or have another setting that means "only these settings". However, restructuring json is something that can be done client side, so I'm not sure there is really a need for that. In either case, I don't think the original description of this issue is something we should do.

**Comment by albertzaharovits** [comment]
I agree that restructuring json should be left onto the client side, but I raised it because we already do a lot of filtering/restructuring . Negating wildcards sounds like a poor man's regex so I suppose discussions have been rejecting this before.

> In either case, I don't think the original description of this issue is something we should do.

Agreed, will close this issue.

**Comment by huanqingdong** [comment]
> `filter_path` is used to filter the json response. It works in your first example because the setting keys become part of the json structure. To filter on setting names for the settings request specifically, use `settings_filter`.

hi,can you tell me how to use `settings_filter`, i try use it like bellow ,but not work
`GET _cluster/settings?include_defaults=true&flat_settings=true&settings_filter=defaults.action.auto_create_index`
it show all defaut settings

**Comment by lucaspouzac** [comment]
Old ticket, but it works by escaping the points from the flat key.

```
GET /_cluster/settings?pretty&include_defaults&flat_settings&filter_path=defaults.xpack\.security\.*
GET /_nodes?filter_path=nodes.*.name,nodes.*.settings.cluster\.name&flat_settings
```
