### ISSUE TITLE
How to send query contains NOT | AND | OR?

### ISSUE THREAD

**Issue by Mr-WangZhe** [elastic/elasticsearch#43310]
I use org.elasticsearch.client to query string contains NOT, but I get the response about {"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [(allnames:((NOT ) OR (NOT* )))]", can you help me to resolve it?

 Thanks!
Jack

**Comment by Mr-WangZhe** [comment]
I know that NOT | AND | OR are conditions, but how can we query string contains them?

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
