### ISSUE TITLE
Unsupported setting in keystore preventing elasticsearch to start

### ISSUE THREAD

**Issue by eedugon** [elastic/elasticsearch#43328]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.7

**Plugins installed**: [N/A]

**JVM version** (`java -version`): 1.8

**Description of the problem including expected versus actual behavior**:
A user who was trying to configure a remote xpack monitoring exporter added the setting `xpack.monitoring.exporters.shared.auth.password` to the keystore.

The setting, together with the rest of the exporter setting in `elasticsearch.yml` didn't work, as the setting is not supported for a keystore. That's clearly identified in this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/secure-settings.html):

> Only some settings are designed to be read from the keystore. See documentation for each setting to see if it is supported as part of the keystore.

However, when the user cleaned the settings from elasticsearch.yml, elasticsearch did not start with this exception:

```
org.elasticsearch.common.settings.SettingsException: missing exporter type for [shared] exporter 
```

As there wasn't any track of the exporter in the cluster settings API, neither in elasticsearch.yml file, it took some time to the user to realize that the "unsupported" setting from the keystore was causing this (elasticsearch is internally receiving the setting and hence having an exporter defined with missing mandatory settings).

Once the setting was removed from the keystore, elasticsearch started without any issue.

From the document description the expectation could be that if the setting is not supported (cannot be read from the keystore) it shouldn't affect the system, so maybe adding a note in the doc might be helpful, as I don't think this is really a bug.

The note could be:
`even if a setting is not designed to be read from a keystore, if added, it will be populated to elasticsearch when starting, which might cause unexpected issues. Avoid adding unsupported settings to the keystore`

**Comment by rjernst** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/43454 to clarify in the docs a bit, to make it a little more clear what behavior to expect.
