### ISSUE TITLE
[Feature Request] In-Place Updates

### ISSUE THREAD

**Issue by carsonhynes** [elastic/elasticsearch#43348]
Many of the documents my company loads into Elasticsearch have massive text fields (upward of 500MB) that we need indexed. While these large fields are mostly static for the life span of the index, we frequently push updates to much smaller indexed fields.

Whenever an update is pushed for one of these documents, the entire document is flagged for reindex. This is problematic due to the fact that our large static fields take a long time to index. 

We frequently do operations on the scale of 10's to 100's of thousands of documents, so this "extra" reindexing is especially problematic for our use case. 

Solr has a feature known as [in-place updates](https://lucene.apache.org/solr/guide/6_6/updating-parts-of-documents.html#UpdatingPartsofDocuments-In-PlaceUpdates) which allows updating on certain fields in a document without flagging the entire document for reindex.

Is it possible for Elasticsearch to implement a feature similar to this so that we can perform our update requests at scale without the need to wait minutes (sometimes even hours) for documents to be indexed and searchable with the new data?

**Comment by dnhatn** [comment]
This feature was requested and discussed at https://github.com/elastic/elasticsearch/issues/30433.

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

I am closing this issue for a similar request is being discussed on another thread already. You can participate and track the progress of this feature at #30433.

**Comment by carsonhynes** [comment]
@dnhatn That issue is related to a non-indexed field. My issue specifically requests support for an indexed field. Are you sure this is a duplicate ticket?
