### ISSUE TITLE
Master Node of ES Cluster is down

### ISSUE THREAD

**Issue by Neel-Gagan** [elastic/elasticsearch#43357]
ES 6.4.3 . i had a cluster with two nodes my master node configured over a Virtual Machine is crashed. prior to the Crash the The monitoring of the cluster showed indexed data as 20 GB. which has reduced to half when i view in the other node which was part of cluster. is it normal or some data might have been lost due to crashing of Master node.

**Comment by tvernum** [comment]
Hi @Neel-Gagan 
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
