### ISSUE TITLE
Create user dynamically (Python)

### ISSUE THREAD

**Issue by ry1015** [elastic/elasticsearch#43356]
Hi All,

It seems on version 7 the default user and password has been removed. Is there a way to create a user and role with xpack security turned on?

Thanks,
Ryan

PS. I tried file based authentication but elasticsearch keep using the security realm as reference thus my user isn't authenticated.

**Comment by tvernum** [comment]
Hi @ry1015,
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests. The discussion forums
are beter suited to these sorts of troubleshooting and problem diagnosis
conversations.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

Thank you.
