### ISSUE TITLE
Monitoring in Kibana for ingest pipelines similar to logstash pipelines

### ISSUE THREAD

**Issue by rugenl** [elastic/elasticsearch#43368]
It would be nice to have monitoring for ingest pipelines similar to that for the logstash pipelines.

**Comment by albertzaharovits** [comment]
Hi @rugenl ,

Can youmplease elaborate on what parameters would you like to monitor for an ingest pipeline?

**Comment by rugenl** [comment]
My thought is replicate what there is for logstash pretty closely,

For the cluster, show a summary each pipeline by name and event count (and failed) events for the interval, maybe with the option to suppress pipeline when event count is zero.  Click on the pipeline and get a logic layout with count/failed for each processor.  

Do the same for each node, of course those stats would be limited to that node.  

Not having the same level of monitoring for ingest pipelines makes it harder to move from logstash to ingest.  

This was prompted by a bug I'm trying to track down, where the ingest pipeline filebeat-6.7.1-elasticsearch-audit-pipeline-json is generating mapping errors containing "Could not dynamically add mapping for field [request.method]. Existing mapping for [elasticsearch.audit.request] must be of type object but found [keyword]" and I was trying to determine if the pipeline was being invoked and if the appropriate rename section is working.  Node stats is hard to correlate to the event time of a failure.  

Thanks

**Comment by jakelandis** [comment]
cc @elastic/stack-monitoring

**Comment by yaronp68** [comment]
@jakelandis we have pipeline metrics monitoring on our list of required metrics. Do you think we need anything beyond what's included in `nodes_stats`?

**Comment by jakelandis** [comment]
@yaronp68 - Today we have a pipeline an ordered list of processors each with "count", "time_in_millis", "current", and "failed".  Exposing that graphed over an interval of time would be helpful, but won't get us to feature parity with Logstash's pipeline viewer. Conditionals, failures, and pipelines calling pipelines are some of the largest gaps for any pipeline level visualizations beyond a line graph.

**Comment by yaronp68** [comment]
@jakelandis Thanks for the clarification. Please link any issues here so we can trace new pipeline metrics

**Comment by matschaffer** [comment]
Closing this in favor of https://github.com/elastic/kibana/issues/41936 - we'll use that as the main "epic" issue for stack monitoring maintainers.
