### ISSUE TITLE
endpoint  did not support AWS China region

### ISSUE THREAD

**Issue by piedro** [elastic/elasticsearch#43369]
it doesn't work with the  endpoint=s3.cn-north-1.amazonaws.com.cn,
but it still works with the endpoint =s3.***.amazonaws.com, sush as s3.ap-northeast-1.amazonaws.com

**Comment by original-brownbear** [comment]
When you say doesn't work, how actually does that manifest? Are you using an S3 bucket that is hosted in a Chinese region or are on that is outside of China? It seems the latter is the case here and afaik AWS has separations in place between their regions outside of China and the Chinese regions (see https://www.amazonaws.cn/en/about-aws/china/) .

**Comment by piedro** [comment]
Install the software in the AWS cn-north-1 Region, and  copy the data between  S3 and ES

**Comment by original-brownbear** [comment]
@piedro your bucket is hosted in a Chinese region but you can only access it via non-Chinese endpoints?
What is the exact exception you're seeing?

**Comment by original-brownbear** [comment]
I'm closing this for now, please reopen and provide additional details if this continues to be an issue for yuo. It seems highly improbably that Elasticsearch is at fault here with the information provided so far, likely the issue here is simply the separation between CN and non-CN regions AWS.
