### ISSUE TITLE
7.1.1 : Geoip module : database_file  is not configurable

### ISSUE THREAD

**Issue by gboddin** [elastic/elasticsearch#43376]
While trying to create a pipeline with custom mmdb files ( aka GeoIP2-City.mmdb ) it fails :

So from https://www.elastic.co/guide/en/elasticsearch/reference/7.1/geoip-processor.html#geoip-processor we're doing a : 

```
PUT _ingest/pipeline/geoloc
{
  "processors": [
    {
      "geoip": {
        "field": "xForwardedFor",
        "target_field": "xForwardedForGeo",
        "ignore_missing": true,
        "database_file": "GeoIP2-City.mmdb"
      }
    },
    {
      "geoip": {
        "field": "ipAddress",
        "target_field": "ipAddressGeo",
        "ignore_missing": true,
        "database_file": "GeoIP2-City.mmdb"
      }
    }
  ]
}
```

Returns :

```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "[database_file] database file [GeoIP2-City.mmdb] doesn't exist",
        "processor_type": "geoip",
        "property_name": "database_file"
      }
    ],
    "type": "parse_exception",
    "reason": "[database_file] database file [GeoIP2-City.mmdb] doesn't exist",
    "processor_type": "geoip",
    "property_name": "database_file"
  },
  "status": 400
}
```

So far we've been trying to put the mmdb files in : 

/usr/share/elasticsearch/config/ingest-geoip ( as per the doc )
/usr/share/elasticsearch
/etc/elasticsearch/config/ingest-geoip
/etc/elasticsearch

We've also been trying a mysterious settings mention in the code : https://github.com/elastic/elasticsearch/blob/7.1/modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/IngestGeoIpPlugin.java#L90 which is not recognized by the nodes ...

So far no luck in using other db than the provided ones.

**Comment by gboddin** [comment]
We're running Elastic's Debian packages on Debian 9

**Comment by jasontedor** [comment]
I am so sorry for the lack of clarity and precision in the documentation regarding this. The correct location in which to place this files when installed via a package manager on Debian 9 is `/etc/elasticsearch/ingest-geoip`. So the docs should say `$ES_CONFIG/ingest-geoip`.

**Comment by jasontedor** [comment]
I opened #43383.

**Comment by gboddin** [comment]
Files are now in /etc/elasticsearch/ingest-geoip : 
```
root@es-ingest001:~# ls /etc/elasticsearch/ingest-geoip/ -lha
total 207M
drwxr-sr-x 2 root elasticsearch 4.0K Jun 20 06:48 .
drwxr-s--- 4 root elasticsearch 4.0K Jun 20 06:48 ..
-rw-r--r-- 1 root elasticsearch 118M Jun 20 06:48 GeoIP2-City.mmdb
-rw-r--r-- 1 root elasticsearch 3.9M Jun 20 06:48 GeoIP2-Country.mmdb
-rw-r--r-- 1 root elasticsearch  18M Jun 20 06:48 GeoIP2-ISP.mmdb
-rw------- 1 root elasticsearch    0 Jun 20 06:48 .geoipupdate.lock
-rw-r--r-- 1 root elasticsearch 6.3M Jun 20 06:48 GeoLite2-ASN.mmdb
-rw-r--r-- 1 root elasticsearch  59M Jun 20 06:48 GeoLite2-City.mmdb
-rw-r--r-- 1 root elasticsearch 3.7M Jun 20 06:48 GeoLite2-Country.mmdb
```

Pipeline creation stills says :

```
reason: "[database_file] database file [GeoIP2-City.mmdb] doesn't exist"
```

We haven't restarted the node yet, and will give it a try.

I see the geoloc module might be LazyLoaded on ingest node. Could it be that it's because we're issuing the pipeline creation command on a non-ingest node ?

Thanks

**Comment by jasontedor** [comment]
> We haven't restarted the node yet, and will give it a try.

Hi, you will need to restart the nodes indeed.

> I see the geoloc module might be LazyLoaded on ingest node. Could it be that it's because we're issuing the pipeline creation command on a non-ingest node ?

This is fine, the request will be routed to a master node, and then ingest nodes will receive a cluster state update from the master with the new pipeline definition.

**Comment by gboddin** [comment]
We had a last : `expected database [GeoLite2-ASN.mmdb] to not exist in [/etc/elasticsearch/ingest-geoip]` to fix but it's working flawless ! Thanks for the support.

**Comment by jasontedor** [comment]
You're welcome!

**Comment by hrak** [comment]
For anyone coming here that has dedicated master nodes and only installed the GeoIP database in `/etc/elasticsearch/ingest-geoip` on the nodes with the ingest role, and is still running into `database file [GeoIP2-City.mmdb] doesn't exist`, even after restarting the ingest nodes: the GeoIP database also needs to be installed on the master nodes (+ restart those too) for it to work.

**Comment by al-ah** [comment]
> For anyone coming here that has dedicated master nodes and only installed the GeoIP database in `/etc/elasticsearch/ingest-geoip` on the nodes with the ingest role, and is still running into `database file [GeoIP2-City.mmdb] doesn't exist`, even after restarting the ingest nodes: the GeoIP database also needs to be installed on the master nodes (+ restart those too) for it to work.

Thanks for your guidance. I wish there was a better way
