### ISSUE TITLE
spurious JAVA_HOME deprecation warning on RHEL6 with RPM

### ISSUE THREAD

**Issue by Grinnz** [elastic/elasticsearch#43380]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.8.0, Build: default/rpm/65b6179/2019-05-15T20:06:13.172855Z, JVM: 1.8.0_131

**Plugins installed**: ['analysis-icu']

**JVM version** (`java -version`):
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): Linux ... 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Dec 28 20:15:47 EST 2017 x86_64 x86_64 x86_64 GNU/Linux (Red Hat Enterprise Linux Server release 6.5 (Santiago))

**Description of the problem including expected versus actual behavior**:
After upgrading to Elasticsearch 6.8.0 via RPM upgrade (or possibly in the previous 6.6.2 to 6.7.2 upgrade) any elasticsearch command line invocation results in `warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME`. This occurs even if JAVA_HOME is set to /usr/bin/java in /etc/sysconfig/elasticsearch -- it had previously never been set.

**Comment by Grinnz** [comment]
Note that I cannot currently upgrade to 7.0 because https://github.com/elastic/elasticsearch-perl is not yet compatible.

**Comment by rjernst** [comment]
> if JAVA_HOME is set to /usr/bin/java

Java home should be set to the java installation directory, not the java binary location.

**Comment by jasontedor** [comment]
To expand on what @rjernst is saying, if you have Java installed at `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el6_10.x86_64/` then you would set `JAVA_HOME` to `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el6_10.x86_64/`, not `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el6_10.x86_64/bin/java`. This is because Elasticsearch looks for `java` at `JAVA_HOME/bin/java`. If it fails to find it there, it falls back to the path behavior. This explains why you're seeing the message despite having `JAVA_HOME` set, you don't have it set in a way that Elasticsearch can find the path. Sorry for the confusion here, but this is the standard way that `JAVA_HOME` is configured for software that uses the JVM. It's also consistent with what the JDK refers to internally as `java.home`, as the directory relative to which `bin/java` can be found, not the full path of `java`.

**Comment by Grinnz** [comment]
But why is the message occurring when JAVA_HOME is not set? Should it not work out of the box without deprecation messages?

**Comment by jasontedor** [comment]
> But why is the message occurring when JAVA_HOME is not set? Should it not work out of the box without deprecation messages?

Because it's falling back to finding `java` on the path. That is what is deprecated. In Elasticsearch 7.0+, we bundle a JDK and if `JAVA_HOME` is not set, we use that, and if `JAVA_HOME` is set we don't and use `JAVA_HOME` instead. But picking up `java` on the path is no longer supported.

**Comment by Grinnz** [comment]
Then the deprecation message is confusing: it says to specify JAVA_HOME, when in fact the correct action is to not do anything and live with the spurious messages until then.

**Comment by Grinnz** [comment]
FWIW, I also tried setting `JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64` and the warning still occurs.

**Comment by jasontedor** [comment]
Can you show that `/usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java` exists?

**Comment by Grinnz** [comment]
It is the location referred to by /etc/alternatives/java and thus /usr/bin/java.
```
$ ls -alh /usr/lib/jvm/jre-1.8.0-openjdk.x86_64
lrwxrwxrwx 1 root root 51 May 16  2017 /usr/lib/jvm/jre-1.8.0-openjdk.x86_64 -> java-1.8.0-openjdk-1.8.0.131-0.b11.el6_9.x86_64/jre
```
(I also tried with the referred directory)

**Comment by Grinnz** [comment]
I will also note that this deprecation notice is not occurring on CentOS 7, with the same upgrade path and JAVA_HOME still not specified.

**Comment by rjernst** [comment]
With JAVA_HOME set, can you do `ls -l $JAVA_HOME/bin/java`?

**Comment by Grinnz** [comment]
I'm not sure I follow - it's set in /etc/sysconfig/elasticsearch, not my local environment. If I set it in the (sudo) environment, it does not warn.

**Comment by jasontedor** [comment]
Can you start Elasticsearch, with `JAVA_HOME` set in `/etc/sysconfig` as you think it is, grab the PID of the Elasticsearch process, `cat /proc/<pid>/environ | tr '\0' '\n' | grep JAVA_HOME` and share the output. And then, as @rjernst asks, check `ls -al $JAVA_HOME/bin/java` where `$JAVA_HOME` is the value from the previous command (from the environment of the Elasticsearch process).

**Comment by Grinnz** [comment]
```
$ sudo cat /proc/30591/environ | tr '\0' '\n' | grep JAVA_HOME                                                                                              
JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64

$ JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64; ls -al $JAVA_HOME/bin/java                                                                               
-rwxr-xr-x 1 root root 9488 Apr 13  2017 /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
```

**Comment by jasontedor** [comment]
I am at a loss to explain what is going on here, thanks for being patient with us as we collect information from you. Can you share a little more? How are you starting Elasticsearch? I assume it's `service Elasticsearch start`? Can you show the output that prints the deprecation message including the context surrounding it (e.g., if it shows up on `stdout` after you issue `service elasticsearch start`)?

**Comment by Grinnz** [comment]
I am using `sudo service elasticsearch start`. It does not show up when doing that, but on any other command such as `sudo /usr/share/elasticsearch/bin/elasticsearch --version` or `sudo /usr/share/elasticsearch/bin/elasticsearch-plugin list`.

**Comment by jasontedor** [comment]
Okay, now this is making a lot more sense. Those CLI tools do not read `/etc/sysconfig/elasticsearch`. You have to set `JAVA_HOME` in the environment that you're running in.

**Comment by Grinnz** [comment]
Indeed, if I unset JAVA_HOME in /etc/sysconfig/elasticsearch (as default) then `service elasticsearch start` also exhibits the warning.

**Comment by Grinnz** [comment]
This leaves me with two questions: 1) Why isn't the warning occurring on CentOS 7? 2) Can the deprecation message be clarified? Or is it even useful? The only action I would need to take is if I wanted to keep using the system installed java after upgrading, I would need to set it in /etc/sysconfig/elasticsearch and add it to the environment in some way for all of my sudo commands. It does not feel like a deprecation scenario but a change in behavior.

**Comment by jasontedor** [comment]
> 1) Why isn't the warning occurring on CentOS 7?

I don't know how your environment is setup so we can not explain this. I assure you there is nothing that is OS-specific in this logic. I would look on your end to see if `JAVA_HOME` is set via a login profile, for example.

> 2) Can the deprecation message be clarified? Or is it even useful?

We believe it's useful since it's a breaking change for users relying on using `java` from the path.
