### ISSUE TITLE
Doc:  6.7 CCS compatibility table wrapping issue

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#43391]
This only affects v6.7.  Subsequent doc versions do not have this problem.

The gateway nodes [compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/modules-remote-clusters.html#gateway-nodes-selection) table is wrapping (browser zoom at 100%) so the entries in the table look strange.

![image](https://user-images.githubusercontent.com/7216393/59794672-57596b00-928e-11e9-9421-3df64e3eab1f.png)

**Comment by javanna** [comment]
#43231 fixed this, but it needed to be back-ported to 6.7 too. It's fixed now.
