### ISSUE TITLE
rollover index mac_docs property not working as expected?

### ISSUE THREAD

**Issue by kleinlain** [elastic/elasticsearch#43409]
**Describe the feature**:

Hello,

I attended Elastic{on} in Berlin yesterday, and was asked the nice people at the AMA booth, but they could not instantly help me and told me to reproduce it, and post it here, so here goes:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.2

**Plugins installed**: XPack Security

**JVM version** (`java -version`): 1.8.0_191-b12

**OS version** (`uname -a` if on a Unix-like system): 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)

**Description of the problem including expected versus actual behavior**:
- create an index
- limit rollover only by document count
- insert documents
- rollover does not happen at expected doc count
- it seems necessary to repeat the index rollover setting once the amount of documents is reached?

**Steps to reproduce**:
I used the developer console for these steps

`PUT /rollovertest-000001
{
	"aliases": {
		"rollovertest": {}
	},
	"mappings": {
	  "user": { 
      "_all":       { "enabled": false  }, 
      "properties": { 
        "title":    { "type": "keyword"  }, 
        "name":     { "type": "text"  }, 
        "age":      { "type": "integer" }  
      }
    }
	}
}`

`POST /rollovertest/_rollover
{
	"conditions": {
		"max_docs" : 10
	}
}
`
- insert documents at least 10, I did this in single posts on purpose, to ensure it's not a job-still-running issue

`
POST rollovertest/user
{
    "title" : "some",
    "name" : "tom",
    "age" : 14
}
`

Is there a basic misunderstanding on my side when to apply the rollover conditions?

thanks a lot and kind regards
/Anja

**Comment by jasontedor** [comment]
Rollover conditions are only executed when you call the rollover API, the condition is not continuously monitored otherwise. That is rollover provides primitives, and then on top of this you have to coordinate calls to the rollover API via cron or some other automation. Additionally, we offer index lifecycle management functionality which enables you to set a policy, and then index lifecycle management would periodically execute the rollover API (with your desired condition on your behalf).

See the following note in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/indices-rollover-index.html) for further details:

>To roll over an index, a condition must be met when you call the API. Elasticsearch does not monitor the index after you receive an API response. To automatically roll over indices when a condition is met, you can use Elasticsearch’s [index lifecycle management (ILM) policies](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/index-lifecycle-management.html).

Does that help?

**Comment by kleinlain** [comment]
uh, yes this helps a lot, unfortunately this block you quoted, is not part of the 5.6 (which we are still using) version of the documentation.

Is there a recommendation how to handle this with 5.6? besides the obvious upgrade? ;)

thanks a lot, at least it clarifies the whole issue

**Comment by jasontedor** [comment]
> Is there a recommendation how to handle this with 5.6? besides the obvious upgrade? ;)

Yes, sorry, index lifecycle management is not available in GA form until 6.7. Prior to that, you would have to use a cron job or something similar for automation.

> thanks a lot, at least it clarifies the whole issue

You're welcome. I'll close this issue out then.
