### ISSUE TITLE
The elasticsearch node often dead  with excption of java.lang.OutofMemory:Java heap space 

### ISSUE THREAD

**Issue by hanmin-es** [elastic/elasticsearch#43408]
the test environment of our elastic cluster has 4 nodes, the version of java is 1.8.0_101,the version of elastic is 5.4.3 , we configure the xmx =20g, xms=20g in the jvm.option. the gc mode we use is G1GC.
in our 4 nodes elastic cluster,we insert into the elastic cluster with 10000 datalog per second.the size of each datalog is about 2-3KB, and the segment cache of es cluster is 6.9Gb.
during the process of test，the es nodes often failed with the logs print the fatal error,we can see the following picture appears,the es node generate the dump file at the es install path.
![1](https://user-images.githubusercontent.com/52027568/59830179-afb56900-9371-11e9-8847-2d6b7be4c738.png)
![2](https://user-images.githubusercontent.com/52027568/59830356-0a4ec500-9372-11e9-8ba2-0e01a136d1f6.jpg)
![image003_recompress](https://user-images.githubusercontent.com/52027568/59830436-39653680-9372-11e9-875d-faa0c9059782.jpg)
![image004_recompress](https://user-images.githubusercontent.com/52027568/59830476-4e41ca00-9372-11e9-8b3a-221325c12b8f.jpg)
![image005_recompress](https://user-images.githubusercontent.com/52027568/59830509-5dc11300-9372-11e9-8cfe-8a8e5d2332c3.jpg)

we use the tool of  mat to  analyze the dump file,and we find the biggest object in the java heap is space is like the flowing picture
![6](https://user-images.githubusercontent.com/52027568/59831178-d8d6f900-9373-11e9-9c0b-7bcdbe3eb853.jpg)
![7](https://user-images.githubusercontent.com/52027568/59831209-e68c7e80-9373-11e9-86ce-298224170bd5.jpg)
![image008_recompress](https://user-images.githubusercontent.com/52027568/59831240-f86e2180-9373-11e9-9d4a-3446fef48eb9.jpg)

![image008_recompress (1)](https://user-images.githubusercontent.com/52027568/59831365-39663600-9374-11e9-8dc4-8c90e52daf90.jpg)
![image009_recompress](https://user-images.githubusercontent.com/52027568/59831424-53077d80-9374-11e9-90ee-f45397c65d2c.jpg)
![image010_recompress](https://user-images.githubusercontent.com/52027568/59831438-5864c800-9374-11e9-9e0c-34715054f014.jpg)

![image011_recompress](https://user-images.githubusercontent.com/52027568/59831527-83e7b280-9374-11e9-991e-3d183cf6b7d5.jpg)
![image013_recompress](https://user-images.githubusercontent.com/52027568/59831534-89dd9380-9374-11e9-96c9-b06b3acaa8fd.jpg)
![image014_recompress](https://user-images.githubusercontent.com/52027568/59831541-8fd37480-9374-11e9-8381-a22d080ede1a.jpg)

![image015_recompress](https://user-images.githubusercontent.com/52027568/59831871-3e77b500-9375-11e9-9c35-ca4a69ed33b5.jpg)
![image016_recompress](https://user-images.githubusercontent.com/52027568/59831887-4899b380-9375-11e9-9555-c65459e2ffa2.jpg)
![image017_recompress](https://user-images.githubusercontent.com/52027568/59831901-4e8f9480-9375-11e9-8bea-9cfe4e007243.jpg)
![image018_recompress](https://user-images.githubusercontent.com/52027568/59831914-53ecdf00-9375-11e9-8a86-d0b66d2c3b4d.jpg)

please help us to  solve this problem!

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
