### ISSUE TITLE
[CI] Windows build fails due to absence of Docker

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43417]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/33/console

```
02:25:03  Publishing build scan...
02:25:03  * What went wrong:
02:25:03  Docker (checked [/usr/bin/docker,/usr/local/bin/docker]) is required to run the following tasks: 
02:25:03    :distribution:docker:buildDockerImage
02:25:03    :distribution:docker:buildOssDockerImage
02:25:03  you can address this by attending to the reported issue, removing the offending tasks from being executed, or by passing -Dbuild.docker=false
```

Similar - https://github.com/elastic/elasticsearch/issues/43096 - but this time on Windows.

**Comment by atorok** [comment]
This no longer seems to be the case, windows jobs in CI correctly call `check` and don't require docker.

**Comment by davidkyle** [comment]
This has happened again, reopening the issue

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/46/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/44/console
