### ISSUE TITLE
GET _cat/templates Enhancement

### ISSUE THREAD

**Issue by Gunnerva** [elastic/elasticsearch#43445]
**Describe the feature**:
Enhance what GET _cat/templates can sort on

**Elasticsearch version** (`bin/elasticsearch --version`):
Elasticsearch 6.5.4
**Plugins installed**: []
n/a
**JVM version** (`java -version`):
n/a
**OS version** (`uname -a` if on a Unix-like system):
n/a
**Description of the problem including expected versus actual behavior**:
Requesting the ability to sort on more information when performing a GET _cat/templates

**Steps to reproduce**:

Currently, the "name" parameter is supported where you can filter the output for the templates that match a given name.

```
# GET _cat/templates?v&s=index_patterns,order&name=eng*
name                              index_patterns          order version
eng_application_mappings_throttle [eng_application_*]     10    
eng_application_mappings          [eng_application_*]     10    
eng_application_settings_test     [eng_application_test*] 10    
eng_system_settings_test          [eng_system_*]          10    
eng_system_mappings               [eng_system_*]          20    
```
 

However, this doesn't tell us all of the Templates that would match an Index Pattern starting with "eng*". For example, we have a wildcard Index Pattern "*", matching all indexes created, but there doesn't seem to be a way to query _cat/templates for "Which index templates would match a given index pattern?"

The feature would provide something like:

` GET _cat/templates?v&s=index_patterns,order&index_pattern=eng*`
 
Which would result in the following output:
```
name                              index_patterns                  order      version
6x.default_slowlog_settings_test  [*]                             0          
6x.default_number_of_shards       [*]                             0          
eng_application_mappings          [eng_application_*]             10         
eng_application_mappings_throttle [eng_application_*]             10         
eng_application_settings_test     [eng_application_test*]         10         
eng_system_settings_test          [eng_system_*]                  10         
eng_system_mappings               [eng_system_*]                  20    
```
 

Similarly, it would be nice to be able to provide an actual index name in the "index_pattern" parameter to see exactly which index templates would be applied if that given index name were created:

```
GET _cat/templates?v&s=index_patterns,order&index_pattern=eng_application_test-2019.06.20
name                              index_patterns                  order      version
6x.default_slowlog_settings_test  [*]                             0          
6x.default_number_of_shards       [*]                             0          
eng_application_mappings          [eng_application_*]             10         
eng_application_mappings_throttle [eng_application_*]             10         
eng_application_settings_test     [eng_application_test*]         10         
```

This would make it much easier to find which index templates are being applied to a given index or index pattern.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
