### ISSUE TITLE
Add Painless Utility Methods

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#43442]
This issue is for tracking utility method requests for Painless.

getByPath -- https://github.com/elastic/elasticsearch/pull/43170

**Comment by gingerwizard** [comment]
First one..
I commonly find myself checking types of fields - mainly as data is noisy and sometimes just gets sent as strings. Consider the following just to to check if a field is really an ip:

```
boolean isvalid(def i) {  try { def val = Integer.parseInt(i); return  (val >= 0 && val <=255)  } catch (Exception e) { return false; }   }
        
          def ip = ctx?.source?.ip; if (ip != null) { def groups = Arrays.asList(/\./.split(ip));  def is_ip = groups.stream().filter(s -> isvalid(s)).count() == groups.size(); if (!is_ip) { ctx.source.remove('ip'); ctx.source.domain = ip; }   }
```

whilst im sure this could be improved (iterating over chars and using isDigit()) it remains cumbersome for what is a pretty common check.

Proposing field level methods which allow us to check if a field contains an underlying ES datatype e.g.

`ctx.ip.isIP()`
`ctx.location.isGeoPoint()`

etc.

**Comment by gingerwizard** [comment]
Hashing fields,
to get a simple sha256 has this was needed https://gist.github.com/gingerwizard/ed7e0ee8ab271c1dbb203532d4813d9a

A simple set of message digest utils would be great - especially since MessageDigest is not whitelisted.

**Comment by gingerwizard** [comment]
I commonly find myself needing to have parameters detailing fields for a script processor to operate on. Mainly for flexibility. A simple example, consider the following i use to shift data my a time period (i do this far too often):

```
PUT _ingest/pipeline/timeshift-data
{
  "description": "Time shifts data by X for a field Y",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx[params.field] != null) { def formatter = DateTimeFormatter.ofPattern(params.date_format); def current_time = ZonedDateTime.parse(ctx[params.field], formatter); current_time = current_time.plusSeconds(params.time_shift_seconds);  ctx[params.field] = current_time.format(formatter);  }",
        "params": {
          "field": "created_on",
          "time_shift_seconds": -259200,
          "date_format": "yyyy-MM-dd'T'HH:mm:ss.SSSSSSXXX"
        }
      }
    }
  ]
}
```

This approach works well until fields are under objects. Currently there is no easy way to access nested fields if the field name is passed as a parameter e.g. how do i parameterise `source.ip` given i access the field like:

`ctx['source']['ip']`

Many ways to solve this one, but maybe:

`ctx['source.ip']`

**Comment by jdconrad** [comment]
A safe add/remove from a Map/List structure would be useful to follow up on the getByPath work.  This would take a String as a path and safely create or delete existing elements along the path as necessary.

**Comment by jdconrad** [comment]
Request for random methods: https://github.com/elastic/elasticsearch/issues/39080

**Comment by stu-elastic** [comment]
For: https://github.com/elastic/elasticsearch/issues/43442#issuecomment-504088929 
> e.g. how do i parameterise source.ip given i access the field like:
> ctx['source']['ip']
> Many ways to solve this one, but maybe:
> ctx['source.ip']

Try using `getByPath`. 

For: https://github.com/elastic/elasticsearch/issues/43442#issuecomment-504085275
> Proposing field level methods which allow us to check if a field contains an underlying ES datatype e.g.
> ctx.ip.isIP()
> ctx.location.isGeoPoint()

Try `ctx.ip instanceof IpFieldMapper.IpFieldType.IpScriptDocValues` but we need to fix that: https://github.com/elastic/elasticsearch/issues/55351
Try `ctx.location instanceof ScriptDocValues.GeoPoints`.

For: https://github.com/elastic/elasticsearch/issues/43442#issuecomment-504086076
> A simple set of message digest utils would be great - especially since MessageDigest is not whitelisted.

Moved to https://github.com/elastic/elasticsearch/issues/55352
