### ISSUE TITLE
Snapshot restore fails when there is a lot of indices

### ISSUE THREAD

**Issue by dimatkach** [elastic/elasticsearch#43458]
We have a snapshot with 653 indices, and trying to restore it into an empty (5.6.16) cluster. 
It fails after a while, complaining that it `failed to process cluster event (restore_snapshot[scheduled-1561047587-instance-0000000006]) within 30s`.

<img width="1439" alt="Screen Shot 2019-06-20 at 2 33 07 PM" src="https://user-images.githubusercontent.com/4604190/59880256-9bc23500-937a-11e9-9ce9-b3ad7b78b650.png">

It appears that nothing is actually wrong with that snapshot, it just takes too long to read. 

/cc @original-brownbear

**Comment by original-brownbear** [comment]
@dimatkach sorry I found an easy solution for this after all. I failed to see it last night, but you can just increase that 30s timeout on the request since it's a `MasterNodeRequest` by adding the param `?master_timeout=` with some appropriately high value. Closing here, my bad.
