### ISSUE TITLE
GetSnapshotsResponse should re-wrap failed exceptions so callsites are visible in the stacktrace

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#43462]
From the following code:

https://github.com/elastic/elasticsearch/blob/f879e84e5a536c921f463465557297f994c54e3e/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java#L156-L166

It's possible for snapshot exceptions to be generated on a different line than where they are actually thrown, for example, code that prior to https://github.com/elastic/elasticsearch/pull/42090 worked like this:

```java
GetSnapshotsRequest getSnapshotsRequest = new GetSnapshotsRequest(new String[]{repo}, new String[]{snapshotName});
final GetSnapshotsResponse snaps;
try {
    snaps = client.snapshot().get(getSnapshotsRequest, RequestOptions.DEFAULT);
} catch (Exception e) {
    if (e.getMessage().contains("snapshot_missing_exception")) {
        fail("snapshot does not exist: " + snapshotName);
    }
    throw e;
}

Optional<SnapshotInfo> info = snaps.getSnapshots(repo).stream().findFirst();
if (info.isPresent()) {
    info.ifPresent(si -> {
        assertThat(si.snapshotId().getName(), equalTo(snapshotName));
        assertThat(si.state(), equalTo(SnapshotState.SUCCESS));
    });
} else {
    fail("unable to find snapshot; " + snapshotName);
}
```

Now fails. 

The exception is generated from the `snaps.getSnapshots(repo)` call above, *however*, the stacktrace for the exception actually traces back to the line

```java
    snaps = client.snapshot().get(getSnapshotsRequest, RequestOptions.DEFAULT);
```

which is very confusing, because that line itself is wrapped in a try/catch.

`GetSnapshotsResponse` should change this line:

https://github.com/elastic/elasticsearch/blob/f879e84e5a536c921f463465557297f994c54e3e/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java#L165

Into something like

```java
throw new ElasticsearchException(error);
```

So that the stacktrace correctly identifies the caller.

**Comment by ywelsch** [comment]
@dakrone Thanks for your analysis. Would you like to contribute a PR?

**Comment by amogh-jrules** [comment]
I am willing to take this up

**Comment by dakrone** [comment]
@amogh-jrules if you'd like to submit a PR for this that would be great, check out our [contributing document](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) if you need assistance getting an environment set up.
