### ISSUE TITLE
Elasticsearch node Crashing

### ISSUE THREAD

**Issue by yagizgulen** [elastic/elasticsearch#43470]
Hi,
We receive these errors in a node in our cluster, and the node gives these errors hype cpu and load to the maximum level of elasticsearch can not respond. node resources 2 CPU 8 RAM

Elasticsearch version : 6.5.4

Errors : 
1)
Found index level settings on node level configuration.

Since elasticsearch 5.x index level settings can NOT be set on the nodes
configuration like the elasticsearch.yaml, in system properties or command line
arguments.In order to upgrade all indices the settings must be updated via the
/${index}/_settings API. Unless all settings are dynamic all indices must be closed
in order to apply the upgradeIndices created in the future should use index templates
to set default values.

Please ensure all required values are updated on all indices by executing:

curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
 "index.refresh_interval" : "2m"
}'

2)
[2019-06-10T13:17:31,996][WARN ][o.e.d.s.a.MultiBucketConsumerService] [elasticsearch6_data02] This aggregation creates too many buckets (10480) and will throw an error in future versions. You should update the [search.max_buckets] cluster setting or use the [composite] aggregation to paginate all buckets in multiple requests.
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [flashlogExtra.installedVersion] of type [text]

java version : openjdk version "1.8.0_212"

## JVM configuration

-Xms3843m
-Xmx3843m
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+HeapDumpOnOutOfMemoryError
-XX:+PrintGCDetails

**Comment by astefan** [comment]
@yagizgulen This appears to be a question that could be handled by the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
