### ISSUE TITLE
Migrate HLRC request & response tests to use new base classes.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#43472]
Migrate HLRC request and response tests from extending `AbstractHlrcStreamableXContentTestCase` / `AbstractHlrcXContentTestCase` / `AbstractHlrcWriteableXContentTestCase` to `AbstractResponseTestCase` or `AbstractRequestTestCase`.

The motivation of this migration is that `AbstractResponseTestCase` and `AbstractRequestTestCase` based tests, test xcontent serialization more realistically from a HLRC perspective than the other tests do.

There are a number of tests that need to be migrated:
- [ ] GetBasicStatusResponseTests
- [ ] GetTrialStatusResponseTests
- [x] GetWatchResponseTests #43478
- [ ] HasPrivilegesResponseTests
- [ ] MlInfoActionResponseTests
- [ ] PutCalendarActionResponseTests
- [ ] XPackInfoResponseTests
- [ ] PutLicenseResponseTests
- [ ] StartBasicResponseTests
- [ ] DataFrameIndexerTransformStatsTests
- [ ] DataFrameTransformCheckpointStatsTests
- [ ] DataFrameTransformCheckpointingInfoTests
- [ ] DataFrameTransformStateAndStatsTests
- [ ] DataFrameTransformStateTests
- [x] DeleteWatchResponseTests #43478
- [x] ExecuteWatchResponseTests #43478
- [ ] GraphExploreResponseTests
- [x] PutWatchResponseTests #43478

**Comment by hub-cap** [comment]
None of the classes in the original description exist anymore and all the classes have been migrated. Closing.
