### ISSUE TITLE
SharedClusterSnapshotRestoreIT.testDataFileFailureDuringSnapshot reproducibly fails

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#43498]
`org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testDataFileFailureDuringSnapshot` has started failing consistently failing in `master`. This also reproduces locally. Here are a couple of examples:

https://scans.gradle.com/s/ls7gwwsudnwqo/tests/kyv2y2z3r4v7m-qcoutz5pezhvo
https://scans.gradle.com/s/rj2gdem5wxwha/tests/kyv2y2z3r4v7m-qcoutz5pezhvo

**Comment by mark-vieira** [comment]
Test has been muted in `master`.

**Comment by atorok** [comment]
Looks like this fails in `7.x` too https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/75/

**Comment by original-brownbear** [comment]
This should be fixed by https://github.com/elastic/elasticsearch/commit/03332b5aeb3eeb4c9fc0b61e08a8b84c33d09ee8 now which seems like it wasn't yet in the linked Jenkins run => closing :)
