### ISSUE TITLE
Make _all payload-based boosting more space efficient

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#4349]
When copying content from fields into `_all`, per-field boosts are copied into payloads (when the boost is != 1). These payloads store 4 bytes which are the 4 bytes of the float boost.

In practice this is quite some overhead since this payload needs to be stored for every occurrence of every term. I think using Lucene's `SmallFloat` utility class to store the boosts in a single-byte (like Lucene does for norms) would be a better trade-off?

Another option I'm thinking of is trying to improve Lucene to compress payloads: since the postings format is based on blocks, all payloads are stored sequentially, and using lz compression such as lz4 could easily take advantage of the fact that payloads are redundant (if you have only 10 string fields, there are at most 10 unique values of the boost although there are at least 128 positions per block).

**Comment by jpountz** [comment]
Yes it is! I opened https://issues.apache.org/jira/browse/LUCENE-6764 on the Lucene side, but even if it gets in using 1 byte instead of 4 would still be useful.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/19784
