### ISSUE TITLE
Bug in ES 2.4.6 documentation and also in Breaking changes doc for `transport.tcp.compress`

### ISSUE THREAD

**Issue by prudhvi** [elastic/elasticsearch#43495]
**2.4.6** (`bin/elasticsearch --version`):

**Description of the problem including expected versus actual behavior**:
Hi Team we recently upgraded our cluster from 2.4.6 to 6.6.1 and noticed a huge spike in network bandwidth on the indexing nodes . We also saw lot of frequent GC pauses on the indexing process . Turns out it's all due to disabling tcp compression which was by default `true` in 2.4.6 but `false` in 6.6.1. Doc's doesn't mention the same. Both version docs say compression is disabled by default. But our isssues went away after setting the `transport.tcp.compress` true in our transport client settings in 6.6.1 version.

I spent a lot of time figuring out the root cause as it wasn't documented in any breaking changes doc as well.

https://www.elastic.co/guide/en/elasticsearch/reference/6.6/modules-transport.html
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-transport.html

**Comment by andrershov** [comment]
I'm looking at 2.4 docs
> Set to true to enable compression (LZF) between all nodes. Defaults to false.
Now 6.6 docs
> Set to true to enable compression (DEFLATE) between all nodes. Defaults to false.

So in both versions default is false, so nothing was changed in this regard. Could you please clarify?

**Comment by prudhvi** [comment]
Yeah docs say it's false by default in 2.4 which I think is wrong because when we upgraded to 6.6.1 we have to explicitly enable to true to achieve the same bandwidth usage. So my impression was that in 2.4 the default might be true which isn't reflected in docs correctly.

**Comment by andrershov** [comment]
I'm looking at the source code and it seems that it was false by default, so docs are correct about this setting. https://github.com/elastic/elasticsearch/blob/3d32f3e9b0ac3b3f1b63e8ac815a5087f667ab3b/core/src/main/java/org/elasticsearch/transport/netty/NettyTransport.java#L220

**Comment by prudhvi** [comment]
Thanks @andrershov , I guess the setting is same in both but for some reason without explicitly enabling that compression flag, 2.4 was better in bandwidth usage. The issue we saw is very similar to https://github.com/elastic/elasticsearch/issues/21526#issuecomment-325909340
