### ISSUE TITLE
Smarter shard allocation

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#43518]
Currently Elasticsearch doesn't take memory and CPU needs into account when it decides whether to rebalance shards and where to move them.
Because of this, we turned automatic rebalancing off and do this by hand, which is painful and causes a lot of stress on the system (for example when one node falls out of the cluster, because Elasticsearch will put the shards onto different nodes than we want them, so we have to move them back).
Because of this, I'm filing this feature request.

Elasticsearch should have a smarter shard allocator, which tries to balance shards according to multiple criteria.
Controlling which is more important -I guess- is up to the user, the default could be either the current state, or a composite default, I don't know.

Some parameters, which could be considered to be added to the decision flow:
1. shard's memory needs (there is a "constant" need here (which scales with the number of the documents for eg) and a dynamic, which moves with the usage (patterns). I think a good allocator may be able to utilize both)
2. shard's CPU utilization. Take for example a heavily updated index (with other indices being more idle, but with a lot of documents), with few documents. They can end up being on fewer nodes than the cluster has, instead of spreading the shards onto more machines, increasing throughput.
3. disk IO. This can be as simple as counting Lucene read/write operations per shards.
4. anything else which may be relevant to utilize the cluster's resources to the fullest

After having these, it would be nice if nodes could be weighted according to these parameters, so if not all nodes are equal, the distribution could be modified from being evenly balanced.

Next level is an autonomous, self tuned system, which learns about nodes and their capabilities as well, but that may be too ambitious from what Elasticsearch offers now. :)

**Comment by DaveCTurner** [comment]
I think this is a more comprehensive description of the plan outlined in https://github.com/elastic/elasticsearch/issues/17213#issuecomment-383974707, particularly the idea of multidimensional costs. I remain unconvinced about the value of _balancing_ on these attributes, given the risk of excessive shard movement.

**Comment by bra-fsn** [comment]
Well, in a perfect world (where elastic nodes are forever running) not balancing on these probably means a worse result.
On shard assign time (again: in a perfect world) the new shard would be empty, hence there is no information about its usage (patterns).
All you could do to watch for the existing ones, but that will give different results.
Luckily, enabling and disabling rebalance is quite an easy operation, and one could do this in idle periods.
So I think it would be worth to add it, possibly create a switch for it (on/off), or just provide thresholds for the different metrics, like now.

**Comment by ZLightning** [comment]
Perhaps there should be some settings to tune the decision of when to rebalance.  To decide when, it would be important to know things like, at the current search/index rate, would it be worth the increased overhead, bandwidth, and disk wear to move these shards now, later, or never?  It might be a task well suited for machine learning, as it is very likely usage patterns would be predictable for most clusters based on index name, creation, etc.  For instance, if you index logs with daily index rotation, and the index sees heavy indexing for the day and heavy searching for a week, machine learning could easily know when to move the shards to the appropriately sized machine.

**Comment by pxsalehi** [comment]
This seems to be partially covered by #17213. I'll close this one. Please feel free to add a comment on #17213 if it misses some of the points here. Currently, we have no immediate plan to address this.
