### ISSUE TITLE
[doc]add more watcher example

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#43524]
Back in 2.x, there were 4 watcher examples.
![image](https://user-images.githubusercontent.com/25199092/59992237-c1568380-9685-11e9-8b76-6ad1e13a4bf7.png)

https://www.elastic.co/guide/en/watcher/current/watching-marvel-data.html#watching-memory-usage

But there is only 2.

![image](https://user-images.githubusercontent.com/25199092/59992252-d9c69e00-9685-11e9-8211-e9b0b52f3f1e.png)

https://www.elastic.co/guide/en/elastic-stack-overview/7.x/example-watches.html

It would be nice if there are more examples our users can get a grip on how things are done.

**Comment by jrodewig** [comment]
[docs issue triage]
