### ISSUE TITLE
How to improve query performance by taking only one field

### ISSUE THREAD

**Issue by guozhongtao** [elastic/elasticsearch#43520]
P 级别的数据，多个索引查询，但是只需要取一个字段如何提高查询性能?目前尝试过store_field,_id,doc_value等方式，效果都不理想。
P 级别的数据，多个索引查询，但是只需要取一个字段如何提高查询性能?目前尝试过store_field,_id,doc_value等方式，效果都不理想。
P-level data, multiple index queries, but how to improve query performance by only taking one field? At present, store_field, _id, doc_value and other methods have been tried, and the results are not satisfactory.

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
