### ISSUE TITLE
Java High Level REST Client Snapshot Create RepositoryAPI set verify false not work

### ISSUE THREAD

**Issue by ccfang** [elastic/elasticsearch#43521]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.8.0

**Description of the problem including expected versus actual behavior**:

Follow the [guide](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.8/java-rest-high-snapshot-create-repository.html) and finally set verify false like below

```java
request.verify(false);
```

It didn't work and still throw exception（failed to create blob container）

**Steps to reproduce**:

I check the source code org.elasticsearch.client.RequestConverters and maybe find the reason.

When org.elasticsearch.client.SnapshotRequestConverters's createRepository calling withVerify, it should append verify=fasle to param but the code do nothing

```java
Params withVerify(boolean verify) {
    if (verify) {
        return putParam("verify", Boolean.TRUE.toString());
    }
    return this;
}
```

Should modify like below

```java
Params withVerify(boolean verify) {
    if (verify) {
        return putParam("verify", Boolean.TRUE.toString());
    } else {
        return putParam("verify", Boolean.FALSE.toString());
    }
}
```

**Comment by original-brownbear** [comment]
Thanks for raising this @ccfang. This is indeed a bug as far as I can see, the default for verify is `true` and the code as you point out incorrectly overrides the `false` case.
