### ISSUE TITLE
`GET /_snapshot/_all/_all` times out when there are no repositories

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#43547]
Relates to changes in #42090

When there are no repositories, a request to `GET /_snapshot/_all/_all` returns a 504 timeout error.

I would expect this request to return `[]` (an empty array).

**Comment by original-brownbear** [comment]
@andrershov I think we just need to short-circuit the listener in `org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction#getMultipleReposSnapshotInfo`, instantiating a group action listener with count `0` seems to be killing us here.
