### ISSUE TITLE
[CI] IndexAliasesIT.testWaitForAliasSimultaneousUpdate failed on 7.1

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#43551]
The following assertion tripped:

```
org.elasticsearch.aliases.IndexAliasesIT > testWaitForAliasSimultaneousUpdate FAILED
    java.lang.AssertionError: 
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([C6D19736A33FE1C0:E27F6E8C0B199BE3]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.aliases.IndexAliasesIT.testWaitForAliasSimultaneousUpdate(IndexAliasesIT.java:564)
```

On this build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.1+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/41/console
    https://gradle.com/s/zkoif4f6eltmq
    https://gradle.com/s/vmlnhuhxvr6l2
    https://gradle.com/s/hcitcwwb4pvfq

I was unable to reproduce it by using

```
./gradlew :server:integTest --tests "org.elasticsearch.aliases.IndexAliasesIT.testWaitForAliasSimultaneousUpdate" -Dtests.seed=C6D19736A33FE1C0 -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=Europe/Istanbul -Dcompiler.java=12 -Druntime.java=8
```

**Comment by jaymode** [comment]
This test has not failed since the issue was raised and there is nothing actionable at this point so I am closing this issue and we can always revisit if we see a recurrence of the issue in CI.
