### ISSUE TITLE
enable_position_increments not working for phrase queries with stopwords

### ISSUE THREAD

**Issue by bdecarne** [elastic/elasticsearch#43574]
Hi there,

I'm reporting here a bug found by me and another user, witch i found the original message on https://discuss.elastic.co with no response.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1 (docker)

**Description of the problem including expected versus actual behavior**:

I'm following this guide https://stackoverflow.com/questions/31719249/how-to-query-a-phrase-with-stopwords-in-elasticsearch to run phrase queries against text with stopwords removed, and the verified answer doesn't work in Elasticsearch 7. Setting enable_position_increments to false in my query_string query doesn't do anything at all.

**Steps to reproduce**:

```
PUT /fr_articles
{
   "settings": {
      "analysis": {
         "analyzer": {
            "stop": {
               "type": "standard",
               "stopwords" : ["the"]
            }
         }
      }
   },
   "mappings": {
      "properties": {
            "title": {
               "type": "text",
               "analyzer": "stop"
            }
         }
   }
}
```
```
POST /fr_articles/test/1
{
    "title" : "Tom the king of Toulon!"
}
```
```
POST /fr_articles/_search
{
   "query": {
      "query_string": {
         "default_field": "title",
         "query" : "\"tom king\"",
         "enable_position_increments": false
      }
   }
}
```
This returns 0 results.

**Comment by jimczi** [comment]
The option is not propagated correctly so I opened https://github.com/elastic/elasticsearch/pull/43578 to fix it. However the example in the description is not correct, when set to false this option will remove the position increment that filtered terms introduce. So the query `"tom the king"` with `enable_position_increments` set to `false` will rewrite the query as if the term `the` was never present. This means that document that contain `tom king` will match while `tom the king` will not.
The option has no effect on queries that don't contain a filtered term (`the` in your example).

**Comment by bdecarne** [comment]
Thank you for this explanation, although it is disappointing for my case.

Is there a way to reach my goal without using slop ?

Thank you

**Comment by jimczi** [comment]
> Is there a way to reach my goal without using slop ?

You could write a custom stop filter that would not increment the position when removing a term, otherwise you'll need to use a `slop`. You don't want to use a `slop` because it will match terms other than stop word in the middle ?

**Comment by bdecarne** [comment]
> You don't want to use a slop because it will match terms other than stop word in the middle ?

Yep, you're right !

Thanks for the tip, i'll study that.
