### ISSUE TITLE
Windows container support for docker

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#43608]
This is a feature request, moved over from https://github.com/elastic/elasticsearch-docker/issues/67.  Users wanting this feature can add their support here to help gauge the importance of windows container support in docker.

**Comment by aidapsibr** [comment]
We are running ~8000 Windows containers in our production clusters and so far only DataDog can monitor the work. ECK is far superior for our business model, but we can't consider it due to this missing functionality.

**Comment by mark-vieira** [comment]
I'm going to go ahead and close this. I just don't think there's enough demand to justify supporting a Windows-based Docker image in the immediate future.
