### ISSUE TITLE
Add wrapperSort to SortBuilders

### ISSUE THREAD

**Issue by hudsonb** [elastic/elasticsearch#4360]
Add `wrapperSort` to `SortBuilders` like `QueryBuilders.wrapperQuery` and `FilterBuilders.wrapperFilter` allowing a JSON string representing a sort to be wrapped as a `SortBuilder`.

**Comment by vedil** [comment]
I was stuck with similar issue and thought i need SortBuilder that could take a json, but i figured SearchRequestBuilder.setExtraSource would be sufficient for me.

**Comment by clintongormley** [comment]
Just discussed this with the people who have been working on the query refactoring, who are of the opinion that we shouldn't be passing JSON in the Java API. They're also considering removing wrapperQuery, so I'm going to close this one.

**Comment by hudsonb** [comment]
So there would be no way to go from JSON to QueryBuilder? I rely heavily on this currently.

I have a thick client which generates the queries in JSON, these JSON queries are sent through a web service which then uses the wrapperQuery to combine the query (using bool query) with some other clauses that are added by the server.

**Comment by javanna** [comment]
I think it would make more sense to send a json request through REST rather than using the java api for that. The idea is that the java api uses the transport layer (binary protocol), so you should be specifying java objects and no parsing should be involved. On the other hand the REST layer does parse queries into java objects. Makes sense?

**Comment by hudsonb** [comment]
From the client since we couldn't because we don't expose elasticsearch directly.

From the service we could, but we make heavy use of the Java API there - the query is just one piece that happens to be JSON since its generated by the client and sent to the service as JSON.

For example as part of one service call we do something like this:
```
HistogramBuilder histogram = histogram("h")
                                                 .field(field)
                                                 .interval(interval)
                                                 .minDocCount(minCount);

client.prepareSearch(alias)
        .setSearchType(SearchType.COUNT)
        .setTypes(eventType)
        .setQuery(filteredQuery(query, wrapperFilter(request.getFilter()))
        .addAggregation(histogram)
        .execute();
```

The only use of straight JSON is in the wrapperFilter call, where we get the JSON filter spec from the request sent by the client.
