### ISSUE TITLE
Enable Docker content trust

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#43609]
Note: This issue is transferred from https://github.com/elastic/elasticsearch-docker/issues/158.

From the original issue:

Please enable [content trust](https://docs.docker.com/engine/security/trust/content_trust/) for all Docker images in docker.elastic.co.
Content trust allows clients to verify that Docker images are actually built by the distributor.

**Comment by mark-vieira** [comment]
This would have to be implemented in release manager and by the infra release team. There is an existing issue regarding that so I'm closing this one.
