### ISSUE TITLE
Response handlers not always called

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#43649]
The `Transport.ResponseHandlers` in `TransportService` stores resources for pending responses. A response handler will stay in this map until one of the following happens:

1. A response is received
2. The corresponding channel is closed
3. The request times-out (not all requests have timeouts)

Theoretically the resources should always be eventually freed. However, we sometimes see heap dumps with handlers that have been around for over a day. If proper TCP keep-alive mechanisms are in place to kill dead channels, this should not happen.

However, part of the problem is that it is very difficult to debug these issues when there is a legitimate bug which causes a response to be lost.

We need to discuss how we might improve visibility into these issues and potentially avoid issues related to hanging response handlers.

**Comment by original-brownbear** [comment]
The infrastructure I added in #43259 might be helpful here in spots where we can track this by tracking the object/listener that should've invoked the response handler.

**Comment by original-brownbear** [comment]
We discussed this during our team meeting today. As a first step towards a solution here, I will add functionality to our testing that ensures that we don't leave dangling tasks/transport-handlers after tests.

**Comment by original-brownbear** [comment]
The above has been added in so far that we now close the transport service in a clean way that ensures all handlers are resolved. We also have much better leak tracking now than we did in the past by wrapping the Netty buffers' leak tracking better than we used to. -> closing here for now, since this hasn't been an issue in the recent past.
