### ISSUE TITLE
[ML] Data frame source index seems to be fully re-read when continuous transform moves nodes

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#43662]
In a rolling upgrade, or node failure scenario, a continuous transform seems to re-read the entire index when it is moved to a new node. I think the last checkpoints timestamp information may be missed when the transform starts executing again on its new node. 

I saw this behavior by looking at the stats between the the continuous transform moving between nodes. The documents read increased by the number of docs present in the index each time it changed nodes. 

It could either be:  
* the stats are being gathered incorrectly (the docs are not actually being read)
* The entire index is being read again when the task starts again. 

`DataFrameTransformPersistentTasksExecutor` and how it reads in checkpoint information is suspect.

**Comment by benwtrent** [comment]
Additional info:

* This happens when we have fully reached a checkpoint
* It happens right when the task starts executing again (no new data in the index yet).

**Comment by droberts195** [comment]
I will add some internal cluster tests similar to `MlDistributedFailureIT` and `BasicDistributedJobsIT` to enable these scenarios to be more easily tested.

**Comment by hendrikmuhs** [comment]
The problem has been identified, the change detection works in 2 steps:

1. get the list of changes
2. query using the list of changes

We are not persisting the output of step 1 and after a failure we skip step 1 and continue with step 2.

The 2 step approach has been identified as problematic in other respects therefore the solution is not to persist step 1 but combining 1 and 2 which solves another problem, namely the terms limit (65k).

**Comment by hendrikmuhs** [comment]
fixed with https://github.com/elastic/elasticsearch/pull/44219
