### ISSUE TITLE
setup-password Master Not Connected

### ISSUE THREAD

**Issue by thewasta** [elastic/elasticsearch#43676]
Elastic Version: 6.6.1
My Enviroment: 3 nodes.
Master Node: 192.168.1.142
Slave 1: 192.168.1.144
Slave 2: 192.168.1.146
cluster.name: elasticppo
node.name: ${HOSTNAME}
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
bootstrap.memory_lock: true

#Each Node has own server .144/.146
network.host: ["127.0.0.1","192.168.1.142"]

discovery.zen.ping.unicast.hosts: ["192.168.1.142","192.168.1.144","192.168.1.146"]
discovery.zen.minimum_master_nodes: 2
#action.destructive_requires_name: true

#Slaves nodes has his own certs elasticslave1, elasticslave2 In their respective server
xpack.security.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/certs/elasticmaster.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/certs/elasticmaster.p12

Maybe I have to post this problem in forum but I am not able to write more because of limit per day for new users.

### Steps to reproduce
Before to active 

> xpack.security.enabled: true

Elastic works fine, not master problems and health is green, but now I want to integrate user login and I got this error

>Failed to determine the health of the cluster running at http://192.168.1.142:9200
Unexpected response code [503] from calling GET http://192.168.1.142:9200/_cluster/health?pretty
Cause: master_not_discovered_exception
It is recommended that you resolve the issues with your cluster before running elasticsearch-setup-passwords.
It is very likely that the password changes will fail when run against an unhealthy cluster.
Do you want to continue with the password setup process [y/N]N

I have tried to
>curl -XGET 192.168.1.142:9300

And the response is:
>This is not an HTTP port

And If I try to 9200, it response with `missing authentication token for REST request[/]`
I think it's reasonable because now I'm using login and is asking for user/password

If you can this is my other issue which is in Elastic Forums [LINK](https://discuss.elastic.co/t/trobling-with-https-configuration/187557) and ref this issue.

Thanks a lot!

**Comment by henningandersen** [comment]
@thewasta thanks for your interest in elasticsearch. I noticed that you have been able to respond to the forum topic and I hope you will continue the conversation there. I will therefore close this issue.
