### ISSUE TITLE
OpenID Connect realm fails when special characters are present in client id

### ISSUE THREAD

**Issue by cpmoore** [elastic/elasticsearch#43709]
If special characters are present in the client id, the token request fails with the following error

```
[2019-06-27T08:33:56,252][TRACE][o.e.x.s.a.o.OpenIdConnectAuthenticator] [node1] Received Token Response from OP with status [400] and content [{"error":"invalid_request","error_description":"MSIS9692: Received invalid OAuth request. The Basic Authorization header must have ClientID and ClientSecret UrlEncoded then separated by \u0027:\u0027."}]
```
The original client_id was in the format of `http://adfshost/client`, after being changed to a client id without / or : in it, authentication started working.

Looking at the code for the realm it appears as if the client id and secret are not being url encoded when set as the basic authentication header.  
https://github.com/elastic/elasticsearch/blob/46d5d68bbbb8dd68720aec2ac186061ab63d31dc/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java#L468-L470

**Comment by jkakavas** [comment]
Thank you for reporting this @cpmoore

**Comment by cpmoore** [comment]
No problem!  Thanks for developing the realm in the first place.  I'm not a fan of SAML.

**Comment by jkakavas** [comment]
This is a bug according to the specification, as both client id and client password need to be encoded using the `application/x-www-form-urlencoded` encoding algorithm when used for HTTP Basic
   authentication. https://tools.ietf.org/html/rfc6749#section-2.3.1
