### ISSUE TITLE
[Docs] refresh_interval change made it unclear

### ISSUE THREAD

**Issue by tbuchier** [elastic/elasticsearch#43724]
Hello, 

The refresh_interval documentation have changed in 7.0+, making it's new behavior unclear. 

**Describe the Issue**:

https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html#_unset_or_increase_the_refresh_interval

> By default, Elasticsearch runs this operation every second, but only on indices that have received one search request or more in the last 30 seconds. This is the optimal configuration if you have no or very little search traffic (e.g. less than one search request every 5 minutes) and want to optimize for indexing speed.
> 
> On the other hand, if your index experiences regular search requests, this default behavior means that Elasticsearch will refresh your index every 1 second. If you can afford to increase the amount of time between when a document gets indexed and when it becomes visible, increasing the index.refresh_interval to a larger value, e.g. 30s, might help improve indexing speed.

If I modify the refresh_interval setting, the documentation isn't clear if the behavior " but only on indices that have received one search request or more in the last 30 seconds." is kept or not.

**Example :** 

If I set  refresh_interval to 5s
If I'll have a refresh:
 - every 5 seconds, but only on indices that have received one search request or more in the last 30 seconds.

- every 5 seconds contact, no matter what

From my testing, the behavior (only on indices that have received one search request or more in the last 30 seconds) "break" and isn't applied anymore if I modify the refresh_interval. 

I think documentation should specify that

**Comment by dliappis** [comment]
Thanks for raising this issue.
This is related to https://github.com/elastic/elasticsearch/pull/27500

The last sentence in the commit reads:

> This behavior is only applied if there is no explicit refresh interval set.

So your observation validates this and indeed we need a clarification in the docs.
