### ISSUE TITLE
strict_date_optional_time does not support "," as separator for fractions

### ISSUE THREAD

**Issue by simioa** [elastic/elasticsearch#43730]
**Elasticsearch version** (`bin/elasticsearch --version`): 
7.2.0

**Plugins installed**: []

**JVM version** (`java -version`): 
Bundled JDK

**OS version** (`uname -a` if on a Unix-like system): 
Red Hat 7.6 3.10.0-957.12.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:
strict_date_optional_time does not support "," as separator for fractions but ISO 8601 says that "," and "." should both be accepted.
Furthermore the ESJsonLayout also uses "," as separator which causes mapping exceptions when elasticsearch logs are indexed.
https://github.com/elastic/elasticsearch/blob/508c38a450a48279bd160c6b8fb2d6703eaf1105/server/src/main/java/org/elasticsearch/common/logging/ESJsonLayout.java#L63

**Steps to reproduce**:
1. Create Mapping:

```
{
  "order": 10,
  "index_patterns": [
    "date-test"
  ],
  "mappings": {
    "properties": {
      "time": {
        "format": "strict_date_optional_time||epoch_millis",
        "type": "date",
        "doc_values": true
      }
    }
  },
  "aliases": {}
}
```
2. Create Document in date-test Index with "," as separator:
```
POST date-test/_doc
{
  "time": "2019-06-28T08:30:39,104+0200"
}
```
3. Indexing fails with mapper_parsing_exception:

> failed to parse date field [2019-06-28T08:30:39,104+0200] with format [strict_date_optional_time||epoch_millis]

4. Replace "," with "." and try to index:
```
POST date-test/_doc
{
  "time": "2019-06-28T08:30:39.104+0200"
}
```
5. Document is indexed successfully

**Comment by markharwood** [comment]
Does this behaviour depend on the Locale that the JVM is configured with?

**Comment by simioa** [comment]
I don't know if this is the correct setting but I tried setting different locales with the following JVM Parameters:

"ES_JAVA_OPTS=-Duser.country=US -Duser.language=en"

and 

"ES_JAVA_OPTS=-Duser.country=DE -Duser.language=de"

Both Configurations throw mapper_parsing_exception

**Comment by markharwood** [comment]
Maybe try[ the locale on the date mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html#date-params)?

**Comment by droberts195** [comment]
Another thing to try if you're not tied to `strict_date_optional_time` is to change the format to `iso8601`.  That accepts both comma and dot in all locales.  But I accept that if you're tied to `strict_date_optional_time` for backwards compatibility reasons it's not an option.

**Comment by simioa** [comment]
I set the locale on the Date Mapping, we still get `mapper_parsing_exception`.
It tried it with the locales `de_DE` and `en_US`.
It looks like this is not Locale specific.

Thanks for the tip with the `iso8601` format, it worked for me!
Is this format officially supported? It is not documented in the official documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#built-in-date-formats

Furthermore, the `strict_date_optional_time` is defined as an generic iso datetime parser, shouldn't it therefore also support comma in all locales?
It was also not logged into the 6.8.1 deprecation log that the `strict_date_optional_time` parser was deprecated or that behavior would change which started to cause problems after upgrading elasticsearch to Version 7  

We would have to check if the `iso8601` parser works for all our indices and applications but this would be tied to a very high amount of work for us because we would have to check every Index and every Application for compatibility and correct parsing of the timestamps.

**Comment by pgomulka** [comment]
@simioa Thank you for raising this.
This indeed looks like a breaking change and I will aim to fix it soon. 
We don't change the `DecimalPoint` when Locale changes. In fact we only used java.time default `DecimalStyle.STANDARD` which uses `.` (except for the `is8601` parser).

`strict_date_optional_time` is certainly to be fixed, but there might be some more - will update the issue later on this.
