### ISSUE TITLE
PDF annotations not indexed ?

### ISSUE THREAD

**Issue by Stef-33560** [elastic/elasticsearch#43732]
Hi all :)

 I've got a huge quantity of PDF file containing only images and comments (annotations). To let users to find those documents, I would like to index the comments stored in those PDF files. Actually, my elasticsearch 5.6.3 does not seems to index the comments/annotations :(

May you tell me how to do this ?
Notice I wouldn't like to use OCR (PDFBox/Tesseract) but just to use the ALL the text areas already stored in the PDF files, including the comments/annotations :)

Thanks a lot !

**Comment by dadoonet** [comment]
Please ask this question on https://ela.st/forum where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on https://ela.st/forum.

Thanks!
