### ISSUE TITLE
GET _template API can create a template

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#43736]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.2 / 6.7.0

**Description of the problem including expected versus actual behavior**:
It is possible to create a new template by using the GET _template API with a body, as shown in the STR below. The expectation is that this should be impossible, as only a PUT or POST should be able to create a new template.

**Steps to reproduce**:

1. Run: `DELETE _template/test`
2. Run `GET _template/test`
3. Observe there is no template named "test"
4. Run:
```
GET _template/test
{ 
  "order" : 10, 
  "index_patterns" : ["test-*"]
}
```
5. Run `GET _template/test`
6. Observe that there is a template named "test"

This behaviour is verified on 6.6.2 and 6.7.0. It may also be a bug in other versions too.

**Comment by dakrone** [comment]
Legacy templates are deprecated and this issue is incredibly old, so I am going to close it. We can re-open if this occurs with newer templates.
