### ISSUE TITLE
Repository to use XPack in Laravel

### ISSUE THREAD

**Issue by thewasta** [elastic/elasticsearch#43735]
I would like to know if there is any repository/library to use Xpack in Laravel, currently I'm using
[cviebrock/laravel-elasticsearch](https://github.com/cviebrock/laravel-elasticsearch) but It haven't for X-pack and then I decided to change to this repository [ElasticSearch-PHP](https://github.com/elastic/elasticsearch-php), this one give you a link to a repository in case you want to use X-Pack: [ElasticSearch-X-Pack](https://github.com/elastic/elasticsearch-x-pack-php). But this repository doesn't work. Any alternative?

**Comment by thewasta** [comment]
In case you ask Why Xpack repository doesn't work:
Because this repository needs Elastic-PHP 5.0, and this version needs ElasticSearch >= 5.0, < 6.0, and this version of ElastcSearch, XPack isn't free.

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
