### ISSUE TITLE
Move MappingMetaData to use internal compressed generic content (prefer SMILE)

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#4377]
Today, `MappingMetaData` has an internal `CompressedString` that is used to store the json serialized version of the mapping. It would be much better if we had it stored as compressed, but in SMILE format, that will be much more storage efficient.

I think it would make sense to create a `CompressedXContent` class, that would store internally the content compressed as bytes (based on a specific content type if needed). Then, we can use it, in SMILE format, to store the mapping. Also, `CompressedXContent` can include helper methods to convert to json and so on (that can make use of the XContentHelper classes).

Last, for very large mappings, we can have a paged bytes instead of a single byte array in the `CompressedXContent` class.

**Comment by jpountz** [comment]
Closing: reasonable mappings are tiny once compressed anyway.
