### ISSUE TITLE
SQL: alias type of fields return no value if they need to be extracted from _source

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43798]
At the moment, ES SQL extracts data for the displayable fields from either doc values (preferably) or _source, through the use of `docvalue_fields` element or `_source` `includes/excludes`, respectively.

An `alias` type of field, though, if pointing to a field that cannot be extracted from docvalue_fields - a `text` field - it won't return any value from SQL. This is because of a limitation `alias` fields have - https://www.elastic.co/guide/en/elasticsearch/reference/7.x/alias.html#unsupported-apis. I believe this should be documented in the Limitations page, as it might not be so obvious to the usual SQL user.

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by astefan** [comment]
This is no longer needed, since [now ES SQL uses the `fields` API to extract the needed values](https://github.com/elastic/elasticsearch/issues/67727). Alias field types are supported with `fields`.
