### ISSUE TITLE
Highlighters should reject ignored keyword field early

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#43800]
Highlighters are able to handle `text` and `keyword` field by reanalyzing their content at search time. However they don't check if the field was ignored at search time due to the `ignore_above` option. For instance a `keyword` field that is greater than the `ignore_above` option would skip indexing but if it is set in an highlighter option, the content will be extracted from `_source` and reanalyzed (ignoring `ignore_above` option). We should check the `ignore_above` option at highlighting time in order to avoid hitting the `highlight.max_analyzed_offset` on a field that was ignored at index time.

**Comment by mayya-sharipova** [comment]
Related proposal: https://github.com/elastic/elasticsearch/issues/52155#issuecomment-593508032 to introduce `ignore_above` parameter in a highlighter.
That proposal doesn't replace the current issue.
