### ISSUE TITLE
SQL: allow configuring cert validation mechanism for JDBC driver connection

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43812]
"There's no way to override the SSL cert validation outside of a [keystore on the filesystem](https://github.com/elastic/elasticsearch/blob/dded86344a6f42fd3a59206cf28e0eda40e3282d/x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/SslConfig.java#L95-L109). This can be an issue when connecting to a dynamic set of servers that you do not have added to your local JKS (or when you don't have a system specific one like in ephemeral container deployments).

It's possible to work around this by dynamically creating a JKS file for each server but it's way more convenient to be able to do it all in memory either by specifying a custom `SSLSocketFactory` / `TrustManager`. One way to implement this is to add a JDBC connection property to specify a `SSLSocketFactory` class name and arbitrary string arg. If defined, then it'll get instantiated at connection time (with arg as a constructor param) rather than the default `SSLSocketFactory` via the default `SSLContext`. This gives the invoker the freedom to perform whatever validations they'd like (e.g. everything from blind trust to an in-memory cert store)."

**Comment by wchaparro** [comment]
Superceded by ES|QL
