### ISSUE TITLE
Draw attention to transport port in remote cluster documentation

### ISSUE THREAD

**Issue by akki** [elastic/elasticsearch#43858]
It would be nice to emphasize on the fact that remote cluster connections require another port (not the one Elasticsearch is usually available on).

I am not very clear on how these ports are different but after struggling a lot to set up a cross-cluster search I realised that Elasticsearch exposes port 9300 as well for some things and it is `9300` that needs to be mentioned in the `seeds`.

I do see that it is being used in the example here - https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html. But I didn't realise that `9300` was being used instead of `9200` intentionally until I read [this comment](https://github.com/elastic/elasticsearch/issues/30247#issuecomment-389227201) from Mr. javanna.

**Comment by jimczi** [comment]
> It would be nice to emphasize on the fact that remote cluster connections require another port (not the one Elasticsearch is usually available on).

The documentation explicitly says that:
`All the communication required between different clusters goes through the` [transport layer](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html).
The linked documentation explains what the transport module is and how the communication is handle in this module. However I guess that it would help to repeat that the transport port should be used on the first mention of `seeds` in the snippet examples. Would you be interested to provide a patch for this ?

**Comment by akki** [comment]
@jimczi I admit I did somehow skipped going through the `transport layer` link when it was mentioned in the docs.

Do you mean something like adding another info point with the snippet (see attached picture)? I think that would is a good idea.

I would be happy to send a patch but it would quite helpful for me if you could tell me where these docs reside (Elasticsearch docs code seems a bit overwhelming to me as a beginner 😅).

Thanks for your quick reply!

![Remote_clusters___Elasticsearch_Reference__7_2____Elastic](https://user-images.githubusercontent.com/4801628/60506038-2ac23c00-9cef-11e9-9e9d-612c0f7a055a.jpg)

**Comment by jimczi** [comment]
> Do you mean something like adding another info point with the snippet (see attached picture)? I think that would is a good idea.

Yes, if you think it is helpful ;)

> I would be happy to send a patch but it would quite helpful for me if you could tell me where these docs reside

You can find this doc [here](https://github.com/elastic/elasticsearch/blob/master/docs/reference/modules/remote-clusters.asciidoc).

**Comment by akki** [comment]
@jimczi - https://github.com/elastic/elasticsearch/pull/43883
