### ISSUE TITLE
span_near query does not return all occurrences that satisfy the conditions.

### ISSUE THREAD

**Issue by alwag85** [elastic/elasticsearch#43867]
**Elasticsearch version:** 6.7.0 build_hash: 8453f77 lucene_version: 7.7.0
**Plugins installed:** No plugins installed
**JVM version:** 1.8.0_201
**OS version:** Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior:**
Span_near query does not return all occurrences that satisfy the conditions. Because of this, the span_not query may not work as expected.
**Steps to reproduce:**
```javascript
    PUT span-near-test/doc/1
    {
        "field1": "la hoya hoya hoya"
    }
```
```javascript
POST span-near-test/_search
{
    "query": {
        "span_near" : {
            "clauses" : [
                { "span_term" : { "field1" : "hoya" } },
                { "span_term" : { "field1" : "la" } }
            ],
            "slop" : 50,
            "in_order" : false
        }
    },
    "highlight" : {
        "fields" : {
            "*" : {}
        }
    }
}
```
**Expected highlight: **<em>la</em> <em>hoya</em> <em>hoya</em>  <em>hoya</em>
**Actual highlight:** <em>la</em> <em>hoya</em> hoya hoya
```javascript
POST span-near-test/_search
{
    "query": {
        "span_not" : {
            "include" : {
                "span_term" : { "field1" : "hoya" }
            },
            "exclude" : {
                "span_near" : {
                    "clauses" : [
                        { "span_term" : { "field1" : "la" } },
                        { "span_term" : { "field1" : "hoya" } }
                    ],
                    "slop" : 50,
                    "in_order" : false
                }
            }
        }},
        "highlight" : {
            "fields" : {
                "*" : {}
            }
        }
}
```
**Expected:** No docs should be returned 
**Actual:** Doc 1 is returned.

**Comment by benwtrent** [comment]
Span is being deprecated in favor of intervals:

https://github.com/elastic/elasticsearch/issues/110491
