### ISSUE TITLE
SQL: failure while resolving a set of indices that have fields that are not found in other indices

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43876]
The simplest example that reproduces this is a minimum of 4 indices where each of them has fields that cannot be found in other indices. Also, this bug is present in 7.2+.

```
POST /index1/_bulk
{"index":{}}
{"field1": "bla"}
```

```
POST /index2/_bulk
{"index":{}}
{"field2": "bla"}
```

```
POST /index3/_bulk
{"index":{}}
{"field3": "bla"}
```

```
POST /index4/_bulk
{"index":{}}
{"field4": "bla"}
```

Then, creating an alias covering all these 4 indices:

```
{
    "actions" : [
    	{ "add" : { "index" : "index4", "alias" : "my_alias" } },
    	{ "add" : { "index" : "index3", "alias" : "my_alias" } },
        { "add" : { "index" : "index2", "alias" : "my_alias" } },
        { "add" : { "index" : "index1", "alias" : "my_alias" } }
    ]
}
```

And running a simple `SELECT * FROM my_alias` will return:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Illegal Capacity: -1"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Illegal Capacity: -1"
  },
  "status": 400
}
```

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/341006e9913e831408f5bbc7f8ad8c453a7f630e
7.x (7.4.0): https://github.com/elastic/elasticsearch/commit/9957b66d2ec4db476640d5930156fce4b344d2bf
7.3 (7.3.1): https://github.com/elastic/elasticsearch/commit/9a8406f73dda2fdcfc07233284c8eb3dd31da1e7
7.2 (7.2.1): https://github.com/elastic/elasticsearch/commit/911fe8495374f26eb814323d6a2214e7ed2ba85e

**Comment by blfrantz** [comment]
Thanks for the quick fix @astefan.  I have a question, though: the issue description and fix indicate that this is specific to SQL, but I seem to be having the same problem in Canvas when doing a "raw documents" query when my Kibana index pattern matches many indices (I haven't configured any aliases).  If I use an index pattern without a wildcard (one concrete index), it works.  Do you expect this to fix that case as well, or should I file a separate bug?  Or, when will the cherry-pick be in the 7.2 docker image so I can try the fix out (or will it)?

**Comment by astefan** [comment]
@blfrantz indeed, this is a specific issue in SQL. If you used an SQL query in Canvas in your test and still see the issue, it's very likely that you are using a version of Elasticsearch that doesn't have the fix. The version labels in this github issue as well as the versions mentioned in my latest comment should be ones that will have the fix.
