### ISSUE TITLE
Clarify G1GC support on docs

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#43885]
As of 6.5.0, [G1GC is now supported by Elasticsearch](https://www.elastic.co/blog/elastic-stack-6-5-0-released).

We should document this, perhaps in the [setup page](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html).

**Comment by bczifra** [comment]
Related: https://github.com/elastic/elasticsearch/issues/41358

**Comment by jrodewig** [comment]
Closing as this was addressed with #44145.

Please comment or re-open if any additional documentation is needed.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving this open as it's still relevant.

**Comment by williamrandolph** [comment]
@jrodewig @debadair Is this issue still relevant? It looks like we have some discussion of garbage collectors on the page about the serial collector check: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/_use_serial_collector_check.html

That paragraph mentions that we default to using G1GC, and that CMS will only be used if you don't use the JVM shipped with Elasticsearch.

**Comment by jrodewig** [comment]
Thanks for the ping @williamrandolph.

I'm going to close this issue. With https://github.com/elastic/elasticsearch/pull/49123, we now default to G1GC for JDK 14+. With https://github.com/elastic/elasticsearch/pull/59667, Elasticsearch 7.11+ ergonomically adjusts G1GC options based on heap size.

While users can manually adjust G1GC options, I don't think we should encourage it or document it in depth. That effort can be covered in #53889.
