### ISSUE TITLE
ElasticSearch Documentation is wrong for update by query

### ISSUE THREAD

**Issue by yesnid** [elastic/elasticsearch#43884]
The documentation on this [page](https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.1/java-docs-update-by-query.html), is incorrect in that it shows the argument of the script and language being passed to the new Script constructor in reversed order.

`UpdateByQueryRequestBuilder updateByQuery =
  new UpdateByQueryRequestBuilder(client, UpdateByQueryAction.INSTANCE);
updateByQuery.source("source_index")
    .script(new Script(
        ScriptType.INLINE,
        "if (ctx._source.awesome == 'absolutely') {"
            + "  ctx.op='noop'"
            + "} else if (ctx._source.awesome == 'lame') {"
            + "  ctx.op='delete'"
            + "} else {"
            + "ctx._source.awesome = 'absolutely'}",
        "painless",
        Collections.emptyMap()));
BulkByScrollResponse response = updateByQuery.get();`

Note that the correct order is ScriptType, Language, Code, Params.

**Comment by henningandersen** [comment]
@yesnid thanks for reporting this, I have opened #43907 to address this.

Notice that you are looking at the documentation for the [deprecated transport client](https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.1/java-api.html).

**Comment by debadair** [comment]
Closing as fixed.
