### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

### ISSUE THREAD

**Issue by NineSwordsMonster** [elastic/elasticsearch#43911]
**Describe the feature**:

A gc deprication error is being shown, then shutdown soon.

**Elasticsearch version** (`bin/elasticsearch --version`):
`7.2.0`
`docker pull docker.elastic.co/elasticsearch/elasticsearch:7.2.0`

**Plugins installed**: []

**JVM version** (`java -version`):
I use docker image, I dont know really.

**OS version** (`uname -a` if on a Unix-like system):
Darwin ErasmeMacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

OpenJDK 64-Bit Server VM warning: __Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release__.

What puzzles me is that when I start two ESs, one can start successfully, but the other fails.
BTW, my `mysql container` will close after I use `docker-compose up`

inspect my mysql container:
```json
[
    {
        "Id": "356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032",
        "Created": "2019-07-03T09:06:32.5568395Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "mysqld"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9221,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-07-03T11:04:41.7383267Z",
            "FinishedAt": "2019-07-03T10:56:02.7957783Z"
        },
        "Image": "sha256:c7109f74d339896c8e1a7526224f10a3197e7baf674ff03acbab387aa027882a",
        "ResolvConfPath": "/var/lib/docker/containers/356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032/hostname",
        "HostsPath": "/var/lib/docker/containers/356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032/hosts",
        "LogPath": "/var/lib/docker/containers/356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032/356f72819503a9f78e32061afed0a1f436ecd3a615f8b9e7945beed3d9a37032-json.log",
        "Name": "/mysql",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "mysql:/var/lib/mysql"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "3306/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3306"
                    }
                ],
                "33060/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "33060"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ff18b614fd582eb310aa3b53e914466b2945ed93f56b6515199f128c10bc0499-init/diff:/var/lib/docker/overlay2/ef94c269761e145ecb1c8a33f728f16e4e3d3d0e0c7e06b6b958a45f9d2127fc/diff:/var/lib/docker/overlay2/6b264664a345b9f1e9aef82bdf4b70b96c547d0ceb19db2a4d5073a7ef2e5519/diff:/var/lib/docker/overlay2/d014d270a405af3e1a02634af044be8d0c29a1ea5532e63a2852c88d07d2cf60/diff:/var/lib/docker/overlay2/80a05c250e324a58795d3efda4c44d4102e027c9a22ba33a04ecd39855e96d44/diff:/var/lib/docker/overlay2/2b3dc3f1d4b633a538a8a8aefe7c28fad9ec715a4ca8a93036b428ac450507d1/diff:/var/lib/docker/overlay2/1fecdd89abf1f76f931bf5f4cda8b32afa141feebc4adf66b70402639ca8fb5c/diff:/var/lib/docker/overlay2/dffded761d89063934cec0aa299b1fb9447a740889a33a7c5cc1288e4acfedf6/diff:/var/lib/docker/overlay2/a982eca650da7d9d324142a46866bffbb76a1b3367489f08a5e701ddc9d478bd/diff:/var/lib/docker/overlay2/93f1ae42c652629d2376c759678c521d7a77897a1c84b426fb2cb01de4bb4641/diff:/var/lib/docker/overlay2/a128f80791df84ff7dd3d64db3310766b44c4b0808aba1489deb49d4f2e3629f/diff:/var/lib/docker/overlay2/ff28c5d5c706a5479a08859e39ff2c41713f6c7ececc74c1ab00492ba6f8dbf1/diff:/var/lib/docker/overlay2/904bcc52be1e9ceb8f1db8f9768fc139e1bafb823d422f8db747833d7f8a295b/diff",
                "MergedDir": "/var/lib/docker/overlay2/ff18b614fd582eb310aa3b53e914466b2945ed93f56b6515199f128c10bc0499/merged",
                "UpperDir": "/var/lib/docker/overlay2/ff18b614fd582eb310aa3b53e914466b2945ed93f56b6515199f128c10bc0499/diff",
                "WorkDir": "/var/lib/docker/overlay2/ff18b614fd582eb310aa3b53e914466b2945ed93f56b6515199f128c10bc0499/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "mysql",
                "Source": "/var/lib/docker/volumes/mysql/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "356f72819503",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "33060/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MYSQL_ROOT_PASSWORD=root",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "MYSQL_MAJOR=8.0",
                "MYSQL_VERSION=8.0.16-2debian9"
            ],
            "Cmd": [
                "mysqld"
            ],
            "ArgsEscaped": true,
            "Image": "mysql",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "efec56cd3943eeaa31c265de0e396be9eb7255619040a09c434d0a3387c7ee5b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3306"
                    }
                ],
                "33060/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "33060"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/efec56cd3943",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "c9fc4d6b3c6969fb7f5004803cf49c4295bd750b1431753d7c5b474cc95e97fc",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "06359789bca3576e9d846bb7eb2ba522c3f9a3dfea67582b49825eb63077f8ed",
                    "EndpointID": "c9fc4d6b3c6969fb7f5004803cf49c4295bd750b1431753d7c5b474cc95e97fc",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

```
$ docker-compose up
Creating network "docker_esnet" with the default driver
Creating es02 ... done
Creating es01 ... done
Attaching to es02, es01
es02    | Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
es02    | output:
es02    |
es02    | error:
es02    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es02    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es02    | 	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
es02    | 	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
es02    | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
es02    | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
es01    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es01    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
es02 exited with code 1
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,481+0000", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [12.9gb], net total_space [29.2gb], types [ext4]"  }
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,487+0000", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "heap size [512mb], compressed ordinary object pointers [true]"  }
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,491+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "node name [es01], node ID [ErvCPMVsSpK357oc2BztiA], cluster name [docker-cluster]"  }
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,491+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "version[7.2.0], pid[1], build[default/docker/508c38a/2019-06-20T15:54:18.811730Z], OS[Linux/4.9.125-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/12.0.1/12.0.1+12]"  }
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,492+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "JVM home [/usr/share/elasticsearch/jdk]"  }
es01    | {"type": "server", "timestamp": "2019-07-03T11:00:16,492+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "es01",  "message": "JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-2384203903017900189, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:-UseConcMarkSweepGC, -XX:-UseCMSInitiatingOccupancyOnly, -XX:+UseG1GC, -XX:InitiatingHeapOccupancyPercent=75, -Dio.netty.allocator.type=unpooled, -XX:MaxDirectMemorySize=268435456, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]"  }
Killing es01  ... done
```

my docker-compose.yml is

```yaml
version: '2.2'
services:
  es01:
    image: elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC
                                        -XX:-UseCMSInitiatingOccupancyOnly
                                        -XX:+UseG1GC
                                        -XX:InitiatingHeapOccupancyPercent=75"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: elasticsearch:7.2.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC -XX:-UseCMSInitiatingOccupancyOnly -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=75"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:

```

**Comment by NineSwordsMonster** [comment]
not this error cause

**Comment by lionants02** [comment]
in kubernetes deployment will loop restart inline "OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated..."
I am looking for a solution.

**Comment by liuxf1993** [comment]
had you solve this issue? I meet the same problem, when I try to run the elasticsearch
`[root@VM_0_13_centos elasticsearch-7.3.0]# ./bin/elasticsearch -d -p pid
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
output:

error:
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)`

**Comment by liuxf1993** [comment]
had you solve this issue? I meet the same problem, when I try to run the elasticsearch
`[root@VM_0_13_centos elasticsearch-7.3.0]# ./bin/elasticsearch -d -p pid
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
output:

error:
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)`

**Comment by liuxf1993** [comment]
had you solve this issue, when I try to run the elasticsearch, it failed
![4CC((EKG2)GHHOFGWNL2AO6](https://user-images.githubusercontent.com/25604624/62407320-f7721600-b5e8-11e9-9460-03d84a23cb15.png)

**Comment by JX-Wang** [comment]
The same error, java start failed and there is no log output
![image](https://user-images.githubusercontent.com/26851488/62452862-9cd0e980-b7a3-11e9-8070-759661674526.png)

**Comment by mostafaebrahimi** [comment]
same error on `Debian` when try to start `elasticsearch` service

**Comment by lionants02** [comment]
I use it on Kubenes. It appears that I put too little memory.,I solved by adding Ram.

**Comment by liuxf1993** [comment]
yes,I think  this error is caused by the little memory, refer to another issue https://github.com/elastic/elasticsearch/issues/45170

I run the es on the ECS, just 1G RAM, I let it run successfully by revise the Document  path-to-es/config/jvm.options
`-Xms108m
-Xmx108m`
the number is depend on your machine.
Hope my answer can help you

**Comment by hichenning** [comment]
use it on VMware workstation , solved by appending RAM, TK U

**Comment by tain198127** [comment]
> yes,I think this error is caused by the little memory, refer to another issue #45170
> 
> I run the es on the ECS, just 1G RAM, I let it run successfully by revise the Document path-to-es/config/jvm.options
> `-Xms108m -Xmx108m`
> the number is depend on your machine.
> Hope my answer can help you

It is WORK well! Thanks a lot! You save me.

**Comment by ceskhiemle** [comment]
I found one topic here https://discuss.circleci.com/t/elasticsearch-container-got-killed/17654/3. I resolved my issue base on it.
Hoping it can help you guys.

**Comment by startshineye** [comment]
1.you may run es as root  
![1](https://user-images.githubusercontent.com/19678129/69491229-27f9fa80-0ecd-11ea-9ac5-8ed63b905465.png)
2.It appears that I put too little memory 
Document path-to-es/config/jvm.options
-Xms512m -Xmx512m

**Comment by MaryMaryGuo** [comment]
> > yes,I think this error is caused by the little memory, refer to another issue #45170
> > I run the es on the ECS, just 1G RAM, I let it run successfully by revise the Document path-to-es/config/jvm.options
> > `-Xms108m -Xmx108m`
> > the number is depend on your machine.
> > Hope my answer can help you
> 
> It is WORK well! Thanks a lot! You save me.

I have any issue, how to revise jvm.options file?

**Comment by MaryMaryGuo** [comment]
What should I change?

**Comment by falcantar** [comment]
> **Describe the feature**:
> 
> A gc deprication error is being shown, then shutdown soon.
> 
> **Elasticsearch version** (`bin/elasticsearch --version`):
> `7.2.0`
> `docker pull docker.elastic.co/elasticsearch/elasticsearch:7.2.0`
> 
> **Plugins installed**: []
> 
> **JVM version** (`java -version`):
> I use docker image, I dont know really.
> 
> **OS version** (`uname -a` if on a Unix-like system):
> Darwin ErasmeMacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
> 
> **Description of the problem including expected versus actual behavior**:
> 
> OpenJDK 64-Bit Server VM warning: **Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release**.
> 
> What puzzles me is that when I start two ESs, one can start successfully, but the other fails.
> BTW, my `mysql container` will close after I use `docker-compose up`
> 
> inspect my mysql container:

I Got this error on my AWS ES installation after I changed the network.host to the instance IP.
The reason is that I didn't change the discovery.seed_hosts to also point to the same IP. It was commented. After updating it and restarting ES everything worked.

**Comment by miskeenhijas** [comment]
please add following lines

LimitNOFILE=65536

LimitMEMLOCK=infinity

TimeoutStopSec=0

**Comment by Greentash** [comment]
> please add following lines
> 
> LimitNOFILE=65536
> 
> LimitMEMLOCK=infinity
> 
> TimeoutStopSec=0

Please, In which file, do i add these lines?

**Comment by miskeenhijas** [comment]
> > please add following lines
> > LimitNOFILE=65536
> > LimitMEMLOCK=infinity
> > TimeoutStopSec=0
> 
> Please, In which file, do i add these lines?

Add those lines in the ES service file.

**Comment by toshiro92** [comment]
>  
> please add following lines
> 
> LimitNOFILE=65536
> 
> LimitMEMLOCK=infinity
> 
> TimeoutStopSec=0

Worked for me on Docker, thank you! However, I did not have this error until I've activated the ES Security (xpack.security.enabled)

**Comment by ttttaheri** [comment]
I have the same issue when running sonarqube.
CentOS 7
OpenJDK 11

```OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: Could not find or load main class 8:-XX:+PrintGCDetails
Caused by: java.lang.ClassNotFoundException: 8:-XX:+PrintGCDetails```

**Comment by Brian154** [comment]
I have a problem starting my server, I would greatly appreciate your help please this is the console log. Investigating there are possibilities that it is due to the ram (it has 500mb) and I try to start the server with forge, it should be noted that this problem only appears when I select the version of forge, paper or some external version like kcauldron. Thank you very much please is urgent! :(

> 23.04 14:15:05 [Server] INFO /run.sh: line 31: 18643 Killed                  /monitor.sh "$PID" "$USER"
> 23.04 14:15:04 [Server] INFO Process 18642 detected
> 23.04 14:15:04 [Server] INFO Process 18642 dead!
> 23.04 14:15:04 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
> 23.04 14:15:04 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:52)
> 23.04 14:15:04 [Server] INFO at java.base/java.lang.Class.forName(Class.java:398)
> 23.04 14:15:04 [Server] INFO at java.base/java.lang.Class.forName0(Native Method)
> 23.04 14:15:04 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 23.04 14:15:04 [Server] INFO at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 23.04 14:15:04 [Server] INFO at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 23.04 14:15:04 [Server] INFO You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
> 23.04 14:15:04 [Server] INFO We appear to be missing one or more essential library files.
> 23.04 14:15:03 [Server] INFO OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> 23.04 14:16:06 [Server] INFO /usr/bin/java $VARS $@

**Comment by lauramejiaarroyave** [comment]
> I have the same issue when running sonarqube.
> CentOS 7
> OpenJDK 11
> 
> ```
> OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> Error: Could not find or load main class 8:-XX:+PrintGCDetails
> Caused by: java.lang.ClassNotFoundException: 8:-XX:+PrintGCDetails
> ```

Hey!
Im having the same issue.
Did you fix it?

**Comment by vishalvsh1** [comment]
**I Solved the issue in my Environment**

I got exactly the same issue when I was trying to run the elasticsearch as a swarm cluster. 


```
  warning: ignoring JAVA_TOOL_OPTIONS=-XX:MinRAMPercentage=55.0 -XX:MaxRAMPercentage=55.0 -Djava.awt.headless=true -Dsun.net.inetaddr.ttl=10
  Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
  output:
 
  error:
  OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
  OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
```

**Reason.**

I was giving only 2GB memory to the container in my docker-composse.yml file but elasticsearch was configured with Xms and Xmx as 4GB, hence I was getting the above error.
I increased the memory in my docker-compose.yml to 6GB and restarted the ES and worked fine.
