### ISSUE TITLE
thirdPartyAuditTask is disabled for :plugins:repository-s3

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#43918]
Earlier today I tried to run the `thirdPartyAudit` task for the `repository-s3` project but the task is always skipped:

```
./gradlew :plugins:repository-s3:thirdPartyAudit --info
...
> Task :plugins:repository-s3:thirdPartyAudit SKIPPED
Skipping task ':plugins:repository-s3:thirdPartyAudit' as task onlyIf is false.
```

@ywelsch found that the task is disabled by https://github.com/elastic/elasticsearch/blob/4586f2928cc3a0f729692b25c54c746ed730dd52/buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java#L59 when a docker-compose.yml file exists in the project. 

So I commented out the lines that disable the 3rd party audit task and the task is now executed but fails (which I kind of expected because of https://github.com/elastic/elasticsearch/pull/43671).

I'm filling this issue to ensure that `thirdPartyAudit` tasks are correctly executed on CI.

**Comment by mayya-sharipova** [comment]
3 failures today. The most recent on master:
Log:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob+third-party-tests-s3/2/console
