### ISSUE TITLE
[ML] Allow force delete for a data frame transform

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#43961]
Found in 7.3.0-SNAPSHOT 03-Jul-2019

In order to delete a failed transform, the user must first `_stop?force` it and then `DELETE`.

This is a theoretical two step process but in reality they will probably try `DELETE` and see a failure, then `_stop` and see a failure, then `_stop?force` and then the final `DELETE`.

We should allow the user to delete a failed transform without directing them through this convoluted path. By having a force-delete, we can force-stop in the background thus removing the persistent task and then delete the data frame transform.

This can be used by the UI in order to delete failed transforms. 

For the context of the UI experience, note that the error in the transform (the reason for the failure) should be visible in the messages tab in the UI and therefore we do not need to also show it to the user when they are trying to delete it. UI ref https://github.com/elastic/kibana/issues/40298

**Comment by droberts195** [comment]
To clarify, force delete should not just unconditionally delete failed transforms, but should unconditionally delete transforms whatever their current state.  As noted, the envisaged use case is the UI, where the current state is visible and an "are you sure" confirmation can be displayed if we want to protect users from deleting transforms that are progressing successfully.

(This is consistent with anomaly detectors where force delete will delete jobs whether they are open, closed or failed.)
