### ISSUE TITLE
Resolve fallout from version bumps in CI

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#43971]
## The Problem 

Depending on the order in which versions are bumped on different branches, we could be getting build failures when checking out and building BWC versions. 

Unreleased versions are mapped  to branches and asserted that the version produced there is the one we are expecting. 
If  this version was bumped on the current branch but not on the BWC branch or the other way around, these won't match up and the build will fail with a message similar to:
```
02:28:09 > Building 7.3.0 didn't generate expected file /private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/distribution/bwc/minor/build/bwc/checkout-7.x/distribution/archives/darwin-tar/build/distributions/elasticsearch-7.3.0-SNAPSHOT-darwin-x86_64.tar.gz
```

We don't want these failures on intake and all the notifications that go with it.

## Periodic jobs

For periodic jobs that use "lat good commit"  we fix the revision of BWC versions that we need to check out too, so we shouldn't run into this problem there even if a version bump happens between when the intake job( that sets last good commit ) and the periodic job runs.
This however seems broken as there were failures recently despite this mechanism: 
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/62/console
```
The build was using last good commit ( from the logs):
```
02:19:39 runbld>>> Using last successful commit e84a79a from the job elastic+elasticsearch+master+intake with the build id 20190703181815-589A85DE that was started at 2019-07-03T18:18:17.190Z and finished 1m 16s ago
02:19:39 runbld>>> BUILD_METADATA found in Elasticsearch.
02:19:39 runbld>>> BUILD_METADATA: bwc_refspec_distribution:bwc:bugfix=7c9aa15746b1bf48740df2390bb3066b59148832;bwc_refspec_distribution:bwc:minor=553f783e735b24a5eea3730d3ce97c7af74bfcc2
02:19:39 runbld>>> >>>>>>>>>>>> SCRIPT EXECUTION BEGIN >>>>>>>>>>>>
```

We need to look at and fix this.

## PR checks 

Pr checks on branches that didn't merge the version bump in will fail in a similar way.

## Leniency 

We could be lenient and allow a one off error when comparing versions ( e.x. accept 7.4 when we were expecting 7.3 ), but that should be considered only as a last resort.

**Comment by atorok** [comment]
## Atomic git push 

It look like git supports __atomic pushes__. 
One could do the version bump on all branches and then do something like
```
git push --atomic origin 6.8 7.3 7.x master
```
We should update the documentation on how to do version bumps and eventually automate it. 

## No longer store metadata

We are currently checking out the BWC branches individually after the build starts,
so we could be in the situation where we check out e.x master before the push, then a push happens before we get to the BWC checkout part and we would still get a mismatch.
The atomic push doesn't help with this problem. 

We should replace the current mechanism in runbld that stores build metadata about the bwc checkout with a simple flag that would be passed in CI  that would make it so no BWC revision is newer than the one we are running on.  (Except for PR jobs, see bellow)

e.x
Wit this timing: 
```
            |                                       time --->                                  |
-----------|----------------------------------------------------------------------------|
master |  m1                  m2                    m3 
7.x        |            x1  x2   x3 x4   
                                        ^
                                         | m2 and x3 are atomic
```
When we run intake on `m2` , we would use `x3`  because the tow revisions have the exact same timing. Suppose `x4` is right after `x3` so that by the time we get to the bwc checkout it's already there, we would ignore it and use `x3` because the timestamp of `x4` is newer than `m2`.  
Eventually we will trigger `m3` which will test with `m3`. 

We don't want this behavior locally as even if it's considered bad practice, one could go a long time without creating a commit and this would limit the bwc testing to an older than actual release. 
The same foes for PR builds. A long standing PR running it's checks should not use a really old BWC checkout as it could create a false sense of security.  
The checkout of these will remain as it is Today. 

###  How is this different from the metadata we store ? 

Most of the time it will be the same. 
With the current infrastructure what would probably happen going back to the example from before is that we would store `x4` with `m3` instead of `x3` so in those cases where we have a quick succession of commits it will be different but not incorrect. 

On the other hand we wouldn't need to persist state, which would help us with multijobs, as we could do the update of last good commit ( and only that, no metadata ) from a post build action or a publisher that calls runbld.  

It would also solve the problem from the description where we don't want to pick up a version bump if it happened after the build started but the checkout didn't happen without putting the burden on CI to do the checkouts ( which would be fine, except we still have to have them in Gradle anyhow for local development, so better to maintain a single solution ).

Side note: in theory we should be triggering master on changes from  `7.x` because a merge there can influence the tests in mate.

**Comment by atorok** [comment]
@rjernst @mark-vieira I'm happy to implement this but would like your thoughts first.

**Comment by mark-vieira** [comment]
I'm still not quite sure this "time-based" pinning of BWC commits will work. I think this will break down in CI for the same reason it does locally. What happens if `master` doesn't change, but I make a forward-incompaptible change in a BWC version branch? Using this method we would not be testing `master` against those new changes which would identify a regression. For a concrete example.

1. The `master` branch is built by intake and last good commit is recorded.
2. I make a change in `7.x` which breaks compatibility with `master`.
3. The `master` periodic builds run against last good commit from step (1), but do not pull changes from step (2) because they are "newer" than last good commit.

So I don't think this will work. I think the solution to mid-build build pushes is to pin the BWC checkout commit revisions at build start time. Either by doing a single `git fetch` at the beginning of the build as discussed in our weekly, or have `runbld` inject these somehow. Essentially, we need to also do _checkouts_ atomically when BWC testing in addition to pushing atomically.

**Comment by atorok** [comment]
@mark-vieira what you describe would work in the same way Today. 
Last good commit pins the BWC checkout refs, so unless there's an intake job to update them, any breakage coming from `7.x` would go undetected. 
For the periodic jobs that is by design as we don't want them to break because something in `7.x` changed after we recorded the last good commit.

**Comment by atorok** [comment]
I think where it would make a difference is if we were to trigger `master` intake jobs on changes to `7.x` or other branches that master is backwards compatible to. 
That would pose challenges to properly  display and handle the author,  essentially the author that would get the ping needs to be from `7.x` not the master commit that happens to be building.  Always enabling the forward comparability PR check we are introducing might be a better solution to this problem to prevent that bad merge in the first place.

**Comment by mark-vieira** [comment]
> I think where it would make a difference is if we were to trigger master intake jobs on changes to 7.x or other branches that master is backwards compatible to.

Right. This is the scenario I'm referring to. This issue is specific to intake builds where we just checkout the latest of everything.

**Comment by atorok** [comment]
We spent some time discussing this.
There are two problems we are looking to fix here. 
Besides the  fallout from version bumps we would we are also considering replacing the intake job with the [multi job](https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+fast/) to get much faster feedback. 
 These are related because they both have to do with how we manage the last good commit for BWC checkouts. 
With multi jobs the checkout metadata has to come from the `bwc` downstream job, but the last good commit comes from the upstream job when all downstream jobs complete. 

@rjernst I spent some time Today looking at how we could implement that currently and 
it doesn't seem straightforward at all ( or maybe I'm missing something ).
For instance we could produce the metadata as build output and then use the [Copy Artifact Plugin](https://wiki.jenkins.io/display/JENKINS/Copy+Artifact+Plugin) but then I couldn't find a way to configure that using jjb, so we might have to develop our own modules for jjb to be able to configure it.

The time based approach might not be great,  I'm really concerned that having to deal with this state in Jenkins keeps us on the wrong track will require much more maintenance and would take significantly longer to implement.

Are you willing to give it a try ? Any ideas on how to do this without requiring state in Jenkins ?

**Comment by atorok** [comment]
Another line of taught I';m considering is to keep this information in git itself. 
This would have the advantage that it would make it easier to have reproducible jobs outside of CI but would obviously create a lot of noise. 

I'm thinking about something like pushing a tag such as `bwc-ref-branch` ex `bwc-123-7.x` and have the build look for it  based on the current ref, so if we are building `123` it would find and use this tag instead. 

AFAIK builds are working off a repo hosted on the Jenkins master to speed things up, so these tags could potentially only live there, but that would cause failures when masters are rotated.  

I'm just throwing around ideas ... This would need more taught

**Comment by mark-vieira** [comment]
Regarding the Jenkins implementation, one thought is to use the [Clone Workspace Plugin](https://wiki.jenkins.io/display/JENKINS/Clone+Workspace+SCM+Plugin) to transfer the metadata files to some downstream build. There's still other details to sort out here that I'm not completely sure about though.

FWIW, I'm pretty sure the Git date-based checkout system will work. Git supports this as a first-class function with many commands accepting options like `--since` or `--before`. The commit date is not just some mutable metadata (unlike author date), and `git log` and `git rev-list` are primarily temporal lists.

We could implement such a system something like this:

```bash
HEAD_COMMIT_DATE=$(git log -1 --pretty=format:"%cd" HEAD)
git checkout $(git rev-list -1 --until="$HEAD_COMMIT_DATE" origin/7.x)
```

The benefit here is there's not explicit reliance on last good commit or any other "injected" information by CI. We simply infer the correct BWC branch commits form the commit date of current `HEAD`. As far as I can tell this is stable and reproducible. The only thing that would cause a different set of BWC commits to be used for a given `HEAD` commit would be if the Git history was rewritten which would breaks all sorts of other reproducibility mechanisms anyhow.

**Comment by atorok** [comment]
Clone workspaces will have to transfer files over the network and might not work with gobld as workspaces are not available once the build completes.

I'we also considered [Parameterized Trigger Plugin](https://wiki.jenkins.io/display/JENKINS/Parameterized+Trigger+Plugin)
which could pick up the metadata from the workspace and pass it along.
All the extra testing jobs would be downstream jobs to intake.
This would also show upstream/downstream relations in the Jenkins UI which would be a nice improvement. 

Problem is we don't want to trigger all the testing for all the intake jobs  and the only way to influence that is the  [Conditional BuildStep Plugin](https://wiki.jenkins.io/display/JENKINS/Conditional+BuildStep+Plugin) on a post build action but there's no way to implement the current behavior of having periodic additional testing. 
We could do something like trigger every X jobs which might make more sense than time based, as sometimes the periodic builds have lots of commits and others ( like weekends ) might have nothing new. 

Another problem is this doesn't help with multijobs as the problem of having a different job produce the metadata remains.

One possible solution with the multijobs is to use [EnvInject Plugin](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin) to inject the bwc checkout metadata from the parent job. It would mean we would run something to create that metadata then pass it to all jobs and eventually use it post build to set it for the job itself with runbld.  So instead of trying to pass it back from a downstream job, we set it on the upstream job and pass it down which seems to be better supported in Jenkins.

**Comment by atorok** [comment]
We changed to a solution that uses `git rev-list` and looks at the timing of each to decide what to pick.
This will cause no fallout when the version bump happens in an atomic push across branches.  All that is left here is to update the documentation on version bumps.
