### ISSUE TITLE
How to initialize PreBuiltXPackTransportClient

### ISSUE THREAD

**Issue by zhaoyunxing92** [elastic/elasticsearch#43985]
Hello, how should I initialization PreBuiltXPackTransportClient I opened the x - pack

**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4
**Plugins installed**: []
x-pack
**JVM version** (`java -version`):
jdk1.8
**OS version** (`uname -a` if on a Unix-like system):
win10
**Description of the problem including expected versus actual behavior**:
I see official support only to es6.0，[https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html](https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html)

```java
Settings settings = Settings.builder()
                // es 集群的名称
                .put("cluster.name", "elasticsearch")
                .put("client.transport.sniff", "true")
                //账号密码
                .put("xpack.security.user", "elastic:123456")
                .build();
        client = new PreBuiltXPackTransportClient(settings)
                //添加集群节点
                .addTransportAddresses(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300);
```
The exception that occurs after this setting

```log
java.lang.NoSuchMethodError: org.elasticsearch.common.settings.Settings$Builder.put([Ljava/lang/Object;)Lorg/elasticsearch/common/settings/Settings$Builder
```

**Comment by henningandersen** [comment]
I believe you simply have to recompile your code against the version you are using, the specific method that java complains about has been removed.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by zhaoyunxing92** [comment]
Ok,thanks
