### ISSUE TITLE
Problems encountered in the cosine similarity test sample

### ISSUE THREAD

**Issue by forheroes1994** [elastic/elasticsearch#44007]
With the ES 7.2.0 environment，I wanted to use cosineSimilarity function to calculate cosine similarity.But I got this error.
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "compile error",
        "script_stack": [
          "cosineSimilarity(params.q ...",
          "^---- HERE"
        ],
        "script": "cosineSimilarity(params.queryVector, doc['my_vector'])",
        "lang": "painless"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "dindex",
        "node": "ZyVgRJKqQ-GpSuXLyzG74A",
        "reason": {
          "type": "query_shard_exception",
          "reason": "script_score: the script could not be loaded",
          "index_uuid": "HxMQYoQWQwiQ0Lrlp3xVNg",
          "index": "dindex",
          "caused_by": {
            "type": "script_exception",
            "reason": "compile error",
            "script_stack": [
              "cosineSimilarity(params.q ...",
              "^---- HERE"
            ],
            "script": "cosineSimilarity(params.queryVector, doc['my_vector'])",
            "lang": "painless",
            "caused_by": {
              "type": "illegal_argument_exception",
              "reason": "Unknown call [cosineSimilarity] with [2] arguments."
            }
          }
        }
      }
    ],
    "caused_by": {
      "type": "script_exception",
      "reason": "compile error",
      "script_stack": [
        "cosineSimilarity(params.q ...",
        "^---- HERE"
      ],
      "script": "cosineSimilarity(params.queryVector, doc['my_vector'])",
      "lang": "painless",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Unknown call [cosineSimilarity] with [2] arguments."
      }
    }
  },
  "status": 400
}

My code as follows：
PUT dindex
{
  "mappings": {
    "properties": {
      "my_vector": {
        "type": "dense_vector"
      },
      "my_text": {
        "type": "keyword"
      }
    }
  }
}
PUT dindex/_doc/1
{
  "my_text": "text1",
  "my_vector": [5.5, 100.8, -12]
}
GET dindex/_search
{
  "query": {
    "script_score": {
      "query": {
        "match_all": {}
      },
      "script": {
        "source": "cosineSimilarity(params.queryVector, doc['my_vector'])",
        "params": {
          "queryVector": [ 4.5, 3.4, -1.2]
        }
      }
    }
  }
}

Thanks for answering.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

If you choose to post your question in discuss, please don't post
unformatted code as it's very hard to read.

Instead paste the text and format it with </> icon, and check the preview
window to make sure it's properly formatted before posting it. This makes it
more likely that your question will receive a useful answer.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
