### ISSUE TITLE
[Feature request] Alternative for ignore_above to support occasional long strings considered in aggregations

### ISSUE THREAD

**Issue by EmilBode** [elastic/elasticsearch#44002]
**Use-case**
When indexing a document with dynamical mappings, textfields are automatically mapped as both text, and a keyword field with parameter `ignore_above` set to 256. 
This works fine in most cases, but can lead to surprising results if there is an occasional long textfield, which is ignored in the keyword.

Suppose a user executed the following code:
```
PUT newindex/_doc/1
{
  "field": "val1"
}
PUT newindex/_doc/2
{
  "field": "val1"
}
PUT newindex/_doc/3
{
  "field": "val2"
}
PUT newindex/_doc/4
{
  "field": "val2"
}
PUT newindex/_doc/5
{
  "field": "val3"
}
PUT newindex/_doc/6
{
  "field": "For a change, this value is a lot longer. Actually, it's so long that it doesn't get mapped in the keyword field at all................................................................................................................................................................................................."
}

GET newindex/_search
{
  "size": 0,
  "aggs": {
    "valcount": {
      "cardinality": {
        "field": "field.keyword"
      }
    }
  }
}
```
The output gives me a valcount of 3.

As a naive user, I was expecting a cardinality of 4 (val1, val2, val3 and the long value). Instead, the long value gets ignored, so we get a cardinality of 3.

This is as documented, and in this case it's easily spotted. The user can fix it by manually providing a mapping with either fielddata enabled on the text, or setting the `ignore_above` on the keyword higher.

However, with lots of documents, fields that have lengths spread around the cutoff value, and an unaware user this may lead to more subtle miscalculations, or very confusing behaviour.

Of course just disabling the `ignore_above` value will lead to decreased performance and potentially other problems, so I don't think that's a solution. But I think there may be other alternatives, although I have to admit I don't have a perfect solution myself. 
Summarized, I think a text.keyword field should store *something* when dynamically mapping, although not the string in its entirety. 

**Proposed change**
My proposal would be to cut off a string after a certain length. The details of this should be stored in a mapping, so that users still have full control.
So a dynamically generated mapping of my previous example would look like this:
```
{
  "newindex" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "field" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "cutoff_after" : 256
            }
          }
        }
      }
    },
    "settings" : {...}
  }
}
```
Where `field.keyword` only stores the first 256 character (or bytes), and aggregations are based on these. 

Nothing would change for values of length<256, and nothing would change for user-provided mappings that don't use the `cutoff_after`-parameter.

Other ways of mapping a longer text to a keyword may also be feasible, although I think we have to be careful not to change any behaviour for fields <256 characters, and it must be clear to the user what exactly is stored (so I wouldn't store a hash or some similar solution).

**Comment by jtibshirani** [comment]
I agree that while it helps, `cutoff_after` is not a perfect solution: if there were two fields containing distinct pieces of text, but had a long shared prefix, then `cutoff_after` could produce identical values. A `cardinality` aggregation on this field would still give misleading results.

Would you be able to describe the data you're working with (ideally with some example documents), and how it's being searched + analyzed? That would help in understanding the problem + brainstorming a good approach.

**Comment by jtibshirani** [comment]
Thanks @EmilBode for the detailed example, it gives very helpful context.

> A workaround for me would be manually including a field that's some modification of the status text, but this adds to the ingest of course, and feels like overkill.

This is a good suggestion -- you could create a simple ingest pipeline containing a [script processor](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/script-processor.html) that takes in the text field (`status` in your example), trims it, and adds a new keyword field. The mappings could be adjusted to ensure only one keyword field is created.

The workaround assumes that you know the names of these fields in advance, and that they don't need to be mapped dynamically. Is that true for your use case? I wasn't sure because you mentioned dynamic mapping in the original issue description.

**Comment by EmilBode** [comment]
It looks like I'll use a variant of this solution, where I'm going to ingest first, then update records where needed. 

Regarding the field-names, I have multiple fields where this issue might play a role., I'm not sure exactly which ones. So for that reason I'll ingest first, and see which fields have a textfield present, but not a keyword, then I'll use a script to update (trim) the keywords.

Originally, I hadn't read the documentation carefully enough, so I thought _ignore_above_ was ignoring _characters_ above the 256-limit, so that's why I proposed this change.

I agree I can work around it, but I still think an automatic cutoff (as opposed to an automatic throwaway) of long values would make working with elastic easier. But I'll close the issue for now, thanks for helping me!

**Comment by jtibshirani** [comment]
> I agree I can work around it, but I still think an automatic cutoff (as opposed to an automatic throwaway) of long values would make working with elastic easier.

This makes sense, if you continue to run into issues (or if another user encounters a similar situation), we can re-open the issue and resume the discussion.
