### ISSUE TITLE
Elasticsearch 7.2 failed to start

### ISSUE THREAD

**Issue by skdasarin00b** [elastic/elasticsearch#44013]
Hello Everybody,

I am trying to install elasticsearch 7.2 from RPM. I have changed certain settings in jvm options file and as well as log4j2 properties file.

Please find the attachment which is as follows.
[log4j2.properties.txt](https://github.com/elastic/elasticsearch/files/3362926/log4j2.properties.txt)
[elasticsearch.yml.txt](https://github.com/elastic/elasticsearch/files/3362927/elasticsearch.yml.txt)

[jvm.options.txt](https://github.com/elastic/elasticsearch/files/3362920/jvm.options.txt)

Below attached are the log files

[log file.txt](https://github.com/elastic/elasticsearch/files/3362941/log.file.txt)
[service status file.txt](https://github.com/elastic/elasticsearch/files/3362942/service.status.file.txt)

**Comment by skdasarin00b** [comment]
The page is not working

**Comment by stefanobranco** [comment]
Maybe [this](https://stackoverflow.com/questions/40908998/error-unable-to-locate-plugin-type-for-rollingfile-and-for-timebasedtriggeringp) helps?
It's a few years old, but it seems very similar to your issue, and you do have spaces at the end of your config lines.

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.
