### ISSUE TITLE
At Github Releases page link to 7.2.0 Release notes is broken

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/elasticsearch#44037]
At [Github Releases page](https://github.com/elastic/elasticsearch/releases) link to 7.2.0 Release notes - https://www.elastic.co/guide/en/elasticsearch/reference/master/release-notes-7.2.0.html is broken. It should be https://www.elastic.co/guide/en/elasticsearch/reference/7.2/es-release-notes.html

**Comment by jasontedor** [comment]
Thanks for the report, sorry for the issue, and sorry for the slow response. We have manually fixed these release notes, and are adjusting our release process to avoid this issue in future releases.
