### ISSUE TITLE
Field Collapsing to accept script

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#44035]
Today field collapsing only accepts a single field to collapse on.
We need to investigate if it is possible/worth to allow to accept a script instead of a single field to collapse on. This will help in use cases where is is necessary to  collapse results on values of several fields.

An example:
```js
{
  "query": {
    "match_all": {}
  },
  "collapse": {
    "script": {
      "source": "doc['last_name'].value + doc['first_name'].value"
    }
  }
}
```

**Comment by mayya-sharipova** [comment]
We have discussed this within the team, while people are in favour of implementing it (as we have similar functionality with composite aggs), we still need to investigate the technical feasibility of this feature.

**Comment by jimczi** [comment]
For field collapsing we need a way to quickly find all documents belonging to a group, this way we can retrieve `inner_hits` efficiently. With `script` we'd need to do a full scan of the documents to retrieve the top hits of a single group so I doubt that it is a price that users are willing to take.
For exploratory cases the  `terms` aggregation accepts `script` so it should be doable there. Users can then create a composite field and reindex if they want to speed up the search with `collapsing`.

**Comment by mayya-sharipova** [comment]
Closing this issue, as Jim noted an exploratory use case can be achieved with `term` agg, and for speedups a composite field can be created.
