### ISSUE TITLE
Reindex Task ignores slices configuration in client API

### ISSUE THREAD

**Issue by RomanShtern** [elastic/elasticsearch#44045]
**Elasticsearch version**: REST High Level Client 6.6.0+

**Plugins installed**: []

**JVM version** openjdk version "11.0.2" (Zulu)

**OS version** Windows 10

**Description of the problem including expected versus actual behavior**:

The High-Level REST Java client supports submitting a Reindex request to the Tasks API using "submitReindexTask". However, when including a slices configuration (via ReindexRequest.setSlices()), that parameter is ultimately ignored and not included in the actual Http request. 

According to the documentation, there should be no problem supplying the slices amount, as the only thing that causes the request to be submitted as a task is the parameter value "wait_for_completion=false".

I also tested it by sending a manually crafted API request and it indeed works as it should. So currently the only way to do it is using the low level client as a workaround.

**The problem in the code**:
submitReindexTask uses RequestConverters::submitReindex, in which only the following params are added:

```
Params params = new Params(request)
            .withWaitForCompletion(waitForCompletion)
            .withRefresh(reindexRequest.isRefresh())
            .withTimeout(reindexRequest.getTimeout())
            .withWaitForActiveShards(reindexRequest.getWaitForActiveShards(), ActiveShardCount.DEFAULT)
            .withRequestsPerSecond(reindexRequest.getRequestsPerSecond());
if (reindexRequest.getScrollTime() != null) {
            params.putParam("scroll", reindexRequest.getScrollTime());
        }
```

So here the slices parameter is lost and not included in the request.

**Comment by 9deniz** [comment]
@original-brownbear @hub-cap Hi guys, I added small fix for this issue and opened PR, could someone please take a look?
