### ISSUE TITLE
Documentation for the "stored scripts" feature

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#4405]
I can't find a way to make a simple MVEL script to work (for a bulk update request).
It's OK if it's embedded in the request, but if it's stored, it doesn't.

I've created a [gist](https://gist.github.com/jlecour/9f4463361b3205130951) with more information about my problem.

This issue is more about the documentation side of things. The current official documentation says very little about update scripts, and even less about stored scripts.
There is no example of a request that will use a basic stored MVEL script.

The test suite doesn't contain any test for stored scripts either.

Is there something out there that would explain a little more how to use stored scripts?

Thanks

**Comment by clintongormley** [comment]
These docs have subsequently been improved. Closing
