### ISSUE TITLE
Missing required library in `:plugins:repository-hdfs` Eclipse project

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#44065]
I've been getting this error in Eclipse for a while now, just saw that it might be related to #43651.
I tried cleaning the workspace etc., cannot find a file or directory of the same name in test/fixtures/krb5kdc-fixture anywhere though. Maybe something I'm missing running to create those resources? 

```
Project ':plugins:repository-hdfs' is missing required library: '/Users/christoph/workspace/elasticsearch/test/fixtures/krb5kdc-fixture/build-eclipse/shared/hdfs/keytabs'
```

I'm currently working around it by closing that plugins subproject.

**Comment by mark-vieira** [comment]
@cbuescher I think running `./gradlew eclipse copyKeytabToGeneratedResources` should create that file for you and get Eclipse to stop complaining in the meantime. I think https://github.com/elastic/elasticsearch/pull/44075 will fix this permanently.

**Comment by cbuescher** [comment]
Thanks, I'm not sure how this is related but trying to run the above command (with Docker running), I get:
```
> Task :test:fixtures:krb5kdc-fixture:postProcessFixture FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/christoph/workspace/elasticsearch/test/fixtures/krb5kdc-fixture/build.gradle' line: 42

* What went wrong:
Execution failed for task ':test:fixtures:krb5kdc-fixture:postProcessFixture'.
> assert confTemplate.exists()
         |            |
         |            false
         /Users/christoph/workspace/elasticsearch/test/fixtures/krb5kdc-fixture/build-eclipse/shared/peppa/krb5.conf.template
```
Not sure what to make of this since I'm pretty unfamiliar with that project.

**Comment by mark-vieira** [comment]
This works for me locally. Perhaps you don't have `docker-compose` installed?

**Comment by cbuescher** [comment]
> Perhaps you don't have `docker-compose` installed

No, thats there. I can try this again later at some point though.

**Comment by cbuescher** [comment]
Works now, thanks. 
Aka "Have you tried turning it off an on again..."
Will close this for now, hope #44075 will solve the issue for the future so running the `copyKeytabToGeneratedResources` is not needed anymore or run automatically.
