### ISSUE TITLE
Allow adjustment of index resource constraints in ILM phase transitions

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#44070]
The shards allocator mostly does a good job of spreading the shards of each index out across the available nodes, but there are some corner cases where it might temporarily concentrate too many hot shards on a single node, leading to poor performance and possible resource exhaustion (https://github.com/elastic/elasticsearch/issues/17213). It is occasionally useful to add the `index.routing.allocation.total_shards_per_node` constraint when indices are under heavy load, to prevent too many hot shards from being allocated to the same node. We are contemplating generalising this to a more nuanced set of per-index resource constraints too (https://github.com/elastic/elasticsearch/issues/17213#issuecomment-382310838).

If an index is managed by ILM then it is likely its resource requirements will change along with its lifecycle. In particular when the index leaves the hot phase it will no longer see such heavy indexing, and so any `total_shards_per_node` constraint is likely no longer necessary. It's important to keep the use of this sort of setting to a minimum to avoid over-constraining the allocator since this can lead to unassigned shards (https://github.com/elastic/elasticsearch/issues/12273). I therefore think it'd be a good idea to allow this kind of setting to be changed in the appropriate ILM phase transitions.

**Comment by DaveCTurner** [comment]
I raised this question with the distrib team today and although we're not super-keen on recommending the widespread use of the `total_shards_per_node` constraint, we think it's a good idea to allow it to be relaxed on ILM phase transitions, particularly the hot-to-warm one.

**Comment by vigyasharma** [comment]
Are `per-index` resource constraints being planned as _prescriptive_ - as in allocator makes a best effort to comply by constraints but allocates the shards anyway if no node is able to fulfill its requirements, or will it be a _hard limit_, and leave shards unallocated if not fulfilled?

Resource requirements are often quite dynamic. Even in the **hot** stage, and index may have off peak hours when the reserved resources could've been shared by other indices. 

Requirement prediction itself is hard with users almost always under/over provisioning in the first pass. It needs iterative fine tuning to get the limits right. I would vote for a prescriptive best case effort to allow for such flexibility.

Separately, +1 on revising constraints through ILM transitions.

**Comment by dakrone** [comment]
We discussed this and agreed on putting an option for setting `index.routing.allocation.total_shards_per_node` into the `allocate` action in ILM.

**Comment by avneesh91** [comment]
@DaveCTurner would it be ok if I started working on this?

**Comment by dakrone** [comment]
@avneesh91 sure if you'd like to contribute a PR for this that would be great.

**Comment by shoaib4330** [comment]
@avneesh91 I'd like to pick this issue, if you're not actively working on it?

**Comment by epicvinny** [comment]
It is impracticable to use ILM at scale :(

**Comment by Aloshi** [comment]
Another +1 to this issue. We've been having problems when we scale up our larger clusters by 2-3 nodes where ES decides to allocate all of the shards for the next index on the new nodes, which causes abysmal performance and slows down ingestion. We've been guarding against it by setting `index.routing.allocation.total_shards_per_node` to 1 or 2 until the new nodes are mostly full, and we'd like to just leave this set all the time, but when these indices are moved to warm nodes there aren't enough warm nodes to satisfy the constraint (since having fewer warm nodes than hot nodes is kind of the point).

**Comment by ppf2** [comment]
+1 [Shard imbalance](https://github.com/elastic/elasticsearch/issues/17213) necessitating the use of `total_shards_per_node` does not only apply to the heavy indexing use case, we have seen this affect other cluster operations such as force merge when a majority of shards of an index being force merged ended up concentrating on a single warm node.

**Comment by JohnLyman** [comment]
> We discussed this and agreed on putting an option for setting `index.routing.allocation.total_shards_per_node` into the `allocate` action in ILM.

Resetting `total_shards_per_node` is also required when using the `shrink` action which necessitates that all primary shards be moved to the same node.

@dakrone - if this option is put in the `allocate` action, would that allow for the value to be reset prior to `shrink`?  I'm not sure of the order of operations here (I don't think it's documented).  In other words, does `allocate` come before `shrink` in the warm phase?

**Comment by dakrone** [comment]
> if this option is put in the allocate action, would that allow for the value to be reset prior to shrink? I'm not sure of the order of operations here (I don't think it's documented). In other words, does allocate come before shrink in the warm phase?

`allocate` does come before `shrink` in the warm phase, though I think regardless we should endeavor to make `shrink` run regardless of the setting, unsetting the setting during the allocation, then resetting it if necessary.

**Comment by JohnLyman** [comment]
That seems reasonable @dakrone (and thanks for the quick reply).  Should I open a new issue for your suggestion?

**Comment by dakrone** [comment]
@JohnLyman I think it can be subsumed into this issue for now, thanks for bringing it up!

**Comment by JohnLyman** [comment]
I was thinking for shrink in general, whether it's initiated by ILM or not.

**Comment by dakrone** [comment]
I think that is one of the main goals of #63519
