### ISSUE TITLE
License enquiry for using elasticsearch in a lab enviornment to teach students.

### ISSUE THREAD

**Issue by iam-alex** [elastic/elasticsearch#44087]
Hi,

This issue is in regarding the Elastic License. 

First of all, I'd like to say Great Work! I'm really impressed with elastic search. 

I'm a teacher and I take online classes, I also have a paid lab environment where students can follow my video and perform the activity accordingly. For e.g I've SQL, NoSQL databases preinstalled, students can interact with them and learn SQL/NoSQL in the lab environment.

I was planning on adding on Elastic search, so that students can interact with it and learn how to perform operations on elastic search. 

I went through the Elastic License and I wanted to verify whether I can use the commercial code and deploy elastic search for teaching in a lab environment to students online. 

I'm hoping using elastic search in the lab environment will come under section 6.8 "Non-production Environment".

Thanks!

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
