### ISSUE TITLE
[feature request]copy_index api(reindex with file copy not doc insert)

### ISSUE THREAD

**Issue by riverbuilding** [elastic/elasticsearch#44128]
use case: copy old index as a backup to support rollback and then update the original index to move forward in the same cluster.

ES provide re-index API which can be used to copy index with many flexibility like schema change, doc filter etc.
although with many limitations, from performance side, the file copy method is much fast than reindex, especially when index size is big.

API:

POST _copyindex
{
  "source": {
    "index": "twitter"

  },
  "dest": {
    "index": "new_twitter"
    "replica": Number//must eq or less than orginal index replica, otherwise, fail request
  }
}

it's really like snapshot-restore process only repository is ES itself

**Comment by original-brownbear** [comment]
@riverbuilding just to understand this feature request better:

Your motivation is to effectively have ES be the repository instead of using another repository implementation to save the complexity of setting up a repository?

**Comment by ywelsch** [comment]
As far as I understand, this could be the [index split functionality](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-split-index.html) with the additional option of keeping the number of primary shards the same in the target index.

**Comment by riverbuilding** [comment]
@ywelsch split is really what I need in this situation. thanks a lot.

**Comment by riverbuilding** [comment]
@ywelsch I'd like to ask: when split index, can the "can't select recover from shards if both indices have the same number of shards" be omit? I mean, can the target index be set the same shard  number with the original index?

**Comment by ywelsch** [comment]
Right now, it can't. If we were to allow this, I would rather prefer to expose it via a new endpoint `_clone` than enable this on `_split`.

**Comment by riverbuilding** [comment]
@ywelsch _clone is really a good name. thanks

**Comment by jakelandis** [comment]
We discussed this today and think this a good enhancement and also like the `_clone` name implemented on top of the split functionality.
