### ISSUE TITLE
DOCFIX: clearer allowed script type settings

### ISSUE THREAD

**Issue by kcm** [elastic/elasticsearch#44142]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0-7.x (current)

**Description of the problem including expected versus actual behavior**:

Docfix for:

https://github.com/elastic/elasticsearch/edit/master/docs/reference/scripting/security.asciidoc

The settings here are not clear for `stored` and default settings.

We could do something like:

```
----
script.allowed_types: inline <1>
----
<1> This will allow only inline scripts to be executed but not stored scripts
(or any other types).

----
script.allowed_types: stored <1>
----
<1> This will allow only stored scripts to be executed but not inline scripts
(or any other types).

----
script.allowed_types: stored, inline <1>
----
<1> This will allow inline and stored scripts to be executed (the default, if this setting is not specified).
```

Additional background: we removed a third type of `file` as of https://github.com/elastic/elasticsearch/pull/24627 (6.0), so any wording that indicates additional types could be removed for those versions if desired.

**Comment by talevy** [comment]
opened #44143 to fix this
