### ISSUE TITLE
Explicitly annotate public API parameters as Nonnull by default to allow Kotlin plugins to check usage

### ISSUE THREAD

**Issue by vinoov** [elastic/elasticsearch#44148]
_Opening this issue to discuss making default non-null arguments explicit as suggested by @mark-vieira in https://github.com/elastic/elasticsearch/pull/43912#issuecomment-509281993_

Currently ES APIs explicitly annotate Nullable method parameters and all other parameters are implicitly understood to be non-null (at least as far as I can tell).  If this implicit default is made explicit for the plugin APIs then plugins written in Kotlin could benefit from better null checking as described here: https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support

One way to implement this is by defining a new annotation in the `org.elasticsearch.common` package like so: 

```
@Nonnull
@TypeQualifierDefault({ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface NonnullParameters {
}
```

and then applying it to classes/packages as needed.

**Comment by mark-vieira** [comment]
We'd need to also scrub these APIs to ensure that parameters do indeed require non-null values. There may be places where `@Nullable` is appropriate but simply missing.

**Comment by jaymode** [comment]
Thank you for opening this issue for discussion. This was discussed today and the consensus was that this type of change would add a lot of noise to our codebase and the team is still in favor of implicit non-null parameters and explicitly using `@Nullable` to define parameters where null is accepted.
