### ISSUE TITLE
SQL: Supports two columns comparing on `WHERE` clause

### ISSUE THREAD

**Issue by sw-jung** [elastic/elasticsearch#44151]
**Describe the feature**: Supports two columns comparing on `WHERE` clause like this:
```sql
SELECT a, b
FROM my_table
WHERE a = b
```

For now, when I run this query, it returns error:
```sql
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Line 1:109: Comparisons against variables are not (currently) supported; offender [b] in [==]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Line 1:109: Comparisons against variables are not (currently) supported; offender [b] in [==]"
  },
  "status": 500
}
```

Of course, it's hard to work with the `text` type field but how about numeric or `keyword` type field?

Currently, numeric field can approach like below indirectly:
```sql
SELECT num_a, num_b
FROM my_table
WHERE num_a - num_b = 0
```

And it translates as:
```javascript
{
  ...
  "query" : {
    "script" : {
      "script" : {
        "source" : "InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.eq(InternalSqlScriptUtils.sub(InternalSqlScriptUtils.docValue(doc,params.v0),InternalSqlScriptUtils.docValue(doc,params.v1)),params.v2))",
        "lang" : "painless",
        "params" : {
          "v0" : "num_a",
          "v1" : "num_b",
          "v2" : 0
        }
      },
      "boost" : 1.0
    }
  },
  ...
}
```

However, there is no way to compare two `keyword` type field. I think it can be resolve with simple script query:
```javascript
{
  "query": {
    "bool" : {
      "filter" : {
        "script" : {
          "script" : {
            "source": "doc['a'].value == doc['b'].value",
            "lang": "painless"
          }
        }
      }
    }
  }
}
```

Of course, there may be performance concerns due to the script query, but it will be useful in many cases even considering this.

**Comment by astefan** [comment]
@sw-jung you are right, this can be done in ES query dsl and we don't support this at the moment. This feature request has already a github issue created: https://github.com/elastic/elasticsearch/issues/34400.

If you don't mind, I'd like to close this one as a duplicate and keep the original one opened.

**Comment by sw-jung** [comment]
Ahh... I missed that issue. Please feel free to mark this as a duplicate and close!

Thank you @astefan!
