### ISSUE TITLE
BulkAll takes a long time to complete

### ISSUE THREAD

**Issue by CSharpBender** [elastic/elasticsearch#44167]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.5

**Plugins installed**: C# Nest package 5.0.0

**JVM version** (`java -version`): 9

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
Sometimes BulkAll takes a long time to complete.
I'm not getting any errors it's just waiting for something, sometimes for 85 seconds or longer.
During my tests the list of items contains a single item, so it's not about having too much data.
This reproduces when it's called 2-3 times per second.

**Steps to reproduce**:
```
Client.BulkAll(itemArray, i => i.Index<T>()
                                                    .BackOffTime(TimeSpan.FromSeconds(5))
                                                    .BackOffRetries(2)
                                                    .MaxDegreeOfParallelism(Environment.ProcessorCount) //12
                                                    .Size(100)
                                                    .RefreshOnCompleted())
                            .Wait(TimeSpan.FromSeconds(60), r => { });
```

**Comment by jakelandis** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
