### ISSUE TITLE
[CI] Gradle sporadically fails with OOME on Windows

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#44163]
We see build failures in CI on Windows where the Gradle process itself terminates with an `OutOfMemoryError`. Here is an example from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/93/consoleFull (build-id: `20190710105514-036E743F`):

```
11:16:49 > Task :test:framework:test
11:16:49 Error occurred during initialization of VM
11:16:49 Could not reserve enough space for object heap
```

This has occurred 30 times in the last 30 days and the following build ids were affected in that time range (June 10, 2019 until July 10, 2019):

<details>
    <summary>Click to expand build ids</summary>
    <p><pre>
20190624004647-81B94E52
20190630202159-46CE8A05
20190703070643-83570AD7
20190703073255-4F03A402
20190703075849-283103C2
20190703082033-E5308B7F
20190703084036-2C32BD8C
20190703105517-AAC68017
20190703113029-07D760DC
20190703123422-BE73668E
20190703152555-F32C91A3
20190703162003-E070F501
20190703181200-75EE399D
20190703183356-C5AFB5BF
20190703184301-6241221E
20190703214124-6BDB72E4
20190703225502-44DB0C4E
20190703231617-F2B93497
20190704003052-EBFC2578
20190704043650-92EAA332
20190704105450-1986BD71
20190705042017-19A664A9
20190705105505-1899BB61
20190706225507-4714C187
20190707105521-069D8931
20190707162004-13997F1E
20190708225453-5C58D41D
20190709105447-AA3F9AC2
20190709162010-48553C3B
20190710105514-036E743F
</pre></p>
</details>

All of them have failed on Windows (Windows Server 2012 R2 and Windows Server 2016), one of them on the `6.8` and the rest on `7.x` and `7.3` but none of them on the master branch. As of today, `6.8` is on Gradle 5.2.1, the rest (including master) on Gradle 5.5.

**Comment by atorok** [comment]
We have ephemeral workers which don't have this issue. I took the non ephemeral workers offline in CI.
