### ISSUE TITLE
Allow CharArrays to be created from a BytesReference

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#44173]
Copying from https://github.com/elastic/elasticsearch/pull/43197#discussion_r301756649 : 

> .. it seems like most of the places we use CharArrays like this we have a BytesReference, and we end up copying to a byte array in order to convert to chars. I wonder if we could flip the CharArrays input around so it takes a BytesReference, so that we don't need to have the try/finally like this. In the few cases we actually have a real bytes array, we can wrap the array in a bytesreference.

**Comment by williamrandolph** [comment]
This is a small refactor and I think we'll be able to see from a PR whether it's still a good idea or not.

**Comment by williamrandolph** [comment]
It turns out that it's not quite trivial because `CharArrays` is in the libs:core project while `BytesReference` is in elasticsearch:server. There are 12 usages of the `CharArrays#utf8BytesToChars` method.

@rjernst Do you think this is still worth doing?

**Comment by rjernst** [comment]
I think it would be difficult to move BytesReference to libs:core, partly because it would create a circular dependency with libs:x-content because BytesReference implements TXContentFragment. So I think we can safely close this as infeasible.
