### ISSUE TITLE
Logstash Output to Alias

### ISSUE THREAD

**Issue by amm-uit-2017** [elastic/elasticsearch#44198]
I create an alias for elasticsearch index and add a life cycle policy on that. The life cycle policy rollover to the new index after 1 month. But the logstash still sending the logs to the old index. I want to send the logs from logstash to a new index that is rollover by the life cycle policy. 

My configuration for logstash output is just pointing to " index => 'xxxx' ".

```
elasticsearch {
        hosts => "https://172.31.46.56:9200"
        index => "index-00001"
        user => 'logstash'
        password => 'xxxxxxxxxxxx'
        ssl => true
        ssl_certificate_verification => false
        cacert => '/etc/logstash/elastic-ca.pem'
```

How to configure output for logstash to send new logs to rollover index?

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
