### ISSUE TITLE
CI: SimpleQueryStringIT.testDocWithAllTypes fails periodically 

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#44192]
Introduction of https://issues.apache.org/jira/browse/LUCENE-8811 that was enabled by #44171 makes this test to fail with `TooManyClauses[maxClauseCount is set to 52];` error since the last query generates 57 clauses.

```
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.search.query.SimpleQueryStringIT.testDocWithAllTypes" -Dtests.seed=4BE99E7769CF3EAC -Dtests.security.manager=true -Dtests.locale=dav-KE -Dtests.timezone=US/Pacific -Dcompiler.java=12 -Druntime.java=11
```

**Comment by cbuescher** [comment]
For some reason we randomize the CLUSTER_MAX_CLAUSE_COUNT on test setup (@BeforeClass) between 50 and 100. For the query in question we seem to need at least 57 clauses to pass. This probably hasn't been detected before. I don't see a reason we need to be that conservative in the allowed number of clauses and will raise it.
