### ISSUE TITLE
[DOCS] Replace `_meta` with `metadata` for snapshot APIs

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#44195]
According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-snapshots.html#_snapshot), when creating a snapshot, arbitrary `_meta` key value pairs can be sent in the payload to store extra information. From my testing of the snapshot creation and info APIs, this no longer seems to be true: `_meta` seems to have been replaced with `metadata`.

**Comment by original-brownbear** [comment]
Yea, this is def. documented wrong.
