### ISSUE TITLE
UPDATE Feature Request: Return old source

### ISSUE THREAD

**Issue by jm4games** [elastic/elasticsearch#4420]
So I was wondering if it would be possible to add a feature to UPDATE for returning the old source of a document that exist before the update is applied. This would be useful in scenarios where you want to update a document and possibly take additional actions if the update caused certain values in the document to change. The current alternative is to do a GET operation before the update, but then you can run into possible timing issues. Not mention you take the additional network call to perform the GET.

**Comment by bleskes** [comment]
It's an old issue, but it feels to me that a nice solution for this is to allow the script in a scripted update to return values that will be added to the response. This would allow you to make smarter about the change. The down side is that it introduces overhead if you really just want the original doc. @Plasma maybe you can comment?

**Comment by jpountz** [comment]
I don't think we should make the update API more complicated. It is easy to get the previous source by issuing a GET first, then running the update on the same version of the document and retrying in case of conflict.
