### ISSUE TITLE
Remove support for old translog checkpoint formats

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#44210]
Today we support three formats of checkpoint. We stopped using the oldest format in 6.0, so support for this can be dropped in both `7.x` and `master`. We stopped using the second-oldest format in 6.4, so support for this can be dropped in `master`. I also don't see any tests for Elasticsearch's behaviour with checkpoint files of these old formats (like e.g. `TranslogHeaderTests#testLegacyTranslogVersions`), but I think we should have some.

**Comment by Hohol** [comment]
I'd like to take this.

**Comment by DaveCTurner** [comment]
Sure, go for it @Hohol
