### ISSUE TITLE
[CI] NodeTests suite timeouts on new windows workers

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#44256]
On Windows 2016 and windows 2012 we getting suite timeouts in what seem to be the very first suite run in that build.

It appears to that the test takes a long time between finishing the test method, and being marked as "done" - possibly due to clean up tasks in `@After`?

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob-windows-compatibility/os=windows-2016/1/
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob-windows-compatibility/os=windows-2012-r2/1/

Looking at the Windows-2016 failure:
- We start :server:test at 4:43 (`04:43:11 > Task :server:test`)
- We fail a little over 20 minutes (1,200,000 ms) later.
```
05:05:42 org.elasticsearch.node.NodeTests > testCloseOnLeakedStoreReference FAILED
05:05:42     java.lang.Exception: Test abandoned because suite timeout was reached
...
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
``` 
- The node being tested was stopped early in the 20 mminutes (7:45 in the node's TZ)
```
1> [2019-07-12T07:45:46,034][INFO ][o.e.n.Node               ] [testCloseOnLeakedStoreReference] closed 
```
- but the "after test" log doesn't come until we're killing off the suite (8:05)
```
1> [2019-07-12T08:05:47,854][INFO ][o.e.n.NodeTests          ] [testCloseOnLeakedStoreReference] after test
```

It seems that something on this new Ephemeral Windows CI worker is causing a problem moving this test method from "testing complete" to "test done"

**Comment by atorok** [comment]
Saw this:
```
"TEST-NodeTests.testCloseOnOutstandingTask-seed#[5A77C82F64470C03]" ID=794 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6650632c
	at sun.misc.Unsafe.park(Native Method)
	- timed waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6650632c
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1475)
	at org.elasticsearch.threadpool.ThreadPool.awaitTermination(ThreadPool.java:421)
	at org.elasticsearch.threadpool.ThreadPool.awaitTermination(ThreadPool.java:775)
	at org.elasticsearch.threadpool.ThreadPool.terminate(ThreadPool.java:759)
	at org.elasticsearch.node.Node.awaitClose(Node.java:901)
	- locked org.elasticsearch.node.MockNode@1c36784d
	at org.elasticsearch.node.NodeTests.testCloseOnOutstandingTask(NodeTests.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccess
```
here: https://scans.gradle.com/s/rhypi43cmywgq/tests/nfxodyych4uas-o4ihtq27xgiqs
The code reads :
```
assertTrue(node.awaitClose(1, TimeUnit.DAYS));
```

**Comment by ebadyano** [comment]
Might be another one:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob-windows-compatibility/os=windows-2012-r2/22/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob-windows-compatibility/os=windows-2019/19/consoleFull

**Comment by jdconrad** [comment]
Another:
https://scans.gradle.com/s/fcvxdhfqiy224/console-log
