### ISSUE TITLE
Esdocs query in Canvas fails on multiple indices with different mappings

### ISSUE THREAD

**Issue by blfrantz** [elastic/elasticsearch#44296]
**Elasticsearch version** 
docker.elastic.co/elasticsearch/elasticsearch:7.2.0

**Description of the problem including expected versus actual behavior**:
My issue is almost exactly like [this bug](https://github.com/elastic/elasticsearch/issues/43876), except my case doesn't seem to have anything to do with SQL. 

In Canvas (running in a 7.2.0 kibana docker container), when I try to populate a metric with data from an Elasticsearch Raw Documents source, I'm getting the following error:
`[esdocs] > Unexpected error from Elasticsearch: [illegal_argument_exception] Illegal Capacity: -2`

Like in the issue linked, it only reproduces if I use an index pattern that matches multiple indices, and those indices have some different fields.

**Steps to reproduce**:
I've been able to reproduce with data generated by the following python3 script:
```
from elasticsearch import Elasticsearch

ES = Elasticsearch()
BASE_INDEX = 'test'

for i in range(0, 5):
    obj = {'num': i}
    obj['unique' + str(i)] = i
    index = BASE_INDEX + str(i)
    ES.index(index=index, body=obj)
```

Then, I create an index pattern in Kibana for test*, and in Canvas:
1. Add a Metric element
2. Go to Data > Change data source > Elasticsearch raw documents
3. Select test* index and save
4. Note the error in the element.  Since nothing loaded, I can't select the column I want to display.
If I follow these same steps but with index pattern test0, it works.

**Comment by astefan** [comment]
@blfrantz I would have created this issue in the kibana/canvas repo, as a more likely investigation starting point...

**Comment by blfrantz** [comment]
@astefan Ok, I thought about doing that but due to the similarity to that ES SQL bug, I thought it'd make sense to start here.  Should I create an issue over there and close this one, or is there an easier way to loop them in?

**Comment by romseygeek** [comment]
@blfrantz can you create a Kibana issue and link it here?

**Comment by polyfractal** [comment]
I suspect Canvas is using SQL in the background to gather some data even though you're using esdocs.  Can you try upgrading to 7.2.2 and see if that fixes the issue?

Alternatively, do you have the logs from the Elasticsearch server?  That would let us narrow down where the server is throwing the error, which might inform debugging.

**Comment by tlrx** [comment]
Closing in favor of the Kibana issue. Please feel free to reopen if it happens to be a ES SQL issue.
