### ISSUE TITLE
Creating a time series in ElasticSearch based on date field

### ISSUE THREAD

**Issue by dsonjohn** [elastic/elasticsearch#44314]
i want to create time series analysis for my index based on date field (not based on system time). can anyone help me? my index mapping is like this:
{
   "test" : {
      "mappings" : {
             "properties" : {
                   "@timestamp" : {"type" : "date"},
                   "age" : {"type" : "integer"}     
           }
         }
       }
     }

**Comment by dadoonet** [comment]
Please ask this question on https://ela.st/forum where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on https://ela.st/forum.

Thanks!

**Comment by dsonjohn** [comment]
ok! thanks dadoonet
