### ISSUE TITLE
authc.realms in docker-compose env vars

### ISSUE THREAD

**Issue by azhurbilo** [elastic/elasticsearch#44311]
https://github.com/elastic/elasticsearch/blob/e5a3ae97e2d0bcfb8a66408bbde3085e308f3ec1/distribution/docker/docker-compose.yml#L25

according  to official documentation https://www.elastic.co/guide/en/elasticsearch/reference/6.7/security-settings.html#realm-settings

```
xpack.security.authc.realms.file1.order=0
xpack.security.authc.realms.file1.type=file
```

@atorok is it correct?

**Comment by tvernum** [comment]
@azhurbilo 

You are looking at a file on the `master` branch (What will become elasticsearch 8.0) and comparing it do documentation for the 6.7 release of Elasticsearch.

The configuration of realms was changed in 7.0 so the `docker-compose.yml` file is correct for master and the docs are correct for 6.7

If you need additional help with configuring realms in Docker compose, we like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
