### ISSUE TITLE
GC can't decrease heap memory usage and Elastic fails

### ISSUE THREAD

**Issue by adtrace** [elastic/elasticsearch#44312]
I use elastic 6.2.4 with a 2 node cluster.
when elastic index rate increases at specific time at day heap memory exceed th 70 % and GC starts but heap memory usage won't decrease untill goes up to 97-98% and elastic won't respond and fails after minutes.
1- both servers has 64 GB memory and bot elastic nodes have 32 GB memory allocation.
2- the elastic failure happens every day at a specific time (it's weird due becasue it's not maximum load)
3- load in failure time is 70-80 record index per sec and about 50-60 search per sec
4- always the master node fails 
5- if needed I can post jvm and elastic.yml files and logs.

**Comment by dadoonet** [comment]
Please ask this question on https://ela.st/forum where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on https://ela.st/forum.

Thanks!
