### ISSUE TITLE
Last good commit doesn't work for bwc tests

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44327]
Also described in #43971 and https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+release-tests/145/ possibly also failed because of this

**Comment by atorok** [comment]
also https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+bwc-tests/145/ is a suspect

**Comment by atorok** [comment]
Looking at the failure at #43971  runbld set appears to have set build metadata  
```
BUILD_METADATA: bwc_refspec_distribution:bwc:bugfix=7c9aa15746b1bf48740df2390bb3066b59148832;bwc_refspec_distribution:bwc:minor=553f783e735b24a5eea3730d3ce97c7af74bfcc2
```
and the build picked that up properly 
```
02:24:40 > Task :distribution:bwc:bugfix:checkoutBwcBranch
02:24:40 Checking out elasticsearch 7c9aa15746b1bf48740df2390bb3066b59148832 for branch 7.2
02:24:40 
02:24:40 > Task :distribution:bwc:minor:checkoutBwcBranch
02:24:40 Checking out elasticsearch 553f783e735b24a5eea3730d3ce97c7af74bfcc2 for branch 7.x
02:24:40 
```

**Comment by atorok** [comment]
This is the intake build acting as last good commit: 
https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-1531848254847/t?id=20190703181815-589A85DE&_g=()

`e84a79a8fb309d608f7ebb9fefb6f1a9ec61304e`  is the commit that build ran on and 
```
:distribution:bwc:minor:writeBuildMetadata
--
Checked out elasticsearch commit 50e96f9f0e9a967fb5e368c05287ea8d0e8e1316
 
:distribution:bwc:minor:buildBwcDarwinTar
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
:distribution:bwc:bugfix:writeBuildMetadata
Checked out elasticsearch commit 7c9aa15746b1bf48740df2390bb3066b59148832 
```
is the metadata it produced based on the scan at: https://scans.gradle.com/s/7bxf2pb4mafac/console-log

**Comment by atorok** [comment]
https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-1531848254847/t/?id=20190703231934-26691C32 is the build that failed.
The registered metadata in build-stats looks to be the same as what was passed to that build, even trough the build that produced the metadata seems to have produced something different

**Comment by atorok** [comment]
```
:distribution:bwc:minor:checkoutBwcBranch
--
Checking out elasticsearch elastic/7.x for branch 7.x
:distribution:bwc:minor:writeBuildMetadata
Checked out elasticsearch commit 553f783e735b24a5eea3730d3ce97c7af74bfcc2

:distribution:bwc:bugfix:checkoutBwcBranch
--
Checking out elasticsearch elastic/7.2 for branch 7.2
:distribution:bwc:bugfix:writeBuildMetadata
Checked out elasticsearch commit 7c9aa15746b1bf48740df2390bb3066b59148832
```
from https://scans.gradle.com/s/3otqrma5vxmha/console-log note that the previus commit included messages from our invocation of Gradle with parallel, between then and the second invocation it seems there was a push to the branch so it got updated again when we invoked Gradle again this time without  parallel, so it blew away our optimization but still shouldn't have failed

**Comment by atorok** [comment]
`553f783e735b24a5eea3730d3ce97c7af74bfcc2` has the current version set to `7.4.0` but last good commit is  `e84a79a` that expects `7.x` to still be at `7.3.0` .
In other words it's expected that the mac build would fail, it's strange that the intake build didn't fail in the same way.  

The reason the intake build didn't fail is that we don't do a clean between the Gradle invocations  so the first run that build bwc in parallel created the `7.3.0` artifacts that were still there when the second one ran, but the metadata was stored for the second one causing the subsequent mac build using last goot commit to fail even trough the intake build it was based on did not.

**Comment by atorok** [comment]
The problem in release tests seem to be different @leathekd  runbld seems to have simply missed last good commit info. The config of the job did not change, yet, there's no indication in the log that last good commit as missed in this specific build: 
https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+release-tests/145/

here's another where it did work: https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+release-tests/154/consoleFull

**Comment by leathekd** [comment]
The behavior here is that build 145 (the failing one) was kicked off by elasticmachine with an overridden `branch_specifier` ([see the params here](https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+release-tests/145/parameters/)).  In this case runbld assumes that the user has set the branch specifically and on purpose and doesn't attempt to do anything with the last good commit.  Unfortunately, the downstream effect is that build metadata isn't loaded.

Do you know how build 145 was started?

**Comment by atorok** [comment]
Thanks ! I have no idea how it was started ... Jenkins said it was elasticmachine . Is it possible we have some automation ?
