### ISSUE TITLE
Clarify the docs on the LDAP nested groups limitation

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#44333]
Our [security limitations doc](https://www.elastic.co/guide/en/elastic-stack-overview/7.2/security-limitations.html#_ldap_realm) says that we don't _support the discovery of nested LDAP Groups_.
This is true - we have no explicit support for discovering nested groups. However, it a little misleading because we do support nested groups _if the directory implements them transparently_ as some directory do (or at least claim to).

It might be helpful to add a few more words in there, to be clear that we are dependent on the directory server to do this for us.

**Comment by tvernum** [comment]
Relates: https://github.com/elastic/elasticsearch/issues/43921

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. Still relevant.

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
