### ISSUE TITLE
Multipe org.elasticsearch.xpack.ccr.CcrAliasesIT failing on Mac

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44353]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/84/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/85/#showFailuresLink
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/87/

Scans:
https://gradle.com/s/4ljj6i5tvjmte
https://gradle.com/s/kgs343wrehidw
https://gradle.com/s/kmxybkv4odxyc

```
org.elasticsearch.xpack.ccr.CcrAliasesIT.testRemoveExistingAlias
org.elasticsearch.xpack.ccr.CcrAliasesIT.testAddAlias
org.elasticsearch.xpack.ccr.CcrAliasesIT.testStress
org.elasticsearch.xpack.ccr.CcrAliasesIT.testAddExplicitNotWriteAlias
org.elasticsearch.xpack.ccr.CcrAliasesIT.testWriteAliasIsIgnored
org.elasticsearch.xpack.ccr.CcrAliasesIT.testAddMultipleAliasesSequentially
org.elasticsearch.xpack.ccr.CcrAliasesIT.testUpdateExistingAlias
org.elasticsearch.xpack.ccr.CcrAliasesIT.testAddMultipleAliasesAtOnce
org.elasticsearch.xpack.ccr.CcrAliasesIT.testAliasOnIndexCreation
org.elasticsearch.xpack.ccr.CcrAliasesIT.classMethod

```

**Comment by ywelsch** [comment]
Duplicates https://github.com/elastic/elasticsearch/issues/41071
