### ISSUE TITLE
Support Missing Range Values

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#44381]
While working on #41545 we observed that it's not currently possible to provide missing or scripted values for Range fields.  There are two major steps to support this.  First off, the parsers need to accept range fields for missing values (complex objects are not currently supported at all).  This probably also involves requiring some type information from the user.  After that, the `ValuesSourceConfig` and associated classes need to support explicit range missing fields.

**Comment by not-napoleon** [comment]
We discussed this on 2020-08-05.  A few notes:

- We have another ticket, #50190 specifically for script support.
- Adding script support for ranges has implications for #59332 so there's some impetus to support range scripting for that use case.
- Missing support is a distinct problem, not solved by script support.  I'm going to update this ticket to only refer to missing.
- We're interested in missing support for ranges, but that's considerably lower priority.

**Comment by wchaparro** [comment]
not planned
