### ISSUE TITLE
[CI] SamlAuthenticationIT.testLoginUserWithSamlRoleMapping failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#44410]
SamlAuthenticatorIT. testLoginUserWithSamlRoleMapping failed on
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+EAR/27/console

```
11:31:36 FAILURE 3.07s | SamlAuthenticationIT.testLoginUserWithSamlRoleMapping <<< FAILURES!
11:31:36    > Throwable #1: java.lang.AssertionError: Unexpected HTTP Response status: HTTP/1.1 503 Service Unavailable
11:31:36    > Expected: <200>
11:31:36    >      but: was <503>
11:31:36    > 	at __randomizedtesting.SeedInfo.seed([43BF4801CCD3AC0E:CC50FE2BD895C0D3]:0)
11:31:36    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.assertHttpOk(SamlAuthenticationIT.java:594)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$goToLoginPage$1(SamlAuthenticationIT.java:353)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:502)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.goToLoginPage(SamlAuthenticationIT.java:352)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.loginViaSaml(SamlAuthenticationIT.java:263)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithSamlRoleMapping(SamlAuthenticationIT.java:245)
11:31:36    > 	at java.lang.Thread.run(Thread.java:748)
```
Locally could not reproduce on 6.8:
```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner -Dtests.seed=43BF4801CCD3AC0E -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT -Dtests.method="testLoginUserWithSamlRoleMapping" -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=US/Hawaii -Dcompiler.java=12 -Druntime.java=8
```

Not muting for the moment as very few failures are noticed and only on 6.8 branch

**Comment by jkakavas** [comment]
This is the `MockHttpServer` returning a 503 after Elasticsearch builds the SAML Authentication request successfully. 

This only failed [4 times between July 03 and July 15](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SamlAuthenticationIT),sort:!(time,desc))) but I can't figure out which commit in 6.8 could have introduced an issue. I will keep an eye on it for now, close it in a week if we see no more failures or investigate further if we see more

**Comment by jkakavas** [comment]
Closing this in the absence of new failures.

**Comment by jkakavas** [comment]
This failed again 6 times after August 16th  : https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SamlAuthenticationIT),sort:!(time,desc)), reopening to investigate

**Comment by jkakavas** [comment]
```java
 private void httpLogin(HttpExchange http) throws IOException {
        final Map<String, String> body = Collections.singletonMap("acs", this.acs.toString());
        Request request = buildRequest("POST", "/_security/saml/prepare", body, kibanaAuth());
        final Response prepare = client().performRequest(request);
        assertOK(prepare);
        final Map<String, Object> responseBody = parseResponseAsMap(prepare.getEntity());
        logger.info("Created SAML authentication request {}", responseBody);
        http.getResponseHeaders().add("Set-Cookie", REQUEST_ID_COOKIE + "=" + responseBody.get("id"));
        http.getResponseHeaders().add("Location", (String) responseBody.get("redirect"));
        http.sendResponseHeaders(302, 0);
        http.close();
    }
```

The authentication request is printed and I would assume that the http exchange is closed properly because otherwise the `HttpHandler#handle` would throw. Still not quite sure what sets the status to 503. If the context was not correctly registered somehow, we'd get a 404. If the server wasn't started for some reason, we'd get a `java.net.SocketTimeoutException` and if there was an error with the response body/headers handle would throw.. 

Don't have many more ideas atm, pinging @tvernum in case he has some

**Comment by tvernum** [comment]
Another failure (master)
- https://gradle-enterprise.elastic.co/s/tn47j66hql44e/console-log?task=:x-pack:qa:saml-idp-tests:integTestRunner

```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner --tests "org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithSamlRoleMapping" \
  -Dtests.seed=B490BF33252A7897 \
  -Dtests.security.manager=true \
  -Dtests.locale=ki \
  -Dtests.timezone=America/Kentucky/Louisville \
  -Dcompiler.java=12 \
  -Druntime.java=11
```
- org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT testLoginUserWithAuthorizingRealm
- org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT testLoginUserWithSamlRoleMapping
- org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT testLoginWithWrongRealmFails

I'll try to find time to look into this soon.

**Comment by jkakavas** [comment]
This started to fail quite a lot, I'm muting tests until we get to the bottom of it

**Comment by jkakavas** [comment]
Muted in 6.8, 7.3, 7.4, 7.x and master
