### ISSUE TITLE
Note blocks with capitilization senstive characters render differently outside of github

### ISSUE THREAD

**Issue by SeanPlacchetti** [elastic/elasticsearch#44447]
**Steps to reproduce**:

View the api-reference, https://www.elastic.co/guide/en/elasticsearch/reference/master/date-math-index-names.html in firefox. Image attached.

![image](https://user-images.githubusercontent.com/5383704/61317119-59044900-a7d0-11e9-9ca1-08a826fe51e0.png)

**Comment by dadoonet** [comment]
Yeah. This has been reported to the web design team who is working on a fix.
Thanks!

**Comment by dadoonet** [comment]
It has been fixed. Thanks for flagging! 🤗
