### ISSUE TITLE
the class org.apache.lucene.queryparser.classic.MapperQueryParser import java.text.ParseException? 

### ISSUE THREAD

**Issue by lurongjiang** [elastic/elasticsearch#44470]
While running local elsaticsearch,the IDEA present me some problem:
- 1.Override getFieldQuery error,should the java.text.ParseException be replaced by org.apache.lucene.queryparser.classic.ParseException
- 2.But when I change the class java.text.ParseException to org.apache.lucene.queryparser.classic.ParseExceptio,the method seem to need java.text.ParseException

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
