### ISSUE TITLE
False positives/Unexpected results using percolation with search

### ISSUE THREAD

**Issue by karlbanke** [elastic/elasticsearch#44474]
We are running Elasticsearch 6.2 as an AWS managed service. Configuration has 3 data nodes and 2 dedicated master nodes but the same condition can be observed using a single elasticsearch node only. 

After indexing items, we run percolations against user stored queries passing in the item as a datastructure. We are sorting the documents using the following code in order to use search after for large number of results. 

`  "sort": [
    {
      "_id": {
        "order": "asc"
      }
    }
  ],
`
When the sort condition is present, we observe that sometimes we get a very large number of matched percolators.

The percolator query is performed as as shown below. Note that this behaviour is intermittent and only observed for some documents. Once it has been observed for one document it can be reproduced with the same document.

`
{
  "size": "1000",
  "sort": [
    {
      "_id": {
        "order": "asc"
      }
    }
  ],
  "query": {
    "percolate": {
      "field": "query",
      "document": {
        "select_feeds": [
          "sel_Greenpeaceplattform",
          "sel_VolkswagenAG"
        ],
        "category": [
          "http://g2.dpa.com/cv/category/pl"
        ]
      }
    }
  }
}
`

In the returned result we get back 18 out of 21 indexed percolator queries. However for most of these the snippet

`
"fields": {
                    "_percolator_document_slot": [
                        0
                    ]
                }
`

is entirely missing. On short, when we sort

- 13 matching and non matching results out of 21 queries are returned
- Only five have the _percolator_document_slot set
- _score is null (expected)

When we do not sort 

- 5 matching results are returned
- All have the _percolator_document_slot set
- _score is set

When we sort and use "track_scores": true

- 5 matching results are returned
- All have the _percolator_document_slot set
- _score is set

When we query only a single "select_feed" item.

- Only matching items are returned
- All have the _percolator_document_slot set
- _score is null (expected)

Fron my understanding, from the documentation of the percolator query, it should never return queries that do not match the document. When percolating a single document using the "_percolator_document_slot" is neither required nor expected. ("The _percolator_document_slot field indicates which document has matched with this query. Useful when percolating multiple document simultaneously.").

Below find the full result list

`
{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": null,
        "hits": [
            {
                "_index": "filterbadges",
                "_type": "newsitem",
                "_id": "https://devel.dpa-select.de/filters/api/v1/27fcf210-a7d2-11e9-a970-819ba8e9b221",
                "_score": null,
                "_source": {
                    "meta": {
                        "owner": "banke@mecom.de",
                        "name": "Politik",
                        "link": "https://devel.dpa-select.de/filters/api/v1/27fcf210-a7d2-11e9-a970-819ba8e9b221",
                        "isPublic": false
                    },
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            },
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/pl"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_SpringerFachmedien",
                                            "sel_VolkswagenAG"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                },
                "fields": {
                    "_percolator_document_slot": [
                        0
                    ]
                },
                "sort": [
                    "https://devel.dpa-select.de/filters/api/v1/27fcf210-a7d2-11e9-a970-819ba8e9b221"
                ]
            },
            {
                "_index": "filterbadges",
                "_type": "newsitem",
                "_id": "https://devel.dpa-select.de/filters/api/v1/a5180380-4f16-11e9-9db3-219dda5eaa59",
                "_score": null,
                "_source": {
                    "meta": {
                        "owner": "andrew@factorial.io",
                        "name": "Politik",
                        "link": "https://devel.dpa-select.de/filters/api/v1/a5180380-4f16-11e9-9db3-219dda5eaa59",
                        "isPublic": false
                    },
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/pl"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_Greenpeaceplattform",
                                            "sel_IHKBerlin",
                                            "sel_VolkswagenAG",
                                            "select_afx_test"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                },
                "fields": {
                    "_percolator_document_slot": [
                        0
                    ]
                },
                "sort": [
                    "https://devel.dpa-select.de/filters/api/v1/a5180380-4f16-11e9-9db3-219dda5eaa59"
                ]
            }
        ]
    }
}
`

**Comment by karlbanke** [comment]
Also, when I use only either one of the two terms in the select_feed field of the percolated document it works correctly.

**Comment by hpetru** [comment]
@karlbanke Hello Karl, can you proved a snippet of code which will allow me to reproduce this issue, I was trying to get the same behavior on origin/6.2 branch and had no luck in getting this problem
https://gist.github.com/hpetru/4bb2c21b309641e863debd258e60425f - here are my steps for reproducing this issue, after indexing all those documents I queried ES 15 times and always ES was returning right results

**Comment by karlbanke** [comment]
@hpetru Thanks for checking. I use the following 4 documents. 

`
{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 4,
        "max_score": 1,
        "hits": [
            {
                "_index": "filterbadges",
                "_type": "_doc",
                "_id": "nu00GmwBIuAyBPQRqwpK",
                "_score": 1,
                "_source": {
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            },
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/ku"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_SpringerFachmedien",
                                            "sel_VolkswagenAG"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                }
            },
            {
                "_index": "filterbadges",
                "_type": "_doc",
                "_id": "ee0zGmwBIuAyBPQRtgqM",
                "_score": 1,
                "_source": {
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            },
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/pl"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_SpringerFachmedien",
                                            "sel_VolkswagenAG"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                }
            },
            {
                "_index": "filterbadges",
                "_type": "_doc",
                "_id": "VO05GmwBIuAyBPQRJgvr",
                "_score": 1,
                "_source": {
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            },
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/pl"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_SpringerFachmedien",
                                            "sel_VolkswagenAG",
                                            "sel_SomeYetOther",
                                            "sel_SomeTotallyOther"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                }
            },
            {
                "_index": "filterbadges",
                "_type": "_doc",
                "_id": "Te04GmwBIuAyBPQR_Qvq",
                "_score": 1,
                "_source": {
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "bool": {
                                        "must": [
                                            {
                                                "bool": {
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            },
                                            {
                                                "bool": {
                                                    "should": [
                                                        {
                                                            "terms": {
                                                                "category": [
                                                                    "http://g2.dpa.com/cv/category/ku"
                                                                ],
                                                                "boost": 1
                                                            }
                                                        }
                                                    ],
                                                    "adjust_pure_negative": true,
                                                    "boost": 1
                                                }
                                            }
                                        ],
                                        "adjust_pure_negative": true,
                                        "boost": 1
                                    }
                                },
                                {
                                    "terms": {
                                        "select_feeds": [
                                            "sel_SpringerFachmedien",
                                            "sel_VolkswagenAG",
                                            "sel_SomeOther",
                                            "sel_SomeTotallyOther"
                                        ],
                                        "boost": 1
                                    }
                                }
                            ],
                            "adjust_pure_negative": true,
                            "boost": 1
                        }
                    }
                }
            }
        ]
    }
}
`

And the following query

`{
   "size":"1000",
   "sort":[
      {
         "_id":{
            "order":"asc"
         }
      }
   ],
   "query":{
      "percolate":{
         "field":"query",
         "document":{
            "select_feeds":[
               "sel_SpringerFachmedien",
               "sel_VolkswagenAG"
            ],
            "category":[
               "http://g2.dpa.com/cv/category/pl"
            ]
         }
      }
   }
}`

against the Elasticsearch 6.2.0 Docker Container. This returns 4 hits (all documents!) instead of the expected 2. 

As soon as I provide only one feed for the document the result is correct (query see below).

`{
   "size":"1000",
   "sort":[
      {
         "_id":{
            "order":"asc"
         }
      }
   ],
   "query":{
      "percolate":{
         "field":"query",
         "document":{
            "select_feeds":[
               "sel_SpringerFachmedien"
            ],
            "category":[
               "http://g2.dpa.com/cv/category/pl"
            ]
         }
      }
   }
}`

**Comment by hpetru** [comment]
This bug is for ES from 6.2.0 until ES 6.2.4, 6.2.4 is fixed, this commit https://github.com/elastic/elasticsearch/commit/12b50ab89a08e11d003f43efcab21004fa3bf1b4 which was introduced in version 6.2.4 solves bug described by you above

You should just update your ES server from 6.2.0 to 6.2.4

**Comment by romseygeek** [comment]
Fixed by 12b50ab
