### ISSUE TITLE
ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary() fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#44479]
The test `testPromoteReplicaToPrimary()` failed today on CI:
https://scans.gradle.com/s/k3fjyxepqf2kc

```
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.indices.recovery.ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary" -Dtests.seed=74EB02FB45178972 -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=Asia/Harbin -Dcompiler.java=12 -Druntime.java=11
--
2> java.lang.AssertionError: CloseIndexResponse failed - not acked
Expected: <true>
but: was <false>
at __randomizedtesting.SeedInfo.seed([74EB02FB45178972:FE9BAE80DCAFA5B9]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:110)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:98)
at org.elasticsearch.indices.recovery.ReplicaToPrimaryPromotionIT.testPromoteReplicaToPrimary(ReplicaToPrimaryPromotionIT.java:60)

```

Closing the index was not acknowledged. It does not reproduce locally after multiple runs but I suspect that it happens on slower machines with a high number of shards and/or with async translog durability, and that the global checkpoint takes time to catch up with the max seq no on replicas when closing the index.

We could retry to close the index but before I'd like to add more log traces to get the full close index response to confirm my assumption.

**Comment by DaveCTurner** [comment]
It looks like https://gradle.com/s/e7brc5neezwyi failed similarly, after the extra logging was added.

**Comment by tlrx** [comment]
The two last test failures show that the reason (and cause) of the failure is not rendered out in the `CloseIndexResponse` because of #45203. I'd like #45203 to be merged so that the exact cause of failure will appear in the test logs.

**Comment by tlrx** [comment]
Closing the issue as #45203. If this test fails again, please reopen with the log trace.
