### ISSUE TITLE
[feature request] add query hash for slow log

### ISSUE THREAD

**Issue by hufuman** [elastic/elasticsearch#44537]
Describe the feature:
We created "query hash" for DSL to classify different requests. We think it maybe useful for people need to solve slow query.

For example, we have three pieces of codes:

` Code A:
{
    "query": {
        "terms": {
                "type": [1,2,3]
        }
    }
}
`

` Code B:
{
    "query": {
        "terms": {
                "type": [2,3,4]
        }
    }
}
`

` Code C:
{
    "query": {
        "match": {
                "name": "Jack"
        }
    }
}
`

We treat A and B are the same kind, because their struct are the same, even though different parameters. But C is different cause of its unique struct.

Furthermore, we calculate query hash considering sorts. Different types (scripts/plain) or ordering are factors that will lead to different query hash.

We submit query hash/took/diff(real interval minus took) to our APM, so we can know which types of query impact performance more.

**Comment by pgomulka** [comment]
Hey @hufuman , that sounds like an interesting idea
so if I understand correctly CodeA & CodeB will result in the same hash ? but Code C will ahve a different hash?
Have you considered using `X-Opaque-ID` as a header being part of you query?
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/index-modules-slowlog.html
This  should also be available in 7.3, I will improve the docs

**Comment by astefan** [comment]
No further feedback received. @hufuman if you have more details to add, to help assess the utility of such a feature, please add it in a comment and we can look at re-opening this issue.
