### ISSUE TITLE
elasticsearch throws error: Connection reset by peer

### ISSUE THREAD

**Issue by PeterMen** [elastic/elasticsearch#44546]
I use elasticsearch java High level rest client ,  but it always throw error : connection reset by peer.

**elasticsearch-rest-high-level-client:6.5.4**

**error logs below:**
java.io.IOException: Connection reset by peer
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:954)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
        ......

**I init my highlevelClient  below:**

`RestClientBuilder builder = RestClient.builder(hosts);

builder.setRequestConfigCallback(requestConfigBuilder -> {
            requestConfigBuilder.setConnectTimeout(Integer.valueOf(PropertyUtils.getProperty(CONNECT_TIME_OUT)));
            requestConfigBuilder.setSocketTimeout(Integer.valueOf(PropertyUtils.getProperty(SOCKET_TIME_OUT)));
            requestConfigBuilder.setConnectionRequestTimeout(Integer.valueOf(PropertyUtils.getProperty(CONNECTION_REQUEST_TIME_OUT)));
            return requestConfigBuilder;
        });

builder.setHttpClientConfigCallback(httpClientBuilder -> {
            httpClientBuilder.setMaxConnTotal(Integer.valueOf(PropertyUtils.getProperty(MAX_CONNECT_NUM)));
            httpClientBuilder.setMaxConnPerRoute(Integer.valueOf(PropertyUtils.getProperty(MAX_CONNECT_PER_ROUTE)));
            return httpClientBuilder;
        });

RestHighLevelClient client = new RestHighLevelClient(builder);`

**Comment by astefan** [comment]
@PeterMen this appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. Would you mind asking this question there, please?

**Comment by PeterMen** [comment]
the forums have a lot of the same questions like mine, but no good answer, all be auto closed  .  For example https://discuss.elastic.co/t/highlevel-rest-client-retry-requests-on-failure/163497

How can I solve my problem???

**Comment by siwuai** [comment]
> the forums have a lot of the same questions like mine, but all be auto closed without a right answer . For example https://discuss.elastic.co/t/highlevel-rest-client-retry-requests-on-failure/163497
> 
> How can I solve my problem???

Hello , the same problem happend in my project , has you solved this?

**Comment by alwintom** [comment]
I had the same error while running elasticsearch as a docker container. I fixed it by adding the following line in the elasticsearch.yml file:

network.bind_host: 0.0.0.0

**Comment by OsoriAndOmori** [comment]
@siwuai @alwintom 
I had the same problem as you
but solved the problem by increasing connection timeout.
Default connection timeout of [RestClientBuilder.java](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java#L43) which is builder of RestHighLevelClient
is 1000ms. 

```java
RestClientBuilder builder = RestClient.builder(new HttpHost(endpoint, port))
				.setHttpClientConfigCallback(
						httpClientBuilder -> httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider))
				.setRequestConfigCallback(requestConfigBuilder ->
						requestConfigBuilder.setConnectTimeout(10000).setSocketTimeout(30000));
		return new RestHighLevelClient(builder);
```

In unstable network and various environment, I think it could be take more time than 1000ms.
I hope this will help you.

**Comment by tbook** [comment]
Connecting with the wrong protocol (http vs. https) produces the same error.

**Comment by marielcherkassky** [comment]
Someone found a solution ?

**Comment by alessio-torelli** [comment]
we are facing the same issue. Any solution?
