### ISSUE TITLE
OOM-related failures on Windows

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#44542]
multijob-windows-compatibility test failed with:
```
Execution failed for task ':test:framework:test'.
```

In the logs, there are references to JVM having not enough memory, e.g:
```
08:08:10 Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
08:08:10 > Task :test:framework:test
08:08:10 #
08:08:10 Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
08:08:10 #
08:08:10 Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e0000000, 536870912, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
08:08:10 # There is insufficient memory for the Java Runtime Environment to continue.
08:08:10 # There is insufficient memory for the Java Runtime Environment to continue.
0
```

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2016/19/console
Build Scans: https://gradle.com/s/lsrgz7amvp4gwhttps://gradle.com/s/6eziuaqm6ykbq, https://gradle.com/s/gcpo6o7lmhmdw

**Comment by atorok** [comment]
That's a non ephemeral worker , they somehow all came back to life

**Comment by mark-vieira** [comment]
The static Windows workers are gone now and there hasn't been a build on a non-ephemeral worker in a week so I think this was just a hiccup that's since been cleared up.
