### ISSUE TITLE
Enable shard request cache with DLS and FLS

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#44581]
It seems that shard request cache is disabled when document/field level security is in place. 

We could not find any documentation that explains it, neither in [Shard Request Cache documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html), nor in [Field Level Security documentation](https://www.elastic.co/guide/en/elastic-stack-overview/current/field-level-security.html).  Would be nice to add documentation about this.

**Comment by mayya-sharipova** [comment]
We had some concerns that with the FLS/DLS on, users can't take advantage of request caching anymore, and their queries will run slower.  Do you think it would be possible to redesign `IndicesRequestCache` to incorporate security privileges as well?

**Comment by mayya-sharipova** [comment]
@elastic/es-security, would it be possible to implement `IndicesRequestCache` which would cache requests with a key that incorporates role definitions as well?

**Comment by luzidl** [comment]
@mayya-sharipova have you heart back from Security on the above?

**Comment by mayya-sharipova** [comment]
@luzidl Sorry for a late reply.  I have heard back from the Security team, and they said it is a valid feature request, but it will discussed and implemented according to their schedule.

**Comment by luzidl** [comment]
@mayya-sharipova no worries, it was important to get your feedback and the feedback of the security team. Thanks a mil for discussing with them!

**Comment by wernerb** [comment]
Is there any update on this, will it be on the roadmap?

**Comment by tvernum** [comment]
No one is currently working on this, but I have some ideas on how we might make it work, so it's possible it will make it into a future release.
