### ISSUE TITLE
Improve FieldSubsetReader to return more accurate stats

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch#44637]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.x

**Plugins installed**: []

**JVM version** (`java -version`): n/a

**OS version** (`uname -a` if on a Unix-like system): n/a

**Description of the problem including expected versus actual behavior**:

Improvements for FieldSubsetReader.java

https://github.com/elastic/elasticsearch/blob/81ea7e1802847361d4502c6eb046e2c4265aae44/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java#L340 could be changed to return `return fieldInfos.size();`

and

https://github.com/elastic/elasticsearch/blob/81ea7e1802847361d4502c6eb046e2c4265aae44/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java#L421 should be `return super.getDocCount();` (or just not be overriden) because for _field_names there are always terms (e.g. never empty)

Unittests also passed with these modifications!

**Comment by jtibshirani** [comment]
I took a look but am not very familiar with this area, it would be great if someone from search or security could look as well.

@mistevenson for context, was there an external motivation behind this change (perhaps there was a higher-level behavior you noticed that made you consider the change)?

**Comment by mistevenson** [comment]
@jtibshirani Just something I observed during security researching ...

**Comment by jimczi** [comment]
There are comments in the code explaining why we return `-1` and uses `maxDoc()`. I am closing this issue since the behavior is expected in this layer.
