### ISSUE TITLE
basic_date illegal_argument_exception vs yyyyMMdd

### ISSUE THREAD

**Issue by tstilwell** [elastic/elasticsearch#44640]
**Elasticsearch version** : 7.2.0

**Plugins installed**: none

**JVM version** :
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version**: CentOS Linux release 7.6.1810 (Core) x86_64

**Description of the problem including expected versus actual behavior**:
When trying to map a date field to accept either `yyyyMMdd` or `yyyy-MM-ddTHH:mm:ss.SSSZ`, according to 7.2 documentation it looks like specifying `"format": "basic_date||strict_date_optional_time"` should work, and the mapping should be accepted. However, trying to put a mapping with the above fails (haven't even indexed any documents at this point - the mapping itself fails):

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"formatters must have the same time zone"}],"type":"illegal_argument_exception","reason":"formatters must have the same time zone"},"status":400}`

However, specifying `"format": "yyyyMMdd||strict_date_optional_time"` works, and the mapping is accepted. 

Obviously something to do with switch from joda to java. `basic_date||strict_date_optional_time` worked in versions of ES prior to v7.

**Steps to reproduce**:

Broken:
```
PUT localhost:9200/my_index
{
  "mappings": {
    "date_detection": false,
    "properties": {
      "myDate": {
        "type":   "date",
        "format": "basic_date||strict_date_optional_time"
      }
    }
  }
}
```
result:
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"formatters must have the same time zone"}],"type":"illegal_argument_exception","reason":"formatters must have the same time zone"},"status":400}`

Working example (from docs one would assume basic_date and yyyyMMdd are synonymous):
```
PUT localhost:9200/my_index
{
  "mappings": {
    "date_detection": false,
    "properties": {
      "myDate": {
        "type":   "date",
        "format": "yyyyMMdd||strict_date_optional_time"
      }
    }
  }
}
```
result:
```
{"acknowledged":true}
```

**Comment by pgomulka** [comment]
@tstilwell Thank you for raising this issue. This indeed looks like a bug, both `basic_date||strict_date_optional_time` should use  UTC timezone as default. They in fact do, but the validation logic in 7.2 is incorrect.
The validation in ES 7.5 is less strict so this  should work.
Also if you plan on using yyyyMMdd , it would be better to use `uuuuMMdd`. We use strict resolving in 7.5 so it might not work for some scenarios for you.

**Comment by pgomulka** [comment]
@tstilwell I hope my previous comment is sufficient to work around. I will close the issue. 
Let me know if you need more assistance
