### ISSUE TITLE
errors when building elasticsearch, please help me to check  

### ISSUE THREAD

**Issue by qinluyao761** [elastic/elasticsearch#44651]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by qinluyao761** [comment]
[root@ceph1 elasticsearch-6.7.2-src]# gradle assemble
> Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE
> Task :buildSrc:compileMinimumRuntimeGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileMinimumRuntimeGroovy'.
> Could not resolve all files for configuration ':buildSrc:minimumRuntimeCompileClasspath'.
   > Could not resolve junit:junit:4.12.
     Required by:
         project :buildSrc
      > Could not resolve junit:junit:4.12.
         > Could not get resource 'https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.pom'.
               > jcenter.bintray.com: Name or service not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by jasontedor** [comment]
That looks like a transient network error, or an issue with your DNS resolver.

We reserve GitHub for verifies bugs and feature requests and offer the [forums](https://discuss.elastic.co) for discussion, questions, and troubleshooting. If you have follow-ups, please use the forums.
