### ISSUE TITLE
Got Different uuid error after cluster configs

### ISSUE THREAD

**Issue by Amirhossein2000** [elastic/elasticsearch#44650]
I needed to use elasticsearch for one of my BigData projects so I installed elasticsearch and start testing by random data , after many inserts I wanted to start clustering and add one more server.
I did all of the configs correctly but I still get this error --> **join validation on cluster state with a different cluster UUID q elasticsearch**
this error takes me 10 hours to fix and I understand I had to delete old files of my tests.
I think if we just add one more sentence to the error log will make this problem easy to solve for others.

**Comment by DaveCTurner** [comment]
Please keep the discussion of your PR on the thread for your PR. No need for a separate issue, so I'm closing this.
