### ISSUE TITLE
No field found for [group] in mapping with types []

### ISSUE THREAD

**Issue by xfmo** [elastic/elasticsearch#44692]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.5.1

**Plugins installed**: []

**JVM version** (`java -version`):1.8.0_111

**OS version** (`uname -a` if on a Unix-like system):  Darwin bogon 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

curl -X POST -H "Content-Type: application/json"  -d '{"size": 1, "query": {"bool": {"must": [{"match": {"scene": "open.order.split"} }, {"match": {"group.company": "test"} } ] } }, "aggs": {"group": {"sum": {"script": "int score = 0; if(doc.containsKey(\u0027group\u0027)) { for (el in doc[\u0027group\u0027]) {if (el.company_id == -1) {score += el.money}} }else {score = 0;} return score;"} } } }'   'http://10.11.5.227:9200/monitor-real-time-2019.07.22/_search?pretty'

I use 'doc.containsKey(\u0027group\u0027)' but only get group value 0.0.

If i not use "doc.containsKey('group')" and get an error "No field found for [group] in mapping with types []"

result 
  ```{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 6,
    "max_score" : 1.3864851,
    "hits" : [
      {
        "_index" : "monitor-real-time-2019.07.22",
        "_type" : "log",
        "_id" : "my_id_21563797701",
        "_score" : 1.3864851,
        "_source" : {
          "scene" : "open.order.split",
          "user_id" : 7,
          "log_time" : 1563797701,
          "flag" : true,
          "group" : [
            {
              "company_id" : -1,
              "company" : "test",
              "money" : 100
            },
            {
              "company_id" : 2,
              "company" : "test",
              "money" : 200
            }
          ]
        }
      }
    ]
  },
  "aggregations" : {
    "group" : {
      "value" : 0.0
    }
  }
}
```

My  mapping 
```{
  "monitor-real-time-2019.07.22": {
    "mappings": {
      "log": {
        "properties": {
          "flag": {
            "type": "boolean"
          },
          "group": {
            "properties": {
              "company": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "company_id": {
                "type": "long"
              },
              "money": {
                "type": "long"
              }
            }
          },
          "log_time": {
            "type": "long"
          },
          "scene": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "user_id": {
            "type": "long"
          }
        }
      }
    }
  }
}
```

Can not get sum money

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tlrx** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by OpakAlex** [comment]
@tlrx you so nice guy, but if you checked forum, nobody provided really answer how to access array in script filter. It's 5 posts, and no 1 answer how to, just stupid answer what is slow and what is fast, can you provide answer or not here?

**Comment by tlrx** [comment]
@OpakAlex I'm afraid there is no one fits all answer to this 2 year old issue. Can you point me to the post you opened on the forum please?

**Comment by rooch84** [comment]
`doc['group.company_id']` is the syntax you need. 

I found it in a comment here: https://stackoverflow.com/questions/42394039/elasticsearch-no-field-found-in-mapping-while-executing-custom-score-script
