### ISSUE TITLE
`path_hierarchy` generates more tokens in reverse mode

### ISSUE THREAD

**Issue by LordMike** [elastic/elasticsearch#44709]
(note: I reproduced this on the docker image for ES 7.2.0)

**Elasticsearch version** (`bin/elasticsearch --version`): `7.2.0`

**Plugins installed**: None.

**JVM version** (`java -version`): es reports jdk version `12.0.1`

**OS version**: `Linux 308bcfaae31e 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

When I create a custom analyzer that uses the `path_hierarchy` tokenizer, and set the `reverse` option to `true`, I get more tokens than if reverse was not set. This happens for "invalid data".

According to the docs, the tokens should be in a reverse order - which they are ... but there are more tokens. From looking at it, I also note that:

* It seems as if the tokens from reverse mode, actually interpret the Hierarchy from Right-to-left, and thus isn't a simple reversing of the Left-to-right tokens ?
* This also happens with "valid data", `/parent/file`, this seems to confirm for me that the docs are wrong.

**Steps to reproduce**:
```
DELETE /bug_44709

PUT /bug_44709
{
    "settings": {
        "analysis": {
            "tokenizer": {
                "reverse_hierarchy": {
                    "type": "path_hierarchy",
                    "reverse": true
                }
            }
        }
    }
}

// This analysis returns 3 tokens
// /parent, /parent/, /parent//file
POST /bug_44709/_analyze
{
    "tokenizer": "path_hierarchy",
    "text": "/parent//file"
}

// This analysis returns 4 tokens
// /parent//file, parent//file, /file, file
POST /bug_44709/_analyze
{
    "tokenizer": "reverse_hierarchy",
    "text": "/parent//file"
}
```

**Provide logs (if relevant)**:

**Comment by mayya-sharipova** [comment]
@LordMike Thanks for filling the issue. Indeed, I confirm this behaviour. This behaviour comes from the corresponding Lucene's tokenizers.
But I would not call it a bug, it just features how these tokenizers work.  I have created a [PR](https://github.com/elastic/elasticsearch/pull/44910) to update our documentation to reflect this.

About "invalid data", often tokenizers expect the input in some valid form, and it is our responsibility to clean the input before passing it to tokenizers.

**Comment by LordMike** [comment]
Great to have the docs updated. Could a "reverse" tokenizer be made that, in general, can reverse the stream -- and the limit tokenizer get an option to skip tokens also?

My end goal is to index the parent directory to a full path. So `/a/b/c` should index `/a/b/`. I envisioned that I could tokenize as path, reversed, and then skip/take to get just the one token I need.

**Comment by mayya-sharipova** [comment]
>  Could a "reverse" tokenizer be made that, in general, can reverse the stream -- and the limit tokenizer get an option to skip tokens also?

Internally we use Lucene tokenizers and expose their functionalities. You can [file an issue](https://issues.apache.org/jira/projects/LUCENE) in Lucene, and ask for that.

For you use case, you may consider [pattern tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-tokenizer.html).

> Certainly you mean your responisibility, right? -- not our responsibility
Right, our responsibility as ES users and developers

**Comment by ZLightning** [comment]
@LordMike see issue #44833 to understand what the reverse option is designed for
