### ISSUE TITLE
OperationModeFileWatcherTests can fail with assertion error

### ISSUE THREAD

**Issue by ebadyano** [elastic/elasticsearch#44701]
The failure doesn't reproduce for me locally.

Link to the build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/358/console

Command to reproduce:

```
./gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.license.OperationModeFileWatcherTests.testUpdateModeFromFile" \
  -Dtests.seed=553B2DE4C5A7DD90 \
  -Dtests.security.manager=true \
  -Dtests.locale=ne \
  -Dtests.timezone=UTC \
  -Dcompiler.java=12 \
  -Druntime.java=11

```
Relevant excerpt from the logs:
```
06:37:06   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.license.OperationModeFileWatcherTests.testUpdateModeFromFile" -Dtests.seed=553B2DE4C5A7DD90 -Dtests.security.manager=true -Dtests.locale=ne -Dtests.timezone=UTC -Dcompiler.java=12 -Druntime.java=11
06:37:06   2> java.lang.AssertionError: 
06:37:06     Expected: <BASIC>
06:37:06          but: was <GOLD>
06:37:06         at __randomizedtesting.SeedInfo.seed([553B2DE4C5A7DD90:B99EDD80697A288D]:0)
06:37:06         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
06:37:06         at org.junit.Assert.assertThat(Assert.java:956)
06:37:06         at org.junit.Assert.assertThat(Assert.java:923)
06:37:06         at org.elasticsearch.license.OperationModeFileWatcherTests.testUpdateModeFromFile(OperationModeFileWatcherTests.java:73)
```

**Comment by ebadyano** [comment]
another failure from Juky 18th: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/322/consoleFull

**Comment by jkakavas** [comment]
It's not only `testUpdateModeFromFile` that fails like this, but other methods in the same class as can be seen [here](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(branch,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:OperationModeFileWatcherTests),sort:!(time,desc))) fail with similar errors

**Comment by original-brownbear** [comment]
Another one from today: https://gradle-enterprise.elastic.co/s/t5b6ius4hhetc/tests/sbbvdtbroicas-evjnuheyoawag

**Comment by javanna** [comment]
Another one, this one was `Expected: <PLATINUM> but: was <GOLD>`. See https://gradle-enterprise.elastic.co/s/t56i72xzwn2qa .

**Comment by romseygeek** [comment]
Another one, this time on a PR: https://gradle-enterprise.elastic.co/s/aqyoafff2hhiy/console-log?task=:x-pack:plugin:core:test

**Comment by romseygeek** [comment]
And another PR failure: https://gradle-enterprise.elastic.co/s/mruwate5tbhsq/tests/:x-pack:plugin:core:test/org.elasticsearch.license.OperationModeFileWatcherTests/testUpdateModeFromFile
