### ISSUE TITLE
Randomize gateway node selection in cross cluster search

### ISSUE THREAD

**Issue by vengadanathan-s** [elastic/elasticsearch#44786]
Currently in Elasticsearch during cross cluster search setup, each node in source cluster fetches upto 3 nodes  from remote cluster (via seed node by making cluster state call) and those 3 nodes are always used for handling any cross cluster request. These 3 nodes are picked via remote cluster state call, where in the cluster state, node's list is fixed in particular order, so all the source cluster nodes will always use same set of 3 remote nodes as gateway nodes and traffic to remote cluster will be always skewed to those 3 nodes. 

Instead if we randomize and pick 3 gateway nodes from remote cluster state, that would provide better distribution of cross cluster search across all gateway nodes in remote cluster.

**Comment by vengadanathan-s** [comment]
Adding more detail:

I was referring to this section, https://github.com/elastic/elasticsearch/blob/905ad4e28a0a0969e410d86c2bf2ee61455f1f6c/server/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java#L574-L587 where we pick only first 3 nodes (i.e configurable value) returned by cluster state as gateway nodes , ideally we should randomize and pick 3 nodes to provide efficient distribution of gateway nodes else all source cluster nodes will point to same set of 3 gateway nodes.

**Comment by javanna** [comment]
hi @vengadanathan-s , 
note that the cluster state call performed to retrieve the list of nodes provides the `local` flag set to `true`, hence the list of nodes is not retrieved from the same node, but rather locally from the node hit by the request, which is determined by what `getAnyConnectedNode()` returns on each node. There is no guarantee that the list of nodes will be sorted equally, as nodes are stored in an unsorted map and retrieved from different nodes.

I am curious though, did you experience problems with the selection of gateway nodes and balancing of CCS requests? Would increasing the maximum number of nodes also be a solution?

**Comment by ebadyano** [comment]
No further feedback received. @vengadanathan-s  if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
