### ISSUE TITLE
Common interface for GetField and SearchHitField

### ISSUE THREAD

**Issue by phrone** [elastic/elasticsearch#4479]
Hi, this is a Java client-related suggestion/issue: 
Today I was looking to combine some results retrieved from a GetResponse and a SearchResponse, but I found they don't share an interface, even though they basically serve the same purpose and have the same common methods. It makes perfect sense to let them have a common "GenericField" interface or something similar, containing at least:
String getName();
Object getValue();

Not having such forced to implement a solution that was far from elegant.

Don't you think it's a good idea? Thanks!

**Comment by markharwood** [comment]
It makes sense that Get and Search APIs should share common interfaces where possible for the Field/Doc level constructs returned in results. Any refactoring or introduction of interfaces should be done in a backwards compatible fashion.

**Comment by clintongormley** [comment]
Given that three years have passed with no action, and we're moving away from the transport client to the rest client, I'm going to close this as won't fix
