### ISSUE TITLE
[Feature Request] Add username to slow log output

### ISSUE THREAD

**Issue by hobo05** [elastic/elasticsearch#44811]
**Describe the feature**:

We are currently using the Elastic cloud offering and was recently informed that we can find slow logs by ourselves now in the UI. However, we found that the slow logs output didn't include a username. Given that there may be non-developers that may be creating/viewing dashboards, they may not know what their raw query looks like. Therefore, with only the query to go off of, it's hard to track down exactly who ran the query. It would really useful to include the username of the user who ran the query in the slow log output

**Comment by pgomulka** [comment]
thanks for raising this @hobo05 
username is not used for this at the moment as username/password are used authentication only.
However you can use `X-Opaque-Id` header on your requests and I think you would be able to identify the origin of slow queries

**Comment by hobo05** [comment]
I'll just subscribe to this issue https://github.com/elastic/kibana/pull/41530

**Comment by pgomulka** [comment]
@hobo05 great, bear in mind that on ES side this is already finished and you can use it since 6.4 https://github.com/elastic/elasticsearch/issues/31521

**Comment by asgs** [comment]
@pgomulka #31521 has been closed mentioning it will not be implemented in slow logs. can you please confirm?

**Comment by pgomulka** [comment]
@asgs it says that it was implemented in search slow logs 
but
it wasn't implemented in indexing slow logs. If you want to have an id in indexing slow logs, add it to your document https://github.com/elastic/elasticsearch/issues/31521#issuecomment-406401478

**Comment by asgs** [comment]
@pgomulka oh. sorry. I didn't read that carefully

I'm not getting the id populated in either of indexing or search slow logs. can I open a thread for that in discuss forum?

thank you for the clarification!

**Comment by pgomulka** [comment]
sure, feel free to ping me on a thread if you need assistance

**Comment by asgs** [comment]
@pgomulka created https://discuss.elastic.co/t/x-opaque-id-not-displayed-in-search-slow-log/282067 please check when you get time
