### ISSUE TITLE
Expose segment splitting as an ILM action

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#44819]
We already have the ability to split shards in order to increase the number of shards in an index.

Another operation that is useful is splitting segments into multiple segments. Having more segments generally doesn't help (which is why we recommend force-merging indices) except if you can give these segments interesting properties for query execution. For instance adding high-cardinality clauses tends to slow down queries. If we could split the index so that documents that match a high-cardinality clause end up in exactly one segment, then queries on these high-cardinality clauses could be rewritten as `match_all` queries and automatically removed from the query when used as a filter by Lucene, which would have the potential of significantly speeding up query execution.

For instance if you were doing log analysis on a fleet of servers, it could be interesting to have exactly one segment per server, at least for the most frequently occurring servers in the logs. It would make filtering by those servers much faster.

**Comment by gwbrown** [comment]
This sounds like a very interesting way to optimize data for known query patterns.

Do we currently expose an API for this already, or would that need to be implemented? I'm not aware of one, although please correct me if I'm wrong. ILM actions all run on the master node and are restricted to viewing/modifying cluster state and invoking asynchronous transport actions so actually splitting the segments would likely need to be implemented outside of ILM paired with a relatively simple automation layer in an ILM action.

**Comment by jpountz** [comment]
> Do we currently expose an API for this already, or would that need to be implemented?

That would need to be implemented.

> actually splitting the segments would likely need to be implemented outside of ILM paired with a relatively simple automation layer in an ILM action.

Right this is what I had in mind.

**Comment by jpountz** [comment]
I tried to think more about the pros/cons of this feature. On the pros side:
 - faster filters on the fields used for splitting
 - likely lower disk usage because it would co-locate similar documents (like index sorting)
And cons compared to a force-merged shard
 - would need global ordinals for `terms` aggs
 - slower terms-dict-intensive queries (e.g. fuzzy or regexp)

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
