### ISSUE TITLE
Elastic search High Rest Java client multi search error x_content_parse_exception

### ISSUE THREAD

**Issue by writeaditya** [elastic/elasticsearch#44840]
I'am trying to use Elastic Search with Scala. Using official version https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.2/java-rest-high.html?

Now, I'am trying to make a multi search query as following the given documentation and it is giving parsing exception. I'am not sure where I'am going wrong.

def multiSearch(client: RestHighLevelClient): Unit = {

    val multiRequest = new MultiSearchTemplateRequest()
    val request = new SearchTemplateRequest()
    request.setRequest(new SearchRequest("common_gisdata_2018q4"))

    request.setScriptType(ScriptType.INLINE)
    request.setScript(
      "{" +
        " \"query\":{ \"geo_shape\":{\"ogr_geometry\":{\"shape\":{\"type\":\"circle\"," +
        " \"coordinates\":[55.333,25.269],\"radius\":\"1000.0m\"},\"relation\":\"intersects\"}}}," +
        " \"size\":1,\"sort\":[{\"_geo_distance\":{\"ogr_geometrypoint\":[[55.333,25.269]],\"distance_type\":" +
        " \"arc\",\"mode\":\"min\",\"order\":\"asc\",\"unit\":\"m\"}}],\"_source\":{\"includes\":[\"countryname_ol\"," +
        " \"emiratestateuno\",\"countryname_en\",\"areaname_en\",\"areaname_ol\",\"countryuno\",\"to_roadspeedlimit\"," +
        " \"emiratestatename_ol\",\"emiratestatename_en\",\"streetname_ol\",\"streetname_en\",\"from_roadspeedlimit\"]}}")

    multiRequest.add(request)

    val multiResponse = client.msearchTemplate(multiRequest, RequestOptions.DEFAULT)

    for (item <- multiResponse.getResponses()) {
      if (item.isFailure()) {
        val error = item.getFailureMessage()
      } else {
        val searchTemplateResponse = item.getResponse().getResponse()getHits().getHits

        for(results <- searchTemplateResponse) {
          println(results.getSourceAsString)
        }
      }
    }
  }
It gives an error -

run : ElasticsearchStatusException[Elasticsearch exception [type=x_content_parse_exception, reason=[1:617] [search_template] params doesn't support values of type: VALUE_NULL]]

Reference - https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-multi-search-template.html

i tried another way -

        request.setRequest(new SearchRequest("common_gisdata_2018q4"))
        request.setScriptType(ScriptType.INLINE)
        request.setScript("{" +
           " \"query\":{ \"geo_shape\":{\"ogr_geometry\":{\"shape\":{\"type\":\"circle\"," +
           " \"coordinates\":[55.333,25.269],\"radius\":\"1000.0m\"},\"relation\":\"intersects\"}}}," +
           " \"size\":1,\"sort\":[{\"_geo_distance\":{\"ogr_geometrypoint\":[[55.333,25.269]],\"distance_type\":" +
           " \"arc\",\"mode\":\"min\",\"order\":\"asc\",\"unit\":\"m\"}}],\"_source\":{\"includes\":[\"countryname_ol\"," +
           " \"emiratestateuno\",\"countryname_en\",\"areaname_en\",\"areaname_ol\",\"countryuno\",\"to_roadspeedlimit\"," +
           " \"emiratestatename_ol\",\"emiratestatename_en\",\"streetname_ol\",\"streetname_en\",\"from_roadspeedlimit\"]}}")

        println("script " + request.getScript )
        request.setSimulate(true)
        val renderResponse = client.searchTemplate(request, RequestOptions.DEFAULT)
        val source = renderResponse.getSource

        println("search start" + source.length()))
So I grilled more and catch the exception, it is giving as -

ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [GET], host [http://ip:9200], URI [_render/template], status line [HTTP/1.1 400 Bad Request]
Please suggest where parsing body is going wrong. This json works fine with Kibana or postman. Thanks

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
