### ISSUE TITLE
Unable to Fix Elasticsearch.yml file

### ISSUE THREAD

**Issue by nkuruvil** [elastic/elasticsearch#44861]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.90

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**:
I am attempting to run Filebeat alongside this Elasticsearch using docker run docker.elastic.co/beats/filebeat:7.2.0 setup -E setup.kibana.host=localhost:5601 -E output.elasticsearch.hosts=["localhost:9200"].  Both elasticsearch seem to run correctly when I used a browser to access them. For reference, I used docker run -d --name elasticsearch --net tasotest -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.2.0 to run elasticsearch.
I expect the function to run correctly

However, I instead receive the error "Exiting: Couldn't connect to any of the configured Elasticsearch hosts. Errors: [Error connection to Elasticsearch http://localhost:9200: Get http://localhost:9200: dial tcp [::1]:9200: connect: cannot assign requested address]." After searching for the solution online, I decided to modify the elasticsearch.yml file in the image so that host is set to 127.0.0.1 instead of 0.0.0.0.. I then learned that it is not possible to edit an image pulled from the docker hub. How do I repair this issue?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.
 1. Pull Filebeat image
 2. Pull Kibana image
 3. Pull estaticsearch image
 4. docker run -d --name kibana --net tasotest -p 5601:5601 kibana:7.2.0
 5. docker run -d --name elasticsearch --net tasotest -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.2.0
 6. docker run docker.elastic.co/beats/filebeat:7.2.0 setup -E setup.kibana.host=localhost:5601 -E output.elasticsearch.hosts=["localhost:9200"]

**Provide logs (if relevant)**:

**Comment by andyb-elastic** [comment]
If you're using a user defined network you need to use the container names as hostnames (e.g. `elasticsearch` instead of `localhost`) and put the filebeat container on the network as well

We have an active [forum](https://discuss.elastic.co/) for questions like this and prefer to use github for bug tracking, so if you have more questions please open a thread there. Thanks
