### ISSUE TITLE
[ML-DataFrame] NPE if no source index available / revisit empty set of source indexes

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#44906]
Originally at lease 1 source index was required, in case of a pattern new index could appear but it wasn't allowed to remove them. To support ILM however we decided to relax this constraint and allow the deletion of indexes, see https://github.com/elastic/elasticsearch/pull/44344.

As indexes could get deleted while indexing is running it could happen that searches fail if the index is closed at the moment we try to access it, that's why we had to switch to lenient source index expansion: https://github.com/elastic/elasticsearch/pull/44633

This had a bad side effect: sources indexes can run empty which breaks assumptions made in various places of the indexer, e.g. leading to a NPE:

```
[2019-07-25T06:49:38,936][WARN ][o.e.x.d.t.DataFrameTransformTask] [ml-qa-ubuntu-5] Data frame transform [dft_failed_missing_source_index_1564037378655] encountered an exception: 
java.lang.NullPointerException: null
    at org.elasticsearch.xpack.dataframe.transforms.DataFrameIndexer.doProcess(DataFrameIndexer.java:170) ~[?:?]
    at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexer.onSearchResponse(AsyncTwoPhaseIndexer.java:337) ~[?:?]
    at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
    at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

(the NPE happens as we try to access the non-existing `aggs` object in the response)

## Solution

 - ~if a concrete index is involved and the set of source indexes gets empty the transform should fail~
 - ~if the source is a pattern~ we allow source getting empty

=> always be lenient (whether or not source is a pattern)
=> require a non-empty source(index, not document-wise!) on `_preview` and `PUT`

## Dev Notes

 - check for empty source set / results:
   - at validation time if validation is not deferred do not allow an empty set, independent of pattern usage
   - at preview, independent of pattern usage
 - expect empty/null results, code needs to be hardened for that

## Discuss

=> a strict mode will be provided once we see a demand for it

Outdated:

The deletion of source indexes seem only relevant if source indexes are managed by ILM and for continuous data frames:

- should batch data frames be strict like before?
- even if continuous is used you might not want to "loose" data without notice, should we have a parameter for strictness (while lenient can be the default)?
  - or use `index` for non-ILM and `index_patterns` for ILM:

non-ILM:
```
"source": {
    "index": "kibana_sample_data_ecommerce",
    "query": {}
...
```

ILM: 
```
"source": {
    "index_patterns": ["events-*"],
    "query": {}
...
```

**Comment by benwtrent** [comment]
I am against separating out `index` and `index_patterns`. I think that adds unnecessary complexity. 

We should handle these types of responses in a sane way. Maybe allowing empty results, but auditing if we see empty results. It could be just fine that there are no concrete indices (for a period of time) that can be queried.


If we want to allow some sort of control to the user, we could also add support for index expansion flags in the `source` object, but that seems too granular. Possibly an `allow_no_indices` flag? Just spit balling.

**Comment by sophiec20** [comment]
I would also be against separating out `index` and `index_patterns`.

Good auditing is important here. As we are a platform and expect and want to see many varied use cases, we should not be trying to be too restrictive and controlling.

I'd like to see lenience for now - document as such and provide good auditing. Pending wider adoption and user feedback we can consider giving stricter controls.

**Comment by hendrikmuhs** [comment]
> Good auditing is important here. As we are a platform and expect and want to see many varied use cases, we should not be trying to be too restrictive and controlling.

Can you elaborate on "restrictions and controlling" - I do not get what we restrict or control.

> 
> I'd like to see lenience for now - document as such and provide good auditing. Pending wider adoption and user feedback we can consider giving stricter controls.

Can you elaborate on the batch data frames usecase:

- a user creates a dft "pivot_A" with source index A
- source index A gets deleted
- user starts "pivot_A"
- result: "pivot_A" does not create results as A was deleted

we used to error for this usecase, now we are not.

Even if we strictly validate:

- a user creates a dft "pivot_A" with source index A
- user starts "pivot_A" 
- user stops "pivot_A"
- source index A gets deleted
- user starts "pivot_A" again
- result: "pivot_A" has incomplete results as A was deleted

**Comment by sophiec20** [comment]
To elaborate / clarify / give more background (hopefully) ..

The user may use a single concrete index name, an array of concrete index names or a pattern (or possibly a combination). I would assume patterns to be the common usage. 

When the search runs and there are no results, then this would be due to either no documents matched or no indices matching. If we have results, these may have some (not all) missing concrete indices.

If no matching documents, then we retry the checkpoint. We think this is fairly likely in environments that don't change too much.

If one or more concrete indices are missing, then we may or may not find documents. In my opinion, we can be lenient here and this is worth an audit and continuing.

If no matching indices, then we can audit. I think we should retry (x times) as it may still be temporary.  

The above is from the point of view of runtime. At start, then perhaps we can fail faster if there are no matching indices.

**Comment by benwtrent** [comment]
1. We validate that indices exist on `_start`. If there are no underlying concrete source indices, we throw an error. If we don't that is bug.
2. If ALL indices go away, that is the same as there being "no more data". I think we should be lenient, and audit. Additionally, if indices are persistently gone, checkpointing, or whatever system is in place should see that there are no changes between checkpoints (i.e. the data has been gone for two checkpoints).

**Comment by hendrikmuhs** [comment]
I updated the top description for documentation purposes.
