### ISSUE TITLE
When Sort use _ignoring_unmapped_fields how search_after do?

### ISSUE THREAD

**Issue by luyuncheng** [elastic/elasticsearch#44904]
ES version6.3.2
1. when use sort [_ignoring_unmapped_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields),
**why there is ambiguous response in unmapped_type**
WHEN USE type:float/double
`
PUT  test_index/_search
{
  "sort": {
    "unknown_field": {
      "unmapped_type": "float/double"
    },
    "_id": {
      "order": "asc"
    }
  }
}
`
RESPNSE in sort
`
        "sort": [
          "Infinity",
          "xxxID"
        ]
`
WHEN USE type:byte/boolean/integer
`
PUT  test_index/_search
{
  "sort": {
    "unknown_field": {
      "unmapped_type": "byte/boolean/integer"
    },
    "_id": {
      "order": "asc"
    }
  }
}
`
RESPNSE in sort is INT64MAX
`
        "sort": [
          9223372036854775807,
          "xxxID"
        ]
`
WHEN USE type:string/keyword
`
PUT  test_index/_search
{
  "sort": {
    "unknown_field": {
      "unmapped_type": "string/keyword"
    },
    "_id": {
      "order": "asc"
    }
  }
}
`
RESPNSE in sort is null
`
        "sort": [
          null,
          "xxxID"
        ]
`

2. **when use unmapped_fields  how a search_after do to ignore these value**?

**Comment by andyb-elastic** [comment]
Hi, we have an active [forum](https://discuss.elastic.co/) for questions like this and prefer to use github for bug reports and feature requests. Do you mind opening a thread there? I'm going to close this issue, but if you think this behavior is a bug please let me know and I'll reopen. Thanks
