### ISSUE TITLE
Handle incorrect refresh interval on security indices

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#44934]
There are places in the security code (notably the token service) that perform updates with wait-for-refresh and depend on the refresh interval being short.

e.g. Kibana has a 30s timeout on token generation, and we may update more than 1 document (e.g during a refresh) so a refresh interval of 15s or more will inevitably cause problems (and does).

We should not leave this as a silent problem that needs to be diagnosed and resolved by the user. 
Options include:
- Detect when the refresh is > 10 seconds, and log warnings (least preferred because the log may not be read)
- Detect when the refresh is > 10 seconds and reset it (and log a warning)
- Detect when the refresh is > 10 seconds and automatically fail all affected API calls
- Force a refresh (perhaps only if the refresh interval is > 10 seconds)

I have no strong view on the solution, but we should do something to protect users from the problem.

**Comment by jasontedor** [comment]
Or we let system indices solve this and consider overriding the refresh interval a non-option here.

**Comment by jasontedor** [comment]
@jaymode I looked for the system indices project to link this issue to. Can you add this to your tracking when you have availability?

**Comment by tvernum** [comment]
System indices would be the preferred solution, but in the absense of any progress on that, I would like to have something that means we can at least detect when we run into this situation so that users aren't left guessing.  
It's happened frequently enough that I can spot the symptoms and guide people to a solution, but it's not something that's obvious if you haven't already encountered it before.

**Comment by tvernum** [comment]
We discussed this in the security team meeting and realised that setting an explicit refresh interval when we create the index would probably do the job that we need right now.
Our belief is that all the times when this problem occurs, it is due to a template that applies `*` and sets the refresh interval. We can avoid that by setting our own explicit interval, and not relying on the template value.
