### ISSUE TITLE
Update opensaml related dependencies

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#44947]
The shibboleth project doesn't push their artifacts to maven central [on purpose](https://wiki.shibboleth.net/confluence/display/DEV/Use+of+Maven+Central) and that means that the packages that are hosted there (or on jcenter) are a little stale (3.3.0 vs 3.4.3 as of writing this ) and managed by 3rd parties. The shibboleth project offers their own [maven repo](https://build.shibboleth.net/nexus/content/repositories/releases/) but offers no guarantees wrt to performance and availability. 

Now that we have an artifactory instance, we could cache the artifacts there so that we can upgrade to the latest version available.

**Comment by atorok** [comment]
We will still want to add the additional maven repo to  our build since our artifactory is not public.

**Comment by jkakavas** [comment]
> We will still want to add the additional maven repo to our build since our artifactory is not public.

Already did in #44972
