### ISSUE TITLE
Converting ES JSON to CSV (feature request)

### ISSUE THREAD

**Issue by G-K-Patel** [elastic/elasticsearch#44941]
Hi Elastic Team, 

In kibana, there is a feature that allows us to convert ES JSON Response to CSV files. Is it possible to have an API endpoint that returns a CSV response -- similar to the one calcuated by Kibana ? 

I think the logic for converting  ES-JSONs to CSV is already available in Kibana, maybe the same logic could be implemented in ES, thereby allowing us to directly get CSV output for different queries/aggregations made on ES. 

Thank you for considering my issue/request, and for the wonderful search engine of yours :)

**Comment by eskibars** [comment]
Hi @G-K-Patel.  We had a discussion about this today to consider the various places and ways that something like this could be used.  You mention Kibana's reporting, and looking at queries/aggregations results.  This got us thinking about the types of applications which may make use of or require this type of data output, and things like BI tools, spreadsheet systems, and the like are top of mind.  Elasticsearch has a [SQL](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-sql.html) layer including [SQL over REST which can output CSV, TSV, and other formats](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-format.html) and even an [ODBC driver](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-odbc.html) for direct connection between some of those tools.

In the case that someone is looking for more general conversion between JSON and CSV across a wider range of APIs than search/aggs, there are tools like [jq](https://stedolan.github.io/jq/) you can add to processing pipeline and which can arbitrarily format the data to your liking (including to CSV).  We think this is generally a better place to do any of this type of datatype conversion.

If we're missing additional details on your use case that aren't satisfied by the above, let us know, but for now, I'm going to close this.  Thank you for filing!
