### ISSUE TITLE
Document the Possibility and Solution for Leaking S3 Multi-Part Requests

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#44955]
We are using multi-part S3 requests in `org.elasticsearch.repositories.s3.S3BlobContainer#executeMultipartUpload` to upload larger blobs to the S3 snapshot repository.
A multi-part upload consists in [multiple requests to S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html).
In its current implementation, a failure in the middle of a multi-part upload could lead to a leaked multi-part upload that still costs storage.
This is not terribly likely as we do try to abort a multi-part upload if we run into an exception while processing any part of it, but possible in situations of flaky networking (where the abort requests than fails as well) or on outright node failures.

The documentation should advise users to [specify a bucket lifecycle policy to prevent this automatically](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config) when on AWS S3 and take other action to account for this possibility when using other S3 implementations.

cc @ywelsch ... I'll open a separate issue to handle implementation of an automatic cleanup for this shortly.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. Still relevant.
