### ISSUE TITLE
Improve accessibility for privileges and action unauthorized messages.

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#44984]
Elasticsearch reports the following:

`action [cluster:monitor/main] is unauthorized for user [example]`

Kibana User Management offers no privilege matching the action "cluster:monitor/main". I know these permissions map _somehow_ to Elasticsearch security privileges, but I can't find any documented definitive mapping of actions (cluster:monitor/main?) to privileges.

I can browse the Elasticsearch source code and find things like [this](https://github.com/elastic/elasticsearch/blob/b4bc6ac08fcf38e40880ca3d8b04fbb43d395b84/server/src/main/java/org/elasticsearch/action/main/MainAction.java#L26) but it doesn't necessarily help me on my journey.

There's something that looks like a hint deep within [ml](https://github.com/elastic/elasticsearch/blob/5fa36dad0b8503bef3d91173bb342da555445c26/x-pack/plugin/ml/qa/ml-with-security/roles.yml#L3-L5).

In general, providing an actionable response would be very helpful.

Some ideas:
* Instead of offering me `cluster:monitor/main`, offer me what privileges(s) are required.
* Or, provide a way to map privileges to actions, possibly in the documentation or via API.

**Comment by jordansissel** [comment]
My initial report confused privileges/actions/roles/etc... possibly highlighting the complexity in this area.

Short version, as a user, when I see: `action [cluster:monitor/main] is unauthorized for user [example]`, I want to know what privileges I need to grant in order to make this action successful. Ideally, just telling me the privilege required would be lovely :)

**Comment by jordansissel** [comment]
Examples:

* [`indices:admin/template/put` is `manage_index_templates`](https://discuss.elastic.co/t/indices-admin-template-put-is-a-cluster-action/67262)

**Comment by jkakavas** [comment]
@jordansissel I'll go ahead and close this in favor of the existing https://github.com/elastic/elasticsearch/issues/42166, we could move any details there but I think it pretty much covers your issue/ask
