### ISSUE TITLE
Optimize Encoding of Action Type in Network Protocol

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#44995]
Our current network protocol is pretty inefficient when it comes to encoding the "action" which tends to require upwards of 20 bytes in every message. This could be way optimized by having two nodes negotiate all the actions on handshake (which looks like it does only require exchanging the version for all core actions). 
Why not just encode the action as a 32bit `int`?
Since the core actions seem to fit into 9 bits (rough count only admittedly, but it seems it's fewer than 300), the remaining 23 bits in an `int` could just be made available to plugins like xpack to encode their actions. In the handshake between two nodes the nodes could simply exchange which relevant plugins they use and the offsets in the int for those plugins.
So e.g. if two nodes used two plugins, one (X) with 8 actions and another (Y) with 20 actions and ES core had 300 actions registered with the transport: 
* The initiator in a handshake could just sent the map `X: 1, Y: 9` to communicate that 301 is the first action in plugin X and e.g. 312 would be the 4th action in the action `int`.

I think there's a number of advantages to this:
* This would save ~ 16 bytes or more per message (action names tend to be 20 bytes(ish))
  * This could also be used for further optimizations. There isn't really much point in all the objects we create on the IO loop in `org.elasticsearch.transport.InboundMessage.Reader#deserialize` and the code around it
* We wouldn't have to read and instantiate a `String` for every message and look it up from a map to get the transport handler for a message. Instead we could just look up the actions from an array in the `TransportService`and not touch most of the bytes in a message on the IO loop or allocate anything before deciding what to do with a message.

Since all the action resolving happens on the IO thread, this might be worth it?

**Comment by DaveCTurner** [comment]
I'm all for reducing allocations and streamlining things where appropriate, but the compatibility (particularly BWC) implications of such a change to the wire format make me very uneasy. It's already reasonably tricky to pin down some serialisation issues, and having the on-the-wire format be dependent on some earlier handshake would make this much much worse.

> the two nodes could simply exchange

"simply" 😭 

I am pretty unconvinced that the 20-30 bytes of action on the wire has a significant performance impact. I'd like to suggest keeping the strings on the wire and looking for a way to process them without as many allocations.

**Comment by original-brownbear** [comment]
> "simply" :sob: 

I apologize :) 

> I am pretty unconvinced that the 20-30 bytes of action on the wire has a significant performance impact. 

In isolation this doesn't matter much probably, I agree. On the other hand, this would reduce the cost of ideas like application level keep-alives quite a bit.  Also, with compressed transport enabled, we currently have to decompress (at least a block of it which costs buffers etc.) the message on the IO thread-pool to figure out what where to handle the message (and if we may circuit break it!).
I think the value of this is more in the applications it enables without adding overhead.

Could also use this for proxy-type situations that were recently discussed, where having the ability to just put the type of a message in a fixed size header might be pretty neat?

Admittedly, the most of the possible applications could be enabled pretty cheaply by just moving the action string before the compressed section of the message (and yes we could 0-GC look up the transport action as well). 
Maybe it just seemed more aesthetically pleasing to do what most other protocols do (Kafka, Cassandra etc.) than to send clear text strings in our internal protocol. Fixed size request headers are just always nice I guess when trying to do some routing/prioritization  (looking at you replication requests).

**Comment by original-brownbear** [comment]
Closing here, we discussed it an decided the complication isn't worth the gain.
