### ISSUE TITLE
Incompatible Low Version

### ISSUE THREAD

**Issue by laijianbin** [elastic/elasticsearch#45000]
when java client jar use  Elasticsearch  6.8.0,Elastic Server use 6.6.1

![image](https://user-images.githubusercontent.com/26161527/62122531-7a992080-b2f8-11e9-8eb5-863f388db1f1.png)

Is there any soluation to resolve this problem?

**Comment by jimczi** [comment]
Hi @Neel-Gagan
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
