### ISSUE TITLE
Update HLRC to include WatchSourceBuilder classes

### ISSUE THREAD

**Issue by joshjanoski** [elastic/elasticsearch#45059]
**Describe the feature**:

The documentation page here: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.7/java-rest-high-x-pack-watcher-put-watch.html#java-rest-high-x-pack-watcher-put-watch says:

`// you can also use the WatchSourceBuilder from org.elasticsearch.plugin:x-pack-core to create a watch programmatically`

However, the WatchSourceBuilder class is not accessible within the HLRC. Since some prefer to use this method when creating their watches, is it possible to duplicate the classes needed for this functionality in the HLRC since the transport client is going away? Thanks for considering this!

**Comment by hub-cap** [comment]
We have decided to punt on these for now. We are focusing on making the API more generate-able friendly, and the users can just include that `x-pack-core` jar in their source so they can use the builder. Once the API is generated, we can also generate builders for these types of things, which will be included in HLRC. 

Basically there is a workaround that does not involve duplicating more code, and that is to just use the non OSS jar in your source.
