### ISSUE TITLE
SQL: Optimize resulting QueryDSL

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#45063]
While the SQL produced queries are correct, there are ways to improve it by making it more compact and less verbose.
One idea would be to balance between include and excludes (instead of specifying 9 out of 10 fields, only exclude the 10th).
Further more the JSON itself can be minimized by specifying fields as a list instead of individual objects.

Relates to #41856

**Comment by wchaparro** [comment]
Superceded by ES|QL
