### ISSUE TITLE
Add an ILM action to ensure a snapshot contains the index prior to being deleted

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#45067]
It's a common pattern with data to go through the lifecycle of an index, and then take a snapshot immediately prior to the index being deleted. It would be great if we could add functionality similar with this by combining parts of the SLM and ILM features in ES.

For example, if an index had a policy like:

```json
{
  "policy": {
    "phases": {
      "delete": {
        "min_age": "15d",
        "actions": {
          "snapshot": {
            "policy": "my-slm-policy"
          },
          "delete": {}
        }
      }
    }
  }
}
```

ILM would wait until the index entered the delete phase, it would then *wait* until a snapshot from the `my-slm-policy` SLM policy had been taken (it would *not* manually kick off a snapshot, since that could potentially create scores of unwanted snapshots), and then it would delete the index.

/cc @yaronp68 as you asked me to open an issue for this.

**Comment by JohanPeeters** [comment]
I absolutely agree that there is a need to ensure that an index has been archived before it is deleted. I can see this could be achieved by adding a 'snapshot' action to the delete phase to induce a wait on an SLM policy, as suggested. However, currently, snapshot lifecycle policies are very backup-oriented and do not support archiving terribly well imo - archiving usually needs to be triggered by the age of an index. As far as I can tell, there is no elegant way of ensuring that an SLM policy selects only indices of a certain age for its snapshot. If such capability was added, this proposal would suit my purposes perfectly.
