### ISSUE TITLE
Script object have compulsory parameter for user-define parameter for script execution

### ISSUE THREAD

**Issue by sagarpatel07** [elastic/elasticsearch#45128]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2

**Plugins installed**: No

**JVM version** (`java -version`): JDK 8

**OS version** (`uname -a` if on a Unix-like system): windows

**Description of the problem including expected versus actual behavior**:
I have tried to update ES document using script from java client, but problem is that i not need to pass any user-defined parameter for script as script is always increment count with 1. but java Script class constructor is expecting not null value for user-defined params to be bound for script execution.

Script countScript = new Script(ScriptType.STORED, null, "count-view", parameters);

As per my understanding expected behavior should be allowing parsing null value for user-define parameter.
Script countScript = new Script(ScriptType.STORED, null, "count-view", null);

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
