### ISSUE TITLE
issue found in readme.md

### ISSUE THREAD

**Issue by AsDeadAsADodo** [elastic/elasticsearch#45129]
![RZ49~39E 2NV`92J J6VPB0](https://user-images.githubusercontent.com/38915818/62352512-e7036200-b53a-11e9-83bf-d97857c6dde1.png)

the selected line above will cause http status code 400

**Comment by cbuescher** [comment]
@AsDeadAsADodo many thanks for pointing this out. It should be corrected on all branches >=6.8 now.
