### ISSUE TITLE
Clarify how many slices the _reindex uses by default

### ISSUE THREAD

**Issue by jgimenez** [elastic/elasticsearch#45121]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3

**Description of the problem including expected versus actual behavior**: Documentation does not indicate how many slices are used in `_reindex` API.

**Steps to reproduce**:

1. See `docs/reference/docs/reindex.asciidoc`
2. How many `slices` will be used if not specified? It's not clear, could be `1`, could be `auto`

**Comment by debadair** [comment]
[docs issue triage]

**Comment by debadair** [comment]
Closing as fixed. https://github.com/elastic/elasticsearch/pull/47483
