### ISSUE TITLE
docker下载elasticsearch失败

### ISSUE THREAD

**Issue by ljh0718** [elastic/elasticsearch#45125]
1.docker search elasticsearch
2.docker pull elasticsearch 
  出现了Trying to pull repository docker.io/library/elasticsearch ... 
  manifest for docker.io/elasticsearch:latest not found，找不到最新的
3.后执行带有版本号的docker pull elasticsearch:7.2.1
  出现了Trying to pull repository docker.io/library/elasticsearch ... 
  7.2.1: Pulling from docker.io/library/elasticsearch
  no supported platform found in manifest list，找不到这个

**Comment by jasontedor** [comment]
> docker pull elasticsearch
出现了Trying to pull repository docker.io/library/elasticsearch ...
manifest for docker.io/elasticsearch:latest not found，找不到最新的

For this, we don't support the `latest` tag.

> docker pull elasticsearch:7.2.1
出现了Trying to pull repository docker.io/library/elasticsearch ...
7.2.1: Pulling from docker.io/library/elasticsearch
no supported platform found in manifest list，找不到这个

This looks like a real issue. @jethr0null can you raise this with our Docker compatriots that manage these images? Note that this impacts all of our 7.2.1 images, so it's not that anything changed in the product builds that led to this, rather it seems something systematic happened on the creation of the library images.

**Comment by jethr0null** [comment]
Will do.

**Comment by jethr0null** [comment]
Running `docker pull elasticsearch:7.2.1` appears to be working now. 

@ljh0718 would you mind trying again and letting me know if you're still seeing the issue?

**Comment by jasontedor** [comment]
I’ve confirmed this is now working when it wasn’t before.

@ljh0718 If you still run into this problem, let us know and we will reopen this issue.
