### ISSUE TITLE
Add ability to cancel an ILM step

### ISSUE THREAD

**Issue by galindro** [elastic/elasticsearch#45143]
According [to this documentation section](https://www.elastic.co/guide/en/elasticsearch/reference/current/_updates_to_executing_policies.html), I can't change the version of the policy on the index because it's currently checking if it's ready to be rolled over. Unfortunately there's no way to force it to change it's policy version to be used. I see that even change it to use another policy, the older one's phase still must finish before it can use the new policy. This is a really annoying situation. For example: imagine if I set, by mistake, the max_size to 100 GB and the primary shards of the index attached to the policy never reach that size? 

One thing that I can do to workaround this limitation would be to re-index the data from the original index that’s still bound to the original version of the policy into one that either matches the naming pattern to have a corresponding template and policy automatically applied or manually assigning the policy before re-indexing. Therefore, the latest iteration of the policy should apply. 

But it is stills a boring situation. I agree that this isn't a large scale problem, but it can simply be resolved by adding an API action for cancel the current step or something to force the transition to the next policy step.

**Comment by dakrone** [comment]
Closing this as this is now possible with the work introduced in #50820
