### ISSUE TITLE
Propagate notices from vendored code

### ISSUE THREAD

**Issue by tomcallahan** [elastic/elasticsearch#45161]
Today the Elasticsearch build collects the `NOTICE` files for dependencies in jar form ([example](https://github.com/elastic/elasticsearch/blob/master/server/licenses/lucene-NOTICE.txt)) and propagates these to the `NOTICE.txt` file inside of the [distribution](https://www.elastic.co/downloads/elasticsearch).  This behavior is [required](http://www.apache.org/dev/licensing-howto.html#alv2-dep) for the Apache License 2.0, as well as some other licenses.

This propagation of `NOTICE` content is required whether we include a dependency as source (e.g. copying the source into our own codebase - "vendoring") or as a binary dependency (e.g., jar).  We do not currently have a mechanism in the build for the former.  While vendoring is not our usual mechanism of including dependencies, it [does happen](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/support/BCrypt.java) and we need to build a mechanism to comply with our OSS obligations here.

[Here is an example](https://github.com/elastic/kibana/blob/56cafd3a859c1a45c1d00b0ff9980b774df678d3/src/legacy/ui/public/styles/bootstrap/bootstrap_dark.less#L6-L11) of how Kibana identifies vendored code, and these bits are then propagated to Kibana's `NOTICE.txt`

**Comment by atorok** [comment]
@tomcallahan is this the only place where this happened ? Is there already a list or is it also the scope of the issue to identify thees ?

**Comment by tomcallahan** [comment]
@atorok I know this is not the only place.  I know of a small number of these but there is no list; we will need to find them

**Comment by mark-vieira** [comment]
@jasontedor I've collected all the source files I could find that is not using the Elasticsearch attributing license header. Please take a look to determine which are properly vendored, which are bogus, and which can go away.

https://docs.google.com/spreadsheets/d/1GOb81_NKjoiVUtUY9Sxybxtqr5DGYbnkCunIR_LQvSQ/edit#gid=0

FYI, this does not include our Guice fork living in https://github.com/elastic/elasticsearch/tree/master/server/src/main/java/org/elasticsearch/common/inject.
