### ISSUE TITLE
Disk-based shard allocation does not relocate shards unless path.data is absolute

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#45176]
If `path.data` is set to a relative path then `clusterInfo.getDataPath(shardRouting)` also returns a relative path. However, `getDiskUsage()` returns an absolute path. This mismatch effectively disables the disk-based shard allocator at this condition:

https://github.com/elastic/elasticsearch/blob/88c9ecb0b06c0c1951900e162687fdd8c66bd972/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L278

**Comment by jasontedor** [comment]
I think that we should be normalizing all the paths in the environment at startup. Adding the core/infra label too.
