### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]

### ISSUE THREAD

**Issue by liuxf1993** [elastic/elasticsearch#45170]
**when I try to run the elasticsearch, it starting java failed with [137]**:

**Elasticsearch version** (` elasticsearch-7.3.0`):

**Plugins installed**: []

**JVM version** (`java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)`):

**OS version** (`Linux VM_0_13_centos 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` ):

the error is like that
![4CC((EKG2)GHHOFGWNL2AO6](https://user-images.githubusercontent.com/25604624/62407474-a4e62900-b5eb-11e9-86bf-f4985e50bf74.png)

**Comment by jasontedor** [comment]
A JVM exit code of 137 means that the JVM was killed with `SIGKILL`. Something *outside* of Elasticsearch is killing the JVM that we start to determine the startup flags. This is almost surely your kernel OOM killer (check your system logs). I don't think there is an Elasticsearch issue. Free free to update this issue with additional information if you think that it is, we would be happy to re-open this issue.
