### ISSUE TITLE
Issue when using the "_rank_eval" api with ndcg score

### ISSUE THREAD

**Issue by jasondaicoder** [elastic/elasticsearch#45184]
Elasticsearch version: 7.2.0

Configuration: 1 shard, 3 nodes with same ES version

Description of the problem including expected versus actual behavior:

Actual: We have a scheduled job to call the "_rank_eval" api with a set of document id and rate to get the ndcg score. However when the rated document set doesn't change, different run sometimes returns different ndcg socre.

Expected: When the rated document set in the request doesn't change, the ndcg score should not change as well.

Can someone please help?

**Comment by cbuescher** [comment]
Hi @jasondaicoder,

Your expectations are right in that th ndcg score should only change if the ordering of any of the documents returned for one of the queries in your test set change. This might be the case for any of the following reasons:

* You indexed or deleted documents in the index that you are running the evaluation against. This might be documents seemingly unrelated to your queries, but every change to the index has the potential to change term frequencies and affect ranking consequently
* Your analysis chain slightly changed. This might be an undetected, involuntary change, e.g. some dictionary or file resources you are loading have changed or are configured slightly differently on two nodes in your cluster (synonym files are especially prone to this, if they are not exactly the same on all nodes, query result rankings can be different depending on which shard they hit)
* running some nodes on slightly different versions of ES, e.g. changes in Lucene similarity calculcations amongst different versions can change slightly

Maybe you can try to narrow the change in the overall score down to a particular requests "id", (the "details" section should show you a "metric_score" for each for each "request id"). Do all of those change when you compare the responses of the calls that have a different overall score? If only some of them changed, maybe you can narrow down what changed in the returned result order for those cases. Hope this helps as a start for investigation, let me know if you find anything that explains the changes in your case.

**Comment by jasondaicoder** [comment]
Hi @cbuescher ,

Thanks a lot on your reply, you raised some very good point which we used to review and check our environment. 

1. We have a scheduled indexing job which is scheduled to run on every a few hours, however the source data changes rarely, we would expect very minimum impact from this, but will try to narrow down if there were any changes
2. We don't use any external file for things like synonym, they are all inline settings
3. All data nodes are in same ES version
4. The ndcg score which changes on different run is actually per request id with specific "query string", we have list of terms which is passed as the "query string". We have discovered lots of them have the problem.

**Comment by jasondaicoder** [comment]
Hi @cbuescher,

Sorry forgot to mention that the changed ndcg score just swaps between two different values, it doesn’t change a lot.

**Comment by cbuescher** [comment]
>  ndcg score just swaps between two different values, it doesn’t change a lot

Thanks, could you share the values to see what "not a lot" means to you? I have a suspicion this could be rounding errors depending on the order in which the different search results arrive back and the overall score gets calculcated. Would you mind either sharing the whole response you get (both versions for the two slightly different values) or if you cannot do that, maybe just a list of the "metric_score" in the "details" section for each of the two varying overall scores?

**Comment by cbuescher** [comment]
Hi @jasondaicoder, just coming back to this. I'd still be interested to learn more about the magnitude of the fluctuations in scoring you are seeing and the circumstances under which this is happening (see my previous post). Let me know if you can share any more details, otherwise I'll close this issue in a bit but you can always reopen if you find a way so I can reproduce this issue or you can share more information.
