### ISSUE TITLE
Make docker environment variable parsing available in CLI tools

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#45223]
Our docker entry point script has special logic to convert environment variables into `-E` options when starting Elasticsearch.

https://github.com/elastic/elasticsearch/blob/v7.3.0/distribution/docker/src/docker/bin/docker-entrypoint.sh#L41-L62

However this logic is not available when executing CLI commands via `docker exec` (or other similar commands like `kubectl exec`, etc) which surprises people, and makes it difficult to run some commands within a container.

e.g. https://discuss.elastic.co/t/how-to-use-elasticsearch-setup-passwords-with-tls-and-selfsigned-certificates/193795/7

I definitely don't think we should enable this environment parsing by default, but I wonder if there's value in having some sort of option for this.

A couple of ideas:
1. Have a `--docker` (or `--parse-env`) option to our CLI tools (this could be handled in `elasticsearch-cli` or `elasticsearch-env`) 
2. Have a `elasticsearch-parse-env` script that generates `-E` options as output so that something like the below would work:
```
bin/elasticsearch-setup-passwords auto $(elasticsearch-parse-env)
```

I don't love any of this, but it's causing confusion right now so I think it's at least worth a discussion.

The CLI tools that I know of that make use of ES settings are _(there may be others, I didn't dig too deeply)_:

- elasticsearch-node (node roles) 
- elasticsearch-saml-metadata (realm settings)
- elasticsearch-setup-passwords (HTTP URL, HTTP SSL settings)
- elasticsearch-users (password hashing algorithm)

**Comment by dliappis** [comment]
Wanted to provide some initial feedback here.

The Docker entrypoint script is only used when the container starts and is not involved in subsequent operations like `docker exec`'ing commands. (see also [this SO comment](https://stackoverflow.com/questions/43723777/how-to-execute-the-entrypoint-of-a-docker-images-at-each-exec-command/43725278#comment74500786_43725278)).

We discussed on alternative in our weekly meeting which is to generalize the entrypoint script so that it can be used as a launcher for adhoc commands as well. Then it would be sufficient to run the following:

```
docker exec -ti <containername> docker-entrypoint.sh bin/elasticsearch-setup-passwords auto
```

**Comment by pugnascotia** [comment]
I had a quick look at some of the scripts. It looks like they all eventually source `elasticsearch-env` to tailor the environment, so if we moved the Docker-specific logic there, not only would we share it between the CLI tools, but there would be no need explicitly call an entrypoint i.e. `docker exec` would just work. Am I missing something, or does that sound reasonable?

**Comment by pugnascotia** [comment]
I suppose a downside of this would be that anyone running ES not in a container would need to watch their environment variables more closely, though the same applies to e.g. `JAVA_HOME` already.

**Comment by rjernst** [comment]
> anyone running ES not in a container would need to watch their environment variables

We definitely don't want that. Perhaps we could conditionally do this based on `ES_DISTRIBUTION_TYPE`, which is set to "docker" already for docker images?

**Comment by pugnascotia** [comment]
Oh that's interesting, I wasn't aware of that env var. @dliappis and I taked about it and concluded that the explicit entrypoint approach was more appropriate, but actually being able to tailor the env var handling while consolidating the code would be a +1 from me.

**Comment by dliappis** [comment]
I am possibly missing something; my question is even if we can do env var parsing in `elasticsearch-env` how would this help as the cli tools just source it but still need the actual parameters to get passed as `-E ...` style cli args? This is ultimately what the [entrypoint does](https://github.com/elastic/elasticsearch/blob/91b0ac3077c84d9ed3f43abed9ad2d0e46208e0b/distribution/docker/src/docker/bin/docker-entrypoint.sh#L90-L96), parsing env vars that seem related to elasticsearch and convert them to `-E ...` cli args.

**Comment by rjernst** [comment]
I believe the idea is we would move the conversion of the environment variabls into cli args into elasticsearch-env. We would need an env var that contains these converted settings which clis would then pass through. My suggestion was about making sure this only happens insider docker.

**Comment by dliappis** [comment]
We discussed this in a team meeting and iterated on top of the existing comments [here](https://github.com/elastic/elasticsearch/issues/45223#issuecomment-553493416) and [here](https://github.com/elastic/elasticsearch/issues/45223#issuecomment-552199176).

The preferred approach is to move the Elasticsearch specific env var parsing logic from the [entrypoint scipt](https://github.com/elastic/elasticsearch/blob/4ac79f900dd6e8be5489484e45a48ab41ab5e860/distribution/docker/src/docker/bin/docker-entrypoint.sh#L83-L96) to the [elasticsearch-env script](https://github.com/elastic/elasticsearch/blob/master/distribution/src/bin/elasticsearch-env). The following steps would be performed in `elasticsearch-env`:

1. if `ES_DISTRIBUTION_TYPE == docker`:
2. Assemble Elasticsearch specific env vars in an array, say `es_arg_array` (we currently do that in the [entrypoint.sh](https://github.com/elastic/elasticsearch/blob/4ac79f900dd6e8be5489484e45a48ab41ab5e860/distribution/docker/src/docker/bin/docker-entrypoint.sh#L83-L96))
3. Prepend the args from 2 in the bash argument array
    Technical detail on an example implementation: `set -- "${es_arg_array[@]}" "$@"`

As all tools (including the elasticsearch [startup script](https://github.com/elastic/elasticsearch/blob/master/distribution/src/bin/elasticsearch) itself) source `elasticsearch-env`, the problem described in this ticket would be solved.
  
One thing to be aware of is that there is a corresponding set of `elasticsearch-env` / `elasticsearch-cli` `elasticsearch` batch scripts for Windows, but as there is no Windows native Docker image currently, there is no immediate need to add this functionality that benefits only Docker images.

**Comment by pugnascotia** [comment]
Something isn't right here.

If I look at the docs for e.g. [elasticsearch-setup-passwords](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-passwords.html), they say that I can pass `-E` arguments. However, in reality I cannot:

```
$ docker pull docker.elastic.co/elasticsearch/elasticsearch:7.4.2
$ docker run -it docker.elastic.co/elasticsearch/elasticsearch:7.4.2 \
  elasticsearch-setup-passwords -Ediscovery.type=single-node auto
Sets the passwords for reserved users

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: E is not a recognized option
```

From a quick glance at the code, some CLIs extend `EnvironmentAwareCommand`, and some do not. It would appear that simply refactoring environment variable handling won't be enough to make everything "just work" under Docker. Given which, do we want to proceed with this work? There's no point doing it without changing the CLI code, because any tools that don't support `-E` options would be broken if there were any ES options in a container's environment.

**Comment by tvernum** [comment]
The `-E` needs to after the subcommand

```bin/elasticsearch-setup-passwords auto -Ehttp.host=this.is.not.valid
Exception in thread "main" java.lang.IllegalStateException: unable to determine default URL from settings, please use the -u option to explicitly provide the url
	at org.elasticsearch.xpack.security.authc.esnative.tool.CommandLineHttpClient.getDefaultURL(CommandLineHttpClient.java:161)
	at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool$SetupCommand.setupOptions(SetupPasswordTool.java:267)
	at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool$AutoSetup.execute(SetupPasswordTool.java:128)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool.main(SetupPasswordTool.java:107)
Caused by: java.net.UnknownHostException: this.is.not.valid: nodename nor servname provided, or not known
```

**Comment by pugnascotia** [comment]
Thanks @tvernum. I've raised #49612 to address this, I'd love your feedback.
