### ISSUE TITLE
How do i disqualify a parent document, based on a key value pair in a child doc in elasticsearch

### ISSUE THREAD

**Issue by yashtandon07** [elastic/elasticsearch#45232]
I am using parent child relationship in elasticsearch v7.3 suppose my parent document consist of 'users' also their are more than one child documents for each parent document. Now in all my child document i have with me a text field suppose 'name' with value 'raju' or 'yash' or etc. And my query is to get all the parent documents, whose child doc must not contain 'name' equals to 'raju'.

i.e if suppose we have 4 child doc in a parent doc and even if one child doc has name 'raju' then its parent doc must be disqualified and it must not be retrieved. hence i would request if anyone can help me with this.

                "has_child": {
                  "type": "child_1",
                  "query": [
                    {
                      "bool": {
                        "must_not": [
                          {
                            "match_phrase": {
                              "name": "raju"
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
As the negative weight concept has been removed then what is the way to acheive the solution to this problem. Any help would be highly appreciable. 

ES Version: 7.3
OS: ubuntu 18.04
GitHub reference: https://github.com/elastic/elasticsearch/issues/19166

**Comment by javanna** [comment]
Please could you ask your question in our forums at https://discuss.elastic.co/ ? We reserve github issues for feature request and confirmed bug reports.
