### ISSUE TITLE
Add vector functions to Sort Script Context

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45243]
See user filed problem [here](https://github.com/elastic/elasticsearch/pull/37947#issuecomment-518635775)

**Comment by jimczi** [comment]
The code looks good to me but I wonder if we should allow this. The query can already be used to sort by these functions if it is set as the only scoring clause so I am concerned that we add multiple ways to achieve the same. Is there a compelling reason to add this functionality other than consistency ?

**Comment by csenol** [comment]
@jimczi Vectors are encoded and these are the only functions which makes them possible to use in sorting context. 
I would not think vectors only for document/query embedding and using it for document scoring. Cosine similarity / dot products outputs can be used as an input to other sorting mechanism such as personalization, receny and so on with a combination of multi-staged sorting. So I think enabling them in script sorting is a reasonable Idea

**Comment by csenol** [comment]
@jimczi @mayya-sharipova Any updates on this issue ?

**Comment by mayya-sharipova** [comment]
@csenol Sorry for a late reply.  If you are interested to sort by the output of the vector functions, would it be possible for your use case to  use`script_score` query and sort results by `_score`:

```js
GET /my_index/_search
{
    "sort" : [
        "_score",
        "user"
    ],
    "query" : {
        "script_score" :  {...} // your vector function here
    }
}
```

We have internally redesigned vector functions which would make them difficult to be used in the sort context.

**Comment by csenol** [comment]
@mayya-sharipova Thanks for reply but I think this limits the usage of vectors almost into query/vector embeddings. There might be different sorting needs where relevancy score is not needed in the query context.

**Comment by mayya-sharipova** [comment]
@csenol 
>  relevancy score is not needed in the query context.

You don't need to include relevancy scores. Here `_score` is the output of the `script_score` which could be just the result of computation from vector functions.

**Comment by csenol** [comment]
@mayya-sharipova Let's say it is OK for vector functions not to be in score context, but we still miss decay functions in sort context. What about adding them ?

**Comment by mayya-sharipova** [comment]
@csenol A similar question here: is there a reason why you can't use sort by `_score`, where `_score` can include a result from decay functions together with any other calculations you need?

```js
GET /my_index/_search
{
    "sort" : [
        "_score",
        "user"
    ],
    "query" : {
        "script_score" :  {...} // your decay function here combined with any other calculations
    }
}
```

**Comment by csenol** [comment]
This is a bit patronizing how sorting should be used. In long term, you can even argue "sort" is useless and everything should be expressed with "script_score"

**Comment by csenol** [comment]
@mayya-sharipova I updated my cluster to ES 7.5.0 but I am still getting 
```
Caused by: java.lang.IllegalArgumentException: Unknown call [dotProduct] with [2] arguments.
	at org.elasticsearch.painless.PainlessScript$Script.compile(dotProduct(params.query_embed, doc['my_vector']):1) ~[?:?]
	at org.elasticsearch.painless.node.ECallLocal.analyze(ECallLocal.java:125) ~[?:?]
	at org.elasticsearch.painless.node.SExpression.analyze(SExpression.java:62) ~[?:?]
	at org.elasticsearch.painless.node.SClass.analyze(SClass.java:205) ~[?:?]
	at org.elasticsearch.painless.node.SClass.analyze(SClass.java:162) ~[?:?]
	at org.elasticsearch.painless.Compiler.compile(Compiler.java:215) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:356) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:352) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:389) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:352) ~[?:?]
```

**Comment by mayya-sharipova** [comment]
@csenol Can you please post your whole query?  Please also consider that we still don't allow to use vector functions in sort. They can be used only inside script_score. `dotProduct(params.query_embed, doc['my_vector'])` is the correct syntax for 7.5

**Comment by csenol** [comment]
Yes I was using it in sort.
```
 { "query" : {"exists" : { "field" : "my_vector" }},
    "sort" : {
        "_script" : {
            "type" : "number",
            "script" : {
                "lang": "painless",
                "source": "dotProduct(params.query_embed, doc['my_vector'])",
                "params" : {
                    "query_embed" : [1,2,3]
                }
            },
            "order" : "asc"
        }
    }
}
   ```


In the release notes of (7.5.0 )[https://www.elastic.co/guide/en/elasticsearch/reference/7.5/release-notes-7.5.0.html]

>Ranking
Add vector functions to the Sort Script Context #45244 (issue: #45243)


What does this mean then? Could you maybe clarify?

**Comment by mayya-sharipova** [comment]
Sorry, this was misbehaving of our script for release notes. The PR was closed without merging. You can't use vector functions in `sort`.

**Comment by csenol** [comment]
That is pretty disappointing. Could you please fix at least release notes, so that I am not the only one who trapped into this.

**Comment by mayya-sharipova** [comment]
@csenol Thanks for letting us know, we will [fix the release notes.](https://github.com/elastic/elasticsearch/pull/52660).

I am closing this issue, as we are not going to implement this feature for now.
