### ISSUE TITLE
[Data Frame] Allow to pivot around _index

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#45275]
It would be great if data frames would allow to pivot (group by) `_index`. This would be similar to running a `terms` aggregation on the `_index` field.

Use cases could include showing different kinds of data per Index, such as min/max timestamp, number of documents, etc.

**Comment by hendrikmuhs** [comment]
@fkelbert 

I just tried this and it worked for me. Can you describe what is not working for you?
Or is it about the UI not showing you this option?

I used the dev console:

```
POST _transform/_preview
{
  "source": {
    "index": "kibana_sample_data_ecommerce"
  }
  , "pivot": {
    "group_by": {
      "index": {"terms": {
        "field": "_index"
      }}
    },
    "aggregations": {
      "max_price": {
        "max": {
          "field": "taxful_total_price"
        }
      }
    }
  }
}
```

(Sorry for the late reply)

**Comment by fkelbert** [comment]
@hendrikmuhs 

Just double checked. The UI does not allow my to create a Transform with `terms(_index)`:

![image](https://user-images.githubusercontent.com/714592/71664457-f2102780-2d50-11ea-9d9d-c792c9cb693e.png)

**Comment by hendrikmuhs** [comment]
Closing this in favor of https://github.com/elastic/kibana/issues/53887

The feature is supported in the back-end, but not exposed in the front-end (UI), but even in the UI you can directly edit using the "Advanced pivot editor".
