### ISSUE TITLE
When index announced word server freezes

### ISSUE THREAD

**Issue by oxozle** [elastic/elasticsearch#45273]
**Elasticsearch version**
7.3

**Plugins installed**: []

**OS version** (`uname -a` if on a Unix-like system):
Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

Index request with body freeze indexing operation.
```
  {
    "basic": {
      "description": "announced"
    }
  }
```

Word exactly **announced**. If change word to another it will be ok. I think something in token analyse engine broken.

**Steps to reproduce**:

 1. Create index with mapping (basic: object, description: text)
 2. Try to index something contains word **announced**
 3. No response for minutes

**Comment by javanna** [comment]
Can you please post a complete recreation including your mappings, and your index request?

**Comment by oxozle** [comment]
1. Create index 

![image](https://user-images.githubusercontent.com/3500727/62695835-c4ac9100-b9df-11e9-9c67-1d1665040db0.png)

2. Working example

![image](https://user-images.githubusercontent.com/3500727/62695902-fd4c6a80-b9df-11e9-8225-512da4525f94.png)

3. Example with **announced** word. Executing for ages

![image](https://user-images.githubusercontent.com/3500727/62695953-16551b80-b9e0-11e9-85cb-fd5aea1857c0.png)

![image](https://user-images.githubusercontent.com/3500727/62695981-253bce00-b9e0-11e9-900e-c3d4bbafd7aa.png)

**Comment by javanna** [comment]
heya, 
what http client are you using to send those requests? Have you tried using curl from command line? Asking because I tried to reproduce this but I did not manage.

**Comment by markharwood** [comment]
No further feedback received. @oxozle  if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
