### ISSUE TITLE
I am not able to tokenise dot(.) elements 

### ISSUE THREAD

**Issue by chetanveratech** [elastic/elasticsearch#45271]
When I try to tokenize X.Y separately it takes the only X.Y token, But for all other special characters, tokenizer is working fine.
I have mentioned the problem correctly here.

https://stackoverflow.com/questions/57358427/while-searching-a-string-i-cannot-retrieve-strings-which-consist-of-a-symbol

please check it if anyone can help, I will be thankful

**Comment by javanna** [comment]
Please post your question in our forms at discuss.elastic.co. We reserve github issues for verified bug reports and feature requests.
