### ISSUE TITLE
Enhance logging for slow query to reflect memory overhead

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#45278]
### Problem Description
Slow logging doesn't indicate the memory overhead for the query. There could be a possible GC pause on the node running the query which could also take time. So essentially if the query itself was expensive is not known. Can the below factor also be logged. 

1. Big Arrays
2. Aggregation buckets
3. Response size

**Comment by Bukhtawar** [comment]
Hey @romseygeek , if the proposal makes sense, then do you think it can be prioritized. I can try taking a stab at this.

**Comment by jimczi** [comment]
The circuit breaker (and big arrays in general) we have checks the total memory used by requests but it does not have the granularity to check memory overhead per query. The slow log is also executed before the serialization of the response so the size is not known. We could log the number of hits/buckets we have in the response but I wonder how useful it would be since this information can be easily derived from the query.

**Comment by Bukhtawar** [comment]
>The circuit breaker (and big arrays in general) we have checks the total memory used by requests but it does not have the granularity to check memory overhead per query

Do you think logging the overhead for big arrays at a per request(only for the time/memory consuming ones)  makes sense as a part of slow logs or maybe some query memory overhead logs

>We could log the number of hits/buckets we have in the response but I wonder how useful it would be since this information can be easily derived from the query.

I think `total_hits` is already present but having info on the buckets or for that matter any factor contributing significantly to memory overhead definitely helps to root cause issues like frequent/long GCs at a point in time as buckets can change based on the dataset(varying over time).


The uber idea is any offending query can cause a surge in the memory pressure and are hard to identify.

**Comment by javanna** [comment]
We are not currently planning to make this change, closing.
