### ISSUE TITLE
ES requires me to specify the type of data that I do not want to index.

### ISSUE THREAD

**Issue by greenx** [elastic/elasticsearch#45291]
ES requires me to specify the type of data that I do not want to index.

I want to save some data just in case (Suddenly, later come in handy).
I need them to not be indexed and not involved in the search.
If this data is later needed, I will get it from _source.
I tried to add mapping, but ES swears:

```
curl -s -H 'content-type: application/json; charset=UTF-8' "http://localhost:9205/test123/_mapping/searchtype?pretty" -XPUT  -d'{"properties" : {"name2":{"index":false}}}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "No type specified for field [name2]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "No type specified for field [name2]"
  },
  "status" : 400
}
```
Why? This data is in the original JSON.
ES 6.8.

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by greenx** [comment]
@romseygeek 
It seems to me that this is not quite a user issue.
https://discuss.elastic.co/t/es-requires-me-to-specify-the-type-of-data-that-i-do-not-want-to-index/194404/3?u=greenx
