### ISSUE TITLE
BWC matrix builds failing due to missing task

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#45311]
We have a few builds failing because there is a CI job configured for the BWC version but no corresponding build task exists. Seems to be specific to 5.1.x and 5.2.x.

https://gradle-enterprise.elastic.co/s/nc3gavszz2aca
https://gradle-enterprise.elastic.co/s/a6vpnx7sbyx4i

**Comment by mark-vieira** [comment]
@atorok these failures still seem to be happening. Any idea why some BWC test tasks would simply be missing?

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=non_verification&failures.failureMessage=Task%20*%20not%20found%20in%20root%20project%20%27general-purpose%27.%20Some%20candidates%20are:%20%27v5.0.0%23bwcTest%27,%20%27v5.0.1%23bwcTest%27,%20%27v5.0.2%23bwcTest%27,%20%27v5.3.1%23bwcTest%27,%20%27v5.3.2%23bwcTest%27,%20%27v5.3.3%23bwcTest%27,%20%27v5.4.0%23bwcTest%27,%20%27v5.4.1%23bwcTest%27,%20%27v5.4.2%23bwcTest%27,%20%27v5.4.3%23bwcTest%27,%20%27v5.5.0%23bwcTest%27,%20%27v5.5.1%23bwcTest%27,%20%27v5.5.2%23bwcTest%27,%20%27v5.5.3%23bwcTest%27,%20%27v5.6.0%23bwcTest%27,%20%27v5.6.1%23bwcTest%27,%20%27v5.6.10%23bwcTest%27,%20%27v5.6.11%23bwcTest%27,%20%27v5.6.12%23bwcTest%27,%20%27v5.6.13%23bwcTest%27,%20%27v5.6.14%23bwcTest%27,%20%27v5.6.15%23bwcTest%27,%20%27v5.6.16%23bwcTest%27,%20%27v5.6.2%23bwcTest%27,%20%27v5.6.3%23bwcTest%27,%20%27v5.6.4%23bwcTest%27,%20%27v5.6.5%23bwcTest%27,%20%27v5.6.6%23bwcTest%27,%20%27v5.6.7%23bwcTest%27,%20%27v5.6.8%23bwcTest%27,%20%27v5.6.9%23bwcTest%27,%20%27v6.0.0%23bwcTest%27,%20%27v6.0.1%23bwcTest%27,%20%27v6.1.0%23bwcTest%27,%20%27v6.1.1%23bwcTest%27,%20%27v6.1.2%23bwcTest%27,%20%27v6.1.3%23bwcTest%27,%20%27v6.1.4%23bwcTest%27,%20%27v6.2.0%23bwcTest%27,%20%27v6.2.1%23bwcTest%27,%20%27v6.2.2%23bwcTest%27,%20%27v6.2.3%23bwcTest%27,%20%27v6.2.4%23bwcTest%27,%20%27v6.3.0%23bwcTest%27,%20%27v6.3.1%23bwcTest%27,%20%27v6.3.2%23bwcTest%27,%20%27v6.4.0%23bwcTest%27,%20%27v6.4.1%23bwcTest%27,%20%27v6.4.2%23bwcTest%27,%20%27v6.4.3%23bwcTest%27,%20%27v6.%E2%80%A6&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&performance.metric=avoidanceSavings,avoidanceSavingsRemoteBuildCache&performance.offset=530&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1565801912846&search.startTimeMin=1565715512846&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-420

**Comment by droberts195** [comment]
Pasting this to make this issue easy to search for for people doing test triage:

```
Task 'v5.2.2#bwcTest' not found in root project 'general-purpose'. Some candidates are: 'v5.0.0#bwcTest', 'v5.0.1#bwcTest', 'v5.0.2#bwcTest', 'v5.3.1#bwcTest', 'v5.3.2#bwcTest', 'v5.3.3#bwcTest', 'v5.4.0#bwcTest', 'v5.4.1#bwcTest', 'v5.4.2#bwcTest', 'v5.4.3#bwcTest', 'v5.5.0#bwcTest', 'v5.5.1#bwcTest', 'v5.5.2#bwcTest', 'v5.5.3#bwcTest', 'v5.6.0#bwcTest', 'v5.6.1#bwcTest', 'v5.6.10#bwcTest', 'v5.6.11#bwcTest', 'v5.6.12#bwcTest', 'v5.6.13#bwcTest', 'v5.6.14#bwcTest', 'v5.6.15#bwcTest', 'v5.6.16#bwcTest', 'v5.6.2#bwcTest', 'v5.6.3#bwcTest', 'v5.6.4#bwcTest', 'v5.6.5#bwcTest', 'v5.6.6#bwcTest', 'v5.6.7#bwcTest', 'v5.6.8#bwcTest', 'v5.6.9#bwcTest', 'v6.0.0#bwcTest', 'v6.0.1#bwcTest', 'v6.1.0#bwcTest', 'v6.1.1#bwcTest', 'v6.1.2#bwcTest', 'v6.1.3#bwcTest', 'v6.1.4#bwcTest', 'v6.2.0#bwcTest', 'v6.2.1#bwcTest', 'v6.2.2#bwcTest', 'v6.2.3#bwcTest', 'v6.2.4#bwcTest', 'v6.3.0#bwcTest', 'v6.3.1#bwcTest', 'v6.3.2#bwcTest', 'v6.4.0#bwcTest', 'v6.4.1#bwcTest', 'v6.4.2#bwcTest', 'v6.4.3#bwcTest', 'v6.5.0#bwcTest', 'v6.5.1#bwcTest', 'v6.5.2#bwcTest', 'v6.5.3#bwcTest', 'v6.5.4#bwcTest', 'v6.6.0#bwcTest', 'v6.6.1#bwcTest', 'v6.6.2#bwcTest', 'v6.7.0#bwcTest', 'v6.7.1#bwcTest', 'v6.7.2#bwcTest', 'v6.8.0#bwcTest', 'v6.8.1#bwcTest', 'v6.8.2#bwcTest'.
```

**Comment by atorok** [comment]
```
  // the BWC version under test will fail to start in this situation so we skip creating the test task
  if (project.cgroupsV2Enabled && version.isVersionBrokenIfCgroupsV2Enabled()) {
    continue
  }
```
We'll have to pin this jobs to a worker that doesn't have cgroups v2
