### ISSUE TITLE
[DOCS] Add examples in watchers definitions that uses throttle_period_in_millis

### ISSUE THREAD

**Issue by laraMorenoIgle** [elastic/elasticsearch#45346]
**Description of the problem including expected versus actual behavior**:

When defining an action in a watcher you can configure a *throttle period*. 

In the documentation all the examples use `throttle_period` parameter, but you could use `throttle_period_in_millis` instead, since, as per the [code](https://github.com/elastic/elasticsearch/blob/v7.3.0/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchParser.java#L158-L167) both parameters are accepted. 
However, `throttle_period_in_millis` parameter is mentioned neither in the examples related to watchers in the Elasticsearch documentation nor anywhere in the docs. 

*Examples in the doc using **throttle_period***
https://www.elastic.co/guide/en/elastic-stack-overview/7.2/actions-slack.html
https://www.elastic.co/guide/en/elastic-stack-overview/7.1/actions.html#actions-ack-throttle

*Example in the discussion forum using **throttle_period_in_millis***
https://discuss.elastic.co/t/how-to-set-a-time-range-in-the-watcher/93679/4

 It would be good to include examples in the documentation using  **throttle_period_in_millis** too.

**Comment by jrodewig** [comment]
Thanks for opening this issue @laraMorenoIgle.

I opened #45607 to document the `throttle_period_in_millis` parameter. However, I'm hesitant to update any of the existing examples.

It seems that `throttle_period` is likely a better default for most users. But I'm not that experienced with Watcher and its use cases. If you feel strongly that `throttle_period_in_millis` should be included in an example, I can look at maybe adding a new one.
