### ISSUE TITLE
get mapping from index return 'object' type property without 'type' field

### ISSUE THREAD

**Issue by outshow** [elastic/elasticsearch#45367]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2

**Plugins installed**: [jcseg]

**JVM version** (`java -version`):default

**OS version** (`uname -a` if on a Unix-like system): centos 6

**Description of the problem including expected versus actual behavior**: get mapping from index return 'object' type property without 'type' field

**Steps to reproduce**:

 1. create an index with object type field
 2.  insert any data to th index
 3. use api to get mapping from the index
 4. object type field return without 'type' field

definition mapping 
`"identity": {
                "type": "object"
            },`

get mapping return
` "identity":{
                    "properties":{
                        "coser":{
                            "type":"long"
                        }
                    }
                },`

it should be
`"identity":{
		    "type": "object",
                    "properties":{
                        "coser":{
                            "type":"long"
                        }
                    }
                },`

**Comment by astefan** [comment]
@outshow this is not an issue. The `object` type of field is the default type when the type is not explicitly specified. Thus, a mapped field without an explicit type is an `object` type of field. And our documentation shows examples of mappings where the type is missing and the field is considered to be of the default type `object`: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/object.html

**Comment by outshow** [comment]
@astefan Thank you for explaining.
