### ISSUE TITLE
Embedded JDK is not used

### ISSUE THREAD

**Issue by alexhass** [elastic/elasticsearch#45372]
Per https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html#jvm-version the bundled version should be used if JAVA_HOME is not set. This is **not** true on Windows. It still finds an installed Java 8 via registry and used this outdated version.

Additionally it is not possible to run several ES versions in parallel with their own bundled JDK. I need to run 5.6 and 7.3 in parallel for example - but like to use JRE8 with ES5.6 and the bundle one with ES7.3.

Whats wrong here.

**Comment by astefan** [comment]
@alexhass Can you please check you do not already have a JAVA_HOME set? Something like echo %JAVA_HOME% just before running elasticsearch.bat.

**Comment by alexhass** [comment]
It was 100% not set. I have also rebooted and checked again and it was still using an Oracle JRE8 161 that was installed.

**Comment by rjernst** [comment]
How did you install Elasticsearch? The windows zip file only looks at the environment variable JAVA_HOME, but the Windows installer (msi) looks at several places in the registry for java.

**Comment by alexhass** [comment]
I always use MSI setups.

**Comment by rjernst** [comment]
Thanks @alexhass. This is a known issue in the windows installer. I've created https://github.com/elastic/windows-installers/issues/330 to address that. Since it is not an issue with Elasticsearch directly, I hope you don't mind that I close this issue.
