### ISSUE TITLE
Release notes: exclude closed PRs with version labels?

### ISSUE THREAD

**Issue by pcsanwald** [elastic/elasticsearch#45377]
The release notes generation script doesn't include filtering for PRs that are closed, as opposed to merged. This is a problem, because it means that the person generating the release notes needs to somehow check every PR to ensure it's actually merged, and not closed, or, alternatively, the release notes could contain an unmerged PR.

This means that a command like this:

```
docker run \
  --rm \
  -it \
  -v $HOME/.elastic/github.token:/root/.github_auth \
  -v $PWD:/elasticsearch \
  docker.elastic.co/elasticsearch-infra/dev-tools:latest \
  bash -c "/elasticsearch/dev-tools/es_release_notes.pl v7.2.0 > /elasticsearch/docs/reference/release-notes/7.2.0.asciidoc"
```

generates a release notes file that contains these closed, unmerged pull requests:

https://github.com/elastic/elasticsearch/pull/41488
https://github.com/elastic/elasticsearch/pull/38504
https://github.com/elastic/elasticsearch/pull/40047
https://github.com/elastic/elasticsearch/pull/41799
https://github.com/elastic/elasticsearch/pull/43910 

which were all closed, as opposed to being merged. To avoid this, we could update the script to filter by `is:merged` or similar. That would leave us with PRs that were closed, but did have a version label, which could be less than ideal; because those version labels are then "incorrect" _if_ we want to use the version label as a single source of truth. Is there a reason why we don't filter by `is:merged` today? As an alternative solution, could we handle this in the relabel step, which could remove version labels for closed PRs?

**Comment by pugnascotia** [comment]
We don't use that script, we can't close this.
