### ISSUE TITLE
Mapping not applied to new index after rollover

### ISSUE THREAD

**Issue by Incara** [elastic/elasticsearch#45399]
**Version 7.2.0**

**Plugins installed**: [none]

**OS version**: Linux 4.1.12-124.28.6.el7uek.x86_64

**Description of the problem including expected versus actual behavior**:

When calling _rollover with a supplied mapping, it is not applied to the new index. Issue first noticed in the Rest High Level Client, but present when directly making requests. Expected behavior is that mappings would be applied. Settings are correctly applied.

**Steps to reproduce**:

 1. PUT test-index

 2. POST _aliases
```javascript
{
  "actions": [
    {
      "add": {
        "index": "test-index",
        "alias": "test-alias"
      }
    }
  ]
}
```

 3. POST test-alias/_rollover/new-test-index
```javascript
{
  "settings": {
    "index": {
      "mapping": {
        "coerce": "false"
      }
    }
  },
  "mappings": {
    "dynamic": "false",
    "properties": {
      "someProperty": {
        "properties": {
          "value": {
            "type": "keyword"
          }
        }
      }
    }
  },
  "aliases": {},
  "conditions": {
    "max_docs": 0
  }
}
```
**Note: If I use the same `settings` and `mapping` content above to manually PUT an index, it works correctly**

4. GET test-alias/_settings, validate setting present

5. GET test-alias/_mappings
```javascript
{
  "new-test-index": {
   "mappings": { }
  }
}
```

**Workaround**: Manually apply the mappings to the index after rollover happens.

**Comment by jtibshirani** [comment]
Thank you @Incara for reporting this issue! I just opened #45411 to address it.

I also wanted to mention another workaround -- it is common to define an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/indices-templates.html) that matches the indices. When rolling over to a new index, mappings from matching index templates will be automatically applied.
