### ISSUE TITLE
ML Data Frame Analytics regression model tests should not validate algorithm

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#45412]
The ML regression model is still going through a large experimental phase. We should not be testing the results of the algorithm directly, just that it ran and gave us values.

Example failure

https://scans.gradle.com/s/zfiwscvwtiodi

**Comment by dimitris-athanasiou** [comment]
I have muted the test until we are certain it's stable. This is also tracked by https://github.com/elastic/elasticsearch/issues/45425 so I'm closing this one.
