### ISSUE TITLE
OutOfMemory with high Index Writer Memory Usage

### ISSUE THREAD

**Issue by Elias481** [elastic/elasticsearch#45427]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Plugins installed**: []

**JVM version** (`java -version`): e.g. 11.0.1+13

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
After some time of indexing (no other load on the single-node cluster) using bulk-api, the index writer memory usage raises straight up and an OOM happens.
The Heap is not really big as elasticsearch is used as backend for an application with not too much data. But I assume there wouldn't be a problem if the index writer memory would stick at around 200MB out of the 2GB and not raise towards 1GB at some point in time.
What does the metric index_writer_memory_in_bytes mean and how to limit this particular region or calculate the max. needed bytes for this area to avoid crashes?
Also: why is the circuit breaker not accounting for this huge portion of heap memory? (We currently need to let the circuit breaker run in `use_real_memory: false` mode as it looks it counts uncollected garbage as used memory which shouldn't cause requests to fail but trigger a stop-the-world full-gc before to free some memory, so I cannot say whether circuit breaker would help agains OOM in these cases shich could be the case...)

**Steps to reproduce**:

 1. Start ES
 2. Start bulk-indexing some documents in small chunks
 3. Wait some time till OOM cause ES to stop

**Provide logs (if relevant)**:

**Comment by Elias481** [comment]
I just found some other facts:
At the same time the Index Writer memory usage climbs to about 1,4GBs (out of 2GB) the Version Map memory raises in same relation (to a max of about 50MB, thought).
There are these well known throtelling because segment writing can't keep up messages shortly when the memory usage starts to raise.
This time I managed to kill the bul-loading process before OOM actually happened (Full-GC was still looping) and the memory usage went down after some time.
The throtelling ended messages appeared.
Anyway ES did not recover, despite no error messages in log the CPU usage kept to be at about 1 core all the time and a clean shutdown was not possible (after many minutes of waiting). The monitoring view was not updating anymore.

I will now try with index refresh intervall disables and debug logging for indices, but anyway expected behaviour is to be able to set some hard limit at which elasticsearch throttles requests (not deny but just keep requester on hold till buffers are available). So this is a still a bug (at least a documentation bug).

**Comment by original-brownbear** [comment]
@Elias481 the fact that the circuit does not account for GC was discussed in https://github.com/elastic/elasticsearch/issues/40115 and we decided not to do anything about this for now.

There is ongoing discussion about throttling network reads to get smoother behavior in https://github.com/elastic/elasticsearch/issues/44484 in some situations when running a multi-node cluster (see last point).

I think your best solution here is to account for the circuit breaker behavior in your client and make it retry (and maybe throttle) when running into the circuit breaker as intended by the functionality.

> behaviour is to be able to set some hard limit at which elasticsearch throttles requests (not deny but just keep requester on hold till buffers are available)

The problem with this idea is that it only really makes sense in a single node cluster doesn't it?
If you have multiple nodes that you can send your bulk request to, running into `503`s is likely a lot more useful than the node throttling network reads for REST requests. Without those 503s and throttled reads in their place on the REST layer, the latency behavior of ES becomes a lot less predictable and load balancing REST requests across multiple ES nodes becomes much harder doesn't it?

**Comment by Elias481** [comment]
Hmm I have to think about. Currently my problem is the software that was made by our development and gave us to put it in production.
They do not cope with the circuit-breaker (no retries..) and I have to do initial bulk-load.
So what is making the memory usage going straight up at certain point in time? Is it just that throtteling? Do I have a chance to calculate needed memory for successfull initial bulk-import?

So if the circuit breaker would account for the "Index Writer Memory Usage" I would be happy to go to our dev team with this. (We can use it in current mode then so let it stop at 60% usage for all accounted memeory).
Otherwise it copes down to GC tuning (initiation occupancy) and more heap because of such behaviour, at least that is what I expect from our dev.

**Comment by original-brownbear** [comment]
@Elias481  

Unfortunately, this appears to be a user question at this point and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/\). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Let me try a few quick answers here though to get you started:

> So what is making the memory usage going straight up at certain point in time? Is it just that throtteling? Do I have a chance to calculate needed memory for successfull initial bulk-import?

I don't think there is any viable way of calculating the memory use up front. There's just too many variables going into this like the performance of your underlying storage, CPU performance, GC settings and many many more => Your best bet is to implement retry logic into your application in my opinion instead of trying to work around a lack of it by turning off ES safety features. Trying to guess the amount of load that the system can handle seems like a significantly more complex undertaking than simply implementing retries to me.

**Comment by Elias481** [comment]
@original-brownbear I now read linked tickets. There was no discussion about whether andy why the indexing heap cannot be accounted in circuit breaker (besides the real-mem cb that has the drawback of tripping just because the GC has not finished housekeeping). So for systems with predicatble workload the old cb looks much better - if it would account for such large portions of heap like used for the indexing buffer and one could tune the threshold to account for all the things not caught in circuit breaker but are more predictable as the suddenly extremle raising indexing buffers which also stay high.
So if we would use the real-mem cb we could not ditinguish between just "immediate" retry for letting the GC do it's work or wait some more time because there is really memory pressure because of the disk throtteling issue or such things.
