### ISSUE TITLE
Frequent failures of RunDataFrameAnalyticsIT.testRegressionWithNumericFeatureAndFewDocuments

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#45425]
This test has failed a number of times now in the last couple of days. It doesn't seem to reproduce locally for me though.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'test:%20%22testRegressionWithNumericFeatureAndFewDocuments%22'),sort:!(time,desc))

**Comment by dimitris-athanasiou** [comment]
I have muted the test until we stabilise behaviour.
