### ISSUE TITLE
add a field comment to _search endpoint

### ISSUE THREAD

**Issue by granierbernard** [elastic/elasticsearch#45436]
**Describe the feature**: Our system is compound by a web application and Elasticsearch, a business request on the web application generates several request to Elasticsearch. In order to investigate issues and performances troubles, it would be great to link Elasticsearch requests together and to business requests. For that a comment field in search woul be helpfull.

It could be an array to be able to set an uuid to link Elasticsearch requests together and some keywords to link Elasticsearch requests to a business request.

**Comment by granierbernard** [comment]
When I say "link", it means to sort or aggregate traces or packet beat data in Kibana.

**Comment by jimczi** [comment]
You can already add an [`x-opaque-id`](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/tasks.html#_identifying_running_tasks) in the header of your request that will be propagated to slow logs and search tasks:
https://github.com/elastic/elasticsearch/issues/31521
https://github.com/elastic/elasticsearch/pull/31539
Is it what you're looking for @granierbernard ?

**Comment by granierbernard** [comment]
I understood that if the X-Opaque-Id is set by the REST client, it will be sent back in the response. That's could do the job. 
Thanks for the information and apologiez for this false issue?.

**Comment by granierbernard** [comment]
I understood that the header variable X-Opaque-Id could be set and will sent back in the answer. That's do the job. 
Thanks for your answer and apologize for this false issue.
