### ISSUE TITLE
Elasticsearch service over HTTPS channel (Linux OS)

### ISSUE THREAD

**Issue by manoj4321** [elastic/elasticsearch#45445]
Hello,
I don't know if this is the correct place to post this issue........
I am able to get elasticsearch service over HTTPS channel, but in windows operating system by following the tutorial given over elasticsearch home site. Now I want to implement the same in Ubuntu. Kindly, someone guide me how should I go about it. Thanks.

**Comment by martijnvg** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
