### ISSUE TITLE
[DOCS] Painless - Context Examples document type 

### ISSUE THREAD

**Issue by gemaliano** [elastic/elasticsearch#45458]
Context examples is using type which is deprecated in version 7. 
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-context-examples.html
This is in seats.json data (step 1) and in index seat data (step 5)

When executing example in version 7.3 we get:
```Rejecting mapping update to [seats] as the final mapping would have more than 1 type: [_doc, seat]"}}},```

**Comment by jdconrad** [comment]
Fixed by #45631
