### ISSUE TITLE
[Elasticsearch Docker] Multiple GC selected for elasticsearch-cli from v7.2.1

### ISSUE THREAD

**Issue by maramos-elastic** [elastic/elasticsearch#45467]
**GitHub discuss**:
https://github.com/elastic/elasticsearch/issues/45223

**Elasticsearch version** (`bin/elasticsearch --version`): 
7.2.1 (Docker official image)

**JVM version** (`java -version`): 
openjdk version "12.0.1" 2019-04-16

**OS version** (`uname -a` if on a Unix-like system):
Linux 57438d3ba5c3 4.9.184-linuxkit

**Description of the problem including expected versus actual behavior**:
On version `7.2.1` (docker official image) isn't possible to run some commands from `bin/elasticsearch-cli` when we're selecting a different GC (through `ES_JAVA_OPTS`), for example, `elasticsearch-keystore`.

**Steps to reproduce**:
- To reproduce the error:
```
docker run -ti --rm --name fail docker.elastic.co/elasticsearch/elasticsearch:7.2.1 bash -c 'ES_JAVA_OPTS="-XX:+UseG1GC" bin/elasticsearch-keystore'
Error occurred during initialization of VM
Multiple garbage collectors selected
```
- If use the same command on version `7.2.0`, success:
```
docker run -ti --rm --name success docker.elastic.co/elasticsearch/elasticsearch:7.2.0 bash -c 'ES_JAVA_OPTS="-XX:+UseG1GC" bin/elasticsearch-keystore'
A tool for managing settings stored in the elasticsearch keystore
...
```

The same behavior is reproducible on version `7.3.0`.

**Comment by rjernst** [comment]
It looks like this is due to https://github.com/elastic/elasticsearch/pull/44545. 

@maramos-elastic Why do you need to run with a different garbage collector for cli commands? These are tiny, short lived jvms.

/cc @jasontedor

**Comment by jasontedor** [comment]
There’s no need to set a garbage collector for the CLI commands. If you still feel you do, you need to add flags to disable the garbage collector we think the CLI tools should use. That would be `-XX:-UseSerialGC`.

**Comment by maramos-elastic** [comment]
Hello @jasontedor, @rjernst 

As you pointed, it's not necessary to run the CLI using a different GC, but if we start docker using `ES_JAVA_OPTS` with a different GC for Elasticsearch we can't execute the CLI on the same environment.
Disabling it explicitly on environment work as expected.
Thank you for your considerations.
