### ISSUE TITLE
[CI] Old (5.3.1) X-Pack zip not available in artifactory

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#45479]
BWC builds are failing against very old versions because the 5.3.1 x-pack zip cannot be found in artifactory (and it looks like artifactory is just caching from jcenter, but the zip is not there either)

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc/BWC_VERSION=5.3.1,nodes=general-purpose/22/
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+default-distro+bwc/BWC_VERSION=5.3.1,nodes=general-purpose/18/

```
01:46:03 * What went wrong:
01:46:03 Execution failed for task ':x-pack:qa:full-cluster-restart:with-system-key:v5.3.1#oldClusterTestCluster#node0.copyBwcPlugins'.
01:46:03 > Could not resolve all files for configuration ':x-pack:qa:full-cluster-restart:with-system-key:v5.3.1#oldClusterTestCluster_elasticsearchBwcPlugins'.
01:46:03    > Could not find x-pack.zip (org.elasticsearch.plugin:x-pack:5.3.1).
01:46:03      Searched in the following locations:
01:46:03          https://artifactory.elstc.co/artifactory/gradle-release/org/elasticsearch/plugin/x-pack/5.3.1/x-pack-5.3.1.zip
01:46:03 
01:46:03 * Try:
```

**Comment by rjernst** [comment]
We reconfigured the artifactory virtual repo to first go to Elastic's own maven repo where these artifacts exist. The 5.3.1 bwc job is now passing.
