### ISSUE TITLE
Question - Why elasticsearch has separate JNA library

### ISSUE THREAD

**Issue by hirik** [elastic/elasticsearch#45488]
Hi,

Why do we maintain separate JNA library for elasticsearch? 
Found this repo in maven dependency : (https://mvnrepository.com/artifact/org.elasticsearch/jna)

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
