### ISSUE TITLE
[DOCS] Watcher condition context example - fielddata or keyword field on play field

### ISSUE THREAD

**Issue by gemaliano** [elastic/elasticsearch#45491]
**Elasticsearch version** : 7.3.0

**Description of the problem including expected versus actual behavior**:
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-watcher-condition-context.html

Watcher example fails to execute due to play field is not keyword and fielddata is false by default.

**Steps to reproduce**:

 1. Execute context examples 
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-context-examples.html
 2. Execute watch from example 1
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-watcher-condition-context.html

**Provide logs**:
```"Fielddata is disabled on text fields by default. Set fielddata=true on [play] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."```

**Comment by jdconrad** [comment]
@hub-cap ping

**Comment by hub-cap** [comment]
Hi, Ive discussed with @jdconrad and he needs to first do #45492 and then he can update the field in the example to `  "play":     { "type": "keyword"    },`, so the docs will be more usable for these examples.

**Comment by jdconrad** [comment]
Fix is committed.
