### ISSUE TITLE
[DOCS] Context example seat data to include true in sold field

### ISSUE THREAD

**Issue by gemaliano** [elastic/elasticsearch#45492]
**Elasticsearch version**: 7.3.0

**Description of the problem including expected versus actual behavior**:
Seat data context example contains all sold field with false value.
In watcher example we use  ```"term": { "sold": "true"}```
Would be good to have sample data covering cases to get output from watcher. Or some explanation if we need to change watcher or data. What output we should get when running watcher. 

**Steps to reproduce**:
 1. Execute context examples
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-context-examples.html
(Step 1. Download the seat data --> seats.json)
 2. Execute watch from example 1
https://www.elastic.co/guide/en/elasticsearch/painless/7.3/painless-watcher-condition-context.html

**Comment by hub-cap** [comment]
Hi, while I was updating the docs for watcher I updated the play file w/ some randomness and I have provided to @jdconrad. He should be doing the work to update the docs.

**Comment by jdconrad** [comment]
Fix is committed.
