### ISSUE TITLE
SQL: Improve SQL tests by checking response headers for warning messages

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#45498]
Elasticsearch is adding deprecation warning messages as a header in the REST response, following https://github.com/elastic/elasticsearch/issues/43922.

We should improve SQL's tests by checking for `warning` header existence in all of the requests we make in tests.

Related to https://github.com/elastic/elasticsearch/issues/43922.

**Comment by wchaparro** [comment]
Superceded by ES|QL
