### ISSUE TITLE
Reload Search Analyzers does not work with synonym_graph

### ISSUE THREAD

**Issue by slumx** [elastic/elasticsearch#45505]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3

**Plugins installed**: [ICU]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Win10

**Description of the problem including expected versus actual behavior**:
as described here https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html it should be possible to reload `synonym` and `synonym_graph` filters. Running the example provided it does as expected with `synonym` filter but if we change it to `synonym_graph` nothing is reloaded

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. run the example at https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html
 2. verify that the response states that the `synonym` filter was reloaded
 3. delete the index and change the `synonym` filter to `synonym_graph` filter and run the example again
4. run `_reload_search_analyzers`. See that nothing was reloaded

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
Thanks for reporting @slumx. This bug is already fixed by https://github.com/elastic/elasticsearch/pull/45135 so I hope you don't mind if I close this issue.

**Comment by slumx** [comment]
Sorry, didn't see it was already reported. Thanks for the fix
