### ISSUE TITLE
deb package containing JDK 12 won't install unless you already have JDK 11+

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#45555]
**Elasticsearch version** (`bin/elasticsearch --version`):
8.0.0-5db0569b .. elasticsearch-8.0.0-SNAPSHOT-amd64.deb

**Plugins installed**: []

**JVM version** (`java -version`): 8 (but the deb package contains 12)

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04
Linux vagrant 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:  Since we've bundled a JDK in this deb package I wouldn't expect the `dpkg -i` to fail because the locally installed version of Java is less than 11.
https://www.elastic.co/guide/en/elasticsearch/reference/master/deb.html

**Steps to reproduce**: 
1. use Ubuntu with Java 8
2. try to install `dpkg -i elasticsearch-8.0.0-SNAPSHOT-amd64.deb`
3. fails with;
```
Unpacking elasticsearch (8.0.0~SNAPSHOT) ...
Setting up elasticsearch (8.0.0~SNAPSHOT) ...
the minimum required Java version is 11; your Java version from [/usr/lib/jvm/java-8-oracle/jre] does not meet this requirement
Processing triggers for systemd (229-4ubuntu7) ...
dpkg: error processing package elasticsearch (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 elasticsearch
```

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by LeeDr** [comment]
@jasontedor explained that the problem is that I had JAVA_HOME set in my environment and that causes the package install scripts to use that.  It would be nice to make the exact issue clear either in the installer output or the docs or both.

The error from the package install is;
`the minimum required Java version is 11; your Java version from [/usr/lib/jvm/java-8-oracle/jre] does not meet this requirement`

Maybe it could be changed to;
`the minimum required Java version is 11; your JAVA_HOME does not meet this requirement; unset JAVA_HOME to use the included JDK`

This page; https://www.elastic.co/guide/en/elasticsearch/reference/master/deb.html
says;
`Elasticsearch includes a bundled version of OpenJDK from the JDK maintainers (GPLv2+CE). To use your own version of Java, see the JVM version requirements`

Maybe could say something like;
`Elasticsearch includes a bundled version of OpenJDK from the JDK maintainers (GPLv2+CE). To use your own version of Java, set your JAVA_HOME and see the JVM version requirements`

or;
`Elasticsearch includes a bundled version of OpenJDK from the JDK maintainers (GPLv2+CE) which is used unless you have JAVA_HOME set. To use your own version of Java, see the JVM version requirements`

**Comment by jasontedor** [comment]
The error from the package install is explicit about which Java we are using, to help with problems where a user thinks that their `JAVA_HOME` is set to one value and Elasticsearch is seeing another value. I don't think saying "unset JAVA_HOME to use the included JDK" is helpful to a user that is not trying to use the bundled JDK.

Regarding the documentation, `see the JVM version requirements` is a [link](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/setup.html#jvm-version) that explains how to use your own Java so adding `set your JAVA_HOME` only duplicates information on that page (which is linked to from elsewhere).
