### ISSUE TITLE
Missing aggregations field in response

### ISSUE THREAD

**Issue by julioolvr** [elastic/elasticsearch#45559]
This bug report originally comes from the forums [here](https://discuss.elastic.co/t/missing-aggregations-field-in-response/193189)

---

**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.2

**Plugins installed**: `discovery-ec2` and `search-guard` 25.0

**JVM version** (`java -version`):

```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system): We use the official docker image for 6.7.2 so OS and JVM is whatever comes in the image

**Description of the problem including expected versus actual behavior**:

We have a query that includes an aggregation sections like the following:

```json
"aggs": {
    "key": {
        "terms": {
            "field": "request_key"
        }
    }
}
```

<details><summary>Full query</summary>

```json
{
    "size": 0,
    "query": {
        "bool": {
            "filter": [
                {
                    "range": {
                        "target_status_code": {
                            "gte": 400
                        }
                    }
                },
                {
                    "range": {
                        "timestamp": {
                            "gte": "2019-07-29T03:47:01",
                            "lte": "2019-07-29T03:49:01"
                        }
                    }
                }
            ]
        }
    },
    "aggs": {
        "key": {
            "terms": {
                "field": "request_key"
            }
        }
    }
}
```

</details>

And, sometimes, won't include the `aggregations` part in the response. An actual sample response:

```json
{
    "took": 203,
    "timed_out": false,
    "_shards": {
        "total": 255,
        "successful": 254,
        "skipped": 254,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": 0,
        "hits": []
    }
}
```

And the expected results (which is also a response to the same query, it often works as expected):

```json
{
  "took" : 158,
  "timed_out" : false,
  "_shards" : {
    "total" : 255,
    "successful" : 255,
    "skipped" : 254,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "key" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ ]
    }
  }
}
```

**Steps to reproduce**:

This is executed periodically and very often, and it only happened a couple of times (as in two or three times out of hundreds of executions) so sadly I don't have exact steps to reproduce.

---

To follow up the discussion here, answering @polyfractal's question from the forum here:

> Do you use a timeout on your searches?

We don't in the query itself, and we haven't changed any default configuration regarding timeouts in the server.

> Was this going through cross-cluster-search?

No

> Anything notable in the logs, like an error or a shard being unavailable or something?

From our devops team: "not sure, we didn't see alerts for yellow status, so shard being unavailable was probably not the case"

> You said it only happened twice, so I'm assuming you don't have a more minimal example that we can use to replicate it? Figured it couldn't hurt to ask

Sadly no, but if there's anything else I can provide or that you want me to try let me know.

**Comment by julioolvr** [comment]
@polyfractal you noted in the forums the difference between the successful and non-successful responses, where the wrong one says:

```json
    "_shards": {
        "total": 255,
        "successful": 254,
        "skipped": 254,
        "failed": 0
    },
```

and the one with the correct response contains

```json
  "_shards" : {
    "total" : 255,
    "successful" : 255,
    "skipped" : 254,
    "failed" : 0
  },
```

Which is interesting - it seems in both cases 254 shards are skipped which makes sense based on what you said about one shard always being queries in order to generate the proper response. But in the incorrect case, even though there's 254 successful shards and 255 total shards, there are no failed shards? I wonder where did the missing one go.

**Comment by not-napoleon** [comment]
I'm closing this - the version is unsupported, and I without data to reproduce it I can't do anything.  If you can send a script that reproduced this (including mappings and data that cause the bug) on a current version, I'd be happy to look into it then.
