### ISSUE TITLE
RepositoryURLClientYamlTestSuiteIT fails on  master - intake part 1

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45560]
This is probably not related to tests themselves, but how they are executed/infrastructure. We have the following tests failed; the test failures don't reproduce for me:

./gradlew :modules:repository-url:integTestRunner --tests "org.elasticsearch.repositories.url.RepositoryURLClientYamlTestSuiteIT.test {yaml=repository_url/10_basic/Restore with repository-url using http://}" \
  -Dtests.seed=857DDFAB28A152F9 \
  -Dtests.security.manager=true \
  -Dtests.locale=bg-BG \
  -Dtests.timezone=America/Port-au-Prince \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/755/console
Build Scans: https://gradle-enterprise.elastic.co/s/tskpxia547s5k

Fails with: 
"type" : "snapshot_restore_exception",
"reason" : "[repository-url:snapshot-one/OGdCpDX4TdS7V1AP6e0htw] cannot restore index [docs] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"

----
./gradlew :modules:repository-url:integTestRunner --tests "org.elasticsearch.repositories.url.RepositoryURLClientYamlTestSuiteIT.test {yaml=repository_url/10_basic/Get a non existing snapshot}" \
  -Dtests.seed=32E44CD114650972 \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-Hant-TW \
  -Dtests.timezone=America/St_Lucia \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/754/console
Build Scans:  https://gradle-enterprise.elastic.co/s/kfqr6tcpcya2q

Fails with: "concurrent_snapshot_execution_exception"

**Comment by original-brownbear** [comment]
Very interesting, this seems very similar to #45336 ... looking into what's going on here

**Comment by original-brownbear** [comment]
It seems to me this has the same underlying cause as https://github.com/elastic/elasticsearch/issues/45605 ... we fail to delete the index because we can't get a hold of the shard lock and things go downhill from there.

**Comment by mayya-sharipova** [comment]
@original-brownbear Thanks for the investigation. I will close this issue, as I think you are right underlying cause is investigated in #45605
