### ISSUE TITLE
Build tools testkit builds should use artifactory server

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#45568]
It looks like we have instances where our build tools integration tests aren't using the ES artifactory server configured by the CI init script.

https://gradle-enterprise.elastic.co/s/moa74rf46k2oi/tests/orjfcz7hu5lqq-fzbt5s3nffypy

I suspect this is because testkit is using an isolated gradle user home. I think we can explicitly configure this otherwise.

**Comment by mark-vieira** [comment]
Right now we have removed the usage of our internal due to instability and lack of high availability (see discussions [here](https://github.com/elastic/infra/issues/14421)). Right now this is effectively blocked on us sorting that out.

**Comment by atorok** [comment]
It won't make a difference for sure, but we'll also get artifactory back for sure, so we could make sure that the configuration is kept in the testkit tests in the mean time.

**Comment by mark-vieira** [comment]
I'm closing this for now since we aren't going to do anything about this until we have a HA solution for artifactory and at that point we sould probably switch to using that across the board in CI.
