### ISSUE TITLE
`intervals` queries fail percolator term extraction

### ISSUE THREAD

**Issue by OrionNebula** [elastic/elasticsearch#45639]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0 (deb)

**Plugins installed**: [ discovery-ec2, analysis-icu ]

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Linux 4.4.0-1085-aws #96-Ubuntu SMP Tue Jun 11 09:08:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Percolator queries that contain an `intervals` clause fail term extraction.

Expected: Intervals queries will be supported by percolator term extraction and pre-filtering.
Actual: Intervals queries fail term extraction and are always considered for percolation.

**Steps to reproduce**:

 1. Create an index containing a `percolator` field (name doesn't matter, but I used "query")
 2. Index a query containing an `intervals` clause
 3. Search for `{ "term": { "query.extraction_result": "failed" } }`

**Comment by jimczi** [comment]
@romseygeek can you take a look ?
