### ISSUE TITLE
Elastic SQL Limit 1000 by default?

### ISSUE THREAD

**Issue by pigaz5201314** [elastic/elasticsearch#45645]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
7.2.0
**Plugins installed**: []
[X-Pack] Elasticsearch SQL 
**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
centos7.2
**Description of the problem including expected versus actual behavior**:
jdk-11.0.3
**Steps to reproduce**:
Querry from index by runing the following sql:
POST _sql?format=txt
{
  "query":"select    id as id ,    timestamp as sampleTimeStr    from  \"app_task_201908_7\"  where  1=1     ORDER BY  sampleTimeStr desc limit 2000"
}
only 1000 row returned. 
      id       |     sampleTimeStr      
---------------+------------------------
67977          |2019-08-16T02:21:26.488Z
67972          |2019-08-16T02:17:25.085Z
67969          |2019-08-16T02:16:29.004Z
67963          |2019-08-16T02:13:25.126Z
67958          |2019-08-16T02:12:44.415Z
67933          |2019-08-16T02:09:25.111Z
......

it seems i cannot go beyond limit 1000. Is there a way to increase the limit beyond 1000?
could anyone help me? Thanks..

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/\). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/\) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
