### ISSUE TITLE
Account for Index Writer Cache in Circuit breaker

### ISSUE THREAD

**Issue by Elias481** [elastic/elasticsearch#45648]
**Describe the feature**: Account for Index Writer Cache in Circuit breaker

For some use cases it is essential to run elasticsearch with a limited amount of heap memory and nodes. In this case it is not really nice to use the use_real_memory mode of circuit breaker as that causes many unnecessary breaker trips / denial of requests in the time the garbage collector is running.
The old mode would work very nice in that cases but when the disks get slow because of temporary high utilization the Writer Cache can grow much above the configured threshold within short time. The circuit breaker does not see this memory at all but the memory is calculated very often anyway. The CB should really get this memory usage into its pools to be able to react in such case.

**Comment by danielmitterdorfer** [comment]
> it is essential to run elasticsearch with a limited amount of heap memory

Can you please elaborate a bit on that? What amount of heap memory do you have in mind?

> when the disks get slow because of temporary high utilization the Writer Cache can grow much above the configured threshold within short time. 

Do you mean the configured indexing buffer via the setting [`indices.memory.index_buffer_size`](https://www.elastic.co/guide/en/elasticsearch/reference/current/indexing-buffer.html)? This setting is used by a component that will track index buffer usage and will then start throttling and force-refreshing the largest shards when the total indexing buffer size and the bytes being written to disk reach the [threshold](https://github.com/elastic/elasticsearch/blob/2bcfe1a2d82d52d7d0b74071610875cdaf418f76/server/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java#L335) (50% above the configured buffer size).

> The circuit breaker does not see this memory at all

Considering you're talking about the old circuit breaker, this is correct. However, the maximum overhead of the indexing buffer is known upfront (determined by `indices.memory.index_buffer_size`) so you could instead lower the [limit of the parent circuit breaker](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html#parent-circuit-breaker) accordingly via `indices.breaker.total.limit` to account for that.

**Comment by Elias481** [comment]
>> it is essential to run elasticsearch with a limited amount of heap memory

> Can you please elaborate a bit on that? What amount of heap memory do you have in mind?

It shall be used as some backend service for very specific queries. We saw that normally 1GB is very sufficent if not more then we need.


>> when the disks get slow because of temporary high utilization the Writer Cache can grow much above the configured threshold within short time.

> Do you mean the configured indexing buffer via the setting indices.memory.index_buffer_size? This setting is used by a component that will track index buffer usage and will then start throttling and force-refreshing the largest shards when the total indexing buffer size and the bytes being written to disk reach the threshold (50% above the configured buffer size).

Yes I mean indices.memory.index_buffer_size. We can see in normal working conditions the buffers are written to disk as soon as threshold is exceeded.
But what You mean with "start throtteling"? Is it the message we see in the logs that the disks cannot keep up / starting throtelling? We see this indeeded every time the error happens. But I doubt that it throttels on the correct side (it needs to throttle input of new indexing requests but for me it looks more like throtteling the output side / the speed of disk-writes which is counter productive of course). Or does it only looks like and the "force-refreshing the largest shards" causes additional disk-load? I don't know what force-refreshing means in this scope. At all it looks like elasticsearch writes to disk more slowly then disks would handle normally after the "disk cannot keep up / throtteling" message which would be broken (but I did not investigate code nor did exact maesurements to be absolutely certain - I just wondering why after the message it mostly leads to a OOM and almostr never recovers which I would expect as outcome of throttelling),


>> The circuit breaker does not see this memory at all

> Considering you're talking about the old circuit breaker, this is correct. However, the maximum overhead of the indexing buffer is known upfront (determined by indices.memory.index_buffer_size) so you could instead lower the limit of the parent circuit breaker accordingly via indices.breaker.total.limit to account for that.

That is true but the new "circuit breaker" is not very nice at least if You do not want to spend much extra RAM to have the GC running early enough to not constantly trip the breaker. The old breaker considers real memory usage (or at least tries to do) opposed to current heap usage which includes all the garbage a java programm produces which is more friendly to configure. So it would be nice if the old cb would include the used index_buffer_size (or the throtteling which is announced in the message would effectively throttle on the input side).

**Comment by danielmitterdorfer** [comment]
> It shall be used as some backend service for very specific queries. We saw that normally 1GB is very sufficent if not more then we need.

Thanks for the clarification. We regularly run our [nightly benchmarks](https://elasticsearch-benchmarks.elastic.co/) with 1GB of heap size (that is the out-of-the-box default of Elasticsearch) and I don't recall ever having problems there but it may be the case that you have a different workload that triggers this behavior. We did run also experiments on smaller heaps of 512MB and even 256MB a while ago. While I don't have the details handy, I also don't recall running into problems with those configurations.

> what You mean with "start throtteling"?

Oh, I was - unintentionally - not very clear about that. If you observe the logs you should see a message along the lines of:

```
now throttling indexing for shard [[myindex][0]]: segment writing can't keep up
```

Under the hood, a lock ensures that [only one thread can enter a region in `InternalEngine`](https://github.com/elastic/elasticsearch/blob/a340795a0fb58456649593888e2de956393c1eea/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L853-L854). That look is replaced with a no-op once it stops throttling again. So the idea of this solution is indeed to reduce the rate at which new documents are added to an index.

> Or does it only looks like and the "force-refreshing the largest shards" causes additional disk-load?

What I meant by the term "force-refreshing" is that it will ensure [the indexing buffer contents are written to disk](https://github.com/elastic/elasticsearch/blob/2bcfe1a2d82d52d7d0b74071610875cdaf418f76/server/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java#L374-L385) and it will start with the shard that takes up most of that buffer. That will mean additional load for the disk at this point, yes.

>>> The circuit breaker does not see this memory at all

>> Considering you're talking about the old circuit breaker, this is correct. However, the maximum overhead of the indexing buffer is known upfront (determined by indices.memory.index_buffer_size) so you could instead lower the limit of the parent circuit breaker accordingly via indices.breaker.total.limit to account for that.

> That is true but the new "circuit breaker" is not very nice at least if You do not want to spend much extra RAM to have the GC running early enough to not constantly trip the breaker.

What garbage collector are you using? Do you use the out-of-the-box default or did you explicitly configure a different one (e.g. G1GC)? I am asking because we have recently improved G1GC's configuration to work better with the real-memory circuit breaker (see https://github.com/elastic/elasticsearch/pull/46169). As an aside, if you want to run Elasticsearch with little heap you should probably look into JVM configuration anyway. If the garbage collector is triggered too late you might run into full GCs (which are completely stop-the-world) so triggering a (concurrent) GC cycle *could* make sense (but to decide that I suggest testing a scenario and analyzing the GC logs).

> The old breaker considers real memory usage (or at least tries to do) opposed to current heap usage which includes all the garbage a java programm produces which is more friendly to configure.

I think this is a misunderstanding: Only the real memory circuit breaker (new in 7.0.0) asks the JVM for the current heap usage (and this is what I'd consider "real"). The previous circuit breaker only considers the amount of memory that is *explicitly* reserved within Elasticsearch (e.g. by the network layer or other parts of the application). If that component actually needs more memory to complete an operation than what was reserved, the parent circuit breaker wouldn't know. In that respect the new circuit breaker is admittedly "harsher" but takes into account also memory that has never been reserved. However, if a concurrent GC cycle is ongoing for a long time, the JVM cannot report the memory that is being reclaimed as "free" and thus the real memory circuit breaker is also a bit more conservative in that respect.

> So it would be nice if the old cb would include the used index_buffer_size (or the throtteling which is announced in the message would effectively throttle on the input side).

As the index buffer has a upper bound that is well-known upfront it should be possible to tweak the parent circuit breaker's limit? I think adding a new circuit breaker for an amount of memory that is well-known upfront seems more complex than changing the value. Semi-related, we're also discussing to throttle request on the network layer in https://github.com/elastic/elasticsearch/issues/44484.

**Comment by Elias481** [comment]
> Thanks for the clarification. We regularly run our nightly benchmarks with 1GB of heap size (that is the out-of-the-box default of Elasticsearch) and I don't recall ever having problems there but it may be the case that you have a different workload that triggers this behavior. We did run also experiments on smaller heaps of 512MB and even 256MB a while ago. While I don't have the details handy, I also don't recall running into problems with those configurations.
So do the nightly benchmarks include inserting some GBs of data via bulk with higher speed the disks can write - und with the old "used-memory" circuit-breaker? If they would, I'm quite certain they would trigger OOM.

About the throtteling I found out it works as designed, but does not help in our case because we have mutiple primary shards on single mashine to allow better query parallelization. So if only one index is causing the high load on disk IO the throtteling does nothing.

> What I meant by the term "force-refreshing" is that it will ensure the indexing buffer contents are written to disk and it will start with the shard that takes up most of that buffer. That will mean additional load for the disk at this point, yes.
I would not call this additional load, it is currently THE load because almost all the writes are done through this (indexing into buffers until they are at threshold). According to our dev he found an issue with the way they handled disable and reenable of refreshing for the bulk-inserts and he fixed something. I cannot mind what it should be and don't know whether it helped. I don't think so because they cannot limit or raise the data written to disk with this as the force-refresh will kick in. (As long as no duplicate indexing has been done and is now avoided.)

For the GC, yes we use G1. Your findings are quite interesting on the one hand, on the other hand trivial. It's normal that with lowered InitiatingHeapOccupancyPercent it's less likely that the "real-mem" CB trips. But that means on the other hand that one need to assign much more heap than needed with a CB that accounts for the "used-mem" (excluding collectable garbage) as long as one can tolerate slowdowns during possible stw full-gc caused by trying to allocate more memory than currently available (this is what I prefer for our use case and why I would like to have the old cb enhanced to include the write-buffers).
The G1ReservePercent is quite new for me. I could test it but still InitiatingHeapOccupancyPercent=30 means one need to assign a lot more of Heap than wold be needed otherwise - and it is likele that it will trip often if the writing side does write much faster that disks are currently able to write - that is what our dev does not want / want to avoid. (Just don't want to implement logic :-( ....)

> I think this is a misunderstanding: Only the real memory circuit breaker (new in 7.0.0) asks the JVM for the current heap usage (and this is what I'd consider "real"). The previous circuit breaker only considers the amount of memory that is explicitly reserved within Elasticsearch (e.g. by the network layer or other parts of the application). If that component actually needs more memory to complete an operation than what was reserved, the parent circuit breaker wouldn't know. In that respect the new circuit breaker is admittedly "harsher" but takes into account also memory that has never been reserved. However, if a concurrent GC cycle is ongoing for a long time, the JVM cannot report the memory that is being reclaimed as "free" and thus the real memory circuit breaker is also a bit more conservative in that respect.
No this is not a misunderstanding, but a question of the technical point of view. From my point of view the new "real" memory CB has the downside that is does not or can not distinguish between memory occupied by live data and memory occupied by garbage. So the other old CB does this, thought it can only calculate what is currently known to consume space, thus cannot take everything into account and may be late with accounting used memory it gets aware about so gets aware aout that memory AFTER it has been already occupied (but for that reason it's set to a lower threshold and for our use case the only thing that consumes a notable amount of memory is always the write buffer).
So still I would like to have the current write-buffers refelcted in good old CB as soon as possible but as delayed as unavoidable. It will just help because this pool is growing fast and constantly, but not that fast that it would be too late if the old CB then trips at it default threshold of then 70% or what (the 10% default for the now unaccounted write buffers added to the default threshold).

> As the index buffer has a upper bound that is well-known upfront it should be possible to tweak the parent circuit breaker's limit? I think adding a new circuit breaker for an amount of memory that is well-known upfront seems more complex than changing the value. Semi-related, we're also discussing to throttle request on the network layer in #44484.
The index buffer just does not have an upper bound that is well-known upfront, exactly that is the cause of our problems. It will keep growing if incoming bulk-data causes the buffer to fill faster that the disks can write. It must not be a new-circuit breaker it would be sufficent to include it in the parent CB (but I think by design it should be a distinct circuit breaker, possibly without distinct limits but visible as such on the monitoring page). I cannot see anything realted to exactly this issue if the goal is minimize needed memory by not using the new CB (I would call it jvm-memory not real-memory, but anyhow...)

**Comment by Elias481** [comment]
In the meantime I tried with new suggested settings delivered with 7.4 (on both the 7.3.0 and 7.4.2 versions) - on the machines that generate the input data quite fast as they have "fast" (SSD) disks - but with write performance drops causing the OOMs with good old "calculated needed memory" circuit breaker as they are anyway oversized (3 to 4GB instead of <=1 GB which is totally sufficent for our use case).  

This (of course) avoids the crashed, but anyway it causes much to many rejected requsts (because of "real memory" circuit breaker tripping). This is bad for many reasons (user interface depends on elasticsearch availability as well as jobs are not designed to restart) - so besides the wasted memory which is an expensive good in cloud environments a huge performance and usability loss. Also we often get "429 Client Error: Too Many Requests for url: http://localhost:9200/_all/_settings" which disturbs our monitroing badly.  
It looks that we cannot go with that and have to switch back to the memory-efficient circuit breaker.

So the change does not really cost anything besides effort to implement, which is also not too high. Could You discuss that issue? Maybe we could make a PR for this if You do not have ressources to implement this?

**Comment by Elias481** [comment]
Any update here?

**Comment by danielmitterdorfer** [comment]
We did attempt to add an indexing circuit breaker in https://github.com/elastic/elasticsearch/pull/52469 but in the end decided to implement this differently in https://github.com/elastic/elasticsearch/pull/58885 which is available starting from Elasticsearch 7.9.0.

**Comment by Elias481** [comment]
#52469 sounds very resonably generally, the spec to suffice bulk-request protocol requirements is not clearly denoted. To some part the indexings protocol proposal suffices, but for the bulkloading nature of expected immediate wites, it could make sense to implement a timer for when the buffering capacity of the node suffering under load and seems to be stalling or gets stalled by more later buffering instance as for example a subsystem of the node's operating system output channel dedicated to the nodes targeted to by application-setting for data-folder and operatings systems configurations as well as hardware-configuration, that particular write thread or just the currently running method should be abandoned and it's output indexed in a round robin processable kind of buffer containing the checksum and the expected data block identifiers to have a watcher-threadpools thread supervising the abandoned thread and send a KILL signal if the node do not confirm abandonding currents buffer contents and undo the output operation resulted from current buffer content and estimate the corrections to be done in order for the nodes stale and duplicating as well as probably currupted output-activities to be revised in a sufficiently saved manner and put the calculated work away for another threads thread pool to initiate that output actions in bulk.

The advantage is, the buffers content can be processed by another node that is clear for buffering some data and write the pending data before the abandoning process is completed, or possibly clone the old thread if configured such in the nodes config and give it a start as when the buffer is just freshly filled after complete emptyness, keeping a connection so that the cloned thread can be assigned some of the watcher-threadpools thread work under the watchers supervision, for more efficiency and more effectivity if internal to a almost same thread for the node. On the other side, if the abandon is somehow confirmed without the respective thread had died or his confirmation contains a no hup or quit but a terminate request in the responses metadata, some watcher thread or if possible a clone thread mutated from the thread under question, can ensure the buffer is empty and the output subsystem is in a clear state, and recycle the thread when it sends the subsequent enquiry requests code sequence.

**Comment by Elias481** [comment]
The #58885 contains some part, for stall-checking and such, not certain whether some of the not instantly recognisable functionallity to implement in turn of that issue or in parall existing issues or PRs.
