### ISSUE TITLE
Error about injecting contructor after upgrading indexes from 2.4.6 to 5.0/5.1.2

### ISSUE THREAD

**Issue by rgarcia6520** [elastic/elasticsearch#45672]
**Elasticsearch version** 2.4.6

**Plugins installed**: [elasticsearch-migration]

**JVM version** openjdk 1.8.0_141

**OS version** Linux 64b5280735b3 3.13.0-168-generic #218-Ubuntu
(Elasticsearch official docker container Elasticsearch:2)

Upgrading cluster from 2.4.6 to 5.0, indices are confirmed as 2.X indices from the upgrade-assistant plugin. When starting cluster using existing graylog2 indices, we get an error about "Injecting Constructor" and elasitcsearch is unable to fully start.

What we expect to see happen:
Start cluster with 2.X indices on version 5.0.4 and see successful imports of indices and initialization of cluster.

Logs from error and cluster:
4) Error injecting constructor, java.lang.IllegalStateException: unable to upgrade the mappings for the index [[graylog2_12/Xljr968HSfatfnjqYPxY2g]]
  at org.elasticsearch.gateway.GatewayMetaState.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayMetaState
    for parameter 4 at org.elasticsearch.gateway.GatewayService.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayService

curl -XGET 'http://HOST:9200/graylog2_12/_mapping' 
{"graylog2_12":{"mappings":{"message":{"_source":{"compress":true},"_timestamp":{},"_ttl":{"enabled":true},"dynamic_templates":[{"store_generic":{"mapping":{"index":"not_analyzed"},"match":"*"}}],"properties":{"drupaluid":{"type":"long"},"facility":{"type":"string","index":"not_analyzed"},"full_message":{"type":"string","analyzer":"standard"},"gl2_remote_ip":{"type":"string","index":"not_analyzed"},"gl2_remote_port":{"type":"long"},"gl2_source_input":{"type":"string","index":"not_analyzed"},"gl2_source_node":{"type":"string","index":"not_analyzed"},"level":{"type":"long"},"message":{"type":"string","analyzer":"standard"},"remoteip":{"type":"string","index":"not_analyzed"},"source":{"type":"string","analyzer":"analyzer_keyword"},"streams":{"type":"string","index":"not_analyzed"},"timestamp":{"type":"date","doc_values":true,"format":"epoch_millis||yyyy-MM-dd HH:mm:ss.SSS"},"wdmessage":{"type":"string","index":"not_analyzed"},"wdtype":{"type":"string","index":"not_analyzed"}}}}}}

**Comment by original-brownbear** [comment]
This looks like it's the same issue with the `index` setting as the one that has been answered here https://github.com/elastic/elasticsearch/issues/31231#issuecomment-489782991 .
=> Closing here since we're no longer creating new 5.x releases.
