### ISSUE TITLE
How to Enable/Disable watchers automatically

### ISSUE THREAD

**Issue by ramya397** [elastic/elasticsearch#45691]
We are Alerting our customers when there is a problem in their infrastructure,Basically we are using ELK as a Monitoring solution.

We are having around 300+ watcher to notify when something goes wrong based on different alert type and condition ,now the problem is in weekend server bounces,upgrading like this other activities are going on. At this time we don't want to alert our customers false positive alerts because everybody knows that some activities are happening at this time.

**Comment by henningandersen** [comment]
Hi @ramya397,

Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
