### ISSUE TITLE
why id query is realtime?

### ISSUE THREAD

**Issue by zhuangshufeng** [elastic/elasticsearch#45695]
official documentation : the get API will issue a refresh call in-place to make the document visible.

First I call the id query, then call query QSL, the official documentation says it will call refresh, but I still can't search with query qsl?

(I set the refresh_interval is 60s for test)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
