### ISSUE TITLE
[CI] XPackRestIT different test cases are failing

### ISSUE THREAD

**Issue by 9deniz** [elastic/elasticsearch#45713]
Each time I run ```./gradlew :x-pack:plugin:integTestRunner``` locally on latest ES master branch, there is one test case failing, always different, some logs examples below:
https://scans.gradle.com/s/lws3q7ozokxmc
https://scans.gradle.com/s/ivnfpufxb6m64
https://scans.gradle.com/s/dk6hlyf6bdhuo

When rerunning failed test with ```REPRODUCE WITH``` command from build log, it passes. 

Am I missing something in local setup for running integration tests?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. And you can feel free to ping me directly on the forum topic. As such, I hope you don't mind that I close this.
