### ISSUE TITLE
ElasticsearchLRUQueryCache use much memory cause node OutOfMemoryError

### ISSUE THREAD

**Issue by LoadingZhang** [elastic/elasticsearch#45722]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0

**JVM version** (`java -version`): Build-in JDK12

**OS version** (`uname -a` if on a Unix-like system): CentOS 7.3

**Description of the problem including expected versus actual behavior**:
I have a index with join field, heap useage will raise to 90%+ when doing has_child query.
MAT report shows `org.elasticsearch.indices.IndicesQueryCache$ElasticsearchLRUQueryCache` consume 80%+ heap size.
![image](https://user-images.githubusercontent.com/10226902/63339093-bca50780-c376-11e9-97b2-45245ccff9fc.png)

what is the reason that ElasticsearchLRUQueryCache would larger then 10% of heap size and cause oom problem?

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
