### ISSUE TITLE
[RestHighLevelClient] mapper_parsing_exception, tried to parse field [list] as object, but found a concrete value

### ISSUE THREAD

**Issue by LiuWillow** [elastic/elasticsearch#45730]
elasticsearch version: 7.2 
java highLevelClient version: 7.2
this is my indexmapping,         
```
{
	"owner": {
		"properties": {
			"positionList": {
				"properties": {
					"positionId": {
						"type": "long"
					},
					"positionName": {
						"type": "keyword"
					}
				}
			}
		}
	}
}
```
I try to use java RestHighLevelClient updateByQuery api to update document,:
```
Script script = new Script(ScriptType.INLINE, DEFAULT_LANG, 
scriptBuilder.toString(), paramsMap);
request.setScript(script);
```
i tried to print script: 
```
Script{type=inline, lang='painless', 
idOrCode='ctx._source.owner.positionList=params.positionList;', 
options={}, params={positionList=[{"positionId":0,"positionName":""}]}}
```
then it occured:
![image](https://user-images.githubusercontent.com/25578789/63094807-f4d5d000-bf9b-11e9-9fc8-13ff7f1ee9e7.png)

but it did work when I ran the same script on kibana,
![image](https://user-images.githubusercontent.com/25578789/63094893-3ebeb600-bf9c-11e9-9927-1a848b6527d3.png)
I convert the object array to json and put it in the params map. It seems that the string can not be recognized as object array in java client

**Comment by LiuWillow** [comment]
> Pinging @elastic/es-core-features
I'm sorry that I don't understand what you mean. Should I put the question under this project or you just @ someone？ 
When I click on the link elastic/es-core-features ,  the page shows 404

**Comment by hub-cap** [comment]
>  When I click on the link elastic/es-core-features , the page shows 404

No this is fine, it is a subteam that some of us are on so we can receive notifications about the things that are relevant to our team. It is why I am reading this now, because i was notified :)

**Comment by hub-cap** [comment]
Can you give a complete example? I would like to see what `scriptBuilder` variable looks like. I dont know that passing in a `toString()` is the correct approach, but I can validate once I see more of your code.

**Comment by LiuWillow** [comment]
My code looks like this：
```
      //define department list
        List<ESDepartment> esDepartments = new ArrayList<>();
        ESDepartment esDepartment1 = new ESDepartment();
        esDepartment1.setDepartmentName("dep1");
        esDepartment1.setDepartmentId(1L);
        ESDepartment esDepartment2 = new ESDepartment();
        esDepartment2.setDepartmentName("dep2");
        esDepartment2.setDepartmentId(2L);

        esDepartments.add(esDepartment1);
        esDepartments.add(esDepartment2);

        UpdateByQueryRequest request = new UpdateByQueryRequest(ESConfig.indexName);
        request.setRouting("1");
        String jsonString = JSON.toJSONStringWithDateFormat(esDepartments, ESUtils.DEFAULT_DATE_FORMAT);

        Map<String, Object> paramsMap = new HashMap<>();
        paramsMap.put("departmentList", jsonString);

       //generate script
        Script script = new Script(ScriptType.INLINE, "painless",
                "ctx._source.owner.departmentList=params.departmentList;", paramsMap);
        request.setScript(script);

        request.setQuery(QueryBuilders.boolQuery().must(QueryBuilders.termQuery("companyId", 1L))
                .must(QueryBuilders.termQuery("entityId", 1L))
                .must(QueryBuilders.termQuery("dataType", (byte) 1)));

        System.out.println(script.toString());
        client.updateByQuery(request, RequestOptions.DEFAULT);
```
and ESDepartment is a entity look like this: 
```
public class ESDepartment {
    private Long departmentId;
    private String departmentName = "";
}
```
The script that the console printed looks like this:
```
Script{type=inline, lang='painless', idOrCode='ctx._source.owner.departmentList=params.departmentList;', 
options={},
 params={departmentList=[{"departmentId":1,"departmentName":"dep1"},
{"departmentId":2,"departmentName":"dep2"}]}}
```
and same exception occurs:
```
"cause":{"type":"mapper_parsing_exception",
"reason":"object mapping for [owner.departmentList] tried to parse field [departmentList] as object, but found a concrete value"}
```
and it did work when I copy the same script and params strings on kibana

**Comment by hub-cap** [comment]
I dont think that painless is able to interpret the string as json. Can you pass the params map as an actual nested map down? I think this should work.

```
Map<String, Object> paramsMap = Map.of("departmentList",
            List.of(
                Map.of("departmentId", 1, "departmentName", "dep1"),
                Map.of("departmentId", 2, "departmentName", "dep2")));
```

**Comment by LiuWillow** [comment]
this did work.. I thought it was a json string transferred like kibana.Thank you so much 
@hub-cap

**Comment by hub-cap** [comment]
:+1:
