### ISSUE TITLE
ERROR Unable to locate plugin type for ESJsonLayout

### ISSUE THREAD

**Issue by seanmpage** [elastic/elasticsearch#45760]
**Elasticsearch version** (`bin/elasticsearch --version`):
![Screen Shot 2019-08-20 at 2 20 54 PM](https://user-images.githubusercontent.com/12896091/63385450-d71ab900-c355-11e9-96b0-fc2429b7a0f9.png)

**Plugins installed**: 
N/A

**JVM version** (`java -version`):
![Screen Shot 2019-08-20 at 2 20 43 PM](https://user-images.githubusercontent.com/12896091/63385463-dc780380-c355-11e9-9e0c-8e0d17f4b898.png)

**OS version** (`uname -a` if on a Unix-like system):
<img width="238" alt="Screen Shot 2019-08-20 at 2 22 02 PM" src="https://user-images.githubusercontent.com/12896091/63385480-e6016b80-c355-11e9-9bc4-1b1f58182bfe.png">

**Description of the problem including expected versus actual behavior**:
After install elasticsearch via homebrew I am getting this error. 
![Screen Shot 2019-08-20 at 2 20 23 PM](https://user-images.githubusercontent.com/12896091/63385521-fd405900-c355-11e9-9ede-bfae43f94f9f.png)
I have tried all kinds of suggestions found from the googles and am at a standstill. 

**Steps to reproduce**:
N/A

**Provide logs (if relevant)**:

**Comment by mackermedia** [comment]
@seanmpage : I'm curious if you ever found a resolution for this? 
I'm running into the exact same issue.
