### ISSUE TITLE
[CI] RollupIndexerStateTests expected STARTED

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#45770]
This test has been failing frequently since ~20th August on 7.x and master

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.console-url),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RollupIndexerStateTests),sort:!(process.time-start,desc))

The error is always `Expected <STARTED> but: was <INDEXING>` e.g. 
```
java.lang.AssertionError: 
Expected: <STARTED>
     but: was <INDEXING>
	at __randomizedtesting.SeedInfo.seed([18DC60842CC79258:4BCFCF641A707760]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testSearchShardFailure(RollupIndexerStateTests.java:848)

java.lang.AssertionError: 
Expected: <STARTED>
     but: was <INDEXING>
	at __randomizedtesting.SeedInfo.seed([A3064620ADF98E4D:7B10D3C97C30BA3D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testUnknownKey(RollupIndexerStateTests.java:692)
```

2 recent failures
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/214/console
https://gradle-enterprise.elastic.co/s/22nlguzfshaxw

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=amazon/214/console
https://gradle-enterprise.elastic.co/s/rr4ygrwt7bvoq

Does not reproduce
```
./gradlew :x-pack:plugin:rollup:test --tests "org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testSearchShardFailure" \
  -Dtests.seed=18DC60842CC79258 \
  -Dtests.security.manager=true \
  -Dtests.locale=lt \
  -Dtests.timezone=Europe/Paris \
  -Dcompiler.java=12 \
  -Druntime.java=8


./gradlew :x-pack:plugin:rollup:test --tests "org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testUnknownKey" \
  -Dtests.seed=A3064620ADF98E4D \
  -Dtests.security.manager=true \
  -Dtests.locale=es-MX \
  -Dtests.timezone=America/Kentucky/Monticello \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

#45757 may fix `RollupIndexerStateTests::testBulkFailure` but there are other tests in the suite failing.

**Comment by davidkyle** [comment]
Muted in master b8645908d38eeb76a32df68642e0b6e332edb705 and 7.x 982560afebc78abe1af2f1804e8319d6ffc0332e

**Comment by benwtrent** [comment]
That change won't fix it. I know the problem and will have a fix in place asap
