### ISSUE TITLE
Some search results contain invalid UTF-8 in highlight field

### ISSUE THREAD

**Issue by emiksk** [elastic/elasticsearch#45771]
## Description of the problem including expected versus actual behavior
In some rare cases, Elasticsearch returns a search result containing an invalid UTF-8 character (such as "\uD83C") at the end of the highlight field.
Some clients cannot handle a response like this; they throw an exception.

I posted the same issue to elastic/elasticsearch-php#934 too.
#9538 (a little similar issue) is tagged as "won't fix" because the guidance says "don't put invalid utf-8 in the index if you can't handle it". However, I'm following the guidance in the case of this issue.

Could you help me work around this problem?
Thank you.

## Environment
I could reproduce this issue with the the docker image, elasticsearch/6.8.0:d0b291d7093b.

## Steps to reproduce
 1. index.json: The settings and mappings for an index
```
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "filter": [
            "cjk_bigram_filter"
          ],
          "tokenizer": "standard"
        }
      },
      "filter": {
        "cjk_bigram_filter": {
          "type": "cjk_bigram",
          "ignored_scripts": [],
          "output_unigrams": true
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "dynamic": "strict",
      "properties": {
        "data": {
          "type": "text",
          "term_vector": "with_positions_offsets"
        }
      }
    }
  }
}
```

 2. document.json: The document data for testing
```
{
  "data": "【This is the text for reproducing the issue】
【今日の作業】
・10:00-11:30 ミーティング（フリースペース）
・13:00-13:30 🌸タスク🌸:定型データ入力
・13:30-14:00 ..."
}
```

 3. search.json: The body to search
```
{
  "query": {
    "bool": {
      "must": {
        "query_string": {
          "query": "\"ミーティング\"",
          "fields": [
            "data"
          ],
          "default_operator": "and"
        }
      }
    }
  },
  "highlight": {
    "pre_tags": [
      "4bde2e4c-58b8-42fc-acaf-cb20f60fec4b"
    ],
    "post_tags": [
      "ea7a3b14-470c-482b-a889-64ad09c26e92"
    ],
    "fragment_size": 52,
    "number_of_fragments": 1,
    "fields": {
      "data": {
        "fragment_size": 52,
        "type": "fvh"
      }
    },
    "highlight_query": {
      "bool": {
        "must": {
          "query_string": {
            "query": "\"ミーティング\"",
            "fields": [
              "data"
            ],
            "default_operator": "and"
          }
        }
      }
    }
  }
}
```

4. You can reproduce the issue by the following procedure.
```
# Elasticsearch v6.8.0 is running on localhost with the default port.
$ curl -XPUT -H 'Content-Type: application/json' localhost:9200/test -d @index.json
$ curl -XPOST -H 'Content-Type: application/json' localhost:9200/test/_doc/1 -d @document.json
$ curl -XPOST -H 'Content-Type: application/json' localhost:9200/test/_search?pretty -d @search.json
# The search result is... 
{
  "took" : 26,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 4.7742524,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "doc",
        "_id" : "2",
        "_score" : 4.7742524,
        "_source" : {
          "data" : "【This is the text for reproducing the issue】【今日の作業】・10:00-11:30  ミーティング（フリースペース）・13:00-13:30 \uD83C\uDF38タスク\uD83C\uDF38:定型データ入力・13:30-14:00 ..."
        },
        "highlight" : {
          "data" : [
            "issue】【今日の作業】・10:00-11:30 4bde2e4c-58b8-42fc-acaf-cb20f60fec4bミーティン グea7a3b14-470c-482b-a889-64ad09c26e92（フリースペース）・13:00-13:30 \uD83C"
          ]
        }
      }
    ]
  }
}
```

The above search result contains the invalid UTF-8 character, "\uD83C", at the end of highlight.data[0].
"data"[0]: "...・13:00-13:30 **\uD83C**"

**Comment by jimczi** [comment]
It looks like the `fvh` highlighting does not check the boundary of unicode character correctly. I tested with the `unified` highlighter, which is the default since `es 6`, and the cherry blossom emoji is correctly handled. We plan to remove the `fvh` in a future release in favor of the `unified` highlighter that also uses terms vector when available so I'd recommend to test the new one (`unified`).

**Comment by emiksk** [comment]
Thank you so much for your response.

I confirmed this problem is fixed by your solution in my environment.

> We plan to remove the fvh in a future release in favor of the unified highlighter that also uses terms vector when available so I'd recommend to test the new one (unified).

This is very useful information for me. I'm looking forward to the release.

Closed. Thank you!
