### ISSUE TITLE
[CI] OpenCloseIndexIT testTranslogStats failures

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#45801]
```
java.lang.AssertionError: 
Expected: <9>
     but: was <30>
	at __randomizedtesting.SeedInfo.seed([9BC7168A89B5BF68:DDF74C95536F1D97]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.state.OpenCloseIndexIT.testTranslogStats(OpenCloseIndexIT.java:379)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1361/console
https://gradle-enterprise.elastic.co/s/thddxf4hncok4

[Build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-08-10T23:00:00.000Z',mode:absolute,to:'2019-08-21T22:59:59.999Z'))&_a=(columns:!(message,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:OpenCloseIndexIT),sort:!(time,desc))) shows this test has failed a few times recently

Does not reproduce:
```
./gradlew :server:integTest --tests "org.elasticsearch.indices.state.OpenCloseIndexIT.testTranslogStats" \
  -Dtests.seed=9BC7168A89B5BF68 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Africa/Mbabane \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by dnhatn** [comment]
Maybe relates to https://github.com/elastic/elasticsearch/pull/45473.
