### ISSUE TITLE
add a log

### ISSUE THREAD

**Issue by laijianbin** [elastic/elasticsearch#45890]
When zipkin connect to elasticsearch , no log shows is it connect success or not. Maybe add a log is better

**Comment by jkakavas** [comment]
Hi @laijianbin, 
Thanks very much for your interest in Elasticsearch.

Maybe this request would be better suited for the developers of zipkin in their [repo](https://github.com/openzipkin/zipkin/). As such, I hope you don't mind that I close this issue.
 As far as Elasticsearch is concerned, it would be impossible to add specific logging regarding every external system that connects to Elasticsearch somehow.
