### ISSUE TITLE
[Docs][Watcher] Email notification settings 

### ISSUE THREAD

**Issue by fdartayre** [elastic/elasticsearch#45908]
1. In [Email Notification Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/notification-settings.html#email-notification-settings) it should be clear that an account name is required under `xpack.notification.email.account`. For example `profile` cannot be configured under `xpack.notification.email.account`, it must be `xpack.notification.email.account.<account name>.profile`

2. `smtp.user` is shown as required but is not if `smtp.auth` is `false` (which is the default value)

**Comment by wchrisdean** [comment]
[doc issue triage]
