### ISSUE TITLE
[CI] test failure SnapshotStatusApisIT.testStatusAPICallInProgressSnapshot

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45917]
Test failed on 7.x. Doesn't reproduce for me.

./gradlew :server:integTest --tests "org.elasticsearch.snapshots.SnapshotStatusApisIT.testStatusAPICallInProgressSnapshot" \
  -Dtests.seed=D0C1B4242C6B7FA9 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CU \
  -Dtests.timezone=Etc/GMT+4 \
  -Dcompiler.java=12 \
  -Druntime.java=8

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-6&&immutable/219/console
Build Scans: https://gradle-enterprise.elastic.co/s/5cnjuw2u5gsnc

```
java.lang.AssertionError: expected:<INIT> but was:<STARTED>
```

**Comment by original-brownbear** [comment]
I opened #45929 which should fix this

**Comment by henningandersen** [comment]
The test failed on my intake build here:

https://gradle-enterprise.elastic.co/s/j6t7jbgj6ksga/tests/kyv2y2z3r4v7m-fol5ler4lgsjg?openStackTraces=WzBd

and the stack trace looks identical to the original:

```
java.lang.AssertionError: expected:<STARTED> but was:<INIT>Close stacktrace
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.elasticsearch.snapshots.SnapshotStatusApisIT.lambda$testStatusAPICallInProgressSnapshot$0(SnapshotStatusApisIT.java:104)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:895)
at org.elasticsearch.snapshots.SnapshotStatusApisIT.testStatusAPICallInProgressSnapshot(SnapshotStatusApisIT.java:104)
```

I checked that the fix from #45929 is included into 7.4 (which is also evident from the stacktrace). The the failure is in the same line of the test and it is waiting for a minute according to log file.

Seems like the original issue still exists (at least in 7.4) so reopening this issue.

**Comment by atorok** [comment]
Failed again on master: https://gradle-enterprise.elastic.co/s/savzjd7eyqdf6/tests/kyv2y2z3r4v7m-fol5ler4lgsjg

**Comment by original-brownbear** [comment]
Actually working fix incoming in https://github.com/elastic/elasticsearch/pull/46563 ... :)
