### ISSUE TITLE
[CI] Doc split-index failed on master

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45920]
doesn't reproduce for me

REPRODUCE WITH: ./gradlew :docs:integTestRunner --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/indices/split-index/line_161}" \
  -Dtests.seed=364FE8193A41A01A \
  -Dtests.security.manager=true \
  -Dtests.locale=pl-PL \
  -Dtests.timezone=Europe/Budapest \
  -Dcompiler.java=12 \
  -Druntime.java=11

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/934/console
Build Scans: https://gradle-enterprise.elastic.co/s/cjdn4kjtd4dy6

Relevant stacktrace:

```
java.lang.AssertionError: Failure at [reference/indices/split-index:59]: expected [2xx] status code but api [raw[method=POST path=my_source_index/_split/my_target_index]] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [my_target_index/QqBVFW-uRSODi6JIxOmasQ] already exists","index_uuid":"QqBVFW-uRSODi6JIxOmasQ","index":"my_target_index","stack_trace":"[my_target_index/QqBVFW-uRSODi6JIxOmasQ] 
```

**Comment by dnhatn** [comment]
Relates to #46091
