### ISSUE TITLE
A dedicated field datatype for injecting user provided tokens

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#45942]
This case from [this](https://discuss.elastic.co/t/data-type-to-specify-exact-tokens-to-index/195637) discuss question.

Would it make sense to create a dedicated field datatype that will allow to inject a user-provided tokens?
```js
PUT my_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "my_tokens": { 
          "type": "tokens"
        }
      }
    }
  }
}

```

```js
PUT my_index/_doc/1
{
  "my_tokens": [
    {
      "value": "data",
      "start": 5,
      "end": 11
    }
  ]
}
```

**Comment by markharwood** [comment]
We discussed this today in the weekly search meeting.
We've seen this feature in Solr and one of the concerns we had was that when you are dealing with multiple clients written in different languages the issue of their encodings and reliable offsets and lengths comes in. The client also has some responsibilities to ensure positions etc tie up with the strict Lucene requirements about valid token streams.
There's also the question of how to handle search input - we need to know which analyzer to use on any text searches.

The main use case for this I expect are things like entity extraction tools (as was the case with the referenced discuss question). We targeted this with the `annotated_text` type and one (known) limit was the lack of support for nested annotations. An example might be this text:

    he met with the President of Mexico

An entity extraction tool might want to annotate both the person "President of Mexico" and the country "Mexico". Today we might get around that using a multi-value annotation separated by ampersands eg

```
  he met with the [President of Mexico](Andrés+Obrador&Mexico) 
```

This might be adequate for some scenarios. Another consideration is to create a new form of markup that supports nesting using start and end tags. An example with two number annotations might be:

```
  he met with the [1 Andrés+Obrador]President of [2 Mexico]Mexico[/1][/2]
```
This might help solve the indexing issues but of course highlighting is another messy area to have to deal with and nested annotations will require some complex code there too.

I'd like to see just how many people need the added complication of nested annotations before embarking on any support for that.

**Comment by markharwood** [comment]
The original discuss issue relating to nested annotations has now had an [update](https://discuss.elastic.co/t/data-type-to-specify-exact-tokens-to-index/195637/11?u=mark_harwood)

The user has proposed using the annotated text plugin in this way:

```One solution we are looking at is marking up each word separately so we can support nested entities, for example if we have the entity 'leg' (ANAT:456) within 'short leg syndrome' (IND:123): [short](IND:123) [leg](IND:123&ANAT:456) [syndrome](IND:123)```

**Comment by nik9000** [comment]
@markharwood should we keep this one open?

**Comment by markharwood** [comment]
Closing seems reasonable. I don't think we have any strong cases emerging for something beyond what annotated text offers today.
