### ISSUE TITLE
QPS 

### ISSUE THREAD

**Issue by madonhe** [elastic/elasticsearch#45959]
I want to testing elasticsearch 7.X QPS,
before I use YCSB,but 7.x move type
How do you recommend me to do QPS testing?
I'm learning to use elasticsearch

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
