### ISSUE TITLE
 can't to issue sync id  forout of sync replica 

### ISSUE THREAD

**Issue by xubb1988** [elastic/elasticsearch#45965]
hi.  
 i have a Cluster，  build on elasticsearch  6.3.1, i use bulkAsync to insert index in my api, i found i loss my data sometime,  then  i check the log  file,  there some log like :
  can't to issue sync id [ch_qyXmGR6O71Kkk3RXziw] for out of sync replica [[myIndex][7], node[Cryea8MmTWaYvJ9Vk6XoZw], [R], s[STARTED], a[id=z3BH41oNR2GpCog7TkbM0Q]] with num docs [33387]; num docs on primary [33388],
thanks for you help

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
