### ISSUE TITLE
[Docs][Update API] Usage of version parameter not present in the API specs

### ISSUE THREAD

**Issue by ezimuel** [elastic/elasticsearch#45961]
The Elasticsearch reference page [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_15) mentions `version` as possible parameter. 
This parameter is not included in the API specifications [/rest-api-spec/src/main/resources/rest-api-spec/api/update.json](https://github.com/elastic/elasticsearch/blob/v7.3.0/rest-api-spec/src/main/resources/rest-api-spec/api/update.json#L31-L77) that I'm using to generate the [elasticsearch-php](https://github.com/elastic/elasticsearch-php) client.
I'm not sure if this is an issue of the docs or a missing parameter in the spec.

**Comment by ezimuel** [comment]
From https://github.com/elastic/elasticsearch/pull/43516 it seems that we do not support anymore the `version` parameter in Update API. Thanks @jkakavas  for sharing this. I'll open a PR for updating the docs.

**Comment by arteam** [comment]
Fixed in #43516
