### ISSUE TITLE
[docs] Custom Analyzer callouts are invalid

### ISSUE THREAD

**Issue by bmorelli25** [elastic/elasticsearch#45995]
The callouts for 2-6 on the [Custom Analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/analysis-custom-analyzer.html#CO290-3) page are blank. In the [source](https://github.com/elastic/elasticsearch/blob/7.3/docs/reference/analysis/analyzers/custom-analyzer.asciidoc), it appears to be because all the callouts are labeled as `(1)`.

This problem appears from `5.0` to `master`.

<img width="684" alt="Screen Shot 2019-08-26 at 1 43 07 PM" src="https://user-images.githubusercontent.com/5618806/63722372-eb542f80-c807-11e9-96ab-19d955aa6f2e.png">

**Comment by jrodewig** [comment]
#46030 fixes this for all branches within the support lifecycle (currently 6.8-8.0). Generally, we avoid backporting to earlier branches.

**Comment by bmorelli25** [comment]
Nice!
