### ISSUE TITLE
[CI] Failure in ILMDocumentationIT.testAddSnapshotLifecyclePolicy

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#46021]
The following failed on `7.x`:

```
11:09:05 org.elasticsearch.client.documentation.ILMDocumentationIT > testAddSnapshotLifecyclePolicy FAILED
11:09:05     java.lang.AssertionError: 
11:09:05     Expected: <1L>
11:09:05          but: was <2L>
11:09:05         at __randomizedtesting.SeedInfo.seed([667E1B76EEB11627:FF88531C062144A]:0)
11:09:05         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:09:05         at org.junit.Assert.assertThat(Assert.java:956)
11:09:05         at org.junit.Assert.assertThat(Assert.java:923)
11:09:05         at org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy(ILMDocumentationIT.java:869)
11:09:06 REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy" -Dtests.seed=667E1B76EEB11627 -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=America/Lima -Dcompiler.java=12 -Druntime.java=8
```

[Build Scan](https://gradle-enterprise.elastic.co/s/r2vkjnwvgohzs/console-log)

@dakrone can you take a look?

**Comment by original-brownbear** [comment]
Another one https://gradle-enterprise.elastic.co/s/5heq24lk5ausi

**Comment by henningandersen** [comment]
Another one, also 7.x:

https://gradle-enterprise.elastic.co/s/ujxnu53ps7ms2/console-log?task=:client:rest-high-level:integTestRunner#L34

I wonder if it could be a variant of #46224 in that both cases seems to be either a delete/create or double create issue in rest tests.

**Comment by henningandersen** [comment]
The symptom here looks sufficiently close to #46091, any objections to closing this?

**Comment by dakrone** [comment]
@henningandersen it does look the same, let's close this for now and we can re-open if it occurs again now that we use ram disks for the CI.

**Comment by original-brownbear** [comment]
This happened again here https://gradle-enterprise.elastic.co/s/ssgsd3wxbxvno in `7.x`

**Comment by dnhatn** [comment]
This still happens after #46881: https://gradle-enterprise.elastic.co/s/5opdtqmvz3j4i.

**Comment by DaveCTurner** [comment]
Also https://gradle-enterprise.elastic.co/s/hbt4xxlvwtrnc

**Comment by gwbrown** [comment]
This is now the same problem as https://github.com/elastic/elasticsearch/issues/48441: `Could not determine repository generation from root blobs`.  We likely just need to add some retries around this type of exception, or wait until the underlying issue is fixed as described at https://github.com/elastic/elasticsearch/pull/48433#discussion_r338514444.

**Comment by original-brownbear** [comment]
@gwbrown I think you'll be happier with retries and keeping the coverage for the time being. A fix (including reviews) will probably not happen in less than 2 weeks.

**Comment by gwbrown** [comment]
Thanks @original-brownbear, I was going to ping you soon to ask about the timeline on that. I'll move ahead with implementing retries as needed in these tests.

**Comment by gwbrown** [comment]
Now that https://github.com/elastic/elasticsearch/pull/48548 has been merged and back ported, this failure should be fixed. I'm going to close this, please reopen if the failure shows up again.
