### ISSUE TITLE
SQL: CASE WHEN with NULL result yields NULL column type

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#46032]
If there's a `null` in the results of a CASE WHEN query, the column type is incorrectly set to `null`.

Example: 
```
SELECT (CASE WHEN ({fn DAYOFWEEK("employees"."hire_date")} IN (7, 1)) THEN NULL ELSE "employees"."hire_date" END) AS DOW
FROM "employees"
GROUP BY 1
```
returns:
```
{
  "columns" : [
    {
      "name" : "DOW",
      "type" : "null"
    }
  ],
  "rows" : [
    [
      null
    ],
    [
      "1985-02-18T00:00:00.000Z"
    ],
    [
      "1985-05-13T00:00:00.000Z"
    ],
  ...
```

**Comment by matriv** [comment]
`master` : 8c1012efbbd3a300afd0dfb9b18250f15ea753f9
`7.x` : 3bee647e5b10579c6d7dd6729f06ca64be4b6240
`7.4` : 09697f848b6541bbb55287c72579ba6e3eeabf1a
`7.3` : 6e5cb35780707ea7c78f366ffb74d18f5cdfbaab
