### ISSUE TITLE
Unable to manage Elasticsearch index using Curator

### ISSUE THREAD

**Issue by LiuZeng520** [elastic/elasticsearch#46056]
I want to use Curator to manage the index of Elasticsearch.But my Elasticsearch uses the elasticsearch-setup-passwords command to set the username and password, and where should I configure the Curator. Please let me know if you know. thank you very much.

**Comment by astefan** [comment]
@LiuZeng520 this doesn't seem to be a confirmed bug or feature request, but a general usage question about Curator. We believe this type of questions are better handled in our forum: https://discuss.elastic.co.

I'll go ahead and close this issue. In the meantime, you might want to have a look at https://discuss.elastic.co/t/curator-not-able-to-authenticate-elasticsearch-with-x-pack/132206/2, regarding your question.

**Comment by LiuZeng520** [comment]
I have solved it, thank you very much.
