### ISSUE TITLE
SQL: incorrect DATE format when converting and GROUPing BY

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#46090]
ES/SQL will return a DATETIME value (instead of a DATE) when `GROUP BY` is applied:
`SELECT {fn CONVERT("@timestamp", SQL_DATE)} FROM kibana_sample_data_logs GROUP BY 1`
will return:
```
"columns" : [
    {
      "name" : """CONVERT("@timestamp", SQL_DATE)""",
      "type" : "date"
    }
  ],
  "rows" : [
    [
      "2018-07-22T00:39:02.912Z"
    ],
...
```

It works as expected without the `GROUP BY` clause (that is `"2018-07-22T00:00:00Z"`)

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/3e25db2f302c3aafe27e4d8d4fb1743401d85e6d
7.x (7.5.0): https://github.com/elastic/elasticsearch/commit/40e93539475bfe5f51e3d65f4179a0a718c86134
7.4 (7.4.1): https://github.com/elastic/elasticsearch/commit/162bffaab140bc081eb597d970e31153c21166a8
