### ISSUE TITLE
[docs] Search template callouts are broken

### ISSUE THREAD

**Issue by bmorelli25** [elastic/elasticsearch#46109]
The callouts on the [Search template](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-template.html#pre-registered-templates) page are broken. The following errors appear in every branch from `master` to `1.3`.

---

The first code block is broken because `<1>` is used three times:
<img width="577" alt="Screen Shot 2019-08-28 at 7 36 13 PM" src="https://user-images.githubusercontent.com/5618806/63906166-b85a9900-c9cb-11e9-8921-6a28872614e4.png">

---

The second is broken because the number `<2>` is used twice:

<img width="582" alt="Screen Shot 2019-08-28 at 7 36 22 PM" src="https://user-images.githubusercontent.com/5618806/63906165-b5f83f00-c9cb-11e9-9d0e-a2b240d5fa97.png">

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.
