### ISSUE TITLE
illegal_argument_exception but the total_fields doesn't exceeded

### ISSUE THREAD

**Issue by BainDragneel** [elastic/elasticsearch#46108]
Http put request, dynamically map when dynamically adding data**Describe the feature**:

illegal_argument_exception but i get the total doesn't exceeded
**Elasticsearch version** (`bin/elasticsearch --version`):
7.3.0 and 6.7.0
**Plugins installed**: []
head kibana
**JVM version** (`java -version`):
11.0.2
**OS version** (`uname -a` if on a Unix-like system):
macOS 10.14.4
**Description of the problem including expected versus actual behavior**:
Under dynamic mapping, when I want to import new data, I am prompted that the field under the index exceeds 1003, but I see that the total number of fields at that time is 1000.
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.curl -s -XGET 'the address of ES/your index/_mapping?pretty' | grep type | wc -l   to get the sum of total_fields,   mine 1000 ,The maximum number of my ES settings is 1003....
 2.Look for a data already in the ES, add a new key and value (I added "ceShiTotalIndex": 1000), and re-use the http put request to try adding to the ES
 3.Request 400, prompt me "Limit of total fields [1003] in index [orders] has been exceeded"

**Provide logs (if relevant)**:
I have not yet checked the specific log., But when I set the maximum number to 2000, the same body re-request can be added, but the total_fields field of the index under the current ES mapping is only changed to 1004.

I hope someone can explain the detection method, principle and mechanism of the total fields of the mapping index.
Thanks!

**Comment by BainDragneel** [comment]
hi!!!!!  no one?

**Comment by jimczi** [comment]
The total number of fields includes objects and nested fields so I guess that you have `1000` leaves and 3 object field. If you have additional questions, please use the [forums](https://discuss.elastic.co/c/elasticsearch) as we reserve GitHub for bug reports and feature requests.
