### ISSUE TITLE
Introduce intellij gradle - junit plugin

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#46118]
Some tests require additional configuration like jvm options in order to pass. To make running them easier, it would be great if we could prepare the configuration in gradle build files and use that in IDE as a runner template.
@mark-vieira suggested we can use from Jetbrains for Intellij 
https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.1#junit

**Comment by atorok** [comment]
Relates to #32257 would be nice if Eclipse also has something like this

**Comment by cbuescher** [comment]
To add some specifics to this, we just ran into some tests (SearchQueryIT.testRangeQueryWithLocaleMapping) that require
`-Djava.locale.providers=SPI,COMPAT` to be set when running from an IDE (Eclipse, IntelliJ). I added some note to the CONTRIBUTING docs and that particular test in  #49491 but it would be great not to have to think about this.
