### ISSUE TITLE
Add a summary of IngestStats to ClusterStatsNodes

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#46146]
It would be nice to see a unified view of which processors are being used by the cluster in the cluster-stats response. Right now, ingest-stats is present in node stats, but it is left out of cluster-stats. This issue is open to discuss and track if and how it makes sense to expose these details in the `ClusterStatsNodes` part of the `ClusterStatsResponse`

Some information that would be interesting to provide that is missing

- number of pipelines present
- set of processor types used

**Comment by talevy** [comment]
Come to think of it, this type of info may be better served in the Cluster Info Response

For example

```
    "ingest" : {
      "number_of_pipelines" : 2,
      "processor_types" : [
        "circle",
        "gsub",
        "script"
      ]
    }
```

Can you think of any other information you'd like to see in this @giladgal?

**Comment by giladgal** [comment]
To document our quick discussion about it, we want to collect:
1. Which environments used the processor
2. How many records were ingested by the processor

**Comment by martijnvg** [comment]
👍 I think we can easily include this information (all installed processor types with a node count and the cluster wide ingest count) in the cluster stats api when it gathers stats from all nodes that are part of the cluster.
