### ISSUE TITLE
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

### ISSUE THREAD

**Issue by vivekj11** [elastic/elasticsearch#46168]
I tried to create a basic setup with one Elasticsearch pod.
The jvm_memorry for this pod is 8GB.
index.number_of_shards: 3

I didn't notice the pod for some time and today I found that the above-mentioned error. it says that all my shards are failed.
I checked the data size and it grows to 37GB.

I removed the backend volume from the ES and added a new volume. Now the cluster is up and running but with the new data only.

Now the challenge is to merge the old data with this new volume and thus the cluster and I don't know how to do this. 

Any help here would be really appreciated.

**Comment by tlrx** [comment]
Hi @vivekj11 , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
