### ISSUE TITLE
Make the snippets more "asciidoctor" standard

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#46189]
This is to track the cleanup that we can do to the docs after #46180 and #45937. That is:
1. On console snippets we can
 1. Replace `[source,js]` with `[source,console]`
 2. Remove `// CONSOLE`
2. On console response snippets we can
 1. Replace `[source,js]` with `[source,console-result]`
 2. Remove `// TESTRESPONSE` if it doesn't have any special operations like `s`

The first on is nice because it makes the docs consistent with how they actually work in Asciidoctor. The second one does that too but *also* will allow clients to override those snippets when they are overriding request snippets.

**Comment by nik9000** [comment]
@jrodewig started this with #46159.

**Comment by jrodewig** [comment]
#46295 switches all the // TESTRESPONSE comments over.

**Comment by jrodewig** [comment]
Second PR: #46353

**Comment by jrodewig** [comment]
Once #46353 and #46440 are merged, we can consider this near complete.

However, there are likely pending PRs that still contain the old magic comments.

@nik9000 Are we planning to remove support for those magic comments? If so, we may want to do a coordinated "final cleanup" right beforehand. We'd also want some way to address pending PRs that have already passed CI but would fail in production if support was removed.

All that is moot if we want to continue supporting both.

**Comment by jrodewig** [comment]
Closing this as #46936 ends support for `// CONSOLE` in the `master` and `7.x` branches.

7.4 acts as a 'bridge' branch where both `[source,console]` and `// CONSOLE` are supported.
