### ISSUE TITLE
rewrite_time in _search takes a lot longer after upgrading from 6.4.2 to 6.8.2

### ISSUE THREAD

**Issue by imrimt** [elastic/elasticsearch#46194]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.2

**Plugins installed**: [aws-repository, hdfs-repository, s3-repository, gcs-repository]

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

We recently upgraded our ES cluster from 6.4.2 to 6.8.2 without any changes to the data. One thing we notice is that the **same** search query takes a lot longer in 6.8.2, and after turning on profiling, we notice the significant time increase for `rewrite_time`. I couldn't find anything through the release notes that indicate this change in behavior.

We were able to pin-point the regression due to `field_value_factor` function in the `function_score` query within the `has_child` query when applied on the `cluster.idHash` field (see the query for more details). `cluster.idHash` is a `long` field, and all the documents have this field populated with a fairly big values. When applied to another `long` field in which most documents have null, low or small values, the `rewrite_time` goes back to normal. 

If we also create a `float` or `int` field and populate it with random values and use that field instead, it is also faster. We experimented this because #17497 indicates that the `_score` field is `float` type.

**Steps to reproduce**:

Not sure what the minimal steps are to reproduce this, but we can share the queries and the profiling information here:
Here's our query: https://gist.github.com/imrimt/4bae846b627201de8dd0acf20f545cb7
Here's the profiling section when running against the 6.4.2 cluster: https://gist.github.com/imrimt/27fab2bf9bafa409ae34ae462c11cfc7
And here's the profiling section when running against the 6.8.2 cluster: https://gist.github.com/imrimt/dba81fea4950d99ebbd6013c2d9e0b12

**Comment by javanna** [comment]
Closing since this is a pretty old issue, sorry we have not replied until now. Feel free to add more context, timing info especially against more recent versions and we'll reopen.
