### ISSUE TITLE
ElasticSearch - How to Update with Api Update

### ISSUE THREAD

**Issue by maczy** [elastic/elasticsearch#46209]
I need help to use Api Update in elasticsearch, the problem is what I have when I want to update this level further inside the structure, for example:

`{
"mainLevel": [
    {
        "name": "maxi",
        "SecundaryLevel": [
            {
                "title": "Bachelor"
            }
        ]
    }
]
}`

In this case the update would like to do it in "SecondaryLevel" but for a certain "MainLevel", I leave my index below.

`# Index an animal
POST test_object/animales/1
  {
"name": "test_object",
"cats": [
  {
  "colors": 1,
  "name": "Irida",
  "breed": "European Shorthair"
},
{
  "colors": 2,
  "name": "Nino",
  "breed": "Aegean",
  "toys": [
      {
        "colors": 1,
        "name": "pelotita"
      }
  ]
}
],
"dogs": [
{
  "colors": 1,
  "name": "Irida",
  "breed": "European Shorthair"
}
]
}`

My Update:

`POST test_object/animales/1/_update
{
    "script": {
       "source": "ctx._source.toys.add(params.val)",
       "lang": "painless",
       "params": {
           "val": {
               "colors": 77,
               "name": "cricket"
           }
       }
   }
 }`

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
