### ISSUE TITLE
Multi Level Nested Queries

### ISSUE THREAD

**Issue by omkar1707** [elastic/elasticsearch#46210]
I have a multi-level nested document. I want to query based on multiple nested queries with all the conditions must match.

Elastic Search Version: 6.5.0

Example

Document 1
```
{
	"publishing_rule": {
		"publishing_orders": [{
				"transporters": [{
					"fteid": "81"
				}],
				"active": false
			},
			{
				"transporters": [{
					"fteid": "82"
				}],
				"active": true
			}
		]
	}
}
```

Document 2
```
{
	"publishing_rule": {
		"publishing_orders": [{
				"transporters": [{
					"fteid": "81"
				}],
				"active": true
			},
			{
				"transporters": [{
					"fteid": "82"
				}],
				"active": false
			}
		]
	}
}
```

I want to fetch all the documents which match below condition
```
publishing_rule.publishing_orders.active = true 

AND 

publishing_rule.publishing_orders.transporters.fteid = '81'
```
Both `active` and `transporters.fteid` should be part of same object.

I have tried creating below mapping
```
{
  "mappings": {
    "_doc": {
      "properties": {
        "publishing_rule.publishing_orders": {
          "type": "nested",
          "properties": {
            "transporters": {
              "type": "nested"
            }
          }
        }
      }
    }
  }
}
```
And used below query 
```
{
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "publishing_rule.publishing_orders",
            "query": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "publishing_rule.publishing_orders.active": true
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "nested": {
            "path": "publishing_rule.publishing_orders.transporters",
            "query": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "publishing_rule.publishing_orders.transporters.fteid": "81"
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
Also tried below query. 
```
{
  "query": {
    "nested": {
      "path": "publishing_rule.publishing_orders",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "publishing_rule.publishing_orders.active": true
              }
            },
            {
              "nested": {
                "path": "publishing_rule.publishing_orders.transporters",
                "query": {
                  "bool": {
                    "must": [
                      {
                        "match": {
                          "publishing_rule.publishing_orders.transporters.fteid": "81"
                        }
                      }
                    ]
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}
```
But I am not getting expected result. The query returning both the documents. 

I am expecting only Document 2 in the result.

**Comment by astefan** [comment]
@omkar1707 we appreciate your interest in Elasticsearch and asking questions when having difficulties when using it, but the github repo is for confirmed bugs, issues or new features request. This sort of question you posted is better suited for our [forum like website](https://discuss.elastic.co/), where not only Elastic employees can answer but also community members.

As such, I will close this issue now, kindly suggesting you post your question in the forum I mentioned above, if my suggested query below doesn't fix the issue.

In your case I think the correct query should be (haven't actually tried it, only built it using your snippets, so there may be syntax errors in it):

{
  "query": {
    "nested": {
      "path": "publishing_rule.publishing_orders",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "publishing_rule.publishing_orders.active": true
              }
            },
            {
              "match": {
                "publishing_rule.publishing_orders.transporters.fteid": "81"
              }
            }
          ]
        }
      }
    }
  }
}
