### ISSUE TITLE
 Es 6.2.3 uses multiple indexes to correspond to the same alias. Can the query result be de-duplicated according to the alias?

### ISSUE THREAD

**Issue by luww** [elastic/elasticsearch#46216]
Version es 6.2.3 uses multiple indexes (index 1 and index 2) to correspond to the same alias, queries by alias, whether the query results can be de-duplicated, or can specify preferential queries (by percentage) for index 1 or index 2 data.

Index 1 and index 2 have the same data with _id;

Using collapse-field did not achieve the desired results.

**Comment by astefan** [comment]
@luww Can you, please, try explaining the issue again? It is difficult for me to understand  the issue/question. Thank you.

**Comment by astefan** [comment]
@luww You could, also, ask the question in our forum - discuss.elastic.co - and if it helps more, even in your native tongue: https://discuss.elastic.co/c/in-your-native-tongue/chinese. I will go ahead and  close this issue for now, kindly asking you to open a new issue if you have a confirmed bug or feature request in the future.
