### ISSUE TITLE
boolean, string, number value - canonical form

### ISSUE THREAD

**Issue by regfaker** [elastic/elasticsearch#46222]
Hi,
hard to say if this is bug or feature request. From my point of view it is rather bug.

Boolean type fields accepts both boolean and string boolean values. But it is saved in that form which comes in. So then in search response hits there are mixed values "true", true, ...
It was suprising to me that it does not persist canonical value of given type. Ok, search term based on boolean value is working but if hits are processed then it is not what one would expect. Of course it could be said that it is competence of client which sends data to save. But it is also part of competence of storage to hold values of given type in correct form.

Same behaviour for string (keyword, text) (number value stored), number (string value of number is allowed) types.

Shouldn't be all types saved in their canonical form?

**Elasticsearch version**: 6.6.1
**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Linux  4.4.0-1075-aws #85-Ubuntu SMP Thu Jan 17 17:15:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 1. Put boolean type mapping to field on some index.
 2. Save document to this index with this field value as "true" (string form)
 3. Make _search to return this new document and string form value will be returned in hits _source.

**Comment by cbuescher** [comment]
> But it is saved in that form which comes in. So then in search response hits there are mixed values "true", true, ...

I assume by this statement you refer to the way those values are returned in the "_source" section of the documents in search hits, correct? In that case I can probably explain. The [_source field](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html) the original JSON document body that was passed at index time. We do this so that the "ground truth" of what the user indexed is preserved in its original form, e.g. to be able to re-index it into another index later, but also for other purposes. The values are "indexed" internally in a common form (and in case of e.g. text in its analyzed form).
It would be helpful to understand what you are trying to do that the current behaviour doesn't allow to see if there is anything missing in terms of functionality, but returning "_source" the way it was entered is likely going to stay this way.

**Comment by regfaker** [comment]
Yes, _source has "unconverted" values passed at index time. I just don't think the type tolerance is ok, well maybe would be ok if it is converted ("true" -> true). It should throw an error if value is of other type or it should convert to that type.
I don't see the value of keeping it in its original form because either you have it all in same form and then it doesn't bring any additional value or values are in mixed form (some true, some "true") and you have to resolve this before/after re-index anyway.
But if you will stay this way - is there a way to return that common form you've talked about in hits?
Thanks

**Comment by cbuescher** [comment]
>  is there a way to return that common form you've talked about in hits

In the case of boolean fields, yes. Its called [doc_values](https://www.elastic.co/guide/en/elasticsearch/reference/current/doc-values.html) and is enabled by default on fields supporting it. You can include it in your search result like described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-docvalue-fields). E.g.
```
PUT /index_2
{
  "mappings": {
    "properties": {
      "flag" : {
        "type": "boolean"
      }
    }
  }
}

PUT /index_2/_doc/1
{
  "flag" : true
}

PUT /index_2/_doc/2
{
  "flag" : "true"
}

POST /index_2/_search
{
  "docvalue_fields" : ["flag"]
}
```
will return
```
"hits" : [
      {
        "_index" : "index_2",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "flag" : true
        },
        "fields" : {
          "flag" : [
            true
          ]
        }
      },
      {
        "_index" : "index_2",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "flag" : "true"
        },
        "fields" : {
          "flag" : [
            true
          ]
        }
      }   
    ]
```

**Comment by cbuescher** [comment]
I'm going to close this issue for now, but feel free to add anything if you feels there is anything missing. For more general follow-up questions around doc_values and the search API we prefer folks using the support forums over at https://discuss.elastic.co. Thanks.
