### ISSUE TITLE
[CI] qa:vagrant#update fails with SSL error

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#46233]
A number of builds has failed with an error similar to this one:

```
10:38:37 ==> debian-8: Checking for updates to 'elastic/debian-8-x86_64'
10:38:37     debian-8: Latest installed version: 20190901.0.0
10:38:37     debian-8: Version constraints: 
10:38:37     debian-8: Provider: virtualbox
10:38:37 
10:38:37 Standard error:
10:38:37 There was an error while downloading the metadata for this box.
10:38:37 The error message is shown below:
10:38:37 
10:38:37 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

[6.8](https://gradle-enterprise.elastic.co/s/mrwj7qhcww3s2)
[6.8](https://gradle-enterprise.elastic.co/s/qqojiwiozraso/console-log?task=:x-pack:qa:vagrant:vagrantFedora26%23update)
[7.3](https://gradle-enterprise.elastic.co/s/rtv242kgnlcyi/console-log?task=:qa:vagrant:vagrantUbuntu1604%23update)

**Comment by jaymode** [comment]
@atorok @mark-vieira it appears that this is on your radar, have you done any investigation or have ideas/a plan around these failures?

**Comment by mark-vieira** [comment]
I've not had a chance to investigate this yet. We use vagrant only for packaging tests for these older, more inactive branches so it's fallen down the queue a bit. I'll try and make some time to revisit this.

**Comment by rjernst** [comment]
This hasn't reoccurred that I can find, so closing for now.
