### ISSUE TITLE
Java HighLevelRestClient back-compatibility issue for type, auto_generate_synonyms_phrase_query

### ISSUE THREAD

**Issue by Kabhal** [elastic/elasticsearch#46238]
Reopening of https://github.com/elastic/elasticsearch/issues/29374

elasticsearch-rest-high-level-client is not back-compatible with older version **5.6.13** of ES (still used by OpenShift)  for at least 2 unsupported attributes :
* `type` : `org.elasticsearch.client.ResponseException: method [POST], host [***], URI [/.kibana.*/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=20s&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[query_string] query does not support [type]","line":1,"col":287}],"type":"parsing_exception","reason":"[query_string] query does not support [type]","line":1,"col":287},"status":400}`
* `auto_generate_synonyms_phrase_query` : `org.elasticsearch.client.ResponseException: method [POST], host [***], URI [/.kibana.*/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=20s&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[query_string] query does not support [auto_generate_synonyms_phrase_query]","line":1,"col":533}],"type":"parsing_exception","reason":"[query_string] query does not support [auto_generate_synonyms_phrase_query]","line":1,"col":533},"status":400}`

At least the following clients are not compatible :
* 'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.7.0'
* 'org.elasticsearch.client:elasticsearch-rest-high-level-client:7.3.1'

ElasticSearch server version : 5.6.13

Code extract to make the request with client 7.3.1 : 
```
SearchSourceBuilder searchBuilder = new SearchSourceBuilder();

      searchBuilder.sort(SEARCH_INDEX, SortOrder.ASC);
      searchBuilder.query(boolQuery()
                                .must(rangeQuery(SEARCH_INDEX)
                                            .format(DATE_FORMAT)
                                            .from(formattedDate(fromDate, DATE_FORMAT))
                                            .to(formattedDate(toDate, DATE_FORMAT)))
                                .must(queryStringQuery(query)
                                            .analyzeWildcard(true)
                                            .defaultField("*")
                                            .defaultOperator(Operator.AND)));
      searchBuilder.size(PAGE_SIZE);

      return new SearchRequest(INDEX).source(searchBuilder).scroll(SCROLL_TIMEOUT);
```

**Comment by Kabhal** [comment]
Here the API response for  `_nodes` as requested in previous issue : [_nodes.json.zip](https://github.com/elastic/elasticsearch/files/3566294/_nodes.json.zip)

**Comment by javanna** [comment]
Can you confirm that what you are trying to do is send a request to 5.6.x using a 6.x or 7.x client?

**Comment by Kabhal** [comment]
@javanna Yes I confirm ..

**Comment by javanna** [comment]
@Kabhal that is not supported. See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html please.

**Comment by Kabhal** [comment]
Ok sorry, I thought back-compatibility was for minor and majors ...
Any tip to develop a general purpose ES client supporting multiple ES versions ?

**Comment by javanna** [comment]
No worries! it's not just about minors and majors, but also that the client is forward compatible meaning it is meant to be the last component to be upgraded once you move your cluster to a newer Elasticsearch version.

Developing a general purpose ES client supporting multiple ES versions is really not the goal of the high-level REST client. If you want to be able to talk to multiple majorversions with the same client, I would recommend using the low-level REST client , though it does not offer the same features, as marshalling and unmarshalling of requests and response is up to users.
