### ISSUE TITLE
[CI] elasticsearch-hadoop build failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#46239]
This has failed since the version bump to 7.5 in elasticsearch-hadoop:

```
15:31:24 * What went wrong:
15:31:24 Could not resolve all files for configuration ':buildSrc:runtimeClasspath'.
15:31:24 > Could not find org.elasticsearch.gradle:build-tools:7.5.0-SNAPSHOT.
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+7.x+periodic/90/console

**Comment by henningandersen** [comment]
CC: @jbaiera

**Comment by jasontedor** [comment]
This will succeed when we have a successful 7.x snapshot. This is being tracked elsewhere, and doesn’t require any changes in this project nor elasticsearch-Hadoop.
