### ISSUE TITLE
[CI] SSLClientAuthTests failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#46230]
All tests in SSLClientAuthTests failed in a number of builds, starting on August 29th, with either suite timeout failure or `NoNodeAvailableException`:

```
Suite timeout exceeded (>= 1200000 msec)
```

```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{kaRXMmaCTEeL1PvopD2gQg}{127.0.0.1}{127.0.0.1:33166}]Close stacktrace
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
```

looks like following is part of the underlying cause:

```
1> [2019-09-02T02:32:59,967][WARN ][o.e.t.TcpTransport       ] [node_sm1] exception caught on transport layer [TcpNioSocketChannel{localAddress=/127.0.0.1:44852, remoteAddress=127.0.0.1/127.0.0.1:43203}], closing connection
--
1> javax.net.ssl.SSLException: Received fatal alert: internal_error
1> 	at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
1> 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
1> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
1> 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
1> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
1> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
1> 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:672) ~[?:?]
1> 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:627) ~[?:?]
1> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:443) ~[?:?]
1> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:422) ~[?:?]
1> 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:674) ~[?:?]
1> 	at org.elasticsearch.xpack.security.transport.nio.SSLDriver.unwrap(SSLDriver.java:178) ~[main/:?]
1> 	at org.elasticsearch.xpack.security.transport.nio.SSLDriver$RegularMode.read(SSLDriver.java:327) ~[main/:?]
1> 	at org.elasticsearch.xpack.security.transport.nio.SSLDriver.read(SSLDriver.java:119) ~[main/:?]
1> 	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.read(SSLChannelContext.java:165) ~[main/:?]
1> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
1> [2019-09-02T02:32:59,968][WARN ][o.e.t.TcpTransport       ] [node_sm0] exception caught on transport layer [Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:43203, remoteAddress=/127.0.0.1:44852}], closing connection
1> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Session has no PSK
```

Example builds:

[master](https://gradle-enterprise.elastic.co/s/tgtlskl7r52j2/console-log?task=:x-pack:plugin:security:test#L18)
[7.x](https://gradle-enterprise.elastic.co/s/tk7gomx2kkuby/console-log?task=:x-pack:plugin:security:test#L20)

Around 15 builds failed since 29th August:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SSLClientAuthTests),sort:!(time,desc))

CC @tbrooks8

**Comment by henningandersen** [comment]
This does reproduce using:

```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLClientAuthTests"   -Dtests.seed=E8F33A5E6B8FE7EF   -Dtests.security.manager=true   -Dtests.locale=rwk-TZ   -Dtests.timezone=America/Antigua   -Dcompiler.java=12   -Druntime.java=11
```

against 7.x

**Comment by jkakavas** [comment]
I can't see any commits that could have introduced this on August 28th/29th.

**Comment by henningandersen** [comment]
There were several tests that starting failing on August 29th and this does coincide with the version bump. It may be a red herring, but could be worth examining. I did try a few naive searches, but did not spot anything that would differ based on the version bump.

**Comment by hendrikmuhs** [comment]
another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/545/console

**Comment by tvernum** [comment]
Another: https://gradle-enterprise.elastic.co/s/lymakh2qm3dr2

**Comment by tlrx** [comment]
I muted the test in f033c3fb8955d3ac01e5551556b67a5b7a172d95

I think that #45666 which added AdopOpenJDK is a good suspect.

**Comment by droberts195** [comment]
Now that `testThatHttpFailsWithoutSslClientAuth` is muted the failure has moved on to a different test in the same suite: `testThatHttpWorksWithSslClientAuth`

This failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/199/console with the error `cluster failed to form with expected nodes`.

Some possibly interesting exceptions from the [test output](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/199/testReport/junit/org.elasticsearch.xpack.ssl/SSLClientAuthTests/testThatHttpWorksWithSslClientAuth/) are `javax.net.ssl.SSLException: Session has no PSK`, `javax.net.ssl.SSLException: Received fatal alert: internal_error` and `javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)`.

The failure did not reproduce locally for me using:

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.ssl.SSLClientAuthTests.testThatHttpWorksWithSslClientAuth" \
  -Dtests.seed=2784063770E3790B \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-MQ \
  -Dtests.timezone=US/Central \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by droberts195** [comment]
I muted `SSLClientAuthTests.testThatHttpWorksWithSslClientAuth` in 52c709120fc2290074466bbf2f36e83aa90aab2b as it has failed a few times now.

**Comment by jaymode** [comment]
There was a [race condition](https://bugs.openjdk.java.net/browse/JDK-8213202) related to this fixed in JDK 12 and JDK 11.0.3. I sampled the failures and the runtime java is adoptopenjdk11 or JDK 11.0.2. I for sure have seen this with JDK 11.0.2, but I am not sure what patch version adoptopenjdk11 would equate to; @jasontedor do you know?

**Comment by jasontedor** [comment]
@jaymode OpenJDK 11.0.2 would equate to AdoptOpenJDK 11.0.2 as well.

**Comment by jaymode** [comment]
Further digging reveals that `adoptopenjdk11` is most likely not AdoptOpenJDK11 but the base Oracle JDK 11, which would trigger these failures as well.

```
Runtime JDK Version   : 11 (Oracle Corporation 11 [OpenJDK 64-Bit Server VM 11+28])
Runtime java.home     : /var/lib/jenkins/.java/adoptopenjdk11
```
