### ISSUE TITLE
A question about search threadpool size

### ISSUE THREAD

**Issue by rpgmakervx** [elastic/elasticsearch#46246]
As **org.elasticsearch.threadpool. ExecutorBuilder#applyHardSizeLimit** method shown that write threadpool holds a **controllable** core thread count, default could not over 32.

but search will return an unlimit max size which means that when queue is full, thread will be created ulimitly. So why search threadpopl designed like this?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by rpgmakervx** [comment]
thanks for your advies
