### ISSUE TITLE
Wildcard queries should not normalize/remove wildcards in queries

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#46300]
Wildcard queries should not normalize wildcards from queries

Example scenario where wildcard queries do not exhibit expected behavior:

```
PUT my-index
{
  "mappings": {
    "_doc": {
      "properties": {
        "foo": {
          "type": "keyword",
          "normalizer": "no_wildcard"
        }
      }
    }
  },
  "settings": {
    "index": {
      "analysis": {
        "char_filter": {
          "no_wildcard": {
            "pattern": "[\\*]",
            "type": "pattern_replace",
            "replacement": ""
          }
        },
        "normalizer": {
          "no_wildcard": {
            "type": "custom",
            "char_filter": "no_wildcard"
          }
        }
      }
    }
  }
}

PUT /my-index/_doc/1
{
    "foo": "bar"
}

GET my-index/_search
{
  "profile": true,
  "query": {
    "wildcard": {
      "foo": {
        "value": "ba*"
      }
    }
  }
}
```

The resulting input that is provided to the wildcard query removes the `*`.

```
// output from the query profiler for above query
...
             {
                "type" : "MultiTermQueryConstantScoreWrapper",
                "description" : "foo:ba",
...
```

Because of this, the search does not find any matching documents.

I believe this relates to #28894.

**Comment by jimczi** [comment]
I think we can consider this as a bug. The reserved characters should be excluded when the normalization is applied. As a comparison, the `query_string` splits the wildcard input by reserved characters and applies normalization on each split independently to build the normalized version:
https://github.com/apache/lucene-solr/blob/master/lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParserBase.java#L708
We should do the same in the `wildcard` query.

**Comment by talevy** [comment]
thanks Jim. I'll update the labels
