### ISSUE TITLE
ReindexIT#testUpdateByQuery can fail with assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#46301]
This failure first popped up a couple times in the master intake builds, once in `testDeleteByQuery` and once in `testUpdateByQuery`. In both failures, it seems that there is an unexpected task still running after the main test logic has completed.

First build scan: https://gradle-enterprise.elastic.co/s/rasy6lapqbogy
Second build scan: https://gradle-enterprise.elastic.co/s/t5l5j3kplm2fa

A code snippet containing one of the failing assertions:

```
// any rethrottling after the delete-by-query is done performed with the same taskId should result in a failure
response = execute(new RethrottleRequest(taskIdToRethrottle, requestsPerSecond),
    highLevelClient()::deleteByQueryRethrottle, highLevelClient()::deleteByQueryRethrottleAsync);
assertTrue(response.getTasks().isEmpty());
```

**Comment by henningandersen** [comment]
Given this is only in master intake, I think this was affected by the IO problem described in #46091. Still, the 2s timeout is too aggressive, so will leave open until PR is merged.
