### ISSUE TITLE
Feature Request: Index mixed with all other indexes

### ISSUE THREAD

**Issue by rajatrj16** [elastic/elasticsearch#46313]
Ideally, ES `data/node/0/indices` should group to similar objects, So suppose I have created one index i.e `SOMEINDEX-*`, 
It should group into one, so if one index is deleted accidentally it should not affect other nodes or elastic search, 

**Current scenario:** Now what happens is if one index is deleted, you can never recover the index or can not delete its metadata, It should not depend on that.

Also, we can not find the indices inside ES matched with index, But we can do that in` DEV tool` by this command: `GET /_cat/indices?v`

**Comment by jasontedor** [comment]
Are you referring to using filesystem delete operations to remove directories on disk?

**Comment by rajatrj16** [comment]
My opinion is to resolve the dependencies over indices, This is because when you messed up with one index it should not break the whole elasticsearch.

**Comment by rajatrj16** [comment]
at least we should be able to identify which index related to which alas.

**Comment by jasontedor** [comment]
I'm sorry @rajatrj16, I am not following. Can you provide the specific steps that you are following, and the errors that you are encountering?

**Comment by astefan** [comment]
No further feedback received. @rajatrj16 if you have the requested information please add it in a comment and we can look at re-opening this issue.
