### ISSUE TITLE
SQL: add DATE_TRUNC function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#46319]
The DATE_TRUNC function is used to truncate date/datetimes to specified precision.
https://www.w3resource.com/PostgreSQL/date_trunc-function.php

**Comment by jbonn360** [comment]
@astefan does this need approval? I can work on this

**Comment by astefan** [comment]
@jbonn360 thank you for your interest in ES-SQL. We do appreciate it.
We've already started looking at this implementation and it's not that trivial. If you maybe would like to have a look at a more simple issue to start with, that would be preferable.

**Comment by jbonn360** [comment]
@astefan ok cheers

**Comment by matriv** [comment]
@jbonn360 Once again, thank you for your interest to contribute to our project.
If you'd like you could give a go on a functionality extension of DATE_TRUNC to include intervals: #46632

**Comment by matriv** [comment]
`master` : b37e96712db1aace09f17b574eb02ff6b942a297
`7.x` : d956509394a848f92764e219297e00758b280f50
