### ISSUE TITLE
SQL: add DATEPART function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#46372]
DATEPART function receives 2 or 3 parameters:
- first parameter is a string which indicates which "part" of a DATE or DATETIME field is needed. Example: 'day', 'year', 'month' etc
- the second parameter is the date/datetime field itself (or a literal)
- the third parameter is optional and is either `Sunday` or `Monday` that indicates the start of the week for the respective time zone in which the date is considered to be in.

The returned value is of type INTEGER.

**Comment by astefan** [comment]
As an example for `month` part:
`CONVERT(TRUNCATE(EXTRACT(MONTH FROM my_date_field),0), SQL_BIGINT)`

**Comment by matriv** [comment]
`master` : ead743d3579eb753fd314d4a58fae205e465d72e
`7.x` : f792dbf23915d9c4b97c75964d41e7494354a53e
