### ISSUE TITLE
Failed assertions in integration tests should be made more visible to developers

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#46379]
It looks like people have a hard time figuring out the cause of a failure caused by a failing assertion. We do who all the logs but it's easy to miss and since the node dies there will be lots of test failures that might draw the eye instead. 

We teach testclusters about assertions and have it detect it in the logs and better surface it. 
Instead of dumping all the logs on a failure, we could just surface the assertion in cases like this.

See also  #31834

**Comment by mark-vieira** [comment]
I believe the updated test clusters framework which includes node logs in test output more or less addresses this problem.
