### ISSUE TITLE
SQL subquery

### ISSUE THREAD

**Issue by kaplan6616** [elastic/elasticsearch#46383]
Hi,

SELECT * FROM index where index.id NOT IN ( SELECT index.responseID from index where index.type=3)

i am writing this sql in elastic search but it says "not in query not supported yet". I'm wondering can i write this query in elastic DSL? or can i write this query another way ?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
