### ISSUE TITLE
HLRC: allow to run delete by query with wait_for_completion=true

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#46395]
**Describe the feature**: The HLRC has a method for reindex, that allows to trigger an async reindex by running `RestHighLevelClient.submitReindexTask` and `RestHighLevelClient.reindex`. The delete by query however only has an `RestHighLevelClient.deleteByQuery` method (and its async counterpart), but no `RestHighLevelClient.submitDeleteByQueryTask`.

**Comment by vaibhavkhanduja** [comment]
@spinscale can I take a look at this bug? It is marked as good first issue and I want to start contributing.

**Comment by qianyuxiang01** [comment]
@spinscale I have add function submitDeleteByQueryTask in class RestHighLevelClient and have a pull request.Could you review the code?
