### ISSUE TITLE
Exception cause unwrapping ran for 10 levels

### ISSUE THREAD

**Issue by jasonwee** [elastic/elasticsearch#4639]
Hi,

To summarize from https://groups.google.com/forum/#!msg/elasticsearch/WdMU4_vD8zk/SKjOiCGHvFgJ

running elasticsearch version 0.90.7 

gist file 
https://gist.github.com/jasonwee/8282477 
https://gist.github.com/jasonwee/8294514

server and client both running the same version the entire times.
$ java -version
java version "1.6.0_25"
Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.0-b11, mixed mode)

According to Jörg Prante, this is worth raising an issue at the Elasticsearch github . 

node3 elasticsearch instance was restarted and then the exceptions is no longer exists in node1 and node4 no more.

If you need more information, please let me know what I can provide.

Thank you.

Jason

**Comment by sacheendra** [comment]
This problem still exists. Noticed it while doing a benchmark. Some nodes had high CPU usage relative to other nodes and similar things were there in the logs of such nodes. 

Gist of the error: https://gist.github.com/sacheendra/ab00b6625c3367ed06c1

ES version: 1.4.0
JVM: Hotspot 1.7.0_67
Number of nodes: 15

**Comment by Srinathc** [comment]
Found a similar exception on release 1.3.0.
https://discuss.elastic.co/t/stackoverflowerror-in-es/25278/2

**Comment by clintongormley** [comment]
We have changed exception handling completely in master - would be interested to know if you're seeing something similar in 2.0 (once it is released)

**Comment by Srinathc** [comment]
Are there any details on when and why this happens? Any remedies for 1.x releases will be great to know. Our instances are already on production.

Thanks.

**Comment by clintongormley** [comment]
almost all of these exceptions are due to a change in serialization between java versions.  we no longer rely on java serialization.  also, stack traces are now trimmed of their guice content (see https://github.com/elastic/elasticsearch/pull/13782)

I think this is resolved in 2.0
