### ISSUE TITLE
Add percentage for other stats (affects _stats and _cat)

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#4642]
Percentages are quite useful for doing quick diagnosis - there's such an indicator for ram/heap but we could/should extend them to other runtime stats as well such as disk used/free for example.

**Comment by bleskes** [comment]
@clintongormley the sentiment is that this is still a useful thing, but we need to judge on a metric by metric basis.  

@costin it's a long time ago- but was there some specific metrics you had in mind? (other then the disk usage)

**Comment by clintongormley** [comment]
No feedback in 18 months. Closing
