### ISSUE TITLE
high level rest client count request fails with 400 Bad Request

### ISSUE THREAD

**Issue by ItamarBenjamin** [elastic/elasticsearch#46446]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.0

**Plugins installed**: []

**JVM version** (`java -version`): official 6.7.0 docker

**OS version** (`uname -a` if on a Unix-like system): linux

**Description of the problem including expected versus actual behavior**:
when executing count request from high level rest client and using "terminate_after", requests fails with this error:
{
        "type": "parsing_exception",
        "reason": "request does not support [terminate_after]",
        "line": 2,
        "col": 2
      }

this is because terminate_after is sent in the request body and not as request param

was able to reproduce with kibana by running this:

PUT /test
POST /test/_count
{
 "terminate_after":1 
}

however this works:

POST /test/_count?terminate_after=1

**Steps to reproduce**:

can reproduce with this code:

`
CountRequest countRequest = new CountRequest(index);
        countRequest.terminateAfter(1);
        CountResponse countResponse = highLevelClient.count(countRequest, RequestOptions.DEFAULT);
`

**Comment by hub-cap** [comment]
This is definitely a bug. Looks like we are passing back that value in the post data entity, like you suspect. The fix is to stop doing that, as well as to add it to the request converters such that it can be passed in the param map.

**Comment by shardulsonar** [comment]
Hello, I can pick this issue. Will update the progress as soon as I have a solution.

**Comment by shardulsonar** [comment]
@turackangal Are you still working on this issue. I am ready with the solution.  ?

**Comment by turackangal** [comment]
Yes, I will finish today.

**Comment by sankettg** [comment]
Is there a workaround for this for earlier version?
