### ISSUE TITLE
[CI] CuckooFilterTests.testEqualsAndHashcode fais

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#46443]
The test `CuckooFilterTests.testEqualsAndHashcode` failed today:
https://gradle-enterprise.elastic.co/s/rqifrbr6u4lpk

It reproduces on master and 7.x using:
```
gradlew ':server:test' --tests "org.elasticsearch.common.util.CuckooFilterTests.testEqualsAndHashcode" -Dtests.seed=2B86B99BE45AAA8E -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=America/Buenos_Aires -Dcompiler.java=12 -Druntime.java=8
```

**Comment by polyfractal** [comment]
I see the issue.  When we randomly create test filters, we allow creating filters with super low capacity/precision.  This means that no matter what you add to the filters it's pretty much guaranteed to create internal collisions after a handful of values, which means all filters converge to equality quickly.

Will push a fix with some larger defaults, and some better logging in case this happens again.

**Comment by tlrx** [comment]
Thanks @polyfractal !
