### ISSUE TITLE
[DOCS] ES Reference [6.8] Mappings doc issue

### ISSUE THREAD

**Issue by stiltz** [elastic/elasticsearch#46460]
On the [Elasticsearch Reference [6.8] >> Mappings](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/mapping.html) docs page the [Example Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/mapping.html#_example_mapping) shows 7 references in the example screenshot but then the references only show 1 - 4 and 5 - 7 are blank.

I don't know what the proper steps for 5-7 are otherwise I'd submit a PR.

**Here is a screen capture from the docs:**
---
![image](https://user-images.githubusercontent.com/16760856/64451268-71466500-d0a9-11e9-89c7-71b7075c4b81.png)

**Comment by cbuescher** [comment]
@stiltz thanks for pointing this out. Looking at the example, I think the text on point 4 is meant to cover all remaining callouts. Putting it on each field again would create unnecessary repetition. Having said that, the example has been already reworked in the [7.0 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/mapping.html#_example_mapping), so I'm leaning towards leaving it like it is on 6.8. Happy to accept a PR though if you think its clearer the way it is in 7.0, just adapt the 6.8 example accordingly and open a PR.

**Comment by stiltz** [comment]
@cbuescher I opened [PR 47109](https://github.com/elastic/elasticsearch/pull/47109) to update the docs. I think it's more clear and may benefit those still on the 6.x versions.

**Comment by jrodewig** [comment]
Closing this as #47109 is now merged.
