### ISSUE TITLE
ilm time operations' formula not support month or longer time range

### ISSUE THREAD

**Issue by godlockin** [elastic/elasticsearch#46479]
ES 6.7.2/6.8/7.3
Systen: Mac/CentOS

actually i think the env stuffs doesn't matter.

I read the guide and source code of indices life management, the min_age field is only supporting form nanosecond to day...

It means, it means if I need to rolling retire some indices, e.g. every month .etc, I ganna build my own script to "manually" retire the indices then.

Can the normal time operations be supporting here as they do in time range query .etc?

**Comment by dakrone** [comment]
@godlockin I'm not sure I understand, is there a reason you don't want to do `30d` as your time range?

**Comment by godlockin** [comment]
@dakrone 
in this case, when i use the ilm function, I may want to make some index move hot->warm, warm -> cold ... in 1 month, 2 months .etc

while, as the time calc formula here, I need to calculate the days of 1 month to 30days and set it as 30d in script, and, what i want/need is just set it as 1M/2M .etc as the other time calculations (e.g. time range query), because there aren't 30days in every months, Jan. has 31 days while most of Feb. has only 28days .etc, when I set it as 30d, some cross months issues might happen then

**Comment by godlockin** [comment]
no more update?

**Comment by dakrone** [comment]
@godlockin thanks for explaining your use case, we're still prioritizing the ILM work, so I don't know when we would address this yet.

**Comment by dakrone** [comment]
We've left this open to see if there was any other feedback regarding it, but as it stands, this issue would introduce a fair amount of complexity (dealing with calendars) without enough benefit. I am going to close this for now.
