### ISSUE TITLE
hightlight not worked when use script_score

### ISSUE THREAD

**Issue by suxianbaozi** [elastic/elasticsearch#46471]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.1

**Plugins installed**: ["ikAnalyse"]

**JVM version** (`java -version`):1.7

**OS version** (`uname -a` if on a Unix-like system):centos7

**Description of the problem including expected versus actual behavior**:

hightlight not worked when use script_score，highlight not found in the response

if i used function_score it works fine

GET company/_search
{
  "query": {
    "script_score":{
      "query": {
        "multi_match": {
          "query": "有限公司",
          "fields": ["companyName^5","historyName^4","companyDesc"],
          "minimum_should_match": "4<50%"
        }
      },
      "script":{
        "source":"1"
      }
    }
  }, 
  "highlight": {
    "fields": {"companyName": {},"companyDesc": {},"historyName":{}}
  }
}

**Comment by mayya-sharipova** [comment]
@suxianbaozi  Thank you for filing this issue.  Indeed the highlighting was not working in `script_score` query. This would be fixed in 7.5.
