### ISSUE TITLE
BUG: High Rest Client MultiSearchTemplateRequest ignores HTTP-GET parameters

### ISSUE THREAD

**Issue by eemelianov** [elastic/elasticsearch#46488]
**Elasticsearch version** elastic Docker-Image elasticsearch:7.3.0
**High Rest Client version** 7.3.1

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:
Hight Rest Client maps es-requests to Low Level Rest Client Requests. MultiSearchTemplateRequest is mapped via RequestConverters#multiSearchTemplate, this method is missing the line to add Params to the underlying Request, like in other methods: `request.addParameters(params.asMap());`

**Steps to reproduce**:

1. Create a MultiSearchTemplateRequest add a request and use a stored script with simple terms aggregation.
2. Use RestHighLevelClient#msearchTemplate(request, RequestOptions.DEFAULT) to get the response.

**Comment by henningandersen** [comment]
@eemelianov , thanks for reporting this, I opened #46492 to fix this.
