### ISSUE TITLE
Docker problems exclusively on MacOS

### ISSUE THREAD

**Issue by mihai1voicescu** [elastic/elasticsearch#46548]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.1

**Plugins installed**: []

**JVM version** (`java -version`): from docker

**OS version** (`uname -a` if on a Unix-like system): MacOS

**Description of the problem including expected versus actual behavior**:
Loading the dump does not work on MacOS with docker, but works on Windows(with docker) and allegedly on Linux as described in https://github.com/taskrabbit/elasticsearch-dump/issues/592

It gives out the following error:
```
Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
```

**Steps to reproduce**:

 1. echo '{"comment":{"mappings":{"properties":{"created":{"type":"date"},"creator":{"properties":{"id":{"type":"keyword"},"type":{"type":"keyword"}}},"joinField":{"type":"join","eager_global_ordinals":true,"relations":{"comment":"reply"}},"patientId":{"type":"keyword"},"text":{"type":"text"},"type":{"type":"keyword"}}}}}' > dump.json
 2. npm install -g elasticdump
 3. docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.3.1

 4. elasticdump --output=http://localhost:9200/comment --input=./dump.json --type=mapping

**Provide logs (if relevant)**:
```
(base) wlan-145-94-230-236:es mihaivo$ elasticdump --output=http://localhost:9200/comment --input=./dump.json --type=mapping
Tue, 10 Sep 2019 14:30:54 GMT | starting dump
Tue, 10 Sep 2019 14:30:54 GMT | got 1 objects from source file (offset: 0)
Tue, 10 Sep 2019 14:30:54 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
Tue, 10 Sep 2019 14:30:54 GMT | Total Writes: 0
Tue, 10 Sep 2019 14:30:54 GMT | dump ended with error (set phase)  => [object Object]
(base) wlan-145-94-230-236:es mihaivo$ 
```

**Comment by dliappis** [comment]
Hey @mihai1voicescu 

Thanks very much for your interest in Elasticsearch.

This appears to be a user question. I tried the above reproduction steps on macOS: it didn't reproduce and `comment/_mapping` was created correctly.

In fact seeing the error looks as if the application somehow tries to use [types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) so I'd double check the tool is the same version on all platforms.

At any rate, we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
