### ISSUE TITLE
_field_caps API takes long time (more than a minute) to return results

### ISSUE THREAD

**Issue by nikhil-bhat** [elastic/elasticsearch#46544]
**Elasticsearch version** 6.7.2

**JVM version** Java HotSpot(TM) 64-Bit Server VM (1.8.0_172):

**OS version** Linux

**field_caps API takes long time (more than a minute) to return results**:

**Steps to reproduce**:
1.) Index pattern with about 409 matching indices with about 61 fields
2.) curl -XGET https://esurl:9200/indexpattern-*/_field_caps?fields=*
2.) Takes 1 minute 45 seconds to get the result.

This causes kibana to not be able to refresh the index pattern as default timeout is set to 30 seconds.
Is it on expected lines , Anything that can be done to speed up this api ?. Cluster is not resource constrained?

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
