### ISSUE TITLE
[DOCS] Redesign version compatibility for snapshot/restore

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#46596]
The current information design for [snapshot/restore version compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-snapshots.html#_version_compatibility) is a bit dense and difficult to visually parse.

<img width="742" alt="Screen Shot 2019-09-11 at 9 29 53 AM" src="https://user-images.githubusercontent.com/40268737/64701410-bb975f80-d476-11e9-8015-0fe6e2c22530.png">

We should redesign this section of the documentation to be more scannable.

**Comment by wchrisdean** [comment]
[doc issue triage]
Assigning this to myself, working on snapshot/restore doc overhaul anyway and this is an element of that.
