### ISSUE TITLE
SQL: Extend DATE_TRUNC to also operate on intervals

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46632]
According to the PostgreSQL spec the DATE_TRUNC's 2nd argument can also be an interval: https://www.postgresql.org/docs/9.1/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC
Currently for ES-SQL it only supports DATETIME & DATE.

Follow up to: #46319

**Comment by musteaf** [comment]
Hi, I would like to work on this issue. Can I take it?

**Comment by rajalohiy8** [comment]
can I take this issue and work on this?

**Comment by musteaf** [comment]
Hi @matriv I am fully ready to work on this issue. I am just waiting for your response to prevent conflicts. Can I take it?

**Comment by matriv** [comment]
@musteaf Sorry for the delayed response. Please go ahead.
Thank you!

**Comment by musteaf** [comment]
@matriv No problem. I will start right away. Thank you.

**Comment by shoaib4330** [comment]
@musteaf Could I pick it up if you're not actively working on it?

**Comment by DANIELK121** [comment]
Hi, is this issue still open?
If so, I would like some help to run the function DATE_TRUNC - 
I have forked and downloaded the project to my machine, and as written in the README file i ran 
the @./gradlew assemble@ command in the cloned directory (via cmd line in windows). 
I get the message:

`FAILURE: Build failed with an exception.`
and
```
* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> At least Java 11 is required to build elasticsearch gradle tools
```
i have JDK 13 installed. 
what can be the problem?

**Comment by musteaf** [comment]
Hi @shoaib4330 I'm about to finish. Only tests left.

**Comment by musteaf** [comment]
@matriv Sorry for being late. I sent a PR. https://github.com/elastic/elasticsearch/pull/47720

**Comment by matriv** [comment]
@musteaf no worries at all, please, thank you for working on this.

**Comment by matriv** [comment]
> Hi, is this issue still open?
> If so, I would like some help to run the function DATE_TRUNC -
> I have forked and downloaded the project to my machine, and as written in the README file i ran
> the @./gradlew assemble@ command in the cloned directory (via cmd line in windows).
> I get the message:
> 
> `FAILURE: Build failed with an exception.`
> and
> 
> ```
> * What went wrong:
> A problem occurred evaluating project ':buildSrc'.
> > At least Java 11 is required to build elasticsearch gradle tools
> ```
> 
> i have JDK 13 installed.
> what can be the problem?

@DANIELK121 Since @musteaf has already picked this up, please try to find another issue you would like to contribute to.

Regarding the problems you're having when trying to build es have you followed the guide here: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase ?

**Comment by matriv** [comment]
`master` : 2dc79505825fa75e0711dcfa8e9c69e8028fc979
`7.x` : af03200ad6ac982e7db4515ae61acab8a8b1bfec
