### ISSUE TITLE
[DOCS][release notes] term dict memory usage is a 7.3.0 enhancement, not 7.2.0

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#46635]
7.2.0 release notes mention this change:

`Use reader attributes to control term dict memory useage #42838 (issue: #38390)`

https://github.com/elastic/elasticsearch/pull/42838 was originally labeled 7.2.0. The change was not committed until 7.3.0.

Please correct the release notes for [7.2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.2.0.html) and [7.3.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.3.0.html).

**Comment by javanna** [comment]
This is now fixed.
