### ISSUE TITLE
Setting the refresh_interval parameter failed

### ISSUE THREAD

**Issue by LiuZeng520** [elastic/elasticsearch#46643]
I want to set:
"refresh_interval" : "5s"

I used the put method:
_all/_settings { "index" : { "refresh_interval" : "5s" } }

But it returned 405
![image](https://user-images.githubusercontent.com/43592564/64750584-0505ae80-d54c-11e9-8472-2056c6886fea.png)

**Comment by LiuZeng520** [comment]
I hope someone can help me, thank you very much.

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the Elasticsearch forum. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Regarding your issue the error message says that you should use `POST` and not `PUT` to update a setting so I hope you don't mind that I close this.
