### ISSUE TITLE
API to pause auto-follow patterns

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#46665]
When using a bi-directional cross-cluster replication scheme, the supported method of upgrading the two clusters is to [pause index following, and then perform a rolling upgrade on both clusters](https://www.elastic.co/guide/en/elastic-stack-overview/current/ccr-upgrading.html#_bi_directional_index_following). However, while performing these upgrades, auto-follow patterns could continue to run creating new indices and starting replication, leading to problems during the rolling upgrades.

Therefore, there needs to be ability to pause auto-follow patterns, and then the ability to resume them after the rolling upgrade is complete. These would be via API calls.

**Comment by tlrx** [comment]
I opened #47510 as a proposal for the implementation.

**Comment by tlrx** [comment]
This API has been implemented in #47510, documented in #47985 and can be used already using the Java High Level REST Client (some examples in #47989).
