### ISSUE TITLE
[DOCS]  Use shared "stack" version file in elastic/docs for docs version bumps

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#46687]
As part of every release, ES tech writers or the docs release manager must update version-related attributes in two separate files:

- A [stack version file](https://raw.githubusercontent.com/elastic/docs/master/shared/versions/stack/master.asciidoc) in the elastic/docs repo
- The [`$ES_REPO_ROOT/doc/Versions.asciidoc` file](https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/Versions.asciidoc) in the elastic/elasticsearch repo

This is not DRY. It duplicates effort and increases the likelihood of error.

Instead, docbooks generated from the elastic/elasticsearch repo should use the shared stack version file in the elastic/docs repo.

As the elastic/docs repo is already required to build any docbooks, this would not introduce any new repo-cloning requirements. The process for building Elasticsearch dobooks would not change.

Relates to elastic/docs#804.

## Proposed plan

1. Include the stack version file in the `$ES_REPO_ROOT/doc/Versions.asciidoc` file. As of writing, this impacts the following docbooks:

    * [ Java REST Client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/index.html)
    * [Painless Scripting Language](https://www.elastic.co/guide/en/elasticsearch/painless/master/index.html)
    * [Elasticsearch Plugins and Integrations](https://www.elastic.co/guide/en/elasticsearch/plugins/master/index.html)
    * [Elasticsearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/master/index.html)

2. Remove the following attributes from the `$ES_REPO_ROOT/doc/Versions.asciidoc` file, back to the last supported version:
    * `version`, which displays the current Elasticsearch version in several example snippets
    * `bare_version`, which is used similarly to the `version` attribute but does not include `-alpha` or `-beta`
    * `major_version`, which is the `version` in a n.x format (e.g. 7.x)
    * `prev-major-version`, which is the laster `version` in a n.x format (e.g. 7.x)
    * `branch`, which is used during the doc build
    * `release-state`, which determines whether a [preliminary note](https://github.com/elastic/docs/blob/master/lib/ES/Book.pm#L22) displays.

Going forward, docs release managers will update these attributes in the appropriate 
stack version file as part of the release process.

ES dev release managers will continue updating the Elasticsearch `Versions.asciidoc` file as today.

**Comment by lcawl** [comment]
For the record, step 1 is already done.  e.g. https://github.com/elastic/docs/blob/master/shared/versions/stack/6.8.asciidoc

**Comment by jrodewig** [comment]
Thanks @lcawl. I'll remove that step from the description.
