### ISSUE TITLE
Execution failed for task ':qa:rolling-upgrade:v6.8.4#twoThirdsUpgradedTestCluster#wait'.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#46698]
```
15:35:35 * What went wrong:
15:35:35 Execution failed for task ':qa:rolling-upgrade:v6.8.4#twoThirdsUpgradedTestCluster#wait'.
15:35:35 > Failed to locate seed node transport file [/var/lib/jenkins/workspace/elastic+elasticsearch+7.4+EAR/qa/rolling-upgrade/build/cluster/v6.8.4#twoThirdsUpgradedTestCluster node0/elasticsearch-7.4.0-SNAPSHOT/logs/transport.ports]: timed out waiting for it to be created after 40 seconds
```

Reproduces locally with:
```
./gradlew :x-pack:qa:rolling-upgrade:v6.8.4#bwcTest
```

Build
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.4+EAR/13/console
Build Scans: https://gradle-enterprise.elastic.co/s/uicivttvur5hghttps://gradle-enterprise.elastic.co/s/zng2dqwa5hl5uhttps://gradle-enterprise.elastic.co/s/ygfslicsf6hfg

**Comment by atorok** [comment]
All projects use testclusters now that offers more flexibility around timeouts. 
We didn't see failures like this since then.
