### ISSUE TITLE
The index pattern syslog-pfsense-* does not contain any of the following compatible field types: geo_point

### ISSUE THREAD

**Issue by crakerkai** [elastic/elasticsearch#46696]
Hi Everyone,

Today, I try to create Coordinate Map but unsuccessfully, this issues is describe in below
![image](https://user-images.githubusercontent.com/16294734/64855474-29e04b80-d64a-11e9-93a6-705f9460a791.png)
And this is parsing rule in logstash
![image](https://user-images.githubusercontent.com/16294734/64855773-d02c5100-d64a-11e9-8732-2abda7c3bef8.png)
Please help me to fix issue in order to create map dashboard.

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.
The Kibana or logstash forums may be more relevant than elasticsearch in this case.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
