### ISSUE TITLE
Cache estimated sizes of per-segment per-field field data to short-circuit circuit breaker

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#4672]
It could be helpful to have something like a `Map<SegmentReader.CoreCacheKey|FieldName, Long>` cache so that multiple requests all attempting to load field data for the same field can first check to see whether the there is enough space for the data, and short-circuit if not.

This should help for multiple requests so we don't have to continually estimate if we know it's going to break regardless.

**Comment by clintongormley** [comment]
In memory fielddata is going to be removed for all fields that support doc values.  I think we can close this one.
