### ISSUE TITLE
Invalid '?' in query when using word_delimiter_graph

### ISSUE THREAD

**Issue by null-pointer-byte** [elastic/elasticsearch#46722]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.3.2, Build: default/tar/1c1faf1/2019-09-06T14:40:30.409026Z, JVM: 12.0.2

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "12.0.2" 2019-07-16

**OS version** (`uname -a` if on a Unix-like system):
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
When `word_delimiter_graph` is used and any token is removed by subsequent filters, the query containing a `PhraseQuery` from the produced tokens emits an invalid `?` in place of the removed token.

**Steps to reproduce**:

1. Create an index with below mappings.
```
PUT /my-index HTTP/1.1
Host: localhost:9200
Content-Type: application/json

{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "analysis": {
            "filter": {
                "english_stop": {
                    "type": "stop",
                    "stopwords": "_english_"
                },
                "my_delimiter": {
                    "type": "word_delimiter_graph"
                }
            },
            "analyzer": {
                "my_analyzer": {
                    "tokenizer": "whitespace",
                    "filter": [
                        "my_delimiter",
                        "lowercase",
                        "english_stop"
                    ]
                }
            }
        }
    },
    "mappings": {
        "properties": {
            "title": {
                "type": "text",
                "analyzer": "my_analyzer"
            }
        }
    }
}
```

2. Query the validate API to get the parsed query.
```
GET /my-index/_validate/query?explain HTTP/1.1
Host: localhost:9200
Content-Type: application/json

{
    "query": {
        "match_phrase": {
            "title": {
                "query": "stripAndHtml"
            }
        }
    }
}
```

3. Actual response contains an invalid `?` where `And` was removed from the tokens emitted by `word_delimiter_graph`.
```
{
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "valid": true,
    "explanations": [
        {
            "index": "my-index",
            "valid": true,
            "explanation": "title:\"strip ? html\""
        }
    ]
}
```

Expected response should be:
```
{
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "valid": true,
    "explanations": [
        {
            "index": "my-index",
            "valid": true,
            "explanation": "title:\"strip html\""
        }
    ]
}
```

Verified on v7.3.2 as well as master branch, got the same issue.

**Comment by jimczi** [comment]
This is expected, the `?` is not a term but an indication that there is a gap between `strip` and `html` due to the removal of `and`. This means that the phrase query will match documents that contain `strip` and `html` only if they are one positions apart (one term must appear between them). As such I hope you don't mind that I close this issue, please open a discussion in our [forum](https://discuss.elastic.co/c/elasticsearch) if you have further questions since we reserve github for verified bugs and feature request.
