### ISSUE TITLE
ElasticSearch - Spring Boot - Upsert is throwing DocumentMissingException

### ISSUE THREAD

**Issue by yatendragoel** [elastic/elasticsearch#46727]
**Elasticsearch version**: Version: 6.4.3, Build: default/tar/fe40335/2018-10-30T23:17:19.084789Z, JVM: 1.8.0_191

**Plugins installed**: None

**JVM version**: java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version**: Darwin Yatendras-MacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

**Issue Description**:
I am using Spring Boot and ElasticSearch. When I am trying to upsert using Spring, it is throwing `DocumentMissingException` when there is no document present in the ElasticSearch. The same code works fine when there is a document present in the ElasticSearch.

**Code**:

    public <S extends Company> void saveAllCustom(Iterable<S> companies) {

        List<UpdateQuery> updateQueries = new ArrayList<UpdateQuery>();

        ObjectMapper oMapper = new ObjectMapper();

        for (S company : companies) {

            Map<String, Object> companyJsonMap = (Map<String, Object>) oMapper.convertValue(company, Map.class);

            Map<String, Object> paramsDocument = new HashMap<String, Object>();
            paramsDocument.put("doc", companyJsonMap);

            Script script = new Script(
                ScriptType.INLINE
                , "painless"
                , "if (ctx._source.dataAsOf < params.doc.dataAsOf) {ctx._source = params.doc}"
                , paramsDocument);

            UpdateRequest updateRequest = new UpdateRequest()
                .index("company")
                .type("_doc")
                .id(company.cin)
                .script(script) // Conditional Update
                .upsert(companyJsonMap);

            UpdateQuery updateQuery = new UpdateQueryBuilder()
                .withIndexName("company")
                .withType("_doc")
                .withId(company.cin)
                .withDoUpsert(true)
                .withClass(Company.class)
                .withUpdateRequest(updateRequest)
                .build();

            updateQueries.add(updateQuery);

        }

        elasticsearchTemplate.bulkUpdate(updateQueries);
    }

**Logs**:
org.springframework.data.elasticsearch.ElasticsearchException: Bulk indexing has failures. Use ElasticsearchException.getFailedDocuments() for detailed messages [{U65929AR1978SGC001748=[company/vteSxfKoRF-k4g982vissw][[company][2]] DocumentMissingException[[_doc][U65929AR1978SGC001748]: document missing], U45309AR2000PTC006288=[company/vteSxfKoRF-k4g982vissw][[company][3]] DocumentMissingException[[_doc][U45309AR2000PTC006288]: document missing],...

**But a similar upsert command is working using CURL:**

    curl -X POST "localhost:9200/company/_doc/10001/_update" -H 'Content-Type: application/json' -d'
    {
        "script": {
            "lang": "painless",
            "source": "ctx._source = params.doc",
            "params": {
                "doc": {
                    "name": "XYZ LIMITED - updated",
                    "cin": "10001"
                }
            }
        },
        "upsert" : {
            "name": "XYZ LIMITED - newly created",
            "cin": "10001"
        }
    }'

As per my understanding, when there is no document present in the ElasticSearch, it shouldn't throw a `DocumentMissingException` because I have added `upsert(...)` as well in the query.

Please let me know if anything else is needed from my end.

**Comment by yatendragoel** [comment]
I submitted the same issue first in the discussion forum [ElasticSearch Discussion Forum](https://discuss.elastic.co/t/upsert-is-throwing-documentmissingexception/199307) to see if this is actually a bug or is there something I am missing

**Comment by consulthys** [comment]
Note that this is not an Elasticsearch issue but a Spring Data ES one.

See: https://stackoverflow.com/a/57986771/4604579

**Comment by javanna** [comment]
Thanks @consulthys for commenting. This does seem like an Elasticsearch issue indeed. Please could you report it upstream @yatendragoel ?

**Comment by yatendragoel** [comment]
Hi @javanna,

If this is an Elasticsearch issue, then is there any particular reason for closing this?

**Comment by consulthys** [comment]
@yatendragoel I think @javanna wanted to say "This does **not** seem..." ;-)

**Comment by yatendragoel** [comment]
@consulthys yes, even I thought so... just wanted a confirmation from him :)

**Comment by javanna** [comment]
Sometimes I just write the opposite of what I am thinking, but thanks both
of you for reading between the lines :)
