### ISSUE TITLE
Watcher http mustache support

### ISSUE THREAD

**Issue by BFLB** [elastic/elasticsearch#46733]
Watcher http input and webhook action do not fully support mustache templating. Please add mustache support for at least the following fields: 
- scheme
- host
- port

With mustache support these settings could be done in metadata and thus simplify configuration of complex watches.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
