### ISSUE TITLE
Add pre-indexed shape support to geo-polygon query

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#46730]
Kibana puts Elasticsearch filters in the URL. Geo-polygon queries can be very long when the polygon contains lots of vertices. This can cause problems where the URL exceeds the allowable limit, as explained in https://github.com/elastic/kibana/issues/45521.

The Kibana Maps application would like to solve this problem by using [pre-indexed shape](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_pre_indexed_shape) in both geo-shape queries and geo-polygon queries. The problem is that geo-polygon does not support pre-indexed shapes like geo-shape query does.

**Comment by iverase** [comment]
Hi @nreese ,

One of there ideas we are trying to achieve is to be able to perform geo_shape queries on top of geo_point fields. There is still some work to at Lucene level as well as defining the behaviour for different spatial operations.

**Comment by iverase** [comment]
This can be closed as now geo_shape queries can be used with geo_point fields.
