### ISSUE TITLE
Lowercase_terms not in term suggester

### ISSUE THREAD

**Issue by lilysikes** [elastic/elasticsearch#46761]
GET _search
{
  "query" : {
    "match": {
      "body": "hllo"
    }
  },
  "suggest" : {
    "my-suggestion" : {
      "text" : "hllo",
      "term" : {
        "field" : "body",
        "lowercase_terms": false
      }
    }
  }
}

This query gives this error:{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "suggester[term] doesn't support field [lowercase_terms]",
        "line": 12,
        "col": 28
      }
    ],
    "type": "parsing_exception",
    "reason": "suggester[term] doesn't support field [lowercase_terms]",
    "line": 12,
    "col": 28
  },
  "status": 400
}

When I look through the code it doesn't appear to support the lowercase_terms option, but it is in the reference for suggest as an option for term suggester.

**Comment by jrodewig** [comment]
Thanks for raising this @lilysikes. I've opened PR #46879 to address.
