### ISSUE TITLE
[ML] How to handle job tasks that have no matching config

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#46781]
If an ML persistent task (anomaly detector, datafeed or analytics) is in cluster state and the `.ml-config` index somehow disappears (user error, data node failure, etc.), then we find ourselves in a state where those tasks have no matching config. This renders many of the APIs useless as they would complain there is no such job/datafeed. In addition, it is unclear what to do for the jobs in terms of memory tracking.

Note that for short temporary losses of the config index, we probably wouldn't want to stop the task entirely, as it would mean the user has to manually restart it after the data problem is resolved.

**Comment by benwtrent** [comment]
It seems to me the big issue is a more permanent loss of the index but still being able to stop running datafeeds, analytics, or jobs.

If the index has "gone away", are users still able to stop the tasks without utilizing the tasks API?

**Comment by dimitris-athanasiou** [comment]
No, we rely on having the index around so that we can resolve expressions. Thus, at the moment, you could not stop those tasks using their relevant APIs.

**Comment by benwtrent** [comment]
It seems prudent for us to provide a fallback for when the index is gone, but the user wants to close the job. Maybe expand the IDs given the list of persistent task ids?

🤔

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/51888 allows for jobs and datafeeds to be closed/stopped when the config is missing.

**Comment by dimitris-athanasiou** [comment]
https://github.com/elastic/elasticsearch/pull/56360 allows for DF Analytics jobs to be stopped when their config is missing.

**Comment by dimitris-athanasiou** [comment]
ML tasks are now allowing stopping when the config is missing.

In addition, upcoming improvements on hidden indices will mean the config index is more restricted.

If we're missing something it's visibility in that there is a running task whose config is missing. Do you think it'd be worth looking into how we'd expose this?

**Comment by benwtrent** [comment]
Honestly, I don't think anything more needs to be done here. 

Moving configs to system indices removes the obvious issue of users deleting docs directly. If zombie tasks become a bigger issue, we can return them in _stats or something and indicate they are running without configs.
