### ISSUE TITLE
Support max_doc_count: 0 for RareTerms

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#46787]
The `terms` agg has an interesting property/trick of setting `min_doc_count: 0`, which lets you see what terms in the index _did not_ have any documents for that aggregation.  This is potentially useful if you have a query excluding a known set of documents and you want to see what keywords/terms are not in the leftover docs.

The problem is that to accurately collect those "missing" terms, you need to also collect all the other terms with a large `size`.  In contrast RareTerms is made for this long-tail, and I don't see a technical problem supporting it.  Just need a tweak to scan the terms dictionary in that scenario like terms agg does

**Comment by Thlamz** [comment]
Hey @polyfractal I don't know if this is still a wanted change but I will be submitting a Pull Request soon

**Comment by polyfractal** [comment]
Heya @Thlamz, I think this is still a useful feature to add.  I'll take a look at the PR tomorrow :)

**Comment by Thlamz** [comment]
> Heya @Thlamz, I think this is still a useful feature to add. I'll take a look at the PR tomorrow :)

@polyfractal Great, thanks!

**Comment by not-napoleon** [comment]
I'm marking this for team discuss.  We're not sure we want to encourage additional use of `max_doc_count: 0` in general at this point.
