### ISSUE TITLE
Failures waiting for :qa:smoke-test-client test cluster to start on 7.x and 7.4

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#46798]
We've seen an increasing number of build failures related to the `:qa:smoke-test-client:integTestCluster#wait` task timing out, specific to the 7.x and 7.4 branches. This seems to have started about a week ago.

![image](https://user-images.githubusercontent.com/4106672/65084145-31139c00-d95f-11e9-80a6-150786b4660f.png)

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=non_verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:qa:smoke-test-client:integTestCluster%23wait%27.%0A*&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.rootProjectName=elastic%2Belasticsearch%2Bpull&search.startTimeMax=1568758728727&search.startTimeMin=1566284400000&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-420

@atorok Do you recall any changes to test cluster stuff specifically for 7.x?

**Comment by mark-vieira** [comment]
Just realizing this is still `ClusterFormationTasks`. So I guess the other question is whether we have an outstanding backport PR to convert this project to test clusters which might also solve this problem.

**Comment by atorok** [comment]
We do,  it's #45654 and then one more pending back-port, but we need #46740 first

**Comment by mark-vieira** [comment]
Cool, let's leave this open for now anyhow as posterity for folks on test triage.

**Comment by dweiss** [comment]
Would this affect v7.3.2 too? I tried to upgrade https://github.com/carrot2/elasticsearch-carrot2 to v7.3.2 and it stalls on integTestCluster.wait (different machines, same result).

**Comment by mark-vieira** [comment]
@dweiss It might be a different issue. We've observed this happening in our CI mainly with the 7.x and 7.4 branches. If you could provide a Gradle build scan for the issue you're seeing that might help us troubleshoot.

**Comment by dweiss** [comment]
Hi Mark. You can clone that repo and run gradlew check, actually. Happens for me every time (linux, windows - doesn't matter).

https://scans.gradle.com/s/k4ndb3nak7rpk

**Comment by dweiss** [comment]
I think I found the problem - some of the internal infrastructure has changed and configurations are different -- 
https://github.com/elastic/elasticsearch/pull/41864/files

I'll dig, although it's really painful to go through commits and diffs every single time...

**Comment by dweiss** [comment]
I fixed the problem -- false alarm (at least in my case). Thanks Mark.

**Comment by mark-vieira** [comment]
This is no longer an issue.
