### ISSUE TITLE
slow query when time range  cross a few days, aggs cache is not effective

### ISSUE THREAD

**Issue by fengyong** [elastic/elasticsearch#46800]
grafana --- es (3 nodes)
i need to query percentiles over massive records, and the time range over 2 weeks ,like  30 days.
the query is quite slow, es cache doesn't work well. 
it takes about 30 seconds for a particular query.
i have to develop a reverse proxy of grafana for es data source, to devide a long range request to multiple requests per day, then combine responses, so es will cache the result, it works as a charm，reduce the query time from 30 seconds to about 2 seconds,  but still not perfect. 
it has to merge json body of responses and not suitable for complicate scenes.
is there an official plan to accelerates query over long time range?

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by fengyong** [comment]
> his allows us to use GitHub for verified
> bug reports, feature requests, and pull re

thanks for your reply, i will look around in the forum for
