### ISSUE TITLE
Improve documentation for deprecation logging

### ISSUE THREAD

**Issue by juliank** [elastic/elasticsearch#46808]
The documentation for how to enable deprecation logging could be improved.

We're in the process of planning an upgrade of Elasticsearch from 6.8 to 7.x, and in this process we came across deprecation logging. According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/logging.html#deprecation-logging) it appears to be quite simple, that by only setting the single property `logger.deprecation.level = warn` you'll get a separate file with all your deprecation logs:

> This will create a daily rolling deprecation log file in your log directory.

We are running the Elastic stack using the Docker images, and in this case it was not as straight forward. [See this thread](https://discuss.elastic.co/t/how-to-enable-deprecation-logging-in-elasticsearch-6-8/197550/7) for the issues we faced, as well as the solution.

At least a note in the documentation, that you would have to dig a bit deeper when running the Docker images, would have been quite helpful.

**Comment by javanna** [comment]
Thanks for opening this issue @juliank , would you be up for opening a pull request with the desired docs changes?

**Comment by pgomulka** [comment]
@juliank just to let you know, since 7.0 you should be able to see JSON deprecation logs on the docker console. All log streams (server, deprecation, slow logs) are combined on the console, but they all have corresponding `type` field so you should be able to distinguish them.
There was some more improvements related to audit logging in 7.3

https://github.com/pgomulka/elasticsearch/blob/8aa18ecd8eaed7cdbc2cc3bed755364fa59f39f6/distribution/docker/src/docker/config/log4j2.properties

**Comment by juliank** [comment]
@javanna: Since I've barely started to scratch the surface of the Elastic stack, I'm probably not your best bet, but I can give it a try. It shouldn't be too big an adjustment anyhow.

@pgomulka: As there has been changes to the logging in 7.0, should I open a pull request on the 6.8-branch, since that was where we faced the issue? Or should I try to make a generic change to the documentation on master, which could then be merged back into previous versions if needed?

**Comment by pgomulka** [comment]
@juliank if you could aim for 6.8 branch that would be great. 
In 7.0 the default configuration is JSON logging and the configuration would slightly differ. Obviously if you notice that in 7.0 or master the doc could be improved too, let us know!
thank you very much for your contribution!

**Comment by javanna** [comment]
go for it @juliank we will assist you with your PR, it will be fine ;)

**Comment by debadair** [comment]
[docs issue triage]

**Comment by juliank** [comment]
Just as a small notice: I haven't had the time to properly set up the required development environment to contribute a PR, so for anybody else that might be keeping an eye on this, please feel free to pick it up.

**Comment by pgomulka** [comment]
@juliank for documentation changes you can modify and create a PR from the documentation page itself. We will then run the test on the PR itself
