### ISSUE TITLE
snapshot-tool tests break --parallel builds

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#46813]
These tests use fixtures from the repo such as:
```
thirdPartyTest.dependsOn(':plugins:repository-gcs:qa:google-cloud-storage:createServiceAccountFile',

            ':plugins:repository-gcs:qa:google-cloud-storage:googleCloudStorageFixture')
    thirdPartyTest.finalizedBy(':plugins:repository-gcs:qa:google-cloud-storage:googleCloudStorageFixture#stop')
```

This doesn't fail in PR and intake build since one project is in part 1 and the other in part 2 but start to fail as soon as one runs everything in a single  run  with `--parallel` 

Since we have tests in CI that run against real repositories, I am going to mute this failure to be able to move forward with running all jobs on CI in parallel. 

//cc @andrershov

**Comment by atorok** [comment]
I think the proper fix here is to extract dedicated test fixture projects e.x. `tests/fixture/gcp`  and  `tests/fixture/s3`, have the source code  for the fixture there and dockerize it so we can have two docker-compose services running one for each project that want to run it's tests.

**Comment by atorok** [comment]
Muted on master bfdbb8742ad and 03832328d51

**Comment by original-brownbear** [comment]
I'm closing this, the snapshot tool has already been removed from `master` and can probably also be removed from `7.x` (looking into that) => no point in working on this any more.
