### ISSUE TITLE
testingConventions  up-to date checks are not working properly 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#46815]
This failed in CI : https://gradle-enterprise.elastic.co/s/ihu3sw6nza3jq 
after it passed locally. 

I have ran `precommit` then disabled a task, then ran it again.

Could be that we are not tracking the state of tasks as input ?

**Comment by mark-vieira** [comment]
> Could be that we are not tracking the state of tasks as input ?

That is most definitely it. This task implementation is pretty unique in the way that it's influenced by other tasks' configuration. I'll create a PR for this.
