### ISSUE TITLE
Percolator degraded performance 7.2

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#46831]
We are migrating from 1.7 to 7.2 ES

Our use case of percolator is pretty simple. We have around 120K percolators spread on a 5 node cluster. Percolator docs have meta fields that lets us filter out unnecessary queries that are surely not going to match [1.7 had an explicit support for filtering in the percolator API, In 7.2 we have to make use of bool query]

The index has 48 shards. We have allocated 8GB of heap giving the Young Gen 6GB [we saw the usage of Old gen is our previous cluster to be zero]. The machine has 15GB of RAM. We use the G1GC collector [default] and haven't tweaked anything [we made use of the ParNewGC for 1.7]. Number of GC that happen per minute is ~40 and take around 200ms. We do see a XX:MaxGCPauseMillis setting in the JVM which is defaulted to 200ms. Anything to do with this? I've also heard that G1GC doesn't work well with smaller heaps [it's good with >10GB]

Anyways,

What I want to know is that how does ES optimise queries on its end? And how much does ordering of filters matter? [we did benchmarking with filter ordering and did see a bit of benefit but not much really at peak time]. This is how we do percolation

    {
      "query": {
        "bool": {
          "filter": [
             { "term": { "domain": <> } },
             { "percolate": { } }
         ]
       }
     }
    } 

We keep the domain filtering before in the hopes that ES will filter out unnecessary percolation

One other significant change we've done in the ES queries was the below

    {
       "query":  {
              "bool": {
                  "filter": [
                     { "term": { ... } },
                     { "term": { ... } },
                     { "term": { ... } }
                  ]
               }
         }
    } 

now looks like

    {
       "query":  {
              "bool": {
                  "filter": [
                     { "bool { "filter": { "term": { ... } } } },
                     { "bool { "filter": { "term": { ... } } } },
                     { "bool { "filter": { "term": { ... } } } }
                  ]
               }
         }
    } 

This just simplified ES query creation from our home grown logic spec. But does having unnecessary bools affect the way queries are executed by Lucene? I heard ES has done some sort of intermediate representation of queries, so I'm guessing it optimises certain things? What exactly would they be? Most of our queries are either term queries or match queries on keywords/text/numbers/booleans/dates

Other common settings like memorylock are all in place. This cluster is exclusively for percolation only so no other traffic. Our traffic is around 200 QPS

**Comment by fhalde** [comment]
System metrics

Load average always hovers at 1 which is not a good sign
Does percolator do any IO?

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests. 

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this. If we can determine that there has been a performance regression in Percolator, then we can reopen this issue.
