### ISSUE TITLE
Searching for a same term in both the clauses with SpanNear query is returning results when in_order is false

### ISSUE THREAD

**Issue by dileep2614** [elastic/elasticsearch#46836]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
If a document has a term say "using" only once, upon searching using span_near query with both the clauses having span_term for using "using" is returning the document. 
**Steps to reproduce**:
Following are the sense queries which I used to reproduce the issue.
 1.  Creating a test index
```
PUT test_index
{
   "settings": {
      "number_of_shards": 1
   },
   "mappings": {
      "type1": {
         "properties": {
            "field1": {
               "type": "text",
               "analyzer": "english"
            }
         }
      }
   }
}
```
 2. Indexing a document
```
PUT test_index/type1/doc3
{
   "field1": "abc def def"
}
```
 3. Searching for it
```
POST test_index/type1/_search
{
    "query": {
      "span_near": {
         "clauses": [
            {
               "span_term": {
                  "field1": "abc"
               }
            },
            {
               "span_term": {
                  "field1": "abc"
               }
            }
         ],
         "slop": 10,
         "in_order": false
      }
   },
    "highlight": {
        "fields": {
            "field1":{
                "type": "unified"
            }
        }
    }
}

```
**If the in_order property is set to true, it doesn't return any result.**
I guess that's not the expected behavior?

**Comment by javanna** [comment]
heya @romseygeek could you have a quick look? Would you expect the described behaviour?

**Comment by romseygeek** [comment]
It's a known issue with Spans: https://issues.apache.org/jira/browse/LUCENE-5396

There's a fix for Intervals, but it's not exposed in ES yet: https://issues.apache.org/jira/browse/LUCENE-8828

**Comment by romseygeek** [comment]
The fix for intervals has been in ES for a while now.  We should probably look again at just deprecating spans and recommending people use intervals instead?

**Comment by benwtrent** [comment]
We are deprecating spans and moving towards intervals. https://github.com/elastic/elasticsearch/issues/110491
