### ISSUE TITLE
[Feature request] Add possibility to append search results to SlowLog

### ISSUE THREAD

**Issue by machine424** [elastic/elasticsearch#46843]
**Describe the feature**:

I don't know if there is another way to get readable requests/responses logs, without stressing out ES, with dynamic configuration.

Here we add the total number of hits to the SlowLog message:

https://github.com/elastic/elasticsearch/blob/769ff81548869ffd02d70bdba5b25c80ffa386e5/server/src/main/java/org/elasticsearch/index/SearchSlowLog.java#L167

It could be useful to add more data; the content of the hits, a part of it (it should be always the same), a hash of the response if the order doesn't change ...

We can do it via some settings:
"index.search.slowlog.also_hits": "true" for example

I need to gather search requests and responses to do some log replaying for some tests. I cannot assemble this data on the ES's client side, I'm forced to do it on ES cluster. (and there are a lot of settings and possibilities "rootLogger." , "logger.searchguard.", "appender.rolling." ,"index.search.slowlog.")

**Comment by javanna** [comment]
hi @machine424 thanks for opening this feature request. I can already comment that adding the hits to the slowlog will probably not be a good idea, but we will discuss this general idea of enriching the search slowlog with the team, just to check and see if there's anything we can do to improve things on this end.

**Comment by machine424** [comment]
Thanks for your response, actually all I need is a place where I can find all requests ( for all APIs actually) and their responses that the cluster had received, I don't want the logging to be very verbose. Is there a way to do so without using slowlogging ?

**Comment by javanna** [comment]
@machine424 I am not clear on whether this is only about search API or any API. 

What do you mean with "responses that the cluster received"? You mean responses that the cluster has returned?

Also, I don't follow how you can keep logging not so verbose if you need to dump all requests and responses into it? :)

**Comment by machine424** [comment]
@javanna, As I mentioned, for all APIs will be great.

I was talking about the requests, I don't need other actions that the cluster takes in the logs; only requests and associated responses. I don't know if it's possible

**Comment by javanna** [comment]
This is a very different request compared to the initial one, I am not aware of a way to do this for all APIs within Elasticsearch, and it's a question better suited for our forums at https://discuss.elastic.co/ . If you use any of our language clients to send requests to Elasticsearch, it is pretty easy to enable requests and response logging, every client supports that feature.
