### ISSUE TITLE
Wrong averageFieldLength(avgdl, average length of field) and fieldLength (dl, length of field) calculation 

### ISSUE THREAD

**Issue by AshishKumarUpadhye** [elastic/elasticsearch#46855]
I have created new index in Elastic Search 7.3.2 version ( "lucene_version" : "8.1.0") .
With following details:
INDEX created using the below details:
**FILTER**
--------------------------------------------------------------------------------------------------
 "skillset_synonyms_filter": {
          "type": "synonym_graph",
          "synonyms": [
            "c-sharp,c sharp",
            ".net,mvc,core, asp.net,winservice",
            "sql,structured query language,dba,database,backend",
            "javascript,js"
          ]
},
"my_stopword_filter": {
          "type": "stop",
          "stopwords": [
            "a","an","and","are","as","at","be","but","by","for","if","in","into","is","it","no","not","of","on","or",
            "such","that","the","their","then","there","these","they","this","to","was","will","with"
          ]
        },
**ANALYZER**
-----------------------------------------------------------------------------------------------
"analyzer": {
        "my_synonym_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "skillset_synonyms_filter",
            "my_stopword_filter"
          ]
        }
----------------------------------------------------------------------------------------------
and also I have added the data into the index like this
1]skills -.NET,MVC,SQL,WEB API
2]skills -.NET,MVC,SQL,WEB API
3]skills -javascript
4]skills-java
5]skills-SQL
6]skills:.NET,.NET MVC,.NET Core,SQL,WEB API
so in this the 1st and 2nd record the skillset is the same.
-------------------------------------------------------------------------------------------------
my query to fetch the record like this:
{
  "explain": "true",
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "skills": {
              "query": "sql"
            }
          }
        }
      ]
    }
  }
}
---------------------------------------------------------------------------------------------
So i am getting the correct result set but i am not getting how the  tf getting calculated.
Means **I am getting the  "length of field" (dl)=3 And "average length of field " (avgdl)= 13.666667
which is confusing, So anyone could you please help me with this.**

Here is the Details:
{
"value": 0.66775244,
"description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
"details": [
{
"value": 1,
"description": "phraseFreq=1.0",
"details": [ ]
}
,
{
"value": 1.2,
"description": "k1, term saturation parameter",
"details": [ ]
}
,
{
"value": 0.75,
"description": "b, length normalization parameter",
"details": [ ]
}
,
{
"value": 3,
"description": "dl, length of field",
"details": [ ]
}
,
{
"value": 13.666667,
"description": "avgdl, average length of field",
"details": [ ]
}
]
}
-----------------------------------------------------------------------------------------------
Thanks.

**Comment by jimczi** [comment]
Hi @AshishKumarUpadhye, `dl` is the field length for the document so the number of terms that it contains, we call it the norm of the field. `avgdl` is the average length of  the field among all documents in the shard. This value is used to compute the final `BM25` score as explained in the output. 
Please note that we reserve github for verified bugs and feature requests so I hope you don't mind if I close this issue. If you have further questions please use the [discuss forum](https://discuss.elastic.co/) which is more suited for this type of request.

**Comment by AshishKumarUpadhye** [comment]
Thanks jimczi.
Its still confusing,so i have added the same with different scanario into the discuss forum.

Thanks.
