### ISSUE TITLE
AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles fails with AssertionError: Count is 7961 hits but 13205 was expected

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#46854]
## Example build failure

https://gradle-enterprise.elastic.co/s/sejaaz3cnniii/tests/lgycqkw2bfw46-kndg2ibqwghd6
https://gradle-enterprise.elastic.co/s/sejaaz3cnniii/tests/lgycqkw2bfw46-kndg2ibqwghd6

```
:plugins:repository-azure:testorg.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests » testSnapshotWithLargeSegmentFiles (15.875s)
java.lang.AssertionError: Count is 7961 hits but 13205 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:Close stacktrace
at __randomizedtesting.SeedInfo.seed([E4E9171EE3E6EDB:19749B8C70A43AA5]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:254)
at org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles(AzureBlobStoreRepositoryTests.java:134)
```

**Comment by tlrx** [comment]
Thanks @atorok. This should have been fixed by https://github.com/elastic/elasticsearch/pull/46802, can you please check that this build contains the commit (I did not find it in the Gradle scan)?

**Comment by atorok** [comment]
I think indeed these are old commits. The scan is local so it doesn't have a hash, but I don't think it has the change from your PR. 
CI caught this https://gradle-enterprise.elastic.co/s/7wnckmqr4p4v6/tests/lgycqkw2bfw46-kndg2ibqwghd6 too but that seems older too

**Comment by tlrx** [comment]
> CI caught this https://gradle-enterprise.elastic.co/s/7wnckmqr4p4v6/tests/lgycqkw2bfw46-kndg2ibqwghd6 too but that seems older too

Yes I saw a similar failure (maybe not this exact one) but I already had an approved PR fixing the issue at that time, so I did not feel the need to open an issue and closed it 2 hours later. Maybe should I have

**Comment by tlrx** [comment]
Anyway, sorry for the noise.

**Comment by atorok** [comment]
@tlrx I think that's a resolvable assumptions. Most of time most people won't run into it, so I don't think we need to spend time on a ticket in cases like this. 
I happen to be running multiple jobs in a loop so i'm prone to find these, and it's important for me to be able to discriminate existing issues, flaky tests  from problems introduced by me changing the setup in how we  run these jobs ( ex. more in parallel multiple cpu cores etc ) so feedback on issues is important.
