### ISSUE TITLE
Improve documentation for debian installation

### ISSUE THREAD

**Issue by jillesvangurp** [elastic/elasticsearch#46868]
The documentation for installing the debian/ubuntu package suggests running:

```bash
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
```

We added this to our chef scripts and this of course runs a lot and ends up appending the same line over and over again. This slows down apt-get operations to the point where it is unusable. When I checked the file it had 500+ lines already.

I would suggest changing this to:

```
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
```

without the `-a` or to:

```
echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list
```

The one issue I can see with this approach is if there is a usecase for this file to contain more than one line. In that case, maybe use separate files for each entry.

Note. created the ticket after discussion here: https://discuss.elastic.co/t/minor-problem-with-documentation-for-es-debian-installation/200172

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.
