### ISSUE TITLE
Enhance documentation around DLS templated role query

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#46878]
We have the option to construct the DLS (Document Level Security) query from the index privilege, using parameters from the user metadata.
This is what we currently document:
https://www.elastic.co/guide/en/elastic-stack-overview/current/field-and-document-access-control.html#templating-role-query

I would like to see examples for how to reference values from `_user.metadata` or lists from `_user.groups` . How do we handle missing values?

**Comment by wchrisdean** [comment]
[doc issue triage]
NOTE: New version of this https://www.elastic.co/guide/en/elasticsearch/reference/7.4/field-and-document-access-control.html - does include example for `_user.metadata`, but does not have `_user.groups`example.

**Comment by jrodewig** [comment]
Closing as this has been addressed by #62257 and other updates. We now show users how to access metadata and arrays/objects in the docs:

https://www.elastic.co/guide/en/elasticsearch/reference/master/field-and-document-access-control.html#templating-role-query
