### ISSUE TITLE
Need to re-name RPM name from test1.rpm to test.rpm without deleting test1.rpm

### ISSUE THREAD

**Issue by saiprathapreddy** [elastic/elasticsearch#46899]
**re-name RPM name from test1.rpm to test.rpm without deleting test1.rpm**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: [Maven] pom.xml

**JVM version** (`java -version`):  

**OS version** (`uname -a` if on a Unix-like system):  

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Need to re-name RPM name from test1.rpm to test.rpm without deleting changing content of test1.rpm. please share the maven plugin to do that.

Expectation: 
 1. test1.rpm has three files 1.txt,2.txt and 3.txt. now i need to rename the rpm name to test.rpm  and test.rpm should contain 1.txt,2.txt and 3.txt.  
 2. Is there any other way to re-name the rpm without deleting old rpm-name.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This does not look related to Elasticsearch.
