### ISSUE TITLE
[DOCS] Improve documentation of the get role mappings API

### ISSUE THREAD

**Issue by fdartayre** [elastic/elasticsearch#46905]
**Describe the feature**:
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-role-mapping.html) doesn't indicate that `GET /_security/role_mapping` returns only the role mappings configured via the [API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role-mapping.html) and not the roles configured through [files](https://www.elastic.co/guide/en/elastic-stack-overview/current/mapping-roles.html#mapping-roles-file).

For the sake a clarity it should be clearly stated in the documentation.

**Comment by jrodewig** [comment]
[docs issue triage]

leaving open as this is still relevant.
