### ISSUE TITLE
[CI] Ubuntu packaging test failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46903]
Task `:qa:os:ubuntu-1804:distroTest.default-deb` fails on master

Logs: https://gradle-enterprise.elastic.co/s/xgy5awpx6r326/console-log?task=:qa:os:ubuntu-1804:distroTest.default-deb

Error: 
```

org.elasticsearch.packaging.test.DebMetadataTests > test05CheckLintian FAILED
--
\|     java.lang.RuntimeException: Command was not successful: [bash -c lintian --fail-on-warnings /elasticsearch/distribution/packages/deb/build/distributions/elasticsearch-8.0.0-SNAPSHOT-amd64.deb] result: <org.elasticsearch.packaging.util.Shell$Result exitCode = [1] stdout = [W: elasticsearch: jar-contains-source usr/share/elasticsearch/jdk/demo/jfc/SwingSet2/SwingSet2.jar AquaTheme.java
     N: 397 tags overridden (185 errors, 122 warnings, 90 info)
     ] stderr = [warning: the authors of lintian do not recommend running it with root privileges!
     warning: --fail-on-warnings is deprecated
     ]>
         at __randomizedtesting.SeedInfo.seed([6A0354A806B4E302:AAFDC844BCC086B9]:0)
         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:94)
         at org.elasticsearch.packaging.util.Shell.run(Shell.java:61)
         at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:41)

```

Fails also on 7.4: https://gradle-enterprise.elastic.co/s/nmiplie2ink4u/console-log?task=:qa:os:ubuntu-1804:distroTest.default-deb

**Comment by atorok** [comment]
Possibly related to changing to openjdk  @jasontedor .
Perhaps we should exclude the `demo` folder from the JDK  ? 
We should also see why this wasn't caught by the snapshot PR check ?Afaik that runs on ubuntu, don't we run lintian there?

**Comment by jasontedor** [comment]
I think that it's fine to exclude the `demo` folder. Will you take up understanding why the PR check didn't fail?

**Comment by ywelsch** [comment]
I've muted `test05CheckLintian` on master, 7.x and 7.4 (42cc899d176, db63e78b68c, 61f0eaa121f). I didn't know how to mute this purely on Ubuntu, so it's a complete mute.

**Comment by rjernst** [comment]
This should be fixed by #47161 and the test has been unmuted. Closing.

**Comment by atorok** [comment]
The test failure is indeed fixed. @rjernst hope you don't mind if I leave this open as a reminder to check why this was not caught as part of PR checks

**Comment by atorok** [comment]
I checked and we do run lintian on unbuntu 1604 as part of the snapshot PR check.
Recent PR  runs show this test running, but unfortunately the log for the original is no longer present in Jenkins, so there's not much we can say about it. 
The only possibility I see is that Ubuntu 18 ( the failing one ) has a different config than 16 which is part of snapshot.
