### ISSUE TITLE
[DOCS] _exists_ returns `too_many_clauses` exception

### ISSUE THREAD

**Issue by thePanz** [elastic/elasticsearch#46928]
**Elasticsearch version**: 7.3.2
**Plugins installed**: none
**JVM version**: 12.0.2
**OS version**: latest docker container for 7.3.2

**Issue**
Running the following query: `{"query": {"exists": {"field": "myField"}}}}` returns a "all shards failed" due to `too_many_clauses` exception.

The container log reports:
```
elasticsearch_1  | {"type": "server", "timestamp": "2019-09-20T13:49:09,025+0000", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "elasticsearch", "node.name": "es01", "cluster.uuid": "Lj6To9uwSTetSdntuC4Wyw", "node.id": "iCm50_K2QEq8aV9FZcrTWg",  "message": "All shards failed for phase: [query]" , 
elasticsearch_1  | "stacktrace": ["org.elasticsearch.index.query.QueryShardException: failed to create query: {",
elasticsearch_1  | "  \"exists\" : {",
elasticsearch_1  | "    \"field\" : \"myField\",",
elasticsearch_1  | "    \"boost\" : 1.0",
elasticsearch_1  | "  }",
elasticsearch_1  | "}",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:321) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:304) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.parseSource(SearchService.java:743) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createContext(SearchService.java:591) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:550) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:353) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService$2.doRun(SearchService.java:1052) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) [?:?]",
elasticsearch_1  | "Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024",
elasticsearch_1  | "at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:114) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:127) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.elasticsearch.index.query.ExistsQueryBuilder.newObjectFieldExistsQuery(ExistsQueryBuilder.java:208) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.ExistsQueryBuilder.newFieldExistsQuery(ExistsQueryBuilder.java:195) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.ExistsQueryBuilder.newFilter(ExistsQueryBuilder.java:157) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.ExistsQueryBuilder.doToQuery(ExistsQueryBuilder.java:130) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:305) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:317) ~[elasticsearch-7.3.2.jar:7.3.2]",
elasticsearch_1  | "... 16 more"] }
```

**Steps to reproduce**:
The issue relies on the mapping structure of the `myField` property, which contains ~80 sub-properties, and those have between 10 to 50 (or more) sub-properties.
No analysis is defined for the index.

A quick gist of the document defined in the mappings:
```
- propertyA <-- this property fill cause the issue, "myField" in the example
    - propertyA01
        - propertyA01_01
        - propertyA01_02
            - propertyA01_02_01
            - .. ~10 properties at this level
        - propertyA01_03
        - .. ~15 properties at this level
        - propertyA01_xx
    - propertyA02
    - .. ~85 properties at this level (with additional sub-levels)
    - propertyA80
- propertyB
- .. ~80 properties at this level
- propertyXX
```
 1. Create an index with no analysis, 
 2. Create a mapping with a document configured as above
 3. Query for the `_exists_` with the property pointed above

**Comment by thePanz** [comment]
Any update @jimczi ?

**Comment by jimczi** [comment]
We discussed this issue internally and decided that we'll update the documentation to explain the limitation. We have a limit in terms of number of fields per mapping so I suppose that you changed the default to allow more than 1000 fields ? If so you also need to increase the maximum number of boolean clause that a query can have: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html
We transform any `exists` query on object fields into sub-clauses that check the existence of the leaves so you'll need to set the `indices.query.bool.max_clause_count` to the maximum number of sub-fields that you have for a single object field.

**Comment by thePanz** [comment]
@jimczi thank you for the update, a note in the documentation would be great!

Just one comment:  the `exists` query is transformed to check the existence of leaves, why not checking the existence of nodes 1 step from the requested property only?

From my example above: why not transforming `_exists_:propertyA` to check the existence of `propertyA01` to `propertyA80` (the set of nodes reachable with 1 step from the `propertyA`)?

This would lead to creating a fewer queries. WDYT?

**Comment by jimczi** [comment]
> Just one comment: the exists query is transformed to check the existence of leaves, why not checking the existence of nodes 1 step from the requested property only?

Because we don't index object fields, we need to find the leaves associated to the requested object because that's what we can search for. In previous versions of Elasticsearch we used to index all field names present in a document in a special field to speed up `exists` queries. However indexing these field names is costly so we now rely on the fact that we have forward iterator on concrete fields (doc values) to perform these queries. 

> update1 yes, I can confirm that the mapping.total_fields.limithas been changed from the default value to 100k

You could maybe use a different model to limit the explosion of fields ? For instance a nested field with a `key` and a `value` where `key` would act as a field name and `value` is the content. You can then write nested query that search for the conjunction of a `key` (the field name) and a `value` ?

**Comment by jrodewig** [comment]
I've opened #48153 to note in the docs that `index.mapping.nested_objects.limit` and `indices.query.bool.max_clause_count` should be increased together. All feedback welcome!

**Comment by thePanz** [comment]
@jrodewig : a mention on the `mapping.total_fields.limit` should be adde too, not only to `index.mapping.nested_objects.limit`

**Comment by jrodewig** [comment]
Thanks @thePanz . I've relocated the note in the PR.
