### ISSUE TITLE
Boolean "should" query is blowing up for queries that don't have a field for the given index

### ISSUE THREAD

**Issue by JacobBrandt** [elastic/elasticsearch#46987]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.1

**Description of the problem including expected versus actual behavior**:
Expected behavior:
A boolean "should" query should return results if the minimum_should_match has been met for the query clauses given in the array.

Actual behavior:
Boolean "should" query is blowing up because a query clause in the should array has a field that doesn't exist in the index preventing valid results to be returned.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

1.  Use Kibana and Elasticsearch for this version
2. Add all of the sample data
3. Create a tile map visualization using the kibana_sample_data_flights index.
4. Create a tile map visualization using the kibana_sample_data_logs index.
5. Add both visualizations to a dashboard.
6. Add this boolean query filter
```json
{
  "bool": {
    "should": [
      {
        "geo_bounding_box": {
          "geo.coordinates": {
            "top_left": {
              "lat": 39.52740405218037,
              "lon": -90.9840712267211
            },
            "bottom_right": {
              "lat": 37.545846355109944,
              "lon": -87.71916499126257
            }
          }
        }
      },
      {
        "geo_bounding_box": {
          "DestLocation": {
            "top_left": {
              "lat": 39.52740405218037,
              "lon": -90.9840712267211
            },
            "bottom_right": {
              "lat": 37.545846355109944,
              "lon": -87.71916499126257
            }
          }
        }
      }
    ]
  }
}
```
7. Observe the bug described

**Comment by jimczi** [comment]
Most (if not all) queries have an option called `ignore_unmapped` (defaults to false), for `geo_bounding_box` query the option is described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#_ignore_unmapped). It was added specifically for the issue that you're reporting here so I hope you don't mind if I close this issue.

**Comment by JacobBrandt** [comment]
Thanks, that's what I was missing.  I did not see that option as I was looking in the bool query documentation.  I think it would go a long way if an example of this option being used was documented by itself.  Similar to the minimum_should_match parameter.

**Comment by JacobBrandt** [comment]
@jimczi Actually that didn't work.  Could you reopen this because it still doesn't return the correct results even with ignore_unmapped set to true.  It's no longer throwing an exception but it's still returning unexpected results.  Same steps as before just using this filter

```json
{
  "bool": {
    "should": [
      {
        "geo_bounding_box": {
          "ignore_unmapped": true,
          "geo.coordinates": {
            "top_left": {
              "lat": 39.52740405218037,
              "lon": -90.9840712267211
            },
            "bottom_right": {
              "lat": 37.545846355109944,
              "lon": -87.71916499126257
            }
          }
        }
      },
      {
        "geo_bounding_box": {
          "ignore_unmapped": true,
          "DestLocation": {
            "top_left": {
              "lat": 39.52740405218037,
              "lon": -90.9840712267211
            },
            "bottom_right": {
              "lat": 37.545846355109944,
              "lon": -87.71916499126257
            }
          }
        }
      }
    ]
  }
}
```

I thought it was correct until I looked deeper into the response.  It's returning things way outside the bounding boxes.

**Comment by JacobBrandt** [comment]
Nevermind it's slightly different steps I'll create another ticket
