### ISSUE TITLE
reindex fail from es1.x to es5.x

### ISSUE THREAD

**Issue by jessin20161124** [elastic/elasticsearch#46993]
I execute the following command
```
POST /_reindex
{
    "size":1,
    "dest":{
        "index":"qbcp_order",
        "op_type":"INDEX"
    },
    "source":{
        "index":"qbcp_order_beta_tts3",
         "remote":{
            "host":"http://110.93.67.26:9200"
        }
    }
}
```
and get the error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "Response didn't include Content-Type: body={\"OK\":{}}"
      }
    ],
    "type": "exception",
    "reason": "Response didn't include Content-Type: body={\"OK\":{}}"
  },
  "status": 500
}
```

**Comment by henningandersen** [comment]
@jessin20161124 are you on newest 1.x and 5.x versions? I think this should work fine and wonder if something could be intercepting the remote call from reindex to the old version node. Either the call to "/" to lookup the version or the search call. The response body listed does not look like the response from either of those endpoints we call.

**Comment by tbrooks8** [comment]
Closing as we did not receive feedback.
