### ISSUE TITLE
Building deb packages fails on Windows 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#47007]
The stack trace of the failure is : 
```
begin 0, end -1, length 71
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':distribution:packages:buildOssDeb'.Open stacktrace
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 71Close stacktrace
at com.netflix.gradle.plugins.utils.GradleUtils.relativizeSymlink(GradleUtils.groovy:35)
at com.netflix.gradle.plugins.deb.DebFileVisitorStrategy.addFile(DebFileVisitorStrategy.groovy:34)
at com.netflix.gradle.plugins.deb.DebCopyAction.visitFile(DebCopyAction.groovy:123)
at com.netflix.gradle.plugins.packaging.AbstractPackagingCopyAction$StreamAction.processFile(AbstractPackagingCopyAction.groovy:60)
```

https://gradle-enterprise.elastic.co/s/sidkgld4awq4m/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

**Comment by atorok** [comment]
@mark-vieira @rjernst  to summaries, the upstream plugin has a bug when dealing with symlinks on Windows. Do you think it's worth pursuing a fix upstream for this ? I'm leaning to wards saying it's not, since there should never be a need to build deb packages on windows.

**Comment by mark-vieira** [comment]
> I'm leaning to wards saying it's not, since there should never be a need to build deb packages on windows.

I wouldn't go so far as saying you _never_ want to build a deb on Windows. That might be the release machine. Just as we build both RPM and DEB on our worker regardless of whether it's RedHat or Debian based.

That said, Windows support for unix packaging tools is probably not high priority but there might be folks doing development on Windows that might want the ability to build on Windows. I'll defer to @rjernst's judgement here.

**Comment by rjernst** [comment]
We always build our releases on the same system (ubuntu based IIRC), and the vast majority of developers use a nix compatible OS. I think dropping support for building rpm/deb on windows is fine, as long as the build gracefully skips it on that platform (like assumeFalse basically).

**Comment by atorok** [comment]
I'm going to close this issue then, since there's no further work planned.

**Comment by mark-vieira** [comment]
I'm not sure we've resolved this. We should _disable_ this on windows or have it fail gracefully with a useful message.
