### ISSUE TITLE
[Docs] Provide best practices for the safest way of upgrading Elasticsearch

### ISSUE THREAD

**Issue by rwaight** [elastic/elasticsearch#47028]
**Describe the feature**:  
Last week we discussed our upgrade documentation and ways we can improve the upgrade experience; for larger deployments, the proper order becomes important.

While we provide [this high level overview](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) for upgrading Elasticsearch, we should also include best practices around the safest way to upgrade Elasticsearch.  We should include the order in which nodes should be upgraded (for example: do we suggest ingest-only nodes first, master nodes last?), especially for larger deployments.

For overall Elastic Stack upgrades, I've opened [`elastic/stack-docs#537`](https://github.com/elastic/stack-docs/issues/537) for best practices to be included.

**Comment by debadair** [comment]
Are there additional recommendations that should be made, or can this be closed now that #47279 is merged?

**Comment by rwaight** [comment]
Hi @debadair, I'm checking with the team and will let you know if any additional recommendations should be made, thanks!

**Comment by inqueue** [comment]
> Are there additional recommendations that should be made, or can this be closed now that #47279 is merged?

What we have looks good. I think this can be closed.
