### ISSUE TITLE
Remove StandardHtmlAnalyzer

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#4704]
The StandardHtmlAnalyzer has never been documented and has been implemented with limited support for configuration.

Its functionality is easy to replicate (in a more flexible way) using the HTMLStripCharFilter, so we should remove this analyzer.

**Comment by clintongormley** [comment]
I think we can deprecate this now (5.x).  We'll need to support it for existing indices in 6.0, but not allow new indices to be created with it, and we can remove in 7.0.

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs
