### ISSUE TITLE
ExplainResponse deserialization with the matched field

### ISSUE THREAD

**Issue by amdious** [elastic/elasticsearch#47053]
While playing with the high level REST api for explain requests I was noticing that the isMatched() was always returning false even though it's true in the JSON payload.  Digging deeper it always looks like the case in:

https://github.com/elastic/elasticsearch/blob/3035cd35a4ca0a3db13ae1597421d6518fa14e4c/server/src/main/java/org/elasticsearch/action/explain/ExplainResponse.java#L159

But my problem is that can we always infer that greater than 0 is match? This seems like a bug to me since Boolean filter implies no score:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

And there's nothing preventing the explanation passing in 0 for value in the constructor:

https://github.com/apache/lucene-solr/blob/4ec4061cbcd426774b84184c074c24ecf3a1e81b/lucene/core/src/java/org/apache/lucene/search/Explanation.java#L71

I would honestly just want to pull make it symmetric with the toXContent but wanted to make sure I wasn't missing anything before doing a PR.

The workaround is obvious to just parse the explanation without the high level client if you have a dependency on that field and use boolean queries.

**Comment by jtibshirani** [comment]
This also looks like a bug to me, we would welcome a pull request to fix it. As part of the change, it would be great to include some test cases that exercise the incorrect behavior you noticed.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
