### ISSUE TITLE
Make sure doc only changes, plugin only changes or other "leaf" changes only run those specific tests

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47091]
Currently we have a special "docs only" PR check that runs as an alternative when the 
changes are contained in the docs folder only.
This works very well since we have lots of PRS doing small changes to the docs, so the checks on these can finish much sooner, and the people making these changes are shielded from dealing with flaky tests.  

We discussed extending this to Intake jobs, however, thanks to the excellent work done by @mark-vieira the build cache works very well and can be made to serve this purpose in a more generic way that doesn't add complexity to CI. 
In addition it will work for all types of "leaf" only changes  ( changes to projects nobody else depends on ). 

As such we should make sure that inputs are configured correctly on tasks so that all other tests are skipped. 
We should also remove the existing docs only PR check for simplicity. 

It would be nice if we had a way to verify this is not broken.
Could we have a check that does a spot check for changes only in some plugin or docs and then checks the build scan to make sure all but the relevant tests were skipped, pointing out ones that were not ? 

How will parallel jobs affect us ? If the build on the previous iteration is still running some of the tests might run again for the docs change because cached results don't exist yet. Granted that would mean making these changes would have to be relatively quick, going from `git pull` to creating the PR in less than 40 minutes at most.

**Comment by mark-vieira** [comment]
This is a fuzzy issue that is mostly addressed by the build cache, we have more specific issues to improve that, like increase use of the integ-test distribution so I'm closing this in favor of that.
