### ISSUE TITLE
GrokTests#testNumericCapturesCoercion fails rarely and unreproducibly

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#47098]
The following (PR) build failed:

https://gradle-enterprise.elastic.co/s/2gxm5b5kffo22/console-log?task=:libs:elasticsearch-grok:test

```
org.elasticsearch.grok.GrokTests > testNumericCapturesCoercion FAILED
    java.lang.IllegalArgumentException: Unable to find pattern [] in Grok's pattern dictionary
        at __randomizedtesting.SeedInfo.seed([86D6B3FCB40F7F8B:D214B887E3D6771F]:0)
        at org.elasticsearch.grok.Grok.toRegex(Grok.java:193)
        at org.elasticsearch.grok.Grok.<init>(Grok.java:104)
        at org.elasticsearch.grok.Grok.<init>(Grok.java:82)
        at org.elasticsearch.grok.GrokTests.testNumericCapturesCoercion(GrokTests.java:300)
REPRODUCE WITH: ./gradlew ':libs:elasticsearch-grok:test' --tests "org.elasticsearch.grok.GrokTests.testNumericCapturesCoercion" -Dtests.seed=86D6B3FCB40F7F8B -Dtests.security.manager=true -Dtests.locale=ta-LK -Dtests.timezone=US/Indiana-Starke -Dcompiler.java=12 -Druntime.java=11
```

The `REPRODUCE WITH` line does not reproduce for me, and I have run tens of iterations of `./gradlew ':libs:elasticsearch-grok:test' --tests "org.elasticsearch.grok.GrokTests.testNumericCapturesCoercion" -Dtests.iters=10000 -Dtests.failfast=true` without seeing another failure. However there are a couple of other similar failures in build-stats over the last few months too, so this wasn't a complete one-off.

**Comment by martijnvg** [comment]
The underlying cause of this failure is the same as to other tests in `GrokTests` reported in #43673. Closing this issue in favour that issue.
