### ISSUE TITLE
Auto unlock indices when disk space is freed

### ISSUE THREAD

**Issue by cdalexndr** [elastic/elasticsearch#47099]
**Describe the feature**:
When running out of space indices go to read-only, causing errors:
`cluster_block_exception: index [metricbeat-7.3.0-2019.09.19-000001] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];`
After resolving the space issue, the indices are still locked and require manual intervention: https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/4

If the indices are **auto-locked** when disk is full, then they should be **auto-unlocked** when disk space is available again, so no manual intervention will be required to restore the system to a working state.

**Comment by ywelsch** [comment]
Already implemented and will be released in ES 7.4, see https://github.com/elastic/elasticsearch/pull/42559 and https://github.com/elastic/elasticsearch/issues/39334
