### ISSUE TITLE
Start testing against debian (8) again

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#47118]
As far as I can see on build-stats, we are no longer testing debian as frequently as we used to, probably disabled due to #43387.

That issue has not occurred for a while, but to be sure it is really fixed (maybe by the new 3.16.0-10 kernel) we need to see it not fail when all debian jobs are back to running again.

Can we please put debian jobs back into circulation (i.e., back to how it used to be)?

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fy,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%27build.project:%20elasticsearch%20AND%20build.tags:%20debian-*%27),sort:!(process.time-start,desc))

**Comment by atorok** [comment]
We do still run on debian in the [unix compatability matrix tests](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/) but indeed it was pulled from the pool of eligible workers for intake and PR. 
I'we ran some tests in the last few days and will be adding it back.
