### ISSUE TITLE
Pre-search lookup/enrichment phase

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#47129]
When formatting a query, there are cases where some of the parameters are irritating to include in the query itself.  Common examples are long list of terms for filter, geo shapes (which are usually very large), vectors/maps representing pre-generated models used for custom scoring or aggregation.

We support a `lookup` functionality on the terms query, and _some_ of the geo queries support lookups, but support is very sporadic.  We also support search templates which can be used, but their static nature makes them only useful in certain situations.

I wonder if we should have some kind of unified "pre-search lookup" phase?  This would allow fetching a document, parsing it and storing the representation in the search context.  Then all queries and aggregations could have access to that document for their own purpose, be it geo shapes during queries or large vectors for ML models during aggregation.

It would provide a unified interface for "lookups", and we could potentially deprecate the individual logic that is currently implemented on each feature that supports it's own lookup.

I'm sure the devil is in the details, and a few potential problem areas that jump out at me:
- Could be expensive to cache a large document in the search context, serialization overhead, etc
- How does it work with CCS?
- If parsing is needed (e.g. converting a geojson into the internal shape tree) how is that specified / who is responsible for that?  Or do we expect the indexed data to be stored in that format?

**Comment by mayya-sharipova** [comment]
This kind of lookup would also be very useful for our ann search case, where a model can be loaded  from a document or a file. But here it is also important to cache it so not to lead the same model on every query.

**Comment by dnhatn** [comment]
+1. I think we are good here the enrich processor and [lookup runtime field](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-retrieving-fields.html#lookup-runtime-fields). I am closing the issue.

**Comment by javanna** [comment]
To avoid confusion, I care to clarify that the lookup runtime field is only a fetch phase enrichment and cannot be queried/aggregated on, which I believe is what this issue was about. The enrich processor solves that, but it would be an index time enrichment (hence static) rather than search time (dynamic).
