### ISSUE TITLE
Add support for external (snapshot) distributions for the distribution download plugin

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#47123]
Now that the plugin builder plugin applies the test-clusters project which uses the distributions download plugin, the plugin builder can no longer be used outside of the ES project as the lather has no support for it.

**Comment by mark-vieira** [comment]
This is effectively a blocker for 8.0 release, yes? Do we have some way of tracking this to ensure this absolutely gets fixed.

**Comment by atorok** [comment]
It's also a blocker for `7.x` as we would like to back-port the changes there, so it too will break as soon as we back-port #47022
