### ISSUE TITLE
[DOCS] index.store.preload link points to Store module instead of setting

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#47144]
[Tune for search speed::Warm up the filesystem cache](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#_warm_up_the_filesystem_cache) contains a link for the Elasticsearch `index.store.preload` setting. The link points to https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-store.html#file-system when it should point to https://www.elastic.co/guide/en/elasticsearch/reference/master/_pre_loading_data_into_the_file_system_cache.html.

Can the link be changed for the current and all previous doc versions?

**Comment by jasontedor** [comment]
> Can the link be changed for the current and all previous doc versions?

We try to keep maintenance low and really only backport to currently maintained versions unless it’s an egregious issue. This wouldn’t qualify as one.

**Comment by jrodewig** [comment]
I plan to backport this to 6.8, the earliest supported version based on our [ product end of life](https://www.elastic.co/support/eol) schedule.
