### ISSUE TITLE
cannot bind to logstash 5000 port

### ISSUE THREAD

**Issue by jacobmathewssoffit** [elastic/elasticsearch#47153]
hi...I am not able to connect to my localhost 5000 port in which I have configured by logstash…I am attaching a screenshot of my "filebeat test output",logstash input conf and filebeat.yml configurations.kindly help me with the solution,as I am a fresher in this elk part.

![error filebeat](https://user-images.githubusercontent.com/55828576/65667996-84bc6e80-e05e-11e9-9743-72862e54e0f1.png)

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
