### ISSUE TITLE
Doc:  Composite aggregation and count accuracy

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#47180]
There's a nice explanation from @markharwood (thx!) on why composite aggregations return accurate counts compared to terms aggs.

https://discuss.elastic.co/t/composite-aggregation-document-count/153322/2

This can be a great addition to our doc pages:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-aggregations-bucket-composite-aggregation.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.3/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts

**Comment by markharwood** [comment]
>There's a nice explanation from @markharwood (thx!)
Thanks, that was the short answer

Related: I proposed a much longer [blog post](https://github.com/elastic/blog/issues/509) on the topic of choosing the right "group by" approach (we have several). 

In the end I opted to create an interactive [wizard](https://embed.plnkr.co/4u5CscRfiUOQwUDSDRgC/) which I think proved technically challenging to wrap up in our official docs.

**Comment by debadair** [comment]
[docs issue triage]

We should incorporate the "short answer" and still want to incorporate the wizard approach. There's a doc infra issue for that: https://github.com/elastic/docs/issues/1253

**Comment by not-napoleon** [comment]
I think the clarification I did in https://github.com/elastic/elasticsearch/pull/86528 accurately captures this, closing.
