### ISSUE TITLE
Dashboard Issue with Metricbeat

### ISSUE THREAD

**Issue by skdasarin00b** [elastic/elasticsearch#47190]
Hello Team,

https://discuss.elastic.co/t/metricbeat-dashboard-not-displaying-accurate-avg-metrics-for-every-host/199921

Please find the mentioned link above. Not sure why am i facing this issue.. Is it normal??

**Comment by tlrx** [comment]
Hi @skdasarin00b, thanks for using Elasticsearch, Kibana and Metricbeat :) You already opened an issue in the [Elastic forums](https://discuss.elastic.co/), which is the right thing to do. But we reserve the Elasticsearch Github repository for bug reports and feature requests, so I'm going to close this issue in favor of the Discuss message. Thank you!
