### ISSUE TITLE
[CI] buildDeb fails on windows

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#47199]
Example failure:

https://gradle-enterprise.elastic.co/s/agjjs25jqhcqe/console-log#L5330

Not a lot to go by:
```
* What went wrong:
--
Execution failed for task ':distribution:packages:buildDeb'.
> begin 0, end -1, length 71
```
but it seems it started failing around a week ago:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:f0e86d70-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'log:%22:distribution:packages:buildDeb%22%20AND%20log:failed'),sort:!(time,desc))

Did a bit of manual correlation to the builds and it looks like it is only windows builds failing, both windows-2016 and windows-2019.

**Comment by mark-vieira** [comment]
Duplicates #47007
