### ISSUE TITLE
[CI] windows testExtractValidHeapSizeNoOptionPresent failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#47209]
Example failed build:

https://gradle-enterprise.elastic.co/s/khwai6gtvlozo/tests/n22ss45luel4s-7tywknohsipo2?openStackTraces=WzBd

Failure:

```
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>
```

Started failing this morning after 9:24 on 7.3. and 7.4:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testExtractValidHeapSizeNoOptionPresent),sort:!(process.time-start,desc))

**Comment by atorok** [comment]
Possibly related to #44669
