### ISSUE TITLE
[Stack Monitoring] Remove exporters

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#47215]
_The work described in this issue is a breaking change. As such, it is intended to be released **only** in a major release (i.e. no backports)._

We now have the ability to monitor Elasticsearch, Kibana, Logstash, Beats, and APM Server with Metricbeat. The previous method of monitoring stack products, using collection code internal to each product that shipped monitoring data to a custom Monitoring Bulk API endpoint, is now deprecated. And in the next major release (likely 8.0.0), all code related to this internal collection approach should be removed.

This issue tracks the removal of one specific item related to the internal collection approach: the `local` and `http` exporters implemented by the Monitoring plugin. Note that settings related to these exporters should also be removed from documentation. However, keep in mind that resource creation code from exporters would've already been moved to the plugin init stage (see https://github.com/elastic/elasticsearch/issues/44102); settings related to this code should be retained but moved out from under the exporters namespace.

By removing these exporters Elasticsearch will no longer be able to index monitoring documents into `.monitoring-*` indices, either on the local cluster or a remote monitoring cluster. Instead, users will have to run Metricbeat along side Elasticsearch. Metricbeat will collect monitoring metrics from various stack products and ship them to a specified Elasticsearch cluster for indexing into `.monitoring-*` indices.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
