### ISSUE TITLE
[DOCS] Document CCR compatibility requirements

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#47218]
### Context

(Courtesy of @jasontedor & @ppf2 in #47185. Thanks!)

CCR has a stricter compatibility requirement than remote clusters do.

The local cluster (the one that is pulling from the remote cluster) must be of a compatible version equal to or newer than the version of the remote cluster. The reason is the same as for allocation of replicas: the local cluster must be able to understand the Lucene segment files that are sent to it, as well as any index settings, mappings, etc.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by MrNoddyInfy** [comment]
Is this issue fixed?

**Comment by jrodewig** [comment]
Hi @MrNoddyInfy.

The issue is not yet fixed, but @erzz99 has a resolving PR in review:
https://github.com/elastic/elasticsearch/pull/47331
