### ISSUE TITLE
[DOCS] Add practical example of using the reindex API to change mappings

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#47248]
**Describe the feature**:

Today, both the the Put Mapping API [1] and Reindex API [2] docs have blurbs that touch on the concept of reindexing to adjust an existing index's mappings.

Mapping API:

> Changing the mapping of an existing field could invalidate data that’s already indexed. If you need to change the mapping of a field, create a new index with the correct mappings and reindex your data into that index. If you only want to rename a field, consider adding an alias field.

Reindex API:

> Reindex does not attempt to set up the destination index. It does not copy the settings of the source index. You should set up the destination index prior to running a _reindex action, including setting up mappings, shard counts, replicas, etc.

Users might find it helpful if we went a step further to document a hands on example (e.g code snippets that can be run in Console) to demonstrate exactly how to use the reindex API to accomplish this.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by jrodewig** [comment]
Issue triage

Opened #47462 to address.
