### ISSUE TITLE
How to build es v6.6.1 with java1.8.0_60?

### ISSUE THREAD

**Issue by sunny868** [elastic/elasticsearch#47273]
I want to build es v6.6.1 with java 1.8.0_60 ,gradle v5.6.2. but failed .

**Comment by atorok** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
