### ISSUE TITLE
Norm elastic search ranking result

### ISSUE THREAD

**Issue by Hedgehogues** [elastic/elasticsearch#47290]
Hello. I want to normalize the scalar product when ranking.

I will explain in simple words, and then add a little bit of mathematics. Suppose we have 2 search results. One search result was generated for the query `Pupkina Sons`, and the second - for the query` Sons Pupkina`. Then we have the output:

```
document_0, score_0
document_1, score_1
document_2, score_2
...
document_p, score_p
```

Issue for the second request:

```
document_0, score_0
document_1, score_1
document_2, score_2
...
document_q, score_q
```

Let score_0 for the first issue is 500. And score for the second issue is 0.5. ** Task ** is required to be able to compare the scores of different issues and evaluate the relevance to each other.

Default ranking function, as I know, is dot product. For example, we have vector for query (v) and vector for documents (d_i). For ranking, we make (q, d_i) for all i, where (., .) -- dot product. Please, explain me, how I can calculate (q / |q|, d_i / |d_i|)? I think it possible three solves of my problem. 

* function_score. Can I get weight (tf-idf) into function_score?
* getting all weights by API elasticsearch. Flag `explain` is not valid solve, because this is so long. Another case, this is bad solve as explain return intersection (q and d_i tokens). Notice: While now, I say about dot product, in the future, I want calculate euclidean distance.
* normalize elastic search weights by default

**Comment by Hedgehogues** [comment]
Found on the expanses of elastic for 6.8 https://www.elastic.co/guide/en/elasticsearch/reference/6.8/norms.html the possibility of normalization. I'm interested in the normalization of weights. But, alas, I conducted an experiment and did not observe the normalization. Those. score> 1.

I did it with python like this:

`` `request_body = {
             'properties': {
                 'title': {
                     'type': 'text',
                     'norms': True,
                 }
             }
         }
         resp = es.indices.put_mapping (body = request_body, doc_type = '_ doc') `` ``

Do I understand correctly that this article is about normalization? I use the library: https://pyelasticsearch.readthedocs.io/

**Comment by Hedgehogues** [comment]
Apparently, this is impossible to do. The only option I was offered was to patch the elastic. But this option does not look adequate, since it will have to be redone after any version update. It hurts. Scripts do not allow you to get to the scales. Plugins - similarly.

This is most likely explained by the fact that the elastic is distributed and not all weights are stored on one shard.

**Comment by jimczi** [comment]
By default the ranking uses BM25 to score documents, so they are not "normalized". 
However for queries of similar structure (same field, same number of terms) it should be fine to compare the BM25 score directly. You could also "normalize" the score if the number of terms is different by dividing the final score by number of terms. Note that could work only if the the same type of query is compared (terms vs phrase query will not work). 
We have another [issue](https://github.com/elastic/elasticsearch/issues/23850) opened with a lot of history regarding different type of normalizations, it's a good entry point if you want to understand the different challenges that we have to handle inside Elasticsearch.
I am also curious to hear more about your use case but the discuss forum is better suited for this kind of discussion. Could you open a new thread in the [forum](https://discuss.elastic.co/c/elasticsearch) and me or/and someone from the community can continue to discuss the best options that you have to solve your issue ? I hope you don't mind that I close this issue, we can reopen if the discussion in the forum reveals a feature that is missing.
