### ISSUE TITLE
[DOCS] Make 'node type' documentation more readable

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#47292]
We've received feedback that the 'node type' documentation is difficult to read/parse:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#master-node

We should consider rewriting to increase readability.

**Comment by DaveCTurner** [comment]
Relates #42422

**Comment by debadair** [comment]
[docs issue triage]

Note that this is the official source of truth for our node type definitions.

**Comment by jrodewig** [comment]
Closing as this seems to be improved a bit with #42422 and, as mentioned, this is the source of truth for node type definitions. Will re-open or address in other issues if we get more specific feedback.
