### ISSUE TITLE
Delete by Query API should not support text field queries by default

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch#47314]
The fact that the delete-by-query API supports deletions of text content (which can delete more than anticipated in a field) seems inherently dangerous. 

It might be a good idea to assume that the field should be a keyword field and return a 400 level response if the delete by query searches on a text field. You could continue to support text fields in the delete-by-query API using a parameter that explicitly allows it. 

This might be a good way to safeguard against PEBCAK deletions of more content than was intended. 

<!--

** Please read the guidelines below. **

Issues that do not follow these guidelines are likely to be closed.

1.  GitHub is reserved for bug reports and feature requests. The best place to
    ask a general question is at the Elastic [forums](https://discuss.elastic.co).
    GitHub is not the place for general questions.

2.  Is this bug report or feature request for a supported OS? If not, it
    is likely to be closed.  See https://www.elastic.co/support/matrix#show_os

3.  Please fill out EITHER the feature request block or the bug report block
    below, and delete the other block.

**Comment by henningandersen** [comment]
We discussed this and think this works as designed. Making delete by query work differently from update by query (and reindex) would cause confusion. `_search` can be used to preview what will be deleted too. Hence we are closing this.
