### ISSUE TITLE
Add OS tests for macOS

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47336]
We don't currently run OS (packaging) tests for macOS.
While we probably can't implement checks that mess with the OS like other packaging tests because we neither have VMs nor ephemeral CI workers, we could still at least check basics, like the distribution starting up and the bundled JDK notarization being valid. 

Relates to #46498

**Comment by mark-vieira** [comment]
This is not gonna happen anytime soon, especially since we don't "officialy" support macos anyhow.
