### ISSUE TITLE
Investigate reduction in bwc tests 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#47349]
Since #46952 is not merge yet, this seems very strange: 

![Screenshot_2019-10-01_13-12-40](https://user-images.githubusercontent.com/2565652/65953696-3091ff80-e44d-11e9-8412-35d23da9a2f3.png)

This build spent 37 minutes running bwc tests: 
  https://gradle-enterprise.elastic.co/s/3zyogeubyogli/performance/execution

Then a series of runs spent less than one minute because bwc was disabled: 
  https://gradle-enterprise.elastic.co/s/ik75sohhjdyju/console-log

When they were re-enabled the build times wen down to ~ 20 minutes:
  https://gradle-enterprise.elastic.co/s/g2gyh65jdo26a/performance/build
And stayed there ever since.

I'm adding this issue because I'm not aware of what improved and want to make sure we are not skipping something we shouldn't

**Comment by atorok** [comment]
Compareing https://gradle-enterprise.elastic.co/s/3zyogeubyogli/performance/buildCache with https://gradle-enterprise.elastic.co/s/g2gyh65jdo26a/performance/buildCache both jobs behaved similarly and looking at tests ran they seem to have ran the same number of tests.

**Comment by atorok** [comment]
Looking at the timeline, it seems that for some reason the bwc tests parallelism improved. Rolling upgrade tests are scheduled sooner, and thus are no longer the long pole allowing everything to complete faster.

Looking at the changes nothing stands out:
`git log --since "Sep 25, 2019 11:00:34 PM EEST" --until "Sep 25, 2019 2:35:51 PM EEST" --date iso` on `7.x` and ` git log 777f4b316087631d9eb08088dc4e667033ce9ee5..bd5573dd0226694ecbfbdc5e410af2fd3df1e456 ` on master

@mark-vieira I'm going to close this since everything seems fine, but I'm still interested in your opinion.

**Comment by mark-vieira** [comment]
This is pretty interesting. It's amazing how much just a more efficient scheduling of tasks affects total build execution time. There's nothing sticking out to me on why it would start suddenly executing tasks in a different order. The task graph is pretty touchy though, any slight change in dependencies or ordering rules will cause a cascade that can drastically change how tasks are scheduled for execution.

**Comment by mark-vieira** [comment]
That said, since we _know_ this has a huge impact on build times we should probably add an ordering rule to force these tests to run as early as possible. That way this behavior we are now getting is explicit and won't suddenly change again w/o notice.

**Comment by mark-vieira** [comment]
I've opened #47379 to add some ordering rule so we don't eventually lose this optimization.
