### ISSUE TITLE
different score for the same documents

### ISSUE THREAD

**Issue by Hedgehogues** [elastic/elasticsearch#47357]
Hello to all. I insert the document into the collection. The document consists of 1 field:
```
{
     "tokens": "makita"
}
```

I do it 3 times. Then, I do a full-text index search. And it turns out that the 3 documents found have different speeds. Moreover, when I ask for `explain = True`, for some reason` docCount` and `docFreq` are different for them. What's the trouble?

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
