### ISSUE TITLE
Allow changing write consistency timeout on a cluster level

### ISSUE THREAD

**Issue by rore** [elastic/elasticsearch#4739]
The write consistency timeout (which is 1 minute by default) can be changed only with the timeout parameter on each individual indexing request.

It will be very useful to be able to change it globally on a cluster level (via configuration / settings), so you can be sure that the cluster doesn't hang when there are recovering shards. 

In the current situation after a cluster restart, when some indexes don't have a quorum yet, indexing requests hang and timeout. This can cause a cascading failure on an application level if you have a high throughput of indexing. In many cases it's better to fail the request fast rather than timeout.

**Comment by dakrone** [comment]
@rore when you are talking about the write consistency timeout, are you talking about the `?timeout=1m` parameter when sending the indexing request? Or are you talking about a different timeout entirely?

**Comment by rore** [comment]
Wow, this was opened a long time ago. 

Yes, it's the timeout parameter on the index API. 
I know you can pass it with the indexing requests, the point was to enable changing the default at the cluster level so you won't have to specify it on each request. 
1m timeout can be disastrous at some scenarios as described.

**Comment by clintongormley** [comment]
@bleskes what do you think about this, esp with the changes around write consistency?

**Comment by bleskes** [comment]
This is implemented in 5.0 with #19454 where an index settings  `index.write.wait_for_active_shards` was added. Also note that the original issue is now solved because our default is to only wait for the primary.

**Comment by bleskes** [comment]
It seems I misread and the request was for changing the timeout, not the actual wait criteria. I'm reopening the issue. Sorry for the noise.

PS I think this should be an index level setting rather than a cluster one

**Comment by dakrone** [comment]
This feature request is an interesting idea but since its opening we have
not seen enough feedback that it is a feature we should pursue. We prefer
to close this issue as a clear indication that we are not going to work on
this at this time. We are always open to reconsidering this in the future
based on compelling feedback; despite this issue being closed please feel
free to leave feedback on the proposal (including +1s).
