### ISSUE TITLE
SQL: allow spaces in escape sequences

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#47401]
Elasticsearch/SQL now supports JDBC/ODBC escape sequences at server level.
However, the current parser requires the `{` escape begin character to be followed by the escape discriminator with no white space allowed in-between. Example: `FUNCTION_ESC: '{FN';`.
The [BNF specification](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/scalar-function-escape-sequence) suggests white spaces would be allowed (maybe an **A**BNF would have made that explicit) and in support for that, other DBs supporting these escape sequences at server level do allow for spaces too (like MSSQL, DB2, MariaDB/MySQL).
Furhermore, also some applications - like PowerBI - generate escape sequences with spaces:
`select { fn name(params) } etc.`

**Comment by bpintea** [comment]
Alternatively, the statements spacing should to be adjusted in the respective drivers.

**Comment by matriv** [comment]
`master` : 08a22d0b393f4a76c52dabc5e7b9cafcc19c30ca
`7.x` : e698e68f06f4cc7947f4d959f0254c114878093d
`7.4` : aaea48d23677fa239aa7b16d3c029b67c3217035
`6.8` : c2583e5e232ba2b4d079c84c8d0b29f60bbf602f
