### ISSUE TITLE
Featurerequest: Track user actions and amount of resources used (process list)

### ISSUE THREAD

**Issue by simpleuser99** [elastic/elasticsearch#47426]
How to track user activity by username? Understand what data users use? Understand how much memory and cpu it took to process the user request? What requests are sent to the elastic? Looking for users who send large elastic requests? Search for specific queries that led to the failure or slow work of the cluster? See the most popular indices and queries to them from important users for us to optimize specific indices?
It would also be nice to be able to limit resource consumption for specific users in any way.
That is, it is about linux "top" like utility for Elastic because we have multiuser cluster. These are very important questions to meet the needs of users.
We have more than 100 users, but for example we don’t understand which specific users cause the elastic to work slowly. And also we cannot limit such users so that the other majority of users do not experience problems.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
