### ISSUE TITLE
Consistent indices APIs, part 2

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#4743]
Issue #4071 completed a lot of the work to make the various indices APIs consistent.  This issue details the work that remains:

PUT (singular) COMPLETED
--------------

    Request                                 Status
    -----------------------------------------------------------------------------------
    PUT /{index}/_mapping/{type}            Done
    { single defn }

    PUT /{index}/_warmer/{name}             Done
    { single defn }

    PUT /{index}/_alias/{name}              Done
    { single defn }

    PUT /{index}/_setting/{name}            Will not support
    { single defn }

Also support:

     PUT /{index}/{type}/_mapping           Done
     PUT & POST                             Done

Where: 

* `{index}` = `blank | * | _all | prefix* | name,name`
* `{name}`  = `name`

POST (plural) WORK NEEDED
-------------

    Request                                 Status
    -----------------------------------------------------------------------------------
    POST /{index}/_mappings                 Not done
    { multi defn }

    POST /{index}/_warmers                  Not done
    { multi defn }

    POST /_aliases                          Already supported
    { actions }

    POST /{index}/_settings                 Already supported
    { multi defn }

Also support:

     PUT & POST                             Add URLs

Where: 

* `{index}` = `blank | * | _all | prefix* | name,name` 

GET (singular or plural) WORK NEEDED
------------------------

    Request                                 Status
    -----------------------------------------------------------------------------------
    GET /{index}/_mappings/{type}           Add URL
    GET /{index}/_mapping/{type}            Done

    GET /{index}/_warmers/{name}            Add URL
    GET /{index}/_warmer/{name}             Done

    GET /{index}/_aliases/{name}            See note below
    GET /{index}/_alias/{name}              Done

    GET /{index}/_settings/{name}           Done
    GET /{index}/_setting/{name}            Add URL

Also support:

    GET /{index}/{type}/_mapping            Done

 Where: 

* `{index}` = `blank | * | _all | prefix* | name,name`
* `{name}`  = `blank | * | _all | prefix* | name,name`

Missing types/warmers/aliases/settings should return empty objects, not throw 404s

Note: The `GET /_aliases` response is different from `GET /_alias` currently, as it returns all matching indices, regardless of whether they have aliases or not.  This functionality is required by Kibana (et al) and should be implemented via the proposed functionality in #4614 or #4609.

DELETE (singular or plural) WORK NEEDED
---------------------------

    Request                                 Status
    -----------------------------------------------------------------------------------
    DELETE /{index}/_mappings/{type}        Add URL
    DELETE /{index}/_mapping/{type}         Done

    DELETE /{index}/_warmers/{name}         Add URL
    DELETE /{index}/_warmer/{name}          Done

    DELETE /{index}/_aliases/{name}         Add URL
    DELETE /{index}/_alias/{name}           Done

    DELETE /{index}/_settings/{name}        Will not be supported
    DELETE /{index}/_setting/{name}         Will not be supported

Also support:

    DELETE /{index}/{type}/_mapping         Done

 Where: 

* `{index}` = `* | _all | prefix* | name,name` BLANK NOT ALLOWED
* `{name}`  = `* | _all | prefix* | name,name` BLANK NOT ALLOWED

If no matching types/warmers/aliases/settings found, throw 404.

HEAD (singular or plural) WORK NEEDED
------------------------

    Request                                 Status
    -----------------------------------------------------------------------------------
    HEAD /{index}/_mappings/{type}           Not done
    HEAD /{index}/_mapping/{type}            Not done

    HEAD /{index}/_warmers/{name}            Not done
    HEAD /{index}/_warmer/{name}             Not done

    HEAD /{index}/_aliases/{name}            Add URL
    HEAD /{index}/_alias/{name}              Done

    HEAD /{index}/_settings/{name}           Not done
    HEAD /{index}/_setting/{name}            Not done

Also support:

    HEAD /{index}/{type}/_mapping            Add URL

 Where: 

* `{index}` = `blank | * | _all | prefix* | name,name`
* `{name}`  = `blank | * | _all | prefix* | name,name`

If no matching types/warmers/aliases/settings found, throw 404.

**Comment by dakrone** [comment]
@clintongormley is this something we still want to do? I think it would be better to standardize on a single API endpoint instead of trying to handle singular/plural for all the APIs

**Comment by clintongormley** [comment]
@dakrone I agree.  i think we're good where we are today
