### ISSUE TITLE
gc log rotation doesn't appear to work properly

### ISSUE THREAD

**Issue by OrangeDog** [elastic/elasticsearch#47431]
**Elasticsearch version** (`bin/elasticsearch --version`): controller (64 bit): Version 7.4.0 (Build 11d694e7bae395) Copyright (c) 2019 Elasticsearch BV

**Plugins installed**: none

**JVM version** (`java -version`): OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)

**OS version** (`uname -a` if on a Unix-like system): Linux 4.15.0-65-generic \#74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The rotation of GC logs doesn't appear to be working. I'd expect only one to be marked current, but currently three are.
```
-rw-r--r-- 1 elasticsearch elasticsearch 67109094 Sep 20 17:50 gc.log.0
-rw-r--r-- 1 elasticsearch elasticsearch  1218696 Oct  2 10:35 gc.log.0.current
-rw-r--r-- 1 elasticsearch elasticsearch 67109340 Sep 23 00:26 gc.log.1
-rw-r--r-- 1 elasticsearch elasticsearch 67109671 Sep 25 06:17 gc.log.2
-rw-r--r-- 1 elasticsearch elasticsearch 67109785 Sep 27 10:12 gc.log.3
-rw-r--r-- 1 elasticsearch elasticsearch 67109019 Sep 29 21:11 gc.log.4
-rw-r--r-- 1 elasticsearch elasticsearch 46899066 Oct  1 10:59 gc.log.5.current
-rw-r--r-- 1 elasticsearch elasticsearch 48996796 Sep  4 13:07 gc.log.6.current
```

**Steps to reproduce**:

Run elasticsearch for a while. Reboot server a few times.

**Comment by rjernst** [comment]
@OrangeDog Could you please expand on your reproduce steps? A more concrete list of commands/requests would be helpful in investigating this issue.

@pgomulka Would you please investigate this?

**Comment by OrangeDog** [comment]
> Could you please expand on your reproduce steps?

Not really. As you can see the modification times above are spread over a month. I've not done anything in that time except have the server running and occasionally reboot for kernel updates.

**Comment by pgomulka** [comment]
in jdk8 we use these jvm options for gc logging
```
8:-Xloggc:${loggc}
8:-XX:+UseGCLogFileRotation
8:-XX:NumberOfGCLogFiles=32
8:-XX:GCLogFileSize=64m
```
When you run ES, java will create gc log files gc.log.0, gc.log.1, gc.log2 etc (up to 32, then rolling back to 0) and the one that is currently being written to will be marked with `current`. In this example gc.log.3.current
Let's say you stop your app, your gc logs file are 
```
gc.log.0
gc.log.1
gc.log.2
gc.log.3.current
```
then you start again, java will start the rotation from the beginning. so you will end up with additional file gc.log.0.current
```
gc.log.0
gc.log.0.current
gc.log.1
gc.log.2
gc.log.3.current
``` 

This is a known limitation in jdk8, and was improved in jdk9+. With jdk9+ ES no longer create a current file and will continue the sequence from before the restart. For example
```
8289 Oct 11 10:34 gc9.log.00
8232 Oct 11 10:34 gc9.log.01
8210 Oct 11 10:34 gc9.log.02
8244 Oct 11 10:34 gc9.log.03
5059 Oct 11 10:34 gc9.log.04
restart
 8348 Oct 11 10:34 gc9.log.05
```
I have run my sample test with filesize 8K, note that previous file ended at 5K and java created a new file after restart

@OrangeDog I think upgrading to jdk9+ would help you, would you consider it?

**Comment by OrangeDog** [comment]
That's good to know. I'll be upgrading to jdk11 soonish.
