### ISSUE TITLE
Composite aggregation could avoid loading global ordinals entirely

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#47452]
Currently a `composite` aggregation on a keyword field will use global ordinals to ensure that comparisons between segments is fast. However the `composite` aggregation keeps track of the top N composite bucket so we should be able to use the segment ordinal when collecting inside a segment and map the top N to the next segment ordinals when we go to the next segment. Since N should be small the overhead of mappings these ordinals should be low and the big advantage is that we wouldn't require global ordinals to be loaded.

**Comment by boicehuang** [comment]
Is there any progress here?

**Comment by jakommo** [comment]
@nik9000 was talking to a user about this and I see you self assigned it a while ago. Is this still something on your list ?

**Comment by nik9000** [comment]
> @nik9000 was talking to a user about this and I see you self assigned it a while ago. Is this still something on your list ?

Sorry, not really. That was a speculative assignment and I ended up wandering off into another direction. Though @not-napoleon might be interested to read this as he's been spending more time with composite lately.

**Comment by wchaparro** [comment]
Reopening, as we still want to do this. This is pending benchmarks on composite, so marking as stalled at this time.

**Comment by wchaparro** [comment]
closing as not planned.
