### ISSUE TITLE
Update BouncyCastle FIPS provider to v1.0.2 for testing

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#47455]
Bouncy Castle's BC-FJA-1.0.2 is [certified](https://csrc.nist.gov/projects/cryptographic-module-validation-program/Certificate/3514) so we can update from 1.0.1 in our CI testing.

This release contains general performance improvements and fixes for the two issues we have reported: 
```
BC-FJA-1.0.1-15: Thai and Japanese locales confuse ASN.1 date recovery
BC-FJA-1.0.1-17: Java 11 fails to load provider if provider configuration string is used in java.security file
```

**Comment by jkakavas** [comment]
The new version seems to be more "entropy hungry" than the previous ones. In tests in my system, It quickly depletes available entropy ( measured via `/proc/sys/kernel/random/entropy_avail` )  and blocks before elasticsearch even has a chance to run.

**Comment by mr-samarjit-adhikari** [comment]
@jkakavas Agreed, so do require  java.security.egd=file:/dev/urandom in java.security file ?

**Comment by jkakavas** [comment]
Hi @mr-samarjit-adhikari, 

We'd like to keep this issue regarding our use of the library in our CI environment and not as a place for a general discussion for how to overcome the entropy needs of 1.0.2. This sounds like a user question, so if this relates to your use of elasticsearch in a FIPS 140 environment using the BouncyCastle crypto provider, feel free to open a post in our [discuss forums](https://discuss.elastic.co) or contact your support engineer if you are a customer. 

That said I'd start by reading section 2.3 in [BC user guide](https://downloads.bouncycastle.org/fips-java/BC-FJA-UserGuide-1.0.2.pdf) and maybe [this thread in their mailing list](http://bouncy-castle.1462172.n4.nabble.com/Issues-with-random-seeding-under-FIPS-td4659846.html)
