### ISSUE TITLE
BREAKING CHANGE - Range Query by Date Year returns no results

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#47473]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.0

**Plugins installed**: ["mapper-size"]

**JVM version** (`java -version`): using official docker image.

**OS version** (`uname -a` if on a Unix-like system):using official docker image.

**Description of the problem including expected versus actual behavior**:
Date range queries that were working in 5.x latest are no longer when we upgraded to Elastic 7.x
 
# Here are the exact scripts needed to create the sample for 5.x
```
PUT /test
{
    "mappings" : {
        "doc": {
          "properties" : {
              "mydate" : { "type" : "date" }
          }
        }
    }
}

POST /test/doc/
{
  "mydate": "2016-07-23T00:00:00"
}

GET /test/_search

POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

# This seems to be a bug as well. specifying any value in GTE returns the document.
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "201555",
                    "lte": "2019"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

# Here are the exact scripts needed to create the sample for 7.x

```
PUT /test
{
    "mappings" : {
        "properties" : {
            "mydate" : { "type" : "date" }
        }
    }
}

POST /test/_doc/
{
  "mydate": "2016-07-23T00:00:00"
}

GET /test/_search

POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

The query returns no results on 7.x but returns results on 5.x. Also as shown in the query example above, it seems like you can put any numeric value in 5.x on the `gte` query and it will return results.

Changing the Elasticsearch 7.x query to include the full date format for `lte` returns results (along with invalid `gte` values)

```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
or
```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015-01-01",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
``` 

or 
```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015555",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

I started digging into the formats and all breaking changes and all looks ok...  Interesting enough I noticed the following docs changed a bit and no longer talk as much about date range queries (between 6.x and 7.x
- https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-range-query.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.0/query-dsl-range-query.html

**Comment by jasontedor** [comment]
@pgomulka Can you take a look?

**Comment by pgomulka** [comment]
@niemyjski Thank you for this report. This is related to https://github.com/elastic/elasticsearch/issues/45284 bug where we don't parse partial dates as joda used to. The fix is now being in progress. I will update you once the work is done.
What is happening here behind the scene is that you have a field of type `date` which has a format defaulted to `"strict_date_optional_time||epoch_millis"` that means it expects a full date `2018-01-01` at minimum with optional time part, or a `long` to represent epoch millis. It used to be more relaxed in  6 & 5 versions. 
A work around for this would be if you update your mapping to be in this form `uuuu-MM-dd'T'HH:mm:ss.SSS||uuuu-MM-dd'T'HH:mm:ss.SSS||uuuu-MM-dd'T'HH:mm||uuuu-MM-dd'T'HH||uuuu-MM-dd'T'HH||uuuu-MM-dd||uuuu-MM||uuuu`

```
  "properties": {
    "mydate": {
      "type": "date",
      "format": "uuuu-MM-dd'T'HH:mm:SS||uuuu-MM-dd'T'HH:mm||uuuu-MM-dd'T'HH||uuuu-MM-dd'T'HH||uuuu-MM-dd||uuuu-MM||uuuu"
    }
  }
```
I realise that it would be an inconvenience.
Once again, the fix is in progress.

**Comment by niemyjski** [comment]
Thanks for the short term work around, any idea what might also be causing the `gte` bug?

**Comment by pgomulka** [comment]
you mean `it seems like you can put any numeric value in 5.x on the gte query and it will return results` ?
in ES 5&6 we were defaulting missing month and day if not provided in a date. So `2015` with `strict_date_optional_time` would be parsed as `2015-01-01`. This is the gap we will try to address in a fix

**Comment by niemyjski** [comment]
No, perhaps it needs a new bug issue. You can put any numeric value in it like `223423423423423423` and the query will still return a value... Seems like the GTE is not respected at all and this could be a query optimization because I can do a greater than query that's a higher number than the less than and it will return all the results and ignore the value (when this could be short circuited).

**Comment by pgomulka** [comment]
that would be indeed a bug. I confused though - this works as expected not returning results
```
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "223423423423423423",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
would you be able to provide a query that fails on the mapping we used earlier?

**Comment by niemyjski** [comment]
See the query examples above :-) in the original post

**Comment by pgomulka** [comment]
you mean this one? 
```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015555",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

as I mentioned in the previous comment. The default format is `strict_date_optional_time||epoch_millis` so it files to parse with first `strict_date_optional-time` and then it tries with `epoch_millis`. `2015555` epoch represents `24 January 1970 07:52:35`

**Comment by niemyjski** [comment]
yeah that one, it doesn't seem intuitive that it's doing that and it's not
what I want to do or what most people would want to do. I'd think if you
have a range query most likely both conditions would be in the same format.
Thanks
-Blake Niemyjski

**Comment by niemyjski** [comment]
@pgomulka did this make it into 7.4.1 as I don't see no mention of it in the release notes.

**Comment by pgomulka** [comment]
@niemyjski It will be released with 7.5

**Comment by niemyjski** [comment]
We really really need this change sooner than later, we have hundreds of date fields. I thought with the back port that it would make it in 7.4.1

**Comment by niemyjski** [comment]
I'm getting the following error using the workaround: `failed to parse date field [2019-11-04T07:01:06.3098957+00:00] with format [uuuu-MM-dd'T'HH:mm:SS||uuuu-MM-dd'T'HH:mm||uuuu-MM-dd'T'HH||uuuu-MM-dd'T'HH||uuuu-MM-dd||uuuu-MM||uuuu]` I'm guessing because of the format of the date. This is one more reason we need this fix deployed.

**Comment by pgomulka** [comment]
@niemyjski Yes, the milliseconds and timezone part is missing. Something like this below. Be careful with this format though. It is fragile and need to be tested. 
The 7.5 is coming soon, can't confirm the date unfortunately. 

uuuu-MM-dd’T’HH:mm:ss.SSS||uuuu-MM-dd’T’HH:mm:ss.SSSXXX||
uuuu-MM-dd’T’HH:mm:ss||uuuu-MM-dd’T’HH:mm:ssXXX||
uuuu-MM-dd’T’HH:mm||uuuu-MM-dd’T’HH:mmXXX||
uuuu-MM-dd’T’HH||uuuu-MM-dd’T’HHXXX||
uuuu-MM-dd||uuuu-MM-ddXXX||
uuuu-MM||uuuu-MMXXX

**Comment by niemyjski** [comment]
Thanks for some reason I cannot get this document to index. I've looked at the format docs and I have no idea It looks correct `failed to parse date field [2019-10-17T07:01:26.3488489+00:00] with format [uuuu-MM-dd'T'HH:mm:ss.SSSXXXXZZ||uuuu-MM-dd'T'HH:mm:ss.SSSXXXXZ||uuuu-MM-dd'T'HH:mm:ss.SSSXXXX||uuuu-MM-dd'T'HH:mm:SS||uuuu-MM-dd'T'HH:mm||uuuu-MM-dd'T'HH||uuuu-MM-dd'T'HH||uuuu-MM-dd||uuuu-MM||uuuu]` your help is greatly appreciated. I've tried many different formats.

**Comment by pgomulka** [comment]
so I think you have used incorrect pattern. You redundantly specified time zone twice (XXX and ZZ) https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

try using the one I provided in this comment https://github.com/elastic/elasticsearch/issues/47473#issuecomment-555191389

**Comment by niemyjski** [comment]
Yeah, no mater what I try it won't work:

```
DELETE test1
PUT /test1
{
  "mappings": {
      "dynamic_templates": [
        {
          "idx_date": {
            "match": "date*",
            "mapping": {
              "format": "uuuu-MM-dd'T'HH:mm:ss.SSSAAAAZ",
              "type": "date"
            }
          }
        }
      ]
  }
}

POST /test1/_doc/
{
  "date": "2019-10-17T07:01:26.3488489+00:00"
}
```

**Comment by pgomulka** [comment]
`uuuu-MM-dd'T'HH:mm:ss.SSSSSSSxxxxx` hm this does not seem right to be fair
The exact one I gave you was not working for you?
We rely on java.time package and the spec for patterns can be found here https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by niemyjski** [comment]
No it wasn't working, only the above parsed the date. I tried at least 100 different combinations

**Comment by pgomulka** [comment]
I see, you need SSSSSSS to parse 3488489, I missed that. At the same time you might have less 
if you replace SSS it should work
however it won't work if your part of second is just .1 
I don't have a work around for this. 

I guess the best way is just wait for 7.5 wich will be released soon

**Comment by pgomulka** [comment]
@niemyjski just wanted to let you know, that  7.5 elasticsearch is out and this bug is fixed there
https://www.elastic.co/blog/elastic-stack-7-5-0-released

**Comment by niemyjski** [comment]
Thanks, I'm going to verify this right now :)
