### ISSUE TITLE
Deprecated Warning in Elasticsearch 7.3.1

### ISSUE THREAD

**Issue by ashisheric** [elastic/elasticsearch#47490]
**Kibana version:**
7.3.1

**Elasticsearch version:**
7.3.1

**Logstash Version:**
7.3.1

**Describe Warning:**
Deprecation Logs not constantly raised, its raised first time when configure ELK.

**Warning Log:** 
[o.e.d.c.j.Joda           ] [elasticstack-data] Use of negative values in epoch time formats is deprecated and will not be supported in the next major version of Elasticsearch.

**Expected behavior:**
No deprecation warnings should be raised, I have used ELK version 7.3.1

**Comment by ywelsch** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
