### ISSUE TITLE
[Discuss] Restructure monitoring documentation

### ISSUE THREAD

**Issue by cachedout** [elastic/elasticsearch#47509]
This is a discussion issue to work through a series of high-level questions about the structure of the Monitoring documentation for Elasticsearch.

### Exporters vs. Metricbeat

Below is a screenshot from a page in the [documentation describing how to monitor Elasticsearch in production](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-production.html):

<img width="765" alt="which?" src="https://user-images.githubusercontent.com/111616/66129387-59e29500-e5df-11e9-801a-cbbc97f22ff9.png">

It is not clear from look at the above that one should choose one OR the other (but not both).

Click on the link to Metricbeat monitoring does, correctly, take a user to a page where Metricbeat monitoring configuration is described. However, clicking on `Use HTTP exporters` leads to a more confusing experience. If one clicks on this link, they  are [taken to this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-monitoring.html):

<img width="414" alt="overview" src="https://user-images.githubusercontent.com/111616/66129935-63b8c800-e5e0-11e9-8905-062fe145e2e9.png">

But then clicking on the `Overview' [link lands a person here](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-overview.html):

<img width="810" alt="overview_page" src="https://user-images.githubusercontent.com/111616/66130077-a5e20980-e5e0-11e9-8de0-863dcf2a98ce.png">

As one can see from the above, this page doesn't even mention internal collection  and instead references Metricbeat collection.

This problem exists elsewhere, throughout the documentation, such as in the links to both `Collecting monitoring data` and `Collecting monitoring data with Metricbeat` [found here](https://www.elastic.co/guide/en/elasticsearch/reference/current/how-monitoring-works.html).

Before putting together a PR, I wanted to raise this as a discussion issue to try to collect consensus on a plan to remedy this. I'll try to frame this discussion through a series of questions.

1. Is there still a need going forward to maintain public documentation for internal collection? We don't intend to _remove_ internal collection until 8.0, but, given that the documentation would remain online for previous versions of the stack, could we accelerate the transitions by assuming that all new users should be using Metricbeat collection and would this be well-served by not giving them the option to read about internal collection?

2. With the introduction of the Migration Wizard to the Stack Monitoring application, should we also introduce documentation pages which assist people in migrating from  internal collection to Metricbeat collection, either via the  wizard  or by hand?

3. If we do choose to keep documentation online for both internal collection and for Metricbeat collection, how could we remedy the problems described above?

cc: @elastic/stack-monitoring @lcawl @karenzone

**Comment by cachedout** [comment]
I have opened a draft PR for this: https://github.com/elastic/elasticsearch/pull/47818

**Comment by debadair** [comment]
[docs issue triage]

I think we should:

- Treat Metricbeat as the default for new users. 
- Provide information about switching for existing users.
- Fix the circular nav problems introduced when we moved things around.

**Comment by Rileyb-cnu** [comment]
1. I believe that we need to keep the documentation for internal collection for users who choose to use an older version of the software. That said, I feel like it would be less confusing to new users to hide it within some sort of archive.

2. Having information to use the wizard would prove very helpful to existing users, I agree with @debadair .

3. When going to the configuring monitoring page, I suggest a link to both the internal collection and Metricbeat collection (the current link) with it being clear that the internal collection would only work with earlier versions of Elasticsearch. Though dropping this feature entirely would be beneficial to size and reduction in complexity, there are still limited uses in which a user would want to reference the internal collection.

**Comment by debadair** [comment]
Closing as won't fix, as the necessary changes are not as described here.
