### ISSUE TITLE
Intermittent failures in getting started guide on call to _cat/health

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#47537]
There's been an intermittent failure since roughly Oct. 1 where a call to `GET _cat/health?v` (from the getting started guide) doesn't match the regex it should be matching.

[Build scan](https://gradle-enterprise.elastic.co/s/5os3yu7ddneb6/tests/jbm2x6tnwtxku-ior7e5flcvvj6)

Error:
```
Failure at [reference/getting-started:15]: field [$body] was expected to match the provided regex but didn't
Expected: epoch      \s+timestamp \s+cluster       \s+status \s+node.total \s+node.data \s+shards \s+pri \s+relo \s+init \s+unassign \s+pending_tasks \s+max_task_wait_time \s+active_shards_percent\s* \d+ \s+\d+:\d+:\d+ \s+integTest \s+green           \s+\d+         \s+\d+      \s+\d+   \s+\d+    \s+0    \s+0        \s+0             \s+\d+                  \s+(-|\d+(micros|ms|s))                \s+100.0%\s*
     but: was "epoch      timestamp cluster   status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent\n1570139444 21:50:44  integTest green           1         1      0   0    0    0        0             2              9.3ms                100.0%\n"
```

Reproduce line (does not reproduce locally):
```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/getting-started/line_169}" -Dtests.seed=3C57F50F2442A596 -Dtests.security.manager=true -Dtests.locale=bs-Cyrl -Dtests.timezone=America/Argentina/San_Juan -Dcompiler.java=12 -Druntime.java=11
```

What it gets back looks reasonable at a glance, though I haven't dug in - might be an issue with the regex? I'm not sure if any changes were made to the _cat APIs recently that might have triggered this.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by henningandersen** [comment]
One more failure here:

https://gradle-enterprise.elastic.co/s/kms7qb7vdpys4/tests/jbm2x6tnwtxku-ior7e5flcvvj6

looks like it fails around twice a week:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'getting-started%20AND%20epoch'),sort:!(time,desc))
