### ISSUE TITLE
Asymmetry between supported point format in geo_point and geo_shape field types

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#47535]
Right now `geo_point` can be defined in multiple formats:

- `"POINT(0 0)"`, WKT
- `{ "lat": 0, "lon": 0}`, lat/lon object
- `[0, 0]`, [lon, lat] array
- `"0, 0"`, (lat, lon) string
- `"gbsuv"`, geohash

Since `geo_shape` supports point types, it may make sense to also support `geo_point` formats as field values for this field type.

relates to #47243, where it would be nice to match either geo_point or geo_shape values.

**Comment by talevy** [comment]
We discussed this in our Analytics/Geo team meeting and concluded that it would be clearer if the parsing of geo fields were consolidated together. This means that all valid `geo_point` field value formats will also be valid `geo_shape` field value formats, which will be indexed as `Point`/`MultiPoint` geometries. This will enable more flexible support for indexing the same field as both `geo_point` and `geo_shape` without modifying the value (even as a multi-field).

As part of this, GeoJSON will also be supported by the geo_point field (see https://github.com/elastic/elasticsearch/issues/47815).

**Comment by craigtaverner** [comment]
Documentation PR at https://github.com/elastic/elasticsearch/pull/86066 takes us one step closer, but we still need to remove documentation for the older, soft-deprecated, formats.

**Comment by craigtaverner** [comment]
A new PR should address this issue: https://github.com/elastic/elasticsearch/pull/86835
