### ISSUE TITLE
indices_boost ignore aliasing

### ISSUE THREAD

**Issue by fdejaeger** [elastic/elasticsearch#4756]
It looks that the top level boosting based on the indices (_indices_boost_) requires that we specify the exact index name.  We cannot substitue an alias pointing to a given index.  This is very inconvenient since it defeats the purpose of having aliases to hide internal organization of the indices.

**Comment by sschwell** [comment]
+1

**Comment by tdoman** [comment]
+1, has this been addressed yet?  i must be able to use the alias.

**Comment by EgorZhuk** [comment]
+1

**Comment by dabit** [comment]
Has this been addressed? Please don't tell me this has not been fixed. Just bumped into it in production.

**Comment by splittingfield** [comment]
+1 as we have just hit this surprising behavior in production as well.

**Comment by masaruh** [comment]
Things to consider:
- should wildcard expansion be supported as well? (probably yes)
- what if an index belongs to more than one alias in indices_boost parameter? For example, `"indices_boost": {"alias1": 3,"alias2": 2}` and both aliases include `index1`. (sum boost? max? min?)

**Comment by thiagolocatelli** [comment]
It seems the option to add indices_boost with the java client is not available. Is this true? I am using spring-data-elasticsearch and I cant seem to find a way to add indices_boots to my query. Thank you.

**Comment by davibe** [comment]
+1

**Comment by ramseydsilva** [comment]
I would like support for wildcard expansion as well.

:+1:

**Comment by LoooooKe** [comment]
+1

**Comment by gcds** [comment]
Any updates on these? @clintongormley ?

**Comment by bjorn-ali-goransson** [comment]
Calling all devs. @clintongormley @kimchy Is this for real?

**Comment by thehybridtechnician** [comment]
+1

**Comment by clintongormley** [comment]
This change stalled because of the problem of figuring out what to do when an index is boosted more than once via an alias or wildcard.  From https://github.com/elastic/elasticsearch/pull/8811#issuecomment-258675219 : 

@masaruh just reread this thread and i think the correct answer is here:

> Make indices_boost take list of index name and boost pair. We may need to do this if we want to have full control. But I somewhat hesitate to do this because it's breaking change.

Then the logic would be that we use the boost from the first time we see the index in the list, so eg:

    [  
      { "foo" : 2 },  # alias foo points to bar & baz
      { "bar": 1.5 }, # this boost is ignored because we've already seen bar
      { "*": 1.2 }      # bar and baz are ignored because already seen, but index xyz gets this boost
    ]

This could be implemented in a bwc way. In fact, the old syntax doesn't need to be removed. We could just add this new syntax as an expert way of controlling boosts.

What do you think?

**Comment by masaruh** [comment]
Ooh, true. that should work! Thanks @clintongormley.
I'll see what I can do.
