### ISSUE TITLE
[Feature] extract bots in useragent module

### ISSUE THREAD

**Issue by hiaselhans** [elastic/elasticsearch#47568]
To me it seems pretty helpful to be able to receive a boolean "is_bot" from the ingest-useragent  module.
That way one can easily filter these without demanding wildcard queries.

Would a pull request have chances to be merged for this..?

**Comment by tlrx** [comment]
Hi @hiaselhans! I might be out of date, but I don't think that there's a single standard way to detect bots from user agent information? I think that in any case you have to rely on a predefined set of identifiers?

Before opening a pull request maybe you could expand on how you'd like to implement the feature?

**Comment by hiaselhans** [comment]
Hi @tlrx!

thanks for the answer. 
There might be no standard way to do it but for me a simple check for the words ("bot", "spider") works pretty good. in my user agents, when i filter for the bot boolean i have only real browsers left.
It's just additional information at more less no cost for me.

here's what i did in my pipeline:

`

      "script": {
        "source": "if (ctx.request?.user_agent != null){ boolean bot = false; String user_agent = ctx.request.user_agent.toLowerCase(); if (user_agent.contains('bot') || user_agent.contains('spider')) {bot = true;} ctx.request.browser.bot = bot;}"
      }
`

**Comment by tlrx** [comment]
Thanks @hiaselhans for your detailed response!

> Would a pull request have chances to be merged for this..?

Because there's no standard way to detect robots user agent, I don't think that a PR which searches for `bot` or `spider` and adds a field is likely to be accepted (what do you think @jakelandis?).

What you are doing today using script is the right thing to do. Note that we're working on the Enrich processor (see #32789) and this feature could also be used in the future to lookup user agents from an Elasticsearch index and tag them as robots :)

**Comment by martijnvg** [comment]
I'm also not sure whether checking for the existence of `bot` or `spider` in the user agent string is something that should be a built-in feature in the useragent processor. I will label this issue as team-discuss and get back to this.

**Comment by martijnvg** [comment]
I'm closing this issue. Just checking whether a `bot` or `spider` phrase occurs in the useragent name isn't sufficient for the this processor to automatically detect whether a useragent is a bot. That decision should be made in [the upstream uap-core project](https://github.com/ua-parser/uap-core). If this basic/incomplete bot detection is desired then that should be done by using the `script` processor.

**Comment by hiaselhans** [comment]
ok. no worries.
Do you think it is worth to put a PR for the corresponding docs or just drop it?
