### ISSUE TITLE
The json output may differ if the response went through the transport protocol

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#47574]
In case a component breaks a surrogate pair the json output will differ if the response goes through the transport protocol serialization vs being encoded directly into json.

We see this behavior because of a bug in the custom highlighter we use: it may break surrogate pairs:

When going through the transport protocol the output looks like (note the tofu char): 
`"text":["注意：本页面含有Unihan新版用字。有关字符可能會错误显示，詳见Unicode扩展汉字。 六疊字是指漢字中一類由六個完全相同的部分所组成的疊字。大多數的六疊字亦可以被視為兩個三疊字或三個二疊字的組合。 現將已知的此類字列於下表： 疊字 二疊字 三疊字 四疊字 五疊字 八疊字 ZDIC.NET. �"]`
and is properly parsed by the client.

But when targeting the node that holds the shard (directly encoding to json) the output looks like:

`"text":["注意：本页面含有Unihan新版用字。有关字符可能會错误显示，詳见Unicode扩展汉字。 六疊字是指漢字中一類由六個完全相同的部分所组成的疊字。大多數的六疊字亦可以被視為兩個三疊字或三個二疊字的組合。 現將已知的此類字列於下表： 疊字 二疊字 三疊字 四疊字 五疊字 八疊字 ZDIC.NET. \uD847"]`
and causes parse failures by most json parsers.

It is unclear to me if this is worth fixing by making sure that whether or not the transport protocol is being used the response should be identical so feel free to close.

**Comment by tlrx** [comment]
> But when targeting the node that holds the shard (directly encoding to json) the output looks like:

Hi @nomoa - In this case you are referring to the REST API right? If so, what client are you using to execute the request?

**Comment by nomoa** [comment]
It is in the highlight response, the json parsers that I use and fail are `jq` and json_decode from php 7.2.

Could it be caused by the fact that because SearchHit uses the Text object for storing strings and that the writeText/readText simply use [String#getBytes(UTF8)](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java#L388) it will replace unmapable chars (e.g. broken surrogates) [with a default char](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes%28java.nio.charset.Charset%29) when going through the transport protocol?

The method writeString/readString methods do not seem affected by this as they seem to own the char->byte encoding.

**Comment by rjernst** [comment]
All the builtin text handling read/write methods for StreamInput/Output as well as xcontent operate under the assumption of using utf8. When you say that you have a custom highlighter, do you mean your own highlighting code? Are you constructing `Text` objects with  the constructor taking `BytesReference` with bytes that are not utf8 encoded?

**Comment by nomoa** [comment]
We use our own Highlighter but we use the `Text(String)`.

Here is a small test case to illustrate the inconsistency between the readText/writeText vs the readString/writeString behaviors.

```java
    @Test
    public void testText() throws IOException {
        String str = "\uD82D\uDC4A".substring(0, 1); // broken component: breaks surrogate
        Text text = new Text(str);

        // Run a simple Text -> json using XContentBuilder
        ByteArrayOutputStream jsonOutputBytes = new ByteArrayOutputStream();
        XContentBuilder builder = new XContentBuilder(JsonXContent.jsonXContent, jsonOutputBytes);
        builder.startObject().field("text", text).endObject().close();
        String directTextThroughRest = new String(jsonOutputBytes.toByteArray(), "UTF-8");

        // Mimic a roundtrip using the transport protocol
        // Serialize a Text using StreamOutput then write it to json
        BytesStreamOutput transportOut = new BytesStreamOutput();
        transportOut.writeText(text);
        transportOut.close();
        Text transportedText = StreamInput.wrap(transportOut.bytes().toBytesRef().bytes).readText();
        jsonOutputBytes = new ByteArrayOutputStream();
        builder = new XContentBuilder(JsonXContent.jsonXContent, jsonOutputBytes);
        builder.startObject().field("text", transportedText).endObject().close();
        String transportedTextAndRest = new String(jsonOutputBytes.toByteArray(), "UTF-8");
        Assert.assertEquals(directTextThroughRest, transportedTextAndRest);
    }

    @Test
    public void testString() throws IOException {
        String str = "\uD82D\uDC4A".substring(0, 1); // broken component: breaks surrogate

        ByteArrayOutputStream jsonOutputBytes = new ByteArrayOutputStream();
        XContentBuilder builder = new XContentBuilder(JsonXContent.jsonXContent, jsonOutputBytes);
        builder.startObject().field("text", str).endObject().close();
        String directStringThroughRest = new String(jsonOutputBytes.toByteArray(), "UTF-8");

        BytesStreamOutput transportOut = new BytesStreamOutput();
        transportOut.writeString(str);
        transportOut.close();
        String transportedStr = StreamInput.wrap(transportOut.bytes().toBytesRef().bytes).readString();
        jsonOutputBytes = new ByteArrayOutputStream();
        builder = new XContentBuilder(JsonXContent.jsonXContent, jsonOutputBytes);
        builder.startObject().field("text", transportedStr).endObject().close();
        String transportedStrAndRest = new String(jsonOutputBytes.toByteArray(), "UTF-8");
        Assert.assertEquals(directStringThroughRest, transportedStrAndRest);
    }
```

testText fails with:
```
org.junit.ComparisonFailure: 
Expected :{"text":"\uD82D"}
Actual   :{"text":"�"}
```

In other words:
a Text going through the serialization mechanism may have it's content modified by the nature of String#getBytes() as opposed to StreamOutput.writeString() that properly owns the encoding of the char array.

**Comment by rjernst** [comment]
Thanks for the explanation @nomoa. This looks like something your highlighter needs to account for when constructing Text objects. We assume the String is encodable. Since Java's getBytes method is what does the encoding, and also does the translation of invalid codepoints, there isn't anything we can really do. As such, I hope you don't mind I close this issue.
