### ISSUE TITLE
BulkProcessor can deadlock when bulk requests fail

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#47599]
If the [BulkProcessor](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java) results in failed bulk requests, they will be retried via the [RetryHandler](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/Retry.java#L143). In versions of Elasticsearch prior to 7.3.0 this can result in a deadlock. 

The deadlock can happen due to the `Scheduler` which is shared between the `Flush` and `Retry` logic. The deadlock can happen because the `Scheduler` is configured with 1 worker thread which can be blocked in the `Flush` method. The `Flush` method is guarded by [synchronized (BulkProcessor.this)](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java#L408) , but the [internalAdd(..)](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java#L324) method is also blocked by the same (synchronized) monitor lock. What can happen is that a bulk request comes in through `internalAdd` obtains the lock, the bulk request is sent and a failure occurs, so the retry logic kicks in.  The scheduler thread is blocked in the `Flush` method due to the `internalAdd`'s hold on the synchronized block , so now when the retry attempts to schedule a retry, it can not because the `Flush` is blocking the only worker thread for the scheduler. So here `Flush` can not continue because it is waiting on `internalAdd` to finish, and `internalAdd` can not finish because it waiting on `Retry`, but `Retry` can not finish because it is waiting on a scheduler thread which it can not obtain because it is waiting on `Flush` to finish. 

The change in 7.3.0 fixes this issue because it is much more selective about exactly what is locked, and no longer wraps the execution of the bulk request inside the lock. 

Until `7.3.0` the only workaround is to set the [BackOffPolicy](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/BackoffPolicy.java) to `BackoffPolicy.noBackoff()` so that the `Retry` does not kick in. The default backoff is `BackoffPolicy.exponentialBackoff()` which is used by Watcher and is not configurable and thus is susceptible to this bug pre `7.3.0`

This is related to [https://github.com/elastic/elasticsearch/pull/41418](https://github.com/elastic/elasticsearch/pull/41418) butthe fix for that does not fix this issue. This issue is fixed by [https://github.com/elastic/elasticsearch/pull/41451](https://github.com/elastic/elasticsearch/pull/41451) in 7.3.0.

EDIT: see below for a case where this can still happen in 7.3.0+ (_if the flush documents themselves fail_)

**Comment by jakelandis** [comment]
Thanks to @SuXingLee for finding this issue and providing a test case on #46790.  

I logged this issue as reference point and will close out this issue as fixed by #41451 in 7.3.0. I will evaluate if Watcher needs to implement the workaround for older versions in a different PR.

**Comment by SuXingLee** [comment]
Thank you for your reply. 
> Until `7.3.0` the only workaround is to set the [BackOffPolicy](https://github.com/elastic/elasticsearch/blob/v6.8.3/server/src/main/java/org/elasticsearch/action/bulk/BackoffPolicy.java) to `BackoffPolicy.noBackoff()` so that the `Retry` does not kick in.

PS: Another workaround is not to set the bulk flush interval.

**Comment by SuXingLee** [comment]
@jakelandis 
After modifying the test case: when the `Flush` logic is executed first and a failure occurs. I found that it seems that a similar problem still occurs in the latest version of ES.  #48013 is the newest test case in master branch. I am not sure and hope you can verify it.

**Comment by jakelandis** [comment]
Re-opening issue since as @SuXingLee points out this can still happen if the documents that flush is flushing fail. 

In the original description and what is fixed in 7.3.0 is "normal requests" fail -> Flush kicks in but is blocked by the request that failured -> Retry tries to happens but is blocked by Flush.  The more granular locking fixes that deadlock case.  

Here, the question is what happens if the "Flush request" fail (which grabs the lock and only slot in the scheduler), and the Retry attempts to kick in. Retry can't run because the one and only slot in the scheduler is consumed by Flush, but Flush is waiting on the Retry to finish.  Hence the deadlock. 

The workarounds are the same, disable Flush (pass null) , or disable Retry (use `BackoffPolicy.noBackoff()`). 

@SuXingLee - thanks again for the test that illustrates this.  I am still weighing the options of increasing single scheduler number of slots vs. using separate schedulers for flush and retry.
