### ISSUE TITLE
Encryption at rest builds failing for 7.x branch due to insufficient disk space

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#47607]
Our encryption at rest builds run in a [40GB encrypted volume](https://github.com/elastic/infra/blob/0198dc922ce03387703c6e200f1c39eab20b3947/ci/jjb/elasticsearch-ci/globals/macros/builder.yml#L103). It seems for `7.x`, which has many BWC versions, this isn't enough space for the build to successfully complete. We should probably increase the size of this volume if possible.

https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.x/job/elastic+elasticsearch+7.x+EAR/160/consoleFull

**Comment by mark-vieira** [comment]
@atorok Can we just bump this volume size? How much space do we have to place with on these workers?

**Comment by mark-vieira** [comment]
pinging @atorok, any thoughts on this one?

**Comment by atorok** [comment]
Sorry I  neglected to close the issue. The space in the encrypted volume was doubled, and we are no longer seeing this issue.
