### ISSUE TITLE
Optimize terms query when put in a must_not (negative) clause

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#47698]
This is a spinoff of https://github.com/elastic/elasticsearch/issues/14335 with a narrowed scope. Today the `terms` query creates a bitset of the matching documents eagerly in order to be able to intersect the result with the other parts of the query. This is very efficient if the `terms` query is put in a positive clause but can be very expensive when put under a `must_not` clause. In this case the current execution is not optimal especially if it matches only a few documents from the other clauses. It would be more efficient in such situation (`terms` query in a `must_not` clause) to run the query as a `DocValuesTermsQuery` that would only check if the document should be excluded or not based on the content of doc values.
As discussed in the previous issue this feature would be simpler to implement in Elasticsearch where we can rely on the schema to decide which execution should be preferred. This would allow to use the `terms` query as a negative clause efficiently instead of relying on a script  query that doesn't have the ability to lookup the list of terms to blacklist in a different index.

**Comment by mayya-sharipova** [comment]
Relevant issue: https://github.com/elastic/elasticsearch/issues/74954

**Comment by javanna** [comment]
thanks @mayya-sharipova at first glance they look like exactly the same issue? Shall we close one in favour of the other?

**Comment by javanna** [comment]
Closing in favour of #74954
