### ISSUE TITLE
Stricter validation for _cat APIs

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#47755]
Currently all `_cat` APIs support the same set of HTTP parameters. Some parameters such as `time` and `bytes` do not influence the output of the actual API call. For example `_cat/alias` does not have time nor bytes in the output, but `time` and `bytes` are accepted inputs. 

Further, the value of the parameters are not validated. For example, no error is raised on `GET _cat/recovery?time=foobar&v` where `foobar` is _not_ a valid value for the `time` parameter. 

Ideally we would not let users ask for something that has no impact or allow them to provide values that are invalid.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
