### ISSUE TITLE
v7.4.0 REST API specs removed url params

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#47768]
Relates: https://github.com/elastic/elasticsearch-net/pull/4117

A number of URL parameters have been removed in v7.4.0 REST API specs

1. **delete_by_query**: `"analyzer"`

    - 7.3: https://github.com/elastic/elasticsearch/blob/7.3/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json#L28-L31
    - 7.4: https://github.com/elastic/elasticsearch/blob/7.4/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json

2. **msearch_template**: `"ccs_minimize_roundtrips"`

    - 7.3: https://github.com/elastic/elasticsearch/blob/7.3/rest-api-spec/src/main/resources/rest-api-spec/api/msearch_template.json#L44-L48
    - 7.4: https://github.com/elastic/elasticsearch/blob/7.4/rest-api-spec/src/main/resources/rest-api-spec/api/msearch_template.json

3. **search_template**: `"ccs_minimize_roundtrips"`

    - 7.3: https://github.com/elastic/elasticsearch/blob/7.3/rest-api-spec/src/main/resources/rest-api-spec/api/search_template.json#L78-L83
    - 7.4: https://github.com/elastic/elasticsearch/blob/7.4/rest-api-spec/src/main/resources/rest-api-spec/api/search_template.json

Many of the clients generate source code using the REST API specs, so the removal of parameters in a minor version can manifest as an API breaking change in the client. 

Looking at v7.4.0 tagged commit, it looks like all parameters are still valid, so should be reinstated.

**Comment by rjernst** [comment]
It looks like https://github.com/elastic/elasticsearch/pull/42346 removed this, probably inadvertently? @javanna can you comment on the reason these were removed?

**Comment by javanna** [comment]
I don't know about those specific params that were removed and why, probably @karmi can double check that as he worked on the spec change itself. If those params are still supported, they should indeed be reinstated.

**Comment by karmi** [comment]
I'm afraid I don't have a good explanation why those particular parameters would be removed — I've used a script to manipulate the JSON structures, and it seems weird that three parameters out of hundreds would be mishandled. My bet would be on some Git rebase / other surgery on the patch, it's been a bit of a painful process.

@russcam , can you please add those parameters back to the specification, anyone from us can approve it, and then you can backport it to the 7.x branches, in order to remove any overrides you might need when generating the .NET client?

**Comment by rjernst** [comment]
It looks like at least the analyzer param for delete_by_query still exists in master, so this seems to be something that got messed up on backport. Just FYI to ensure this gets fixed in all necessary branches (7.x and 7.4 at least, maybe master for the others as well).

**Comment by javanna** [comment]
I had another look and I think that this was a problem introduced during backport (#45624), not sure what happened, probably a bad merge. These params need to be restored. @russcam let me know if I can do anything to help.

**Comment by SortingLee** [comment]
Is there a criterion for the query to be deleted?
also How do you know what the expected effect is?

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/52544 to address

**Comment by javanna** [comment]
I believe this should be closed given the corresponding PR is merged.

**Comment by russcam** [comment]
thanks @javanna
