### ISSUE TITLE
ElasticSearch 7.4 launch error

### ISSUE THREAD

**Issue by Luke7810** [elastic/elasticsearch#47769]
**Describe the feature**:

**Elasticsearch version** : 7.4

**Plugins installed**: NA

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**:
When I lunch ES, using command /bin/elasticsearch, we got follow error:

Exception in thread "main" java.lang.NullPointerException        at org.elasticsearch.tools.launchers.JvmErgonomics.extractHeapSize(JvmErgonomics.java:126)        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:58)        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
--

**Comment by jimczi** [comment]
@Luke7810 it is difficult to diagnose this issue without more info. We have tests with java 8 with all our support jdk vendors so it is likely an issue with your java vendor.
Additionally, it is better to start discussions about possible bugs on our forums. We try to keep github reserved for feature requests and confirmed bug reports so I'd be happy to help in the [discuss forum](https://discuss.elastic.co/t). Please start a new topic explaining the java version you used as well as how you installed it and where it comes from.
