### ISSUE TITLE
TextFieldMapperTests.testFastPhraseMapping fails during Lucene 8.3.0 upgrade

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#47777]
The test contains a work around for  https://github.com/elastic/elasticsearch/issues/43976 which is fixed in this new Lucene version. The test fails for that reason so it has been disabled for the upgrade and it needs to be fixed once https://github.com/elastic/elasticsearch/pull/47770 is merged.

**Comment by zacharymorn** [comment]
Hi @iverase looks like you already merged #47770. I can take a look at this issue.
