### ISSUE TITLE
Add graphical explanation on geo queries 

### ISSUE THREAD

**Issue by marekduciuc** [elastic/elasticsearch#47781]
**Describe the feature**:

Would be good to add graphical explanation filters and queries on these pages:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/geo-queries.html

**Comment by debadair** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.
