### ISSUE TITLE
Add a PR  check for Windows

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#47794]
Add a light weight windows PR check that does not extend the overall time the checks take, and uses one additional CI worker to run a subset of tests that will possibly break on windows (e.x. unit tests, some internal cluster tests).

Introduce a new  label, example `check-all` and `check-all-windows`. 
Both will enable a full windows run on the PR, but the first implies that all such checks will be run. 
This implies that we will add others in the future, like `check-all-packaging` and `check-all-bwc`.

**Comment by atorok** [comment]
https://gradle-enterprise.elastic.co/s/jsyi4lgipyxqi is running just the `test` task on Windows, took 21 minutes, I was hopping it will be faster.  
In light of that, I think we should consider adding a `checkPart1` and `checkPart2` into intake instead.

**Comment by mark-vieira** [comment]
After discussing this in our weekly we've opted against adding early Windows checks for now. We felt it the benefits just weren't sufficient to justify the additional cost here at this time. We may at some point revisit this later.
