### ISSUE TITLE
Improve the organization of our tests

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#47802]
We started down this path and have the testing conventions task to check a few things, but there's still a few things that we discussed but didn't get to implement. 

- [ ] better support hierarchies in testing conventions.  Assert that tests don't match base classes from other suffixes unless these are in a hierarchy.  We configure `Tests` as `EsTestCase` and `IT` as `ESRestTestCase`, but the lather extends the former, so `Tests` could also have `ESRestTestCase`. We need to detect and prevent this. 
- [ ] better separate unit tests from internal cluster tests and rest tests, either by using a different class naming conventions and renaming existing tests, or by moving them to separate source sets. 
- [ ] consolidate the  configuration of different types of tests so the testing tasks are added and wired automatically if tests of a certain kind are present in a project. Right now  these are defined in the project themselves. 
- [ ] it would be great if we could check that any test task is eventually ran, e.x. by checking that the task is a dependency of check, or some other configurable task like `bwcTask`
- [ ] check that tests are not ran multiple times by default with a way to disable this for bwc tests 
- [ ] replace internal cluster tests that actually talk to an external cluster with a proper rest test

**Comment by mark-vieira** [comment]
> replace internal cluster tests that actually talk to an external cluster with a proper rest test

I wasn't aware this was a thing. Can you point me at an example of this?

**Comment by atorok** [comment]
@mark-vieira anything that references `tests.cluster` sysprop. 
We should not need to pass that in. Look at `ESIntegTestCase.TESTS_CLUSTER` and `buildTestCluster` and `buildExternalCluster` this whole thing should not exist.
So any test that runs via a `RestIntegTestTask` and extends `ESIntegTestCase` falls into this category. I'we been meaning to create a list, but didn't get to it yet.

**Comment by mark-vieira** [comment]
So those tests spin up an embedded ES instance but don't use it? They instead talk to the external cluster? If so, is there a specific reason those tests don't extend `ESRestTestCase` instead?

**Comment by atorok** [comment]
I'm not sure if the internal cluster is actually spin up or that's circumvented as well but it's definitely unused.  The reason is historic, `ESRestTestCase` didn't exist when this was first used, then it was I assume unknowingly replicated for newer projects as well which could have used it.  

On complication in fixing this is that  these tests use the transport client instead of the rest client. I haven't looked at the effort required to change that.

**Comment by mark-vieira** [comment]
I'm closing this as this issue is so large in scope it's unlikely to ever be addressed entirely. That said, must of this has been done by the work to introduce individual testing plugins for different test types.
