### ISSUE TITLE
Incorrect source in  elasticsearch-sql-cli

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#47803]
One can't start the tool from any working directory.

Here's a reproduction
```
# create a test cluster
./gradlew run
cd distribution/build/testclusters/runTask-0
ES_CONFIG_PATH=$PWD/config ./distro/8.0.0-DEFAULT/bin/elasticsearch-sql-cli
# Fails with : ./distro/8.0.0-DEFAULT/bin/elasticsearch-sql-cli: line 9: ./distro/8.0.0-DEFAULT/bin/x-pack-env: No such file or directory
cd distro/8.0.0-DEFAULT
ES_CONFIG_PATH=$PWD/../../config ./bin/elasticsearch-sql-cli
# works
```

The reason for this is that  `source "`dirname "$0"`"/elasticsearch-env` changes the working directory to `$ES_HOME` so I think the second source should just be 
```
source ./bin/x-pack-env
```

Would be nice to add some packaging tests to `qa/os` to make sure the tool can be called from different places.

**Comment by q2dg** [comment]
If it's called from "home" folder (that is, from "/usr/share/elasticsearch" folder, writing this:: **./bin**/elasticsearch-sql-cli), it works

**Comment by annirathore** [comment]
I am getting below error during run ./bin/elasticsearch-sql-cli

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR: Cannot communicate with the server http://localhost:9200/. This version of CLI only works with Elasticsearch version v7.5.1 [3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96]

**Comment by bpintea** [comment]
> ERROR: Cannot communicate with the server http://localhost:9200/. This version of CLI only works with Elasticsearch version v7.5.1 [3ae9ac9]

@annirathore you will find usage help on the discussion forum: [discuss.elastic.co](https://discuss.elastic.co/).
