### ISSUE TITLE
Update CCR docs with latest UI

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#47822]
In 6.7 and 7.0, we added the ability to [manage follower indices in CCR](https://github.com/elastic/kibana/pull/27936). The [current docs](https://www.elastic.co/guide/en/elastic-stack-overview/current/ccr-getting-started.html#ccr-getting-started-auto-follow) reflect an [older UI](https://github.com/elastic/kibana/pull/26777), in which the user can only manage auto-follower patterns. We need to update the docs to reflect the current functionality and backport this update to 6.7.

CC @gchaps

**Comment by lcawl** [comment]
The CCR documentation now exists in the elasticsearch repo, so I've transferred this PR

**Comment by jrodewig** [comment]
[docs issue triage]
