### ISSUE TITLE
Extends geo_shape query docs to explain the behaviour when data is indexed as an array of shapes

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#47845]
When data is indexed in a geo_shape field as an array of shapes, for example:

```
POST /test/_doc
  "location": [
    {
      "coordinates": [0.0,0.0],
      "type": "point"
    },
    {
      "coordinates": [1.0,1.0],
      "type": "point"
    }
  ]
}
```

The shape is treated as a one shape so this is equivalent to index the following shape:

```
POST /test/_doc
  "location": 
    {
      "coordinates": [[0.0,0.0],[1.0,1.0]],
      "type": "multipoint"
    }
}
```

This is counter-intuitive as all other fields treat every element of the array independently so we should add this behaviour to the documentation.

**Comment by debadair** [comment]
[docs issue triage]
