### ISSUE TITLE
Supporting early failure of new pipeline creation

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#47852]
As it stands right now, when a pipeline is created, there is no way of knowing if the `Processor.Factory#create` method is being called from a new pipeline creation or from a new node being spun up on the cluster. 

This information would be helpful (along with the latest cluster state) to facilitate failing processor creation early if not all the nodes support the processor (and its configuration). Failing early in this manner will be good for user experience, and allow the processor authors tailor their message given the minimum node version of the cluster and the configuration object provided.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
