### ISSUE TITLE
Sanitise slow log's request source

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#47853]
users might have sensitive information within their search or indexing request. When slow logging is enabled this information might leak into logs.
It would be useful to allow configuring which fields from request source are cleared or obfuscated.

**Comment by pgomulka** [comment]
ping @yacine-younes who raised a problem

**Comment by yacine-younes** [comment]
The original use case behind this request is the customer that asking how we can hide the user name or other sensitive information in the slow log. In some situation the team analyzing the queries and having access to the nodes should not be able to see the user name related to the queries in the slowlog.

**Comment by pgomulka** [comment]
we discussed this on core-infra sync meeting on 24th Feb
We concluded that in this situation users should try to configure their own pattern layout with regex converter.
The main problem with this usecase is that the confidential data do exist in the cluster anyway, so just filtering the sensitive data from slow log does not help much.

For this reasons I will close the issue. If you have more details why this should be implemented, please do reopen
