### ISSUE TITLE
How multiple indexes correspond to multiple aliases in a template

### ISSUE THREAD

**Issue by RemeoJenius** [elastic/elasticsearch#47893]
**Describe the feature**:Every 30 seconds, the system status will be stored in the ES. The index name is, for example, i_index-2019-10-10. The aggregation will be done every 5 minutes. The data of this table will be summarized into the 5-minute table. The index name is for example: i_index- 5m-2019-10-10, I want to use a template definition, i_index-20* corresponds to the alias a_index, and i_index-5m-* corresponds to the alias a_index-5m.
How should the template file be written?

**Elasticsearch version** (`bin/elasticsearch --version`):7.3.1

**Plugins installed**: []

**JVM version** (`java -version`):OpenJDK-1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.I tried to write like this, it doesn't work
 ``` json
PUT _template/t_ceshi
{
  "order": 0,
  "index_patterns": ["i_ceshi-*"],
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "0",
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      
    }
  },
  "aliases": {
    "actions" : [
        { "add" : { "index" : "i_ceshi-20*", "alias" : "a_ceshi" } },
        { "add" : { "index" : "i_ceshi-5m-*", "alias" : "a_ceshi-5m" } }
    ]
  }
}

```
2.I also tried to write like this, it doesn’t work either.
```json
PUT _template/t_ceshi
{
  "order": 0,
  "index_patterns": ["i_ceshi-*"],
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "0",
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      
    }
  },
  "aliases": {
    "a_ceshi": {"index":"i_ceshi-20*"},
    "a_ceshi-5m": {"index":"i_ceshi-5m-*"}
  }
}
```
 

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
