### ISSUE TITLE
POST _forcemerge with max_num_segments merge more than necessary

### ISSUE THREAD

**Issue by viewsite** [elastic/elasticsearch#47899]
In https://www.elastic.co/guide/en/elasticsearch/reference/6.7/indices-forcemerge.html, it said, "max_num_segments is the number of segments to merge to". But when I sent a force merge request to v6.8.3, with maxSegmentCount set to not 1, it only created 1 large segment.

I found it is related to Lucene issue https://issues.apache.org/jira/browse/LUCENE-8688 ForcedMerges tried to create the cheapest merges that allow the index to go down to maxSegmentCount segments or less. The problem was fix in newer  v7.7.2.

**Comment by romseygeek** [comment]
Thanks for opening this issue @viewsite , I've created https://github.com/elastic/elasticsearch/pull/47901 to upgrade our 6.8.x branch to lucene 7.7.2.

**Comment by romseygeek** [comment]
Fixed by #47901
