### ISSUE TITLE
SQL: negative numbers surrounded by round brackets are not treated as negative

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#48009]
`SELECT TRUNCATE(-1.5), TRUNCATE(-(1.5)), -(1.5)`

```
TRUNCATE(-1.5) |TRUNCATE(-(1.5))|      1.5      
---------------+----------------+---------------
-1.0           |1.0             |1.5            
```

While the result should be obvious, in case it isn't `-(1.5)` seems to evaluate in the end to 1.5.

**Comment by matriv** [comment]
`master` : 4dee4bf3b34081062ba2e28ab8524a066812a180
`7.x` :  3233bce8cb1680cf090f12b59cc3d16b08d8bd43
`7.4` : e3516784b1576f2b945f47735f9eae113eb3f84f
`6.8` : 74fe2f486f12797c8e9a24af7efe2e50645a813c
