### ISSUE TITLE
Elasticsearch 7.4 recommendation

### ISSUE THREAD

**Issue by John33000** [elastic/elasticsearch#48045]
Hi,

Since my upgrade from Elasticsearch 6.8 to Elasticsearch 7.4 my cpu is used at 122% by, kibana or elasticsearch. 

I have 8 Go RAM and 4 vCPU with 2 core. 
How many vCPU need elasticsearch ? I have a single node.

Best regards,

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
