### ISSUE TITLE
[DOCS] Document restart procedure separately from upgrade procedure

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48051]
Today we document how to upgrade a cluster via a [full-cluster restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html) and a [rolling restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html), but there are other situations where you might want to restart some or all of the nodes in your cluster. For instance, you might want to adjust a node-level static setting. The procedure is basically the same, except that you should skip any parts that talk about upgrading the nodes while they're down.

I think we should have docs specifically for restarts without upgrades, rather than asking users to skip the irrelevant bits of the upgrade docs themselves. This repeats #7169 which was closed ("Done"? perhaps we added this and then lost it later?). I'm asking for help from the docs team since I don't think my Asciidoc-fu is up to the task of re-using the bits of the docs we already have.

**Comment by Leaf-Lin** [comment]
@ppf2 5 years later...

**Comment by debadair** [comment]
[docs issue triage]

**Comment by szabosteve** [comment]
#48583 created the page that contains the procedures for full-cluster restart and rolling restart. I close thee ticket.
