### ISSUE TITLE
[ML] Allow `indices_options` parameter for datafeed configuration

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#48056]
In certain situations it is valuable to allow missing indices (e.g. a well defined datafeed configuration that takes advantage of ECS). Right now, if one of the indices in the supplied index pattern does not exist, we throw an error on `_start`. If we exposed an `indices_options` type of parameter (that serializes to an `IndicesOptions` object), that will allow more advanced users to provide custom expansion options to handle their use case.

**Comment by jasonrhodes** [comment]
Related issue we're having on the logs/ML integration side: https://github.com/elastic/kibana/issues/48219

**Comment by droberts195** [comment]
One particular effect of not being able to configure indices options on the datafeed config is that it's currently impossible to configure a datafeed to search frozen indices because you have to explicitly set the `ignore_throttled=false` option to do this.
