### ISSUE TITLE
[ML] Remove ToXContentParams.INCLUDE_TYPE

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#48057]
Given we now have `INCLUDE_TYPE` and `FOR_INTERNAL_STORAGE` it seems redundant to keep both. `FOR_INTERNAL_STORAGE` can be used in all cases where we are using `INCLUDE_TYPE` plus more. It will simplify things to just keep the one.

**Comment by rsarawgi** [comment]
@dimitris-athanasiou I'm interested in working on this one. Can I pick it up?

**Comment by dimitris-athanasiou** [comment]
@rsarawgi Most certainly!

**Comment by rsarawgi** [comment]
@dimitris-athanasiou Submitted a PR for this -- please take a look when you get a chance.
