### ISSUE TITLE
Allow reusing the same scripts in sorts, aggregations and script queries

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48059]
Scripted queries and aggs provide a lot a flexibility. One downside however is that they require different kinds of scripts. It makes it challenging for Kibana to expose [scripted fields](https://www.elastic.co/guide/en/kibana/master/scripted-fields.html).

Instead of expecting scripts of `script` queries to return a boolean, could we accept arbitrary search scripts and allow users to pass an expected value as well? This way the same scripts could be used in both queries and aggregations.

**Comment by mayya-sharipova** [comment]
> Instead of expecting scripts of script queries to return a boolean, could we accept arbitrary search scripts and allow users to pass an expected value as well? 

@jpountz  This is not very clear to me. For example if we have a script `"source": "doc['num1'].value  * 10`, is the idea that `script` query can run all different types of queries on these field values?

Do you have ideas how a  potential API of this `script` query can look like?

**Comment by jpountz** [comment]
@mayya-sharipova I think there are many options, we'd need to weigh pros and cons, e.g.
 - give existing queries (`term`, `range`, ...) a `script` parameter like we have on most aggregations so that they support scripts too
 - add more options to the existing `script` query to tell how to check whether the produced value matches
 - add ways to define fields as scripts as part of a search request, and allow these one-off scripted fields to be used in any query or aggregation

There might be other options I haven't thought of.

**Comment by mayya-sharipova** [comment]
> add ways to define fields as scripts as part of a search request, and allow these one-off scripted fields to be used in any query or aggregation

I wonder if we can reuse already existing [script_fields](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-request-body.html#request-body-search-script-fields) for queries as well.

```js
{
  "query": {
    "range": {
      "price_in_dollars": {
        "lte": 100
      }
    }
  },
  "script_fields": {
    "price_in_dollars": {
      "script": {
        "source": "doc['price'].value * 1.25"
      }
    }
  }
}
```

**Comment by jpountz** [comment]
I like the idea.

**Comment by javanna** [comment]
We are going to introduce support for runtime fields. The first implementation of them is going to be scripted runtime fields, which will address exactly the limitations mentioned in this issue, hence I am closing this in favour of #59332 .
