### ISSUE TITLE
Keep the query cache enabled when field-level security is on

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48060]
We currently disable query caching when field-level security is enabled. This is required because queries that use disallowed fields might return different results from queries that only used allowed fields. Could we get smarter about it and keep this cache enabled when the query only targets allowed fields?

Could the new visitor API allow us to collect the set of fields that are used by a query?

**Comment by jpountz** [comment]
@romseygeek mentioned that it's something we should be able to do via the visitor API indeed, e.g. by special-casing for a set of leaf queries that we can extract fields from (`term` and `range` would be a good start) or maybe leveraging `acceptField`.

**Comment by javanna** [comment]
Closed by #93390 .
