### ISSUE TITLE
Add 'read ingest pipeline' cluster privilege

### ISSUE THREAD

**Issue by rneil06** [elastic/elasticsearch#48062]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by polyfractal** [comment]
Can you provide some more context for this @rneil06?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @rneil06 if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
