### ISSUE TITLE
Convenience tooling for OS/packaging test development

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#48087]
Our packaging tests were recently refactored by @rjernst in a series of PRs (#45064, #45565, #45761, and others). When I updated `TESTING.asciidoc` to document the new commands (#48023), I found myself deleting a lot of outdated documentation on iterative development of packaging tests. In the old style of test, a developer could:

1. Spin up and provision a VM, but stop short of running the test.
2. Run packaging tests, but leave the VM running afterwards rather than destroying it.
3. Re-run packaging tests on an already-running VM in order to save time.

Now, the most granular command we can run is something like:

```
./gradlew :qa:os:fedora-28:distroTest.default-linux-archive \
  --tests "com.elasticsearch.packaging.test.ArchiveTests"
```

Do we need to add tasks or plugins to Gradle to restore this functionality?

* On the one hand, someone clearly once found it useful to have such features. Starting and stopping VMs can definitely be tedious, and there are times when a test is more-or-less idempotent and doesn't need a fresh VM for every test run.
    * What warnings do we need to have around Gradle tasks that don't clean up after themselves? What design constraints should we accept for this work, if we choose to do it?
* On the other hand, the whole point of these tests is that they're *not* idempotent; they can be destructive, and always destroying and recreating the VM ensures that we always run the tests in the same way that they'll be run by our CI tooling.

Of course, it's possible that we wouldn't mind having such features but also don't see any reason to prioritize adding them over the many other things we have to work on.

**Comment by williamrandolph** [comment]
We discussed this issue in today's core-infra team meeting.

We agreed that the strong default for these tests should be running on a fresh VM, so we don't have much of a need to support spinning up the VM, but not running tests. The one place this might be inconvenient is in working with BATS tests, but we can consider that yet another good reason to convert the BATS-format tests to Java.

We discussed three things we would like to do:

1. Add a flag that lets devs run the tests, but leave the VM running. We should prefer capturing and outputting machine state to shelling into VMs, but sometimes you need to get into the machine to figure out exactly what state to capture. When we add this capability, we should document that using it as a shortcut will bite us when it comes to problems in CI. Finally, an implementation consideration is that the flag needs to be handled in both the Gradle plugin for spinning up VMs and in the Reaper process. It would be easy to forget about the Reaper.
2. We want to be able to attach a debugger to the "in-VM" Java process. This would involve opening a port on the Vagrant VM, and running the "internal"/"destructive" Gradle task with a debugger flag.
3. We can also improve how we capture output from "nested" task in build scans, so that details about failures for the internal task show up in the build scan for the external task. There's some work for this item going on already.

**Comment by mark-vieira** [comment]
We have internal tooling now for easily spinning up build VMs for this purpose.
