### ISSUE TITLE
when ./gradlew assemble How to set build_snapshot to false,and 7.2.0-SNAPSHOT to 7.2.0

### ISSUE THREAD

**Issue by monster0007** [elastic/elasticsearch#48111]
Describe the feature:
1. gradlew assemble elasticsearch7.2.0. when running it catch an exception.
when ./gradlew assemble How to set build_snapshot to false and 7.2.0-SNAPSHOT to 7.2.0

{
  "name" : "node214",
  "cluster_name" : "botudata-test",
  "cluster_uuid" : "4VqNhnliQQ27cKEscPuQ_w",
  "version" : {
    "number" : "7.2.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "Unknown",
    "build_date" : "2019-09-17T02:38:00.887399Z",
    "build_snapshot" : true,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Elasticsearch version 7.2.0 (bin/elasticsearch --version):

Plugins installed: []

**JVM version 12.0.2 (java -version):

**OS version OS Info: Windows 7 6.1 (amd64)
(uname -a if on a Unix-like system):

Description of the problem including expected versus actual behavior:

Steps to reproduce:

Please include a minimal but complete recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc. The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.
1. gradlew assemble elasticsearch7.2.0. when running it catch an exception.
when ./gradlew assemble How to set build_snapshot to false and 7.2.0-SNAPSHOT to 7.2.0

{
  "name" : "node214",
  "cluster_name" : "botudata-test",
  "cluster_uuid" : "4VqNhnliQQ27cKEscPuQ_w",
  "version" : {
    "number" : "7.2.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "Unknown",
    "build_date" : "2019-09-17T02:38:00.887399Z",
    "build_snapshot" : true,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by astefan** [comment]
@monster0007 can you give it another try at explaining the issue? Your post is not clear.

**Comment by astefan** [comment]
@monster0007 I am closing this issue for its lack of completeness. Please, open a thread of discussion on our [forum](https://discuss.elastic.co/) with more details about the problem you are having. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
