### ISSUE TITLE
Elasticsearch rest-api-spec is missing the Voting Config Exclusions API

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch#48131]
Voting Config Exclusions API (https://www.elastic.co/guide/en/elasticsearch/reference/master/voting-config-exclusions.html) was added in 7.0 to support graceful termination of master-eligible nodes.

It seems this API is missing from the REST API spec (https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api), which means it's not part of the official clients (among potentially other things/tests)

**Comment by philkra** [comment]
Pining @elastic/es-clients

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by zacharymorn** [comment]
@DaveCTurner I I just finished working on https://github.com/elastic/elasticsearch/issues/51412 and this seems like a very similar issue, but just for different REST API. From what I understand this issue is to add:
1. REST API spec
2. A few integration tests.

Is this the right understanding?

**Comment by DaveCTurner** [comment]
@zacharymorn I've been holding off on taking action here until the changes you've been working on in https://github.com/elastic/elasticsearch/pull/50836 have been merged. There's no sense in documenting an API that's immediately deprecated.

**Comment by zacharymorn** [comment]
@DaveCTurner Sorry I actually just realized that you were assigned to this task. I was browsing for issues to pick up and thought this one might be a good one, as I just finished off a similar one and have been working on #50836, hence the comment above to check for details.

**Comment by DaveCTurner** [comment]
@zacharymorn now that #50836 is merged would you like to tackle this issue?

**Comment by zacharymorn** [comment]
@DaveCTurner Thanks for checking! Yes I would love to pick this up.

**Comment by zacharymorn** [comment]
@DaveCTurner I've opened a PR for this. Please let me know if it looks good.
