### ISSUE TITLE
2019-10-16 16:17:42 Commons Daemon procrun stdout initialized ERROR: Temporary file directory [C:\temporary file directory does not exist or is not accessible

### ISSUE THREAD

**Issue by 18549** [elastic/elasticsearch#48145]
**Elasticsearch version** (`bin/elasticsearch --version`):
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Could not rename log file 'logs/gc.log' to 'logs/gc.log.21' (Permission denied).
Version: 7.3.0, Build: default/zip/de777fa/2019-07-24T18:30:11.767338Z, JVM: 12.0.1
```
**Plugins installed**: []

**JVM version** (`java -version`):
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
Windows 10 Pro

**Description of the problem including expected versus actual behavior**:

After rebooting ElasticSearch fails to run.

**Steps to reproduce**:

Install ElasticSearch using msi installer from https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html

Run. (It worked fine for ages for me)

Delete any elasticsearch directory from [C:\Users\username\AppData\Local\Temp\elasticsearch]  (Windows will do this automatically from time to time)

Restart the service.

**Provide logs (if relevant)**:
```
2019-10-16 16:17:42 Commons Daemon procrun stdout initialized
ERROR: Temporary file directory [C:\Users\username\AppData\Local\Temp\elasticsearch] does not exist or is not accessible
```

**Comment by rjernst** [comment]
Something is a bit odd here. Are you running as a service, or explicitly starting Elasticsearch? The log message you provided implies you are usinng bin/elasticsearch-service.bat to install and run an ES service, but the msi+elasticsearch.exe has it's own service that it sets up. Also, is `username` your actual user name?

**Comment by 18549** [comment]
I installed using the msi and started the service installed by the msi, I did not run any of the batch files or explicitly install any service. I modified 'username' in the log path to elide my real name.

**Comment by russcam** [comment]
@18549 Would you be able to provide a list of the explicit steps that you performed? For example,

1. Installed Elasticsearch 7.3.0 using the MSI. Ran with the defaults _except_ chose to manually start the Windows Service. (If you have the MSI log file here too, that will be super helpful. As with any MSI installation package, a log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`.).
2. Start Windows Service using the Service Control Manager GUI / PowerShell on command line

etc.

As @rjernst says, the error message is odd here as the elasticsearch.exe installed by the MSI doesn't use Apache Commons Daemon to run. In what file (name and path) was this log line found?

Do you have any other versions of Elasticsearch installed on the machine? If so, were they installed using the MSI or using the zip distribution? Was installation of Elasticsearch 7.3.0 with the MSI a clean installation, or was it an upgrade of a previously installed version?

**Comment by russcam** [comment]
I've run through the following steps:

1. Installed Elasticsearch 7.3.0 using the MSI, with all default settings.
2. Verified Elasticsearch is running
3. Stopped Elasticsearch service using the Services control panel
4. Deleted the `elasticsearch` folder created in `C:\WINDOWS\TEMP`. This is where installation of the Windows service and the default account that it runs under will create this directory. This can be verified using the Nodes API `http://localhost:9200/_nodes?filter_path=nodes.*.jvm.input_arguments`

    which returns the following

    ```
    {
        "nodes": {
            "dx9fhEVGQZySGjs-CWQdyQ": {
                "jvm": {
                    "input_arguments": [
                        "-XX:+UseConcMarkSweepGC",
                        "-XX:CMSInitiatingOccupancyFraction=75",
                        "-XX:+UseCMSInitiatingOccupancyOnly",
                        "-Des.networkaddress.cache.ttl=60",
                        "-Des.networkaddress.cache.negative.ttl=10",
                        "-XX:+AlwaysPreTouch",
                        "-Xss1m",
                        "-Djava.awt.headless=true",
                        "-Dfile.encoding=UTF-8",
                        "-Djna.nosys=true",
                        "-XX:-OmitStackTraceInFastThrow",
                        "-Dio.netty.noUnsafe=true",
                        "-Dio.netty.noKeySetOptimization=true",
                        "-Dio.netty.recycler.maxCapacityPerThread=0",
                        "-Dlog4j.shutdownHookEnabled=false",
                        "-Dlog4j2.disable.jmx=true",
                        "-Djava.io.tmpdir=C:\\WINDOWS\\TEMP\\elasticsearch",
                        "-XX:+HeapDumpOnOutOfMemoryError",
                        "-XX:HeapDumpPath=data",
                        "-XX:ErrorFile=logs/hs_err_pid%p.log",
                        "-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m",
                        "-Djava.locale.providers=COMPAT",
                        "-Xmx2048m",
                        "-Xms2048m",
                        "-Dio.netty.allocator.type=pooled",
                        "-XX:MaxDirectMemorySize=1073741824",
                        "-Delasticsearch",
                        "-Des.path.home=C:\\Program Files\\Elastic\\Elasticsearch\\7.3.0",
                        "-Des.path.conf=C:\\ProgramData\\Elastic\\Elasticsearch\\config"
                    ]
                }
            }
        }
    }
    ```
5. Started Elasticsearch service again using the Services control panel
6. Observed that the service successfully starts, Elasticsearch is running, and `elasticsearch` folder created in `C:\WINDOWS\TEMP`

With these steps, I can't replicate what you're seeing. I tried with Elasticsearch 7.3.0 and latest 7.4.1.

**Comment by 18549** [comment]
I think I might have made a mistake and taken the version information from my development machine which has 7.3 on it that I installed using the bat file, whereas the server has 7.4 installed on it from the elasticsearch-7.4.0.msi Sorry about that.

On the server that experienced the failure the elasticsearch temp folder was initially created in my user directory, but now that directory is being created in c:\windows\temp, I don't know why that's changed but it seems happy enough now and we haven't experienced any subsequent failures.

I can't find any msi logs left over from the original installation so seeing as how it's not reproducable and is working now I'm happy for this to be closed.

**Comment by rjernst** [comment]
Thanks @18549
