### ISSUE TITLE
Separate configuration from implementation for testclusters 

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#48175]
The way testclusters is implemented right now make it difficult to iterate on the DSL to define the clusters. 
We are looking to improve advances use-cases that involve re-configuring the cluster over time in a way that would allow for immutable configuration and runtime and invariant state ( once created it never changes ) including the files and folders for the nodes (excluding anything ES changes itself, e.x. the data directory).

We should have classes that hold the configuration and are used to implement the DSL  and others that make use of this information to implement starting the clusters. 
This is all that is proposed here, additional steps like extending the DSL, making node folder invariant will be tracked separatly.

**Comment by mark-vieira** [comment]
This is the case for the "new" test clusters framework. We won't be improving the old one. We should instead focus on removing usages of it.
