### ISSUE TITLE
Add `full_id` option to `_cat/nodeattrs` and any other APIs returning shortened node ids

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#48178]
**Describe the feature**:
It would be helpful to add the `full_id` option that is available as part of the `_cat/nodes` API to the `_cat/nodeattrs` API. Ideally this would be available in any API that returns the shortened node id.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
