### ISSUE TITLE
[DOCS] Update example from documentation not working

### ISSUE THREAD

**Issue by nicolasSoares** [elastic/elasticsearch#48187]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.3.2, Build: default/zip/1c1faf1/2019-09-06T14:40:30.409026Z, JVM: 12.0.2

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): windows 10

**Description of the problem including expected versus actual behavior**:
I tried an example from https://www.elastic.co/guide/en/elasticsearch/reference/7.3/docs-update.html :

POST test/_update/1
{
    "script" : {
        "source": "ctx._source.test.add(params.tag)",
        "lang": "painless",
        "params" : {
            "tag" : "blue"
        }
    }
}
 and I receive this error

{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[][127.0.0.1:9300][indices:data/write/update[s]]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "failed to execute script",
        "caused_by": {
            "type": "script_exception",
            "reason": "runtime error",
            "script_stack": [
                "ctx._source.test.add(params.tag)",
                "                           ^---- HERE"
            ],
            "script": "ctx._source.test.add(params.tag)",
            "lang": "painless",
            "caused_by": {
                "type": "null_pointer_exception",
                "reason": null
            }
        }
    },
    "status": 400
}

**Comment by jrodewig** [comment]
Hi @nicolasSoares

Thanks for reaching out.

Can you ensure you followed the first example in this section?
https://www.elastic.co/guide/en/elasticsearch/reference/7.3/docs-update.html#update-api-example

```
PUT test/_doc/1
{
    "counter" : 1,
    "tags" : ["red"]
}
```
After that example, you can attempt the following:

```
POST test/_update/1
{
    "script" : {
        "source": "ctx._source.tags.add(params.tag)",
        "lang": "painless",
        "params" : {
            "tag" : "blue"
        }
    }
}
```

Your error indicates the `tags` field doesn't already exist in the document. I'm going to go ahead and close this issue, but please feel free to re-open if more discussion or action is needed.
