### ISSUE TITLE
[CI] Frequent timeouts for XPackRestIT

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#48212]
We have a [decent number of builds failing](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(message,build-id),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:d,query:(language:kuery,query:'class%20:%20"org.elasticsearch.xpack.test.rest.XPackRestIT"%20and%20"timeout"'),sort:!(time,desc))
) due to the `XPackRestIT` suite timing out.

I'm thinking this might just be a case of this suite growing bigger and bigger and simply getting too close to the default suite timeout of 20 minutes. As you can tell from [this build](https://gradle-enterprise.elastic.co/s/wtzckil6qwe2o/tests/byProject?toggled=W1syXSxbMiwwXSxbMiwwLDBdLFsyLDAsMCwwXV0) the suite took over 19m during a successful run. Perhaps it makes sense to bump the suite timeout for this test or break it up, depending on how easy that might be.

**Comment by atorok** [comment]
It would be better to have a lot of tolerance at the suite level and tighter timeouts on the individual methods ? 

This would be solved by #47793 in a better way by making the timeout dependent on the number of individual tests. 

I'we been thinking about splitting these large tests for a while  so I added #48229  to have it in writing.

**Comment by mark-vieira** [comment]
Perhaps we could bump the timeout for now to lesson the pain of these failures until we address to larger scope projects? We're getting about half a dozen of these a day.
