### ISSUE TITLE
ClusterState's toXContent (imperfectly) duplicates logic from other classes' toXContent

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#48218]
`ClusterState.toXContent` method serializes `IndexMetaData` itself, rather than delegating to `IndexMetaData.toXContent`. This has resulted in some additions to `IndexMetaData`, such as `RolloverInfo`, not being included in the serialized cluster state returned by `GET _cluster/state`.  There is also duplicated logic for `MetaData.toXContent` (which *does* call `IndexMetaData.toXContent), although it appears that this might be so that the information can be presented in a different form.

The code in `ClusterState` which serializes `IndexMetaData` objects is found here:
https://github.com/elastic/elasticsearch/blob/6abacd23cbbceed16997410deac68c01442d3e70/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L459-L505

This duplicates, partially, `IndexMetaData`'s `toXContent`:
https://github.com/elastic/elasticsearch/blob/6abacd23cbbceed16997410deac68c01442d3e70/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetaData.java#L1188-L1248

Here's the code in `ClusterState` which serializes part of `MetaData`:
https://github.com/elastic/elasticsearch/blob/6abacd23cbbceed16997410deac68c01442d3e70/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L420-L451

It seems like it would be good to delegate this to the classes' own `toXContent` methods so that we don't duplicate logic and end up with data missing from the `GET _cluster/state` API.

**Comment by zacharymorn** [comment]
Hi  @gwbrown, your description is clear and I can pick up this one. 

I took a look at `ClusterState.toXContent`, and see that the idea of delegation may be applicable to other sections of the code, even the corresponding Class.toXContent is not there yet. For example:

---

https://github.com/elastic/elasticsearch/blob/72e2d16d6f990b500c9d3fa191da357981c14028/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L384-L408

There’s already ClusterBlock.toXContent, shall we also add ClusterBlocks.toXContent?

---
https://github.com/elastic/elasticsearch/blob/72e2d16d6f990b500c9d3fa191da357981c14028/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L411-L417

There’s already DicoveryNode.toXContent, shall we also also DicoveryNodes.toXContent?

---
https://github.com/elastic/elasticsearch/blob/72e2d16d6f990b500c9d3fa191da357981c14028/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L520-L538

There’s already ShardRouting.toXContent, shall we also add RoutingTable.toXContent, IndexRoutingTable.toXContent & IndexShardRoutingTable.toXContent ?

---

https://github.com/elastic/elasticsearch/blob/72e2d16d6f990b500c9d3fa191da357981c14028/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L541-L560

There’s already ShardRouting.toXContent, shall we also add RoutingNodes.toXContent & RoutingNode.toXContent ?

---

Applying the same approach there would make that section of code more consistent, but may increase the effort to a large extent. What do you think ?

**Comment by gwbrown** [comment]
It would be a good idea to switch all of them eventually, at least for the ones that already have their own `toXContent`, unless we find a good reason to do otherwise (omitting sensitive data or something), but we can do one PR for each to split up the work, rather than having to do it all as a single chunk. Thanks for finding the other places where we duplicate this logic!

For the ones that don't already have a `toXContent`, it might be a good idea to add one and use it in ClusterState, just so that each class owns its own serialization logic, but I think that's a lower priority than the ones that have duplicated logic.

**Comment by zacharymorn** [comment]
Ok make sense. I'll raise a PR in a few days.

**Comment by zacharymorn** [comment]
@gwbrown  I opened a PR and took a first stab at delegating logic from `ClusterState.toXContent` to `IndexMetaData.toXContent`. To see what has been changed from both code and serialization, I purposefully separated the commits and the delta can be seen directly here https://github.com/elastic/elasticsearch/pull/48924/commits/4850accccfb0a9d0c8cc810cb6813ec07e1e8e47 . 

Not surprisingly, there are quite some differences.  Is it ok for us to assume that `IndexMetaData.toXContent` logic is what we should go with and disregard that of `ClusterState.toXContent`, or this may break clients depending on the existing serialization logic?

**Comment by zacharymorn** [comment]
I pushed up more commits to show the changes in code & serialization in stages:

- https://github.com/elastic/elasticsearch/pull/48924/commits/bfc1103163f4cb1fb6c49d5a3bff06e50a30eef6 Subtitute relevant logic in ClusterState.toXContent with IndexTemplateMetaData.toXContent
- https://github.com/elastic/elasticsearch/pull/48924/commits/9ce5915d5e7932b435387daacf15d70a84d0db9a Subtitute relevant logic in ClusterState.toXContent with MetaData.toXContent

**Comment by gwbrown** [comment]
Thanks @zacharymorn, I'll take a look at the PR soon.

**Comment by williamrandolph** [comment]
This was fixed by https://github.com/elastic/elasticsearch/pull/52743.
