### ISSUE TITLE
Run rest tests against multiple clusters

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#48229]
We have rest tests that grow fairly large see #48212 , docs tests etc. 

It would make sense to be able to split these and run them against different clusters to make their run faster. This is especially important in smaller runs.

The improvements in #47793  would likely help, as we could maybe generate one class per file , and then run with a fixed number of forks to which testclusters would be sensitive to to start multiple clones of the cluster, then based on the worker ID the test would route to a specific clone.

**Comment by mark-vieira** [comment]
We are slowly moving towards splitting these up, specifically the `XPackRestIT` by moving some of those tests in the corresponding subprojects. I think we want to do more of that kind of modular refactoring work rather than bake logic into the build to do this splitting for us.
