### ISSUE TITLE
[CI] mixed_cluster/80_data_frame_jobs_crud failure

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48236]
https://github.com/elastic/elasticsearch/issues/48019 changed transforms to return an error if they are run in a mixed cluster with a node of version less than 7.4.0.  However, `UpgradeClusterClientYamlTestSuiteIT` can occasionally pick versions older than this to run rolling upgrade tests, in which case `mixed_cluster/80_data_frame_jobs_crud/Test put batch data frame transforms on mixed cluster` will fail.

**Comment by hendrikmuhs** [comment]
This is a regression of #48116. The tests are currently disabled for `7.x` as well as `7.5`, that's why the problem only happens in the `7.4` branch.

**Comment by hendrikmuhs** [comment]
fixed with #48239
