### ISSUE TITLE
[CI] JdbcResultSetIT.testGettingInvalidShort() fails

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48234]
A previous issue uncovered some errors in the JDK timezone database, which were fixed by upgrading the version of Java 11 that we use in CI: https://github.com/elastic/infra/issues/14773

However, there have been three failures in CI since that issue was closed out, all with different JDK runtimes and different timezones, so it looks as though there are some further issues to investigate.  All failures were on the 6.8 branch.

https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-*/t?id=20191003115034-AB8D76F1&_g=()
```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' -Dtests.seed=1130571AB9E10E0A -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingInvalidShort" -Dtests.security.manager=true -Dtests.locale=dyo-SN -Dtests.timezone=America/Belem -Dcompiler.java=12 -Druntime.java=13
```

https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-*/t?id=20191004235915-09D58264&_g=()
```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' -Dtests.seed=A080022C8A1289 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingInvalidShort" -Dtests.security.manager=true -Dtests.locale=ccp-IN -Dtests.timezone=Europe/Simferopol -Dcompiler.java=12 -Druntime.java=11
```

https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-*/t?id=20191017234915-A98515DC&_g=()
```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' -Dtests.seed=CFDC382017C0E2BA -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingInvalidShort" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=SystemV/EST5EDT -Dcompiler.java=12 -Druntime.java=8
```

**Comment by astefan** [comment]
Same as https://github.com/elastic/elasticsearch/issues/45035

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/51592.
