### ISSUE TITLE
Implement a unique way to mute tests

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#48245]
We currently have many ways to mute a test: the `@Awaitsfix` annotation, `assume*` methods to conditionally mute, `skip` in yml tests, and corner  cases keep showing up. 

It would be nice to have a framework to do this in Gradle at the Junit level ( since we do use that as a runner across the board ).

The way it would work is that we would have one file checked in that Gradle would read to know what tests need to be excluded for which tasks. 
We could also add additional capabilities like having tests that are ran, but if they fail, that would not contribute to the overall build, which would succeed. 
This would allow us to run flaky tests where we need additional logs without leading to failures in CI. 

It would be ideal to have a check in `precommit` to identify non existing tests in the list to protect against typos, and the issue Id would also be mandatory.

@mark-vieira  I know we talked about this before and you had some pointers, including ideas on how this could be implemented with Gradle, but I could not find that discussion. 

Having this structured in this way would allow interesting use-cases, like automating test muting, or generating the tests to mute based on some pattern in Github issues.
I'm not arguing we should go there, I think this change has value in it's own.

**Comment by mark-vieira** [comment]
Yeah, there are a few ways we could do this I think. One option is via a `TestFilter` that reads from this file you mention. Conditionally reporting failures is more awkward I think. That would probably have to be implemented in our test framework itself.

**Comment by mark-vieira** [comment]
This has been implemented by #106784
