### ISSUE TITLE
Limit test failure console output from 6.8 builds

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#48257]
The work we did for refactoring our build to use the Gradle test runner, as well as improved logging output on failures was never backported to 6.8. This was intentional, as most work is being done in later branches. However, we still run 6.8 builds, and will do so for some time until we release 8.0. One consequence of the current situation is that test failures in that branch create an [obscene amount of console output](https://gradle-enterprise.elastic.co/s/ja6liebjqnhc6/console-log/raw). In many cases this is 100s of MB of logs for a single build. In the case of Jenkins, we having to ship this data back to the master, which already has one foot in the grave, and now we also send this data to Gradle Enterprise, which stores this indefinitely.

In later branches [we have some logic](https://github.com/elastic/elasticsearch/blob/0cb8cc7eb2233dfe113ae1e4a7789b909c98a540/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L843-L901) to filter the node log contents that get reported. I suggest we backport this small bit of logic back to 6.8 to help lesson the load on our infrastructure.

**Comment by atorok** [comment]
Note that most of the `6.8` branch is running on the old `ClusterFormationTasks` so the logic would need to be re-implemented there, it's not a straight forward back-port.

**Comment by mark-vieira** [comment]
That is correct. But we otherwise don't need to pull in any other test clusters stuff, just the node log filtering bit.

**Comment by atorok** [comment]
Pulling in the node filtering bit for test-clusters wouldn't be too difficult, but I don't think it would help much because only a few projects use testclusters in `6.8`

**Comment by mark-vieira** [comment]
Right, that would not be my intention. I would instead suggest we modify the log printing logic in `ClusterFormationTasks` and replace with what we use for test clusters. It's essentially one method, with no real other dependencies, so I don't think it'd be particularly difficult. In any case, I'll keep an eye on these builds and see if we continue to see this issue. It's pretty infrequent given how little activity is in 6.8 but when we do see failures it results in a huge spike in Gradle Enterprise disk usage.

**Comment by mark-vieira** [comment]
Realistically, we aren't going to bother with this. Closing this issue.
