### ISSUE TITLE
[CI] Failed builds due to insufficient disk space while bundling build logs

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#48264]
This looks to be some fallout from #47642. We have a number of builds that have failed with insufficient disk space while packing up build logs for upload to GCP.

https://gradle-enterprise.elastic.co/s/arus5kdqotuok
https://gradle-enterprise.elastic.co/s/juw6pxer7wjac
https://gradle-enterprise.elastic.co/s/sp7lbqweey2ek

Sounds like it's possible we might be including too much stuff in this archive if we are suddenly eating up the disk? Perhaps we should create this tar outside of the ramdisk? At the very least we should wrap this `buildFinished` hook in an exception handler such that we don't actually fail the build if this barfs for some reason.

**Comment by mohdhanafingah777** [comment]
Good

**Comment by atorok** [comment]
Looking at the partial archive generated, it is 20GB ... 

I considered wrapping everything in a try catch, but that would make ti very easy for problems to go unnoticed for too long. 
We don't want to find out that logs are missing when we run into issues. 
In this case we would happily continue on creating 20GB partial archives.

**Comment by atorok** [comment]
`7.4` doesn't have the change that put distributions in their own folder, so on this branch the logs include a copy of each distro ever used, including the JDKs. 
The  partial archive confirms this.

**Comment by atorok** [comment]
I pushed 1ee31e5047c directly to address this. Specifically only collect the logs on this branch
