### ISSUE TITLE
Geo-aggregation failure

### ISSUE THREAD

**Issue by boba-bugs** [elastic/elasticsearch#48262]
**Elasticsearch version** (`bin/elasticsearch --version`):
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 7.4.0, Build: default/tar/22e1767283e61a198cb4db791ea66e3f11ab9910/2019-09-27T08:36:48.569419Z, JVM: 13
**Plugins installed**: [None]

**JVM version** (`java -version`):
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
**OS version** (`uname -a` if on a Unix-like system):
Linux VA-1207 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:
From Section 4.1.11 of the Elasticsearch Engineer 1 course
Validate that the coordinates field is mapped correctly.

Geo-Aggregations are not working with Geoip  location fields and require a re-index using Geo_point fields in order for aggregations to become operational.  This is a potential hazard for us in the MSSP world if we have content that hinges on the success of these aggregations.  Additionally, as in the example, some Geo aggregations are failing silently with no indication that they misfired.   I have updated the example from the lab guide as below to produce a result:

**Steps to reproduce**:
```python
from elasticsearch import Elasticsearch
import json

es = Elasticsearch(hosts=["127.0.0.1:9200"], http_compress=True)
idxs = es.indices
idxs.create('my_logs')

mapping = {
  "properties": {
    "coordinates": {
          "type": "geo_point"
        },
    "ip": {"type":"ip"}  
      }
    }
idxs.put_mapping(index="my_logs", body=mapping)

document = {
    "properties":{
        "@timestamp": "2019-07-08T03:00:00.000Z",
        "ip" : "105.32.126.44",
        "bytes" : 8261,
        "coordinates" : {
            "lat" : 30.42769722,
            "lon" : -87.70082}
    }
}
es.create(index="my_logs", id=1, body=document)

body ={
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "geo_distance" : {
                    "distance": "12756km",
                    "coordinates" : {
                        "lat" : 30,
                        "lon" : -87
                    }
                }
            }
        }
    }
}
es.search(index="my_logs", body=body)
```
This should aggregate.

Additionally it would be nice if the location field in the geoip object was a possible source in aggregations.  

**Provide logs (if relevant)**:

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
