### ISSUE TITLE
CI jobs in 7.4 fails with `Problem creating TAR: No space left on device`

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#48287]
Starting on Oct 19th, there seems to be quite a lot of 7.4 jobs failing with the message:

```
Problem creating TAR: No space left on device
```

For example:

https://gradle-enterprise.elastic.co/s/dku7gjzm7hq5y
https://gradle-enterprise.elastic.co/s/mhldzndouknnk
https://gradle-enterprise.elastic.co/s/mhrct4y2pmd2q

**Comment by atorok** [comment]
duplicate of #48264

**Comment by iverase** [comment]
I close it in favour of the other issue.
