### ISSUE TITLE
SQL Translate API returns from,to,include_lower,include_upper for range query

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#48327]
Relates: https://github.com/elastic/elasticsearch-net/issues/4110

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.2, but suspect all versions that include SQL translate API are affected.

**Description of the problem including expected versus actual behavior**:

The SQL Translate API returns `"from"`, `"to"`, `"include_lower"`, `"include_upper"` as properties of a range query, when translating a where clause with a binary comparison. This is opposed to returning `"gt"`, `"lt"`, `"gte"`, `"lte"`, respectively.

Elasticsearch will accept a range query using `"from"` et. al, however, [these properties are not documented for range queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#range-query-field-params).

**Steps to reproduce**:

 1. Insert the following documents into an index

    ```
    PUT userindicators/_doc/1
    {
      "LoginDays":10
    }

    PUT userindicators/_doc/2
    {
      "LoginDays":11
    }
    ```

 2. Call the SQL Translate API

    ```
    POST _sql/translate?format=txt
    {
      "query":"select * from userindicators where LoginDays>10"
    }
    ```

 3. Observe a result of the following for the query part

```
  "query" : {
    "range" : {
      "LoginDays" : {
        "from" : 10,
        "to" : null,
        "include_lower" : false,
        "include_upper" : false,
        "boost" : 1.0
      }
    }
  },
```

The expectation is that this would be

```
  "query" : {
    "range" : {
      "LoginDays" : {
        "gt" : 10,
        "boost" : 1.0
      }
    }
  },
```

**Comment by wchaparro** [comment]
Superceded by ES|QL
