### ISSUE TITLE
Elastic Search Basic Authentication

### ISSUE THREAD

**Issue by bhartishradha** [elastic/elasticsearch#48328]
Hi,
I am very new to ELK, and recently we got a requirement that we need to upgrade our elk stack to 7.X while previously it was using ELK2.X
now as part of this, we need to implement basic authentication but when I was going through the video, I noticed that there they are using two nodes of elastic search while we are using only one ...there is nothing like master and node in my existing application 
so could you help me with this that is it possible to put authentication using one node?

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
