### ISSUE TITLE
how reload config file when change the config file？

### ISSUE THREAD

**Issue by kevinsingapore** [elastic/elasticsearch#48326]
how to reload the config file but not restart the service when change the config file?
eg：jvm values，elasticsearch.yml；

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
