### ISSUE TITLE
Failure of :modules:transport-netty4:test on master

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#48330]
Build | 20191022054831-A81DC5D0
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2/215/console
Build Scans | https://gradle-enterprise.elastic.co/s/hpnzc7hnzftce

Reproduce line:
```
REPRODUCE WITH: gradlew ':modules:transport-netty4:test' --tests "org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.testLocalNodeConnection" \
  -Dtests.seed=175DFFF16E9928FC \
  -Dtests.security.manager=true \
  -Dtests.locale=lg-UG \
  -Dtests.timezone=Africa/Juba \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Does *not* reproduce locally.

Excerpt from logs:
```
06:39:55   2> java.lang.AssertionError: expected:<0> but was:<16777216>
06:39:55         at __randomizedtesting.SeedInfo.seed([175DFFF16E9928FC:6655EB5329A51DB6]:0)
06:39:55         at org.junit.Assert.fail(Assert.java:88)
06:39:55         at org.junit.Assert.failNotEquals(Assert.java:834)
06:39:55         at org.junit.Assert.assertEquals(Assert.java:645)
06:39:55         at org.junit.Assert.assertEquals(Assert.java:631)
06:39:55         at org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.tearDown(SimpleNetty4TransportTests.java:53)

```

**Comment by atorok** [comment]
@przemekwitek I think we should mute the test on windows with something like `assumeFalse(Constants.WIDOWS)`

**Comment by przemekwitek** [comment]
Ok, I'll prepare a fix shortly.

**Comment by przemekwitek** [comment]
Another failure on 7.x:


Build | 20191022105837-FAD56C29
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2019/207/console
Build Scans | https://gradle-enterprise.elastic.co/s/h56kplfufmnfy

**Comment by przemekwitek** [comment]
Another instance:


Build | 20191022105802-5CDA2F31
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2016/207/console
Build Scans | https://gradle-enterprise.elastic.co/s/vh6r5tbo7yyhq

**Comment by przemekwitek** [comment]
Another instance:


Build | 20191022105811-393EEB9F
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2012-r2/207/console
Build Scans | https://gradle-enterprise.elastic.co/s/e7xuhufkojecc

**Comment by tbrooks8** [comment]
I think this has to do with dirty state from a prior test. Netty holds a static allocator which if touched will allocate memory. In this test we are asserting the allocator is empty. This assertion was mainly a sanity check and I think was not well thought out on my part (requires all related test to cooperate). 

I opened #48356 to remove this assertion.
