### ISSUE TITLE
Execution failed for task ':docs:integTestRunner'.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#48343]
Does not reproduce locally.

Build | 20191022095030-49D314C2
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/1907/console
Build Scans | https://gradle-enterprise.elastic.co/s/zywvqlrhmdehu

Reproduce lines:
```
REPRODUCE WITH: ./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ccr/apis/get-ccr-stats/line_94}" \
  -Dtests.seed=1F9974FEF2061B2D \
  -Dtests.security.manager=true \
  -Dtests.locale=wae \
  -Dtests.timezone=AET \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ccr/apis/get-ccr-stats/line_94}" \
  -Dtests.seed=1F9974FEF2061B2D \
  -Dtests.security.manager=true \
  -Dtests.locale=wae \
  -Dtests.timezone=AET \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by przemekwitek** [comment]
Another instance:


Build | 20191022094102-D7AC6490
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/421/console
Build Scans | https://gradle-enterprise.elastic.co/s/qa3rnqd5olrhm

**Comment by przemekwitek** [comment]
Another instance:


Build | 20191022095656-49C1538A
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/1767/console
Build Scans | https://gradle-enterprise.elastic.co/s/iekdf3kfjok5w

**Comment by przemekwitek** [comment]
Another issue:


Build | 20191022090850-28A85C9A
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+EAR/12/console
Build Scans | https://gradle-enterprise.elastic.co/s/fqcjc53dk5lcq

**Comment by przemekwitek** [comment]
Another instance:


Build | 20191022083747-C57C99D0
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/12/console
Build Scans | https://gradle-enterprise.elastic.co/s/q3ab5hfdzr3sm

**Comment by tlrx** [comment]
These tests failures seem to be instances of #47718. Yannick provided a [detailed explanation](https://github.com/elastic/elasticsearch/issues/47718#issuecomment-540965152) of the issue but the fix is not that simple.

@przemekwitek If the docs keep failing we should mute these docs tests

**Comment by ywelsch** [comment]
There's already an open issue for this: #47718
