### ISSUE TITLE
mapper_parsing_exception when indexing null \u0000 character into completion type field

### ISSUE THREAD

**Issue by rotzbouw** [elastic/elasticsearch#48341]
**Describe the feature**:
mapper_parsing_exception caused by illegal_argument_exception when indexing null character (utf-16 \u0000)

**Elasticsearch version** (`bin/elasticsearch --version`): Docker container with ES 7.4.0

**Plugins installed**: []

**JVM version** (`java -version`): 12

**OS version** (`uname -a` if on a Unix-like system): Debian

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

```
curl -X PUT "localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "properties" : {
            "suggestions" : { "type" : "completion" }
        }
    }
}
'

curl -X POST "localhost:9200/test/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
    "suggestions" : ["Gu \u0000"]
}
'
```

**Provide logs (if relevant)**:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Illegal input [Gu \u0000] UTF-16 codepoint [0x0] at position 3 is a reserved character"
    }
  },
  "status" : 400
}
```

**Comment by cbuescher** [comment]
Hi @rotzbouw, you hit one of the three reseverd characters of the [SuggestField](https://github.com/apache/lucene-solr/blob/master/lucene/suggest/src/java/org/apache/lucene/search/suggest/document/SuggestField.java#L142) in Lucene. This is the END_BYTE character that is used by the in-memory datastructure for the completion suggester. The other two are control characters \u001e  and \u001f which serve as internal separation characters in the suggester automaton. 

I assume this case came up during testing? I suggest we document this somewhere with the field type, would that be sufficient?

**Comment by rotzbouw** [comment]
Thanks for pointing out the exact line containing the references to the reserved characters. Documentation would be of help to others, yes, thanks!

**Comment by TusharMehtani** [comment]
@cbuescher - Did something change in the newer versions (I am using elasticsearch 7.5.2)? I am getting a similar error with another reserved character (which is not among the 3 you have mentioned above).
```
{
    "error": {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Illegal input [大功牛排 大沙朗牛排oz\x1f 獨家菜單] UTF-16 codepoint [0x1f] at position 12 is a reserved character"
        }
    }
}
```
