### ISSUE TITLE
Documentation search putting java and groovy APIs over json APIs

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#4836]
I normally receive these kinds of bug reports so it is fun filing one.  I think it is important that the documentation present the json api first because it is more generally useful then the language specific api.

So if you:
1.  Go to the documentation, say http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search.html
2.  Type "search api" into the search box.

The first result is for the java api and second is for the groovy api.  The json api is ninth.  It really ought to be first.

I'm not sure if the right solution is to name the json search api page "search api" instead of "search apis" or if it'd be better to lower the score of the non-json apis with a document boost or something and expect people to type "search api java" if they want the java api which should bring it back to the top.

**Comment by javanna** [comment]
This seems to be solved with the new website... unless I am missing something :)

Thoughts @clintongormley ?

**Comment by clintongormley** [comment]
This is definitely better on the new site, and more improvements will follow.
