### ISSUE TITLE
[CI] TokenAuthIntegTests failed with OutOfMemoryError Direct buffer memory

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48384]
Gradle build scan is here: https://gradle-enterprise.elastic.co/s/5wugulq6yrnv6

This looks like the same issue as #46803 and so presumably needs the same fix to be applied to this test.

**Comment by original-brownbear** [comment]
RIght this was the same as #46803 which is fixed now -> closing here :)
