### ISSUE TITLE
[CI] Rolling upgrade test failure - failed to obtain in-memory shard lock

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48395]
All tests in TokenBackwardsCompatibilityIT failed when upgrading from 7.4.1 to 7.x latest with 'there are still tasks running' failures at cleanup time.  Digging into the logs, it seems that the root of the failure is one of the upgraded master nodes failed to start due to a 'failed to obtain in-memory shard lock' error.

Build scan is here: https://gradle-enterprise.elastic.co/s/qycq6tmil2t3w/console-log?task=:x-pack:qa:rolling-upgrade:v7.4.1%23upgradedClusterTest#L2698

This has happened before, a few days ago, also in TokenBackwardsCompatibilityIT, upgrading from 6.8.4: https://gradle-enterprise.elastic.co/s/46trrv4mlxcle

**Comment by jtibshirani** [comment]
I just observed a failed intake build with similar symptoms (a 'failed to obtain in-memory shard lock' error, along with a build-up of cluster state tasks). Build scan: https://gradle-enterprise.elastic.co/s/f4vu4xgxiwkcs/.

**Comment by ywelsch** [comment]
It looks like something is DDoSing the master with persistent task updates.

**Comment by ywelsch** [comment]
I've opened #48483 to get more details on the tasks that are hanging.

**Comment by ywelsch** [comment]
Looking closer at this, it seems as if this is a reoccurrence of #39982
