### ISSUE TITLE
Support `end_session_endpoint` URLs with parameters

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#48409]
Typically `end_session_endpoint` doesn't have a query part, but this is actually not disallowed in the Specification. `oath2-oidc-sdk` doesn't handle this when building the URL to the `end_session_endpont` and simply appends `id_token_hint` and `state` as query parameters starting with an `?`.

This is problematic in case the `end_session_endpoint` already has a query part as the URL that we will redirect the user after logout would be similar to 

```
https://endpoint_url:port?param1=valu1&param2=value2?id_token_hint=X&state=Y
```

**Comment by jputman08** [comment]
@jkakavas We have a customer who has asked me to look into this specific issue. I'm not sure about the level of effort but wanted to ping the team on any update to this issue. Thanks! cc: @mbarretta

**Comment by jkakavas** [comment]
Hi @jputman08, this is something we want to work on at some point but is not currently under implementation, nor it is in the near term plans of any of us to pick up AFAIK. Once someone picks this up to work on it, it will be assigned and the process will be reflected here.

**Comment by mbarretta** [comment]
I filed a (poorly formatted) bug request against `oauth2-oidc-sdk` ...maybe they'll fix it and we'd just need to up our supported version.

https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/285/logoutrequest-creates-invalid-uris-when
