### ISSUE TITLE
Shortcut setting to configure dedicated node types

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#48407]
**Describe the feature**:

Elasticsearch now has several node types:

* Master
* Voting-only (master-eligible nodes that can never be elected as a master node)
* Data
* Ingest
* Coordinating (formerly known as client)
* Machine learning

There is a lengthy and very detailed [document](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/modules-node.html) describing how to configure elasticsearch.yml for dedicated node types:

## Dedicated Master

```
node.master: true 
node.voting_only: false 
node.data: false 
node.ingest: false 
node.ml: false 
xpack.ml.enabled: true 
cluster.remote.connect: false
```

## Dedicated Voting-only (non-OSS distribution only)

```
node.master: true 
node.voting_only: true 
node.data: false 
node.ingest: false 
node.ml: false 
xpack.ml.enabled: true 
cluster.remote.connect: false
```

### default distribution

```
node.master: false 
node.voting_only: false 
node.data: true 
node.ingest: false 
node.ml: false 
cluster.remote.connect: false
```

### OSS-only distribution

```
node.master: false 
node.data: true 
node.ingest: false 
cluster.remote.connect: false
```

## Dedicated Ingest

```
node.master: false 
node.voting_only: false 
node.data: false 
node.ingest: true 
node.ml: false 
cluster.remote.connect: false
```

## Dedicated Coordinating

```
node.master: false 
node.voting_only: false 
node.data: false 
node.ingest: false 
node.ml: false 
cluster.remote.connect: false
```

## Dedicated Machine Learning

```
node.master: false 
node.voting_only: false 
node.data: false 
node.ingest: false 
node.ml: true 
xpack.ml.enabled: true 
cluster.remote.connect: false
```

The number of settings to disable when configuring dedicated node types feels high. I would like to suggest designating a single boolean setting for each node type that dedicates the node to that type. The setting could be `.dedicated` or similar. I would have suggested `.only` but the wording seems redundant with `node.voting_only`. 

An additional aspect of this is the promotion of using dedicated node types. There is one docs [request](https://github.com/elastic/elasticsearch/issues/42422) to better document and motivate the use of dedicated master nodes. Having a `dedicated` setting would really help to streamline documentation and boost ease of use. It would also eliminate the need to consider OSS-only vs. default distributions when configuring dedicated data nodes.

**Comment by jaymode** [comment]
The Core/Infra team discussed this and agree that setting the dedicated role or roles for a node is more complicated than it needs to be. The suggestion that came out of the discussion is to add a new setting `node.roles` that will replace the existing settings, which will be deprecated upon adding the new setting.

| Existing Setting  | Role |
| ---------------- | ----- |
| node.master  | MASTER  |
| node.data  | DATA  |
| node.ingest  | INGEST  |
| node.ml  | ML  |
| node.voting_only  | VOTING_ONLY  |
| cluster.remote.connect | REMOTE_CLUSTER_CLIENT |
| | COORDINATING_ONLY |

There was some discussion regarding the naming of the roles, but we deferred making decisions upon these to avoid derailing the conversation into a naming debate. These items were:

* Rename `MASTER` to `MASTER_ELIGIBLE` to more accurately describe the role
* `ONLY` in `VOTING_ONLY` and `COORDINATING_ONLY` have different meanings. A node could have more roles that `VOTING_ONLY` but may not have more roles than `COORDINATING_ONLY`. Some suggestions were `NON_MASTER_VOTER` or just `VOTING`

The default for the setting should be the default value of starting a node, which is `MASTER`, `DATA`, `INGEST`, `ML`, `REMOTE_CLUSTER_CLIENT`.

**Comment by williamrandolph** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/54998
