### ISSUE TITLE
Produce Docker images for RedHat Universal Base Image

### ISSUE THREAD

**Issue by rwaight** [elastic/elasticsearch#48429]
**Describe the feature**:  
This feature request is a request to produce Elasticsearch images based on the [RedHat Universal Base Image (UBI)](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image).

Producing Elasticsearch images based on the official RHEL UBI would be beneficial for anyone using the official RHEL UBI for the base image of their docker containers.

**Comment by atorok** [comment]
I wonder if it's worth keeping both rhel ubi and centos base images ?
Constantly building and testing these images in the development process, as well as maintaining the changes in two set of images carries a maintenance cost that we would be better off avoiding.

**Comment by jethr0null** [comment]
@atorok I had a similar line of thought earlier this year but discovered that there are some blockers to standardizing on only UBI. The CentOS images are needed for us to continue publishing to Docker Hub (at least for the official images in /library). There is a [requirement](https://github.com/docker-library/official-images#repeatability) (from Docker) that any official images are built on top of a Docker official base image. There isn't an official UBI image and neither Red Hat nor Docker intends to produce one at this time. Hope this helps.

**Comment by atorok** [comment]
That doesn't give us much choice then. We could have a supported, scripted way to generate it, but we'll have to do that as part of the build anyhow to run the tests so we might as well ship an additional set of docker images.
