### ISSUE TITLE
Refactor and DRY up Kahan Sum algorithm

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#48469]
We use the Kahan summation algorithm in several places in aggregations, and while it's not that complicated of an algorithm, each repetition is still a chance to make a subtle error.  Most, if not all, of our usages could just call a common function (`GeoCentroidAggregator` might be the exception, since it runs a latitude and a longitude sum in parallel).  We should refactor the common case into one place and just call it as needed.

**Comment by Lareth51** [comment]
Hello, it would be my first contribution to elasticsearch. Can I work on this?

**Comment by not-napoleon** [comment]
@Lareth51 Sure, if you'd like.  I grepped this list of places we're using Kahan sums, but as I said, some of them may not be suitable for DRYing up.

server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalSum.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/WeightedAvgAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/AvgAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalAvg.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalWeightedAvg.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/StatsAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/SumAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/GeoCentroidAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/ExtendedStatsAggregator.java
server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalStats.java

I haven't given much thought to the best place to put the refactored function, so feel free to take a look around and see what looks good to you.  And please let me know if you have questions or hit any snags.  Thanks!

**Comment by zaina1986** [comment]
Hello, is this issue still available to contribute to?
I am interested in this issue

**Comment by not-napoleon** [comment]
Hi @zaina1986, another contributor has already opened a PR against this issue.  If you want to find a different issue to work on, don't feel like you have to pick only from the `good first issue` list, if something else catches your eye.
