### ISSUE TITLE
Histogram aggregations: support decimal intervals

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#4847]
Fork of #3810 and #3799. Decimal intervals would be useful for certain data types such as currencies, temperatures, lengths ...

**Comment by jakegibson** [comment]
+1

**Comment by marcosg3** [comment]
+1
We came across this limitation on one of our projects, has there been any traction on this one?

**Comment by ignaciovazquez** [comment]
+1

**Comment by roblovelock** [comment]
+1
I am currently working arround this issue by running a script (probably not the most efficient)

"aggs" : {
                            "decimalValueHistogram" : { 
                                "terms": {
                                    "field": "value",
                                    "script" : "_value % interval < 0 ? _value -((_value % interval) + interval) : (_value -  (_value % interval))",
                                    "lang" : "expression" ,
                                    "params": {
                                        "interval" : 0.05
                                    }
                                }
                            }                                           
                        }

**Comment by ESamir** [comment]
+1

**Comment by sylvinus** [comment]
+1. Would be incredibly useful and avoid storing lots of duplicate columns, which is our only workaround for now :/

**Comment by pjcardy** [comment]
If you're not going to do this, please at least put a massive warning in the documentation! It's not mentioned at all, and I think most people's assumption would be that discrete values are supported, not just integers!

As it stands, I've spent time and money gathering data I now can't use.

+1

**Comment by clintongormley** [comment]
@pjcardy want to send a pull request?

**Comment by ejain** [comment]
For a facet that supports decimal intervals (and offsets), see https://github.com/zenobase/decimal-histogram-facet. I'd be happy to update it to use aggregations and contribute it to elasticsearch.

**Comment by clintongormley** [comment]
@ejain thanks for the offer. I don't know whether or not there is some missing infrastructure that would prevent this happening.  @jpountz what do you think?

**Comment by pjcardy** [comment]
@clintongormley That's a good point, sorry I should have done that in the first place. Please see above.

**Comment by jpountz** [comment]
@clintongormley I don't think there's anything missing. I think the two main challenges will be to make sure it works fine with pipeline aggregations and that empty bucket generation (`min_doc_count:0`) also works fine if there are floating-point rounding errors.

**Comment by clintongormley** [comment]
@ejain you've heard [the man](https://github.com/elastic/elasticsearch/issues/4847#issuecomment-111970019) :)  A PR for decimal support in aggs wouldl be greatly appreciated

**Comment by sbyim** [comment]
+1

**Comment by alecklandgraf** [comment]
+1

**Comment by jeffsteinmetz** [comment]
There is actually a typo in that last merge btw `themsevles`

**Comment by nicktgr15** [comment]
+1

**Comment by troglotit** [comment]
+1

**Comment by GregHubs** [comment]
+1

**Comment by tom-christie** [comment]
+1

**Comment by DimitryDushkin** [comment]
+1

**Comment by yossicahen** [comment]
+1

**Comment by Hossrod** [comment]
+1

https://discuss.elastic.co/t/less-than-1-interval-values/55201

**Comment by StianOvrevage** [comment]
+1!

**Comment by slava-vishnyakov** [comment]
So, is this available only in `v5.0.0-alpha5` ? No backport?

**Comment by jpountz** [comment]
This required a very large refactoring (see diif stats on the PR) so I am leaning towards not backporting in order to not destabilize the 2.x series so close to the release of 5.0.

**Comment by slava-vishnyakov** [comment]
@jpountz, got it, thanks! Very useful feature indeed!

**Comment by Hossrod** [comment]
Woot, thanks!!

**Comment by mrvincenzo** [comment]
@jpountz, is it in the 5 GA versions? 5.1.1 specifically?
