### ISSUE TITLE
TermQueryBuilder and WildcardQueryBuilder should rewrite queries on `_index` so that shards get skipped

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48473]
`term` and `wildcard` queries already create either a `MatchAllDocsQuery` or a `MatchNoDocsQuery` at the shard level depending on the index name and its aliases. See `IndexFieldType#termQuery` and `IndexFieldType#wildcardQuery` for details.

It would be nice to go further and handle these in `TermQueryBuilder#rewrite` and `WildcardQueryBuilder#rewrite`. The benefit is that if someone queries index `foo` with a filter on `{ "term": { "_index": "bar" } }`, then the top-level query will rewrite to a `MatchNoDocsQuery`, which is exactly the information that the `can_match` phase leverages in order to skip shards.

It would be a convenient and efficient way for Kibana to filter on a subset of data streams that are configured in the index patterns.

**Comment by jpountz** [comment]
Handling `TermsQueryBuilder` (note the `s`) would be helpful too.

**Comment by markharwood** [comment]
I expect the required rewrite logic would be something like this:

        if (fieldName.equals("_index") && context.indexMatches(value.toString()) == false) {
            return Queries.newMatchNoDocsQuery(
                    "The index [" + context.getFullyQualifiedIndex().getName() + "] doesn't match the provided value [" + value + "].");
        }

But I added this example is in the `AbstractQueryBuilder.doToQuery` method override where "context" arg is a `QueryShardContext` with that helpful index-name matching method. 

In your suggested placement of `AbstractQueryBuilder.doRewrite` the `context` arg passed is a less useful class - `QueryRewriteContext` without the index-name checking logic.

Would it matter if the MatchNoDocs rewrite happens in the `doToQuery` method?

**Comment by jpountz** [comment]
Indeed it would probably look something like that. You can call `queryRewriteContext.convertToShardContext();` to get a shard context - with some cavehats. See for instance how `RangeQueryBuilder#doToRewrite` works.

> Would it matter if the MatchNoDocs rewrite happens in the doToQuery method?

Unfortunately yes. We already do this in doToQuery today actually via `IndexFieldType#termQuery`. However the heuristic that the `can_match` phase uses to know whether a shard might have any documents is by looking at whether the query rewrites to a MatchNoneQueryBuilder on that shard.
