### ISSUE TITLE
Pure disjunctions should rewrite to a MatchNoneQueryBuilder when all clauses are instances of MatchNoneQueryBuilder

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48475]
`BoolQueryBuilder` already has logic to rewrite to a `MatchNoneQueryBuilder` when any of its required sub clauses is a `MatchNoneQueryBuilder`. We should add similar logic for pure disjunctions, this might help skip more shards.

**Comment by SivagurunathanV** [comment]
PR: https://github.com/elastic/elasticsearch/pull/48557.

**Comment by SivagurunathanV** [comment]
@jpountz Thanks 👍
