### ISSUE TITLE
Setting to whitelist allowed licenses

### ISSUE THREAD

**Issue by bytebilly** [elastic/elasticsearch#48508]
# Description

We want to introduce a new Elasticsearch setting to define which are the licenses that can be used in a specific cluster.

The main goal is to allow external coordinators (like ECK or ECE) to control which license can be installed on clusters that are centrally managed, and to avoid that inconsistent licenses are manually installed using direct access to the cluster.

# Proposal

Introduce the new setting and perform the check on the license type when a new license is sent via [Update license API](https://www.elastic.co/guide/en/elasticsearch/reference/current/update-license.html).

The setting name could be `xpack.license.whitelist` or some similar name.

The value is a string (or an array of strings) matching possible license types: `trial`, `basic`, `gold`, `platinum`, `enterprise` (this one is a new value that we need to support).
Any combination of the above is valid.

The default value for this setting is to allow any license to be used.

# Questions

1. ~~Is it defined in `elasticsearch.yml`?~~ — YES
1. ~~Can it be updated via setting via API?~~ — NO
1. ~~Will the check happen also on bootstrap?~~ — NO

**Comment by bytebilly** [comment]
@tvernum I left a few technical questions in the first comment, and I'd like to hear from you which could be a possible approach.

Given our previous discussions and priorities, we should try to add this feature in 7.6 if possible.

**Comment by tvernum** [comment]
> Is it defined in elasticsearch.yml?

Yes

> Can it be updated via setting via API?

No, that would defeat the purpose. The reason we want the setting is so that the orchestrator can control the license management by controlling the YML. If it's configurable via API then it is easy to by-pass the orchestrator.

> Will the check happen also on bootstrap

No, we don't plant to do this. It is to easy to leave a cluster is a broken state.

**Comment by bytebilly** [comment]
Thanks, description updated with these answers.
