### ISSUE TITLE
HybridDirectory should open .dim files with mmap

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#48509]
This is a follow-up to https://issues.apache.org/jira/browse/LUCENE-8932. The BKD index is now off-heap when the index input is a ByteBufferIndexInput. So if we want the index to move off-heap with the default directory implementation when upgrading to Lucene 8.4, we should make `HybridDirectory` open `dim` files with mmap.

@jdconrad I'm assigning it to you if you don't mind since you worked on the Lucene change

**Comment by jdconrad** [comment]
@jpountz Happy to work on this. Will likely have follow up question soon :)

**Comment by jdconrad** [comment]
Closed by #49272
