### ISSUE TITLE
>test-mute PRs run docs check and no precommit

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48505]
See e.g. https://github.com/elastic/elasticsearch/pull/48504 which is labelled `>test-mute` since it is merely muting a test. I was expecting this to run a precommit, but instead it runs a docs check. This seems wrong to me.

**Comment by jkakavas** [comment]
As a data point the last PR with this label that ran precommit checks as far as I can see is #44159 on July 10.
