### ISSUE TITLE
[DOCS] omission of core thread pools "management,  flush, force_merge, fetch_shard_started and fetch_shard_store"

### ISSUE THREAD

**Issue by dharada** [elastic/elasticsearch#48524]
**Describe the feature**: This is not feature request.  Just a document issue.

**Elasticsearch version** (`bin/elasticsearch --version`): latest

**Plugins installed**: []

**JVM version** (`java -version`): n/a

**OS version** (`uname -a` if on a Unix-like system): n/a

**Description of the problem including expected versus actual behavior**:

These core thread pools are undocumented as of now.

- management
- flush
- force_merge
- fetch_shard_started
- fetch_shard_store

please check here.
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-threadpool.html

(ref)
https://github.com/elastic/elasticsearch/blob/d579f892dbd8e70acc27ecb95b9035a97352d8d8/server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L65

**Comment by jrodewig** [comment]
[docs issue triage]
