### ISSUE TITLE
SQL: incompatible intervals with IN operator

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#48540]
In [this PR](https://github.com/elastic/elasticsearch/pull/47595) we made date/datetime data types and intervals compatible, but one edge case scenario was still problematic: `SELECT INTERVAL 1 YEAR IN (INTERVAL 1 YEAR, INTERVAL 12 MONTH)`.

**Comment by wchaparro** [comment]
Superceded by ES|QL
