### ISSUE TITLE
`moveShards` of shards allocation should also take weight into account

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#48555]
ES_VERSION: 7.3.1
**Description of the problem including expected versus actual behavior:**
shards allocation contains three parts:
+ allocateUnassigned
+ moveShards
+ balance

we have known that we will compute the weight in `allocateUnassigned` and `balance` when deciding shard distribution. but the weight strateg is discard y in `moveShards`,  I see the function comment:
> 
> Move started shards that can not be allocated to a node anymore
> 
> For each shard to be moved this function executes a move operation
> to the minimal eligible node with respect to the
> weight function. If a shard is moved the shard will be set to
> {@link ShardRoutingState#RELOCATING} and a shadow instance of this
> shard is created with an incremented version in the state
> {@link ShardRoutingState#INITIALIZING}.
>
which you have considered it.

When a shard has to move to another node, it only meet  AllocationDeciders requirements, I think it is not enough, maybe the shard will be moved to another node again in `allocateUnassigned` later because of the high weight. 

If we should take weight into  account in `moveShards`?

**Comment by ywelsch** [comment]
we do take the weight into account, see `decideMove`, in particular the call to `sorter.reset(shardRouting.getIndexName());` which sorts `sorter.modelNodes` by weight, and on which we subsequently iterate to find the first match.
