### ISSUE TITLE
shards rebalance should take into account that shards distribution of a index among the multi path.data in on node may be unbalancedly

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#48551]
ES_VERSION: 7.3.1
**Description of the problem including expected versus actual behavior:**
when shards distribution decides how the shards of one index  distribute among the multi path.data  in on node, it may be unbalancedly, for example, the  shards distribution of index1  in a node  is as follow:
+ path1:  shard1
+ path2: shards2, shard3, shard4
+ path3: None

now shards distribution need to move one shard of index1 from the node to another node, it only consider the factors:
1. the shard is started.
2. the shard can `canAllocate` and `canRebalance` to the another node.
3. delta score is  lower or shardId is lower.
Related code is here:
https://github.com/elastic/elasticsearch/blob/94fe4806ce9449ec152a89e869064603fe13b296/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L992

Accord to the rules, it will pick out the shard1 because of equal weights for shards1/shard2/shard3, then move shard1 to another node, we can see that it may be unbalancedly for index1 in the node, the path1 will be free and path2 will be busy when index1 occurs a lot of writes or searches, so it should pick out the shard of path2, not the shard1.

If we could select the shard which is more unbalanced among the multi path in one node for a index. we just need to add the fourth factor here: https://github.com/elastic/elasticsearch/blob/94fe4806ce9449ec152a89e869064603fe13b296/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L1014

**Comment by kkewwei** [comment]
hi, @mayya-sharipova, is there anyone can confirm it?

**Comment by ywelsch** [comment]
The balancer is unaware of multiple data paths, and making it so would require significant effort. It sounds as if the solution you're proposing would require us to make quite a significant change in the way the balancer works today. We're currently not planning on making such changes, and are evaluating whether we want to continue supporting multiple data paths in the way it is done today.
