### ISSUE TITLE
`timeout` for bulk request no working

### ISSUE THREAD

**Issue by hydrogen666** [elastic/elasticsearch#48563]
We have an `elasticsearch` 6.2.4 cluster with 3 `master`, 10 `data` and 3 `coordinator`. We set `BulkRequest` with timeout `60s` and http client timeout `70s`. When a data node having a network interface failure, our bulk client will got timeout with an `EOF` and retry, this causes the coordinating node OOM at `TransportService#clientHandlers`.

After reading the code of 6.2.4 and 7.4, time `timeout` parameter of `BulkRequest` is only used for `TransportReplicationAction.ReroutePhase#observer` [7.4.0](https://github.com/elastic/elasticsearch/blob/v7.4.0/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L640) and [6.2.4](https://github.com/elastic/elasticsearch/blob/v6.2.4/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L701) to wait shard ready.

**Comment by hydrogen666** [comment]
@mayya-sharipova any solution about this issue?

**Comment by njustyq** [comment]
hello，请问你的问题解决了吗？我也遇到一个类似的问题，能交流一下吗

**Comment by hydrogen666** [comment]
> hello，请问你的问题解决了吗？我也遇到一个类似的问题，能交流一下吗

南京理工的校友么？这边看了下具体的实现和之前的issue #15101，靠超时是解决不了的，如果replication因为超时失败的话，当前的实现会fail shard，如果频繁地因为网络问题超时导致fail shard，对系统稳定性是有影响的。所以这边还是推荐配置inflight_requests断路器来解决OOM的问题。

**Comment by hydrogen666** [comment]
After reading issue #15101 and the implementation. When doing replication on primary shard, if send request timeout due to network interface failure, the primary shard will send shard failure to current master node, the master will choose another replica and do peer recovery. Frequent shard failures can cause system stability issues. It's better config `inflight_requests` to a lower value to reduce probability of coordinating node OOM.

Or you can update to version 7.x, it do have a `real_memory` circuit breaker, see pull request #31767.

**Comment by njustyq** [comment]
> > hello，请问你的问题解决了吗？我也遇到一个类似的问题，能交流一下吗
> 
> 南京理工的校友么？这边看了下具体的实现和之前的issue #15101，靠超时是解决不了的，如果replication因为超时失败的话，当前的实现会fail shard，如果频繁地因为网络问题超时导致fail shard，对系统稳定性是有影响的。所以这边还是推荐配置inflight_requests断路器来解决OOM的问题。
> 
> 或者看下7.x版本的 `real_memory`断路器 #31767

哈哈哈，你也是南理工的吗？校友可以留个wx交流一下吗？我邮箱njustyq@163.com
