### ISSUE TITLE
using minimum_should_match with percent values in combination with trigrams produces wrong results

### ISSUE THREAD

**Issue by maxdreamland** [elastic/elasticsearch#48569]
Hi,

I stumbled upon something in ES 6.8 (linux) that i consider to be a bug.

Here is the simple 3-step way to reproduce the effect.

1) create a simple test index with a single field that is indexed as trigrams:

```
PUT /test

{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "analysis": {
        "analyzer": {
          "normalized_name_trigram_analyzer": {
            "type": "custom",
            "tokenizer": "only_letters_trigram"
          }
        },
        "tokenizer": {
          "only_letters_trigram": {
            "type": "ngram",
            "min_gram": 3,
            "max_gram": 3,
            "token_chars": [
              "letter"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "sampletype": {
      "properties": {
        "lastName": {
          "type": "text",
          "analyzer": "normalized_name_trigram_analyzer"
        }
      }
    }
  }
}

```
2) Place a single documement into the index:

```
PUT /test/_doc/1

{
    "lastName" : "fischhaber"
}

```
3) Execute a query for lastName="fischer" and minimum_should_match=75%:

```
POST /test/_search

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "lastName": {
              "query": "fischer",
              "minimum_should_match": "75%"
            }
          }
        }
      ]
    }
  }
}

```
Notice that you will find a single result:

```
{
   "took": 0,
   "timed_out": false,
   "_shards":    {
      "total": 1,
      "successful": 1,
      "skipped": 0,
      "failed": 0
   },
   "hits":    {
      "total": 1,
      "max_score": 0.8630463,
      "hits": [      {
         "_index": "test",
         "_type": "sampletype",
         "_id": "1",
         "_score": 0.8630463,
         "_source": {"lastName": "fischhaber"}
      }]
   }
}

```
Also notice that only 3 of the 5 trigrams of "fischer" match the 8 trigrams of "fischhaber". so the match-ratio is 60% and therefore below the limit of 75%. so there should have been no result!

if you use trigram counts instead of percent values it works correctly:

```
POST /test/_search

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "lastName": {
              "query": "fischer",
              "minimum_should_match": "3"
            }
          }
        }
      ]
    }
  }
}

```
This will produce one hit. Change the limit from 3 to 4 and you will no longer get any results.

So it seems, that internally the correct number of matching trigrams/tokens is computed, but the interpretation in percent values seems to be buggy.

regards
Mario

**Comment by cbuescher** [comment]
Hi @maxdreamland, 

the  `minimum_should_match` parameters [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html) mentions "The number computed from the percentage is rounded down and used as the minimum", and since this is computed with relation to the query, I would take this to mean the following:
"fischer" analyzes to 5 trigrams, 5 * 0.75 = 3.75 which rounds down to 3. 80% would then lead to 4 needed clauses to match. This lines up with your observation with using 3 or 4 directly. I think this explains the current behaviour and I will close this issue but please reopen if you are think I'm missing something.

**Comment by maxdreamland** [comment]
I agree with your explanation, it makes sense. thanks for clearing it up!
