### ISSUE TITLE
code in same version has conflict constructor in different platform

### ISSUE THREAD

**Issue by godlockin** [elastic/elasticsearch#48616]
ES 7.4
server/src/main/java/org/elasticsearch/index/analysis/AbstractTokenizerFactory.java

The constructor for this class has conflict, ref below.

the parameters in these 2 constructors has the difference sequence

Github:[indexSettings, settings, name] VS. Maven:[indexSettings, name, settings]

Github version
[AbstractTokenizerFactory](https://github.com/elastic/elasticsearch/blob/60b460d38a1d3a88e208fb7f1285640804866450/server/src/main/java/org/elasticsearch/index/analysis/AbstractTokenizerFactory.java)
```
public AbstractTokenizerFactory(IndexSettings indexSettings, Settings settings, String name) {
        super(indexSettings);
        this.version = Analysis.parseAnalysisVersion(this.indexSettings.getSettings(), settings, logger);
        this.name = name;
    }
```

Maven repository version
[7.4.0 maven ref](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch/7.4.0)

```
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch</artifactId>
    <version>7.4.0</version>
</dependency>
```
```
public AbstractIndexAnalyzerProvider(IndexSettings indexSettings, String name, Settings settings) {
        super(indexSettings);
        this.name = name;
        this.version = Analysis.parseAnalysisVersion(this.indexSettings.getSettings(), settings, logger);
    }
```

**Comment by jimczi** [comment]
Sorry but I don't understand the issue. Your example mentions `AbstractTokenizerFactory` and then you say that `AbstractIndexAnalyzerProvider`,  which is a different class, conflicts with the former. While we could make these ctrs use the same order for consistency I don't see how these classes "conflict". Can you explain ?

**Comment by godlockin** [comment]
I checked the issue, this was my mistake to compile the wrong code  branch
