### ISSUE TITLE
[Feature Request] return updated docs on updateByQuery API calls

### ISSUE THREAD

**Issue by gmmorris** [elastic/elasticsearch#48624]
Hi Team,
Our work optimising Kibana's Task Manager has unearthed a few places where we believe we can improve performance significantly if we could get a change made to the `updateByQuery` API.

**Describe the feature**:
*The Use Case*
We currently use an `updateByQuery` API call to find tasks which are ready to be picked up and we use the `update` to mark these tasks by updating the relevant documents by marking them (updating a field to have the UUID of the current Kibana, though that's immaterial).

Once the `updateByQuery` has completed (we call this the `query & mark` phase), we then need to make a `search` call in order to find all the documents we've just updated (called the `sweep and collect` phase).

This has two drawbacks:
1.  We need to make two calls, the `query & mark` followed by the `sweep and collect`, in order to achieve a stage that we believe could be done in one call- find the relevant tasks and "claim" them so that no other Kibana can do the same.
2. We have to wait for the `refresh` to take place before we can make the `sweep and collect`, forcing us to use `refresh:true` on the `updateByQuery` call.

*Proposed Solution*
What we'd like you to consider is making it possible to request that the `updateByQuery` call actually return the documents that have been updated by the query.
This would save us the second api call (which will make us _faster_) and would mean waiting for the refresh isn't needed.

if it helps, we can definitely live with this limitation existing on this, such as `max_docs` being specified.

Cheers

**Comment by dnhatn** [comment]
A similar request at https://github.com/elastic/elasticsearch/issues/45460.

**Comment by gmmorris** [comment]
Thanks @dnhatn , I see that issue was closed as it is felt this change is too expensive? Am I right in thinking it's too expensive in execution time?

Is it possible to make this configurable, so that only API calls that are willing to pay the cost, do so?

**Comment by jasontedor** [comment]
We do not think this API should be modified as proposed as it presents quite some challenges, similar to what has been pointed out before:
 - the response to a large update by query (update all docs) could be massive, more than the server or the client could buffer
 - while we see your thoughts around adding some limitations around this, we think that complicates our APIs too much, we aim to keep the surface area of them small, and that doesn't feel general purpose but merely specific to the Kibana use-case
