### ISSUE TITLE
Add query cache hit count and field data cache hit count to rest API 

### ISSUE THREAD

**Issue by clandry94** [elastic/elasticsearch#48645]
**Describe the feature**:

I was investigating cache hit ratios in Elasticsearch clusters recently and noticed that the `request_cache` has a `hit_count` and `miss_count` exposed through the rest API but the `query_cache` and `fielddata` cache do not as seen h ere https://github.com/elastic/elasticsearch/blob/18f5690ce75ab0bbd7a564cbb49ff7c42e86e978/server/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java#L157-L169. 

The values seem to be available within the `QueryCacheStats` class but not `FieldDataStats` class so would it make sense to make the `QueryCache` rest API on parity to the `RequestCache` rest API? Also having the field data cache hit and miss counts would be very useful as well but seems to be a bit more work to implement. 

I can implement these features if it would be useful

**Comment by jtibshirani** [comment]
As a point of clarification -- it seems the [node stats API](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/cluster-nodes-stats.html) returns this information, but it is not available in the [cat nodes API](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/cat-nodes.html).

**Comment by samz007** [comment]
@clandry94 I am beginner source contributions, Can I start working on this?

**Comment by clandry94** [comment]
@samz007 sure :slightly_smiling_face: feel free to comment if you have any questions and I can try to help out.

**Comment by abhishek8gupta** [comment]
Is anyone picking up this one? or can I pick up? I am beginner to ES group.

**Comment by samz007** [comment]
@clandry94  Started working on this issue. Thanks.

**Comment by ak-24** [comment]
Is this issue still open and unassigned ?

**Comment by clandry94** [comment]
I won't have time to work on this for the foreseeable future, so if someone else would like to grab it feel free 😄

**Comment by parthpunkster** [comment]
Can I start working on this one?

**Comment by Priya-Raut** [comment]
Is this issue still unassigned? Can I start working on it?
