### ISSUE TITLE
Look into integrating IndexSortDocValuesRangeQuery.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#48665]
We recently added the range query `IndexSortDocValuesRangeQuery` to Lucene, which takes advantage of index sorting to run only on doc values (https://issues.apache.org/jira/browse/LUCENE-7714).  When the following conditions hold, the query is able to run efficiently using only doc values, otherwise it must fall back to a delegate range query: 
* The index is sorted, and its primary sort is on the same field as the query.
* The query field has SortedNumericDocValues.
* The segment has at most one field value per document.

We should investigate whether it could be helpful to integrate this query into Elasticsearch. In particular, it may allow us to avoid indexing the field used for the primary index sort, while still supporting range queries. There are a few open questions around the integration:
* If the field is not indexed, then there is no efficient range query to fall back to. Could we somehow ensure that the documents contain only one field value, to make sure we can run efficiently on doc values?
* The query has only been benchmarked against dense doc values, and may not show good performance on sparse doc values. Is there anything we can do to improve the sparse case, or at least guard against it?

**Comment by dgieselaar** [comment]
If we were to sort indices based on timestamps, would this feature make range queries (that include aggregations or track_total_hits) on a large set of data significantly faster?

**Comment by jimczi** [comment]
> If we were to sort indices based on timestamps, would this feature make range queries (that include aggregations or track_total_hits) on a large set of data significantly faster?

It could speed up the query a bit but it wouldn't make the aggregations faster to run. The main benefits for this feature would be seen on range queries that can early terminate so without aggregations and with track_total_hits set to a low value. However, as explained in the description, this would also allow to disable indexing on the field and relies only on doc-values, which could be helpful to reduce the size of the index.

**Comment by jtibshirani** [comment]
> The main benefits for this feature would be seen on range queries that can early terminate so without aggregations and with track_total_hits set to a low value.

@jimczi thinking about the query implementation, I'm not sure how it relates to early termination. Would you be able to explain this more?

**Comment by jimczi** [comment]
I am thinking of early termination in the context of a query sorted by the same field than the index. In such case, the range query can use the doc values to jump directly to the first doc id that matches the range and the top field collector can stop whenever enough hits have been collected. This logic is implemented in the top field collector so you don't need to do anything in the query implementation. The main difference with a range query using the bkd-tree is that we don't need to build the bit set of all matching doc ids upfront, we can resolve the doc ids in order since the index is sorted and stops the collection whenever enough hits have been collected.

**Comment by jtibshirani** [comment]
I merged #56657 to use the index sort range query for fields of type `date`, `long`, and `integer`. I'm leaving this issue open, since there's still the question of whether we could skip points indexing for the sort field.

**Comment by jtibshirani** [comment]
I merged #56657 to use the index sort range query for fields of type `date`, `long`, and `integer`. I'm going to close this -- there's still the question of whether we can disable points indexing on the field, but I'd like to track that as part of #52728.
