### ISSUE TITLE
 ingest-user-agent: provide a way to extend the default regexes file

### ISSUE THREAD

**Issue by AE777F63** [elastic/elasticsearch#48683]
**Describe the feature**:
Currently in order to add new entries to the regexes file one needs to copy the default file, add the new entries, and configure the pipeline to use the new file. It would be convenient to be able to add new entries without having to maintain the content of the default file.
For example, regex_file option could be extended to accept an array of paths, i.e.
```
      "user_agent" : {
        "field" : "agent",
        "regex_file": ["custom-prepend.yml", "_default_", "custom-append.yml"]
      }
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
