### ISSUE TITLE
[feature request]high level search profile API

### ISSUE THREAD

**Issue by riverbuilding** [elastic/elasticsearch#48696]
like profile API declared: 
Note that the Profile API, amongst other things, doesn’t measure network latency, time spent in the search fetch phase, time spent while the requests spends in queues or while merging shard responses on the coordinating node.

currently the search profile API is actually query profile API.
 if there is a search profile API, which can provide below info:
query time per shard (maybe # of documents scanned, # of documents scored ),
fetch time per shard (maybe # of documents fetched),
merge time (maybe # of documents merged),
and total time (the time during a search in and out ES)

with above info, the overall situation can be summarized, which could help a lot when investigate search performance issues.

**Comment by javanna** [comment]
I agree on the need for a high-level search profile API, this is something that we recently had some discussions about. There is another issue logged with a very similar if not the same ask, hence I will close this issue in favor of #21073.
