### ISSUE TITLE
Reformat Gradle build script to use consistent indent

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#48727]
Our `build.gradle` files use a mix of 2 spaces and 4 spaces for indent width making it really frustrating when editing these files in an IDE configured one way or the other. Because this isn't consistent across all files it's not easily fixable by just reconfiguring IDE settings. Let's pick one and do the one-time step of reformatting all `.gradle` files. 

FWIW, my vote is for 4 spaces since it's consistent with existing conventions we use for Groovy and Java.

**Comment by jasontedor** [comment]
> Because this isn't consistent across all files it's not easily fixable by just reconfiguring IDE settings.

It's annoying that we have a difference between Gradle and Groovy files because otherwise we'd be fine here since IntelliJ appears to apply the same formatting configuration to both.

I personally like two-space indent. 😇

**Comment by mark-vieira** [comment]
> It's annoying that we have a difference between Gradle and Groovy files because otherwise we'd be fine here since IntelliJ appears to apply the same formatting configuration to both.

Indeed. It'd be nice to be able to configure IntelliJ to format Gradle files and plain Groovy files differently.

> I personally like two-space indent. 😇

I don't mind it for build scripts. But due to the IDE limitation, that'd effectively mean using 2-space indent for all Groovy code as well which I'm not a fan of.

**Comment by atorok** [comment]
I feel exactly as @mark-vieira I would like to have 2 space for scripts, but don't like it for groovy. 
There's a fix for that, we are not that far from getting rid of the groovy.

**Comment by pugnascotia** [comment]
We can also update `.editorconfig` so configure the indent for Gradle files. Any decent editor has support for `.editorconfig` files. I'd be happy to take this on, since I seem to have become Captain Formatte di Whitespace

**Comment by pugnascotia** [comment]
Sorry, meant to add - using `.editorconfig` means we can have a 2-space indent in script files, but 4 in regular Groovy files.

**Comment by pugnascotia** [comment]
Closed by #48849.
