### ISSUE TITLE
SQL: improve the SQL CLI documentation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#48729]
Our documentation on the SQL CLI has few issues (a bit of background [here](https://discuss.elastic.co/t/running-elasticsearch-sql-cli-script-on-remote-machines/205143)):
> The jar containing the SQL CLI is a stand alone Java application and the scripts just launch it. You can move it around to other machines without having to install Elasticsearch on them.

* Move what around? The jar? The script? The script AND the jar?
* Is the script really needed or a simple `java` command and the jar itself are enough? If so, we should be more clear on how to use the CLI on machines without ES installed on them, including a sample command.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by szabosteve** [comment]
https://github.com/elastic/elasticsearch/pull/52626 addressed this issue. Thank you for the PR @astefan.
