### ISSUE TITLE
[Docs] threadpool default size

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#48771]
[Threadpool documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html) mentions several times the default value of the  `size` of the threadpool as:
"The size parameter ...defaults to the number of cores times 5."

This happens for example in the section for [fixed auto queue size threadpool](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#fixed-auto-queue-size).  
But it looks like this default size is not used anymore, as each specific threadpool (for example search) has its own default size.  Is this definition still relevant or should it be removed?

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by szabosteve** [comment]
https://github.com/elastic/elasticsearch/pull/49442 solves the issue.
