### ISSUE TITLE
Analysis:  protecting tokens based on their length

### ISSUE THREAD

**Issue by loren** [elastic/elasticsearch#4877]
I would like to be able to tell the keyword marker to protect tokens 1-4 characters in length, or tell the minimal english stemmer to ignore tokens shorter than 5 characters.

Perhaps the more generic thing to have would be a Minimum Length Keyword Marker that could go in front of the other filters.

Based on discussion at https://groups.google.com/forum/#!msg/elasticsearch/uFlKWq2HvQk/mM8KjaItPH0J

**Comment by clintongormley** [comment]
This should be done in Lucene - nice easy one to adopt

**Comment by mikemccand** [comment]
> This should be done in Lucene - nice easy one to adopt

+1

**Comment by abeyad** [comment]
@loren we have exposed the pattern keyword marker token filter from Lucene in ES: https://github.com/elastic/elasticsearch/issues/23600

With this, you could specify your minimum token length as a regular expression pattern

**Comment by loren** [comment]
Excellent! And a much more widely useful solution than I had expected. Thanks!
