### ISSUE TITLE
QueryBuilder, XContentType, backslashes and you

### ISSUE THREAD

**Issue by amdious** [elastic/elasticsearch#48792]
While trying to play around with making [regex](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html) and backlashes, I was trying to get the following JSON to render:

`{ "regexp": { "field": { "value": "d\u00e9cor" } } }`

And that's when the problems started.  Using the High Level client I kept finding that it was searching for `d\\u00e9cor` and I couldn't figure out what on earth is escaping the backslash.  After more digging I find out that:

https://github.com/elastic/elasticsearch/blob/d92f362df041e4f68e8f18c83a5c4de0c74d8cc0/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java#L97

https://github.com/elastic/elasticsearch/blob/d92f362df041e4f68e8f18c83a5c4de0c74d8cc0/libs/x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContent.java#L61

From which you'll see that in Jackson they default escape the backslashes:

https://github.com/FasterXML/jackson-core/blob/0fdae270faefab96db3e0c586591bcce11fe2637/src/main/java/com/fasterxml/jackson/core/io/CharTypes.java#L164

Meaning that there's no way for me to send it unescaped since I have no way to configure the default XContentType.  At this point I'm thinking the best way it to make my own XContentType and use the low level client instead, but that seems like a lot of work just to deal with rendering characters literally.  I was also thinking about just saying to heck with it and find/replacing \uXXXX with unencoded value via [unescapeJava](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html#unescapeJava-java.lang.String-), but then where would it stop if tomorrow I needed to render \@?

Anyhow I'm mainly hoping someone can point me to something simple that I'm missing; otherwise if this could be a feature ask to allow users to have hooks into the jsonFactory (or REQUEST_BODY_CONTENT_TYPE) to be able to customize as needed.  Thanks!

**Comment by hub-cap** [comment]
Thx for adding this. Im looking at it to see what we can do about it.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
