### ISSUE TITLE
ES 6.6 is not support "ScriptService.ScriptType.INLINE",may be document should be updated 

### ISSUE THREAD

**Issue by BIYS** [elastic/elasticsearch#48790]
I think there may be a document bug at https://www.elastic.co/guide/en/elasticsearch/client/java-api/6.6/java-docs-update.html
ES version after 5.1 is not support "ScriptService.ScriptType.INLINE" 。 However, the  java api document still use it in it's usecase.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by BIYS** [comment]
In my view，this section should be change as follows

`
client.prepareUpdate("ttl", "doc", "1")
                .setScript(new Script(ScriptType.INLINE,
                        "ctx._source.gender = \"male\""
                        , null, null))
                .get();
`

**Comment by BIYS** [comment]
Can I submit a PR for it?

**Comment by jrodewig** [comment]
@BIYS Yes, contributions are welcome.

Please ensure you read our contribution guidelines before proceeding: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

As this issue still exists in the master branch, please use `master` as your base branch. Thank you!

**Comment by szabosteve** [comment]
#49424 solves it.
