### ISSUE TITLE
Create upgrade tests for typed mappings

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#48800]
We need to ensure that the following scenarios work correctly:
* [ ] create index with a type in 7x, ensure that untyped put and get mappings requests work in 8x
* [ ] create index with a type in 7x, snapshot it, and ensure that it works correctly when restored to 8x
* [ ] create index template with a type in 7x, ensure that matching indexes are correctly created in 8x

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
