### ISSUE TITLE
[DOCS]  `indices.lifecycle.poll_interval` listed as index level setting

### ISSUE THREAD

**Issue by danielyahn** [elastic/elasticsearch#48811]
One [ILM document](https://www.elastic.co/guide/en/elasticsearch/reference/current/using-policies-rollover.html) correctly lists `indices.lifecycle.poll_interval` as cluster setting.

However, in this section of the [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-settings.html#ilm-settings), `indices.lifecycle.poll_interval` is listed under index level setting.

**Comment by jrodewig** [comment]
Thanks for raising this @danielyahn. I've addressed with #48813.
