### ISSUE TITLE
Upgrading ES 5.6.9 to 6.4.0 Fails

### ISSUE THREAD

**Issue by TomasKuznetsov** [elastic/elasticsearch#48839]
##### Installed plugins:

- discovery-ec2

- repository-s3

- x-pack

##### JVM version:

- openjdk version "1.8.0_222"

- OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10) 

- OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

##### OS version:

- Distributor ID:	Ubuntu

- Description:	Ubuntu 16.04.6 LTS

- Release:	16.04

- Codename:	xenial

##### Description:

We have a cluster that consists of 3 master nodes, 2 data nodes, and 2 client nodes.
We try to perform a rolling upgrade from version 5.6.9 to 6.4.0 and encounter this error:

![es error](https://user-images.githubusercontent.com/26360621/68083302-cd223580-fe2f-11e9-9b9a-ea40fac8f68b.png)

We have tried multiple ways of upgrading and they all ended up in the same way, none of the upgraded nodes can join the cluster and they all get the same error, here are some of the things we have tried: 

1. Remove x-pack from all the instances and do a rolling restart and then start a rolling upgrade.

2. Tried a combination of settings to disable x-pack,  `node.ml: false` and `xpack.ml.enabled: false`, on all or off all, perform a rolling restart and then rolling upgrade.

3. Upgrade one Data / Master node

4. Add another three master nodes with the new version, wait for them to join the existing cluster and then drain the old master nodes and start the data nodes rolling upgrade

The only way we managed to get it working was by upgrading all three masters at the same time. after all three masters have been upgraded they joined the old data nodes and client nodes. but it's not a valid solution for us and a huge risk.

It seems like the main issue is that elasticsearch nodes without x-pack can't join a cluster that has nodes with x-pack installed.
We use elasticsearch 6 open source, so x-pack is not an option. 
We even reproduced this error without upgrading, we removed the x-pack plugin from one of the nodes in the cluster and restarted elasticsearch service. the node couldn't join the cluster till we removed the x-pack from the master nodes and restarted them.

##### Steps to reproduce:

 1. Create elasticsearch cluster (5.6.9) that consists of three master nodes, two data nodes, and two client nodes. (x-pack plugin must be installed)
 2. Follow elasticsearch rolling upgrade guide (we use puppet to install elasticsearch 6 open source)

##### logs:

![es log](https://user-images.githubusercontent.com/26360621/68083622-7ae31380-fe33-11e9-8b46-5963a78b7e87.png)

**Comment by javanna** [comment]
What you are describing makes sense, and you identified the problem yourself: when x-pack is installed, it expects x-pack to be installed on every node. That's by design. The specific error that you get is caused by nodes with x-pack installed sending over the network x-pack related info that the nodes without x-pack cannot decipher, hence the failure.

You can either do a full cluster restart, meaning that rolling upgrade will not work, or remove x-pack from the 5.6 nodes before starting the rolling upgrade.
