### ISSUE TITLE
Score with too many digits gets scrambled in last places

### ISSUE THREAD

**Issue by JanecekJ** [elastic/elasticsearch#48845]
**Elasticsearch version**: 7.4.2

**Plugins installed**: []

**JVM version** : 1.8.0_221

**OS version** : 18.04.2-Ubuntu

**Description of the problem including expected versus actual behavior**:
Using elasticsearch 7.4.2 we encountered a strange behavior.
While using function_score query with [script_score](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl-function-score-query.html#function-script-score) and resulting score with many digits, the final score is changed from the number returned  by script.

Expected result: 1234567890
Actual result: 1.23456794E9

The problem is the last digits change from **890** to **940**.

Is it possible, that between the calculation of score and final result, the score is temporarily stored in, for example, float field, causing a loss of precision?

**Steps to reproduce**:

 1. Create index:
PUT /test
```
{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 1
    }
}
```

 2. Index items:
```
POST /test/_doc/
{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}

POST /test/_doc/
{
    "user" : "kimchy 2",
    "post_date" : "2010-11-15T14:12:12",
    "message" : "trying out Elasticsearchanother time"
}
```

 3. Query search:
```
GET /test/_search
{
    "explain": true,
    "size": 5,
    "query": {
        "function_score": {
            "query": {
                "match_all": {}
            },
            "script_score" : {
                "script" : {
                  "inline": "1234567890"
                }
            }
        }
    }
}
```

4. Results in:
The first hit
<pre>
"max_score": 1.23456794E9,
"hits": [
    {
        "_shard": "[test][0]",
        "_node": "hBT4HfzdSX6QKBBHpkdmKA",
        "_index": "test",
        "_type": "_doc",
        "_id": "zl9QNm4BspuaxsAfOjks",
        "_score": <b>1.23456794E9</b>,
        "_source": {
            "user": "kimchy",
            "post_date": "2009-11-15T14:12:12",
            "message": "trying out Elasticsearch"
        },
        "_explanation": {
            "value": <b>1.23456794E9</b>,
            "description": "function score, product of:",
            "details": [
                {
                    "value": 1.0,
                    "description": "*:*",
                    "details": []
                },
                {
                    "value": <b>1.23456794E9</b>,
                    "description": "min of:",
                    "details": [
                        {
                            "value": <b>1.23456794E9</b>,
                            "description": "script score function, computed with script:\"Script{type=inline, lang='painless', idOrCode='<b>1234567890</b>', options={}, params={}}\"",
                            "details": [
                                {
                                    "value": 1.0,
                                    "description": "_score: ",
                                    "details": [
                                        {
                                            "value": 1.0,
                                            "description": "*:*",
                                            "details": []
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "value": 3.4028235E38,
                            "description": "maxBoost",
                            "details": []
                        }
                    ]
                }
            ]
        }
    }
</pre>

**Comment by jpountz** [comment]
Scores are floats indeed. I'm making this a docs issue, we should document it more clearly.

**Comment by jrodewig** [comment]
[docs issue triage]
