### ISSUE TITLE
Enhancement: OpenJ9 JVM support for ELK

### ISSUE THREAD

**Issue by jagansankara** [elastic/elasticsearch#48847]
As Eclipse stated comparison results of other JVM vs OpenJ9 JVM in its websites ( and in some other sites also), OpenJ9 JVM uses less memory foot print and faster startup time.  

If ELK supports OpenJ9 JVM, it would be better to use ELK service in less memory if above its advantages are true.

**Comment by williamrandolph** [comment]
Thanks for raising this issue. We don't have any plans to support OpenJ9 right now.

We've been deliberate in our choice of JDKs to support. Developing and testing for another JDK increases the testing and maintenance burden, and our team has to ensure that every Elasticsearch release works correctly on that JDK. Our support matrix shows which JDKs we do support. https://www.elastic.co/support/matrix#matrix_jvm

We also don't know that OpenJ9 would improve performance _for Elasticsearch_. Given that we have put a great deal of effort into understanding tradeoffs and optimizing performance for Hotspot JDKs, I don't think we can assume that OpenJ9 would offer better performance to our users.

Given all that, I hope you understand if we close this issue.
