### ISSUE TITLE
es6.x upgrade es7.x the same data and settings appear circuit_breaking_exception

### ISSUE THREAD

**Issue by ChenJhua** [elastic/elasticsearch#48842]
**I tried to adjust the circuit breaker limit and heap memory, the same error, but the size of the data triggered by the circuit breaker is increasing**
`{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [14145003552/13.1gb], which is larger than the limit of [13915717632/12.9gb], real usage: [14145003552/13.1gb], new bytes reserved: [0/0b]","bytes_wanted":14145003552,"bytes_limit":13915717632,"durability":"PERMANENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [14145003552/13.1gb], which is larger than the limit of [13915717632/12.9gb], real usage: [14145003552/13.1gb], new bytes reserved: [0/0b]","bytes_wanted":14145003552,"bytes_limit":13915717632,"durability":"PERMANENT"},"status":429}`

**Comment by CucurbitBrothers** [comment]
I have the same issue.

> TransportError: TransportError(429, u'circuit_breaking_exception', u'[parent] Data too large, data for [<http_request>] would be [1026207274/978.6mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1026206768/978.6mb], new bytes reserved: [506/506b], usages [request=0/0b, fielddata=1474/1.4kb, in_flight_requests=506/506b, accounting=2595853/2.4mb]')

**Comment by javanna** [comment]
We reserve github for confirmed bug reports and feature requests. This does not seem to fit in either category, but is rather a question. Would you mind opening a new thread in our forums at https://discuss.elastic.co if you haven't already done so?

**Comment by ChenJhua** [comment]
yes， I'm very sorry
