### ISSUE TITLE
Confusing Example: /_security/privilege/<application>/<privilege>

### ISSUE THREAD

**Issue by AndrewMcQuerry** [elastic/elasticsearch#48846]
The example for using the _security/privilege endpoint to create or update an application privilege is a tad confusing.

/x-pack/docs/en/rest-api/security/put-app-privileges.asciidoc

The description states:

> To add a single privilege, submit a PUT or POST request to the /_security/privilege/\<application\>/\<privilege\> endpoint

But, the example only shows executing against the _security/privilege endpoint.

```
PUT /_security/privilege
{
  "myapp": {
    "read": {

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by szabosteve** [comment]
https://github.com/elastic/elasticsearch/issues/48846 solves it. I close the issue.
