### ISSUE TITLE
repository-s3 not uploading snapshot to s3.

### ISSUE THREAD

**Issue by suratpyari** [elastic/elasticsearch#48855]
Hi,

I am  running Elasticsearch on eks cluster. for backup to s3 I have added repository-s3 plugin.  When I run following command,

```
curl -X PUT "localhost:9200/_snapshot/my_s3_repository?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "s3",
  "settings": {
    "bucket": "uat-k8-elasticsearch-bckup",
    "region": "ap-south-1",
    "endpoint": "s3.ap-south-1.amazonaws.com"
  }
}
'
```

I receive ..

```
{
  "acknowledged" : true
}
```

But there is no upload on s3. Let me know how I can debug it.

Thanks in advance.

**Comment by original-brownbear** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
