### ISSUE TITLE
Improve documentation on search_as_you_type datatype

### ISSUE THREAD

**Issue by 2DSharp** [elastic/elasticsearch#48862]
The **search_as_you_type** datatype documentation is a bit vague in terms of how it can be more beneficial than a completion suggester.

It has been referenced in the **Completion Suggester** doc page: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester in a note, but it doesn't say _why_ or in _which case_ the new datatype can be better suited than the completion suggester.

Is it meant to be a replacement to completion suggester for auto-completion scenarios? If so, how can we add weights to the results (based on context or in general)?

The documentation could be refined to address some of those questions to make it clearer for the user. 

I will be happy to take on this issue and drop a PR if someone points me in the right direction.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by 2DSharp** [comment]
Any updates to this issue? @jrodewig @henningandersen

**Comment by jrodewig** [comment]
Thanks for reaching out @2DSharp. If you're still interested in contributing, a PR would be very welcome. 

Here are the  relevant Asciidoc source files for the completion suggester documentation:
https://github.com/elastic/elasticsearch/edit/master/docs/reference/search/suggesters/completion-suggest.asciidoc

We have some contribution guidelines here:
https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by 2DSharp** [comment]
Hi, @jrodewig I can get started with the PR, however, I could use some help. The `search_as_you_type` datatype doesn't seem to have much documentation in its page, could you point me to some resource which may help me get to understand it better?

**Comment by jrodewig** [comment]
Hi @2DSharp 

Here's the issue outlining the need and other context for the `search_as_you_type` field type:
https://github.com/elastic/elasticsearch/issues/33160

You can see the original implementation for the `search_as_you_type` field type here:
https://github.com/elastic/elasticsearch/pull/35600

Thank you for considering contributing!

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.
