### ISSUE TITLE
Documentation on safe cluster restarts for infrastructure maintenance

### ISSUE THREAD

**Issue by VimCommando** [elastic/elasticsearch#48869]
The current documentation for "how to safely restart a cluster" is framed solely in the context of performing an upgrade to the Elastic version:
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/rolling-upgrades.html

Even the page title **Rolling upgrades** does not give any indication it could apply to anything _but_ upgrades. This is very bad for discoverability. If you simply search for "cluster restart" you are greeted with these results:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1674688/68236238-e7cbea00-ffa8-11e9-9177-efd79863c81f.png">

A full-outage cluster restart on a major upgrade is the top result--far from "I upgraded some system packages and need to restart the OS on each node" that inspired the search. Infrastructure upgrades also need information in the **Rolling upgrades** document covers.

**Comment by DaveCTurner** [comment]
Duplicates #48051
