### ISSUE TITLE
Make clear license pre-requisites in Kibana SAML guide

### ISSUE THREAD

**Issue by DominicWatson** [elastic/elasticsearch#48871]
# Feature request

The SAML setup guide in the docs: [https://www.elastic.co/guide/en/elasticsearch/reference/7.4/saml-guide.html](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/saml-guide.html) makes no mention of either the licensing prerequisite, or the general authentication setup requirement. The guides all assume that authentication is turned on and make no mention of needing to setup authentication at all.

This makes sense if you are running a licensed version which has it turned on by default :) 

However, for those complete new and  trying to setup and get things working in a test environment, for example, this absent information could lead to a lot wasted time :)

**Comment by gogovan-vincentngai** [comment]
Yeah...
take a very long time and reveiw logging 

then see this 

`{"type":"log","@timestamp":"2020-01-16T09:40:38Z","tags":["debug","plugins","security","saml"],"pid":7,"message":"Failed to initiate SAML handshake: [security_exception] current license is non-compliant for [saml], with { license.expired.feature=\"saml\" }"}`

current license is non-compliant for [saml] .....so sad...

**Comment by jrodewig** [comment]
The [SAML documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/saml-guide.html) has an `x-pack` tag, which indicates a licensed feature. This tag links to https://www.elastic.co/subscriptions, where you can see the difference license levels.

<img width="672" alt="Screen Shot 2020-07-31 at 3 47 46 PM" src="https://user-images.githubusercontent.com/40268737/89071745-5033d600-d345-11ea-8d81-07fe8c799324.PNG">

**Comment by mchudinov** [comment]
For me as for newbie x-pack tag says nothing.
It should be explicitly indicated in the documentation in what version the feature is supported.
I spend around 2 hours today to find out what is wrong with my setup and why SAML auth does not work.

**Comment by hopik007** [comment]
3 years and doc still not updated. Bravo

**Comment by cheetah25** [comment]
@hopik007 , its 5 years * 😂
