### ISSUE TITLE
Named query (_name) causes slower response time

### ISSUE THREAD

**Issue by jamesdaily** [elastic/elasticsearch#48870]
**Elasticsearch version**: 7.1

**Plugins installed**: None / standard

**JVM version** (`java -version`): 1.8.0_201

**OS version** (`uname -a` if on a Unix-like system): Windows 7

**Description of the problem including expected versus actual behavior**:
Named queries lead to slow response times, especially when searching among many inner hits of nested documents. 

The more parts with _name specified, the slower the response, especially if the field has fuzziness enabled.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create an index with a nested document, for example People (first and last names) with nested documents for their multiple mailing addresses (city, state, zip)
 2. Load a few million records
 3. Execute a search against a bool match of first and last name with fuzziness enabled, as well as a nested query of shoulds for the address parts, again with fuzziness enabled. Take note of average response "took" time. In my index of about 2-3 million records, it is about 20-40ms.
4. Add _name to all possible query parts. Take note of new average responses time - in my experience it is higher - up to 50-70ms. It is worse when searching nested fields, although in my dataset there are more nested documents than main documents (many addresses per person). With an even larger index and more complicated query, I experienced variation from 50-70ms without named parts, to 220-250ms with named parts.

Sample index mapping:

    {
      "mappings": {
        "properties": {
          "first_name": {
            "type": "text"
          },
          "middle_name": {
            "type": "text"
          },
          "last_name": {
            "type": "text"
          },
          "addresses": {
            "type": "nested",
            "properties": {
              "city": {
                "type": "text"
              },
              "state": {
                "type": "text"
              },
              "zip": {
                "type": "text"
              }
            }
          }
        }
      }
    }

Sample query (add/remove _name properties as needed):

    GET people_index/_search
    {
      "query": {
        "bool": {
          "_name": "TopLevelName",
          "must": [
            {
              "match": {
                "last_name": {
                  "query": "Eisenhower",
                  "_name": "LASTFUZZ_MATCH",
                  "fuzziness": "auto"
                }
              }
            }
          ],
          "should": [
            {
              "match": {
                "last_name": {
                  "query": "Eisenhower",
                  "_name": "LAST_MATCH",
                  "boost": 30
                }
              }
            },
            {
              "match": {
                "first_name": {
                  "query": "Dwight",
                  "fuzziness": "auto",
                  "_name": "FIRSTFUZZ_MATCH",
                  "boost": 20
                }
              }
            },
            {
              "nested": {
                "path": "addresses",
                "inner_hits": {},
                "query": {
                  "bool": {
                    "should": [
                      {
                        "match": {
                          "addresses.city": {
                            "query": "Orlando",
                            "fuzziness": "auto",
                            "_name": "CITY_MATCH",
                            "boost": 10
                          }
                        }
                      },
                      {
                        "match": {
                          "addresses.state": {
                            "query": "FL",
                            "_name": "STATE_MATCH",
                            "boost": 10
                          }
                        }
                      },
                      {
                        "match": {
                          "addresses.zip": {
                            "query": "12345",
                            "_name": "ZIP_MATCH",
                            "boost": 10
                          }
                        }
                      }
                    ]
                  }
                }
              }
            }
          ]
        }
      }
    }

**Comment by javanna** [comment]
This fell through the cracks: we should have looked at a profile output when this was opened, a long time ago. I suspect that we would have seen longer fetch time when named queries are used. That is because named queries do cause some additional overhead, as they are implemented as a subfetch phase that more or less re-runs each query on the shards that have top hits. I am not sure there's anything we can do to improve this. If you bump into this issue, leave a comment and provide a profile output so that we can analyze further.
