### ISSUE TITLE
[Docs] The mechanics of CCR

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#48875]
[The mechanics of replication in CCR overview](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-overview.html#_the_mechanics_of_replication) 

> "Otherwise, if the timeout elapses, the follower shard replies that there are no new operations."

Because replication is pull-based，so "the follower shard" is "the leader shard" correctly?

**Comment by jasontedor** [comment]
Yes, thank you for catching this. Would you be interested to submit a patch to our docs to fix this?

**Comment by gaobinlong** [comment]
I'm glad to do this.

**Comment by gaobinlong** [comment]
#48882

**Comment by gaobinlong** [comment]
#48882
