### ISSUE TITLE
Unable to install Elasticsearch7.4.x with AdoptOpenJDK  1.8.0_232 OpenJ9-0.17.0 JVM

### ISSUE THREAD

**Issue by nikhil-machcha** [elastic/elasticsearch#48876]
Installation of Elasticsearch7.4 via .ZIP package fails on Windows 10 machine running AdoptOpenJDK  1.8.0_232 OpenJ9-0.17.0 JVM

Though it is supported per https://www.elastic.co/support/matrix#matrix_jvm,

**Elasticsearch version** (`bin/elasticsearch --version`): 7.4

**JVM version** (`java -version`):
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20191016_492 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
Expected: Successful ES-7.4 installation
Actual: Unsupported Java version error

**Steps to reproduce**:

 1. Prerequisites:
Windows 10 machine running AdoptOpenJDK  1.8.0_232 OpenJ9-0.17.0 JVM

 2.  Install Java via Source link https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9

 3. Install ES via https://www.elastic.co/guide/en/elasticsearch/reference/current/zip-windows.html
     cd into extracted folder
     $> .\bin\elasticsearch.bat

**Comment by jasontedor** [comment]
Sorry for the confusion but OpenJ9 is not supported, only HotSpot. We will clarify this in our support matrix.
