### ISSUE TITLE
elasticsearch-certutil prints several WARNING messages when creating certificates

### ISSUE THREAD

**Issue by hulkk** [elastic/elasticsearch#48879]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "11.0.5" 2019-10-15 LTS

**OS version** (`uname -a` if on a Unix-like system): Linux redacted 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elasticsearch-certutil binary prints several warnings when creating certificates as per documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html

**Steps to reproduce**:

It doesn't matter is the command executed as root/elasticsearch or is there parameters provided or not.

 1. `sudo /usr/share/elasticsearch/bin/elasticsearch-certutil`

**Provide logs (if relevant)**:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/usr/share/elasticsearch/lib/tools/security-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by 111andre111** [comment]
Hi, actually seems like this issue was fixed in
https://github.com/bcgit/bc-java/issues/510
So at the moment bcprov-jdk15on-1.61.jar v1.61 is used, and starting with 1.62 that should be fixed.

**Comment by albertzaharovits** [comment]
I think @111andre111 is right. Thank you!

Our latest release (7.12) ships with bc v1.64 which seems to have fixed it.

I've also tested it and it doesn't manifest.

**Comment by 111andre111** [comment]
@albertzaharovits 
Very nice. Quite an older issue. Thank you for double checking.
