### ISSUE TITLE
Why add hdfs schema limit, but not add viewfs support for repositories-hdfs plugin

### ISSUE THREAD

**Issue by konghui** [elastic/elasticsearch#48880]
**Describe the feature**:
Repositories-hdfs current support hdfs schema, I try the elastic 2.x. Viewfs can work correct. After 5.x the code here:
https://github.com/elastic/elasticsearch/blob/3ce7a37f1ff2ff4c24c97c60ce619f840ed1b7fb/plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java#L81

It make the repositories-hdfs not support viewfs. Is there any reason why add this code?

**Comment by ywelsch** [comment]
We can only support things that we test. Given that there are no tests for viewfs (and would be a non-trivial effort to add), and this is the first time that this ask has come up, I don't see this as any priority right now. To make it clear that we're not working on this, I'm closing this issue.
