### ISSUE TITLE
es5.6.8 basic license 导入失败

### ISSUE THREAD

**Issue by wanzi-520** [elastic/elasticsearch#48891]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):  es5.6.8

**Plugins installed**: []    logstash、head

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): centos 6.8

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.curl -XGET ‘http://ip:9200/_license’
 2.curl -XPUT ‘http://ip:9200/_license’ -d @license.json
 3.

**Provide logs (if relevant)**:
![Uploading 1.jpg…]()

**Comment by cbuescher** [comment]
Hi @wanzi-520! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
