### ISSUE TITLE
[feature request] Reaching per-cluster shard limit should be reflected somewhere

### ISSUE THREAD

**Issue by turchanov** [elastic/elasticsearch#48892]
We have just hit per-cluster shard limit (> node * max_shards_per_node). Aside from the client errors and elasticsearch logs there is no explicit indication of this condition. Cluster state is green. 

Shouldn't this cluster condtion be reflected somewhere, for example, turning cluster state to yellow or something?

**Comment by gwbrown** [comment]
I agree that it would be better to surface this somewhere more visible, but doing so in an API-based way is challenging.  Perhaps this would be good to add to Kibana (cc @elastic/es-ui)?

Turning the cluster health yellow currently has a well-defined meaning that hasn't changed in a long time, so I would be hesitant to make that change as it may lead to confusion.  But we should make it more visible somehow.

**Comment by alisonelizabeth** [comment]
Agreed that this sounds like a good candidate for the UI.

**Comment by patelvp** [comment]
Not sure how this can fit in the api model of es. But this seems like a good candidate to work on. I see the number of shards per node limit as a safety limit. Which if we do approach on production system can be safely increased given the resource utilization of the cluster. Just a visual indicator would help in alerting us to go check the cluster and increase it if it is safe to do so.

**Comment by dakrone** [comment]
We have this now reported in the health API in the shards_capacity indicator — https://www.elastic.co/guide/en/elasticsearch/reference/8.13/health-api.html
