### ISSUE TITLE
missing value not considered in min/max aggregations

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch#48905]
The missing value is not considered in min/max aggreagtions in es7 as they were in previous versions and I don't see this documented as a breaking change.  I believe this is due optimization of using segment min/max values.

To reproduce run the following against es6 and es7. The missing values should be returned as the min and max value of the aggregation.

```
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/1' -d '{"title": "with value", "value": 1}'
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/2?refresh' -d '{"title": "missing value"}'
curl -XPOST -H"Content-Type: application/json" 'localhost:9200/testmissing/_search?pretty' -d '{
    "size": 0,
    "aggs": {
        "min_missing": {
            "min": {
                "field": "value",
                "missing": -1
            }
        },
        "max_missinng": {
            "max": {
                "field": "value",
                "missing": 2
            }
        }
    }
}'
```

**Comment by imotov** [comment]
Which version of elasticsearch did you test it on. I just tried it on 7.4.2 and I am getting:

```
{
  "took" : 12,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "max_missinng" : {
      "value" : 2.0
    },
    "min_missing" : {
      "value" : -1.0
    }
  }
}
```

What am I missing? (some pun intended)

**Comment by mattweber** [comment]
You are right, it is fixed on `7.4.2`.  I was testing on `7.4.1`,  thanks!

**Comment by mattweber** [comment]
@imotov Actually no, issue still exists in `7.4.2`.  Appears to be inconsistent, run the following a couple times deleting the index between runs.  Min should be `-1` and max `10`.

```
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/1' -d '{"title": "with values", "value": [2, 3, 5]}'
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/2' -d '{"title": "with values", "value": [7, 1]}'
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/3' -d '{"title": "with values", "value": [8, 2, 5, 4]}'
curl -XPUT -H"Content-Type: application/json" 'localhost:9200/testmissing/_doc/4?refresh' -d '{"title": "missing value"}'
curl -XPOST -H"Content-Type: application/json" 'localhost:9200/testmissing/_search?pretty' -d '{
    "size": 0,
    "aggs": {
        "min_missing": {
            "min": {
                "field": "value",
                "missing": -1
            }
        },
        "max_missinng": {
            "max": {
                "field": "value",
                "missing": 10
            }
        }
    }
}'
```

I actually have the above in code using `ESIntegTestCase` that reproduces every time I run it.

**Comment by imotov** [comment]
Could you share this ESIntegTestCase? I cannot reproduce it with rest commands.

**Comment by mattweber** [comment]
@imotov Give this a try:

https://gist.github.com/mattweber/e12f28d288c4948d2fcb93c926677388

**Comment by imotov** [comment]
@mattweber Thanks! I was able to reproduce it using your test and @polyfractal suggested the fix. It turned out the reproduction depends on distribution of documents in segments. That's why I wasn't able to reproduce it in kibana. I am going to open a PR soon.

**Comment by mattweber** [comment]
Great! Thanks for working on it!

**Comment by zegging** [comment]
I ran these requests in ES 6.8. The maximum value changes before and after running a segment force-merge. I assume this is caused by the same bug?

```
PUT /test_metrics
{"mappings":{"_doc":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"},"grade":{"type":"float"},"timestamp":{"type":"date"},"weight":{"type":"float"}}}}}

POST /test_metrics/_bulk?refresh
{ "index": { "_id": "4", "_type": "_doc" } }
{ "id": "4", "name": "Cart Anderson", "timestamp": "2023-10-01T12:00:00Z", "weight": 1.0 }
{ "index": { "_id": "2", "_type": "_doc" } }
{ "id": "2", "name": "Alice Johnson", "grade": 78.0, "timestamp": "2023-10-01T12:00:00Z", "weight": 1.2 }

GET /test_metrics/_segments

# the max value is 78
POST /test_metrics/_search?request_cache=false
{"aggs":{"grade_max":{"max":{"field":"grade","missing":100.0}}}}

DELETE /test_metrics/_doc/2

POST /test_metrics/_bulk?refresh
{ "index": { "_id": "2", "_type": "_doc" } }
{ "id": "2", "name": "Alice Johnson", "grade": 78.0, "timestamp": "2023-10-01T12:00:00Z", "weight": 1.2 }

# check the segments, two segments
GET /test_metrics/_segments

# the max value is 100 
POST /test_metrics/_search?request_cache=false
{"aggs":{"grade_max":{"max":{"field":"grade","missing":100.0}}}}

POST /test_metrics/_forcemerge?max_num_segments=1

# after merge, the max value change back to 78
POST /test_metrics/_search?request_cache=false
{"aggs":{"grade_max":{"max":{"field":"grade","missing":100.0}}}}
```
After debugging Elasticsearch, I found that the issue may originate from the `org.elasticsearch.search.aggregations.metrics.max.MaxAggregator#findLeafMaxValue` method. It does not properly handle missing values and instead directly returns the segment maximum (segMax) as 78.

When the two documents are stored in different segments, the missing document's `pointValues` is null in the `findLeafMaxValue` method. Consequently, the method delegates to `LeafBucketCollectorBase` part in `org.elasticsearch.search.aggregations.metrics.max.MaxAggregator#getLeafCollector` to calculate the maximum value include MissingValues.

This is what I observed and inferred from my experiments, but I’m not sure if my conclusion is correct. Could you help me confirm whether my situation and the issue are caused by the same problem?
