### ISSUE TITLE
Can a Java program operate on multiple versions of elasticsearch?

### ISSUE THREAD

**Issue by sanjun1995** [elastic/elasticsearch#48913]
I need to develop an es automation tool.
Our company's es cluster has multiple versions.
I found that many clients require the corresponding ES version.
Currently I can only think of Java indirectly using the curl and http tools to operate the ES.
Such as "curl -XGET http://localhost:9200/_snapshot/test_backup/_all?pretty".
Automated tools designed in this way can operate all versions of ES.

I hope some experts can help me and provide some suggestions. Thank you.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
