### ISSUE TITLE
Enable geo_shape queries on geo_point field types

### ISSUE THREAD

**Issue by djptek** [elastic/elasticsearch#48928]
Enable `geo_shape` query to work on `geo_point` fields. Add a new query processor for lon, lat point queries and modify the field mapper to accommodate add a new `geo_shape` mapper.

**Comment by djptek** [comment]
working on this

**Comment by nreese** [comment]
Hi @djptek, wanting to check the status of adding geo_shape query support for geo_point fields. Is this feature targeting 7.6?

Kibana allows users to create filters from shapes in the UI. Those filters are placed in the URL. Having to put the shape geometry into the URL can cause the URLs to be too long and prevents users from creating filters from shapes when querying against geo_point fields. This is a large limitation and prevents users from filtering by shape in some cases. It is also a complex error to explain to users. Allowing pre-indexed shape query for geo_point fields would greatly simplify our messaging and allow filtering to work for any shape already indexed in ES and provide good messaging to users when shape is not indexed in ES. 

cc @elastic/kibana-gis

**Comment by nreese** [comment]
Here is a link to a related ES issue regarding pre-indexed query support for geo_points, https://github.com/elastic/elasticsearch/issues/46730

**Comment by djptek** [comment]
PR submitted for preliminary refactor post type-removal rework https://github.com/elastic/elasticsearch/pull/50737 now working on query processor

**Comment by djptek** [comment]
This issue now resolved, see PRs
#53774
#52382

**Comment by alexfrancoeur** [comment]
🎉 🎉 🎉 🎉 🎉
