### ISSUE TITLE
怎么获取es中的 tf 和 idf

### ISSUE THREAD

**Issue by zyh1218** [elastic/elasticsearch#48929]
hi 我想在查询的时候获取 tf 和idf  但是 把es中的explain开启的时候 得到的分数和数据结构无规律 无法解析  有其他好的办法嘛

**Comment by zyh1218** [comment]
还有 词频的offset

**Comment by cbuescher** [comment]
Hi @zyh1218! This looks like a general question (if auto-translate was correct) and is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. There is a section in the forum where you can also ask your questions in Chinese: https://discuss.elastic.co/c/in-your-native-tongue/chinese
