### ISSUE TITLE
get extra fields in Graph api

### ISSUE THREAD

**Issue by ddor254** [elastic/elasticsearch#48939]
Hello all , i am using elasticsearch v5.6 with an "xpack" license, i am doing a request to `//_xpack/_graph/_explore` as shown in the docs. 
the response is `vertices` and `connections` as expected. is there any way to add an "extra" field except the one pointed out in 
` "vertices": [
     {
        "field": "field1"
    }
 ]
` 

???

**Comment by cbuescher** [comment]
Hi @ddor254! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
