### ISSUE TITLE
Allow Elasticsearch to be an Identity Provider

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#48962]
Elasticsearch already allows authenticating users, either via the native realms or by connecting to other services. It also allows connecting to an external Identity Provider for an SSO experience. It will be great to allow a single Elasticsearch cluster to be itself an Identity Provider to other Elasticsearch cluster. This will allow supporting SSO between a group of clusters (and thus implicitly the associated Kibana). 

/cc @tvernum @jkakavas @skearns64 @uric

**Comment by skearns64** [comment]
cc @bytebilly @arisonl

**Comment by tvernum** [comment]
Resolved by #54046
