### ISSUE TITLE
JdbcResultSetIT.testGettingInvalidFloat

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#48992]
```
gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' -Dtests.seed=809F6C227F2212B8 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingInvalidFloat" -Dtests.security.manager=true -Dtests.locale=fr-NC -Dtests.timezone=Australia/Tasmania -Dcompiler.java=12 -Druntime.java=12
--
FAILURE 0.17s \| JdbcResultSetIT.testGettingInvalidFloat
```

Unclear if it's JVM related (Zulu) or not.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu12,nodes=general-purpose/322/console

https://gradle-enterprise.elastic.co/s/vck4hnwjlwszi/console-log?task=:x-pack:plugin:sql:qa:single-node:integTestRunner

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/51592
