### ISSUE TITLE
Allow specifying custom log config location

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#48994]
At the moment Elasticsearch is expecting log4j2.properties (name matters) files under config path (this is configurable from `path.conf`)
It would make debugging easier and allow more flexibility if log4j2 config file could be added from `log4j.configurationFile` property . 
It should merge with previously parsed config files.
This would also allow changing docker configuration at startup, which is at the moment only outputing on Console. Assuming that file will be present in the tweaked docker image.

**Comment by rjernst** [comment]
> It should merge with previously parsed config files.

We've historically opted for simplicity here, at least since around version 2.0. Merging files can be complex, and having several different overlapping settings like config directory (broad) and log4j config file (specific) can get confusing. We have similarly rejected allowing the keystore location to be configurable, always expecting it relative to the config dir.

Can you expand some more on the logic here behind some statements:

> It would make debugging easier 

What about debugging would an additional system property make easier?

> This would also allow changing docker configuration at startup

Could we implement this on our own without adding additional settings? What about correcting the console logging requires an additional file?

**Comment by pgomulka** [comment]
> It should merge with previously parsed config files...

The intention would be to let custom config be added to a `CompositeConfiguration` as it is done today and merged with a `DefaultMergeStrategy `(the same as at the moment). It should not override fully the provided configurations in `config`

> > It would make debugging easier
>
> What about debugging would an additional system property make easier?

When reproducing test failures, if you want to change multiple log levels or add custom appenders it is easier to be done with additional logging config. It is easier to modify the content of `config/log4j2.properties` file when running local cluster, but if you simply want to tweak the logging cluster of Rest/yml test it gets slighly more tedious.

The other way is to modify the gradle file of the module where the integ test is run from with 
```
testClusters.integTest {
  setting 'logger.org', 'trace'
}
```
I think this is also inconvenient and it would be great if could be modified from command line/additional property file. We can't do this at the moment?


> > This would also allow changing docker configuration at startup
> 
> Could we implement this on our own without adding additional settings? What about correcting the console logging requires an additional file?

I imagine in some situation user might want to opt out from console logging in docker and configure file logging. Can he override the `config/log4j2.properties` with his custom docker image? Not sure if there is a way to do this. Might be worth discussing.

**Comment by pgomulka** [comment]
closing as we decided that overriding full configuration is not needed for tests. Improvements to allow single log levels changes will be discussed here https://github.com/elastic/elasticsearch/issues/48672

chaning docker logging configuration can be done as indicated here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-config-bind-mount
