### ISSUE TITLE
Deboosting of search time synonym matches

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#49001]
Currently, if a search term is expanded via synonym filters, the term that is expanded to it treated the same way as the original search term in terms of search relevancy. For example, if I search for "automobile" and there is a synonym rule to expand this to "car", I can get results matching "car" ranked higher up than matches for the exact search term. Here is a very simple example that illustrates this:

```
PUT /test_index
{
    "settings": {
        "index" : {
            "analysis" : {
                "analyzer" : {
                    "synonym" : {
                        "tokenizer" : "standard",
                        "filter" : ["synonym"]
                    }
                },
                "filter" : {
                    "synonym" : {
                        "type" : "synonym",
                        "lenient": true,
                        "synonyms" : ["car, automobile"]
                    }
                }
            }
        }
    },
    "mappings": {
      "properties": {
        "field1" : {
          "type" : "text",
          "analyzer": "standard",
          "search_analyzer": "synonym"
        }
      }
    }
}

PUT /test_index/_doc/1
{
  "field1" : "fast car"
}

PUT /test_index/_doc/2
{
  "field1" : "fast automobile"
}

GET /test_index/_search
{
  "query": {
    "match": {
      "field1": "automobile"
    }
  }
}
```

When running this locally on one shard, both results returned have the same score. Ideally we should be able to take the token type of the search term into account and score the "car" match with a slightly lower boost than the one on the exact search term.

**Comment by AlShaffey** [comment]
This is one is actually important, however, I'm more towar having a weighted synonyms, so, I'm in need to have control over the weight of each of the sysnonyms something like [this](https://sease.io/2020/03/introducing-weighted-synonyms-in-apache-lucene.html).

So, it this possible?

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
