### ISSUE TITLE
Explain Enrich Policies at a higher level than APIs in documentation

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#49003]
I was recently working through the Enrich documentation to share an explanation of how things work, and found that there was no singular page that explained the flow at a high level.

Issues I felt:

- [enriching data](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-enriching-data.html) jumps straight into a list of steps of API calls
- an explanation of the structure of an enrich policy is mainly located within the [put-enrich-policy-api](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-enrich-policy-api.html) docs, which is not the most friendly place to be introduced to new terminology and ideas.

Expected structure from my point of view:

- the Enriching Data documentation should link to or contain a high-level description of how policies and processors/pipelines interact without getting lost in API call details
- May be useful to think of SEO when choosing wording and titles for the enrich documentation since I find it very difficult to find. The enrich REST APIs seem to be the easiest thing to stumble upon, so maybe a quick win would be a link back to the Enriching Data docs for more context.
- Have match and geo-match examples be treated similarly. Right now it seems the match policy example is being used in the initial flow docs, while the geo-match is hidden within the put-policy-api. Having the example within the put-enrich-policy-API be brought up a level and have dedicated page ([geo-match example](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-enrich-policy-api.html#put-enrich-policy-api-example)) might help with browsing for info.

These are just some thoughts I had that would make the docs feel easier to browse for me, feel free to disagree!

**Comment by jrodewig** [comment]
Thanks for the feedback @talevy!

The intent with [Enrich your data](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-enriching-data.html) was to introduce users to the concepts through a tutorial rather than frontloading that material. However, it sounds like that may have caused more friction than help.

I can definitely work on implementing some of these suggestions. Thanks for taking a critical look.

**Comment by martijnvg** [comment]
+1 to explain enrich policies at a different place than the put policy api page.
