### ISSUE TITLE
Rolling restart of the Elasticsearch cluster

### ISSUE THREAD

**Issue by rudziankou** [elastic/elasticsearch#49015]
Hi all,

I need to do an Elasticsearch upgrade from 5.1.1 to 5.6.7. I'm not so clear about the proper strategy. I need an advice. Let me know if there any other solution.

**Setup:**
3 master and 10 data nodes cluster

**Option 1:**
1. Disable shard allocation (if it's a data node).
2. Stop ES service on the node.
3. Upgrade it.
4. Start ES service.
5. Re-enable shard allocation.
6. Wait till cluster back to the green state.
7. Proceed to the next node and repeat all the steps.

**Option 2:**
1. Disable shard allocation.
2. Stop ES service on the node.
3. Upgrade it.
4. Start ES service
5. Proceed to the next node and repeat the steps 2-4.
6. Re-enable shard allocation when all the nodes are completed.

Best,
Ihar

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
