### ISSUE TITLE
v

### ISSUE THREAD

**Issue by jesinity** [elastic/elasticsearch#49010]
I think its worth moving them to a "list task response" common class tho like in server side, so we dont have to move them (or duplicate them cuz maybe the author did not see them here).

_Originally posted by @hub-cap in https://github.com/elastic/elasticsearch/pull/47017_

OK, I can add this extra class, containing all data. Actually this is going to be used also in the ListTasks, that is also broken

**Comment by hub-cap** [comment]
Im not sure we need a issue for this. But yes I agree we should add/fix it. You may consider doing that work first so it makes the cancel task issue easier to deal with and a smaller PR.

Im going to close this issue now that we know what needs to be done.

**Comment by jesinity** [comment]
I tried to comment but inadvertently opened a issue, sorry

**Comment by hub-cap** [comment]
no biggie :)
