### ISSUE TITLE
End-to-end search latency stats on coordinating nodes

### ISSUE THREAD

**Issue by wangkhc** [elastic/elasticsearch#49024]
Today we are lack of e2e search latency metrics on coordinating nodes, which is helpful for performance analyzation in OLAP scenario. For example, when a query with heavy aggregation happening on coordinating node, this cost is not being recorded in current query stats (only shard level on data nodes), we cannot track any information happening on coordinating nodes. 

With coordinating stats on e2e query latency, this is very helpful for OLAP users to realize that heavy aggregation is happening, and thus can further optimize their use-case. 

Relates #42788

**Comment by jakelandis** [comment]
Closing this and associated PR with an explanation here: https://github.com/elastic/elasticsearch/pull/49362#issuecomment-557694128
