### ISSUE TITLE
Order of result in complain auto-suggest

### ISSUE THREAD

**Issue by yzhymkov** [elastic/elasticsearch#49034]
**Elasticsearch version**: 7.3

**Plugins installed**: []

**JVM version**: jre1.8.0_221

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

Hello, guys. I have a problem with the order of result in complete auto-suggest

**Steps to reproduce**:
1. created index: put - `http://localhost:9200/test`

2. added mappings `{ "properties": { "suggest": { "type": "completion", "analyzer": "pattern", "preserve_separators": true, "preserve_position_increments": true, "max_input_length": 50 } } }`

3. added few docs:
```
{
"suggest": "Custom Color, Green, #0f0"
}
{
"suggest": "Custom Color Test, Red, #f00"
}
{
"suggest": "Custom Color NewTest, Blue, #00f"
}
```

4. I tried to make a searching query like this:

```
{
  "suggest": {
    "color_suggest": {
      "prefix": "Custom Color",
      "completion": {
        "field": "suggest",
        "skip_duplicates": true
      }
    }
  }
}
```

Current result:

- Custom Color NewTest, Blue, #00f
- Custom Color Test, Red, #f00
- Custom Color, Green, #0f0

Expect result:

- Custom Color, Green, #0f0
- Custom Color NewTest, Blue, #00f
- Custom Color Test, Red, #f00

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
