### ISSUE TITLE
[ML] Failure persisting datafeed timing stats leaves datafeed in limbo

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#49032]
Since 7.4.0 when a datafeed is stopped it tries to persist datafeed timing stats.  However, this is [done in the `finally` block in `DatafeedManager.stop()`](https://github.com/elastic/elasticsearch/blob/d308095b28d7398f7cbf0779780547363ce95380/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedManager.java#L373), and if it fails for some reason then the datafeed is not fully stopped.  It remains permanently in the `stopping` state, and due to #48931 there is currently no way to stop a datafeed that is stuck in the `stopping` state.

Failure to persist datafeed timing stats for some reason should be logged as a warning but should not prevent more critical datafeed shutdown actions from being attempted.

**Comment by przemekwitek** [comment]
This issue is now fixed.
