### ISSUE TITLE
facing socket timeout frequently after some idle time. (elasticsearch spring boot)

### ISSUE THREAD

**Issue by sumitkothariqp** [elastic/elasticsearch#49039]
Hi,

I am using below code to create rest highlevel client in spring boot application.

new RestHighLevelClient(RestClient.builder(
                new HttpHost(env.getProperty(ds + ".node1.host"),
                        Integer.parseInt(env.getProperty(ds + ".node1.port")), scheme),
                new HttpHost(env.getProperty(ds + ".node2.host"),
                        Integer.parseInt(env.getProperty(ds + ".node1.port")), scheme))
                .setRequestConfigCallback(
                        new RestClientBuilder.RequestConfigCallback() {
                            @Override
                            public RequestConfig.Builder customizeRequestConfig(
                                    RequestConfig.Builder requestConfigBuilder) {
                                System.out.println("setting timeout");
                                return requestConfigBuilder
                                        .setConnectionRequestTimeout(0)
                                        .setSocketTimeout(5000);
                            }
                        })
                .setFailureListener(new RestClient.FailureListener() {
                    @Override
                    public void onFailure(Node node) {
                        System.out.println("Failed Connection");
                    }
                }));

After some idle time socket connection is lost and I get socketConnectionTimeout exception.

Is there any way to maitain connection throughout?

**Comment by cbuescher** [comment]
Hi @forkforlearn! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by zhuaizhuaixi** [comment]
I face the same problem.
I find [similar problem in https://discuss.elastic.co](https://discuss.elastic.co/t/elastic-search-resthighlevelclient-delaying-when-doing-simple-requests-to-es/204801/1)
but there is no response.
