### ISSUE TITLE
About remove tansport client performance

### ISSUE THREAD

**Issue by deanjo** [elastic/elasticsearch#49040]
Hello 
I want to know why remove tansport client . HTTP1.1 that I know uses the text protocol and does not support multiplexing , so I think there is a huge performance difference between jest client and tansport client in high concurrency scenarios

**Comment by deanjo** [comment]
I've been confused ever since I know than transport client would be removed .
No one answered my questions in the official forum [https://discuss.elastic.co/t/about-remove-tansport-client-performance/207632](url)  and I couldn't find the performance comparsion between high level jest client and transport client

**Comment by jakelandis** [comment]
I provided an brief answer over at https://discuss.elastic.co, lets keep the discussion there. 

GitHub is for coding issues and error reporting.
