### ISSUE TITLE
RFE: ILM - different delete actions for size vs. time rollover triggers

### ISSUE THREAD

**Issue by obogobo** [elastic/elasticsearch#49046]
ILM has been a godsend for keeping our indices manageable in production, we greatly appreciate not having to rely on external code to do this anymore!

An additional feature that would be nice centers around the delete phase, specifically: being able to set separate delete actions for
- Time since an index rolled over, if it was triggered on **size**
- Time since an index rolled over, if it was triggered on **time**

An example in our case, we rollover when an index's shards hit ~50G, or if after 48 hours that hasn't happened yet, then delete 72 hours after the warm phase in either case. 

For the **size** case, we end up keeping data near our target lifespan of 72 hours + however long it took to hit the index size cap.

For the **time** case, we end up keeping data for 5 days, which is more or less ok, just slightly longer than desirable in the interest of keeping the total shard count down.

Do a global _"delete after N hours from index inception"_, or separate delete actions depending on which trigger caused a rollover seem like viable options to expedite delete in this scenario?

Thanks!

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
