### ISSUE TITLE
JAVA_HOME environment variable NOT working

### ISSUE THREAD

**Issue by cs-niraj-nandane** [elastic/elasticsearch#49068]
I have set `JAVA_HOME` to `/usr`. When i restart elasticsearch using `systemctl` i get following:
```
Job for elasticsearch.service failed because the control process exited with error code. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
```

If i set same value of JAVA_HOME in `/etc/sysconfig/elasticsearch`, it works.

Environment:
1. ES version 7.4.1
2. CentOS kernel 3.10.0-1062.1.2.el7.x86_64
3. Version : CentOS Linux release 7.7.1908 (Core)

**Comment by PhaedrusTheGreek** [comment]
Seems to be related to [this bit](https://github.com/elastic/elasticsearch/blob/master/distribution/src/bin/elasticsearch-env#L39-L55) where the `JAVA_HOME` env is assumed to be the parent directory of `/bin`, such as `/jre` suffix, e.g.:

```
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre/
```

Related: https://discuss.elastic.co/t/error-in-installing-elasticsearch-6-7-and-above/180980

**Comment by cs-niraj-nandane** [comment]
Can't we simply check 
```
if [ "X${JAVA_HOME}" != "X" ];then
   #java home is NOT set
fi
```

**Comment by rjernst** [comment]
This does not reproduce for me. The JAVA_HOME (or the environment in general) of the user running systemctl should have no effect on environment of systemd services. Can you please provide a detailed list of instructions to reproduce?

The steps I took were as follows:
```
centos-7:~$ /usr/bin/java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
centos-7:~$ sudo su -
Last login: Fri Nov 15 18:13:11 UTC 2019 on pts/0
centos-7:~$ rpm -i /elasticsearch/distribution/packages/rpm/build/distributions/elasticsearch-8.0.0-SNAPSHOT-x86_64.rpm
Creating elasticsearch group... OK
Creating elasticsearch user... OK
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Created elasticsearch keystore in /etc/elasticsearch
centos-7:~$ export JAVA_HOME=/usr
centos-7:~$ systemctl start elasticsearch.service
centos-7:~$ systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-11-15 18:29:28 UTC; 7s ago
     Docs: http://www.elastic.co
 Main PID: 29359 (java)
    Tasks: 71
   Memory: 1.2G
   CGroup: /system.slice/elasticsearch.service
           ├─29359 /usr/share/elasticsearch/jdk/bin/java -Des.networkaddress.cache.ttl=60 -Des.ne...
           └─29454 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controlle...

Nov 15 18:29:15 localhost.localdomain systemd[1]: Starting Elasticsearch...
Nov 15 18:29:15 localhost.localdomain elasticsearch[29359]: OpenJDK 64-Bit Server VM warning: Op....
Nov 15 18:29:28 localhost.localdomain systemd[1]: Started Elasticsearch.
```

**Comment by PhaedrusTheGreek** [comment]
For me it was caused by having `JAVA_HOME` set in `/etc/environment`, and simply installing the RPM.   I'm not sure how that variable got into that file in the first place.

**Comment by cs-niraj-nandane** [comment]
@rjernst If you look at the output, Elasticsearch still using `/usr/share/elasticsearch/jdk/bin/java ` instead of `/usr/bin/java`. When we export `JAVA_HOME=/usr`, it is expected that elasticsearch use `/usr/bin/java`

**Comment by rjernst** [comment]
Using the bundled jdk there is by design, as there is no JAVA_HOME that the service knows about. As I mentioned in my earlier comment, any environment variables existing for the session that is running `systemctl` are not propagated into the actual service. Changing the environment for a systemd service requires modifying `/etc/sysconfig/elasticsearch`, which according to your original description works.

**Comment by rjernst** [comment]
In the original failure, what does journalctl show for why elasticsearch failed to start? Sorry I should have asked that earlier. Based on your recent assertion I should delete the bundled jdk, I assume ES fails to start with a message like "no java home or bundled jdk found". If so, this is working as intended.

**Comment by cs-niraj-nandane** [comment]
Ok. If this is by design, then we must update the documentation. By reading documentation, which just says about `JAVA_HOME` environment variable in case of custom jdk, it creates confusion.

**Comment by rjernst** [comment]
Thanks @cs-niraj-nandane. I agree we should be more explicit about this and have opened #49565.
