### ISSUE TITLE
control the hits of scroll search

### ISSUE THREAD

**Issue by czhang223** [elastic/elasticsearch#49075]
**Describe the feature**:
Can I get the ability that when I execute scroll search, I can control the result has 'hits' attribute or not. Because it may take heavy bandwidth, or mem, or cpu time. If I'm looking for the 10000th~11000th record, I can only transfer the 'hits' that I want instead of the previous ones

**Comment by cbuescher** [comment]
Hi @czhang223, can you explain a bit more around this use case and what you are missing? If you are paginating that deeply, it seems to me that usually you would want to do something with the first pages somewhat earlier at some point.

**Comment by czhang223** [comment]
> Hi @czhang223, can you explain a bit more around this use case and what you are missing? If you are paginating that deeply, it seems to me that usually you would want to do something with the first pages somewhat earlier at some point.

@cbuescher   Yes, I'm paginating deeply. For example, **I need 10000th~11000th records, and I execute the command below.**
`
GET /kibana_sample_data_logs/_search?scroll=1m&size=1000
{
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ]
}
`
**And I get a '_scroll_id', then I execute the command below for 9 times.** So I can get the 10000~11000
`
GET /_search/scroll?scroll_id=DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAOCcWc1NSVU9INm5TcmlROWZ4SHMtTmFtdw==
`
I get something like that:
{
  "_scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAOCcWc1NSVU9INm5TcmlROWZ4SHMtTmFtdw==",
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 14074,
      "relation" : "eq"
    },
    "max_score" : null,
    **"hits"** : [
      { ... }
...
As you can see the "hits" attribute shows the _source data, but I only need to handle **the last time** that I execute the scroll command. **For the previous 9 times I don't want to transfer the "hits" data from server to client, It's totally a waste to bandwidth, mem, cpu.** So give me some power please. That's also in java client or any other clients, I hope only when you need the _source results, you transfer.

**Comment by czhang223** [comment]
@cbuescher Can I have your reply, please?

**Comment by cbuescher** [comment]
I've marked this for discussion with the team.

**Comment by jimczi** [comment]
@czhang223 can you explain your use case ? We understand that you need this feature but you didn't explain why so it's hard to say how useful this would be for users.

**Comment by dliappis** [comment]
No further feedback received. @czhang223  if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
