### ISSUE TITLE
can not build source code without suitable jdk

### ISSUE THREAD

**Issue by GreedyPirate** [elastic/elasticsearch#49078]
ES 7.2
jdk 11
command: ./gradlew assemble

**error message**
`the compiler java.home must be set to a JDK installation directory for Java 12 but is [/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home] corresponding to [11]`

then i looked for jdk12
but jdk12 has reached end of support. here is the link
https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html

then i installed jdk 13. The result was entirely predictable
`java.lang.IllegalArgumentException: Unsupported class file major version 57`

my question is how can i build the source code now?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
