### ISSUE TITLE
CSV processor

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#49113]
CVS is common source format, it would be nice if Elasticsearch supported a processor that offers explicit support to convert lines from a CSV document to an indexed document. 

Grok, Dissect, or KV can you get close but may be difficult to setup correctly and may not handle all of the cases that an explicit CSV processor may handle.

**Comment by dadoonet** [comment]
Would you like to get https://github.com/johtani/elasticsearch-ingest-csv in? cc @johtani

**Comment by martijnvg** [comment]
@dadoonet @johtani That looks like a great csv ingest processor. I'm only a bit concerned about the fact that the parser being used  [is not thread safe](https://github.com/johtani/elasticsearch-ingest-csv/blob/master/src/main/java/info/johtani/elasticsearch/plugin/ingest/csv/CsvProcessor.java#L59).

**Comment by johtani** [comment]
@martijnvg Yeah, unfortunately. https://github.com/johtani/elasticsearch-ingest-csv/issues/4#issuecomment-528193674
