### ISSUE TITLE
Ability to delete a mapping field or change type if no records are created

### ISSUE THREAD

**Issue by aimyth** [elastic/elasticsearch#49133]
Ability to delete a mapping field or change the type if no records are created.
According to this link, it's not possible to delete the mapping fields in an index.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-mapping.html

This is too limiting and even simple errors expect the entire index to be recreated and a new mapping done before the copy over of the data.

Let's assume you created a new field F1 on an existing index I1 with a type = nested. You then realized it was a copy paste error of different field and that you really wanted to create a type =keyword
Even though not a single record got created one is forced to delete the index and create the new field with this type.

This feature should be enhanced to check if there are any records have been inserted with this mapping field and if not present it should allow the mapping type change.

Similarly if one is able to find existing records and delete those records the feature should allow the same mapping to be changed.

**Comment by cpmoore** [comment]
+1 for this

**Comment by jimdowling** [comment]
+1 for this

**Comment by sachmuchsachin** [comment]
+1

**Comment by javanna** [comment]
I have a rather unpopular opinion on this: I don't think it is acceptable that we'd allow to remove or update a field conditionally, only if no docs were created. Such API would give the wrong perception that we do allow to update or remove fields from existing data, which is not the case. Also, I wonder what this saves: the real hassle is to have to reindex data to correct mapping mistakes (runtime fields may come to the rescue today!), but if no data was indexed, recreating the index with the right mappings does not look like a big overhead to me.

**Comment by dnhatn** [comment]
While this proposal might be useful, we discussed and decided not to implement it. You can find the reasons [here](https://github.com/elastic/elasticsearch/issues/68759#issuecomment-791552996).
