### ISSUE TITLE
Initialize the shards on time every day at 08:00

### ISSUE THREAD

**Issue by garywu520** [elastic/elasticsearch#49134]
Why is my elasticsearch cluster automatically initializing shards at 08:00 every day in Hong Kong? Can anyone tell me why, thank you!

Elasticsearch version: 6.5.4

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
