### ISSUE TITLE
scroll with script sorting return endless data

### ISSUE THREAD

**Issue by godlockin** [elastic/elasticsearch#49146]
ES 7.4.0
Centos 7

I would like to do a scroll operation for some data with the sorting of the abs value of the diff between publishTime VS. current system time.

In my opinion, the scroll might be:
1.  find out and make a snapshot for the query conditions
2.  cache them by the sort formula
3. return the data paged by size

but for this query, each time i query for scroll page by scroll id, es result has these 2 results:
1. data with missed up sequence
2. return the same data list

I think this issue should be caused by `System.currentTimeMillis()`? I don't know, maybe ?

```
{
    "query": {
"some filters"
},
    "sort":[
        {
            "_script":{
                "script":{
                    "inline":"Math.abs(doc['publishTime'] - System.currentTimeMillis())",
                    "lang":"painless"
                },
                "type":"number",
                "order":"desc"
            }
        }
    ]
}
```

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
