### ISSUE TITLE
[ML] Memory estimate endpoint returns value less than 1MB minimum

### ISSUE THREAD

**Issue by peteharverson** [elastic/elasticsearch#49168]
**Elasticsearch version**: 8.0.0-SNAPSHOT

The endpoint used to provide an estimate of the model memory limit for a data frame analytics job `/_ml/data_frame/analytics/_estimate_memory_usage` can return values which are less than what appears to be the allowed 1MB minimum threshold.

For example, created a transform off the cloudwatch data set, with 80 docs (grouped by `instance`, and 6 aggregations), and the estimate for an outlier job is returned by the endpoint as 60kb. Following error is seen in the UI when attempting to run a job with this 60KB MML:

![image](https://user-images.githubusercontent.com/7405507/68950888-f8543f80-07b4-11ea-9ede-4bb53f44ce8b.png)

**Comment by przemekwitek** [comment]
The fix PR is merged to both master and 7.x.

Closing the issue.
