### ISSUE TITLE
Could not load hsdis-amd64.so

### ISSUE THREAD

**Issue by ndanl** [elastic/elasticsearch#49178]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 7.3.2, Build: default/deb/1c1faf1/2019-09-06T14:40:30.409026Z, JVM: 12.0.2

**Plugins installed**: []

**JVM version** (`java -version`):

# /usr/share/elasticsearch/jdk/bin/java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux bill03 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Elasticsearch can not start, crashed with the following error:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fd5e4856948, pid=62249, tid=62343
#
# JRE version: OpenJDK Runtime Environment (12.0.2+10) (build 12.0.2+10)
# Java VM: OpenJDK 64-Bit Server VM (12.0.2+10, mixed mode, tiered, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# J 5337 c2 com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.findName([II)Ljava/lang/String; (198 bytes) @ 0x00007fd5e4856948 [0x00007fd5e4856840+0x0000000000000108]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /usr/share/elasticsearch/core.62249)
#
# An error report file with more information is saved as:
# /var/log/elasticsearch/hs_err_pid62249.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)

**Steps to reproduce**:

 1. start elasticsearch
 2. 
 3.

**Provide logs (if relevant)**:

https://gist.githubusercontent.com/ndanl/4a39c126712e6f25de20f5dc8722b521/raw/4cb3d2692a9c5bf3d500096b2764a33a5e33ef5b/gistfile1.txt

**Comment by ndanl** [comment]
added `-XX:UseSSE=2` and it was starting

**Comment by jasontedor** [comment]
This isn't a bug in Elasticsearch. It's a bug in the JVM. The JVM encountered a `SIGILL`. The instruction it tripped on is `phaddd xmm2,xmm2`. Your processor AMD Opteron(tm) Processor 6176 SE doesn't support that instruction, it's a bug that the JVM compiled down to that instruction (take it upstream, please). In particular, that's an SSE3 instruction which your CPU doesn't support, you can disable these by setting `-XX:UseSSE=2`.

**Comment by ndanl** [comment]
thank you

**Comment by twjs76** [comment]
Just as some extra information, I believe this to be the relevant JDK bug for this issue: https://bugs.openjdk.java.net/browse/JDK-8232106

**Comment by kerimovkhikmet** [comment]
> added `-XX:UseSSE=2` to jvc and it was able to start

So I had the same issue, and I am new in Java, and have question about fix. Where exactly should I add `-XX:UseSSE=2`, in which file?

**Comment by vmdarji85** [comment]
Hi All, I am getting similar error.  Can you please provide solution how can i resolve this error?


A fatal error has been detected by the Java Runtime Environment:

SIGFPE (0x8) at pc=0x0000000118e9ea48, pid=4481, tid=7683

JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.9+7) (build 11.0.9+7-LTS)
Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.9+7-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
Problematic frame:
j com.sun.tools.javac.comp.ConstFold.fold2(ILcom/sun/tools/javac/code/Type;Lcom/sun/tools/javac/code/Type;)Lcom/sun/tools/javac/code/Type;+877 jdk.compiler@11.0.9
No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

Compiled method (c1) 884 193 3 java.lang.System::getSecurityManager (4 bytes)
total in heap [0x0000000119455010,0x0000000119455338] = 808
relocation [0x0000000119455178,0x00000001194551a0] = 40
main code [0x00000001194551a0,0x0000000119455260] = 192
stub code [0x0000000119455260,0x00000001194552f0] = 144
metadata [0x00000001194552f0,0x00000001194552f8] = 8
scopes data [0x00000001194552f8,0x0000000119455300] = 8
scopes pcs [0x0000000119455300,0x0000000119455330] = 48
dependencies [0x0000000119455330,0x0000000119455338] = 8
Could not load hsdis-amd64.dylib; library not loadable; PrintAssembly is disabled

**Comment by JMBero** [comment]
Thanks @kerimovkhikmet this just saved me!

In case someone else stumbles across this - for the location to enter that Java option:  In my case elasticsearch is using sysconfig file here: (Debian)

 /etc/default/elasticsearch

I modified this line and uncommented:

# Additional Java OPTS
ES_JAVA_OPTS="-XX:UseSSE=2"
