### ISSUE TITLE
Enable building in parallel by default 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#49181]
With Gradle 6 we have a way to control the amount of paralelism so we can turn it on by default. 
We should upgrade to this version and make use of that we make use of that feature.

**Comment by mark-vieira** [comment]
I think it's time to pull the trigger on this. Folks are running local builds w/o parallel enabled and that's just crazy.

@jasontedor looking through Gradle Enterprise it looks like you've been using `--parallel`. Any issues concerns you've encountered?

@rjernst Looking at your last few builds on Gradle Enterprise you are **not** using `--parallel`. Why the @#$* not?

**Comment by jasontedor** [comment]
Creepy. I use it 100% of the time. If I forget, I cancel the running task and start again, because it's always a better experience to run with `--parallel`.

**Comment by rjernst** [comment]
I'm all for it to be enabled by default. I'm simply too lazy to add more flags to my command. Most of my recent builds are either a single test repro line, or running distro tests, so while I haven't had an immense need, it probably would have sped up my commands by a bit in the beginning to build the distros.

**Comment by williamrandolph** [comment]
👍 for enabling by default; it's a huge time saver.

**Comment by mark-vieira** [comment]
Ok. I'm going to add some verbage to our team docs on configuring parallelism for folks that might have environmental issues with using default worker configurations. Then I'll throw the switch.
