### ISSUE TITLE
Reindex from _source by document ID or Query

### ISSUE THREAD

**Issue by apatrida** [elastic/elasticsearch#492]
Be able to ask the system to reindex from the saved JSON by document ID or query.  This is useful once we have ES style plugins for manipulating documents that might later change and therefore cause you to want to reindex some set of documents.

#490 and #491 would let you query by a set of documents indexed before the required change.

If you are going to store the JSON, you can take advantage of that by reindex requests.

This might also allow the system to handle schema changes in the future more automatically by reindexing to the new analyzer over time in batch.

**Comment by eskibars** [comment]
I'm closing this in favor of the combination of #15201 / #2230 / #15125 where we've made some significant progress

**Comment by apatrida** [comment]
Great, I've been waiting a bit for this, glad to see it coming along!  Nice work, I read the log of discussions in #15125, very nice.

**Comment by clintongormley** [comment]
@apatrida Just a bit :) Issue #492!
