### ISSUE TITLE
Stats around elasticsearch percolator queries

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#49224]
**Stats around elasticsearch percolator queries**

**7.x**

**Plugins installed**: []

**1.8**

**Ubuntu**

After the unification of percolators as searches, all the metrics around percolators that were there in 1.x/2.x are gone. It kind of makes it difficult to figure out what's going on in percolation

Searches and percolations are very different use cases in my opinion & sometimes it's hard to tell why CPU spikes happened on our percolation server. They mostly depend on the document coming in and based on the fields ES deciding potential candidates

As a production deployment, we need metrics like how many percolators ES is trying for a document, can be a percolate_total/percolate_current metric at an index level or in the response some field telling us how many potential percolators ES tried for this document and how many actually matched. The latter can be found using the hits.total.value so that's not an issue. We usually are blind as to why our servers spiked

**Comment by romseygeek** [comment]
You should be able to get this information using a combination of the slow log to identify documents that take a long time to percolate, and then the profile API to get more information about what's taking the time - specifically the `match_count` value for `PercolateQuery` will tell you how many queries are candidates for checking for that document.

**Comment by javanna** [comment]
We have no concrete plans to work on this issue. Closing.
