### ISSUE TITLE
index mapping needs to show date format 

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#49222]
index mapping lacks date format when the format is the default one.
I think that the format should be returned regardless of that.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

```
DELETE my*

PUT my_index1
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
      }
    }
  }
}


PUT my_index2
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "strict_date_optional_time||epoch_millis"
      }
    }
  }
}

GET my_index1/_mapping
GET my_index2/_mapping
```

```
# result from GET my_index1/_mapping
{
  "my_index1" : {
    "mappings" : {
      "properties" : {
        "date" : {
          "type" : "date",
          "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    }
  }
}

# result from GET my_index2/_mapping

{
  "my_index2" : {
    "mappings" : {
      "properties" : {
        "date" : {
          "type" : "date"
        }
      }
    }
  }
}
```

**Comment by pgomulka** [comment]
hey @TomonoriSoejima this is interesting idea. We discussed this on 27th Nov core-infra sync meeting.
This should be already possible. You need to specify which field you want to see the default though.
```
GET my_index2/_mapping/field/date?include_defaults=true
```

We want to avoid showing all the defaults from `_mapping` out of the box. This would make mapping very complex and hard to digest.
Let me know what you think

**Comment by TomonoriSoejima** [comment]
Just tried it and it does return the format.
I suppose the endpoint was intentionally not described in https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html

**Comment by rjernst** [comment]
@TomonoriSoejima The field mapping api is described in a separate doc:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-field-mapping.html

**Comment by TomonoriSoejima** [comment]
@rjernst , Right. I am so bad at googling..
