### ISSUE TITLE
Master doesn't  delete the connection from `ConnectionManager.connectedNodes` with the node failing to join the cluster because of ValidateJoinRequest failure

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#49244]
ES_VERSION: 7.3.1
**Description of the problem including expected versus actual behavior:**
When the node want to join the cluster, the process is as below:
1. The node will send join request to master.
2. The master will connect to the node, including establishing five types of connections, and putting the five types of connections into `ConnectionManager.connectedNodes`.
3. The master calls function `sendValidateJoinRequest` to send `internal:cluster/coordination/join/validate` to the node.
4. The node receives the request and checks `clusterUUID` and `clusterUUIDCommitted`. check code: https://github.com/elastic/elasticsearch/blob/6681cc0df5029daf21584bc4406fa1616943b3b0/server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java#L135

If the node check that `clusterUUID` and `clusterUUIDCommitted` are not equal, it will throw exception and fail to join the cluster, but the master has established the connections with the node, if we don't release the connections, it will always exists in `ConnectionManager.connectedNodes` of master. In fact, we do not initiative release those connections in master.

The node  will establish five connections with other master-attribute nodes  in cluster before joining the cluster successfully, if the node fails to join the cluster, those connections will always exists, It may also be a problem.

If we should initiative release connections from `ConnectionManager.connectedNodes` in master when the node fails to join the cluster?  If the node should not  establish connections with other master-attribute nodes in cluster before the node joins to cluster successfully?

**Comment by DaveCTurner** [comment]
I think this is the desired behaviour. Join validation failures are not fatal and the correct response is to retry until successful. The alternative is that the master closes these connections and then reopens them the next time the node attempts to join, which seems wasteful.

Note that it's not true that these connections will "always exist": they are cleaned up when the joining node shuts down.
