### ISSUE TITLE
Rewrite queries on unmapped fields as MatchNoDocsQueryBuilder

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#49254]
It's probably more easily explained with an example: `TermQueryBuilber#doToQuery` looks like this today

```java
    protected Query doToQuery(QueryShardContext context) throws IOException {
        Query query = null;
        MappedFieldType mapper = context.fieldMapper(this.fieldName);
        if (mapper != null) {
            query = mapper.termQuery(this.value, context);
        }
        if (query == null) {
            query = new TermQuery(new Term(this.fieldName, BytesRefs.toBytesRef(this.value)));
        }
        return query;
    }
```

So if the field is unmapped, we create a TermQuery on a field that doesn't exist, which is no different from returning a MatchNoDocsQuery.

It's becoming more and more common that multiple indices that have different mappings get queried together, e.g. as part of an alias or an index pattern, so a more efficient way to handle these cases would be to _rewrite_ to a `MatchNoDocsQueryBuilder` in the `rewrite()` method. This would help figure out that the shard cannot possibly match in the `can_match` phase and skip the `query` phase completely.

**Comment by ejmiers** [comment]
Could I jump on this issue? Fairly new to elasticsearch.

**Comment by jpountz** [comment]
@ejmiers Sure, can you only focus on TermQueryBuilder for the first iteration of your PR, add me as a reviewer, and once I'm good with the approach for TermQueryBuilder we will generalize to other queries that need the same change like TermsQueryBuilder, MatchQueryBuilder and MultiMatchQueryBuilder?

**Comment by ejmiers** [comment]
Hi @jpountz, I am having difficulty locating the rewrite() function referenced above. Could you point me in the right direction?

**Comment by jpountz** [comment]
Apologies @ejmiers I had to work on this as part of another change, so this issue should soon no longer be relevant.

**Comment by singhprincejeet** [comment]
@jpountz Should this issue be closed then?
