### ISSUE TITLE
Memory leak due to DocumentSubsetBitsetCache.keysByIndex

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#49261]
While reviewing `DocumentSubsetBitsetCache`, I noticed that it might leak memory since size-based evictions don't trigger evictions in `DocumentSubsetBitsetCache.keysByIndex`. So `keysByIndex` might keep holding a reference to cache keys long after they have been removed from the cache.

**Comment by jpountz** [comment]
@jkakavas Did you close the wrong issue?

**Comment by jkakavas** [comment]
Yeap, wrong resolves link :/

**Comment by olegbonar** [comment]
Hi @jpountz! If I understand you correctly we can try using a `RemovalListener` in order to remove the leaking entry from `keysByIndex` too. What do you think?

**Comment by jpountz** [comment]
Yes this is the idea. The tricky part is to make sure there are no race conditions in case a query is removed from the cache and shortly added back afterwards.

**Comment by olegbonar** [comment]
@jpountz, I'm not a concurrency expert but should we make adding to the cache and adding to the hashmap a separate atomic operation? Aren't they atomic now?

**Comment by tvernum** [comment]
@olegbonar Have you made any progress on this? I'd like to fix this bug in the next couple of weeks, but I'm happy to leave it for you if you've got something underway.

**Comment by olegbonar** [comment]
@tvernum, I haven't. Please take it.
