### ISSUE TITLE
Add default value in documentation to remove settings index.routing.allocation

### ISSUE THREAD

**Issue by AlexandreRoux** [elastic/elasticsearch#49288]
Hello Team. 

I think that it will be great to add in your documentation [elasticsearch/blob/6.7/docs/reference/index-modules/allocation/filtering.asciidoc](https://github.com/elastic/elasticsearch/blob/6.7/docs/reference/index-modules/allocation/filtering.asciidoc) the default value to remove a settings. 

For example specify `null` for `index.routing.allocation.require._name`. Please correct me if I misunderstood something here.

**Comment by jasontedor** [comment]
Our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/indices-update-settings.html#reset-index-setting) already have indication that `null` is the way to remove the value of *any* index setting. Given this, I don't think we should cover them on a case-by-case basis.

**Comment by AlexandreRoux** [comment]
@jasontedor Thx for pinned point this part of the docs. Make sense so now.

**Comment by jasontedor** [comment]
Glad to hear, you’re welcome.
