### ISSUE TITLE
Interval Query should work with Annotated Text Plugin

### ISSUE THREAD

**Issue by bijanfahimi** [elastic/elasticsearch#49289]
### Feature Request

**elasticsearch version** >= 7.4.2

In our use case we would like use the interval query on text fields of type annotated text. The interval query, however, throws an exception:
`Can only use interval queries on text fields - not on [text] which is of type [annotated_text]"`
The exception is thrown here `https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java#L395`.

**Interval query:** https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-intervals-query.html.
**Annotated Text Plugin:** https://www.elastic.co/blog/search-for-things-not-strings-with-the-annotated-text-plugin

**Comment by cbuescher** [comment]
Maybe @markharwood can comment on whether this field type restriction is there on purpose of if this can and should eventually be supported.
