### ISSUE TITLE
SQL: multiply operation between INTERVALs and NULL is not possible

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49297]
`SELECT NULL * INTERVAL 1 DAY` results in:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "verification_exception",
        "reason" : "Found 1 problem(s)\nline 1:8: [*] has arguments with incompatible types [NULL] and [INTERVAL_DAY]"
      }
    ],
    "type" : "verification_exception",
    "reason" : "Found 1 problem(s)\nline 1:8: [*] has arguments with incompatible types [NULL] and [INTERVAL_DAY]"
  },
  "status" : 400
}
```

**Comment by matriv** [comment]
@astefan: Hint: `Mul`'s `resolveType()` uses DataType functions and not the TypeResolutions ones which allow the NULL data type. We should check everywhere for this and fixit.

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/ce727615c08cf5ae422feb77f69ea24fb53cd9d1
7.x (7.6.0): https://github.com/astefan/elasticsearch/commit/e2982b2110b047ae3ede46eb2621d7bfb68a70b3
7.5 (7.5.1): https://github.com/elastic/elasticsearch/commit/b99667176f3f6edafc31dccb0e5ef506e4657791
