### ISSUE TITLE
[CI] Build fails on 7.4 branch

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#49293]
Since November 16th, many builds fail on the 7.4 branch with a "no space left on device" error. 

I'm not sure if this is just an Infra issue or if this is related to https://github.com/elastic/elasticsearch/pull/49130, hence I'm reported the issue here to raise @elastic/es-core-infra team awareness.

https://gradle-enterprise.elastic.co/s/yungwyqx2um7i
https://gradle-enterprise.elastic.co/s/b7rerbunbqksi
https://gradle-enterprise.elastic.co/s/jozsruqgrgoem
https://gradle-enterprise.elastic.co/s/xq63ebd7rscvs
https://gradle-enterprise.elastic.co/s/y7237xpny4xyu

**Comment by mark-vieira** [comment]
Looks like the backports for #49130 didn't get properly applied to 7.5 and 7.4. I've fixed this with 3d1f2a3087225af69500c4a110a6c28b31e37ce1 and f1e4fcda85817fe8ba773b35e26b76143ff738d7.

**Comment by mark-vieira** [comment]
The EAR failures still need to be addressed. I'll open a PR in the elastic/infra repo to increase the encrypted volume size.

**Comment by mark-vieira** [comment]
FYI, I'm keeping this open right now to confirm that this sorts out the EAR builds as well, and that bumping the size of the encrypted volume we use isn't still necessary. Given the 7.5 and master builds are passing I suspect not but I want to see some green builds before closing this.

**Comment by mark-vieira** [comment]
Removing the `>test-failure` label here since this is a generic build issue and not related to test execution.

**Comment by markharwood** [comment]
[Another case](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.4+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=general-purpose/166/console) of 7.4 with no space today

**Comment by mark-vieira** [comment]
Thanks @markharwood. I've merged https://github.com/elastic/elasticsearch/pull/49456 to address the remaining issues in `7.4`.

**Comment by mark-vieira** [comment]
Looks like the 7.4 builds are passing again. 

https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.4/job/elastic+elasticsearch+7.4+periodic/219/
