### ISSUE TITLE
geo_shape query with circle does not work for legacy geo_shape field

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#49296]
We currently do not support circle queries for geo_shape fields using BKD_backed geo_shape but it should be possible to do it using legacy indexing strategy.

This is currently broken. They issue seems to be in the [serialisation mechanism](https://github.com/elastic/elasticsearch/blob/98c850c08bbed147eee4e8fe3b96e71957c2d4da/server/src/main/java/org/elasticsearch/common/geo/GeometryIO.java) which throws an error for circle geometries.

**Comment by imotov** [comment]
I started to look into it, and implemented serialization, but then I realized that we didn't support circles in queries for a very long time (if ever) I went all the way back to v2.4.6 and we didn't support circle queries even back then. So, it's not just a serialization issue. Considering that we are trying to deprecate and remove the legacy index strategy, I am not totally sure it's worth the effort to add it there. I think we should discuss it before I sink more time into it.

**Comment by iverase** [comment]
Circles queries are supported for LegacyGeoShape (aka prefix trees). I think this needs to be fixed.

**Comment by imotov** [comment]
It doesn't look like there is support on the [elasticsearch side](https://github.com/elastic/elasticsearch/blob/13a8835e5a8615aeb8304b48fd9e543a83361e13/server/src/main/java/org/elasticsearch/index/query/LegacyGeoShapeQueryProcessor.java#L126).

**Comment by iverase** [comment]
https://discuss.elastic.co/t/circle-geo-shape-query-not-supported-in-es7-4-2/208404/2

**Comment by imotov** [comment]
@iverase were you able to reproduce it?

**Comment by imotov** [comment]
Just to clarify. I was looking at the wrong place. We did indeed support it, but I lost it during refactoring in 7.4.0. I opened PR that restores this functionality.
