### ISSUE TITLE
[CI] TrainedModelIT and RunDataFrameAnalyticsIT fail on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#49305]
Both tests RunDataFrameAnalyticsIT and TrainedModelIT failed today on `7.x`:
https://gradle-enterprise.elastic.co/s/qj7swzyjlnyje
https://gradle-enterprise.elastic.co/s/2iyfuafv32tao

I'm filling a single issue as both tests failed together twice, but maybe there are unrelated and deserve separate issues.

`RunDataFrameAnalyticsIT` test timed out:
```
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testOutlierDetectionStopAndRestart FAILED
--
java.lang.Exception: Test abandoned because suite timeout was reached.
```
And `TrainedModelIT.testGetTrainedModels` and `TrainedModelIT.testDeleteTrainedModels` failed with a different errors:

```
expected:<0> but was:<3>
--
at __randomizedtesting.SeedInfo.seed([23B4ACF49009EAD2:8118EE7A7F4FCF5C]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$3(ESRestTestCase.java:387)
```

The failures do not reproduce locally with:
<details>
Execution failed for task ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner'.

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CL \
  -Dtests.timezone=Hongkong \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CL \
  -Dtests.timezone=Hongkong \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CL \
  -Dtests.timezone=Hongkong \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.TrainedModelIT.testGetTrainedModels" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Cuba \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.TrainedModelIT.testDeleteTrainedModels" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Cuba \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.TrainedModelIT.testGetTrainedModels" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Cuba \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.TrainedModelIT.testDeleteTrainedModels" \
  -Dtests.seed=23B4ACF49009EAD2 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Cuba \
  -Dcompiler.java=12 \
  -Druntime.java=8
</details>

**Comment by original-brownbear** [comment]
Looks like this is similar to https://gradle-enterprise.elastic.co/s/bgubdjegnkvgg/tests/zcquf3hc3eoda-q3ovxh6ju37ic

**Comment by mark-vieira** [comment]
I've seen the error @original-brownbear posted happen a few times this week but all on `7.5` so I've just muted that test in that branch since we are going to sunset it soon with cdbe6a71dc78455fc10e7cf535034d3504df60c8.

**Comment by droberts195** [comment]
This hasn't happened recently.  It sounds like it's a bug in 7.5 that's been fixed in more recent versions.  Since there will be no more changes to 7.5 there is not point keeping this issue open.
