### ISSUE TITLE
Build failure for elasticsearch 7.2 on PPC64LE

### ISSUE THREAD

**Issue by sarveshtamba** [elastic/elasticsearch#49353]
I am trying to build elasticsearch version 7.2 on PPC64LE inside a `registry.access.redhat.com/ubi7/ubi-minimal` based container.

Initially I ran into `error: unmappable character (0xE0) for encoding US-ASCII` errors, which were resolved by exporting `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` .

However now I am facing the following error as below:-
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE
> Task :buildSrc:compileMinimumRuntimeGroovy UP-TO-DATE
> Task :buildSrc:processMinimumRuntimeResources NO-SOURCE
> Task :buildSrc:minimumRuntimeClasses UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy UP-TO-DATE
> Task :buildSrc:processTestResources UP-TO-DATE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test SKIPPED
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.4.1
  OS Info               : Linux 3.10.0-1062.el7.ppc64le (ppc64le)
  JDK Version           : 12 (AdoptOpenJDK 12.0.2 [OpenJDK 64-Bit Server VM 12.0.2+10])
  JAVA_HOME             : /usr/local/jdk-12.0.2+10
  Random Testing Seed   : E715761E1F58416E
=======================================

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/root/elasticsearch/benchmarks/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':benchmarks'.
> Must specify license and notice file for project :benchmarks

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```
Am I missing anything here?

**Comment by cbuescher** [comment]
Hi @sarveshtamba! Unfortunately compiling for PPC64LE isn't [something we support](https://www.elastic.co/support/matrix). You might get help in the support forums over at https://discuss.elastic.co though, so I'd like to encourage you to ask this question in the forum instead. Many thanks.

**Comment by haomi123** [comment]
> I am trying to build elasticsearch version 7.2 on PPC64LE inside a `registry.access.redhat.com/ubi7/ubi-minimal` based container.
> 
> Initially I ran into `error: unmappable character (0xE0) for encoding US-ASCII` errors, which were resolved by exporting `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` .
> 
> However now I am facing the following error as below:-
> 
> ```
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> Starting a Gradle Daemon (subsequent builds will be faster)
> > Task :buildSrc:compileMinimumRuntimeJava NO-SOURCE
> > Task :buildSrc:compileMinimumRuntimeGroovy UP-TO-DATE
> > Task :buildSrc:processMinimumRuntimeResources NO-SOURCE
> > Task :buildSrc:minimumRuntimeClasses UP-TO-DATE
> > Task :buildSrc:compileJava UP-TO-DATE
> > Task :buildSrc:compileGroovy UP-TO-DATE
> > Task :buildSrc:pluginDescriptors UP-TO-DATE
> > Task :buildSrc:processResources UP-TO-DATE
> > Task :buildSrc:classes UP-TO-DATE
> > Task :buildSrc:jar UP-TO-DATE
> > Task :buildSrc:assemble UP-TO-DATE
> > Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> > Task :buildSrc:compileTestJava UP-TO-DATE
> > Task :buildSrc:compileTestGroovy UP-TO-DATE
> > Task :buildSrc:processTestResources UP-TO-DATE
> > Task :buildSrc:testClasses UP-TO-DATE
> > Task :buildSrc:test SKIPPED
> > Task :buildSrc:validateTaskProperties UP-TO-DATE
> > Task :buildSrc:check UP-TO-DATE
> > Task :buildSrc:build UP-TO-DATE
> 
> > Configure project :benchmarks
> =======================================
> Elasticsearch Build Hamster says Hello!
>   Gradle Version        : 5.4.1
>   OS Info               : Linux 3.10.0-1062.el7.ppc64le (ppc64le)
>   JDK Version           : 12 (AdoptOpenJDK 12.0.2 [OpenJDK 64-Bit Server VM 12.0.2+10])
>   JAVA_HOME             : /usr/local/jdk-12.0.2+10
>   Random Testing Seed   : E715761E1F58416E
> =======================================
> 
> FAILURE: Build completed with 2 failures.
> 
> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/root/elasticsearch/benchmarks/build.gradle' line: 20
> 
> * What went wrong:
> A problem occurred evaluating project ':benchmarks'.
> > Failed to apply plugin [id 'elasticsearch.build']
>    > Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':benchmarks'.
> > Must specify license and notice file for project :benchmarks
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> ```
> 
> Am I missing anything here?

May I ask whether you have solved the problem？I had the same problem.

**Comment by sarveshtamba** [comment]
@haomi you can check here - https://github.com/ppc64le/build-scripts/tree/master/e/elasticsearch

**Comment by sarveshtamba** [comment]
@haomi123 you can check here - https://github.com/ppc64le/build-scripts/tree/master/e/elasticsearch
