### ISSUE TITLE
Test-forward is picking up a wrong JDK version

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#49378]
when testing 7.x branch against master (test-forward) build is failing because JDK1.8 is no longer supported on master.
PR where it fails https://github.com/elastic/elasticsearch/pull/48703
jenkins build https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+master+fwc/12/
build scan https://gradle-enterprise.elastic.co/s/4t3vmbqqoe3ei

**Comment by mark-vieira** [comment]
This was a result of us not properly setting `JAVA_HOME` after checking out the FWC branch. This has been sorted out in https://github.com/elastic/infra/pull/16611.
