### ISSUE TITLE
phrase_prefix search issue with single character

### ISSUE THREAD

**Issue by meta-dipanshu-sharma** [elastic/elasticsearch#49372]
I have a data like 'Dipanshu S',  'Mohit Sharma' and 'Mohit Shakya' in my database and when i do a ES search query like :- 

"multi_match":  {
                          "query": "Mohit S",
                          "type": "phrase_prefix",
                          "fields": [  "name"  ]
                     }

It gives me correct result 'Mohit Sharma' and 'Mohit Shakya' as it returns results with exact matching of first term 'Mohit' and returning all words starting with 'S' but when i do same search with "query":"Dipanshu S" then  it doesn't return any results because the word 'S' is not a word starting with character 'S' but its a complete word in itself in the data 'Dipanshu S'.

So how to manipulate query to get results with single character words?

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/c/elasticsearch). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the forums
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
