### ISSUE TITLE
SQL: implicit CASTing between DATEs and DATETIMEs

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49379]
We have a hard CASTing rule for DATEs and DATETIMEs, ie `CAST(CAST(date AS STRING) AS DATE)` will fail with `SqlIllegalArgumentException[cannot cast [2004-06-04T00:00:00.000Z] to [date]: Text '2004-06-04T00:00:00.000Z' could not be parsed, unparsed text found at index 10]` because a date and a time is not actually a date.
Should we loosen this hard rule for DATEs and DATETIMEs? Should we do implicit CASTing?

**Comment by matriv** [comment]
`master` : 5863b27500d5e7f6cdd8c6c62b09b84e53ca724a
`7.x` : 6b600855a96c23b4591da75edd84f7078db263bd
