### ISSUE TITLE
SQL: GROUPing BY YEAR function applied on a CASTed AS DATE field results in NULL values

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49386]
`SELECT YEAR(CAST(birth_date AS DATE)) FROM test_emp GROUP BY 1` results in 

```
YEAR(CAST(birth_date AS DATE))
------------------------------------
null
```

**Comment by matriv** [comment]
`master` : 93c37abc943d00d3a14ba08435d118a6d48874c7
`7.x` : b0cb7bf229e3d386d08013c910888c67fe3c2ee4
`7.5` : e56a463b61a8718258b2688f43da5adfa050f24c

**Comment by matriv** [comment]
Backported to previous branches where the YEAR() resulted in fixed interval and not a calendar interval:
`7.4` : e54d7d557939e895226894781f386dbb97c7d8e7
`6.8` : 90378a9ff50f9d6026bfe36bdb11514063f8dd63
