### ISSUE TITLE
Elasticsearch does not indicate retryability when flood stage is exceeded

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#49393]
Today if a node exceeds the disk flood stage watermark, the disk threshold monitor will apply a special read-only index block to any indices that have a shard allocated to the node that exceeded the watermark. This block carries with it a forbidden status code so that if an attempt is made to index into such an index, the client receives a HTTP 403 status code.

Clients assume that a 403 status code is not retryable and they drop data.

This situation is retryable though, as once the disk threshold monitor observes the free disk space go above the appropriate threshold, the index block is automatically removed.

Rather than expecting our clients to all account for this situation (by inspecting the specifics of the exception that led to the 403 status code), we should indicate retryability by using HTTP status code 429. While 429 is often translated as "too many requests", the [HTTP specification is liberal](https://tools.ietf.org/html/rfc6585#section-4) about what this means:

>Note that this specification does not define how the origin server identifies the user, nor how it counts requests.  For example, an origin server that is limiting request rates can do so based upon counts of requests on a per-resource basis, across the entire server, or even among a set of servers.

By making this change, all of our clients can start retrying when faced with an index that was marked read-only due to a flood stage watermark exceeded event.

Similarly, the status codes of other cluster blocks should be reexamined in this context.

**Comment by gaobinlong** [comment]
Hi @jasontedor , I'm intersted in this issue. Should we return 429 status code if the cluster block is set manually rather than set automaticly when the flood stage is exceeded?

**Comment by jasontedor** [comment]
@gaobinlong I think it's fine to treat them the same. I wish we had an easy way to distinguish when it's automatically set versus when it's not, be we don't really so let's proceed to treat them as the same.

**Comment by gaobinlong** [comment]
@jasontedor ok, I got it.

**Comment by gaobinlong** [comment]
Hi @jasontedor , I hava made a PR for this issue, can you help to review the code change?

**Comment by zez3** [comment]
https://github.com/elastic/elasticsearch/pull/50166

This PR valid from 7.7 has been brought to my attention

**Comment by DaveCTurner** [comment]
Closed by #50166.
