### ISSUE TITLE
Elasticsearch 6.8.5 release archive ownership

### ISSUE THREAD

**Issue by csandanov** [elastic/elasticsearch#49417]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.5

**OS version** (`uname -a` if on a Unix-like system): Alpine 3.10.3

**Description of the problem including expected versus actual behavior**:

I'm maintaining elasticsearch docker images where I download the archive (https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.5.tar.gz) and extract it via `tar` with `--strip-components` flag. I've noticed that since 6.8.5 release the flag `--strip-components` no longer works. However 7.4.2 works just fine. The only difference I can see is the ownership of the files in the archive which for 6.8.5 is `631:503` (unlike 7.4.2 with `root:root`). I'm not entirely sure though that's the main reason because it still doesn't work with flags `--no-same-owner`, `--user` or even when I add the user/groups with these IDs. That's why I've also [posted this issue on serverfault](https://serverfault.com/questions/992681/why-tar-flag-strip-components-ignored-sometimes)

**Steps to reproduce**:

```shell
$ docker run --rm -ti alpine:3.10.3 sh

### from container
$ apk add --update tar
$ wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.5.tar.gz
$ mkdir elastic
$ tar zxvf elasticsearch-6.8.5.tar.gz --strip-components=1 -C elastic
$ ls -la elastic
```
You'll see directory elastic/elasticsearch-6.8.5 that shouldn't exist

**Comment by Conky5** [comment]
Hi @csandanov, this is happening because there is a leading `./` on the paths within the archive due to a change in our release pipeline for the 6.8.5 artifact. This is viewable in your example with:

```
/ # tar tvf elasticsearch-6.8.5.tar.gz --numeric-owner | head -n 2
drwxr-xr-x 631/503           0 2019-11-14 14:20 ./
drwxr-xr-x 631/503           0 2019-11-13 20:07 ./elasticsearch-6.8.5/
```

To extract the 6.8.5 artifact to the location you want you can use `--strip-components=2`:

```
/ # tar zxvf elasticsearch-6.8.5.tar.gz --strip-components=2 -C elastic
```

Future releases will switch back to not including `./`, so it might be good to prepare the script to handle both cases, something like this should do the trick:
```
$ if tar tf elasticsearch-6.8.5.tar.gz | head -n 1 | grep -q '^./$'; then STRIP_COMPONENTS_COUNT=2; else STRIP_COMPONENTS_COUNT=1; fi
$ tar zxvf elasticsearch-6.8.5.tar.gz --strip-components=$STRIP_COMPONENTS_COUNT -C elastic
```

**Comment by csandanov** [comment]
Thank you, that helped!
