### ISSUE TITLE
Invalid JSON request bodies result in 500 response

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#49428]
**Elasticsearch version:** v7.3.1
**OS version:** Linux 4.4.0-1098-aws
**JVM**: OpenJDK 1.8.0_201 / 25.201-b09

**Current behaviour:**

If I execute a search with an invalid JSON request body, e.g. missing a double-quote:

```
GET blogs/_search
{"query":{"match":{"title":{"query":"open source software,"minimum_should_match":2}}}}
```

Then ES rejects the query with a 500, which indicates a server-side problem.

**Expected behaviour:**

The server should respond with "400 Bad Request", to indicate a client problem.

**Impact:**

The 500 is problematic because it indicates to clients that they can retry the request, but of course it will always fail. See also #48308, which concerns the Bulk API.

**Comment by Mpdreamz** [comment]
Clients don't retry 500

See: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/fail-over.html

And https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/client/test/src/main/java/org/elasticsearch/client/RestClientTestUtil.java#L39

Great fix though thanks @pugnascotia !

**Comment by jasontedor** [comment]
Some clients do, for example, Beats: https://github.com/elastic/beats/blob/ee5a4e73a98fbf63307cd5d7f6cfcf196bb15bd3/libbeat/outputs/elasticsearch/client.go#L522-L524
