### ISSUE TITLE
Missing dependencies for log4j's JSONLayout

### ISSUE THREAD

**Issue by onimisionipe** [elastic/elasticsearch#49421]
Hello

Currently elasticsearch is not packaged with jackson-databind and jackson-annotations. This is needed to use structured logging. For example when using JSONLayout, log4j fails because of these dependencies.
Can we add this to the list of dependencies? or better suggestion will work well for us. 

We are currently tracking this here: https://phabricator.wikimedia.org/T225125
We need this to move forward on our migration to structured logging.

**Comment by jasontedor** [comment]
Can you clarify the version you’re using? Elasticsearch since 7.0 provides JSON logging capabilities out of the box.

**Comment by onimisionipe** [comment]
We are currently using elasticsearch 6.5.4.

**Comment by onimisionipe** [comment]
I guess we have to wait till we upgrade to 7.
Thank you!
