### ISSUE TITLE
Support for ignore_throttled and/or preFilterShardSize in watches

### ISSUE THREAD

**Issue by jsermer** [elastic/elasticsearch#49453]
Similar to https://github.com/elastic/elasticsearch/issues/39377 but it would be nice to have the ability for watches to indicate whether they should search within frozen indices or not.  Currently, watches are configured to always search frozen indices (ignore_throttled=false) and the preFilterShardSize defaults to 128, so if the number of primary shards for a watch's target indices is less than 128, it will always incur a delay while the nodes load the frozen indices into memory (sometimes leading to a timeout - which can be adjusted using the timeout parameter within the watch).

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
