### ISSUE TITLE
`null_value` should not be analyzed

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#4945]
When setting a `null_value` on an analyzed field, that value should not be analyzed before indexing:

    curl -XPUT "http://localhost:9200/my_index " -d'
    {
       "mappings": {
          "posts": {
             "properties": {
                "tags": {
                   "type": "string",
                   "null_value": "NULL"
                }
             }
          }
       }
    }'

    curl -XPUT "http://localhost:9200/my_index/posts/1" -d'
    { "tags": null }'

Sorting shows that the `null_value` has been analyzed:

    curl -XGET "http://localhost:9200/_search?sort=tags"

    {
       "took": 3,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 1,
          "max_score": null,
          "hits": [
             {
                "_index": "my_index",
                "_type": "posts",
                "_id": "1",
                "_score": null,
                "_source": {
                   "tags": null
                },
                "sort": [
                   "null"
                ]
             }
          ]
       }
    }

And using the `missing` filter with `null_value` set to `true` fails to work because it is looking for `NULL` instead of `null`:

    GET /_search?sort=tags
    {
       "query": {
          "filtered": {
             "filter": {
                "missing": {
                   "field": "tags",
                   "null_value": true
                }
             }
          }
       }
    }

**Comment by rjernst** [comment]
Not analyzing the null value would mean you couldn't find documents with the null value from anything *but* the `missing` filter.

I don't think this is a problem with null values, but simply with the missing filter.  When using `null_value: true` in `missing`, it should analyze the value before running the filter.

**Comment by clintongormley** [comment]
True, hadn't considered that. I was thinking more of the case where you want to be sure that the null value is a concrete value that couldn't possibly appear in real values, eg `NULL` when all the real values are lowercased.

**Comment by jpountz** [comment]
I see `null_value` as something that is quite specific to structured data. Not sure how much sense it makes on analyzed string fields?

**Comment by clintongormley** [comment]
@jpountz agreed - closing
