### ISSUE TITLE
Make KeystoreManagementTests work in the docker case

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#49469]
While I was working on #32691, we added some Docker packaging tests. Right now, some of the keystore tests are failing on the `distroTest.default-docker` task, e.g. `:qa:os:centos-6:distroTest.default-docker`.

Ideally, the keystore management tests can be flexible enough to run even in the docker case. If not, the tests should be fixed so that they don't run for that docker testing task.

Relates #32691

**Comment by pugnascotia** [comment]
@williamrandolph let me know if I can help here.

**Comment by williamrandolph** [comment]
@pugnascotia OK, I'm looping back around to this now.

Right now we have a `PackagingTestCase` class that all of the more specific test classes inherit from. Almost all of those classes either exclude Docker explicitly or select a specific packaging type other than Docker. The one exception? `DockerTests`, which extends `PackagingTestCase` but modifies the setup before each test by setting the `Shell` object to a new `DockerShell` and setting the `installation` object with `runContainer`.

If I want to make the `KeystoreManagementTest` class run correctly for Docker, it seems like I would have to push that Docker-specific `shell`/`installation` setup into the `PackagingTestCase` class. Is that something you tried doing while you were writing these test cases? Do you think there's any reason that approach wouldn't work in principle?

**Comment by pugnascotia** [comment]
I didn't try that approach, but it certainly sounds reasonable. If you run into any issues, let me know and we'll figure it out.

**Comment by williamrandolph** [comment]
Closed by #50610
