### ISSUE TITLE
`> test-mute` label doesn't trigger precommit checks

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#49480]
Instead it only seems to trigger es-docs tests. See 

https://github.com/elastic/elasticsearch/pull/49479
https://github.com/elastic/elasticsearch/pull/49476

Actually this seems to be going on for a while, i.e.

https://github.com/elastic/elasticsearch/pull/49364
https://github.com/elastic/elasticsearch/pull/48535

The last PR with this label that ran precommit as far as I can see is https://github.com/elastic/elasticsearch/pull/44159 on July 10.

**Comment by DaveCTurner** [comment]
Duplicates https://github.com/elastic/elasticsearch/issues/48505 I think.

**Comment by jkakavas** [comment]
:man_facepalming:  who would have though one needs to look for existing issues before opening one
