### ISSUE TITLE
Add wire serialization tests for internal index requests.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#49507]
Some internal request objects do not have good unit test coverage around wire serialization. In particular, the following test classes extend `ESTestCase`, but it would be better if they implemented `AbstractWireSerializingTestCase` to extensively test wire serialization:
- `PutMappingRequestTests`
- `PutIndexTemplateRequestTests`
- `CreateIndexRequestTests`

Note that the `testEqualsAndHashcode` cases will currently fail because these requests do not override `equals` and `hashCode`.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
