### ISSUE TITLE
Provide LogNormal support in script score predefined functions

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#49516]
**Describe the feature**:

The predefined functions for script score query does not provide support for LogNormal, which is required as a part of rescoring. (There is no way to implement the method in Painless.) Please provide support for LogNormal.

**Comment by jtibshirani** [comment]
Thanks @sherry-ger for the feedback. For our context/ knowledge it would be helpful to hear more details of the use case:
* How would the log normal distribution be used as part of scoring? I would guess that its probability density function could be helpful as a decay function.
* Why can't it be implemented using pre-existing Painless functions? I think we already have the right building blocks to represent the PDF, just want to check I'm not missing some subtlety here.

**Comment by jtibshirani** [comment]
@sherry-ger just pinging again about the questions above.

**Comment by danielmitterdorfer** [comment]
No further feedback received. @sherry-ger if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
