### ISSUE TITLE
[DOCS] Include `xpack.security.http.ssl.client_authentication: optional` recommendation for Kibana

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#49510]
It may be helpful to document the following recommendations for Kibana users in our [security settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#http-tls-ssl-settings):

- When setting up Elasticsearch https and not using PKI realm, **do not** set `xpack.security.http.ssl.client_authentication: required`.  Recommended: `xpack.security.http.ssl.client_authentication: optional` 
- If there is a requirement for Kibana server to authenticate with Elasticsearch, configure PKI realm in Elasticsearch, then you can use `elasticsearch.ssl.certificate` and `elasticsearch.ssl.key` settings in the kibana.yml to specify the certificates to authenticate with Elasticsearch.

Relates to elastic/kibana#48303

**Comment by jkakavas** [comment]
> If there is a requirement for Kibana server to authenticate with Elasticsearch, configure PKI realm in Elasticsearch, then you can use elasticsearch.ssl.certificate and elasticsearch.ssl.key settings in the kibana.yml to specify the certificates to authenticate with Elasticsearch.

Note that kibana can authenticate with Elasticsearch using a username/password ( defined in `elasticsearch.username` and elasticsearch.password` ) so the above applies _only_ when there is an explicit requirement for kibana to authenticate with a client key/certificate. 

> When setting up Elasticsearch https and not using PKI realm, do not set xpack.security.http.ssl.client_authentication: required. Recommended: xpack.security.http.ssl.client_authentication: optional

I think we should not recommend something, but rather elaborate a little more on our explanation on the difference between `required` and `optional`. `none` is a totally valid option when not using a PKI realm.

**Comment by tvernum** [comment]
The root of the issue is that the combination of
- Required client auth
- PKI realm
- Kibana
don't work well together.

We recommend that you avoid applying PKI auth to any user authenticated connections from Kibana.

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
