### ISSUE TITLE
[Feature Request] Support parameterized queries

### ISSUE THREAD

**Issue by etki** [elastic/elasticsearch#49526]
Hey, I have a bit strange request. In classic SQL, we have prepared statements: a statement that is always the same, except for parameters, which are passed separately. May be we can do the same with elastic, adding named binding markers to query parameters and passing actual parameter values in and additional `body` field?

Benefits:

- Easy query diffs (on the position i'm working we need to analyze new changes in query quite often, and the query itself is couple of kilobytes)
- Separation of query preparation (it can be done once on application startup) and execution (if query is completely static)

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Elasticsearch. This feature is already available in Elasticsearch and is called [search templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html).
