### ISSUE TITLE
Additional context to the CONTRIBUTING.md

### ISSUE THREAD

**Issue by WilliamMars20** [elastic/elasticsearch#49521]
**Describe the feature**:

In CONTRIBUTING.md I noticed there are commands to configure the repository for eclipse and IntelliJ. These commands are only written in the way they would be for a shell and not the windows CLI. To remain consistent with the readme should the commands be written as if they were being put into a windows CLI as well as the unix terminal?

i.e.
> Eclipse users can automatically configure their IDE: `./gradlew eclipse` (Linux) `gradlew.bat eclipse` (Windows)
then `File: Import: Gradle : Existing Gradle Project`.

instead of:
> Eclipse users can automatically configure their IDE: `./gradlew eclipse`
then `File: Import: Gradle : Existing Gradle Project`.

**Comment by danielmitterdorfer** [comment]
Thanks for the idea. I've opened https://github.com/elastic/elasticsearch/pull/49528 which adds a clarifying note about usage on Windows in general.
