### ISSUE TITLE
SearchRequest: set customized parameters to url

### ISSUE THREAD

**Issue by QxiaoQ** [elastic/elasticsearch#49576]
When I use RestHighLevelClient, how do I add my '?token=6ueeefhueebff' to SearchRequest.

I know how to add param into request:

Request request = new Request("GET", "/myfile/_search?token=6ueeefhueebff");  OR
request.addParameter("token", "6ueeefhueebff");

But it seem s that there is no interface for SearchRequest to add my param.

**Comment by gaobinlong** [comment]
ES cannot accept customized parameters, so you can only send the parameter to your program but not es.

**Comment by cbuescher** [comment]
Hi @QxiaoQ and thanks @gaobinlong for chiming in. I would like you to continue this discussion and similar ones in out support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and this is more a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
