### ISSUE TITLE
question: I can not access  "https://discuss.elastic.co/"

### ISSUE THREAD

**Issue by xjtushilei** [elastic/elasticsearch#49586]
I can't open this website on my own computer. I can't open this website with Internet Accelerator.

Then I tried to Ping the domain name with servers in Singapore, Hong Kong and India, but it still didn't work.

Is this website accessible?

**Comment by xjtushilei** [comment]
https://gtmetrix.com/reports/discuss.elastic.co/pQu0aiRI

**Comment by cbuescher** [comment]
Looks live to me. I don't know how to help you with this here, Github doesn't seem the right way to track this though so I'm closing.
