### ISSUE TITLE
Systemd startup timeouts after upgrade to 7.4

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#49593]
It has been observed/reported in a few separate environments where after an upgrade from Elasticsearch 7.3 to 7.4, systemd will kill the elasticsearch process before it finishes starting up.

The end of the log looks like this:

```
[2019-11-25T07:16:46,095][DEBUG][o.e.a.ActionModule ] [node1] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2019-11-25T07:17:22,306][INFO ][o.e.x.m.p.NativeController] [node1] Native controller process has stopped - no new native processes can be started
```

Trace inspection of the log reveals that the ES node is busy upgrading.

Systemd requires that processes signal after successful startup with `sd_notify(READY)` before `TimeoutStartSec`, which in ES doesn't happen until metadata upgrades are complete.   It seems that we need to update [SystemdPlugin](https://github.com/elastic/elasticsearch/blob/ded5ad43d8fcd1190a5e4fb021bfca8d14409a0b/modules/systemd/src/main/java/org/elasticsearch/systemd/SystemdPlugin.java) to support [EXTEND_TIMEOUT_USEC](https://www.freedesktop.org/software/systemd/man/sd_notify.html) in the event of any expected startup delays such as upgrade.

**Comment by PhaedrusTheGreek** [comment]
Also curious here is why this hasn't been observed prior to 7.4.  Has something changed in this area?

**Comment by jasontedor** [comment]
> Also curious here is why this hasn't been observed prior to 7.4. Has something changed in this area?

Yes, the `sd_notify` functionality was not used until 7.4.0: elastic/elasticsearch#44673

**Comment by ppf2** [comment]
We have users starting to run into this with the service timing out and terminating Elasticsearch on startup (on nodes that are slower) after upgrading to 7.14.  Will we consider documenting this change under packaging in the [release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.14.0.html#packaging)?  thx!

**Comment by ppf2** [comment]
(Please ignore previous notification. I was reading 7.4 as 7.14 😄 ).  This was added back in 7.4.  Though some users may not hit this until later on nodes that are slow to start :)

**Comment by jasontedor** [comment]
Since 7.5.1/7.6 (https://github.com/elastic/elasticsearch/pull/49784), nodes that are slow to start should not present an issue.

**Comment by ppf2** [comment]
Thanks Jason!  It looks like we have user run into this on 7.14.  I will collect the details and file an issue accordingly for investigation.
