### ISSUE TITLE
[Monitoring] Introduce deprecation warning for shipping monitoring data to the production cluster

### ISSUE THREAD

**Issue by cachedout** [elastic/elasticsearch#49591]
This issue is a request for Elasticsearch to add a deprecation log entry in 7.6 for users who are shipping monitoring data to the production cluster which urges them to switch to using Metricbeat monitoring in order to be prepared for 8.0. 

If desired, the warning could link to instructions for doing so which are described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html

cc: @jakelandis @elastic/stack-monitoring

**Comment by cachedout** [comment]
@jakelandis Is this something you could add for us?

**Comment by jakelandis** [comment]
@cachedout - I'm not sure we want to emit deprecation warnings until we ship [Metricbeat with ES](https://github.com/elastic/elasticsearch/issues/49399).

**Comment by jakelandis** [comment]
this issue has been resolved via https://github.com/elastic/elasticsearch/pull/79499
