### ISSUE TITLE
Implement EQL Pipes in EQL Plugin

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#49627]
EQL has the concept of [pipes](https://eql.readthedocs.io/en/latest/query-guide/pipes.html) which run logic on the results of an eql query and can be combined. Regardless of the fact that in some cases the execution of these pipes can be pushed down to the Search API and run as aggregations (this will be addressed in a later issue) we need to implement the logic in the EQL plugin since there are many cases, including any EQL queries using sequence or join where we will not be able to push the evaluation down to the search API.

The pipe operations that need to be implemented are:
* [ ] count
* [ ] unique
* [ ] unique_count
* [ ] filter
* [ ] sort
* [x] head
* [x] tail

**Comment by costin** [comment]
Pipe infrastructure, `head` and `tail` are introduced through https://github.com/elastic/elasticsearch/pull/58536

**Comment by costin** [comment]
Raised a dedicated issue for `filter` through #59763

**Comment by costin** [comment]
Currently there are no plans to introduce other pipes for 7.11 GA hence why I'm closing the issue.
A new issue should be opened if this topic needs to be revisited.
