### ISSUE TITLE
it takes too lang when I use a shingle analyzer to search, because of create_weight

### ISSUE THREAD

**Issue by chenyiping111** [elastic/elasticsearch#49624]
I custom a analyzer which analyze text to 3-gram phrase use shingle-token-filter, when I look the profile , it takes 2.8s in create_weight(97.8% of all took) which field use the 3-gram analyzer , how can I improve the search speed ?

**Comment by chenyiping111** [comment]
why it takes so long to create weight when term is not single word?

**Comment by cbuescher** [comment]
Hi @chenyiping111! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
