### ISSUE TITLE
Modify EQL execution to use point in time reader

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#49628]
When https://github.com/elastic/elasticsearch/issues/46523 is merged we will want to modify the EQL execution logic to create a point in time reader at the start of execution and use that same point in time view of the index throughout the execution of the query. This will ensure that the results ae gathered from a consistent view of the index

**Comment by costin** [comment]
Solved by https://github.com/elastic/elasticsearch/pull/62276 and https://github.com/elastic/elasticsearch/pull/62469
