### ISSUE TITLE
Coordinating node stats including search qps and latency

### ISSUE THREAD

**Issue by wangkhc** [elastic/elasticsearch#49622]
Today we are lack of coordinating node metrics, which is helpful for performance analyzation in many scenario. For example, when a query with heavy aggregation happening on coordinating node, this cost is not being recorded in current query stats (only shard level on data nodes), we cannot track any information happening on coordinating nodes.

With coordinating stats recording server-side latency (which is same as "took" in search response), this is very helpful for OLAP users to realize that heavy aggregation is happening, and thus can further optimize their use-case.

Besides, current "qps" is kind of confusing as it only reflects shard-level, which is (real_qps * shard_count). Introducing coordinating node search qps can make it clear for end users

**Comment by jasontedor** [comment]
Thanks for the issue. This relates to #49362. At this time, we don’t think we should add stats like this. Currently, we collect stats at the shard level, and collecting at the coordinating level would be quite the departure from that. We aim to keep our API surface area small, and don’t see compelling justification to add anything along the lines suggested here.
