### ISSUE TITLE
[CI] 409 Conflicts in synced-flush docs test

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#49623]
We've had at least 4 occurrences this month (on a couple of different lines):
- https://gradle-enterprise.elastic.co/s/ukjhirjmluqsg
- https://gradle-enterprise.elastic.co/s/6accccwxy7tko/console-log?task=:docs:integTestRunner
- https://gradle-enterprise.elastic.co/s/cqrnlr52mnrkc/console-log?task=:docs:integTestRunner
- https://gradle-enterprise.elastic.co/s/m7r54sg46ktji/console-log?task=:docs:integTestRunner
 
> org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/indices/synced-flush/line_10} FAILED

```
java.lang.AssertionError: Failure at [reference/indices/synced-flush:42]:
expected [2xx] status code but api [raw[method=POST path=twitter/_flush/synced]] returned
[409 Conflict] [{
  "_shards":{"total":2,"successful":0,"failed":2},
  "twitter":{"total":2,"successful":0,"failed":2,
    "failures":[{"shard":0,"reason":"[1] ongoing operations on primary"}]
  }
}]
```

```
./gradlew ':docs:integTestRunner' \
  --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/indices/synced-flush/line_10}" \
  -Dtests.seed=85FAD2E193B5BFFA -Dtests.security.manager=true \
  -Dtests.locale=ru-RU -Dtests.timezone=Africa/Khartoum \
  -Dcompiler.java=12
```

**Comment by ywelsch** [comment]
I suspect that this is a background global checkpoint sync, retention lease sync or other such action. Synced flush performs poorly in the presence of those. As we are getting rid of synced flush, I wonder if we should just disable these flaky REST tests.

**Comment by ywelsch** [comment]
@jrodewig can you remove the docs tests for synced-flush? These are unfortunately flaky as they can interact with other parts of the system (see my comment above). We are covering the functionality as part of our test infrastructure in other places.

**Comment by jrodewig** [comment]
@ywelsch Yes. I'll remove those tests. Thanks for reaching out.
