### ISSUE TITLE
SQL: Improve optimization of binary comparisons and equal

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#49637]
Teach optimizer to handle equality and a comparison:

`a = 2 AND a > 1` -> `a=2` but also
`a = 2 AND a > 3` -> `FALSE`

**Comment by costin** [comment]
Also inequality - `a != 2 AND a >3` -> `a > 3`

**Comment by matriv** [comment]
++
Would be a nice optimization to prevent unnecessary clauses from leading to scripting queries and decreasing performance.

**Comment by olegbonar** [comment]
Hi @costin! If I got it right this optimization is to implement another method in `org.elasticsearch.xpack.sql.optimizer.Optimizer`. Any ideas on hacking it?

**Comment by bpintea** [comment]
Fixed in #50703, #50792, #51088.
