### ISSUE TITLE
elasticsearch-croneval shouldn't dump a stacktrace for invalid patterns

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#49642]
**Elasticsearch version**

7.4.2, master

**Description of the problem including expected versus actual behavior**:

When `elasticsearch-croneval` is run with a malformed cron pattern, it dumps a stacktrace to the terminal.

The tool ought to simply report that the pattern is malformed and either direct the user to the documentation or print a brief summary of the expected input (I'd vote for the latter).

**Steps to reproduce**:

   1. `bin/elasticsearch-croneval "*"

**Comment by gaobinlong** [comment]
Hi @pugnascotia , this issue can be closed as the related PR #49744 has been merged.
