### ISSUE TITLE
[DOCS] Ingest-attachment using CBOR example

### ISSUE THREAD

**Issue by carantunes** [elastic/elasticsearch#49659]
Please provide an example for ingest attachment plug in with CBOR format for indexing documents.

I'm  struggling indexing large documents - and currently have no idea how to use "CBOR...without using json" as specified in the docs here: https://www.elastic.co/guide/en/elasticsearch/plugins/5.2/ingest-attachment.html

**Comment by martijnvg** [comment]
@carantunes Thanks for opening this issue. We should provide more information on how to use the attachment processor with cbor.

Which Elasticsearch client & programming language are you using? An Elasticsearch node natively accepts cbor if the content type header is set correctly. Also you will need to serialize that as cbor in your application.

**Comment by carantunes** [comment]
Hey, I managed to test it. Thanks!

For anyone interested here's a sample:
https://discuss.elastic.co/t/ingest-attachment-using-cbor-sample/209818/3

**Comment by carantunes** [comment]
Great to see this was updated! 🚀
