### ISSUE TITLE
[CI] ICUCollationKeywordFieldMapperIT.testNormalization() failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#49654]
Build logs: https://gradle-enterprise.elastic.co/s/tcbswba24vb6u/console-log#L5288

```
REPRODUCE WITH: ./gradlew ':plugins:analysis-icu:integTestRunner' --tests "org.elasticsearch.index.mapper.ICUCollationKeywordFieldMapperIT.testNormalization" -Dtests.seed=534D27A7291B436E -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=12
--
2> java.lang.AssertionError: Expected id: 2 at position 0 but wasn't. Total shards: 4 Successful shards: 4 & 0 shard failures:
Expected: "2"
but: was "1"
at __randomizedtesting.SeedInfo.seed([534D27A7291B436E:77124CFBC84F3C44]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertOrderedSearchHits(ElasticsearchAssertions.java:247)
at org.elasticsearch.index.mapper.ICUCollationKeywordFieldMapperIT.testNormalization(ICUCollationKeywordFieldMapperIT.java:208)
```

This test has failed 6 times now today according to [build stats](https://build-stats.elastic.co/app/kibana#/discover/c46fbf60-05ec-11ea-ba75-91621e16ca05?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20class:*ICUCollationKeywordFieldMapperIT%20AND%20test:testNormalization'),sort:!(time,desc))).

**Comment by cbuescher** [comment]
I think I see a small glitch introduced in https://github.com/elastic/elasticsearch/commit/c2deb287f138323e9cee1b4fd0aa3d5a9056b1f3. Will open a PR if nobody else beats me to it...

**Comment by martijnvg** [comment]
Thanks for fixing @cbuescher!
