### ISSUE TITLE
add some pointer to determine when upgrading is complete

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#49670]
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/rolling-upgrades.html#rolling-upgrades shows the step of rolling upgrade process, but it would be nice to add final step as to how to validate the upgrade finished successfully.

I can imagine that everyone must be issuing some flavor of cat API and it would be helpful if we can list them up in this page as well.

**Comment by matriv** [comment]
@TomonoriSoejima Thank you for bringing this up to our attention.
A PR is out to provide more info on how to check the status of a rolling upgrade.

**Comment by matriv** [comment]
`master` : 8ca11f54cd839f41632c556601e94da67e91a3d1
`7.x` : d5842aebab5d42a64b2e05fba94bf4cf2b7f3cbc
`7.5` : eefc6ec28fc4fb1d14382c1a1ab8986399c3f69c
`7.4` : 073449b5616b558f0b4f1897a6dfd82b7030f3fb
