### ISSUE TITLE
[CI] Failure in org.elasticsearch.search.query.QueryPhaseTests.testIndexHasDuplicateData

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#49703]
`#testIndexHasDuplicateData` and specifically [this assertion](https://github.com/elastic/elasticsearch/commit/fa8b48deefbec1eb58161252552628a1a0866e5f#diff-5fac69dcf1790a41ec05793b9c025862R728) has been failing since https://github.com/elastic/elasticsearch/commit/fa8b48deefbec1eb58161252552628a1a0866e5f, as seen for example in this scan: https://gradle-enterprise.elastic.co/s/k3vldmv6cz4ac 

``` java
    public void testIndexHasDuplicateData() throws IOException {
        int docsCount = 7000;
        int duplIndex = docsCount * 7 / 10;
        int duplIndex2 = docsCount * 3 / 10;
        long duplicateValue = randomLongBetween(-10000000L, 10000000L);
        Directory dir = newDirectory();
        IndexWriter writer = new IndexWriter(dir, new IndexWriterConfig(null));
        for (int docId = 0; docId < docsCount; docId++) {
            Document doc = new Document();
            long rndValue = randomLongBetween(-10000000L, 10000000L);
            long value = (docId < duplIndex) ? duplicateValue : rndValue;
            long value2 = (docId < duplIndex2) ? duplicateValue : rndValue;
            doc.add(new LongPoint("duplicateField", value));
            doc.add(new LongPoint("notDuplicateField", value2));
            writer.addDocument(doc);
        }
        writer.close();
        final IndexReader reader = DirectoryReader.open(dir);
        boolean hasDuplicateData = indexFieldHasDuplicateData(reader, "duplicateField");
        boolean hasDuplicateData2 = indexFieldHasDuplicateData(reader, "notDuplicateField");
        reader.close();
        dir.close();
        assertTrue(hasDuplicateData); <---- this trips
        assertFalse(hasDuplicateData2);
    }
```

I am able to reproduce this locally using `./gradlew ':server:test' --tests "org.elasticsearch.search.query.QueryPhaseTests.testIndexHasDuplicateData" -Dtests.seed=EA6BD7DFEF354E5A -Dtests.security.manager=true -Dtests.locale=en-ZA -Dtests.timezone=Etc/GMT+0 -Dcompiler.java=12`.

**Comment by spinscale** [comment]
another failing seed (under osx for me): `./gradlew ':server:test' --tests "org.elasticsearch.search.query.QueryPhaseTests.testIndexHasDuplicateData" -Dtests.seed=7D0D1C76527A8E17 -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=America/Porto_Velho -Dcompiler.java=12`

**Comment by andreidan** [comment]
another failing seed: `./gradlew ':server:test' --tests "org.elasticsearch.search.query.QueryPhaseTests.testIndexHasDuplicateData" \
  -Dtests.seed=A6A1AFA6B34C16A4 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Singapore \
  -Dcompiler.java=12`
