### ISSUE TITLE
Mapping Field Types Specification

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#49704]
I am opening this issue to discuss how we could expose the specification of the field types exposed in our mappings. Today we have a json spec for all our rest APIs but it covers only the path and request parameters. It would be a gigantic task to cover the body of all our requests and responses so this issue is not about a full spec but rather a focus on a specific part of our API: the  mapping field types. When building a client on top of Elasticsearch or a UI to create a mapping, it would be useful to have an endpoint that could list all available field types and the options that they accept. Having an endpoint instead of a json spec in our repository would allow to expose custom field types in plugins more easily. However maintaining this endpoint has a cost so it should be built in a way that any discrepancy between the spec and the code would fail the build.

This issue relates to https://github.com/elastic/elasticsearch/issues/25152 but the scope hre is limited to mapping field types so if you'd like to discuss a general specification model for Elasticsearch the linked issue is the right place to add your comment.

**Comment by jimczi** [comment]
\cc @elastic/es-ui

**Comment by jethr0null** [comment]
@jimczi I just wanted to touch base here to see if this has been discussed any further on the es-search team side? If a real-time discussion would be of benefit, I'm happy to hop on a zoom.

**Comment by javanna** [comment]
Gathering some context here and figuring out what has changed since this issue was opened: @elastic/es-clients how do the clients interact with mappings nowadays? Are they aware of field types and their options?

**Comment by sethmlarson** [comment]
They are! We've created the [elasticsearch-specification](https://github.com/elastic/elasticsearch-specification) which includes a TypeScript specification for [mapping types](https://github.com/elastic/elasticsearch-specification/tree/main/specification/_types/mapping).

**Comment by javanna** [comment]
looks good @sethmlarson , thanks for linking that. How is that spec kept up-to-date?

**Comment by sethmlarson** [comment]
@javanna The process today is manual to keep specs up-to-date. We use integration tests to verify whether our specifications match requests and responses structure so any changes there will show up as a "failure" to match the structure.

**Comment by javanna** [comment]
Ok, thanks for the input @sethmlarson . I am now wondering if the suggested endpoint to expose field types and their options is still necessary. I believe that plugins are not covered by the specification linked above, but I am missing context on where this endpoint would be used and why plugins play a role. I will leave it open waiting for feedback on this cc @cjcenizal @jethr0null @sebelga

**Comment by cjcenizal** [comment]
To be honest I don't 100% remember the context of this request. I _think_ it had to do with the Mappings Editor in Kibana Stack Management. We currently hardcode all expected mapping types and their allowed options on the client side, and this API would enable us to depend on ES as the source of truth instead.

**Comment by sebelga** [comment]
Correct @cjcenizal. We were looking for

_a solution on how we are going to keep in sync with the API for the default values and the allowed parameters for each type_. 

As everything is hard coded in the mappings editor, if a default value changes for a parameter or if a parameter is deprecated or added we are not automatically notified and the UI is out of sync with the API.

I don't think we leverage the Typescript types (as they were added later) so maybe we could revisit the implementation and make it more robust with TS?

**Comment by javanna** [comment]
I can imagine that the typescript types are not leveraged because they are a fairly recent thing. Now that we have that, it would be great to try to reuse and consolidate them. It makes a lot of sense to me that Kibana relies on the same mechanism that the language clients rely on. The question around plugins remains ( I assume they are not supported by the spec, but then how important is it that they are supported?). While adding an API is an interesting idea, I have some concerns about the maintenance cost, extending the API surface further, plus I don't foresee the team will get to this anytime soon. For this reason I would close the issue for now. We can always reopen if needed.
