### ISSUE TITLE
{"error":"Content-Type header [application/x-ndjson] is not supported","status":406} using curl

### ISSUE THREAD

**Issue by altafparkar** [elastic/elasticsearch#49741]
**Describe the feature**:
I get {"error":"Content-Type header [application/x-ndjson] is not supported","status":406} error when I do the below
curl -s -H "Content-Type: application/x-ndjson" -XPOST http://localhost:9200/_template/hazard-template --data-binary <<filename>>

**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.0

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_201"

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Hi @altafparkar. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
