### ISSUE TITLE
Custom function for Text Similarity Search

### ISSUE THREAD

**Issue by loretoparisi** [elastic/elasticsearch#49750]
I'm using a `dense_vector` and `cosineSimilarity` to get documents similarity following the good tutorial [here](https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch)

```python
script_query = {
        "script_score": {
            "query": {"match_all": {}},
            "script": {
                "source": "cosineSimilarity(params.query_vector, doc['text_vector']) + 1.0",
                "params": {"query_vector": query_vector}
            }
        }
    }
```

As for release 7.3 elasticsearch provide natively for the script the `cosineSimilarity`. When working in the STS (Sentence Textual Similarity), there are more choices for the metrics, among them: 

- Euclidean distance
- Manhattan distance
- Cosine distance (equivalente alla Euclidean distance dei vettori normalizzati)
- Hamming distance
- Dot (Inner) Product distance

So, how to implement a custom ElasticSearch similarity function for the search query script, let's say Euclidean or dot product?

Thank you.

**NOTE**
- My reference project was [BertSearch](https://github.com/Hironsan/bertsearch), were the textual embedding has been calculated with Google's BERT.
- We should keep in mind that for a given vectorial distance to get the similarity a common transformation is:`similarity = 1 / (1 + distance)`.
- Regarding BERT, a good similarity scoring approach is described in [bert_score](https://github.com/Tiiiger/bert_score)

**Comment by probakowski** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by loretoparisi** [comment]
@probakowski okay, it makes sense, but the question is. Will ElasticSearch support other custom functions than "cosinesimilarity" and / or is it possibile to customize ES for that?
