### ISSUE TITLE
Can I update analyzer in field without recreating the index?

### ISSUE THREAD

**Issue by ysunil702** [elastic/elasticsearch#49752]
**Elasticsearch version** (`bin/elasticsearch --version`):7.0.0

Following index is created.

```
 "ticketId": {
        "type": "text",
        "fields": {
          "completion": {
            "type": "completion",
            "analyzer": "simple",
            "preserve_separators": true,
            "preserve_position_increments": true,
            "max_input_length": 50,
            "contexts": [
              {
                "name": "mailboxIdStr",
                "type": "CATEGORY",
                "path": "mailboxIdStr"
              }
            ]
          },
          "keyword": {
            "type": "keyword"
          }
        },
        "analyzer": "simple"
      }
  
```
so, i want to update or remove _"analyzer":"simple"_ from ticketId field. is it possible without recreate index?

**Comment by cbuescher** [comment]
Hi @ysunil702. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
