### ISSUE TITLE
[CI] elasticsearch-hadoop build failure

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#49766]
This has been failing since the 25th of November since another build problem was fixed with https://github.com/elastic/elasticsearch-hadoop/pull/1394 

```
Execution failed for task ':elasticsearch-hadoop-hive:esCluster#start'.
13:34:35 > org/elasticsearch/gradle/info/BuildParams has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+7.x+periodic/181/console

**Comment by jaymode** [comment]
@mark-vieira can you take a look at this?

**Comment by mark-vieira** [comment]
Looks like we'll have to move this class to our java8 source set. I'll open a PR for this.
