### ISSUE TITLE
Install license WITHOUT REST API, Kibana upload option

### ISSUE THREAD

**Issue by nathanrstacey** [elastic/elasticsearch#49783]
**Describe the feature**:
Several high-security users, for their internal security processes, have to take extreme measures to install new licenses via the REST API. Request an upload option to upload a license file into Elasticsearch via Kibana

**Comment by pickypg** [comment]
This feature has existed since at least 6.3.

https://www.elastic.co/guide/en/kibana/current/managing-licenses.html
