### ISSUE TITLE
Docs: Instructions to enable TLS incorrect, xpack.security.enabled -> xpack.security.transport.ssl.enabled

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#49806]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.5

**Plugins installed**: [analysis-icu]

**JVM version** (`java -version`): openjdk version "11.0.4" 2019-07-16

**OS version** (`uname -a` if on a Unix-like system): Linux els02 4.15.0-1056-aws #58-Ubuntu SMP Tue Nov 26 15:14:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Instructions tell us to set xpack.security.enabled to true.

If the instructions are followed, elasticsearch fails to start due to an invalid license.

The instructions should in theory tell us to set xpack.security.transport.ssl.enabled to true.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Follow instructions to "Configure TLS and authentication" at https://www.elastic.co/blog/getting-started-with-elasticsearch-security
 2. Elasticsearch fails to start with a license error.

**Provide logs (if relevant)**:

**Comment by jkakavas** [comment]
@minfrin the blog post you are referencing also states to set `xpack.security.transport.ssl.enabled: true` in the same configuration stanza it mentions `xpack.security.enabled`. 

Can you clarify what you mean with 

> If the instructions are followed, elasticsearch fails to start due to an invalid license.

What is the actual error you are getting? 

Also, how did you install elasticsearch on your system ?

**Comment by minfrin** [comment]
Elasticsearch is installed from the supplied debian package on Ubuntu Bionic.

Annoyingly I didn't cut and paste the exception, and the stack has been dropped and the logs are gone. I now can't reproduce this with this config, this starts up:

```
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: machine-server.key
xpack.security.transport.ssl.certificate: machine-server+issuer.crt
xpack.security.transport.ssl.certificate_authorities: machine-issuer+root.crt
```

**Comment by albertzaharovits** [comment]
I understand there are no actionable problems left.
