### ISSUE TITLE
Failing in Mapping a doc with Multi field of boolean  

### ISSUE THREAD

**Issue by afnanali1992** [elastic/elasticsearch#49808]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.5 - elastic cloud

**Plugins installed**: [mongoosastic]

Hello, I have a question regarding mapping Multifield of the following types (boolean, array, string) with using `ignore_malformed` where it doesn't support those types,  ignore_malformed works properly with a number and a date type.

We have the value field which is of type `Mixed` in MongoDB and we tried to transport into ES using `multifield` by creating the following **mapping**:

 ```
{
  "mappings": {
    "user": {
      "properties": {
        "attribute": {
          "type": "nested",
          "properties": {
            "value": {
              "type": "text",
              "fields": {
                "number": {
                  "type": "double",
                  "ignore_malformed": true
                },
                "date": {
                  "type": "date",
                  "ignore_malformed": true
                },
                "boolean": {
                  "type": "boolean",
                  "ignore": true
                }

              }
            }
          }
        }
      }
    }
  }
}
```
Our schemas are :
**User schema**
```
var UserSchema = new Schema({
  name: { type: String, es_indexed: true, required: true },
  email: { type: String, es_indexed: true },
  address: { type: [addressSchema], es_type: 'nested', es_indexed: true },
  attribute: { type: [attribute], es_type: 'nested', es_indexed: true }
})
```
**Attribute Schema**
```
const attribute = new Schema({
  inner_name: String,
  value: {
    type: Schema.Types.Mixed,
    es_type: 'multi_field',
    es_fields: {
      string: { type: String, index: 'analyzed' },
      date: { type: Date, index: 'analyzed' },
      number: { type: Number, index: 'analyzed' },
      boolean: { type: Boolean, index: 'analyzed' },
      array: { type: Array, index: 'analyzed' },
      object: { type: Object, index: 'analyzed' },
      null: { type: null }
    }
  }
})
```

The Error was `failed to parse the field of type [boolean]` 
 If there is any instead of `ignore_malformed` parameter that could support (boolean, array, string) types ? or Is there any a solution?

Thanks in advance.

**Comment by astefan** [comment]
@afnanali1992 thank you for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
