### ISSUE TITLE
logs about updating IndexSetting should be more detailed

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#49818]
**ES_VERSION:** 7.3.1
**Description of the problem including expected versus actual behavior:**
When updating index setting like this:
`PUT index1/_settings
{
	"index": {
		"merge": {
			"policy": {
				"max_merge_at_once": "5"
			}
		}
	}
}`
and relevent log is:
`[2019-12-03T21:59:14,065][INFO ][o.e.c.s.IndexScopedSettings] [node-1] updating [index.merge.policy.max_merge_at_once] from [10] to [5]`
according to the log, I don't know which index is updated, If we could add the index name in the log.

**Comment by DaveCTurner** [comment]
Seems like a reasonable thing to want @kkewwei. Would you care to work on a PR?

**Comment by kkewwei** [comment]
It's my pleasure to do it.

**Comment by rachana-prajapati** [comment]
Is this item still open?

**Comment by kkewwei** [comment]
@rachana-prajapati, yes, you can see it it the pr.
