### ISSUE TITLE
Remove code_user, code_admin roles and remove .code* index privileges for kibana_system role

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch#49842]
Since the experimental code application has now been removed from Kibana, we can remove or modify some of the existing reserved roles as well.

The `code_user` and `code_admin` roles can be removed entirely.

Additionally, the `kibana_system` role can be modified to remove the index-privileges for the `code-*` and `code_internal-*` indices.

**Comment by tvernum** [comment]
Thanks for raising this @kobelb.
It has been on my TODO list, but I didn't get around to opening an issue yet.
