### ISSUE TITLE
Any plan to add support for aarch(ARM64)?

### ISSUE THREAD

**Issue by freesinger** [elastic/elasticsearch#49846]
I'm configuring ES in development environment and I find that Linux version ES(v7.3.0, x86-64) which I can only download is not compitable for my server arm64 architechture.
Any solution to this problem such compiling to get binary files for arm64 architecture?
It seems that this problem has been pointed long ago.

`If you'd prefer to only enable metadata for architectures that you know are being used, then I'd just ask adding arm64 to that list - I can confirm that it is being used.`

_Originally posted by @dannf in https://github.com/elastic/elasticsearch/issues/9299#issuecomment-71059960_

**Comment by astefan** [comment]
@freesinger there are several similar questions on discuss.elastic.co, one of which I find particularly relevant: https://discuss.elastic.co/t/elasticsearch-7-x-support-for-arm64-raspberry-pi-4-b/187976/2

I don't think we have plans for _official_ arm64 support. CC @elastic/es-core-infra for confirmation.

**Comment by freesinger** [comment]
@astefan Thank for replying, I've found the question you mentioned in the forum.
I'll find my way to solve my issue.
