### ISSUE TITLE
Linear/factor rank_feature query scoring

### ISSUE THREAD

**Issue by mrkamel** [elastic/elasticsearch#49859]
It would be great to have a linear/factor scoring for rank_feature queries in addition to saturation, log and sigmoid, especially with the rank_features datatype, where the matching rank_features value simply is applied as is (while it can still be boosted).

Example use case: a certain product should rank better for a small subset of categories according to a predefined value, but with linear scoring, like with function_score/field_value_factor. However, field_value_factor can't be used due to high variance of keys in the vector and mapping explosion, accordingly.

**Comment by jpountz** [comment]
For the record, a workaround is to use saturation with high values of `boost` and `pivot`, e.g.

```
  {
    "rank_feature": {
      "field": "my_feature",
      "boost": 100000,
      "saturation": {
        "pivot": 100000
      }
    }
  }
```

**Comment by mrkamel** [comment]
Yeah :+1: that's what i do currently. Still, it would be great to be supported without workaround as the workaround maybe is not self explanatory to everyone before really digging into it and ... it's "just" a  close approximation.

**Comment by mayya-sharipova** [comment]
@mrkamel  We would like to know more details about your use-case for a linear rank feature function.  Our intent for a `rank_feature` query is to boost scores of textual queries based on some non-textual features. The boosting happens by combining textual scores with some function from non-textual features. From the literature, we understood that the best functions are saturation, logarithm and sigmoid, which we are available.

Now, we are wondering what is your need for a linear function?   Is it to ensure that a document having a certain feature ranks higher no matter what other contributions are? What kind of queries you would like to run for your use case  –  only` rank_feature` or in a combination with other queries?

**Comment by mrkamel** [comment]
hi, sure:

> Now, we are wondering what is your need for a linear function? 

Generally, a linear function is often easier to reason about and to communicate.
Specific use case: when calculating scores for a rank_features field externally and you want the scores to be applied as is

For instance, we e.g. boost certain docs according to a match in a lead concept/category, the categories are stored as the keys of a rank_features field, while the matching category is looked up externally before sending the query to ES. The scores are pre-calculated externally as well (e.g. via ML model/similarilty metrics/etc) and we want them to be applied as is.

> Is it to ensure that a document having a certain feature ranks higher no matter what other contributions are?

yes, that's a use regarding `rank_features` as well. When you want to "pin" a varying number of docs according to a matching key of a `rank_features` field and with a pre-defined order of those docs.

> only rank_feature or in a combination with other queries?

always in combination with other queries, any kind, ... boosted term queries, multi_match with boolean similarity, geo distance, anything.

**Comment by mayya-sharipova** [comment]
[Linear function](https://github.com/apache/lucene-solr/pull/2051)  for feature field has been merged to Lucene.
We will expose it in elasticsearch with the next Lucene upgrade.

**Comment by dvisztempacct** [comment]
Thank you!

**Comment by peterdm** [comment]
Thank you!  This will also be valuable for anyone who is performing feature normalization outside of elasticsearch!
