### ISSUE TITLE
Separate AST into direct AST representation of script and an internal representation

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49869]
Painless parses the script into an AST and mutates while processing.  Correlation with user provided script is difficult as we don't have the raw representation.  Keeping the original AST around without mutating it will enable better error messages and other IDE-like functionality.

**Comment by stu-elastic** [comment]
Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by jdconrad** [comment]
Closing in favor of #53702
