### ISSUE TITLE
Jar Separation - Separate Painless into it's own jar for consumption within other projects

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49868]
Painless is packaged as a plugin in it's out jar, which makes consumption outside of the elasticsearch context difficult.  We should add a build task to build a stand-alone jar for consumption outside of elasticsearch.

**Comment by stu-elastic** [comment]
Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
