### ISSUE TITLE
Painless Safety: Runaway loop checking

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49871]
Add a timing counter every `n` iterations which may trigger an early exit if the script has gone over time.

Related: https://github.com/elastic/elasticsearch/issues/30139

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
