### ISSUE TITLE
Painless Safety: Explore memory limiting

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49872]
Scripts should not be able to OOM a node.  Explore strategies for avoiding this such as memory tracking, cgroups, etc.

Related: https://github.com/elastic/elasticsearch/issues/30139

**Comment by jdconrad** [comment]
Closing this as there is no effective way to limit memory consumption without drastically impacting performance along with the fact that Painless uses library methods that while safe, it doesn't have memory control over.
