### ISSUE TITLE
Add highlighting and autocomplete for painless to kibana via Monaco

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49879]
Monaco is a in-browser implementation of VS Code that was recently added to Kibana.

We should integrate with Monaco to make writing painless scripts easier for users.  This includes highlighting and autocomplete.

**Comment by stu-elastic** [comment]
Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by stu-elastic** [comment]
* [ ] Setup vscode/monaco and register a LSP server for painless
* [ ] See request frequency for LSP

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
