### ISSUE TITLE
Build context factories from AST rather than ASM

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49875]
ASM is used to build the context factories on the fly.  This task is to build the AST directly and use that to generate the ASM.

We'll be better able to reason about the generation process since ASM is difficult to read.

Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by jdconrad** [comment]
Done.

**Comment by jdconrad** [comment]
Oops, thought this was a different issue.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
