### ISSUE TITLE
Design deprecation flow for painless whitlisted methods

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49881]
One can currently deprecate whitelisted methods but nothing is done with this.  We need to design a flow that eventually removes deprecated whitelisted methods.

Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
