### ISSUE TITLE
Painless documentation: generate context documentation

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49883]
Use descriptions and context API to generate context documentation in painless

Related: https://github.com/elastic/elasticsearch/issues/49882
Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
