### ISSUE TITLE
Support read only variables in painless

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49884]
Read only variables would help users reason about their code and allow us to avoid several hash look ups for unchanged variables.

Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by stu-elastic** [comment]
This enables optimizations per doc that is not possible right now.  Eg a param does not change per doc but maybe recomputed.  This would enable us to avoid the lookup per doc.  The accessor for a doc value should be reusable as it gets changed behind the scenes.

Notes:
* Classbindings assume read only values, but there this invariant is not ensured.
* Subclassing classes like Map would be a lot of work for nested Maps (eg watcher input)
* Change eg params to unmodifiable map, which doesn't work with arrays
* Can use an annotation in whitelist `@readonly` for methods that are safe
* May have to change `doc` to a non-map, we currently use a map for bracket access.  This will change with #52589.
  * Will still have to track the output from `@readonly` whitelisted methods for correctness.
* Modify IR tree to add caching once `@readonly` tracking is implemented.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
