### ISSUE TITLE
Make type checking only occur during semantic phase

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#49880]
Type checking occurs in both the lexing phase and semantic phase.  This leads to obtuse errors when caught in the lexing phase.  Supporting both is also a maintenance burden.  If the grammar were context free, we could do all type checking in the semantic phase and provide better error messages and clean up some code.

Migrated from: https://github.com/elastic/elasticsearch/issues/31009

**Comment by jdconrad** [comment]
Done.
