### ISSUE TITLE
org.elasticsearch.index.query.QueryBuilder  can extends  java.io.Serializable

### ISSUE THREAD

**Issue by biuabiu** [elastic/elasticsearch#49897]
when use apache.dubbo time , because the QueryBuilder   can not implements java.io.Serializable
the dubbo  throw the java.lang.RuntimeException: QueryBuilder  subclass  must implement java.io.Serializable
Can I get your help?
Looking forward to reply thanks

**Comment by cbuescher** [comment]
Hi @biuabiu, sorry but those classes don't really support Java's builtin serialization. For node-to-node communication we serialize e.g. queries with an own mechanism. There's a short [section in our checktstyle definition](https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/resources/checkstyle.xml#L89) where we supress warnings around it. As such I hope you don't mind if I close this issue. If you need further help around this please post a question in our support forums over at https://discuss.elastic.co.

**Comment by biuabiu** [comment]
oh no , why not ?
if AbstractQueryBuilder can implements?
analogy , AbstractPageRequest  it is implements
