### ISSUE TITLE
Make GeoIP processor seamless to Beats

### ISSUE THREAD

**Issue by nathanrstacey** [elastic/elasticsearch#49928]
**Describe the feature**:
When adding geo info to IP data, it requires extensive configuration changes. Specifically changing the Beat yml and adding a pipeline in Elasticsearch. As shown here:
https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-geoip.html

It would be great if these steps were simplified to the user by just a button to click on Kibana. Maybe this button is next to the ML drop down, maybe this button is in the Beats management area

Concerning how to do this: My first thought is to ALWAYS have the geoIP pipeline added for ALL ingest from Beats. Then, change the GeoIP processor to ONLY reach out to the internet when the button on Kibana says GeoIP is needed.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
