### ISSUE TITLE
RestHighLevelClient causing warnings on all requests

### ISSUE THREAD

**Issue by SledgeHammer01** [elastic/elasticsearch#49973]
Running ES 7.4.2.

Client app is Spring Boot 2.2.1 using ElasticsearchRepository.

pom.xml specifies:

		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-elasticsearch</artifactId>
			<version>3.2.3.RELEASE</version> 
		</dependency>

I am using the RestHighLevelClient as follows:

	@Bean
	@SuppressWarnings("deprecation")
	public RestHighLevelClient client() {
		RestClientBuilder restClientBuilder = RestClient.builder(getHost()).setHttpClientConfigCallback(new HttpClientConfigCallback() {
			@Override
			public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
				return httpClientBuilder.setDefaultCredentialsProvider(getCredentialsProvider());
			}
		});

		RestHighLevelClient client = new RestHighLevelClient(restClientBuilder);

All my requests return a warning:

2019-12-08 11:02:18.379  WARN 15876 --- [/O dispatcher 1] org.elasticsearch.client.RestClient      : request [PUT http://localhost:9200/kibana_sample_data_flights/_mapping/_doc?master_timeout=30s&include_type_name=true&timeout=30s] returned 1 warnings: [299 Elasticsearch-7.4.2-2f90bbf7b93631e52bafb59b3b049cb44ec25e96 "[types removal] Using include_type_name in put mapping requests is deprecated. The parameter will be removed in the next major version."]

I understand types are removed. How do I make RestHighLevelClient use the typeless APIs? The state of this is somewhat confusing...

**Comment by tvernum** [comment]
Hi @SledgeHammer01, Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

In your forum post, please include:
1. The exact version of the High Level Rest Client you are using. (I believe spring uses an old version of the client, but we need to know exactly what is in use in your project).
2. The code for where you perform one of the operations that returns this warning (e.g. the put  index mapping request).

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
