### ISSUE TITLE
Restarting data node should not cause local shards unassigned when disk size above low-watermark

### ISSUE THREAD

**Issue by wangkhc** [elastic/elasticsearch#49972]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.2

**Description of the problem including expected versus actual behavior**:

We have disk low-watermark threshold settings which will prevent allocating new shard when disk size above 85% by default. However on node simply rebooting scenario, this setting still prevents local existing shards to recover back, because master think of these shards are "new" to this node, which is not true since these shard data still located on this node and not being deleted.

**Steps to reproduce**:
 1. Setup 3 node cluster with all disk all above 85% filling by index shards
 2. reboot one node

![image](https://user-images.githubusercontent.com/32295978/70392135-7e138580-1a17-11ea-8672-e95aa32d6a69.png)

**Comment by DaveCTurner** [comment]
Currently the master cannot determine that the data on the node can actually be re-used, so there is a risk that it allocates an apparently-reusable shard to the node and only then discovers that it needs to make a full copy.

However it does seem that there is room for improvement in the (common) case that the shard data can be re-used. For instance, maybe we could allocate the shard on a "ops-based-recovery-or-nothing" basis, never performing a file-based recovery. Marking this as "help wanted".

**Comment by wangkhc** [comment]
> Currently the master cannot determine that the data on the node can actually be re-used, so there is a risk that it allocates an apparently-reusable shard to the node and only then discovers that it needs to make a full copy.
> 
> However it does seem that there is room for improvement in the (common) case that the shard data can be re-used. For instance, maybe we could allocate the shard on a "ops-based-recovery-or-nothing" basis, never performing a file-based recovery. Marking this as "help wanted".

Seems that "BaseGatewayShardAllocator" already done this validation check in function "allocateUnassigned", but finally rejected by DiskThresholdDecider which checks low-watermark settings. 

Can I start working on this issue?

**Comment by DaveCTurner** [comment]
Sure, a PR would be welcome.

Note that the checks in the gateway shard allocators are not the only concern here - the `RecoverySourceHandler` may independently decide to perform a file-based recovery, and this should be forbidden if there isn't enough disk space.

**Comment by wangkhc** [comment]
> Sure, a PR would be welcome.
> 
> Note that the checks in the gateway shard allocators are not the only concern here - the `RecoverySourceHandler` may independently decide to perform a file-based recovery, and this should be forbidden if there isn't enough disk space.

So a simple way to avoid this file-based recovery is to pre-check whether local existing shard data needs a full file copy from source shard. Do you think it's ok to send another tcp request to recovery-source shard to gather some information for validation? Like what we do in RecoverySourceHandler, pre checking whether target is sequenceNumberBasedRecovery

**Comment by DaveCTurner** [comment]
We already make such a check in `ReplicaShardAllocator#canPerformOperationBasedRecovery`, but it must be checked again in `RecoverySourceHandler` since the `ReplicaShardAllocator` is always working on potentially-stale data.

**Comment by wangkhc** [comment]
@DaveCTurner Great improvement! So let's confirm that there are two things left to do: Firstly reuse ReplicaShardAllocator's decision on this reusable store data in DiskThresholdDecider to skip watermark validation; Secondly peerRecoveryTarget should pre-check disk usage before receiving phase1 data. Is that right?

**Comment by DaveCTurner** [comment]
>  Firstly reuse `ReplicaShardAllocator`'s decision on this reusable store data in `DiskThresholdDecider` to skip watermark validation

Yes, that sounds good.

> Secondly `peerRecoveryTarget` should pre-check disk usage before receiving phase1 data.

I'm not so sure about this bit, but it might be a good approach. Bear with me while I discuss with some colleagues.

**Comment by DaveCTurner** [comment]
We came up with an alternative idea that seems simpler and more generally useful:

1. Cancel ongoing recoveries (and clean up partial transfers) when a node exceeds the high watermark.

2. Always ignore the low watermark in the `ReplicaShardAllocator`. This allocator only acts where there is a shard copy already present and we can be more optimistic in assuming that this copy is mostly up-to-date.

Cancelling recoveries protects us from an over-large operations-based recovery filling up the disk while also allowing us to safely attempt a hopefully-small file-based recovery, and meshes nicely with the goal of the disk-based shard allocator to keep all nodes below the high watermark.

I would recommend two separate PRs for these two ideas, in this order.

**Comment by wangkhc** [comment]
@DaveCTurner Sounds good to me, I'll start working on this two idea :)

**Comment by wangkhc** [comment]
@DaveCTurner First PR has submitted #50367

**Comment by wangkhc** [comment]
> We came up with an alternative idea that seems simpler and more generally useful:
> 
> 1. Cancel ongoing recoveries (and clean up partial transfers) when a node exceeds the high watermark.
> 2. Always ignore the low watermark in the `ReplicaShardAllocator`. This allocator only acts where there is a shard copy already present and we can be more optimistic in assuming that this copy is mostly up-to-date.
> 
> Cancelling recoveries protects us from an over-large operations-based recovery filling up the disk while also allowing us to safely attempt a hopefully-small file-based recovery, and meshes nicely with the goal of the disk-based shard allocator to keep all nodes below the high watermark.
> 
> I would recommend two separate PRs for these two ideas, in this order.

Hi @DaveCTurner , since the first PR is still pending review, can I start working on the second PR? :)

**Comment by wangkhc** [comment]
> Always ignore the low watermark in the `ReplicaShardAllocator`

I've done some investigation on the second idea referenced above, but I didn't find an elegant way to achieve this goal. I tried two ways:

1. When `ReplicaShardAllocator` found a `NO` decision was made by `DiskThresholdDecider`, and the explanation containing `the node is above the low watermark`, skip this decision and continue allocation. This is kind of a hack choice I think. 

2. Set a variable in `DiskThresholdDecider` from outside to skip low-watermark validation, but I didn't figure out where to place this variable.

@DaveCTurner Can you give me some advice on this? Thank you :)

**Comment by DaveCTurner** [comment]
I'm closing this in favour of #56578 since they're fundamentally the same issue and #56578 is slightly more general. It's still a genuine problem, but there's no need to keep both of these issues open to track it.
