### ISSUE TITLE
It have a high Disk occupancy for updateByQuery frequently

### ISSUE THREAD

**Issue by yida-lxw** [elastic/elasticsearch#50011]
when I add a new extension word into the IKAnalyzer, and then I save them into the MYSQL DB, I also send a message to the RabbitMQ at the same time. Then another service will consume the message and work with the updateByQuery method to update the Elasticsearch Index Data. But It will hit a high Disk occupancy  after adding a  extension word. because we need to update at lease 1000 document which related to the word.  the amount of instantaneous updates to the index will be very large If I add words at a slightly faster rate, and the number of segment files will continue to go up.but we can't merge the segments frequently. So I was caught in conflict. Is there any way to fit the scene of updating frequently in elasticsearch,and it is not affected to the Query latency at the same time?
Here are some code fragments I used in my project：
```BoolQueryBuilder boolQueryBuilder = QueryBuilders.boolQuery();
        for (String keyword:keywordList) {
            boolQueryBuilder.should(QueryBuilders.matchPhraseQuery("searchkeyword", keyword)
                    .slop(Integer.parseInt(CentralConfig.getProperty("index.refresh.index_keyword.slop","0"))));
        }
        boolQueryBuilder.minimumShouldMatch(1);

        Map<String,List<String>> refreshMap = Maps.newHashMap();

        SearchResponse response = client.prepareSearch(Const.INDEX_KEYWORD)
                .setSize(1000).setQuery(boolQueryBuilder).setFetchSource(new String[]{"refid", "type"}, null).setScroll("10m")
                .execute().actionGet();

        long totalHits = response.getHits().getHits().length;
        String scrollId = response.getScrollId();
        while (totalHits > 0) {
            putRefreshId(response,refreshMap);
            SearchResponse subResponse = client.prepareSearchScroll(scrollId).setScroll("10m").execute().actionGet();
            totalHits = subResponse.getHits().getHits().length;
            scrollId = subResponse.getScrollId();
            response=subResponse;
        }
       
        if (MapUtils.isEmpty(refreshMap)){
            return;
        }
       //refresh the index by UpdateByQuery
        for (Map.Entry<String,List<String>> entry : refreshMap.entrySet()){
            BulkByScrollResponse updateResponse = UpdateByQueryAction.INSTANCE.
                    newRequestBuilder(client).source(entry.getKey())
                    .abortOnVersionConflict(true)
                    .execute()
                    .actionGet();
            LOGGER.info("update index : {} , refresh size : {}",entry.getKey(),updateResponse.getUpdated());```

**Comment by yida-lxw** [comment]
Here is a screenshot from my Kibana at the time of failure occuring on my Elasticsearch Cluster:
![12681575968423_ pic_hd](https://user-images.githubusercontent.com/12723117/70514747-20924c80-1b6f-11ea-8788-263cc0236a0f.jpg)

**Comment by cbuescher** [comment]
Hi @yida-lxw! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by yida-lxw** [comment]
> Hi @yida-lxw! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

Thank you all the same, but I can't open it. cause it was blocked in china.
