### ISSUE TITLE
[Docs] Templates do not apply when reindexing

### ISSUE THREAD

**Issue by cachedout** [elastic/elasticsearch#50046]
In [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) it says:

`You must set up the destination index before calling _reindex. Reindex does not copy the settings from the source index. Mappings, shard counts, replicas, and so on must be configured ahead of time.`

It seems upon testing that this also means that an existing template will not apply settings to an index if it is re-indexed without first creating the index.

I suggest that we update this notice to explicitly state that a template will not be applied during a re-indexing operation. (This should be verified by the ES team, but that seems to me to be how this works.)

**Comment by jrodewig** [comment]
Closing. Index templates do apply to indices during a reindex. See #60539.
