### ISSUE TITLE
org.elasticsearch.common.UUIDTests.testCompression Fails

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#50048]
Multiple build failures due to this test failure

Reproduces reliably with: 
```
./gradlew ':server:test' --tests "org.elasticsearch.common.UUIDTests.testCompression" \
  -Dtests.seed=4713F1387D472105 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-BA \
  -Dtests.timezone=Africa/Asmera \
  -Dcompiler.java=12
```
Additional reproduce line:
```
./gradlew ':server:test' --tests "org.elasticsearch.common.UUIDTests.testCompression" \
  -Dtests.seed=5AD9FA10D2CE6D04 \
  -Dtests.security.manager=true \
  -Dtests.locale=bg \
  -Dtests.timezone=Pacific/Truk \
  -Dcompiler.java=12
```

Builds: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux-6&&immutable/443/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-12&&immutable/443/console

Failure:
```
org.elasticsearch.common.UUIDTests > testCompression FAILED
    java.lang.AssertionError:
    Expected: a value less than <14.0>
         but: <15.22106> was greater than <14.0>
        at __randomizedtesting.SeedInfo.seed([4713F1387D472105:BC26D75E7799D156]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.common.UUIDTests.testCompression(UUIDTests.java:123)
```

**Comment by rjernst** [comment]
Timing wise this seems possibly related to the update to Lucene 8.4.0 snapshot (https://github.com/elastic/elasticsearch/pull/50016). @jpountz Could you have a look?

**Comment by rjernst** [comment]
Note I was not able to reproduce this locally. I don't have any direct evidence of it being due to the Lucene upgrade, but the compression clearly seems to be fluctuating based on some external factors, which is surprising since the serial merge scheduler is used to ensure somewhat deterministic behavior. Some numbers from my own testing:

```
CI:
100000 docs indexed at 1000 docs/s required 1.6mb bytes of disk space, or 16.93854 bytes per document. Took: 478ms.

Local, before 8.4.0 snapshot:
100000 docs indexed at 1000 docs/s required 1.2mb bytes of disk space, or 12.61174 bytes per document. Took: 492ms.

Local, after 8.4.0 snapshot:
100000 docs indexed at 1000 docs/s required 1.3mb bytes of disk space, or 14.09807 bytes per document. Took: 479ms.
```

**Comment by jpountz** [comment]
I'm looking into it.

**Comment by jpountz** [comment]
This seed seems to make the issue likely reproducable: `-Dtests.seed=EDEB762CDE5FAC81`.
