### ISSUE TITLE
Elasticsearch _recovery api resets percent done

### ISSUE THREAD

**Issue by jmwilkinson** [elastic/elasticsearch#50055]
**Elasticsearch version** (`bin/elasticsearch --version`):  5.4

**Plugins installed**: 
ingest-geoip | v5.4.0 | Ingest processor that uses looksup geo data based on ip adresses using the Maxmind geo database
ingest-user-agent | v5.4.0 | Ingest processor that extracts information from a user agent
x-pack | v5.4.0 | Elasticsearch Expanded Pack Plugin
_Note:_ I don't think any of those plugins are active (or related)

**JVM version** (`java -version`): OpenJDK 64-Bit Server VM (1.8.0_201)

**OS version** (`uname -a` if on a Unix-like system): Docker running on Centos 7

**Description of the problem including expected versus actual behavior**:

There are two parts to this:
1. **Actual:** After tagging indices as "warm", the cluster will automatically begin moving shards, which can be tracked via the `_recover` API. Occasionally, this API reset from some known percentage (like `32%`) on both files and and the bytes reporting back to `0%`. On subsequent calls, the files reporting will usually jump back to pretty close to where it was, so it might go `72%` -> `0%` -> `71%`. But the bytes will continue from `0%`.
This may be an issue that was fixed in subsequent versions, but I have been unable to find any info on it.
Example Response section:
```
"index": {
                    "size": {
                        "total_in_bytes": 0,
                        "reused_in_bytes": 0,
                        "recovered_in_bytes": 0,
                        "percent": "0.0%"
                    },
                    "files": {
                        "total": 0,
                        "reused": 0,
                        "recovered": 0,
                        "percent": "0.0%"
                    },
                    "total_time_in_millis": 0,
                    "source_throttle_time_in_millis": 0,
                    "target_throttle_time_in_millis": 0
                },
```
**Expectation:** The expectation is that once started, the percent recovered would never drop to 0 and only continuously increase.
2. If this is expected behavior, there is no documentation on what is happening or why it is happening, or what the percentages actually mean. It feels like there should be more of an explanation as to what is going on.

**Steps to reproduce**:

1. Create a 5-node cluster version 5.4 (this has not been tested on later versions). Tag two nodes with the `box_type=warm`, and the others with `box_type=hot`
2. Create any index, giving it the setting `"index.routing.allocation.require.box_type": "hot"`, with 1 shard & 1 replica.
3. Write about 20GB of data to that index
4. PUT the setting `"index.routing.allocation.require.box_type": "warm"`
5. Begin polling the `_recovery?active_only=true` endpoint, and look at `shard.index` sections 

**Notes**

I realize this is an older version of elasticsearch, and the solution *may* simply be to upgrade (which is an ongoing process). However, if that is the case, I would like to know if this was a known issue that has been closed with an explanation, or if it is an unknown behavior and we're simply _hoping_ it got fixed or became irrelevant somewhere along the way.

Ideally, I also think it would be good to update the docs with maybe a bit more information as to what the recovery API actually means. If documentation already exists on this, sorry, I wasn't able to find it.

**Comment by ywelsch** [comment]
I have not seen any kind of similar reports on any recent version of ES, which is why I'm closing this.
