### ISSUE TITLE
[Monitoring] [UI] Multiple logstash pipelines aggregations are broken

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#50054]
See https://github.com/elastic/elasticsearch/issues/44914#issuecomment-564161902

Something changed recently in ES, triggering a slew of test failures (https://github.com/elastic/kibana/issues/52470, https://github.com/elastic/kibana/issues/52471, https://github.com/elastic/kibana/issues/52476,https://github.com/elastic/kibana/issues/52476). 

The culprit seems to be using `bucket_script` aggregations somewhere under a `nested` aggregation. In this scenario, the `bucket_script` aggregation doesn't seem to ever run, as the response does not contain the data.

(Partial copy-paste from the comment linked above)
See this example here: https://gist.github.com/chrisronline/836dbbdb594d5848538e412236f32147

For 7.5 and below, the output is:
```
{
  "aggregations" : {
    "date_histo" : {
      "buckets" : [
        {
          "in_nested" : {
            "types" : {
              "buckets" : [
                {
                  "bs_value" : {
                    "value" : 1.0
                  }
                }
              ]
            }
          },
          "high_level_bs_value" : {
            "value" : 0.0
          }
        }
      ]
    }
  }
}
```

For 7.6 and above, the output is:
```
{
  "aggregations" : {
    "date_histo" : {
      "buckets" : [
        {
          "high_level_bs_value" : {
            "value" : 0.0
          }
        }
      ]
    }
  }
}
```

Luckily, we have good test coverage for this, but this needs to be a blocker for 7.6

I've pinged @polyfractal about this and he is currently investigating. It sounds like this is also affecting other aggregation types too.

cc @elastic/stack-monitoring

**Comment by polyfractal** [comment]
I had a look at this last night, the changes in https://github.com/elastic/elasticsearch/pull/45796/ neglected to invoke pipeline reductions on the sub-aggs in SingleBucket aggs, meaning any pipeline under `nested`, `filter`, `global`, etc all fail to execute.

I have a fix and am writing up some tests, will get a PR up today I think.
