### ISSUE TITLE
Security should not reload files that haven't changed 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#50063]
In security we currently monitor a set of files for changes
- `config/role_mapping.yml` (or alternative configured path)
- `config/roles.yml`
- `config/users`
- `config/users_roles`

We use the `ResourceWatcherService` to detect changes and then reload structures and/or clear caches.

In some cases we detect that a "file change" has resulted in no actual changes to the stored content, and do nothing, but there are cases where simply touching a file will clear caches.

It would be preferable to only clear caches if the file change actually caused some internal structure to change (e.g a user was added/removed/modified).

**Comment by j-bean** [comment]
Can I start working on this?

**Comment by albertzaharovits** [comment]
Thank you for your interest in contributing to the project @j-bean !

Yes, you may start working on it.
