### ISSUE TITLE
[CI] BuildPluginIT.testInsecureIvyRepository failure

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#50064]
**Elasticsearch version** : master

**JVM version** (`java -version`):
openjdk 12 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

**OS version**:
Mac OS X 10.13.6 (x86_64)

**Gradle version**: 5.6.3

**Description of the problem including expected versus actual behavior**:
When executinig ./gradlew check, BuildPluginIT.testInsecureIvyRepository task failed with an exception:

org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.gradle.build-scan', version: '2.4.2', artifact: 'com.gradle:build-scan-plugin:2.4.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle TestKit (classpath: /Users/gaobellen/WorkSpace/githome/elasticsearch-6.0/buildSrc/build/classes/java/main...
- Plugin Repositories (could not resolve plugin artifact 'com.gradle:build-scan-plugin:2.4.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by gaobinlong** [comment]
But I realy found a build-scan-plugin jar in the gradle cahces dir:/Users/gaobellen/.gradle/caches/modules-2/files-2.1/com.gradle/build-scan-plugin/2.4.2/91027a52970e93d012fc96bcc683ed32120cef20, what's wrong here, I got no answer in the forum: [discuss.elastic.co](discuss.elastic.co).

**Comment by jasontedor** [comment]
This doesn’t feel like a build bug. Can you link to your forum post (the link you provided previously 404s) and someone will try to help you there?
