### ISSUE TITLE
GET _cat/nodes?local is not completely local

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#50088]
The cat nodes API performs a `ClusterStateAction` then a `NodesInfoAction`. It accepts the `?local` parameter and passes this to the `ClusterStateAction` but this parameter has no effect on the `NodesInfoAction`. This is surprising, because `GET _cat/nodes?local` looks like it might be a completely local call but in fact it still depends on every node in the cluster.

I think the `?local` parameter does not make sense on this API and we should remove it.

**Comment by DaveCTurner** [comment]
We discussed this as a team today and agreed to deprecate the `?local` parameter to `GET _cat/nodes` in 7.x and remove it in 8.0.

**Comment by olegbonar** [comment]
Hi @DaveCTurner! May I work on this one? Any hints are appreciated.

**Comment by DaveCTurner** [comment]
Sure, go ahead. See e.g. https://github.com/elastic/elasticsearch/pull/49458 for another example of how to deprecate something properly.

**Comment by DaveCTurner** [comment]
Closed by #50594 and #50499.
