### ISSUE TITLE
[DOCS] Replace CONTAINS (deprecated) with INTERSECTS when doing Point in Polygon

### ISSUE THREAD

**Issue by krsarmiento** [elastic/elasticsearch#50099]
When upgrading ElasticSearch we noticed that CONTAINS relation is now deprecated.

<img width="693" alt="Capture d’écran 2019-12-11 à 3 02 35 PM" src="https://user-images.githubusercontent.com/1755939/70656024-47ac5500-1c27-11ea-8f93-d0da5e0c1499.png">

But in the documentation there's no indication on how to proceed with newer versions if we want to do PIP (Point-in-polygon) operations. We have done some testing and it appears that we can safely use INTERSECTS but we're not 100% sure. Is this the way to proceed when we want to find points inside a polygon? If so, can we add that to the documentation?

**Comment by iverase** [comment]
CONTAINS has not been departed but it was not supported for BKD-backed geo-shapes until 7.6. It is supported. I am closing this issue. please feel free to reopen if you have other opinion.
