### ISSUE TITLE
es suggest 不能使用 结果options字段总是空的

### ISSUE THREAD

**Issue by CodeManHappy** [elastic/elasticsearch#50116]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by pgomulka** [comment]
@CodeManHappy can you please provide details and steps to reproduce a problem

**Comment by CodeManHappy** [comment]
first ：es data  is：
    "hits": [
      {
        "_index": "website",
        "_type": "blog",
        "_id": "123",
        "_score": 1.0,
        "_source": {
          "title": "My first blog entry",
          "text": "Just trying this out...",
          "date": "2019/12/13"
        }
      },
      {
        "_index": "website",
        "_type": "blog",
        "_id": "1x8d_W4BP1r3TdByc8bp",
        "_score": 1.0,
        "_source": {
          "title": "M",
          "text": "a",
          "date": "2019/12/13"
        }
      },
      {
        "_index": "website",
        "_type": "blog",
        "_id": "2B8d_W4BP1r3TdBy28YS",
        "_score": 1.0,
        "_source": {
          "title": "My",
          "text": "aa",
          "date": "2019/12/13"
        }
      },
      {
        "_index": "website",
        "_type": "blog",
        "_id": "2R8e_W4BP1r3TdByGcZL",
        "_score": 1.0,
        "_source": {
          "title": "My first",
          "text": "aa a",
          "date": "2019/12/13"
        }
      },
      {
        "_index": "website",
        "_type": "blog",
        "_id": "2h8e_W4BP1r3TdByb8a-",
        "_score": 1.0,
        "_source": {
          "title": "last My first",
          "text": "b aa c",
          "date": "2019/12/13"
        }
      }

my suggest request is：

{
	"suggest": {
    "my-suggest-1" : {
      "text":"My first",
      "term" : {
        "field" : "title"
      }
    }
  }
}

then the response is :
    "suggest": {
        "my-suggest-1": [
            {
                "text": "my",
                "offset": 0,
                "length": 2,
                "options": []
            },
            {
                "text": "first",
                "offset": 3,
                "length": 5,
                "options": []
            }
        ]
    }
the all options is null , I don't know why

**Comment by CodeManHappy** [comment]
thanks. you can help analysis this. issue ,this my first to use es tool

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by CodeManHappy** [comment]
Sorry. Thanks




| |
温泽鹏
|
|
theworldinmyheart@163.com
|
签名由网易邮箱大师定制


在2019年12月13日 16:42，Przemyslaw Gomulka<notifications@github.com> 写道：

Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the forums. If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the forums
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
