### ISSUE TITLE
Docker build task doesn't track any inputs

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#50125]
PR #49613 changed the Docker build to avoid rebuilding if the outputs are up-to-date. However, the build task isn't tracking any _inputs_ here. For example, after running `assemble`, if you change the `Dockerfile`, things are still `UP-TO-DATE`, which is clearly incorrect. We should be tracking the `Dockerfile`, as well as anything else we include in the image as inputs to this task otherwise folks are liable to get unreliable behavior.

_Originally posted by @mark-vieira in https://github.com/elastic/elasticsearch/pull/49613#issuecomment-561340397_

**Comment by mark-vieira** [comment]
This issue was addressed by https://github.com/elastic/elasticsearch/pull/49814.
