### ISSUE TITLE
[CI] XPackRestIT "license/30_enterprise_license/Installing enterprise license" failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#50151]
This license test has just started failing in our `7.x` and `master` [release tests build](https://elasticsearch-ci.elastic.co/view/Elasticsearch%20master/job/elastic+elasticsearch+master+release-tests/) in CI.

Here's an example of the failure: https://gradle-enterprise.elastic.co/s/fw3temsfbwr2a/tests/fcijb24gqtmnc-d25rdgodfcm42

Not sure if we broke something or perhaps license key we store in vault for the purposes of this test is no longer correct.

**Comment by tvernum** [comment]
The failing test is new - I'm not sure why it passed PR-CI but is failing now.

**Comment by tvernum** [comment]
Ah, sorry I missed the "release tests" bit. That makes sense then, I just need to work out how the other license tests work around the release key issue.
