### ISSUE TITLE
Make script cache and compilation limits per context

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#50152]
Currently, we have setting to apply a max for the script cache and settings to determine the max rate of compilation. These apply to all script contexts. We should change the settings to be per script context as each context has different needs.

Relates to https://github.com/elastic/elasticsearch/issues/49763

**Comment by stu-elastic** [comment]
In `ScriptService`
`SCRIPT_CACHE_SIZE_SETTING` and `SCRIPT_MAX_COMPILATIONS_RATE`, `SCRIPT_CACHE_EXPIRE_SETTING` needs to be per context as well as `Cache<CacheKey, Object> cache;` along with `scriptMetrics`, which is where they are being tracked.

``SCRIPT_MAX_COMPILATIONS_RATE` needs to be able to be unlimited.

In `compile` we can sychronize on the context rather than `this`.  Can add arbitrary private object used for locking.

Idea: encapsulate these into a `ContextCompiler`, move all compile logic into here.

**Comment by stu-elastic** [comment]
Code staging:
1) General context compiler
2) Settings changes for specific compilers only
    fallback to general context compiler
3) Update stats API

Behavior:
If general settings, use general compiler and deprecate log
If no general settings use context specific
If general settings and context specific, error
 -> cluster update settings for context specific and general then context specific rejected

**Comment by stu-elastic** [comment]
Should we disable caching all together if a user sets an unlimited compilation rate?

**Comment by stu-elastic** [comment]
Having `script` and `script_cache` in `_node/stats` is redundant.  Here's the value of `_node/stats` in 7.x:
```json
      "script" : {
        "compilations" : 172,
        "cache_evictions" : 72,
        "compilation_limit_triggered" : 0
      },
```

Here's it in 8.x right now:
```json  
      "script_cache": {                                                      
        "sum": {                      
          "compilations": 1,                                                 
          "cache_evictions": 0,                                              
          "compilation_limit_triggered": 0                                   
        },                            
        "contexts": [                                                        
          {                           
            "context": "aggregation_selector",                               
            "compilations": 0,                                               
            "cache_evictions": 0,                                            
            "compilation_limit_triggered": 0                                 
          },                                  
```

We will remove `node_stats` in 8 and hoist `sum` to the top level.  Here's what we'll have:
```json  
      "script_cache": {                          
        "compilations": 1,
        "cache_evictions": 0,
        "compilation_limit_triggered": 0,
        "contexts":[
          {
            "context": "aggregation_selector",                               
            "compilations": 0,                                               
            "cache_evictions": 0,                                            
            "compilation_limit_triggered": 0                                 
          },                                  
```
 
This keeps the format the same between 7 and 8 so we can easily drop `node_stats`.  Also the `sum` is unnecessary indirection.
