### ISSUE TITLE
Add tests for IntervalsSourceProvider implementations

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#50150]
The implementations are partialy tested though the IntervalQueryBuilderTests and other tests, but since the class supports xContent and wire serialization, some dedicated tests (maybe extending AbstractWireTestCase, AbstractXContentTestCase or both) might be useful.

**Comment by Hohol** [comment]
May I take this?

**Comment by cbuescher** [comment]
@Hohol sure, maybe start with one of the simpler ones to get yourself familiarized with the kind of serialization testing we are typically doing. I think IntervalsSourceProvider.Prefix is one of the easiest of the implementations. I think a test for this should try to extend AbstractSerializingTestCase that already takes away some boilerplate code for creating random instances and test that both our xContent serialization (what typically is passed as JSON through the REST layer) and the internal serialization works. You can take a look at e.g. at `TaskInfoTests` for inspiration how some of these tests look like and work from there. Hope that helps.
