### ISSUE TITLE
Multiple fields are returned after aggregation

### ISSUE THREAD

**Issue by ZhiHao1** [elastic/elasticsearch#50161]
``
"source_data_school_achievements_of_the_paper" : {
            "properties" : {
              "school_achievements_of_the_paper" : {
                "type" : "nested",
                "properties" : {
                  "abstract" : {
                    "type" : "keyword"
                  },
                  "account" : {
                    "type" : "keyword"
                  },
                  "achievements_of_the_paper_url" : {
                    "type" : "keyword"
                  },
                  "author" : {
                    "type" : "keyword"
                  },
                  "co_author" : {
                    "type" : "keyword"
                  },
                  "first_author" : {
                    "type" : "keyword"
                  },
                  "first_author_handle" : {
                    "type" : "keyword"
                  },
                  "included_publications" : {
                    "type" : "keyword"
                  },
                  "issn" : {
                    "type" : "keyword"
                  },
                  "issue_number" : {
                    "type" : "keyword"
                  },
                  "keyword" : {
                    "type" : "keyword"
                  },
                  "page_range" : {
                    "type" : "keyword"
                  },
                  "publication_time" : {
                    "type" : "date"
                  },
                  "publications" : {
                    "type" : "keyword"
                  },
                  "title" : {
                    "type" : "keyword"
                  },
                  "type_of_papers" : {
                    "type" : "keyword"
                  },
                  "user_id" : {
                    "type" : "keyword"
                  },
                  "volume_number" : {
                    "type" : "keyword"
                  }
                }
              }
            }
          }
``

error

``
GET es_userinfo_ip3/userinfo/_search
{
  "size": 0,
  "aggs": {
    "path": {
      "nested": {
        "path": "source_data_school_achievements_of_the_paper.school_achievements_of_the_paper"
      },
      "aggs": {
        "journalGroup": {
          "terms": {
            "field": "source_data_school_achievements_of_the_paper.school_achievements_of_the_paper.publications",
            "order": {
              "count": "asc"
            }
          },
          "aggs": {
            "count": {
              "cardinality": {
                "field": "source_data_school_achievements_of_the_paper.school_achievements_of_the_paper.title"
              }
            }
          }
        },
        "cfsfsdgv": {
          "top_hits": {
            "_source": ["source_data_school_achievements_of_the_paper.school_achievements_of_the_paper.issn"]
          }
        }
      }
    }
  }
}
``

``
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Cannot execute inner hits. One or more parent object fields of nested field [source_data_school_achievements_of_the_paper.school_achievements_of_the_paper] are not nested. All parent fields need to be nested fields too"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "es_userinfo_ip3",
        "node": "c1up1y1GSZuClRbX3X1qmQ",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Cannot execute inner hits. One or more parent object fields of nested field [source_data_school_achievements_of_the_paper.school_achievements_of_the_paper] are not nested. All parent fields need to be nested fields too"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Cannot execute inner hits. One or more parent object fields of nested field [source_data_school_achievements_of_the_paper.school_achievements_of_the_paper] are not nested. All parent fields need to be nested fields too",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Cannot execute inner hits. One or more parent object fields of nested field [source_data_school_achievements_of_the_paper.school_achievements_of_the_paper] are not nested. All parent fields need to be nested fields too"
      }
    }
  },
  "status": 400
}
``

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. 
This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
