### ISSUE TITLE
can interal id initied in yml file?

### ISSUE THREAD

**Issue by kevinsingapore** [elastic/elasticsearch#50162]
1、according to the offical website handbook, we can change the password of interal id（elastic/kiabna..) ，and use the curl mommand；
2、the question:  can i init the interal id password in elasticsearch.yml?

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
