### ISSUE TITLE
Don't fallback to anonymous user when anonymous access is enabled for invalid access token/api key

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#50171]
Currently, when anonymous access is enabled, a request with an invalid/expired/wrong access token or an API Key would fallback to being authenticated as the anonymous user, as if the request wouldn't contain any Authorization header. This might be a confusing behavior for users and we should be explicit in our responses about treating no credentials and wrong credentials differently, even when anonymous access is enabled.

**Comment by kobelb** [comment]
Hey @jkakavas, is there any chance of getting this addressed for 7.6? Otherwise, Kibana's Kerberos auth provider isn't going to work properly after a token expires for long enough that it's purged from the `.security-tokens-7` index.
