### ISSUE TITLE
SQL: CASTing passes instead of throwing an exception

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#50191]
`SELECT (CAST('bla' AS DATE) IS NOT NULL)`

yields

```
CAST('bla' AS DATE) IS NOT NULL
-------------------------------
true    
```

But running `SELECT CAST('bla' AS DATE)` throws an (expected) exception:

```
                "type": "sql_illegal_argument_exception",
                "reason": "cannot cast [bla] to [date]: Text 'bla' could not be parsed at index 0"
```

In reality, both cases should have thrown the sql_illegal_argument_exception. In the first case, though, `bla` is evaluated as not being null and the optimizer is already returning `TRUE` for `IS NOT NULL`.

**Comment by matriv** [comment]
`master` : 671e07a931cd828661e226cba22a5d38804a17a5
`7.x` : f1a6b675f7421796b07e4f6c85249f1e7a83a84a
`7.5` : 56a417687506284cf2221dad51dc6c6b60d3a695
`6.8` : a2b753239b277fcb3d2f6ca868983619c10584c0
