### ISSUE TITLE
_count is slower in 7.x than 6.x

### ISSUE THREAD

**Issue by awick** [elastic/elasticsearch#50198]
Started in https://discuss.elastic.co/t/count-api-performance-downgraded-after-cluster-upgrade-from-6-8-4-to-7-5/210783

Summary, _count is definitely slower with 7.x than 6.x.  It seems like it might have to do with the number of indices/shards involved, like there is O(n^2) with a loop inside a loop or something.

Our old way with _count on 7.5.0

```
time curl -H "Content-Type: application/json" -s --insecure https://localhost:9200/_count
{"count":182116470792,"_shards":{"total":20107,"successful":20107,"skipped":0,"failed":0}}

real	0m6.795s
```
_cat/count is the same on 7.5.0

```
time curl -H "Content-Type: application/json" -s --insecure 'https://localhost:9200/_cat/count?format=json'
[{"epoch":"1575661460","timestamp":"19:44:20","count":"182117127449"}]```

real	0m6.523s
```

 /_cat/indices is faster on 7.5.0, so my current work around is to just add up the indices myself.

```
time curl -H "Content-Type: application/json" -s --insecure 'https://localhost:9200/_cat/indices?h=index,docs.count&format=json' > /dev/null

real	0m2.351s
```

Interesting if I do partial counts like the following on 7.5
```
time curl  'https://localhost:9200/sessions2-18*/_count' = 1s     (435 indices)
time curl  'https://localhost:9200/sessions2-19*/_count' = 3s    (1160 indices)
time curl  'https://localhost:9200/sessions2-18*,sessions2-19*/_count' = 6s
```

I would expect the last to take 4s instead of 6

I don't have timings for 6.x, but I do know this used to be under 2s because it wasn't the slowest part of all my queries, and now it is.

**Comment by jimczi** [comment]
I answered in the the [forum](https://discuss.elastic.co/t/count-api-performance-downgraded-after-cluster-upgrade-from-6-8-4-to-7-5/210783) so I hope you don't mind if I close this. 
We try to keep github for verified bugs and feature requests so let's continue to investigate in the forum and we'll open a specific issue later if we find something to improve or fix.
