### ISSUE TITLE
Improve refresh execution time by warming up large merged segments

### ISSUE THREAD

**Issue by zhichen** [elastic/elasticsearch#50226]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.2

**Description of the problem and Optimization suggestions**

When using Alibaba Cloud ES, the user occasionally encounters that after writing the data successfully, it takes several seconds to be queried, even if the refresh_interval he set is 1s or 500ms. He hopes to query the written data faster.

We found that this problem usually occurs when merge produces large segments larger than 500MB. Because reopen is serial, reopening of a large merged segment will block the refresh of the new segment, causing newly written data to take a few seconds to be queried.

  Here is an optimization. For large segments (over 500MB), you can use IndexWriterConfig.setMergedSegmentWarmer to warm up to improve the efficiency of reopening, so as to ensure that the data refresh execution time is within 1s.

**Comment by zhichen** [comment]
No one responded to this issue for a week. Does anyone help to see if this optimization is appropriate? Is there a better way to shorten the refresh execution time?

**Comment by dnhatn** [comment]
Yes, your proposal can be an option, but we first need to understand the bottleneck. Do you enable [eager global ordinals](https://www.elastic.co/guide/en/elasticsearch/reference/master/eager-global-ordinals.html#eager-global-ordinals) for those indices? Can you share the [hot threads](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html) when you suspect refresh is slower than the expectation? Thank you!

**Comment by zhichen** [comment]
@dadoonet Thank you for your reply. I did not set eager global ordinals, and I also understand that setting eager global ordinals will greatly affect the refresh execution time, but I am not targeting this scenario. 
     My hot_threads are usually in IndexWriter.getReader (r = StandardDirectoryReader.open (this, segmentInfos, applyAllDeletes, writeAllDeletes)), when you suspect refresh is slower than the expectation.
     At that time, I only recorded part of the hot_threads. If necessary, I can intercept the complete hot_threads after recurring the problem.
```
4/10 snapshots sharing following 27 elements
       app//org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:106)
       app//org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:493)
       app//org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:294)
       app//org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:269)
       app//org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:259)
       app//org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
       app//org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
       app//org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
       app//org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
       app//org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
```


I tried to modify the lucene source code and type the time overhead of StandardDirectoryReader.open. When the merged segment exceeds 2G, the time of StandardDirectoryReader.open exceeds 2S.

**Comment by dnhatn** [comment]
> At that time, I only recorded part of the hot_threads. If necessary, I can intercept the complete hot_threads after recurring the problem.

It will be clearer if we have a full picture of the hot threads.

**Comment by dliappis** [comment]
No further feedback received. @zhichen if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
