### ISSUE TITLE
Rollup_search requires more than read-only permissions

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#50245]
In searches against rollup indices using the `_rollup_search` api, users need at least `manage` privileges for what should really be a `read` only operation.
This was reported on 6.8 and I reproduced it but this may apply to other versions too.
It's possible `read` and `view_index_metadata` may be required privileges but write-capable permissions should really not be required here.

**Comment by gbanasiak** [comment]
Also present in 7.5.1.
