### ISSUE TITLE
Document how to use PKCS#12 keystore with REST client

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#50255]
**Describe the feature**:

In "Encrypted communication" [1] we document how to configure the Java REST client to us TLS. This involves configuring the client to use a Java Keystore:

```
KeyStore truststore = KeyStore.getInstance("jks")
```

However, we don't provide guidance on how to actually build a Java Keystore. The `elasticsearch-certutil` docs [2] show users how to build a PKCS#12 keystore-- so if our example code snippet demonstrated how to use a `.p12` (in lieu of, or in addition to a `.jks`) things would align better.

[1] https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html

**Comment by tvernum** [comment]
Thanks @n0othing.
Duplicate of https://github.com/elastic/elasticsearch/issues/44202
