### ISSUE TITLE
Check contexts for nondeterminism to ensure cacheability

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#50341]
Related: #49466 which handles nondeterminism for whitelist methods

As a future-proofing measure, we should detect when contexts provide non-deterministic classes and methods.

A sketch:
`ScriptClassInfo` we need to check the `executeArguments` for nondeternism.  So, in `SClass.analyze` when creating the `ScriptRoot` we can check to see if `executeArguments` is all deterministic.  This can be done in `ScriptClassinfo` ie add `ScriptClassinfo.areExecuteArgumentsDeterministic` or inside `SClass`.  The result should be passed to the `ScriptRoot` instance via `markNonDeterministic`.

**Comment by jdconrad** [comment]
Done.
