### ISSUE TITLE
[CI] TimeSeriesLifecycleActionsIT testHistoryIsWrittenWithFailure 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#50353]
A number of failures on the master branch in the last day:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2/331/console
https://gradle-enterprise.elastic.co/s/clxgk64w274hw

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/460/console
https://gradle-enterprise.elastic.co/s/ptsngwrgxzn64

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-6&&immutable/460/console
https://gradle-enterprise.elastic.co/s/jdmkulxql5ris

```
java.lang.AssertionError: 

Expected: a value equal to or greater than <1>
     but: <0> was less than <1>

at __randomizedtesting.SeedInfo.seed([9BF20B84CA3FCF0E:49B89F3F80A0B0A0]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1157)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithDeletion$72(TimeSeriesLifecycleActionsIT.java:1103)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:866)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion(TimeSeriesLifecycleActionsIT.java:1102)
```

Does not reproduce:
```
gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess" \
  -Dtests.seed=DA4311B28F41839E \
  -Dtests.security.manager=true \
  -Dtests.locale=id-ID \
  -Dtests.timezone=SystemV/MST7MDT \
  -Dcompiler.java=13
```

**Comment by davidkyle** [comment]
Muted in c1580dc33fad9b58b621c4c5df27b38bdfd06b40

**Comment by dnhatn** [comment]
I also muted `testHistoryIsWrittenWithSuccess` in https://github.com/elastic/elasticsearch/commit/ceec4eaa074035baae885b4ca62ccedca83feaa4.

**Comment by andreidan** [comment]
This happened again on 7.x - https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-6&&immutable/471/consoleFull. 

There's a build scan available https://gradle-enterprise.elastic.co/s/u7p4epuphegx6

**Comment by albertzaharovits** [comment]
Another failure in a PR build check against master-ish : https://gradle-enterprise.elastic.co/s/aryfl6vkivmcm

**Comment by cbuescher** [comment]
Just got failures in `TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure` today that also look similar, so I'm adding these here as well:

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-15&&immutable/490/console
-- | --
Build Scans | https://gradle-enterprise.elastic.co/s/7rsdhwtqxkpka

```
java.lang.AssertionError: 
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>
	at __randomizedtesting.SeedInfo.seed([308B5D256356833E:B0E5874928ACC0FA]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1158)
	at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1111)
	at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithFailure$70(TimeSeriesLifecycleActionsIT.java:1074)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:879)
	at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure(TimeSeriesLifecycleActionsIT.java:1074)
```
Could not immediately reproduce with:
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure" \
  -Dtests.seed=308B5D256356833E \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-OM \
  -Dtests.timezone=US/Arizona \
  -Dcompiler.java=13
```

**Comment by cbuescher** [comment]
And another one on 7.x:

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=corretto11,nodes=general-purpose/427/console
-- | --
Build Scans | [7.5.2] https://gradle-enterprise.elastic.co/s/2vsjobvtg3uzy [6.8.7] https://gradle-enterprise.elastic.co/s/cttlnyx7gxaz2https://gradle-enterprise.elastic.co/s/tgvte72sfravm

**Comment by cbuescher** [comment]
Another on master (TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess). Maybe muting makes sense again. Will wait a bit longer but this seems to get frequent.

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/2865/console
-- | --
Build Scans | https://gradle-enterprise.elastic.co/s/fsh24b2yzlr3e

**Comment by cbuescher** [comment]
Another one:

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/428/console
-- | --
Build Scans | [7.5.2] https://gradle-enterprise.elastic.co/s/wnaucq2gssave [6.8.7] https://gradle-enterprise.elastic.co/s/z4toxanmwlsvwhttps://gradle-enterprise.elastic.co/s/4rp6nnb5jr67q

Will mute on master and 7.x, please revert those commits if you need more logs etc...

**Comment by cbuescher** [comment]
I muted `TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess` and `TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure` with 
a5ab7da  on master and 6c8868e95538a17cf5a49ce089073417430b2564 on 7.x

**Comment by dakrone** [comment]
I pushed some extra logging and enhancements for this test as well as unmuting them. Please leave a comment here if you see this fail again.

**Comment by cbuescher** [comment]
fyi, looks like `TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion` just failed in a PR of mine: https://gradle-enterprise.elastic.co/s/am3f7ezmibqp2
I think it should already have the logging you added.

**Comment by mayya-sharipova** [comment]
`testHistoryIsWrittenWithFailure` failed on PR for me:

./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure" -Dtests.seed=A50FCC98D7E0AF89 -Dtests.security.manager=true -Dtests.locale=hu -Dtests.timezone=America/Caracas -Dcompiler.java=13
HomeTestsorg.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT » testHistoryIsWrittenWithFailure

 Build: https://gradle-enterprise.elastic.co/s/4ov353fat2izi

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/kcpewteoty3yc. @leehinman Should we mute this suite again?

**Comment by dakrone** [comment]
@dnhatn yes, I'll re-mute now that I have the extra logging.

**Comment by dakrone** [comment]
I pushed yet more logging and un-muted a single test on master only, so if it fails again please do update this issue and I'll re-mute.

**Comment by mark-vieira** [comment]
@dakrone here are a few more failures that I assume include your additional logging:

https://gradle-enterprise.elastic.co/s/b6om55dj2eqk2/tests/ao2nxxbijves6-iqisezgxfz7vq
https://gradle-enterprise.elastic.co/s/vlmvs2kl6ge4k/tests/ao2nxxbijves6-iqisezgxfz7vq

**Comment by mark-vieira** [comment]
Given we've gotten a few more failures since adding the additional logging I've remuted this test with `bd6d6f7ac9ad05736d32d57eb0ef1a8eaf210239`.

I've also noticed this test failing recently with a different assertion error. Since it's not clear if these might be related I've opened a separate issue(https://github.com/elastic/elasticsearch/issues/52853) to make discoverability easier for folks.

**Comment by dakrone** [comment]
@mark-vieira thanks, these do have more information, thanks for re-muting for me.

**Comment by williamrandolph** [comment]
Bad news: this failure came up again on `master` today.

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux-7&&immutable/625/console
-- | --
Build scan | https://gradle-enterprise.elastic.co/s/rd3tzsc3sdt6c

**Comment by mark-vieira** [comment]
This is continuing to fail with some regularity (a dozen times in the past week on `master`) so I've muted this again with 73fe15632510a6bf800ac65050b35d7e0be4bbe1.

**Comment by mayya-sharipova** [comment]
Another failure on 7.x.   I keep it unmuted for now, as it a only a first failure from  Jan 2nd.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=java11,nodes=general-purpose/564/console

Build Scans: https://gradle-enterprise.elastic.co/s/ehgyqqem7x2r4

Failure doesn't reproduce for me on 7.x

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure" \
  -Dtests.seed=4CF58E4CF1F92544 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-EG \
  -Dtests.timezone=Europe/Helsinki \
  -Dcompiler.java=13

```
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1635)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1558)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithFailure$107(TimeSeriesLifecycleActionsIT.java:1420)
```

**Comment by davidkyle** [comment]
Numerous failures on 7.x I muted the test again - a38e5ca

**Comment by andreidan** [comment]
This test has been un-muted (and fixed) in https://github.com/elastic/elasticsearch/pull/64521
