### ISSUE TITLE
doubt about doc type 

### ISSUE THREAD

**Issue by niyanchun** [elastic/elasticsearch#50350]
I know es will remove type, and in 6.x, only one type is allowed, in 7.x, only `_doc` is allowed.  I use es 6.8, and when I create index template, I cannot give type in template, because the it will use default type `_doc`.  But I found in Kibana 6.8,  if I omit the type, it will be an error.  What's worse, I use filebeat 6.8 and es 6.8,  and I will create template in es, it use `_doc` as type. But filebeat use `doc` as type, and user cannot change it.  My doubt is: since es use `_doc`( although maybe remove type in 8.0), why filebeat use `doc`, and user cannot change it to `_doc`?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
