### ISSUE TITLE
SELECT COUNT(DISTINCT) NOT SHOWING CORRECT RESULTS

### ISSUE THREAD

**Issue by skiod** [elastic/elasticsearch#50354]
es : 6.7

I'm using elasticsearch sql api 
i found that results not correct when i add DISTINCT 

es code 
```
require('./elasticsearch/').transport.request({
        method : "POST",
        path   : '/_xpack/sql',
        body : {
            query : "SELECT COUNT(DISTINCT id)  FROM orders"
        }  
    },(err,res) => {
        console.log("error",err)
        return res.status(200).send(res)
    })
```

results : 
```
{
   "columns":[{"name":"COUNT(DISTINCT id)","type":"long"}],
    "rows":[[11459]] <----------------------------------------------- MUST BE (11501)
}
```

i execute same query in mysql 

```
SELECT COUNT(DISTINCT id)  FROM orders

```

results 
```
11501
``` 
Any Helps ?
Thank you

**Comment by astefan** [comment]
@skiod `COUNT(DISTINCT)` from SQL is using a `cardinality` aggregation behind the scene which, by design, doesn't offer accurate results in all scenarios: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate

Can you try running the following ES query on your `order` index (which actually comes from [_xpack/sql/translate API](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/sql-translate.html)) and see if the result you get there is the same SQL is showing you?

```
{
    "size": 0,
    "_source": false,
    "stored_fields": "_none_",
    "aggregations": {
        "groupby": {
            "filters": {
                "filters": [
                    {
                        "match_all": {
                            "boost": 1
                        }
                    }
                ],
                "other_bucket": false,
                "other_bucket_key": "_other_"
            },
            "aggregations": {
                "7a413d63": {
                    "cardinality": {
                        "field": "id"
                    }
                }
            }
        }
    }
}
```

**Comment by dliappis** [comment]
No further feedback received. @skiod if you have the requested
information please add it in a comment and we can look at re-opening
this issue.

**Comment by ionutale** [comment]
`cardinality` is not working after 20k records
do you have any other way?

**Comment by matriv** [comment]
@ionutale What do you mean doesn't work? Have you checked: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_precision_control ?

**Comment by ionutale** [comment]
Sorry, i am just frustrated that i am unable to do an `distinct count.`

Cardinality is just an approximation. 
I have over 20k buckets and cardinaly with `precision_threshold = 40000` is still retuning me wrong values, (approximate)

`Term aggregation ` is precise, but i am unable to do a `count ` those grouped buckets.
any idea how?

**Comment by matriv** [comment]
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question.

Thank you!

**Comment by ionutale** [comment]
ok, perfect thank you
