### ISSUE TITLE
Composite terms source should support include/exclude filtering

### ISSUE THREAD

**Issue by markwolke** [elastic/elasticsearch#50368]
Add support for include and exclude parameters with the terms source of composite aggregations.

The terms aggregation allows for [limiting the buckets returned](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4) but the [terms source of composite aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_terms) does not have the same feature.

**Comment by danielmitterdorfer** [comment]
Thanks for your idea. I've labelled the issue accordingly so that the respective team can have a closer look.

_Note: I've edited the original description so it links to the relevant sections of the reference documentation and is thus hopefully easier to understand for people that are not that familiar with these features._

**Comment by nik9000** [comment]
Given that you can't perform bucket selector scripts against composite aggs right now I think the regex and exact filtering is pretty compelling. I don't think the [partitioning](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_with_partitions) stuff makes a ton of sense though.

I do wonder if it'd be possible to use the script based terms support for composite aggs and then have the script return `null` when you don't to select the term. I'm not sure if that works now, if it *should* work, and if it'd be efficient. For instance, it isn't going to have a chance to use early termination from sorted indices. And probably can't use any global ordinals either.

@polyfractal, does this all sound right to you?

**Comment by alk-lbinet** [comment]
This feature would be extremely helpful indeed 👍  (regex/exact filtering).

**Comment by wchaparro** [comment]
closing as not planned.
