### ISSUE TITLE
Document the relationship between query_delay and frequency in ML

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#50389]
[Somewhere](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-datafeed-resource.html) we should document the relationship between `query_delay` and `frequency`

e.g.:

`frequency`
(time units) The interval at which scheduled queries are made while the datafeed runs in real time. The default value is either the bucket span for short bucket spans, or, for longer bucket spans, a sensible fraction of the bucket span. For example: 150s.   When `query_delay` is present, queries run at `query_delay` after the end of each `frequency`.   When `frequency` is shorter than the associated job's `bucket_span`, interim results for the last (partial) bucket are written, and then overwritten by the full bucket results eventually.

EDIT:  Added relationship to `bucket_span` also

⬆️ cc @droberts195 let me know if i've got that right ⬆️

**Comment by igor-kozlov** [comment]
It would be also great to learn whether `query_delay` could exceed `frequency`. Thank you!

**Comment by droberts195** [comment]
> It would be also great to learn whether `query_delay` could exceed `frequency`. Thank you!

Yes it can. If your data gets indexed the day after its timestamp you can set `query_delay` to 24 hours for example. (Some people really do this.)

**Comment by droberts195** [comment]
> let me know if i've got that right

Yes, the information is correct.  I will defer to the ML docs team about whether the description of `frequency` is the right place to put this.  The alternative might be a place where we describe the interaction of `frequency`, `query_delay`, `bucket_span` and also `interval` on the time aggregation (if the datafeed uses aggregations), then link to that from all the related setting descriptions.

**Comment by szabosteve** [comment]
https://github.com/elastic/elasticsearch/pull/50959 adds a section to the PUT datafeed docs about the relationship between the time-related settings and adds a link pointing to this section to the `frequency`, `query_delay`, and `bucket_span` descriptions.

**Comment by lcawl** [comment]
> The alternative might be a place where we describe the interaction of `frequency`, `query_delay`, `bucket_span` and also `interval` on the time aggregation ...

I have also drafted an update to the datafeed overview in https://github.com/elastic/stack-docs/pull/810
