### ISSUE TITLE
Linux OS id [arch-null] is not present in the Docker exclude list?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#50393]
**Elasticsearch version** (`bin/elasticsearch --version`): `master`

**Plugins installed**: none

**JVM version** (`java -version`): jdk-13

**OS version** (`uname -a` if on a Unix-like system): Linux/arch

**Description of the problem including expected versus actual behavior**:

`./gradlew :run` logs
```
Linux OS id [arch-null] is not present in the Docker exclude list
```

This seems like a message that we log for CI, but it was an odd greeting while compiling the project for the first time in a year.

**Comment by mark-vieira** [comment]
@pugnascotia I'm inclined to short-circuit [this stuff](https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/DistroTestPlugin.java#L501-L527) when not in a CI environment. Our exclusion list is based on our own custom images. There's nothing to say that a developer using Debian 8 can't run Docker-based tests. Thoughts?

**Comment by pugnascotia** [comment]
@mark-vieira Yeah, I think that's fair. Do you happen to know what is the best way of detecting CI for us?

**Comment by mark-vieira** [comment]
You can use `BuildParams.isCi()`.
