### ISSUE TITLE
commons-codec dependency 1.11 vulnerability WS-2009-0001

### ISSUE THREAD

**Issue by davydotcom** [elastic/elasticsearch#50396]
Bump commons-codec to 1.12 to resolve this vulneraibility

**Comment by rjernst** [comment]
The referenced issue was essentially retracted by WS:

```an additional review by WhiteSource research team could not indicate on a clear security vulnerability```

Additionally, version 1.12 fo commons-codec doesn't actually change anything. The [issue](**https://issues.apache.org/jira/browse/CODEC-55**) was closed as `not a bug`.
