### ISSUE TITLE
Allow Split Index and Allocation Deciders to work well together

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#50413]
Allocation deciders will prevent a split index based on projected hitting of watermark, however because Split Index performs hard links, it seems that the watermarks should be ignored in that specific case.

Example scenario is this:  User upgrades to 7.x, extremely large index is unexpectedly created on a single node and cannot be split.

**Comment by ywelsch** [comment]
There is no guarantee that hardlinking will be used (e.g. if not supported by platform, or if multiple data path are being used). Furthermore, hard-linking is not the only thing going on behind the scenes (That's just used to put the initial segments into place). There's also a force-merge step that might require substantially more space (eliminating a lot of deletes that have been introduced by the split). The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-split-index.html) are also clear on this:

> The node handling the split process must have sufficient free disk space to accommodate a second copy of the existing index.
