### ISSUE TITLE
Add setting to prevent index creation without matching template

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#50412]
In some environments it is considered erroneous to create an index with no matching template.   It would be helpful, and I imagine simple to provide a setting to prevent that.

Specifically, an index with no ILM policy or incorrect shard settings can present a risk to normal operations.

**Comment by gwbrown** [comment]
Likely related to some of the solutions discussed on https://github.com/elastic/elasticsearch/issues/41699

**Comment by dakrone** [comment]
Closing this as it's very old. We can always re-open if we want to revisit it.
