### ISSUE TITLE
Geohash grid aggregations's precision should support distance unit

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#5042]
The precision parameter of the geohash grid agg current allows specifying precision using a number:

```
"geohash_grid" : {
     "field" : "location",
      "precision" : 3
}
```

we should also support unit distances, like the `geohash_precision` of the geo point mapping does.

**Comment by xando** [comment]
Hi. Is this is something that could get into future version of ES?

**Comment by jqb** [comment]
Hi, any chance to move this forward anytime soon?

**Comment by Jordanwmk** [comment]
Hi, I am new to OSS but I would like to have a go at resolving this issue
