### ISSUE TITLE
Provide a way to avoid to overwite the ILM policy on beat setup --index-template

### ISSUE THREAD

**Issue by fpompermaier** [elastic/elasticsearch#50435]
**Elasticsearch version**: 7.5.0

I think it is wrong to force the usage of the default lifecycle policy when you specify the  **setup.ilm.policy_name** but you don't configure **setup.ilm.policy_file**.
I'd like to be able to configure a policy and then create only the index template and the "bootstrap" index  when calling setup --index-management.

What happens instead right now is that the ilm policy get's overwritten by the default policy..

**Comment by dakrone** [comment]
@fpompermaier This issue should be opened at https://github.com/elastic/beats, as Elasticsearch itself does not do any management of Beats' policies or templates. Please open this issue on the Beats repository.

**Comment by fpompermaier** [comment]
Added specific comment to https://github.com/elastic/beats/issues/13050
