### ISSUE TITLE
How to change the process default path?

### ISSUE THREAD

**Issue by sunnut** [elastic/elasticsearch#50461]
1. Start the elasticsearch with ./elasticsearch -d in the ES_HOME/bin
2. check the process id with ps -ef | grep elas
3. Check the path of the process with ll /proc/PID
4. the path is ES_HOME not the ES_HOME/bin

**Comment by imotov** [comment]
@sunnut this is intentional. See #39937 for details. Could you explain why you want to change the path?

**Comment by sunnut** [comment]
@imotov Oh. Because I change the es plugin code calling the C code(so file). And the so file used the relative path.So I must put the file in the same path with ES_HOME not put it in the ES_HOME

**Comment by rjernst** [comment]
As @imotov mentioned, it is intentional we always launch with the working directory as ES_HOME.  As this is working as designed, I hope you don't mind I close this issue.
