### ISSUE TITLE
request cache can not be enabled successfully in java transport client 

### ISSUE THREAD

**Issue by pphust** [elastic/elasticsearch#50493]
Hi,

I meet one strange problem in our es cluster.
When I submit one http request through curl, or submit it through java rest client, the request cache works well and I can see "hit_count" keep increasing when submitting same requests.

But when I use java transport client, it seems it never uses request cache even if I use `SearchRequestBuilder.setRequestCache(true)` to setup it. Anyone meet same problem and how can I resolve it?

Below is my working environment:
Elasticsearch version: 5.4.3
Plugins installed:  N/A
JVM version: 1.8.0_11
OS version: 3.10.0-693.5.2.el7

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
