### ISSUE TITLE
Not equal value inside array in ES SQL API

### ISSUE THREAD

**Issue by skiod** [elastic/elasticsearch#50494]
According to Elasticsearch doc it doesn't support arrays in SQL api.

I ended up using filter but it's doesn't work for my case. 

include product ids **works** fine
```
"body": {
            "query" :"SELECT email FROM orders WHERE  shop='domain' GROUP BY email,total_price", 
            "filter": { 
                 "term: { 
                            "line_items.product_id": "14141414"
                        } 
            }
          }
```

but when i try to exclude some product ids by adding 'not' it **doesn't work**

```
"body": {
            "query" :"SELECT email FROM orders WHERE  shop='eclatdeparis.myshopify.com' GROUP BY email,total_price", 
            "filter": { 
                "not" : {
                   "filter" : {
                        "term": { 
                            "line_items.product_id": "1418646978625"
                        } 
                    }
                }
            }
          }
```
is it any trick for exclude ?????
Thanks in advance

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
