### ISSUE TITLE
need simple nest sql query support feature please

### ISSUE THREAD

**Issue by a2393439531** [elastic/elasticsearch#50491]
AS you can see below,it's a simple nested query,it cannot be executed in ES 7.5.0 version.
  POST _xpack/sql
 {
   "query":"SELECT kks , sum(count) AS \"sum(count)\" FROM (select kks, count from \"crsdata\" LIMIT 5) AS T GROUP BY kks"
 }

  it returns 

{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Does not know how to convert argument LiteralAttribute[count,INTEGER,T,FALSE,163,false,1] for function Sum[]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Does not know how to convert argument LiteralAttribute[count,INTEGER,T,FALSE,163,false,1] for function Sum[]"
  },
  "status": 500
}

**Comment by skiod** [comment]
write your code 
inside  backticks
```
SELECT * ...
```

**Comment by astefan** [comment]
@a2393439531 sub-selects are supported for very simple, limited set of scenarios and the query you are trying to do is, unfortunately, not currently possible. At the moment we have no immediate plans on improving the sub-selects support.
