### ISSUE TITLE
Feature request: signed images

### ISSUE THREAD

**Issue by MrDienns** [elastic/elasticsearch#50504]
## Proposal
**Use case. Why is this important?**
Docker Content Trust allows us to verify if the images downloaded are indeed the images that ElasticSearch published. Security measures can be setup to only download signed images.

This goes for all ElasticSearch images, not just specific to this repository.

Is there any particular reason why signed images haven't been added, or is it simply a feature which hasn't been looked into yet?

https://docs.docker.com/engine/security/trust/content_trust/

**Comment by pugnascotia** [comment]
@MrDienns this is indeed something we're thinking about, but I don't have any dates at this time.

**Comment by mark-vieira** [comment]
Elastic stack Docker images are now signed via Sigstore.

https://www.elastic.co/blog/elastic-stack-container-images-signed-sigstore
