### ISSUE TITLE
MergeException : java.lang.ArrayIndexOutOfBoundsException : -1

### ISSUE THREAD

**Issue by lijiang1983** [elastic/elasticsearch#50520]
mips system test，merge error
The data volume of elastic search 6.3.2 reaches 100000 error reports
Elastic search 7.3.2 data volume reaches 2 million error reports
error information:

org.apache.lucene.index.MergePolicy$MergeException : java.lang.ArrayIndexOutOfBoundsException : -1
   at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun
   at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun
Cased By: java.lang.ArrayIndexOutOfBoundsException:-1
   at org.apache.lucene.util.fst.ReverseBytesReader.readByte
   at org.apache.lucene.util.fst.FST.readLabel(FST.java :542)
   at org.apache.lucene.util.fst.FST.readNextRealArc(FST.java 967)
   at org.apache.lucene.util.fst.FST.readFirstRealTargetArc(FST.java 874)
   at org.apache.lucene.util.fst.FST.readFistTargetArc(FST.java 845)
   at org.apache.lucene.util.fst.FSTEnum.pushFirst(FSTEnum.java 498)
   at org.apache.lucene.util.fst.FSTEnum.doNext(FSTEnum.java 111)

**Comment by henningandersen** [comment]
@lijiang1983 thanks for reporting this. Can you elaborate on the cluster setup, data set and workload that provokes this? Also, it would be good to have a more complete exception trace as well as check that there are no other errors that could cause this (in the log file or system/kernel log files).

**Comment by lijiang1983** [comment]
> @lijiang1983 thanks for reporting this. Can you elaborate on the cluster setup, data set and workload that provokes this? Also, it would be good to have a more complete exception trace as well as check that there are no other errors that could cause this (in the log file or system/kernel log files).

Thank you very much, Henning Anderson
we use single node. node count is 1. es use default config
attach file is entire log.

[es merge error.zip](https://github.com/elastic/elasticsearch/files/4009345/es.merge.error.zip)

**Comment by henningandersen** [comment]
@lijiang1983 thanks for the log file and additional info. Can you elaborate on the versions too? The log file seems to be a 6.3.2 version. When you mention 6.3 and 7.3, are they two different clusters or is it the same cluster that was upgraded?

Did you try running the elasticsearch-shard tool? In 6.3, it might bail out early due to not finding a corruption marker, but in 7.3, it should check the shard regardless.

**Comment by lijiang1983** [comment]
@henningandersen 6.3.2 and 7.3 has the same error.The tests we built in 6.3 and 7.3 respectively
when the error happen, es shard can't recovery in 6.3.2
when the error happen, es shard can recovery in 7.3.2, But recovery will take some time
Can this error be solved by es configuration？

**Comment by henningandersen** [comment]
@lijiang1983 can you also share the 7.3 log file showing the issue? Also, does this happen after a restart, reboot or similar? We need more details to diagnose this and I would prefer if you could tell a more complete story on how and when this happens. This should include details on the ingest workload and any other relevant details.

> But recovery will take some time

What kind of recovery are you referring to here? Using the elasticsearch-shard tool?

**Comment by dliappis** [comment]
@henningandersen as this is now pending feedback >1 month, is it worth keeping it open?

**Comment by henningandersen** [comment]
@lijiang1983 I hope you can find the time to respond to my questions above?

**Comment by henningandersen** [comment]
No further feedback received. @lijiang1983 if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
