### ISSUE TITLE
add stats for bulk_shard sizes/lantency/qps

### ISSUE THREAD

**Issue by zhichen** [elastic/elasticsearch#50536]
In the high-concurrency write log scenario, we found that hot_threads is always on the translog.sync operation. After a long investigation, I found that the application client often consumes several Kafka topics at the same time to form a bulkrequest and write it to Elasticsearch. Each topic corresponds to an index, resulting in a very small bulk quest to each shard, so the translog sync operation is very frequent .
This problem can be alleviated by setting translog async. In order to quickly locate the problem, I think it is necessary to add stats for bulk per shard, including bulk_shard_sizes, bulk_shard_lantency, and bulk_shard_qps.

**Comment by zhichen** [comment]
We have a lot of users who have this problem, so this demand is urgent for us.
If it is necessary to add stats for bulk per shard, which is a key indicator for writing, May I start working on this issue?

**Comment by dakrone** [comment]
@zhichen sure if you would like to work on this, go for it. Let me know if you have any questions.

**Comment by zhichen** [comment]
@dakrone  I am very sorry that I was delayed by other things some time ago. Now I have started to work on it.

First, the BulkOperationListener needs to be added, while the new ShardBulkStats will contain the following three metric
shard_bulk_size represents the average bulk sizes per shard
shard_bulk_time represents the number of bulk shard requests
shard_bulk_time_in_millis represents the service time of the bulk shard request.

Is there anything else to be concerned about here

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
