### ISSUE TITLE
elasticsearch Java Rest Client  request time cost

### ISSUE THREAD

**Issue by yffmonday** [elastic/elasticsearch#50545]
I use  Java Rest Client （6.6.0 vesion）to send request to ES。here is my basic config for REST Client:
    private static final int CONNECT_TIMEOUT = 10000;
    private static final int SOCKET_TIMEOUT = 10000;
    private static final int CONNECTION_REQUEST_TIMEOUT = 10000;
    private static final int MAX_CONNECT_NUM = 300;
    private static final int MAX_CONNECT_PER_ROUTE = 200;
We have a api which is a msearch request, and we use CAT to detect the api performance. To our surprise,mearcha api time cost is under 60ms most of the time，however sometime it will be over 400ms. At same time,I found network IO of ES cluster is normal. Accroding to my study,  Java Rest Client  use HttpAsyncClient to send request, and has a connection manager pool，so time cost of request should not be tremble.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
