### ISSUE TITLE
When will the Elastic Stack 8.0 be released? 

### ISSUE THREAD

**Issue by TableofContents** [elastic/elasticsearch#50546]
1, When will the Elastic Stack 8.0 be released? Do you have a schedule? Why not refer to the JDK release cycle?
2, Does Elasticsearch have plans for a pipline-like streaming pre-aggregation feature?

Thank you very much.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
