### ISSUE TITLE
Correction to Realm chains documentation for 7.x

### ISSUE THREAD

**Issue by joshjanoski** [elastic/elasticsearch#50560]
I noticed that there is a discrepancy in the Realm chains documentation for 7.x here: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/realm-chains.html

The example on that page uses the "type" parameter to specify the realm types, but this has been deprecated in 7.x per: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#include-realm-type-in-setting

Requesting that the example provided be updated to show the correct configuration format for 7.x with the type parameter removed. Thank you!

**Comment by cbuescher** [comment]
Looks like this is already worked on in https://github.com/elastic/elasticsearch/pull/50552, please correct me if I'm wrong...

**Comment by joshjanoski** [comment]
Apologies, @cbuescher. I didn't realize it had already been submitted. You are correct that it is already being worked through that issue, so if you wish to close out my issue that is ok. Thanks for your help!
