### ISSUE TITLE
Updating from 6.X to 7.X breaks

### ISSUE THREAD

**Issue by SElab2019** [elastic/elasticsearch#50579]
When I try to upgrade elasticsearch from 6.X to version 7.X. The following code breaks.

```
public void demo() throws IOException {

    int res = 0;
    RestHighLevelClient esClient = new RestHighLevelClient(null);
    SearchRequest searchRequest = new SearchRequest("test");
    
    SearchResponse searchResponse = esClient.search(searchRequest, RequestOptions.DEFAULT);
    res = (int)searchResponse.getHits().getTotalHits();
}
```

The code should pass, but it throws an error:
```
Demo.java:[24,57] incompatible types: org.apache.lucene.search.TotalHits cannot be converted to int
```

**Comment by albertzaharovits** [comment]
Hi @SElab2019 !
The format of the response has changed in 7 (breaking change), see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response .
