### ISSUE TITLE
Document Voting configuration exclusions API in rest-api-spec

### ISSUE THREAD

**Issue by jeromepin** [elastic/elasticsearch#50576]
Hello, 

I noticed their was no support for the [Voting configuration exclusions API](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/voting-config-exclusions.html). Is there a reason to not implement it ? Otherwise I'm willing to try to implement it.

Thanks !

**Comment by DaveCTurner** [comment]
Duplicates #48131. @jeromepin are you interested in working on this still?

**Comment by jeromepin** [comment]
@DaveCTurner Well, I originally created the issue in elasticsearch-py where I would have been able to write code, but here... That's a whole other level I don't have. So short answer is : I don't have enough Java/ES knowledge to work on that.

**Comment by DaveCTurner** [comment]
:grin: understood, thanks for letting us know. I'll close this in favour of #48131.
