### ISSUE TITLE
after reindex , why the docs.deleted is not 0

### ISSUE THREAD

**Issue by zte-wangning** [elastic/elasticsearch#50628]
Version: Elasticsearch 5.4.3

I'm trying to re indexing 50 indices into a new index, but some documents of new index marked for deletion repeatedly after re indexing, I want to know why.

the new index info, why the docs.deleted is not 0:
{
    "docs.count": "500000",
    **"docs.deleted": "124706",**
    "health": "yellow",
    "index": "new-reindex-all",
    "pri": "5",
    "pri.store.size": "1.2gb",
    "rep": "1",
    "status": "open",
    "store.size": "1.2gb",
    "uuid": "expg9KP3To2YNHJp4MEdyg"
  }

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
