### ISSUE TITLE
cat: ip doesn't agree with bound_address

### ISSUE THREAD

**Issue by drewr** [elastic/elasticsearch#5065]
A node with `network.host` set to `127.0.0.1` will show an IP that has nothing to do with the `lo` interface.

    $ curl -s localhost:9200/_nodes\?all | python -mjson.tool | fgrep bound
                "bound_address": "inet[/127.0.0.1:9200]",
                "bound_address": "inet[/127.0.0.1:9300]",
    $ curl -s localhost:9200/_cat/nodes\?h=ip,host
    192.168.56.10 es1

Repro on OS X and Ubuntu 12.04.

**Comment by clintongormley** [comment]
The returned address is now the publish host. Closing
