### ISSUE TITLE
master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster

### ISSUE THREAD

**Issue by NoCodeInMyHeart** [elastic/elasticsearch#50733]
[node-2] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [node-1, node-2, node-3] to bootstrap a cluster: have discovered [{node-2}{p8D3Ac90SUWPE3re8LhjMQ}{tNhJAi3QQ9uWwdnfzBH7Aw}{172.30.88.185}{172.30.88.185:9301}{dilm}{ml.machine_memory=1911832576, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [172.30.88.111:9300, 172.30.88.179:9302] from hosts providers and [{node-2}{p8D3Ac90SUWPE3re8LhjMQ}{tNhJAi3QQ9uWwdnfzBH7Aw}{172.30.88.185}{172.30.88.185:9301}{dilm}{ml.machine_memory=1911832576, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0

how can  i fix it?

**Comment by ywelsch** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
