### ISSUE TITLE
Support richer segment patterns in common.path.PathTrie

### ISSUE THREAD

**Issue by thejohnfreeman** [elastic/elasticsearch#5074]
PathTrie builds a trie by splitting path specifications like so:

```
/{index}/{type}/{id} => * as index -> * as type -> * as id
```

The elasticsearch-jetty plugin uses this structure to manage security constraints for different API endpoints. However, because of [this line in PathTrie.java](https://github.com/elasticsearch/elasticsearch/blob/6c23ace68fd9579e02d570d70aea8880ed3929be/src/main/java/org/elasticsearch/common/path/PathTrie.java#L114), any path segment that contains a wildcard is reduced to match anything, ignoring any prefixes or suffixes:

```
/category-{index}/{type}/{id} => * as index -> * as type -> * as id
```

I'm sure more than just the jetty plugin would benefit from a trie that supported richer patterns (even simple ones) at each level of a path. The improvement would require a different implementation of PathTrie, but does not need an API change, meaning it could be implemented transparently.

**Comment by javanna** [comment]
First of all sorry it took ages to comment on this. I am conflicted about this, primarily because we would introduce support for something that we don't need ourselves, which would complicate the codebase and would be potentially hard to test and maintain.

**Comment by dakrone** [comment]
@thejohnfreeman is this something you would be able to contribute? (along with tests). I'm concerned the same way that @javanna is about adding something we don't use ourselves and making it testable and maintainable.

**Comment by clintongormley** [comment]
Closing for now. Feel free to reopen if you are interested in @dakrone 's suggestion
