### ISSUE TITLE
Add JDK 15 EA to testing rotation

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#50764]
The OpenJDK project has an EA (early access) build for JDK 15 available at https://jdk.java.net/15/, which was released on Dec 27, 2019. This issue is to track getting this JDK integrated into CI for testing.

**Comment by mark-vieira** [comment]
I've opened https://github.com/elastic/infra/pull/17056 to add the JDK 15 builds to the JVM catalog.
