### ISSUE TITLE
IndicesOptions wilcard state parsing is too lenient

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#50762]
The logic to parse `IndicesOptions.WildcardStates` from a String or List of strings is overly lenient in that the ordering of values results in a different output when `none` is used as one of the values.

| Input | Output |
| ----- | ------- |
| all,none | |
| none,all | open, closed |
| none,open | open |
| open,none | |
| closed,none,open | open |

The parsing should be made more strict to disallow none with other values. There could be some users relying on this behavior, so to maintain BWC we could deprecate the use of `none` with other values in 7.x and disallow `none` with other values in 8.0.

**Comment by martijnvg** [comment]
+1 to remove the none with other leniency as is described in this issue.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
