### ISSUE TITLE
[CI] TimeSeriesLifecycleActionsIT testWaitForSnapshot failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#50781]
Failure:

```
2> java.lang.AssertionError: 
    Expected: "completed"
         but: was "wait_for_snapshot"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testWaitForSnapshot$23(TimeSeriesLifecycleActionsIT.java:344)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:879)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:852)
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testWaitForSnapshot(TimeSeriesLifecycleActionsIT.java:344)
```

Reproduce line:

```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testWaitForSnapshot" -Dtests.seed=EC28318704EF9660 -Dtests.security.manager=true -Dtests.locale=nb -Dtests.timezone=Pacific/Tarawa -Dcompiler.java=13
```

This didn't reproduce for me.

Build url: https://gradle-enterprise.elastic.co/s/uirpg2i73okrq

This test failed a few times already:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:*TimeSeriesLifecycleActionsIT+AND+test:testWaitForSnapshot'),sort:!(time,desc))

**Comment by original-brownbear** [comment]
Muted in 170e100

**Comment by original-brownbear** [comment]
This looks like the same issue in `testWaitForSnapshotSlmExecutedBefore` https://gradle-enterprise.elastic.co/s/t65m4uewdrzlo

**Comment by mark-vieira** [comment]
Yeah, I'm seeing a number of failures for different tests in `TimeSeriesLifecycleActionsIT` starting around mid December.

Page takes a minute to load: https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1578643199999&search.startTimeMin=1575187200000&tests.container=org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT&tests.sortField=FAILED&tests.unstableOnly&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-480

**Comment by nik9000** [comment]
This showed up with https://github.com/elastic/elasticsearch/pull/50454

**Comment by mark-vieira** [comment]
Let's please give this some immediate attention. `TimeSeriesLifecycleActionsIT` is the most common test failure across CI in the past month excluding Windows packaging tests. That could just mean muting for now.

**Comment by probakowski** [comment]
`testWaitForSnapshotSlmExecutedBefore` muted in ce50e8e

**Comment by probakowski** [comment]
Closing this one, looks like it's successfully fixed by #50818

**Comment by dakrone** [comment]
The failed today on the master intake branch: https://gradle-enterprise.elastic.co/s/aalmk4jiei77w

The same error:

```
java.lang.AssertionError
: 

Expected: "completed"
     but: was "wait_for_snapshot"
```

**Comment by tvernum** [comment]
Failed again
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2012-r2/386/console
- https://gradle-enterprise.elastic.co/s/4me7nb3m6ldkm/tests/ao2nxxbijves6-qhzts7vzmiy7k

Will re-mute.

**Comment by droberts195** [comment]
`testWaitForSnapshotSlmExecutedBefore` failed again on master with the same error as before in https://gradle-enterprise.elastic.co/s/zqejrnbnah5bu

I re-muted `testWaitForSnapshotSlmExecutedBefore` on master in c6c628bc0b83916e12c3f72249c3e35fc17755fb

**Comment by cbuescher** [comment]
Another failure today on 7.x: 
https://gradle-enterprise.elastic.co/s/jfkhpckv7ohxk/console-log?task=:x-pack:plugin:ilm:qa:multi-node:integTestRunner
Will also mute on 7.x for now

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/rd72cz5aa5lo2.

**Comment by probakowski** [comment]
I'll close this issue, given that it hasn't failed for over 900 builds since #51892 has been merged:
https://ela.st/wait-for-snapshot
https://ela.st/wait-for-snapshot-before
