### ISSUE TITLE
Using filter directly doesn't work

### ISSUE THREAD

**Issue by mooncui** [elastic/elasticsearch#50785]
curl -XGET '1.2.3.4:8080/pm_counter_kibana/_search?pretty'  -d '{
            "filter": {
                "term": {"counter.id" : "NETWORK_RX_RATE_MAX" }
            },
  }' doesn't work.

While 
    curl -XGET '1.2.3.4:8080/pm_counter_kibana/_search?pretty'  -d '{
    "query" : {
        "constant_score" : {
            "filter": {
                "term": {"counter.id" : "NETWORK_RX_RATE_MAX" }
            },
            "boost" : 1.0
         }
     }
  }' works.

Why is that?

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

"filter" is no longer a supported part of the search syntax.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
