### ISSUE TITLE
beats/logstash doesn't consistently name ES index for ILM default 

### ISSUE THREAD

**Issue by sgreszcz** [elastic/elasticsearch#50789]
**Elasticsearch version** (`bin/elasticsearch --version`): 

7.5.1 (elastic.co cloud), problem happened with previous 7 versions too.

**Description of the problem including expected versus actual behavior**:

According to the documentation, the default beat/logstash index pattern should be applied to the index name to support ILM.  https://www.elastic.co/guide/en/beats/metricbeat/current/ilm.html#setup-ilm-pattern-option

`%{now/d}-000001`

This is not happening consistently, and indices are being named with the "filebeat-7.5.1-" without the extension.  It seems to be happening randomly.  You can see in the screenshot below that some of them are named properly and some of them are not.  The elastic output from beats and logstash are set as default and there are no changes to the index name.

![Screenshot 2020-01-09 at 10 58 12](https://user-images.githubusercontent.com/22910494/72063705-31e78980-32d2-11ea-9d38-ef56f18611cb.png)

**Steps to reproduce**:

1. Stop all beats or logstash shippers
2. Delete indexes in elasticsearch
3. Start up the beats/logstash
4. Sometimes they name the new index with the proper ILM extension (%{now/d}-000001), and sometimes only with just the prefix (shipper-version-).

**Provide logs (if relevant)**:

If someone can tell me how from the cloud instance, I can attach them.

**Comment by sgreszcz** [comment]
> **Provide logs (if relevant)**:
> 
> If someone can tell me how from the cloud instance, I can attach them.

After doing a stop of all metricbeat 7.5.1 and logstash 7.5.1 indexes and index templates, and starting the data shipper containers, this time the indexes got names properly and linked to the ILM profiles OK.

I'm still not sure why it works sometimes and not another, especially when upgrading from one version of the shippers to the next.  Maybe it gets caught up with the existing index template being there?

<img width="870" alt="Screenshot 2020-01-09 at 16 43 12" src="https://user-images.githubusercontent.com/22910494/72086733-573ebc80-32ff-11ea-8080-00cf7e2a053c.png">
<img width="825" alt="Screenshot 2020-01-09 at 16 43 29" src="https://user-images.githubusercontent.com/22910494/72086734-573ebc80-32ff-11ea-92f4-da3271ee69b4.png">

**Comment by dakrone** [comment]
@sgreszcz this sounds like more of an issue on the beats side, rather than the ES side. Can you open your issue in the https://github.com/elastic/beats repository?

**Comment by sgreszcz** [comment]
> @sgreszcz this sounds like more of an issue on the beats side, rather than the ES side. Can you open your issue in the https://github.com/elastic/beats repository?

Sure, will do thank you.

**Comment by dakrone** [comment]
Close this in favor of the issue in the beats repo.

**Comment by sgreszcz** [comment]
Unfortunately despite the naming being OK now, I'm getting index errors after the ILM policy is applied.  For example filebeat-7.5.1-2020.01.13-000005 index is red for some reason.

<img width="1163" alt="Screenshot 2020-01-16 at 11 22 26" src="https://user-images.githubusercontent.com/22910494/72521253-ffe6a200-3852-11ea-8fa4-9c9142227635.png">

**Comment by sgreszcz** [comment]
> Close this in favor of the issue in the beats repo.

Unfortunately despite the naming being OK now, I'm getting index errors after the ILM policy is applied. For example filebeat-7.5.1-2020.01.13-000005 index is red for some reason.

Should I open another issue?


![](https://user-images.githubusercontent.com/22910494/72521253-ffe6a200-3852-11ea-8fa4-9c9142227635.png)
