### ISSUE TITLE
BWC test failures for MultiVersionRepositoryAccessIT

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#50819]
Our most recent `master` BWC test run failed against versions 7.0.x and 7.1.x with the same test failures indicating we either made a BWC incompatible change in `master` or perhaps just the test needs updating.

The build run in question included [this commit](https://github.com/elastic/elasticsearch/commit/ee6fbcc4a7a79bd7bd3e05768824798af264a30e), which _might_ potentially be related. @original-brownbear any thoughts?

Example build scan: https://gradle-enterprise.elastic.co/s/dpoop7fvn2rwq/tests/failed
Jenkins build with links to each BWC version: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc/471/

**Comment by original-brownbear** [comment]
@mark-vieira yea I know how to fix this (already did in `7.x`) but I'm afraid I will only be able to do so in 10-12h. Will do it right away in my morning sorry for the noise

**Comment by mark-vieira** [comment]
No rush. These builds only run every 8 hours so we are talking maybe 1 or 2 more failures so hardly much in the way of noise in the grand scheme of things. Thanks, Armin!

**Comment by mark-vieira** [comment]
@original-brownbear we are getting more failures on the `7.x` branch builds against BWC versions `6.5.x` and lower.

https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.x/job/elastic+elasticsearch+7.x+bwc/483/

https://gradle-enterprise.elastic.co/s/72ecamxlrgnc4/tests/b25xfi2kvu43g-g5ybnrrraxiry

**Comment by original-brownbear** [comment]
@mark-vieira ah sorry about that! Will fix it right away in my morning in 12h

**Comment by mark-vieira** [comment]
Thanks, Armin!

**Comment by danielmitterdorfer** [comment]
For the sake of completeness: We have two more build failures in:

* https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.x/job/elastic+elasticsearch+7.x+bwc/484/
* https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.x/job/elastic+elasticsearch+7.x+bwc/485/

(omitting build scans as they don't add any new information)

**Comment by original-brownbear** [comment]
Relatively trivial fix incoming in #51006 :)

**Comment by mark-vieira** [comment]
Thanks again, Armin!

**Comment by original-brownbear** [comment]
npnp closed via #51006

**Comment by mark-vieira** [comment]
@original-brownbear we are still getting failures on `7.x`.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro+bwc/487/

**Comment by original-brownbear** [comment]
Sorry about that, the failure we're seeing there could in fact also hit `master` fix incoming in https://github.com/elastic/elasticsearch/pull/51120 ... tests failed to account for running on non-OSS clusters

**Comment by tvernum** [comment]
Sorry @original-brownbear it looks like it's still failing in 7.x (694b8ab95dd298bebd9c1021efb10653cd87afae) BWC against 6.4.3
https://gradle-enterprise.elastic.co/s/uczk6mc54bwts/tests/kza37bzrrhlvw-pwyqvbdz22w3g

**Comment by tvernum** [comment]
I haven't checked whether the logs / causes are identical, but it looks like it's broken from [6.3.0, 6.5.4]

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro+bwc/498/

**Comment by ywangd** [comment]
Same type of failures also occur for 7.6 BWC tests against from 6.3.0 to 6.6.4 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+default-distro+bwc/13/

**Comment by original-brownbear** [comment]
Looks like there is yet another random failure left here unrelated to those fixed so far. I'm on it again.

**Comment by original-brownbear** [comment]
Fix incoming in https://github.com/elastic/elasticsearch/pull/51246
