### ISSUE TITLE
[CI] InternalAggregationsTests testSerialization reproducibly failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#50827]
`org.elasticsearch.search.aggregations.InternalAggregationsTests » testSerialization` has failed 7 times today and hasn't failed otherwise in the past month, so it's likely something is busted here.

Here's a build failure for which the reproduction line reproduces locally for me: https://gradle-enterprise.elastic.co/s/jrqqlb4u4unv2/tests/nfxodyych4uas-dbj4whiivduzy

**Comment by cbuescher** [comment]
Looks like yet again a subtle time zone glitch, only triggered when the serialization is done on a version <7.0. The time zone of the `rounding` inside an InternalDateHistogram is set to "Z" ([Zulu time](https://www.timeanddate.com/time/zones/z)) which seems to be equivalent to UTC. For versions before 7.0 we don't directly write the zone ID but convert to a string representation which in this case gives "UTC". This is deserialized to a "UTC" time zone which is equivalent but fails our strict equality checks.
I'll mute the test for now and work on a fix.

**Comment by cbuescher** [comment]
Should be closed by https://github.com/elastic/elasticsearch/pull/50845
