### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test "{p0=search/110_field_collapsing/field collapsing on a field alias}" failing in BWC tests

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#50826]
The test `org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.{p0=search/110_field_collapsing/field collapsing on a field alias}` has begun failing in our default distro BWC tests on `master` when testing against `7.5.x`.

Jenkins Job Type: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+default-distro+bwc/

Example Failure: https://gradle-enterprise.elastic.co/s/7usxvifrsqs6e/tests/hmmm3ltg6qpy2-yzt5ygktkanrk

Commit https://github.com/elastic/elasticsearch/commit/9b676b5cd16fd4182430d4fb5c3c6bd878ad528f seems to align with when this started happening. @jtibshirani any thoughts?

**Comment by jtibshirani** [comment]
@mark-vieira I'm sorry for the noise here, I didn't set the `skip` version correctly in tests (I didn't realize we tested against all 7.5.x versions, I only thought we tested against the latest). I'll push some commits to correct the situation.

**Comment by mark-vieira** [comment]
No worries, thanks Julie!

**Comment by jtibshirani** [comment]
I pushed the following commits to fix the error:
* 4af1ed53e14f9924c645464701e4a74c46a87b6b (7.5)
* a9c4db4134bd564523415a5f3a264860ac031fdf (7.x)
* 8dba29fe2dce203aa1a6e57c9f946d78789c5e43 (master)

**Comment by mark-vieira** [comment]
Looks like the builds are passing again. Thanks, Julie.
