### ISSUE TITLE
[CI] IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready failing occasionally

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#50860]
The `org.elasticsearch.indices.IndexingMemoryControllerTests. testSkipRefreshIfShardIsRefreshingAlready` has started failing in CI over the past two days (beginning 9 January).

```
Expected: <3L>
     but: was <4L>
java.lang.AssertionError: 

Expected: <3L>
     but: was <4L>
Open stacktrace
[2020-01-10T20:07:02,409][INFO ][o.e.i.IndexingMemoryControllerTests] [testSkipRefreshIfShardIsRefreshingAlready] before test
[2020-01-10T20:07:02,661][INFO ][o.e.i.IndexingMemoryController] [testSkipRefreshIfShardIsRefreshingAlready] now throttling indexing for shard [[index][0]]: segment writing can't keep up
[2020-01-10T20:07:02,755][INFO ][o.e.i.IndexingMemoryControllerTests] [testSkipRefreshIfShardIsRefreshingAlready] after test
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.indices.IndexingMemoryControllerTests.testSkipRefreshIfShardIsRefreshingAlready" -Dtests.seed=B5BDCAA2A6E7D70E -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=Etc/GMT-7 -Dcompiler.java=13
HomeTestsorg.elasticsearch.indices.IndexingMemoryControllerTests » testSkipRefreshIfShardIsRefreshingAlready
```

Here are a few examples:
https://gradle-enterprise.elastic.co/s/cba7nu73aolhi/tests?search=testSkipRefreshIfShardIsRefreshingAlready
https://gradle-enterprise.elastic.co/s/ndwjucgca5frm/tests?search=testSkipRefreshIfShardIsRefreshingAlready
https://gradle-enterprise.elastic.co/s/dr4gcyuvdtmwm/tests?search=testSkipRefreshIfShardIsRefreshingAlready
https://gradle-enterprise.elastic.co/s/kkgovpbeyu34q/tests?search=testSkipRefreshIfShardIsRefreshingAlready

**Comment by mark-vieira** [comment]
Not sure what area this issue would best fall under, @dnhatn, since you last touched `IndexingMemoryController` maybe you might have an idea as to what is going on here, or perhaps who is best suited to look at this.

**Comment by mark-vieira** [comment]
Actually @dnhatn, looks like you just added this test yesterday so I'm just going to go ahead and assign this to you 😉

**Comment by dnhatn** [comment]
@mark-vieira Thanks for the ping. @henningandersen kindly fixed this test in https://github.com/elastic/elasticsearch/pull/50856.
