### ISSUE TITLE
Type-exists HEAD request returns 404 unless type exists in all specified indices

### ISSUE THREAD

**Issue by bwmeier** [elastic/elasticsearch#5087]
In 0.90.10 and 0.90.11, with logstash generated indexes logstash-YYYY.MM.DD, wildcard resolution fails for HEAD index existence checks.  This causes failures in elasticsearch-hadoop M2 and other tools that use this paradigm to check for index existence.

``` bash
~$ curl -I -XHEAD 'http://localhost:9200/logstash-*/log4jlogs'
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=UTF-8
Content-Length: 0
```

``` bash
~$ curl -I -XGET 'http://localhost:9200/logstash-*/log4jlogs/_search'
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 11083
```

**Comment by kleptog** [comment]
FWIW, a 404 is also returned when using _all, so it's not specifically related to index wildcard resolution.

ES 2.0.0

**Comment by clintongormley** [comment]
> However, I definitely think that if the associated _search query would return data, then the HEAD query should return 200, by principle of least surprise.

I think I disagree with this.  Search is just one use case.  What if you were using this to answer the question "does this type exist in all indices or do I need to update the mapping"?

In fact, searching on a non-existent type doesn't return an error - it just returns zero results, which seems safe.

I think we should leave this as it is.
