### ISSUE TITLE
Message-ID in watcher emails violates RFC

### ISSUE THREAD

**Issue by gbanasiak** [elastic/elasticsearch#50895]
**Elasticsearch version**: 7.5 (reported version, earlier also affected)

**Description of the problem including expected versus actual behavior**:

Message-ID in watcher emails follows the following format:
`<action-ID>_<watcher-ID>_<random-UUID>-<timestamp>`

Example:
`send_email_prod-disk-usage-alert_6814c3de-277f-4aa4-867b-04a7c5bd7c21-2020-01-13T07:45:27.747334Z`

This violates RFC 5322 (former RFC 2822) [format](https://tools.ietf.org/html/rfc5322#section-3.6.4) in a number of ways: missing angle brackets, lack of left/right part, forbidden special characters used (i.e. `:`).

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
