### ISSUE TITLE
CreateIndexRequest with source as input cast "mappings.dynamic" property as Map

### ISSUE THREAD

**Issue by LuckyLukas** [elastic/elasticsearch#50902]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.5.1

**Plugins installed**: [ "phonetic"]

**JVM version** (`java -version`):

openjdk version "11.0.4" 2019-07-16

**OS version** (`uname -a` if on a Unix-like system):

macOS Mojave 10.14.5

**Description of the problem including expected versus actual behavior**:

When trying to create an Index and providing the full settings + mappings from a .json file, the parsing logic tries to cast the "dynamic" property of mappings as Map and throws a ClassCastException.

**Steps to reproduce**:
1) 
```
import org.elasticsearch.action.admin.indices.create.CreateIndexRequest;
[...]
CreateIndexRequest request = new CreateIndexRequest("myIndex");
request.source(indexSource, XContentType.JSON);
```

with this as input:
```
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "prop1": {
        "type": "text",
      }
    }
  }
}
```

will lead to `ClassCastException` in `CreateIndexRequest::source(Map<String, ?> source, DeprecationHandler deprecationHandler)` on line `412` when trying to parse "dynamic"

removing "dynamic" works.

**Comment by romseygeek** [comment]
The internal `CreateIndexRequest` object assumes that the mappings is wrapped in a `_doc` type; you should be able to work around this either by using the `CreateIndexRequest` object for the high-level rest client instead (in `package org.elasticsearch.client.indices;`) or adding an extra `_doc` level around `dynamic` and `properties`.  I'd recommend doing the former, as using the internal request objects is deprecated.

**Comment by LuckyLukas** [comment]
got it, didn't see we where using the .admin. package
