### ISSUE TITLE
.watcher-history: Access status fields

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#50905]
**Describe the feature**: We would like to be able to access some of the fields within the `.watcher-history` index (e.g., `status` and subfields) to evaluate the history of watch execution. However, some fields, such as `status` are disabled within the index template.

Unfortunately, the following workarounds do not work:

1. Copy the value of, e.g., `status.last_met_condition`, to a different field using an ingest pipeline. This does not work, as the mapping is not dynamic.
2. Overlaying the default index template to enable field `status` (or others): We are not sure if this is recommended, as the default template uses an order of 2^31-1.

Are there specific reasons why the mentioned fields are disabled in the first place?

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
