### ISSUE TITLE
Document the option to use painless as script language in search templates

### ISSUE THREAD

**Issue by laraMorenoIgle** [elastic/elasticsearch#50923]
Painless can be used as script language for search templates as done in this github #24529.
However as per our documentation mustache is the only allowed language for creating search templates. 
If `painless` is fully supported as script language in search templates, then we should state it in the [documenation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html) and provide at least one example.

**Comment by jdconrad** [comment]
If we do want to officially support this, we need to add some test coverage to ensure changes to Painless don't break templates unknowingly. We may also want to consider the places that watcher hard codes mustache for template support.

**Comment by jdconrad** [comment]
Spoke with @stu-elastic and @rjernst - we've agreed this should be supported, so it's a matter of tests and docs now.

**Comment by sauln** [comment]
Hey, I'm stoked to get to use Painless in my search templates. Is there any draft documentation on how this works?  I'm not sure if the syntax described in #24529 is relevant at all.  

Thank you,

**Comment by stu-elastic** [comment]
Painless cannot be used as a search template language and we do not currently have plans to extend it to be one.  If there shortcomings in use mustache that need to be addressed, we'd love to see them, with use cases, in separate issues.

The documentation on the search template API is correct
> Allows you to use the mustache language to pre render search requests.

so I'm going to close this issue.
