### ISSUE TITLE
search_as_you_type result score always 1

### ISSUE THREAD

**Issue by dpkirchner** [elastic/elasticsearch#50935]
**Elasticsearch version**

`Version: 7.5.0, Build: default/docker/e9ccaed468e2fac2275a3761849cbee64b39519f/2019-11-26T01:06:52.518245Z, JVM: 13.0.1`

**Plugins installed**: None (/_cat/plugins returns nothing)

**JVM version** (`java -version`): 
```
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux bce72a9add6b 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

When you search on a search_as_you_type field, every result has exactly the same score (1.0). I expected the scores to vary based on the quality of the match. The results are not sorted in a useful order, instead they're sorted by the document creation time.

**Steps to reproduce**:

1. Start Elasticsearch
2. Create an index and mapping with a search_as_you_type field
3. Add documents
4. Search and witness the identical scores

```
# Start Elasticsearch
rm -rf /tmp/es
mkdir /tmp/es
docker run --rm -p 9200:9200 -v /tmp/es:/usr/share/elasticsearch/data -e discovery.type=single-node docker.elastic.co/elasticsearch/elasticsearch:7.5.0

# Open another window, then run this until you get a successful result:
curl localhost:9200
```
```
# Create the index and mapping
curl -X PUT -H 'content-type: application/json' -d '{"mappings":{"properties":{"title":{"type":"search_as_you_type"}}}}' localhost:9200/testo
```
```
# Add documents
curl -X POST -H 'content-type: application/json' -d '{"title":"abc"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"def abc"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"abcdef"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"xyz"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"zzz"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"abc2"}' 'localhost:9200/testo/_doc?refresh'
curl -X POST -H 'content-type: application/json' -d '{"title":"ghi jkl abc"}' 'localhost:9200/testo/_doc?refresh'
```
```
# Run searches
curl -s -X POST -H 'content-type: application/json' -d '{"query":{"multi_match":{"query":"ab", "type": "bool_prefix", "fields": ["title","title._2gram","title._3gram"]}}}' localhost:9200/testo/_search | jq -r '.hits.hits[] | "\(._score) \(._source.title)"'
# Output (note: jq is converting 1.0 to 1, but the score returned by ES is 1.0):
1 abc
1 def abc
1 abcdef
1 abc2
1 ghi jkl abc
```

You'll get exactly the same results if you drop the `title._2gram` and `title._3gram` fields from the query. If you drop `title` and just leave the n-gram fields, you get no results. I'm not sure if that's relevant, however, as I'm a newbie when it comes to the n-gram functionality.

As a user running a search-as-you-type query, I'd expect to see "abcdef" and "abc2" before "def abc" and "ghi jkl abc". It looks like the query is just returning documents in the order they were added. When I add a document with title "abc def" I see it at the end of the search results, when I'd expect it to be in the second position, before "def abc".

This may be an issue on my end, but I haven't found it (yet).

**Comment by mayya-sharipova** [comment]
@dpkirchner  Thank you for submitting the issue. This is an expected behaviour. Your query consists of a single term that is turned into a prefix query and prefix queries only produce scores of 1.

The query you are using `bool_prefix` with an option of `multi_match` runs prefix query on the **last** query term using `_index_prefix` fields. In your case it is the only term, and only 1 field has a prefix field, so your query will be translated to  `ConstantScore(title._index_prefix:ab)`. (You can always check what your query translates to by adding an option `_search/explain=true`.) . Index prefix queries are always scored as 1  if a document field has this term, so all matched documents will have the same score and will be returned in the order of their internal document ids.

If your query consists of several terms, the behaviour will be different and will account for other fields as well.  

If you are looking for some custom scoring, consider also experimenting with boolean queries directly, like this:
```js
POST /test_index/_search?pretty&explain=true
{
  "query": {
    "bool": {
      "should": [
        {"term": {"title": "abc"}},
        {"term": {"title._2gram": "abc"}},
        {"term": {"title._3gram": "abc"}},
        {"prefix": {"title": "abc"}}
      ]
    }
  }
}
```

**Comment by dpkirchner** [comment]
@mayya-sharipova I've gotta say this is surprising behavior, although I'll admit it's possible I'm alone on that. I think it'd be worth updating the documentation to indicate that the sort order for `search_as_you_type` queries aren't (really) sorted when using the query suggested there:

https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-as-you-type.html

I'll try your suggestion -- that specific query has the same results, but I'll tinker with it to see if I can get it to score the results the way I need. `explain=true` is especially helpful.

**Comment by tmakin** [comment]
@dpkirchner I'm 100% with you on this issue. I find the constant scoring for single terms unintuitive. Did you come up with any useful workarounds?

**Comment by dpkirchner** [comment]
@tmakin Sadly, no. I gave up.

**Comment by euclidd** [comment]
Hey, @dpkirchner, I had a similar issue with prefixes. Check out this video, maybe it'll help: https://www.youtube.com/watch?v=GCnPx89oD4Y. 
Basically, you can try: 
{
    "query": {
        "match_phrase_prefix": {
            "title": "abc"
        }
    }
}

Hope it helps!
