### ISSUE TITLE
Cannot configure snapshot-tool QA tests

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#50971]
We get the following failure for the third-party-tests-s3 in CI consistently since January 9 (see also the [build scan](https://gradle-enterprise.elastic.co/s/qscynwbekf3lm) of first failing build [#238](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+third-party-tests-s3/238/)):

```
A problem occurred configuring project ':x-pack:snapshot-tool:qa:s3'.
No docker-compose.yml found for :x-pack:snapshot-tool:qa:s3 nor does it use other fixtures.
```

* example build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+third-party-tests-s3
* Build scan link: https://gradle-enterprise.elastic.co/s/s4g5kmsd5vrvi

@original-brownbear I assume you're probably most familiar with this area. Can you please have a look at this?

**Comment by original-brownbear** [comment]
Jup, I think I know how to fix this.

**Comment by danielmitterdorfer** [comment]
Thanks Armin!

**Comment by original-brownbear** [comment]
npnp, fixed in https://github.com/elastic/elasticsearch/pull/50983 :)
