### ISSUE TITLE
[docs] Watcher TLS/SSL setting no default values in 7.x

### ISSUE THREAD

**Issue by gemaliano** [elastic/elasticsearch#50984]
[Watcher TLS/SSL setting documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/notification-settings.html#ssl-notification-settings) says:

```You can configure the following TLS/SSL settings. If the settings are not configured, the Default TLS/SSL Settings are used.```

This is not valid since version 7.x. as per [Breaking Change](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/breaking-changes-7.0.html#tls-setting-fallback) we do not have default settings for watcher. We have to configure ```xpack.http.ssl.*```.

**Comment by lcawl** [comment]
That page pulls content from the https://github.com/elastic/elasticsearch/blob/7.5/docs/reference/settings/ssl-settings.asciidoc file, which is also used in the monitoring and security settings page.
I think we need someone from the Elasticsearch security team to verify that the information is incorrect for one or all of those contexts.  It sounds like we're proposing that the "Default values for TLS/SSL settings" (https://www.elastic.co/guide/en/elasticsearch/reference/7.5/security-settings.html#ssl-tls-settings) and all links to it should be removed entirely?

**Comment by tvernum** [comment]
The docs could definitely be improved (which @lcawl is working on in #51017), but I don't think the docs are intended to be understood as refering to `xpack.ssl.*` but rather are trying to say "if you don't set these, there is a default behaviour".

e.g. You can set `xpack.http.ssl.supported_protocols`, but if you _don't_ you get TLS1.1 and newer.

**Comment by tvernum** [comment]
Actually, on second reading, I'm not even sure what that doc is trying to say. Maybe your interpretation was correct. Either way, we can do better.

**Comment by lcawl** [comment]
@gemaliano I've merged https://github.com/elastic/elasticsearch/pull/51017, which ensures the same definitions are used for the TLS settings in the monitoring, Watcher, and security pages in master, 7.x, and 7.6 branches. I've also removed that unclear  "If the settings are not configured, the Default TLS/SSL Settings are used" statement from https://www.elastic.co/guide/en/elasticsearch/reference/current/notification-settings.html#ssl-notification-settings

If there's anything else still outstanding from your point of view, please just let me know.  Thanks!
