### ISSUE TITLE
Node stats API returns incorrect "is_throttled" when indices are deleted.

### ISSUE THREAD

**Issue by itiyamas** [elastic/elasticsearch#51023]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.0
**Description of the problem including expected versus actual behavior**: Node stats returns incorrect "is_throttled" even after an index that was being throttled is deleted. I suspect this is due to the fact that nodes stats' is_throttled flag is [not cleared](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/IndexingStats.java#L91) when index is deleted. Even though indexingStats for old indices [checks for](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L976) engine close condition, it is checked [before closing](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/indices/IndicesService.java#L777) the engine- hence is_throttled is true in this case

**Steps to reproduce**:

 1. Create a cluster with a single node.
 2. Create an index and ensure that it is being throttled- reduce merge thread count- index1
 2. Create another index and ensure that it is not being throttled- index2
 3. Delete "index1", while it is being throttled.
 4. Index stats does not show that any index is throttled
 5.  Node stats show that is_throtted is true for the node, even though none of the indices stats shows is_throttled as true.

**Comment by Gaurav614** [comment]
I am taking this up. And soon raise a PR for it.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
