### ISSUE TITLE
Ingest: `_ingest._value` not accessible within `append` processor

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#51036]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5 Elastic Cloud

We are trying to copy an array of values to another field. While the `uppercase` processor is able to access `_ingest._value`, the `append` processor is not:

```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "foreach": {
          "field": "recipients",
          "processor": {
            "uppercase": {
              "field": "_ingest._value"
            }
          }
        }
      },
      {
        "foreach": {
          "field": "recipients",
          "processor": {
            "append": {
              "field": "test",
              "value": [ "_ingest._value" ]
            }
          }
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "recipients": [
          "Foo@bar.com",
          "Bar@foo.com"
        ]
      }
    }
  ]
}
```

Results in:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "index",
        "_type" : "_doc",
        "_id" : "id",
        "_source" : {
          "test" : [
            "_ingest._value",
            "_ingest._value"
          ],
          "recipients" : [
            "FOO@BAR.COM",
            "BAR@FOO.COM"
          ]
        },
        "_ingest" : {
          "_value" : null,
          "timestamp" : "2020-01-15T12:33:36.9819Z"
        }
      }
    }
  ]
}
```

**Comment by danhermann** [comment]
@fkelbert, you need to use a [template snippet](https://www.elastic.co/guide/en/elasticsearch/reference/current/accessing-data-in-pipelines.html#accessing-template-fields) in the append processor above. E.g.:

```
"foreach": {
  "field": "recipients",
  "processor": {
    "append": {
      "field": "test",
      "value": [ "{{_ingest._value}}" ]
    }
  }
}
```

**Comment by fkelbert** [comment]
Thank you @danhermann. This works.

However, I do not quite understand why one would need to use different syntax in different processors. To me, this is quite non-intuitive. While there might be technical reasons for the way things are today (just a guess on my side), imho this should not be exposed to the user.

I have opened a separate issue: https://github.com/elastic/elasticsearch/issues/51162
