### ISSUE TITLE
Performance monitoring of Ingest pipelines

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#51039]
Just like for Logstash pipelines, it would be great to have insights into the performance of ingest pipelines and specific processors.

This is essential to debug and optimise performance of ingest pipelines.

**Comment by danhermann** [comment]
@fkelbert, the `_nodes/stats` endpoint currently provides a list of ingest pipelines and their respective processors with `count`, `time_in_millis`, `current`, and `failed` metrics for each. Is there something beyond that you would like to see?

**Comment by fkelbert** [comment]
Thanks @danhermann, that's what I was looking for. Kibana Monitoring for these numbers would be awesome.

[Kibana: Ingest pipeline monitoring](https://github.com/elastic/kibana/issues/41936)

**Comment by a03nikki** [comment]
This overlaps with #43368

**Comment by matschaffer** [comment]
https://github.com/elastic/kibana/issues/41936 is the new central isssue for ingest pipeline monitoring.
