### ISSUE TITLE
java.lang.ClassNotFoundException: org.elasticsearch.action.Action

### ISSUE THREAD

**Issue by yipixiaofeiyang** [elastic/elasticsearch#51040]
**Describe the feature**:

**Elasticsearch version** (` v7.5.1`):

**Plugins installed**: [spring-data-elasticsearch]

**JVM version** (`1.8`):

**OS version** (`centos7`):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
my elastic(6.8.0)+spring-data-elasticsearch(3.2.3) project upgrade elastic(7.5.1)+spring-data-elasticsearch(3.2.3), centos7 server elastic Has been upgraded to7.5.1, but project running exception:   ### **java.lang.ClassNotFoundException: org.elasticsearch.action.Action**

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Hi @yipixiaofeiyang. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
