### ISSUE TITLE
Ingest: Allow arrays in lowercase and uppercase processors

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#51048]
Elastic Cloud 7.5

Currently, we implement long lists of `lowercase`/`uppercase` processors to lowercase/uppercase a list of fields. These processors should be able to process multiple fields.

Potentially, this also applies to other processors.

Current approach:

```
{
  "processors": [
    {
      "lowercase": {
        "field": "mail.sender"
      }
    },
    {
      "lowercase": {
        "field": "mail.sender_domain"
      }
    }
  ]
}
```

Desired approach:

```
PUT _ingest/pipeline/generic
{
  "processors": [
    {
      "lowercase": {
        "field": [ "mail.sender", "mail.sender_domain" ]
      }
    }
  ]
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
