### ISSUE TITLE
Scripted Field for elements inside JSON objects

### ISSUE THREAD

**Issue by yishaihl** [elastic/elasticsearch#51078]
Hey Guys,
I'm using FluentD (deployed as DaemonSet) to stream k8s app (containers) logs to elasticsearch. i want to extract specific keys from the 'log' key string (see attached) in elastic such as logKey: ... or statusCode:..
i want to use scripted field ~ painless script.
i struggled a bit with it, can someone please advise?

<img width="930" alt="Screen Shot 2020-01-16 at 0 50 44" src="https://user-images.githubusercontent.com/39559916/72478949-c6367c80-37fb-11ea-8227-47c24e2f8549.png">

**Comment by matriv** [comment]
@yishaihl 

Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us
to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. 
As such, I hope you don't mind that I close this.
