### ISSUE TITLE
Improve:  split index, will copy data when each es instance have many disks

### ISSUE THREAD

**Issue by huyfaeng** [elastic/elasticsearch#51084]
when each es instance have many disks,  split index will lead  copy data from one disk to another disk. because hark link cann't  across disk.

the best way may be : the target index and source index should use the same disk, so it will be finish soon, or will cost too much time, especially if the disk is hdd, and the cluster is red.

the side effect is : the usage rate of disk will not even. but it will reblance because the nunber of shard is not even , so the impact is trivial.

in my case: 
in my production es 7.1  cluster, there are 12 disks of each machine, and each es instance have 4 disks, like this image:

![image](https://user-images.githubusercontent.com/844875/72499018-b8204480-386b-11ea-912c-e84200e3f52b.png)

when i split source index, it will cost too long time,  only the shard of target index   used the same disk with source index will finished quickly, other will not.

![image](https://user-images.githubusercontent.com/844875/72498996-a9399200-386b-11ea-8eed-6a685dd95330.png)

**Comment by pgomulka** [comment]
@huyfaeng I am afraid this will not work.
I suppose you are using multiple data paths on each node? 
ES does not balance shards across them.
```
Elasticsearch does not balance shards across a node’s data paths. High disk usage in a single path can trigger a high disk usage watermark for the entire node. If triggered, Elasticsearch will not add shards to the node, even if the node’s other paths have available disk space. If you need additional disk space, we recommend you add a new node rather than additional data paths.
```
https://www.elastic.co/guide/en/elasticsearch/reference/master/important-settings.html#path-settings

For this reason I will close an issue. If you think you can provide more information, feel free to reopen
