### ISSUE TITLE
Add "enterprise" license OperationMode

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#51081]
Elasticsearch supports the "enterprise" type stack license, but internally it maps that to the "platinum" operation mode.

We should create an explicit "enterprise" operating mode so that it is possible for new functionality to be tied to this license type.
 
Relates: #48510

**Comment by tvernum** [comment]
I think it might be time to do a refactor of `XPackLicenseState` when we do this. There are a lot of methods there, many of which are tied to explicit modes.

It might be better to replace the body of each of those `isXyzAllowed()` methods with a call to something common e.g.

```
    public boolean isSqlAllowed() {
        return checkMinimumLicense(OperationMode.BASIC);
    }

    public boolean isJdbcAllowed() {
        return checkMinimumLicense(OperationMode.PLATINUM);
    }

    private boolean checkMinimumLicense(OperationMode mode) {
        return checkMinimumLicense(mode, true);
    }
  
    private synchronized boolean checkMinimumLicense(OperationMode minimumMode, boolean allowTrial) {
        Status localStatus = status;
        if (localStatus.active == false ) {
            return false;
        }
        if (allowTrial && localStatus.mode == OperationMode.TRIAL) {
            return true;
        }
        return localStatus.mode >= minimumMode;
    }
```

**Comment by ywangd** [comment]
Should every one of these methods check `status.active == true`? Some of them don't, e.g. `isApiKeyServiceAllowed`? If refactored, the `active` check will be applied. Or should we make exception for them?

**Comment by tvernum** [comment]
Good point.
A few features, like security (and therefore API Keys) are intended to be permitted even if the license expires (`active == false`). We don't want to turn off security when a license expires, and if security is on, then you need to be able to authenticate (via any authentication method).

So, we need an exception.

**Comment by ywangd** [comment]
There is also a `MISSING` operation mode which is not handled in every case. For an example, the [XPackLicenseState#isSecurityEnabled](https://github.com/elastic/elasticsearch/blob/7.6/x-pack/plugin/core/src/main/java/org/elasticsearch/license/XPackLicenseState.java#L840) handles it as defaults, i.e. same as gold or platinum. Is this an issue?

**Comment by tvernum** [comment]
MISSING will mostly (fully?) go away with #45022
If it stays, I think we may need to look at it on a case-by-case basis but for non-security we could treat it like BASIC
For security we probably want to continue to treat it like PLATINUM so that a license problem doesn't break security.

**Comment by ywangd** [comment]
Cool makes sense. Currently there is a bit inconsistency between code and javadocs. For an example, [isEnrichAllowed](https://github.com/elastic/elasticsearch/blob/7.6/x-pack/plugin/core/src/main/java/org/elasticsearch/license/XPackLicenseState.java#L702) only check whether a license is active. But its javadocs says `all license types except MISSING`. I lean towards removing the line in javadocs. Sounds reasonable to you?

**Comment by tvernum** [comment]
> Sounds reasonable to you?

Yes. If the implementation of `isEnrichAllowed` is clean (e.g. `checkMinimumLicense(OperationMode.BASIC);`) then I don't think it really needs Javadoc.

The purpose of the method is clear from the name. The behaviour is clear from the implementation. What more does the Javadoc add?

**Comment by ywangd** [comment]
> What more does the Javadoc add?
>
Nothing. Code should be treated as the ultimate reference. So I'll delete the doc line as it adds nothings but confusion. Thanks.
