### ISSUE TITLE
Define restriction for field values in index mapping

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#51114]
It could be useful for users to be able to restrict field values to a pre-defined list. For example, restrict the values of field `colour` to  `red`, `green`, `blue`. 

Currently such functionality could be implemented with dropping the documents not matching the condition using [conditional execution pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-conditionals.html), but it might be useful to be able to define such a restriction through index mapping.

**Comment by matriv** [comment]
There are several ways for a user to validate the data for a field upon insertion but the requirement for an enum like type has been brought up frequently so it seems to worth implementing it. Apart from the validation during insertion, there can be a no-match query optimization if all the match term values specified are not in the enum set. If some of them are not in the enum set, they can be safely removed from the match term values as they will never match.

After some discussion on the topic, adding a new type for such fields seems to win over the alternative solution to add a new option specifying the valid set of values accepted for a field.
NOTE: with a new field type `enum` it means that such fields would be treated internally as keyword type.

**Comment by matriv** [comment]
An additional useful feature for the new `enum` type would be the ability for the user to define custom ordering on the values instead of the natural one that a keyword would provide.

**Comment by jtibshirani** [comment]
Closing in favor of #59135, which proposes to add a new `enum` field type.
