### ISSUE TITLE
http://localhost:9200 Unable to access this siteThe connection to localhost was denied.

### ISSUE THREAD

**Issue by rnardo** [elastic/elasticsearch#51160]
Good Morning everbody !

I have a great challenge !

The service has been installed on Windows successfully and It's running very well. But when attenpting to do request with the url: http://localhost:9200 i recived the message below:

I installed the JRE 8, configured the environment variable and installed the Elastic Search 7.5.1. I am using the Windows 8.1.

Unable to access this siteThe connection to localhost was denied.
Try it:

Check the connection
Check proxy and firewall
ERR_CONNECTION_REFUSED

Regards,

Rafael Nardo

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
