### ISSUE TITLE
Support more complex paths in set processor

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#51176]
The set processor seems to only support fairly simple `{{template}}` format. For more advanced use cases, it would be very useful if the format adhered to an `xpath` or `jsonpath` extraction format. 

The the following could be supported
```
"foo": {
    "bar": [
      { "baz": "cat" },
      { "baz": "gif" },
      { "baz": "hotel_california" }
    ]
  }
``` 

```
{
  "set": {
    "field": "bazes",
    "value": "{{$foo.bar[*].baz}}"
  }
}
```
```
{
   "bazes": ["cat", "gif", "hotel_california"]
}
```

Right now the format only really supports
```
{
  "set": {
    "field": "bazes",
    "value": "{{$foo.bar.0.baz}}"
  }
}
```

But easily getting all the elements (without a painless loop) would be beneficial.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
