### ISSUE TITLE
DEBUG-level logging of org.elasticsearch.action by default seems excessive

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51198]
In 2bb31fe74037a7ee2a04c9a994bc4bacbc8e8102 (v0.6.0!) we added `DEBUG`-level logging to the default config of the `action` logger "for easier debugging". This lives on to this day in the default config and results in a good deal of log noise sometimes. For instance, an exception thrown in an implementation of `TransportMasterNodeAction#masterOperation` results in a retry or else it is propagated back to the caller but is also logged at `DEBUG` level, complete with stack trace, by `TransportMasterNodeAction` on the way past:

https://github.com/elastic/elasticsearch/blob/96b4f3df9067d579bf7e22e09613ea94f4f05462/server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java#L155-L166

It seems odd to single out this one package for `DEBUG`-level logs; these days many actions are in other packages (e.g. within `org.elasticsearch.xpack.*`). Do we still see value in this being part of the out-of-the-box default config? I think we should move to not emitting any `DEBUG`-level logs by default.

**Comment by nik9000** [comment]
>  I think we should move to not emitting any `DEBUG`-level logs by default.

+1. I think that is what DEBUG is supposed to mean. When I first saw these were on years ago I thought it was a temporary thing. Then I forgot about it.

**Comment by DaveCTurner** [comment]
Seeing no objections, I opened https://github.com/elastic/elasticsearch/pull/51459
