### ISSUE TITLE
Enable `index_prefixes` by default

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#51216]
By default `text` fields expand a `prefix` query to all matching terms in the dictionary. This makes the behavior consistent, all documents that should match are visited, at the cost of slow queries. 
However for positional queries such as `match_phrase_prefix` we have to limit the expansion to a small number of terms since each prefix match must be validated with the other terms in the phrase. The option `index_prefixes` circumvents this issue by indexing 2-5 grams so that each prefix can be handle as a single inverted list. This allows to handle prefixes correctly in positional queries at the cost of slower indexing and bigger index. The trade-off is hard to find but users can be confused when a `match_phrase_query` doesn't return the expected documents by default.
 
For correctness we should look at enabling `index_prefixes` by default. For instance we could:

1. Enable `index_prefixes` by default on `text` field.
2. Or change the default mapping for `string` (dynamic mapping) to:
````
{ type: text, index_prefixes: {}, fields: { keyword: { type: keyword, ignore_above: 256 } } }
````

We should also look at the cost of enabling `index_prefixes` in terms of index size and indexation speed to get more insights.

**Comment by jpountz** [comment]
I am a bit on the fence about indexing prefixes by default (option 1), which I would probably find surprising as a user. I still need to make my mind about option 2 but I think it would be quite consistent with the dual keyword mapping in the sense that it would trade disk usage for flexibility, and I like the fact that it would also raise awareness about this feature.

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
