### ISSUE TITLE
Avoid creating a default SSLContext if not necessary

### ISSUE THREAD

**Issue by gsmet** [elastic/elasticsearch#51225]
Hi,

Quarkus developer here: we are trying to optimize the Elasticsearch REST client bootstrap for a very specific use case: when you use our live coding feature, we restart the server for each page refresh if there were changes to the code so we need the restart to be as optimized as possible.

When you're coding your application locally, there's a good chance you will use a local Elasticsearch cluster without SSL. In this case, we could avoid creating the `SSLContext` altogether as it's really something very slow.

Unfortunately, it's not doable right now because the Elasticsearch REST client forces the initialization of a default `SSLContext` here: https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java#L212 .

I wonder if the fix could be as simple as dropping this line as `HttpAsyncClientBuilder` seems to properly define a default context if the context is null. See https://github.com/apache/httpasyncclient/blob/4.1.4/httpasyncclient/src/main/java/org/apache/http/impl/nio/client/HttpAsyncClientBuilder.java#L649 .

Or maybe the default context from the Http Async client is not good enough for you?

We would appreciate if we could come up with a solution for this one as it's a significant part of the Hibernate Search + Elasticsearch bootstrap when doing live coding and it makes the developer experience more painful than it needs to be.

Thanks.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
