### ISSUE TITLE
[DOCS] Would like to include some verbiage on java time vs joda time

### ISSUE THREAD

**Issue by jkelastic** [elastic/elasticsearch#51236]
**Elasticsearch version** (`bin/elasticsearch --version`): ES 6.8 and ES 7.0

**Description of the problem including expected versus actual behavior**: Users would benefit from some verbiage describing the migration of joda to java date time format in our official documentation to reflect that recommendation:

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_name.html

From our research, we think it's the difference between Joda time and Java time.

The Java time library <https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html> seems to prefer yyyy to YYYY:

y year-of-era year 2004; 04
Y week-based-year year 1996; 96

Since ISO weeks and years might have changed, that would explain why it suddenly the year said 2020 instead of 2019.

**Comment by pgomulka** [comment]
hey @jkelastic you mean specifically the migration?
We made few attempts to document this, but maybe we could improve it further
have a look into this first : https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_java_time_changes
Then there is a support knowledge article, maybe we could compile some information from it and expose it in our elasticsearch documentation?
https://github.com/elastic/support-knowledge-articles/blob/master/Knowledge%20Share/Elasticsearch%20Joda%20-%20Java%20migration.md

And lastly there is a blog post about that:
https://www.elastic.co/blog/journey-support-nanosecond-timestamps-elasticsearch

Let me know what documentation should contain. Just the migration process? Also let me know if the  information from the links above would be sufficient or we should try to expand on this?

**Comment by jkelastic** [comment]
@pgomulka Yes, specifically on the migration. Thanks for the links. I think I've also provided some of the links to the customer. However, what he's expecting is have them referenced in the usage section of our docs below

For example

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_name.html

on top of the breaking changes as breaking changes will only appear in the ES version this problem exist. Customer would have a hard time realizing this change if they aren't installing the breaking change ES version.

**Comment by pgomulka** [comment]
closed by https://github.com/elastic/elasticsearch/pull/51986
