### ISSUE TITLE
Extend Yml dsl framework to skip per JDK version

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#51248]
often times we depend on a feature available in certain JDK version. Given we support versions since jdk8 in 7.x branch it would be useful to write tests that depend on features available in newer versions.
Example would be loading SPI from classpath is a feature available since JDK9 (used for IsoCalendarProvider) https://github.com/elastic/elasticsearch/pull/50916

**Comment by mark-vieira** [comment]
Given we've bumped master to Java 17 I'm not sure this is really an issue. We are no longer using multi-release jars so we don't have any Java runtime specific functionality that I'm aware of.

**Comment by pgomulka** [comment]
I think this would be useful for bwc testing or 7.x branch testing. This is where jdk8 still can be used in testing as per https://www.elastic.co/support/matrix#matrix_jvm
Imagine a test (not sure we have one like this at the moment) where a search is using a week based year date format. This format depends on a definition of first day of the week and a rule how to calculate first week of a year. We define these in https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/server/src/main/java/org/elasticsearch/common/time/IsoCalendarDataProvider.java#L14 and use a feature available since jdk9 to allow loading extension classes from classpath https://bugs.openjdk.java.net/browse/JDK-8062588

I would consider this a super minor issue though

**Comment by rjernst** [comment]
This issue has been open a while and hasn't gained any traction. Given that I'm going to close, and we can reopen if necessary.
