### ISSUE TITLE
remove final from SearchHit class to be able to mock it in unit tests

### ISSUE THREAD

**Issue by clakech** [elastic/elasticsearch#51242]
Elastic client does not help users to mock it when developing repositories to manage queries/indexation in elastic because several methods of RestHighLevelClient are final and other sub classes used are final as SearchHit. Even mockito does not support final classes mocking. And mocking final stuff is hard.

Maybe provide a sample of unit testing a Reposity using the RestHighLevelClient for indexing/searching with ability to simulate mocked response like SearchHit, Errors etc. And remove final modifiers.

**Comment by cbergau** [comment]
Mockito does support mocking final stuff: https://www.baeldung.com/mockito-final

But i agree with you, i want SearchHit to not be final aswell.

**Comment by clakech** [comment]
When we tried this Mockito plug-in, then the tests become very slow

**Comment by xeraa** [comment]
Just for reference, this was already discussed in #31065, #34244, and #40534 (with some workarounds).

**Comment by cshunsinger** [comment]
Same thing with my team. The Elasticsearch library is the worst Java library ever made. There is no reason why the exposed API classes should be final. I personally have yet to run into a scenario where there is any good reason to make a class 'final'.

There are a lot of people who have raised issues related to being unable to mock these 'final' classes. Mockito final is a nice workaround, but that's all it is: a workaround.

Perhaps the ES developers should stop saying "What's wrong with our users!?" and instead say "What's wrong with our API?"

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
