### ISSUE TITLE
[CI] DedicatedClusterSnapshotRestoreIT.testMasterShutdownDuringSnapshot failure

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#51253]
Encountered this failure on a feature branch https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/14196/

A build scan is available here https://gradle-enterprise.elastic.co/s/y3sp3pow27tp2

**Comment by original-brownbear** [comment]
Looks like this may have been introduced by https://github.com/elastic/elasticsearch/pull/50788 ... will create a fix shortly
