### ISSUE TITLE
[Webhook Action] Question Mark (?) is being URL encoded in HTTP request from Elasticsearch

### ISSUE THREAD

**Issue by richiejarvis** [elastic/elasticsearch#51257]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.1

**Plugins installed**: [] default

**JVM version** (`java -version`): Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_232/25.232-b09

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**:
In 6.8.6, a webhook with a question mark `?` in the path field will cause an HTTP POST request to be sent with a `?`.  In 7.5.1, if a question mark is included, it is encoded as `%3F`.

**Steps to reproduce**:
1. Create the following watcher: 
```
PUT _watcher/watch/test2
{
  "trigger" : {
    "schedule" : {
      "hourly" : { "minute" : 30 }
    }
  },
  "actions": {
    "my_webhook": {
      "webhook": {
        "host": "<Server IP Address>",
        "port": 8888,
        "method": "POST",
        "path": "/path1/path2/SOAP?WSDL",
        "headers": {
          "Content-Type": "application/soap+xml; charset=utf-8"
        },
        "body": ""
      }
    }
  }
} 
```
2. Start a netcat server with `nc -kl -s <server-ip-address> -p 8888` to receive the request from the triggered watcher.
3. Trigger the watcher with `PUT _watcher/watch/test2/_execute`
4. Repeat on v7.5.1.

In v6.8.6, the request received shows:
```
POST /path1/path2/SOAP?WSDL HTTP/1.1
```

In v7.5.1, the request received shows:
```
POST /path1/path2/SOAP%3FWSDL HTTP/1.1
```

**Workaround:**
In some cases, clever use of the Webhook Params option bypasses the URL encoding of the path field as shown here: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/actions-webhook.html#webhook-query-parameters

The resulting test webhook:
```
PUT _watcher/watch/test2
{
  "trigger" : {
    "schedule" : {
      "hourly" : { "minute" : 30 }
    }
  },
  "actions": {
    "my_webhook": {
      "webhook": {
        "host": "<Server IP Address>",
        "port": 8888,
        "method": "POST",
        "path": "/path1/path2/SOAP",
        "params": {
          "wsdl": ""
        },
        "headers": {
          "Content-Type": "application/soap+xml; charset=utf-8"
        },
        "body": ""
      }
    }
  }
}
```

The request received then looks like this:
```
POST /path1/path2/SOAP?wsdl= HTTP/1.1
```

**Comment by richiejarvis** [comment]
An additional workaround is to use the following structure in the Webhook:

```
webhook": {
    "scheme": "https",
    "host": "<soap-server>/path1/path2/SOAP?wsdl",
    "port": 443,
    "method": "post",
    "params": {
    },
```

**Comment by fdartayre** [comment]
This is a breaking change that should at least be documented.

**Comment by richiejarvis** [comment]
@fdartayre It is a breaking fix I suppose?  Once fixed, it is back to how it was before afaik.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
