### ISSUE TITLE
ElasticSearch crashes with EXCEPTION_ILLEGAL_INSTRUCTION error

### ISSUE THREAD

**Issue by twjs76** [elastic/elasticsearch#51261]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.5.4, Build: default/zip/d2ef93d/2018-12-17T21:17:40.758843Z, JVM: 11.0.4

**Plugins installed**: [searchguard]

**JVM version** (`java -version`):
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
- Windows Server   2012 R2 Standard Edition: ServerStandard (6.3 Build 9600)
- AMD Opteron(tm)   Processor 6180 SE

**Description of the problem including expected versus actual behavior**:
After a reboot (which is performed nightly), ElasticSearch will suddenly no longer be able to start. A fatal JRE error will be reported, memory dump written and the process crashes. Subsequent attempts to start ElasticSearch are met with the same error. Deleting the ElasticSearch index helps temporarily, and the system will run normally (i.e. data will be indexed and searches will be executed no problem) however at some point the issue will reoccur after a reboot.

**Steps to reproduce**:
I have not been able to reproduce the issue locally unfortunately, it only seems to happen on a small number of (live) customer systems. One interesting thing that I've noticed, is that on all of the systems with this issue (3 so far), they have AMD Opteron processors. This issue happens with both G1GC and ConcMarkSweepGC.

**Provide logs (if relevant)**:
[elasticsearch.out.log](https://github.com/elastic/elasticsearch/files/4092452/elasticsearch.out.log)
[hs_err_pid17828.log](https://github.com/elastic/elasticsearch/files/4092453/hs_err_pid17828.log)

**Comment by jasontedor** [comment]
Please see #49178 where I have diagnosed this issue as a JVM bug. I provided a flag there that you can use to workaround the issue.
