### ISSUE TITLE
Feature Request - Add max_score to be available in painless script of score conext.

### ISSUE THREAD

**Issue by ialisyed** [elastic/elasticsearch#51317]
Please add max_score to be accessible inside painless script of score context, so that we can normalize score w.r.t max score. for the docs.

**Comment by rjernst** [comment]
Normalizing scores isn't really possible, at least not in a generic way that could be done for all possible queries. See https://cwiki.apache.org/confluence/display/lucene/ScoresAsPercentages. As there is nothing that can be done here, I hope you don't mind that I close this issue.
