### ISSUE TITLE
Keep bracket access, but change DocLookup to a non-map

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#51373]
As mentioned in https://github.com/elastic/elasticsearch/issues/8990, throwing an exception for unmapped fields is outside of the contract of `Map`.

Instead, we should implement our own data type with the methods we implement and their contracts since we don't use most of the map API currently.

Of course, we should keep bracket access available.

**Comment by jdconrad** [comment]
Covered by the fields api.
