### ISSUE TITLE
Package versioning ( Deb & RPM ) modifications

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#5138]
Currently when releasing multiple packages of the same version result in some issues this is because we don't add a package version.
The package version is used to determine which package is the latest at a new install or available for for upgrading.

The new package naming convention should be:

elasticsearch-x.x.x-yy(.zzz)

x.x.x is the actual version; for example 1.0.0
yy is the package version. For stable/final releases this is '1'. for any release before that we start at '0.1' and increment it for every release.
zzz is optional and can contain any string like 'Beta1' or 'RC2'.

The resulting package naming for 1.0.0 is:

elasticsearch-1.0.0-0.1.Beta1
elasticsearch-1.0.0-0.2.Beta2
elasticsearch-1.0.0-0.3.RC1
elasticsearch-1.0.0-0.4.RC2
elasticsearch-1.0.0-1

**Comment by clintongormley** [comment]
Our current package naming now allows for packages to be sorted correctly, without requiring a package version.  Closing
