### ISSUE TITLE
Create GET _cat/transforms API

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#51412]
See https://github.com/elastic/elasticsearch/pull/51364 for more info on how to do this (but obviously put this API in the `transforms` plugin).

This API should return basic statistics and settings that effect those statistics. 

I think the `GetTransformStatsAction` is a good place to start.

**Comment by zacharymorn** [comment]
hi @benwtrent, I'm interested in this task. To clarify, is the ask to enable an API endpoint to use the existing `GetTransformStatsAction` to return already available stats result (used in Gateway context maybe?), or there might be more stats that need to be added into the action for this API?

**Comment by benwtrent** [comment]
@zacharymorn the stats call does return a ton of info. But, I think more information about the transform itself should be added.

But some additional information from the `GetTransformAction`:

- source indices
- destination indices
- description
- version
- creation time
- frequency
- and maybe something indicating if it is continually looking at data or is/was batch (continuous is indicated if it has a sync config).

Here is an example of a similar change: https://github.com/elastic/elasticsearch/pull/52260

If you wish to take the issue, feel free. Please assign it to yourself to indicate you are working on it.

**Comment by zacharymorn** [comment]
@benwtrent Thanks for the additional information. The needed changes are clear and I'll start to work on it.

I've also gone through the internal process to get the approval to contribute on behalf of the company I'm working for  (Amazon). I'll work with the relevant internal team to see how we can best contribute. Please let me know if you have any suggestion as well as this is the first time I'm contributing on behalf of a company.

Thanks,
Zach

**Comment by sophiec20** [comment]
@zacharymorn We'd like to try to get this enhancement in for our next minor and there is a small window in which to do this. Thanks for your interest but we've found internal resource and we aim to be working on this shortly.

**Comment by zacharymorn** [comment]
@sophiec20 Thanks for letting me know. I've actually worked on this over the weekend and should be able to open a PR tonight, please let me know if that will work for you.

**Comment by zacharymorn** [comment]
@sophiec20  I've gone ahead and opened the PR. Please let me know if it looks good to you.
