### ISSUE TITLE
Shard balancer prefers to rebalance larger indices in a hot/warm cluster

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51422]
Today the shard balancer selects the most unbalanced index and then attempts to move one of its shards to improve the balance of the cluster. We don't take any allocation filtering into account when finding the most imbalanced index, and indices with more shards are heavier, so we may sometimes focus attention on larger indices when rebalancing. Having chosen an index we iterate through the pairs of heavy/light nodes and perform the first valid heavy-to-light relocation that we can find.

This seems to be particularly problematic when adding an empty warm node to a hot/warm cluster, because having selected a high-shard-count (warm) index it's likely that the balancer will find it worthwhile to rebalance one of its shards onto the new, empty, node. This may not, however, affect the total imbalance of that index enough, so on the next iteration it may well select this same index again and move another one of its shards onto the new, empty, node. The ultimate consequence is that the new node receives more than its fair share of shards from high-shard-count indices.

Eventually the new node's shard count will match its peers closely enough that index balancing will overrule this effect and the end result will be properly balanced. There is, however, a risk that the node cannot cope with all the intermediate states, particularly if these shards consume a lot of heap space. High-shard-count indices are often larger, particularly if they are rolled over on a fixed-age basis (e.g. daily), which makes this risk even more likely.

For example, consider a cluster with three hot nodes and three warm nodes. The hot nodes have 200 shards each; warm nodes `wrm-0` and `wrm-1` have 700 shards and the final warm node `wrm-2` is in the process of joining the cluster so currently only has 400 shards. This means the average number of shards per node is 400.

For example, here is an imbalanced situation that the balancer makes worse on its way to making it better. Consider a 12-shard index in the warm tier which has the imbalanced allocation `wrm-0: 3`, `wrm-1: 3` and `wrm-2: 6`. It has a `delta` of `226.65`:

```
node [hot-0] total: [200] vs [400] => total weight [-200]; index: [0] vs [2] => index weight [-2] ==> overall weight [ -91.10] ** minimum
node [hot-1] total: [200] vs [400] => total weight [-200]; index: [0] vs [2] => index weight [-2] ==> overall weight [ -91.10]
node [hot-2] total: [200] vs [400] => total weight [-200]; index: [0] vs [2] => index weight [-2] ==> overall weight [ -91.10]
node [wrm-0] total: [700] vs [400] => total weight [+300]; index: [3] vs [2] => index weight [+1] ==> overall weight [+135.55] ** maximum
node [wrm-1] total: [700] vs [400] => total weight [+300]; index: [3] vs [2] => index weight [+1] ==> overall weight [+135.55]
node [wrm-2] total: [400] vs [400] => total weight [   0]; index: [6] vs [2] => index weight [+4] ==> overall weight [  +2.20]
``` 

Now consider a 2-shard index in the warm tier which is allocated `wrm-0: 1`, `wrm-1: 1` and `wrm-2: 0`. It has a `delta` of `225.55`:

```
node [hot-0] total: [200] vs [400] => total weight [-200]; index: [0] vs [0.3333] => index weight [-0.3333] ==> final weight [ -90.18] ** minimum
node [hot-1] total: [200] vs [400] => total weight [-200]; index: [0] vs [0.3333] => index weight [-0.3333] ==> final weight [ -90.18]
node [hot-2] total: [200] vs [400] => total weight [-200]; index: [0] vs [0.3333] => index weight [-0.3333] ==> final weight [ -90.18]
node [wrm-0] total: [700] vs [400] => total weight [+300]; index: [1] vs [0.3333] => index weight [+0.6666] ==> final weight [+135.37] ** maximum
node [wrm-1] total: [700] vs [400] => total weight [+300]; index: [1] vs [0.3333] => index weight [+0.6666] ==> final weight [+135.37]
node [wrm-2] total: [400] vs [400] => total weight [   0]; index: [0] vs [0.3333] => index weight [-0.3333] ==> final weight [  -0.18]
```

Since the 12-shard index is more imbalanced by this measure, the balancer will consider it first. The lightest node that can accept another shard of this index is `wrm-2` thanks to allocation filtering, so the balancer will decide to move yet another shard onto this node, further exacerbating the imbalance in this index.

**Comment by idegtiarenko** [comment]
Desired balance will address this issue
