### ISSUE TITLE
Escape non-alphanumeric fields for EQL

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#51443]
We need to add an escape sequence for fields that don't follow the typical IDENTIFIER regex: `[_A-Za-z0-9][_A-Za-z0-9]*`

One thought, and currently in the #49658 PR is to use back ticks ` around special fields. I believe this is how MS SQL works, and we currently check for that syntax within the SQL plugin but mark it as unsupported: https://github.com/elastic/elasticsearch/blob/ec1ac0d463bfa12a02c8174afbcdd6984345e8b4/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/SqlParser.java#L161-L169

We should decide on an intuitive syntax that doesn't compete with single and double quotes.

**Comment by costin** [comment]
I've added the discuss label so we can tackle it on our next meeting.

**Comment by rw-access** [comment]
We decided in the 2020/03/19 weekly sync to stick with backticks. Closing.

**Comment by colings86** [comment]
@rw-access I'm not sure you meant to close this? We should keep the issue open until we have made and merged the change/enhancement/feature.

**Comment by rw-access** [comment]
@colings86 we implemented and added tests for the backticks in #49658, but afterwards weren't 100% sure if that was the desired approach. we opened this issue to discuss and track what we decided. since we decided to keep the **\`\** escaping **\`\**, I closed it

**Comment by colings86** [comment]
Ah ok, that makes sense. Sorry for the confusion
