### ISSUE TITLE
parsing logs with filebeat modules to logstash

### ISSUE THREAD

**Issue by atefeh99** [elastic/elasticsearch#51458]
i have installed logstash 7.4.1 in my vmware and elasticsearch 7.4.1 . besides that i have installed filebeat 7.4.1 in a remote machine and want to send logs with apache module pipeline into my logstash.then logstash send logs to elasticsearch and make an index. my problem is when i run pipeline with the command "./filebeat setup --pipelines --modules apache" and start all services there is no index in elasticsearch.
i set my logstash ip and port in filebeat.yml and disable elasticsearch output . following lines are the content of logstash configuration file 
input {
  beats {
    port => 5044
    host => "0.0.0.0"  
}
}

output {
  if [@metadata][pipeline] {
    elasticsearch {
      hosts => "127.0.0.1:9200"
      manage_template => false
      index => "apache-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      pipeline => "%{[@metadata][pipeline]}"
    }
  } else {
    elasticsearch {
      hosts => "127.0.0.1:9200"
      manage_template => false
      index => "atefeh-%{[@metadata][version]}-%{+YYYY.MM.dd}"
    }
  }
}

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
