### ISSUE TITLE
Add support for newer versions of supported OS

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#51481]
As we aim to remove support for older OS that are seeing their end-of-life (#51480), we should investigate adding support for newer versions of these OS:
- [x] CentOS 8
- [x] Oracle Enterprise Linux 8
- [x] Ubuntu 20.04
- [x] openSUSE Leap 15

We should endeavor to add support for these in 7.x.

**Comment by pugnascotia** [comment]
Have we asked Infra about making images available for CI? We'll likely want images for Vagrant as well.

**Comment by jasontedor** [comment]
@pugnascotia I think that part of this issue will include doing the leg work or coordination to ensure that we have the appropriate images available. I agree that we will want Vagrant boxes for these for local testing (I think there's a case right now of there being an OS in the support matrix but we don't have a Vagrant image built yet, I can't remember which it is that is like that).

**Comment by rjernst** [comment]
> I think there's a case right now of there being an OS in the support matrix but we don't have a Vagrant image

That is for Debian 10.

> Have we asked Infra about making images available for CI?

We (@mark-vieira and myself) have been discussing with infra on getting the vagrant images closer in sync with the GCP images we use for CI.

**Comment by mark-vieira** [comment]
Ryan and I discussed the current Vagrant situation with @leathekd last week. Essentially, this work got deprioritized a bit since it wasn't clear to infra that anyone was actually using those images. We've since clarified that we do indeed use those images and David is looking into pressing forward with integrating Vagrant images into the new Packer 2.0 build processes.

**Comment by pugnascotia** [comment]
Cool, once any new Vagrant images are available, I'm happy to do the work to start using them in the ES repo.

**Comment by mark-vieira** [comment]
We are now running both platform support and packaging tests on CentOS 8 in `master` and `7.x`.

**Comment by mark-vieira** [comment]
@jasontedor what's our status on Fedora? We don't list it on the support matrix yet we test against Fedora 29 and there's an [open infra issue](https://github.com/elastic/infra/issues/15769) to bump to Fedora 31.

**Comment by jasontedor** [comment]
We treat it like macOS, we don’t support it on production but we work to maintain Elasticsearch on it. We do this for a few reasons:
 - it’s a very popular OS amongst developers
 - it’s on the cutting edge of kernel versions and other Linux advancements so it gives us a way to stay ahead of the maintenance curve there
 - advancements in it often end up in CentOS/Red Hat, OS that we do support, so again we stay ahead of the curve

**Comment by mark-vieira** [comment]
Thanks, @jasontedor. Also, it looks like we are already testing on opensuse 15. I believe we have been for awhile. I think we can scratch that one as well, although it's not yet on the support matrix.

**Comment by markwalkom** [comment]
Ubuntu 20.04 came out a few months ago, it'd be great if we could get this added to the done list :)

**Comment by mark-vieira** [comment]
I've opened an [infra issue](https://github.com/elastic/infra/issues/22922) to get an image built so we can begin testing on this platform.

**Comment by bytebilly** [comment]
Oracle Linux 8 has been added to test matrix! 🎉 

https://github.com/elastic/infra/pull/25624

**Comment by mark-vieira** [comment]
Closing this now that Oracle linux is :+1:
