### ISSUE TITLE
[DOCS] Improvement request for email account configuration

### ISSUE THREAD

**Issue by dharada** [elastic/elasticsearch#51485]
**Describe the feature**: This is not feature request, but just a document improvement.

**Elasticsearch version** (`bin/elasticsearch --version`): 

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:

We need to configure `email account` in elasticsearch.yml to send email notifications with email action of watcher.
but it seems current documentation doesn't describe regarding WHICH nodes. I think we don't need to configure on ALL nodes.

```
Use the email action to send email notifications. To send email, you must configure at least one email account in elasticsearch.yml.
```

https://www.elastic.co/guide/en/elasticsearch/reference/master/actions-email.html

Could you add some explanation which node's elsticsearch.yml should be configured for `email account` ?

It seems it should be configured on `Data nodes` which have `.watches` shards. (please correct me if this is wrong understanding.)
https://www.elastic.co/guide/en/elasticsearch/reference/current/how-watcher-works.html#watch-execution

(just a ref) - https://github.com/elastic/elasticsearch/pull/36543

**Comment by ypid-geberit** [comment]
https://www.elastic.co/blog/distributed-watch-execution-elasticsearch-6.0 describes the details, but I was also missing that information in the documentation itself so I agree with @dharada that this should be added.
