### ISSUE TITLE
HTTP 500 response to invalid dynamic_mappings syntax

### ISSUE THREAD

**Issue by jowiho** [elastic/elasticsearch#51486]
**Elasticsearch version**: 7.5.2

**Plugins installed**: []

**JVM version**: (Elastic Cloud)

**OS version**: (Elastic Cloud)

**Description of the problem including expected versus actual behavior**:

_Actual behavior:_ An (invalid) mappings update request, where `dynamic_mappings` is an object instead of an array, results in a http response with a 500 code. 

_Expected behavior:_ A 400 (bad request) http response code.

**Steps to reproduce**:

 1. Create a new index `my_index`
 2. Send the following request through Kibana's console
```
PUT /my_index/_mappings
{
  "dynamic_templates": {}
}
```
3. Notice the 500 response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "class_cast_exception",
        "reason": "class java.util.LinkedHashMap cannot be cast to class java.util.List (java.util.LinkedHashMap and java.util.List are in module java.base of loader 'bootstrap')"
      }
    ],
    "type": "class_cast_exception",
    "reason": "class java.util.LinkedHashMap cannot be cast to class java.util.List (java.util.LinkedHashMap and java.util.List are in module java.base of loader 'bootstrap')"
  },
  "status": 500
}
```

**Comment by lmenezes** [comment]
@elasticmachine care if I send a PR to fix this?

**Comment by jimczi** [comment]
Thanks @lmenezes, elasticmachine doesn't care ;) but I am sure our CI will be very happy to test your pr if you send one ;).
