### ISSUE TITLE
Drop support for older OS in the next major release

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#51480]
The following OS have or will soon see their end-of-life. Therefore, Elasticsearch will drop support for these OS in its next major release:
- CentOS 6 (November 30, 2020)
- Oracle Enterprise Linux 6 (March, 2021)
- Ubuntu 16.04 (April, 2019, security updates end in 2021)
- openSUSE Leap 42 (June, 2019)
- Debian 8 (June 30, 2020)
- Amazon Linux (June 30, 2020)

**Comment by mark-vieira** [comment]
I believe https://github.com/elastic/elasticsearch/pull/51499 and https://github.com/elastic/infra/pull/17537 have resolved this issue as we are no longer doing any testing on the above listed OSes on `master`.  @rjernst am I missing anything?

**Comment by rjernst** [comment]
Yes I think this is complete with both of those.
