### ISSUE TITLE
HttpExportBulk: IllegalArgumentException: Values less than -1 bytes are not supported

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#51489]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.x

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem**:

Customer reports an issue with stats being sent to the monitoring cluster for a specific node.  That node reports this error:

```
[2020-01-24T16:53:43,545][WARN ][o.e.x.m.e.h.HttpExportBulk] [tor63velam101] failed to render document [org.elasticsearch.xpack.monitoring.collector.cluster.ClusterStatsMonitoringDoc@834bdae7], skipping it [xpack.monitoring.exporters.id1]
java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -9223371986295221505b
```

User reported this issue was resolved after node was removed from the cluster for some disk maintenance, then reintroduced.

**Comment by steevo590** [comment]
To clarify, those errors appeared when the only shard on the node was a replica of ".security-7", it had been excluded to allow some disk maintenance.

**Comment by jbaiera** [comment]
@pugnascotia @steevo590 Do you have the OS version that these showed up on?

**Comment by steevo590** [comment]
Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.6.2.el7.x86_64
      Architecture: x86-64

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
