### ISSUE TITLE
SQL: use calendar interval of 1m instead of fixed interval for grouping by Month and HISTOGRAMs 

### ISSUE THREAD

**Issue by elasticforme** [elastic/elasticsearch#51538]
Currently when use interval 1M it gives wrong answer.
can this be fixed for something like this https://github.com/elastic/elasticsearch/pull/47558.

here is what I mean https://discuss.elastic.co/t/sql-query-histogram-interval-one-month-problem/216442/5

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/928b11a34ec92d90d082abdf4fa09f7ce1d7c0c4
7.x (7.7.0): https://github.com/elastic/elasticsearch/commit/ed6b10bc038d7658dca157bcf4d74625855ca9b2
