### ISSUE TITLE
ILM: Allow to have a policy to roll over after given size and still delete after a number of days from creation even if rollover didn't happen

### ISSUE THREAD

**Issue by JohannesMahne** [elastic/elasticsearch#51533]
**Describe the feature**:

Requesting a feature that would allow the following scenario: 
- to allow to manage index size (ie. roll over after 30gb), plus
- to allow for a data retention period enforcement (ie. your indices need to be deleted after 30 days). 

Currently, the deletion phase happens `x` number of days/hours after the `rollover date`. The feature request, therefore, asks to allow another option that the deletion should happen `x` number of days/hours after the `creation date` of the original index, regardless of the fact that it is rolled over or not.

**Example**:
I want to keep my indices not to grow over 30gb in size, but I want to make sure that I don't keep more than one month's data.

**Comment by andreidan** [comment]
@JohannesMahne this is currently possible using the [`origination date`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-settings.html) which, if configured for an index, all the phase timings will be calculated based on it (for more details we wrote a [blog post](https://www.elastic.co/blog/control-ilm-phase-transition-timings-using-origination-date?blade=tw&hulk=social) with more details about how it works) 

In your case, given a policy as follows:
```
PUT /_ilm/policy/30gbs_30days
{ 
  "policy": { 
    "phases": { 
      "hot": { 
        "actions": { 
          "rollover": {
            "max_age":   "30d",
            "max_size":  "30gb" 
          } 
        } 
      }, 
      "delete": { 
        "min_age": "30d", 
        "actions": { 
          "delete": {} 
        } 
      } 
    } 
  } 
}
```
(note `max_age` on the rollover action makes sure the index is rolled and moved into the delete phase even if the `max_size` condition was not triggered)
you could apply it to an index and set the origination date to the _current date_ (the creation date). eg.
```
PUT /events-2020.01.28 
{ 
  "settings" : { 
    "index" : { 
      "lifecycle.name": "30gbs_30days", 
      "lifecycle.parse_origination_date": true
    } 
  } 
}
```
or if the date is something you don't want to incorporate in your index name you can manually set the origination date: 
```
PUT /events 
{ 
  "settings" : { 
    "index" : { 
      "lifecycle.name": "30gbs_30days", 
      "lifecycle.origination_date": 1580169600000
    } 
  } 
}
```

Does this cover your use case?

**Comment by Scha7ten** [comment]
![Policy en](https://user-images.githubusercontent.com/60462812/73430231-d1ca8d00-433d-11ea-9308-8e2bdab463f5.png)
My company wants Kibana to do what I put in the picture. But when I try to PUT into an existing index, it gives me an error message saying that the index already exists. I thought, PUT is to update existing things and can be used for creating new.

**Comment by Scha7ten** [comment]
Is it possible tpo manually change the size of an index that is set to "is_write_to: false" for testing? Say I have an index of the size of 1 GB and for testing a new policy I want to make it have 30 GB

**Comment by JohannesMahne** [comment]
Thanks, @andreidan it does cover it. Thanks for the detail.

**Comment by zhangshp** [comment]
lifecycle.parse_origination_date  has timezone problem ,  I am in UTC/GMT+08:00, when I set ` "lifecycle.parse_origination_date": true`  use data stream ,  index is "test-2021.05.26-000001" , lifecycle_date_millis is "1621987200000". how to solve this problem?
