### ISSUE TITLE
[CI] LoggingOutputStreamTests fails on Windows

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#51532]
The following tests fail in 7.x Windows builds:

```
org.elasticsearch.common.logging.LoggingOutputStreamTests testBufferExtension
org.elasticsearch.common.logging.LoggingOutputStreamTests testEmptyLine
org.elasticsearch.common.logging.LoggingOutputStreamTests testFlushOnNewline
org.elasticsearch.common.logging.LoggingOutputStreamTests testMaxBuffer
org.elasticsearch.common.logging.LoggingOutputStreamTests testThreadIsolation
```

An example is https://gradle-enterprise.elastic.co/s/yiooghd5t4ai4 (but every 7.x Windows build is failing for this reason).

The errors are all along the lines of this:

```
Expected: iterable containing ["pjsQsvUyoViFJjlUeCGSsMwFyERKKNZexDFEkobYKBmMuiqRUjqKIGjFAIojNnJgIZAqCaewZeaiaIqRupTDLXQhPmAdaRTzNPLYypRYxiVeZQOycAVicOazPvUQifDNMOqaXIJJRAOrlndMd", "OVERFLOW"]
     but: item 1: was "\r"
```

It seems like the CRLF Windows line endings are messing up the line splitting.

**Comment by droberts195** [comment]
Unsurprisingly these same tests are also failing for the same reason on Windows on master.  They just didn't appear in the failure emails for master because so many other tests are also failing on Windows...

**Comment by cbuescher** [comment]
Several more of this today, e.g. https://gradle-enterprise.elastic.co/s/727tjb7hppge4 on 7.x or https://gradle-enterprise.elastic.co/s/pxnzjqw65ckj2 on master.

**Comment by mayya-sharipova** [comment]
Several more of these failures today on master:
The latest:

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2016/418/console
Build Scans: https://gradle-enterprise.elastic.co/s/63vvoouwnqwto
