### ISSUE TITLE
[CI] unknown setting [xpack.eql.enabled] in release-tests

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#51541]
The `xpack.eql.enabled` setting is only registered in snapshot builds.  This causes release-tests builds to fail with the following error:

```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.eql.enabled] did you mean any of [xpack.sql.enabled, xpack.ml.enabled, xpack.slm.enabled, xpack.ccr.enabled, xpack.ilm.enabled, xpack.rollup.enabled, xpack.enrich.enabled, xpack.graph.enabled, xpack.vectors.enabled]?
```

An example of a build that failed like this is https://gradle-enterprise.elastic.co/s/ihwtv5x2wbo4g

Something needs to be done to skip all EQL tests in release-tests builds.

**Comment by cbuescher** [comment]
More today: https://gradle-enterprise.elastic.co/s/3nvcuhhuotypq

**Comment by aleksmaus** [comment]
Will fix.
