### ISSUE TITLE
GET _warmer should return a 404 for warmers that do not exist

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#5155]
Doing the following in any of the 0.90 releases
```Shell
curl -XPOST "http://localhost:9200/my-new-index"
curl -XGET "http://localhost:9200/my-new-index/_warmer/this-warmer-does-not-exists"
```
Will result in:
```json
{
   "error": "IndexWarmerMissingException[index_warmer [this-warmer-does-not-exists] missing]",
   "status": 404
}
```
However in the 1.0 GA release the latter returns a 200 with the following body:
```json
{}
```

**Comment by javanna** [comment]
I agree that the get warmer api should be changed to return 404 when the warmer doesn't exist.

**Comment by jpountz** [comment]
Closing: warmers will go away in 3.0 #15614
