### ISSUE TITLE
Error while reindexing data: Mixing up field types [ ES version 5.4.3 ]

### ISSUE THREAD

**Issue by ashwani2797** [elastic/elasticsearch#51601]
Hi Team,

I am reindexing data because the required change type of field, but during reindexing, I got the error.

_Mixing up field types: class org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType != class org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType on field payment.additionalParams_

This additionalParams type is "Text" in both old and new mappings.
Its contains the stringify JSON:
For example:

additionalParams": "{\"CURRENCY\":\"INR\",\"redirectUrl\":\"9c2e1f025773c41e2c58a4ec5837efe8dfc5a43d1ea5c3105291017f8ac26c2b776ce7f6ccb5af7218bc678e6f5a19b4083ff5b1c157bdf650e5cd734a6e3663ba9286cd0d5706f986bfb3f13486536ca4b53bef50c4f106cde24aef67cb2986\",\"RESPMSG\":\"User has not completed transaction.\",\"orderId\":\"1580295987504\",\"MID\":\"NoBrok64803316911648\",\"MERC_UNQ_REF\":\"7009030043_ff8081815a701e88015a7f4d06d203a6\",\"RESPCODE\":\"141\",\"TXNID\":\"20200129111212800110168616311417623\",\"TXNAMOUNT\":\"10.00\",\"hashValue\":\"OIxc5Msu2Qu9OBgxuO/RuzwCggNLiwJxxmy20pK3nergGodbrQXmUHwH7Tj16cMy8sptfhrhowKI/7JtXrAFaApGO+kCLuxqVb1itR0bUo0=\",\"ORDERID\":\"1580295987504\",\"STATUS\":\"TXN_FAILURE\",\"BANKTXNID\":\"\",\"pg\":\"PAYTM\",\"CHECKSUMHASH\":\"lhCBMehDWysjQRctb3z9m5Y82Ja+AoF5Ap7dekW/Ru9KYVDZhoYiOFLaQWQM3Mxntyub+i/Nu3NgBm6Nkw2SMYiFgA9jUuh2xdRMwNglsE8=\"}",

**Comment by cbuescher** [comment]
Hi @ashwani2797! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by ashwani2797** [comment]
sure. Thanks.
