### ISSUE TITLE
[CI] Task ':printGlobalBuildInfo' failing often lately

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#51611]
Just saw this today: https://gradle-enterprise.elastic.co/s/n56o6hfi2rlwy

There is not much info in the logs except the cause seems to be some node is locked (Caused by: java.lang.IllegalStateException: Configuration for node{:docs:integTest-0} can not be altered, already locked)

```
Execution failed for task ':printGlobalBuildInfo'.
> Configuration for node{:docs:integTest-0} can not be altered, already locked

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':printGlobalBuildInfo'.
	at [...]
Caused by: java.lang.IllegalStateException: Configuration for node{:docs:integTest-0} can not be altered, already locked
	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.checkFrozen(ElasticsearchNode.java:1065)
	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.setTestDistribution(ElasticsearchNode.java:235)
		[...]
     
```

**Comment by cbuescher** [comment]
Some similar ones from the last days:
https://gradle-enterprise.elastic.co/s/hjjbecxax4bve/console-log?anchor=221
https://gradle-enterprise.elastic.co/s/u3sxom4vsr6ke/console-log#L97
https://gradle-enterprise.elastic.co/s/kua25c7yiun4o/console-log#L97
https://gradle-enterprise.elastic.co/s/4vgdz3gmzdy4q/console-log#L97

While the above all all on 7.6, there's also the same on 7.x, eg.
https://gradle-enterprise.elastic.co/s/72jglicttnuzg/console-log#L97
https://gradle-enterprise.elastic.co/s/wq2ao54xeiufo/console-log#L97

**Comment by jkakavas** [comment]
These are all in our new fips matrix jobs. I will investigate but it looks like the `setTestDistribution(TestDistribution.DEFAULT)` we added in 7.x  ( https://github.com/elastic/elasticsearch/pull/51333 ) is to blame

**Comment by cbuescher** [comment]
> These are all in our new fips matrix jobs

Right, I didn't pay attention to this. Thanks for noting, maybe still makes sense to track.

**Comment by mark-vieira** [comment]
So all the recent failures are `7.6`, this was fixed in `7.x` by #49485. @jkakavas do you mind backporting #49485 to `7.6`?

**Comment by mark-vieira** [comment]
ping @jkakavas

**Comment by jkakavas** [comment]
pong @mark-vieira : https://github.com/elastic/elasticsearch/pull/51660 :) (Forgot the `resolves:`)
