### ISSUE TITLE
[Java.time] Document or fix timeezone migration

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#51614]
The goal is document or add a feature that will help print/parse dates as they used previously after the migration from joda to java is performed by a user.
We should consider what should be adviced to users in doc for this scenario.

when migrating from joda, timezone specifier has changed behaviour. It previously in joda allowed parsing and printing all these formats:
```
           // hh
            // hhmm
            // hhmmss
            // hhmmssSSS
            // hh:mm
            // hh:mm:ss
            // hh:mm:ss.SSS
```

In order to achieve the same behaviour using java.time an optional section of a pattern has to be used.
For instance:
`YYYY-MM-dd'T'HH:mm:ss.SSSZZ` where `ZZ` means 
https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

> Zone: 'Z' outputs offset without a colon, 'ZZ' outputs the offset with a colon, 'ZZZ' or more outputs the zone id.

allows parsing all the mentioned formats with colon. In order to achieve that in java.time a format has to be changed to:
`yyyy-MM-dd'T'HH:mm:ss.SSS[XXXXX][XXX][X]`
where XXXXX parses Hour, Minute and Second with colon
XXX parses Hour and Minute with colon
X parses just Hour
I am skipping millisecond part as it is not defined in docs anyway.

If someone migrates `YYYY-MM-dd'T'HH:mm:ss.SSSZZ` -> `yyyy-MM-dd'T'HH:mm:ss.SSS[XXXXX][XXX][X]`
it will be able to parse all the date that was parasble with joda, 
but it won't be able print the same way. 
For formats mentioend above and input being parsed first 2020-01-01T01:01:01.001+01:02:03
Joda will print `2019-12-31T23:58:58.001+00:00`
Java will print `2020-01-01T01:01:01.001+01:02:03+01:02+0102`

**Comment by rjernst** [comment]
@pgomulka I don't think `yyyy-MM-dd'T'HH:mm:ss.SSS[XXXXX][XXX][X]` is a valid format someone would want to use. Instead, they would want one format for each of the possible timezones, ie:

```
yyyy-MM-dd'T'HH:mm:ss.SSS[X]|yyyy-MM-dd'T'HH:mm:ss.SSSXXX|yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX
```

**Comment by pgomulka** [comment]
closed by https://github.com/elastic/elasticsearch/pull/51986
