### ISSUE TITLE
high level rest client dependency for 7.5.2 comes with 6.4.3 transitive dependencies

### ISSUE THREAD

**Issue by LuckyLukas** [elastic/elasticsearch#51623]
**Elasticsearch version** (

7.5.2

**JVM version** (`java -version`): any JDK 8 or 11, gradle 4 and 5

**Description of the problem including expected versus actual behavior**:

actual: 
adding `compile group: 'org.elasticsearch.client', name: 'elasticsearch-rest-high-level-client', version: '7.5.2'`

to a gradle build, comes with `org.elasticsearch.client:elasticsearch-rest-client:6.4.3` and `org.elasticsearch:elasticsearch:6.4.3` as transitive dependencies

expected:

version: '7.5.2' of the transitive dependencies

***reproduce***:

simple gralde build, add the 7.5.2 high level rest client dependency;

```
 ./gradle :dependencyInsight --dependency :elasticsearch-rest-client:

> Task :dependencyInsight
org.elasticsearch.client:elasticsearch-rest-client:6.4.3 (selected by rule)
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

org.elasticsearch.client:elasticsearch-rest-client:7.5.2 -> 6.4.3
\--- org.elasticsearch.client:elasticsearch-rest-high-level-client:7.5.2
     \--- compileClasspath
```

**Comment by dadoonet** [comment]
Are you doing that with a spring boot project by any chance?

**Comment by dadoonet** [comment]
in case it helps, have a look at https://github.com/elastic/elasticsearch/issues/41189#issuecomment-483254425 if you are using Spring Boot.

**Comment by LuckyLukas** [comment]
ah I see, thanks
