### ISSUE TITLE
SQL: Enhance error messages for ordinals and ref aliases

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#51636]
Currently the `Verifier` produces error messages that refer to the original position of the referenced field in the SELECT clause instead of the position where the offending field is actually used. e.g.:
```
SELECT ST_AsWKT(shape) AS s FROM test WHERE s = 'point (10 20)'
```
Produces an error message like:
```
1:17: geo shapes cannot be used for filtering
```
instead of mentioning position: `1:45` and maybe the reference to the original field `shape`

**Comment by wchaparro** [comment]
Superceded by ES|QL
