### ISSUE TITLE
Allow doc values of nested documents to be used in scripts for sorting

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#51641]
It could be useful to be able to have a scripted query for sorting where the script
uses doc values from a nested document, which is currently not supported.

This came from an SQL use case, e.g.:
```
SELECT first_name f, YEAR(dep.from_date) start FROM test_emp WHERE dep.dep_name = 'Production' AND languages > 1 ORDER BY start
```
where the `dep` is the nested field of `test_emp` index.
In this case ORDER BY uses a scalar function which results to painless script which should be used to
execute the sorting.

**Comment by mayya-sharipova** [comment]
Here by `nested` you mean an elasticsearch [nested](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/nested.html) datatype?

If we want to sort documents by nested field values, and usually a document has several nested values, which value should be used for sorting?
For example, if `dep` is a nested field which value of `start_date` we should use for doc1?
```js
doc1:
"dep": [{"start_date": "2015-01-01"}, {"start_date": "2016-01-01"}]
```

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
