### ISSUE TITLE
response.Total does not match response.Document.Count() 

### ISSUE THREAD

**Issue by cgstevens** [elastic/elasticsearch#51656]
**Elasticsearch version**
7.5.0

**OS version**
OS[Windows 10/10.0/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]

**Description of the problem**

response.Total only shows 10000 when Document.Count() equals 12000
I would expect response.Total to be 12000 based on the description - Gets the total number of documents matching the search query criteria.
![TotalMismatch](https://user-images.githubusercontent.com/11180136/73413558-0a387f80-42da-11ea-924a-d43a55d9bb4a.jpg)

**Steps to reproduce**:

Create index.
Set the following on index.  : .Setting("max_result_window", 50000)
Populate index with 12000 documents.
Search with Skip = 0, Take = 15000. : Request: {"from":0,"size":12000}
Returns 12000 documents.  response.Document.Count() == 12000 but response.Total == 10000.
To provide the correct result I am doing another request which just does the count.  
Is this a bug or am I missing another setting?

Thanks for the help!  I really don't want to do another request just to get the accurate count if I don't have to.

var dummyContacts = new List<Contact>();
            for (int i = 0; i < 12000; i++)
            {
                var contact = new Contact();
                contact.ContactId = Guid.NewGuid();
                contact.Properties["FirstName"] = contact.ContactId.ToString().Substring(0, 12);
                contact.Properties["LastName"] = contact.ContactId.ToString().Substring(12, 12);

                dummyContacts.Add(contact);
            }

            // Start clean... delete index and populate with 12,000 dummy contacts.
            Target.BulkAll(dummyContacts, true).Wait();

version[7.5.0], pid[18044], build[default/zip/e9ccaed468e2fac2275a3761849cbee64b39519f/2019-11-26T01:06:52.518245Z], OS[Windows 10/10.0/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]

**Comment by dadoonet** [comment]
Have a look at https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-track-total-hits

Feel to ask your questions or share your doubts on discuss.elastic.co where we can help.

**Comment by cbuescher** [comment]
Hi @cgstevens, like @dadoonet already suggested, this question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead and to come back if it turns out this is more likely to be a bug that having to do with the above mentioned changes to track_total_hits.

**Comment by cgstevens** [comment]
Thank you so much @dadoonet! That did fix the problem.

**Comment by cgstevens** [comment]
Yeah... So many options and I didn't see this one and I didn't find my answer hence I posted here.  
Again thank you!
