### ISSUE TITLE
'enrich stats' API not included in 'monitor' security privilege

### ISSUE THREAD

**Issue by peterpramb** [elastic/elasticsearch#51677]
**Elasticsearch version**:
`Version: 7.5.2, Build: default/tar/8bec50e1e0ad29dad5653712cf3bb580cd1afcdf/2020-01-15T12:11:52.313576Z, JVM: 11.0.6`

**JVM version**:
`OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`

**OS version**:
`Linux 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 16 14:19:51 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Using Metricbeat's `elasticsearch` module with `xpack.enabled: true` and the built-in`remote_monitoring_user` to monitor the Elasticsearch instance gives HTTP/403 errors for the `enrich` [metricset](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-enrich.html).

It seems the `monitor` privilege does not cover the `enrich stats` [API](https://www.elastic.co/guide/en/elasticsearch/reference/current/enrich-stats-api.html), and therefore the `remote_monitoring_collector` role fails too.

As a workaround one can create a custom role with the `manage_enrich` privilege, but of course this is way too permissive just for monitoring.

**Provide logs (if relevant)**:
```
2020-01-30T14:55:24.941+0100	INFO	module/wrapper.go:252	Error fetching data for metricset elasticsearch.enrich: HTTP error 403 in : 403 Forbidden
```

**Comment by peterpramb** [comment]
Ok, it seems there is something else going on:

It turned out, that the errors only occur on the **active** master node. After failing the master over the errors disappear from the original master node's Metricbeat instance, but starts to show up on the new active master node's Metricbeat instance...

**Comment by peterpramb** [comment]
Anyway, this remains a permission issue:
```
$ curl -k -u remote_monitoring_user -XGET "https://localhost:9200/_enrich/_stats?pretty"
Enter host password for user 'remote_monitoring_user':
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "action [cluster:admin/xpack/enrich/stats] is unauthorized for user [remote_monitoring_user]"
      }
    ],
    "type" : "security_exception",
    "reason" : "action [cluster:admin/xpack/enrich/stats] is unauthorized for user [remote_monitoring_user]"
  },
  "status" : 403
}
```

**Comment by tvernum** [comment]
@martijnvg Is there a reason `EnrichStatsAction` is marked as an `admin` action (`"cluster:admin/xpack/enrich/stats"`) rather than a `monitor` action (e.g. XPackInfo is `"cluster:monitor/xpack/info"`) ?

**Comment by martijnvg** [comment]
@tvernum No, I don't think so. I think it got the current action name by mistake. The action name should be `cluster:monitor/xpack/info`.
