### ISSUE TITLE
Ability to invoke immediate unconditional rollover

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#51688]
There are two common circumstances when an immediate rollover is necessary

1) Part of the normal testing process.  Update template mappings, delete everything and start over.   However with Rollover, doing so [breaks things](https://github.com/elastic/elasticsearch/issues/41699) and requires re-boostrap.

2) In production when a pipeline is blocked and must immediately have a new mapping and a new index.

---

Today you could do something like this:

```
POST /filebeat-7.5.2/_rollover 
{
  "conditions": {
    "max_age":   "1m"
  }
}
```

But using a fake condition might raise administrator doubt about the correctness of such an action.

**Comment by dakrone** [comment]
@PhaedrusTheGreek for the rollover part, I guess I don't understand quite what you mean about the administrator doubt? We *do* have a wait to unconditionally rollover, which is the rollover API which is to do `POST /filebeat-7.5.2/_rollover` (with no body)

**Comment by PhaedrusTheGreek** [comment]
Proving once again not to assume!  Thanks Lee
