### ISSUE TITLE
Ability to reset watches in a throttled state

### ISSUE THREAD

**Issue by richiejarvis** [elastic/elasticsearch#51709]
It would be nice to have new watch-action to reset the throttle status.  The sequence is hopefully explained below.

The numbers indicate the current minute and execution of the watch.  They also indicate the actions of the DevOps team responsible for actioning the alert.

1. Condition not met
2. Condition met -  Alert - Action carried out - Throttle for 30 minutes OR a `reset` 
3. Condition met -  Throttled state - no action
4. Condition met -  Throttled state - no action
...etc, until...
9. Condition met -  Throttled state - no action
  Human fixes the reason for the Alert condition, and uses the new `reset` API call to reset the throttle state of the watch.
10. Condition not met
...etc, until...
21. Condition met -  Alert - Action carried out - Throttle for 30 minutes OR a `reset` 

This scenario does not appear to be possible, as there does not appear to be a way to unthrottle a watch that is throttled, except by deleting and readding the watch.

Thanks in Advance,

Cheers,

Richie

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
