### ISSUE TITLE
Add support for combining fields to the unified highlighter (matched_fields)

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#5172]
Like the FVH can combine fields, it'd be nice to be able to combine fields in the postings highlighter.  See #3750 for the FVH.  See https://issues.apache.org/jira/browse/LUCENE-4652 for the Lucene twin.

**Comment by clintongormley** [comment]
This should be doable now that we're using Lucene's postings highlighter instead of our own custom version.

**Comment by nik9000** [comment]
Now that we're dropping the postings highlighter in favor of the unified highlighter, I think this should be about the unified highlighter instead.

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by joostPieterse** [comment]
I came across this issue when trying to find the right highlighter for our multifields. At the moment we use FVH and would want to switch to unified for its bm25 scoring, but I don't think we can without matched_fields being supported for unified. 

I see this issue hasn't gotten much attention (any chance it's going to be picked up still?), but maybe someone can comment if one of the following approaches may work in a custom plugin:

- Get offsets and scores from the unified highlighter so we can merge the snippets it produces for each multifield ourselves. Scores seem available, but I couldn't find offsets.

- Add bm25 scoring to the FVH highlighter (somehow...)

**Comment by stefanobranco** [comment]
I know this has been around for quite a while, but with the full focus now apparently being on the [unified highlighter](#34015), this has sort of risen up in priority for us since it means we either lose functionality we're currently using with the FVH or don't get the benefits of any improvements to the unified highlighter.

**Comment by mayya-sharipova** [comment]
Addressed in PR #107640
