### ISSUE TITLE
_id clash on restored server.

### ISSUE THREAD

**Issue by praveenkutty** [elastic/elasticsearch#51735]
Hey,

I migrated elasticsearch onto a new server using npm package elasticdump. 

After restoring when I ingest new data, it does not add since it seems to use an existing _id for the  new data and is being rejected as duplicate data. The _id is a auto generated one.

Is there a way where I can start the sequence of _id based on the max of _id. 

Also I the _id being auto generated seems to be an UUID based and I want to change it time based id. Any pointers on this would solve my problem.

I have tried reIndexing on the same server but issue persist on the new index too. 

**ElasticSearch version: 5.6.4**
**1 cluster
1 node** 

The index was created as below
let index = {
    "mappings": {
      "textindex": {
        "properties": {
          "a": {
            "type": "integer"
          },
          "b": {
            "type": "keyword"
          },
          "c": {
            "type": "integer"
          },
          "d": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              }
            },
            "analyzer": "english"
          },
          "e": {
            "type": "integer"
          },
          "f": {
            "type": "keyword"
          },
          "g": {
            "type": "text",
            "analyzer": "english"
          },
          "h": {
            "type": "text",
            "analyzer": "english",
            "fielddata": true
          },
          "i": {
            "type": "keyword",
            "boost": 3
          }
        }
      },
      "category": {
        "properties": {
          "name": {
            "type": "keyword"
          }
        }
      }
    }
  };

    let esindex = await (0, _axios2.default)({
      method: 'put',
      url: `http://localhost:9200/textindex/`,
      data: index
    }

**Comment by pgomulka** [comment]
I am afraid that this is not supported

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
