### ISSUE TITLE
Wildcard * support in field name for Filters

### ISSUE THREAD

**Issue by lordaugustus** [elastic/elasticsearch#5174]
For wildcard in field name, currently we can have
{
    "query_string" : {
        "fields" : ["city.*"],
        "query" : "this AND that OR thus",
        "use_dis_max" : true
    }
}
It would be nice if there is also a "fields" option like this for filter, so that one can filter on the inner object.

"filter" : {
            "terms" : { "user" : ["kimchy", "elasticsearch"]}
}

Turning "user" to "user.*" wouldn't work currently.

**Comment by pquentin** [comment]
To make things clear, #5137 was merged, and supporting wildcard in field names was abandoned because it was out of the scope of the PR. clintongormley provided a nice overview of the difficulties this would pose: https://github.com/elastic/elasticsearch/pull/5137#issuecomment-42740126.

**Comment by dakrone** [comment]
We discussed this and agree that this would be very complex and should not be changed for the reasons specified in https://github.com/elastic/elasticsearch/pull/5137#issuecomment-42740126
