### ISSUE TITLE
HELP!  ES 7.4 Search performance is much slow than ES 5.5

### ISSUE THREAD

**Issue by taoyantu** [elastic/elasticsearch#51754]
We currently use the ES 5.5 version and plan to upgrade to the ES 7.4 version.

I deployed two environments,use the same server , 88 core cpu , 256G memory , the cluster have 3 servers, each server starts 3 nodes, the cluster has a total of 9 nodes.

jvm is configured to 30G, others use the default configuration

I used jmeter to write the same data to the cluster,index with 9 shards and 1 replcate. The amount of data is 300G.

When executing the query, the ES 7.4  result took a lot larger than the ES 5.5 , and the ES 7.4 server's io is also very large, there are a lot of disk read conditions.

Query like:
{
    "size": 0,
    "query": {
        "bool": {
            "filter": [{
                    "term": {
                        "aaa": "bbb"
                    }
                }, {
                    "range": {
                        "@timestamp": {
                            "gte": "1576117714282",
                            "lte": "1576118614282"
                        }
                    }
                }
            ], "Must_not": [{
                    "terms": {
                        "bizcode": ["00000000"]
                    }
                }
            ]
        }
    },
    "aggs": {
        "distribution": {
            "terms": {
                "field": "payer",
                "size": 10,
                "order": {
                    "_count": "desc"
                }
            }
        },
        "aggs": {
            "distribution2": {
                "terms": {
                    "field": "from",
                    "size": 10,
                    "order": {
                        "_count": "desc"
                    }
                }
            }
        }
    }
}

What is the cause of this problem? Are there any changes to the query in ES 7.4?

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
