### ISSUE TITLE
Security test are failing on 7.x matrix-java-periodic-fips

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#51753]
A lot of security tests are continuously failing on 7.x matrix-java-periodic-fips

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/8/console
Build Scans: https://gradle-enterprise.elastic.co/s/ln7zxbmdzpa5e

For example this test failure reproduces for me
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.settings.ListKeyStoreCommandTests.testListWithIncorrectPassword" \
  -Dtests.seed=DAFBEBE59800507D \
  -Dtests.security.manager=true \
  -Dtests.locale=hr-HR \
  -Dtests.timezone=America/Argentina/ComodRivadavia \
  -Dcompiler.java=13 \
  -Dtests.fips.enabled=true

**Comment by jkakavas** [comment]
Failures like this were resolved by #51832
