### ISSUE TITLE
Missing index templates with Metricbeat monitoring if monitoring plugin is disabled

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#51759]
Index templates for monitoring are setup by exporters, and we create a default local exporter if the monitoring plugin is enabled.

If the monitoring plugin is disabled on the monitoring cluster, these index templates will not be created on startup. However, the production cluster will [send over the templates](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java#L276) if it detects the monitoring cluster doesn't have them.

In a Metricbeat monitoring world, there are no exporters so if the monitoring plugin is disabled on the monitoring cluster, the necessary index templates will never exist

**Comment by jakelandis** [comment]
closed by https://github.com/elastic/elasticsearch/pull/78350
