### ISSUE TITLE
Missing cluster alerts with Metricbeat monitoring if monitoring plugin is disabled

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#51762]
Exporters are responsible for [creating the watcher-based cluster alerts for monitoring](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java#L307) and exporters aren't used in a metricbeat monitoring world. 

If a user has an appropriate license for watcher and never configures an exporter, the cluster alert watches are never created.

**Comment by chrisronline** [comment]
This bug is actually more severe than we originally thought.

Right now (7.6+), users using Metricbeat to collect and ship monitoring data to a separate, dedicated Elasticsearch monitoring cluster will not have cluster alerts available for the _production_ cluster. 

Without exporters, the Elasticsearch monitoring plugin will create the necessary monitoring resources, such as index templates, ingest pipelines, and cluster alerts. However, these are only created on the cluster itself (since the Elasticsearch monitoring plugin creates a hidden, local exporter if the monitoring plugin is enabled) which works fine for index templates and ingest pipelines as those only need to exist on the monitoring cluster. For cluster alerts, this hidden, local exporter will create them, but they will be created _on_ the monitoring cluster _for_ the monitoring cluster. What we actually need is for cluster alerts to exist _on_ the monitoring cluster _for_ the **production** cluster.

Historically, this was done via the `http` exporter but that is not used with Metricbeat collection.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
