### ISSUE TITLE
Rename 'Set Security User' processor's 'field' to 'target_field'

### ISSUE THREAD

**Issue by peterpramb** [elastic/elasticsearch#51782]
To be consistent with all other processors writing to some target field the `Set Security User` [processor's](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-node-set-security-user-processor.html) option `field` should be renamed to `target_field` to cleary indicate that this field will be modified by the processor and is not the input.

**Table 60. Set Security User Options**

Name | Required | Default | Description
-- | -- | -- | --
`field` | yes | - | The field to store the user information into.
`properties` | no | [username, roles, email, full_name, metadata] | Controls what user related properties are added to the `field`.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
