### ISSUE TITLE
RestHighLevelClient write log WARNING Using include_type_name in create index requests is deprecated

### ISSUE THREAD

**Issue by straestrae** [elastic/elasticsearch#51790]
Elasticsearch rest-high-level-client 6.8.6 
With dependency:
```
<dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-elasticsearch</artifactId>
      <version>3.2.4.RELEASE</version>
</dependency> 
```

Create client
```
import org.elasticsearch.client.RestHighLevelClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.elasticsearch.client.ClientConfiguration;
import org.springframework.data.elasticsearch.client.RestClients;
import org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate;
import org.springframework.data.elasticsearch.repository.config.EnableElasticsearchRepositories;

@Configuration
@EnableElasticsearchRepositories
public class ElasticSearchConfiguration {

    @Value("${spring.data.elasticsearch.host-port}")
    private String hostPort;


    @Bean
    public RestHighLevelClient elasticsearchClient() {
        ClientConfiguration clientConfiguration = ClientConfiguration.builder()
                .connectedTo(hostPort)
                .build();

        return RestClients.create(clientConfiguration).rest();
    }

    @Bean
    public ElasticsearchRestTemplate elasticsearchTemplate() {
        return new ElasticsearchRestTemplate(elasticsearchClient());
    }
}
```
Use client to create index
```
import lombok.RequiredArgsConstructor;
import org.elasticsearch.action.admin.indices.alias.Alias;
import org.elasticsearch.client.RequestOptions;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.client.indices.CreateIndexRequest;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
@RequiredArgsConstructor
public class IndexService {

    private final RestHighLevelClient restHighLevelClient;

    public void createIndexWithAlias() throws IOException {
        CreateIndexRequest request = new CreateIndexRequest("event-history-01-02-2020_11_18_08")
                .alias(new Alias("event-history"));
        restHighLevelClient.indices().create(request, RequestOptions.DEFAULT);
    }

}
```
in log WARNING messages

`{"timestamp":"2020-02-01T20:18:09.792Z","level":"WARN","thread":"I/O dispatcher 1","context":"default","message":"request [PUT http://localhost:32826/event-history-01-02-2020_11_18_08?master_timeout=30s&include_type_name=false&timeout=30s] returned 1 warnings: [299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf \"[types removal] Using include_type_name in create index requests is deprecated. The parameter will be removed in the next major version.\"]","source":"org.elasticsearch.client.RestClient"}`

How to use RestHighLevelClient without pass 'include_type_name=false' ?

**Comment by dliappis** [comment]
The default value of `include_type_name` is false starting with client version `7.0` -> see the detailed reply in https://github.com/elastic/elasticsearch/issues/40897#issuecomment-480833056. Have you tried using a newer version of the high level rest client esp. since you are targeting Elasticsearch 7.5.2?

However, this appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by straestrae** [comment]
Thanks for replay, but issue is include_type_name is false  leads to WARNING message.  So on my understanding RestHighLevelClient  should not send include_type_name=false  at all. It is like a bug
