### ISSUE TITLE
Remove support for delaying state recovery pending master nodes

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51806]
It is useful to be able to delay state recovery until enough data nodes have joined the cluster, since this gives the shard allocator a decent opportunity to re-use as much existing data as possible. However we also have the option to delay state recovery until a certain number of master-eligible nodes have joined, and this seems unnecessary: we require a majority of master-eligible nodes for state recovery, but there is no advantage in waiting for more.

We should deprecate the following settings in `7.x` and remove them in `8.0`:

- `gateway.expected_nodes`
- `gateway.expected_master_nodes`
- `gateway.recover_after_nodes`
- `gateway.recover_after_master_nodes`

**Comment by DaveCTurner** [comment]
We discussed this today and agreed that it will help to simplify this area, but this isn't on the roadmap yet so I'm marking it as `help wanted` to invite contributions from the community.

**Comment by aldenpeffer** [comment]
@DaveCTurner I'm going to take a crack at this.

**Comment by DaveCTurner** [comment]
Thanks @aldenpeffer, go ahead. Note that this'll take two PRs in sequence: the first to deprecate these settings and the second to remove them, and both should be opened against the `master` branch. We will take care of backporting the first.

**Comment by vishalthakur1972** [comment]
you like a genius to me. can you convert this script to an amp script? plzzzz

<script type="text/javascript">

setTimeout(function(){  

setInterval(function(){ gtag('event', 'Open', {'event_category': 'TimeOnPage'}); }, 10000);

setInterval(function(){ if(!document.hidden) gtag('event', 'Visible', {'event_category': 'TimeOnPage'}); }, 10000);

}, 60000);

</script>

**Comment by zroll** [comment]
Is this still open? Or was it fixed in #53845? Thanks!

**Comment by jainankitk** [comment]
@DaveCTurner - Are we still planning to include this in 8.0 release?

**Comment by DaveCTurner** [comment]
Yes, although https://github.com/elastic/elasticsearch/pull/53845 appears to have stalled.
