### ISSUE TITLE
LoggingOutputStreamTests failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#51838]
Some recent changes were made to `LoggingOutputStream` in #51779 which might be responsible for these failures:

https://gradle-enterprise.elastic.co/s/vokapgu3ogfry/tests/failed

**Comment by mark-vieira** [comment]
@rjernst I'm assigning this to you for now.

**Comment by ywelsch** [comment]
I'm muting the tests in #51917

**Comment by davidkyle** [comment]
Reopening as there were 3 recent failures all based on commit https://github.com/elastic/elasticsearch/commit/0b493e5808702dddfa46d5d30577efe9895a7143 which comes after the fix in https://github.com/elastic/elasticsearch/commit/88cf8ac0a84890bd51b602282455f0c1d32b43b0

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2016/439/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2/439/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/439/console


Looks like `LoggingOutputStreamTests.testMaxBuffer` also needs the `\r` fix.

**Comment by davidkyle** [comment]
Muting again in #52193
