### ISSUE TITLE
Add a way for statements nodes to be internal in Painless

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#51836]
All statement nodes in Painless contain a Location object that describes information about what generated the statement including a character offset and possibly a source code snippet. Currently, during ASM writing we check to ensure there are no statement offsets that collide with each other with an assert. We need a way to mark a statement as internal since we are going to decorate the ir tree with statements generated by code as opposed to a user. Collision detection can then ignore any internal statements.

Relates to: #49869

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
