### ISSUE TITLE
Feature Request: Obtain all conflicting mapping types across indexes

### ISSUE THREAD

**Issue by junmuz** [elastic/elasticsearch#51849]
**Support for getting the mappings that are conflicting**:

Often at times when time based indexes are used with dynamic mappings enabled, a situation can be reached where the mapping types are conflicting for different indexes. Through the _mapping API, one could parse out all the fields and check which fields are conflicting or not. Though I would like this to happen at the server side, and if there is a possibility can we get something like

GET 'localhost:9200/index1,index2/_mapping?conflicting=true'

Such a request should return all the mappings that are conflicting across the 2 indices.

**Comment by jimczi** [comment]
I think you can use the[ _field_caps API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html) for this purpose. It was added to provide a field-centric view of multiple indices. In your case you could ask for all fields:
````
GET index1,index2/_field_caps?fields=*'
````
and check the result to extract fields that have more than one type, (e.g. `rating` in this case):
````
{
    "indices": ["index1", "index2"],
    "fields": {
        "rating": { 
            "long": {
                "searchable": true,
                "aggregatable": true,
                "indices": ["index1"]
            },
            "keyword": {
                "searchable": true,
                "aggregatable": true,
                "indices": ["index2"]
            }
        },
        "title": { 
            "text": {
                "searchable": true,
                "aggregatable": false
            }
        }
    }
}
````
Is it what you're looking for ?

**Comment by junmuz** [comment]
That certainly is one step closer. A minor addition to the `_field_caps` to only show the conflicting mappings would be great. If an additional query params can be added that allows only listing out conflicting fields (Fields with keys > 1). In the above example , `rating` field has conflicting mappings.

**Comment by jimczi** [comment]
Are you concerned by the size of the response ? Conflicts is an abstract concept for this API, for instance you could consider that having a field mapped as `integer` in one index doesn't conflict with the same field mapped as `long`. Same holds for `text` and `keyword`. We use this API to determine if a query can run or what kind of input are supported on a field mapped in multiple indices.

**Comment by junmuz** [comment]
That's true. If the number of types is greater than 1 for a particular field, it means that there could be some implications from querying perspective.

Lets say we have 2 indexes `index1` & `index2`. `index1` has a field `count` with type `integer` where as `index2` has the same field with type `keyword`. The coercing feature will allow insertion of documents in the index. 

index1
{"count": 4}

index2
{"count": "10"}


If a range query is executing for field count, it will fail on the index2 because the field `count` for index2 is defined as keyword. A quick look at the `_field_caps` API can be handy here if there is a way of limiting the response to only return those with types greater than 1.

**Comment by jimczi** [comment]
> A quick look at the _field_caps API can be handy here if there is a way of limiting the response to only return those with types greater than 1.

I understand that it would be an optimization for the case that you're trying to solve but that shouldn't prevent you from using `field_caps` already ? I am asking because I am not sure of the benefit compared to the maintenance cost. It looks like an easy option to add but removing a feature proved to be difficult in the past so we try to keep the surface API as little as possible.

**Comment by junmuz** [comment]
Correct, this API do assist me in achieving what I want to do. If it's possible, it'll be good to have that filtering option.

**Comment by javanna** [comment]
We don't have concrete plans on adding support for returning "conflicts" only from field_caps, hence I am closing this issue.
