### ISSUE TITLE
Elasticsearch cannot be started after an upgrade: Temporary file directory [${ES_TMPDIR}] does not exist or is not accessible

### ISSUE THREAD

**Issue by nelyanne-v** [elastic/elasticsearch#51848]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2

**Plugins installed**: [kibana, x-pack]

**JVM version** (`java -version`): Java(TM) SE Runtime Environment (build 1.8.0_112-b15)

**OS version** (`uname -a` if on a Unix-like system): CentOS 7

**Description of the problem including expected versus actual behavior**:

I am trying to upgrade my Elasticsearch cluster from 7.4.0 to 7.5.2. I successfully upgraded the first node, but having some issues with the second one. I used the rpm files from https://www.elastic.co/downloads/elasticsearch. 

**Steps to reproduce**:

 1. sudo rpm -Uvh elasticsearch-7.5.2-x86_64.rpm
 2. systemctl daemon-reload
 3. sudo systemctl start elasticsearch.service

Service cannot be started, see the logs below.
I saw that there was another topic mentioning the same error message ([https://github.com/elastic/elasticsearch/issues/40812](url)), but it doesn't help me much.

**Provide logs (if relevant)**:

> -- Unit elasticsearch.service has begun starting up.
Feb 04 16:01:59 xxx-server-3 elasticsearch[129216]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future rele
Feb 04 16:02:00 xxx-server-3 elasticsearch[129216]: ERROR: Temporary file directory [${ES_TMPDIR}] does not exist or is not accessible
Feb 04 16:02:00 xxx-server-3 systemd[1]: elasticsearch.service: main process exited, code=exited, status=78/n/a
Feb 04 16:02:00 xxx-server-3 systemd[1]: Failed to start Elasticsearch.
-- Subject: Unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit elasticsearch.service has failed.
--
-- The result is failed.
Feb 04 16:02:00 xxx-server-3 systemd[1]: Unit elasticsearch.service entered failed state.
Feb 04 16:02:00 xxx-server-3 systemd[1]: elasticsearch.service failed.

**Comment by cbuescher** [comment]
Hi @nelyanne-v Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
