### ISSUE TITLE
Bulk request throttling issue (slow speeds compared to previous ES versions)

### ISSUE THREAD

**Issue by jackpf** [elastic/elasticsearch#51877]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.3.1, Build: default/deb/4749ba6/2019-08-19T20:19:25.651794Z, JVM: 1.8.0_131

**Plugins installed**: [analysis-icu
ltr
repository-hdfs
search-es-scorer-plugin
sentinel-plugin]

**JVM version** (`java -version`): java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Hi, unsure if this is a bug or intended behaviour, but we have experienced highly throttled indexing speeds since we've upgraded from ES 5.6.10 to 7.3.1.

We receive bulk request thread rejections, but we are actually only utilising around half of our available CPU, and it seems we are not able to increase the thread pool size because of this limit here: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/threadpool/ExecutorBuilder.java#L52

Our use case is that we only reindex clusters that don't receive live traffic, so I don't think this limit really makes sense for us. I wondered what the reasoning behind it was, and if other people have the same issue?

**Steps to reproduce**:

 1. Reindex a cluster with enough writes per second to get bulk thread rejections
 2. Check if CPU is actually maxing out
 3. In our case, we're only using 50% CPU

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
