### ISSUE TITLE
EQL: Verification tests need improving

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#51873]
The current test suite for the Verifier are fairly slim (on purpose).
Going forward this needs expansion, by using more complicated datasets both from a mapping perspective (see the list here https://github.com/elastic/elasticsearch/tree/7e85fc454eb53235fe31e9a510f0fb4338b89459/x-pack/plugin/ql/src/test/resources)
and query wise (simple and complicated queries that should work or fail).

**Comment by aleksmaus** [comment]
Closing as completed now.
