### ISSUE TITLE
Host no-jdk distro of Elasticsearch in a yum repo

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#51895]
**Describe the feature**:

Elastic offers a JDK-less version [1] of Elasticsearch. It would be helpful to host this in a yum repository like we do for the regular and oss packages.

[1] https://www.elastic.co/downloads/elasticsearch-no-jdk

**Comment by jasontedor** [comment]
It is a deliberate choice that these builds are not in a repository as we aim to remove them. They were available for a transition period between 6.x (no bundled JDK) and 7.0 (bundled JDK) but are not part of our long-term plans.
