### ISSUE TITLE
CompletionStats need only be recomputed on a refresh

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51915]
Computing the completion stats involves walking every field of every segment of every relevant shard, looking for completion fields. By default the seemingly-innocuous `GET _stats` API does this for every shard in the cluster. I've seen more than a few cases where an external monitoring system is hitting an overly-broad stats API hard enough that the cluster can't keep up. The consequence is that these stats requests pile up in the `management` threadpool and interfere with the other users of that threadpool.

As far as I can tell, these stats only change on a refresh. In most cases this means they do not change much at all, so I think we can improve the situation by caching these stats between refreshes.

I also note that in #33847 we changed the source of these stats from the external searcher to the internal one. I'm not sure why - external seems more appropriate to me, and would help with the caching since external refreshes may be very infrequent indeed.

Relates:

- https://github.com/elastic/elasticsearch/issues/36773
- https://discuss.elastic.co/t/bulk-indexing-causes-management-threadpool-queue-to-skyrocket/217852/7
- https://discuss.elastic.co/t/monitor-tasks-piling-up-in-master-node-6-8-3/212547
- https://discuss.elastic.co/t/concurrent-indices-stats-requests-cause-cluster-to-go-red/161385
- https://discuss.elastic.co/t/high-cpu-usage-while-bulk-indexing/135023/10

**Comment by rtkgjacobs** [comment]
There are number of external projects (just listing a few we've found with our audits so far) that hit this pinch point by default as an FYI

* https://github.com/vvanholl/elasticsearch-prometheus-exporter
* https://github.com/justwatchcom/elasticsearch_exporter
* https://github.com/lmenezes/cerebro

**Comment by dnhatn** [comment]
+1 to cache the completion stats (especially when we have many fields). Another optimization is to not compute the completion stats if we don't have any suggest field in the mapping.

**Comment by rtkgjacobs** [comment]
> +1 to cache the completion stats (especially when we have many fields). Another optimization is to not compute the completion stats if we don't have any suggest field in the mapping.
We have turned off all things hitting variants of `/stats` API's and are still finding high management threading / queue backlogs. We confirmed our mappings do not call out or enable suggested fields. 

Is ES7 set to always generate completion stats during ingestion ?   Can we turn this off? It is possibly a blocker for us to upgrade to ES7 from prior (old) versions in production for us if so...  We are finding with our latest tests removing the above fixtures, we are still seeing it stand out in our hot threads.

**Comment by DaveCTurner** [comment]
> Is ES7 set to always generate completion stats during ingestion ?

It's not really anything to do with ingestion, nor is it specific to ES7. By default the completion stats are computed for each stats call and [this seems to be true as far back as ES1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-stats.html) (I haven't checked further back).

> Can we turn this off?

Indeed you can; if you don't need to monitor completion stats so frequently then you should exclude them from these stats requests. I can't comment on how you might configure the third-party products linked above to do this, sorry, but Elasticsearch has had support for selecting specific stats for a long long time.

**Comment by rtkkroland** [comment]
>but Elasticsearch has had support for selecting specific stats for a long long time.
Is this true for `/_cluster/stats` as well? It doesn't mention it in the Guide https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html and it returns the full set of completion stats.

**Comment by DaveCTurner** [comment]
@rtkkroland oh dear, yes, I didn't realise we also compute completion stats for the cluster-level API but you're right I think we do:

https://github.com/elastic/elasticsearch/blob/84dbadb20b48b4fb360ba4c09aefb9c7009ac72a/server/src/main/java/org/elasticsearch/action/admin/cluster/stats/TransportClusterStatsAction.java#L57-L59

It doesn't look like there are selectors for this API 😕

**Comment by rtkgjacobs** [comment]
Some additional follow up / findings on our side. We had Netdata installed on all our cluster nodes and its default configuration hits `_cluster/stats` - and its default refresh rate seems too frequent. Removing that vastly improved our performance (several orders of magnitude). We have slightly raised the maximum threads of type:management to match our core counts to offset what 30s prometheus scrapes we run. We'll be watching closely balancing these API's use, but passing on a warning for others that might fall into our trap. 

Strongly encourage the cost or risks of API's like `_cluster/stats`  and `_all/stats` etc are derisked where possible. A few of us on this project have more grey hairs now.
