### ISSUE TITLE
reindex doesn't accept comma separated values as inputs

### ISSUE THREAD

**Issue by Mekk** [elastic/elasticsearch#51949]
I am trying to merge few small indices into one bigger. It looks like  comma-separated list is not supported, contrary to docs. Tested on Elasticsearch 7.5.1.

According to https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html page 
```
 index
    (Required, string) The name of the index you are copying from. Also accepts a comma-separated list of indices to reindex from multiple sources. 
```
So I tried comma separated list:
```
POST /_reindex?pretty
{"conflicts": "proceed",
  "source": {
    "index": "sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03"
  },
  "dest": {"index": "sfx-pb-1.3.0-2020.03", "op_type": "create"}}
```
(both indexes mentioned in source exist what `GET /sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03` gladly confirmed).

Result:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03]",
        "resource.type" : "index_or_alias",
        "resource.id" : "sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03",
        "index_uuid" : "_na_",
        "index" : "sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03]",
    "resource.type" : "index_or_alias",
    "resource.id" : "sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03",
    "index_uuid" : "_na_",
    "index" : "sfx-pb-1.3.0-2020.03.02,sfx-pb-1.3.0-2020.03.03"
  },
  "status" : 404
}
```

**Comment by Mekk** [comment]
(edited as it turned out that globbed value didn't work for me because index was frozen – but for comma-separated values problem persists also after reopening them)

**Comment by cbuescher** [comment]
> Also accepts a comma-separated list of indices to reindex from multiple sources.

I think this could be read as something like:
```
"source": {
    "index": [ "sfx-pb-1.3.0-2020.03.02", "sfx-pb-1.3.0-2020.03.03" ]
  }
```
Have you tried that as well?

**Comment by Mekk** [comment]
No, doc seems to be clearly stating that this param is of type string (and I would never consider array to be „comma separated value” in any case). I will give this format a try next time.

**Comment by Mekk** [comment]
Looks like sth started using array format. So this is documentation issue - doc should state it clearly and provide an example.

(the same also applies to glob format, which also doesn't have any example and isn't even mentioned in field description)
