### ISSUE TITLE
Indicate scripting compilation cache miss in request log

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#51958]
It's difficult for a customer to determine the source of compilations.  If we feed back whether a request hit the compilation cache, that could be noted in the request log.   Then the user can use standard monitoring tools to hunt down frequent compilers.

**Comment by bczifra** [comment]
@stu-elastic would this approach also help ferret out compilations originating from watch executions?

**Comment by rjernst** [comment]
> that could be noted in the request log

There is no general request log. There is the slowlog, which is disabled by default, and logging there is controlled by the request time. While it can be abused for this purpose (by setting the thresholds very low), I'm not sure that we would want to rely on this for surfacing such issues. 

I wonder what is the usual underlying issue? Is it watcher compilations (which should really be internal and not subject to compilation limits), or is it users inline scripts being sent with unique values per request? I haven't heard of needing to have fine grained hit/miss info in other Elasticsearch caches, so I wonder why this is only a problem in scripting?

**Comment by stu-elastic** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/52232
