### ISSUE TITLE
Compound query

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#51967]
This is related to #42811 -- deprecating function_score query

A proposal is to have a new type of  compound query that has an ability to combine scores from different queries:

```js
{
  "query": {
    "compound": {
      "queries": [
        {
          "match": {"message": "elasticsearch"}
        },
        {
         "match": {"author": "shay banon"}
        }
      ],
      "combine_mode": "sum"
    }
  }
}
```

combine_mode has the same values and definitions as in [Function Score Query's score_mode](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html)

combine_mode | definition
-- | --
sum | scores are summed (default)
multiply | scores are multiplied 
avg | scores are averaged
first | the first function that has a matching filter is applied
max | maximum score is used
min | minimum score is used

----
The intention for this query is to allow custom scoring logic, so internal queries are primarily expected to be `script_score` queries. For example, the intention fo the following query is to find "best fit" candidate with necessary skills: 
```js
{
  "query": {
    "compound": {
      "queries": [
        {
          "script_score": {
            "query": {
              "match": {
                "skills": "Java"
              }
            },
            "script": { "source": "10.0"}
          }
        },
        {
          "script_score": {
            "query": {
              "match": {
                "skills": "Scala"
              }
            },
            "script": {"source": "5.0"}
          }
        },
        {
          "script_score": {
            "query": {
              "match": {
                "skills": "Python"
              }
            },
            "script": {"source": "1.0"}
          }
        }
      ],
      "combine_mode": "first"
    }
  }
}
```

**Comment by mayya-sharipova** [comment]
Closing this issue, as it is replaced by #52482

**Comment by jayaddison** [comment]
Hi @mayya-sharipova - closing of the linked issue reminded me of this, and I noticed that there was an implementation in-progress at one point (#52387).  Are there any plans to introduce something like a `compound` query in ES in future?  (it's ok either way, I'm just curious)

**Comment by mayya-sharipova** [comment]
@jayaddison Thank you for your interest. We did not pursue this work till the end, as we had some other priorities to work on. We will try to re-discuss this topic and get back to it.

**Comment by jayaddison** [comment]
Thanks @mayya-sharipova, that makes sense.

At the risk of over-communicating: I've removed my upvote from this issue because I don't know for certain whether compound queries would address my [use case](https://github.com/elastic/elasticsearch/issues/42811#issuecomment-576440524).  I'll rephrase my problem as a feature request (linked to this one for the possibility of relevance) to try to gauge whether it has support.

(in other words: don't feel any pressure to re-discuss this; that may not be required unless other people want this query functionality)
