### ISSUE TITLE
EQL: Add High Level Rest Client

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#51961]
Adding HLRC for EQL should simplify writing non-trivial end-to-end tests.

**Comment by aleksmaus** [comment]
Closing as completed.

**Comment by imotov** [comment]
@aleksmaus if we added support for [`_eql/stats`](https://github.com/elastic/elasticsearch/blob/a11ccb83d45905e0f48907b29be9489bb6260d96/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlStatsAction.java#L26), could you link the PR here, if we didn't add it yet, this issue is not completed in my opinion.

**Comment by aleksmaus** [comment]
@imotov good point, missed that.

**Comment by aleksmaus** [comment]
Closing this issue as agreed since support for _eql/stats is implemented now.
