### ISSUE TITLE
SQL: string to DATE converter accepts only "date" format

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#51965]
The `SqlConverter.STRING_TO_DATE` is converting strings to a (ES/SQL-only type) `DATE` and using `DateUtils::asDateOnly` to parse the input, which will only accept a `YYYY-MM-DD` format.

Currently the DATE format is returned in zoned ISO8601 format (in result sets).

The above formatter is now used for parameters (#51945), leading to the situation where a query's `DATE` parameters would need to be provided in the above given format, but the result `DATE` values are provided as ISO timestamps.

**Comment by bpintea** [comment]
duplicate of #49379

**Comment by matriv** [comment]
@bpintea I actually think this is a duplicate of #49379 as the `DateUtils.asDateOnly(String date)` has been adapted to also accept time and also both `T` and ` ` separators.

**Comment by bpintea** [comment]
> @bpintea I actually think this is a duplicate of #49379 as the `DateUtils.asDateOnly(String date)` has been adapted to also accept time and also both `T` and ` ` separators.

It probably is (that's why I initially closed it myself), but I wanted to check the result in master before closing. If you are sure or get to verify it before me, feel free to close it.

**Comment by matriv** [comment]
No, it's fine, let's verify it 1st!

**Comment by bpintea** [comment]
duplicate of #49379
