### ISSUE TITLE
Respect runas auth realm for all API key security operations

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#51975]
When user A run as user B and creates an API key, the creator realm is recorded as user B's realm. However, when retrieving or invalidating the above API key, user A's realm will be used. This creates a problem for queries with `owner=true` and leads to empty result set, e.g. `GET -H 'es-security-runas-user: B' /_security/api_key?id=keyId&owner=true`.

This feels like a bug and it is better to have consistent behaviour for how runas realm is handled for all API key security operations. But it will be a breaking change if users are relying on the current behaviour.

**Comment by albertzaharovits** [comment]
I think this is a bug in how the `manage_own_api_key` privilege works, because it checks ownership as if API keys are created under the realm that did the authentication, but they are actually created under the realm that did the user look-up (the realm that the user running-as is a member of).

**Comment by tvernum** [comment]
I agree. I think, on analysis, that we should call this a bug, and fix it in 7.x (soon).

As always, [one person's bug fix is another person's breaking change](https://xkcd.com/1172/), but I'm happy that `>bug` is the right call here.

**Comment by ywangd** [comment]
Reading through the `ManageOwnApiKeyClusterPrivilege` class, I think [checkIfuserIsOwnerOfPApiKeys](https://github.com/elastic/elasticsearch/blob/7.6/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ManageOwnApiKeyClusterPrivilege.java#L89) needs to be updated as well. Maybe it is what @albertzaharovits meant by `manage_own_api_privilege`. Sorry I am still trying to get my head around this area.

**Comment by tvernum** [comment]
@ywangd Yes, I think that needs to change as well.
