### ISSUE TITLE
Add support to use query-string in enrich policy

### ISSUE THREAD

**Issue by crickes** [elastic/elasticsearch#51978]
When enriching documents using Ingest Pipeline Enrichment, provide a way to use a query string match as well as a term field. In a use case where there could be multiple matching document to enrich the target document, the user would ensure that the desired document is returned by sorting, filtering and returning just one document, which would be the desired document to enrich the incoming document. 

Example
POST number-plan-test/_search
{
"size": 2,
"query": {
"bool": {
"should": [
{
"query_string": {
"query": "00441352870123",
"default_field": "digits.prefixes",
"analyzer": "dialstring_analyzer"
}
}
]
}
},
"track_scores": true,
"sort": {
"_script": {
"type": "number",
"script": {
"lang": "painless",
"source":"_score"
},
"order": "desc"
}
}
}

The above query correct came back with 2 results, one matching on 00441352, and one matching on 0044135287, with the latter scoring more highly as it has a longer digit match.

I want to use this logic in an ingest pipeline to enrich call records with the operator details for the numbers involved in the call, but the enrichment pipeline will only let you use a term query currently, and term queries can't use analysers.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Comment by timtutt** [comment]
Would like to +1 and hopefully re-open this issue. This comes up often with a variety of clients. Enriching based on ANY field matching a query string or with an analyzer.
