### ISSUE TITLE
[CI] Packaging tests failing with "task with path 'batsTest.default' not found"

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#51974]
Right now our packaging test builds are blowing up trying to execute the bats tests with:

```
> Task with path 'batsTest.default' not found in project...
```

https://github.com/elastic/elasticsearch/pull/51565 should address this, but I wanted to create this issue for posterity so folks on test triage don't create another issue.

**Comment by rjernst** [comment]
I pushed 37210c4 to fix this as there are still issues getting  #51565 ready to merge.
