### ISSUE TITLE
[CI] DockerTests.test010Install failed multiple times

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#51998]
The test fails regularly on CI, mostly on `7.6` and `7.x` branches but also on `master`.

The failure on 7.6 is:
```
> Task :qa:os:destructiveDistroTest.default-docker
 org.elasticsearch.packaging.test.DockerTests > test010Install FAILED
     java.lang.RuntimeException: Command was not successful: [bash -c docker run --detach --env discovery.type=single-node --publish 9200:9200 --publish 9300:9300 elasticsearch:test]
        result: exitCode = [125] stdout = [] stderr = [Unable to find image 'elasticsearch:test' locally
     docker: Error response from daemon: manifest for elasticsearch:test not found: manifest unknown: manifest unknown.
    See 'docker run --help'.]
         at __randomizedtesting.SeedInfo.seed([AEB3DBE026C1E285:8AEC7B73446CBDDD]:0)
         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
         at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
         at org.elasticsearch.packaging.util.Docker.executeDockerRun(Docker.java:162)
         at org.elasticsearch.packaging.util.Docker.runContainer(Docker.java:104)
         at org.elasticsearch.packaging.util.Docker.runContainer(Docker.java:92)
         at org.elasticsearch.packaging.test.DockerTests.setupTest(DockerTests.java:106)
```

Build scan for 7.6: https://gradle-enterprise.elastic.co/s/2rzg3s5wfa3oo

On master the error is a bit different:
```
java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty b2f88432b9f5dc03f3d36aed59761bc5b99eac1867480feb4415e401e073a0cf /usr/share/elasticsearch/bin/elasticsearch-keystore create]
   result: exitCode = [126] stdout = [OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown] stderr = []
```

Build scan for master: https://gradle-enterprise.elastic.co/s/tisfc272vhzxo

**Comment by mark-vieira** [comment]
Running the `destructiveDistroTest.default-docker` task is consistently busted on `7.x` and `7.6`. It seems there's probably a missing task dependency here because we aren't building the docker image at all. This seems to be specific to the Vagrant tasks BTW.

@williamrandolph do you mind taking a look at this?

**Comment by williamrandolph** [comment]
@mark-vieira I think I've got it. Fix incoming.

**Comment by williamrandolph** [comment]
The reason the dependency was missing is that we build the docker image on the host machine rather than in the Vagrant VM. This part was working correctly. The failure came in the test code that makes sure the already-built docker image is _loaded_ for the in-VM tests.

**Comment by williamrandolph** [comment]
I've merged the PRs that ought to fix this. I'll open again if we see these failures again.
