### ISSUE TITLE
[CI] ClusterRerouteIT.testDelayWithALargeAmountOfShards timed out waiting for green state 

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#52000]
The test `ClusterRerouteIT » testDelayWithALargeAmountOfShards` failed today on CI for the `7.x` branch with the error:
 
```
timed out waiting for green state
java.lang.AssertionError
: 
timed out waiting for green state
Close stacktrace
at __randomizedtesting.SeedInfo.seed([B25CE8847D0ACBC2:9E2DE2656C14E120]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:929)
at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:882)
at org.elasticsearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards(ClusterRerouteIT.java:224)
```

Build scan: https://gradle-enterprise.elastic.co/s/3l2rtho4qznu6

Looking at the build stats it also fails on 7.6 (https://gradle-enterprise.elastic.co/s/bxlllkb4jubxs) and seems to be related to the new way of persisting metadata state (see #50907), in which case tests might need to be adapted?

**Comment by pugnascotia** [comment]
Failed again on 7.6 - https://gradle-enterprise.elastic.co/s/wmy4bjcpxqnte

**Comment by henningandersen** [comment]
Failed again on master: https://gradle-enterprise.elastic.co/s/getynn6hnzfm2

Looked a bit into it, looks like retention lease sync causes the shards to become stale one by one, not sure if this is part of why it is timing out, but it is at least a significant difference since this test was written.

**Comment by DaveCTurner** [comment]
Hmm. All 7 of the failures of this test over the last 30 days were using `org.apache.lucene.mockfile.WindowsFS`. It typically completes in 30-60 seconds but the failures are 6-8 minutes long. `WindowsFS` adds extra validation that we behave correctly on filesystems that don't let you delete open files; I wonder if this is introducing extra slowness.

**Comment by DaveCTurner** [comment]
I opened https://github.com/elastic/elasticsearch/pull/52488 to suppress WindowsFS on this test suite.

I am not marking #52488 as `closes #52000` since I am not fully certain that this is the underlying problem. I would prefer to have a couple of weeks without failures before declaring this issue closed.

**Comment by DaveCTurner** [comment]
Echoing Henning's [comment](https://github.com/elastic/elasticsearch/pull/52488#pullrequestreview-360602830) here: if after a couple of weeks we decide that `WindowsFS` was the source of our slowdown we have a few options to discuss:
- reduce the scope of the suppression by moving the one slow test into its own suite and suppress `WindowsFS` there
- reinstate `WindowsFS` and either
  - extend the timeout anyway, possibly only if `WindowsFS` is in use, or
  - dig further into why `WindowsFS` is slow for us here and fix it upstream
- take no further action

**Comment by DaveCTurner** [comment]
We discussed this today and decided that we'll take no further action unless we see another failure, and therefore we can close this; please reopen it if you come across another failure.

**Comment by probakowski** [comment]
Another failure from today: https://gradle-enterprise.elastic.co/s/gws7m6tms6coy

**Comment by DaveCTurner** [comment]
`WindowsFS` strikes again. I backported #52488 to the 7.6 branch in 2878ec84fe26f20b89811c8a992b7c99e4ac2741.
