### ISSUE TITLE
Bell Canada: ECE LDAP not supporting nested groups

### ISSUE THREAD

**Issue by ElasticAF** [elastic/elasticsearch#52005]
Customer is complaining that ECE does not support LDAP nested groups. What can be done about this? 

Bell Canada is one of our largest customers in the region (2nd largest deployment).

When I look at this other issue it seems that ES could support nested groups (if AD or RedHat): https://github.com/elastic/elasticsearch/issues/43921

Would the same also be applicable to ECE or is that different?

**Comment by Kushmaro** [comment]
closing this one, moved to ER
