### ISSUE TITLE
[CI] CoreFullClusterRestartIT testRecovery failing against upgraded cluster

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52031]
There have been 5 of these this week in `master`, `7.x` and `7.6`.

```
java.lang.AssertionError: 
mismatch while checking for translog recovery
testrecovery 0 existing_store done 0
testrecovery 0 peer           done 0
testrecovery 1 existing_store done 0
testrecovery 1 peer           done 0
testrecovery 2 existing_store done 0
testrecovery 2 peer           done 0
testrecovery 3 existing_store done 0
testrecovery 3 peer           done 0
testrecovery 4 existing_store done 0
testrecovery 4 peer           done 0
 expected:<true> but was:<false>
at __randomizedtesting.SeedInfo.seed([501B62971D61B9E6:91EB1B3B30317341]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:800)
```

https://gradle-enterprise.elastic.co/s/5y4zpqvjppqxk/tests/futb4ms7jdaog-gweza6zb3vqbg
https://gradle-enterprise.elastic.co/s/tdf4altcwoehc/tests/azvgwapql5okk-gweza6zb3vqbg
https://gradle-enterprise.elastic.co/s/cs3p4ljhknz4a/tests/4taevsg7bdssu-gweza6zb3vqbg
https://gradle-enterprise.elastic.co/s/lqqvda5lljnh2/tests/4taevsg7bdssu-gweza6zb3vqbg
https://gradle-enterprise.elastic.co/s/r2yx7lqnmipfy/tests/azvgwapql5okk-gweza6zb3vqbg

**Comment by albertzaharovits** [comment]
Another one on the `master` pile https://gradle-enterprise.elastic.co/s/5y4zpqvjppqxk
```
REPRODUCE WITH: ./gradlew ':x-pack:qa:full-cluster-restart:v8.0.0#upgradedClusterTest' --tests "org.elasticsearch.xpack.restart.CoreFullClusterRestartIT.testRecovery" -Dtests.seed=ED932745F6998539 -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=Africa/Tripoli -Dcompiler.java=13	
  2> java.lang.AssertionError: mismatch while checking for translog recovery	
    testrecovery 0 existing_store done 0	
    testrecovery 0 peer           done 0	
     expected:<true> but was:<false>	
        at __randomizedtesting.SeedInfo.seed([ED932745F6998539:2C635EE9DBC94F9E]:0)	
        at org.junit.Assert.fail(Assert.java:88)	
        at org.junit.Assert.failNotEquals(Assert.java:834)	
        at org.junit.Assert.assertEquals(Assert.java:118)	
        at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:737)
```

**Comment by DaveCTurner** [comment]
There's been another couple of instances of this [recently](https://build-stats.elastic.co/goto/fe33059ab38570af9b7bbecd99560df5):

- https://gradle-enterprise.elastic.co/s/llnfdbgfqjwcw
- https://gradle-enterprise.elastic.co/s/wvghvvn7eyzyw

**Comment by jbaiera** [comment]
There have been a few more of these failures today: https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1619115574845&search.startTimeMin=1618891200000&search.timeZoneId=America/New_York&tests.container=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT&tests.sortField=FAILED&tests.test=testRecovery&tests.unstableOnly=true

**Comment by davidkyle** [comment]
These failures seem to be becoming more common https://build-stats.elastic.co/goto/d177d430847e31747ce4dd2f3416f4b3

This is the latest occurring on 7.x upgrading from v6.8.16: https://build-stats.elastic.co/goto/d177d430847e31747ce4dd2f3416f4b3

**Comment by mayya-sharipova** [comment]
Another failure today on 7.x: https://gradle-enterprise.elastic.co/s/4hy7qacj7amjk

**Comment by mayya-sharipova** [comment]
I've muted the test on 7.x branch in https://github.com/elastic/elasticsearch/commit/4a27476875ee8f3340f72cce7e695331225e6a63, as there has been 3 failures just today.

**Comment by ywangd** [comment]
Also failed on 7.13: https://gradle-enterprise.elastic.co/s/6bi677w57lnhs
I backported @mayya-sharipova's mute from 7.x c6ed64ca015ce5e27220bb037a1447f2669a6143

**Comment by dimitris-athanasiou** [comment]
This is also fails as `FullClusterRestartIT.testRecovery`, the parent test class. See https://gradle-enterprise.elastic.co/s/b36d3sxurm35c/tests/:qa:full-cluster-restart:v8.1.0%23upgradedClusterTest/org.elasticsearch.upgrades.FullClusterRestartIT/testRecovery. I'm muting on master too.

**Comment by DaveCTurner** [comment]
I muted this in 8.0 with 236751ece87 too.
