### ISSUE TITLE
Logn script compilation can bring cluster down

### ISSUE THREAD

**Issue by probakowski** [elastic/elasticsearch#52058]
If you try to use scripted field during search or add scripted field in Kibana index pattern with script that is very hard to compile it can leave long running tasks and finally overcome cluster.
This was confirmed on `7.3` and `master`, on cloud and local, using script like below:
```
def field = doc['a'].value;

return
    (field == '1' ? 'a1' :
    field == '2' ? 'a2' :
    field == '3' ? 'a3' :
    field == '4' ? 'a4' :
    field == '5' ? 'a5' :
    field == '6' ? 'a6' :
    field == '7' ? 'a7' :
    field == '8' ? 'a8' :
    field == '9' ? 'a9' :
    field == '10' ? 'a10' :
    field == '11' ? 'a11' :
    field == '12' ? 'a12' :
    field == '13' ? 'a13' :
    field == '14' ? 'a14' :
    field == '15' ? 'a15' :
    field == '16' ? 'a16' :
    field == '17' ? 'a17' :
    field == '18' ? 'a18' :
    field == '19' ? 'a19' :
    field == '20' ? 'a20' :
    field == '21' ? 'a21' :
    field == '22' ? 'a22' :
    field == '23' ? 'a23' :
    field == '24' ? 'a24' :
    field);
```
This script takes 1h+ to compile and when search using it targets multiple indices there will be a lot of stuck tasks which will make cluster unusable

**Comment by jdconrad** [comment]
@probakowski Can this issue be closed with the commit of https://github.com/elastic/elasticsearch/pull/52056?

**Comment by DmitryOlshansky** [comment]
Just hit this hard in production, for now we limited number of clauses we allow our users to specify. 
7.7 doesn't have the issue, we are running 7.6.1.
