### ISSUE TITLE
how does es return the synced response while doing async executions

### ISSUE THREAD

**Issue by kaihekaihe** [elastic/elasticsearch#52106]
actions are executed in async manner after request fired from postman，how does “hold” the request thread and finally use the listener to return response?

I know rest client wraps future and 'future.get()‘ will block until response returns. so is this the answer for my question?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
