### ISSUE TITLE
REST API documentation with the required privileges

### ISSUE THREAD

**Issue by utsushiiro** [elastic/elasticsearch#52120]
I'm using X-Pack security to protect my Elasticsearch clusters.
Very easy to use, with detailed documentation.
However, it is a bit difficult to find the privileges required for each REST API.
So, how about explaining the required privileges in the REST API documentation?

**Comment by jrodewig** [comment]
Hi @utsushiiro.

Thanks for raising this issue. However, I think this duplicates #48630.

I'm going to close this one to consolidate. Thanks again.
