### ISSUE TITLE
_mapping shows type as nested object when fieldname contains a .

### ISSUE THREAD

**Issue by daveisfera** [elastic/elasticsearch#52164]
Using the official docker image:
`Version: 6.8.1, Build: default/docker/1fad4e1/2019-06-18T13:16:52.517138Z, JVM: 12.0.1`

**Plugins installed**:
Whatever comes in the Docker image

**JVM version** (`java -version`):
```
openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux 27f75616c6d6 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
When calling `_mapping`, any fields that have a `.` in the name show a nested object instead of just having `type`

**Steps to reproduce**:
 1. Create an index with a `.` in a field name:
```
curl -X PUT "localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "_doc" : {
            "properties" : {
                "field1.test" : { "type" : "text" }
            }
        }
    }
}
'
```
 2. Get the mapping:
`curl localhost:9200/test/_mapping` returns
```
{"test":{"mappings":{"_doc":{"properties":{"field1":{"properties":{"test":{"type":"text"}}}}}}}}[root@ae7dea46a81d elasticsearch]# curl localhost:9200/test/_mapping?pretty
{
  "test" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "field1" : {
            "properties" : {
              "test" : {
                "type" : "text"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jtibshirani** [comment]
The behavior in the example is expected -- using a dotted path like `field1.test` indicates that the mappings should contain an object called `field1`, with a field named `test`. Leaf field names cannot contain dots, so it would need to be renamed (for example to `field1_test`).

**Comment by daveisfera** [comment]
This example works and I believe it's a "leaf field name" so I'm not sure that your statement is correct

**Comment by jtibshirani** [comment]
To clarify my explanation, issuing a request with the mappings

```
"mappings" : {
  "_doc" : {
    "properties" : {
      "field1.test" : { "type" : "text" }
    }
  }
}
```

is the same as issuing a request with

```
"mappings" : {
  "_doc": {
    "properties" : {
      "field1" : {
        "properties" : {
          "test" : {
            "type" : "text"
          }
        }
      }
    }
  }
}
```

Elasticsearch always interprets names that contain dots like `field1.test` as a path, and creates both a parent object mapping `field1` and a leaf field mapping `test`.

**Comment by jtibshirani** [comment]
I'm closing this out since it doesn't indicate a bug. If we encounter other confusion around this point, it could worth adding a note to the [object datatype](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/object.html) docs.
