### ISSUE TITLE
elasticsearch 7.5.2 ClassNotFoundException: org.elasticsearch.client.Cancellable

### ISSUE THREAD

**Issue by hellosweetmain1** [elastic/elasticsearch#52180]
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.5.2</version>
</dependency>
`

`BulkProcessor.builder(
        (request, bulkListener) -> {
          client.bulkAsync(request, RequestOptions.DEFAULT, bulkListener);
        }, listener)
        .setBulkActions(actions)
        .setBulkSize(new ByteSizeValue(bulkSize, ByteSizeUnit.MB))
        .setFlushInterval(TimeValue.timeValueSeconds(bulkFlushInterval))
        .setConcurrentRequests(Runtime.getRuntime().availableProcessors())
        .setBackoffPolicy(BackoffPolicy.constantBackoff(TimeValue.timeValueSeconds(1L), 3))
        .build();
`

`client.bulkAsync(request, RequestOptions.DEFAULT, bulkListener);`

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
