### ISSUE TITLE
cannot find integration for JoinQueryBuilders with searchSourceBuilder

### ISSUE THREAD

**Issue by AnthuDuke** [elastic/elasticsearch#52192]
is there any integratino for JoinQueryBuilders with SearchSourceBuilder?

I couln't find any functions that returns QueryBuilder which is required for SearchSourceBuilder for a query.

Is SearchSourceBuilder the best to add queries for SearchRequest, if not please revert with the best to use with RestHighLevelClient.

**Comment by cbuescher** [comment]
Hi @AnthuDuke, Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. The following seems to work for me when the code from the parent-join module is on the classpath:
```
SearchSourceBuilder sb = new SearchSourceBuilder();
sb.query(JoinQueryBuilders.hasChildQuery("type", QueryBuilders.matchAllQuery(), ScoreMode.Avg));
```
I'm closing this as an issue here, but encourage you to ask this question in the forum instead if the above doesn't work.
