### ISSUE TITLE
SQL: [Docs] Add limitation for scalars and Agg Order By

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#52204]
When using aggregate functions in the `ORDER BY` then only plain
functions can be used. Operators and scalars are not allowed. Examples
of not allowed queries:
```
SELECT a, f(max(b)) GROUP BY a ORDER BY f(max(b))
SELECT a, max(b) GROUP BY a ORDER BY f(max(b))
SELECT a, max(b) + min(b) AS diff GROUP BY a ORDER BY diff
```
This limitation is missing from the docs.

**Comment by matriv** [comment]
`master` : 78a1185549ff7f3229fd2d036567eb2a4f2cf230
`7.x` : c2e055253777748a3680f4abaa846d8162adb0d7
`7.6` : d8569c0236fc56df446733514513a3dfa6b1e51b
`6.8` : 6033c70f8c82288ffcf17758957c65c32c388cdf

**Comment by the-zucc** [comment]
If I am not mistaken, there is a small typo:
Moreover, the aggregation(s) used in the **`ORDER BY** must be only plain aggregate functions. No scalar functions or operators can be used, and therefore no complex columns that combine two ore more aggregate functions can be used for ordering. Here are some examples of queries that are not allowed:

**Comment by matriv** [comment]
@the-zucc Yes, Thank you! fixing it!
