### ISSUE TITLE
[CI] XPackRestIT p0=indices.freeze/10_basic/Basic L74 Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#52209]
```
java.lang.AssertionError: Failure at [indices.freeze/10_basic:74]: expected [2xx] status code but api [search] returned [503 Service Unavailable] [{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[],"stack_trace":"Failed to execute phase [query], all shards failed\r\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:
...
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob-windows-compatibility/os=windows-2019/53/console
https://gradle-enterprise.elastic.co/s/t66es3e2pbe6g

Does not reproduce:
```
./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT" \
  -Dtests.method="test {p0=indices.freeze/10_basic/Basic}" \
  -Dtests.seed=143749813EC5AF86 \
  -Dtests.security.manager=true \
  -Dtests.locale=mt-MT \
  -Dtests.timezone=Africa/Ouagadougou \
  -Dcompiler.java=13 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

**Comment by mark-vieira** [comment]
Couple more of these:

https://gradle-enterprise.elastic.co/s/gbbfvkr5jo5x4/tests/fcijb24gqtmnc-dyizuu7rv265i
https://gradle-enterprise.elastic.co/s/kzkf35kl7jwxk/tests/fcijb24gqtmnc-dyizuu7rv265i

**Comment by dnhatn** [comment]
Relates #51708?

**Comment by jpountz** [comment]
@dnhatn It looks like you already spent some time looking into it, I wonder whether you have ideas where the problem so that we could give a single area label to this failure?

**Comment by henningandersen** [comment]
One more failure on 7.6 here: https://gradle-enterprise.elastic.co/s/w2qeb5quewqde/tests/fcijb24gqtmnc-dyizuu7rv265i
But it also fails on master according to build-stats. Looks like we had an increasing frequency of this failing around the beginning of February:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'indices.freeze%20AND%20NOT(build.branch:pull-request-*)'),sort:!(process.time-start,desc))

**Comment by henningandersen** [comment]
The problem here is that the `ilm-history` index is created in the middle of the test (not explicitly by the test but implicitly by ILM, due to some earlier tests triggering ilm).

```
[ilm-history-1-000001] creating index, cause [api], templates [ilm-history], shards [1]/[0], mappings [_doc]
```

If the test is unfortunate enough to run the search using `_all` while the primary is still initializing, I believe it will fail like this.
