### ISSUE TITLE
SQL: Allow scalars when ordering by an agg function

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#52206]
Currently when `ORDER BY` contains an aggregate function
on the plain aggregate functions, no scalars/operators are allowed
So queries like:
```
SELECT gender, max(salary) - min(salary) as diff FROM test_emp GROUP BY gender ORDER BY diff
SELECT gender, max(salary) FROM test_emp GROUP BY gender ORDER BY gender, max(salary) + min(salary)
```
are not allowed.

Consider relaxing this limitation, by applying the in-memory sorting on the rows, after the scalar functions have been applied (Processors have been applied to the raw results)

**Comment by wchaparro** [comment]
Superceded by ES|QL
