### ISSUE TITLE
SQL: Validate params for next page requests

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#52207]
Currently, the next page request can have all the params as the initial sql query request.
Most of them (apart from `columnar` and `page_timeout` are ignored internally, but it will be safer
to add a validation to prevent of accidental use of those params that will only make sense in the 
initial request.

Based on #51258, nasty behaviours can rise if, for example, the `time_zone` param is passed with the next page requests and differs from the original one, or even between pages.

**Comment by wchaparro** [comment]
Superceded by ES|QL
