### ISSUE TITLE
max_children top level nested restriction released wrongly

### ISSUE THREAD

**Issue by erayarslan** [elastic/elasticsearch#52202]
Hi,
While i was testing migrating to 7.5.2 i found and issue.

In master branch restriction seems fine but in 7.6, 7.5, 7.5.1, 7.5.2 releases has an issue.
I think in 199fff8a55fc31d23512abaf102a0270538e202d merge the feature is broken.

Changes should be like [this](https://github.com/elastic/elasticsearch/pull/46731/files)

Thanks

**Comment by erayarslan** [comment]
Hi @jimczi, can you check it? old "max_children is only supported on last level of nested sort" restrictions must be deleted.

**Comment by jimczi** [comment]
The cherry-pick seemed to apply smoothly so I just ran the test and pushed. Thanks for checking @erayarslan and sorry for the trouble. I opened #52744.

**Comment by erayarslan** [comment]
seems okay. thank you for your time @jimczi
