### ISSUE TITLE
Link the flattened field from the `kv` processor and `nested` fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#52239]
I think we should try to make `flattened` more easily discoverable in our docs. I'm currently considering linking from:
 - The `kv` processor because it is one reason how users may end up with field names they don't have control of.
 - The `nested` field because whenever users are tempted to create nested objects that have two `key` and `value` keyword fields, then it's likely a better fit for the `flattened` field.

Any other ideas where we should link `flattened` from?

**Comment by lockewritesdocs** [comment]
> I think we should try to make [`flattened`](https://www.elastic.co/guide/en/elasticsearch/reference/master/flattened.html) more easily discoverable in our docs. I'm currently considering linking from:
> 
> * The [`kv` processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/kv-processor.html) because it is one reason how users may end up with field names they don't have control of.
> * The [`nested` field](https://www.elastic.co/guide/en/elasticsearch/reference/master/nested.html) because whenever users are tempted to create nested objects that have two `key` and `value` keyword fields, then it's likely a better fit for the `flattened` field.
> 
> Any other ideas where we should link `flattened` from?

Adding some links to the sections that Adrien mentioned.
