### ISSUE TITLE
Build problem with Eclipse IDE in Windows 10

### ISSUE THREAD

**Issue by PARKJUHONG123** [elastic/elasticsearch#52254]
**Describe the feature**: `Build problem with Eclipse IDE in Windows 10`

**Elasticsearch version** : `7.5.2`

**JVM version** : `13.0.1`

**Tools** : `Eclipse 2019-09 R (4.13.0)` , `Gradle 6.1.1` , `Mingw64`

**OS version** : `Windows 10`

**Description of the problem including expected versus actual behavior**: 
Hi, I am very beginner to elasticsearch.
Please understand with your honor although this issue may be too fool. 

I try to build the master branch of elasticsearch using Eclipse IDE.

These are what I have done,
1. Download up-to-date Gradle (Version 6.1.1)

2. Clone master branch on my desktop using Mingw64

3. Execute `./gradlew eclipse` using Mingw64
and the result is :
```
> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.1
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version           : 13 (Oracle Corporation 13.0.1 [Java HotSpot(TM) 64-Bit Server VM 13.0.1+9])
  JAVA_HOME             : C:\Program Files\Java\jdk-13.0.1
  Random Testing Seed   : FD73C09F53E563DC
  In FIPS 140 mode      : false
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 38s
2306 actionable tasks: 2029 executed, 277 up-to-date
```

4. Execute `./gradlew run --debug-jvm` using Mingw64 
and the result is : 

```
> Task :distribution:run
Running elasticsearch in debug mode, node{:distribution:runTask-0} suspending until connected on debugPort 5005
Exec output and error:
| Output for cmd:ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:735]


> Task :distribution:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:run'.
> Process 'command 'cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 41s
296 actionable tasks: 216 executed, 80 up-to-date
```

5. Using Eclipse 2019-09 R (4.13.0), import cloned elasticsearch

6. Set the run configurations and select working directory location to my gradle folder

7. Run 
and the result at the console is : 
```
Working Directory: C:\Gradle\gradle-6.1.1
Gradle user home: C:\Users\박주홍\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 5.6.1
Java Home: C:\Program Files\Java\jdk-13.0.1
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: <run default tasks>


> Task :help

Welcome to Gradle 5.6.1.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```

I opened `http://localhost:9200/` and nothing appeared.
Is there any problem or missing something on what I've done?

What I want to do is building from source code using Eclipse IDE in Windows 10.
Just want to open `http://localhost:9200/` from source code, not from distribution version

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by PARKJUHONG123** [comment]
Thanks for your kindness @jasontedor and sorry that I didn't look for forums first.
