### ISSUE TITLE
[discovery-ec2] plugin should look at ENI security groups instead

### ISSUE THREAD

**Issue by michael-robbins** [elastic/elasticsearch#52255]
**Describe the feature**:

discovery-ec2 currently look at an instances security groups, but not any security groups attached to the network interfaces on the EC2 host.

Instead it would be good if we looped over the network interfaces attached to the EC2 host, if the security group for that network interface matches what's provided in 'discovery.ec2.groups' then we use the IP address assigned to that network interface.

Reason: We are currently using ECS's awsvpc networking mode that creates a new network interface for every task it creates (isolating the containers networking from the host networking).

This means Elasticsearch on cluster creation cannot easily find the other master eligible nodes (can't hardcode as the IP/hostnames, as they are not known at creation/deployment time).

By knowing the Security Groups that will be attached to these dynamic network interfaces before, we *can* hardcode them, allowing us to link an IP address to an ES node, allowing for dynamically configured cluster creation.

**Comment by DaveCTurner** [comment]
Hi @michael-robbins, thanks for the idea. I have some questions:

1. Multi-homed hosts make discovery complicated in two different ways: each node must select the correct publish address at startup, and then other nodes must be able to find that publish address later. The `ec2-discovery` plugin adds features to both aspects and it's not clear if your issue with the first or the second (or both). Are your nodes selecting the correct publish address? The publish address is reported in a log message from `o.e.t.TransportService` shortly after startup.

2. ECS, unlike bare EC2, supports [its own DNS-based service discovery mechanism](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html) that sounds like it fits your needs. Have you tried this?

3. Can you work around this using the [file-based seed hosts provider](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-hosts-providers.html#file-based-hosts-provider) by populating the `unicast_hosts.txt` file yourself?

**Comment by michael-robbins** [comment]
Thanks for the info Dave! Here's my context/knowledge!

1. The nodes are selecting the correct publish address (they only see a single address, which is *the* address/interface they are given), no other host network interfaces/IP address are present to confuse the container. All nodes have TCP/9300 to each other, so they have network access to each other in a local 10/8 private range, it's just knowing which IP addresses to talk to which is the problem.

2. I did look at ECS's Service Discovery, but (and I could just not understand ES here properly), the DNS A record returns multiple IPs (one for each ES node runnign). So a request to 'es.my.domain.com' will return a list of IP addresses for each node/task running. It doesn't automatically register node1.es.my.domain.com, node2.es.my.domain.com, node3.es.my.domain.com, etc. for each running node.

Would the above case work if I just hardcoded es.my.domain.com into each node's seed_hosts? (a single host entry, resolving to multiple IPs). And assume that ES will interpret the A record response with multiple IP addresses and connect to each host? If so then that sounds like it might be worth a shot. Otherwise this didn't really sound suitable for me at first glance.

3. This is probably going to be my backup solution in the mean time, have either a custom entrypoint in the container before ES is initiated that populates that file, or have a sidecar container running that will populate the file. It's probably going to have to be this way forward for now, but it would be nice without having to do this, and discovery-ec2 performing this manual lookup instead. 
All that script would be doing would be emulating discovery-ec2's DescribeInstances but just implementing some further business logic around inspecting the attached network interfaces.

**Comment by DaveCTurner** [comment]
> The nodes are selecting the correct publish address

Good, I hoped for that answer :smile:

> Would the above case work if I just hardcoded es.my.domain.com into each node's seed_hosts? (a single host entry, resolving to multiple IPs). And assume that ES will interpret the A record response with multiple IP addresses and connect to each host?

Yes, [that's the documented behaviour](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-hosts-providers.html#built-in-hosts-providers):

> ... If a hostname resolves to multiple IP addresses then Elasticsearch tries to find a seed node at all of these addresses.

You should try and arrange for the DNS name to resolve only to the master-eligible nodes' addresses here. There's a limit to how many addresses are returned by AWS's service discovery mechanism (8 IIRC) and you need to ensure that the right addresses aren't squeezed out with inappropriate ones.

**Comment by michael-robbins** [comment]
Ahh I missed that line, dang it, thanks for the help mate! I'll have a go at configuring that and giving it a whirl.

Yeah I'll only be provisioning nodes that are master-eligible so that's at least something I don't have to worry about for now.

Cheers for the help!

**Comment by DaveCTurner** [comment]
Sounds good.

FWIW I think the original point is a valid one. Today we only look at the addresses that belong to the instance itself and do not consider any attached ENIs, but we could add that if there was enough support for the idea. A quick search doesn't turn up anyone else asking for it before this issue, but if we see some support here then we can always revisit this. Comments and +1s from the community are welcome.
