### ISSUE TITLE
Add Version data type

### ISSUE THREAD

**Issue by XavierRamosORGADATA** [elastic/elasticsearch#52282]
**Version data type:**

For Software versioning analysis we would like to be able to sort/group documents by Version and use such versions as X-axis in decreasing or increasing order inside of Line Visualizations. 

Therefore, when you sort your documents by Increasing Version number it would need to take into account each significant level from left to right, as the standard is.(https://en.wikipedia.org/wiki/Software_versioning)

Ex: 
Document 1 - Version: 14.15.14.2900
Document 2 - Version: 4.14.14.2900
Document 3 - Version: 4.15.14.29
Document 4 - Version: 14.15.15.900

Increasing order:

Document 2 - Version: 4.14.14.2900
Document 3 - Version: 4.15.14.29
Document 1 - Version: 14.15.14.2900
Document 4 - Version: 14.15.15.900

**Comment by jtibshirani** [comment]
@XavierRamosORGADATA we have discussed adding support for semantic version numbers in https://github.com/elastic/elasticsearch/issues/48878. I'm going to close this to avoid duplication -- if you have any suggestions feel free to comment on the existing issue.
