### ISSUE TITLE
[DOCS] Mapping options `include_in_root` and `include_in_parent` are not documented

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#52309]
The options `include_in_root` and `include_in_parent` allow you to modify how a nested object is indexed in the root document or a parent document respectively:

https://github.com/elastic/elasticsearch/blob/1dc9dd42235e876fde8c3b31934f1bc88d668896/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L226-L235

I cannot find any mention of them in today's documentation, although they were [documented in 1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-nested-type.html).

**Comment by jtibshirani** [comment]
A note for context that the issue https://github.com/elastic/elasticsearch/issues/12461 proposes to deprecate `include_in_root` and `include_in_parent` (although I agree they should still be documented!)
