### ISSUE TITLE
geo-shape-doc-values centroid calculation should handle polygons as lines/points and lines as points

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#52303]
- Polygons with no area should not be treated as polygons — they should be treated as lines.
- Lines with no length should not be treated as lines — they should be treated as points.

**possible solution A**

This can be achieved by updating the `DimensionalShapeType` of the geometry for such geometries. The downside of this is that then we would love information about what type of geometry the field value was.

**possible solution B**

The other option is to keep the original `DimensionalShapeType`, and instead have a place-holder weight that is close to `0` for such geometries.

relates to #50834

**Comment by talevy** [comment]
@nknize and @iverase, do you have a preference for how this issue is to be solved? Currently such values return `NaN` for longitude and latitude. At the time, I had tests for this and thought it was OK, but now I realize such geometries are very much expected in the wild.

**Comment by iverase** [comment]
My opinion here is those geometries are degenerated and they should be treated as the final shape. So if a polygon becomes a line, the `DimensionalShapeType` should be change accordingly. I think it is more important the current geometry than the original geometry type.

**Comment by talevy** [comment]
this was closed in #52500
