### ISSUE TITLE
ILM: add ability to delete the Xth rollover index

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#52308]
**Describe the feature**:
In ILM feature, in delete phase, it would be nice to add the ability to remove the Xth rollover index.
For instance, in UI, you say “5 rollovers” instead of “5 days”, and that means that the index index-00001 will be deleted when current write index is index-00006 (there have been 5 rollovers). 

This is particularly useful when on hot phase, you define a rollover rule only based on index size. 
With such a delete phase rule, you can ensure that you will never reach data FS size. 
It is quite equivalent to log rollover rules based on size and number to avoid full FS.

**Comment by jasontedor** [comment]
> With such a delete phase rule, you can ensure that you will never reach data FS size.
It is quite equivalent to log rollover rules based on size and number to avoid full FS.

It sounds like you might more directly want the ability to limit by total size across an "index stream", is that fair to say? For example, see #49392.

**Comment by fbaligand** [comment]
Well, I agree that is other issue is quite the same. 
So do I close this one?

**Comment by jasontedor** [comment]
Yes, closing.
