### ISSUE TITLE
Bad interpretation of mustache empty array object field.

### ISSUE THREAD

**Issue by ivister** [elastic/elasticsearch#52315]
*Result of interpretation mustache template input object looks wrong:*

In action json field in watcher creation I tries to get `{{ctx.payload.hits.hits}}`.
When this field is not empty it interpreted as expected (`[ {...}, {...}, ..., {...}]`) like array of objects (may be empty).
When array field of object is empty array it interpreted like empty object.

**Code**: `{{ctx.payload.hits.hits}}`
**Input data example**:
`{
    metadata={...},
    ...,
   payload={
        _shards={...},
        hits={
            hits=[],
            ...
        },
    },
    ...
}
`
**Expected result:** `[]`
**Execution result:** `{}`
 
**Elasticsearch version** (`"version" : {
    "number" : "7.3.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "1c1faf1",
    "build_date" : "2019-09-06T14:40:30.409026Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }`):

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
