### ISSUE TITLE
Context class loader for plugins set to ES class loader

### ISSUE THREAD

**Issue by dweiss** [elastic/elasticsearch#52320]
When plugins are invoked (initialized and then run) the context class loader is set to ES's class loader. This causes some grief with plugin dependencies that look up SPI endpoints and don't find them because ServiceLoader.load(Class) uses context class loader (and not the calling class's class loader).

A workaround requires the context class loader to be set locally but this in turn requires permissions and generates a warning/ confirmation prompt upon plugin installation.

**Comment by rjernst** [comment]
Historically we haven't tried dealing with the context class loader, thus why you see it set to ES's class loader. Plugins that implement SPI themselves are expected to implement ExtensiblePlugin and the reloadSPI method.

However, is the case you are describing for a dependency of your plugin uses SPI and internally is calling service loader? I can understand how that would be difficult to workaround, and I'm not opposed to setting it in this case while plugins are being constructed, but I want to clarify the situation that we would be supporting here.

**Comment by dweiss** [comment]
I understand the reluctance to deal with this; it's a nightmare. This said, since you opened this can of worms (different classloaders) I don't think it'll be possible to ignore context class loaders - they're just an inherent part of this class loader mess that we all have to live with... The built-in service loader mechanism utilizes this by default for example (not the calling class's class loader) and it currently just plain fails and requires a manual workaround. I don't know what else in the standard library uses context class loaders.

A particular example I stumbled upon is the new SLF4J which attempts to look up implementations via SPI mechanism. If you have both the API and its implementation in the plugin the implementation is not found (even if it's present on classpath). This may be quite a head scratcher for somebody not intimately familiar with these class-loading nuances.

**Comment by rjernst** [comment]
Thanks for the clarification; that is what I expected. Setting the context classloader while initializing the plugin (before calling the Plugin constructor) should be easy enough. Do you think this will be sufficient? Do you think it is reasonable to expect such dependencies will have initialized SPI during construction? Setting it before calling every method call, eg to createComponents, would be quite complex.

**Comment by dweiss** [comment]
Ideally it'd be good to swap out class loader for createComponents and other "initialization" methods. But even plugin class constructor would be a good start. I remember wondering myself what the "lifecycle" of a plugin is and where to put component-assembling code; this wasn't (and isn't) clear to me. While components have a lifecycle plugins don't seem to have one. Perhaps it'd be nice to add such a thing too.

**Comment by rjernst** [comment]
I've given this some thought and agree we should be setting the context classloader before all calls into the Plugin instances. However, doing so across all methods, not just the ctor, is going to take some work. While we could have a helper method to do this, it would be error prone since we could easily miss a call to one of these methods, especially with newly added methods.

Instead, I think we should wrap all Plugin instances with a dynamically created class that sets/delegates/unsets within each method. Unfortunately I think this will take some work, as to do it cleanly we would need ASM, but we don't want to pull that into core. It should be possible to load ASM into a separate classloader, one used just for constructing these wrapper objects. But given that there is a workaround for this issue, I don't think this should be a high priority (although I hope to handle it during some general plugin improvements later this year).

**Comment by dweiss** [comment]
Isn't a Plugin class implementation with a delegation pattern going to work? Then it could be statically implemented, it wouldn't have to be complicated... But I agree it's not something super urgent.

**Comment by rjernst** [comment]
The Plugin class is only the common base class. There are many plugin interfaces, eg MapperPlugin or SearchPlugin that plugins may implement to expose additional functionality in those areas. A plugin may implement 0 to many of these, so we would need to dynamically mimic the inheritance in our wrapper.

**Comment by dweiss** [comment]
Hi Ryan. Just wondering if something like this would work:
https://github.com/elastic/elasticsearch/pull/63185/files

I also corrected classloader.load() to Class.forName(..): this avoids early class initialization.

I've tried to run gradlew check but I'm getting test errors on master (without the patch) so I'm not sure whether I broke something or something is broken already. :)

**Comment by rjernst** [comment]
@dweiss I think that is the first step. Would you be willing to open a PR with that change? We can work through checking it with CI.

The other more broad change that is needed is what I described in https://github.com/elastic/elasticsearch/issues/52320#issuecomment-590570998. I think that will require a lot more work, but your proposal will at least get some cases working, and it would be no worse off than it is now.

**Comment by dweiss** [comment]
You're right in that even this would be a small step forward as it allows plugin writers to initialize things explicitly where the context class loader is set. It'd be nice to have it work everywhere but something is better than nothing! 

As for the PR - ahem, this link is a PR already? Would you like me to clean it up somehow?

**Comment by rjernst** [comment]
Apologies, I just looked at the diff and didn't realize I was looking at a PR. I've kicked off testing there.

**Comment by dweiss** [comment]
No need to at all. Is there anything special I need so that gradlew check passes on master (Linux, Ubuntu)? I didn't look deeply into the failures but they were consistent.

**Comment by rjernst** [comment]
There shouldn't be anything special. Let's see what happens in CI.

**Comment by williamrandolph** [comment]
I think we can close this as fixed in #63185
