### ISSUE TITLE
Feature flag outside XPack plugins boundaries

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#52328]
Inside EQL's telemetry code (and actually any XPack plugin that needs to expose usage data and summarized info), there is a pair of actions that need to be registered on the plugin side, but also two that need to be registered on the xpack core side.

XPack core actions:
- https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/XPackInfoFeatureAction.java#L31
- https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/XPackUsageFeatureAction.java#L31

EQL actions registration (draft PR): https://github.com/elastic/elasticsearch/pull/52248/files#diff-65a84ede375062e6ddafed077d89e530R109-R123

If the EQL side Usage and Info actions are hidden behind the `enabled` flag then [PingAndInfoIT.testXPackInfo fails](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/15863/console) and, also, [MiscellaneousDocumentationIT.testXPackUsage](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/MiscellaneousDocumentationIT.java#L149) fails.
Ideally, the same feature flag value should be able to allow/forbid the action registration on the XPack code side, but it doesn't look like something easily doable.

The current approach is the one from the draft PR where Info and Usage actions are always registered which means eql will appear as available but disabled
```
    "eql" : {
      "available" : true,
      "enabled" : false
    }
```
when `/_xpack` or `/_xpack/usage` is called on the rest layer.

Opening this issue for discussion about any other approach than the current one for eql, as shown in the links above.
@jasontedor @henningandersen @colings86

**Comment by jasontedor** [comment]
@astefan I think always registering the info/usage endpoints independently of EQL being enabled is fine.

**Comment by henningandersen** [comment]
@astefan, this looks fine, though I would prefer the available flag to switch to false when the feature flag is not set to true. Looks like this can be easily handled in EqlInfoTransportAction.available()

**Comment by jasontedor** [comment]
@henningandersen Availability is about whether or not the license level permits the feature (e.g., machine learning would be marked as not available with a basic license, but available with a platinum license, independently of whether or not it's enabled).

**Comment by henningandersen** [comment]
Thanks @jasontedor , @astefan, that approach looks good :smiley: .

**Comment by astefan** [comment]
Thank you for the feedback @jasontedor and @henningandersen.
