### ISSUE TITLE
Enhance functionality of `search.allow_expensive_queries_setting`

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#52337]
Currently the setting is crude and once set to `false` the respective queries that it guards are not permitted. Consider adding more fine grain control:
- Be able to disallow only a subset of the queries
- Be able to fine tune the disallowed queries for some cases, e.g : based on the length of the prefix (for a prefix query)

Follows: #29050

**Comment by javanna** [comment]
This does not seem to have come up since we have introduced the allow expensive queries setting. We don't plan on making these improvements as this point, hence closing for now. Feel free to reopen / comment if you think these should be implemented.
