### ISSUE TITLE
Allow modifying settings of indices for an arbitrary number of indices at the time

### ISSUE THREAD

**Issue by nachogiljaldo** [elastic/elasticsearch#52367]
**Describe the feature**:
Currently, it is possible to change the settings of several indices at the time via:
```
PUT /idx1,idx2,.../_settings
{
  ...
}
```

However, there are some, not so clear limitations about what the length of the URL is and how that length is calculated (i.e. what is included). As per a conversation with @DaveCTurner , it is 4096, but it counts the HTTP method, the query string, the http protocol version, etc.

My suggestion is providing a way to do this in the payload, so one can do this for an unlimited number of indices using the request's payload. This simplifies a lot the case when having to modify many indices at the time.

**Comment by dwlizlo** [comment]
I'm about to work on this, I hope that's alright.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
