### ISSUE TITLE
Add support for `match_prefix` enrich policy

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#52362]
**Describe the feature**:

Currently, the [enrich policy ](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/enrich-policy-definition.html) only supports term queries.

It would be useful to add support for `match_prefix` policy types in order to support the use case where a user would like to enrich the incoming documents based on a variable-length prefix. 

For example, products documents can have `product_id` and a `producer_prefix` and we'd like to enrich the product documents with the producer name.

So documents in the form of 
```
{ "product_id": "123456", "producer_prefix": "abc" },
{ "product_id": "345678", "producer_prefix": "bc" }
``` 
would need to be enriched with the producer name using the lookup table 
```
{"producer_id": "abc_123", "name": "producerA" }
{"producer_id": "bc_serial_222", "name": "producerB" }
```

An enrich policy of the form would enrich the product documents with the producer name:
```
PUT producer_enrich_policy {
    "match_prefix": {
        "indices": ["producers"],
        "match_field": "producer_id",
        "enrich_fields": ["name"]
    }
  }
}
```

**Comment by andreidan** [comment]
This would not work as the query direction is from "ingest document" -> "enrich index" and the prefixes would be stored in the enrich index.

I'm closing this for the moment and we have https://github.com/elastic/elasticsearch/issues/51978 to discuss the direction in which the enrich query capabilities could evolve

**Comment by andreidan** [comment]
Updated the use-case to illustrate the situation when the incoming docs contain the prefixes. In this case the `match_prefix` policy type would yield the desired enrichment.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
