### ISSUE TITLE
[DOCS] Terms agg doc counts are more precise than documented.

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#52377]
The terms aggregation docs include a [_Document count are approximate_](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts) section.

When [reproduced on 6.8 or 7.x](https://gist.github.com/geekpete/38c06b2eaf2745c3b7312d329acb01fd), the actual results are more precise than documented in last table and paragraphs of the section.

### Steps to reproduce
https://gist.github.com/geekpete/38c06b2eaf2745c3b7312d329acb01fd

Thanks to @geekpete for raising and putting together the reproduction steps.

**Comment by abprash** [comment]
Can i work on this one?

**Comment by jrodewig** [comment]
@abprash A PR would be welcome. Thanks.

**Comment by abprash** [comment]
Thank you @jrodewig . Working on it. Will submit a PR when done.
Would like to get clarified on the process followed, Would this issue need to be assigned to me?

**Comment by geekpete** [comment]
The repro steps were in a private gist, I made it public.

**Comment by abprash** [comment]
Thanks @geekpete

**Comment by abprash** [comment]
@geekpete @jrodewig  Not sure, how it usually goes, would you mind reviewing my PR?

**Comment by jrodewig** [comment]
@abprash I'll take a look when time permits. Thanks for raising this!
