### ISSUE TITLE
ES returns an invalid Json

### ISSUE THREAD

**Issue by Kiran-G1** [elastic/elasticsearch#52379]
In below Json returned by ES
`        "_index": "index_name",
        "_type": "index_name",
        "_id": "idxxxx",
        "_score": 1,
}        "_source": {
    }`

I'm getting an extra  `}` at _score.
is this a known bug?

**Comment by dadoonet** [comment]
Could you share the full json you are getting and which API did you call exactly with which parameters/body?

**Comment by Kiran-G1** [comment]
I'm using kibana for searching.
And in the response result I see one extra "}" which is breaking the process.

**Comment by dadoonet** [comment]
But you didn't tell how you did that. Is there any way to reproduce the problem?

**Comment by jasontedor** [comment]
@Kiran-G1 You’ve left out a lot of basic information here such as the version and how to reproduce this issue?

**Comment by jasontedor** [comment]
No additional feedback, closing.
