### ISSUE TITLE
Unable to run subset of bwc yaml tests

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#52383]
For a while the way to run multiple the full BWC suite against a subsection of the yaml tests was to use a command like the following:

```
./gradlew :x-pack:qa:rolling-upgrade:v7.7.0#bwcTest -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT -Dtests.method="test {p0=*/40_ml_datafeed_crud/*}"
```
This no longer works. 

The tests fail in the initial oldCluster runner with
```
org.elasticsearch.upgrades.TransformSurvivesUpgradeIT.initializationError
...
org.elasticsearch.upgrades.WatcherRestartIT.initializationError
```
Each failing with
```
org.junit.runner.manipulation.NoTestsRemainException
```

The typical new way of running tests with `--tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT"` only works with a specific runner selected. 

This is not an option with BWC tests.

**Comment by williamrandolph** [comment]
I ran into something like this as well recently. `-Dtests.method="test {p0=*/40_ml_datafeed_crud/*}"` was working, and you could see whether your test passed or failed, but the output was junked up with the `NoTestsRemain` exceptions and stack traces.

**Comment by mark-vieira** [comment]
This turns out to be an issue introduced in version 2.7.5 of the randomized testing library. I've opened an issue with them as well as #52785 on our end to revert back to a known good version in the meantime.
