### ISSUE TITLE
Using inFipsSunJsseJvm() causes failures in ESXPackSmokeClientTestCase and MigrateToolTestCase

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#52391]
The title is vague as it is not obvious yet what causes this failures. When attempting to do a static import of `EsTestCase#inFipsSunJsseJvm()` in the two aforementioned classes in order to determine if we're running in Java 8 and in fips mode, the transport client used in the test fails to connect to the node. The `TransportClient` created, has a `TransportClientNodesService` that ends up having 0 listed nodes. 
The failures are reproducible easily locally. Example failure: https://gradle-enterprise.elastic.co/s/yphikcuckyz5e

The workaround for now is to reimplement `inFipsSunJsseJvm()` in these two classes until we can figure out what causes the error.

**Comment by rjernst** [comment]
@jkakavas Can you confirm whether the above is still an issue? I cannot find either that method `inFipsSunJsseJvm`, or a use of `EsTestCase#inFipsJvm` in either of those classes.

**Comment by jkakavas** [comment]
Thia is now irrelevant since the changes introduced in https://github.com/elastic/elasticsearch/pull/56526
