### ISSUE TITLE
[ML] Make .ml indices that will not become system indices hidden

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#52420]
#50452 introduced the concept of hidden indices into 7.7.

All indices beginning with `.ml` need to migrate to being either hidden indices or system indices.  They cannot be normal indices from 8.0 onwards.

Since the hidden index functionality is available we should start to use it now.  The following patterns of `.ml` index should become hidden indices, i.e. have the `index.hidden` setting added to them on creation:

1. `.ml-anomalies*`
2. `.ml-state*`
3. `.ml-notifications*`
4. `.ml-annotations*`
5. `.ml-stats*`

(Note `.ml-config*` and `.ml-meta*` will become system indices and should not be altered by this piece of work.  Any others I have missed need discussing.)

**Comment by przemekwitek** [comment]
Done apart from `.ml-stats` which does not exist yet.

**Comment by droberts195** [comment]
> Done apart from `.ml-stats` which does not exist yet.

@dimitris-athanasiou I know you are working on adding `.ml-stats` at the moment, so please can you make it a hidden index from the start?
