### ISSUE TITLE
Using same field in QueryStringQuery's "fields" and "quote_field_suffix" result in boosts being multiplied

### ISSUE THREAD

**Issue by pbvahlst** [elastic/elasticsearch#52439]
Sorry to repost, but #50263 was never confirmed or denied as a bug. It will be very helpful to know if we need to work with this new way of calculating scores or it will be reverted to the former way of doing it. 
Thanks in advance 

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Duplicates #50263
