### ISSUE TITLE
Ingest node grok processor httpd patterns

### ISSUE THREAD

**Issue by cdalexndr** [elastic/elasticsearch#52440]
Please add httpd grok patterns supported by logstash: 
https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/httpd

Currently not supported error:
`Unable to find pattern [HTTPD_COMMONLOG] in Grok's pattern dictionary`

**Comment by danhermann** [comment]
@cdalexndr, `HTTPD_COMMONLOG` is a synonym for the `COMMONAPACHELOG` pattern which is available in the ingest node grok processor.
