### ISSUE TITLE
Detect and log painless compilation cache thrashing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#52497]
If the painless compilation cache is thrashing, we should log a rate limited message.

Brainstorm:
* Keep track of last N (maybe size of cache, or something smaller) evictions, and last N compiles
* If they are equal, we are thrashing (that's a very tight defintion, we could broaden it later if needed). 
* I think the case we really want to warn on is when a unique script is always passed in, so we will just be pumping through the cache, never reusing
  TODO: Consider allowing unique scripts to flag that they want to bypass the cache.

Related: https://github.com/elastic/elasticsearch/issues/49763#issuecomment-587876788

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
