### ISSUE TITLE
Simplify object creating in ConstructingObjectParser

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#52499]
Currently ConstructingObjectParser collects parsing result in an array of objects which has to be processed into an object, which causes us to write a lot of code that looks like this:
```
                int i = 0;
                boolean completed = (boolean) a[i++];
                TaskInfo task = (TaskInfo) a[i++];
                BytesReference error = (BytesReference) a[i++];
                BytesReference response = (BytesReference) a[i++];
                return new TaskResult(completed, task, error, response);
```
I had a long and boring flight during which I thought about different ways to improve the ConstructingObjectParser experience and came up with a couple of prototypes: 
- The first approach simply wraps an iterator and casting into a helper object imotov/elasticsearch@bdce5cb
- The second approach replaces an array with a map imotov/elasticsearch@cbe683d

I would like to solicit feedback on the these two solutions and maybe other ideas about how to improve this areas.

CC @nik9000

**Comment by rjernst** [comment]
Of the two approaches here, I'm more in favor of the iterator. However I wonder if we could use a helper to extract the constructor based on arity (statically), and then `newInstance` on the constructor already takes in Object[]. We could also then statically fail if the arity does not match the number of registered args, which right now would not happen until a failure at runtime.

**Comment by nik9000** [comment]
I didn't go with a map at first because I didn't want to add too much overhead. Maybe I was too cautious.... But your `Arguments` wrapper is *really* cute! It'd need to be super documented because it is sneaky, but I do like it.

You could make  ctors on `ConstructingObjectParser` that take `Function<Arguments, T>`  so you wouldn't need to explicitly build it. And deprecate the other ctors.

**Comment by nik9000** [comment]
> Of the two approaches here, I'm more in favor of the iterator. However I wonder if we could use a helper to extract the constructor based on arity (statically), and then `newInstance` on the constructor already takes in Object[]. We could also then statically fail if the arity does not match the number of registered args, which right now would not happen until a failure at runtime.

I missed this comment. It is kind of what I was hoping we could try at some point honestly. It is a bit more involved, but I think it *could* be the lowest overhead, safest option.

**Comment by imotov** [comment]
Interesting idea. I can try prototyping that as well. 

If I understood your idea, we might lose the ability to convert parameters between parser and constructor easily thought. In some cases we need to do some simple conversion on parameters on the way in, iterator allows us to do it in the constructor. With Object[] we would need to replace Nth element of an array that again forces us to deal with magic numbers, etc.

**Comment by nik9000** [comment]
I think if we took a function reference *somehow* that'd be the cleanest thing from a usability standpoint. But I know that ain't easy.

**Comment by imotov** [comment]
I tried implementing @rjernst 's ideas as an external utility method, but it didn't go that well, so I ended up making another object parser. It shares 90% of code with ConstractingObjectParser, so I moved this code unchanged to a common abstract super class. Let me know what you think #55483
