### ISSUE TITLE
Need to be able to specify include_upper / include_lower with Range and Date-Range Aggregation

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#5249]
Currently, the behaviour appears to be that when specifying a range aggregation, the lower value is included, but the upper value is not.

If I index the following data:

```javascript
{ "integer" : 0,  "float" : 1.0, "date" : "2014-03-10" }
{ "integer" : 1,  "float" : 1.1, "date" : "2014-03-11" }
{ "integer" : 2,  "float" : 1.2, "date" : "2014-03-12" }
{ "integer" : 3,  "float" : 1.3, "date" : "2014-03-13" }
{ "integer" : 4,  "float" : 1.4, "date" : "2014-03-14" }
{ "integer" : 5,  "float" : 1.5, "date" : "2014-03-15" }
{ "integer" : 6,  "float" : 1.6, "date" : "2014-03-16" }
{ "integer" : 7,  "float" : 1.7, "date" : "2014-03-17" }
{ "integer" : 8,  "float" : 1.8, "date" : "2014-03-18" }
{ "integer" : 9,  "float" : 1.9, "date" : "2014-03-19" }
{ "integer" : 10, "float" : 2.0, "date" : "2014-03-20" }
```

And then (illustrating with dates) do a range aggregation:
```javascript
"date_range" : {
  "date_range" : {
    "field" : "date",
    "ranges" : [ {
      "from" : "2014-03-15",
      "to" : "2014-03-17"
    } ]
  }
}
```

I get the following results:
```javascript
"date_range" : {
  "buckets" : [ {
    "key" : "2014-03-15T00:00:00.000Z-2014-03-17T00:00:00.000Z",
    "from" : 1.3948416E12,
    "from_as_string" : "2014-03-15T00:00:00.000Z",
    "to" : 1.3950144E12,
    "to_as_string" : "2014-03-17T00:00:00.000Z",
    "doc_count" : 2
  } ]
}
```
Here we can see that its not including both from and to in the aggregation (or otherwise we would expect a doc_count of 3. The same is true if you do a range aggregation on the integer or decimal number.

Doing a different aggregation illustrates that its the upper thats getting omited:
```javascript
"date_range_upper" : {
  "date_range" : {
    "field" : "date",
    "ranges" : [ {
      "from" : "2014-03-01",
      "to" : "2014-03-10"
    } ]
  }
}
```
Gives results
```javascript
"date_range_upper" : {
  "buckets" : [ {
    "key" : "2014-03-01T00:00:00.000Z-2014-03-10T00:00:00.000Z",
    "from" : 1.393632E12,
    "from_as_string" : "2014-03-01T00:00:00.000Z",
    "to" : 1.3944096E12,
    "to_as_string" : "2014-03-10T00:00:00.000Z",
    "doc_count" : 0
  } ]
}
```

It needs to be possible to include the upper (or omit the lower) value in the aggregation specification.

Here is an example of what I need to do:
I want to do an aggregation as follows:
```javascript
"aggregations": {
    "intentDate": {
        "date_range": {
            "field": "intentDate",
            "ranges": [
                {
                    "key": "Overdue",
                    "to": "2014-02-17"
                },
                {
                    "key": "March",
                    "from": "2014-02-18",
                    "to": "2014-03-17"
                },
                {
                    "key": "April",
                    "from": "2014-03-18",
                    "to": "2014-04-15"
                }
            ]
        }
    }
}
```
I want the upper value to be inclusive in the range.
Then I want to take the results to create a filter - without having to do any date/datetime manipulation to translate between them.

**Comment by clintongormley** [comment]
@jpountz which means that the consuming client application would potentially have to check for `to`, `from`, `gt`, `gte`, `lt`, and `lte` keys.... 

@nickminutello i'm guessing you've worked around it, but is this still something that you (or others) want?

**Comment by jpountz** [comment]
@clintongormley Agreed it would make things more complex on the client side.

**Comment by nickminutello** [comment]
Sorry, @clintongormley I missed the message. 

In my case, my date range was constructed according business rules (exchange conventions + trading calendars plus rules on how to deal with holidays) so in my domain date range specifications were always taken mean inclusive of upper and lower bounds. 

So I had to hack the creation of the filter to +1 on the request (and then remember to -1 on the date in the results....)

**Comment by jpountz** [comment]
Now that we have a `filters` aggregation, I'm tempted to just recommend it instead if someone needs different include/exclude behaviour than the range aggregation. Opinions?

**Comment by clintongormley** [comment]
@jpountz would there be any difference in performance?

**Comment by clintongormley** [comment]
Given the discussion above, I'm going to close this issue as won't fix

**Comment by nickminutello** [comment]
Fine by me

**Comment by djschny** [comment]
Adding @dakrone as he was in favor of the switch
