### ISSUE TITLE
[watcher] Message-ID reused in emails generated with foreach parameter

### ISSUE THREAD

**Issue by immon** [elastic/elasticsearch#52513]
**Elasticsearch version** (`bin/elasticsearch --version`): reported in 7.5

**Description of the problem including expected versus actual behavior**:

When Watcher's email action is run multiple times thanks to [foreach](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/action-foreach.html) parameter, then all generated email messages use the same Message-ID header.

[RFC2392](https://tools.ietf.org/html/rfc2392) states that Message-ID should be unique:
`Both message-id and content-id are required to be globally unique. That is, no two different messages will ever have the same Message-ID addr-spec;`

A similar issue was fixed in the past https://github.com/elastic/elasticsearch/pull/30112 by adding action_id to Message-ID. With `foreach` it's not enough since we have one action but generate multiple email messages.

**Comment by jgregmac** [comment]
Bummer!  I am having this problem as well.  It is preventing delivery of Watcher alerts to our ticketing system as the receiving system insists on strict adherence to RFC2392 Message-ID uniqueness.

**Comment by kkojouri** [comment]
I'm seeing the same issue on our side, getting the same Message-ID even when the body of the messages are different. This results in missing alerts in our ticketing system (which doesn't support Webhook).

**Comment by toby-sutor** [comment]
This has been addressed here: https://github.com/elastic/elasticsearch/pull/56574

**Comment by joegallo** [comment]
Closing since https://github.com/elastic/elasticsearch/pull/56574 has been merged.
