### ISSUE TITLE
Gradle build projects should declare unique group and artifact IDs

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52528]
Gradle 6.2 enforces that projects have unique publishing coordinates and fails otherwise: https://gradle-enterprise.elastic.co/s/klqf2th25y4ae/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

While we can temporarily disable this additional check (since we don't publish QA projects) we should probably go back and fix the actual problem at some point as this could potentially cause other issues in dependency resolution.

**Comment by rjernst** [comment]
@mark-vieira can you note here which group/artifact combos are duplicated currently?

**Comment by mark-vieira** [comment]
I don't have an exhaustive list. I suspect the build fails at first encounter so there are likely more. I could probably whip up a script to generate a list though. I'll look into doing so.

**Comment by mark-vieira** [comment]
This was resolved by #96536.
