### ISSUE TITLE
Add a documentation guide on ES shard sizing

### ISSUE THREAD

**Issue by zuketo** [elastic/elasticsearch#52541]
The most popular guide available today on ES shard sizing is on the Elastic blog: https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster

Unfortunately, the blog entry above was created in 2017 and is not actively maintained. Let's move this content over to our documentation and determine what information (if any) should be updated within the guide. 

By moving this content to our documentation, it will be easier for the team to maintain the recommendations and make changes when needed.

**Comment by jpountz** [comment]
+1 a number of assumptions in that blog have been invalidated since then

**Comment by abprash** [comment]
Can i work on this one?

**Comment by jpountz** [comment]
@abprash Thanks for helping, but this is something we'll want to work on internally.

**Comment by abprash** [comment]
Sounds good. Thanks.

**Comment by bczifra** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/avoid-oversharding.html is now available in the documentation and touches on this topic.
