### ISSUE TITLE
SQL: CLI validate availability of the SQL module on start

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#52574]
When the CLI is starting, it GETs the root path of Elasticsearch only (`checkConnection()`, `serverInfo()`), validates its version and proceeds to wait for and process user terminal input.

If SQL is not available though, this will only become evident once the user tries to execute a query. An alternative to this would be to fail earlier, by having CLI do a quick check against the SQL endpoint part of the starting sequence (much like any SQL application's "Test connection" functionality).

This would be useful once one CLI can be used against heterogenous deployments at potentially different versions.

**Comment by wchaparro** [comment]
Superceded by ES|QL
