### ISSUE TITLE
Standardize source names across contexts in scripting

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#52593]
For ingest pipelines, it's accessed via `ctx._source` elsewhere it's `params._source`.  We should provide consistent access.

**Comment by stu-elastic** [comment]
There's an annoying difference between the ingest processor context and the reindex context.  Updates in ingest processor context happens in `ctx` vs `ctx['source']` in reindex.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. Since the fields api provides a new way to access source, I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
