### ISSUE TITLE
Partially parse `source` documents to speed up `source` access

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#52591]
When `source` is accessed, it is fully parsed.  If a script only uses a single field, most parsing and object construction is wasted.

We could implement a "skip parser" that does not extract values but rather keeps track of parsing context (inside string, inside map, etc) until we hit the desired field, and provide that field to the script.

**Comment by stu-elastic** [comment]
Here's the approach we're gonna try:
* Given a list of fields, provide a view of those values (including the ES specific logic of folding multiple instances into an array)
* Try to avoid as many allocations as possible, do this by using a facade to provide access to those objects, including nested objects

For first deliverable the list of fields are concrete, no wild cards.

**Comment by jtibshirani** [comment]
@stu-elastic how to you see this relating to https://github.com/elastic/elasticsearch/issues/25168? Would it make sense to close one of the two issues?

**Comment by stu-elastic** [comment]
I'll put it up for discussion in painless triage meeting today.

**Comment by stu-elastic** [comment]
Yup, adding a label to that one and putting it on our project board.
