### ISSUE TITLE
Enable working with real documents via doc-ids in scripting execute API

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#52605]
Target: Painless Lab

Goal: Allow users to work with a real documents from an index via the execute API.  This will make scripts developed in Painless Lab portable to their correct context.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
