### ISSUE TITLE
Painless constant folding misses folds of same prescedence

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#52611]
For example:
`def fToC(double f) { return (f - 32) * (5.0 / 9)}` ->
```asm
  public static fToC(D)Ljava/lang/Object;
    LDC 1000000
    ISTORE 2
   L0
    LINENUMBER 29 L0
   L1
    LINENUMBER 30 L1
    DLOAD 0
    LDC 32.0
    DSUB
    LDC 0.5555555555555556
    DMUL
```

`(5.0 / 9)` is folded to `0.5555555555555556`

However, if we don't use parens then `5.0 / 9` is not folded due to how we process the tree.
`def fToC(double f) { return (f - 32) * 5.0 / 9 }`
```asm
public static fToC(D)Ljava/lang/Object;
    LDC 1000000
    ISTORE 2
   L0
    LINENUMBER 29 L0
   L1
    LINENUMBER 29 L1
   L2
    LINENUMBER 30 L2
    DLOAD 0
    LDC 32.0
    DSUB
    LDC 5.0
    DMUL
    LDC 9.0
    DDIV
```

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
