### ISSUE TITLE
Integrity checks for snapshots

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#52622]
As far as I am aware, Elasticsearch does not implement integrity checks for snapshots. If I am not mistaken, Elasticsearch will silently restore restore snapshots partially if, e.g., data of one shard within the snapshot has been corrupted.

It would be an invaluable feature for users if Elasticsearch would store integrity hashes (e.g., for each shard) together with each snapshot. These hashes may then be used to:

- upon restoring a corrupted snapshot: inform the user that a snapshot has been only partially restored due to a corrupt shard
- upon taking a new incremental snapshot: take a new snapshot of any parts that might have been corrupted

**Comment by original-brownbear** [comment]
> upon restoring a corrupted snapshot: inform the user that a snapshot has been only partially restored due to a corrupt shard

This already happens. All files (including snapshot metadata) in the snapshot come with Lucene footers that contain a checksum of the file contents. We will not silently skip corrupted data if any file in a shard is corrupted and properly fail the restore for this shard.

> upon taking a new incremental snapshot: take a new snapshot of any parts that might have been corrupted

This one is trickier. We can't really do this for every new snapshot as it would entail downloading all the files that we are reusing from previous snapshots wouldn't it? In the real world this could be massive amounts of data and would not be feasible.
Also, if a snapshot got corrupted at a given location, I don't think we should quietly reuse that location? What guarantees would we have that the next snapshot to it wouldn't again be corrupted?

**Comment by fkelbert** [comment]
>>upon taking a new incremental snapshot: take a new snapshot of any parts that might have been corrupted

> We can't really do this for every new snapshot as it would entail downloading all the files that we are reusing from previous snapshots wouldn't it? In the real world this could be massive amounts of data and would not be feasible.

Can we detect this and inform the user, at least? This way, they would have a chance/choice to create a new backup, potentially in a different location.

In general, what is the recommended way to ensure snapshot integrity then? RAID0 or other methods on the backup drive? 

Is this something we can document better in the snapshot/restore documentation?

**Comment by original-brownbear** [comment]
Sorry was out for 2 weeks, continuing here:

> Can we detect this and inform the user, at least? 

How would we detect it? The only way to do so is to literally checksum every file in the repository, we can't do this as part of any other operation on the repository.
There has been talk about adding a verification endpoint in the past that would allow you to manually run this check. Is this what you had in mind?

> In general, what is the recommended way to ensure snapshot integrity then? RAID0 or other methods on the backup drive?

We don't make any active recommendations here. Obviously, as with any other backup, you need to ensure that the volume you write to is safe. For the cloud provider backed blob stores and HDFS (assume appropriate replication settings) that can probably be assumed.
For an NFS based repository the user will have to make sure that the backing file system does not get corrupted. How they do it (IMO) is not something we can document as there's just far too many possible setups to cover?

> Is this something we can document better in the snapshot/restore documentation?

See above, I'm not sure what we could possibly document here. The fact that whatever volume the snapshots go to must be safe/durable seems to be a given to me. Given specific instructions on how to set up NFS is way beyond the scope of our docs I'd say.

**Comment by fkelbert** [comment]
> Sorry was out for 2 weeks, continuing here:
> 
> > Can we detect this and inform the user, at least?
> 
> How would we detect it? The only way to do so is to literally checksum every file in the repository, we can't do this as part of any other operation on the repository.

Yes, I had been thinking of checksums. But I am unable to say how practical this is.

> There has been talk about adding a verification endpoint in the past that would allow you to manually run this check. Is this what you had in mind?

I am not aware of this discussion. But some check, even manual, is better than none, imo.

> > In general, what is the recommended way to ensure snapshot integrity then? RAID0 or other methods on the backup drive?
> 
> We don't make any active recommendations here. Obviously, as with any other backup, you need to ensure that the volume you write to is safe. For the cloud provider backed blob stores and HDFS (assume appropriate replication settings) that can probably be assumed.
> For an NFS based repository the user will have to make sure that the backing file system does not get corrupted. How they do it (IMO) is not something we can document as there's just far too many possible setups to cover?

I understand that we do not want to make active recommendations. But I think we should at least inform our users that they are expected to ensure the integrity (and possibly point to some common solutions such as RAID).

**Comment by original-brownbear** [comment]
> I am not aware of this discussion. But some check, even manual, is better than none, imo.

Let's build the manual integrity check here then :) I think that's the best we can do really. There is no way of doing an automated check that wouldn't significantly increase the cost of the snapshot functionality for Cloud backed repositories.

> But I think we should at least inform our users that they are expected to ensure the integrity 

I think I disagree here. Who would ever expect that snapshots will continue to work if the underlying storage medium gets corrupted over time? :) This isn't just a thing specific to snapshots, no matter what a user would use an NFS setup that randomly corrupts data for would probably fail in the long run. I'd take a stable and consistent NFS as a given here tbh.

**Comment by DaveCTurner** [comment]
> But I think we should at least inform our users that they are expected to ensure the integrity

I do agree with this, but this raises further questions about how exactly they should do that. Today we don't have a good answer for that -- "avoid storage that might corrupt your data" isn't really helpful, and we don't have a good procedure for taking backups of the repository itself. I opened https://github.com/elastic/elasticsearch/issues/54944 for this point.

**Comment by DaveCTurner** [comment]
@fkelbert I forgot to say that your opinion on #54944 would be helpful to hear, given the context of this discussion.

**Comment by DaveCTurner** [comment]
Hi @Matthew-Jenkins, thanks for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I hide your comment.
