### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by anmol27katyani** [elastic/elasticsearch#52632]
Situation: I have a Linux system and creating a cluster of 3 nodes inside of docker but it is not working fluently

Looking for help,**Target** is to get 3 nodes running and I have access to elasticsearch.yml of individual yml of those 3 nodes.
Task: I want to **create 3 nodes** in a cluster and I have successfully created it as well but now I wish to tweak the cluster created so my approach was to update the **elasticsearch.yml** file for the same however I followed a steps, I have not met my requirements. I did not know how to do it so followed a few steps, **Please help**

Action :   
I tried the followign commands in order
` sudo docker build --tag=elasticsearch-custom `  
`docker build --tag=elasticsearch-custom`
[build log](https://gist.github.com/anmol27katyani/d57b2d8d0753586e2b328f592841fb0f)
[docker.compose.yml](https://gist.github.com/anmol27katyani/b2fb3cadf2f25620cfbb1d403bf4726c)

**Comment by matriv** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
