### ISSUE TITLE
Deprecate & remove undocumented alternatives to the nodes hot threads API

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#52640]
The [nodes hot threads API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html) has some little-known synonyms:

https://github.com/elastic/elasticsearch/blob/a11ccb83d45905e0f48907b29be9489bb6260d96/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestNodesHotThreadsAction.java#L43-L54

These date back to its introduction in v0.20 but I do not think they have ever been documented. They seem unnecessary and I think we should remove them. There is of course a risk that someone out there is using one of these undocumented endpoints (perhaps due to a typo) and this is a breaking change so we should deprecate them first of course.

**Comment by muachilin** [comment]
I would like to work on this! Thanks!

**Comment by DaveCTurner** [comment]
Thanks @muachilin, go ahead. Note that this'll take two PRs in sequence: the first to deprecate these endpoints and the second to remove them, and both should be opened against the master branch. We will take care of backporting the first. See e.g. #50499 for an example of a PR that deprecates things in the REST API, and note particularly that this includes a test showing that we do indeed log the right warnings when the deprecated API is used.

**Comment by atmask** [comment]
Hi, @DaveCTurner I was looking to help on this issue but it looks as though the endpoints are already deprecated? 
https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/nodes.hot_threads.json#L104

**Comment by muachilin** [comment]
I am working on this to add tests and deprecate warnings for this file!

**Comment by muachilin** [comment]
@atmask Do you want to work on this? But I've claimed this issue

**Comment by atmask** [comment]
@muachilin Ah I see, I didn't realize the issue was actively being taken care of! All yours!

**Comment by muachilin** [comment]
@atmask Thank you very much!

**Comment by DaveCTurner** [comment]
Interesting observation @atmask, thanks. I had indeed not noticed that these endpoints were documented and deprecated, in the REST API spec (see #39063). We also need the deprecation warnings in the REST handler too since there's a risk that clients won't all notice them.

**Comment by muachilin** [comment]
@DaveCTurner I see! I have added warnings and made some tests about this.

**Comment by jasontedor** [comment]
This was deprecated in 7.7.0 in #52930. @muachilin are you interested in proceeding with the removal of the deprecated endpoints in the master branch?

**Comment by muachilin** [comment]
@jasontedor Sure!

**Comment by muachilin** [comment]
Thank you :)

**Comment by mathewTH** [comment]
Is this still being worked on?

**Comment by jasontedor** [comment]
@muachilin Did you still want to work on removing the dedicated endpoints from master (8.0.0)?

**Comment by erickmp07** [comment]
@jasontedor If he didn't, I'd like to work on it.

**Comment by jasontedor** [comment]
@erickmp07 Thanks. Let's give @muachilin some time to reply. If there's no reply by this time tomorrow, it's yours.

**Comment by muachilin** [comment]
Hi! @erickmp07 @jasontedor I would like to work on it! Thank you :)

**Comment by muachilin** [comment]
@jasontedor I open a PR (#55109) to remove the deprecated end points for hot threads API. Thanks!
