### ISSUE TITLE
How script fields access parent document properties？

### ISSUE THREAD

**Issue by hubiao1** [elastic/elasticsearch#52670]
`{
  "from": 0,
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "has_parent": {
            "parent_type": "myparent",
            "score": true,
            "inner_hits": {},
            "query": {
              "bool": {
                "must": [
                  {
                    "bool": {
                      "should": [
                        {
                          "term": {
                            "columns.id": 14
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "exists": {
            "field": "split_text_int_sore"
          }
        }
      ]
    }
  },
  "aggregations": {
    "genders": {
      "terms": {
        "script": {
          "lang": "painless",
          **"inline": ""**
        },
        "size": 100,
        "order": {
          "_count": "desc"
        },
        "min_doc_count": 1
      }
    }
  }
}`

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
