### ISSUE TITLE
[CI] TermsAggregatorTests.testSupportedFieldTypes fails reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52681]
This looks to be a newly added test which has failed 3 times already. This also reproduces locally for me.

https://gradle-enterprise.elastic.co/s/xqoxiluwuzono/tests/nfxodyych4uas-al6l6qgxmtvfa?open-stacktraces=WzBd

```
java.lang.AssertionError: Aggregator [terms] supports field type [ip] but executing against the field threw an exception: [class org.apache.lucene.index.ParallelCompositeReader cannot be cast to class org.apache.lucene.index.DirectoryReader (org.apache.lucene.index.ParallelCompositeReader and org.apache.lucene.index.DirectoryReader are in unnamed module of loader 'app')]Close stacktrace
at __randomizedtesting.SeedInfo.seed([37F644DC7A7897F3:90E5F9E8055C4EC0]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.search.aggregations.AggregatorTestCase.testSupportedFieldTypes(AggregatorTestCase.java:661)
```

**Comment by mark-vieira** [comment]
Since this has failed a number of times already and reproduces I've muted this in `master` with fb4032f223ea1c09c12fd4bea3b2c2e3abef7c73.

**Comment by mark-vieira** [comment]
@polyfractal since you added this test case recently do you mind taking a look here?

**Comment by polyfractal** [comment]
On it, thanks for the ping!

**Comment by polyfractal** [comment]
Gah, this was a dumb mistake on my part.  Will get a fix up in a sec

**Comment by mark-vieira** [comment]
Thanks @polyfractal!
