### ISSUE TITLE
How to build a query "fallback chain" above the ES query DSL?

### ISSUE THREAD

**Issue by chenzx** [elastic/elasticsearch#52692]
I want do this:

when given a query keyword, do 2 kinds of query: exact match_phrase, & fuzzy.

the key point is, i do not want send 2 querys, or use bool should query to combine the 2.
which i want, is some kind of "fallback chain", which does the first query, if having results, then directly return, or else try the second query as a fallback...

How can i do this using the standard ES query DSL?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
