### ISSUE TITLE
EQL: Improve handling for non-keyword field exact matching

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elasticsearch#52709]
The error messaging could be improved, which is currently:
"1:11: [multi_field.english == 'bar'] cannot operate on first argument field of data type [text]: No keyword/multi-field defined exact matches for [english]; define one or use MATCH/QUERY instead"

Need to discuss "to get consensus about how we deal with exact matches on analyzed fields - whether we prevent any exact comparison against them or introduce some other type of comparison (inexact matches - say ~=)"

This is related to the PR https://github.com/elastic/elasticsearch/pull/52664

Discuss ...

**Comment by costin** [comment]
The medium term goal is to have this behavior within Elasticsearch itself so, as a consumer, one would not have to pick the right type of field but rather have the engine do it automatically based on the query raised and the target field.
