### ISSUE TITLE
Bool with minimum_should_match set to zero not honored

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#52735]
While running a query bool query with only `should` clauses, it appears that you cannot set `minimum_should_match` to `0`.

```http
POST /test/_bulk?refresh=wait_for
{ "index": { "_id": "1" } }
{ "value": 1 }
{ "index": { "_id": "2" } }
{ "value": 2 }

GET /test/_search
{
  "query": {
    "bool": {
      "minimum_should_match": 0,
      "should": [
        {
          "term": {
            "value": 1
          }
        }
      ]
    }
  }
}
```

This will return 1 document, instead of what I would have expected to be scoring `1`, and returning `2` (unscored). Ignoring the parameter becomes a little obvious by adding a `match_all` into the mix to counter this behavior (`match_all` can be either a `filter` or `must`):

```http
GET /test/_search
{
  "query": {
    "bool": {
      "filter": [ { "match_all": { } } ],
      "minimum_should_match": 0,
      "should": [
        {
          "term": {
            "value": 1
          }
        }
      ]
    }
  }
}
```

This returns both documents with the `_score` adjusted as one would expect. I tested this as far back as 5.6 and the behavior is at least consistent, but unexpected.

**Comment by repl-chris** [comment]
I also just got burned by this....easy to work around, but yeah a little unexpected with nothing in the documentation to indicate this behavior

**Comment by faizan-turing** [comment]
facing the same issue, any progress or documentation on this??

**Comment by faizan-turing** [comment]
> No matter what number the calculation arrives at, a value greater than the number of optional clauses, or a value less than 1 will never be used. (ie: no matter how low or how high the result of the calculation result is, the minimum number of required matches will never be lower than 1 or greater than the number of clauses.

probably bcs of this
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html

**Comment by pickypg** [comment]
> probably bcs of this https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html

Except it does accept the `0` in the workaround example.

**Comment by catmanjan** [comment]
Would be nice to support this, or if not possible, give a warning

**Comment by javanna** [comment]
Heya, I am trying to follow what should change here, and based on the docs pasted above that say that values less than 1 will never be considered, I wonder what the bug is here. The title of this issue says "minimum should match set to zero not honored" but the docs are clear that a value less than zero will not be honored. Could you clarify and help me understand please?

**Comment by pickypg** [comment]
I don't believe that it used to be clearly documented.

Separately, if it's not supposed to be less than 1, it doesn't make sense that it's not thrown as a bad request.

And, separate from that, disallowing zero for relevance boosting seems to be eliminating a valuable use case.

**Comment by javanna** [comment]
We discussed this with the team. Although it is Elasticsearch that makes the decision of not providing `0` for minimum should match when there are only optional clauses, even if it was passed down the line, Lucene would still require for at least one required clause. Also, this can be easily worked around by adding one required match_all clause, hence we are opting for leaving things as they are.

**Comment by pickypg** [comment]
Shouldn’t it at least be a bad request to set it as `0`?

**Comment by javanna** [comment]
Ideally, but this could break existing users, and the current behaviour has been documented for years. I can imagine that existing users are building queries dynamically and may end up with queries that are perfectly valid, and some that may end up with only should clauses and minimum should match set to `0` which would then cause an error. I am wondering if it's worth potentially breaking existing applications. @jpountz do you have an opinion?

**Comment by vhugues** [comment]
@javanna even if queries are dynamically built, request sent to ES that contain explicit minimum_should_match = 0 do not work like expected. So the response does not match the requested document, and this use case will probably generate bugs without throwing any warning/error.
