### ISSUE TITLE
SQL: IP type reported to have column size of 0

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#52762]
The `IP` type is currently reported to have the column size (i.e. older "precision") of 0. This is reported in `SYS TYPES`.
This value is passed to the client applications and older ones use it as-is to allocate buffers to have the values returned in; which results in them getting just a string null-terminator only for the IP fields (i.e. empty string).

The value should contain the maximum length of an IP address in characters (as the type is backed by a KEYWORD).

(Collaterally, the `DataType`.`size` for `IP` value should be corrected from current 39 to 45.)

**Comment by matriv** [comment]
`master` : 815f01747a4d54a274ca248af6fc08e5ea0728c1
`7.x` : 1d5c84270033bc1b919019f9ac61ebf1c6dc02f8 
`7.6` : 353128cac111ae569d8c5a8fe6d9ff9bc90e4434
`6.8` : c5bc9ae6ec06d0fc0c096a1d27dda701a29a153b
