### ISSUE TITLE
[DOCS] Default values for `index_option` mapping parm are inaccurate.

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#52777]
The  [`index_options` mapping parameter](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-options.html) docs state the following:

> `text` fields use `positions` as the default, and all other fields use `docs` as the default.

However, as outlined in #50136, some datatypes other than `text`, such as range datatypes or `geo_point`, use `positions` as the default value.

See https://github.com/elastic/elasticsearch/pull/50136#issuecomment-565005070

**Comment by mayya-sharipova** [comment]
Indeed, all these `index_options` only make sense for `text` field where we are building a postings list.
I imagined before numeric fields were also indexed as text, but not any more. Currently numeric fields are indexed only in BKD trees and docValues, and for these data structures `index_options` are not applicable.
