### ISSUE TITLE
Elastic Search Default _score (Levenstein)

### ISSUE THREAD

**Issue by vinaychila** [elastic/elasticsearch#52802]
Hi,

Source: vinay
Target: vinayc

When I searched using above fields in online Levelstein we are getting score as: 84%.
check using the following link: https://awsm-tools.com/text/levenshtein-distance

When I searched in elastic against the following document and query am getting score as:  "_score": 0.80259144, which is different from levenstein.

Query:

GET levensteinindex/_search
{
  "query": {
      "match": {
      "name":{
        "query":"vinay",
        "fuzziness":"Auto"
        }
      }
    }
}

index with document:
================
PUT /levensteinindex/_doc/1
{
  "name": "vinay"
}

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
