### ISSUE TITLE
DNS cache or TTL is -1 when RestClientBuilder creates CloseableHttpAsyncClient and hence not compatible with multiple clusters behind GSLB

### ISSUE THREAD

**Issue by harshahst** [elastic/elasticsearch#52836]
5.6.0 onwards and even in 7.6.0 below is the issue

RestClientBuilder creates CloseableHttpAsyncClient with default TTL value of -1.
Meaning CloseableHttpAsyncClient contains PoolingNHttpClientConnectionManager with CPool.timeToLive=-1.
There is no additional method to create CloseableHttpAsyncClient with different or +ve value for CPool.timeToLive.

Due to this issue, we are unable to use multiple clusters behind Load Balancer or GSLB.

**Comment by swallez** [comment]
The `CPool.timeToLive` setting is the keepalive time for connections. You can override it on the http client builder:

```java
RestClientBuilder builder = RestClient.builder(...);
builder.setHttpClientConfigCallback(
    httpClientBuilder -> httpClientBuilder.setKeepAliveStrategy(...)
);
```

That being said, it seems that [setting a low keepalive time should also solve the DNS issues you mention](https://stackoverflow.com/questions/29107681/httpclients-poolinghttpclientconnectionmanager-and-dns-caching).

Can you cross-check?

**Comment by Sovietaced** [comment]
> Can you cross-check?

Confirmed that this does work.

```
    private val client = RestHighLevelClient(RestClient.builder(HttpHost.create(httpHost))
        .setHttpClientConfigCallback { it.setKeepAliveStrategy { _, _ -> 60L } })
```

**Comment by harshahst** [comment]
Yes, it is working - however cluster switch very slow even when I use 5ms for keepAliveStrategyMillis.
Say we have EAST and WEST Data Centers with 3 clusters each and behind GSLB.
When I keep refresh actuator /health check w.r.t. Spring Boot in WEST - cluster switch is very very slow.

```
if (keepAliveStrategyMillis() > 0) {
   httpClientBuilder.setKeepAliveStrategy((response, context) -> Duration.ofMillis(keepAliveStrategyMillis()).toMillis());
}
```

**Comment by harshahst** [comment]
Since it works, closing the ticket
