### ISSUE TITLE
Ingest pipeline _simulate request with empty docs array never returns a response

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#52833]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0

**Description of the problem including expected versus actual behavior**:
When sending an ingest pipeline `_simulate` request, If the value of `docs` is an empty array, a response is never returned.

I would've expected the request to either immediately fail and ask for the `docs` array to have at least 1 document, or have the request succeed and return:
```
{
  "docs" : []
}
```

**Steps to reproduce**:
1.  Send  `POST _ingest/pipeline/_simulate` with the following payload:
```json
{
  "pipeline": {
    "processors": []
  },
  "docs": []
}
```
 2. Notice that a response is never returned.

**Comment by danhermann** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/52937
