### ISSUE TITLE
Deleting a Filebeat- and/or Metricbeat- Index in Elastic Search Causes a GraphQL Error 

### ISSUE THREAD

**Issue by AmirSedrak** [elastic/elasticsearch#52852]
Hi guys, 

Any time I delete an old Filebeat-* and/or Metricbeat-* Index in Elastic Search and a new index is automatically created (Because Filebeat or Metricbeat are still passing data to my ELK stack). I get this error: 

```
Failed to load data sources.

Error: GraphQL error: [illegal_argument_exception] Fielddata is disabled on text fields by 
default. Set fielddata=true on [event.dataset] in order to load fielddata in memory by 
uninverting the inverted index. Note that this can however use significant memory. 
Alternatively use a keyword field instead. 

(and) [illegal_argument_exception] Fielddata is disabled on text fields by default. 
Set fielddata=true on [event.dataset] in order to load fielddata in memory by uninverting 
the inverted index. Note that this can however use significant memory. Alternatively use 
a keyword field instead.

```
I've followed this stackoverflow guide: https://stackoverflow.com/questions/38145991/how-to-set-fielddata-true-in-kibana

However, I get: 
``` 
"error": "status:400" "index [metricbeat-7.5.1/XjAAfPpnRO6aLLCmhDsC5w] already exists"

```

I'm still looking at the Elasticsearch documents, however, it's kind of confused on where to go to set fielddata=true on [event.dataset] . I don't mind fixing this issue using the Kibana dashboard either.

**Comment by markharwood** [comment]
Thanks very much for your interest in Elasticsearch.

>I'm still looking at the Elasticsearch documents, however, it's kind of confused on where to go to set fielddata=true on [event.dataset]

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
