### ISSUE TITLE
ElasticsearchNodesSniffer complains about  "unknown role [ml]"

### ISSUE THREAD

**Issue by bobbyi** [elastic/elasticsearch#52864]
We have an API server using version 7.5.1 of the elasticsearch-rest-high-level-client and elasticsearch-rest-client-sniffer Java libraries, which matches the version of ES used on our cluster. It is working fine, but our application log ends up filled with messages saying
`WARN o.e.c.s.ElasticsearchNodesSniffer - unknown role [ml] on node <name>`

I asked about this on the official Elastic forum and was told by David Turner
(an Elastic Team Member) that this behavior is a bug and I should file it here. Specifically, he says "The ElasticsearchNodesSniffer only knows about the three core roles... IOW it was not updated when node roles became pluggable", and points to the code here:

https://github.com/elastic/elasticsearch/blob/bbbdf949a9d63dbc795ce8dd7dbd529d5f40b98b/client/sniffer/src/main/java/org/elasticsearch/client/sniff/ElasticsearchNodesSniffer.java#L209-L222

**Comment by jasontedor** [comment]
Ouch, that's a bad bug. This relates to #43175 and #45174. I own ensuring this is fixed.

**Comment by jasontedor** [comment]
I opened #52888.
