### ISSUE TITLE
There are search and aggregation issues with date type fields in version 5.6

### ISSUE THREAD

**Issue by hirampeng** [elastic/elasticsearch#52869]
my index mapping:
"mappings": { "my_type": { "properties": { "age": { "type": "integer"},"birth": { "type": "date","format": "yyyy-MM-dd HH:mm:ss||epoch_millis"},"group": { "type": "keyword"},"price": { "type": "float"}}}}

my index date:
[
{ "group": "a","age": 5,"price": 5.2,"birth": "2018-03-03 03:00:00"},
{"group": "c","age": 8,"price": 5.2,"birth": "2018-03-03 23:00:00"}
]

my search query:
{
    "size": 0,
    "timeout": "120000ms",
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "birth": {
                            "from": 1519833600000,
                            "to": null,
                            "include_lower": true,
                            "include_upper": true,
                            "boost": 1
                        }
                    }
                },
                {
                    "range": {
                        "birth": {
                            "from": null,
                            "to": 1520092799000,
                            "include_lower": true,
                            "include_upper": true,
                            "boost": 1
                        }
                    }
                }
            ],
            "disable_coord": false,
            "adjust_pure_negative": true,
            "boost": 1
        }
    },
    "aggregations": {
        "date_histogram#birth$day": {
            "date_histogram": {
                "field": "birth",
                "interval": "day",
                "offset": 0,
                "order": {
                    "_key": "asc"
                },
                "keyed": false,
                "min_doc_count": 0
            },
            "aggregations": {
                "value_count#birth": {
                    "value_count": {
                        "field": "birth"
                    }
                }
            }
        }
    }
}

I want to find out the number of records aggregated by day from 00:00:00 on March 1, 2018 to 23:59:59 on March 3, 2018. Why only one record is returned?I don't understand. Can you help me?
Note: my version is 5.6

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by hirampeng** [comment]
Thank you for your answer. I am now going to the forum for help.
