### ISSUE TITLE
JarHell when running tests in Eclipse

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#52895]
After #52363 we've started to see JarHell exceptions all over the place when trying to run tests in Eclipse. This is mostly because of Eclipse not isolating test and production dependencies.

**Comment by nik9000** [comment]
This seems to happen in all unit test for the analytics module and the eql module. Probably more. I'm not sure.

**Comment by costin** [comment]
You're comment on #52363 exposes an issue that I think needs fixing - reproducing here:

> This broke my ability to run x-pack:plugin:analytics tests in my IDE because analytics pulls in the hlrc for testing and the hlrc pulls in this for testing. Somehow that causes two versions of guava to be on the classpath. Could we flip the testing dependency so this depends on hlrc instead of hlrc depending on it? That way testing the Elastic licensed bits depends on the Apache licensed bits. And it makes Eclipse happy.

Indeed HLRC pulls dependencies from other projects but itself, is used by the testing of others.

**Comment by costin** [comment]
@nik9000 I believe your commit from last week fixed this problem. Can you please double check if we can close the ticket?

Thanks

**Comment by nik9000** [comment]
I can confirm these tests work for me now! Thanks for the ping!
