### ISSUE TITLE
Analyzing index_prefixes is not highlighting matches

### ISSUE THREAD

**Issue by matiasponce** [elastic/elasticsearch#52904]
Creating this index:

      "mappings" : {
          "properties": {
            "field": {
              "type": "text",
              "index_prefixes": {
                  "min_chars" : 3,
                  "max_chars" : 8
               }
            }
         }
      }
and this query:

      {
        "highlight": {
          "fields": {
             "*": {}
           }
         },
          "query": {
  	    "multi_match":{
  		"type":"phrase_prefix",
  		"query":"pre"
  	    }
          }
    }

The result returned is:

      {
	"took": 3,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 1,
			"relation": "eq"
		},
		"max_score": 1.1212674,
		"hits": [
			{
				"_index": "my_index",
				"_type": "_doc",
				"_id": "id1",
				"_score": 1.1212674,
				"_source": {
					"field": "prefixed text"
				}
			}
		]
	}
     }

without the highlights.

And if i do the same with a shorter query (a lower length than the min_chars property):

     {
       "highlight": {
        "fields": {
           "*": {}
          }
         },
         "query": {
  	  "multi_match":{
             "type":"phrase_prefix",
  	     "query":"pr"
  	  }
        }
   }

I get the highlights:

       {
	"took": 2,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 1,
			"relation": "eq"
		},
		"max_score": 1.07389,
		"hits": [
			{
				"_index": "my_index",
				"_type": "_doc",
				"_id": "id1",
				"_score": 1.07389,
				"_source": {
					"field": "prefixed text"
				},
				"highlight": {
					"field": [
						"<em>prefixed</em> text"
					]
				}
			}
		]
	}
       }

**Comment by jimczi** [comment]
The issue was already reported in #49069 so I hope you don't mind if I close this. You can follow the progress and/or add comments in the original issue. Thanks for reporting @matiasponce.
