### ISSUE TITLE
Enhancement: Watcher action to push messages to kafka topic

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#52903]
Add watcher `kafka` [action](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/actions.html) to send message to a kafka topic

Currently it's possible to use a webhook with some custom application which would then ingest onto kafka but there is no easy way to send a messafe directly to a kafka topic

**Comment by jtwillis92** [comment]
+1 This would be an incredibly useful feature

**Comment by pmanvi** [comment]
+1 
waiting for the same. The best would be to include native support, we do have option to run REST server and include in action. https://docs.confluent.io/2.0.0/kafka-rest/docs/intro.html

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
