### ISSUE TITLE
EQL: Returning _source for matching documents

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#52912]
Currently all matching documents under `events` are returned as 

```json
"hits" : {
        "total" : {
            "value" : 1000,
            "relation" : "eq"
        },
        "events" : [
            {
                "_index" : "my_index",
                "_id" : "0",
                "_source" : {
                    "date" : "2009-11-15T14:12:12",
                    "event": {
                        "type": "process",
                        ...
                    },
```

Similar to other search APIs, returning the document `_source` instead of individual fields is a straight forward way (especially when dealing with large metrics mappings that can have 100s or 1000s of fields).

As a consumer of said response is that good enough? Would certain fields (like `@timestamp`) need to be retrieved in a `normalized` format (as the source will contain the insert time value)?

/cc @tsg @stacey-gammon 

https://github.com/elastic/elasticsearch/issues/49634

**Comment by tsg** [comment]
I like optimizing for consistency with the other search APIs, so I like this solution. I imagine parameters like source filtering could be supported in the future?

I'm not sure about normalizing `@timestamp`, for the SIEM team I think it's still better to keep consistency with the regular search API, as we're going to generally support both in the same places.

**Comment by costin** [comment]
> I imagine parameters like source filtering could be supported in the future?

Sure - a potential downside is that filtering would be applied across all documents which are likely to have different mappings.

**Comment by stacey-gammon** [comment]
Sorry I don't really follow this.  What do you mean by "as the source will contain the insert time value" .. what is the "insert" time value?

What do you mean by `returning the document _source instead of individual fields in a straight forward way (especially when dealing with large metrics mappings that can have 100s or 1000s of fields).`

Is the alternative approach something like:

```
"hits" : {
        "total" : {
            "value" : 1000,
            "relation" : "eq"
        },
        "@timestamp": "2009-11-15T14:12:12",
        "events" : [
            {
                "_index" : "my_index",
                "_id" : "0",
                "_source" : {
                    "date" : "2009-11-15T14:12:12",
                    "event": {
                        "type": "process",
                        ...
                    },
```

or you mean something like this, with no `_source` and no

```
"hits" : {
        "total" : {
            "value" : 1000,
            "relation" : "eq"
        },
        "events" : [
            {
               "type": "process",
               "@timestamp": "2009-11-15T14:12:12",
               ....
            }],
```

Or wait!  Maybe you are talking about what you did (are doing?) for SQL to help Kibana out with a smaller response format and do something like:

```
"hits" : {
        "total" : {
            "value" : 1000,
            "relation" : "eq"
        },
        "columns": ["date", "type", ...]
        "rows" : [
          ["2009-11-15T14:12:12", "process", ...]
       ]
``` 

So the field names aren't repeated for every single row.  

Am I at all close to understanding what you are talking about? :)

**Comment by costin** [comment]
> What do you mean by "as the source will contain the insert time value" .. what is the "insert" time value?

Whatever was sent to ES without any processing.
Returning `_source` means the original document is returned in case of a match without manipulating its content.

This impacts fields that can have multiple values in particular dates - there might be multiple formats defined for a field and the `_source` will contain one of them.
Normalizing a field (`timestamp`) means the normalized value will be added next to the `_source` in the response.

To wit:

1. Current approach - similar to that of ES:
```
 "events" : [
            {
                "_index" : "my_index",
                "_id" : "0",
                "_source" : {
                    "date" : "2009-11-15T14:12:12",
                    "event": {
                        "type": "process",
                        ...
                    },
```
Essentially the `_source` and metadata about the document.

2. Normalized timestamp :
```
 "events" : [
            {
                "_index" : "my_index",
                "_id" : "0",
               "@timestamp":"2009-11-15:12:34:56Z"
                "_source" : {
                    "date" : "2009-11-15T14:12:12",
                    "event": {
                        "type": "process",
                        ...
                    },
```

`timestamp` is extracted and transformed (if needed) into a dedicated format (ISO) regardless of its source representation.

3. Individual fields: 
```
 "events" : [
            {
                "_index" : "my_index",
                "_id" : "0",
               "@timestamp":"2009-11-15:12:34:56Z"
               "date" : "2009-11-15T14:12:12",
                 "event": {
                     "type": "process",
                      ...
                 },
```
All fields are extracted from `_source` - this however doesn't work on metrics since it hits various limitations on the number of maximum doc values or source fields that can be extracted.

This is a problem in SQL has as well however SQL takes this approach because:
a. the fields are required, the response being tabular
b. SQL has projections, EQL does not. So extracting fields is ..useless.

**Comment by costin** [comment]
As there has been no update since Mar 2nd, I'm closing this ticket. The response does not change and the document source will be returned in full.
