### ISSUE TITLE
EQL: Change request parameter query to filter and rule to query

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#52911]
Currently EQL requests use rule to specify a query - this should be aligned with the existing terminology and be renamed to `query` for consistency with the rest of the APIs, while the existing `query` param, used for passing a query dsl for filtering, renamed to `filter`.

**Comment by aleksmaus** [comment]
Hmm, spammy. Will make a note for the future.

**Comment by aleksmaus** [comment]
Done.
