### ISSUE TITLE
EQL: Test infrastructure improvements

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#52942]
The existing tests could be improved a bit:

- [ ] Where possible, the `XContent` API should be used instead of Jackson for reading JSON files (`EqlActionIT`)
- [ ] `Currently matching the results against the expectation requires manual intervention (extracting `serial_event_id` for example). This shouldn't be the case and be done by the testing infrastructure the test having to deal only with triggering the spec (results and query) to be executed. (see `EqlActionIT`)
- [ ] in `CommonEqlRestTestCase`, the queries initialization can be externalized or templified to make changes somewhat easier

**Comment by aleksmaus** [comment]
Merged and haven't received any objections.
