### ISSUE TITLE
Consider preventing indexing to concrete indexes when ILM is enabled

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#52947]
There are at least 2 situations where accidental indexing to ILM concrete indexes can happen erroneously:

1) User deletes a concrete index during testing and boostrap is bypassed [as described here](https://github.com/elastic/elasticsearch/issues/41699)

2) User has misconfigured beats instance that is not ILM enabled, but is indexing to an index that is ILM enabled, which ends up in ILM failure like this:

```
Index lifecycle error
illegal_argument_exception: index.lifecycle.rollover_alias [metricbeat-7.5.0] does not point to index [metricbeat-7.5.0-2020.02.19]
```

It seems that unless there is a valid case when non-alias indexing to an ILM managed index is expected, preventing it should cut down on error states.

**Comment by martijnvg** [comment]
This ilm bootstrap problem the let us to the data streams proposal (#53100).
With data streams setup via an index template this problem shouldn't occur.
