### ISSUE TITLE
EQL: consistent naming for event type vs event category

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#52941]
EQL historically had used `event_type` to indicate the type for an event.
The decision has been made (#49634) to change this to `event.category` which is not just a simple name but also a slightly different structure, `event` being an object while `category` a sub-field.
Yet the request still uses `event_type_field` to allow overriding the event field.

The two need to be aligned, it's either `category` meaning `event_category_field` or `type` so there's `event.type` (instead of `event.category`).

**Comment by costin** [comment]
Pinging @tsg in case there's a preferred terminology used by SIEM.

**Comment by tsg** [comment]
`event.category` matches best in my opinion, see the possible values [here](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html#ecs-event-category-process). I'd say it makes sense to switch the request setting to `event_category_field`, less confusing that way.

**Comment by costin** [comment]
Thanks - what about timestamp, should it be `@timestamp` or `timestamp` (no leading @)?

**Comment by costin** [comment]
`@timestamp` it is.

**Comment by tsg** [comment]
Yeah, `@timestamp` is the ECS name so we should default to it.

**Comment by aleksmaus** [comment]
Done.
