### ISSUE TITLE
NodeSubclassTests#testReplaceChildren fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#52951]
This failure reproduces with the seed:

```
./gradlew ':x-pack:plugin:ql:test' --tests "org.elasticsearch.xpack.ql.tree.NodeSubclassTests"   -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.InPipe}"   -Dtests.seed=221E160E2C0A0D52
```

```
java.lang.IllegalArgumentException: expected at least [2] children but received [1]

	at __randomizedtesting.SeedInfo.seed([221E160E2C0A0D52:1BE1B543D50C2DAC]:0)
	at org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.InPipe.replaceChildren(InPipe.java:27)
	at org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.InPipe.replaceChildren(InPipe.java:18)
	at org.elasticsearch.xpack.ql.tree.NodeSubclassTests.testReplaceChildren(NodeSubclassTests.java:189)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/958

**Comment by javanna** [comment]
Note that I was not able to reproduce the same failure on master with the same seed.

**Comment by astefan** [comment]
It does repro for me on master....

**Comment by javanna** [comment]
> It does repro for me on master....

Interesting, I must have done something wrong then. Actually, I did not pull latest master I guess :D that should give you a good indication that in the last few days some change made this test fail.

I just muted the test although there was only one failure of it (the one linked above) in the last two months. Please unmute once fixed. I guess I need to mute also on master.

**Comment by astefan** [comment]
I merged today a PR directly affecting the `InPipe` class involved in test. So, there is definitely something fishy with my changes. Please, mute on master as well.

**Comment by javanna** [comment]
Done, thanks for jumping on this.
