### ISSUE TITLE
Is special license required to use X-pack token API service?

### ISSUE THREAD

**Issue by lakechat** [elastic/elasticsearch#52976]
I am using docker image 7.4.2 with x-pack enabled. I followed document (https://www.elastic.co/guide/en/elasticsearch/reference/7.4/security-api-get-token.html) to test "Get Token API". I logged in as "elastic" builtin user.

Request:
POST /_security/oauth2/token
{
  "grant_type" : "client_credentials"
}

Response:
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "current license is non-compliant for [security tokens]",
        "license.expired.feature": "security tokens"
      }
    ],
    "type": "security_exception",
    "reason": "current license is non-compliant for [security tokens]",
    "license.expired.feature": "security tokens"
  },
  "status": 403
}

Is special license required to use Token API?

![Screen Shot 2020-02-28 at 3 21 03 PM](https://user-images.githubusercontent.com/5877363/75594701-74aa2000-5a3e-11ea-82dd-8dc6804b6e18.png)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
