### ISSUE TITLE
terms aggregation with partition - paging aggregations

### ISSUE THREAD

**Issue by rm2k** [elastic/elasticsearch#52984]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6

**Plugins installed**: []

**JVM version** (`java -version`): 10.0.2

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

so the terms aggregations doesn't support paging, but is there some way to control the  what makes it into `partition`? It seems to be playing unpredictable on me or maybe not. As an example, I have 5 terms and I want to page them in 3 pages of 2 and of course 1 in the last page. 

To my surprise:
 
    page 1: 3 items 
    page 2: 0 items [hm! I didn't expect this one. Is this intentional?]
    page 3: 2 items.

expected:
    
    page 1: 2 items
    page 2: 2 items
    page 3: 1 item only    

my example documents:

    GET marketplace/product/_search
    {
    }

result:

    {
        "took": 121,
        "timed_out": false,
        "_shards": {
            "total": 5,
            "successful": 5,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": 5,
            "max_score": 1,
            "hits": [
            {
                "_index": "marketplace",
                "_type": "product",
                "_id": "5",
                "_score": 1,
                "_source": {
                    "category": "Cars",
                    "dateUpdated": "2020-02-15T14:12:12+02:00",
                    "description": "trying out Elasticsearch"
                }
            },
            {
                "_index": "marketplace",
                "_type": "product",
                "_id": "2",
                "_score": 1,
                "_source": {
                    "category": "Household",
                    "dateUpdated": "2020-01-15T14:12:12+02:00",
                    "description": "trying out Elasticsearch"
                }
            },
            {
                "_index": "marketplace",
                "_type": "product",
                "_id": "4",
                "_score": 1,
                "_source": {
                    "category": "Jobs",
                    "dateUpdated": "2020-02-15T14:12:12+02:00",
                    "description": "trying out Elasticsearch"
                }
            },
            {
                "_index": "marketplace",
                "_type": "product",
                "_id": "1",
                "_score": 1,
                "_source": {
                    "category": "Pets",
                    "dateUpdated": "2009-11-15T14:12:12+02:00",
                    "description": "trying out Elasticsearch"
                }
            },
            {
                "_index": "marketplace",
                "_type": "product",
                "_id": "3",
                "_score": 1,
                "_source": {
                    "category": "Property",
                    "dateUpdated": "2020-02-15T14:12:12+02:00",
                    "description": "trying out Elasticsearch"
                }
            }
           ]
      }
    }

**Steps to reproduce**:

partion 0:

    GET marketplace/product/_search
    {
        "size": 0,
        "aggs": {
            "cats": {
                "terms": {
                    "field": "category.keyword",
                    "size": 2,
                    "include": {
                        "partition": 0,
                        "num_partitions": 3
                    }
                }
            }
        } 
    }

result

    {
        "took": 0,
        "timed_out": false,
        "_shards": {
             "total": 5,
             "successful": 5,
             "skipped": 0,
             "failed": 0
        },
        "hits": {
             "total": 5,
             "max_score": 0,
             "hits": []
        },
        "aggregations": {
            "cats": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 1,
                "buckets": [
                    {
                        "key": "Cars",
                        "doc_count": 1
                    },
                   {
                       "key": "Pets",
                       "doc_count": 1
                   }
                ]
            }
        }
    }

partiotion 1:

    GET marketplace/product/_search
    {
        "size": 0,
        "aggs": {
            "cats": {
                "terms": {
                    "field": "category.keyword",
                    "size": 2,
                    "include": {
                        "partition": 1,
                        "num_partitions": 3
                    }
                }
            }
        } 
    }

result:

    {
        "took": 0,
        "timed_out": false,
        "_shards": {
            "total": 5,
            "successful": 5,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": 5,
            "max_score": 0,
            "hits": []
        },
        "aggregations": {
            "cats": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            }
        }
    }

partion 2

    GET marketplace/product/_search
    {
        "size": 0,
        "aggs": {
            "cats": {
                "terms": {
                    "field": "category.keyword",
                    "size": 2,
                    "include": {
                        "partition": 2,
                         "num_partitions": 3
                    }
                }
            }
        }
    }

result:

    {
        "took": 0,
        "timed_out": false,
        "_shards": {
            "total": 5,
            "successful": 5,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
             "total": 5,
             "max_score": 0,
             "hits": []
        },
        "aggregations": {
            "cats": {
                 "doc_count_error_upper_bound": 0,
                 "sum_other_doc_count": 0,
                 "buckets": [
                     {
                         "key": "Household",
                         "doc_count": 1
                     },
                     {
                         "key": "Jobs",
                         "doc_count": 1
                     }
                 ]
            }
      }
    }

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

mappings:

    GET marketplace/product/_mapping

result:

    {
        "marketplace": {
            "mappings": {
                "product": {
                    "properties": {
                        "category": {
                             "type": "text",
                                 "fields": {
                                      "keyword": {
                                       "type": "keyword",
                                           "ignore_above": 256
                                       }
                                 }
                        },
                        "dateUpdated": {
                            "type": "date"
                        },
                        "description": {
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "type": "keyword",
                                    "ignore_above": 256
                                }
                            }
                        }   
                    }
                }   
            }
        }
    } 

**Provide logs (if relevant)**:

**Comment by markharwood** [comment]
Thanks for your interest. Term partitioning is a large scale divide-and-conquer approach for performing certain types of analysis on millions or billions of unique terms, not evenly dividing small numbers of terms into pages. You should have no need to use this on so few documents.

Launching [this wizard ](https://plnkr.co/edit/eZr7r3KZW02AxNKAHCQa?p=preview) might give you some guidance as to when term partitioning is useful.

This feature is working as expected so I'm going to close this issue. Feel free to drop by our discuss  [forums](https://discuss.elastic.co/) for general questions of this nature.

**Comment by rm2k** [comment]
@markharwood Thanks for the response. I understand the intended purpose and I don't intent to use it on few documents. The above was meant to be just a reproducible example.

The issue I was raising is even on few documents why would a mid partition (i.e. partition 1 in this case) contains 0 terms while all remaining terms are pushed into partition 3. What would be the real purpose as in most times if not all we would process the terms in partition order 1,2,3, ... Am I'm still missing the whole point? If I am then I guess that would be the forum topic.

**Comment by markharwood** [comment]
> Am I'm still missing the whole point?

We use the same form of [hash modulo N](https://www.toptal.com/big-data/consistent-hashing) approach to term routing that is used in lots of distributed system algorithms including our system for routing documents to a choice of shard. It's a well-established practice that in large samples will even the data out across divisions but in very small samples like yours would be uneven. 
If you want to continue a discussion the forum would be the place to do that.
