### ISSUE TITLE
Ability to assume missing field as zero in aggregations

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#5298]
To keep docs reasonably small we omit fields that has zero value, but when we use `avg` or `extended_stats` aggregation it would be nice to make missing values assumed to be zeroes too.

In example below we have 31 970 816 docs in bucket, but only 7 310 of them have non-zero value.

```json
{
   "aggregations": {
      "country": {
         "buckets": [
            {
               "key": "RU",
               "doc_count": 31970816,
               "cents": {
                  "count": 7310,
                  "min": 8,
                  "max": 169800,
                  "avg": 514.1964432284542,
                  "sum": 3758776,
                  "sum_of_squares": 60978796462,
                  "variance": 8077434.639111836,
                  "std_deviation": 2842.0827994820693
               }
            }
        ]
    }
}
```

Maybe additional boolean parameter could be introduced for `extended_stats` and `avg` aggregations, like `assume_zeroes`?

cc @uboness

**Comment by jpountz** [comment]
Closed through https://github.com/elastic/elasticsearch/pull/11042. Most aggs now have a `missing` option that allows to configure the value to consider when a document has no values.
