### ISSUE TITLE
SmokeTestWatcherTestSuiteIT.testMonitorClusterHealth failures on master

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#52995]
Similar to https://github.com/elastic/elasticsearch/issues/32299
Happened ~3 times last month.
Doesn't reproduce locally.

Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/3982/console
Build Scans https://gradle-enterprise.elastic.co/s/gtv35dhpev3ou

**Comment by martijnvg** [comment]
Thanks for triaging @przemekwitek. This test failure is being tracked here: #52453
The watcher stats api sometimes doesn't report the correct number of watches.
This happened in several tests. We are investigating it. I will close this issue for now.
