### ISSUE TITLE
When I using the "normalizer" seting under the "fields" setting is not work

### ISSUE THREAD

**Issue by boat320** [elastic/elasticsearch#52996]
elasticsearch 6.7
jdk1.8
my problem is when I using the "normalizer" seting under the "fields" setting is not work.
this is my setting:

######It's work########
{
      "settings": {
    "analysis": {
      "char_filter": {
        "quote": {
          "type": "pattern_replace",
          "pattern": "\\?.*",
          "replacement": ""
        }
      },
      "normalizer": {
        "my_normalizer": {
          "type": "custom",
          "char_filter": ["quote"]
        }
      }
    }
  },
"mappings": {
    "doc": {
      "properties": {
        "request": {
          "type" : "keyword",
          "normalizer":"my_normalizer",
          "fields" : {
           "text":{
            "type": "text"
           }
          }
        }
      }
    }
  }
}
###########

##########It's not work#########
{
      "settings": {
    "analysis": {
      "char_filter": {
        "quote": {
          "type": "pattern_replace",
          "pattern": "\\?.*",
          "replacement": ""
        }
      },
      "normalizer": {
        "my_normalizer": {
          "type": "custom",
          "char_filter": ["quote"]
        }
      }
    }
  },
"mappings": {
    "doc": {
      "properties": {
        "request": {
          "type" : "text",
          "fields" : {
           "keyword":{
            "type": "keyword",
            "normalizer":"my_normalizer"
           }
          }
        }
      }
    }
  }
}
########################

You cat see different in this commend

POST huanghui-analyzer/doc
{
    "request": "/partner/OrderQuery.actio?111"
}
POST huanghui-analyzer/doc
{
    "request": "/partner/OrderQuery.actio?222"
}
POST huanghui-analyzer/doc
{
    "request": "/partner/OrderQuery.actio?333"
}

When use the first mapping:
GET huanghui-analyzer/_search
{
  "size": 0, 
    "aggs" : {
        "genres" : {
            "terms" : { "field" : "request" } 
        }
    }
}

When use the last mapping:
GET huanghui-analyzer/_search
{
  "size": 0, 
    "aggs" : {
        "genres" : {
            "terms" : { "field" : "request.keyword" } 
        }
    }
}

**Comment by markharwood** [comment]
Thanks for reporting. To take this further can you:
1) Use the formatting tools to indent your JSON so that it is readable
2) Describe further why "it doesn't work":
   a) Does it return an error - can you share the result if so?
   b) Does it return OK but with not what you expect? Can you share what you expected and what you got?

**Comment by boat320** [comment]
Thank you .I have worked out the problem. The reason of my problem is cause by my mistake

**Comment by markharwood** [comment]
OK, thanks. Closing
