### ISSUE TITLE
Support for message attributes when sending alerts via AWS SNS to enable filtering

### ISSUE THREAD

**Issue by fretboarder** [elastic/elasticsearch#52993]
When using the Alerting feature for Elasticsearch via AWS SNS it would be very helpful to have the ability to specify "Message Attributes" to allow for message filtering on a single SNS topic. In order for that to work there would have to be a way to set "message attributes" (see https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html).

Currently the only way to selectively propagate alerts to different destinations is to used dedicated SNS topics. This can get very taxing if there are a lot of different subscribers for different types of alerts.

**Comment by jeremynelsonxinja** [comment]
Having attributes would also allow downstream systems, such as OpsGenie, to filter alerts

**Comment by jrykowski-huron** [comment]
+1

That feature is a large gap with Alerting.   This needs prioritized!   The work arounds are less than elegant and introduce administrative headaches.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
