### ISSUE TITLE
Handling index templates with multiple mapping types

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#53018]
It has been impossible to add a new index template with multiple mapping types since version 6.0, and creating an index that matches an index template containing multiple mapping types has failed with an error since 7.0.  However, because index templates are preserved over rolling upgrades, it is still possible to have a cluster state that contains such a template.  In 8.0, with types being removed entirely, it will not be possible to preserve these.

Since #50982 we have emitted warnings on startup when a node finds an index template with multiple mappings.  A node running elasticsearch 8.0 or higher should refuse to join a cluster that contains one of these templates.

**Comment by alisonelizabeth** [comment]
If possible, could we add a deprecation message around this to the deprecation info API ([related code](https://github.com/elastic/kibana/blob/master/x-pack/plugins/upgrade_assistant/server/lib/reindexing/reindex_service.ts#L293))? That way, we could easily surface the message to users in Upgrade Assistant.

**Comment by romseygeek** [comment]
This is handled by a deprecation check, added in #72540
