### ISSUE TITLE
QL: Add support for constant_keyword field type

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#53016]
`constant_keyword` just landed in master, being a specialized type of keyword - QL should add support for it

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/d6cd4ce7849ba215407c8c5fa815c9b373fb8480
7.x (7.7.0): https://github.com/elastic/elasticsearch/commit/91ca9c5c33a6f017fe1f51438117d9147bc12a25
