### ISSUE TITLE
No way to specify auto-slice in an AbstractBulkByScrollRequest

### ISSUE THREAD

**Issue by tc027** [elastic/elasticsearch#53044]
Elasticsearch version: 7.6.0

JVM version:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

OS version: Windows 10

**Description of the problem including expected versus actual behavior**:
There is no way to specify auto-slice in an AbstractBulkByScrollRequest. AbstractBulkByScrollRequest.setSlices only takes an int but AbstractBaseReindexRestHandler.parseSlices checks for an 'auto' string, which is impossible provide via the Java High Level REST Client. Simply providing '0' instead does not work either as this causes parseSlices to throw an exception.

```
public static final int AUTO_SLICES = 0;
public static final String AUTO_SLICES_VALUE = "auto";

public Self setSlices(int slices) {
        if (slices < 0) {
            throw new IllegalArgumentException("[slices] must be at least 0 but was [" + slices + "]");
        }
        this.slices = slices;
        return self();
}
```

```
private static Integer parseSlices(RestRequest request) {
        String slicesString = request.param("slices");
        if (slicesString == null) {
            return null;
        }

        if (slicesString.equals(AbstractBulkByScrollRequest.AUTO_SLICES_VALUE)) {
            return AbstractBulkByScrollRequest.AUTO_SLICES;
        }

        int slices;
        try {
            slices = Integer.parseInt(slicesString);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                "[slices] must be a positive integer or the string \"auto\", but was [" + slicesString + "]", e);
        }

        if (slices < 1) {
            throw new IllegalArgumentException(
                "[slices] must be a positive integer or the string \"auto\", but was [" + slicesString + "]");
        }

        return slices;
}
```

**Steps to reproduce**:

```
UpdateByQueryRequest request = new UpdateByQueryRequest(index)
request.setSlices("auto")// does not work due to being string
```

```
UpdateByQueryRequest request = new UpdateByQueryRequest(index)
request.setSlices(0)// does not work due to being less than 1
```

**Comment by cbuescher** [comment]
Hi,

thanks for raising the issue. I would like to clarify if all your above observations are based on trying to send the request using the HLRC.

> UpdateByQueryRequest request = new UpdateByQueryRequest(index)
> request.setSlices(0)// does not work due to being less than 1

I think the problem here is that we provide a way to set the '0' value representing "auto" on the request itself, but we cannot pass this through the Rest layer. I think we need to be more lenient in the above mentioned "parse" method.

**Comment by cbuescher** [comment]
@tc027 in case my assumption mentioned above is true, I opened a PR that should adress the High Level Rest Client behaviour when translating this parameter.

**Comment by tc027** [comment]
> Hi,
> 
> thanks for raising the issue. I would like to clarify if all your above observations are based on trying to send the request using the HLRC.
> 
> > UpdateByQueryRequest request = new UpdateByQueryRequest(index)
> > request.setSlices(0)// does not work due to being less than 1
> 
> I think the problem here is that we provide a way to set the '0' value representing "auto" on the request itself, but we cannot pass this through the Rest layer. I think we need to be more lenient in the above mentioned "parse" method.

That is indeed the case, yes.

> @tc027 in case my assumption mentioned above is true, I opened a PR that should adress the High Level Rest Client behaviour when translating this parameter.

Thank you for implementing a fix so promptly.

**Comment by jchharris** [comment]
Any chance of getting this into a 7.6.x patch releases?

**Comment by cbuescher** [comment]
> Any chance of getting this into a 7.6.x patch releases?

Should be in 7.6.2

**Comment by Camalot9** [comment]
It would be really nice to have this feature in `ReindexRequest` as well. The documentation says `slices` can be set to `auto` but it's required to be a positive integer.
