### ISSUE TITLE
[CI] Rolling upgrade tests failing to start after upgrading node

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#53042]
We have a bunch of BWC tests failing in `master`:

```
Execution failed for task ':x-pack:qa:rolling-upgrade:v7.7.0#oneThirdUpgradedTest'.
> `cluster{:x-pack:qa:rolling-upgrade:v7.7.0}` failed to wait for cluster health yellow after 40 SECONDS
  IO error while waiting cluster
    503 Service Unavailable
  > IO error while waiting cluster
    > 503 Service Unavailable
```

The problem here is the cluster failing to come up after upgrading one of the cluster nodes from `7.7.0` (i.e. latest from `7.x` branch) to `8.0.0` (i.e. `master`).

The logs are littered with logs of SSL/crypto type errors, as well as this one:

```
»  Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.ClusterState$Custom][]
»  	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:113) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:728) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.<init>(ValidateJoinRequest.java:33) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:175) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:118) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

It's not clear to me (since these are all `info` and `warn` level logs) which is stopping the cluster from actually being formed. My guess is the "failed to join" errors are the problem, given the whole point of these tests is to ensure that an 8.0 node can talk to a 7.7 cluster.

https://gradle-enterprise.elastic.co/s/6asy246orjjj6/console-log?task=:x-pack:qa:rolling-upgrade:v7.7.0%23oneThirdUpgradedTest

There have been over 20 of these failures today across all CI builds (pull requests, feature branches, etc). It didn't reproduce locally more me however, and I'm quite surprised we haven't seen an intake build fail with this yet.

**Comment by ywelsch** [comment]
Quick grep at recently merged code shows https://github.com/elastic/elasticsearch/pull/53012 as possible cause. @hendrikmuhs can you check this one?

**Comment by hendrikmuhs** [comment]
> Quick grep at recently merged code shows #53012 as possible cause. @hendrikmuhs can you check this one?

I will have a look, however I merged the PR you mention 2 hours ago, the bug report is 8 hours ago.

BWC testing has been disabled by me until I re-enabled them 2 hours ago, its strange that the rolling upgrade still run.

**Comment by hendrikmuhs** [comment]
I think this is due to transform serialization changes introduced in https://github.com/elastic/elasticsearch/pull/52998

The changes have been backported and BWC has been re-enabled with #53012 

I wonder about this failure, BWC has been disabled, the log contains:

```
01:51:05 ========================= WARNING =========================
01:51:05          Backwards compatibility tests are disabled!
01:51:05 See https://github.com/elastic/elasticsearch/pull/52998
01:51:05 ===========================================================
```

Is it expected that the rolling upgrade test, which is about BWC, gets executed? I think this test should be skipped if BWC tests are disabled.

Infra?

**Comment by mark-vieira** [comment]
> Is it expected that the rolling upgrade test, which is about BWC, gets executed? I think this test should be skipped if BWC tests are disabled.

Good catch. Nope, that definitely should not be the case. I'll investigate this.

**Comment by mark-vieira** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/53079 to address the problem of some BWC tests still executing when BWC testing is disabled.

**Comment by hendrikmuhs** [comment]
Thanks @mark-vieira !

Closing this issue as tests are back ok again, after re-enabling in #53012
