### ISSUE TITLE
ES 7.6 Disk shows full but isn't

### ISSUE THREAD

**Issue by sgreszcz** [elastic/elasticsearch#53052]
**Elasticsearch version** (`bin/elasticsearch --version`):  Elasticsearch 7.6 in Elastic.co Elastic Cloud.

**Description of the problem including expected versus actual behavior**:

Elastic Cloud upgraded to 7.6.  Was running fine with hot node, and rolling 50GB indexes from filebeat, metricbeat, and logstash to warm node.  After a week or so no more indexing and single sign on broke as disk showing full.  However when logged into Elastic.co console showed only 14% disk as did Elastic API commands via Kibana.

Elastic sales engineer confirmed issue, but I haven't been able to find it in Github so raising this issue now.

**Steps to reproduce**:

Upgrade to 7.6 on Elastic.co
Send data using beats, logstash
Disk shows full even though it isn't.

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
Hi @sgreszcz, sorry to hear that you are having trouble. Unfortunately there's not enough information here for us to take any action; also, issues on this repository are for tracking development work rather than support cases. Please raise this issue through your support or sales contacts to get the proper attention.

**Comment by sgreszcz** [comment]
> Hi @sgreszcz, sorry to hear that you are having trouble. Unfortunately there's not enough information here for us to take any action; also, issues on this repository are for tracking development work rather than support cases. Please raise this issue through your support or sales contacts to get the proper attention.

OK, thanks fo that, however it was a confirmed bug by the support team.  Also it is difficult to put logs or config information here without significant cleaning of the data.

Anyway it is a problematic bug (blocks the loading of new data) so hope it gets fixed for 7.6.x
