### ISSUE TITLE
Docs on custom realm still point to old Shield sample repo

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#53088]
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/custom-realms.html

Says:
> Sample code that illustrates the structure and implementation of a custom realm is provided in the [custom-realm-example](https://github.com/elastic/shield-custom-realm-example) repository on GitHub. You can use this code as a starting point for creating your own realm.

That repo is no longer maintained, and it points people to
- https://github.com/elastic/elasticsearch/tree/master/x-pack/qa/security-example-spi-extension

We should update the ES docs to point to the correct branch (the same branch as the docs are for) in that repo instead.

**Comment by lcawl** [comment]
There's also a typo on that page ("matchesto")
