### ISSUE TITLE
high level REST client does not have a way to set max_concurrent_shard_requests

### ISSUE THREAD

**Issue by bwf93** [elastic/elasticsearch#53086]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.0

**Plugins installed**: [custom plugin]

**JVM version** (`java -version`): 11.0.6

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**: MacOS 10.15.1

**Steps to reproduce**:

The MultiSearchRequest object in the high-level REST client does not have any way to set the max_concurrent_shard_requests parameter.  I see a method 
maxConcurrentSearchRequests(int maxConcurrentSearchRequests)
that can be used to set the parameter max_concurrent_searches but I do not see a method to set max_concurrent_shard_requests.

**Comment by biuabiu** [comment]
hi @jrodewig ,
I also have the same question,Can you see this issue
