### ISSUE TITLE
How does elasticsearch do storage and computation separation? In other words, use shared storage instead of local hard disk？

### ISSUE THREAD

**Issue by awzhgw** [elastic/elasticsearch#53091]
How does elasticsearch do storage and computation separation? In other words, use shared storage instead of local hard disk

https://elasticsearch.cn/article/13650

Can this article achieve 80% resource savings?

**Comment by awzhgw** [comment]
https://elasticsearch.cn/article/13650  it used https://github.com/chubaofs/chubaofs 

To do shared storage instead of local disk. Because 1 copy is used, 66% of the CPU and memory are saved. Because 80% of the time, the local IO of the es is idle. After using chubaofs, all the resources are shared, which increases the disk resource utilization rate. Come, almost 80% of the hardware savings

**Comment by ansjsun** [comment]
hi @awelzel , it is a good idea, but I think  this method may not perform well

**Comment by zhuhyc** [comment]
Yes，the separation of computing and storage does bring many benefits to elasticsearch，which can significantly reduce Total Cost of Ownership. If you want to save more money, you can try this solution.

**Comment by jasontedor** [comment]
Sorry, but this is basically self-promotion which is not an acceptable use of our GitHub repository, we reserve it for bug reports and feature requests.
