### ISSUE TITLE
How does Elasticsearch calculates AVG value ?

### ISSUE THREAD

**Issue by longvd89** [elastic/elasticsearch#53093]
if i have 10 documents and AVG aggregation: { "aggs" : { "avg_grade" : { "avg" : { "field" : "grade" } } } }
but 1 document have grade = undefined (or not exist field grade in document). I have question : the value of AVG is is calculated on 10 documents or 9 documents (have value of grade )

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
