### ISSUE TITLE
[CI] Builds for 6.8 branch frequently fail to download dependencies

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#53121]
Our 6.8 builds are particularly vulnerable to failures due to dependency downloads due to a limitation in how we seed our CI image dependency caches. Essentially, we only seed the cache with dependencies for `master` and it's BWC branches. Since `master` has no backwards compatibility with `6.8` our caching script (which lives in `master`) doesn't download 6.8 dependencies. We have a couple of options here:

1. Set up a local proxy for external repos. We've tried this before but we ended up crushing Artifactory with load. There's an existing infra issue to address this but it might take time to get traction there: https://github.com/elastic/infra/issues/14421
2. Get our `packer_cache.sh` script to also run 6.8 builds.

**Comment by mark-vieira** [comment]
@breskeby I'm assigning this to you. This issue is becoming quite the thorn so we should address it. Failing to download dependencies is the [primary reason why 6.8 builds fail](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=non_verification&search.relativeStartTime=P28D&search.tags=CI&search.tags=6.8&search.timeZoneId=America/Los_Angeles) (other than tests). This also affects 7.x build, since they have to build 6.8 from source for BWC testing.

We should investigate solution (2) mentioned in the description. Going the full local artifactory route is a bridge too far right now and is unlikely to be better since we don't have a local HA deployment.

This should be relatively low hanging fruit and a decent bang for the buck.

**Comment by breskeby** [comment]
I'll look into this

**Comment by mark-vieira** [comment]
This should be sorted out by #65510.
