### ISSUE TITLE
Improve error message for calls against a null def type

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#53129]
The error message for `def x = null; x.toString();` is similar to the following:
```
Caused by: java.lang.NullPointerException
	at org.elasticsearch.painless.DefBootstrap$PIC.fallback(DefBootstrap.java:206)
	at org.elasticsearch.painless.PainlessScript$Script.execute(def x = null; x.toString():16)
```

This is a poor user experience as it doesn't explicitly say that we found a null def when trying to make a call. Instead they see a hard to reason about stack trace. We should add a null check in our PIC and give a better exception here.

**Comment by peejmonty** [comment]
I can take a stab at this unless somebody else has taken it.

**Comment by shay123g** [comment]
added a null check that described the error in user-friendly way

**Comment by sharmasiddarth** [comment]
Hi. Is this issue open ?

**Comment by jdconrad** [comment]
Removing "good first issue" as this is more complicated than I originally thought.
