### ISSUE TITLE
Composite aggregation ignores value script in terms source

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#53135]
Using a terms source in a composite aggregation is documented to fully support [scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_terms) in the same way as terms aggregation:

```
The terms value source is equivalent to a simple terms aggregation. The values are extracted from a field or a script exactly like the terms aggregation.
```

However, [value script](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_value_script_9) does not work as expected but is silently ignored.

## Workaround

Instead of using `_value` use `doc[{field_name}]` 

## Reproduction

The described behavior can be reproduced using the kibana sample data logs:

```
GET kibana_sample_data_logs/_search
{
  "size": 0,
  "aggs": {
    "my_composite_agg": {
      "composite": {
        "sources": [
          {
            "agent": {
              "terms": {
                "field": "agent.keyword",
                "script": {
                  "source": "'agent: ' + _value"}
              }
            }
          }
        ]
      }
    }
  }
}
```

returns e.g.

```
      "buckets" : [
        {
          "key" : {
            "agent" : "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)"
          },
          "doc_count" : 4010
        },

```

while the expected output is:

```
      "buckets" : [
        {
          "key" : {
            "agent" : "agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)"
          },
          "doc_count" : 4010
        },
```

I am not sure if this is really a bug or a technical limitation. If its a limitation the documentation should not claim full support and the search request using a value script should error.

**Comment by hendrikmuhs** [comment]
I debugged this to learn a bit about the implementation of aggs. #53232 contains what I found out and also has a quick-fix for it.

**Comment by bczifra** [comment]
@hendrikmuhs I've run into field+script issues before, such as https://github.com/elastic/elasticsearch/pull/43390. Pulling the entire content into the script will work reliably:
```
GET kibana_sample_data_logs/_search
{
  "size": 0,
  "aggs": {
    "my_composite_agg": {
      "composite": {
        "sources": [
          {
            "agent": {
              "terms": {
                "script": {
                  "source": "'agent: ' + doc['agent.keyword']"}
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by hendrikmuhs** [comment]
@bczifra Thanks. yes using doc works, I should have mentioned this for readers of the issue. I will update the entry post.

**Comment by wchaparro** [comment]
closing as not planned.
