### ISSUE TITLE
Deduplicate deprecation warnings from LoggingDeprecationHandler

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#53137]
A [user on the forums](https://discuss.elastic.co/t/turn-off-es-deprecation-logs-dynamically/221948) reports that they are seeing GBs of deprecation logs of the following forms:

```
[2020-03-02T22:21:15,295][WARN ][o.e.d.c.ParseField       ] Deprecated field [_version] used, expected [version] instead
[2020-03-02T22:21:15,295][WARN ][o.e.d.c.ParseField       ] Deprecated field [_version_type] used, expected [version_type] instead
```

It looks like these are coming from here:

https://github.com/elastic/elasticsearch/blob/e1fdd00420b226b33adba3675ac0ff5d6daf954c/server/src/main/java/org/elasticsearch/common/xcontent/LoggingDeprecationHandler.java#L51-L59

Could we use `deprecatedAndMaybeLog` to deduplicate these messages instead of overwhelming users like this?

**Comment by rjernst** [comment]
> Could we use deprecatedAndMaybeLog

Yes, we should be using that method. I wonder if we should remove or change the deprecated method altogether, such that we can't fall into this trap again. I can't think of any cases where we *don't* want to deduplicate?

**Comment by pugnascotia** [comment]
I think we should always deduplicate. We'd have to change the existing deprecated calls to supply a key value, in order to support deduplication, but that would also be a good thing for indexing and reporting on deprecation logs. I could take that on.

**Comment by musabdogan** [comment]
Use this: 

```
PUT /_cluster/settings
{
  "persistent": {
    "logger.org.elasticsearch.deprecation": "OFF"
  }
}
```
https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html

**Comment by DaveCTurner** [comment]
Deprecation logging is important, we strongly recommend not recommend disabling it. I'm marking this comment as off-topic.
