### ISSUE TITLE
InternalEngineTests are unstable

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#53195]
We've seen a number of InternalEngineTests failures today on CI, many of them reproduce locally with some light effort:

- [ ] https://github.com/elastic/elasticsearch/issues/53190
- [ ] https://github.com/elastic/elasticsearch/issues/53186
- [ ] https://github.com/elastic/elasticsearch/issues/53185
- [ ] https://github.com/elastic/elasticsearch/issues/53182
- [ ] https://github.com/elastic/elasticsearch/issues/53193 

@dnhatn seems to think they are all related to https://issues.apache.org/jira/browse/LUCENE-8962 which makes sense considering we recently bumped our lucene snapshot. This issue is meant to encapsulate these separate failures all together in one place.

**Comment by dnhatn** [comment]
These tests can fail with the [MockRandomMergePolicy](https://github.com/apache/lucene-solr/blob/9cfdf17b2895866877668002d443277a46cd04e8/lucene/test-framework/src/java/org/apache/lucene/index/MockRandomMergePolicy.java#L132). Only this merge policy returns non-null for `findFullFlushMerges` which was introduced recently in Lucene.

**Comment by dnhatn** [comment]
This is a Lucene issue.

**Comment by DaveCTurner** [comment]
@dnhatn I am still seeing occasional failures that were linked to this closed issue, e.g. https://gradle-enterprise.elastic.co/s/eh6lnrbtyc2y6 in which `GatewayMetaStatePersistedStateTests#testDataOnlyNodePersistence` failed. Is it really closed or is it waiting for another Lucene update?

**Comment by dnhatn** [comment]
@DaveCTurner The engine tests stopped failing after [LUCENE-8962](https://issues.apache.org/jira/browse/LUCENE-8962) was reverted. I think `testDataOnlyNodePersistence` failed for a different reason.
