### ISSUE TITLE
7.6.0 GeoIP Processor results do not match specified DB

### ISSUE THREAD

**Issue by danielharada** [elastic/elasticsearch#53206]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.6.0, Build: default/tar/7f634e9f44834fbc12724506cc1da681b0c3b1e3/2020-02-06T00:09:00.449973Z, JVM: 13.0.2

**Plugins installed**: []

**JVM version** (`java -version`):
ava version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
mac OS 10.14.6

**Description of the problem including expected versus actual behavior**:
The GeoIP pipeline processor is not giving results that match our expected output, and results do not change when a DB with known good results is supplied.

IP address giving bad results is `50.201.67.67`.  We expect this IP to originate in PA, and Elastic Cloud clusters running <=7.5.2 return this.  Cloud clusters on 7.6.0 and 7.6.1 return a value in CA.  Currently (March 5th 2020) the GeoLite2-City CSV shows these values for the `50.201.67.XXX` block:
```
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,
is_anonymous_proxy,is_satellite_provider,postal_code,latitude,longitude,accuracy
_radius
50.201.67.0/27,5393015,6252001,,0,0,95051,37.3417,-121.9753,1000
50.201.67.32/28,5393015,6252001,,0,0,95051,37.3417,-121.9753,1000
50.201.67.48/28,5399020,6252001,,0,0,95219,38.0100,-121.3698,1000
50.201.67.64/26,5207728,6252001,,0,0,19607,40.2960,-75.9894,1000
50.201.67.128/25,5393015,6252001,,0,0,95051,37.3417,-121.9753,1000
```
The entries that have (latitude, longitude) coordinates around (37, -121) have a CA location.  The entry around (40, -76) is a PA location.  Our IP in question should fall into the block giving a PA location.

On 7.6.0 / 7.6.1, supplying our own current download of the GeoLite2-City.mmdb database file in the pipeline with the "database-file" option does not change the results from the bad CA value.

When trying to load my known good DB, I did get good results in one query from both the default DB along with my supplied DB, but I have not been able to reproduce those results.  No change in queries used, the only change was that my DB had been installed at both elasticsearch/config/ingest-geoip/my-GeoLite2-City.mmdb and elasticsearch/module/ingest-geoip/my-GeoLite2-City.mmdb.  After deleting these and restarting ES, I got the CA results again.  Reinstalling my DB in both places did not change future results after restarts, so I am unsure if results are inconsistent or if there was something else that changed that I did not notice.

**Steps to reproduce**:
1. Setup an ES cluster running 7.6.0 or 7.6.1
2. Download a copy of MaxMind's GeoLite2-City.mmdb, rename it to ensure no collisions with the default DB
3. Verify what results are expected from the DB for 50.201.67.67 (I did this by checking the CSV version of the DB)
4.  Copy the renamed DB into $ES_CONFIG/ingest-geoip
5.  Run the following simulated pipeline to see the default GeoIP results for 50.201.67.67:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "Lookup geolocation",
    "processors": [
      {
        "geoip": {
          "field": "ip",
          "target_field": "default_geo",
          "properties": [
            "ip",
            "country_name",
            "continent_name",
            "region_iso_code",
            "region_name",
            "city_name",
            "timezone",
            "location"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "ip": "50.201.67.67"
      }
    }
  ]
}
```
Expected results:  
`region_iso_code: US-PA`, `lat: ~40`, `lon: ~-76`
Actual Results:
On 7.5.2 cluster:  `region_iso_code: US-PA`, `lat: 40.204`, `lon: -75.5381`
On 7.6.0 cluster:  `region_iso_code: US-CA`, `lat: 36.9356`, `lon: -121.7767`

6.  Run the following simulated pipeline to see the default DB results and our supplied DB results side by side:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "Lookup geolocation",
    "processors": [
      {
        "geoip": {
          "field": "ip",
          "target_field": "default_geo",
          "properties": [
            "ip",
            "country_name",
            "continent_name",
            "region_iso_code",
            "region_name",
            "city_name",
            "timezone",
            "location"
          ]
        }
      },
      {
        "geoip": {
          "database_file": "my-GeoLite2-City.mmdb",
          "field": "ip",
          "target_field": "new_db_geo",
          "properties": [
            "ip",
            "country_name",
            "continent_name",
            "region_iso_code",
            "region_name",
            "city_name",
            "timezone",
            "location"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "ip": "50.201.67.67"
      }
    }
  ]
}
```
Expected results:
Assuming the CA result from above is actually expected for the default geoIP DB on 7.6.0 - 
default_geo:  `region_iso_code: US-CA`, `lat: 36.9356`, `lon: -121.7767`
new_db_geo:  `region_iso_code: US-PA`, `lat: 40.2960`, `lon: -75.9894`

Actual result:
default_geo:  `region_iso_code: US-CA`, `lat: 36.9356`, `lon: -121.7767`
new_db_geo:  `region_iso_code: US-CA`, `lat: 36.9356`, `lon: -121.7767`

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
