### ISSUE TITLE
File conflicts on install of elasticsearch 7.6.1 rpm

### ISSUE THREAD

**Issue by vb-dave** [elastic/elasticsearch#53201]
On a Centos 7.7 server running Elasticsearch 7.6.0 installed from RPM via Chef cookbook https://github.com/elastic/cookbook-elasticsearch/, when we try and install 7.6.1 the package is not being installed.

When I try and install elasticsearch-7.6.1-x86_64.rpm manually on the command line I get the following error:
`$ rpm -ivh elasticsearch-7.6.1-x86_64.rpm
Preparing...                          ################################# [100%]
	file /usr/lib/systemd/system/elasticsearch.service from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/bin/elasticsearch-env-from-file from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/aggs-matrix-stats/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/analysis-common/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/flattened/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/frozen-indices/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/ingest-common/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/ingest-geoip/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/ingest-user-agent/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/lang-expression/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/lang-mustache/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/lang-painless/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/mapper-extras/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/parent-join/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/percolator/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/rank-eval/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/reindex/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/repository-url/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/search-business-rules/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/spatial/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/systemd/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/transform/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/transport-netty4/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/vectors/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-analytics/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ccr/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-core/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-deprecation/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-enrich/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-graph/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ilm/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-logstash/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-monitoring/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-rollup/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-security/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-sql/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-voting-only-node/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-watcher/plugin-descriptor.properties from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/autoconfig from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/autodetect from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/categorize from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/data_frame_analyzer from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64
	file /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/normalize from install of elasticsearch-0:7.6.1-1.x86_64 conflicts with file from package elasticsearch-0:7.6.0-1.x86_64`

If I uninstall the existing 7.6.0 rpm first, then run Chef again the 7.6.1 rpm installs without issue. However, we've never had to do this in the upgrade path before. Am I missing something?

**Comment by rjernst** [comment]
> When I try and install elasticsearch-7.6.1-x86_64.rpm manually

Upgrading a package with `rpm` requires using the `-U` flag as you found. Why were you installing manually, not continuing with using Chef? Is there a different error you receive when upgrading with Chef?

**Comment by vb-dave** [comment]
Unfortunately with Chef the install resource showed completing successfully with version 7.6.1, but didn't actually upgrade the rpm to the latest version (confirmed in logs/UI after Chef run had finished, as well as with an `rpm -qa`). I haven't seen this behavior before but it was easily reproduced in all our environments.

I didn't get to the point of running it with a debug log level to see if it was just ignoring errors or what, but I'll try to find time to do this.

**Comment by danielmitterdorfer** [comment]
No further feedback received. @vb-dave  if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
