### ISSUE TITLE
expand_wildcards spec definitions mismatch yaml test usage

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#53212]
The `expand_wildcards` param defined in REST API specs is defined as an `enum` type with options `:[
"open", "closed", "none", "all"]`. An example is `cluster.state.json`:

https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json#L95-L105

An `enum` type is defined as a set of constants where a single value is provided, [according to the REST API spec type definitions](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec#type-definition). There are some YAML tests however that specify `expand_wildcards` as an  array of values, containing either a single or multiple values. For example:

https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/30_expand_wildcards.yml#L36

https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/30_expand_wildcards.yml#L45

https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/30_expand_wildcards.yml#L54

It seems that one of the following actions should be considered to resolve this discrepancy:

1. If `expand_wildcards` is intended to take multiple values, then the `type` should be changed to `"list"`. In other cases in the REST API specs where a list of values can be specified, a `"list"` type is used in conjunction with a collection of `"options"`. For example, `metric` in `cluster.reroute`:

https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json#L31-L43

There may be merit in having a _separate_ discussion in defining a `"flags"" true` or `"multiple": true` property for enums where multiple values can be specified, and keeping the type definition of `"list"` for a collection of arbitrary values.

2. If `expand_wildcards` is not intended to take multiple values, the YAML tests should be updated to specify a single value. Where `[ "open", "closed" ]` is used, `"all"` should be used

**Comment by russcam** [comment]
Another example, which specifies a comma-separated string to denote multiple values: https://github.com/elastic/elasticsearch/blob/0d38626d8e6e9e2620a7a446b617a2ac42852461/rest-api-spec/src/main/resources/rest-api-spec/test/indices.get/10_basic.yml#L156

**Comment by martijnvg** [comment]
I think that `expand_wildcards` parameter's type in yaml spec should be a list (like `metric` in reroute api). Valid options are: `open`, `closed`, `hidden`, `none` and `all`.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
