### ISSUE TITLE
Aggregation with Filter 

### ISSUE THREAD

**Issue by soumilshah1995** [elastic/elasticsearch#53264]
Hello We are working on a project and we are stuck at this if someone can help that would be really Great 
`GET xyxz/_search
{
            "size": 0,
            "aggs": {
                "company": {
                    "terms": {
                        "field": "skills.name.keyword",
                        "size": 10
                    }
                }
            },
            "query": {
                "bool": {
                    "must": [],
                    "filter": [],
                    "should": [
                        {
                            "wildcard": {
                                "skills.name": {
                                    "value": "jav*"
                                }
                            }
                        }
                    ],
                    "must_not": []
                }
            }
        }`

The problem with this query is that i do get the result java python c++ but i want to get only those aggreation with starts with jav ie what i type 

we are trying to implement autocomplete feature please any help would be really appreciated

**Comment by martijnvg** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
