### ISSUE TITLE
property totalHits is always 0 on BoolQuery Search response

### ISSUE THREAD

**Issue by durancu** [elastic/elasticsearch#53267]
**Describe the feature**: totalHits property always returns 0, but hits contains items

**Elasticsearch version** (`bin/elasticsearch --version`): 7.6

**Plugins installed**: []

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): MacOS

**Description of the problem including expected versus actual behavior**:
I am using Java REST Client to implement a microservice that integrates to Elasticsearch (via AWS).
When I am debugging, I see totalHits is coming always as zero (0),
If I run same query in Kibana, it returns the right value of totalHits.

I create a boolQuery, with several must queries inside it. For the example I am debugging, I have a BoolQueryBuilder object, and the generated query is:

```
{
  "bool" : {
    "must" : [
      {
        "match_phrase" : {
          "wellSiteName.keyword" : {
            "query" : "XXXXXXX 501H, 502H",
            "slop" : 0,
            "zero_terms_query" : "NONE",
            "boost" : 1.0
          }
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
```

This is my request object toString:

```
SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=null, source={"query":{"bool":{"must":[{"match_phrase":{"wellSiteName.keyword":{"query":"WINNEBAGO 30 STATE COM 501H, 502H","slop":0,"zero_terms_query":"NONE","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}}}
```

This is the response I get:

<img width="1074" alt="Screen Shot 2020-03-09 at 1 19 44 AM" src="https://user-images.githubusercontent.com/858387/76187763-37fbc880-61a4-11ea-860a-055a1bb47ed9.png">

As you can see, despites there are many hits, `totalHits` property is 0

However, if I run same query in Kibana, I get a number of totalHits matching that query, that is not 0

![Screen Shot 2020-03-09 at 1 22 23 AM](https://user-images.githubusercontent.com/858387/76187862-801aeb00-61a4-11ea-8d99-86c55e038141.png)

**Steps to reproduce**:

1- Create a BoolQueryBuilder object
2- Add a must query to the object, using matchPhraseQuery, on a keyword column
3- Create a SearchRequest object
4- Create a SearchSourceBuilder object
5- Add BoolQueryBuilder object to SearchSourceBuilder object as query
6- Set SearchSourceBuilder object as source of SearchRequest.
7- Call Elasticsearch client using SearchRequest object and RequestOptions.DEFAULT

**Comment by martijnvg** [comment]
Thanks for opening this issue @durancu. Maybe the default (10000) for `track_total_hits` gets changed from interacting via the hlrc. 

If you add: `searchSourceBuilder .trackTotalHitsUpTo(10000);` does total hits get returned via hlrc?

I'm not sure yet why you always get zero total hits via hlrc if you don't alter the search source build's track total hits.

**Comment by durancu** [comment]
Hi @martijnvg, thanks for your quick response
I can't call that method. Here is what intelliJ shows on autocomplete:

![Screen Shot 2020-03-09 at 4 53 32 AM](https://user-images.githubusercontent.com/858387/76202501-eca4e280-61c2-11ea-953f-26f374ea290b.png)

**Comment by martijnvg** [comment]
That is odd. What version of hlrc are you using on the client side?

**Comment by durancu** [comment]
I am using 7.6

![Screen Shot 2020-03-09 at 5 10 19 AM](https://user-images.githubusercontent.com/858387/76203277-5a9dd980-61c4-11ea-9450-ba85eb990928.png)

**Comment by martijnvg** [comment]
This should be a public method: https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L584

**Comment by durancu** [comment]
I purged my local Maven repository, and reimport all dependencies. 
This is how my dependencies graph looks like:

![Screen Shot 2020-03-09 at 12 25 10 PM](https://user-images.githubusercontent.com/858387/76240571-7c698180-6201-11ea-8390-9944411297a5.png)

And noting in Maven plugin, in IntelliJ that elasticsearch high rest client uses REST client dependency from v. 6.4. Since I am using objects from client, like SearchSourceBuilder, it's referencing wrong one.

![Screen Shot 2020-03-09 at 12 23 31 PM](https://user-images.githubusercontent.com/858387/76240520-622fa380-6201-11ea-8b2b-c15e7ac99830.png)

**Comment by dadoonet** [comment]
Are you using spring boot by any chance ?

**Comment by durancu** [comment]
Yes, I am using Spring Boot. Sorry forgot to mention

**Comment by dadoonet** [comment]
When using springboot with 
elasticsearch, you need to be explicit with some transitive dependencies as SpringBoot declares a version 6.4... 

Basically you can put this in your `pom.xml`:

```
<properties>
  <elasticsearch.version>7.6.1<elasticsearch.version>
</properties>
```

See documentation here: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-customize-dependency-versions

**Comment by durancu** [comment]
Thanks @dadoonet for your reply. 
I applied that change but also add:
```
           <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>7.6.1</version>
            </dependency>
```

to <dependencyManagement> section, and it didn't work.

I am see this is something related to SpringBoot more than ElasticSearch. 
I understand they tie SpringBoot version to ElasticSearch version, and I would need to find a way to override it.
Do you have any idea about how to do it?

**Comment by dadoonet** [comment]
I'm just aware that spring data elasticsearch has a new beta version IIRC which is compatible with 7.x so may be you need to use that?

**Comment by durancu** [comment]
Solution was to override version of spring-boot dependencies (elasticsearch, elasticsearch-client):

1- Define property for elasticsearch version:
`
<properties>
   <elasticsearch.version>7.6.0</elasticsearch.version>
</properties>
`

2- Exclude autoconfigured dependencies from elasticsearch-rest-high-level-client
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>${elasticsearch.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.elasticsearch</groupId>
                    <artifactId>elasticsearch</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.elasticsearch.client</groupId>
                    <artifactId>elasticsearch-rest-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

3- Call elasticsearch dependencies by themselves, using same version:

  `<dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>${elasticsearch.version}</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>${elasticsearch.version}</version>
        </dependency>
`

This is a way to override the version, but need to be careful to prevent incompatibilities with forced dependency version.
This luckily worked for me to use Elasticsearch 7.6 in Springboot 2.1
