### ISSUE TITLE
CONF_FILE in /etc/sysconfig not used by startup script on RedHat

### ISSUE THREAD

**Issue by lehcim** [elastic/elasticsearch#5329]
I'm facing a issue with node default parameters in the system configuration file (/etc/sysconfig/elasticsearch) on a RedHat Linux installation : the 
definition of the node configuration file is ignored by the standard startup script.

Environment:
- Redhat Linux RHEL 6.2
- Elasticsearch 1.0.1 (elasticsearch-1.0.1-1.noarch.rpm)

### Problems:

1) custom config file defined in /etc/sysconfig is ignored

The file /etc/sysconfig/elasticsearch contains default parameters used by the startup script /etc/init.d/elasticsearch to intialize the node. The parameter CONF_FILE, as its name suggests, contains the name of the configuration file. By default, it is defined like this:
    
```
    # Elasticsearch configuration file (elasticsearch.yml)
    CONF_FILE=/etc/elasticsearch/elasticsearch.yml 
```

If this value is changed to another location, the node will start but the new configuration will be ignored.
   
2) relative config file in /etc/sysconfig prevents node startup
  
In file /etc/sysconfig/elasticsearch, another parameter named CONF_DIR defines the Elasticsearch configuration directory, where other config files like logging.yml will be found:
    
```
    # Elasticsearch conf directory
    CONF_DIR=/etc/elasticsearch
```

According to the CONF_FILE comment, it should be possible to give a relative file name (elasticsearch.yml), but it does not work, the node will not start using standard service command.

### How to reproduce:

0) prerequisites

- install elasticsearch-1.0.1-1.noarch.rpm on a RedHat/Centos system
- create a new configuration file called foobar.yml in /etc/elasticsearch with specific parameters, for example the cluster name:
    
    ```
    cluster.name: foobar
    ```
          
1) custom config file
      
- edit file /etc/sysconfig/elasticsearch and change the CONF_FILE value to the new configuration file:
    
    ``` 
    CONF_FILE=/etc/elasticsearch/foobar.yml
    ```
          
- start the server using the service command:
    
    ```
    service elasticsearch start
    ```
        
- check the cluster name using the REST API:
    
    ``` 
    curl http://localhost:9200/_nodes?pretty=true
    ```
         
- the cluster name is still the default "elasticsearch", new configuration file was not used.    

2) relative standard config file

- edit file /etc/sysconfig/elasticsearch and change the CONF_FILE value to a relative name of an existing file in the CONF_DIR directory:
    
    ```
    CONF_FILE=elasticsearch.yml
    ```
        
- start the server using the service command:
    
    ```
    service elasticsearch start
    ```
        
- the startup fails with exit code 6 (configuration file not found), however the file $CONF_DIR/$CONF_FILE exits !      

### Workaround:

In file /etc/sysconfig/elasticsearch, pass the config file in the Java options : 
  
```
    ES_JAVA_OPTS="-Des.config=/etc/elasticsearch/foobar.yml"
```
    
If the config argument is not absolute (foobar.yml), the file will be searched in the $CONF_DIR directory during Elasticsearch startup (Java code). But it's not very clean, because :
  
- you can't use CONF_FILE in JAVA_OPTS, because it's defined later in the sysconfig file
- you still need an absolute CONF_FILE, because it's existence is directly checked in the init.d script    
- you'll have to remember that CONF_FILE is not really used by the node...

### How to solve:

1) in /etc/init.d/elasticsearch, line 88, in the daemon launch command line, define the es.config property using the $CONF_FILE variable :
  
```
    daemon --user $ES_USER --pidfile $pidfile $exec -p $pidfile -d \
        -Des.default.path.home=$ES_HOME \
        -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR \
        -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR \
        -Des.config=$CONF_FILE
```
    
(maybe es.default.config would be better than es.config ?)
    
This way, the configuration specified in the sysconfig file is really used by the node (solves problem n°1).  
    
2) in /etc/init.d/elasticsearch, line 68, replace the current configuration file existence test :
  
```
    [ -f $CONF_FILE ] || exit 6        # line 68
```

by this one:

```
    [ -f $CONF_FILE ] || [ -f $CONF_DIR/$CONF_FILE ] || exit 6
```

This test reproduce better the one made in the Java code (first check for an absolute configuration file, then for a relative one in the configuration directory, then in the classpath, else fail). Now, the configuration file can be absolute or relative, it works without surprise (solves problem n°2).

What do you think ?

**Comment by piyushGoyal2** [comment]
+1

**Comment by clintongormley** [comment]
@tlrx is this still an issue?

**Comment by piyushGoyal2** [comment]
@clintongormley : I know this is not a place to ask question, but wanted to check on one thing since it's a little bit in relevance with this topic. What takes more precedence, the sysconfig file or the elasticsearch yml file if both have the same properties like

**Comment by clintongormley** [comment]
@piyushGoyal2 good question. i *think* the sysconfig file, as those values would get passed in as environment variables.

**Comment by piyushGoyal2** [comment]
Thanks @clintongormley . I just tried that as well. Sysconfig always take the precedence. Thanks once again for the reply. I guess, this should be published somewhere since many folks might have faced this confusion.

**Comment by brwe** [comment]
> edit file /etc/sysconfig/elasticsearch and change the CONF_FILE value to a relative name of an existing file in the CONF_DIR directory:

I think currently the CONF_FILE is supposed to be an absolute path, this is at least what the documentations says [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/setup-configuration.html#styles) and also how it works with -Des.path.conf and -Des.config. But that we never pass the CONF_FILE parameter to the startup command for rpm is a bug I think. I made a pr here: https://github.com/elastic/elasticsearch/pull/13687

**Comment by brwe** [comment]
I forgot to say: We decided to remove the support for CONF_FILE altogether, see #13772
