### ISSUE TITLE
Template API does not return the name of the index which has failed the update

### ISSUE THREAD

**Issue by almiche** [elastic/elasticsearch#53318]
**Describe the feature**:

I would like to include the template name being modified in a MapperParsingException when making a PUT request to the template API with a faulty template.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.2.0

**Plugins installed**: []

**JVM version** (`java -version`):12.0.1

**OS version** (`uname -a` if on a Unix-like system): Linux ec1f30f2faf4 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Taking a look a the output of a failing Template API put request (in this example I added an unsupported parameter on a field for testing) 

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "Mapping definition for [host_name] has unsupported parameters:  [_all : {enabled=true}]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_doc]: Mapping definition for [host_name] has unsupported parameters:  [_all : {enabled=true}]",
    "caused_by" : {
      "type" : "mapper_parsing_exception",
      "reason" : "Mapping definition for [host_name] has unsupported parameters:  [_all : {enabled=true}]"
    }
  },
  "status" : 400
}
``` 
It does not contain the name of the index or template in question here. I was wondering if it would be possible to include that information into error message, since otherwise the information being returned currently is essentially useless.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  Make the following curl request 
```
curl -X PUT "localhost:9200/_template/template_1?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_source": {
      "enabled": false
    },
    "properties": {
      "host_name": {
        "type": "keyword",
        "_all": {
          "enabled": true   
        }
      },
      "created_at": {
        "type": "date",
        "format": "EEE MMM dd HH:mm:ss Z yyyy"
      }
    }
  }
}
'
```

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
> It does not contain the name of the index or template in question here.

Hi @almiche ,
Just to confirm the ask here: when you put an index template like this, there shouldn't be an index yet that triggers the error, but the put template action with the invalid mapping definition itself, so I don't understand where the ask for an index name comes from here. 

With regards to the template name, that would be the template you are just trying to put? Or are you missing the context in which this error is returned? If you manually send a rest request you (or your application) should still know which Url was hit, wouldn't it? And if you do this programmatically, the error should also be sent as a response to a particular request, so you should be able to map them, unless I'm missing something here. Could you elaborate?

**Comment by almiche** [comment]
>  index yet that triggers the error, but the put template action with the invalid mapping definition itself, so I don't understand where the ask for an index name comes from here.

My mistake, for some context we have a lot of different customers that are creating various templates and it's difficult to dig into it further when looking at log messages that just contain the name of the field that is erroneous. It would really ease our workflow if the name of the template trying to be created or updated was included in error response as well. All of our template updates are performed programmaticly so it would be difficult to pinpoint a given response.

Additionally, all of our requests to elasticsearch are made using the bulk api which once again adds to the complexity of matching a request to a response. Let me know if that helps out.

cc: @cbuescher

**Comment by cbuescher** [comment]
Thanks, just two follow up questions:

> All of our template updates are performed programmaticly

Where are these updates triggered? Is it an application you control? Can you add logging there to match the request and potential failures?

> our requests to elasticsearch are made using the bulk api

AFAIK you cannot `PUT /_template` through the bulk API, this is a separate concern I think, or am I missing something here?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @almiche if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
