### ISSUE TITLE
Issue starting elasticsearchv5

### ISSUE THREAD

**Issue by paulm677** [elastic/elasticsearch#53342]
I've been trying to setup elasticsearchv5 on a stand alone machine relating to a TFS install (files picked up from a Azure DevOps drop folder) and am getting the below when the service tries to start.

![image](https://user-images.githubusercontent.com/32931743/76322664-0d039880-62ba-11ea-9d5d-6812da89b876.png)

elasticsearch-service-x64 log:
2020-03-09 15:54:33 Commons Daemon procrun stderr initialized
The data area passed to a system call is too small.

Failed to start service

I've seen a number of issues relating to the JAVA_PATH var, but it appears to be set properly.
![image](https://user-images.githubusercontent.com/32931743/76322861-463c0880-62ba-11ea-8f37-c02dbd81f679.png)

Install is on win server 2012 R2 64bit. 

Install folder was under C and data folder was on D, but I've confirmed the user I configured has admin access to the D... 

Event log notes: The Elasticsearch 5.4.1 (elasticsearch-service-x64) service terminated with the following service-specific error: 
Incorrect function.

Any help would be appreciated

**Comment by paulm677** [comment]
Event log notes: The Elasticsearch 5.4.1 (elasticsearch-service-x64) service terminated with the following service-specific error: 
Incorrect function.

**Comment by paulm677** [comment]
.yml file 
![image](https://user-images.githubusercontent.com/32931743/76323365-00cc0b00-62bb-11ea-882d-34b5a24ed781.png)

jvm.options
![image](https://user-images.githubusercontent.com/32931743/76323416-117c8100-62bb-11ea-9177-8f87e57705ce.png)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
