### ISSUE TITLE
Unable to search double quotes from kibana/query

### ISSUE THREAD

**Issue by ibtisamtahir** [elastic/elasticsearch#53383]
I have some records in my document with 4" , 2" . I want to search 4" but I can only search 4. Elastic is unable to search " from my records. I have tried searching with different methods in my query. I also tried searching through Kibana but problem persists.

**Steps to reproduce**:

 1. Add a document with some data having " in it.
 2. Search using "
 3. It will not hit on the basis of "

**Comment by matriv** [comment]
Thank you very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
