### ISSUE TITLE
*IT tests in x-pack/plugin/core silently ignored?

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#53407]
`*IT` tests in `x-pack/plugin/core`seems to be silently ignored. I was working on a patch for source only snapshots and noticed that `SourceOnlySnapshotIT` is failing on master (without my changes), but this is not being picked up by CI. Same probably applies to `ReloadSynonymAnalyzerIT` and other `*IT` tests?

This looks potentially dangerous as test coverage is not what we would expect it to be.

**Comment by rjernst** [comment]
I've found the problem, and it is very unfortunate. It appears all IT tests in xpack have been disabled for *over a year*. The IT tests in xpack are run under a separate test runner task called `internalClusterTest`. In moving where this task is created, it was accidentally not added to the `check` task, so CI has not known to run it.

I'll open a PR to re-enable, and mute any failing tests with test-failure issues as we would any other failing test.

**Comment by rjernst** [comment]
After going through all the xpack modules defining internalClusterTask, only the core tests were left out of check. This should be fixed by #53444.
