### ISSUE TITLE
org.elasticsearch.node.NodeBuilder & NodeBuilder cannot be resolved to a type

### ISSUE THREAD

**Issue by soumyadip007** [elastic/elasticsearch#53416]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Hi @soumyadip007! Without any information more that the subject line, I assume you are experiencing compilation issues of some sort. Please note that your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
