### ISSUE TITLE
Rest: Path components with plus signs are decoded wrong

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch#5341]
It's perfectly legal for literal '+' characters to appear in the path component on a URL, so for example:

```
$ curl 'http://localhost:9200/foo+bar' -XPOST
{"error":"InvalidIndexNameException[[foo bar] Invalid index name [foo bar], must not contain the following characters [\\, /, *, ?, \", <, >, |,  , ,]]","status":400}
```

should not result in an error, since the index name was "foo+bar", not "foo bar".

A workaround until this issue have been fixed is to percent-encode the plus sign using %2B, but this is not optimal, as it should not be required.

**Comment by clintongormley** [comment]
As a workaround, percent encoding the plus sign will work.

**Comment by paregos** [comment]
Hi there Im new to elastic search and I would like to try and fix this bug, if there is any additional information relating to it please let me know.
Thanks

**Comment by nik9000** [comment]
I don't know about any additional information, though in the time between when this was filed and now we've made a ton of changes. So I'd start by adding tests to make sure it is still a problem and then working from there if it is.

**Comment by vladdypwnz** [comment]
Hey there, new to elasticsearch. Is this issue still open ?

**Comment by monishk7** [comment]
curl -X PUT 'http://localhost:9200/foo+bar'
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [foo bar], must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?]","index_uuid":"_na_","index":"foo bar"}],"type":"invalid_index_name_exception","reason":"Invalid index name [foo bar], must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?]","index_uuid":"_na_","index":"foo bar"},"status":400}

'+' is treated as space.
Is there anyone working on this issue ?

**Comment by original-brownbear** [comment]
This was now fixed in https://github.com/elastic/elasticsearch/pull/33164.
