### ISSUE TITLE
ReloadSynonymAnalyzerIT times out

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#53443]
This test (and others) have been accidentally not running in CI for the last year.

>  REPRODUCE WITH: ./gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.core.rest.action.ReloadSynonymAnalyzerIT.testSynonymsUpdateable" -Dtests.seed=45CA0959F9B975B4 -Dtests.security.manager=true -Dtests.locale=es-UY -Dtests.timezone=AST -Dcompiler.java=13 |  

> REPRODUCE WITH: ./gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.xpack.core.rest.action.ReloadSynonymAnalyzerIT" -Dtests.seed=45CA0959F9B975B4 -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=America/Los_Angeles -Dcompiler.java=13

https://gradle-enterprise.elastic.co/s/lbgekmjgvbi4a/console-log?task=:x-pack:plugin:core:internalClusterTest#L568

**Comment by cbuescher** [comment]
This reproduces for me with the above test seeds, but some other seeds seem to work (e.g. EE844BDD847822CE or ED44152BF83DD23E).

**Comment by cbuescher** [comment]
Something is wrong here with the index names while merging responses:
```
2> ADVERTENCIA: Uncaught exception in thread: Thread[elasticsearch[node_s2][transport_worker][T#2],5,TGRP-ReloadSynonymAnalyzerIT]
  2> java.lang.AssertionError
  2> 	at __randomizedtesting.SeedInfo.seed([45CA0959F9B975B4]:0)
  2> 	at org.elasticsearch.xpack.core.action.ReloadAnalyzersResponse$ReloadDetails.merge(ReloadAnalyzersResponse.java:167)
  2> 	at org.elasticsearch.xpack.core.action.TransportReloadAnalyzersAction.newResponse(TransportReloadAnalyzersAction.java:72)
  2> 	at org.elasticsearch.xpack.core.action.TransportReloadAnalyzersAction.newResponse(TransportReloadAnalyzersAction.java:47)
  2> 	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.newResponse(TransportBroadcastByNodeAction.java:150)
```
```
        void merge(ReloadResult other) {
            assert this.indexName == other.index;
            this.reloadedAnalyzers.addAll(other.reloadedSearchAnalyzers);
            this.reloadedIndicesNodes.add(other.nodeId);
        }
```
