### ISSUE TITLE
EQL: Improve query error message for IN clause with variables 

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elasticsearch#53482]
The issue is captured presently in QueryFolderFailITests
https://github.com/elastic/elasticsearch/pull/53187?email_token=AAGU7H67SBNCJGFAP4YUZ43RGY7W5A5CNFSM4LCR3LA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOLORVY#discussion_r391528671

The following query
`"process where opcode in (1,3) and process_name in (parent_process_name, \"SYSTEM\")"`

results in QlIllegalArgumentException with error message:
`Comparisons against variables are not (currently) supported; offender [parent_process_name] in [==]`

which could be slightly confusing.

**Comment by rw-access** [comment]
Resolved via #53244
