### ISSUE TITLE
Refactor TimeSeriesLifecycleActionsIT (break it down into multiple tests)

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#53488]
This class encapsulates the tests related to ILM in the context of timeseries data (hot/warm/cold deployments). However, it's grown to a size where it's hard to manage and reason about.
We should aim to split the tests that are specific to ILM actions into dedicated test classes, possibly extracting some testing utilities to check the ILM step, explain index api, create index etc.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
