### ISSUE TITLE
Enable support for decompression of compressed response within RestHighLevelClient

### ISSUE THREAD

**Issue by Hakky54** [elastic/elasticsearch#53555]
**Describe the feature**:
I would like to use the http compression feature of Elasticsearch within the RestHighLevelClient.
Currently this is not supported, as other people have already mentioned it here: [Elastic community - resthighlevelclient http compression for gzip](https://discuss.elastic.co/t/resthighlevelclient-http-compression-for-gzip/199155) and also it mentioned here: https://github.com/elastic/elasticsearch/issues/30789

This feature is supported with the low-level-client see here [AsyncElasticsearchCompressedRequest](https://gist.github.com/Hakky54/e818a2d8d7d8153cd0ef89ca4143d805)
Compression can be enabled within a node configuration with the following property: `http.compression: true` Compression can be triggered by a request from a client. Therefor you also need to provide additional information within the header of the request to Elasticsearch if a client really wants to enable it. That is possible with the following RequestOptions:
```
RequestOptions.Builder requestOptions = RequestOptions.DEFAULT.toBuilder()
    .addHeader("Accept-Encoding", "gzip")
```

With these two properties Elasticsearch will return a gzip compressed response body. The RestHighLevelClient can send a request with the above request options but it can't handle the response. This feature request contains the option to handle a compressed response within a RestHighLevelClient received from Elasticsearch.

**Comment by Hakky54** [comment]
See here for the pull request as a solution for this feature request: https://github.com/elastic/elasticsearch/pull/53533

**Comment by Hakky54** [comment]
This feature request looks like a duplicate to this one: https://github.com/elastic/elasticsearch/issues/24349

**Comment by javanna** [comment]
Note for who will review this from the core/features team: I think that we should work on implementing this feature properly in the async client so it gets exposed to all its users, here is their issue where they give pointers and accept external contributions: https://issues.apache.org/jira/browse/HTTPCLIENT-1822 . Although implementing this ourselves may work out and make some of our users happy, I am afraid the way this will be implemented outside of the client may not fit well in the async nature of the apache http async client.

**Comment by Hakky54** [comment]
@andreidan javanna points out that this feature needs to be implemented properly and especially for the async client. The implementation in the pull request covers also the async client as the integration test will be executed for sync and async client, but do you think we missed something that javanna asked for or did we covered everything?

**Comment by Hakky54** [comment]
It looks like this issue can be closed as it already has been merged

**Comment by dakrone** [comment]
Yep, thanks @Hakky54, closing this.
