### ISSUE TITLE
Replace fromValue() method with clear method name.

### ISSUE THREAD

**Issue by JaeGeunBang** [elastic/elasticsearch#53569]
I am currently testing org.elasticsearch.cluster.health.ClusterHealthStatus.

I looked at the `fromValue()` method and `fromString()` method.

The input parameter of `fromString(String status)` is a string type, and the method name also seems clear.

But, the input parameter of `fromValue(byte value)` is a byte type, the method name seems to be **ambiguous**.

Below is fromValue() in ClusterHealthStatus.

```java
public static ClusterHealthStatus fromValue(byte value) throws IOException {
    switch (value) {
        case 0:
            return GREEN;
        case 1:
            return YELLOW;
        case 2:
            return RED;
        default:
            throw new IllegalArgumentException("No cluster health status for value [" + value + "]");
    }
}
```

Looking at other classes that use fromValue (), it simply plays a role of returning a specific value that matches the integer value received as a parameter using switch() or if().

**How about replacing `fromValue(byte ...)` with `fromByte (byte ...)` or `fromNum (byte ...)` ?**

**I think this seems clearer than `fromValue()`.**

The classes that use `fromValue()` are as follows.

```
org.elasticsearch.action.admin.cluster.snapshots.status.SnapshotIndexShardStage
org.elasticsearch.action.admin.indices.alias.IndicesAliasesRequest
org.elasticsearch.cluster.health.ClusterHealthStatus
org.elasticsearch.cluster.RestoreInProgress
org.elasticsearch.cluster.SnapshotInProggress
org.elasticsearch.cluster.routing.ShardRoutingState
org.elasticsearch.index.VertionType
org.elasticsearch.snapshots.SnapshotState
```

**Comment by nik9000** [comment]
For what it is worth I imagine most of these are for serialization and in those cases I'd prefer to put merge the switch statements into the deserialization method.

**Comment by rjernst** [comment]
Thanks for noticing this @JaeGeunBang. We typically use `readFrom` as the method name for doing this kind of deserialization. I've open #53893 to remove this `fromValue` method.
