### ISSUE TITLE
Override Geo aggregations in X-Pack

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#53600]
This is the second (of two) critical issues in preparation for [geo_shape support for geo aggregations](https://github.com/elastic/elasticsearch/issues/37206). To prevent a dependency on [Value Source Refactor](https://github.com/elastic/elasticsearch/issues/42949) from further delaying the release of `geo_shape` doc values and aggregation support, a temporary solution of registering geo aggregations in the X-Pack spatial plugin is suggested by using the module framework. Much like the approach to [overriding doc_values parameter](https://github.com/elastic/elasticsearch/issues/53263), the `SearchModule` class will register geo_ aggregation implementations through a thin OSS `geo` module that provides the base classes necessary to implement Basic+ functionality in the X-Pack `spatial` module (when the appropriate license level is available). In this manner, the OSS implementations will only be registered absent a Basic+ license. 

This approach allows the geo_shape doc value feature to move forward independent of any additional work to the aggregation framework paving the way to potentially release the feature earlier than anticipated.

**Comment by iverase** [comment]
@nknize Can this be closed?

**Comment by iverase** [comment]
I am closing this as it has been done and Elasticsearch 7.8 supports aggregations over geo_shape.
