### ISSUE TITLE
Stemmer token filter light_bengali not working

### ISSUE THREAD

**Issue by facevoid** [elastic/elasticsearch#53628]
**Error in index creation*:

Error in index creation with stemmer token filter value "light_bengali"
but this is available according to the doc [https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html](url)
It works fine with token filter value "bengali"
My mapping is attached below
**Elasticsearch version** : 7.6.1, I've tried on 7.2.0 and got the same error
```
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "refresh_interval": "10s",
    "analysis": {
      "filter": {
        "my_stop": {
          "type": "stop",
          "stopwords": "_bengali_"
        },
        "my_stemmer": {
          "type": "stemmer",
          "language": "light_bengali"
        }
      },
      "analyzer": {
        "bengali_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "indic_normalization",
            "bengali_normalization",
            "my_stop",
            "my_stemmer"
          ]
        }
      }
    }},
    "mappings": {
      
        "content" : {
          "type" : "text",
          "analyzer": "bengali_analyzer"
        }
      }

    }
  }

```
 2. And here is the error
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Invalid stemmer class specified: Light_bengali"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Invalid stemmer class specified: Light_bengali",
    "caused_by" : {
      "type" : "class_not_found_exception",
      "reason" : "org.tartarus.snowball.ext.Light_bengaliStemmer"
    }
  },
  "status" : 400
}

```

**Comment by jimczi** [comment]
Thanks for reporting @facevoid, this looks like a documentation issue because there is only one`bengali` stemmer in Lucene. The javadocs comment says that some criteria are taken from a [`light stemmer`](http://members.unine.ch/jacques.savoy/clef/BengaliStemmerLight.java.txt) but the only one exposed in Elasticsearch is called `bengali`.
Would you be interested in providing a fix in the documentation to remove the link ?

**Comment by facevoid** [comment]
Thanks for your reply.
