### ISSUE TITLE
Index template overwritten with default settings setup.template.overwrite=false

### ISSUE THREAD

**Issue by magicpotion** [elastic/elasticsearch#53644]
**Elasticsearch version**: 7.5.2 elasticloud

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:

Documentation is quite clear about it:

`setup.template.overwrite`
A boolean that specifies whether to overwrite the existing template. **The default is false**.

yet my index templates with the same name and index pattern are being overwritten, as seen in logs:

> [instance-0000000011] adding template [winlogbeat-7.5.2-blabla] for index patterns [winlogbeat-7.5.2-blabla-*]

Sending data directly from Beats with mostly default configuration, no setup.template.ovewrite, believing the default would be false, relevant custom template settings are these:

```
setup.template.name: "filebeat"  
setup.template.pattern: "filebeat-*"  
setup.ilm.rollover_alias: "filebeat-%{[agent.version]}-${STORE,,}"
```

**Comment by dakrone** [comment]
Hi @magicpotion, this appears to be an issue for the beats project, as Elasticsearch does not manage that setting, nor adding the template. Can you please re-open this issue on the https://github.com/elastic/beats/ repository?
