### ISSUE TITLE
How to include Clinet IP /Hostname in Slowlog via some modification in log4j2.properties

### ISSUE THREAD

**Issue by vthorwat** [elastic/elasticsearch#53652]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.6.2

**Plugins installed**: []
opendistro_alerting
opendistro_performance_analyzer
opendistro_security
opendistro_sql
repository-hdfs

**JVM version** (`java -version`):
1.8.0_221
**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.2.1511 (Core)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. How to include Clinet IP /Hostname in Slowlog via some modification in log4j2.properties

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Hi @vthorwat ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
