### ISSUE TITLE
Support include_defaults in the GET-mapping API

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#5368]
The get-field-mapping API only works for core field types, not for fields of type `object` or `nested`:

```
curl -XPUT "http://localhost:9200/test" -d'
{
  "mappings": {
    "test": {
      "properties": {
        "foo": {
          "type": "object",
          "properties": {
            "bar": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}'
```

Retrieving the mapping for core fields works:

```
curl -XGET "http://localhost:9200/test/_mapping/test/field/foo.bar"
```

Result:

```
{
   "test": {
      "mappings": {
         "test": {
            "foo.bar": {
               "full_name": "foo.bar",
               "mapping": {
                  "bar": {
                     "type": "string"
                  }
               }
            }
         }
      }
   }
}
```

But not for fields of type `object` or `nested`:

```
curl -XGET "http://localhost:9200/test/_mapping/test/field/foo"
```

Result:

```
{}
```

**Comment by csezheng** [comment]
+1 to add the include_defaults option to get mapping API, and also makes it work for the object type field.

**Comment by csezheng** [comment]
If this is not gonna be fixed soon, is there any alternative way to get the default values for the object/nested type fields? Thanks.

**Comment by jpountz** [comment]
We just discussed it in Fixit Friday and are +1 on @bleskes 's plan. Making it an adoptme as well as a high-hanging fruit because of the described caveats...

**Comment by clintongormley** [comment]
Rediscussed in FixItFriday - would be good to:

* remove the field mapping API
* add support for include_defaults to the mapping API
* users can use response filtering for a particular field 
* perhaps we can support `flat_paths` to return fields like `foo.bar.baz` instead of using JSON objects

@rjernst is the following still true after the mapping refactoring you did?

> Caveat - The get field mapping api was added and implemented in the current form (i.e., requiring at least one assigned shard) because the defaults are currently baked in the the field mapper in memory objects. To so on the master and based on the serialized representation of the _mapping, we need to have a better grip on the defaults (or if we just choose to instantiate these objects with every request).

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
The issue of still relevant. cc @elastic/es-search-aggs

**Comment by javanna** [comment]
It's been a long time since this issue was discussed last. The get field mappings API has effectively been replaced by the field caps API. We have not removed the API due to the breaking nature of such a change but we would expect users to rely on field_caps to inspect the fields and their capabilities. In case mappings need to be inspected instead, get mappings is the way to go. As for adding support for include_defaults to get mappings, I doubt that it would be useful today given that most users should rely on field_caps, hence I am going to close this issue. Feel free to comment or reopen if you think otherwise.
