### ISSUE TITLE
Add gradle task to run core/server REST YAML tests

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#53683]
Currently we have instructions to run (from TESTING.asciidoc):

```
./gradlew :distribution:archives:integ-test-zip:integTestRunner \
 --tests "org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT"
```

It would be great to have this as a simple command, so it could be composed with other things, such as:

```
./gradlew :checkYAML
```

And then I could do:

```
./gradlew :server:check :checkYAML
```

**Comment by mark-vieira** [comment]
Looks like `IntegTestZipClientYamlTestSuiteIT` is no longer a think. I think the replacement for this is `./gradlew :rest-api-spec:check`.
