### ISSUE TITLE
Excessive redundancy suggestion

### ISSUE THREAD

**Issue by hydralien** [elastic/elasticsearch#5369]
Hi,

there's a case when there seems to be a place for improvement in elasticsearch. Problem is, if node dropping off the cluster is something that happens rather often, rebalancing the cluster to keep replicas in sync with index.number_of_replicas setting (especially if node gets back rather soon) produces a significant load.

There seem to be a rather simple solution for this though:
- have a higher and lower bounds for index.number_of_replicas - let me call them index.min_number_of_replicas and index.max_number_of_replicas here. By default they might be omitted in config and both equal index.number_of_replicas unless redefined explicitly
- replicate any shard only if number of its replicas is lower than index.min_number_of_replicas
- drop excessive shard replicas only if replicas count is over index.max_number_of_replicas
- new shards should be replicated to index.min_number_of_replicas
- replication should pump replica count up to index.max_number_of_replicas off-peak. There are two quick initial solutions for this: 
a) it could be either customer's responsibility to change index.min_number_of_replicas setting to match index.max_number_of_replicas in off-peak hours and drop down when high load is expected. 
b) it could be a command-line tool or parameter or any other directive to "replicate up to the limit"
Eventually there could be another setting like index.off_peak_range to do that automatically, but even without it the change would be of a significant help.

Generally this would let the cluster to have some extra resources to spare for query needs rather than shards redistribution.

Apologies if this doesn't actually suit the architecture or was discussed before or else.

Cheers.

**Comment by dakrone** [comment]
We discussed this and this is really outside the scope of Elasticsearch itself, this is something that could be better implemented either as a plugin (listening to `clusterChanged` events and dynamically increasing/decreasing the replica count for an index) or as a client-side application that handled this. Additionally things like determining off-peak hours would be better suited to a process other than Elasticsearch itself.

Closing this for now, let me know if we have misunderstood something about it.
