### ISSUE TITLE
Full Execute API Context Support

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#53703]
Painless allows users to test a script using our execute API (https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-execute-api.html) for a few specific contexts. We will define an appropriate API and move this feature to core so that any context using any language has the ability to define appropriate execute api parameters to test scripts against.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
