### ISSUE TITLE
SQL: add support for formatting dates/strings using a custom date format

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#53714]
This is a generic ask for more flexibility when dealing with timestamps that have a different format than the one Elasticsearch is expecting to get in queries.

Because ES SQL doesn't have a way to find the actual format a `date` field is being configured with in Elasticsearch,when creating a query the user needs to have this knowledge and provide the proper text string when dealing with timestamps. For example `SELECT timestamp FROM test WHERE timestamp = '1990-12-12 10:23:00'` will fail in a default index configuration in Elasticsearch because ES will expect the date format to be `1990-12-12T10:23:00`.

With a function like `to_char`, the query above becomes `SELECT timestamp FROM test WHERE to_char(timestamp, 'yyyy-MM-dd HH:mm:ss') = '1990-12-12 10:23:00'`.

Using custom date formats could also work the other way around with functions like `to_date(text, format)` or `to_timestamp`.

Relates to https://github.com/elastic/elasticsearch/issues/50193.

**Comment by matriv** [comment]
- DATETIME_FORMAT
  -  `master` : 72be0b54a9299e87e785469cdc9aafac2a48c046
  - `7.x` : 6afd60b0821f57bc913fe6ae456bfda2e192e4a7

- DATETIME_PARSE
  - `master` : 3febcd8f3cdf9fdda4faf01f23a5f139f38b57e0
  - `7.x` : bf0cadb6023ac23d67510b76c3fc0ff322a19abb
