### ISSUE TITLE
[Docs] Script examples in Strings Stats Aggregation

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#53723]
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-aggregations-metrics-string-stats-aggregation.html

Running scripts as part of an aggregation at query time is expensive, yet this extensively described in the documentation of this aggregation.

While it is important to show that this aggregation can be combined with scripts, I am wondering if it would be wise to add a Note (read: Warning) that this may significantly impact performance. In particular, users should avoid running scripts often. Instead, the data should be transformed at ingest time and stored accordingly.

**Comment by nik9000** [comment]
That makes sense to me. Would you like to open a PR?

**Comment by polyfractal** [comment]
If we add something like this, it should go somewhere centralized rather than on a per-agg basis imo.  E.g. scripting is used widely across all aggs, search and elsewhere so it's not necessarily an agg-specific item.  This isn't necessarily related to string_stats in particular.

That said, scripts are also a lot less expensive than they used to be.  Painless does a good job of compiling scripts down to near-native performance.  The biggest issue is that they eliminate some optimizations like skipping docs if used for filtering (because they have to evaluate each doc), etc.

**Comment by nik9000** [comment]
> That said, scripts are also a lot less expensive than they used to be. Painless does a good job of compiling scripts down to near-native performance. The biggest issue is that they eliminate some optimizations like skipping docs if used for filtering (because they have to evaluate each doc), etc.

:+1:

min and max are a great example. terms and composite too!

**Comment by fkelbert** [comment]
> E.g. scripting is used widely across all aggs, search and elsewhere so it's not necessarily an agg-specific item. This isn't necessarily related to string_stats in particular.

I agree. 

> If we add something like this, it should go somewhere centralized rather than on a per-agg basis imo. 

I am not sure users would find this information. Instead, I would expect users to copy/paste code examples from the documentation and to adjust them to their needs. This is why I think it makes sense to have a corresponding note just below or above the code example. 

Can we have a centralized place that describes the gotchas of using scripts within aggs? Then, whenever the docs provide such an example, there is a single sentence (of warning) linking to the central place with detailed information?

**Comment by nik9000** [comment]
I talked with @debadair and @jrodewig about this and they are willing to help out here but would like me to make a list of places where we talk about similar stuff. Here is my list!

* "Avoid Scripts" in [tuning for speed](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#_avoid_scripts)
* [regexes](https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-regexes.html) in the painless docs. In general a lot of the hand and fast choices we made in painless were to make sure that query time scripts were fast.
* [scripted metric](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html) *super* needs a warning about how it can be slow.
* [script query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-query.html) does too!
* [prefer parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#prefer-params) looks good
* [stored scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#modules-scripting-stored-scripts) doesn't really mention speed differences in stored scrips vs request script (I don't believe there are too many)

That is about as far as I got before I got distracted!
