### ISSUE TITLE
No support for max_determinized_states in _source: includes

### ISSUE THREAD

**Issue by JaspreetSinghChahal** [elastic/elasticsearch#53739]
Elasticsearch version : 7.*
There is no option to specify max_determinized_states in source filtering.
_source:{
    "includes":["field1",..........] 
}
 specifying more than 1000 fields leads to "too_complex_to_detrmine_exception_error". So even if more than 1000 fields are supported in index there is no way to selectively return them (especially in reindex)

**Comment by benwtrent** [comment]
I wonder if this issue still exists. The way we parse given source values and grab values from _source has changed greatly in the last 4 years. 

I would expect complicated source patterns to still fail, but I would expect overall support to have improved.

**Comment by jimczi** [comment]
Yes @benwtrent this PR makes the option irrelevant in newer version I think: https://github.com/elastic/elasticsearch/pull/72277
