### ISSUE TITLE
Should support pipeline search command like splunk

### ISSUE THREAD

**Issue by huangchen007** [elastic/elasticsearch#5373]
splunk is a log analysis software(http://www.splunk.com/)(http://docs.splunk.com/Documentation/Splunk/latest/SearchReference/WhatsInThisManual)

It support some kind of search command like as below:

Example 1: Return the 20 most common values of the "referer" field.
sourcetype=access_*   |  top limit=20 referer

Example 2:Create a chart to show the average number of events in a transaction based on the duration of the transaction

sourcetype=access_* status=200 action=purchase | transaction clientip maxspan=30m | chart avg(eventcount) by duration span=log2

Pipeline char "|" can allow us to compose a complex a rule for analysis straightforwardly!!! It's very important!

Consider it please!

labels:enhancement

**Comment by clintongormley** [comment]
Elasticsearch is a very different beast. This syntax is targeted at stream processing of raw data, while Elasticsearch gains its speed advantage by indexing everything up front.  While I could imagine somebody building something like this into a plugin or application based on elasticsearch, I don't think the syntax is right for inclusion in core.
