### ISSUE TITLE
Joining more indexes and paginate the result

### ISSUE THREAD

**Issue by mdepascale** [elastic/elasticsearch#53732]
**Describe the feature**: 
I'd like to be able to join more indexes and paginate the result

**Elasticsearch version**: 6.8.0

URL: POST ... .../_opendistro/_sql/

**Actual query:** 
`"query": "SELECT * FROM file f JOIN document d ON d.id = f.documentId WHERE d.documentCategoryId = '..."  AND d.state = '...' LIMIT 5 "`
this query is working fine, but it can skip the first x results

**Feature request**
`"query": "SELECT * FROM file f JOIN document d ON d.id = f.documentId WHERE d.documentCategoryId = '..."  AND d.state = '...' LIMIT 5 OFFSET 5"`

I don't actually need _opendistro/_sql/ if you have other options like:
- can I translate SQL query **with JOIN** in ES query?
- any way I can join 2 indexes and use `size` and `from`
- is there any option with `search_after` or `from`

**Comment by cbuescher** [comment]
Hi @mdepascale! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
