### ISSUE TITLE
Elasticsearch image creation fails due to docker issues

### ISSUE THREAD

**Issue by aishwaryabk** [elastic/elasticsearch#53786]
I am trying to build elasticsearch 7.6.0 image on rhel 7 ppc64le platform. However the gradle build fails

ERROR:

	Some docker related errors were encountered while running the build.
	FAILURE: Build failed with an exception.

	* What went wrong:
	Process 'command '/usr/bin/docker'' finished with non-zero exit value 1

	BUILD FAILED in 5m 10s

Running a docker build command and all neccessary file are placed in the same working directory.

`Docker version:  18.03.1-ce`
`Environment: Rhel 7.6 PowerPC (ppc64le)`

Would like some help on understanding the cause for the same . I am running it on a High end VM with good connectivity.

**Comment by nik9000** [comment]
There really *ought* to be an error report further up from docker. Please double check that. In the mean time I'll stick the `"build" tag on this and someone more familiar with the build will have a look too.

**Comment by rjernst** [comment]
@aishwaryabk As Nik suggested, please look further up in the build output. The entire build output would be useful here, including a link to a gradle build scan if you have enabled that (or run another build with the build scan enabled).

**Comment by aishwaryabk** [comment]
Is there a way  to skip the docker build? @nik9000 @rjernst

**Comment by rjernst** [comment]
You can run the `assemble` task in the subproject for whichever distribution you are interested in. For example, `./gradlew :distribution:archives:oss-linux-tar` for the oss linux tar archive.

**Comment by rjernst** [comment]
@aishwaryabk Were you able to find the output requested? If not I think we should close this as a setup issue, as it seems you are not actually interested in the docker distribution.

**Comment by aishwaryabk** [comment]
@rjernst Thank You. 

> You can run the `assemble` task in the subproject for whichever distribution you are interested in. For example, `./gradlew :distribution:archives:oss-linux-tar` for the oss linux tar archive.

This works.
