### ISSUE TITLE
Upgrade docs do not cover patch-version upgrades

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#53787]
Today's upgrade docs describe how to upgrade from e.g. 7.5.x to 7.6.1, but do not explicitly cover upgrades _within_ a minor version, e.g. 7.6.0 to 7.6.1. I think we should cover this case too, lest users think that this kind of upgrade is not supported. Such a user [raised this very question on the forums](https://discuss.elastic.co/t/upgrade-es-from-7-6-to-7-6-1/224256).

**Comment by jrodewig** [comment]
Closed by #55012.
