### ISSUE TITLE
Change in `index_in_parent` doesn't work, but throws no error

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/elasticsearch#53792]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.6 / 7.6.0

**Description**:
Trying to change the value of `index_in_parent` seems to succeed, but doesn't.
I would expect that it is working as designed that that value cannot be changed, but I think it's a bug that no error is returned when trying to change it.

**Steps to Reproduce:**
```
PUT /parenttest
```
```
PUT /parenttest/_mapping/_doc
{
  "properties": {
    "email": {
      "type": "keyword"
    },

            "user" : {
                "type" : "nested",
                "include_in_parent": true,
                "properties": {
                    "first" : {"type": "text" },
                    "last"  : {"type": "text" }
                }
            }

  }
}
```
```
GET parenttest
```
```
PUT /parenttest/_mapping/_doc
{
  "properties": {
    "email": {
      "type": "keyword"
    },

            "user" : {
                "type" : "nested",
                "include_in_parent": false,
                "properties": {
                    "first" : {"type": "text" },
                    "last"  : {"type": "text" }
                }
            }

  }
}
```
```
GET parenttest
```

*Expected behaviour:*
The third `PUT` returns an error explaining that it's not possible to change the value of "include_in_parent"

*Observed Behaviour:*
None of the calls throws an error.
The second `GET` returns exactly the same data as the first.

**Comment by iluwa** [comment]
I would like to work on this. May I?

**Comment by jtibshirani** [comment]
Thanks @AndyHunt66 for reporting this. I agree that we should throw an error when attempting to change the values for these parameters. The alternative is to add support for changing the value. This would allow for a situation in which some documents contain the values in the parent/ root but others do not, which is a strange index state and could cause confusion when querying against these fields.
