### ISSUE TITLE
Automatically configure formatting for IntelliJ

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#53812]
Forked from #53747.

We could automatically configure IntelliJ to use the Eclipse formatter and our bundled format config. The downside of this is that it relies on the "Eclipse Code Formatter" plugin, though I also noticed a thing in IntelliJ about "Required Plugins", under "Build, Execution, Deployment". I tried adding the Eclipse plugin, and it created the file `.idea/externalDependencies.xml` with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ExternalDependencies">
    <plugin id="EclipseCodeFormatter" />
  </component>
</project>
```

Configuring the plugin created: `.idea/eclipseCodeFormatter.xml` with contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="EclipseCodeFormatterProjectSettings">
    <option name="projectSpecificProfile">
      <ProjectSpecificProfile>
        <option name="formatter" value="ECLIPSE" />
        <option name="pathToConfigFileJava" value="$PROJECT_DIR$/.eclipseformat.xml" />
        <option name="selectedJavaProfile" value="Elasticsearch" />
      </ProjectSpecificProfile>
    </option>
  </component>
</project>
```

It's also referenced in `.idea/workspace.xml`:

```xml
<project>
  <component name="PropertiesComponent">
    <property name="settings.editor.selected.configurable" value="EclipseFormatter" />
```

**Comment by mark-vieira** [comment]
@pugnascotia does the recent work for Checkstyle mostly address this?

**Comment by pugnascotia** [comment]
No, this is a separate thing.

**Comment by mark-vieira** [comment]
Where did we land with this? So far as I can tell the only missing bit is the "Required plugins" bit. I tested this locally be uninstalling the plugin and doing a fresh import and it worked fine.

![image](https://user-images.githubusercontent.com/4106672/156441818-859e6036-1d04-4bb3-a7a5-b856b936d001.png)

I suggest we go ahead and do this so it's one less thing folks have to configure manually. In fact, I think that will mean folks don't have to configure _anything_ manually on import which would be awesome. I know we've had some reports of folks fighting with spotless before realizing they weren't using the same format rules in the IDE.

**Comment by pugnascotia** [comment]
I haven't looked at this again since I raised it, but if you can get it to work on project import then please do!

**Comment by mark-vieira** [comment]
Should we add the checkstyle plugin to the list as well?
