### ISSUE TITLE
EQL: add test class that should deal with Node's replaceChildren, transform and info methods

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#53862]
With [functions starting to be added to the project](https://github.com/elastic/elasticsearch/issues/51556) there is a need for a NodeSubclassTests class to be added as well. This should be very similar to QL's and SQL's corresponding classes with the same name and should test common Node implementations from QL and EQL.

**Comment by wchaparro** [comment]
Superceded by ES|QL
