### ISSUE TITLE
Classification analysis fails when dependent variable is of type text.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#53876]
The error message is:
```
{
        "type" : "illegal_argument_exception",
        "reason" : "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [glass_type] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
```

**Comment by przemekwitek** [comment]
This reproduces easily in integration test.

**Comment by przemekwitek** [comment]
Ok, I was able to track down this issue. As part of starting the analysis, we first
 1. perform 'cardinality` aggregation on `dependent_variable` field to use it later for limit verification (see line 125 in `ExtractedFieldsDetectorFactory.java`)
and then we
 2. verify supported `dependent_variable` types in `ExtractedFieldsDetector`

This order is problematic as we simply cannot perform `cardinality` aggregation on a `text` field (it yields the error I provided in the first post).
So we would need to reverse this order and first check for supported types and then check cardinality.

**Comment by javanna** [comment]
heya @przemekwitek may I ask you to add labels to this issue please? Thanks!

**Comment by przemekwitek** [comment]
> heya @przemekwitek may I ask you to add labels to this issue please? Thanks!

Done.

**Comment by przemekwitek** [comment]
PR #53874 makes the error message more understandable for the user.
