### ISSUE TITLE
Search returns invalid JSON when identity meta-fields are used in docvalue_fields

### ISSUE THREAD

**Issue by vad-de-mark** [elastic/elasticsearch#53875]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.2

**Plugins installed**: [
  "analysis-icu",
  "discovery-ec2"
]

**JVM version** (`java -version`):
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux *** 4.14.165-102.185.amzn1.x86_64 #1 SMP Wed Jan 15 01:39:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When `docvalue_fields` is used with identity meta-fields (`_id`, `_index`, `_type` in any combination) these fields are adding to the hit object itself, not to fields array. It wouldn't be a big deal if only we didn't get duplication, because for now if you specify for example `_id` in `docvalue_fields` the hit will contain two `_id` fields. And this behaviour repeats for each identity meta-field. If you specify all of them - all of them will be duplicated. Kibana can handle invalid JSON, but Java API can not, what leads to errors. Not sure about adding values of these fields into `fields` array in response is necessary, but invalid JSON looks like a bug.
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create an index (e.g. `test_index`)
 2. Index at least one document (empty document is more than enough)
 3. Try to search with `docvalue_fields` and identity meta-fields (e.g. `_id`)

```
PUT test_index

POST test_index/_doc/1
{}

GET test_index/_search
{
  "docvalue_fields": [ "_id" ]
}
```

The hits would be:
```
"hits" : [
      {
        "_index" : "test_index",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_id" : "1",
        "_source" : { }
      }
    ]
```

**Comment by oeddyo** [comment]
anyone working on this? If not may I try?

**Comment by abprash** [comment]
@oeddyo, i was wondering if you were working on this, and if you needed any help. Feel free to let me know.

**Comment by abprash** [comment]
I am able to reproduce this on 8.0.0-SNAPSHOT as well. Looking into it.

**Comment by oeddyo** [comment]
Sorry just saw this. Are you working on it? I can work on it for sure! @abprash

**Comment by abprash** [comment]
i am working on it for the past few days @oeddyo :)

**Comment by cbuescher** [comment]
I checked this issue on 7.9.3 and we don't return duplicate "_id" or other metadata fields there anymore. Instead the requested metadata field is added to the "fields" output as well, e.g.
```
"fields" : {
          "_id" : [
            "1"
          ]
        }
```
Closing this issue for that reason.
