### ISSUE TITLE
When Watcher HTTP action fails, it reports it fails forever without ever actually retrying

### ISSUE THREAD

**Issue by runtman** [elastic/elasticsearch#53885]
**Elasticsearch version** (`bin/elasticsearch --version`): Elastic Cloud 7.6.1

**Plugins installed**: None

**Description of the problem including expected versus actual behavior**:

Hello, so I got a watcher action that posts to an API for freshdesk (Ticket system) this works 99.9% of the time, but every now and then we receive a 502 back from Freshdesk.

If this happens, every consequtive alert, will skip the freshdesk part and claim it's failing.

![1](https://user-images.githubusercontent.com/6459792/77183511-59bf4e80-6ac6-11ea-834e-16f20b12c2e7.png)

![2](https://user-images.githubusercontent.com/6459792/77183519-5c21a880-6ac6-11ea-99e1-d48fb2b77d1c.png)

Even on watches that should now report OK report as failing... it's quite annoying.

The only way I appear to fix is is by recreating the watch, am I doing something wrong here? The watcher config is as follows:

```
    "freshdesk_alert" : {
      "webhook" : {
        "method" : "POST",
        "host" : "X.freshdesk.com",
        "path" : "/api/v2/tickets",
        "scheme" : "https",
        "port" : 443,
        "body" : {
          "inline": {
            "subject": "X",
            "description": "X",
            "email": "devops@X.com",
              "priority": 3,
              "status": 2,
              "group_id" : 6000196835,
              "custom_fields" : {
                "customer": "Actual Experience",
                "it_or_devops_support_required": "Product Fault/Bug",
                "end_customer": "N/A",
                "cf_internal_logging_codes_1": "IT Incident",
                "cf_internal_logging_codes_2": "Network/Infrastructure",
                "cf_internal_logging_codes_3": "Event"
             }
          }
        },
        "auth" : {
          "basic" : {
            "username" : "{{PASSWORDADDEDBYCI}}",
            "password" : "X"
          }
        },
        "headers" : {
          "Content-Type" : "application/json"
        }
     }
  }, 
```

Original Failure:

https://pastebin.com/6zi9pkkQ 1

Consequitve Watches Listed As Error:

https://pastebin.com/KQ8hbtje 1

This is just a visual problem as the action hasn't required to fire again,  but it led me to believe that there was a problem with the watch.

A retry mechanism would go a long way here also, unless this already exists?

**Comment by runtman** [comment]
Bug report requested by: https://discuss.elastic.co/t/when-watcher-http-action-fails-it-reports-it-fails-forever-without-ever-actually-retrying/224395/4

**Comment by abdalians** [comment]
+1 I see the same behaviour.. I got this error back on the 11th, and from then on the watch stayed in Error state. This is happening on 6.5.4 as well as 7.4.2 Editing and saving the watch clears the error state and the watch begins to function as normal. 

`[2020-08-11T18:09:27,709][ERROR][o.e.x.w.n.s.SlackService ] [es14] failed to execute slack api http request
org.apache.http.conn.ConnectTimeoutException: Connect to hooks.slack.com:443 [hooks.slack.com/54.227.211.227, hooks.slack.com/54.209.135.9, hooks.slack.com/3.229.174.54] failed: connect timed out
        at org.elasticsearch.xpack.watcher.notification.slack.SlackAccount.send(SlackAccount.java:115) [x-pack-watcher-6.5.4.jar:6.5.4]
        at org.elasticsearch.xpack.watcher.notification.slack.SlackAccount.send(SlackAccount.java:69) [x-pack-watcher-6.5.4.jar:6.5.4]
        at org.elasticsearch.xpack.watcher.actions.slack.ExecutableSlackAction.execute(ExecutableSlackAction.java:50) [x-pack-watcher-6.5.4.jar:6.5.4]`

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
