### ISSUE TITLE
[DOCS] Consolidate data management docs into a cohesive story

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#53895]
## Goals

- Provide a conceptual overview on how to manage your data over time
- Describes the deployment architectures that support typical use cases
- List and explain the tools that Elasticsearch provides to make it happen

## High-level actions

- Sketch an initial outline the overall Data Management story
- Sync with the Data Management team to get it validated
- Make sure the outline is aligned with parallel doc initiatives like serverless, IA and migration

Relates to: #53894

**Comment by alaudazzi** [comment]
Closing in favour of Jira issue [DOC-30](https://elasticco.atlassian.net/browse/DOC-30)
