### ISSUE TITLE
[CI] createNodeKeyStore failed on Jenkins darwin worker due to DNS name

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#53968]
https://gradle-enterprise.elastic.co/s/r3hcjn6yivexe failed with the following error in a darwin build (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/595):

```
00:08:37 keytool error: java.lang.RuntimeException: java.io.IOException: DNSName components must begin with a letter
00:08:37 
00:08:37 build complete, generating: /private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/build/595.tar.bz2
00:09:40 
00:09:40 FAILURE: Build failed with an exception.
00:09:40 
00:09:40 * What went wrong:
00:09:40 Execution failed for task ':x-pack:plugin:sql:qa:security:with-ssl:createNodeKeyStore'.
00:09:40 > Process '/var/lib/jenkins/.java/openjdk11/bin/keytool [-genkey, -alias, test-node, -keystore, /private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/x-pack/plugin/sql/qa/security/with-ssl/build/keystore/test-node.jks, -keyalg, RSA, -keysize, 2048, -validity, 712, -dname, CN=smoke-test-plugins-ssl, -keypass, keypass, -storepass, keypass, -ext, san=ip:fe80::1,dns:20049.local,ip:::1,dns:localhost,ip:127.0.0.1,dns:localhost]' finished with non-zero exit value 1
```

I am guessing the part of that that `keytool` took offence at is `dns:20049.local`.

I can run `./gradlew ':x-pack:plugin:sql:qa:security:with-ssl:createNodeKeyStore'` without problems on my Macbook.  Presumably there is something different about the way the macOS Jenkins workers are configured that means they have a technically invalid DNS name.

**Comment by droberts195** [comment]
This was not a one-off problem.  The next build, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/596/console, failed in the same way.

Also https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/592/console also failed in this way on 21st March.

Every single macOS master branch build still in the Jenkins history has failed for one reason or another, so this might not be a new problem.  It might just have been masked by other failures for a while.  But now it is the blocker to getting a working macOS CI run on master.

**Comment by rjernst** [comment]
I don't think this is a general build problem, but something SQL needs to look at within their own build setup. I'm relabeling as such; please reach out to core/infra if you need help.

**Comment by tlrx** [comment]
This failed again today, and this is failing regularly for few days now:
- https://gradle-enterprise.elastic.co/s/mfeeeo2b3wraa
- https://gradle-enterprise.elastic.co/s/5o3ka3aohoiq6
- https://gradle-enterprise.elastic.co/s/zn27ns6kyxccs

I'm not sure how to fix or mute this, hence I'm assigning the issue to @costin so that he can dispatch :)
