### ISSUE TITLE
Apply timeout on the coordinating node too

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#54056]
Currently the timeout is only applied at the shard level. Shards are expected to wrap up ongoing work as soon as they hit the timeout and return a partial response. This is usually good enough, unless shard requests spend time in the search queue. For instance if a timeout of `1s` is configured but the shard search request waits for 10s in the search queue, then Elasticsearch wouldn't return a response in less than 10s despite the timeout.

This hasn't been much of an issue until now, but I believe that the introduction of slower options like searchable snapshots and schema on read is going to make this issue worse, as it'll make it more likely to have shard requests waiting in the queue.

**Comment by javanna** [comment]
Closing in favour of #30897 .
