### ISSUE TITLE
Remove `ignore_throttled`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#54058]
Quoting the docs:

> Search requests will not be executed against frozen indices by default, even if a frozen index is named explicitly. This is to prevent accidental slowdowns by targeting a frozen index by mistake.

While this made sense at the time when frozen indices were introduced, I wonder that we should remove this option now:
 - Throttled indices are only one way that requests may be slow, we are now introducing other options that may make requests very slow, such as doc-value-only fields or schema-on-read.
 - While frozen indices were considered 2nd-class citizens at the time of their introduction, slower storage options are becoming first-class citizens. For instance they now have an `_async_search` API to make searching slow indices less painful. I don't think we should keep making a difference between throttled and non-throttled indices.
 - The introduction of this parameter ended up forced everything that builds on top of `_search` to also support this parameter, like `_sql` or Kibana, while they really shouldn't worry about whether an index is throttled or not.

**Comment by jpountz** [comment]
We just had a discussion about this proposal. Here is a summary of arguments that have been made:
 - Removing this option feels right for the `_async_search` API, but is it right for `_search`?
 - We feel that it is important to keep `_search` and `_async_search` consistent, which would mean removing this option for `_search` too.
 - While this option tries to prevent surprisingly slow requests, it also hides data silently, which might be even more surprising to users.
 - There are many ways why a request might be slow, why make throttled indices special?

We ran a bit short on time, but it looked like we were converging towards removing it. It's still time to speak up if you disagree.

A question that is open is when to implement this change. The breaking nature of the change suggests 8.0, but on the other hand there have been arguments that we should look at our options for 7.x given how surprising it is that throttled indices get ignored by default.

**Comment by jimczi** [comment]
@jpountz should we close this issue now that https://github.com/elastic/elasticsearch/pull/55852 is merged ?
