### ISSUE TITLE
Rewrite `exists` queries to MatchNoneQueryBuilder when the field is unmapped

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#54062]
Rewriting `exists` queries to a `MatchNoneQueryBuilder` when the field is unmapped would help skip shards in the `can_match` phase.

**Comment by Subhadeep2707** [comment]
Hi, I am a beginner. Can I start working on this?

**Comment by jpountz** [comment]
Sure. You might want to have a look at TermQueryBuilder#doRewrite and how it deals with the case when the field is not mapped.

**Comment by Subhadeep2707** [comment]
As per Contributing.md, I need to sign the Contributor License Agreement before submitting a PR. But my signing process fails with an 'Unable to start signing process. Please try again' error.

**Comment by Subhadeep2707** [comment]
I have submitted a pull request. Can you please review it and let me know? Thanks.

**Comment by SivagurunathanV** [comment]
@Subhadeep2707 Please let me know if you are still working on this issue? or can I take this up?

**Comment by Subhadeep2707** [comment]
@SivagurunathanV I am not working on this issue. Please go ahead.

**Comment by SivagurunathanV** [comment]
#54857 https://github.com/elastic/elasticsearch/pull/54857
