### ISSUE TITLE
Feature request: Force shards of the same index to be allocated to different physical hosts

### ISSUE THREAD

**Issue by ldpvl** [elastic/elasticsearch#54091]
This feature request is based from https://discuss.elastic.co/t/es-6-8-force-primary-shards-of-the-same-index-to-be-allocated-to-different-physical-hosts/217434

This applies to setups of Elasticsearch clusters where there are multiple ES data nodes running on the same host. These kind of setups are understood to be not recommended but can be prevalent in organisations due to various reasons.

Below is an example ES setup:

Host A: data node A1, data node A2, data node A3
Host B: data node B1, data node B2, data node B3
Host C: data node C1, data node C2, data node C3
...

If we take an example where there are daily indexes created for logs (an index has number of primaries 10 and number of replicas 1), then today's index will usually be the most written to index and past day indexes will almost have nothing being written to them.

Now because ES is constantly balancing shards across all nodes, on some occasions all or the majority shards of today's index (which is being written to a lot) end up being on data nodes A1, A2 and A3 on the same Host A.

This causes an imbalance in the cluster in terms of resource usage - hosts A is overloaded and hosts B and C are practically idle.

There is already a similar feature to what is being asked here which is [cluster.routing.allocation.same_shard.host](https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html) - it forces copies of the same shard to be on different hosts which in turn reduces the chance of writes being congregated on the same host.

So it would be great to have a new feature to force shards of the same index to be on different hosts.

**Comment by DaveCTurner** [comment]
I think it unlikely we will take action on this issue so I am closing it. You can achieve approximately the desired behaviour with allocation awareness, but even without that we'd recommend proper isolation between co-located nodes (e.g. using containerisation).
