### ISSUE TITLE
Geoshape query of type envelope fails to find geo_point

### ISSUE THREAD

**Issue by nickpeihl** [elastic/elasticsearch#54123]
Thanks so much for https://github.com/elastic/elasticsearch/pull/52382.

However, I tried to use the [envelope](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#_envelope) type of geoshape query from the [docs example](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#_envelope) over a geo_point field and it failed to return my geo_point. 

If envelope is not supported for geo_point, shouldn't it return an error? 

For example:

```
PUT /test/
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point"
      }
    }
  }
}

PUT /test/_doc/0
{
  "location": [-123.0, 48.5]
}

```

This query returns zero hits. 
```
POST /test/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": [
        {
          "geo_shape": {
            "location": {
              "shape": {
                "type": "envelope",
                "coordinates": [
                  [-121,49], [-124,47]
                  ]
              },
              "relation": "intersects"
            }
          }
        }
      ]
    }
  }
}

```

**Comment by iverase** [comment]
The sysntaxt for envelope is a bit trappy. When using GeoJSON, the coordinates should be given with the format [[minLon, maxLat], [maxLon, minLat]].

 In your case minLon = -121 and maxLon = -124. This means that minLon > maxLon, therefore is a bounding box that crosses the dateline and the longitudes between -124 and -121 are excluded. Try changing the order:

```
POST /test/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": [
        {
          "geo_shape": {
            "location": {
              "shape": {
                "type": "envelope",
                "coordinates": [
                  [-124,49], [-121,47]
                  ]
              },
              "relation": "intersects"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by nickpeihl** [comment]
Oops. Thanks @iverase for correcting me. Closing this.
