### ISSUE TITLE
listener timeout after waiting for [300000]ms

### ISSUE THREAD

**Issue by zjfplayer** [elastic/elasticsearch#54143]
We are using version 5.4 elasticsearch. When using BulkRequest for batch update operations, we find that when the number of records is approximately 100 million, an "listener timeout after waiting for [xxx] ms" exception is reported. We have tried to increase the timeout period, and we can see from the error log that the timeout configuration has taken effect, but it still reports an error. The document content is:
<pre>
"c_appid": "com.yaliceshi.id4",
"c_appname": "LightView",
"c_appversion": "2.5.5",
"c_crashsource": null,
"c_crashtype": "NATIVE_CRASH",
"c_date1": "2020-03-20 00:00:00.000",
"c_date2": "2020-03-20 23:59:59.999",
"c_exceptiondes_type": "java.lang.ArrayIndexOutOfBoundsException",
"c_fwversion": "1.20.0.20190117",
"c_model": "Mi-4c",
"c_platform": "ios",
"c_udid": "638c76de11cf4b0a9be61d90df396af1",
"i_day": 20,
"i_hour": 0,
"i_month": 3,
"i_period": 1,
"i_type": 1,
"i_week": 0,
"i_year": 2020,
"l_count": 1,
"l_createtime": 1585041126408,
"l_date1": 1584633600000,
"l_date2": 1584719999000,
"l_maxtime": 1584699921860,
"l_updatetime": 1585041126408
</pre>

**Comment by zjfplayer** [comment]
cluster.log is in [https://github.com/zjfplayer/EsError](url)

**Comment by zjfplayer** [comment]
The time point of the first request error was around 12:14, and then we adjusted some index configurations:
<pre>
1. curl -XPUT "localhost:9201/[index_name]/_settings?pretty" -d '{
  "index" : {
  "number_of_replicas" : 0 
  }
}'
2.curl -XPUT "localhost:9201/[index_name]/_settings?pretty" -d '{
  "index" : {
  "translog.flush_threshold_size" : "4g" 
  }
}'
3.curl -XPUT "localhost:9201/[index_name]/_settings?pretty" -d '{
  "index" : {
  "refresh_interval" : "30s" 
  }
}'
</pre>
Then at 19:17, the same error was reported again.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by zjfplayer** [comment]
> Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

I use "BulkProcessor" instead and it's fine.
