### ISSUE TITLE
Enable adding unambiguous imports and optimizing imports for Java on the fly 

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#54144]
IntelliJ has two options:
 - add unambiguous imports on the fly
 - optimize imports on the fly

These are productivity boosts, so that we don't have to be notified that an unqualified symbol is not found, and then go through the bother of importing the symbol. When the symbol is unambiguous (e.g., `ShardFollowTaskExecutor`), IntelliJ can be configured to automatically add the import.

Similarly, IntelliJ can be configured to optimize imports on the fly, which helps reduce the frequency with which we run into unused imports, or imports that are not in the proper sort order.

These would be nice options to have automatically configured now that we are using Gradle to auto-configure IntelliJ.

**Comment by mark-vieira** [comment]
@pugnascotia I believe this is no longer relevant as we _do_ autoconfigure import rules now for IntelliJ, yes?

**Comment by mark-vieira** [comment]
I think we've configured managment of imports to the extent possible with IntelliJ so there's no further improvement to be made here.
