### ISSUE TITLE
add/remove clusters from tribe node dynamically

### ISSUE THREAD

**Issue by cleesmith** [elastic/elasticsearch#5415]
It would be nice to dynamically add or delete clusters on a tribe node, i.e. without
editing elasticsearch.yml and then having to stop/start the tribe node.

Is this possible ?

This is probably too much to wish for, but it would be nice if each node/cluster that "knew" it
was a part of a tribe could add/remove itself from the "tribe" (so to speak).

**Comment by clintongormley** [comment]
A potential problem here is what to do when merging cluster states with conflicts.

**Comment by raf64flo** [comment]
A solution could'nt be to fail the addition of the new cluster in the tribe in case of conflict at merge time?

**Comment by agonen** [comment]
Hi any update on this , we need this possibility.

Our use case is as follow:
  we capture network data in several sites and index into a local ES. we are using tribe to do federate queries across several sites . 
we would like to be able to add new site **without** effecting (restart) on tribe node.

any idea ? or we must do restart ?

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/21473
