### ISSUE TITLE
How to simulate long running search requests

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#54159]
For the development of the [`async_search` APIs](https://www.elastic.co/guide/en/elasticsearch/reference/master/async-search.html) we needed a way to simulate long running queries. For this purpose we wrote a [small module](https://github.com/jimczi/elasticsearch/tree/delayed_aggs_async_search/modules/delayed-aggs) that can simulate such long running queries on shards.  We used it for demo and monkey testing but we've also shared it with Kibana to help them integrating the new feature. While sharing a plugin/module is ok when developing a feature in master, we think that this module could be used outside of the development phase by other solutions to simulate long running queries.
A question was raised whether we want to provide this plugin/module in our distribution automatically in order to let users play with long running queries without requiring to index billions of documents.
The way we simulate long running queries can be discussed in a follow up, the current module uses `Thread.sleep` but it's an implementation details at this point. I opened this issue to discuss two points:

- Does that sound useful to provide a way for users to simulate long running queries easily in Elasticsearch.

- If so, how should we expose such functionality. 

We probably don't want this module to be available in production deployment so @jasontedor proposed that we ship the module automatically in the distribution only if the build is a snapshot build. 
Another option would be to provide such functionalities as an example plugin only available in our build.

**Comment by jimczi** [comment]
cc @lukasolson

**Comment by rjernst** [comment]
> we needed a way to simulate long running queries
> We used it for demo and monkey testing but we've also shared it with Kibana to help them integrating the new feature

Manual testing seems ok as a first step, but could we simulate the timing/triggering of the code to *act* as if a long query is running, but not actually consume real time (similar to how watcher manipulates Clock for testing triggering)?

>  @jasontedor proposed that we ship the module automatically in the distribution only if the build is a snapshot build. Another option would be to provide such functionalities as an example plugin only available in our build.

I think either approach is viable, and I do think we should have more fine grained control over the modules in each of our distributions. However, if Kibana is writing permanent tests for this feature, then a plugin would seem more appropriate, so we can test against released versions? I'm fine with either though.

**Comment by lizozom** [comment]
> @jasontedor proposed that we ship the module automatically in the distribution only if the build is a snapshot build. Another option would be to provide such functionalities as an example plugin only available in our build.

@lukasolson @tylersmalley and I discussed this recently. We'd probably want to have tests using slow searches for the builds of Kibana and Cloud, requiring this functionality to be available in production builds. Same type of aggregation can be also useful for diagnostics in support cases.

We thought of adding a "delayed aggregation" to ES, making it appear as a UI option only if some "Debug mode" toggle is enabled in Kibana. @jimczi  What do you think?

**Comment by elastic-jb** [comment]
@jim @jason @lizozom @lukasolson Can we walk through the risks we need to address for this capability to be in a production build for testing purposes?

**Comment by jasontedor** [comment]
Why do these need to be in production builds to test on Cloud? We deploy snapshots to staging on a nightly basis.

**Comment by lizozom** [comment]
@tylersmalley @spalger remember we talked about it? Can you explain why we prefer to have the delayed aggregations in production builds?

**Comment by spalger** [comment]
I think it's mostly for simplicity in our testing and ease of implementation. Being able to rely on the `delay` aggregation makes it much easier to integrate this functionality into Kibana and our tests as we need to support this at several levels in Kibana to actually use it.

Our functional tests are designed to run, as much as possible, against production instances of Kibana and as such it would be great if there was a way for end-users to enable some sort of "delay queries" feature that would inject `delay` aggregations. Then the functional tests could simply use this feature and folks wanting to test out slow-query support in their own installations, or when developing features, would all use the same functionality.

I think this would be ideal mostly because I think of the `delay` aggregation as totally harmless, but @elastic-jb's comment makes me wonder if I'm naive and there are risks in shipping the `delay` aggregation that I'm not aware of.

**Comment by dtuck9** [comment]
This would be really helpful for testing on Cloud.
