### ISSUE TITLE
[CI] TransportSearchActionTests.testShouldPreFilterSearchShards fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#54156]
The test failed several times since it was added in #53873:

- https://gradle-enterprise.elastic.co/s/x3ahgdw6zogaq
- https://gradle-enterprise.elastic.co/s/k6xvtno24ofeu
- https://gradle-enterprise.elastic.co/s/pjuhdq5dxngis

It reproduces with:
```
./gradlew ':server:test' --tests "org.elasticsearch.action.search.TransportSearchActionTests.testShouldPreFilterSearchShardsWithReadOnly" -Dtests.seed=B4C0C67AB112D4B5 -Dtests.security.manager=true -Dtests.locale=ar-SA -Dtests.timezone=Australia/West -Dcompiler.java=13
```

Since it was added very recently I'm not going to mute it (I think that it will be fixed soon).

**Comment by tlrx** [comment]
@jimczi it failed 3 times yesterday on master so if you don't have the time to look at it I can mute it straightforward.

**Comment by jimczi** [comment]
Thanks @tlrx , I am on it but let's mute since it fails relatively often.
