### ISSUE TITLE
Allow keystore command to add / remove an arbitrary number of settings at the time

### ISSUE THREAD

**Issue by nachogiljaldo** [elastic/elasticsearch#54191]
**Describe the feature**:
The keystore command allows adding/removing settings one at the time. However, when the number of settings grows this can take quite a while.

It would be great if it was possible to add and/or remove more than one setting at the time so only one JVM had to be initialized. That would cut quite a bit the startup time.

cc @jasontedor

**Comment by jasontedor** [comment]
The `remove` command already supports removing more than one key per invocation.
