### ISSUE TITLE
Query by width/height or area of a geo-shape

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#54218]
When running a `_search` for individual documents, it would be useful if ES could filter out documents where its `geo_shape` are smaller than a given size.  (e.g. ideally by width/height in webmercator meters, but lat/lon delta could work as well).

The reason for this is that often times a client issues an ES-query in order to display the shapes at a given scale. If that scale is small enough (ie. zoomed out), features smaller than a pixel do not need to be included.

Including in the search-result documents that the recipient then will filter out, adds noise to the ES-response. These unnecessary documents also count to the `index.max_result_window` search limit, potentially hiding less relevant results.

This would be relevant for the Kibana Maps application, since it performs scale-based queries. This is especially relevant for vector-tiling of ES search-results (https://github.com/elastic/kibana/issues/58519). When features are too small, they will be omitted from the tile anyway.

@giladgal @nknize @alexfrancoeur

**Comment by giladgal** [comment]
The ask makes sense to me. It might be useful to include it in a query that gets all shapes that are bigger than a certain minimum threshold and within given geo bounds.

**Comment by nknize** [comment]
This was discussed in the full stack geo meeting. One way to do this would be to have something in Lucene akin to term vectors but for spatial geometries. At index time we compute the area, perimeter, etc of tessellated triangles and store them in a spatial term vector. Having this granularity would make it easier for us to compute things like area overlap, or geometric clipping, as we would be doing this on the individual triangle.

A shorter / "easier" solution might be to offer a `geo_attribute` enrichment processor that computes and stores this information in a `geo_attribute` object field.

**Comment by iverase** [comment]
With the introduction of painless support for geo_shape fields on #72886, this can now be achieved by using runtime fields. For example:

```

GET /example/_search
{
  "size": 10,
  "fields": [
    "width",
    "heigth"
  ],
  "runtime_mappings": {
    "width": {
      "script": """
         GeoBoundingBox bbox = doc['location'].getBoundingBox();
         emit(bbox.bottomRight().lon - bbox.topLeft().lon);
       """,
      "type": "double"
    },
    "heigth": {
      "script": """
         GeoBoundingBox bbox = doc['location'].getBoundingBox();
         emit(bbox.topLeft().lat - bbox.bottomRight().lat);
       """,
      "type": "double"
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "width": {
              "lte": 1
            }
          }
        },
        {
          "range": {
            "heigth": {
              "gte": 1
            }
          }
        }
      ]
    }
  }
}
```

The computation of distances is left to the user as that can be done in several ways.
