### ISSUE TITLE
 ILM warm phase is stuck in the segment-count step, but no error log output

### ISSUE THREAD

**Issue by zhousPole** [elastic/elasticsearch#54247]
(elasticsearch 6.8.0)
   I am using ilm management index,shrink and forcemerge are configured during the warm phase and max_num_segments configured to 1.The index is stuck in a segment-count step, however, changing the log level to trace, background without any error log output, The query is forcemerge the task is empty, my index always has a part shard can not complete. but when i remove the shrink action of warm phase, index can go to the next stage normally.
  My suspicion is that when the shrink is completed shard, it redistributes, causing some of the shard to be migrated to other nodes, but forcemerge does not perform at other nodes,
 The final part of the shard can not be completed forcemerge, leading ilm to wait indefinitely for the segment-count step, Is that possible?
  What if shrink affected forcemerge, Then warm phase how to configure shrink and forcemerge, at the same time because after configuration at the same time index may always wait in segment-count steps.

**Comment by dakrone** [comment]
This was already fixed by https://github.com/elastic/elasticsearch/pull/43246, which fixed https://github.com/elastic/elasticsearch/issues/43245

**Comment by dakrone** [comment]
I'm going to close this since it's already been resolved.
