### ISSUE TITLE
Exec failure of reindex from remote cluster

### ISSUE THREAD

**Issue by CoderViking** [elastic/elasticsearch#54243]
**Elasticsearch version (bin/elasticsearch --version):** 7.6.1

**JVM version (Oracle Jave -version):** 8

**OS version :** Centos 7.6

**Description of the problem including expected versus actual behavior:**
Executing reindex from remote cluster with a slice value of '10' 

**results in an error:** 
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: reindex from remote sources doesn't support slices > 1 but was [10];".

The API documentation tells me that I can fill in a value equal to the number of shards

**Steps to reproduce:**

 ``` 
POST _reindex?slices=10
{
  "source": {
    "remote": {
      "host": "http://oldhost:9200",
      "username": "user",
      "password": "pass"
    },
    "index": "source",
    "query": {
      "match": {
        "test": "data"
      }
    }
  },
  "dest": {
    "index": "dest"
  }
}
```

**Error Message:**

    "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: reindex from remote sources doesn't support slices > 1 but was [10];"

**Comment by geekpete** [comment]
Seems like we could add mention of this limitation in these pages:
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/reindex-upgrade-remote.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/reindex-upgrade.html

The docs for Reindex do have a mention here, that neither manual nor automatic slicing is not supported for Reindex from remote:
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-reindex.html#reindex-from-remote

`"Reindexing from remote clusters does not support manual or automatic slicing."`

I think we can improve the documentation here to mention this limitation more clearly and probably in more places.
