### ISSUE TITLE
Rollup job fails silently after the first page is indexed

### ISSUE THREAD

**Issue by jbogp** [elastic/elasticsearch#54261]
**Elasticsearch version** : 7.4.2

**Plugins installed**: None

**JVM version** : OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9

**OS version**: CentOS Linux release 7.7.1908 (Core)

**Description of the problem including expected versus actual behavior**:
Rollup fails silently after the first page indexed, subsequent triggers do not go forward in the events, leaving only Rollups indexed = The page size defined at rollup creation. The total number of documents indexed does not increase (14647 in my case but there are more than 100k in total)

Every trigger after that increases the "search_failures" in the rollup json but no error are visible in ES logs.

Dump of the rollup config after 42 triggers
```json
{
  "config": {
    "id": "5m-filebeat",
    "index_pattern": "filebeat-*",
    "rollup_index": "5m-filebeat",
    "cron": "0 * * * * ?",
    "groups": {
      "date_histogram": {
        "fixed_interval": "5m",
        "field": "@timestamp",
        "delay": "1d",
        "time_zone": "UTC"
      },
      "terms": {
        "fields": [
          "json.action",
          "json.affected_package",
          "json.agency_country",
          "json.agency_erp_id",
          "json.agency_kind",
          "json.agency_language_id",
          "json.agency_language_name",
          "json.agency_name",
          "json.contract_country_code",
          "json.contract_country_name",
          "json.contract_package",
          "json.erp_test",
          "json.contract_status",
          "json.image_provider",
          "json.service",
          "json.site_is_model",
          "json.site_is_published",
          "json.site_is_trial",
          "json.site_language_id",
          "json.site_language_name",
          "json.site_status",
          "json.site_template",
          "json.site_template_name",
          "json.user_language_id",
          "json.user_language_name"
        ]
      }
    },
    "metrics": [],
    "timeout": "20s",
    "page_size": 10000
  },
  "status": {
    "job_state": "started",
    "current_position": {
      "@timestamp.date_histogram": 1539696900000,
      "json.action.terms": "COLLECTION_BOUGHT",
      "json.affected_package.terms": null,
      "json.agency_country.terms": null,
      "json.agency_erp_id.terms": 22522,
      "json.agency_kind.terms": 10,
      "json.agency_language_id.terms": 1,
      "json.agency_language_name.terms": "Français",
      "json.agency_name.terms": "",
      "json.contract_country_code.terms": "FR",
      "json.contract_country_name.terms": "France",
      "json.contract_package.terms": "",
      "json.contract_status.terms": 10,
      "json.erp_test.terms": 0,
      "json.image_provider.terms": "getty_1",
      "json.service.terms": null,
      "json.site_is_model.terms": 0,
      "json.site_is_published.terms": 0,
      "json.site_is_trial.terms": 1,
      "json.site_language_id.terms": 1,
      "json.site_language_name.terms": "Français",
      "json.site_status.terms": 10,
      "json.site_template.terms": 5,
      "json.site_template_name.terms": "",
      "json.user_language_id.terms": 1,
      "json.user_language_name.terms": "Français"
    },
    "upgraded_doc_id": true
  },
  "stats": {
    "pages_processed": 1,
    "documents_processed": 14647,
    "rollups_indexed": 10000,
    "trigger_count": 41,
    "index_time_in_ms": 5151,
    "index_total": 1,
    "index_failures": 0,
    "search_time_in_ms": 13582,
    "search_total": 1,
    "search_failures": 41
  }
}
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a rollup with the following request 
```json
PUT _rollup/job/5m-filebeat
{
  "id": "5m-filebeat",
  "index_pattern": "filebeat-*",
  "rollup_index": "5m-filebeat",
  "cron": "0 * * * * ?",
  "page_size": 10000,
  "groups": {
    "date_histogram": {
      "interval": "5m",
      "delay": "1d",
      "time_zone": "UTC",
      "field": "@timestamp"
    },
    "terms": {
      "fields": [
        "json.action",
        "json.affected_package",
        "json.agency_country",
        "json.agency_erp_id",
        "json.agency_kind",
        "json.agency_language_id",
        "json.agency_language_name",
        "json.agency_name",
        "json.contract_country_code",
        "json.contract_country_name",
        "json.contract_package",
        "json.erp_test",
        "json.contract_status",
        "json.image_provider",
        "json.service",
        "json.site_is_model",
        "json.site_is_published",
        "json.site_is_trial",
        "json.site_language_id",
        "json.site_language_name",
        "json.site_status",
        "json.site_template",
        "json.site_template_name",
        "json.user_language_id",
        "json.user_language_name"
      ]
    }
  }
}
```
 2. Start the rollup job
 3. After the first trigger, subsequent triggers won't index anymore documents

**Provide logs (if relevant)**:

**Comment by jbogp** [comment]
Actually upon further investigation, I found out that removing all numerical fields from the `terms` list makes to rollup behave normally.
Numerical fields should be added in the histogram category not terms.

**Comment by polyfractal** [comment]
@jbogp Was just about to reply to this :)  Glad you fixed your problem, although that still sounds buggy to me... numerics _should_ work with the terms aggregation.  I'll investigate and open a subsequent bug report.  Thanks for raising this!

Regarding logs, there should be an error log somewhere if the search_failures counter is incrementing.  You'll probably need to track down the node that's running the rollup job to check the search failure there.  You can find the node using the [Tasks API](https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html), look for the node running a Rollup task.  And then check those logs.

As an aside, we know this is a real pain: there's a todo to expose the "most recent error" in the stats somehow, so that you don't have to go digging through logs when something goes wrong.

**Comment by jbogp** [comment]
@polyfractal Thank you for replying, I agree it is a bit buggy, have you been able to reproduce it? Also I'll point out that the UI on kibana to create rollup jobs actually shows you the numerical fields of your index when creating the "terms" section (whereas it doesn't show the keyword fields in the histogram section), so it feels like it's definitely supposed to work :)

Hope this helps !
