### ISSUE TITLE
Unknow Plugin Error When Install Plugin

### ISSUE THREAD

**Issue by bigshans** [elastic/elasticsearch#54318]
**Elasticsearch version** (`bin/elasticsearch --version`):7.6.1

**Plugins installed**:  none

**JVM version** (`java -version`):1.8.0_242

**OS version** (`uname -a` if on a Unix-like system): Debian 9

I tried installing [ik](https://github.com/medcl/elasticsearch-analysis-ik) using elasticsearch-plugin. I used the command `/ usr / share / elasticsearch / bin / elasticsearch-plugin install. / Elasticsearch-analysis-ik-7.6.1.zip` but got the result` ERROR: Unknown plugin ./elasticsearch-analysis-ik-7.6.1 .zip`. I had to try to decompress and install the plugin, and the plugin worked normally. I don't know what went wrong, I hope you guys have a look.

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
