### ISSUE TITLE
Failures in "qa:mixed-cluster:v7.8.0#mixedClusterTest" tests

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#54313]
We've had several failures from the `:qa:mixed-cluster:v7.8.0#mixedClusterTest` in a short period. Two examples are:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+bwc/4543/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+bwc/4542/console

**Comment by dnhatn** [comment]
@stu-elastic I think this is related to https://github.com/elastic/elasticsearch/pull/54008. It wasn't backported but the wire version is 7.8.0 already. We need to backport that PR to 7.x or revert the change on master.

**Comment by original-brownbear** [comment]
I opened https://github.com/elastic/elasticsearch/pull/54321 to fix the version constant for now to get BwC tests unblocked.

**Comment by stu-elastic** [comment]
Thanks, I'm backporting now.
