### ISSUE TITLE
Edge-Ngram with Whitespace Tokenizer 

### ISSUE THREAD

**Issue by cawoodm** [elastic/elasticsearch#54341]
It seems to be impossible today to create an edge-ngram tokenizer which only tokenizes on whitespace so that given `hel.o wo/rld` we get the tokens `he`, `he.`, `hel.`, `hel.o`, `wo`, `wo/`, `wo/r`, `wo/rl`, `wo/rld`.

The problem seems to be that the `whitespace` setting breaks on non-whitespace as the documentation says:
> Elasticsearch will split on characters that don’t belong to the classes specified. 

If I have understood this correctly we need a `nonwhitespace` setting:

```
    "tokenizer": {
        "token_chars": ["nonwhitespace"],
        "min_gram": "2",
        "max_gram": "20",
        "type": "edge_ngram"
    }
```

Workaround - this can be approached today by doing:
```
    "tokenizer": {
    "token_chars": ["letter", "digit", "punctuation", "symbol"],
    "custom_token_chars": ["="],
    "min_gram": "2",
    "type": "edge_ngram",
    "max_gram": "20"
}
```

The problem with this workaround is that it's a constant battle to add characters to `custom_token_chars` if they (like `=`) are not included in `punctuation` or `symbol`.

**Comment by cawoodm** [comment]
It's also a question as to what the `whitespace` option is supposed to do: include only spaces as tokens??

```
POST /_analyse
{
    "tokenizer": {
        "token_chars": ["whitespace"],
        "min_gram": "2",
        "max_gram": "20",
        "type": "edge_ngram"
    },
    "text": "hel.o wor/ld"
}
```
result:
```
{
    "tokens": []
}
```

**Comment by cbuescher** [comment]
> edge-ngram tokenizer which only tokenizes on whitespace so that given `hel.o wo/rld` we get the tokens `he`, `he.`, `hel.`, `hel.o`, `wo`, `wo/`, `wo/r`, `wo/rl`, `wo/rld`.

Why can't you use a `whitespace` tokenizer and an `edge-ngram` filter?
```
PUT test-index
{
  "settings": {
    "analysis": {
      "filter": {
        "my_filter": {
          "type": "edge_ngram",
          "min_gram": 2,
          "max_gram": 20
        }
      }
    }
  }
}


POST test-index/_analyze
{
  "tokenizer": "whitespace",
  "filter": ["my_filter"], 
  "text": "hel.o wo/rld"
}
```
>  question as to what the `whitespace` option is supposed to do: include only spaces as tokens??

That configuration is a bit weird, but yes, thats what it does. E.g. 
```
UT test-index
{
  "settings": {
    "analysis": {
      "tokenizer": {
        "my_tokenizer": {
          "token_chars" : ["whitespace"],
          "type": "edge_ngram",
          "min_gram": 1,
          "max_gram": 20
        }
      }
    }
  }
}


POST test-index/_analyze
{
  "tokenizer": "my_tokenizer",
  "text": "Quick brown fox"
}
```

returns two whitespace token. One can argue about how useful that is but the character class is usually used in conjunction with something else.

Hope this helps. For future request like this please use the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask any follow up questions in the forum instead. Many thanks.

**Comment by cawoodm** [comment]
Thanks, your help has enabled me to solve the problem.
I've posted my results in the forum on the [original question](https://discuss.elastic.co/t/elastic-edge-ngram-with-whitespace-word-breaker/225280).
