### ISSUE TITLE
Document partly updating strategy

### ISSUE THREAD

**Issue by kaihekaihe** [elastic/elasticsearch#54378]
Index has about 600+ columns，average size of doc is relatively big, Lucene firstly obtain the original doc from disk and then merge the old and the updating coulmns to a new one,finally flush to disk.
The dsik io usage rate of our 150+ nodes always reach nearly 99% while partly updating requests call frequently.

I want to optimize the partly updating strategy, only partly columns instead of all are obtained and merge into a new one while partly updating request calls,in purpose of cuting down disk io usage rate.
is there any suggestions?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
