### ISSUE TITLE
Multi-version testing for cross cluster search

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#54375]
I think we need a new qa style project to test cross cluster search where the versions differ. I think scenarios like these are pretty common:

Coordinating Node | Remote Cluster Gateway Node | Data Node
------------------|-----------------------------|----------
7.7.0             | 7.3.0                       | 7.3.0
7.3.0             | 7.7.0                       | 7.7.0
6.8.7             | 7.7.0                       | 7.7.0
7.7.0             | 6.8.7                       | 6.8.7

And scenarios like this are common but transient:

Coordinating Node | Remote Cluster Gateway Node | Data Node
------------------|-----------------------------|----------
7.7.0             | 7.3.0                       | 7.7.0
7.7.0             | 7.7.0                       | 7.3.0
7.7.0             | 6.8.7                       | 7.7.0
7.7.0             | 7.7.0                       | 6.8.7

If you read our remote clusters [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/modules-remote-clusters.html) it look like we support "chains" of different versions, like:

Coordinating Node | Remote Cluster Gateway Node | Data Node
------------------|-----------------------------|----------
7.7.0             | 7.3.0                       | 6.8.7
6.8.7             | 7.3.0                       | 7.7.0
8.0.0             | 7.99.0                      | 6.8.7
6.8.7             | 7.99.0                      | 8.0.0

The trouble with those chains is that the testing burden is going to get pretty nuts. Supporting three different versions just makes the number of tests super high because n^3 is bigger than n^2. Worse, because you can "chain" you can get transitively supported version like those last two lines in the table above where an 8.0.0 node talks to a 6.8.7 node *through* a 7.99.0 node.

The thing is, a lot of this *works* now because of the way we've implemented serialization and cross cluster search. We always deserialize on the gateway node and reserialize. So we get both layers of compatibility applied. We just don't test it. And we should. But *which* verions we should test is a complete mystery to me.

**Comment by nik9000** [comment]
I'm going to take the next step in this: document the scenarios that we expect to work.

**Comment by nik9000** [comment]
> The trouble with those chains is that the testing burden is going to get pretty nuts. Supporting three different versions just makes the number of tests super high because n^3 is bigger than n^2. Worse, because you can "chain" you can get transitively supported version like those last two lines in the table above where an 8.0.0 node talks to a 6.8.7 node _through_ a 7.99.0 node.

Point of clarification: in #58120 we explicitly forbade the kinds of chains I called out in the last table. They might work on accident but we don't test them. You shouldn't use them. We also documented that the "common but transient" cases should only occur during an upgrade.

**Comment by javanna** [comment]
We have restricted the cross-version compatibility for CCS to the previous minor, and expanded the tests coverage with #84481 . That should be enough, closing.
