### ISSUE TITLE
auto date histogram error in mixed version cluster

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#54382]
While working on the backport to #54161 I discovered a new and unique error that is almost certainly my fault:
```
        "failures" : [
          {
            "shard" : 1,
            "index" : "test",
            "node" : "OmBZbfyERlKeciJo0vK2QA",
            "reason" : {
              "type" : "transport_serialization_exception",
              "reason" : "Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]",
              "caused_by" : {
                "type" : "exception",
                "reason" : "unknown rounding id [85]"
              }
            }
          }
        ]
```

**Comment by nik9000** [comment]
This isn't related to the change I'm backporting but the new test that I'm writing discovers it. The failure comes when running against a 6.8.8 mixed version cluster.

**Comment by nik9000** [comment]
I'm totally unsure which version fix has this bug. I'll figure it out on Monday when I can concentrate on it properly.

**Comment by imotov** [comment]
@nik9000 have you ever figured this one out?

**Comment by nik9000** [comment]
Looks like I got it in #54447.  Sorry for the trouble!
