### ISSUE TITLE
Optimize date histogram on non-fixed timezones

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#54403]
Today the `date_histogram` aggregation rewrites time zones into fixed offsets if the data in the shard is within a single transition. This optimization ensures that we don't need to check time zone transitions on every document.

While this optimization handles most of the cases, the alternative when it is not applicable is very slow since it requires to check for time zone transitions on every document. 

For time-based indices most of the shards should have a single transition (DST happens twice a year) and few shards should have 2 (before and after DST). 
For the latter, it should be possible to avoid the costly checks by pre-filling the transitions from the possible values in the shard directly in milliseconds since epoch. 
This would allow to resolve such transitions directly with numerics (longs) rather than costly java time object.

**Comment by nik9000** [comment]
I spent some time playing with this today. Good news:
1. `java.time` exposes everything we need.
2. We absolutely can make this faster by building a shard-local `lookup` that do a no single binary search per date on an array as big as all of the transitions that are in the shard - usually 1 or 2. We wouldn't even need to allocate any objects.
3. We have a ton of lovely test cases in `RoundingTests` for "funny" cases.
4. We can always drop back to the `java.time` implementation if we don't like ours.
5. We could probably remove `shardRounding` entirely. Not in the first PR, but eventually.
6. I have some performance tests that reproduce exactly how slow this is.

The bad news:
1. Daylight savings time is hard.
2. Rounding around it is even harder
3. We'd need to plumb our `lookup` into the aggregator.
4. I'm not 100% sure my `lookup` isn't slower if you have to round a single date. It might be. It might not be.

Anyway, just an update while I'm thinking about it.

**Comment by nik9000** [comment]
This has been on my list for a while and I even have a little of a prototype but I keep getting distracted.

**Comment by nik9000** [comment]
I think I have it! PR coming soon!

**Comment by nik9000** [comment]
> I think I have it! PR coming soon!

Er, now that I think about it, in a few days! I'm sure I can make a faster rounder. Plugging it in will take some time. But I think the rounding tests pass with my rounder now!

**Comment by nik9000** [comment]
Update:

Rounding dates on a shard that contained a daylight savings time transition is currently something like 500% o 1000% slower than when a shard contains dates only on one side of the DST transition. And it makes a ton of short lived garbage. I have an implementation that benchmarks around 60% to 25% slower. And doesn't generate any garbage per search hit.

This comes up about twice a year and bothers folks for the same amount of time as their dashboards are long. So a week long dashboard will be slow for a week after the daylight savings time transition.

**Comment by nik9000** [comment]
Closed by #55559.
