### ISSUE TITLE
Well-defined order in which indexes included in a snapshot are snapshotted

### ISSUE THREAD

**Issue by shikhar** [elastic/elasticsearch#54464]
**Describe the feature**:

We have a pattern of using a "sidecar" index containing timestamps (physical timestamps or or logical timestamps like Kafka offsets) relevant to the indexing state of an Elasticsearch index.

To ensure all the relevant data represented by the sidecar index in the snapshot is present once the snapshot is restored, and indexing activity is able to resume in a way that ensures "at-least-once" indexing, we need to be able to rely on the order in which the snapshot is performed.

E.g. if requesting a snapshot for the indices e.g. `$index-sidecar,$index`, have `$index-sidecar` be snapshotted first, then `$index`.

Currently, the order in which indices are snapshotted is not specified in the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-take-snapshot.html). It would be great to know if this is the case already!

**Comment by jasontedor** [comment]
There are no guarantees if the kind that you are looking for. At the highest level, the shards in a single snapshot request are snapshotted concurrently. The primary shards of the indices in a snapshot request could be allocated on different nodes. The nodes will not receive and act on the requests to start snapshots for the shards they are responsible for in any well-defined order, nor do the snapshots finish in a well-defined order as there are many factors here such as the size of the incremental data to be transferred, and the behavior of remote systems where a snapshot is being made too.

**Comment by shikhar** [comment]
Thanks @jasontedor, what about custom index metadata (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html)? Is this state captured before or after the snapshot?

**Comment by jasontedor** [comment]
@shikhar It's captured when finalizing the snapshot.
