### ISSUE TITLE
EQL: Implement string function

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#54465]
Part of #51556
https://eql.readthedocs.io/en/latest/query-guide/functions.html#string

Probably the most straightforward function in EQL.

#### Function behavior
Validation requirements:
* One exact argument (isExact check)

**null** behavior:
* this function will never return null
* obj.toString()

**Comment by astefan** [comment]
What is the main use case for this function?

**Comment by rw-access** [comment]
The `string` and `number` functions #54471 were added to EQL to facilitate comparisons across types.

The test examples were clearly silly, but still tested the function with uncomplicated examples. Ideally, both functions will be rarely used, and every field transformation is done at index time. One use case within ES, is for functions to fill in those gaps when data wasn't ingested right, or inconsistent to other , or was ingested for particular reasons.
