### ISSUE TITLE
Getting array_index_out_of_bounds_exception while set require_field_match=false

### ISSUE THREAD

**Issue by zhuzhu9651** [elastic/elasticsearch#54476]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 
6.5.4

**Plugins installed**: No

**JVM version** (`java -version`): 
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 
centos7.2

**Description of the problem including expected versus actual behavior**: 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. query: 
{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "nested": {
                  "query": {
                    "term": {
                      "mobile.number": {
                        "value": "123456",
                        "boost": 1
                      }
                    }
                  },
                  "path": "mobile",
                  "ignore_unmapped": false,
                  "score_mode": "sum",
                  "boost": 1
                }
              }
            ],
            "boost": 1
          }
        },
        {
          "terms": {
            "_id": [
              "09a3b559bdd366e93d008cbee3b7ba72",
              "1e45d652ed7ca22eb2b6d9d6c165e591",
              "24d3d3fee40729e91eae191005bbc5f9",
              "48a5a3f43399f7b19f4b034bc69169e6",
              "568442155a583178d36788c4583bb1a3",
              "6a084f02719c77bafb9656b445574ac1",
              "6f3ed5f6b3acb67bb056dbf9b26b2f0f",
              "7bd9044f40fcd3bcb24d5b07ffbe112a",
              "8df1a548ab61c8fabe1089ccbdd593b6",
              "e11b2416a81ca9be3691483ab852a3ac",
              "f01c9af002a78b2666e2b96bada0618f"
            ],
            "boost": 1
          }
        }
      ],
      "boost": 1
    }
  },
  "highlight": {
    "fields": {
      "mobile.number": {
        "pre_tags": [
          "<span class='highlight_hit'>"
        ],
        "post_tags": [
          "</span>"
        ],
        "require_field_match": false
      }
    }
  },
  "size": 1
}
 2. If I set require_field_match=false, then the es report:
{
	"took": 5,
	"timed_out": false,
	"_shards": {
		"total": 9,
		"successful": 8,
		"skipped": 0,
		"failed": 1,
		"failures": [{
			"shard": 0,
			"index": "user_info",
			"node": "uZZTqza_Q7KbTmO5wBm75w",
			"reason": {
				"type": "array_index_out_of_bounds_exception",
				"reason": "Index 24 out of bounds for length 24"
			}
		}]
	},
	"hits": {
		"total": 1,
		"max_score": 16.434092,
		"hits": []
	}
}
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
This looks very similar to https://github.com/elastic/elasticsearch/issues/38170 and https://github.com/elastic/elasticsearch/issues/37525 to me, which should be fixed in 6.7.2 by https://github.com/elastic/elasticsearch/pull/41275. Can you try this scenario with a later version, either 6.7.2 or up or one of the 7.x versions and see if you still get the exception?

**Comment by zhuzhu9651** [comment]
Thank you. I updated to 6.7.2, and the problem is solved.

**Comment by cbuescher** [comment]
Thanks for the feedback, closing then.
