### ISSUE TITLE
Build task :distribution:packages:buildNoJdkRpm fails

### ISSUE THREAD

**Issue by christianskovholm** [elastic/elasticsearch#54491]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: None

**JVM version** (`java -version`): OpenJDK 13

**OS version** (`uname -a` if on a Unix-like system):

Linux christian-ZenBook-UX434FAC-UX433FAC 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Expected behavior is that the build process executes successfully and places the build files into the build directory.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Run gradle assemble in the elasticsearch dir

**Provide logs (if relevant)**:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:packages:buildNoJdkRpm'.
> No signature of method: static org.gradle.util.DeprecationLogger.whileDisabled() is applicable for argument types: (com.netflix.gradle.plugins.rpm.RpmCopyAction$_startVisit_closure1) values: [com.netf
lix.gradle.plugins.rpm.RpmCopyAction$_startVisit_closure1@547632dc]
```

**Comment by martijnvg** [comment]
Can you share whether you made modifications to your local clone and if not, from what git branch you're running the gradle command?

**Comment by christianskovholm** [comment]
Pretty sure i used master. However, i tried to clone again and then i received an error saying i needed to update to Gradle 6.3. I upgraded, and then the build went fine.
