### ISSUE TITLE
[ML] Excessive precision in analytic model memory limit estimate from _explain endpoint

### ISSUE THREAD

**Issue by peteharverson** [elastic/elasticsearch#54506]
When obtaining an estimate for the model memory limit for a data frame analytics job, the `explain` endpoint `/_ml/data_frame/analytics/_explain` returns the estimate in KB with very high precision. This often appears overly precise to the user, for example when viewed in the Create job flyout in the ML UI:

![image](https://user-images.githubusercontent.com/7405507/78038217-7ed47c80-7364-11ea-87c4-d9e67c2880a8.png)

Could some sensible rounding be applied to the estimate, or return it in `MB` rather than `KB`.

**Comment by droberts195** [comment]
The fix for this may not be in UI code.  It may be better to do it in the C++.  I opened elastic/ml-cpp#1110 for discussion.
