### ISSUE TITLE
Inconsistent errors in bulk API

### ISSUE THREAD

**Issue by s-nel** [elastic/elasticsearch#54549]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: []

**JVM version** (`java -version`): Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**:

The bulk API may respond with errors per bulk request item, or it may fail the entire request, and it's unclear and undocumented when each might happen. The structure of bulk response for failed items is AFAICT completely undocumented. The only mention about the response structure I found [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) is:

> The response to a bulk action is a large JSON structure with the individual results of each action performed, in the same order as the actions that appeared in the request. The failure of a single action does not affect the remaining actions.

As an example of inconsistent behavior in this respect if I attempt to index a document into an index that does not exist (and automatic index creation is disabled) the bulk response will look like:

```json
{
    "took": 0,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "bar-4",
                "_type": "_doc",
                "_id": null,
                "status": 404,
                "error": {
                    "type": "index_not_found_exception",
                    "reason": "no such index [bar-4]",
                    "resource.type": "index_expression",
                    "resource.id": "bar-4",
                    "index_uuid": "_na_",
                    "index": "bar-4"
                }
            }
        }
    ]
}
```

however if I try to index into an alias that does not have a write alias defined I get an overall request failure, even though other bulk request items _could_ have been processed:

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "no write index is defined for alias [bar]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "no write index is defined for alias [bar]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
    },
    "status": 400
}
```

I would expect missing "index not found" and "no write index for an alias" to be treated the same: the request would succeed, but the individual response item would show the failure. Both errors are predicated on server state. It contradicts the documentation that says a failure of a single action does not affect the remaining actions.

As a further example of inconsistency, consider when a mapping is `dynamic: strict`, and using the bulk API I attempt to index a field that is not in the mapping:

```json
{
    "took": 1,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "foo",
                "_type": "_doc",
                "_id": "zC4WM3EBVwMmsGyRIIsp",
                "status": 400,
                "error": {
                    "type": "strict_dynamic_mapping_exception",
                    "reason": "mapping set to strict, dynamic introduction of [otherfield] within [_doc] is not allowed"
                }
            }
        }
    ]
}
```

As part of this issue, can we:
1. Document the bulk API response object and expectations for when the entire request will fail
2. Make item-level errors consistent with documentation

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `PUT /bar-1`
 2. `PUT /bar-2`
 3. Create an alias that points to two indices
   ```
   POST /_aliases
   {
     "actions": [
       { "add": { "index": "bar-1", "alias": "bar" } },
       { "add": { "index": "bar-2", "alias": "bar" } }
     ]
   }
   ```
4. Attempt to index a document using `bar` alias
   ```
   POST /_bulk
   { "create": { "_index": "bar" } }
   { "message": "hello, world" }
   ```

**Provide logs (if relevant)**:

**Comment by martijnvg** [comment]
Thanks for opening this issue @s-nel. I agree that the no write alias error should be handled the same as the index not found error, since other items may have a different `index`.

**Comment by immon** [comment]
Another instance where this is manifested is a bulk request with document id longer than 512 bytes. Instead of per document status code the HTTP error is returned.


Example:
```
POST /_bulk
{ "index": { "_index": "foo", "_id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" } }
{ "message": "hello, world" }
{ "index": { "_index": "foo", "_id": "1" } }
{ "message": "goodbye, world" }
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: id [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] is too long, must be no longer than 512 bytes but was: 513;"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: id [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] is too long, must be no longer than 512 bytes but was: 513;"
  },
  "status" : 400
}
```
