### ISSUE TITLE
EQL: implicit boolean casting

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#54544]
EQL has two scenarios for values/functions involved in comparisons or logical expressions:
- `... where indexOf(file_name,"A") > 0`
- `... where pid>10000 and indexOf(file_name,"A")`

The first scenario compares the output of the function with a value and this works as is currently.
The second scenario assumes an implicit boolean casting of the functions' value comparison with NULL. As such, the second query could potentially be re-written as `where pid>10000 and indexOf(file_name,"A") != null` or `where pid>10000 and indexOf(file_name,"A") IS NOT NULL`.

I created this issue to establish a way forward: either handle the hidden/behind-the-scene `null` comparison or enforce (also in eql) an explicit `null` comparison.

Related to https://github.com/elastic/elasticsearch/issues/54419 as well.

**Comment by astefan** [comment]
Preference for enforcing a query of the type `where indexOf() > 0` meaning users should be explicit on the result of the function.

**Comment by rw-access** [comment]
I think we've since removed all questionable implicit casting. Are we good to close this?
