### ISSUE TITLE
[CI] branch-consistency verifyVersions fails for master, 7.x, 7.7 and 7.6

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#54557]
The gradle tasks checks maven central and can see 7.6.2 is [available](https://search.maven.org/artifact/org.elasticsearch/elasticsearch/7.6.2/j) there and failed the task with:
```
18:15:14 Execution failed for task ':verifyVersions'.
18:15:14 > out-of-date released versions
18:15:14   Build considers versions unreleased, but they are released according to an authoritative source: [7.6.2]
18:15:14   The next versions probably needs to be added to Version.java (CURRENT doesn't count).
```

I think we need add 7.6.3 to both Version.java and bwcVersions files

Build scans:
* https://gradle-enterprise.elastic.co/s/tt7tck6rh4qtk
* https://gradle-enterprise.elastic.co/s/o2lzbhyowkrtm
* https://gradle-enterprise.elastic.co/s/7ptvbygcimcwe
* https://gradle-enterprise.elastic.co/s/dpe7u5ui4xj7g

**Comment by rjernst** [comment]
These failures happened before the version in 7.6 branch was bumped to 7.6.3, and they pass locally now, so the next run of the consistency check CI job should pass.

**Comment by BigPandaToo** [comment]
Happenning again:
https://gradle-enterprise.elastic.co/s/jh2pjbzwkad7u

**Comment by mark-vieira** [comment]
> Happenning again:
> https://gradle-enterprise.elastic.co/s/jh2pjbzwkad7u

This was temporary due to the 7.13 release and the 7.12 builds not being removed right away.
