### ISSUE TITLE
[CI] SamlIdentityProviderTests.testIdpInitiatedSso fails with "SERVICE_UNAVAILABLE/1/state not recovered / initialized"

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#54555]
A few methods in the class could fail with the same underlying reason of "SERVICE_UNAVAILABLE/1/state not recovered / initialized". The reason is that [registerServiceProvider](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/identity-provider/src/test/java/org/elasticsearch/xpack/idp/action/SamlIdentityProviderTests.java#L267) is called before [ensureGreen](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/identity-provider/src/test/java/org/elasticsearch/xpack/idp/action/SamlIdentityProviderTests.java#L76).

Sample error message:
```
:x-pack:plugin:identity-provider:test » org.elasticsearch.xpack.idp.action.SamlIdentityProviderTests » testIdpInitiatedSso (3.715s)
method [PUT], host [http://127.0.0.1:43027], URI [/_idp/saml/sp/ec%3Aabcdef%3A123456?refresh=true], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"}],"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"},"status":503}
org.elasticsearch.client.ResponseException: 
method [PUT], host [http://127.0.0.1:43027], URI [/_idp/saml/sp/ec%3Aabcdef%3A123456?refresh=true], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"}],"type":"cluster_block_exception","reason":"blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"},"status":503}
Open stacktrace
```

Build scans:
* https://gradle-enterprise.elastic.co/s/k44tuy33a6ab6
* https://gradle-enterprise.elastic.co/s/k44tuy33a6ab6

**Comment by jkakavas** [comment]
Solved in https://github.com/elastic/elasticsearch/pull/54215/files#diff-2d6e04d0396ee829c618397c58aae1b9R114, will close once #54215 is merged

**Comment by tvernum** [comment]
@jkakavas Your change was to the RestTestCase, but this failure is in the IntegTest case.
I think #54622 is the real fix.
