### ISSUE TITLE
Unable to create filtered alias with terms lookup

### ISSUE THREAD

**Issue by junjun-zhang** [elastic/elasticsearch#54550]
**Elasticsearch version** (`bin/elasticsearch --version`):
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 7.6.1, Build: default/deb/aa751e09be0a5072e8570670309b1f12348f023b/2020-02-29T00:15:25.529771Z, JVM: 13.0.2

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
`Linux  5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Index some documents:
```
POST _bulk
{"index":{"_index":"colors","_id":"1"}}
{"color":"blue"}
{"index":{"_index":"colors","_id":"2"}}
{"color":["red","green"]}
{"index":{"_index":"products","_id":"1"}}
{"id":"a","color":"red"}
{"index":{"_index":"products","_id":"2"}}
{"id":"b","color":"blue"}
```

 2. Create a filtered alias with terms lookup:
```
POST /products/_aliases/color2_products
{
  "filter": {
    "terms": {
      "color": {
        "index": "colors",
        "id": "2",
        "path": "color"
      }
    }
  }
}
```

 3. Get an error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "failed to parse filter for alias [color2_products]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to parse filter for alias [color2_products]",
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "async actions are left after rewrite"
    }
  },
  "status" : 400
}
```

**Comment by junjun-zhang** [comment]
not sure whether it's related to #54315

**Comment by joegallo** [comment]
I'm removing the `team-discuss` label from some older `Team:Data Management` issues -- we've had plenty of time to discuss them, but we haven't, so the label isn't serving its purpose. Feel free to delete this comment and/or re-add the `team-discuss` label.

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Comment by ahs53** [comment]
Hi @javanna , so it's not possible to create an alias filter with terms lookups?

**Comment by javanna** [comment]
@ahs53 correct. The filter would need to be executed implicitly for every query, and terms lookup requires fetching from a secondary index which is rather heavy (that's why the error says "async actions left after rewrite").
