### ISSUE TITLE
Add a consolidated source of health information for clusters

### ISSUE THREAD

**Issue by nachogiljaldo** [elastic/elasticsearch#54569]
**Describe the feature**:

Currently Elasticsearch provides an `/_cluster/health` endpoint that includes some information about the health of the cluster.

However, there are many more health data points that can be relevant and it would be very useful to have a consolidated point to fetch them.

Some things from the top of my mind:
- per node
  * memory usage
  * CPU usage
  * disk usage
  * task rejections
- ILM policies failing / succeeding
- certain index blocks that indicate problems
- SLM policies not running and/or failing
- nodes dropping the cluster

**Comment by nachogiljaldo** [comment]
cc @henningandersen

**Comment by dakrone** [comment]
We introduced something like this with the [health report](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/health-api.html) API, so I'm closing this as completed
