### ISSUE TITLE
Enable geo_distance and geo_bounding_box queries on geo_shape field type

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#54628]
Following the development in #48928, we should enable `geo_distance` and `geo_bounding_box` queries over `geo_shape` field type.

**Comment by hariseldon3141** [comment]
@iverase Excuse my ignorance, but how does this differ from #53468

**Comment by iverase** [comment]
@hariseldon3141 no problem as I can see where your confusion is coming from.

The only query supported by geo_shape field is currently the geo_shape query. In #53466 we added the capability of building geo distance queries on geo shape fields when using the current default indexing strategy which means that you can now build a geo_shape query using a CIRCLE shape (see #39237). 

In this change we proposed to be able to run geo_distance and geo_boulding_box queries over geo_shape fields as it currently only supports being executed over a geo_point field.

**Comment by Shubhangi2901** [comment]
Hi @iverase I would like to work on this issue

**Comment by iverase** [comment]
Hi @Shubhangi2901,

great, please feel free to open a PR addressing  the issue.

Thanks!

**Comment by Shubhangi2901** [comment]
Hi @iverase - Can you give me a little bit more context on what exactly needs be done for this issue?

I went over the code for geo_boundingbox queries and geo_distance queries and geo_shape field type and understand it, but now given a geo_shape field type, how am I expected to use the geo_distance concepts for it? I can think of a few ways which I am not sure are correct, but I am not sure if you already have thoughts on how you'd like this to be implemented.

**Comment by iverase** [comment]
Hi,

I will try :)

 First of all, mind you that last week there was a bit of refactoring going on in geo field mappers (https://github.com/elastic/elasticsearch/pull/55621). Now `geo_point` and `geo_shape` inherit from `AbstractGeometryFieldMapper`, which defines an `AbstractGeometryFieldType` which can generate geometry queries.

The idea for geo_distance and geo_bounding_box queries is to accept any field that is an instance of `AbstractGeometryFieldMapper`. In that case, we can build the query as a geometry query as defined in the interface. We are already doing something very similar in geo_shape queries:

https://github.com/elastic/elasticsearch/blob/eb0b2c8f6996ff90becc8875f20ac34b925f5795/server/src/main/java/org/elasticsearch/index/query/GeoShapeQueryBuilder.java#L203

hope it makes sense.

**Comment by iverase** [comment]
Hi @Shubhangi2901,

Do you have any update about this issue? Are you still working on it?

Thanks!

**Comment by Shubhangi2901** [comment]
Hi @iverase 

Sorry for not updating earlier - I was busy with a couple of other things that were taking precedence. 

I have made some progress on this issue now, and I am sharing a link to my PR with the initial progress on this issue:
https://github.com/elastic/elasticsearch/pull/58151

I describe what have I done till now in the PR, please take a look and let me know if I am on the right track - I'm figuring out next steps and will add more commits my PR soon.
