### ISSUE TITLE
can update use TransportBulkAction with a single item instead?

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#54626]
**Describe the feature**:
As index and delete use TransportBulkAction with a single item instead.
Can update  also use TransportBulkAction with a single item instead?

**Elasticsearch version** (`bin/elasticsearch --version`): master

**Comment by cbuescher** [comment]
Hi @weizijun! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
