### ISSUE TITLE
Updating/removing in-use repository results in 500 Internal Server Error

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#54637]
If you try and update or remove a repository while it's in use you get a reasonable exception message, `trying to modify or unregister repository that is currently used`, but the exception itself is an `IllegalStateException` which maps onto a `500 Internal Server Error`:

https://github.com/elastic/elasticsearch/blob/95a7eed9aa35f47b228e402508709b5bd6703cf4/server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java#L449

I think we should return a 4xx error instead, maybe `409 Conflict`, since this is not really an internal server error so much as a conflict between clients.

**Comment by original-brownbear** [comment]
This was fixed in https://github.com/elastic/elasticsearch/pull/56070
