### ISSUE TITLE
[CI] master/7.x release tests TransportPutAutoscalingPolicyActionIT fails with "unknown setting [xpack.autoscaling.enabled]"

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#54654]
## Issue

On **release tests only**, `TransportPutAutoscalingPolicyActionIT` fails with the message `java.lang.IllegalArgumentException: unknown setting [xpack.autoscaling.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`.

Example gradle report: https://gradle-enterprise.elastic.co/s/inpkmrheishha
Example jenkins report: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/1090/

This has been happening for about a day and may have to do with #54473.

## Reproduction line

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT.testNoOpPolicy" \
  -Dtests.seed=DD0A88851B625774 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=pt-BR \
  -Dtests.timezone=America/Santarem \
  -Dcompiler.java=13
```

Unfortunately, when I run this locally I get a message about a missing license key property, so I can't verify. When I remove the `-Dbuild.snapshot` lines, this test passes.

Since this isn't failing on PR builds or intake builds, I'm not going to mute just yet.

**Comment by jasontedor** [comment]
Closed by db572afda8cbead464e1bb1f08a028d4201e464d
