### ISSUE TITLE
[DOCS] Implement collapsible sections for nested objects in Elasticsearch APIs

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#54667]
We have created a stylesheet to make it easier to delineate nested objects in the API reference pages: https://github.com/elastic/docs/pull/1786

We have already implemented it in machine learning APIs like https://www.elastic.co/guide/en/elasticsearch/reference/master/get-dfanalytics-stats.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-put-job.html

It involves setting `[role="child_attributes"]` on the section that contains nested objects, then putting the objects in collabsible sections, which default to open for search purposes.

The following APIs contain nested objects and would likely benefit from this layout too:

- [x] [cluster reroute](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-reroute.html) #54851
- [x] [cluster stats](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-stats.html) #54739
- [x] [cluster nodes stats](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-stats.html) #54755
- [x] [get ccr stats](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-get-stats.html): https://github.com/elastic/elasticsearch/pull/54697
- [x] [get ccr follower stats](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-get-follow-stats.html): https://github.com/elastic/elasticsearch/pull/54697
- [x] [get follower info](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-get-follow-info.html): https://github.com/elastic/elasticsearch/pull/54697
- [x] [explore](https://www.elastic.co/guide/en/elasticsearch/reference/master/graph-explore-api.html) #55067
- [x] [create rollup jobs](https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-put-job.html): https://github.com/elastic/elasticsearch/pull/54690
- [x] [get rollup jobs](https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-get-job.html): https://github.com/elastic/elasticsearch/pull/54690
- [x] [put snapshot lifecycle policy](https://www.elastic.co/guide/en/elasticsearch/reference/master/slm-api-put-policy.html): https://github.com/elastic/elasticsearch/pull/54834
...

P.S.  The child_attributes stylesheet is not set in stone either.  If there are better colours or padding, input is welcome on https://github.com/elastic/docs/blob/master/resources/web/style/child_attributes.pcss

**Comment by patelvp** [comment]
Working on cluster reroute and explore. Hope nobody is looking into it.
