### ISSUE TITLE
Painless: Removing "lexer-hack" for scripting context free lexing and parsing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#54677]
In order to pre-parse a script and resolve the types and identifiers against different contexts, say to ensure a stored script compiles for some context (see: #27612), we'll need to resolve the ambiguities between types and identifiers.

Let's get the taxonomy of ambiguities listed here before we discuss solutions.

**Comment by jdconrad** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/56293
