### ISSUE TITLE
Support SNI on transport TLS connection

### ISSUE THREAD

**Issue by sventschui** [elastic/elasticsearch#54703]
**Describe the feature**:

The transport connection should support SNI when configured to use TLS

**Elasticsearch version** (`bin/elasticsearch --version`):

```
Version: 7.6.1, Build: default/rpm/aa751e09be0a5072e8570670309b1f12348f023b/2020-02-29T00:15:25.529771Z, JVM: 13.0.2
```

**Plugins installed**: default rpm install

**JVM version** (`java -version`):
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system): CentOS 7

**Description of the problem including expected versus actual behavior**:

I expect the transport connection to use SNI when connecting to a peer. Currently it does not send any SNI headers

**Steps to reproduce**:

Can't come up with a simple repro case.  I guess the easiest would be to setup a cluster and a haproxy that proxies to the nodes using SNI

**Provide logs (if relevant)**:

n/a

**Comment by astefan** [comment]
I believe this is already supported as part of https://github.com/elastic/elasticsearch/issues/32517 with docs being added with https://github.com/elastic/elasticsearch/pull/40281.

**Comment by sventschui** [comment]
Hi @astefan. Thanks for the fast reply. To clarify things: I do not want to configure a remote cluster. I try to setup a coordinator only node that connects to the other ones through a k8s ingress that requires SNI. When configuring the nodes in `discovery.seed_hosts` the connection fails as the k8s ingress (haproxy) can not detect the pod to route to since SNI headers seem to be missing

**Comment by ywelsch** [comment]
@sventschui can you explain why you're setting up nodes that way? Nodes in a cluster are supposed to be part of the same network. Nodes in a cluster also need to be able to bidirectionally establish connections amongst each other. It sounds to me that what you're trying to do (unidirectional connect) would be better accomplished with the remote cluster feature.

**Comment by DaveCTurner** [comment]
> We have a 2 DC setup where we want a HA setup of elasticsearch. When one DC fails there still needs to be a quorum.

This isn't even theoretically possible. See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/high-availability-cluster-design-large-clusters.html#high-availability-cluster-design-two-zones) for more information.

> traffic to OpenShift is only allowed through an ingress on Port 443 that does SNI based load balancing

I don't think we should offer support for proxies between nodes within a cluster (at least not at layer 4 and up where this kind of feature would be needed). I could have seen some value in doing this for the transport client (but not now it's deprecated) and we already support SNI for remote clusters, so I think we shouldn't take any action here.

**Comment by original-brownbear** [comment]
For the reasons above we do not believe this is something we want to do so I'm closing this.
