### ISSUE TITLE
how to prevent steal read

### ISSUE THREAD

**Issue by ChinaXing** [elastic/elasticsearch#54711]
if client read sent to a replica which not included in sync-set.
and the replica's route is outdated. send to a steal sync-replica will cause steal read

how to prevent this situation ?

**Comment by astefan** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
