### ISSUE TITLE
LicenseServiceClusterTests testClusterRestartWithLicense failed on 7.7

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#54722]
The recent failure on 7.7
There were a number of failures for this test on 7.x and 7.6 before Feb 14

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/17/console
Build Scans: https://gradle-enterprise.elastic.co/s/uag3qsrtvt3y6

./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.license.LicenseServiceClusterTests.testClusterRestartWithLicense" \
  -Dtests.seed=2D09519D1517668E \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=Etc/Zulu \
  -Dcompiler.java=13

Reproduce with:
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.license.LicenseServiceClusterTests.testClusterRestartWithLicense" \
  -Dtests.seed=2D09519D1517668E \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=Etc/Zulu \
  -Dcompiler.java=13

Doesn't reproduce for me

Stack trace:
```
Caused by: java.lang.AssertionError: liveNodes = [{node_td2}{r7gWuHwlQH-frZxLBWNiBA}{4gzJxSZqSfmXOoi4lsnjsg}{127.0.0.1}{127.0.0.1:45961}{dimr}{xpack.installed=true}, {node_td0}{85ixmiaLSjWDv80QlPw_9g}{m95q0RY9TVewJI6jRT-How}{127.0.0.1}{127.0.0.1:46423}{dimr}{xpack.installed=true}] master = {node_td3}{-SejcTudQXegYl4TqSVuYQ}{UR8pDC44R_iH3h18dyhE_g}{127.0.0.1}{127.0.0.1:38129}{dimr}{xpack.installed=true}
```

Looks like an assertion that checks for live nodes is tripped.
Could be just a temporary problem in node connections

**Comment by tvernum** [comment]
@jkakavas will look into the current state of this test and whether it's failing on active branches

**Comment by jkakavas** [comment]
All but a couple of failures ( and _all_ the ones in the last month ) are 7.6, 7,7, 7.x in FIPS 140 matrix jobs that we should ignore for now until the CI is fixed. Since these are tracked in other issues, I will be closing this specific issue.
