### ISSUE TITLE
[DOCS] Update `node.processors` settings on the "Thread Pool" page

### ISSUE THREAD

**Issue by a03nikki** [elastic/elasticsearch#54815]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4+

**Description of the problem including expected versus actual behavior**:

The documentation still lists the deprecated name instead of current name for the setting.

**Steps to reproduce**:
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/breaking-changes-7.4.html#deprecate-processors

> processors setting is being replaced by node.processors
>
> To ensure that all settings are in a proper namespace, the `processors` setting is deprecated, and will be removed in version 8.0.0. Instead, use `node.processors`.

https://www.elastic.co/guide/en/elasticsearch/reference/7.6/modules-threadpool.html#processors

> Processors setting
>
> The number of processors is automatically detected, and the thread pool settings are automatically set based on it. In some cases it can be useful to override the number of detected processors. This can be done by explicitly setting the processors setting.
>
> `processors: 2`
>
> ...

**Comment by jasontedor** [comment]
I opened #54855.
