### ISSUE TITLE
Sizes of shard are incorrect

### ISSUE THREAD

**Issue by Kamna09** [elastic/elasticsearch#54827]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**: None

**JVM version** (`java -version`): 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux ip-xxx-xxx-xxx-xxx 4.14.165-103.209.amzn1.x86_64 #1 SMP Sun Feb 9 00:23:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Shard sizes for an index are different. Please find output of _cat/shards below:

"/_cat/shards/logstash-2020.03"
logstash-2020.03 4 p STARTED 530401 246.5mb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 4 r STARTED 530401 246.5mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 2 p STARTED 530013 248.3mb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 2 r STARTED 530013 248.3mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc
logstash-2020.03 1 r STARTED 529378 245.3mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 1 p STARTED 529378 245.3mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc
logstash-2020.03 3 r STARTED 528994     1gb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 3 p STARTED 528994     1gb X dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 0 r STARTED 530356 247.8mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 0 p STARTED 530356 247.8mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc

The doc counts are accurate between the primary and secondary shards. 
However, after forceMerge was ran. Sizes of the shard have shrunk, but the doc count is accurate and the same.

% /_cat/shards?v | grep 'shard\|logstash-2020.03'
logstash-2020.03 4 p STARTED 530401 246.5mb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 4 r STARTED 530401 246.5mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 2 p STARTED 530013 248.3mb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 2 r STARTED 530013 248.3mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc
logstash-2020.03 1 r STARTED 529378 245.3mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 1 p STARTED 529378 245.3mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc
logstash-2020.03 3 r STARTED 528994 244.8mb X d9b8dd5f9fbd1d041d37a9e97c2a1097
logstash-2020.03 3 p STARTED 528994 244.8mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 0 r STARTED 530356 247.8mb X  dd3f1d287f72b9cb4ea56421d3838fd5
logstash-2020.03 0 p STARTED 530356 247.8mb X  7cd0b6c4209bd6ad211c0bd0caf50bcc

As forgeMerge fixed the size issue, I suspect its stale metadata issue. Not sure if it is specific to ES 7.1 only, but I would have expected this to have been done automatic.

ES did not automatically fix this issue, this issue was there from last 10 days until we issued ForceMerge command and sizes of all shards became same.

**Comment by DaveCTurner** [comment]
I do not think this can be explained by "stale metadata" since these sizes are calculated by adding up the sizes of the files on disk. I think it much more likely that shard `[3]` really was 1GB in size due to some older segments which the force-merge cleared up.

However your force-merge operation will have destroyed the information we needed to do any further investigation, so I think there's no further action to take here.

**Comment by Kamna09** [comment]
@DaveCTurner , Thanks for quick reply!
Can you please let me know, what all information I should capture when this issue occurs again?

**Comment by DaveCTurner** [comment]
I would start with `GET _cat/segments` and a listing of the actual files on disk together with their sizes, but that may not be enough.
