### ISSUE TITLE
[ILM] Can't change number of  replicas to 0 in warm phase if auto_expand_replicas is set

### ISSUE THREAD

**Issue by mellieA** [elastic/elasticsearch#54835]
The APM template has auto_expand_replicas set. When a user has a hot-warm deployment with only a single warm instance, they want to change the number of replicas to 0 in the warm phase. This never happens when auto_expand_replicas is enabled.

Steps to reproduce:

- Configure a hot/warm deployment in Elastic Cloud
- Edit the APM ILM policy to add a warm phase in Kibana. Set the number of replicas to 0.
- Wait for the index to rollover, observe that the new index should be using the new version of the ILM policy.
- Wait for the new index to move to the warm phase, observe that number of replicas stays at 1.

Workaround:

- Edit the apm-7.X.X template, change auto_expand_replicas to number_of_replicas, and set the value to 1.
- Wait for the index to roll over again, observe that the ILM policy version is incremented
- Wait for the index to move to the warm phase. The number of replicas is set to 0 as expected.

**Comment by mellieA** [comment]
@Dakrone opened this issue as requested :)

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
