### ISSUE TITLE
EQL: implement math functions: add, divide, module, multiply, subtract

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elasticsearch#54846]
- [ ] **add** `(number, number) -> number`
- [ ] **divide** `(number, number) -> number`
- [ ] **modulo** `(number, number) -> number`
- [ ] **multiply** `(number, number) -> number`
- [ ] **subtract** `(number, number) -> number`

**Comment by Shubhangi2901** [comment]
Hi @aleksmaus I would like to work on this issue.

**Comment by aleksmaus** [comment]
Hi @Shubhangi2901, thank you for your interest in contributing to Elasticsearch. I have already started working on this issue.
There is plenty of other interesting issues to tackle for this project though. To find one, please check the `good first issue` label for example:
https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
