### ISSUE TITLE
Bug when highlighting on field with more than 50 matching fragments

### ISSUE THREAD

**Issue by jonpaul** [elastic/elasticsearch#5486]
Hi Elasticsearch. I'm presenting an issue that has been sitting on the mailing list for a while without attention, I think that I've found a highlighting issue when a field has a "large" number of fragments, specifically edge ngram fragments.

I have a gist that easily reproduces the issue. When attempting smaller hashes with the same analyzer, the highlight result is what I would expect. It's only when using longer hash strings that this issue occurs. Sorry if this is just a misunderstanding of how to use the highlighter, but, it certainly seems to be a bug. Thanks very much for looking into this issue.

Repro gist: https://gist.github.com/jonpaul/d4a9aa7f9c8741933cf5

[Edits:]
This issue was verified on the mailing list, here: https://groups.google.com/forum/?fromgroups#!topic/elasticsearch/DeC5JXqY78M

I think a realistic, simple solution would be to make that property (MAX_NUM_TOKENS_PER_GROUP) configurable, so that users can specify unusually large numbers if they believe their system is capable of handling it.

**Comment by clintongormley** [comment]
Closing in favour of #21621
