### ISSUE TITLE
TLS certs may not be picked up if updated at ES startup

### ISSUE THREAD

**Issue by sebgl** [elastic/elasticsearch#54867]
Elasticsearch version: any (observed with 6.8.5 and 7.6.1)

I think we spotted a bug where TLS transport certificates are not picked up by Elasticsearch, if they are updated on disk around the same time Elasticsearch starts. See [this issue in ECK repository](https://github.com/elastic/cloud-on-k8s/issues/2823).

It's not easy to reproduce, but we observed it happening several time across multiple rolling upgrade scenarios. The following seems to be happening:

* ES is running, and configured to use a transport TLS certificate file on disk. Any modification on this file is correctly picked up.
* We trigger a rolling upgrade on the cluster. When a node is restarted, it may restart with a different IP address (we're running in Kubernetes). As a result, ECK generates a new certificate to match the new IP address, and replaces the existing one on disk.
* In case we're not lucky, this happens when Elasticsearch (re)starts:
    * It picks the existing certificates on disk: the old ones with the old IP address, that has not been replaced yet
    * At that point the certificate file is updated
    * Elasticsearch starts monitoring the filesystem for any change on certificates file. We missed the certificate update here, and still serve the old certificate that does not exist on the disk anymore. The new cert on disk does not get picked up until it gets modified again.

I can imagine this is unlikely to happen since most people won't manipulate TLS certificates while Elasticsearch is still starting. However this is what happens in ECK, since we cannot know the node IP address until the Pod is created, at which point Elasticsearch is starting already.

More generally, as a user, I would expect Elasticsearch to pick up my TLS certificate file, whether I create/update them before Elasticsearch starts, during the startup, or after Elasticsearch is started. Having a small time window where this is not the case feels like a bug?

A quick chat with @ywangd confirmed, from reading the code, that there's a time window between loading certificates and watching for changes where any update is not accounted for.

**Comment by ywangd** [comment]
There are two reasons for it to happen, one major and one minor:

* The [high frequency watcher](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/watcher/ResourceWatcherService.java#L111) of `ResourceWatcherService` has an initial delay of [5 seconds](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/watcher/ResourceWatcherService.java#L53) before its 1st poll. If a cert file gets updated before the 1st poll, it won't be picked up. This could be the main contributor to the failure.

* A minor possibility: Both `SSLService` and `SSLConfigurationReloader` are created in [`XPackPlugin`](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackPlugin.java#L236-L239) as part of the bootstrap [setup](https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java#L349) process. But `ResourceWatcherService` (used by `SSLConfigurationReloader`) does **not** start and queue its 1st poll until the [start](https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java#L358) process is invoked. This is a much shorter gap. But may still worth considering.

**Comment by jaymode** [comment]
I see this as more of a general issue since not only security could be affected:

1. Starting of the resource watcher service. It should be one of the first items constructed and started within a node IMO.
2. Ensuring that when an item is added to be watched we capture the relevant stats so we can detect a change between add and first poll
