### ISSUE TITLE
Index Lifecycle Management not removing exclude for tags defined in the index template

### ISSUE THREAD

**Issue by crisdarocha** [elastic/elasticsearch#54883]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_191

**OS version** (`uname -a` if on a Unix-like system): Darwin Kernel Version 18.7.0

**Description of the problem including expected versus actual behavior**:

If we add an allocation exclude to a certain tag in the index template, this tag is not removed by Index Lifecycle Management in a later phase.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Add an allocation exclusion in the index template
```
"routing": {
  "allocation": {
    "exclude": {
      "node_type": "cold"
    }
  }
}
```

 2. Add an ILM policy that will in the cold phase, remove the exclude and add a require for this tag
```
"cold": {
  "min_age": "15d",
  "actions": {
    "allocate": {
      "number_of_replicas": 0,
      "include": {
        "node_type": "cold"
      },
      "exclude": {},
      "require": {
        "node_type": "cold"
      }
    },
    "set_priority": {
      "priority": 0
    }
  }
}
```

 3. Index settings at the end still have the `exclude`
```
"routing": {
  "allocation": {
    "include": {
      "node_type": "cold"
    },
    "exclude": {
      "node_type": "cold"
    },
    "require": {
      "node_type": "cold"
    }
  }
}
```
 4. Adding a null as tag value will fail validation
```
"exclude": {
    "node_type": null
}
```

Validation
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[36:28] [allocate] failed to parse field [exclude]"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[36:28] [put_lifecycle_request] failed to parse field [policy]",
    "caused_by" : {
      "type" : "x_content_parse_exception",
      "reason" : "[36:28] [lifecycle_policy] failed to parse field [phases]",
      "caused_by" : {
        "type" : "x_content_parse_exception",
        "reason" : "[36:28] [phases] failed to parse field [cold]",
        "caused_by" : {
          "type" : "x_content_parse_exception",
          "reason" : "[36:28] [phase] failed to parse field [actions]",
          "caused_by" : {
            "type" : "x_content_parse_exception",
            "reason" : "[36:28] [actions] failed to parse field [allocate]",
            "caused_by" : {
              "type" : "x_content_parse_exception",
              "reason" : "[36:28] [allocate] failed to parse field [exclude]",
              "caused_by" : {
                "type" : "illegal_state_exception",
                "reason" : "Can't get text on a VALUE_NULL at 36:28"
              }
            }
          }
        }
      }
    }
  },
  "status" : 400
}
```

**Provide logs (if relevant)**:

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
