### ISSUE TITLE
Specifying a negative `from` value in a Search returns different hard-to-interpret error messages

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#54897]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**Description of the problem including expected versus actual behavior**:

When specifying a negative `from` value in a search request, the exceptions do not contain a proper hint, of what is wrong, same for the `size` value. Also, specifying different values returns different exceptions:

**Steps to reproduce**:

```
DELETE foo

PUT foo/_doc/1?refresh
{
  "foo" : "bar"
}

# no exception is returned. SearchRequest class uses `-1` to encode `no value`
GET foo/_search
{
  "from": -1
}
```

```
GET foo/_search
{
  "from": -2
}
```

This returns

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "Index -2 out of bounds for length 1"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "foo",
        "node" : "09AkvSHFQau4CNnVlDeOgQ",
        "reason" : {
          "type" : "array_index_out_of_bounds_exception",
          "reason" : "Index -2 out of bounds for length 1"
        }
      }
    ],
    "caused_by" : {
      "type" : "array_index_out_of_bounds_exception",
      "reason" : "Index -2 out of bounds for length 1",
      "caused_by" : {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "Index -2 out of bounds for length 1"
      }
    }
  },
  "status" : 500
}
```

```
GET foo/_search
{
  "from": -10
}
```

This returns

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "foo",
        "node" : "09AkvSHFQau4CNnVlDeOgQ",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count"
      }
    }
  },
  "status" : 400
}
```

This does not contain any concrete information what could be culprit (think of an autogenerated search request from an app, that accidentally uses a negative value - this will be hard to track down.

Original issue reported via the forum at https://discuss.elastic.co/t/numhits-must-be-0-please-use-totalhitcountcollector-if-you-just-need-the-total-hit-count/226516/3

Relates #10791

**Comment by cbuescher** [comment]
This behaviour suprised me since we already [check for negative from values](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L360) in our SearchSourceBuilder setters and even have [rest tests](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/search/30_limits.yml#L35) for this -2 that check for the right exception message. 

Turns out that test sets the request parameter, not the "from" value in the search body, so this:
```
GET foo/_search?from=-2
```
throws "illegal_argument_exception", "reason" : "[from] parameter cannot be negative" as expected.
