### ISSUE TITLE
The `indices.delete_index_template` REST API doesn't accept `_all`

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#54937]
The [`indices.delete_index_template`](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.delete_index_template.json) doesn't accept the `_all` value for name, to delete all index templates, but it does accept an asterisk:

```
curl -X DELETE 'http://localhost:9200/_index_template/_all?pretty'
# ...
# "type" : "index_template_missing_exception",
# "reason" : "index_template [_all] missing"
# ...

curl -X DELETE 'http://localhost:9200/_index_template/*?pretty'
# ...
# "acknowledged" : true
# ...
```

To make it consistent with the other APIs, it should accept `_all`?

**Comment by zacharymorn** [comment]
I'm interested in working on this. Is there any update from team discussion (or when the discussion will happen)?

**Comment by dakrone** [comment]
@zacharymorn sorry for the late update on this, we're still discussing this (and the long term implications of `_all` in general)

**Comment by jpountz** [comment]
We discussed it and the general agreement was that we should generally accept wildcards and abandon `_all`. However how we get there proved controversial because of the backward compatibility implications.

I'm marking this issue as stalled.

**Comment by dakrone** [comment]
@jpountz I'm not sure there is a backwards compatibility issue for this API in particular since it has never supported `_all`? (I'm more inclined to close this issue than leave it as stalled) Or do you mean more of an issue with fitting in with our existing APIs?

**Comment by jpountz** [comment]
Oh right, the bw compatibility issue is for the general case. This one is good since it does _not_ support `_all`. Thanks for flagging.
