### ISSUE TITLE
FVH does not work with span_near queries

### ISSUE THREAD

**Issue by hazzadous** [elastic/elasticsearch#5496]
I would expect highlighting to work, a recreation at https://gist.github.com/hazzadous/9671181

Groups discussion at https://groups.google.com/forum/#!topic/elasticsearch/zQ06PD_T1tw

Robert Muir mentions this would require flattening the query to achieve.

**Comment by clintongormley** [comment]
Closing in favour of #21621

**Comment by lami02** [comment]
I have this problem as well. Perhaps there is someone who could help me working around this, without waiting for the unified highlighter. I need the span_near queries to use wildcard-queries within phrases (like "*foo bar") and I need the fast vector highlighter to match multiple fields (with two different analyzers). How can I get the desired result? Is there any option I am missing?
