### ISSUE TITLE
SQL: Implement TIME_PARSE

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#54963]
Implement TIME_PARSE(<time_str>, <pattern_str>) function
which allows to parse a time string according to the specified
pattern into a time object. The patterns allowed are those of
java.time.format.DateTimeFormatter.

Follows: #54960

**Comment by vishnugt** [comment]
I would like to work on a PR to implement this.

**Comment by matriv** [comment]
@vishnugt Feel free to work on this, thank you!

**Comment by vishnugt** [comment]
Due to some personal issues, I won't be able to continue working on this.  Please feel free to continue my work or make a new PR to work from scratch.  Sorry for the trouble @matriv

**Comment by atif-konasl** [comment]
Hi @matriv , would you please assign this task to me? I want to contribute.

**Comment by nathanvercaemert** [comment]
Hi. Can I work on this?

**Comment by nathanvercaemert** [comment]
Is this available for me to work on?

**Comment by MohamedBechir** [comment]
I would like to start working on it!

**Comment by matriv** [comment]
@MohamedBechir Sorry but @Patrick0308 has already started working on this: #55223

**Comment by matriv** [comment]
`master` : 1fe1188d449cad7d0782a202372edc52a4014135
`7.x` : b2651323fd880ab916c91588c0996e2679943b2a
