### ISSUE TITLE
SQL: Implement to_char(date/time/datetime, pattern)

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#54964]
Implement `to_char` according to the PostgreSQL spec: https://www.postgresql.org/docs/9.1/functions-formatting.html by translating to the java.time patterns used in `DATETIME_FORMAT`.
Follows: #54832

**Comment by avirlrma** [comment]
Hi, Can I start working on this?

**Comment by matriv** [comment]
@avirlrma  Sure go ahead.

**Comment by Boda805** [comment]
@avirlrma Are you still working on this? I would like to if not.

**Comment by matriv** [comment]
@Boda805 Since there is no response for some time, feel free to take it over if you want.

**Comment by Kasula11** [comment]
Hi matriv, I am new to open source. Can I take this?.  Can you please tell me where to implement?

**Comment by matriv** [comment]
@Boda805 Are you still interested in taking this?

**Comment by Boda805** [comment]
@matriv Yes but I'm pretty busy for the next couple weeks, if @Kasula11 wants to take that's fine, I could still try to help out as well when I have time.

**Comment by Kasula11** [comment]
Thanks. When I am trying to import project this project as existing gradle project. then it is showing me error.  

Caused by: org.gradle.api.GradleException: At least Java 11 is required to build elasticsearch gradle tools
	at build_6mm40yswivqsuj1oqx64fwsng.run(C:\Users\karthik\elasticsearch\buildSrc\build.gradle:66)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 155 more

Even though I have download Java 11 and Set JAVA_HOME to C:\Program Files\Java\jdk-11.0.6

**Comment by Boda805** [comment]
@Kasula11 use Java 14 I had the same problem at first. I believe it's in the documentation somewhere.

**Comment by Kasula11** [comment]
@matriv  I need to know whether my understanding is correct for regarding implementation of to_char() function. For example if i am going to implement to_char function for converting time stamp to string than the arguments that are passed to to_char function are timestamp and pattern which are of Expression Type.

Using DATETIME_FORMAT(DateTimeFormat class) I am going to getting the Desired format for particular timestamp and return string version of it?

**Comment by cheng141** [comment]
I  Just  want   to you

**Comment by z13z** [comment]
Hi, if it's possible I would like to start working on this issue.

**Comment by grgAditya** [comment]
Hi is someone working on this or I can take this up?

**Comment by devanandch** [comment]
Hi, can i work on this item please

**Comment by devanandch** [comment]
any update on my request

**Comment by matriv** [comment]
@devanandch Sorry for the delay, go ahead and please use the same approach as in #55454

**Comment by syedsouban** [comment]
Hi @devanandch let me know if you are working on it, otherwise I would like to work on it. Thanks!

**Comment by devanandch** [comment]
Hi @syedsouban i am working on it.

**Comment by devanandch** [comment]
> @devanandch Sorry for the delay, go ahead and please use the same approach as in #55454

Thank you Matriv, I will make sure to get the PR submitted soon.

**Comment by SrihariShastry** [comment]
Hi, can I work on this?

**Comment by bpintea** [comment]
Hi. Thank you for your interest in contributing!
Inline with common open source practices, we would like to no longer block and attribute issues, but rather invite anyone with a concrete proposal to simply submit a PR. No one likes duplicating work, but please consider that chances of concurrent PRs are low - especially for longer standing issues - and quality will trump over submission order.

**Comment by mohammedtabish** [comment]
Hey, if nobody’s working on it can I?

**Comment by philkra** [comment]
@mohammedtabish, please refer to one of the previous comments https://github.com/elastic/elasticsearch/issues/54964#issuecomment-696033995

**Comment by matriv** [comment]
Please try to use the pattern of a similar PR: #62701

**Comment by pspranjal444** [comment]
Hi @matriv. I am new to open source. Can you please provide more context on what exactly to do ? I have to add `to_char()` in `DateTimeFormatProcessor.java` file. Is that correct ?

**Comment by matriv** [comment]
@pspranjal444 The implementation is pretty straight forward, please look at my previous comment and follow the pattern for implementing another flavour of this function.

**Comment by LahiruSen** [comment]
> Implement `to_char` according to the PostgreSQL spec: https://www.postgresql.org/docs/9.1/functions-formatting.html by translating to the java.time patterns used in `DATETIME_FORMAT`.
> Follows: #54832

Hi @matriv , I would like to work on this issue.

**Comment by rakeshmissioncode** [comment]
I'd like to start contributing to this issue.
Any hints on which part of the code I should start with, for this issue?

**Comment by matriv** [comment]
Implemented with https://github.com/elastic/elasticsearch/pull/66486
