### ISSUE TITLE
SQL: Implement DATE_PARSE

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#54962]
Implement DATE_PARSE(<date_str>, <pattern_str>) function
which allows to parse a date string according to the specified
pattern into a date object. The patterns allowed are those of
`java.time.format.DateTimeFormatter`.

Follows: #54960

**Comment by Patrick0308** [comment]
Hi @matriv, I want to know that what's the different between <date_str>, <datetime_str>, <time_str>.

**Comment by matriv** [comment]
`date_str` contains only date information, e.g.: `20/05/2020` and returns an object of `DATE` data type.
`time_str` contains only time information, e.g.:  `10:20:30.12345` and returns an object of `TIME` data type.
`datetime_str` contains both, e.g.: `20-05-2020 10:20:30.123` and returns an object of `DATETIME` data type.

**Comment by Patrick0308** [comment]
@matriv Thank you for explaining. Let me try.

**Comment by matriv** [comment]
@Patrick0308 Thank you!

**Comment by matriv** [comment]
@Patrick0308 I would suggest though to wait for #55095 since this will re-arrange some code, with the introduction of an enum, or simpler a new argument to the Processor so that TIME and then DATE can be parsed with 2 new separate functions.

**Comment by Patrick0308** [comment]
@matriv Ok, I will pay attention to the progress of #55095 .

**Comment by matriv** [comment]
Would you like to take over #55095 ? or you could just implement the DATE_PARSE with similar approach as described in my comments there.

**Comment by matriv** [comment]
@Patrick0308 Would you like to take over #55095 ? or you could just implement the DATE_PARSE with similar approach as described in my comments there.

**Comment by paytonmcl** [comment]
I would like to contribute to fix this issue. Could I get assigned? This would be my first issue.

**Comment by sakthivigneshkumar** [comment]
Can I Contribute to fix this issue? Please let me know if it is open. This would be my first issue.

**Comment by maheshsv** [comment]
Can i contribute to this issue, please let me know

**Comment by matriv** [comment]
@maheshsv there is already a PR open for this: #57391

**Comment by matriv** [comment]
`master` : 647a413d9b21bd3938f1716bb19f8407e1334125
`7.x` : c7efbc1b831adf99cbf2d37d6e9c47ee2b93722d
