### ISSUE TITLE
_ccr/info should return parameters for paused follower indices

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#54996]
Kibana allows users to edit paused follower indices, which is problematic because the API doesn't return the `parameters` information which we surface to the user as "Advanced settings". This creates a buggy UX because it appears to the user as if any changes they've made to the parameters have disappeared.

A solution would be to change the `_ccr/info` API to provide the same response regardless of whether a follower index is paused or active.

Here's the UI in question:

![image](https://user-images.githubusercontent.com/1238659/78846932-3a7b5900-79c2-11ea-9045-f2d2675f11d8.png)

Here's an example response from the `_ccr/info` API, showing follower indices both with and without parameters information:

```json
{
  "follower_indices" : [
    {
      "follower_index" : "kibana_sample_data_ecommerce1",
      "remote_cluster" : "test",
      "leader_index" : "kibana_sample_data_ecommerce",
      "status" : "active",
      "parameters" : {
        "max_read_request_operation_count" : 100,
        "max_write_request_operation_count" : 5120,
        "max_outstanding_read_requests" : 12,
        "max_outstanding_write_requests" : 9,
        "max_read_request_size" : "32mb",
        "max_write_request_size" : "9223372036854775807b",
        "max_write_buffer_count" : 2147483647,
        "max_write_buffer_size" : "512mb",
        "max_retry_delay" : "500ms",
        "read_poll_timeout" : "1m"
      }
    },
    {
      "follower_index" : "kibana_sample_data_ecommerce2",
      "remote_cluster" : "csdcds",
      "leader_index" : "kibana_sample_data_ecommerce",
      "status" : "paused"
    }
  ]
}
```

**Comment by cjcenizal** [comment]
@jasontedor Would you mind explaining why this doesn't qualify as a bug? From my perspective, it's a bug because the API response drops information that I'd expect to be present (resulting in bugs in the UI -- see back-linked issue for a new one).

**Comment by jasontedor** [comment]
Because the API was only designed to fetch info for active follower indices. That is, it's operating as designed, it's not not doing something it was suppose to do. Whether or not it should be designed differently to accommodate this use case is an open question. We wouldn't change this behavior in a patch release, only in a new minor release, so it wouldn't be considered a bug fix, but an enhancement.

**Comment by cjcenizal** [comment]
Thanks for the explanation @jasontedor. This makes sense. The docs don't mention this change in response based on status, so I'll submit a PR to clarify this.

**Comment by MorrieAtElastic** [comment]
@jasontedor , @cjcenizal: should not any condition that returns a java script stack trace to the browser screen be considered a bug? Possibly the bug is in the design, but this strikes me as a screen crash, and - IMHO - a screen crash should always be considered a bug

**Comment by cjcenizal** [comment]
@MorrieAtElastic To clarify, that stack trace indicated a Javascript error, and I was able to track it down to an error in Kibana, not Elasticsearch.

**Comment by tlrx** [comment]
Duplicates of #37740
