### ISSUE TITLE
[DOCS] Multi Search - Default value for `max_concurrent_searches` not documented

### ISSUE THREAD

**Issue by bestpath-gb** [elastic/elasticsearch#55033]
On the documentation page for [Multi Search](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-multi-search.html), the default value for `max_concurrent_searches` is not specified.

It took a bit of asking on Slack and digging through the code to figure it out. Found it [here](https://github.com/elastic/elasticsearch/blob/2843992b1168f585349cfb7d1902e2aacc558cd6/server/src/main/java/org/elasticsearch/action/search/TransportMultiSearchAction.java#L107) in the end. It would be great to have this in the docs.

**Comment by jtibshirani** [comment]
Thanks @bestpath-gb for raising this. Would you be interested in submitting a fix?
