### ISSUE TITLE
SLES-12 vagrant packaging tests failure to install expect

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#55048]
Example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=sles-12,nodes=metal/30/console / https://gradle-enterprise.elastic.co/s/rbuw6vtrfalp6

This is reproducible on the latest master e.g. using `./gradlew :qa:os:sles-12:distroTest.default-rpm`

Issue appears that the repos don't include the `expect` package any more:

```
...
|  INFO interface: detail: ==> Installing expect
|  INFO interface: detail:     sles-12: ==> Installing expect
|     sles-12: ==> Installing expect
| DEBUG ssh: stderr: No provider of 'expect' found.
```

which can be manually verified as well:

```
vagrant-sles-12-x64:~ # zypper update
Loading repository data...
Reading installed packages...

The following 3 package updates will NOT be installed:
  libxslt-tools libxslt1 rcs

Nothing to do.
```

**Comment by dliappis** [comment]
@rjernst WDYT abt disabling SLES-12 vagrant packaging tests until the corresponding infra ticket gets resolved?

**Comment by rjernst** [comment]
@dliappis I came up with a workaround: https://github.com/elastic/elasticsearch/pull/55135
