### ISSUE TITLE
packaging-vagrant-matrix jobs failing after requiring JDK-14 for compilation

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#55044]
A stream of vagrant based packaging jobs (pretty much all defined in [the vagrant packaging matrix](https://github.com/elastic/elasticsearch/blob/master/.ci/matrix-vagrant-packaging.yml)) are failing after JDK-14 became mandatory for compilation (https://github.com/elastic/elasticsearch/pull/54696).

This can be noticed on the `master` and `7.6` branches at least.

Examples:

- #master/ubuntu-18.04
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=ubuntu-1804,nodes=metal/30/console / https://gradle-enterprise.elastic.co/s/wnqreurvzqqtk

- #master/centos-7
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=centos-7,nodes=metal/30/console / https://gradle-enterprise.elastic.co/s/2ysfcusce7aos

- #master/fedora-29
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=fedora-29,nodes=metal/30/console / https://gradle-enterprise.elastic.co/s/6s74vnnhfvipe

The vagrant command shows that the first element in `PATH` is still set to JAVA-13:

```
INFO vagrant: `vagrant` invoked: ["ssh", "centos-7", "--command", "sudo bash -c '\npwd\ncd /elasticsearch/\nexport SYSTEM_JAVA_HOME=/elasticsearch/build/jdks/openjdk-11.0.2_linux_x64\nexport PATH=/elasticsearch/build/jdks/openjdk-13.0.1_linux_x64/bin:$PATH\nexport JOB_NAME=elastic+elasticsearch+master+packaging-vagrant-matrix/OS=centos-7,nodes=metal\nexport JENKINS_URL=https://elasticsearch-ci.elastic.co/\nexport BUILD_NUMBER=30\nexport BUILD_URL=https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=centos-7,nodes=metal/30/\n./gradlew destructiveDistroTest.default-linux-archive --project-cache-dir /elasticsearch/qa/os/centos-7/build/gradle-cache -S --parallel -D'org.gradle.logging.level'=LIFECYCLE -D'tests.inVM'\n'"]
```

which is odd because on the underlying bare metal host `~/.java` does contain `~/.java/openjdk14/` referenced by: https://github.com/elastic/elasticsearch/blob/201adafba9def1de4bf843760defb9def3394f63/.ci/java-versions.properties#L7-L8 which ought to be properly specified in `BUILD_JAVA_HOME`: https://github.com/elastic/elasticsearch/blob/201adafba9def1de4bf843760defb9def3394f63/.ci/os.sh#L27 ultimately referenced in: https://github.com/elastic/elasticsearch/blob/201adafba9def1de4bf843760defb9def3394f63/.ci/os.sh#L77-L83

**Comment by rjernst** [comment]
This needs to be updated in DistroTestPlugin.GRADLE_JDK_VERSION
