### ISSUE TITLE
Monitoring exporter treats absence of remote host as fatal failure

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#55041]
We have seen error messages of the following kind on our Cloud service:

```
org.elasticsearch.xpack.monitoring.exporter.Exporters [instance-0000000016] exporter [found-user-defined] failed to open exporting bulk\norg.elasticsearch.client.ResponseException: method [GET], host [http://containerhost:9244], URI [/?filter_path=version.number], status line [HTTP/1.1 410 Gone]\n{"ok":false,"message":"Deleted deployment."}\n\n\tat org.elasticsearch.client.RestClient.convertResponse(RestClient.java:253) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]\n\tat org.elasticsearch.client.RestClient.access$900(RestClient.java:95) ~[elasticsearch-rest-client-7.3.2.jar:7.3.2]\n\tat org.elasticsearch.client.RestClient$1.completed(RestClient.java:298) [elasticsearch-rest-client-7.3.2.jar:7.3.2]\n\tat org.elasticsearch.client.RestClient$1.completed(RestClient.java:294) [elasticsearch-rest-client-7.3.2.jar:7.3.2]\n\tat org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [httpcore-4.4.11.jar:4.4.11]\n\tat org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCo...
```

These error messages are being logged by Elasticsearch's monitoring component while it's unable to open a new bulk export for the http exporter. Opening a new bulk export means determining some information about the endpoint to which the monitoring data is to be sent, in order to make sure that that endpoint can handle the data to be sent. One such information that is determined is version information (i.e. which version the remote node has), to see if it has a compatible Elasticsearch version. This check is implemented in `VersionHttpResource.doCheckAndPublish` and matches the `/?filter_path=version.number` URI that appears in the failure message. Whenever the monitoring endpoint is not available while determining its remote version, a failure of the above kind will be logged at ERROR level. There are 2 variants of the message, which are probably coming from the Cloud infrastructure that is used to contact the remote monitoring endpoint: One says "Deleted deployment", the other one "Unknown deployment", i.e. the two main reasons for why the monitoring endpoint is not available. The first one returns status code 410 Gone, and the second one 404 Not Found. The check in considers this as a fatal error, logs a message of the form "failed to verify minimum version" at ERROR level and bubbles the exception up to ultimately log a message of the form "failed to open exporting bulk" at ERROR level as well.

VersionHttpResource.doCheckAndPublish should not treat the absence of a remote endpoint as a fatal error. It could follow what other classes that are extending HttpResource are doing, namely have special handling for some status codes such 404 Not Found. Note that these other classes do not have special handling for 410 Gone, and from a quick look also seem inconsistent in their use of status codes to be ignored.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
