### ISSUE TITLE
SQL: consider adding support for functions usage in LIKE/RLIKE predicates

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#55058]
A query like `SELECT LTRIM("first_name") lt FROM "test_emp" WHERE LTRIM("first_name") LIKE '%a%'` is not supported at the moment since the `LIKE` predicate expects it's left hand side argument to be a field.

ES SQL should also support the same functionality for `RLIKE`.

**Comment by matriv** [comment]
`master` : 51c14e2dbb7fb29004a23369c449d425b3ac8fe2
`7.x` : cbbbd499bf3b461a0e6dcfaab004ae927bdd5724
