### ISSUE TITLE
Allow multi character separator for CSV Ingest processor

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#55075]
**Describe the feature**:

Allow multiple characters as separator for CSV ingest processor.  As of version 7.6, the CSV ingest processor only allows single character separator. We have a use case where the log lines are delimited by `||` We were able to work around the issue using the split processor but it was less convenient. In Logstash the CSV filter, mulit character delimiters are allowed.

**Comment by probakowski** [comment]
We can potentially consider that, but I don't think we will have man-power to pick it up for  the foreseeable future.
For now maybe you can consider Gsub processor to replace multiple delimiters with single one:
```
GET _ingest/pipeline/_simulate 
{
  "pipeline": {
    "processors": [
      {
        "gsub": {
          "field": "test",
          "pattern": "\\|\\|",
          "replacement": "|"
        }
      },
      {
        "csv": {
          "field": "test",
          "target_fields": ["a", "b"],
          "separator": "|"
      }
    }]
  },
  "docs": [
    { 
      "_source": {
        "test": "1||2||3"
      }
    }
  ]
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
