### ISSUE TITLE
Upon upgrade to 7.6.2 from 7.4.x, null_value for type: ip doesn't seem to be executed

### ISSUE THREAD

**Issue by StratoZen** [elastic/elasticsearch#55097]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.6.2

**Plugins installed**: []
None

**JVM version** (`java -version`):
hosted elastic not sure

**Description of the problem including expected versus actual behavior**:

Post upgrade to 7.6.2 from 7.4.x, receiving the following error on document index attempt, where a few have null values.

RequestError(400, 'mapper_parsing_exception', "failed to parse field [ip_addr] of type [ip] in document with id 'jjPOanEBJ9vnX_RF5UnE'. Preview of field's value: ''")

The index template and resulting indexes do have the following null_value designation.
When null value is seen, sets the value to '0.0.0.0'
   "ip_addr": {
          "type": "ip",
          "null_value": "0.0.0.0"

Client is python 3 elasticsearch>=7.0.0,<8.0.0 -- prior to upgrade this issue was not seen.
**Steps to reproduce**:
Try to index a document with a our field above "ip_addr" of type IP with a null value set. 
The affected field does have a null_value set on index mapping, but this does not occur when a null value is submitted for this field, instead document insertion fails.

**Comment by nik9000** [comment]
@StratoZen, I've marked this for further looking by folks who know more about ES's mapping internals than I do. We might be able to reproduce the issue on our own but we tend to want a complete reproduction with built with `cURL` or Kibana's dev `CONSOLE`. As it stands we'll have to guess your mapping and the requests that you make. That might turn out pretty easy or it might not. But it'd be super helpful if you'd add reproduction with curl or console.

**Comment by StratoZen** [comment]
@nik9000 I'll work on getting those Dev console examples to you.

**Comment by StratoZen** [comment]
I'm not sure if I can put the entire post example, but I roughly have the follows:
In dev console:
POST /index1/_doc
{
  //json fields...
  "ip_addr": "0.0.0.0",
  //more json fields
}

This succeeds as the ip_addr field is of type "IP". 
{
  "_index" : "index1-000017",
  "_type" : "_doc",
  "_id" : "IvrjdHEBJ9vnX_RF9DC-",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "_seq_no" : 1692650,
  "_primary_term" : 1
}

Now taking the exact same record, and indexing it again, this time setting ip_addr : "".

"install_status": "N/A", "ip_addr": "", 
"last_file_recv_time": 1563911977, 
"last_perf_data_time": 1563911977, 
"last_status_update_time": 1563911980,
//more fields 
The result is a failure, normally this is expected.
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [ip_addr] of type [ip] in document with id 'dfXodHEBdhcRqQnIGaZ7'. Preview of field's value: ''"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [ip_addr] of type [ip] in document with id 'dfXodHEBdhcRqQnIGaZ7'. Preview of field's value: ''",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "'' is not an IP string literal."
    }
  },
  "status" : 400
}

With the null_type mapping however, upon finding a null  value, it should set it to what we designate. As mentioned above, for the above index, the field "ip_addr" does indeed have a null_value designation.

        },
        "ip_addr": {
          "type": "ip",
          "null_value": "0.0.0.0"
        },

My understanding is that, when a null value, or empty string is found, it should insert 0.0.0.0 for the field instead of failing to document the record.

It seems as though, upon finding an empty string, it should attempt to see if the null_value option is set prior to throwing an exception.

Thanks,

-Rob

**Comment by cbuescher** [comment]
@StratoZen thanks for the reproduction.
I was able to get the same error you described on 7.6.2. However, the behaviour when trying to add an empty String literal as an IP adress doesn't seem to have changed at least until 7.0. I got the same error on 7.0, 7.3.2 and 7.4.2 when doing

```
PUT /index1
{
  "mappings": {
    "properties": {
      "ip_addr" :{
        "type" : "ip",
        "null_value": "0.0.0.0"
      }
    }
  }

PUT /index1/_doc/1
{
  "ip_addr" : ""
}
```
```
      "type": "illegal_argument_exception",
      "reason": "'' is not an IP string literal."
```

Also note that the behaviour for real "null" values is as expected, the document gets indexed with a "0.0.0.0" value (although you don't see it in the "_source" but the value is searchable). I wonder wether the bahaviour on empty strings should be considered as intended since its not really a `null` value. Can you confirm how/if this worked for you in any earlier version, maybe with a more detailed example? Otherwise I'll assume this isn't a change in behaviour but maybe something we should document better instead.

**Comment by cbuescher** [comment]
Also 6.8.7 throws the IAE on trying to index an empty string.

**Comment by StratoZen** [comment]
Ah this makes perfect sense. My problem here was incorrectly assuming an empty string would be treated as a NULL value. What I was seeing on our client side, was some behavior results in a python type None, and upon indexing would correctly get assigned the null_value "0.0.0.0".  This scenario seems to work, but where the confusion was, is some data resulted in an empty string. I thought null_value option would also incorporate this. I only noticed post upgrade, so I had thought this was related.

Easy fix on my client side, thanks for the help.

**Comment by cbuescher** [comment]
@StratoZen no problem, thanks for raising the issue anyway. Will close then.
