### ISSUE TITLE
Index template can not match the date pattern exactly as used in the URI.

### ISSUE THREAD

**Issue by zw963** [elastic/elasticsearch#55093]
Following is my index template definition:

![image](https://user-images.githubusercontent.com/549126/79034912-03888b80-7bec-11ea-8e2b-cbcd93dca8b2.png)

the index pattern in above definition works well in URI for following index, but I hope it can working on template definition, so it can apply exactly to following index when do ILM.

```
airhost_ror-2020.04.10-000001 
airhost_ror-2020.04.10-000002 
airhost_ror-2020.04.11-000001
```
But it is not working.

So, i don't know if this is a issue, or i just don't know how  to use it,  or, we still not support it yet.

Thank you.

**Comment by nik9000** [comment]
I'm tagging this with `Indices APIs` so folks who know more about those APIs will look at the issue.

**Comment by dakrone** [comment]
Template index patterns do not support date math. I'm not sure whether this is something we'd want to support though, it would be better to use `airhost_ror-*` for the pattern.

@zw963 maybe you can explain why you want date math to be supported in index templates?

**Comment by zw963** [comment]
@dakrone , thank you for replied.

> maybe you can explain why you want date math to be supported in index templates?

We have some existed index, which named like  `airhost_ror-000023`, used in old index templdate with old lifecycle policy.

We add some new index recent days,  use date named like `airhost_ror-2020.04.13-000001`,  with new index template,  and hope can support `two individual template can only effect individual index`.

In fact, index pattern can be do like this, it should working.

first one: "airhost_ror-00*"
second: "airhost_ror-20*"

anyway, this issue is resolved, thank you!
