### ISSUE TITLE
Painless ElasticSearch: Deletion of object from array of objects not working as expected.

### ISSUE THREAD

**Issue by HighOnWater** [elastic/elasticsearch#55110]
Java version: 1.8.0_151
ES Version: 7.4

I have this document in ElasticSearch index:
```
{
    "field1":"value1",
    "field2":"value2",
    "array1": [{
        ..some fields,
        "arrayObjectId": "12346",
      
    },{
       ... some fields,
        "arrayObjectId": "12346",
    },{
       ... some fields,
        "arrayObjectId": "12346",
    }]
}
```
I want to delete the objects from ```array1``` based on the ```arrayObjectId```. 
I use the following painless script to achieve it:
```
{
  "script": {
    "lang": "painless",
    "source": """

    for(int i = 0;i < ctx._source['array1'].length; i++) {
      if (ctx._source['array1'][i].arrayObjectId == "12346"){
        ctx._source['array1'].remove(i);
      }
    }
       """
  }
}
```
The above script removes 2 out of the three arrayObjectIds, instead of all of them. This same behavior is seen with Iterators. However it works fine (removing the objects from array that match the arrayObjectId field) with ```removeIf``` method of ArrayList as specified [here](https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-lambdas.html). 

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-lang-spec.html), painless shares basic constructs with Java. Ideally it should delete all objects from the array that match the arrayObjectId. Is the above behavior a bug? Can this be looked into.
Thanks

**Comment by nik9000** [comment]
I don't know the answer offhand so I've tagged the scripting folk. I remember that there is some issue with `List.remove(index)` and `List.remove(item)` that painless bumps into.

**Comment by jdconrad** [comment]
@HighOnWater I believe this isn't working correctly because the code is both reading from the `ctx._source['array1']` list and modifying it at the same time with the remove method. So it's possible to skip one of the fields as the index `i` has already moved past it.

**Comment by HighOnWater** [comment]
Hi @jdconrad i agree with your reasoning on the behavior of the code mentioned in the issue. However if you implement something similar in java using traditional ```for-loops``` or ```list-iterators```, the expected behavior is that it removes the object for which the condition suffices and no skipping happens. So my point is, shouldn't this behavior be consistent? atleast in the case of list iterators. (a recommended solution to ConcurrentModification issues when using ```for-in``` construct).

**Comment by rjernst** [comment]
@HighOnWater This isn't a painless issue, nor even a java specific problem. A ConcurrentModificationException is only thrown when a container knows that it is being iterated and modified at the same time. Using indices to access and modify a list will never work (unless special care is taken to adjust the loop index when an element is removed).

Since there is nothing we can do in painless, or java, to protect from this, I hope you don't mind that I close this issue.

**Comment by HighOnWater** [comment]
Hi @rjernst , while mentioning ConcurrentModificationException, i was digressing a bit. Shouldn't the removal of item from lists work fine with traditional for loops in painless as in java?
If you look at this snippet:
```
ArrayList<String> stringsList = new ArrayList<>();
        stringsList.add("Hello");
        idstringsLists.add("World");
        stringsList.add("Data");
        stringsList.add("World");

        for(int i = 0;i < stringsList.size(); i++) {
            if (stringsList.get(i).equals("World"))
                stringsList.remove(i);
        }
```
It works fine in java. As the documentation specifies, most of the java constructs are supported by painless, shouldn't then the behavior be consistent?

**Comment by rjernst** [comment]
@HighOnWater Your example happens to work only because of the order you insert the elements. If you instead you use this order, you will see the second instance of "World" is left:

```
stringsList.add("Hello");
stringsList.add("World");
stringsList.add("World");
stringsList.add("Data");
```

**Comment by HighOnWater** [comment]
thanks
