### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [elastic/elasticsearch#55145]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by jkakavas** [comment]
Hi there @Neustradamus ! Thank you for your interest in elasticsearch. We don't use spongycastle ( which is a repackaged version of BouncyCastle for android, so not really applicable to a project like elasticsearch) anywhere in our project, as such I hope you don't mind me closing this issue.

**Comment by Neustradamus** [comment]
I mix, I have not done the good ticket here!
I change it right now!

**Comment by Neustradamus** [comment]
@jkakavas: Sorry, I have mixed, I have not done the good ticket here!
I have changed, can you reopen it and solve it?

**Comment by jkakavas** [comment]
Hi again, we are using BouncyCastle 1.64 which doesn't suffer from any of the vulnerabilities that I assume you meant ( linking https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html ). We are aware that 1.65 was released two weeks ago and we will upgrade after testing this at some point as we do with all of our dependencies. We don't usually keep issues around for these upgrades when there is no bug or security issue that affects us so I will keep this closed.

**Comment by Neustradamus** [comment]
Good to have the last no?
- 1.64: https://github.com/elastic/elasticsearch/issues/55145
- 1.52: https://github.com/elastic/elasticsearch-mapper-attachments/issues/232
- 1.54: https://github.com/elastic/java-lumber/issues/1
- 1.56: https://github.com/elastic/gradle-code-manifest-plugin/issues

**Comment by Neustradamus** [comment]
@jkakavas: Good to have the last no?
- 1.64: https://github.com/elastic/elasticsearch/issues/55145
- 1.52: https://github.com/elastic/elasticsearch-mapper-attachments/issues/232
- 1.54: https://github.com/elastic/java-lumber/issues/1
- 1.56: https://github.com/elastic/gradle-code-manifest-plugin/issues

**Comment by jkakavas** [comment]
@Neustradamus thank you again for your feedback and interest. As I said, we will update this when we have tested the new version and we are certain that we want to upgrade.

**Comment by Neustradamus** [comment]
@jkakavas: I need to create a new ticket?
No change in this repository...

**Comment by jkakavas** [comment]
@Neustradamus Hi again, I tried to explain to you why I closed the issue and how we will handle this (without opening a new issue for now) and I kindly ask you to accept this. Thank you again for your interest in elasticsearch and for your help.

**Comment by Neustradamus** [comment]
Any news?

1/ Here:
- https://github.com/elastic/elasticsearch/blob/master/buildSrc/version.properties#L31

2/ Can you archive:
- https://github.com/elastic/elasticsearch-mapper-attachments

3/
- https://github.com/elastic/java-lumber/issues/1
- https://github.com/elastic/java-lumber/blob/master/build.gradle#L19

4/
- https://github.com/elastic/gradle-code-manifest-plugin/issues/5
- https://github.com/elastic/gradle-code-manifest-plugin/blob/master/testProjects/androidProject/expected_manifest.json#L113
- https://github.com/elastic/gradle-code-manifest-plugin/blob/master/testProjects/androidProject/expected_manifest.json#L411

**Comment by Neustradamus** [comment]
@jkakavas: Can you update Bouncy Castle to 1.69 and Java FIPS Release 1.0.2.1?
There are CVEs since your used versions.
