### ISSUE TITLE
Getting score with response when using sort in elastic request

### ISSUE THREAD

**Issue by guruprasadkk** [elastic/elasticsearch#55144]
I am using elasticsearch-rest-high-level-client 7.6.2 version to interact with elastic server from my java application.
Now I am planning to use sorting capability in elastic. When I added the sort in the elastic request. I am not getting the scores back in response.
I understood that it is expected behaviour and suggestion is to use
SearchRequestBuilder#setTrackScores(true)

But I am using RestHighLevelClient. with this how can I create the instance of SearchRequestBuilder?
Is there any other alternate solution for this problem?

**Comment by cbuescher** [comment]
Hi @guruprasadkk ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
