### ISSUE TITLE
Incremental restores treat segments containing soft-deleted docs as "different"

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#55142]
Today in restores and peer recoveries we treat any `.liv` files as per-commit rather than per-segment since they may change independently of the rest of the segment as documents are deleted:

https://github.com/elastic/elasticsearch/blob/a862dff26c67744d63076f9d5d8a774ca17e7fe9/server/src/main/java/org/elasticsearch/index/store/Store.java#L963-L969

This means that a restore or peer recovery that only deletes documents need only copy the corresponding `.liv` files. However today we soft-delete documents instead which updates their doc values, not their liveness markers, which means we fully restore/recover any segments whose set of deleted documents have changed.

Relates https://github.com/elastic/elasticsearch/issues/55013
Relates https://discuss.elastic.co/t/227184
Relates https://issues.apache.org/jira/browse/LUCENE-9324

**Comment by yjchen-tw** [comment]
any update for this issue? 
it seems to have a PR #55239 to fix this but have been postponed from v7.9.0 to v7.14.0
we suffer from large network traffic during restore due to newly deleted documents in large segments
would be happy to know if this can be fixed in recent release
