### ISSUE TITLE
EQL:  Comparisons against variables are not (currently) supported

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elasticsearch#55154]
While working on math functions implementation and testing against existing EQL specs stumbled upon this issue with comparison. Opening the tracking issue for this.

Example query:
```
process where add(serial_event_id, 1) == serial_event_id"
```

Result error:
```
Comparisons against variables are not (currently) supported; offender [serial_event_id] in [==]
```

Full request example:
```
$ curl -X GET "localhost:9200/test/_eql/search" -H 'Content-Type: application/json' -d'
{
    "query": "process where add(serial_event_id, 1) == serial_event_id"
}
' 
{"error":{"root_cause":[{"type":"ql_illegal_argument_exception","reason":"Line 1:42: Comparisons against variables are not (currently) supported; offender [serial_event_id] in [==]"}],"type":"ql_illegal_argument_exception","reason":"Line 1:42: Comparisons against variables are not (currently) supported; offender [serial_event_id] in [==]"},"status":500}
```

Expected:
The query to return result without error.

Not sure who to assign to, or if any additional labels are needed. Feel free to opt out.

**Comment by rw-access** [comment]
I don't see why we can't add this.

Would we fix in QL, which would add SQL  and EQL support?
https://github.com/elastic/elasticsearch/blob/04c39ae0ecffad3c25ef31c2ddefc0f55c6d8f32/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java#L215-L220

https://github.com/elastic/elasticsearch/blob/04c39ae0ecffad3c25ef31c2ddefc0f55c6d8f32//x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java#L264-L281

**Comment by rw-access** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/34400

**Comment by rw-access** [comment]
Update:
Only a handful of existing rules leverage this functionality. Of the ones that do, about half of them could be rewritten to not need it.

One of those examples, simplified:
```python
process_name in ("foo", "bar", ...) and parent_process_name != process_name
```
Could just be:
```python
(process_name == "foo" and parent_process_name != "foo") or
(process_name == "bar" and parent_process_name != "bar")
```

The ROI on adding this support is pretty low, but the risk might be hard to measure. I think it's okay to close the issue or de-scope it.

There are some (ugly) workarounds if users want to leverage it. Put this expression within a function that can only be evaluated in painless, then that code will never be reached. You could do this:
```python
string(process_name != parent_process_name) == "true"
```

**Comment by jrodewig** [comment]
#58941 will document this behavior and close this issue.
