### ISSUE TITLE
[CI] DedicatedClusterSnapshotRestoreIT.testDataNodeRestartWithBusyMasterDuringSnapshot timing out

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#55180]
This test has timed out twice now in the past couple days on `7.x`.

https://gradle-enterprise.elastic.co/s/43hnnh23kcozs/tests/kyv2y2z3r4v7k-6xc443z725n7o
https://gradle-enterprise.elastic.co/s/fmmmylincesru/tests/kyv2y2z3r4v7k-6xc443z725n7o

**Comment by original-brownbear** [comment]
This will be resolved over the next couple of hours via some missing backports to 7.x.

**Comment by original-brownbear** [comment]
Should be fixed now
