### ISSUE TITLE
[Feature Request][Foreach Ingest Processor] Add support for iterating over Hashmaps

### ISSUE THREAD

**Issue by P1llus** [elastic/elasticsearch#55215]
**Describe the feature**:

There has been an increase in the need to do a single action over a hashmap of JSON object, which is currently being handled by painless. Here is a real scenario example, in which incoming data coming from a device that cannot be modified on the source side has certain fields mapped as strings instead of integers, preventing the possibility of aggregation and visualisation.

```
"docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "system": {
          "hostname": "somemachine",
          "diskStorage": {
            "/": {
              "1024-blocks": "234",
              "Capacity": "5%",
              "name": "/"
            },
            "/dev": {
              "1024-blocks": "654616",
              "Capacity": "23%",
              "name": "/dev"
            },
            "/dev/shm": {
              "1024-blocks": "5430",
              "Capacity": "543%",
              "name": "/dev/shm"
            }
          }
        }
      }
    }
  ]
```

If I would want to iterate over diskStorage here, and remove the % + changing the type from String to Int, trying to put this into a foreach processor like so:

```
"pipeline": {
    "description": "_description",
    "processors": [
      {
        "foreach": {
          "field": "system.diskStorage",
          "processor": {
            "gsub": {
              "field": "_ingest._value.Capacity",
              "pattern": "%",
              "replacement": ""
            }
          }
        }
      }
    ]
  },
```

Will return the below error:
`"type" : "illegal_argument_exception",
  "reason" : "field [system.diskStorage] of type [java.util.HashMap] cannot be cast to [java.util.List]"`

This is of course that this is not an array of objects, but it would be great to be able to do a foreach operation on hashmaps like these as well.

Currently as part of a script processor, you can do something like this as an example:

```
processors": [
      {
        "script": {
          "lang": "painless",
          "source": """
          def entryset = ctx.system?.diskStorage?.entrySet();
          if (entryset != null) {
            for (def x : entryset) {
              x.getValue().Capacity = Integer.parseInt(x.getValue().Capacity.replace('%', ''));
            }
          }
          """
        }
      }
```

**Comment by scottdfedorov** [comment]
Following. I see this has been developed, but keeps getting bumped back. 7.11 to 12 to 13 now to 14... :(

**Comment by scottdfedorov** [comment]
Hooray for 7.15!
