### ISSUE TITLE
SnapshotRetentionTask#getAllRetainableSnapshots Exception Handling is Broken

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#55217]
If the callback used in this method encounters an exception (possible to trigger by e.g. concurrently deleting a repository but I bet there's lots of other possible ways of getting there via repo IO issues) then the `running` flag (https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L69) is never set to `false` again, apparently breaking SLM on a node until it is restarted because all future retention tasks will just be skipped.
We need to properly handle exceptions throughout to make sure we can't leak a state that doesn't return the flag to `false` right? (see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L274 which can throw for the exact broken spot)

**Comment by original-brownbear** [comment]
@dakrone this one looks pretty serious unless I'm missing some detail here, can you take a look please?

**Comment by dakrone** [comment]
@original-brownbear yeah, I will work on a fix for this today, I can switch this to use `ActionListener.wrap` which does the automatic wrapping. Thanks for finding this!
