### ISSUE TITLE
block-max WAND for function_score_query & collapse_top_docs_collector

### ISSUE THREAD

**Issue by unix1986** [elastic/elasticsearch#55222]
The block-max WAND algorithm in lucene，can it be applied to FunctionScoreQuery and CollapseTopDocsCollector？I think it can't，but i am not sure. I have not found the relevant implement in elasticsearch.

**Comment by javanna** [comment]
hi @unix1986 may I ask you to ask your question in our forums at https://discuss.elastic.co/? We reserve github issues for feature requests and confirmed bug reports. Thanks!

**Comment by unix1986** [comment]
> hi @unix1986 may I ask you to ask your question in our forums at https://discuss.elastic.co/? We reserve github issues for feature requests and confirmed bug reports. Thanks!

Oka, thanks!
