### ISSUE TITLE
I am crazy by elasticsearch, I just want to set the global default time zone to +8: 00 | 我想修改全局默认时区 

### ISSUE THREAD

**Issue by geekyouth** [elastic/elasticsearch#55234]
I am crazy by elasticsearch, I just want to set the global default time zone to +8: 00
I have been tormented by the time zone issue

我被 elasticsearch 逼疯了，我仅仅是想设置全局默认的时区为 +8:00
我已经被时区问题折磨到痛苦不堪

😫😫😫

**Comment by cbuescher** [comment]
Hi @geekyouth! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
