### ISSUE TITLE
EQL: Regex character classes are not supported

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#55231]
In the Python implementation, the [EQL `match` function](https://eql.readthedocs.io/en/latest/query-guide/functions.html#) supports [shorthand character classes](https://docs.oracle.com/javase/tutorial/essential/regex/pre_char_classes.html) for regular expressions (e.g., `[\s]`, `[\w]`, `[\d]`).

In the Elasticsearch implementation, the `match` function is converted into a [SQL `RLIKE` function](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-like-rlike-operators.html#sql-rlike-operator). The `RLIKE` function is then converted into a [`regexp` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) that uses [Lucene's regular expression engine](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html).

 However, Lucene's regular expression syntax does _not_ support these character classes.

### Next steps
We should discuss whether it is reasonable to add support for shorthand character classes in Elasticsearch.

At the least, we should update the documentation for the EQL `match` function and the SQL `RLIKE` function to note that character classes are not supported and point users to our regexp syntax documentation.

**Comment by markharwood** [comment]
I opened a [Lucene issue ](https://issues.apache.org/jira/browse/LUCENE-9336)to discuss.

**Comment by jrodewig** [comment]
The ES EQL docs for the `regex` keyword point to our docs for Lucene's [regular expression syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html). Now that [LUCENE-9336](https://issues.apache.org/jira/browse/LUCENE-9336) is resolved, we'll support the shorthand classes when ES updates to Lucene 9.0.
