### ISSUE TITLE
[Feature Request][Painless Lab] Adding support for _source context

### ISSUE THREAD

**Issue by P1llus** [elastic/elasticsearch#55259]
**Describe the feature**:

The Painless Lab feature would be a great tool for everyone that creates ingest pipelines if it was able to simulate a _source document context.

Currently context choices in Painless Lab is "Basic", "Filter" and "Score", adding a fourth that are able to simulate a document being processed by a ingest pipeline in at least some basic manner would be very beneficial.

Adding support to copy paste a full document and modify it in similar fashion to a ingest pipeline script processor would be great.

**Comment by rjernst** [comment]
Note that there is no "_source" context, there are contexts which give access to _source (and the way in which they expose it varies, eg ctx.source vs params._source). "Basic" is a raw script with no actual context; the only provided variables are params. We can certainly add other contexts manually, but each is cumbersome. I believe this issue overlaps with another we already have to add support for all scripting contexts: https://github.com/elastic/elasticsearch/issues/53703.

**Comment by stu-elastic** [comment]
We'd get this in #53703 since that would add the ingest context, all with the others, in the execute API.

Thanks for the feature request!  Please follow #53703.
