### ISSUE TITLE
[CI] ModelLoadingServiceTests.testMaxCachedLimitReached failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#55251]
There were recent changes to this test and it has just failed on `master` and `7.x` so I suspect something happened here. Didn't reproduce locally for me.

```
org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests > testMaxCachedLimitReached FAILED
    org.mockito.exceptions.verification.TooLittleActualInvocations: 
    trainedModelProvider.getTrainedModel(
        "test-cached-limit-load-model-1",
        true,
        <any>
    );
    Wanted 2 times:
    -> at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:186)
    But was 1 time:
    -> at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingService.loadModel(ModelLoadingService.java:209)
        at __randomizedtesting.SeedInfo.seed([3F1D5FFBB076DE4D:E279278987AADA40]:0)
        at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:186)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached" -Dtests.seed=3F1D5FFBB076DE4D -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=America/Merida -Dcompiler.java=14
```

master: https://gradle-enterprise.elastic.co/s/h52saigk4s3ji/tests/7bifs6bt3pimq-zvg6hwacrq4zu
7.x: https://gradle-enterprise.elastic.co/s/s4uvsitolnt56/tests/7bifs6bt3pimq-zvg6hwacrq4zu

**Comment by mark-vieira** [comment]
@davidkyle you made some recent changes here, do you mind taking a look?

**Comment by mark-vieira** [comment]
Muted this in `master` and `7.x` for now.

**Comment by jkakavas** [comment]
@mark-vieira did you mean to mute this but didn't for a reason ? I just hit this in a PR : https://gradle-enterprise.elastic.co/s/rotvbtqgmjnmo/console-log?task=:x-pack:plugin:ml:test 

It failed 2 times today so I'll mute it in master and 7.x

**Comment by jkakavas** [comment]
@davidkyle I think that #55307 might not have fixed this, I saw two failures today : https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testMaxCachedLimitReached),sort:!(time,desc))

**Comment by davidkyle** [comment]
Thanks for the ping @jkakavas 

I re-muted on master (23bb15f1f04d2edc117320bfcec9065f8972fc76) and 7.x (e99ef3542cf1746d20655b6d8badaf7e0e2d917e)

**Comment by davidkyle** [comment]
I unmuted the test and added trace logging in master e4af4b6f6c8c17e0a1c26c2d018f155a6e14a321

Will keep an eye out for failures and re-mute once I have the logs

**Comment by davidkyle** [comment]
The failure was captured with test logging in https://gradle-enterprise.elastic.co/s/en5fhzeraljde

Muted on master again in 7a79d1b28904d499a198ac6b1637b2af18bc95be
