### ISSUE TITLE
Node disk level shard allocation settings

### ISSUE THREAD

**Issue by ZLightning** [elastic/elasticsearch#55268]
**Describe the feature**:
Enable disk level shard allocation settings to tune performance and data persistence at the disk level.  For instance, in a single node cluster, maybe you want to assign a primary and a replica to the same node on different disks (and perhaps there's a way to optimize keeping them in sync since they are on the same node).  In another use case, you have a machine with a 1TB NVMe and a 10TB magnetic spinner and need to assign the most active shards to the NVMe before re-allocating them to the magnetic drive when they cool down.

Note, this is similar to #43518 and https://github.com/elastic/elasticsearch/issues/17213#issuecomment-383974707 but specific to disk level allocation.

**Comment by DaveCTurner** [comment]
It makes no sense to assign a primary and a replica to the same node: this consumes extra resources (disk space, filesystem cache etc) and offers no benefits over RAIDing the disks together.

The idea for heterogeneous storage duplicates https://github.com/elastic/elasticsearch/issues/28323, which we discussed some time back and decided to close. The recommended solution is to run multiple nodes.
