### ISSUE TITLE
Does es have the Incremental change function like mysql‘s binlog

### ISSUE THREAD

**Issue by q6413260** [elastic/elasticsearch#55277]
I want to subscribe es’s  Incremental change(some write events like mysql binlog) to trigger some business check event.
How can I achieve this goal？

**Comment by tvernum** [comment]
Hi @q6413260, Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to providing this sort of user advice. 

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by q6413260** [comment]
@tvernum Thank you for your answer
