### ISSUE TITLE
Dissect processor - Support Fixed length extraction 

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#55273]
Elastic maintains 3 implementations of the dissect processor. One in [beats](https://www.elastic.co/guide/en/beats/filebeat/master/dissect.html), one in [Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-filters-dissect.html), and another in Elasticsearch [ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/master/dissect-processor.html). 

In an attempt to maintain feature parity between the 3 implementation, we strive to maintain similarity through a [specification](https://github.com/elastic/dissect-specification) 

Beats is looking at implementing fixed length field extraction: https://github.com/elastic/dissect-specification/issues/6 via https://github.com/elastic/beats/pull/17191 and this issue is for the ingest node dissect processor to follow suite. 

The details of the change are described here: https://github.com/elastic/dissect-specification/issues/6.  If possible test cases should be shared between the implementations.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
