### ISSUE TITLE
[CI] RemoteClusterServiceTests.testCollectNodes fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55292]
Fails on 7.x:
https://gradle-enterprise.elastic.co/s/fggxy7emgdb7a

Cannot reproduce locally with
```
./gradlew ':server:test' --tests "org.elasticsearch.transport.RemoteClusterServiceTests.testCollectNodes" \
  -Dtests.seed=E8A58760A64ADCFF \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Canada/Pacific \
  -Dcompiler.java=14
```

Error in Logs:
```
java.lang.AssertionError: 
Expected: “no seed node left”
but: was “Unable to open any connections to remote cluster [cluster_2]”
at __randomizedtesting.SeedInfo.seed([E8A58760A64ADCFF:D2512FB984274F6]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.transport.RemoteClusterServiceTests.testCollectNodes(RemoteClusterServiceTests.java:661)
```

**Comment by cbuescher** [comment]
And another one also on 7.x: https://gradle-enterprise.elastic.co/s/gavowknd4ffs6

**Comment by javanna** [comment]
This test is failing again, failures are very similar to the previous ones: 

```
java.lang.AssertionError:
Expected: ("no seed node left" or "Unable to open any connections to remote cluster [cluster_2]") but: was "Unable to open any connections to remote cluster [cluster_1]"
```

https://gradle-enterprise.elastic.co/s/pm67pbkuwcgni/tests/:server:test/org.elasticsearch.transport.RemoteClusterServiceTests/testCollectNodes#1

**Comment by cbuescher** [comment]
@tbrooks8 just saw something similar again today on 7.x, seeing that the PR is still "backport pending", just wanted to check if we should reopen this issue in the meantime or if the backport is imminent? 

Failure: https://gradle-enterprise.elastic.co/s/p6pk2kwrvdztu
https://gradle-enterprise.elastic.co/s/p6pk2kwrvdztu/console-log?task=:server:test#L2881

**Comment by tbrooks8** [comment]
I will back port it today. Thanks for the reminder.
