### ISSUE TITLE
Allow to give IP range to network.publish_host

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch#55339]
**Describe the feature**:

In Docker Swarm cluster, if a container belong to 2 overlay networks:

- master node on network A
- client node on network A & B

we dont know the interface name and the real IP, so it's impossible to configure ``network.publish_host`` propertly. Hence the client node cannot be reached by the master.

At this time, we know the network name, and the IP range.

``network.publish_host`` (and ``transport.publish_host``) could accept:

- IP Range
- IP subnet: "10.0.1" ==> "must match all ip prefixed by 10.0.1"

**Workaround**

- Try one by one the network interfaces (eg: ``transport.publish_host=_eth0_``, ``transport.publish_host=_eth1_``, ...) until find the good one
- Find the right IP at runtime, and set ``transport.publish_host`` env: 
``env transport.host=$(getent hosts | grep 10.0.1 | awk '{print $1}')``

**Comment by ebuildy** [comment]
Thanks you, I took Swarm as an example, but I am sure there are other environnements also impacted.

Why the client node dont send to master all possible IPs addresses, then the master could choice automatically the one accessible?

**Comment by DaveCTurner** [comment]
I checked a few other common environments and I think this difficulty is pretty much unique to Docker Swarm. You can certainly control the interface name when running outside of containers. On EC2 you can set the device index of an ENI which controls the interface name. According to section 4.1.2.1.5 of [this document](https://github.com/k8snetworkplumbingwg/multi-net-spec/blob/8b8456011d971291cc9badd37d58881d8c7aa3f2/v1.1/%5Bv1.1%5D%20Kubernetes%20Network%20Custom%20Resource%20Definition%20De-facto%20Standard.pdf) you can specify the name of extra interfaces in Kubernetes too.

**Comment by ebuildy** [comment]
Yes I agree,

And the workaround is quite easy to do (just a single line of shell) ``env transport.host=$(getent hosts | grep 10.0.1 | awk '{print $1}')``
