### ISSUE TITLE
Debian repository / package naming

### ISSUE THREAD

**Issue by sammcj** [elastic/elasticsearch#5536]
The current (partially documented) system from http://www.elasticsearch.org/blog/apt-and-yum-repositories is non-standard for Debian and very hard to maintain.

You essentially need to change your apt sources for every Elasticsearch release.

It might be good to move to package-name based versioning, i.e:

```
# /etc/apt/sources.list.d/elasticsearch.list
deb http://packages.elasticsearch.org/elasticsearch stable main
```

Then can install the ES major version package of your choosing, leaving 'stable' to determine the latest stable minor release from ES:

```
apt-get install elasticsearch-1.1
```

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/13971
