### ISSUE TITLE
I am unable to use script field in another script field as parameter.On running the below query dsl the value of b field is coming to be "a"

### ISSUE THREAD

**Issue by samara-101** [elastic/elasticsearch#55381]
{
  "size": 10,
  "timeout": "45000ms",
  "query": {
    "bool": {
      "filter": [
        
        {
          "query_string": {
            "query": "*",
            "fields": [],
            "type": "best_fields",
            "default_operator": "or",
            "max_determinized_states": 10000,
            "enable_position_increments": true,
            "fuzziness": "AUTO",
            "fuzzy_prefix_length": 0,
            "fuzzy_max_expansions": 50,
            "phrase_slop": 0,
            "escape": false,
            "auto_generate_synonyms_phrase_query": true,
            "fuzzy_transpositions": true,
            "boost": 1
          }
        },
        
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [],
    "excludes": []
  },
  "stored_fields": "*",
  "docvalue_fields": [
    {
      "field": "@timestamp"
    }
  ],
  "script_fields": {
    "a": {
      "script": {
        "source": "return 1",
        "lang": "painless"
      },
      "ignore_failure": false
    },
    "b": {
      "script": {
        "source": "if(params.pr != null){return params.pr}",
        "lang": "painless",
        "params": {
          "pr": "a"
            
          
        }
      },
      "ignore_failure": false
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "aggregations": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "time_zone": "Asia/Kolkata",
        "interval": "1w",
        "offset": 0,
        "order": {
          "_key": "asc"
        },
        "keyed": false,
        "min_doc_count": 1
      }
    }
  },
  
}

**Comment by albertzaharovits** [comment]
@samara-101  this is indeed not possible.

In the future please head over to our discuss forum where questions like this are usually answered, see https://discuss.elastic.co/t/is-it-possible-to-use-a-scripted-field-inside-a-scripted-field/129598 .
