### ISSUE TITLE
[Feature Request][KV Processor] Add support for whitespace lenient mode

### ISSUE THREAD

**Issue by P1llus** [elastic/elasticsearch#55415]
**Describe the feature**:

Reproducing certain older modules from logstash to beats there was one thing that came up a few times, that would also come up in the future when more focus is put on ingest pipelines for ingesting logs from beats.

In logstash, when utilising the KV filter, it has a whitespace argument, which can be set to either strict or lenient. This allows you to set a field separation as whitespace, while values can still also include whitespaces as well and can make KV in many use-cases much easier to use without having to modify the incoming data first.

This does has some impact on performance, so keeping this as a option (default to off) would be a good way to add this option if it's feasible at all.

Another option could be to be able to add both the key, separator and value in one regex as a argument. This would allow us to check each kv pair against one or more patterns.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
