### ISSUE TITLE
Store different index files into different directories in Lucene

### ISSUE THREAD

**Issue by Jie1-Hou** [elastic/elasticsearch#55438]
**Describe the feature**: Currently Lucene can only store all kinds of index files into the same directory, and the price and performance of storages are so different from HDD to NVMe disk right now. To get higher performance with low price, could we introduce a new feature to store segment files and important index files like .nvd .dvd. tim .doc .dim into a different directory which can be in a NVMe disk, and still keep other files into original directory which is in a HDD disk?

**Comment by markharwood** [comment]
Thanks for this request, @Jie1-Hou 
If this were to be considered it would start with a change to Lucene which currently assumes all segment files for a Lucene index exist in the same directory. I would therefore suggest opening a ticket on the [Lucene list](https://issues.apache.org/jira/projects/LUCENE/issues) and see how that pans out before opening an elasticsearch issue.
If you don't mind I will close this issue.

**Comment by markharwood** [comment]
Thanks for this request, @Jie1-Hou 
We are aware that Lucene does include a `FileSwitchDirectory` which allows for this sort of separation but we have chosen not to expose this because it would be both hard to administer and provide robust support.  I'll leave the issue open to see if there's any further comments.

**Comment by Jie1-Hou** [comment]
Great! So we already have a mechanism in Lucene. I think we can introduce one or two new options to define directory and which index files need to switch in elasticsearch.yml for advanced users.

**Comment by Jie1-Hou** [comment]
Hybirdfs has used FileSwitchDirectory of Lucene from elasticsearch 7. Easy to enhance Hybirdfs logic to support this feature, made a little modification on my own branch as a sample: https://github.com/Jie1-Hou/elasticsearch/commit/ba2a9b3434c45aa4dc4a3bfd741433bf5bfcd712

**Comment by ywelsch** [comment]
These ideas have been discussed before (a variant of this was to store the translog in a location separate to the index). Just using `FileSwitchDirectory` is not sufficient here, that's the easy part. This would have to be integrated with Elasticsearch's shard allocation and management logic (e.g. taking disk space usage of the different parts of the shard into account for shard balancing, or deleting files in multiple directories in case the shard is deallocated), which introduces some extra complexity.

**Comment by Jie1-Hou** [comment]
Thanks ywelsch, also confirmed FileSwitchDirectory usage had been removed from elasticsearch 7.3 since issue LUCENE-8835, which doesn't support both directories point to the same underlying FS directory, it seems this request won't trigger this issue.

**Comment by Jie1-Hou** [comment]
introduced a new plugin named store-switchfs to support this feature: https://github.com/Jie1-Hou/elasticsearch/commit/0fe6a442255a5077ffb1720938c33518b3a8cc3b

**Comment by Jie1-Hou** [comment]
Store.tryOpenIndex function uses SimpleFSDirectory class to open index files directly without checking index.store.type, it breaks FileSwitchDirectory class usage, enhanced this logic: https://github.com/Jie1-Hou/elasticsearch/commit/c061eb946530cf05cadbca43e41c7bdb5478d2d8

**Comment by Jie1-Hou** [comment]
will check other shard allocation and management logic, to enable FileSwitchDirectory class usage.

**Comment by original-brownbear** [comment]
Closing here this does not seem to be something we will do in the foreseeable future.
