### ISSUE TITLE
MetadataTests#testSerialization fails on 7.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55449]
I have only observed this locally atm but can reproduce on 7.x with
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.MetadataTests.testSerialization" \
  -Dtests.seed=707475CF4BFA0EDA:F2C6C3B0B9E46633 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-RS \
  -Dtests.timezone=America/Yakutat \
  -Dcompiler.java=14
```

I get an AssertionError when creating the random test instance:
```
org.elasticsearch.cluster.metadata.MetadataTests > testSerialization FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([707475CF4BFA0EDA:F2C6C3B0B9E46633]:0)
        at org.elasticsearch.cluster.metadata.Metadata$Builder.buildIndicesLookup(Metadata.java:1458)
        at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1406)
        at org.elasticsearch.cluster.metadata.MetadataTests.randomMetadata(MetadataTests.java:1106)
        at org.elasticsearch.cluster.metadata.MetadataTests.testSerialization(MetadataTests.java:1065)
```

I don't know if that assertion is off or if the random test object violates some basic assumtions, e.g. with this seed DataStreamTests#randomIndexInstances() sets `numIndices` to 0, and when forcing this the test always fails. Not sure if the fix should be to relax assertion or to prevent those values in randomization.

**Comment by cbuescher** [comment]
@martijnvg not sure if this is your area, please reassign if I'm wrong.

**Comment by cbuescher** [comment]
Also found a recent failure of this on CI here https://gradle-enterprise.elastic.co/s/n3tvz3kpvq646

**Comment by danhermann** [comment]
@cbuescher, the backport [here](https://github.com/elastic/elasticsearch/pull/55455) will resolve this test failure. Sorry for the noise.

**Comment by danhermann** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/55455
