### ISSUE TITLE
Add (Hard-) Limit to SLM Snapshot Frequency?

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#55450]
Currently, users can get their clusters into some trouble by accidentally setting a second-scale SLM snapshot frequency.
E.g. accidentally setting something like 10s that is short enough to finish a snapshot (because the cluster contents barely changed) could lead to a situation where the repository metadata size grows enormously by accident.

Should we add some hard limit to the snapshot frequency in SLM? (e.g. 5 min)

**Comment by original-brownbear** [comment]
cc @nachogiljaldo

**Comment by jakelandis** [comment]
We discussed today , and this sounds like a good idea. Since it is a cron expression, it is a bit more challenging to enforce, but still do-able.

**Comment by joegallo** [comment]
On the opposite side, what about preventing SLM schedules like once every thousand years?

**Comment by dakrone** [comment]
> what about preventing SLM schedules like once every thousand years?

We shouldn't prevent this, and we shouldn't prevent schedules that never execute (such as `* * * 31 FEB ? *`), because SLM policies can still be manually executed on an as-needed basis.
