### ISSUE TITLE
Elasticsearch iNotify not being sent to systemctl / systemd

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch#55477]
Elasticsearch version: 7.6.x
Plugins installed: none
JVM version: OpenJDK 9
OS version:4.15.0-76-generic
Description of the problem including expected versus actual behavior: 
Running ES as a systemd service on different builds of the same OS fails on some instances. 
Symptoms indicate iNotify on socket for "notify" systemd setting might not be sent by ES once it starts up. 
```
[Service]
Type=notify
...
ExecStart=/home/xxx/Projects/elasticsearch-7.6.2/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --verbose
(Use any static path in place of /home...)
```
On 
```
systemctl start elasticsearch times out, while ES starts up successfully. Then systemctl kills ES as notification has not been received. 
```

**Comment by jasontedor** [comment]
Can you clarify how you've installed Elasticsearch? It looks like you've installed it from the tar.gz archive, and created a systemd service unit yourself?

**Comment by svanschalkwyk** [comment]
We installed from the RPM on RHEL with the same issue on one machine. 
This example above is from the tarball.

**Comment by jasontedor** [comment]
With the tar.gz archive, we do not bundle the systemd module that invokes the `sd_notify` call when Elasticsearch is ready. So, for the tar.gz archive, this behavior is expected.

Are you saying though that you're seeing this issue from the RPM? That would be unexpected. Please clarify.

**Comment by svanschalkwyk** [comment]
I took the service file from the deb for this instance. 
Our client insists on different file paths, and relocating the rpm is not an option. 
What does one have to do to to the tarball extract to enable the iNotify systemd notification?

**Comment by jasontedor** [comment]
There is not the option to enable it, the code is simply not bundled with the tar.gz archive.

**Comment by svanschalkwyk** [comment]
Any indication of which files have to be changed/added/copied from deb to make this happen? All file paths have to be changed from the rpm/deb install for this env.

**Comment by michaelcizmar** [comment]
I faced the same issue.  I download the tar.gz file file and implemented a elasticsearch.service file it basically times out.  I don't see anywhere that there is reasonable cause for this not to work.    Why is the code not bundled with the tar.gz file?

**Comment by jasontedor** [comment]
It's simply because our expectation was that users that wanted to install Elasticsearch as a systemd service would use the RPM or the Debian packages, and the tar.gz archive is cross-platform. We're happy to revisit this, but that was our thinking.

**Comment by svanschalkwyk** [comment]
Jason, could you point me to the file(s) that need to be modified please? This is an urgent issue as we have been receiving this request from a number of clients.

**Comment by jasontedor** [comment]
Do you have to deploy this service of type `notify`?

**Comment by michaelcizmar** [comment]
Thanks Jason.  Appreciate that insight.  In my particular case, I've got a customer who has some interesting ideas about where things should go so we opted for the tar.gz and eventually did get it "working" but I'm confirming if it's ideal or suitable.

**Comment by michaelcizmar** [comment]
In my case, we opted not use use the notify.  If we could get the documentation updated I think that would be helpful in my case.

**Comment by jasontedor** [comment]
Sure @michaelcizmar. Can you suggest what documentation you would like updated, and what guidance you would like to see there?

**Comment by svanschalkwyk** [comment]
@jasontedor Add a systemd script to the tarball with instructions on how to get ES to message on iNotify socket. That's all I need.

**Comment by michaelcizmar** [comment]
Agreed.  Just a little note on the systemd page so that you don't attempt to user the other script as a reference.

**Comment by Omer-N** [comment]
It really should be stated in the documentation that `tar.gz` version comes without this module.

**Comment by michaelcizmar** [comment]
Thanks for updating the documentation.  However, I do not think that updating the documentation resolves the issue.  My preference would be for consistency in all downloads where reasonably possible.  Adding one line to the documentation will still cause people to trip over this.

Other than preference, you've given no reason why this was designed this way.

**Comment by tumbl3w33d** [comment]
> will still cause people to trip over this

Yep, here we go. Thankfully it was figured out in the [linked issue](https://github.com/wazuh/wazuh-packages/issues/666#issuecomment-803044675).

But look what it made them do. So let's get back to @jasontedor 's offer:

> It's simply because our expectation was that users that wanted to install Elasticsearch as a systemd service would use the RPM or the Debian packages, and the tar.gz archive is cross-platform. We're happy to revisit this, but that was our thinking.

systemd seems to be pretty much the standard in most distros, so it seems like a sane default to package the systemd module (it's just 28K) and rather check for an env like `NOTIFY_SOCKET=/run/systemd/notify` to decide whether to send a signal instead of looking at the archive type used for installation.

Apart from that, I cannot quite comprehend the association of "user who wants to use systemd" with RPM/DEB. I, for example, am an arch user (we like informing people about it 😉) and while I could convert the deb, it seems more intuitive (and less complicated) to go with the cross-platform archive. I took inspiration from the deb, but this missing signal behavior really surprised me and it looks like only dirty hacks can save me for now. I'm automating the entire installation btw., so it's not like I would copy things around once and forget about this issue.
