### ISSUE TITLE
Improve "put template" error message and documentation of disallowed characters

### ISSUE THREAD

**Issue by hatharom** [elastic/elasticsearch#55606]
Couldn't find anything in the documentation.
The examples are with *.

I have tried with ?  - while  PUT-ing a template - which was rejected:
` "index_patterns": ["test?"]`
response:
> "reason": "index_template [temp1] invalid, cause [Validation Failed: 1: template must not contain the following characters [ , \", *, \\, <, |, ,, >, /, ?];]"

which is interesting because the error message contains the * as well.

How can I define an index pattern for this?:    prefix-anyword-number    
right now I am doing this: prefix-*-* , which is terrible imo.

Or is it only supports the asterisk?

**Comment by cbuescher** [comment]
Hi @hatharom,

you can find the code checking the validity of the index patters in [MetaDataIndexTemplateService](https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexTemplateService.java#L279). Looking at this, the following characters seem to be forbidden:
<Space>, `,`, `#`, `_` and the ones mentioned in [Strings](https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/common/Strings.java#L376), with the notable exception of the asterisk (see https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/common/Strings.java#L389). The error message is indeed misleading here, we should correct that and maybe also document the (dis)allowed characters better.

**Comment by cbuescher** [comment]
@hatharom hope you don't mind me changing the subject of this issue, so its clear its not just a usage question. For pure usage questions we generally prefer asking in the support forums over at https://discuss.elastic.co so we can keep Github issues only for bug reports and feature requests, but since the error message is misleading and the `index_patterns` documentation probably needs updating I think we should keep this open.

**Comment by Boda805** [comment]
Hi I'd be interested in taking this on. Would be my first issue so I may need extra guidance.

**Comment by abprash** [comment]
Is someone working on this ? @hatharom , @cbuescher . If not, can i work on this?

**Comment by cbuescher** [comment]
@abprash sorry, I think this was adressed by https://github.com/elastic/elasticsearch/pull/56170 and this issue can be closed.
