### ISSUE TITLE
Enhance Repository Third Party Tests to Cover Large Files

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#55642]
Currently our third party tests for Azure, GCS and S3 only run a very rudimentary snapshot and restore cycle without much data in it. This means we don't have full coverage of the blobstore APIs since uploading and (at least in the case of GCS) downloading will behave differently for files above a certain size threshold.
S3 will eventually switch to multi-part uploading, GCS will switch to resumable uploads etc. Currently, these APIs are only covered by our own mock REST-API based implementations of these services.

To validate changes like https://github.com/elastic/elasticsearch/pull/55506 we should have a test that will upload and restore at least one file large enough to trip these thresholds. We can do this the same way we do it in the mock API based tests, by indexing a large number of documents and then merging down to a single segment to get a large file.

**Comment by jasontedor** [comment]
Note that in #55421 I took a different approach which was to enable changing in tests the threshold at which the "large file" APIs are used, so that at least for the write path in GCS, this code path is now being tested in the mock tests locally and in CI against the real service.

**Comment by original-brownbear** [comment]
Right, that covers things well API wise. 

I think we should still (especially when it comes to GCS) test actual large files. We've definitely left the territory of what the SDK does with reading arbitrarily large chunks in a single stream (#55506) and we're thinking about doing the same for writes. There is no clear documentation on the limits on the chunk sizes for GCS unfortunately so we should have tests to make sure it's supported and stays supported IMO.

**Comment by original-brownbear** [comment]
We have `org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase#testSnapshotWithLargeSegmentFiles` now which should cover this.
