### ISSUE TITLE
[ML] Support scripted metric in datafeed aggs

### ISSUE THREAD

**Issue by tveasey** [elastic/elasticsearch#55674]
Currently, this fails generating an unsupported `agg` error. For example, the result type for the following example `agg` is a single numeric value for which we could run anomaly detection:
```
GET /event_data/_search
{
  "aggs": {
    "time": {
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "15m",
        "time_zone": "UTC",
        "min_doc_count": 1
      },
      "aggs" : {
        "@timestamp":{
          "max":{"field":"@timestamp"}
        },
        "amount_sum": {
          "scripted_metric": {
            "init_script": {
              "source": "state.amount = []"
            },
            "map_script": {
              "source": "state.amount.add(doc['amount'].value)"
            },
            "combine_script": {
              "source": "def sum = 0.0; for (c in state.amount) { sum += c } return sum"
            },
            "reduce_script": {
              "source": "def sum = 0.0; for (a in states) { sum += a } return sum"
            }
          }
        }
      }
    }
  }
}
```

\cc @dimitris-athanasiou.

**Comment by dimitris-athanasiou** [comment]
`ScriptedMetric` has a `Object aggregation()` method that returns its value. That object could be many things depending on the script (according to the docs):

- primitive types
- String
- Map (containing only keys and values of the types listed here)
- Array (containing elements of only the types listed here)

We could easily add support for it by excluding maps and arrays. Maps we certainly can't support. Arrays might be valid for our `lat_long` function. But I'm not sure it makes sense to produce a lat_long using a scripted metric. @benwtrent What are your thoughts on this?

**Comment by benwtrent** [comment]
I don't think we should support `scripted_metric`. 

There are too many edge cases.

 It can return completely different object types based on different buckets (`if (_value == 1){ return 0;}else{return [foo: 'bar'];}`).

**Comment by dimitris-athanasiou** [comment]
We need to gather use cases before we further discuss this.

**Comment by benwtrent** [comment]
I am closing this. No further discussion. While runtime_fields add us further expressiveness and flexibility, scripted_metric MAY open doors for us in the future, but we would need some sort of guarantee around the return type. 

Closing until a real use case manifests itself.
