### ISSUE TITLE
[Feature Request][Ingest Pipeline] Adding a Copy processor

### ISSUE THREAD

**Issue by P1llus** [elastic/elasticsearch#55682]
**Describe the feature**:

Currently it is not possible to copy a object to another object.

An example would be during ingestion, to populate all the source and destination ECS fields, and in plenty of use-cases these have to be copied to client/server fields as well.

Currently its not possible to use the set processor to set the value of the "client" object to the value of "source" object.

This combined with https://github.com/elastic/elasticsearch/issues/54783 creates a situation in which we have to rely on a large amount of set + painless conditions for each and every field.

Source and Destination alone is large objects, so 30 fields would result in 30 set processors each with at least 1 painless script condition since we cannot check for null inside the processor.

If we was able to duplicate a object to a new object, and either copy it directly to root or define the path (if you want to copy it deeper than root) then it would create very big benefits for us when creating ingest pipelines.

**Comment by danhermann** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/63540
