### ISSUE TITLE
'processors' configuration parameter ignored on official docker container

### ISSUE THREAD

**Issue by Jamalarm** [elastic/elasticsearch#55731]
**Elasticsearch version**: 7.6.1

**Plugins installed/JVM version/OS version**: Official docker container

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I am trying to limit the size of thread pools on a local elastic search test cluster using the `processors` setting described here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#processors

We start our test clusters using the unmodified official docker containers, then configure them using environment variables. This works for all configuration parameters we have so far tried, with the exception of the `processors` setting.

Providing an environment variable of `processors:2` does not seem to be picked up. On my dev machine this is still showing as `24` everywhere, and the threadpools remain too large.

Please let me know if this is a known limitation, or if I need to provide that setting some other way. For various reasons, it would be pretty difficult to use the in-built docker CPU limiting to achieve this so I'd rather use the native ES way if possible.

**Comment by jasontedor** [comment]
The setting `processors` has been deprecated. In 7.6 you can use the setting `node.processors`, which would be compatible with the way that we translate environment variables to settings within our Docker images. It looks like we missed updating this in the docs, which I will address.

**Comment by jasontedor** [comment]
I pushed 423afbff22ce1dad445e1b29447346e35b1ed788 to 7.6 and ec095760d41738916a1d00965d5262786282fdba to 7.7. Since this was a partial backport of #54855, I pushed directly.
