### ISSUE TITLE
Potential bug for 3d point arrays in geo_polygon queries

### ISSUE THREAD

**Issue by mbarretta** [elastic/elasticsearch#55741]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.6.2

**JVM version** (`java -version`):
ESS

**OS version** (`uname -a` if on a Unix-like system):
ESS

**Description of the problem including expected versus actual behavior**:
When using a 3d points array in a `geo_polygon` query, it results in an exception

**Steps to reproduce**:

```
PUT /example
{
    "mappings": {
        "properties": {
            "location": {
                "type": "geo_point"
            }
        }
    }
}

POST /example/_doc?refresh
{
    "location": [13.400544, 52.530286]
}

GET /example/_search
{
    "query": {
        "geo_polygon": {
            "location": {
                "points": [
                    [
                       [13.0, 53.0], 
                       [14.0, 52.0]                
                    ],
                    [
                       [13.0, 53.0], 
                       [14.0, 52.0]                
                    ]                   
                ]
            }
        }
    }
}
```

**Output**:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "numeric value expected"
      }
    ],
    "type" : "parse_exception",
    "reason" : "numeric value expected"
  },
  "status" : 400
}
```

**Comment by mbarretta** [comment]
Maybe related to https://github.com/elastic/elasticsearch/pull/40447

**Comment by iverase** [comment]
I had a look and that format is not supported (those are not 3d point arrays). The error might be clearer but it is clearly not supported. As geo_polygon query is deprecated in favour of geo_shape query I am going to close this without further action,
