### ISSUE TITLE
How to run elasticsearch source code specified test case 

### ISSUE THREAD

**Issue by deanjo** [elastic/elasticsearch#55769]
Hello I downloaded the source code of elasticsaerch6.8.3 and imported IntelliJ idea I want to run the specified test case in idea and set a breakpoint
 For example org.elasticsearch.document.DocumentActionsIT # testIndexActions

My operation is as follows
Select the specified unit test case, right-click debug to run
But I found that this will run a lot of test cases and the breakpoints I set are not entered during the operation, which makes me very confused
I checked a lot of documents and found no how to run the specified unit test cases in idea

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by deanjo** [comment]
why closed ???????????????
