### ISSUE TITLE
503 error when use low level api

### ISSUE THREAD

**Issue by andyyumiao** [elastic/elasticsearch#55771]
**When i create es instance with bellow code:**
RestClient restClient = RestClient.builder(
      HttpHost.create("http://xxx.xx.com")).build();
**then call the method: restClient.performRequest, i got 503 error:**
org.elasticsearch.client.ResponseException: method [GET], host [http://xxx.xx.com], URI [megacorp/employee/_search], status line [HTTP/1.0 503 Service Unavailable]
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

**But run curl command is ok: curl http://xxx.xx.com**

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
