### ISSUE TITLE
I want to use nori plugin in elasticsearch 5.4.2, how to do?

### ISSUE THREAD

**Issue by nissansz** [elastic/elasticsearch#55778]
I want to use nori plugin in elasticsearch 5.4.2, how to do?

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
