### ISSUE TITLE
Create annotations on significant model changes.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#55781]
In order to give users more insight into anomaly detection, we could be creating an annotation every time there is a significant change in the model calculation. Some ideas on what to report are:
- step change detected
- periodicity detected
- trend detected

How this could work technically:
- CPP emits log messages with special marker string denoting log message related to a significant model change
- Java adds a hook to `CppLogMessageHandler` class so that every time such message is discovered, an annotation is created
- Annotation is automatically visible in the UI, just like user-created annotations or other system-created annotations (e.g.: model snapshot annotation)
- When job is deleted, we don't need to delete the annotations as they provide history that the user may want to retain

**Comment by droberts195** [comment]
Fixed by elastic/ml-cpp#1247
