### ISSUE TITLE
[7.x] RelocationIT.testIndexSearchAndRelocateConcurrently failed a few times

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#55806]
Example failure:

Build 20200427124217-E6E26461
Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+EAR/576/console
Build Scans https://gradle-enterprise.elastic.co/s/o72idc3h2fn5g

Repro lines:
```
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.recovery.RelocationIT.testIndexSearchAndRelocateConcurrently" \
  -Dtests.seed=E6953C1AD4610C2 \
  -Dtests.security.manager=true \
  -Dtests.locale=it \
  -Dtests.timezone=Portugal \
  -Dcompiler.java=14 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.recovery.RelocationIT.testIndexSearchAndRelocateConcurrently" \
  -Dtests.seed=E6953C1AD4610C2 \
  -Dtests.security.manager=true \
  -Dtests.locale=it \
  -Dtests.timezone=Portugal \
  -Dcompiler.java=14 \
  -Druntime.java=8
```

Does not reproduce locally.

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/55799.

**Comment by przemekwitek** [comment]
It also failed on master:

Build 20200427054840-B5C596C5
Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/590/console
Build Scans https://gradle-enterprise.elastic.co/s/sjowlrjl7qmaq
