### ISSUE TITLE
DST is not honored when searching by rounded dates on query_string

### ISSUE THREAD

**Issue by adagios** [elastic/elasticsearch#55813]
**Elasticsearch version** (`bin/elasticsearch --version`):

Running on docker with `docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.6.2`

```
{
"type": "server", 
"timestamp": "2020-04-27T14:25:52,730Z", 
"level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", 
"node.name": "d34756e67976", 
"message": "version[7.6.2],
 pid[1],
 build[default/docker/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z], 
OS[Linux/4.19.76-linuxkit/amd64], 
JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]"
}
```
**Plugins installed**: []
none

**JVM version** (`java -version`):
AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8

**OS version** (`uname -a` if on a Unix-like system):
Linux/4.19.76-linuxkit/amd64

**Description of the problem including expected versus actual behavior**:

When searching for a date with query_string with date rounding, DST is not taken into consideration. The query `some_date:2020-10-25||/d` does not match the indexed value of `2020-10-25T00:00:00+01:00` that is correct for Lisbon Portugal.

It works if searching for a date range (i.e. `some_date:[2020-10-25 TO 2020-10-25]`).

**Steps to reproduce**:

```
curl -XDELETE "http://localhost:9200/testes-dst"
curl -XPUT "http://localhost:9200/testes-dst"

# create a mapping with a date
curl -XPUT "http://localhost:9200/testes-dst/_mapping" -H 'Content-Type: application/json' -d'
{
  "properties": {
    "data":{
      "type": "date"
    },
    "quantidade": {
      "type": "integer"
    }
  }
}'

# index the day before: 2020-10-24 00:00:00 WET (+01:00)
curl -XPOST "http://localhost:9200/testes-dst/_doc" -H 'Content-Type: application/json' -d'
{
  "data": "2020-10-24T00:00:00+01:00",
  "quantidade": 1
}'
# index DST change day: 2020-10-25 00:00:00 WET (+01:00)
curl -XPOST "http://localhost:9200/testes-dst/_doc" -H 'Content-Type: application/json' -d'
{
  "data": "2020-10-25T00:00:00+01:00",
  "quantidade": 1
}'
# index the day after: 2020-10-24 00:00:00 WET (+00:00)
curl -XPOST "http://localhost:9200/testes-dst/_doc" -H 'Content-Type: application/json' -d'
{
  "data": "2020-10-26T00:00:00+00:00",
  "quantidade": 1
}'
```

The following work as expected, returning the single hit:

```
# search for the day before (no problems)
curl -XGET "http://localhost:9200/testes-dst/_search?q=data:2020-10-25||\/d"

# search for the day after (no problems)
curl -XGET "http://localhost:9200/testes-dst/_search?q=data:2020-10-26||\/d"

{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"testes-dst","_type":"_doc","_id":"N88ivHEBo5SSWgbqZgTU","_score":1.0,"_source":
{
  "data": "2020-10-26T00:00:00+00:00",
  "quantidade": 1
}}]}}
```

But the day of the change in DST doesn't, returning 0 hits:

```
# seach for the change day by date rounding
curl -XGET "http://localhost:9200/testes-dst/_search?q=data:2020-10-25||\/d"

# seach for the change day by date rounding with time_zone param
curl -XGET "http://localhost:9200/testes-dst/_search" -H 'Content-Type: application/json' -d'
{
  "query": {
    "query_string": {
      "time_zone": "WET",
      "query": "data:2020-10-25||\\/d"
    }
  }
}'

{"took":3,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
```

It only works if using a date range:
```
# seach for the change day by date range with time_zone param
curl -XGET "http://localhost:9200/testes-dst/_search" -H 'Content-Type: application/json' -d'
{
  "query": {
    "query_string": {
      "time_zone": "WET", 
      "query": "data:[2020-10-25 TO 2020-10-25]"
    }
  }
}'
```

**Comment by cbuescher** [comment]
From a first look it seems like the `timezone`  parameter in the query isn't considered at all in these cases. Explain output of 
```
GET /testes-dst/_validate/query?explain=true
{
  "query": {
    "query_string": {
      "time_zone": "+06:00",    <--- also try UTC, +01:00, CET
      "query": "data:2020-10-25||\\/d"
    }
  }
}
```
shows we always get a range query with "explanation" : "data:[1603584000000 TO 1603670399999]"

Will check if this was always the case or try to narrow down when this started.

**Comment by adagios** [comment]
> Will check if this was always the case or try to narrow down when this started.

We've seen this since ES 5.6, so it's pretty old.

**Comment by cbuescher** [comment]
Yes, the behaviour you mention seems to have been around for a long time. I think the "normal" way users interact with date fields in query string queries is via using the `[...]` syntax. When using your example (even without the date math and without DST), the query parser tries to build a single term query, which we then rewrite to a range query in our date field mapper logic (https://github.com/elastic/elasticsearch/blob/7.6/server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L370). 
Unfortunately the timezone information that gets used correctly when using "range" syntax is lost at that point. I have a draft for a way to force creation of a range query with correct time zone which I'll open a PR for, but we might have to discuss the desired behaviour here in some more depth.
