### ISSUE TITLE
IS there any way to delete some of the request parameters settled default by myself? 

### ISSUE THREAD

**Issue by Tasselmi** [elastic/elasticsearch#55839]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.2

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.1

**OS version** (`uname -a` if on a Unix-like system):
centos 7.0

**Description of the problem including expected versus actual behavior**:
when I use 7.6 client to delete multi-doc from 6.3.2 server, error here:
`contains unrecognized parameter: [ignore_throttled]"}],"type":"illegal_argument_exception"`

**Steps to reproduce**:

 1. IS there any way to delete some of the request parameters settled default by myself? 
 2.
 3.

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
