### ISSUE TITLE
Elasticsearch multi-layer remote cluster is invalid

### ISSUE THREAD

**Issue by jiankunking** [elastic/elasticsearch#55849]
Initial requirements

[https://github.com/elastic/kibana/issues/64267](https://github.com/elastic/kibana/issues/64267)

Set up the es cluster as shown below：

![1](https://user-images.githubusercontent.com/15723050/80473969-75e1c580-8979-11ea-8336-98119bbe1da0.png)

However, the following anomalies are found:
`at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:214) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:139) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) ~[elasticsearch-7.6.2.jar:7.6.2]", "at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]", "at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]", "stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [][10.133.0.89:9300] general node connection failure", "at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]", "at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]", "Caused by: java.lang.IllegalStateException: Received message from unsupported version: [6.5.1] minimal compatible version is: [6.8.0]", "stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [][10.163.204.195:9300] general node connection failure", "at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.lambda$onResponse$2(TcpTransport.java:979) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.6.2.jar:7.6.2]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]", "at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]", "at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]", "at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]", "at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleResponse(TransportHandshaker.java:139) ~[elasticsearch-7.6.2.jar:7.6.2]", "at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225) ~[elasticsearch-7.6.2.jar:7.6.2]", "at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]", "at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]", "at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]", "at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) ~[?:?]", "at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]`

So I rebuilt the es cluster, as shown in the following figure:

![2](https://user-images.githubusercontent.com/15723050/80475306-46cc5380-897b-11ea-9a64-01de13caee6e.png)
However, I found that in kibana, I still could not see the data of each es cluster in the blue box。

**Is it because remote cluster cannot multilayer proxy?**

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
