### ISSUE TITLE
v2.3.2 have only SNAPSHOT version

### ISSUE THREAD

**Issue by yixingzhong** [elastic/elasticsearch#55843]
hi, i want to modify elasticsearch of v2.3.2 source code, but i cant find release version.
can you help me? thanks!!!

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
