### ISSUE TITLE
Additional way for elasticsearch [ Feature request]

### ISSUE THREAD

**Issue by BigGitWorld** [elastic/elasticsearch#55841]
Hello.
Please look at the [GridDB](https://github.com/griddb/griddb_nosql) architecture (a key-container No-SQL database) for the IoT scenarios.
I think it would be great if the elasticsearch can also store data as the key-container (key=thing UUID, container = data of that thing in ONE document). I think this architecture improves the search performance even more than now.

**Comment by pgomulka** [comment]
hey @BigGitWorld 
I think you can use elasticsearch as a key-value store. However you have to bear in mind of the underlying architecture and the fact that elasticsearch is using inverted indices and analyzer framework for searches.

**Comment by pgomulka** [comment]
I am gonig to close an issue, if you feel that the issue needs more discussion - feel free to reach out/reopen

**Comment by BigGitWorld** [comment]
Hey@pgomulka
I know how the elasticsearch works.
I think you can add some configuration to consider IoT application scenarios, so that keep inverted index architecture too.
Elasticsearch claculates the inverted index for every document. but in the IoT scenarios, you don't need it always and most of the time you want to store a huge volume of streaming data (hundreds of thousands per second for example). 
Please look at the GridDB architecture to find the solution.
They have extended the normal key-value to key-container, so that user can have both of them.
For example:
User should be able to specify the scenario in the index configuration:
If user specified that he/she want normal indexing (key-value), elasticsearch behaves normal.
If user specified that he/she want to store doc as a key-container, elasticsearch have to save that document in a separate package (the index has its own package) and therefore whenever user wants to search for specific IoT devices, elasticsearch can only search inside of that package not whole of the data store.
Am I wrong?
