### ISSUE TITLE
ILM Rollover on the first of the month

### ISSUE THREAD

**Issue by Gunnerva** [elastic/elasticsearch#55861]
**Describe the feature**:
With the elasticsearch ILM policy you can set the index to rollover based on the min_age, however in some instances it would be nice if you could rollover on the first of the month regardless of the month.  Using min_age of 30 or 31 (ignoring February) would not work due to different number of days per month.

It would be nice to have a new flag that was possibly in additon to min_age could possibly have roll_on_first = true or something along those lines.

**Comment by Tommmster** [comment]
This would be helpful for the `delete` phase as well

**Comment by dakrone** [comment]
We discussed this today, but we are reluctant to add calendar support to something within ILM, as dealing with absolute times based on a calendar introduces a large amount of complexity we would like to eschew. As such we've decided to close this for now.

An alternative exists where time-based index names are used (for example, with something like logstash using `yyyy-MM`), where ILM can still be used without ILM handling the rollover.
