### ISSUE TITLE
[CI] org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testDoNotWaitForCompletion

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#55875]
This failed on 7.x with a time out.

Build scan: https://gradle-enterprise.elastic.co/s/4slsedxex4eei

Repro line:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testDoNotWaitForCompletion" -Dtests.seed=8B437416A10AF044 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=be -Dtests.timezone=Africa/Algiers -Dcompiler.java=14 -Druntime.java=8
```

**Comment by mark-vieira** [comment]
I've muted this in `master` and `7.x` (failing in both). 

I just now noticed that @dnhatn has added some additional logging here though. Please feel free to unmute if you need to capture more info, but let's try and remute quickly since this is failing several times a day.

**Comment by dnhatn** [comment]
Sure, thanks for the ping @mark-vieira.

**Comment by dnhatn** [comment]
Log: [log.txt](https://github.com/elastic/elasticsearch/files/4566895/log.txt)
