### ISSUE TITLE
Smartcn analyzer fails on Emoji

### ISSUE THREAD

**Issue by rickardp** [elastic/elasticsearch#55913]
**Elastic version ** 7.6.2

**Plugins installed**: [analysis-smartcn, analysis-icu]

**JVM version** (`java -version`): (Official Docker image)

**OS version** (Official Docker image)

**Description of the problem including expected versus actual behavior**:

After switching from the default tokenizer to the smartcn_tokenizer, the unit tests we have on Emojis fail with

Elasticsearch.Net.ElasticsearchClientException : Request failed to execute. Call: Status code 400 from: PUT /search_zh-223d4ef3396c4be183a6e0824e2e3e56. ServerError: Type: illegal_argument_exception Reason: "failed to build synonyms" CausedBy: "Type: parse_exception Reason: "Invalid synonym rule at line 16" CausedBy: "Type: illegal_argument_exception Reason: "term: 🏖️ analyzed to a zero-length token"""

We expected that emojis continues to work as with the default tokenizer.

**Steps to reproduce**:

 1. Add synonym token filter mapping an Emoji (such as above) to a word.
 2. Switch to the smartcn tokenizer
 3. Observe the exception above

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
The `smartcn` tokenizer does not understand emoji natively. Emoji sequences (🇫🇷) for instance are divided into multiple tokens but single code point emoji like  🏖️ shouldn't be removed. I tested with the following mapping and it works as expected:
`````
{
    "settings": {
        "index": {
            "analysis": {
                "analyzer": {
                    "synonym": {
                        "tokenizer": "smartcn_tokenizer",
                        "filter": [
                           "synonym"
                        ]
                    }
                },
                "filter": {
                    "synonym": {
                        "type": "synonym",
                        "synonyms": [
                            "🏖️ => baz"
                        ]
                    }
                }
            }
        }
    },
    "mappings": {
        "properties": {
            "text": {
                "type": "text",
                "analyzer": "synonym"
            }
        }
    }
}
`````
Can you provide us with the mapping that fails on your case ?

**Comment by jimczi** [comment]
We don't plan to add support for emoji sequences in the smartcn tokenizer so I hope you don't mind if I close this issue. You should use the `icu` tokenizer which handles emojis natively.

**Comment by rickardp** [comment]
Cool, we have since worked around it by moving the logic to application code. There is still a difference here in how the tokenizer handles emoji, but it seems then this is the intended behavior.
