### ISSUE TITLE
ILM include description of step in the _ilm/explain api

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#55949]
ILM will normally try to execute as many steps as possible but the `AsyncWaitAction` steps are checked only when the ILM loop runs (this runs every `indices.lifecycle.poll_interval`). 

It can be hard for a user to debug why an `AsycnWaitAction` step is not run even though `_ilm/explain` shows the lifecycle on that step (and the user can check the condition the step is trying to execute is met)

It would be useful for the `_ilm/explain` api to return some business domain information about what the step is, what it does and gotchas about how/when it runs, how expensive it is, other (?) 
This could be static information returned by every step in a `description() -> String` method. 

I realise the proposed description to be returned is very broad but it will have to be decided on a step by step basis.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
