### ISSUE TITLE
Get API, refresh=wait_for not allowed

### ISSUE THREAD

**Issue by aCLr** [elastic/elasticsearch#55970]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.4.2, reproduced for 7.6

**Plugins installed**: []

**JVM version** (`java -version`): 

**OS version** (`uname -a` if on a Unix-like system): Linux archlinux 5.6.7-arch1-1 #1 SMP PREEMPT Thu, 23 Apr 2020 09:13:56 +0000 x86_64 Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
```
DELETE test 
PUT test/_doc/1
{
  "foo": "bar"
}
GET test/_doc/1?refresh=wait_for
# {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [wait_for] as only [true] or [false] are allowed."}],"type":"illegal_argument_exception","reason":"Failed to parse value [wait_for] as only [true] or [false] are allowed."},"status":400}
``` 

**Provide logs (if relevant)**:

Here is a discussion about that bug: https://discuss.elastic.co/t/get-api-refresh-wait-for-not-allowed/230396

**Comment by dadoonet** [comment]
Was tested also on 7.6. The documentation says it's supported for the GET document API but it's not.

**Comment by ywelsch** [comment]
This has never been supported in any ES version, but was inadvertently introduced by a [docs change](https://github.com/elastic/elasticsearch/pull/45416) which shared the refresh definition with other commands.

@debadair can you make a docs fix?

**Comment by dserdyuk** [comment]
same for _delete_by_query https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-api-query-params

**Comment by ywelsch** [comment]
The docs are confusing indeed. In [another section of the same docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#_refreshing_shards) it states that "unlike the delete API, it does not support wait_for."

@jrodewig can you have another look?

**Comment by jrodewig** [comment]
Thanks for re-opening @ywelsch @dserdyuk. I've opened a PR to fix this for delete by query and a few other APIs:
https://github.com/elastic/elasticsearch/pull/74749
