### ISSUE TITLE
Int 32 overflow on geo centroid aggregation

### ISSUE THREAD

**Issue by angeloprobst** [elastic/elasticsearch#55992]
https://github.com/elastic/elasticsearch/blob/6f244eb167edb7a4d262fb7626ffc9cdb2c8d60a/server/src/main/java/org/elasticsearch/search/aggregations/metrics/geocentroid/InternalGeoCentroid.java#L109

We have a Elasticsearch with billions of docs with geopoint and this local variable (int totalCount) is being overflowed when a bucket has more than 2.147Bi docs.

**Comment by talevy** [comment]
Hi @angeloprobst! thank you so much for reporting this issue. Terribly sorry you ran into this as your reduced so many points! The issue should be resolved in the versions listed as labels in #56370.

**Comment by angeloprobst** [comment]
Hi guys.
Any chance to have this fix applied to ES 6.x.x series?
Thanks.
Regards,
Angelo

**Comment by talevy** [comment]
Hi @angeloprobst thanks for bringing that up. 6.8.x is unfortunately in a maintenance mode where we would likely only deliver a new patch release for higher impact items than this. Sorry to say that. Let me know if you'd like some assistance in getting prepared to upgrade to the next released version with this bug fix, I'd be happy to help!
