### ISSUE TITLE
Azure and GCS Repositories Needlessly Limit Chunk Size?

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#56018]
Currently, the Azure repository plugin seems to allow for a max chunk size of 256M only and the GCS repository is even limited to 100M.
For the S3 repository on the other hand we allow a maximum of 5TB for the chunk size and at least default to 1GB.

Chunking large files this heavily incurs a lot of overhead writing and restoring large files form the repositories. We are using multi-part uploading and its equivalents on all three implementations (S3, GCS, Azure) so there really is no need to artificially chunk files at all.

For S3 you could make an argument to chunk files because third party implementations of S3 might not like very large blobs. 

For GCS and Azure I think we should simply set the chunk size to the maximum size allowed by the services by default (5T and 4T respectively). This will speed up restores of large files, keep the blob count in the repository lower (waste less resources on iterating through shard directories on deletes for example).

=> Is there any reason to keep the manual chunking around? If not we should go ahead with optimizing this. The longer we keep this kind of chunking the more slow snapshots/repositories we create.

**Comment by original-brownbear** [comment]
We discussed this during snapshot resiliency sync and the consensus was that there isn't a good reason to have chunk sizes smaller than the maximum supported by the underlying blob store set per default.

=> We should adjust the default chunk size setting to the maximum blob size for each underlying blob store.
=> Keep the setting around for now in case this is causing issues in an unexpected case.
=> Document the change

**Comment by DaveCTurner** [comment]
Someone mentioned in the sync that we should document this as a breaking change but the conversation moved on before I had a chance to disagree, so I'm raising that here. I don't think we need to call the change to the default a breaking change. The default is already `Long.MAX_VALUE` on `FsRepository`, and we only need to care about the official services for the other repositories (plus Minio which [claims to support objects up to 5TB](https://github.com/minio/minio/blob/master/docs/minio-limits.md#limits-of-s3-api) just like S3 proper).

I think there's value in keeping the setting around indefinitely however, there are situations where the maximum blob size supported by the repository may be under the user's control (e.g. CephFS) or may not correspond with the maximum filesize of the data store.

**Comment by original-brownbear** [comment]
++ David, updated my comment accordingly.
