### ISSUE TITLE
SQL: range queries on dates do not pass along the timezone

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#56049]
When dealing with a time interval, the user timezone is not set on the [range](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html) (meaning `gt`, `lt`, etc..) query which can lead to problems when dealing with relative intervals (such as 1d).

**Comment by matriv** [comment]
`master` : 300f010c0b18ed0f10a41d5e1606466ba0a3088f
`7.x` : cc214685594ccb24ae33ffd4e3b28056652e1fa0
`7.7` : 86db5bcfbc77a362b3b827af98f6f7cfe3573d68
