### ISSUE TITLE
rest high level client dynamic query generation support

### ISSUE THREAD

**Issue by FuncGuy** [elastic/elasticsearch#56102]
Hi,

Using rest high level client it is not possible to generate a dynamic query for more details.

https://stackoverflow.com/questions/61587399/elasticsearch-rest-high-level-client-aggregate-fields-dynamically

please suggest an a answer for this.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/) or in your case keep it on the original platform Stackoverflow. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I
hope you don't mind that I close this.
