### ISSUE TITLE
Third part test builds failing due to missing task

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#56165]
After merging https://github.com/elastic/infra/pull/20008 our third part test builds are now failing for branches older than `7.x`.

```
Project 'searchable-snapshots' not found in project ':x-pack:plugin'.
```

CC @tlrx

**Comment by tlrx** [comment]
I reverted the changes so that third part tests should be green again, until we implement the right approach. Thanks @mark-vieira and sorry again for the noise.

**Comment by tlrx** [comment]
I opened #56587 for this.
