### ISSUE TITLE
[Transform] Stats return wrong count after upgrade

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#56196]
**Severity**: low 
**Affected version**: `7.4` -

`_transform/{id}/_stats` can return a wrong count after a rolling upgrade. This happens only if > 1 config documents exist, which can only happen if the transform got updated with `_transform/{id}/_update`

The issue has been found in upgrade tests, see below.

Root cause: When expanding the id's the hit count is returned for `count` which contains duplicates when config documents for the same transform exist in more than 1 index.

The race only exists for roughly `1s` as old configs get deleted during `_transform/{id}/_update`, the delete call is not waiting for a flush.

### Original issue:

see: https://gradle-enterprise.elastic.co/s/pe4tc7q3kxd2w/tests/uw5bo54r7qs3g-ocnko4nkedlpa

```
[2020-05-05T19:17:28,791][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "count" : 2,
      "transforms" : [
        {
          "id" : "mixed-simple-continuous-transform",
          "state" : "stopped",
          "stats" : {
            "pages_processed" : 1,
            "documents_processed" : 0,
            "documents_indexed" : 0,
            "trigger_count" : 2,
            "index_time_in_ms" : 0,
            "index_total" : 0,
            "index_failures" : 0,
            "search_time_in_ms" : 2,
            "search_total" : 1,
            "search_failures" : 0,
            "processing_time_in_ms" : 0,
            "processing_total" : 1,
            "exponential_avg_checkpoint_duration_ms" : 28.0,
            "exponential_avg_documents_indexed" : 0.0,
            "exponential_avg_documents_processed" : 0.0
          },
          "checkpointing" : {
            "last" : {
              "checkpoint" : 1,
              "timestamp_millis" : 1588681048540,
              "time_upper_bound_millis" : 1588675648540
            },
            "changes_last_detected_at" : 1588681048540
          }
        }
      ]
    }
  }
}]
```

**Comment by jtibshirani** [comment]
We observed a potentially related failure `TransformSurvivesUpgradeIT`: https://gradle-enterprise.elastic.co/s/2rj2qhjzx3kja. I muted this test for now.

**Comment by hendrikmuhs** [comment]
> We observed a potentially related failure `TransformSurvivesUpgradeIT`: [gradle-enterprise.elastic.co/s/2rj2qhjzx3kja](https://gradle-enterprise.elastic.co/s/2rj2qhjzx3kja). I muted this test for now.

Thanks @jtibshirani, this is now tracked in #56269. As far as I debugged it, this is a different issue (but might be caused by the same commit).
