### ISSUE TITLE
API endpoint for previewing composed result of an index template v2

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#56255]
Users will want to know what the final result of an index template will be once all of its component templates, mappings, settings, and aliases have been applied. This will be mostly useful during the creation process, so that users can have confidence that an index template they're building will behave as expected.

**Comment by cjcenizal** [comment]
Related to https://github.com/elastic/elasticsearch/pull/55686

**Comment by dakrone** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/56390
