### ISSUE TITLE
Surface metadata about which index templates use a component template

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#56256]
It will be useful to know if a component template is being used by any index templates and, if so, which ones. Users will be able to delete any unused component templates this way, and be able to trace a component template back to where it's being used to gain context around its configuration.

**Comment by dakrone** [comment]
I don't think we should do this, as the information is pretty easily obtainable from listing all index templates. We also tend not to duplicate information about this in other APIs (for instance, we don't list all the indices using an ILM policy when you retrieve a policy)

**Comment by cjcenizal** [comment]
> We also tend not to duplicate information about this in other APIs

As a counterpoint, data streams and indices contain references to each other, which is what lead me to think of this option.

> the information is pretty easily obtainable from listing all index templates

You're right. We'll implement this solution in Kibana. I'll close this issue for now until we discover any problems with this approach.
