### ISSUE TITLE
[Transform] Make transforms work with data streams

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#56270]
Once data streams are released users will expect to be able to run continuous transforms against them.

This may require extra support in the transforms code.  To some extent transforms should be able to treat data streams like aliases, but there are subtle differences regarding how access permissions work, so there may need to be code changes in this area.  It certainly needs testing.

The related UI issue is elastic/kibana#65438

**Comment by hendrikmuhs** [comment]
:+1: I think data streams are great for continuous transforms.

IMHO make it work is not enough, I think we should strive for proper integration. This requires some more work on the backend, e.g. using a data stream it should not be required to configure synchronization (only on or off?).

**Comment by hendrikmuhs** [comment]
data stream support has been added with #58280

I will open a new issue regarding improvements.
