### ISSUE TITLE
ForecastIT#testOverflowToDisk failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#56280]
This occasionally ( [3 times since April 21](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(summary,branch,build-id,stacktrace),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testOverflowToDisk),sort:!(time,desc)))) fails due to insufficient disk space on the runner. 

Example https://gradle-enterprise.elastic.co/s/373f7jrrzzbkw/console-log?task=:x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner

**Comment by droberts195** [comment]
This is the same problem as #58806: EAR builds.  Although this one was opened earlier I'll close it in favour of #58806 as that contains more comment and analysis.
