### ISSUE TITLE
DefaultAuthenticationFailureHandler does not update with license changes

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#56318]
`DefaultAuthenticationFailureHandler` determines the set of response headers based on the active realms at startup.

However, the Realms list may be empty if the node thinks it has a TRIAL or BASIC license at startup (because we default security off in those cases).
The handler is never updated if the license state changes.

**Comment by BigPandaToo** [comment]
@tvernum I have tried to reproduce the scenario and tend to think it was indeed a network problem. When at startup (unless security is explicitly disabled) we always add a default header `DefaultAuthenticationFailureHandler` to:
`if (failureResponseHeaders == null || failureResponseHeaders.isEmpty()) {
            this.defaultFailureResponseHeaders = Collections.singletonMap("WWW-Authenticate",
                       Collections.singletonList("Basic realm=\"" + XPackField.SECURITY + "\" charset=\"UTF-8\""));
 }`
We also add Realms dispite the current license and always add default ones.
I tried upgrading both from Trial and Basic to Gold and everything works properly - authentication dialog pops up after upgrade.
