### ISSUE TITLE
search_as_you_type doesn't work with multi-field

### ISSUE THREAD

**Issue by CSharpBender** [elastic/elasticsearch#56326]
**Elasticsearch version** (`bin/elasticsearch --version`):
Elasticsearch 7.6.1
**Plugins installed**: []
Nest 7.6.1
**JVM version** (`java -version`):
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
**OS version** (`uname -a` if on a Unix-like system):
Linux c87e626860d1 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Create _title_ of type `search_as_you_type` with field _sortable_
```
PUT my_test
{
  "mappings": {
    "properties": {
      "title": {
        "type": "search_as_you_type",
        "fields": {
          "sortable": {
            "type": "keyword",
            "ignore_above": 256,
            "normalizer": "lowercase_normalizer"
          }
        }
      }
    }
  },
  "settings": {
    "analysis": {
      "normalizer": {
        "lowercase_normalizer": {
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        }
      }
    }
  }
}
```

No error but the sortable field is not present in the mapping
```
{
  "my_test" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "title" : {
          "type" : "search_as_you_type",
          "max_shingle_size" : 3
        }
      }
    },
    "settings" : {
      "index" : {
        "number_of_shards" : "1",
        "provided_name" : "my_test",
        "creation_date" : "1588843483989",
        "analysis" : {
          "normalizer" : {
            "lowercase_normalizer" : {
              "filter" : [
                "lowercase"
              ],
              "type" : "custom"
            }
          }
        },
        "number_of_replicas" : "1",
        "uuid" : "fhsaD0XzRhalwzqMNAfrxQ",
        "version" : {
          "created" : "7060199"
        }
      }
    }
  }
}
```

**Comment by telendt** [comment]
I also encountered this problem - I believe it's because `search_as_you_type` fields create their own sub-fields. One simple workaround for this is to move search_as_you_type field to sub-field as well, and define top field as text field (not indexed if it's not really used for anything), e.g.:

```
PUT my_test
{
  "mappings": {
    "properties": {
      "title": {
        "type": "text",
        "index": false,
        "fields": {
          "prefix": {
            "type": "search_as_you_type"
          },
          "sortable": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```

That said I think this should  be solved either by merging user defined sub-fields with SAYT sub-fields (`_Xgram`, `_index_prefix`) or forbidding defining `fields` in SAYT fields definition (+documenting this shortcoming and workaround).

**Comment by aneeshpanoli** [comment]
@telendt Thank you!
In my case, I had to do both `more like this` and 'search as you type' on the same field. However `more like this` only works on 'keywords'. I followed your direction and was able to fix it. I had to set `index=true` though.

**Comment by xeraa** [comment]
Maybe we could add a comment to the docs that you should change the order of analyzers to avoid the problem? Keep `search_as_you_type` in the subfield — using the initial example here:

```
PUT my_test
{
  "mappings": {
    "properties": {
      "title": {
        "type": "keyword",
        "ignore_above": 256,
        "normalizer": "lowercase_normalizer"
        "fields": {
          "searchable": {
            "type": "search_as_you_type",
          }
        }
      }
    }
  },
  "settings": {
    "analysis": {
      "normalizer": {
        "lowercase_normalizer": {
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        }
      }
    }
  }
}
```

**Comment by dpkirchner** [comment]
Was this bug/issue ever resolved? I'm not able to do this on 7.13.0 so I'm guessing not.

If it's not going to happen may I suggest:

- Documenting that you can't add your own fields, with an officially recommended workaround
- Returning an error when you try, instead of silently accepting the mapping update request

**Comment by roytmana** [comment]
I could not find any guidance on whether `search_as_you_type` type could be used as as subfield or main field with subfields 
from my testing in 7.15 when using it as main type any additional subfields that I define in my mappings are not created. when using it as a subfield type (ex `prefix` subfield of `subjects` field it to work by creating `subjects.prefix._2gram` and other subfields (have not tested in detail but search on `subjects.prefix._2gram` works)

This would be, in my opinion, desired behavior but I could not find anything in the docs confirming it to make sure we can use it safely

could anyone confirm and perhaps update docs please?

**Comment by roytmana** [comment]
Highlighting does not work in this case
it does work if search_as_you_type used for the main field although not very precisely - it tends to highlight entire field rather than individual fragments in most cases

```
{
  "query": {
    "multi_match": {
      "query": "Fed. regulations",
      "type": "bool_prefix", 
      "fields": [
        "subjects.prefix",
        "subjects.prefix._2gram",
        "subjects.prefix._3gram"
      ]
    }
  },
  "highlight": {
    "require_field_match":"false", 
    "fields": {
      "subjects.prefix._index_prefix":{}
    }
  }
}
```

**Comment by javanna** [comment]
@romseygeek could have a quick look at this? As far I can see from the code, search as you type field mapper does not do anything with it's declared fields. Could it support multi-fields instead or is there a reason that it does not? Trying to figure out if we need to fix the code or the docs.
