### ISSUE TITLE
Cancel transport request handling on disconnection

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#56327]
Since #43332 we cancel the handling of some REST requests when the REST channel closes, on the grounds that we cannot respond on a closed channel so there's no point in carrying on with its computation.

Relatedly, when a node N leaves the cluster all the other nodes will close their connections to N, which means that the results of any ongoing requests that N is handling will also ultimately be discarded. Should we therefore cancel the corresponding tasks and save a bunch of effort?

Relates #55566 in which a node leaves the cluster due to overload but then carries on being overloaded for longer than the user expects since it carries on doing the work that caused the overload until completion.

**Comment by dnhatn** [comment]
+1. Today we already [cancel](https://github.com/elastic/elasticsearch/blob/44b5c2550178ba8a0456008181e96f78e7c0a823/server/src/main/java/org/elasticsearch/tasks/TaskManager.java#L445) child tasks when the node with the parent task leaves the cluster. However, it's at the node-level. We would react more quickly with the connection level. I am working on a task heartbeat component that detects orphaned tasks (i.e., the parent task was gone) and cancels them. I will try to integrate this suggestion into it.
