### ISSUE TITLE
Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc in product names

### ISSUE THREAD

**Issue by scottbolasevich** [elastic/elasticsearch#56344]
Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc

Preconditions
magento 2.3.4 and elastic search 6+ on nexcess

Magento Version : 2.3.4

ElasticSuite Version : 6.0

Environment : production

Third party modules : no

Steps to reproduce
1.https://www.goinggreensolutions.com.au/
2. search "eco max"
3. you can see here https://prnt.sc/s8v1k7

Expected result
normal search results
{
"title": "Eco",
"num_results": "242"
},
Actual result
[Screenshot, logs] sql error
https://www.goinggreensolutions.com.au/search/ajax/suggest/?q=eco+max&_=1588277353486
{
"title": "eco max brush' AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 EN",
"num_results": "267"
}
https://prnt.sc/s8v1k7

**Comment by scottbolasevich** [comment]
FYI i dont need a test box or anything either. .this problem is all over the internet look at all the sites with this issue.. it must be from a special character in the product title/name or something not being escaped properly

https://prospecelectronics.com/search/ajax/suggest/?q=prv
http://www.northfalmouthrentals.com/catalogsearch/ajax/suggest/?q=EKGQ
https://noti.nu/catalogsearch/ajax/suggest/?q=car

i mean there are literally hunderds of sites with this problem i can use google like a scanner and just give you a ton of results.. you can see here also effecting there front end https://prnt.sc/s8vai5

so this is likley a wide spread problem on like every installation of elastic search either that or ALOT of people including myself have it misconfigured?? any info here would be great

**Comment by romseygeek** [comment]
Hi @scottbolasevich , can you add the exact query you're sending to elasticsearch?  It's difficult to tell where the issue might be from a website front end.

**Comment by scottbolasevich** [comment]
Sure thing easiest way is to go to https://www.goinggreensolutions.com.au/ and search for "eco max"

**Comment by romseygeek** [comment]
Sorry, I mean the json payload that you send over the wire to elasticsearch

**Comment by scottbolasevich** [comment]
The REQUEST is

https://www.goinggreensolutions.com.au/search/ajax/suggest/?q=eco+max&_=1588860063378

The JSON Payload it returns is 

[{"title":"Eco max","num_results":"245"},{"title":"eco max brush' AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 EN","num_results":"10"},{"title":"eco max brush%' AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 E","num_results":"5"},{"title":"eco max brush) AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 EN","num_results":"2"},{"title":"eco max brush","num_results":"60"},{"title":"eco max brush AND 1615=(SELECT UPPER(XMLType(CHR(60)||CHR(58)||CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113)||(SELECT (CASE W","num_results":"4"},{"title":"eco max brush') AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 E","num_results":"1"},{"title":"eco max brush AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 END","num_results":"138"}]

Does that help?

**Comment by romseygeek** [comment]
OK.  This looks like you've got a problem at ingest time, as your documents are being added with this extra SQL cruft somehow.  Would you mind taking this to the discuss forums at https://discuss.elastic.co as I think this is likely to be a configuration issue rather than a bug in ES itself, and we like to keep github specifically for bug reports and enhancement requests.  Thanks!

**Comment by scottbolasevich** [comment]
that would be amazing i just made an account scottbolasevich... do you need to send me a invite to something or where do i go? thank you!

**Comment by scottbolasevich** [comment]
FYI the site is hosted at nexcess and i previously had a ticket open with them they said it was a bug.. so this could be good for ALOT of people cause whatever you share i will go back to the host with as well.. alot of people have the issue

**Comment by romseygeek** [comment]
You should just be able to https://discuss.elastic.co/c/elasticsearch/6 and start a new topic.  I'll close this ticket out and we can continue over there.
