### ISSUE TITLE
ElasticSearch7.1  query cache invalid

### ISSUE THREAD

**Issue by lmlsky** [elastic/elasticsearch#56355]
![image](https://user-images.githubusercontent.com/6120644/81309161-3459c480-90b5-11ea-9d00-5bd425b5d9b3.png)

**Comment by lmlsky** [comment]
1：GET my_index/_stats/query_cache,request_cache

  "_all" : {
    "primaries" : {
      "query_cache" : {
        "memory_size_in_bytes" : 0,
        "total_count" : 0,
        "hit_count" : 0,
        "miss_count" : 0,
        "cache_size" : 0,
        "cache_count" : 0,
        "evictions" : 0
      },

2：dsl
GET /_search
{
  "query": { 
    "bool": { 
      "must": [
        { "match": { "title":   "Search"        }},
        { "match": { "content": "Elasticsearch" }}
      ],
      "filter": [ 
        { "term":  { "status": "published" }},
        { "range": { "publish_date": { "gte": "2015-01-01" }}}
      ]
    }
  }
}

**Comment by romseygeek** [comment]
Hi, I'm not clear on what you think the bug is here?

**Comment by lmlsky** [comment]
if i use dsl filter , query_cache. hit_count  shouldn't be zero all the time

**Comment by romseygeek** [comment]
You need to re-use it a few times before it typically gets cached, what happens if you issue the query four or five times and then check the stats?

**Comment by lmlsky** [comment]
Hi~ romseygeek
1：Reference document links
     https://www.elastic.co/guide/en/elasticsearch/reference/7.6/query-cache.html
2：I tested it more than 1,00 times，the result is the same

**Comment by romseygeek** [comment]
How much data is there in your index? We also don't enable caching on segments that are smaller than 10,000 docs, or that make up less than 3% of the total index.

**Comment by lmlsky** [comment]
oh，I only have 20 docs. Can I enable it by config?

**Comment by romseygeek** [comment]
If you only have 20 docs, then the overhead of caching is going to wipe out any advantages you get by not having to re-run the query.

Seeing as this is an issue of configuration rather than a bug, I hope you don't mind if I close this - we prefer to keep github for bug reports and enhancement requests.  If you still have questions, please do start a thread at https://discuss.elastic.co

**Comment by lmlsky** [comment]
Thank you very much.
see you discuss
