### ISSUE TITLE
Sort fields should return formatted values

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#56364]
Unlike `stored_fields` and `docvalues_field`, the `sort` values returned by search requests are displayed as raw values. The sort value for a `date` field for instance, returns a `long` that represents the time in UTC since epoch. For consistency and to avoid leaking the format of the internal storage, we should return the display form of the value like we do in `stored_fields` and `docvalues_field`. 
This should also be consistent with `search_after` that allows to provide  formatted values already.

**Comment by javanna** [comment]
There are no concrete plans to work on this issue. Closing.
