### ISSUE TITLE
[CI] testRandomTimeIntervalRounding Failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#56400]
**Build scan**: https://gradle-enterprise.elastic.co/s/plit7g4fdojhi/tests/

**Repro line**: 
```
./gradlew ':server:test' \
--tests "org.elasticsearch.common.RoundingTests.testRandomTimeIntervalRounding" \
-Dtests.seed=DE09A1CC10383EB0 -Dtests.security.manager=true \
-Dtests.locale=ca-ES -Dtests.timezone=Etc/GMT+1 \
-Dcompiler.java=14 -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure excerpt**:
```
Expected [148 MINUTES in America/Menominee] to \
 round [2008-11-02T07:50:16.470Z] \
    to [2008-11-02T06:56:00Z] but instead rounded \
    to [2008-11-02T07:56:00Z]
at __randomizedtesting.SeedInfo.seed([DE09A1CC10383EB0:7D4B1688B8C503D4]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.common.RoundingTests.testRandomTimeIntervalRounding(RoundingTests.java:410)
```

**Comment by tvernum** [comment]
Ping: @nik9000 because this looks related to #56371

**Comment by rjernst** [comment]
> Reproduces locally?: No

Not sure why, but this *does* reproduce for me.

**Comment by nik9000** [comment]
Sorry folks! I'll dig as soon as I wake up for real. Feel free to revert if
it is loud.

**Comment by nik9000** [comment]
This doesn't reproduce for me, but I bet it is variable depending on the tzdb file that is in the distribution. Fun times. I was able to make some tests fail by running the random tests a ton of times. I'm going to fix those and hope that fixes this.

**Comment by nik9000** [comment]
OK! It looks like I made some assumptions about the shape of the "current transition list" vs the "future transition rules" that was incorrect. It caused duplicate transitions in my list which oddly, never broke with time *unit* rounding, but does break with time *interval* rounding. They do use different strategies, especially around overlaps. Anyway, the tzdb for `America/Tijuana` has a similar behavior for me locally so I can reproduce this issue. Probably.

I'll open a PR with assertions that'll trip if we hit this.

**Comment by martijnvg** [comment]
Just an fyi, another instance of this failure: https://gradle-enterprise.elastic.co/s/2ua7hql4oeqec/tests/:server:test/org.elasticsearch.common.RoundingTests/testRandomTimeIntervalRounding#1

**Comment by nik9000** [comment]
I opened a PR to fix it. It looks like about 10% of the tests fail my machine. I'm kind of surprised I didn't bump into this.
