### ISSUE TITLE
[ML] Force closing an ML job can leave unfinished forecast jobs behind

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#56419]
**Affected versions**:  6.1 - 

**Problem**

When a ml job is force closed the native process gets terminated without waiting for unfinished forecasts. These forecasts end as `started` or in progress but will never finish. This is only a reporting problem, there are no hanging processes or tasks.

**Mitigation**

Delete using the UI or the [API](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-delete-forecast.html)

**Fix discussion**

A force close should cleanup queued forecasts or mark them as failed.

**Comment by sophiec20** [comment]
Please confirm if this mitigation is correct. Error seen when attempting to delete forecast job indicates it `needs to be either FAILED or FINISHED to be deleted`.

Provided there are no hanging processes or threads, the impact is forecast docs in the results index, which is undesirable especially for large forecasts. 

Agree that force closing the anomaly detection job should also ensure forecast jobs are cleaned up. Suggest we also have a force delete for forecasts for consistency.

**Comment by droberts195** [comment]
> When a ml job is force closed the native process gets terminated without waiting for unfinished forecasts

The same thing also happens when a node running a forecast leaves the cluster for any reason.  (Power failure, bug, planned upgrade - any reason.)

We should probably check for and clean up forecast statuses in the persistent task assignment.  When a job is getting assigned to a new node we know that any forecasts that were in progress on the old node have failed.

**Comment by dimitris-athanasiou** [comment]
While #57152 allows for such incomplete forecasts to be deleted, should we still mark such forecasts as failed on force-close/task allocation?

**Comment by droberts195** [comment]
> we still mark such forecasts as failed on force-close/task allocation?

I think we should.  #57143 is supposed to do that (although I haven't reviewed it).

**Comment by hendrikmuhs** [comment]
Good point about not being able to delete forecasts using the UI for this case. I updated the mitigation with a DBQ.
