### ISSUE TITLE
elasticsearch requires initial heap size === max heap size even if bootstrap.memory_lock=false

### ISSUE THREAD

**Issue by mikkorantalainen** [elastic/elasticsearch#56422]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.0

**Plugins installed**: none

**JVM version** (`java -version`):
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-2ubuntu116.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-2ubuntu116.04, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
$ uname -a
Linux worker1 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 16.04.6 LTS

**Description of the problem including expected versus actual behavior**:
To reduce memory usage we would like to run elasticsearch with as little memory as possible. To make this possible, we'd need to set -Xms to much lower value than -Xmx. However, the check in BootstrapChecks.java always enforces -Xms == -Xmx. This is a bug and this code is missing a check similar to MlockallCheck which has

 if (BootstrapSettings.MEMORY_LOCK_SETTING.get(context.settings()) && !isMemoryLocked())
...

but the code in BootstrapCheckResult does not have similar check.

**Steps to reproduce**:
Set jvm.options initial and max heap usage to different values, for example:

-Xms50m
-Xmx1000m

**Provide logs (if relevant)**:

systemd[1]: Starting Elasticsearch...
elasticsearch[11874]: ERROR: [1] bootstrap checks failed
elasticsearch[11874]: [1]: initial heap size [52428800] not equal to maximum heap size [1048576000]; this can cause resize pauses and prevents mlockall from locking the entire heap

**Comment by mikkorantalainen** [comment]
s/BootstrapCheckResult/HeapSizeCheck/

**Comment by mikkorantalainen** [comment]
See also:
https://github.com/elastic/elasticsearch/blob/f5827ba0aed662c90648dcae168750396d59877d/docs/reference/setup/sysconfig/swap.asciidoc#enable-bootstrapmemory_lock

**Comment by jasontedor** [comment]
It’s not only related to memory locking, there are also resize pauses.

> To reduce memory usage we would like to run elasticsearch with as little memory as possible. 

Then you need to set Xmx lower, allowing Xms to be less than Xmx doesn’t help you in this goal of the heap size can increase up to Xmx, and Xmx is too large for your use case.

**Comment by mikkorantalainen** [comment]
Could you at least fix the error message in BootstrapCheckResult() (https://github.com/elastic/elasticsearch/blob/5a3c4524805f88f0875989d656f87c01595a8de7/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L231) if you intend to not fix this issue? It currently says 

    "initial heap size [%d] not equal to maximum heap size [%d]; " +
    "this can cause resize pauses and prevents mlockall from locking the entire heap"

which makes zero sense if one is not using mlockall support.

I understand that you feel that -Xms and -Xmx flags must be set to equal amounts. I still believe that CMS (and maybe Z GC with Java 11) should be able to waste less memory on average if elasticsearch didn't use hardcoded memory space for full process duration and still allow higher memory consumption for weird corner cases. (It's not like we cannot use the memory if required but we would rather use the RAM as additional disk cache than keeping it reserved for elasticsearch forever.) As such, unless mlockall support has been requested via config, the above test should output a warning instead of forcing a failure.

**Comment by jasontedor** [comment]
Thanks for the feedback. I opened #56565.
