### ISSUE TITLE
Index template v2 deprecration warning for overlapping templates may be misleading

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#56451]
If you use the new index template v2 and there is an overlap with index template v1, you will receive a deprecation message
```
#! Deprecation: index template [bar] has index patterns [test*] matching patterns from existing older templates [foo] with patterns (foo => [test*]); this template [bar] will take precedence during new index creation
```
However, this message is only only true if the index is created with the `prefer_v2_template` flag, and probably shouldn't be deprecation notice in 7.x.  

To reproduce:
```
PUT _template/foo
{
  "index_patterns" : ["test*"],
  "settings" : {
	"index.number_of_shards" : 3
  }
}

PUT _index_template/bar
{
  "index_patterns": [
    "test*"
  ],
  "template": {
    "settings": {
      "index.number_of_shards": 2
    }
  }
}
```

**Comment by dakrone** [comment]
Closing this since we no longer have the `prefer_v2_template` flag, so we don't need to update the warnings
