### ISSUE TITLE
SQL: escape special characters in jdbc connection url

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#56475]
Using URI special characters in the jdbc driver connection url can lead to parsing failures for valid input data. For example `jdbc:es://localhost:9200/?ssl=#5#` will fail because `#` indicates a fragment identifier and using two of them is invalid in the respective url.

**Comment by bpintea** [comment]
@astefan, just to make sure I understand: 
* the provided example should fail;
* `jdbc:es://localhost:9200/?ssl=5#` (or `jdbc:es://localhost:9200/?ssl=5#foo`) works fine;
* generally, if `#` needs to be used for one of the properties, it should be provided as escaped (`%23`; ex: `?user=EndsIn%23&password=bar` for a username of `EndsIn#`).

Assuming the above are true, which escaping do you propose to implement? Have the driver escape the 1st `#` in your example before "really" parsing the URI? i.e. turn it into `jdbc:es://localhost:9200/?ssl=%235#` beforehand?

**Comment by bpintea** [comment]
@astefan, let me know plz if the above clarifications (and #58650) address your concern, or if anything else should be considered for this case.

**Comment by astefan** [comment]
@bpintea no other ideas about other special characters to escape. If anything else comes up, we'll address it then.

**Comment by bpintea** [comment]
Thanks, will close this one for now, then.
