### ISSUE TITLE
SQL: the invalid url error message should be in line with the documentation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#56476]
We state in docs that the [url format should be](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sql-jdbc.html#jdbc-setup) `jdbc:es://[[http|https]://]*[host[:port]]*/[prefix]*<[?[option=value]&]*` but if the url is indeed incorrect, the error message mentions `Invalid URL [jdbc:es://localhost:9200/?ssl=#5#], format should be [jdbc:es://[http|https]?[host[:port]]*/[prefix]*[?[option=value]&]*]` which is inaccurate.

**Comment by matriv** [comment]
`master` : 1a5945c3962cdda21482f4b0b3e0ca508534c2c4
`7.x` : 1a5945c3962cdda21482f4b0b3e0ca508534c2c4
`7.8` : 1a5945c3962cdda21482f4b0b3e0ca508534c2c4
`7.7` : 1a5945c3962cdda21482f4b0b3e0ca508534c2c4

**Comment by matriv** [comment]
`master` : 1a5945c3962cdda21482f4b0b3e0ca508534c2c4
`7.x` : e781193cf928387a71e0054883258de4eb58ae48
`7.8` : 10aefc7657c3e6e5812ce7f8180c209733caf0a0
`7.7` : 3d4eec4ac4720a077dde8aa5c73a70f2000d004e
