### ISSUE TITLE
ES maybe use ThreadPoolExecutor.toString() too frequently when reject tasks.

### ISSUE THREAD

**Issue by nooneuse** [elastic/elasticsearch#56485]
- Elasticsearch version (bin/elasticsearch --version):

> Version: 7.6.2, Build: default/tar/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z, JVM: 1.8.0_131

- Plugins installed:

> None

- JVM version (java -version):

> openjdk version "13.0.2" 2020-01-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)

- OS version (uname -a if on a Unix-like system):

> Linux testhaha 4.14.81.bm.17-amd64 #1 SMP Debian 4.14.81.bm.17 Sun Dec 15 02:54:05 UTC 2019 x86_64 GNU/Linux

- Description of the problem including expected versus actual behavior:

**expected**: tasks rejected very fast with a simple response
**actual**: threads waits for the lock in ThreadPoolExecutor.toString()

_I think_ it maybe is **no necessary** to add detailed infos to rejected response **each time**.

- Steps to reproduce:

> Please include a minimal but complete recreation of the problem,
> including (e.g.) index creation, mappings, settings, query etc. The easier
> you make for us to reproduce it, the more likely that somebody will take the
> time to look at it.
> 

**hello**, I found a place that maybe affects es response performance. 
i think, in the case of high qps, any code that involves locking should be carefully optimized.
# 1.query i uesd:
```json
{
"from": 0,
"size": 0,
"query": {
"bool": {
"filter": [
{ "term": { "user_id": "blabla" }},
{ "term": { "name": "poipoipoi"}},
{ "term": { "type": "testhaha"}}
]
}
},
"_source": {
"includes": [
"SUM",
"SUM"
],
"excludes": [

]
},
"aggregations": {
"SUM(impression_cnt)": {
"sum": {
"field": "impression_cnt"
}
},
"SUM(play_cnt)": {
"sum": {
"field": "play_cnt"
}
}
}
}
```
# 2.my es cluster hardware configuration:
the cluster has two machine and each machine has:
Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz * 2 (total 96 cores)
1TB memory
3576GB nvme SSD * 4
NIC speed 25000Mb/s
# 3.my es cluster software configuration:
each machine has two es node
maybe useful node conf：
```
node.master: true
node.data: true
```
jvm options:
```
-Xms31g
-Xmx31g
```
> each node has very same configuration.
# 4.my indices data
we generate some test data
```
health status index                                pri rep docs.count docs.deleted store.size pri.store.size
green  open   akagiski_and_kagarov-20200417        10   1   19977900            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200416        10   1   19920048            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200415        10   1   19859651            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200414        10   1   19789584            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200419        10   1   20929600            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200418        10   1   20654947            0      2.8gb          1.4gb
green  open   akagiski_and_kagarov-20200430        10   1   21222883            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200413        10   1   19575457            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200412        10   1   19603141            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200411        10   1   19755647            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200410        10   1   19680710            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200505        10   1   21747819            0        3gb          1.5gb
green  open   akagiski_and_kagarov-20200406        10   1   19237776            0      2.6gb          1.3gb
green  open   akagiski_and_kagarov-20200428        10   1   21574421            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200427        10   1   21404682            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200504        10   1   21889895            0        3gb          1.5gb
green  open   akagiski_and_kagarov-20200503        10   1   21607366            0        3gb          1.5gb
green  open   akagiski_and_kagarov-20200502        10   1   21214568            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200425        10   1   21312079            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200409        10   1   19599835            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200408        10   1   19374761            0      2.7gb          1.3gb
green  open   akagiski_and_kagarov-20200507        10   1   21467157            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200506        10   1   21401544            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200407        10   1   19330520            0      2.6gb          1.3gb
green  open   akagiski_and_kagarov-20200420        10   1   21025548            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200501        10   1   21156376            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200424        10   1   21030666            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200423        10   1   20801871            0      2.8gb          1.4gb
green  open   akagiski_and_kagarov-20200422        10   1   20950070            0      2.9gb          1.4gb
green  open   akagiski_and_kagarov-20200421        10   1   21032101            0      2.9gb          1.4gb
```
# 5.I use Locust load testing framework to test the es cluster with the query above 
target indices is akagiski_and_kagarov-*
Locust running test at 3000user & 8 slaves
Locust send requests to a node in this cluster(use ip:port), it **not** random pick nodes to send request.
# 6.my goal is make the cluster response as fast as possible. 
> Any way to improve es performance is welcome.

i got 400 ~ 800 qps waving quickly.  cpu usage 60% ~ 80%, load 60% ~ 80%. 20% ~ 30% of response is returned with 429 code, 
which means task queue full and reject, I think this cluster can have **better qps performance**.

# Provide logs (if relevant):
lets see what happend in stack:
![image](https://user-images.githubusercontent.com/8781788/81471951-77d44000-9227-11ea-87e7-7007b0fcd8b2.png)
i suspected there is a lock in EsThreadPoolExecutor.toString
so i find the code:
```
@Override
    public final String toString() {
        StringBuilder b = new StringBuilder();
        b.append(getClass().getSimpleName()).append('[');
        b.append("name = ").append(name).append(", ");
        if (getQueue() instanceof SizeBlockingQueue) {
            @SuppressWarnings("rawtypes")
            SizeBlockingQueue queue = (SizeBlockingQueue) getQueue();
            b.append("queue capacity = ").append(queue.capacity()).append(", ");
        }
        appendThreadPoolExecutorDetails(b);
        /*
         * ThreadPoolExecutor has some nice information in its toString but we
         * can't get at it easily without just getting the toString.
         */
        b.append(super.toString()).append(']');
        return b.toString();
    }
```
this method use super.toString(), lets see the code of super.toString():
it came from ThreadPoolExecutor, a jdk class.
```
public String toString() {
        ReentrantLock mainLock = this.mainLock;
        mainLock.lock();

        long ncompleted;
        int nworkers;
        int nactive;
        try {
            ncompleted = this.completedTaskCount;
            nactive = 0;
            nworkers = this.workers.size();
            Iterator var6 = this.workers.iterator();

            while(var6.hasNext()) {
                ThreadPoolExecutor.Worker w = (ThreadPoolExecutor.Worker)var6.next();
                ncompleted += w.completedTasks;
                if (w.isLocked()) {
                    ++nactive;
                }
            }
        } finally {
            mainLock.unlock();
        }

        int c = this.ctl.get();
        String runState = isRunning(c) ? "Running" : (runStateAtLeast(c, 1610612736) ? "Terminated" : "Shutting down");
        return super.toString() + "[" + runState + ", pool size = " + nworkers + ", active threads = " + nactive + ", queued tasks = " + this.workQueue.size() + ", completed tasks = " + ncompleted + "]";
    }
```
to make sure the infos is right, the ThreadPoolExecutor have to lock the mainLock when it collect infos of its workers.So it may be a too slow method to use frequently. But EsThreadPoolExecutor use it every time when toString().
EsThreadPoolExecutor will use super.toString() per reject which cost a lot of time to wait.I still think it is maybe no necessary to add detailed infos to rejected response each time.Can we have an option to skip EsThreadPoolExecutor.toString() when reject?

**Comment by original-brownbear** [comment]
@nooneuse I'm not sure this is something worth optimizing. In the end, we'd only optimize the path for sending out `429` responses. But those `429` responses are supposed to make the client back off and send requests at a slower rate to begin with. The idea behind this kind of backpressure architecture is to give clients the ability to back off and reduce their request rate. The system is not designed to be in a steady state of full queues permanently.

So with properly behaving clients that reduce their request rate so that queues aren't permanently full, optimizing this path achieves nothing pretty much since they'd back off anyway removing the issue of contention on the `.toString` call quickly.
With badly behaved clients that constantly exceed the request rate that the cluster can handle without backing off on the other hand, nothing is achieved as well I think. Enabling those clients to send requests that mostly result in `429`s at a higher rate might mean wasting even more resources (memory, network IO, etc.) in a situation that should be fixed on the client-side.

Does that make sense, or can you see a situation where optimizing the `429` path achieves anything productive? (I would add that in practice having the detailed information about those queues available has been helpful in the past often times)

**Comment by original-brownbear** [comment]
Closing here for now due to lack of feedback for now, please reopen if you think there's still an issue here.
