### ISSUE TITLE
SQL: Consolidate Date/Time related Utils

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#56494]
Currently we have various date/time utility constants and methods in ql eql sql and sql/jdbc projects.
It would be great to consolidate those utils into one class if possible.
Probably we would need a new small module qa-util/common that is shared across all modules
and can be included in the JDBC jar.

The same could be done for the test util classes.

**Comment by wchaparro** [comment]
Superceded by ES|QL
