### ISSUE TITLE
index.number_of_replicas cannot be reset to a default value

### ISSUE THREAD

**Issue by Ingramz** [elastic/elasticsearch#56501]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: []

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Any

**Description of the problem including expected versus actual behavior**:

Per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#reset-index-setting), one should be able to reset an index setting to its default value by using `null` as value. This seems to work for a setting such as `refresh_interval`, but not for `number_of_replicas`, resulting in following response:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "must specify numberOfReplicas for index [twitter]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "must specify numberOfReplicas for index [twitter]"
    },
    "status": 400
}
```

It is uncertain whether there are more settings that exhibit this behavior.

**Steps to reproduce**:

Create Index:
```json
PUT /twitter
```

Check defaults (see that `number_of_replicas` is 1):
```json
GET /twitter
```

Set `number_of_replicas` temporarily to 0:
```json
PUT /twitter/_settings
{
    "index" : {
        "number_of_replicas" : 0
    }
}
```

Verify that `number_of_replicas` is 0:
```json
GET /twitter
```

Try to reset the value per documentation:
```json
PUT /twitter/_settings
{
    "index" : {
        "number_of_replicas" : null
    }
}
```

**Provide logs (if relevant)**: N/A

**Comment by cbuescher** [comment]
@Ingramz thanks for raising this, I'm not sure its a bug or the intended behaviour that should be documented better. Labeling accordingly so the team can weigh in.

**Comment by jasontedor** [comment]
This is a bug, I opened #56656

**Comment by jasontedor** [comment]
I'm relabeling this since this isn't a general problem with the settings infrastructure, but a case for this specific API (the update index settings API).
