### ISSUE TITLE
[DOCS]Wrong description for`indices.query.bool.max_clause_count`

### ISSUE THREAD

**Issue by chengyang14** [elastic/elasticsearch#56598]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0

In #56449   ,the indices.query.bool.max_clause_count parameter is incorrectly described as dynamic, in fact it is not a dynamic parameter.

```
public class SearchModule {
    public static final Setting<Integer> INDICES_MAX_CLAUSE_COUNT_SETTING = Setting.intSetting("indices.query.bool.max_clause_count",
            1024, 1, Integer.MAX_VALUE, Setting.Property.NodeScope);
```

**Comment by albertzaharovits** [comment]
Thank you @chengyang14 for bringing this issue to our attention!

FYI @jrodewig

**Comment by jrodewig** [comment]
Thanks @chengyang14  @albertzaharovits
