### ISSUE TITLE
xQL: Consolidate common execution bits between EQL and SQL

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#56641]
Currently EQL uses similar bits and pieces from SQL while using a different execution model.
Once EQL finalizes, this topic needs to be revisited as not only the code be consolidated but the SQL execution pipeline could be improved by generalizing some of code such as promoting custom ordering as an execution stage instead of a custom result listener.

**Comment by wchaparro** [comment]
Superceded by ES|QL
