### ISSUE TITLE
Update timezone DB for bundled JDKs or CI

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#56659]
Prior to 6.8 where only joda time was used in Elasticsearch the only way to update timezone DB was to update joda  time library. 
Timezone DB is released by https://www.iana.org/time-zones this happens more frequently than JDK or joda releases. Changes occurs when for instanc a country decides to tweak their DST. 

Since 6.8 we also use java.time and java allows updating timezone DB with [timezone updater tool](https://www.oracle.com/java/technologies/javase/tzupdater-readme.html) There is a file in `$JAVA_HOME/lib/tzdb.dat` (for jdk12) with timezone information. I am not aware this is configurable.
We can rely on a user to update his JDK with latest timezone data if he uses his own JDK. We can also keep on updating joda for 7.x and 6.8 releases. 

I think we should be keeping both joda and java.time timezone dbs on the same version. If a user is using a newer timezone DB in 6.8 or 7.x and decides to upgrade to use java.time he would notice the breaking change (non existing or differently configured timezones) 

However the problem remains for our bundled JDKs. I suspect we should consider updating these JDKs before we release. - as well as when we update our joda.time containing new timezone db. We did that recently which highlighted the problem https://github.com/elastic/elasticsearch/pull/49748

We should be also updating the JDKs we use for testing (whenever a joda dependency is upgraded)

**Comment by jasontedor** [comment]
@pgomulka Could you update this issue summarizing our recent discussion?

**Comment by pgomulka** [comment]
We reached several conclusion during core-infra sync on 27th May. 

1.  We should not try to update joda.time unless it is confirmed that the same or newer timezone database. 
2.  We will rely on JDK updates we ship with bundled JDK. With every release we update the bundled JDK to the latest version.
- we rely on the fact that each JDK update is shipping with the latest available timezone db
3. If a user on not latest ES version and in need in newer timezone db, he should upgrade to latest ES version or use his own JDK with updated timezonedb.
Things I still consider open for discussion.
4. Ci is testing with multiple JDKs. This also relies on the fact that these JDKs receive updates to their timeozne db. For example on 2020-04-14 all [JDK 14.01](https://www.oracle.com/technetwork/java/javase/14all-relnotes-5809668.html), [JDK 11.0.7](https://www.oracle.com/technetwork/java/javase/11all-relnotes-5013287.html#R11_0_7) and [JDK 8u251](https://www.oracle.com/technetwork/java/javase/8u251-relnotes-5972664.html) all received updates to `IANA Data 2019c`

Worth noting is a scenario where during rolling upgrade a cluster on older version using older timezone DB might see some unexpected behaviour when some nodes respond basing on newer timezone DB.

**Comment by pgomulka** [comment]
closing as we will rely on jdk updates
