### ISSUE TITLE
How to build the docker images of the elastictsearch with my private ID to do some testing in my local

### ISSUE THREAD

**Issue by xauthulei** [elastic/elasticsearch#56658]

**Comment by xauthulei** [comment]
I want to build a private elasticsearch docker image, it is so confuse to me to how build it.  Is there a dockerfile or how to get it? Many thanks.

**Comment by cbuescher** [comment]
Hi @xauthulei! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by dadoonet** [comment]
For the record, I think this discussion is happening now at https://discuss.elastic.co/t/how-to-build-the-elasitic-docker-images-in-my-local-to-do-some-testing-and-if-there-are-some-steps-or-docs/232372
