### ISSUE TITLE
Bundle by default miminal composable templates for the new indexing strategy

### ISSUE THREAD

**Issue by ph** [elastic/elasticsearch#56709]
As part of the new indexing strategy proposed in this [doc](https://github.com/elastic/kibana/blob/f91c795e30b7221cdce36e235470a4cda82f70b2/docs/ingest_manager/index.asciidoc) we would like to add by default a few v2 templates that will be installed by default.

That will match the following index patterns:

```
logs-*-*
metrics-*-*
events-*-*
```

This is to ensure that the Elastic Agent just works out of the box before Kibana is started. 

The downside of this indices matching the above patterns will potentially have a conflict. One of the ideas was that we provide a config flag in Elasticsearch to disable this setup in 7.x so users can opt out. 

With the flag we didn't need this setting as the v1 template was still honored even if a v2 template was around and only had priority if the flag was set which was the case for data sent from the agent. Now that we don't have the flag anymore I assume we need such a setting or other ideas how to help users that will face this conflict in 7.x.

**Comment by ph** [comment]
Changed the name of the index_pattern in the above issues for

```
logs-*-*
metrics-*-*
events-*-*
```

This expand into `${type}-${dataset}-${namespace}`

cc @ruflin

**Comment by dakrone** [comment]
Marked this as team-discuss so we can discuss in @elastic/es-core-features where in the codebase this will live.

**Comment by dakrone** [comment]
We discussed this and decided to make a new "stack" module in the x-pack directory for these templates and other common infrastructure (to be added to in the future).

**Comment by ruflin** [comment]
We soon need to have a conversation about the exact content of these templates. I started a draft PR here https://github.com/elastic/package-registry/pull/481 but no real progress yet. It will be important that the ES team also chimes in especially on the setting sides for recommendations. I will ping here as soon as we need input.

**Comment by dakrone** [comment]
@ruflin I am almost done with this work already, should we have the discussion on the PR itself once I open it?

**Comment by ruflin** [comment]
@dakrone That would be great! Can you ping me on it? BTW lets only add logs-*-* and metrics-*-* for now as we might not need events-*-* for now.
