### ISSUE TITLE
Support compatibility test for JDBC driver

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#56722]
Forwards compatibility was added to our JDBC driver starting in version 7.7.0 (see https://github.com/elastic/elasticsearch/pull/56223). The compatibility guarantee being that for any given version of the driver, it should support (mostly) communication for future versions of Elasticsearch of the same major version. For example, version 7.7.0 of the driver should be able to talk to Elasticearch nodes of version 7.7.1, 7.8.0, 7.8.1, 7.9.0 and so on...

Currently, there is no automated testing in place to ensure we maintain forwards compatibility. It's also not completely clear where, or how these tests should run. Currently, the build only supports _backwards_ compatibility. That is, testing branch code against assets or artifacts from earlier versions or branches. Building or resolving artifacts to test against from _future_ branches currently isn't supported, since, for example, the `7.x` branch has no knowledge of the code in `master`.

We'll need to sort out a few things here, such as which _direction_ we test in. Do we do backwards testing, where in which future branches grab the older JDBC drivers and run the tests, or forwards testing, where older branches grab the new Elasticsearch distribution and run the tests? Much of this is implementation detail, but it has some semantic impact, as with the former method, a failure in a given branch generally points to an incompatible change made in a different branch (but not necessarily). Going the latter route would require more effort, since we'd need to add support to build unreleased artifacts from future branches, which we currently don't do.

cc @matriv

**Comment by mark-vieira** [comment]
It's possible that this somewhat overlaps with what @jakelandis is doing with REST compatibility, as this is another type of forwards compatibility, although implemented a bit differently. Again, in that case (correct me if I'm wrong) newer branches grab the artifact (in this case the rest specs) from the older branch and run them against the current version.

**Comment by rjernst** [comment]
> We'll need to sort out a few things here, such as which direction we test in. Do we do backwards testing, where in which future branches grab the older JDBC drivers and run the tests, or forwards testing, where older branches grab the new Elasticsearch distribution and run the tests?

I think we should continue with backwards compatibility testing, for a few reasons:
* The compatibility layer is implemented in the "future" version. ie in 7.x, we have the compatibility layer with earlier versions, ie backwards compatibility. Thus that is where 7.x should be tested against all the versions it is compatible with.
* As you say, backcompat is the model of tests that we already have. We already have build infrastructure for iterating over compatible versions to build tests against each version.
* It fits better with our branching model. We rarely commit directly to release branches, but instead go through our unreleased branches. It is better to catch compatibility problems in the initial commit rather than only once we backport to a release branch.

**Comment by matriv** [comment]
FYI I've opened: #56872, to "isolate" the jdbc integration tests and avoid hidden bugs because of possible unnecessary pulled in dependencies, and to prepare for the support compatibility testing.

**Comment by matriv** [comment]
I also agree with keeping the bwc scheme. So for example: for 7.8 we can check for each 7.7.x and 7.8.x released versions of ES nodes with the [7.7.0 -> es node version - 1].

We'd like to have something soon as new features are blocked by this (for example date_nanos support PR awaits on this).

**Comment by matriv** [comment]
@mark-vieira @rjernst  Can we please have an ETA for this?

The JDBC tests are already split into a separate `jdbc` module under `sql/qa` and we really need this soon as there is already a feature (date_nanos) blocked by it and soon we want to add array support which also needs JDBC changes.

Thank you.

**Comment by mark-vieira** [comment]
I don't have a concrete ETA for you but I've thrown this on the top of the list for upcoming work.

**Comment by mark-vieira** [comment]
@matriv I presume that the set of tests that we want to perform compatibility testing with are everything under `:x-pack:plugin:sq:qa:jdbc`. Essentially the suite of tests represented by this build: https://gradle-enterprise.elastic.co/s/5sd7brkq23oi6/tests?collapse-all

The tests in `:x-pack:plugin:sql:jdbc` are simply unit tests, so compatibility testing is not applicable there. Correct?

**Comment by matriv** [comment]
@mark-vieira Correct! only the `:x-pack:plugin:sq:qa:jdbc`

**Comment by mark-vieira** [comment]
One thing I ran into here is that it's going to be problematic to use the shadowjar as the test artifact here. To do so, we have to exclude any dependencies from the test classpath that are bundled in the JDBC driver fatjar (things like core libs, etc). The problem is, then we use the libraries from the BWC jar when testing, which causes errors like this:

https://gradle-enterprise.elastic.co/s/cxm6mvbcixo4c/tests/:x-pack:plugin:sql:qa:jdbc:single-node:v7.8.1%23bwcTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcFetchSizeIT/initializationError#1

We are relying on the JDBC driver jar to bring in that class, but it doesn't exist in `7.8` and thus the test fails. I'm not sure we have a good solution here other than to use the "slim" jar for testing and otherwise use the ES dependencies from the current branch.

**Comment by mark-vieira** [comment]
I'm struggling to find a good way forward here given the way these tests are currently architected. The problem is our `:test:framework` code brings in `:server` and other core libraries which are going to class with the same classes coming in from the JDBC driver jar. In my mind we have two options here if we want to do compatibility testing with older JDBC driver jars:

1. We rearchitect the tests such that the load the JDBC driver fatjar in some kind of isolated classloader that can't see the rest of the test runner classpath.
2. We relocate `org.elasticsearch` classes in the JDBC driver jar under a different package so they can both exist on the same classpath simultaneously.

**Comment by mark-vieira** [comment]
I'll add a third item:

3. We don't use `ESRestTestCase`, remove the dependency on `:test:framework` altogether and directly extend `LuceneTestCase` for these tests. I don't see much need to use `ESRestTestCase` anyhow.

**Comment by mark-vieira** [comment]
Ok item (3) likely won't work since these tests rely on `RestClient` to setup test data.

**Comment by costin** [comment]
Thanks for looking into this @mark-vieira. Both (1) and (2) work for me - I have a slight preference towards (2) since, despite not being a fan of shadowing packages, medium term this might prove beneficial as embedding JDBC drivers in other Java apps that use ES, will lead to the same problem that you are facing - classpath issues.
So moving all packages out of the way would address both problems.

The concern that I have though is this feature will be available only moving forward so past releases (in this case 7.7) would miss out on this. However I'd rather have us acting quickly through (2) and then look into ways to address 7.7 later down the road if we really have to.

So 👍 for going with (2).

**Comment by mark-vieira** [comment]
> The concern that I have though is this feature will be available only moving forward so past releases (in this case 7.7) would miss out on this.

Correct, with this option we effectively cannot do compatibility testing with existing releases. We would have to start with `7.8.1` given that would be the first available version with relocated packages. That means that we will not know if we break backcompat with the 7.7 driver (although 7.8.1 will be a pretty close analog).

**Comment by matriv** [comment]
Even though this is not ideal, we can assume that is safe enough to start with `7.8.1`, so if (1) is difficult to implement, it's fine also by me to go with the (2) approach.

**Comment by mark-vieira** [comment]
> so if (1) is difficult to implement, it's fine also by me to go with the (2) approach

To clarify, I've not investigated what it would take to implement solution (1). I suspect someone more familiar with the tests would be better suited to do that. It might be worth looking into in parallel with this. Course (2) is not necessarily an easy win, package relocation might not easily work, as it doesn't play nicely with things like reflection. We may find out that we have to make code changes in the JDBC driver or some of it's dependencies to make that work, at which point refactoring the tests might be an easier road.

**Comment by costin** [comment]
> Course (2) is not necessarily an easy win, package relocation might not easily work, as it doesn't play nicely with things like reflection. We may find out that we have to make code changes in the JDBC driver or some of it's dependencies to make that work, at which point refactoring the tests might be an easier road.

Have you tried changing the packages and encountered failures? The JDBC driver is not using reflection nor does it depend on the package name; maybe the `org.elasticsearch` dependency does but this would be easy to find out by just trying things out.

**Comment by mark-vieira** [comment]
> Have you tried changing the packages and encountered failures? 

I have not yet, I'll be giving this a try soon.

**Comment by mark-vieira** [comment]
Ok, with some tinkering I was able to get a green build of the current integration test suite against a shadowjar with relocated `org.elasticsearch` packages.

https://gradle-enterprise.elastic.co/s/3cutzwlvii6lq/tests

I'll move on to testing this against similarly configured BWC branch as well.

**Comment by mark-vieira** [comment]
Here we are folks. This is a successful run of building the 7.8.1 JDBC driver (with relocated shadowed dependencies) again a 7.9 Elasticsearch cluster.

https://gradle-enterprise.elastic.co/s/sqjzlft75tx42/tests

Since this approach seems to be ok I'll move forward with getting the necessary changes made in the 7.8 branch and forward. I'd also highly suggest we expand the existing test suite to also validate the current JDBC driver version is what we expect. I'm going to inject a `jdbc.driver.version` system property into the test runner with the "expected" JDBC jar version. We should add a unit test to validate that matches the reality of what's on the test classpath.

**Comment by mark-vieira** [comment]
Alright with https://github.com/elastic/elasticsearch/pull/60430 merged we now have this in place. We didn't make this in to 7.8 so we are beginning compatibility testing with 7.9. As mentioned above, I would highly recommend putting some assertions in place to confirm the JDBC driver being loaded is the version that's expected in case we muck up the build wiring somehow.
