### ISSUE TITLE
EQL: implement case sensitivity for between string function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#56749]
Following a similar approach in https://github.com/elastic/elasticsearch/pull/56404/, implement case sensitivity based on request parameter for `between` string function.

**Comment by costin** [comment]
It's worth considering whether we should still preserve the case sensitivity switch for `between` - iirc, its usage was not wide so maybe we could remove it altogether.

**Comment by costin** [comment]
Superseded by #62255
