### ISSUE TITLE
EQL: case sensitivity aware integration testing

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#56754]
With the [addition of `case_sensitivity` request parameter](https://github.com/elastic/elasticsearch/pull/56404), we should consider integration testing infra supporting it, as well, so that tests work no matter the value of this parameter.

**Comment by costin** [comment]
Tagging @rw-access as well - not sure what's the best way forward. We could either end up with a different test suite so essentially there's one test for case sensitivity and another for the insensitive part. Or we can add dedicated tests inside the same test suite and based on a convention (such as test name or some sort of flag), some test will be skipped or picked up.

**Comment by rw-access** [comment]
I added case sensitivity on/off flags to the Python TOML tests as part of the backport process. I just need to pull them into this repo. We may need to add more individual tests, but I think that should be sufficient for our testing. Unless there are other things I'm not anticipating

Here's an example of a test
https://github.com/endgameinc/eql/blob/master/eql/etc/test_queries.toml#L196
