### ISSUE TITLE
Docs: clarify how bucket boundaries are formed in Date Histogram

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#56760]
It seems that some users are confused that buckets in `date_histogram` aggregations are formed by rounding up the interval value. The `histogram` [aggregation documentation](https://github.com/elastic/elasticsearch/blob/master/docs/reference/aggregations/bucket/histogram-aggregation.asciidoc#histogram-aggregation) starts with a pretty good explanation describing this process with an example, I think `date_historgram` documentation could benefit from this as well, especially if an example is based on a non-trivial fixed intervals such as "5m".

**Comment by nik9000** [comment]
@imotov, do you want to write this? I can certainly do it because I was just hacking on this code and have it in my head pretty well.

**Comment by imotov** [comment]
@nik9000 please go ahead. I will not be able to get to it for a while.
