### ISSUE TITLE
EQL: Handle case insensitivity for Comparisons

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#56771]
Related to #56404

For EQL, `==` and `!=` are always case-insensitive for the Python library and the Endpoint implementations. We should have the ability to make these case-insensitive.

The Python library will be updated to make `<`, `<=`, `>=`, `>` case-insensitive as well.
https://github.com/endgameinc/eql/issues/30

**Comment by astefan** [comment]
https://github.com/elastic/elasticsearch/issues/53603 should help with this, I believe.

**Comment by costin** [comment]
Not needed anymore - see https://github.com/elastic/elasticsearch/issues/62949
