### ISSUE TITLE
Issue in language detection with ingest-attachment plugin

### ISSUE THREAD

**Issue by lzaiko** [elastic/elasticsearch#56822]
Hi Everyone
To test the **ingest-attachment** plugin I indexed the following page which is written in English:
[https://derivatives.juliusbaer.com/en/products/details?Isin=CH0524980189&ReturnUrl=/en/home](https://derivatives.juliusbaer.com/en/products/details?Isin=CH0524980189&ReturnUrl=/en/home)
The indexation ran well. But when I checked the indexed document, the detected language was **French** (**fr**)?
`curl 'http://127.0.0.1:9200/test/_doc/1?stored_fields=attachment.language' {"_index":"test","_type":"_doc","_id":"1","_version":1,"_seq_no":0,"_primary_term":1,"found":true,"fields":{"attachment.language":["fr"]}}`
Any hint on how to solve this strange behavior?
Thanks

PS: I attached  my index settings
[es.json.zip](https://github.com/elastic/elasticsearch/files/4634729/es.json.zip)

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
