### ISSUE TITLE
Completion suggester - duplicates - `index_analyzer` and `preserve_separators` ignored

### ISSUE THREAD

**Issue by g00fy-** [elastic/elasticsearch#5682]
I would expect that `index_analyzer: standard` and `preverve_separators: true` would lowercase and normalize the `output` but it turns out that they don't. This causes the completion suggester to return duplicated results.

```curl -XPOST "/test"```

```
curl -XPOST "/test/_mapping/test" -d'
{
    "test":{
        "properties": {
            "name":{
                "type": "string",
                "copy_to":"name_suggest"
            },
            "name_suggest":{
                "type": "completion",
                "index_analyzer": "standard",
                "search_analyzer": "standard",
                "preserve_position_increments":false,
                "payloads":false,
                "preserve_separators":false
            }
        }
    }
}'
```
```
curl -XPOST "/test/test" -d'
{
    "name":"bmw"
}'
```
```
curl -XPOST "/test/test" -d'
{
    "name":"BMW"
}'
```
```
curl -XPOST "/test/test" -d'
{
    "name":"bmw "
}'
```
```
curl -XPOST "/test/_suggest" -d'
{
    "text":"b",
    "car":{
        "completion":{
            "field":"name_suggest"
        }
    }
}'
```

Result

```javascript
{
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "car": [
      {
         "text": "b",
         "offset": 0,
         "length": 1,
         "options": [
            {
               "text": "BMW",
               "score": 1
            },
            {
               "text": "bmw",
               "score": 1
            },
            {
               "text": "bmw ",
               "score": 1
            }
         ]
      }
   ]
}
```

**Comment by arildplassen** [comment]
What is the status on this? Experience the same problem. 

Also, both custom and predefined analyzers doesn't seem to have any effect at all (on index_analyzer, search_analyzer).

**Comment by askaliuk** [comment]
+1

**Comment by clintongormley** [comment]
> I would expect that index_analyzer: standard and preverve_separators: true would lowercase and normalize the output but it turns out that they don't. This causes the completion suggester to return duplicated results.

I think this is expected.  The analysis chain is only for the input.  The output is supposed to be provided in the format that you want to display.  Your example basically translates to a single input with multiple outputs.
