### ISSUE TITLE
ILM and defining node types

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#56876]
In the ILM documentation we don't clearly state how the concept of hot/warm/cold nodes work - just that they can exist. This is usually done via [allocation awareness](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html), and it'd be good to get something added in the overall chapter about this.

**Comment by dakrone** [comment]
This is going to be moot once we have #60848, so I'm going to close this for now.
