### ISSUE TITLE
Link to similarity plugin still reference 2.x branch

### ISSUE THREAD

**Issue by grib0** [elastic/elasticsearch#56912]
This page about similarity has a link to the 2.x branch. When clicking, you are going to the 2.x page, with an info section inviting you to go to latest version, but then you are redirect to the root reference version loosing your navigation.

https://www.elastic.co/guide/en/elasticsearch/reference/current/similarity.html

Section : Pluggable Similarity Algorithms

The link should point to 
https://www.elastic.co/guide/en/elasticsearch/reference/7.7/index-modules-similarity.html instead of 
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/pluggable-similarites.html

**Comment by jrodewig** [comment]
Thanks for raising @nik9000. I don't think we have a good substitute for these pages in the ES reference guide.

However, I think we can either remove the links or replace them with links to the algorithms in wikipedia:

* https://en.wikipedia.org/wiki/Okapi_BM25
* https://en.wikipedia.org/wiki/Tf%E2%80%93idf

I can work on a PR.

**Comment by jrodewig** [comment]
Closed by #56925.
