### ISSUE TITLE
Dashboard filter broke for timelion

### ISSUE THREAD

**Issue by kscianna** [elastic/elasticsearch#56918]
I am using 7.7 on the elastic cloud. I have a dashboard with a timelion graph that splits by a field.  If I add a filter to choose that field, the filter is not applied and I still see all lines. 

Steps:
 1. Create a timelion visualization with a split.
 2. Add the visualization to a dashboard.
 3. Add a filter to pick one of entries from the split field.
 4. Only a single plot using the filtered value should be shown, but all lines are still visible.

**Comment by matriv** [comment]
@kscianna Please open this issue in the [kibana repo](https://github.com/elastic/kibana).
