### ISSUE TITLE
Update geo_point documentation to include geo_shape query

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#56927]
geo_point documentation, https://www.elastic.co/guide/en/elasticsearch/reference/7.8/geo-point.html, contains text about finding points in a polygon. This should be replaced with geo_shape query support recently added to geo_point

<img width="300" alt="Screen Shot 2020-05-18 at 5 54 55 PM" src="https://user-images.githubusercontent.com/373691/82270051-c1f8a800-9930-11ea-8bd3-0662cd960ade.png">

**Comment by talevy** [comment]
thanks @nreese. should be better now!
