### ISSUE TITLE
Hidden indices not exposed in monitoring index_stats documents

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#56949]
With the [introduction of hidden indices](https://github.com/elastic/elasticsearch/pull/50452), it looks like they are not included in the monitoring `index_stats` documents. (It's worth noting that the index total in `cluster_stats` monitoring documents is accurate (`cluster_stats.indices.count`)).

I'm also proposing we add additional mappings to indicate that the index is hidden, such as `index_stats.hidden: <boolean>`.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
