### ISSUE TITLE
Identify & document differences between EQL ES and EQL endpoint queries

### ISSUE THREAD

**Issue by sethpayne** [elastic/elasticsearch#56996]
Our goal is to minimize differences between querying data in ES and data on endpoints via EQL.

Per the EQL on ES ticket:

> A separate implementation of EQL will still exist that queries the endpoint devices directly. This means that we should avoid differences between writing EQL for Elasticsearch and EQL to run on the endpoints as any differences would have the potential to confuse users

However, given the inherent differences between centrally storing data in ES vs accessing data on disparate endpoints, some functionality will differ.

This ticket is to identify and document all differences between writing queries for ES and writing EQL for endpoints.

**Comment by jrodewig** [comment]
Some of these differences are already documented here:

https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-limitations.html

We should continue using this page to document differences. However, I'm waiting on adding final documentation for some differences until implementation is settled (e.g., multi-value fields: https://github.com/elastic/elasticsearch/issues/54970).

**Comment by sethpayne** [comment]
Thanks @jrodewig 

@paulewing will have more insight here.  But one thing I'm concerned about is the UX when users move between querying endpoints and ES within SIEM.  Users should be able to easily understand the query functionality differences between ES and endpoint queries.

**Comment by costin** [comment]
The response format is relevant (see #57036).
