### ISSUE TITLE
Inconsistent formatting for date_nanos fields?

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#57019]
The formatting behavior for `date_nanos` fields can be surprising. In particular, when retrieving `docvalue_fields`, using the format `strict_date_time` gives a different result than `strict_date_optional_time`.

An example:
```
PUT my_index
{
  "mappings": {
    "properties": {
      "date": {
        "type": "date_nanos" 
      }
    }
  }
}

PUT my_index/_doc/1
{
  "date": "2015-01-01T12:10:30.123456789Z"
}
```

The following search returns the date "2015-01-01T12:10:30.123456789Z":
```
GET my_index/_search
{
  "docvalue_fields" : [
    {
      "field" : "date",
      "format": "strict_date_time" 
    }
  ]
}
```

While this returns "2015-01-01T12:10:30.123Z":
```
GET my_index/_search
{
  "docvalue_fields" : [
    {
      "field" : "date",
      "format": "strict_date_optional_time" 
    }
  ]
}
```

**Comment by gaobinlong** [comment]
This issue maybe come from the difference between `STRICT_DATE_PRINTER `and `STRICT_DATE_OPTIONAL_TIME_PRINTER `:
https://github.com/elastic/elasticsearch/blob/21f18e02c26a40140f5c8708bfa0cd52df0bf2e8/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L593
https://github.com/elastic/elasticsearch/blob/21f18e02c26a40140f5c8708bfa0cd52df0bf2e8/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L96

**Comment by pgomulka** [comment]
`strict_date_optional_time`  is a format that was always parsing and printing up to 3  digits on `fraction of second` part. 
On the other hand `strict_date_time` was actually allowing parsing and printing up to 9 digits - even when it was not supported with joda (additional digits were dropped)
see https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/joda/time/format/StrictISODateTimeFormat.java#L2020

Changing this now would surely break some users.

would  you consider using `strict_date_optional_time_nanos` ?

**Comment by jtibshirani** [comment]
> `strict_date_optional_time` is a format that was always parsing and printing up to 3 digits on `fraction of second` part.

To clarify, in my testing I saw that `strict_date_optional_time` accepts dates with nanosecond precision, but only formats them at millisecond precision. This leads to confusing behavior where you can successfully index a `date_nano` using `strict_date_optional_time` (the default), but when you go to retrieve it through `docvalue_fields` with this same format, the nanosecond precision is lost.

> would you consider using `strict_date_optional_time_nanos` ?

I'm not up to speed on the details of date formatting and backwards compatibility, but to me it'd be better to fix the inconsistency (or explicitly choose not to fix it) instead of introducing this new type.

**Comment by pgomulka** [comment]
> I'm not up to speed on the details of date formatting and backwards compatibility, but to me it'd be better to fix the inconsistency (or explicitly choose not to fix it) instead of introducing this new type.

I am also not sure on backwards compatibility implication on changing `strict_date_optional_time`. @rjernst do you happen to remember?
I guess there must be some, as the only alternative to modifying `strict_date_optional_time` would be to add a new date format.

**Comment by rjernst** [comment]
I don't remember why the allowed digits were extended for `strict_date_optional_time`. The nanos variant was added for the `date_nanos` field type, which is what should be used IMO. I don't think we should change the behavior of `strict_date_optional_time` unless it can be conditionalized on the field type, so that users of regular `date` fields continue to get the same behavior.

**Comment by jtibshirani** [comment]
Sorry for the confusion, I actually didn't realize that `strict_date_optional_time_nanos` already exists. I'm happy to go with whatever you think is best in terms of the behavior.

For me, a takeaway from this discussion is that we could improve the docs: `strict_date_optional_time_nanos` isn't listed on the [date formats](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/mapping-date-format.html) page. We could also mention this format on the [date_nanos](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/date_nanos.html) page and give clearer guidance around formats.

**Comment by pgomulka** [comment]
@jtibshirani good idea - I will keep this item open and update the docs
We are intending actually to limit number of named formats in the future, but `strict_date_optional_time*` are likely to stay I think.
