### ISSUE TITLE
Confusion over codec parameter to ILM force-merge action

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#57034]
In https://github.com/elastic/elasticsearch/pull/49974 we added support for changing to the `best_compression` codec in ILM's force-merge action, but it seems that the parameter in the REST API is actually `index_codec` and not `codec` as per the docs:

https://github.com/elastic/elasticsearch/blob/95a7eed9aa35f47b228e402508709b5bd6703cf4/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ForceMergeAction.java#L36

This means the docs for 7.7 are wrong (see https://github.com/elastic/elasticsearch/pull/55978). I think `index_codec` is an unfortunate choice of name and it would be preferable to change it to `codec` even though it's now a breaking change so we'd have to do the whole deprecation dance to achieve that.

**Comment by dakrone** [comment]
> I think `index_codec` is an unfortunate choice of name and it would be preferable to change it to `codec`

I'm going to guess (since it was a community PR), that `index_codec` came from it being the `index.codec` setting, and I asked to not have a dot in the field name for the action definition.

Can you explain why you think `index_codec` is an unfortunate name? Just parity between the two?

**Comment by DaveCTurner** [comment]
Yes, just that I think of the index setting as simply `codec` (the namespace may be given separately and can even be omitted in some contexts) and that the `index_` prefix seems redundant (whose codec could we be changing if not the index's?). I'm not certain we should rename it, but I do expect this discrepancy will catch me out in the future.

**Comment by zuozp8** [comment]
docs still need updating https://www.elastic.co/guide/en/elasticsearch/reference/7.7/ilm-forcemerge.html

**Comment by jrodewig** [comment]
#62243 updates the docs to use the current `index_codec` param key.

**Comment by jrodewig** [comment]
@dakrone @DaveCTurner I'm going to close this issue as the docs are now fixed. Please re-open if you feel we need to rename the parameter.
