### ISSUE TITLE
Missing date field for a doc is impacting the relevancy. 

### ISSUE THREAD

**Issue by lasagar** [elastic/elasticsearch#57062]
"functions": [                         {                             "linear": {                                 "date": {                                     "origin": "now",                                     "offset": "60d",                                     "scale": "3590d",                                     "decay": 0.5                                 }                             }                         },

Is there a way we can have missing field with the option to provide default score for that doc

**Comment by cbuescher** [comment]
Have you tried the date datatypes [`null_value`](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) parameter yet? If that doesn't work I'd like to refer you to our support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
