### ISSUE TITLE
Automate delete/recreate of indices

### ISSUE THREAD

**Issue by kovacsvx** [elastic/elasticsearch#57077]
One feature that is continually requested and explained
is that deleting and recreating an index is a better way
to delete all data in an index.

The user will not like this, because it forces one to:

1.  Take careful note of the index as it stands (including
field formatting that may have been created automatically,
and security).  It is quite likely that something will be missed.

2.  And then come up with a query that will re-create
the index with correct permissions.

This may seem simple to experienced users, but makes
the learning curve steeper than a new user would
want to see.

Might I suggest:

DELETE /server:port:/<index_name>/_truncatre

Which internally:

1. Takes note of an index's features such as typing, security, etc.
2.  Deletes the index.
3.  Creates a new index with the features noted above.
4.  Requires appropriate permissions.

**Comment by kovacsvx** [comment]
Sorry, my fingers were running faster than my mind.
DELETE //server:port/<index_name>/_truncate

**Comment by dnhatn** [comment]
You can achieve this with a [delete by query.](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-api-example) Thanks very much for your interest in Elasticsearch.  I hope you don't mind that I close this.
