### ISSUE TITLE
[bool] failed to parse field

### ISSUE THREAD

**Issue by Happyfeet01** [elastic/elasticsearch#57090]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.0

**Plugins installed**: []
readonlyrest 7.7.0
ingest-attachment

**JVM version** (`java -version`):
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux  4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

i have installed elasticsearch and readonlyrest to use the internal search from Nextcloud. Whis this App https://github.com/nextcloud/fulltextsearch/

The setup works without problems, but the search won´t work. Here is the logentry from Nextcloud 

there is no relevant log entry by elasticsearch.

**Provide logs (if relevant)**:

```500 - {"request":{"providers":["files"],"author":"lars","search":"ratingen","page":1,"size":20,"parts":["comments","ocr"],"queries":[],"options":{"files_within_dir":"","files_local":"","files_external":"","files_extension":""},"metatags":[],"subtags":[],"tags":[]},"version":"1.4.1","status":-1,"exception":"Elasticsearch\\Common\\Exceptions\\BadRequest400Exception","message":"{\"error\":{\"root_cause\":[{\"type\":\"x_content_parse_exception\",\"reason\":\"[1:63] [bool] failed to parse field [should]\"}],\"type\":\"x_content_parse_exception\",\"reason\":\"[1:63] [bool] failed to parse field [must]\",\"caused_by\":{\"type\":\"x_content_parse_exception\",\"reason\":\"[1:63] [bool] failed to parse field [should]\",\"caused_by\":{\"type\":\"x_content_parse_exception\",\"reason\":\"[1:63] [bool] failed to parse field [should]\",\"caused_by\":{\"type\":\"illegal_state_exception\",\"reason\":\"expected value but got [START_ARRAY]\"}}}},\"status\":400}"}```

debug logentry:

`
h_elasticsearch | debug - request: {"providers":["files"],"author":"lars","search":"ratingen","page":1,"size":20,"parts":["comments","ocr"],"queries":[],"options":{"files_within_dir":"","files_local":"","files_external":"","files_extension":""},"metatags":[],"subtags":[],"tags":[]} - query: {"params":{"index":"cloud_index","type":"standard","size":20,"from":0,"body":{"query":{"bool":{"must":{"bool":{"should":{"bool":{"should":[[{"bool":{"should":[{"match_phrase_prefix":{"content":"ratingen"}},{"match_phrase_prefix":{"title":"ratingen"}},{"match_phrase_prefix":{"share_names.lars":"ratingen"}},{"wildcard":{"title":"*ratingen*"}},{"wildcard":{"share_names.lars":"*ratingen*"}},{"query_string":{"fields":["parts.comments","parts.ocr"],"query":"ratingen"}}]}}]]}}}},"filter":[{"bool":{"must":{"term":{"provider":"files"}}}},{"bool":{"should":[{"term":{"owner":"lars"}},{"term":{"users":"lars"}},{"term":{"users":"__all"}},{"term":{"groups":"admin"}}]}},{"bool":{"should":[]}},{"bool":{"must":[]}},{"bool":{"must":[]}}]}},"highlight":{"fields":{"content":{},"parts.comments":{},"parts.ocr":{}},"pre_tags":[""],"post_tags":[""]}}}}`

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by Happyfeet01** [comment]
Hello, 

Thanks for your. I read that the app for Nextcloud is not compatible with elasticsearch 7.7.0. Its not a problem with elasticsearch.

Next time I write at the user forum.
