### ISSUE TITLE
function_score +agg

### ISSUE THREAD

**Issue by wuyu8995861** [elastic/elasticsearch#57149]
You bigwigs, now we have a requirement, first according to the enterprise name as the main query, and then according to the enterprise ID grouping, and then custom ranking, the Function_score of ES does not seem to support?

POST demo/demo/_search
{
    "query": {
        "function_score": {
              "query": {
                "term": {
                  "name": "zhangsan"
                }
          },
          "script_score": {
            "script": {
            "source": "doc['crank].value/doc['crank'].value"
            }
          },
          "boost_mode": "replace"
        },
      "aggs": {
        "avg_price": {
          "avg": {
            "field": "group_id"
          }
        }
      }
    }
}

**Comment by cbuescher** [comment]
Hi @wuyu8995861! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
