### ISSUE TITLE
Kuromoji and Nori slowdown

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#57142]
Dictionary-based analyzers have been much slower since Lucene 8.4 / Elasticsearch 7.6 due to a refactoring of FSTs. This problem is already fixed via https://issues.apache.org/jira/browse/LUCENE-9286 which is expected to be released in Lucene 8.6/Elasticsearch 7.8, I'm opening this issue for tracking purposes.

**Comment by johtani** [comment]
Hi @jpountz ,
Should is the label `7.9.0` instead of `7.8.0`?
Unfortunately, 7.8.0 still uses Lucene 8.5.1.
