### ISSUE TITLE
Can I get the size of the query result specified in the queryBuilder implemented by myself, or can I specify the size of the query result in the queryBuilder

### ISSUE THREAD

**Issue by JamesIsHuang** [elastic/elasticsearch#57186]
Can the size of the specified query result be obtained in the queryBuilder implemented by inheriting the AbstractQueryBuilder class, or can I specify the size of the query result in queryBuilder？

**Comment by cbuescher** [comment]
Hi @JamesIsHuang! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
