### ISSUE TITLE
Default distro BWC matrix failure for 6.0.0-6.2.4 versions from 7.7 branch

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#57252]
**Build scan**: https://gradle-enterprise.elastic.co/s/mo74b3662e2di (the [Jenkins build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+default-distro+bwc/3/) is a bit clearer as to what's going on)

**Repro line**: n/a

**Reproduces locally?**: n/a

**Applicable branches**: 7.7, 7.8, v6.0.0-v6.2.4 (inclusive)

**Failure history**:
Appears to have failed only in the latest run of the matrix, see [the Jenkins build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+default-distro+bwc/3/). From [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:f0e86d70-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22plugin%20directory%22%20AND%20%22already%20exists%22'),sort:!(time,desc))), I can only see evidence of this happening once, so it might be a fluke.

**Failure excerpt**:
`ERROR: plugin directory [/dev/shm/elastic+elasticsearch+7.7+default-distro+bwc/BWC_VERSION/6.1.2/nodes/centos-7&&immutable/qa/translog-policy/build/testclusters/v6.1.2-0/distro/6.1.2-DEFAULT/plugins/x-pack] already exists; if you need to update the plugin, uninstall it first using command 'remove x-pack'`

It appears that the build is having trouble installing x-pack for the versions which do not bundle it with the default distribution.

**Comment by gwbrown** [comment]
The default distro matrix for 7.8 just ran and hit the same issue, see [Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.8+default-distro+bwc/).

**Comment by rjernst** [comment]
Fixed by #57266
