### ISSUE TITLE
EQL: Port over new TOML tests from endgameinc/eql

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#57313]
The new TOML tests in the Python library need to be pulled into this repo and incorporated 
It contains unit and integration tests that work for case-sensitive, case-insensitive configurations and some tests that match the case exactly and will work for both. 

Those tests should be incorporated here. It still needs greater test coverage, and we can update and synchronize those periodically.
https://github.com/endgameinc/eql/tree/master/eql/etc

**Comment by costin** [comment]
This has been addressed through PRs #58624 and #58748
