### ISSUE TITLE
ES Creating too many files in /tmp

### ISSUE THREAD

**Issue by lanerjo** [elastic/elasticsearch#57369]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk-11_28

**OS version** (`uname -a` if on a Unix-like system): Linux 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I am running into an issue since upgrading elasticsearch from 6.7.2 to 7.5.2, where elasticsearch is now creating 1000's of files in /tmp on the host machines.
Filenames are elasticsearch-* and controller_log_*
Elasticsearch instances are not being restarted 1000's of times, and I have been unable to determine where these files are being created.
I am aware that elasticsearch disables the periodic cleaning of the /tmp directory for elasticsearch related files. But creating 1000 files per day is unacceptable, this will cause system instability and many other issues.

    prw-------  1 elasticsearch    elasticsearch          0 May 26 19:03 controller_log_99392
    prw-------  1 elasticsearch    elasticsearch          0 May 26 17:18 controller_log_99520
    prw-------  1 elasticsearch    elasticsearch          0 May 26 19:03 controller_log_99621
    prw-------  1 elasticsearch    elasticsearch          0 May 26 18:14 controller_log_9965
    prw-------  1 elasticsearch    elasticsearch          0 May 26 17:18 controller_log_99761
    prw-------  1 elasticsearch    elasticsearch          0 May 27 09:20 controller_log_9987
    prw-------  1 elasticsearch    elasticsearch          0 May 26 17:18 controller_log_99958
and

    drwx------  2 elasticsearch    elasticsearch       4096 May 27 04:13 elasticsearch-9900697386538499675
    drwx------  2 elasticsearch    elasticsearch       4096 May 26 15:59 elasticsearch- 9906081905532042965
    drwx------  2 elasticsearch    elasticsearch       4096 May 26 20:32 elasticsearch-9934128230626817962
    drwx------  2 elasticsearch    elasticsearch       4096 May 26 19:38 elasticsearch-9959566056361653972
    drwx------  2 elasticsearch    elasticsearch       4096 May 27 04:42 elasticsearch-9967643642543549351
    drwx------  2 elasticsearch    elasticsearch       4096 May 26 23:50 elasticsearch-9987506565151338674
    drwx------  2 elasticsearch    elasticsearch       4096 May 26 16:18 elasticsearch-999953937332847863
Here are the counts of the files from one node that was cleared out completely yesterday. As you can see if this is not cleaned up regularly, it will (has in my case) cause an out of iNode issue.

    ls -lah | grep controller_log | wc -l
    1103

    ls -lah | grep elasticsearch- | wc -l
    1104
Output from ps -ef

    ps -ef | grep elastic
    496      135301      1 80 Mar17 ?        56-21:38:51 /usr/java/openjdk-11_28/jdk-11/bin/java - Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=COMPAT -Xms30500m -Xmx30500m -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/es-data0/es_gc_%t_%p.log:utctime,pid,tags:filecount=5,filesize=64m -Djna.tmpdir=/home/elasticsearch/jnatmp -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1HeapRegionSize=16m -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=5 -XX:ConcGCThreads=5 -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.type=unpooled -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -Djdk.tls.ephemeralDHKeySize=2048 -XX:MaxDirectMemorySize=15997075456 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch/es-data0 -Des.distribution.flavor=default -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch-es-data0/elasticsearch-es-data0.pid -d
    496      135733      1 92 Mar17 ?        65-16:46:49 /usr/java/openjdk-11_28/jdk-11/bin/java -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=COMPAT -Xms30500m -Xmx30500m -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/es-data1/es_gc_%t_%p.log:utctime,pid,tags:filecount=5,filesize=64m -Djna.tmpdir=/home/elasticsearch/jnatmp -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1HeapRegionSize=16m -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=5 -XX:ConcGCThreads=5 -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.type=unpooled -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -Djdk.tls.ephemeralDHKeySize=2048 -XX:MaxDirectMemorySize=15997075456 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch/es-data1 -Des.distribution.flavor=default -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch-es-data1/elasticsearch-es-data1.pid -d
    496      136037 135301  0 Mar17 ?        00:00:00 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
    496      136701 135733  0 Mar17 ?        00:00:00 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
X-pack machine learning is supposed to be disabled.

    xpack.ml.enabled: false
    xpack.monitoring.enabled: false
    xpack.watcher.enabled: false

**Comment by jasontedor** [comment]
Are you sure that you're not restarting, or maybe another instance keeps trying to start? These files:

```
elasticsearch-999953937332847863
```

are *only* created at node startup.

> I am aware that elasticsearch disables the periodic cleaning of the /tmp directory for elasticsearch related files.

I am not aware that we do that, what makes you think we do? Maybe we have a bug here?

**Comment by lanerjo** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/es-tmpdir.html <<-- This is why I think that Elasticsearch disables the periodic cleaning on elasticsearch files in the /tmp directory. 

I will check to see if an instance of elasticsearch is trying to start on those machines.

**Comment by rjernst** [comment]
The periodic cleanup being described there is within one boot of the system. Systemd by default runs cleanup of temp files 15 mins after boot, and then every 24 hours. We use a private tmp dir so our files do not get cleaned up by that periodic cleanup, but the system should still do its own /tmp cleanup on boot (in fact I think most systems now use a tmpfs mount for /tmp so it is automatically wiped on reboot).

**Comment by rjernst** [comment]
As stated before, /tmp cleanup is handled by the operating system. Given that, we don't view this as a bug, but a local environmental issue. As such, I hope you don't mind that I close this issue.
