### ISSUE TITLE
Spark ES sql  use "where in" condition to filter multi keyword is not correct

### ISSUE THREAD

**Issue by vernepenn** [elastic/elasticsearch#57405]
**Elasticsearch version** (`bin/elasticsearch --version`):6.3.1

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

val sparkConf = new SparkConf()
          .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
          .set("spark.es.index.auto.create", "true")
          .set("spark.es.nodes", "nodes")
          .set("spark.es.port", "9200")
          .set("spark.es.resource", "index_name")
          .set("spark.es.nodes.wan.only", "true").set("spark.master", "local[4]")

val essessionDataFrame = spark.sqlContext.read
          .format("org.elasticsearch.spark.sql")
          .option("inferSchema", "true").load("index_name/type")
essessionDataFrame.createOrReplaceTempView(hiveTableName)
essessionDataFrame.show()
spark.catalog.refreshTable(hiveTableName)
val sql = s"SELECT DISTINCT memid FROM $hiveTableName WHERE town_no IN ('21400','23500')"
spark.sql(sql).rdd.count()

 1. index_name/type has 3 records  whether town_no = 21400 or town_no = 23500
 2.when I run sql = s"SELECT DISTINCT memid FROM $hiveTableName WHERE town_no IN ('21400')"
or s"SELECT DISTINCT memid FROM $hiveTableName WHERE town_no IN ('23500')"
it works and return 3 records
 3.but I run sql = s"SELECT DISTINCT memid FROM $hiveTableName WHERE town_no IN ('21400','23500')" ,  it return 0 record.

**Provide logs (if relevant)**:

**Comment by jkakavas** [comment]
Hello @vernepenn , could you please close this and re-open it in https://github.com/elastic/elasticsearch-hadoop ?
