### ISSUE TITLE
Missing CHANGELOG.md?

### ISSUE THREAD

**Issue by jirihradil** [elastic/elasticsearch#57403]
Can you please create/update `CHANGELOG.md` file in the root of this marvelous gem to allow developers to quickly look what was changed in the last version?

Thank you!

**Comment by romseygeek** [comment]
Hi @jirihradil we maintain release notes outside of the code repo.  You can find them here: https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html
