### ISSUE TITLE
Regression in aggregation latency after #57241

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#57407]
After merging https://github.com/elastic/elasticsearch/pull/57241 we see the following spike in aggregation latency in the nightly charts (starting 20200528):

![image](https://user-images.githubusercontent.com/1754575/83406710-e3b95b00-a417-11ea-9e02-28a5fee3dd8f.png)

The list of commits between 20200527 -> 20200528 is: https://github.com/elastic/elasticsearch/compare/16be0e65d387320aff35e3ddbaef3f1f621c41b9...9f6bc6856b1dde0d4a59eac33add780023b350d5

and based on analysis, it can be attributed to #57241.

The specific regression is on the [country_agg-uncached query](https://github.com/elastic/rally-tracks/blob/a2d6f871466e24aa335b491abb9b1b043d16060a/geonames/operations/default.json#L48-L68) on geonames and it reproduces regardless of license type.

The following Rally invocations can be used to identify the regression:

Before #57241 i.e. 6f79750

```
esrally --track=geonames --challenge=append-no-conflicts --include-tasks="delete-index,create-index,check-cluster-health,index-append,refresh-after-index,force-merge,refresh-after-force-merge,wait-until-merges-finish,index-stats,node-stats,country_agg_uncached" --runtime-jdk=bundled --car=defaults --revision=6f79750 --user-tag="commit:before_make_global_ords_terms_simpler_to_understand" --on-error=abort
```

Using suspect commit: 974d236
```
esrally --track=geonames --challenge=append-no-conflicts --include-tasks="delete-index,create-index,check-cluster-health,index-append,refresh-after-index,force-merge,refresh-after-force-merge,wait-until-merges-finish,index-stats,node-stats,country_agg_uncached" --runtime-jdk=bundled --car=defaults --revision=974d236 --user-tag="commit:make_global_ords_terms_simpler_to_understand" --on-error=abort
```

**Comment by nik9000** [comment]
Interesting! I'll take a look this morning.

**Comment by nik9000** [comment]
> Interesting! I'll take a look this morning.

The whole point of these changes is to be able to make a change that makes the `terms` agg *faster*, it'd be super a shame to make it slower.

**Comment by nik9000** [comment]
Rally: [before](https://gist.github.com/nik9000/573702d66ccdf83f7be08768ed6abcd7) [after](https://gist.github.com/nik9000/85f1235d9ac264bb1e77601e8f745414)
Profile: [before](https://gist.github.com/nik9000/5e4edcda580e0bb62c90fa0585d7b86a) [after](https://gist.github.com/nik9000/fd4c3b88163593e274ec5e0634322d5a)

**Comment by nik9000** [comment]
Two things:

The performance of the `master` and the commit in question is the same. So for the most part y "after" tests are going to be against master.

The latency in the `after` rally results is a bit odd. I think it is because we're pushing the little node a bit to hard. The service time is real though.

**Comment by nik9000** [comment]
All of my tests come from loading the data with `master`, taring it, and then doing something like:
```
rm -rf elasticsearch-8.0.0-SNAPSHOT/ && tar xvf master.tar.gz  && tar xvf data.tar  && ./elasticsearch-8.0.0-SNAPSHOT/bin/elasticsearch
```

That allows my to play with the version running the agg very quickly.

**Comment by nik9000** [comment]
The problem is losing an optimization here: https://github.com/elastic/elasticsearch/pull/57241/files#diff-97bf2bf8142ccb028d9115ad647bc307R114

I'll put together a PR to claw this performance back.

**Comment by nik9000** [comment]
[here](https://gist.github.com/nik9000/e413105a83ee1ef0828d47f6f5ae13d8) is rally after the fix.

**Comment by dliappis** [comment]
@nik9000 wow that was fast.

**Comment by nik9000** [comment]
> @nik9000 wow that was fast.

I just broke it! So it didn't take too long to hunt down the bit that mattered. Also, I got lucky.

**Comment by nik9000** [comment]
I think I may have made this slow again.....

**Comment by nik9000** [comment]
[Nightrally](https://elasticsearch-benchmarks.elastic.co/#tracks/geonames/nightly/default/30d) doesn't really show it.

**Comment by nik9000** [comment]
Ok. I believe this is a little worse than it was before I touched it. But not much and the exchange is that inner-terms are way, way faster. I could probably get the performance back eventually, but it isn't going to weigh heavily on me.
