### ISSUE TITLE
Add URL parts to url decode processor

### ISSUE THREAD

**Issue by leehinman** [elastic/elasticsearch#57481]
It would be nice if the url decode processor was able to populate a target field with the parts of the URL.  This would make it much easier to populate things like host & port information when you have a url to work with

https://docs.oracle.com/javase/tutorial/networking/urls/urlInfo.html

**Comment by andrewkroh** [comment]
For reference, these are the fields that ECS splits a URL into: https://www.elastic.co/guide/en/ecs/current/ecs-url.html.
