### ISSUE TITLE
"time" format not applied to running_time in cat tasks api

### ISSUE THREAD

**Issue by sewi-cpan** [elastic/elasticsearch#57502]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.6.0 and 7.6.1, following answers based on 7.6.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu219.10)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu219.10, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
Linux 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The cat tasks api ignores any time format given. The content of the "running_time" column is always "human readable".

**Steps to reproduce**:
Working example:
```
http://localhost:9200/_cat/nodes?v&h=uptime
uptime
  7.5m
http://localhost:9200/_cat/nodes?time=s&v&h=uptime
uptime
   455
http://localhost:9200/_cat/nodes?time=ms&v&h=uptime
uptime
457067
```
Bug example:
```
http://localhost:9200/_cat/tasks?v&h=running_time
running_time
209micros
52.5micros
http://localhost:9200/_cat/tasks?time=s&v&h=running_time
running_time
187.6micros
35micros
http://localhost:9200/_cat/tasks?time=ms&v&h=running_time
running_time
248.7micros
58.7micros
```
Also happens with more and longer (>1s) running tasks.

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Start Elasticsearch
 2. http://localhost:9200/_cat/tasks?time=s&v&h=running_time

**Provide logs (if relevant)**:

**Comment by gaobinlong** [comment]
Same to #54554, the problem has been resolved by #54536, so maybe this issue and #54554 can be closed.
