### ISSUE TITLE
:benchmarks:run tasks runs instead of elasticsearch

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#57521]
Today I encountered a situation where I intended to run local elasticsearch server. Instead, a suite of benchmarks started executing.

Command I've run:
```
./gradlew run -Dtests.es.xpack.license.self_generated.type=trial -Dtests.es.xpack.security.enabled=false -Dtests.heap.size=4g | tee /tmp/es_logs_8
```

Excerpt from logs:
```
> Task :benchmarks:run
36098346.893 ns/op
# Warmup Iteration   2: 33190125.903 ns/op
# Warmup Iteration   3: 37843203.593 ns/op
# Warmup Iteration   4: 26284528.077 ns/op
# Warmup Iteration   5: 30729173.758 ns/op
Iteration   1: 26416481.579 ns/op
Iteration   2: 33929365.500 ns/op
Iteration   3: 26431221.795 ns/op
Iteration   4: 29273386.371 ns/op
Iteration   5: 27746130.324 ns/op
```

FWIW, I have a symlink which makes elasticsearch build ml-cpp locally:

```
elasticsearch-extra$ ll
```
```
total 0
drwxr-xr-x  3 witek  staff   96 Apr 28 17:03 .
drwxr-xr-x  9 witek  staff  288 Apr 28 19:27 ..
lrwxr-xr-x  1 witek  staff   35 Apr 28 17:03 ml-cpp -> /Users/witek/github/elastic/ml-cpp/
```

**Comment by javanna** [comment]
I encountered the same, I suspect it's caused by #57197 . And I just figured that `./gradlew run` != `./gradlew :run` . The latter does what you want @przemekwitek

**Comment by przemekwitek** [comment]
> I encountered the same, I suspect it's caused by #57197 . And I just figured that `./gradlew run` != `./gradlew :run` . The latter does what you want @przemekwitek

Thanks for the hint!

**Comment by rjernst** [comment]
AFAIK, the only thing we could do to "fix" this is rename the task in `:benchmarks`. @mark-vieira @breskeby thoughts?

**Comment by breskeby** [comment]
What would be a good name then? The alternative is to run "./gradlew :benchmark:run". or run the build from the benchmark project folder (btw. I use this little tool that makes runny gradle from within multi project folders easy: https://github.com/dougborg/gdub)

**Comment by mark-vieira** [comment]
I believe this problem was "solved" before by setting `impliesSubProjects = true` on the root build `run` task. This will allow folks running `./gradlew run` from the root folder to run only the root project task, which is almost certainly what they want. I think it's worth doing since it's such a simple mistake to ommit the `:` and the benchmarks project isn't the only culprit here, all plugin projects declare a `run` task as well.

**Comment by rjernst** [comment]
Maybe we should just set that on all `RunTask`s?
