### ISSUE TITLE
Improve top-level docs on mapping field types.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#57548]
As we’ve added more field types, the [list of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/mapping-types.html) has grown quite long. For users, the list of options can be a bit overwhelming and hard to navigate.

To help address this, we could reorganize the reference on field types:
* Instead of the sections 'core', 'complex', and 'specialized', they could be grouped more by use case. For example there would be a 'full-text search' section that contains `text`, `completion`, and `search_as_you_type`, etc.
* We could add a ['how to' page](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/how-to.html) on choosing the right mappings. The assumption is that the user has already played around with Elasticsearch with all data mapped dynamically, and now wants to design the right schema.

Other suggestions are very welcome!

**Comment by jtibshirani** [comment]
A couple other ideas:
* Now that we've add the notion of a 'field type family' in #53175, it would be good to surface these families in the docs. For example, `keyword`, `constant_keyword`, and `wildcard` could be grouped together.
* In the overview page, we could indicate which field types are OSS vs. licensed (?)

**Comment by markharwood** [comment]
> it would be good to surface these families in the docs

I added a short comment[ in the field caps docs](https://github.com/elastic/elasticsearch/pull/58483/files#diff-87e8289b86ba3f98ad31a98fa6636dc9) but I imagine it could be expanded on.

**Comment by jrodewig** [comment]
I've been working on this in #61117 and stumbled across this reference in the Beats dev guide:

> metricbeat/module/{module}/{metricset}/_meta/fields.yml: Contains all fields definitions retrieved by the metricset. As field types, each field must have a core data type [supported by elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-types.html#_core_datatypes). Here’s a very basic example that shows one group from the MySQL status metricset:

https://www.elastic.co/guide/en/beats/devguide/current/metricset-details.html#_fields_yml

I don't think `core` has any formal or technical meaning in the current docs. But I've also heard there are some field types that aren't supported by Metricbeat, such as `histogram`. This change could break those docs and make it difficult for users to know what types are supported.

@jtibshirani @dedemorton What are your thoughts? I like the idea of better organizing these types around family/use case. However, that may mean maintaining a list of unsupported field types in the Metricbeat docs.

**Comment by jtibshirani** [comment]
> I don't think `core` types has/had any formal or technical meaning... However, that may mean maintaining a list of unsupported field types in the Metricbeat docs.

Depending on the new grouping, it could make sense to retain a section for 'core' data types. But I agree that 'core' is not meant to be an official concept, and we regularly add (and may remove) field types from this section. It feels more robust for Metricbeat to not rely on this section and instead explain what field types are supported/ unsupported.

**Comment by jrodewig** [comment]
> It feels more robust for Metricbeat to not rely on this section and instead explain what field types are supported/ unsupported.

Opened https://github.com/elastic/beats/issues/20671 to capture this.

**Comment by jtibshirani** [comment]
I'm going to close now that @jrodewig merged #53175 to reorganize the field types and define type families. We also opened #61441 to track combining all the types in the `keyword` family into the same page.

It'd be great to provide more guidance on choosing the right mappings (through a 'how to' page, visual guide, or even a 'mappings suggestion API'?), but we can plan to address that separately.
