### ISSUE TITLE
Prevent overriding an existing document field having a non null value with a null value for that field

### ISSUE THREAD

**Issue by cipriandumitrel** [elastic/elasticsearch#57546]
Hi guys,

I'm not sure whether there's an existing issue on this topic or not. I searched and found some similar topics but neither one describing exactly the same behaviour. 

I have an existing document in an index called **test_index** like this:

`
GET test_index/_doc/KXbfdXIBUrXF8bei7Oc_
`
`
{
  "_index" : "test_index",
  "_type" : "_doc",
  "_id" : "KXbfdXIBUrXF8bei7Oc_",
  "_version" : 1,
  "_seq_no" : 41,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "bar" : "bar",
    "foo" : "foo"
  }
}
`

We have a flow where sometimes such an existing document is updated with a **null** value for field **foo**. So it's possible to have something like:

`
PUT test_index/_doc/KXbfdXIBUrXF8bei7Oc_
{
  "foo": null,
  "bar": "bar1"
}
`

What I would like as the result would be: when updating an existing document and providing a null value for field foo, the value for this field will not be updated. The rest of the fields should be updated instead. 

So, if I would query that particular document after executing the PUT, I would like to have:

`
{
  "_index" : "test_index",
  "_type" : "_doc",
  "_id" : "KXbfdXIBUrXF8bei7Oc_",
  "_version" : 1,
  "_seq_no" : 41,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "bar" : "bar1",
    "foo" : "foo"
  }
}
`

I tried both the SET and REMOVE processors, but neither of them suited my use case. 

I defined a SET processor like this:

`
PUT _ingest/pipeline/preventNullValuesOverriding
{
  "description": "A pipeline of pipelines",
  "version": 1,
  "processors": [
    {
      "set" : {
        "field": "foo",
        "value": "{{foo}}",
        "if": "ctx.foo != null"
      }
    }
  ]
}
`, but of course it didn't work because when I set a null value for **foo**, the pipeline won't be executed because of the if condition. 

I also tried to use the REMOVE processor. I defined the pipeline like this:

`
PUT _ingest/pipeline/removeNullFields
{
  "description": "Remove null fields",
  "version": 1,
  "processors": [
    {
      "remove" : {
        "field": "foo",
        "if": "ctx.foo == null",
        "ignore_missing": true
      }
    }
  ]
}
`
I've put **ignore_missing** on true, because in the documentation it's stated that _If true and field does not exist or is null, the processor quietly exits without modifying the document_ . But in this case it still removes the field from the merged document. The same removing the ignore_missing line.

Is there a processor or a combination of processors that could help me for this use case?

**Comment by gaobinlong** [comment]
@cipriandumitrel , maybe you can use [UPDATE API:](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-update.html)

POST index/_doc/1/_update
```
{
  "script": {
    "source": "if (params.foo != null) ctx._source.foo = params.foo",
    "lang": "painless",
    "params": {
      "foo": null,
      "bar":"bar"
    }
  }
}
```

**Comment by cipriandumitrel** [comment]
Hi @gaobinlong , thanks a lot for your response, but the UPDATE API is not suitable for me. The reason for which I am trying to do this using processors is because I am writing in elastic search directly from Kafka using Kafka Connect, so somehow writing in ES is transparent for me. Using the UPDATE API would mean to create my own client that has a Kafka listener and do the logic against ES when a new message arrives in Kafka. But on the other hand I would lose all the Kafka connect goodies.

**Comment by gaobinlong** [comment]
@cipriandumitrel，ingest pipeline only handles the incoming documents and cannot fetch the origin field value from the index, so maybe we can only update document partially by UPDATE API which will fetch the document from the index firstly and then update the document.

**Comment by cipriandumitrel** [comment]
Ok, that answered my question. Thanks a lot, @gaobinlong, for your input.
