### ISSUE TITLE
Security privileges for ingest pipelines

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#57586]
Currently we have minimal support in Security for restricting access to ingest pipelines. There is a single dedicated privilege, `manage_ingest_pipelines`, that provides access to CRUD APIs for pipeline definitions.

We should improve this model in the following 2 ways:

- make the `manage_ingest_pipelines` privilege a "configurable cluster privilege", so that admins can specify that users can manage pipelines only in a _certain namespace_, instead of all the pipelines. Ideally, we should also create a "read" type of privilege, also "configurable" for pipeline namespaces, so that users can only see the pipeline definition, without being permitted to change or remove it.
- create a new type of privilege that restricts access to pipelines during ingestion. The exact format for defining the new privilege is still to be determined. But it must restrict access to an index and a pipeline simultaneously, e.g. permits the usage of pipelines whose names match the "pipeline-format1-\*" wildcard only on indices under the "index-test-\*" namespace. However, there are some pipelines that have the same outcome no matter the target index (they are used to re-route documents to other indices) in which case restricting access to the pipeline by index name is not necessary.

During a recent brainstorm inside the ES Security team, we've identified that in order to support restricting access to the pipeline usage during ingestion, we must refactor the execution of pipelines from https://github.com/elastic/elasticsearch/blob/a9338672c5d4e10150e88a4d56f05cf0a0215373/server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java#L195 as an internal transport action. This way, Security will be able to intercept this call and reject individual bulk index requests that reference unauthorized pipelines. Can someone from @elastic/es-core-features please give some feedback on this?

**Comment by martijnvg** [comment]
> This way, Security will be able to intercept this call and reject individual bulk index requests that reference unauthorized pipelines. Can someone from @elastic/es-core-features please give some feedback on this?

I think this makes sense. Initially I was hoping this could be done by just introspecting a bulk request in security, but then we don't know about default and final pipelines. Also noted in #57968, in a pipeline the `_index` can be changed and potential other pipelines can execute via a redirect. So a dedicated internal action seems like the right choice to properly authorize whether a user can use specific pipelines.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
