### ISSUE TITLE
Range aggregations do not work as expected with NANOSECOND resolution

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#57651]
DateRangeAggregatorTests#testCase() has the following code in it, which is supposed to change the resolution at which aggregations on date range fields are run:
```
DateFieldMapper.Builder builder = new DateFieldMapper.Builder(DATE_FIELD_NAME)
            .withResolution(resolution);
        DateFieldMapper.DateFieldType fieldType = builder.fieldType();
        fieldType.setHasDocValues(true);
        fieldType.setName(DATE_FIELD_NAME);
```

However, `DateFieldMapper.Builder.withResolution()` doesn't actually make any changes to the underlying MappedFieldType, so this means that tests are always run with the default resolution (`Resolution.MILLISECONDS`).  The tests fail if the resolution is set explicitly on the fieldtype.

RangeAggregatorTests#testDateFieldNanosecondResolution has the same test bug, and also fails when the fieldType resolution is set correctly.

**Comment by nik9000** [comment]
I added some tests for, I think, min and max that assert nanoseconds. The way it is rigged up feels a little brittle to me.

**Comment by James-Brosnahan-Agile-1** [comment]
See the limitations section: [date-nanos-limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/date_nanos.html#date-nanos-limitations)

**Comment by nik9000** [comment]
Looks we still have a skip for this. I'll see about removing it too.
