### ISSUE TITLE
Highlighting numeric fields issue

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#5771]
I am not sure it is feasible or even doable but the problem I have is that when I search on _all or as _all-like field which include numeric field (as text of course) I get a hit but the numeric field (which is folded into _all) does not get highlighted if I include its name into highlights part of the query definition. It works fine for string fields but not for numbers (or dates). I tested it using postings and plain highlighters. Did not try FVH because performance is poor for me as I am highlighting close to 100 small fields)

Is it a bug or works a designed? Any chance of making it work - that would save us lots of work arounds (multifields with text representation of numbers which is used for highlighting)

As a related issue, when I search and highlight on the same numeric field using plain highlighter it does not get highlighted but works with postings

**Comment by clintongormley** [comment]
Since the change to use Point fields for numerics, it is no longer possible to highlight numeric fields with the postings highlighter (or any other highlighter).  If this is required, then the numeric value also needs to be indexed as a `keyword` field.
