### ISSUE TITLE
[Transform] increase page size limit to 65k

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#57719]
#57042 increases the limit for `search.max_buckets` from `10k` to `65k`, this applies to composite aggregation, too.

Transform hard codes the old `10k` limit. This should be changed to support `65k`. 

Ideally we remove the hard coding and read the default from the default constant, even better would be to get the value from settings, because the `65k` is the default of a cluster setting.

**Comment by RvI101** [comment]
I can take a look at this.

**Comment by Esduard** [comment]
Greetings. Is this issue taken at the moment? I'd like to contribute to the project and this seems like a good issue to take.

**Comment by Esduard** [comment]
#74651

**Comment by Esduard** [comment]
@benwtrent Thanks for letting me know. I've spent most of the time trying to run the project on my machine and have managed to run some tests after making the issue's changes.
