### ISSUE TITLE
Dense_Vector field not supported on ElasticSearchService AWS

### ISSUE THREAD

**Issue by tudor33sud** [elastic/elasticsearch#57742]
I am trying to implement a solution for text similarity and I am having issues with the ElasticSearch version. I am using AWS ElasticSearch service.

Initially, I started development locally on ElasticSearch 7.4 downloaded from the official site. Everything worked fine, until I created an aws ES cluster and deployed my code. It seems that mapping doesn't work as expected on the cloud version  with the following reason:  
```
"caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "No handler for type [dense_vector] declared on field [stext_sbert_nli]"
    } 

```
I am attaching GET /  information for the cloud cluster.

```
{
  "name" : "",
  "cluster_name" : "",
  "cluster_uuid" : "",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2020-05-05T04:47:22.951128Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```
I find it frustrating that the cloud managed solutions are advertised to give you the full experience. Even though dense vector was added in 7.1, even on 7.4 I cannot use it... Can you kindly let me know if there's any option I have to enable that feature?

Thanks!

**Comment by dadoonet** [comment]
`dense_vector` only exists from the basic free version of Elasticsearch. See https://www.elastic.co/subscriptions (Vector field type).

Did you look at https://www.elastic.co/cloud and https://aws.amazon.com/marketplace/pp/B01N6YCISK ?

Cloud by elastic is one way to have access to all features, all managed by us. Think about what is there yet like Security, Monitoring, Reporting, SQL, Canvas, APM, Logs UI, Infra UI, SIEM, Maps UI, AppSearch and what is coming next :) ...

If you have further questions, please come and ask on discuss.elastic.co.

Thanks!
