### ISSUE TITLE
"size" parameter for filtered aliases to prevent DoS

### ISSUE THREAD

**Issue by firla** [elastic/elasticsearch#5774]
Hi,

To secure an ES installation (prevent DoS) it's necessary to restrict the number of returned documents by configuration (for all ES queries). Currently, it seems to be not possible to use the 'size' filter in filtered aliases. The "limit" filter isn't suitable, see e.g. https://stackoverflow.com/questions/21444623/elasticsearch-limit-filter-ambiguity for the difference.

Adrien mentioned (https://groups.google.com/forum/?fromgroups#!topic/elasticsearch/86A5DbEP94E) that this would be also an interesting feature given that while Elasticsearch is fast at retrieving the top hits, going deeper in the result set can use lots of resources (both CPU-wise and memory-wise).

=> Please implement the "size" parameter for filtered aliases.
=> Are there any workarounds for this problem.

Thank you, BTW: ES is really great!

**Comment by dakrone** [comment]
Related to #9311

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/14116
