### ISSUE TITLE
CircuitBreakingException when *Beats dashboard.enabled=true Crashes the entire ECK network

### ISSUE THREAD

**Issue by jaydlowrider** [elastic/elasticsearch#57833]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: [] repository-gcs mapper-size

**JVM version** (`java -version`): OpenJDK 13

**OS version** (`uname -a` if on a Unix-like system): Linux #1 SMP Tue Feb 11 05:33:03 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

circuit_breaking_exception at shard 3index .server.log.2020.05.28node hRMLMRV1S2acHAMvwcOT_g
Type
circuit_breaking_exception
Reason
[parent] Data too large, data for [<transport_request>] would be [10251944894/9.5gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10251941816/9.5gb], new bytes reserved: [3078/3kb], usages [request=0/0b, fielddata=3394401948/3.1gb, in_flight_requests=3078/3kb, accounting=5119101055/4.7gb]
Bytes wanted
10251944894
Bytes limit
10150864486
Durability
PERMANENT

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Install Metricbeat 7.7.0
 2. `setup.dashboards.enabled: true` and all relevant Kibana settings for the metricbeat.yml
 3. and start metricbeat 

**Provide logs (if relevant)**:
{"type":"log","@timestamp":"2020-06-01T14:44:29Z","tags":["status","plugin:reporting@7.6.2","error"],"pid":6,"state":"red","message":"Status changed from red to red - [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10193362360/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193362360/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb], with { bytes_wanted=10193362360 & bytes_limit=10150864486 & durability=\"PERMANENT\" }","prevState":"red","prevMsg":"[circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10200774048/9.5gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10200774048/9.5gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3394415362/3.1gb, in_flight_requests=0/0b, accounting=5119101055/4.7gb], with { bytes_wanted=10200774048 & bytes_limit=10150864486 & durability=\"PERMANENT\" }"}
{"type":"log","@timestamp":"2020-06-01T14:44:29Z","tags":["info","monitoring","kibana-monitoring"],"pid":6,"message":"Monitoring status upload endpoint is not enabled in Elasticsearch:Monitoring stats collection is stopped"}
{"type":"log","@timestamp":"2020-06-01T14:44:29Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10193362360/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193362360/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb], with { bytes_wanted=10193362360 & bytes_limit=10150864486 & durability=\"PERMANENT\" } :: {\"path\":\"/_xpack\",\"statusCode\":429,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [10193362360/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193362360/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb]\\\",\\\"bytes_wanted\\\":10193362360,\\\"bytes_limit\\\":10150864486,\\\"durability\\\":\\\"PERMANENT\\\"}],\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [10193362360/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193362360/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb]\\\",\\\"bytes_wanted\\\":10193362360,\\\"bytes_limit\\\":10150864486,\\\"durability\\\":\\\"PERMANENT\\\"},\\\"status\\\":429}\"} error"}
{"type":"log","@timestamp":"2020-06-01T14:44:29Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10193397776/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193397776/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb], with { bytes_wanted=10193397776 & bytes_limit=10150864486 & durability=\"PERMANENT\" } :: {\"path\":\"/_xpack\",\"statusCode\":429,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [10193397776/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193397776/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb]\\\",\\\"bytes_wanted\\\":10193397776,\\\"bytes_limit\\\":10150864486,\\\"durability\\\":\\\"PERMANENT\\\"}],\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [10193397776/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193397776/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb]\\\",\\\"bytes_wanted\\\":10193397776,\\\"bytes_limit\\\":10150864486,\\\"durability\\\":\\\"PERMANENT\\\"},\\\"status\\\":429}\"} error"}
{"type":"log","@timestamp":"2020-06-01T14:44:29Z","tags":["status","plugin:xpack_main@7.6.2","error"],"pid":6,"state":"red","message":"Status changed from red to red - [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10193397776/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193397776/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb], with { bytes_wanted=10193397776 & bytes_limit=10150864486 & durability=\"PERMANENT\" }","prevState":"red","prevMsg":"[circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [10193362360/9.4gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10193362360/9.4gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=3386311265/3.1gb, in_flight_requests=0/0b, accounting=5117300532/4.7gb], with { bytes_wanted=10193362360 & bytes_limit=10150864486 & durability=\"PERMANENT\" }"}
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [prod-logs-es-warm-2][10.248.141.4:9300][indices:data/read/search[phase/query]]",
"Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be [10304452728/9.5gb], which is larger than the limit of [10150864486/9.4gb], real usage: [10304449576/9.5gb], new bytes reserved: [3152/3kb], usages [request=0/0b, fielddata=3386319373/3.1gb, in_flight_requests=3152/3kb, accounting=5117300532/4.7gb]",

"at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:343) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:171) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:119) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [transport-netty4-client-7.6.2.jar:7.6.2]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326) [netty-codec-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) [netty-codec-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478) [netty-handler-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) [netty-handler-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) [netty-handler-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503) [netty-codec-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) [netty-codec-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281) [netty-codec-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:600) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:554) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-transport-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-common-4.1.43.Final.jar:4.1.43.Final]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.43.Final.jar:4.1.43.Final]",
"at java.lang.Thread.run(Thread.java:830) [?:?]"] }

**Comment by jaydlowrider** [comment]
This error made our cluster unresponsive and kibana fail to load.

**Comment by gwbrown** [comment]
Hi @jaydlowrider, thanks for filing this issue.

The error message given in your post are from Elasticsearch's memory circuit breakers, which kill requests that are likely to cause stability problems in the cluster, especially when memory usage is high. If this happens to every request, as you're seeing, it's a strong indication that the cluster is heavily overloaded. Is there other load (other indices, other processes sending documents, other queries, etc.) present on this cluster, or did this issue occur immediately after setting up a new cluster?

If there's other load, it's highly likely that the cluster is simply overloaded and either needs the load reduced, or more resources added.

If this occurred with a new cluster, there might be a bug to investigate here.

**Comment by melvinFF** [comment]
Hello @gwbrown 

Thanks for your response.. 

I thought it was beats that caused this, but it seems that its an ongoing problem similar to what you mentioned.

The cluster is heavily used, there is very high write, and query, we have 1TB ingest for of 1 index, specifically and we have ILM setup as for hot-warm rolling 3 days on Hot and 25 days to warm.

>present on this cluster, or did this issue occur immediately after setting up a new cluster?
This happens over time, it looked like between 1-2 weeks. I have to bounce the entire cluster to get stabled.

When this happens, Application is still in green state, and don't see any problems with cluster, is there any indication that I can use to see where I can find the issue?

**Comment by jaydlowrider** [comment]
Hello @gwbrown

Thanks for your response..

I thought it was beats that caused this, but it seems that its an ongoing problem similar to what you mentioned.

The cluster is heavily used, there is very high write, and query, we have 1TB ingest for of 1 index, specifically and we have ILM setup as for hot-warm rolling 3 days on Hot and 25 days to warm.

>present on this cluster, or did this issue occur immediately after setting up a new cluster?

This happens over time, it looked like between 1-2 weeks. I have to bounce the entire cluster to get stabled.

When this happens, Application is still in green state, and don't see any problems with cluster, is there any indication that I can use to see where I can find the issue?

**Comment by gwbrown** [comment]
Since the errors you encountered seem to be due to overload on the cluster, and we try to keep Github issues reserved for verified bug reports and feature requests, I'd like to close this issue. That said, I know that your problem has not been resolved - could you please stop by our [forums](https://discuss.elastic.co/)? There's an active community in the [forums](https://discuss.elastic.co/) (including some Elasticsearch developers) that should be able to help get an answer to your question.
