### ISSUE TITLE
Rasterization artefacts for geotile_grid and geo_centroid aggregations on geo_shape

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#57846]
There's some odd rasterization effects that seem to occur when running a geo_centroid agg under a geotile_grid agg for geo_shape fields.

It seems to occur for large shapes that overlap multiple geotile_grid cells.

Steps:

1) Download the world_countries file from EMS: https://maps.elastic.co/v7.7/index.html#file/world_countries
2) Index into Elasticsearch. Use `geo_shape` for coordinates field.
```
{
   "world_countries_v1":{
      "mappings":{
         "_meta":{
            "created_by":"file-upload-plugin"
         },
         "properties":{
            "coordinates":{
               "type":"geo_shape"
            },
            "iso2":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            },
            "iso3":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            },
            "name":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            }
         }
      }
   }
}
```

3) Issue following query
```
{
  "size": 0,
  "aggs": {
    "gridSplit": {
      "geotile_grid": {
        "bounds": {
          "top_left": [
            121.475075,
            74.95303
          ],
          "bottom_right": [
            30.36361499999998,
            -17.385369999999998
          ]
        },
        "field": "coordinates",
        "precision": 8
      },
      "aggs": {
        "gridCentroid": {
          "geo_centroid": {
            "field": "coordinates"
          }
        }
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [],
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "match_all": {}
        },
        {
          "geo_shape": {
            "coordinates": {
              "shape": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -239.0625,
                      75.14078
                    ],
                    [
                      -239.0625,
                      -17.97873
                    ],
                    [
                      30.9375,
                      -17.97873
                    ],
                    [
                      30.9375,
                      75.14078
                    ],
                    [
                      -239.0625,
                      75.14078
                    ]
                  ]
                ]
              },
              "relation": "INTERSECTS"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

You can also use Kibana to see the result. Notice how around Mountain time zone, the centroid switches from snapping to top-left to top-right. This causes this "overlap" effect.

![image](https://user-images.githubusercontent.com/1833023/84081980-ffd77200-a9ac-11ea-8fbf-62a144695cca.png)

cc @talevy @nknize

**Comment by iverase** [comment]
I am having a hard time trying to understand the issue here. It seems to me a side-effect of how maps is using the centroid information? Could you explain exactly your expectations?

**Comment by thomasneirynck** [comment]
@iverase we're using the result of the geo_centroid to place the clusters on the map. It seems that the centroid is not calculated to the middle of the cell, but seems to snap to a corner. Why is it snapping to a corner?

**Comment by iverase** [comment]
I doubt is ES that is snapping the centroid to a corner.

A sub aggregation only knows about the documents in the bucket and it will calculate the centroid of the documents in the bucket. It is my understanding that the snapping is done in Kibana not in ES? It was added because this effect might happen when you have Muti-points in a geo_point field.

**Comment by thomasneirynck** [comment]
@iverase 

awesome call. Yes, actually here: https://github.com/elastic/kibana/pull/13581

This displaces the problem a little. This was introduced for points. For shapes this makes less sense. E.g. when a shape completely overlaps the cell (like the USA), we would want it in the middle.

Any suggestion on how we could use ES to determine that a shape overlaps an entire grid-cell? Nest another geo_bounds under it?

**Comment by iverase** [comment]
I need to think over it but I agree that this strategy might need to be different with shapes.

**Comment by iverase** [comment]
There is something cool about the current implementation, you can actually see where the centroid of a shape is.

**Comment by iverase** [comment]
We spoke offline and we agreed that those artefacts are expected and there is nothing to here, therefore I am closing the issue.
