### ISSUE TITLE
[ML] Make .ml-config and .ml-meta indices system indices

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#57874]
All indices beginning with `.ml` need to migrate to being either hidden indices or system indices. They cannot be normal indices from 8.0 onwards.

#52420 made many ML indices hidden.  The two that are left are `.ml-config` and `.ml-meta`.  These need to be made into system indices.

They do not need to be accessed from outside of the ML plugin except using the APIs we already have.

**Comment by przemekwitek** [comment]
As of today `MachineLearning` is a `SystemIndexPlugin` and both `.ml-meta` and `.ml-config` indices are returned via `MachineLearning::getSystemIndexDescriptors` method.
As per discussion with the implementors of system indices functionality, no additional changes are needed on our side so I'm closing this issue.

**Comment by droberts195** [comment]
> no additional changes are needed on our side

I have a feeling this will not be the case forever.  It sounds like the current implementation of system indices does not lock them down as much as they're intended to be locked down eventually.

When they are fully locked down I bet we will find we have test cases that access the indices in non-standard ways for initial setup or test assertions.

I think there is going to be a backdoor way for superusers to search system indices even though they aren't supposed to, so the simplest solution will probably be to change some tests to use that backdoor method as the lockdown gets stricter.

Still, good news we didn't need to do anything immediately 🎉

**Comment by przemekwitek** [comment]
> I have a feeling this will not be the case forever. It sounds like the current implementation of system indices does not lock them down as much as they're intended to be locked down eventually.

That's my feeling too after talking to Jay and Gordon.

> Still, good news we didn't need to do anything immediately 🎉

+1
If there is any work that comes up related to system indices (e.g.: adjusting tests), we will address it then.
