### ISSUE TITLE
Update Watcher Slack integration to work with Slack Apps

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#57904]
Slack designated "custom integrations" as legacy in March 2017 (which is around Elasticsearch v2.4.5 time) and have documented legacy custom integrations as not recommended in their guide:

https://api.slack.com/legacy/custom-integrations/incoming-webhooks
![image](https://user-images.githubusercontent.com/7216393/84194346-bab94b80-aa51-11ea-8cb8-cf56b8a42649.png)

They have since recommended using Incoming Webhooks feature in Slack Apps: https://api.slack.com/messaging/webhooks as a replacement of legacy custom integrations.

So far, we haven't caught up with these changes.  For example, our current documentation still provides inline instructions to set up webhook URLs using the legacy custom integrations.  I have filed a [PR](https://github.com/elastic/elasticsearch/pull/57834) to address this.

I am filing this as a meta issue to identify all the areas we have to address as part of this effort, so that our integration point with Slack is up-to-date.  I am listing some ideas below and will let the Elasticsearch team review and create the appropriate child issues/PRs :)

- [ ] Custom integrations has not been recommended by Slack since March 2017.  I have filed this doc PR to update our guide to reference the recommended approach by Slack (using incoming webhooks feature in Slack App):  https://github.com/elastic/elasticsearch/pull/57834
- [ ] Make `message.to` an optional setting.  Currently, it is a required setting.

![image](https://user-images.githubusercontent.com/7216393/84196142-a4f95580-aa54-11ea-87f2-a9adb3116fce.png)

Per Slack documentation, they no longer allow runtime overwrite of the default/destination channel/username, etc.. it must now inherit from the incoming webhook URL configuration in the Slack App.

https://api.slack.com/messaging/webhooks
>You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.

https://api.slack.com/legacy/custom-integrations/incoming-webhooks#migrating-from-legacy
>the only thing you can no longer do is customize the destination channel and author identity at runtime.

The suggestion here is to make it optional because there might be users out there who had the legacy "custom integrations" service installed in Slack where this setting is still applicable and (can overwrite the channel list).

- [ ] At some point, we may want to remove the support for `message.to` option in a future major version given that Slack no longer allows this type of overwrite.  This will be a breaking change though for users who had previously installed the custom integration in Slack.  We might want to coordinate with Slack's removal of custom integration from their product in the future.

- [ ] We should update the Elasticsearch documentation to indicate that `message.to` (runtime overwrite of the destination channels/usernames) is no longer possible due to the Slack API changes noted above.  Because `message.to` is still a required field today, they will have to specify the same (single) channel/username that is configured in the Slack App.  Also clarify that multiple elements in this `message.to` array will only work for users who are still using the Slack legacy implementation (https://api.slack.com/legacy/custom-integrations/incoming-webhooks) that is no longer recommended.

- [ ] More user friendly handling of multiple Slack channel notifications:  A single Slack action in Elasticsearch can only work with a single `secure_url` (i.e., webhook URL) today. With the Slack API/App now inheriting the channel/username association directly from the Slack App configuration, users will have to create multiple webhook URLs in Slack App because Slack only allows for a single channel/username per webhook URL.  It will be nice for our integration to be enhanced to support this multiple webhook URL design.  The current workaround is to use multiple Slack actions in a watch (1 for each Elasticsearch Slack account/Slack incoming webhook URL) for the multiple channel notification use case.

**Comment by adamthor1** [comment]
Are there any updates on this topic? Same as in June 2020, incoming webhooks are not recommended by Slack and "will be deprecated and possibly removed in the future".

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
