### ISSUE TITLE
Stats API fetching all indices information if given regex has no matches

### ISSUE THREAD

**Issue by ferhatsb** [elastic/elasticsearch#5794]
Hi,
I expect to get empty response for scenario;

```ssh
#create an index
curl -XPOST http://localhost:9200/test-1

# execute _stats for indices starting with xyz (ensure this regex has no matches)
curl -XPOST http://locahost:9200/xyz*/_stats
```

returns stats of all indices. I think this should return empty response.

Tried with 1.0.1 and 1.1.0

**Comment by xuzha** [comment]
@clintongormley, looks like this issue has been fixed. I cannot reproduce it.

**Comment by clintongormley** [comment]
thanks @xuzha
