### ISSUE TITLE
7.x BWC with v7.4.2 fails to start the testcluster due to missing gc.log file

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#57965]
This is triggered while investgating a [CI test failure](https://gradle-enterprise.elastic.co/s/5olm2yvykcazk). However, this issue is _not_ about the CI failure, but is about that the reproduction line does **not** work locally.

> ./gradlew ':x-pack:qa:rolling-upgrade:v7.4.2#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" -Dtests.seed=C320303B19599520 -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Mexico/General -Druntime.java=8

The testcluster fails with the following error message:
```
[0.009s][error][logging] Error opening log file 'logs/gc.log': No such file or directory
[0.009s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
```
Build scan: https://gradle-enterprise.elastic.co/s/e5ghyqne72il2

The same test line works by replacing `v7.4.2` with `v7.5.0`, so this is version specific. 

@mark-vieira also confirmed that this is a problem when just downloading and running `v7.4.2` on its own. Interestingly, this also depends on the JDK version, e.g. Oracle JDK 8.0.201 works, but 8.0.241 does *not*.

**Comment by pgomulka** [comment]
possibly related to https://github.com/elastic/elasticsearch/issues/45673
the problem reproduce for me on `"1.8.0_181"` as well as `1.8.0_275`

**Comment by rjernst** [comment]
This issue is quite old, and it is unclear if it is still an issue. I'm going to close and we can reopen if the issue reoccurs.
