### ISSUE TITLE
[ML] Delete job should delete associated annotations

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#57976]
Currently annotations are not deleted if a user deletes an ML job.

The historical decisions that led to this decision are in #33376.  For example:

> This makes the deletion logic quite complicated - annotations should be deleted when all jobs they relate to are deleted, but the wide variety of ways of specifying which jobs an annotation relates to makes determination of this complex.

and:

> We also decided that it would be useful to have persistent annotations, that _don't_ get deleted if all the jobs they relate to get deleted. This would be useful for the case of repeatedly deleting and recreating a job to try out slightly different configurations.
>
> So there should be an `is_persistent` boolean field in the annotations too.

The way annotations was eventually developed means the first thought is completely irrelevant.  We envisaged annotations that would apply to multiple jobs but currently every annotation is bound to exactly one job.

The second idea is still potentially relevant, but we never implemented the `is_persistent` boolean field.

Given that large numbers of annotations will now be generated by model change events, it makes sense that we delete all annotations related to a job with a `create_username` of `_xpack` when the job is deleted.

This should be done as an extra step in the chain of deletion steps in `TransportDeleteJobAction.deleteJobDocuments()`.

**Comment by droberts195** [comment]
Given the comments of https://github.com/elastic/elasticsearch/issues/57977#issuecomment-642580338 I changed the spec to say:

> with a `create_username` of `_xpack`

**Comment by sd1998** [comment]
@droberts195 Can this issue be assigned to me?

**Comment by droberts195** [comment]
@sd1998 sure, if you can fix this that would be great. However, we need it fixed by the end of June, as we cannot release the next version of the stack with this problem. If you don’t think you can fix it by then please let me know and we’ll take it back to work on internally.

**Comment by sd1998** [comment]
@droberts195 I am new to the project, if there is a time bound on this then I don't think I should take it up due to my lack of understanding of the codebase. Wouldn't want cause any delays.

**Comment by przemekwitek** [comment]
I'm starting work on this issue.
