### ISSUE TITLE
[ML] Delete some annotations when reverting a model snapshot with delete_intervening_results=true

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#57982]
At the moment when a model snapshot is reverted using the revert model snapshot API with [`delete_intervening_results`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-revert-snapshot.html#ml-revert-snapshot-request-body) set to `true`, all results later than the last result time stored in the model snapshot document are deleted.

It also makes sense to delete certain types of annotations in this situation:

* `delayed_data` - because the results based on the delayed data are being deleted, the fact that the data was originally delayed is not relevant.  If the same time period is re-run and data is delayed again then a new `delayed_data` annotation will be generated.
* `model_change` - because the model that changed is no longer in use; it has been rolled back to a time before those changes occurred.  If the same time period is re-run then new `model_change` annotations may be generated, but these may or may not be the same as the original ones depending on what else was changed before the re-run (e.g. calendar events or corrections to the input data).

Only annotations that relate to periods after the reversion time should be deleted - earlier ones are still relevant.

Other types of annotation should not be deleted when reverting a model snapshot.

There is actually a tricky situation with `model_change` annotations in the case where `delete_internvening_results` is `false`.  Results will still exist around the time of the model changes, so it makes sense to keep them to explain these results.  But the model changes _won't_ apply to the period after which the datafeed is restarted using the reverted model.  Ideally we'd add an annotation at the start time of the datafeed after reverting a model snapshot with `delete_internvening_results=false` to say that model changes in between the snapshot time and the restart time weren't relevant after the restart.  But this would be extremely hard as they are two separate APIs that have no knowledge of each other.

It is much simpler and more obvious what needs doing when `delete_internvening_results=true`, so implementing that would be a good start.

**Comment by przemekwitek** [comment]
> It is much simpler and more obvious what needs doing when delete_internvening_results=true, so implementing that would be a good start.

Ok, I'll start with that.
