### ISSUE TITLE
Disable rate limiting for ingest scripts

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#58008]
With recent changes to [ingest pipelines](
https://github.com/elastic/elasticsearch/pull/57960), scripts are eagerly compiled at pipeline registration.

Since stored scripts are rare for ingest pipelines, we can avoid user pain by skipping compilation rate limiting.

TODO: validate "Since stored scripts are rare for ingest pipelines"

We should also deprecate stored scripts for ingest pipelines.

**Comment by jakelandis** [comment]
> TODO: validate "Since stored scripts are rare for ingest pipelines"

@ph - do you know if any of the Elastic ingest management or beats use stored scripts for their

**Comment by jakelandis** [comment]
@stu-elastic - this may duplicated with https://github.com/elastic/elasticsearch/issues/49763 where we discussed this and tentativly agreed that would be good idea, but was blocked https://github.com/elastic/elasticsearch/issues/50152.  Is it possible to disable rate limiting for ingest scripts without https://github.com/elastic/elasticsearch/issues/50152 ?

**Comment by stu-elastic** [comment]
Hey @jakelandis #50152 is in master and got delayed on backport, which I'm back to now.  I'll take this one once that backport is done.

**Comment by stu-elastic** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/59267
