### ISSUE TITLE
How does es realize the integration of SQL nested group aggregation?

### ISSUE THREAD

**Issue by fl1312661385** [elastic/elasticsearch#58022]
SELECT
	t.mykey,
	count(*),
	t.myvalue
FROM
	(
		SELECT
			date_year mykey,
			count(*) myvalue
		FROM
			ts_user_behavior
		GROUP BY
			date_year,
			date_month,
			date_day
	) t
GROUP BY
	t.myvalue;

**Comment by jrodewig** [comment]
@fl1312661385 

I'm sorry to hear you are having trouble with Elasticsearch. However, your question is better suited to the support forums over at https://discuss.elastic.co.

We prefer to use Github issues only for bug reports and feature requests. I'm closing this issue, but I encourage you to ask this question in the forum instead.

Thanks,
