### ISSUE TITLE
[CI] Seed-specific failure of TriangleTreeTests.testRandomPolygonIntersection in 7.x

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#58032]
On the 7.x branch `TriangleTreeTests.testRandomPolygonIntersection` fails reproducibly using:

```
./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.index.fielddata.TriangleTreeTests.testRandomPolygonIntersection" -Dtests.seed=FE54FE32BC33F7CF -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=America/Santiago -Druntime.java=8
```

The error is:

```
org.locationtech.spatial4j.exception.InvalidShapeException: Cannot determine orientation: edges adjacent to (-5.2298701235708654E-183,0.0) coincide
```

Changing the seed makes it pass, so it's a seed-specific failure.

I saw this in a PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/1186/testReport/junit/org.elasticsearch.xpack.spatial.index.fielddata/TriangleTreeTests/testRandomPolygonIntersection/

**Comment by iverase** [comment]
The problem is that we are generating degenerated polygons.
