### ISSUE TITLE
Add an API to easily report why shard relocation isn't happening

### ISSUE THREAD

**Issue by sebgl** [elastic/elasticsearch#58030]
**Context**:

When migrating data from some nodes to another set of nodes, we can use `cluster.routing.allocation.exclude._name` in the transient cluster settings.

One way to monitor this migration is to inspect the shards on the excluded nodes, and consider the migration to be over once the node does not hold any shard any more.
We can also use `_cat/health` to inspect `relo: <number>`, `init: <number>`, `pending_tasks: <number>`, which also gives some insights on whether shards relocation is still happening.

In certain situations, data migration can stay "stuck" and some shards just cannot be relocated. Examples:
- other nodes already hold a copy of the shard to relocate
- other nodes don't have enough disk space to hold the shard
- other nodes mismatch the allocation filters
- other nodes already hold some shards which make us reach the index `index.routing.allocation.total_shards_per_node ` limit

When we suspect data migration is stuck, I think (?) the only way to get more details is to:
- retrieve the name of the nodes that were excluded (from `_cluster/settings`)
- inspect whether shards are still STARTED on those nodes (from eg. `_cat/shards`)
- inspect whether anything seems to be happening (from `_cat/recovery` and maybe `_cat/health`)
- if nothing seems happening, grab the name of a shard (from `_cat/shards` that is still STARTED on an excluded none
- call `POST _cluster/allocation/explain  {"index": <index_name>, "shard": "<number>", "primary": true/false}`
- read the output of this call to understand why migration to node X cannot happen

**Feature request**:

Provide a single API that gives a reason about why a random shard, that should not remain on its current node, cannot be relocated (unless throttled by other concurrent operations).

**Idea**:

If some shards are unassigned, we can use `GET _cluster/allocation/explain` (with no body), to get some insights on why a (random) shard is currently unassigned. It does not require an index name, which makes things easier.

Could an API call along the lines of `GET _cluster/allocation/explain?includeFailedRelocation=true` provide a similar mechanism for shards that should but cannot be relocated?

**Comment by sebgl** [comment]
`decommission_possible` in the [decommission API](https://github.com/elastic/elasticsearch/issues/49064) seems to be a similar idea.

**Comment by DaveCTurner** [comment]
The node shutdown API (and the new health API) should mean that ECK no longer needs to care so much about the details of relocating shards while decommissioning a node, so I'm closing this as no longer relevant. It's possible that there's still gaps in our error reporting but I think this is mostly out of scope of the shard allocator and so deserves a separate discussion.
