### ISSUE TITLE
SearchSourceBuilder not functional on Android

### ISSUE THREAD

**Issue by jhudis** [elastic/elasticsearch#58075]
**Elasticsearch version**: 7.7.1

**Plugins installed**: Kibana

**JVM version**: 1.8.0_251

**OS version**: Android 10

**Description of the problem including expected versus actual behavior**:

Our team is trying to use the Elasticsearch Java High Level REST Client 7.7.1 on an Android device. So far we've only been indexing data, not querying, and that code has been functional. But when trying to simply *instantiate* a `SearchSourceBuilder` object, the following error occurs:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.CodeSource java.security.ProtectionDomain.getCodeSource()' on a null object reference
   at org.elasticsearch.Build.getElasticsearchCodeSourceLocation(Build.java:194)
   at org.elasticsearch.Build.<clinit>(Build.java:137)
   at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:154) 
   at org.elasticsearch.search.builder.SearchSourceBuilder.<clinit>(SearchSourceBuilder.java:83)
```
The specific line of code which causes this `NullPointerException` is the following (`Build.java:194`):
```
final CodeSource codeSource = Build.class.getProtectionDomain().getCodeSource();
```
Apparently, per [this StackOverflow answer](https://stackoverflow.com/questions/27790348/getclass-getprotectiondomain-getcodesource-getlocation-getpath-throw-a), the method `getProtectionDomain()` "is not implemented in Android's version of Java." `Build.class.getProtectionDomain()` thus returns null, hence the `NullPointerException`.

This would indicate that any classes which use the `DeprecationLogger`, such as the critically important `SearchSourceBuilder`, will not function on Android. This is an issue with the Java REST Client.

**Steps to reproduce**:

 1. Add Elasticsearch Java REST Client 7.7.1 to an Android app
 2. Instantiate a SearchSourceBuilder object
 3. Run the app

**Comment by aissa-atif** [comment]
any solution for this probleme please ??? or other methode tu use elastic with android app ???

**Comment by pugnascotia** [comment]
See [this comment](https://github.com/elastic/elasticsearch/pull/58166#pullrequestreview-431671344) for the current status.

**Comment by rjernst** [comment]
As explained in the comment linked by Rory, we don't have any plans to fix this currently. The long term plan is to separate the java client so that it does not depend on the server jar, at which time we can evaluate adding tests for other client jvm scenarios like android. Given that, I hope you don't mind that I close this issue.
