### ISSUE TITLE
SQL: COUNT(DISTINCT(field)) returns with decimal instead of long

### ISSUE THREAD

**Issue by Willsun52000** [elastic/elasticsearch#58097]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.4.0

**Description of the problem including expected versus actual behavior**:
using count + distinct together, a decimal number is returned.

**Steps to reproduce**:
```
POST _sql?format=txt
{
  "query": "select event_type, count(*), count(distinct(stock_code))  from table_name group by event_type order by event_type"
}
event_type   |   count(*)    |count(distinct(stock_code))
-------------+---------------+---------------------------
test1        |289            |152.0
test2        |3              |1.0
test3        |2017           |1663.0
test4        |65             |2.0
test5        |7              |5.0
```

**Comment by matriv** [comment]
Indeed, this is issue exists in all branches up to current master.
Even though we return LONG as the type of the column, the `count(distinct <field_name>)` is extracted from the result of the HyperLogLog used under the hood for the distinct counts which is a Double.
