### ISSUE TITLE
Enhance move-to-step API to allow optionally dropping step name

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#58128]
Currently the `move-to-step` API for ILM looks like this:

```
POST /_ilm/move/foo
{
  "current_step": {
    "phase": "warm",
    "action": "shrink",
    "name": "check-allocation"
  },
  "next_step": {
    "phase": "cold",
    "action": "allocate",
    "name": "allocate"
  }
}
```

However, in order to use this API, we require a user to know the name of the step they are on and wish to go to. These steps are not documented because they are subject to change an more of an implementation detail rather than something that can be relied upon.

A nice enhancement for this would be if we could make the step name for `next_step` optional, where ILM would go to the *first* step of the action if the step name was not specified, such as:

```
POST /_ilm/move/foo
{
  "current_step": {
    "phase": "warm",
    "action": "shrink",
    "name": "check-allocation"
  },
  "next_step": {
    "phase": "cold",
    "action": "allocate"
  }
}
```

This would also help make the move-to-step API safer to use, as some of our actions contain validation in steps that occur at the beginning of the action (things like checking whether a shrink can be skipped for instance). We could ensure that users are more likely to run this validation when moving to a step directly.

**Comment by andreidan** [comment]
We discussed today, and this sounds like a good idea. (re)Starting an action from the first step will make sure the action proceeds only if all the prerequisites are in place. 
Leaving the `team-discuss` label on as @matt-davis-elastic will have more feedback related to this.

**Comment by andreidan** [comment]
We discussed this again and decided to move forward with the described proposal of allowing to optionally drop the "to" step name. Removing the `team-discuss` label.

**Comment by sebelga** [comment]
Could this be taken one step further and be able to move to the next phase without knowing/specifying the action?

```
POST /_ilm/move/foo
{
  "current_step": {
    "phase": "warm",
    "action": "shrink",
    "name": "check-allocation"
  },
  "next_step": {
    "phase": "cold"
  }
}
```

**Comment by dakrone** [comment]
@sebelga yes I think it'd be nice to be able to move to the beginning of a phase that way also.
