### ISSUE TITLE
Elasticsearch RestClient Error javax.net.ssl.SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by wmeg-aprico** [elastic/elasticsearch#58134]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.8

**Plugins installed**: []

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): Lentos

**Description of the problem including expected versus actual behavior**:
I'am configuring pls/ssl in a multi-node cluster. I generated certificate using the following command:

bin/elasticsearch-certutil cert --ca elastic-stack-ca.p12 --name filename-cert --in cluster.yml
and then, I generated a CA certificate as follows:

openssl pkcs12 -in filename-cert.p12 -cacerts -nokeys -chain > client-ca.cer

I set xpack.security.transport.ssl.verification_mode: full in elasticsearch side
I set elasticsearch.ssl.verificationMode: full in Kibana side.

Both Kibana and Elasticsearch are working as expected. However, my java client does not work and fails with the following exception: Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'xxx-xxx-xxx-xx' does not match the certificate subject provided by the peer (CN=xxx-node-1)

In my code, I enabled hostname verification as follows: 

cb.setHttpClientConfigCallback(http -> {
                    http.disableAuthCaching();
                    http.setSSLHostnameVerifier((s, session) -> true);
                    http.setSSLContext(ssl);
                    return http.setDefaultCredentialsProvider(cp);
                });

Could you please provide me with more details on haw to fix the issue.

Thank you in advance.
Best Regards.
Wael

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wmeg-aprico** [comment]
@jkakavas  Thank you for your feedback
