### ISSUE TITLE
Ingest Node Pipeline Fail Open vs Fail Closed

### ISSUE THREAD

**Issue by cataclysdom** [elastic/elasticsearch#58147]
Ingest node pipelines (not just processors) should have the ability to fail open in the event of a pipeline failure and index the document anyways.  Currently, any failure or exception without ignore clauses in the pipeline results in a failure to index the document, and an error status code returned to the sender.  There should be an option to allow for pipeline failures, quit on the first failure that doesn't have explicit failure actions, and index the document as is.

There are some merits to failing closed with pipelines, but overall there's a general expectation that Ingest nodes will operate like Logstash; failures are tagged and sent through.  Blocking data streams on pipeline failure has the possibility of bringing down entire pipelines.  This is exacerbated by pipeline-to-pipeline communication, which can block on all data streams.

**Comment by jbaiera** [comment]
@cataclysdom We have the ability to specify what should happen in a pipeline/processor should there be a failure with [the `on_failure` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/handling-failure-in-pipelines.html). Would this solve the issue, or are you encountering a problem with pipelines that this would not solve?

**Comment by cataclysdom** [comment]
The `on_failure` setting solves some immediate issues, but I don’t believe it solves the real issue at hand.  A single processor failure should not fail the entire pipeline, it should behave like Logstash - failures are tagged accordingly and sent to the destination.

I can only speak for my environment, but most processors need other `if` conditionals -as well as `on_failure` clauses- to determine processor execution.  This adds a lot of additional complexity to already complex pipelines.  

I think the best option is to have a meta-setting that impacts the behavior of failures on ingest pipelines.  Assuming you have a simple pipeline that looks similar to:
```
record -> grok (syslog) ->  grok (application) -> kv -> date -> index
```

Our outcomes should boil down to: 

1. **Implicit pipeline failure (current, default)**.  If any processor in a pipelines fails and has no explicit on_failure response, return a status code 400 to signal a failure to index.  Assume in the example above that grok (application) has failed to process, there is still value in extracting the syslog headers from the message, but would never be seen since the record is rejected.  Consequently, leveraging the `ignore_failiure` directive would mean we now need to introduce complex conditional checks at grok (application), kv, and date processors to ensure we don’t waste resources or improperly extract values (namely kv).
2. **Implicit pipeline success**.  If any processor in a pipeline fails and has no explicit on_failure response, terminate the pipeline with the current record context and return a status code 200 to signal successful indexing.  Assume in the example above that grok (application) has failed to process, however our message gets indexed and we can still extract information from the syslog header.  We protect the remainder of the pipeline from erroneous processor execution (again, kv) by stopping at the failure but still have more key/value pairs than the initial unstructured message. 3. **Explicit pipeline tagging (logstash, default)**.  If any processor in a pipeline fails, tag the resource with the appropriate tag and continue onto the next processor.  Assume in the example above that grok (application) has failed, the processor would tag the record with `_grokparsefailure` and then continue onto the next processor. These tags can be used further down the pipeline to control processor execution.
4. **Explicit pipeline on_failure**.  If any processor in a pipeline fails, perform a predefined `on_failure` condition and continue onto the next processor.  Assume in the example above that grok (application) has failed to process, the processor would perform whatever action is defined and then continue onto the next processor.  This would set a default for the `on_failure` condition.

**Comment by jbaiera** [comment]
I'm still confused how you wouldn't be able to do any of these things with the current implementation. It may complicate the pipeline definition slightly, but I don't see how these outcomes couldn't be satisfied:

Our outcomes should boil down to:

1. **Implicit pipeline failure (current, default)**.  This is the current state of things, though we seem to return a 500 error for unexpected failures.
2. **Implicit pipeline success**.  This is doable with an `on_failure` handler on the pipeline itself. The failure handler will execute and the document will be inserted regardless.
3. **Explicit pipeline tagging (logstash, default)**.  This may take some effort to do presently, but this can still be achieved by placing an on failure handler on each processor. It can be as simple as adding an error flag to the document, or appending an error code to an error code list on the doc. Checking the error code list to make sure the dependent processors haven't failed is doable. Complicated, yes, but every pipeline is different.
4. **Explicit pipeline on_failure**.  While I agree that this would be an interesting feature to save some keystrokes, I'm afraid that this might just add clutter to the API. A pipeline definition isn't going to change very often, and when it does, I would assume that for most users it is persisted in a location where edits and revisions can be maintained. It's probably better to simply repeat the "default" failure handler. In cases where processors don't want to use the predefined failure handler, they can override it, but in the cases where there shouldn't be one, then you'll have to either introduce ignore failure handler logic into every processor definition or manually copy each failure handler anyway. The benefits just don't seem to make it worth it here.

I'm happy to discuss further if my take on the situation is misguided. We obviously would rather our API's be easier to use for people, but we also try to be judicious to avoid API clutter and complexity.

**Comment by cataclysdom** [comment]
You’re right, you can do any of those things with the current implementation but with added complexity and additional maintenance.  This feature request seeks to enhance pipeline management or change the default ingest node failure response.

Elasticsearch’s default indexing behavior with unknown data is to automatically create an index and dynamically create fields.  Logstash’s default failure behavior is to add a tag and continue like normal.  It seems like ingest pipelines should follow suit.  The expected behavior is that a document will make it through and index _something_, indiscriminate of the success or failure of a pipeline.

**Comment by jbaiera** [comment]
Adding team discuss label for now. It would be helpful to gauge the team's opinion on feature parity with Logstash, specifically the default error handling logic. My understanding of the the ingest features is that they are meant to be flexible enough to support multiple solutions on top of them. This flexibility comes with the cost of configuration.

If your suggestion here is that we should change the defaults, it would be a long process to making the "new default" the actual default logic for Ingest. There's a long roll out period for changes that large. Many users would need to migrate their existing workloads, which causes increased effort and user discomfort when upgrading. Until then, the "Logstash" way would need to be enabled on a pipeline via a configurations anyway, albeit with fewer settings.

If your suggestion is to make all of that configuration _easier_ by having a number of out of the box pipeline behaviors, that would be more likely to gain traction than changing default behavior, but it _does_ add more surface area to the API's and a decent amount of complexity to the ingest features.

**Comment by jbaiera** [comment]
After discussing with the team, we feel there is a distinct line we can draw between Logstash's default behavior and the current default behavior for the Ingest node. Ingest processors and pipelines are meant to be building blocks in your final ingestion solution. This requires them to be configurable, flexible, and somewhat un-opinionated. Logstash however is a fully fleshed out solution, where these sorts of bells and whistles being the default makes more sense. As it stands, since we are able to more or less emulate the Logstash approach with the correct pipeline configurations (albeit more in-depth than a Logstash config may be) we will not move forward with changing any defaults in the Ingest node.
