### ISSUE TITLE
Proximity boosting on array fields.

### ISSUE THREAD

**Issue by aksel** [elastic/elasticsearch#58161]
We are building a forum, in which we have posts and replies.

We want to sort posts by popularity. Whenever there is a reply to a post, it should boost that post's popularity in some manner. This could be extended with number of reactions, likes, etc., but as a starting point, it's a pretty simple popularity ranking system.

I was trying to use distance_feature as a boost, and added a field reply_timestamps to the post document. However, it seems that only the latest timestamp is acted upon by distance_feature.

Here's an example
<pre>
<b>Request</b>
{
  "query": {
    "bool": {
      "should": [
        {
          "distance_feature": {
            "field": "reply_timestamps", <b>// date[]</b>
            "pivot": "1d",
            "origin": "now"
          }
        }
      ]
    }
  },
  "explain": true
}

<b>A snippet from one of the resulting hits</b>
{
  ...
  "_source": {
    ...
    "reply_timestamps": [
      "2020-06-16T08:34:35.798Z", <b>// Has a distance score of 0.9566114</b>
      "2020-06-16T08:58:33.284Z", <b>// Has a distance score of 0.9720828</b>
      "2020-06-16T09:27:53.656Z"  <b>// Has a distance score of 0.9917248</b>
    ]
  },
  "_explanation": {
    "value": 0.9917248, <b>// Matches the distance score of the last reply timestamp</b>
    "description": "Distance score, computed as weight * pivotDistance / (pivotDistance + abs(value - origin)) from:",
    "details": [
      {
        "value": 1.0,
        "description": "weight",
        "details": []
      },
      {
        "value": 86400000,
        "description": "pivotDistance",
        "details": []
      },
      {
        "value": 1592300394602, <b>// Current time in ms</b>
        "description": "origin",
        "details": []
      },
      {
        "value": 1592299673656, <b>// "2020-06-16T09:27:53.656Z" as ms, the last timestamp in the array</b>
        "description": "current value",
        "details": []
      }
    ]
  }
}
</pre>

I would have expected all three timestamps to affect the score, resulting in the score being ≈2.92.

If this is already a an inherent feature, to have all items in an array affect the score, please let me know. I am relatively new to this :sweat_smile: 

Thanks!

**Comment by mayya-sharipova** [comment]
Thanks for submitting a feature request.

> it seems that only the latest timestamp is acted upon by distance_feature

If a document has multiple values for a field, `distance_feature` query  from multiple values chooses a value that is closest to the `origin` (that produces the highest score).  And there is no way for other values to effect the score. 

I see how it could be helpful to specify a custom `multi_values_mode`.  But I don't think it will work with `distance_feature` query as it uses internal optimizations to efficiently skip documents that will not produce competitive scores.  I think it would very difficult to reason about what documents can be skipped if we need a sum of scores from multi-values.


As an alternative I can suggest:
- Use decay functions of function_score query with [multi_values_mode](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_multi_values_fields).  This query is slower than `distance_feature` query as it needs to go through all matched documents. Also, there is a plan to deprecate it from 8.0.
- See if [rank_feature](https://www.elastic.co/guide/en/elasticsearch/reference/master/rank-feature.html) or [rank_features](https://www.elastic.co/guide/en/elasticsearch/reference/master/rank-features.html) could be helpful for your use case.

**Comment by aksel** [comment]
Cool, thanks for the suggestions!

Your example is very helpful.
