### ISSUE TITLE
Field mapping API unexpectedly returns 404 response

### ISSUE THREAD

**Issue by tylersmalley** [elastic/elasticsearch#58188]
**Elasticsearch version**: master/8.0

**Description of the problem including expected versus actual behavior**: Field mapping API returns an empty response when the mapping contains a property not indexed and requested with `include_defaults=true`

**Steps to reproduce**:

Building upon the example provided in the [field mapping API docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-get-field-mapping.html#get-field-mapping-api-request).

 1. Create an index containing a property with `index: false`

```
curl -X PUT "localhost:9200/publications?pretty" -H 'Content-Type: application/json' -d'
{
    "mappings": {
        "properties": {
            "id": { "type": "text" },
            "title":  { "type": "text"},
            "abstract": { "type": "text", "index": false },
            "author": {
                "properties": {
                    "id": { "type": "text" },
                    "name": { "type": "text" }
                }
            }
        }
    }
}
'
```

 2. Request all fields with `include_defaults=true`

```
curl -X GET "localhost:9200/_mapping/field/*?index=publications&allow_no_indices=false&include_defaults=true"
```

 3. Observe 404 response
```
curl -i -X GET "localhost:9200/_mapping/field/*?index=publications&allow_no_indices=false&include_defaults=true"
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 2

{}%
```

**Comment by tylersmalley** [comment]
This failure was caught by our [nightly checks](https://www.elastic.co/guide/en/kibana/master/development-es-snapshots.html) against Elasticsearch, so we will need to resolve this or understand how to move forward in order to unblock that process. Thanks!

**Comment by jtibshirani** [comment]
This could be due to the `MappedFieldType` refactor (#57666), since there were changes to the `include_defaults` behavior. Tagging @romseygeek so he could take a look.
