### ISSUE TITLE
Add context values to aliases

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#5819]
We use aliases with filtering and routing to give us lightweight pseudo index-per-user.

Perhaps we should also accept "context" values in aliases, to do the same thing for the context suggester?

**Comment by dakrone** [comment]
@areek can you comment on this? Is it still applicable with the new suggester stuff you're working on?

**Comment by areek** [comment]
The new Completion Field will support filters, so this is not applicable atm.
