### ISSUE TITLE
Conflict using G1GC

### ISSUE THREAD

**Issue by rotastrain** [elastic/elasticsearch#5823]
I wanted to try the G1GC collector. 
However when i start the server it gives me an error
bin/elasticsearch -XX:+UseG1GC
Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I can't understand what may be the issue. This is a fresh download of 1.1.0. Also tried on earlier versions, same problem. Do i have to set something special?

Thanks

**Comment by jasontedor** [comment]
There's nothing to do here at this time as we still do not advise using G1GC.

**Comment by milnerm** [comment]
This this been resolved? or is there any news on use of G1GC?
