### ISSUE TITLE
Test upgrade scenarios with New Indexing Strategy for Data Streams

### ISSUE THREAD

**Issue by ruflin** [elastic/elasticsearch#58251]
In a recent conversations around data streams the upgrade scenarios we use for the new indexing strategy were brought up and that it is important that these are potentially also tested on the ES so they will get broken. This issue is to document the different scenarios.

In the following scenarios it is always assumed, that on upgrade, the following additional assets are installed / overwritten in the following order:

* New ingest pipeline is loaded
* Template is overwritten
* Check if mapping can be updated

## 1) Compatible mapping upgrade

The old and new mapping are compatible. The old template contains `foo.bar: keyword`, the new mapping `foo.bar: keyword, foo.hello_world: keyword`. Steps

* Load template
* Ingest data into data stream with `foo.bar`
* Update template
* Update mapping of current write index
* Send data with `foo.bar` and `foo.hello_world`
* Make sure `foo.hello_world` is type keyword

## 2) Conflicting mapping upgrade

The old and new mapping are not compatible. The old template contains `foo: keyword`, the new mapping `foo.bar: keyword`. Steps

* Load template and empty ingest pipeline "old"
* Ingest data into data stream with `foo`
* Load ingest pipeline which checks for `foo` field and renames it to `foo.bar`
* Update template
* Try to update mapping of current write index -> error
* Trigger rollover of write index
* Send data with `foo` 
* Send data with `foo.bar` 
* Make sure `foo.bar` is type keyword and newest index contains 2 events

**Comment by ruflin** [comment]
@leehinman Hope this is what you were looking for, happy to provide more details if needed.
@neptunian FYI

**Comment by leehinman** [comment]
@dakrone I think this was meant for you, although I'm interested too :-)
