### ISSUE TITLE
TokenBackwardsCompatibilityIT#testInvalidatingTokensInOldCluster failed on composable index templates

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#58258]
**Build scan**:
[scan](https://gradle-enterprise.elastic.co/s/n6oip5lebon4u/tests/:x-pack:qa:rolling-upgrade:v7.8.0%23oldClusterTest/org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT/testInvalidatingTokensInOldCluster#1)

**Repro line**:
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.8.0#oldClusterTest' --tests "org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testInvalidatingTokensInOldCluster" -Dtests.seed=A8B9BE81ACA2C978 -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Asia/Makassar -Druntime.java=8
```

**Reproduces locally?**:
Not initially. Might if run in a loop though. :shrug: 

**Applicable branches**: 7.x

**Failure history**:
First sited [June 1st](https://build-stats.elastic.co/goto/837c6f4839e6198e094ce6c85db7172e)

**Failure excerpt**:
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:42075], URI [token_backwards_compatibility_it/_doc/old_cluster_token5], status line [HTTP/1.1 201 Created] 
```

**Comment by dakrone** [comment]
Fixed in #59242
