### ISSUE TITLE
SQL: extend timestamp literal format to ISO

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#58262]
Currently, providing a timestamp literal conforming to the [ODBC escape sequence spec](docs.microsoft.com/en-us/sql/odbc/reference/appendixes/date-time-and-timestamp-escape-sequences) works as expected: `SELECT {ts '2000-01-01 11:11:11'}`.
Note that the spec requires an empty space between date and time components (and other databases supporting this type of literal, like SQL Server will reject non-space values).

The format with a binding `T` is also supported `{ts '2000-01-01T11:11:11'}`, hinting that an ISO format would be fine. However, providing a timezone delta, like `{ts '2000-01-01T11:11:11Z'}` will fail with `"line 1:9: Invalid timestamp received; Text '2000-01-01T11:11:11Z' could not be parsed, unparsed text found at index 19"`.

I believe we should be able to parse an ISO timestamp literal.

(As a side note, casting a string as a `timestamp` is currently quite flexible, all combination are supported: `SELECT CAST('2000-01-01T11:11:11Z' AS timestamp)`, `2000-01-01 11:11:11` (also expected), and `2000-01-01T11:11:11` or even `'2000-01-01 11:11:11Z`.)

**Comment by matriv** [comment]
@bpintea I believe it's because we expect at least 3 millis there so the `.000` part is missing before the timezone, can you please validate that?

**Comment by bpintea** [comment]
`SELECT {ts '2000-11-11T11:11:11.000Z'}` generates a `"line 2:11: Invalid timestamp received; Text '2000-11-11T11:11:11.000Z' could not be parsed, unparsed text found at index 23"`, but it works again if the `Z` is left out.
In any case, it'b great to have the full ISO flexibility (i.e. with or w/o millis).

**Comment by matriv** [comment]
`master` : 0af1f2fef805324e802d97d2fd9b4660abb403f0
`7.x` : e7c40d973e54fc5c378767661e8f2935548f11fc
