### ISSUE TITLE
Elasticsearch version mismatch watch is broken

### ISSUE THREAD

**Issue by chrisronline** [elastic/elasticsearch#58261]
[The query filter](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/resources/monitoring/watches/elasticsearch_version_mismatch.json#L39) is looking at the `_id` field when it should be looking at the `cluster_uuid` field.

**Comment by danhermann** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/58321
