### ISSUE TITLE
Painless Array Equality Checking

### ISSUE THREAD

**Issue by cataclysdom** [elastic/elasticsearch#58276]
Is there any way to improve loops over arrays in painless?  The current method seems more difficult than anticipated.  Logstash simplifies this with `if "foo" in [tags] { .. }`, but it's much more involved with a similar equality check in painless.

Here's an example:

```java
Collection tags = ctx.tags;
if(tags!= null){
  for (String tag : tags) {
    if (tag.contains('foo')) {
      return true
    }
  }
}
return false
```

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the Elasticsearch forum. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forum that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
