### ISSUE TITLE
Bump 5.6 branch to version 5.6.17 

### ISSUE THREAD

**Issue by luizavladislavna** [elastic/elasticsearch#58297]
Hi!

According to your latest PR for version 5.6: https://github.com/elastic/elasticsearch/commit/59bb0dc17971b8e8d1376fc28f26aaf28acc164e

Could you please provide official link for artifact with version 5.6.17?
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.17.tar.gz - return 404

Or, m.b. you know where I can find docker image with ES version 5.6.17 ?

**Comment by jasontedor** [comment]
We never released 5.6.17, 5.6.16 was and will be the final release in the 5.x series.

**Comment by luizavladislavna** [comment]
Thank you, @jasontedor!

Just in case, if someone need elasticsearch with version 5.6.17: 
- https://gist.github.com/luizavladislavna/a65a7514cab13e2408046c985c8599f3
