### ISSUE TITLE
Elasticsearch OSS Docker images not available on Docker Hub

### ISSUE THREAD

**Issue by slovdahl** [elastic/elasticsearch#58303]
**Elasticsearch version** (`bin/elasticsearch --version`): all

**Description of the problem including expected versus actual behavior**:

It looks like the `elasticsearch-oss` Docker images aren't available from Docker Hub (https://hub.docker.com/_/elasticsearch). Is there any specific reason for this? The problem we're having at the moment is that we are unable to cache the `elasticsearch-oss` image locally, because we need to use `docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1` as the reference to get it, and such references can't be fetched transparently from a local Docker registry pull-through cache. Images available on Docker Hub can be transparently cached in a local proxy without having to change the references to the image (see https://docs.docker.com/registry/recipes/mirror/ for how to do it).

It's of course possible to work around this by building our own versions of the `elasticsearch-oss` image, but it'd be one less moving part if the OSS variant would be available from Docker Hub as well.

For the record, I wrote about this on [discuss.elastic.co](https://discuss.elastic.co/t/elasticsearch-oss-docker-images-not-available-on-docker-hub/236172) 10 days ago, but I haven't received any responses at all.

**Comment by mark-vieira** [comment]
Closing this given we are no longer going to publish OSS artifacts beginning with 7.11.
