### ISSUE TITLE
DedicatedClusterSnapshotRestoreIT testAbortWaitsOnDataNode failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#58314]
This failed a PR build based on a branch containing the commit 1d3032faa90d60173593817eb167e1d330e65a3b from #58214

**Build scan**:
https://gradle-enterprise.elastic.co/s/3cl2mxi6ccqlo/tests/:server:internalClusterTest/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT/testAbortWaitsOnDataNode#1

**Repro line**:
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testAbortWaitsOnDataNode" -Dtests.seed=987BA7A5E63ADABA -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Europe/Riga -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
Master

**Failure history**:

**Failure excerpt**:

java.util.concurrent.TimeoutException: Timeout waiting for task. 

at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:236) at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:65) 
at org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testAbortWaitsOnDataNode(DedicatedClusterSnapshotRestoreIT.java:1474)

**Comment by original-brownbear** [comment]
This was fixed in https://github.com/elastic/elasticsearch/pull/58238 already and looking at the line number of the failure the branch did not contain the fix => closing :)
