### ISSUE TITLE
Randomize the order of the fields in XContent

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#5831]
Due to the way we parse `XContent` in query parsers and friends it's easy to make those order dependent. We just recently had an issue related to this #/5783 - We can maybe randomize the order by injecting a randomized XContentGenerator. if we parse XContent the order of the fields should not matter.

**Comment by cbuescher** [comment]
Random shuffling of xContent is now added in the basic roundtrip parsing tests (`testFromXContent()`) for queries, shapes, ingest metadata, aggregations, pipeline aggs, highlight builder, sort builders, rescore builders and suggestions. 
It might be useful in other cases where xContent is generated and then parsed, I'll scan the tests for possible spots but will close this issue if nothing particular comes to mind.

**Comment by cbuescher** [comment]
I have also added random shuffling for InnerHitBuilderTest and some other smaller ones (#18093), closing this now. Please reopen if you think there is other places that need this.
