### ISSUE TITLE
Allow unittests to run against an external cluster

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#5832]
Today we run our unittests against an internal cluster but we already have support for `ImmutableCluster` that is used by tests that done't need to modify the cluster. Yet, those tests can easily run against an external cluster. as a first simple step we can just use some Junit magic to make this work ie. we add support for an annotation like `@NeedsJVMLocalCluster` or `@NeedsMutableCluster` and given the cluster we use to run the tests we can just exclude those tests. 
A pure external cluster can then run on all tests that don't have either of these annotations. In a second step we can add a `MutableExternalCluster` impl that can start external processes and tear them down as needed given the test is not annotated with `@NeedsJVMLocalCluster`

**Comment by clintongormley** [comment]
@s1monw you still want to do this?

**Comment by rjernst** [comment]
This already works? You can pass -Dtests.cluster=x.x.x.x (this is how REST tests are run for release). It works for any integration tests (ie tests that require a cluster).

**Comment by clintongormley** [comment]
great, thanks @rjernst.  Closing
