### ISSUE TITLE
EQL: Remove `implicit_join_key_field` and `search_after` params from EQL search REST API

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#58333]
Both `implicit_join_key_field` and `search_after` are accepted as valid request body parameters for the EQL search REST API. However, these params don't actually do anything.

As `search_after` has a corresponding parameter in the 'regular' search API, it may be better to remove support for these parameters or otherwise surface an error before release. Otherwise, a user could use the `search_after` param and assume it worked when it did not.

This is less of a concern for the `implicit_join_key_field` param but still possible.

**Comment by costin** [comment]
Closed by #59232 and #59280
