### ISSUE TITLE
Remove 'minimumRuntime' source set from buildSrc

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#58351]
We currently separate out some core classes in `buildSrc` into the `minimumRuntime` source set. This source set is compiled with a target bytecode version of Java 8 for compatibility with builds unable to migration forward to Java 11, primarily `elasticsearch-hadoop`. They have since been able to bump their Gradle and JDK versions so we can get rid of this complexity and fold this code back into the `main` sourceset and use the same compiler version as everything else.

**Comment by mark-vieira** [comment]
@breskeby do you mind taking a look at this when you find some time?

**Comment by breskeby** [comment]
👍 will do
