### ISSUE TITLE
linked indices 0 although many indices are linked (regression 7.7.1)

### ISSUE THREAD

**Issue by chrismaes87** [elastic/elasticsearch#58374]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.1

**using cloud.elastic.co**
-

**Description of the problem including expected versus actual behavior**:
after upgrading our cloud.elastic.co instance from 7.6.2 to 7.7.1, the **linked indices** kpi show 0 linked indices although there are many linked indices.
![image](https://user-images.githubusercontent.com/6972561/85113239-4469d580-b217-11ea-98b3-25355f6bdc2f.png)

The ILM policy is correctly linked to index templates:
![image](https://user-images.githubusercontent.com/6972561/85113220-3b790400-b217-11ea-92fa-07db51161d55.png)

there are multiple indices linked to this template:
![image](https://user-images.githubusercontent.com/6972561/85113293-53e91e80-b217-11ea-92da-b3c159ac2053.png)

**Steps to reproduce**:

make sure to have:
 1. an index template
 2. a lifecycle policy linked to that index policy
 3. make sure indices are created using that index template

**Comment by ddolcimascolo** [comment]
Hello,

I'm on 7.7.0 and I just noticed this as well...

David

**Comment by alisonelizabeth** [comment]
I'm going to close this issue as it should be fixed in `7.7.2` via https://github.com/elastic/kibana/issues/68804.
