### ISSUE TITLE
Expose type parameter in Simple Query String

### ISSUE THREAD

**Issue by robmartin-scibite** [elastic/elasticsearch#58375]
`query_string`  and `multi_match` queries support a `type` parameter which determines how the query matches and scores documents over multiple fields. `simple_query_string` does not expose this property and seems to default to `most_fields`. `simple_query_string`  is perfect for our use case, but we cannot use it as we require  `best_fields` behaviour. Would it be possible to expose this parameter on `simple_query_string` as well?

**Comment by javanna** [comment]
We discussed this today with the team: `most_field` is currently the hardcoded type we use, it would make sense to make that configurable but we this is the only time where we saw this requested, hence it is not high priority. We would welcome a community contribution to address it.

**Comment by Kiriakos1998** [comment]
Hello @javanna can I  pick this up?

**Comment by javanna** [comment]
please go ahead @Kiriakos1998
