### ISSUE TITLE
ElasticSearch bulk data push using nodejs takes long time...

### ISSUE THREAD

**Issue by lmk07** [elastic/elasticsearch#58378]
Hi every one,
i'm pushing some bulk amount of data reading from s3 bucket. using streaming. data size will be around 2.5GB containing approx 70lakhs data. for every push i'm passing 10000 data, its taking around 1hr. i want to reduce the time.My sample code :

var Data = [];
Stream.on('data', (data) => {
Data.push({
                  index: {
                              _index: ,
                              _type: "_doc",
                              _id:
                   }
       }, data);
});

if Data length is 10K i will initiate data push function. after that i will again stream.

eSclient.bulk({ body: Data});

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the Elasticsearch forum. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forum that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
