### ISSUE TITLE
 Rollup job makes a date field max aggregation type to be float instead of date

### ISSUE THREAD

**Issue by simbarashe** [elastic/elasticsearch#58370]
Elasticsearch version (`bin/elasticsearch --version`): 7.6.0

OS version (`uname -a` if on a Unix-like system): linux Redhat 7

Description of the problem including expected versus actual behavior: 
Roll-up jobs make the mappings of a date field max aggregation data type to be float instead of date type. The resulting value should be a date type usable in Grafana.

Steps to reproduce:

 1. Create a rollup job using Kibana, the following will be generated:
PUT _rollup/job/rollup_job_orc_wmbstats_uat_limited
{
  "id": "rollup_job_orc_wmbstats_uat_limited",
  "index_pattern": "orc_wmbstats_uat_*",
  "rollup_index": "rollup_orc_wmbstats_uat_limited",
  "cron": "0 0 1 * * ?",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "interval": "60m",
      "delay": "1d",
      "time_zone": "Africa/Johannesburg",
      "field": "messageFlow.gmtEndTime"
    },
    "terms": {
      "fields": [
        "messageFlow.applicationName.keyword",
        "messageFlow.brokerLabel.keyword",
        "messageFlow.executionGroupName.keyword",
        "messageFlow.accountingOrigin.keyword",
        "recordCode.keyword",
        "recordType.keyword",
        "messageFlow.messageFlowName.keyword"
      ]
    },
    "histogram": {
      "interval": 1000,
      "fields": [
        "messageFlow.totalInputMessages",
        "messageFlow.totalNumberOfBackouts",
        "messageFlow.totalNumberOfCommits",
        "messageFlow.totalNumberOfErrorsProcessingMessages",
        "messageFlow.totalNumberOfMessagesWithErrors",
        "messageFlow.totalNumberOfMQErrors"
      ]
    }
  },
  "metrics": [
    {
      "field": "messageFlow.totalInputMessages",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.totalNumberOfBackouts",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.totalNumberOfCommits",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.totalNumberOfErrorsProcessingMessages",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.totalNumberOfMessagesWithErrors",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.totalNumberOfMQErrors",
      "metrics": [
        "sum"
      ]
    },
    {
      "field": "messageFlow.gmtEndTime",
      "metrics": [
        "max"
      ]
    }
  ]
}
 2. Query the mappings through the Kibana console, the following will be returned:
{
  "rollup_orc_wmbstats_uat_limited" : {
    "mappings" : {
      "_meta" : {
        "_rollup" : {
          "rollup_job_orc_wmbstats_uat_limited" : {
            "cron" : "0 0 1 * * ?",
            "rollup_index" : "rollup_orc_wmbstats_uat_limited",
            "groups" : {
              "histogram" : {
                "interval" : 1000,
                "fields" : [
                  "messageFlow.totalInputMessages",
                  "messageFlow.totalNumberOfBackouts",
                  "messageFlow.totalNumberOfCommits",
                  "messageFlow.totalNumberOfErrorsProcessingMessages",
                  "messageFlow.totalNumberOfMessagesWithErrors",
                  "messageFlow.totalNumberOfMQErrors"
                ]
              },
              "date_histogram" : {
                "fixed_interval" : "60m",
                "delay" : "1d",
                "field" : "messageFlow.gmtEndTime",
                "time_zone" : "Africa/Johannesburg"
              },
              "terms" : {
                "fields" : [
                  "messageFlow.applicationName.keyword",
                  "messageFlow.brokerLabel.keyword",
                  "messageFlow.executionGroupName.keyword",
                  "messageFlow.accountingOrigin.keyword",
                  "recordCode.keyword",
                  "recordType.keyword",
                  "messageFlow.messageFlowName.keyword"
                ]
              }
            },
            "id" : "rollup_job_orc_wmbstats_uat_limited",
            "metrics" : [
              {
                "field" : "messageFlow.totalInputMessages",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.totalNumberOfBackouts",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.totalNumberOfCommits",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.totalNumberOfErrorsProcessingMessages",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.totalNumberOfMessagesWithErrors",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.totalNumberOfMQErrors",
                "metrics" : [
                  "sum"
                ]
              },
              {
                "field" : "messageFlow.gmtEndTime",
                "metrics" : [
                  "max"
                ]
              }
            ],
            "index_pattern" : "orc_wmbstats_uat_*",
            "timeout" : "20s",
            "page_size" : 1000
          }
        },
        "rollup-version" : "7.6.0"
      },
      "dynamic_templates" : [
        {
          "strings" : {
            "match_mapping_type" : "string",
            "mapping" : {
              "type" : "keyword"
            }
          }
        },
        {
          "date_histograms" : {
            "path_match" : "*.date_histogram.timestamp",
            "mapping" : {
              "type" : "date"
            }
          }
        }
      ],
      "properties" : {
        "_rollup" : {
          "properties" : {
            "id" : {
              "type" : "keyword"
            },
            "version" : {
              "type" : "long"
            }
          }
        },
        "messageFlow" : {
          "properties" : {
            "accountingOrigin" : {
              "properties" : {
                "keyword" : {
                  "properties" : {
                    "terms" : {
                      "properties" : {
                        "_count" : {
                          "type" : "long"
                        },
                        "value" : {
                          "type" : "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "applicationName" : {
              "properties" : {
                "keyword" : {
                  "properties" : {
                    "terms" : {
                      "properties" : {
                        "_count" : {
                          "type" : "long"
                        },
                        "value" : {
                          "type" : "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "brokerLabel" : {
              "properties" : {
                "keyword" : {
                  "properties" : {
                    "terms" : {
                      "properties" : {
                        "_count" : {
                          "type" : "long"
                        },
                        "value" : {
                          "type" : "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "executionGroupName" : {
              "properties" : {
                "keyword" : {
                  "properties" : {
                    "terms" : {
                      "properties" : {
                        "_count" : {
                          "type" : "long"
                        },
                        "value" : {
                          "type" : "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "gmtEndTime" : {
              "properties" : {
                "date_histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "keyword"
                    },
                    "time_zone" : {
                      "type" : "keyword"
                    },
                    "timestamp" : {
                      "type" : "date"
                    }
                  }
                },
                "max" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "messageFlowName" : {
              "properties" : {
                "keyword" : {
                  "properties" : {
                    "terms" : {
                      "properties" : {
                        "_count" : {
                          "type" : "long"
                        },
                        "value" : {
                          "type" : "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "totalInputMessages" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "totalNumberOfBackouts" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "totalNumberOfCommits" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "totalNumberOfErrorsProcessingMessages" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "totalNumberOfMQErrors" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            },
            "totalNumberOfMessagesWithErrors" : {
              "properties" : {
                "histogram" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "interval" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "float"
                    }
                  }
                },
                "sum" : {
                  "properties" : {
                    "value" : {
                      "type" : "float"
                    }
                  }
                }
              }
            }
          }
        },
        "recordCode" : {
          "properties" : {
            "keyword" : {
              "properties" : {
                "terms" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "keyword"
                    }
                  }
                }
              }
            }
          }
        },
        "recordType" : {
          "properties" : {
            "keyword" : {
              "properties" : {
                "terms" : {
                  "properties" : {
                    "_count" : {
                      "type" : "long"
                    },
                    "value" : {
                      "type" : "keyword"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

 3. Attached is the view of the date field max aggregation mappings. How can these mappings be created manually or to update the data types of the aggregations?

![Max-aggregation-type](https://user-images.githubusercontent.com/5719446/85108301-c1914c80-b20f-11ea-9aeb-bfa1bf06ba29.JPG)

**Provide logs (if relevant)**:

**Comment by wchaparro** [comment]
With the 8.7 release of Elasticsearch, we have made a [new downsampling capability](https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling.html) associated with the new [time series datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) functionality generally available (GA). This capability was in tech preview in ILM since 8.5.  Downsampling provides a method to reduce the footprint of your time series data by storing it at reduced granularity. The downsampling process rolls up documents within a fixed time interval into a single summary document. Each summary document includes statistical representations of the original data: the min, max, sum, value_count, and average for each metric. Data stream time series dimensions are stored unchanged. 

Downsampling is superior to rollup because:

- Downsampled indices are searched through the _search API
- It is possible to query multiple downsampled indices together with raw data indices
- The pre-aggregation is based on the metrics and time series definitions in the index mapping so very little configuration is required (i.e. much easier to add new time serieses)
- Downsampling is managed as an action in ILM
- It is possible to downsample a downsampled index, and reduce granularity as the index ages
- The performance of the pre-aggregation process is superior in downsampling, as it builds on the time_series index mode infrastructure

Because of the introduction of this new capability, we are deprecating the rollups functionality, which never left the Tech Preview/Experimental status, in favor of downsampling and thus we are closing this issue. We encourage you to migrate your solution to downsampling and take advantage of the new TSDB functionality.
