### ISSUE TITLE
bulk request returned 200 OK but saved nothing

### ISSUE THREAD

**Issue by GopherJ** [elastic/elasticsearch#58398]
**Elasticsearch version** (`bin/elasticsearch --version`):
latest

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by GopherJ** [comment]
Bulk is failing silently for new created indexes.

**Comment by grgAditya** [comment]
Hi Would like to work on this, can you can you provide more info?

**Comment by GopherJ** [comment]
@grgAditya Hi I suspect it's the rust client `elastic/elasticsearch` which causes problem, shall I create an issue for them?

**Comment by iverase** [comment]
Hi @GopherJ,

In order to successfully triage this issue you would need to provide more information about the issue, for example an example of how to reproduce the issue and some information about your set up. Could you provide  such information?

**Comment by GopherJ** [comment]
Hi, @iverase finally I succeed to track  the error:

```
 faild to save: Elastic Error: `Error { kind: Http(reqwest::Error { kind: Status(400), url: "http://localhost:9200/alerts.bd1459f8d1b44aec8acedf059a1b53ed/_doc/7901124001906198514" }) }`
```

**Comment by GopherJ** [comment]
This is our mappings (simplified):

```
mappings: {
 "source": {
                "properties": {
                    "type": {
                        "type": "keyword"
                    },
                    "mac": {
                        "type": "keyword"
                    }
                }
            }
}
```

It works for data:

```
{"source": "type": "mobile"}
```
but when I tried to send bulk request with:

```
{ "source": {"type": "gateway", "mac": "abcdabcdabcd"}}
```

It saved nothing and returned 200 OK

Then I switched to index only one document, it gave me the above error

**Comment by russcam** [comment]
I'm closing this issue in favour of https://github.com/elastic/elasticsearch-rs/issues/112
