### ISSUE TITLE
post filter not applied to field collapsing inner hits?

### ISSUE THREAD

**Issue by mtfgqd** [elastic/elasticsearch#58397]
Please reference to below issue,
https://github.com/elastic/elasticsearch/issues/26649

Recently, I met the same requirement,but post filter not applied to field collapsing.
Can anybody tell me how to filter data set after field collapsing?
I use ES version 6.4.2,Many thanks

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
