### ISSUE TITLE
[ML] Should flush have a wait_for_completion option?

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#58395]
The [flush job](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-flush-job.html) endpoint has evolved over the years, and now fulfils several roles that are only tenuously related.

- When the endpoint was first introduced, it had no arguments and was all about ensuring that having sent data to a job you could query all the results generated from that data with the certainty that no results would be generated or changed after your results query was made.  In other words, it was aimed at programmatic users of the ML APIs. (The docs don't mention this aspect at all - they should be improved.)
- After a time the option was added to tell ML to generate interim results as part of a flush.  This made sense at the time, as the users who wanted the interim results were programmatic users who had just sent data to ML, so _also_ wanted the searchability guarantee.
- Then additional options were added to advance time or skip time.  It is not as clear that these fit well with the flush endpoint.  However, for a programmatic user who wants to tell ML there was no data for a bucket and then get results for that bucket having both requests combined is a convenience.
- Finally, datafeeds were added.  Datafeeds need to request interim results be calculated and sometimes need to skip or advance time in the model.  But datafeeds do _not_ immediately require results be completely up-to-date when the flush request returns.  Datafeeds would be happy with async interim results calculation and time skip/advance.

At small scale these discrepancies do not matter.  But at large scale they do.

- One aspect of making sure results reflect the impact of all previously sent data is waiting for any renormalization that is already in progress _or caused by advancing time_ to finish.
- When there are many millions of results renormalization can take a long time.
- Datafeeds _always_ ask for interim results to be calculated, so flush very regularly.  This means that datafeeds block for a considerable amount of time for large jobs where results renormalization takes a long time.
- Additionally, now that category definitions contain the category count, a datafeed requesting interim results for a job will cause every category definition where we have incremented the count in the C++ process to be updated in the results index, and will block until this is done.  If we saw 100 different message categories in the 7.5 or 10 minutes between requesting interim results then that means the datafeed will need to wait for 100 document updates in the results index.

Some possibilities for addressing this:

1. Split the functions of flush into separate endpoints.  For example, if you want to calculate interim results and make sure they are searchable then you'd call the interim results endpoint followed by the flush endpoint.  If you wanted to advance time but didn't immediately require results you'd just call the advance time endpoint, and not bother with the (potentially expensive) flush afterwards.
2. Add a `wait_for_completion` option to the current flush endpoint.  This would default to `true` to preserve existing behaviour.  But when set to `false` the flush endpoint would not block until all its effects were visible.

Option 1 might be better in a green field situation, but given that that would be a breaking change option 2 seems more sensible.

Then the datafeed would call flush with `wait_for_completion=false`.  The key benefit would be that subsequent iterations of the datafeed could run while renormalizations triggered by the previous flush chugged away in the background.  The datafeed would no longer pointlessly block waiting for renormalizations to complete.

**Comment by benwtrent** [comment]
@droberts195 

> Then the datafeed would call flush with wait_for_completion=false. The key benefit would be that subsequent iterations of the datafeed could run while renormalizations triggered by the previous flush chugged away in the background. The datafeed would no longer pointlessly block waiting for renormalizations to complete.

What if we made the flush in the datafeed job asynchronous? This way the datafeed job thread can continue and handle the flush response in a callback. 

We do need the latest finalized bucket in the datafeed to calculate the missing data. So, we could make flush asynchronous, protected with some mutexes and the datafeed should be able to continue executing.
