### ISSUE TITLE
[CI] RangeQueryBuilderTests.testToQuery failing due to invalid time zone

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#58431]
The following test fails because of invalid time zones in 7.x:

https://gradle-enterprise.elastic.co/s/kendslddzh4j6

It can be reproduced with:

```
./gradlew ':server:test' --tests "org.elasticsearch.index.query.RangeQueryBuilderTests.testToQuery" -Dtests.seed=EE8414A2AEE61B4C -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Timbuktu -Druntime.java=11 -Dtests.fips.enabled=true -Dtests.iters=100
```

Error:

```
java.lang.IllegalArgumentException: The datetime zone id 'SystemV/PST8PDT' is not recognised
```

This seems to be possible in all the test that uses `randomZone()` method and it seems to have been fix in some cases:

https://github.com/elastic/elasticsearch/pull/30175/files

Maybe we can fix it once for all cases we call that method.

**Comment by cbuescher** [comment]
> Maybe we can fix it once for all cases we call that method.

The conditions under which this can fail on 7.x are extremely rare, namely we need:
* an index versionCreated before V_7_0_0
* no "forced" date parser through a format parameter
* one of the SystemV* time zones that Jodas DateTimeZone parser doesn't know how to convert

In addition, this doesn't seem to be possible anymore on master. Given how unlikely this is I would opt for only excluding this case from RangeQueryBuilderTests. I generally think its good to sample from the "true" source of possible java.util.TimeZone ids. I'm opening a PR for this

**Comment by cbuescher** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/58449
