### ISSUE TITLE
[DOCS] ILM policy update – add phase effect on older indices

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#58445]
Add documentation that explains what happens to older indices when we add a new phase to the ILM policy. This documentation can be added to this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/update-lifecycle-policy.html)

Some background information:

In newer versions of Elasticsearch (including 7.7) the pick-ups to the policy will happen automatically, but only on new indices.
If older indices are in the completed/completed/completed step from a long time ago (prior to when we stopped going to the "completed" phase), then automatic pickup will not apply to them and they will have to be manually moved the new added phase. Newer indices that are not in the completed/completed/completed phase won't need this.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
