### ISSUE TITLE
[match_phrase_prefix] query does not support [zero_terms_query]

### ISSUE THREAD

**Issue by jklofs** [elastic/elasticsearch#58468]
According to the current documentation, match phrase prefix queries support the zero_terms_query parameter. However, if I attempt to set this parameter to "all" in a query, I get an error of type parsing_exception with reason "[match_phrase_prefix] query does not support [zero_terms_query]".

The cURL I'm using:

curl -X GET "localhost:9200/events/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_phrase_prefix" : {
            "name" : {
                "query" : "page",
                "analyzer" : "english",
                "zero_terms_query" : "all"
            }
        }
    }
}
'
but result

{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "[match_phrase_prefix] query does not support [zero_terms_query]",
                "line": 8,
                "col": 30
            }
        ],
        "type": "parsing_exception",
        "reason": "[match_phrase_prefix] query does not support [zero_terms_query]",
        "line": 8,
        "col": 30
    },
    "status": 400
}

version is 7.8.0

What am I doing wrong?

Thanks.

**Comment by cbuescher** [comment]
@jklofs thanks for raising this, indeed there seems to be a mismatch between the docs and the `match_phrase_prefix` implementation that doesn't currently support `zero_terms_query`. Given that e.g. `match` and `match_phrase` support this settings, I think we should add this to this query as well.

**Comment by homersimpsons** [comment]
[Elasticsearch 7.9.2](https://github.com/elastic/elasticsearch/releases/tag/v7.9.2) is released  since the 24th of september, this fix does nott seem to be part of it. Any idea on the release date (/version) of this fix ?

**Comment by cbuescher** [comment]
@homersimpsons this change has only been[ backported up to version 7.10](https://github.com/elastic/elasticsearch/pull/59784)
