### ISSUE TITLE
QL: remove constant_keyword from code base

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#58471]
Following https://github.com/elastic/elasticsearch/pull/58315 merging, there is no need for constant_keyword field type in QL projects anymore.

**Comment by keremh** [comment]
Hello @astefan, i want to work on this issue 👍

**Comment by astefan** [comment]
Hi @keremh , thank you for your interest in helping out with this gh issue. There is a [PR already opened](https://github.com/elastic/elasticsearch/pull/60524) for this which is waiting on bwc tests to be complete and further merged in `master` afterwards.

**Comment by bpintea** [comment]
Fixed by #60524.
