### ISSUE TITLE
Newly added ml data streams tests fail

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#58491]
The following tests are failing on master as well as 7.x:

RegressionIT » testWithDatastream
DatafeedJobsIT » testLookbackOnlyDataStream
ClassificationIT » testWithDatastreams

The error message is slightly different but I think the root cause is the same on both branches:

java.lang.AssertionError: no proxy found for action: org.elasticsearch.action.admin.indices.datastream.CreateDataStreamAction@516949c9

java.lang.IllegalStateException: failed to find action [org.elasticsearch.action.admin.indices.datastream.CreateDataStreamAction@516949c9] to execute

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testWithDatastream" -Dtests.seed=FBF282FF768F23EC -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ru -Dtests.timezone=Asia/Novosibirsk -Druntime.java=11
```

I suspect this has to do with the fact that data streams are developed under a feature flag, hence its actions are not available depending on how the ml tests are run?

https://gradle-enterprise.elastic.co/s/jnvbyo62q32gs
https://gradle-enterprise.elastic.co/s/2qdhni6hmvl6c

**Comment by javanna** [comment]
These tests were recently added as part of #58280 .  cc @benwtrent . I am going to mute them for now.

**Comment by benwtrent** [comment]
These tests should only run if the feature flag is turned on. 

I will see about adding a test assumption to conditionally skip based on that flag somehow.
