### ISSUE TITLE
[Snapshot & Restore] Issue with restoring a snapshot that contains a data stream

### ISSUE THREAD

**Issue by jloleysens** [elastic/elasticsearch#58496]
**Elasticsearch version** (`bin/elasticsearch --version`): Latest `elasticsearch-oss-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**JVM version** (`java -version`): 12.0.2

**OS version** (`uname -a` if on a Unix-like system): Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

When restoring snapshot that contains a data stream that existed on the cluster previously (in my case `test-data-stream1`), the data stream can not be deleted and responds with:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index [.ds-test-data-stream1-000001]",
        "index_uuid": "OYWmUQ64RhqdVSopJpd0kw",
        "index": ".ds-test-data-stream1-000001"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index [.ds-test-data-stream1-000001]",
    "index_uuid": "OYWmUQ64RhqdVSopJpd0kw",
    "index": ".ds-test-data-stream1-000001",
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "index uuid doesn't match expected: [OYWmUQ64RhqdVSopJpd0kw] but got: [IAbkfRhxRxGdcQ9R-MAffQ]"
    }
  },
  "status": 404
}
```

Additionally, when restoring the data stream, the option to rename the indices upon restore was not reconnecting the restored data streams with the original data stream.

I would expect the data stream to be restored in a manner that leaves it fully functional as it was when the snapshot was taken.

**Steps to reproduce**:

#### Step 1

Create a data stream.

Index Template:
```json
PUT /_index_template/test-data-stream
{
	"index_patterns": [
		"test-data-stream*"
	],
	"template": {
		"mappings": {
			"properties": {
				"@timestamp": {
					"type": "date"
				}
			}
		}
	},
	"data_stream": {
		"timestamp_field": "@timestamp"
	}
}
```

Data stream:
```
PUT /_data_stream/test-data-stream
```

#### Step 1

Create a repository and snapshot policy that will capture data streams and data stream indices into that repository in snapshots:

```
# Example
PUT _slm/policy/test
{
  "name": "<test-{now/d}>",
  "schedule": "0 30 1 * * ?",
  "repository": "test",
  "config": {
    "indices": [],
    "include_global_state": true
  }
}
```

#### Step 2

Attempt to restore the a snapshot created by the SLM policy adding option for global state (this seems to include the data stream? otherwise it is not restored?):

```json
{
  ...
  "include_global_state": true
  ...
}
```

You may need to first delete the data stream or use the index renaming option upon restore. I found that the renaming leads to a different bug where the restored indices are not linked back to the data stream that was restored.

#### Step 3

Attempt to delete the restored data stream:

```
DELETE /_data_stream/test-data-stream1
```

See the error reported above.

CC @martijnvg

**Comment by martijnvg** [comment]
I think upon restore, the Index instance in a data stream needs to be refreshed. If I remember correctly, the index uuid of an index changes when being restored.

**Comment by danhermann** [comment]
We plan to fix this by including only the name of the backing indices in the data stream rather than the name and UUID since the latter would change during a snapshot restore.
