### ISSUE TITLE
Former master reports "failed to reassign persistent tasks" repeatedly

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#58531]
Following a slightly messy master election I saw a 7.6.1 cluster with the two unelected master nodes both reporting this message every 30 seconds apparently indefinitely:

```
failed to reassign persistent tasks
org.elasticsearch.cluster.NotMasterException: no longer master. source: [reassign persistent tasks]
```

Possibly there's a race in the `PersistentTasksClusterService` around election time? Not sure, I am not very familiar with this area.

**Comment by droberts195** [comment]
This is a silly bug.  If a persistent task cannot be immediately reassigned and has caused periodic rechecks to be scheduled (on the master node at that time) then those rechecks continue to be rescheduled regardless of whether the node is still the master.  I will open a PR to fix it.
