### ISSUE TITLE
[DOCS] Update index template example in ILM automate rollover tutorial

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#58543]
The index alias section of the ILM automate rollover tutorial uses a legacy
index template:

https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-index-lifecycle-management.html#ilm-gs-alias-apply-policy

We should update this section to use a corresponding composable template.

**Comment by dakrone** [comment]
Relates to #56387
