### ISSUE TITLE
[SLM] Capturing global state in snapshot also captures data streams

### ISSUE THREAD

**Issue by jloleysens** [elastic/elasticsearch#58544]
**Elasticsearch version** (`bin/elasticsearch --version`): Snapshot of latest building artifact at time of issue creation `elasticsearch-oss-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**JVM version** (`java -version`): openjdk 12.0.2 2019-07-16

**OS version** (`uname -a` if on a Unix-like system): Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

When creating a snapshot policy users are given the option to include global state, by setting `include_global_state` to `true`. Creating a snapshot policy like:

```
PUT _slm/policy/test-k
{
  "name": "<test-k-{now/d}>",
  "schedule": "0 30 1 * * ?",
  "repository": "test",
  "config": {
    "indices": [
      ".k*"
    ],
    "include_global_state": true
  }
}
```

And running it yields a snapshot that also contains all the data streams metadata. Even though there are no data streams in the policy that match the patterns specified in `indices`.

Furthermore, when attempting to restore a snapshot created with the above policy the following error is reported:

```
[index_not_found_exception] no such index [.ds-test-data-stream-000001], with { index_uuid="_na_" & index=".ds-test-data-stream-000001" }
```

I would expect the policy snapshot to not include _any_ data about data streams (as it does not contain any of the backing indices either).

I would also expect the snapshot to be restore-able.

**Steps to reproduce**:

#### Create an index template

```
PUT /_index_template/test-data-stream
{
	"index_patterns": [
		"test-data-stream*"
	],
	"template": {
		"mappings": {
			"properties": {
				"@timestamp": {
					"type": "date"
				}
			}
		}
	},
	"data_stream": {
		"timestamp_field": "@timestamp"
	}
}
```

#### Create a data stream

```
PUT /_data_stream/test-data-stream
```

#### Then...

After the policy has created the snapshot, inspect the data concerning that snapshot, it should contain information about he data stream that was just created (which it should not).

#### Do the restore

I was using the Kibana UI to restore the snapshot and required that the global metadata be included in the snapshot

CC @martijnvg

**Comment by dakrone** [comment]
Worth noting for this that it's not SLM-specific, regular snapshots would exhibit this same behavior.
