### ISSUE TITLE
Testing documentation disappeared since Elasticsearch 7.6

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#58564]
Hi,

Until Elasticsearch 7.5, there is "testing" documentation available:
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/testing.html

But since Elasticsearch 7.6, the documentation section has disappeared:
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/testing.html

Is it a miss? If so, can you recover it?

**Comment by lcawl** [comment]
I'm transferring this issue to the elasticsearch repo since it pertains to this source file: https://github.com/elastic/elasticsearch/blob/7.5/docs/reference/testing.asciidoc

**Comment by jasontedor** [comment]
Relates #55257

**Comment by lockewritesdocs** [comment]
The latest page for the [Java testing framework](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/testing-framework.html) indicates:

> This page was deleted. Information about the Java testing framework was removed ([55257](https://github.com/elastic/elasticsearch/issues/55257)) from the Elasticsearch Guide because it was out of date and erroneously implied that it should be used by application developers.

Therefore, I'm marking this issue as closed.
