### ISSUE TITLE
IndicesQueryCache consuming the entire JVM Heap (7.4.2)

### ISSUE THREAD

**Issue by arunabh23** [elastic/elasticsearch#58577]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.2

**JVM version** (`java -version`): jdk-11

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**: The node query cache on two of the nodes for an 18 node cluster (15 data nodes, 3 master nodes) had 99% JVM heap_used_percent. Node query cache settings are not set explicitly so the default limit of 10% should have not been breached. 

Even /_cat/allocation was returning circuit_breaker_exception for the affected nodes. 
```
"root_cause" : [
      {
        "type" : "circuit_breaking_exception",
        "reason" : "[parent] Data too large, data for [<http_request>] would be [32344991800/30.1gb], which is larger than the limit of
 [31003960934/28.8gb], real usage: [32344991800/30.1gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=45646419/43.5mb, i
n_flight_requests=0/0b, accounting=128008962/122mb]",
        "bytes_wanted" : 32344991800,
        "bytes_limit" : 31003960934,
        "durability" : "PERMANENT"
      }
```

On the analysis of the heap dump it was found that the **org.elasticsearch.indices.IndicesQueryCache$ElasticsearchLRUQueryCache** consumed 29GB out of the total 30.1GB of memory. 
This looks like a problem with Boolean query which was reserving 1542660 * 16Kb instances of int[] and not causing it to get garbage collected due to caching it in the LRU cache.
Attaching screenshots of the heap dump analysis.

<img width="874" alt="BiggestObjectsOverview" src="https://user-images.githubusercontent.com/7038087/85794056-9e0c5b80-b753-11ea-9597-7c00e706076d.png">
<img width="696" alt="BiggestTop-LevelDominatorPackages" src="https://user-images.githubusercontent.com/7038087/85794068-a369a600-b753-11ea-96ec-2d296fc281f7.png">
<img width="1276" alt="int" src="https://user-images.githubusercontent.com/7038087/85794088-ab294a80-b753-11ea-932e-c39a905665d1.png">
<img width="1272" alt="booleanQuery" src="https://user-images.githubusercontent.com/7038087/85794917-07d93500-b755-11ea-8f00-5ec1ed224b53.png">

**Comment by jimczi** [comment]
Thanks for reporting @arunabh23 . This is a known [issue](https://issues.apache.org/jira/browse/LUCENE-9022) that we fixed in Lucene 8.3. Parent join queries should never be cached because they hold a lot of pre-aggregated informations that are not accounted in the cache. You should upgrade to a most recent 7.x version (latest is `7.8.0` and the first version that contains the fix is `7.5`) so I hope you don't mind if I close this issue.
