### ISSUE TITLE
Ordered intervals query could match a wrong document

### ISSUE THREAD

**Issue by bperalta** [elastic/elasticsearch#58576]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.0 docker image

**Plugins installed**: [] 

**JVM version** (`java -version`): openjdk version "1.8.0_252"

**OS version** (`uname -a` if on a Unix-like system): Linux insight-bperalta.private.mesao.com 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 
In some specific context with documents containing some repetitive words, an ordered intervals query could return a wrong document while the same unordered intervals query does not return any document.

**Steps to reproduce**:

 1. Create a simple index : 
```
PUT /intervals_test
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "object": { "type": "text" }
    }
  }
}
```
 2.  Index that simple document : 
```
PUT /intervals_test/_doc/1
{
    "object": "issue with intervals queries from search engine. So it's a big issue for us as we need to do ordered searches. Thank you to help us concerning that issue"
}
```

 3. Execute that unordered intervals query
```
POST /intervals_test/_search
{
    "query": {
        "intervals": {
            "object": {
                "match": {
                    "query": "issue search ordered",
                    "max_gaps": 1,
                    "ordered": false
                }
            }
        }
    }
}
```
The document will not match. The answer is correct.

 4. Execute the same query but with `"ordered": true` option : 
```
POST /intervals_test/_search
{
    "query": {
        "intervals": {
            "object": {
                "match": {
                    "query": "issue search ordered",
                    "max_gaps": 1,
                    "ordered": true
                }
            }
        }
    }
}
```
The document will match, but it would not

**Comment by jimczi** [comment]
None of this query should match. They have a `max_gaps` of 1  and the matching words are separated by more than 1 term.
Removing the `max_gaps` option work as expected, however 
I tested with `7.8` and it works correctly, however, when playing with `max_gaps` I realized that the caching of the query has a [bug](https://github.com/apache/lucene-solr/blob/7c1ba1aebeea540b67ae304deee60162baee2e12/lucene/queries/src/java/org/apache/lucene/queries/intervals/FilteredIntervalsSource.java#L140). It doesn't take into account the value set in `max_gaps`, so a query using a different value for this option is considered equivalent in the query cache. @romseygeek can you take a look ?

**Comment by romseygeek** [comment]
The `max_gaps` value is taken into account, as it's part of the filter name (`MAXGAPS/1` vs `MAXGAPS/2`) - there shouldn't be cache pollution here.

**Comment by romseygeek** [comment]
So this is a bug in the ORDERED algorithm (and it appears to be a problem in the initial paper as well).  I opened https://issues.apache.org/jira/browse/LUCENE-9418 to fix it.

**Comment by jimczi** [comment]
The bug is fixed in [Lucene](https://issues.apache.org/jira/browse/LUCENE-9418) and will be included in the next minor release of Elasticsearch (`7.9.0`), hence closing. Thanks for reporting @bperalta !
