### ISSUE TITLE
Improve leader node-left logging to indicate timeout/coordination state rejection

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#58586]
## Problem
Production systems generally don't have debug logging enabled, to look at historical reasons for `node-left` reasons it becomes tricky to find if follower rejected with `CoordinationStateRejectedException`  causing `followers check retry count exceeded` or was it a slow node with maybe long GC or slow resource which failed to respond back within the default `10s` timeout. 

While I understand it might be tricky though is conclude the reason if there is a mix of multiple reasons across attempts, but maybe fine to log last or all

**Comment by Bukhtawar** [comment]
@DaveCTurner if this issue makes sense, then would it be fine if I start working the PR

**Comment by DaveCTurner** [comment]
I haven't encountered a situation where this detail would have been useful. A node only actively rejects follower checks after it's stopped following the master, which it records in its logs; on the other hand if the checks time out then you have to look at the lost node's logs to see why that might have happened too. Given that you have to look at the lost node's logs in any case, there isn't much benefit in adding detail to the master's logs as well.

You can of course set `logger.org.elasticsearch.cluster.coordination.FollowersChecker: DEBUG` on your specific production system if you want to see more details anyway. This logger is silent on the happy path.

**Comment by Bukhtawar** [comment]
Thanks your suggestion, that works too. I didn't realise that the debug logs are otherwise mute.

**Comment by Bukhtawar** [comment]
The only concern would be in a large size cluster(100+) with  multiple nodes seeing a problem, leader logs could bloat up, in which case we might want to only enable it on data only nodes. `node-left` reason has acted as a one place to start the investigation in the past. I still think it would add value but sure there is a work around

**Comment by DaveCTurner** [comment]
Follower checks are relatively rare, no more frequent than once per second per node, so even if hundreds of nodes all actively failed at once I don't think the log volume would be unmanageable.

**Comment by Bukhtawar** [comment]
Got it. Other than that I currently have no other feedback. Thanks for your suggestions, really useful

**Comment by DaveCTurner** [comment]
Closing this as there doesn't seem to be any action needed here.
