### ISSUE TITLE
Re-enable FIPS tests in CI for 6.8

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#58645]
6.8 has diverged quite a bit from 7.x and master in terms of our build infrastructure so backporting the changes made to enable fips testing there were not straightforward. However, 6.8 will be with us for a long time ahead and we need to re-enable running CI tests there in FIPS mode

**Comment by mark-vieira** [comment]
@jkakavas realistically, do we see this happening? I'm inclined to say no and punt on this issue.

**Comment by jkakavas** [comment]
I dont think this is a decision we can take lightly as it affects our support of the feature in that version. I will discuss with the security team and come back with a plan.

**Comment by mark-vieira** [comment]
@jkakavas any update on this? I believe a lot of the effort here would land with the security team as well to sort out issues. Has there been a discussion on whether we want to put in that effort?

**Comment by jkakavas** [comment]
Yes ,we discussed it in our team meeting and decided we dont want to do this.
