### ISSUE TITLE
Mutliple CVE vulnerabilities in the elasticsearch docker image(v7.7.1 & v7.8.0)

### ISSUE THREAD

**Issue by anshu14** [elastic/elasticsearch#58653]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.1 & 7.8.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): 16.04

**Description of the problem including expected versus actual behavior**: When i am trying to install elasticsearch using helm install command, it tries to pull the image from "docker.elastic.co/elasticsearch/elasticsearch:7.7.1". This image has in total 33 CVE violations(Common Vulnerabilities and Exposures). Due to this, i cannot proceed ahead and it is kind of blocker for me. These violations are mainly in libxml2 and python library.

I updated the image version from 7.7.1 to 7.8.0, but this image version also has same CVE issues.
Please help me in resolving these CVE issues.

**Expected behavior**: The image should get downloaded without any CVE issues.

**Comment by DaveCTurner** [comment]
Please send reports of security vulnerabilities to security@elastic.co. As per https://www.elastic.co/community/security, we can accept only security issues at this address.
