### ISSUE TITLE
The scroll, clear scroll and analyze apis should support json in request body

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#5866]
The scroll, clear scroll and analyze apis are the only apis not accepting json, yaml etc in the request body. In order to be consistent with all the other apis they should support this. These apis just assume the scroll_id / text to analyze is specified as a string in the request body.

Supporting json, yaml etc. can be done in bwc manner via content type sniffing and if the content type can't figured out then the request body is assumed to be consumed as a plain string.

**Comment by clintongormley** [comment]
Reopening as the commit was backed out
