### ISSUE TITLE
Showing node type in the elasticsearch log

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#58796]
It would be useful to have node type (master/data/ml/coord) etc information (in addition to node name) available in the logs so that when beats elasticsearch module collects logs from all nodes and visualise in kibana, it will be easier to filter/aggregate and see what message was from what node type.

I guess asking it for hot/warm type of node attribute will be even harder for now, but that will be useful to see as well.

**Comment by Leaf-Lin** [comment]
The second part of my ask could be resolved by having https://github.com/elastic/elasticsearch/pull/54998, yay, but still somehow having the node roles in the log would be useful?

**Comment by rjernst** [comment]
@Leaf-Lin I think this was addressed indirectly through https://github.com/elastic/elasticsearch/pull/60994, which added the roles to an existing log line during startup.

```
[2021-01-12T15:37:34,941][INFO ][o.e.n.Node               ] [runTask-0] node name [runTask-0], node ID [QgeUEXFeTXW-0HfCKyDXDQ], cluster name [runTask], roles [remote_cluster_client, data_hot, master, data_content, ml, transform, data_cold, data_warm, data, ingest]
```

I'm going to close this, but feel free to reopen if I missed something.
