### ISSUE TITLE
GCS integration tests failing due to missing test fixture properties

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#58795]
We've started to see consistent failures in the `7.x` branch with the following:

```
* What went wrong:
Execution failed for task ':x-pack:plugin:searchable-snapshots:qa:gcs:integTestRunner'.
> Cannot get property 'test.fixtures.gcs-fixture-other.tcp.80' on extra properties extension as it does not exist
```

https://gradle-enterprise.elastic.co/s/5bryflowvrjsm

For some reason the Docker compose service properties are not getting set. Initial investigation looks to be some issue with either Docker compose of the corresponding Gradle plugin not returning service info synchronously.

**Comment by mark-vieira** [comment]
Docker-compose test fixtures have been temporarily disabled with 119462dc85758157cbd9d66597a6989bda111815.

**Comment by danhermann** [comment]
I'm still seeing instances of this error in 7.x builds: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/3215/console

**Comment by pgomulka** [comment]
I also see this on my PR against 7.x https://gradle-enterprise.elastic.co/s/6it63unz4zp4s

**Comment by cbuescher** [comment]
Seen today on 7.8 build: https://gradle-enterprise.elastic.co/s/zaxqrqzedl6aw

**Comment by imotov** [comment]
Looks like another failure in https://gradle-enterprise.elastic.co/s/l6sdxrd6zgnbs/console-log?anchor=4734
