### ISSUE TITLE
MixedClusterClientYamlTestSuiteIT timing out on Darwin

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#58816]
The suite has a 40 minute timeout, which seems to occasionally be exceeded on our Darwin CI workers.

Build scan:  https://gradle-enterprise.elastic.co/s/gxr76e7jfnuiq

Output: 

```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Comment by droberts195** [comment]
There’s more comment and analysis about the possible causes in #58286

**Comment by rjernst** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/58286
