### ISSUE TITLE
Watcher state doesn't show errors while all executions exited with ERROR

### ISSUE THREAD

**Issue by chrismaes87** [elastic/elasticsearch#58826]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.1 (elastic cloud)

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

The **elasticsearch Watcher** summary shows state **OK** while all the last runs encountered an error

**Steps to reproduce**:

 1. create a watcher that runs ok (triggers every x minutes)
 2. insert a typo
 3. look at the watcher history, you should see errors: 
![image](https://user-images.githubusercontent.com/6972561/86234239-e9c96580-bb96-11ea-9841-b6ac78fcb34f.png)
 4. The status of the watcher remains OK, while we would expect it to show ERROR: 
![image](https://user-images.githubusercontent.com/6972561/86239485-b5a67280-bb9f-11ea-99fb-2e5dd13accb6.png)

**Provide logs (if relevant)**:

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
