### ISSUE TITLE
sum_bucket over a top_metrics aggregation throws when metric has no value

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch#58926]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0

**Plugins installed**: []

**JVM version** (`java -version`): Java 11 (bundled JDK)

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**: Doing a `sum_bucket` aggregation over a `top_metrics` does not support getting `null`s in metrics, though this might well be the "top" value... I'm expecting the `sum_bucket` aggregation to simply skip the null value, following the configured _gap policy_.

**Steps to reproduce**:

This 3 requests in Kibana dev console should reproduce the problem.

```
PUT /sum_bucket_over_top_metrics
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "keyword": {
        "type": "keyword"
      },
      "metric": {
        "type": "long"
      }
    }
  }
}

PUT /sum_bucket_over_top_metrics/_bulk
{ "index": {} }
{ "@timestamp": "2020-07-01", "metric": 1, "keyword": "first" }
{ "index": {} }
{ "@timestamp": "2020-07-02", "metric": 2, "keyword": "first" }
{ "index": {} }
{ "@timestamp": "2020-07-01", "metric": 1, "keyword": "second" }
{ "index": {} }
{ "@timestamp": "2020-07-02", "metric": 2, "keyword": "second" }
{ "index": {} }
{ "@timestamp": "2020-07-03", "keyword": "second" }

POST /sum_bucket_over_top_metrics/_search
{
  "size": 0,
  "aggs": {
    "keyword": {
      "terms": {
        "field": "keyword"
      },
      "aggs": {
        "metrics": {
          "top_metrics": {
            "sort": { "@timestamp": "desc" },
            "metrics": [{ "field": "metric" }]
          }
        }
      }
    },
    "sum": {
      "sum_bucket": {
        "buckets_path": "keyword>metrics[metric]"
      }
    }
  }
}
```

**Provide logs (if relevant)**:

```
{
  "error" : {
    "root_cause" : [ ],
    "type" : "search_phase_execution_exception",
    "reason" : "",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "null_pointer_exception",
      "reason" : "Cannot invoke \"org.elasticsearch.xpack.analytics.topmetrics.InternalTopMetrics$MetricValue.numberValue()\" because the return value of \"java.util.List.get(int)\" is null"
    }
  },
  "status" : 500
}
```

Thanks !

David

**Comment by ddolcimascolo** [comment]
Hi guys, did you get a chance to review this issue? Could it be something I'm doing wrong? 

Thanks!

**Comment by nik9000** [comment]
Thanks for the recreation! This is certainly a bug on my side. I'm not 100% sure whether the sum should be `NaN` or `0`, but :boom: is certainly not he right answer.

**Comment by ddolcimascolo** [comment]
Hi @nik9000, thx for taking the time to review this.
I think the sum_bucket aggregation should respect the defined gap policy and either replace the null with 0 (insert_zeroes) or skip the value (skip)

Regards, 
David

**Comment by nik9000** [comment]
@polyfractal what do you think of handling the null value by looking at the gap policy? Do you know off hand what we do in other place?

**Comment by polyfractal** [comment]
So the gap policy stuff will be handled by the pipeline agg, depending on the value returned by the metric aggregator.  E.g. if a metric returns NaN (either because it's an "empty" metric and that's the placeholder, or because the value really was NaN), the pipeline infra will replace that with the selected gap_policy

We might need to make some changes though, since today I believe pipelines only handle NaN/Infinity/empty buckets (doc_count zero).  Right now null == invalid bucket path, because actual nulls aren't generally encountered by pipelines

This logic is mostly done in [BucketHelpers](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketHelpers.java#L157), and not in a particularly robust manner...  :(

**Comment by ddolcimascolo** [comment]
Thx for fixing!

**Comment by nik9000** [comment]
> Thx for fixing!

I'm just sorry it took so long! It should land with 7.9.
