### ISSUE TITLE
SQL: integer parameter validation in string functions

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#58923]
The following query uses `Integer.MAX_VALUE` as parameter input: `SELECT SUBSTRING('a', 2147483647, 1), INSERT('ab', 2147483647, 1, 'x')`, returning the correct result:
```
SUBSTRING('a', 2147483647, 1)|INSERT('ab', 2147483647, 1, 'x')
-----------------------------+--------------------------------
                             |ab                              
```

Going over the Integer limit by 1:
* `SELECT SUBSTRING('a', 2147483648, 1)` returns an expected error: 
  ```
        "type" : "string_index_out_of_bounds_exception",
        "reason" : "begin 2147483647, end -2147483648, length 1"
  ```
* `SELECT INSERT('ab', 2147483648, 1, 'x')` is surprisingly accepted and returns a correct result:
  ```
  INSERT('ab', 2147483648, 1, 'x')
  --------------------------------
  ab                              
  ```
. But going over the limit with more than 1: `SELECT SUBSTRING('a', 2147483649, 1), INSERT('ab', 2147483649, 1, 'x')` behaves as an integer overflow:
```
SUBSTRING('a', 2147483649, 1)|INSERT('ab', 2147483649, 1, 'x')
-----------------------------+--------------------------------
a                            |xb                              
```

The expectation would be either for the functions to accept a long parameter _or_ throw an arithmetic overflow error.

**Comment by bpintea** [comment]
There's one more discrepancy that'd be worth addressing with the string functions: some will only accept an integer parameter (like [`SUBSTRING`](https://github.com/elastic/elasticsearch/blob/bc82b93f467ba5ce22f4b5b71b129bb49acda58b/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/string/Substring.java#L56)), while others will accept floating points too (like [`INSERT`](https://github.com/elastic/elasticsearch/blob/bc82b93f467ba5ce22f4b5b71b129bb49acda58b/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/string/Insert.java#L58)).

**Comment by wuyinan0126** [comment]
@bpintea Yes, the parameter type was different from `insert`, `locate` and `substring`. But in *FunctionProcessor, the integer or rational parameters of these functions are all cast into integer, hence they can treat as integer to check integer overflow.
