### ISSUE TITLE
Test failure: org.elasticsearch.xpack.searchablesnapshots.rest.FsSearchableSnapshotsIT

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#58961]
More specifically it seems that tests from :x-pack:plugin:searchable-snapshots:qa:rest:integTest in 7.x and 7.8 are susceptible to failing. 

**Build scan**:

7.8 https://gradle-enterprise.elastic.co/s/lbxrrtqjia4oe (FsSearchableSnapshotsIT and SearchableSnapshotsClientYamlTestSuiteIT failures) (includes commit a6347a85a51258c127b7d60552bf87c4f9e784ae and ec4843f4df11273a27301b02fb528458822a72eb)
7.x https://gradle-enterprise.elastic.co/s/qjbdm6lqgwjqo (FsSearchableSnapshotsIT failures) (includes commit 6aa669c8bb3eb947375d4777451d3902365392f0 and ec4843f4df11273a27301b02fb528458822a72eb)

**Repro line**:
Focusing on FsSearchableSnapshotsIT since they seem to be the common denomiator (and relevant to recent changes)

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:qa:rest:integTestRunner' --tests "org.elasticsearch.xpack.searchablesnapshots.rest.FsSearchableSnapshotsIT.testClearCache" -Dtests.seed=730DE50376F77A10 -Dtests.security.manager=true -Dtests.locale=ar-EG -Dtests.timezone=Africa/Kigali -Druntime.java=8
```

**Reproduces locally?**:
No. Tried multiple times with different reproduction lines and running different snapshot based tests in parallel. 

**Applicable branches**:

It seems 7.x and 7.8 

**Failure history**:

History is skewed by some related changes https://github.com/elastic/elasticsearch/pull/58847 and https://github.com/elastic/elasticsearch/pull/58912

**Failure excerpt**:

```
org.elasticsearch.xpack.searchablesnapshots.rest.FsSearchableSnapshotsIT > testClearCache FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:35474], URI [/_snapshot/repository/searchable-snapshot/_mount?wait_for_completion=true], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"snapshot_restore_exception","reason":"[repository:searchable-snapshot/4gHSfhgjS8Gtpt48i7shHQ] cannot restore index [wbhjbjxkmn] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"}],"type":"snapshot_restore_exception","reason":"[repository:searchable-snapshot/4gHSfhgjS8Gtpt48i7shHQ] cannot restore index [wbhjbjxkmn] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"},"status":500}
```

cc: @tlrx 
related: https://github.com/elastic/elasticsearch/issues/58901

**Comment by pgomulka** [comment]
It happened again https://gradle-enterprise.elastic.co/s/dd5oniyis7nna on 7.8

**Comment by tlrx** [comment]
The test didn't fail in the past 7 days since #59021 has been merged. Another change in #59313 addresses the last failure that happened on 7.8. I'm considering this issue as fixed.
