### ISSUE TITLE
Rollups: Can't sort by average metric

### ISSUE THREAD

**Issue by lukasolson** [elastic/elasticsearch#58967]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.5-current

**Description of the problem including expected versus actual behavior**:

When running a rollup search using a terms agg, I'm getting errors when sorting by an average agg.

**Steps to reproduce**:

1. Using Kibana, install the sample data web logs
1. Create a rollup job that has a terms field and a sum/avg field
1. Create a visualization using the avg as metric and split by terms

The request will look something like this:

```json
POST rollup_kibana_sample_data_logs/_rollup_search
{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "calendar_interval": "1m",
        "time_zone": "UTC",
        "min_doc_count": 1
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "agent.keyword",
            "order": {
              "1": "desc"
            },
            "size": 5
          },
          "aggs": {
            "1": {
              "avg": {
                "field": "bytes"
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
```

And the response looks like this:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "aggregation_execution_exception",
        "reason" : "Invalid aggregation order path [1]. The provided aggregation [1] either does not exist, or is a pipeline aggregation and cannot be used to sort the buckets."
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "rollup_kibana_sample_data_logs",
        "node" : "Cbd7OK3eTMilRZC4eYAT_g",
        "reason" : {
          "type" : "aggregation_execution_exception",
          "reason" : "Invalid aggregation order path [1]. The provided aggregation [1] either does not exist, or is a pipeline aggregation and cannot be used to sort the buckets.",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "The provided aggregation [1] either does not exist, or is a pipeline aggregation and cannot be used to sort the buckets."
          }
        }
      }
    ]
  },
  "status" : 500
}
```

Note that if I use the sum as the metric instead, I am not getting the error.

**Comment by polyfractal** [comment]
Haven't looked properly, but what I suspect this is due to field name rewriting.  We are either missing the rewrite entirely so it's not finding an underlying agg, or we are rewriting but the special nature of avg aggs means it's not finding one (because those are rewritten into two underlying aggs).

The second option seems more likely since this appears to just affect avg agg.  If that's the issue... unclear if we can fix this, since we won't be able to really sort it until things are merged on the coordinator...

(Luckily, the new v2 rollup should handle this without a problem I think)

**Comment by wchaparro** [comment]
Hey @csoulios What are your thoughts on this one?

**Comment by csoulios** [comment]
This is a known issue in Rollups v1. I have investigated in the past and it is what Zach describes as: 

> we are rewriting but the special nature of avg aggs means it's not finding one (because those are rewritten into two underlying aggs).

Result of `avg` agg is not stored separately but it's  broken as a `sum` and a `value_count` so that it is composable. This means that sort cannot find the `avg` aggregation.

**Comment by csoulios** [comment]
This issue is caused because of the inherent limitations in the design of rollups and it would take signifcant refactoring to fix this. 

As we are focusing our efforts in producing a totally new implementation for rollups (see #74660), we do not plan to fix this issue. Closing it.
