### ISSUE TITLE
Support ip_range in Enrichment 

### ISSUE THREAD

**Issue by srikwit** [elastic/elasticsearch#59037]
Elasticsearch supports the ip_range type. 

One way to reduce a lot of traffic from investigation or focus on a specific network is by the use of allow or deny lists. 
Currently I am only able to enrich IP's individually as the enrich index converts them into a keyword.
As a subnet size increases, it is not effective to expand it and do an enrichment on a 1:1 basis.

Kindly consider for supporting ip_range as it will be helpful to reduce the size of an allow or deny list index and help quicker processing for a lot of security based use cases.

**Comment by jakelandis** [comment]
@martijnvg - does https://github.com/elastic/elasticsearch/pull/76110 close this issue ?  (I think documentation is still needed ?)

**Comment by martijnvg** [comment]
Yes, it does. I will add docs for the range policy type soon. In the meantime I think this issue can closed.

**Comment by mjmbischoff** [comment]
docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.16/range-enrich-policy-type.html
