### ISSUE TITLE
[CI] ML IT: Timed out waiting for the ML templates to be installed

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#59053]
**Build scan**: https://gradle-enterprise.elastic.co/s/3zr7kqjx6oyza

**Repro line**: ```./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT.testFailOverBasics_withDataFeeder" -Dtests.seed=528D9725A2F669F6 -Dtests.security.manager=true -Dtests.locale=ja -Dtests.timezone=Africa/Douala -Druntime.java=14```

**Reproduces locally?**: no

**Applicable branches**: 7.8

Installation of templates times out, might be slowness but given it waits `10s` indicate a real problem.

**Comment by droberts195** [comment]
I think this is another case of the increased parallelism making some tasks take a lot longer than they would if they had the machine to themselves:

<img width="1336" alt="Screenshot 2020-07-07 at 11 05 30" src="https://user-images.githubusercontent.com/7405510/86766036-dfe5ad80-c041-11ea-88f2-d6a129e655e4.png">

There were some periods during the ML internal cluster tests that they were sharing the machine with 7 other heavyweight test suites.

I think we just need to increase the timeout to cope with these situations.

**Comment by droberts195** [comment]
This hasn't failed recently in this way.  A number of timeouts have been increased due to other issues, so this has probably been fixed by one of them.
