### ISSUE TITLE
release-highlights for 7.7.0 is missed

### ISSUE THREAD

**Issue by UkrZilla** [elastic/elasticsearch#59071]
I was searching for a new setting search.check_buckets_step_size since 7.7.0 but can't find it
I think it should be here as for versions before: https://www.elastic.co/guide/en/elasticsearch/reference/7.7/release-highlights-7.7.0.html

**Comment by gwbrown** [comment]
The page you're looking for has been moved, it is now here: https://www.elastic.co/guide/en/elastic-stack/7.7/elasticsearch-highlights.html

I'm not sure if this is something we would usually have a redirect for, so I'll let some docs folks weigh in on that.

**Comment by UkrZilla** [comment]
Have this this pull request been applied to release? https://github.com/elastic/elasticsearch/pull/55266 
According to it 7.7 has a new setting search.check_buckets_step_size

**Comment by jrodewig** [comment]
Hi @UkrZilla,

The `search.check_buckets_step_size` setting was not merged. [That section of the release highlights][0] was later revised in #57306. I hope that clears up the confusion. 

I'll also add a redirect for the 7.7 release highlights.

[0]: https://www.elastic.co/guide/en/elastic-stack/7.7/elasticsearch-highlights.html#_finer_memory_control_for_bucket_aggregations

**Comment by UkrZilla** [comment]
Thanks, James

**Comment by jrodewig** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.7/release-highlights-7.7.0.html now redirects to page that links to https://www.elastic.co/guide/en/elasticsearch/reference/7.7/release-highlights.html.

Closing this issue. Thanks again.
