### ISSUE TITLE
terms agg doesn't like being nested under parent and child aggs

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#59097]
When a `terms` agg is nested under a `parent` or `children` agg it can't use some optimizations. Before #56533 they would also be skipped because all sub-aggregations collect as though they are multi-bucketed. We tried to collect sub-aggregations of the parent/child agg as single bucketed because, well, they only collect a single bucket. But that produced incorrect results and I couldn't figure out why. So, for now, we force the sub-aggs of `parent` and `children` to collect in multi-bucket mode. This bug is to figure out how to disable that.

**Comment by not-napoleon** [comment]
@nik9000 Do we still care about this or can we close it?

**Comment by nik9000** [comment]
I don't think we are going to do anything about this for a while. So I'd zap it.
