### ISSUE TITLE
7.8.0 shuffles shards constantly for no reason

### ISSUE THREAD

**Issue by awick** [elastic/elasticsearch#59104]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.8.0, Build: default/tar/757314695644ea9a1dc2fecd26d1a43856725e65/2020-06-14T19:35:50.234439Z, JVM: 14.0.1

**Plugins installed**: [] none

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): Linux moloches29 3.10.0-1127.10.1.el7.YAHOO.20200605.60.x86_64 #1 SMP Fri Jun 5 13:51:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

After upgrading from 7.7.1 to 7.8.0 some of my clusters (9 of 14) have been migrating shards around constantly for 2 weeks now. The clusters are all GREEN. This happens on both clusters that have ILM and don't have ILM, so I don't think it is ILM related. It seems to only be happening on clusters that have cluster.routing.allocation.awareness.attributes set, but not sure if that is the cause. I do have 2 clusters with cluster.routing.allocation.awareness.attributes that aren't doing it. I've tried doing a full bounce of one the cluster (since they were upgraded using a rolling restart) but that doesn't seem to have fixed anything. The clusters that it happens on are medium to large, anywhere from 15 data nodes to over 100 data nodes. Prior to going to 7.8.0 there were no shards shuffling around.

Other folks who use Moloch have reported having the same issue, so it isn't just me and my clusters.

```
curl -H "Content-Type: application/json" -s --insecure 'https://localhost:9200/_cluster/settings?pretty&flat_settings'
{
  "persistent" : {
    "cluster.max_shards_per_node" : "5000",
    "cluster.routing.allocation.awareness.attributes" : "molochzone",
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "40",
    "cluster.routing.allocation.node_concurrent_recoveries" : "4",
    "indices.recovery.max_bytes_per_sec" : "200mb"
  },
  "transient" : { }
}
```

**Comment by ywelsch** [comment]
Can you reduce `cluster.routing.allocation.cluster_concurrent_rebalance` back to 2 (the default), let the cluster juggle shards for a bit and see if that helps? Based on the above settings, it also sounds like your cluster is way over-sharded.

**Comment by awick** [comment]
I forgot to put in my standard background info
* I've been running large Elasticsearch clusters since 2011
* I've been using the current persistent settings for several years, and the last time I even changed my elasticsearch.yml file was Nov 2019 (I use ansible so I have every version ever used)
* This behavior is new, I've never seen it in any of the previous versions I've used.

I will try reducing it to 2, but I don't think I can leave it that way. I forgot to mention on 1 cluster I did try changing cluster.routing.allocation.cluster_concurrent_rebalance to 0 to stop all rebalancing and let it sit for a while and then I turned back on and it started moving things again.

I'm not sure what you mean by oversharding. I keep my typical shard size ~100G after force_merge

It sure seems like there is something in the disk decider or awareness algorithms that changed where it constantly thinks it can do better and never settles down. Like maybe some random seed or sort algorithm changed between versions.

**Comment by ywelsch** [comment]
> Can you reduce cluster.routing.allocation.cluster_concurrent_rebalance back to 2 (the default), let the cluster juggle shards for a bit and see if that helps?

What's been the effect of this?

Are you perhaps close to your disk watermarks, which can cause shard movements?

> It sure seems like there is something in the disk decider or awareness algorithms that changed where it constantly thinks it can do better and never settles down. Like maybe some random seed or sort algorithm changed between versions.

I'm not aware of any changes in 7.8.0 that would explain the behavior observed. Is there any kind of pattern you see in these relocations? For example, is it always the same shards moving back and forth? The only option I see to debug this further would be to enable debug/trace logging on `org.elasticsearch.cluster.routing.allocation`, which will create a lot of logging output on the master (so better just put as transient setting), but will perhaps provide some information as to why shards are moving.

**Comment by cjcenizal** [comment]
No further feedback received. @awick if you have any more information for us please add it in a comment and we can look at re-opening this issue.
