### ISSUE TITLE
Elasticsearch: empty slices when using scroll api with slice

### ISSUE THREAD

**Issue by casertap** [elastic/elasticsearch#59110]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2

**Plugins installed**: []

repository-s3
analysis-icu
analysis-kuromoji
analysis-nori
analysis-phonetic
analysis-smartcn
analysis-stempel
analysis-ukrainian
https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.5.2/elasticsearch-analysis-ik-7.5.2.zip
https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v7.5.2/elasticsearch-analysis-pinyin-7.5.2.zip
https://github.com/medcl/elasticsearch-analysis-stconvert/releases/download/v7.5.2/elasticsearch-analysis-stconvert-7.5.2.zip

**JVM version** (`java -version`):

JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9

**OS version** (`uname -a` if on a Unix-like system):

OS[Linux/5.4.0-39-generic/amd64]

**Description of the problem including expected versus actual behavior**:

I have a simple setup with a green cluster (v7.5.2) of 1 instance with 1 index (replica 0) with 8 shards.
61,500 documents indexed.

If I create 8 slices with these queries (POST queries)
```
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 0, 'max': 8}, 'size': 1000}
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 1, 'max': 8}, 'size': 1000}
...
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 7, 'max': 8}, 'size': 1000}
```
for each slice I collect the first hits of each slice and get those lengths:
```[1000, 0, 0, 0, 0, 0, 0, 0]```

Only 1 slice has results which is equivalent to not slicing the index in the first place.

I tried a max of 32 with those commands:
```
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 0, 'max': 32}, 'size': 1000}
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 1, 'max': 32}, 'size': 1000}
...
http://localhost:9202/products_dev/_search?scroll=10m: {'slice': {'field': 'created_at', 'id': 31, 'max': 32}, 'size': 1000}
```
for each slice I collect the first hits of each slice and get those lengths:
```[1000, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0]```

This way I can scroll my index using 4 different (non-empty) slices but I had to create 32 contexts which is not ideal.

I think this is a bug. It also happens on a real production cluster with 3 nodes and index with replica 1.

I tried to use a date as slice.field
```
"slice": {
        "field": "created_at",
```
but it did not help.

**Steps to reproduce**:

I can't share my mapping but there is nothing special in there. here is the settings part
```
  "settings": {
    "number_of_shards": 8,
    "number_of_replicas": 1, (or 0)
    "max_result_window": 50000,
    "codec": "best_compression",
```
# Scenario 1 (8 slices)
then you create the scroll 0:
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at", "id": 0, "max": 8}, "size": 1000}' | jq '.hits.total.value'
``` 
=> should contain all the documents in your index

then you create the scroll 1:
```
 curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at", "id": 1, "max": 8}, "size": 1000}' | jq '.hits.total.value'
``` 
=> should return 0 result
scroll 2,3,4,5,6,7 should return 0 result as well

# Scenario 2 (16 slices)

you create the scroll 0:
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at", "id": 0, "max": 16}, "size": 1000}' | jq '.hits.total.value'
```
=> should contain half of all the documents in your index
scroll 1,2,3,4,5,6,7 should return 0 result

then you create the scroll 8:
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at", "id": 8, "max": 16}, "size": 1000}' | jq '.hits.total.value'
``` 
=> should contain half of all the documents in your index
scroll 9,10,11,12,13,14,15 should return 0 result as well

**Comment by DaveCTurner** [comment]
@casertap does this also happen with a `max` that not a multiple of 8, e.g. `7` or `29`? I'm wondering if your `created_at` field contains dates that are all multiples of 8 so they all land in the first bucket. For instance, they might all be rounded to the nearest second but represented in milliseconds so they're all divisible by 1000.

**Comment by casertap** [comment]
Thanks @DaveCTurner for your response.

I ran a few experiments to try to debug this.

Each of the following queries creates a slice with `id: 0` and then with `id: 1`. 

Remove the `field` from slice creation to use the default _id (eg. vst_3497636_all, vst_2373825_all, ... ) (keep max: 8 size: 1000)
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 0, "max": 8}, "size": 1000}' | jq '.hits.total.value'
7500
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 1, "max": 8}, "size": 1000}' | jq '.hits.total.value'
0
```

Try `max: 7` slices with `size: 999` on `_id`
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 0, "max": 7}, "size": 999}' | jq '.hits.total.value'
9500

curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 1, "max": 7}, "size": 999}' | jq '.hits.total.value'
0
```

Try an integer timestamp field `created_at_day_timestamp` that vary 148 times

the query for the number of distinct values
```
JSON='{"aggs" : {"type_count" : {"cardinality" : {"field" : "created_at_day_timestamp"} } }, "size": 0 }'
curl -XPOST "http://localhost:9202/products_dev/_search" -H 'Content-Type: application/json' -d "$JSON"

{"took":11,"timed_out":false,"_shards":{"total":8,"successful":8,"skipped":0,"failed":0},"hits":{"total":{"value":9500,"relation":"eq"},"max_score":null,"hits":[]},"aggregations":{"type_count":{"value":148}}}% 
```
Some actual values for here
```
curl -H 'Content-Type: application/json' -XGET "http://localhost:9202/products_dev/_search" -d'
{
  "aggs" : {
    "distinct" : {
      "terms" : { "field" : "created_at_day_timestamp", "size":10 } 
    }
  }, 
  "size": 0
}' | jq '.aggregations.distinct.buckets[] | \(.key)'
1585958400000
1587168000000
1587686400000
1569801600000
1587254400000
1593216000000
1589846400000
1591228800000
1592265600000
1581984000000
```

create a scroll using this `created_at_day_timestamp` field  `max: 7` slices with `size: 999` 
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at_day_timestamp", "id": 0, "max": 7}, "size": 999}' | jq '.hits.total.value'
9500
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "created_at_day_timestamp", "id": 1, "max": 7}, "size": 999}' | jq '.hits.total.value'
0
```
explicitly set _id
```
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "_id", "id": 0, "max": 7}, "size": 999}' | jq '.hits.total.value'
9500
curl -XPOST "http://localhost:9202/products_dev/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"field": "_id", "id": 1, "max": 7}, "size": 999}' | jq '.hits.total.value'
0
```
I copy-paste here the actual result of the last query
```
{"_scroll_id":"DnF1ZXJ5VGhlbkZldGNoCAAAAAAAAABpFm8xZzNCSS1WUlIycGdkb25Eb0RCSWcAAAAAAAAAahZvMWczQkktVlJSMnBnZG9uRG9EQklnAAAAAAAAAGsWbzFnM0JJLVZSUjJwZ2RvbkRvREJJZwAAAAAAAABsFm8xZzNCSS1WUlIycGdkb25Eb0RCSWcAAAAAAAAAbRZvMWczQkktVlJSMnBnZG9uRG9EQklnAAAAAAAAAG4WbzFnM0JJLVZSUjJwZ2RvbkRvREJJZwAAAAAAAABvFm8xZzNCSS1WUlIycGdkb25Eb0RCSWcAAAAAAAAAcBZvMWczQkktVlJSMnBnZG9uRG9EQkln","took":1,"timed_out":false,"_shards":{"total":8,"successful":8,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}% 
```

I tried to recreate the slice decision algo with this java code on the `_id` field using 8 slices
```
        String Str = new String("vst_3497636_all");
        int slice = Math.floorMod(Str.hashCode(), 8);
        System.out.println("Hashcode for "+ Str +" :" + Str.hashCode() + " slice: "+ slice);
        String Str2 = new String("vst_2373825_all");
        int slice2 = Math.floorMod(Str2.hashCode(), 8);
        System.out.println("Hashcode for "+ Str2 +" :" + Str2.hashCode() + " slice: "+ slice2);
```

I get 2 different slices already but this algo my not be the actual one used by elasticsearch
```
Hashcode for vst_3497636_all :-270199692 slice: 4
Hashcode for vst_2373825_all :112387448 slice: 0
```

**Comment by casertap** [comment]
Sorry my local index had now only 9500 documents. Let me add more documents, I will run a `/_cat/shards` and let you know if any of the previous queries worked better

**Comment by casertap** [comment]
My local index had so few documents, most of the documents where saved in 1 shard

I tried a bigger index and got some better results
7
```
curl -XPOST "http://localhost:9200/products_ingest_2020-07-09_10-44-00/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 0, "max": 7}, "size": 999}' | jq '.hits.total.value'
1315482
curl -XPOST "http://localhost:9200/products_ingest_2020-07-09_10-44-00/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 1, "max": 7}, "size": 999}' | jq '.hits.total.value'
656709
curl -XPOST "http://localhost:9200/products_ingest_2020-07-09_10-44-00/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 2, "max": 7}, "size": 999}' | jq '.hits.total.value'
657589
```
8
```
curl -XPOST "http://localhost:9200/products_ingest_2020-07-09_10-44-00/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 0, "max": 8}, "size": 1000}' | jq '.hits.total.value'
657406
curl -XPOST "http://localhost:9200/products_ingest_2020-07-09_10-44-00/_search?scroll=10m" -H 'Content-Type: application/json' -d '{"slice": {"id": 1, "max": 8}, "size": 1000}' | jq '.hits.total.value'
656709
```
Thanks for your help
