### ISSUE TITLE
Report peak model memory in ModelSizeStats

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#59130]
`ModelSizeStats` should contain `peak_model_bytes` field containing the peak memory usage of the model in bytes.
C++ class (`CResourceMonitor`) already stores relevant bit of information.

**Comment by droberts195** [comment]
I think there might be one complication, which is that `CResourceMonitor::m_Peak` is not remembered when the program stops and restarts.  It might be possible to get around this using the functionality of the `core::CProgramCounters` class.  Those counters persist between runs, and already contain a counter for latest memory usage.  So it should be possible to add another for peak memory usage, get rid of `CResourceMonitor::m_Peak`, and use the program counter in its place.

This is only an idea - it needs a closer look to see if it will work in practice.  If it won't then we'll need an alternative way of persisting `m_Peak` between runs.

**Comment by przemekwitek** [comment]
> This is only an idea - it needs a closer look to see if it will work in practice.

Thanks for the idea, I'll take a look.
