### ISSUE TITLE
`_ml/data_frame/analytics/{id}/_update` is not present in rest-api-spec

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch#59148]
Hello team!
While the API `_ml/data_frame/analytics/{id}/_update` is documented in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/update-dfanalytics.html), it appears not to be present in the [rest-api-spec](https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/api) (both `master` and `7.x`), is there a reason for this?
Thanks!

**Comment by dimitris-athanasiou** [comment]
I stumbled on this one too. I'll pick it up if you don't mind @przemekwitek.

**Comment by przemekwitek** [comment]
> I stumbled on this one too. I'll pick it up if you don't mind @przemekwitek.

Sure, go ahead @dimitris-athanasiou. Thanks!
