### ISSUE TITLE
[DOCS] Move bi-directional CCR blog to documentation

### ISSUE THREAD

**Issue by zuketo** [elastic/elasticsearch#59171]
The architecture described in [Bi-directional replication with Elasticsearch cross-cluster replication (CCR)](https://www.elastic.co/blog/bi-directional-replication-with-elasticsearch-cross-cluster-replication-ccr) is becoming a common CCR architecture.

To ensure the content is properly maintained, updates are made to the guide with new versions of Elasticsearch, and to improve discoverability of the content, this guide should be moved to the Elasticsearch docs.

**Comment by lockewritesdocs** [comment]
@zuketo, I'm going to do some work on the CCR docs soon, so I can incorporate this information and tutorial as part of that effort.

**Comment by mellieA** [comment]
@zuketo and @lockewritesdocs, I'm already working on this. I don't have an issue open for it yet, so I'm happy to take this one on. I have a draft in a google doc that I've already moved into asciidoc, it's based on your blog @zuketo, but from a Kibana perspective. I can add you both as reviewers when I put the PR up later this week, let me know if anything is missing that you want to include.

**Comment by lockewritesdocs** [comment]
@mellieA, your response is timely 😄  I emailed you separately about combining efforts on this work. Please read that email and let me know what you think of my proposal. I would love to collaborate!

**Comment by lockewritesdocs** [comment]
@mellieA, just circling back on this issue. Do you have a PR that we can link to this issue that will mark it as resolved?
