### ISSUE TITLE
Support custom metadata on Data Streams

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#59195]
The intention behind this feature is to enable the UI to identify the data streams created by Ingest Manager. We'll need to implement a solution that allows index templates to define the metadata that is applied to the data streams that they create.

**Comment by afharo** [comment]
We need this as well for the changes in https://github.com/elastic/kibana/pull/71419. 
Ideally, the `_meta` info in the Data Streams should be copied over to the underlying indices it creates.

**Comment by dakrone** [comment]
> Ideally, the `_meta` info in the Data Streams should be copied over to the underlying indices it creates.

We first need to support `_meta` on indices themselves, which is probably a separate issue

**Comment by afharo** [comment]
@dakrone what do you mean with _support `_meta` on indices themselves_?

I thought it is already supported. Kibana uses that feature in the `.kibana` index and AFAIK, Beats does as well. I'm talking about `mappings._meta` though. Maybe that's my confusion?

**Comment by dakrone** [comment]
Mappings metadata is more thought of as metadata about the mappings themselves, not the index (at least that's they way I think about it). It would work for now, but I don't think we should use it as a general purpose metadata storage for the index.

**Comment by afharo** [comment]
@dakrone I agree! Thank you for explaining!

**Comment by yuliacech** [comment]
@dakrone Hi Lee, I was wondering if there is any work planned on adding metadata to data streams? I see now that we have 
```
"_meta": {
    "package": {
      "name": "system"
    },
    "managed_by": "ingest-manager",
    "managed": true
  }
```
in both index templates mappings and index mappings if they were created by ingest manager.

**Comment by dakrone** [comment]
@yuliacech it's still something we'd like to do, but I don't think it has anyone currently working on adding it.

**Comment by martijnvg** [comment]
I think this is something that we can pickup in the near future. 

When a data stream is created then custom data stream metadata should be sourced from the matching composable index template and be added to the data stream under the `_meta` key. This custom metadata can then be retrieved via the get data stream api. 

I do have a question about from where the data stream custom metadata is sourced. Should all the keys under the current `_meta` json object on a composable index template be added to a data stream's custom metadata? Or only a subset of keys? Or should the `data_stream` object on a composable template have its own `_meta` object? 

Also is there a need to update a data stream's custom metadata after its creation? Currently there isn't a data stream update api or something similar.

**Comment by yuliacech** [comment]
Hi @martijnvg, thanks a lot for getting back to me on this! 
I can tell that in Index Management we want to show which data streams are managed by Ingest Manager, so probably using `"managed_by"`and `"managed"`keys. Currently, `"package"` is probably not needed but might be in the future for more info in the UI.
There is no UI for updating data stream at the moment, not sure about planning for it though, @cjcenizal  maybe has more info on this?

**Comment by martijnvg** [comment]
@yuliacech Besides the mentioned keys, would it be okay if other keys also appear on a data stream? More specifically i'm wondering whether there is a need for custom meta keys to only be associated with a data stream or if it is okay if all custom meta data keys from the composable template appear on a data stream and in other places.

**Comment by yuliacech** [comment]
@martijnvg additional keys should not be a problem for UI, I think we can safely ignore them and only use the ones for managed info.

**Comment by martijnvg** [comment]
@yuliacech that is good to know. That will simplify the change that we need to make.

**Comment by cjcenizal** [comment]
> Also is there a need to update a data stream's custom metadata after its creation? Currently there isn't a data stream update api or something similar.

I'm not aware of a need at this time.
