### ISSUE TITLE
Search - expose new Lucene option for case insensitive RegExp queries

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#59235]
[Lucene 9386](https://issues.apache.org/jira/projects/LUCENE/issues/LUCENE-9386) introduced an option for case insensitive matching of RegExp queries. This issue is to expose that capability to elasticsearch users.

One complexity with the feature is that it currently only supports ASCII characters and full support for Unicode has been left as a TODO. Rather than being a simple Boolean flag (eg case sensitive - yes or no?) there is a bitmask parameter which accepts only one flag at the moment - "ASCII_CASE_INSENSITIVE". In future the assumption is that we could use this same bitmask parameter and pass a new "(Unicode)CASE_INSENSITIVE" flag.

Another concern is in Lucene we renamed the previous "flags" constructor parameter to "syntax_flags" to make it distinct from the new "match_flags" parameter. Renaming constructor parameters works OK in Java because they are identified by position and type but in our REST api we rely on JSON field names so have to keep the existing [flags parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-query-field-params).
The question then perhaps is how best to expose the new case insensitive matching flag in the REST api?
Options are:
1)  Add an "ASCII_CASE_INSENSITIVE" value option for the existing `flags` parameter
2) Add a new "match_flags" parameter with possible value option of "ASCII_CASE_INSENSITIVE"
3) Add a simple Boolean flag that can only accept one value (the flag name choice would be `case_sensitive:false` or `case_insensitive:true`). We'd use documentation to declare that only ASCII is supported currently.

**Comment by jpountz** [comment]
I'm not a fan of 1 because it creates issues with `ALL` since I don't think it should affect case sensitivity.

I have a slight preference for 3 because I fear that otherwise we would mostly be pushing complexity downstream. I'm running under the assumption that it wouldn't be a breaking change if we eventually made it handle unicode, which might be controversial.

**Comment by markharwood** [comment]
I'll opt for 3. As for the BWC concern I expect the behaviour change would be welcome. I assume the intent of asking for `lower_case:true` is always the same and the more able we are to fulfil that, the better.

**Comment by micah-gould** [comment]
Can you explain how too do number 3?
