### ISSUE TITLE
Document the execution of ingest pipelines

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#59251]
There are two aspects of ingest pipeline execution that are not well documented today.

First, at the node level, how are ingest pipelines executed if the local node has the ingest role versus if it does not (as far as I can tell, we don't document round robin selection anywhere in the docs).

Second, at the pipeline level, we should document the execution flow. For example, conditional execution and error handling. Additionally, we have default and final pipelines, and it's possible within a pipeline to change the target index, which today doesn't trigger re-execution of pipelines. While in #57968 we are proposing that if the target index is changed then we execute the default and final pipelines on the new target index, we should document the overall execution flow so that it's clear to users.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
