### ISSUE TITLE
Feature request : improvement of the perceived relevance of the highlight

### ISSUE THREAD

**Issue by mdimiceli** [elastic/elasticsearch#5928]
Hi, my name's Damien, I'm working for a french company, Orange.

We discovered Elasticsearch a few months ago and we are very enthusiasts about it, great tool really, so we decided to make a proof a of concept with it. The aim is to replace our internal (home-made) search engines with ES.

To this point we are really satisfied of the results we get in terms of search relevance thanks to all the possible tunings : mappings, lots of query types, filters, etc. But we are facing a big problem, a blocking one. We are not able to obtain what we want from the highlighting part.

To be precise, there are two types of relevance for us :
- the "real" relevance : Do the documents I obtain from my search are relevant according to my search query (and maybe other criterias) ? Is the result exhaustive ? Are the documents well ordered ? etc. It involves reading all the returned documents in their entirety to answer those questions.
- the "perceived" relevance : When I get the highlighted parts of the returned documents do I feel that the results are relevant ? It involves just reading a small part of the document to answer the relevance question.

Actually we have a good relevance and a poor perceived relevance (according to our criterias of what is a good preceived relevance).
This point is a blocking one and our marketing department will not give its approval for the migration until this problem is solved.

I think that we read the the docs correctly, we tried a lot of things, so we need to submit a feature request to your team. Let me explain what we need with some examples, and if we missed something in the docs please accept our apologies.

<h2>First example</h2>

What we want : no matter the number of fragments, we want a constant total size (ex: 2x30, 3x20, 4x15, ... total size is 60).

What we have:
We index a sentence 90 chars long (approximately). We make two searches with 2 fragments of size 30 specified. The first time we search with two words, we get 2 fragments, each of size 30, everything fine, total size is 60 (approximately). The second time we search with only one word so obviously we can have only one fragment and the total size is 30, not 60.

``` bash
# Deleting all indexes
curl -XDELETE 'localhost:9200/_all?pretty=yes'

# Putting some data, approximately 70 characters long.
curl -XPUT 'localhost:9200/index/doc/1?pretty=yes' -d '
{
    "text": "My parents had the good idea of offering me a dog for my tenth birthday. I like him a lot."
}
'

# Refreshing the index.
curl -XPOST 'http://localhost:9200/_refresh?pretty=yes'

# Searching with two keywords for two fragments.
curl -XGET 'localhost:9200/index/doc/_search?pretty=yes' -d '
{
    "query": {
        "match": {
            "text": {
                "query": "idea birthday",
                "operator" : "and"
            }
        }
    },
    "highlight": {
        "fields": {
            "text": {
                "number_of_fragments": 2,
                "fragment_size": 20
            }
        }
    }
}
'

# Searching with one keyword for two fragments.
curl -XGET 'localhost:9200/index/doc/_search?pretty=yes' -d '
{
    "query": {
        "match": {
            "text": "idea"
        }
    },
    "highlight": {
        "fields": {
            "text": {
                "number_of_fragments": 2,
                "fragment_size": 20
            }
        }
    }
}
'
```

Here we specify:
"number_of_fragments": 2
"fragment_size": 30

We would prefer:
"number_of_fragments": 2
"preferred_fragment_size": 30
"total_size": 60
or something like that, the parameters are up to you, we are looking for a behaviour not a syntax.

What we really want is to have a constant total size because when showing the results to the users through a web page it's nicer to have regular sizes for text blocks (to the marketing department's point of view...). So according to this, there are cases when the fragments size should be of variable length. Typically when there are less matches than the number of required fragments. The only case for which we accept to have a smaller size is when the size of the searched field is shorter than the size we specified for the highlight, this is obvious but has to be mentionned to be exhaustive.
This is kind of a corner case between using "no_match_size", and "number_of_fragments" coupled with "fragment_size".

<h2>Second example</h2>

What we want: we compose resumes from fragments, by catenating them with ellipses(...). We want the resumes to start by the beginning of a phrase.

What we have:
We have to choose between the postings highlighter and the fast vector highlighter. With the first one we have all the fragments beginning by the beginning of a sentence but we loose control over the total size of the resume. With the second one we keep control over the total size but we loose "the sentence effect". We would like something between the two, once more. The first fragment should start by the beginning of a sentence and the others are free.

Once more it's a matter of good user experience (still the marketing department's opinion...). The problem with that is that if the sentence contains a keyword but it is far from the beginning, it could be impossible to have both the beginning of the sentence AND the highlighted keyword in the same fragment because of a too short fragment. Variable fragments length could do the trick in some cases but not all, if the sentence is longer than the total length we loose once more. Maybe the solution would be to have an additional fragment for the sentence purpose.

Once your highlighted fragments have been collected you add an extra fragment which contains the beginning of the sentence in which the first fragment was taken. This extra fragment can be short and is not forced to contain a keyword, it is just here for the glitter effect.

<h2>Third example</h2>

The total size should never be excedeed. If you look at the previous examples you will see that the total length is sometimes longer than our desired total size. Moreover the individual lengths of the fragments do not always seem optimal, they sometime could be longer without exceeding their specified size. We don't really understand how this works.

<h2>Fourth example, the most important</h2>

What we want:
When searching for several terms we want to get the most big number of different terms to be highlighted. This point is crucial for the perceived relevance.

What we have:
ES selects the best matches and so often takes the same keyword. In the following example we search for "dog" and "friend" and we only get "dog" highlighted, twice, because it comes first in the text. We would prefer to have "dog" and "friend" highlighted because it seems more relevant. We tried with highlighted query but did not manage to get what we wanted.

``` bash
# Deleting all indexes.
curl -XDELETE 'localhost:9200/_all?pretty=yes'

# Putting some data
curl -XPUT 'localhost:9200/index/doc/1?pretty=yes' -d '
{
    "text": "I have a dog, very cute. Maybe he is the cutest dog in the world. He is my friend, my best friend actually, and will remain it."
}
'

# Refreshing the index
curl -XPOST 'http://localhost:9200/_refresh?pretty=yes'

# Searching
curl -XGET 'localhost:9200/index/doc/_search?pretty=yes' -d '
{
    "query": {
        "match": {
            "text": {
                "query": "friend dog",
                "operator" : "and"
            }
        }
    },
    "highlight": {
        "order": "score",
        "fields": {
            "text": {
                "number_of_fragments": 2,
                "fragment_size": 30
            }
        }
    }
}
```

Resume of our requirements :
- Specify total size.
- Specify fragments number (preferred number to  be precise)
- Specify fragments size (preferrered again)
- First fragment starts as sentence.
- Fragments contain as much different keywords as possible.

Maybe this should have been posted to Lucene ? Sorry if it is the case.

**Comment by jimczi** [comment]
These are all interesting ideas but there's too much to handle in a single issue ;). 
Also we're now using the `unified` highlighter which does some of the things described here differently (the scores are computed differently as well as the passage boundaries). I'd advise to try the `unified` highlighter and to report any problems related to this new highlighter in a new issue since this one seems to be applicable to the `plain` highlighter only.
