### ISSUE TITLE
DocsClientYamlTestSuiteIT times out

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#59297]
_Note: We had raised such an issue earlier already (https://github.com/elastic/elasticsearch/issues/49753) but I felt a new issue is warranted_

While we did not see any timeouts for a while they have come back in recent months so I wanted to raise this issue for us to keep track of these. Here is a time series of the last five months (https://github.com/elastic/elasticsearch/issues/49753 has been closed on February 5):

![timeouts-last-five-months](https://user-images.githubusercontent.com/1699576/87038503-1fe99380-c1ee-11ea-959e-d6edfe34f93b.png)

Before June 16, timeouts affected Linux workers but after all timeouts happened on Darwin workers (see attached [build stats report](https://github.com/elastic/elasticsearch/files/4896740/dm-docs-client-yaml-test-suite-timeouts.csv.zip) generated via filtering for `test.failed-testcases.summary: "FAILURE DocsClientYamlTestSuiteIT classMethod" AND test.failed-testcases.message: "java.lang.Exception: Suite timeout exceeded (>= 1800000 msec)."` in the last three months).

**Build scan**: https://gradle-enterprise.elastic.co/s/g3rrfj7scx7ki

**Repro line**:

```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT" \
  -Dtests.seed=A25554FFC677D4B5 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=America/Los_Angeles \
  -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: `7.8`, `master` (see failure history link below for details)

**Failure history**: [timeouts within the last three months](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-3M,mode:relative,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20test:%22classMethod%22%20AND%20class:%22%20org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT%22%20AND%20message:%22java.lang.Exception:%20Suite%20timeout%20exceeded%22'),sort:!(time,desc)))

**Failure excerpt**:

The test suite fails with a timeout:

```
java.lang.Exception: Suite timeout exceeded (>= 1800000 msec).
```

**Comment by droberts195** [comment]
I think this is #58286.  The parallelism was increased on the macOS workers and they cannot cope with it so various suites time out.  It's not just the docs tests.  Any of the test suites that start up external clusters and run a lot of tests can be affected.

**Comment by danielmitterdorfer** [comment]
Thanks for the pointer @droberts195! IMHO there is no point having multiple issues for the same underlying cause. I'll close this one then.
