### ISSUE TITLE
Java High Level REST Client is slow than kibana very much

### ISSUE THREAD

**Issue by zzujustme** [elastic/elasticsearch#59301]
es version:6.6.0

i search by kibana cost 600ms,but search by rest high level rest client cost 10s!

**Comment by dadoonet** [comment]
Could you open a discussion on discuss.elastic.co and share the exact query you are running on Kibana and the exact code you are running using Java?

**Comment by nik9000** [comment]
I'm going to close this issue because I can't reproduce it. It'd be great if you could attach reproduction steps, like `curl` for the REST request and a little java project for the HLRC request.
