### ISSUE TITLE
Shard allocation filtering: Prefer certain nodes

### ISSUE THREAD

**Issue by ppat** [elastic/elasticsearch#5936]
```index.routing.allocation.include._host``` allows us to pin indices to certain hosts, but it would be also nice to have the functionality to prefer certain hosts (say ```index.routing.allocation.prefer._host```) and fall back to whatever hosts that are available if the preferred hosts are not up (bonus: then later move shards over once they become available).

**Comment by jpountz** [comment]
No replies for more than one year: closing. We discussed it Fixit Friday and also had some concerns about making the allocation rules more complicated than they are today.
