### ISSUE TITLE
SnapshotResiliencyTests testSnapshotWithNodeDisconnects and testSnapshotPrimaryRelocations failures

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#59384]
**Build scan**:
https://gradle-enterprise.elastic.co/s/puwxv532d7p5u

**Repro line**:
```
 ./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotWithNodeDisconnects" \
  -Dtests.seed=AB11F5CEE90655C4 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=Pacific/Pitcairn \
  -Druntime.java=11
```

**Reproduces locally?**:
Yes 😲 

**Applicable branches**:
Master

**Failure history**:
Once or twice a day since 08/07/2020

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,class,stacktrace),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'SnapshotResiliencyTests%20testSnapshotWithNodeDisconnect'),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError: Condition wasn't fulfilled.
	at __randomizedtesting.SeedInfo.seed([AB11F5CEE90655C4:A5DE5A06F3C06E04]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.runUntil(SnapshotResiliencyTests.java:1163)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.verifyReposThenStopServices(SnapshotResiliencyTests.java:280)
```

'Condition wasn't fulfilled' <- you are such a disappointment

**Comment by davidkyle** [comment]
Muted on master in 35861830b8a593027b32dc8c2840ad9d9a3878b7

**Comment by davidkyle** [comment]
The test `testSnapshotPrimaryRelocations` is also failing with the same error although less frequently and does not reproduce

https://gradle-enterprise.elastic.co/s/u7xph7zsea7mq

```
 ./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotPrimaryRelocations" \
  -Dtests.seed=3D1AA3D6C186B90 \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:-UseSerialGC -XX:+UseG1GC" \
  -Dtests.locale=ar-YE \
  -Dtests.timezone=Europe/Tirane \
  -Druntime.java=11
```

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,class,stacktrace,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testSnapshotPrimaryRelocations),sort:!(time,desc))

**Comment by original-brownbear** [comment]
Turns out this is a real bug with partial snapshots, opened a fix PR that covers both test failures here https://github.com/elastic/elasticsearch/pull/59428
