### ISSUE TITLE
RegressionIT testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#59413]
**Build scan**:
https://gradle-enterprise.elastic.co/s/5fxzmspwrij5s

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows" \
  -Dtests.seed=50E4467094AC6573 \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=SystemV/MST7MDT \
  -Druntime.java=8
```

**Reproduces locally?**:
Nope

**Applicable branches**:
Master, 7.x

**Failure history**:
Not the first time

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,class,stacktrace,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RegressionIT),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: a collection with size a value greater than <0>
     but: collection size <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([50E4467094AC6573:44F0E3F9D85A697A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows(RegressionIT.java:105)
```

**Comment by davidkyle** [comment]
Muted master: c2d58c8e34351be048a33caed864e38dcf1ee757, 7.x: 054d5236d4255663a1d2ce63e1cc1d2074685e61

**Comment by martijnvg** [comment]
I've seen similar failure with the `testWithDatastream()` test in the past days. This is a recent failure: https://gradle-enterprise.elastic.co/s/7j3rvve56jzss/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner/org.elasticsearch.xpack.ml.integration.RegressionIT/testWithDatastream#1

Is this failure similar or should I open a different issue?

**Comment by davidkyle** [comment]
Thanks for the ping @martijnvg 

#59664 has been opened  for the `testWithDatastream` failure and I've muted the tests

**Comment by davidkyle** [comment]
This test has been re-enabled in #59855 with extra logging.

**Comment by davidkyle** [comment]
Possibly related to #60759

**Comment by dimitris-athanasiou** [comment]
Just got another failure of this https://gradle-enterprise.elastic.co/s/ewvxfv7u2k5zs.

@tveasey @valeriy42 It seems it's somehow possible we get no feature importance in that test. This seems like it shouldn't be happening, right? Let me know if I can help explain the test so we figure out what causes it.

**Comment by davidkyle** [comment]
Another failure https://gradle-enterprise.elastic.co/s/2cpqn575esnic

ping @tveasey @valeriy42 This issue with the missing feature importance has been open for a while, logging shows it is coming from the C++ side

**Comment by albertzaharovits** [comment]
Here are another two instances of this failure, today https://gradle-enterprise.elastic.co/s/appijmfujfy42
, and yesterday https://gradle-enterprise.elastic.co/s/pk2dzd4d3xmqe  (from the build scan stats https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.sortField=FAILED&tests.test=testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows&tests.unstableOnly=true ).

This fails very rarely and it looks like it benefits from more data, leaving it unmuted for now.
