### ISSUE TITLE
[CI] Auditing log fails for API key realm name during BWC with version prior to v7.5

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#59425]
The failed test `UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/120_api_key_auth/Test API key authentication will work in a mixed cluster}`.

ApiKey realm name is not available in Authentication metadata till [v7.5](https://github.com/elastic/elasticsearch/commit/7b6246ec670040e8e5dfef05b33bb2b39f8a9357). Hence auditing log fails to [retrieve it](https://github.com/elastic/elasticsearch/blob/7.x/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java#L464) for older versions. 

The failed test has been configured to run only for v7.5 and up. Once this issue is fixed, it can be renabled for older versions by removing [these two lines](https://github.com/elastic/elasticsearch/blob/master/x-pack/qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/120_api_key_auth.yml#L6-L7).

Build scan: https://gradle-enterprise.elastic.co/s/zyiwyg5feg74a

**Comment by dakrone** [comment]
I believe this is the same issue: https://gradle-enterprise.elastic.co/s/x3e4t32i6m3jq that failed today

**Comment by dakrone** [comment]
Muted this since it has failed a couple of times today

**Comment by ywangd** [comment]
Thanks @dakrone 
The new failure is caused by missing role descriptors when creating the API key. The role descriptors were mandatory till v7.3 (#43481). Will raise a fix.

**Comment by ywangd** [comment]
Fixed with #59680
