### ISSUE TITLE
Fail to exclude Post by Term localhost:9200/abc-post-1/post/_search/?mode=exclude:Sales&q=post_type:%22jobs%22&size=1000&from=1

### ISSUE THREAD

**Issue by iexpertini** [elastic/elasticsearch#59457]
Hi Guys,

Need help to filter the ElasticSearch Result.

I don't want to display the post that comes from center post author.

We try to filter it by localhost:9200/abc-post-1/post/_search/?mode=exclude:authorname&q=post_type:%22articles%22&size=1000&from=1

Every time we try but it failes to exclude post from that author. So please can anyone guide it on us.

Thanks,
HS

**Comment by astefan** [comment]
@iexpertini Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
