### ISSUE TITLE
Elastic Search Failure over EC2 AWS

### ISSUE THREAD

**Issue by BabarAli93** [elastic/elasticsearch#59450]
I was trying to install Magento over Amazon EC2 instance and it requires ElasticSearch as prerequisite. I followed available methods to install it through Archive and the other method. But none of them worked for me. 

When I run "sudo service elasticsearch start", it fails and the snapshot of "journalctl -xe" is attached. Can someone help me what is wrong here and what is my mistake. It is currently installed in /etc/share/elasticseach. I also reduced to half the memory in java.options file due to few errors in start.
<img width="1208" alt="Screenshot 2020-07-13 at 10 37 28 PM" src="https://user-images.githubusercontent.com/50677432/87336742-c5d52f00-c55b-11ea-93d9-a486bc45fd83.png">

**Comment by original-brownbear** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by BabarAli93** [comment]
if this is not related to here then it can be closed. Thanks for the guidance Sir.
