### ISSUE TITLE
Document pro-tips for copy_to field

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#59478]
In a recent email thread, @nik9000 described how `copy_to` can be very useful in situations where you want to query many fields many times a second, particularly for phrase queries:

> It tends to be faster to do things one time rather than 30 times. You have to consult a single terms index rather than many. You have a single posting list to walk. If you are doing phrase queries you only have one positions list to load too. It saved us quite a bit of disk IO.
>
> It's important that this really is only something that you want for `should` clauses, no `must` clauses. `must` can do some "leap frogging" tricks that'll save quite a bit of time. But you often want to do a bunch of `should` clauses for a search box.

I'd love to see this information captured in our docs somewhere, possibly in the [copy_to docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html) or maybe on a dedicated page in some sort of "Pro tips" context. Users of the Kibana mappings editor would be able to discover this content from the UI (there's already a link), which will help anyone who is trying to make a decision about how/whether to use `copy_to`.

**Comment by nik9000** [comment]
@jpountz did this a while back: https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#_search_as_few_fields_as_possible

**Comment by nik9000** [comment]
It might be useful on the `copy_to` docs to say "you might use this to improve search speed by searching fewer fields" with a link. You also might use `copy_to` to handle multi-language search, though I don't know the state of the art of that.

**Comment by jpountz** [comment]
+1 to link from the `copy_to` docs
