### ISSUE TITLE
[CI] IndexingIT.testIndexVersionPropagation failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#59494]
Failed as part of `:qa:mixed-cluster:v7.0.1#mixedClusterTest`

**Build scan**: https://gradle-enterprise.elastic.co/s/xpr26bxabxec2

**Repro line**:
```
./gradlew ':qa:mixed-cluster:v7.0.1#mixedClusterTest' \
  --tests "org.elasticsearch.backwards.IndexingIT.testIndexVersionPropagation" \
  -Dtests.seed=529B730BCF19A195 -Dtests.security.manager=true \
  -Dtests.locale=sl-SI -Dtests.timezone=Asia/Tomsk \
  -Dtests.distribution=default -Druntime.java=8 
```

**Reproduces locally?**: No

**Applicable branches**: `7.x`

**Failure history**:
The test itself fails often, but this seems to be the first failure with this particular error condition.
- [Build Stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(branch,build-id,message),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%22testIndexVersionPropagation%22),sort:!(time,desc)))

**Failure excerpt**:
```
java.lang.AssertionError: version mismatch for doc [3] preference [_only_nodes:v7.0.1-1]	
Expected: <10>	
     but: was <11>	
	at __randomizedtesting.SeedInfo.seed([529B730BCF19A195:D308272B6AEF67CA]:0)	
	at org.elasticsearch.backwards.IndexingIT.assertVersion(IndexingIT.java:297)	
	at org.elasticsearch.backwards.IndexingIT.testIndexVersionPropagation(IndexingIT.java:137)	
```

**Comment by dnhatn** [comment]
I've added more logs to this test in https://github.com/elastic/elasticsearch/commit/120fe964022ca06cb4d4c7d4c97cfdf71199f504. Please reopen when it fails again.
