### ISSUE TITLE
ILM delete phase is extremly slow

### ISSUE THREAD

**Issue by hatharom** [elastic/elasticsearch#59545]
ES 7.7.1 running in docker

In short: Delete phase stucks at  "step": "wait-for-shard-history-leases"

In details:

I have created a basic delete policy:

```
"test_policy": {
    "version": 1,
    "modified_date": "2020-07-13T11:38:15.283Z",
    "policy": {
        "phases": {
            "delete": {
                "min_age": "60s",
                "actions": {
                    "delete": {}
                }
            }
        }
    }
}

```
PUT _template/my_template

```
{
  "index_patterns": ["test-*"], 
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.lifecycle.name": "test_policy" 
  }
}
```
then I PUT two indices : test-2017-11-12 and test-2222

Expected outcome : after ~60s (+ some time for the real work) the index get deleted

Actual Outcome: 

What happened (according to http://localhost:9200/test-*/_ilm/explain ) is that both indices phase is 'new' even after minutes. Then after 4-5min one index switched to "delete" phase and stucks there. The other one is still in 'new' phase.

```
"test-2017-11-12": {
    "index": "test-2017-11-12",
    "managed": true,
    "policy": "test_policy",
    "lifecycle_date_millis": 1594640489746,
    "age": "13.69m",
    "phase": "delete",
    "phase_time_millis": 1594640734626,
    "action": "delete",
    "action_time_millis": 1594640734626,
    "step": "wait-for-shard-history-leases",
    "step_time_millis": 1594640734626,
    "phase_execution": {
        "policy": "test_policy",
        "phase_definition": {
            "min_age": "60s",
            "actions": {
                "delete": {}
            }
        },
        "version": 1,
        "modified_date_in_millis": 1594640295283
    }
}
```

And finally after 17min!!! the index gets deleted, now the other one stucks at the same phase

1.What is this 'wait-for-shard-history-leases' thing? Couldn't find anything about it in the ES documentation.
2.Even if one hangs at the 'delete' phase why the other index gets blocked by this? Why not all the indices over 10s age go to the delete phase?

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

In your case the default [poll interval](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/ilm-settings.html#_cluster_level_settings) is 10 minutes, so steps are only advanced every 10 minutes
