### ISSUE TITLE
_field_caps perf test on large mapping

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#59581]
Kibana is considering becoming more reliant on the performance of the field_caps api call - https://github.com/elastic/kibana/issues/71787

tldr; instead of saving the field mapping as a kibana saved object, it would be queried when needed by the user.

It would be extremely helpful to understand the performance limitations of the field caps api, if there are any. Perhaps a perf test on a large field mapping would be helpful.

**Comment by jpountz** [comment]
Can you clarify what "when needed" means? Is it everytime you need to suggest a list of fields to a user, or is there more?

**Comment by mattkime** [comment]
Closing, no longer needed.
