### ISSUE TITLE
CcrRollingUpgradeIT fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#59625]
This test started to fail regularly since July 14th 2020. The logs show some errors related to component templates but this should be addressed by #59624.

**Build scan**: 
https://gradle-enterprise.elastic.co/s/uxnrmjs7mcwve
https://gradle-enterprise.elastic.co/s/li64mi23adjtm
https://gradle-enterprise.elastic.co/s/uza2ofj3d32fe

**Applicable branches**: 7.x

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.upgrades.CcrRollingUpgradeIT%22'),sort:!(time,desc))

**Comment by dakrone** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/mkzyvj65xtfkc

**Comment by dakrone** [comment]
And another: https://gradle-enterprise.elastic.co/s/jfzdfqa6fi4jc

@dnhatn should this be muted while you're taking a look at it?

**Comment by dnhatn** [comment]
Thanks @leehinman. I've muted this suite.

**Comment by dakrone** [comment]
I backported the mute commit to 7.9 as it was failing there regularly also

**Comment by martijnvg** [comment]
@arteam and I spotted that this test suite is still muted in 7.x: https://github.com/elastic/elasticsearch/blob/7.x/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java#L32

Is there a reason for this?

**Comment by dnhatn** [comment]
@martijnvg I've opened https://github.com/elastic/elasticsearch/pull/76765.
