### ISSUE TITLE
We need the RoaringBitMap DataType to be applied in the customer portrait

### ISSUE THREAD

**Issue by ynuosoft** [elastic/elasticsearch#59635]
In big data application,**customer portrait** is very important and  popular.
What we do  now in Elasticsearch? we use binary datatype ,but performance is not good,so instead of ElasticSearch, we used ClickHouse,It supports **roaringBitmap** datatype and is also very convenient.
However, The operation and maintenance of Clickhouse is relatively primitive and I do not like it very much

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
