### ISSUE TITLE
Most of SLM Snapshot Orchestration can be Removed

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#59655]
With #56911 merged to `7.9` and newer, all code in SLM dedicated to making sure that multiple snapshots or snapshot deletes don't run at the same time has become obsolete.
We should move this logic to a separate BwC path to be used in a mixed version cluster and otherwise short-circuit all the checks and waiting and simply execute all operations exactly as scheduled since they will always work out now without exception.

This will make SLM a lot more predictable in behavior since things like slow snapshots will stop causing hold-ups for deletes or other snapshots. Another obvious benefit would be that we will never redundantly load all the `SnapshotInfo` to determine what snapshots to delete since deletes would never collide/wait/fail.

Somewhat relates to #56082 which is another possible optimization to SLM enabled by recent snapshot changes

**Comment by dakrone** [comment]
This has been open for quite a while, and we've made some progress on this. For now I'm going to close this as something that's been done. We can re-open it later if needed.
