### ISSUE TITLE
RegressionIT.testWithDatastream fails on 7.9 branch

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#59664]
**Build scan**:
https://gradle-enterprise.elastic.co/s/7j3rvve56jzss

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testWithDatastream" -Dtests.seed=DB5C0242FF9869CB -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=Pacific/Fakaofo -Druntime.java=8	
```

**Reproduces locally?**:
Nope

**Applicable branches**:
7.9

**Failure history**:
Failed 12 times in the last week: https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.sortField=FAILED&tests.test=testWithDatastream&tests.unstableOnly=true
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testWithDatastream FAILED
    java.lang.AssertionError: 
    Expected: a collection with size a value greater than <0>
         but: collection size <0> was equal to <0>
        at __randomizedtesting.SeedInfo.seed([DB5C0242FF9869CB:A3B7DE539925F385]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
```

**Comment by davidkyle** [comment]
Muted on master 716e22acd18b85e592e24cf7894a2c59a2231ec6, 
7.x c349fdcb896bb0d9fdaeb54c22aac97bc43a5be1
7.9 2488906c1d8d8a013dc24f2815cbb83bfa9e8185
