### ISSUE TITLE
RestClientSingleHostIntegTests.testRequestResetAndAbort fails in 7.x cancelling request

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#59678]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ujpqnv5kcwnj4

**Repro line**:
What's strange is that there *is no reproduction line*.

**Reproduces locally?**:
No, because there's no reproduction line

**Applicable branches**:
7.x

**Failure history**:
Only one failure recently: https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.client.RestClientSingleHostIntegTests&tests.sortField=FAILED&tests.test=testRequestResetAndAbort&tests.unstableOnly=true

**Failure excerpt**:
```
Suite: Test class org.elasticsearch.client.RestClientSingleHostIntegTests
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([1590BDDE62D15D51:21DEFA66B0D9B281]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.elasticsearch.client.RestClientSingleHostIntegTests.testRequestResetAndAbort(RestClientSingleHostIntegTests.java:295)
```

Which seems to be failing on:

```java
            {
                httpGet.reset();
                Future<HttpResponse> future = client.execute(httpHost, httpGet, null);
                assertFalse(httpGet.isAborted());
                httpGet.abort();
                assertTrue(httpGet.isAborted());
                try {
                    assertTrue(future.isCancelled()); // <---- here
                    future.get();
                    throw new AssertionError("exception should have been thrown");
                } catch(CancellationException e) {
                    //expected
                }
            }

```

**Comment by ywangd** [comment]
A new failure on this method, but this time it is about suite timeout. It could be just a temporary issue and not related. But since we have an open issue for this method, I am linking it here just in case : https://gradle-enterprise.elastic.co/s/7ohuxbptlyo2e (7.x on darwin)
