### ISSUE TITLE
geo_polygon not handling polygons that cross the date line properly

### ISSUE THREAD

**Issue by pablocastro** [elastic/elasticsearch#5968]
Using Elasticsearch 1.1.1. I'm seeing geo_polygon behave oddly when the input polygon cross the date line. From a quick look at GeoPolygonFilter.GeoPolygonDocSet.pointInPolygon it doesn't seem that this is explicitly handled. 

The reproduce this create an index/mapping as:

POST /geo

``` json
{ "mappings": { "docs": { "properties": { "p": { "type": "geo_point" } } } } }
```

Upload a document:

PUT /geo/docs/1

``` json
{ "p": { "lat": 40, "lon": 179 } }
```

Search with a polygon that's a box around the uploaded point and that crosses the date line:

POST /geo/docs/_search

``` json
{
  "filter": { "geo_polygon": { "p": { "points": [
      { "lat": 42, "lon": 178 },
      { "lat": 39, "lon": 178 },
      { "lat": 39, "lon": -179 },
      { "lat": 42, "lon": -179 },
      { "lat": 42, "lon": 178 }
  ] } } }
}
```

ES returns 0 results. If I use a polygon that stays to the west of the date line I do get results:

``` json
{
  "filter": { "geo_polygon": { "p": { "points": [
      { "lat": 42, "lon": 178 },
      { "lat": 39, "lon": 178 },
      { "lat": 39, "lon": 179.5 },
      { "lat": 42, "lon": 179.5 },
      { "lat": 42, "lon": 178 }
  ] } } }
}
```

Also, if I use a bounding box query with the same coordinates as the initial polygon, it does work:

``` json
{
  "filter": { "geo_bounding_box": { "p": 
    { "top_left": { "lat": 42, "lon": 178 },
       "bottom_right": { "lat": 39, "lon": -179 }
     }
  } }
}
```

It seems that this code needs to either split the check into east and west checks or normalize the input values. Am I missing something?

**Comment by jtibshirani** [comment]
I tried @pablocastro's example on trunk, and unfortunately the issue is still there. There might've been some confusion -- the original example refers to the geo_polygon filter, whereas @nknize's fix is for the polygon geo_shape type.

Should I create a new ticket for the geo_polygon filter, or should we re-open this one?

**Comment by nknize** [comment]
Good catch @jtibshirani!  We'll go ahead and reopen this ticket since its a separate issue.

**Comment by nknize** [comment]
Reopening due to #9462

**Comment by ogerman** [comment]
The search hits of really huge polygon (elasticsearch 1.4.3)
```javascript
{
  "query": {
    "filtered": {
      "filter": {
        "geo_shape": {
          "location": {
            "shape": {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    -70.4873046875,
                    79.9818262344106
                  ],
                  [
                    -70.4873046875,
                    -28.07230647927298
                  ],
                  [
                    -103.3583984375,
                    -28.07230647927298
                  ],
                  [
                    -103.3583984375,
                    79.9818262344106
                  ],
                  [
                    -70.4873046875,
                    79.9818262344106
                  ]
                ]
              ],
              "orientation": "ccw"
            }
          }
        }
      }
    }
  }
}
```
doesn't include any points inside that polygon even with orientation option.
Is it related with this issue?

**Comment by nknize** [comment]
Its related.  For now, if you have an ambiguous poly that crosses the pole you'll need to manually split it into 2 separate explicit polys and put inside a ```MultiPolygon```  Depending on the complexity of the poly computing the pole intersections can be non-trivial.  The in-work patch will do this for you.

A separate issue is related to the distance_error_pct parameter.  If not specified, larger filters will have reduced accuracy.  Though this seems unrelated to your GeoJSON

**Comment by nknize** [comment]
relates to #26286

**Comment by nknize** [comment]
closing in favor of #26286 since its an old issue
