### ISSUE TITLE
CCS IndexNotFound Exception when disable remote_connect

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#59683]
Reproduced both on 7.3.1 and 7.8.0.

According documentation:
```
node.remote_cluster_client
By default, any node in the cluster can act as a cross-cluster client and connect to remote clusters. The node.remote_cluster_client setting can be set to false (defaults to true) to prevent certain nodes from connecting to remote clusters. Remote cluster requests must be sent to a node that is allowed to act as a cross-cluster client.
```
When configure some nodes, like data node, set `node.remote_cluster_client` to `false` in 7.8 or set `cluster.remote.connect` to `false`  in 7.3, the remote clusters was not working as expected, and if you run query against the remote cluster, it will randomly get `index_not_found_exception`, as below:
![CCS-roundrobin-index-not-found](https://user-images.githubusercontent.com/64487/87624429-58432180-c75a-11ea-9433-962a553e652a.gif)

seems those remote requests are still routing to these nodes and this doesn't work as expected, these nodes should be skipped i guess.

But if you check the log, it says `password authentication failed for elastic`,
<img width="752" alt="Jietu20200714-213301" src="https://user-images.githubusercontent.com/64487/87624473-77da4a00-c75a-11ea-9535-972d6994fa22.png">

And also this issue happens in proxy mode as well.

Another side effect on Kibana:
- Monitoring page refused to display, says permission error.
- Remote clusters page lost/disappear the data.

**Comment by dnhatn** [comment]
@medcl Can you share the stacktrace?

**Comment by medcl** [comment]
@dnhatn what kind of stacktrace you need? the original environment is gone now.

**Comment by dnhatn** [comment]
@medcl It's a CCS, not CCR issue(The CCR label confused me). We need to reroute CCS requests to nodes that have the remote_cluster_client role.

**Comment by medcl** [comment]
@dnhatn Sorry for the confusion, you are right, it is a CCS issue. :)
it should not reroute requests to the nodes which remote connect was not enabled, but seems it does.

**Comment by dnhatn** [comment]
@medcl No worry. Thanks for reporting the bug :).
