### ISSUE TITLE
Packer cache script fails due to deprecated Gradle usages

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#59743]
The [builds which run our `packer_cache.sh` script](https://infra-ci.elastic.co/job/elastic+infra+master+packer-cache-elasticsearch-ci-linux/BUILDER=gcp,BUILD_OS=sles-15,label=linux%20&&%20immutable%20&&%20docker/147/console) are failing after merging in #59598. These builds run the `resolveAllDependencies` task which likely is tripping some usage of deprecated configurations.

We could either a) change `resolveAllDependencies` such that it doesn't resolve these configurations or b) override the deprecation failure setting in `packer_cache.sh` to just ignore/warn instead of fail.

Attached is a log that's actually readable since the one in Jenkins is completely incomprehensible and these builds don't produce a build scan for some reason.
[packer_cache_failure.log](https://github.com/elastic/elasticsearch/files/4935582/packer_cache_failure.log)

**Comment by mark-vieira** [comment]
@breskeby do you mind taking a look at this? The CI image builds are failing due to our enforcement of deprecated usages. Simplest thing might just be to make these lenient.

**Comment by breskeby** [comment]
On it

René Gröschke
@breskeby
