### ISSUE TITLE
EQL: Expand case sensitive queries

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#59754]
While doing performance testing, we discovered some cases where the mapping caused case sensitive/insensitive queries to fail. Due to the large volume of work it is unclear what failed - maybe it was a mapping issue, maybe a bug in how the queries get generated.
In the future, it would be useful to see whether we can validate such cases so instead of the query failing silently, we can verify that we can properly execute it.

/cc @matriv

**Comment by matriv** [comment]
Currently Equals & NotEquals doesn't seem to take into account the case insensitivity, so while python will match events with case INsensitivity when using something like `myField = 'vaLUe'` (provided that caseInsensitive flag is correctly set), ES EQL will always be case sensitive.

If we want to match in a case insensitive manner we have to lowercase the field -> painless -> slower queries.

**Comment by rw-access** [comment]
Related #56771 and #53603

**Comment by costin** [comment]
Superseded by #62255
