### ISSUE TITLE
EQL: Better abstraction for logical/physical plans

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#59765]
The current model for EQL plans can be improved as in some cases, it is a bit low-level.
For example why EQL has support for `sort`, each query by default a `head` or `tail` position which is added through `LogicalPlanBuilder`.
This impacts the way matching is done, either `ASC` and `DESC` which influences the relationship between sequence queries (which are by `search_after` queries). This is currently done in the optimizer by looking at a query order but be better encapsulated so it doesn't _leak_ out.
Limit is also manually managed - on an event query it is applied directly on the query but for a sequence, it gets replaced with a `fetch_size` limit, while the limit itself sits at the top.
While there is nothing wrong with the approach, the fact that these details leak is a problem since it's a mixture of concern - the logical plan contains execution details which should belong in the physical plan.

This might cause some rules to be moved around and potentially a physical plan optimizer to be added.

**Comment by wchaparro** [comment]
Superceded by ES|QL
