### ISSUE TITLE
EQL: Basic EQL queries return `hits.events.<num>.fields` property if timestamp is not `epoch_millis`

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#59779]
If an index's timestamp field does not use the `epoch_millis` format, basic EQL queries return the timestamp as a `epoch_millis` value in the response's `hits.events.<num>.fields` property.

This property is not returned for sequence queries.

We currently hide this property in our docs. We should either remove the property or document it.

## Example

Index a doc.
```
PUT /my_index/_bulk?refresh
{"index":{ }}
{ "@timestamp": "2020-12-07T11:07:08.000Z" }
```

Run a basic EQL query.
```
GET /my_index/_eql/search
{
  "query": """
    any where true
  """
}
```
The response includes the `hits.events.0.fields` property.
```
{
  "is_partial" : false,
  "is_running" : false,
  "took" : 37,
  "timed_out" : false,
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "events" : [
      {
        "_index" : "my_index",
        "_id" : "3yYqXXMBNQmfUvpj29G1",
        "_score" : null,
        "_source" : {
          "@timestamp" : "2020-12-07T11:07:08.000Z"
        },
        "fields" : {
          "@timestamp" : [
            "1607339228000"
          ]
        }
      }
    ]
  }
}
```

**Comment by costin** [comment]
Thanks - this is a side-effect of #59764. Essentially when passing the search results verbatim, they end up exposing more information than that of the source. Currently some of that is cleaned-up however going forward it would just be easier to move away from `SearchHit` all together.
