### ISSUE TITLE
"_msearch" does not accept "_source" and "stored_fields" parameters

### ISSUE THREAD

**Issue by soroushtaheri** [elastic/elasticsearch#59841]
Yesterday I wanted to use "_source" and "stored_fields" in my "_msearch" request but looks like they are not supported in the header section. I tried to read issues similar to my situation and I found [this message](https://github.com/elastic/elasticsearch/issues/4227#issuecomment-548222055) from @zacharymorn. As far as I am aware, there have been some updates in order to fix this issue but it looks like there are some parameters that still are not supported in "_msearch" request. (in my case, "_source" and "stored_fields")
I would like to know if there is any particular reason behind not implementing this feature or simply there hasn't been enough time to fix the issue.

**Comment by jimczi** [comment]
`_source`  and `stored_fields` can be set in the body section of the _msearch request so we don't consider this as an issue. 
Considering the custom format that `_msearch` uses, the header section is generally for options that cannot be set in the body. Is there a particular reason why you would like to set these options in the header and not in the body ?

**Comment by soroushtaheri** [comment]
As I normally use `_source` and `stored_fields` in the **header** section of a `_search` request and also based on the documentation for Multi Search API, I thought I should do the same when using `_msearch`. But apparently, as you just said, using them in the body section works perfectly (and I wasn't aware of that, I have no idea why ...).
So I believe my problem is solved now. Thanks for your response, Jim.
