### ISSUE TITLE
QL: Push isCaseSensitive handling down to Configuration

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#59899]
Related to #54411

There was a repeated pattern we kept running into when adding case handling (sensitivity/insensitivity toggles) to QL and EQL functions. We generally would make the relevant QL functions case sensitive, then we would subclass and change the handling.

It's an odd pattern, and we could instead make the Configuration provide `isCaseSensitive()`, defaulting to `true`, and refer to it when determine which mode to handle a function. I think it simplifies the code a bit and makes it easier to extend to new functions.

**Comment by costin** [comment]
Not needed anymore - closed by https://github.com/elastic/elasticsearch/issues/62949.
