### ISSUE TITLE
Many endpoints require a GET request with data in the body: this is a dissonance with respect to the HTTP spec

### ISSUE THREAD

**Issue by Uzay-G** [elastic/elasticsearch#59910]
Many endpoints of the elasticsearch api (ex: https://www.elastic.co/guide/en/elasticsearch/reference/current/run-a-search.html#run-request-body-search) require the user to send data through the GET body.

Roy Fielding, one of the authors of the HTTP spec, has said:

>  In other words, any HTTP request message is allowed to contain a message body, and thus must parse messages with that in mind. Server semantics for GET, however, are restricted such that a body, if any, has no semantic meaning to the request. The requirements on parsing are separate from the requirements on method semantics.
> So, yes, you can send a body with GET, and no, it is never useful to do so.

The request body for a GET request should **not** be useful, and this way of passing data can even damage certain projects. Foe example, this is literally **impossible** in browser js (see https://stackoverflow.com/questions/54810942/send-a-get-request-with-a-body-in-javascript-xmlhttprequest).

The only solution in this case is to use a proxy server endpoint and then pass that to elasticsearch.

Please review this design decision and maybe consider using a POST or other alternative.

I understand the logic, you specify which data you want to `GET`, but it is extremely limiting with regards to many different http implementations like JavaScript's.

Thank you.

**Comment by pugnascotia** [comment]
@Uzay-G All our search APIs also support the `POST` method, so you're not required to use `GET`. However, removing `GET` at this point would be time-consuming and quite painful, so thank you for taking the time to raise an issue, but I'm going to close this issue.
