### ISSUE TITLE
Highlighting should leverage the new field retrieval API

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#59931]
In #55363 we're adding a core functionality to retrieve field content from the mappings. Today highlighting is limited to fields that are contained in the `_source` or stored explicitly. Switching to the new API would allow to highlight alias, copy_to and multi-fields seamlessly without requiring the targeted field to be included in the `_source`. As such, this issue can be seen as a follow up of #55363, for internal usage we should use this generic API since it provides a nice abstraction for field retrieval in general. Note that this issue is different than #5172 which is an high hanging fruit and would require changes in the highlighter.

**Comment by jimczi** [comment]
Highlighting already work for multi-fields and aliases so the switch would only be helpful to retrieve the content of copied fields (the source of the `copy_to`). Sorry for the confusion. However, that alone would be a nice addition since we don't want users to rely on `stored` fields just for highlighting.

**Comment by jtibshirani** [comment]
I really like that this change would reduce the need for stored fields -- users sometimes set `store: true` on a text field just so highlighting will capture the `copy_to` content.
