### ISSUE TITLE
Rename `binary_soft_classification` to `outlier_detection`

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#59947]
There is confusion in the Evaluate API between `classification` and `binary_soft_classification` terms (the user may be confused which one of these two should they be using in a particular case).
As `binary_soft_classification` is used as means to evaluate outlier detection analysis, we should rename `binary_soft_classification` to `outlier_detection`.

Note: Ultimately, we may want to be able to perform all kinds of classification-related evaluations (binary vs multi-class, soft vs hard) using `classification` evaluation stanza. But for now simply introducing 1:1 mapping between analyses names and evaluations names should increase API understandability for the users

**Comment by droberts195** [comment]
Fixed by #59951
