### ISSUE TITLE
Optionally disallow dynamic field access in script

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#60002]
For validation of runtime field script and cycle detection, add the ability to reject dynamic script access.

We can do this in phases if necessary, first only allow string constants, then relax to allowing read-only variables, finally relax to variables that only use constant strings.

We also have to handle doc being assigned to another variable, we can disallow it #60001 temporarily.

Related: #59332

**Comment by stu-elastic** [comment]
@nik9000 is this still a priority for runtime fields?

**Comment by nik9000** [comment]
Nah. We have very low overhead runtime detection for cycles in scripts and its always on. No need for this.

**Comment by stu-elastic** [comment]
ty, sir.
