### ISSUE TITLE
manage_pipeline requires nodes info privilege to create pipeline

### ISSUE THREAD

**Issue by jgowdyelastic** [elastic/elasticsearch#60041]
A user assigned the privilege `manage_pipeline` or the role `ingest_admin` is not able to create a new ingest pipeline without also having the privilege `cluster:monitor/nodes/info`

**Comment by droberts195** [comment]
It was agreed on Slack that this is a bug.

I will open a PR to add the missing permission for 7.9.  Not fixing it causes a very slight breaking change for the ML file data visualizer in 7.9 as we've moved most of the ML UI to using Kibana privileges.

**Comment by droberts195** [comment]
There's been a change of plan.  Instead of modifying the permissions I'll change the put pipeline action to call get nodes info in the system context.  It's an internal implementation detail that the user shouldn't be aware of.
