### ISSUE TITLE
Commercially Support Elasticsearch on SUSE Linux Enterprise 15 

### ISSUE THREAD

**Issue by ktate-suse** [elastic/elasticsearch#60101]
A number of SUSE customers who run Elasticsearch on SUSE Linux Enterprise 12 want to move up to SLES 15. They are asking for Elasticsearch commercial support on SLES 15. SUSE doesn't deliver this support. The Elastic teams do. 
The SUSE Technology Partners team would like to work with the Elasticsearch development team get SLES 15 integrated into their regular QA testing and support cadence so they can support our joint customers.
The most immediate customer who asked us to file this is a very large customer in Switzerland.

**Comment by ktate-suse** [comment]
Is there any update on this request?

**Comment by rjernst** [comment]
We've actually been testing SLES 15 since last year, and have now added it to our [official support matrix](https://www.elastic.co/support/matrix) for 7.9.x.

**Comment by ktate-suse** [comment]
Thanks so much. Our mutual customer will be very happy!
