### ISSUE TITLE
Search - Should wildcard field regex queries be subject to the ALLOW_EXPENSIVE_QUERIES flag?

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#60139]
Currently the wildcard field, like the keyword field prohibits the use of range and regexp queries if the ALLOW_EXPENSIVE_QUERIES flag is set to false.
Arguably the wildcard field should be faster than the worst-case keyword search (a linear scan of all unique values) but can still be slow if the number of docs containing the matching values is high.

It's therefore unclear if we consider the wildcard field should be considered expensive for these queries.

The wildcard field doesn't test this flag for wildcard, range or prefix queries so at the least there is some inconsistency in the logic between query types. The keyword field assumes range, regexp, fuzzy and prefix are all expensive.

**Comment by jpountz** [comment]
+1 to not make them subject to this flag. The execution model of these queries is similar to phrases, which are not affected by this flag today, so I don't think these queries should be disabled by this flag.
