### ISSUE TITLE
 Why is the coordination node unavailable and returns topn data

### ISSUE THREAD

**Issue by wujieaiyan** [elastic/elasticsearch#60186]
When searching across clusters, each coordinating node will return the buket size, whether there can be a parameter to control the coordinating node to return topn pieces of data

Is it possible

![image](https://user-images.githubusercontent.com/22367785/88517224-1c913d00-d021-11ea-984f-ae64cea6bf9e.png)

![image](https://user-images.githubusercontent.com/22367785/88517102-ea7fdb00-d020-11ea-9660-b0becd4d7ced.png)

**Comment by jimczi** [comment]
@wujieaiyan can you explain why such option would be needed ? I don't see how it is different from the final `size` parameter ? Maybe a small example might help ?

**Comment by wujieaiyan** [comment]
@jimczi For example, I want to query the data of 3 clusters. The bucket size of the coordination node aggregation of each cluster is 100w, and the return of 3 clusters is 300w. I want each cluster to return 100 pieces of data, so that finally 300 pieces of data are returned to Query the nodes and aggregate again to get the first 10 pieces of data I want. In this way, the pressure of aggregation can be distributed to the coordinating nodes of each cluster instead of querying nodes.

**Comment by nik9000** [comment]
We have a [TODO](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java#L285) around pruning the terms aggregation results when performing a partial reduce that relates to this.

For what is worth we perform a partial reduction when before returning cross cluster search results if you set `ccs_minimize_roundtrips`. We just don't prune the terms after that. I think *that* pruning is probably what you are looking for.

**Comment by wujieaiyan** [comment]
I have multiple clusters and need to query across clusters. The ccs_minimize_roundtrips parameter can only control whether the coordination node is aggregated, but it cannot confirm how many items the coordination node returns after aggregation.

**Comment by jimczi** [comment]
Thanks for explaining @wujieaiyan . I'd like to understand better why you think that this change would improve performance. Did you see a bottleneck in the coordinating node when using a bigger `shard_size` ? Merging `terms ` aggregation should be a linear operation so I am not sure that there's a big difference when returning a few more `terms` per shards. Did you compare setting `shard_size` to 100 vs the default value ?

**Comment by wujieaiyan** [comment]
@jimczi If each coordination node of three clusters returns 100W, then the query node will have 300W data. I think we should add a parameter to control the coordination node to return topn

**Comment by jimczi** [comment]
Sure I understand the feature request but what I'd like to see are evidences that this is more effective than playing with the existing `shard_size` option.

**Comment by wchaparro** [comment]
Closing, no evidence to support this feature request.
