### ISSUE TITLE
Explain index.number_of_routing_shards for splitting

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#60182]
This setting is mentioned in the [split docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-split-index.html#), but nowhere else that I can find. It feels like it should be mentioned [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings), or perhaps given a practical example in the split docs?

One thing that's worth adding as well, is that you cannot change `number_of_routing_shards` on an open index.

**Comment by jrodewig** [comment]
@markwalkom I've opened #60311, which should address most of this feedback. Can you elaborate a bit more on this:

> perhaps given a practical example in the split docs?

There is an example in the split API description:
https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-split-index.html#split-index-api-desc

Is there anything in that example that seems impractical or unrealistic? It seemed adequate to me, but I may be missing something. Thanks!

**Comment by markwalkom** [comment]
Thanks @jrodewig.
When I meant practical example, I was thinking about a mapping one at index creation, rather than a breakdown of the maths. Your changes make it a lot clearer though!

**Comment by jrodewig** [comment]
Ah. I see. I can add an index creation example to illustrate. Thanks!
