### ISSUE TITLE
Delete By Query under heavy indexing load causes OOM errors

### ISSUE THREAD

**Issue by xyu** [elastic/elasticsearch#6025]
Hello,

We are running an ES 1.1.1 cluster and when we bulk index into it with a high write load we have found that it can trigger OOM errors if we run deletebyquery calls. The symptoms of the problems appears to be the following:

1. Index into the cluster with a heavy write load, this will cause merges to pile up. During the pileup the merge thread pool queue goes up and stays at ~120 per node. (Maybe related to #5779?)
1. Merges are no longer able to keep up with new segments created from indexing operations and segments per node shoots up. (We have seen over 30k segments per node.)
1. Long GC cycles are triggered which may or may not cause the node to drop out of the cluster.
1. When a Delete By Query call is issued an internal refresh is triggered (#3593) which fails due to an out of memory error and causes the node to be removed from the cluster for not responding. (See [gist](https://gist.github.com/xyu/4ca1ddb56200479a07d7) for logs. In this example es13.iad sends a call to es13.sat which experiences OOM causing es13.iad to remove it from the cluster.)

Please let me know if there are any other info I can provide that may be helpful.

**Comment by mikemccand** [comment]
Alas, deleteByQuery is not throttled when merges are falling behind.

**Comment by mikemccand** [comment]
I'll make this operation throttled like we do for index/create ops.

However I'm doubtful this is "enough" to always prevent segment explosion, i.e. https://github.com/elasticsearch/elasticsearch/issues/7052 is a better (trickier) long term solution.

**Comment by s1monw** [comment]
@mikemccand can we close this?

**Comment by mikemccand** [comment]
Yeah, I'll close it ... I think you can still easily provoke OOME on 1.6, but in 2.0 we are switching to a plugin that runs scan/scroll query and then bulk delete the resulting IDs, which does fix it.
