### ISSUE TITLE
Add support for maximumSouldMatch in bool query

### ISSUE THREAD

**Issue by raderio** [elastic/elasticsearch#60296]
Sometimes we need to have possibility to choose the first/one field that satisfy the condition.
This can be solved by addind `maximumSouldMatch` same as already exists `minimumSouldMatch`.

**Comment by jimczi** [comment]
I am not sure I understand what you're asking for. Can you explain what you're trying to achieve with a concrete example ? From the description it seems like a `minimum_should_match` of 1 should be enough to do what you want ?

**Comment by raderio** [comment]
For example I have a list of documents
```
[
  {
    "shortName": "CA",
    "longName": "California"
  },
  {
    "shortName": "New York",
    "longName": "New York"
  },
]
```
So, when I search for "New York" I want to match only 1 field, not both, this is why we I need `maximumSouldMatch`

**Comment by jimczi** [comment]
You can use a [disjunction max query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html) to achieve this
We reserve github for verified bugs and feature requests so I hope you don't mind if I close this issue. The [forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) is better suited for this kind of question. I'd be happy to continue the discussion there, we can open a feature request if we cannot find a way to solve your problem but currently it looks like an [XY problem](https://en.wikipedia.org/wiki/XY_problem) to me.
