### ISSUE TITLE
Elasticsearch add parameters

### ISSUE THREAD

**Issue by wujieaiyan** [elastic/elasticsearch#60366]
Why the data obtained after adding a parameter is misplaced and wrong
![image](https://user-images.githubusercontent.com/22367785/88778577-45e5d080-d1bb-11ea-8a1b-084645800f76.png)
![image](https://user-images.githubusercontent.com/22367785/88778624-51d19280-d1bb-11ea-9422-1d8b5ab91b92.png)

**Comment by cbuescher** [comment]
This is erroneously tagged as a test failure which should be used only for our internal CI tests.
I'm unsure what this issue is about. @wujieaiyan could you please clarify your problem?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @wujieaiyan if you have the requested information please add it in a comment and we can look at re-opening this issue.
