### ISSUE TITLE
DocsClientYamlTestSuiteIT timing out on Darwin

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#60365]
The docs suite seems to occasionally time out on Darwin (default suite timeout is 30 minutes) as it's executing too slowly.

Build scan: https://gradle-enterprise.elastic.co/s/llofljhvauztu/console-log/raw

Relevant output:

> WARNING: Suite execution timed out: org.elasticsearch.smoketest.DocsClientYamlTestSuiteI

Relates https://github.com/elastic/elasticsearch/issues/58286

**Comment by rjernst** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/58286
