### ISSUE TITLE
ssl received a record that exceeded the maximum permissible length

### ISSUE THREAD

**Issue by LONGLEECH** [elastic/elasticsearch#60438]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Centos 7 3.10.0-1127.13.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:  ssl received a record that exceeded the maximum permissible length

**Steps to reproduce**:  

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. curl --cacert /etc/elasticsearch/certs/ca.crt -XGET https://1.x.x.x:9200/_cat/nodes?pretty
Ouput: curl: (35) SSL received a record that exceeded the maximum permissible length.
 2. /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
Output: SSL connection to https://1.x.x.x:9200/_security/_authenticate?pretty failed: Unsupported or unrecognized SSL message
Please check the elasticsearch SSL settings under xpack.security.http.ssl.
ERROR: Failed to establish SSL connection to elasticsearch at https://1.x.x.x:9200/_security/_authenticate?pretty.
 3.

**Provide logs (if relevant)**:

**Comment by original-brownbear** [comment]
@LONGLEECH thanks for bringing this up. Could you give us a little more information about your setup please?

1. Are all the APIs broken or just those endpoints in your report?
2. Are there any errors logged by ES?
3. For the broken endpoints, do they work from e.g. a browser?

**Comment by tvernum** [comment]
@LONGLEECH What does your `elasticsearch.yml` look like?

That `elasticsearch-setup-passwords` error can be easily reproduced if you try to access as non-SSL node using `https`. If the config that `elasticsearch-setup-passwords` is using isn't the same config that the node is running with (because it's out of date, or you have 2 different yml files), you would experience that error.

**Comment by original-brownbear** [comment]
Closing this due to a lack of feedback.
