### ISSUE TITLE
Manage the synonym file like we manage an index

### ISSUE THREAD

**Issue by gitterhh** [elastic/elasticsearch#60449]
Managing the synonyms by files is somehow cumbersome. 
It will be more convenient to mange the synonyms data like we manage an index.

Related to https://github.com/elastic/elasticsearch/issues/25189

**Comment by cbuescher** [comment]
I think this ties into https://github.com/elastic/elasticsearch/issues/38523, would you mind if I close this as a duplicate?

**Comment by gitterhh** [comment]
Yes, I agree.
