### ISSUE TITLE
SecurityWithBasicLicenseIT.testWithBasicLicense failed

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#60519]
**Build scan**:
https://gradle-enterprise.elastic.co/s/fr4mt4blht7u4

**Repro line**:
`./gradlew ':x-pack:plugin:security:qa:security-basic:integTestRunner' --tests "org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.testWithBasicLicense" -Dtests.seed=8896CF1F5831ADCC -Dtests.security.manager=true -Dtests.locale=be -Dtests.timezone=Asia/Manila -Druntime.java=11`

**Reproduces locally?**: No.

**Applicable branches**: master

**Failure history**:
https://build-stats.elastic.co/goto/bf6148253b0eb65ed4ae64112b8a4ce7

**Failure excerpt**:
```

org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT > testWithBasicLicense FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:36021], URI [/_license], status line [HTTP/1.1 404 Not Found] |  
  | { } |  
  | at __randomizedtesting.SeedInfo.seed([8896CF1F5831ADCC:9E1C8AAED47D5688]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) |  
  | at org.elasticsearch.test.rest.ESRestTestCase.getAsMap(ESRestTestCase.java:1185) |  
  | at org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.checkLicenseType(SecurityWithBasicLicenseIT.java:81) |  
  | at org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.testWithBasicLicense(SecurityWithBasicLicenseIT.java:31)

```

Fails mostly on master but failed a few times also in 7.x branches.

**Comment by ywangd** [comment]
This is another variant of the same issue similar to #60468 and #59157. I have a working PR (#60498) for fix.
