### ISSUE TITLE
AllocationRoutedStepTests.testExecuteAllocateNotComplete fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#60520]
**Build scan**:
https://gradle-enterprise.elastic.co/s/wxfwotvgopwai

**Repro line**:
`./gradlew ':x-pack:plugin:core:unitTest' -Dtests.seed=F9038A75D04CA8E3 -Dtests.class=org.elasticsearch.xpack.core.indexlifecycle.AllocationRoutedStepTests -Dtests.method="testExecuteAllocateNotComplete" -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=America/Dawson_Creek -Dcompiler.java=12 -Druntime.java=8`

**Applicable branches**: any including 6.8

**Failure history**:
https://build-stats.elastic.co/goto/431253d63db35a0d1ec9008ba182170e

**Failure excerpt**:
Waiting for [1] shards to be allocated to nodes matching the given filters","shards_left_to_allocate":1,"all_shards_active":true,"actual_replicas":0}> but was:<{"message":"Waiting for [2] shards to be allocated to nodes matching the given filters","shards_left_to_allocate":2,"all_shards_active":true,"actual_replicas":0

**Comment by andreidan** [comment]
We have additional logging in place if this flakes again, but the test has been running in CI for months without any failure. Closing this for now.
