### ISSUE TITLE
[DOCS] Document search-ability of meta fields

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#60553]
In some cases, [meta fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html) can be searched, for example `"exists": { "field": "_routing" }`.  We should update our documentation somewhere (if it doesn't exist already) to indicate that this is reliable.

**Comment by jrodewig** [comment]
As @jtibshirani pointed out in #60765, the search-ability of a metadata field is noted in the docs for that field. For example, the `_id` field lists its supported queries: https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-id-field.html
