### ISSUE TITLE
[CI] MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#60587]
Failure snippet:

```
org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT > testRerouteOccursOnDiskPassingHighWatermark FAILED |  
-- | --
  | java.lang.AssertionError: node2 has at least 3 shards |  
  | Expected: a value equal to or greater than <3> |  
  | but: <0> was less than <3> |  
  | at __randomizedtesting.SeedInfo.seed([BD7A2AE4A45BDB1D:D94F442D7ACD8FF4]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.lambda$testRerouteOccursOnDiskPassingHighWatermark$6(MockDiskUsagesIT.java:138) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924) |  
  | at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark(MockDiskUsagesIT.java:134)
```

Reproduce line: `./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark" -Dtests.seed=BD7A2AE4A45BDB1D -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Africa/Tunis -Druntime.java=8`
This does not reproduce.

Only appears to have failed on the 7.x branch since July 25.

Build url: https://gradle-enterprise.elastic.co/s/supfvdigtgpsq/tests/:server:internalClusterTest/org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT/testRerouteOccursOnDiskPassingHighWatermark#1

Failure history: https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT&tests.sortField=FAILED&tests.test=testRerouteOccursOnDiskPassingHighWatermark&tests.unstableOnly=true

**Comment by DaveCTurner** [comment]
Haven't been able to reproduce this locally after many iterations. I opened https://github.com/elastic/elasticsearch/pull/60817 to add some more detailed logging here.

**Comment by DaveCTurner** [comment]
```
  1> [2020-08-08T13:24:25,108][DEBUG][o.e.c.r.a.DiskThresholdMonitor] [testRerouteOccursOnDiskPassingHighWatermark] 5rKSAdkHSAeIJxWplRiM1w has gone below a disk threshold, but an automatic reroute has occurred in the last [1ms], skipping reroute
```

I opened #60869 to address this.
