### ISSUE TITLE
AD Kerberos auth on HDFS Repo uses sAMAccountName on Java 14

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#60628]
When running HDFS Repository on the packaged Java 14 distribution, authentications against Active Directory's Kerberos server will change the original principal name to that principal's sAMAccountName. This seems to be due to a JDK bug introduced in Java 13 [JDK-8215032](https://bugs.openjdk.java.net/browse/JDK-8215032) which was previously reported and should be fixed in Java 15 [JDK-8239385](https://bugs.openjdk.java.net/browse/JDK-8239385) (backported to 11.0.2, and 8u241).

Creating or validating an HDFS Repository secured against AD on this version of Java can produce this error response:
```json
{
  "error":{
    "root_cause":[
      {
        "type":"unchecked_i_o_exception",
        "reason":"unchecked_i_o_exception: Cannot create HDFS repository for uri [hdfs://namenode.uri]"
      }
    ],
    "type":"repository_exception",
    "reason":"[node] cannot create blob store",
    "caused_by":{
      "type":"unchecked_i_o_exception",
      "reason":"unchecked_i_o_exception: Cannot create HDFS repository for uri [hdfs://namenode.uri]",
      "caused_by":{
        "type":"i_o_exception",
        "reason":"User: $XXXXXX-XXXXXXXXXXXX@FQDN.REALM is not allowed to impersonate elasticsearch/HOST@FQDN.REALM"
      }
    }
  },
  "status":500
}
```

Enabling krb5 debugging log reveals that Elasticsearch kerberos client performs login against AD Kerberos server and receives an updated principal:
```
[INFO ][stdout                   ] [node] Found ticket for $XXXXXX-XXXXXXXXXXXX@FQDN.REALM to go to krbtgt/FQDN.REALM@FQDN.REALM expiring on <expiration date>
...
[INFO ][stdout                   ] [node] >>> DEBUG: ----Credentials----
[INFO ][stdout                   ] [node] 	client: $XXXXXX-XXXXXXXXXXXX@FQDN.REALM
[INFO ][stdout                   ] [node] 	client alias: elasticsearch/HOST@FQDN.REALM
[INFO ][stdout                   ] [node] 	server: nn/namenode.uri@FQDN.REALM
[INFO ][stdout                   ] [node] 	ticket: sname: nn/namenode.uri@FQDN.REALM
```
This updated principal is the sAMAccountName for the associated principal in Active Directory. The original principal name is persisted as an alias for the principal. Hadoop uses this alias field to support user impersonation, which causes the first authentication attempt to Namenode to fail with the above message, as Namenode is not configured to accept impersonation requests from a principal with the sAMAccountName as the original.

Current Workarounds: Downgrading to a Java 11 version (before 11.0.6 or 11.0.9 and up) should resolve the issue, allowing for the client to correctly resolve the principal during the authentication request.

**Comment by ywelsch** [comment]
Does this require any action on our end, or just wait for newer JDK? Do we have a testing gap here?

**Comment by jbaiera** [comment]
Personally, I feel like it falls into a "known issues" sort of category, with the understanding that when we upgrade to a newer JDK it will no longer be a problem. Though, I wonder if this might be considered an issue with our Kerberos authentication realm as well? Not on the server side, but on the client side?

**Comment by mark-vieira** [comment]
@jbaiera this sounds like it's not a thing anymore given we're bundling Java 21 with Elasticsearch now?

**Comment by jbaiera** [comment]
That is likely the case. It's been a few years so I do not recall the specifics of the problem here. I'd be ok with closing this issue out and reopening if we see any other related issues. Personally, I haven't seen this crop up at all from any users since opening this issue.
