### ISSUE TITLE
dynamic mapping of nest jsonObject make space used increased by 6.5x

### ISSUE THREAD

**Issue by liuxinto01** [elastic/elasticsearch#60637]
**Elasticsearch version** (`bin/elasticsearch --version`):6.2

**Description of the problem including expected versus actual behavior**:

The issue is I applied dynamic mapping into mapping to help index new field, which is a nested jsonObject and child jsonObject's value is geoShape.
After reindex, found that the space consumed by the new index is actually increased by 6.5x which is totally odd.
 

 1. mapping (for dynamic mapping and new field part):
```json
{
   "test_index":{
      "mappings":{
         "_doc":{
            "dynamic":"strict",
            "_routing":{
               "required":true
            },
            "dynamic_templates":[
               {
                  "shapes":{
                     "path_match":"test_field*.*",
                     "mapping":{
                        "precision":"50m",
                        "type":"geo_shape"
                     }
                  }
               }
            ]
         }
      }
   }
}
```
the new field is starting with a default nested field named "default", but we will index new nested jsonObject per custom mapping 
```json
{"test_field": {
            "dynamic": "true",
            "properties": {
             "default":{
                  "precision":"50m",
                   "type":"geo_shape"
                   }
              }
    }
}


```

 2. new fields were indexed successfully like below but sadly the space used by the new index increased by 6.5x, very confusing to me
```json
"test_field": {
            "experiment": {
              "treatment1": {
                "type": "circle",
                "coordinates": [
                  -122.39409,
                  37.7928
                ],
                "radius": 3650
              },
              "treatment2": {
                "type": "circle",
                "coordinates": [
                  -122.39409,
                  37.7928
                ],
                "radius": 3650
              }
            },
            "default": {
              "type": "circle",
              "coordinates": [
                -122.39409,
                37.7928
              ],
              "radius": 3650
            }
          }
```
 3. please advice/help ASA， thanks in advance

**Comment by javanna** [comment]
Apologies, this issue fell through the cracks. It is at this point very difficult to track back what may have caused this issue in 6.2, given it is two major versions ago.
