### ISSUE TITLE
Add Beats metadata processors field mappings to monitoring index templates

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#60646]
At the moment we recommend that users use Metricbeat for monitoring Elasticsearch and other stack products. This results in Metricbeat indexing data into `.monitoring-*` indices. The mappings for these indices are governed by the `monitoring-*.json` index templates defined over here: https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/core/src/main/resources.

When Metricbeat is used in a container environment like Docker or Kubernetes, we recommend that users use Metricbeat's [autodiscover](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html) functionality. With this functionality, certain metadata fields are appended to each indexed document. 

Currently, the mappings defined in the `monitoring-es.json` index templates do not allow such metadata fields. The mappings set `dynamic: false` and do not explicitly define the metadata fields. We should enhance the index templates to include these fields. 

Until we make this change, users are not able to perform Stack Monitoring using Metricbeat with autodiscovery in a container environment.

--- 

In the long term (8.0.0 onwards), the plan is for users to use Agent to monitor stack products, which will result in stack monitoring data being indexed into `metrics-*` data streams. As such, the `.monitoring-*` indices and their index templates will be phased out.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
