### ISSUE TITLE
Painless convenience function for matching IP addresses

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#60668]
Matching an ipaddress to a cidr, canonicalizing IPv6 addresses, stripping low-order bytes from addresses.

Meta: #60659

**Comment by andrewstucki** [comment]
Not sure what the state of this is in terms of prioritization, but it would definitely help on the ingest side of things.

Right now I'm trying to add network direction detection to a good chunk of filebeat modules. Currently with modules that are defined completely in ingest pipelines we have no way of doing CIDR matching to say whether a particular event captures a network request to/from a whitelisted CIDR block range considered inside a DMZ.

**Comment by andrewstucki** [comment]
As far as CIDR inclusion goes, I think that, at least for ingest purposes, supporting something similar to the functionality of the `contains` method from [netty](https://netty.io/3.5/api/org/jboss/netty/handler/ipfilter/CIDR.html) would be sufficient.

So, in the case of doing an ip address check for inclusion in a CIDR blocks. Something to the effect of:

```
def block = new CIDR("192.168.0.0/8");
if (block.contains("192.168.1.1")) {
...
}
```

Alternatively, we could also do something similar to the CIDR matching implementation in EQL. Exposing `CIDRUtils.isInRange` to the execution context seems like it'd be sufficient for most ingest purposes that I can think of:

https://github.com/elastic/elasticsearch/blob/709068da7cf6e11e3148e67eac211a088affce4a/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRUtils.java#L23

**Comment by interpreter95** [comment]
Hi @andrewstucki, just wanted to check if this issue is still active?

If so I could try to implement either of your suggestions (please let me know which one you'd prefer).

Also, is canonicalizing IPv6 addresses and stripping low-order bytes from addresses up for grabs as well?

**Comment by stu-elastic** [comment]
> just wanted to check if this issue is still active?

Hi @interpreter95.  Yes it is.

Go ahead and implement:
```
def block = new CIDR("192.168.0.0/8");
if (block.contains("192.168.1.1")) {
...
}
```

> Also, is canonicalizing IPv6 addresses and stripping low-order bytes from addresses up for grabs as well?

Let's start with `CIDR.contains`.  Since these APIs are long lived (two major revisions to change), we're conservative about adding new ones until we have a strong use case.

**Comment by interpreter95** [comment]
Hi @stu-elastic,

Sorry that I haven't responded in a while.

A question, where should this functionality be located in the repo? I've been thinking for a bit but I'm afraid that I'm too inexperienced to determine whether it's a lib, module or plugin that you want.

Also, I saw that there are two cidr files in the repo which provide similar functionality as what you are describing (I think), namely:

./server/src/main/java/org/elasticsearch/common/network/Cidrs.java
./x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRUtils.java

So I was just wondering if I should implement the functionality from scratch or if I can wrap the functionality provided by these two files to provide the functionality you want?

**Comment by stu-elastic** [comment]
We'd usually put something like this in `./modules/lang-painless/src/main/java/org/elasticsearch/painless/api/`.  Thinking about this more, exposing `isInRange` makes sense.  That's work that'll have to happen on our side.

**Comment by Karrade7** [comment]
if not already included, checking if something is a valid IP (IPv4 or IPv6 )would be helpful. 
for example, isIPv4(foo) returns true if foo ~ /[0-255].[0-255].[0-255].[0-255]/ else false.

use case example for ingest:
set observer.ip = observer.name
conditional: isIPv4(observer.name)

**Comment by interpreter95** [comment]
Hi @Karrade7 ,

I agree and I intend to have an IPv4 check in my initial solution that I'm working on.

I do agree that IPv6 support should also be included but I think that is for a future commit. I prefer to deliver in small increments, so I have constrained the first commit to be IPv4 specific and only implement the necessary functionality of `CIDR.contains`.

However, I see now that @shans96 beat me to it and already have a commit under review implementing the `CIDR.contains` functionality as well as IPv4/6 checking :)

**Comment by shans96** [comment]
Hi @interpreter95, apologies for any inconvenience caused. I haven't implemented direct IPv4/IPv6 checking- the processing code can differentiate between the two types, but there are no methods dedicated just to checking if an IP given is a valid v4 or v6 one. If I understood correctly, some static utility methods could be added to do this, e.g. `boolean isValidIPv4()` and `boolean isValidIPv6()`.

**Comment by interpreter95** [comment]
Hi @shans96, no worries.

Yeah, I think the static utility methods you propose would do the trick.

However, I would recommend doing that in a separate commit (and maybe wait with doing that until you get your commit under review approved) in order to keep the commit sizes to a minimum.

**Comment by interpreter95** [comment]
Hi @shans96 ,

Congratulations on getting #69630 in 🥳

Just wanted to check with you if you're still planning on implementing `boolean isValidIPv4()` and `boolean isValidIPv6()`? Otherwise, I'm interested in getting my hands dirty 😃

**Comment by stu-elastic** [comment]
Re: `isValidIPv4()`, we're trying to be deliberate about adding these functions.

Good evidence for a new function would come from ingest scripts in the wild or other elastic products, for example Logstash has a [Cidr filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-cidr.html).

**Comment by interpreter95** [comment]
Hi @stu-elastic , thanks for the clarification.

Just so I'm on the same page, is the intention of having this issue open for people to request additional functionality?

From what I can tell #71258 will not close this issue, so I'm not sure whether there's additional functionality we already know should be implemented (and that's why this issue will continue to be open) or if this issue serves as a placeholder for people to make requests for additional functionality?

**Comment by stu-elastic** [comment]
> Just so I'm on the same page, is the intention of having this issue open for people to request additional functionality?

I was thinking about that this weekend after responding to you. I'm going to close this issue as done with the CIDR work, as that was the main ask.  Interested users should cut new issues for future work.

If you're interested in contributing, please suggest designs by commenting on some of the issues linked from https://github.com/elastic/elasticsearch/issues/60659.

An good first commit would be whitelisting `java.net.URL`, see https://github.com/elastic/elasticsearch/issues/60660#issuecomment-811452672.  That would consist of adding to the [org.elasticsearch.net.txt](https://github.com/elastic/elasticsearch/pull/71258/files#diff-6696b7c7b491cc5d88d7115088e788be956309a3dd2990a445ab9fac8bf37593) file and adding some tests.
