### ISSUE TITLE
CI: Could not determine the dependencies of task ':qa:os:destructivePackagingTest'.

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#60690]
**Build scan**:
https://gradle-enterprise.elastic.co/s/xs3tglp6yzkzk

**Applicable branches**:
`master`. checking others.

**Failure history**:
Started Aug 4, 2020 1:03:30 AM
**Failure excerpt**:

```
13:07:51 > Task :buildSrc:build
13:08:06 build complete, generating: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob+packaging-tests-unix-gcp/os/oraclelinux-7-packaging/build/210.tar.bz2
13:08:07 
13:08:07 FAILURE: Build failed with an exception.
13:08:07 
13:08:07 * What went wrong:
13:08:07 Could not determine the dependencies of task ':qa:os:destructivePackagingTest'.
13:08:07 > Task with path 'destructiveBatsTest.upgrade' not found in project ':qa:os'.
```

**Comment by andreidan** [comment]
A few more occurrences 
https://gradle-enterprise.elastic.co/s/ncx6sqqsshtsq
https://gradle-enterprise.elastic.co/s/5ydnc47sjfh5g
https://gradle-enterprise.elastic.co/s/24nr7kwtgg4om
https://gradle-enterprise.elastic.co/s/hz22fjlsgpeiq
https://gradle-enterprise.elastic.co/s/24nr7kwtgg4om
