### ISSUE TITLE
Make cluster recovery near instantaneous if all shards are present and accounted for

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#6069]
When restarting a cluster from green state, each shard appears to undergo some form of checksum to verify it before bringing it online.

Is there a way to journal writes so that recovery is much much faster, in the way that the xfs filesystem does it.

Only review the data that was being written to at the time of the outage or shutdown so that only the in-progress write data needs to be checked.

For a clean shutdown, maybe a complete cluster restart command could tell all nodes to shutdown in a clean state then turn off, allowing a near instantaneous recovery on startup. Like stop allocation then flush all translogs, then shut down,etc.

Would just take lots of the pain out of cluster restarts.

Just an idea

**Comment by connieyang** [comment]
We have an Elasticsearch cluster (as part of our ELK stack) in production and have experienced (6+ hours) for the cluster to turn green during a rolling restart.  When will a fix for this be ready?

**Comment by bleskes** [comment]
@connieyang sorry to hear the pain. We are actively working on it. Sadly I can't promise any ETA at the moment.

**Comment by cfeio** [comment]
+1, We are also experiencing pains with cluster recover due to a large cluster size (6 TB cluster). It is taking hours to recover even after a planned maintenance restart.

**Comment by shyem** [comment]
+ 1, same here. With daily index, most of them are unchanged, yet it takes for ever to recover.

**Comment by shyem** [comment]
+1, same here. With daily index, most of them are unchanged, yet it takes for ever to recover.

**Comment by clintongormley** [comment]
Closed by #11336
