### ISSUE TITLE
re open ckp file in every translog sync may be a waste?

### ISSUE THREAD

**Issue by youngzhang26** [elastic/elasticsearch#60702]
https://github.com/elastic/elasticsearch/blob/393ce41740007d4ed0341d2116b8c739974d0f6c/server/src/main/java/org/elasticsearch/index/translog/Checkpoint.java#L191

in my env , open a file cost avg 129us , force just only use avg 102 us , can we open once and update it when rollGeneration?

**Comment by dnhatn** [comment]
@youngzhang26 Thanks for raising this. Do you have a benchmark that shows the indexing improvement with the proposal? If the improvement is trivial, then I think we will not commit the change as the current code is simpler.

**Comment by youngzhang26** [comment]
> @youngzhang26 Thanks for raising this. Do you have a benchmark that shows the indexing improvement with the proposal? If the improvement is trivial, then I think we will not commit the change as the current code is simpler.

i also agree that it will not have a improve . (maybe less that 5%  i will do the benchmark when i have time to do this and give the result)

**Comment by dnhatn** [comment]
I am closing this issue as we agreed that the improvement is small. Thank you for your interest in Elasticsearch.
