### ISSUE TITLE
GET _cat/shards?local and GET _cat/indices?local are not completely local

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#60718]
The cat shards and cat indices APIs perform a `ClusterStateAction` then a `IndicesStatsAction`. They accept the `?local` parameter and passes this to the `ClusterStateAction` but this parameter has no effect on the `IndicesStatsAction`. This is surprising, because `GET _cat/shards?local` and `GET _cat/indices?local` look like they might be completely local calls but in fact they still depend on every data node in the cluster.

I think the `?local` parameter does not make sense on these APIs and we should remove it.

Relates #50088 which is the same issue for `GET _cat/nodes`.

**Comment by boicehuang** [comment]
Do _cat/indices?local have the same behavior?

**Comment by DaveCTurner** [comment]
Yes, `GET _cat/indices?local` is also nonlocal as it also uses a cluster-wide indices stats request.

**Comment by boicehuang** [comment]
May I work on this one?

**Comment by DaveCTurner** [comment]
Sure, go ahead. See #50088 for a good example of deprecating and removing a REST parameter like this.

**Comment by danhermann** [comment]
The local parameters have been deprecated in 7.x and removed for 8.x.
