### ISSUE TITLE
Projecct build error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

### ISSUE THREAD

**Issue by Crab2died** [elastic/elasticsearch#60712]
When Gradle build the Elasticsearch source code, download jars runs error

### Expected Behavior
Gradle download dependency jars

### Current Behavior
```
* What went wrong:
A problem occurred configuring root project 'elasticsearch'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.gradle:build-scan-plugin:2.2.1.
     Required by:
         project : > com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:2.2.1
      > Could not resolve com.gradle:build-scan-plugin:2.2.1.
         > Could not get resource 'https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/2.2.1/build-scan-plugin-2.2.1.pom'.
            > Could not GET 'https://plugins-artifacts.gradle.org/com.gradle/build-scan-plugin/2.2.1/3f7331c5ff5c6809f340f7e64290b654402fb6f8edc3f8f4ce425e17dd202ff1/build-scan-plugin-2.2.1.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Steps to Reproduce 
1. git clone https://github.com/elastic/elasticsearch.git elasticsearch
2.  import https://plugins.gradle.org &  https://jcenter.bintray.com etc.  certification to JAVA_HOME/lib/security/cacerts
     I'm sure the certification added success
3. ./gradlew assemble
   I tried add config -Djavax.net.ssl.trustStore="JAVA_HOME/lib/security/cacerts"
   I also tried add config in gradle.properties
   ```
   systemProp.javax.net.ssl.trustStore=JAVA_HOME/lib/security/cacerts
   systemProp.javax.net.ssl.trustStorePassword=changeit
   ```
   **But still report the same error**

### Your Environment
  Platform: Win10
  JDK: 
     java version "11.0.4" 2019-07-16 LTS
     Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
     Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
  Gradle version: gradle-5.2.1-all.zip

**Comment by JenniferPruitt** [comment]
I noticed that there is a similar problem at https://github.com/tchiotludo/akhq/issues/338. Perhaps we can refer to [this issue](hhttps://github.com/tchiotludo/akhq/issues/338) to find more context about the bug.

**Comment by cbuescher** [comment]
This issue is erroneously tagged as test failure which should be applied for internal CI test failures.
@Crab2died is this still an issue that you can reproduce with the above steps?

**Comment by Crab2died** [comment]
@cbuescher Yes, it can still reproduce

**Comment by cbuescher** [comment]
Thanks, I'm personally not sure if we support the way you are trying to build ES, but maybe somebody from @elastic/es-core-infra can check if this is a problem on our side or not.

**Comment by rjernst** [comment]
@breskeby @mark-vieira Can either of you comment on this workflow?

**Comment by mark-vieira** [comment]
> Gradle version: gradle-5.2.1-all.zip

You mention a pretty old Gradle version, what branch/tag are you attempting to build?

**Comment by breskeby** [comment]
I tried reproducing this on master with no luck (trying with java 11.0.8 hotspot). I mean I imported the certificate for plugins.gradle.org but build went well with resolving the Gradle Enterprise plugin from there. @cbuescher which branch you reproduced this problem on?

**Comment by breskeby** [comment]
@Crab2died can you share which branch you're on and if this is still reproducible with the latest master branch?

**Comment by breskeby** [comment]
Is there a chance this has something todo with trying to build this from china? is there a potential firewall or something that potentially is breaking this?

**Comment by mark-vieira** [comment]
> I tried reproducing this on master with no luck (trying with java 11.0.8 hotspot).

GIven the build scan plugin version and Gradle versions reported this must be `6.8`.

**Comment by Crab2died** [comment]
> @Crab2died can you share which branch you're on and if this is still reproducible with the latest master branch?

7.1 branch

**Comment by mark-vieira** [comment]
Looks like the final failure is with `https://plugins-artifacts.gradle.org`, did you add that cert to your keystore?

**Comment by mark-vieira** [comment]
@Crab2died are you still having this problem?

**Comment by mark-vieira** [comment]
Closing this since there hasn't been any updates.
