### ISSUE TITLE
Force awarness shards wrong assignment

### ISSUE THREAD

**Issue by yu55** [elastic/elasticsearch#6072]
We try to index large database data in our company and we encouter some reliability problems with elasticsearch 1.1.0 and 1.1.1. When we use force awarness option elasticsearch has problems with proper shards allocation and we loose access to some or whole index data.

Below steps to reproduce bug:
1. Prepare two separate linux machines called DC2 and DC4 connected via LAN.
2. On machine DC2 unzip 4 separate instances of elasticsearch 1.1.1 with following configuration:
   
   elastic 1:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC2
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC2_1
   
   elastic 2:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC2
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC2_2
   
   elastic 3:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC2
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC2_3
   
   elastic 4:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC2
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC2_4
3. On machine DC4 unzip 4 separate instances of elasticsearch 1.1.1 with following configuration:
   
   elastic 1:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC4
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC4_1
   
   elastic 2:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC4
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC4_2
   
   elastic 3:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC4
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC4_3
   
   elastic 4:
   cluster.routing.allocation.awareness.force.zone.values: DC2,DC4
   node.zone: DC4
   cluster.routing.allocation.awareness.attributes: zone
   node.name: DC4_4
4. Start all elastics on DC2. 4-node cluster forms properly.
   ![01_empty_dc2_start](https://cloud.githubusercontent.com/assets/1789867/2899770/59ce842c-d5bc-11e3-8ac2-94666fcdd1c5.png)
5. Start all elastics on DC4. 8-node cluster forms properly.
   ![02_empty_dc2_start](https://cloud.githubusercontent.com/assets/1789867/2899787/ac919bae-d5bc-11e3-8d57-970e4149e067.png)
6. Create new empty index (5 shards, 3 replicas). Shards are spread properly across nodes.
   ![03_dc2_up_dc4_up_create_index](https://cloud.githubusercontent.com/assets/1789867/2899788/b2dc9982-d5bc-11e3-87cf-ce19791a2a14.png)
7. Shutdown all elastics on DC4.
   PROBLEM: All shards are assigned to all elastics on DC2. According to force awarness configuration only half of them should be assigned. Shards from DC4 should be unassigned.
   ![04_shutdown_dc4_wrong_assignment](https://cloud.githubusercontent.com/assets/1789867/2899793/c49d0044-d5bc-11e3-8396-ac09a89451c7.png)
8. Shutdown all elastics on DC2.
9. Start all elastics on DC2.
   PROBLEM: All shards are assigned to all elastics on DC2. According to force awarness configuration only half of them should be assigned. Shards from DC4 should be unassigned.
   ![05_start_only_dc2_wrong_assignment](https://cloud.githubusercontent.com/assets/1789867/2899802/d9a37bda-d5bc-11e3-98e7-fb53e22ff9ad.png)
10. Shutdown all elastics on DC2.
11. Start all elastics on DC4.
    PROBLEM: All shards are unassigned. According to force awarness configuration half of them should be assigned. Shards from DC2 should be unassigned.
    ![06_start_only_dc4_wrong_assignment](https://cloud.githubusercontent.com/assets/1789867/2899804/e64738d6-d5bc-11e3-8031-e5b2f2f0a8e7.png)
12. Start all elastics on DC2 - all shards are assigned properly.

Problems in steps 7-11 occure all the time in this index. Sometimes (other but similar index) all shards are unassgined in steps 7 and 9 (just like in step 11).

When shards cannot be assign following lines in log occures:
[2014-05-07 08:21:23,787][DEBUG][gateway.local            ] [DC4_1] [some_index][3]: not allocating, number_of_allocated_shards_found [1], required_number [3]
[2014-05-07 08:21:23,787][DEBUG][gateway.local            ] [DC4_1] [some_index][0]: not allocating, number_of_allocated_shards_found [1], required_number [3]
[2014-05-07 08:21:23,787][DEBUG][gateway.local            ] [DC4_1] [some_index][1]: not allocating, number_of_allocated_shards_found [0], required_number [3]
[2014-05-07 08:21:23,787][DEBUG][gateway.local            ] [DC4_1] [some_index][4]: not allocating, number_of_allocated_shards_found [0], required_number [3]
[2014-05-07 08:21:23,787][DEBUG][gateway.local            ] [DC4_1] [some_index][2]: not allocating, number_of_allocated_shards_found [1], required_number [3]

**Comment by clintongormley** [comment]
As of 5.0, all of these scenarios now work correctly

**Comment by clintongormley** [comment]
thanks @yu55 for the very thorough recreation
