### ISSUE TITLE
fields API fails to return values in an array of objects

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#60743]
There are two different scenarios where this fails, both with the same output. The query used is the same in both cases:
```
{
  "query": {
    "match_all": {}
  },
  "fields": [
    "*"
  ]
}
```

Also, the output is almost the same in both cases, with the exception of the input string being formatted:

```
{
    "error": {
        "root_cause": [
            {
                "type": "number_format_exception",
                "reason": "For input string: \"[[1, 2]]\""
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "test",
                "node": "UysFGHdVSiiHtIR9UgkWmg",
                "reason": {
                    "type": "number_format_exception",
                    "reason": "For input string: \"[[1, 2]]\""
                }
            }
        ],
        "caused_by": {
            "type": "number_format_exception",
            "reason": "For input string: \"[[1, 2]]\"",
            "caused_by": {
                "type": "number_format_exception",
                "reason": "For input string: \"[[1, 2]]\""
            }
        }
    },
    "status": 400
}
```

1. `{"a" : {"b" : [[[1,2]]]}}` error message reason is `"reason": "For input string: \"[[1, 2]]\""`
2. `{"a" : [{"b" : [1,2]}]}` error message reason is `"reason": "For input string: \"[1, 2]\""`

The tests above are for numbers, but for strings there is semi-faulty behavior as well. For a document containing `{"a" : [{"b" : [["x","y"]]}]}` the output of `fields` for `a.b` and `a.b.keyword` is `"[[x, y]]"` I would have expected an array of string values not a string value representing two nested arrays with the two values as a single one.

CC @jtibshirani

**Comment by jtibshirani** [comment]
Thanks @astefan for reporting this, it's a great catch!
