### ISSUE TITLE
[CI] WatcherYamlRestIT.test {p0=watcher/usage/10_basic/Test watcher usage stats output}

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#60757]
**Build scan**:
https://gradle-enterprise.elastic.co/s/jmfsg2cxodr5o

**Repro line**:
```
./gradlew ':x-pack:plugin:watcher:qa:rest:integTest' --tests "org.elasticsearch.smoketest.WatcherYamlRestIT.test {p0=watcher/usage/10_basic/Test watcher usage stats output}" \
  -Dtests.seed=B06F9BA57D069902 \
  -Dtests.security.manager=true \
  -Dtests.locale=fi \
  -Dtests.timezone=JST \
  -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: Master

**Failure history**:

**Failure excerpt**:
```
Caused by: java.lang.AssertionError: field [watcher.count.active] is not greater than [$watch_count_active]
Expected: a value greater than <1>
     but: <1> was equal to <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.rest.yaml.section.GreaterThanAssertion.doAssert(GreaterThanAssertion.java:64)
	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
	... 37 more
```

**Comment by JenniferPruitt** [comment]
I noticed that there is a similar problem at https://github.com/elastic/elasticsearch/issues/33326. Perhaps we can refer to [this issue](https://github.com/elastic/elasticsearch/issues/33326) to find more context about their steps to repair?.

**Comment by tbrooks8** [comment]
I think this test failed here again: https://gradle-enterprise.elastic.co/s/awqijlpuhzg2e.

**Comment by jakelandis** [comment]
This test was never muted and no comments in the past 6 months and [no failures in the past 28 days](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.smoketest.WatcherYamlRestIT&tests.sortField=FAILED&tests.unstableOnly=true). Closing.
