### ISSUE TITLE
Fast grok access in painless

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#60766]
We need to precompile the pattern for grok access to be fast.

We can use a compiler phase for this.  That precludes passing in patterns as params and, for the initial release, precludes custom patterns.

Extensions:
 * Custom patterns can be added after we think about the API.

depends on: #51955, #49873

ref: #60659

**Comment by stu-elastic** [comment]
Not on the radar, will reopen if necessary.

**Comment by javanna** [comment]
I opened #73468 as a follow-up to allow custom pattern definitions, but grok has already been made available in painless as a function. Closing then.
