### ISSUE TITLE
Allow binary sort values

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#6077]
In order to support the new ICUCollationKeyAnalyzer https://github.com/elasticsearch/elasticsearch-analysis-icu/issues/28 we need to be able to handle binary values as sort keys.  The problem comes when serializing the binary keys into JSON.

Possibly we can detect whether the analyzer creates binary token streams.

An alternative would be to add a dedicated `icu_collation_key` field type: https://github.com/elasticsearch/elasticsearch-analysis-icu/issues/29

**Comment by dadoonet** [comment]
See also #13148
