### ISSUE TITLE
Remove "experimental-ish" language in HDR Histo percentiles/ranks

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#60780]
Percentiles and Ranks have "experimental-ish" language which suggests we [might change the syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#_hdr_histogram):

> Note: This setting exposes the internal implementation of HDR Histogram and the syntax may change in the future.

I believe this was added when percentiles was upgraded to GA, because there was [some concern](https://github.com/elastic/elasticsearch/issues/19798#issuecomment-237707657 ) we were leaking implementation details to the user.  While that's true, I'm not sure I see an alternative (e.g. TDigest and HDR operate sufficiently different that it would be hard to generalize some kind of "precision" parameter between the two, and gets harder if we ever add new algorithms).  It has also been 4+ years since the language was added so I think it's not really accurate anymore.  The feature is fairly "stable" at this point, at least with regards to syntax.

I'd like to propose we remove these warnings.

**Comment by wchaparro** [comment]
We discussed this in our team sync, and we agree we should remove the experimental language.
