### ISSUE TITLE
Compatible with multiple versions, such as v5 and v7

### ISSUE THREAD

**Issue by lvyanru8200** [elastic/elasticsearch#60808]

**Comment by mayya-sharipova** [comment]
This looks like a duplicate issue of https://github.com/elastic/elasticsearch/issues/51816

I am closing because of duplicates.

@lvyanru8200 Please reopen if you had something else in mind, but please provide more details, e.g. specific API, feature you are requesting to make compatible.

**Comment by lvyanru8200** [comment]
Thanks, I'm a novice developer, my job is to make the project compatible with both V5 and V7 versions of elastic, I just finished a version based on the version number of judgement, return the corresponding version of  * Elastic. Client, then do the corresponding log processing, you can reply to me, I am very honored
