### ISSUE TITLE
CompressibleBytesOutputStreamTests#testStreamWithoutCompression reproducibly fails with NPE

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#60814]
**Build scan**:

https://gradle-enterprise.elastic.co/s/engob2pskrgnm

**Repro line**:

```
$ ./gradlew ':server:test' --tests "org.elasticsearch.transport.CompressibleBytesOutputStreamTests.testStreamWithoutCompression" -Dtests.seed=24AC7625DAF12E49
```

**Reproduces locally?**:

Yes!

**Applicable branches**:

`7.x` and `master`

**Failure history**:

[Three failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:CompressibleBytesOutputStreamTests),sort:!(process.time-start,desc))) over the last couple of days.

**Failure excerpt**:

```
org.elasticsearch.transport.CompressibleBytesOutputStreamTests > testStreamWithoutCompression FAILED
    java.lang.NullPointerException
        at __randomizedtesting.SeedInfo.seed([24AC7625DAF12E49:FA65C21184F046B0]:0)
        at org.elasticsearch.transport.CompressibleBytesOutputStreamTests$ZeroOutOnCloseStream.close(CompressibleBytesOutputStreamTests.java:117)
        at org.elasticsearch.transport.CompressibleBytesOutputStreamTests.testStreamWithoutCompression(CompressibleBytesOutputStreamTests.java:54)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.transport.CompressibleBytesOutputStreamTests.testStreamWithoutCompression" -Dtests.seed=24AC7625DAF12E49 -Dtests.security.manager=true -Dtests.locale=ga -Dtests.timezone=America/Nassau -Druntime.java=8

```

**Comment by DaveCTurner** [comment]
Muted in `master` with 807b0fef9ebe807252157a80bbaeb9ea756c95c0 and `7.x` with 273a6f916d01abfc0155342ceb54721161527158.

**Comment by original-brownbear** [comment]
I'm pretty sure this is my fault, on it :)
