### ISSUE TITLE
A way of determining whether an index is open or closed

### ISSUE THREAD

**Issue by jloleysens** [elastic/elasticsearch#60810]
## Description

Currently, ES users are only able to determine whether an index is open or closed by querying `GET _cluster/state/metadata/<indices>` or `GET _cat/indices`. Neither of these are recommended for tooling or applications.

This would be really useful in, for instance, the Kibana Upgrade Assistant where users might have a large of number indices that are deprecated (perhaps 100s) and their names might be very lengthy. Currently, the `_cluster/state` endpoint can result in web servers returning 414s if the names added to the URI are many and lengthy.

The Upgrade Assistant UI uses this information to warn users when an index is closed and that it will need to open and close the index while performing a reindex for upgrading.

## Proposed approach

I don't have a particular implementation in view other than being able to specify indices in _not_ the URI or advice on how this might be solved otherwise.

**Comment by jloleysens** [comment]
Related https://github.com/elastic/kibana/pull/74485

**Comment by danhermann** [comment]
@jloleysens, the new [_resolve/index API](https://github.com/elastic/elasticsearch/pull/57626) includes an `attributes` array in the results that includes either `open` or `closed` for each matching index. It does not permit the specification of index names in the request body, but it is lightweight enough that specifying `*` for the desired indices would not put undue load on the cluster. Would that work for what you need?

**Comment by jloleysens** [comment]
@danhermann thanks for weighing in! Specifying `*` with the _resolve endpoint should do the trick for this specific case, thanks!
