### ISSUE TITLE
Can not search woocomerce product with elastic

### ISSUE THREAD

**Issue by alexminh-its** [elastic/elasticsearch#60866]
I have an issue when try to search on Woocomerce website with elastic press. 
Query Body: 
{
    "from": "",
    "size": 6,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "match_all": {
            "boost": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "terms": {
                                    "terms.product_cat.term_id": [
                                        1251
                                    ]
                                }
                            }
                        ],
                        "must_not": [
                            {
                                "terms": {
                                    "terms.product_visibility.term_taxonomy_id": [
                                        7
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "product"
                        ]
                    }
                },
                {
                    "term": {
                        "post_status": "publish"
                    }
                }
            ]
        }
    }
}

Query Result: 
{
    "error": {
        "root_cause": [
            {
                "type": "number_format_exception",
                "reason": "empty String"
            }
        ],
        "type": "number_format_exception",
        "reason": "empty String"
    },
    "status": 400
}

Please give me advice to fix this. Thanks

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
