### ISSUE TITLE
Packer cache script failing due to missing repository definition

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#60860]
I believe the introduction of #60803 might be in play here.

```
> Could not resolve all files for configuration ':distribution:integ-test-zip'.
> Cannot resolve external dependency adoptopenjdk_8:linux:8u242 because no repositories are defined.
```

https://infra-ci.elastic.co/job/elastic+infra+master+packer-cache-elasticsearch-ci-linux/BUILDER=gcp,BUILD_OS=fedora-29,label=linux%20&&%20immutable%20&&%20docker/168/console

**Comment by mark-vieira** [comment]
@breskeby do you mind investigating this? Looks like we busted the `resolveAllDependencies` bit again.

**Comment by breskeby** [comment]
will do
