### ISSUE TITLE
Can elasticsearch split query to primary shards and replicas shards?

### ISSUE THREAD

**Issue by chenyiping111** [elastic/elasticsearch#60879]
I have query like:
            {
              "query_string": {
                "fields": [
                  "title",
                  "title_zh",
                  "abstract",
                  "abstract_zh"
                ],
                "query": "\"Computer Science\" \"Machine Learning\" \"Anomaly Detection\" \"Cluster Analysis\" \"Topic Modeling\" \"Source Separation\" \"Motif Discovery\" \"Dimensionality Reduction And Manifold Learning\" \"Mixture Modeling\""
              }
            }
there are to many phrase query , it make query slow, I want to know whether ES will make (\"Computer Science\" \"Machine Learning\" \"Anomaly Detection\" \"Cluster Analysis\" \"Topic Modeling\") to search primary shards  and (\"Source Separation\" \"Motif Discovery\" \"Dimensionality Reduction And Manifold Learning\" \"Mixture Modeling\") to search replicas shards. Or I can do this by changing the settings ?

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
