### ISSUE TITLE
Stackoverflow in Response 

### ISSUE THREAD

**Issue by skombijohn** [elastic/elasticsearch#60889]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8

**Plugins installed**: [] none

**JVM version** (`java -version`): shipped version

**OS version** (`uname -a` if on a Unix-like system): Windows 10 64bit

**Description of the problem including expected versus actual behavior**:

I am in a migration process from "legacy" index templates to the new composed templates.
As I introduced the composed templates into my application, I will have to remove existing legacy index templates in a "changelog" step.

To test my code, I created a test, that will boot up the actual elasticsearch 7.8 with the actual new composed templates.
Then (in my test only) I create a handful of legacy templates, to allow testing the removal code.

When inserting one of the legacy templates, I get an stackoverflow in some RegEx matching.

In fact, I debugged that to the point, where the response is parsed. The response contains a "warning header", which in my case contains the following error:

(Note: the actual template names are pseudonymized here for company reasons...)

`299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "legacy template [default] has index patterns [*] matching patterns from existing composable templates [templateA, templateB, ...] with patterns (templateA=> [templateA*],templateB=> [templateB*],... => [...*],...); this template [default] may be ignored in favor of a composable template at index creation time"`

To clear this up:
In my legacy templates there was a "default" template with some settings, that are meant to match all actual indices with the old "inheritance" style mechanism with order 0 and so on. Therefore the matching pattern of the "default" template was "*".

The follow up code, see stacktrace below, will try to do some matching of some kind against a monster regexp. 
Somewhere in there, a stackoverflow occurs..

Stacktrace:
`
match:4614, Pattern$Branch (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3812, Pattern$BmpCharProperty (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3812, Pattern$BmpCharProperty (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3986, Pattern$Slice (java.util.regex)
match:1270, Matcher (java.util.regex)
matches:604, Matcher (java.util.regex)
assertWarningValue:194, Response (org.elasticsearch.client)
extractWarningValueFromWarningHeader:185, Response (org.elasticsearch.client)
getWarnings:207, Response (org.elasticsearch.client)
convertResponse:278, RestClient (org.elasticsearch.client)
performRequest:261, RestClient (org.elasticsearch.client)
performRequest:235, RestClient (org.elasticsearch.client)
internalPerformRequest:1611, RestHighLevelClient (org.elasticsearch.client)
performRequest:1581, RestHighLevelClient (org.elasticsearch.client)
performRequestAndParseEntity:1551, RestHighLevelClient (org.elasticsearch.client)
putTemplate:1279, IndicesClient (org.elasticsearch.client)
addLegacyTemplate:59, RemoveLegacyTemplatesIT (my.secret.package)`
`

**Steps to reproduce**:

 1. Boot up an empty cluster of ES 7.8
 2. Insert some composable templates and some index templates with matchPatters like "indexA*", "indexB*" etc.
 3. After that, insert the following LEGACY template:

`
{
  "order": 0,
  "version": 1,
  "index_patterns": [
    "*"
  ],
  "settings": {
    "index": {
      "number_of_shards": "2",
      "auto_expand_replicas": "0-2",
      "number_of_replicas": "0",
      "max_result_window": 5000000,
      "search": {
        "idle": {
          "after": "10s"
        }
      }
    }
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      "createdAt": {
        "type": "date",
        "format": "epoch_millis"
      },
      "lastChange": {
        "type": "date",
        "format": "epoch_millis"
      }
    }
  },
  "aliases": {}
}
`
4. The above mentioned response can be seen in RestClient#convertResponse.
5. When that code invokes Response#getWarnings, the StackOverflow will occur.

**Comment by martijnvg** [comment]
@skombijohn Looks like this error occurs in the hlrc library in your application, right?

**Comment by skombijohn** [comment]
@martijnvg 
Yes! Sorry, forgot to mention that.

**Comment by andreidan** [comment]
I wasn't able to reproduce this (here's the test I used https://gist.github.com/andreidan/cb71c1d1bad04d34242fd2497de8c577 )

Equally we use this regex to extract the warning message: ```
299 Elasticsearch-\d+\.\d+\.\d+(?:-(?:alpha|beta|rc)\d+)?(?:-SNAPSHOT)?-(?:[a-f0-9]{7}(?:[a-f0-9]{33})?|unknown) "((?:	| |!|[\x23-\x5B]|[\x5D-\x7E]|[\x80-\xFF]|\\|\\")*)"( "(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} GMT")?
```
and it correctly extracts the warning message from the one you got: 
```
299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "legacy template [default] has index patterns [*] matching patterns from existing composable templates [templateA, templateB, ...] with patterns (templateA=> [templateA*],templateB=> [templateB*],... => [...*],...); this template [default] may be ignored in favor of a composable template at index creation time"
```

@skombijohn are there more steps you're executing in `RemoveLegacyTemplatesIT` to reproduce this? is this something that you can reproduce consistently?

**Comment by martijnvg** [comment]
@skombijohn Would also be helpful if you share the jvm arguments used by your application (for example by running `jps -lvm` when running your app).

**Comment by skombijohn** [comment]
@martijnvg 
Hi,
i kind of obfuscated the actual message to remove "company internal" stuff from it, but probably it does influence the outcome. Here is the actual message:

`299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "legacy template [default] has index patterns [*] matching patterns from existing composable templates [peerstate,systemevents,configuration,processresults,meterreplacements,telegramprocessingtasks,tours,analyses,notificationevents,analysisdata,datapackages,pluginregistry,tourevents,rawdata,geolayers,tasks,processlog,sessions,processes,devices,peercontacts,jobs,datareductionsettings,groups,zones,users,tempfiles,additionalinfo,extensions,nodes,dictionary,virtualmeters,usergroups,meteringdatasources,analysistemplates,timeline,notifications,contacts] with patterns (peerstate => [peerstate*],systemevents => [systemevents*],configuration => [configuration*],processresults => [processresults*],meterreplacements => [meterreplacements*],telegramprocessingtasks => [telegramprocessingtasks*],tours => [tours*],analyses => [analyses*],notificationevents => [notificationevents*],analysisdata => [analysisdata*],datapackages => [datapackages*],pluginregistry => [pluginregistry*],tourevents => [tourevents*],rawdata => [rawdata*],geolayers => [geolayers*],tasks => [tasks*],processlog => [processlog*],sessions => [sessions*],processes => [processes*],devices => [devices*],peercontacts => [peercontacts*],jobs => [jobs*],datareductionsettings => [datareductionsettings*],groups => [groups*],zones => [zones*],users => [users*],tempfiles => [tempfile*],additionalinfo => [additionalinfo*],extensions => [extensions*],nodes => [nodes*],dictionary => [dictionary*],virtualmeters => [virtualmeters*],usergroups => [usergroups*],meteringdatasources => [meteringdatasources*],analysistemplates => [analysistemplates*],timeline => [timeline*],notifications => [notifications*],contacts => [contacts*]); this template [default] may be ignored in favor of a composable template at index creation time"`


So, with that minimal example, I can reproduce the stackoverflow:

```
public static void main(String[] args){
        Pattern pattern = Pattern.compile("299 Elasticsearch-\\d+\\.\\d+\\.\\d+(?:-(?:alpha|beta|rc)\\d+)?(?:-SNAPSHOT)?-(?:[a-f0-9]{7}(?:[a-f0-9]{33})?|unknown) \"((?:\t| |!|[\\x23-\\x5B]|[\\x5D-\\x7E]|[\\x80-\\xFF]|\\\\|\\\\\")*)\"( \"(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), \\d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \\d{4} \\d{2}:\\d{2}:\\d{2} GMT\")?");
        String s = "299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 \"legacy template [default] has index patterns [*] matching patterns from existing composable templates [peerstate,systemevents,configuration,processresults,meterreplacements,telegramprocessingtasks,tours,analyses,notificationevents,analysisdata,datapackages,pluginregistry,tourevents,rawdata,geolayers,tasks,processlog,sessions,processes,devices,peercontacts,jobs,datareductionsettings,groups,zones,users,tempfiles,additionalinfo,extensions,nodes,dictionary,virtualmeters,usergroups,meteringdatasources,analysistemplates,timeline,notifications,contacts] with patterns (peerstate => [peerstate*],systemevents => [systemevents*],configuration => [configuration*],processresults => [processresults*],meterreplacements => [meterreplacements*],telegramprocessingtasks => [telegramprocessingtasks*],tours => [tours*],analyses => [analyses*],notificationevents => [notificationevents*],analysisdata => [analysisdata*],datapackages => [datapackages*],pluginregistry => [pluginregistry*],tourevents => [tourevents*],rawdata => [rawdata*],geolayers => [geolayers*],tasks => [tasks*],processlog => [processlog*],sessions => [sessions*],processes => [processes*],devices => [devices*],peercontacts => [peercontacts*],jobs => [jobs*],datareductionsettings => [datareductionsettings*],groups => [groups*],zones => [zones*],users => [users*],tempfiles => [tempfile*],additionalinfo => [additionalinfo*],extensions => [extensions*],nodes => [nodes*],dictionary => [dictionary*],virtualmeters => [virtualmeters*],usergroups => [usergroups*],meteringdatasources => [meteringdatasources*],analysistemplates => [analysistemplates*],timeline => [timeline*],notifications => [notifications*],contacts => [contacts*]); this template [default] may be ignored in favor of a composable template at index creation time\"";
        Matcher matcher = pattern.matcher(s);
        boolean matches = matcher.matches();
        // stackoverflow 
        System.out.println(matches);
    }
```





However, the setup for LegacyTemplateRemovalIT is quite big. In general here are some short steps:
- An actual forked elasticsearch 7.8 process is started (as a basic IT setup)
- The basic IT setup will utilize an actual HighLevelRestClient, to setup the cluster as the actual application will setup the cluster
- This means create index templates (now composable templates), some initial data insertion etc.
- The LegacyTemplateRemovalIT then will insert some legacy templates, as the IT will assert the application's logic to now remove the legacy stuff. 
- The above mentioned "default" template will cause the stackoverflow while the response is parsed.

I extracted the minimal example. I guess the RegExp is prone to "ReDoS" as it is relying on loads of grouping.

For reference see here:
https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

**Comment by andreidan** [comment]
@skombijohn Thanks for giving us more details. I'm now able to reproduce this.

**Comment by andreidan** [comment]
Reopening as #61259 didn't fix it.
