### ISSUE TITLE
[CI] Failure in SearchableSnapshotActionIT testSearchableSnapshotForceMergesIndexToOneSegment

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#60901]
**Build scan**:

master: https://gradle-enterprise.elastic.co/s/5sezp5x6xsw5q
7.x: https://gradle-enterprise.elastic.co/s/gtmynzftuszqa

**Repro line**:

master:

```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment" \
  -Dtests.seed=E76CE2D8CF966834 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=Mexico/General \
  -Druntime.java=11
```

7.x:

```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment" \
  -Dtests.seed=A3D3EF154BDB6AFF \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-RS \
  -Dtests.timezone=ROK \
  -Druntime.java=8
```

**Reproduces locally?**:

**Applicable branches**:

master, 7.x

**Failure history**:

Started today:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'SearchableSnapshotActionIT%20AND%20testSearchableSnapshotForceMergesIndexToOneSegment'),sort:!(process.time-start,desc))

**Failure excerpt**:

```
   java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([A3D3EF154BDB6AFF:D0C230E14240EB4]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment(SearchableSnapshotActionIT.java:104)
```

**Comment by droberts195** [comment]
I will mute this test in master and 7.x - see #60904

**Comment by davidkyle** [comment]
Another failure from a PR build. I missed the mute 😞 

https://gradle-enterprise.elastic.co/s/nnefm6lzbm7ym
