### ISSUE TITLE
Elasticsearch C++ client.

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#60934]
There is a community supported [C++ client currently](https://github.com/seznam/elasticlient), but it would be nice if there was an officially supported C++ client as robust as the other supported clients.

**Comment by philkra** [comment]
Hi @A-Hall , correct, we currently don't have an official C/C++ Elasticsearch client in our offering. All community clients are listed [here](https://www.elastic.co/guide/en/elasticsearch/client/community/current/index.html).
