### ISSUE TITLE
Support min/max aggregations for histogram fields

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elasticsearch#60951]
Currently, a min or max aggregation for a histogram field will return `{ value: null }`.

For APM, we are experimenting with replacing events with pre-aggregated data stored in histogram fields. To be able to fully migrate to histogram fields we also need support for a min/max aggregation, for which we have a couple of use cases.

**Comment by csoulios** [comment]
@dgieselaar I assume that min/max should return the min/max values of the bucket/centroid of all histograms. `count` should be ignored. Right?

**Comment by dgieselaar** [comment]
@csoulios yes, I think so? I'm not sure how `counts` would come into play.

**Comment by dgieselaar** [comment]
e.g. if you have two histograms, one of `{ values: [ 1, 2, 4 ] }`, and one of `{values: [ 0, 1, 2, 5] }`, the result of `max` should be 5, `min` should be 0, and `counts` would not be relevant.

**Comment by csoulios** [comment]
That's what I thought. Thanks!
