### ISSUE TITLE
[Index templates] Simulate API does not return mappings when is empty

### ISSUE THREAD

**Issue by sebelga** [elastic/elasticsearch#60968]
Currently, when we execute the `_index_template/_simulate` API without providing anything, we get back empty objects for "settings" and "aliases" but not for "mappings".

It would be better and more consistent to also return an empty object for "mappings" inside the "template".

```
// Current response
{
  "template": {
    "settings": {},
    "aliases": {}
  },
  "overlapping": []
}
```

```
// Expected response
{
  "template": {
    "mappings": {},
    "settings": {},
    "aliases": {}
  },
  "overlapping": []
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
