### ISSUE TITLE
snapshot/restore expand_wildcards option not consistent with other apis

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#6097]
With #4453 we introduced new indices options to be used across all apis that support multiple indices. Those options are listed here in our docs: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/multi-index.html .

All apis support the `expand_wildcards` option that accepts `open`, `closed` or both as values, while create and restore snapshot apis accept `expand_wildcards_open` and `expand_wildcards_closed` as booleans instead. Looks like we should make them consistent with other apis.

**Comment by javanna** [comment]
I think this got fixed right @imotov ? can we close?

**Comment by imotov** [comment]
@javanna no, it looks like it's still an issue https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java#L392

**Comment by javanna** [comment]
doh! I was almost sure we were using indices options there like in all other apis. thanks for checking.
