### ISSUE TITLE
Add possibility to update inline defined list of synonyms

### ISSUE THREAD

**Issue by raderio** [elastic/elasticsearch#60970]
At the moment if synonyms are defined in the file, and it is marked as `updatable`, the synonyms list can be changed without re-indexing, but this is not possible if the synonyms list is defined inline.

To manage the file is more cumbersome, and it will be more convenient to be able to update synonyms defined inline.

At least this should not be an issue if we use only query-time synonyms.

**Comment by mayya-sharipova** [comment]
@raderio Thanks for submitting the issue, but wanted to let you know that we overall don't recommend to store synonyms inline in the settings, as it increases the cluster state that for the efficient cluster work should be kept small.

**Comment by raderio** [comment]
Is 5KB of synonyms an issue for the cluster?

**Comment by jimczi** [comment]
As Mayya explained we don't recommend to store synonyms in the settings. Using an external file ensures that we don't need a cluster state update to change synonyms. That's an important part of the design so I hope you don't mind if I close this issue. We don't want to provide features that can make the cluster unstable.
