### ISSUE TITLE
Aggregations response should include index name, field names, and data types

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elasticsearch#60987]
In order for Kibana to support [user-defined searches in Lens and other visualizations](https://github.com/elastic/kibana/issues/59439), we are looking for Elasticsearch to provide **more metadata in aggregation responses**. The most important information for this use case is **index name**, **data type** and **field name**. The mental model for this is that we want to be able to programmatically construct a table from the Elasticsearch response.

**Current response for aggregations**:

Which index was searched? Which fields were searched? How should we know that `buckets.key` is a date field?

```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2789,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "categories" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "Men's Clothing",
          "doc_count" : 1204,
          "time_buckets" : {
            "buckets" : [
              {
                "key_as_string" : "2020-08-04T00:00:00.000Z",
                "key" : 1596499200000,
                "doc_count" : 19
              },
              {
                "key_as_string" : "2020-08-05T00:00:00.000Z",
                "key" : 1596585600000,
                "doc_count" : 68
              },
```

**Proposed response with added metadata**:

This response would be parseable by Kibana without knowledge of the request that generated this in the first place. Essentially, I'm proposing the following additions to the response schema:

* `aggregations._index`: The matched index name, similar to `_index` in a single document
* `aggregations.<name>.field`: The name in the mapping, if the field came from a mapping
* `aggregations.<name>.type`: The mapping type, such as `keyword` or `date`

```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2789,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "_index": "kibana_sample_data_logs",
    "categories" : {
       "field": "category.keyword",
      "type": "keyword",
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "Men's Clothing",
          "doc_count" : 1204,
          "time_buckets" : {
            "field": "@timestamp",
            "type": "date",
            "buckets" : [
              {
                "key_as_string" : "2020-08-04T00:00:00.000Z",
                "key" : 1596499200000,
                "doc_count" : 19
              },
              {
                "key_as_string" : "2020-08-05T00:00:00.000Z",
                "key" : 1596585600000,
                "doc_count" : 68
              },
```

## Cases that may need additional metadata

The example above is not accounting for:

* Non-aggregated queries
* Multi-index searches, or cross-cluster searches
* Scripted aggregations
* Alias fields
* Data streams
* Rollups

It's unclear if we should be supporting these as part of the simple definition of `_index`, `field` and `type` proposed here, but I'd appreciate input on whether this is something that the Elasticsearch folks are interested in adding.

## Should this be always returned, or requested via a query parameter?

Both would be acceptable for use in Kibana.

## Related issues

[More metadata on SQL and EQL](https://github.com/elastic/elasticsearch/issues/60956)
[Support for ES DSL in Kibana](https://github.com/elastic/kibana/pull/69254)

cc @ppisljar @flash1293

**Comment by costin** [comment]
I'm not sure whether this has been considered or not, but relying on the index name can be tricky.
A query can refer to an index pattern (`index*`), include/excludes (`index*,-index10`), date math or all of the above.
The issue here is that an alias can point to other aliases that can point to multiple, concrete indices (see the fieldcaps API).
I'm raising this point to emphasize that there will not just be one index and finding the concrete index can be a low-level detail that is hard to get (multiple indices -> multiple mappings, potential conflicts, etc...).

**Comment by wylieconlon** [comment]
That's a good point @costin. Since the two use cases we have for this metadata in Kibana are **display** and **automatically creating filters**, we probably want to use exactly the index expression that the user typed. So in your example, if the user types `index*` or `index*,-index10`, we would want to generate filters for `index*` or `index*,-index10`.

Because we already know the index expression that the user has typed in order to make the query, I no longer think that **concrete index names** are a requirement.

**Comment by wchaparro** [comment]
hey @flash1293 just checking in on this one. Is this still a need and can we find some time to talk a bit about the use case if so?

**Comment by flash1293** [comment]
The use case behind this is being able to support a visualization builder which allows the user to type the Elasticsearch query manually, then the response being translated into a data table which can be mapping to a chart type (like xy chart, pie chart and so on). The index and field name information would be used to make in-chart filtering possible: if the user clicks a bar in a bar chart, a filter is constructed for the field and term which underlies this particular bar.

As having a visualization build which allows manual editing of Elasticsearch query dsl isn't anywhere close on the roadmap, this is not a priority for us right now.

**Comment by wchaparro** [comment]
Not planned at this time.
