### ISSUE TITLE
About normal flush action

### ISSUE THREAD

**Issue by Charele** [elastic/elasticsearch#61003]
In SyncedFlushService.onShardInactive() method,
It notes,
"// A normal flush has the same effect as a synced flush if all nodes are on 7.6 or later."

I use 7.8.1,so it always will execute the NormalFlush(not the SyncedFlush).We know,the SyncedFlush will write the sync id on all shards,
but I find the NormalFlush don't do it!

Let's see the flush(boolean, boolean) method of InternalEngine,
...
commitIndexWriter(indexWriter, translog, null);
...
the 3th parameter is "null",

...
                if (syncId != null) {
                    commitData.put(Engine.SYNC_COMMIT_ID, syncId);
                }
...
it will never add(or update) the sync id,is it okay?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
