### ISSUE TITLE
move logger.trace() outside of try statement

### ISSUE THREAD

**Issue by zztv** [elastic/elasticsearch#6100]
While using  TransportClient in application with older log4j version 1.2.8 it is possible to get very misleading NoNodeAvailableException (see at the very bottom of this message):

The reason is that log4j doesn't have method trace() and call to logger.trace() is placed inside try/catch(Throwable) below. It results in exception being thrown during execution of logger.trace()  which later lead to NoNodeAvailable exception down the road.

Thanks,
Igor.

protected ImmutableList<DiscoveryNode> validateNewNodes(Set<DiscoveryNode> nodes) {
            for (Iterator<DiscoveryNode> it = nodes.iterator(); it.hasNext(); ) {
                DiscoveryNode node = it.next();
                if (!transportService.nodeConnected(node)) {
                    try {
                        logger.trace("connecting to node [{}]", node);
                        transportService.connectToNode(node);
                    } catch (Throwable e) {
                        it.remove();
                        logger.debug("failed to connect to discovered node [" + node + "]", e);
                    }

May  8 11:15:28 9.21.119.107 [dataNode.dataNode] [Ariel Writer#events] org.elasticsearch.client.transport.NoNodeAvailableException: No node available
May  8 11:15:28 9.21.119.107 [dataNode.dataNode] [Ariel Writer#events]    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219)

**Comment by jasontedor** [comment]
As of #16703, we only support log4j on the backend and with #17697 we will support log4j 2 only (which of course, support trace). Closing.
