### ISSUE TITLE
Hot-warm setup confusing, docs could explain better

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#61019]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

The docs are currently somewhat confusing with respect to setting up hot-warm with ILM. In particular it was difficult to realise that `index.routing.allocation.require.data` had to be set on the index template and then also in the policy.
The doc which contains all the information is here: https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-allocate.html. But that is very referential... if there was an example there of how to setup a hot-warm architecture as a step-by-step, this would remove confusion.
On the other hand there are plans to formalise the concept of node tiers in ES https://github.com/elastic/elasticsearch/issues/60848. So perhaps if that happens soon we will be covered regardless, assuming the process becomes simpler.

**Comment by jrodewig** [comment]
With #64185, this is now covered in https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html#data-tier-migration. I'm going to close this issue, but feel free to re-open if needed. Thanks!
