### ISSUE TITLE
Ingest nodes persistent queue

### ISSUE THREAD

**Issue by willemdh** [elastic/elasticsearch#61015]
It would be an awesome feature if ingest nodes could have a persistent queue, like Logstash. And if this feature was somehow implemented in a way that multiple threads could write to disk at the same time, it would even be better.
Currently we have to configure multiple identical pipelines in Logstash, as each pipeline can only write to disk in a single thread. (https://www.elastic.co/blog/using-parallel-logstash-pipelines-to-improve-persistent-queue-performance)

Forum link => https://discuss.elastic.co/t/ingest-nodes-persistent-queue/244591

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
