### ISSUE TITLE
reduce one traversal for shards

### ISSUE THREAD

**Issue by hanbj** [elastic/elasticsearch#61021]
#61002 
When balancing. 
A Balancer object is created inside BalancedShardsAllocator.
The buildModelFromAssigned() method is called in the Balancer construction method.
In the buildModelFromAssigned() method all RoutingNode are traversed. Traverse the shards corresponding to each RoutingNode to create a ModeNode object. 
I found that when creating the RoutingNodes object, it traverses all the shards to create each RoutingNode.
In the construction method of RoutingNode, it will traverse the shards of the node.
Therefore, I wonder whether ModeNode can be created while RoutingNode traverses the node shards.
In this way, there is no need to traverse all the shards when creating the Balancer object.

**Comment by DaveCTurner** [comment]
Can you quantify the benefit of doing this? As far as I can tell it's the same amount of work either way.

**Comment by hanbj** [comment]
@DaveCTurner 
That is, one less traversal of all shards.
ModeNode is created while RoutingNode traverses the node shards.
In the buildModelFromAssigned() method, the modeNode() method of RoutingNode is called directly to obtain it, and there is no need to traverse all the shards.
I will add a benchmark later, you have worked hard to compare it, thank you, I think there will be some improvement when there are more shards.

**Comment by DaveCTurner** [comment]
No benchmarks received, I'm closing this.
