### ISSUE TITLE
Why AnalyzerProvider is initialized twice When create index 

### ISSUE THREAD

**Issue by xushaonan** [elastic/elasticsearch#6103]
Hi:
Java code:
Part 1:
    client.admin().indices().prepareExists(index).execute().actionGet();
Part 2:
    BulkRequestBuilder builder = client.prepareBulk();
    for(AbsBean bean : e){
        builder.add(client.prepareIndex(index, type).setSource(bean.toRequest()));
    }
    BulkResponse resp = builder.execute().actionGet();

AnalyzerProvider is initialized twice when Part1 and Part2 run together in one process, but AnalyzerProvider is initialized once when Part1 and Part2 run in two processes.

thanks

**Comment by s1monw** [comment]
we don't use guice to create this stuff anymore I will close this for now
