### ISSUE TITLE
Docker pull unauthorized: Authentication Required

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [elastic/elasticsearch#61049]
Docker pull stopped working for us since some minutes:

command:
`docker pull docker.elastic.co/elasticsearch/elasticsearch-oss`

response:
`Error response from daemon: Get https://docker.elastic.co/v2/elasticsearch/elasticsearch-oss/manifests/latest: unauthorized: authentication required`

**Comment by albestia** [comment]
Same here:

`> docker pull docker.elastic.co/kibana/kibana-oss
Using default tag: latest
Error response from daemon: Get "https://docker.elastic.co/v2/kibana/kibana-oss/manifests/latest": unauthorized: authentication required
> docker pull docker.elastic.co/kibana/kibana
Using default tag: latest
Error response from daemon: manifest for docker.elastic.co/kibana/kibana:latest not found: manifest unknown: manifest unknown`

**Comment by jeanmatheussouto** [comment]
Same here:

```
Error response from daemon: Get https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/5.5.3: unauthorized: authentication required
```

**Comment by jeanmatheussouto** [comment]
https://github.com/elastic/elasticsearch/issues/61047#issuecomment-673008664

I tested here, it works now!

**Comment by xeraa** [comment]
It should be resolved now. Also let's keep the discussion in #61047 — so I'll close this one out.
