### ISSUE TITLE
Migrate existing indices to a data stream

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#61046]
Introduce a new API to migrate existing indices into a data stream. The first iteration of the API will operate on a single alias with the following provisions:

- The name of the alias will be used as the name of the new data stream. As part of the migration, the alias will be removed.
- The alias should be "clean" with no filter or routing specifications.
- All indices referenced by the alias will be set to hidden.
- The alias must have a write index.
- The _data_stream_timestamp field mapper will be inserted into the indices to enable validation.
- The mappings of the indices with _data_stream_timestamp meta field mapper will be validated.
- A composable index template must exist for the new data stream. If it is missing, the user must create it first.

**Comment by martijnvg** [comment]
@danhermann I think this can be closed now?

**Comment by danhermann** [comment]
Completed by #61525, #63749, #64415, and #65017.
