### ISSUE TITLE
docker.elastic.co authentication required (again)

### ISSUE THREAD

**Issue by key88sf** [elastic/elasticsearch#61048]
Same issue as here:
https://github.com/elastic/elasticsearch-docker/issues/237   (this repo is archived so can't add to that thread).

I'm seeing this error:
```Error response from daemon: Get https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/5.5.2: unauthorized: authentication required```

**Comment by aviau** [comment]
I just opened the same issue here: https://github.com/elastic/elasticsearch/issues/61047

**Comment by brunocvcunha** [comment]
Same happening here.

**Comment by jagretti** [comment]
Same here

**Comment by archerz** [comment]
Same here

**Comment by ywelsch** [comment]
The team is working with highest priority on a fix. Sorry for the disruption.

**Comment by ywelsch** [comment]
Let's track progress on #61047
