### ISSUE TITLE
Upgrade to Gradle 6.6

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#61051]
Gradle 6.6 is GA so we should go ahead and upgrade. Of note, it adds first-class support for the `javac --release` flag so we can finally address this [long standing todo](https://github.com/elastic/elasticsearch/blob/dd74be0f839e963eac14354ef5cfe2c8cb264fb6/buildSrc/src/main/java/org/elasticsearch/gradle/ElasticsearchJavaPlugin.java#L176).

**Comment by mark-vieira** [comment]
@breskeby I think you've already done some work here, mind going ahead and bumping the wrapper and addressing the TODO linked above?

**Comment by breskeby** [comment]
will do

**Comment by breskeby** [comment]
@mark-vieira I've updated the build to use the native --release support here: https://github.com/elastic/elasticsearch/pull/61093

**Comment by mark-vieira** [comment]
> will do. the update was done already here: #59909

Doh!

**Comment by breskeby** [comment]
The usage of the --release flag support was added here: https://github.com/elastic/elasticsearch/pull/61093 closing this issue
