### ISSUE TITLE
Add doc values support to _parent field data

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#6107]
The `_parent` field can easily have a high cardinality, as a consequence field data for this field can take a lot of memory. It would be useful to have the ability to store this mapping on disk using Lucene doc values.

Doc values proved to perform very well for aggregations in combination with global ordinals (https://github.com/elasticsearch/elasticsearch/pull/5672). So now that parent/child queries use global ordinals as well (https://github.com/elasticsearch/elasticsearch/pull/5846) I think doc values could even be the default for the `_parent` field?

**Comment by tmcerwin** [comment]
Is there any estimate on when the 2.0 version will be released?  We will likely have to remove usage of parent / child relationships, until they are moved to doc-values.  The in memory relationships are not scaling well with our application.

**Comment by jpountz** [comment]
As you can see from https://github.com/elastic/elasticsearch/issues/9970 there are 3 remaining boxes to tick and good progress is being made these days, so the first release candidate should happen pretty soon. However it might still take time between the release candidate and the GA depending on feedback.

**Comment by tmcerwin** [comment]
Thanks for the quick response!  I will run some testing on the master branch.

**Comment by alexkavon** [comment]
Is this still happening for 2.0?

**Comment by martijnvg** [comment]
@alexkavon yes, doc values support for parent/child will be included in the first 2.0 release. If you want to try it out, just make sure that you create a new index once upgraded to 2.0. The doc values support is only enabled on indices created on or after version 2.0. Indices that existed before the upgrade to 2.0 will remain to work and perform in the same way they did on previous 1.x releases.

**Comment by alexkavon** [comment]
So a reindexing should take care of this then?

**Comment by martijnvg** [comment]
@alexkavon Yes, once upgraded to 2.0.x a reindex would use the new p/c implementation.
