### ISSUE TITLE
SQL support for UNPIVOT

### ISSUE THREAD

**Issue by itssimon** [elastic/elasticsearch#61078]
It would be great if there was an UNPIVOT clause in the Elasticsearch SQL language which does the reverse operation of the already existing PIVOT clause.

The syntax could be similar to [what SQL Server has](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15#unpivot-example).

```
SELECT
  VendorID,
  Employee,
  Orders  
FROM (
  SELECT
    VendorID,
    Emp1,
    Emp2,
    Emp3
  FROM pvt
) AS p  
UNPIVOT (
   Orders FOR Employee IN (Emp1, Emp2, Emp3)  
) AS unpvt;
```

**Comment by wchaparro** [comment]
Superceded by ES|QL
