### ISSUE TITLE
Change `action.destructive_requires_name` to true by default to avoid data deleted by accident

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#61074]
Forking from the ask in https://github.com/elastic/elasticsearch/issues/30878, which contains two separated issue.
Changing the default  `action.destructive_requires_name` to true seems a legitimate request and could save a few disastrous situations. 

If I read the following line correctly, it still defaults to `false` in 7.8.1?
https://github.com/elastic/elasticsearch/blob/v7.8.1/server/src/main/java/org/elasticsearch/action/support/DestructiveOperations.java#L36

**Comment by javanna** [comment]
We have discussed this with the team and agreed that changing the default to require names for destructive operations is something we would like to do. This will affect how we delete indices when we execute integration tests, as we today rely on deleting all indices while we should instead inspect the cluster and delete all existing indices by name.

We considered if changing the default based on dev/prod mode is necessary but concluded that this is likely to confuse users and it would be good to have as few behavioural gaps as possible between dev and prod mode. 

One open question is whether, after changing the default, this setting still makes sense to keep. Should we remove it with an appropriate deprecation period?

**Comment by jackneer** [comment]
hi, may I help this? thanks!
