### ISSUE TITLE
certutil docs has unsafe example

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#61087]
In the [docs for the certutil tool](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/certutil.html) we have an example at the bottom that runs

```
bin/elasticsearch-certutil cert --silent --in instances.yml --out test1.zip --pass testpassword
```

This mode for certutil will generate a new CA, and then throw the private key away. That is almost never the right thing to do.

It should be either:
```
bin/elasticsearch-certutil cert  --silent --in instances.yml --out test1.zip --pass testpassword --ca cluster-ca.p12
```
which will use an existing CA, or

```
bin/elasticsearch-certutil cert  --silent --in instances.yml --out test1.zip --pass testpassword --keep-ca-key
```
which will generate a new CA and retain a copy of the key for future use.

I think the latter is probably the better option for that example.

**Comment by ywangd** [comment]
I wonder whether we should have `--keep-ca-key` as default for the CLI tool and instead have `--discard-ca-key` option for the unusual use case.

**Comment by bytebilly** [comment]
I'm wondering which is the use case where the CA key is not needed. For tests, it's probably not a problem to keep it. For any other case, it's probably safer to keep it.

I'm supportive to switch the default, and also to consider if we really need an option to delete the key. Users can delete it manually if they really want.

If there is no strong reason to keep the current default, I'll open a new issue to discuss it.
