### ISSUE TITLE
Fix packaging / unpacking overhead when setting up local distributions

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#61095]
When installing local elasticsearch distributions we create an archive and then immediately unpackage that archive again in the desired target directory. This mechanism is used for example 

- when running `./gradlew :run` to spin up a local installation or
- when using the test clusters plugin that leverages the distribution-download-plugin.

For developers we ultimately want to be able to use the `-t` or `--continuous` command line flag in gradle that immediately updates a running build with just the changes since the last build.

**Comment by breskeby** [comment]
There has been some work towards this goal already:

- https://github.com/elastic/elasticsearch/pull/60713 (a first application of artifact transforms for handling jdk downloads) 
- https://github.com/elastic/elasticsearch/pull/57869

-

**Comment by mark-vieira** [comment]
@breskeby I believe we've come full circle on this now with the additions to BWC building, yes? Can we close this issue or are there items still to complete?

**Comment by breskeby** [comment]
I think we're complete. Wanted to double check if there's anything left here before closing

**Comment by breskeby** [comment]
completed by getting https://github.com/elastic/elasticsearch/pull/66342 into master / 7.x
