### ISSUE TITLE
_cat/indices shows gb when it seems like it should be gib

### ISSUE THREAD

**Issue by Alex3k** [elastic/elasticsearch#61091]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8 in Elastic Cloud

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:
When using _cat/indices the default output looks like the below image. However, from reading [the docs on the byte size units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#byte-units) it states 
> Note that these units use powers of 1024, so 1kb means 1024 bytes

Does this not mean that instead of GB in the below image it should be GiB?

![image](https://user-images.githubusercontent.com/5962803/90134367-f978c400-dd68-11ea-9ba1-b3abefb86436.png)

**Comment by pgomulka** [comment]
:) 
I think the consensus is that gb still means Gigabytes 1024^3. Although Giga means 10^9 in SI units, in context of computer science it is clear that it means 2^30.

https://en.wikipedia.org/wiki/Gigabyte
