### ISSUE TITLE
I use elasticsearch in java ,and i get some questions that i can't understand

### ISSUE THREAD

**Issue by AnswerNo2** [elastic/elasticsearch#61094]
when i create a doc，i need use :   IndexRequest indexRequest = new IndexRequest(String indexName);   the question is : 
indexRequest .type(type) ,this method is deprecated, and what method can replace it ？ i want  know!

**Comment by pugnascotia** [comment]
Types are being removed completely - see this blog post for more information:

https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0

**Comment by AnswerNo2** [comment]
> Types are being removed completely - see this blog post for more information:
> 
> https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0

thank you ! i have seed that blog
