### ISSUE TITLE
[DOCS] An overview page for Ingest Pipelines like for ILM 

### ISSUE THREAD

**Issue by Alex3k** [elastic/elasticsearch#61146]
**Summary**
I find the Ingest Pipeline docs quite heavy on technical detail on [the root page](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) whereas other pages like the ILM docs have a [great, very approachable brief summary ](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html)and then [solid overview section](https://www.elastic.co/guide/en/elasticsearch/reference/current/overview-index-lifecycle-management.html).

**Detail**
Within the ILM docs, you get a really brief introduction to ILM with a screenshot that gives a bit more detail and then various sections such as Overview and Concepts. This documentation in my mind if the gold standard when sharing with customers as I don't need to reinvent the wheel when trying to describe that it's useful.
![image](https://user-images.githubusercontent.com/5962803/90248944-81c29c00-de31-11ea-9db6-072b76cc9152.png)

However, I find when trying to encourage folks towards [Ingest Pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) it gets a bit more complicated. The root documentation is on `ingest node` and the first image is about setting node.ingest - this leads to confusion for those on cloud/ece. 

![image](https://user-images.githubusercontent.com/5962803/90249455-67d58900-de32-11ea-9dcc-43e7d9a073e5.png)

Furthermore, you don't need dedicated ingest nodes for Ingest Pipelines. However the root of ingest pipelines is entitled `ingest node`. This often leads to a bit of confusion and therefore long emails in the pre-sales conversations where I try and summarise what ingest pipelines are.

It would be really great and useful if we could structure the ingest pipeline documentation to be closer to the structure of ILM. For example, the root page could be titled "Ingest Pipelines" and then an overview of what they are and why they're awesome. Within the a page similar to concepts, we could then go into detail about what the ingest node is, how to configure it, the cluster state and so on.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
