### ISSUE TITLE
LDAP User Metadata: Return tokenGroups attribute as SID string, not byte array

### ISSUE THREAD

**Issue by djsiroky** [elastic/elasticsearch#61173]
When adding additional metadata fields to the Active Directory realm configuration, would it be possible for the **tokenGroups** attribute to be returned in SID string format so it could be used more easily in document queries for document level security?

Currently, if I add `metadata: ["tokenGroups"]` to `xpack.security.authc.realms.active_directory.ad_realm1` in elasticsearch.yml, querying `/_security/_authenticate` gives a response of string encoded bytes. When putting together the document query, I assume the `_user.metadata.tokenGroups` field looks similar and I don't believe there's a way to be able to compare this metadata to a field that uses SID format for representing permissions.

It looks like Elastic uses the **tokenGroups** user attribute to populate the "ldap_groups" and there is already [a method to convert the bytes to SID](https://github.com/elastic/elasticsearch/blob/627ef279fd29f8af63303bcaafd641aef0ffc586/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ldap/ActiveDirectorySIDUtil.java#L31) in the Elastic code base. I could see it being a modified version of the **ActiveDirectoryGroupsResolver** or a modification to the **LdapMetaDataResolver**, but I'm interested if this seems like a worthwhile addition to make it easier to compare user access in SID form to index SID fields.

Thanks!

**Comment by djsiroky** [comment]
To add to this issue, the string-encoded byte array included user's metadata for the JSON response to`GET /_security/_authenticate`  contains replacement characters (�) that would prevent someone from constructing the same SID from the bytes. 

I found this out from an attempt at a workaround where our search client would get the user's metadata, convert the `tokenGroups` string-encoded bytes to SID format using a similar method to the one linked in the code base, and pass that to a search template that would filter on the field containing SIDs in our index.

So I suppose this leaves a couple options (as far as I can tell) for the including the `tokenGroups` field in `user.metadata` in a useful manner:
- Encoding the response in a way that SIDs could be reconstructed client-side
- Returning the tokenGroups value in SID format

Definitely open to other suggestions, and we may end up just reindexing the field related to security access to another format like the distinguished name, although the ID of the group/user with access seems to ideal since it is less likely to change.

**Comment by djsiroky** [comment]
To provide a sample case, here's one of the strings returned in the JSON response to `GET /_security/_authenticate`:
`
 "\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000��2?|�$\r���(B\u0019\u0000\u0000"`

Following the logic of `ActiveDirectorySIDUtil.java`:
### Revision
byte[0] = `\u0001` = `1`    
`> S-1`
### Number of sub-authorities
byte[1] = `\u0005` = `5`    5 sub-authorities
### Identifier Authority (big-endian)
byte[2-7] = `\u0000\u0000\u0000\u0000\u0000\u0005\` = `[0, 0, 0, 0, 0, 5]` = `5`
`> S-1-5`

### 1st SubAuthority (little-endian)
byte[8-12] = `\u0015\u0000\u0000\u0000` = `[21, 0, 0, 0]` = `21`
`> S-1-5-21`

### 2nd SubAuthority (little-endian) (does not match)
#### Expected:
byte[12-16] = `\x8a\xa72?` = `[138, 167, 50, 63]` = `1060284298`
`> S-1-5-21-1060284298`

#### Actual:
byte[12-16] = `��2?` = `[63, 63, 50, 63]` = `1060257599`
`> S-1-5-21-1060257599`

Any additional case with the replacement character present has a similar issue.

**Comment by djsiroky** [comment]
For anyone trying to work around this issue, in particular trying to use document-level security to filter results by the SIDs of the AD security groups someone is a member of, here's what we did as a workaround:

Write an AD Security Group / ElasticSearch Role + Role Mapping sync script that:
- Fetches all AD security groups
- For each security group:
  - Create an ES role for that group, with a document filter for the field containing the SIDs with a value of the SID of the current group: `{
  "bool": {
    "filter": [
      {"term":{"acls":{"value":"S-1-5-...."}}}
    ]
  }
}`
  - Create an ES role mapping that adds the role created in the previous step if the user's groups contains the DN of the group
- This script should also handle updated or removed groups to ensure it is in sync with your AD

This does not resolve the issue above, but is working for us to bypass it until a more integrated solution becomes available.

**Comment by bytebilly** [comment]
Thanks for providing details and sharing your workaround.

I'm curious if the "wrong" characters are sent back by Elasticsearch as replacements (0xFF 0xFD) or if they are sent as expected (0x8A 0xA7) and rendered with the replacement on the client side, since it was interpreted as a text string.

**Comment by djsiroky** [comment]
Hi @bytebilly, I don't believe that's the case. I've checked the response via `curl`, Insomnia (an REST API tool similar to Postman), and a Node.js script, and each time the response from the server includes:
- Content-Type headers of  `application/json; charset=UTF-8` (telling me the byte array is being string encoded server-side)
- Some form of an encoded string with the replacement characters (these are all different examples, not the same group):
Node: `'\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00��2?|�$\r���(�Y\x01\x00'`
Insomnia: `"�S�|cE�P�\b�7�\n"` (Visual Preview view) or `"\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000��2?|�$\r���(�u\u0000\u0000"` (Raw Data view)
curl: `"\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000��2?|�$\r���(7*\u0001\u0000"`
