### ISSUE TITLE
PUT /_cluster/settings/" while throw IllegalArgumentException

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#61175]
**Elasticsearch version** : 6.8.11
**Plugins installed**: []
**JVM version** : 1.8.0_45
**OS version** : GNU/Linux

**Description of the problem including expected versus actual behavior**:
First the cluster version is 5.6.8,  then we upgrade the cluster to 6.8.11. If we update cluster settings in the new cluster, it will throw the IllegalArgumentException:
```
"reason": "unknown setting [archived.indices.ttl.interval] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"

```
The reason is clear, there exists a setting in the ES5 cluster, which is archived in ES6 cluster. After upgrading to ES6, if we update the cluster setting , ES6 server will validate the archived settings:`indices.ttl.interval` and not ignore it, which will throw exception.
https://github.com/elastic/elasticsearch/blob/0f256948a5176ac4baab0a217e1107c0f86063a5/server/src/main/java/org/elasticsearch/action/admin/cluster/settings/SettingsUpdater.java#L94
As the result:
1.There doesn’t exist api which can be used to delete those cluster settings.
2.I will be unable to update any cluster settings in ES6.

**Steps to reproduce**:
step 1:
Push the cluster setting to ES5.6.8 cluster:
```
PUT _cluster/settings/admin/lc_gh_4
{
    "persistent": {
        "indices.ttl.interval":"6000s"
    }
}
```
step 2:
Upgrade the cluster to 6.8.11
step 3:
Push the cluster setting to the cluster:
```
PUT _cluster/settings
{
     "persistent": {
      "cluster": {
         "routing": {
            "allocation": {
               "cluster_concurrent_rebalance": "3"
            }
         }
      }
     }
}
```
ES will throw the exception
```
 "reason": "unknown setting [archived.indices.ttl.interval] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
```

**Comment by j-bennet** [comment]
I have the same issue when upgrading from 7.16.0 to 8.0.0. The setting in question is `index.search.slowlog.level`. When Elasticsearch was upgraded, the setting became `archived.index.search.slowlog.level`. When trying to set a different setting for the index, I get an error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "unknown setting [archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unknown setting [archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  },
  "status" : 400
}
```

**Comment by jrodewig** [comment]
Thanks for raising this @j-bennet. However, I wasn't able to reproduce this locally. I included my reproduction steps below. Can you help provide some more detailed steps on your end?

1. Start up a 7.16.0 cluster.
2. Create an index with the `index.search.slowlog.level` setting.
```
PUT my-index-000001
{
  "settings": {
    "index.search.slowlog.level": "INFO"
  }
}
```
3. Add a doc just so we have some data in the index.
```
POST my-index-000001/_doc
{
  "field": "foo"
}
```
4. Shut down the cluster and upgrade to 8.0.0-beta1 by copying the `data` directory over. Restart the cluster.

5. Check to see that the index exists and the setting was archived.
```
GET  my-index-000001?pretty&flat_settings=true&filter_path=**.settings
```
Response:
```
{
  "my-index-000001" : {
    "settings" : {
      "archived.index.search.slowlog.level" : "INFO",
      "index.creation_date" : "1639781967087",
      "index.number_of_replicas" : "1",
      "index.number_of_shards" : "1",
      "index.provided_name" : "my-index-000001",
      "index.routing.allocation.include._tier_preference" : "data_content",
      "index.uuid" : "lEULF7fGRgWiy5OtF1gSLA",
      "index.version.created" : "7160099"
    }
  }
}
```
6. Update another setting for the index.
```
PUT my-index-000001/_settings
{
  "index" : {
    "number_of_replicas" : 2
  }
}
```
Response:
```
{
  "acknowledged" : true
}
```
7. Add some data to the index.
```
POST my-index-000001/_doc
{
  "field": "foo"
}
```
Response:
```
{
  "_index" : "my-index-000001",
  "_id" : "Oumnyn0Bg6t9s50kl9Z-",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 3,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 2,
  "_primary_term" : 2
}
```

Since this doesn't appear to be related to the docs, I'm going to remove the `>docs` label for now. However, we can re-add it later if needed.

**Comment by DaveCTurner** [comment]
I think there are a few docs issues here @jrodewig.

Archived index settings are ignored in existing metadata, but I think we should clarify that they're not ignored in requests:

```
PUT /_settings
{
  "archived.index.search.slowlog.level": "DEBUG"
}

# 400 Bad Request
# {
#   "status": 400,
#   "error": {
#     "reason": "unknown setting [index.archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
#     "root_cause": [
#       {
#         "reason": "unknown setting [index.archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
#         "type": "illegal_argument_exception"
#       }
#     ],
#     "type": "illegal_argument_exception"
#   }
# }
```

This is one way to get the reported error: run `GET $INDEX/_settings`, change a few values, and then try and `PUT` the modified settings back. This won't work if there are any archived ones in the `GET` result.

Also the docs imply that all archived settings are ignored but that only applies to index settings. Archived _cluster_ settings are not ignored:

```
GET /_cluster/settings?flat_settings

# 200 OK
# {
#   "persistent": {
#     "archived.discovery.zen.minimum_master_nodes": "3"
#   },
#   "transient": {}
# }

PUT /_cluster/settings
{
  "persistent": {
    "indices.recovery.max_bytes_per_sec": "50mb"
  }
}

# 400 Bad Request
# {
#   "status": 400,
#   "error": {
#     "reason": "unknown setting [archived.discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
#     "root_cause": [
#       {
#         "reason": "unknown setting [archived.discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
#         "type": "illegal_argument_exception"
#       }
#     ],
#     "type": "illegal_argument_exception"
#   }
# }
```

We say that you can remove them by setting `archived.*` to `null`, but really we should say that you _have_ to do this before you can set any other setting.

**Comment by jrodewig** [comment]
Thanks for clarifying @DaveCTurner. I'll work on some related updates.

**Comment by j-bennet** [comment]
Here are the exact reproduction steps.

1. Start Elasticsearch & Kibana in Docker using the attached `docker-compose.yml`: `ES_VERSION=7.16.0-SNAPSHOT KIBANA_VERSION=7.16.0-SNAPSHOT docker-compose up`
2. Change kibana user password, so Kibana can access ES:
`curl -u elastic:changeme -X POST "localhost:9200/_security/user/kibana_system/_password?pretty" -H 'Content-Type: application/json' -d' { "password" : "changeme" }`
3. Log in to Kibana and create an index with deprecated settings:

```
PUT index1
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "search.slowlog.level": "debug"
  },
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "id": { "type": "keyword"},
      "content": {"type": "text"}
    }
  }
}
```

Response:

```
#! [index.search.slowlog.level] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "index1"
}
```

Index a document:

```
PUT index1/_doc/doc1
{
  "id": "doc1",
  "content": "Quick brown fox"
}
```

4. `Ctrl + C` to stop containers.
5. Start Elasticsearch & Kibana in Docker, this time with 8.0: `ES_VERSION=8.0.0-SNAPSHOT KIBANA_VERSION=8.0.0-SNAPSHOT docker-compose up`
6. Log in to Kibana (elastic/changeme). Verify the deprecated setting was archived: 

```
GET index1/_settings
```

Response:

```
{
  "index1" : {
    "settings" : {
      "archived" : {
        "index" : {
          "search" : {
            "slowlog" : {
              "level" : "debug"
            }
          }
        }
      },
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "index1",
        "creation_date" : "1640109084516",
        "number_of_replicas" : "0",
        "uuid" : "TgQmqpzqSM2a2NXnUBBypA",
        "version" : {
          "created" : "7160099"
        }
      }
    }
  }
}
```

Attempt to change a different index setting - make index hidden:

```
PUT index1/_settings
{
  "index.hidden": "true"
}
```

There is an error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "unknown setting [archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unknown setting [archived.index.search.slowlog.level] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  },
  "status" : 400
}
```

Here is the Elasticsearch version:

```
> curl -u elastic:changeme -XGET 'http://localhost:9200' -s
{
  "name" : "df6b63336817",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "vVbGrHb5Tuy2Y4nuQuoi3A",
  "version" : {
    "number" : "8.0.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "b004395990b3fc8903dcbc1f7348a22387d17773",
    "build_date" : "2021-12-17T00:19:59.189085917Z",
    "build_snapshot" : true,
    "lucene_version" : "9.0.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Should this be happening? What is the workaround? I tried to clear the archived settings:

```
PUT index1/_settings
{
  "archived.*": null
}
```

But that did not do anything.

**Comment by jrodewig** [comment]
Hi @j-bennet,

Thanks for adding the steps. I was able to reproduce the issue on my end.

The docs are definitely wrong here, and that's my fault. I'm very sorry that you hit this issue. I'll work on a related fix.

> What is the workaround?

There are a couple of options:

**Option A. Clear the setting before the upgrade**
Clear the `index.search.slowlog.level` index setting **before upgrading**. This will prevent the setting from being archived.

```
PUT index1/_settings
{
  "index" : {
    "search.slowlog.level": null
  }
}
```

**Option B. Reindex after the upgrade**
2. If you've already upgraded and have an archived index setting, you can reindex to remove it.

```
### Configure a new index without `search.slowlog.level` setting.
PUT reindexed-index1
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "hidden": true
  },
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "id": { "type": "keyword"},
      "content": {"type": "text"}
    }
  }
}

### Reindex into the new index.
POST _reindex
{
  "source": {
    "index": "index1"
  },
  "dest": {
    "index": "reindexed-index1"
  }
}
```
