### ISSUE TITLE
Best way to ingest/ship logs from fluentd to Kafka 

### ISSUE THREAD

**Issue by dinesh4747** [elastic/elasticsearch#61181]
Hi Team,

I am working setting up a logging pipeline for kubernetes running on GCP and we already have fluentd as a daemonset running across the nodes and it takes care of log Shipping

Question:

We have close to 500 app containers and it bound to scale even 2x as running in the cluster and looking for a best case solution to implement efk stack and looking for options on methodology to transport all the logs to Kafka, like interms of looking below questions

1) Can we ingest every single container logs to individual partitions in Kafka ?

2) How many topics we can have and how do we design the topic vs partitions on building the scaling logging pipeline

3) How about acks? And replication factor? Any best approach to follow 

Any help/direction or pointer would help a lot here 

Regards
Dinesh

**Comment by tvernum** [comment]
Hello @dinesh4747, Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of conversations around solution design.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
