### ISSUE TITLE
Index template example uses deprecated API, should be changed

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#61222]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

**Description of the problem including expected versus actual behavior**:
The [docs here](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/getting-started-index-lifecycle-management.html#ilm-gs-apply-policy) show an example of index template creation. However, this uses the old, deprecated API. It should be updated to use the [new Index Template API](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-templates.html).

**Comment by jrodewig** [comment]
Closed by #61223
