### ISSUE TITLE
[CI] idp-fixture:composeUp  failures in startup of open-ldap service

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61260]
Probably an infra-related issue but I want to open it here first to get feedback from the build team what to do with this.

**Build scan**:
https://gradle-enterprise.elastic.co/s/bmqpyge4osmje/console-log?task=:x-pack:test:idp-fixture:composeUp
https://gradle-enterprise.elastic.co/s/bmqpyge4osmje

**Repro line**: -

**Reproduces locally?**: -

**Applicable branches**:
7.x

**Failure history**:
Several similar looking failures in the last days

**Failure excerpt**:
:x-pack:test:idp-fixture:composeUp FAILED
/bin/sh: /tmp/_MEIX9dp75/libreadline.so.7: no version information available (required by /bin/sh)
openldap uses an image, skipping
shibboleth-idp uses an image, skipping
http-proxy uses an image, skipping
oidc-provider uses an image, skipping
/bin/sh: /tmp/_MEI5I91mK/libreadline.so.7: no version information available (required by /bin/sh)
Creating network "0ab299945d34701bf482740b3c354ac1_idp-fixture__default" with the default driver
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__openldap_1 ... 
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1 ... 
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__openldap_1   ... error

ERROR: for 0ab299945d34701bf482740b3c354ac1_idp-fixture__openldap_1  Cannot start service openldap: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/f801cb5616847c103a41debc1ab68cd1ee7eed0b0602c44e6708f57e289d5444/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1 ... done
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... 
Creating 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... done

ERROR: for openldap  Cannot start service openldap: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/f801cb5616847c103a41debc1ab68cd1ee7eed0b0602c44e6708f57e289d5444/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Encountered errors while bringing up the project.
/bin/sh: /tmp/_MEIANy362/libreadline.so.7: no version information available (required by /bin/sh)
Stopping 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... 
Stopping 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1    ... 
Stopping 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... done
Stopping 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1    ... done
/bin/sh: /tmp/_MEIoNHnBD/libreadline.so.7: no version information available (required by /bin/sh)
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... 
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__openldap_1      ... 
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1    ... 
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__http-proxy_1    ... done
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__openldap_1      ... done
Removing 0ab299945d34701bf482740b3c354ac1_idp-fixture__oidc-provider_1 ... done
Removing network 0ab299945d34701bf482740b3c354ac1_idp-fixture__default

**Comment by cbuescher** [comment]
Pretty similar looking one from 2 days ago: https://gradle-enterprise.elastic.co/s/5s62z2ewpxlji/console-log/raw?task=:x-pack:test:idp-fixture:composeUp

**Comment by cbuescher** [comment]
This is another fixture than idp-fixture, but the error looks related to me since the cause also seems to be "unable to remount dir as readonly":

https://gradle-enterprise.elastic.co/s/vaes6ktxtnrzq/console-log?task=:test:fixtures:s3-fixture:composeUp
```
:test:fixtures:s3-fixture:composeUp FAILED
/bin/sh: /tmp/_MEI5aArfV/libreadline.so.7: no version information available (required by /bin/sh)
Building s3-fixture
Building s3-fixture-other
Building s3-fixture-with-session-token
Building s3-fixture-with-ec2
Building s3-fixture-with-ecs
/bin/sh: /tmp/_MEIf63r8o/libreadline.so.7: no version information available (required by /bin/sh)
Creating network "05e238095ec607cf6dc576411d9464b3_s3-fixture__default" with the default driver
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-other_1 ... 
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-ecs_1 ... 
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-session-token_1 ... 
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture_1                    ... 
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-ec2_1           ... 
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-ecs_1           ... error

ERROR: for 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-ecs_1  Cannot start service s3-fixture-with-ecs: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/0960fe60a4b16570bd0e6e48037179e9031aa5231c9e448ade4d0a98f47829da/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-other_1              ... done
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture_1                    ... done
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-session-token_1 ... done
Creating 05e238095ec607cf6dc576411d9464b3_s3-fixture__s3-fixture-with-ec2_1           ... done

ERROR: for s3-fixture-with-ecs  Cannot start service s3-fixture-with-ecs: unable to remount dir as readonly: mount tmpfs:/var/lib/docker/containers/0960fe60a4b16570bd0e6e48037179e9031aa5231c9e448ade4d0a98f47829da/mounts/secrets, flags: 0x21, data: uid=0,gid=0: device or resource busy
Encountered errors while bringing up the project.
/bin/sh: /tmp/_MEIuHoo9L/libreadline.so.7: no version information available (required by /bin/sh)

```

**Comment by mark-vieira** [comment]
Our CI images were updated to SLES 15.2 from 15.1 so the new versions needed to be added to our [exclusion list](https://github.com/elastic/elasticsearch/blob/master/.ci/dockerOnLinuxExclusions#L13). This has been done so we should stop seeing these failures.
