### ISSUE TITLE
[CI] ESTestCaseTests.testRandomDateFormatterPattern fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61261]
**Build scan**:
https://gradle-enterprise.elastic.co/s/pui6fsuhb34yu

**Repro line**:
./gradlew ':test:framework:test' --tests "org.elasticsearch.test.test.ESTestCaseTests.testRandomDateFormatterPattern" \
  -Dtests.seed=A30749E4133D87A5 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Asia/Dacca \
  -Druntime.java=14

**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure history**:
Another failure on 7.x earlier today: https://gradle-enterprise.elastic.co/s/7sxkmswcglt6a

**Failure excerpt**:
java.lang.AssertionError: 
Expected: <0L>
     but: was <-259200000L>
	at __randomizedtesting.SeedInfo.seed([A30749E4133D87A5:AE6E17DEFD8D5E5E]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.test.test.ESTestCaseTests.testRandomDateFormatterPattern(ESTestCaseTests.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Looking at the commit history my guess is https://github.com/elastic/elasticsearch/commit/ca36bca5bd3d51c69a726281e757b5ba7643d445 might have to do something with this. @nik9000 can you check and otherwise assign someone else or another team?

**Comment by cbuescher** [comment]
Another one on 7.x: https://gradle-enterprise.elastic.co/s/5rgbaxswje3ga

**Comment by pgomulka** [comment]
For that seed the random format is `strict_weekyear_week`
it  formats epoch `0L` to `1970-W01`. 
However epoch is considered to be `00:00:00 UTC on 1 January 1970`
but week 1 of `1970` actually starts on `29.12 1969` (hence the negative number)

so in a way, because the `strict_weekyear_week` does not have information about day of week, we loose that information. T

**Comment by nik9000** [comment]
> There will be more test cases failing like that (there are more formats which "loose" information when formatting). If possible can we mute the test and reconsider it?

Yeah, on further thought that test isn't very good, is it? I'll weaken its assertion. Really I just care that any random date format makes a working formatter.

**Comment by nik9000** [comment]
I pushed 74bad1812debedd7d879a4d4a153c3bf7f078720.
