### ISSUE TITLE
Shard deletion from disk does not happen immediately after replica count change.

### ISSUE THREAD

**Issue by itiyamas** [elastic/elasticsearch#61284]
Shard deletion for a replica follows the following path:
1. Delete from the metadata maintained per node via IndicesClusterStateApplier. 
2. Close the store object and decrease store ref count. Store ref is an abstraction over the actual file directory, write accesses to which are managed by a shard lock. The shard lock is released when the store is closed and the ref count becomes 0.
3. IndicesStore(listener) triggers a check to see whether shard is active on any other node and if yes, it tries deleting the shard from disk if not present in metadata. This step is asynchronous. 
4. The listener in step 3 does a bunch of stuff to maintain consistency of the system like checking cluster state version before and after the request. The same listener will take a shard lock before deleting the shard. 

The above is true for any kind of shard deletion, except when index is deleted.
The listener fails in deleting the shard in certain cases because the store reference does not immediately become zero due to an ongoing peer/snapshot recovery and/or a long running search. In those cases, the shard lock fails(as the acquire timeout is just 0 ms) and the shard remains as dangling till the next cluster state arrives. It might so happen that a few new cluster state changes could arrive to create new indices before the store ref count has a chance to get to 0, leading to the shard dangling in the cluster for a longer duration and causing the disk to become full as a result of more indexing on this node.

Ideally, we should delete the shard from disk when the store ref count becomes 0 and shard lock is released and not wait for the new cluster state update to clear the entries. 

Is there a specific reason, the shard deletion from disk requires a new cluster update?

Steps to reproduce:
1. Create an index with 5 primaries and 1 replica.
2. Start search traffic on replica. Add searches that take close to 30 seconds to finish.
3. Change replica count to 0.
4. Check _cat/shards API output. It returns shard count as 5.
5. Check the data folder on node with replica. It still shows the replica. Wait for some time.
6. Trigger reroute API or any cluster state update change. The replica is removed from the disk.

Let me know if you need logs as well.

**Comment by DaveCTurner** [comment]
> Is there a specific reason, the shard deletion from disk requires a new cluster update?

I think no, cluster state updates are just used as a trigger mechanism since we can assume that they happen infinitely often. Listening for the close of the shard lock would be nicer.

**Comment by itiyamas** [comment]
+1 for adding a listener on shard lock close.

**Comment by DaveCTurner** [comment]
I think this would be addressed by the changes proposed in https://github.com/elastic/elasticsearch/issues/74149, although it's not directly related, the vision of a more robust shard deletion mechanism would also come with improvements to how timely those deletions are.

**Comment by tlrx** [comment]
Closed in favor of #74149
