### ISSUE TITLE
Error in building and running elasticsearch source code in IntelliJ

### ISSUE THREAD

**Issue by bhavya121999** [elastic/elasticsearch#61292]
**Elasticsearch version** (`bin/elasticsearch --version`): Latest elasticsearch source code from [Github](https://github.com/elastic/elasticsearch)

**Plugins installed**: [None]

**JVM version** (`java -version`): 
`
java 14.0.2 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
`

**OS version** (`uname -a` if on a Unix-like system): 
```Linux bhavya-lenovo-ideapad-330s-15ikb-u 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

**Description of the problem including expected versus actual behavior**:
Error in building and running elasticsearch source code in IntelliJ

**Steps to reproduce**:
Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. I have cloned the latest Elasticsearch Source Code from the official [Github repository](https://github.com/elastic/elasticsearch)
`JAVA_HOME` is set to `/home/bhavya/.jenv/versions/14`
 
 2. Then I imported the project into IntelliJ IDEA
 
 3. Now when I run the elastic search from IntelliJ IDEA, using `build.gradle`, following response is generated

```
10:53:09 PM: Executing task...

Starting Gradle Daemon...
Gradle Daemon started in 1 s 45 ms
> Task :buildSrc:reaper:compileJava UP-TO-DATE
> Task :buildSrc:reaper:processResources NO-SOURCE
> Task :buildSrc:reaper:classes UP-TO-DATE
> Task :buildSrc:reaper:jar UP-TO-DATE
> Task :buildSrc:reaper:assemble UP-TO-DATE
> Task :buildSrc:reaper:compileTestJava NO-SOURCE
> Task :buildSrc:reaper:processTestResources NO-SOURCE
> Task :buildSrc:reaper:testClasses UP-TO-DATE
> Task :buildSrc:reaper:test NO-SOURCE
> Task :buildSrc:reaper:check UP-TO-DATE
> Task :buildSrc:reaper:build UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:generateVersionProperties UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestFixturesJava UP-TO-DATE
> Task :buildSrc:compileTestFixturesGroovy NO-SOURCE
> Task :buildSrc:processTestFixturesResources NO-SOURCE
> Task :buildSrc:testFixturesClasses UP-TO-DATE
> Task :buildSrc:testFixturesJar UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources UP-TO-DATE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test SKIPPED
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/elastic/elasticsearch/pull/57936
===========================================================
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.5
  OS Info               : Linux 5.4.0-42-generic (amd64)
  JDK Version           : 14 (OpenJDK)
  JAVA_HOME             : /usr/lib/jvm/jdk-14.0.1
  Random Testing Seed   : DBEB7C61046935E5
  In FIPS 140 mode      : false
=======================================

> Task :help

Welcome to Gradle 6.5.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 20s
1 actionable task: 1 executed
10:53:31 PM: Task execution finished.

```

4. Now according to [CONTRIBUTING.md](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md), when I run Elasticsearch using command `./gradlew :run` from the terminal, I get the following errors :

```
Unrecognized VM option 'AggressiveOpts'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```
I have already asked question on Stackoverflow and discuss.elastic.co, the links for the same are provided below:

- [Stackoverflow Question](https://stackoverflow.com/questions/62886376/error-in-building-and-running-elasticsearch-source-code-in-intellij-idea)

- [Discuss link](https://discuss.elastic.co/t/error-in-building-and-running-elasticsearch-source-code-in-intellij-idea/240957)

But got no response from any of the sources mentioned above. 
Can anyone please help me resolve this issue?

**Provide logs (if relevant)**:

**Comment by costin** [comment]
I'm sorry to hear that you haven't had any answers yet to your question. It looks like you have some issues with the JDK being used (either it's too old or too new - make sure you use the appropriate one for the version of ES you are trying to build).
However we reserve GitHub issues for bug reports and feature requests only.
Please continue using the [forums](https://discuss.elastic.co/), or consult the [documentation](https://www.elastic.co/guide/index.html).
