### ISSUE TITLE
Runtime fields to support runtime type geo-shape

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#61299]
As a follow-up of #59332, we'd like to add support for runtime fields that have `runtime_type` `geo-point` and `geo-shape`.

**Comment by javanna** [comment]
geo_point was added with #63164

**Comment by nreese** [comment]
I work on Kibana maps team and have a customer asking for runtime geo_shape support. Below is the use case.

Customer has geo-locations that are not precise GPS positions but rather a location with an error ellipse. The error ellipse is stored as a center lat/lon, semi-minor axis length, semi-major axis length, and an origination from north. The error ellipse centers are indexed as geo_points in elasticsearch. Customer would like to use a runtime field to generate the error ellipse polygon to the error ellipse from Elasticsearch vector tile search API.
