### ISSUE TITLE
Runtime fields: check that dependent fields are available

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#61300]
As a follow-up of #59332, we'd like to look into validating that all fields a scripted runtime field depends on (accessed through `doc` notation) are available when compiling the script. This is made possible by #60072 which allows to have a global mappings validation phase, and #60001 which allows to retrieve the list of fields that a script refers to from painless.

**Comment by javanna** [comment]
@elastic/es-core-infra could you check that this still make sense and fits in the recent improvements around accessing fields from Painless scripts? Feel free to close if it's a high hanging fruit, it seemed like a good improvement at the time, but we never got to it.

**Comment by jdconrad** [comment]
Closing this as the scripting fields api handles cases with missing fields better than doc access.

**Comment by javanna** [comment]
heya @jdconrad out of curiosity, does it mean that it is/will be possible to validate that all the fields referred to in the script are available which was the goal of this issue? I do feel like back when I opened the issue I was a bit too optimistic on what we can/should try to achieve... maybe the scope was narrower than it is today as `doc` requires a field to be mapped, while the new scripting fields API loads from _source as well, hence dependent fields may very well be unmapped. All in all I wonder if the requirement was realistic, can you expand a bit on how the scripting fields API helps in this situation?
