### ISSUE TITLE
Inconsistent fraction of a second part requirement between strict_date_optional_time_nanos and strict_date_optional_time

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#61357]
Error is thrown if date type is strict_date_optional_time_nanos and ingested data has single digit nanoseconds. I get the same error when the type is `date_nanos`, too. 
```
PUT test-date
{
  "mappings": {
    "properties": {
      "datetest-nano": {
        "type": "date",
        "format": "strict_date_optional_time_nanos"
      }
    }
  }
}

POST test-date/_doc/123
{
  "datetest-nano": "2020-06-19T07:16:17.2Z"
}
=>
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [datetest-nano] of type [date] in document with id '123'. Preview of field's value: '2020-06-19T07:16:17.2Z'"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [datetest-nano] of type [date] in document with id '123'. Preview of field's value: '2020-06-19T07:16:17.2Z'",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "failed to parse date field [2020-06-19T07:16:17.2Z] with format [strict_date_optional_time_nanos]",
      "caused_by" : {
        "type" : "date_time_parse_exception",
        "reason" : "Text '2020-06-19T07:16:17.2Z' could not be parsed, unparsed text found at index 19"
      }
    }
  },
  "status" : 400
}
```
I heard this is not a bug, since the code does enforce a minimum 3 digits nano value.
However, `strict_date_optional_time` allow one digit fraction of a second part as below:
```
PUT test-date
{
  "mappings": {
    "properties": {
      "datetest-nano": {
        "type": "date",
        "format": "strict_date_optional_time"
      }
    }
  }
}

POST test-date/_doc/123
{
  "datetest-nano": "2020-06-19T07:16:17.2Z"
} 
=>
{
  "_index" : "test-date",
  "_type" : "_doc",
  "_id" : "123",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```

I think either 1) `strict_date_optional_time_nanos` should allow 1 digit nano value or 2) the documentation should mention that `strict_date_optional_time_nanos` requires a minimum 3 digit nano value while "strict_date_optional_time" allows 1 digit millisecond value.

**Comment by astefan** [comment]
CC @pgomulka

**Comment by pgomulka** [comment]
agree on the documentation update. 
the reason why `strict_date_optional_time_nanos` is that previously it was incorrectly assumed that strict formats require more fields to be present - hence it required minimum 3 fractions of a second.  When in fact strict prefix should indicate that strict validation is enforced.
`strict_date_optional_time` on the other hand requires 1-9 fractions of a second (it can support nanoseconds). This might be the second reason why `strict_date_optional_time_nanos` was enforcing min 3 fraction of a second - to make it different to `strict_date_optional_time`. @rjernst do you happen to remember more reasoning behind this?

Worth remembering -  `strict_date_optional_time_nanos` with `date` field will lead to loose of precision on nanosecond part.

**Comment by rjernst** [comment]
> do you happen to remember more reasoning behind this?

I do not. These patterns were made by @spinscale, maybe he might remember more context.

**Comment by kiju98** [comment]
FYI, I see `strict_date_optional_time_nanos` in 7.6.2 allowed 2 digit nanoseconds as below:
```
PUT test-date
{
  "mappings": {
    "properties": {
      "datetest-nano": {
        "type": "date_nanos",
        "format": "strict_date_optional_time_nanos"
      }
    }
  }
}

POST test-date/_doc/123
{
  "datetest-nano": "2020-06-19T07:16:17.02Z"
}
=>
{
  "_index" : "test-date",
  "_type" : "_doc",
  "_id" : "123",
  "_version" : 2,
  "result" : "updated",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 1,
  "_primary_term" : 1
}
```

**Comment by pgomulka** [comment]
@kiju98 are you sure about this? I tested this as well now and it did not work - failed to be parsed. It has to have at least 3 digits for `fraction of second` part.
can you confirm the mapping?

**Comment by kiju98** [comment]
Yes, I just tested again and got the same success with the two digit nanoseconds `2020-06-19T07:16:17.02Z`. The mapping is as below:
```
GET test-date/_mapping
=>
{
  "test-date" : {
    "mappings" : {
      "properties" : {
        "datetest-nano" : {
          "type" : "date_nanos",
          "format" : "strict_date_optional_time_nanos"
        }
      }
    }
  }
}
```

**Comment by pgomulka** [comment]
@kiju98 thank you for being persistent and confirming the mapping
I think this is because of JDK you were using. Allowing parsing 2digits when 3 were required was a JDK bug
https://bugs.openjdk.java.net/browse/JDK-8230136
it was fixed in jdk 14

can you confirm java version you used?

also please bear in mind that we don't support jdk14 in 7.6. JDK 14 is supported since 7.7

**Comment by kiju98** [comment]
Thank you for the information @pgomulka 
The JDK was `openjdk version "13.0.2" 2020-01-14` bundled with Elasticsearch 7.6.2.
For 7.8.1 I used `openjdk version "14.0.1" 2020-04-14` bundled with Elasticserach 7.8.1.
So the result is consistent with your answer.

How about the documentation update? Are we waiting for @spinscale 's opinion?
