### ISSUE TITLE
Failure of 110_enrich/Enrich stats query smoke test for mixed cluster on 7.9 and 7.x in a mixed cluster

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#61421]
**Build scan**:  https://gradle-enterprise.elastic.co/s/5pc2l2ikblbl4

**Repro line**:
on 7.9

./gradlew ':x-pack:qa:rolling-upgrade:v7.9.0#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/110_enrich/Enrich stats query smoke test for mixed cluster}"

**Reproduces locally?**:  yes

**Applicable branches**:  7.x and 7.9

**Failure history**:  There are a dozen of failures over the last two days.

**Failure excerpt**:

Looks like a problem with nodes' connection:

Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : null
  1>   }
  1> }]

 java.lang.RuntimeException: Failure at [mixed_cluster/110_enrich:8]: NodeSelector [version ranges [[6.0.0-alpha1 - 7.8.99]]] rejected all nodes, living [[host=http://127.0.0.1:52827, bound=[http://127.0.0.1:52827, http://[::1]:52826], name=v7.9.0-2, version=7.9.0, roles=data,ingest,master,ml,remote_cluster_client,transform, attributes={testattr=[test], ml.machine_memory=[68719476736], ml.max_open_jobs=[20], xpack.installed=[true], transform.node=[true]}], [host=http://127.0.0.1:53028, bound=[http://[::1]:53027, http://127.0.0.1:53028], name=v7.9.0-0, version=7.9.1, roles=data,ingest,master,ml,remote_cluster_client,transform, attributes={testattr=[test], ml.machine_memory=[68719476736], upgraded=[true], ml.max_open_jobs=[20], xpack.installed=[true], transform.node=[true]}], [host=http://127.0.0.1:53259, bound=[http://127.0.0.1:53259, http://[::1]:53258], name=v7.9.0-1, version=7.9.1, roles=data,ingest,master,ml,remote_cluster_client,transform, attributes={testattr=[test], ml.machine_memory=[68719476736], upgraded=[true], ml.max_open_jobs=[20], xpack.installed=[true], transform.node=[true]}]] and dead []

**Comment by jbaiera** [comment]
Looks like the backwards compatibility is checking upgrades from 7.9.0 to 7.9.1. Neither of these fit in with the 7.8.99 max node version requirement, and thus fails the test. Likely was running fine on 7.9.0 before anything higher than that version was introduced. 

This test bug seems to be an issue only on the 7.9 branch. Closing this out since that branch will not see any more releases.
