### ISSUE TITLE
Network-safe scroll API

### ISSUE THREAD

**Issue by pauldraper** [elastic/elasticsearch#61449]
Currently, if there is a network error, the scroll API must be restarted, to prevent records from being missed.

This is inconvenient when iterating over millions of records to do maintenance (e.g. sync with another source).

Perhaps the solution is separate the fetch and advance operations of the scroll API, so that consumers could confirm reception of hits before advancing.

**Comment by dnhatn** [comment]
I am closing as we already have an [issue](https://github.com/elastic/elasticsearch/issues/26472) for this enhancement. Thank you very much for your interest in Elasticsearch.

Duplicates of #26472
