### ISSUE TITLE
Number of documents should be autocounted in client/benchmark

### ISSUE THREAD

**Issue by chenqi0805** [elastic/elasticsearch#61450]
**Elasticsearch version** (`bin/elasticsearch --version`):
current master

**Plugins installed**: []
current master

**JVM version** (`java -version`):
current master

**OS version** (`uname -a` if on a Unix-like system):
current master

**Description of the problem including expected versus actual behavior**:
In client/benchmark

gradlew -p client/benchmark run --args ' rest bulk localhost build/documents-2.json geonames type 8647880 5000'

The number of documents 8647880 is now outdated and should be replaced by 11396503. But more importantly, this number should be calculated in the benchmark instead of manual input to prevent bugs in running the benchmark.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
