### ISSUE TITLE
Record sample for formal run iterations in `BulkBenchmarkTask`

### ISSUE THREAD

**Issue by chenqi0805** [elastic/elasticsearch#61452]
**Elasticsearch version** (`bin/elasticsearch --version`):
current master

**Plugins installed**: []

**JVM version** (`java -version`):
current master

**OS version** (`uname -a` if on a Unix-like system):
current master

**Description of the problem including expected versus actual behavior**:
https://github.com/elastic/elasticsearch/blob/ab55d67de84888c170ee48d7abdc0cce74509872/client/benchmark/src/main/java/org/elasticsearch/client/benchmark/ops/bulk/BulkBenchmarkTask.java#L174

should be iteration >= warmupIterations

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
