### ISSUE TITLE
Upgrade Lucene to 8.6.2

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#61512]
Lucene 8.6.0 and 8.6.1 contain a slow memory leak which is fixed by [LUCENE-9478](https://issues.apache.org/jira/browse/LUCENE-9478) in 8.6.2. The only affected Elasticsearch version is 7.9.0. This is a blocker for the release of Elasticsearch 7.9.1 which will be fixed by upgrading Lucene to at least 8.6.2.

**Comment by s1monw** [comment]
we are working on a 8.6.2 release as soon as possible
