### ISSUE TITLE
Default Watcher history store to be asynchronous and batched

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#61557]
Currently every time a Watch runs, it generates a history document that will be indexed one at a time in a synchronous manner. A cluster that is struggling to keep up with write requests can also result in Watcher backing up.  Writing one history document synchronously has the benefit that history document is coupled pretty tightly with the Watch itself. However, it is not very efficient to synchronously index one document at a time. 

This can be addressed with the following configuration (in elasticsearch.yml) (node restarts are needed):
```
xpack.watcher.bulk.concurrent_requests: 3
xpack.watcher.bulk.actions: 10
```

The above configuration allows for 3 concurrent write requests with batch sizes of 10, for a total of 30 possible in flight watch history records. The suggestion here is to change the default to use async and bulk writes so that it writes its documents more efficiently and less likely to back up. 

Also as a side note, https://github.com/elastic/elasticsearch/pull/59464 should help with the existing synchronous defaults since it provides more room for the write thread pool, and less likely of a chance to backup due to default retry logic.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Comment by masseyke** [comment]
Done in https://github.com/elastic/elasticsearch/pull/94133.
