### ISSUE TITLE
[CI] ClassificationIT.testTooLowConfiguredMemoryStillStarts & RunDataFrameAnalyticsIT.testModelMemoryLimitLowerThanEstimatedMemoryUsage

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#61561]
**Build scan**:
https://gradle-enterprise.elastic.co/s/lqjgfg43cew4q
Note it has two failed tests

**Repro line**:
> ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testTooLowConfiguredMemoryStillStarts" -Dtests.seed=B6982EE4D20C808E -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=Australia/West -Druntime.java=11
>
> ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testModelMemoryLimitLowerThanEstimatedMemoryUsage" -Dtests.seed=B6982EE4D20C808E -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=America/Sitka -Druntime.java=11
>

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:

The method `testModelMemoryLimitLowerThanEstimatedMemoryUsage` failed for the very first faliure in last 30 days according to [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!t,params:!(pull-request,pull-request-1,pull-request-2,pull-request-bwc),type:phrases,value:'pull-request,%20pull-request-1,%20pull-request-2,%20pull-request-bwc'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(build.branch:pull-request)),(match_phrase:(build.branch:pull-request-1)),(match_phrase:(build.branch:pull-request-2)),(match_phrase:(build.branch:pull-request-bwc))))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RunDataFrameAnalyticsIT),sort:!(process.time-start,desc))). I was gonna let it pass, but then I noticed that `testTooLowConfiguredMemoryStillStarts` is a new method added in today's [changes](https://github.com/elastic/elasticsearch/commit/44d667b33faf28fdc6a8be0e6b617403d9dc1855). Both methods are touched in the change set. So there might be something going on.

**Failure excerpt**:
```
java.lang.AssertionError: |  
-- | --
  | Expected: <0L> |  
  | but: was <1L> |  


at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
-- | --
  |   | •••
  |   | at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpAnalytics(MlNativeDataFrameAnalyticsIntegTestCase.java:96) |  
  |   | at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpResources(MlNativeDataFrameAnalyticsIntegTestCase.java:87) |  
  |   | at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase.cleanUp(MlNativeIntegTestCase.java:181) |  
  |   | at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.cleanup(RunDataFrameAnalyticsIT.java:62)


```

**Comment by nik9000** [comment]
@benwtrent this looks to have failed again, this time in 7.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose/196/

**Comment by benwtrent** [comment]
Yeah, more discussion here https://github.com/elastic/elasticsearch/issues/61704

I think we have found the cause. Hopefully it will get fixed soon. It can be muted for the time being.
