### ISSUE TITLE
Add min_doc_count to bucketing aggregations

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#61591]
**Feature Proposal**

Introducing a `min_doc_count` parameter for all bucketing aggregations.

It may be useful to filter buckets that do not meet some minimum document threshold. This presents the ability for a visualization to hide buckets that have so few documents it is possible to recognize single documents in an un-anonymized way.

Existing workarounds today:

One can use the [Bucket Pipeline Selector](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-bucket-selector-aggregation.html) aggregation to filter buckets that have fewer counts. This works the same as `min_doc_count` for many bucketing aggs except the cardinality, where filtering a bucket of cardinality 1 is not the same as minimum of some number of documents from that bucket.

**feature requests:**

- cardinality: https://github.com/elastic/elasticsearch/issues/54649
- geo grid: https://github.com/elastic/elasticsearch/issues/50481

**historical conversation**

The team has primarily not implemented this up till now because there is another solution using the pipeline aggregation, and often this is behavior that can easily be implemented in the clients/UIs.

**Comment by TrueDevCoder** [comment]
Hi, I am looking for some open source tasks at beginner level, may I work on this?

**Comment by BrandNewLifeJackie26** [comment]
Hi, it's the first time I am trying to contribute to this repo. Is this still an open feature request that should be looked into? I can take some time to investigate, but it's better if there are some hint/files I can directly go into. Thanks!

**Comment by A135Y** [comment]
Is this issue still active @talevy if so I'd like to give it a go as my first contribution to ES

**Comment by wchaparro** [comment]
this should be addressed by other developments (ESQL), we're not planning on addressing this one any time soon, and it raises complications by introducing the concept to all bucketing aggs.
