### ISSUE TITLE
Show Connected Clients API

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#61609]
I want to have an Elasticsearch API to say `GET _client/connected` or something alike to show all the connected clients, like Kibana, APM, EnterpriseSearch, Beats, Logstash, AppSearch, Curator, nodejs clients etc.

Today, these connected clients might be traceable from the es/audit logs, and if they have monitoring enabled to send to some monitoring cluster, but it's still tedious and sometimes very hard to find the right ip/server to disconnect/upgrade relevant clients especially for a large organisation where different clients are usually installed/maintained by different teams, and have to maintain compatibility with the [product support matrix](https://www.elastic.co/support/matrix#matrix_compatibility).

 Maybe even stored in a system (hidden) index with the following structure:
```
"client":{
  "type": "kibana",
  "status": "connected",
  "ip":"x.x.x.x",
  "hostname": "example.com",
  "last_connected_datetime": "the day after yesterday"
}
``` 

It would be useful to have `disconnected` as an option too, but that's less of a priority.

----

I've tried to search for few seconds and unable to find such feature request existed, but admittedly, I didn't search for long enough, due to these common words in this feature requests, lots of irrelevant issues poping up in the searches and github's searchability. Let me know if there's a better solution or such issue existed already 🙇

**Comment by danhermann** [comment]
I'm going to close this as resolved with #64561.
