### ISSUE TITLE
[CI] Path replacement regex fails on Windows (backslash paths)

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#61612]
**Build scan**: https://gradle-enterprise.elastic.co/s/cr6cjsij6kmt6/tests/:build-tools:integTest/org.elasticsearch.gradle.JdkDownloadPluginFuncTest/transforms%20of%20type%20UnzipTransform%20are%20kept%20across%20builds#1

It looks like this is a result of #61533

`String.replaceAll` treats the first argument as a regex. 
On windows `testProjectDir.root.canonicalPath` will contain backslashes, which can lead to an invalid regex.

I think we want to use `String.replace` instead of `replaceAll`.

**Comment by breskeby** [comment]
In some cases we need replaceAll actually. I'll check
