### ISSUE TITLE
[CI] BWC jobs against pre-6.3 clusters failing in 7.x branch

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#61643]
Example: https://gradle-enterprise.elastic.co/s/web7xzbkycu7m

Looks like our BWC jobs on `7.x` have started failing for versions < 6.3.0 when installing test cluster plugins.

```
| ERROR: plugin directory [/dev/shm/elastic+elasticsearch+7.x+bwc/BWC_VERSION/6.2.3/nodes/centos-7&&immutable/build/elasticsearch-distros/extracted_elasticsearch_6.2.3_archive_linux_default/elasticsearch-6.2.3/plugins/x-pack] already exists; if you need to update the plugin, uninstall it first using command 'remove x-pack'
```

It seems probably this is related to #61566. @breskeby, mind taking a look?

**Comment by breskeby** [comment]
fixed via https://github.com/elastic/elasticsearch/commit/0d488cfbb9d85320992c3a06e950ad32549cdce7

**Comment by rjernst** [comment]
Fixed as of https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.x/job/elastic+elasticsearch+7.x+default-distro+bwc/.
