### ISSUE TITLE
[CI] Build tools tests failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#61645]
Looks like some our buildsrc tests are failing on Windows due to path escape character stuff 🤦 

**Build scan**:
https://gradle-enterprise.elastic.co/s/bldsp2dagqbua/tests/failed

**Failure excerpt**:
```

java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3 |  
-- | --
  | C:\Users\jenkins\AppData\Local\Temp\junit601039288614214022

```

**Comment by mark-vieira** [comment]
Right now this is only happening on `7.x` but only because I think on `master` it's otherwise blocked by #61647 which is simply failing before these tests can run.

**Comment by breskeby** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/61706
