### ISSUE TITLE
Add new index for synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/elasticsearch#61665]
For the new Elastic agent, there are two current index types are logs and metrics. Synthetics doesn't really fit with that, we should add a new synthetics index for data reported from heartbeat. This would be under the 'monitoring' category.

A question I have is about the fields that should be included in ES. We don't really have a 'minimal' subset. We need all our fields for the Uptime UI to be rendered correctly. Should we include all our field mappings with the index in ES? 

CC @ruflin @ph

**Comment by dakrone** [comment]
@andrewvc as I understand it, we only need a template (similar to our `logs-*-*` and `metrics-*-*` templates. We don't need the index to be pre-created, is that right?

**Comment by ruflin** [comment]
I would suggest we use the same templates we have for logs / metrics at the moment for synthetics. The detailed data_stream templates will be set up Uptime before data is shipped but having the template in Elasticsearch ensures nobody messed with the indices/data streams in advance.

**Comment by andrewvc** [comment]
@ruflin that's fine with me. 

@dakrone yes, I believe that's correct. @ruflin is there anything else needed?

**Comment by ruflin** [comment]
A PR to get it into ES :-)

**Comment by andrewvc** [comment]
@dakrone I take it you're the one to open the PR?

**Comment by dakrone** [comment]
@andrewvc I have been on vacation for the past 11 days, but yes, either me or someone on the core/features team would likely work on this

**Comment by dakrone** [comment]
@ruflin 

> I would suggest we use the same templates we have for logs / metrics at the moment for synthetics.

These two templates have slightly different mappings (logs have a "message" field), should the `synthetics-*-*` template mappings include a "message" field?

**Comment by ruflin** [comment]
My guess is that we don't need the `message` as so far synthetics will load its own templates for all indices.
