### ISSUE TITLE
Create a new discovery plugin for DNS SRV records

### ISSUE THREAD

**Issue by matthewbarr** [elastic/elasticsearch#6171]
It looks like it'd be fairly easy to use DNS SRV records to find the list of hosts to use in unicast mode for discovery.   It'd be very easy to use this w/ a local d-dns server, or Route53, etc, and not have to worry about any credentials for a cloud provider or specialty plugins.

**Comment by nilsga** [comment]
This would certainly be a very useful feature. Is this being considered?

**Comment by dakrone** [comment]
@matthewbarr this sounds like a great idea, would you be willing to take a stab at a plugin?

**Comment by grantr** [comment]
I've got a working prototype of this at https://github.com/grantr/elasticsearch-srv-discovery.

**Comment by dakrone** [comment]
Okay, closing this since @grantr has a plugin for it -

@grantr would you like me to add this to the list of community plugins?

**Comment by grantr** [comment]
@dakrone sure. It's just a prototype now but I hope to make it a real project in the medium term.
