### ISSUE TITLE
Make msearch line format less lenient

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61771]
A user recently discovered that we allow training closing brackets in `_msearch` request lines (see https://github.com/elastic/elasticsearch/pull/61353).
It seems we parse only the first complete JSON object to a map, then discarding the rest of the line in MultiSearchRequest#readMultiLineFormat, allowing requests like the following:

```
GET my-index/_msearch
{"index": "my-index"}}}}
{"query" : {"match_all" : {}}}}}}
{"index": "my-index"}{ "this is" : "ignored as well"}
{"query" : {"match_all" : {}}}
```

While this is just a leniency that shouldn't affect the correct behaviour of the search, maybe we shouldn't allow this and error if we detect anything after parsing the initial json object.

**Comment by pranutyagi** [comment]
Hi, I am a first timer and want to work on this issue, can you please give more details on how to raise a pull request?

**Comment by Utsavk** [comment]
Hi @cbuescher , Can I give it try? It will be my first contribution.

**Comment by sujaysamanta** [comment]
Hello team,
This is my first time here and I want to contribute, is this issue still available to be picked up ..?
