### ISSUE TITLE
Monitoring Enhancement: Cluster-wide bulk rejections overview

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#61810]
It would be helpful if the ES Monitoring overview page had a bulk rejections overview visualization, instead of having to drill into each node first.    This is something that many users must create custom today from the monitoring data.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
