### ISSUE TITLE
Stopwords generated by word_delimiter_graph are raising exceptions

### ISSUE THREAD

**Issue by buinauskas** [elastic/elasticsearch#61848]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.0.

Using official Elasticsearch Docker image.

**Description of the problem including expected versus actual behavior**:

Combination of `word_delimiter_graph` and `stop` token filter may raise a runtime error. I've encountered it with a custom French analyzer with a combination of an elision, quote and a stopword.

This appears to be a problem when `generate_word_parts` is set to true (default) and generated word parts may be stopwords.

However exception is raised only during `_search` phrase. I tried to debug my analyzer using `_analyze` and didn't get exactly the same behavior. `_search` was failing, but `_analyze` was parsing it successfully and potentially bringing me back partial results.

**Steps to reproduce**:

```json
PUT /test
{
  "settings": {
    "analysis": {
      "filter": {
        "stop": {
          "ignore_case": "true",
          "type": "stop",
          "stopwords": "_french_"
        },
        "preserve_hashtag": {
          "type": "word_delimiter_graph",
          "type_table": [
            "# => ALPHANUM"
          ],
          "preserve_original": "true"
        }
      },
      "analyzer": {
        "french": {
          "filter": [
            "preserve_hashtag",
            "stop"
          ],
          "tokenizer": "whitespace"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "title": {
        "type": "text",
        "analyzer": "french"
      }
    }
  }
}

# Throws an exception
GET /test/_search
{
  "query": {
    "match": {
      "title": "t'il goal"
    }
  }
}

# Silently fails
GET /test/_analyze
{
  "analyzer": "french", 
  "text": "t'il goal"
}
```

_search endpoint raises the following exception:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: Index 0 out of bounds for length 0",
        "index_uuid" : "tm2h-t9WR8-YFhN2ZFZjLw",
        "index" : "test"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test",
        "node" : "pYU97gIoSuK2VERyoVHEyA",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: Index 0 out of bounds for length 0",
          "index_uuid" : "tm2h-t9WR8-YFhN2ZFZjLw",
          "index" : "test",
          "caused_by" : {
            "type" : "array_index_out_of_bounds_exception",
            "reason" : "Index 0 out of bounds for length 0"
          }
        }
      }
    ]
  },
  "status" : 400
}
```

I've managed to fix my use case by applying French token elision filter, but there might be other scenarios when this could be potentially raised.

**Comment by jimczi** [comment]
@romseygeek can you take a look ?

**Comment by romseygeek** [comment]
This is caused by a lucene bug, https://issues.apache.org/jira/browse/LUCENE-8717.  If we remove the `stop` filter from the analyzer configuration described above, we get the following output from `_analyze`:
```
{
  "tokens" : [
    {
      "token" : "t'il",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "word",
      "position" : 0,
      "positionLength" : 2
    },
    {
      "token" : "t",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "il",
      "start_offset" : 2,
      "end_offset" : 4,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "goal",
      "start_offset" : 5,
      "end_offset" : 9,
      "type" : "word",
      "position" : 2
    }
  ]
}
```

The second token here is the articulation point, and it needs to be present for the token graph to be correctly converted into an automaton in QueryBuilder.  Adding the stopword filter removes the second and third tokens, and so the articulation point doesn't get located properly and we end up with the exception (in a test setup this actually trips assertions before we get to the IndexOutOfBoundsException).

Unfortunately it's difficult to find workarounds for this, other than "don't use stopwords" or "don't use WDF".  We could try and detect earlier that there's been a problem in generating a token graph, but that just gets us a nicer error message, rather than a fix for the underlying problem.

**Comment by bytepeak** [comment]
@buinauskas Hello , I have encountered a similar problem. I wonder if it has been solved?
