### ISSUE TITLE
MlMappingsUpgradeIT testMappingsUpgrade

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#61908]
**Build scan**:
https://gradle-enterprise.elastic.co/s/5msxbxbgw6bbi/tests/:x-pack:qa:rolling-upgrade:v7.10.0%23upgradedClusterTest/org.elasticsearch.upgrades.MlMappingsUpgradeIT/testMappingsUpgrade#1

**Repro line**:
./gradlew ':x-pack:qa:rolling-upgrade:v7.10.0#upgradedClusterTest' --tests "org.elasticsearch.upgrades.MlMappingsUpgradeIT.testMappingsUpgrade" -Dtests.seed=D2B94DCD19B71635 -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=11 

**Reproduces locally?**:
NO

**Applicable branches**:
master

**Failure history**:
Since #61834

**Failure excerpt**:
java.lang.AssertionError: Error the template mappings [.ml-config] and index mappings [.ml-config] are not the same 
   Keys in the index missing from the template mapping: [properties.deleting.type]

**Comment by ywangd** [comment]
This fails for 7.x as well:
* https://gradle-enterprise.elastic.co/s/fh6spnoncer7e
* https://gradle-enterprise.elastic.co/s/uaqe3aqbtkav2
And a bunch of others for different bwc versions

They can be reproduced locally with 
> ./gradlew ':x-pack:qa:rolling-upgrade:v7.6.2#upgradedClusterTest' --tests "org.elasticsearch.upgrades.MlMappingsUpgradeIT.testMappingsUpgrade" -Dtests.seed=F2CA8D7ABE77E726 -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=America/Maceio -Druntime.java=8
>
I noticed the test on master is already muted with #61909. I am backporting it to 7.x (#62136)

**Comment by hendrikmuhs** [comment]
The test is now failing for `.ml-notifications-000001` in `7.x`, see e.g. https://gradle-enterprise.elastic.co/s/aniecxdcpnd4g

In agreement with the other devs, I did _not_ mute the whole test (we would loose important coverage), but only the part for [`.ml-notifications-000001`](https://github.com/elastic/elasticsearch/commit/ab259d37a7d4fded8200e525a20b75f54242d4f4).

The issue now only applies to `7.x`, because only there upgrade from `7.any` to `7.x` is possible.

**Excerpt**:
```
11:59:48 org.elasticsearch.upgrades.MlMappingsUpgradeIT > testMappingsUpgrade FAILED
11:59:48     java.lang.AssertionError: Error the template mappings [.ml-notifications-000001] and index mappings [.ml-notifications-000001] are not the same
11:59:48     Keys in the template missing from the index mapping: [dynamic, properties.message.fields.raw.type]
11:59:48     Keys in the index missing from the template mapping: [properties.job_id.fields.keyword.ignore_above, properties.job_id.fields.keyword.type, properties.job_type.fields.keyword.ignore_above, properties.job_type.fields.keyword.type, properties.level.fields.keyword.ignore_above, properties.level.fields.keyword.type, properties.message.fields.keyword.ignore_above, properties.message.fields.keyword.type, properties.node_name.fields.keyword.ignore_above, properties.node_name.fields.keyword.type]
11:59:48     Values for key [properties.job_id.type] are different
11:59:48         template value [keyword] String
11:59:48         index value [text] String
11:59:48     Values for key [properties.job_type.type] are different
11:59:48         template value [keyword] String
11:59:48         index value [text] String
11:59:48     Values for key [properties.level.type] are different
11:59:48         template value [keyword] String
11:59:48         index value [text] String
11:59:48     Values for key [properties.node_name.type] are different
11:59:48         template value [keyword] String
11:59:48         index value [text] String
11:59:48     Values for key [properties.timestamp.type] are different
11:59:48         template value [date] String
11:59:48         index value [long] String
```

**Comment by davidkyle** [comment]
I've temporarily unmuted to above failure with some extra debug logging. #62342

**Comment by davidkyle** [comment]
The extra logging I added showed that in every single failure the message being written to `.ml-notifications-000001` before the index was installed is
```
Loading model snapshot [XXX] with latest_record_timestamp [YYY]
```

This makes sense as when an AD job moves to an upgraded node and the master isn't upgraded the index template has not been put.

What is confusing though is that the default dynamic mappings should break the UI which runs aggregations on the fields incorrectly mapped as `text`. Testing showed the failure to be obvious (error on the overview page) and significant (no jobs shown) yet I cannot find any bug reports. 🤔

**Comment by droberts195** [comment]
> This makes sense as when an AD job moves to an upgraded node and the master isn't upgraded the index template has not been put.

This won't happen in four cases:

1. Persistent task assignment is disabled during the upgrade - Cloud does this
2. ML upgrade mode is enabled during the upgrade - we advise people that this is best practice (though not compulsory)
3. People stop their jobs before upgrading and restart them after the upgrade is complete - we used to advise this before 6.3, and it's still the only way to ensure persisted state is the absolute latest available
4. The versions being upgraded from and to are either both pre-7.5.0 or both 7.5.0+ - there is only a problem for upgrades that span the 7.5.0 boundary

So maybe all our upgrades have fallen into one of these categories.  Then again, no, it seems impossible that there hasn't been a single upgrade from 7.4 or earlier to 7.5 or later that was done with jobs shuffling between nodes during the upgrade.  So it is astonishing that we haven't had a single bug report about this.

**Comment by droberts195** [comment]
Another failure in https://gradle-enterprise.elastic.co/s/7ja326o652k4w, this time on the `.ml-stats` index:

```
java.lang.AssertionError: Error the template mappings [.ml-stats] and index mappings [.ml-stats-000001] are not the same
Keys in the template missing from the index mapping: [properties.hyperparameters.properties.alpha.type, properties.hyperparameters.properties.gamma.type, properties.hyperparameters.properties.lambda.type, properties.hyperparameters.properties.soft_tree_depth_limit.type, properties.hyperparameters.properties.soft_tree_depth_tolerance.type]
```

**Comment by droberts195** [comment]
There have been a few failures upgrading the `.ml-stats` index mappings now, so I have opened #63234 to mute that bit of the test.

**Comment by davidkyle** [comment]
The `.ml-notifications-000001` failure is fixed by #63063 and I've unmuted the test in #63388 (7.x only, master is not affected)

**Comment by benwtrent** [comment]
@droberts195 @davidkyle can we close this? I think the original work around index update test is fixed.

**Comment by davidkyle** [comment]
Closing as the test failure and related issued are all resolved
