### ISSUE TITLE
ClassificationIT.testTooLowConfiguredMemoryStillStarts fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#61913]
The test `ClassificationIT.testTooLowConfiguredMemoryStillStarts` fails regularly on CI on both `master` and `7.x` branches.

**Build scan**:
https://gradle-enterprise.elastic.co/s/lb4svvfnvgrgg

**Repro line**:

**Reproduces locally?**:
No

**Applicable branches**:
`master` and `7.x`

**Failure history**:

[Build stats for last 30 days](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-07-05T13:38:09.491Z',mode:absolute,to:'2020-09-03T13:38:09.492Z'))&_a=(columns:!(branch,test),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:test,negate:!f,params:(query:testTooLowConfiguredMemoryStillStarts,type:phrase),type:phrase,value:testTooLowConfiguredMemoryStillStarts),query:(match:(test:(query:testTooLowConfiguredMemoryStillStarts,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.ml.integration.ClassificationIT%22'),sort:!(time,desc)))

**Failure excerpt**:
It looks like the test leaves transient cluster  metadata but I'm not sure why. The most notable `AssertionError` is

```
org.elasticsearch.xpack.ml.integration.ClassificationIT > testTooLowConfiguredMemoryStillStarts FAILED
    java.lang.AssertionError: 
    Expected: <0L>
         but: was <1L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpAnalytics(MlNativeDataFrameAnalyticsIntegTestCase.java:96)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpResources(MlNativeDataFrameAnalyticsIntegTestCase.java:87)
        at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase.cleanUp(MlNativeIntegTestCase.java:181)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.cleanup(ClassificationIT.java:111)

    java.lang.AssertionError: test leaves transient cluster metadata behind
    Expected: an empty collection
         but: <[logger.org.elasticsearch.xpack.ml.dataframe.inference, logger.org.elasticsearch.xpack.core.ml.inference]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:545)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2054)
```

but skimming through the logs also show some ERROR messages like:

```
» ERROR][o.e.x.m.d.p.AnalyticsProcessManager] [integTest-0] [test_model_memory_limit_lower_than_estimated_memory_usage] Marking task failed; [test_model_memory_limit_lower_than_estimated_memory_usage] analytics process stopped unexpectedly: Input error: memory limit 1MB is too low to perform analysis. You need to give the process at least 4MB, but preferably more.
```

**Comment by benwtrent** [comment]
I think the test failed because it got an old snapshot of the c++ binary. I will investigate.

**Comment by tlrx** [comment]
Given the frequency of the failures, the test will be muted in #61914 and #61915.

**Comment by tlrx** [comment]
> I think the test failed because it got an old snapshot of the c++ binary. I will investigate.

@benwtrent Note that it failed regularly on the last 30 days - but maybe for different causes

**Comment by benwtrent** [comment]
@tlrx thanks. I thought the new binary would fix it, but alas this failing build had the newest C++ binary. 

some internal race condition is definitely occurring. Feel free to mute. Back to the drawing board :(

**Comment by benwtrent** [comment]
When a job is forced closed, we simply remove the task from the cluster state and return to the caller. 

This means we immediately perceive the job as closed, even though we persist progress during the `onCancelled()` callback.

To prevent this from happening, I have opened a PR that shortcuts progress storage if the previously stored progress is the same.

When a job is failed, we persist the progress. 

This means that when `onCancelled()` is called after a force close call, the current progress will be the same as the progress already persisted, and nothing will happen. 

Hopefully, this fixes this race condition.
