### ISSUE TITLE
ActiveDirectorySessionFactoryTests fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#61924]
**Build scan**:
https://gradle-enterprise.elastic.co/s/74dhunlfmfns4

**Repro line**:
`./gradlew ':x-pack:qa:third-party:active-directory:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests" -Dtests.seed=7DC1AAA8FBD287F3 -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=11
`

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
It failed [4 times](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-07-05T14:44:15.202Z',mode:absolute,to:'2020-09-03T14:44:15.202Z'))&_a=(columns:!(branch,test),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests%22'),sort:!(time,desc))) today: 1 on master and 3 times on pull requests. 

**Failure excerpt**:

> 
> org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests > classMethod FAILED
>     com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests: 
>        1) Thread[id=209, name=Health Check Thread for LDAPConnectionPool(serverSet=FailoverServerSet(serverSets={SingleServerSet(server=localhost:32789, includesAuthentication=false, includesPostConnectProcessing=false)}), maxConnections=20), state=TIMED_WAITING, group=TGRP-ActiveDirectorySessionFactoryTests]
>             at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
>             at java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
>             at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
>             at java.base@11.0.2/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:458)
>             at app//com.unboundid.ldap.sdk.LDAPConnectionPoolHealthCheckThread.run(LDAPConnectionPoolHealthCheckThread.java:119)
>         at __randomizedtesting.SeedInfo.seed([7DC1AAA8FBD287F3]:0)
> 
> 
> org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests > classMethod FAILED
>     com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
>        1) Thread[id=209, name=Health Check Thread for LDAPConnectionPool(serverSet=FailoverServerSet(serverSets={SingleServerSet(server=localhost:32789, includesAuthentication=false, includesPostConnectProcessing=false)}), maxConnections=20), state=TIMED_WAITING, group=TGRP-ActiveDirectorySessionFactoryTests]
>             at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
>             at java.base@11.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
>             at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
>             at java.base@11.0.2/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:458)
>             at app//com.unboundid.ldap.sdk.LDAPConnectionPoolHealthCheckThread.run(LDAPConnectionPoolHealthCheckThread.java:119)
>         at __randomizedtesting.SeedInfo.seed([7DC1AAA8FBD287F3]:0)

**Comment by jkakavas** [comment]
This failed only on september 3 and 4 , because of https://github.com/elastic/elasticsearch/pull/61859 which was later reverted. As such, I'm closing the issue
