### ISSUE TITLE
Allow hot-threads to execute an API request directly

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#61947]
Hot threads is a great diagnostic tool to look at a cluster's activity generally.  But it is also very useful when trying to capture another API's side-effects.  This requires the user to queue up the API-under-investigation and a hot-threads request, then rapidly try to execute them back to back.

It'd be useful if the hot-threads API could optionally execute an API directly.  So you call hot-threads and tell it to execute an API (potentially with a body and request parameters).  Hot threads would then start the API call and begin to poll threads as normal.

This would hopefully simplify the process of gathering diagnostics of a specific API call for the user, and make it more certain that hot-threads captures the intended target.

**Comment by pugnascotia** [comment]
@polyfractal would it be possible to get some more context on this suggestion?

**Comment by polyfractal** [comment]
@pugnascotia  Say you have a search request that has strange characteristics and you want to investigate how it is executing on each node (seeing how the search is executing in hot_threads is often very insightful to determine what optimization paths are chosen, how it's accessing the index/doc_values, potential bottlenecks, etc).  Today, the user needs to:

1. Queue up the search request in one terminal
2. Queue up the hot_threads request in a separate terminal
3. Execute search request, switch terminals, execute hot_threads
4. If the search request executes quickly, you might have missed it via hot_threads and have to try again

This is particularly problematic when asking users to perform the above process, since you're never _quite_ sure if an empty hot_threads is because there was nothing interesting... or if the user just didn't execute the dance quickly enough.

The main use would probably be search/agg requests... but just the other day I saw a similar situation with a cat/indices API.  So I think it'd be generally useful to execute APIs as an investigative mechanism.

Hope that helps!  Lemme know if it's unclear, happy to chat more realtime.

**Comment by jaymode** [comment]
The core/infra team discussed this and decided that we are not against the idea but would not have bandwidth to work on this in the near future. The team also suggested that it may be worthwhile to look at flipping the feature from being part of the hot threads API to being part of the REST framework in general that is triggered by query parameters to profile the threads of a request. There are wrinkles here including the output format as the hot threads output is plain text and how would we output this information with the API's response. An additional though is to keep it specific to the search API.  

The @elastic/es-analytics-geo also discussed it recently to see if there was interest and bandwidth to work on it. For now it seems like there is interest but this wouldn't be a top priority. As such, I'm adding the help wanted label.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
