### ISSUE TITLE
[CI] Running resolveAllDependencies tasks results in build failure

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#61945]
Looks like our newly added artifact transforms don't play well with `resolveAllDependencies` since just calling `resolve()` on those configurations doesn't mean the backing artifacts have been generated, and in any case, we shouldn't be resolving configurations for locally built artifacts anyhow. We should probably exclude these.

https://gradle-enterprise.elastic.co/s/2aynnrgfsyake

**Comment by mark-vieira** [comment]
@breskeby you mind taking a look? This is breaking our CI image builds at the moment.

**Comment by breskeby** [comment]
Will do. I should run this task as part of my integration work 🤷🏻‍♂️

René Gröschke
@breskeby
