### ISSUE TITLE
Cannot change http exporter to local

### ISSUE THREAD

**Issue by s-nel** [elastic/elasticsearch#61952]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.0

**Plugins installed**: []

**JVM version** (`java -version`): Cloud

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

When updating an exporter from `http` type to `local` type I would expect to be able to set `host` to `null` because it is unused, but when I try Elasticsearch returns a 400 response:

```json
{
  "status": 400,
  "error": {
    "caused_by": {
      "caused_by": {
        "reason": "host list for [xpack.monitoring.exporters.my_exporter.host] is empty but type is [local]",
        "type": "settings_exception"
      },
      "reason": "Failed to parse value [[]] for setting [xpack.monitoring.exporters.my_exporter.host]",
      "type": "illegal_argument_exception"
    },
    "root_cause": [
      {
        "reason": "illegal value can't update [xpack.monitoring.exporters.my_exporter.host] from [[\"<url>\"]] to [[]]",
        "type": "illegal_argument_exception"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "illegal value can't update [xpack.monitoring.exporters.my_exporter.host] from [[\"<url>\"]] to [[]]"
  }
}
```

**Steps to reproduce**:

1. Add a `http` exporter:
   ```json
   PUT _cluster/settings
   {
     "persistent": {
       "xpack.monitoring.exporters.my_exporter": {
         "type": "http",
         "enabled": true,
         "host": [
           "<url>"
         ],
         "auth": {
           "username": "<username>",
           "password": "<password>"
         }
       },
       "xpack.monitoring.collection.enabled": true
     }
   }
   ```
2. Change the exporter to `local` type:
   ```json
   PUT _cluster/settings
   {
     "persistent": {
       "xpack.monitoring.exporters.my_exporter": {
         "type": "local",
         "enabled": true,
         "host": null,
         "auth.username": null,
         "auth.password": null
       },
       "xpack.monitoring.collection.enabled": true
     }
   }
   ```
3. Notice that 400 is returned saying that an empty host cannot be specified for type `local`

A workaround is to clear out all the settings before configuring the local exporter:
```
PUT _cluster/settings
{
  "persistent": {
    "xpack.monitoring.exporters.my_exporter": {
      "type": null,
      "enabled": null,
      "host": null,
      "auth.username": null,
      "auth.password": null
    }
  }
}
```

**Provide logs (if relevant)**:

**Comment by danhermann** [comment]
Fwiw, the code doesn't accommodate changing the type of an exporter. We should probably explicitly reject any attempt to do that.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
