### ISSUE TITLE
Using missing_bucket with a composite aggregation with a date_histogram source doesn’t seem to create missing buckets

### ISSUE THREAD

**Issue by acommend** [elastic/elasticsearch#61953]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0

**Plugins installed**: []

**JVM version** (`java -version`): openjdk "12.0.2" 2019-07-16

**OS version** (`uname -a` if on a Unix-like system): Windows 10 Professional

**Description of the problem including expected versus actual behavior**:

Using missing_bucket with a composite aggregation with a date_histogram source doesn't seem to create missing buckets.  In the "Steps to reproduce" below, 2 documents are created with a date field that are 45 minutes apart.  Using a composite aggregation date_histogram source with a fixed_interval set to 15m the expected outcome should be 3 buckets, one for each 15 minute interval with the interval in the middle containing 0 doc_count.  Instead only the first and last 15 minute intervals are present in the response.  Note that I initially tried to get the possible bug confirmed via the forums prior to posting it here but no one responded to the post.

**Steps to reproduce**:

Enter the following in a Kibana console to reproduce the problem:

 1. Create index with date mapping for time field
```
PUT /test
{
  "mappings": {
    "properties": {
      "myDate":    { "type": "date" }
    }
  }
}
```
 2. Add test data
```
PUT /test/_doc/1
{
  "myDate": "2020-08-03T15:00:00"
}

PUT /test/_doc/2
{
  "myDate": "2020-08-03T15:45:00"
}
```

 3. Create composite aggregation with date histogram with 15 minute intervals
```
GET /test/_search
{
  "size": 0,
  "query": {
    "match_all": {}
  },
  "aggregations": {
    "intervals": {
      "composite": {
        "sources": [
          {
            "test_date_histogram": {
              "date_histogram": {
                "field": "myDate",
                "fixed_interval": "15m",
                "missing_bucket": true
              }
            }
          }
        ]
      }
    }
  }
}
```

**Provide logs (if relevant)**:

Response from Kibana console:
```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "intervals" : {
      "after_key" : {
        "test_date_histogram" : 1596469500000
      },
      "buckets" : [
        {
          "key" : {
            "test_date_histogram" : 1596466800000
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "test_date_histogram" : 1596469500000
          },
          "doc_count" : 1
        }
      ]
    }
  }
}

**Comment by polyfractal** [comment]
Hmm so this isn't necessarily a bug with `missing_bucket`, but it _is_ some missing functionality in composite/date_histo.

The `missing_bucket` parameter is used to add `null` keys when a document is missing a field.  In this case, there are only two documents and they both have the timestamp field, so there are no missing keys that need to be emitted as `null`.

What's missing here is the ability for date_histo to use `min_doc_count` parameter.  In a normal, non-composite date_histo, `min_doc_count: 0` ensures that buckets are emitted even if no documents landed in those buckets which for date_histo means it "fills in" the gaps.  Composite currently doesn't support that parameter and so you get the behavior you're seeing.

I'm going to swap this label from bug to enhancement, but leave it open since I agree it'd be useful to support. :)

**Comment by madisonb** [comment]
Is there documentation as to what the composite histogram/date histogram lacks vs the pure elasticsearch supported version?

I came across this ticket trying to debug why my composite histogram scripted aggregation can't bucket on `_score` and figured I would ask.

Doesn't work:
```
  "aggs": {
    "my_buckets": {
      "composite": {
        "sources": [
          {
            "score_buckets": {
              "histogram": {
                "script": "_score",
                "interval": 0.1
              }
            }
          }
        ]
      }
    }
  }
```

Works: 
```
  "aggs": {
    "score_buckets": {
      "histogram": {
        "script": "_score",
        "interval": 0.1
      }
    }
  }

```

**Comment by not-napoleon** [comment]
Related to #60043
