### ISSUE TITLE
InternalEngine doesn't throttle when indexing buffer limit is reached

### ISSUE THREAD

**Issue by sohami** [elastic/elasticsearch#61959]
**Elasticsearch version** (7.7):

**JVM version** (jdk-11):

**Description of the problem including expected versus actual behavior**:
1) I was seeing an issue where the JVM usage of the ES process went up very high to 97% and was analyzing the heap dump for it. In this case, one shard of an index end up consuming around 25GB of JVM out of 32GB. The index was receiving very high ingestion workload. I was surprised to see that and was trying to understand why indexingBuffer based throttling didn't kicked in. I can see from the dump, that the indexingBuffer limit is breached for one ES shard (or Lucene index) and IndexingMemoryController detects that and activates the throttling mode for the shard. But I was expecting that with throttling mode activated the InternalEngine will start throttling any new indexing requests and also initiates the flush process to relieve the memory pressure. However, while looking into the code it looks like InternalEngine doesn't throttle the new indexing requests if it's not because of recovery. It looks to me even though the indexingBuffer limit is breached by one of the Lucene index, it can still keep consuming the memory by the new indexing requests and increase the overall memory usage by the Lucene index or ES shard. If the ingestion workload is very high this can consume memory very fast.

Ref: https://github.com/elastic/elasticsearch/pull/22721/commits/bd1c30ffa5c775981c7678432609b669147b9202#diff-74a25d57bbb52202a04fe43d8632172eR547

It looks like with this commit (https://github.com/elastic/elasticsearch/pull/22721)  the check was reversed to apply throttling only in recovery scenarios. 

Please let me know if my understanding is correct. I can open a PR with the fix.

**Comment by ywelsch** [comment]
Relates https://github.com/elastic/elasticsearch/pull/61768

**Comment by sohami** [comment]
@ywelsch - I was also thinking that shouldn't there be a timed wait while acquiring the throttle lock `throttle.acquireThrottle`. In cases when a write thread takes the lock and end up blocking somewhere in the Lucene layer (because of some bug), that may end up blocking all the other indexing thread as well since they will wait indefinitely for this throttle lock. Instead based on timed throttle, if a writer thread doesn't get the lock its request can be rejected by the engine.

**Comment by ywelsch** [comment]
I think the untimed lock is fine. I'm not aware of any such bug, and I would rather not like the system to silently work around such a bug if it were to exist.

**Comment by sohami** [comment]
While investigating this issue only I found the case where one of the write thread was blocked indefinitely. I have opened a bug with Lucene here: https://issues.apache.org/jira/browse/LUCENE-9508
