### ISSUE TITLE
Improve compile time validation of runtime fields

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#61988]
We should improve the validation that we perform at compile time for runtime fields, so that scripts that cause problems at runtime don't even make it into the mappings.

- [ ] Detect cyclic dependencies at compile time
- [ ] Forbid non-fixed lookups (e.g. `doc[doc[‘field’]]` or `doc[param1 + param2]`) (#60002)
- [ ] Detect too many references at compile time
- [ ] validate the return type when a field is accessed through `doc['field']`

**Comment by stu-elastic** [comment]
Hi @javanna, I think we can close this one as it hasn't been a problem.  Let's cut new issues if we see customer issues with the lack of compile-time checking.
