### ISSUE TITLE
Incorrect link to read-only action implementation?

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#62025]
In [the ILM documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-readonly.html#) we mention;

> Makes the index [read-only](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings).

However in that link there's no mention of what setting is the actual read-only one. And looking through them I am not sure this is the correct reference. Should it be pointing to [`index.blocks.read_only`](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-blocks.html#index-block-settings) instead?

**Comment by ORDAZ11-AR** [comment]
@elasticmachine

**Comment by andreidan** [comment]
@markwalkom thanks for raising this. The setting being configured by the `readonly` action is `index.blocks.write` (set to `true)
