### ISSUE TITLE
RestClient should allow compressing request bodies

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch#62044]
The Rest client has transparent support for compressed responses, but no support for compressed requests.

The low-level client should make it easy to compress request bodies, either globally or per-request. The high-level client should automatically benefit from this feature.

Compressing the request body should be driven by adding the corresponding header on `RequestOptions`, e.g.:

```java
RequestOptions gzipOptions = RequestOptions.DEFAULT.toBuilder().addHeader("Content-Encoding", "gzip").build();
esClient.search(new SearchRequest("foo"), gzipOptions);
```

We can also add a more convenient `RequestOption.compress(true)` but ultimately that will set the header option as illustrated above, since that header can always be set directly.

**Comment by cykl** [comment]
This would be a great improvement. I spent a few hours today trying to compress request bodies but failed to find a user-level workaround. 

Any user who pay outgoing data transfer should be greatly interested by this feature :dollar:
