### ISSUE TITLE
SqlClearCursorActionIT.testAutoCursorCleanup failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#62046]
**Build scan**:
https://gradle-enterprise.elastic.co/s/vww2nhtqvllnq

**Repro line**:
```
 ./gradlew ':x-pack:plugin:sql:internalClusterTest' --tests "org.elasticsearch.xpack.sql.action.SqlClearCursorActionIT.testAutoCursorCleanup" \
  -Dtests.seed=ED48C0414093BFA8 \
  -Dtests.security.manager=true \
  -Dtests.locale=de \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
First ever failure I could find at least.

I have not muted the test because this is the first failure and it does not reproduce 

**Failure excerpt**:
```
java.lang.AssertionError: expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([ED48C0414093BFA8:2A4953187A7F7CBA]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.xpack.sql.action.SqlClearCursorActionIT.testAutoCursorCleanup(SqlClearCursorActionIT.java:85)
```

**Comment by romseygeek** [comment]
Interestingly it just failed on a PR CI run for me as well:

https://gradle-enterprise.elastic.co/s/s5vuirc57c4ws/console-log?task=:x-pack:plugin:sql:internalClusterTest

**Comment by probakowski** [comment]
Another instance https://gradle-enterprise.elastic.co/s/45v3lhr2vdy42/tests/:x-pack:plugin:sql:internalClusterTest/org.elasticsearch.xpack.sql.action.SqlClearCursorActionIT/testAutoCursorCleanup#1

**Comment by ywangd** [comment]
Failed again on master with openjdk 15: https://gradle-enterprise.elastic.co/s/hmc76oys6hcvy
