### ISSUE TITLE
multi_match query excluded fields

### ISSUE THREAD

**Issue by db-ruslan** [elastic/elasticsearch#62075]
Could you please consider adding excluded fields along with "fields" attribute to the multi_match query.

Scenario:
Application might have some data generated by users and searchable by all users (authenticated or not), but nobody should be able to associate data with particular user except when particular user would like to search for all of the data he created.

For example:
Users sell some items and listings should be available to all, but nobody should be able to search for all listings for a given user.

**Comment by jimczi** [comment]
Using query options to hide content is fragile and not something that we want to rely on so if your use case is to prevent users from seeing or searching specific you should check [x-pack security](https://www.elastic.co/guide/en/elasticsearch/reference/current/field-level-security.html). With this module you can define document and field level security for different roles and ensure that the access is secured for all.

**Comment by db-ruslan** [comment]
The scenario is not about hiding something, it is about disabling backward association.

For example:
A user might be commenting under a different posts and  each post, and comment should be searchable, but system should prevent scenario when somebody would simply enter a user id in the search box and find all of the post particular user commented under. 

There is no need to hide content, or information about who posted/commented, it should be searchable, but nobody should be able to search all the posts particular user commented under. The value here is not posts or comments, it is knowledge about interests of particular user derived from the posts she/he commented under.

So, it makes sense to store all of the comments and posts in the same index and perform multi_match search on all of the fields except "user_id".
