### ISSUE TITLE
Sub-aggregations when terms aggregation `min_doc_count` is 0 return a server error (new in 7.9.0)

### ISSUE THREAD

**Issue by jamieparkinson** [elastic/elasticsearch#62084]
**Elasticsearch version**: 7.9.0 on Elastic Cloud, verified on local official Docker image
**Plugins installed**: _N/A_

**Description of the problem including expected versus actual behavior**:
Performing a search that includes a terms aggregation with `min_doc_count: 0` and any sub-aggregation, where the query ensures that buckets with a doc count of 0 will exist, returns a `search_phase_execution_exception` with a root cause of `array_index_out_of_bounds_exception`.

This behaviour was not present in 7.8.1, and is still present in 7.9.1. The previous (and expected) behaviour was for the sub-aggregations to proceed as if on an empty context.

**Steps to reproduce**:
These steps reproduce the problem on a fresh cluster. So far as I can tell, _any_ aggregation under `subagg` will return the same error - not just the filter/match_all in this example.

```
PUT /bug-mre

PUT /bug-mre/_mapping
{
  "properties": {
    "letter": {
      "type": "keyword"
    }
  }
}

POST /bug-mre/_bulk
{"index":{}}
{"letter":"a"}
{"index":{}}
{"letter":"b"}

GET /bug-mre/_search
{
  "query": {
    "term": {
      "letter": "a"
    }
  },
  "aggs": {
    "letters": {
      "terms": {
        "field": "letter",
        "min_doc_count": 0
      },
      "aggs": {
        "subagg": {
          "filter": {
            "match_all": {}
          }
        }
      }
    }
  }
}
```

This returns:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "Index -1 out of bounds for length 1"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "bug-mre",
        "node" : "vuf3AdPqQV--8ZHh5QiYrA",
        "reason" : {
          "type" : "array_index_out_of_bounds_exception",
          "reason" : "Index -1 out of bounds for length 1"
        }
      }
    ],
    "caused_by" : {
      "type" : "array_index_out_of_bounds_exception",
      "reason" : "Index -1 out of bounds for length 1",
      "caused_by" : {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "Index -1 out of bounds for length 1"
      }
    }
  },
  "status" : 500
}

```

Please let me know if you'd like any more info!

**Comment by nik9000** [comment]
Sounds like something I would have done. I'll dig.

**Comment by nik9000** [comment]
I've tracked this down to the work that I did to cut down on memory usage in the aggregator and to merge the implementation of `significant_terms` and `terms`. Its twisted all together in the work to build the whole tree layer by layer that was required to save the memory. Anyway, I have a solution based on the example you sent. I should be able to open a PR this afternoon if everything lines up.

**Comment by nik9000** [comment]
In general I'd try and stay away from `min_doc_count: 0` because it forces a really inefficient execution mode. I do have a fix though.

**Comment by jamieparkinson** [comment]
That's great, thank you for the quick solution! `min_doc_count: 0` has been _very_ useful for building faceted search interfaces without the fuss of caching the filterable values (or similar) but will bear in mind that this is a good place to start when looking at perf...

**Comment by nik9000** [comment]
Would the `global` agg do the right thing for you?  I'm unsure which one
would perform better but if it works it is another option.

**Comment by jamieparkinson** [comment]
Ooh, interesting, I wasn't aware of the global agg. The answer is "maybe" as it's a long time since I've touched this but thank you for the suggestion regardless - I'll have a look.
