### ISSUE TITLE
Timeout for primary relocation handoff seems block all write operation

### ISSUE THREAD

**Issue by djjsindy** [elastic/elasticsearch#62102]
**Elasticsearch version** (`bin/elasticsearch --version`):
 6.2.3
**Plugins installed**: []
NONE
**JVM version** (`java -version`):
1.8.0_152
**OS version** (`uname -a` if on a Unix-like system):
3.10.0-327
**Description of the problem including expected versus actual behavior**:
I see some issues like [41307](https://github.com/elastic/elasticsearch/issues/41307) . My cluster does show some write hangs.  At the same time in the relocation process, i see all write operation hang. After 30 minutes of timeout, I see the following error “timed out waiting for relocation hand-off to complete” ,and then all write operations are normal.  
I would like to ask, within 30 minutes of this timeout, are all writes hanging normal? @DaveCTurner

**Comment by cjcenizal** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
