### ISSUE TITLE
[DOCS] An overview page for CCS like for ILM 

### ISSUE THREAD

**Issue by Alex3k** [elastic/elasticsearch#62106]
**Summary**
I find the CCS docs quite heavy on technical detail on [the root page](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html) whereas other pages like the ILM docs have a [great, very approachable brief summary ](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html)and then [solid overview section](https://www.elastic.co/guide/en/elasticsearch/reference/current/overview-index-lifecycle-management.html).

**Detail**
Within the ILM docs, you get a really brief introduction to ILM with a screenshot that gives a bit more detail and then various sections such as Overview and Concepts. This documentation in my mind if the gold standard when sharing with customers as I don't need to reinvent the wheel when trying to describe that it's useful.
![image](https://user-images.githubusercontent.com/5962803/90248944-81c29c00-de31-11ea-9db6-072b76cc9152.png)

However, I find when trying to encourage folks towards [CCS](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html) it gets a bit more complicated. The documentation dive straight into a lot of detail around APIs without giving any detail more than a few line of why it is useful and how it can be used for critical topics like disaster recovery. It would be great to see possible architectures of this in use and how folks can use it.

![image](https://user-images.githubusercontent.com/5962803/92491768-8426d480-f1ea-11ea-9923-cd06bf7caa46.png)

It would be really great and useful if we could structure the CCS documentation to be closer to the structure of ILM. For example, the root page could be titled "Cross Cluster Search" and then an overview of what it is, how it can be used, scenarios of use, common architectures and how to set it up and limitations would be awesome. 

cc: @zuketo

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
