### ISSUE TITLE
Completion suggester not giving matches when prefix query is a direction abbreviation.

### ISSUE THREAD

**Issue by srgupta99** [elastic/elasticsearch#62147]
We are using completion suggester in ElasticSearch 6.8
The completion field has a search time synonym filter having value **"se,s.e,se.,s.e.,southeast,south east"** for the directions.

Now, we are observing a very strange behaviour when we do a prefix based query:

1. Given the prefix input as **"s"**, we get suggestions like **"STE A...."**.

1. Given the prefix input as **"se"**, we don't get any suggestions.

1. Given the prefix input as **"sea"**, we get suggestions like **"SEAS GENERA...."**.

Why is that for the 2nd case there are no suggestions found?

This is happening only for the direction abbreviations, all the other abbreviations are working fine.

**Comment by javanna** [comment]
This is an old issue that we have not replied to. I am going to close it for now, as it does not have enough context for us to determine whether it is a bug or what needs fixing. Feel free to add more info or test this against a more recent version.
