### ISSUE TITLE
Format field for date histogram does not work with Transforms

### ISSUE THREAD

**Issue by djaswal** [elastic/elasticsearch#62174]
Elasticsearch version (bin/elasticsearch --version): 7.9.1

Plugins installed: []

JVM version (java -version): openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

OS Version: Ubuntu 18.04

Description of the problem including expected versus actual behavior:
Transforms that include date histogram with format value do not work with the following error:
`"error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:47] [data_frame_date_histogram_group] unknown field [format]"
            }
        ],`

Steps to reproduce:

1. Create Index 
```json
{
   "mappings":{
      "properties":{
         "date":{
            "type":"date",
            "format":"yyyy-MM-dd HH:mm:ss"
         },
         "voltage":{
            "type":"long"
         }
      }
   }
}
```

2. Add test items
```json
POST test_index/_doc/1
{
    "date": "2015-01-01 12:10:30",
    "voltage":1
}
```
```json
POST test_index/_doc/2
{
    "date": "2015-02-01 12:10:30",
    "voltage":1
}
```
```json
POST test_index/_doc/3
{
    "date": "2015-03-01 12:10:30",
    "voltage":5
}
```
```json
POST test_index/_doc/4
{
    "date": "2015-04-01 12:10:30",
    "voltage":10
}
```
3. Try transform preview

```json
POST _transform/_preview
{
   "dest":{
      "index":"hourly_data_aggregations"
   },
   "source":{
      "index":"test_index"
   },
   "pivot":{
      "group_by":{
         "dateTime":{
            "date_histogram":{
               "field":"date",
		"calendar_interval": "1M",
		"format": "yyyy-MM-dd HH:mm:ss"
            }
         }
      },
      "aggregations":{
         "avgVoltage":{
            "avg":{
               "field":"voltage"
            }
         }
      }
   }
}
```
ERROR:
```
"error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:47] [data_frame_date_histogram_group] unknown field [format]"
            }
        ],
```

**Comment by djaswal** [comment]
Upon further investigation, I see it was removed in support of https://github.com/elastic/kibana/issues/39250.

So there is no way to have custom date format for the destination index?

**Comment by hendrikmuhs** [comment]
@djaswal 

We removed custom data time support for the reasons explained in https://github.com/elastic/kibana/issues/39250, in short custom date time can interfere with transform logic and lead to wrong configurations. We decided that it is better to not allow this error-prone option. Note that kibana visualizations and further aggregations on the transform dest index use doc values.


Transform follows the logic and syntax of aggregations as much as possible, however this isn't always possible and in some cases it does not make sense, e.g. as transform indexes the data we have to think 1 step further than aggregations, which "only" respond to search requests.

Custom formatted date strings can be created using an ingest pipeline:

```
PUT _ingest/pipeline/custom_date
{
  "description" : "Set a custom date",
  "processors" : [
    {
      "date" : {
        "field" : "dateTime",
        "target_field" : "dateTime-custom",
        "formats" : ["UNIX_MS"],
        "output_format" : "yyyy-MM-dd HH:mm:ss"
      }
    }
  ]
}
```

You can specify this pipeline as part of `dest`:

```
"dest":{
  "index":"hourly_data_aggregations",
  "pipeline": "custom_date"
},
```

In my example I wrote a new field, of course you can overwrite the existing field, too.

I am closing this issue and hope the provided workaround works for you.
