### ISSUE TITLE
Need to add /usr/share/elasticsearch/bin when seraching for elasticsearch.bin.sh to  elaslticsearch script 

### ISSUE THREAD

**Issue by linearregression** [elastic/elasticsearch#6220]
After installation in unbuntu desktop 13.x, without ES_HOME set.
A bit of digging shows that elasticsearch shell script does not include bin.
Making a symbolic link with bin, solves the issue.

starting elasticserach complains about missing ES_CLASSPATH being absent.
Error message:
/usr/share/elasticsearch/bin/elasticsearch: 1: /usr/share/elasticsearch/bin/elasticsearch: dirname: not found
/usr/share/elasticsearch/bin/elasticsearch: 1: /usr/share/elasticsearch/bin/elasticsearch: dirname: not found
You must set the ES_CLASSPATH va

Looks like you need to include "bin" in some system:
Details:
In ElasticSearch.sh in /usr/share/elasticsearch/bin/elasticsearch, does not include "bin":
----
# If an include wasn't specified in the environment, then search for one...
if [ "x$ES_INCLUDE" = "x" ]; then
    # Locations (in order) to use when searching for an include file.
    for include in /usr/share/elasticsearch/elasticsearch.in.sh \
                   /usr/local/share/elasticsearch/elasticsearch.in.sh \
                   /opt/elasticsearch/elasticsearch.in.sh \
                   ~/.elasticsearch.in.sh \
                   "`dirname "$0"`"/elasticsearch.in.sh; do
        if [ -r "$include" ]; then
            . "$include"
            break
        fi
    done

**Comment by clintongormley** [comment]
Closing as won't fix
