### ISSUE TITLE
More general fix for dependencies of the composeUp task 

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#62203]
PR #58708 had an issue with the `:x-pack:test:idp-fixture:composeU` task, for which @breskeby came up with a [fix](https://github.com/breskeby/elasticsearch/commit/de079d6dde022c5122a0c7b41ae9248abed4ad58).  It's temporary solution, but considered good enough for #58708 and hence is [adopted](https://github.com/elastic/elasticsearch/pull/58708/files/52a4c80eb89f14ec2cdebd776e95236e259f2f53..1dcd6f31090b51a94f0c0947ff402afdbdd8408e).

This issue is created to track possible formal/general fix to replace the above mentioned temporary fix for the test fixture.

**Comment by BigPandaToo** [comment]
More composeUp failures:
https://gradle-enterprise.elastic.co/s/mzy6ysoxndkl2

**Comment by mark-vieira** [comment]
We are removing usages of the compose task altogether so we don't plan to improve the tooling here.
