### ISSUE TITLE
Introduce FetchContext

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#62228]
We currently pass a SearchContext around to share configuration among FetchSubPhases.  With the introduction of runtime fields, it would be useful to start storing some state on this context to be shared between different subphases (for example, stored fields or search lookups can be loaded lazily but referred to by many different subphases).  However, SearchContext is a very large and unwieldy class, and adding more methods or state here feels like a bridge too far.

We should investigate extracting a FetchContext that contains only those methods necessary for the FetchPhase.  This can also be an opportunity to rationalise some of the methods (there seem to be about seven different ways to indicate that the source should be loaded, for a start).

**Comment by jtibshirani** [comment]
> With the introduction of runtime fields, it would be useful to start storing some state on this context to be shared between different subphases (for example, stored fields or search lookups can be loaded lazily but referred to by many different subphases).

I filed #62511 to expand on this idea -- comments are very welcome!

**Comment by romseygeek** [comment]
Fixed by #62357
