### ISSUE TITLE
Should we continue to account 5kb per bucket in the request circuit breaker

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#62240]
Today aggregations that run on shards adds 5kb to the circuit breaker every time they create a new bucket. This estimation was added because most of the memory consumed in aggregations were not accounted properly. 

However, the situations has changed, we are now properly accounting almost every allocation in aggregations and [the missing ones are tracked](https://github.com/elastic/elasticsearch/issues/59892). The extra memory that was used to create doc values iterator is also gone with [a large refactoring that allows to create a single instance](https://github.com/elastic/elasticsearch/pull/55873) no matter how many buckets the parent creates. Finally the coordinating node should be able to track the memory used to perform reduction of aggregations so we need to make sure that the accounting we have in the request circuit breaker is not too far from the truth.

Adding an arbitrary 5kb for each bucket means that a node running an aggregation that creates 1M buckets will occupy 5GB in the request circuit breaker even though we return only the top N. The reality for a term aggregation is closer than a few bytes than 5kb so I hope we can revive some tests to check the validity of this estimation again.

**Comment by jimczi** [comment]
Right, I was not sure if all type of `terms` aggregation have migrated yet. That's another argument in favor of the removal, this accounting becomes insignificant with the refactor and could be confusing since it doesn't protect against anything.

**Comment by nik9000** [comment]
Yeah, the refactor is all done, 100%. That 5k is per aggregation now. That feels *ok* to me, as, sort of, a catch all to account for TermsEnum and just general objects we don't account.

**Comment by polyfractal** [comment]
I'm ambivalent tbh.  The 5kb has never been terribly effective (in 6.x there were instances of accumulated TermsEnum OOMing a node while the request breaker reported <100kb), but otoh it does provide a bit of buffer for strings on heap, misc variables we don't track, etc.  :shrug:

**Comment by jimczi** [comment]
> That feels ok to me, as, sort of, a catch all to account for TermsEnum and just general objects we don't account.

Ok then I can close this issue. The refactor reduced the number of aggregator that we create drastically so it shouldn't be a problem.
