### ISSUE TITLE
disabling allow_leading_wildcard not working in 7.9.1 like it is in 7.9.0

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#62267]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.1 (from official docker image)
**Description of the problem including expected versus actual behavior**:
allow_leading_wildcard false prevent a search in 7.9.0 which runs in 7.9.1
**Steps to reproduce**:
Run this in Kibana Dev tool:
```
PUT testwildcard/_doc/1
{
  "foo": "bar"
}

POST testwildcard/_search
{
  "query": {
    "query_string": {
      "query": "*ar",
      "fields": [
        "foo"
      ],
      "allow_leading_wildcard": false
    }
  }
}
```

In 7.9.1, the document is returned, the output in 7.9.0 (and lower versions) does block the search from running as expected: 
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "Failed to parse query [*ar]",
        "index_uuid" : "UmDK7qc_Sqef6uhk-f0fWA",
        "index" : "testwildcard"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "testwildcard",
        "node" : "zyyjFmpWQnK4NE9VXPn_ng",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "Failed to parse query [*ar]",
          "index_uuid" : "UmDK7qc_Sqef6uhk-f0fWA",
          "index" : "testwildcard",
          "caused_by" : {
            "type" : "parse_exception",
            "reason" : "Cannot parse '*ar': '*' or '?' not allowed as first character in WildcardQuery",
            "caused_by" : {
              "type" : "parse_exception",
              "reason" : "'*' or '?' not allowed as first character in WildcardQuery"
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
```

For ref : 
- [7.9.1 release notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/release-notes-7.9.1.html)
- [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) : `analyze_wildcard (Optional, boolean) If true, the query attempts to analyze wildcard terms in the query string. Defaults to false.`

**Comment by jimczi** [comment]
@cbuescher can you take a look?

**Comment by cbuescher** [comment]
I can reproduce 7.9 (error) and 7.9.1 behaviour. After some digging I think the evaluation of `allow_leading_wildcard` that is happening in QueryParserBase#getWildcardQuery isn't called under the same circumstances anymore after some internal refactoring. Will work on tests and a fix.
