### ISSUE TITLE
Cannot execute shell command in custom modules

### ISSUE THREAD

**Issue by tanghengliang** [elastic/elasticsearch#62265]
I want to use the SED command to modify a specific file content, but I throw an IOException error, such as: sed... Operation, return Cannot run program “sed ....” :error = 13, permission denied

**Comment by costin** [comment]
The issue doesn't offer a lot of details and it's unclear how this is related to Elasticsearch itself.
Please ask user questions on the [forums](https://discuss.elastic.co/), or consult the [documentation](https://www.elastic.co/guide/index.html).
We reserve GitHub issues for bug reports and feature requests only. The forums are the appropriate place to handle these questions.
