### ISSUE TITLE
NPE when deleting multiple backing indices on a data stream

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#62272]
As reported by @Snp3r here: https://github.com/elastic/elasticsearch/pull/55690#issuecomment-691087407:

I've got 500 error, nullpointer exception when I trying to delete multiple backing indices:

`curl -X DELETE "localhost:9200/.ds-my-data-stream-000001,.ds-my-data-stream-000002?pretty"`
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}`

Deleting one by one is ok:

`curl -X DELETE "localhost:9200/.ds-my-data-stream-000001?pretty"`
`{
  "acknowledged" : true
}
`
`curl -X DELETE "localhost:9200/.ds-my-data-stream-000002?pretty"`
`{
  "acknowledged" : true
}
`

**Comment by immanuelfodor** [comment]
When can one expect the next release with this fix? In a month's time or maybe sooner?

**Comment by danhermann** [comment]
> When can one expect the next release with this fix? In a month's time or maybe sooner?

We hope to release in ~3 weeks though we cannot commit to any specific timeframe for future releases.
