### ISSUE TITLE
Detect noop doesn't work with Script and Upsert

### ISSUE THREAD

**Issue by rishinaveen** [elastic/elasticsearch#62277]
Hi, does detect noop work with an update that's done with a script and upsert value? 

Here's what i am trying to do. I want to do an upsert. Insert the document if doesn't exist or update the document using a script if a document exists. 

Existing document may or may not have all the hobbies. In which case, I want to check and add the new hobby if it didn't already exist or if it did, update the existing hobby with new values.

Run 1: Successful. It did an insert (no updated_at field)
Run 2: Successful. It did an update (with updated_at field)
Run 3: Successful. Nothing changed but result says **updated** instead of noop

Ex:
#### POST /users/_update/abcd1234
```
{
  "detect_noop": true, // don't need to specify it as it default to true, but I did anyway for the sake of testing.
  "script": {
    "source": 
       """
       // get source
       // get hobbies
       // get newHobby from params

      for (Map hobby : hobbies) {
        if (hobby.get("name").equalsIgnoreCase(newHobby.get("name"))) {
           matchedHobby = hobby;
           break;
    	}
      }

      if (matchedHobby != null) {
        matchedHobby.putAll(newHobby);
      } else {
        hobbies.add(newHobby);
      }
       """,
    "params": {
      "name": "Naveen",
      "id": "abcd1234",
      "updated_at": "2020-09-11 00:00:00.000",
      "hobbies": [
         {
           "name": "coding",
           "since": 2010
         }
      ]
    }
  }
  "upsert": {
    "name": "Naveen",
    "id": "abcd1234",
    "hobbies": [
         {
           "name": "coding",
           "since": 2010
         }
    ]
  }
}
```

#### **I am using ES 7.7 and running this script from a ElasticSearch Java Rest Highlevel Client.

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. You should also try searching there, which can likely [answer your question](https://discuss.elastic.co/t/script-update-noop-when-script-does-not-modify-document/222724). As such, I hope you don't mind that I close this.
