### ISSUE TITLE
The `clear_caches` setting for the Benchmark API doesn't accept `true`

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#6228]
The `clear_caches` setting for the [benchmark API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-benchmark.html#search-benchmark) does not accept a `true` value.

Since it can accept a `false` value, accepting `true` as well is expected -- more so, when the documentation uses the language usually used for boolean values, “Whether caches should be cleared on each iteration (...)”.

```bash
curl -X PUT 'http://localhost:9200/_bench?pretty' -d '{
  "name":"my_benchmark",
  "clear_caches":true,
  "competitors":[
    {
      "name":"query_1",
      "requests":[
        {
          "query":{
            "match":{
              "_all":"a*"
            }
          }
        }
      ]
    }
  ]
}'

# [400] (0.004s)

{"error":"Failed parsing field [clear_caches] must specify which caches to clear"}
```

**Comment by jpountz** [comment]
The benchmark API efforts have been discontinued.
