### ISSUE TITLE
DiskThresholdDeciderIT.testHighWatermarkNotExceeded failure

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#62326]
**Build scan**:
https://gradle-enterprise.elastic.co/s/okz2lziucuxkq/tests/:server:internalClusterTest/org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT/testHighWatermarkNotExceeded

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=60A6AF6A936EF834 -Dtests.security.manager=true -Dtests.locale=ro-RO -Dtests.timezone=America/Pangnirtung -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT&tests.sortField=FAILED&tests.test=testHighWatermarkNotExceeded&tests.unstableOnly=true

**Failure excerpt**:
```
java.lang.AssertionError: |  
  | Expected: a collection with size <1> |  
  | but: collection size was <0>

at __randomizedtesting.SeedInfo.seed([60A6AF6A936EF834:89874ED813A831DA]:0) |  
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:160) |  
  |  

```

**Comment by original-brownbear** [comment]
This reproduces pretty easily for me locally over a few tens of runs. I'll look into a fix tomorrow

**Comment by droberts195** [comment]
The test failed in the same way in 7.x in https://gradle-enterprise.elastic.co/s/x4m3oyeudq7ck in a commit that is more recent than the fix.

```
   java.lang.AssertionError:
   Expected: a collection with size <1>
   but: collection size was <0>
```

**Comment by danielmitterdorfer** [comment]
Muted via

* https://github.com/elastic/elasticsearch/pull/62858 in `master`
* https://github.com/elastic/elasticsearch/pull/62859 in `7.x`

**Comment by cbuescher** [comment]
Reopening since we face similar issues again on master and 7.x:
https://gradle-enterprise.elastic.co/s/dvlwxfzwu4yzc
https://gradle-enterprise.elastic.co/s/hcrfpa4y2h2io

Will mute on master, 7.x and 7.10

**Comment by cbuescher** [comment]
Muted with a615845fea1156d2ecb29631f67b095370e61b9c, 0db9dd10f631669ea706fc373d1b6566eb3c481c and 517d3e4336fe44c713aed4ee9168cb66c2df5f52
