### ISSUE TITLE
index.blocks.read_only_allow_delete setting documented twice

### ISSUE THREAD

**Issue by kdrvn** [elastic/elasticsearch#62369]
In the [index blocks settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-blocks.html#index-block-settings) documentation, the `index.blocks.read_only_allow_delete` setting is documented twice with slightly different descriptions.

Based on the commit history, the first instance seems to have been initially removed (https://github.com/elastic/elasticsearch/commit/822b7421ce2cbbeb0cf64c0e15f7e0b9b5963b69) and then re-introduced in a later commit (https://github.com/elastic/elasticsearch/commit/20d04081ec79450261d84df11c961fcc2d2d3034).

Additionally, the indentation for the second instance/description seems inconsistent with the rest of the documentation: it is aligned with top level documentation rather than setting specific description.

**Comment by hashmeet-singh** [comment]
@kdrvn I can rectify it. Which one do we plan on removing?
