### ISSUE TITLE
Script runtime field should allow an empty script definition

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#62407]
To reproduce this scenario, try to create an index template like this:

```
PUT _index_template/test
{
  "template": {
    "mappings": {
      "properties": {
        "day_of_week": {
          "type": "runtime",
          "runtime_type": "keyword",
          "script": {
            "source": ""
          }
        }
      }
    }
  },
  "index_patterns": [
    "test"
  ],
  "composed_of": []
}
```

You'll get back this error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "composable template [test] template after composition is invalid"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "composable template [test] template after composition is invalid",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "invalid composite mappings for [test]",
      "caused_by" : {
        "type" : "mapper_parsing_exception",
        "reason" : "Failed to parse mapping: compile error",
        "caused_by" : {
          "type" : "script_exception",
          "reason" : "compile error",
          "script_stack" : [
            "",
            "^---- HERE"
          ],
          "script" : "",
          "lang" : "painless",
          "position" : {
            "offset" : 0,
            "start" : 0,
            "end" : 0
          },
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "invalid function definition: found no statements for function [execute] with [0] parameters"
          }
        }
      }
    }
  },
  "status" : 400
}
```

It seems reasonable to want to define a runtime field without knowing what exactly it should emit yet, for example as a placeholder. Can we update the API to allow this?

**Comment by javanna** [comment]
@cjcenizal could you clarify what the usecase is for a placeholder? Why would you define a runtime field without knowing what it should emit? The put mappings API would need to be used to update the script anyways later, and with the same API you can define the same field once you know what values it needs to emit?

**Comment by cjcenizal** [comment]
@javanna You're right, I was mostly thinking that you'd want to be able to create a placeholder when defining a runtime field on a query, and that allowing it there would be inconsistent with disallowed it when defining it on the index. But that inconsistency is overshadowed by designing the API for the specific use-case at hand, and I can't think of a situation where you'd deliberately want to specify a placeholder runtime field on an index template or index.
