### ISSUE TITLE
Wrong information about cluster.routing.allocation.disk.watermark.flood_stage in official reference.

### ISSUE THREAD

**Issue by jemini12** [elastic/elasticsearch#62426]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.x-7.3.x

**Plugins installed**: []

**JVM version** (`java -version`): openjdk java 11

**OS version** (`uname -a` if on a Unix-like system): CentOS 7.7

**Description of the problem including expected versus actual behavior**:
  [Official document](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/disk-allocator.html) tells us that `index.blocks.read_only_allow_delete` is automatically released when the disk utilization falls below the high watermark. 

  But we found that this automatic release function does not work on version 6.8 to 7.3. And I found that in github issue [#39334](https://github.com/elastic/elasticsearch/issues/39334) and following pull request [#42559](https://github.com/elastic/elasticsearch/pull/42559) there is a comment about release version of the patch which is 7.4.0.

  Please fix the official document as automatic releasement of read-only block setting is not supported on 6.8 to 7.3.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Index document or use disk space until disk usage exceeds flood stage. 
 2. Check whether `index.blocks.read_only_allow_delete` is set or not on index.
 3. Delete document or remove some files in the system to below the flood stage. 
 4. Check whether `index.blocks.read_only_allow_delete` is released or not on index.

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
@lockewritesdocs this error was introduced into the 6.8 docs in #57322, would you take a look?

**Comment by lockewritesdocs** [comment]
Thanks for bringing this issue to my attention @DaveCTurner! I opened #62627 with a fix.

**Comment by jrodewig** [comment]
#62627 merged a fix for this. Closing this one out.
