### ISSUE TITLE
Remove uncommon search URL parameters?

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#62423]
In the search API, several parameters can be specified both in the URL and the request body. For common options like `from` and `size`, this can provide some helpful flexibility.

But for other less common parameters like `_source_excludes` and `suggest_field`, it's unclear why they can be specified in the URL. It could be nice to simplify and remove the ability to pass these in the URL. That way there would be a single clear way to pass most search parameters.

**Comment by javanna** [comment]
While this would be a good simplification, it would also be a breaking change for users that rely on the parameter variant that we'd decide to remove. We have no concrete plans to work on this, hence I am closing this issue.
