### ISSUE TITLE
what can i do？when i change 2.x to 6.x

### ISSUE THREAD

**Issue by CSuperC** [elastic/elasticsearch#62429]
**Elasticsearch version** (`bin/elasticsearch --version`):
 2.x 6.x agg 

myquestion ：
our 2.x agg very good，bug agg 6.x is worst
one day 3kw logs，then agg logs by a,b,c,d, very well in 2.x，when use in 6.x ，server is bad ，out of memery
2.x and 6.x java heap is almost the same ，6.x is more heap
one day in 2.x index size is 50GB，but 100GB in 6.x，is it the reason，when 6.x go down？，if this is the question ，what can i do to decrease the index in 6.x  version 6.7.1  version 2.4.5

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Hi @CSuperC! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by CSuperC** [comment]
@cbuescher ok，i will go there ，thank you~
