### ISSUE TITLE
[CI] release-tests failing for :test:external-modules:test-delayed-aggs:yamlRestTest

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62435]
Seems to have started yesterday (Sep 15th), probably only this build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/

**Build scan**:

https://gradle-enterprise.elastic.co/s/izocqozwwpvaw

**Repro line**:

---

**Reproduces locally?**:

no

**Applicable branches**:

master, 7.x

**Failure history**:

Earliest failure I can find atm: https://gradle-enterprise.elastic.co/s/nzhaic5f5yd4g, (2020-09-15T16:51:05.730Z) on 9a9cb06916b86a6d24e438ffca5c51f1eacf35a4

**Comment by cbuescher** [comment]
Maybe related to https://github.com/elastic/elasticsearch/commit/de169c5daf1a97ebc3a73a981d9a53950c91740c

**Comment by jimczi** [comment]
Looks like the release tests are running with the test-modules:
````
