### ISSUE TITLE
Elastic search results are not as expected

### ISSUE THREAD

**Issue by Alishma** [elastic/elasticsearch#62440]
I've a field indexed with custom analyzer with the below configuration 

```
 "HANDELSNM" : {
          "type" : "text",
          "analyzer" : "textAnalyzer"
        }

 "textAnalyzer" : {
              "filter" : [
                "lowercase"
              ],
              "char_filter" : [ ],
              "type" : "custom",
              "tokenizer" : "ngram_tokenizer"
            }

 "tokenizer" : {
            "ngram_tokenizer" : {
              "type" : "ngram",
              "min_gram" : "2",
              "max_gram" : "3"
            }
          }
```

While I'm searching for a text "ikea" I'm getting the below results 

Query :

```
GET company_info_test_1/_search
{
  "query": {
    "match": {
      "HANDELSNM": {"query": "ikea"}
    }
  }
}
```
Results are as below,

> 1.mikea
> 2.likeable
> 3.maaikeart
> 4.likeables
> 5.**ikea b.v.**  
> 6.likeachef
> 7.**ikea breda** 
> 8.bernikeart
> 9.ikea duiven
> 10.mikea media

I'm expecting the exact match result should be boosted more than the rest of the results.
Could you please help me what is the best way to index if I have to search with exact match as well as with fuzziness.

Thanks in advance.

**Comment by cbuescher** [comment]
Hi @Alishma! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

In your particular case I notice you are only using the ngram tokenizer for that field, which basically means after analysis you have 2- and 3-grams but the original token is lost. 
One possible solution is to index into two fields (one e.g. using the standard analyzer or a language analyzer and one using the ngrams for fuzzy matching). Then query over both of them and adjust the boosts as needed. If you have further questions on this someone in the forums is sure able to help.
