### ISSUE TITLE
[CI] AsyncSearchActionIT.testRestartAfterCompletion failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62451]
**Build scan**:

https://gradle-enterprise.elastic.co/s/tds3nk2ykh2yc

**Repro line**:

./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion" \
  -Dtests.seed=1AE8DAD4C04E8D0D \
  -Dtests.security.manager=true \
  -Dtests.locale=nb \
  -Dtests.timezone=America/Jujuy \
  -Druntime.java=11

**Reproduces locally?**:

No

**Applicable branches**:

7.x

**Failure history**:

Then failures start again around Sep 11th, all on 7.x, e.g
https://gradle-enterprise.elastic.co/s/qgznb7twjitsc

**Failure excerpt**:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([9D9231A4428E0BCA:CB0FFCAEB428886B]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion(AsyncSearchActionIT.java:192)
```

That assertion checks that the AsyncSearchResponse has the `isRunning` flag set to false.

**Comment by andreidan** [comment]
Another occurrence of this on `7.x` https://gradle-enterprise.elastic.co/s/dbecvbj75iko2

**Comment by benwtrent** [comment]
Seems like the same failure: https://gradle-enterprise.elastic.co/s/sk4qya62oqb7k

```

org.elasticsearch.xpack.search.AsyncSearchActionIT > testRestartAfterCompletion FAILED |  
-- | --
  | java.lang.AssertionError |  
  | at __randomizedtesting.SeedInfo.seed([965F106985D6DC53:C0C2DD6373705FF2]:0) |  
  | at org.junit.Assert.fail(Assert.java:86) |  
  | at org.junit.Assert.assertTrue(Assert.java:41) |  
  | at org.junit.Assert.assertFalse(Assert.java:64) |  
  | at org.junit.Assert.assertFalse(Assert.java:74) |  
  | at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion(AsyncSearchActionIT.java:188)


```

```



./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion" -Dtests.seed=965F106985D6DC53 -Dtests.security.manager=true -Dtests.locale=de-DE -Dtests.timezone=Europe/Samara -Druntime.java=8 |  
 


```
