### ISSUE TITLE
Load version field even if fetching source is disabled

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#62456]
Currently we avoid adding the version field to search hits if fetching source is disabled for the request.  However, the version is loaded from docvalues, not from source, so this doesn't really make much sense.  It also is not applied to loading sequence numbers and primary terms.  I think we should just remove this check entirely.

**Comment by romseygeek** [comment]
cc @jimczi seeing as you added this functionality originally

**Comment by jimczi** [comment]
+1, that makes sense to me.
