### ISSUE TITLE
Translog plugin

### ISSUE THREAD

**Issue by jcchen2** [elastic/elasticsearch#62508]
We host multi-tenanted data by storing data for each tenant in a separate index.  We would like to encrypt each index with tenant-specific key at rest to prevent data compromise for other indices in the unlikely event that one tenanted key and index is compromised.

Elasticsearch currently relies on filesystem encryption for at-rest encryption.  Index-level encryption via filesystem-based encryption tools such as LUKS, ecryptfs, or fscrypt requires a lot of directory and encryption setup and management overhead outside of elasticsearch.  These tools lack full control over encryption algorithm and encryption keys and they do not protect against attacks while the file system is mounted.

There is existing ability to customize index persistence via IndexStorePlugin.  We can use it to encrypt index with tenant-specific keys.  But we have no ability to customize translog persistence.  The enhancement request is to support translog persistence customization so that we can encrypt translog with tenanted keys.

**Comment by albertzaharovits** [comment]
@elastic/es-distributed can someone please comment on the feasibility of making the translog store pluggable?

Multi-tenant encryption at rest is something we don't currently support, but there's on-going discussion about it.
CC @bytebilly

**Comment by bytebilly** [comment]
Thanks Albert.

Last time we discussed a similar proposal we decided to not proceed because of the critical role of the translog and its reliability.
Looping @jasontedor since he was involved on the technical side and may have more context or updates.

**Comment by albertzaharovits** [comment]
I appreciate the rigorous explanation Jason, thank you!
I'm going to close this issue.
