### ISSUE TITLE
Benchmark API might miss not yet starting benchmark in unabortable state

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#6252]
Today there is a race condition in how we handle the benchmark state that allows for benchmarks to be kicked off without the ability to abort them again. The main reason for this is that the state handling is flawed since applying the state is not serializable in a way that the executing nodes knows if a benchmark that is marked as `running` has been aborted. The abort call simply tires to stop the benchmark and if it's not in the executing nodes datastructure due to some sort of a delay or an exhausted threadpool it just ignores it. At that point the benchmark state is already updated in the cluster state and can not be aborted again.  

The solution to this is a bigger change though. We should move to cluster state listeners instead of per node RPC calls just like Snapshot & Restore works

**Comment by jpountz** [comment]
The benchmark API efforts have been discontinued.
