### ISSUE TITLE
[CI] EqlCancellationIT#testCancellation failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#62530]
**Build scan**: https://gradle-enterprise.elastic.co/s/gehzubbmkv22c/tests/:x-pack:plugin:eql:internalClusterTest/org.elasticsearch.xpack.eql.action.EqlCancellationIT/testCancellation#1

**Repro line**:

`./gradlew ':x-pack:plugin:eql:internalClusterTest' --tests "org.elasticsearch.xpack.eql.action.EqlCancellationIT.testCancellation" -Dtests.seed=CED58D289E2F2711 -Dtests.security.manager=true -Dtests.locale=it-IT -Dtests.timezone=GB -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure history**: 

Failed twice in the last 7 days, in 7.x and a pr build for master.

https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.xpack.eql.action.EqlCancellationIT&tests.sortField=FAILED&tests.test=testCancellation&tests.unstableOnly=true

**Failure excerpt**:

```
junit.framework.AssertionFailedError: Expected exception Exception but no exception was thrown	
at __randomizedtesting.SeedInfo.seed([CED58D289E2F2711:18E2D25E00901097]:0)	
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2744)	
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2734)	
at org.elasticsearch.xpack.eql.action.EqlCancellationIT.testCancellation(EqlCancellationIT.java:78)
```

**Comment by costin** [comment]
Igor can you please take a look?

**Comment by andreidan** [comment]
Another occurrence https://gradle-enterprise.elastic.co/s/fhwzd3ekix2wo

**Comment by imotov** [comment]
This is triggered by the change in https://github.com/elastic/elasticsearch/commit/63afc61b084e78d0f0005f666f0e6b766ecb345d#diff-9c70930068120c515204efa560512fd9R96 

Basically, in this test the shortcut is triggered by before we ever check if task is cancelled causing the task to proceed. I am working on a fix.
