### ISSUE TITLE
SourceLookup should leverage sequential stored fields reader

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#62621]
In #62509 we've added a way to leverage sequential stored fields reader from any leaf readers used during a search.
This optimization has been plugged only for the fetch phase, when all documents to retrieve are contiguous, and proved very successful on scrolls that paginate every documents in an index.
With the addition of runtime fields, this optimization could also be helpful to speed up the retrieval of source fields in queries and aggregations since they visit documents in the natural order of the index (sequential reads).
This issue is a placeholder to implement this optimization to speed up runtime fields that work on the raw source.

**Comment by cbuescher** [comment]
I have a draft open at https://github.com/elastic/elasticsearch/pull/63035 that shows speed-ups when accessing runtime-fields in "docvalue_fields".
A draft for the rally track used can be found here: https://github.com/elastic/rally-tracks/pull/133
