### ISSUE TITLE
[DOCS] Refactor index name to make JSON bodies readable.

### ISSUE THREAD

**Issue by subhendusethi** [elastic/elasticsearch#62679]
Index name in the [Index APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_index_apis) section, shows the example of an index with the name as ``index``. 
This is confusing/less readable when reading the JSON request/reponse bodies.  e.g. ``"_index": "index"`` in the section.

Proposing changes to refactor the ``index`` name to ``your_index`` :  #62678

**Comment by mayya-sharipova** [comment]
@subhendusethi  Seems that PR #62678 has already addressed this change renaming the index name from `index` to `my-index-000001`.  Because of this I am closing this issue.  
Please let us know if there is still something else to be done for it.
