### ISSUE TITLE
[DOCS] Add settings description for nodes info API

### ISSUE THREAD

**Issue by lockewritesdocs** [elastic/elasticsearch#62725]
The description for the `settings` parameter of the [nodes info API](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/cluster-nodes-info.html) is missing.
![image](https://user-images.githubusercontent.com/25848033/93806778-af141e00-fc17-11ea-8e6f-3bf8ab5da10d.png)

**Comment by jaymode** [comment]
@lockewritesdocs as I am going through triaging issues I came up with the following blurb:

> Settings in use by the node as defined within the `elasticsearch.yml`
        file.

Your call on whether to use it or not :)

**Comment by lockewritesdocs** [comment]
Thanks for the suggestion @jaymode! How about something like this:
> Lists all node settings in use as defined in the `elasticsearch.yml` file.

**Comment by jaymode** [comment]
Sounds great to me
