### ISSUE TITLE
null buckets missing from terms aggregation

### ISSUE THREAD

**Issue by j0hnsmith** [elastic/elasticsearch#6273]
The terms aggregation creates a bucket for each value but doesn't include a `null` bucket. When there is a doc with a key set to `null` the cardinality is currently incorrect. 

Users may or may not want to include a `null` bucket so it should be configurable (default should be false in line with current behaviour), I propose

    {
        "aggs" : {
            "genders" : {
                "terms" : { 
                    "field" : "gender",
                    "null": true
                }
            }
        }
    }

And the response

    {
        ...

        "aggregations" : {
            "genders" : {
                "buckets" : [
                    {
                        "key" : "male",
                        "doc_count" : 10
                    },
                    {
                        "key" : "female",
                        "doc_count" : 10
                    },
                    {
                        "key" : null,
                        "doc_count" : 1  // indicates doc without gender field or field set to null
                    },
                ]
            }
        }
    }

**Comment by jpountz** [comment]
Closing: with https://github.com/elastic/elasticsearch/pull/11042 you can now configure arbitrary keys for documents that are missing a value.
