### ISSUE TITLE
snapshot retention with `max_size`

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#62752]
As of writing, snapshot retention can be set with `max_count` or `expire_after`. Typical backup storage is limited by the available disk size, and would be easier to configure if one can also specify `max_size` of all snapshots allowed to store without worrying about the number of snapshots or age of them.

**Comment by original-brownbear** [comment]
I think it's a very valid idea but I have a few comments on the practicality of this idea (at least in the short- to mid-term):

>  without worrying about the number of snapshots or age of them.

With the way the repositories currently work, there is some danger in not specifying a `max_count` for snapshots. The repositories do not scale endlessly in the number of snapshots they can hold (independently of the physical size of the snapshots they contain to some degree even). If we completely drop the requirement for setting a `max_count` then on a cluster that see little change in the data it contains the number of snapshots will only be increasing over time until it turns into a problem.

The other issue we have with implementing a size bound is that it's not a straight forward thing to do currently.
We only store the size of all files in the repository on a per-shard basis. If your repository contains snapshots of say `10k` shards, this means that computing the size of the repository will require reading `10k` blobs from the repository which is time consuming and incurs some API call cost for cloud provider backed repositories.
A possible fix for this might be incoming through caching repository metadata but as of right now computing the current size of the repository is not practical in my opinion.

I think if there's wide-spread interest in having this functionality it would serve as another motivation to improve the snapshot metadata format to scale better and have a more centralized view of the files in the repository though :)

**Comment by Leaf-Lin** [comment]
For cloud snapshot store, snapshot storage is less of a problem. For self-managed snapshot store usage estimation will be tracked under https://github.com/elastic/elasticsearch/issues/56660
