### ISSUE TITLE
Documents in a data stream can be deleted via the bulk API

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#62762]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.1

**Plugins installed**: none

**JVM version** (`java -version`): irrelevant

**OS version** (`uname -a` if on a Unix-like system): irrelevant

**Description of the problem including expected versus actual behavior**:

In the docs we state that [only `create` is allowed as action in bulk requests](https://www.elastic.co/guide/en/elasticsearch/reference/current/use-a-data-stream.html#data-streams-bulk-indexing-requests) for data streams. However, it is possible to use other actions as well with Elasticsearch 7.9.1.

* Expectation: Any bulk item with an operation type other than `create` fails with an `IllegalArgumentException` with a message "only write ops with an op_type of create are allowed in data streams".
* Actual behavior: The bulk request succeeds

**Steps to reproduce**:

In the following example we setup a data stream according to the docs:

```
curl -X PUT "localhost:9200/_ilm/policy/my-data-stream-policy?pretty" -H 'Content-Type: application/json' -d'
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_size": "25GB"
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
'

curl -X PUT "localhost:9200/_index_template/my-data-stream-template?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": [ "my-data-stream*" ],
  "data_stream": { },
  "priority": 200,
  "template": {
    "settings": {
      "index.lifecycle.name": "my-data-stream-policy"
    }
  }
}
'
```

Once it is setup, we will index a single document into it. This requires `jq` so we can extract the document id automatically.

```
DOC_ID=$(curl -s -X POST "localhost:9200/my-data-stream/_doc?pretty" -H 'Content-Type: application/json' -d'
{
  "@timestamp": "2020-12-06T11:04:05.000Z",
  "user": {
    "id": "vlb44hny"
  },
  "message": "Login attempt failed"
}
' | jq -r ._id)
```

Attempting to delete a single document via the data stream will fail (as expected):

```
curl -X DELETE "localhost:9200/my-data-stream/_doc/$DOC_ID?pretty"

# response:

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "only write ops with an op_type of create are allowed in data streams"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "only write ops with an op_type of create are allowed in data streams"
  },
  "status" : 400
}
```

However, if we attempt to do the same via the bulk API, the request succeeds:

```
curl -X PUT "localhost:9200/my-data-stream/_bulk?refresh&pretty" -H 'Content-Type: application/json' -d"
{\"create\":{ }}
{ \"@timestamp\": \"2020-12-08T11:06:07.000Z\", \"user\": { \"id\": \"8a4f500d\" }, \"message\": \"Login successful\" }
{ \"delete\" : { \"_id\" : \"$DOC_ID\" } }
"
```

This results in:

```
{
  "took" : 48,
  "errors" : false,
  "items" : [
    {
      "create" : {
        "_index" : ".ds-my-data-stream-000001",
        "_type" : "_doc",
        "_id" : "l6uxtXQBe4e9VJV_yQMw",
        "_version" : 1,
        "result" : "created",
        "forced_refresh" : true,
        "_shards" : {
          "total" : 2,
          "successful" : 1,
          "failed" : 0
        },
        "_seq_no" : 13,
        "_primary_term" : 1,
        "status" : 201
      }
    },
    {
      "delete" : {
        "_index" : ".ds-my-data-stream-000001",
        "_type" : "_doc",
        "_id" : "laustXQBe4e9VJV_xgOd",
        "_version" : 2,
        "result" : "deleted",
        "forced_refresh" : true,
        "_shards" : {
          "total" : 2,
          "successful" : 1,
          "failed" : 0
        },
        "_seq_no" : 14,
        "_primary_term" : 1,
        "status" : 200
      }
    }
  ]
}
```

Notes:

* The bulk API will behave identical to the document delete API if there is only one bulk item but behaves as described above if there are multiple actions.
* It is irrelevant whether the `_index` property is contained in the bulk request body. The behavior is identical.

**Comment by martijnvg** [comment]
Actually the bug is worse. The validation that checks that only create ops are allowed to go into a data stream is skipped for all bulk items after the first create operation in a data stream.
