### ISSUE TITLE
Bug in rest client caused by Future.get()

### ISSUE THREAD

**Issue by ssnijik** [elastic/elasticsearch#62798]
https://github.com/elastic/elasticsearch/blob/f120064734d5fa34b1020566793f51ac0e9b729e/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L271

It appears that when using rest client to synchronize write to es, timeout may not take affect. Timeout is a parameter called `master_timeout` in url for server. But when server is not responding, rest client will be blocked by Future.get() forever.

**Comment by javanna** [comment]
hi @ssnijik can you provide a snippet of your code that uses the `RestClient` please?

**Comment by ssnijik** [comment]
@javanna 
```
    IndexRequest indexRequest = new IndexRequest(indexName).opType(DocWriteRequest.OpType.INDEX).source(map);
    indexRequest.id(id);
    indexRequest.timeout(TimeValue.timeValueSeconds(timeout));
    IndexResponse indexResponse = client.index(indexRequest, RequestOptions.DEFAULT);
```
Stack trace and variables are also provided as follows, based on version 7.2.1. As you can see, timeout is a parameter on server side. Which means if server is not responding, client will not timeout.
![image](https://user-images.githubusercontent.com/3711535/94230053-b0a15700-ff33-11ea-83bb-6f29d8847f10.png)

![image](https://user-images.githubusercontent.com/3711535/94229922-5f916300-ff33-11ea-8421-eafff86de341.png)

**Comment by javanna** [comment]
To clarify, the index API supports two types of timeout parameteron the server side: `timeout` and `master_timeout`, which are described in the docs at https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html . The low-level client also supports setting connect and socket timeout.

From what you posted it seems like you are setting the `timeout` parameter to `45s`, but how are connect and socket timeout set on the client side? And what is the behaviour you are seeing? Does the index request take longer than 45 seconds yet it does not time out?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @ssnijik if you have the requested information please add it in a comment and we can look at re-opening this issue.

**Comment by woshibendanbuyaodawo** [comment]
遇到过好多次
