### ISSUE TITLE
QL: Improve disjunction translations on the same field

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#62804]
Queries with a lot of `OR` clauses on the same field, end up being translated to individual bool clauses for every single expression. While correct this can result in very large, non-optimal requests which in turn can lead to other problems (see #46477).
QL can optimize this scenario away so the multiple bool queries are translated into a terms one,

**Comment by astefan** [comment]
This is a task for the far future, considering https://github.com/elastic/elasticsearch/pull/61596#discussion_r490123586 right? Or limited to SQL for the moment.

**Comment by costin** [comment]
Correct, this works if/when dealing with exact equals. Case insensitive equals, the default currently in EQL, breaks this so at least for the moment, this would work only in SQL.
