### ISSUE TITLE
EQL: Unicode escape sequences

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#62832]
Related to #61659

This is a proposal to add two new escape sequences for unicode code points to EQL `"` strings. Occasionally, we need to inject non-printable unicode characters into an EQL string. The first case we realized this was for the MITRE 2019 eval. We managed to workaround this by carefully copying and pasting a character. It was a little tricky because the character happened to be the RTL encoding character. So as soon as it was pasted, all the subsequent text was flipped, since it was immediately interpreted in the browser.

I propose we add these new escape sequences, which are widely used, and how JSON typically escapes non-ascii characters.
* `\uXXXX`
* `\UXXXXXXXX`

I believe our current escape sequences are these:
* `\n` for newlines
* `\r` for carriage returns
* `\b` for backspace
* `\t` for a tab
* `\f` for form feed
* `\\` for backslash

Currently, if `\` is not followed by one of these characters, it is invalid syntax. So this change is purely additive and doesn't break. I'm indifferent if this targets 7.10 vs 7.11.

**Update:**
Use an alternative, less visually ambiguous form for the escape sequence: `\u{xxxxxxxx}` (2-8 hex characters)

**Comment by matriv** [comment]
`master` : https://github.com/elastic/elasticsearch/commit/cb6a6e084b9d5bcbb7ab62c6ba1e85ae026b6044
`7.x` : https://github.com/elastic/elasticsearch/commit/de237f0413a2cdcb552bc758c75096c55c46b4b8
