### ISSUE TITLE
occurred exception while doing reindex

### ISSUE THREAD

**Issue by vancefantasy** [elastic/elasticsearch#62844]
**Elasticsearch version** (`bin/elasticsearch --version`): 

    Version: 6.4.2, Build: default/tar/04711c2/2018-09-26T13:34:09.098244Z, JVM: 1.8.0_181

**Plugins installed**: []

    analysis-ik
    analysis-pinyin
    sql

**JVM version** (`java -version`):

    java version "1.8.0_181"
    Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

    Linux data1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

occurred exception while doing reindex

**mappings settings**:

         "quantity": { 
            "type": "double"
          },
          "quantityOfBaseUnit": { 
            "type": "double"
          },
**"dirty data" in source index**

     "quantity": 1e+46,
     "quantityOfBaseUnit": 1e+46,

**Provide logs (if relevant)**:

 ```
  % Total    % Received % Xferd  Average  Speed   Time   Time    Time    Current
                                                      Dload      Upload  Total   Spent   Left     Speed
100   720    0   285    0   435      0      0 --:--:--  5:06:34 --:--:--     0
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "cannot write xcontent for unknown value of type class java.math.BigInteger"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "cannot write xcontent for unknown value of type class java.math.BigInteger"
  },
  "status": 400
}

```

**Comment by matriv** [comment]
Seems that this issue has been fixed in the past, but you are using a very old version of ES.
Please refer to: #32395 and the relevant PR.

Therefore, I'm closing this issue.

**Comment by vancefantasy** [comment]
@matriv THX
