### ISSUE TITLE
IndexRecoveryIT.testPeerRecoveryTrimsLocalTranslog is stuck sporadically

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#62863]
**Build scan**: 

on 7.x:

* https://gradle-enterprise.elastic.co/s/n6g3wfnbhpsw2
* https://gradle-enterprise.elastic.co/s/ihnyeqjamqaem
* https://gradle-enterprise.elastic.co/s/d4kf4qkmcr2ds

on master:

* https://gradle-enterprise.elastic.co/s/phxortxfty7tc
* https://gradle-enterprise.elastic.co/s/fwmfuivftffwy
* https://gradle-enterprise.elastic.co/s/2m5vt6geehu4u

**Repro line**:

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT" -Dtests.seed=7C2C36E235B18ACB -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=8
```

**Reproduces locally?**: no

**Applicable branches**:

* master
* 7.x

**Failure history**:

According to [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-3M,mode:relative,to:now))&_a=(columns:!(class,test,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.indices.recovery.IndexRecoveryIT%22%20AND%20test:%22testPeerRecoveryTrimsLocalTranslog%22%20AND%20NOT%20branch:%22pull-request%22'),sort:!(time,desc))) this test has failed six times (excluding pull request builds); all of these errors have occured within the last two weeks.

**Failure excerpt**:

The failure manifests as suite timeout:

```
11:33:39   2> java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
11:33:39         at __randomizedtesting.SeedInfo.seed([7C2C36E235B18ACB]:0)
```

This might be a red herring but in the 7.x build failures we also see in the output of the active threads that the test is waiting for indexing to finish (this one is from the [most recent failure](https://gradle-enterprise.elastic.co/s/n6g3wfnbhpsw2)):

```
11:33:35   2>   23) Thread[id=3068, name=Thread-6, state=WAITING, group=TGRP-IndexRecoveryIT]
11:33:35   2>         at sun.misc.Unsafe.park(Native Method)
11:33:35   2>         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
11:33:35   2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
11:33:35   2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
11:33:35   2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
11:33:35   2>         at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:259)
11:33:35   2>         at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
11:33:35   2>         at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:56)
11:33:35   2>         at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:37)
11:33:35   2>         at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
11:33:35   2>         at org.elasticsearch.indices.recovery.IndexRecoveryIT.lambda$testPeerRecoveryTrimsLocalTranslog$42(IndexRecoveryIT.java:1802)
11:33:35   2>         at org.elasticsearch.indices.recovery.IndexRecoveryIT$$Lambda$4561/181390541.run(Unknown Source)
11:33:35   2>         at java.lang.Thread.run(Thread.java:748)
```

See also:

https://github.com/elastic/elasticsearch/blob/752590041e46fff97496b7487a1110581ac0593f/server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java#L1800-L1802

**Comment by danielmitterdorfer** [comment]
Muted in:

* https://github.com/elastic/elasticsearch/pull/62865 for master
* https://github.com/elastic/elasticsearch/pull/62868 for 7.x

**Comment by original-brownbear** [comment]
This reproduces fairly easily locally. The problem here is likely that we are restarting a node while using it's `client()` to run an index request. This isn't actually thread-safe to do in our test code and can run into a dead-lock like seen here.
I'll code up a fix shortly
