### ISSUE TITLE
Exception management for internal code contracts

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#6289]
Exception management for some of the internal code is repetitive across the entire codebase, requiring a lot of boilerplate code that is sensitive to copy/paste issues as well as a lot of unintended `NullPointerException`s in places that mean to check for `null` while checking other conditions. I propose creating a utility to handle this boilerplate for the most common cases.

In the forthcoming pull request, I have created an `Exceptions` utility that works like the `Preconditions` utility in Guava (and others that I have used/written), which just gives a very simple and readable mechanism for failing fast with expected exceptions (in this case, `ElasticsearchIllegalArgumentException`s). I have been using things like this for years on projects and I have found that they make code shorter, more readable and more predictable.

It turns code like:

    if (value1 == null) {
      throw new ElasticsearchIllegalArgumentException("value1 cannot be null");
    }
    if (Strings.isNullOrEmpty(value2)) {
      throw new ElasticsearchIllegalArgumentException("value2 cannot be empty");
    }
    if (value3 < 0) {
      throw new ElasticsearchIllegalArgumentException("value3 cannot be negative");
    }

    // required
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    // optional
    this.value4 = value4;

into:

    // required
    this.value1 = Exceptions.ifNull(value1, "value1 cannot be null");
    this.value2 = Exceptions.ifEmpty(value2, "value2 cannot be empty");
    this.value3 = Exceptions.ifNegative(value3, "value3 cannot be negative");
    // optional
    this.value4 = value4;

I also tend to use a few other functions not specified by `Preconditions`, such as inclusive and exclusive range checks and latitude/longitude checks, which I have implemented here. If they are actually embraced, it should make a simple way to provide predictable code contracts with minimal code.

**Comment by clintongormley** [comment]
Closing as nobody has shown the interest to pick this up
