### ISSUE TITLE
Kubernetes logs split in kibana

### ISSUE THREAD

**Issue by snirbenyosef** [elastic/elasticsearch#62923]
What happened:
I have Kubernetes system in Azure and used the following instrustions to install fluent, elasticsearch and kibana: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch I am able to see my pods logs in kibana but when i send logs more then 16k chars its just split.

if i send 35k chars . its split into 3 logs.

how can i increase the limit of 1 log? I want to able to see the 36k chars in one log.
[https://i.stack.imgur.com/ewocJ.png](https://i.stack.imgur.com/ewocJ.png
)

What you expected to happen:
to see the log as one. not spilt to 3.

How to reproduce it (as minimally and precisely as possible):
just send 36k chars.

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version): kuberenetes 1.17.11

**Comment by matriv** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

PS. Please provide version of the ES that you are using with your setup.
