### ISSUE TITLE
Cluster read only settings and archived settings conflict issue.

### ISSUE THREAD

**Issue by howardhuanghua** [elastic/elasticsearch#62920]
In our production environment, we hit a cluster settings update conflict issue. Here are the steps to reproduce:

1. One 5.6.4 cluster before upgrading to 6.8.2, set cluster level read-only block to lower down cluster's pressure temporarily.
2. Full cluster restart to upgrade from 5.6.4 to 6.8.2.
3. After restarting cluster, we found some unsupported settings in new version in archived settings:
```
  "persistent": {
    "archived": {
      "cluster": {
          "routing": {
            "allocation.disk.watermark.low": "85%"
          }
      },
      "pre-create_index": { // self-developed settings
          "reserved_hours": "6"
      }
    }
  }
```
4. After upgrading cluster successful, we are going to set cluster read only setting to false, however, it blocked by above `archived` settings:
```
PUT /_cluster/settings
{
  "persistent": {
    "cluster.blocks.read_only_allow_delete": null
  }
}

Response:
{
   "error":{
      "root_cause":[
         {
            "type":"remote_transport_exception",
            "reason":"[node-1][127.0.0.1:26364][cluster:admin/settings/update]"
         }
      ],
      "type":"illegal_argument_exception",
      "reason":"unknown setting [archived.cluster.routing.allocation.disk.watermark.low] did you mean any of [cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.disk.watermark.high]?",
      "suppressed":[
         {
            "type":"illegal_argument_exception",
            "reason":"unknown setting [archived.pre-create_index.reserved_hours] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
         }
      ]
   },
   "status":400
}
```
Then we also try to remove these archived settings but blocked by cluster read only settings:
```
PUT /_cluster/settings
{
  "persistent": {
    "archived.*": null
  }
}

Response:
{
   "error":{
      "root_cause":[
         {
            "type":"cluster_block_exception",
            "reason":"blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
         }
      ],
      "type":"cluster_block_exception",
      "reason":"blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
   },
   "status":403
}
```

Then whole cluster is read only forever, we can do nothing to fix it. Finally, we have updated related code to skip the `archived.` prefix settings validation:
https://github.com/elastic/elasticsearch/blob/ad69694863a23abe3070ec81662d9158001be497/server/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L486-L488
to get rid of `ignoreArchivedSettings` condition, as it only supports for index level settings update, we make it for all the `archived.` settings:
```
        if (key.startsWith(ARCHIVED_SETTINGS_PREFIX)) {
            logger.warn("skipped archived settings [{}] validation", key);
            continue;
        }
```

Please help to check the fix, if it's ok I will submit a PR to fix this issue, thanks.

**Comment by rjernst** [comment]
@howardhuanghua I'm not sure if it will work, but have you tried deleting the archived settings in the same request as clearing the cluster block?

**Comment by howardhuanghua** [comment]
Here is the current cluster settings:
```
curl localhost:5100/es/test_archived/_cluster/settings?pretty
Response:
{
  "persistent" : {
    "archived" : {
      "search" : {
        "check_buckets_step_size" : "10000"
      }
    },
    "cluster" : {
      "blocks" : {
        "read_only_allow_delete" : "true"
      }
    }
  },
  "transient" : { }
}
```
And I tried to set read only and archived setting together but also failed:
```
curl -XPUT "/_cluster/settings?pretty" -H 'Content-Type: application/json' -d' {
   "persistent" : {
     "cluster.blocks.read_only_allow_delete": false,
     "archived.search.check_buckets_step_size": null
   }
 }'

Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "cluster_block_exception",
        "reason" : "blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
      }
    ],
    "type" : "cluster_block_exception",
    "reason" : "blocked by: [FORBIDDEN/13/cluster read-only / allow delete (api)];"
  },
  "status" : 403
}

```

With our fix, we could set read only block to false and remove the archived setting:
```
curl -XPUT "/_cluster/settings?pretty" -H 'Content-Type: application/json' -d' {
  "persistent" : {
    "cluster.blocks.read_only_allow_delete": false
  }                                          
}'
{
  "acknowledged" : true,
  "persistent" : {
    "cluster" : {
      "blocks" : {
        "read_only_allow_delete" : "false"
      }
    }
  },
  "transient" : { }
}


curl -XPUT "/_cluster/settings" -H 'Content-Type: application/json' -d' {
  "persistent" : {
    "archived.*": null
  }
}'
{"acknowledged":true,"persistent":{},"transient":{}}
```

**Comment by howardhuanghua** [comment]
Hi @rjernst would you please help to review the issue again? Could I open a PR to fix the issue with my proposal?

**Comment by rjernst** [comment]
@howardhuanghua I don't think we would want such a flag. We always want validation. This is an edge case, but I'm hopeful we can find another solution. I've reached out to some other folks to solicit additional thoughts.

**Comment by howardhuanghua** [comment]
@rjernst thanks. Yes, this is an edge case, but if user got this case, it would be fatal, user cannot recover the cluster anymore. It's my pleasure to fix this issue if you could advise some better solutions.

**Comment by DaveCTurner** [comment]
You can recover from this in more recent versions using [`elasticsearch-node remove-settings`](https://www.elastic.co/guide/en/elasticsearch/reference/current/node-tool.html#_removing_persistent_cluster_settings) although that's not ideal.

I think it would be reasonable to allow removing the block and the archived settings in a single call. I don't think we should allow the two-step process proposed above since it completely bypasses some of the validation that we have in place today.

**Comment by howardhuanghua** [comment]
@DaveCTurner thanks for the suggestion. As far as I know, `archived` settings are coming from the duplicated settings during upgrading the cluster? User cannot set any `archived.*` settings? So the only case we set `archived.*` settings is to clean them? I mean user doesn't have any chance to set `archived.*` settings, so we could skip validation in `AbstractScopedSettings`?

If we still need to keep this validation, then check both cluster blocking status setting and `archived.*` settings together during validation, skip validation if both of them existing in the settings list? I am not sure user could get this point or not, we didn’t expect to set them at the same time before **rjernst**'s suggestion.

**Comment by DaveCTurner** [comment]
I think I don't fully understand your proposed changes to the validation. You seem to be suggesting skipping all validation of archived settings, which is definitely unacceptable: it's deliberate that you cannot do anything in the cluster until you clear the archived settings to acknowledge that they are no longer in force. You also cannot do anything in the cluster until you remove any read-only blocks. This is why it makes sense to me to try and do both of these in a single call. It is fair to say that this isn't clear from the docs, and we can address that too.

If that's not what you are proposing, then maybe it's simplest to open a PR to show your idea rather than trying to describe it further in words.
