### ISSUE TITLE
SYNONYM help

### ISSUE THREAD

**Issue by acclea** [elastic/elasticsearch#62921]
i need help, thanks.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: ik，SYNONYM

**JVM version** (`java -version`): 1.8.0_251

**OS version** (`uname -a` if on a Unix-like system): win10

**Description of the problem including expected versus actual behavior**:
SYNONYM can't match

**Steps to reproduce**:
ex:
 input: homework
synonym:homework,home,work
index-info:
1. home is sweet place
2.i offen in my home do some work
3.home can't go on to work

when i searched it, result nothing.
but 'hom&ework' or 'home|work' can searched.

thanks.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
HI @acclea! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by acclea** [comment]
> HI @acclea! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

I can't open this web,
so...
i came here,
sorry.
