### ISSUE TITLE
Upgrading ES 6.8 -> 7.9.2 questions

### ISSUE THREAD

**Issue by draganrelu** [elastic/elasticsearch#62940]
Hey,

We are planning to do an online 6->7 upgrade for our ES clusters, and we are looking into ways of rolling back safely from 7 to 6 in case something bad happens. The ES docs state that once the upgrade starts, the ES cluster will run into a backwards-compatible mode and will start using ES7 features after all nodes are fully upgraded. To get a better understanding of this, I have a few questions:

1) Is this switch happening automatically? Would it be possible to prevent it? (via a code change, or a setting change)

2)  What would be the place in the code where this switch would happen?

Thank you,
Relu

**Comment by cbuescher** [comment]
Hi @draganrelu! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
