### ISSUE TITLE
[ML] Adding custom rule with scope doesn't take effect on open job

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#62948]
Spotted in 7.8.1. Reproduced using an Elastic Cloud cluster.

**Description of the problem including expected versus actual behavior**:
This is regarding the update of an anomaly detection job's custom rules with a filter list while the job is open. It is expected that after the job config is updated with a filter list, any document processed by the job will be filtered.

Although the job update succeeds and the job config shows the updated custom rules, documents that match items in the filter list are still coming through.

**Steps to reproduce**:

 1. Create an anomaly detection job.
 2. Open the job, but don't start the datafeed.
 3. Update the job's custom rules with a filter list that matches some documents in the source data.
```
POST _ml/anomaly_detectors/job_with_filters/_update
{
  "detectors" : [
    {
      "custom_rules" : [
        {
          "actions" : [
            "skip_result",
            "skip_model_update"
          ],
          "scope" : {
            "field_to_filter" : {
              "filter_id" : "items_to_ignore",
              "filter_type" : "include"
            }
          }
        }
      ],
      "detector_index" : 0
    }
  ]  
}
```
 4. Start the datafeed.
 5. Notice that the documents that match items in the filter list are not excluded from the processed data.

**Comment by dimitris-athanasiou** [comment]
I have reproduced the issue and have understood the problem. The issue regards the exact scenario when a scoped rule is added. The rule actually gets updated in the process but the referenced filter doesn't and the update is rejected by the process.

Working on a fix.
