### ISSUE TITLE
Only send diff of cluster state instead of full cluster state

### ISSUE THREAD

**Issue by bluelu** [elastic/elasticsearch#6295]
If you have many nodes, and many index, even a small cluster state will trigger 500 MB of data to be sent to all nodes from the master. A few small rebalancing operations will kill the cluster.

This is a big issue.

Would be good if only the diff could be sent, then later merged. If node isn't at previous version, then fall back to current behaviour and send full state.

**Comment by ywelsch-t** [comment]
Hey @imotov, I'm working with @bluelu.

A more immediate patch to reduce the cluster state size which we plan to apply looks as follows: As we have many indices with the same mapping, deduplicating the index mappings reduces the cluster state to 1/3 of its size.

**Comment by s1monw** [comment]
we had a boat load of failures related to this so I branched off `feature/cluster_state_diffs` and reverted the commit from master.

**Comment by DrGonzo424** [comment]
I was wondering if there are plans to address the cluster state in an upcoming 2.x release.  We currently need to have thousands of small indexes to best support our data flow.  Right now we have almost 3000 indices and the GET request for cluster state takes around 40 seconds and effectively makes most admin tools (HQ, Head) non-functional.

**Comment by imotov** [comment]
@DrGonzo424 this change (which was merged into 2.0.0) only improves node-to-node communication which works over transport protocol. HQ and Head are using REST API and will not be able to take advantage of cluster state diffs.

**Comment by DrGonzo424** [comment]
Thanks for the quick reply, that is great to know that node-to-node communication will benefit from cluster state diffs as we are currently on 2.2.  Do you know if any of the admin tools do a better job of paging or caching the cluster state, to improve usability?  Right now it makes me a but uncomfortable that our administrative tools are not scaling with our cluster.  Perhaps there are some better admin tools out there.

**Comment by imotov** [comment]
@DrGonzo424 I think https://discuss.elastic.co/ would be a much better place to ask this question. My favorite admin tool is [_cat API](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/cat.html) it works fast even on large cluster states and does everything I need, but it might be too minimalistic for your purposes.
