### ISSUE TITLE
Open API to allow creating a SearchContext from an existing ShardSearchContextId

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#62956]
At the moment in _master_, it is not possible to create a `SearchContext` from an existing `ShardSearchContextId`. The methods required to do so are both `private` (see below). This would allow to leverage the [new reader context logic](https://github.com/elastic/elasticsearch/commit/879279c9b46b5a9606dfca96075e005624f0785d) within the [Federate plugin](https://siren.io/federate/) of siren.
Therefore, both methods below should be `public` in order to allow this:

https://github.com/elastic/elasticsearch/blob/860997b08c8452bee70a8d3ca63e977c1639bd29/server/src/main/java/org/elasticsearch/search/SearchService.java#L614

https://github.com/elastic/elasticsearch/blob/860997b08c8452bee70a8d3ca63e977c1639bd29/server/src/main/java/org/elasticsearch/search/SearchService.java#L720

**Comment by javanna** [comment]
Hello, sorry about our late reply. I am assuming you worked around this, hence I am closing this issue. Feel free to comment to add info if the suggested change is still of interest.
