### ISSUE TITLE
TransformContinuousIT.testContinousEvents test failed

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#62951]
**Build scan**:
https://gradle-enterprise.elastic.co/s/rpnsd3e5jwf3y

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" \
  -Dtests.seed=DA001B314F2CA42D \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Asia/Jayapura \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" \
  -Dtests.seed=DA001B314F2CA42D \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Asia/Jayapura \
  -Druntime.java=8
```

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
This is the first failure since August 6th.

**Failure excerpt**:
```
13:49:46 org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT > testContinousEvents FAILED
13:49:46     java.lang.AssertionError: Error in test case [continuous-terms-pivot-test].If you want to mute the test, please mute [org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT] only, but _not_ [org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT] as a whole.
13:49:46         at __randomizedtesting.SeedInfo.seed([DA001B314F2CA42D:E1366A2AC547267B]:0)
13:49:46         at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:258)
13:49:46 
13:49:46         Caused by:
13:49:46         java.lang.AssertionError: Ingest run: 1 did not match max run: 0.0, iteration: 1
13:49:46         Expected: <0.0>
13:49:46              but: was <1.0>
13:49:46             at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
13:49:46             at org.junit.Assert.assertThat(Assert.java:956)
13:49:46             at org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT.testIteration(TermsGroupByIT.java:144)
13:49:46             at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:249)
```

**Comment by hendrikmuhs** [comment]
Update:

The test failed 14 times in the last 24h. I will add extra debug logging to find the root cause.

**Comment by hendrikmuhs** [comment]
New failure with extra logging: https://gradle-enterprise.elastic.co/s/zyre3zt5twxb6

**Comment by nik9000** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/6a3rxv5czjggw/tests/:x-pack:plugin:transform:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT/testContinousEvents#1

**Comment by mark-vieira** [comment]
This is continuing to fail. @hendrikmuhs do we have enough diagnostic info from CI on this? Can we mute this for now until we have a fix?

**Comment by nik9000** [comment]
> This is continuing to fail. @hendrikmuhs do we have enough diagnostic info from CI on this? Can we mute this for now until we have a fix?

I've talked to @hendrikmuhs about this. I he's going to look at this tomorrow and I don't think waiting a day to mute this is a big deal because its not all that frequent. If you feel differently I can mute it.

**Comment by javanna** [comment]
@hendrikmuhs may this recent failure be related or is it a different one? https://gradle-enterprise.elastic.co/s/ovpotiny57i2m/tests/:x-pack:plugin:transform:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT/testContinousEvents#1

**Comment by hendrikmuhs** [comment]
@javanna Thanks for the ping. 

Looks like a new issue, the test implementation for `continuous-date-histogram-pivot-other-timefield-test` is younger than this issue. I will check if this reproduces for me asap.

**Comment by davidkyle** [comment]
A failure on 7.x: https://gradle-enterprise.elastic.co/s/wenxxiji5twto

```
Caused by: java.lang.AssertionError: Ingest run: 9 did not match max run: 7, iteration: 9
Expected: is a value less than or equal to <1>
     but: <2> was greater than <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.transform.integration.continuous.DateHistogramGroupByOtherTimeFieldIT.assertResultsGroupByDateHistogramAndTerms(DateHistogramGroupByOtherTimeFieldIT.java:211)
	at org.elasticsearch.xpack.transform.integration.continuous.DateHistogramGroupByOtherTimeFieldIT.testIteration(DateHistogramGroupByOtherTimeFieldIT.java:108)
	at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:258)
```

Reopening as there appears to be a few failures recently

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.branch,test.failed-testcases),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testContinousEvents),sort:!(process.time-start,desc))

**Comment by hendrikmuhs** [comment]
As said, this is not the same issue, but a new one, I created #64192.
