### ISSUE TITLE
unsigned_long Script query fails on master and 7.x

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#62975]
**Build scan**:

https://gradle-enterprise.elastic.co/s/su74sd55noel6

**Repro line**:
./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=unsigned_long/50_script_values/Script query}" \
  -Dtests.seed=44860D565D728165 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=Asia/Jerusalem \
  -Druntime.java=11

**Reproduces locally?**:
yes

**Applicable branches**:
master and 7.x

**Failure history**:
3 failures so far

**Comment by pugnascotia** [comment]
@mayya-sharipova is #62997 related, perhaps?
