### ISSUE TITLE
Doc: Backwards compatibility of monitoring clusters

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#63039]
https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-production.html#monitoring-production

![image](https://user-images.githubusercontent.com/7216393/94630795-9a6d0100-027b-11eb-8298-828288638a9d.png)

This question comes up a lot from the field (esp. when new versions get released).
We mention that monitoring a 7.x cluster requires a 7.x monitoring cluster.

It is quite common for users to upgrade monitoring clusters first to a newer version.  I believe we intend to support monitoring a 6.x cluster using a 7.x monitoring cluster as well.  In other words, the monitoring cluster is 1 major version backwards compatible with the monitored cluster.  Would be nice to confirm that there are no edge case exceptions and document this accordingly.  Thx!

**Comment by ravikesarwani** [comment]
We need to make 2 changes to the following [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-production.html#monitoring-production)

(1) Remove line "If you are sending your data to the ESMS, see Elastic Stack Monitoring Service."
ESMS is retired and we shouldn't mention this is our doc anymore.

(2) Modify our compatibility production<->monitoring cluster compatibility line from:
"To monitor an Elasticsearch 7.x cluster, you must run Elasticsearch 7.x on the monitoring cluster."

TO

"The monitoring cluster and the clusters being monitored (aka production clusters)
Should run the same version of the stack
OR
The monitoring cluster can run the latest release of the same major version as the production clusters
OR
The monitoring cluster can monitor production clusters running the latest release of the previous major version."

**Comment by ravikesarwani** [comment]
@lcawl Lisa, would you be able to help make the above changes in the document? If you are not the right person who should I contact that can help to make this doc change. Thanks!

**Comment by VimCommando** [comment]
I feel like these two statements:

> "The monitoring cluster and the clusters being monitored (aka production clusters)
Should run the same version of the stack
> OR
> The monitoring cluster can run the latest release of the same major version as the production clusters

Are a little confusing. I feel it is really saying:

> The monitoring cluster needs to be running the same major version, on the same or newer minor release, as the monitored clusters.

**Comment by ravikesarwani** [comment]
@VimCommando I am not very sure about combining the 3 scenarios into one. This is something I had discussion with few support people before and the thinking was keeping them separate provides more clarity and the order of preference as well.
Once we have a doc person taking a look at it we can get another viewpoint added to the equation.
