### ISSUE TITLE
esplugin always appends scm and url to POM, even if they already exist

### ISSUE THREAD

**Issue by dweiss** [elastic/elasticsearch#63108]
This is problematic in PublishPlugin.java:
```
    private static void addScmInfo(XmlProvider xml) {
        Node root = xml.asNode();
        root.appendNode("url", Util.urlFromOrigin(BuildParams.getGitOrigin()));
        Node scmNode = root.appendNode("scm");
        scmNode.appendNode("url", BuildParams.getGitOrigin());
    }
```

as it always appends url and scm nodes, even if they've been configured before, creating duplicated XML entries and resulting in an invalid POM. I think it should be allowed for downstream plugins to define these properties manually and, if they exist, they shouldn't be force-fed to the POM.

**Comment by rjernst** [comment]
I'm curious why you would want to set this on your own, rather than rely on the automatic value found by the build? That said, it is certainly possible to add guards here, but we lack tests in this area, so it may break in the future until that improves.

Can you provide an example of how you are setting this on your own such that it conflicts, so that we can confirm the change will fix this problem?

**Comment by dweiss** [comment]
I don't use nebula - I use regular Gradle publishing. I also had it set up properly and when I upgraded to new ES release it failed with an awkward error (POM invalid). The checks and automatic setup is fine for ES infrastructure (for you guys) but I don't think it's that beneficial for others. I actually had to disable some of the POM validation stuff because it was complaining about missing bits (developer's url section if I recall right?). This doesn't make sense in our case.

https://github.com/carrot2/elasticsearch-carrot2/blob/master/build.gradle#L165-L201

**Comment by rjernst** [comment]
I agree we should let developers publish however they choose. We have been moving towards making esplugin more lightweight, and leaving our elastic specific bits to only be used within our build.

In this case I think we can do that by removing PublishPlugin from esplugin. I'll try to find some time to do this.

**Comment by dweiss** [comment]
Thanks Ryan. Let me know if you need help testing.

**Comment by williamrandolph** [comment]
Since this ticket appears to be on @rjernst 's to-do list, I'm going to remove the needs:triage label and leave it as is.

**Comment by mark-vieira** [comment]
We no longer apply `PublishPlugin` in `PluginBuildPlugin` so I think this is not longer an issue. @dweiss are you still seeing this behavior with the latest `build-tools` versions?

**Comment by dweiss** [comment]
I'll take a look next time around when I'm publishing an update to the plugin. Thanks for letting me know, Mark.

**Comment by dweiss** [comment]
Sorry for the delay. It's still a problem because PluginBuildPlugin applies BuildPlugin and this one in turn applies publish plugin:
```
project.getPluginManager().apply("elasticsearch.publish");
```
This applies all the way to es 7.11.2 I just tried.

**Comment by mark-vieira** [comment]
We no longer apply our internal `BuildPlugin` in the `PluginBuildPlugin`.
