### ISSUE TITLE
Performance issue: Rest High Level Client unnecessary parses _source

### ISSUE THREAD

**Issue by azhuchkov** [elastic/elasticsearch#63129]
**Elasticsearch version** (client library): 7.5.1

**Description of the problem including expected versus actual behavior**:
I have sophisticated **Jackson** mapping for (un-)marshalling objects which are used for indexing. After performing search request these documents are needed to be deserialized manually from string returned by `SearchHit.getSourceAsString()`. 

So, there is no need for client library to parse returned source. But actually the client does this for unknown reason - according to comments from source code, it strips whitespaces and indentations. As a result source documents are being parsed twice. Moreover **JVM profiler** says that `SearchHit.parseSourceBytes()` consumes more time than my own Jackson parser. 

Is there a way to avoid this additional parsing using **High Level client**? Or using low level one is the only option so far?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
