### ISSUE TITLE
[CI] Problem building build tools on Windows

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#63232]
**Build scan**:

https://gradle-enterprise.elastic.co/s/6m5fpo3u7phqa

**Repro line**:

```
gradlew.bat :build-tools:integTest
```

**Reproduces locally?**:

Yes (on Windows)

**Applicable branches**:

master

**Failure history**:

Failed every day since 1st October:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:InternalDistributionBwcSetupPluginFuncTest),sort:!(process.time-start,desc))

**Failure excerpt**:

The failure email reports these failed tests:

```
org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest builds distribution from branches via archives assemble
org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest bwc distribution archives can be resolved as bwc project artifact
org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest bwc expanded distribution folder can be resolved as bwc project artifact
org.elasticsearch.gradle.internal.InternalBwcGitPluginFuncTest current repository can be cloned
```

The console log for one of these looks like this:

```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\JENKIN~1.PAC\AppData\Local\Temp\junit11950913961942412554\remote with arguments [:distribution:bwc:bugfix:buildBwcDarwinTar, :distribution:bwc:bugfix:buildBwcOssDarwinTar, -DtestRemoteRepo=C:\Users\JENKIN~1.PAC\AppData\Local\Temp\junit3150283545385647587\remote\.git, -Dbwc.remote=origin] |  
-- | --
  |   |  
  | Output: |  
  |   |  
  | FAILURE: Build failed with an exception. |  
  |   |  
  | * What went wrong: |  
  | Project directory 'C:\Users\jenkins.PACKER-5DA68B4D\AppData\Local\Temp\junit11950913961942412554\remote' is not part of the build defined by settings file 'C:\Users\jenkins.PACKER-5DA68B4D\AppData\Local\Temp\junit11950913961942412554\settings.gradle'. If this is an unrelated build, it must have its own settings file.
```

**Comment by imotov** [comment]
Failed again in https://gradle-enterprise.elastic.co/s/a6kbfo3rlcqde

**Comment by breskeby** [comment]
Fixed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/278/

**Comment by dliappis** [comment]
Noticed the same in 7.10 e.g. in https://gradle-enterprise.elastic.co/s/nlfxjehu4pftm; fix might need backporting.
