### ISSUE TITLE
[CI] RoundingDuelTests.testSerialization failures

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#63256]
**Build scan**:

1. https://gradle-enterprise.elastic.co/s/yolyw4q244v4k
2. https://gradle-enterprise.elastic.co/s/tthsxuy6b6arq
3. https://gradle-enterprise.elastic.co/s/5rcdquw445aye

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.common.rounding.RoundingDuelTests.testSerialization" \
  -Dtests.seed=61B72CA82AC641C4 \
  -Dtests.security.manager=true \
  -Dtests.locale=de-DE \
  -Dtests.timezone=VST \
  -Druntime.java=8
```

**Reproduces locally?**:

Sometimes, though interestingly this doesn't seem to be deterministic given a test seed - when it fails locally the exact numbers are different to those from the CI failure.

**Applicable branches**:

7.x

**Failure history**:

3 times today, none before:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RoundingDuelTests),sort:!(process.time-start,desc))

**Failure excerpt**:

```
org.elasticsearch.common.rounding.RoundingDuelTests > testSerialization FAILED
    java.lang.AssertionError: 
    Expected: is <3279600000L>
         but: was <4141850467L>
        at __randomizedtesting.SeedInfo.seed([5655895357D141DB:28DE81B70837C47]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.common.rounding.RoundingDuelTests.testSerialization(RoundingDuelTests.java:57)
```

**Comment by droberts195** [comment]
Since this is happening frequently now I muted the test in 7.x (only) in a522e932e852f08bde0baa8feaeb47a674aa4964

The failing test doesn't exist in master for some reason.  @nik9000 I am guessing this problem is a side effect of 461475f9e9dfe5e49ff43af4c57123dafe024ccd.

**Comment by nik9000** [comment]
Sounds likely! I'll take a look.
