### ISSUE TITLE
EQL: Divergent `ignore_unavailable` behavior

### ISSUE THREAD

**Issue by rylnd** [elastic/elasticsearch#63295]
EQL queries appear to have differing behavior for the `ignore_unavailable` option as compared to a standard query.

While a user can perform a regular search across unavailable indexes:

```js
# SETUP: indexes match the auditbeat-* pattern, while none matches foo*

GET auditbeat-*,foo*/_search
// success

GET auditbeat-*,foo*/_eql/search
// index_not_found_exception: no such index [foo*]
```

This only appears to be an issue with wildcard indexes, since passing a concrete (unavailable) index works as expected:

```js
GET auditbeat-*,foo*/_eql/search
// index_not_found_exception: no such index [foo*]

GET auditbeat-*,foo/_eql/search
// success
```

__Update__: one more data point: `allow_no_indices` can be used to bypass this behavior:

```js
GET auditbeat-*,foo*/_eql/search
// index_not_found_exception: no such index [foo*]

GET auditbeat-*,foo*/_eql/search?allow_no_indices=true
// success
```

Note: this is a followup to [this issue](https://github.com/elastic/elasticsearch/issues/62986), particularly: [this comment](https://github.com/elastic/elasticsearch/issues/62986#issuecomment-703967815).

**Comment by costin** [comment]
This has been solved through https://github.com/elastic/elasticsearch/issues/63561 and https://github.com/elastic/elasticsearch/issues/63529
