### ISSUE TITLE
QL: Add support for unsigned_long field type

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#63312]
Following https://github.com/elastic/elasticsearch/pull/60050 merge, we should consider adding support for it in both EQL and SQL.

**Comment by stu-elastic** [comment]
Unsigned long support has been added in https://github.com/elastic/elasticsearch/pull/76519 which has been backported to v7.15

 You can use `doc['ul'].value` which will return a `java long` (which means values greater than 2^63 are negative), or the fields api equivalent `field('ul').getValue(default)`.

You can also treat it as a `BigInteger`, `field('ul').as(Field.BigInteger).getValue(default)`.  For examples, check out the [yamlRestTest](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/unsigned_long/50_script_values.yml#L145)
