### ISSUE TITLE
`_score` always 0 in cardinality aggregation

### ISSUE THREAD

**Issue by nonmanager** [elastic/elasticsearch#63318]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.1

**JVM version** (`java -version`): OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

**Description of the problem including expected versus actual behavior**:

When `_score` is accessed in a [scripted cardinality aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_script_4), it always return 0, instead of the document's actual score. The same field behaves correctly in several other metric aggregations.

**Steps to reproduce**:

1. Populate the DB with sample entries:
```
POST score-test/_doc/1
{
  "letter": "A",
  "number": "1"
}

POST score-test/_doc/2
{
  "letter": "B",
  "number": "1"
}

POST score-test/_doc/3
{
  "letter": "A",
  "number": "2"
}

POST score-test/_doc/4
{
  "letter": "B",
  "number": "2"
}
```

2. Perform a query using `function_score` to manually assign scores. Then use the scores in a cardinality aggregation in order to count the number of distinct scores. For comparison, also include a max aggregation on `_score`.
```
GET score-test/_search
{
  "query": {
    "function_score": {
      "query": { "match_all": {} },
      "functions": [
        {
          "filter": { "match": { "letter": "A" } },
          "weight": 5
        },
        {
          "filter": { "match": { "number": "1" } },
          "weight": 10
        }
      ],
      "score_mode": "sum",
      "boost_mode": "replace"
    }
  },
    "aggs": {
      "test_card": {
        "cardinality": {
          "script": {
            "source": "_score"
          }
        }
      },
      "test_max": {
        "max": {
          "script": {
            "source": "_score"
        }
      }
    }
  }
}
```
3. Observe the result returned by ES. The document scores are correct (15, 10, 5, and 1). The max aggregation is also as expected (15). However, the cardinality aggregation returns 1 instead of 4 (4 distinct scores). By using `Debug.explain(_score)`, we can confirm that this is because each `_score` is wrongfully seen as 0 (and so only one distinct value is reported).
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : 15.0,
    "hits" : [
      {
        "_index" : "score-test",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 15.0,
        "_source" : {
          "letter" : "A",
          "number" : "1"
        }
      },
      {
        "_index" : "score-test",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 10.0,
        "_source" : {
          "letter" : "B",
          "number" : "1"
        }
      },
      {
        "_index" : "score-test",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 5.0,
        "_source" : {
          "letter" : "A",
          "number" : "2"
        }
      },
      {
        "_index" : "score-test",
        "_type" : "_doc",
        "_id" : "4",
        "_score" : 1.0,
        "_source" : {
          "letter" : "B",
          "number" : "2"
        }
      }
    ]
  },
  "aggregations" : {
    "test_max" : {
      "value" : 15.0
    },
    "test_card" : {
      "value" : 1
    }
  }
}
```

**Comment by polyfractal** [comment]
I believe this is an updated version of https://github.com/elastic/elasticsearch/issues/25337, which itself is a derivation of https://github.com/elastic/elasticsearch/issues/26294

I'd generally agree with some of the comments in #25337 that cardinality on score tends to not make much sense (since, outside of function_score, scores are likely to be a wide range of double values).  But that said, since other aggs support it, we should probably be consistent here and support the same in cardinality

**Comment by not-napoleon** [comment]
We're migrating towards runtime fields as a replacement for aggregation scripts in general, and we don't support `_score` in runtime fields.  And as already noted, `_score` on cardinality doesn't make a whole lot of sense.  Given that, I'm closing this as won't fix.
