### ISSUE TITLE
Tribe node with Amazon public DNS in a multi-region setup

### ISSUE THREAD

**Issue by Dchamard** [elastic/elasticsearch#6333]
Trying to configure a tribe node on a multi-region clusters setup, I am running into an issue trying to configure this setup with Amazon Public DNS.

discovery.ec2.host_type: public_dns
network.publish_host: _ec2:publicDns_

In that case, the remote tribe node... discover the cluster but then try to connect to the remote node with his local.ip
With public_Ip, it seems to be working but its not acceptable in our situation since we do not want the internal cluster to talk internally with Public I.p

Normally using public_dns go around  that issue.. since it tries to connect  using internal i.p when it makes sense.

**Comment by rparkhunovsky** [comment]
Hi @Dchamard
Interested too!!

**Comment by dadoonet** [comment]
I think it's related to this issue: https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/76

**Comment by rparkhunovsky** [comment]
The bug has been around for almost a year which makes using such a useful feature complicated. I'm eager to provide details to test and fix it!

**Comment by Pryz** [comment]
Any news or feedback on that ?

I'm facing the same issue with elasticsearch 1.7.1

**Comment by clintongormley** [comment]
Closing in favour of #21473
