### ISSUE TITLE
Fix: Update the JdkDownloadPlugin to stop trying to download the JDK from an outdated URL

### ISSUE THREAD

**Issue by palesz** [elastic/elasticsearch#63353]
The URL the [JdkDownloadPlugin](https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/java/org/elasticsearch/gradle/JdkDownloadPlugin.java#L116) class is looking for OpenJDK version 15 is dead:
https://download.oracle.com/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_mac-x64_bin.tar.gz

The actual live URLs where JDKs can be found:

- Current Oracle JDK: `https://download.oracle.com/otn-pub/java/jdk/15+36/779bf45e88a44cbd9ea6621d33e33db1/jdk-15_osx-x64_bin.tar.gz`
- OpenJDK URL: `https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_osx-x64_bin.tar.gz`

**Comment by rjernst** [comment]
This will be fixed by https://github.com/elastic/elasticsearch/pull/63309

**Comment by palesz** [comment]
FYI: #63309 only changes `mac` -> `osx`, but the domain and the url pattern also changed.
