### ISSUE TITLE
Adding co-ordinator related stats to Node Stats API

### ISSUE THREAD

**Issue by anshul291995** [elastic/elasticsearch#63378]
Stats API endpoints don't have any statistics about the metrics ( latency/ success rate / queue length) seen by the coordinator node. While search/indexing latencies on data node are greatly helpful, a view from co-ordinator node is required. This will help us look at statistics from the point elastic search cluster has received the rest request, such as:

1. Time spend in each individual phases     
2. Response time from individual nodes during indexing/ search. This might also give us indications of network being slow 
    or identify faulty nodes.
3. Rejections at coordinator level.
4. Time spent in queue.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
