### ISSUE TITLE
Highlighting tags do not surround special characters at end of search string

### ISSUE THREAD

**Issue by roblangenfeld** [elastic/elasticsearch#6341]
Elastic Search Version 1.1
Java API

Issue: We are using elastic search 1.1 and performing highlighting on the our results. We starting noticing a particularly strange occurence where the tags where being inserted in regards to single quotes.

If I were to search the exact sting (with single quotes): 'de
I am returned this string as one of my results (this works):
<b>'de</b>termine output from
However if I perform this search: de'
Now the tags do no honor the single quote anymore and this string is returned:
'Add co<b>de</b>' button

So the issue here is that when it comes to highlighting, es is not honoring trailing single quotes in the highlighting. But if the quote comes first in the search string it will honor it in the highlighting. Elastic search should honor wrapping the highlighting tags around the entirely found search string when it ends with a single quote.

Update:

This issue also occurs with any special character " / \ | and more when they are the last item in the search string, they don't get highlighted.

**Comment by clintongormley** [comment]
No recreation provided, but this looks like a simple problem with analysis which removes punctuation.
