### ISSUE TITLE
Should Snapshots include hidden indices by default?

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#63448]
In https://github.com/elastic/elasticsearch/pull/57325, Snapshot index resolution was changed to include hidden indices by default. At the time, there was [a plan](https://github.com/elastic/elasticsearch/issues/57208#issuecomment-636149039) to emit a deprecation warning when wildcards in Snapshot requests resolved to hidden indices in such a way that they would not be included by the default wildcard resolution behavior and switch snapshots to using the default resolution behavior in the next major version (as this would be a breaking change), but I recall that there was some objection to this at the time that I cannot now locate.

This issue is to track any necessary discussion on that topic and record a final decision.

**Comment by original-brownbear** [comment]
Closing this one as it seems it went stale and we can't really change this without a massive BwC issue at this point anyway.
