### ISSUE TITLE
Fix error reporting for SSL resources outside of config dir

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#63451]
In #55330 we change the sequence of events on startup so that the SSL resource watcher code runs before the SSL contexts are loaded.

As a consequence some of the friendly error messages that were added in #45122 are no longer used (because the reloader fails before it gets to the key/trust config objects)

**Comment by burnerlee** [comment]
@tvernum i would like to start contributing to this project starting with this issue.. could you please guide a bit on how to start with getting familiar with your project

**Comment by BarshaR** [comment]
First timer here - looking into this issue. Will reach out if I have any questions :)

**Comment by orhanar** [comment]
Hi just started open source contribution can I work on this?

**Comment by tvernum** [comment]
@orhanar 
Sorry, there's already work in progress on this issue.

**Comment by orhanar** [comment]
> @orhanar 
> 
> Sorry, there's already work in progress on this issue.

no worries
