### ISSUE TITLE
[CI] Failures in FullClusterRestartIT.testSystemIndexMetadataIsUpgraded

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#63457]
**Build scan**:
https://gradle-enterprise.elastic.co/s/dwlvjbmo23uyi

**Repro line**:
./gradlew ':qa:full-cluster-restart:v6.1.1#oldClusterTest' --tests "org.elasticsearch.upgrades.FullClusterRestartIT.testSystemIndexMetadataIsUpgraded" \
  -Dtests.seed=6AB0BF4E78C3CA4A \
  -Dtests.security.manager=true \
  -Dtests.locale=hr \
  -Dtests.timezone=Europe/Dublin \
  -Druntime.java=8

**Reproduces locally?**:
yes

**Applicable branches**:
7.10, 7.x

**Failure history**:

**Failure excerpt**:
» [2020-10-08T10:30:07,203][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [v6.1.1-0] failed to put mappings on indices [[[test_index_old/qcZuuZPsTn6NlkJ7RNL8jA]]], type [_doc]
»  org.elasticsearch.indices.InvalidTypeNameException: Document mapping type name can't start with '_', found: [_doc]
»       at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:297) ~[elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:640) ~[elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:195) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:130) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.1.1.jar:6.1.1]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.1.1.jar:6.1.1]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
»       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by cbuescher** [comment]
Also fails on 7.x:  https://gradle-enterprise.elastic.co/s/uoawdq52pv7ta

**Comment by cbuescher** [comment]
This fails quite often so I'm muting on 7.10 and 7.x

**Comment by cbuescher** [comment]
Muted on 7.x and 7.10 with cb0b01ed48f83cf6bd6e8ea40e638de8bc09356b and 1f7b107ed132b6ccad351b95dab93adf1c3818ad

**Comment by rjernst** [comment]
Fixed by #63506
