### ISSUE TITLE
[CI] RoundingTests.testRandomTimeIntervalRounding fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#63467]
**Build scan**: https://gradle-enterprise.elastic.co/s/2gc6ssqmwu6r2

**Repro line**:
./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeIntervalRounding" \
  -Dtests.seed=2FA254ED28F9337D \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-JO \
  -Dtests.timezone=Asia/Ust-Nera \
  -Druntime.java=11

**Reproduces locally?**:
yes 

**Applicable branches**:
master

**Failure history**:
Another one yesteraday on master: https://gradle-enterprise.elastic.co/s/czzwgfh2zovfi

**Failure excerpt**:
java.lang.AssertionError: utcMillis must be after 625620000000
        at __randomizedtesting.SeedInfo.seed([2FA254ED28F9337D:8CE0E3A980040E19]:0)
        at org.elasticsearch.common.Rounding$ArrayRounding.round(Rounding.java:1319)
        at org.elasticsearch.common.RoundingTests.testRandomTimeIntervalRounding(RoundingTests.java:449)

**Comment by cbuescher** [comment]
@nik9000 could you take a look, I remember you were active in that area recently

**Comment by cbuescher** [comment]
Also on 7.x e.g. https://gradle-enterprise.elastic.co/s/hqtkum6n25op4

**Comment by cbuescher** [comment]
Another one on 7.x. I'm considering muting since this seems to happen fairly often now.

**Comment by nik9000** [comment]
Sorry! I promise I'll look at it this afternoon. If you have a chance to mute please do.

**Comment by cbuescher** [comment]
Muted with 3e06f08498d and 10f0dfda504d1533dfa47edbaaa308ef2dab128b on master and 7.x

**Comment by nik9000** [comment]
Fixed by 1c193f0168db36af61884155ee6fa9152ef00070.
