### ISSUE TITLE
Ingest pipeline parses the wrong week of the year

### ISSUE THREAD

**Issue by antonisnyc94** [elastic/elasticsearch#63489]
Hello,

I am trying to parse weekly indices by utilizing the ingest pipelines in elasticsearch but I keep getting a week before the actual week of the year. Would you know what the issue is?

{
        "date_index_name" : {
          "date_rounding" : "w",
          "index_name_prefix" : "{{fields.index_prefix}}",
          "index_name_format" : "YYYY.ww",
          "ignore_failure" : false,
          "field" : "timestamp"
        }

Today (10/8)  is the 41st week of the year but the my index shows the 40th.

Thanks a lot for your help.

**Comment by pgomulka** [comment]
hey @antonisnyc94 
thank you for raising this.
can you confirm ES version and JDK used?
we fixed this in ES 7.6 https://github.com/elastic/elasticsearch/pull/48209 but it requires JDK9+

**Comment by antonisnyc94** [comment]
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

It appears that im having version 8. I"ll upgrade and keep you posted.

Thanks a lot for the reply!

**Comment by antonisnyc94** [comment]
I dont know how upgrading to openjdk 11 will impact my cluster so for now I am accepting the one week delay for the index. Thanks a lot for your input tho.

regards,
Tony

**Comment by pgomulka** [comment]
@antonisnyc94 jdk9+ support the fix we implemented. More specifically it allows loading SPIs from classpath, so ES was able to implement a CalendarDataProvider with correct ISO settings
