### ISSUE TITLE
Profile can match

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#63482]
I was investigating a performance issue and the profile said everything was quite fast. But the request was quite slow! We've talked about using #61947 as a work around for the profiler not covering everything, but I expect it wouldn't pick up can_match because `can_match` isn't cpu intensive, it's a ton of network stuff.

**Comment by javanna** [comment]
heya @nik9000 , I am trying to understand how this could be implemented. You were suggesting to add a section for can match to the output of the profile API, or something along those lines?

**Comment by nik9000** [comment]
I think that's what I was suggesting, yeah.

**Comment by javanna** [comment]
That makes sense, I see this implemented as part of # 21073 , hence I would lean towards closing this issue. Let me know if you think otherwise.
