### ISSUE TITLE
Difference in deb/rpm init scripts

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#6351]
After checking the init scripts there are allot of differences between them.
This is the result after an initial scan of the files.

RPM doesn't have:

* id = root check ( validation of the user trying to start is the root user )
* default values ( currently sysconfig file is leading while default values should be in init script and sysconfig file should override those )
* Debian script has a nice DAEMON and DAEMON_OPTS variables to keep things clean and simple.
* Check for different JDK directories to use.
* -Des.default.config=$CONF_FILE option when launching ES.
* Uses lower and upper case variable names ( nicer to use upper case everywhere. )

DEB doesn't have:

* Daemon check ( does the program exist )
* Does the config file exist?
* mkdir/chown for general directories
* if MAX_LOCKED_MEMORY is set, make sure that ES_HEAP_SIZE  is set as well.

**Comment by clintongormley** [comment]
I believe these scripts have been sync'ed up now, closing
