### ISSUE TITLE
[Queries] make "Span field masking" consistent with other span queries

### ISSUE THREAD

**Issue by homersimpsons** [elastic/elasticsearch#63527]
### Request

Rename `field_masking_span` to `span_field_masking`.

### Explanations

Currently the [Span field masking query](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/query-dsl-span-field-masking-query.html) is the only [`span_*`](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/span-queries.html) to end with `_span` instead of starting with `span_`

The query builder is coherent with this naming and should be updated accordingly
https://github.com/elastic/elasticsearch/blob/4e740c2e4a544c7e99963ccd9f64686b1f0531e1/server/src/main/java/org/elasticsearch/index/query/QueryBuilders.java#L377

Lucene had the right naming:
> The span field masking query maps to Lucene’s `SpanFieldMaskingQuery`

Of course this is a Breaking Change so it should not land before 8.0.0. This is also not critical, but this could improve the naming consistence of all span queries.

**Comment by sabiya** [comment]
@homersimpsons I am interested to pick this.
Can I start to work on this?

**Comment by homersimpsons** [comment]
@sabiya I am sorry I was just mentioning the issue, I do not know if the search Team is willing to make this change...

**Comment by romseygeek** [comment]
@homersimpsons thanks for opening the issue.  We think this is a reasonable change to make, please feel free to work on it @sabiya .

The important thing to do here will be to ensure that we maintain backwards compatibility.  The simplest way forward I think will be to change the QuerySpec registration for this query to use a ParseField rather than a String for the name, and set things up so that the old name is added as a deprecated name to the ParseField.

**Comment by soarescaique** [comment]
Can I work on this? Since it's still opened?

**Comment by sabiya** [comment]
Hello @soarescaique,
I have taken this issue, was waiting for someone to confirm.
I would like to fix it. Please pick another issue.

**Comment by eduardomaksoud** [comment]
Hi, i'd like to pick this issue. @sabiya are you still working on it?

**Comment by GrayFox1** [comment]
Hi @homersimpsons, it seems that sabiya is no longer working on this issue, so i would like to contribute. I opened a PR and since this is my first contribution, i'd be really glad if you could give me some feedback.

**Comment by homersimpsons** [comment]
Hello @GrayFox1 thank you for your PR, I'm not affiliated to elasticsearch so I won't be able to help you...

Maybe @romseygeek will be able to answer you.

**Comment by GrayFox1** [comment]
Thanks @homersimpsons. The ParseField that i've created deprecates the previous naming besides replacing those occurrences, but i'm still trying to understand if i need to change the QuerySpec registration. 

I would appreciate if you could give me some feedback. @romseygeek
