### ISSUE TITLE
The number of sharding is automatically increased.

### ISSUE THREAD

**Issue by gaohuag** [elastic/elasticsearch#63528]
The default number of sharding changed from 5 to 1, but if the the data is more and more big, and then we need to change the number of sharding, this process is artificial, very inconvenient, we need a more convenient way of operation, thank you.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

As an additional note: To set the number of shards on an index you can specify `index.number_of_shards` [when you create the index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html).
