### ISSUE TITLE
Add ability to sort composite aggr, with missing_bucket  = true, like a normal search sort

### ISSUE THREAD

**Issue by joevalerio** [elastic/elasticsearch#63523]
Add ability to sort composite aggr, with missing_bucket  = true, like a normal search sort

For normal search sort you have the following options:

"The missing parameter specifies how docs which are missing the sort field should be treated: The missing value can be set to _last, _first, or a custom value (that will be used for missing docs as the sort value). The default is _last."
\- [sort-search-results](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html)

When you are using a composite aggr sort with missing_bucket = true the options are:

"The order specified in the source dictates whether the null values should rank first (ascending order, asc) or last (descending order, desc)."
 \- [search-aggregations-bucket-composite-aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-aggregations-bucket-composite-aggregation.html#_missing_bucket)

These options are conflicting, in that I can never get the nulls always last for both of asc or desc using a composite aggr which conflicts with the normal search sorting leaving my application inconsistent.  I would really appreciate adding the ability to sort nulls always last or always first like the normal search sort.

**Comment by nik9000** [comment]
`composite` has some technical limitations based on its goal of wanting to allow scrolling aggs but I believe we could do a fair bit to make sorting in composite more similar to sorting in top hits. Long story short: something like this is almost certainly possible to implement.

*but* I think that this could end up as quite a deep rabbit hole. A few of us met over zoom to talk about and talked about this and decided to leave it open as a fine thing to do, but that none of us wanted to do it ourselves any time soon.
