### ISSUE TITLE
Documentation: Add additional details regarding supported Java versions for the Java High Level REST Client

### ISSUE THREAD

**Issue by joshjanoski** [elastic/elasticsearch#63525]
The documentation for the Java High Level REST Client here: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html states: 

`The Java High Level REST Client requires Java 1.8`

However, Java 1.8 is just the minimum requirement, and the Java HLRC also supports whatever versions of Java are supported by the associated Elasticsearch release. For example, Elasticsearch 7.9.x supports Java 1.8, 11, 14, and 15, so the 7.9 HLRC will work with all of these Java versions. Requesting that the documentation be updated to clarify that since how it is written right now leads to the assumption that only Java 1.8 will work. Thank you!

**Comment by lockewritesdocs** [comment]
#63106 already has a fix in place for this clarification. 

Closed by #63016
