### ISSUE TITLE
Enable users to migrate v1 rollup indices to Rollup v2

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#63570]
We want users of the existing, experimental, rollup feature to be able to migrate existing rolled up data to the new version as cleanly as possible.  This ticket covers only migrating the index (documents and metadata), not the rollup job itself.

Notes and consideration:
- Need to look at how the rollup relates to the base index.  There are three cases:
  - The base index no longer exists, or no longer contains the data the rollup covered.
  - The base index has additional data for the time span the rollup covers
  - The base index still exactly matches the rollup
- State of the rollup job
  - Is the job currently running?  Probably needs to be stopped before we can safely migrate
  - What's the last good point at which the rollup and the index were synced?
- Differences between v1 and v2
  - In v1, we allowed multiple, unrelated rollups of the same base index.  This doesn't map cleanly into the v2 model.
- Need a way to disable the job after migration?

Plan:
- We can delegate the work of actually scrolling through the existing rollup to a reindex job.
- Reindex can use a transformation script to adapt each document.  For ease of testing, we can build a dedicated script context that only converts v1 style rollup records to v2 style rollup records.
- In addition to migrating each record, the job will need to validate the source index, and migrate/set up the metadata.

Tasks:
- [ ] Validate source index
    - Is it possible for a v1 rollup to not be valid in v2?
    - At a minimum, confirm that the source index is a v1 style rollup index
- [ ] Migration script for individual documents
- [ ] Metadata migration

Relates to #42720

**Comment by not-napoleon** [comment]
Marking this as stalled.  Effectively, this is blocked on #42720, which is also stalled.

**Comment by csoulios** [comment]
The team has decided that we will not migrate existing rollup indices to the new rollup/dowsampled indices, because there are so many incompatibilities in the structure of those indices. 

Hence, I am closing this issue.
