### ISSUE TITLE
Random shards do not recover if one index has faulty synonym filter defined

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#6357]
I use a synonym filter with the synonyms defined in a text file. 1 node, several indexes with several shards, only one of them uses the synonym filter. When I remove the textfile that contains the synonyms many indexes do not recover when I restart the node. This is random, affected shards and indexes vary.

To reproduce:

1. start node and create some indexes with documents
1. place synonym file in correct folder, create index that uses synonym filter with synonyms from file and index documents (see example below for details)
2. stop node
3. remove the synonym file
4. start node again

I would have expected only the affected index shards not to recover but instead this is completely random.

Example index:

```
DELETE synonymindex

PUT synonymindex
{
   "settings": {
      "index": {
         "analysis": {
            "analyzer": {
               "synonym": {
                  "tokenizer": "whitespace",
                  "filter": [
                     "synonym"
                  ]
               }
            },
            "filter": {
               "synonym": {
                  "type": "synonym",
                  "synonyms_path": "analysis/synonym.txt"
               }
            }
         }
      }
   },
   "mappings": {
      "sometype": {
         "properties": {
            "text": {
               "type": "string",
               "analyzer": "synonym"
            }
         }
      }
   }
}

POST synonymindex/sometype
{
    "text": "foo"
}
```

the file analysis/synonym.txt contains only one line:

```
foo, bar
```

**Comment by brwe** [comment]
cannot reproduce anymore

**Comment by kimchy** [comment]
@brwe to close the loop, this fixed it: https://github.com/elastic/elasticsearch/pull/10283
