### ISSUE TITLE
Ability to define default for track-total-hits from cluster or index settings

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#63689]
From [7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#track-total-hits-10000-default), track-total-hits defaults to 10000 and must be set at request level to show more accurate total hit
It would be useful to be able to set default value for cluster instead of via individual request. For example if an application always require accurate count, a change is required for all searches defined and in some cases having a cluster setting would allow easier upgrade by setting the setting at cluster level

**Comment by yurafff** [comment]
Is this task still relevant? I want to help with the implementation of this feature

**Comment by damienalexandre** [comment]
This has been discussed already at #46779 and the conclusion was to not add a setting, and things could have been done more smoothly.

I'm currently migrating an application from 5.x to 7.x and not having this kind of global setting will prevent me from having queries compatible with both 5.x and 7.x (which would have been helpful for a no downtime migration).

**Comment by jimczi** [comment]
Following the recommendation discussed in https://github.com/elastic/elasticsearch/issues/46779 I am closing this issue. We'll not provide an index setting for this parameter that can be changed on a per-request basis.
