### ISSUE TITLE
EQL: Improve grammar to handle bool declarations

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#63695]
The following query `process where field` is allowed in EQL but requires special handling because the condition is invalid, should be `field == true`. This can easily _leak_ inside other expressions such as `where functionA(field) > 0 and field or functionB(field) + 1 > 0`
The parser should pick this up and add a proper declaration instead of forcing the Optimizer or query translator to fix it down the stream.

See #63694

**Comment by rw-access** [comment]
I'm not sure this is actually possible to enforce grammatically. And I don't see why we should explicitly forbid `where field` vs handling it more gracefully

**Comment by rw-access** [comment]
I'm not sure this is actually possible to enforce grammatically. And I don't see why we should explicitly forbid `where field` vs handling it more gracefully

**Comment by costin** [comment]
The issue is not about enforcing this in the grammar rather about identifying this pattern and unwrapping the shorter version inside the AST. So `where bool_field` is interpreted as `where bool_field == true`.
That is, the behavior for the user will not change.
