### ISSUE TITLE
Restore Elasticsearch from snapshot, doesn't respect attributes in config

### ISSUE THREAD

**Issue by tabbi** [elastic/elasticsearch#63717]
**Elasticsearch version** (`7.4.0`):

**Plugins installed**: []

**JVM version** (`1.8.0`):

**OS version** (CentOS 7.8):

**Description of the problem including expected versus actual behavior**:
I have a 3 node ElasticSearch (V.7.4.0) Cluster, and i want to move data to new Elasticsearch cluster containing 5 nodes (3 master eligible, and 2 data nodes)
here is my old cluster overview
 
- ES01 (master,data) 
- ES02 (master,data)
- ES03 (master,data)

and here is my new cluster overview 

Zone1 (e,g Rack1 in my physical DC)
- ES01 (Master,data,)
- ES02 (DATA)

Zone2
- ES03 (Master,data)
- ES04 (DATA)

Zone3
- ES05 (Master-only)

so as you can see the main difference from old cluster, is added Racks, so respect of this, i've added following lines in my elasticsearch.yml file

ES01.yml
```
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
node.attr.zone: zone1
```

ES02.yml

```
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
node.attr.zone: zone1 
```

ES03.yml

```
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
node.attr.zone: zone2

```

ES04.yml

```
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
node.attr.zone: zone2

```

ES05.yml

```
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
```

so when i'm restoring data from snapshot from old (3 node cluster without any attributes) to new (5 node cluster with attributes, some primary and replica shards allocated on the same Zone
```

ip-kim-info                             0  p STARTED    126  79.3kb 10.0.87.209 elastic-03
ip-kim-info                             0  r STARTED    126  79.3kb 10.0.87.208 elastic-02
notification                            0  r STARTED 580957   1.7gb 10.0.87.209 elastic-03
notification                            0  p STARTED 580957   1.7gb 10.0.87.208 elastic-02

```
as you can see above the notification and ip-kim-info shards are allocated on the nodes which composed in the same Zone

**Comment by original-brownbear** [comment]
@tabbi 

I'm not sure I understand this:

```
ip-kim-info                             0  p STARTED    126  79.3kb 10.0.87.209 elastic-03
ip-kim-info                             0  r STARTED    126  79.3kb 10.0.87.208 elastic-02
```

elastic-03 is in `zone2` according to your yml snippet and elastic-02 is in `zone1` so they're not in the same zone are they?

**Comment by tabbi** [comment]
@original-brownbear you bro fu*k that, i'm dumb, sorry, i'm really sorry
