### ISSUE TITLE
Geospatial team: Option to return collection of split objects(lines/polygons) crossing dateline.

### ISSUE THREAD

**Issue by vmanohar1** [elastic/elasticsearch#63739]
* Opening this feature request based on discussion with Nicholas Knize during the conference yesterday.
   * Currently, if a polygon crosses dateline (antimeridian) and if that polygon is used to find geo point locations (from an existing index) inside that polygon, my understanding is that elastic engine will split that polygon at the date line, do appropriate computation using BKD tree and then return the geo point locations matching the criteria in response.
   * So the elastic engine already knows how to do polygon splitting at the dateline. Given that, why not create a new feature to allow elastic queries to request splitting of polygon(s)/Line(s) at the dateline and in response get a collection of split objects [lines/polygons] at the dateline?
* This feature can be useful to any mapping platform that uses web mercator projections when displaying any geo locations on map.

**Comment by iverase** [comment]
I am wondering if the fields API should return the split geometry? cc @romseygeek

**Comment by vmanohar1** [comment]
> I am wondering if the fields API should return the split geometry? cc @romseygeek

* API should have that option in addition to returning results of the geospatial query.
