### ISSUE TITLE
docs for upgrading with optimistic concurrency control

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#63747]
I think it'd be cool if we had docs describing the process of upgrading from the cluster that used the old style "versioning" for optimistic concurrency control to one that uses `if_seq_no` and `if_primary_term`. Is it as simple as continuing to use the old optimistic concurrency control, upgrading the cluster, and then switching to the new one? What would that look like?

**Comment by sribharghava** [comment]
thanks @nik9000 for the awesome help in the AMA booth. 
It would be great if we have such a documentation explaining how to do such an upgrade if possible with no data loss/corruption and zero downtime.

**Comment by henningandersen** [comment]
We discussed this today and we think the following is the easiest route. Note that 6.8 supports both version and sequence number based optimistic concurrency control, whereas 7.0+ only supports sequence number based optimistic concurrency control.

1. Upgrade to 6.8
2. Ensure all relevant indexes created prior to 6.0 are reindex'ed to ensure they have sequence numbers.
3. Change application code to use sequence number based optimistic concurrency control.
4. Upgrade to 7+

**Comment by sribharghava** [comment]
Thanks @henningandersen for the update. That makes sense.
We had a look at this last week and approached this in a slight different way. We modified our application layer to use external versioning for the OCC by incrementing the version by one before writing to the ES. As external versioning is supported in 7.x, this prevented any API changes in our application layer for the upgrade allowing us to focus on only the upgrade and not the OCC for the time being. We'll slowly phase out the external versioning way of doing the OCC and move to sequence numbers after the upgrade or may be continue with the external versioning way of doing the OCC. This also avoids 2 upgrade paths(to 6.8 and then to 7.x) and  keeps the OCC concerns separate. Let me know if that makes sense.

**Comment by henningandersen** [comment]
@sribharghava one reason we chose the approach listed above is that it requires no downtime (rolling upgrades) and does not rely on every update/index request for existing data to use OCC.

If you upgraded from a version prior to 6.7 to 7.x using a full cluster restart but wanted to keep OCC concerns separate, your approach makes sense. Notice that you need to use OCC for every update/index request of existing data for this to work correctly.

**Comment by sribharghava** [comment]
yeah, that makes sense. Our case is a little different though. We planned for a no downtime upgrade using a blue green deployment strategy with dual writes to both old and the new 7.x clusters and reindexing. We are currently on 1.4 and with so many breaking changes in the API and the functionality rolling upgrades is not an easy option for us.

**Comment by sribharghava** [comment]
Thanks for the help on this. If this whttps://github.com/elastic/elasticsearch/issues/63747#issuecomment-713616402 makes into the documentation somewhere that would be helpful to people I believe

**Comment by jrodewig** [comment]
Closed via #64550
