### ISSUE TITLE
Scripted metric broken for transport client < 7.8.0

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#63760]
If you use a version of the transport client before 7.8.0 you bump into this code:
```

        if (out.getVersion().before(Version.V_7_8_0)) {
            if (aggregations.size() > 0) {
                /*
                 * I *believe* that this situation can only happen in cross
                 * cluster search right now. Thus the message. But computers
                 * are hard. 
                 */
                throw new IllegalArgumentException("scripted_metric doesn't support cross cluster search until 7.8.0");
            }
            out.writeGenericValue(aggregations.get(0));
        } else {
            out.writeCollection(aggregations, StreamOutput::writeGenericValue);
        }
```

Because your transport client is before 7.8.0 you end up in the top branch of the if statement. Then, because the transport client receives fully reduced aggregations, `aggregation.size()` is exactly `1`. So you hit my exception about not supporting CCS. But of course, you aren't using CCS. Computers really are hard. The problem here is that we do `size > 0` instead of `size > 1`. If there is one agg we could totally send that value to the older transport client. I just goofed. And I didn't add a test for this case.

**Comment by lipusz** [comment]
Thanks for looking into this. On our side we are [fixing](https://issues.liferay.com/browse/LPS-120240)
it by bumping the client version to 7.9.0, however I thought you may want to fix this so I reported through your support.

Let me know if you need further information from us.
