### ISSUE TITLE
7.9 documentation for Configuring elasticsearch for SAML references the deprecated sp.acs endpoint.

### ISSUE THREAD

**Issue by travisestill** [elastic/elasticsearch#63763]
**Details:**
The documentation found at https://www.elastic.co/guide/en/elasticsearch/reference/current/saml-guide-authentication.html states that the sp.acs value should be "https://kibana.example.com/api/security/v1/saml"

However, this endpoint was deprecated in 7.6 in favor of "https://kibana.example.com/api/security/saml/callback".
See: https://github.com/elastic/elasticsearch/blob/master/x-pack/docs/en/security/authentication/saml-guide.asciidoc#create-a-saml-realm

This causes confusion as to what the setting should be defined as. When using the saml-elasticsearch-metadata script, the generated metadata binds to the location using the ../saml/callback. When these don't match because the realm settings are configured with the deprecated endpoint, it results in an authentication warning similar to:

```
Authentication to realm <realm_name> failed - Provided SAML response is not valid for realm <realm_name> (Caused by ElasticsearchSecurityException[SAML response <string> is for destination <KIBANA_URL>/api/security/v1/saml but this realm uses <KIBANA_URL>/api/security/saml/callback])
```

**Comment by tvernum** [comment]
>This causes confusion as to what the setting should be defined as. When using the saml-elasticsearch-metadata script, the generated metadata binds to the location using the ../saml/callback

I don't follow what you're describing here. The `elasticsearch-saml-metadata` command uses whatever is configured on the realm, it makes no assumptions about what those values should be, it simply relies on whatever is configured.

**Comment by travisestill** [comment]
Hey @tvernum,

I didn't fully understand that part about the saml-elasticsearch-metadata script. That should have read that if the customer follows the details in github, then later references the official docs while troubleshooting, they might end up changing to the old endpoint unnecessarily as was the case with the customer. 

But @jkakavas is spot on with his description as far as the root of the issue.

**Comment by lockewritesdocs** [comment]
This issue was fixed in the 7.x docs, so I'm marking this issue as closed.
