### ISSUE TITLE
Add KeyUsage, ExtendedKeyUsage, CipherSuite & Protocol to SSL diagnostics

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#63784]
Per https://discuss.elastic.co/t/ldaps-and-chain-of-certificates/250724 it's possible to get an SSL failure & diagnostic when the cipher requires certain key usage that is not permitted by the certificate.

To assist in such diagnostics, it would be of assistance to print out the ceritficate's KeyUsage and the session's Cipher suite in the message.
While we're doing that, the cert's ExtendedKeyUsage and session Protocol are probably worth including as well.

**Comment by AGZain** [comment]
I'd like to start contributing to this issue. 
Any hints on which part of the code I should start with, for this issue?

**Comment by Moe82** [comment]
Hi, @tvernum . I'd like to work on this issue. Can you please provide a format for how you want the 4 new strings to appear?
Would something basic like this work:
message.append(format("Key Usage: %s", X509Certificate.getKeyUsage()));

**Comment by tvernum** [comment]
@AGZain , @Moe82 you'll need to coordinate between yourselves as to who is looking at this.

The class that needs to change is [SslDiagnostics](https://github.com/elastic/elasticsearch/blob/master/libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/SslDiagnostics.java) but I have looked at this in enough detail to know exactly how we should represent these value, or where we should slot them in.

**Comment by Moe82** [comment]
I assumed the other user was no longer interested. @AGZain , let me know if you still want to work on it.

**Comment by Moe82** [comment]
Ok, seems like AGZain is no longer interested. I'll pick it up.

**Comment by sindhusp** [comment]
Hi @Moe82, are you working on this?

**Comment by Moe82** [comment]
hi @sindhusp , not at the moment. Was planning on resuming mid December after my school semester ends. But feel free to work on it. If you can't figure it out by then, please let me know.

**Comment by sindhusp** [comment]
@tvernum Can you please review my PR for this issue? 
Also, I signed the Contributor Agreement successfully, but that check is failing on my PR. Any thoughts on what I could do to verify the signing?
