### ISSUE TITLE
EQL: Error responses do not include `caused_by` fields

### ISSUE THREAD

**Issue by rylnd** [elastic/elasticsearch#63855]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10BC2

When error responses are returned from EQL searches, they lack the `error.caused_by.type` and `error.caused_by.reason` fields that appear to be standard across elasticsearch error responses.

In practice, this means that the default [response error presentation](https://github.com/elastic/kibana/pull/70404) in kibana does not provide useful EQL error information to the user, despite it being present elsewhere in the response.

Example EQL error response:
<img width="678" alt="DevTools_-_d4949281e4954bb089dbb8f7ac5b2af1_europe-west1_gcp_cloud_es_io_9243_app_security_detections_rules_id_33fbcc07-372b-4c49-9b4c-1385437302ec_sourcerer__default______timerange__global__linkTo___timeline__timerange__from__272020-10-16T" src="https://user-images.githubusercontent.com/657252/96327420-0c28a700-0fff-11eb-8040-ec383a200b23.png">

Example elasticsearch error response (taken from https://github.com/elastic/kibana/issues/70352): ![](https://user-images.githubusercontent.com/908371/86163372-fe3d2d80-bac4-11ea-86ba-9b51899b0e38.png)

**Comment by costin** [comment]
EQL exceptions are Elasticsearch exceptions (both semantically and in terms of hierarchy) however that doesn't mean they should contain a `caused_by`. That is used when there's an underlying exception - in your example the date_histogram failed (top exception) because there was a parsing exception related to the timezone.
The verification exception in EQL doesn't have an underlying exception - it is the root of the problem and there's no wrapping of it. You could argue that the style is different however that's on purpose as we're trying to report as many failures as possible for a given query inside the same exception.

**Comment by rylnd** [comment]
@costin thanks for the response, that's great information! It sounds like the logic in kibana could be more correct, then.

I wasn't able to find any current documentation on the structure of these error responses, however I tracked down what looks to be the [original PR for standardizing errors](https://github.com/elastic/elasticsearch/pull/10643), which then lead to this [subsequent PR in kibana](https://github.com/elastic/kibana/pull/5176). 

Just a few quick clarifications, then, to assist in creating the kibana issue: 

* Is there documentation for the error response fields and their meaning?
* Are `error.reason` and `error.type` always present?
  * They _seem_ to always represent the most useful error message, but I'm cautious since that [first kibana PR](https://github.com/elastic/kibana/pull/5176) instead focused on `error.root_cause`
* If not, is there an error field that will always be present, or an algorithm by which we can find the best information for the user?

**Comment by astefan** [comment]
@rylnd I don't think the response message format is documented, or at least I couldn't find this info. Maybe a question better asked to the wider Elasticsearch team. I see a tangential mentioning in the "Common options" docs page: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-error-options.

Regarding the structure of the error message, an ElasticsearchException (which we use as base class for our eql exceptions) can output a detailed error message or a trimmed down one, depending on [`http.detailed_errors.enabled` parameter setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) (code [here](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L557)). 

Looking at the code in ElasticsearchException:
- if `detailed` is `true` (the default), then the error message has an `error` object in the final JSON structure with potentially multiple `root_cause`s as an array of JSON objects. Each root_cause exception should have a [`type`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L332) and a [`reason`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L333).
- if `detailed` is `false` then just the `error` element is present with the name of the exception

**Comment by rylnd** [comment]
Thanks for the help here! I've opened https://github.com/elastic/kibana/issues/81857 to address this on the kibana side 👍

**Comment by astefan** [comment]
@rylnd heads up, I'm about to merge in 7.10 the following backport https://github.com/elastic/elasticsearch/pull/64267 that might affect the error type displayed in some scenarios. The original issue is here https://github.com/elastic/elasticsearch/issues/63529.
The PR itself contains some tests that show the way the error message will look like after the merge is done.
