### ISSUE TITLE
EQL Profile API

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elasticsearch#63857]
It would be great to have a profile API for EQL searches, similar to [the Profile API available in a regular search request](https://www.elastic.co/guide/en/elasticsearch//reference/current/search-profile.html).

I'm not entirely sure what a EQL search profile should return. What would help me at least, is timings and request bodies of the underlying ES requests.

**Comment by wchaparro** [comment]
Superceded by ES|QL
