### ISSUE TITLE
security.clear_api_key_cache does not document all routes.

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#63885]
The tests for `security.clear_api_key_cache` seems to indicate that `ids` is optional by allowing to pass an empty string `""` for ids.

https://github.com/elastic/elasticsearch/blob/7.10/x-pack/plugin/src/test/resources/rest-api-spec/test/api_key/10_basic.yml#L197-L198

And therefor the tests assumes whatever builds the url will happily build `/_security/api_key//_clear_cache`.  

This is true for the java test runner but this is not true for the more strict clients. 

The spec and the `RestAction` need to explictly define `/_security/api_key/_clear_cache` as a valid route to clear all API's.

After a quick peek I suspect the same is true for several other security related (`clear_*`) API's

**Comment by ywangd** [comment]
Hi @Mpdreamz as you have noticed, the double slash pattern was added there following existing pattern in the code. @albertzaharovits and I did have brief discussion about adding support for the single slash version. But we haven't come to a conclusion yet. Let me discuss this with the team and come back to you.
