### ISSUE TITLE
[ML] Notifications index mappings don't have ignore_above on message.raw multi-field

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#63888]
The mappings for the `.ml-notifications*` and `.transform-notifications*` indices contain this:

```
        "message": {
          "type": "text",
          "fields": {
            "raw": {
              "type": "keyword"
            }
          }
        },
```

Because there is no `ignore_above` on the `keyword` multi-field, we are vulnerable to errors like `Document contains at least one immense term in field="message.raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms.`

According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html):

> The `ignore_above` setting can be updated on existing fields using the [PUT mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html).

So in this case we might be able to correct the mappings in a minor release rather than having to wait for the next major.

We can certainly update our notification index template mappings so that future notifications indices do not suffer from this problem.  UPDATE this was implemented in #64455

**Comment by davidkyle** [comment]
Closed by #64570
