### ISSUE TITLE
JdbcPreparedStatementTests#testSettingSqlDateValues failed with a 1-hour discrepancy

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#63924]
**Build scan**:

https://gradle-enterprise.elastic.co/s/dxvxj6pzgjjua/console-log?task=:x-pack:plugin:sql:jdbc:test

**Repro line**:

`REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:jdbc:test' --tests "org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests.testSettingSqlDateValues" -Dtests.seed=3218B3C41ADF034E -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=AST -Druntime.java=8`

**Reproduces locally?**:

My attempt failed for unrelated reasons.

**Applicable branches**:

7.9

**Failure history**:

This is the only failure of this test in the last 90 days. Possibly related to https://github.com/elastic/elasticsearch/issues/50035, noting that this is using JDK8 and that the expected and actual values are off by 3600000ms == 1 hour.

**Failure excerpt**:

```
org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests > testSettingSqlDateValues FAILED |  
-- | --
  | java.lang.AssertionError: expected:<258340161203490066> but was:<258340161199890066> |  
  | at __randomizedtesting.SeedInfo.seed([3218B3C41ADF034E:C2E89BAB44A3A640]:0) |  
  | at org.junit.Assert.fail(Assert.java:88) |  
  | at org.junit.Assert.failNotEquals(Assert.java:834) |  
  | at org.junit.Assert.assertEquals(Assert.java:645) |  
  | at org.junit.Assert.assertEquals(Assert.java:631) |  
  | at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests.testSettingSqlDateValues(JdbcPreparedStatementTests.java:440) |  
```

**Comment by bpintea** [comment]
> @bpintea I've assigned you this one, as well, since you also own the older one.

👍 
(I guess the intended one was #71704.)

**Comment by craigtaverner** [comment]
I noticed this was not muted in main (8.15), nor back in 7.17, and the original report was for 7.9. I think this issue should just be closed if this is not failing in supported versions.

**Comment by craigtaverner** [comment]
No comments mention failures since 7.9, and since it is not muted, we should close it.
