### ISSUE TITLE
AsyncSearchActionIT.testRetryVersionConflict fails

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#63948]
**Build scan**:

https://gradle-enterprise.elastic.co/s/xbsokeqogmz4e/console-log?task=:x-pack:plugin:async-search:internalClusterTest

**Repro line**:

`REPRODUCE WITH: ./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRetryVersionConflict" -Dtests.seed=69CB029E447B660 -Dtests.security.manager=true -Dtests.locale=be -Dtests.timezone=Asia/Kabul -Druntime.java=11`

**Reproduces locally?**:

Not after a handful of iterations

**Applicable branches**:

`master`

**Failure history**:

[Three failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testRetryVersionConflict),sort:!(process.time-start,desc))) on `master` over the last couple of days.

This test was added recently in #63652

**Failure excerpt**:

```

org.elasticsearch.xpack.search.AsyncSearchActionIT > testRetryVersionConflict FAILED |  
-- | --
  | java.lang.AssertionError: [java.util.concurrent.ExecutionException: org.elasticsearch.transport.RemoteTransportException: [node_s0][127.0.0.1:43365][indices:data/write/update[s]]] |  
  | at __randomizedtesting.SeedInfo.seed([69CB029E447B660:1F5DBEBF72D58D61]:0) |  
  | at org.junit.Assert.fail(Assert.java:88) |  
  | at org.junit.Assert.assertTrue(Assert.java:41) |  
  | at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRetryVersionConflict(AsyncSearchActionIT.java:456) |  
```

**Comment by davidkyle** [comment]
Also failing on 7.9 https://gradle-enterprise.elastic.co/s/xvofuzl46ajb6

This one contains the nested exception:
```
java.lang.AssertionError: [java.util.concurrent.ExecutionException: RemoteTransportException[[node_s1][127.0.0.1:46393][indices:data/read/async_search/get]]; 
nested: RemoteTransportException[[node_s1][127.0.0.1:46393][indices:data/write/update[s]]]; 
nested: VersionConflictEngineException[[4IS9k-ppQv-tZUSVK5duPQ]: version conflict, required seqNo [22], primary term [1]. current document has seqNo [23] and primary term [1]];]
	at __randomizedtesting.SeedInfo.seed([1A6E99799614A613:3AF97EF00869D12]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRetryVersionConflict(AsyncSearchActionIT.java:451)
```

**Comment by ywangd** [comment]
Another one on 7.x: https://gradle-enterprise.elastic.co/s/e4mdifcbsntqq

Not reproducible locally.

The exception is similar to above:

```
2> java.lang.AssertionError: [java.util.concurrent.ExecutionException: RemoteTransportException[[node_s1][127.0.0.1:39801][indices:data/read/async_search/get]]; nested: RemoteTransportException[[node_s0][127.0.0.1:42103][indices:data/read/async_search/get]]; nested: RemoteTransportException[[node_s1][127.0.0.1:39801][indices:data/write/update[s]]]; nested: VersionConflictEngineException[[ia_wQNGPRKGbkM-jlsfMAA]: version conflict, required seqNo [17], primary term [1]. current document has seqNo [18] and primary term [1]];] |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([5DE656C6DFF469C8:44275850496652C9]:0) |  
  | at org.junit.Assert.fail(Assert.java:88) |  
  | at org.junit.Assert.assertTrue(Assert.java:41) |  
  | at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRetryVersionConflict(AsyncSearchActionIT.java:453)
```

**Comment by mayya-sharipova** [comment]
Another failure on master PR: https://gradle-enterprise.elastic.co/s/3feqp5dosgpwo

Doesn't reproduce for me.

```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRetryVersionConflict" -Dtests.seed=ECA507FC331A242 -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=America/Juneau -Druntime.java=11
```


Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [GYbwbtUpQwaVs1VHs0QcvA]: version conflict, required seqNo [18], primary term [1]. current document has seqNo [19] and primary term [1]

**Comment by danielmitterdorfer** [comment]
another instance in https://gradle-enterprise.elastic.co/s/f33z6uu22dh2e.

I'll mute the test on `master`, `7.x` and `7.10`.
