### ISSUE TITLE
Document how to update existing TLS certificates in a cluster

### ISSUE THREAD

**Issue by adoerrES** [elastic/elasticsearch#63953]
Users may ask what the correct steps are to update existing TLS certificates in an Elasticsearch, for example: 

- does it require a full-cluster or rolling restart?
- can certificates just be updated in place?
- does the process change if Certificate Authority (CA) certificates are updated in addition to the individual node certificates?

Some of this guidance is captured in the following discussion below, which details how to update certificates when only updating the node certs. This could also be expanded to include steps for when the CA chain is updated, which is alluded to requiring different steps in the post but not really addressed:

https://discuss.elastic.co/t/updating-node-certificate-on-existing-cluster/243413

This guidance could be captured in proper documentation, as updating the certificates is a slightly different process than creating and applying certificates for the first time, which is already documented.

**Comment by recurrence** [comment]
Is there no documentation "anywhere" for CA cert renewal?

**Comment by lockewritesdocs** [comment]
@recurrence, we have some internal documentation for this process but nothing external at the moment that is ready for publication. We know that this is a challenging issue for users and are working diligently to incorporate this information into our public documentation.

**Comment by lockewritesdocs** [comment]
> Is there no documentation "anywhere" for CA cert renewal?

@recurrence, we just published documentation for [updating TLS certificates](https://www.elastic.co/guide/en/elasticsearch/reference/current/update-node-certs.html). Please let us know if this information is helpful!

**Comment by tyler-ground** [comment]
Hi @lockewritesdocs , I saw and followed the PR :).   I ended up restarting the cluster with new certs.  The steps make sense to me (potentially even more verbose than needed)!

**Comment by recurrence** [comment]
Hi @lockewritesdocs , I saw and followed the PR :). I ended up restarting the cluster with new certs. The steps make sense to me (potentially even more verbose than needed)!
