### ISSUE TITLE
Explore making RequestOptions optional in HLRC requests

### ISSUE THREAD

**Issue by Charele** [elastic/elasticsearch#63964]
Every time we use RHLC client,
for example,
index(IndexRequest indexRequest, RequestOptions options)
I must explictly input the 'options',
Always I use "RequestOptions.DEFAULT".

In the org.elasticsearch.client.Request class, its defualt value is this RequestOptions.DEFAULT,
so I think it's unnecessary.

Can we provide a simple version without the 'option' parameter in RHLC?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
