### ISSUE TITLE
Maybe memory leak in search.SearchService

### ISSUE THREAD

**Issue by arielzach** [elastic/elasticsearch#64028]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8

**Plugins installed**: []

**JVM version** (`java -version`): 14.0.1

**OS version** (`uname -a` if on a Unix-like system): 4.14.186-110.268.amzn1.x86_64 #1 SMP Tue Jul 14 02:57:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (docker.elastic.co/elasticsearch/elasticsearch:7.8.0)

**Description of the problem including expected versus actual behavior**:

Continuously growing memory usage eventually leading to periodically FullGC result in Cluster not available. All nodes have 64G physical memory，32G JVM Heap, 8 cores, 1 index, 32 shards, 2 replicas.

The problem is similar to the one presented here: https://github.com/elastic/elasticsearch/issues/57400

Previously we had a 6.8 cluster with exactly the same configuration (hardware and ES config) and we did not have this problem.

I just dump the heap and analysis the heap with MAT

![image](https://user-images.githubusercontent.com/64101789/96801000-0820ce80-13dd-11eb-81b0-ea10ea1b8e72.png)
![image](https://user-images.githubusercontent.com/64101789/96801050-238bd980-13dd-11eb-8427-d03b09cd71ca.png)
![image](https://user-images.githubusercontent.com/64101789/96801070-2dadd800-13dd-11eb-9688-10170bb431f0.png)
![image](https://user-images.githubusercontent.com/64101789/96801083-37cfd680-13dd-11eb-8568-b90870820407.png)
![image](https://user-images.githubusercontent.com/64101789/96801176-677ede80-13dd-11eb-9e90-fea925d0560d.png)

**Comment by dnhatn** [comment]
@arielzach Thanks for reporting the issue. Can you share the heap dump with us privately?

**Comment by arielzach** [comment]
> @arielzach Thanks for reporting the issue. Can you share the heap dump with us privately?

Hi @dnhatn ,

Unfortunately I can't pass the dump, tell me what you need to see.

**Comment by arielzach** [comment]
I can confirm that this also happens in version 7.9.2

**Comment by dnhatn** [comment]
Hi @arielzach,

Do you use [_scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html)? And, do you [clear](https://www.elastic.co/guide/en/elasticsearch/reference/current/clear-scroll-api.html) them after using?

> Unfortunately I can't pass the dump, tell me what you need to see.

Ok, can you share these?

- Number of search contexts in `SearchService.activeContexts`
- `keepAlive`, `lastAccessTime`, and `scrollContext` of these search contexts

**Comment by arielzach** [comment]
We use **_scroll** but we only use **clear** when we have an error.

SearchService.activeContexts: 300
keepAlive: 5m

I don't know where to look for these values: lastAccessTime and scrollContext

![image](https://user-images.githubusercontent.com/64101789/97180947-7c5ec780-1779-11eb-90b3-e51701f814ae.png)

**Comment by dnhatn** [comment]
> We use _scroll but we only use clear when we have an error.

You also need to clear _scroll when you finish scrolling; otherwise, the scroll contexts will be there until its sessions are expired.

I don't think there is a memory leak here as all open search contexts are scroll contexts. I am closing this issue. Thanks very much for your interest in Elasticsearch.

**Comment by arielzach** [comment]
Why don't we have the same problem with version 6.8?
