### ISSUE TITLE
Switch back to AdoptOpenJDK for bundled jdk

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#64026]
We recently switched the bundled jdk back to Oracle, to maintain support for CentOS 6/OEL 6/RHEL 6, which was broken with jdk 15 of adoptopenjdk (https://github.com/AdoptOpenJDK/openjdk-build/issues/2097). While this worked to get jdk 15 working on those older platforms, this causes an issue with homebrew:

```
==> find /usr/local/Cellar/elasticsearch-full/7.9.3/libexec/jdk.app/Contents/Home/bin -type f -exec
Error: Failed changing dylib ID of /usr/local/Cellar/elasticsearch-full/7.9.3/libexec/jdk.app/Contents/Home/lib/libnet.dylib
  from @rpath/libnet.dylib
    to /usr/local/opt/elasticsearch-full/libexec/jdk.app/Contents/Home/lib/libnet.dylib
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formulae against it.
```

It is unclear how this issue can be fixed without recompiling the jdk. Fortunately the original issue upstream in AdoptOpenJDK has been fixed, and the 15.0.1 release should again support RHEL 6 and friends. We should switch back to adoptopenjdk, since we know it does not have this issue with homebrew.

**Comment by sweikenb** [comment]
Running into the same issue.

**Comment by aahlenst** [comment]
AdoptOpenJDK member here... 15.0.1 is out. Sorry for the problems with CentOS 6. We plan to keep glibc 2.12 support around as long as it is supported by OpenJDK and technically possible. If we ever cause problems again, please make some noise. I almost missed the issue reference.
