### ISSUE TITLE
[CI] buildBwcOssWindowsZip failing with Illegal char <	at index 32: C:\Users\jenkins\.java\java8\jre

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#64048]
**Build scan**:
https://gradle-enterprise.elastic.co/s/yddbfk6f6vync
https://gradle-enterprise.elastic.co/s/o3tj4pdqxxm5k
https://gradle-enterprise.elastic.co/s/uor75gsxbbepo

**Repro line**:

**Reproduces locally?**:

**Applicable branches**: master

**Failure history**:

**Failure excerpt**:
```

:distribution:bwc:staged:buildBwcOssWindowsZip FAILED |  
-- | --
  | build complete, generating: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\build\307.tar.bz2 |  
  |   |  
  | FAILURE: Build failed with an exception. |  
  |   |  
  | * What went wrong: |  
  | Execution failed for task ':distribution:bwc:staged:buildBwcOssWindowsZip'. |  
  | > Could not determine the details of Java installation in directory C:\Users\jenkins\.java\java8. |  
  | > Illegal char < |  
  | > at index 32: C:\Users\jenkins\.java\java8\jre

..........


Caused by: java.nio.file.InvalidPathException: Illegal char < |  
-- | --
  | > at index 32: C:\Users\jenkins\.java\java8\jre |  
  |   |  
  | at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) |  
  | at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) |  
  | at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) |  
  | at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) |  
  | at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) |  
  | at java.base/java.nio.file.Path.of(Path.java:147) |  
  | at java.base/java.nio.file.Paths.get(Paths.java:69) |  
  | at org.gradle.jvm.toolchain.internal.JavaInstallationProbe$ProbeResult.getJavaHome(JavaInstallationProbe.java:100) |  
  | at org.gradle.jvm.toolchain.internal.DefaultJavaInstallationRegistry$DefaultJavaInstallation.<init>(DefaultJavaInstallationRegistry.java:106) |  
  | at org.gradle.jvm.toolchain.internal.DefaultJavaInstallationRegistry$1.call(DefaultJavaInstallationRegistry.java:77)


```

**Comment by astefan** [comment]
https://gradle-enterprise.elastic.co/s/f2xtpz7a3wkqw
https://gradle-enterprise.elastic.co/s/uaintufnrctti
https://gradle-enterprise.elastic.co/s/fxruutc46xccy

**Comment by rjernst** [comment]
@breskeby Can you take a look? Seems like an issue with the java home we pull for building bwc distros, specifically on windows CI hosts.

**Comment by davidkyle** [comment]
Task `:distribution:bwc:maintenance:buildBwcOssZip` is also failing with the same error.

https://gradle-enterprise.elastic.co/s/fcbt2somad2wc
https://gradle-enterprise.elastic.co/s/rqr52nupnh4ea
https://gradle-enterprise.elastic.co/s/ccqw7gdgayylo

**Comment by breskeby** [comment]
should be fixed by moving back to gradle 6.6.1 on master and 7.x branches. I'll close this once all ci builds have passed

**Comment by jtibshirani** [comment]
I think another failure just popped up on CI: https://gradle-enterprise.elastic.co/s/evort4spsvx6g

**Comment by breskeby** [comment]
@jtibshirani that is a different issue you see which should also be fixed by now. I'm closing this as windows CI jobs are passing again after the gradle downgrade
