### ISSUE TITLE
Cannot update documents with date field with format "epoch_second", even if not updating the date field itself

### ISSUE THREAD

**Issue by shirkan** [elastic/elasticsearch#64050]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.1

**OS version** (`uname -a` if on a Unix-like system): Ubuntu

**Description of the problem including expected versus actual behavior**:
mapping is:
```
{
  "mapping": {
    "properties": {
      "condition": {
        "type": "text",
        "index": false
      },
      "name": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "rank": {
        "type": "double"
      },
      "timestamp": {
        "type": "date",
        "format": "epoch_second"
      }
    }
  }
}
```

Update request:
`POST shirkan_test/_update/test_id
{
  "doc": {
    "name": "shirkan"
  },
  "doc_as_upsert": true
}`

Error message:
`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse field [timestamp] of type [date] in document with id 'test_id'. Preview of field's value: '1.602505857664299E9'"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [timestamp] of type [date] in document with id 'test_id'. Preview of field's value: '1.602505857664299E9'",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "failed to parse date field [1.602505857664299E9] with format [epoch_second]",
      "caused_by": {
        "type": "date_time_parse_exception",
        "reason": "Failed to parse with all enclosed parsers"
      }
    }
  },
  "status": 400
}`

Changing `timestamp` format to `strict_date_optional_time_nanos` doesn't yield such an error and the upsert works well.

**Comment by rjernst** [comment]
@pgomulka Can you take a look?

**Comment by pgomulka** [comment]
@shirkan can you please send me the full reproduction steps ?
most importantly what was the document and the timestamp field when you created it?

**Comment by rjernst** [comment]
I'm not able to reproduce this issue. Given the lack of response, I'm going to close this. Please open a new issue with a reproduction if it occurs again.

**Comment by arthur-caillaud** [comment]
I am currently facing the same issue.

Date field is accepted at document creation but when performing an update the index yield a `date_time_parse_exception` even if I am not changing the date value in `update` payload.

@shirkan did you achieve to solve this issue ?

### Context informations

ElasticSearch engine version : 7.10

Currently indexed document
```json
{
    "createdDate": 1656482668350.6194
}
```

`update` query error
```
failed to parse field [createdDate] of type [date] in document with id 'file:localdisk:dfc0fb0d-55ba-4493-83c5-a206f24dbb28:8be31786bf050c69bd653fe7e208d595ab5658ddf8a9f59a0a995d759f89e774'.
Preview of field's value: '1.6564826683506194E12'
```

Index mapping
```
{
    "createdDate" : {
          "type" : "date",
          "format" : "epoch_millis"
    },
}
```

Other fields are omitted for simplicity.

**Comment by currents-abhishek** [comment]
To anyone facing this issue, we got around this using the following in the update
```
...
"script": {"source": "ctx._source.date = (long)ctx._source.date;"}
...
```

Ugly. But works.
