### ISSUE TITLE
[CI] SearchServiceTests testCreateSearchContextFailure failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#64055]
**Build scan**: https://gradle-enterprise.elastic.co/s/mb4fxdioop3sk

**Repro line**: `./gradlew ':server:test' --tests "org.elasticsearch.search.SearchServiceTests.testCreateSearchContextFailure" -Dtests.seed=3513A4B213D3E47A -Dtests.security.manager=true -Dtests.locale=ko -Dtests.timezone=Africa/Niamey -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: [this method failed in the past but the errors were different then](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.search.SearchServiceTests%22%20AND%20test:%22testCreateSearchContextFailure%22'),sort:!(time,desc)))

**Failure excerpt**:
```
2> java.lang.AssertionError: should have 2 store refs (IndexService + InternalEngine) expected:<2> but was:<4>
        at __randomizedtesting.SeedInfo.seed([3513A4B213D3E47A:D9C6D58E7791BD50]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.search.SearchServiceTests.testCreateSearchContextFailure(SearchServiceTests.java:911)
```

**Comment by dnhatn** [comment]
Closes in favor of https://github.com/elastic/elasticsearch/issues/64052
