### ISSUE TITLE
Add print tree for each of the Painless trees

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#64076]
Add a print tree phase for each of the ANTLR tree, user tree, and ir tree. The expected use for each of these is internal debugging. For the user and ir trees, decorations should be optionally printed as part of the tree.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
