### ISSUE TITLE
Slow results on date range query?

### ISSUE THREAD

**Issue by HarelM** [elastic/elasticsearch#64086]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.1

**Plugins installed**: none

**JVM version** (`java -version`): using docker, which ever is there...

**OS version** (`uname -a` if on a Unix-like system): docker image

**Description of the problem including expected versus actual behavior**:
I not sure this used to work faster, but I believe it was.
I expect date range query not to take so long but it take very long:
I have about 135K documents, and I'm querying the database to get updates in the last month and it takes about 20 seconds to get the answer back - which returns about 3K docs.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 Mapping is basically a geojson feature: https://github.com/IsraelHikingMap/Site/blob/e03617cb2f7cf71b0f5a7a79c40ffaa19eb89067/IsraelHiking.DataAccess/ElasticSearchGateway.cs#L430
Query: https://github.com/IsraelHikingMap/Site/blob/e03617cb2f7cf71b0f5a7a79c40ffaa19eb89067/IsraelHiking.DataAccess/ElasticSearchGateway.cs#L340
In theory, just insert 135K documents with different dates and test the performance of the above query in difference dates ranges.
I'm using a single node.
I've also tested the query when not returning the geometry with minimal effect so I don't think the issue is with the size of the data being returned.

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
The [discuss forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) is better suited for this kind of question. We reserve github for verified bugs and feature requests so I hope that you don't mind if I close this issue. Our nightly benchmarks didn't spot any regression so I suspect that the slowdown comes from your setup. It might be the number of docs that you paginate at once but you'd have to confirm with some numbers. If you open a topic in the [forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), please provide the size of the response as well as some outputs of the [`hot  threads` API ](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html#cluster-nodes-hot-threads-api-request) while the request is running.

**Comment by HarelM** [comment]
Thanks for the info and your detailed response.
I believe there's an issue here in terms of performance for the date range query, might not be a regression issue but a general not optimized performance. I have decided to do a workaround and to "page" the request from the client side in order to be able to better handle client side timeouts.
If you don't agree with my observation, that's totally fine, I trust that you know your system better than I do...

**Comment by jimczi** [comment]
There's something odd in your setup that makes the request run for 20s but I'd not blame the date range query without clear evidence. As I said, you should learn a lot by running the hot threads while the request is running on the node. If you cannot understand the output, don't hesitate to open a topic in the forum. Maybe there's a performance bug somewhere but the investigation may take time and we prefer the discuss forum to handle this kind of interaction until we find more details about the case.
