### ISSUE TITLE
Add a `interval_format` parameter to `date_histogram` aggregations

### ISSUE THREAD

**Issue by qraynaud** [elastic/elasticsearch#6408]
It would be very cool if we could give a format to create the interval instead of the simple multi value `interval` parameter.

Let's give some examples... A `days` interval could be the same as `'Y-M-d'` interval format.

So, what is this new parameter allowing? More complex aggregations! Like if I want to aggregate each element depending on which week day (`"interval_format": "e"`) it was created on. Or which month of the year (`"interval_format": "M"`).

I would love to have this! Right now I have to write ugly scripts and I don't even know how to handle timezones properly in those.

**Comment by jpountz** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/6580
