### ISSUE TITLE
Updating dense_vector field fails

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#64093]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.1

**Plugins installed**: []
-

**JVM version** (`java -version`):
Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system):
Elastic Cloud

**Description of the problem including expected versus actual behavior**:
An exception occurs when trying to update a `dense_vector` field.

Also worth noting that the exact same error occurs with `sparse_vector` as well.

**Steps to reproduce**:
1. First, create an index with a `dense_vector` field

```
PUT test
{
  "mappings": {
    "properties": {
      "dense": {
        "type": "dense_vector",
        "dims": 2
      }
    }
  }
}
```

2. Then, index a document in it

```
PUT test/_doc/1
{
  "dense": [ 1, 2 ]
}
```

3. When we try to update the `dense` field with a new vector, we get an error
```
POST /test/_doc/1/_update
{
  "dense": [ 2, 5 ]
}
```

Error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[2:3] [UpdateRequest] unknown field [dense]"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[2:3] [UpdateRequest] unknown field [dense]"
  },
  "status" : 400
}
```

4. However, updating via script works fine:

```
POST test/_doc/1/_update
{
      "script": {
        "source": "ctx._source.dense = params.vector",
        "params": {
          "vector": [3, 8]
        }
      } 
}
```
Result:
```
{
  "_index" : "test",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 4,
  "result" : "updated",
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "_seq_no" : 3,
  "_primary_term" : 1
}

```

**Comment by jimczi** [comment]
The [`update` API](elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) expects a `doc` or a `script` in the body so this has nothing to do with the `vector` field. 
The request should be:

```
{
    "doc": {
        "dense": [
            2,
            5
        ]
    }
}
```

**Comment by consulthys** [comment]
Sorry for the trouble 🤦‍♂️ my bad
