### ISSUE TITLE
Wrong documentation of pattern_replace token filter

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#64173]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.1
**Plugins installed**: []
None
**JVM version** (`java -version`):
11
**OS version** (`uname -a` if on a Unix-like system):
11.0.7.10.1
**Description of the problem including expected versus actual behavior**:
Docs of pattern_replace filter https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern_replace-tokenfilter.html  mentioned Regular expressions cannot be anchored to the beginning or end of a token, while it works, and looking at the code it seems docs might be wrong. Maybe its discourage to anchored to the beginning or end of a token due to performance reason, but it works totally fine.
**Steps to reproduce**:
Refer to https://stackoverflow.com/questions/64538891/anchor-token-replace-patterns-to-the-end-of-tokens question example.
**Analyze API request**

curl -XGET "localhost:9900/_analyze?pretty" -H 'Content-Type: application/json' -d'
{
  "tokenizer": "whitespace",
  "filter": [
    {
      "type": "pattern_replace",
      "pattern": "(dog)$",
      "replacement": "hot$1"
    }
  ],
  "text": "dog dogs"
}'

**And generated tokens**
{
  "tokens" : [
    {
      "token" : "hotdog",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "dogs",
      "start_offset" : 4,
      "end_offset" : 8,
      "type" : "word",
      "position" : 1
    }
  ]
}

As shown in the https://github.com/elastic/elasticsearch/blob/master/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/PatternReplaceTokenFilterFactory.java#L52 code, it doesn't have the special handling of the **end or beginning of the token**
Note: Pattern(hot) is anchored to the end of the `dog` token and `dog(s)` is not replaced because it doesn't end with `dog`.
**Provide logs (if relevant)**:
N/A

**Comment by amitmbm** [comment]
I already have the PR ready, and once triage will raise it.

**Comment by jrodewig** [comment]
@amitmbm Thanks for raising this. Please go ahead and open a PR. I'll be happy to review.

**Comment by amitmbm** [comment]
@jrodewig @polyfractal  thanks for your prompt response on this, I will soon raise the PR 👍

**Comment by amitmbm** [comment]
@jrodewig  here you go, please review my PR https://github.com/elastic/elasticsearch/pull/64189 related to this issue and let me know your review comments, and I would address them.
