### ISSUE TITLE
Allow fine-grained script settings

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#6418]
Would be good to globally disallow scripting based on the type of operation being done. 

In particular I want to prevent scripting on queries but allow scripting in update/index operations.

Or maybe just separate this by which thread pool it is running in?

Related to #5943

**Comment by s1monw** [comment]
I removed the blocker label here - it's not really a blocker...

**Comment by javanna** [comment]
I am looking into this. I think that the default should not just be `script.all: sandbox` otherwise groovy file scripts cannot be run by default, which is kinda annoying and breaks bw comp. To be honest I am leaning towards removing the `script.all` setting for simplicity in favour of explicit configuration of the three generic settings, which would have the following defaults:

```
script.file: enable
script.indexed: sandbox
script.dynamic: sandbox
```

Thoughts?

**Comment by clintongormley** [comment]
+1

**Comment by javanna** [comment]
As for the more generic settings, I am wondering about conflicts. Of course more specific settings take precedence. But which one takes precedence between conflicting script_type based setting and operation based setting?

Let's say we have:

```
script.dynamic: enable
script.search: disable
```

Should it get expanded to the following?

```
script.engine.groovy.indexed.update:  sandbox
script.engine.groovy.indexed.search: disable
script.engine.groovy.indexed.aggs: sandbox
script.engine.groovy.dynamic.update: enable
script.engine.groovy.dynamic.search: disable
script.engine.groovy.dynamic.aggs: enable
script.engine.groovy.file.update: sandbox
script.engine.groovy.file.search: disable
script.engine.groovy.file.aggs: sandbox
```

If so, it means that operation based settings take precedence over script_type based settings. Maybe it's obvious, but I thought it was worth to double check what folks think.

**Comment by clintongormley** [comment]
Yes, I think the order should be: lang > source > operation

**Comment by javanna** [comment]
Just noticed that `mustache` and `native` are treated as special scripting engines since they are considered safer than others. Turns out that currently we always considered them both enabled, even if dynamic scripting is completely off.

That means that our default settings should be different only for `mustache` and `native`, they would have everything enabled by default.

We could have a problem though with generic settings as they would end up affecting `mustache` and `native` too. Think of `script.dynamic` set to `false`. Should we still allow `mustache` and `native` scripts anyways, which would mean not applying those generic settings to them? But maybe make it possible to set their settings only through engine specific settings? Thoughts?

**Comment by rjernst** [comment]
`native` scripts are by definition not dynamic.  Why would these settings ever affect them?

**Comment by clintongormley** [comment]
> Think of script.dynamic set to false. Should we still allow mustache and native scripts anyways, which would mean not applying those generic settings to them? But maybe make it possible to set their settings only through engine specific settings? Thoughts?

Hmm... good point. Native scripts can't be defined dynamically anyway, so it's really just templating.  The default will be that dynamic mustache and expressions are on, but everything else is off.  So I think there is no real need to set `script.dynamic: false`.  So if somebody sets it, we'd do what they say and disable mustache and expressions too.

**Comment by dakrone** [comment]
If we do that, we also need to be extra sure to document that search templates will not work if dynamic scripting is disabled (just a reminder)

**Comment by javanna** [comment]
> native scripts are by definition not dynamic. Why would these settings ever affect them?

@rjernst good point. Weird, but the fact that native scripts are not dynamic is an implementation detail of the native engine. You execute the script as it was dynamic (providing its name as `script: my_script`), then the engine knows that what you provided is not a script but the identifier of a script that is already compiled somewhere...

> Native scripts can't be defined dynamically anyway, so it's really just templating.

@clintongormley right but as I described above native scripts end up being considered dynamic although they aren't. That means that unless we treat them as special scripts they won't be executable with defaults settings, as their engine is not declared "sandboxed". I think the notion of `file`, `indexed` and `dynamic` makes little sense in the context of `native` scripts, and we should have a special case for them, like we currently have [here](https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/script/ScriptService.java#L511). I wonder if these fine grained settings should even apply to native scripts. By default you have no native scripts available, and if you install any via plugin, you just want to be able to execute them. Does it ever make sense to disable native scripts, especially given that these settings are static? I am leaning towards taking them out of this loop and making them always enabled regardless of settings.

As for `mustache` scripts, they are a little bit different as their engine is declared "sandboxed", thus they would run with default settings. That said they would be affected by generic settings applied, which is acceptable as @clintongormley said, we will document it as @dakrone suggested. The only concern is that this behaviour breaks backwards compatibility as at the moment you can always execute mustache scripts...
