### ISSUE TITLE
Add configurable inter-node data transfer profiling

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#64187]
Currently the transport layer keeps track of incoming and outgoing bytes. However, this does not provide the granularity to investigate which actions are contributing to data usage. We should discuss adding a mechanism to either permanently or temporarily provide more granular tracking. 

One potential idea would be to add a dynamic setting which would enable tracking of a map->byte counter for incoming and outgoing request / response bytes. This data could be fetched from an API.

We need to discuss if we are interested in metric granularity from IP to IP. But I tend to think that might be an overload of data for elasticsearch and would be better solved by an external tool.

**Comment by tbrooks8** [comment]
We have decided that the first step here is to improve logging. I will open a PR soon to modify our tracer logging to include both compressed and uncompressed message sizes.

**Comment by original-brownbear** [comment]
@tbrooks8 think we still need to do anything here, now that we have better tracing available?

**Comment by DaveCTurner** [comment]
relates https://github.com/elastic/elasticsearch/issues/88151 (which I think still has merit)

**Comment by tbrooks8** [comment]
Closed as this targeted what David's linked issue covers.
