### ISSUE TITLE
TransformContinuousIT.testContinousEvents DateHistogramGroupByOtherTimeFieldIT failures

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#64192]
**Build scan**: gradle-enterprise.elastic.co/s/wenxxiji5twto

**Repro line**: gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" -Dtests.seed=5766C4F5BD7A09B -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Jamaica -Druntime.java=8 -Dtests.fips.enabled=true

**Reproduces locally?**: with `-Dtests.iters=50` it is sometimes reprodicible

**Applicable branches**: `7.x`(`7.11`), `master`

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.branch,test.failed-testcases),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%22continuous-date-histogram-pivot-other-timefield-test%22),sort:!(process.time-start,desc))

**Failure excerpt**:
```
16:33:20 org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT > testContinousEvents FAILED
16:33:20     java.lang.AssertionError: Error in test case [continuous-date-histogram-pivot-other-timefield-test].If you want to mute the test, please mute [org.elasticsearch.xpack.transform.integration.continuous.DateHistogramGroupByOtherTimeFieldIT] only, but _not_ [org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT] as a whole.
16:33:20         at __randomizedtesting.SeedInfo.seed([5766C4F5BD7A09B:3E401D54D1BC22CD]:0)
16:33:20         at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:267)
16:33:20 
16:33:20         Caused by:
16:33:20         java.lang.AssertionError: Ingest run: 9 did not match max run: 7, iteration: 9
16:33:20         Expected: is a value less than or equal to <1>
16:33:20              but: <2> was greater than <1>
16:33:20             at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
16:33:20             at org.junit.Assert.assertThat(Assert.java:956)
16:33:20             at org.elasticsearch.xpack.transform.integration.continuous.DateHistogramGroupByOtherTimeFieldIT.assertResultsGroupByDateHistogramAndTerms(DateHistogramGroupByOtherTimeFieldIT.java:211)
16:33:20             at org.elasticsearch.xpack.transform.integration.continuous.DateHistogramGroupByOtherTimeFieldIT.testIteration(DateHistogramGroupByOtherTimeFieldIT.java:108)
16:33:20             at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:258)
```

**First look**:

This seems to be a problem in the test itself, probably related to timing, that's why it is only reproducible with `-Dtests.iters`. Time is the only component not part of randomization.

The failure asserts for an optimization expected to be applied. Even if this turn out to be a problem in the product it is benign as no data corruption is happening here. It is only about "unexpected longer runtime".

**Comment by jbaiera** [comment]
Had a couple more failures of this test today: 

https://gradle-enterprise.elastic.co/s/z73tyatcbz5dy
https://gradle-enterprise.elastic.co/s/x3lauci63pvny

**Comment by imotov** [comment]
Failed twice today. The latest failure is https://gradle-enterprise.elastic.co/s/paya6uib3y7aa
