### ISSUE TITLE
No index name in error message with ignore_unavailable=true and allow_no_indices=false

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#64197]
Tested in master the following `_search` request `/inexistent1,inexistent2/_search?allow_no_indices=false&ignore_unavailable=true`.
Which gives
```
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index [null]",
                "resource.type": "index_expression",
                "resource.id": [
                    "inexistent1",
                    "inexistent2"
                ]
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index [null]",
        "resource.type": "index_expression",
        "resource.id": [
            "inexistent1",
            "inexistent2"
        ]
    },
    "status": 404
}
```

It is strange to see the reason as `"reason": "no such index [null]"` where there is a list of patterns/resources that cannot be resolved into concrete indices. Code-wise, this INFE seems to come from `IndexNameExpressionResolver:303`.

**Comment by vamuzumd** [comment]
@astefan, I was interested in fixing this issue, would it be okay to return the reason as "no such index [inexistent1, inexistent2]"?

**Comment by cbuescher** [comment]
Just tried to repro, this seems to be working okay now on 8.4.1, I also went back to 8.0.0 and 7.7.16 and both versions also give me:

```
 "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [[inexistent1, inexistent2]]",
        "index_uuid" : "_na_",
        "index" : "[inexistent1, inexistent2]"
      }
    ]
```

which I think is what was expected here. Will close this issue for that reason.
