### ISSUE TITLE
CachedBlobContainerIndexInputTests.testRandomReads failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#64215]
**Build scan**: https://gradle-enterprise.elastic.co/s/tiqw5pjr4tiwk

**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads" -Dtests.seed=9EFCEB28234D764F -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Pacific/Auckland -Druntime.java=8
```

**Reproduces locally?**:
No.

**Applicable branches**:

At least 7.x, that is where it failed on #64160 

**Failure history**:

Looks like it only failed [once](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testRandomReads),sort:!(process.time-start,desc))), though there is also a failure of the test from September 3rd (looks like an unrelated failure).

**Failure excerpt**:

```
java.lang.AssertionError: All bytes should have been read from source	
Expected: <20522L>	
     but: was <20115L>
     at __randomizedtesting.SeedInfo.seed([9EFCEB28234D764F:ABFE49DBC9E1D265]:0)
     at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
     at org.junit.Assert.assertThat(Assert.java:956)
     at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads(CachedBlobContainerIndexInputTests.java:150)
```

**Comment by original-brownbear** [comment]
This also failed once for me locally on `master`.
