### ISSUE TITLE
Incorrect type check in SQL API

### ISSUE THREAD

**Issue by chatumoh** [elastic/elasticsearch#64238]
I am using elastic v7.5.2  I have added a field say **custNum** of type long in index mapping for an Index **A**. 
Under Index patterns, the Field type is shown as Number.

I queried the same index **A** using SQL API with multiple values(starting with values in integer range) for **custNum** field within SQL IN clause i.e. **SELECT * FROM A WHERE custNum in (2997,299738,299742,3000270011,29975)**

i got below exception, though the type of **custNum** field is long

     {
        "type": "sql_illegal_argument_exception",
        "reason": "[3000270011] out of [integer] range"
      }

If i query with 3000270011 alone or 3000270011 being first number in list  i.e. **SELECT * FROM A WHERE custNum in (3000270011,2997,299738,299742,29975)**. the query returns results successfully.

It seems the SQL parsing selecting the type based on first element in list but not honoring the type defined for the field in index mapping. 

**Type check should be based on defined mapping, if present.**

**Comment by matriv** [comment]
@palesz Please check if this has been resolved with #63483 
Before that the type was determined by the first value in the list instead of the field type at the left of the `IN` operator.

**Comment by palesz** [comment]
This was indeed fixed in #63483 , but added a couple of test cases to cover this particular error too.

**Comment by palesz** [comment]
I am closing this issue. The fix is part of the #63483 and will be released in `7.11.0`.
