### ISSUE TITLE
In IntegTest, TransportClient resets Node Roles

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#64260]
I've marked this as a test failure because I think this only matters in IntegTest, but it's possible there's an implication I haven't noticed. 

`TransportClient.buildTemplate` calls `DiscoveryNode.setAdditionalRoles`.
Because the XPackClientPlugin doesn't implement `getRoles`  that means that the TransportClient sets the additionalRoles to an empty set.

However, the `roleMap` in DiscoveryNode is static, so if `TransportClient` is running within the same VM as a `Node`, then the `DiscoveryNode.setAdditionalRoles` will be called multiple times with different arguments  - first the node(s) will set DATA_COLD, etc (XPackPlugin.getRoles()), then transport client will replace it with an empty list. 

This means in an integTest, when the node is torn down, `DiscoveryNode` will no longer understand roles like `data_cold` and will fail with:
```
java.lang.IllegalArgumentException: unknown role [data_cold]	
	at __randomizedtesting.SeedInfo.seed([DC175618C501C13:E9AF8852F96F20C1]:0)	
	at org.elasticsearch.cluster.node.DiscoveryNode.getRoleFromRoleName(DiscoveryNode.java:510)	
...
	at org.elasticsearch.common.settings.Setting.lambda$listSetting$44(Setting.java:1478)	
	at org.elasticsearch.common.settings.Setting.get(Setting.java:441)	
	at org.elasticsearch.common.settings.Setting.get(Setting.java:435)	
	at org.elasticsearch.cluster.node.DiscoveryNode.getRolesFromSettings(DiscoveryNode.java:233)	
	at org.elasticsearch.cluster.node.DiscoveryNode.isDataNode(DiscoveryNode.java:93)	
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.doStop(IndicesClusterStateService.java:206)	
	at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:79)	
	at org.elasticsearch.node.Node.stop(Node.java:913)	
	at org.elasticsearch.node.Node.close(Node.java:943)
```
(See: https://gradle-enterprise.elastic.co/s/ig4ptxqrzjuou/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.audit.logfile.AuditTrailSettingsUpdateTests/testDynamicEventsSettings)

This seems to be fixed by adding the DataTier roles to `XPackClientPlugin`, but I haven't attempted to understand the possible implications of that change.

Relates: https://github.com/elastic/elasticsearch/pull/64015

**Comment by jasontedor** [comment]
It is not clear to me why we even register these additional roles in the transport client. Transport clients do not take on these roles, and the role-handling code is built in a way that unknown roles can be handled (it needs to, since it might be talking to a new node that knows about roles the current node/client does not know about). I pushed the change that registered them in 2bcc49424d6c0dba1a5bead2fa8eeff30d96d48e but alas neither the code nor the commit message (my bad) are revealing enough to indicate why we have to do this. As a starting point, I would like to see what happens if we remove this registration.

**Comment by jasontedor** [comment]
I wonder if it's merely because need to be more careful in some of our tests and copy the node settings into the transport client settings (as you've done in the start basic trial license tests).

**Comment by jasontedor** [comment]
So the change in #64276 passes CI, indicating that we only need to not be setting node.roles on the transport client in tests.

**Comment by rjernst** [comment]
I believe this was fixed by https://github.com/elastic/elasticsearch/pull/64276, since we now no longer pass node.roles to the transport client.
