### ISSUE TITLE
Scripts should have a "cache" they can work with

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#6428]
It'd be useful if scripts could dump arbitrary values into a string keyed map that is reused across executions of the script.  In the case of function scoring you'd want it reused for all the scored documents on the same shard.  For script filters you'd want it to reused for all filtered documents on the shard.

**Comment by javanna** [comment]
@dakrone did you make any progress on this? I am curious on what you had in mind, and whether it is still doable or not.

**Comment by nik9000** [comment]
@shadow000fire, a static variable would work pretty poorly given that it could be run on multiple requests across multiple threads.  A ThreadLocal would have leakage issues, I think.  OTOH a native script might just be able to use a class variable - I haven't checked but I imagine the class is built once per request.  There _should_ be something for native scripts though.

@javanna, the writable slot trick in groovy _works_ but its a little bit horrible.  I imagine expression language wouldn't be able to do things like assign variables.....

**Comment by dakrone** [comment]
@javanna I haven't made any progress on this yet, feel free to grab it :)

**Comment by javanna** [comment]
I marked this for discussion, I am personally not sure we should support something like this, it sounds scary, but maybe it's just me. Also, if we do we need to find a way to make it work for all of the different engines.

**Comment by nik9000** [comment]
> I marked this for discussion, I am personally not sure we should support something like this, it sounds scary, but maybe it's just me.
I suppose it'd give you some way to consume a ton of memory.  I was just using it for holding precocmpiled automata.  It only had to work across a single request.  Its the same sort of attack vector as creating a huge collection in groovy in a while true loop.

> Also, if we do we need to find a way to make it work for all of the different engines.
Maybe its only a feature in one.  I dunno.  We're probably going to abandon scripts pretty soon, especially if we can get fast rolling restarts from index sealing.  In that case it doesn't make a huge difference for me.

This, btw, is why I stopped submitting patches for the builtin highlighters - it because a huge pain to implement everything three times with three different mindsets.

**Comment by s1monw** [comment]
> This, btw, is why I stopped submitting patches for the builtin highlighters - it because a huge pain to implement everything three times with three different mindsets.

you really read my mind... the highlighter situation is a nightmare and we have to fix this one way or the other!

**Comment by clintongormley** [comment]
This is too risky to expose with generic script engines.  If you want a cache in scripts then I think a native script is the only way to go here.
