### ISSUE TITLE
Check-and-set for aliases

### ISSUE THREAD

**Issue by magnhaug** [elastic/elasticsearch#6431]
The atomic update of aliases is very useful. However, if you have aggregate aliases that point to a lot of indexes, and these indexes are managed by a different threads/processes, you risk running into race conditions on updates.

I'd like this application flow:
 - Read which aliases to update
 - Issue the correct deletes and adds, *given the current situation is as expected*
 - Full *rollback*, and the ability to retry if the situation had changed from what we asserted

This would remove the need to synchronize complex alias operations in a multi-thread environment.

In the Java API I'd wish for something like:
 - .addAlias(index, alias)
 - .removeAlias(index, alias)
 - *.assertAlias(index, alias)*  or similar

**Comment by magnhaug** [comment]
@clintongormley Ok, I'll try to describe a quick example. Let's say:
 - A new datestamped index is created every day by process 1. The "current data"-alias is set up with a few alias filters.
 - Another process (process 2) periodically lists out the active aliases and writes them back with updated alias filters, when new sensitivity restrictions on the data should apply.

If these two processes work at the same time, process 2 might read soon-to-be-outdated aliases, and thusly re-binding the alias to an index that was deprecated by process 1.
Given that process 2 could atomically assert that the aliases it is updating are still valid, it could nicely retry instead of harmfully adding aliases pointing to old/stale data.

Our real world example is a bit more involved, but the application flow is similar to this example.
Our workaround has been to let "process 1" and "process 2" compete for a distributed lock, but this introduces the need for new components and synchronization points in the architecture.

**Comment by clintongormley** [comment]
Hi @magnhaug 

Thanks for the info.  I'll put this issue up for discussion, but my feeling is that it is the wrong approach.  Once you start with assertions like this, then where does it end?  Should we also assert on routing values, or alias filters?  What about other indices that an alias might point to?  It starts getting really messy.

Typically updating aliases is a very light-weight operation, so serialising requests application side is pretty easy.  Also, I'm working on a proposal for a more event-driven framework which will allow you to specify actions to be taken on certain cluster events (eg the creation of a new index).  i think this will be a cleaner solution than the assertions.

**Comment by magnhaug** [comment]
Valid points. I agree that specifying actions to be taken in order sounds cleaner from a client-perspective. Especially if they can be more fine-grained, like replacing a named alias filter or changing a routing value on an alias.

**Comment by clintongormley** [comment]
This ticket hasn't garnered any further interest, so I'm going to close it with the advice to serialize alias changes client side, where custom logic can easily be controlled.
