### ISSUE TITLE
Span_Not Equivalent in Intervals?

### ISSUE THREAD

**Issue by prasad2kin** [elastic/elasticsearch#64329]
Hi,

I'm looking for a way to implement [SPAN_NOT](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/query-dsl-span-not-query.html) queries using Intervals. I have seen that Lucene supports `notWithin` queries. I don't see Elasticsearch has anything that implements it.

So, can this please be implemented?

**Comment by jimczi** [comment]
You can check all the filters that `intervals` provide [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-intervals-query.html#interval_filter).
`not_contained_by`, `not_containing` and  `not_overlapping` are multiple ways to match documents with a not clause.
I hope you don't mind if I close this issue but we reserve github for verified bugs and feature requests.
