### ISSUE TITLE
EQL:  Introduce like/matches keywords

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#64387]
As pattern matching is common, provide support for it through dedicated keywords in the language.

#### `like`

Provides wildcard/star matching:

`field like "pattern*"`

The target field is always on the left, the pattern as a string literal on the right.

#### `matches`

`field matches "[a-z][0-9]"`

Similar construct to `like` however it accepts a regular expression.

**Comment by rw-access** [comment]
@costin I think we're good to close this one
