### ISSUE TITLE
Document the limitation of role query for document level security 

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#64405]
The role query used for document level security has a few limitations. For an example, it cannot use terms lookup, percolate, geoshape etc, which are pretty evident in the [code](https://github.com/elastic/elasticsearch/blob/7.10/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/support/DLSRoleQueryValidator.java#L142). Another less obvious limitation is that datemath with "now" cannot be used in a range query. None of these limitations is documented. In fact, the [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/document-level-security.html) says it "supports the full Elasticsearch Query DSL", which is somewhat misleading.

**Comment by tvernum** [comment]
We document some of these (neither particularly well, nor in any easy to find location)
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-limitations.html#_field_and_document_level_security_limitations

**Comment by ywangd** [comment]
Thanks Tim. I did search for "elasticsearch document level security terms lookup" and got nothing back in the first 2 pages. So it seems most of the limitation are actually documented. The only missing one is just datemath with "now" and it can be easily added alongside the existing ones.

As for the location, I'd suggest at least add a cross-link to the [document level security doc page](https://www.elastic.co/guide/en/elasticsearch/reference/current/document-level-security.html) to reference the page you linked. And revise the statement of it "supports the full Elasticsearch Query DSL".
