### ISSUE TITLE
Elasticsearch 7.7.0 ram.percent always 99% full

### ISSUE THREAD

**Issue by praveenmak** [elastic/elasticsearch#64445]
I see to have similar issue with Elasticsearch 7.7.0

```
free -mh
                      total        used       free      shared  buff/cache   available
Mem:           125G       34G        2.3G     16M      88G             90G
Swap:            0B          0B          0B
```

This is the Java -version. My RAM parcent shows its 99% full and Buffer/Cache has 80-90 GB.

openjdk 14 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

Here are all 10 nodes in the ES cluster. All of them show almost 99% ram.percent

```
heap.percent ram.percent cpu 
33           98          0
48           97          0
31           99          0
40           96          0
37           99          0
48           98          0
38           29          0
31           94          0
54           98          0
31           98          0
```

**Comment by apocarteres** [comment]
@praveenmak it would be great if you composed docker stack to reproduce that and share your compose file. It's literally impossible to figure out why you see the issue with no samples / input data / etc.

**Comment by cbuescher** [comment]
Hi @praveenmak! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by jtreher** [comment]
@praveenmak Did you ever solve this issue? We have the same problem. Once memory hangs at 99% all of ES slows down.

**Comment by philbert101** [comment]
You probably configured 50% Of system memory for the ES Heap. To decrease the ram.percent, just add memory to the server.
The ram.percent  is basically the  (total - free) / total    

`# free -m`
              `              total        used        free      shared  buff/cache   available`
`Mem:          32104       19032         278           4       12793       12596`
`Swap:             0           0           0`

Hope this answers your question.
