### ISSUE TITLE
Field-value-cardinality switch query

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#64506]
This idea is a spin off from a conversation we were having with @wylieconlon, and mirrors some difficulties users have with multi-valued fields in general.

I'd like to (tentatively) propose a query which can execute one of two sub-clauses based on if a field is multi-valued or not.  I think we can ascertain if a field is multi-valued _relatively_ easily from the doc values (since DVs often specialize between single and multi fields, or are don't apply at all like with binary).  We could use the DV information just for determining the "kind" of field, and still execute regular index queries otherwise to maintain performance.

The caveat is that this would only work with fields that have DVs, notably not working with text fields.  But in my experience, multi-valued text fields are pretty rare, whereas multi-valued keyword fields are very common.

We could of course store this information somewhere else so that it works universally, but the advantage of DVs is that we already have them and it'd be backwards compatible with already-indexed data.

Syntax could be pretty simple, providing two sub-clauses which are switched depending on the segment's field information:

```
{
  "multi-value-switch": {
    "multi-valued": {
      ... query here when there are multiple values ...
    },
    "single-valued": {
      ... other query here when there is only one value ...
    }
  }
}
```

Naming, of course, needs work :)

If this could be made to work, it'd give users an ability to tease apart behavior for single vs multi-valued fields.  I don't know if it's _sufficient_ to handle all cases, e.g. we probably need functionality like `must_only`, `must_not_only`, `value_count` etc to make it a robust experience... but just this "switch" query would open up a lot of interesting doors I think.

### Fatal Flaw!
There is a fatal flaw to the above plan: a single document with multiple field values will "promote" the whole field to multi-value.  Which means "multi-valued" fields with a single value will flow through the "multi" switch and could easily derive the incorrect results.  I suspect this is a dealbreaker, but already had the issue typed up so I'm hoping folks on the Search team have a clever idea how to fix it (without just checking the DVs on each document... which sounds quite slow)

Edit:  Even with this flaw, it would still give you a potential "fast path" for single-valued fields, since you would know definitively in that case.  Which might help overall performance by allowing a fast, native query for single-valued fields, and fall back to a scripted solution for multi-valued fields.

**Comment by nik9000** [comment]
We built something similar for ESQL a while back: https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java

There are some problems with it that @iverase are working on, but we do have it. If anyone else needs it we can move it.

It's a little different in that if a field *could* have multiple values we actively check against the doc values. That's how ESQL's filters mostly work.

Given that no one has asked for this in four years, I'm going to close it. If you need something like it ESQL kind of already does it. And if you need it in the search DSL then reopen this and explain please. I think it's possible to move it over.
