### ISSUE TITLE
[CI] Failure in org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#64578]
```
./gradlew ':x-pack:qa:rolling-upgrade-basic:v7.9.4#oldClusterTest' --tests "org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic" -Dtests.seed=5B22100B1FCA9959 -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=Africa/Algiers -Druntime.java=8
```

failed in https://gradle-enterprise.elastic.co/s/7n4cfvbfcywl6/console-log?anchor=12279 with

```

org.elasticsearch.upgrades.BasicLicenseUpgradeIT > testOldAndMixedClusterHaveActiveBasic FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:42229], URI [/_license], status line [HTTP/1.1 404 Not Found] |  
  | { } |  
  | at __randomizedtesting.SeedInfo.seed([5B22100B1FCA9959:78F3B9C5F9CAB7D8]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262) |  
  | at org.elasticsearch.upgrades.BasicLicenseUpgradeIT.checkBasicLicense(BasicLicenseUpgradeIT.java:27) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:991) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:976) |  
  | at org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic(BasicLicenseUpgradeIT.java:17)
```

Does not reproduce locally.

**Comment by imotov** [comment]
Failed twice today. The last failure: https://gradle-enterprise.elastic.co/s/fjpv6fvx26mdw

**Comment by javanna** [comment]
another failure: https://gradle-enterprise.elastic.co/s/qozvlo4u6oxse/console-log?task=:x-pack:qa:rolling-upgrade-basic:v7.11.0%23oldClusterTest

**Comment by costin** [comment]
Occurring inside the multi-job matrix: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=fedora-32&&immutable/355/console

[7.10.1] https://gradle-enterprise.elastic.co/s/vqnxk4bcaznge 
[6.8.14] https://gradle-enterprise.elastic.co/s/eut424xpifh42 
[7.10.1] https://gradle-enterprise.elastic.co/s/u2sjv56zlk2kq 
[6.8.14] https://gradle-enterprise.elastic.co/s/yeu7ny2yql3my 
[7.10.1] https://gradle-enterprise.elastic.co/s/ypqknr6gmwrne
https://gradle-enterprise.elastic.co/s/wrbfw4dfxe6yu

**Comment by hendrikmuhs** [comment]
The failures seem to have this in common:

```
12:07:23 » 2020-11-04 11:07:23,413033 UTC [557462] ERROR CLogger.cc@310 Cannot log to named pipe /var/lib/jenkins/workspace/elastic+elasticsearch+7.10+multijob-unix-compatibility/os/fedora-32&&immutable/x-pack/qa/rolling-upgrade-basic/build/testclusters/v7.9.4-1/tmp/controller_log_556925 as it could not be opened for writing
12:07:23 »  2020-11-04 11:07:23,413133 UTC [557462] INFO  Main.cc@103 Parent process died - ML controller exiting
```

All the recent failures happened on `fedora-32`, this might be a platform specific issue with native code.

/CC @droberts195

**Comment by droberts195** [comment]
> All the recent failures happened on `fedora-32`, this might be a platform specific issue with native code.

Yes, every single Gradle scan linked in this issue is for Fedora 32.  Fedora 32 was added to CI 24 days ago, which tallies with this issue being opened 19 days ago (there was a weekend in that first 5 days).  I will look into it.

**Comment by droberts195** [comment]
I had a look in more detail at this.  The ML error message "Cannot log to named pipe /var/lib/jenkins/workspace/elastic+elasticsearch+7.10+multijob-unix-compatibility/os/fedora-32&&immutable/x-pack/qa/rolling-upgrade-basic/build/testclusters/v7.9.4-1/tmp/controller_log_556925 as it could not be opened for writing" is highly misleading.  What has actually happened is that the ES JVM has been killed, then the ML controller process has noticed and also exited.  To do this the call to connect the named pipe used for logging had to be interrupted.  So the only reason this pipe didn't open was that opening it was deliberately interrupted.  The second ML message, "Parent process died - ML controller exiting", is the one that is accurate.  I have opened elastic/ml-cpp#1591 to stop the confusing message getting logged in the future.

None of this is related to the root cause of the problem though.  Looking at that, the nodes in the cluster are logging errors like:

```
org.elasticsearch.transport.RemoteTransportException: [v7.10.1-0][127.0.0.1:45415][internal:cluster/coordination/join]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: incoming term 1 does not match current term 2
```

and:

```
org.elasticsearch.transport.RemoteTransportException: [v7.10.1-0][127.0.0.1:45415][internal:cluster/coordination/join]
Caused by: org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node is no longer master for term 1 while handling publication
```

and:

```
org.elasticsearch.transport.RemoteTransportException: [v7.10.1-1][127.0.0.1:39947][internal:cluster/request_pre_vote]
Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: rejecting PreVoteRequest{sourceNode={v7.10.1-0}{RjSXzJ1CR2ubwHojpIeNUQ}{QC9rPeJHS-CW0042b0rgWg}{127.0.0.1}{127.0.0.1:45415}{cdhimrstw}{testattr=test, xpack.installed=true, transform.node=true}, currentTerm=2} as there is already a leader
```

So it seems that the cluster is failing to form, then eventually gets killed by the test harness, then after that the ML controllers (correctly) decide they should no longer be running and exit.

Does anyone from @elastic/es-distributed have an idea why the cluster doesn't form sometimes?  I am not sure why Fedora 32 would make a difference here.

**Comment by nik9000** [comment]
Another! https://gradle-enterprise.elastic.co/s/6dmtqkrv2h5fu/tests/failed

**Comment by tvernum** [comment]
Another: https://gradle-enterprise.elastic.co/s/bazoexvcxmrzc/tests/:x-pack:qa:rolling-upgrade-basic:v7.10.1%23oldClusterTest/org.elasticsearch.upgrades.BasicLicenseUpgradeIT/testOldAndMixedClusterHaveActiveBasic#1

Also Fedora-32, also cluster formation issues.
```
[WARN ][o.e.c.s.MasterService    ] [v7.10.1-0] failing [elected-as-master ([2] nodes joined)[{v7.10.1-0}{6Vcnc_NlToy_fddvOceKPw}{X46o4X6wQpSnEQ8rZUpIiQ}{127.0.0.1}{127.0.0.1:41405}{cdhimrstw}{xpack.installed=true, transform.node=true, testattr=test} elect leader, {v7.10.1-1}{OJpfmS-1Q5Ohc0efJqIRwQ}{019TQIXMSaCx84d8uL_NnQ}{127.0.0.1}{127.0.0.1:42367}{cdhimrstw}{testattr=test, xpack.installed=true, transform.node=true} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_]]: failed to commit cluster state version [1]	
»  org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: publication failed	
»  	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$4.onFailure(Coordinator.java:1467) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
```

```
 Caused by: org.elasticsearch.ElasticsearchException: publication cancelled before committing: become candidate: joinLeaderInTerm	
»  	at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:86) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
```

```
» [2020-12-08T02:25:07,862][INFO ][o.e.c.c.JoinHelper       ] [v7.10.1-0] failed to join {v7.10.1-2}{uG7wo3t5RXmOJ9kOW2R5nA}{Cp_fVfMKSPWvk5W9Odg8jw}{127.0.0.1}{127.0.0.1:38647}{cdhimrstw}{testattr=test, xpack.installed=true, transform.node=true} with JoinRequest{sourceNode={v7.10.1-0}{6Vcnc_NlToy_fddvOceKPw}{X46o4X6wQpSnEQ8rZUpIiQ}{127.0.0.1}{127.0.0.1:41405}{cdhimrstw}{xpack.installed=true, transform.node=true, testattr=test}, minimumTerm=4, optionalJoin=Optional.empty}	
»  org.elasticsearch.transport.RemoteTransportException: [v7.10.1-2][127.0.0.1:38647][internal:cluster/coordination/join]	
»  Caused by: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: join target is a follower	
»  	at org.elasticsearch.cluster.coordination.JoinHelper$FollowerJoinAccumulator.handleJoinRequest(JoinHelper.java:445) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
```

```
[WARN ][o.e.g.DanglingIndicesState] [v7.10.1-1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually	
» WARN ][o.e.d.FileBasedSeedHostsProvider] [v7.10.1-1] expected, but did not find, a dynamic hosts list at [/var/lib/jenkins/workspace/elastic+elasticsearch+7.x+multijob-unix-compatibility/os/fedora-32&&immutable/x-pack/qa/rolling-upgrade-basic/build/testclusters/v7.10.1-1/config/unicast_hosts.txt]	
»   ↑ repeated 2 times ↑	
» WARN ][o.e.c.s.MasterService    ] [v7.10.1-1] failing [elected-as-master ([2] nodes joined)[{v7.10.1-0}{6Vcnc_NlToy_fddvOceKPw}{X46o4X6wQpSnEQ8rZUpIiQ}{127.0.0.1}{127.0.0.1:41405}{cdhimrstw}{testattr=test, xpack.installed=true, transform.node=true} elect leader, {v7.10.1-1}{OJpfmS-1Q5Ohc0efJqIRwQ}{019TQIXMSaCx84d8uL_NnQ}{127.0.0.1}{127.0.0.1:42367}{cdhimrstw}{xpack.installed=true, transform.node=true, testattr=test} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_]]: failed to commit cluster state version [1]	
»  org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node is no longer master for term 1 while handling publication
```

@elastic/es-distributed What can we do to track this down?

**Comment by benwtrent** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/nbgdghakyqonq

Still fedora 32.

**Comment by dimitris-athanasiou** [comment]
And another fedora 32 failure: https://gradle-enterprise.elastic.co/s/g5p3nej3434eo

**Comment by fcofdez** [comment]
I've been able to reproduce this issue in a VM. 
The issue doesn't seem to be related to the cluster formation, as a master is elected and the cluster seems to be stable after that.
The problem seems to be that the test harness considers the cluster to be ready (and performs the `GET _license` request) before the license state has been loaded in memory, causing the error that we can see in this test failure.
I'm still not sure why this only happens in Fedora 32.

**Comment by valeriy42** [comment]
The failure occured again several times recently:
*  https://gradle-enterprise.elastic.co/s/xfoxzcdazhupk
* https://gradle-enterprise.elastic.co/s/mzkhmvhuwy3wk
* https://gradle-enterprise.elastic.co/s/ozneqeqcy5vd6

**Comment by fcofdez** [comment]
I missed backporting the fix to 7.11, https://github.com/elastic/elasticsearch/commit/b0e1d9dab97e8e1620dcd2282fe0e92cfb633cc2 should fix it in 7.11. Sorry for the noise.

**Comment by tarekziade** [comment]
@fcofdez I feel like we should try to address the problem at the API level by returning a value when it's ready -- the CI fix is a workaround

My understanding is that it should return the license data, never `{}` - see / https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html

Should we open a follow-up bug ?

**Comment by tvernum** [comment]
@tarekziade 

> I feel like we should try to address the problem at the API level by returning a value when it's ready -- the CI fix is a workaround

We do, but it is possible for the cluster to be ready but the license to not be ready. 
They are separate operations with separate lifecycles.

It is an incorrect (though understandable) assumption to expect that a cluster will necessarily have a license just because the cluster is active.

> My understanding is that it should return the license data, never {} 

As above, the `{}` (which is accompanied by a `404` status) is due to there being not being any license data yet.
If there are scenarios where the cluster definitely has license data, but the API is responding with `{}` then we should look at those, but I haven't seen any cases of that.

> see / https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html

Our API documentation doesn't do a very thorough job of documenting all the ways that an API can fail, and we should do a better job of that. I opened https://github.com/elastic/elasticsearch/issues/70848 to add this scenario to the docs.

**Comment by tarekziade** [comment]
> @tvernum
> As above, the `{}` (which is accompanied by a `404` status) is due to there being not being any license data yet.
> If there are scenarios where the cluster definitely has license data, but the API is responding with `{}` then we should look at those, but I haven't seen any cases of that.

When I start ES using docker, I get this *transient* state where it returns `{}` for a few seconds before everything is running. 
My interpretation is that the cluster a license, but was not able to pull it *yet*. Do you mean by your answer that in some cases, it's possible that a cluster will never have a license, and getting a 404 on this URL is OK ?
> 
> > see / https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html
> 
> Our API documentation doesn't do a very thorough job of documenting all the ways that an API can fail, and we should do a better job of that. I opened #70848 to add this scenario to the docs.

Thanks!

**Comment by tvernum** [comment]
> When I start ES using docker, I get this transient state where it returns `{}` for a few seconds before everything is running.
My interpretation is that the cluster a license, but was not able to pull it yet.

I don't think that interpretation is quite right - at least I'm not aware of any circumstances under which that would be true.

Are you:
1. Starting a brand new cluster with a single node in docker
2. Starting a brand new cluster with a multiple nodes in docker
3. Joining the docker node to an existing cluster that is already running
4. Starting a standalone node with an existing cluster state on disk

The only circumstances under which I am aware of this behaviour occurring is in (1) and (2) (which are effectively the same)

For (3) once the node reports that it is part of the cluster, it should also report the license for the cluster. There should never be a circumstance under which the node correctly returns that it is a member of the cluster but does not know about the license in that cluster (provided that license exists).

For (4) once the node reports that it has recovered the cluster state from disk, it should also report the correct license. I don't _think_ there is any case under which we would report that the cluster is ready but not yet have a recovered license, unless the cluster never had a license, which is extremely unlikely.

> Do you mean by your answer that in some cases, it's possible that a cluster will never have a license, and getting a 404 on this URL is OK ?

I didn't mean that, but it might be true.
Given the history of the commercial plugins for ES, the license is managed separately to the core parts of the cluster state. In some versions of ES it was explicitly possible to have a cluster that had the license plugin, but no license. In current versions we try to avoid that, but there are theoretical cases where that could happen.
By which I mean, if you poll `/_license` for 60s or more, and it's still returning `404` then the cluster has probably gotten into some state that we didn't cater for, and it might never get a license (or the master node might need to be restarted to fix it). I haven't seen that, but I don't want to exclude the possibility.

**Comment by tarekziade** [comment]
I can reproduce the issue by starting a brand new cluster with a single node in docker. 
Thanks for the detailed explanation ! I guess the 60 seconds poll scenario is the safest for us.
