### ISSUE TITLE
uax_url_email analyzer incorrectly parses domain: ".local"

### ISSUE THREAD

**Issue by stevemer** [elastic/elasticsearch#6467]
uax_url_email analyzer appears unable to recognize the .local TLD. Bug can be reproduced by

curl -XGET "ADDRESS/INDEX/_analyze?text=First%20Last%20lname@section.mycorp.local&pretty&analyzer=uax_url_email"

will parse "lname@section.my" and "corp.local" as separate tokens, as opposed to

curl -XGET "ADDRESS/INDEX/_analyze?text=First%20Last%20lname@section.mycorp.org&pretty&analyzer=uax_url_email"

which will recognize  "lname@section.mycorp.org".

**Comment by clintongormley** [comment]
No point in keeping this open any longer - we'll get the update when it is addressed in Lucene
