### ISSUE TITLE
EQL: better error message for missing tiebreaker

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#64690]
In sequences that specify tiebreakers, events without such a field trigger the following error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "eql_illegal_argument_exception",
        "reason" : "Expected tiebreaker to be Comparable but got null"
      }
    ],
    "type" : "eql_illegal_argument_exception",
    "reason" : "Expected tiebreaker to be Comparable but got null"
  },
  "status" : 500
}
```
This is not very user friendly since it indicates the problem but not the cause or how to fix it. It would help to rephrase the message to indicate that the tiebreaker field (and its name) and potentially the associated query is missing for a certain document (along side information on the document id).

**Comment by costin** [comment]
Replaced by #64706

**Comment by caiomelo22** [comment]
Hi! Can I try to solve this issue?
