### ISSUE TITLE
Rework complex tests for runtime_mappings

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#64716]
We "stole" core's tests for `runtime_mappings` defined on the search request, modifying them on the fly to add the `runtime_mappings`. This isn't really as simple as we'd like because the tests rely on dynamic mappings and, well, we can't use those because the whole point of the tests is to define the mappings on the search request. We manage, but its *complex* and we might be able save some complexity by letting ES do *some* dynamic mappings but disabling the fields it makes. Then, before a search request scraping the mapping and building our "load from source" runtime fields on the fly. This is fairly complex too, but *might* be simpler than what we have at the moment....

**Comment by nik9000** [comment]
I've filed this to make sure we don't forget to look at these tests again with fresh eyes in a month or something.

**Comment by javanna** [comment]
> I've filed this to make sure we don't forget to look at these tests again with fresh eyes in a month or something.

It's been a year and a half, and I think it would be more complex to rewrite these tests now than to keep the current complexity :) jokes aside, I feel like these tests are running fine as they are and we don't necessarily need to go back and change them. Please let me know if you think otherwise!
