### ISSUE TITLE
ArchiveTests.test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir fails on Fedora 32 / Ubuntu 20.04

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#64735]
On Fedora 32 and Ubuntu 20.04, we're seeing repeated failures on one specific archive packaging test. It's not clear where the problem lies yet. We may not be able to add Ubuntu 20.04 to the support matrix until we get to the bottom of the problem, as this could be a legitimate environmental issue.

**Build scan**:

https://gradle-enterprise.elastic.co/s/n4q2o3xfmbhoy/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveTests/test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir#1

**Comment by pugnascotia** [comment]
cc @Dinomoe for your interest.

**Comment by mark-vieira** [comment]
@rjernst Anything immediately jump out to you here?

**Comment by pugnascotia** [comment]
I added some debugging in a PR, and it does look like Elasticsearch isn't stopping during that test like it's supposed to (I don't know yet if it's just slow, or no stopping at all).

**Comment by pugnascotia** [comment]
I have a fix in #64858.

**Comment by mark-vieira** [comment]
Nice. Given we've confirmed this was just a test issue, and not actually a problem with Elasticsearch. We can probably pull the trigger on adding Ubuntu 20.04 to our support matrix.
