### ISSUE TITLE
different allocation of tcp connect

### ISSUE THREAD

**Issue by zhangyunzhao** [elastic/elasticsearch#64761]
most of our cluster only use one or two connect to our restclient, but there is one data node use 7 connect to our restclient

**Comment by zhangyunzhao** [comment]
version is 7.3.1

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
