### ISSUE TITLE
[CI] Pin java 8 version to a pre u272 for fips matrix jobs

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#64776]
Since the last updates of JDK8 ( u272 ) and the introduction of TLSv1.3 support in JDK8, our fips matrix jobs are failing for 7.x. We are tracking this in  https://github.com/elastic/elasticsearch/issues/64379. 

The reason for the failure is detailed in https://github.com/elastic/elasticsearch/issues/61316#issuecomment-685482708 and in a subsequent email in [the BC mailing list ](http://bouncy-castle.1462172.n4.nabble.com/JDK8-SunJSSE-with-BCFIPS-TLS-v1-3-handshake-failure-due-to-unavailable-signature-scheme-td4660027.html)

We currently have no coverage for 7.x, 7.9, 7.10. Can we pin the version of JDK8 we are using in these jobs to the last available before u272 ( which is u265 ) instead of using the latest available? @mark-vieira @breskeby can we specify an exact version in the axis of a job definition ( instead of reading i.e. `adoptopenjdk8` from our YAML file with runtime java definitions ) ? 

In the medium term we need to decide what we can do with the SunJSSE + BCFIPS combination and whether or not it is supportable or we need to change to BCJSSE for 7.x too. This discussion and decision can potentially take some time and we should find a way to keep testing in JDK8, even with a slightly older JDK version.

**Comment by mark-vieira** [comment]
>  Can we pin the version of JDK8 we are using in these jobs to the last available before u272 ( which is u265 ) instead of using the latest available? @mark-vieira @breskeby can we specify an exact version in the axis of a job definition ( instead of reading i.e. adoptopenjdk8 from our YAML file with runtime java definitions ) ?

I don't believe so since these JDKs are baking into the CI worker images. @leathekd is this something we can do in the Packer config? Can we have it install a particular version of Java 8 instead of latest?

**Comment by leathekd** [comment]
Yeah, it's possible.  Two options come to mind:

1. Override the version of JDK8 for all of Elasticsearch-CI
    You'll need to override the [default set of JDKs][] with a set defined in [your ansible group vars][].  The [config for the long run benchmark servers][] offers an example.  

2. Override just for the FIPs builds
    Similar to the above, except start with adding a new ansible group for the FIPS images and update the [two packer configs][] to apply that group.  Then do the same as 1 but only using the new FIPS group for the group vars.

Let us know if you need an hand with either of those.

[default set of JDKs]: https://github.com/elastic/infra/blob/master/ansible/roles/java/defaults/main.yml#L12-L62
[your ansible group vars]: https://github.com/elastic/infra/blob/master/ansible/playbooks/group_vars/elasticsearch-ci/jenkins.yml
[config for the long run benchmark servers]: https://github.com/elastic/infra/blob/master/ansible/playbooks/group_vars/longrunbenchmarks/config.yml
[two packer configs]: https://github.com/elastic/infra/search?q=fips+nocache

**Comment by mark-vieira** [comment]
Yeah, that centos fips image is a slightly different thing. It's specifically for packaging tests and pinning the version for all builds is non-ideal. @leathekd could we simply _add_ an item [here](https://github.com/elastic/infra/blob/master/ansible/roles/java/defaults/main.yml#L12-L62) for the specific java 8 version we need and just install it to `/openjdk8-fips` or something like that?

**Comment by jkakavas** [comment]
We could alternatively leave the current jobs as-is ( we can change the security provider for those assuming we can get coverage with SunJSSE in another way ) and add a new job that has the jdk8 pinned to a specific version, if this is easier to handle.

**Comment by mark-vieira** [comment]
@elastic/infra-automation does my idea in [this comment](https://github.com/elastic/elasticsearch/issues/64776#issuecomment-724313569) sound sane? If so I'll open a PR to implement this.

**Comment by jonahbull** [comment]
@mark-vieira Yes, I think that'll work. Something like this (you'd have to make a separate entry for each OS you need to support)?
```
  "adoptopenjdk-8u265-linux":
    link_as: "{{ custom_java_location }}/openjdk8-fips"
```

**Comment by mark-vieira** [comment]
Thanks @jonahbull. We only need this for Linux. I've opened https://github.com/elastic/infra/pull/24900.

**Comment by jkakavas** [comment]
I think the best test coverage would be provided by: 

- Keeping the existing matrix job as is ( and updating the code to use BCJSSE instead of SunJSSE ) so that we test with latest jdk 8 versions
- Adding a new Job that runs 7.x and the supported 7.y branches with the pinned jdk8 version so that we can keep testing with SunJSSE


@mark-vieira if you're ok with the additional job, I'll raise a PR with the job template.

**Comment by mark-vieira** [comment]
@jkakavas I believe this has been resolved? Can we close this issue?

**Comment by jkakavas** [comment]
yes, we still need to do something to extend coverage as mentioned in the last post but we can discuss this in a separate issue
