### ISSUE TITLE
Sample documents before aggregating

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elasticsearch#64777]
When aggregating over a large amount of documents, it might be acceptable to the user to have Elasticsearch select a subset of documents, and return the aggregation response for those. Ideally ES can also upscale the results of its aggregations, but that's not a requirement or this to be useful at all.

Random sampling is totally fine. A bonus would be to be able to define the max response time and have ES reports it data when that time has elapsed.

**Comment by polyfractal** [comment]
Related: https://github.com/elastic/elasticsearch/pull/53200

**Comment by not-napoleon** [comment]
@dgieselaar When you have a moment, it would be helpful to get a sense of what situations you'd want to use sampling in.  What kind of queries & aggs, how the data is laid out (especially you expect to be using this with multiple date rolled indexes), what kind of error you'd find acceptable, what kind of time improvement you'd be looking for.  That type of thing.

Sampling is definitely something we'd like to build, but it's a pretty complicated problem and I want to make sure we're building something people will actually use.  That said, we're currently only in the requirements gathering phase and it's not on our near term road map, so don't hold your breath :)

**Comment by rayafratkina** [comment]
cc @wylieconlon @timroes for visibility

**Comment by JosephTucci** [comment]
@not-napoleon a situation I've run into is aggregating the cardinality of large sets of documents. 

A big win for me is how HLL++ can be precise at counts <50k documents
For counts of 50k to about 1M documents things are great. Counts are up to ~5% off depending on the precision I send in. 
Counts beyond 1M I see the process takes time proportional to the number of documents, even with precomputed hashes. This feature would allow me to define a ceiling on the number of documents to perform HLL++ upon. For me, it makes sense to accept large error bounds for consistent speed.

My query filter is dynamic so i don't know how many documents a given filter set will return but I am aware of how many aggregations I am executing. In some instances, I want to compute tens of terms aggregations across various fields then perform a cardinality upon those results.

While I'm not holding my breath I am excited to see this feature come to life. If I can help in anyway let me know.

**Comment by dgieselaar** [comment]
> @dgieselaar When you have a moment, it would be helpful to get a sense of what situations you'd want to use sampling in. What kind of queries & aggs, how the data is laid out (especially you expect to be using this with multiple date rolled indexes), what kind of error you'd find acceptable, what kind of time improvement you'd be looking for. That type of thing.

I would say something below 1% error margin is acceptable, but @graphaelli or @alex-fedotyev have a better feeling for those things. I think in an ideal world, we'd like to load every dashboard in under 2.5 seconds (probably a configurable threshold). Ideally we can tell ES try to complete within 2.5s, but make sure that the error margin is below 1%, and tell me roughly what percentage of documents/values were sampled.

I'm on PTO, but maybe @sqren or others from the APM UI team can chime in here with the type of queries that we're doing that are slow (@sqren: I'm thinking service inventory and traces overview, possibly service maps depending on our data structure).

**Comment by wchaparro** [comment]
@benwtrent can we close this one in lieu of the 8.4 release of random sampler?

**Comment by benwtrent** [comment]
I think so @wchaparro

**Comment by not-napoleon** [comment]
closing this as the Random Sampler should address this need.  Further enhancements to random sampling can and should be addressed with new tickets.
