### ISSUE TITLE
EQL: Add support for Cross-cluster search (CCS)

### ISSUE THREAD

**Issue by peluja1012** [elastic/elasticsearch#64784]
Elastic Security users have the ability to create Detection Rules using CCS queries. However in 7.10, users are unable to create Event Correlation (EQL) rules using CCS. Fo example, creating an Event Correlation rule with a CCS index pattern of `*:auditbeat-*` will yield an EQL error of:
```javascript
Found 1 problem line -1:-1: Unknown index [*,-*]
```
This issue is to discuss the support of CCS in EQL queries.

**Comment by costin** [comment]
I'm glad to report that we've managed [to merge](https://github.com/elastic/elasticsearch/pull/74399) this functionality, as experimental, for 7.14.
Note this is experimental and will all clusters (local and remove) to be the same version.
There's work underway on documenting this functionality - I'll post a link once it's done.

**Comment by astefan** [comment]
This is complete with the last bit - documentation: https://github.com/elastic/elasticsearch/pull/74995
