### ISSUE TITLE
write consistency levels -- quorum of two is two

### ISSUE THREAD

**Issue by shikhar** [elastic/elasticsearch#6482]
In `TransportShardReplicationOperationAction`'s verification of the write consistency level where it checks before executing the write if sufficient shards are available,

```java
                    int requiredNumber = 1;
                    if (consistencyLevel == WriteConsistencyLevel.QUORUM && shardIt.size() > 2) {
                        // only for more than 2 in the number of shardIt it makes sense, otherwise its 1 shard with 1 replica, quorum is 1 (which is what it is initialized to)
                        requiredNumber = (shardIt.size() / 2) + 1;
                    } else if (consistencyLevel == WriteConsistencyLevel.ALL) {
                        requiredNumber = shardIt.size();
                    }
```

the `(n / 2) + 1)` should apply even with just 2 shards, giving a `requiredNumber = 2`. This is the commonly accepted definition.

**Comment by shikhar** [comment]
v2.0 seems like a good opportunity to fix this :-)

The main argument I have heard here is the out-of-the-box experience, which can be addressed by making the default `number_of_replicas` 0.

**Comment by bleskes** [comment]
@shikhar the one node experience is one argument. The other is being fault tolerant when loosing a node (and it's replicas). If we remove the exception of quorum for the two data copies case, (i.e., primary and replica) people won't be able to index when they loose a node, until the replica is re-constructed on another node - which may take a long time depending on shard size. To avoid this, one would need to keep 3 copies of everything by default. This is all about making the right tradeoffs between things and we feel that asking people to have 3 copies of their data (potentially many terabytes if not more) by default  goes too far. The alternative of having only one copy by default also doesn't seem appealing as it is a risky default. Of course, people can make another choice and change the setting - and we should document that clearly.

**Comment by dakrone** [comment]
It's been a year of discussion on this since the last comment, I don't think we are planning on changing the default number of replicas to 0, or changing the quorum value, so I'm going to close this, we can re-open if people still want to discuss it.

**Comment by bleskes** [comment]
Thx @dakrone for bubbling this up. I think this is covered by #19454, which removes the quorum terminology.
