### ISSUE TITLE
Should we include a category with deprecation messages?

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#64824]
Right now, the deprecation messages that Elasticsearch records contain a "key" (a string identifier, loosely descriptive) and a message about the deprecation, possibly with specific details.

We discussed during an 8.0 Stack Upgrade meeting whether it would be useful to also record a category field, e.g. "search" or "security". This would provide a useful field for grouping messages in the Kibana Upgrade Assistant. Such groupings would be useful for prioritising efforts to address deprecated uses of Elasticsearch, or even assigning work to different groups.

The work to implement this would be simple enough, just a little tedious.

**Comment by rjernst** [comment]
We discussed this within core/infra and it seems easy enough and not to much overhead, given a fixed set of categories and requiring that when logging a deprecating message.
