### ISSUE TITLE
[Docs] Add checksum links to plugin download links

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/elasticsearch#64846]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.3 

**Plugins installed**: Any - e.g. S3 Repository plugin

**Description of the problem including expected versus actual behavior**:
On the download pages for downloading standard artefacts (e.g. [here](https://www.elastic.co/downloads/elasticsearch) ), next to each download link we include a link to the Sha512 hash and the pgp signature for each file (`sha` and `asc` respectively)

![Screenshot from 2020-11-10 08-56-21](https://user-images.githubusercontent.com/5576500/98651819-a3e59080-2332-11eb-8e08-768bb0abbe9e.png)

Can we please include these links in the Plugin download page as well ( https://github.com/elastic/elasticsearch/blob/master/docs/plugins/install_remove.asciidoc )

The relevant links are simply 
`{plugin_url}/{plugin_name}/{plugin_name}-{version}.zip.sha512` 
and
`{plugin_url}/{plugin_name}/{plugin_name}-{version}.zip.asc`
respectively

**Comment by jrodewig** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/64949
