### ISSUE TITLE
WatcherYamlRestIT timeout 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#64857]
**Build scan**:
https://gradle-enterprise.elastic.co/s/a5auppz5wydyo/console-log?task=:x-pack:plugin:watcher:qa:rest:yamlRestTest
https://gradle-enterprise.elastic.co/s/l6k42hnx76ygu/console-log?task=:x-pack:plugin:watcher:qa:rest:yamlRestTest

**Repro line**:
```
./gradlew ':x-pack:plugin:watcher:qa:rest:yamlRestTest' --tests "org.elasticsearch.smoketest.WatcherYamlRestIT.test {p0=painless/40_exception/Test painless exceptions are returned when logging a broken response}" -Dtests.seed=4D7B25D50C51E6EA -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Iran -Druntime.java=11
```
**Reproduces locally?**:
No

**Applicable branches**:
Master

**Failure history**:
Twice in the last 2 days. 

It may be a slow VM but 2 failures in 2 days has raised my suspicions 

**Failure excerpt**:
```
Caused by: java.lang.AssertionError: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"yamlRestTest","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}]
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:296)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
```

**Comment by danielmitterdorfer** [comment]
Another instance in https://gradle-enterprise.elastic.co/s/mpqcawtne46uq:

```
        java.lang.AssertionError: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"yamlRestTest","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}]
```

i.e. the test is failing because there is one unassigned shard.

**Comment by markharwood** [comment]
Another instance in https://gradle-enterprise.elastic.co/s/sd4va4diu23ps

**Comment by martijnvg** [comment]
The yaml tests ran by this test class don't seem to have failed for at least 6 weeks ([history](https://build-stats.elastic.co/app/kibana#/discover/0d588210-3843-11ea-a7eb-15e193b310ea?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-100d,mode:relative,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch+AND+class:*WatcherYamlRestIT'),sort:!(time,desc)))). 

After 30 November not a single failure occurred, some has changed which seem to make this test suite behave.
Please re-open tests in the `WatcherYamlRestIT` yaml test suite start to fail.
