### ISSUE TITLE
g1gc build is failing consistently

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#64916]
**Build scan**: e.g. https://gradle-enterprise.elastic.co/s/gtjmd37pq2dlm

**Repro line**: N/A (see below for details)

**Reproduces locally?**: no

**Applicable branches**: `master`

**Failure history**:

The build has [failed consistenly since September 23, 2020](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-3M,mode:relative,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'build.job-name:%22elastic%2Belasticsearch%2Bmaster%2Bg1gc%22%20AND%20NOT%20process.status:%22FAILURE%22'),sort:!(process.time-start,desc))) (note that the linked view shows successful builds, not failed ones, and the last one was on September 23). Since then we had [146 build failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-09-23T22:00:00.000Z',mode:absolute,to:'2020-11-11T12:25:58.785Z'))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'build.job-name:%22elastic%2Belasticsearch%2Bmaster%2Bg1gc%22%20AND%20process.status:%22FAILURE%22'),sort:!(process.time-start,desc))).

**Failure excerpt**:

The build fails because `elasticsearch-keystore` terminates with exit code 1.

```
11:15:24 Execution failed for task ':qa:full-cluster-restart:v7.10.0#oldClusterTest'.
11:15:24 > Process 'command './bin/elasticsearch-keystore'' finished with non-zero exit value 1
11:15:24 
11:15:24 * Try:
11:15:24 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
11:15:24 
11:15:24 * Exception is:
11:15:24 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':qa:full-cluster-restart:v7.10.0#oldClusterTest'.
```

In the [console output](https://gradle-enterprise.elastic.co/s/gtjmd37pq2dlm/console-log?task=:qa:full-cluster-restart:v7.10.0%23oldClusterTest) we see why the test has failed:

```
:qa:full-cluster-restart:v7.10.0#oldClusterTest FAILED
Exec output and error:
| Output for ./bin/elasticsearch-keystore:Unrecognized VM option 'UseConcMarkSweepGC'
| Error: Could not create the Java Virtual Machine.
| Error: A fatal exception has occurred. Program will exit.
```

So it seems that `elasticsearch-keystore` picks up JVM flags for a Java version < 14 (including the JVM option `UseConcMarkSweepGC`) but actually runs with a Java version >= 14 (where [CMS has been removed](https://openjdk.java.net/jeps/363)).

**Comment by droberts195** [comment]
I think this is #62716, but I didn't notice the pattern that it was g1gc builds at the time I opened it.

https://github.com/elastic/elasticsearch/issues/62716#issuecomment-723750234 suggests getting rid of the dedicated g1gc builds.

**Comment by danielmitterdorfer** [comment]
Thanks for the pointer @droberts195, I did not see that issue originally. I think we can close this one as duplicate.
