### ISSUE TITLE
RolloverIT#testRolloverWithClosedIndexInAlias is failing

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#64921]
**Build scan**: https://gradle-enterprise.elastic.co/s/gbswxpml6kujk

**Repro line**:

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.indices.rollover.RolloverIT.testRolloverWithClosedIndexInAlias" \
  -Dtests.seed=DB5398BC05A28FB5 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-SV \
  -Dtests.timezone=Asia/Tashkent \
  -Druntime.java=8 \
  -Dtests.fips.enabled=true
```

**Reproduces locally?**: no

**Applicable branches**: `7.x`

**Failure history**:

This is the [first time this test has failed](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-3M,mode:relative,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.action.admin.indices.rollover.RolloverIT%22%20AND%20test:%22testRolloverWithClosedIndexInAlias%22'),sort:!(time,desc))).

**Failure excerpt**:

```
java.lang.AssertionError: CloseIndexResponse failed - not acked
Expected: <true>
     but: was <false>
	at __randomizedtesting.SeedInfo.seed([DB5398BC05A28FB5:B2BC1ACD6E1D733E]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:115)
	at org.elasticsearch.action.admin.indices.rollover.RolloverIT.testRolloverWithClosedIndexInAlias(RolloverIT.java:468)
```

**Comment by danhermann** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/67953
