### ISSUE TITLE
Named queries (_name) are inconsistent and the documentation is wrong

### ISSUE THREAD

**Issue by tstibbs** [elastic/elasticsearch#6496]
See http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/search-request-named-queries-and-filters.html, it says:
> Each filter and query can accept a `_name` in its top level definition.

However, not all queries/filters can accept a `_name`, e.g.
```json
{
  "query": {
    "simple_query_string": {
      "query": "bungalow",
      "fields": [
        "building_type"
      ],
      "_name": "blah"
    }
  }
}
```
returns you a `QueryParsingException[[index] [simple_query_string] unsupported field [_name]]`

---
 
Some queries let you put the `_name` in the top level definition (as the documentation suggests), while some insist that the `_name` is **not** in its "top level definition", but inside the field object, e.g.

valid:
```json
{
  "query": {
    "term": {
      "building_type": {
        "value": "bungalow",
        "_name": "blah"
      }
    }
  }
}
```
invalid:
```json
{
  "query": {
    "term": {
      "building_type": "bungalow",
      "_name": "blah"
    }
  }
}
```
It would make more sense to me if the `_name` was alongside the field name, rather than within it.

---

Some types are even inconsistent within themselves, e.g.

range query
```json
{
  "query": {
    "range": {
      "field1": {
        "gt": 10,
        "lt": 20,
        "_name": "range1"
      }
    }
  }
}
```
range filter
```json
{
  "query": {
    "constant_score": {
      "filter": {
        "range": {
          "field1": {
            "gt": 10,
            "lt": 20
          },
          "_name": "range1"
        }
      }
    }
  }
}
```

---

The documentation also says that when filters match the list of matches will be returned in an element called `matched_filters`, however it appears that they just show up in the `matched_queries` list. This even applies to filters supplied as part of the `filter` (as opposed to `query`) element of the search request body.

Note I'm testing these on 1.0.2 currently.

**Comment by javanna** [comment]
This has been discussed and fixed in #11744 as part of the query-refactoring effort which is now in the master branch (future 3.0 release).
