### ISSUE TITLE
System index plugin for fleet indices

### ISSUE THREAD

**Issue by ruflin** [elastic/elasticsearch#64971]
The Fleet data is moved out of the .kibana index as it is not using saved objects anymore and wants to have its own system indices. The number of system indices is 7-8 indices which are written by Fleet from Kibana but also the upcoming Fleet Server.

To get us started, it would be great to have system index plugin which maps to all `.fleet-*` indices. The kibana_system user should have access to these indices and in the future a fleet user. At the moment it is enough if superuser has access.

For the mapping it would be great if a simple template could be put into place that maps all fields to keyword by default like the default template for `metrics-*-*` as an example.

**Comment by gwbrown** [comment]
We've added a basic Fleet plugin in https://github.com/elastic/elasticsearch/pull/65275, so I'm going to close this issue. Any further required enhancements to the Fleet plugin should have separate issues opened for them.
