### ISSUE TITLE
RPM repository broken on RHEL5: «Error performing checksum»

### ISSUE THREAD

**Issue by gioele** [elastic/elasticsearch#6498]
Yum complains about wrong checksums when the RPM repository is used in RHEL 5:

>    $ yum list
>    Loaded plugins: rhnplugin, security
>    This system is receiving updates from RHN Classic or RHN Satellite.
>    elasticsearch-0.90/primary_db                            | 9.1 kB     00:00
>    http://packages.elasticsearch.org/elasticsearch/0.90/centos/repodata/primary.sqlite.bz2: [Errno -3] Error performing checksum
>    Trying other mirror.
>    Error: failure: repodata/primary.sqlite.bz2 from elasticsearch-0.90: [Errno 256] No more mirrors to try.

This problem has been dissected in this blog post: <http://prefetch.net/blog/index.php/2009/11/26/dealing-with-yum-checksum-errors/>.

The solution is to create the repositores using `createrepo` with the `-s sha1` option that enables the creation of SHA1 checksums instead of SHA256.

**Comment by sergei-maertens** [comment]
what's the status of this? I'm having the same problem on CentOS 5.11 and would prefer to install/update via yum instead of sources.

**Comment by spinscale** [comment]
Hey

I just checked this, and @electrical if right. Even though we change the `createrepo` call, we still call `gpg` with the wrong arguments. I would like to incorporate this fully into our built, so we need the possibility to configure this via `mvn` - I will ask the maven-rpm-plugin folks to support this feature, by allowing to configure the `%__gpg_sign_cmd` call.

In the meantime I will try to add this to the build by manually adding this to the `~/.rpmmacros`.

@sergei-maertens @gioele Do you know, if there is any disadvantage in using the old signatures or the sha1 hashing in `crearerepo`? After all there might be a reason for the change? (sorry I am not a packaging guru)

**Comment by spinscale** [comment]
So, from digging around a bit more there are two things. First, we need to have a custom GPG key, because the old rpm only seems to accept certain sized keys (no big ones), second we seem to need an own repository, which is only for those older versions. Not sure, how to integrate this in our build infra.

**Comment by spinscale** [comment]
Hey,

so we talked this through and decided to not support this for now, as it would make our automated build and release process far more complex (creating the RPM twice and then processing it differently, signing it with another key and have two different repositories). That said this does not mean it's set in stone for eternity.

A couple of workarounds are available if you are willing to create your own repo.

* Built elasticsearch with `mvn rpm:rpm` and it to your own repo (you can check the `build_repositories.sh` script in the elasticsearch for some help
* Grab the zip file and maybe create your own package using [fpm](https://github.com/jordansissel/fpm), if you do not care to much about rpm standards
