### ISSUE TITLE
Deleting a snapshot does not delete the associated files

### ISSUE THREAD

**Issue by blevine** [elastic/elasticsearch#65005]
**Elasticsearch version** (`bin/elasticsearch --version`):
Docker image elasticsearch:7.4.0

**JVM version** (`java -version`):
AdoptOpenJDK/OpenJDK 64-Bit Server VM/13/13+33

**Description of the problem including expected versus actual behavior**:
I've created a snapshot repo and snapshot using the Node.js API.  After calling deleteSnapshot, the snapshots
files still exist in the repo directory.

Expected: the files associated with the snapshot are deleted
Actual: the files associated with the snapshot still exist

**Steps to reproduce**:
To create snapshot:

```
    const result = await indexClient.snapshot.create(
      {
        repository: INDEX_REPO_NAME,
        snapshot: snapshotName,
        wait_for_completion: true, // May want this to be false in the future for long backups...
        body: {
          indices: this.opts.indexName,
          ignore_unavailable: false,
          include_global_state: false,
          metadata: {
            backup_ts: new Date().toISOString(),
            alias: this.opts.indexName,
            localIndexName: this.opts.indexNameOverride,
            fromUrl: this.opts.indexUrl
          }
        }
      })
```
To delete the snapshot:

```
      await indexClient.snapshot.delete(
        {
          repository: INDEX_REPO_NAME,
          snapshot: snapshotName
        }
      )
```

I know that the delete succeeds because if I don't call delete, the create fails with a duplicate snapshot error. Still I would expect the files associated with the snapshot to have been deleted.

**Comment by original-brownbear** [comment]
@blevine 

> the snapshots files still exist in the repo directory.

What do you mean by this? Which file(s) exactly do you see after the delete that should not be in the repository any longer?

**Comment by blevine** [comment]
After creating the snapshot repo, I see the repo's directory which is empty.  After creating a snapshot in that repo, I see something like the directory tree below in the repo's directory.  After deleting the snapshot, this directory tree still exists.

Also, after deleting the snapshot if I then create a snapshot in the same repo with the same name, I see a similar file tree except with index-1 and index-2 files in the root of the directory.  Each time I do this, I get new index-n files with n incremented.
```
.
├── index-0
├── index.latest
├── indices
│   └── Sa4zE8G0ReiylcfhHs-jhA
│       ├── 0
│       │   ├── __2Gz3HC97RWyfCoUV0ug2tQ
│       │   ├── __2TLkJkzoRsCJT13Y4jfPWQ
│       │   ├── __384CC2WcQE2d1UdQazNuLQ
│       │   ├── __3z-l-Kr3Rp6lED3KkE31zQ
│       │   ├── __4vv96fkpQ62HmbiWasUo5A
│       │   ├── __61D_PzqxT86_IXXfIzVdJw
│       │   ├── __7u5pOnOKQUSE402QSoT7tQ
│       │   ├── __9UQBfGrBTYSRBX7iT-MAAg
│       │   ├── __A7wRtmrMR8mWCy6I9x4IuA
│       │   ├── __CwN8wu2LSwK_1f9AGEFuvA
│       │   ├── __I8SZ3ACxSpemz8IGro9kIQ
│       │   ├── __KBjni3e5RK6wC3WcsyjIWA
│       │   ├── __KBkEx27VTWiJM9AC64d_kQ
│       │   ├── __OEYU4iFlTrGphthJu4sC-A
│       │   ├── __OGtn5yYfR5ShYMkOgOEieA
│       │   ├── __OaLc1MgpRqWyWrqk6ZqNMg
│       │   ├── __TgeYqrRCTd6VSHSlpnTlIA
│       │   ├── __WFJH86drRrGrTrOCLrpQ6w
│       │   ├── __WfDWJNxKRde5bfIcJo7Bjw
│       │   ├── __d39v9QWlR56Xvn30y7atjA
│       │   ├── __daZGdg4aSmqLGSsAvVD-EA
│       │   ├── __ep-eAk11RjeaTWECSXnFBw
│       │   ├── __ha_O_NdHSpm57WD0J8Dmpg
│       │   ├── __iLGds6hgSqeLDpr1ytzhbg
│       │   ├── __oIw-_CUXQxK72dbpH15Y2A
│       │   ├── __qvSz941RSZGOe1QVCaSQxQ
│       │   ├── __rJF2VYBuS6uEEppD39tpuQ
│       │   ├── __rvnkmHRDTVq2X8xPcYXdrw
│       │   ├── __vZgSoCxPTu2HYGaAPFC7zg
│       │   ├── __zVT3_GN9QsmTmMfPmBUK0Q
│       │   ├── index-0
│       │   └── snap-kfTHbaEkR327z9d-CQESIg.dat
│       └── meta-kfTHbaEkR327z9d-CQESIg.dat
├── meta-kfTHbaEkR327z9d-CQESIg.dat
└── snap-kfTHbaEkR327z9d-CQESIg.dat
```

**Comment by original-brownbear** [comment]
@blevine what you're seeing is expected in version `7.4`. We keep an extra `index-N` file around (keeping the last two).  Even if you delete all snapshots in the repository an empty `index-N` (like the one you posted) that references no indices or snapshots will be created. Same goes for the `indices` directory which is never deleted (but should be empty if there are no snapshots in the repository at all) and the `index.latest` file.
Unless we leak other files but the ones I mentioned above I don't think there's anything broken here.

**Comment by blevine** [comment]
Thanks for the explanation @original-brownbear. Is this behavior changed in later 7.x releases? The documentation for 7.10 for example states that the files will be deleted: https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-snapshot-api.html. For some reason I couldn't find 7.4 documentation for the delete snapshot API.

**Comment by original-brownbear** [comment]
No problem @blevine 

> Is this behavior changed in later 7.x releases?

Newer 7.x versions (`7.6+`) will only keep around a single `index-N` file. Otherwise the behavior remains unchanged (empty `indices` and `index.latest` files will also stick around). Completely deleting all contents of the repository even after removing all snapshots isn't something we can do on all repository types due to consistency guarantees of the underlying blob store when reusing file names so this behavior is unlikely to change in the foreseeable future.

I hope you don't mind that I'll close here for now as it doesn't look like there's anything broken.

**Comment by blevine** [comment]
Given your description, there's nothing broken.  However there's still a documentation bug because current doc states:

"When deleting a snapshot from a repository, Elasticsearch _deletes all files that are associated with the snapshot_ and not used by any other snapshots. All files that are shared with at least one other existing snapshot are left intact."
