### ISSUE TITLE
[DOCS] each term in the glossary should be linkable for ease of reference and sharing

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#65028]
In our glossary page:
https://www.elastic.co/guide/en/elasticsearch/reference/master/glossary.html

each term should have a link to allow ability to have a url that links straight to the specific term.
This allows very easy reference when sharing information about particular terms with others, by making it easy to provide a link directly to the term you want to reference.

**Comment by sidram05** [comment]
Can I work on this one ?

**Comment by jrodewig** [comment]
While not easily visible, these anchors already exist. Generally, the term anchor follows this convention:

`#glossary-<slugified-term>`

For example, the anchor for `warm phase` is `#glossary-warm-phase`. You can link directly to the term at https://www.elastic.co/guide/en/elasticsearch/reference/master/glossary.html#glossary-warm-phase

We're currently working on a redesign of the docs to make these anchors more obvious, but I think that's a separate issue.
