### ISSUE TITLE
SQL: Using CASE expression in COUNT aggregate fails

### ISSUE THREAD

**Issue by mason-sharp** [elastic/elasticsearch#65036]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): Linux 3.10.0-862.9.1.el7.x86_64 (using docker.elastic.co/elasticsearch/elasticsearch:7.6.1)

**Description of the problem including expected versus actual behavior**:

ERROR:  Does not know how to convert argument CASE(IfConditional[customer.c_birth_month{f}#106198 < 6[INTEGER],something[KEYWORD]],customer.c_salutation{f}#106213) for function COUNT(CASE(IfConditional[customer.c_birth_month{f}#106198 < 6[INTEGER],something[KEYWORD]],customer.c_salutation{f}#106213))

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. SELECT COUNT(DISTINCT (CASE WHEN "c_birth_month" < 6 THEN 'something' ELSE "c_salutation" END)) AS "my_count" FROM "customer";
 2. Same issue also without DISTINCT
 3.

**Provide logs (if relevant)**:

**Comment by costin** [comment]
I think this was fixed in a previous version - @bpintea can you please double check?

**Comment by bpintea** [comment]
This had been fixed in 7.8.0 by https://github.com/elastic/elasticsearch/pull/55241.
