### ISSUE TITLE
elasticsearch container start output warn log

### ISSUE THREAD

**Issue by like-inspur** [elastic/elasticsearch#65032]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.2

**Steps to reproduce**: start elasticsearch with docker 

**Description of the problem including expected versus actual behavior**:
I run elasticsarch with default config, container output log like below
```
{"type": "server", "timestamp": "2020-11-13T07:48:57,449Z", "level": "WARN", "component": "o.e.g.DanglingIndicesState", "cluster.name": "docker-cluster", "node.name": "e2333260fcf0", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
```

**Comment by romseygeek** [comment]
Thanks for opening the issue @like-inspur.  This should probably just be an INFO level output rather than a warning, given that you don't particularly need to do anything about it.

**Comment by DaveCTurner** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/65309.
