### ISSUE TITLE
[ML] Add support for search-time runtime fields to datafeeds

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#65055]
Since #64374 Elasticsearch has the option to have search-time runtime fields.

ML should allow these to be used in datafeeds.

The most obvious way to do it seems to be to add an optional `runtime_mappings` section to the datafeed config with the same structure as the `runtime_mappings` section of searches (as defined in #64374), then add this into the search the datafeed does when getting input data.

**Comment by davidkyle** [comment]
There are a few limitations when using RT fields in ml datafeeds

1. Performance will be impacted if the time field is a runtime field. Configurations of jobs/datafeeds that use runtime_mappings to create the time field will be rejected.
2. RT fields do no work with v1 Rollup searches. If the datafeed is querying a rollup index it will not start if RT fields are used.
3. RT fields in Cross Cluster Search require the remote cluster to be v7.11 or above. The datafeed will start and the search will fail in this case.

**Comment by benwtrent** [comment]
@davidkyle @droberts195 do we think this should stay open? Seems like we can close it.

**Comment by davidkyle** [comment]
Close it!
