### ISSUE TITLE
[ML] Add support for search-time runtime fields to data frame analytics

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#65056]
Since #64374 Elasticsearch has the option to have search-time runtime fields.

ML should allow these to be used in data frame analytics.

The most obvious way to do it seems to be to add an optional `runtime_mappings` section to the data frame analytics config with the same structure as the `runtime_mappings` section of searches (as defined in #64374), then add this into the search the data frame analytics job does when reindexing source data to the destination index.

However, after this initial step there is a choice of approaches.  For the destination index we could:

1. Make the search-time runtime fields on the source indices into indexed fields
2. Make the search-time runtime fields on the source indices into runtime fields stored in the destination index mappings
3. Keep the search-time runtime fields on the source indices as search-time runtime fields on the destination index

Some analysis of the pros and cons is needed before deciding which option is best.

**Comment by dimitris-athanasiou** [comment]
I am working on this following approach 2: allowing the user to provide search-time runtime fields to the config which are then becoming mapped runtime fields in the destination index.
