### ISSUE TITLE
[CI] Multiple builds fail because of the missing docker executables

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#65069]
**Build scan**: https://gradle-enterprise.elastic.co/s/rwlyl7vm7hlua

**Applicable branches**: `master`, `7.x`

**Failure history**:

There are [250 failures in the past week](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Docker%20(checked%20%5B/usr/bin/docker,%20/usr/local/bin/docker%5D)%20is%20required%20to%20run%20the%20following%20tasks:%20%0A*%0A*%0A*:distribution:docker:buildOssDockerImage%0A*%0Ayou%20can%20address%20this%20by%20attending%20to%20the%20reported%20issue,%20or%20removing%20the%20offending%20tasks%20from%20being%20executed.&search.relativeStartTime=P28D&search.tags=CI&search.timeZoneId=Europe/Berlin)

Following os/projects are affected
* windows-2016
* windows-2012-r2
* windows-2019
* opensuse-15-1-packaging
* centos-6-packaging
* centos-8-packaging
* debian-8-packaging
* oraclelinux-6-packaging
* oraclelinux-7-packaging
* sles-12-packaging
* sles-15-packaging

**Failure excerpt**:

```
Docker (checked [/usr/bin/docker, /usr/local/bin/docker]) is required to run the following tasks: 
:distribution:docker:buildDockerImage
:distribution:docker:buildAarch64DockerImage
:distribution:docker:buildUbiDockerImage
:distribution:docker:buildAarch64UbiDockerImage
:distribution:docker:buildOssDockerImage
:distribution:docker:buildAarch64OssDockerImage
you can address this by attending to the reported issue, or removing the offending tasks from being executed.
```

**Comment by mark-vieira** [comment]
Looks like this got resolved around November 18th. I can't be bothered to track down the specific PR though :wink:
