### ISSUE TITLE
Cannot run from sources : isSubtype UNKNOWN

### ISSUE THREAD

**Issue by Ierezell** [elastic/elasticsearch#65076]
**Elasticsearch version** (`bin/elasticsearch --version`):
Latest from github (16/11/2020)

**Plugins installed**: None, building error

**JVM version** (`java -version`): 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```
Linux 5.9.8-zen1-1-zen (Archlinux with zen kernel 5.9.8)
```

**Description of the problem including expected versus actual behavior**:
Cannot build elasticsearch from sources with gradle because the building script raise an : 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:plugin:monitoring:compileJava'.
> java.lang.AssertionError: isSubtype UNKNOWN
```
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. git clone https://github.com/elastic/elasticsearch.git/
 2. cd elasticsearch 
 3. ./gradlew run
 4. wait for it to initialize, compile and all...
 5. get a 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:plugin:monitoring:compileJava'.
> java.lang.AssertionError: isSubtype UNKNOWN
```

Thanks in advance for your help !

**Comment by cbuescher** [comment]
Hi @Ierezell,

Unfortunately Elasticsearch requires at least JDK 14 on master. This is also documenten in our [contribution guideline](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase). You can use JDK 11 at runtime but for compilation JDK 14 is required. I can reproduce your error using 11, but everything seems to work as expected on 14. I'm closing this but you can ask for advice and help in our  forums over at https://discuss.elastic.co if you have further questions around this.

**Comment by Ierezell** [comment]
Hi @cbuescher, 
Thanks for the quick response ! 

I had other versions of java which leads to error indicating i needed at least java 11. I will try right now with 14.
Thanks again and sorry for the stupid issue :)
