### ISSUE TITLE
EQL: potential between() optimizations

### ISSUE THREAD

**Issue by rw-access** [elastic/elasticsearch#65106]
We have a good recommendation to steer users away from potentially costly EQL functions, and to instead perform string manipulation with ingest node pipelines, logstash, or some other method that will manipulate the data pre-ingest.

I believe we convert `startswith` and `endswith` into the corresponding wildcard queries. There are a few potential optimizations we can do for `between`. This issue is not urgent AFAIC, so I'm just documenting it here for a backlog

Here are some transformations we could potentially make:

* `between(myfield, "foo", "bar") == "baz"` --> `wildcard(myfield, "*foobazbar*")` (assuming greedy=false)
* `wildcard(between(myfield, "foo", "bar"), "*b*a*z*")` --> `wildcard(myfield, "*foo*b*a*z*bar*"` (assuming greedy=false)

I'm not sure if these will always be more performant. If the query is already filtered enough ahead of time, and painless is only evaluated on a subset of results, that might still be better than leading and trailing wildcards. But if the underlying field is a wildcard type, then it might change the performance characteristics.

**Comment by wchaparro** [comment]
Superceded by ES|QL
