### ISSUE TITLE
index.routing.allocation.include  not work as document described

### ISSUE THREAD

**Issue by chenchuangc** [elastic/elasticsearch#65113]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.2.0

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_91"

**OS version** (`uname -a` if on a Unix-like system):
Linux   2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

as the document say that different attributes for ``` index.routing.allocation.include.xxx ``` are all should satisfied
>If you specify multiple filters, all conditions must be satisfied for shards to be relocated. For example, to move the test index to big nodes in rack1, you could specify:

```
PUT test/_settings
{
  "index.routing.allocation.include.size": "big",
  "index.routing.allocation.include.rack": "rack1"
}
```
the document is [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/shard-allocation-filtering.html#index-allocation-filters) 

but in my test i find that the test index will be relocated to nodes that have ever ``` big ```size OR  ```rack1``` attr

if i want to move the test index to big nodes in rack1, i should do like this 

```
PUT test/_settings
{
  "index.routing.allocation.require.size": "big",
  "index.routing.allocation.require.rack": "rack1"
}
```

**Comment by original-brownbear** [comment]
@chenchuangc thanks for reporting this. This wasn't documented properly indeed, I adjusted the documentation now via the linked PR.
