### ISSUE TITLE
Multiple shards are giving different results on same query

### ISSUE THREAD

**Issue by Alishma** [elastic/elasticsearch#65114]
Hi,

**Setup**

Fallowing is my ES setup.

- Using Elastic Cloud
- Have 3 shard with 3 replicas
- Size is 5 GB(3.2 millions documents)

**Problem Statement**

While performing the wildcard search, its giving a different result each time. I believe that the search is going to different shards and giving the fastest result first(score is same) .

If

1. I make my index with single shard instead of 3 shards for 3.2 million records(5 GB), will it impact the performance?
or

2. What is the other best way to query multiple shards with the same result all the time with faster response time (not the priority).

**PS** 
I've gone through the below article and I didn't get clear idea.

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-preference.html

https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html

Thanks in advance.

**Comment by cbuescher** [comment]
Hi @Alishma. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please provide additional information like what kind of query you are issuing exactly, what the documents look like you are expecting to match and what the actual results look like when opening an issue there. Many Thanks.
