### ISSUE TITLE
Remove suppressAccessChecks permission from repository-s3

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#65122]
This morning I was looking at [a problem reported on discuss](https://discuss.elastic.co/t/elasticsearch-cannot-find-a-non-existing-file/255636/) and I came to this content:

https://github.com/elastic/elasticsearch/blob/master/plugins/repository-s3/src/main/plugin-metadata/plugin-security.policy#L25-L36

Apparently, we can remove this permission when https://github.com/aws/aws-sdk-java/issues/766 is fixed. And this has been fixed a long time ago. I'm wondering then if this can be removed or if we should change the comment?

@tlrx Do you remember?

**Comment by tlrx** [comment]
AWS SDK 1.11.749 cannot run without the `suppressAccessChecks` permission because `InternalConfig` still uses a Jackson's `ObjectMapper` with the `ALLOW_FINAL_FIELDS_AS_MUTATORS` feature which requires this permission.

**Comment by dadoonet** [comment]
Should https://github.com/aws/aws-sdk-java/issues/766 be reopened or commented then?

**Comment by pugnascotia** [comment]
@tlrx I just found this issue because I am doing work on plugin installation. What is the path forward here?

**Comment by tlrx** [comment]
As far as I know this permission is still required, but the annoying logging traces have been muted in #62522
