### ISSUE TITLE
No Node Available

### ISSUE THREAD

**Issue by marcelopaesrech** [elastic/elasticsearch#6515]
Hi guys,

I'm having some problems with NoNodeAvailable. When the cluster is idle during some time the problem occurs (between 0:00 and 8:00 am). 

I saw the sockets log in the cluster and there is a lot of sockets opened (like 700 in one of them). And because of that I load-balancer node is throwing out of memory.

I'm using TranportClient to connect to cluster. My environment is:
- 15 ES nodes with 7 shards and 2 replicas (7 data nodes (16Gb each one), 4 load balancers(4Gb each one), 4 masters(4Gb each one)); 
- 8 clients pointing to the 4 load-balancer nodes.

When the cluster is being used (during the day), this problem does not happen, but every first connection of the day catch this error.

I created a discussion on Google Groups as follows:
https://groups.google.com/forum/#!searchin/elasticsearch/marcelopaesrech/elasticsearch/ZqypeTOguoM/8qunqmONggoJ

Best regards.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/10189
