### ISSUE TITLE
add truncate support for a index

### ISSUE THREAD

**Issue by easyice** [elastic/elasticsearch#65189]
when i want to change  type for some  filed in mapping, i should  reindex or bulk write to a new index，but，in my case，create an index can be costly，because：

1. i have more than 100 index need to reindex from remote every mouth
2. my cluster has 50 nodes and 10000 shards, when create a new index, the shards-stared RPC need  much more time for master node processing, the rpc has URGENT priority，He caused the other rpc to have no chance to execute, like put-mapping.

i want to reuse the old index,Don't delete it.if the truncate api can be support， i can  truncate then old index, including then all index segments, and mappings, then put new mapping, and write index to the old index

thanks

**Comment by DaveCTurner** [comment]
@easyice what version are you using? In particular if it's before 7.4.0 then you are missing https://github.com/elastic/elasticsearch/pull/44433 which considerably speeds up the processing of shard-started events in high-shard-count clusters.

**Comment by easyice** [comment]
thanks for replay，my cluster is 6.8.0, in this version the one shard-started event  need over 50 seconds for processing done, the cluster has 50000 shards.

let me test how much fast  on 7.4.0, thanks a lot

**Comment by easyice** [comment]
@DaveCTurner I tested on 7.6.0, #44433  and #47817 can solve the problem，so this issues can be closed
