### ISSUE TITLE
Intervals queries with use_field could match wrong documents

### ISSUE THREAD

**Issue by bperalta** [elastic/elasticsearch#65201]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.0 docker image

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_252"

**OS version** (`uname -a` if on a Unix-like system): Linux insight-bperalta.private.mesao.com 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

With specifics documents & queries using intervals query combining fields using different analyzers (with `use_field` parameter) a wrong document could match. After doing many tests, the query result could change when I update the stemmer parameters or the word_delimiter filter parameters but I did not find any logic...

**Steps to reproduce**:

 1. Create the index
```
curl -XPUT 'localhost:9200/test_fr' -H 'Content-Type: application/json' -d '{
    "settings": {
        "analysis": {
            "filter": {
                "worddelimiter": {
                    "type": "word_delimiter_graph",
                    "split_on_case_change": false,
                    "split_on_numerics": true
                },
                "french_stemmer": {
                    "type": "stemmer",
                    "language": "french"
                }
            },
            "analyzer": {
                "my_analyzer": {
                    "filter": [
                        "worddelimiter",
                        "french_stemmer"
                    ],
                    "type": "custom",
                    "tokenizer": "standard"
                },
                "standard_analyzer": {
                    "type": "standard",
                    "stopwords": "_french_"
                }
            }
        }
    },
    "mappings": {
        "properties": {
            "my_text": {
                "type": "text",
                "analyzer": "my_analyzer",
                "fields": {
                    "other": {
                        "type": "text",
                        "analyzer": "standard_analyzer"
                    }
                }
            }
        }
    }
}'
```

 2. Insert the attached document
```
curl -XPUT 'localhost:9200/test_fr/_doc/1' -H 'Content-Type: application/json' -d @test_fr_doc_1.json
```
[test_fr_doc_1.json.zip](https://github.com/elastic/elasticsearch/files/5560384/test_fr_doc_1.json.zip)

 3. Execute that query
```
curl -XPOST 'localhost:9200/test_fr/_search' -H 'Content-Type: application/json' -d '{
    "from": 0,
    "size": 10,
    "query": {
        "intervals": {
            "my_text": {
                "all_of": {
                    "ordered": false,
                    "max_gaps": 2,
                    "intervals": [
                        {
                            "match": {
                                "query": "Travaux de déconstruction",
                                "max_gaps": 2,
                                "ordered": false,
                                "use_field": "my_text.other"
                            }
                        },
                        {
                            "match": {
                                "query": "ouvrage",
                                "max_gaps": 0,
                                "ordered": false
                            }
                        }
                    ]
                }
            }
        }
    },
    "_source": false,
    "explain": true
}'
```

The document will match, but it shoud not.
The same test without the worddelimiter filter in the my_analyzer analyzer woks fine.
If I delete some parts of the document, it also works fine (of course I cancel parts without searched words).

**Comment by jimczi** [comment]
> The same test without the worddelimiter filter in the my_analyzer analyzer woks fine.

This is expected, the word delimiter graph should not be used in an index analyzer. Moreover the `use_field` option expects that the two fields (the original and the alias one) have the same tokenization, they can have different filters like one that stems and the other that doesn't but any filter that creates different paths should be avoided. 
I hope you don't mind if I close this issue but we reserve github for verified bugs and feature requests. If you have have further questions, the [discuss forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) is better suited to start this kind of discussion.
