### ISSUE TITLE
Index prioritization during recovery

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#6522]
ES currently does not have the ability to prioritize indices during recovery.  It would be useful for the node to recover certain shards first, using an algorithm chosen by the user.  Some possibilities could be 'smaller indices first' or 'larger indices first' or 'most recently created indices first'.  That would allow for fast recovery of a current day's log index (for example) to get that index green and ready for ingestion as soon as possible.

**Comment by garyelephant** [comment]
+10 for this

**Comment by simwood-simon** [comment]
+1

**Comment by faxm0dem** [comment]
A feature which addresses this at least partially has been [released in 1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/recovery-prioritization.html)

**Comment by clintongormley** [comment]
I think that users now have sufficient control over index recovery prioritization, so I'm going to close this one
