### ISSUE TITLE
Add test coverage for Elasticsearch distribution with quota aware filesystem plugin installed

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#65227]
As a follow up to folding the quota aware filesystem plugin in the Elasticsearch code base (see #61145) we want to additionally ensure we have some test coverage in place to make sure that we don't observe funny behavior when this plugin is installed, as will be the case in all Cloud deployments.

The intent here is not to add any additional tests specific to validating plugin functionality, only to exercise the existing full test suite against a distribution which includes the plugin. We have a similar test setup in CI which runs all tests using the default distribution (vs the integ-test or oss distro as is often used for non-xpack tests). This pattern will probably work well for this purpose as well and eventually we should extend this to be less specific to the quota-aware-fs plugin and more a model of what we deliver to cloud.

**Comment by pugnascotia** [comment]
We removed this plugin in #76352.
