### ISSUE TITLE
Some artifacts weren't released for 7.10.0

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#65247]
While building a plugin for 7.10.0 , we get this error:

```
> Task :loggerUsageCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':loggerUsageCheck'.
> Could not resolve all files for configuration ':loggerUsagePlugin'.
   > Could not find org.elasticsearch.test:logger-usage:7.10.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/elasticsearch/test/logger-usage/7.10.0/logger-usage-7.10.0.pom
```

Indeed it seems like the logger-usage artifact wasn't released for 7.10.0 - https://jcenter.bintray.com/org/elasticsearch/test/logger-usage/ , also https://mvnrepository.com/artifact/org.elasticsearch.test/logger-usage

Can you please get that fixed so we can push our 7.10.0 compatible plugins out?

**Comment by synhershko** [comment]
Related: #65177

**Comment by stefanobranco** [comment]
I dont assume anyone has found an easy workaround for this in the meantime? This pretty much blocks us from using 7.10 at all.

**Comment by rjernst** [comment]
Apologies @synhershko , we have been working on relaxing the requirements placed on plugin authors which currently must follow our coding guidelines. This is another case where the logger usage is questionable as a requirement for plugin authors, and we removed it thinking we had eradicated it from external use, but sadly, we were wrong.

Given the above workaround should work (please confirm if it does for you), and we have removed most precommit checks for external authors in 7.11 (https://github.com/elastic/elasticsearch/pull/65102), I don't think there is currently anything to do here.

**Comment by synhershko** [comment]
Indeed @rjernst that seems to have fixed it. Thank you so much for your responsiveness and help, again.
