### ISSUE TITLE
es7.8.0 run on docker with error: NoClassDefFoundError: org/elasticsearch/bootstrap/JNAKernel32Library

### ISSUE THREAD

**Issue by wushifeng** [elastic/elasticsearch#65246]
**Elasticsearch version** (`bin/elasticsearch --version`):7.8.0

**Plugins installed**: [no]

**JVM version** (`java -version`):8

**OS version** (`uname -a` if on a Unix-like system): docker container

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
+ elasticsearch.yml
cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.max_content_length: 500mb
bootstrap.memory_lock: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.elasticsearch.collection.enabled: true

+ docker-compose.yml
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: "elasticsearch"
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

**Provide logs (if relevant)**:
 $ docker logs elasticsearch -f
{"type": "server", "timestamp": "2020-11-19T07:07:28,623Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "fatal error in thread [main], exiting", 
"stacktrace": ["java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/JNAKernel32Library",
"at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:149) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.8.0.jar:7.8.0]",
"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.8.0.jar:7.8.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.8.0.jar:7.8.0]",
"Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.JNAKernel32Library",
"at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[?:?]",
"at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]",
"at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]",
"... 10 more"] }
fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/JNAKernel32Library
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:149)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.JNAKernel32Library
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more

**Comment by wushifeng** [comment]
**OS and docker verison**
$ cat /etc/lsb-release 
DISTRIB_ID=Deepin
DISTRIB_RELEASE="15.11"
DISTRIB_DESCRIPTION="Deepin 15.11 "
DISTRIB_CODENAME=stable
$ uname -a
Linux wushifeng-PC 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux
$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

So this bug maybe the os's problem？

But when I run on centos 7, and setting bootstrap.memory_lock: true , the container also cant startup.
so how to set this flag under docker container?

Thanks.

**Comment by rjernst** [comment]
Given that class is in the main jar, was there another error in the log indicating the class failed to initialize?

**Comment by wushifeng** [comment]
> Given that class is in the main jar, was there another error in the log indicating the class failed to initialize?
Not see any other error information. 

The class is in jar, the reason is os is https://www.deepin.org/zh/download/

**Comment by pugnascotia** [comment]
I tried replicating this in a CentOS 7 VM, and in Docker running inside the CentOS 7 VM, but I didn't see the exception reported here.

**Comment by wushifeng** [comment]
1 NoClassDefFoundError
On centos it's ok, but on https://www.deepin.org/zh/download/ this os, it has problem.

2 cannot compute used swap when total swap is 0 and free swap. this problem can ben found in this
https://discuss.elastic.co/t/warn-in-logs-cannot-compute-used-memory-swap/244417
It's a jdk's bug
