### ISSUE TITLE
[Aggregations] Need a deprecation message for the percentiles parameter not allowing duplicate values

### ISSUE THREAD

**Issue by cuff-links** [elastic/elasticsearch#65240]
## Summary 
When we perform a query in 7.x with an aggregation, the percentiles parameter allows for an array of numbers. As per the docs, in 8.0, all of those values must be unique. Currently, we allow for duplicate values but we should be getting a deprecation warning. There is no warning.

## Source
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-8.0.html#breaking_80_aggregations_changes

## How to Test
Run the following query in Dev Console:

```
GET latency/_search
{
  "size": 0,
  "aggs": {
    "load_time_outlier": {
      "percentiles": {
        "field": "load_time" ,
        "percents": [
          1,
          1,
          5,
          25,
          50,
          75,
          95,
          99
        ]
      }
    }
  }
}
```

Check the deprecation logs for a message.

**Comment by hendrikmuhs** [comment]
fixed by #65252
