### ISSUE TITLE
[REST API] Requests with unconsumed bodies should be rejected. 

### ISSUE THREAD

**Issue by cuff-links** [elastic/elasticsearch#65242]
# Summary
This is a regression of https://github.com/elastic/elasticsearch/pull/37504. 

# Environment
Kibana: 7.x (7.11)
Elasticsearch: 7.x (7.11)

# How To Test
Run the following command in console.
```
PUT test/_doc/1
{}
DELETE /test
{
  "query" : {
    "term" :  {
      "field" : "value"
    }
  }
}
```
The above is no longer rejected.  

Another example (which found this regression): 
```
POST /latency/_forcemerge
{
  "only_expunge_deletes": true,
  "max_num_segments": 1
}
```
Which since https://github.com/elastic/elasticsearch/pull/37504 should not be allowed. (related: https://github.com/elastic/elasticsearch/pull/30792)

# Screenie
http://g.recordit.co/bUGDVNyJue.gif

**Comment by jakelandis** [comment]
This might be due the description in https://github.com/elastic/elasticsearch/pull/44902 which states that content is consumed when we check the content length.
