### ISSUE TITLE
elasticsearch bool query should highlight does not match

### ISSUE THREAD

**Issue by zj619** [elastic/elasticsearch#65293]
**Elasticsearch version** (`bin/elasticsearch --version`):5.6.10

**Plugins installed**: []ik_smart

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):centos7

**Description of the problem including expected versus actual behavior**:
first search:
GET /xxx/_search
{
  "_source": {
    "includes": [
      "档案_邮箱"
    ]
  },
  "from": 0,
  "size": 10000,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "档案_邮箱": {
              "wildcard": "*step*",
              "boost": 1
            }
          }
        }
     
        
      ],
      "disable_coord": false,
      "adjust_pure_negative": true,
      "boost": 1
    }
  },

  "explain": true,
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ],
  "highlight": {
    "pre_tags": [
      "&lt;em&gt;"
    ],
    "post_tags": [
      "&lt;/em&gt;"
    ],
    "fields": {
     
      "档案_邮箱": {}
      
    }
  }
}

result is 
"hits": [
      {
        "_shard": "[xxx][0]",
        "_node": "AaYfkGuvQ0WGfD9C6J35ag",
        "_index": "janusgraph_dangan_newmix1107",
        "_type": "dangan_newmix1107",
        "_id": "j1k",
        "_score": 1,
        "_source": {
          "档案_邮箱": [
            "374792241@163.com",
            "588331216@qq.com",
            "136746003@sohu.com",
            "253139691@qq.com",
            "143205689@sohu.com",
            "410415030@sohu.com",
            "Stepha"
          ]
        },
        "highlight": {
          "档案_邮箱": [
            "&lt;em&gt;Stepha&lt;/em&gt;"
          ]
        },

while when is use the following should, the expected value 'Stepha'  does not be hightlighted

GET /xxx/_search
{
  "_source": {
    "includes": [
      "档案_邮箱"
    ]
  },
  "from": 0,
  "size": 10000,
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "档案_邮箱": {
              "wildcard": "*step*",
              "boost": 1
            }
          }
        },
        {
          "wildcard": {
            "档案_邮箱": {
              "wildcard": "*qq*",
              "boost": 1
            }
          }
        },
        {
          "wildcard": {
            "档案_邮箱": {
              "wildcard": "*sohu*",
              "boost": 1
            }
          }
        }
     
        
      ],
      "disable_coord": false,
      "adjust_pure_negative": true,
      "boost": 1
    }
  },

  "explain": true,
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ],
  "highlight": {
    "pre_tags": [
      "&lt;em&gt;"
    ],
    "post_tags": [
      "&lt;/em&gt;"
    ],
    "fields": {
     
      "档案_邮箱": {}
      
    }
  }
}

result is 
"hits": [
      {
        "_shard": "[xxx][0]",
        "_node": "AaYfkGuvQ0WGfD9C6J35ag",
        "_index": "janusgraph_dangan_newmix1107",
        "_type": "dangan_newmix1107",
        "_id": "j1k",
        "_score": 3,
        "_source": {
          "档案_邮箱": [
            "374792241@163.com",
            "588331216@qq.com",
            "136746003@sohu.com",
            "253139691@qq.com",
            "143205689@sohu.com",
            "410415030@sohu.com",
            "Stepha"
          ]
        },
        "highlight": {
          "档案_邮箱": [
            "588331216@&lt;em&gt;qq.com&lt;/em&gt;",
            "136746003@&lt;em&gt;sohu.com&lt;/em&gt;",
            "253139691@&lt;em&gt;qq.com&lt;/em&gt;",
            "143205689@&lt;em&gt;sohu.com&lt;/em&gt;",
            "410415030@&lt;em&gt;sohu.com&lt;/em&gt;"
          ]
        },
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Hi @zj619 , this doesn't reproduce in 7.10 so the bug has likely been fixed sometime since 5.6.10.  We're not backporting fixes to the 5.x line any more, so we'd recommend that you upgrade.
