### ISSUE TITLE
Need to remove two Node out of three node Elasticsearch cluster

### ISSUE THREAD

**Issue by suman616** [elastic/elasticsearch#65305]
Hi Team,

Need guidelines for how to remove two Nodes out of three Node in Elastic Cluster without data loss

we have install Elasticsearch in single node but it has connected three node which is early install still it's taking part of current elastic environment.

Have checked bring down two node's which is not of installation , we can see their data loss in my application it's  around 40% data  missing .

need Guidelines how to move all the data into ONE Node which is part of our installation.

Regards,
suman k

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by suman616** [comment]
@ DaveCTurner 
yeah sure you can close this issue .. Thanks for your assistance
