### ISSUE TITLE
SQL query not properly applying some operators

### ISSUE THREAD

**Issue by psanz-estc** [elastic/elasticsearch#65322]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
SQL query is properly translating all the operators when the query combine several conditions

**Steps to reproduce**:

It can be verified by using: https://demo.elastic.co/app/dev_tools#/console?load_from=https:%2F%2Fs3.us-east-2.amazonaws.com%2Fdemo.elastic.co%2Fquery_12.json&_g=()

1) Base query, shows first 3 row:
```
POST _sql?format=csv
{
"query":"SELECT FlightNum FROM flights ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
00882F6
009NIGR
00CGX81
```
2) Add `where` clause to unselect first row:
```
POST _sql?format=csv
{
"query":"SELECT FlightNum FROM flights WHERE FlightNum <> '00882F6' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
009NIGR
00CGX81
00DRRXR
```

Notice `00882F6` is not listed

3) Add `where` clause which does not change result set:
```
POST _sql?format=csv
{
"query":"SELECT FlightNum FROM flights WHERE timestamp >= '2010-06-18T22:58:43.000Z' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
00882F6
009NIGR
00CGX81
```

4) Combine both conditions yields a **wrong result**:
```
POST _sql?format=csv
{
"query":"SELECT FlightNum FROM flights WHERE timestamp >= '2010-06-18T22:58:43.000Z' AND FlightNum <> '00882F6' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
00882F6
009NIGR
00CGX81
```

Notice `00882F6` is there,  but should not be listed

Looking at the output of the `translate` endpoint, the query doesn't include any MUST_NOT 

```
POST _sql/translate
{
"query":"SELECT FlightNum FROM flights WHERE timestamp >= '2010-06-18T22:58:43.000Z' AND FlightNum <> '00882F6' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
{
  "size" : 3,
  "query" : {
    "range" : {
      "timestamp" : {
        "from" : "2010-06-18T22:58:43.000Z",
        "to" : null,
        "include_lower" : true,
        "include_upper" : false,
        "time_zone" : "Z",
        "boost" : 1.0
      }
    }
  },
  "_source" : {
    "includes" : [
      "FlightNum"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "FlightNum.keyword" : {
        "order" : "asc",
        "missing" : "_last",
        "unmapped_type" : "keyword"
      }
    }
  ]
}
```

Using `!=` doesn't work either... But `=` is properly translated:

```
POST _sql/translate
{
"query":"SELECT FlightNum FROM flights WHERE timestamp >= '2010-06-18T22:58:43.000Z' AND FlightNum = '00882F6' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
{
  "size" : 3,
  "query" : {
    "bool" : {
      "must" : [
        {
          "range" : {
            "timestamp" : {
              "from" : "2010-06-18T22:58:43.000Z",
              "to" : null,
              "include_lower" : true,
              "include_upper" : false,
              "time_zone" : "Z",
              "boost" : 1.0
            }
          }
        },
        {
          "term" : {
            "FlightNum.keyword" : {
              "value" : "00882F6",
              "boost" : 1.0
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "FlightNum"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "FlightNum.keyword" : {
        "order" : "asc",
        "missing" : "_last",
        "unmapped_type" : "keyword"
      }
    }
  ]
}


```

**Provide logs (if relevant)**:

**Workaround**:

As a workaround, we can use the date not as a string in the `where`clause:

`WHERE timestamp >= CAST ('2010-06-18T22:58:43.000Z' AS DATETIME)`

That gets properly translated:

```
POST _sql/translate
{
"query":"SELECT FlightNum FROM flights WHERE  timestamp >= CAST ('2010-06-18T22:58:43.000Z' AS DATETIME) AND FlightNum != '00882F6' ORDER BY FlightNum LIMIT 3"
}

RESPONSE
************
{
  "size" : 3,
  "query" : {
    "bool" : {
      "must" : [
        {
          "range" : {
            "timestamp" : {
              "from" : "2010-06-18T22:58:43.000Z",
              "to" : null,
              "include_lower" : true,
              "include_upper" : false,
              "time_zone" : "Z",
              "format" : "strict_date_time",
              "boost" : 1.0
            }
          }
        },
        {
          "bool" : {
            "must_not" : [
              {
                "term" : {
                  "FlightNum.keyword" : {
                    "value" : "00882F6",
                    "boost" : 1.0
                  }
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "FlightNum"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "FlightNum.keyword" : {
        "order" : "asc",
        "missing" : "_last",
        "unmapped_type" : "keyword"
      }
    }
  ]
}

```

**Comment by palesz** [comment]
Thanks for the awesome bug report, taking a look.

**Comment by palesz** [comment]
Good news in the bad news is that I can reproduce this problem with a unit test. Taking a deeper dive.


Unit test in the `QueryTranslator` on the `master` branch:

    public void testBug() {
        PhysicalPlan p = optimizeAndPlan("SELECT keyword FROM test WHERE date >= '2010-06-18T22:58:43.000Z' AND keyword <> '00882F6' ORDER BY keyword LIMIT 3");
        assertEquals(EsQueryExec.class, p.getClass());
    }

Reveals the following query translation process:

    [2020-11-21T05:21:22,837][DEBUG][o.e.x.s.p.QueryFolder    ] [testBug] Tree transformation took 48ms
    LimitExec[3[INTEGER]]                                                        ! EsQueryExec[test,{
    \_OrderExec[[Order[test.keyword{f}#9,ASC,LAST]]]                             !   "query" : {
      \_ProjectExec[[test.keyword{f}#9]]                                         !     "range" : {
        \_FilterExec[test.date{f}#10 >= 2010-06-18T22:58:43.000Z[KEYWORD],false] !       "date" : {
          \_EsQueryExec[test,{                                                   !         "from" : "2010-06-18T22:58:43.000Z",
      "_source" : false,                                                         !         "to" : null,
      "stored_fields" : "_none_",                                                !         "include_lower" : true,
      "sort" : [                                                                 !         "include_upper" : false,
        {                                                                        !         "time_zone" : "Z",
          "_doc" : {                                                             !         "boost" : 1.0
            "order" : "asc"                                                      !       }
          }                                                                      !     }
        }                                                                        !   },
      ]                                                                          !   "_source" : false,
    }]                                                                           !   "stored_fields" : "_none_",
                                                                                 !   "docvalue_fields" : [
                                                                                 !     {
                                                                                 !       "field" : "keyword"
                                                                                 !     }
                                                                                 !   ],
                                                                                 !   "sort" : [
                                                                                 !     {
                                                                                 !       "keyword" : {
                                                                                 !         "order" : "asc",
                                                                                 !         "missing" : "_last",
                                                                                 !         "unmapped_type" : "keyword"
                                                                                 !       }
                                                                                 !     }
                                                                                 !   ]
                                                                                 ! }]

**Comment by palesz** [comment]
Seems the problem is somewhere here:

```
[2020-11-21T05:21:22,705][TRACE][o.e.x.s.o.Optimizer      ] [testBug] Rule optimizer.OptimizerRules$CombineBinaryComparisons applied
Limit[3[INTEGER]]                                                                                            = Limit[3[INTEGER]]
\_OrderBy[[Order[test.keyword{f}#9,ASC,LAST]]]                                                               = \_OrderBy[[Order[test.keyword{f}#9,ASC,LAST]]]
  \_Project[[test.keyword{f}#9]]                                                                             =   \_Project[[test.keyword{f}#9]]
    \_Filter[test.date{f}#10 >= 2010-06-18T22:58:43.000Z[KEYWORD] AND test.keyword{f}#9 != 00882F6[KEYWORD]] !     \_Filter[test.date{f}#10 >= 2010-06-18T22:58:43.000Z[KEYWORD]]
      \_EsRelation[test][bool{f}#6, int{f}#7, text{f}#8, keyword{f}#9, date{..]                              =       \_EsRelation[test][bool{f}#6, int{f}#7, text{f}#8, keyword{f}#9, date{..]
```

**Comment by palesz** [comment]
The first issue is that `OptimizerRules$CombineBinaryComparisons` tries to combine the `test.date{f}#10 >= 2010-06-18T22:58:43.000Z[KEYWORD]` and `test.keyword{f}#9 != 00882F6[KEYWORD]` that are both BinaryComparisons, but for different fields (left side is NOT the same as the right field). But the code does not check it. It sees that the right side of the negation is a keyword (string) that lexically before the right side of the first expression `2010-06-18T22:58:43.000Z[KEYWORD]`, so it thinks the negation can be dropped from the `AND`. This is of course incorrect.

**Comment by magicwerk** [comment]
Can you think of a workaround by writing the query in a different way to get a correct result?
Or is the only option to wait for a bug fix?

**Comment by palesz** [comment]
For this particular query (and where you have `!=` in the query) using `field NOT IN ('<value>')` instead of `field != '<value>'` is a good workaround. At the moment I am not sure about all the possible where clauses and conjunctions that might be impacted though.

**Comment by costin** [comment]
In case it was overlooked another workaround (and more readable) is in the issue description - namely casting the date in string format to a date.
