### ISSUE TITLE
Make it easier to define enum settings

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#65335]
We have a few settings that accept a fixed set of string values, like `index.routing.allocation.enable` and `index.translog.durability`. It could be nice to provide a built-in way of creating these 'enum settings', in line with other factory methods we have like `boolSetting`. This would create a standard, robust way to validate + parse these settings, instead of relying on 'switch' statements as we currently do in some places.

**Comment by AlexAxeman** [comment]
I'll take a stab at this as first issue.

**Comment by Edu93Jer** [comment]
Hi guys, I am new at open source and would like to contribute to the project, this issue looks find to get started, but please guys could you please let me know how is it going? I saw @AlexAxeman  has started, but any update, can I help with something, how should I start working on it, please could you explain to me a little more @jtibshirani so I can get the full context, or look at where is the issue exactly

**Comment by AlexAxeman** [comment]
Hi @Edu93Jer. I have an implementation ready, performing last few checks to make sure everything is in order. I'll have a PR up just after christmas.
