### ISSUE TITLE
gradlew run --debug-jvm fail -7.8.0

### ISSUE THREAD

**Issue by wushifeng** [elastic/elasticsearch#65344]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.8.0
https://github.com/elastic/elasticsearch/releases/tag/v7.8.0

**Plugins installed**: []
no

**JVM version** (`java -version`):
jdk-14.0.1

**OS version** (`uname -a` if on a Unix-like system):
centos 7.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
1 download and unzip https://github.com/elastic/elasticsearch/releases/tag/v7.8.0
2 export JAVA_HOME=/opt/dev/jdk-14.0.1/;./gradlew run --debug-jvm --info
failed info is bleow
[ If run this: export JAVA_HOME=/opt/dev/jdk-14.0.1/;./gradlew run ,  all is ok]

**Provide logs (if relevant)**:

> Task :extractElasticsearchLinux7.8.0-SNAPSHOT UP-TO-DATE
Caching disabled for task ':extractElasticsearchLinux7.8.0-SNAPSHOT' because:
  Build cache is disabled
  Caching has not been enabled for the task
Skipping task ':extractElasticsearchLinux7.8.0-SNAPSHOT' as it is up-to-date.
:extractElasticsearchLinux7.8.0-SNAPSHOT (Thread[Daemon worker Thread 4,5,main]) completed. Took 4.962 secs.
:run (Thread[Daemon worker Thread 4,5,main]) started.

> Task :run FAILED
Caching disabled for task ':run' because:
  Build cache is disabled
Task ':run' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Running elasticsearch in debug mode, node{::runTask-0} expecting running debug server on port 5005
Starting `node{::runTask-0}`
Written config file:/opt/work/es/elasticsearch/build/testclusters/runTask-0/config/elasticsearch.yml for node{::runTask-0}
Starting process 'command './bin/elasticsearch-keystore''. Working directory: /opt/work/es/elasticsearch/build/testclusters/runTask-0/distro/7.8.0-DEFAULT Command: ./bin/elasticsearch-keystore create
Successfully started process 'command './bin/elasticsearch-keystore''
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [open/src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
:run (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.486 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command './bin/elasticsearch-keystore'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

**Comment by cbuescher** [comment]
> Running elasticsearch in debug mode, node{::runTask-0} expecting running debug server on port 5005

Your IDE needs to listen to that port for debug mode. Please consult TESTING.asciidoc for more information. In general, question like these are better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead if you have furhter trouble. Many thanks.
