### ISSUE TITLE
Allow keyword_marker filter to be updateable

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#65355]
The [keyword_marker filter](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-keyword-marker-tokenfilter.html) allows for a `keyboard_path` configuration setting, but does not seem to support the `updateable` flag and thus cannot be reloaded via the [reload search analyzers API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-reload-analyzers.html).

To reproduce create a `config/analysis/example_word_list.txt` file containing

```text
experience
sample
```

Then run the following in dev-tools

```
DELETE test_index

PUT /test_index
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "search_synonyms": {
            "tokenizer": "whitespace",
            "filter": [
              "my_custom_keyword_marker_filter",
              "porter_stem"
            ]
          }
        },
        "filter": {
          "my_custom_keyword_marker_filter": {
            "type": "keyword_marker",
            "keywords_path": "analysis/example_word_list.txt",
            "updateable": true
          }
        }
      }
    }
  }
}

# cat example_word_list.txt
# experience 
# sample

# sample and experience are untouched
GET test_index/_analyze
{
"text": "this is a experience sample",
"analyzer": "search_synonyms"
}

# Now remove the `sample` line from the file and reload
POST /test_index/_reload_search_analyzers

# retry, sample should be `sampl` now if updateable, but remains sample
GET test_index/_analyze
{
"text": "this is a experience sample",
"analyzer": "search_synonyms"
}
```

Another issue with this is, that anything can be configured in `my_custom_keyword_marker_filter` and thus setting/believing the `updateable` parameters works can be misleading.

**Comment by cbuescher** [comment]
I can see the benefit of being able to update the `keyword_marker` list used for search analyzers without node shutdown.
In many ways this resource file is comparable to a synonym list. However it would be the first non-synonym filter that would be
`updateable` so I think this request needs some more inspection and discussion. As far as implementation goes it should be sufficient
to wire the "updateable" setting in the same way as we do for synonym filters.
