### ISSUE TITLE
[CI] WatcherUtilsTests.testDeserializeSearchRequest failing reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#65397]
Looks like this test has just started failing frequently.

**Build scan**:
https://gradle-enterprise.elastic.co/s/hst2mas3she2e/tests/:x-pack:plugin:watcher:test/org.elasticsearch.xpack.watcher.support.WatcherUtilsTests/testDeserializeSearchRequest#1

**Repro line**:
./gradlew ':x-pack:plugin:watcher:test' --tests "org.elasticsearch.xpack.watcher.support.WatcherUtilsTests.testDeserializeSearchRequest" -Dtests.seed=18E90D4845E5B676 -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=Pacific/Kiritimati -Druntime.java=11

**Reproduces locally?**:
Yes. Here's my [local build scan](https://gradle-enterprise.elastic.co/s/k2sgzq7duct24).

**Applicable branches**:
Seeing this happen in `master`, `7.x` and `7.10`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.watcher.support.WatcherUtilsTests&tests.sortField=FAILED&tests.test=testDeserializeSearchRequest&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.watcher.support.WatcherUtilsTests > testDeserializeSearchRequest FAILED
    java.lang.AssertionError: 
    Expected: <IndicesOptions[ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=true, expand_wildcards_closed=true, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=false, ignore_aliases=false, ignore_throttled=false]>
         but: was <IndicesOptions[ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=true, expand_wildcards_closed=true, expand_wildcards_hidden=true, allow_aliases_to_multiple_indices=true, forbid_closed_indices=false, ignore_aliases=false, ignore_throttled=false]>
        at __randomizedtesting.SeedInfo.seed([18E90D4845E5B676:A71DDD38CB82959B]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.watcher.support.WatcherUtilsTests.testDeserializeSearchRequest(WatcherUtilsTests.java:211)
```

**Comment by mark-vieira** [comment]
This is failing often and reproducibly so I've muted this test in 5b143b40bf05e1a13c12bfaf8efb7af70f636379.

**Comment by mark-vieira** [comment]
Muted in `7.x` (5b143b40bf05e1a13c12bfaf8efb7af70f636379) and `7.10` (5b143b40bf05e1a13c12bfaf8efb7af70f636379) as well.

**Comment by martijnvg** [comment]
#65379 should fix this test failure.

**Comment by jaymode** [comment]
#65379 has been merged and backported.
