### ISSUE TITLE
Tribe nodes joining two clusters with the same name

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#6539]
A customer has requested the ability for a tribe node to span two clusters with the same name.  This particular request is for use in an environment with a legacy cluster and a new cluster being brought online to replace it, but I could see the same feature being used to span two different datacenters in the future.

**Comment by javanna** [comment]
This is not possible with multicast discovery, cause the tribe node has to have access to both clusters and needs to be able to distinguish between the two. 

That said, it works with unicast discovery out of the box. Let's say the two clusters are on separate networks, the tribe node has access to both and points to them this way:

```
tribe.t1.discovery.zen.ping.unicast: tribe1:9300
tribe.t2.discovery.zen.ping.unicast: tribe2:9300
```

there is not even need to specify the cluster name for the tribe node configuration, but only the unicast addresses, the tribes can have whatever node, even the same.

@seang-es could you please let me know if my answer addresses your concerns?

**Comment by javanna** [comment]
pign @seang-es could you please have a look at my answer?

**Comment by clintongormley** [comment]
No more info. Closing
