### ISSUE TITLE
Auto throttle on Force Merge

### ISSUE THREAD

**Issue by easyice** [elastic/elasticsearch#65403]
force merge is very useful for time-based indices, but it use a lot of cpu, I hope it doesn't have any impact on the indexing or searching，Because my clusters used to some  online service，it needs always low latency . if a force merge can be throttle when system cpu% greater than some threshold，for instance 80%,we will never worry about the impact of  searching or indexing

**Comment by mayya-sharipova** [comment]
@easyice Thank you for submitting an issue.
In terms of CPU, force merge is using a dedicated [threadpool](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html) with a size of 1.  Indexing and searching have their own dedicated threadpools.

So if you multicore CPU, for forcemerge operation using just 1 thread when running should not be a big issue for CPU.

Futhermore, we can recommend to allocate your online low latency services to "hot" nodes, while time-based indices that need force merge can be moved to separate "warm" nodes. This should completely illuminate any interferences between force merge and search/indexing operations in terms of CPU.

**Comment by easyice** [comment]
@mayya-sharipova Thank you for reply

my server have multicore CPU，it  usually have more idle of CPU%，so we can  perform multiple merges in parallel ,But system idle is not periodic, so i want to pause the merges when system is busy, In other words， only run it when system is idle.

in my case, the cluster is used of ad  services, all the indices is hot, the query of the older indices must keep a low latency

**Comment by DaveCTurner** [comment]
> in my case, the cluster is used of ad services, all the indices is hot, the query of the older indices must keep a low latency

In Elasticsearch terms, "hot" means roughly "receiving indexing", and in that sense you should never force-merge a hot index. Warm nodes can still deliver excellent search performance, as long as they have appropriate hardware and configuration.

Additionally, force-merging is already automatically throttled in terms of its IO bandwidth. This makes more sense than CPU throttling since IO is usually the limiting factor, and it only uses a single thread anyway. Are you raising this issue because you are experiencing problems with the existing auto-throttle, or is it more of a theoretical concern? If you're experiencing problems, you will need to describe them in more detail.

**Comment by easyice** [comment]
ok, I have about 1000 clusters， in some cluster，i perform multiple  forcemerge at night（single forcemerge is to slow），i can see，The merge USES more CPU than IO，when the multiple  forcemerge is running, and my users suddenly perform a lot of aggregation or indexing, i can't pause or cancel the forcemerge.

**Comment by DaveCTurner** [comment]
How many CPUs are allocated to each node in your 1000-cluster estate?

**Comment by easyice** [comment]
We deployed on physical server，the server has 48 or 96 cpu core, and 256G\~1TB memory ，we start 1~4 nodes on the server, each node has 31GB JVM memory, and share the cpu cores

````
Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz

cat /proc/cpuinfo| grep "processor"| wc -l
48

cat /proc/cpuinfo| grep "cpu cores"| uniq
cpu cores	: 12
````

**Comment by DaveCTurner** [comment]
Can you help us understand more clearly how ≤4 force-merge threads running on such a powerful machine has a significant operational impact?

**Comment by DaveCTurner** [comment]
> Additionally, force-merging is already automatically throttled in terms of its IO bandwidth.

I was mistaken here, apologies. I read the code more closely and discovered that today's auto-throttle applies only to regular merges and not force-merges. Today we don't expose any control over force-merge throttling in Elasticsearch, although the option to do so is available in Lucene. IMO it'd be reasonable to expose this option, or else introduce some kind of automatic mechanism to constrain force-merges too. It's definitely possible for a single thread to consume all your IO bandwidth which would have an operational impact.

**Comment by easyice** [comment]
Thanks for @DaveCTurner . Currently ,the node run single thread for forcemerge, It will not have a significant impact on the CPU

it's my problem ,didn't make it clear,I'm assuming that forcemerge can be run in multithreaded. i understand, single thread makes things easier , but sometimes slower

I have no more questions，thanks all ❤️

**Comment by DaveCTurner** [comment]
We discussed this in the Lucene sync yesterday and decided that exposing Lucene's force-merge throttle as an Elasticsearch setting on indices.

**Comment by easyice** [comment]
Great！
and also, can multithreading forcemerge be considered? like hadoop hbase , the number of merge threads  can be configured

**Comment by DaveCTurner** [comment]
> can multithreading forcemerge be considered?

You can already increase the number of force-merge threads if you want and you have the resources to cope with it. Multithreading a single force-merge is something the Lucene folks have considered (see https://issues.apache.org/jira/browse/LUCENE-8580) but it turned out not to help very much.

**Comment by easyice** [comment]
Thanks for DaveCTurner ,I will  try to run parallel force-merge on different shards on one node, and try and see if it works

**Comment by piyushdaftary** [comment]
> Thanks for DaveCTurner ,I will try to run parallel force-merge on different shards on one node, and try and see if it works

@easyice : Were you able to run parallel force-merge on different shards of **same index** ? If Yes, can you please share how ?

**Comment by easyice** [comment]
@piyushdaftary  yes, I'm coding this feature in my branch, let TransportXXXAction extends from TransportBroadcastReplicationAction，just like refresh action，let shard level action run parallel  in thread pool. so ,if multiple shard of same index on one node, the forcemerge can be run  parallel

 when  parallel force-merge  running,I will auto throttle them by system metic

**Comment by easyice** [comment]
It is not an important issue, so i close the issue
