### ISSUE TITLE
QL: Refactor QueryTranslation tests

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#65417]
The query translation tests in QL (`QueryTranslatorTests`) and SQL(some bits of `QueryFolderTests`) are done manually which makes them more complicated than they have to be.
Instead of manually extracting the query string, replacing and then comparing it with a string, the test can do this automatically and assert the strings based on an external file based on the approach taken in EQL (`QueryFolderOkTests`) a file that however has an incorrect name.

The two approaches need to be consolidated:
- [ ] Use `QueryTranslatorTests` as a name for testing query translation
- [ ] Move QL and SQL tests from a manual approach to a declarative approach
- [ ] Keep any programmatic test that doesn't just do string comparison into its own test suite

**Comment by soarescaique** [comment]
Can I work on this?

**Comment by palesz** [comment]
Hello @soarescaique! Thank you for the interest, but we already assigned this work within the team.

**Comment by matriv** [comment]
`master` : 58e74ed037d7c967072073792806b74f6065a6db
`7.x` : 5766c7e45a8bdbb2a3c39760909d2fed7248fbd7
`7.13` : 64c06c83cbed470be170543fc7a6509f99ebc6fd
