### ISSUE TITLE
indices.memory.index_buffer_size optimization

### ISSUE THREAD

**Issue by EricMCornelius** [elastic/elasticsearch#6543]
https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/indices/memory/IndexingMemoryController.java#L238

Current, a shard will get a percentage of the indexing buffer on a node allocated unless it is  fully closed.  A potentially useful optimization would be to prevent allocating an indexing buffer unless the shard is actually writable.  Namely

index.blocks.read_only

Should not be set to true for the given shard in question.  This may be quite beneficial in environments where there are a large number of shards per node.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/14121
