### ISSUE TITLE
Specifying the default_search analyzer no longer works for Elasticsearch 7.10.0

### ISSUE THREAD

**Issue by cgoller** [elastic/elasticsearch#65434]
It seams that instead of the specified default_search analyzer the default index analyzer is also used for search. 
Simple example:

PUT my_index
{
  "settings":{
    "analysis":{
      "analyzer":{
        "default": {"type": "simple"},
        "default_search": {"type": "german"}
      }
    }
  },
  "mappings":{
    "properties":{
      "body_explicit": {
        "type":"text", "analyzer" : "simple", "search_analyzer": "german"
      },
      "body_default": {
        "type":"text"
      }
    }
  }
}

PUT my_index/_doc/1
{
   "body_explicit":"Ich lese die Bücher",
   "body_default":"Ich lese die Bücher"
}

Searching für "Bücher" should never produce doc 1 as hit since the search analyzer reduces "Bücher" to "buch" and the index analyzer leaves it untouched. However, if you search on body_default, you get doc 1. You don't get it if you search on body_explicit.

GET my_index/_search
{
  "query": {
    "query_string": {
    "fields" : ["body_explicit"],
    "query": "Bücher"
    }
  },
  "_source": ["body_default"],
  "highlight": {
    "require_field_match": true,
    "fields": {
      "body_default" : {
            "type" : "unified", "no_match_size" : 100, "fragment_size": 100, "number_of_fragments" : 1
      },
      "body_explicit" : {
            "type" : "unified", "no_match_size" : 100, "fragment_size": 100, "number_of_fragments" : 1
      }
    }
  }
}

**Comment by mayya-sharipova** [comment]
@cgoller Thank you for opening the issue.

I can confirm the bug. Indeed, `analysis.analyzer.default_search index setting` is not applied during search for a field `body_default` as it is supposed to.
