### ISSUE TITLE
Java High-Level Rest Client [7.10] PutIndexTemplateRequest doesn't support "composed_of"

### ISSUE THREAD

**Issue by bosakm** [elastic/elasticsearch#65453]
The version 7.10 PutIndexTemplateRequest classes does not support the new (added 7.8 release) "composed_of" List array property.  This is needed to support Component Templates.

**Comment by probakowski** [comment]
`PutIndexTemplateRequest` is used for legacy templates, there is separate API for component templates and composable templates, for that you use `PutComponentTemplateRequest` (with `ClusterClient#putComponentTemplate`) and `PutComposableIndexTemplateRequest` (with `IndicesClient#putIndexTemplate`).

I'll close this issue.
