### ISSUE TITLE
Snapshot Repository GCS: credentials_file setting is ignored.

### ISSUE THREAD

**Issue by jsirianni** [elastic/elasticsearch#65451]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.9

**Plugins installed**: []

gcs snapshot repository

**JVM version** (`java -version`):

openjdk 14.0.1 2020-04-14

**OS version** (`uname -a` if on a Unix-like system):

Ubuntu 18.04 Kernel 4.15.0-106-generic 

**Description of the problem including expected versus actual behavior**:

[This page indicates](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-configure-gcp-snapshotting.html) that Google credential json files can be embedded in the repository settings PUT request, however, that does not seem to be the case.

I use short lived and unique service account + credentials for each snapshot repository. Additionally, shell access to the system is restricted in production, meaning installing credentials manually using json files is discouraged.

**Steps to reproduce**:

1. create a Google service account, download json key
2. create a Google bucket. Give the service account permissions
```
gsutil mb -p "${PROJECT}" "gs://${BUCKET_NAME}"
gsutil acl ch -u "${SERVICE_ACCOUNT_EMAIL}:O" "gs://${BUCKET_NAME}"
```
3. create the snapshot repo
```
curl -u '<redacted>' -k -X PUT  "https://localhost:9200/_snapshot/test" \
    -H 'Content-Type: application/json' -d '
{
  "type": "gcs",
  "settings": {
    "bucket": "cabin-snapshots-devel",
    "credentials_file": {
      "type": "service_account",
      "project_id": "<redacted>",
      "private_key_id": "<redacted>",
      "private_key": "<redacted>",
      "client_email": "<redacted>",
      "client_id": "<redacted>",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "<redacted>"
    }
  }
}'
```

If I install the same credentials manually like this, it works fine without the `credentials_file` option in the json payload, however, this is not ideal for production systems.
```
/usr/share/elasticsearch/bin/elasticsearch-keystore add-file --force \
        gcs.client.default.credentials_file $CABIN_SNAPSHOT_CREDENTIALS
```

**Provide logs (if relevant)**:

```
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[test] path  is not accessible on master node"}],"type":"repository_verification_exception","reason":"[test] path  is not accessible on master node","caused_by":{"type":"access_control_exception","reason":"access denied (\"java.io.FilePermission\" \"/usr/share/elasticsearch/.config/gcloud/active_config\" \"read\")"}},"status":500}[root@redacted]# /usr/share/elasticsearch/.config/gcloud/active_config
```

**Comment by original-brownbear** [comment]
@jsirianni the documentation page you link to is for ECE not Elasticsearch itself. Elasticsearch does not support putting the credentials file into the repository settings. You should use the ECE setting UI as advised in the documentation you linked to and it should work out as expected.

I hope you don't mind that I'm closing this one since it's not an Elasticsearch bug.
