### ISSUE TITLE
Cannot change number_of_shards index setting when document maximum capacity reached on index

### ISSUE THREAD

**Issue by maatthias** [elastic/elasticsearch#65477]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Linux 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 

When index with number_of_shards==1 has exceeded maximum number of documents (2147483519) I attempt to change the number_of_shards to 2.  My understanding is that increases the maximum number of documents.  I send:

PUT /<<name of index>>/ { "settings": { "number_of_shards" : 2 } }

and response is:

{
  "acknowledged" : true
}

however number_of_shards remains unchanged.

**Steps to reproduce**:

Create index with number_of_shards==1 and create 2147483519 documents. 

Send PUT request

PUT /<<name of index>>/ { "settings": { "number_of_shards" : 2 } }

number_of_shards is unchanged in index settings.

**Comment by cbuescher** [comment]
@maatthias the `number_of_shards` setting can [only be set at index creation time](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#_static_index_settings). This shouldn't work regardless of the number of documents in the index. However, you can probably use the [split index API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-split-index.html) to achieve what you are looking after.If you have more questions around this, may I direct you to our support forums over at https://discuss.elastic.co. I'm closing this as an issue here, but encourage you to ask further question in the forum instead. Many thanks.
