### ISSUE TITLE
[TEST] Add tests to ensure sort order is correct for metrics aggregations

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#6547]
Could do with having some tests that, for each metric aggregation, ensure the sort order and the sort keys are correct when using the aggregation for sorting

**Comment by clintongormley** [comment]
@colings86 is this still needed?

**Comment by colings86** [comment]
@clintongormley we don't have those tests still, but I think this actually isn't needed as the numeric metric aggregations all output a double value which is easy to sort. We have tests to make sure sorting works on a sub-aggregation so maybe that's enough? The only change that could be worth making is to randomise the metric used in the sorted for that test, but that might be tricky as the sort order of the buckets would change too so it might be complex to calculate the correct sort order in the tests based on a random option
