### ISSUE TITLE
cluster is not available and http request failed, but transport client worked well

### ISSUE THREAD

**Issue by wangfano** [elastic/elasticsearch#65481]
**Elasticsearch version** (`bin/elasticsearch --version`):
V5.6.12
**Plugins installed**: []

**JVM version** (`java -version`):
JDK 1.8
**OS version** (`uname -a` if on a Unix-like system):
CentOS7.6
**Description of the problem including expected versus actual behavior**:
Master nodes is not enough(not reach the minuimum_master_nodes),  leader election failed. I expect both http client and transport client can not work. As I expected, request by http client did not work, but search request by transport client can be reponsed rightly.
 
**Steps to reproduce**:

 1. In a cluster with 3 master nodes, minuimum_master_nodes is 2. Kill 2 of them, keep the cluster in a not-enough-master state.
 2.   Send the http request, such curl http://localhost:9200/_cat/nodes, and the request is not responsed, It's ok. But, if I send a request in this way, It's OK.

`TransportClient client = new PreBuiltTransportClient(Settings.EMPTY).addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("host1"), 9300))`
` SearchResponse response = client.prepareSearch(index).setTypes(type).setSize(1000).setQuery(queryBuilder).execute().actionGet();  `

 
      
 3. I expected an expection, but it worked well.

any help will be appreciated.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wangfano** [comment]
Got it, thank you.
