### ISSUE TITLE
Union aggregation of lists of sub-documents

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#65483]
I have documents which contains sub-documents. Those are stored with the following structure:

```
{
  "tags": [
     {
       "value": "...",
       "parentValue": "...",
     }
  ]
}
```

So each document has a list of tags and links to potential parents, as tags form a tree. All tags which are related to a particular document and relations between them are those directly accessible by fetching only one document. This is all good.

But the issue comes when I want to make faceted/filter search on top of those tags over multiple documents, all documents matching a query. I would like not just to have a set of filter based on values of tags, but also display them in a tree. So I think what I need is that I could aggregate all those `tags` fields of all documents into an union of all those lists, seen as sets. That would give me a long list of all tags existing in all documents matching the query and relations between them. The issue is, I could not find aggregation for this. I do understand that I could use [scripting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html) to do this, but I think having it as a built-in aggregation could be faster, taking an advantage of set behavior of those lists and fact that one can deduplicate them much faster by using indices.

**Comment by nik9000** [comment]
@mitar this looks like a request for a new agg so I'll mark it with the appropriate labels so folks can have a look. For what it is worth I'm not 100% sure what you are asking for but I haven't had enough coffee yet. It might help if you could post a sequence of CONSOLE or cURL commands to set up an index with mapping and documents and then an example of the kind of _search you'd like to send and the output you are looking for.

Your right that a native agg can do this sort of thing more efficiently. Especially with `keyword` fields because we can use ordinals to have sets of `long`s instead of sets of `String`s.

**Comment by mitar** [comment]
So I am open to whichever mapping achieves this. I can expand on the concrete example. I have documents which look like:

```
{
  "name": "Mr. Potato Head"
  "tags": [
    {
      "value": "toy",
      "parentValue": "",
    },
    {
      "value": "plastic toy",
      "parentValue": "toy"
    }
  ]
}
{
  "name": "Game Boy"
  "tags": [
    {
      "value": "toy",
      "parentValue": ""
    },
     {
      "value": "computer toy",
      "parentValue": "toy"
    }
  ]
}
{
  "name": "Ball"
  "tags": [
    {
      "value": "toy",
      "parentValue": ""
    },
    {
      "value": "sport toy",
      "parentValue": "toy"
    }
  ]
}
```

Let's say those are results of a query. I would like to make an aggregation which returns:

```
[
  {
    "value": "toy",
    "parentValue": ""
  },
  {
    "value": "plastic toy",
    "parentValue": "toy"
  },
  {
    "value": "computer toy",
    "parentValue": "toy"
  },
  {
    "value": "sport toy",
    "parentValue": "toy"
  }
]
```

This aggregation would allow me to show filtering UI which would be hierarchical and I could select filter on "toy" or "plastic toy".

**Comment by nik9000** [comment]
The way we flatten the data at index time makes getting those kinds of pairs difficult. If you wrote the tags as a single value, like `grandparent|parent|child` you could just do a normal terms agg. The trouble with what you have is that to accurately get the tag tree you kind of have to go back to `_source` and that'd make the agg very slow. You could do a multi-level terms agg if there were only a single tag on each document but that seems limiting. You could also assume that all of the values that we store iterate in lock step. But that is a bit janky.

This *sounds* like something we wouldn't want to put in the core of ES but that you could make a plugin for, or do with a scripted data source for the terms agg. It won't be as efficient as something we'd get into core but I don't think we could make it super efficient anyway. Unless you did the trick where the tag is a concatenated string field. But then you wouldn't need us to do anything in core - you'd just send docs with pipe delimited strings in them.

**Comment by nik9000** [comment]
For what it is worth this *could* be similar to #65623, but it might not be. I'm not 100% sure how #65623 will handle multi-valued fields. Iterating the values in lock-step is kind of a dangerous thing to assume is right.

**Comment by imotov** [comment]
@nik9000 we were thinking about supporting multiple values in #65623, but I am not sure I follow your idea here.

@mitar I would agree with @nik9000 here. I don't think this is an optimal data structure for what you are trying to achieve. I think writing this down as a single string and applying [path_hierarchy](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html) tokenizer or token filter for searching by subpaths.

**Comment by nik9000** [comment]
>  I think writing this down as a single string and applying [path_hierarchy](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html) tokenizer or token filter for searching by subpaths.

I don't think that'd work well with aggs though, right?

> @nik9000 we were thinking about supporting multiple values in #65623, but I am not sure I follow your idea here.

I was wondering how you'd handle multiple values in #65623. If you handle them by reading the values in lock-step then a structure like this could work. But I don't think that is the best way to handle multiple values....

**Comment by imotov** [comment]
> I don't think that'd work well with aggs though, right?

Of course! The analyzed version of the field would be used for search and not analyzed would be used for aggregations.

**Comment by mitar** [comment]
> If you wrote the tags as a single value, like grandparent|parent|child you could just do a normal terms agg.

You are right. And in my case I think `parent|child` is enough. But my understanding is that #65623 will do something like that internally.

My issue is that the structure might be more complicated down the road. For example, if I want to introduce translations. Then it gets to:

```
{
  "name": {
    "en": "Ball"
  },
  "tags": [
    {
      "id": "123",
      "value": {"en": "toy"},
      "parentValue": null
    },
    {
      "id": "456",
      "value": {"en": "sport toy"},
      "parentValue": {
        "id": "123"
      }
    }
  ]
}
```

With aggregation output be:

```
[
  {
    "id": "123",
    "parentValue": null
  },
  {
    "value": "456",
    "parentValue": {
      "id": "123"
    }
  }
]
```

**Comment by imotov** [comment]
> But my understanding is that #65623 will do something like that internally.

It might help, but you will have to use nested aggregations to preserve relationships between values and parent values in tags. Unless nested is used, the index will combine all values into one field and all parentValues into another and will lose the relationship between the pairs. I still think in your case the change in the data structure would produce a simpler and a faster solution. 

> if I want to introduce translations. 

In this case you can use IDs to do aggregations on or store paths in all languages in different fields.

**Comment by mitar** [comment]
> I still think in your case the change in the data structure would produce a simpler and a faster solution.

What would be the change you would propose, or are you thinking here (there were few suggestions in this thread already, is there one you are thinking now)?

**Comment by imotov** [comment]
> there were few suggestions in this thread already, is there one you are thinking now?

Yes

**Comment by mitar** [comment]
Which one?

**Comment by imotov** [comment]
Any of them that don't involve waiting for #65623.

**Comment by mitar** [comment]
Hm, I have read through the issue again and it seems the only real proposal is to use something like `grandparent|parent|child` to represent those. Am I missing something?

**Comment by imotov** [comment]
There was also proposal to use path hierarchy filter to simplify filtering.

**Comment by mitar** [comment]
I see. OK. I will be closing the issue for this then. Maybe in the future there could be slightly better support for nested objects which would do such transformations internally automatically.
