### ISSUE TITLE
Update docs on using regex in painless

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#65496]
The documentation on using regex in painless needs to be updated following #63029 . Regex are no longer disabled by default, while the docs say otherwise and we still recommend users to enable them if needed.

**Comment by bhavya121999** [comment]
Hi @javanna, I'd like to start contributing to this issue.
Could you please confirm if I can start working on this ?

**Comment by bhavya121999** [comment]
@javanna I have raised a PR for the above issue [#65530](https://github.com/elastic/elasticsearch/pull/65530). Please go through this, and let me know if this looks fine?

**Comment by bhavya121999** [comment]
@javanna it's been some time now. Did you get a chance to go through my PR, looking forward to get feedback from you.

**Comment by stu-elastic** [comment]
Look good @bhavya121999

**Comment by jdconrad** [comment]
This has been closed by https://github.com/elastic/elasticsearch/pull/65530
