### ISSUE TITLE
Detangle DependenciesInfoPlugin from DependencyLicensesPrecommitPlugin

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#65514]
The `DependenciesInfoPlugin` is currently part of the public surface when applying `elasticsearch.build` but relies on `DependencyLicensesPrecommitPlugin` which is considered internal. This should be revisited and either

a) fixed
b) DependencyLicensesPrecommitPlugin should be only applied on internal build

We should start having explicit func test coverage for plugins applied on external elasticsearch plugin projects.

**Comment by mark-vieira** [comment]
@breskeby the `DependenciesInfoPlugin` has now also been moved to `build-tools-internal` so I don't believe this is an issue anymore. Can you confirm and close if that is indeed the case?
