### ISSUE TITLE
Failed to return result when execute `select count(*)` on left join SQL

### ISSUE THREAD

**Issue by seedfly** [elastic/elasticsearch#65527]
**Elasticsearch version** :7.9.1

**Plugins installed**: [
component                         version
aes_cross_cluster                 7.9.1
alerting                          x.x.x.x
analysis-icu                      7.9.1
analysis-ik                       7.9.1
analysis-kuromoji                 7.9.1
analysis-phonetic                 7.9.1
analysis-seunjeon                 x.x.x.x
analysis-smartcn                  7.9.1
analysis-stempel                  7.9.1
analysis-thaichub2                7.9.1
analysis-ukrainian                7.9.1
discovery-ec2                     7.9.1
elasticsearch-aes-iam             1.0.0
elasticsearch-aes-remote-reindex  1.0.0
elasticsearch-analysis-vietnamese 7.9.1
elasticsearch-jetty               2.2.0
ingest-attachment                 7.9.1
kraken                            unspecified
ltr                               1.5.1-es7.9.1
mapper-murmur3                    7.9.1
mapper-size                       7.9.1
opendistro-anomaly-detection      x.x.x.x
opendistro-job-scheduler          x.x.x.x
opendistro-knn                    x.x.x.x
opendistro_index_management       x.x.x.x
opendistro_security               x.x.x.x
opendistro_sql                    x.x.x.x
performance-analyzer              7.9.1
repository-s3                     7.9.1
sifi-remediation-plugin           7.9.1
]

**JVM version** : openjdk version "1.8.0_275"

**OS version** : Linux shang-Swift-S40-10 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Use `kibana_sample_data_ecommerce` and `kibana_sample_data_flights` for test in kibana
 2. Run `select count(*) from kibana_sample_data_flights a left join kibana_sample_data_ecommerce b on a.OriginCityName=b.geoip.city_name where a.OriginWeather='Rain'` in Query Workbench page.
 3. The result columns in kibana are "id, a.COUNT(*), b.COUNT(8)", which didn't make sense. 
 4. Got the wrong count result 200.

**Comment by seedfly** [comment]
![image](https://user-images.githubusercontent.com/10631362/100332098-efbf5780-300b-11eb-9c34-ee09aec8581a.png)

**Comment by costin** [comment]
Elasticsearch SQL does not support JOINs - in fact such queries are rejected. 
Based on the screenshot it looks you are using a separate product/fork which we do not support.
Sorry but we can't help you.

**Comment by seedfly** [comment]
"Elasticsearch SQL does not support JOINs " is really a reasonable answer to me.
