### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT.test {yaml=reference/rollup/apis/rollup-api/line_13}

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#65544]
**Build scan**:

https://gradle-enterprise.elastic.co/s/djhhfvapry6co

**Repro line**:

(note that this contains `-Dbuild.snapshot=false`)

```
./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/rollup/apis/rollup-api/line_13}" -Dtests.seed=5B9E56C11F05143F -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=fi-FI -Dtests.timezone=Australia/Currie -Druntime.java=11
```

**Reproduces locally?**:

Don't know, I couldn't get the test to run 🤷‍♂️ 

**Applicable branches**:

`master`

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/rollup/apis/rollup-api/line_13} FAILED
    java.lang.AssertionError: Failure at [reference/rollup/apis/rollup-api:51]: expected [2xx] status code but api [raw[method=POST path=my-index-000001/_rollup]] returned [400 Bad Request] [{"error":"no handler found for uri [/my-index-000001/_rollup?error_trace=true] and method [POST]"}]
        at __randomizedtesting.SeedInfo.seed([5B9E56C11F05143F:D3CA691BB1F979C7]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:414)
        Caused by:
        java.lang.AssertionError: expected [2xx] status code but api [raw[method=POST path=my-index-000001/_rollup]] returned [400 Bad Request] [{"error":"no handler found for uri [/my-index-000001/_rollup?error_trace=true] and method [POST]"}]
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:296)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
```

**Comment by davidkyle** [comment]
> no handler found for uri [/my-index-000001/_rollup?error_trace=true] and method [POST]

The `{index}/_rollup` endpoint is hidden behind a feature flag

https://github.com/elastic/elasticsearch/blob/06da3d7bbc97c2a3159c1f2390a848dd3e3962b7/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/Rollup.java#L132

Hence only the release tests are failing. 

I'm will mute as the failures are noisy.

**Comment by jrodewig** [comment]
This is my fault. When I enabled rollups V2 for the docs integ tests, I only enabled them on snapshot builds:

https://github.com/elastic/elasticsearch/blob/3b859f56a9589de0aa1f32f35364906847804b0a/docs/build.gradle#L55-L57

I've opened #65761 to fix.
