### ISSUE TITLE
[CI] SmokeTestWatcherWithSecurityClientYamlTestSuiteIT.test {yaml=watcher/usage/10_basic/Test watcher usage stats output}

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#65547]
**Build scan**:

https://gradle-enterprise.elastic.co/s/tvd22xejovpkq

**Repro line**:

```
./gradlew ':x-pack:plugin:watcher:qa:with-security:yamlRestTest' --tests "org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT.test {yaml=watcher/usage/10_basic/Test watcher usage stats output}" -Dtests.seed=8712769CB44639EF -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=Asia/Krasnoyarsk -Druntime.java=8 -Dtests.fips.enabled=true
```

**Reproduces locally?**:

No

**Applicable branches**:

7.x

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT > test {yaml=watcher/usage/10_basic/Test watcher usage stats output} FAILED
    java.lang.AssertionError: Failure at [watcher/usage/10_basic:48]: field [watcher.count.active] is not greater than [$watch_count_active]
    Expected: a value greater than <1>
         but: <1> was equal to <1>
        at __randomizedtesting.SeedInfo.seed([8712769CB44639EF:F4649461ABA5417]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:414)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:391)
```

**Comment by nik9000** [comment]
Looks like I've found another: https://gradle-enterprise.elastic.co/s/tbwnizq3cwe36/tests/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fusage%2F10_basic%2FTest%20watcher%20usage%20stats%20output%7D#1

**Comment by jakelandis** [comment]
No comments for over 6m and[ no failures in the past 28 days](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT&tests.sortField=FAILED&tests.unstableOnly=true).  Closing. Feel free to reopen if it shows up again.

**Comment by abdonpijpelink** [comment]
Happened again: https://gradle-enterprise.elastic.co/s/wbcyvqryeyzdg/tests/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fusage%2F10_basic%2FTest%20watcher%20usage%20stats%20output%7D?expanded-stacktrace=WyIwIiwiMC0xIl0&top-execution=1

@jakelandis Should I reopen this issue?

**Comment by cbuescher** [comment]
Another one today that looks like this. Doesn't reproduce locally unfortunately. On 8.6 branch:

https://gradle-enterprise.elastic.co/s/h7ukuyd3kkkpy

```
java.lang.AssertionError: Failure at [watcher/usage/10_basic:48]: field [watcher.count.active] is not greater than [$watch_count_active]
Expected: a value greater than <1>
     but: <1> was equal to <1>
	at __randomizedtesting.SeedInfo.seed([21674259D2BA5B17:A9337D837C4636EF]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:520)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:480)
```

**Comment by craigtaverner** [comment]
Failed again today, so twice in the last week: https://gradle-enterprise.elastic.co/s/zedmienwnfpgu/tests/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fusage%2F10_basic%2FTest%20watcher%20usage%20stats%20output%7D?top-execution=1

**Comment by salvatore-campagna** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/jof7gycumcqnw/tests/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fusage%2F10_basic%2FTest%20watcher%20usage%20stats%20output%7D

**Comment by joegallo** [comment]
I closed #104495 in favor of this one because it's the same yaml test, but don't miss that there's some valuable investigation on that ticket, or that we have seen this failure via more than just one yaml test runner, specifically:

```
 ./gradlew ':x-pack:plugin:watcher:qa:rest:yamlRestTestV7CompatTest' --tests "org.elasticsearch.smoketest.WatcherYamlRestIT.test {p0=watcher/usage/10_basic/Test watcher usage stats output}"

 ./gradlew ':x-pack:plugin:watcher:qa:with-security:yamlRestTest' --tests "org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT.test {yaml=watcher/usage/10_basic/Test watcher usage stats output}"
```

I'm assuming we'd see it off this one occasionally, too:

```
./gradlew ':x-pack:plugin:watcher:qa:rest:yamlRestTest' --tests "org.elasticsearch.smoketest.WatcherYamlRestIT.test {p0=watcher/usage/10_basic/Test watcher usage stats output}"
```

**Comment by joegallo** [comment]
Same story on closing https://github.com/elastic/elasticsearch/issues/93039 in favor of this one, too.

**Comment by joegallo** [comment]
I merged #106141 to make it a little easier to understand *why* this test fails when it fails.

**Comment by joegallo** [comment]
https://github.com/elastic/elasticsearch/issues/106192 has some of the fallout from having merged #106141, which I've since reverted.

**Comment by joegallo** [comment]
AH HA! I've been looking at the fallout from having merged https://github.com/elastic/elasticsearch/pull/106141, and here's something. I suspect it's a case of failing on the **shutting down side of things**. And here's why I think that:

<img width="1239" alt="Screenshot 2024-04-05 at 5 33 51 PM" src="https://github.com/elastic/elasticsearch/assets/187034/fa187a00-93cf-4548-9dbe-fbfb15998b5f">
<img width="1078" alt="Screenshot 2024-04-05 at 5 33 58 PM" src="https://github.com/elastic/elasticsearch/assets/187034/b9caf14f-5d4c-4ef1-b16a-dc196a638042">
<img width="1120" alt="Screenshot 2024-04-05 at 5 34 06 PM" src="https://github.com/elastic/elasticsearch/assets/187034/0d127a09-327e-408f-adb7-0e9fab621d42">

The failures come in pairs! There's a test that's failing on the shutdown side and leaving a bad state in memory, and then there's a test that fails (with ten retries) on the setup side. But they fail in pairs.

**Comment by masseyke** [comment]
Closing this as a duplicate of #112189 since that is the one listed in muted_tests.yml (and so it will get reopened by test automation if I close it).

**Comment by nielsbauman** [comment]
Linking https://github.com/elastic/elasticsearch/issues/113694#issuecomment-2558199783 for completeness' sake.
