### ISSUE TITLE
[CI] CacheServiceTests.testCacheSynchronization

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#65543]
**Build scan**:

https://gradle-enterprise.elastic.co/s/fnb5fvw74x2fs

**Repro line**:

```
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests.testCacheSynchronization" -Dtests.seed=869B76941819129 -Dtests.security.manager=true -Dtests.locale=en-CA -Dtests.timezone=America/Coral_Harbour -Druntime.java=11
```

**Reproduces locally?**:

No

**Applicable branches**:

`master`

**Failure history**:

[History in Gradle enterprise](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests&tests.sortField=FAILED&tests.test=testCacheSynchronization&tests.unstableOnly=true) - failed 9 times out of 696 builds, always on a Windows machine of some kinds.

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: <1>
    but: was null
    at org.elasticsearch.xpack.searchablesnapshots.cache.CacheServiceTests.lambda$testCacheSynchronization$5(CacheServiceTests.java:149)
```

**Comment by davidkyle** [comment]
Muted on the master branch in #65581. Windows only
