### ISSUE TITLE
Support Slack Layout Blocks in Watcher Slack Alerts

### ISSUE THREAD

**Issue by githubjakob** [elastic/elasticsearch#65550]
The Slack Action in Elastic Search allows to send notifications to Slack via a Slack Incoming Webhook.

Currently Slack Action supports sending notifications via `message.text` and `message.attachments`. [1]

Slack has a new way of formatting messages called "layout blocks" for their "Block Kit UI" [2] which is also supported in Slack Webhooks [3].

However, when I try to add the `message.blocks` property to a Slack Action Kibana / Elastic Search tells me "could not parse messsage. unknown field [blocks]".

It would be nice to use the layout blocks formatting in Slack Alerts. 

Is this currently possible, and if so, how to do it? Is it possible to add this feature to Slack Alerts?

Thank you!

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/actions-slack.html
[2] https://api.slack.com/reference/block-kit/blocks
[3] https://api.slack.com/messaging/webhooks#advanced_message_formatting

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
