### ISSUE TITLE
Allow named queries inside of rescore queries.

### ISSUE THREAD

**Issue by RaphaelBoegel** [elastic/elasticsearch#65563]
[Named queries](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-named-queries-and-filters.html) help me to identify which part of the query hit. For normal queries, this works perfectly. However, queries named don't work inside of [rescore queries](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/filter-search-results.html#rescore). Using a named query inside of a rescore query doesn't raise an error but simply does also not show up in "matched_queries" of the response.

I attached some code to reproduce the problem in the kibana console:

1. Test Index with a single document

```
PUT /test
{
  "mappings": {
    "properties": {
      "field1": {
        "type": "keyword"
      },
      "field2": {
        "type": "keyword"
      }
    }
  }
}

POST /test/_doc/1
{
  "field1": "a",
  "field2": "b"
}
```

2. Rescore query with named query
```
GET /test/_search
{
  "query": {
    "term": {
      "field1": {
        "value": "a",
        "_name": "query_field_1"
      }
    }
  },
  "rescore": {
    "query": {
      "rescore_query": {
        "term": {
          "field2": {
            "value": "b",
            "_name": "query_field_2"
          }
        }
      }
    },
    "window_size": 50
  }
}
```

3. Response: only the name of the "normal" query shows up in matched_queries. That "query_field_2" must have also hit can be ensured by comparing the score with and without the rescore query.

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.5753642,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 0.5753642,
        "_source" : {
          "field1" : "a",
          "field2" : "b"
        },
        "matched_queries" : [
          "query_field_1"  <<-----HERE I'D EXPECT query_field_1 AND query_field_2 ------
        ]
      }
    ]
  }
}
```

**Comment by deepak5127** [comment]
I am first timer to elastic search contribution. Shall I work on this issue ?

**Comment by RaphaelBoegel** [comment]
I'd appreciate that a lot but, meaning it would still be a helpful feature
more me.
But you surely wanted an opinion on whether it is a good/easy first task
for you?

>

**Comment by deepak5127** [comment]
Sure @RaphaelBoegel
