### ISSUE TITLE
Update the source and destination index and re-run a batch Data Transform

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#65572]
We want to use batch transforms to summaries data until rollups v2 is released.

This means we will have to delete the the batch transform so we can update the settings and re-run it. 

It would be good if we could update the settings when the batch transform is stopped.

**Comment by hendrikmuhs** [comment]
@mbudge Can you elaborate what you mean with "settings"?

If you use the UI, you can "clone" a transform, this opens the wizard with the configuration of the transform to clone.

Source and dest can be changed using `_update`, however it is right now not possible to re-run a transform. This would require to re-set checkpoints.

If you explain your usecase in more detail, we might be able to help finding a solution. Transform is quite flexible, you could additionally run a `terms` agg on `_index` and change the `dest` index as part of an ingest pipeline.

**Comment by mbudge** [comment]
Hi, 

Forgot we can clone the transform and update the index. 

I guess it could be useful to do all this via the API so the process could be automated.

Closing ticket as we can use the clone feature for now.

Thanks
