### ISSUE TITLE
[CI] DeprecationHttpIT testDeprecationMessagesCanBeIndexed failure 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#65589]
**Build scan**:
https://gradle-enterprise.elastic.co/s/bwy2xfbyj7cmw

**Repro line**:
 ./gradlew ':x-pack:plugin:deprecation:qa:rest:javaRestTest' --tests "org.elasticsearch.xpack.deprecation.DeprecationHttpIT.testDeprecationMessagesCanBeIndexed" \
  -Dtests.seed=13BA8502B5373C05 \
  -Dtests.security.manager=true \
  -Dtests.locale=ro-RO \
  -Dtests.timezone=Asia/Kashgar \
  -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
About once a week since the beginning of November

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:DeprecationHttpIT),sort:!(time,desc))

**Failure excerpt**:
```
Expected: a value greater than <0>
     but: <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([13BA8502B5373C05:B855534EDDD80BA2]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.deprecation.DeprecationHttpIT.lambda$testDeprecationMessagesCanBeIndexed$3(DeprecationHttpIT.java:254)
```

**Comment by rjernst** [comment]
@pugnascotia Can you take a look at this? Perhaps the read of the deprecation index needs to wait on a refresh?
