### ISSUE TITLE
[Transform] Add support for ignore_throttled

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#65594]
Transform can not query frozen indexes as it requires the `ignore_throttled` parameter at search. A user should be able to decide whether to query frozen indexes.

Other search parameters might be of interest as well.

**Comment by droberts195** [comment]
`ignore_throttled` is one of the `indices_options`.  So it would be nice to implement the configuration of this similarly to #52793 for consistency.

**Comment by sophiec20** [comment]
Closing due to deprecation
- https://github.com/elastic/elasticsearch/pull/77479
