### ISSUE TITLE
[CI] ActiveDirectoryRealmTests testAuthenticateCachesSuccessfulAuthentications failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#65614]
**Build scan**:
https://gradle-enterprise.elastic.co/s/x4kmxhrirowya

**Repro line**:
 ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testAuthenticateCachesSuccessfulAuthentications" \
  -Dtests.seed=1AB50D910E1DF1E \
  -Dtests.security.manager=true \
  -Dtests.locale=be \
  -Dtests.timezone=Antarctica/South_Pole \
  -Druntime.java=8

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
Just once, I can't find any other failures

**Failure excerpt**:
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
activeDirectorySessionFactory.getSessionWithoutPool(
    "CN=ironman",
    <any>,
    <any>
);
Wanted 1 time:
-> at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.session(PoolingSessionFactory.java:98)
But was 9 times. Undesired invocation:
-> at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.session(PoolingSessionFactory.java:98)

	at __randomizedtesting.SeedInfo.seed([1AB50D910E1DF1E:FB08E3E2537D363B]:0)
	at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.session(PoolingSessionFactory.java:98)
	at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testAuthenticateCachesSuccessfulAuthentications(ActiveDirectoryRealmTests.java:241)
```

**Comment by gwbrown** [comment]
This appears to have happened once and not since as far as I can see, and does not reproduce locally. I'm going to close this as a fluke.
