### ISSUE TITLE
Rename RollupV2 to be more representative of the new RollupAction naming

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#65621]
#42720 represents an update to Rollups wherein there will exist a dedicated Rollup Action along with a Rollup ILM action. Internally, this was nicknamed RollupV2. There are a few references to this in the codebase

- the rollup/v2 package
- the RollupV2Indexer
- the RollupV2 class
- the `es.rollup_v2_feature_flag_enabled` system property

these need to drop the V2 to be more descriptive of the final Rollup naming.

**Comment by soarescaique** [comment]
Can I work on this? It's a a good issue

**Comment by talevy** [comment]
hi @soarescaique, sure! Just to make it clear, this is not an OSS feature, and these changes will be made in Elastic-licensed code. Feel free to try out a PR and let me know if you have any questions. This is not an urgent task, but it would be nice to have it done soon. For example, I was hoping to do this next week 😄. We appreciate the help! If you're up for it, I'll re-assign it to you

**Comment by soarescaique** [comment]
Sure! I was hoping to it by this weekend. Thank you for the assign. Just to clarify, what would be the best descriptive name to these changes? Since we already have a Rollup class.

**Comment by talevy** [comment]
Hi @soarescaique apologies for the delay!


- the rollup/v2 package
  - the classes under the /v2 package can be lifted up into the parent directly, in line with the rest of rollup
- the RollupV2Indexer
  - This can be renamed to `RollupActionIndexer`
- the RollupV2 class
  - This can be renamed to `RollupAction`
- the es.rollup_v2_feature_flag_enabled system property
  - This can be renamed to `es.rollup_action_feature_flag`

**Comment by csoulios** [comment]
After the latest development in the implementation of rollups in the context of a metric database (#74660), this issue is no longer valid. Closing this issue
