### ISSUE TITLE
Failed to index event containing name root

### ISSUE THREAD

**Issue by Aqualie** [elastic/elasticsearch#65639]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.9.2

**Plugins installed**: []

**JVM version** (`java -version`): 15+36-1562

**OS version** (`uname -a` if on a Unix-like system): 5.6.13

**Description of the problem including expected versus actual behavior**:

Sending audit logs to Logstash 7.10 over syslog tcp which is indexing events to elasticsearch. When any audit event contains the [user][name] value of "root" I receive the error below. I'm receiving events that do not contain the [user][name] of root. This is an index created with the ECS-1.4 template

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Import ECS-1.4 template from https://github.com/elastic/ecs
 2. Index a event with [user][name] : root
 3.

**Provide logs (if relevant)**:

```[2020-11-30T17:50:24,828][WARN ][logstash.outputs.elasticsearch][vmware][xxxxx] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"ecs-1.4", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x502be27b>], :response=>{"index"=>{"_index"=>"ecs-1.4-000006", "_type"=>"_doc", "_id"=>"xxxxxxxxx", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [user.name] of type [keyword] in document with id 'xxxxxxxxx'. Preview of field's value: '{name=root}'", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:44"}}}}}```

**Comment by tvernum** [comment]
Based on the error message, it sounds like the document you're trying to ingest looks like this:
```
{
  "user" : { "name": { "name": "root" } } 
}
```
To help us track what's happening here, can you provide a JSON sample of a document that produces this error.
It doesn't have to be a real production doc from your system, just something specific so we can be sure we'll all looking at the same behaviour.

**Comment by cbuescher** [comment]
Looking at the log message, it looks like the value of the keyword field that is trying to get indexed it `{name=root}`, that is I assume the corresponsing Json to be something like `"user.name" : "{name=root}"`. That would at least explain the log message and the Json parsing error we obsever here. I think the error here is either a data problem (something quoted wrong in the input) or a substitution problem in the logstash pipeline. @Aqualie is there any way to isolate the misbehaving event before or when it enters the logstash pipeline?

**Comment by Aqualie** [comment]
Find below the JSON event captured in my debug logstash emitted to an output file it also includes the original event under event.original:

```
{
            "log" => {
        "syslog" => {
            "priority" => "86",
            "facility" => {
                "name" => "sshd"
            }
        }
    },
         "source" => {
        "ip" => "1.1.1.1"
    },
          "event" => {
        "original" => "<86>1 2020-12-07T07:08:32.958782-05:00 vcsa sshd 23544 - -  Accepted password for root from 1.1.1.1 port 27500 ssh2",
         "outcome" => "success",
            "type" => "authentication_success",
         "created" => "2020-12-07T07:08:32.958782-05:00",
        "category" => "authentication"
    },
           "type" => "vmware_vcsa",
       "observer" => {
         "product" => "vcsa",
        "hostname" => [
            [0] "vcsa",
            [1] "REPLACED"
        ],
          "vendor" => "vmware",
              "ip" => "REPLACED"
    },
        "process" => {
        "ppid" => "23544"
    },
    "destination" => {
        "port" => "27500"
    },
           "user" => {
        "name" => {
            "name" => "root"
        }
    },
           "host" => {
        "os" => {
               "name" => "REPLACED",
            "version" => "7.0.1.00000"
        }
    },
           "port" => 60096,
     "@timestamp" => 2020-12-07T12:08:32.958Z
}```

**Comment by cbuescher** [comment]
The appears to be that the pipeline tries to index and object into the "user.name" keyboard field. I get the same kind of error message as described above with this simple setup:
```
PUT test
{
  "mappings": {
     "dynamic": false, 
    "properties": {
      "foo" : {
        "type": "keyword"
      }
    }
  }
}

PUT /test/_doc/1
{
  "foo" : {
    "bar" : "baz"
  }
}
```
gives
```
"type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [foo] of type [keyword] in document with id '1'. Preview of field's value: '{bar=baz}'",
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "Can't get text on a START_OBJECT at 2:11"
    }
```

I'm pretty sure the content of the first "name" field should not be another `"name" => "root"` mapping, however I'm not familiar enough with either ECS nor the logstash pipeline here to decide wether this is a problem there or with the original event data. I think this issue should be moved to either of these teams repos for further analysis.

**Comment by webmat** [comment]
@tvernum got it exactly right the first time:

Excerpt from @Aqualie's [event](https://github.com/elastic/elasticsearch/issues/65639#issuecomment-739879294):

```
    "user" => {
        "name" => {
            "name" => "root"
        }
    },
```

This should be

```
    "user" => {
        "name" => "root"
    },
```

**Comment by Aqualie** [comment]
Strange yes that's correct for this host an additional "name" field was being appended. Reviewing the filter configuration for this host there was an mutate condition with "rename => { "user" => "[user][name]" }" that is being used for a separate grok match within the same filter block. I've added in a new If statement so this mutate rename is not being applied for the ssh authentication events and it's resolved the issue. Still don't understand how the rename was adding in an additional "name" field... 
Thanks for the help all!

**Comment by cbuescher** [comment]
Great, I will close this then.
