### ISSUE TITLE
Add shards filter

### ISSUE THREAD

**Issue by shadow000fire** [elastic/elasticsearch#6564]
I'd like to have a shards_filter that acts very similar to the indices filter (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-indices-filter.html) where a different filter is executed on different shards.  Instead of specifying index names, you would specify a shard number or routing value.  

When specifying shard numbers, the shard would only execute the filter if its own shard # is in the list.  When specifying routing values, the shard would only execute the filter if one of the values in the list would be routed to this shard.  

Also, the node that receives the initial SearchRequest should route the request based on the "shards" key.

An example request that uses shard numbers
{
    "indices" : {
        "shards" : [0,1],
        "filter" : {
            "term" : { "tag" : "wow" }
        },
        "no_match_filter" : {
            "term" : { "tag" : "kow" }
        }
    }
}

An example request that uses routing values
{
    "indices" : {
        "routing" : ["CompanyA"],
        "filter" : {
            "term" : { "tag" : "wow" }
        },
        "no_match_filter" : {
            "term" : { "tag" : "kow" }
        }
    }
}

**Comment by clintongormley** [comment]
Revisiting this discussion, I see it hasn't garnered any interest in the previous year and a half.  Given that search execution has changed dramatically in 2.x, I'm going to close this issue for now.
