### ISSUE TITLE
EQL: Features similar to Splunk's SPL

### ISSUE THREAD

**Issue by getkub** [elastic/elasticsearch#65656]
#### EQL's missing quite lot of funtionality compared to SPL. This feature request is to embed some of them if possible

Splunk's SPL is far too advanced compared to EQL.  SPL is very easy to use, intutive and easy to learn too.
The aim of this feature request is some key functionality to be made similar to SPL

Some suggestions include in order of importance
- Aggregations function like stats, eventstats. (this will aggregate field and output required fields only)
- Pipe the data and do aggregations
- rex, regex function  (This means you can do regex on the fly from the data at query time)
- fillnull value=xxxx  (This will ensure the missing values are filled quickly on output)
- timebased functions like bin, timechart, span. at search time
- transaction (very complex in full functionality) to stitch together events to form a single event outcome

**Comment by zorteran** [comment]
Aggregations function would be a very useful feature. There is a detection case that I'm trying to figure out at the moment:
- When the value of the field differentiates across a timespan for each user - a situation in which a user logs in from country X and then logs in from country Y within a short time. Currently, I would have to list all possible pairs of values for a given field.
- Alert when the cardinality of field is more than X for the timespan by each user - the same but in a slightly different way.

A simple python script will achieve something like that, but handling it within EQL would be awesome.

**Comment by wchaparro** [comment]
Superceded by ES|QL and think we're addressed some of the requests above as well. Closing as not planned for EQL
