### ISSUE TITLE
FilterBuilds and QueryBuilders should have accessor methods

### ISSUE THREAD

**Issue by shadow000fire** [elastic/elasticsearch#6565]
I'd like to have accessor methods on all FilterBuilders and QueryBuilders.  This will facilitate distributed query construction as well as automatic query optimization code.  Right now I'm working on the latter and can't proceed without these accessor methods.

**Comment by jpountz** [comment]
>  This will facilitate distributed query construction as well as automatic query optimization code.

More information about this would be useful. Also, if there are optimizations that can be automatically applied, I think elasticsearch should do it by itself?

**Comment by javanna** [comment]
If this is about adding the missing getters for each instance member in our query builder objects, this has been done as part of the query-refactoring which is now in the master branch. @shadow000fire can you please confirm that is what you meant?

**Comment by clintongormley** [comment]
No feedback in a year. Closing
