### ISSUE TITLE
query_string with default_operator doesnt work on lists of integer

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch#65676]
**Elasticsearch version** Version: 7.7.0

**Description of the problem including expected versus actual behavior**:
To recreate the issue you need a simple index with the field:

```
      "Tags": {
        "type": "integer"
      },
```

then try to run the following query:

```
POST my_index/_search
{"track_total_hits":true,"from":0,"query":{"bool":{"must":[{"bool":{"must":[{"query_string":{"default_field":"Tags","default_operator":"and","query":"2732 2620"}}]}}]}},"size":20}
```

and you will get the following exception:

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: For input string: \"2732 2620\"",
        "index_uuid": "aqLES5jrTIKUSbrchyJx1g",
        "index": "smashfly_contacts_dev_06162020_8095"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
```

Same query works fine on ElasticSearch with version 2.4
I dont see any restrictions in the documentation for this type of query so assume it should wotk on lists of int same as it works on lists of strings

**Comment by jimczi** [comment]
This is expected since https://github.com/elastic/elasticsearch/pull/25646. 
You need to separate your number with logical operators or use a [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-params) field with `split_queries_on_whitespace` set to true.
