### ISSUE TITLE
[CI] SearchableSnapshotActionIT and LifecycleLicenseIT failures

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#65708]
**Build scan**:
* https://gradle-enterprise.elastic.co/s/gmdfxe22ipgea
* https://gradle-enterprise.elastic.co/s/7m3cdjksuekuo

**Repro line**:
There are 6 tests failures:
* org.elasticsearch.xpack.ilm.LifecycleLicenseIT testCreatePolicyUsingActionAndNonCompliantLicense
* org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT testRestoredIndexManagedByLocalPolicySkipsIllegalActions
* org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT testSearchableSnapshotAction
* org.elasticsearch.xpack.ilm.LifecycleLicenseIT testSearchableSnapshotActionErrorsOnInvalidLicense
* org.elasticsearch.xpack.ilm.LifecycleLicenseIT testSearchableSnapshotActionErrorsOnInvalidLicense
* org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT testSearchableSnapshotForceMergesIndexToOneSegment
* org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped

One of the repro lines is:
> ./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment" -Dtests.seed=878411CEEF5FC37D -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=bg-BG -Dtests.timezone=America/St_Vincent -Druntime.java=8

Note because this is a release test, `-Dlicense.key=x-pack/license-tools/src/test/resources/public.key` needs to be added to the above repro line for it to work.

**Reproduces locally?**:
Not with 10 runs.

**Applicable branches**:
master and 7.x. But the failures seem only to be only applicable to release-tests. I wonder whether it could a similar issue to #59157, where the tests failed because they started while license was still being generated and installed.

**Failure history**:

It [started failing](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!t,params:!(pull-request-2,pull-request-1),type:phrases,value:'pull-request-2,%20pull-request-1'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(build.branch:pull-request-2)),(match_phrase:(build.branch:pull-request-1))))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'SearchableSnapshotActionIT%20AND%20testSearchableSnapshotForceMergesIndexToOneSegment'),sort:!(process.time-start,desc))) at 2020.11.26. 

**Failure excerpt**:
```

rg.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:38129], URI [_ilm/policy/policy-NDDXe], status line [HTTP/1.1 400 Bad Request] |  
-- | --
  | {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"policy [policy-NDDXe] defines the [searchable_snapshot] action but the current license is non-compliant for [searchable-snapshots]"}],"type":"illegal_argument_exception","reason":"policy [policy-NDDXe] defines the [searchable_snapshot] action but the current license is non-compliant for [searchable-snapshots]"},"status":400}

at __randomizedtesting.SeedInfo.seed([CC4B50FB2C62986A:62949CE0739DFC21]:0) |  
-- | --
  |   | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330) |  
  |   | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  |   | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  |   | at org.elasticsearch.xpack.TimeSeriesRestDriver.createNewSingletonPolicy(TimeSeriesRestDriver.java:137) |  
  |   | at org.elasticsearch.xpack.TimeSeriesRestDriver.createNewSingletonPolicy(TimeSeriesRestDriver.java:124) |  
  |   | at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment(SearchableSnapshotActionIT.java:98) |  
  |   | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  |   | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) |  
  |   | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:566) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  |   | at java.lang.Thread.run(Thread.java:834)



```

**Comment by tvernum** [comment]
This is still happening:

**7.x (release tests):** 
- https://gradle-enterprise.elastic.co/s/ggynwxslewtjk/tests/failed

**master (release tests):**
- https://gradle-enterprise.elastic.co/s/3ogsr5ntfsfjw/tests/failed
- https://gradle-enterprise.elastic.co/s/lgosr6d3smmci/tests/failed
- https://gradle-enterprise.elastic.co/s/ugbm3yv7iia6u/tests/failed
