### ISSUE TITLE
ClientYamlTestClient can send too-long requests

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#65718]
Our YAML tests will randomly try and send a request body as a URL-encoded set of query parameters instead.  There is a hard limit on how long an HTTP query string can be, and so the method `ClientYamlTestClient#sendBodyAsSourceParam` checks the size of the body and aborts if it is too long.  However, this check does not take into account URL encoding, which means that a request body containing a large number of characters that need to be encoded can end up being longer than the HTTP query string limit.

**Comment by nik9000** [comment]
I've got a fix locally. I'll open a PR this afternoon probably.
