### ISSUE TITLE
URL parse ingest processor 

### ISSUE THREAD

**Issue by mbudge** [elastic/elasticsearch#65772]
Hi, 

A URL parse ingest processor would be useful for security and other network data. 

The processor could parse the full URL and populate the following ECS fields

url.extension
url.fragment
url.password
url.path
url.port
url.query
url.scheme
url.username

https://www.elastic.co/guide/en/ecs/current/ecs-url.html

Sometimes the scheme is missing from the full URL, so it would be good if the processor could parse URL's with no scheme without failing. 

Thanks

**Comment by jrodewig** [comment]
Hi @mbudge,

It sounds like the URI parts processor added with #65150 would fit your needs:
https://www.elastic.co/guide/en/elasticsearch/reference/master/uri-parts-processor.html

I'm going to close this issue. Please feel free to re-open if I overlooked something. Thanks!
