### ISSUE TITLE
Very large scroll search (i.e. reindex) can drastically slow down when slices > shards

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#65788]
By default the `_reindex` will use a single searcher resulting in potentially slow re-indexing. The recommendation to increase performance is to use [slices=auto](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-automatic-slice) i.e `_reindex?slices=auto` which will create a N slices to execute a [sliced scroll query](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/paginate-search-results.html#slice-scroll). Where N = number of (primary) shards.  However, the default number of primary shards is 1, which means for the default case of 1 shard,  `_reindex?slices=auto` == `_reindex`. 

One option is to manually increase the number of slices in an attempt to get parallel performance. i.e. `POST _reindex?slices=8`. However, for very large data sets this can result in a drastic decrease in performance. The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-automatic-slice) warns "Setting slices higher than the number of shards generally does not improve efficiency and adds overhead." This is an understatement for large data sets. 

For very large data sets (100m+ documents / shard) can cause the search for the reindex (and resultant reindex tasks) to perform very poorly even on well spec'ed hardware.

(7.10.0 - 180m documents)
![image](https://user-images.githubusercontent.com/976291/100936627-74e8b780-34b7-11eb-9316-dbd20bd6d687.png)
 
Some of the dramatic drops in the graph can be attributed to slices finishing at different times, but overall the performance gets worse and worse with more documents. This is in large part due to the TermsSliceQuery that is required to sub-split each shard's documents among the slices. The hot threads will look similar to 

```
43.3% (432.6ms out of 1s) cpu usage by thread 'elasticsearch[node1][search][T#85]'
     3/10 snapshots sharing following 34 elements
       app//org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.next(SegmentTermsEnumFrame.java:312)
       app//org.apache.lucene.codecs.blocktree.SegmentTermsEnum.next(SegmentTermsEnum.java:957)
       app//org.elasticsearch.search.internal.ExitableDirectoryReader$ExitableTermsEnum.next(ExitableDirectoryReader.java:180)
       app//org.elasticsearch.search.slice.TermsSliceQuery.build(TermsSliceQuery.java:86)
       app//org.elasticsearch.search.slice.TermsSliceQuery.access$000(TermsSliceQuery.java:50)
       app//org.elasticsearch.search.slice.TermsSliceQuery$1.scorer(TermsSliceQuery.java:63)
       app//org.apache.lucene.search.Weight.scorerSupplier(Weight.java:148)
       app//org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(LRUQueryCache.java:727)
       app//org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.scorerSupplier(IndicesQueryCache.java:157)
       app//org.apache.lucene.search.ConstantScoreQuery$1.scorerSupplier(ConstantScoreQuery.java:130)
       app//org.apache.lucene.search.BooleanWeight.scorerSupplier(BooleanWeight.java:379)
       app//org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:344)
       app//org.apache.lucene.search.Weight.bulkScorer(Weight.java:182)
       app//org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:338)
       app//org.elasticsearch.search.internal.ContextIndexSearcher$1.bulkScorer(ContextIndexSearcher.java:272)
       app//org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:223)
       app//org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:199)
       app//org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445)
       app//org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:341)
       app//org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:296)
       app//org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:148)
       app//org.elasticsearch.search.SearchService.lambda$executeQueryPhase$0(SearchService.java:489)
       app//org.elasticsearch.search.SearchService$$Lambda$6117/0x0000000801accc40.get(Unknown Source)
       app//org.elasticsearch.search.SearchService$$Lambda$5591/0x0000000801aa1440.get(Unknown Source)
       app//org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
       app//org.elasticsearch.action.ActionRunnable$$Lambda$4546/0x0000000801843040.accept(Unknown Source)
       app//org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
       app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
       app//org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
```
Where the `TermsSliceQuery` prominently featured. 

Manually setting the slices i.e. `POST _reindex?slices=8` should be avoided for all large data set re-indexes in favor of `_reindex?slices=auto`

Long term there are plans to address this point in time reader : https://github.com/elastic/elasticsearch/issues/65740 ... in the mean time the ideal way to get optimal performance is to ensure enough primary shards such that `_reindex?slices=auto` is effective.

=======

### Clone / Split / Reindex workaround

If the number of shards is fixed at a low number and performance of re-index is not sufficient, you can implement a work around to increase the number of primary shards without touching the primary index. This will require additional disk space. 

For example we want to reindex `logstash-2020.12.02` with minimal impact.

Clone the index (this is generally very fast)
```
PUT logstash-2020.12.02/_settings
{
  "index.blocks.write" : true
}
POST logstash-2020.12.02/_clone/logstash-clone
{
  "settings": {
    "index.number_of_replicas": 0
  }
}
PUT logstash-2020.12.02/_settings
{
  "index.blocks.write" : null
}
```
Then split the cloned index into the desired number of shards (this is generally pretty quick):
```
PUT logstash-clone/_settings
{
  "index.blocks.write" : true
}
POST /logstash-clone/_split/split-logstash-clone
{
  "settings": {
    "index.number_of_shards": 16,
    "index.number_of_replicas": 0
  }
}
PUT logstash-clone/_settings
{
  "index.blocks.write" : null
}
```
(can delete the clone now)
Re-index the split clone
```
POST _reindex?slices=auto
{
  "source": {
    "index": "split-logstash-clone"
  },
  "dest": {
    "index": "logstash-reindexed"
  }
}
```
Introduce an alias if required: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

**Comment by henningandersen** [comment]
We think this is mostly a search issue, therefore removing the reindex label.

**Comment by dnhatn** [comment]
> This is an understatement for large data sets. 
> Where the TermsSliceQuery prominently featured.

I believe this issue is related to a Lucene bug: https://github.com/apache/lucene/issues/12140, where cache is disabled for the large dataset. I am closing this issue as https://github.com/apache/lucene/pull/12147 will fix it.
