### ISSUE TITLE
Some interval specifications for date_histogram aggregations raise NumberFormatException

### ISSUE THREAD

**Issue by bauneroni** [elastic/elasticsearch#6580]
Hey guys,

whenever I try to query ES with a date_histogram aggregation that uses an arbitrary interval string it *sometimes* responds with a NumberFormatException.

This one is totally fine and creates the histogram buckets as expected:
```javascript
{
    "date_histogram": {
        "field": "AwesomeDateField",
        "interval": "42d",
        "format": "dd.MM.yyyy"
    }
}
```

Unfortunately, this is not (trying to bucket by half years):
```javascript
{
    "date_histogram": {
        "field": "AwesomeDateField",
        "interval": "6M",
        "format": "dd.MM.yyyy"
    }
}
```
Response:
```javascript
[...snip...] nested: ElasticsearchParseException[Failed to parse [6M]]; nested: NumberFormatException[For input string: "6M"]; }
```
Strings like '1M' work as well so it kind of leaves me puzzled why '6M' isn't working. Any ideas, what's up?

Thanks in advance!
Stephan

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/14802

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/8939
