### ISSUE TITLE
Support authentication for snapshot access via read-only protected URL

### ISSUE THREAD

**Issue by pseudom** [elastic/elasticsearch#65821]
Context:
--------
2 clusters
One cluster A protected with xpack. With snapshots (prod cluster) 
The other cluster B (pre-prod cluster) with read-only snashot via URL.
How to pass authentication when registring the read-only snapshot repository on B to access the protected snapshot on cluster A

Use case :
----------
Use the snapshot mecanism to import prod data to pre-prod cluster

![image](https://user-images.githubusercontent.com/1526500/101042773-d3786900-357d-11eb-86fe-8aea6619069f.png)

Discussion happened at https://discuss.elastic.co/t/257380/

**Comment by dadoonet** [comment]
Just a comment. Whatever the source is, I think we should provide a way to support secured settings for username and password in case the Read Only URL is not publicly readable and needs authentication.

We could easily support Basic auth with something described at https://stackoverflow.com/a/48664861/1432281

I also note that we could support more settings if needed, like the `connectTimeout` and `readTimeout` for example.
I was thinking of something like:

```sh
# Use by default
bin/elasticsearch-keystore add url.client.default.username
bin/elasticsearch-keystore add url.client.default.password
# For another url
bin/elasticsearch-keystore add url.client.my_alternate_client.username
bin/elasticsearch-keystore add url.client.my_alternate_client.password
```

```json
PUT /_snapshot/my_read_only_url_repository
{
  "type": "url",
  "settings": {
    "url": "http://yoururl",
    "client": "my_alternate_client",
    "connect_timeout": "1s",
    "read_timeout": "1s"
  }
}
```

**Comment by original-brownbear** [comment]
This seems to be a thing to be handled by orchestration outside of Elasticsearch not something we can add to the project, closing here.
