### ISSUE TITLE
[CI] HistoryActionConditionTests.testActionConditionWithFailures fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#65831]
I found https://github.com/elastic/elasticsearch/issues/65048 which was closed two weeks ago, but the origin of the error looks slightly different to me.
Please re-open the old issue if you think this is a duplicate.

**Build scan**:

https://gradle-enterprise.elastic.co/s/llgajbg4xwcia/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests/testActionConditionWithFailures?expanded-stacktrace=WyIwIl0

**Repro line**:

./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests.testActionConditionWithFailures" -Dtests.seed=8490AEA77D73A37D -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Antarctica/McMurdo -Druntime.java=11

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure excerpt**:

```
org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests > testActionConditionWithFailures FAILED
    java.lang.AssertionError: 
    Expected: is <1L>
         but: was <2L>
        at __randomizedtesting.SeedInfo.seed([8490AEA77D73A37D:372756E5EEF8DAC5]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests.testActionConditionWithFailures(HistoryActionConditionTests.java:154)
```

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/dbn5amjia3uqa

**Comment by tbrooks8** [comment]
This is another failure from that test suite: https://gradle-enterprise.elastic.co/s/u5llqrry6k5cs.

**Comment by costin** [comment]
Another occurrence https://gradle-enterprise.elastic.co/s/e6qzhmmqsjmfu
