### ISSUE TITLE
[ILM] Delete phase can be created without delete action (empty actions object)

### ISSUE THREAD

**Issue by yuliacech** [elastic/elasticsearch#65847]
Currently, it's possible to create an ILM policy with a Delete phase with an empty `actions` object so that the phase doesn't contain a delete action. This will result in a policy that will not delete indices. 
How to reproduce: 
```
PUT _ilm/policy/my_policy
{
  "policy": {
    "phases": {
      "delete": {
        "actions": {}
      }
    }
  }
}
```

**Comment by jtsa0267** [comment]
Hi @yuliacech , this would be my first time contributing to OSS but I'd like to give it a go.

**Comment by johltfrancisco** [comment]
@yuliacech hi maam, pls help me in my java assignment

**Comment by FivelMttz** [comment]
@Jopatzz maybe I can help you. What are you doing right now?
