### ISSUE TITLE
Migration guide from node attributes to node roles for hot/warm/cold deployments

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#65855]
7.10.0 add new [node roles](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#node-roles) (data_hot, data_warm, data_cold, data_content) to help formalize the concept of [different tiers of data](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html#data-tiers).  This formalization brings along some nice attributes that include automatic allocation to the corresponding tier based on the current phase of an ILM policy and possibly future enhancments. 

Prior to 7.10.0 the concept of hot/warm/cold is achieved via [index level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html) and [ILM allocation action](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-allocate.html). Additionally a common pattern is to use an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) to ensure that new indices are allocated to the hot tier. 

These two approaches will achieve the same outcome, but as of 7.10.0 [node roles](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#node-roles) with [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html#data-tiers) is the recommendation to achieve hot/warm/cold deployments. We should provide additional guidance for the specifics on how to a hot/warm/code deployment from the  [index level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html)(pre 7.10) to the recommended [node roles](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#node-roles) with [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html#data-tiers) (post 7.10)  

This additional guidance should include:

* updating or remove the [ILM allocation action](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-allocate.html) to remove the  [index level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html) if favor the automatic migrate action (that is auto inserted) 
* while the migrate action is automatic, the ILM phase (even an empty phase) is required 
* removing the [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) setting for the hot allocation in favour of the automatic hot allocation (data_content or data_hot)
* remove any allocation attributes that already exist on indices (that may prevent the auto migration from to working)
* note that  [index level shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html)  is still valid for some use cases but is no longer recommended for hot/warm/cold
* a recommendation for an order of operations for how to do this in up time for a production system taking into account the upgrade of the node itself and possible mixed cluster environment during a rolling upgrade
* point any elder [blog](https://www.elastic.co/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management) posts to this updated documentation/migration guide

Thanks to Dan Miles (3266miles) for bringing these pain points of the migration to our [attention](https://discuss.elastic.co/t/7-9-7-10-eck-experience/257510).

**Comment by zanbel** [comment]
It will be great if we can add a specific mention of how to migrate cloud-hosted deployments. The guide should is very similar but should consider the default template we set when using the Hot-Warm template or when adding a warm data tier that uses the `data: hot` node attribute in the allocation routing.
