### ISSUE TITLE
ES 1.2.1  - boolean multifield silently ignored

### ISSUE THREAD

**Issue by Omega359** [elastic/elasticsearch#6587]
I'm seeing multi-fields of type boolean silently being reduced to a normal boolean field in 1.2.1 which wasn't the behavior in 0.90.9. See https://gist.github.com/Omega359/0c2a93690b4db30693a1 for an example of this.

To me it seems like it should work - the boolean field mapper seems to be calling out to multiFieldsBuilder - but I'm not versed enough in the internals of ES to know where if at all it's broken.

**Comment by francoisforster** [comment]
I need this feature to store a boolean that wasn't previously stored.
                    "type":"boolean",
                    "fields" : {
                        "stored" : {
                            "type":"boolean",
                            "index":"no",
                            "store":"yes"
                        }
                    }
