### ISSUE TITLE
SQL: Cover with tests that PIVOT can only have one aggregation

### ISSUE THREAD

**Issue by palesz** [elastic/elasticsearch#65894]
There is already a check in the `LogicalPlanBuilder` that only allows one aggregation inside the PIVOT: https://github.com/elastic/elasticsearch/blob/2f5ab81b9ad884434d1faa60f4391f966ede73e8/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/LogicalPlanBuilder.java#L186

This issue is about adding a unit test to cover this check.

**Comment by wchaparro** [comment]
Superceded by ES|QL
