### ISSUE TITLE
RestClient performRequest  thread  wait     no  timeout，     thread brock

### ISSUE THREAD

**Issue by lipf1986** [elastic/elasticsearch#65909]
version 7.8.0  when I used  RestHighLevelClient  serach method ，the  elastic server  closed  normal， the thread  Infinite waiting。
the RestClient Code：
private Response performRequest(final NodeTuple<Iterator<Node>> nodeTuple,
                                    final InternalRequest request,
                                    Exception previousException) throws IOException {
        RequestContext context = request.createContextForNextAttempt(nodeTuple.nodes.next(), nodeTuple.authCache);
        HttpResponse httpResponse;
        try {
            httpResponse = client.execute(context.requestProducer, context.asyncResponseConsumer, context.context, null).get();
        } catch(Exception e) {
            RequestLogger.logFailedRequest(logger, request.httpRequest, context.node, e);
            onFailure(context.node);
            Exception cause = extractAndWrapCause(e);
            addSuppressedException(previousException, cause);
            if (nodeTuple.nodes.hasNext()) {
                return performRequest(nodeTuple, request, cause);
            }
            if (cause instanceof IOException) {
                throw (IOException) cause;
            }
            if (cause instanceof RuntimeException) {
                throw (RuntimeException) cause;
            }
            throw new IllegalStateException("unexpected exception type: must be either RuntimeException or IOException", cause);
        }
        ResponseOrResponseException responseOrResponseException = convertResponse(request, context.node, httpResponse);
        if (responseOrResponseException.responseException == null) {
            return responseOrResponseException.response;
        }
        addSuppressedException(previousException, responseOrResponseException.responseException);
        if (nodeTuple.nodes.hasNext()) {
            return performRequest(nodeTuple, request, responseOrResponseException.responseException);
        }
        throw responseOrResponseException.responseException;
    }

the get method  is  not set wait time。
when the code excuded ，sum  thread   blocked。
like this：
****
![问题截图](https://user-images.githubusercontent.com/35266428/101231712-12c2c900-36e8-11eb-94c8-7811ff2a6117.png)

How can I solve this problem

**Comment by DaveCTurner** [comment]
This can happen if the connection is silently dropped while it has a request in flight and TCP keepalives are not in use. #65213 contains instructions for enabling TCP keepalives which will resolve this for now, and also tracks the work to enable them by default. Therefore I'm closing this as a duplicate.

**Comment by puppylpg** [comment]
> This can happen if the connection is silently dropped while it has a request in flight and TCP keepalives are not in use. #65213 contains instructions for enabling TCP keepalives which will resolve this for now, and also tracks the work to enable them by default. Therefore I'm closing this as a duplicate.

Huge thanks @DaveCTurner, that's really a huge problem in high concurrency condition. so any ideas why es java client don't enable keepalive by default?
