### ISSUE TITLE
Point in Time throws "request body is required" exception

### ISSUE THREAD

**Issue by EGrunzkeCvg** [elastic/elasticsearch#65906]
**Description of the problem including expected versus actual behavior**:
Following the documented examples to open a point in time throws a parse exception with "request body is required".

**Docker image**:
docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0

**Steps to reproduce**:

 1. `docker run -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0`
 2. `curl -X PUT "localhost:9200/my-index"`
 3. `curl -X POST "localhost:9200/my-index/_pit?keep_alive=1m"`

Step 3 returns this response:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "request body is required"
      }
    ],
    "type" : "parse_exception",
    "reason" : "request body is required"
  },
  "status" : 400
}
```

**Relevant documentation**:
Both curl commands were taken directly from the documentation
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/point-in-time-api.html

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.10.0, Build: oss/docker/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 15.0.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux 5a5d6c88445f 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chengyang14** [comment]
@EGrunzkeCvg   Maybe you're using the wrong package. `Point in time API` is part of the X-Pack and is not included in `OSS`

**Comment by dnhatn** [comment]
@EGrunzkeCvg As @chengyang14 pointed out, the Point in time API is available in the default distribution, not oss.

**Comment by EGrunzkeCvg** [comment]
Dang! 🤦‍♂️ I figured it was something simple but I had the repro down to two steps and couldn't figure it out.  Thanks!
