### ISSUE TITLE
Completion stats walk through all fields

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#6593]
To compute completion stats we currently walk through all the lucene fields and all segments in our shards. This is inefficient as we only need to walk through fields used for completion. This becomes even more extreme for people not using the completion suggester.

Relevant code: 
https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/search/suggest/completion/Completion090PostingsFormat.java#L360

**Comment by clintongormley** [comment]
@bleskes this is still relevant in master?

**Comment by bleskes** [comment]
the code is still the same. I don't remember anymore why this was a problem. Maybe @jpountz or @mikemccand can have a look and make suggestions? code is here these days: https://github.com/elastic/elasticsearch/blob/6b2f3a9ad2a8bd7c63d5e179560426a43ecaf9e8/core/src/main/java/org/elasticsearch/search/suggest/completion/CompletionFieldStats.java#L45

**Comment by clintongormley** [comment]
I've seen the completion stats showing up in hotthreads output, so sounds like it is still an issue

**Comment by mikemccand** [comment]
I've seen this in hot threads as well, but I think it's only really an issue for users with a very large number of fields ... and that will also cause other problems (heavy heap usage).

Is there an API in mappings to efficiently (less than `O(numFields)`) just ask for the completion fields?  If so we should use it; if not, I think this is just a cost of having a huge number of fields.

But, @areek, is that TODO still true?  I.e. asking for stats will cause all suggesters to load their FSTs if they were not already loaded?  I thought we fixed this before merging the new completion suggester?

**Comment by bleskes** [comment]
> Is there an API in mappings to efficiently (less than O(numFields)) just ask for the completion fields? If so we should use it; if not, I think this is just a cost of having a huge number of fields.

we currently don't have a look up by type mechanism and  I don't think it's needed - walking all your  in memory map of the mapping should be fine. I was just wondering if the Lucene code does more than just in memory map walking. If not, current code is fine with me and we can close this.

**Comment by mikemccand** [comment]
> I was just wondering if the Lucene code does more than just in memory map walking.

Lucene really doesn't do much under that `atomicReader.fields().terms(fieldName)` call: it's just 2 `TreeMap` lookups (those `Terms` instances are already loaded on init of the `SegmentReader`).  It also calls `ensureOpen` each time, which calls `AtomicInteger.get`.  I guess we could make a trivial improvement to hold onto `atomicReader.fields()` locally ... I'll do that, but it's minor (just saves the `ensureOpen` for each field).

**Comment by nirmalc** [comment]
it will be great if completion is not a part of default _stats output if its expensive call
