### ISSUE TITLE
Checkstyle not failing on wildcard imports

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#65953]
Our style guide (https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines) says that wildcard imports will cause the build to fail, but when I tested this, checkstyle did not fail for `import java.util.*`

**Comment by breskeby** [comment]
@not-napoleon hey, Can you tell me how to reproduce this? I just tried it locally but here I get the expected checkstyle failure: https://gradle-enterprise.elastic.co/s/7ablkcx6ff5we

**Comment by not-napoleon** [comment]
Huh.  I think this was an error on my part.  I have several workspaces checked out, and I think I ran precommit in a different workspace than I made the change in.  Seems to be working for me now, sorry about the noise.  I'll close.
