### ISSUE TITLE
Special values for network.host: bogus documentation, confusing error messages

### ISSUE THREAD

**Issue by jelmd** [elastic/elasticsearch#65978]
The (documentation)[https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#network-interface-values] is really confusing wrt. `_[networkInterface]_`. If e.g.
one uses `network.publish_host: _[ hellas1 ]_` one gets strange error messages like
```
org.elasticsearch.transport.BindTransportException: Failed to resolve publish address
...
Caused by: java.lang.IllegalArgumentException: No interface named '[name:hellas1 (hellas1)]' found, got [name:lo (lo), name:hellas0 (hellas0), name:hellas1 (hellas1)]
...
org.elasticsearch.bootstrap.StartupException: BindTransportException[Failed to resolve publish address]; nested: IllegalArgumentException[No interface named '[name:hellas1 (hellas1)]' found, got [name:lo (lo), name:hellas0 (hellas0), name:hellas1 (hellas1)]];
```
And now the casual user wonders: What the heck do they expect wrt. NIC name[s] for  the `network.publish_host` argument? `_[ name:hellas1 (hellas1) ]_`?

**Comment by DaveCTurner** [comment]
It's tricky to think how else to represent this option in the docs; if we just said `_networkInterface_` then it seems just as likely that someone would write literally that and encounter the same error. IMO the best we can do is show an example, as we do today:

> `_[networkInterface]_`
>  .  Addresses of a network interface, for example `_en0_`.

In your case your interface is called `hellas1` so, extrapolating from this example, you should write `network.host: _hellas1_`.

**Comment by jelmd** [comment]
Hmmm, but I do not see any `_[` `]_`  in your suggestion. You suggest to just prefix + suffix the NIC name with an underline and use that one - that's not, what the documentation says.  Also the documented example does not align with `_[networkInterface]_` at all! `[_networkInterface_]` would and in the Unix world `[ _networkInterface_ ... ]` would describe it even better, if one adds a note, that `[]_' are literals ...
