### ISSUE TITLE
Shell scripts fail under POSIXLY_CORRECT

### ISSUE THREAD

**Issue by jelmd** [elastic/elasticsearch#65980]
Trying to follow https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-security.html .
Unfortunately elasticsearch-setup-passwords (elasticsearch-env) seems to be broken:
```
/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
/usr/share/elasticsearch/bin/elasticsearch-env: line 126: syntax error near unexpected token `<'
```

So how to secure elasticsearch?

**Comment by jelmd** [comment]
env: Ubuntu 20.04 (focal), elasticsearch 7.10.0

**Comment by tvernum** [comment]
Are you running on docker? Or did you install the docker version of ES?
 
This line (126)
```
/usr/share/elasticsearch/bin/elasticsearch-env: line 126: syntax error near unexpected token `<'
```
should only be relevant in the docker distribution of Elasticsearch.

**Comment by jelmd** [comment]
No, I'm running it in a LXC zone - so more or less like bare metal.

**Comment by tvernum** [comment]
Thanks.

You paste lines 90-94 of your `elasticsearch-env` file for us?
For example, this is from my local tar install:
```
$ cat -n bin/elasticsearch-env | sed -n -e90,94p
    90
    91	ES_DISTRIBUTION_FLAVOR=default
    92	ES_DISTRIBUTION_TYPE=tar
    93	ES_BUNDLED_JDK=false
    94
```

Do you know how Elasticsearch was installed on this machine? `.deb` package (`apt-get`), or direct download?

The error points to you having a setup that thinks it's the docker install, and we'd need to work out why.

**Comment by tvernum** [comment]
Also, to check on an alternative theory, can you provide the output of:

- `/bin/bash --version`

and

- `uname -a`

**Comment by jelmd** [comment]
No problem:
```
 > cat -n /usr/share/elasticsearch/bin/elasticsearch-env | sed -n -e90,94p
    90	
    91	ES_DISTRIBUTION_FLAVOR=default
    92	ES_DISTRIBUTION_TYPE=deb
    93	ES_BUNDLED_JDK=true
    94	

> /bin/bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

> uname -a
Linux hellas 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mark-vieira** [comment]
@pugnascotia any thoughts here. As Tim says, the line in the script that's complaining shouldn't even be executing here given this is a DEB install.

**Comment by jelmd** [comment]
I guess some underlying scripts are not POSIX compatible and explode.

**Comment by pugnascotia** [comment]
I'm struggling to replicate this. Here's what I tried (more or less).

```shell
docker run -it --rm ubuntu:20.04 bash
cd
apt-get update
apt-get install wget vim
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-amd64.deb
dpkg -i elasticsearch-7.10.2-amd64.deb
echo "xpack.security.enabled: true" >> /etc/elasticsearch/elasticsearch.yml
service elasticsearch restart
/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
```

**Comment by jelmd** [comment]
Is POSIXLY_CORRECT env var set? Otherwise add to the profile or set it manually after you got attached to the zone.

**Comment by pugnascotia** [comment]
Aha, setting `POSIXLY_CORRECT` triggers the problem. I'll look into this, but in the meantime you can work around this by unsetting the env var.
