### ISSUE TITLE
[CI] s3ThirdPartyTest missing required credentials

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#65994]
**Build scan**:
`master` : https://gradle-enterprise.elastic.co/s/ns4cq3v7zotla
`6.8`: https://gradle-enterprise.elastic.co/s/zizu5l2fwz7du

**Failure history**:
Looks like just the 2 occurrences this month:
- [Gradle History](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=A%20problem%20occurred%20evaluating%20project%20%27:plugins:repository-s3%27.%0A%3E%20not%20all%20options%20specified%20to%20run%20against%20external%20S3%20service%20as%20permanent%20credentials%20are%20present&search.relativeStartTime=P28D)
- [Build Stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(process.status),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:process.status,negate:!f,params:(query:FAILURE,type:phrase),type:phrase,value:FAILURE),query:(match:(process.status:(query:FAILURE,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:s3ThirdPartyTest),sort:!(process.time-start,desc)))

**Failure excerpt**:
```
	
* Where:	
Build file '/dev/shm/elastic+elasticsearch+master+multijob+third-party-tests-s3/plugins/repository-s3/build.gradle' line: 124	
	
* What went wrong:	
A problem occurred evaluating project ':plugins:repository-s3'.	
> not all options specified to run against external S3 service as permanent credentials are present	
```

Given there has been no change to `6.8`:`plugins/repository-s3/` since June, I suspect this was an Infra/Vault issue, but it might be worth adding more diagnostic info in the failure (like which variables were sent, and which weren't) in case it keeps happening.

**Comment by original-brownbear** [comment]
I researched this a little and I'll just close this for now. This happened a 3 times in December and was the result of running into an IAM rate limit. 

```
22:01:04 Error reading aws-test/creds/elasticsearch-ci-s3: Error making API request.
22:01:04 
22:01:04 URL: GET [*******]/v1/aws-test/creds/elasticsearch-ci-s3
22:01:04 Code: 502. Errors:
22:01:04 
22:01:04 * Error creating IAM user: Throttling: Rate exceeded
```

this hasn't happened in a while now and I don't think it's worth forwarding this to infra unless it comes up again.

**Comment by arteam** [comment]
The issue seems to be transitory, I haven't seen it failing on CI over the last month. I assume that the S3 credentials are correctly set up on CI now.
