### ISSUE TITLE
Ingest simluate should corece _version also following issue #23823

### ISSUE THREAD

**Issue by gabriel-tessier** [elastic/elasticsearch#65992]
**Elasticsearch version** (`bin/elasticsearch --version`): from version 6.x

**Description of the problem including expected versus actual behavior**:
The description and tests are in the following discuss topic.
https://discuss.elastic.co/t/integer-cannot-be-casted-to-long-bis/257799

I also found the following related issue https://github.com/elastic/elasticsearch/issues/23823
which was closed with this pull request: https://github.com/elastic/elasticsearch/pull/23885

Checking the code, look like the "_version" field was forgotten.

**Comment by gaobinlong** [comment]
Resolved by #66197.
