### ISSUE TITLE
[CI] /mixed_cluster/100_analytics_usage/Basic test for usage stats on analytics indices failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#66021]
**Build scan**: https://gradle-enterprise.elastic.co/s/2y4pdjoguxype/tests/:x-pack:qa:rolling-upgrade:v7.11.0%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F100_analytics_usage%2FBasic%20test%20for%20usage%20stats%20on%20analytics%20indices%7D#1

**Repro line**: `./gradlew ':x-pack:qa:rolling-upgrade:v7.11.0#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/100_analytics_usage/Basic test for usage stats on analytics indices}" -Dtests.seed=B621DD3ABB713FC1 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=cs -Dtests.timezone=America/Juneau -Druntime.java=11 -Dtests.rest.suite=mixed_cluster`

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Bp0%3Dmixed_cluster/100_analytics_usage/Basic%20test%20for%20usage%20stats%20on%20analytics%20indices%7D&tests.unstableOnly=true

**Failure excerpt**:

```
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.xpack.core.XPackFeatureSet$Usage][runtime_fields] |  
-- | --
  | at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) |  
  | at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) |  
  | at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) |  
  | at org.elasticsearch.common.io.stream.StreamInput.readNamedWriteableList(StreamInput.java:1246) |  
  | at org.elasticsearch.xpack.core.action.XPackUsageResponse.<init>(XPackUsageResponse.java:28) |  
  | at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69) |  
  | at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36) |  
  | at org.elasticsearch.transport.TransportService$6.read(TransportService.java:739) |  
  | at org.elasticsearch.transport.TransportService$6.read(TransportService.java:719) |  
  | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1255) |  
  | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1242) |  
  | at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234)


```

**Comment by javanna** [comment]
This was a transient failure, caused by #65600 . I should have disabled bwc tests between its merge and the backport, but I forgot. It's backported to 7.x, so the issue is solved.
