### ISSUE TITLE
Deprecation warnings are written when request deprecation info

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66063]
When calling the `GET /_migration/deprecations` header warnings are written on the response. 

This only happens if system indices exist in the cluster. This occurs because: https://github.com/elastic/elasticsearch/blob/d4d56cb5ffca1fc6f11e616ae54f4391333ea863/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/deprecation/DeprecationInfoAction.java#L202

Is expanding to ALL indices in the cluster, which includes system indices. 

I think this call should either:

A. Always ignore system indices because users cannot take action to adjust them
B. Expand to system indices without warning.

**Comment by gwbrown** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/67312
