### ISSUE TITLE
[guide]  More shard size discussion

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#6606]
It'd be nice to have more discussion on the shard size in the guide.  Now it says this:

```
While there is no theoretical limit to the amount of data that a primary shard can hold, there is a practical limit. What constitutes the maximum shard size depends entirely on your use case: the hardware you have, the size and complexity of your documents, how you index and query your documents, and your expected response times.
```

Somethings I've found anecdotally that would be nice to have in there if they are true:
- Having more total shards then nodes slows down queries quite a bit.
- While most things parallelize reasonably well highlighting multi term queries and the term and phrase suggester have pretty high per shard costs.
- If you have more then 500 indexes you should keep each index in fewer shards to keep the cluster state smaller.
- Shards bigger then a few gigabytes take a long time to copy.

**Comment by javanna** [comment]
This seems well covered in the "Designing for scale" chapter of the definitive guide: https://www.elastic.co/guide/en/elasticsearch/guide/2.x/scale.html .
