### ISSUE TITLE
Why is the INDEX phase of replica shards recovery in elasticsearch so slow?

### ISSUE THREAD

**Issue by wang-rui-dong** [elastic/elasticsearch#66103]
After a data node is restarted, it is found that the replica shards has been in the INITIALIZING state for a long time.
    For the _cat / recovery interface, it is found that most of them are replica shards, which are in the INDEX stage. 
    Does replica shards recovery pull down or incremental?  How to adjust to incremental pull？
    The version of ES is 7.7.
    Thank you for the answers.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wang-rui-dong** [comment]
First of all, thank you very much for your reply. Are always unable to enter the forum address you provide. What is the reason?

**Comment by jasontedor** [comment]
Sorry you're having trouble reaching the forums. I followed the link I provided and it's fine, so there must be something I'm not aware of. Let me find someone from our community team that can help you.

**Comment by wang-rui-dong** [comment]
好的，那等您的消息

**Comment by wang-rui-dong** [comment]
OK. I'll wait for your information

**Comment by markwalkom** [comment]
If you're coming from China, then there may be issues with the great firewall, that we cannot control.

Try heading over to https://elasticsearch.cn/ and asking there, and we have a number of Wechat channels as well :)

**Comment by wang-rui-dong** [comment]
OK, thank you very much
