### ISSUE TITLE
Async Search Status return expired

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#66114]
When async search is expired  we return NOT found 404  even if it still available in task manager or `.async-search` index.

Kibana team requested if it would be possible instead to return expired status in this case.
For example, a response can be:

```js
{
  "id" : <id>,
  "is_expired" : true,
  "is_running" : false,
  "is_partial" : true,
  "start_time_in_millis" : 1583945890986,
  "expiration_time_in_millis" : 1584377890986,
  "_shards" : {
      "total" : 562,
      "successful" : 188,
      "skipped" : 0,
      "failed" : 0
  }
}
```

Related to: https://github.com/elastic/elasticsearch/pull/62947

cc: @lizozom

**Comment by mayya-sharipova** [comment]
First, there is only a short window when searches are expired but not yet deleted,  we potentially can display their status as expired. But after that window they will deleted and we don't have a way to retrieve them anymore as we don't store expired searches.

@lizozom A a bigger question that we were wondering, does Kibana itself store all async search IDs that it fires?  If it does then the only reason the status for the stored ID is returned "NOT FOUND" is because it is expired (or because it was explicitly deleted).  Thus, if Kibana stores all the async search IDs, we don't see the need to add `expiration` status.  Please let us know what you think @lizozom

**Comment by lizozom** [comment]
We can derive the status if needed, I just wanted to make sure I wasn't doing duplicated work.
Feel free to close this issue.

**Comment by mayya-sharipova** [comment]
@lizozom Thank you for the comment.  I will be closing this issue then, as it is better to do this from Kibana, not from elasticsearch, as elasticsearch only temporarily stores expired searches.
