### ISSUE TITLE
Create Watcher from service

### ISSUE THREAD

**Issue by webjoel** [elastic/elasticsearch#66122]
I'm updated version Elastic Cloud from 7.8 to 7.9.3 and option the Create Watcher from Service (APM> Services > my-service > Transactions) is gone.

Has feature removed?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
