### ISSUE TITLE
Consider removing MetadataIndexUpgradeService

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#66143]
In major version *n*, we support indices back to version *n-1*, including all minor versions. This requires support for not only old index data but also metadata, and we have compatibility logic in various places that checks the index version and knows how to read old mapping formats, handle old setting names, etc.

We also support upgrading old index metadata through `MetadataIndexUpgradeService`. Some example operations:
* Marking system indices with a 'is system' flag, to easily identify them going forward
* Archiving unknown or invalid index settings (note we've discussed removing this leniency in #26998)
* Checking that we can read the mappings

My understanding is that this is only guaranteed to run in certain scenarios like opening a closed index or a full cluster restart. Importantly, it may not complete successfully during a rolling upgrade.

Should we consider removing `MetadataIndexUpgradeService`? It seems a bit broken, as we can't rely on upgrades always being run. Instead we'd make use of compatibility logic as described above. And maybe we could still allow certain upgrades through more focused components (like a system index migration framework?)

**Comment by DaveCTurner** [comment]
+1 from me. The fact that it doesn't take effect during rolling upgrades means we basically have to cope with v6-style metadata in v7 anyway, but the fact that it does run sometimes means we may not cover these cases as well as we should.

We already permit certain metadata conditional on the version in which the index was created. This still gives a (rather generous) bound on how long we need to support old things, but makes more sense to me than having the metadata depend on the version of the node that's running things.

**Comment by gwbrown** [comment]
Removing the system index logic from this class shouldn't be too difficult - the logic is not terribly complex, and we already have the same logic in `SystemIndexMetadataUpgradeService` (might move to `SystemIndexManager` soon) as a `ClusterStateListener` to handle the rolling upgrade case.

**Comment by jtibshirani** [comment]
There's support for removing `MetadataIndexUpgradeService`. Some individual tasks:
- [ ] Remove system index logic, relying instead on a component specific to system indices.
- [ ] Stop archiving unknown/ invalid index settings (relates to #26998).
- [ ] Remove `MetadataIndexUpgradeService`. Make sure there's nothing we need to pull out and keep (like logic for validating the index version + mappings).

**Comment by jtibshirani** [comment]
These are the steps we ended up going with:
* Remove system index logic from `IndexMetadataUpgradeService` (#67941)
* Refactor `IndexMetadataUpgradeService` to `IndexMetadataVerifier` (#67547)
