### ISSUE TITLE
SQL: consecutive unary minuses ignored in literals

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#66145]
`SELECT -(-1)` will incorrectly return `-1` (and similar in expressions `SELECT -(-1) + 1` will return `0`).

**Comment by matriv** [comment]
`master` : db2cd3aa864a2611972c85f5c9d35515de5905e3
`7.x` : c0261925b136da08c14a3561c6f34de84ddc0073
`7.12` : e9fb8f31679dfbe235c103fd8e76a30d2d2ceedc
`7.11` : daea94095a3769ddfed6798fba8501129b54859f
