### ISSUE TITLE
Add relevancy to geo_shape queries based on overlap or distance

### ISSUE THREAD

**Issue by shane-axiom** [elastic/elasticsearch#6616]
geo_shape query results should be scored based on percent overlap with or distance from the query shape.

There are references to adding this feature (https://github.com/elasticsearch/elasticsearch/issues/2169 and http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_relevancy_and_score) but I didn't find a specific issue for it. This would be a very powerful enhancement!

**Comment by clintongormley** [comment]
@nknize is this a feature you're planning on implementing?

**Comment by imalygin** [comment]
Do you have any updates for this issue by any chance?

**Comment by ajturner** [comment]
Is there any update on the status of this feature? It's not been in Lucene since 2014, but no update in Elastic since 2015.

**Comment by clintongormley** [comment]
@nknize is working on a new BKD-backed geo-shape field in Lucene, so we definitely won't be making changes like this to the existing geo-shape fields.  I don't know whether scoring-on-overlap will be a feature of the new field type.  Perhaps Nick can comment?

**Comment by Sebruck** [comment]
Any updates on this topic? Is this a planned feature?

**Comment by jpountz** [comment]
Given that shapes are going to be indexed as independent triangles, we won't have access to the total overlap surface at once, so I'll close this issue.

**Comment by shane-axiom** [comment]
@jpountz Are details on the independent triangle index methodology documented anywhere? We need to implement some sort of workaround if this isn't going to be supported natively in elasticsearch, trying to understand the implications.

**Comment by flavienrouiller** [comment]
Hi! Is there anything new about this? Can scores be influenced by how much bounding boxes overlaps?

**Comment by mpurcell1337** [comment]
Looking for the same functionality, to be able to sort by percent overlap between two polygon's Geometry or BoundingBox - underlying mapping is `geo_shape`.
