### ISSUE TITLE
Reconsider CentOS support

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#66170]
Ref:

> [CentOS Project shifts focus to CentOS Stream](https://blog.centos.org/2020/12/future-is-centos-stream/)

We don't want to support CentOS Stream. We'll continue to support CentOS 8 in the v7 series, but drop support for it from the v8 series.

We'll also need to change the base image for our Docker images to something else.

**Comment by mark-vieira** [comment]
I believe the recent changes to CentOS pretty much solidifies this decision. We will not support CentOS Stream going forward but will continue to support CentOS 7 for existing ES versions.
