### ISSUE TITLE
Reindex from Remote using API Key

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#66211]
While attempting to use `_reindex` from remote, I ran into the issue that I cannot use it with an Elasticsearch API Key.

This is a far less generic request compared to #58396.

**Comment by albertzaharovits** [comment]
@dimitris-athanasiou Mentioned this is also necessary in order to support dataframe analytics jobs to run from remote.

**Comment by ywangd** [comment]
Using API key for `_reindex` is possible with the _undocumented_, generic `headers` parameter, e.g.:

```javascript
POST _reindex?wait_for_completion=true
{
  "source": {
    "index": "origin",
    "remote": {
      "host": "http://your_remote_host:9200",
      "headers": {
        "Authorization": "ApiKey N2VkR1puWUJKUXNkRjJrYTlZYm06cDNHazRNMXhTaGE4ZVhCMDFPX3ZNUQ=="
      }
    },
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "copy"
  }
}
``` 
Not sure why it is not documented. But an easy solution is probably just adding documentation.

**Comment by albertzaharovits** [comment]
Good catch @ywangd ! I would've suggested a `headers` parameter as a "fix" for this anyway, so I think documenting is what's left here.

**Comment by dimitris-athanasiou** [comment]
@albertzaharovits I'd like to give an update on that we are no longer planning to use this functionality for data frame analytics. We will rely on CCS instead, which already works with _reindex without needing to configure the `remote` part of the reindex request.

**Comment by henningandersen** [comment]
Looks like this is fixed, closing this.
