### ISSUE TITLE
Docs issue: search.max_buckets default value different in two pages for ES 7.10

### ISSUE THREAD

**Issue by bernardobelchior** [elastic/elasticsearch#66253]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10

**Plugins installed**: []

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

Actual behavior: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-aggregations-bucket.html says that default value for `search.max_buckets` is 65,535, but https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-settings.html#search-settings-max-buckets mentions 10,000.

Expected behavior: both pages should agree on the default value (either 65,535 or 10,000)

**Steps to reproduce**:
 
1. Go to https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-aggregations-bucket.html. You can read 
  > The maximum number of buckets allowed in a single response is limited by a dynamic cluster setting named search.max_buckets. It defaults to 65,535, requests that try to return more than the limit will fail with an exception.
2. The `search.max_buckets` link links [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-settings.html#search-settings-max-buckets), where you can read:
  >  search.max_buckets
  >  (Dynamic, integer) Maximum number of aggregation buckets allowed in a single response. Defaults to 10000. 

These values are conflicting and seems to have been caused in 7.10 only. The 7.9 version of both pages say that the default is `65,535`, as well as [ElasticSearch 7.10 release announcement](https://www.elastic.co/blog/whats-new-elasticsearch-7-10-0-searchable-snapshots-store-more-for-less):
> in 7.9 we increased the search.max_buckets limit to 65,535

Just wanted to bring attention to this, as it is a bit confusing.

**Comment by jrodewig** [comment]
Thanks for raising this @bernardobelchior. The correct default is 65,535.
