### ISSUE TITLE
SearchableSnapshotsPersistentCacheIntegTests. testCacheSurviveRestart failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66278]
**Build scan**:
https://gradle-enterprise.elastic.co/s/xy7c3vznahvoc
**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests.testCacheSurviveRestart" -Dtests.seed=9F0422EA69B04B29 -Dtests.security.manager=true -Dtests.locale=ga -Dtests.timezone=Asia/Yakutsk -Druntime.java=11
```
**Reproduces locally?**:
No, ran it with the same seed, and many different seeds but with other params being the same
**Applicable branches**:
master
**Failure excerpt**:
```
org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests > testCacheSurviveRestart FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <0L> |  
  | but: was <12L> |  
  | at __randomizedtesting.SeedInfo.seed([9F0422EA69B04B29:851033F89C267B6E]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests.testCacheSurviveRestart(SearchableSnapshotsPersistentCacheIntegTests.java:155)
```

**Comment by benwtrent** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/jpxhkvlcqq3ze/console-log?task=:x-pack:plugin:searchable-snapshots:internalClusterTest

```

org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests > testCacheSurviveRestart FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <0L> |  
  | but: was <10L> |  
  | at __randomizedtesting.SeedInfo.seed([98F3DDD081D6BC00:82E7CCC274408C47]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923)
```

**Comment by tlrx** [comment]
It will be muted in https://github.com/elastic/elasticsearch/pull/66289

**Comment by tvernum** [comment]
This failed again (sorry @tlrx)

https://gradle-enterprise.elastic.co/s/7vw5xavdodpwg/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests/testCacheSurviveRestart#1

**Comment by tlrx** [comment]
Thanks @tvernum for reopening, and sorry for the noise. I opened another fix.

**Comment by costin** [comment]
Another instance at
https://gradle-enterprise.elastic.co/s/6l445sanhzsty

**Comment by tvernum** [comment]
This is still failing, and it looks like there's an open PR but it has stalled (due to holidays?)
 - [Recent Failure](https://gradle-enterprise.elastic.co/s/4x6gmxfguuqtc/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests/testCacheSurviveRestart#1)
 - [History](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Australia/Sydney&tests.container=org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests&tests.sortField=FAILED&tests.test=testCacheSurviveRestart&tests.unstableOnly=true)
 - [Stalled PR](https://github.com/elastic/elasticsearch/pull/66578)

Is the PR likely to pick up again, or should we mute?

**Comment by martijnvg** [comment]
Another instance of this failure that I ran into in pr CI for #66178:
https://gradle-enterprise.elastic.co/s/2h3uxcs2ta6zy/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.cache.SearchableSnapshotsPersistentCacheIntegTests/testCacheSurviveRestart#1

**Comment by tlrx** [comment]
The shard eviction mechanism has been improved in #67160, which should in turn fix this issue.
