### ISSUE TITLE
Add explicit testing for Elasticsearch on RHEL

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66305]
Right now we claim support on RHEL for Elasticsearch via our testing on CentOS we which treat as a "good enough" analogue. With the recent news around CentOS Stream and existing CentOS going away, we can no longer rely on this and need to start testing on proper RHEL images.

Other products test on RHEL so we have foundation images available, we should only need add Packer jobs for elasticsearch-ci images based on the existing RHEL images and update our testing matrix accordingly.

**Comment by mark-vieira** [comment]
> Other products test on RHEL so we have foundation images available, we should only need add Packer jobs for elasticsearch-ci images based on the existing RHEL images and update our testing matrix accordingly.

@jonahbull does my statement here sound accurate?

**Comment by jonahbull** [comment]
@mark-vieira Yep

**Comment by mark-vieira** [comment]
I've opened https://github.com/elastic/infra/pull/26347 to start buiding RHEL images for elasticsearch-ci.

**Comment by mark-vieira** [comment]
This was added in 2eda8c1a.
