### ISSUE TITLE
Warn when autoheap is not used

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#66308]
https://github.com/elastic/elasticsearch/pull/65905 is adding automatic configuration of heap size based on roles and memory available. This feature is the future for Elasticsearch; we hope to continue tweaking the auto sizing to further improve it. So we want users to use the auto heap, and we should add a warning when not using the auto heap.

This has one technical hurdle, which is the jvm options parser currently prints out the final jvm options on stdout, and we have no means to pass back such a warning to be emitted. We will need to consider how to split the streams and utilize stderr, or some other bash trick.

**Comment by mark-vieira** [comment]
> We will need to consider how to split the streams and utilize stderr, or some other bash trick.

There should be no need for any such trickery. The way we currently run the options parser in the bash script will only capture stdout, which means we are free to write anything we want to stderr w/o effecting the "result". I can't confirm this works the same for the Windows batch script though.

**Comment by mark-vieira** [comment]
Example:

```
mark@photon:~/workspaces/availableMemory$ export MEMORY_TEST=`./app/build/install/app/bin/app`
Some random message on stderr.
mark@photon:~/workspaces/availableMemory$ echo $MEMORY_TEST
-Xmx64300
```

**Comment by rjernst** [comment]
Ah, thanks @mark-vieira. I had thought for some reason we captured everything as one stream.

**Comment by lucabelluccini** [comment]
An idea to at least have a trace the auto heap sizing is being used might be to output a dummy JVM parameter if the JVM Heap size is generated, like `-Des.heap.autosizing=true`.

**Comment by mark-vieira** [comment]
Where are we at with this @rjernst? Is this something we'd want to surface through the deprecation APIs, as could be done via the mechanism @lucabelluccini describes or are we just looking to log a warning on startup?

**Comment by mark-vieira** [comment]
Sure, but I'm not sure the deprecation logs are strictly appropriate in this case. A "deprecation" implies that this feature is scheduled for removal in the future, so you should stop using it as soon as possible. We have no intention of removing the ability to manually configure heap, we simply discourage it. Based on that, I'm even someone reluctant to add a warning if that's just the right thing to do. Imagine someone from support told you to tweak your JVM arguments based on a particular deployment or use case, and now Elasticsearch yells at you for doing so.

I'm not convinced we should do either until we're satisfied that our auto  heap ergonomics satisfy every use case and folks manually configuring heap are a tiny minority.

**Comment by rjernst** [comment]
That's a fair point. I'm going to close this issue, we can reopen when auto heap is more battle tested.

**Comment by lucabelluccini** [comment]
Sorry to chime in but is there any Monitoring API to tell the auto-heap is being used?
If not, would it be possible to have it or at least have a JVM Flag which might give us the hint it was auto-set?

**Comment by mark-vieira** [comment]
Good point. We could still add some system property flag to indicate that auto heap settings were used. I'm not certain how to surface this information though. I assume there's some mechanism to get the full set of JVM options passed to ES? At the very least we print it on startup so we can just scan logs for something like `-Des.auto-heap.enabled` or something.

**Comment by lucabelluccini** [comment]
Yes, that would be useful. The `_nodes` API returns the JVM flags under `input_arguments`

**Comment by pugnascotia** [comment]
If we wanted to be explicit about it, we could also include it in the `/_nodes` output under something like `.nodes.$NODE_ID.jvm.using_auto_heap`. I'm not if that's much of an improvement over searching in `input_arguments` however.
