### ISSUE TITLE
SQL: enhance the test data set with more data types

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#66325]
This issue is to track the need for more data types in the H2/CSV tests. We're currently missing floating types and bools. These could be obtained from current data set, but would require conversions, so scripting, for filtering, which might be limiting.

Relates: 
* https://github.com/elastic/elasticsearch/pull/66268#discussion_r542569059
* https://github.com/elastic/elasticsearch/pull/66022 (whose goal is to eliminate scripting where possible).

**Comment by wchaparro** [comment]
Superceded by ES|QL
