### ISSUE TITLE
Fixed sidebar in the documentation pages

### ISSUE THREAD

**Issue by mindrones** [elastic/elasticsearch#66337]
Currently scrolling documentation pages also scrolls the sidebar, making it difficult to use the Table of contents, or jump to other parts of the documentation in that most of the times, before navigating, you need to scroll up to the index or the TOC with some degree of precision. In the long run this has proven quite fatiguing to me.

It would be really great if the sidebar was fixed, so that its scroll position was independent from the page scroll.

**Comment by lockewritesdocs** [comment]
Thanks @mindrones -- we're actively working on updates to our doc system to help address this issue. We appreciate your feedback!

**Comment by mindrones** [comment]
@lockewritesdocs cool, is there somewhere to test this? (asking because I can't see a correspondent PR). Thanks!

**Comment by lockewritesdocs** [comment]
@mindrones, we're working on these enhancements internally and will release them when they're complete. There aren't any external-facing PRs for this work, but stay tuned as we continue to work on improvements.
