### ISSUE TITLE
Forbidden APIs checks not applied to all projects

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#66371]
We use [forbidden-apis](https://github.com/policeman-tools/forbidden-apis) to disallow certain methods and classes.

According to the tool's wiki, Java 14 and 15 are supported, but out task implementation appears to be broken. I discovered that the built-in String checks weren’t triggered if I have `RUNTIME_JAVA_HOME=$JAVA14_HOME`, but they were triggered if `RUNTIME_JAVA_HOME=$JAVA11_HOME`. It didn’t matter that `JAVA_HOME=$JAVA11_HOME` in both cases.

I created a small test project that uses Java 14 and just prints to stdout with a `String.format(String,Object...)`. The `forbiddenApisMain` tasks flags that up just fine.

So my conclusion is that our forbidden-apis tasks are partially broken somehow.

**Comment by mark-vieira** [comment]
Can you provide an example of a specific code change which didn't trigger the check? Changing a call to `String.format()` in the `:server` project gave me the correct error.

https://gradle-enterprise.elastic.co/s/a3ikw6rwpvica

Perhaps the code change was in a method already annotated with `@SuppressForbidden` for some other reason?

**Comment by pugnascotia** [comment]
🤦 

I think I was editing a method with a `@SuppressForbidden` annotation. It's a shame you can't suppress specific APIs.

I can't replicate this problem now, but I also can't explain how we [apparently got into trouble with locales](https://gradle-enterprise.elastic.co/s/xf6ss2essmi66/console-log?task=:x-pack:plugin:transform:qa:single-node-tests:javaRestTest), due to `String.format` missing the `Locale` parameter (fixed in f41cee8403e0871c10176fce03d9a8c276aff9d3). The broken test was added in #66177, but CI was green for a merge. See also the [build scan](https://gradle-enterprise.elastic.co/s/f2jid5nhdhhlo).

Very odd, but since I can't replicate I'll close this issue.

**Comment by mark-vieira** [comment]
So the issue here is that the java rest test plugin doesn't apply these checks, so they never ran. Our mess of various rest test plugins is not helping here. We need to get rid of `StandAloneRestTestPlugin` and others.

**Comment by mark-vieira** [comment]
I'm closing this in favor of #63696, which when addressed will solve this root problem.
