### ISSUE TITLE
Build fails to start hdfsFixture due to port conflict

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66377]
We've started getting a number of build failures bringing up test fixtures.

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Failed%20to%20start%20*&search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles

It seems the root cause is that the port (`9999` in this case) seems to be already in use:
```
java.net.BindException: Problem binding to [localhost:9999] java.net.BindException: Address already in use; For more details see:  http://wiki.apache.org/hadoop/BindException
```

The most likely explanation is that there is another instance of this fixture in use at the time. Given the timing, it seems likely that #65832 might be related to this. I'm not sure what logic was in place before to ensure this scenario didn't happen but it looks like we either a) aren't managing parallelism for fixtures like we did before or b) aren't shutting down previous instances as aggressively as we used to.

**Comment by mark-vieira** [comment]
@breskeby do you mind taking a look at this?

**Comment by breskeby** [comment]
Will do. I did changes in that area. Wonder if that might be related.

**Comment by breskeby** [comment]
I can reproduce it locally via `./gradlew :plugins:repository-hdfs:check :x-pack:plugin:searchable-snapshots:qa:hdfs:check`

**Comment by breskeby** [comment]
I think the timing of the stop fixture task execution is causing this. The former wiring didn't guarantee running them in the "right" order neither ( finalizedBy task are not guaranteed to be executed immediately) but the actual implementation made a difference here. Will look for a more robust solution here. Worst case we can wire the previous task order manually

**Comment by mark-vieira** [comment]
Thanks Rene, if we can't come up with a solution quickly we might need to revert these changes. We've had over 100 builds fail due to this just since yesterday so it's a pretty common occurrence even if the previous implementation only worked incidentally.

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Failed%20to%20start%20hdfsFixture&search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles

**Comment by breskeby** [comment]
As said, how it was done before wasn't bulletproof either. I went ahead and introduced the possibility of dynamically setting the port on these fixtures. This should be a more robust solution and also allow us to run these tests in parallel. There was even an older todo on this: https://github.com/elastic/elasticsearch/blob/bf5866048262d897ede629293b6fe26c3b108b7a/test/fixtures/hdfs-fixture/src/main/java/hdfs/MiniHDFS.java#L101

the PR with a fix is here: https://github.com/elastic/elasticsearch/pull/66440
