### ISSUE TITLE
[CI] CanMatchPreFilterSearchPhaseTests failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66380]
Various test cases in `CanMatchPreFilterSearchPhaseTests` have started failing. It's likely something has changed.

**Build scan**:
https://gradle-enterprise.elastic.co/s/t3srm4doj4clw/tests/:server:test/org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests/testCanMatchFilteringOnCoordinatorThatCanNotBeSkipped#1

**Repro line**:
`./gradlew ':server:test' --tests "org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests.testCanMatchFilteringOnCoordinatorThatCanNotBeSkipped" -Dtests.seed=5172F962631A5CBE -Dtests.security.manager=true -Dtests.locale=ar-QA -Dtests.timezone=Europe/Lisbon -Druntime.java=11`

**Reproduces locally?**:
Did not reproduce for me.

**Applicable branches**:
master and 7.x

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests&tests.sortField=FAILED&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests > testFilterWithFailure FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=6179, name=pool-2-thread-19, state=RUNNABLE, group=TGRP-CanMatchPreFilterSearchPhaseTests]

        Caused by:
        java.lang.AssertionError: Unexpected failure
            at __randomizedtesting.SeedInfo.seed([6CA68C2C31BB214F]:0)
            at org.elasticsearch.action.search.AbstractSearchAsyncAction$2.onFailure(AbstractSearchAsyncAction.java:313)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
```

**Comment by mark-vieira** [comment]
@fcofdez you made some recent changes here, can you take a look or route this to the proper place?

**Comment by fcofdez** [comment]
Yes, we already reverted the assertion on:
https://github.com/elastic/elasticsearch/pull/66360
https://github.com/elastic/elasticsearch/pull/66382
