### ISSUE TITLE
[CI] ExecuteWatchQueuedStatsTests test timing out

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66392]
**Build scan**:
https://gradle-enterprise.elastic.co/s/gzppknprufrms/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests/testQueuedStats#1

**Repro line**:
`./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests.testQueuedStats" -Dtests.seed=C4007BD5948B7DF2 -Dtests.security.manager=true -Dtests.locale=nb -Dtests.timezone=America/Havana -Druntime.java=11`

**Reproduces locally?**:
No.

**Applicable branches**:
Looks like master only

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests&tests.sortField=FAILED&tests.test=testQueuedStats&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.watcher.execution.ExecuteWatchQueuedStatsTests > testQueuedStats FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([C4007BD5948B7DF2]:0)
```

**Comment by mark-vieira** [comment]
This has happened 4 times in the last week.

**Comment by dimitris-athanasiou** [comment]
Another timeout here: https://gradle-enterprise.elastic.co/s/6m2fk77hqm37g

**Comment by dimitris-athanasiou** [comment]
This doesn't happen too often but it's definitely worth looking into

**Comment by tlrx** [comment]
Another timeout: https://gradle-enterprise.elastic.co/s/f7l6k3iq3cspe

**Comment by valeriy42** [comment]
Another timeout here https://gradle-enterprise.elastic.co/s/vx332sadw3tno
It happened 4 times in the past week.

**Comment by probakowski** [comment]
Another one https://gradle-enterprise.elastic.co/s/l3iuvolx5g4ms

**Comment by tlrx** [comment]
This test is failing for months now and I did not find any evidence of investigation of the failure so I muted the test in master in (27023aa85d159d0255a18e5b47cca19585cb1d85).

@jakelandis I'm assigning this issue to you so that it can be dispatched in the core-features team, I hope it is ok.
