### ISSUE TITLE
Remove the legacy node role settings

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#66409]
In #54998 targeting 7.9.0, we introduced a new `node.roles` settings for configuring the roles that a node has. These supersede the legacy node settings such as `node.data`, `node.master`, etc., which were deprecated in the same release. For example, to configure a dedicated ML node, previously you would use `node.ml: true` and now you’d use `node.roles: [ “ml” ].` 

We intend to remove the legacy node role settings in the 8.0.0 release of Elasticsearch. This issue is a placeholder for following that work.

**Comment by hendrikmuhs** [comment]
once decided, `node.transform`, see `TRANSFORM_ENABLED_NODE` in `org.elasticsearch.xpack.transform.Transform` needs to be removed as well.

**Comment by jasontedor** [comment]
Closed by #71163
