### ISSUE TITLE
Undocumented(?) change in default for wait_for_active_shards on close index requests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#66419]
In 7.x the default for `?wait_for_active_shards` on a `POST /index/_close` request is `NONE` (i.e. do not wait) whereas in 8.0 it defaults to `DEFAULT` (i.e. whatever the index metadata says). I took a quick look at the breaking changes docs for 8.0 and didn't see this mentioned, and nor do I see anywhere that we're emitting deprecation logs indicating the change in behaviour.

This caught me out when writing some tests (see https://github.com/elastic/elasticsearch/pull/66415). Should we consider this a breaking change and warn on cases where folk are relying on it? Perhaps not, it might not break anything. I'm opening this issue to remind us to discuss it at some point before releasing 8.0.

@tlrx WDYT?

**Comment by tlrx** [comment]
Looking at the list of changes when the replication of closed indices was merged in master (#39499) and more precisely at #38854 I see nothing that documents the `NONE` to `DEFAULT` change so I think I missed to do it. When the change was merged in 7.2 [we decided to use `NONE`](https://github.com/elastic/elasticsearch/pull/38854#discussion_r257167004) to keep the existing behavior of immediate closing (before 7.2 closing indices was also a way to get rid of unassignable indices...) but it should have been documented as a change for 8.0.

So I agree with you and I think the NONE to DEFAULT move should be documented as breaking in 8.0.

**Comment by DaveCTurner** [comment]
Ok :+1: I opened #66543 for the breaking changes doc and #66542 to add deprecation warnings.

**Comment by DaveCTurner** [comment]
I think it was JFK that once said

> We do these things not because they are easy, but because we thought they would be easy.

It turns out we have to add a new value to the `?wait_for_active_shards` parameter to indicate that you want the default behaviour. I opened #66575 to do that.

**Comment by DaveCTurner** [comment]
This is still open because #67246 was reverted, see https://github.com/elastic/elasticsearch/pull/67246#issuecomment-759567388.

**Comment by DaveCTurner** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/67527
