### ISSUE TITLE
mapping fields xxx cannot be replaced during template composition

### ISSUE THREAD

**Issue by amingo123** [elastic/elasticsearch#66426]
I have index message202001,message202002,message202003... created on ES7.8.0 with alias message. These index are migrated from ES6.4.0

When i try to create new index as below,
PUT /**message202010**
{
  "mappings": {
    "properties": {
      "**CrashStatus**": {
        "type": "keyword"}}}}

i got the error message:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "mapping fields [CrashStatus] cannot be replaced during template composition"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "mapping fields [CrashStatus] cannot be replaced during template composition"
  },
  "status" : 400
}
![image](https://user-images.githubusercontent.com/8415292/102319399-c7e16500-3fb5-11eb-811b-36858d640097.png)

I tried index names: 'messag2020', 'xmessage2020' and any other names are not begin with 'message' can be created successfully. Or change the property name CrashStatus can work as well. CrashStatus field exists in other message index.

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
