### ISSUE TITLE
Cross-cluster restore from snapshot when snapshot includes snapshot backed indices

### ISSUE THREAD

**Issue by zanbel** [elastic/elasticsearch#66431]
There are scenarios where a user will like to "clone" a cluster from another cluster's snapshot by creating a new cluster and then restoring from a remote cluster's snapshot.  Another use case is restoring a specific index from a remote cluster's snapshot. 

These scenarios are currently not supported if the cluster includes snapshot backed indices or if the specific index we wish to restore is a snapshot backed index.  There is a workaround to achieve the above, but it's not trivial and error-prone.

The ideal situation will be for Elasticseach to handle restoring snapshot backed indices as part of the restore procedure.

// cc @dakrone @jasontedor @AlexP-Elastic @bleskes @andrew-moldovan

**Comment by DaveCTurner** [comment]
Please try to avoid mixing the phrase ["frozen index"](https://www.elastic.co/guide/en/elasticsearch/reference/current/frozen-indices.html)" with the concepts surrounding searchable snapshots that we're discussing here.

Today you can restore a snapshot containing searchable snapshot indices into another cluster and they will already end up in the same "phase" as before. I believe the only restriction on this is that the repositories containing the searchable snapshot indices must be registered under the same names in both clusters. Is that the only problem you're asking about, or are you describing other issues too?

**Comment by zanbel** [comment]
Thanks for the feedback @DaveCTurner. I've updated the title and comment to reflect it's a snapshot backed index to focus on the more immediate use case.

**Comment by zanbel** [comment]
Sorry for missing your question. In cloud, the built-in restore from snapshot functionality uses the preconfigured `found-snapshots` repo so they should have the same name. @AlexP-Elastic can you confirm this is the only scenario we wanted to address here?

**Comment by DaveCTurner** [comment]
I think this is fully addressed by the linked issues so I'm closing it.
