### ISSUE TITLE
Increase log levels of definitely-broken network disconnects

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#66473]
In #51612 we promoted log messages regarding unexpected network disconnects from `TRACE` to `DEBUG`. Some users have indicated that they'd like even more visibility on these by default, at least for the ones that are definite indications of something going wrong at the network level, which IMO is at least `Connection reset` and `Connection timed out` on Linux. Normally we shouldn't be seeing either of these so I'm opening this issue to propose moving them all the way up to `WARN`.

I'm not decided on whether to push for this change in 7.x or to wait for 8.0. The trouble with doing it in 7.x is that transport clients are still in use in these versions and clients may have less reliable connectivity to Elasticsearch than we expect for node-to-node connections, so some of the logs we emit might not be actionable for the server administrator.

We might need a sync discussion on this topic eventually but for now I'd prefer to gather async thoughts here first.

**Comment by original-brownbear** [comment]
We discussed this in our sync today and everyone was in agreement that the benefits of doing this in 7.x outweigh this issue:

```
 The trouble with doing it in 7.x is that transport clients are still in use in these versions and clients may have less reliable connectivity to Elasticsearch than we expect for node-to-node connections, so some of the logs we emit might not be actionable for the server administrator.
```

which should be rare and while not always actionable you could argue that knowing that client connections are unstable will often be valuable as well -> Removing team-discuss here and unless you have any concerns @DaveCTurner this one should be good to go.

**Comment by DaveCTurner** [comment]
I looked at this some more and concluded that even `Connection reset` and `Connection timed out` can have benign causes sometimes so it wouldn't be appropriate to have them at `WARN` level, but I do see value in reporting them at `INFO` level so they appear in the logs by default. See #81768.
