### ISSUE TITLE
Support installing and removing plugins when a Docker container starts

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#66476]
Our current advice regarding plugins and running Elasticsearch in Docker is to extend the image and install all the required plugins. However, this may not be practical if there is a need to add or remove plugins dynamically.

We would therefore like to have a mechanism to specify the desired plugins when a container starts. Note that in the case where the `plugins` directory has been persisted across restarts, e.g. as a bind-mounted volume, then plugins may be installed that now need to be removed.

**Comment by mark-vieira** [comment]
For inspiration, Grafana's Docker image does this by simply providing a list of plugins you wish to install via an environment variable. I've found this method pretty convenient.

https://grafana.com/docs/grafana/latest/installation/docker/#install-official-and-community-grafana-plugins

**Comment by pugnascotia** [comment]
Yes, I came across something similar with the Jenkins Docker image.

**Comment by mark-vieira** [comment]
After discussion with @elastic/cloud-delivery we've decided it's sufficient to provide a way to bulk remove plugins using the CLI tools. See #69063.

**Comment by pugnascotia** [comment]
Related: #61385

**Comment by alpar-t** [comment]
#69840 Is also relevant in this context as it provides a means to implement this.
