### ISSUE TITLE
Add support for user bundles to Docker images

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#66479]
Some aspects of Elasticsearch configuration requires extra files to be provided to Elasticsearch. Where a cluster user is in full control of the environment, they can simply arrange for the correct files to be put into the correct places, e.g. when bind-mounting the `conf` directory. However when the cluster user is not the platform operator, then it becomes harder for user-provided files to be made available to Elasticsearch.

We would like to support the concept of "user bundles". A bundle is a zip file containing configuration files, dictionaries, etc. The Elasticsearch Docker image would be passed the URIs of one or more bundles, which would be downloaded and installed on startup.

**Comment by mark-vieira** [comment]
@mieciu has been kind enough to offer to walk us through the user experience on providing these configuring bundles in cloud. I think that exercise will provide us better context to make a decision on how best to move forward on this one.

**Comment by mark-vieira** [comment]
So @mieciu walked us through how user bundles are handled in Cloud. Initially it was described that there was logic there for validating bundles but that's actually not the case, they are just naively unpacked into the `/app` directory. I'm inclined to think this is another thing that could just be handled with https://github.com/elastic/elasticsearch/issues/66479 and that this doesn't need to become a formal concept that's part of the vanilla image.

@alpar-t can we close this in favor of continuing to handle user bundles via https://github.com/elastic/elasticsearch/issues/66479?

**Comment by pugnascotia** [comment]
@mark-vieira did you intend to link to #69840?

**Comment by mark-vieira** [comment]
Yep, thanks. I updated my comment.

**Comment by alpar-t** [comment]
I've reached out in an email to further discuss this. I would not like to do this in a startup script as that would make us depend on tools to download the bundles that have nothing to do with ES. In fact I would prefer such tools are not easily accessible to the startup script (their not on path). 
I agree there are other options  to  implement this than adding support tot he docker image, but I would ask to keep this open until we settle on an approach that we can link here before closing.

**Comment by mark-vieira** [comment]
Yea, we have similar concerns on our end to having script logic that reaches a level of complexity where it's having to make network requests. I think we'll probably end up investigating other solutions here.

**Comment by mark-vieira** [comment]
I'm closing this for now, we can reopen when we decide this is the way forward.
