### ISSUE TITLE
elasticsearch docker image problem

### ISSUE THREAD

**Issue by jiankunking** [elastic/elasticsearch#66487]
1、es should not be the first to start in the container, because the process number is 1, the jvm command cannot be executed。
2、es should provide a quick configuration security manager, so that troubleshooting can be quickly closed。

[https://github.com/alibaba/arthas/issues/1626](https://github.com/alibaba/arthas/issues/1626)

**Comment by mark-vieira** [comment]
> es should not be the first to start in the container, because the process number is 1, the jvm command cannot be executed

I'm not sure I understand the issue you are having. How does the pid of the elasticsearch process impact what you are trying to do?

**Comment by jiankunking** [comment]
> impact
When I want to use the JVM Tool or [Arthas](https://github.com/alibaba/arthas) to debug an online problem.

**Comment by jiankunking** [comment]
> > es should not be the first to start in the container, because the process number is 1, the jvm command cannot be executed
> 
> I'm not sure I understand the issue you are having. How does the pid of the elasticsearch process impact what you are trying to do?

When I want to use the JVM Tool or Arthas to debug an online problem

**Comment by mark-vieira** [comment]
I think you just need to give the tool the correct pid. Perhaps it's not detecting it properly. You should be able to grab the actual pid like so:

```
jps | grep Elasticsearch | awk '{print $1}'
```

**Comment by jiankunking** [comment]
> jps | grep Elasticsearch | awk '{print $1}'

![1](https://user-images.githubusercontent.com/15723050/106242147-3155c400-6242-11eb-936c-9f5da892f588.png)

pid is not 1？

**Comment by mark-vieira** [comment]
In that case it looks like it is, but I believe in our Docker container it isn't, the entrypoint script would be pid 1. Which version of Elasticsearch is this? It's possible there's just an incompatibility between either the JVM used to run elasticsearch and the JVM of the tool you're trying to use.

**Comment by jiankunking** [comment]
elasticsearch:6.5.1 and elasticsearch:7.6.2 Is always the same，The next one is 7.6.2
![1](https://user-images.githubusercontent.com/15723050/106243482-73800500-6244-11eb-8426-d3cb819b0446.png)

I find this problem is through this: https://github.com/alibaba/arthas/issues/1626

**Comment by mark-vieira** [comment]
Sure, I'm quite certain this has nothing to do with the process pid and something to do with JVM incompatibilities. I'm not familiar with the arthas tool but perhaps reach out to the developers of that to see if they can provide some insight. At this point I'm going to close this issue because this isn't a problem with Elasticsearch so far as I can tell.

**Comment by mark-vieira** [comment]
Yes, looks this changed, I'm not sure exactly when. We no longer start Elasticsearch as pid 1 in our docker images.
