### ISSUE TITLE
Is it possible to limit the number of returned documents by setting a threshold for document cosine similarity?

### ISSUE THREAD

**Issue by Wenorm** [elastic/elasticsearch#66494]
Is it possible to limit the number of returned documents by setting a threshold for document cosine similarity?

**Comment by benwtrent** [comment]
Yes, there are two ways:

 - Via approximate knn search with `cosine` similarity and setting `similarity` with the `knn` clause
 - Scoring via brute force, calculating cosine similarity to calculate the score and then utilizing `min_score`
