### ISSUE TITLE
CI: testTaskCancellationOnCoordinatingNodeLeavingTheCluster fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#66518]
**Build scan**: https://gradle-enterprise.elastic.co/s/df5tjhtcm552m/console-log/raw

**Repro line**: 

```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests.testTaskCancellationOnCoordinatingNodeLeavingTheCluster" -Dtests.seed=4656B267C8C11E43 -Dtests.security.manager=true -Dtests.locale=nl-NL -Dtests.timezone=US/Aleutian -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master

**Failure excerpt**:
```
org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests > testTaskCancellationOnCoordinatingNodeLeavingTheCluster FAILED
    java.lang.AssertionError: No bans on the node 1 expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([4656B267C8C11E43:1D5057DC1747CFB7]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)

```

**Comment by benwtrent** [comment]
Unsure if related: https://gradle-enterprise.elastic.co/s/rc47gnpa33bua

This is a cluster timeout in the task cancellation IT. It is from a build without the recent test mute.

**Comment by csoulios** [comment]
From the test history, it looks that this test fails very often in the last 24 hours. 
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Athens&tests.container=org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests&tests.sortField=FAILED&tests.test=testTaskCancellationOnCoordinatingNodeLeavingTheCluster&tests.unstableOnly=true
