### ISSUE TITLE
testBanOnlyNodesWithOutstandingDescendantTasks fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#66520]
**Build scan**: https://gradle-enterprise.elastic.co/s/rc47gnpa33bua/console-log/raw

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testBanOnlyNodesWithOutstandingDescendantTasks" -Dtests.seed=36A4633D2592BD95 -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Etc/UTC -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure excerpt**:
org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([36A4633D2592BD95]:0)

**Comment by gwbrown** [comment]
Another failure, from 7.x this time https://gradle-enterprise.elastic.co/s/sw5palpj2jbyi.

Looks like the suite is timing out.
