### ISSUE TITLE
Script engines should be aware of the script name

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#6653]
It would be nice if we could access the name of the script from the script engine framework so it could be logged when errors occur. This would be especially helpful for additional logging for users with dynamic scripting disabled.

**Comment by javanna** [comment]
Heya @dakrone are you working on this? If not can you elaborate on what you mean? Where should the script name be available but it isn't?

**Comment by dakrone** [comment]
@javanna when exceptions are thrown in a script, it's nice to know in the logs which script (if it came from on disk) the error came from, I believe right now we use:

```java
private String generateScriptName() {
  return "Script" + counter.incrementAndGet() + ".groovy";
}
```

Which works for dynamic scripts (maybe we want to rename it "dynamic-script1.groovy" or something to be extra clear. The on-disk ones should have their name clearly in the exception/logging.

**Comment by jdconrad** [comment]
@rjernst Would you please take a look when you get a chance?  Thanks!
