### ISSUE TITLE
Support run-as user in Watcher search input

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#66544]
While it's possible to define a run-as header in the `HTTP input` for watcher, there's no way to specify a run-as user in the `search input`.  It would be nice to be able to pass a run-as user in the `search input` to limit the scope of the query to indices that the user has permissions to access.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
