### ISSUE TITLE
QL: Upfront validation of exact fields

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#66600]
Resolution of exact matching on `text` fields by looking at the exact variant happens late currently in the engine instead of upfront at validation time. It's an optimistic approach which works however it has some issues:
- if there are issues in determining the exact field, an error is being return instead of a message missing context
- the resolution happens closely to the translation phase, when most of the work has been done
- there is a small risk of the field being used in multiple places causing the translation to use both the exact and inexact form within the same query which can only lead to issues.

Reworking the exact field handling upfront inside the analyzer should simplify this as the conversion happens in only one place. This means exacting the various places where the conversion applies, including grouping (both SQL and EQL) and string functions (SQL) and centralizing them into a rule, ideally with some templating for ease of use.

**Comment by wchaparro** [comment]
Superceded by ES|QL
