### ISSUE TITLE
Better control of number of snapshots in cluster

### ISSUE THREAD

**Issue by psanz-estc** [elastic/elasticsearch#66603]
SLM allows to define snapshot retention periods without any limitation, ie:

```
      "retention": {
        "expire_after": "365d",
        "min_count": 10,
        "max_count": 9000
      }
```

But that doesn't take into consideration the impact a large number of snapshots has in the system (ie metadata size), impactic whole cluster operations.

Should we consider some sort of hard limit for the number of snapshots we can handle? Or maybe adding a warning in Kibana if the number of snapshots go above a threshold?

**Comment by Leaf-Lin** [comment]
This is related to the scalability work https://github.com/elastic/elasticsearch/issues/74350

**Comment by original-brownbear** [comment]
We have the `max_number_of_snapshots` setting now to hard-limit snapshot count if desired and made big strides in terms of how many snapshots we support.
