### ISSUE TITLE
FullClusterRestartIT.testDataStreams fails during BWC when started before midnight and finishes after midnight

### ISSUE THREAD

**Issue by palesz** [elastic/elasticsearch#66606]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/15000/
Build scan: https://gradle-enterprise.elastic.co/s/dv3bwzpn5axfu/tests/:x-pack:qa:full-cluster-restart:v7.11.0%23upgradedClusterTest/org.elasticsearch.xpack.restart.FullClusterRestartIT/testDataStreams#1

The build started on `Dec 17, 2020 11:47:24 PM` and finished `22 min` later with the following exception in the test: 

```
org.junit.ComparisonFailure: expected:<.ds-ds-2020.12.1[8]-000001> but was:<.ds-ds-2020.12.1[7]-000001>	
```

**Comment by rjernst** [comment]
Another case of this in a PR: https://gradle-enterprise.elastic.co/s/3fkytnugezod4
