### ISSUE TITLE
TransportReindexAction could not found in maven repo es6.5.4

### ISSUE THREAD

**Issue by 15838028035** [elastic/elasticsearch#66660]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: []

**JVM version** (`java -version`): jdk1.8

**OS version** (`uname -a` if on a Unix-like system): win10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

when i download https://github.com/elastic/elasticsearch/ , and checkout 6.5 branch ,
i found there's a class TransportReindexAction,  but i can't fould it in maven repo  ,
i have add es dependency in  pom.xml.

	<dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>${es.version}</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>${es.version}</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>${es.version}</version>
        </dependency>

what should i do ?    is there a deme for reindex remote ?

**Comment by calm4wei** [comment]
Is the reindex module compiled under the elasticsearch project?

**Comment by 15838028035** [comment]
no . i only download maven es dependency.

**Comment by mayya-sharipova** [comment]
@15838028035  What are you trying to do? Are you trying to use reindex operation in elasticsearch client?

**Comment by 15838028035** [comment]
Yes !

发自我的iPhone
