### ISSUE TITLE
CCR QA tests fail in FIPS mode when run in CI

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#66661]
**Build scan**: https://gradle-enterprise.elastic.co/s/cazo3ytgekmus

**Repro line**:

**Reproduces locally?**:  Yes, but only when checkPart2 is run ( as opposed to the QA project )

**Applicable branches**: master

**Failure history**:

**Failure excerpt**:

In the build scan attached `:x-pack:plugin:ccr:qa:restart:follow-cluster` fails to start after 120 seconds but there is nothing in the logs identifying why. @breskeby theorized that this might have to do with certain tasks that run in parallel, but attempts to trigger this outside of checkPart1 , i.e. with 
```
./gradlew :x-pack:plugin:ccr:qa:restart:follow-cluster :x-pack:plugin:ccr:internalClusterTest :x-pack:plugin:ccr:qa:multi-cluster:middle-cluster
```

doesn't reproduce locally. 

CCR QA tests have been muted in fips mode for now.

**Comment by ywelsch** [comment]
Can we get this a bit more investigated by @breskeby? This looks very much like a slow start up of the ES process (taking longer than 120s). I don't know how to get the full logs of the ES process but the partial logs from the console output are strongly suggesting this is not a CCR issue, but an infrastructural / build issue.

**Comment by breskeby** [comment]
I will have another look on this.

**Comment by breskeby** [comment]
having a hard time reproducing this failure locally

**Comment by jkakavas** [comment]
Given that this has failed ever only on my local workstation while I was preparing the latest FIPS related CI changes and never on our CI, I'll close this issue for now. 

> This looks very much like a slow start up of the ES process (taking longer than 120s)

It could be that my workstation is low on available entropy ( latest bouncy castle fips versions are more hungry ) and that caused some cryptographic operations to be blocked, ending up in ES failing to start within 120s.
