### ISSUE TITLE
FilterAllocationDecider handles exclude._tier filters not correctly

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#66679]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version (java -version)**: 14.0.1

**OS version (uname -a if on a Unix-like system)**: Mac OS 10.13.6

**Description of the problem including expected versus actual behavior**:

When we setup a cluster with only one node, and set the node as `data_hot` and `master`:

```
node.roles: [ data_hot, master ]
```
then we set cluster level shard allocation filter: `"cluster.routing.allocation.exclude._tier": "data_cold"`, 
finally, new index'shards canot be allocated because:

```
{
    "index":"z",
    "shard":1,
    "primary":true,
    "current_state":"unassigned",
    "unassigned_info":{
        "reason":"INDEX_CREATED",
        "at":"2020-12-21T09:35:07.850Z",
        "last_allocation_status":"no"
    },
    "can_allocate":"no",
    "allocate_explanation":"cannot allocate because allocation is not permitted to any of the nodes",
    "node_allocation_decisions":[
        {
            "node_id":"c7uiAGEAQTO3lY6MjGAGVQ",
            "node_name":"node1",
            "transport_address":"127.0.0.1:9300",
            "node_attributes":{
                "xpack.installed":"true",
                "transform.node":"false"
            },
            "node_decision":"no",
            "weight_ranking":1,
            "deciders":[
                {
                    "decider":"filter",
                    "decision":"NO",
                    "explanation":"node matches cluster setting [cluster.routing.allocation.exclude] filters [_tier:"data_cold"]"
                }
            ]
        }
    ]
}
```

**Steps to reproduce**:

1. setup a cluster with only one node:

```
node.roles: [ data_hot, master ]
```
2. PUT _cluster/settings

```
{
  "transient": {
    "cluster.routing.allocation.exclude._tier": "data_cold"
  }
}
```

3. Create a new index with setting `index.routing.allocation.include._tier_preference:"data_hot"`
4. GET _cluster/allocation/explain

**Comment by gaobinlong** [comment]
By debuging the code, I found the bug comes from the line:
https://github.com/elastic/elasticsearch/blob/cdddb3b161e42c2e81a934df0955f545d0d432b5/server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java#L185,

so if we set a cluster level `exclude._tier` setting, `clusterExcludeFilters.match(node)` always `true`:

https://github.com/elastic/elasticsearch/blob/cdddb3b161e42c2e81a934df0955f545d0d432b5/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDecider.java#L193.

The index level `exclude._tier` setting has the same issue.

**Comment by gaobinlong** [comment]
Maybe we can remove the `_tier` filters from the `FilterAllocationDecider`, because they will be handled in `DataTierAllocationDecider`.

**Comment by dakrone** [comment]
@gaobinlong I'm working on a fix for this, hopefully will have it today.
