### ISSUE TITLE
Remove deprecated date_histo intervals

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#66715]
We split date_histo intervals between `calendar` and `fixed` intervals in https://github.com/elastic/elasticsearch/pull/33727.  At the same time, we deprecated the older, unified `interval` parameter.

It's been deprecated since 7.2, so we should be good to remove from 8.0 in my opinion.  There is a non-negligible amount of code to handle the old intervals and it'd be great to clean that up.

This issue is a placeholder so we don't forget to remove it as 8.0 grows nearer :)

**Comment by not-napoleon** [comment]
I resolved this with #75000, I just forgot to tell github to close this one.
