### ISSUE TITLE
6.8.13: assert on parsing 7.10.1 warning

### ISSUE THREAD

**Issue by dmivankov** [elastic/elasticsearch#66716]
**Elasticsearch version** (`bin/elasticsearch --version`):
> docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
Version: 7.10.1, Build: oss/docker/1c34507e66d7db1211f66f3513706fdf548736aa/2020-12-05T01:00:33.671820Z, JVM: 15.0.1

**Plugins installed**: []

**JVM version** (`java -version`):
> openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
> Linux nixos 4.14.118 #1-NixOS SMP Fri May 10 15:53:15 UTC 2019 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Consider current state being 6.8 client&server and desired state being client&server 7.10.
Docs say client should be updated last https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html
So that means we need to use 6.8 client with 7.10 server in a transition period.
We have some junit integration tests that start failing if we swap server to 7.10 (hosted via testcontainers).

**Steps to reproduce**:
1. Start client in a unit test / in a jvm with asserts enabled
2. Issue bulkIndexRequest (or almost any other kind of request) with rest high level client 6.8.13 against 7.10.1 server
3. Expect deprecation warnings but no crashes
4. Observe client crash

**Provide logs (if relevant)**:
Server side
> {"type": "deprecation", "timestamp": "2020-12-21T19:46:53,770Z", "level": "DEPRECATION", "component": "o.e.d.a.b.BulkRequestParser", "cluster.name": "docker-cluster", "node.name": "0a3d1b3f7ea5", "message": "[types removal] Specifying types in bulk requests is deprecated.", "cluster.uuid": "4WPCyFH3RzG4OkwYjEiZ1Q", "node.id": "rYSQBAn_Su-4As4uThl95Q"  }

Client gets following warning header
> 299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa "[types removal] Specifying types in bulk requests is deprecated."

Which is a fair warning, later switch to 7.x client should fix it

But the client issues and assert in https://github.com/elastic/elasticsearch/blob/6.8/client/rest/src/main/java/org/elasticsearch/client/Response.java#L193
Which could go unnoticed in a real service, but tests are run with asserts on (-ea jvm flag) and fail.

Client logs
> {"timestamp":{"seconds":1608580839,"nanos":976000000},"severity":"WARNING","message":"request [POST http://localhost:33321/_bulk?timeout\u003d1m] returned 1 warnings: [299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa \"[types removal] Specifying types in bulk requests is deprecated.\"]","sourceLocation":{"file":"RequestLogger.java","line":"65","function":"org.elasticsearch.client.RequestLogger.logResponse"},"context":{}}
Exception in thread "I/O dispatcher 2" java.lang.AssertionError
	at org.elasticsearch.client.Response.assertWarningValue(Response.java:193)
	at org.elasticsearch.client.Response.extractWarningValueFromWarningHeader(Response.java:183)
	at org.elasticsearch.client.Response.getWarnings(Response.java:205)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
