### ISSUE TITLE
Filter for time dont work

### ISSUE THREAD

**Issue by LucasTeodoro** [elastic/elasticsearch#66719]
When i try to filter de created_date(date/time) just in time dont work.
**Elastic version:** 7.6.2

**MAPPING**

{
  "mapping": {
    "_doc": {
      "properties": {
        "campaign_id": {
          "type": "keyword"
        },
        "client_id": {
          "type": "keyword"
        },
        "client_plan_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "client_route_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "connector": {
          "type": "keyword"
        },
        "cost_center_id": {
          "type": "keyword"
        },
        "created_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "destination_addr": {
          "type": "text",
          "norms": false,
          "fielddata": true
        },
        "dropper_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "gateway_gsm_send_id": {
          "type": "keyword"
        },
        "gateway_send_id": {
          "type": "keyword"
        },
        "index": {
          "type": "keyword"
        },
        "jasmin_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "master_connector_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "master_id": {
          "type": "keyword"
        },
        "master_plan_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "message": {
          "type": "text",
          "norms": false
        },
        "message_id_external": {
          "type": "keyword"
        },
        "message_id_jasmin": {
          "type": "keyword"
        },
        "provider": {
          "type": "keyword"
        },
        "provider_submit_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "report_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "report_stat": {
          "type": "keyword"
        },
        "resale_id": {
          "type": "keyword"
        },
        "resale_plan_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "resale_route_cost": {
          "type": "half_float",
          "index": false,
          "null_value": 0
        },
        "route_id": {
          "type": "keyword"
        },
        "sanitized": {
          "type": "boolean"
        },
        "send_by": {
          "type": "keyword"
        },
        "send_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "size": {
          "type": "short",
          "index": false
        },
        "source_addr": {
          "type": "text",
          "norms": false,
          "fielddata": true
        },
        "submit_stat": {
          "type": "keyword"
        },
        "updated_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        }
      }
    }
  }
}

**QUERY:**

GET mt_*/_search
{
  "size": 0,
  "query": {
    "range": {
      "created_date": {
        "gte": "00:00:00",
        "lte": "23:00:00",
        "format": "HH:mm:ss"
      }
    }
  }, 
  "aggs": {
    "buckets": {
      "composite": {
        "sources": [
          {
            "client": {
              "terms": {
                "field": "master_id"
              }
            }
          },
          {
            "day": {
              "date_histogram": {
                "field": "created_date",
                "calendar_interval": "day"
              }
            }
          }
        ]
      }
    }
  }
}

**Response:** 

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "buckets" : {
      "buckets" : [ ]
    }
  }
}

**Comment by mayya-sharipova** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
