### ISSUE TITLE
CI: MixedClusterClientYamlTestSuiteIT#top_hits aggregation failure

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#66728]
Looks like a regression that was picked up by a recent commit by @jtibshirani, hence the assignment.

**Build scan**:

[6.8.14] https://gradle-enterprise.elastic.co/s/vojwlxwvfkjjq
[7.11.0] https://gradle-enterprise.elastic.co/s/qj43lj64clyi6
[7.10.2] https://gradle-enterprise.elastic.co/s/5xcurd4lgok2i
[7.10.2] https://gradle-enterprise.elastic.co/s/wc4y7pg33lpsk
[7.11.0] https://gradle-enterprise.elastic.co/s/cxf7a5zuffbrs
[6.8.14] https://gradle-enterprise.elastic.co/s/emnkvkkawvi6w
[7.11.0] https://gradle-enterprise.elastic.co/s/fpc5nvnazpbcq
[7.10.2] https://gradle-enterprise.elastic.co/s/3lyzj7wimr652
https://gradle-enterprise.elastic.co/s/fhee626sjqywg

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.11.0#mixedClusterTest' \
  -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.aggregation/200_top_hits_metric/top_hits aggregation with nested documents and disabled _source}" \
  -Dtests.seed=191827059CB1C8D9 \
  -Dtests.security.manager=true \
  -Dtests.bwc=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Asia/Calcutta \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.11.0#mixedClusterTest' \
  -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.inner_hits/20_highlighting/Unified highlighter with stored fields and disabled source}" \
  -Dtests.seed=191827059CB1C8D9 \
  -Dtests.security.manager=true \
  -Dtests.bwc=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Asia/Calcutta \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.11.0#mixedClusterTest' \
  -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.aggregation/200_top_hits_metric/top_hits aggregation with nested documents and disabled _source}" \
  -Dtests.seed=191827059CB1C8D9 \
  -Dtests.security.manager=true \
  -Dtests.bwc=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Asia/Calcutta \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.11.0#mixedClusterTest' \
  -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.inner_hits/20_highlighting/Unified highlighter with stored fields and disabled source}" \
  -Dtests.seed=191827059CB1C8D9 \
  -Dtests.security.manager=true \
  -Dtests.bwc=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Asia/Calcutta \
  -Druntime.java=8
```

**Applicable branches**:
6.8-master

**Failure excerpt**:
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search.aggregation/200_top_hits_metric/top_hits aggregation with nested documents and disabled _source}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search.inner_hits/20_highlighting/Unified highlighter with stored fields and disabled source}

**Comment by costin** [comment]
A few more failures below - looks like the issues got propagated through the builds. Listing here just a few for the record:

https://gradle-enterprise.elastic.co/s/sswwcdblgodmo
https://gradle-enterprise.elastic.co/s/szbrokbyft2ue

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/419/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+EAR/417/console

**Comment by jtibshirani** [comment]
This was fixed yesterday -- these new tests accompany a bugfix, and I initially missed the newly-cut 7.11 branch while backporting. That is why mixed cluster tests against 7.11 are failing, the branch did not contain the fix. I'm closing this out and will keep an eye out to make sure there aren't further failures.
