### ISSUE TITLE
Extended kibana user

### ISSUE THREAD

**Issue by anomaliyao** [elastic/elasticsearch#66729]
Is it possible to create a user with such privileges so that it is as an extended kibana user, but without the rights to remove any indexes from the cluster?
- rights to create and delete users are available
- editing widgets and dashboards
- adding / editing index templates
- etc

**Comment by mayya-sharipova** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
