### ISSUE TITLE
Simulating a watch with an index action causes actual writes if multiple docs are specified

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#66735]
**Elasticsearch version** (`bin/elasticsearch --version`): all 6.x/7.x

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:
Simulating a watch with an index action causes actual writes, but only when multiple documents are requested to be indexed. Single documents do not get indexed. This behaviour is inconsistent internally, and also with respect to the behaviour of other actions. For example, the email action does not send an email under simulation. I consider it appropriate, therefore, that the index action should never actually index any documents, no matter if one or more are specified.

**Steps to reproduce**:
Please find attached a full repro case, to be executed in Kibana Dev Console.

[final_repro.json.zip](https://github.com/elastic/elasticsearch/files/5729635/final_repro.json.zip)

**Comment by dakrone** [comment]
I believe this was fixed by #76820, so closing this.
