### ISSUE TITLE
Wildcards for fields in fuzzy like this query

### ISSUE THREAD

**Issue by klappvisor** [elastic/elasticsearch#6674]
Right now you can use fields property in fuzzy like this query to specify list of fields to query against, but if your documents have nested objects inside and you want to search only against all fields inside particular nested object, you have to specify list of all properties with full path. For example with the following document:
```
{"id": "some_id",
"en": {
    "title": "en_title",
    "description": "en_description",
    /* ... */
},
"nl": {
    "title": "nl_title",
    "description": "nl_description",
    /* ... */
}}
```

In some cases you want to search only through **en** subdocument, then fuzzy like this should be:
```
{"query": {
    "flt": {
        "like_text": "search string",
        "fields": [ "en.title", "en.description", /* all other fields under en */ ]
}}}
```

It would be convenient to use wildcards to specify fields especially if you don't have defined list of fields here or list is too big, to have query like this:
```
{"query": {
    "flt": {
        "like_text": "search string",
        "fields": [ "en.*" ]
}}}
```
May be it's worth to add include/exclude patterns. It's more or less the same feature as for _source: [source filtering](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-source-filtering.html)
```
{"query": {
    "flt": {
        "like_text": "search string",
        "fields": {
            "include": [ "obj1.*", "obj2.*" ],
            "exclude": [ "categories.*" ]
}}}}

**Comment by clintongormley** [comment]
FLT has been removed. Closing
