### ISSUE TITLE
The total storage space of the cluster is incorrect

### ISSUE THREAD

**Issue by calm4wei** [elastic/elasticsearch#66789]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): CentOS release 6.5 (Final)

**Description of the problem including expected versus actual behavior**:
env: 
3 servers, single-machine dual-instance deployment, 6 nodes in total
Each server has 6 disks, 3.6T per disk, respectively /data00,/data01,/data02,/data03,/data04,/data05
Each node uses 3 disks, a total of 3*3.6T storage space
expected:
The total storage space of the cluster is 3*6*3.6T
actual:
The total storage space of the cluster is 3*3*3.6T

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.Build an es cluster, including 3 servers, single-machine dual-instance deployment, 6 nodes in total.
Each node independently uses half of the server's disks.(The server contains multiple disks)
 2.get _cluster/stats
view the result of fs.total_in_bytes
 3.Compare the total storage size actually used with the fs.total_in_bytes of the cluster obtained using _cluster/stats

**Comment by nik9000** [comment]
> single-machine dual-instance deployment

I'm not sure the degree to which we want to work super hard to support this. Though I am curious how you assigned the disks. It looks like we attempt to get the free space of disk that contains the data directory. If they aren't separate mount points then ES really doesn't have a way to know that it should only use half the space.

**Comment by nik9000** [comment]
Oh! I see, looking at #66790 its about the scenario where you share disks like I said but it is correcting the total. That makes sense.

**Comment by joegallo** [comment]
Closing in favor of #24472.
