### ISSUE TITLE
Tests fail in fips mode because of default hashing algorithm 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#66819]
**Build scan**: 

https://gradle-enterprise.elastic.co/s/bdqsrnib6twrc/failure#1
**Repro line**:

**Reproduces locally?**: Aye

**Applicable branches**:
7.x , 7.11
**Failure history**:

**Failure excerpt**:

Testclusters fail to start because in fips.gradle we set `xpack.security.fips_mode.enabled: true` but the default hashing algorithm in 7.x is bcrypt. This wasn't observed in master as there we have changed the default algorithm to be pbkdf2.

We can solve this by setting the hashing algorithm in fips.gradle to be either pbkdf2 or pbkdf2_stretch

**Comment by tvernum** [comment]
Resolved in #66841
