### ISSUE TITLE
testIncorrectPasswordHashingAlgorithm failures 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#66824]
**Build scan**:

Example https://gradle-enterprise.elastic.co/s/skfubyliw3wqe

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.action.user.TransportChangePasswordActionTests.testIncorrectPasswordHashingAlgorithm" -Dtests.seed=D78AA09ED8362D41 -Dtests.security.manager=true -Dtests.locale=hi-IN -Dtests.timezone=Pacific/Chuuk -Druntime.java=8
```
**Reproduces locally?**: yes

**Applicable branches**: master, 7.11, 7.x

**Failure history**:

**Failure excerpt**:

Aggressive replacement in https://github.com/elastic/elasticsearch/pull/64024. We need to ensure that the hasher selected for hashing in the beginning of the tests is not the same that is set in passwordHashingSettings for the test to make sense.

**Comment by mayya-sharipova** [comment]
Another failure today on 7.11: https://gradle-enterprise.elastic.co/s/4qge7wckwyrlm

**Comment by jkakavas** [comment]
@BigPandaToo will you backport this to 7.11 too ?

**Comment by ywangd** [comment]
> @BigPandaToo will you backport this to 7.11 too ?

I am backporting (#66978) it to 7.11 since it failed just now

**Comment by BigPandaToo** [comment]
> > @BigPandaToo will you backport this to 7.11 too ?
> 
> I am backporting (#66978) it to 7.11 since it failed just now

Thanks, @ywangd ! Didn't have time to port it before leaving...
