### ISSUE TITLE
APT repository format can cause problems

### ISSUE THREAD

**Issue by ispmarin** [elastic/elasticsearch#6682]
The current apt [repository format](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-repositories.html) is not following the [Debian repository guidelines] (https://wiki.debian.org/HowToSetupADebianRepository#APT_Archive_Types). The version number on the path of the repository can cause confusion. 

Package naming also violates Debian guidelines, leading to versioning problems. Version upgrade is also problematic, as the entire line in sources.list has to be changed for upgrade, while the Debian guidelines recommends package pinning to keep a specific version. 

There are several issues open about this (#5536, #1726) that can help solving this problem.

**Comment by ispmarin** [comment]
After almost one year and several changes, the repository format is still not conforming to the Debian guidelines and @erikrose comment. Any ideas on this front?

**Comment by clintongormley** [comment]
We have moved to a single repo per major version. Closing
