### ISSUE TITLE
Mixed cluster tests log errors around component templates

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#66837]
The 7.x bwc builds take many minutes to build the `tar.gz` of the test results. It turns out that it contains 100s of mb of:
```
[2020-12-28T14:38:34,853][ERROR][o.e.x.c.t.IndexTemplateRegistry] [v6.8.14-0] error adding index template [.triggered_watches] from [/triggered-watches.json] for [watcher]
org.elasticsearch.transport.RemoteTransportException: [v6.8.14-3][127.0.0.1:37687][indices:admin/index_template/put]
Caused by: org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [indices:admin/index_template/put]
```
and
```
[2020-12-28T14:38:34,854][ERROR][o.e.x.c.t.IndexTemplateRegistry] [v6.8.14-0] error adding index template [.deprecation-indexing-settings] from [/org/elasticsearch/xpack/deprecation/deprecation-indexing-settings.json] for [deprecation]
org.elasticsearch.transport.RemoteTransportException: [v6.8.14-3][127.0.0.1:37687][cluster:admin/component_template/put]
Caused by: org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [cluster:admin/component_template/put]
```

It feels like we should probably do something to avoid this. I'm not sure if this is something that can happen in production, but if it can, it feels like a fairly angry error message we should do our best to avoid.

**Comment by mark-vieira** [comment]
For some more context, I specifically observed this with the mixed-cluster tests against 6.8.x nodes. So this doesn't seem to be a problem for 7.x clusters.

**Comment by mathur7vidit** [comment]
hi Team,

we were recently performing upgradation from 7.4.2 to 7.10.2 version. we were not aware of the fact that these errors are expected and that too in bulk. We stopped our upgradation there itself. Now as highlighted by @mark-vieira, it was observed against cluster with ES version 6.8.x. However, ours was not the same case. So does it mean that existing internal indices related to watchers are not correct or need some modification for our current Prod 7.4.2 cluster?
Any lead will be very much of help.

**Comment by jakelandis** [comment]
@mathieu-chauvet The errors, while not pleasant, should be harmless here (unless you keep the mixed cluster for a very long time, or are watcher indices during the upgrade). Basically we upgraded the index templates for Watcher and used the "new" style of templates that did not exist on 7.4.2. When trying to add the template during a rolling upgrade (and 7.4.2) is still the master it errors since it does not know what that is (since it did not exist in 7.4.2). If you have control over which nodes go first in the rolling up, you should be able to avoid this error by upgrading the master node first. Otherwise just ignore the error and once the master is updated, the errors should go away. I submitted a fix for this https://github.com/elastic/elasticsearch/pull/69147 and the expected versions are on the PR.

**Comment by mark-vieira** [comment]
Are we going to merge a fix for this? One side effect, on top of the one Nik mentions, is that it makes diagnosing test failures here really hard as the node logs are just flooded with these messages.

**Comment by mark-vieira** [comment]
Another ping on this one. Our Windows builds have all been failing due to suite timeouts on mixed cluster testing against 6.8.15 and I suspect this is related. Surely there is overhead associated with generating thousands and thousands of stacktraces.

**Comment by mark-vieira** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/69641 to specifically address these timeouts.

**Comment by benwtrent** [comment]
Two more 7.x/6.8.15 mixed cluster timeouts. Many log entries about the missing APIs in the issue description

https://gradle-enterprise.elastic.co/s/2pw4anm4ercxo

https://gradle-enterprise.elastic.co/s/cadcycdijdecy

Example:
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:51545], URI [_component_template], status line [HTTP/1.1 500 Internal Server Error]
  1> {"error":{"root_cause":[{"type":"action_not_found_transport_exception","reason":"No handler for action [cluster:admin/component_template/get]"}],"type":"action_not_found_transport_exception","reason":"No handler for action [cluster:admin/component_template/get]"},"status":500}
```

**Comment by mark-vieira** [comment]
We've had over 100 builds fail just in the last 7 days due to this test suite timing out. If we don't have a solution lined up here we need to consider muting this test suite.

**Comment by mark-vieira** [comment]
Thanks @jakelandis!

**Comment by jakelandis** [comment]
Assuming the timeout is due to the log messages and possible retries, then https://github.com/elastic/elasticsearch/pull/69147 should fix the timeout issue.
