### ISSUE TITLE
How to do integration test with elastic search 7.9.1 and spring boot test.

### ISSUE THREAD

**Issue by longzhihun** [elastic/elasticsearch#66843]
Versions:

    Elastic Search: 7.9.1
    Spring boot: 2.3.6.release
    Spring Cloud: Hoxton.SR9

We want to test our code can run well, so we want to do many integration test, especially the native query of ElasticSearchRestTemplate. but we don't know how to integrate with ES when test, anyone can share the method?

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
