### ISSUE TITLE
distribution:tools:keystore-cli failures in fips mode 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#66845]
**Build scan**:

https://gradle-enterprise.elastic.co/s/zsh75t3idenhi/failure#1

**Repro line**:

**Reproduces locally?**: yes 

**Applicable branches**: master, 7.x ,7.11

**Failure history**:

**Failure excerpt**:

We have two options: either use long passwords for the keystores in all those tests so that they pass in fips mode too, or mute in fips the ones that use a keystore without password/with short passwords

**Comment by jkakavas** [comment]
Reopening until backports are complete

**Comment by ywangd** [comment]
Backports are merged #66902 #66964
