### ISSUE TITLE
Introduce DocValuesNumbersQuery for long type

### ISSUE THREAD

**Issue by gf2121** [elastic/elasticsearch#66855]
# Use Case
In my use case, I stored 2 kind of ids as `long` in elasticsearch, called `a_id` and `b_id` here. Their relation is one-to-many and `b_id` is globally unique. I search them in this pattern:

```
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "a_id": 123
                    }
                },
                {
                    "terms": {
                        "b_id": {
                            "index": "abc",
                            "type": "_doc",
                            "id": "123",
                            "path": "b_id"
                        }
                    }
                }
            ]
        }
    }
}
```

There can be **more than 50,000** values in the Terms Query so the query can be quite slow. I'm looking for a way to spped it up, and luckily find that there has been a query called [`DocValuesNumbersQuery`](https://github.com/apache/lucene-solr/blob/master/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/DocValuesNumbersQuery.java) in Lucene, which scan DocValues instead of intersecting in a BKD tree. I've run some JMH benchmark and find it can be **100 times** faster in my case.

I knew that `DocValuesNumbersQuery` is usually slower than a `PointInSetQuery`, and obviously there are many factors that affect the result, such as `terms length`, `lead cost`, `hit ratio` and so on. So it may be diffcult to figure out a perfect way to CBO the query,  But it will be really nice if i can tell elasticsearch to execute a `DocValuesNumbersQuery` in some way, e.g. a dsl param or an index setting.

# Benchmark

**Java version**

> java version "11.0.6" 2020-01-14 LTS
> Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
> Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

**Firstly i constructed some data to mock my use case:** 
```
final int aRange = 500;
final int bRange = 1000000000;
BitSet bitSet = new BitSet(bRange);

Directory directory = FSDirectory.open(Paths.get("./test"));
IndexWriter indexWriter = new IndexWriter(directory,
        new IndexWriterConfig()
                .setOpenMode(IndexWriterConfig.OpenMode.CREATE_OR_APPEND));

for (int i = 0; i < 100000000; i++) {
    Document document = new Document();
    int a,b;
    do {
        b = random.nextInt(bRange);
    } while (bitSet.get(b));
    bitSet.set(b);
    a = b % aRange;

    document.add(new LongPoint("a", a));
    document.add(new SortedNumericDocValuesField("a", a));
    document.add(new LongPoint("b", b));
    document.add(new SortedNumericDocValuesField("b", b));

    indexWriter.addDocument(document);
}

indexWriter.flush();
indexWriter.commit();
indexWriter.close();
```
**And search them in this pattern:**
```
@Benchmark
@BenchmarkMode({Mode.AverageTime})
@Fork(1)
@Measurement(iterations = 10)
@Warmup(iterations = 5)
@CompilerControl(CompilerControl.Mode.DONT_INLINE)
public static void baseline(Blackhole blackhole) throws IOException {
    int a = random.nextInt(500);
    for (int i = 0; i < termsLen; i++) {
        terms[i] = random.nextInt(2000000) * 500 + a;
    }
    Query aQuery = LongPoint.newExactQuery("a", a);
//  Query bQuery = new DocValueNumbersQuery("b", terms);
    Query bQuery = LongPoint.newSetQuery("b", terms);
    Query query = new BooleanQuery.Builder()
        .add(aQuery, BooleanClause.Occur.FILTER)
        .add(bQuery, BooleanClause.Occur.FILTER)
        .build();
    AtomicInteger res = new AtomicInteger(0);
    indexSearcher.search(query, new SimpleCollector() {
        @Override
        public void collect(int doc) throws IOException {
            res.set(doc ^ res.get());
        }
        @Override
        public ScoreMode scoreMode() {
            return ScoreMode.COMPLETE_NO_SCORES;
        }
    });
    blackhole.consume(res.get());
}
```
**Result**
TermsLength | PointInSetQuery (s/op) | DocValueNumbersQuery (s/op)
-- | -- | --
1000 | 0.246 ± 0.026 | 0.021 ± 0.001
5000 | 0.640 ± 0.072 | 0.025 ± 0.001
10000 | 0.975 ± 0.078 | 0.027 ± 0.002
50000 | 1.663 ± 0.074 | 0.022 ± 0.001
100000 | 2.089 ± 0.034 | 0.028 ± 0.003

**Comment by nik9000** [comment]
I've triaged this so some folks familiar with the queries can pick it up.

I wonder how this'd fair with `IndexOrDocValuesQuery`. If it worked well it'd be nice because it'd be fairly simple to use it only when it'd help. I guess it depends on where the time is going in the `PointInSetQuery`.

**Comment by nik9000** [comment]
> I've triaged this so some folks familiar with the queries can pick it up.

And by that I mean that the search folk can further triage it. I don't have enough background to know if its a good idea or not but it sounds promising.

**Comment by gf2121** [comment]
@nik9000  Thanks for triaging! 
I'm sorry that i forgot to describe my benchmark result on a `IndexOrDocValuesQuery`. Unluckily, i have to say that the `IndexOrDocValuesQuery` can not be faster than a `PointInSetQuery` in this case.

Here are some code in `IndexOrDocValuesQuery`:
```
@Override
public ScorerSupplier scorerSupplier(LeafReaderContext context) throws IOException {
    final ScorerSupplier indexScorerSupplier = indexWeight.scorerSupplier(context);
    final ScorerSupplier dvScorerSupplier = dvWeight.scorerSupplier(context);
    if (indexScorerSupplier == null || dvScorerSupplier == null) {
        return null;
    }
    return new ScorerSupplier() {
        @Override
        public Scorer get(long leadCost) throws IOException {
            final long threshold = cost() >>> 3;
            if (threshold <= leadCost) {
                return indexScorerSupplier.get(leadCost);
            } else {
                return dvScorerSupplier.get(leadCost);
            }
        }

        @Override
        public long cost() {
            return indexScorerSupplier.cost();
        }
    };
}
```
As these code shows, `IndexOrDocValuesQuery` always builds scorers for both queries and do some comparation on the `indexScorer`'s cost to decide which scorer should be supplied.  However, `PointInSetQuery` do the BKD tree intersecting when building scorer, this is to say that we still have to intersect BKD tree even we decide to use a `dvQuery`, and this makes the `IndexOrDocValuesQuery` slow.

**Comment by gf2121** [comment]
> Unluckily, i have to say that the `IndexOrDocValuesQuery` can not be faster than a `PointInSetQuery` in this case.

In addition, this conclusion is based on the original `IndexOrDocValuesQuery`. If we rewrite the CBO rule to avoid the dependency on `indexScorer`'s cost, the result may be different. A simple logic that I can think of now is like this:
```
if (leadCost < 1000) {
    final ScorerSupplier dvScorerSupplier = dvWeight.scorerSupplier(context);
    if (dvScorerSupplier == null) {
        return null;
    }
    return dvScorerSupplier.get(leadCost);
}
final int factor = leadCost/TermsLength;
final int threhold = 1000;
if (factor > threhold) {
    final ScorerSupplier indexScorerSupplier = indexWeight.scorerSupplier(context);
    if (indexScorerSupplier == null) {
        return null;
    }
    return indexScorerSupplier.get(leadCost);
} else {
    final ScorerSupplier dvScorerSupplier = dvWeight.scorerSupplier(context);
    if (dvScorerSupplier == null) {
        return null;
    }
    return dvScorerSupplier.get(leadCost);
}
```
However, this rule is not perfect because it only considered the `termslength` and `leadCost`. `hitsCount` should also be a important factor, for example,  `PointInSetQuery` could be far more faster if the query hits no docs. I have no idea how can i get a estimate hits count before building a scorer, and i'm not sure if any ohter factors will affect the speed. So maybe we can expose a paramater in search DSL, and users can do some benchmark for their own use case.

**Comment by gf2121** [comment]
@jpountz Hi! Sorry to disturb.  I saw you participated in the [issue](https://issues.apache.org/jira/browse/LUCENE-6539) that introduced `DocValuesNumbersQuery` into lucene, so I believe that you are very familar with this query. Would you like to help take a look at this issue?

**Comment by jimczi** [comment]
> As the code shows, IndexOrDocValuesQuery always builds scorers for both queries and do some comparation on the indexScorer's cost to decide which scorer should be used. 

That's not how this query works. It builds a `ScorerSupplier` that is able to provide an estimation of the cost without building the actual scorer. If you look at `PointRangeQuery#scorerSupplier`, you'll see how the estimation is done for a range query over points. That's how we decide whether doc values should be used or not. This estimation works great because the BKD tree exposes the min and max values of each block so it's fast and relatively accurate.
The problem is completely different if you have 50k terms to estimate since we're looking for exact matches and not ranges.
Maybe that the lead cost and the value size are good enough heuristics but that would require proper benchmark to ensure that the change doesn't affect other valid usage of the `terms` query. One option to consider on your side is to build a custom query in a plugin that would implement this heuristic specifically for your usage. That would simplify the issue since you would not need to optimize all cases. If a plugin is too much to handle for you, you can also switch to a script query that can always use the doc values to validate matches.

**Comment by gf2121** [comment]
@jimczi Thank you very much for the explaination!
