### ISSUE TITLE
RolloverIT.testRolloverWithDateMath times out on creating index in 6.8

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#66874]
**Build scan**:

https://gradle-enterprise.elastic.co/s/mj63igsdha5hk

**Repro line**:
./gradlew ':server:integTest' \
  -Dtests.seed=E05D4BAC6B6AFA04 \
  -Dtests.class=org.elasticsearch.action.admin.indices.rollover.RolloverIT \
  -Dtests.method="testRolloverWithDateMath" \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=WET \
  -Dcompiler.java=11 \
  -Druntime.java=8

**Reproduces locally?**:
Yes

**Applicable branches**:
6.8

**Failure history**:
A lot of failures 

**Failure excerpt**:
```
Throwable #1: java.lang.AssertionError: timed out waiting for green state
   >    at __randomizedtesting.SeedInfo.seed([E05D4BAC6B6AFA04:619FD3822CA040AC]:0)
   >    at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:975)
   >    at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:931)
   >    at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:920)
   >    at org.elasticsearch.action.admin.indices.rollover.RolloverIT.testRolloverWithDateMath(RolloverIT.java:283)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by joegallo** [comment]
Closing this one -- the test isn't muted on 7.x and above, and we're not seeing failures there. At this late date I don't think it's worth it for us to invest the time into a 6.8 test.
