### ISSUE TITLE
Sorting terms buckets on nested or parent or child aggregations silently sorts incorrectly

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#66876]
When you sort the `terms` aggregation on `nested` or a `child` or a `parent` aggregation the on-data-node sorting sorts by "empty" values. This can be masked by a large enough `shard_size` so it has slipped through our test cases for a while, but [this](https://gist.github.com/nik9000/3cc956d1bc420f3b7c5734ef99aeded0) shows the failures. It looks like this is caused because we delay collecting parent and nested until right before we build buckets.

Replaces #53534 and #53570. Both are about error messages trying to sort. You actually can sort now, it just doesn't work :cry:.

Relates to #63811.

**Comment by rccoe** [comment]
Where does this stand in terms of priority? Seems like a pretty egregious bug

**Comment by nik9000** [comment]
I believe we got this in a patch release in 7.11 in  #67839.
