### ISSUE TITLE
Add Aggregation that buckets documents based on co-occurance of terms within a document

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#6688]
The aggregation would take a list of terms as input (e.g. a list of email addresses) and creates buckets based upon co-occuring terms (terms which appear in the same document regardless of their relative position in the document).  These buckets then represent edges between the terms and can be used to create weighted graphs (e.g. who is sending emails to whom)

This aggregation can be used in eg social nets where the terms represent uniquely identifiable entities and combined with time based aggregations can summarise interactions over time

**Comment by clintongormley** [comment]
@markharwood @colings86 is this still of interest?

**Comment by markharwood** [comment]
This is superseded by the graph API
