### ISSUE TITLE
Elasticsearch remote cluster authentication

### ISSUE THREAD

**Issue by xxlaila** [elastic/elasticsearch#66906]
Help:  Elasticsearch 7.8. Independent account authentication is configured between the two clusters,
` ` ` `
xpack.security.enabled : true
xpack.security.transport . ssl.enabled : true
xpack.security.transport . ssl.verification_ mode: certificate
xpack.security.transport . ssl.keystore.path : certs/elastic-certificates.p12
xpack.security.transport . ssl.truststore.path : certs/elastic-certificates.p12
` ` ` `
On kibana, the remote cluster status indicates that the remote cluster is "not connected"
The cluster kibana connects to is "connected". How to configure account authentication in cross cluster search.

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
