### ISSUE TITLE
EQL _async_search status API

### ISSUE THREAD

**Issue by lizozom** [elastic/elasticsearch#66955]
We need an API similar to the one implemented for the KQL async search https://github.com/elastic/elasticsearch/issues/57537 to check the status of running EQL requests.

The request and response formats should be identical.

**Comment by mayya-sharipova** [comment]
There are several ways we can organize an API for async EQL search status:

1.  Use the same API as for non EQL searches:
```js
GET /_async_search/status/<ID>
```

2. Use the EQL specific API
```js
GET /_eql/search/status/<ID>
```

@lizozom @jimczi  What do you think of each option?

@lizozom Is it important for you to have a single API to check the status regardless whether it is EQL search or not? Or is it important for you to differentiate between EQL searches and other searches?

**Comment by lizozom** [comment]
@mayya-sharipova I have a preference for a single API.
In the context of checking the status - the strategy used to run them doesn't seem to matter, and it would require additional effort to support this in KIbana.
It would be even more important as we move towards having a bulk status API.

**Comment by mayya-sharipova** [comment]
Thanks @lizozom.
For the unified status API for searches, @jimczi what do you think of these options?
 ```js
GET _searches_status/<ID>
```
or 

 ```js
GET _stored_searches_status/<ID>
```

**Comment by lizozom** [comment]
@mayya-sharipova after talking to @jimczi, it's fine to have two separate APIs with identical req\res formats.
(And if and when we decide to have a bulk API, we'd pass in the async ids with a type, so that you could work with them more easily)

**Comment by mayya-sharipova** [comment]
@lizozom @jimczi Thank you, I will work on this.

So for EQL status API, the request will be:
```js
GET /_eql/search/status/<ID>
```

The response will be identical to async search status response.

**Comment by mayya-sharipova** [comment]
I've just learned that eql search response doesn't have information about shards and status. So eql status response will have a different format from async search responses, like the following:

```js
{
  "id" : <id>,
  "is_running" : true,
  "is_partial" : true,
  "start_time_in_millis" : 1583945890986,
  "expiration_time_in_millis" : 1584377890986,
  "timed_out" : false
}
```

I hope you are fine with this, @lizozom
