### ISSUE TITLE
Aggregations: Memory-bound terms

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#6697]
Our terms aggregations implementations use an amount of memory that is linear with the cardinality of the value source they run on. Thanks to global ordinals, we only require 4 bytes per unique term to track the count, so even with a field that has a cardinality of 10M, that would only be 40MB of memory.

However, things get worse when using sub aggregations, especially the memory-intensive ones such as `percentiles`, `cardinality`, `top_hits` or bucket aggregations. Ideally we would want memory usage to depend on `size` instead of the cardinality of the value source.

I have been looking recently at the `Space-Saving` algorithm described in section 3.1 of [`Efficient Computation of Frequent and Top-k Elements in Data Streams`](https://icmi.cs.ucsb.edu/research/tech_reports/reports/2005-23.pdf). Although described for computing top buckets based on counts, I think it would be possible to use it when sorting by term or sub-aggregation. But you don't get optimized memory usage for free so it would have two main drawbacks compared to the current implementation:
 1. it would only work correctly on skewed distributions
 2. there is no clear separation between buckets and some buckets might aggregate document from other buckets

I think `1` is fine since top terms tend to make more sense on skewed distributions anyway, eg. most frequent terms in natural language text, or top ip addresses that hit a website.

`2` is more inconvenient, especially if there are other aggregations under this terms aggregation. One good news is that we could know what buckets might have aggregated data that is not theirs (they would be those whose term ordinal has been updated during collection), so we could have it as part of the response if necessary. On the other hand, if there are no sub aggregations, it would be more acceptable to use this implementation since [counts are inaccurate anyway](https://github.com/elasticsearch/elasticsearch/issues/1305). And it would also work nicely with https://github.com/elasticsearch/elasticsearch/issues/6696 since the maximum error can be estimated.

**Comment by clintongormley** [comment]
@jpountz is this still something you plan on pursuing?

**Comment by jpountz** [comment]
Yes. I think it can be useful for pagination in particular, when sorting by term. I'll close for now and reopen when I have more concrete plans.
