### ISSUE TITLE
Failure SmokeTestPluginsSslClientYamlTestSuiteIT.test {yaml=smoke_test_plugins_ssl/10_basic/Plugins are actually installed}

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#66979]
**Build scan**: https://gradle-enterprise.elastic.co/s/cxvvmzem5imok

**Repro line**:
> ./gradlew ':x-pack:qa:smoke-test-plugins-ssl:integTest' --tests "org.elasticsearch.smoketest.SmokeTestPluginsSslClientYamlTestSuiteIT.test {yaml=smoke_test_plugins_ssl/10_basic/Plugins are actually installed}" -Dtests.seed=62B281504E24A42 -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=Africa/Ouagadougou -Druntime.java=11 -Dtests.fips.enabled=true

**Reproduces locally?**:
Yes

**Applicable branches**:
7.x, 7.11
It does not failed on `master`. So maybe some backport is missing.

**Failure history**:

**Failure excerpt**:
```
org.elasticsearch.smoketest.SmokeTestPluginsSslClientYamlTestSuiteIT > test {yaml=smoke_test_plugins_ssl/10_basic/Plugins are actually installed} FAILED
    java.lang.IllegalStateException: Keystore /Users/ywangd/projects/elastic/elasticsearch-7.11/x-pack/qa/smoke-test-plugins-ssl/build/resources/test/testnode.jkscannot be used in FIPS 140 mode. Please configure certificate_authorities with a PEM encoded trusted CA/certificate instead
        at org.elasticsearch.test.rest.ESRestTestCase.configureClient(ESRestTestCase.java:1037)
        at org.elasticsearch.test.rest.ESRestTestCase.buildClient(ESRestTestCase.java:1021)
        at org.elasticsearch.test.rest.ESRestTestCase.initClient(ESRestTestCase.java:194)
```

**Comment by jkakavas** [comment]
This is muted in master but not in 7.x ,that's why it fails only there. We can unmute and use pem certificates instead of the keystore
