### ISSUE TITLE
Prefer "aggs" over "aggregations" in response from SQL Translate API

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#66994]
[An issue was recently logged](https://github.com/elastic/elasticsearch-net/issues/5201) for the .NET client where the response from the Translate API was failing to deserialise aggregations into the strongly-typed `SearchRequest`. After reviewing the response, the cause of the failure is due to the Translate API returning aggregations with the key "aggregations" rather than "aggs". The deserialisation prefers "aggs" since that's what we expect to serialise when sending a search request.

Since "aggs" is now the key recommended in all documentation, for 8.0, would it be practical to adjust the Translate API response? While we've worked around the serialisation issue for now, it would be cleaner to standardise this.

Example of current response

```
{
  "size" : 0,
  "_source" : false,
  "stored_fields" : "_none_",
  "aggregations" : {
    "groupby" : {
      "composite" : {
        "size" : 1000,
        "sources" : [
        {
          "ccf51bfa" : {
            "terms" : {
              "field" : "UDFvarchar1.keyword",
              "missing_bucket" : true,
              "order" : "asc"
            }
          }
        }]
      }
    }
  }
}
```

**Comment by costin** [comment]
Translate API doesn't perform manual translation - the choice of "aggregation" vs "aggs" actually comes from Elasticsearch itself and the way it serializes its own response internally (see https://github.com/elastic/elasticsearch/blob/541cb020773df3ee2b96e6627e5295b43b4e5b3b/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L1372)
Until that changes, there's not much QL can do.
