### ISSUE TITLE
Query DSL: Allow to default default_operator in query_string / field queries

### ISSUE THREAD

**Issue by kjelle** [elastic/elasticsearch#6700]
Hello!

I have a feature request to also add "indices.query.query_string.default_operator" to [#1540] so we can set it to default AND in a config file.

Also, it would be nice to set this per index (in e.g. templates' settings).

**Comment by clintongormley** [comment]
The settings added in #1540 are about safety, while the default operator is about retrieval... I'm loathe to add yet another setting.

Given that there hasn't been any further interest in this ticket in the last year and a half, I'm going to close this.
