### ISSUE TITLE
Is File and native authentication feature free in open source edition?

### ISSUE THREAD

**Issue by ziyunxiao** [elastic/elasticsearch#67004]
Hello,

I am new to Elasticsearch, and I am confused about if the file and native authentication feature is free or not.

Based on the blog: https://www.elastic.co/blog/security-for-elasticsearch-is-now-free it is free. (2019)
![Screen Shot 2021-01-05 at 7 47 24 AM](https://user-images.githubusercontent.com/6117913/103659991-4f255700-4f2a-11eb-82b1-d734dd021e3c.png)

But on the latest subscriptions document, it shows two features are not included in the opensource edition.
https://www.elastic.co/subscriptions
![Screen Shot 2021-01-05 at 7 46 55 AM](https://user-images.githubusercontent.com/6117913/103660009-5482a180-4f2a-11eb-96ef-aec566241f39.png)

Could anyone please help me to understand it? And if it is not free, what are the options to prevent everyone to access my Elasticsearch cluster?

Thanks,

Robin

**Comment by iankoetter** [comment]
The short answer is that local authentication is free tier while connection to third party auth sources requires a license. You can secure things with local credentials/keys, and firewall policy for free.

https://discuss.elastic.co/t/kibana-free-authentication/227497/4

(Discuss is probably a better place for this type of question, too)

**Comment by cbuescher** [comment]
Hi @ziyunxiao! Thanks for your interest in our security features. Your question is indeed better suited to the support forums over at https://discuss.elastic.co, probably in the elasticsearch forum. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
