### ISSUE TITLE
Rolling upgrade tests trip assertion error to do with tasks mapping

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#67010]
**Build scan**: e.g. https://gradle-enterprise.elastic.co/s/ravvhlwt6xlcu, https://gradle-enterprise.elastic.co/s/xtpm4xhblzwyq

**Repro line**: `./gradlew :qa:rolling-upgrade:v7.12.0#bwcTest`

**Reproduces locally?**: Attempt failed for other reasons.

**Applicable branches**:

Only seen on `master`, but the failure occurs on a 7.12 node in a mixed cluster.

**Failure history**:

It doesn't seem possible to identify similar failures from build-stats.

**Failure excerpt**:

```
»  java.lang.AssertionError: expected current mapping [{"task":{"dynamic":"strict","_meta":{"version":"7.12.0"},"properties":{"completed":{"type":"boolean"},"error":{"type":"object","enabled":false},"response":{"type":"object","enabled":false},"task":{"properties":{"action":{"type":"keyword"},"cancellable":{"type":"boolean"},"description":{"type":"text"},"headers":{"type":"object","enabled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_task_id":{"type":"keyword"},"running_time_in_nanos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":{"type":"object","enabled":false},"type":{"type":"keyword"}}}}}}] for type [task] to be different than new mapping
--
```

**Comment by DaveCTurner** [comment]
Possibly relates #67005

**Comment by probakowski** [comment]
I think https://gradle-enterprise.elastic.co/s/ayd5bsmfc2w6o is another instance of this, even though failed tests show different messages (you can still find `expected current mapping...` in console log).

**Comment by pugnascotia** [comment]
I did manage to reproduce this locally, but it's not reliable.

**Comment by probakowski** [comment]
Another one I think: https://gradle-enterprise.elastic.co/s/d2lsxtpmbnmca

**Comment by davidkyle** [comment]
The repo line is `./gradlew :qa:rolling-upgrade:v7.12.0#bwcTest`

**Comment by nik9000** [comment]
[Another](https://gradle-enterprise.elastic.co/s/im6mg22pxv6xq/console-log/raw), I think.

**Comment by pugnascotia** [comment]
I backed out the code responsible, so I'll go ahead and close this issue.
