### ISSUE TITLE
Support for size and order in all bucket aggregations

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#6704]
At the moment not all of the bucket aggregations support returning buckets in a particular order or limiting the number of returned buckets.  Because of this the aggregations that support size and order have their own implementations for this.  It would be nice to have a common implementation which can be used by all bucket aggregations.  This would also ensure the implementations are consistent in functionality

**Comment by clintongormley** [comment]
@colings86 still of interest?

**Comment by colings86** [comment]
@clintongormley No, with the addition of Pipeline Aggregations I think it would be better to have a 'sort and truncate' pipeline aggregation to cover this functionality in a generic way across all aggregations rather than having to implement it for each one individually. I have created an issue (https://github.com/elastic/elasticsearch/issues/14928) for this so I'll close this in favour of it

**Comment by jpountz** [comment]
+1

**Comment by McStork** [comment]
This feature seems pretty cool. If it was implemented outside of the pipeline feature, it would be perform faster though, right?
