### ISSUE TITLE
[CI] HistoryTemplateEmailMappingsTests.testEmailFields failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#67069]
**Build scan**:
- https://gradle-enterprise.elastic.co/s/5vybgc7tydvlw/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.history.HistoryTemplateEmailMappingsTests/testEmailFields#1

**Repro line**:
```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' \
  --tests "org.elasticsearch.xpack.watcher.history.HistoryTemplateEmailMappingsTests.testEmailFields"  \
  -Dtests.seed=90E27C46A8EF1767 -Dtests.security.manager=true -Dtests.locale=sr-Latn \
  -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=11 -Dtests.fips.enabled=true
```

**Reproduces locally?**: No

**Applicable branches**:
- `master`
 
**Failure history**:
3 in the past week
- https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Australia/Sydney&tests.container=org.elasticsearch.xpack.watcher.history.HistoryTemplateEmailMappingsTests&tests.disabledDistributions=WyJvdXRjb21lOnBhc3NlZCJd&tests.sortField=FAILED&tests.test=testEmailFields&tests.unstableOnly=true

**Failure excerpt**:
```
java.lang.AssertionError: 	
Expected: is <1L>	
     but: was <2L>	
	at __randomizedtesting.SeedInfo.seed([90E27C46A8EF1767:E603C1FC661103A9]:0)	
		•••
	at org.elasticsearch.xpack.watcher.history.HistoryTemplateEmailMappingsTests.testEmailFields(HistoryTemplateEmailMappingsTests.java:100)	
```

**Comment by martijnvg** [comment]
This failed 12 days in the last 28 days with the same assertion failure. This is an old test, but I think the point of this test is to check whether certain email fields (to, from, cc, bcc, reply_to) actually exist. So I think we can relax the assertion from exactly one to one or more.
