### ISSUE TITLE
Clarify docs on exposing Elasticsearch to the internet

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#67061]
There's a couple of [well-hidden](https://www.elastic.co/guide/en/elasticsearch/reference/current/ip-filtering.html#ip-filtering) [places](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html#_do_not_expose_elasticsearch_directly_to_the_internet) in the docs that say not to expose Elasticsearch directly to the internet. Recently I came across https://github.com/10up/ElasticPress/issues/2016 where it was suggested to a user that it's ok to put Elasticsearch behind a simple proxy. The system in question apparently requires such an architecture since it seems to work by [constructing queries](https://github.com/10up/elasticpress-react/blob/2c1b5ab922565d6b554a0323229073431b629e6f/src/queries/searchQuery.js) in the browsers of untrusted users.

I can see the reasoning, technically it's no longer directly exposed to the internet if it's behind a proxy, but I don't think a proxy offers any real security benefit. Can we clarify this message to call out that putting Elasticsearch behind a proxy still counts as direct exposure from a security perspective, and maybe move this information somewhere a bit more prominent too?

**Comment by ywangd** [comment]
What about the Elastic Cloud and the in-progress Fleet project? Are they an example of accessing Elasticsearch directly via internet (with HTTP proxy)? I think it is more of restricting the application and the privileges it associates so that communication to Elasticsearch is well understood and managed. If an user has the privileges to write and execute arbitrary scripts, no proxy can really stop it from harming the cluster. With the Fleet project, it means the agent should only perform the minimal necessary actions with minimal set of privileges. In addition, we also talked about a few issues to improve server stability against unauthenticated access. Overall, my question is whether this recommend of "[not exposing Elasticsearch directly to the internet](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html#_do_not_expose_elasticsearch_directly_to_the_internet)" is still valid once Fleet is GA?

**Comment by DaveCTurner** [comment]
It's a valid question @ywangd and further indicates need for some clarification in this area. Neither Cloud nor Fleet involve access from untrusted agents so they're nothing like as dangerous as the recommendation to use a proxy just for TLS termination as in the issue I linked. You're right that one of the goals should be to prevent outside users from writing arbitrary scripts, but I don't think it's sufficiently clear how to do that, and it's also not clear to me that this is the only concern with public access to an Elasticsearch cluster.

**Comment by lockewritesdocs** [comment]
Can we use the same note that @DaveCTurner recently introduced for the [networking](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/modules-network.html) page? I think the overarching message is that if you expose an unprotected node to the internet, then you're inviting bad actors. Using the same note in several areas also provides a consistent message

![image](https://user-images.githubusercontent.com/25848033/106507982-ce5e6a00-6499-11eb-8f35-60fa48e8adce.png)

**Comment by tvernum** [comment]
> I don't think a proxy offers any real security benefit.

Depending on what the proxy does, it may provide _some_ benefits, but not enough to treat it as a simple solution to the "don't expose ES to the internet" issue.

> Can we use the same note that @DaveCTurner recently introduced for the networking page?

I think that's helpful, but we need more. In this case, it's not just "turn on security", it's "even if you turn on security, there are additional risks to think about".

Security + a **well configured** proxy _might_ be enough, but as usual _It Depends_.

**Comment by lockewritesdocs** [comment]
@tvernum, thanks for the feedback. I think that the majority of the page for [Scripting and security](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html) applies to Elasticsearch in a broader context, and not just in relation to scripts. I feel like we should move the first few sections of that page to a top-level page; something like *Important security considerations* that outlines the practices people should not do. Having a page at that top level provides a platform to instruct users on best practices, like using security + a well-configured proxy. We could also expound on that page and inform users of security practices they _should_ do, like enabling some level of security that we're outlining in [#68946](https://github.com/elastic/elasticsearch/pull/68946). 

Just some thoughts on how to move forward. I'll have a 💺 and welcome any feedback on this proposal.

**Comment by lockewritesdocs** [comment]
Circling back on this issue. @tvernum, let me know if my proposal in the last comment makes sense as a way to move forward.

**Comment by lockewritesdocs** [comment]
Circling back on this issue. @tvernum, let me know if my proposal in [this comment](https://github.com/elastic/elasticsearch/issues/67061#issuecomment-780572726) makes sense as a way to move forward.

**Comment by tvernum** [comment]
Sorry for taking so long @lockewritesdocs.

I suspect this is likely to need a few attempts to get to the right wording, but your proposal makes sense to me.

I think the message we want is probably:
- Never expose an unsecured ES to the internet.
- Even with security turned on, ES is not designed to be exposed to public internet traffic.
- If you need to connect to ES from devices on the internet you should consider some combination of Proxy/Firewall/VPN in relation to your needs & risks.

It's documenting the last part well that will be hard.

**Comment by bytebilly** [comment]
> Never expose an unsecured ES to the internet.

I'd be even stronger here, adding that you should not run a cluster with security features off.

> It's documenting the last part well that will be hard.

I think we should not try to document any specific configuration/setup, just mentioning technologies that can help.
However, we could also mention as an example that if you want Elastic Agent to work you should allow incoming connections to port 9200, and blocking everything else.

**Comment by DaveCTurner** [comment]
> you should allow incoming connections to port 9200

I would like us to mention something about the risks of doing this. I expect it's not too hard for a bad actor to generate a high enough volume of requests to overwhelm a cluster even without a set of good credentials.

**Comment by lockewritesdocs** [comment]
> > you should allow incoming connections to port 9200
> 
> I would like us to mention something about the risks of doing this. I expect it's not too hard for a bad actor to generate a high enough volume of requests to overwhelm a cluster even without a set of good credentials.

@bytebilly, from what I understand in reading the [Fleet installation instructions](https://www.elastic.co/guide/en/fleet/7.14/fleet-quick-start.html), users configure security for ES and Kibana, and then manage Fleet through Kibana. Because Kibana is already securely connected to ES, users only have to specify the URL for ES that includes the HTTP port, correct?

**Comment by lockewritesdocs** [comment]
I created #76850 with updated information around Elastic security principles. Feel free to continue the conversation over in that PR.
