### ISSUE TITLE
Improve default format for date_nanos fields

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#67063]
By default, `date_nanos` fields use the `strict_date_optional_time` format. Unfortunately `strict_date_optional_time` accepts and parses dates with nanosecond precision, but when it formats it drops the nanoseconds.

Some search options like `fields` and `docvalue_fields` use the field's format by default to format + return values. This leads to confusing behavior for `date_nanos` fields, where the values are missing nanosecond precision.

It would be good to update the default format for `date_nanos` fields to one that always preserves nanoseconds.

Example reproduction:
```
PUT index 
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date_nanos"
      }
    }
  }
}

PUT index/_doc/1
{
  "@timestamp": "2019-09-22T23:50:13.253123345Z"
}

GET index/_search
{
  "fields": ["@timestamp"]
}
```

**Comment by jtibshirani** [comment]
@elastic/es-core-infra would it be okay to assign this to you? Instead of just labelling everything with `:Search/Mapping` that relates to mappings, we're trying to consider the underlying issue and determine who'd be best to handle it. As the experts on date formats, it seems like you'd understand the best default, and if any changes need to be made to the formats themselves.

**Comment by pgomulka** [comment]
It certainly makes sense to fix it. I am not sure we need a separate printer for `date_nanos` though. We allow parsing up to 9 nanos with `strict_date_optional_time` so I guess we should be able to print as well (assuming this won't break anything for `date` type)
I will try to come up with a PR

**Comment by pgomulka** [comment]
as discussed with @nik9000 the approach of simply changing the print format to 9digits might be breaking as seen here https://github.com/elastic/elasticsearch/pull/67893
a better way might be to introduce `strict_date_optional_time_with_nanos` printer that would be a default for `date_nanos` field.
