### ISSUE TITLE
Native search script working for searches but not for percolation

### ISSUE THREAD

**Issue by petchema** [elastic/elasticsearch#6709]
The same native AbstractSearchScript that works in classic searches do not work from percolators (tested with Elasticsearch 2.0.0 snapshot).

Script code:
package test;
import java.util.Map;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.component.AbstractComponent;
import org.elasticsearch.common.inject.Inject;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.node.Node;
import org.elasticsearch.script.ExecutableScript;
import org.elasticsearch.script.NativeScriptFactory;
public class CooccurenceScriptFactory extends AbstractComponent implements NativeScriptFactory{
    private final Node node;
    @SuppressWarnings("unchecked")
    @Inject
    public CooccurenceScriptFactory(Node node, Settings settings) {
        super(settings);
        this.node = node;
    }
    @Override public ExecutableScript newScript (@Nullable Map<String,Object> params){
        return new CooccurenceScript(node.client(), logger, params);
      }
}
package test;
import org.elasticsearch.ElasticsearchIllegalArgumentException;
import org.elasticsearch.client.Client;
import org.elasticsearch.common.Nullable;
import org.elasticsearch.common.logging.ESLogger;
import org.elasticsearch.common.xcontent.support.XContentMapValues;
import org.elasticsearch.script.AbstractSearchScript;
import org.elasticsearch.search.lookup.SourceLookup;
import java.util.List;
import java.util.Map;
public class CooccurenceScript extends AbstractSearchScript {
    private List<String> list = null;
    @SuppressWarnings("unchecked")
    public CooccurenceScript(Client client, ESLogger logger, @Nullable Map<String,Object> params) {
        Map<String, Object> map = params == null ? null : XContentMapValues.nodeMapValue(params.get("map"), null);
        if (map == null) {
            throw new ElasticsearchIllegalArgumentException("Missing the map parameter");
        }
        list = (List<String>) map.get("list");
        if (list == null || list.isEmpty()) {
            throw new ElasticsearchIllegalArgumentException("Missing the list parameter or list is empty");
        }
    }
    @Override
    public java.lang.Object run() {
        SourceLookup source = source();
        @SuppressWarnings("unchecked")
        List<Object> values = (List<Object>) source.get("source_field");
        if (values == null || values.isEmpty()) {
            return false;
        }
        for (Object localValue : values) {
            boolean result = true;
            for (String s : list) {
                result &= ((String) localValue).contains(s);
            }
            if (result) {
                return true;
            }
        }
        return false;
    }
}

Search test:
# Create index and type arefresh
curl -XDELETE http://localhost:9200/index1
curl -XPOST http://localhost:9200/index1
curl -XPOST http://localhost:9200/index1/mytype/_mapping -d '{
  "mytype": {
    "properties": {
      "source_field": { "type": "string" }
    }
  }
}'

# Create one document
curl -XPOST "http://localhost:9200/index1/mytype" -d '{
  "source_field" : [ "this a that" ]
}'
curl -XGET "http://localhost:9200/index1/_refresh"

# Search the document
curl 'http://localhost:9200/index1/mytype/_search' -d '{
  "query": {
    "constant_score": {
      "filter": {
        "script": {
          "script": "cooccurenceScript",
          "params": {
            "map": { "list" : [ "a", "this" ] }
          },
          "lang": "native"
        }
      }
    }
  }
}'
Result:
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"index1","_type":"mytype","_id":"cwrZpe8hR_KPPBVVB30AKw","_score":1.0,"_source":{
  "source_field" : [ "this a that" ]
}}]}}

Percolation test:
# Add a percolator using the same native script
curl -XPUT "http://localhost:9200/index1/.percolator/1" -d '{
  "query": {
    "constant_score": {
      "filter": {
        "script": {
          "script": "cooccurenceScript",
          "params": {
            "map": { "list" : [ "a" ] }
          },
          "lang": "native"
        }
      }
    }
  }
}'

# Percolate an identical document
curl -XPOST "http://localhost:9200/index1/mytype/_percolate" -d '
{
  "doc" : {
    "source_field" : [ "this a that" ]
  }
}'
Result:
{"took":3,"_shards":{"total":5,"successful":5,"failed":0},"total":0,"matches":[]}

**Comment by clintongormley** [comment]
Accessing the `_source` in a percolator is a really bad idea, for performance (and thus cluster stability) reasons.  Closing
