### ISSUE TITLE
How can I calculate score using More-like-this in script score in elasticsearch?

### ISSUE THREAD

**Issue by simonezz** [elastic/elasticsearch#67131]
Hi.
I'm writing a query for searching engine.
I want to calculate the score using cosine similarity(between image feature vectors) and tfidf.
So, I used "function_score" to calculate weighted sum of more-like-this score and cosine similarity.
I found that I should use "script_score" inside "functions" when I use function_score.
But I didn't work. Can anybody help me? Thanks.

This is my query.

`
script_query = {
     "function_score": {
         "query": {
                    "bool": {
                        "must": [
                            {"match": {"unitCode": unitCode}},
                            {"match": {"problemLevel": problemLevel}}

                        ]
                    }
                },
     
      "functions": [
        {
            "script_score": {
                    "script": {
                        "source": "cosineSimilarity(params.query_vector, 'fvec') + 1.0",
                        "params": {"query_vector": fvec}
                    }
            }
        
        },
        {
            "script_score": {
              "script": { 
                          "source":
                             {"more_like_this" : 
                                  {
                                    "fields" : ["plainText"],
                                    "like" : text,
                                    "min_term_freq" : 0,
                                    "min_doc_freq" : 0,
                                    "minimum_should_match" : "0%"
                                    }
                                }
                        }
                }
        }         
      ],
      "score_mode": "sum",
      "boost_mode": "sum",
      "max_boost": 4,
      "min_score": 3
    }`

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
