### ISSUE TITLE
[ILM] Shrink action may allocate shards to excluded _tier nodes

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#67133]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version (java -version)**: 14.0.1

**OS version (uname -a if on a Unix-like system)**: Mac OS 10.13.6

**Description of the problem including expected versus actual behavior**:

Seem to #64529,  `SetSingleNodeAllocateStep` in ILM may not consider existed `_tier` filters in the cluster settings as the step constructs a  new `DataTierAllocationDecider`:

https://github.com/elastic/elasticsearch/blob/ab39cd5d96f39b95798e49b7a7dd6bc33dce3d76/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SetSingleNodeAllocateStep.java#L77

**Steps to reproduce**:

1. setup a cluster with three nodes:

node1 with roles:
```
node.roles: [ data_hot, master ]
```

node2 with roles:
```
node.roles: [ data_cold ]
```

node3 with roles:
```
node.roles: [ data_warm ]
```
2. PUT _cluster/settings

```
{
  "transient": {
    "cluster.routing.allocation.exclude._tier": "data_cold"
  }
}
```
3. _ilm/policy/test_policy

```
{
  "policy": {
    "phases": {
      "warm": {
        "min_age": "1s",
        "actions": {
          "migrate": {},
          "shrink": {
            "number_of_shards": 1
          }
        }
      },
      "cold": {
        "min_age": "50d",
        "actions": {
          "allocate": {
            "number_of_replicas": 0,
            "include": {},
            "exclude": {},
            "require": {}
          },
          "freeze": {},
          "set_priority": {
            "priority": 10
          }
        }
      },
      "hot": {
        "min_age": "0ms",
        "actions": {
          "set_priority": {
            "priority": 100
          }
        }
      },
      "delete": {
        "min_age": "60d",
        "actions": {
          "delete": {
            "delete_searchable_snapshot": true
          }
        }
      }
    }
  }
}
```

3. Create a new index `y` with setting `index.routing.allocation.include._tier_preference:"data_hot"`  and attach the ilm poliy `test_policy ` to it.
4. Watch the ilm logs, ilm may stuck in `check-shrink-allocation` step if the last step `set-single-node-allocation` has selected `node2` to execute the `shrink` action.
```
[2021-01-07T14:22:44,662][INFO ][o.e.x.i.IndexLifecycleTransition] [node1] moving index [y] from [{"phase":"warm","action":"shrink","name":"set-single-node-allocation"}] to [{"phase":"warm","action":"shrink","name":"check-shrink-allocation"}] in policy [test_policy]
```

**Comment by dakrone** [comment]
I believe this has been resolved in #67137, so closing this issue.
