### ISSUE TITLE
Automatic replications factor

### ISSUE THREAD

**Issue by itayB** [elastic/elasticsearch#67149]
Hi,

I first posted it in [elastic forum](https://discuss.elastic.co/t/automatic-replications-factor/259996) but I got no comments so I'll try here as well :)

I wonder if there is a feature for dynamically changing the replication_factor of each index.

We have an Elasticseach cluster with hundreds of indices as part of our recommendations engine. Each index represents a different customer (encapsulation and privacy reasons).
Some of the indices (aka customers) are queried 300 times in a second while others can be queried once in a minute.
We are happy users of the "Adaptive Replica Selection" that help us to improve performance for those "heavy" (in term of search per second) indices.
Today we are manually set the `replication_factor` per each index: "heavy" indices get high `replication_factor` (5-6) while lighter get 1-2 - but that's not a scalable solution and required manual intervention.
As we grow fast, the idea is the keep the optimal number of shards and stop adding data nodes.

I wonder if such a feature exists? is it is on the roadmap, or is it something I can develop as a plugin?
The search rate can be retrieved from the index status and can assist to decide whether this index needs more or fewer replicas.

Thoughts?
Thanks,
Itay

**Comment by gwbrown** [comment]
Hi @itayB, thanks for your interest in Elasticsearch! We prefer to keep questions like this to the forums, which you've already found.

I'm afraid there's not an Elasticsearch feature currently to automatically adjust the number of replicas based on query rate. We are working on a few features which are somewhat related (keep an eye on the release notes for upcoming releases!), and there are a few open issues for related features, such as https://github.com/elastic/elasticsearch/issues/63872, but we do not have immediate plans for a feature like that at this time.

I believe it would be possible to develop something like this as a plugin, but I can't provide much guidance on what that would look like. We do at least have some [docs for plugin authors](https://www.elastic.co/guide/en/elasticsearch/plugins/7.10/plugin-authors.html) which you may find useful if you decide to go that route.

As this is a question and we prefer to keep Github issues for bug reports and feature requests, I'm going to close this issue. If you have a proposal for a feature similar to the one you're describing here, please open a new issue describing the proposed feature.
