### ISSUE TITLE
Translate API: Unknown index VerificationException in 7.11 BC2 when index contains join field mapping

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#67163]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.11.0 BC2 

**Plugins installed**: []
**JVM version** (`java -version`):
**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:

I've run into a similar issue as described in #44320 when running our .NET client integration tests against master and the latest 7.x snapshots. This time, the issue occurs when a mapping contains a `join field` type. When this is the case, the SQL Translate API fails to locate the index.

This is occurring locally using the latest 7.11 BC2 build -  8f5ce7c2:7.11.0 and replicated using v7.11.0-SNAPSHOT in the cloud. Present also in the 8.0.0 snapshots. This error is not occurring using the latest v7.10.2 deployment in the cloud or 7.10.1 locally.

**Steps to reproduce**:

1. Create an index with the following mapping

```
PUT project
{
  "mappings": {
    "properties": {
      "branches": {
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        },
        "type": "text"
      },
      "join": {
        "relations": {
          "project": "commits"
        },
        "type": "join"
      }
    }
  }
}
```

2. Attempt to use the Translate API

```
POST _sql/translate
{
  "fetch_size":5,"query":"SELECT branches FROM project"
}
```

**Expected Response:**

A **valid** response from the server. e.g.

```
{
  "size" : 5,
  "_source" : {
    "includes" : [
      "branches"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}
```

**Actual Response:**

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "verification_exception",
        "reason" : "Found 1 problem\nline 1:22: Unknown index [project]"
      }
    ],
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:22: Unknown index [project]"
  },
  "status" : 400
}
```

**Comment by Luegg** [comment]
@stevejgordon I tried to reproduce the issue and was not able to produce the same error on both 7.13.4 and latest master. The response I'm getting on these versions is:

```
{
  "size": 5,
  "_source": false,
  "fields": [
    {
      "field": "branches"
    }
  ],
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ]
}
```

It looks like the issue has been resolved in the meantime. Can you confirm that it also works in your case?

**Comment by stevejgordon** [comment]
Hi @Luegg! The original test was reworked to avoid the issue but I created a simplified version and it ran through fine against 7.13.3 so indeed, it looks like this was fixed elsewhere. I'll close this issue. Thanks!
