### ISSUE TITLE
Watcher > Pager Duty > Set Incident Urgency

### ISSUE THREAD

**Issue by runtman** [elastic/elasticsearch#67203]
**Describe the feature:**

Currently, with the watcher > pagerduty integration, every incident that gets sent to pager duty is marked as `high` for it's urgency

If you see here, there is no option for urgency: https://www.elastic.co/guide/en/elasticsearch/reference/current/actions-pagerduty.html

However if you see here: https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents/post

The ability to set urgeny is available in their API.

**Describe a specific use case for the feature:**

We want all alerts to go to pagerduty, but we don't want them all being marked as high. We want to be able to triage this ourselves. This should be changeable.

**Comment by joegallo** [comment]
I'm removing the `team-discuss` label from some older `Team:Data Management` issues -- we've had plenty of time to discuss them, but we haven't, so the label isn't serving its purpose. Feel free to delete this comment and/or re-add the `team-discuss` label.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
