### ISSUE TITLE
API for listing index file sizes

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#6728]
I think it would be useful when debugging if there was a way to get a snapshot of basically `ls -l` of the lucene index files. This would give us some basic information like size of some in-memory datastructures (norms, terms index), as well as some structural information (how large is the term dictionary? positions file? etc).

I know this might be tricky because of NRT and deleted files, but even if its not perfect, it would be handy.

**Comment by rmuir** [comment]
I think it would also be useful here to recurse into .cfs files.

**Comment by mikemccand** [comment]
+1

**Comment by ppf2** [comment]
+1 would be great to see the file sizes used for doc values as more users switch from fd to dvs.

**Comment by clintongormley** [comment]
Closed by #8832
