### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [elastic/elasticsearch#67318]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

- https://github.com/elastic/elasticsearch/blob/master/buildSrc/version.properties#L31

Other points:
- https://github.com/elastic/elasticsearch/issues/55145#issuecomment-758457666

**Comment by jkakavas** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to security@elastic.co

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.

**Comment by Neustradamus** [comment]
@jkakavas: The problem is not new...
- https://github.com/elastic/elasticsearch/issues/55145

**Comment by jkakavas** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to security@elastic.co

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.

**Comment by Neustradamus** [comment]
@jkakavas: Can you update to Java FIPS Release 1.0.2.1?
There are CVEs.
