### ISSUE TITLE
Add boolean or constant_score similarity

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#6731]
The idea here is that some use cases don't need or want full-text ranking. In a lot of cases it can even hurt, for example: trying to use fuzzy query to find misspellings in a database of place names or something like that.

Today I think its too hard to turn off various measures such as IDF, we could just make it easy by providing a simple similarity out of box that users could enable.

**Comment by clintongormley** [comment]
Boolean similarity is now in Lucene 6.4

**Comment by synhershko** [comment]
What is the status of this? is it exposed already?

**Comment by clintongormley** [comment]
Not yet
