### ISSUE TITLE
Improve cluster/index settings 

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#6732]
Currently there is no way of seeing all settings that are enforced.  For instance, defaults are not available and settings from the `config/elasticsearch.yml` are not available.

Any setting which is different from the default should be returned by these APIs:

    GET /{index}/_settings
    GET /_cluster/settings

Both should also support the `include_defaults` query string parameter, which would return all settings, including the defaults.

Also, deleting a setting should reset the setting to the default.

Setting an unknown setting, or a setting that can't be changed should throw an error.

Relates to #5018, #3670, #2738, #2730, #3572, #2628, #3671, #5019, #6309

**Comment by linkwoman** [comment]
@georgi0u Thank you so much for that explanation and workaround.  I made a copy/paste mistake and nested another set of analysis, etc. inside of analysis!  I did the following to set the 'analysis' analyzer (doh!) to "type": "standard" and now can get my index open again.

    curl -XPUT 'localhost:9200/books/_settings' -d '
    {
        "analysis": {
            "analyzer": {
                "analysis": {
                  "type" : "standard"
                  }
                }
            }
    }'

Looking forward to there being a way to delete index settings.

There isn't a way for me to rename that bad analyzer, is there?

**Comment by nopejpg** [comment]
A Google search results in people getting brought here... Unfortunately, empty stringing a value doesn't behave as one would expect; so the only way I've been able to actually remove settings is by deleting the global-X.st files under 0/_state/.

**Comment by damienjoldersma** [comment]
+1 on being able to delete index settings.

**Comment by RJ3000** [comment]
+1 on being able to delete index settings.

**Comment by ncolomer** [comment]
+1 too

**Comment by thenom** [comment]
+1

**Comment by pemontto** [comment]
:+1:

**Comment by bsandvik** [comment]
+1 for ability to delete index settings. :pray:

**Comment by traxair** [comment]
+1

**Comment by drocsid** [comment]
+1 I created an undesired key for an index setting, and was surprised I'm unable to remove that key now.

**Comment by jaytaylor** [comment]
ES team doesn't seem to be very responsive here.  Unsubscribing to stop the daily inbox spam!

:-1:

**Comment by hjc1710** [comment]
Would love to see this implemented, especially this part:

> Setting an unknown setting, or a setting that can't be changed should throw an error.

Would have saved me some time during a recent DevOps incident.

:+1:

**Comment by drocsid** [comment]
I think creating a setting is actually a feature. However removing a setting is a feature I want.

**Comment by kjelle** [comment]
+1 for ability to delete persistent/transient index settings.

**Comment by hjhart** [comment]
+1 for being able to delete index settings.

**Comment by prikha** [comment]
+1 *)

**Comment by fitz123** [comment]
+1

**Comment by reardencode** [comment]
:pray: :heart:

**Comment by vb3** [comment]
+1 

I cannot delete my fielddata limit breaker that i set using /_cluster/settings

**Comment by ppf2** [comment]
+1 Some features in product requires a setting to be set on all master and data nodes, other features expect settings to be set only on the master nodes.  Folks in the field tend to err on the side of caution and put the same configuration on every node (master and data) in the cluster.  If there is a configuration end point that allows users to manage all the configurations in a central location without having to worry about where these settings should go, it will be great.

**Comment by JohnMcSpedon** [comment]
+1 for deleting an index setting

**Comment by athompson-r7** [comment]
+1

**Comment by andyrhee** [comment]
+1

**Comment by eedwardsdisco** [comment]
+1

**Comment by traceur** [comment]
+1 !!!

**Comment by Bukhtawar** [comment]
Do deciders like disk threshold prefer disk watermark yaml settings of their specific node if different nodes on a cluster have different values for the property `cluster.routing.allocation.disk.watermark.high`. Or the cluster resolves this value over conflicting values for this property

**Comment by clintongormley** [comment]
@Bukhtawar yes, the local settings are preferred, until a cluster wide setting is set via the api
