### ISSUE TITLE
Improve error message when the build cannot location a Java installation

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#67408]
I ran into an awkward error when refreshing my project in intellij after the 6.8 upgrade.

https://gradle-enterprise.elastic.co/s/uyqyicvalpgzo/failure#1

Essentially, none of the JAVA_* environment variables were set in the context of my IDE so the build couldn't find a matching installation in the registry for the "current" JDK. Ended up that I had all my environment variables set in a bash_rc file which doesn't apply when launching an application from the desktop (or via Jetbrains toolbox) on Linux. To fix this I had to move these to `~/.profile` which is applied at login, instead of when launching a shell.

This is perhaps a unique situation but we should probably improve the message here to say something like "Hey, do you at least have JAVA_HOME set?"

**Comment by mark-vieira** [comment]
Alternatively, is there a way to remove this requirement that the currently used JDK _must_ also be defined in one of the hard-coded environment variables? If I understand this correctly the `CurrentInstallationSupplier` should solve this problem but perhaps it gets disabled when auto-detection is turned off?

**Comment by breskeby** [comment]
yeah. auto detection of does disable this. 

The problem with auto detection on is that you do not have proper control on priotize the order in which potential jdk versions are used over another. What we want is, that When providing JAVAX_HOME variables, that these take priority over any other installation locally. Gradle does currently not allow it and just gives you all it can find. So you might end up using a jdk of the same version (e.g. 14) that you have on your system installed, but not the one declared in JAVA14_HOME.

I think I found a way to take the current JDK into account too (using `CurrentInstallationSupplier`) and will raise a PR for this
