### ISSUE TITLE
[API Docs] Use _flush instead of flush

### ISSUE THREAD

**Issue by Erni** [elastic/elasticsearch#67442]
In the [docs here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-synced-flush-api.html#synced-flush-api-request) it says that the requests endpoints use the word `flush` but all the examples are with `_flush`. I checked that it works with _flush, so I guess the docs are wrong when showing the Requests. They need to be changed for `_flush`, so the docs will look like this:
`POST /<index>/_flush/synced`
`GET /<index>/_flush/synced`
`POST /_flush/synced`
`GET /_flush/synced`

**Comment by jrodewig** [comment]
Thanks for raising this @Erni. This is fixed with #67446.
