### ISSUE TITLE
Canvas SQL: Unexpected result of an SQL query

### ISSUE THREAD

**Issue by halimB8** [elastic/elasticsearch#67458]
**Elasticsearch version**: 7.10.1

**Kibana version:** 7.10.1

**OS version** : Debian 10

**Description of the problem including expected versus actual behavior**:
I would like to display in canvas the number of users having more than 10 failed authentication using an SQL Query, but I am getting an unexpected result.

**My SQL query:** 

```
SELECT COUNT(*) as result_count 
FROM (
SELECT user.name, COUNT(*) as result 
FROM "winlogbeat-*"  
WHERE event.category = 'authentication'  
AND event.action = 'logon-failed'
GROUP BY user.name
HAVING result > 10
)
```

**The expected result is** 3

**The result that I am getting is:**

```
    |result_count|
    |------------|
    |     29     |
    |------------|
    |     78     |
    |------------|
    |     13     |
    |------------|
```

**Comment by costin** [comment]
Thanks for the detailed post. 
This type of query requires a double aggregation, that is aggregating the data outside of Elasticsearch - in this case the results of the inner query.
Like join functionality, this is a feature the team is not chasing at least in the near future.
