### ISSUE TITLE
we should't split bulk  request into much shards to increase indexing concurrency on the coordinating node

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#67462]
Here we only consider the bulk request of no primary key, to simply it, the bulk contains only index

On the coordinating node, we will split the bulk request by index name and shardID, and send the BulkShardRequest to every target data node in a poll, the bulk request in coordinating node will return when the last data node response. Considering the long tail phenomenon, the bulk will cost  extra much time to wait the the response from last data node which is hot node. 

A document written to a specific shard is determined by hash(id), which will lead to a bad result: a bulk will be split too much BulkShardRequest. For example, if the bulk request contains 10,000 documents, the target index has 50 shards, As the result, the bulk will be split into 50 BulkShardRequest by hash(id), If we could put the request send into only on shard  instead of 50 shards?

hash(id) is used by routing in writing  and search, it is created by UUIDs.legacyBase64UUID(), we will use id for search,  we also want the whole bulk is written into on shard. The solution is redefining id structure: 
```id,splitTag,shardId```
1. id: It is created by UUIDs.legacyBase64UUID()
2. splitTag: The value can be "$", which will not exists in UUIDs.legacyBase64UUID()
3. shardId: shardId is the current ShardId which the bulk will be sent to, every shard will be polled by the later request.

So in search phase, if we use the redefining Id to obtain the document, we just split the shardId on the coordinating node, and send the target node.

**Comment by dnhatn** [comment]
We discussed a similar issue in https://github.com/elastic/elasticsearch/pull/62020#issuecomment-759346882, but we felt the optimization targeted a small user case.

I hope you don't mind if I close this issue. Thank you for your interest in Elasticsearch.
