### ISSUE TITLE
Hide internal versions of dependencies from IDE auto-import

### ISSUE THREAD

**Issue by benmccann** [elastic/elasticsearch#6755]
Elasticsearch packages many dependencies. E.g. `com.google.common.base.Preconditions` can also be found at `org.elasticsearch.common.base.Preconditions` This leads to folks on my team often accidentally importing the wrong class and a frustrating experience including elasticsearch in our project.

These can be hidden from IDE auto-import. [Google Guice has done the same thing](https://code.google.com/p/google-guice/wiki/Guice40), so it would be a great example to look at:

> Many things inside com.google.inject.internal changed and/or moved. This is especially true for repackaged Guava (formerly Google Collections), cglib, and asm classes. All these classes are now hidden from IDE auto-import suggestions and are in new locations. You will have to update your code if you relied on any of these classes.

**Comment by dakrone** [comment]
Closing this as we no longer shade dependencies.
