### ISSUE TITLE
Query performance regression after upgrade to 7.10.x with huge values for "size" field

### ISSUE THREAD

**Issue by naag** [elastic/elasticsearch#67574]
**Elasticsearch version** (`bin/elasticsearch --version`): 
```
Version: 7.10.0, Build: default/docker/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 15.0.1
```

**Plugins installed**: []

**JVM version** (`java -version`): 
```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux PC3776 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

We've recently upgraded our on-prem production cluster from ES 7.4.1 to ES 7.10.1 and experienced a huge performance regression when querying a very small index of just ~4.500 docs with <20MiB in size. Queries used to go through in <20ms, but after the upgrade the search performance dropped to >2s. We did a lot of debugging and performance testing locally and `git bisect` turned up this commit as the one triggering the issue: https://github.com/elastic/elasticsearch/commit/31c026f25ccbbc02bb643351338786297a2dff6a

Since this is the Lucene upgrade to 8.7.0, we continued bisecting this issue in Lucene and found this particular PR to be involved:

https://github.com/apache/lucene-solr/pull/1793/files

We verified that ES 7.9.3 still performs the same as 7.4.1, so below you'll see our results against ES 7.9.3 and not 7.4.1. We also ran our workload against a `master` (1c8559976b23472dbfca3e703502a214e5692513) build of Elasticsearch, but the problem remained.

The queries we're running seem simple enough, index mapping contains just a handful of integer fields and one boolean field. The docs are basically lists of integers, and the queries look for matching values. However we use `size: 10000` (with `_source: false`), which seems to play a big role in this performance issue.

Note that the performance impact in our production cluster was much more severe than what you can see in this benchmark (probably due to the base load on the cluster).

Discussed this with David Turner on #stack-elasticsearch @ Slack.

**Steps to reproduce**:

Extract the test data from [es-perf-issue.zip](https://github.com/elastic/elasticsearch/files/5820813/es-perf-issue.zip) to a local directory and follow the steps below.

<details>
<summary>
**Performance baseline with 7.9.3**:

```
docker run --rm -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.9.3
curl -XPUT -H"Content-Type: application/json" --data-binary @mapping.json http://localhost:9200/test_index
curl -XPOST -H"Content-Type: application/x-ndjson" --data-binary @docs.json http://localhost:9200/_bulk
ab -c 16 -n 2000 -T "application/json" -p query.json http://localhost:9200/test_index/_search
```

Mean query time over 2000 requests: **89ms**.
</summary>
Results:

```
[...]

Server Software:        
Server Hostname:        localhost
Server Port:            9200

Document Path:          /test_index/_search
Document Length:        53378 bytes

Concurrency Level:      16
Time taken for tests:   11.174 seconds
Complete requests:      2000
Failed requests:        604
   (Connect: 0, Receive: 0, Length: 604, Exceptions: 0)
Total transferred:      106934604 bytes
Total body sent:        2734000
HTML transferred:       106756604 bytes
Requests per second:    178.99 [#/sec] (mean)
Time per request:       89.389 [ms] (mean)
Time per request:       5.587 [ms] (mean, across all concurrent requests)
Transfer rate:          9346.00 [Kbytes/sec] received
                        238.95 kb/s sent
                        9584.95 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       2
Processing:    25   89  30.1     90     243
Waiting:       25   89  30.0     89     243
Total:         25   89  30.1     90     244

Percentage of the requests served within a certain time (ms)
  50%     90
  66%    102
  75%    110
  80%    114
  90%    126
  95%    136
  98%    153
  99%    168
 100%    244 (longest request)
```
</details>

<details>
<summary>
**Verify performance of 7.10.0 against baseline**:

```
docker run --rm -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.0
curl -XPUT -H"Content-Type: application/json" --data-binary @mapping.json http://localhost:9200/test_index
curl -XPOST -H"Content-Type: application/x-ndjson" --data-binary @docs.json http://localhost:9200/_bulk
ab -c 16 -n 2000 -T "application/json" -p query.json http://localhost:9200/test_index/_search
```

Mean query time over 2000 requests: **590ms**.
</summary>

Results:

```
[...]

Server Software:        
Server Hostname:        localhost
Server Port:            9200

Document Path:          /test_index/_search
Document Length:        53379 bytes

Concurrency Level:      16
Time taken for tests:   73.937 seconds
Complete requests:      2000
Failed requests:        15
   (Connect: 0, Receive: 0, Length: 15, Exceptions: 0)
Total transferred:      106936015 bytes
Total body sent:        2734000
HTML transferred:       106758015 bytes
Requests per second:    27.05 [#/sec] (mean)
Time per request:       591.497 [ms] (mean)
Time per request:       36.969 [ms] (mean, across all concurrent requests)
Transfer rate:          1412.41 [Kbytes/sec] received
                        36.11 kb/s sent
                        1448.52 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:   277  590 143.4    585    1815
Waiting:      276  589 143.4    585    1814
Total:        277  590 143.4    585    1815

Percentage of the requests served within a certain time (ms)
  50%    585
  66%    641
  75%    676
  80%    695
  90%    755
  95%    808
  98%    890
  99%    997
 100%   1815 (longest request)
```
</details>

<details>
<summary>
Just for completeness these are the results for ES master, commit 1c8559976b23472dbfca3e703502a214e5692513, built using: 

`gradle :distribution:docker:buildOssDockerImage`

Mean query time over 2000 requests: **701ms**.
</summary>

```
Server Software:        
Server Hostname:        localhost
Server Port:            9200

Document Path:          /test_index/_search
Document Length:        27793 bytes

Concurrency Level:      16
Time taken for tests:   87.782 seconds
Complete requests:      2000
Failed requests:        1971
   (Connect: 0, Receive: 0, Length: 1971, Exceptions: 0)
Total transferred:      86995762 bytes
Total body sent:        2734000
HTML transferred:       86847762 bytes
Requests per second:    22.78 [#/sec] (mean)
Time per request:       702.254 [ms] (mean)
Time per request:       43.891 [ms] (mean, across all concurrent requests)
Transfer rate:          967.82 [Kbytes/sec] received
                        30.42 kb/s sent
                        998.23 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:   320  701 171.1    692    1870
Waiting:      319  700 171.0    692    1870
Total:        320  701 171.1    692    1870

Percentage of the requests served within a certain time (ms)
  50%    692
  66%    747
  75%    786
  80%    811
  90%    894
  95%    971
  98%   1118
  99%   1258
 100%   1870 (longest request)
```
</details>

**Comment by gingerwizard** [comment]
The regression introduced by LUCENE-9510 was detected in our nightlies and  tracked through https://github.com/elastic/night-rally/issues/305.  Alot of the regressions from this lucene change seem to have been address through https://issues.apache.org/jira/browse/LUCENE-9529 and https://issues.apache.org/jira/browse/LUCENE-9535. It is possible that https://github.com/elastic/night-rally/issues/305#issuecomment-700846387 explains this performance but its not treated as regression.  

In @jpountz absence maybe @jimczi has some ideas re the conditions required for https://github.com/elastic/night-rally/issues/305#issuecomment-700846387 and why memory accounting for stored fields may have impacted performance here - if at all.

**Comment by dliappis** [comment]
@naag Thank you for the interest and raising this. While very interesting to see the impact with the shared dataset, how large is your production dataset? Do you see the same impact with a larger dataset? cc @jimczi

**Comment by naag** [comment]
I basically dumped the index into `docs.json` and just renamed the fields a bit, so effectively this is the production dataset. Of course there are many more docs in the cluster in other indices (more than 20 billion), but we didn't notice any slowdown on those.

**Comment by danielmitterdorfer** [comment]
The reason for the slowdown is that Lucene optimizes for different tradeoffs now by reading larger blocks for stored fields (previously 16KB, now 60KB) and as `_id` is a stored field this is the reason for the slowdown. We think this is still the right tradeoff for larger indices but it hurts small indices as yours. We suggest the following route:
1. Instead of relying on `_id`, generate your own id and store it in a doc_value field, e.g. `my_id_field`.
2. [Disable stored fields](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-fields.html#disable-stored-fields) in your query by specifying: `"stored_fields": "_none_"`
3. Retrieve your custom id using `"docvalue_fields": ["my_id_field"]`

**Comment by naag** [comment]
Thanks @danielmitterdorfer, your suggestion worked out beautifully. Queries are lightning fast and even faster than before, so I'm going to close this one :taco:

**Comment by danielmitterdorfer** [comment]
Great to hear! Thanks for the feedback.

**Comment by miha0000** [comment]
hi all, we cannot resolve this problem(we change es 7.4 to 7.10.2), because we don't understand how to do correctly parts 1-3(that danielmitterdorfer writed). can you give us more detals about it? thanks a lot

**Comment by cbuescher** [comment]
> hi all, we cannot resolve this problem(we change es 7.4 to 7.10.2), because we don't understand how to do correctly parts 1-3(that danielmitterdorfer writed). can you give us more detals about it? thanks a lot

Hi @miha0000, I would like to redirect you to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and since this issue has been answered we would like you to ask related questions around the usage of Elasticsearch there. Many thanks.

**Comment by miha0000** [comment]
Hi @naag, we cannot resolve this problem(we change es 7.4 to 7.10.2), because we don't understand how to do correctly parts 1-3(that danielmitterdorfer writed). can you give us more detals about it? thanks a lot
