### ISSUE TITLE
[discovery-ec2] Support for setting additional information such as instanceId in node attrs

### ISSUE THREAD

**Issue by dekimsey** [elastic/elasticsearch#67622]
I'd like to see the discovery-ec2 plugin's automatic node attributes feature expanded a wee bit more. Of particular interest to me is the instance-id's as those are something I commonly need to go manually lookup in AWS from the private IP of the node or visa-versa. Just exposing it here would be helpful to operators and tooling trying to translate a node in ES to an instance in AWS and back. Perhaps in an container/ECS instance environment that might be the task uuid instead. Just a bit of extra information to help inform the operator about the instance.

Bonus points, support automatically exposing arbitrary node attributes based on the instance tags, could be as simple as: `aws_tag_Name_Value`. These can be super helpful for querying nodes

**Comment by DaveCTurner** [comment]
@dekimsey you can set arbitrary settings via environment variables, and that's a good way to set node attributes as desired: see https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_environment_variable_substitution. You could do this for the `node.attr.aws_availability_zone` attribute too and I am unsure why that alone was chosen for special treatment in the plugin.

I see some value in automatically configuring a wider set of attributes in the plugin, but worry that it would all get quite complicated to decide which attributes should/shouldn't be set. You give an example of this, noting that the right choice likely depends on whether we are running in bare EC2 or in ECS. On balance I think it's better to leave these decisions in the hands of the cluster operators themselves, via the environment variable substitution mechanism.

**Comment by dekimsey** [comment]
Hrm, that's a good point with the environment variables. In ECS at least, its clunky but possible to inject those sort of runtime dynamic variables in (curl, jq, etc) depending on the containers available processes. I do it on our haproxy containers to expose the task ID, but it is pretty clunky to do. It tends to fall over if you want anything that's not in the instance metadata such as resource tags.

In a systemd/rpm install though, I don't think it's very easy to inject dynamic environment settings at runtime. There's no good way to hook into the runtime before the application starts without replacing parts of the service file. ExecStartPre doesn't keep the environment between runs, and I believe the sysconfig EnvironmentFile has already been read by the time the service starts. Further, the query isn't trivial to do from the point of view of a shell-script without also requiring the AWS cli or other toolkit.

> I see some value in automatically configuring a wider set of attributes in the plugin, but worry that it would all get quite complicated to decide which attributes should/shouldn't be set.

I envisioned some simple glob matching myself. Make it a list of globs, and that gives the operator plenty of flexibility.

**Comment by DaveCTurner** [comment]
> It tends to fall over if you want anything that's not in the instance metadata such as resource tags.

The scope is creeping here :grin: I really think this level of generality is pushing the bounds of what Elasticsearch needs to do internally vs what we'd expect to be the responsibility of an external orchestrator. Even the original ask, tagging nodes with their instance ID to save you a lookup, is a bit orchestratory for my liking.

> In a systemd/rpm install though, I don't think it's very easy to inject dynamic environment settings at runtime.

I'm not a `systemd` expert but AIUI you're expected to customise the environment with drop-ins (separate files in the `service.conf` directory) and creating such a drop-in file before starting Elasticsearch sounds like the sort of thing that `systemd` lets you do. You are right that this would need `curl` and `jq` and `aws-cli` and so on, or else you can inject these things at the time you launch the instance.

**Comment by arteam** [comment]
There doesn't seem too much public interest in this feature, and as @DaveCTurner mentioned, the AWS SDK provides this functionality with environment variables. Please feel free to re-open the issue if you still need this feature.
