### ISSUE TITLE
API key service is disabled when TLS is disabled, but the log message is misleading

### ISSUE THREAD

**Issue by antoineco** [elastic/elasticsearch#67626]
ℹ️ Running Elasticsearch using the `docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT` image

**Elasticsearch version**: 8.0.0-SNAPSHOT (build 2021-01-15T19:37:43.964331Z, 35f478b61811425c1f677787b96e0fb9e08d7a21)
**Plugins installed**: []
**JVM version**: AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9
**OS version**: Linux/5.4.0-1036-azure/amd64

**Description of the problem including expected versus actual behavior**:

With the `xpack.security.authc.api_key.enabled` setting set to `true`, Elasticsearch prints the warning message below:

```json
{
  "@timestamp":"2021-01-16T21:56:54.454Z",
  "log.level": "WARN",
  "message":"HTTPS is required in order to use the API key service; please enable HTTPS using the [xpack.security.http.ssl.enabled] setting or disable the API key service using the [xpack.security.authc.api_key.enabled] setting",
  "service.name":"ES_ECS",
  "process.thread.name":"main",
  "log.logger":"org.elasticsearch.bootstrap.BootstrapChecks",
  "type":"server",
  "node.name":"30967a0e299e",
  "cluster.name":"docker-cluster"
}
```

Until recently, this was an actual _Warning_ and the API key service was enabled even though TLS was disabled.

Now, it seems like the API key service won't start without TLS, but the log message hasn't changed, which is misleading. I'm not sure whether this behaviour was intentional, but I would expect either:
* An error to be logged instead of a warning
* The API key service to be enabled regardless, just like it used to be

**Steps to reproduce**:

 1. Start Elasticsearch with ~its default~ [this minimal configuration](https://github.com/deviantony/docker-elk/blob/980c5c480ff1486d37981b68dc7aa03c10f5c16e/elasticsearch/config/elasticsearch.yml#L1--L13)
 1. Set `xpack.security.authc.api_key.enabled: true`
 1. Restart Elasticsearch
 1. Observe that the message above is logged at the WARN level
 1. Observe that the API key service isn't actually enabled (`/_security/api_key`)

**Provide logs (if relevant)**:

Full logs: https://github.com/deviantony/docker-elk/pull/544/checks?check_run_id=1714913116#step:11:17
(where you can also see Enterprise Search fail because the API key service is now disabled)

**Comment by tvernum** [comment]
> Until recently, this was an actual Warning and the API key service was enabled even though TLS was disabled.

I don't think this is the case.

This is a [Bootstrap Check](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/bootstrap-checks.html), as such it is a warning when you are in development mode (e.g. bound to a loopback address - see the linked docs) and a fatal error when you are in production mode (all other cases).
 
In your case you are [using `single-node` discovery](https://github.com/antoineco/docker-elk/blob/future/docker-stack.yml#L16-L18), so bootstrap checks should not be enforced.

Since you are seeing the bootstrap failure logged as a warning, that implies that the bootstrap checks are not being enforced. - they _should_ throw an exception if they are being enforced, and that exception would not be logged by the `BootstrapChecks` class.

> ```
>  "log.level": "WARN",
>  "message":"HTTPS is required in order to use the API key service; please enable HTTPS using the [xpack.security.http.ssl.enabled] setting or disable the API key service using the [xpack.security.authc.api_key.enabled] setting",
> // ...
>   "log.logger":"org.elasticsearch.bootstrap.BootstrapChecks",
> ```

All of that fits with what you're observing - this message is simply a warning.

What I think is an issue here is this:

> **Steps to reproduce:**
>
> 1. Start Elasticsearch with its default configuration
> 2. Set xpack.security.authc.api_key.enabled: true
> 3. Restart Elasticsearch
> 4. Observe that the message above is logged at the WARN level
> 5. Observe that the API key service isn't actually enabled (/_security/api_key)

Those steps don't ever turn on security. Even though you turn on the API key service, it won't work without security being enabled.

What I can't follow is how these steps worked for you on 7.10

**Comment by antoineco** [comment]
My bad, my issue description contains a mistake! I said "default", but in fact the configuration I used is this one: https://github.com/deviantony/docker-elk/blob/980c5c480ff1486d37981b68dc7aa03c10f5c16e/elasticsearch/config/elasticsearch.yml#L1--L13 

Sorry for that.

**Comment by tvernum** [comment]
I can't reproduce this easily. It looks like there's something specific to your setup - are you able to generate a cut down reproduction?

This is what I just tried:
```
docker run -p 9200:9200 -p 9300:9300 \
   -e ELASTIC_PASSWORD=changeme -e discovery.type=single-node -e xpack.license.self_generated.type=trial  \
   -e xpack.security.enabled=true -e xpack.security.authc.api_key.enabled=true \
   docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
```

```
GET /
===
{
  "name": "48cf2d3bf41e",
  "cluster_name": "docker-cluster",
  "cluster_uuid": "-vdb39RQReGRf2bh3SBscw",
  "version": {
    "number": "8.0.0-SNAPSHOT",
    "build_flavor": "default",
    "build_type": "docker",
    "build_hash": "63c85ff3e846a13ae1294e99fc8ad63b9dd72d38",
    "build_date": "2021-01-24T13:23:08.274944Z",
    "build_snapshot": true,
    "lucene_version": "8.8.0",
    "minimum_wire_compatibility_version": "7.12.0",
    "minimum_index_compatibility_version": "7.0.0"
  },
  "tagline": "You Know, for Search"
}
```

```
GET /_license
===
{
  "license": {
    "status": "active",
    "uid": "5bbf2c6c-03c2-4613-8b09-0719e4b4a550",
    "type": "trial",
    "issue_date": "2021-01-25T02:02:21.592Z",
    "issue_date_in_millis": 1611540141592,
    "expiry_date": "2021-02-24T02:02:21.592Z",
    "expiry_date_in_millis": 1614132141592,
    "max_nodes": 1000,
    "max_resource_units": null,
    "issued_to": "docker-cluster",
    "issuer": "elasticsearch",
    "start_date_in_millis": -1
  }
}
```

```
GET /_security/api_key
===
{
  "api_keys": []
}
```

Everything looks fine there, what am I missing?

**Comment by antoineco** [comment]
@tvernum I noticed the error because Enterprise Search started crashing in our test pipeline around December 20 (see [CI logs](https://github.com/deviantony/docker-elk/pull/544/checks?check_run_id=1714913116#step:11:309)). We have a branch that's been targeting ES 8.0 since October 15, and Enterprise Search didn't throw that error before ([full history of CI runs](https://github.com/deviantony/docker-elk/actions?query=branch%3Afuture+workflow%3ACI)).

I acknowledged your failed repro and will try to come up with something more detailed this week.

**Comment by antoineco** [comment]
@tvernum you're right, I can't reproduce the issue either. I got misled into believing the error message reported by Enterprise Search (`"Elasticsearch API key service must be enabled"`) and as a result misinterpreted the warning message printed by Elasticsearch.

Closing as an Enterprise Search issue. Sorry for the noise.
