### ISSUE TITLE
[CI] yaml=stack/10_basic/Test stack template installation} failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#67676]
**Build scan**: https://gradle-enterprise.elastic.co/s/abge4tnwtb6r4

**Repro line**: `./gradlew ':x-pack:plugin:stack:qa:rest:yamlRestTest' --tests "org.elasticsearch.xpack.stack.StackYamlIT.test {yaml=stack/10_basic/Test stack template installation}" -Dtests.seed=F85D4C855E185A74 -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Africa/Sao_Tome -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.stack.StackYamlIT&tests.test=test%20%7Byaml%3Dstack/10_basic/Test%20stack%20template%20installation%7D

No other failure so far.

**Failure excerpt**:

```
"root_cause" : [ |  
-- | --
  | { |  
  | "type" : "resource_not_found_exception", |  
  | "reason" : "Lifecycle policy not found: logs", |  
  | "stack_trace" : "org.elasticsearch.ResourceNotFoundException: Lifecycle policy not found: logs |  
  | at org.elasticsearch.xpack.ilm.action.TransportGetLifecycleAction.masterOperation(TransportGetLifecycleAction.java:67) |  
  | at org.elasticsearch.xpack.ilm.action.TransportGetLifecycleAction.masterOperation(TransportGetLifecycleAction.java:34) |  
  | at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:162)
```

**Comment by joegallo** [comment]
`master` https://github.com/elastic/elasticsearch/commit/1143769cde4c6fd85aba1a9ff229d271471f8a56
`7.x` https://github.com/elastic/elasticsearch/commit/ef4faed0dcb14e558258415ff30833989cc6cb44
