### ISSUE TITLE
Document number_of_routing_shards usage in 7.x related to reindexing from lower versions and document distribution changes

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#67689]
https://github.com/elastic/elasticsearch/pull/60311 added `number_of_routing_shards` from [index module 7.8 documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-modules.html#_static_index_settings) for split API

[Breaking changes documentation on document distribution changes](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_document_distribution_changes) specify this setting requires same value as number of primary shard since 7.0 to maintain same distribution when using custom routing.

However the index module doc does currently not mention the setting prior to 7.8 or the fact it's used for routing

Example to add to documentation from 7.8 (similar content would be great for all prior 7.x documentation to help users of custom routing not miss this important breaking change - this is not checked in the upgrade assistant in 6.8) : 
> NOTE : `index.number_of_routing_shards` is also used for document distribution from 7.0 and should be set when reindexing from an older index using custom routing (refer to [breaking change documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/breaking-changes-7.0.html#_document_distribution_changes))

**Comment by jrodewig** [comment]
Thanks @jguay.

I've opened #69541 to address this. If you have any feedback, please feel free to leave it on the PR.

While we occasionally make exceptions, we typically only backport doc changes to currently maintained versions. As of writing, that would be `master`, `7.x` (7.13+), `7.12`, and `7.11`. This also aligns with our recommend upgrade paths from 6.x and earlier versions.
