### ISSUE TITLE
[CI] {search/110_field_collapsing/field collapsing and multiple inner_hits} failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#67682]
**Build scan**: https://gradle-enterprise.elastic.co/s/6dya3ao437ryk

**Repro line**: `gradlew ':qa:mixed-cluster:v6.8.14#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and multiple inner_hits}" -Dtests.seed=FD0D84F14B070EEA -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=hr-HR -Dtests.timezone=Europe/Malta -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: 7.x, 7.11

**Failure history**: [3 times](https://build-stats.elastic.co/app/kibana#/discover/0d588210-3843-11ea-a7eb-15e193b310ea?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20(branch:%227.x%22%20OR%20branch:%22master%22%20OR%20branch:%227.11%22%20OR%20branch:%226.8%22)%20AND%20test:%22test%20%7Bp0%3Dsearch%2F110_field_collapsing%2Ffield%20collapsing%20and%20multiple%20inner_hits%7D%22'),sort:!(time,desc))) since yesterday.

Other instance of this failure today: https://gradle-enterprise.elastic.co/s/7ztfqozgopoa2

**Failure excerpt**:

(mismatch in expected total count)

```
java.lang.AssertionError: Failure at [search/110_field_collapsing:339]: count didn't match expected value:                          count: expected Integer [6] but was Integer [5]  	at __randomizedtesting.SeedInfo.seed([FD0D84F14B070EEA:7559BB2BE5FB6312]:0) 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:416) 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:393) 	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498)
--
```

**Comment by javanna** [comment]
Is this the same as #52416 ?

**Comment by martijnvg** [comment]
@javanna Yes, I think so. For some reason this failure didn't appear when I searched for previous failures...
