### ISSUE TITLE
[CI] CorruptedBlobStoreRepositoryIT.testMountCorruptedRepositoryData test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#67696]
**Build scan**: https://gradle-enterprise.elastic.co/s/roqbjclxvcbou

**Repro line**: `./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.CorruptedBlobStoreRepositoryIT.testMountCorruptedRepositoryData" -Dtests.seed=77A65478567458BB -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=Navajo -Druntime.java=8`

**Reproduces locally?**: yes!

**Applicable branches**: 7.10

**Failure history**: Only once in the last 7 days:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.snapshots.CorruptedBlobStoreRepositoryIT&tests.sortField=FAILED&tests.test=testMountCorruptedRepositoryData&tests.unstableOnly=true

**Failure excerpt**:

```
junit.framework.AssertionFailedError: Expected exception RepositoryException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([77A65478567458BB:587159D591753152]:0)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2744)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2734)
        at org.elasticsearch.snapshots.CorruptedBlobStoreRepositoryIT.testMountCorruptedRepositoryData(CorruptedBlobStoreRepositoryIT.java:323)
```

**Comment by original-brownbear** [comment]
Reproduces on 7.11 as well, looking into it

**Comment by original-brownbear** [comment]
This is a pretty minor issue fortunately. The corruption test is merely creating a corrupted file sequence that starts with "{}" which our parser accepts as empty repository data. Will make the parser a little stricter

**Comment by martijnvg** [comment]
The error just occurred in master intake ci: https://gradle-enterprise.elastic.co/s/bu4htfnvrji22

**Comment by original-brownbear** [comment]
I think we broke this a different way than before now with some repo data load+caching changes. I'll fix it tomorrow, it's not a bug just a test issue I think.

**Comment by cbuescher** [comment]
Muted on master and 7.x
