### ISSUE TITLE
Add full support for join queries

### ISSUE THREAD

**Issue by gamars** [elastic/elasticsearch#6769]
Using lucene's org.apache.lucene.search.join package we could be able to generate full join query with the proper "from, to, on" parameters.

**Comment by matthiasg** [comment]
Is apache spark capable of joins on top of es ? https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html does not mention it ...

**Comment by clintongormley** [comment]
There are no plans to support full joins.  Closing

**Comment by mrdanadams** [comment]
@clintongormley We've been using the siren-join plugin (https://github.com/sirensolutions/siren-join) pretty heavily but the company behind it just told us they are going to stop supporting it. Still, with a large data set we've had some good results with it. The idea is similar to using a terms filter with values from another document except that the values come from the result of a search.

Would there be any re-considering supporting this at the ES level? Using siren-join also requires turning on 'cache everything' on your index (which isn't ideal). Perhaps if it were native it could be more optimally integrated?

**Comment by maxnilz** [comment]
mark
