### ISSUE TITLE
Combine float, scaled_float and half_float into same field family

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#67723]
As part of #53175, we can consider merging together `float`, `half_float` and `scaled_float` data types into a generic `float` data type. `_field_caps` API would only return `float` whenever `float`, `half_float` or `scaled_float` exists in indices mappings.

**Comment by astefan** [comment]
Depends on https://github.com/elastic/elasticsearch/issues/67727.

**Comment by jtibshirani** [comment]
This sounds like a great follow-up to #53175! @astefan hope it's okay with you, I updated the title to refer to 'field families' to avoid confusion. We usually say 'data type' to mean a concrete field type in the mappings.

**Comment by jtibshirani** [comment]
We decided to look into this seriously, and plan to catch up with other teams to get their opinions.

**Comment by javanna** [comment]
Based on more recent discussions, this change has implications and brings little gain, hence we are not going to make it.
