### ISSUE TITLE
QL: integrate high-level field retrieval support in SQL and EQL

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#67727]
Following the merge of [high-level field retrieval in _search](https://github.com/elastic/elasticsearch/pull/60100) (docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/search-fields.html#search-fields-param)), we should switch from extraction from `_source` and `docvalue_fields` to using `fields` option.

**Comment by astefan** [comment]
Revisit https://github.com/elastic/elasticsearch/issues/43798 after closing this issue.

**Comment by costin** [comment]
I believe this can be closed.
