### ISSUE TITLE
SQL: can't query an index with null values only

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#67816]
[Very corner case.]
Creating an index with only null values will get reported as existing table, but no querying it is possible.
Resolving field's type to the `NULL` type should be possible.
```
POST test/_doc
{
  "a": null
}
```
```
sql> show tables;
            name            |     type      |     kind
----------------------------+---------------+---------------
test                        |TABLE          |INDEX

sql> select a from test;
Bad request [Found 1 problem
line 1:8: Unknown column [a]]
```
But all good once the type's resolution's clear.
```
POST test/_doc
{
  "a": 0
}
```
```
sql> select a from test;
       a
---------------
null
0

```

**Comment by matriv** [comment]
Check if possible to improve the error message and point to what's happening if there is no mapping, and maybe point to `show tables` to check if there are concrete column types.

**Comment by palesz** [comment]
```
PUT /test/_doc/1
{
  "a": null
}

GET /test/_mapping
```

Results in no mapping: `{"test":{"mappings":{}}}`

**Comment by bpintea** [comment]
> Results in empty mapping: `{"test":{"mappings":{}}}`

Right. And because of this the index resolver won't be able to establish that there's a field in the index. Not ideal, but not of a relevant impact either, so closing.
