### ISSUE TITLE
Remove concurrent modification check in rollover action

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#67836]
The concurrent modification check does a "soft" rollover prior to the real rollover, comparing that result to the final "hard" rollover to make sure no other rollovers have happened in the meantime.

However, now that rollovers are completed in a single cluster state update, we don't need this compare-and-set check, as it only means we introduce our own race condition (that throws an exception when it races).

This does mean, however, that concurrent rollovers will result in rolling over twice (which is closer in line with what is intended since rollover was invoked twice).

**Comment by henningandersen** [comment]
In the unconditional rollover case, this sounds like reasonable behavior.

If there are conditions in the request, it would seem most correct that two concurrent rollovers that both request to rollover after X GB/docs/age only result in one rollover. I think the exception response is non-helpful though, we could turn that into the same response as when conditions are not met.

We could reevaluate the conditions and retry instead, but given that these happen concurrently, it must be legal to assume that the second rollover did not fulfill any of the conditions. There is a problem with conditions involving `<=0`  size/age/docs. We should check that at least one of the conditions have a number `> 0`.

So I suggest to:

1. Trigger two rollovers when no conditions are included or all conditions check against a value `<= 0` (unconditional rollover).
2. Trigger only one rollover when conditions are included and let the second rollover respond not rolled over.

Optionally, we could consider deprecating the ability to check conditions against `<= 0` values.

**Comment by dakrone** [comment]
@henningandersen that is in line with what I am working on. I've discovered there are a couple of other race condition issues with the transport rollover code, so those will be fixed with this change as well.
