### ISSUE TITLE
RepositoryMissingException when running EncryptedRepositorySecretIntegTests.testWrongRepositoryPassword

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#67834]
**Build scan**:

https://gradle-enterprise.elastic.co/s/te3jyynvpqpli/tests/:x-pack:plugin:repository-encrypted:internalClusterTest/org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests/testWrongRepositoryPassword#1

**Repro line**:

REPRODUCE WITH: ./gradlew ':x-pack:plugin:repository-encrypted:internalClusterTest' --tests "org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests.testWrongRepositoryPassword" \
  -Dtests.seed=54D666F6B99A8BC5 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SG \
  -Dtests.timezone=America/Edmonton \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true

(note - there are non-fips failures in the history)

**Reproduces locally?**:

Not for me.

**Applicable branches**:

7.x, Master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/New_York&tests.container=org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests&tests.sortField=FAILED&tests.test=testWrongRepositoryPassword&tests.unstableOnly=true

**Failure excerpt**:
org.elasticsearch.repositories.RepositoryMissingException: [qf] missing

**Comment by not-napoleon** [comment]
This doesn't seem to be failing frequently, so I'm leaving it unmuted for now.

**Comment by williamrandolph** [comment]
I just got this on 7.x: https://gradle-enterprise.elastic.co/s/rw6khjnwawd2g/tests/:x-pack:plugin:repository-encrypted:internalClusterTest/org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests/testWrongRepositoryPassword#1

**Comment by matriv** [comment]
New failure on master:
https://gradle-enterprise.elastic.co/s/dnukblq6xddlq

```
org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests > testWrongRepositoryPassword FAILED
10:55:31     org.elasticsearch.repositories.RepositoryMissingException: [cuzeer] missing
10:55:31         at __randomizedtesting.SeedInfo.seed([334777FA22EF305A:1E630C8F31FF7AD5]:0)
10:55:31         at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:503)
10:55:31         at org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests.testWrongRepositoryPassword(EncryptedRepositorySecretIntegTests.java:586)
```
**REPRODUCE WITH:** 
```
./gradlew ':x-pack:plugin:repository-encrypted:internalClusterTest' --tests "org.elasticsearch.repositories.encrypted.EncryptedRepositorySecretIntegTests.testWrongRepositoryPassword" -Dtests.seed=334777FA22EF305A -Dtests.security.manager=true -Dtests.locale=en-GB -Dtests.timezone=America/Argentina/Mendoza -Druntime.java=11
```

Couldn't reproduce locally.
