### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT execution performance degraded causing timeouts

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#67853]
**Update:** This initially started as an investigation into Windows performance but it seems something has happened to this test suite which is affecting execution times on both Windows and Linux now. It's just that this is severe enough on Windows to result in suite timeouts.

While investigating some test timeout issues in TeamCity I noticed that we have very different performance characteristics with regards to test execution between Windows Server 2012 R2 and Server 2016/2019. In the examples below I'm using `XPackRestIT` since it's a very large and long running test suite. Hardware is identical across the board here as well, 32 Cores, 96GB of RAM and 150GB SSD-backed disk. Since this is Windows we are _not_ using a ramdisk.

Here's a graph of execution times for `XPackRestIT` for the last month on **WIndows 2012 R2**
![image](https://user-images.githubusercontent.com/4106672/105425969-2924d580-5bff-11eb-9539-93cd166e522d.png)

And here's **Windows Server 2016**
![image](https://user-images.githubusercontent.com/4106672/105426031-478ad100-5bff-11eb-929f-ada613c1a410.png)

And **Windows Server 2019**
![image](https://user-images.githubusercontent.com/4106672/105426070-5b363780-5bff-11eb-8da7-4f43b072d3b6.png)

So the main question is: why is this taking nearly 50% longer on the later Windows versions? On TeamCity the delta is even worse (although execution times on 2012 R2 are identical between Jenkins and TeamCity).

**Comment by mark-vieira** [comment]
My first shout out here is going to be to @elastic/es-perf. Have we done performance testing on different Windows versions? If so, was a similar disparity observed? Any other gotchas with regard to Windows performance that we might be able to implement to improve this?

**Comment by danielmitterdorfer** [comment]
No we did not run any performance tests on Windows so I fear we also don't have much input here.

**Comment by mark-vieira** [comment]
@DaveCTurner any chance #67829 might be in play here given that we've added an additional step to every test in this suite (1700 of them)?

**Comment by DaveCTurner** [comment]
Oh. Oh dear. That's only needed once for the whole suite, not once per test.

**Comment by DaveCTurner** [comment]
I opened https://github.com/elastic/elasticsearch/pull/68013.

**Comment by mark-vieira** [comment]
That looks better:

![image](https://user-images.githubusercontent.com/4106672/106225517-2a737680-619a-11eb-9ccb-b9eb899dcc06.png)
