### ISSUE TITLE
[docs] Start transform API missing scope

### ISSUE THREAD

**Issue by cdalexndr** [elastic/elasticsearch#67870]
[API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-transform.html) is missing start command scope.

If I restart elasticsearch, do I need to re-run the start command or the transform remains active?

**Comment by hendrikmuhs** [comment]
@cdalexndr transforms are "persistent tasks", that means they are stored in cluster state. This makes them resilient for failures. If a single node fails in a cluster another one can take over, see https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-checkpoints.html#ml-transform-checkpoint-errors

> If I restart elasticsearch, do I need to re-run the start command or the transform remains active?

No, transform will try to recover from the last persisted state. It will continue from this position. 

> API docs is missing start command scope.

I am not sure about this, but let our @elastic/ml-docs decide. I checked, comparable API's (ML, rollup) do not mention it in the `_start` docs. But maybe the docs around it, can be improve a little bit to explain what a "persistent task" means.

What does "restart elasticsearch" mean for you? The whole cluster? Do you have a cluster or does your cluster consist only of 1 node?

As explained above, if you restart a single node and it happens to be the one where the transform is running on, the task will be automatically moved to another node.

I hope that helps. If you have further questions, I would like to continue the discussion in the [discuss forum](https://discuss.elastic.co/tag/transforms). Once we identified concrete issues/tasks, they can be opened on github.

**Comment by hendrikmuhs** [comment]
Documentation improvements have been addressed in https://github.com/elastic/elasticsearch/pull/68582

Closing
