### ISSUE TITLE
Highlighting require_field_match option does not always work

### ISSUE THREAD

**Issue by davidlbowen** [elastic/elasticsearch#6787]
I have this record:
```
{
   "field1": "x y",
   "field2": "y"
}
```
and this query:
```
{
    "query": {
        "multi_match": {
             "query":  "x y",
             "fields": [ "field1", "field2" ],
             "operator": "and"
        }
    },
    "highlight" : {
        "fields" : {
            "field1" : { "number_of_fragments" : 0 },
            "field2" : { "number_of_fragments" : 0 }
        },
        "require_field_match": true
    }
}
```
The highlights returned are:
```
      "highlight" : {
        "field2" : [ "<em>y</em>" ],
        "field1" : [ "<em>x</em> <em>y</em>" ]
      }
```
So field2 is highlighted although it was not part of the match (and it does not show up in the explain output).

**Comment by javanna** [comment]
Sorry it took ages to get to this. I spent some time looking at this, we can call it a bug, or just asking too much of highlighting :) 

The meaning of `requireFieldMatch` is different from what is expected here. It is really only about field names, not really matching queries. By default (`require_field_match: false`) the field name gets ignored, for instance with the following document

```
{
  "field1":"value",
  "field2":"value"
}
```

the following search request will cause `field2` to be highlighted simply based on the fact that it contains the term `value` that was mentioned in the query, the field name gets ignored. 

```
{
  "query" : {
    "match" : {
        "field1" : "value"
    }
  },
  "highlight" : {
    "fields" : {
      "field2" : { }
    }
  }
}
```

By setting `require_field_match` to `true` the field name will be taken into account and only `field1` will be highlighted for a query executed against `field1`.


I can give you some more explanation of how lucene works internally here, just to explain why `field2` gets highlighted in your original example. It might seem strange but highlighting doesn't always highlight matching queries, but it's more about matching terms extracted from queries, which is close... The internal lucene query generated in your case is a `DisjunctionMaxQuery` that contains two `BooleanQuery`s, each of which holds two `TermQuery`s as clauses.

```
((+field2:x +field2:y) | (+field1:x +field1:y))
```

while highlighting `field2`, each of the leaf queries (the term queries) are checked against the field content, regardless of the context. When checking `field2:y` for instance, the highlighter doesn't really look at whether the clause was in and with some other clause, as each leaf is highlighted independently. If the `y` term appears in the field, it gets highlighted. By setting `require_field_match` to `true` you are just making sure that the match was really on that same field, which it is, but there is no way to make sure that the query is an actual match overall.

I think there isn't much that we can do to fix this, we just need to live with this limitation, or eventually report this issue (that doesn't have much to do with require field match anyway) upstream to lucene.

**Comment by javanna** [comment]
I think we can close this, nothing we can do here.

**Comment by fernandocoronatomf** [comment]
I'd like to ask it as well:

> so how to avoid highlighting unmatched fields ?
