### ISSUE TITLE
_cluster/stats fs data not match the __nodes/stats/fs data

### ISSUE THREAD

**Issue by kin122** [elastic/elasticsearch#67876]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.2
**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0
**OS version** (`uname -a` if on a Unix-like system):
centos 7.6
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.I have al cluster with 8 nodes
 2.the cluster stats show the fs usage like this
![图片](https://user-images.githubusercontent.com/39018485/105655903-01ce5100-5efc-11eb-9bc3-e4b07c91c88a.png)

 3. but FS usage for each node is about 3T
![图片](https://user-images.githubusercontent.com/39018485/105656089-6be6f600-5efc-11eb-8e40-3104e081ef1d.png)

there is no path reuse ，each node have independent  ip and path.
By rights.The statistics of the cluster must be equal to the sum of the data of the individual nodes.
But it's not.why?

**Comment by matriv** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
