### ISSUE TITLE
Prevent interaction between source-only repositories and searchable snapshots

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#67936]
Source-only repositories and searchable snapshots don't mix, but today we don't have any special handling to prevent users from trying to mix them. A [user on the forums reported](https://discuss.elastic.co/t/issue-using-searchable-snapshots-in-an-ilm-policy/262001) that this does lead to errors but they're pretty obscure.

We should decide whether to support this combination or not. If not then we should reject it in a clearer and more actionable fashion.

**Comment by ywelsch** [comment]
I think we should support this, as it's fairly trivial to do so and enables a number of interesting use cases in combination with runtime fields (see also https://github.com/elastic/elasticsearch/issues/67972). I've opened https://github.com/elastic/elasticsearch/pull/67975
