### ISSUE TITLE
Listening addresses configuration (network.host) not specified (multiple values allowed)

### ISSUE THREAD

**Issue by Chealer** [elastic/elasticsearch#67956]
Following ticket #13592 and a change my @rmuir , it has been possible for a long time to give _network.host_ several values. For example:
`network.host: [ '_local_' , '_site:ipv4_' ]`

Unfortunately, _network.host_ is unspecified and that change was accompanied by hardly any documentation update. It would be most helpful to specify, or at least add at least 1 example with multiple values.

The default configuration file pretty much implies that multiples values are unsupported:
> Set the bind address to a specific IP (IPv4 or IPv6):

### Note
[The current section](https://www.elastic.co/guide/en/elasticsearch/reference/master/important-settings.html#network.host)'s phrasing suggests that this setting is only useful to form a cluster.

**Comment by DaveCTurner** [comment]
I think it's pretty confusing that `network.host` supports multiple values. This setting determines both the (multiple) addresses to which we bind and the (single) publish address used for cluster formation. If this setting resolves to multiple addresses then the unique publish address is chosen from them [by magic](https://github.com/elastic/elasticsearch/blob/f6f42600243d4aaa36539bdb5108fe191a6e9353/server/src/main/java/org/elasticsearch/common/network/NetworkService.java#L130) (i.e. arbitrarily) which is trappy. IMO it'd be better to require a multi-homed setup to specify which of its addresses is the publish address to avoid this confusion.

I'd generally expect that these days it only makes sense to bind HTTP to multiple addresses, which you can do via `http.host`, although that's also not mentioned in the docs. Binding the transport to multiple addresses is useful for exposing a cluster to remote clusters for CCS/CCR, but can definitely cause cluster formation headaches unless the publish host is also specified.

Anyway yes I think this is an area we can document better.

**Comment by Chealer** [comment]
@DaveCTurner I see that a lot of work was done regarding this and related issues, but do you consider that this configuration is now specified?

**Comment by DaveCTurner** [comment]
Yes, this was closed by #68051. The [current networking config docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html) describe what it means to set `network.host` to a list of values whilst guiding the reader away from doing so.

**Comment by Chealer** [comment]
First of all, I should clarify that the reference treats network.host twice, in the page mentioned by @DaveCTurner (Configuring Elasticsearch » Networking) as well as in the page I was reading (Configuring Elasticsearch » Important Elasticsearch configuration). I suppose the priority should be to start by clarifying the former.

That being said, as far as I can see, neither of these pages properly specifies it. Dave, can you clarify where you consider that "The current networking config docs describe what it means to set `network.host` to a list of values"?

**Comment by DaveCTurner** [comment]
The "Important Elasticsearch configuration" page is more of a quick-start guide, it deliberately omits a full specification of each setting to avoid overwhelming the reader, so I think it's right not to mention the possibility of providing a list of addresses there.

The more exhaustive docs on the "Networking" page do however definitely say that you can provide a list, and describe what happens if you do so:

> **NOTE**: You can specify a list of addresses for `network.host` and `network.publish_host`. You can also specify a single hostname which resolves to multiple addresses. If you do this then Elasticsearch chooses one of the addresses for its publish address. This choice uses heuristics based on IPv4/IPv6 stack preference and reachability and may change when the node restarts. You must make sure that each node is accessible at all possible publish addresses.

Perhaps I'm not understanding what you think is still missing here. Could you clarify?

**Comment by Chealer** [comment]
Thank you Dave

I agree with you that the "Important Elasticsearch configuration" page needs not to fully specify network.host, and the possibility to enter multiple addresses is one thing which can be omitted.

However, the main problem at this time is in the Networking page. While it does eventually mention that network.host can receive a list of addresses, the part which is specifically about network.host (in _[Commonly used network settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings)_) **implies that it can only have 1 address**:

>     (Static) Sets the address of this node for both HTTP and transport traffic. The node will bind to this address and will also use it as its publish address. Accepts an IP address, a hostname, or a special value.
> 
>     Defaults to _local_.

**Comment by DaveCTurner** [comment]
Yes, that is deliberate. Using a list value for `network.host` is almost certainly a mistake. Ideally we would drop support for lists of values for this setting for that reason, but that's quite a long process since we must make breaking changes carefully and consciously, and yet the practical benefits would be pretty small so it's not really worth the effort right now. We feel it's sufficient for the docs to guide users away from mistakenly using a list like this whilst still mentioning what would happen if you did so.

**Comment by Chealer** [comment]
I kind of understand your position @DaveCTurner , but as status quo tends to last longer than we'd imagine, I'd still recommend to fix the doc. Considering that the setting's name is already misleading, if multiple pieces of documentation clearly imply that only one value is allowed, confusion is sure to find more admins.
