### ISSUE TITLE
RPM-Installation not complete

### ISSUE THREAD

**Issue by einfallstoll** [elastic/elasticsearch#6798]
I'm on a `SUSE Linux Enterprise Server 11 (x86_64)` and evaluating ElasticSearch to replace an existing solution.

I downloaded [the rpm-release](https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.noarch.rpm) and tried to install it using `rpm -i elasticsearch-1.2.1.noarch.rpm` but neither the group shown in [preinstall](https://github.com/elasticsearch/elasticsearch/blob/master/src/rpm/scripts/preinstall) is added nor the [init-script](https://github.com/elasticsearch/elasticsearch/blob/master/src/rpm/init.d/elasticsearch) is moved/copied to `/etc/init.d`.

Am I missing something or is the installation routine messed up for SLES?

**Comment by clintongormley** [comment]
Closing in favour of #12555
