### ISSUE TITLE
failed to put template [filebeat-7.10.2]

### ISSUE THREAD

**Issue by chenpfeisoo** [elastic/elasticsearch#67980]
{"type": "server", "timestamp": "2021-01-26T12:34:28,924+0000", "level": "DEBUG", "component": "o.e.a.a.i.t.p.TransportPutIndexTemplateAction", "cluster.name": "docker-cluster", "node.name": "73c2f3182272", "cluster.uuid": "5Vh4CG6CRNiFPdLeEAVi5g", "node.id": "8iphj99QTyicPxy2_1PVVQ",  "message": "failed to put template [filebeat-7.10.2]" ,
"stacktrace": ["org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: No handler for type [flattened] declared on field [devices]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:327) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateAndAddTemplate(MetaDataIndexTemplateService.java:253) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:65) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.execute(MetaDataIndexTemplateService.java:176) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.2.0.jar:7.2.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.2.0.jar:7.2.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",

env:
![image](https://user-images.githubusercontent.com/18147157/105845728-346c6c80-6016-11eb-89b7-d394a30956c7.png)

**Comment by jtibshirani** [comment]
@chenpfeisoo it looks like your Elasticsearch/ Kibana version (7.2.0) doesn't match the Filebeat version (7.10.2). Filebeat is trying to use a new field type called `flattened` that is not available in 7.2.0, so template validation is failing. In general Elasticsearch and Filebeat need to have the same minor version.

**Comment by chenpfeisoo** [comment]
When all components use version 6.5, there is no problem

**Comment by cbuescher** [comment]
I think this can be closed then.
