### ISSUE TITLE
Percolator to support inner-hits for Nested queries

### ISSUE THREAD

**Issue by hitesh-tarani** [elastic/elasticsearch#68001]
This was already [discussed](https://discuss.elastic.co/t/possible-to-highlight-inner-hits-in-percolate-query/91926) long time back.
The percolate query currently doesn't support(ignores) inner-hits for stored queries which are nested queries with inner-hits.

Feature request: Add inner-hits in percolation query response if percolate query has a matching nested filter with inner-hits set. These will be the child inner-hits matching the nested query from the percolation-documents provided in percolate query.

Use-case: We have new documents coming into the system, and we have user-defined queries for which items if they match, they need to be notified(or some other action).  Currently to solve this, we split the document into separate documents with a single item, cloning other details.
This works, but I find this a lot inefficient as all other queries except the nested query needs to be evaluated many times, even though none may actually match. Also, the client needs to manage the document by splitting, querying ES for each.

Fictional Example:
Original Document:
```
{
  "items": [
    {
      "vendor": "vendorA",
      "quantity": 10,
      "location": "location1",
      "tags": []
    },
    {
      "vendor": "vendorB",
      "quantity": 50,
      "location": "location2",
      "tags": ["expire-soon", "delayed"]
    },
    {
      "vendor": "vendorC",
      "quantity": 30,
      "location": "location3",
      "tags": ["delayed"]
    }
  ],
  "customer": "custA",
  "status": "Active"
}
````
Split Document:
```
{
  "item": {
    "vendor": "vendorA",
    "quantity": 10,
    "location": "location1",
    "tags": []
  },
  "customer": "custA",
  "status": "Active"
}
```
Stored query for percolation:
```
{
  "query": {
    "bool": {
      "filter": [
        {
          "nested": {
            "path": "item",
            "query": {
              "bool": {
                "filter": [
                  {
                    "terms": {
                      "vendor": ["vendorA", "vendorC"]
                    }
                  },
                  {
                    "terms": {
                      "tags": ["delayed"]
                    }
                  }
                ]
              }
            },
            "inner_hits": {} // support this for percolate query, path will be changed to items
          }
        },
        {
          "term": {
            "status": "Active"
          }
        },
        {
          "terms": {
            "customer": ["custA", "custB"]
          }
        }
      ]
    }
  }
}
```

Also I would like to work on this, if you guys think this is good to have and can be implemented.

**Comment by jtibshirani** [comment]
Thanks @hitesh-tarani for raising this. I definitely see how supporting `inner_hits` in percolator would be convenient.

Hearing your use case, I wonder if denormalizing the documents is actually strongest approach. When giving guidance on how to model data, we often recommend denormalizing if it's possible. Although some data is duplicated, it often results in a simpler model and faster queries, as nested queries can add significant overhead. The percolator API also allows for sending several documents at once through the `documents` parameter.

So it wouldn't be surprising if your current strategy turned out to be faster. It could be worth benchmarking the two set-ups to see if it's worth pursuing.

**Comment by hitesh-tarani** [comment]
Thanks @jtibshirani for taking a look.

> When giving guidance on how to model data, we often recommend denormalizing if it's possible

Does denormalizing always help, or is it dependent on size of the document or the array(count of nested documents)?

> The percolator API also allows for sending several documents at once through the documents parameter.

Yeah, for our use-case, after denormalizing(splitting) the documents, we send them together in a single percolate query. However it still involves a micro-service hop, and we felt the overall documents size increasing significantly because of data duplication.

**Comment by jtibshirani** [comment]
It's hard to give a definitive answer without digging into the use case + benchmarking, but nested queries are generally slower than their non-nested counterparts. But as you noted, `nested` helps avoid duplicated data (and can support some types of queries not possible with denormalizing).

I suggest we close the issue, as it may not be the right complexity/ performance trade-off (percolator + inner_hits are both quite complex features). We can always reopen if we get more feedback from users that this would be useful.
