### ISSUE TITLE
Elastic Watcher API regression bug (optional parameters are no longer optional when indices_options is specified)

### ISSUE THREAD

**Issue by stevegaossou** [elastic/elasticsearch#68022]
**Elasticsearch version**: 7.10.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux 39b5309d4c57 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Note: This was using the [Elasticsearch Docker v7.10.1 image](https://github.com/elastic/dockerfiles/blob/v7.10.1/elasticsearch/Dockerfile)

**Description of the problem including expected versus actual behavior**:

#### Expected 
When creating a watcher using the Elastic watcher API and using the `indices_options` section, I should not have to include all the following optional paramaters:
* allow_no_indices
* expand_wildcards
* ignore_unavailable

The docs say each of the above is optional: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-get-settings.html#get-index-settings-api-query-params

#### Actual
However, if `indices_options` is specified, then all of the above parameters become required. 

This was not the case in a previous version of Elasticsearch we were using (v7.6.2). 

Attempting to create a watcher with a payload that does not contain those parameters leads to errors: 
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "indices options xcontent did not contain expand_wildcards"
      }
    ],
    "type" : "parse_exception",
    "reason" : "could not parse [search] input for watch [tigera_secure_ee_watch.cluster.honeypod.ip.enum.test]. failed to parse [request]",
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "indices options xcontent did not contain expand_wildcards"
    }
  },
  "status" : 400
}
```

Looking at the code, this section looks like the cause: 
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/support/IndicesOptions.java#L435-L445

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create a new watcher using the Watcher API 
```
PUT /_watcher/watch/some.arbitrary.watcher
{
  "trigger": {
    "schedule": {
      "interval": "300s"
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": [
          "some.arbitrary.index"
        ],
        "body": {
            ...
        },
        "indices_options": {
          "allow_no_indices": true   <--- Define at least one option
        }
      }
    }
  },
  ...
}
```
 2. You will get an error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "indices options xcontent did not contain expand_wildcards"
      }
    ],
    "type" : "parse_exception",
    "reason" : "could not parse [search] input for watch [tigera_secure_ee_watch.cluster.honeypod.ip.enum.test]. failed to parse [request]",
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "indices options xcontent did not contain expand_wildcards"
    }
  },
  "status" : 400
}
```

**Provide logs (if relevant)**:

**Comment by jaymode** [comment]
This is probably due to #65332. I'll look into the issue
