### ISSUE TITLE
DATETIME_FORMAT adds a year for dates in the Dec 27 - Dec 31 range

### ISSUE THREAD

**Issue by aiva** [elastic/elasticsearch#68030]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.1

**Plugins installed**: [none]

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

When formatting dates at the end of the year (Dec 27th+) DATETIME_FORMAT adds a year to the date where it shouldn't

**Steps to reproduce**:

POST _sql/?format=txt
{
  "query": """
SELECT 
  DATETIME_FORMAT(CAST('2020-12-26' AS DATE), 'YYYY-MM') AS first,
  DATETIME_FORMAT(CAST('2020-12-27' AS DATE), 'YYYY-MM') AS second,
  DATETIME_FORMAT(CAST('2021-12-28 00:00:00' AS DATETIME), 'YYYY-MM-dd') AS third
"""
}

produces:

     first              |    second          |     third     
---------------+---------------+---------------
2020-12           | 2021-12            | 2022-12-28     

expected:

     first              |    second          |     third     
---------------+---------------+---------------
2020-12           | 2020-12            | 2021-12-28  

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jtibshirani** [comment]
I think this may be due to Java's date formatting logic: `YYYY` gives the 'week year', whereas `yyyy` is the calendar year (usually what you want). I found [this explanation](https://stackoverflow.com/questions/32847304/java-simpledateformat-shifts-date-by-one-year) to be helpful.

**Comment by aiva** [comment]
> If that addresses your problem I'll plan to close this out, as it doesn't indicate a bug in Elasticsearch (just a confusing part of Java date formats).

Yep it sure does. Should have realized it sooner. Using yyyy works. Closing the issue.

**Comment by aiva** [comment]
Btw I suggest update to the documentation in https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sql-functions-datetime.html to have the examples use the yyyy format instead of YYYY. I'm sure others will unintentionally have the same problem when copy/pasting the examples.
