### ISSUE TITLE
Document built-in index template component

### ISSUE THREAD

**Issue by cdalexndr** [elastic/elasticsearch#68087]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 7.10.1, Build: default/docker/1c34507e66d7db1211f66f3513706fdf548736aa/2020-12-05T01:00:33.671820Z, JVM: 15.0.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system): docker
Linux 6892b17294a4 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Updating an existing managed index template component using the REST API returns success, but the component is not modified.

**Steps to reproduce**:

`logs-settings` is a built-in template component.
```
PUT _component_template/logs-settings
{
  "template": {
    "settings": {
      "number_of_shards": 1,
      "index": {
        "lifecycle": {
          "name": "logs"
        },
        "codec": "best_compression",
        "query": {
          "default_field": [
            "message"
          ]
        }
      }
    }
  }
}
```

returns 
```
{
  "acknowledged" : true
}
```

but calling `GET _component_template/logs-settings` doesn't show the `number_of_shards` setting.

Using other name `logs-settigns2` works as expected.

Should the `managed` template components be read-only?

If yes, a couple of changes should be done to reflect this:

- REST API should return fail if an attempt is made to modify a read-only template
- [Docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) should be updated to specify that the build-in index templates and components cannot be modified by user.
- Kibana: when hovering mouse over `Managed` label besides the template name, the popup should include a brief explanation that it cannot be modified (what does `managed` mean?)

**Comment by gaobinlong** [comment]
`logs-settings` is a stack-managed template and it's version defaults to `0`, maybe you can add `version` parameter into the request body to update the template, if not it will be reset to the origin version.

**Comment by dakrone** [comment]
What @gaobinlong said is correct, if you increment the version Elasticsearch will not overwrite the template. Additionally, you can disable the managed templates entirely (`stack.templates.enabled`) and then change whatever you'd like with the templates.

I do think we could describe it better both in the docs and in the Kibana UI, so I will leave this open for that purpose.
