### ISSUE TITLE
 At least Java 11 is required to build elasticsearch gradle tools

### ISSUE THREAD

**Issue by aserendipper** [elastic/elasticsearch#68097]
**Build scan**:

**Repro line**:
Build file 'elasticsearch/buildSrc/build.gradle' line: 61

**Reproduces locally?**:

**Applicable branches**:
master
**Failure history**:

**Failure excerpt**:
What went wrong:
A problem occurred evaluating project ':buildSrc'.
At least Java 11 is required to build elasticsearch gradle tools

idea：2020.1.2

i want to build elasticsearch to idea,and set JDK to 15,however,this error occurred。
thank you very much

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
