### ISSUE TITLE
ES depends on folder 'elasticsearch' in windows temp directory

### ISSUE THREAD

**Issue by yBother2** [elastic/elasticsearch#68107]
On some clients, Elasticsearch (7.6x) service start up fails:
2021-01-28 08:41:20 Commons Daemon procrun stderr initialized
ERROR: Temporary file directory [...~1\AppData\Local\Temp\elasticsearch] does not exist or is not accessible

That occurs when ~AppData\Local\Temp\elasticsearch does not exist. I don't know why this folder apparently does not exist on some client sometimes. However,  I am very confused that ES depends in a temp directory. This seems weird. At least it should be able to recreate that folder on its own

**Comment by tlrx** [comment]
The document contains information about this temporary folder, see https://www.elastic.co/guide/en/elasticsearch/reference/7.6/zip-windows.html


> The service automatically configures a private temporary directory for use by Elasticsearch when it is running. This private temporary directory is configured as a sub-directory of the private temporary directory for the user running the installation. If the service will run under a different user, you can configure the location of the temporary directory that the service should use by setting the environment variable ES_TMPDIR to the preferred location before you execute the service installation.

**Comment by tlrx** [comment]
Note that we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
