### ISSUE TITLE
Add a runtime field section to the Field Capabilities API

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#68117]
[Runtime fields defined in a search request](https://www.elastic.co/guide/en/elasticsearch/reference/master/runtime-search-request.html) will not appear in the output of the field capabilities API. Merging these runtime fields in the output of the field capabilities API is not trivial since we have some internal logic to decide the capabilities of fields based on their mappings.
In order to make it easier for Kibana, QL, ml or any consumer of runtime fields, the field capabilities API should be able to handle a runtime section just like search requests. The section would be used internally as an override in the mappings of all the indices that the request targets:

```yml
GET my_data_stream/_field_caps?fields=*
{
  "runtime_mappings": {
    "day_of_week": {
      "type": "keyword",
      "script": {
        "source": "emit(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
      }
    }
  }
}
```

Would return all the fields present in the mapping as well as the runtime fields defined in the request (as an override if the field already exists in the index mappings).

Relates #68115

**Comment by przemekwitek** [comment]
@jimczi: How is this issue going? How likely is it to be ready for `7.12`?

**Comment by cbuescher** [comment]
@przemekwitek I recently started looking into this but cannot say for sure what the timeframe for this might be. Hopefully have an estimate soon though.

**Comment by przemekwitek** [comment]
> I recently started looking into this but cannot say for sure what the timeframe for this might be. Hopefully have an estimate soon though.

SGTM, thanks!
