### ISSUE TITLE
QL: Support runtime-fields at query-time

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#68116]
With the introduction of query-time runtime fields, requests can be enhanced with "runtime"/"virtual" fields that augment the mapping.
Both declarative languages should allow clients to specify such fields if desired, similar to the `filter` parameter.
As a side-note, as the number of params increases, it might make sense to encapsulate ES query parameter into a dedicated object so potential future additions, don't end up clashing with other top-level params:

```
filter: {} -> enrich { filter: {} , runtime-mapping : {}, <extra-option> : {}
```

**Comment by astefan** [comment]
This is implemented with https://github.com/elastic/elasticsearch/pull/71356.
