### ISSUE TITLE
EQL: Support returning of runtime fields

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#68115]
Currently EQL returns only `_source` and thus ignores any runtime fields defined in the mapping. This can be addressed, by potentially supporting the `fields` API option just like on Elasticsearch requests.

**Comment by astefan** [comment]
There is a difference, and an unnecessary complication imo, to mimic the support offered by `fields` API in EQL search request, if everything that's needed is only the runtime fields: `fields` accepts any kind of input and retrieves those fields, if they exist.

An EQL output that shows both the original, indexing time, `_source` and potentially the same fields as in those from `_source` means duplicating the output. We could look into adding this request body parameter but limit its functionality to runtime fields only, not name it `fields` but `runtime_fields` or similar and define it as an array of string values representing runtime field names. We can also allow `*` (wildcard) to return all runtime fields (which should be possible in future if https://github.com/elastic/elasticsearch/issues/68117 is implemented).
