### ISSUE TITLE
SLM & ILM Interdependencies

### ISSUE THREAD

**Issue by Alsheh** [elastic/elasticsearch#68180]
Snapshot lifecycle management (SLM) and index lifecycle management (ILM) sometimes can depend on each other and having the ability to prevent an ILM phase from executing until the SLM policy finishes can be vital. For instance, an ILM policy that deletes an index after x number of days could delete the index before the SLM policy gets the chance to snapshot the index; this scenario could occur especially when the master node is overwhelmed and constantly failing to process the snapshot request within the configured master timeout.

Having the ability to configure each ILM phase to depend on a certain a SLM phase and vice versa would be an amazing feature to add and could prevent some unwanted scenarios.

**Comment by dakrone** [comment]
@Alsheh we already have the feature I think you're asking for, the `wait_for_snapshot` action in the delete phase that waits for an SLM policy to take a successful snapshot: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/ilm-wait-for-snapshot.html

Is that what you had in mind, or was there additional functionality I'm not understanding?

**Comment by Alsheh** [comment]
@dakrone this feature does satisfy my own use case and I will reopen if I can think of anything else. Thanks!
