### ISSUE TITLE
how to load balance an ES-cluster with 70+nodes and 70+ replica shards?

### ISSUE THREAD

**Issue by Niidy** [elastic/elasticsearch#68194]
My es is 70+nodes and there is an index with a pri shard and 70+ replica shards,  because there is no new data written, but there are a lot of queries. 

but now, only some of them are 80+ cpu and 20+ load (my node is  16c cpu and 64g mem), more than 80% of nodes are 20-60 cpu. i know a large number of requests only access a few nodes. But I have load balance before ES nodes.  how to setting ES and make the cold nodes be used more.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/45956136/106244971-b0e59200-6246-11eb-870b-4d159024ed7e.png">

`only some of them are 80+ cpu and 20+ load (my node is  16c cpu and 64g mem), more than 80% of nodes are 20-60 cpu.`
<img width="472" alt="image" src="https://user-images.githubusercontent.com/45956136/106244639-30bf2c80-6246-11eb-83c9-29842454dfec.png">
![image](https://user-images.githubusercontent.com/45956136/106245030-c8bd1600-6246-11eb-99e3-2939e6f4f4d1.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
