### ISSUE TITLE
Query one index from index wildcard

### ISSUE THREAD

**Issue by AyWa** [elastic/elasticsearch#68195]
Currently multi target syntax (wildcards) and alias pointing to multiples index queries all the underneath index on query.

However we would like to have a way to query only "one" of the underneath index. Maybe there is not many use case (or it can be done client side by manually load balancing the index we query).

But would be better if it was natively supported in ES.

Usecase could be the following:

* index_xx__slow
* index_xx__fast

if query like `index_xx_*` with a setting like `max_index=1` the es coordinator nodes will only select / load balance one of those 2 index (little bit like it will do with replica)

We have other usecases where it would be helpful :)

**Comment by henningandersen** [comment]
@AyWa thanks for your interest in Elasticsearch. I am not sure I fully understand why this feature is necessary in the first place. To be useful, it sounds like the two indices must have identical data and adding more replicas instead would achieve a similar performance benefit.

Given that this is more easily handled in the client, where you can also code the specific load balancing mechanism yourself, I am inclined to close this. Can you elaborate on why this functionality belongs in ES and not in the client as well as elaborate on the use cases and general usefulness of this feature?

**Comment by AyWa** [comment]
@henningandersen Thank you for your answers.

> it sounds like the two indices must have identical data

Yes that is correct

> adding more replicas instead would achieve a similar performance benefit.

This is usually true, but some use case could be to have same data but with different mapping, and just load balance on them. In this case we need to have different index.

An other use case we have is to have different index on different availability zone but fee is pretty high because we scale/downscale -> so shards movement is expensive across AZ see https://github.com/elastic/elasticsearch/issues/60236 
Because our index are mainly read only it would be easier to just have duplicate index and just loadbalance between them. (with shard-allocation-filtering on each index)

> Given that this is more easily handled in the client, where you can also code the specific load balancing mechanism yourself, I am inclined to close this. Can you elaborate on why this functionality belongs in ES and not in the client as well as elaborate on the use cases and general usefulness of this feature?

I think it belongs to ES rather than client side, the same way the ES load balance shards (if multiple replicas). As I understand ES shards choice is not random. It checks previous performance of the shards etc. And so if we implements that features in client side, it needs to also do that kind of logic at some point (to check if healthy or not, or response time etc -> all the issue with load balancing a services)

But I understand if you think it does not belongs inside ES -> I will work on it client side 🙂

**Comment by henningandersen** [comment]
@AyWa thanks for elaborating. About:

> use case could be to have same data but with different mapping

Can you explain the underlying reason for wanting to load balance across two indices with the same data but different mappings?

> different index on different availability zone but fee is pretty high

This is totally valid and I can see how your solution helps. However, it adds another layer of "replication" that searches have to deal with. Instead we have had discussions on allowing replicas/relocations to take most of the data from another node within the same AZ. For read-only indices this would be all data besides a couple of administrative requests to primary. This would make it possible to add more replicas instead without the additional cost of extensive inter-zone transfer. I did not find this as in issue in our repo, so feel free to open another issue for that specific use case of wanting to avoid shard movement across AZs.

**Comment by AyWa** [comment]
> Can you explain the underlying reason for wanting to load balance across two indices with the same data but different mappings?

Sometimes for the same data we have different mapping (one might have some complex analyzer and the other one a simpler one). So the `simpler` analyzer mapping can serve more request than the complex one -> so in this case the load balancing could be usefull inside `ES`

Or some other time we do experiment with same data but different mapping too (but in this case we might change the schema too -> so anyway we might need to load balance manually)

**I created this issue mainly because with our experiment for AZ fee, we run same index in different zones**
 
 > This is totally valid and I can see how your solution helps. However, it adds another layer of "replication" that searches have to deal with. Instead we have had discussions on allowing replicas/relocations to take most of the data from another node within the same AZ. For read-only indices this would be all data besides a couple of administrative requests to primary. This would make it possible to add more replicas instead without the additional cost of extensive inter-zone transfer. I did not find this as in issue in our repo, so feel free to open another issue for that specific use case of wanting to avoid shard movement across AZs.
 
 I got your point, thank you for the kind explanation. 
 I will check more that too. Maybe little related but for our readonly index, we also think sometimes that adding replica by downloading the latest snapshot will be better than shards movement in the cluster (thats also why we do some experiment right now, where we snapshot recovery in a different index -> but then we need to load balance between them)

**Comment by henningandersen** [comment]
@AyWa thanks for additional details.

> adding replica by downloading the latest snapshot

[Searchable snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/current/searchable-snapshots.html) can almost do this automatically for you. The only caveat for your specific use case it that the replica will be active during restore and this can cause searches hitting that copy to be slow (since it will then fetch data on-demand from S3). Adaptive replica selection should handle that relatively gracefully, but I would expect a few slow requests while it is restoring in your case (probably worth trying out to get a feel for that).

**Comment by pxsalehi** [comment]
Closing this since there haven't been any new updates on the issue, and we don't intend to make this change.
