### ISSUE TITLE
Randomize Rollup Index name when one is not provided to Rollup Action

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#68225]
**scenario**

Currently, there is a scenario in ILM where a `rollup` action can fail (on node failure) and restart. Upon restart it will find that the temporary index exists and fail again. This requires human intervention to come and delete that temporary index. To avoid this scenario, it would be ideal if ILM assigns a random index name to the rollup index under a datastream.

right now, `.ds-my-data-stream-2021.01.29-000001` would be `rollup-.ds-my-data-stream-2021.01.29-000001`

**solution** 

To remedy this failure scenario, it can be that the transport-rollup-action can randomly assign a new rollup index name to the rollup when one is not provided. This will enable the ILM Rollup action to not provide a target rollup index and a random one will be created and assigned to the datastream if one is associated with that index.

relates #65633.

**Comment by csoulios** [comment]
Fixed in #87269
