### ISSUE TITLE
SQL: binary type incorrectly filtered by IS (NOT) NULL

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#68229]
With the index defined in Binary type [documentation example](https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html#binary), the `IS [NOT] NULL` filtering works incorrectly: 
* `SELECT blob FROM my-index-000001 WHERE blob IS NULL` returns non-null values (_plus_ any `null` value present);
* `SELECT blob FROM my-index-000001 WHERE blob IS NOT NULL` returns nothing.

**Comment by bpintea** [comment]
The query translation for above queries works correctly, however the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html) states clearly that a [binary field] `is not stored by default and is not searchable` and that `doc_values` and `store` fields parameters are both `false` by default.
So `IS [NOT] NULL` is pretty much the only operation SQL could apply to a `binary` field.
Turning field's `doc_values` to `true` will have the query work as expected.

So I guess there would be the following options:
* close as "working as intended";
* the above plus a note (under limitations page) about `binary` type's defaults;
* have the Verifier check the `aggregatable == false` condition for a `binary` `EsField` in the `Filter`.

Thoughts, @elastic/es-ql?

**Comment by matriv** [comment]
I'm in favour of the `Verifier` check so that binary fields are not allowed in WHERE, as the only filter that could make sense doesn't actually provide any value (`IS NOT NULL` returns nothing/ `IS NULL returns non-null values (plus any null value present)`.

**Comment by costin** [comment]
What Marios said. I'm curious whether fields API impacts the detection in anyway as we won't be able to determine whether something has docvalues enabled or not...

**Comment by bpintea** [comment]
> however we do know if its searchable or aggregateable

Right, the field's reported as aggregateable if doc_values is set.

> What Marios said.

Great, will go that way then.
