### ISSUE TITLE
Runtime fields emit function doesn't work in lambda or functions

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#68235]
Runtime fields are defined by a painless script, like, say:
```
"corrected_voltage": {
  "type": "double",
  "script": """
    for (double v : doc['voltage'].values) {
      emit(v + .2);
   }
  """
```

At the moment the `emit` function that isn't available in lambdas or function. So you can't do this:
```
"corrected_voltage": {
  "type": "double",
  "script": """
    void correctVoltage(double v) {
      emit(v + .2);
    }
    for (double v : doc['voltage'].values) {
      correctVoltage(v);
   }
  """
```

Or this:
```
"corrected_voltage": {
  "type": "double",
  "script": """
    doc['voltage'].values.stream().forEach(v -> emit(v +.2));
  """
```

These are both unfortunate but, at the moment, not show stopper issues. At least, we don't think they are because we wrote a ton of runtime field examples before we encountered the limitation. We'd like to get t working anyway though. Folks like lambdas and method *are* useful.

**Comment by stu-elastic** [comment]
This was fixed by [e9800bd](https://github.com/elastic/elasticsearch/commit/e9800bdebb12abf00b96bc9515f27372f53bbd62)
