### ISSUE TITLE
Cross cluster search illegal_argument

### ISSUE THREAD

**Issue by kissliumin** [elastic/elasticsearch#68252]
My version is 7.9.3.When I search remotely across clusters, I set up a remote cluster and the result is illegal_ argument_ Exception, only when my name contains symbols, but when I build a cluster, the cluster name can contain symbols

```
PUT _ cluster/settings
{
	"persistent": {
		"cluster": {
			"remote": {
				"es-x.": {
					"seeds": [
						" xxxxx:9300 "
					]
				}
			}
		}
	}
}
```
The error message is:
     "reason" : "persistent setting [cluster.remote.es-x..seeds], not recognized"
I think if it is not supported here, the cluster name should also be consistent

**Comment by stu-elastic** [comment]
Hi @kissliumin can you provide a stack trace so we can narrow down where this is coming from?

**Comment by kissliumin** [comment]
> Hi @kissliumin can you provide a stack trace so we can narrow down where this is coming from?
Maybe I'm wrong, maybe it's something else
