### ISSUE TITLE
synonym plugin is install success,but it not enable for search

### ISSUE THREAD

**Issue by acclea** [elastic/elasticsearch#68268]
es 7.6.2
ik 7.6.2
synonym 7.6.2

when I use  _analyze, like this  
post  localhost:9200/_index_test/_analyze
{
  "analyzer": "ik_syno_smart",
  "text": "jingji"
}

result info
{
    "tokens": [
        {
            "token": "经济",
            "start_offset": 0,
            "end_offset": 6,
            "type": "SYNONYM",
            "position": 0
        }
    ]
}

synonym works.

when I search that word,  there is no match result,  

get localhost:9200/_index_test/_search
{
  "query": {
    "bool": {
        "filter":{"term":{"status":1}},
        "should": [
            { "multi_match": 
                {
                    "query":"经济",
                    "analyzer":"ik_syno_smart",
                    "type":"best_fields",
                    "fields":["article_title^999991", "article_kw^9999",  "article_des", "article_intro", "article_tag^9999", "article_cont"]
                }
            }
      ]
    }
  },
  "min_score":1,
  "size":2
}

result info
{
    "took": 20,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": null,
        "hits": []
    }
}

however standard analyzer can return .

**Comment by medcl** [comment]
@acclea seems this question is related to the customized analyzer, and here is not the right place to raise the issue, please ask in `http://discuss.elastic.co` in English or `http://elasticsearch.cn` in Chinese.

You are using the `_analyze` api to test the analysis result, that's great:

```
post localhost:9200/_index_test/_analyze
{
"analyzer": "ik_syno_smart",
"text": "jingji"
}
```

The `jingji` output `经济`, but you are searching `经济`, you should do a test with `经济` like this:
```
post localhost:9200/_index_test/_analyze
{
"analyzer": "ik_syno_smart",
"text": "经济"
}
```

you should also pick one of the query field value from document that should matched and do the same analysis test, the analysis results will tell you why it was not matched.

**Comment by acclea** [comment]
> @acclea seems this question is related to the customized analyzer, and here is not the right place to raise this kind of issue, you could ask in `http://discuss.elastic.co` in English or `http://elasticsearch.cn` in Chinese.
> 
> You are using the `_analyze` api to test the analysis result, that's great:
> 
> ```
> post localhost:9200/_index_test/_analyze
> {
> "analyzer": "ik_syno_smart",
> "text": "jingji"
> }
> ```
> 
> The `jingji` output `经济`, but you are searching `经济`, you should do a test with `经济` like this:
> 
> ```
> post localhost:9200/_index_test/_analyze
> {
> "analyzer": "ik_syno_smart",
> "text": "经济"
> }
> ```
> 
> you should also pick one of the query field value from document that should matched and do the same analysis test, the analysis results will tell you why it was not matched.

thanks your advise，
i ask  in http://elasticsearch.cn again, this url is [https://elasticsearch.cn/question/11254](https://elasticsearch.cn/question/11254)
thank you again.
