### ISSUE TITLE
batch insert lost data

### ISSUE THREAD

**Issue by Kvicii** [elastic/elasticsearch#68262]
I use python ElasticSearch client, ElasticSearch version is 6.7.0, use bulk API, when the update is complete, Some data is missing, ElasticSearch is UDP, what can I do to avoid data loss? We use ElasticSearch as data storage, shouldn't you do this?

**Comment by henningandersen** [comment]
@Kvicii, this sounds mostly like a question more than a bug report. At least for a bug report, would require much more information on frequency, reproducability and more. An upgrade to latest 7.10 version would be advisable, for instance to benefit from [the new cluster coordination layer](https://www.elastic.co/blog/a-new-era-for-cluster-coordination-in-elasticsearch).

I would like to direct you to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

If this should turn out to be a bug we would very much appreciate you returning here, providing a full bug report.
