### ISSUE TITLE
Config file placeholder for environment variables

### ISSUE THREAD

**Issue by KludgeKML** [elastic/elasticsearch#6828]
I spent a little time trying to get enviroment variables into placeholders in the configuration file as described here:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-configuration.html

..where is says that you should be able to include enviroment variables like this:

{
    "network" : {
        "host" : "${ES_NET_HOST}"
    }
}

..but I found a test in the repo that appears to reference the variable as part of "env", so that the example above would be:

{
    "network" : {
        "host" : "${env.ES_NET_HOST}"
    }
}

...and indeed that appears to work in my own application, but before I changed the documentation I wanted to double-check with someone who might understand the source code better than me that this is the intended behaviour.

**Comment by clintongormley** [comment]
Not sure when it changed, but the version without `env.` seems to work correctly. closing
