### ISSUE TITLE
Getting error {"error":"StackOverflowError[null]","status":500} while trying to backup

### ISSUE THREAD

**Issue by AnkitLogics** [elastic/elasticsearch#68347]
Elastic Version : 1.0.1
I have created a repo : 
```
curl -XPUT -H 'Content-Type: application/json' localhost:9200/_snapshot/my_backup -d'{
  "type": "fs",
  "settings": {
    "location": "/data/elastic_search_backup"
  }
}'
```

then when I run : 
```
curl -XPUT -H 'Content-Type: application/json' localhost:9200/_snapshot/my_backup/snapshot_1?wait_for_completion=true
```
I get below error : 
`{"error":"StackOverflowError[null]","status":500}`

Logs : 
`[2021-02-02 10:14:56,808][INFO ][snapshots                ]  snapshot [my_backup:snapshot_1] is done`

**Comment by original-brownbear** [comment]
Hi @AnkitLogics 

1.0.1 is long past it's end of life. We won't be making any more fixes to it and the snapshot functionality in supported versions of Elasticsearch works completely differently from 1.x so I hope you don't mind that I'm closing here.
I would recommend upgrading to a more recent and supported version of ES to address this.
