### ISSUE TITLE
elastic search is missing logs at specific regulars intervals

### ISSUE THREAD

**Issue by bilalmalik777** [elastic/elasticsearch#68427]
Elastic search is showing very strange behavior from yesterday, it was working perfectly, but now it was missing logs after every ten minutes. It was logging for 5 minutes then showed a gap for the next 10 minutes now it continuously missing the logs. Please help me to sort out this issue
![image](https://user-images.githubusercontent.com/23011613/106714715-2610e880-65f4-11eb-8685-54ce1e98676a.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
