### ISSUE TITLE
[Transform] add telemetry support for functions

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#68461]
Transform has now 2 functions: `latest` and `pivot`. It would be good to get usage reports in `_usage`, e.g. counts.

Implementation Detail: In order to able to do so, the mappings need to be updated.

**Comment by przemekwitek** [comment]
@hendrikmuhs: Do you remember where can I find the mappings for the usage index?

**Comment by dimitris-athanasiou** [comment]
@przemekwitek In this PR (https://github.com/elastic/telemetry/pull/520) you can see an example where I add usage mappings for DFA.
