### ISSUE TITLE
Change in the bundled openjdk causes certificate validation issues

### ISSUE THREAD

**Issue by frconil** [elastic/elasticsearch#68507]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10 and later

**Plugins installed**: []

**JVM version** (`java -version`): adoptopenjdk 15.0.1+9

**Description of the problem including expected versus actual behavior**:

Looking at the release notes, the [most recent version of adoptopenjdk (15.0.1)](https://www.oracle.com/java/technologies/javase/15-0-1-relnotes.html) has added stricter option when verifying certificates chains:

> A new system property, jdk.tls.maxHandshakeMessageSize, has been added to set the maximum allowed size for the handshake message in TLS/DTLS handshaking. The default value of the system property is 32768 (32 kilobytes).
> 
> A new system property, jdk.tls.maxCertificateChainLength, has been added to set the maximum allowed length of the certificate chain in TLS/DTLS handshaking. The default value of the system property is 10.

This can cause SSL issues which in turns cause unrelated errors with authentication, third party systems etc, for instance:

```
Authentication to realm oidc1 failed - Failed to authenticate user with OpenID Connect (Caused by ElasticsearchSecurityException[Failed to exchange code for Id Token using the Token Endpoint.]; nested: SSLProtocolException[The certificate chain length (11) exceeds the maximum allowed length (10)];)
```

This can be easily addressed with passing the new flag to `jvm.options` `-Djdk.tls.maxCertificateChainLength=xx`, but I believe we should document this in the release notes as this change behaviours between 7.9 and 7.10.

**Comment by lockewritesdocs** [comment]
@tvernum, is this an issue that persists beyond 7.10? Elasticsearch [7.12 and later](https://www.elastic.co/support/matrix#matrix_jvm) support OpenJDK16, so I'm curious if this issue is resolved in that version.
