### ISSUE TITLE
[Transform] Search runtime fields are not handled properly during mapping deduction.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#68516]
Since not available via `FieldCapabilities` API, transform search runtime fields are not "visible" to the mapping deduction code.
Therefore, the destination index is missing mappings for the aggregation fields based on search runtime fields.
This affects aggregations that copy the mapping type from source (`min`, `max`) but not the aggregations that use a fixed mapping type (`avg`).

**Comment by jimczi** [comment]
We are working on a solution for this, see https://github.com/elastic/elasticsearch/issues/68117. You shouldn't need to reimplement that logic, it's much simpler to just rely on field capabilities to do it for you.

**Comment by przemekwitek** [comment]
> We are working on a solution for this, see #68117. 

Thanks @jimczi . Sounds like that's exactly what we need. Is this enhancement targeted at `7.12` or later?

**Comment by przemekwitek** [comment]
FTR, the fix was implemented using the new `FieldCapabilitiesRequest.runtime_fields` feature mentioned by @jimczi above.
