### ISSUE TITLE
ElasticSearch Client: Wrapping of InterruptedException without restoring interrupted state of thread

### ISSUE THREAD

**Issue by stefanocke** [elastic/elasticsearch#68525]
**Elasticsearch version**: 7.6.2

Here, java.lang.InterruptedException is catched and wrapped without restoring the interrupt state (i.e. calling Thread.currentThread().interrupt()).

https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L842

```
private static Exception extractAndWrapCause(Exception exception) {
        if (exception instanceof InterruptedException) {
            throw new RuntimeException("thread waiting for the response was interrupted", exception);
        }
```

This is bad practice, since subsequent code might miss the fact that the thread is interrupted.

Similar issues have been submitted for other places before. See for example https://github.com/elastic/elasticsearch/issues/4712

**Comment by AlbusAndreus** [comment]
maybe try creating an instance boolean that is turned off when the exception is caught and the code that follows it can check if the boolean is true before executing certain code.

**Comment by stefanocke** [comment]
@AlbusAndreus , please see for example here for best practices:
https://www.ibm.com/developerworks/library/j-jtp05236/index.html

And there, especially the section "Don't swallow interrupts"
