### ISSUE TITLE
ILM should not rollover followed indices

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#68535]
Users can have the same ILM policies on the leader and follower clusters.  This causes CCR with auto-follow patterns to fail if the index is rolled over simultaneously on both clusters.

I think we should not rollover followed indices, or at least ILM should not do this.

**Comment by dakrone** [comment]
@dnhatn we already inject an unfollow action into policies that have a rollover action, is this different than what you are asking for?

**Comment by dnhatn** [comment]
Ah, thanks, Lee!
I am not sure if we can have the same ILM on both clusters. After unfollowed, the follower cluster can rollover to create a new index and it will fail to follow a new index that is rolled over on the leader cluster.

**Comment by dnhatn** [comment]
Closes in favor of https://github.com/elastic/elasticsearch/issues/69025
