### ISSUE TITLE
SQL: [Docs] Check and improve null/edge-case arg handling from functions

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#68531]
Seems that currently we don't have consistency in the SQL function documentation regarding the case of `null`s passed in as arguments. It would be nice to revisit the functions and have a common way of documenting this case and maybe other common behaviour for edge-case args. We can also consider stating the common behaviour for a group of functions (e.g. String functions) at a central place to avoid repeating it on each one of them.

**Comment by jrodewig** [comment]
Closed by #74193.
