### ISSUE TITLE
Removal of mapping types in 7.x: why not include index aliases in results?

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#68549]
I've described my question in detail [here](https://discuss.elastic.co/t/removal-of-mapping-types-in-7-x-why-not-include-index-aliases-in-results/263293).

Since there's only one "type" of document in all our indexes (since the 1.x days even), I'm looking for the abstraction that would be afforded me if the alias was included in the search results alongside the physical index name we receive today.  If this was part of ES 8.x, we could transition our code at that time.

**Comment by markharwood** [comment]
Thanks for the question
> I'm looking for the abstraction that would be afforded me if the alias was included in the search results alongside the 
physical index name

The simple answer is that an index can be referenced by multiple aliases. It's a one-way translation from query request to physical indices - there's no attempt to translate a match on a physical index back to the alias(es) that led searches to that doc.

**Comment by tdoman** [comment]
@markharwood Thanks for the response.  I should have mentioned that I realize there could be multiple aliases.  We use multiples for our log scenarios (ie. "read" on all plus "write" on the hot index).  I'd be happy to get them all ... even via a request flag so that it's optional.
At any rate, it sounds like there's nothing I can't count on programmatically that won't be "by convention".
Conventions:
1. Make sure all my documents have a "type" field (I've been looking to see if I can specify a field as "required" in a mapping but I don't see a way to do that).
2. Make sure all my physical index names follow a convention that includes the type name (we already do that but, again, I don't like programming by convention for obvious reasons).
Any other options?
re: #1 - any way to specify a field as "required" in a mapping?

**Comment by markharwood** [comment]
There's a [constant keyword](https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html#constant-keyword-field-type) field now you can define as part of mappings which defines a fixed implicit value for every doc in an index. You could use it to define a type e.g. "person" and can query and aggregate on it - but it doesn't look like it comes back in the source of documents returned in hits.
This again is a form of convention (there are no types now). You'd probably have to maintain a map of index-name to associated constant-keyword field (or perhaps metadata held in the mapping). If I recall correctly metadata was added to mapping specifically to help  c# bindings provide document deserialization (again, based on a convention).
The only formal kind of doc typing that we are pursuing is [datastreams](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/data-streams.html) which provides the idea of a schema type that spans multiple time-based indices.

Given these options I don't think we'll be thinking about adding aliases to results so will close this issue if you don't mind.
Thanks for raising.

**Comment by tdoman** [comment]
@markharwood Yeah, the constant keyword would work perfectly for our purposes if it was actually returned in the hits.  Do you know where I can find documentation on the mapping metadata to help C# bindings?  TBH, I wouldn't expect this to be a C# specific problem to have to tie hits to a deserialization model in code.  If you don't, I can add a reference to this convo on the .NET project repo.
Yes, feel free to close, I assume that wouldn't prevent you from getting notified if the convo continues hereafter.

**Comment by jtibshirani** [comment]
@tdoman some additional notes that may be helpful:
* In 7.10 we introduced the `fields` search request option, which lets you retrieve field values that may not be present in _source. So if you ended up going with `constant_keyword`, you could use specify `"fields": ["my_type"]` to get the values back. If you are not on 7.10, a workaround is to use `"docvalue_fields": ["my_type"]`.
* We've discussed adding the ability to mark a field as 'required': https://github.com/elastic/elasticsearch/issues/58523. We were not sure if it would be broadly useful, it'd be great to get your feedback on that issue.
