### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT {p0=delete/51_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately"}

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#68562]
MixedClusterClientYamlTestSuiteIT {p0=delete/51_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately"}

**Build scan**: https://gradle-enterprise.elastic.co/s/tku35txu2dr7w

**Repro line**: 
```./gradlew ':qa:mixed-cluster:v6.8.14#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=delete/51_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately"}" -Dtests.seed=E54AB63F4C0F734 -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=MST7MDT -Druntime.java=8```

**Reproduces locally?**: No

**Applicable branches**: 7.10

**Failure history**: Fails once or twice per month for the past ~6 months

**Failure excerpt**:
```
java.lang.AssertionError: Failure at [delete/51_refresh_with_types:113]: hits.total didn't match expected value: 
  hits.total: expected Integer [0] but was Integer [1] |  

at __randomizedtesting.SeedInfo.seed([E54AB63F4C0F734:860094B95A3C9ACC]:0) 
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:414) 
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:391)
```

**Comment by mayya-sharipova** [comment]
I could not get history of failure for this test from gradle-enterprise as it always time-outs.
But [searching for this failure from build@elastic.co ](https://groups.google.com/a/elastic.co/g/build-elasticsearch/search?q=51_refresh_with_types&sortBy=DATE), looks like we had 2 failures this year, and none from the previous year (none test failure specifically about this test).

error_log:

[2021-02-04T13:31:25,839][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=delete/51_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately"] before test
  2> Feb 04, 2021 1:31:27 PM org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [PUT http://127.0.0.1:42983/test_1/test/1?refresh=true&error_trace=true] returned 1 warnings: [299 Elasticsearch-6.8.14-SNAPSHOT-dab5822 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template"]


cc:  Distributed team as the test is about refresh.
