### ISSUE TITLE
7.10 no longer accepts enabled on dynamic mapping template

### ISSUE THREAD

**Issue by raffis** [elastic/elasticsearch#68576]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.10.2, Build: default/docker/747e1cc71def077253878a59143c1f785afa92b9/2021-01-13T00:42:12.435326Z, JVM: 15.0.1

**OS version** (`uname -a` if on a Unix-like system):
Linux elasticsearch-es-data-3 5.4.0-1025-aws #25-Ubuntu SMP Fri Sep 11 09:37:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Having a dynamic template (legacy template) with certain fields to disable dynamic mapping does not work anymore and ends in: `unknown parameter [enabled] on mapper [xxx]`.

This was working before in 7.8.x.

This sounds related to:
* https://github.com/elastic/elasticsearch/issues/64982
* https://github.com/elastic/elasticsearch/issues/66765

**Steps to reproduce**:

index template:
```json
[
  {
    "default_no_index": {
      "match_pattern": "regex",
      "path_match": "^.*$",
      "path_unmatch": "^(@timestamp|auditID|level|stage|requestURI|sourceIPs|metadata|objectRef|user|verb)(\\..+)?$",
      "mapping": {
        "index": false,
        "enabled": "false"
      }
    }
  }
]
```

First document to a new index applied ends in:
```json
{"took":13,"errors":true,"items":[{"index":{"_index":"k8saudit-2021.02.04","_type":"_doc","_id":"hxzGbHcB1FB4PL8e-t_M","status":400,"error":{"type":"mapper_parsing_exception","reason":"unknown parameter [enabled] on mapper [kind] of type [null]"}}},{"index":{"_index":"k8saudit-2021.02.04","_type":"_doc","_id":"iBzGbHcB1FB4PL8e-t_M","status":400,"error":{"type":"mapper_parsing_exception","reason":"unknown parameter [enabled] on mapper [kind] of type [null]"}}}
```

**Comment by romseygeek** [comment]
Hi @raffis, thanks for opening this bug report!  This is indeed the same bug as #64982 and has been fixed by #67763.  The fix should be in the upcoming 7.11 release.
