### ISSUE TITLE
positive_score_impact does not work with rank_features field

### ISSUE THREAD

**Issue by KylePiira** [elastic/elasticsearch#68619]
So the `rank_feature` field has a `positive_score_impact` parameter to make it have a negative correlation with the score. However, this parameter does not work on `rank_features` fields.
When I try it, I get the following error: `unknown parameter [positive_score_impact] on mapper [rank_features] of type [rank_features]`

**Comment by mayya-sharipova** [comment]
@KylePiira  Thank you for submitting the issue. We can add `positive_score_impact` parameter to rank_features type as well, but if used it will be applied to all sub-features of this `rank_features`.

Will this address your use case?

**Comment by KylePiira** [comment]
Hi @mayya-sharipova, yes that would address my use case. I'm using `rank_features` where the key is a user ID and the value is a rating that a user has given to a particular document. When a user performs a search I want to boost documents that they have rated highly in the results (currently possible with `rank_feature`). However, users can also give negative ratings to documents and I would like to negatively boost those in the results.
So for a given document you might have:
```
{
	"title": "...",
	"body": "...",
	"positive_ratings": {
		"1": 5,
		"3": 2,
		"7": 3
	},
	"negative_ratings": {
		"6": 4,
		"2": 8
	}
}
```

Where `positive_ratings` is a `rank_features` with `positive_score_impact=true` and `negative_ratings` is a `rank_features` with `positive_score_impact=false`. Users 1, 3, and 7 have rated the document with scores of 5, 2, and 3 respectively. Users 6 and 2 have rated the document with scores of -4 and -8 respectively.

**Comment by mayya-sharipova** [comment]
@KylePiira  Thanks for sharing your use case; it was very useful. I was also thinking along the same lines.
