### ISSUE TITLE
Intermittent exception using high-level-rest-client. [Unable to load a DateTransformer]

### ISSUE THREAD

**Issue by srikaratstrings** [elastic/elasticsearch#68617]
**Elasticsearch version** (`bin/elasticsearch --version`):7.9.2

**Plugins installed**: []
None

**JVM version** (`java -version`): 
openjdk 15 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

Java on the client:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-2, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux elasticsearch-master-0 4.14.198-152.320.amzn2.x86_64 #1 SMP Wed Sep 23 23:57:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

uname -a on the client
Linux api-server-7b4b9d64f6-5sg5t 4.14.198-152.320.amzn2.x86_64 #1 SMP Wed Sep 23 23:57:28 UTC 2020 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
 We are using elastic search on Kubernetes on AWS [EKS].
  Elastic Search Version: 7.9.2
  Client: Java: elasticsearch-rest-high-level-client [Version 7.9.2]

We notice the following exception sporadically. I spent considerable time debugging this with David Turner. Please refer to the below thread for details. 
https://discuss.elastic.co/t/intermittent-exception-using-high-level-rest-client-unable-to-load-a-datetransformer/262375/4
The short summary of the issue is that the client cannot find a DateTransformer while trying to construct a query. I read through the code and found the class that contains the DateTransformer. I caught the exception and tried to check if the class that provides the DateTransformer is loaded. It looks like the class was available. I am unable to explain why this happens. 

java.lang.IllegalArgumentException: cannot write time value xcontent for unknown value of type class java.util.Date
at org.elasticsearch.common.xcontent.XContentBuilder.timeValue(XContentBuilder.java:751)
at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:815)
at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:804)
at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:789)
at org.elasticsearch.index.query.RangeQueryBuilder.doXContent(RangeQueryBuilder.java:322)
at org.elasticsearch.index.query.AbstractQueryBuilder.toXContent(AbstractQueryBuilder.java:87)
at org.elasticsearch.index.query.BoolQueryBuilder.doXArrayContent(BoolQueryBuilder.java:274)
at org.elasticsearch.index.query.BoolQueryBuilder.doXContent(BoolQueryBuilder.java:255)
at org.elasticsearch.index.query.AbstractQueryBuilder.toXContent(AbstractQueryBuilder.java:87)
at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:857)
at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:850)
at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:842)
at org.elasticsearch.search.builder.SearchSourceBuilder.innerToXContent(SearchSourceBuilder.java:1224)
at org.elasticsearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:1355)
at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:367)
at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:768)
at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:763)
at org.elasticsearch.client.RequestConverters.search(RequestConverters.java:417)
at org.elasticsearch.client.RestHighLevelClient.lambda$search$2(RestHighLevelClient.java:1071)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1609)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553)
at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. It is sporadic. Cannot be reproduced on demand.
 
**Provide logs (if relevant)**:

**Comment by srikaratstrings** [comment]
Is there anything I can do to raise the priority on this one?

**Comment by lbenedetto** [comment]
Why did you close the issue? Did you figure out how to fix it, or find a workaround?

I'm having the same issue, though it appears to happen 100% of the time instead of intermittently like for you

**Comment by srikaratstrings** [comment]
Hello Lars, 
 I closed the issue because I felt that I could not get a resolution here in a meaningful time frame. We spent a lot of time in digging deeper and have some insights. While, the issue hasn't resurfaced since for us, I am not convinced that this is a fix. Happy to help offline because the explanation is a bit involved. Please reach out at srikar@trywingman.com.

**Comment by lbenedetto** [comment]
I have resolved this issue for myself by calling this method during elasticsearch Bean creation
> JsonXContent.contentBuilder();

This triggers the static initialization block in XContentBuilders to run, filling the Writers map at a consistent time rather than during first query.

**Comment by raftonsea** [comment]
It seems a little late  , but I think its worth to  share my  experience .   I meet the same problems . In my scenario , I   use RestHighLevelClient to count a number within an  CompletableFuture , eg:



```
          CompletableFuture cf = CompletableFuture.supplyAsync(() -> {
            try {
                CountRequest countRequest = new CountRequest(index);
                countRequest.source(sourceBuilder);
                CountResponse count = client.count(countRequest, RequestOptions.DEFAULT);
                return count;
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
```


I am develop  a web application with springboot . I run the project with main method on development stage  , eventually deploy it in Tomcat8.5  on the production environment  in form of a  xx.war   . It's normal on develop stage . But  the problem occur  when I try to  deploy  the war in Tomcat    . 
" cannot write time value xcontent for unknown value of type class java.util.Date "  

I reflect the source code  and found that   elasticsearch  will try to find the  time-value-transformer to transfer our time value  when we do a time-based  query  .  Elasticsearch will find the corresponded transformer  from a static map :  org.elasticsearch.common.xcontent.XContentBuilder#DATE_TRANSFORMERS    by the Class type of the value  (in this case that is  java.util.Date ) , the map is initiated in a static block  with SPI . 
The exception indicated that  the  java.util.Date is not inclued in the static Map .   


      
```
       dateTransformers.put(String.class, Function.identity());
        for (XContentBuilderExtension service : ServiceLoader.load(XContentBuilderExtension.class)) {
            ........  omit other
            dateTransformers.putAll(addlDateTransformers);
        }

        DATE_TRANSFORMERS = Collections.unmodifiableMap(dateTransformers);
```



From the source code above . Elasticsearch   try to load  XContentBuilderExtension's   implementations with  SPI  , when successed , the implementation is added to DATE_TRANSFORMERS  .  So the question became :  Why the XContentBuilderExtension's ()  implementation is empty ?  
As we know , ServiceLoader will try to load the class with  current-thread's contextClassLoader ,   if the target implementation is not exist in the thread-ContextClassLoader's  classpath it will return null .   By default a thread's thread-ContextClassLoader is parent-thread's thread-ContextClassLoader , but  we can change it  with  Thread.setContextClassLoader()  . 

 My count() is executed in  CompletableFuture   whose  thread-executor-pool is  ForkJoinPool.commonPool()   .    I print the  thread's contextClassLoader in  CompletableFuture    . 


```
CompletableFuture cf = CompletableFuture.supplyAsync(() -> {
           System.err.println(Thread.currentThread().getContextClassLoader());
           return 1;
        });
```

        
        

The result is null .  Null-classLoader  stand for bootstrap-classloader  and It will load class from rt.jar  so the "XContentBuilderExtension" implementation is null . 
I read the ForkJoinPool's source code  found that  it will  init the ThreadFactory   with   System.getProperty("java.util.concurrent.ForkJoinPool.common.threadFactory")  . **By default  the value is null  , but  tomcat  override it :** 
 

```
org.apache.catalina.core.JreMemoryLeakPreventionListener : 
 
if (forkJoinCommonPoolProtection && !JreCompat.isJre9Available()) {
    // Don't override any explicitly set property
    if (System.getProperty(FORK_JOIN_POOL_THREAD_FACTORY_PROPERTY) == null) {
        System.setProperty(FORK_JOIN_POOL_THREAD_FACTORY_PROPERTY,
                SafeForkJoinWorkerThreadFactory.class.getName());
    }
}

org.apache.catalina.startup.SafeForkJoinWorkerThreadFactory:
private static class SafeForkJoinWorkerThread extends ForkJoinWorkerThread {

    protected SafeForkJoinWorkerThread(ForkJoinPool pool) {
        super(pool);
        setContextClassLoader(ForkJoinPool.class.getClassLoader()); 
    }
}
```


 
   **To avoid memory leak , tomcat  clear the current-thread's  context-classloader .  ForkJoinPool is loaded by bootstrapclassloader , so the ForkJoinThread's context-classloader is null . So if we invoke  XContentBuilderExtension in the default CompletableFuture  in tomcat ,   it will be loaded by bootstapclassloader  ,  the exception will occur.** 

How to  overcome the exception ?  
1 . Defind a  threadpoolExecutor ,  pass to CompletableFuture. 
2 . Invoke org.elasticsearch.common.xcontent.XContentBuilder#DATE_TRANSFORMERS  within  AppClassLoader   like @lbenedetto    .
```
static {
    try {
            JsonXContent.contentBuilder();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```
