### ISSUE TITLE
EQL: Introduce dedicated keywords (like & regex) for pattern matching

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#68639]
A common case in EQL is performing different type of pattern matching against an expression.
Two types of patterns are targeted:

* `like` for wildcard/`*?` pattern
This recognizes `?` and `*` patterns
* `regex` for full regular expressions
Supports the full Lucene/Elasticsearch [regex suite](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html) (similar but different from PCRE).

#### Wildcard

```
field like "pattern*"				// basic matching
field like~ "P?tTeRn*"				// case-insensitive
field like ("a*", "b?", "c*d" )		// multi argument
field like~ ("A*", "B?", "C*d")		// case-insensitive multi argument
```

#### Regex

```
field regex "[a-z]"					// basic form
field regex~ "[A-z]"				// case-insensitive
field regex ("[aA]a", "[Bb]b")		// multi argument 
field regex~ ("aA", "bB")			// case-insensitive multi argument
```

**Comment by rw-access** [comment]
`regex` or `matches`?
