### ISSUE TITLE
When will indices be closed?

### ISSUE THREAD

**Issue by fm0803** [elastic/elasticsearch#68632]
I have a es 6.3 cluster, one day some indices turned close. But I did not do this manually.
How did this happen?

**Comment by tvernum** [comment]
Hi @fm0803, thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
