### ISSUE TITLE
Data Visualizer removing last line of csv on import

### ISSUE THREAD

**Issue by kofi-grid** [elastic/elasticsearch#68717]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Description of the problem including expected versus actual behavior**:

The Import data functionality doesn't import the last line of a csv.

**Steps to reproduce**:
Create csv in google sheets or excel with 3 rows like this:

id | location | worker_ip
-- | -- | --
test1 | OH | 192.168.0.0
test2 | NV | 192.168.0.1

Import with Data Visualizer

Drag and drop csv into the Kibana window

Click import (yes, the visualizer shows the 2 lines but it won't import them) and create the index

Go into discover/dev tools and you won't see the last entry on the csv, only the first one. I would expect to see both.

**Comment by dakrone** [comment]
Hi @kofi-grid, this repository is for the underlying Elasticsearch server, I believe you need to open this issue in the Kibana repository: https://github.com/elastic/kibana/

**Comment by kofi-grid** [comment]
Ok, I duped there. Thanks.
