### ISSUE TITLE
Limited scope of the synonyms section in simple_query_string docs

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#68720]
The [Synonyms](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-simple-query-string-query.html#simple-query-string-synonyms) section of the `simple_query_string` query has a somewhat limited scope. It indicates that we only generate phrase queries by default for multi word synonyms, while in reality it seems to work for all token graphs including token graphs generated as a result of decompounding. I think we should expand this section and perhaps rename `auto_generate_synonyms_phrase_query` into something more generic like `auto_generate_multi_position_token_phrase_query` or something like this to highlight the fact that it is applicable beyond just synonyms. 

Here is another example with `word_delimiter_graph`:
```
DELETE test

PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "keyword",
          "filter": [ "my_filter" ]
        }
      },
      "filter": {
        "my_filter": {
          "type": "word_delimiter_graph",
          "preserve_original": true
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "my_analyzer"
      }
    }
  }
}

### Generates phrase search
GET test/_validate/query?explain=true
{
  "query": {
    "simple_query_string": {
      "query": "wi-fi",
      "fields": ["text"]
    }
  }
}

### Generates AND search
GET test/_validate/query?explain=true
{
  "query": {
    "simple_query_string": {
      "query": "wi-fi",
      "fields": ["text"],
      "auto_generate_synonyms_phrase_query" : false
    }
  }
}
```

**Comment by jrodewig** [comment]
I opened #68753 to address the docs portion of these changes. However, I'll leave this issue open to address the name of the 
`auto_generate_synonyms_phrase_query` parameter.

**Comment by javanna** [comment]
We have no plans on further working on this issue. Closing.
