### ISSUE TITLE
Prevent md5 from being used for cache hashing when in FIPS mode

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#68743]
SP 800-52 approves that MD5 can be used with TLS and it is the only scenario where it is allowed. However, the BCFIPS library (and maybe other libraries) does not prevent it from being used in other places (there really is no reliable way to detect it). In our case, user can choose to use it as the caching algorithm. The usage includes [CachingUsernamePasswordRealm](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java), [ApiKeyService](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ApiKeyService.java) and maybe some other places. It also can be used in the [fingerprint ingest processor](https://github.com/elastic/elasticsearch/pull/68415). We should fix them by either throwing error or fail to start.

In all the aforementioned places we should be checking the value of `XPackSettings.FIPS_MODE_ENABLED` in the current loaded settings ( i.e. by checking `Environment#settings` ) and throw an exception that would cause the component and the node to exit or print a warning in the logs if we want to be more tolerant.

**Comment by n1v0lg** [comment]
As discussed on slack, [FingerprintProcessor](https://github.com/elastic/elasticsearch/blob/master/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/FingerprintProcessor.java) does not use the hash function in a security context, i.e., does not require a cryptographically secure hash function. Instead the hash function is used for content fingerprinting. As such this is outside of scope for FIPS and it does not make sense to include a warning here.
