### ISSUE TITLE
[Index Mappings] Provide Prune API

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#68759]
Index Mappings are a common problem for for new and experienced users of Elasticsearch alike, with the most common problem being the existence of an enormous number of accidentally mapped fields -- both those with backing data (usually from unexpected dynamic mappings) and from predefined templates.

While discussing how to "fix" a problematic cluster they had many indexes with over 6,000 fields defined per index, it occurred to me that just as we can easily add fields, perhaps we can a little-less-easily remove fields (especially unused ones). This could then be used to create non-dynamic mapping templates once an index is "locked in". Particularly setup alongside runtime fields, this would be a powerful new feature.

The downside to such an API is that the next document indexed could reverse the mappings change, but that's true of most things. Being able to remove thousands of fields with a single command without reindexing, if possible, would be tremendously helpful.

In practice, the solution is to reindex such problematic indexes, but that requires knowledge of what fields are actually used in the aggressively unused cases. Obviously there is not much we can do about fields, whether they're sparse or not, that the user does not actually care about but mapped anyway.

-----

I was thinking that there could be two modes of such an API: analyze and remove.

```http
GET /{my-index}/_prune_mapping
```

This would give information about the index's unused fields (if any). In other words, it would figure out what fields simply had no data and let the user know.

```http
POST /{my-index}/_prune_mapping
{
  "fields": ["blah*", "my.field.keyword"],
  "include_unused": true
}
```

This would be the same as above, but it would inform you about the fields that you selected rather than trying to find fields to remove for you. `include_unused` (or something similar) would allow the user to get the body-less `GET` behavior as well.

```http
DELETE /{my-index}/_prune_mapping
{
  "fields": ["blah*", "my.field.keyword"],
  "include_unused": true
}
```

Finally, remove the fields. This would delete any relevant data structures as well.

**Comment by mayya-sharipova** [comment]
We had a team discussion, and jointly decided that we will not implement this API for the following reasons:

- We consider mappings to be not removable, and implementing removing them will require a lot of refactoring.
- 6000 fields doesn't look to be that many fields.
- New runtime fields provide an option to introduce new fields, experiment with them, and then remove them from mapping.
- We are also discussing an option to combine same mappings of different indices for a decreased cluster state size.

**Comment by pickypg** [comment]
I just want to note:

> 6000 fields doesn't look to be that many fields.

I agree for a standalone index that this isn't so bad. But when you have hundreds of these indexes, it's pretty bad. Combining it with:

> We are also discussing an option to combine same mappings of different indices for a decreased cluster state size.

Should be a _huge_ benefit.
