### ISSUE TITLE
Painless script error should contain name and type of script that failed. 

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#68750]
Currently, painless script errors provide a good amount of info about the cause of the failure but notably lacking is a reference to how the script was provided. I'm working on providing better error messages to kibana users and its ambiguous to me as to whether the failed painless script is a runtime field or a scripted field nor do I know its name. Supplying these would help me direct the user to the place in the UI where they can fix the failed script.

My kibana PR for improved error messages - https://github.com/elastic/kibana/pull/90698

**Comment by stu-elastic** [comment]
closing in favor of #73492
