### ISSUE TITLE
Remove all OSS distribution references from Elasticsearch build

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#68797]
As part of the licensing move for Elasticsearch we will no longer publish a separate "oss" distribution the current "default" distribution will now be the only one that exists. Starting with 7.11 the "oss" distribution artifacts are no longer published but the build can still generate such an artifact and there are some internal dependencies on that distribution. We want to ditch all of this which means:

- [x] Remove all the "oss" variants under `:distribution`. This means the build will no longer produce a separate "oss" artifact.
- [x] Update any project that test against this distro (right now this is all the stuff under `:qa`).
- [x] No more `tests.distribution` system property.
- [x] The "default distro" builds can go away since everything will now use the default distro. This means the periodic build, pull request build and docs pr builds.
- [x] Any and all "oss" specific tests can go, which is mainly going to be changes to the packaging tests.
- [x] Remove oss specific windows packaging ci jobs

**Comment by mark-vieira** [comment]
@breskeby anything left to do here?

**Comment by breskeby** [comment]
I think https://github.com/elastic/elasticsearch/pull/70132 is the only thing left here

**Comment by mark-vieira** [comment]
Looks like we're all done here then @breskeby?

**Comment by breskeby** [comment]
I tick this off once I manage to merge https://github.com/elastic/elasticsearch/pull/70134 into master. It hasn't passed the windows tests yet due to that https://github.com/elastic/infra/issues/27453 issue

**Comment by mark-vieira** [comment]
Awesome. Thanks Rene.

**Comment by breskeby** [comment]
https://github.com/elastic/elasticsearch/pull/70134 has been merged into master. therefore I call this done
