### ISSUE TITLE
Http TLS encryption should give options for having two ports .one for https and one for nontls.

### ISSUE THREAD

**Issue by sangeethdba** [elastic/elasticsearch#68836]

**Comment by jkakavas** [comment]
Hi @sangeethdba, thank you for your feedback! I'm closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/35095 which was in turn closed to be tracked as part of [this meta-issue](https://github.com/elastic/elasticsearch/issues/39531) . You can keep track of the latter for any updates

**Comment by sangeethdba** [comment]
My request is for HTPP encryption(client to node) .the issue you are pointing is more on transport layer (internode communication).@jkakavas

**Comment by jkakavas** [comment]
The meta issue I pointed to has a sub-item that says 

> Should we accept http connections

which means that we'd consider this for the HTTP layer also. Does this cover your request sufficiently @sangeethdba ?
