### ISSUE TITLE
Can't install 7.11.0 on Windows 2019

### ISSUE THREAD

**Issue by plancked** [elastic/elasticsearch#68876]
Hi,

I'm trying to install ElasticSearch on Windows Server 2019.
At first i tried to a VM, and installation failed. Then I tried to a dedicated server, but it failed again.

The "Starting Elasticsearch service..." step takes some time, and then i get the following screenshot.

<img width="899" alt="Screenshot 2021-02-11 at 01 44 57" src="https://user-images.githubusercontent.com/15898593/107588708-08074180-6c0d-11eb-9c7b-1b0a945edd72.png">

[ES-error-installation.txt](https://github.com/elastic/elasticsearch/files/5962399/ES-error-installation.txt)

I've attached the log file.

Thanks
Alex

**Comment by plancked** [comment]
I'm seeing this on Event Viewer


Service cannot be started. Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file. result: Exception in thread "main" java.lang.IllegalArgumentException: Expected two arguments specifying path to ES_PATH_CONF and plugins directory, but was [C:\ProgramData\Elastic\Elasticsearch\config] at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:72) at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess.CreateObservableProcessArguments(IEnumerable`1 args) at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(IObservableProcess process, IConsoleOutHandler consoleOutHandler, IFileSystem fileSystem, ElasticsearchEnvironmentConfiguration env, JavaConfiguration java, IElasticsearchTool jvmOptionsParser, IElasticsearchTool javaVersionChecker, ManualResetEvent completedHandle, IEnumerable`1 args) at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(ManualResetEvent completedHandle, IEnumerable`1 args) at Elastic.ProcessHost...

**Comment by plancked** [comment]
anyone? :(

**Comment by gorenerburak** [comment]
I face similar issue, the installation was failed when selected start the elastic service on configuration menu. Afterthat i unclik these options and reinstall it. The installation is successfuly end but service cannot be started on windows services. Afterwards, I try to run elasticsearch.exe manually on the console and faced below issue details. 

Could not evaluate jvm.options file. result: Exception in thread "main" java.lang.IllegalArgumentException: Expected two arguments specifying path to ES_PATH_CONF and plugins directory, but was [C:\Elastic\conf]
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:72)

OS: Window 10.

I think that is a configution issue but i couldn't find a workaround solution yet.

**Comment by orlandotereza** [comment]
The same here for Windows Server 2012

**Comment by danielmitterdorfer** [comment]
Thanks for reporting this! This is an issue with Elasticsearch's Windows installer itself and has also been reported in https://github.com/elastic/elasticsearch/issues/68914 and https://github.com/elastic/windows-installers/issues/401 and fixed in https://github.com/elastic/windows-installers/commit/f53ace7477792ab4d833cf9740501e38e580b410 which will be included in the next patch release. Therefore I'm closing this one as a duplicate.
