### ISSUE TITLE
Can't start elasticsearch

### ISSUE THREAD

**Issue by trpx** [elastic/elasticsearch#68874]
tools/launchers/JvmOptionsParser.java /

```
     * @param args the args to the program which should consist of a single option, the path to ES_PATH_CONF
     */
    public static void main(final String[] args) throws InterruptedException, IOException {
        if (args.length != 2) {
            throw new IllegalArgumentException(
```

the comment clearly contradicts the code, and this exception is what I get when attempting to start elasticsearch

**Comment by williamrandolph** [comment]
@trpx While I agree that the comment needs to be updated for correctness, our startup scripts should still be calling this class with the correct number of arguments. If there is a bug here, I think we will need more information to find it.

What version of Elasticsearch are you using?

What command are you using to start Elasticsearch?

Can you post the full output from the failed startup?

**Comment by pugnascotia** [comment]
If you're using the MSI installer for v7.11.0, see https://github.com/elastic/windows-installers/issues/402 - this will be fixed in v7.11.1.

Otherwise, please provide more information so that we can replicate your issue.

**Comment by lyssom** [comment]
find a dashen

**Comment by williamrandolph** [comment]
Without more information, there is no way to replicate this issue, so I'm going to close it. I will, however, update the javadoc comment.
