### ISSUE TITLE
Breaking change of default of `max_number_of_snapshots` in v8

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#68886]
In #64461 we introduced the ability to set a limit on the number of snapshots in a repo, but in the backport to 7.11 we set the limit to `Integer.MAX_VALUE` to avoid introducing a breaking change in this minor release. However, the limit reduces to `500` in 8.0 which now represents a future breaking change. Today this change gets no mention in the 8.0 breaking changes docs, nor a deprecation warning in 7.x to help users prepare for it.

For changes to parameter defaults we'd usually require users to set the parameter explicitly to avoid the deprecation warning. I'm not sure that works in this case, if we say "you must set `max_number_of_snapshots`" then users will explicitly set it too high to work around their current snapshot hygiene problems, rather than dealing with the root cause.

**Comment by repantis** [comment]
Removing the blocker label, per @DaveCTurner's suggestion, since 8.0.0 shipped without this fix, but still tracking this as a bug.

**Comment by Leaf-Lin** [comment]
As of https://github.com/elastic/elasticsearch/issues/74350, @original-brownbear has improved the `max_numbef_of_snapshots` in v8.  There was a [doc PR on the removal of the soft limit](https://github.com/elastic/elasticsearch/pull/80745/files).  

What's still needed to be done on this issue?

**Comment by original-brownbear** [comment]
I don't think there's anything left to be done here, we went for no limit now and improved scalability instead.
