### ISSUE TITLE
Join Field Type Behavior Change from 7.10.2 to 7.11.0 - Indexing Document Fails

### ISSUE THREAD

**Issue by SpencerLN** [elastic/elasticsearch#68935]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.11.0 - Using the official Docker image
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk 15.0.1 2020-10-20
**OS version** (`uname -a` if on a Unix-like system):
Linux 4.19.112+ #1 SMP Sat Oct 10 13:45:37 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:
Creating a document in Elasticsearch 7.11.0 is failing with the same mappings as was working in 7.10.2. I was unable to identify anything in the release notes or breaking changes that would cause this issue.

**Steps to reproduce**:

 1.
```
PUT hive_test
{
  "mappings": {
    "properties": {
      "relations": {
        "type": "join",
        "eager_global_ordinals": true,
        "relations": {
          "dblist": [],
          "data": [],
          "caseTemplate": [],
          "case_task": "case_task_log",
          "reportTemplate": [],
          "sequence": [],
          "alert": [],
          "audit": [],
          "case_artifact": "case_artifact_job",
          "action": [],
          "user": [],
          "dashboard": [],
          "case": [
            "case_artifact",
            "case_task"
          ]
        }
      }
    }
  }
}
```
 2.
```
PUT hive_test/_doc/2
{
  "test_id": 2,
  "relations": "alert"
}
```

**Provide logs (if relevant)**:

The result on 7.11.0:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "unknown join name [alert] for field [relations]"
    }
  },
  "status" : 400
}
```

The result on 7.10.2:
```
{
  "_index" : "hive_test",
  "_type" : "_doc",
  "_id" : "2",
  "_version" : 2,
  "result" : "updated",
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "_seq_no" : 1,
  "_primary_term" : 1
}

```

**Comment by romseygeek** [comment]
I think this is an empty child list being confused with a non-existent child list, so what was previously ignored is now causing an error.  Just out of interest, what are you expecting the empty child lists to actually do?

**Comment by SpencerLN** [comment]
> I think this is an empty child list being confused with a non-existent child list, so what was previously ignored is now causing an error. Just out of interest, what are you expecting the empty child lists to actually do?

I am not sure if the empty child list actually does anything useful, and suspect that it may not. We are using a third-party application, [The Hive](https://github.com/TheHive-Project/TheHive/tree/3.5.0), that creates the mappings this way. We upgraded the Elasticsearch cluster that serves as the backend for the application and noticed this change in behavior that prevented the application from working as expected.

**Comment by SpencerLN** [comment]
No longer relevant.
