### ISSUE TITLE
Using a term query with an unindexed field for highlighting

### ISSUE THREAD

**Issue by jerry-cherry** [elastic/elasticsearch#68956]
Highlighting is working for indexed terms. But we'd like to limit the highlighting feature to save the index size. For example, there will be a full content field (with indexed, but without the `stored` option) and an additional field (with a limited length of text) for highlighting (with unindexed, but with `stored` option), and then, the highlight query for the smaller field will be submitted.

As of now, any Elasticsearch query builders check the type's `indexed` property and rejects the requests. As far as I know, Lucene supports this and Solr does not have this constraint. My naïve idea is just to add an option to TermQueryBuilder.

Thanks,
jerry

**Comment by mayya-sharipova** [comment]
Closing, as this is currently supported in Elasticsearch (v 8.12). Example:

```js
PUT index1
{
  "mappings": {
    "properties": {
      "field1": {
        "type": "text"
      },
      "field2" : {
        "type" : "text",
        "index" : false,
        "store" : true
      }
    }
  }
}

POST index1/_bulk?refresh=true
{ "index" : {"_id": 1} }
{"field1": "Canada is a big country", "field2" : "Canada is a big country"}

GET index1/_search
{
  "_source": false,
  "query": {
    "match": {
      "field1": {
        "query": "Canada"
      }
    }
  },
  "highlight": {
    "type": "unified",
    "fields": {
      "field2": {"hits": [
      {
        "_index": "index1",
        "_id": "1",
        "_score": 0.2876821,
        "highlight": {
          "field2": [
            "<em>Canada</em> is a big country"
          ]
        }
      }
    ]        "require_field_match" : "false"
      }
    }
  }
}
```

returns 

```js
"hits": [
      {
        "_index": "index1",
        "_id": "1",
        "_score": 0.2876821,
        "highlight": {
          "field2": [
            "<em>Canada</em> is a big country"
          ]
        }
      }
    ]
```
