### ISSUE TITLE
Set up discuss bot that sends slack notifications for ML team

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#69026]
The ML team would like to receive slack notifications on new ML-related discuss items (https://discuss.elastic.co/).

category: Elastic Stack / Elasticsearch
tags: `stack-machine-learning`, `transforms`
slack channel: #ml-sdh

Question: Will it also work when the tag is added *after* the discuss ticket has been created?

**Comment by markwalkom** [comment]
As this is a request for internal tooling, I'll close this in favour of another issue.
