### ISSUE TITLE
Rare failures of DieWithDignityIT#testDieWithDignity 

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69021]
**Build scan**: https://gradle-enterprise.elastic.co/s/zlb7ryytibg6k and https://gradle-enterprise.elastic.co/s/ckso6lw24jhow

**Repro line**: `REPRODUCE WITH: ./gradlew ':qa:die-with-dignity:javaRestTest' --tests "org.elasticsearch.qa.die_with_dignity.DieWithDignityIT.testDieWithDignity" -Dtests.seed=F18A31D85941A143 -Dtests.security.manager=false -Dtests.locale=ar -Dtests.timezone=Europe/Busingen -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: Only seen on `master` but may apply to earlier branches too.

**Failure history**: Just twice in the last 90 days ([link](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testDieWithDignity),sort:!(process.time-start,desc))))

**Failure excerpt**:

```
» [2021-02-16T08:35:57,990][ERROR][o.e.ExceptionsHelper     ] [javaRestTest-0] fatal error
»  	at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:254)
»  	at java.base/java.util.Optional.ifPresent(Optional.java:183)
»  	at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:244)
»  	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.exceptionCaught(Netty4HttpRequestHandler.java:42)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
[snip...]
» [2021-02-16T08:56:05.252584675Z] [BUILD] Stopping node
```

In both cases the test was apparently stuck waiting for `jps` to finish writing its output:

```
  2> "TEST-DieWithDignityIT.testDieWithDignity-seed#[F18A31D85941A143]" ID=30 RUNNABLE (in native code)
  2> 	at java.base@11.0.2/java.io.FileInputStream.readBytes(Native Method)
  2> 	at java.base@11.0.2/java.io.FileInputStream.read(FileInputStream.java:279)
  2> 	at java.base@11.0.2/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
  2> 	at java.base@11.0.2/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
  2> 	- locked java.lang.ProcessImpl$ProcessPipeInputStream@a30b949
  2> 	at java.base@11.0.2/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
  2> 	at java.base@11.0.2/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
  2> 	at java.base@11.0.2/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
  2> 	- locked java.io.InputStreamReader@7b30b35e
  2> 	at java.base@11.0.2/java.io.InputStreamReader.read(InputStreamReader.java:185)
  2> 	at java.base@11.0.2/java.io.BufferedReader.fill(BufferedReader.java:161)
  2> 	at java.base@11.0.2/java.io.BufferedReader.readLine(BufferedReader.java:326)
  2> 	- locked java.io.InputStreamReader@7b30b35e
  2> 	at java.base@11.0.2/java.io.BufferedReader.readLine(BufferedReader.java:392)
  2> 	at app//org.elasticsearch.qa.die_with_dignity.DieWithDignityIT.lambda$testDieWithDignity$1(DieWithDignityIT.java:40)
```

**Comment by williamrandolph** [comment]
It looks like we hit this failure on April 12th as well. As far as I can tell, the other failures of this test in the time between February and now are for unrelated issues. Here is the April failure: https://gradle-enterprise.elastic.co/s/cz2wskeynssvw

**Comment by rjernst** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/77282
