### ISSUE TITLE
Parameter to round date histograms up instead of rounding down, to support a right-aligned histogram

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elasticsearch#69078]
I couldn't find any previous issues in Elasticsearch, but it's been a long-standing [open issue in Kibana](https://github.com/elastic/kibana/issues/7556) to allow "align to now" instead of "align to round intervals". I appreciate that we [documented the rounding](https://github.com/elastic/elasticsearch/issues/56760) last year.

The requirement is that instead of rounding _based on the Epoch time_, we should _allow the user to provide a fixed time to round from_. For example:

```
POST /sales/_search?size=0
{
  "aggs": {
    "sales_over_time": {
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "1h",
        "rounding": {
          "mode": "down",
          "from": "now"
        }
      }
    }
  }
}
```

So instead of generating buckets at the beginning of each hour, it would generate buckets that align with the time of the request.

**Comment by jimczi** [comment]
That looks like something that you could implement client-side with the `offset` parameter of the `date_histogram`:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-offset ?

**Comment by imotov** [comment]
@wylieconlon does this work for you? Should we close this issue or you want to continue?

**Comment by wylieconlon** [comment]
@imotov Yes, I think this workaround works now that Kibana does datemath conversion in the browser.
