### ISSUE TITLE
SQL: incorrect parsing of nested fields

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#69076]
For nested fields containing _some_ keywords, the query parsing will fail:
* `SELECT a.as FROM foo` generates `line 3:10: no viable alternative at input 'u.as'`
* nesting depth seems irrelevant: same with `a.a.a.a.by` or `a.b.by` and also:
* same with `a.by.a`;
* same with `a.by` or `a.when` or `a.to`, but:
* not with `a.top`, for instance.

These work reliably when quoted, though (`SELECT "a.as" ...`), so probably some grammar ambiguity -- half a bug labeling.

**Comment by costin** [comment]
Per our discussion, I don't think this is an issue as with our RDBMS, keywords are required to be quoted - the unquoted form is allowed only when there is no ambiguity as oppose to a question of priority.

**Comment by bpintea** [comment]
>  the unquoted form is allowed only when there is no ambiguity as oppose to a question of priority.

Right. It's maybe a curious behaviour, but not enough so to need looking into it. Thus closing.
