### ISSUE TITLE
Support v7 response format for get-snapshots API

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69108]
In #42090 we changed the response format for the get-snapshots action in 8.0. When the work to support versioned response formats lands, we should revisit this breaking change and make sure we continue to return the older format if requested.

**Comment by pgomulka** [comment]
so for v7 response:
 if someone is using the regular `/_snapshot/{repository}/{snapshot}` with repository being exact name (not all, or * or multiple values) I could just iterate over successfulResponses and generate a response

if the failedResponse was not empty, then I would return the exception - I would not even iterate the successfulResponses.
Should I just take first failure from `failedResponse`? previously in 7 we would not expect a list of exceptions, but only one.

I don't expect for singleRepo, singleSnapshot api to return mix of successful and failed response in v7. Is this assumption ok?

now if someone would try to use `/_snapshot/all/all` with v7 api, then it would get tricky. I have a feeling that this is unlikely as folks would not have their apps/clients updated to do this.
For simplicity I thought I could just iterate all successfulResponses and merge them all together (skip the repository json level)
However failedResponse was not empty, then for the reason mentioned above, I would not bother iterating successfulResponses. 

What do you think?

**Comment by original-brownbear** [comment]
@pgomulka sorry for not spotting this earlier! I'm actually working on exactly this issue in https://github.com/elastic/elasticsearch/pull/74451 right now which will make v8 mostly use the v7 format again for requests that v7 APIs can respond to. Would you be ok with me assigning this to myself?

**Comment by pgomulka** [comment]
We dicussed this with Armin and there is a chance that there possibly won't be a breaking change for the get snapshots.
You can ignore my [comments](https://github.com/elastic/elasticsearch/issues/69108#issuecomment-866642488)
