### ISSUE TITLE
Task management

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#6914]
We need a task management API to allow management of long running tasks, like snapshot/restore, benchmarking, update-by-query etc.

The API should allow listing and aborting of ongoing tasks.

**Comment by sflint** [comment]
+1

**Comment by niemyjski** [comment]
+1

**Comment by raf64flo** [comment]
Looking at it carefully. :+1:

**Comment by smramdani** [comment]
+1
Would be a great feature as "running queries" and "long queries" in the classical RDBMSs.

**Comment by kennycason** [comment]
+1

**Comment by tostasqb** [comment]
+1

**Comment by kiryam** [comment]
+1

**Comment by chenryn** [comment]
+1

**Comment by kjelle** [comment]
+1

**Comment by amontalenti** [comment]
+1

**Comment by BrickXu** [comment]
+1

**Comment by imotov** [comment]
I created a new meta issue #15117 where work on the task management will be tracked. Closing this one.

**Comment by garyelephant** [comment]
+1

**Comment by rfyiamcool** [comment]
+1

**Comment by garyelephant** [comment]
Will this cover resource limit(similar with spark job executor's cpu,mem resource limit)? For Users who want to aggregate more than 1TB of index, it's likely to cause overall elasticsearch cluster overload, no response.

**Comment by imotov** [comment]
@garyelephant there are no immediate plans to do that as a part of task management effort. However, we are working on some improvements in this area. Please see the discussion in #11511.
