### ISSUE TITLE
[ILM] Add telemetry support for ILM policy configuration

### ISSUE THREAD

**Issue by jethr0null** [elastic/elasticsearch#69152]
xpack usage currently reports which ILM phases and actions are enabled but does not report configuration values for a number of actions. 

It would be good to report the detailed configuration such as: 

* rollover max_age, max_size, max_docs
* set_priority - priority 
* allocate - number_of_replicas
* force_merge - max_num_segments
* shrink - number_of_shards
* anything else along these lines that I may have missed

**Comment by jethr0null** [comment]
I'm also wondering if we could capture whether the migrate action is being injected (possibly as a way to associate ILM policies with data tier usage).

**Comment by jbaiera** [comment]
I am adding rollover and shrink's `maxPrimaryShardSize` settings to the list of configurations to be reported. I didn't see any other items than those two that seemed appropriate.

**Comment by jbaiera** [comment]
Just now noticing that the min age fields are set to milliseconds without the string representation - should we just do the same with the time values and bytes sizes in the configuration?
