### ISSUE TITLE
Add support for 'track_total_hits' in top_hits aggregation

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#69163]
There is a cost to keeping track of total hits. Each top_hits aggregation tracks total hits. It would be nice if [supported per hit features](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html#_supported_per_hit_features) included `track_total_hits` to allow for disabling tracking total hits. One use case would be in Kibana's Map application. top_hits is [used to display the most relevant documents per entity](https://www.elastic.co/guide/en/kibana/current/maps-top-hits-aggregation.html), for example, the most recent GPS tracks per flight route.

Example _search request with top_hits.track_total_hits.
```
{
  "size": 0,
  "aggs": {
    "entitySplit": {
      "terms": {
        "field": "CallSign.keyword"
      },
      "aggs": {
        "entityHits": {
          "top_hits": {
            "track_total_hits": false,
            "size": 1,
            "script_fields": {},
            "docvalue_fields": [
              "coordinates"
            ],
            "_source": false
          }
        }
      }
    }
  },
}
```

**Comment by imotov** [comment]
We have discussed this in a team meeting and concluded that while it is possible and can theoretically achieve significant performance improvement in some cases, the benefits might be insignificant in the use case that you are describing when the latest hits are displayed. The complexity of implementing and testing this functionality also doesn't seem to warrant the effort.

In the example that you are showing you seemed to be interested in displaying the path of some entity based on its recent GPS coordinates. Does [geo line](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/search-aggregations-metrics-geo-line.html) aggregation satisfy your needs here or you need some extra information that is missing there?

**Comment by nreese** [comment]
> In the example that you are showing you seemed to be interested in displaying the path of some entity based on its recent GPS coordinates. Does geo line aggregation satisfy your needs here or you need some extra information that is missing there?

geo_line is licensed at Gold level so its not available to all users. Plus, some users may only wish to visualize the lastest hits as points and not lines. Take for instance ship tracks where a line between 2 points may take the ship across land if the pings are not frequent enough.

**Comment by imotov** [comment]
>  some users may only wish to visualize the lastest hits as points and not lines

No attempt of simplification of the line is done at the moment, which means that even if the last N points are on a straight line we still will show all 5 points. So you can treat this line as an ordered list of points, instead of treating it as a line. 

> geo_line is licensed at Gold level so its not available to all users.

This elasticsearch feature seems to be a precise backend equivalent of the front end feature that you described. If we cannot use it because of license mismatch, we probably need to take another look at the licensing levels for these features across the entire stack and make sure they are consistent. Forcing kibana into searching for workarounds seems counterproductive here cc: @giladgal

**Comment by giladgal** [comment]
I think it's worth discussing it in a meeting between the analytics and maps teams

**Comment by giladgal** [comment]
After some discussion we concluded that it will very rarely generate any benefit and for that reason we have decided to close it
