### ISSUE TITLE
Aggregations: Make order more flexible for terms

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#6917]
Terms aggregations only allow to sort based on the UTF-8 bytes of the term, its count or a sub-aggregation.

We should add more flexibility here to allow for doing things like having compound orders, sorting by collation or by a script that would apply to the sub aggregations.

**Comment by hsm3** [comment]
We are also doing ecommerce, and have groups of products being returned via a terms agg.  We would really like to use a secondary sort to improve the fine-grain ordering, and break ties to make the sort stable.

**Comment by colings86** [comment]
We now have the ability to order by mutliple criteria. Ordering by collation is tricky as mentioned above and we already have issues with unbounded errors in terms ordering as mntioned in https://github.com/elastic/elasticsearch/issues/17588.
