### ISSUE TITLE
Ability to create a pipeline on a field that contains dots 

### ISSUE THREAD

**Issue by aeroxy** [elastic/elasticsearch#69172]
When I use `/_ingest/pipeline/user_agent` to create a pipeline as such:

```
{
    "description": "Add user agent information",
    "processors": [
        {
            "user_agent": {
                "field": "meta.http.headers.user-agent",
                "ignore_missing": true
            }
        }
    ]
}
```

What I really want is to allow the pipeline to process data below:

```
{
    "meta": {
        "http.headers.user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.2(0x1800022c) NetType/WIFI Language/zh_CN"
    }
}
```

I hope we could use the below syntax to create a pipeline:

```
{
  "description": "Add user agent information",
  "processors": [
    {
      "user_agent": {
        "field": {
          "meta": "http.headers.user-agent"
        },
        "ignore_missing": false
      }
    }
  ]
}
```

**Comment by danhermann** [comment]
@aeroxy, the [dot expander](https://www.elastic.co/guide/en/elasticsearch/reference/current/dot-expand-processor.html) processor is intended for cases like this where a field with dots in the name must be converted to a nested object. Ingest processors cannot refer directly to fields with dots in the name because that would introduce an ambiguity with the identification of JSON fields. In your example, it would be impossible to distinguish between any of the following fields in a document:

```
{
    "meta.http.headers.user-agent" : "",
    "meta": {
        "http.headers.user-agent": "..."
    },
    "meta.http": {
        "headers.user-agent": "..."
    },
    "meta.http.headers": {
        "user-agent": "..."
    }
}
```

since they would all be called `meta.http.headers.user-agent`.

**Comment by aeroxy** [comment]
> @aeroxy, the [dot expander](https://www.elastic.co/guide/en/elasticsearch/reference/current/dot-expand-processor.html) processor is intended for cases like this where a field with dots in the name must be converted to a nested object. Ingest processors cannot refer directly to fields with dots in the name because that would introduce an ambiguity with the identification of JSON fields. In your example, it would be impossible to distinguish between any of the following fields in a document:
> 
> ```
> {
>     "meta.http.headers.user-agent" : "",
>     "meta": {
>         "http.headers.user-agent": "..."
>     },
>     "meta.http": {
>         "headers.user-agent": "..."
>     },
>     "meta.http.headers": {
>         "user-agent": "..."
>     }
> }
> ```
> 
> since they would all be called `meta.http.headers.user-agent`.

The dot expander changes the data structure of the upcoming data stream which would be incompatible with the existing data.

It's okay to be impossible to distinguish between any of the following fields in a document:

```
{
    "meta.http.headers.user-agent" : "",
    "meta": {
        "http.headers.user-agent": "..."
    },
    "meta.http": {
        "headers.user-agent": "..."
    },
    "meta.http.headers": {
        "user-agent": "..."
    }
}
```

In my case, I just need to be able to do search on documents and get

```
meta['http.headers.user-agent']
```

**Comment by danhermann** [comment]
@aeroxy, the bug in  https://github.com/elastic/elasticsearch/issues/69348 will be fixed in the next release after which the following would work for you:

```
    "processors": [
      {
        "set": {
          "field": "meta2",
          "copy_from": "meta"
        }
      },
      {
        "dot_expander": {
          "field": "http.headers.user-agent",
          "path": "meta2"
        }
      },
      {
        "user_agent": {
          "field": "meta2.http.headers.user-agent"
        }
      },
      {
        "remove": {
          "field": "meta2"
        }
      }
    ]
```
It copies `meta` to a new field `meta2`, runs the dot expander on it and extracts the user agent, and then deletes the `meta2` object leaving the document unchanged except for the addition of the user agent data.

**Comment by aeroxy** [comment]
> @aeroxy, the bug in  #69348 will be fixed in the next release after which the following would work for you:
> 
> ```
>     "processors": [
>       {
>         "set": {
>           "field": "meta2",
>           "copy_from": "meta"
>         }
>       },
>       {
>         "dot_expander": {
>           "field": "http.headers.user-agent",
>           "path": "meta2"
>         }
>       },
>       {
>         "user_agent": {
>           "field": "meta2.http.headers.user-agent"
>         }
>       },
>       {
>         "remove": {
>           "field": "meta2"
>         }
>       }
>     ]
> ```
> 
> It copies `meta` to a new field `meta2`, runs the dot expander on it and extracts the user agent, and then deletes the `meta2` object leaving the document unchanged except for the addition of the user agent data.

In this specific example the solution you have provided above would work, however...

```
{
    "description": "Convert number to string",
    "processors": [
        {
            "convert": {
                "field": "meta.http.user.id",
                "type": "string"
            }
        }
    ]
}
```

if I would like to convert an existing field (which has both number and string) to string so I can use aggregation on that field, this wouldn't work (I am currently using script but it slows down the pipeline).
