### ISSUE TITLE
Deprecation log fills with same log line

### ISSUE THREAD

**Issue by andsel** [elastic/elasticsearch#69188]
**Elasticsearch version** (`bin/elasticsearch --version`):
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 7.10.0, Build: default/tar/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 11.0.7

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux kalispera 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When send indexing request with `type`, each request generate a log line in `elasticsearch_deprecation.log`, with always the same log line.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

1. download Elasticsearch `7.10.0` tar.gz, unpack and run Elasticsearch `bin/elasticsearch`
2.  download Logstasn `7.10.0`, unpack it
3.  create a pipeline config (name it `test_pipeline.conf`) with content:
```
input {
	generator {
		message => "{\"name\": \"John Doe\"}"
		count => 20000
	}
}

output {
	elasticsearch {
		index => "test_bulk_index"
	}
}
```
4.  run `bin/logstash -f test_pipeline.conf`
5. check the `logs/elasticserach_deprecation.log` increasing

**Provide logs (if relevant)**:

**Comment by pgomulka** [comment]
fixed by https://github.com/elastic/elasticsearch/pull/69190
