### ISSUE TITLE
geo_shape type doesn't accept circle

### ISSUE THREAD

**Issue by dw-alex** [elastic/elasticsearch#69184]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1 (via docker `docker.elastic.co/elasticsearch/elasticsearch:7.11.1`)

**Plugins installed**: none

**Description of the problem including expected versus actual behavior**: `geo_shape` type doesn't accept circles

**Steps to reproduce**:

Create a mapping with `location` of type `geo_shape`:

```json
PUT /example
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_shape"
      }
    }
  }
}
```

Then add a circle :

```json
POST /example/_doc
{
  "location" : {
    "type" : "circle",
    "coordinates" : [101.0, 1.0],
    "radius" : "100m"
  }
}
```

The above `POST` leads to the following error:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [location] of type [geo_shape]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [location] of type [geo_shape]",
    "caused_by" : {
      "type" : "unsupported_operation_exception",
      "reason" : "circle geometry is not supported"
    }
  },
  "status" : 400
}
```

NB : no problem with `point`, `envelope`, or `polygon `.

**Comment by iverase** [comment]
Hi @dw-alex,

BKD tree indexing does not support circles natively. You need to approximate to a polygon and we added an ingest circle processor to help:

https://www.elastic.co/guide/en/elasticsearch/reference/7.11/ingest-circle-processor.html

Would it be sufficient for you needs?

**Comment by dw-alex** [comment]
Thanks for the explanation. Perhaps the documentation of circle on the [geo_shape field](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#_circle) should mention that. I thought it was supported out-of-the-box.

**Comment by iverase** [comment]
Agree, I leave this issue open until we add this info to the documentation.
