### ISSUE TITLE
More docker caching?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#69207]
If we build our `rootfs` docker images in `package build` then the CI images would come pre-filled with a cache of docker's dependencies. We'd hit the cache most of the time because we fairly rarely modify the `Dockerfile`. If we do modify the `Dockerfile` then portions of the cache still may be useful. This'd speed up the docker build marginally and help to avoid issues when things like `busybox.net` is dwn.

**Comment by pugnascotia** [comment]
We changed the Docker base to Ubuntu, so I don't think this issue applies any more.
