### ISSUE TITLE
can we search from multiple indexs and assemble their？

### ISSUE THREAD

**Issue by Anyzm** [elastic/elasticsearch#69254]
can we search from multiple indexs and assemble their？

eg:
there are two index person and car，
there are a field called sex in index person and a field called color in index car，we want to search the women who own black cars in one request。
how can we make it？

**Comment by tvernum** [comment]
Hi @Anyzm, thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
