### ISSUE TITLE
ILM try delete datastream earlier than necessary

### ISSUE THREAD

**Issue by zakabluk** [elastic/elasticsearch#69264]
Elasticsearch 7.9.3
I have ILM policy
```
PUT _ilm/policy/delete-after-7-days
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "6d"
          },
          "set_priority": {
            "priority": 100
          }
        }
      },
      "warm": {
        "actions": {
          "allocate": {
            "include": {},
            "exclude": {},
            "require": {
              "box_type": "hot"
            }
          },
          "set_priority": {
            "priority": null
          }
        }
      },
      "delete": {
        "min_age": "1d",
        "actions": {
          "delete": {
            "delete_searchable_snapshot": true
          }
```
I expected that my index was live in hote phase("max_age": "6d"). Than will rollover and index move to warm. Than after 1 day 
datastream will deleted   ("min_age": "1d"). But my datastream was deleted after 1 day. Why?

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
