### ISSUE TITLE
Elasticsearch takes all the memory.

### ISSUE THREAD

**Issue by FabianBoernerCHECK24** [elastic/elasticsearch#69408]
Hi,

we upgraded our system and Suddenly elasticsearch took all the memory of the system.

Instead of the previous setting of Xms1g we now have no setting and it takes all the memory.

Is that wanted behaviour?

**Comment by jaymode** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
