### ISSUE TITLE
[CI] DataStreamTests.testSnapshotWithAllBackingIndicesRemoved failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#69421]
**Build scan**:
https://gradle-enterprise.elastic.co/s/svodbyhwavfcw

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DataStreamTests.testSnapshotWithAllBackingIndicesRemoved" -Dtests.seed=8080DD4EBF3ECF73 -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=America/Resolute -Druntime.java=11 -Dtests.fips.enabled=true |  
```

**Reproduces locally?**:
YES

**Applicable branches**:
7.12

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testSnapshotWithAllBackingIndicesRemoved),sort:!(time,desc))

**Failure excerpt**:
```
org.elasticsearch.cluster.metadata.DataStreamTests > testSnapshotWithAllBackingIndicesRemoved FAILED |  
-- | --
  | java.lang.AssertionError |  
  | at __randomizedtesting.SeedInfo.seed([8080DD4EBF3ECF73:3EA707DB324CD5C5]:0) |  
  | at org.elasticsearch.cluster.metadata.DataStream.<init>(DataStream.java:66) |  
  | at org.elasticsearch.cluster.metadata.DataStreamTests.testSnapshotWithAllBackingIndicesRemoved(DataStreamTests.java:216)
```

**Comment by martijnvg** [comment]
Looks like #69004 wasn't backported to 7.x and 7.12 branches. 
I will backport that change.

**Comment by matriv** [comment]
Thx @martijnvg !

**Comment by martijnvg** [comment]
Fix has been backported.

**Comment by matriv** [comment]
@martijnvg Please don't forget `7.12`, thx!

**Comment by martijnvg** [comment]
> @martijnvg Please don't forget 7.12, thx!

https://github.com/elastic/elasticsearch/pull/69425

**Comment by matriv** [comment]
thx thx!
