### ISSUE TITLE
bin/plugin on a system where JAVA_HOME contains spaces fails

### ISSUE THREAD

**Issue by mikebaldry** [elastic/elasticsearch#6942]
```
/usr/local/Cellar/elasticsearch/1.2.1/bin  $ echo $JAVA_HOME
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
```

results in 

```
/usr/local/Cellar/elasticsearch/1.2.1/bin  $ ./plugin 
./plugin: line 49: /Library/Internet: No such file or directory
./plugin: line 49: exec: /Library/Internet: cannot execute: No such file or directory
```

Suggested fix (worked for me, but I'm no bash guru)
put double quotes around $JAVA in the exec line of plugin

**Comment by ptheofan** [comment]
Bug reappeared? I'm having the exact same issue despite that $JAVA is in doublequotes.

**Comment by nik9000** [comment]
Its possible this came back. We're much better at testing these scripts now but we don't test this case. I'll reopen this so we know to investigate. But I don't know when I'll get a chance to work on it though.

**Comment by rmuir** [comment]
We can test this by putting a space in the path to JAVA_HOME on jenkins servers.

**Comment by pbaille** [comment]
I've got this issue to, is there a workaround to install marvel?

**Comment by clintongormley** [comment]
This is still broken in 2.2 and master

**Comment by kdelchev** [comment]
I had similar issue (`line 114: /Library/Internet: No such file or directory`). Running `sudo bin/plugin license` did the job.

**Comment by ptheofan** [comment]
Latest workaround that worked for me like a charm. Escape the JAVA_HOME path (and ignore the fact that it's wrapped in double quotes)!

I went from
```bash
# export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```

to 

```bash
export JAVA_HOME="/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```

and it worked

**Comment by OsamHdz** [comment]
I had the same problem that @kdelchev, but the sudo command didn't work. Adding ' single quotes at "$JAVA_HOME" in eval line worked for me.

```bash
eval '"$JAVA"' -client -Delasticsearch -Des.path.home="\"$ES_HOME\"" $properties -cp "\"$ES_HOME/lib/*\"" org.elasticsearch.plugins.PluginManagerCliParser $args
```

Here is the info:
http://unix.stackexchange.com/questions/131766/why-does-my-shell-script-choke-on-whitespace-or-other-special-characters

**Comment by clintongormley** [comment]
this is fixed in 5.0

**Comment by anchal0997** [comment]
I am still seeing this issue.

**Comment by pugnascotia** [comment]
@anchal0997 we'll need information please, such as the ES version and terminal output.
