### ISSUE TITLE
Use Lucene's IDVersionPostingsFormat for _uid field

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#6945]
Lucene's new ID+version optimized postings format (https://issues.apache.org/jira/browse/LUCENE-5675 ) should work well for the _uid field.

First, it stores the version with each _uid value directly in the terms index/dict, so we don't need a separate numeric DV lookup (saves one seek & some CPU).

Second, in certain cases it can know just by looking at the in-RAM terms index that a given segment does not contain and ID with a version > X, which can speed up the optimistic concurrency case ("update doc as long as indexed version is <= N).  But taking advantage of this is tricky because ES lets the app pick its version semantics, so I think for this issue we should simply focus on switching to IDVPF and storing/retrieving the version in the terms dict instead of numeric DV.

This issue should also fix tests to randomize whether this PF is used for _uid.

We need to be careful w/ back-compat here as well, because this PF has no back-compat insurance from Lucene (it's not a core PF), and we also must recognize and read "old" segments that stored the version in numeric DV, on a segment by segment basis.

**Comment by clintongormley** [comment]
@mikemccand is this something you're still interested in?

**Comment by mikemccand** [comment]
Well, 1) I think it's not a huge win since few users take advantage of optimistic concurrency (I think?), and 2) this is still a sandbox postings format, so there's no back-compat.  I'll close ... we can revisit if things change.

**Comment by bleskes** [comment]
a short note that we load the version all the time because we need to update it on the primary and replicas use it to deal with out of order delivery from the primary. That said +1 on not using a posting format with no bwc.
