### ISSUE TITLE
ReloadingDatabasesWhilePerformingGeoLookupsIT#test failed

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69475]
**Build scan**: https://gradle-enterprise.elastic.co/s/4kvggmablz2ea/console-log?task=:modules:ingest-geoip:internalClusterTest

**Repro line**: `REPRODUCE WITH: ./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test" -Dtests.seed=12714BFB74C76F6 -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Asia/Baghdad -Druntime.java=8`

**Reproduces locally?**: Yes

**Applicable branches**: Only 7.x so far

**Failure history**: [First failure](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:ReloadingDatabasesWhilePerformingGeoLookupsIT),sort:!(process.time-start,desc))), but this test was not merged long ago.

**Failure excerpt**:

```
2> java.lang.AssertionError: |  
-- | --
  | Expected: null |  
  | but: was <java.lang.AssertionError: |  
  | Expected: not sameInstance(<org.elasticsearch.ingest.geoip.DatabaseReaderLazyLoader@66e20dc2>) |  
  | but: was <org.elasticsearch.ingest.geoip.DatabaseReaderLazyLoader@66e20dc2>> |  
  | at __randomizedtesting.SeedInfo.seed([12714BFB74C76F6:89732B6519B01B0E]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test(ReloadingDatabasesWhilePerformingGeoLookupsIT.java:143)
```

**Comment by DaveCTurner** [comment]
Muted in 7.x: a7d280a8e007466b515452834f84203e9edf6bf9

**Comment by DaveCTurner** [comment]
Not sure if this is a 7.x-only problem, I can't reproduce it in `master`, so I'm only muting it in `7.x`.

**Comment by martijnvg** [comment]
I think it is a timing issue. The logs indicate that no database update has yet taken place, while the files have been moved. 
The `ResourceWatcherService`'s `resource.reload.interval.high` setting is still on the default (`5s`), so I will lower this to `100ms`, which other tests that test file reload do as well.

**Comment by martijnvg** [comment]
This issue started to occur again only on the 7.x branch. I'm able to reproduce it locally:
`./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test" -Druntime.java=8`

Changing java runtime to 11 or higher makes the test pass. Somehow the `FileWatcher` class doesn't detect if a file gets replaced with the same content when running with a runtime version 8, but does from runtime version 11 or higher.

**Comment by jakelandis** [comment]
Ran into this on a PR against master : https://gradle-enterprise.elastic.co/s/vzyelptm2tvos

**Comment by martijnvg** [comment]
Unfortunately this failed again after a fix was pushed to both master and 7.x: https://gradle-enterprise.elastic.co/s/7lspdln444u6y (master, looks like a test issue).

I think the test can be made more stable by not relying on `FileWatcher` to detect changes, but from the `updateDatabaseThread` thread invoke `LocalDatabases#updateDatabase(...)`. We then still test that
the geoip work correct if database are changed while ingesting, but without relying on watching for
changes in geoip config directory.

I will fix this next week. In the mean time I will mute this test.
