### ISSUE TITLE
[CI] GeoIpProcessorNonIngestNodeIT testLazyLoading failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#69496]
There have been some changes here around the introduction of a test fixture. Perhaps that is at play?

**Build scan**:
https://gradle-enterprise.elastic.co/s/efjcopyvrgc2q/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeIT/testLazyLoading#1

**Repro line**:
`./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeIT.testLazyLoading" -Dtests.seed=CC3286F211876D5A -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=Greenwich -Druntime.java=11`

**Reproduces locally?**:
No

**Applicable branches**:
`master`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeIT&tests.sortField=FAILED&tests.test=testLazyLoading&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeIT > testLazyLoading FAILED
    java.lang.AssertionError: Shard [.geoip_databases][0] is still locked after 5 sec waiting
        at __randomizedtesting.SeedInfo.seed([CC3286F211876D5A:A81B6736C4820283]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2321)
        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:551)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2073)
```

**Comment by mark-vieira** [comment]
So far as I can tell from the log the geoip-fixture came up just fine so maybe this is unrelated?

**Comment by mark-vieira** [comment]
I'm actually not completely sure this is an :Analytics/Geo issue. @probakowski since we were just working on this do you mind taking a look and routing this to the correct place?

**Comment by probakowski** [comment]
It's for sure core/features not analytics/geo - it's about ingest processor. I don't know what can cause error above though, will investigate

**Comment by ywangd** [comment]
Failed twice today on master:
* https://gradle-enterprise.elastic.co/s/llcmm42uilz3q
* https://gradle-enterprise.elastic.co/s/nn5gxpcdydrh2

**Comment by pgomulka** [comment]
just got another one on a PR against master
https://gradle-enterprise.elastic.co/s/5g7nhuw5lpiio

**Comment by probakowski** [comment]
It seems it's a different error, just happens to be in the same test. 
I've opened https://github.com/elastic/elasticsearch/pull/70135 that should fix this particular failure
