### ISSUE TITLE
Using dot in index name may cause data stream not correctly create backing indices and throw 500 errors

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#69500]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9

**Plugins installed**: []
N/A

**JVM version** (`java -version`):
Bundled JDK

**OS version** (`uname -a` if on a Unix-like system):
Major OS

**Description of the problem including expected versus actual behavior**:

If using `. (dot)` in index name, data stream may not correctly create backing indices and will throw 500 errors.
Alternatively, same for other conditions, if using `- (dash)` in index name, then the issue will not happen.

**Steps to reproduce**:

[1]
Assuming there are 2 indices.
- `hall1.openshift.ocp45-uat1.openshift-kube-apiserver`
- `hall1.openshift.ocp45-uat1.openshift-kube-apiserver-operator` (with an additional trailing `operator` keyword)

[2]
Setup data stream.
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/set-up-a-data-stream.html

**Expected result**
No naming confliction error ocurring.

**Actual result**
ES reports the following `500` error. (This error is captured in the logstash log)

```
illegal state exception, reason: 
data stream hall1.openshift.ocp45-uat1.openshift-kube-apiserver 
could create backing indices that conflict with 1 existing index or alias include 
.ds-hall1.openshift.ocp45-uat1.openshift-kube-apiserver-operator-000002. 
```

**Workaround**
After changing all the `. (dot)` notation in the index naming to `- (hyphen)`, it stopped reporting the error alredy ever since.

**Additional Information**
The observation is that this error occurs at random.
Sometimes it just error message but system can continue to create the backing index. 
Worst case is as described previously, it failed to create backing index and jammed the entire logstash queue.

**Comment by danhermann** [comment]
@kunisen, thanks for reporting this. We saw this problem in another case and fixed it in https://github.com/elastic/elasticsearch/pull/65791 which went into the 7.10.2 release.
