### ISSUE TITLE
packaging-vagrant-matrix failures

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#69504]
**Build scan**:
There are a few failures that all related to IO issues potentially due to setup, e.g. "No such file or directory", "no source files" etc.
* https://gradle-enterprise.elastic.co/s/75qvxm5cjlboc
* https://gradle-enterprise.elastic.co/s/plns2fmdnijvy

**Repro line**:
N/A

**Reproduces locally?**:
N/A

**Applicable branches**:
7.11

**Failure history**:
The test failed [quite many times](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%22packaging-vagrant-matrix%22),sort:!(process.time-start,desc))) in past few days (they may not all be due to the same underlying reason): 

**Failure excerpt**:
```
* What went wrong:
Execution failed for task ':x-pack:plugin:identity-provider:compileJava'.
> error: no source files
```
```
Caused by: java.io.FileNotFoundException: /elasticsearch/qa/os/build/test-results/destructiveDistroTest.default-linux-archive/output/org.elasticsearch.packaging.test.PackageTests.out (No such file or directory)
| 	at java.base/java.io.FileOutputStream.open0(Native Method)
| 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
| 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
| 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
| 	at org.elasticsearch.gradle.test.ErrorReportingTestListener$EventWriter.<init>(ErrorReportingTestListener.java:237)
```

**Comment by mark-vieira** [comment]
This job has been removed.
