### ISSUE TITLE
[ML] Add Trained Model Post-Processors

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#69571]
Certain models require post-processing of results to make those results more consumable. Examples are reverting to tokenisation process to reassemble input text or converting a numerical to label in a classification tasks.

- `argmax` Return the index of the max value for a given dimension
- `softmax` 
- `label map` Converts an integer value to a label
- `de-tokenise` Reassemble input tokens

Post-Processors would be defined in a similar manner to the existing pre-processors and be optional. It must be possible to chain the outputs and inputs of processors together to handle cases such as `argmax() -> label map()`

**Comment by benwtrent** [comment]
Ensemble model types already have something similar called `OutputAggregator`

We may want to refactor and move that out of the ensemble models.

**Comment by joshdevins** [comment]
Closed by https://github.com/elastic/ml-cpp/pull/1902
