### ISSUE TITLE
.fdt file still exist when disable _source

### ISSUE THREAD

**Issue by lexlee327** [elastic/elasticsearch#69584]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.11

**Plugins installed**: []
no

**JVM version** (`java -version`):
jdk 12

**OS version** (`uname -a` if on a Unix-like system):
mac

**Description of the problem including expected versus actual behavior**:
When I disable the _source, It is expected lower storage usage, but it didn't. 
After set `_source: { enabled: false}` , Elasticsearch doesn't return `_source` in get/search request, but it still keep the .fdt file in segment
Elasticsearch are wildly use in OLAP case, when we just need the analysis report without show the documents, we could get rid of the stored field

**Steps to reproduce**:
1, add sample data:
![image](https://user-images.githubusercontent.com/55966987/109102242-6252e700-7763-11eb-950c-70744d1f7496.png)

2, reindex it with `_source` disable
![image](https://user-images.githubusercontent.com/55966987/109004731-1b71dc80-76e4-11eb-87c8-94267900f6ef.png)
3, new index return without _source
![image](https://user-images.githubusercontent.com/55966987/109102312-87dff080-7763-11eb-8d9a-f63eda2f385d.png)

4, new index with the same size 
![image](https://user-images.githubusercontent.com/55966987/109102290-7a2a6b00-7763-11eb-9938-ef80f54c56ac.png)

5. have the .fdt file
![image](https://user-images.githubusercontent.com/55966987/109102125-1dc74b80-7763-11eb-8da7-0bfd14e8eee5.png)

**Comment by markharwood** [comment]
>When I disable the _source, It is expected lower storage usage, but it didn't.

Thanks for the report. One thing that looks to be missing is the file size comparison between the source enabled and source disabled indices. Could you provide that? Otherwise all you may be showing is that there is some residual use of stored values (possibly not related to source).

**Comment by DaveCTurner** [comment]
I think we need to know exactly what version this is about too, the OP says `7.x` but this is not at all helpful.

In some versions we temporarily retain the source for replica recovery (and CCR) even if `_source` is disabled. It gets removed by a later merge once it's no longer needed.

**Comment by ywelsch** [comment]
Relates https://github.com/elastic/elasticsearch/issues/41628

**Comment by lexlee327** [comment]
> > When I disable the _source, It is expected lower storage usage, but it didn't.
> 
> Thanks for the report. One thing that looks to be missing is the file size comparison between the source enabled and source disabled indices. Could you provide that? Otherwise all you may be showing is that there is some residual use of stored values (possibly not related to source).

![image](https://user-images.githubusercontent.com/55966987/109647484-4b155e80-7b94-11eb-8fc1-6c72f6389070.png)
I reindex the sample data with the name `source_enable` and `source_disable`, you could see that, the `source_enable` even more bigger. 
I think the key issue is that, it still generate the .fdt file in segment

**Comment by lexlee327** [comment]
> I think we need to know exactly what version this is about too, the OP says `7.x` but this is not at all helpful.
> 
> In some versions we temporarily retain the source for replica recovery (and CCR) even if `_source` is disabled. It gets removed by a later merge once it's no longer needed.

I tested it in 7.9.0, 7.10.0, 7.11.0

**Comment by lexlee327** [comment]
just like @DaveCTurner said, I have to disable soft_delete
```
    "settings": {
      "number_of_replicas" : "0",
      "soft_deletes": {
        "enabled": false
      }
    }
```
then, the .fdt file is the proper size:

![image](https://user-images.githubusercontent.com/55966987/109648830-0ab6e000-7b96-11eb-886d-4a4b24172a8c.png)
![image](https://user-images.githubusercontent.com/55966987/109648963-389c2480-7b96-11eb-8d47-371c2d32348e.png)

**Comment by DaveCTurner** [comment]
> just like @DaveCTurner said, I have to disable soft_delete

I said nothing about disabling soft deletes, and I certainly don't recommend that either.

What I _did_ say was that the source is only kept while it's needed for recovery or CCR, and it's removed by a later merge. It's therefore the expected behaviour for there to be stored fields in some segments: there's only a bug here if we are retaining stored fields in merges even though there's no reason to retain it, and so far we haven't seen any evidence of that.

**Comment by DaveCTurner** [comment]
No further response after a few weeks so I'm closing this. If you can find and share evidence of a bug (see my previous message) then we can reopen this.
