### ISSUE TITLE
Ensure Reset Features API correctly resets ML configuration

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#69581]
While the PR that introduces the Reset Features API (https://github.com/elastic/elasticsearch/pull/69469) includes a basic iteration of ML state cleanup, it may not be complete. This reset function should be evaluated by the ML and any shortcomings corrected if necessary.

/cc @droberts195

**Comment by gwbrown** [comment]
It's been pointed out that [Transforms may need a look over as well](https://github.com/elastic/elasticsearch/pull/69469#discussion_r586176251).

**Comment by benwtrent** [comment]
Related PRs:

- Transforms: https://github.com/elastic/elasticsearch/pull/71133
- ML: https://github.com/elastic/elasticsearch/pull/71011, https://github.com/elastic/elasticsearch/pull/71293 (bug fixes)

**Comment by benwtrent** [comment]
Machine learning and transform plugins now are fully cleaned up with the reset feature API.

Following up PRs have fixed some bugs here and there, but it is looking stable right now. Closing issue.
