### ISSUE TITLE
Phrase Suggester Returns Suggestions of Deleted Documents

### ISSUE THREAD

**Issue by bencody** [elastic/elasticsearch#69591]
**Elasticsearch version** (`bin/elasticsearch --version`): as of 7.0.0 and still present in 7.11.1.

**Plugins installed**: []

**JVM version** (`java -version`): Whatever is used by `docker.elastic.co/elasticsearch/elasticsearch:7.0.0`

**OS version** (`uname -a` if on a Unix-like system): Docker Desktop 3.0.1 (50773) on macOS 11.2.1 (`Darwin XXX.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`)

**Description of the problem including expected versus actual behavior**:

Phrase Suggester returns suggestions for deleted documents.

(I also posted this on https://discuss.elastic.co/t/phrase-suggester-returns-suggestions-from-deleted-documents-as-of-7-0-0/265068 but got no response. To me it seems very likely that this is a bug and not a feature, so I decided to post it here.)

**Expected behavior:**
1. Given an index with a text property
2. When document 1 with property "coarse" is indexed
3. And all documents are deleted
4. And document 2 with property "course" is indexed
5. And phrase suggestions for value "corse" are requested
6. Then only the suggestion "course" (from document 2) should be returned

**Actual behavior**
2 suggestions are returned: "coarse" (from the deleted document 1) and "course" (from document 2).

**Steps to reproduce**:

```
PUT test_index
{
  "mappings": {
    "properties": {
      "some_field": {
        "type": "text"
      }
    }
  }
}

PUT test_index/_doc/1
{"some_field":"Coarse"}

POST test_index/_delete_by_query
{"query":{"match_all":{}}}

PUT test_index/_doc/2
{"some_field":"Course"}

GET test_index/_search
{
  "suggest": {
    "suggestions": {
      "text": "corse",
      "phrase": {
        "field": "some_field"
      }
    }
  }
}
```

**Provide logs (if relevant)**:

Response from "suggest" query:

```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "suggest" : {
    "suggestions" : [
      {
        "text" : "corse",
        "offset" : 0,
        "length" : 5,
        "options" : [
          {
            "text" : "coarse",
            "score" : 0.60966235
          },
          {
            "text" : "course",
            "score" : 0.60966235
          }
        ]
      }
    ]
  }
}
```

**Comment by bencody** [comment]
Probably related to https://github.com/elastic/elasticsearch/issues/62677.

**Comment by markharwood** [comment]
See [ the docs ](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html), specifically the `collate` param. It's what helps prune the suggestions gleaned from the raw index by checking actual documents exist with that term.
Also checkout the correct index mapping required for phrase suggestions. 

Closing as "working as designed"
