### ISSUE TITLE
[CI] GeoIpDownloaderIT.testGeoIpDatabasesDownload

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#69594]
**Build scan**:
https://gradle-enterprise.elastic.co/s/3rhsethztvfto
https://gradle-enterprise.elastic.co/s/epbjbdvjltc2k

**Repro line**:
```
./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testGeoIpDatabasesDownload" \
  -Dtests.seed=F82C65126D64DEAC \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-GB \
  -Dtests.timezone=Europe/Uzhgorod \
  -Druntime.java=8
```

**Reproduces locally?**:

No.

**Applicable branches**:
Failed in 7.x only for now.

**Failure history**:
Started failing [this morning](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testGeoIpDatabasesDownload),sort:!(time,desc))), looks like test was merged to 7.x yesterday in #69481/#68424

**Failure excerpt**:

```

org.elasticsearch.ingest.geoip.GeoIpDownloaderIT > testGeoIpDatabasesDownload FAILED |  
-- | --
  | java.lang.AssertionError |  
  | at __randomizedtesting.SeedInfo.seed([F82C65126D64DEAC:4D976915F6DFC979]:0) |  
  | at org.junit.Assert.fail(Assert.java:86) |  
  | at org.junit.Assert.assertTrue(Assert.java:41) |  
  | at org.junit.Assert.assertNotNull(Assert.java:712) |  
  | at org.junit.Assert.assertNotNull(Assert.java:722) |  
  | at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.lambda$testGeoIpDatabasesDownload$0(GeoIpDownloaderIT.java:81) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1010) |  
  | at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testGeoIpDatabasesDownload(GeoIpDownloaderIT.java:77)

```

**Comment by henningandersen** [comment]
Muted in #69595

**Comment by probakowski** [comment]
I'll this issue as this should be fixed now. Please reopen if it reoccurs

**Comment by martijnvg** [comment]
This failure just re-occurred on master: https://gradle-enterprise.elastic.co/s/rje5l6ma3qweo

**Comment by probakowski** [comment]
It hasn't failed in a week, I'll close it again. Please reopen if it reoccurs
