### ISSUE TITLE
Gradle test execution failes when using JDK with wrong page size on ARM

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#69633]
There's an [open JDK bug](https://bugs.openjdk.java.net/browse/JDK-8236847) related to ARM that if the current JDK was built on a system with a different page size than the sytem you are _running_ the JDK on, you'll receive this error:

```
[0.015s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536 
```

We've worked around this in ES itself, but our build is not so resilient because Gradle's JVM probing logic barfs on this.

https://gradle-enterprise.elastic.co/s/natnewgn37p26/failure?expanded-stacktrace=WyIwLTEiXQ

I think we may need to report this to the build tool team to address and make their probing logic more resilient since this "error" isn't actually fatal.

**Comment by mark-vieira** [comment]
@breskeby this makes our ARM testing initiative somewhat annoying. Do you mind reaching out to the Gradle folks about this?

**Comment by breskeby** [comment]
I'll raise that with the gradle folks tomorrow

**Comment by breskeby** [comment]
Raised https://github.com/gradle/gradle/issues/16318

**Comment by mark-vieira** [comment]
For now we work around this bug by using the appropriate JDK build on different operating systems. I'd say we can close this issue.
