### ISSUE TITLE
_source querystring parameters doesn't work in _update_by_query

### ISSUE THREAD

**Issue by davide882** [elastic/elasticsearch#69648]
Good morning,
I'm using the 7.10.0 Elastic version and when I try to do and _update_by_query with the _source parameter I get no fields back.
The update goes well in any case.

```
POST my_index/_update_by_query?_source=true
{
  "script": {
    "source": "ctx._source.IdReferrer='test'",
    "lang": "painless"
  },
  "query": {
    "term": {
      "Source": "Objects::Add"
    }
  }
}
```
The result of this query:
```
{
  "took" : 10,
  "timed_out" : false,
  "total" : 1,
  "updated" : 1,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}
```

Thank you very much.

**Comment by pgomulka** [comment]
I am not sure I follow. Where do you expect the fields to be present?
the documentation do not state that this will be returned https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

We'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by dapriett** [comment]
@pgomulka I noticed this as well.  The documentation says:

```
_source
(Optional, string) True or false to return the _source field or not, or a list of fields to return.
```

So I'm expecting setting the param _source=true to return the updated hits in the _source field, but it doesn't
