### ISSUE TITLE
Reindex resulting index size larger than original index

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#69658]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1

**Plugins installed**: [analysis-icu]

**JVM version** (`java -version`): OpenJDK 64-Bit Server VM

**OS version** (`uname -a` if on a Unix-like system): macOS Big Sur

**Description of the problem including expected versus actual behavior**:

I am trying to run a simple *reindex* operation from a small (~24K docs) index to a new index with identical settings (copied over from the old one).

I am using the Nodejs client, though I have also tried running the operation through the Kibana dev console with the same results, so I don't think it is client-related.

The operation takes too long to complete (much more that a manual indexing of the same data to the new index), seems to be stuck at intervals (documents count starts increasing normally, but gets randomly stuck for a while) and, after the operation completes, the new index has a much larger storage size than the original (~610MB vs ~150MB).

Trying to compare the _stats output of both indices after the operation, the only notable difference that I can find (apart from the storage size) is that the new index has a positive (10K) deleted docs values, when the original has 0 (the index docs are never edited in my use case).

I have tried setting the target "op_type" to "create", which makes the indexing process complete much quicker, but with 1000 (the round number is suspicious) version_conflicts. Please note that I do not provide document versions in my indices, so the  internal UID is used (so there should not be version conflicts, right?).

**Steps to reproduce**:

I don't think there is a way to reproduce this without providing my exact index settings *and data*, which is unfortunately not possible.

**Provide logs (if relevant)**:

ES produces no relevant logs that I can find (apart from the index creation).

**Comment by nemphys** [comment]
I have no problem with the title change (could not find a good title candidate myself), but the index size is not the only problem here; it also takes too long to generate this new oversized index. Maybe this should be included in the title, too.

**Comment by henningandersen** [comment]
@nemphys can you share more details on the exact reindex command as well as perhaps the index settings and more for the relevant indices.

**Comment by nemphys** [comment]
@henningandersen unfortunately it has been too long and I have since followed a totally different route while dealing with this, so I am no longer able to reproduce the initial issue.

**Comment by nemphys** [comment]
Coming back to this after a long time (the problem still persists in 8.8.2) and after a lot of fresh testing, I have the following findings to report:

- For small indices (~5K docs), the reindexing works fine
- When trying to reindex ~80K docs, everything is fine until ~25K docs, but after that it seems that for some reason ES is trying to (re)index the same documents and 1) if ip_type='create', it fails with version conflict errors (version 1 vs version 1), 2) otherwise it just starts increasing the deleted documents count (ie. it is reindexing the same documents).

Please note that I am doing a synchronous reindex (no tasks) and that my index has manually-specified ids (numeric).

**Comment by nemphys** [comment]
I have made some progress, as I at least found a way to complete the operation successfully! 

If I set the dest.op_type to 'create' along with conflicts: 'proceed', everything works as expected and the target index ends up with the correct product count and 0 deleted documents. 

The weird thing is that in the reindex response, I get a huge number of 'version_conflicts', with the total always equal to created + version_conflicts.

Any ideas?

**Comment by nemphys** [comment]
I have finally found the cause of the issue and it apparently has nothing to do with the reindex API, but rather with the ES javascript client.

Apparently, the client does not respect the requestTimeout setting (it has a *hardcoded* 30s request timeout), so the reindex request was therefore timing out after 30s and (silently) triggering a retry (!), which in turn lead to chaos.

I am closing this and will report the issue to the JS client repo.
