### ISSUE TITLE
[Docs] Duplicate sentences in Add Index Alias

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/elasticsearch#69714]
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-add-alias.html

![Screenshot from 2021-03-01 15-18-16](https://user-images.githubusercontent.com/5576500/109517755-8125e600-7aa1-11eb-8e36-d42698a0a36e.png)

In the above page, the sentences inside the "Filter" section are duplicated (see screenshot.)

**Comment by jrodewig** [comment]
Closed by #69716. Thanks again @AndyHunt66!
