### ISSUE TITLE
Replace custom dependency verification with support provided by Gradle

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#69736]
We rolled our own dependency verification logic in our build which uses checksum files checked in to source control against JARs. This works fine enough but now that Gradle has [built-in support](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:checksum-verification) for this it doesn't make much sense for us to maintain our own bespoke solution.  We should migrate to using Gradle's capability here.

**Comment by pugnascotia** [comment]
@mark-vieira @breskeby have we done anything towards this?

**Comment by breskeby** [comment]
no we haven't. but its a good candidate for our backlog :)
