### ISSUE TITLE
Painless user methods as instance methods

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#69742]
~Arguments to execute and proxied variables (`x` is exposed when a script defines `getX` and/or `setX`) are not available in user functions.  This adds ceremony when creating user functions, as they must be passed in.~

~Exposing these as globals simplifies the implementation of the universal fields API (#61388) as well as reducing ceremony.~

~We will allow existing arguments to user functions with the same name to **shadow** the globals.  This avoids breaking existing scripts and incurring backwards compatibility costs.~

~As a follow up, we will deprecate shadowing as it's inconsistent with the painless variable model.~

Instead of global variables, we'll make user defined methods into instance methods, which is a simplier implementation and still helps with the universal fields API (#61388)

**Comment by princejha95** [comment]
Hi @stu-elastic 

I am very much interested to pick up this issue. Since i am new to Elastic Search community, can you please give me a brief info about this issue like which all classes do i need to take a look at in order to provide resolution for this issue ?

Any help would be appreciated.
