### ISSUE TITLE
Enable ES to support high performance shared storage

### ISSUE THREAD

**Issue by maosuhan** [elastic/elasticsearch#69769]
Nowadays, shared storage system and NAS technology developed a lot. According to alibaba cloud's PolarFS, they already developed high performance file system(https://www.vldb.org/pvldb/vol11/p1849-cao.pdf). With many modern technology introduced like RDMA and SPDK, the IO latency is very comparative to local nvme SSD. Also NAS is also an option with low IO latency and provide a compatible posix IO interface to program.
Cloud providers will probably offer such service in the future and many users can benefit from it.

Is there a possibility that ES will store all the realtime/historical data to shared storage like NAS. In such way, the benefits are listed below:
1. It is more flexible to adjust the compute and storage resource.
2. No shard replica process is needed because data reliability relies on NAS thus improve write throughput.
3. We can leverage the data lifecycle management provided by NAS to save costs.
4. Index segments can be generated outside of ES cluster in offline process and data is easily loaded in the cluster with shared storage system.
5. ES cluster can be set up in a more cloud native way.
6. Lucene files is exposed in NAS and it provide a possibility that they can be read by spark/presto/flink for big data processing.

**Comment by DaveCTurner** [comment]
Thanks for the ideas @maosuhan. We (the @elastic/es-distributed team) discussed this today. Elasticsearch is pretty much agnostic to its underlying filesystem: as long as your storage works correctly and reliably and performs well then you should be fine. That's a big caveat: these storage systems don't always work correctly or reliably or perform as well as advertised, but you seem willing to take that risk.

Items 4 and 6, regarding import/export of Lucene-level data, are not supported today but they are interesting ideas and this isn't the first time they have been suggested. They are also quite unrelated to the rest of your proposal. Would you open a separate Github issue for these points? That will let us gather feedback from the rest of the community on this front which helps us to prioritise against all the other things we're working on.

Apart from these two points, we think there's no other action to take here, so I am closing this issue.
