### ISSUE TITLE
:test:fixtures:krb5kdc-fixture:postProcessFixture failed

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69782]
**Build scan**: https://gradle-enterprise.elastic.co/s/2rxllrbennwkm

**Repro line**: None given, I tried `./gradlew :test:fixtures:krb5kdc-fixture:postProcessFixture`

**Reproduces locally?**: No (but not tried on ARM)

**Applicable branches**: Only seen on 7.x and ARM

**Failure history**: [Gradle Enterprise](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:test:fixtures:krb5kdc-fixture:postProcessFixture%27.%0A%3E%20assert%20confTemplate.exists()%0A%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20false%0A%20%20%20%20%20%20%20%20%20/dev/shm/elastic%2Belasticsearch%2B7.x%2Barm/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/peppa/krb5.conf.template&search.relativeStartTime=P90D&search.timeZoneId=Europe/London) indicates 3 failures in the last 90 days, all fairly recent and on ARM.

**Failure excerpt**:

```
Build file '/dev/shm/elastic+elasticsearch+7.x+arm/test/fixtures/krb5kdc-fixture/build.gradle' line: 27
assert confTemplate.exists()
       |            |
       |            false
       /dev/shm/elastic+elasticsearch+7.x+arm/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/peppa/krb5.conf.template
```

**Comment by jkakavas** [comment]
This seems to not be failing any more, there is no failure in the last 90 days. I'll close this down and we can re-open if need be
