### ISSUE TITLE
Various vagrant based packaging tests fail due to wrong Java version

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69789]
**Build scan**: https://gradle-enterprise.elastic.co/s/xzpxjweu5l7pe

**Repro line**: None given, I tried `./gradlew :qa:os:debian-8:distroTest.default-deb`

**Reproduces locally?**: Failed for different reason for me (I do not have `vagrant` installed)

**Applicable branches**: Only seen on 7.x

**Failure history**: [34 possibly-related failures in the last week](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Process%20%27command%20%27vagrant%27%27%20finished%20with%20non-zero%20exit%20value%201&search.relativeStartTime=P7D&search.timeZoneId=Europe/London)

**Failure excerpt**:

```
\| An exception occurred applying plugin request [id: 'elasticsearch.global-build-info'] |  
  | \| > Failed to apply plugin 'elasticsearch.global-build-info'. |  
  | \|    > Project requires Java version of 15 or newer but Gradle JAVA_HOME is 14
```

Unsure if related to https://github.com/elastic/elasticsearch/issues/69784 or not; apologies if this is a duplicate.

**Comment by davidkyle** [comment]
- Debian 9 https://gradle-enterprise.elastic.co/s/3ufvqmyoa6iss
- Oel (Oracle??) 7 https://gradle-enterprise.elastic.co/s/h6jdfmn7i7wh4
- Fedora 28 https://gradle-enterprise.elastic.co/s/ht27r4z7l642s
- SLES 12 https://gradle-enterprise.elastic.co/s/6qlg5rdz7f7q2

All across the 7.12 branch basically 

#69568 appears to be the culprit

**Comment by jkakavas** [comment]
This fails across master too for the same reason as stated above
> | Caused by: org.gradle.api.GradleException: Project requires Java version of 15 or newer but Gradle JAVA_HOME is 14

From today: 

https://gradle-enterprise.elastic.co/s/kakf7cpvv3zwg
https://gradle-enterprise.elastic.co/s/o4gs5qwgpgtms
https://gradle-enterprise.elastic.co/s/7nc5o6zofo6og
https://gradle-enterprise.elastic.co/s/hkp3b57e6qsak
https://gradle-enterprise.elastic.co/s/gajg5ybq632ji
https://gradle-enterprise.elastic.co/s/c3pvwg4anhtlg
https://gradle-enterprise.elastic.co/s/5zcfeaqn24lqi

**Comment by martijnvg** [comment]
Today's failures (this time only on the 7.x branch) caused by Java version mismatch:
* https://gradle-enterprise.elastic.co/s/u4uipdcjfvj7y
* https://gradle-enterprise.elastic.co/s/orovlcjtjftrk
* https://gradle-enterprise.elastic.co/s/wirnqvq3pl2tq
* https://gradle-enterprise.elastic.co/s/ebfftbluwpbeq
* https://gradle-enterprise.elastic.co/s/z6pkizhb3nrsm
* https://gradle-enterprise.elastic.co/s/swkhw2hpz2bsg
* https://gradle-enterprise.elastic.co/s/sq35dlfd3z72i

**Comment by BigPandaToo** [comment]
More from today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+platform-support-arm/os=ubuntu-1804-aarch64&&immutable/41/console

**Comment by mark-vieira** [comment]
We don't run this job anymore.
