### ISSUE TITLE
TransportInstanceSingleOperation retry fails if shard is null

### ISSUE THREAD

**Issue by GaelTadh** [elastic/elasticsearch#6978]
Around line 211 in TransportInstanceSingleOperation handleException in the ResponseHandler. If the node is null the retry will fail, this may have be caused due to the shard being moved to another node.

A log from a failed test is available at : https://gist.githubusercontent.com/GaelTadh/5528eddfddc4663ce0c9/raw/failed%20log

**Comment by clintongormley** [comment]
Long time since we've seen this. Closing
