### ISSUE TITLE
Running elasticsearch docker aarch64 on CentOS 8 throws docker-entrypoint error

### ISSUE THREAD

**Issue by liza-mae** [elastic/elasticsearch#69845]
When I try to run docker image: ```elasticsearch-8.0.0-SNAPSHOT-docker-image-aarch64.tar.gz``` on CentOS 8 aarch64 I am getting the following error: 

```
/usr/local/bin/docker-entrypoint.sh: line 10: /usr/bin/basename: cannot execute binary file: Exec format error
```

I can run the same image fine on Ubuntu 18.04 aarch64.

**Comment by mark-vieira** [comment]
This is the kind of error you'd see if you are trying to run an x86 binary on arm64 or vice versa. Couple of questions, first, where did you download that docker tarball from and second, how were you running CentOS (a VM)?

**Comment by liza-mae** [comment]
Yes I am aware of why I would see that kind of error, which is why I am confused.  

The systems for both Ubuntu and Centos say aarch64, however I am using AWS community AMIs as I don't  have access to any official AWS images.  Could that be the problem?

The docker tar ball is from release manager downloads.  Name: ```elasticsearch-8.0.0-SNAPSHOT-docker-image-aarch64.tar.gz``` 

ami-0683fe1b588fbba6c for CentOS 8 
ami-028e52edfeb33adb2 for Ubuntu 20.04

**Comment by mark-vieira** [comment]
I've made a note to try and reproduce this tomorrow.

**Comment by mark-vieira** [comment]
@liza-mae is this still an issue? I was just doing some work on aarch64 on CentOS yesterday and was able to run non-snapshot images (haven't tried the snapshots yet).

**Comment by liza-mae** [comment]
@mark-vieira yes it is still an issue on 8.0.0-SNAPSHOT

**Comment by pugnascotia** [comment]
We haven't been able to reproduce this and no one else has reported the same issue, so I hope you don' mind if I close this for now. Feel free to reopen it if you have more information that might help us diagnose the problem.
