### ISSUE TITLE
ES does not bind to interface specified in network.host

### ISSUE THREAD

**Issue by gholder** [elastic/elasticsearch#6986]
ES 1.2.2 binds to more interfaces than specified in ES/elasticsearch.yml.

Non-default contents of ES/elaticsearch.yml:

node.name: elasticsearch-me
network.host: zzz.zzz.zzz.150
http.host: zzz.zzz.zzz.150
script.disable_dynamic: true

ip addr for this machine:

: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: pub: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:a0:d1:e1:df:2c brd ff:ff:ff:ff:ff:ff
    inet xxx.xxx.xxx.71/17 brd xxx.xxx.xxx.255 scope global pub
    inet xxx.xxx.xxx.111/17 brd xxx.xxx.xxx.255 scope global secondary pub:dns-name1
    inet xxx.xxx.xxx.207/17 brd xxx.xxx.xxx.255 scope global secondary pub:dns-name2
    inet xxx.xxx.xxx.128/17 brd xxx.xxx.xxx.255 scope global secondary pub:dns-name3
    inet xxx.xxx.xxx.214/17 brd xxx.xxx.xxx.255 scope global secondary pub:dns-name4
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:a0:d1:e1:df:2d brd ff:ff:ff:ff:ff:ff
4: it1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:1b:21:97:37:98 brd ff:ff:ff:ff:ff:ff
5: it2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:1b:21:97:37:99 brd ff:ff:ff:ff:ff:ff
6: eth1.2@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 00:a0:d1:e1:df:2d brd ff:ff:ff:ff:ff:ff
    inet zzz.zzz.zzz.59/24 brd zzz.zzz.zzz.255 scope global eth1.2
    inet zzz.zzz.zzz.1/24 brd zzz.zzz.zzz.255 scope global secondary eth1.2:dns-name5
    inet zzz.zzz.zzz.150/24 brd zzz.zzz.zzz.255 scope global secondary eth1.2:dns-name1
    inet zzz.zzz.zzz.105/24 brd zzz.zzz.zzz.255 scope global secondary eth1.2:dns-name2
    inet zzz.zzz.zzz.92/24 brd zzz.zzz.zzz.255 scope global secondary eth1.2:dns-name3
7: eth1.3@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 00:a0:d1:e1:df:2d brd ff:ff:ff:ff:ff:ff
    inet yyy.yyy.yyy.59/24 brd yyy.yyy.yyy.255 scope global eth1.3
    inet yyy.yyy.yyy.1/24 brd yyy.yyy.yyy.255 scope global secondary eth1.3:dns-name5
    inet yyy.yyy.yyy.150/24 brd yyy.yyy.yyy.255 scope global secondary eth1.3:dns-name1
    inet yyy.yyy.yyy.105/24 brd yyy.yyy.yyy.255 scope global secondary eth1.3:dns-name2
    inet yyy.yyy.yyy.92/24 brd yyy.yyy.yyy.255 scope global secondary eth1.3:dns-name3

netstat -tupan | grep elasticsearch-pid:

tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      2756/java
tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN      2756/java
tcp        0      0 xxx.xxx.xxx.71:38883    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38887    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38888    zz.zzz.zzz.214:9300     ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38887    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38890    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38879    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38880    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38889    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38881    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38888    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38885    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38878    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38890    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38881    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38883    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38879    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38884    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38884    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38886    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38882    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38889    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38878    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38885    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 zzz.zzz.zzz.214:9300    xxx.xxx.xxx.71:38880    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38886    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
tcp        0      0 xxx.xxx.xxx.71:38882    zzz.zzz.zzz.214:9300    ESTABLISHED 2756/java     
udp        0      0 0.0.0.0:54328           0.0.0.0:*               2756/java       

Same results for setting network.host to 127.0.0.1, or _eth1.2_

I'm a little surprised that it doesn't bind to zzz.zzz.zzz.150.

**Comment by clintongormley** [comment]
Fixed in 2.0
