### ISSUE TITLE
Rolling upgrade tests failing on Windows

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#69933]
The tests are failing because `path.repo` is set to `C:\Users\....` and the `\U` is interpreted as the beginning of a Unicode character code. I believe that backslashes in Windows paths need to be escaped as `\\`.

**Build scan**: 
https://gradle-enterprise.elastic.co/s/ef5zqt7vow5z4
https://gradle-enterprise.elastic.co/s/i5m4hwzzriz5e

**Repro line**: n/a

**Reproduces locally?**: No local Windows environment

**Applicable branches**: at least master and 7.12

**Failure history**: At least twice on 3/3/21

**Failure excerpt**:

```

:x-pack:qa:rolling-upgrade:v7.13.0#oldClusterTest FAILED |  
-- | --
  | Exec output and error: |  
  | \| Output for cmd:Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: MarkedYAMLException[while scanning a double-quoted scalar |  
  | in 'reader', line 9, column 14: |  
  | path.repo: [ "C:\Users\jenkins\workspace\elas ... |  
  | ^ |  
  | expected escape sequence of 8 hexadecimal numbers, but found: sers\jen |  
  | in 'reader', line 9, column 19: |  
  | path.repo: [ "C:\Users\jenkins\workspace\elastic+e ... |  
  | ^ |  
  |   |  
  | at [Source: (sun.nio.ch.ChannelInputStream); line: 9, column: 13]]; nested: ScannerException[while scanning a double-quoted scalar |  
  | in 'reader', line 9, column 14: |  
  | path.repo: [ "C:\Users\jenkins\workspace\elas ... |  
  | ^ |  
  | expected escape sequence of 8 hexadecimal numbers, but found: sers\jen |  
  | in 'reader', line 9, column 19: |  
  | path.repo: [ "C:\Users\jenkins\workspace\elastic+e ...
```

**Comment by danhermann** [comment]
Es-delivery was my best guess for this issue. Please reassign if I got the team wrong.

**Comment by mark-vieira** [comment]
Looks like this was introduced by https://github.com/elastic/elasticsearch/pull/69788. I've opened #69946 to fix.
