### ISSUE TITLE
Investigate null Settings in mappers

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#6993]
In #6967 Adrien mentioned he was concerned about this, as e.g. the NumberFieldMapper has to do a null check, but it seems to me its currently designed to be null (its marked Nullable etc in some related apis). Maybe we can avoid this?

**Comment by rjernst** [comment]
I fixed this in a later change. Field mappers no longer allow null index settings (or even empty). They always expect the index_created_version setting.
