### ISSUE TITLE
Avoid Needless  notifyAll() in LocalCheckpointTracker.updateCheckpoint() which slow down the indexing speed

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#69963]
Elasticsearch version : 7.9.1

**Description**
I analyze the indexing process, and find that `this.notifyAll()` in `LocalCheckpointTracker.updateCheckpoint()` cost too much time, but I find it needless.

 the commit about the code says that:
>  // notifies waiters in waitForProcessedOpsToComplete

but the function `waitForProcessedOpsToComplete` seems useless, I don't find any place to call it.

**Comment by kkewwei** [comment]
I analyze the indexing process, and find that `this.notifyAll()` in LocalCheckpointTracker.updateCheckpoint() cost too much time, but I find it needless.

 the commit about the code says this:
>  // notifies waiters in waitForProcessedOpsToComplete
but `waitForProcessedOpsToComplete` seems useless.

**Comment by original-brownbear** [comment]
It's hard to tell what the exact impact of this call is (I'm not sure how exact profiling will be for this kind of thing) but I agree, this was only used in tests and we can simplify the code => I opened https://github.com/elastic/elasticsearch/pull/70070
