### ISSUE TITLE
DatabaseRegistryTests failing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#69986]
**Build scan**:
https://build-stats.elastic.co/goto/d978fe4b4c368da8841ff006472c48df

**Repro line**:
```
./gradlew ':modules:ingest-geoip:test' \
  --tests "org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testRetrieveDatabase" \
  -Dtests.seed=BE6250BEEA8601F1 -Dtests.security.manager=true
  -Dtests.locale=es-NI -Dtests.timezone=Asia/Hovd -Druntime.java=16 -Dtests.fips.enabled=true
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:
![image](https://user-images.githubusercontent.com/215970/110004272-401e1380-7ce5-11eb-9a44-73e27a091967.png)

https://build-stats.elastic.co/goto/d978fe4b4c368da8841ff006472c48df

**Failure excerpt**:
```
Never wanted here:
-> at org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testRetrieveDatabase(DatabaseRegistryTests.java:233)
But invoked here:
-> at org.elasticsearch.ingest.geoip.DatabaseRegistry.lambda$retrieveDatabase$12(DatabaseRegistry.java:304)
```

**Comment by martijnvg** [comment]
It looks like what all these failures have in common is that fips is enabled and the tests run with jdk 16. I will try to reproduce under these conditions.
