### ISSUE TITLE
RestHighLevelClientTests.testApiNamingConventions is littered with exclusions

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70041]
We have a unit test `RestHighLevelClientTests.testApiNamingConventions` whose job it seems is to ensure that we adhere to a naming convention between our REST API specifications (JSON) and the HLRC methods. One issue is that due to some historical reason, we [don't validate against any of the x-pack APIs](https://github.com/elastic/elasticsearch/blob/5341a8c4196d326e0e6d75fab96450e14d3e5b16/client/rest-high-level/src/test/java/org/elasticsearch/client/RestHighLevelClientTests.java#L908-L933) so of course, over time, the naming conventions for those are completely out of whack.

As part of the work related to #69392 we will be consolidating core and x-pack REST API specs. This is causing this [test to fail](https://gradle-enterprise.elastic.co/s/r2p6dakn54w4c/tests/:client:rest-high-level:test/org.elasticsearch.client.RestHighLevelClientTests/testApiNamingConventions#1) because now it's attempting to validate the x-pack APIs as well. The main reason being is because the naming conventions don't match. Some are very high level, for example mapping `machine_learning` to `ml`, but others are just wrong such as `SecurityClient.clearPrivilegesCache` vs `security.clear_cached_privileges`. Of course these have diverged over the years since we haven't been enforcing the conventions. Question is, what do we continue to do?

1. Mute this test entirely since the list of exceptions is so broad it's providing little benefit and we plan on introducing a new HLRC anyhow.
2. Add all the x-pack APIs that don't match the convention to an exclusion list.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
