### ISSUE TITLE
Indexing doc to index with "index_phrase" mapping causes illegal argument exception

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#70049]
**Elasticsearch version** : 7.11.x (Docker image)
**Plugins installed**: N/A
**JVM version**: Bundled
**OS version**: Linux (Docker image)

**Description of the problem including expected versus actual behavior**:

Since 7.11.0, indexing a document where the index mapping includes "index_phrases" fails with an illegal argument exception.

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "position overflowed Integer.MAX_VALUE (got posIncr=1 lastPosition=0 position=-1) for field 'tags._index_phrase'"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "position overflowed Integer.MAX_VALUE (got posIncr=1 lastPosition=0 position=-1) for field 'tags._index_phrase'"
  },
  "status" : 400
}

```

**Steps to reproduce**:

1. Create an index with the following mapping
```
PUT test
{
  "mappings": {
    "properties": {
      "tags": {
        "index_phrases": true,
        "type": "text"
      }
    }
  }
}
```

2. Index a document
```
POST test/_doc
{
  "tags": [
    "bad",
    "Prio 1"
  ]
}
```

**Expected result:** The document is indexed.
**Actual Result:** Illegal argument exception.

I've tested the same steps on a 7.10 version of Elasticsearch and the document is indexed correctly.

Relates to https://github.com/elastic/elasticsearch-net/issues/5399

**Comment by romseygeek** [comment]
This might be to do with multi-valued inputs, I don't think we have specific tests for those.  Do you have a full stack trace for this error @stevejgordon?

**Comment by romseygeek** [comment]
Never mind, I've reproduced the error.  Something to do with the single-valued field is messing up positions.
