### ISSUE TITLE
Recover recent indices first

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#7006]
For logging and analytics where writes happen in "current" (this day, this hour) index it is preferred to see fresh indices recovered first and old indices recovered last. Currently indices are recovered in random order.

With this option during restart queue with updates could be paused for 1 minute instead of 20-30 in our setup.

**Comment by jpountz** [comment]
This has been implemented, see https://www.elastic.co/guide/en/elasticsearch/reference/2.0/recovery-prioritization.html
