### ISSUE TITLE
Rollup action bug unable to rollup date_nanos metrics

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#70161]
Rollup action is supposed to support date_nanos as a metric for rolling up. Instead, there is a field formatter conflict when resolving the field.

reproduction:

```
// Map a date_nanos field.
PUT my-index-000001
{
  "mappings": {
    "properties": {
      "my-date-nanos-field": {
        "type": "date_nanos" 
      }
    }
  }
}

// Index a document with the date_nanos field.
POST my-index-000001/_doc
{ 
  "@timestamp": "2099-11-15T13:12:00",
  "my-date-nanos-field": "2015-01-01T12:10:30.123456789Z"
}

// Attempt to roll up the index with the date_nanos field as a metric.
POST my-index-000001/_rollup/rollup-my-index-000001
{
  "groups": {
    "date_histogram": {
      "field": "@timestamp",
      "calendar_interval": "1d"
    }
  },
  "metrics": [
    {
      "field": "my-date-nanos-field",
      "metrics": [
        "min",
        "max"
      ]
    }
  ]
}
```

exception:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "trying to convert a known date time formatter to a nanosecond one, wrong field used?"
      }
    ],
    "type" : "exception",
    "reason" : "Unable to rollup index [my-index-000001]",
    "caused_by" : {
      "type" : "exception",
      "reason" : "[my-index-000001/9DveCFw8RR67S2tul3Qt_w][[my-index-000001][0]] org.elasticsearch.action.support.broadcast.BroadcastShardOperationFailedException:",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "trying to convert a known date time formatter to a nanosecond one, wrong field used?"
      }
    }
  },
  "status" : 500
}
```

**Comment by jimczi** [comment]
> Rollup action is supposed to support date_nanos as a metric for rolling up.

I don't see why ? We use doubles for metrics so that doesn't work out of the box. Can we disable `date_nanos` as metrics instead ? I am not even sure that handling `date` is required.

**Comment by talevy** [comment]
I believe that is how things were? I see no reason to support `date` or `date_nanos` as metrics either. I can update accordingly

**Comment by not-napoleon** [comment]
@jimczi - Does this still need work?  Do we just need to update the docs?  Can we close it?

**Comment by jrodewig** [comment]
> @jimczi - Does this still need work? Do we just need to update the docs? Can we close it?

I removed the docs for the refactored rollup API + ILM action with https://github.com/elastic/elasticsearch/pull/70885 as it seemed unlikely that we'll move forward with that functionality. I don't think updating the docs is likely the fix here.
