### ISSUE TITLE
Provide a declarative way to manage plugins

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#70219]
Today management of plugins is done through a CLI tool that exposes `list`, `install`, and `remove` commands. End-users and orchestration systems must use these tools to manage the installation and removal of the appropriate plugins, including addressing our existing limitation that plugins are version-locked to a patch version of Elasticsearch. These requirements lead to a poor end-user experience, and complexity for orchestration systems.

A simpler approach would be to enable plugins to be managed through a configuration.

For example, one way to do this would be via a declarative list. You could imagine a user-managed `elasticsearch-plugins.yml` that lists the plugin that an end-user or orchestration system wants installed (this list could be our usual syntax today, a name of an official plugin, Maven coördinates, or a URL). In the Elasticsearch startup script, we could diff this list with the installed plugins, remove those that are not listed, and install those that are. This declarative configuration file could include options like `batch: true` to install without inspecting permissions, and various other options for controlling how plugins are installed (for example, perhaps we need to enable setting proxy system properties here).

There are, of course, several details to work out (e.g., how do we efficiently obtain the name of non-official plugins for comparing to the list of installed plugins) but the purpose of this issue is to encourage us to investigate ways to install plugins declaratively.

**Comment by anyasabo** [comment]
We discussed a narrower way of achieving a similar end a bit ago in https://github.com/elastic/elasticsearch/issues/61385
