### ISSUE TITLE
New authentication check for search functions that bypass TermDocs

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#70221]
The forthcoming [auto-complete API ](https://github.com/elastic/elasticsearch/pull/66452)is an example of a search function that returns responses derived purely from looking at Lucene's index (via TermsEnum) and thus avoids any existing DLS authorisation checks wrapped around Lucene's TermDocs. (It also seems to avoid any FLS checks).
It deliberately avoids accessing postings to be fast (trying to return suggestion responses before users make another keystroke).

To implement this securely I was forced to add[ custom security logic in my data collection logic](https://gist.github.com/markharwood/dbf73480da3093caaa5f7f862aba553a) that runs on data nodes and detects if FLS or DLS is enabled for the current user. If it is then I avoid accessing that field/index.
This is messy, runs later than is ideal (on the data node) and has maintenance concerns. Ideally there'd be a declarative way of filtering whole indices on the coordinating node if the class with my coordinating logic could declare up-front that it can leak potentially sensitive terms without running them past doc postings. This would be similar to the existing rewriting that goes on with `IndicesRequest.Replaceable` using a new form of marker interface which declares the fields accessed in an unsafe fashion. If the current user has any DLS/FLS restrictions on the field(s) in question then the access is blocked at the coordinating node by the security framework not my custom code.

**Comment by ywangd** [comment]
IIUC, the proposed behaviour is to iterate through all combinations of requested indices and field and remove any combinations that have applicable DLS or FLS. So the response will only contain terms from those indices/field that user actually has access? IIUC, it seems the existing [FieldAndDocumentLevelSecurityRequestInterceptor](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/interceptor/FieldAndDocumentLevelSecurityRequestInterceptor.java) is the right place for the above logic. We may need it for more than just the coordinating node, e.g. for cross-cluster search, when roundtrip is minimised, the shard level request is sent directly to the remote node and needs to be filtered there.

**Comment by markharwood** [comment]
Thanks for the feedback, @ywangd - I'll take a look at FieldAndDocumentLevelSecurityRequestInterceptor  and report back

**Comment by markharwood** [comment]
I tried adding a subclass of FieldAndDocumentLevelSecurityRequestInterceptor to add the logic and it looks to be missing some required context.
There are two reasons why I would want to skip an index:
1) _Any_ DLS is enabled on the index or
2) the specific field I'm looking at has FLS enabled and denies me access.

1) is catered for with FieldAndDocumentLevelSecurityRequestInterceptor - I can override `disableFeatures` and be told if DLS is enabled for the indices I have declared I'm accessing.
2) however is an issue because the `disableFeatures` API doesn't tell me which fields I can't see - only that FLS is enabled.

My custom logic was originally taken from `ResizeRequestInterceptor`. I presumably could shift my logic out of my TransportTermEnumAction into a new subclass of RequestInterceptor and register it in `Security.createComponents()`.

However, rather than creating new custom filtering classes like this I wanted to gauge if there was any interest in taking the existing IndicesRequest/Replaceable rewriting contract and expanding it to cover cases like mine. If my use case is too much of an edge case then I'm happy to implement the necessary filtering logic - would be good to get some input on how best to package it though. I'd ideally like to move my search logic to `server` and not have the xpack security API dependencies.

**Comment by ywangd** [comment]
@markharwood Here are my response to your comments based on my understandings. I think I may not fully understand your proposal and the context. Happy to jump on a high bandwidth conversation if needed. Thanks!

> 2) however is an issue because the disableFeatures API doesn't tell me which fields I can't see - only that FLS is enabled.
>
True, the current signature of the `disableFeatures` method is non-ideal for getting detailed information about DLS/FLS. I had similar issue in this draft PR (#70191). So I [changed](https://github.com/elastic/elasticsearch/pull/70191/files#diff-feafa240e2df4413a0a559f0c39e7000f42bea0f241c0c0ecc0c82e0a8ab189e) the method to take a Map of `IndexAccessControl` which allows you to inspect detailed permissions on each index and field. The draft PR itself will likely need a lot more time to finalise. But this particular update to the `disableFeatures` method could be something for you to adpot if needed.

> However, rather than creating new custom filtering classes like this I wanted to gauge if there was any interest in taking the existing IndicesRequest/Replaceable rewriting contract and expanding it to cover cases like mine.
>
Could you please be more specific about this proposal? I don't quite follow and it's probably my lack of understanding on how search part works. But even after you expand the `Replaceable` to cover your case, you still need a caller for this new contract? Where will this call site be located? Since this is security related logic, ideally it should be alongside other security code. To me, the `RequestInterceptor` seems to be a natural fit.

> I'd ideally like to move my search logic to server and not have the xpack security API dependencies.
>
The search itself can stay in the sever package, similar to `SearchRequest` and `TransportSearchRequest`. The filtering logic is in xpack, but the code in `server` package does not have to be aware of it. The `server` package code also does not need depend on xpack security other than providing public methods for mutating the indices and fields of the request.

**Comment by markharwood** [comment]
>I changed the method to take a Map of IndexAccessControl which allows you to inspect detailed permissions on each index and field. 

Sounds like that would help this case, thanks.

>To me, the RequestInterceptor seems to be a natural fit.

That certainly would work.

> Could you please be more specific about this proposal?

My understanding was there is already some in-place policing of requests at the coordinating node which filters indices based on user permissions. This avoids needless trips to data nodes when the authorisation rules are coarse-grained and at the index level.   For finer-grained rules (DLS/FLS) the requests must currently go to the data nodes where data access is policed by wrapping low-level Lucene classes that access the data.  
My new autocomplete API accesses the `TermEnum` part of Lucene (lists of terms in the index) which are not wrapped by the security framework and therefore bypass the fine-grained rules like DLS which wait for my code to try access `TermDocs` (lists of docs that contain a term). Returning data directly from TermEnum is therefore an unsafe thing for an API to do and if an API request could declare that it does this when presented at the coordinating node, the security framework could choose to deny access to that index in the same way it currently does if the user is denied access to a whole index. Something like this addition to IndicesRequest which can be over-ridden:

        /**
         * List of fields the request can return data from in ways not locked down by data node's security wrappers
         */
         default String [] getFieldNamesAccessedInUnsafeManner(String index) {
                 return null;
           }

Maybe the auto-complete is a one-off function that doesn't warrant this sort of change to the security framework but there may be other request types to consider too (any additions @jimczi ?). Basically anything that returns raw terms and doc counts that are held in the TermEnum in the Lucene index without accessing TermDocs.

**Comment by ywangd** [comment]
@markharwood Thanks a lot for the extra explanation!

IIUC, your idea is as the follows:
1. Adding a new interface or a new method to `IndicesRequest` which returns the list of fields that are not accessed through the `SecurityIndexReaderWrapper` (i.e. unsafe field access).
2. Leverage the above information to filter out indices that have unsafe field access. Your question is whether this could happen as part of the code that leads to a call of `IndicesRequest#Replaceable#indices`.

In the previous comment, you also said:
> I'd ideally like to move my search logic to server and not have the xpack security API dependencies.

I think it is *not* possible for item 2 to live outside of xpack, or more specifically, this logic has to live inside the domain of the security code. In security code, index filtering/rewriting already happens inside `RBACEngine#resolveAuthorizedIndicesFromRole`. In theory, new logic can be hooked into this method to filter out indices that have unsafe field access. I assume this is what you mean by "there is already some in-place policing of requests at the coordinating node which filters indices based on user permissions"?

The alternative, as I suggested initially, is to have the new logic in a `RequestInterceptor`. Based on my current understanding, I think `RequestIntercetpor` is still a better fit for following reasons:

1. The new interface/method is equally useful for both approaches.
2. Current code computes `IndicesAccessControl` for DLS/FLS after `RBACEngine#resolveAuthorizedIndicesFromRole`. So hooking into `resolveAuthorizedIndicesFromRole` will be a much bigger change compare to using an interceptor
3. The interceptors run after `resolveAuthorizedIndicesFromRole`, but they run on the coordinate node as well. If your intention is to avoid "needless trips to data nodes", a RequestInterceptor can serve for this purpose too.

> For finer-grained rules (DLS/FLS) the requests must currently go to the data nodes where data access is policed by wrapping low-level Lucene classes that access the data.

This is true when actually "accessing" the data of the index, but *not* for figuring out what the DLS/FLS permission should look like for an index (`IndicesAccessControl`). This can be and is done on the coordinate node and (I think) is all we need for `TermEnum`.

**Comment by albertzaharovits** [comment]
@markharwood As I understand it, the new ES terms enum API can't currently work on indices that are protected with DLS, so Security should reject such requests. Please correct me if this is not accurate.
If that's accurate, as has been discussed already, I also think **a request interceptor is best suited for this type of logic**; it has access to the DLS/FLS model which also contains the accessed indices.

As for FLS, I would boldly put it in the same basket with DLS and reject the request if the new API accesses indices that are protected with FLS only, even if technically it can be implemented. I think it's easier to explain and document it this way.
But to implement FLS-only authz, I think it can be made to work in the current authz logic. In `AuthorizationService#handleIndexActionAuthorizationResult` https://github.com/elastic/elasticsearch/blob/ac5dc6a4694cdafadabc7b9fc10fff3bbc952641/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java#L312-L361
we already have custom handling for request types that need "extra" authz (create index and bulk index). I would suggest we handle the new request there, and only reject it if the FLS-only permission denies fields from the request. As a matter of fact this logic here can handle the DLS thing as well, I don't find it particularly egregious (this whole matter is an exception and so there is a fork in the authz code for it).

**Comment by markharwood** [comment]
Apologies for the lack of update here. The terms enum API has evolved a little lately in terms of auth.
Currently we have logic based on this pseudo-code: 
```
    If  DLS enabled
        set allowAccessToIndexTerms = false
        for all roles current user has
               parse and call "rewrite" on DLS query for role
                  if rewritten DLS query == "match_all" query type
                       set allowAccessToIndexTerms = true
```                  
                       
The thinking behind this is that the assumption is a big use of DLS will be on datastreams and permissions will be associated with certain indices that fall under an umbrella pattern that people will query e.g. users query `logs/_search` but may not have access to one of the underlying indices e.g. `IDS_log` but weblogs etc  are allowed. Technically this is implemented using a cheap DLS filter e.g. one that queries a `constant_keyword` field that holds the same value for every document in that index. In that situation the "Document Level Security" is actually behaving more like an index-level security rule - enabling or denying access to an entire index using a query on this field rather than an index name. This behaviour can be detected when the DLS role query e.g. `myConstantKeywordField == "foo"` rewrites itself to a match_all query. At that point we know all docs in that index are fair game and we don't have to worry about leaking data. See the TransportTermsEnumAction class in [this PR](https://github.com/elastic/elasticsearch/pull/66452) and the "canAccess" method

**Comment by markharwood** [comment]
Closing because we implemented what we consider to be specialised logic for the terms_enum API detailed in my last comment
