### ISSUE TITLE
Fetch fields API inconsistent with doc_values for binary fields

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70244]
We generally expect the `fields` API to be consistent with `docvalue_fields` except for `text` fields. But for `binary` fields the `docvalue_fields` API doesn't return any trailing padding characters in the base64 results. But the `fields` API returns exactly what is in the `_source`, trailing `=`s and all.

Interestingly, we can't parse the results of `docvalue_fields`. When we go to parse the binary field we call `JsonParser.getBinaryValue` which fails on base64 without the padding saying "Unexpected end of base64-encoded String: base64 variant 'MIME-NO-LINEFEEDS' expects padding (one or more '=' characters) at the end". It looks like there are some values where either `JsonParser` doesn't need the padding.

**Comment by nik9000** [comment]
A few of us got together and said "we should be able to parse what we return here". I mean, we should be able to parse what we return from most places. And this is one of them. We didn't have any strong opinion on whether its right to fix it by allowing base64 without the padding or by always emitting the padding. [This](https://stackoverflow.com/a/26632221/14054853) wonderful stackoverflow answer seems to think the padding is only needed if you stick strings together like you'd do in a simple protocol. We use base64 inside of JSON so it *sounds* like it'd be safe to parse without the padding....

**Comment by mayya-sharipova** [comment]
It looks to me the easiest strategy is to make `docvalue_fields` fields to output decoded binary values [with a padding](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/DocValueFormat.java#L168).
We can treat the previous behaviour as a bug as we were not able to parse what we output.  

WDYT @nik9000 ?

**Comment by nik9000** [comment]
Makes sense to me.
