### ISSUE TITLE
Master election and discovery in ZenDiscovery module should be pluggable

### ISSUE THREAD

**Issue by hgesserit** [elastic/elasticsearch#7025]
We are implementing a custom master election strategy, but still want to use the zen module  for other actions such as fault detection, sending join requests, processing cluster state, etc.  There should be a way to pass in custom implementations of ElectMasterService and findMaster() to enable reuse of code without requiring copy-pasted code in custom discovery plugins.

**Comment by clintongormley** [comment]
No feedback in over a year. Closing
