### ISSUE TITLE
Dynamic: false in Production Mode

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#70257]
When going from development to production, it is obviously important to remember to setup the production cluster the same as the development one. However, it is not uncommon for production deployments to be inherently more complex (e.g., bigger) than their development variants.

One of the most common mistakes is to forget to bring templates forward, such as from Filebeat installations, and to kick off writing. Similarly, the mistakes in development often do not have the same impact as mistakes in production, such as a wildly dynamic index mappings.

With the introduction of runtime fields, we should consider making index mappings default to `dynamic: false` when running in production mode. This should save users from obvious mistakes and make it pretty clear that something is wrong immediately, rather than days, weeks, or months later.

If done, this would make correcting such mistakes simple:

- Implement runtime fields as a temporary solution
- When using ILM, roll the index to one with appropriate mappings
- Reindex the defunct data into an aliased index (or just remove the alias from it and push it into the corrected version).

As it stands, dynamic mappings can be painful to unravel. They serve a terrific getting started experience, but a painful production one for those unaware. The mappings explode and it becomes hard for inexperienced admins to determine what is and is not needed. This would also serve as a secondary benefit for such admins, in that it would require teams setting up indexes to provide templates for production scenarios, which experience makes obvious but inexperience does not.

**Comment by javanna** [comment]
Thanks for bringing this up, we discussed this with the team and we agreed that we should not change the default dynamic behaviour.  It would be a big behavioral change which we don't think is justified. Runtime fields are now available and allow to make changes after the data has been ingested, but that does not mean that schema on read becomes our default. Users are free to pick schema on read over schema on write, or a combination of the two which is extremely flexible. There is no default that will fit every single user: `dynamic:true` has downsides, but we think that the best default for the time being is still "fast by default".
