### ISSUE TITLE
Support RFC 6902 style PATCH updates

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#7030]
It would be nice to have a "patch language" that can be used to update documents, or in the `transform` API without using scripting.

**Comment by iohannis** [comment]
Also looking for a solution to this, having an index with rental properties availability data (as nested objects part of the property) that we update multiple times daily. Question is how we replace the array of nested objects with new ones, so the field values are not simply merged (keeping obsolete availability dates for the properties)? 

I have been working just about a month with implementing ElasticSearch, and just now ran into this issue. I cannot find anything in the documentation, and this and the linked issues are the closest to what I am looking for. Any suggestion would be very welcome - even if it's a workaround.

**Comment by vishalshah-org** [comment]
@clintongormley a bit curious why scripting isn't a better fit for advanced patching/merging needs? this would help keep the update api simpler, this would allow u guys to move forward with the simpler use cases folks want - ex #7332 and #5291... Just a thought. I do think however a patch language would be cool..

**Comment by clintongormley** [comment]
@vishalshah-org scripting obviously allows you to do whatever you want, which is fine.  That said, scripting today requires you to add a script to every node, which is quite clumsy.  It'd be nice to have a simple patch language that doesn't require you to expose scripting.

**Comment by clintongormley** [comment]
I think improving scripting (#13084) is a better idea than trying to invent a patch language in JSON. Closing
