### ISSUE TITLE
Improve human-readability of ILM timing error message

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#70336]
In https://github.com/elastic/elasticsearch/pull/70089 we added guardrails to protect against ILM policies being created with phase timings that would result in phases running out of order.

For example, let's say the user tries to save a policy configured with a the warm phase that runs 3 days after rollover, a cold phase that runs 2 days after rollover, and a delete phase that runs 1 day after rollover. The API would reject this policy with this error:

`
phases [cold,delete] configure a [min_age] value less than the [min_age] of [3d] for the [warm] phase, configuration: {cold=2d, delete=1d}
`

The UI team hasn't budgeted time to replicate this error-checking logic in the UI, so for the time being we'll surface the API error directly to the user. Can we make it more human-readable? For example:

`
Your policy is configured to run the cold phase (min_age: 2 days) and the delete phase (min_age: 1 day) before the warm phase (min_age: 3 days). Change the phase timing so that the phases will execute in the order of hot, warm, then cold.
`

CC @dakrone @debadair @jloleysens

**Comment by cjcenizal** [comment]
For reference, here are some guidelines that @gchaps and other writers have prepared for errors in the UI.

![image](https://user-images.githubusercontent.com/1238659/110851991-a4515200-8266-11eb-8252-d2ef43d22628.png)

**Comment by cjcenizal** [comment]
CC @jethr0null @jakelandis

**Comment by Esduard** [comment]
@cjcenizal I made a new message error that is almost identical to your request. I also had some fun trying to find a way to make the proper text depending on the number of phases.
