### ISSUE TITLE
Add Per thread memory allocations in hot_threads API

### ISSUE THREAD

**Issue by easyice** [elastic/elasticsearch#70345]
In a aggregation busy cluster, When then JVM GC has a large  overhead   , all of the query may be have a  large latency, But the slow log cannot find out which query  used the much memory, Because all queries are slow when the node in GC STW, So we can get the allocation during aggregation or other  operation,

This can be [getCurrentThreadAllocatedBytes(long id)](https://docs.oracle.com/en/java/javase/14/docs/api/jdk.management/com/sun/management/ThreadMXBean.html#getCurrentThreadAllocatedBytes())  API , Returns an approximation of the total amount of memory, in bytes, allocated in heap memory for the thread with the specified ID.

we can add this allocated bytes in two samples of hot_thread API, find out which thread allocated many memory:
````
curl ":9200/_nodes/hot_threads?type=mem&interval=1s"                                                                                                           ✘ INT 11:20:05
::: {node-1}{piPTqSeQQOiTYEi6BLCUKw}{YLyoYHhvQViKvvJkoBSNeg}{127.0.0.1}{127.0.0.1:9300}{dilm}{ml.machine_memory=34359738368, xpack.installed=true, ml.max_open_jobs=20}
   Hot threads at 2021-03-10T03:20:09.471Z, interval=1s, busiestThreads=3, ignoreIdleThreads=true:

    0.1% (3482944 out of 5368709120) mem usage by thread 'elasticsearch[node-1][search][T#20]'
     10/10 snapshots sharing following 18 elements
       java.base@13.0.2/java.util.ArrayList$ListItr.add(ArrayList.java:1064)
       app//org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.addEmptyBuckets(InternalDateHistogram.java:430)
       app//org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.reduce(InternalDateHistogram.java:455)
       app//org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:168)
       app//org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:116)
````

For aggregations in the query, we can call getCurrentThreadAllocatedBytes in QueryPhase before aggregations execute, and add in TaskInfo, in this way, we can get  how much memory allocated for the running search task in _Task API, add an **thread_allocated_bytes** field for instance:

````
"tasks" : {
    "..." : {
      "node" : "...",
      "id" : ...,
      "type" : "...",
      "action" : "...",
      "description" : "...",
      "start_time_in_millis" : ...,
      "running_time_in_nanos" : ...,
      "cancellable" : ...,
      "headers" : { },
      "thread_allocated_bytes" : 0,
      "thread_allocated_bytes_sum" : 10356376,
      "children" : [
        {
          "node" : "...",
          "id" : ...,
          "type" : "...",
          "action" : "...",
          "description" : "...",
          "start_time_in_millis" : ...,
          "running_time_in_nanos" : ...,
          "cancellable" : ...,
          "parent_task_id" : "...",
          "headers" : { },
          "thread_allocated_bytes" : 5088512
        },
        {
          "node" : "...",
          "id" : ...,
          "type" : "...",
          "action" : "...",
          "description" : "...]",
          "start_time_in_millis" : ...,
          "running_time_in_nanos" : ...,
          "cancellable" : true,
          "parent_task_id" : "...,
          "headers" : { },
          "thread_allocated_bytes" : 3080304
        },
    }
}
````

I did it on my local branch，And Compare the results of the Virtual VM，it looks right

**Comment by easyice** [comment]
We are using Elasticsearch in online service(Advertising system)，it's very sensitive to query latency. When query latency increases significantly, it's very difficult to find out which query is causing the problem，this feature will help us find out them. If this is reasonable,i can submit a pr, thanks!

**Comment by jtibshirani** [comment]
> When query latency increases significantly, it's very difficult to find out which query is causing the problem

It can certainly be tricky to work backwards from `hot_threads` to the source of the problem! We support passing a special header `X-Opaque-Id` so that clients can tag requests with context information. The header is surfaced in the search slow logs and tasks output (https://www.elastic.co/guide/en/elasticsearch/reference/7.13/tasks.html#_identifying_running_tasks). I just opened an issue suggesting we could add it to the `hot_threads` output too: https://github.com/elastic/elasticsearch/issues/74580. I'm curious if this would help in your case, or if it doesn't address what you need?

**Comment by easyice** [comment]
yeah, we have added X-Opaque-Id on  request header, i mean than ,  when the big queries is running, It causes small queries to slow down as well. so , we see that all queries are slowing down, so we cannot find big queries by X-Opaque-Id

**Comment by easyice** [comment]
Update:  Thanks @jtibshirani

**Comment by grcevski** [comment]
Hi @easyice, 

We have now merged both the master and the 7.x version of this issue. Please let us know if we can close this issue now.

Thanks!

**Comment by easyice** [comment]
@grcevski Thank you very much ! this issue can be closed, the last question, Do you think it makes sense for  add a per thread memory allocations tracing in search thread？We can call the `getCurrentThreadAllocatedBytes` twice in QueryPhase or FetchPhase and so on, then we can add some `SearchSlowLog` when the allocated memory is greater than a certain threshold, the slow logs like this:

````
[2021-04-07T18:04:31,312][WARN ][o.e.i.SearchSlowLog      ] [node-idea] memory allocated in query phase [4830416], [my_index][1],source["quey body"], id[1234], 
[2021-04-07T18:04:31,422][WARN ][o.e.i.SearchSlowLog      ] [node-idea] memory allocated in query phase [4965056], [my_index][0],source["quey body"], id[1234], 
[2021-04-07T18:04:34,531][WARN ][o.e.i.SearchSlowLog      ] [node-idea] memory allocated in coordinator [522117176,reduce[361823088],consumeResult[160294088],indices[my_index],source["quey body"], id[1234], 
[2021-04-07T18:04:34,561][WARN ][o.e.i.SearchSlowLog      ] [node-idea] memory allocated in fetch phase [724160], [my_index][0],source["quey body"], id[1234], 
````

If you find it useful, I can submit another PR

**Comment by grcevski** [comment]
Hi @easyice, so if I understand the need for this correctly, it has to do with being able to find the reason for query latency instability in the past? While the newly created 'memory' HotThreads report will tell you which thread is allocating a lot at the moment, you can't use it retroactively to debug issues that happened an hour ago. Is my understanding correct?

I think it would be very hard to make tracing like this generic enough. Defining a threshold would be difficult to do for diverse use cases. For example, in some situations, allocating 3 GB/s is a lot, but in others it would be expected.

Maybe with the new report type you just contributed it is possible to implement an external infrastructure, which will react to an alert of unstable response times and trigger a call to produce a HotThreads memory report?

**Comment by easyice** [comment]
yeah, that‘s right, we using elasticsearch in advertising analysis service, it's very sensitive to query latency, but when query is timeout, it is difficult do find out the root case,Because there are many places on the query path that cannot be traced, we have added some tracing in Internal version, but it's still a long way off.

This issue may not be urgent to other users, So I'm not going to submit the PR, Thank you again @grcevski
