### ISSUE TITLE
Cluster Level Shard Allocation Settings

### ISSUE THREAD

**Issue by SacredWizard** [elastic/elasticsearch#70340]
Currently there are 4 types of dynamic settings for `cluster.routing.allocation.enable` to enable or disable allocation for specific kinds of shards. It would be great to have a setting which recovers the primary shards first and then the replica. This setting could fast forward the recovery from `red` state to `yellow` state (During recovery preference is given to primary shards and then once all the primary shards are recovered, replicas could be recovered).

**Comment by SacredWizard** [comment]
Is there any update on this ?

**Comment by DaveCTurner** [comment]
The initialization of primaries already happens independently from other recoveries, and by default with greater concurrency, see e.g. the `cluster.routing.allocation.node_initial_primaries_recoveries` setting. This isn't exactly what is proposed in the OP, we don't _block_ other recoveries until all primaries are initialised, but such blocking seems undesirable.

I suspect there's something else wrong with your setup, but this GitHub issue isn't the right place to investigate that further. Would you open a thread on the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) and describe in more detail the specific problem you're having with primary recoveries that you think this idea might fix? I am closing this for now, but we can always re-open it (or open a different feature request) if needed.
