### ISSUE TITLE
Optionally run all bwc tests as part of PR CI

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70367]
Currently the `elasticsearch-ci/bwc` PR CI build only runs the `bwcTestSnapshots ` gradle task, which only performs bwc tests (rolling upgrade, full cluster update) against the latest snapshot version of the previous major version and if applicable for the branch then also the latest snapshot version of the previous minor version.

The bwc ci jobs run the `bwcTest` gradle task, which perform bwc tests against all supported versions (in case for 7.x branch that is 7.1.2 until 6.0.0 (snapshot and released versions)). For versions older than 6.8.0, only full cluster restart upgrade tests are ran if I understand correctly.

Sometimes we make changes that affect bwc and certain mistakes aren't caught by running the `bwcTestSnapshots` task, but only when the `bwcTest` task is run. Would it make sense to add support for `@elasticmachine run bwcTests` (or similar), so that optionally all bwc tests are run? This will make it easier to spot bwc tests prior to merging the changes in.

**Comment by mark-vieira** [comment]
I'm thinking we introduce a label which can trigger a build which does the full BWC test suite. We use this pattern elsewhere as a means of having PR authors "opt-in" to more test coverage. Thoughts?
