### ISSUE TITLE
Java RestHighClient use scroll api,in last scroll the scrollId return null 

### ISSUE THREAD

**Issue by biuabiu** [elastic/elasticsearch#70366]
Elasticsearch version : 7.1.0

JVM version: jdk8_121

OS version: Linux

When I use scrollapi in resthighclient, the scrollid returned in the last scroll is null. I don't think this is the expected result I want, because in kibana use rest API, scroll API always returns scrollId and hits is empty when there is no data. I want to know why to deal with this, or should fix it?

**Comment by dnhatn** [comment]
I tried to reproduce the issue with the rest-high-level client and found that Elasticsearch always returns a scroll id. I think there's something wrong on your side.

I'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
