### ISSUE TITLE
Add Support for Metadata in ElasticSearch Queries(query|suggest)

### ISSUE THREAD

**Issue by abhijeetKumarCompass** [elastic/elasticsearch#70417]
Currently, there is no field in elastic search suggest queries where I can pass metadata to queries. Adding metadata is beneficial in scenarios when query ends up in slow query logs. I can pass details of clientName and work with client to fix their query or access pattern. Further, I can use the metadata to build analytics on slow query logs for further analysis and consumption.

This feature is similar to the analytics tag in elastic app search : https://www.elastic.co/guide/en/app-search/7.8/analytics-tags-guide.html

**Comment by dnhatn** [comment]
@abhijeetKumarCompass I think the [x-opaque-id](https://www.elastic.co/guide/en/elasticsearch/reference/master/tasks.html#_identifying_running_tasks) parameter would be good enough for your problem. Please see: https://github.com/elastic/elasticsearch/pull/31539.
