### ISSUE TITLE
Make indices.memory.index_buffer_size dynamically updateable

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#7045]
Elasticsearch updates this internally, when an index becomes idle, or when active shards change but we don't let the user change it today, I think.

**Comment by mikemccand** [comment]
I don't think we should make this setting dynamically updatable: this isn't a setting you should need to dynamically update, and I think it's risky to make it possible...

**Comment by makeyang** [comment]
so there will be no this feature?
