### ISSUE TITLE
Analyze API doesn't recognize plugin analyzers

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#7047]
Issuing a GET on `http://localhost:9200/_analyze?analyzer=myanalyzer&text=foo` provides the following response:

```json
{
error: "ElasticsearchIllegalArgumentException[failed to find analyzer [myanalyzer]]",
status: 400
}
```

However, `myanalyzer` is definitely present (supplied via code as plugin). Elasticsearch also picked it up correctly as I was able to reference it from a mapping and perform indexing and searches correctly.

**Comment by clintongormley** [comment]
Closing in favour of #8961
