### ISSUE TITLE
bad_record_mac in fips test

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70497]
**Build scan**: https://gradle-enterprise.elastic.co/s/k4opo7gqbocx4/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests/testThatProfileTransportClientCannotConnectToDefaultProfile?expanded-stacktrace=WyIwIl0#1

**Repro line**:
```
./gradlew ':x-pack:plugin:security:internalClusterTest' \
  --tests "org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests.testThatProfileTransportClientCannotConnectToDefaultProfile" \
  -Dtests.seed=3D1042FE5DA6D1A8 -Dtests.security.manager=true -Dtests.locale=ar-EG \
  -Dtests.timezone=Pacific/Samoa -Druntime.java=15 -Dtests.fips.enabled=true
```

**Reproduces locally?**: No

**Applicable branches**: 7.12

**Failure history**:
There was [another](https://gradle-enterprise.elastic.co/s/s6lcccwgbv6ea/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests/testThatProfileTransportClientCanConnectToNoClientAuthProfile#1) failure of the same test a week ago but it doesn't look related.

**Failure excerpt**:
https://gist.github.com/nik9000/ca56fd787c1e8fde3291da87ddc39296

**Comment by gwbrown** [comment]
This test hasn't failed in a really long time, the failure doesn't reproduce, and I thiiiiiink it's an instance of https://github.com/elastic/elasticsearch/issues/64044 which is a broader issue, so I'm going to close this out.
