### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and from}

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70507]
**Build scan**: https://gradle-enterprise.elastic.co/s/u4fbgo3xumcpu

**Repro line**: `./gradlew ':qa:mixed-cluster:v6.8.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and from}" -Dtests.seed=A6910EE8E12F2BA1 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=sl -Dtests.timezone=Africa/Lome -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure history**: (once or twice a day) 
https://build-stats.elastic.co/goto/fc6dc5f69fd658c91b66daf43df5ae36

**Failure excerpt**: 

```
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search/110_field_collapsing/field collapsing and from} FAILED
    java.lang.AssertionError: Failure at [search/110_field_collapsing:87]: count didn't match expected value:
                             count: expected Integer [6] but was Integer [3]
        at __randomizedtesting.SeedInfo.seed([A6910EE8E12F2BA1:2EC531324FD34659]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
```

**Comment by mayya-sharipova** [comment]
Closing as a duplicate for https://github.com/elastic/elasticsearch/issues/52416.
I will mute the test today.
