### ISSUE TITLE
Stability Proposal: Worker Processes

### ISSUE THREAD

**Issue by etki** [elastic/elasticsearch#70522]
Hello.

I understand that right now you're scratching your head and asking yourself if I've mistaken Java for single-threaded or GILocked  architectured language like JS / Python / Ruby / etc., but let me explain.

## Motivation

One of the painful ES moments was always the OOM issue. Since Java is a managed language, there's no way to really limit single request memory usage - the only way to do so is probably to write your own Java++ and attach it using JNI, which is obviously not an option. The circuit breakers, from what I know, mostly do their job but don't provide 100% guarantee on preventing OOMs, spinning GC hell and so on. However, I believe this problem is addressable with a pattern that elevates node safety to a new level.

## Architecture

I'm suggesting to implement classic master & pool of worker process pattern, where master offloads some work to worker processes (here and after `master` keyword refers to process, not to the role of a node); I'm having search phase in mind (following text will mention only offloading search phase), but there could be possibly other things in request pipeline I don't know that may blow up. Suggested changes don't change any functionality observed from outside of ES node and only change internal processing of subset of all possible requests.

In this pattern service process has additional functionality of creating and maintaining a pool of worker processes. Worker processes are considered to be expendable and worker process loss is considered to be part of normal operation, but master process is a "pet" rather than "animal" and it's loss should be avoided at any cost, as it is now for service process. Master process creates worker process by invoking same JVM binary with the same jar but different command arguments and tries to maintain a configured number of worker processes at all time, creating new ones when necessary (i.e. on startup and in case of worker process loss). Master and worker processes are connected by some kind of IPC that allows master process to request task execution in a worker process and then receive results of such task some time after. It is implied that single worker process executes minimum amount of tasks at once, preferrably only one. If master process can't allocate process for task execution within a time limit, it can return 429/503-alike response to requestor (which can be either coordinating node or client).

Given such configuration, master process can offload unsafe tasks that are expected to cause process loss from time to time (most likely from OOM) to one of worker processes, while keeping all other existing functionality within self; for the current document, example of such unsafe task is regular search phase that may end with OOM. Since requestor and executor functionality is placed in two separate processes, execution may fail without affecting master process, moving a whole set of problems from "crashes node" to "degrades node performance" category.

### Limiting task memory consumption in a managed language

Separate process has a separate heap and thus it is possible to limit what amount of memory it is allowed to take. Since worker process executes only 1..N tasks at the same time, using such pattern a task will be provided in average with one Nth of worker process heap memory space (which is way more granular than using other approaches), and if simultaneously executing tasks exceed total limit they cause process loss which is treated as "task tried to allocate more resources than it was allowed to" by master process. N could be configured by end user considering weight of their requests and how many "normal" tasks they are willing to sacrifice for single greedy task.

### OOM & general crash safety

Described pattern greatly reduces chance of master process failure and node loss as a consequence. Such separation forces tasks that can bring process down to be excluded from master process, dwindling the chance that it would crash.

### Better request resource control

Besides memory limit that is provided by separate JVM instance, operating system may provide additional controls for fine tuning processes, including their priority, CPU time limiting and so on. Potentially, this allows to keep more than one worker pool so clients could issue requests of different priority and performance impact per same query.

### Better timeout control

With this pattern if worker process that did not respond in configured time can be simply terminated and replaced with new one. This allows to overcome heavy GC loops that prevent application from taking action in required time.

### Domino dogpile effect resilience

One of the painful things that happens with services like ES is that when a node fails for any reason, then requests that it would otherwise take are redistributed across surviving nodes; this approach is totally correct in absence of context and saves the day whenever this crash caused by node itself, but hits back hardly when such fail occurs because of heavy load. When this happens, it is likely that all nodes receive similar load and are on the edge of failing down, so redistributing load starts taking out more and more nodes until the whole cluster is down. Because of that small spike of load may become fatal for the search that is powered by ES.

Suggested pattern provides ability to keep node alive even if it is out of worker processes for any reason. This will degrade overall service quality, since such node won't return anything but error response, but won't trigger such domino effect and increases chances of having responsive cluster nodes even when it is overwhelmed with work.

### NUMA & other quirks?

I'm not too familiar with that, but I guess separating processes would make it easier to bind workload to particular sockets and do other performance-related tuning.

### Increasing or decreasing task limits without restarting the master process

Since master process supervises other processes, it is trivial to change such limit by recycling existing set of processes and creating new ones with updated values.

### Warmup

Every time a new process is started it has to warm up JIT again, and collected profile / C2-compiled code are lost.

### In-memory data duplication

From what I know, some data from indices has to be present in memory (e.g. fielddata), so every process would have to keep a redundant copy of that. It is possible that it can be avoided by using shared memory (if it can be stored as off-heap data), but I don't have enough experience neither with shared memory nor internal ES management of such things.

### A high level of added complexity

Self-explanatory.

### IPC

Obviously, IPC will add some performance impact, but I don't have a clue how much it would be relative to usual request processing. It highly depends on implementation used, since it can be implemented even as a REST API, but doing so will incur a lot of redundant JSON encoding and decoding.

## Implementation notes

- This will require tremendous amount of work, however, I believe that benefits outweigh it.
- ES is built over index immutability concept, so several processes would be just reading same files without adding concurrency hell.

### Effectively maintaining required number of processes

Bringing up new JVM process is a heavy-weight operation that may take seconds. However, master process may create new processes in advance without huge resource consumption. Every decent OS should not actually map heap to real memory pages as long as it is empty (and -XX:+AlwayPreTouch is not set), so it is expected that just creating new process without feeding it with some work won't be a big deal. Some OS (at least Linux, I'm not an expert on this topic) allow to put processes in dormant state, which allows to reduce CPU consumption of such process down to zero.

However, this may require tuning overcommit OS setting.

### Forking isn't a solution

One might think that instead of creating new processes it is easier to fork current one and instantly get a new process. This is expected to bring more headache rather than benefits:

- Master process and worker process would share same heap size, while it is expected that master doesn't need much and worker could require gigabytes for heavyweight workload.
- There is no benefit in copy-on-write memory since first major GC will either defragment heap or relocate survivors from all across the heap, making most of process memory different in a short time.
- There are other small benefits which, I believe, don't address any needs in this particular scenario
- No performance gains are expected from having access to JIT profile / compiled methods in worker process, since most of the hot code in master and executor process will be completely different, i.e. master process doesn't have neither profile or highly optimzied versions of code that would be spinning in worker.

Forking an existing worker process _may_ help with the latter one, but I don't think it's worth the added complexity.

**Comment by etki** [comment]
Hey, just curious if ES team had any thoughts on this

**Comment by rjernst** [comment]
We appreciate the effort that went into laying out this proposal. It is great to see ideas from the community, however large or small. Ultimately, though, there are several technical details that make the cost of this proposal far outweigh the benefits:

* There are many complex data structures that are shared across the codebase which would need to be shared across processes. That could happen through shared memory or IPC. Either of those solutions present new problems, not insurmountable problems, but ones which would be very complex to solve, especially in Java.
* Launching processes presents attack vectors (remember Java does not have fork). We use both java SecurityManager and OS level features (eg seccomp) to disallow exec, and we want to keep that security model.
* Changing the model at this point in Elasticsearch's lifetime would be **MONUMENTAL**. It would involve rewriting a large portion of the codebase from scratch.

Give the points above, this is not something we plan to pursue, so I hope you don't mind that I close this issue.
