### ISSUE TITLE
IndexShardSnapshotFailedException while uploading snapshots to s3

### ISSUE THREAD

**Issue by patil-abhi** [elastic/elasticsearch#70521]
Please fill in the following details to help us reproduce the bug:
The cluster contains 

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.0

**JVM version** (`java -version`): java-8

**Description of the problem including expected versus actual behavior**:

The cluster contains 338 data nodes with 60 shards in each. Each node has a heap of 30gb.

These are the repo settings for snapshots:
{
  "type": "s3",
  "settings": {
    "bucket": "<bucketname>",
    "chunk_size": "1gb",
    "max_restore_bytes_per_sec": "8000mb",
    "max_snapshot_bytes_per_sec": "8000mb",
    "max_retries": "1000",
    "buffer_size": "100mb",
    "base_path": "/",
    "region": "us-west-2"
  }
}

The exceptions are as follows:
`IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: IOException[Unable to upload object [<>] using multipart upload]; nested: AmazonS3Exception[Please reduce your request rate. (Service: null; Status Code: 0; Error Code: SlowDown; Request ID: <>; S3 Extended Request ID: <>)];`

It fails for a few of the indices with the above exception. 

 What are the recommended parameters for the snapshot repository of s3 to avoid the rate error.

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by cde0** [comment]
do you find a solution for this i have the same problem but only from one node

**Comment by patil-abhi** [comment]
Not yet! I am working on using multiple paths in s3 to get rid of the write
rate error. What error do you get exactly?
