### ISSUE TITLE
es oom due to SegmentReader

### ISSUE THREAD

**Issue by ykgarfield** [elastic/elasticsearch#70536]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.5.4

**Plugins installed**: 
[analysis-ik]

**JVM version** (`java -version`):
jdk1.8.0_131

**OS version** (`uname -a` if on a Unix-like system):
Centos 7.x  3.10.0-862.3.2.el7.x86_64

**Description of the problem including expected versus actual behavior**:
Our cluster have 40 nodes, 36 data nodes, total shards 10576, total data 270TB，recently one data node is down，it's oom，have a dump file。we analysis it with MAT.

![overview](https://user-images.githubusercontent.com/1425308/111563892-c6515400-87d3-11eb-88eb-5d780e80af94.png)

Only have one Problem Suspect  `org.apache.lucene.index.SegmentReader`

Common Path To the Accumulation Point:
![Common Path To the Accumulation Point](https://user-images.githubusercontent.com/1425308/111577376-1ab4fd80-87ed-11eb-9772-2263b85cdc3a.png)

Biggest Top-Level Dominator Classes (Overview):
![Biggest Top-Level Dominator Classes (Overview)](https://user-images.githubusercontent.com/1425308/111577677-b5add780-87ed-11eb-82dc-18cbbe2478a1.png)

Biggest Top-Level Dominator Classes:
![Biggest Top-Level Dominator Classes](https://user-images.githubusercontent.com/1425308/111577729-d0804c00-87ed-11eb-91ad-e796ce060aa1.png)

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Some hints in any case: Looking at the output you've provided this might be related to high memory usage of the field data cache. You can either [lower it](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/modules-fielddata.html#modules-fielddata) (but see the caveats mentioned in the docs: "reloading the field data which does not fit into your cache will be expensive and perform poorly.") or [lower the field data circuit breaker threshold](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/circuit-breaker.html#fielddata-circuit-breaker) so it trips earlier.
