### ISSUE TITLE
The Regexp query for ‘$’ and ‘$’ does not take effect

### ISSUE THREAD

**Issue by gaozhenhai** [elastic/elasticsearch#70549]
1、First, query the log as follows
```
GET ggg-logstash-2021.03.18/_search/?size=1
{
  "_source":[
    "log"
  ],
  "query": {
    "bool": {
      "must": [
        {"range":{
          "@timestamp":{
            "gte":"2021-03-18T01:00:00+00:00", 
            "lte":"2021-03-18T23:00:00+00:00"
          }
        }},
        {"regexp":{
            "log.keyword":"2019-12-13.*"
          }
        }
      ]
    }
  }
}
```
The results are as follows
```
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 7,
    "successful" : 7,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 24388,
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "ggg-logstash-2021.03.18",
        "_type" : "fluentd",
        "_id" : "569ZRHgBDgaK7htXw75b",
        "_score" : 2.0,
        "_source" : {
          "log" : """
2019-12-13 18:16:40 WARN [compress-spi-executor-50] com.ab.universal.filter.convert.ConvertFilter - <Business-Parameter-Flag> Business Get: <?xml version="1.0" encoding="GBK"?>

"""
        }
      }
    ]
  }
}

```

2、Then, modify the regular statement to query again
```
GET ggg-logstash-2021.03.18/_search/?size=1
{
  "_source":[
    "log"
  ],
  "query": {
    "bool": {
      "must": [
        {"range":{
          "@timestamp":{
            "gte":"2021-03-18T01:00:00+00:00", 
            "lte":"2021-03-18T23:00:00+00:00"
          }
        }},
        {"regexp":{
            "log.keyword":"^2019-12-13.*"
          }
        }
      ]
    }
  }
}
```
The results are as follows
```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 7,
    "successful" : 7,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

```

The '^' character in the regular statement does not work. It is the same with '$'
If a ^ character is used in the regex, is it consistent as described at https://github.com/elastic/elasticsearch/issues/17098#issuecomment-196890981

**Elasticsearch version** (`bin/elasticsearch --version`):
```
{
  "name" : "es-allinone-es-0",
  "cluster_name" : "es",
  "cluster_uuid" : "nmjEygWMRXiVibj9L_Gz6g",
  "version" : {
    "number" : "6.8.12",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "7a15d2a",
    "build_date" : "2020-08-12T07:27:20.804867Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.3",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
```
Linux syy1-12 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-unsupported-operators
Anchor operators ('`^` and `$`)  are not supported in Lucene’s regular expression. This behavior is documented and we don't plan to change it so I  hope you don't mind if I close the issue.

**Comment by gaozhenhai** [comment]
> See https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-unsupported-operators
> Anchor operators ('`^` and `$`) are not supported in Lucene’s regular expression. This behavior is documented and we don't plan to change it so I hope you don't mind if I close the issue.

Thank you very much for your answer. I think I understand
