### ISSUE TITLE
there is a bug(http connection pool not destroyed) in "elasticsearch-rest-high-level-client"

### ISSUE THREAD

**Issue by xulang** [elastic/elasticsearch#70553]
When i create the instance of RestHighLevelClient, if it  fail(throw exception), the http connection pool will not be destroyed.  if i try loop to create it,it will cause a lot of thread created.

**Comment by matriv** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

PS. Please provide some more details for the issue you're facing, when you post this question on the forum, it would be great to also have the corresponding code snippet.
