### ISSUE TITLE
Determine when filesystem quotas are respected by Elasticsearch

### ISSUE THREAD

**Issue by mieciu** [elastic/elasticsearch#70560]
As we've recently discovered, Elasticsearch `7.11.1` respected XFS quotas applied to its data directory. The environment details:
* Ubuntu 16.04.7 LTS
* Elasticsearch `7.11.1` running in Docker (`v19.03.13`) container
* Elasticsearch using bundled JDK `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)`

Quick investigation (thanks @rjernst!)  led to `statvfs64` call by `getUsableSpace()` in `LinuxFileSystem`. Therefore, on some environments `quota-aware-fs` and managing its configuration file might not be even required as native XFS quotas are  recognised and reported correctly by Elasticsearch.

It would be great to determine the specific requirements (JDK? Operating system/kernel version?) under which filesystem quotas are working and users are not require to install and manage `quota-aware-fs` plugin.

Related: https://github.com/elastic/elasticsearch/issues/65227 https://github.com/elastic/elasticsearch/issues/61145

**Comment by pugnascotia** [comment]
We removed the quota plugin in #76352.
