### ISSUE TITLE
Deprecate and remove geo_bounding_box query type parameter

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#70561]
The following parameter is documented in the geo_bounding_box query:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#geo-bbox-type

It seems that is coming from the implementation previous to the introduction of there BKD tree in Lucene. It is currently ignored and it has no effect on the result of there query. The documentation should be updated and the parameter deprecated.

**Comment by wchaparro** [comment]
@iverase should we update the docs for this one? @jrodewig FYI

**Comment by jrodewig** [comment]
Thanks @wchaparro @iverase.

I've opened a couple of PRs to document the deprecation:
* 8.0: https://github.com/elastic/elasticsearch/pull/74008
* 7.x: https://github.com/elastic/elasticsearch/pull/74009

These PRs assume we'll deprecate the parameter in 7.x and remove it in 8.0.

**Comment by missinglink** [comment]
Hi, can someone please clarify when setting `geo_bounding_box.type="indexed"` became a no-op?

The [reference for 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/query-dsl-geo-bounding-box-query.html#geo-bbox-type) (for instance) says that the default setting is `memory`.

I'd like to better understand what effect removing `geo_bounding_box.type="indexed"` from our configs will have on users of different versions in the 7.x range.
