### ISSUE TITLE
Document how to adjust the HLRC's default ThreadFactory

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#70584]
Today, the HLRC's default `ThreadFactory` [1] doesn't create daemon threads. This means the JVM will not exit until the client is explicitly closed. In certain situations, an exception (e.g `ElasticsearchException`) might be thrown on a thread resulting in the JVM continuing to run indefinitely. Users may wish to adjust the default `ThreadFactory`:

```JAVA
// Mimics http-client's default thread factory
AtomicInteger threadCounter = new AtomicInteger(0);
ThreadFactory threadFactory = runnable -> {
    Thread result = new Thread(runnable, "ES client " + threadCounter.incrementAndGet());
    result.setDaemon(true);
    return result;
};

builder.setHttpClientConfigCallback(httpClientBuilder -> httpClientBuilder.setThreadFactory(threadFactory));
```

It'd be useful to document this behavior (+ possibly add an easy helper function to enable it).

[1] https://github.com/apache/httpcomponents-core/blob/05d914304ecf41c263cbcb6bcea86e121d2a0bdd/httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/AbstractMultiworkerIOReactor.java#L606

**Comment by scottdfedorov** [comment]
👎🏻
