### ISSUE TITLE
Null pointer exception in two different join types while fetching their parents

### ISSUE THREAD

**Issue by aliabbas-2012** [elastic/elasticsearch#70614]
I have very simple mapping for system, 
`{
  "properties": {
    "type": {
      "type": "join",
      "relations": {
        "user": [
          "user_bookmarks"
        ],
        "post": [
            "post_bookmarks"
        ]
      }
    }
  }
}`

When i try to run this query i get the null pointer exception

` 
 {
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must": [
              {
                "term": {
                  "type": "user_bookmarks"
                }
              },
              {
                "has_parent": {
                  "parent_type": "user",
                  "inner_hits":{
                    "_source":["id"]
                  },
                  "query": {
                    "match_all": {}
                  }
                }
              }
            ]
          }
        },
        {
          "bool": {
            "must": [
              {
                "term": {
                  "type": "post_bookmarks"
                }
              },
              {
                "has_parent": {
                  "parent_type": "post",
                   "inner_hits":{
                    "_source":["id"]
                  },
                  "query": {
                    "match_all": {}
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
 `

**Comment by aliabbas-2012** [comment]
Here is my error
`{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 4,
    "skipped" : 0,
    "failed" : 1,
    "failures" : [
      {
        "shard" : 3,
        "index" : "trending",
        "node" : "hTYvbi70QKGHZvuFYHtnlA",
        "reason" : {
          "type" : "null_pointer_exception",
          "reason" : null
        }
      }
    ]
  },
  "hits" : {
    "total" : 1,
    "max_score" : 10.267918,
    "hits" : [ ]
  }
}
`

**Comment by astefan** [comment]
@aliabbas-2012 Thank you very much for your interest in Elasticsearch.
Your bug report cannot be verified because of lack of details: Elasticsearch version, a complete reproduction list of steps (do I need documents in this index to be able to reproduce this, if so you need to provide those as well. Also, we need to see the complete error message and, if there are any, logs containing the same error plus its stack trace.

**Comment by danielmitterdorfer** [comment]
No further feedback received. @aliabbas-2012 if you have the requested
information please add it in a comment and we can look at re-opening
this issue.
