### ISSUE TITLE
[DOCS] Explain that geo_shape WITHIN query on linestring/multilinestring field is not supported

### ISSUE THREAD

**Issue by atombender** [elastic/elasticsearch#70648]
Querying a linestring or multilinestring using a `geo_shape` query with `WITHIN`:

```
Field [attrs.f_13$G] found an unsupported shape [LINESTRING]
```

Looking at [the code](https://github.com/elastic/elasticsearch/blob/85516d6901ea41ab36be451e9e9ef8fa527e85d1/server/src/main/java/org/elasticsearch/common/geo/GeoShapeUtils.java#L101-L105), this is explicitly unsupported, yet the documentation does not mention it.

**Comment by iverase** [comment]
Yes, line and within are not supported. The limitation comes from the [Lucene implantation](https://github.com/apache/lucene/blob/cce982146af785b0fb5ad4945e8671e1ff76743a/lucene/core/src/java/org/apache/lucene/document/LatLonShapeQuery.java#L45). 

Note that this is mention in the docs under the spatial relationships supported by the geo_shape query but I agree it can easily be missed:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_spatial_relations

**Comment by atombender** [comment]
Ah, I did not see that for 7.11, and 7.12 was released after I created the issue. Thanks.

I assume there's no way to check the type of a geo shape in the query, to avoid having the entire query error out like this. To avoid erroring, we'll have to index the GeoJSON `type` field as a separate field and combine it with a boolean `must_not: {term: {type: "LineString"}}` kind of query.

**Comment by craigtaverner** [comment]
I reviewed the docs, and it seems to me the comment about lines not being supported with `WITHIN` is in exactly the right place in the docs - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html#_spatial_relations
