### ISSUE TITLE
Provider class Completion50PostingsFormat not in module

### ISSUE THREAD

**Issue by mortharia** [elastic/elasticsearch#70699]
**Elasticsearch version** (7.11.2):

**JVM version** (11):

**Description of the problem including expected versus actual behavior**:
Using java module, I am facing a compilation errors assumed that package org.elasticsearch.action.search does not exist.
 By debugging the code, I come through the problem that elasticsearch jar is neither added to the classpath nor the modulepath. The root cause is highlighted in the compile phase by : 

`[WARNING] Can't extract module name from elasticsearch-6.8.6.jar: Provider class org.apache.lucene.search.suggest.document.Completion50PostingsFormat not in module`

Since no implementation of org.apache.lucene.search.suggest.document.Completion50PostingsFormat is provided in the elasticsearch jar, why expose org.apache.lucene.codecs.PostingsFormat service?

Same issues [#28984](https://github.com/elastic/elasticsearch/issues/28984) closing in favor of [#38299](https://github.com/elastic/elasticsearch/issues/38299)

**Comment by matriv** [comment]
@mortharia What's the purpose of opening this issue on top of #38299 ?

**Comment by mark-vieira** [comment]
As @matriv mentions, this is a duplicate of #38299 . That being said, we have no intention of bringing JPMS support to the 6.8 version of the client.
