### ISSUE TITLE
SQL: support for multi-value filtering

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#70705]
In order to have a complete user experience with multivalues in SQL, we need to look at array support both in projections and filtering. While the projection case is clearer - return in a cell all values present in a document for a field -, the filtering poses a few challenges. 

ES/SQL implementation assumes one single value of an attribute or expression to be run against one or a set of conditions. In case the attribute is that of a multivalue field, an arbitrary value of its set is picked, which can lead to unexpected results: for a field `x` containing `[1, 2, 3]` in a document and a filter `x > 2`, ES/Lucene will match on this document (since there is one value in it that matches the criteria) and thus SQL will return this result containing values actually not matching the filter. 

Logically apparently contradictory conditions will now pass: `x > 2 and x < 2` always evaluate to `false` for univalue fields, but can become `true` with multivalue: `3` in the document matches the first conjunction condition and `1` matches the second.

Filtering implemented through scripting will now also pick just one value to run, which compared to previous "under-filtering" examples could now lead to "over-filtering" false negatives: `x > 2` could have value `1` picked out of the field and return nothing, despite value `3` matching the condition.

For projections SQL makes use currently of a request configuration boolean parameter, `multi_value_field_leniency`, which will allow the caller to choose between having an exception thrown when a multivalue field is encountered, or have an arbitrary value returned out of it. This might need to be complemented with a flag to deal with multivalues for querying.

**Comment by wchaparro** [comment]
Superceded by ES|QL
