### ISSUE TITLE
token filter word delimiter not apply type table hyphen

### ISSUE THREAD

**Issue by awenger63** [elastic/elasticsearch#70708]
**Elasticsearch version** (`bin/elasticsearch --version`): 
"version" : {
    "number" : "7.9.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }

**Description of the problem including expected versus actual behavior**:

Like it  is explain in [https://www.elastic.co/guide/en/elasticsearch/reference/7.9/analysis-word-delimiter-graph-tokenfilter.html#word-delimiter-graph-tokenfilter-configure-parms](url)
type_table for hyphen not work 

**Steps to reproduce**:
 1.
```
PUT http://localhost:9200/test_filter
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "no_split_on_hyphen_filter"
          ]
        }
      },
      "filter": {
        "no_split_on_hyphen_filter": {
          "type": "word_delimiter_graph",
          "type_table": [
            "- => ALPHA"
          ]
        }
      }
    }
  }
}
```

 2.
```
GET http://localhost:9200/test_filter/_analyze
Content-Type: application/json

{
  "analyzer": "my_analyzer",
  "text": "test word-with-hyphens not split"
}
```

 3. result
```
{
  "tokens": [
    {
      "token": "test",
      "start_offset": 0,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "word",
      "start_offset": 5,
      "end_offset": 9,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "with",
      "start_offset": 10,
      "end_offset": 14,
      "type": "<ALPHANUM>",
      "position": 2
    },
    {
      "token": "hyphens",
      "start_offset": 15,
      "end_offset": 21,
      "type": "<ALPHANUM>",
      "position": 3
    },
    {
      "token": "not",
      "start_offset": 22,
      "end_offset": 25,
      "type": "<ALPHANUM>",
      "position": 4
    },
    {
      "token": "split",
      "start_offset": 26,
      "end_offset": 31,
      "type": "<ALPHANUM>",
      "position": 5
    }
  ]
}
```

The word "word-with-hyphens" expected to not be split in 3 words

**Comment by matriv** [comment]
@awenger63 
You are using the [standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html) which already splits on the hyphen before the filtering, check [here](https://unicode.org/reports/tr29/) for more info on the standard tokenizer.

To make your custom-defined `no_split_on_hyphen_filter` work correctly, you'll need to use some other tokenizer like the [whitespace](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-whitespace-tokenizer.html) or the [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keyword-tokenizer.html).

For the future, we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). 
If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature
requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to such questions. As such, I
hope you don't mind that I close this.

**Comment by awenger63** [comment]
@matriv Thanks you for you reply. I've create a user account on the forums few days ago and begining also some discussion.
In the futur, I'll use forums before git issues ;-)
Regards

**Comment by matriv** [comment]
Thank you!!
