### ISSUE TITLE
SearchableSnapshotDirectoryStatsTests failures

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#70728]
Some searchable snapshots tests are failing today:

**Build scan**:
https://gradle-enterprise.elastic.co/s/rkhnksundfwxy
https://gradle-enterprise.elastic.co/s/qg2pyjp2w5ie4/

**Repro line**:

./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryStatsTests.testReadBytesContiguously" -Dtests.seed=BFE4833CEC7197EF -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/El_Salvador -Druntime.java=8

./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryStatsTests.testCachedBytesReadsAndWrites" -Dtests.seed=BFE4833CEC7197EF -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/El_Salvador -Druntime.java=8

**Applicable branches**: master and 7.x

**Comment by ywelsch** [comment]
Will be fixed by https://github.com/elastic/elasticsearch/pull/70668
