### ISSUE TITLE
Merge two loops into one to reduce performance consumption in TransportBulkAction$BulkOperation.doRun()

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#70731]
We just want to split the DocWriteRequest by shardId in the loop https://github.com/elastic/elasticsearch/blob/321f46e1877d40d987294f28362619a322d92af3/server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java#L477
which seems unnecessary and costs time,  if we could Merge it into the previous loop?

**Comment by matriv** [comment]
@kkewwei Thanks a lot for bringing this into our attention, it has been addressed.
