### ISSUE TITLE
Add support for _meta field to ILM policies

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#70755]
We support the `_meta` key as an object that can contain any data in our component and composable index templates. We use this functionality to be able to give these objects descriptions and indicate whether they are managed by Elasticsearch.

We should add support for this `_meta` field to ILM policies themselves.

**Comment by gaobinlong** [comment]
@dakrone, can I work on the issue? I'm interested in ILM and have submitted several PRs for ILM.

**Comment by dakrone** [comment]
@gaobinlong certainly, that would be great, feel free to ping me if you need any assistance.

**Comment by dakrone** [comment]
This has been resolved in #73515, thanks again @gaobinlong
