### ISSUE TITLE
Failure in CachedBlobContainerIndexInputTests.testRandomReads

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#70763]
**Build scan**: https://gradle-enterprise.elastic.co/s/3g6dnmunvdxgw

**Repro line**: `./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads" -Dtests.seed=B14197630B410474 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=11`

**Reproduces locally?**: Yes

**Applicable branches**: master

**Failure history**: So far, just once on 3/23/21

**Failure excerpt**:

```

java.lang.AssertionError: Expected at most 1 ranges fetched from the source |  
-- | --
   | Expected: a value less than or equal to <1L> |  
   | but: <2L> was greater than <1L>

at __randomizedtesting.SeedInfo.seed([B14197630B410474:84433590E1EDA05E]:0) |  
-- | --
   |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
   |   | at org.junit.Assert.assertThat(Assert.java:956) |  
   |   | at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads(CachedBlobContainerIndexInputTests.java:148)


```

**Comment by ywelsch** [comment]
Will be fixed by https://github.com/elastic/elasticsearch/pull/70668
