### ISSUE TITLE
ElasticSearch - search not working randomly, refreshing issue ?

### ISSUE THREAD

**Issue by Rayzbam** [elastic/elasticsearch#70794]
Hi,

It's been some week i encounter some issues on ElasticSearch "Search" API.
Sometimes, the search doesn't return a result which has been indexed before (sometimes while before, like 30min or 1hour).

I made some research on this issue, and the only feature i found that can be related to this was the ElasticSearch "refresh" which made available indexed documents for search.
We keep all default parameters on the ElasticSearch servers, so the refresh interval should be 1sec.

It seems that refresh feature targets an index **only** if a "search" has been called in the last 30 seconds.
In our solution we just do a search **every time before indexing any document to check any duplicate** in the index, i guess the index is moving a lot and refresh should refreshing a lot too.

Our servers are 8go RAM and 4vCPU and we're indexing like 50k documents a day for now.
We have 2 nodes in the cluster with this config.
It seems that we're in the Elastic standard for our server for this index load.

It's hard to debug because it happen randomly and if we call the search by ourself, it's just working ..
So we're out of idea now.

I just wanna know if someone has encountered this behavior or know how i can investigate this.

N.B : We're indexing documents one by one, we can't bulk it in our process. Sometimes, we have a "rush" of documents and maybe the servers are struggling (1k documents in a few seconds or minutes) but it seems that 50k documents, when i'm comparing with other topic here, is a tiny tiny tiny load so i can't think about it.

Thanks for your help.

**Comment by kkewwei** [comment]
In high ES version, if you don't explicit set refresh time and there not be search  in the last 30 seconds, it will not refresh, related code:
https://github.com/elastic/elasticsearch/blob/efa6aea168665ae9b914ee8fa4ebd8212f386085/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L3324

**Comment by cbuescher** [comment]
Hi @Rayzbam. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
