### ISSUE TITLE
Reusable teardown of REST tests for docs snippets

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#70830]
Currently, our docs snippets support reusable setup comments like `// TEST[setup:name]`. This lets doc contributors quickly configure indices for snippet tests.

Our current setup tests all use indices. Now that data streams are the preferred way of indexing time series data, I'd like to create setup tests for data streams.

However, data streams require an index template. At the end of each test, our docs integration tests check for uncleared templates[1]. If a template isn't deleted after a test, the test fails. I'd like to automate this cleanup so contributors don't have the overhead.

I've outlined a couple solutions at a high level below. I'm not presenting these as the only options but as a way to explore the problem space. Please feel free to add/discuss other solutions.

1. Update our cleanup tasks to delete all data streams (`DELETE /_data_stream/*`) and all index templates (`DELETE /_index_template/*`) after every snippet test. Or remove the check if it's no longer needed.
2. Create a way to build reusable `// TEST[teardown:name]` tests, similar to our setups.
3. Manually insert a teardown as a block comment in any doc files that use a data stream setup. This doesn't avoid much of the overhead but works right now with no code changes. For example:

```
////
[source,console]
----
DELETE /_data_stream/*
DELETE /_index_template/*
----
// TEARDOWN
////

[source,console]
----
POST /my-data-stream/_rollover
----
// TEST[setup:my_data_stream]
````

[1]: https://github.com/elastic/elasticsearch/blame/master/docs/src/test/java/org/elasticsearch/smoketest/DocsClientYamlTestSuiteIT.java#L148

**Comment by nik9000** [comment]
I can hack something together for this in the grand duct tape tradition of these tests.
