### ISSUE TITLE
REST API spec lifetime policy

### ISSUE THREAD

**Issue by mshustov** [elastic/elasticsearch#70862]
Hi, I'm from Kibana Core team.
Kibana uses the official [@elastic/elasticsearch](https://github.com/elastic/elasticsearch-js) client to communicate to the Elasticsearch server. 
`@elastic/elasticsearch` in turn, uses `rest-api-spec` provided by Elasticsearch to generate the library public API.

During the regular update of `@elastic/elasticsearch` version in Kibana, we [found out](https://github.com/elastic/kibana/pull/95277) `@elastic/elasticsearch` public API has been changed.
It has been caused by this change in the Elasticsearch `rest-api-spec` specification https://github.com/elastic/elasticsearch/pull/67123/files#r552937279
The deprecated endpoint still [provided](https://github.com/elastic/elasticsearch/pull/67123/files#diff-926aa677a20cc02a928f897446bb4f2dc03308ecd898cb8990ec3b52191f0e50R37) by the Elasticsearch server in `v7.12`. So Kibana keeps on using it on the `7.12` branch and switched from the deprecated endpoint to the new one on the `7.13` branch.

I created this issue to discuss how we can keep public API in sync between Elasticsearch, Elasticsearch client library, and Kibana. The first idea that came to my mind was to keep `rest-api-spec` in sync with the actual implementation: an endpoint and the relevant specification should be created, modified, or deleted at the same time. 
I admit that you may have other reasons not to follow this rule, especially for the experimental API. So curious to hear your opinion.

**Comment by rjernst** [comment]
@mshustov The backwards compatibility policy of Elasticsearch should prevent such a change without warning. That is, in normal circumstances, we strive to maintain compatibility through an entire major version. There are exceptions, as you noted, with experimental APIs (as well as once we consider internal).

In the particular linked PR, it seems like compatibility was maintained. A new endpoint was added, but the old one still works, with a depreciation message. And Kibana noticed this through that deprecation, and made the appropriate change.

From my perspective the deprecations and backcompat policy made the process seamless: Kibana did not need to be aware of every change in Elasticsearch, and was also not forced to make an immediate change. Can you describe more what in that process you think should be changed?

**Comment by mshustov** [comment]
> Kibana did not need to be aware of every change in Elasticsearch, 

Sorry for being unclear. For this particular example provided, Kibana has to adopt the change because immediately because `rest-api-spec` for the deprecated `_ml/find_file_structure` endpoint is not present on the `v7.12` branch anymore. Since `rest-api-spec` is absent, the `elasticsearch-js` client generates API without the deprecated endpoint method, which in turn requires Kibana to remove `_ml/find_file_structure` usage in the codebase. 

> Can you describe more what in that process you think should be changed?

Is it possible to keep `rest-api-spec` for an endpoint as long as it works?

**Comment by delvedor** [comment]
> I suppose keeping the old URL around and making it deprecated was me trying to be nice to my UI team so that their kibana builds wouldn't completely break due to an endpoint changing.

You were! But unfortunately, clients are using the rest-api-spec for generating the API surface, so as soon as a definition is removed from there, the clients will no longer have it as well.
Very likely this was an unfortunate timing issue :)

**Comment by mshustov** [comment]
> But I don't think there is any action to take past "follow our existing BWC policies".

If our BWC policy already requires that `rest-api-spec` and implementation must be in sync, then we can close the issue.

>  I will separately see about adding back that particular rest spec endpoint.

Thank you so much.
