### ISSUE TITLE
[DOCS] Documented _reindex Privileges not enough

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#70898]
Running against version 7.11.2, I was trying to create a new API Key to allow me to run a reindex-from-remote job. Every permutation without giving a crazy amount of privileges was rejected with:

```
action [indices:data/write/reindex] is unauthorized for API key id [blah] of user
```

I tried to also create an API with the cluster privilege set to `indices:data/write/reindex`, but that triggered:

```
unknown cluster privilege [indices:data/write/reindex]
```

I could not figure out the right set of privileges to use with it, so the user has far too much access now.

**Comment by pickypg** [comment]
After trolling through the code, I noticed that the `indices:data/write/reindex` is an index-level privilege.

https://github.com/elastic/elasticsearch/blob/d5d8cf95674a55337e9501338de18a67e7c66e54/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/IndexPrivilege.java#L66

Setting it as an index-level privilege got it working without extra privileges.

**Comment by jrodewig** [comment]
Hi @pickypg!

Thanks for raising this. It sounds like giving the user the `write` index privilege for the destination would have fixed this.

https://github.com/elastic/elasticsearch/blob/d5d8cf95674a55337e9501338de18a67e7c66e54/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/IndexPrivilege.java#L66

https://github.com/elastic/elasticsearch/blob/d5d8cf95674a55337e9501338de18a67e7c66e54/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/IndexPrivilege.java#L92

The [7.11 reindex API docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/docs-reindex.html#docs-reindex-api-prereqs) do that you must have:

> The `write` index privilege for the destination data stream, index, or index alias.

It sounds like we may be able to close this issue. Let me know if I've missed something or if we can do anything to make the docs clearer. Thanks again!

**Comment by tvernum** [comment]
> Running against version 7.11.2

_Always be upgrading_ :)

In 7.12 the error message is:

> action [indices:data/write/reindex] is unauthorized for API key id [...] of user [...] on indices [...], this action is granted by the index privileges [write,all]

**Comment by jrodewig** [comment]
I'm going to go ahead and close this out. Please feel free to re-open if wanted. Thanks!

**Comment by pickypg** [comment]
Figures, the one time I'm not running latest! Just as an aside, my use case is about 100% create-only behavior, so I have been hesitant to grant `write` privileges.
