### ISSUE TITLE
Multi terms: return bucket key as a map instead of an array 

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elasticsearch#70912]
When running a multi_terms aggregation, the bucket key is currently an array of strings. This is different from a composite aggregation, where the bucket key is a key-value map (based on `sources`). 

It'd be great if we have an option that allows the bucket key to be a key-value map, where the key is the field name. This allows us to easier get a specific field value from the bucket key. An example:

```
{
  "aggs": {
    "series": {
      "multi_terms": {
        "terms": [
          { "field": "service.name" },
          { "field": "service.environment" },
          { "field": "transaction.type" }
        ]
      }
    }
  }
}
```

would return:

```
{
  "aggregations": {
    "series": {
      "buckets": [
        {
          "key": {
            "service.name": "opbeans-java",
            "service.environment": "production",
            "transaction.type": "request"
          },
          "doc_count": 1
        }
      ]
    }
  }
}
```

We can then get service name as such:
```ts
const serviceName = response.aggregations.series.buckets[0].key.['service.name'];
```

As opposed to:
```ts
const [ serviceName, serviceEnvironment, transactionType ] = response.aggregations.series.buckets[0].key;
```

... which could break if the order of the fields change.

**Comment by imotov** [comment]
What do we do if it is a script?

**Comment by dgieselaar** [comment]
@imotov I'd be fine with specifying the key in the request, e.g.:

```
{
  "aggs": {
    "series": {
      "multi_terms": {
        "terms": {
          "service.name": { "field": "service.name" },
          "service.environment": { "field": "service.environment" },
          "transaction.type": { "field": "transaction.type" }
        }
      }
    }
  }
}
```

> Since this is already released we will need to add a switch to choose between map and an array and that will also significantly increase the response size especially for large keys and numeric values since we will be repeating all keys in all buckets.

I'm not _too_ worried about the response size, but that might just be me. Composite aggs have the same structure, is it an issue there?

> Map in json doesn't support ordering of elements, and I feel like order here is very meaningful, so in my mind it more naturally fits an array. Also if your key is dynamic you should already have a corresponding array in the request structure, so you probably will be looping over this structure anyway in a generic scenario and these names will not be hardcoded like in your example, or I am missing something there?

Can you elaborate on why the order in response is meaningful? Also, this would be opt-in, I did not mean for a mapped response to be the default.

> Considering the overall amount of work related to handling the names, migration path, increased complexity and response size, wouldn't it be easier to create a name to position map on the client side and just do something like this?

It's certainly not a necessity. I was hoping for an easy win 😄

**Comment by imotov** [comment]
> I'm not too worried about the response size, but that might just be me. Composite aggs have the same structure, is it an issue there?

I don't think we ever measured it and I would take consistency over performance in this case and I think we should have modelled it on composite aggs and followed the same structure with sources instead of terms. Unfortunately, we modelled it on term agg instead. We can probably change the structure for follow sources interface in composite aggs, but that would be a bit tricky.

> Can you elaborate on why the order in response is meaningful?

That's basically the sort key. So the first element is more important than the second and so on. 

> I was hoping for an easy win :smile:

It might be a win but it ain't easy :smile: 

I will add it for team discussion.

**Comment by imotov** [comment]
We discussed this issue and decided not to implement this request. The current solution is more compact and contains all necessary information for the client to make sense of data. This change is also pretty significant in terms of backward compatibility.
