### ISSUE TITLE
Point in Time throws "request body is required" exception

### ISSUE THREAD

**Issue by tejuri** [elastic/elasticsearch#70986]
Description of the problem including expected versus actual behavior:
Following the documented examples to open a point in time throws a parse exception with "request body is required".

I am using 7.12.0 in my docker-container

Steps to reproduce:

> def get_pit(self, index_name):
        try:
            self.es = Elasticsearch(
                [self.host],
                http_auth=(self.username, self.password),
                scheme="https",
                port=443,
                timeout=60
            )
            response = self.es.open_point_in_time(
                index=index_name,
                params={"keep_alive": "1m"}
            )
            return response
        except ElasticsearchException as es:
            self.logger.exception(
                "Error retrieving data from Elastic search - %s", es)
            raise Exception

**Comment by rusiano** [comment]
Why closed? Did you find any solution? I am having the same issue...

**Comment by radAragon** [comment]
Same here, version "@elastic/elasticsearch": "7.13.0"
