### ISSUE TITLE
[DOCS] Clarify bi-directional example on CCR docs

### ISSUE THREAD

**Issue by octavioranieri** [elastic/elasticsearch#71009]
Hey team,

Internally discussed with @gwbrown and agreed that documentation may be misleading on bi-directional CCR examples in the docs.
https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-ccr.html#ccr-bi-directional-replication

We mention the following in the docs:
>This configuration is useful for index-only workloads, where no updates to document values occur. In this configuration, documents indexed by Elasticsearch are immutable. Clients are located in each datacenter alongside the Elasticsearch cluster, and do not communicate with clusters in different datacenters.

However it's not clear if it's a hard requirement or not.

The following example should help understand it better:

>Follower indices will reject writes. For example, if Doc-1 is indexed by Cluster-A and then replicated to Cluster-B, if a client connects to Cluster-B and attempts to update Doc-1, the update request will fail. In order to update Doc-1, the client would need to connect to Cluster-A.

Thanks.

**Comment by abprash** [comment]
@octavioranieri I have opened a pull request for this doc update. Can you please review ?
I proceeded, to do, since there weren't any updates for 28 days.

**Comment by lockewritesdocs** [comment]
@abprash, thanks for your contribution. I think that the provided text needs some clarification, which I attempted in #72266.
