### ISSUE TITLE
RestClient injects (default) port number in the Host header

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#71026]
When using `RestHighLevelClient` to communicate with Elasticsearch at some https://example.org outgoing requests have the `Host` header with the port number:
```
Host: example.org:443
```

From technical perspective this is fine. But in practice this causes various problems.
For instance Ambassador [does not handle](https://github.com/datawire/ambassador/issues/2276) such values correctly when applying its mappings. (I get HTTP 200 in a browser which does not use port in the `Host` header and HTTP 404 when accessing the same address with `RestHighLevelClient`)

Would you consider not injecting the port number into outgoing requests `Host` header?

If I understand correctly the injection happens here:
https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L213

`BasicAuthCache` transforms a host to turn it into a key. And then this "normalized" value is used in the `Host` header.

**Comment by sabi0** [comment]
This is the workaround I have to use now to overcome this issue:
```
		clientBuilder.setDefaultHeaders(new Header[] {
				new BasicHeader("Host", "example.org")
		});
```

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
