### ISSUE TITLE
Test failure - WildcardField testFetchMany

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#71040]
The code added by @nik9000 found a seed that causes an error:

Repro line:
     ./gradlew 'null' --tests "org.elasticsearch.xpack.wildcard.mapper.WildcardFieldMapperTests.testFetchMany" -Dtests.seed=EC1737B3C05F519E -Dtests.locale=mgo -Dtests.timezone=Etc/GMT-8 -Druntime.java=14

From 91c700bd99e59d099cee282fe5b4a1a266f70748

>We've had a few bugs in the fields API where is doesn't behave like we'd
expect. Typically this happens because it isn't obvious what we expct. So
we'll try and use randomized testing to ferret out what we want.

**Comment by cbuescher** [comment]
I think this was fixed with https://github.com/elastic/elasticsearch/pull/71068
