### ISSUE TITLE
[CI] "search.aggregation/370_doc_count_field" fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#71088]
**Build scan**: https://gradle-enterprise.elastic.co/s/4wjbqwc44lbve

**Repro line**:

```
./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" -Dtests.method="test {yaml=search.aggregation/370_doc_count_field/Test filters agg with doc_count}" -Dtests.seed=40FC123A004D9768 -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Canada/Yukon -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.12

**Failure excerpt**:
```
  2> java.lang.AssertionError: Failure at [search.aggregation/370_doc_count_field:180]: field [profile.shards.0.aggregations.0.debug.segments_with_doc_count] is not greater than or equal to [1]
    Expected: a value equal to or greater than <1>
         but: <0> was less than <1>
```

**Comment by martijnvg** [comment]
Another instance on the 7.12 branch: https://gradle-enterprise.elastic.co/s/s4m4gdib64v7g/tests/:rest-api-spec:yamlRestTest/org.elasticsearch.test.rest.ClientYamlTestSuiteIT/test%20%7Bp0=search.aggregation%2F370_doc_count_field%2FTest%20filters%20agg%20with%20doc_count%7D#1

**Comment by mark-vieira** [comment]
Failed again today so I've muted this in 7.12 with 74e31467bdcd5faa80126d727a5a6ab8ef8fc231.

**Comment by nik9000** [comment]
This happens because we end up with two shards and all of the docs with `_doc_count` end up on one shard. Then it happens to come second in the list. Fun times. I'll drop this assertion because we still have one for this in `AggregationProfilerIT`.
