### ISSUE TITLE
Marvel: Can we please show the following Node info ?

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#7111]
Can we please see some hardware/OS info for the server a given node is running on?

Cpu: num cores/procs, arch, brand/model
OS: name, version, distro, etc

Its useful, when managing a number of different nodes running on different servers, to be able to see if a given node is running on an odd piece of hardware (usually the result of a linux VM mis-configuration)

**Comment by clintongormley** [comment]
@tlrx @simianhacker an idea from marvel 1

**Comment by clintongormley** [comment]
This issue was moved to elastic/x-plugins#4183
