### ISSUE TITLE
Docker build task fails on CentOS 8 ARM CI workers

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71138]
I'm seeing a very strange thing. Building our Docker images on the new CentOS ARM workers is failing due to a missing command, specifically `addgroup`. Sure enough, this utility doesn't exist on those machines. My question is, why does it matter? This command is being executed inside the _container_ so why would the setup on the host machine make any difference? Building the image on an Ubuntu host where `addgroup` exists works just fine. Am I missing something here?

https://gradle-enterprise.elastic.co/s/ee3bnyz42wxei/console-log?task=:distribution:docker:buildAarch64DockerImage#L8552

**Comment by mark-vieira** [comment]
@pugnascotia There's something obvious I'm missing, right?

**Comment by mark-vieira** [comment]
I already checked to see if possibly the templated `Dockerfile` differed in some way between the two environments and they are identical with the exception of timestamps.

```
$ diff Dockerfile Dockerfile.ubuntu 
236c236
< LABEL org.label-schema.build-date="2021-03-31T17:56:58.918160148Z" \
---
> LABEL org.label-schema.build-date="2021-03-31T16:07:17.857400544Z" \
246c246
<   org.opencontainers.image.created="2021-03-31T17:56:58.918160148Z" \
---
>   org.opencontainers.image.created="2021-03-31T16:07:17.857400544Z" \
```

Running `docker build` manually in the generated context gives me the same result as well, so it's nothing funny to do with the Gradle integration.

**Comment by pugnascotia** [comment]
Uh...that's weird. I guess if `busybox --list-full` on ARM didn't include `addgroup` then we wouldn't create a link for it. But that would be really peculiar, and would have failed before now, surely.

**Comment by mark-vieira** [comment]
Right, but wouldn't it _also_ blow up on the ubuntu arm machine as well?

**Comment by pugnascotia** [comment]
You'd think so. I also just build the image on my Mac M1 and it was fine.

**Comment by mark-vieira** [comment]
Ok, it's not due to the command missing on the host. Changing `addgroup` to `groupadd` results in the same error despite the later being on the host. Ok, so that makes sense.

My guess is the whole copying from rootfs stuff isn't behaving the way we want. Comparing `docker info` between centos and ubuntu this is the only meaningful part.

```<   Backing Filesystem: xfs
---
>   Backing Filesystem: extfs
```

So CentOS is using XFS whereas Ubuntu extfs.

**Comment by mark-vieira** [comment]
Aha!

```
/bin/sh: /rootfs/bin/busybox: cannot execute binary file: Exec format error
```

Are we downloading the wrong busybox? This is typically the error you get when you try to run x86 on aarch64 or vice versa. Investingating...

**Comment by mark-vieira** [comment]
Yeah, so something is busted with their public build on CentOS 8. CentOS is a much older kernel than ubuntu, so maybe that's the incompatibility? Interestingly enough, I can run the `busybox` docker image just fine. So maybe a workaround would be to instead of downloading the busybox binary, do a `FROM busybox` to copy the bits we need?
