### ISSUE TITLE
Retrying transient network errors for high level rest client bulk processor

### ISSUE THREAD

**Issue by levzem** [elastic/elasticsearch#71159]
The bulk processor exposes some retry configurations but on further examinations we have found that the bulk processor only retries https://github.com/elastic/elasticsearch/blob/4ce162a3dcd4a5797baeb7a9754f28588651849f/server/src/main/java/org/elasticsearch/action/bulk/Retry.java#L110-L111 on too many requests. It does not retry any network related exceptions such as `ConnectTimeout` or `SocketTimeout` which could result from a transient network error. 

Is there are a reason for this? It would be great the `BulkProcessor` also retried those network errors or at least exposed some way of specifying which errors to retry. 

We have completely migrated our [Kafka Connect Elasticsearch connector](https://github.com/confluentinc/kafka-connect-elasticsearch/) over to the high level rest client with the expectation it will provide some error handling out of the box for us.

We have [customers who are running into these issues](https://github.com/confluentinc/kafka-connect-elasticsearch/issues/502) and would be great if the `BulkProcessor` natively supported that. It is possible to roll our own solution but it does complicate things with a multi-threaded async request model that the `BulkProcessor` provides.

**Comment by ilanjiR** [comment]
@elastic/es-core-features is there an approximate timeline for looking at this?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
