### ISSUE TITLE
[CI] TestFeatureResetIT testMLFeatureReset failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71150]
This happened in intake immediately following https://github.com/elastic/elasticsearch/commit/60f4d22722051ef918b8fe3892aaec2b538b287d.

**Build scan**:
https://gradle-enterprise.elastic.co/s/x3ekuehn4i7to/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.TestFeatureResetIT/testMLFeatureReset#1

**Repro line**:
`./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureReset" -Dtests.seed=BAB828D42FB807AB -Dtests.security.manager=true -Dtests.locale=ar-BH -Dtests.timezone=Asia/Damascus -Druntime.java=11`

**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.TestFeatureResetIT&tests.test=testMLFeatureReset

**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.TestFeatureResetIT > testMLFeatureReset FAILED
    java.lang.AssertionError: 
    Expected: an empty array
         but: array size was <7>
        at __randomizedtesting.SeedInfo.seed([BAB828D42FB807AB:E71CB02FAD5AF2B]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.lambda$testMLFeatureReset$2(TestFeatureResetIT.java:82)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:958)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:931)
        at org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureReset(TestFeatureResetIT.java:82)
```

**Comment by mark-vieira** [comment]
Muted in `master` with 67d98c6638a7fb842132c965c1d9ca23acf387d6.

**Comment by mark-vieira** [comment]
@williamrandolph not sure if related but your intake build was the first for this to fail in. Mind taking a look?

**Comment by benwtrent** [comment]
This is probably an ML related failure. But it is interesting that the reset feature API didn't end up deleting any indices :/

Looking at logs.

**Comment by benwtrent** [comment]
I see issue. The ML team writes out custom node settings for this particular test runner. Those settings were not adjusted to handle the destructive action change. 

PR soon.

**Comment by benwtrent** [comment]
closing this issue as the test is fixed and the real problem is described here: https://github.com/elastic/elasticsearch/issues/71178
