### ISSUE TITLE
Sum aggregates returns unexpected results

### ISSUE THREAD

**Issue by georgiantanase-jg** [elastic/elasticsearch#71184]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3

**OS version** (`uname -a` if on a Unix-like system): Windows / Directly on kibana dashboard

**Description of the problem including expected versus actual behavior**: returning the sum aggregates returns unexpected results - one result has a lot of precision, the other one seems to have dropped the digits when summing the elements. For example summing those Value elements: **4625.4, 1000, 160934.4, 16093.44, 500, 5177.2, 3728.9**, returns **192057**, which is wrong, because the real result is **192059.34**. The result returned by the query seems to sum those elements by dropping their precisions at all. For another property, with the Elevation values: **3.9, 0, 3.048, 6.096, 20, 2.5, 0**, it returns **35.54400038719177**, which has much more precision than its underlying elements.

I have tested with other pages and all of them have unexpected behaviour. And I know this https://en.wikipedia.org/wiki/Kahan_summation_algorithm algorithm has been updated to be used for sums. What I expect is that this is happening because of the precision of underlying elements - as you can see the elevation examples have 3 digits after the dot, while the other ones have a 2.

**Steps to reproduce**:

The index document has those values, among others
```
[DataMember(Name = "pageShortName")]
public string PageShortName { get; set; }

[DataMember(Name = "elevation")]
public decimal Elevation { get; set; }

[DataMember(Name = "value")]
public decimal Value { get; set; }
```

With the values:
Value elements: 4625.4, 1000, 160934.4, 16093.44, 500, 5177.2, 3728.9
Elevation values: 3.9, 0, 3.048, 6.096, 20, 2.5, 0
PageShortName: page-name

And this is how I query

```
GET /index/Aggregations/_search?typed_keys=true
{
  "query": {
    "term": {
      "pageShortName.keyword": {
        "value": "page-name",
        "boost": 2
      }
    }
  },
  "aggs": {
    "total_sum": {
      "sum": {
        "field": "value"
      }
    },
    "total_elevation": {
      "sum": {
        "field": "elevation"
      }
    }
  }
}
```

And this is what I get

`  "aggregations": {
    "sum#total_elevation": {
      "value": 35.54400038719177
    },
    "sum#total_sum": {
      "value": 192057
    }
  }`

**Comment by nik9000** [comment]
We'll have a lot better time reproducing the issue if you add reproduction steps in the dev-tools language that you used for the search, including creating the index from scratch.

> The result returned by the query seems to sum those elements by dropping their precisions at all.

Just a wild guess, but if you didn't send us a mapping for the value field up front and your first value didn't have a decimal part we'd index it as a `long`. When new documents showed up with decimal parts we'd throw those parts away.

**Comment by imotov** [comment]
@georgiantanase-jg thank you for your bug report! What @nik9000 meant was that reproductions like this typically helps with identifying the issue faster and with more certainty:

```
DELETE test

POST /test/_bulk?refresh
{"index": {}}
{"val":  1000}
{"index": {}}
{"val":  4625.4}
{"index": {}}
{"val": 160934.4}
{"index": {}}
{"val": 16093.44}
{"index": {}}
{"val": 500}
{"index": {}}
{"val": 5177.2}
{"index": {}}
{"val": 3728.9}

POST /test/_search?filter_path=aggregations
{
  "size": 0,
  "aggs": {
    "sum": {
      "sum": {
        "field": "val"
      }
    }
  }
}
```
As you can see from the example above @nik9000's guess is most likely correct, since if val is automatically mapped as long due to the first value that was received being long, you will get result of summation of long values (since this is how they are stored in the index). 

To avoid that, you need to either send numbers with decimal points `1000.0` instead of `1000` or specify the mapping before sending the first record to the index. Adding this after DELETE fixes that issue:
```
PUT test
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "val": {
        "type": "double"
      }
    }
  }
}

```
By the way if you are new to elasticsearch, our forum https://discuss.elastic.co/ might be a better place to resolve misunderstandings like this one.

**Comment by imotov** [comment]
Since there is no response, I assume that our explanation was satisfactory and close the issue. Please, feel free to reopen the issue if my assumption is not correct.

**Comment by georgiantanase-jg** [comment]
@imotov @nik9000 we don't have a specific mapping for those. We just add the elements. I perfectly understand what you are saying, but it's curious that those individual elements have precision, but the sum of them takes rid of it. 

My example is a subset of a much bigger document, everything happening in .net. The only thing that I did in dev-tools was the manual request, to check for myself that it's not the code, but the request itself.

@imotov I am curious on your POST example. If you try to get the results back, are they all saved as long

**Comment by imotov** [comment]
> If you try to get the results back, do they have the precision?

@georgiantanase-jg, it is important to understand, that values of these fields are stored in elasticsearch essentially twice - 1) in its original JSON form that you sent for indexing and 2) as individually indexed fields, that are used for search and aggregation operations. In the first case the values are stored exactly as you sent them, in the second case the value are indexed based on the mapping. To reiterate, when you retrieve a document using source, you will get these values in their original form, when you perform the aggregation operation they will be retrieved as longs if they were mapped as longs. Please, take a look at [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/documents-indices.html#documents-indices) for more information about this process.

**Comment by georgiantanase-jg** [comment]
@imotov perfect. Thanks a lot for all the information. I will create a new index with strict mappings and reindex all the documents from the current one, remove the old one, and rename the current one so it feels like no changes happen. You were really helpful!

**Comment by imotov** [comment]
@georgiantanase-jg great! If you have any further questions, please don't hesitate to ask on our forum https://discuss.elastic.co/
