### ISSUE TITLE
Doc+: TLS reload polling

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#71234]
Hiya team! ES v7.8 docs has the following line

> Elasticsearch monitors all files such as certificates, keys, keystores, or truststores that are configured as values of TLS-related node settings. If you update any of these files (for example, when your hostnames change or your certificates are due to expire), Elasticsearch reloads them. The files are polled for changes at a frequency determined by the global Elasticsearch resource.reload.interval.high setting, which defaults to 5 seconds.
> https://www.elastic.co/guide/en/elasticsearch/reference/7.8/configuring-tls.html#tls-transport

This isn't referenced in v7.12

> https://www.elastic.co/guide/en/elasticsearch/reference/7.12/configuring-tls.html

But I assume is still true. Will you consider re-adding the content / adding what's true now for cross-version knowledge parity?

Change introduced: https://github.com/elastic/elasticsearch/pull/68946

**Comment by jrodewig** [comment]
@lockewritesdocs  Gonna assign this to you as it's related to #68946. Thanks!

Thanks for letting us know about this @stefnestor!
