### ISSUE TITLE
Pipeline doesn't inherit all default fields from ES

### ISSUE THREAD

**Issue by cohen-ro** [elastic/elasticsearch#71250]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.2/7.12

**JVM version** (`java -version`): dockerised and 7 i think on VM

**OS version** (`uname -a` if on a Unix-like system): Darwin Mrs-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 and Ubuntu 20.04 LTE

**Description of the problem including expected versus actual behavior**:

Pipeline doesn't inherit default fields from elasticsearch, therefore default dashboards doesn't load properly as they miss fields.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Simple pipeline filebeat => elasticsearch will receive in filebeat index 5509 fields see here https://ibb.co/8Mbf8nG
 2. If I use a complex pipeline as filebeat => kafka => logstash => elasticsearch I receive only 200 see here https://ibb.co/sjYCHGp
 3.  Due to this thing, default dashboards from filebeat are not working, as they don't have the default fields see here https://ibb.co/fpXNh35 and https://ibb.co/Mc0Tz5R
 4. What setting should I do to overcome this

This is a simple code that doesn't upload all the fields from ES within ES so defualt dashboards are not loading.
```
input {
  beats {
    port => 5044
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://es01:9200","http://es02:9200","http://es03:9200"]
    index =>  "filebeat-%{+dd.MM.yyyy}"
    ecs_compatibility => disabled
  }
}
```

What settings should I do in order to get all the fields within filebeat's index pattern?

**Comment by danhermann** [comment]
Hi @cohen-ro . Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by cohen-ro** [comment]
I did asked there, but had no answer
