### ISSUE TITLE
Deleting 300k stale blobs from an Azure repo leads to an OOM

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#71267]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Plugins installed**: Cloud + `repository-azure`

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

We received a report of a cluster running on Azure where the master would fail with an OOME every 30 minutes. A heap dump suggests it was trying to delete some 300k stale blobs from the repository at the time.

**Steps to reproduce**:

Currently unknown how we got into this state, but once in this state it can't get out of it.

**Provide logs (if relevant)**:

See linked support case for logs/diagnostics/heap dump and other info.

**Comment by original-brownbear** [comment]
It's not too unlikely to get into this state IMO in case of a large repo and running a delete of a large snapshot or multiple snapshots across many indices. The issue specific to Azure here is that we don't have bulk deletes in Azure and with the new SDK seem to be running all those deletes in parallel. I'll code up a fix for that this morning.
