### ISSUE TITLE
Clean up reproduction lines

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#71290]
Right now our reproduction lines are quite long:

```
 ./gradlew ':docs:integTest' \
  --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/query-dsl/script-query/line_24}" \
  -Dtests.seed=B3D5CA1269773632 -Dtests.security.manager=true \
  -Dtests.locale=zh-HK -Dtests.timezone=PNT -Druntime.java=16
```

So long I have to manually wrap them for them to be visible properly on github. I wonder if we can remove some of these and still get all the reproduction lines. Like, I think `tests.security.manager` is always set by the build and folks rarely override it. Maybe we could write it only if you've manually overridden it yourself?

I think we also write the `tests.rest.suite` and `tests.rest.blacklist` but those are both *generally* set by the build and not on the command line. I think maybe we should only log those if they were set on the command line when invoking the build. Or when they differ from how the build would configure them. Or something like that.

I think logging these on failure is bad because it makes the line too long to be readable. And if you *try* to read it then you end up asking yourself "why did we include this bit?" quite frequently.

**Comment by mark-vieira** [comment]
> I think maybe we should only log those if they were set on the command line when invoking the build. Or when they differ from how the build would configure them. Or something like that.

Yeah, I'm not sure how the reproduction line printer would detect such a thing. All it's doing is looking at system properties. To the tests, there's no distinction between a system property set in a build script or one set via CLI properties.

**Comment by nik9000** [comment]
`tests.security.manager` it could probably just never emit. Its super rare folks mess with that one and when they do they know they did.

I wonder if we could also drop the whitelist and blacklist because its *job* is to control which tests to run. But we *already* control which test to run in the reproduction line.

**Comment by mark-vieira** [comment]
> I wonder if we could also drop the whitelist and blacklist because its job is to control which tests to run. But we already control which test to run in the reproduction line.

Agreed. I think this is the worst offender in most cases.
