### ISSUE TITLE
Add closeTo assertion to yaml tests 

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#71303]
In the aggregation tests we frequently work with double values and due to several factors we frequently end up with different rounding errors. The current work-around for this is to use `lte`/`gte` pairs:

```
  - gte: {hits.hits.0._score: 65425.62}
  - lte: {hits.hits.0._score: 65425.63}
  ```

It's working but a bit kludgy. We would like to improve support for floating point numbers in yaml tests by adding close_to assertions, so the fragment above would become:

```
  - close_to: {hits.hits.0._score: 65425.625, error: 0.005}
```

Alternatively, in order to avoid clashing with `error` field, we can make it:
```
  - close_to: {hits.hits.0._score: { value: 65425.625, error: 0.005}}
```
WDYT?

**Comment by joegallo** [comment]
Just thinking aloud, but a different approach would be that `match:` could 'just' assume that a difference of some reasonable epsilon is acceptable for all float and double comparisons.

That is `- match: { count: 2}` 2 is an int, so therefore it has to be actually equal. But `- match: { count: 2.0}` would be okay with 1.9999999 and 2.00000001 or what have you. I suppose that choosing the right "reasonable epsilon" would be the trick. 😄

**Comment by imotov** [comment]
Indeed picking the "reasonable epsilon" is one issue. Another interesting and somewhat related issue is type conversion. While researching this issue I stumbled upon this interesting fragment:

```
  - lte: { indices.test_index.filter.bool.boost: 1.0 }
  - gte: { indices.test_index.filter.bool.boost: 1.0 }
```
It was added with the following comment:
> Because of the way Perl treats numbers, the boost is represented as 1 instead of 1.0, which caused this test to fail.

Not really sure how relevant this is at the moment.

**Comment by nik9000** [comment]
I like `close_to` instead of `match` picking a reasonable default because:
1. I *suspect* what constitutes as reasonable changes from context to context
2. Sometime you want exact assertions
3. It mirrors hamcrest's `closeTo`

I'm certainly willing to be wrong, but it feels like adding `closeTo` is reasonable.

**Comment by joegallo** [comment]
> It mirrors hamcrest's `closeTo`

Ooh, nice, given that's theres a nearby analogous thing with the same name, then I withdraw my previous suggestion. +1 to `close_to`.

**Comment by dakrone** [comment]
I think I prefer to be explicit about the fuzziness, rather than have `match` differ depending on an integral or floating point number. As long as its not named `close` (to avoid the homonym), `close_to` with `error` seems good to me

**Comment by jakelandis** [comment]
Added a few more labels for awareness.

**Comment by rjernst** [comment]
> I think I would prefer to be explicit about the fuzziness

I would go a step further, and say we should always match exactly. Why would we not know the exact value that should be returned? Being fuzzy is equivalent IMO of saying we don't understand how the underlying value is calculated or how it is rendered. If the value is inconsistent, this should be considered a bug. We should always know exactly what will be returned.

**Comment by imotov** [comment]
> I would go a step further, and say we should always match exactly. 

@rjernst and @sethmlarson  I agree, that would be awesome. Unfortunately, I don't think it is realistic at the moment. To achieve this we would need to sprinkle `strictfp` everywhere we do floating point calculation and somehow make segmentation, replication and merging of records deterministic to avoid glaring issues like #3578 as well as less subtle issues where distribution of records by segments can affect the order of calculations ever so slightly and change the end results.

> Being fuzzy is equivalent IMO of saying we don't understand how the underlying value is calculated or how it is rendered.

I think we understand pretty well how the underlying value is calculated. But we also understand that there are difficult to control factors that can affect exactly how this value is calculated and we make a deliberate choice not to enforce the deterministic order of calculations due to prohibitively high cost in terms of complexity, performance of both.

**Comment by rjernst** [comment]
> I think we understand pretty well how the underlying value is calculated.

Sorry, my choice of words was poor. I meant more that if we are testing a value, we should test what we expect the value to be.

But this brings me to a broader question. If score is the main issue, why are we checking the returned score? We tell users never to do this, because the actual value of the score does not matter. Instead, the relative order matters. Can we just remove such yaml assertions?

**Comment by ezimuel** [comment]
@imotov if I understood the goal of this proposal is to have a better operator to capture the **≈** math approximation. Why not use `almost equal` with an `epsilon` option?
```
-  almost_equal: {hits.hits.0._score: { value: 65425.625, epsilon: 0.005}}
```

**Comment by imotov** [comment]
@rjernst I didn't review all tests related to the score, so I am not sure how feasible your proposal is there. It might be since in most cases we only care about the order there. I don't think it would solve the issue for aggregations though, where the order the results are calculated in are not important, and if intermediate results are calculated with 80 bit precision instead of 64 bit precision they are still good if not better. What we care about in these test is that the actual results are close to the expected results within an expected margin of error. We are dealing with floating point here, so we cannot eliminate the error. The best we can do is to make the error deterministic, but it is quite an effort with non trivial cost and some limited benefits to the end users. So, I am not sure I am completely sold on your proposal here.

@ezimuel We have 600+ usages of hamcrest's closeTo() in our integration and unit tests. So I based my proposal on the fact that it is commonly used and very familiar to developers. I am open for other naming suggestions though, especially if this is already implemented somewhere.
