### ISSUE TITLE
Deprecate legacy template API endpoints

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#71307]
To give users as much notice as possible that they're being replaced by component templates.

**Comment by willemdh** [comment]
@danhermann  When exactly will legacy templates be deprecated?

**Comment by danhermann** [comment]
> @danhermann When exactly will legacy templates be deprecated?

@willemdh, [they were deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/indices-templates-v1.html) in the 7.8 release of Elasticsearch. They will remain completely functional throughout the 7.x release cycle which will continue for a while. In most cases, the transition from legacy index templates to their replacement, [composable index templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/index-templates.html), is quite straightforward. The work in this PR is just to add deprecation warning headers to the HTTP responses from APIs that operate on legacy index templates.
