### ISSUE TITLE
[DOCS] Move Grok syntax docs to separate reference page

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#71404]
Currently, our Grok syntax docs reside in the [Grok ingest processor docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/grok-processor.html).

Now that runtime fields also support Grok, we should consider moving those docs into a separate reference section.

Relates to #72580

**Comment by lockewritesdocs** [comment]
This is also true for Dissect. Looking ahead, runtime field will start supporting other processing options, so we might need a new section that's part of our [scripting docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html).
