### ISSUE TITLE
YamlRestCompatTests isn't compatible with the MavenFilteringHack 

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#71434]
The `MavenFilteringHack` is used to conditionally replace values like `${base_path}` inside YAML REST tests with values defined build.gradle. The usage looks similar to :

```
Map<String, Object> expansions = [
  'base_path': foo + "_integration_tests"
]

tasks.named("processYamlRestTestResources").configure {
  inputs.properties(expansions)
  MavenFilteringHack.filter(it, expansions)
}
```
This does the replacement work too early in the lifecycle for it get applied to the copied REST compat tests (if trying to configure the compat resources). Ideally this type of change to the test would be done via a task that can be wired into the build where it makes it makes the most sense. (Also seems like a party foul to do this at configuration time). FWIW, given the implementation detail of `static void filter(CopySpec copySpec, Map substitutions)` very few tasks satisfy the CopySpec type making the `MavenFilteringHack` fairly brittle.

**Comment by mark-vieira** [comment]
I agree we should make this more of a first-class thing.

> Ideally this type of change to the test would be done via a task that can be wired into the build where it makes it makes the most sense.

Technically it is. It's done primarily by the processResources task.

> Also seems like a party foul to do this at configuration time

It's not. What we are dong at configuration time is registering a filter. The actual work is done with the task the filter is added to is executed.

> FWIW, given the implementation detail of static void filter(CopySpec copySpec, Map substitutions) very few tasks satisfy the CopySpec type making the MavenFilteringHack fairly brittle.

Basically all the tasks that deal with rest apis specs and tests are `Copy` tasks which are compatible with this API. We can just as well add the filtering hack to `copyRestCompatTestTask`, which would do the replacements for those tests as well.

**Comment by jakelandis** [comment]
Thanks for the clarification around what `MavenFilteringHack` is actually doing. 

> Basically all the tasks that deal with rest apis specs and tests are Copy tasks which are compatible with this API. 

In spirit they are ...but they are technically `DefaultTask` on the surface it looks like a pretty easy swap over to a `Copy` task, but I suspect that there are few gotchas along the way.

**Comment by mark-vieira** [comment]
> In spirit they are ...but they are technically DefaultTask on the surface it looks like a pretty easy swap over to a Copy task, but I suspect that there are few gotchas along the way.

Ah, you're right. It would be trivial to expose a `filter()` method on those tasks that simply delegated to the individual `FileSystemOperations.copy()` calls in the task implementation.
