### ISSUE TITLE
[CI] JdbcSqlSpecIT testWildcardWithLimit: Different result for column [birth_date_day_of_week]

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#71442]
**Build scan**:
https://gradle-enterprise.elastic.co/s/bp3vxhz3nious
https://gradle-enterprise.elastic.co/s/xhjwnxm5wimvk

**Repro line**:
`./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT" -Dtests.method="test {select.testWildcardWithLimit}" -Dtests.seed=5CE74B2A4B99DC21 -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=America/Moncton -Druntime.java=11`

`./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT" -Dtests.method="test {select.testWildcardWithOrderWithLimit}" -Dtests.seed=5CE74B2A4B99DC21 -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=America/Moncton -Druntime.java=11`

` ./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT" -Dtests.method="test {select.testWildcardWithOrder}" -Dtests.seed=5CE74B2A4B99DC21 -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=America/Moncton -Druntime.java=11`

etc
**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure excerpt**:
```
org.junit.ComparisonFailure: Different result for column [birth_date_day_of_week], entry [1] expected:<[Tu]esday> but was:<[Wedn]esday>
```

It seems related to https://github.com/elastic/elasticsearch/pull/71356/, these pass before that change and fail after.

**Comment by astefan** [comment]
Yes, definitely related to my PR. I think I know why it happens. Will look into it.
