### ISSUE TITLE
[DOCS] Update mapping API must specify an index name

### ISSUE THREAD

**Issue by lockewritesdocs** [elastic/elasticsearch#71469]
You must specify an index name when updating an index mapping. A request with `PUT /_mapping` fails with this error:

```
{
  "error" : "Incorrect HTTP method for uri [/_mapping?pretty=true] and method [PUT], allowed: [GET]",
  "status" : 405
}
```

The [Update mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/indices-put-mapping.html) page includes this example request:

```
PUT /<target>/_mapping

PUT /_mapping
```

The second example without an index name is incorrect and must be removed.

**Comment by jrodewig** [comment]
Thanks for spotting this @lockewritesdocs. Can you also fix the request path parameter? It should be listed as "Required," not "Optional:"

<img width="736" alt="Screen Shot 2021-04-08 at 8 58 13 AM" src="https://user-images.githubusercontent.com/40268737/114030638-99c7af80-9848-11eb-9b3c-7c3145038ae3.PNG">

**Comment by lockewritesdocs** [comment]
@jrodewig, absolutely! Appreciate your keen 🦅 👁️
