### ISSUE TITLE
Elasticsearch response have data but always return total hit is 0

### ISSUE THREAD

**Issue by NinhNM** [elastic/elasticsearch#71460]
I have use ELS 7.11. I make single query with multiple condition

**Query:**

    {
  "bool" : {
    "filter" : [
      {
        "term" : {
          "loa" : {
            "value" : "2",
            "boost" : 1.0
          }
        }
      },
      {
        "term" : {
          "gender" : {
            "value" : "1",
            "boost" : 1.0
          }
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}

**Response:** 
"took":16,"timed_out":false,"_shards"{"total":1,"successful":1,"skipped":0,"failed":0}, "hits":{"total":0,"max_score":0.0,"hits":[{"_index":"", "_id":"9354", "username":"NguyenGeo"}]
I want use total make pagination for website, response have data but hits:total always is 0

**Comment by cbuescher** [comment]
Hi @NinhNM! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
