### ISSUE TITLE
Data-containing data tiers roles are not mapped onto `DATA` legacy role

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#71464]
**Elasticsearch version** (`bin/elasticsearch --version`): Rolling upgrade from <7.3 to ≥7.10

**Description of the problem including expected versus actual behavior**:

We have special handling for mapping the new pluggable master/data/ingest roles onto their legacy counterparts when talking to pre-7.3 nodes which did not support pluggable roles:

https://github.com/elastic/elasticsearch/blob/941b028d375ed3f48d148f257a6a1c57a77d2d05/server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java#L332-L344

However this code does not use `DiscoveryNodeRole#getCompatibilityRole()` so it does not map the data-tiers-related roles `DATA_{HOT,WARM,COLD,FROZEN}` onto the legacy data role.

Relates #60994 and #63581 so I'm labelling this similarly.

**Comment by andreidan** [comment]
Closing as fixed by #71628
