### ISSUE TITLE
colon sign (:) not excluded from filenames

### ISSUE THREAD

**Issue by picrin** [elastic/elasticsearch#7148]
Colon is not excluded from the list of invalid file names in org.elasticsearch.common.Strings.java in line 683. Mentioned line should read:

public static final ImmutableSet<Character> INVALID_FILENAME_CHARS = ImmutableSet.of('\\', '/', '*', '?', '"', '<', '>', '|', ' ', ',', ':');

This bug causes crash to elasticsearch on Windows with following curl line:
curl "http://localhost:9200/bitcoin:9200" -X POST

Here's the link to the code:
https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/Strings.java#L683

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/9059
