### ISSUE TITLE
[Feature Request] Highlighting API with provided document

### ISSUE THREAD

**Issue by jessebs** [elastic/elasticsearch#71511]
I have a lot of documents stored in their own system.  I'm investigating the use of ElasticSearch for both searching and highlighting.  Storing source, however, is a no-go because of the quantity of documents and the fact that it will significantly increase our storage requirements.

I think I could do what I'm looking for if there was a change to ElasticSearch, but I don't know how feasible it would be.  Would it be possible to add an endpoint to ES to highlight a document that is passed in?  

The workflow would be something like:
1. Add documents to ES (with _store disabled)
2. Search for the documents
3. For the hits that I get back, provide the full document to a new ES endpoint as well as the initial search terms
4. Receive the highlighting as a response to this endpoint even though the document itself was never stored in ES

**Comment by jtibshirani** [comment]
Hello @jessebs, sorry for the slow response. We don't plan to add a new endpoint where you can provide both a search and documents, then receive highlights for those documents. The main downside is that every search would require a follow-up request containing a potentially very large amount of data (all the hit documents).

A better approach would be to expose match information in search results, which the user could apply to the original documents produce highlights. We've discussed integrating the Lucene matches API in the past (https://github.com/elastic/elasticsearch/issues/29631), but ran into difficulties around encodings and ended up putting it aside. I think your use case is a good example of how that API would be valuable -- I'll make a note of that. Unfortunately we don't have short-term plans to work on the API.
 
If you're willing to dive into the plugin framework, it could also be possible to build a custom endpoint or highlighter to immediately support what you're after.

**Comment by jessebs** [comment]
I'd love to go a custom highlighter plugin but i can't find any documentation on implementing a highlighter, not any reference to a HighlighterPlugin or anything similar in the plugin API.  Do you have any suggestions?

**Comment by jtibshirani** [comment]
Unfortunately we don't have great documentation around our plugin APIs. You might find this repository helpful as an example of how to create and build a highlighter plugin: https://github.com/wikimedia/search-highlighter. The main entry point is `ExperimentalHighlighterPlugin.java`.

**Comment by jessebs** [comment]
That's great!  Thank you for the help.

**Comment by jtibshirani** [comment]
No problem! I just noticed that this plugin may support returning offsets instead of snippets: https://gerrit.wikimedia.org/r/c/search/highlighter/+/209956/. Hopefully you are able to track down a solution.
