### ISSUE TITLE
Weird behaviour on the 7.12 version documentation on webpage.

### ISSUE THREAD

**Issue by skayikci** [elastic/elasticsearch#71523]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12 website

**Plugins installed**: NA

**JVM version** (`java -version`):NA

**OS version** (`uname -a` if on a Unix-like system): Mac OS

**Description of the problem including expected versus actual behavior**: The website doesn't reload and the menu below shouldn't be rewritten continuously. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Enter to the link : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html?ref=driverlayer.com/web?ref=driverlayer.com/web
 2. See that the page is reloading and 
 3. See that the menu below the code block is increasing (Copy CurL, Open in Console)

**Provide logs (if relevant)**:
Here is the screenshot.
<img width="1319" alt="Bildschirmfoto 2021-04-09 um 10 03 34" src="https://user-images.githubusercontent.com/3919491/114149898-b2ed6080-991b-11eb-8e4a-58f5e6d3b37b.png">

**Comment by dnhatn** [comment]
It's broken because of the extra parameter: `?ref=driverlayer.com/web?ref=driverlayer.com/web`. I am closing this issue as I am not sure what we can fix. Thank you for your interest in Elasticsearch.
