### ISSUE TITLE
Loop counter in Painless is higher for certain loops after version 7.9.3

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#71584]
@stu-elastic has investigated and discovered refactoring changes have made the internal loop counter in Painless potentially higher for certain types of loops. We are going to do further investigation on which loops are affected by this change and then do a reversion.

**Comment by stu-elastic** [comment]
The statement count is now always decremented when using an iterator, in 7.11 notice the `IINC 1 -1`.
```
    INVOKEINTERFACE java/util/Iterator.next ()Ljava/lang/Object; (itf)
    ASTORE 19
    IINC 1 -1
    ILOAD 1
    ICONST_0
    IF_ICMPGT L37
    NEW org/elasticsearch/painless/PainlessError
    DUP
    LDC "The maximum number of statements that can be executed in a loop has been reached."
    INVOKESPECIAL org/elasticsearch/painless/PainlessError.<init> (Ljava/lang/String;)V
    ATHROW
```

Whereas in 7.9 iterators didn't decrement the loop counter, notice `IINC 1 0`
```
    INVOKEINTERFACE java/util/Iterator.next ()Ljava/lang/Object; (itf)
    ASTORE 19
    IINC 1 0
    ILOAD 1
    ICONST_0
    IF_ICMPGT L36
    NEW org/elasticsearch/painless/PainlessError
    DUP
    LDC "The maximum number of statements that can be executed in a loop has been reached."
    INVOKESPECIAL org/elasticsearch/painless/PainlessError.<init> (Ljava/lang/String;)V
```

Looking at the code, this appears to also be an issue with arrays.

**Comment by jdconrad** [comment]
Loop counter changed in the following:
```def x = []; for (y in x) { int z; }```
```List x = []; for (y in x) { int z; }```
```int[] x = new int[] {}; for (y in x) { int z; }```

**Comment by jdconrad** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/71602
