### ISSUE TITLE
Gradle plugins used by external users are separated from buildSrc project

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71593]
We have a number of plugins that are leveraged by external users to build and test their own Elasticsearch plugins. Right now these reside in `buildSrc` since we use them in our own build. In order to expose these plugins we effectively publish the `buildSrc` JAR by defining a `build-tools` project whose project directory points to `buildSrc`. This causes us all kinds of headaches:

1. We build `buildSrc` twice, once implicitly as the normal `buildSrc` gradle project and again as `:build-tools`.
2. The duplicate existance of the `buildSrc` project causes all kinds of issues with IDE integration and makes the use of Kotlin DSL impossible.
3. Since we publish everything in `buildSrc` we include all sorts of internal stuff not intended for use outside of the Elasticsearch project.
4. The intermingling of this logic makes testing the external builds of `buildSrc` in isolation very hard. To account for this we have `BuildParams.isInternalBuild()` all over the place.

The only way out of this mess is to _physically_ move the code we want to publish so it's completely isolated in a way where it can be built, packaged, published and tested on its own. That said, our build relies on this stuff, so we need to be able to _consume_ these core plugins in our own build as well. There's a little bit of a chicken/egg situation here but I think we can leverage composite builds to get around this. As part of this work we'll want to ensure a few things:

1. Improve documentation for plugin authors. Essentially [this](https://www.elastic.co/guide/en/elasticsearch/plugins/7.12/plugin-authors.html) is all that exists. For the most part we rely on our [examples](https://github.com/elastic/elasticsearch/tree/master/plugins/examples) to act as documentation.
2. Start testing the example plugins properly again.
3. Provide some guidance/docs on testing. We want folks to use the test clusters plugin if they want, but we should give folks _some_ idea of how to actually author REST tests.

**Comment by breskeby** [comment]
For clarification. There are some elastic projects e.g. `elastic/elasticsearch-hadoop` that also rely on build tools. Would we consider those also `external` and only provide them with these external plugins or would there be `elasticsearch internal`, `elastic internal` and `external`? IMO we want only differentiate between `elasticsearch internal` (the build code required by `elastic/elasticsearch` and `external` which is everything else (including third party plugin authors and in house plugin authors like `elastic/elasticsearch-hadoop`.

**Comment by mark-vieira** [comment]
Hadoop should be considered "external", effectively as it is today via `BuildParams.isInternal()` and therefore they would be consumers of the "new" build-tools project just like anyone else. This is another big motivator as right now these two projects are tightly coupled.

**Comment by mark-vieira** [comment]
Can we call this "done"? Just needs to be backported, yes?
