### ISSUE TITLE
Cat indices yaml tests failing

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#71616]
Tests from security/authz/14_cat_indices all fail.

**Build scan**: https://gradle-enterprise.elastic.co/s/nwl4fje4674hu

**Reproduces locally?**: no

**Applicable branches**: master

**Failure excerpt**:

org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=security\authz/14_cat_indices/Test empty request while no-authorized index} FAILED
java.lang.AssertionError: Failure at [security\authz/14_cat_indices:104]: field [$body] was expected to be of type String but is an instanceof [class java.util.ArrayList]

**Comment by jakelandis** [comment]
closing in favor of https://github.com/elastic/elasticsearch/issues/71475 which has more context. This is a windows only issue with the ability to black list a test. (due to the 4 parts it appears to have some odditiies with the backslash)
