### ISSUE TITLE
[CI] RestClientMultipleHostsIntegTests testCancelAsyncRequests failing

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#71610]
Seems to be a suite timeout, and a null pointer caused by the IO reactor being abnormally terminated.

**Build scan:**
https://gradle-enterprise.elastic.co/s/wjn3wlhxzntnc/tests/:client:rest:test/org.elasticsearch.client.RestClientMultipleHostsIntegTests/testCancelAsyncRequests

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.RestClientMultipleHostsIntegTests&tests.test=testCancelAsyncRequests

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([A3D270A8210A0326]:0)

```

**Comment by ywangd** [comment]
Another one: https://gradle-enterprise.elastic.co/s/on4nspu5frs7k

**Comment by astefan** [comment]
And another https://gradle-enterprise.elastic.co/s/ltkiyhwvof5ee
