### ISSUE TITLE
Highlight result not include special characters like $.

### ISSUE THREAD

**Issue by seismic-yu** [elastic/elasticsearch#71622]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 7.12.0, Build: default/zip/78722783c38caa25a70982b5b042074cde5d3b3a/2021-03-18T06:17:15.410153305Z, JVM: 15.0.1

**Plugins installed**: [n/a]

**JVM version** (`java -version`): build-in java (installed by unzip ES zip file)

**OS version** (`uname -a` if on a Unix-like system):
- Windows 10 Enterprise N
- OS build: 19042.867

**Description of the problem including expected versus actual behavior**:
- Actual highlight result: `<em>PLOC</em> $<em>500</em> <em>Referral</em> Bonus for New PLOC Clients Flyer`
- Expect highlight result: `<em>PLOC</em> <em>$500</em> <em>Referral</em> Bonus for New PLOC Clients Flyer`
**Is there a way to include the specific char `$` into highlight results?** Thank you for the help.

**Steps to reproduce**:

 1. create index and doc
> PUT http://localhost:9200/test_customer/_doc/1
```
{
  "title_en": "PLOC $500 Referral Bonus for New PLOC Clients Flyer"
}
```
 2. Search it with below highlight settings
> GET http://localhost:9200/test_customer_02/_search

```
{
    "highlight": {
        "fields": {
            "title_en": {
                "fragment_size": 150,
                "number_of_fragments": 1,
                "type": "plain"
            }
        }
    },
    "query": {
        "match_phrase": {
            "title_en": "PLOC $500 Referral"
        }
    }
}
```

The index settings are listed here:
```
{
    "test_customer_02": {
        "aliases": {},
        "mappings": {
            "properties": {
                "title_en": {
                    "type": "text",
                    "fields": {
                        "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                        }
                    }
                }
            }
        },
        "settings": {
            "index": {
                "routing": {
                    "allocation": {
                        "include": {
                            "_tier_preference": "data_content"
                        }
                    }
                },
                "number_of_shards": "1",
                "provided_name": "test_customer_02",
                "creation_date": "1618299631427",
                "number_of_replicas": "1",
                "uuid": "Hr1BoMs3RJu1zq5h_4dwKw",
                "version": {
                    "created": "7120099"
                }
            }
        }
    }
}
```

**Comment by seismic-yu** [comment]
May someone help take a look at this issue, please?

**Comment by cbuescher** [comment]
@seismic-yu the reason the dollar sign isn't included in the highlighting is that your field is using the [`standard` analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html) which removes any non-alphanumerical character during tokenization. The Highlighter uses the underlying analyzer for that field. If you want that character to be included you could change - for example - to the `whitespace` tokenizer or another tokenizer that better fits your needs. If you want to use a different analyzer for highlighting than for search you also could index the field twice, once into a field used for the search query and then do the highlighting on another fields with similar content but a different analyzer. This comes at the expense of a larger index size though. I hope you don't mind if I close this issue but would like to encourage you asking follow up questions in the support forums over at https://discuss.elastic.co.

**Comment by seismic-yu** [comment]
@cbuescher Thank you very much for your detailed response. I will try both 2 alternatives you suggested. Please go ahead close this ticket. If there is a further question, will post at https://discuss.elastic.co.
