### ISSUE TITLE
Eclipse complaining about classes accesible from more than one module

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#71648]
After importing this morning I'm seeing a ton of:
```
The package org.joda.time.format is accessible from more than one module: <unnamed>, org.joda.time
```

And others.

**Comment by nik9000** [comment]
I'll spend some time debugging this. I don't really have a choice frankly.

**Comment by nik9000** [comment]
This was caused by the update to gradle 7: #69096. It looks like gradle 7 turns on java module support by default.

**Comment by breskeby** [comment]
I'll look into this first thing my morning

**Comment by nik9000** [comment]
@breskeby I opened #71649. Its probably a bad solution, but it does get me unstuck.
