### ISSUE TITLE
elasticsearch-7.10.2 can't be start

### ISSUE THREAD

**Issue by AKA-YoungFresh** [elastic/elasticsearch#71666]
Apr 13 16:15:01 fresh crond[28528]: pam_limits(crond:session): unknown limit item 'noproc'
Apr 13 16:15:01 fresh systemd[1]: Started Session 63371 of user root.
-- Subject: Unit session-63371.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-63371.scope has finished starting up.
-- 
-- The start-up result is done.
Apr 13 16:15:01 fresh CROND[28531]: (root) CMD (sh /opt/ping.sh &)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.elasticsearch.
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/elasticsearch.keys
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:410)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:406)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:254)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:488)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:259)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.cli.Command.main(Command.java:90)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
Apr 13 16:15:18 fresh systemd-entrypoint[28396]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)

**Comment by cbuescher** [comment]
Hi @AKA-YoungFresh! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
