### ISSUE TITLE
ES could not write data

### ISSUE THREAD

**Issue by zhangran2616** [elastic/elasticsearch#71675]
![image](https://user-images.githubusercontent.com/6472032/114677120-93e83780-9d3c-11eb-97a5-e47d1ecd4fc6.png)
![image](https://user-images.githubusercontent.com/6472032/114677161-9fd3f980-9d3c-11eb-8615-297cc3f00e72.png)
![image](https://user-images.githubusercontent.com/6472032/114678159-94350280-9d3d-11eb-8d01-0d01e127a781.png)
ES could not write data

**Comment by cbuescher** [comment]
Hi @zhangran2616! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
