### ISSUE TITLE
else if == else { if () {} }

### ISSUE THREAD

**Issue by Lupo00** [elastic/elasticsearch#71689]
https://github.com/elastic/elasticsearch/blob/f491af65c0946301a85ff0589f24e79dff3d2341/client/rest-high-level/src/main/java/org/elasticsearch/client/common/ProtocolUtils.java#L41

**Comment by jbaiera** [comment]
Not sure if this was opened by accident (wait, Github has comments?), but it does not meet our standards for issue tracking. Closing.
