### ISSUE TITLE
[CI] Integration tests failing on FIPS

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71699]
Looks like some stuff related to security by default have busted all the FIPS builds on `7.x`.

https://gradle-enterprise.elastic.co/s/n4ppzh66df5v6

```
org.elasticsearch.test.rest.ClientYamlTestSuiteIT > test {yaml=search/200_ignore_malformed/_ignored is returned by default} FAILED
    org.elasticsearch.client.WarningFailureException: method [GET], host [http://[::1]:34575], URI [_nodes/plugins], status line [HTTP/1.1 200 OK]
    Warnings: [Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.]
```

**Comment by mark-vieira** [comment]
If we don't have a quick fix for this we might want to consider temporarily disabling FIPS notifications.

**Comment by jkakavas** [comment]
Let's not pull this trigger just yet. We'll look into it and update here shortly

**Comment by mark-vieira** [comment]
Ok, I suspect this is more fallout from the FIPS tests forcing the use of the default distribution.

**Comment by jkakavas** [comment]
Can we put somthing like  
```
if (BuildParams.inFipsJvm){
  tasks.named("yamlRestTest").configure{enabled = false }
}
```

globally temporarily @mark-vieira ?

**Comment by mark-vieira** [comment]
Sure, I can take care of this. Is this only applicable to 7.x then?

**Comment by mark-vieira** [comment]
Ok, I've globally muted all yaml rest tests with e11acad138754081cea3994612e911a1bb1cc45c

**Comment by jkakavas** [comment]
> Sure, I can take care of this. Is this only applicable to 7.x then?

Master seems to suffer from the same since the warning headers PR was merged

**Comment by mark-vieira** [comment]
Yep, just saw the flood come in #es-test-triage. I've cherry-picked the mute to `master` as well.

**Comment by jkakavas** [comment]
Added Lyudmila so that she can take a look,  I know she's on test triage tomorrow

**Comment by mark-vieira** [comment]
It's not just the yaml tests failing: https://gradle-enterprise.elastic.co/s/yuigzlc2eayqm/tests/failed

**Comment by BigPandaToo** [comment]
PR is on it's way
