### ISSUE TITLE
Mapping corrupted when upgrading an index from V7.9.3 to 7.10.2 or higher

### ISSUE THREAD

**Issue by cgoller** [elastic/elasticsearch#71700]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: none

**JVM version** (`java -version`): 

java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

When I upgrade an index from 7.9.3 to 7.10.2 the mapping becomes currupt and search no longer works.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create an index with V 7.9.3
PUT my_index
{
  "settings":{
    "analysis":{
      "analyzer":{
        "default": {
          "type": "german"
        },
        "default_search": {
          "type": "german"
        }
      }
    }
  },
  "mappings":{
    "properties":{
      "de": {
        "type":"text"
      },
      "whitespace": {
        "type":"text",
        "analyzer" : "whitespace",
        "search_analyzer": "whitespace"
      }
    }
  }
}

 2. Add a document

 PUT my_index/_doc/1
{
   "de":"Ich lese die Bücher",
   "whitespace":"Ich lese die Bücher"
}

 3. Check Mappings
 {
  "my_index" : {
    "mappings" : {
      "properties" : {
        "de" : {
          "type" : "text",
          "analyzer" : "default",
          "search_analyzer" : "default_search"
        },
        "whitespace" : {
          "type" : "text",
          "analyzer" : "whitespace"
        }
      }
    }
  }
}

4. Search delivers document as expected
GET my_index/_search
{
  "query": {
    "query_string": {
    "query": "whitespace:Bücher"
    }
  }
}

5. Switch to V 7.10.2 using the same index

This is how the mapping of the index looks:
{
  "my_index" : {
    "mappings" : {
      "properties" : {
        "de" : {
          "type" : "text",
          "analyzer" : "default"
        },
        "whitespace" : {
          "type" : "text",
          "analyzer" : "whitespace"
        }
      }
    }
  }
}

6. Same search as before delivers no result

7. Delete index and recreate it as before, the mapping created by V 7.10.2 looks different:

{
  "my_index" : {
    "mappings" : {
      "properties" : {
        "de" : {
          "type" : "text",
          "analyzer" : "default"
        },
        "whitespace" : {
          "type" : "text",
          "analyzer" : "whitespace",
          "search_analyzer" : "whitespace"
        }
      }
    }
  }
}

8. Now search delivers result again.

9. Conclusion: V 7.9.3 did not store search_analyzer if it was identical to analyzer. This seems to cause the problem.

**Comment by romseygeek** [comment]
Hi @cgoller, this is indeed a bug in 7.9.x where the `search_analyzer` did not get serialized in mappings even if it was set, if it was the same as the `analyzer`.  The `search_analyzer` is an updatable setting, so you should be able to fix this in 7.10 by issuing a PUT mappings request for the `whitespace` field with the correct settings.  I don't think we have any plans for another 7.9.x release but I will add a note to the upgrade docs pointing to this bug and the recommended fix.

**Comment by javanna** [comment]
Based on @romseygeek 's assessment above, this has been fixed, we provided a workaround for 7.9, nothing else to do.
