### ISSUE TITLE
Add slop param to completion suggester

### ISSUE THREAD

**Issue by lazutkin** [elastic/elasticsearch#7174]
I would be very useful if completion suggester will accept a `slop` param. It will solve problem of suggesting for "aaaa bbbb" text in docs with `[ "bbbb aaaa", "bbbb", "aaaa" ]` input.

**Comment by clintongormley** [comment]
Unfortunately, given the way that the completion suggester works (it just follows the common prefix) this wouldn't be possible.  This job should be done by search instead
