### ISSUE TITLE
Update by query successful but not discoverable by Kibana-Discover

### ISSUE THREAD

**Issue by Reggae13** [elastic/elasticsearch#71775]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1

**Plugins installed**: none

**JVM version** (`java -version`): elasticsearch is run as docker-container

**OS version** (`uname -a` if on a Unix-like system): elasticsearch is run as docker-container

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. All transactions are realized with a dockerized NodeJs-service (using fastify - www.fastify.io) and the REST-Api
 2. Index a new document. The document has a field containing a UUID-V4.
 3. Update the document with an update_by_query transacation some 100 milliseconds later, querying the UUID-V4 field.
 4. The response shows that the update took place (response.total > 0 and response.updated > 0)
 5. The updated document is not discoverable by Kibana, whereas the original document is there

**Provide logs (if relevant)**:

The raw data of the two transactions: (The successful response is only possible if the response.total and the respons.update count is > 0)

[log01.txt](https://github.com/elastic/elasticsearch/files/6323240/log01.txt)

**Comment by henningandersen** [comment]
@Reggae13 thanks for your report. Can you elaborate on following:

1. Does this happen every time?
2. Did the indexing of a document in step 2 complete successfully before the update by query was fired?
3. Is there a newly created index involved?
4. What does the update by query do? Can you include the specific update by query request that you make?
5. For completeness, it would be nice to have the document source from both before and after you did the update by query.

**Comment by henningandersen** [comment]
@Reggae13 did you have a chance to look into my questions above?

**Comment by Reggae13** [comment]
Sorry for my late answer,
In the meantime I have learned that changes to documents belonging to a data stream do not work reliably with the update_by_query method (although the documentation says otherwise). I now use the index-API for this by searching for the documents in the corresponding backing-index and changing them there. This works very reliably.

**Comment by nik9000** [comment]
@henningandersen do you know what @Reggae13's May 12th comment is about? I haven't looked into `_update_by_query` on data streams myself. I'd expect it to work though.

**Comment by kingherc** [comment]
I believe this ticket is incomplete and stale for a long time. We do not have enough information to understand whether there's truly a bug neither a way to reproduce it. For the sake of cleaning up old tickets, I am closing this one. @Reggae13 , feel free to re-open this if you have more information to provide to the above-mentioned questions.
