### ISSUE TITLE
aarch64 rpm fails to install when using an arm64 docker builder

### ISSUE THREAD

**Issue by jamshid** [elastic/elasticsearch#71789]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.12.0

**Plugins installed**: []
none
**JVM version** (`java -version`):
none using packaged jdk
**OS version** (`uname -a` if on a Unix-like system):
the centos:7.9.2009 on
**Description of the problem including expected versus actual behavior**:

I know I can use your official images but trying to build my own centos:7 image and install the aarch64 rpm. But docker buildx only creates an arm64 builder and rpm/yum do not consider your aarch64 rpm to be compatible.

I thought aarch64 and arm64 were equivalent. Is this expected behavior? Is there a workaround? `rpm --force` did not help. 

**Steps to reproduce**:
 1. Try to build an arm64 image from a Dockerfile that is `FROM centos:7.9.2009`.
    `docker buildx build --platform linux/arm64 ...`
 2. yum install -y https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-aarch64.rpm

**Provide logs (if relevant)**:
yum fails with:
```
Cannot add package /deliverables/elasticsearch-7.12.0-aarch64.rpm to transaction. Not a compatible architecture: aarch64
```

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
