### ISSUE TITLE
[CI] Docker compose tasks failing with read timeouts on ARM

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71866]
A lot of our ARM builds fail on `composeUp` or `composeDown` tasks due to network read timeouts. Seems very specific to ARM though, and specifically Ubuntu. Of the 20+ failures, only one was CentOS.

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Exit-code%20*%20when%20calling%20/usr/local/bin/docker-compose,%20stdout:%20*&search.relativeStartTime=P7D&search.tags=AARCH64&search.timeZoneId=America/Los_Angeles

```
:x-pack:test:idp-fixture:composeUp FAILED
elasticsearch-node uses an image, skipping
openldap uses an image, skipping
shibboleth-idp uses an image, skipping
http-proxy uses an image, skipping
oidc-provider uses an image, skipping
Creating network "8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__default" with the default driver
Pulling openldap (osixia/openldap:1.4.0)...
1.4.0: Pulling from osixia/openldap
Digest: sha256:ccd95cc6e61effc1bbc4fff8b09d358ee9d6739a43f4124d6219ac18d82879d1
Status: Downloaded newer image for osixia/openldap:1.4.0
Pulling shibboleth-idp (unicon/shibboleth-idp:3.4.2)...
3.4.2: Pulling from unicon/shibboleth-idp
Digest: sha256:7e84115d68b79d50d2d08a9c312d2f8d1b0dd3d831b1d6c921e1761f886e06de
Status: Downloaded newer image for unicon/shibboleth-idp:3.4.2
Pulling oidc-provider (c2id/c2id-server:9.5)...
9.5: Pulling from c2id/c2id-server
Digest: sha256:5c72c361d6135ea93297adc04654f16493e548fce35fee500744e29c10e9f5c3
Status: Downloaded newer image for c2id/c2id-server:9.5
Creating 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__openldap_1 ... 
Creating 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__elasticsearch-node_1 ... 
Creating 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__http-proxy_1         ... 

ERROR: for 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__openldap_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__http-proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__elasticsearch-node_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for openldap  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for http-proxy  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for elasticsearch-node  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Removing network 8aa0a8dd5960825940b3be7ee5713fb6_idp-fixture__default
```

**Comment by martijnvg** [comment]
A few more instances of this failure today:
* https://gradle-enterprise.elastic.co/s/ymhtn7gkis37u
* https://gradle-enterprise.elastic.co/s/ocsqsbpohjreu
* https://gradle-enterprise.elastic.co/s/ica5ni2a2ieu2
* https://gradle-enterprise.elastic.co/s/tz4gro54plege

**Comment by ywangd** [comment]
A few more:
* https://gradle-enterprise.elastic.co/s/c3giw2fcbjgxu
* https://gradle-enterprise.elastic.co/s/jv4z5pwpknxfk
* https://gradle-enterprise.elastic.co/s/eusm7m6zq6qz4

**Comment by droberts195** [comment]
Still happening, for example https://gradle-enterprise.elastic.co/s/5hvafladuybmk

**Comment by BigPandaToo** [comment]
One more today:
https://gradle-enterprise.elastic.co/s/27nhtpn2eitrk

**Comment by mark-vieira** [comment]
Moving our ARM builds to use ramdisks seems to have sorted this out.

**Comment by cbuescher** [comment]
I saw something similar today on 7.13, reopening this just for inspection:

https://gradle-enterprise.elastic.co/s/zhbyeatu5gdwi

**Comment by mark-vieira** [comment]
Indeed, does look like the same thing. Interestingly, docker compose now suggests a workaround.

```
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60)
```

These are still pretty infrequent but it looks like there have been [half a dozen of these failures in the past month](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=non_verification&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Exit-code%201%20when%20calling%20/usr/local/bin/docker-compose,%20stdout:%20N/A&search.relativeStartTime=P28D&search.rootProjectNames=elasticsearch&search.tags=AARCH64&search.tags=CI&search.tasks=check&search.timeZoneId=America/Los_Angeles). I'm going to bump this timeout to 120 seconds and see if that helps.

**Comment by mark-vieira** [comment]
I still occassionally see the "has active endpoints" issue with calling `composeDown` but that's tracked by https://github.com/elastic/elasticsearch/issues/69045. I'm calling this issue resolved.

**Comment by williamrandolph** [comment]
I think I am getting these read timeouts on ARM today: https://gradle-enterprise.elastic.co/s/imiczm4xip6ji

**Comment by Luegg** [comment]
Looks like another one in `composeUp`: https://gradle-enterprise.elastic.co/s/7lstizaia3sfo/console-log?task=:test:fixtures:geoip-fixture:composeUp
