### ISSUE TITLE
Document migration path off multiple data paths

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#71871]
See #71205 for background.

This issue is about documenting the migration paths for users using multiple data paths today. This is a pre-requisite for upgrading to 8.0, but some users may want to do this in advance of the upgrade too.

Possible migration paths are to either decommission nodes or rolling reformat nodes if there are replicas.

**Comment by DaveCTurner** [comment]
Closed by #73578 and #73367.

**Comment by bernarmn-mnb** [comment]
What is the status of a document around migration away from MDP? I have a customer that needs this.
