### ISSUE TITLE
A way to get "interesting" fields from an index

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#71873]
Hey y'all,

We are investigating a way to automatically find "interesting" fields to include in a statistical analysis. 

Interesting-ness could be considered:

 - keyword/ip fields within cardinality range (related to total document count)
 - Numeric ranges within a range (related to total document count)

Right now, we execute a "random_score" query to get the top 1k-10k documents and simply grab fields. This provides some bad info as some of the fields could have an exceptionally large cardinality (near the total doc count) and thus provide very little information (not warranting a more expensive calculation later).

It would be useful to have a better way to determine if a field was interesting before putting it through a more expensive statistical analysis. 

Key factors:

 - Interesting is "good enough" calculation
 - it must be fast (or it really isn't worth it)

Really, our goal is to throw away fields like:
 - Have no values
 - Have cardinalities near the number of docs in the index
 - Have cardinalities near 0
 
ping @tveasey @stevedodson

**Comment by javanna** [comment]
We have no concrete plans on working on this issue. We will close it for now, we can always reopen in the future.
