### ISSUE TITLE
EQL: Deprecate wildcard function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#71906]
Since there's now a dedicated syntax using `like` / `like~` / `regex` / `regex~`, we should deprecate the `wildcard` function.
It should be considered deprecated in a later 7.x release and drop completely from 8.0.

**Comment by astefan** [comment]
@jrodewig can you, please, have a look at this one? Many thanks.

**Comment by jrodewig** [comment]
Thanks @astefan. I left some comments and questions on https://github.com/elastic/eql/issues/7. I'll get started on that once I have that info.
