### ISSUE TITLE
Include # of shards information in nodes api output

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#7194]
Routing table (http://localhost:9200/_cluster/state/routing_table?pretty) provides a nice view of how shards are allocated grouped by indices.  We have use cases in the field where admins would like to have a rest json api (eg. nodes info or node stats) returning # of shard information grouped by nodes (similar to what cat allocation provides) but in json format, eg. # of primary shards per node, # of replicas per node, total # of shards per node, etc..

**Comment by clintongormley** [comment]
This is available with `GET _cat/allocation?format=json`
