### ISSUE TITLE
Missing Aggregations's results do not meet expectations

### ISSUE THREAD

**Issue by yuchen001** [elastic/elasticsearch#71965]
Use Missing Aggregations to return incorrect results if the field type is nested.
I want to know how many of the fields 'victims' are empty in all documents. At the moment there are four documents in the index, and two of them have the field not empty. But after aggregation analysis, the result is 4.

![Screen Shot 2021-04-21 at 00 48 39](https://user-images.githubusercontent.com/22665827/115434483-52bfbe00-a23b-11eb-80c5-c433571ab8cf.png)
![Screen Shot 2021-04-21 at 00 49 03](https://user-images.githubusercontent.com/22665827/115434523-5fdcad00-a23b-11eb-9279-d07669bf777d.png)
![Screen Shot 2021-04-21 at 00 49 17](https://user-images.githubusercontent.com/22665827/115434552-679c5180-a23b-11eb-8f87-6e1eb6e62f7f.png)
![Screen Shot 2021-04-21 at 00 49 33](https://user-images.githubusercontent.com/22665827/115434581-71be5000-a23b-11eb-914e-f156d8ec87fa.png)
---
Elasticsearch version: 7.10.2-SNAPSHOT

Plugins installed: none

JVM version: OpenJDK 16 2021-03-16

OS version: macOS 11.2.3

**Comment by imotov** [comment]
@yuchen001 could you provide a complete reproduction of this issue using text instead of screenshots?

**Comment by ebadyano** [comment]
No further feedback received. @yuchen001 if you have the requested information please add it in a comment and we will re-open this issue.

**Comment by imotov** [comment]
I suspect this is a duplicate of #9571

**Comment by kunwarshukla2020** [comment]
@ebadyano @imotov - Here is the complete description of the [issue] (https://stackoverflow.com/questions/74168990/elasticsearch-aggregations-for-the-count-of-documents-that-has-empty-nested-arr/74169042?noredirect=1#comment130963983_74169042)
