### ISSUE TITLE
Support for Mustache Partials in templates?

### ISSUE THREAD

**Issue by softwaredoug** [elastic/elasticsearch#72036]
At Shopify, we're working with increasingly sophisticated query and index definitions. We <3 Search templates, because they let us have an artifact that we can iterate on that controls query behavior for certain cases. Lately, other teams have had to mix in some business logic to our templates. So the search template has become a change magnet (a file that attracts a lot of change and thus is becoming unmanageable).

We would prefer to decompose some of our Elasticsearch templates and configurations into manageable components. Mustache nicely supports [partials](https://mustache.github.io/mustache.5.html) for this use case.  These are basically includes, where one template can include another. So you can decompose templates into smaller chunks.

Putting my :trollface: hacker hat on, I attempted to see what would happen if I rendered an Elasticsearch mustache template that included a Mustache partial, where the partial name was another search template stored in Elasticsearch. My hope was that the root template would somehow load the other template as a partial. I was not expecting it to work, but also wouldn't be too surprised if it did work!

Here's the example of what I tried, that would be awesome if it could work:

```
# This is the 'include file'
POST _scripts/partial
{
  "script": {
    "lang": "mustache",
    "source": "{ \"match\":  {\"title\": \"{{query_string}}\" } } "
  }
}

# This refers out to 'partial' that happens to be named partial 
# This name matches the other search template
POST _scripts/outer
{
  "script": {
    "lang": "mustache",
    "source": "{ { \"query\": { {{>partial}} } } }"
  }
}
```

OK the big drumroll, what happens if I try to render the `outer` template? Will it inject a match query into `outer` and populate `query_string`?

```
GET _render/template/outer 
 {
  "params": {"query_string": "foo"}}
}
```

No luck! I get this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "general_script_exception",
        "reason": "Failed to compile stored script [outer] using lang [mustache]"
      }
    ],
    "type": "general_script_exception",
    "reason": "Failed to compile stored script [outer] using lang [mustache]",
    "caused_by": {
      "type": "access_control_exception",
      "reason": "access denied (\"java.lang.RuntimePermission\" \"getClassLoader\")"
    }
  },
  "status": 500
}
```

It would be cool if this instead rendered:

```
{
   "query": {
       "match": {
             "title": "foo"
        }
   }
}
```

Thus letting me manage my templates a bit intelligently within Elasticsearch itself...

**Comment by jdconrad** [comment]
@softwaredoug Thank you for raising this issue! This is certainly an interesting use case, and we understand how this would be nice to have especially for Mustache. Unfortunately, after some discussion our team has two primary concerns for which we have decided not to pursue this feature:

1. Calling scripts (partials in this case) as dependencies of other scripts require specific arguments passed into the script that depends on an internal context. It would be challenging to get the arguments into a partial correctly.
2. Given that stored scripts can be removed at any time we are concerned that this could lead to odd and possibly confusing errors if a script used as a dependency (partial) is removed especially in a distributed environment.

Given the above reasons we don't plan to work on this at this time, so I hope you don't mind that I close this issue.

**Comment by ng-druid** [comment]
This would be nice. I wonder if open search would be interested.
