### ISSUE TITLE
ipv6 included 0:0:0 is invalid when we added it in cluster.routing.allocation.exclude._ip

### ISSUE THREAD

**Issue by lqbilbo** [elastic/elasticsearch#72091]
**Elasticsearch version:  (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk 13.0.2

**OS version** (`uname -a` if on a Unix-like system): Linux n24-181-138 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: ipv6 included 0:0:0 is invalid when we added it in cluster.routing.allocation.exclude._ip

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. add ipv6 address in 'cluster.routing.allocation.exclude._ip', we suppose it's fdbd:dc00:111:222:0:0:0:333
 2. there are no shards relocating
 3. but we change the address to fdbd:dc00:111:222::333, shards begin to relocate
 4. in normal condition, ipv6 address fdbd:dc00:111:222:0:0:0:333 is equal to fdbd:dc00:111:222::333

**Comment by DaveCTurner** [comment]
Although we've changed how IPv6 addresses are parsed in newer versions I believe the issue reported here is still a problem, so I'm reopening this to avoid losing track of it while the investigation continues.

**Comment by arteam** [comment]
Thanks, David!
