### ISSUE TITLE
Completion & Context Suggester: Support expressions for suggestion scoring

### ISSUE THREAD

**Issue by areek** [elastic/elasticsearch#7209]
Currently users have to explicitly set score to suggestion entries via the `weight` parameter, while indexing. It would be nice to be able to just specify an `expression` instead and also accept hard-coded values (as done today).

If a weight of a suggestion is calculated by a combination of field values (`popularity`, `recency` for example), then the following format can be used:

``` bash
curl -X PUT 'localhost:9200/music/song/1?refresh=true' -d '{
    "name": ...,
    "suggest": {
        "input": [
           ...
        ],
        "output": ...,
        "payload": {
            ...
        },
        "weight": "doc['popularity'].value * 0.8 + doc['recency'].value * 0.2"
    }
}'
```

the example above assumes `popularity` and `recency` to be already defined in the mapping and both have `Numeric` values.

related #6818

**Comment by clintongormley** [comment]
@areek do you plan to pick this up at some stage?

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by jimczi** [comment]
We don't have plan to work on this in the near future, we also didn't see lot of interests in the community to add this feature so I am closing this issue. A custom weight can be easily computed in an ingest processor or client-side.
