### ISSUE TITLE
geoip Processor DatabaseReaderLazyLoader not using CIDR route selection

### ISSUE THREAD

**Issue by hkelley** [elastic/elasticsearch#72092]
**Elasticsearch version** 
v7.11.1  (cloud)

**Description of the problem including expected versus actual behavior**:

Maxmind DBs may include "overlapping" network ranges,   e.g. 10.0.0.0/8  and 10.2.0.0/24.  Maxmind API's DatabaseReader class for Java correctly selects the more specific route when overlapping routes are present.

The geoip processor uses [DatabaseReaderLazyLoader ](https://github.com/elastic/elasticsearch/blob/5baabff6670a8ed49297488ca8cac8ec12a2078d/modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseReaderLazyLoader.java#L45) and this does not appear to use CIDR route/geo selection.

**Steps to reproduce**:
 1.  Build a pipeline
 PUT _ingest/pipeline/geoip-ecs
 ```
{
  "description" : "Add geoip info to ECS-compliant fields",
  "processors" : [
	{
      "geoip" : {
        "field" : "destination.ip",
        "target_field" : "destination.geo",
        "database_file" : "OurNetworks-City.mmdb",
      	"properties" : ["city_name","region_name","country_name","country_iso_code"]
      }	
	}
  ]
} 

 ```
 2.  Simulate
 POST /_ingest/pipeline/geoip-ecs/_simulate
``` 
{
	"docs": [
	{
		"_index": "index",
		"_id": "id",
		"_source": {			
			"destination": {
			  "ip": "10.2.7.50"
			}
		} 
	}
	]
```

**Comment by probakowski** [comment]
Hello @hkelley, can you provide expected and actual result? Do you have maybe example with our standard databases, I assume `OurNetworks-City.mmdb` is custom one, right?
`DatabaseReaderLazyLoader` uses `DatabaseReader` from MaxMind underneath so I'm surprised that it gives different results than `DatabaseReader` itself

**Comment by hkelley** [comment]
@probakowski ,  yes,  it is a custom DB.   I can try to reproduce with a standard Maxmind DB but I will have to find a case of overlapping routes (I'm not sure they exist in the stock DB).

If DatabaseReaderLazyLoader uses DatabaseReader then I agree,  my theory may be off base.   I'm open to other avenues.   I have used both the Go and Java API on my workstation and both return the expected result against my MMDB.   

Perhaps my custom DB isn't updating on the ingest nodes?  Is there an API way to check the hash/name/date of MMDB file across nodes?   We use a cloud deployment so I'm limited in how much investigation I can do on the server.

```
import java.net.InetAddress;
import java.io.File;

import com.maxmind.geoip2.model.CityResponse;
import com.maxmind.geoip2.DatabaseReader;

public class test {

	public static void main(String []args) {

		try {
			String dbpath  = args[0];
			String ipstring  = args[1];
					
			File database = new File(dbpath);

			DatabaseReader reader = new DatabaseReader.Builder(database).build();

			InetAddress ipAddress = InetAddress.getByName(ipstring);

			CityResponse response = reader.city(ipAddress);

			System.out.println("City " + response.getCity());
			System.out.println("Country " + response.getCountry());
			
		} catch (Exception e){
			
			e.printStackTrace();
		}			 
	}  
}
```

**Comment by hkelley** [comment]
My apologies.  As it turns out,  I was not pushing my new MMDB the correct way.   I was trying to update the MMDB/zip file inside the existing bundle.  I needed to create a new bundle (with the same file name inside, so that the file name in the pipeline is unchanged) and then push that one to the cloud deployment.

Now that I have the MMDB file updating on all cluster nodes,  route/range selection is working as desired.
