### ISSUE TITLE
A different version of the library has been downloaded.

### ISSUE THREAD

**Issue by Tom-Shumi** [elastic/elasticsearch#72103]
I have defined version 6.8.6 Elasticsearch in build.gradle. 

`implementation group: 'org.elasticsearch', name: 'elasticsearch', version: '6.8.6'`

Then version 6.8.6 and version 7.6.2 were downloaded. 
Why?
Moreover, due to the transitive dependency of gradle, application used version 7.6.2.

I want to use version 6.8.6.

help me..

**Comment by cbuescher** [comment]
Hi @Tom-Shumi. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
