### ISSUE TITLE
Add support for on_script_error to runtime fields

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#72143]
When defining a runtime field, it should be possible to configure its error handling behavior. At the moment, a shard failure is returned once the first document fails executing the script on a specific shard, and that shard won't return any matching document. We'd like to have the option for users to continue on error, in which case no errors will be returned, the search will go ahead, and documents that failed executing the script simply won't have a value for it.

This is inline with how you can already configure script error handling on indexed fields associated with a script (#69531). Along with the script, it is possible to configure error handling through the [`on_script_error` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html#number-params):  `fail` means that the document won't be indexed and an error will be returned, while  `continue` means that the document will be indexed but it will have no value for the scripted field as the script failed to run.

This is important as a script, although tested beforehand, may fail against some specific documents but work against some others, and that is the case regardless of whether the script is executed at index time or at search time.

The plan is to add support for the `on_script_error` option to the definition of a runtime field. Errors need to be intercepted, and the kind of reporting we want to return as part of the search response is not clearly defined: possibly the number of errors is enough to start with.

One edge case we currently have is around script-less runtime fields for which the implicit script is lenient hence failure to load values from source is silently accounted as a missing value. We should align this with the new `continue` option being added, and consider adding the ability to fail for script-less runtime fields.

No changes are foreseen to the semantics of the `fail` scenario of a runtime field (the current non configurable behaviour): the first document that fails on a shard will cause a shard failure and there will be no documents returned for that specific shard. That will be signaled by the shard failures returned as part of the search response, like it already is today.

**Comment by mattkime** [comment]
>In this case, when a runtime field script fails to execute at search time, the document won't have a value for that field.

Thats the part of particular interest to the Graceful Error Handling effort.

**Comment by mattkime** [comment]
I'd like to clarify something - we don't want to entirely ignore failures, we'd still like them reported, we would like both the reporting of errors AND the `continue` functionality.

**Comment by javanna** [comment]
@mattkime correct. Including the errors in the search response is something that seems to have gotten lost between edits, I added it back.

**Comment by javanna** [comment]
The ability to ignore errors when executing runtime fields scripts was added with #92380 . Reporting the errors back has yet to be implemented, which is why we are leaving this issue open for now.

**Comment by javanna** [comment]
Additionally, we would like to add support for configuring on script error at the request level, so that users can decide to ignore error with one setting rather than having to modify all their field types, either by overriding them from the search request or modifying their mappings definition.

**Comment by javanna** [comment]
I opened #95455 for the remaining items, closing this as completed.
