### ISSUE TITLE
Retiring repository credentials while snapshotting results in stuck snapshot

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#72140]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.0

**Plugins installed**: Cloud (incl. `repository-s3`)

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

Access credentials to a snapshot repository were rotated while a snapshot was ongoing, and the old credentials were retired. The ongoing snapshot cannot make progress since it can no longer access the repository, but nor can it be cancelled since that also requires repository access. Meanwhile, the repository cannot be updated to use the new credentials because of the ongoing snapshot.

**Comment by original-brownbear** [comment]
I looked into this now. I believe this is already fixed.

> The ongoing snapshot cannot make progress since it can no longer access the repository, but nor can it be cancelled since that also requires repository access.

I don't think this is true and should never have been true either outside of bugs :)
If the credentials break it should be like any other exception during repo interaction. What seems to have happened in the linked SDH that motivated this is this: 
The missing credentials threw a `RuntimeException` in a version that didn't have this fix https://github.com/elastic/elasticsearch/pull/69110 -> leaked the listener -> snapshot never completed. With this fix in I don't think this requires any additional work so I'll close here. Please reopen if you think I missed anything.
