### ISSUE TITLE
Combined Fields query `minimum_should_match` discrepancy for integer values

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#72148]
**Elasticsearch version** 7.13.0-SNAPSHOT
**Plugins installed**: n/a
**JVM version**: bundled
**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

When testing the new [Combined Fields query](https://github.com/elastic/elasticsearch/pull/71213), I noticed a discrepancy with the minimum_should_match field which may be a bug. When sending an integer value for the `minimum_should_match` property it returns:

```
"type" : "x_content_parse_exception",
"reason" : "[1:115] [combined_fields] minimum_should_match doesn't support values of type: VALUE_NUMBER",
```

While it's described as a string [in the documentation](https://www.elastic.co/guide/en/elasticsearch///reference/master/query-dsl-combined-fields-query.html#combined-field-top-level-params), examples elsewhere in the [docs, show](https://www.elastic.co/guide/en/elasticsearch///reference/master/query-dsl-query-string-query.html#query-string-min-should-match-multi) that an integer can be used. For the Match query, we have integration tests successfully sending an integer value too.

**Steps to reproduce**:

Send the following search:

```
POST http://127.0.0.1:9200/project/_search
{
    "query": {
        "combined_fields": {
            "query": "hello world",
            "fields": [
                "description",
                "myOtherField"
            ],
            "minimum_should_match": 2,
            "auto_generate_synonyms_phrase_query": false,
            "operator": "or",
            "zero_terms_query": "all",
            "boost": 1.1,
            "_name": "combined_fields"
        }
    }
}
```

**Expected Result**:

The search executes successfully.

**Actual Result**:

```
"type" : "x_content_parse_exception",
"reason" : "[1:115] [combined_fields] minimum_should_match doesn't support values of type: VALUE_NUMBER",
```

Sending the same query with the value as a string succeeds.

**NOTE**

Sending and integer value for this property in a Match query succeeds, so I'd expect the same behaviour in Combined Fields.

```
{
    "query": {
        "match": {
            "description": {
                "analyzer": "standard",
                "auto_generate_synonyms_phrase_query": false,
                "fuzziness": "AUTO:3,6",
                "fuzzy_rewrite": "top_terms_blended_freqs_10",
                "fuzzy_transpositions": true,
                "lenient": true,
                "minimum_should_match": 2,
                "operator": "or",
                "query": "hello world",
                "boost": 1.1,
                "_name": "named_query"
            }
        }
    }
}
```

**Comment by cbuescher** [comment]
I see that in most other query builders (e.g. `match`) we use `parser.textOrNull()` to parse this value. The new CombinedFieldsQueryBuilder uses the declarative `ConstructingObjectParser` instead of the manual json parsing we use in the older query builders, so maybe we need to be a bit more permissive there.
