### ISSUE TITLE
Encrypt search result

### ISSUE THREAD

**Issue by dg8fv2010** [elastic/elasticsearch#72154]
Hello, we store many information in elasticsearch, some of them are sensitive, so we hope to encrypt these properties when elasticsearch returns search result and these results can only be decrypted by our own services.

In order to do this, we can add a new index setting so that elasticsearch can decide whether need to encrypt return data.

Here are some examples, when we open encrypt_display, user_id, user_name and user_phone can be encrypted.

> #open encrypt display

`PUT /user/_settings
{
    "index":{
        "encrypt_display": {
          "enable":"on",
          "password":"1234"
        }
    }
}`

> #search result

`{
    "took": 101,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 1,
        "hits": [
            {
                "_index": "user",
                "_type": "_doc",
                "_id": "2",
                "_score": 1,
                "_source": {
                    "user_id": "rO0ABXQAAjEx",
                    "user_name": "rO0ABXQABHhrbDI=",
                    "user_phone": "rO0ABXQABTEyMzQ1"
                }
            }
        ]
    }
}`

> #close encrypt display

`PUT /user/_settings
{
    "index":{
        "encrypt_display": {
          "enable":"off",
          "password":"1234"
        }
    }
}`

> #search result

`{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 1,
        "hits": [
            {
                "_index": "user",
                "_type": "_doc",
                "_id": "2",
                "_score": 1,
                "_source": {
                    "user_id": "11",
                    "user_name": "xkl2",
                    "user_phone": "12345"
                }
            }
        ]
    }
}`

**Comment by bytebilly** [comment]
@dg8fv2010 thanks for the proposal. If I get it correctly, the encryption would happen only when data is returned in the search result, and it is not encrypted in Elasticsearch. 

Could you please help to clarify which is the use case for this feature? If you don't want some of your users (the ones without the password) to fetch results, isn't possible to achieve the same goal by using RBAC on those indices?

**Comment by dg8fv2010** [comment]
@bytebilly I just think it would be more safer if elasticsearch could return encrypted data. Even if someone gets some roles' password, he won’t get any useful information, and decryption work can be performed by the program instead of by humans.

**Comment by bytebilly** [comment]
@dg8fv2010 thanks for the additional context.

If sensitive fields are not used in search queries directly, I would suggest to do client encryption before ingestion. In this way, even if anyone gets access to raw data, it's encrypted. Clients can do decryption before showing results to the end user.

The dynamic encryption of results is tricky, even because if you can still search those fields you can "guess" which is the value, and potentially the password.

Unfortunately at the moment we don't have anything in this direction on our roadmap.
The possible workaround is to implement a proxy in front of Elasticsearch and handle encryption/decryption there.
