### ISSUE TITLE
Add ability to find fields by field-type

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#72174]
The `_field_caps` API allows clients to search fields by name (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html).

It would be great if this could be extended so clients can search by field-type.

An existing use-case is in Kibana Maps. In the UX to add a layer, Maps would only want to present users with index-patterns (or indices) that have a `geo_point` or `geo_shape` field-type.

This is hard to achieve _without_ pulling all the fields for all the indices and do the filtering by type on the client. Retrieving all the fields up-front for all the indices, is not feasibly when users have 100s of indices, each with 1000s of fields.

cc @mattkime @nreese @jimczi

**Comment by romseygeek** [comment]
This was added in #83636

**Comment by threatangler-jp** [comment]
Can this be used to list flieds with a conflict? Or could it be expanded to include that capability? Or is there another way to list fields that have a conflict from the api?

**Comment by javanna** [comment]
@threatangler-jp can you expand on what you mean with "conflict"? Indices having a different definition for the same field name?

**Comment by javanna** [comment]
You commented on an issue where the ask was to be able to filter per data-type, hence this directly won't give you which fields have same name but different field types across indices. On the other hand, field caps take a set of indices and fields as input, and will give you the family type of the field in the output, per index. This should give you the info to find conflicts. There isn't a direct way to get only "conflicts" back though.
