### ISSUE TITLE
Please add the user that initiated the command 

### ISSUE THREAD

**Issue by RamiusKahn** [elastic/elasticsearch#72177]
https://github.com/elastic/elasticsearch/blob/fdf254335f73daea672603cb4053ede087808744/server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateEmptyPrimaryAllocationCommand.java#L68

Please consider updating "from user command" to include the user that invoked the command.

**Comment by orhanar** [comment]
hi just started open source contribution. can i work on this?

**Comment by DaveCTurner** [comment]
This information is already recorded in the `user.name` field of the [audit log](https://www.elastic.co/guide/en/elasticsearch/reference/current/enable-audit-logging.html) as follows:

```
{
  "type": "audit",
  "timestamp": "2021-04-25T09:50:12,022+0100",
  "node.id": "MCsJhfQ2RbWmq_ql1QwGiQ",
  "event.type": "transport",
  "event.action": "access_granted",
  "authentication.type": "REALM",
  "user.name": "elastic",
  "user.realm": "reserved",
  "user.roles": [
    "superuser"
  ],
  "origin.type": "rest",
  "origin.address": "127.0.0.1:50813",
  "request.id": "9cfIxBTTThC-LzljVXeSCQ",
  "action": "cluster:admin/reroute",
  "request.name": "ClusterRerouteRequest",
  "opaque_id": "my-custom-id"
}
```

I don't think we should add

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed) team discussed this today and agreed that the audit log is the right place for this information. Therefore I am closing this.
