### ISSUE TITLE
[DOCS] Make JVM options docs more scannable

### ISSUE THREAD

**Issue by clintonjimmie** [elastic/elasticsearch#72259]
Hey team! Following up on a discussion that was had around the ambiguity of file extensions for jvm options files placed in jvm.options.d here: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/jvm-options.html#jvm-options
https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#setting-jvm-heap-size

Here is what we say in the jvm.options doc above

> When installing from the tar or zip distributions, the root jvm.options configuration file is config/jvm.options and custom JVM options files can be added to config/jvm.options.d/.

This makes no mention that any file places in that directory (eg `foo`) would need to be named `foo.options` in order to be picked up and used by Elasticsearch. A quick example to show that the files in the jvm.options.d directory should explicitly have the `.options` extension would help a great deal.

Thank you!

**Comment by jasontedor** [comment]
Immediately after the paragraph that you highlight is the sentence

>JVM options files must have the suffix `.options` and contain a line-delimited list of JVM arguments following a special syntax:

**Comment by jrodewig** [comment]
While I agree with @jasontedor that all the needed information is here, we can probably make some improvements to make JVM options page a bit more scannable. For example, we can probably use a tabbed widget to reduce the screen space of the  config file locations.
