### ISSUE TITLE
Adding One's Own Language Analyzer 

### ISSUE THREAD

**Issue by irint92** [elastic/elasticsearch#72283]
One of our cloud trial prospects from Thailand is requesting for a feature in which he is able to add his own language analyzer on Elastic Cloud. My understanding now is that they are unable to, but the universal language analyzer works well. However, we might want something more specific to some local languages to enable better performance. This is his official question:

"We are new to website & app search engines, and your solution might solve our problems. We’re exploring the solution, and our team has to get an alignment from our Business team. Is that possible that you or your team can walk us through what we can do with Elastic Search on https://www.makroclick.com/th and App – especially in the Thai language?"

Thank you!

Irina

**Comment by imotov** [comment]
@irint92 this repository is not the best place to ask questions like this. We use these issues for tracking bugs and and enhancement requests in elasticsearch. You are asking a question about elasticsearch cloud deployment, which is much better to do using [cloud support form](https://cloud.elastic.co/support) or in our [discuss forum](https://discuss.elastic.co/). Saying this, 
the process of installing custom plugins is well described in [documentation](https://www.elastic.co/guide/en/cloud/current/ec-custom-bundles.html) so I would suggest starting there.
