### ISSUE TITLE
SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense fails when recreating its license

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#72329]
**Build scan**:
https://gradle-enterprise.elastic.co/s/2bpdnr5jqux6y/tests

**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense" -Dtests.seed=5470D1E16498B727 -Dtests.locale=be -Dtests.timezone=Canada/Pacific -Druntime.java=11
```
**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**:
https://build-stats.elastic.co/goto/d7017643bd9139fb127d1f231d6d81d2

![image](https://user-images.githubusercontent.com/215970/116301902-900dd980-a76e-11eb-9b99-ec97b86c0ee3.png)

**Failure excerpt**:

```
java.lang.AssertionError: expected:<UPGRADED_TO_TRIAL> but was:<TRIAL_ALREADY_ACTIVATED> |  
...
at __randomizedtesting.SeedInfo.seed([5470D1E16498B727:D8600A79DC686337]:0)
```

**Comment by droberts195** [comment]
It looks like the same error just occurred in https://gradle-enterprise.elastic.co/s/h7xi5tf25tkjm

**Comment by tlrx** [comment]
I merged #74621 to add some debug logging traces, hopefully this will help me to understand why the test fails.

**Comment by tlrx** [comment]
We're waiting for this CI failure to happen again so that we can do more investigation now more logging was added.

In case someone see a CI failure please add the build scan here 🙏🏻

**Comment by tlrx** [comment]
Failed again today in https://gradle-enterprise.elastic.co/s/o5xbwrtlotewu
