### ISSUE TITLE
[CI] search.aggregation/235_composite_sorted failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#72362]
**Build scan**:

https://gradle-enterprise.elastic.co/s/2w65af7psd4ju

**Repro line**:

```
./gradlew ':qa:mixed-cluster:v7.1.0#mixedClusterTest' \      
  -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.aggregation/235_composite_sorted/two sources - first page}" \
  -Dtests.seed=C13375AE83190C97 \
  -Dtests.bwc=true \
  -Dtests.locale=ar-SD \
  -Dtests.timezone=America/St_Barthelemy \
  -Druntime.java=8
```

**Reproduces locally?**:

Yes

**Applicable branches**:

7.x, 7.13

**Failure history**:

started earlier yesterday night on 7.x and 7.13, apprix 11 failures on both branches in the last half day

**Failure excerpt**:

```
java.lang.AssertionError: Failure at [search.aggregation/235_composite_sorted:133]: expected [2xx] status code but api [search] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:118] [date_histogram] unknown field [calendar_interval], parser not found","stack_trace":"[[1:118] [date_histogram] unknown field [calendar_interval], parser not found]; nested: XContentParseException[[1:118] [date_histogram] unknown field [calendar_interval], parser not found];\n\tat 
```

**Comment by nik9000** [comment]
Looks like I've made a mistake in backporting somewhere. Sorry!

**Comment by cbuescher** [comment]
@nik9000 should I mute or do you think this is an easy fix and I can hold of with it? Its a bit more tricky muting this in yaml with skip sections etc...

**Comment by nik9000** [comment]
I'm unlikely to land a real fix until my afternoon. Probably worth muting
it, sadly. Sorry!

**Comment by cbuescher** [comment]
Muted on 7.x and 7.13 with 41d4eaf4f1dfb35b6b290a9839afee55ea61a7c9 and c1c0b9d10f6b2dffebeecb8c8a8a42e35ea19c32

**Comment by nik9000** [comment]
Hopefully I've fixed this now. Faster than I expected!
