### ISSUE TITLE
Make feature reset compatible with action.destructive_requires_name: false

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#72363]
It has long been best practice to set `action.destructive_requires_name: false` and that is becoming the default in 8.0.

Currently if an end user runs the feature reset API they are likely to see this error response:

```
      "feature_name" : "machine_learning",
      "status" : "FAILURE",
      "exception" : {
        "type" : "exception",
        "reason" : "java.lang.IllegalArgumentException: Wildcard expressions or all indices are not allowed",
        "caused_by" : {
          "type" : "illegal_argument_exception",
          "reason" : "Wildcard expressions or all indices are not allowed"
        }
      }
    },
```

This problem occurs because the feature reset API is trying to delete wildcarded index patterns.  The solution is to set `action.destructive_requires_name: true`, which is what our integration test suites do to avoid this problem, but is not great UX for an end user (and the error response does not make the solution clear). 

It would be much friendlier to resolve the wildcard patterns to a list of concrete indices as suggested in point 2 of https://github.com/elastic/elasticsearch/issues/71178#issuecomment-812193281, or else bypass the value of `action.destructive_requires_name` in some other way within the internals of the feature reset API implementation.

**Comment by williamrandolph** [comment]
I believe that resolving the wildcard patterns to a list of concrete indices is the way to go here. I'll try to get a PR out for that soon.
