### ISSUE TITLE
Ban `Path.of`?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#72392]
We ban `Paths.get` but it master the `Path.of` methods are pretty darn similar. Maybe we should ban `Path.of` for the same reason we banned `Paths.get`?

**Comment by mark-vieira** [comment]
I don't have strong opinions on coding conventions. This _seems_ like more of a Core/Infra discussion.

**Comment by jaymode** [comment]
Makes sense. For more details, we use PathUtils to control access to the filesystem in tests since it can be changed and therefore want to control how we obtain `Path` objects and avoid implicit use of the default filesystem. `Path.of` uses the default filesystem directly so I think it should be a forbidden api.

**Comment by nik9000** [comment]
> Makes sense. For more details, we use PathUtils to control access to the filesystem in tests since it can be changed and therefore want to control how we obtain `Path` objects and avoid implicit use of the default filesystem. `Path.of` uses the default filesystem directly so I think it should be a forbidden api.

I found this because I'd written a test that used `Path.of` in master. It didn't exist on backport so I used `Paths.get`, having forgotten about the ban. The ban pushed me to `PathUtils.get` and *that* detected a sneaky file handle leak the in test! Our test utils did their job. When I used them.

**Comment by rjernst** [comment]
+1 to add `Path.of` to forbidden apis. Those methods were added to Java since we originally banned `Paths.get`.

**Comment by nik9000** [comment]
Cool. I'll ban 'em.
