### ISSUE TITLE
How to resolve: Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/elasticsearch-10045853791335045856

### ISSUE THREAD

**Issue by ContantLearn** [elastic/elasticsearch#72403]
**Linux:** CentOS_7
**JDK:** openJDK_devel_8
**ES Version:** 7.12.0
**Log:**
```
4月 28 22:47:46 localhost.localdomain systemd[1]: Unit elasticsearch.service entered failed state.
4月 28 22:47:46 localhost.localdomain systemd[1]: elasticsearch.service failed.
4月 28 22:47:46 localhost.localdomain polkitd[655]: Unregistered Authentication Agent for unix-process:1394:279830 (system bus name :1.23, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale zh_CN.UTF-8) (disconnected from bus)
4月 28 22:47:47 localhost.localdomain bash[1400]: **Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/elasticsearch-10045853791335045856**
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/java.nio.file.Files.createDirectory(Files.java:694)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:135)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
4月 28 22:47:47 localhost.localdomain bash[1400]: at java.base/java.nio.file.Files.createTempDirectory(Files.java:1011)
4月 28 22:47:47 localhost.localdomain bash[1400]: at org.elasticsearch.tools.launchers.Launchers.createTempDirectory(Launchers.java:55)
4月 28 22:47:47 localhost.localdomain bash[1400]: at org.elasticsearch.tools.launchers.TempDirectory.main(TempDirectory.java:43)
4月 28 23:01:01 localhost.localdomain systemd[1]: Started Session 3 of user root.

```

**Comment by andreidan** [comment]
@ContantLearn Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by ContantLearn** [comment]
> @ContantLearn Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

OK, Thanks For Your Answer
