### ISSUE TITLE
Add `cluster.uuid` to audit logs

### ISSUE THREAD

**Issue by bytebilly** [elastic/elasticsearch#72408]
### Description

Elasticsearch audit logs don't report the `cluster.uuid` field.
```
{
  "type": "audit",
  "timestamp": "2021-04-28T18:13:54,938+0200",
  "node.id": "-l8lCWofT1WiSzbCl5t65w",
  "event.type": "transport",
  "event.action": "access_granted",
  "authentication.type": "REALM",
  "user.name": "elastic",
  "user.realm": "reserved",
  "user.roles": [
    "superuser"
  ],
  "origin.type": "rest",
  "origin.address": "127.0.0.1:53720",
  "request.id": "J4ttGzQFRrWUPcgvQZyPtQ",
  "action": "indices:data/read/search",
  "request.name": "SearchRequest",
  "indices": [
    ".security"
  ]
}
```

### Proposal

Add `cluster.uuid` to audit logs, in the same way other Elasticsearch logs already do (server, deprecation, etc).

### Why

Observability apps rely on the UUID to identify different clusters and show them properly in the UI.
Users can also leverage this field to create alerts for specific deployments.

**Comment by DaveCTurner** [comment]
This might be tricky to get 100% accurate.

1. The cluster UUID is generated when the cluster first forms, but you can conceivably run things that generate audit entries before the cluster forms (e.g. `GET /` and `GET /_cluster/health` are still reasonable things to do in this state).

2. The cluster UUID is only persisted on data nodes and master-eligible nodes, but ephemeral nodes (e.g. coordinating-only ones) won't know this when they start up until they join the cluster. Again, this means it would be missing on audit entries logged in this period.

3. It is _almost_ immutable once set, but you can technically see an incorrect cluster UUID if a node restarts just as the cluster is forming for the first time.

4. It has a different lifecycle from an ECE deployment ID: in the event of a disaster ECE will generate a new cluster UUID for the same deployment ID. IMO the deployment ID is more conceptually useful than the Elasticsearch cluster UUID.

The cluster name (corresponding to the ECE deployment ID) suffers none of these drawbacks, I'd recommend that instead. I see that this was suggested in one of the linked issues and there weren't any arguments against it.

**Comment by bytebilly** [comment]
@DaveCTurner thanks for the feedback.
Do you know if other logfiles suffer the same drawbacks, and in case how the problem was addressed there?

I'm not against having the cluster name as an additional field, but it seems that we already standardized to use the cluster UUID and our Observability apps are built to rely on that too. This means that if we want to switch approach, it will have impacts across multiple products.

The cluster name is also more likely to be duplicated, even if it should not be in a "proper" setup. I'm thinking about docker-based clusters, or other similar automated deployments where the default is used.

What do you think?

**Comment by DaveCTurner** [comment]
TIL we record the cluster UUID in JSON logs, I didn't know that. From looking at the code I think we just simply omit it when it's unknown. The traditional (non-JSON) logs don't show it.
