### ISSUE TITLE
Kibana Docs using deprecated `elastic` user

### ISSUE THREAD

**Issue by Stexxen** [elastic/elasticsearch#72454]
Section on security refers to using "elastic" in kibana setup.

https://www.elastic.co/guide/en/elasticsearch/reference/7.12/security-minimal-setup.html#add-built-in-users

This results in the following entries in the logs on 7.12
```
  log   [09:55:35.048] [warning][config][deprecation] Setting [elasticsearch.username] to "elastic" is deprecated. You should use the "kibana_system" user instead.
  log   [09:55:35.050] [warning][config][deprecation] Setting [monitoring.username] to "elastic" is deprecated. You should use the "kibana_system" user instead.
```

docs should use `kibana_system` if that is what is recommended

**Comment by jrodewig** [comment]
@lockewritesdocs  You mind taking a look at this? Let me know if you'd rather someone else handle. Thanks!
