### ISSUE TITLE
[Docs] Add more info on Snapshot Restore process

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#72497]
@jrodewig / team - I'd like to recommend adding into docs the two most common methods of using your docs to restore snapshots (delete and restore, or restore side-by-side and then delete). 

Outlined here: https://medium.com/@stefnestor/tldr-elasticsearch-snapshot-restore-7b72dd75d74a

(It does include some non-documented but working Elasticsearch URLs, hope that's ok.)

Thanks for the great work you do!

**Comment by jrodewig** [comment]
> (It does include some non-documented but working Elasticsearch URLs, hope that's ok.)

That's a-okay. It's likely the result of a content gap on our end. Thanks for raising this @stefnestor!

**Comment by stefnestor** [comment]
Also for full cluster restores, I've been recommended to turn off Kibana, ML, ILM, & SLM. 
- [ILM](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-stop-ilm.html)
- Kibana: stop service on local machine, in ESS "stop routing requests" (not fully necessary maybe unless you have users doing heavy search requests)
- SLM: [start](https://www.elastic.co/guide/en/elasticsearch/reference/current/slm-api-start.html) & [stop](https://www.elastic.co/guide/en/elasticsearch/reference/current/slm-api-stop.html)
- [ML](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-set-upgrade-mode.html)

**Comment by jrodewig** [comment]
It looks like we already document full cluster restores in [Back up a cluster](https://www.elastic.co/guide/en/elasticsearch/reference/master/backup-cluster.html). However, we don't mention stopping ILM, Kibana, SLM, or ML. We could probably also streamline those docs a bit and cross-link from the snapshot and restore section.
