### ISSUE TITLE
Return mapped runtime fields in GET document API

### ISSUE THREAD

**Issue by timroes** [elastic/elasticsearch#72559]
We currently don't return runtime fields in any way from the [GET API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html) when retrieving an individual document. It feels like we should return them somehow in there.

We are currently in the process of switching Discover over to use this API when viewing an individual document's JSON (since we now use the fields option in the search API to retrieve the full list, we don't have the _source anymore, and we already got quiet some push-back from users on not having this "simple" JSON representation of the document anymore, they used to copy and paste into other places, https://github.com/elastic/kibana/issues/95946). Once we've done that in that JSON wouldn't be any trace of runtime fields anymore, which I think might be a bit of a bummer too.

I imagine that this does not only apply to Kibana, but any kind of frontend you'd want to build on top of ES, that contains some kind of "detail" view for documents, and would then load that document via that API and have no access to (mapped) runtime fields anymore. Given the significance we want runtime fields to play it feels to me like we want users to be able to retrieve them when returning an individual documents.

I don't think they would necessarily needed to be merged into the `_source` key in this response, but could potentially also be in their own key, e.g.

```js
{
  _id: '...',
  _source: {},
  runtimeFields: {}
}
```

**Comment by javanna** [comment]
We will discuss this with the team but is it an option to use a search instead with an ids query? The problem here is that the get API does not support the fields option, and runtime fields are computed at search time, while get is not exactly a search. Maybe we can simplify this in the way we expose it, but I think that we would end up executing a search by id anyways if we want runtime fields returned, hence my question.

**Comment by timroes** [comment]
From my understanding, even doing a search with an id query won't solve the problem, since we would still care about the _source and not asking for `fields` (that's the purpose of that screen altogether, that users wanted that compressed JSON and not the `fields` JSON - see the issue above). So in this case we'd even from that API not get any mapped runtime fields in the _source? Also we can't ask for the mapped runtime fields via the `fields` API deliberately, since we don't know which of the fields are actualy mapped runtime fields?

**Comment by javanna** [comment]
I see what you mean, thanks for explaining further.

**Comment by jtibshirani** [comment]
I don't think we want to add a special 'runtimeFields' section, to be consistent with the search API. Overall we don't draw a distinction between runtime fields in API responses -- they behave the same as other fields. I'll comment on #95946 with some questions/ ideas.

**Comment by jtibshirani** [comment]
@timroes I just caught up on your latest message in https://github.com/elastic/kibana/issues/95946#issuecomment-852911748. My understanding is that you're planning to use a request including `_source` and all `fields`. Is this enhancement request still needed (or maybe there is another change required?)

**Comment by timroes** [comment]
@jtibshirani Thanks for following up, I forgot to post here. We'll solve that from Kibana side in a way, that this won't required to fulfill our user-requirements anymore, thus no request form Kibana side anymore.

I personally still think it would make sense having this, given the importance that we give runtime fields, and if they really grow in usage we're basically taking away signifcance of the GET API altogether, but feel free to handle this issue now on your own discretion and opinion about that topic :)

**Comment by jtibshirani** [comment]
Great, I'll close for now and we'll keep a lookout for feedback related to this.
