### ISSUE TITLE
Add darwin-aarch64 artifacts to release manager configuration

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72575]
Right now we can build darwin artifacts for Apple silicon (arm) but we don't currently publish these. There are a few internal initiatives that would benefit from having these with the understanding that ML is currently disabled for these builds.

**Comment by kevingriffin** [comment]
Our team currently runs everything natively on Apple Silicon for everything except Elasticsearch using nixpkgs. It'd be fantastic to have an aarch64 darwin build to use to completely avoid Rosetta.

**Comment by mark-vieira** [comment]
@kevingriffin FWIW, the "darwin artifact" is really identical to the others except it's bundled with a native darwin JDK. You can technically avoid running Elasticsearch via rosetta in the meantime by just using the Linux distribution and providing your own JRE.

**Comment by droberts195** [comment]
> You can technically avoid running Elasticsearch via rosetta in the meantime by just using the Linux distribution and providing your own JRE.

... and also set `xpack.ml.enabled: false` since the ML native binaries won't be present for the correct platform.

**Comment by kevingriffin** [comment]
Was this closed because builds were made available?

**Comment by pugnascotia** [comment]
@kevingriffin I believe these builds will be available from 7.14.0.

**Comment by mark-vieira** [comment]
> Was this closed because builds were made available?

Correct, the latest snapshot builds for 7.14 now publish these artifacts.

https://snapshots.elastic.co/7.14.0-b3f1839d/downloads/elasticsearch/elasticsearch-7.14.0-SNAPSHOT-darwin-aarch64.tar.gz

**Comment by kevingriffin** [comment]
Great! Thank you so much.
