### ISSUE TITLE
docs: "recovery" is missing from glossary

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#7264]
At time of writing, http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/glossary.html makes no mention of the term 'recovery'. Would be lovely to have this documented for users (myself included).

**Comment by ldhun** [comment]
When I tried to write down base, I asked questions. According to glossary, I think a mention requires simple definitions, requirements, and functions. if It corrects, Is there anything else you need?

**Comment by debadair** [comment]
Should be added to the stack glossary: https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html

**Comment by dnhatn** [comment]
@debadair is this still on your agenda?

**Comment by jrodewig** [comment]
@debadair  @dnhatn  I can work on adding this.
