### ISSUE TITLE
Different interpretation of boolean config values

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#7265]
I realized that configuration values "node.master" and "node.data" are case sensitive. Moreover in one place in code only exact value "true" is interpreted as boolean true.

Class DiscoveryNode reads both properties two times. Once calls appear in nodeRequiresLocalStorage, and second time in dataNode and masterNode methods.

In nodeRequiresLocalStorage method Settings.getAsBoolean is called but in second and third case only Settings.get is called and then value compared with "equals" to String "true".

I think values shouldn't work different in different places. Second thing is that probably Boolean values shouldn't be case sensitive.

**Comment by clintongormley** [comment]
Boolean parsing of settings is now strict.  Closing
