### ISSUE TITLE
Elasticsearch hangs on input containing a huge string without spaces

### ISSUE THREAD

**Issue by athanikkal** [elastic/elasticsearch#7266]
When the input for indexing contains a huge string without spaces, Elasticsearch hangs without responding to the request. I was expecting either to discard or truncate the token or get an error response instead of server hanging. All subsequent valid requests to the server also times out. 

Steps to reproduce

1. Create a  test index using default so that the standard analyzer is used.
2. Send the attached document to index
     curl -XPUT localhost:9200/test/test/1 -d @bad_input.json

I couldn't find a way to attach a file to the bug, so I am sharing the link to the file bad_input.json file on google drive.

https://drive.google.com/file/d/0B4p5T-L62D0SR3dXMDlxemUweU0/edit?usp=sharing

**Comment by imotov** [comment]
@rmuir since v1.3.3 and v1.4.0 were released with Lucene 4.9.1, 4.10 respectively, should we close this issue?

**Comment by rmuir** [comment]
Yeah, lets close it. Thanks @athanikkal for reporting this one!

**Comment by athanikkal** [comment]
Thank you @rmuir for fixing this.
