### ISSUE TITLE
Should the default position_offset_gap be higher then 0?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#7268]
The default value of ```position_offset_gap``` can cause phrase matches across multiple field values.  I _think_ that is generally not what people want.  Can it default to ```10``` or something?

**Comment by pschanely** [comment]
Agreed.  I don't know a ton about the internals, but I suspect the only possible low-level impact of increasing this by default is that we might overflow the vint used to store the offset, making the index slightly larger?  If so, I'd think a modest gap of 10 should still be safe, right?

**Comment by nik9000** [comment]
Almost there - I've merged #12544 to 2.0 and master but I'll need another small tweak to master to make it compatible with the 2.0. I should have developed this against 2.0 and forward ported it to master. I did the opposite. But it'll be ok.
