### ISSUE TITLE
Add validation of the total_shards_per_node to the beginning of the ILM shrink step 

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#72725]
If the `total_shards_per_node` per node setting will prevent the shards of the index from all being relocated to a single node, then we should fail the shrink action without having `set-single-node-allocation` since it won't work anyway.

For example, if the index has 5 shards, but `total_shards_per_node` is set to 3 for this index, then we won't be able to actually move all the shards onto one node -- failing this early with a validation / pre-flight error would be better than attempting to `set-single-node-allocation` and then waiting forever for it to do something that it isn't going to do.

**Comment by joegallo** [comment]
Related to #56062 because this could be one of the potential failure cases mentioned there.

**Comment by DaveCTurner** [comment]
Also relates https://github.com/elastic/elasticsearch/issues/44070.

**Comment by gmarouli** [comment]
The `total_shards_per_node` limit can be set in 2 ways, on the index level and on the cluster level. Issue #76732 allows the shrink action to unset the index's `index.routing.allocation.total_shards_per_node`
setting, meaning that there will be no limit and the shrink process can continue. This means that this validation is not needed for `index.routing.allocation.total_shards_per_node`. 

However, this doesn't apply for the cluster level setting `index.routing.allocation.total_shards_per_node`. We will discuss how we want to proceed with that one.

**Comment by gmarouli** [comment]
Issue #76732 allows the shrink action to unset the index's `index.routing.allocation.total_shards_per_node`
setting, meaning that there will be no limit and the shrink process can continue. This validation is not necessary anymore.

cc @masseyke , @dakrone
