### ISSUE TITLE
sanitize index templates before removal

### ISSUE THREAD

**Issue by gbanasiak** [elastic/elasticsearch#72780]
**Kibana version:** 7.11.1

**Describe the bug:**

Removal of an index template with `*` results in removal of all matching index templates. Note: prior to ES 7.8.0, index templates with `*` were accepted (see PR https://github.com/elastic/elasticsearch/pull/56170, issue https://github.com/elastic/elasticsearch/issues/43737).

**Steps to reproduce:**
1. Create < 7.8.0 ES cluster and configure `test-*` and `test-1` legacy index templates (`PUT _template/<template-name>`).
2. Upgrade ES/Kibana to 7.11.1
3. Delete `test-*` index template in Kibana -> Stack Management -> Index Management -> Index Templates
4. Observe that both `test-1` and `test-*` index templates were removed (due to `test-*` in `DELETE _template/test-*` being interpreted as an index template name wildcard).

**Expected behavior:**
Only the index template selected for removal is in fact removed.

**Comment by gbanasiak** [comment]
I've raised this in Kibana because ES API does what it is supposed to do - it honours the wildcard. There's a slight difference in perception when you delete a specific index template in the UI (you select only one specific item on the list), vs. when running the ES API call with `*` at the end. The latter has a higher chance of being correctly interpreted by the user as "this will remove all matching index templates".

Random thoughts on how this could be addressed:
* ES API - extra option to confirm wildcard expansion (a breaking change)
* Kibana - extra warning / confirmation in case of index template _wildcard_ removal

**Comment by jakelandis** [comment]
We likely won't introduce any breaking changes for the legacy index templates. However, for composable templates (and component template) this is relevant. 

I added team discuss to discuss if, on delete and a`*` matches multiple templates, should we require an additional parameter such as `allow_multi_delete=true` ? 

somewhat related to: https://github.com/elastic/elasticsearch/issues/65667

**Comment by cjcenizal** [comment]
@gbanasiak Thanks for your explanation! Now I understand. Yes, this is certainly a confusing UX. Thanks for your thoughts on possible solutions, too.

**Comment by danhermann** [comment]
This is an unfortunate consequence of the fact that we inadvertently permitted characters such as `*` in legacy index template names in versions of ES prior to 7.8. Since the problem can be worked around and is not known to be widespread, we'd prefer not to add an option such as `allow_multiple_delete` and instead spend that development effort on ensuring that we don't have other objects that permit inappropriate characters such as `*` in their names.
