### ISSUE TITLE
[DOCS] Update "remote clusters" docs & security 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#72841]
Our current docs around CCS/CCR with security are pretty limited, and can be hard to read. 
Given most usage of CCS/CCR is likely to be using security (and therefore SSL), it would be more helpful for users if these docs explained the security setup more clearly.

Current Issues
- The security docs don't mention API Keys, but API Keys have a different security model than Users (API Keys don't have roles), and that affects how CCS/CCR security works.

Resolved issues:
1. ~The [setup docs for remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html) don't mention TLS except in the tiny section on SNI, but (for on prem) setting up TLS trust between clusters is important and requires some explanation.~
2. ~Those docs also don't link to the [CCS security](https://www.elastic.co/guide/en/elasticsearch/reference/current/cross-cluster-configuring.html) docs.~
3. ~The [security docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/cross-cluster-configuring.html) only refer to CCS and not CCR. It would be helpful to at least mention that this applies to CCR as well (and talk about permissions for CCR).~
4. ~The security docs don't mention that if the request is issued with run-as, the authenticating user needs to have the run-as privilege on the remote cluster.~
5. ~The docs don't mention Service Accounts which do not have roles, only privileges.~ _(We need to decide whether we  support CCS/CCR for Service Account)_

We might need to tackle those items one-by-one.

**Comment by tvernum** [comment]
Related : https://github.com/elastic/elasticsearch/issues/40724

**Comment by lockewritesdocs** [comment]
@tvernum, I think that #77043 covers all of the points that you outlined, which the exception of API keys. I think that we should handle that item separately.

**Comment by lockewritesdocs** [comment]
@tvernum, the updated [remote cluster docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/remote-clusters.html) cover the items listed in this issue, with the exception of API keys:

>The security docs don't mention API Keys, but API Keys have a different security model than Users (API Keys don't have roles), and that affects how CCS/CCR security works.

Do you want to cross off the items except for API keys and have this issue focus on that remaining piece of work for CCR/CCS?

Additionally, there's also #70702, which seeks to provide an introduction to API keys and explain how they work in greater detail. It's tangential to this work, but is its own initiative.

**Comment by tlrx** [comment]
I'm removing the CCR label because we think the @elastic/es-security team is in a better position to move forward this issue.

**Comment by lockewritesdocs** [comment]
Given that #70702 covers the work for writing about API keys and that the security model for CCR and CCS is changing, I'm going to mark this issue as closed.
