### ISSUE TITLE
[DOC] Add content: removing data tiers / nodes

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#72854]
Howdy! As an extension of your [Automate ILM Rollover](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/getting-started-index-lifecycle-management.html) or [Migrate index allocation filters to node roles](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/migrate-index-allocation-filters.html), will you add content on (partially/fully) removing data tiers or nodes. I'd falsely assumed I could remove the nodes from my cluster and botched everything because I hadn't changed my ILM policy yet.

AFAIK this is a working process (I'd love feedback if this is wrong for my own edification, worked this time):

1. Disable ILM 
    ```
    POST _ilm/stop
    ```
2. Move data off nodes to be deleted by reallocating shards away from the nodes to be deleted. I assume how depends on how each ILM is setup and on custom inclusion/exclusion rules set, but for my use case (removing the entire cold tier):
    - Search all indices for these settings:
        ```
        GET _all/_settings
        { ... "routing": { "allocation": { 
           "include": {
                  "_tier_preference": "data_cold,data_warm,data_hot"
        }, "require": {
                  "data": "cold"
        }}}...}
        ```
    - For ALL APPLICABLE indices, update settings, (e.g. vacate cold tier & move to hot tier; if all indices applicable use `INDEX_NAME=_all`):
        ```
        PUT INDEX_NAME/_settings
        { "routing": { "allocation": { "include": {
             "_tier_preference": "data_warm,data_hot"
         }}}}

        PUT INDEX_NAME/_settings
        { "routing": { "allocation": { "require": {
             "data": null
         }}}}

        PUT INDEX_NAME/_settings
        {  "routing": { "allocation": { "include": {
              "_tier_preference": "data_hot"
       }}}}
        ```
3. If that didn't kick off the migration, there's other rules to investigate but after, you'd then (not sure if this should be permanent or transient, but transient worked for my use case)
    ```
    PUT /_cluster/settings
    { "transient": { "cluster.routing.allocation.exclude": {
            "_name": "NODE_NAME_A,NODE_NAME_B"
    }}}
    ```
4. Babysit the migration
    ```
    GET _cat/shards?v=true&s=node,index
    
    GET _cat/nodes?v=true&h=name,disk.used&s=name

    GET _cat/recovery?active_only&v=true&h=index,shard,stage,time,files_percent,bytes_percent,translog_ops_percent,source_node,target_node

   GET  _cat/allocation?v=true
    ```
5. Now you can remove the desired nodes (edit Docker YAML, elasticsearch.yml, or however y'all do that in Elastic Cloud).
6. Restart service.
7. Re-enable ILM if it didn't come up with restart.
    ```
    GET _ilm/status

    POST _ilm/start
    ```

**Comment by jakommo** [comment]
Thanks for raising this @stefnestor . Do we still need this documented when https://github.com/elastic/cloud/issues/73416 is in place? 
Looks like it will ship with MS57 in ~2 weeks

**Comment by dakrone** [comment]
Related to: https://github.com/elastic/elasticsearch/issues/73154

**Comment by DanRoscigno** [comment]
Thanks @stefnestor , I will setup ILM in Elastic Cloud using the old attributes, and then switch to the node roles to educate myself on the new way.

**Comment by kunisen** [comment]
FYI - I think we have addressed this issue in favor of https://github.com/elastic/cloud/issues/93379, which ended up with this PR (https://github.com/elastic/cloud/pull/99291) getting merged and now in public, for both tier with and without searchable snapshot:
https://www.elastic.co/guide/en/cloud/current/ec-disable-data-tier.html
