### ISSUE TITLE
Bug in "fields" - EQL

### ISSUE THREAD

**Issue by srikwit** [elastic/elasticsearch#72864]
Dear Team,

From the documentation at https://www.elastic.co/guide/en/elasticsearch/reference/master/eql.html#retrieve-selected-fields

I am trying to use the fields option in EQL but I am getting an error as follows, I have followed the documentation and I am providing the differences against regular search for your reference:

1. Regular fields - works
```
GET winlogbeat-7.12.0/_search
{
  "fields": []
}
```

2. EQL fields - Does not work
```
GET winlogbeat-7.12.0/_eql/search
{
  "fields": []
}

{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[2:3] [eql/search] unknown field [fields]"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[2:3] [eql/search] unknown field [fields]"
  },
  "status" : 400
}

```
I have simplified the example from the documentation and the issue I find is with the following description:
_You can also use the fields parameter to retrieve and format specific fields in the response. This field is identical to the search API’s fields parameter._

I would also like to point out that the fields option is never populated from the console when we type the name in the standard search as well as EQL search which I have uploaded for your reference.

![image](https://user-images.githubusercontent.com/4140019/117564240-d854c200-b0b3-11eb-870f-d746950cd144.png)

**Comment by matriv** [comment]
Hi @srikwit  This is a feature that has been added with: https://github.com/elastic/elasticsearch/pull/68962 and is available in `7.13.0` and not `7.12.x`. Please check the documentation for the relevant version you're using, for example: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/eql.html#retrieve-selected-fields
