### ISSUE TITLE
Add option to prevent recovering replica shards onto nodes that did not have them locally.

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#7288]
For large deployments ES shard recovery after a node goes down or some networking event occurs seems to cause more problems than are necessary because all of the shards end up getting shuffled around the cluster and can cause other performance problems. Seems better to leave some replicas uninitialized until the nodes are alive again. Right now the recovery time from an event affecting a node is proportional to the total amount of data on that node rather than proportional to the amount of changed data on that node if we just waited for the node to be up again so it can recover locally. This behavior also makes it harder to contain a problem from affecting the entire cluster.

## Backstory

We had a 4 min network disruption in one of our 3 data centers (14 data nodes per DC) at 23:04. As you would expect ES queries started timing out to that DC giving us a 30% error rate, but then recovered after about 5 minutes.

![](https://i.cloudup.com/0EhM4BnqMu.png)

However, after about 30 minutes queries again started timing out and that continued to get worse over the next two hours.

The root cause of these bad queries was due to shards getting shuffled around within the DC that had the networking problem.

![](https://i.cloudup.com/8mbgBq1PQt.png)

Some nodes actually ended up getting overloaded with shards causing server performance problems as the shards got initialized on those nodes and they could not handle the increasing query load (those first 14 bars are disk space in the affected DC):

![](https://i.cloudup.com/DBVZ2plrzV-3000x3000.png)

## Proposed Solution

I think a better set of "production" settings would say "do not re-allocate shards to other nodes when a node goes down".

It seems like cluster.routing.allocation.enable should have an additional option: recovery_and_new (this would still allow rebalancing). "Recovery" in this case would mean that shards can only be initialized on a node that already had them on it. 

The assumption here is that the cluster has enough replication that losing a single replica is not such a large event that it is worth triggering a whole lot of network traffic and potentially causing other problems.

## Other Workarounds

I don't think there is a way to do this right now. I could disable all allocation, but that would prevent shards for new indices from being allocated. recover_after_time could almost serve this purpose (I could set the timeout to 3 hours to give the ops team time to get a server back up), but that setting seems to only apply on a full cluster restart.

**Comment by clintongormley** [comment]
This is now closed by #11438, #12421, and #11417

**Comment by gibrown** [comment]
@clintongormley thanks to you and everyone else for these improvements.
