### ISSUE TITLE
Improve the error message for run-as failure

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#72904]
Elasticsearch supports one user (`User_A`) impersonate another user (`User_B`) with the run-as feature. If `User_A` does _not_ have the privilege to run-as `User_B` when issuing a request with run-as, ES correctly rejects the request. But error message is along the line of:
```
action [...] is unauthorized for user [User_A] run as [User_B]
```
This is not accurate enough and can be misleading at times because when the authorization fails, we don't really know whether the action is unauthorized for either `User_A` or `User_B`. What we do know is that `User_A` cannot run-as `User_B`.  Hence the error message should be improved to be more precise about the actual failure.

**Comment by PedroCMonteiro** [comment]
I would like to work on a PR to implement this, but i'm having difficulty with finding where the error message is being built, i would appreciate some help.
