### ISSUE TITLE
null_value on date field

### ISSUE THREAD

**Issue by wc-willa** [elastic/elasticsearch#72909]
i just want to ask question.
because i can not find any effective solution.
i create a index , date type field has null_value like below

"implementDateT": {
  "null_value": "1900-01-01",
  "format": "yyyy-MM-dd",
  "type": "date"
},
But it's useless, How do i set date field null_value

**Comment by cbuescher** [comment]
@wc-willa I'm curious about what is not working as expected here. I'm using 7.12 and just tried:

```
DELETE test*

PUT test
{
  "mappings": {
    "properties": {
      "implementDateT": {
        "null_value": "1900-01-01",
        "format": "yyyy-MM-dd",
        "type": "date"
      }
    }
  }
}

PUT /test/_doc/2
{
  "implementDateT" : null
}

GET /test/_search
{
  "query": {
    "range": {
      "implementDateT": {
        "gte": "1899-01-01"
      }
    }
  }, "fields": ["implementDateT"]
}
```

We seem to correctly use the "null_value" in search and can retrieve the field value using either "docvalue_fields" or "fields". The fact that `null` still shows up in the "_source" is intentional I think.

**Comment by wc-willa** [comment]
Thank you very much! I found the problem, the null_value setting is correct,i use the jpa to save entity,the null field is ommited,so the es document has no the implementDateT field. @cbuescher

**Comment by cbuescher** [comment]
Great, closing then. I would like to recommend the support forums over at https://discuss.elastic.co if you have further questions around usage. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here then.
