### ISSUE TITLE
Introduce version barrier during all upgrades

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#72911]
Today when upgrading to the next major version we have a so-called _major version barrier_: once the cluster comprises nodes of the new major version then nodes of the previous major version are prevented from joining the cluster. This means we can be certain that `clusterState.nodes().getMinNodeVersion().major` will never decrease, so we can implement upgrade logic that relies on the cluster remaining in its wholly-upgraded state.

We do not have the same barrier for minor version upgrades, so we cannot be certain that `clusterState.nodes().getMinNodeVersion()` never decreases. This makes implementing certain BWC changes in minor releases much harder: there is never a point in time where it is safe to consider the cluster as fully upgraded and therefore to fully migrate to the newer functionality.

I would like to implement a version barrier for all upgrades, blocking older versions from rejoining a cluster that comprises entirely upgraded nodes even within the same major series.

This would have minimal impact in almost all upgrades (and no impact when not upgrading). It only changes behaviour when all the older-version nodes unexpectedly leave the cluster at the same time during the upgrade, which would only happen due to a fault e.g. a network partition. If that happens, the user would need to complete the upgrade to bring their cluster back to health. We already (almost) document this in the **IMPORTANT** note at the bottom of the [rolling upgrade docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html); we would only have to delete a single instance of the word `major` to account for the change proposed here. I'm therefore not even sure this would count as a breaking change so much as a bugfix to remove some undue leniency.

Relates https://github.com/elastic/elasticsearch/pull/72586 which introduces some rather complex logic in the snapshot state machine to work around a bug arising from the rare situation that `clusterState.nodes().getMinNodeVersion()` decreases.

**Comment by droberts195** [comment]
This would certainly benefit more complex features like ML.  We have logic today that stops people using new ML functionality until the whole cluster is on a version that will understand it.  At the moment there's a loophole where an old node that doesn't understand that new functionality could join the cluster after new ML functionality has been used, and then suffer exceptions.  If that old node then got elected as the master node then the exceptions from encountering new ML constructs it didn't understand might be even more problematic.  (I don't believe any user has actually suffered a noticeable problem due to this, but it's best not to be in a situation where we are at risk of somebody having a bad experience in the future.)

**Comment by DaveCTurner** [comment]
We discussed this as a team today and concluded it's the right thing to do, and we can reasonably treat it as a bug fix. I will reach out to some folks responsible for the orchestration side of things to make sure it's not going to cause problems for them first.

**Comment by ywangd** [comment]
Just adding another data point: We [assumed](https://github.com/elastic/elasticsearch/pull/70956#discussion_r609410551) this version barrier for minor versions when adding support for API Key metadata. It is not catastrophic if the assumption is not true, but it is certainly great if it can be made reliable. Thanks!

**Comment by DaveCTurner** [comment]
The orchestration folks confirmed this will be ok: in terms of this kind of thing we don't distinguish minor and major upgrades anyway.
