### ISSUE TITLE
[Docs] Add EQL limtation that it does not work with CCS

### ISSUE THREAD

**Issue by a03nikki** [elastic/elasticsearch#72958]
There is no mention in the Elasticsearch 7.12 documentation that Event Query Language (EQL) does not work with cross cluster search (CCS).  I only found out about it when I was told by another user and found #64784 in this repository.

I would have expected to see it listed as a limitation on the [main EQL page](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/eql.html) or [Syntax limitations](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/eql-syntax.html#eql-syntax-limitations).

The Security doc only mentions a CCS limitation for [indicator matches](https://www.elastic.co/guide/en/security/7.12/detection-engine-overview.html#support-indicator-rules).

**Comment by jrodewig** [comment]
Thanks for raising this @a03nikki. I'll get this added.

In the meantime, I did want to point out that the CCS docs note supported APIs: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-apis
