### ISSUE TITLE
INDEX DELETE with wildcard doesn't delete all matching indexes

### ISSUE THREAD

**Issue by andrassy** [elastic/elasticsearch#7295]
When trying to delete multiple indexes, Issuing a DELETE with a wildcard seems to delete 20 indexes at a time and then returns with an {"acknowledge":"true"}. If this is correct behavior then this should be added to the documentation index\delete documentation, otherwise it needs to be fixed.

For example...

DELETE http://192.168.10.73:55590/*event.2013-* HTTP/1.1

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 21

{&quot;acknowledged&quot;:true}

**Comment by javanna** [comment]
I had a look at this, I see the problem and I will work on fixing it. It all boils down to how delete index works internally. One cluster state update per index gets processed by `TransportDeleteIndexAction`, which tends to "forget" about previous indices failures. If the last delete index tasks succeeds, a positive response is returned, whereas if the last delete index tasts fails (or times out), then a failure is returned. This is bad :(  I am on it

**Comment by yodog** [comment]
also happens with `curl -XDELETE 'http://localhost:9200/_all'`

**Comment by javanna** [comment]
This issue will be solved when we get #11189 in, which is a good fix but needs a proper test written for it. With that fix we will return a reliable last failure at least. That said #11258 (or something along those lines) would improve things even better, as it would treat the request as a single cluster state update task. The annoying part in fact is that we have one single failure in the response at the moment, but that's only the last failure, while we could have more potentially.

**Comment by javanna** [comment]
Fixed via #11258 . Closing
