### ISSUE TITLE
Make org.elasticsearch.script.Script.Builder public 

### ISSUE THREAD

**Issue by funcfoo** [elastic/elasticsearch#73035]
This class is private.
``` java
/**
 * Helper class used by {@link ObjectParser} to store mutable {@link Script} variables and then
 * construct an immutable {@link Script} object based on parsed XContent.
 */
private static final class Builder {
    private ScriptType type;
    private String lang;
    private String idOrCode;
    private Map<String, String> options;
    private Map<String, Object> params;

    private Builder() {
        // This cannot default to an empty map because options are potentially added at multiple points.
        this.options = new HashMap<>();
        this.params = Collections.emptyMap();
    }
}
```

Why not make this class public?
Allow users to use, like
```java
ScoreFunctionBuilders.scriptFunction(Script.builder().setStored("my-script").setParams(Map.of()));
```

**Comment by rjernst** [comment]
The Script class (and Builder) are internal implementation details of Elasticsearch. Users don't use it. Within Elasticsearch, the parse methods are what are needed most often. The builder is there for the implementation of parsing.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.

**Comment by funcfoo** [comment]
Thanks for answering!
