### ISSUE TITLE
Tests tab in gradle enterprise doesn't include all tests from 6.8

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73046]
Check out this build with a failing test:
https://gradle-enterprise.elastic.co/s/5gvcejrbhmhpw/failure#1

But if you click the "tests" tab you don't get those tests:
https://gradle-enterprise.elastic.co/s/5gvcejrbhmhpw/tests

**Comment by nik9000** [comment]
That build is in 6.8 - maybe it's just a 6.8 thing?

**Comment by nik9000** [comment]
Yeah, just 6.8 - here is a 7.12 build that failed with actual failing tests: https://gradle-enterprise.elastic.co/s/npxmfxjlxapby/tests/failed

**Comment by mark-vieira** [comment]
This is a known limitation with the 6.8 branch. It still uses the legacy Ant junit runner for test execution so test information isn't captured in build scans.

**Comment by nik9000** [comment]
> This is a known limitation with the 6.8 branch. It still uses the legacy Ant junit runner for test execution so test information isn't captured in build scans.

Thanks!
