### ISSUE TITLE
[CI] Darwin times out cloning

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73070]
The darwin CI builds are consistently failing with:
```
11:11:10 using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
11:11:10  > git fetch --tags --force --progress -- https://github.com/elastic/elasticsearch.git +refs/heads/*:refs/remotes/origin/* # timeout=20
11:11:11 ERROR: Timeout after 20 minutes
11:31:12 ERROR: Error cloning remote repo 'origin'
```

**Comment by nik9000** [comment]
The delivery folks already know about it but I wanted to open this so the next person on test triage doesn't have to track this down again.

Here a failing build example:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.13+multijob+platform-support-darwin/14/console

**Comment by mark-vieira** [comment]
We no longer have CI running on macos agents.
