### ISSUE TITLE
Fedora32 times out on 7.x bwc builds

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73073]
We consistently reach the suite timeout on fedora 32.

**Build scan**:
https://gradle-enterprise.elastic.co/s/ibuiedec52dom

**Repro line**:
Run :qa:mixed-cluster:v6.8.16#mixedClusterTest

**Reproduces locally?**:
I'm not going to try. This seems to be limited to fedora 32 only and I don't have it.

**Applicable branches**:
7.x, 7.13

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test.failed-testcases.class:%22org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT%22%20AND%20test.failed-testcases.summary:%22classMethod%22'),sort:!(process.time-start,desc))

**Failure excerpt**:
```
[2021-05-14T03:19:57,040][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=tasks.list/10_basic/tasks_list test] before test
Mai 14, 2021 3:19:57 AM com.carrotsearch.randomizedtesting.ThreadLeakControl$2 evaluate
WARNING: Suite execution timed out: org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT
==== jstack at approximately timeout time ====
"I/O dispatcher 832" ID=889 RUNNABLE (in native code)
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
```

**Comment by mark-vieira** [comment]
This is related to https://github.com/elastic/elasticsearch/issues/69973. Normally we see those timeouts on Windows because, well, Windows is slow. Why Fedora 32 seems similarly so I'm not completely sure why.

**Comment by benwtrent** [comment]
yet another timeout for fedora 32: https://gradle-enterprise.elastic.co/s/o4eklgip5bxzo

Nothing big in the threads, it seems to occur in cleanup?

**Comment by mark-vieira** [comment]
After discussing with @bytebilly, we're removing testing on Fedora 32 for now since it's EOL and isn't part of our support matrix anyhow.
