### ISSUE TITLE
[Deprecation info API] Support for meta field

### ISSUE THREAD

**Issue by alisonelizabeth** [elastic/elasticsearch#73089]
In Upgrade Assistant (UA), we want to help users as much as possible to resolve deprecations.

In some cases, UA may need additional context other than what is provided in the message field in order to resolve a deprecation. For example, old ML model snapshots may require to be upgraded or deleted before upgrading to 8.0. In order to upgrade or delete the snapshot, the job id and snapshot id is required. 

The deprecation info API currently provides the following message for the above example:

```
model snapshot [1] for job [deprecation_check_job] needs to be deleted or upgraded
```

While the job id and snapshot id technically can be extracted from the message using a regex, it is brittle and prone to regressions if the message format ever changes. 

Related to https://github.com/elastic/kibana/issues/91879

**Proposal:**
I propose we add a new field to the deprecation info API where each deprecation can provide optional parameters that UA can then consume.

```
{
   "cluster_settings": [],
   "node_settings": [],
   "index_settings": {},
   "ml_settings": [
      {
         "level":"critical",
         "message":"model snapshot [1] for job [deprecation_check_job] needs to be deleted or upgraded",
         "url":"/docs",
         "details":"deprecation details...",
         // meta may not be the appropriate name here, but just a suggestion
         "meta":{
            "job_id":"deprecation_check_job",
            "snapshot_id":"1"
         }
      }
   ]
}
```

**Comment by benwtrent** [comment]
++ I think using a field called `meta` is good. It should be a `Map<String, Object>` in java I think. Anything more complex seems unnecessary because it will be per deprecation warning.

**Comment by martijnvg** [comment]
@alisonelizabeth @benwtrent I started to work on adding the `meta` field to the deprecation api in #74085 like is discussed here. For the ml model snapshot deprecation I added the `job_id` and `snapshot_id` parameters. Are we still okay with these names? 

Are there any other parameters that we like to add to other deprecations? Like for example the name or value of index/node settings that are deprecated?

Currently in the mentioned pr, the metadata is a map that allows nesting of parameters (`Map<String, Object>`. I wonder whether this is needed. Can the custom metadata of a deprecation issue be a simple string based key/value pair (`Map<String, String>`)?

**Comment by alisonelizabeth** [comment]
Thanks @martijnvg!

> For the ml model snapshot deprecation I added the job_id and snapshot_id parameters. Are we still okay with these names?

👍 That works for me.

> Are there any other parameters that we like to add to other deprecations? Like for example the name or value of index/node settings that are deprecated?

Possibly. I could see this being helpful for the deprecated translog retention settings as well. I'd have to go back and look through the other deprecations. However, in general, I think anywhere there are deprecated settings it would be useful to include as part of the `meta` field.

> Currently in the mentioned pr, the metadata is a map that allows nesting of parameters (Map<String, Object>. I wonder whether this is needed. Can the custom metadata of a deprecation issue be a simple string based key/value pair (Map<String, String>)?

I think ML is currently the only use case for this, in which I think a simple string based key/value pair is fine. That said, I'm not sure if @benwtrent had other scenarios in mind when he suggested nesting parameters.

**Comment by benwtrent** [comment]
@martijnvg @alisonelizabeth 
> Currently in the mentioned pr, the metadata is a map that allows nesting of parameters (Map<String, Object>. I wonder whether this is needed. Can the custom metadata of a deprecation issue be a simple string based key/value pair (Map<String, String>)?

ML currently doesn't need to support anything other than Strings, but I would be cautious around choosing an unnecessarily restrictive API here for future BWC reasons.

**Comment by martijnvg** [comment]
>  However, in general, I think anywhere there are deprecated settings it would be useful to include as part of the meta field.

That sounds good. I will do this as part of a followup pr ( adding `setting_name` / `setting_value` as custom metadata).

> ML currently doesn't need to support anything other than Strings, but I would be cautious around choosing an unnecessarily restrictive API here for future BWC reasons.

Good point, let's just keep it open. Which is also what we do in other places were we allow custom metadata.
