### ISSUE TITLE
Autoscaling deciders use "frozen" terminology instead of "partially mounted" terminology 

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#73132]
The [autoscaling deciders](https://www.elastic.co/guide/en/elasticsearch/reference/master/autoscaling-deciders.html) for the frozen tier use the "frozen" terminology as opposed to the recent "partially mounted" terminology.

**Comment by henningandersen** [comment]
Nice catch. The two deciders are specific to the frozen tier so in some sense, the names of the deciders are not entirely wrong. I see two options:

1. We leave the decider names but change the documentation around this to state that for instance the frozen shards decider bases decisions on number of partially mounted shards in the frozen tier.
2. We change the decider names to `partially_mounted_shards` and `partially_mounted_storage` as well as documentation. We would need to allow the old names in 7.x.

@jasontedor it is not entirely clear if you are after option 1 or 2, will you clarify?

**Comment by jasontedor** [comment]
@henningandersen Sorry for leaving it ambiguous. I'm referring to option 1, a documentation change to the *descriptions* of the deciders, which currently refer to "frozen shards" and "frozen indices" which is quite misleading now that these terms are specific to indices in that state from the freeze API. For example, the frozen storage decider is described as:

> The frozen storage decider (frozen_storage) calculates the local storage required to search the current set of frozen indices based on a percentage of the total data set size.

I don't think changing the *names* of the deciders is necessary. As you say, these are aligned with the node role, `data_frozen`, these deciders apply to.
