### ISSUE TITLE
Retry ILM force merge step on shard failures

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#73142]
Today ILM's `forcemerge` step treats any non-exception response as success:

https://github.com/elastic/elasticsearch/blob/09d1b97b5f566481d8395fa04618e6ee1da21d28/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ForceMergeStep.java#L44-L46

This is a very weak measure of success, it means that the coordination of the request was successful and not that any merging actually took place. More specifically it ignores `response.getFailedShards()` which is nonzero if some shards could not be merged, perhaps because they were initialising at the time the step executes.

If we ignore an initialising replica here then it may be promoted to primary later, which means that other shard copies and snapshots will continue to contain multiple segments as if the `forcemerge` step did not exist. In particular we prefer searchable snapshots to use single-segment shards for performance reasons but we cannot rely on ILM to generate such shards.

Also relates https://github.com/elastic/elasticsearch/issues/17094#issuecomment-838043706: if we were to permit users to cancel ongoing force-merge tasks then ILM should not carry on regardless.

I think we should retry this step until no shards report failures.

Note that today "no shard failures" is not a watertight guarantee that all shard copies will end up force-merged, because we do not apply the force-merge action to relocation targets or account for shard movements that start while the force-merge is ongoing. We can fix that too, and I would prefer to do that by reporting these unmerged shards as failures once ILM respects that.

**Comment by andreidan** [comment]
We discussed this today and decided to retry in ILM until we don't get failed shards in the response anymore.
