### ISSUE TITLE
Internal: Management thread pool should reject requests when there are too many

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#7318]
Today, the management thread pool (used by stats and cats) is bounded to 5, but it still accepts further requests, and then waits indefinitely for a thread to free up.

This is dangerous because node stats can be a somewhat costly operation (in proportion to number of shards on the node)....

And it confounds debugging, because it can cause loooong hangs in e.g. node stats requests via browser/curl, and it also is not graceful for recovering from "too many management requests" overload.

If we instead rejected the request it would make it clearer which clients are causing too much load.

**Comment by bleskes** [comment]
we should probably revisit this now that we have a different execution model for indices stats etc (#7990) . Reopening ....

**Comment by clintongormley** [comment]
@jasontedor may be of interest to you?

**Comment by jasontedor** [comment]
Superseded by #18613
