### ISSUE TITLE
Close API treats data streams and data stream aliases differently

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#73195]
**Elasticsearch version** (`bin/elasticsearch --version`):
Latest `elasticsearch-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):

Darwin  19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

The close API returns an error when directly targeting a data stream. If the target is a data stream alias,  the API closes
the backing indices of the alias's data streams. I expected the API to treat data streams and data stream aliases similarly.

**Steps to reproduce**:

1. Create a data stream.

```
PUT _data_stream/logs-foo-bar
```

2. Add the stream to a data stream alias.

```
PUT logs-foo-bar/_alias/logs
```

3. Attempt to close the data stream directly.

```
POST logs-foo-bar/_close
```

The API returns an error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [logs-foo-bar]",
        "resource.type" : "index_or_alias",
        "resource.id" : "logs-foo-bar",
        "index_uuid" : "_na_",
        "index" : "logs-foo-bar"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [logs-foo-bar]",
    "resource.type" : "index_or_alias",
    "resource.id" : "logs-foo-bar",
    "index_uuid" : "_na_",
    "index" : "logs-foo-bar"
  },
  "status" : 404
}
```

4. Attempt to close the data stream alias.

```
POST logs/_close
```

The API closes the stream's backing indices:

```
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "indices" : {
    ".ds-logs-foo-bar-2021.05.18-000001" : {
      "closed" : true
    }
  }
}
```

**Comment by jakelandis** [comment]
related: https://github.com/elastic/elasticsearch/issues/66163
cc @martijnvg

**Comment by martijnvg** [comment]
Note that this is a bug in unreleased code.

**Comment by jrodewig** [comment]
Thanks @jakelandis @martijnvg. Feel free to relabel this as an enhancement as the feature is still in development.
