### ISSUE TITLE
Get Aliases API fails when a system data stream exists and security is enabled

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#73218]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.0, probably all later versions

**Plugins installed**: []

**JVM version** (`java -version`): built-in

**OS version** (`uname -a` if on a Unix-like system): MacOS

**Description of the problem including expected versus actual behavior**:
When a system data stream exists and Security is enabled, the Get Alias API will always fail.

**Steps to reproduce**:

 1. Start an Elasticsearch cluster with security enabled. Perform all following steps as superuser.
 2. Create a system data stream:
```bash
curl -X POST -u elastic-admin:elastic-password "localhost:9200/.fleet-actions-results/_doc" -H 'Content-Type: application/json' -H 'X-elastic-product-origin: fleet' -d'{"@timestamp": 0}' | jq
```
 3. Attempt to use the Get Aliases API, with or without any index name, e.g. `GET _alias` or `GET _alias/auditbeat-7.13.0`.
 4. Observe the error response.

Note that the Get Alias API behaves as expected when security is not enabled.

**Provide logs (if relevant)**:
The error response:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
  },
  "status": 400
}
```

**Comment by gwbrown** [comment]
This is the cause of https://github.com/elastic/kibana/issues/100019.

**Comment by williamrandolph** [comment]
It looks to me as if the problem is in `TransportGetAliasesAction#masterOperation`:

```java
        try (ThreadContext.StoredContext ignore = threadPool.getThreadContext().newStoredContext(false)) {
            concreteIndices = indexNameExpressionResolver.concreteIndexNames(state, request);
        }
```

We intend for the invocation of `newStoredContext(false)` to remove the header that denies access to system indices. But it doesn't look like `newStoredContext(false)` actually does this; it just ensures that the stored context is restored when we exit the try-with-resources block.

The method `ThreadContext#stashContext()` does remove the existing headers for the code within the try-with-resources block. I have done some initial testing with this change, but I need to discuss it with other devs before committing to it.

**Comment by deepikakeshav-qasource** [comment]
Hi @ruflin,

As per the ticket [#100019](https://github.com/elastic/kibana/issues/100019) , We have validated this ticket on **7.13.0** BC7 build and Please find the below observations:

Build Details:
```
Version:7.13.0 BC7 On-Prem
Commit:6ce6847436ff9bef0ad91268b6585e0f9339c9fd
Build:40864
```
**Observations:**

- When we install Fleet Server Agent it is installed with Default Fleet Server Policy, and we are able to install beats if we make no change to Fleet Server Agent.
![agent_install_no_chnage](https://user-images.githubusercontent.com/61860752/118769658-0a2d0c00-b89e-11eb-8ee3-f91f009bc048.jpg)

![beat_install](https://user-images.githubusercontent.com/61860752/118769664-0b5e3900-b89e-11eb-9023-2b8b191540b4.jpg)

- However when we attempted to Assign Fleet server agent to Default policy having System, Fleet Server and endpoint integration , we are further unable to install beats on the Kibana environment and getting following errors:

**SCREENSHOT**
![agent_after_policy_change](https://user-images.githubusercontent.com/61860752/118769653-09947580-b89e-11eb-924f-0b46ea634565.jpg)

![beats_error](https://user-images.githubusercontent.com/61860752/118769669-0c8f6600-b89e-11eb-9e9b-33349d9f688f.jpg)

**Agent Logs after changing the policy**
[logs.zip](https://github.com/elastic/elasticsearch/files/6506493/logs.zip)

Thanks!!

**Comment by EricDavisX** [comment]
@deepikakeshav-qasource can you confirm, you have re-tested this in BC8 or newer in the same scenario and that it works?  Thank you!

**Comment by deepikakeshav-qasource** [comment]
Hi @Eric,

We have validated this ticket on **7.13.0** BC9 build and observed that issue **Fixed**. Now able to install the beats When an agent is installed and policy is changed from Fleet server agent to Default policy having System, Endpoint and Fleet Server integration

Build Details:
```
Version:7.13.0 BC9 On-Prem
Commit:9863e88bd63ad546b9d36e6b0c0c55cb65dd9081
Build:40865
```

**Screenshot:**
![agent_policy_change_7 13 0_bc9](https://user-images.githubusercontent.com/61860752/119086215-c7e10780-ba22-11eb-98f3-4cd2f52e5bc3.jpg)

![auditbeat_installed_7 13 0_bc9](https://user-images.githubusercontent.com/61860752/119086216-c9123480-ba22-11eb-88e0-6452a22f4d8e.jpg)


Thanks!!
