### ISSUE TITLE
[DOC] Troubleshooting Expensive Search Results

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#73222]
Hiya! Will you correct, finish, & post this type of doc content related to diagnosing expensive search requests? Or maybe you have it & I missed it (sorry!). I like all the content, but think it would do well consolidated into the specific issue-resolution use case :)

---

**Index Slowlogs**. Since you know the particular index, we recommend updating index settings (1) to show slow logs (2). This should help you pinpoint slow and therefore heavy requests.This may/not pinpoint the dashboard/visualization directly or may just "give you a feel" for the aggregation/request type being loaded to then match up to visualization objects.

**Audit Logs**. If you find you need to expand your search, we recommend enabling audit logs (3). These are the proxy log traffic you requested before. These piggy back into your Observability Logs (4), from Logs & Metrics (5), which you can also lookup in Kibana / Discover (6) after creating reference Kibana / Index Pattern (7) elastic-cloud-logs-*. As an example Elastic Cloud setup, I frequently use (temporarily not long term, because of volume generated & size w/request body enabled):

elasticsearch.yml (8)
```
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: _all
xpack.security.audit.logfile.events.emit_request_body: true
```

Links

1. https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html
2. https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html
3. https://www.elastic.co/guide/en/elasticsearch/reference/current/auditing-settings.html
4. https://www.elastic.co/guide/en/observability/current/tail-logs.html
5. https://www.elastic.co/blog/monitoring-elastic-cloud-deployment-logs-and-metrics
6. https://www.elastic.co/guide/en/kibana/current/discover.html
7. https://www.elastic.co/guide/en/kibana/current/index-patterns.html
8. https://www.elastic.co/guide/en/cloud/current/ec-add-user-settings.html

**Comment by aliciascott** [comment]
I believe this blog already contains this info:
https://www.elastic.co/blog/advanced-tuning-finding-and-fixing-slow-elasticsearch-queries

**Comment by stefnestor** [comment]
Good find & agreed! Can we also add that type of content into the docs?

**Comment by stefnestor** [comment]
Appears this didn't auto-close as I'd thought it would. Closing. Thanks @albertzaharovits! ❤️
