### ISSUE TITLE
Configuring HunSpell filepaths for `.dic` and `.aff` separately for stemming

### ISSUE THREAD

**Issue by GokulNC** [elastic/elasticsearch#73259]
In HunSpell Token-Filter Analyzer for Stemming, while [configuring its parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-hunspell-tokenfilter.html#analysis-hunspell-tokenfilter-configure-parms), is it possible to specify separate full-paths for `.dic` and `.aff` files instead of having to set a common directory per language?

If not, is it possible to take this as a feature request? 

**Use-case:**  
In Amazon's ElasticSearch Service, it is only possible to upload and link individual dictionary files instead of directories.  
([Detailed issue](https://forums.aws.amazon.com/thread.jspa?messageID=984498))

Even if not for this AWS issue, this will be an useful feature to have.
(I think the same is the issue with [Elastic on Google Cloud](https://www.elastic.co/partners/google-cloud))
Thanks!

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
