### ISSUE TITLE
_scripts end point does not return a request body for 404 responses

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#7325]
Tested against both indexed scripts and indexed search templates in 1.3.1:

A HTTP GET to fetch back a non-existing script or search template returns an empty HTTP body with a HTTP header (404):

```
_scripts/groovy/asdasdasfe
_search/template/asdasdasdas
```

Would be nice to return an actual HTTP body to be consistent with our other APIs.  Perhaps something like the following?

```
{
  "status" : 404,
  "error" : "IndexedScriptMissingException[[asdasdasfe] missing]"
}
{
  "status" : 404,
  "error" : "IndexedSearchTemplateMissingException[[asdasdasdas] missing]"
}
```

**Comment by javanna** [comment]
Rather than returning an error, we should return simlar content as what the get api returns. This is the approach taken in #10396. We make sure that a body is always returned, whcih always contains metadata info and the found boolean flag.
