### ISSUE TITLE
[Doc] Runtime fields and Grok - additional example and Grok pickiness

### ISSUE THREAD

**Issue by toby-sutor** [elastic/elasticsearch#73262]
At https://www.elastic.co/guide/en/elasticsearch/reference/master/runtime-examples.html#runtime-examples-grok we are documenting how to use runtime fields in the mapping. Can we please also elaborate that this can be used in a search query. E.g.:
````
GET my-index/_search
{
  "runtime_mappings": {
    "clientip": {
      "type": "keyword",
      "script": {
        "source": """
        String clientip=grok('%{COMMONAPACHELOG}').extract(doc["message"]).value)?.clientip;
if (clientip != null) emit(clientip);
"""
      }
    }
}
}
````

In addition would it be worth to document that accessing tokenized values (neither `keyword` nor `wildcard` but text with fielddata) via `.extract(params["_source"]["message"])` (instead of `.extract(doc["message"])`).

Finally, Grok seems to be more picky on the runtime fields compared to the Kibana Grok debugger - especially on the whitespaces. E.g. 
Raw: `"clientip = 127.0.0.1"`
Kibana Grok debugger: `clientip = %{COMMONAPACHELOG}` - will match
Runtime Grok: `grok("clientip = %{COMMONAPACHELOG}")` - will not match and requires `grok("clientip\\s=\\s%{COMMONAPACHELOG}")` instead.

Ref. https://github.com/elastic/sdh-elasticsearch/issues/4361

**Comment by lockewritesdocs** [comment]
I just tested @cbuescher's findings and did not have to mask spaces in the grok pattern. For example `String ap=grok('cLApName = %{NOTSPACE:ap}').extract(doc["message"].value)?.ap;` works without having to mask the spaces on either side of the `=`. Complete example is below.

```
PUT /mn-spectrum-events
{
  "mappings": {
    "properties": {
      "message": {
        "type": "wildcard"
      }
    }
  }
}

POST mn-spectrum-events/_doc
{
  "message": """A "ciscoLwappApIfDownNotify" event has occurred, from {t} device, named DEF-STE10-WLC-1.

This notification is generated when AP's Interface operational status goes down.

cLApSysMacAddress = 4ImdPeHg
cLApDot11IfSlotId = 0
cLApDot11IfSlotId.cLApSysMacAddress.cLApDot11IfSlotId = 0
cLApAdminStatus = 1
cLApDot11IfAdminStatus = 1
cLApIfUpDownFailureType = 2
cLApIfUpDownCause = Indicates that while the radio state should be updated on controller, no reset should be reported.
cLApIfUpDownFailureCode = RADIO_RC_NO_REPORT
cLApName = DEF-230WCH-AP24
"""
}

GET mn-spectrum-events/_search
{
  "runtime_mappings": {
    "wifi_AP_name": {
      "type": "keyword",
      "script": {
        "source": """
        String ap=grok('cLApName = %{NOTSPACE:ap}').extract(doc["message"].value)?.ap;
if (ap == null) emit("doh!");
if (ap != null) emit(ap);
"""
      }
    }
  },
  "size": 3,
  "fields": [
    "wifi_AP_name"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "wildcard": {
            "message": "*ciscoLwappAp*"
          }
        }
      ]
    }
  }
}
```

**Comment by lockewritesdocs** [comment]
I think that we can handle updates for this issue via #73118
