### ISSUE TITLE
[Doc] Document the list and order of ILM phases, actions and names

### ISSUE THREAD

**Issue by toby-sutor** [elastic/elasticsearch#73301]
There was a very good initiative to document ILM here https://github.com/elastic/elasticsearch/issues/53894 and here https://github.com/elastic/elasticsearch/pull/56560.

What still remains unclear is an entire list and possible order of the ILM `action` and `name` properties.
Sometimes ILM gets stuck and it is manually required to provide the correct next `phase`, `action` and `name` for the `next_step` but although it is required, there is no exhaustive list of the possible options and their order (ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-move-to-step.html). The `phase` is usually the only obvious value while the `action` and `name` are not transparent.

For example: `"action": "set_priority"` or `"action": "force_merge"` are valid values but they are not documented.
For Searchable Snapshots we have something like     
````
"action": "searchable_snapshot",
"name": "branch-check-prerequisites"
````

Another common example, if an index is stuck in the `Hot` phase and is required to be manually moved to the `warm` phase the following query is required (but unfortunately also not documented):
````
POST _ilm/move/<index-name>
{
  "current_step": { 
    "phase": "hot",
    "action": "complete",
    "name": "complete"
  },
  "next_step": { 
    "phase": "warm",
    "action": "set_priority",
    "name": "set_priority"
  }
}
````
It would be great to have this added somewhere neat https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-move-to-step.html#ilm-move-to-step-request-body so it remains in context.

**Comment by dakrone** [comment]
We purposely do not want to document these internal `name` parameters, because they are subject to changes between minor releases, and should not be relied upon (there are many branching execution checks within ILM's steps). Instead, we should implement https://github.com/elastic/elasticsearch/issues/58128 so that these internals are not necessary for the move-to-step API to be used.

**Comment by jrodewig** [comment]
I'm going to close this issue as we don't intend to document the `name` parameters.

With https://github.com/elastic/elasticsearch/pull/74021, we now document the order of ILM actions in each phase at https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-index-lifecycle.html#ilm-phase-actions.
