### ISSUE TITLE
Change the index creation_date

### ISSUE THREAD

**Issue by arsalan993** [elastic/elasticsearch#73302]
Though I tried several approaches I am unable to change the creation_date of the given index. 
When we have time-series indexes sometimes the index is created at the wrong period of date and time in such a scenario we are required to change the creation_date of the index from its setting for making sure the ILM policy works well. 

I am using ES 6.8 and if there is any alternative to change this value through the file system please let us know.

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
