### ISSUE TITLE
SQL: Better size default for nested documents 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#73305]
Currently the number of nested documents returned for a root document is limited to 100, same as the ES default. However there's currently no possibility for the user to modify this number, either through `LIMIT` or otherwise.
One option is to read this setting from the ES cluster first followed by the index definition (if it exists) - `index.max_inner_result_window` then fall back to the default value of 100.

This aligns with the ES settings without leaking into the SQL language.

**Comment by wchaparro** [comment]
Superceded by ES|QL
