### ISSUE TITLE
Allow KV ingest pipeline processor to set 'target_field' from a source field

### ISSUE THREAD

**Issue by pa-jberanek** [elastic/elasticsearch#73377]
When writing an ingest pipeline to handle KV log data, it would be good to be able to use the KV processor and set the 'target_field' option from a field in the source document. This would allow:

```
[
  {
    "_index": "whatever",
    "_source": {
      "message": "key1=value1 key2=value key3=value3",
      "key": "something"
    }
  }
]
```

to end up as:

something.key1: value1
something.key2: value2
something.key2: value3

I tried using "_source.key", "key" and "{{{key}}}" and none of those ended up using the "key" field from the source, even though the documentation generically states:

> Processors have read and write access to an incoming document’s source fields. To access a field key in a processor, use its field name.

I ended up having to define the processor something like:

```
{
      "kv": {
        "field": "log_fields",
        "field_split": " ",
        "value_split": "=",
        "target_field": "something",
        "if": "ctx.key == \"something\""
      }
}
```

**Comment by danhermann** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/73758
