### ISSUE TITLE
Failure to start elasticsearch7.12.0 on aarch64

### ISSUE THREAD

**Issue by crumbjp** [elastic/elasticsearch#73381]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.13.0, Build: default/deb/5ca8591c6fcdb1260ce95b08a8e023559635c6f3/2021-05-19T22:22:26.081971330Z, JVM: 16

**Plugins installed**: []
No plugins

**JVM version** (`java -version`):
```
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```
`/usr/share/elasticsearch/jdk/bin/java` in elasticsearch-7.13.0-arm64.deb

**OS version** (`uname -a` if on a Unix-like system):
Linux cf6dd9ef1df6 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Ubuntu 18.04 aarch64

**Description of the problem including expected versus actual behavior**:
Exec faild with bellows:
```
Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/elasticsearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 70341, exit value: 1
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:107)
        at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 70341, exit value: 1
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
        ... 6 more
```

My work around.
```
diff /usr/share/elasticsearch/bin/elasticsearch.original /usr/share/elasticsearch/bin/elasticsearch
32c32
<   ES_TMPDIR=`"$JAVA" "$XSHARE" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.TempDirectory`
---
>   ES_TMPDIR=`"$JAVA" "-Djdk.lang.Process.launchMechanism=vfork" "$XSHARE" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.TempDirectory`
55c55
< ES_JAVA_OPTS=`export ES_TMPDIR; "$JAVA" "$XSHARE" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.JvmOptionsParser "$ES_PATH_CONF" "$ES_HOME/plugins"`
---
> ES_JAVA_OPTS=`export ES_TMPDIR; "$JAVA" "-Djdk.lang.Process.launchMechanism=vfork" "$XSHARE" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.JvmOptionsParser "$ES_PATH_CONF" "$ES_HOME/plugins"`
60a61
>     "-Djdk.lang.Process.launchMechanism=vfork" \
73a75
>     "-Djdk.lang.Process.launchMechanism=vfork" \
```

It seems like, jdk's bug on aarch64.

**Steps to reproduce**:
```
dpkg -i elasticsearch-7.13.0-arm64.deb
/etc/init.d/elasticsearch start
```

**Provide logs (if relevant)**:
No logs due to before start process.

**Comment by droberts195** [comment]
What are the permissions on `/usr/share/elasticsearch/jdk/lib/jspawnhelper` in your installation?  That file needs to be executable.  I have seen "Failed to exec spawn helper" when it isn't for some reason.

Also, how did you install Elasticsearch?  E.g. `.rpm`, `.deb` or `.tar.gz` bundle?

And finally, if you just try running `jspawnhelper` directly at the command prompt, do you get an error.  For example, I get this, which is expected:

```
$ ./jspawnhelper 
This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application
```

But if you get some other error like it cannot find a certain OS library or wrong architecture or something then that may suggest what is wrong.

By switching to the `vfork` mechanism you are taking `jspawnhelper` out of the equation, which is why that fixes the problem, but the better fix for the long term is to get `jspawnhelper` working.

**Comment by crumbjp** [comment]
OS and other environments is written above. 

Only 2 commands to reproduce this.
```
dpkg -i elasticsearch-7.13.0-arm64.deb
/etc/init.d/elasticsearch start
```

**Comment by droberts195** [comment]
I don't see the same problem as you:

```
ubuntu@ip-10-0-0-227:~$ sudo dpkg -i elasticsearch-7.13.0-arm64.deb
Selecting previously unselected package elasticsearch.
(Reading database ... 116031 files and directories currently installed.)
Preparing to unpack elasticsearch-7.13.0-arm64.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (7.13.0) ...
Setting up elasticsearch (7.13.0) ...
Created elasticsearch keystore in /etc/elasticsearch/elasticsearch.keystore
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for ureadahead (0.100.0-19.1) ...

ubuntu@ip-10-0-0-227:~$ sudo /etc/init.d/elasticsearch start
[ ok ] Starting elasticsearch (via systemctl): elasticsearch.service.

ubuntu@ip-10-0-0-227:~$ curl localhost:9200
{
  "name" : "ip-10-0-0-227",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "m9_FRC2mQMuBjtQidSMFXA",
  "version" : {
    "number" : "7.13.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "5ca8591c6fcdb1260ce95b08a8e023559635c6f3",
    "build_date" : "2021-05-19T22:22:26.081971330Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

ubuntu@ip-10-0-0-227:~$ ps -ef | grep controller
elastic+ 32319 32083  0 12:51 ?        00:00:00 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-aarch64/bin/controller
ubuntu   32426  1998  0 12:54 pts/0    00:00:00 grep --color=auto controller

ubuntu@ip-10-0-0-227:/usr/share/elasticsearch/jdk/lib$ ./jspawnhelper 
This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application
```

If you want further help please answer these questions:

1. What are the permissions on `/usr/share/elasticsearch/jdk/lib/jspawnhelper` in your installation?
2. What error do you get if you try running `jspawnhelper` directly at the command prompt?

**Comment by droberts195** [comment]
Also, does a kernel of `4.19.121-linuxkit` imply that you are running Ubuntu 18.04 in a Docker container running on a Mac?  If so I think that was highly relevant information that you omitted from the initial problem report.

If you are running on a Mac, is it one of the new Apple silicon M1 Macs?  Which version of Docker are you running?

**Comment by droberts195** [comment]
The problem here isn't as simple as "Elasticsearch never works on linux-aarch64".  To progress this further we need more information about the environment, like whether Docker was involved, the host OS, and if Docker wasn't involved why was the kernel linuxkit?

I'll close this for now.  I am happy to reopen and take another look if more details about the environment are provided.
