### ISSUE TITLE
Rename Elasticsearch "migrate" tool

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#73415]
Today, Elasticsearch has a cmd utility called `elasticsearch-migrate` to be used to migrate users from file realm to native realm. 

In addition, I found a few other migrate-related concept that existed in Elasticsearch: (there might be more)
- **Data tier migration**: [API for migrating indices, and ILM policies to use node roles for allocation routing](https://github.com/elastic/elasticsearch/issues/73154)
- **Multiple data path migration**: [Document migration path off multiple data paths](https://github.com/elastic/elasticsearch/issues/71871)
- **Rollup migration**: [Enable users to migrate v1 rollup indices to Rollup v2](https://github.com/elastic/elasticsearch/issues/63570)
- **Template migration**: [Document guidance on migrating legacy index templates to composable index templates and component templates](https://github.com/elastic/elasticsearch/issues/72182)
- **Watcher to Kibana Alerts migration**: [Provide migration path for monitoring alerting from Watcher to Kibana alerting](https://github.com/elastic/elasticsearch/issues/50032)
- **Version migration**: [Elasticsearch Migration Guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes.html)

Thought that the word "migrate API" or "migrate tool" should be avoid when possible, and explicitly talk/think about naming convention so users would know exactly what migrate the tool/API is for.

**Comment by tvernum** [comment]
The migrate tool is already deprecated, and will not exist in 8.0
Closing with no additional action.
