### ISSUE TITLE
Geo-bounding box query does not support camelCase variations

### ISSUE THREAD

**Issue by Pyppe** [elastic/elasticsearch#73417]
**Discuss**: https://discuss.elastic.co/t/geo-bounding-box-query-does-not-support-topleft-bottomleft/273792

**Elasticsearch version** (`bin/elasticsearch --version`): `7.12.1`

**Plugins installed**: `[]`

**JVM version** (`java -version`):
```
/usr/share/elasticsearch/jdk/bin/java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
```Linux es-dev-node0 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

**Description of the problem including expected versus actual behavior**:

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#_vertices) states that:
> More over the names `topLeft` , `bottomRight` , `topRight` and `bottomLeft` are supported

However, using `topLeft` & `bottomRight` causes an error:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "failed to parse [geo_bounding_box] query. [failed to parse bounding box. unexpected field [topLeft]]"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[48:19] [bool] failed to parse field [filter]",
    "caused_by": {
      "type": "parse_exception",
      "reason": "failed to parse [geo_bounding_box] query. [failed to parse bounding box. unexpected field [topLeft]]"
    }
  },
  "status": 400
}
```

**Example query**:

```json
{
  "size": 1,
  "query": {
    "geo_bounding_box": {
      "coordinates": {
        "topLeft": {
          "lat": 75.76654624435699,
          "lon": -168.25100089690216
        },
        "bottomRight": {
          "lat": -34.773502906183325,
          "lon": 179
        }
      }
    }
  }
}
```

**Comment by nik9000** [comment]
I believe the docs are out of date. We've mostly removed support for all the camelCase variations in ES years ago.
