### ISSUE TITLE
SQL: Use TopMetrics instead of TopHits to improve performance

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#73430]
With `TopMetrics` aggregations in place, certain `FIRST/LAST` queries (i.e.:
binary, flattened, ip, keyword, or text fields cannot be used as the sort field, 
scripting - therefore scalars are not supported, etc.), could be 
translated to the underlying query DSL by using `TopMetrics` instead of `TopHits`
which would improve performance.

**Comment by nik9000** [comment]
`top_metrics` doesn't support sorting on `ip` and `keywords` because no one asked for it, but I expect it *could* support that. Its a little tricky, but possible.

**Comment by wchaparro** [comment]
Superceded by ES|QL
