### ISSUE TITLE
Using 'order' by subaggregation gives different results depending on the 'size' parameter of the parent aggregation

### ISSUE THREAD

**Issue by marlaaragao** [elastic/elasticsearch#73506]
Good Evening.

I stumbled in a problem when trying to order my buckets by AVG. Based on my query I know for a fact that there are two docs corresponding to a certain NestedField1.property1 value. The values of the ValueField1 on these documents are respectively:

doc1: **26470.62**
doc2: **4299614.7**

Then, the SUM is: **4326085.32**
and the AVG is: **2163042.66**

Ok.

I have the following aggs section:

```
"aggs": 
{
	"NameAgg": {
		"terms": {
			"field": "NestedField1.property1",
			"size": 1000,
			"order": {
				"ValueAgg>StatsAgg.avg": "desc"
			}
		},
		"aggs": {
			"ValueAgg": {
				"reverse_nested": {},
				"aggs": {
					"StatsAgg": {
						"stats": {
							"field": "ValueField1"
						}
					}
				}
			}
		}
	}
}
```

When I run the query it gives me the following result:

![image](https://user-images.githubusercontent.com/7109504/119890334-15bbab00-bf0e-11eb-8481-50acf6b35104.png)

It's not considering the two docs, only the one with a higher value.

However, if I increase the 'size' on the NameAgg terms from 1000 to 60000, it gives me the correct values:

![image](https://user-images.githubusercontent.com/7109504/119890610-6df2ad00-bf0e-11eb-9a11-6731835adbc0.png)

Is that a bug? If not, is there a way of getting the correct order but with no need of such high size? I tried with several values, but only got it working properly with 60k. The total hits are: 1,432,749 (if that info is important at all).

Thanks in advance!

**Comment by nik9000** [comment]
Check out the shard_size setting in the docs. If that works this is working as designed. But we need to make the docs for why trying to do this doesn't work well more prominent.

**Comment by marlaaragao** [comment]
Hello! I don't think I got it. 

I ran the query:

`GET _cat/shards`

The results are as follow:

```
processos                      2  r STARTED  51157434   13.1gb 172.31.68.138 es-node-2
processos                      2  p STARTED  51157434   12.8gb 172.31.12.142 es-node-1
processos                      4  r STARTED  51288853     13gb 172.31.68.138 es-node-2
processos                      4  p STARTED  51288853   13.7gb 172.31.12.142 es-node-1
processos                      1  r STARTED  51279236   13.5gb 172.31.31.31  es-node-3
processos                      1  p STARTED  51279236   13.7gb 172.31.12.142 es-node-1
processos                      3  r STARTED  51127506   13.1gb 172.31.31.31  es-node-3
processos                      3  p STARTED  51127506     13gb 172.31.68.138 es-node-2
processos                      0  r STARTED  51340761   14.6gb 172.31.31.31  es-node-3
processos                      0  p STARTED  51340761   13.8gb 172.31.68.138 es-node-2
```

But I don't know what to do with this information. Can you help me? Thanks!

**Comment by nik9000** [comment]
> But I don't know what to do with this information. Can you help me? Thanks!

I meant these docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_shard_size_3

Sorry I wasn't clear and linking. Mobile and all that.

I'm reasonably sure this is just the way that terms works and its just shard_size doing its things so I'm going to close this. But if you bump shard_size way up and still get strange results please reopen it.
