### ISSUE TITLE
cannot be changed from type [integer] to [long]

### ISSUE THREAD

**Issue by yhb001** [elastic/elasticsearch#73511]
I use kibana to operate es.There are two commands and behind occurs that error!
1.
PUT yhb
{
  "mappings": {
    "properties": {
      "name":{
        "type": "text"
      },
      "age":{
        "type": "integer"
      },
      "birth":{
        "type": "date"
      }
    }
  }
}
2.
PUT yhb/user/1
{
  "name":"叶",
  "age":12,
  "birth":"1997-09-10"
}

Finnaly:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "mapper [age] cannot be changed from type [integer] to [long]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "mapper [age] cannot be changed from type [integer] to [long]"
  },
  "status" : 400
}

**Comment by cbuescher** [comment]
Hi @yhb001, Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please include your ES version when you are asking this question there. Many thanks.
