### ISSUE TITLE
Supported options on FieldMappers are inconsistent

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#7352]
There are inconsistencies in which options are supported in the different field types.  For example, the geo_shape type does not support the 'common' options such as `store`, `index`, `index_name` etc.

There are other inconsistencies in the root types which @brwe has found (specifically regarding the _all field).  We need to go through each type and determine:
* The options which are not supported but should be (and add them)
* The options which are not supported and should not be supported (and document them)
* the options which are supported which shouldn't be - because they don't make any sense (and remove them and document)

**Comment by clintongormley** [comment]
The meta-fields have been locked down so that the configuration they expose is minimal.  Closing
