### ISSUE TITLE
uri_parts cannot break some URLs 

### ISSUE THREAD

**Issue by Danouchka** [elastic/elasticsearch#73529]
**Customer**: *(Retail shop in france) cloud subscription*

**Kibana version:*7.12.0*

**Elasticsearch version:*7.12.0*

**Server OS version:*NA*

**Browser version:*NA*

**Browser OS version:*NA*

**Original install method (e.g. download page, yum, from source, etc.):*Elastic Cloud*

**Describe the bug:**
The URL in that message below cannot be parsed by  uri_parts processor 
`May 19 17:59:05 server.lan tech[logd]: 10.10.1.1 - XXXXXX [19/05/2021 15:59:05] "GET https://c.amazon-adsystem.com/e/dtb/bid?src=3863&amp;u=https%3A%2F%2Fwww.vinted.fr%2Fvetements%3Fsize_id%5B%5D%3D4%26size_id%5B%5D%3D1255%26size_id%5B%5D%3D1256%26size_id%5B%5D%3D60%26catalog%5B%5D%3D4%26brand_id%5B%5D%3D4313%26status%5B%5D%3D6%26status%5B%5D%3D1&amp;pr=https%3A%2F%2Fwww.vinted.fr%2Ffemmes%2Fmidi%2F1121651312-vestido-satinado-estampado-nastygal&amp;pid=VvlUAMPMdYf2w&amp;cb=0&amp;ws=1920x937&amp;v=7.64.00&amp;t=2000&amp;slots=%5B%7B%22sd%22%3A%220%22%2C%22s%22%3A%5B%22728x90%22%2C%22970x250%22%2C%22970x90%22%5D%2C%22sn%22% HTTP/1.1" 200 - - 18 Advertising`

We get the following error from the ingest pipeline 

`unable to parse URI [https://c.amazon-adsystem.com/e/dtb/bid?src=3863&u=https%3A%2F%2Fwww.vinted.fr%2Fvetements%3Fsize_id%5B%5D%3D4%26size_id%5B%5D%3D1255%26size_id%5B%5D%3D1256%26size_id%5B%5D%3D60%26catalog%5B%5D%3D4%26brand_id%5B%5D%3D4313%26status%5B%5D%3D6%26status%5B%5D%3D1&pr=https%3A%2F%2Fwww.vinted.fr%2Ffemmes%2Fmidi%2F1121651312-vestido-satinado-estampado-nastygal&pid=VvlUAMPMdYf2w&cb=0&ws=1920x937&v=7.64.00&t=2000&slots=%5B%7B%22sd%22%3A%220%22%2C%22s%22%3A%5B%22728x90%22%2C%22970x250%22%2C%22970x90%22%5D%2C%22sn%22%]`

**Steps to reproduce:**
Ingest pipeline used
`PUT _ingest/pipeline/pipeline_tech
{
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{SYSLOGTIMESTAMP:log.timestamp} %{SYSLOGHOST:host.hostname} %{PROG:log.programm}(\\[%{DATA:log.logger}\\])?: %{IPORHOST:source.ip} - (-|%{DATA:user.id}) \\[%{DATESTAMPEU:@timestamp}\\] \"%{WORD:http.request.method} %{DATA:url.original} HTTP/%{NUMBER:http.version}\" %{NUMBER:http.response.status_code:int}"
        ],
        "pattern_definitions": {
          "DATESTAMPEU": "%{DATE_EU}[- ]%{TIME}"
        },
        "ignore_missing": true
      }
    },
    {
      "date": {
        "field": "@timestamp",
        "formats": [
          "dd/MM/yyyy HH:mm:ss"
        ],
        "timezone": "Europe/Paris"
      }
    },
    {
      "geoip": {
        "field": "source.ip",
        "target_field": "source.geo",
        "ignore_missing": true
      }
    },
    {
      "set": {
        "field": "host.name",
        "value": "{{host.hostname}}",
        "if": "ctx.host.hostname!=null"
      }
    },
    {
      "set": {
        "field": "event.ingested",
        "value": "{{_ingest.timestamp}}"
      }
    },
    {
      "uri_parts": {
        "field": "url.original"
      }
    }
  ],
  "on_failure": [
    {
      "append": {
        "field": "error.message",
        "value": [
          "{{ _ingest.on_failure_message }}"
        ]
      }
    }
  ]
}
`
**Any additional context:**

**Comment by danhermann** [comment]
@Danouchka, this was fixed in https://github.com/elastic/elasticsearch/pull/71559 and released in 7.12.1.

**Comment by Danouchka** [comment]
@danhermann  Many thanks :-)
