### ISSUE TITLE
I get sockettimeout when java client is connected to Elasticsearch (not related to idle connection)

### ISSUE THREAD

**Issue by sepidehnaghdi** [elastic/elasticsearch#73542]
hello,
sometimes when I am working with Elasticsearch and sending some query to it, suddenly in the middle of searching and getting response, I get Sockettimeout exception. I know it is not related to idle connection because I send multiple request and I got response from previous query. Could anyone tell me what is the reason?
It seems, it's not related to timeout because according to below link, if search query timeout, I get response with timeout field equals to true
Thank you

**Comment by fcofdez** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
