### ISSUE TITLE
SAML complete logout API has a camel case request parameter 

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#73543]
As discussed in https://github.com/elastic/elasticsearch/pull/72867/files#r629011079, the SAML complete logout API has a camel case request parameter, `queryString`. This is an anomaly because the rest of APIs use only snake case for request parameters. 

This request parameter, `queryString`, should be deprecated and replaced with its snake case equivalent, `query_string`.

**Comment by ywangd** [comment]
@tvernum I noticed the same `queryString` parameter (camel case) is also used for [RestSamlInvalidateSessionAction](https://github.com/elastic/elasticsearch/blob/7.13/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/saml/RestSamlInvalidateSessionAction.java#L41). Do you think it should be deprecated and replaced with `query_string` as well? If so, I can raise a PR to deprecate both of them.

**Comment by tvernum** [comment]
I guess we should. It's wrong, so we ought to fix it.
