### ISSUE TITLE
Combined_fields query almost 3 times slower than multi_match cross_fields query

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#73574]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.0

**Plugins installed**: [analysis-icu]

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): macOS Big Sur

**Description of the problem including expected versus actual behavior**:

Being eager to test the new combined_fields query as a replacement for the multi_match cross_fields query I have been using for the past few years, I performed some basic testing using the a (quite complex) query and switching the query type.

To my disappointment, the new query type takes almost 3 times longer to execute for the exact same query (apart from the query type):

combined_fields query - between 500 and 800 ms
multi_match cross_fields query - between 190 and 300ms

Since I didn't notice any performance-related comments/notes on the relevant github issues/prs/commits, could somebody please clarify if this performance decrease is to be expected when using the combined_fields query?

**Comment by nemphys** [comment]
After some more testing, I just realised that it is the aggregations, not the main query that is taking longer to execute.

In my test query (which is a script score query containing a boolean "should" query with 6 combined_fields queries for the different field analyzers), I am also running 5 aggregations (3 terms, 1 stats and 1 nested).

If I omit the aggregations altogether and compare the execution time, the combined_fields query takes 7-10ms, whereas the multi_match cross_fields query takes 9-11ms (which actually makes the combined_fields query marginally faster).

@jtibshirani any insights?

**Comment by jtibshirani** [comment]
@nemphys great that you are testing out `combined_fields`! If I understand correctly, you no longer see evidence of a performance difference between `combined_fields` and `multi_match`? Even if that's true, would you be able to paste your query (or a simplified version) in case we spot something interesting to look into?

**Comment by nemphys** [comment]
@jtibshirani indeed, the performance difference went away, but only after I set the "execution_hint" parameter to "map" for all terms aggregations in the query (should I be worried that I am doing something wrong regarding global ordinals?). If I don't do that, the difference is there (please note that, as stated above, running just the query with no aggregations has similar execution times between the 2 query types).

My query (multi_match mode) is as follows (though I don't know if it will help much without the actual data):

GET /index_name/_search
{
  "from": 0, 
  "size": 30,
  "query": {
    "script_score": {
      "query": {
        "bool": {
          "should": [
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "language",
                "fields": [
                  "title^4",
                  "short_description",
                  "brand^3",
                  "master_category",
                  "categories^2",
                  "free_shipping"
                ]
              }
            },
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "std",
                "fields": [
                  "title.std^4",
                  "short_description.std",
                  "brand.std^3",
                  "master_category.std",
                  "categories.std^2",
                  "free_shipping.std"
                ]
              }
            },
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "keyword",
                "fields": [
                  "id^5",
                  "product_code^5",
                  "partnumber^5"
                ]
              }
            },
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "ngram",
                "fields": [
                  "id.ngram^5",
                  "product_code.ngram^5",
                  "partnumber.ngram^5"
                ]
              }
            },
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "prefix",
                "fields": [
                  "title.prefix^4",
                  "short_description.prefix",
                  "brand.prefix^3",
                  "master_category.prefix",
                  "categories.prefix^2",
                  "free_shipping.prefix"
                ]
              }
            },
            {
              "multi_match": {
                "type": "cross_fields",
                "tie_breaker": 0.1,
                "query": "iphone",
                "operator": "AND",
                "_name": "suffix",
                "fields": [
                  "title.suffix^4"
                ]
              }
            },
            {
              "match": {
                "_all_fields": {
                  "query": "iphone",
                  "operator": "AND",
                  "fuzziness": "AUTO",
                  "max_expansions": "2",
                  "boost": "0.5",
                  "_name": "fuzzy"
                }
              }
            }
          ]
        }
      },
      "script": {
        "source": """_score  * (doc["popularity"].size() > 0 ? (((params.popularity_value_normalized.multiply.normalized1.normalizedMax - params.popularity_value_normalized.multiply.normalized1.normalizedMin) * (doc["popularity"].value - params.popularity_value_normalized.multiply.normalized1.actualMin) / (params.popularity_value_normalized.multiply.normalized1.actualMax - params.popularity_value_normalized.multiply.normalized1.actualMin)) + params.popularity_value_normalized.multiply.normalized1.normalizedMin) * params.popularity_value_normalized.multiply.normalized1.constant : 1)""",
        "params": {
          "popularity_value_normalized": {
            "multiply": {
              "normalized1": {
                "normalizedMin": 1,
                "normalizedMax": 2,
                "actualMin": 0,
                "actualMax": 45,
                "constant": 1.5
              }
            }
          }
        }
      }
    }
  },
  "highlight": {},
  "suggest": {},
  "aggs": {
    "auto_min_price": {
      "meta": {
        "type": "slider"
      },
      "stats": {
        "field": "auto_min_price"
      }
    },
    "master_category": {
      "meta": {
        "type": "values"
      },
      "terms": {
        "field": "master_category.base",
        "min_doc_count": 1,
        "order": {
          "_key": "asc"
        }
      }
    },
    "brand": {
      "meta": {
        "type": "values"
      },
      "terms": {
        "field": "brand.base",
        "min_doc_count": 1,
        "order": {
          "_key": "asc"
        }
      }
    },
    "attributes": {
      "meta": {
        "type": "attribute_values"
      },
      "nested": {
        "path": "attributes"
      },
      "aggs": {
        "attribute": {
          "terms": {
            "field": "attributes.key",
            "min_doc_count": 1,
            "order": {
              "_key": "asc"
            }
          },
          "aggs": {
            "value": {
              "terms": {
                "field": "attributes.value",
                "min_doc_count": 1,
                "order": {
                  "_key": "asc"
                }
              }
            }
          }
        }
      }
    },
    "facet_filters": {
      "meta": {
        "type": "attribute_values_filter",
        "target": "attributes"
      },
      "terms": {
        "field": "facet_filters",
        "min_doc_count": 1
      }
    }
  }
  "sort": [
    {
      "_score": "desc"
    }
  ]
}

For the combined_fields mode, I just replace "multi_match" with "combined_fields" and remove the "type" and "tie_breaker" parameters.

**Comment by jtibshirani** [comment]
Got it, it sounds like there could be another factors at play. This sort of debugging work is often better suited for our [discuss forums](https://discuss.elastic.co/) -- you could post there and tag me if you are still seeing surprising differences. If we find there's a bug, we'll loop back to GitHub to address it.
