### ISSUE TITLE
whatever you updated ,  seqNo still is -2 and primaryTerm is 0

### ISSUE THREAD

**Issue by siblesos** [elastic/elasticsearch#73603]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

**Plugins installed**: standard

**JVM version** (`java -version`): jdk11

**OS version** (`uname -a` if on a Unix-like system): windows 10

**Steps to reproduce**:

my code: 
 1. i do a search, the data is moviesEntity(id=101991, title=H-Man, The, genre=[Horror, Mystery, Sci-Fi, Thriller], year=0, seqNo=-2, primaryTerm=0) 
 2. i follow guide update this data and set right seqNo=-2, primaryTerm=0,and data do update successfully.
 2. i search data by id again, but seqNo still is -2 and primaryTerm is 0;
 3.

mycode and console pic
![image](https://user-images.githubusercontent.com/30852556/120334535-498a3c80-c323-11eb-9789-1dc603798fa6.png)
![image](https://user-images.githubusercontent.com/30852556/120334388-2c556e00-c323-11eb-8d39-6624959e32c7.png)

when update , the response said seqNo=58107 primaryTerm=6
![image](https://user-images.githubusercontent.com/30852556/120334778-82c2ac80-c323-11eb-8059-d69b45c71ea6.png)

but when i search again , eqNo still is -2 and primaryTerm is 0; why ??
![image](https://user-images.githubusercontent.com/30852556/120336211-b520d980-c324-11eb-99a0-0ceec20d850c.png)

**Comment by dnhatn** [comment]
@siblesos You need to set the parameter `seq_no_primary_term` of a search request to true to retrieve the sequence number and primary term of its search hits. Please refer https://www.elastic.co/guide/en/elasticsearch/reference/7.13/optimistic-concurrency-control.html and https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-search.html#request-body-search-seq-no-primary-term
