### ISSUE TITLE
buildsrc not importing eclipse configuration

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73615]
I updated my eclipse config and it made hundreds of eclipse build files. I imagine we're not applying the eclipse configuration customizations to buildsrc any more.

**Comment by breskeby** [comment]
Given that we did some major refactoring in build logic organisation in elasticsearch I'll look into this

**Comment by breskeby** [comment]
Calling this fixed as https://github.com/elastic/elasticsearch/pull/73699 is merged to master and 7.x
