### ISSUE TITLE
Switch to using UBI for as basis of standard Docker images

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#73623]
The UBI images are now [available on DockerHub](https://hub.docker.com/u/redhat). This, in coupled with the fact that CentOS 8 is soon going to stop getting updates means we can _and should_ switch to using it for the foundation of our Docker images. Since we _already_ build a UBI image this also means we can simply ditch the CentOS version entirely and remove that variant from our build process altogether.

**Comment by mark-vieira** [comment]
There are two main questions I still have on this:

1. Can we use UBI as our base given it's status as a ["verified publisher image"](https://www.redhat.com/en/about/press-releases/red-hat-brings-red-hat-universal-base-image-docker-hub), whatever that means
2. Can we stop publishing our current UBI-based variant since the default image will be based on UBI

**Comment by pugnascotia** [comment]
Quoting https://github.com/docker-library/official-images#repeatability 

> No official images can be derived from, or depend on, non-official images with the following notable exceptions

The UBI images on Docker Hub are not official images at this time, and Docker could take issue with our using it in the default image build. Until the status of the UBI images changes, I don't see how we can make progress here.

**Comment by mark-vieira** [comment]
Bummer. Ok, I've communicated this to the stack team. I suppose we can simply close this issue for now and reopen when things change.
