### ISSUE TITLE
SQL: Changing the precision threshold of count query in Canvas

### ISSUE THREAD

**Issue by AmyMMCollins** [elastic/elasticsearch#73695]
Hi, 

I work on an Analytics team and a lot of our esql queries involve counting distinct/unique values and displaying them on different Canvas dashboards. We really need for the numbers to be as accurate as possible. Therefore, I need a way to tell the SQL endpoint to change the precision threshold.

Please see below for an example:
![image (1)](https://user-images.githubusercontent.com/26348862/120540675-dba44a80-c3e0-11eb-94d6-7197d7d1bd99.png)

Let me know if you need any more information.

Thanks,
Amy

**Comment by jelledrm** [comment]
I also need a way to tell the SQL endpoint to change the precision threshold.

**Comment by wchaparro** [comment]
Superceded by ES|QL
