### ISSUE TITLE
Snapshots cannot be restored on another cluster

### ISSUE THREAD

**Issue by akhasano** [elastic/elasticsearch#73730]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.1

**Plugins installed**: [n/a]

**JVM version** (`java -version`): 

D:\test_elk\7.13.1-2\jdk\bin>java.exe --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):

Windows 10 20H2 OS BUILD 19042.985
and
Linux elksrv 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Create repo on 1st cluster, make snapshot - create the same repo on 2nd cluster, and copy snapshot.
Expectation: i could see snapshot/snapshots and can restore.
Actual behaviour is - snapshots cannot be discovered.

**Steps to reproduce**:

Create two clusters - just unzip files for windows (it is easiest way for checking):
d:\test_elk\7.13.1-1
and 
d:\test_elk\7.13.1-2

elasticsearch.yml for 1st cluster:
cluster.name: es-7131-1
node.name: node-7131-1
network.host: 0.0.0.0
discovery.type: single-node
path.repo: ["d:\\test_elk\\backup-7131-1"]

elasticsearch.yml for 2st cluster:
cluster.name: es-7131-2
node.name: node-7131-2
network.host: 0.0.0.0
discovery.type: single-node
path.repo: ["d:\\test_elk\\backup-7131-2"]

Start first cluster and create test index:
curl -X POST "http://192.168.104.100:9200/_bulk?pretty" -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "index" : { "_index" : "test", "_id" : "2" } }
{ "field1" : "value2" }
{ "index" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
'

Create repo:
curl -X PUT "http://192.168.104.100:9200/_snapshot/repo?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "fs",
  "settings": {
    "location": "repo"
  }
}
'

Make snapshot:

curl -X PUT "http://192.168.104.100:9200/_snapshot/repo/test_snap?wait_for_completion=true&pretty" -H 'Content-Type: application/json' -d'
{
  "indices": "test",
  "ignore_unavailable": true,
  "include_global_state": false
}
'

Stop first cluster. Start second cluster.

Create repo:
curl -X PUT "http://192.168.104.100:9200/_snapshot/repo?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "fs",
  "settings": {
    "location": "repo"
  }
}
'
Copy content folder  D:\test_elk\backup-7131-1\repo to  D:\test_elk\backup-7131-2\repo

curl -X GET "http://192.168.104.100:9200/_snapshot/repo/_all"

Result is:
{"snapshots":[]}                                                                                                                                                                                 ✔

Works for 7.10.1 as designed.

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

Please see steps to reproduce.
 1.
 2.
 3.

Please read above and check the video: https://youtu.be/t4luuiVMQfg

**Provide logs (if relevant)**:

n/a

**Comment by akhasano** [comment]
Update: it worked before 7.12 
7.11.2 does work, 7.12 - doesn't.

**Comment by DaveCTurner** [comment]
According to your repro instructions you are changing the contents of the repository _after_ registering it, which is dangerous in any version. It might appear to have worked in earlier versions but it technically comes with no guarantees and may have silently lost some of your data. Since this is more of a user question than a bug report I am closing this, but encourage you to open a thread on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) if you need further assistance.

**Comment by DaveCTurner** [comment]
I didn't find this information spelled out explicitly in the docs, so I opened #73740 to address that.

**Comment by akhasano** [comment]
> According to your repro instructions you are changing the contents of the repository _after_ registering it, which is dangerous in any version. It might appear to have worked in earlier versions but it technically comes with no guarantees and may have silently lost some of your data. Since this is more of a user question than a bug report I am closing this, but encourage you to open a thread on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) if you need further assistance.

Hello Dave,

Possible you are right,  according to elasticsearch documents, snapshot doesn't depend on clustername etc. and it is recommended method to clone data on new cluster as i wish. But i can't now. 
Let's imagine situation, you have a nightly snapshots from some cluster, for example you have cluster from one node, and something happens with that (liquid from top floor, high voltage etc.) - but you have snapshots backed in cloud, you deploy a new one, put downloaded snapshots to repo of new deployed cluster - and new cluster doesn't see your snapshots. You can't restore your data! That's bug from my point of view, because before 7.12 it worked properly...

**Comment by DaveCTurner** [comment]
I once again encourage you to open a thread on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) if you need further assistance.

**Comment by akhasano** [comment]
Ok i see what did you mean. Thanks.
