### ISSUE TITLE
Persistent task timeout for PyTorchModelIT.testEvaluate

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#73769]
**Build scan**:
https://gradle-enterprise.elastic.co/s/3fhraorgrz462
**Repro line**:
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate" -Dtests.seed=7A6300C6BF1BC1F5 -Dtests.locale=da-DK -Dtests.timezone=Indian/Comoro -Druntime.java=11
**Reproduces locally?**:
No, its a timeout so happens periodicaly
**Applicable branches**:
Master
**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!f,params:(query:master,type:phrase),type:phrase,value:master),query:(match:(build.branch:(query:master,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:PyTorchModelIT),sort:!(process.time-start,desc))
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.PyTorchModelIT > testEvaluate FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:34482], URI [/_ml/trained_models/simple_model_to_evaluate/deployment/_start], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Timed out when waiting for persistent task after 20s"}],"type":"illegal_state_exception","reason":"Timed out when waiting for persistent task after 20s"},"status":500}
        at __randomizedtesting.SeedInfo.seed([7A6300C6BF1BC1F5:50CE5F1A6354D1AE]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.startDeployment(PyTorchModelIT.java:172)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate(PyTorchModelIT.java:91)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate" -Dtests.seed=7A6300C6BF1BC1F5 -Dtests.locale=da-DK -Dtests.timezone=Indian/Comoro -Druntime.java=11
```

Either the test needs more time for waiting for the persistent task, or there is some internal race condition where the listener is not alerted on a deployment start

**Comment by davidkyle** [comment]
The root cause is that the task config could not be found which means the model was not deployed. The test needs to refresh the index after putting the various bits of config

```
[2021-06-04T12:40:04,567][ERROR][o.e.x.m.i.d.DeploymentManager] [javaRestTest-1] [simple_model_to_evaluate] failing model deployment task with error: 
org.elasticsearch.ResourceNotFoundException: Could not find task config for model [simple_model_to_evaluate]
```

But, that error should have been returned on the API instead of timing out the start deployment request. We do have a problem where task failure is not passed back to the listener

**Comment by davidkyle** [comment]
The above error message is misleading the real cause is a missing library: elastic/ml-cpp#1933

**Comment by davidkyle** [comment]
Reopening. The fix depends on https://github.com/elastic/ml-cpp/pull/1934 which has not worked its way through the build system yet
