### ISSUE TITLE
[Monitoring] Add pattern for .monitoring-es-6-* in .monitoring-es index template

### ISSUE THREAD

**Issue by igoristic** [elastic/elasticsearch#73793]
Based on our [support matrix](https://www.elastic.co/support/matrix#matrix_compatibility), and [Stack Monitoring Kibana code](https://github.com/elastic/kibana/blob/355c949463cec5b2169081a809722d55db0e5bf3/x-pack/plugins/monitoring/common/constants.ts#L126-L131) we do support stack monitoring for both 6.x and 7.x major versions. However, right now if we try to monitor a mix of 7.x and 6.x nodes in a single monitoring cluster we get a mapping error (and only see 7.x nodes), because `GET _template/.monitoring-es` is missing the `.monitoring-es-6-*` index pattern and only has `.monitoring-es-7-*`.

Currently a workaround is to either add the missing pattern to the current `.monitoring-es` template, or create a new `.monitoring-es-6` template with the `.monitoring-es-6-*` pattern and use the exact template copied from a 6.x monitoring cluster (since there might be slightly different fields between the two major versions)

Also, anther thing to consider is that the next major version 8.0 should also support the 7.x index pattern

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
