### ISSUE TITLE
Snapshot and Restore Policies - Ability to get indices using Math Expressions

### ISSUE THREAD

**Issue by kevn-gonz** [elastic/elasticsearch#73795]
In order to create Snapshots, we can go to Management > Elasticsearch > Snapshot and Restore > Policies.

This is a great tool, but I noticed something: In the section where we select the indices to backup, it allows 
1. Select ALL the indices
2. Select specific indices manually
3. Use an index pattern to select indices.

Although this is a good approach, an index pattern is not good enough... As you might now, a lot of users create indices using this structure _"index-name-**date**"_ and what happen is that if I want to backup ONLY today's indices I can't do it. The same happen if I want to backup ONLY this month, or this week indices...

The name of the indices are usually like _"myIndex-2021.05.31"_ so a math expression such as <myIndex-{now/d}> will do the trick, in this case the Policy will not consider old indices that were already backed up in last day snapshot..

The real problem: If I have monthly indices (_myIndex-2021.**01** | myIndex-2021.**02** | ..._) that are 500 GB big, when we are in December, **using an index pattern** such as "myIndex-2021*" it will create a 6TB (more or less) snapshot because the index pattern will get January, February, March.... indices as well..

Here is a screenshot that shows what I am saying. Today (2021.06.04) I only want to backup the corresponding index, I don't need to backup yesterday's, or the day before yesterday indices... because the Policy ran yesterday as well, so yesterday's index was already backed up..

![image](https://user-images.githubusercontent.com/21992295/120866377-0ad7ca80-c54d-11eb-85ad-a76f7b6e258d.png)

For the above case, a Math Expression would be extremely beneficial, as I would be able to select the index I need by the date on it's name.

Finally, it doesn't make sense to create Policies using index patters like "myIndex-2021-06*" because the next month (July=07), I'll have to modify the policy to match the new month..

Thanks!

**Comment by marcohevi** [comment]
I strongly agree. The automated snapshots are somewhat helpful, but plain wildcards are a bit wasteful for archive space.

**Comment by DaveCTurner** [comment]
> when we are in December, using an index pattern such as "myIndex-2021*" it will create a 6TB (more or less) snapshot because the index pattern will get January, February, March.... indices as well..

If you have 6TB of data in your cluster then you'll need 6TB of repository storage for the first snapshot, but snapshots include automatic deduplication so subsequent snapshots will need a lot less. It's certainly not the case that each snapshot requires 6TB of additional space as you seem to be suggesting. If the contents of those older indices aren't changing then they'll add almost nothing to later snapshots (kBs or less). Typically you're expected to snapshot all indices since the extra space needed is so small, and since it makes restoring your cluster from a snapshot to be so much simpler if you only need to restore the one snapshot.

Can you explain more clearly why the built-in deduplication process doesn't do what you need already?

**Comment by kevn-gonz** [comment]
Hi @DaveCTurner thank you for your response!
You're right, the deduplication thing does a really good job! I read [here](https://www.elastic.co/blog/found-elasticsearch-snapshot-and-restore) that it was going to add "redundant" data so I it was confusing, I might misunderstood it. 

Anyways, having a single snapshot for all the indices we have is not good, we have been doing that for quite some time and recovering data is kind of a pain (not because of ELK, mostly because of moving data from server to server, it takes several hours, possibly days), because of the size of the snapshots.

That's why we decided to create separate snapshots according to the indices names (linked to the department's name and creation date), so if we need to recover data for one single department, we will recover the specific indices instead of recovering all departments data, and obviously it is easier and faster to manage and recover snapshots.

Once again, thanks for your response, even though the "math expression" might not be implemented, the deduplication feature works fine and could help.
