### ISSUE TITLE
How to open the kibana ui in local browser if the kibana is configured on remote server

### ISSUE THREAD

**Issue by kshitijD38** [elastic/elasticsearch#73814]
I am unable to open the kibana ui 
I have already changed server.host to the server ip in kibana.yml
What should i do?

**Comment by cbuescher** [comment]
Hi @kshitijD38! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Make sure to use the forum part dedicated to Kibana when asking your question there. Many thanks.
