### ISSUE TITLE
Is PIT(point in time) supported in JAVA API?

### ISSUE THREAD

**Issue by liusiyuxyfx** [elastic/elasticsearch#73827]
I want to use search_After with PIT in my JAVA Program, but I can't find find any documentation about it, is there any description?

**Comment by javanna** [comment]
hi @liusiyuxyfx , support for PIT has been recently added to the high level rest client, see #https://github.com/elastic/elasticsearch/pull/72167 . I am also having trouble finding its documentation, although it was added as part of the same PR I linked, I will follow-up on that.
