### ISSUE TITLE
Missing docs for HTTP client stats

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#73830]
In https://github.com/elastic/elasticsearch/pull/64561 we augmented the response to `GET _nodes/stats/http` with information on the individual clients currently connected to Elasticsearch. The [node stats API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) does not currently describe the new client stats:

<img width="732" alt="screenshot of docs showing missing fields" src="https://user-images.githubusercontent.com/5058284/121013814-3b0fab00-c791-11eb-8492-88c1af559fc7.png">

**Comment by danhermann** [comment]
I missed a backport on this one. Will be resolved in https://github.com/elastic/elasticsearch/pull/73835.

**Comment by DaveCTurner** [comment]
Thanks Dan!
