### ISSUE TITLE
Context Suggester: Need better error message if you omit category when indexing.

### ISSUE THREAD

**Issue by bly2k** [elastic/elasticsearch#7388]
Example below (I am omitting the color field category when I index). Error message I get back is:

{"error":"ElasticsearchIllegalArgumentException[one or more prefixes needed]","status":400}

Would be nice to instead say something like "color category must be specified/is missing."

curl -XPUT localhost:9200/test_1 -d '
{
 "settings": {
   "index": {
     "number_of_replicas": "0",
     "number_of_shards": "1"
   }
 },
 "mappings": {
   "doc": {
     "properties": {
       "context_suggest": {
         "type": "completion",
         "context": {
           "color": {
             "type": "category",
             "path": "color",
             "default": []
           }
         }
       }
     }
   }
 }
}'

curl -XPUT localhost:9200/test_1/doc/1 -d '
{
  "context_suggest": {
    "input": ["test"],
    "output": "test"
  }
}'

**Comment by clintongormley** [comment]
The new completion suggester https://github.com/elastic/elasticsearch/pull/11740 now allows zero contexts.  Closing
