### ISSUE TITLE
贵网站一直访问失败 各种503，500 ，502请检查

### ISSUE THREAD

**Issue by SanQi2211** [elastic/elasticsearch#73890]
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
I believe you're asking whether we are aware that the https://elastic.co/ website was unavailable recently. Yes we were, the site's CDN provider, Fastly, experienced some problems but appears to be on the road to recovery now. See https://status.fastly.com/incidents/vpk0ssybt3bj for more details.

For future reference this Github repository is really only for Elasticsearch development, not the website, so this isn't the right place to report website bugs. I would recommend asking questions like this on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) in future.
