### ISSUE TITLE
Cluster/Health and Cluster/Stats disagree on status

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#7390]
If you force your cluster to remain in a Red state on startup, the cluster health and cluster stats disagree on the status.

E.g.  Set `recover_after_nodes: 10` in a one-node cluster.  Cluster never recovers because the number of nodes is not satisfied.  `/_cluster/health` shows Red, `/_cluster/stats` shows Green

```bash
GET _cluster/health

{
   "cluster_name": "elasticsearch_macbookair_zach",
   "status": "red",
   "timed_out": false,
   "number_of_nodes": 1,
   "number_of_data_nodes": 1,
   "active_primary_shards": 0,
   "active_shards": 0,
   "relocating_shards": 0,
   "initializing_shards": 0,
   "unassigned_shards": 0
}
```

```bash
GET _cluster/stats

{
   "timestamp": 1408649084720,
   "cluster_name": "elasticsearch_macbookair_zach",
   "status": "green",
   "indices": {
      "count": 0,
      "shards": {},
      "docs": {
         "count": 0,
         "deleted": 0
      },
   ...

}
```

**Comment by hczhang-** [comment]
@polyfractal I noticed the issue and reproduced it, what do you think the possible reason is? Is it the right way to find out where to judge the cluster status colour and see how it works?

**Comment by clintongormley** [comment]
This looks like a bug in cluster stats.
