### ISSUE TITLE
Consider upgrading to T-Digest 3.3

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#73928]
The new version of t-digest promises improved [accuracy under most circumstances](https://tdunning.blogspot.com/2021/06/whats-new-in-t-digest-new-version-32.html). We should consider upgrading.

**Comment by kkrik-es** [comment]
Duplicate of #95903

**Comment by martijnvg** [comment]
Tdigest has been forked (#96086). This is no longer relevant.
