### ISSUE TITLE
How to modify elasticsearch setsp password and set a fixed password

### ISSUE THREAD

**Issue by dyhyao6** [elastic/elasticsearch#73933]
when i setup password ,i will input too many password .is there a way to set a fixed password ? i want to write a fixed password to the elasticsearch-setsp-password shell.

**Comment by cbuescher** [comment]
Hi @dyhyao6. Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
