### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet$Builder com.google.common.collect.ImmutableSet.builder()' 	at com.google.inject.internal.util.SourceProvider.<init>(SourceProvider.java:47) 	at com.google.inject.internal.util.SourceProvider.<init>(SourceProvider.java:41) 	at com.google.inject.internal.util.SourceProvider.<clinit>(SourceProvider.java:38) 	at com.google.inject.internal.Errors.<init>(Errors.java:111) 	at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:65) 	at com.google.inject.Guice.createInjector(Guice.java:87) 	at com.google.inject.Guice.createInjector(Guice.java:69) 	at com.google.inject.Guice.createInjector(Guice.java:59)

### ISSUE THREAD

**Issue by vijay8484** [elastic/elasticsearch#73945]
Getting this issue while migrating to java 11

=> System.out.println(System.getProperty("java.class.path"));
=> System.out.println(com.google.common.collect.ImmutableSet.class.getResource("ImmutableSet.class"));

Projects\DevCommunitySession\target\classes;C:\Users\vp27570\.m2\repository\org\postgresql\postgresql\42.2.8\postgresql-42.2.8.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\jersey-proxy-runtime\0.0.91\jersey-proxy-runtime-0.0.91.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\core-model\0.0.91\core-model-0.0.91.jar;C:\Users\vp27570\.m2\repository\com\typesafe\config\1.4.1\config-1.4.1.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-cloudfront\1.11.989\aws-java-sdk-cloudfront-1.11.989.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-core\1.11.989\aws-java-sdk-core-1.11.989.jar;C:\Users\vp27570\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\vp27570\.m2\repository\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\vp27570\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\vp27570\.m2\repository\software\amazon\ion\ion-java\1.0.2\ion-java-1.0.2.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.6.7\jackson-dataformat-cbor-2.6.7.jar;C:\Users\vp27570\.m2\repository\joda-time\joda-time\2.8.1\joda-time-2.8.1.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\jmespath-java\1.11.989\jmespath-java-1.11.989.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\configuration-manager\0.0.91\configuration-manager-0.0.91.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\s3-url-stream-handler\0.0.91\s3-url-stream-handler-0.0.91.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-s3\1.11.989\aws-java-sdk-s3-1.11.989.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-kms\1.11.989\aws-java-sdk-kms-1.11.989.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-sts\1.11.989\aws-java-sdk-sts-1.11.989.jar;C:\Users\vp27570\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\vp27570\.m2\repository\org\springframework\spring-jdbc\5.3.7\spring-jdbc-5.3.7.jar;C:\Users\vp27570\.m2\repository\org\springframework\spring-beans\5.3.7\spring-beans-5.3.7.jar;C:\Users\vp27570\.m2\repository\org\springframework\spring-core\5.3.7\spring-core-5.3.7.jar;C:\Users\vp27570\.m2\repository\org\springframework\spring-jcl\5.3.7\spring-jcl-5.3.7.jar;C:\Users\vp27570\.m2\repository\org\springframework\spring-tx\5.3.7\spring-tx-5.3.7.jar;C:\Users\vp27570\.m2\repository\commons-io\commons-io\2.8.0\commons-io-2.8.0.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\serverless\aws-serverless-java-container-jersey\1.3.2\aws-serverless-java-container-jersey-1.3.2.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\serverless\aws-serverless-java-container-core\1.3.2\aws-serverless-java-container-core-1.3.2.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\module\jackson-module-afterburner\2.9.9\jackson-module-afterburner-2.9.9.jar;C:\Users\vp27570\.m2\repository\commons-fileupload\commons-fileupload\1.4\commons-fileupload-1.4.jar;C:\Users\vp27570\.m2\repository\org\apache\httpcomponents\httpmime\4.5.6\httpmime-4.5.6.jar;C:\Users\vp27570\.m2\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar;C:\Users\vp27570\.m2\repository\org\slf4j\slf4j-api\1.8.0-beta2\slf4j-api-1.8.0-beta2.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-lambda-java-log4j2\1.2.0\aws-lambda-java-log4j2-1.2.0.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-lambda-java-core\1.2.1\aws-lambda-java-core-1.2.1.jar;C:\Users\vp27570\.m2\repository\org\apache\logging\log4j\log4j-core\2.14.1\log4j-core-2.14.1.jar;C:\Users\vp27570\.m2\repository\org\apache\logging\log4j\log4j-api\2.14.1\log4j-api-2.14.1.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\media\jersey-media-json-jackson\2.27\jersey-media-json-jackson-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\core\jersey-common\2.27\jersey-common-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\osgi-resource-locator\1.0.1\osgi-resource-locator-1.0.1.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\ext\jersey-entity-filtering\2.27\jersey-entity-filtering-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\media\jersey-media-multipart\2.27\jersey-media-multipart-2.27.jar;C:\Users\vp27570\.m2\repository\org\jvnet\mimepull\mimepull\1.9.6\mimepull-1.9.6.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\guice-bridge\2.5.0-b60\guice-bridge-2.5.0-b60.jar;C:\Users\vp27570\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\inject\jersey-hk2\2.27\jersey-hk2-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\hk2-locator\2.5.0-b42\hk2-locator-2.5.0-b42.jar;C:\Users\vp27570\.m2\repository\com\google\inject\guice\5.0.1\guice-5.0.1.jar;C:\Users\vp27570\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\vp27570\.m2\repository\com\google\guava\guava\30.1-jre\guava-30.1-jre.jar;C:\Users\vp27570\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\vp27570\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\vp27570\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\vp27570\.m2\repository\org\checkerframework\checker-qual\3.5.0\checker-qual-3.5.0.jar;C:\Users\vp27570\.m2\repository\com\google\errorprone\error_prone_annotations\2.3.4\error_prone_annotations-2.3.4.jar;C:\Users\vp27570\.m2\repository\com\google\j2objc\j2objc-annotations\1.3\j2objc-annotations-1.3.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\hk2-api\2.5.0-b42\hk2-api-2.5.0-b42.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\hk2-utils\2.5.0-b42\hk2-utils-2.5.0-b42.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\external\aopalliance-repackaged\2.5.0-b42\aopalliance-repackaged-2.5.0-b42.jar;C:\Users\vp27570\.m2\repository\com\nimbusds\nimbus-jose-jwt\9.7\nimbus-jose-jwt-9.7.jar;C:\Users\vp27570\.m2\repository\com\github\stephenc\jcip\jcip-annotations\1.0-1\jcip-annotations-1.0-1.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\jersey-web-client\0.0.91\jersey-web-client-0.0.91.jar;C:\Users\vp27570\.m2\repository\org\jfarcand\wcs\1.5\wcs-1.5.jar;C:\Users\vp27570\.m2\repository\com\ning\async-http-client\1.9.28\async-http-client-1.9.28.jar;C:\Users\vp27570\.m2\repository\org\scala-lang\scala-compiler\2.11.7\scala-compiler-2.11.7.jar;C:\Users\vp27570\.m2\repository\org\scala-lang\scala-library\2.11.7\scala-library-2.11.7.jar;C:\Users\vp27570\.m2\repository\org\scala-lang\scala-reflect\2.11.7\scala-reflect-2.11.7.jar;C:\Users\vp27570\.m2\repository\org\scala-lang\modules\scala-xml_2.11\1.0.4\scala-xml_2.11-1.0.4.jar;C:\Users\vp27570\.m2\repository\org\scala-lang\modules\scala-parser-combinators_2.11\1.0.4\scala-parser-combinators_2.11-1.0.4.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\core\jersey-client\2.27\jersey-client-2.27.jar;C:\Users\vp27570\.m2\repository\jakarta\ws\rs\jakarta.ws.rs-api\2.1.2\jakarta.ws.rs-api-2.1.2.jar;C:\Users\vp27570\.m2\repository\com\beust\jcommander\1.81\jcommander-1.81.jar;C:\Users\vp27570\.m2\repository\com\amazonaws\aws-java-sdk-lambda\1.11.989\aws-java-sdk-lambda-1.11.989.jar;C:\Users\vp27570\.m2\repository\io\netty\netty-all\5.0.0.Alpha2\netty-all-5.0.0.Alpha2.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-jaxrs2\2.1.7\swagger-jaxrs2-2.1.7.jar;C:\Users\vp27570\.m2\repository\io\github\classgraph\classgraph\4.8.95\classgraph-4.8.95.jar;C:\Users\vp27570\.m2\repository\org\javassist\javassist\3.25.0-GA\javassist-3.25.0-GA.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-models\2.1.7\swagger-models-2.1.7.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-annotations\2.1.7\swagger-annotations-2.1.7.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-integration\2.1.7\swagger-integration-2.1.7.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-core\2.1.7\swagger-core-2.1.7.jar;C:\Users\vp27570\.m2\repository\jakarta\xml\bind\jakarta.xml.bind-api\2.3.2\jakarta.xml.bind-api-2.3.2.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.12.1\jackson-dataformat-yaml-2.12.1.jar;C:\Users\vp27570\.m2\repository\org\yaml\snakeyaml\1.27\snakeyaml-1.27.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.12.1\jackson-datatype-jsr310-2.12.1.jar;C:\Users\vp27570\.m2\repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-json-provider\2.12.1\jackson-jaxrs-json-provider-2.12.1.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-base\2.12.1\jackson-jaxrs-base-2.12.1.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.12.1\jackson-module-jaxb-annotations-2.12.1.jar;C:\Users\vp27570\.m2\repository\jakarta\activation\jakarta.activation-api\1.2.1\jakarta.activation-api-1.2.1.jar;C:\Users\vp27570\.m2\repository\io\swagger\core\v3\swagger-jaxrs2-servlet-initializer-v2\2.1.7\swagger-jaxrs2-servlet-initializer-v2-2.1.7.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.12.1\jackson-databind-2.12.1.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.12.1\jackson-annotations-2.12.1.jar;C:\Users\vp27570\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.12.1\jackson-core-2.12.1.jar;C:\Users\vp27570\.m2\repository\com\zsassociates\aws\jetty-local-runtime\0.0.91\jetty-local-runtime-0.0.91.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-server\9.4.39.v20210325\jetty-server-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-http\9.4.39.v20210325\jetty-http-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-util\9.4.39.v20210325\jetty-util-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-io\9.4.39.v20210325\jetty-io-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-servlet\9.4.39.v20210325\jetty-servlet-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-security\9.4.39.v20210325\jetty-security-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-util-ajax\9.4.39.v20210325\jetty-util-ajax-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\core\jersey-server\2.27\jersey-server-2.27.jar;C:\Users\vp27570\.m2\repository\javax\ws\rs\javax.ws.rs-api\2.1\javax.ws.rs-api-2.1.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\media\jersey-media-jaxb\2.27\jersey-media-jaxb-2.27.jar;C:\Users\vp27570\.m2\repository\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;C:\Users\vp27570\.m2\repository\org\glassfish\hk2\external\javax.inject\2.5.0-b42\javax.inject-2.5.0-b42.jar;C:\Users\vp27570\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\containers\jersey-container-jetty-servlet\2.27\jersey-container-jetty-servlet-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\containers\jersey-container-servlet\2.27\jersey-container-servlet-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\containers\jersey-container-servlet-core\2.27\jersey-container-servlet-core-2.27.jar;C:\Users\vp27570\.m2\repository\org\glassfish\jersey\containers\jersey-container-jetty-http\2.27\jersey-container-jetty-http-2.27.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-continuation\9.4.7.v20170914\jetty-continuation-9.4.7.v20170914.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-webapp\9.4.7.v20170914\jetty-webapp-9.4.7.v20170914.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-xml\9.4.7.v20170914\jetty-xml-9.4.7.v20170914.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\websocket\websocket-api\9.4.39.v20210325\websocket-api-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\websocket\websocket-server\9.4.39.v20210325\websocket-server-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\websocket\websocket-common\9.4.39.v20210325\websocket-common-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\websocket\websocket-client\9.4.39.v20210325\websocket-client-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\jetty-client\9.4.39.v20210325\jetty-client-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\org\eclipse\jetty\websocket\websocket-servlet\9.4.39.v20210325\websocket-servlet-9.4.39.v20210325.jar;C:\Users\vp27570\.m2\repository\com\google\code\gson\gson\2.8.6\gson-2.8.6.jar

jar:file:/C:/Users/vp27570/.m2/repository/com/google/guava/guava/30.1-jre/guava-30.1-jre.jar!/com/google/common/collect/ImmutableSet.class

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
