### ISSUE TITLE
Async search support for cross cluster search minimize round trip optimization 

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#73971]
[Async search](https://www.elastic.co/guide/en/elasticsearch/reference/current/async-search.html) does not currently support minimize roundtrip optimization when used with cross cluster search.  This is a documented limitation.  

With Kibana now using async searches by default, this could cause performance issues in some environments that use cross cluster search with slower/inconsistent network latency.  One workaround is to enable the deprecated advanced setting `courier:batchSearches` in Kibana which will switch Kibana back to using the old way of querying Elasticsearch via `msearch` (but this option is slated for removal in 8.0).

**Comment by javanna** [comment]
@quux00 can this be closed?

**Comment by quux00** [comment]
I was planning on waiting to hear back from the Kibana team on whether they will make it their default or whether we need to do that on the backend before closing this. But I'll go ahead and close it and we can reopen if need be.

**Comment by quux00** [comment]
Kibana has changed to use ccs_minimize_roundtrips=true now. PR: https://github.com/elastic/kibana/pull/159848
