### ISSUE TITLE
Excluding match_field from geolocation enrich policy

### ISSUE THREAD

**Issue by RoyzLevy** [elastic/elasticsearch#74001]
Feature raised from discussion: [https://discuss.elastic.co/t/geo-polygon-query-inside-ingest-pipeline/274886/2](url)

When creating a geolocation policy in order to enrich the data in an existing/new index, like described in [https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-match-enrich-policy-type.html](url) , there is no way to **exclude** the match_field to be added to the index documents.

The suggested feature will be a field in the geo_match which will enable a way to exclude the match_field from being added to the documents. This is needed because in some cases the shapes for the geo-match are very big (a lot of coordinates) and the process of pipelining with the policy will result in too big documents.
As a result the user will need another pipeline which's job will be to remove the match_field from documents, but I think it will be preferred to add this to the existing geomatch policy creation.

**Comment by martijnvg** [comment]
I think this is something we should do. Including the match field in the input document has no real benefit, so we shouldn't do that. More recently #74217 was opened to address this as well, but is more broad, in the sense that no enrich policy should include the match field. For this reason I will close this issue and use the mentioned issue to track this enhancement/bug.
