### ISSUE TITLE
[Docs] Forward port 73577 to 7.x and master

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#74035]
PR #73577 (change to JSON example in SetProcessor docs) was opened and merged directly to the 7.13 branch, but the change needs to also be made on 7.x and master.

**Comment by jrodewig** [comment]
Ported this to 7.x with https://github.com/elastic/elasticsearch/pull/74077.

This was already ported to master with https://github.com/elastic/elasticsearch/pull/43073.
