### ISSUE TITLE
docker: allow specification of settings on the commandline without dots

### ISSUE THREAD

**Issue by t-8ch** [elastic/elasticsearch#74036]
It would be nice to be able to specify settings with environmentvariable not containing dots (`.`) when using the docker container.

Background:
I am using elasticsearch in Microsofts "Azure Container Instances". On this platform, trying to use environment variables containing dots fails with an error:

    Code="InvalidContainerEnvironmentVariable"
    Message="The environment variable name in container 'elasticsearch' of container group 'group' is invalid. A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName')."

Concretely I want to pass `discovey.type=single-node`.

I also tried using the environmentvariable `ES_JAVA_OPTS=-Des.discovery.type=single-node` but it seems this particular setting is not picked up from properties.

For Kibana for example the follow statement is done [in the docs](https://www.elastic.co/guide/en/kibana/current/docker.html):

    For compatibility with container orchestration systems, these environment variables are written in all capitals, with underscores as word separators.

**Comment by pugnascotia** [comment]
@t-8ch thanks for raising this issue. You can workaround this, but it's a little cumbersome. We'll look into improving the situation.

```shell
docker run -it --rm elasticsearch:test bin/elasticsearch -Ediscovery.type=single-node
```

**Comment by t-8ch** [comment]
Thanks for the pointer. This is also what I resorted to do.

Maybe some unified handling between elastic products could be implemented?

For example for the `apm` container I am also facing issues not being able pass any configurations via environment variables.
(I should probably also open a ticket there)

**Comment by pugnascotia** [comment]
Addressed in #74327.

**Comment by t-8ch** [comment]
@pugnascotia Thanks!

**Comment by pugnascotia** [comment]
@t-8ch The implementation in #74327 had issues in environments that injected their own `ES_` environment variables, so I've changed the prefix to `ES_SETTING_` in #76192. It's more verbose, but hopefully won't cause any collisions.

**Comment by t-8ch** [comment]
@pugnascotia Thanks for letting me know! And sorry for the issues this has caused...

**Comment by pugnascotia** [comment]
No problem 😀
