### ISSUE TITLE
Getting all open contexts (i.e: pit) for reconciliation if some were not deleted

### ISSUE THREAD

**Issue by qdumouli** [elastic/elasticsearch#74038]
Hi, 

There is a feature to close all scroll contexts with the DELETE /_search/scroll/_all 

I would like to know if it would be possible to get a similar endpoint for Point in time. 

If not, could it be possible to have an endpoint that returns ids of all open contexts (i.e pit_id) so that we could garbage collect ourselves. 

We have had many PIT's that have not been garbage collected and thus it impacts greatly our performance because the newly created pit_ids are around 10000 characters which give us a 414 request URI too long error on GET request.

**Comment by breskeby** [comment]
@qdumouli At the moment there's no api to close all PITs. Thanks for this enhancement request. It will be triaged by the according team

**Comment by jimczi** [comment]
> We have had many PIT's that have not been garbage collected and thus it impacts greatly our performance because the newly created pit_ids are around 10000 characters which give us a 414 request URI too long error on GET request.

The pit id cannot be used as a request parameter, it needs to be in the body so I am not sure I understand. Can you post an example ?
The timeout of the PIT is a mechanism to perform garbage collection automatically, are you changing the default timeout of 5 minutes ? Keeping this timeout low ensures that PIT are closed automatically when they are not used. Each request that targets a PIT extend the timeout for another 5 minutes.

**Comment by dnhatn** [comment]
No feedback
