### ISSUE TITLE
Add possible values for cluster setting validation

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#74041]
This seems like an honest mistake yet the error message is not very informative:
```
PUT _cluster/settings
{
  "indices.lifecycle.poll_interval":"1m"
}
```
with Validation error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: no settings to update;"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: no settings to update;"
  },
  "status" : 400
}
```
Most users would try to verify specific settings syntax like in this example via https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-settings.html

Since the documentation around specific settings will not include the entire API call like what was described on this page:
https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-settings.html

It would take users several attempts and hoops to jump through in order to land on the correct links. 
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

----
For those who are familiar with elasticsearch settings would immediately realise, this was missing either "transient" or "persistent" setting like (see https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html):
```
PUT _cluster/settings
{
  "transient": {
    "indices.lifecycle.poll_interval": "1m"
  }
}
```
Is it possible to have:
> "reason" : "Validation Failed: 1: no settings to update; Do you mean "transient" or "persistent" setting?"

**Comment by gwbrown** [comment]
We discussed this in the core/infra sync, and fully agree that this is very confusing and a poor experience. However, given that we're currently planning to remove transient cluster settings entirely (https://github.com/elastic/elasticsearch/issues/49540) as they are often confusing, we're planning to address this by changing the API to accept the original setting call and no longer requiring specifying `transient`/`persistent`.

As such, I'm going to close this issue in favor of https://github.com/elastic/elasticsearch/issues/49540.
