### ISSUE TITLE
Reduce memory usage of shard request cache keys

### ISSUE THREAD

**Issue by Bubbad** [elastic/elasticsearch#74061]
Hello!

At my company we have really large search queries, up to 100k terms. 

As the shard request cache uses the entire search json as the cache key, we really waste
a lot of memory on cache keys for our use-cases. 

It would be really nice if we could have something else as the cache key to optimize the utilization of the cache.

Considered either hashing the key inside elasticsearch or allowing the users to manually specify a cache key, similar to how 
you could do for filters in older versions of elasticsearch.

Not sure how to do a hashing inside ES in the best way, so created a small PR for adding the ability to specify a request cache key. What do you think?

**Comment by romseygeek** [comment]
Hi Bubbad, thanks for opening the PR!  I'd be interested to know if having the request cache store results for these very large queries is actually useful, as another option instead of having an external cache key would be to just disable the cache for requests above a certain size.  External keys make me a bit nervous as it would be very easy to re-use a key on different queries without realising it, in which case you could get incorrect results returned from the cache.  They are also tricky to integrate with security.

**Comment by Bubbad** [comment]
Hi Romseygeek!

Thanks for your reply!

So far we've been going with what you say, disabling that cache. Due to the complexity of these large searches our cluster has to spend a lot of CPU to calculate the results and the search times can take up to several minutes. It's quite common for the exact same search to be sent multiple times in a short time span (refreshing a dashboard). Small searches are already fast, so maybe the opposite would be even better; to only use the request cache for large queries? I haven't done any benchmarks here so just thinking out loud! 

Yes, having cache key collisions due to human errors is the risk with this approach. Do you think it would make more sense to hash the search json [here](https://github.com/elastic/elasticsearch/blob/c4741abf771b9d6ce8c52dba0337494c80bd4701/server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java#L399) and use that as cache key instead? Then I guess security shouldn't be affected?

**Comment by romseygeek** [comment]
We discussed this internally, and came up with a couple of options:
1) as you describe above, use a hashed version of the query as the cache key - we'd need to ensure that the function output space is sufficiently large that we won't run the risk of collisions
2) compress the request bytes before using them as a key - would guarantee no collisions but almost certainly won't save as much space as 1)

Would you be interested in implementing either of the above @Bubbad?

**Comment by Bubbad** [comment]
Thanks for your reply @romseygeek. Sure, I can definitely check it out! I'll close my current PR and create a new one shortly. I'll try out the first option.

**Comment by Bubbad** [comment]
Hi @romseygeek! I've created a new [PR](https://github.com/elastic/elasticsearch/pull/74877) now with the hashing option. I'm happy to hear your feedback of it!
