### ISSUE TITLE
_cat API in JSON format does not work with filter_path

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#74070]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.1

**Description of the problem including expected versus actual behavior**:

When using the `json` format of the _cat API, using the `filter_path` parameter does not work and excludes everything, ending up with an empty response, even though the filter matches.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Run ` curl 'localhost:9200/_cat/indices/.tasks?format=json'` and see this output for each index
```json
[
  {
    "health": "green",
    "status": "open",
    "index": ".tasks",
    "uuid": "fOgAYD3oS5-axMdNA70i5A",
    "pri": "1",
    "rep": "0",
    "docs.count": "2",
    "docs.deleted": "0",
    "store.size": "13.7kb",
    "pri.store.size": "13.7kb"
  }
]
```
 2. Run `curl -s 'localhost:9200/_cat/indices/.tasks?format=json&filter_path=**.health'` and see that nothing is returned even though there is a `health` field in the response.

**Comment by jrodewig** [comment]
I was able to get `filter_path` working with different reproduction steps.

1. Create `my-index`:

```
curl -X POST "localhost:9200/my-index/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
  "@timestamp": "2099-11-15T13:12:00"
}
'
```

2. Use cat indices to get info about `my-index`.

```
curl -X GET "localhost:9200/_cat/indices/my-index?format=json&pretty"
```

The API returns:

```
[
  {
    "health" : "yellow",
    "status" : "open",
    "index" : "my-index",
    "uuid" : "MRW5LboPRoKWYTazR0gNLQ",
    "pri" : "1",
    "rep" : "1",
    "docs.count" : "1",
    "docs.deleted" : "0",
    "store.size" : "3.1kb",
    "pri.store.size" : "3.1kb"
  }
]
```

3. Include `filter_path=health` query param:

```
 curl -X GET "localhost:9200/_cat/indices/my-index?format=json&pretty&filter_path=health"
```

The API returns:

```
[
  {
    "health" : "yellow"
  }
]
```

**Comment by jrodewig** [comment]
I'm going to go ahead and close this issue. Please feel free to reopen if I missed something.

**Comment by spinscale** [comment]
My bad. The version that works is `**health` in order as `**.health` would require the JSON object within an inner object. Thanks for testing and closing!
