### ISSUE TITLE
formalize definition of backwards compatibility

### ISSUE THREAD

**Issue by kevinkluge** [elastic/elasticsearch#7415]
We have made a commitment to preserve backwards compatibility across minor and maintenance releases.  I think everyone understands this to mean API level compatibility.  We should refine this with a document that describes treatment of other public aspects of the product.  Examples include command line names, config variable names, log file syntax, ... what exactly of these extra things is considered subject to backwards compatibility constraints?

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated since it was created, and I think is outside of the scope of the Docs team. Marking as closed. If we still need a better definition, then a new issue should be created with regards to Make It Minor.
