### ISSUE TITLE
Highlighting | Fragments | Order:Score ---  is it possible to get the score of every fragment?

### ISSUE THREAD

**Issue by edyas** [elastic/elasticsearch#74160]
When using Highlighting, fragments can be sorted by their respective score, which is a very useful feature.

But is there any way to get their individual score (which must be calculated for the sorting)?

The idea: skip any fragment whose score (i.e. relevance) is too low.

Thanks.

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
