### ISSUE TITLE
Prevent ES from writing to /tmp on startup

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#74162]
Elasticsearch is started using a bash script which by default can write files to /tmp directory. This is because <<< in bash is implemented using temporary files (creates /tmp/sh-thd.random string) https://itectec.com/ubuntu/ubuntu-whats-the-difference-between/
This can be reconfigured by changing TMP and TEMP environment variables.
or we should refactor the script to avoid using << or <<<

**Comment by randallwvr90** [comment]
I found this by searching the "good first issue" tag. 

It looks like Elasticsearch is started and the environment variables are set with these two scripts, is that right? 
* distribution/src/bin/elasticsearch
* distribution/src/bin/elasticsearch-env

Is elastisearch-env the correct place to set the TMP and TEMP environment variables?
What directory would be the right place for the temporary files to be created?

**Comment by qilingzhao** [comment]
Hi @pgomulka , i have commit a PR, please review it, thx.

**Comment by pavangole** [comment]
Is this issue is open ?

**Comment by rjernst** [comment]
Since the CLIs are now in Java, here strings are no longer used, thus this issue should be fixed.
