### ISSUE TITLE
Conditional token filter bug

### ISSUE THREAD

**Issue by mingyitianxia** [elastic/elasticsearch#74176]
In Conditional token filter

https://github.com/elastic/elasticsearch/blob/5baabff6670a8ed49297488ca8cac8ec12a2078d/docs/reference/analysis/tokenfilters/condition-tokenfilter.asciidoc

```
GET /_analyze
{
  "tokenizer": "standard",
  "filter": [
    {
      "type": "condition",
      "filter": [ "lowercase" ],
      "script": {
        "source": "token.getTerm().length() < 5"
      }
    }
  ],
  "text": "THE QUICK BROWN FOX"
}
```
when    "source": "token.getTerm().length() < 4", can not result correct result. 

the "type" should be revised to "predicate_token_filter".

The correct dsl as follows:

```
GET /_analyze
{
  "tokenizer": "standard",
  "filter": [
    {
      "type": "predicate_token_filter",
      "filter": [
        "lowercase"
      ],
      "script": {
        "source": "token.getTerm().length() < 5"
      }
    }
  ],
  "text": "THE QUICK BROWN FOX aaaaaaaa"
}
```

**Comment by nik9000** [comment]
@romseygeek could you have a look at this one? It looks like we run the tests for this so the docs should work. Is `predicate_token_filter` a new or old name for this?

**Comment by nik9000** [comment]
Sorry. I read a bit more. I believe the docs are correct. The `condition` filter will run the `lowercase` filter for tokens that match the condition. Short words in this case. The `predicate_token_filter` will remove tokens that do not match the filter entirely. @mingyitianxia do you have a suggestion for how to change the docs so they are more clear?

**Comment by mingyitianxia** [comment]
yes，you are right!   Sorry, my understanding is wrong.
Only those that meet the filter conditions will be converted, and those that do not meet the conditions will be retained and returned to the word segmentation results.

**Comment by nik9000** [comment]
Thanks for filing it anyway! If you find anything else let us know. Good
luck.
