### ISSUE TITLE
Should we make `_ignored` retrievable via `fields`?

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#74229]
We started adding metadata field like `_size` and `_doc_count` (#70575) or
the new `_tier` field (#71379) to the list of metadata retrievable via the `fields`API.
We might also want to add the `_ignored` field here, which currently doesn't support fetching via fields, but it might make
sense in light of issues like #74121 to add this.

**Comment by jtibshirani** [comment]
If a document contains any ignored fields, the search response always contains a section `"_ignored": [ "field1", "field2", ...]`. Would support for loading `_ignored` through `fields` bring additional benefit?

**Comment by jimczi** [comment]
I agree with Julie, the `_ignored` section that is returned in search hit is not optional. It is always there if the hit has ignored fields. We should make sure that this section covers every case (https://github.com/elastic/elasticsearch/issues/74228) but it's not part of the `fields` option. It's a feature of the search that guarantees that these fields are always visible in search responses.

**Comment by cbuescher** [comment]
Makes, sense, thanks for the quick feedback. I will close this issue then.
