### ISSUE TITLE
Tests using Mockito fail in IntelliJ

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#74232]
Tests are using Mockito currently fail when ran in IntelliJ IDEA (latest: 2021.1.2).

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4b85612c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:59)
	... 57 more
```

Workaround is to use JDK 15 instead of JDK 16.

**Comment by breskeby** [comment]
@ywelsch can you provide an example test that is failing? when running the test in IDEA, do you use the Gradle runner to invoke the test or the IDEA test runner?

**Comment by ywelsch** [comment]
One such test is `org.elasticsearch.xpack.sql.cli.ConnectionBuilderTests`.
Running the test with the IDEA test runner (the Gradle one is just impractical for development purposes).

**Comment by mark-vieira** [comment]
Yeah, I suspect the reason here here is IntelliJ isn't passing the necessary JVM arguments here like we do in our build. See: https://github.com/elastic/elasticsearch/blob/8cba213dfc070156f4ad727bb11521fcc36be43f/build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchTestBasePlugin.java#L96-L102

A fix here would be to add these same options to the default IntelliJ test runner configuration: https://github.com/elastic/elasticsearch/blob/f98b374cf6da6a657051a80bb6ff7cc4f05d50e6/build-tools-internal/src/main/groovy/elasticsearch.ide.gradle#L126

**Comment by ywelsch** [comment]
Is someone working on this? It breaks a basic developer setup for running tests.

**Comment by droberts195** [comment]
A temporary workaround for this is to go to Run -> Edit Configurations after a test fails and change that particular test or test suite to run with Java 15 instead of Java 16.  (I am not saying this should be the solution for this issue, just that it's a way for people to carry on working until a better solution is found.)

**Comment by ywelsch** [comment]
I have been using that approach - after a while it gets tiring making this configuration change again and again. I've configured the project level SDK now to JDK 15, and then explicitly configured the Gradle JVM to use JDK 16. This is certainly not how we want developers to set this up, though, so a fix should be prioritized.

**Comment by mark-vieira** [comment]
Strange that when running from the IDE it needs access to `java.lang` but not when run via Gradle. I'm still investigating but may just end up making the IDE permissions more lax until we resolve this permanently.

**Comment by mark-vieira** [comment]
This should be sorted out now. Keep in mind that you may need to delete the existing run configurations in IntelliJ for these tests for the IDE to pick up the new default JVM arguments.

**Comment by Rishi-web** [comment]
I am still facing the issue with this maven settings
```
<dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.9</version>
      <scope>test</scope>
    </dependency>

**Comment by Rishi-web** [comment]
> This should be sorted out now. Keep in mind that you may need to delete the existing run configurations in IntelliJ for these tests for the IDE to pick up the new default JVM arguments.

Can you please guide this, even after deleting `run configuration` still IntelliJ fails to run test cases.

**Comment by mark-vieira** [comment]
> @mark-vieira, I am still facing the issue with this maven settings while running in intelliJ IDE and JDK-17

I think the issue you are running into is unrelated to Elasticsearch. If you are having issues using Powermock on your own project I suggest you reach out to their support channels.

**Comment by Rishi-web** [comment]
Thanks @mark-vieira
