### ISSUE TITLE
Es7.x querystring can’t boost NOT query

### ISSUE THREAD

**Issue by laigood** [elastic/elasticsearch#74281]
I found that from es7.0,querystring query can't boost NOT query,like below code,the result score is 0,not 100 as expect.I alse check in es5.x and es6.x it work as expect.
`PUT test/_doc/1
{
  "test": "1"
}
GET test/_search
{
  "query": {
    "query_string": {
      "query": "(NOT _exists_:abc)^100"
    }
  }
}`
I finally found the problem,about this commit.
https://github.com/elastic/elasticsearch/commit/aeac6828699c12c0d54a8537af806b824c08ebff
it change BooleanClause.Occur.MUST to BooleanClause.Occur.FILTER in fixNegativeQueryIfNeeded method,that result in the score become 0

**Comment by markharwood** [comment]
Thanks for bringing this to our attention.

The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/query-dsl-bool-query.html) describe the scoring rationale for must_not clauses as follows:

>The clause (query) must not appear in the matching documents. Clauses are executed in filter context meaning that scoring is ignored and clauses are considered for caching. Because scoring is ignored, a score of 0 for all documents is returned.

With this score of zero your boost in `(NOT _exists_:abc)^100` is effectively 100 x 0 which equals zero.
The results are expected as per the docs, no?

Scoring nots is perhaps an odd use of boosting anyway - boosts are normally used to put space between results produced from different optional clauses but its utility in scoring a mandatory clause that all matches require is questionable.

Unless I've missed something important here this looks like something that doesn't require a fix and so will close if that's OK with you.

**Comment by laigood** [comment]
> Thanks for bringing this to our attention.
> 
> The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/query-dsl-bool-query.html) describe the scoring rationale for must_not clauses as follows:
> 
> > The clause (query) must not appear in the matching documents. Clauses are executed in filter context meaning that scoring is ignored and clauses are considered for caching. Because scoring is ignored, a score of 0 for all documents is returned.
> 
> With this score of zero your boost in `(NOT _exists_:abc)^100` is effectively 100 x 0 which equals zero.
> The results are expected as per the docs, no?
> 
> Scoring nots is perhaps an odd use of boosting anyway - boosts are normally used to put space between results produced from different optional clauses but its utility in scoring a mandatory clause that all matches require is questionable.
> 
> Unless I've missed something important here this looks like something that doesn't require a fix and so will close if that's OK with you.

OK.i‘m not notice about this doc before,so it seem like a bug in version below 7.x.For our use case,we use es as a recommend engine,and use boost score to sort,some condition include not query.
