### ISSUE TITLE
Cross Cluster Search 6.8.16 intermittent query failures against 7.10.2 remote 

### ISSUE THREAD

**Issue by jeffmontagna** [elastic/elasticsearch#74322]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Cross Cluster Search Cluster:
`Version: 6.8.16, Build: default/docker/1f62092/2021-05-21T19:27:57.985321Z, JVM: 15.0.1`

Remote Cluster:
`Version: 7.10.2, Build: default/docker/747e1cc71def077253878a59143c1f785afa92b9/2021-01-13T00:42:12.435326Z, JVM: 15.0.1`

**Plugins installed**: none

**JVM version** (`java -version`):
```
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
Cross Cluster Search Cluster:
`Linux 0ac13dac2194 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Remote Cluster:
`Linux 48248808f7b1 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
- Intermittent shard failures results when querying remote cluster version `7.10.2` and a cross cluster search version `6.8.16`.  
- Failure is always 1 or more shards with reason type `null_pointer_exception`
- The same shard or node does not always fail.  
- Running the same query with a `7.10.2` cross cluster search cluster never results in a shard failure. 
- Running the same query against with `6.8.16` cross cluster search cluster and a `7.9.2` remote cluster does not result in a shard failure.
- Tried different `7.10.2` clusters to rule out something unique to the test cluster, and got the same shard failures.
  
**Steps to reproduce**:
 1. Stand up `6.8.16` cross cluster search cluster 3 x master 2 x client nodes
 2. Stand up `7.10.2` remote cluster 3 x master 5 x data nodes
 3. Setup remote 
 ```
curl -sS -X PUT "es-xsearch-test2/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "cluster": {
      "remote": {
        "es_test3": {
          "skip_unavailable": "true",
          "seeds": [
            "elasticsearch-test3.test3:9300"
          ]
        }
      }
    }
  }
}
'
```

**Provide logs (if relevant)**:
- No relevant logs on client or master nodes in cross cluster search cluster
- Error from search: 
```bash
curl -sS "es-xsearch-test2/es_test3:test_index1/_search?pretty&q=date:>=2020-10-16" | jq  ._shards
{
  "total": 5,
  "successful": 4,
  "skipped": 0,
  "failed": 1,
  "failures": [
    {
      "shard": 0,
      "index": "es_test3:test_index1",
      "node": "xxxxxxxxx",
      "reason": {
        "type": "null_pointer_exception",
        "reason": null
      }
    }
  ]
}
```
Successful search:
```bash
curl -sS "es-xsearch-test2/es_test3:test_index1/_search?pretty&q=date:>=2020-10-16" | jq  ._shards
{
  "total": 5,
  "successful": 5,
  "skipped": 0,
  "failed": 0
}
```

**Comment by cbuescher** [comment]
Can you provide the search request body? 

> No relevant logs on client or master nodes in cross cluster search cluster

Is there any further evidence around the null pointer exception in the remote cluster log? Looking at the node that contains `es_test3:test_index1` might give us further hits. As it is, there's little to go by here so far.

**Comment by dnhatn** [comment]
Hi @jeffmontagna This is a known issue between 6.8 and 7.10 clusters and we have fixed it in https://github.com/elastic/elasticsearch/pull/70948. Can you upgrade the remote cluster to the latest 7.x?

**Comment by jeffmontagna** [comment]
@dnhatn Thanks for the response. That looks like the fix we need, but  I'm unable to upgrade the remote cluster to the latest 7.x.
