### ISSUE TITLE
`ReactiveStorageDeciderService` constructs a lot of `RoutingNodes`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#74325]
Well ok it constructs two of them:

https://github.com/elastic/elasticsearch/blob/095e49eaf3f8691424fe4de5b99a95736296bd78/x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java#L194

https://github.com/elastic/elasticsearch/blob/095e49eaf3f8691424fe4de5b99a95736296bd78/x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java#L211

That's still quite a lot, these things are expensive to construct:

https://github.com/elastic/elasticsearch/blob/095e49eaf3f8691424fe4de5b99a95736296bd78/server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java#L499-L504

I don't think we need these things to be mutable, so why not use `ClusterState#getRoutingNodes()` instead?

**Comment by henningandersen** [comment]
Thanks for raising this, David, this is a leftover from previous iterations where we did mutate the routing nodes.
