### ISSUE TITLE
Field Capabilities API returns no results with index with the Join field type

### ISSUE THREAD

**Issue by kylelyk** [elastic/elasticsearch#74335]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1

**Plugins installed**: []

**JVM version** (`java -version`): openjdk 11.0.4 2019-07-16 LTS

**OS version** (`uname -a` if on a Unix-like system): x86 mac, ARM linux

**Description of the problem including expected versus actual behavior**: 
In ES 7.9.2, the following queries would return expected results:
```
PUT test
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "parentChildJoin": {
        "relations": {
          "parent": "child"
        },
        "type": "join"
      }
    }
  }
}

GET test/_field_caps?fields=*
```

However, in ES 7.11.1, the Field capabilities API it is now returning:
```
{
  "indices" : [ ],
  "fields" : { }
}
```

As soon as I add a join field, it stops returning that index completely. Other indices without join fields are unaffected.

**Comment by cbuescher** [comment]
It looks like this is fixed by https://github.com/elastic/elasticsearch/pull/70143 on 7.11.3 and and later.
I just verified 7.12.0 and it doesn't show this problem any more. I suggest updating and will close this issue.

**Comment by cbuescher** [comment]
Looks like there was no 7.11.3 minor release, so 7.12 seems to be the earliest version that contains the fix.
