### ISSUE TITLE
cannot import name 'AsyncElasticsearch' from 'elasticsearch'

### ISSUE THREAD

**Issue by miss85246** [elastic/elasticsearch#74334]
hi there, I'm trying use asyncelasticsearch to do something . but I got an Error:

```python
ImportError: cannot import name 'AsyncElasticsearch' from 'elasticsearch' (E:\Codeing\Python\.virtualenvs\abc_test\lib\site-packages\elasticsearch\__init__.py)
```

Here is my code: 
![image](https://user-images.githubusercontent.com/42527535/122672283-68cb0a00-d1fd-11eb-8be9-c674fb5723d4.png)

The elasticsearch version is 7.13.1
The python version is 3.9.2
Plantform is win10 19043.1081

what should I do ?

**Comment by brightgreat** [comment]
@miss85246 您好，您的这个问题解决了吗？我遇到了和您一样的问题
