### ISSUE TITLE
Store min/max/sum/value_count for histogram fields

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elasticsearch#74359]
Currently, all metric aggregations iterate over all bins in histogram fields. Here's an example of the min aggregation:

https://github.com/elastic/elasticsearch/blob/68817d7ca29c264b3ea3f766737d81e2ebb4028c/x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/aggregations/metrics/HistoBackedMinAggregator.java#L75-L80

For histogram fields with lots of bins, a possible performance improvement would be to add another backing data structure, similar to aggregate_metric_double, that stores min/max/sum/value_count, so that min/max/avg/sum aggregations no longer have to iterate over all bins in the histogram.

**Comment by wchaparro** [comment]
Hey @dgieselaar we can consider this as a future optimization. Can you provide us with a little more clarification around why you need this performance improvement? We assume its just optimizations in general to improve performance, but we wanted to see if that was indeed the case or if you have a specific performance need in mind.

**Comment by dgieselaar** [comment]
@wchaparro yeah, it's performance. We are moving to histogram fields in APM, and previous research showed little query performance improvement due to the fact that it's mostly related to the amount of values that are being aggregated rather than the amount of documents. This should improve performance for dashboards that are not percentile based, which is most of them.

**Comment by axw** [comment]
Here's a concrete example of where storing `value_count` would be helpful: https://github.com/elastic/kibana/issues/114814#issuecomment-942882560

If it's an option to change how histograms are stored internally, then we could store cumulative histograms and we would get all of these for free:
 - `value_count`: last cumulative count
 - `sum`: last cumulative sum
 - `min`: first cumulative sum
 - `max`: last cumulative sum - second last cumulative sum

(Values are already required to be provided in ascending order, so not sure why we would need to iterate for min/max anyway?)

**Comment by jpountz** [comment]
My mental model of the `histogram` field is that is like a multi-valued numeric field that doesn't require repeating equal values. If we start adding min/max/sum/value_count metrics to `histogram`, I'd worry that we would blur the lines between `histogram` and `aggregate_metric_double`.

I would suggest doing the opposite and adding support for histograms to `aggregate_metric_double`, so that histograms would be a metric of these aggregate fields, just like the `min`, `max`, `sum` and `value_count`.

**Comment by csoulios** [comment]
@jpountz I agree with you and this is something we have already discussed with the team internally. We would rather implement histogram structures inside `aggregate_metric_double` fields.

However, I wanted to discuss more @axw 's idea about cumulative histogram. I think there are many performance benefits when using cumulative histograms and maybe we should consider providing an alternative implementation of the `histogram` or a `cumulative_histogram` field type.

**Comment by jpountz** [comment]
The main challenge that I see with @axw's proposal is that today we are using run-length encoding to write the counts in order to save space, which means that we can't have direct access to the last value since we cannot know the index at which it can be found without decoding all previous value/count pairs. We could use a fixed number of bytes per value/count pair (e.g. 8 bytes (double) for the value and 8 (long) for the cumulative sum) but then the space overhead would often be greater than if we stored the min, max sum and value_count separately?

**Comment by csoulios** [comment]
In that case, can we all agree that we should close this issue and create a new issue about adding histogram support in the `aggregate_metric_double` field type?

**Comment by axw** [comment]
Sounds reasonable to me. If it supports the same queries as the histogram type, then I can't imagine that would be a problem for our UI. Any concerns @dgieselaar?

**Comment by jpountz** [comment]
@csoulios This sounds good to me. One thing that might be worth discussing is whether `aggregate_metric_double` could accept the same input format as `histogram` and derive min, max, sum and value_count from the histogram automatically at index time. I suspect that this would help APM transition from `histogram` to `aggregate_metric_double`, and more generally users would appreciate not having to provide redundant information?

**Comment by dgieselaar** [comment]
> Any concerns @dgieselaar?

Not really, other than this being a breaking change, assuming we change the field name of `transaction.duration.histogram`?   If not, are these types (histogram and aggregate_metric_double) going to be fully compatible, e.g. when querying a set of indices where both are present under the same field name?

**Comment by csoulios** [comment]
@dgieselaar When the `aggregate_metric_double` field type is queried/aggregated, it will automatically delegate all histogram  related operations (percentiles etc) to its internal `histogram` structure. So, it will behave as a `histogram` field. 

>. One thing that might be worth discussing is whether aggregate_metric_double could accept the same input format as histogram and derive min, max, sum and value_count from the histogram automatically at index time.

This is something we can probably implement and will definitely improve compatibility between the `histogram` and `aggregate_metric_double` field types

**Comment by csoulios** [comment]
As dicussed, closing this ticket. I have opened #81031
