### ISSUE TITLE
[CI] SmokeTestMultiNodeClientYamlTestSuiteIT test {yaml=snapshot.get/10_basic/Get snapshot info with metadata} failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#74377]
**Build scan:**
https://gradle-enterprise.elastic.co/s/vvx5u2sdyn2iw/tests/:qa:smoke-test-multinode:integTest/org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT/test%20%7Byaml=snapshot.get%2F10_basic%2FGet%20snapshot%20info%20with%20metadata%7D

**Reproduction line:**
`./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" -Dtests.method="test {yaml=snapshot.get/10_basic/Get snapshot info with metadata}" -Dtests.seed=8A1BBF935CCF0978 -Dtests.locale=en-AU -Dtests.timezone=Eire -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dsnapshot.get/10_basic/Get%20snapshot%20info%20with%20metadata%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([8A1BBF935CCF0978]:0)

```

**Comment by mark-vieira** [comment]
I think this is just another example of stuff timing out on Fedora 32 for some reason. This distro is actually EOL and not part of our support matrix anyhow so I've removed Fedora 32 testing. I'm going to close this for now, we can reopen if we see it happen on another platform.
