### ISSUE TITLE
Clarify migration from warm to cold tier

### ISSUE THREAD

**Issue by repantis** [elastic/elasticsearch#74385]
At least one user was confused by how data are migrated from warm to cold tier.  They assumed that an index that moves from warm to cold stays local.  However, we currently copy the data back to the local node from the snapshot.  The user suggested to mention this explicitly in the documentation, to avoid surprises over the associated data transfer.

https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-searchable-snapshot.html may be the best place for such a warning, with https://www.elastic.co/guide/en/elasticsearch/reference/current/searchable-snapshots.html being a second alternative.

@sajjadwahmed @tlrx

**Comment by andreidan** [comment]
We've improved a bit the documentation for the `searchable_snapshot` action in ILM (thanks @stefnestor ) https://github.com/elastic/elasticsearch/pull/74706
