### ISSUE TITLE
[CI] CoreTestsWithSearchRuntimeFieldsIT failes: Expected: GlobalOrdinalsStringTermsAggregator.* but: was "MapStringTermsAggregator"

### ISSUE THREAD

**Issue by BigPandaToo** [elastic/elasticsearch#74430]
**Build scan**:
https://gradle-enterprise.elastic.co/s/m3dpetvdbs5bq/console-log?task=:x-pack:qa:runtime-fields:core-with-search:yamlRestTest

**Repro line**:
./gradlew ':x-pack:qa:runtime-fields:core-with-search:yamlRestTest' --tests "org.elasticsearch.xpack.runtimefields.test.search.CoreTestsWithSearchRuntimeFieldsIT" -Dtests.method="test {yaml=search.aggregation/22_terms_disable_opt/disable optimization}" -Dtests.seed=1271A6F7789D0793 -Dtests.locale=en-US -Dtests.timezone=America/New_York -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,summary),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:CoreTestsWithSearchRuntimeFieldsIT),sort:!(time,desc))

**Failure excerpt**:
Expected: GlobalOrdinalsStringTermsAggregator.* |  
-- | --
  | but: was "MapStringTermsAggregator" |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:62) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)

**Comment by nik9000** [comment]
Closed by ce245705b6828424f6877c97226cebe10b3e731a.
