### ISSUE TITLE
ES 6.0 cancel running task command not stopping the task

### ISSUE THREAD

**Issue by utkarsh1996** [elastic/elasticsearch#74461]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

To get the running task in ES 6.0
run the command:
GET _tasks?actions=*search (this will fetch those tasks which are related with search

from the response get the **node_id:task_id**

Now run the ES 6.0 cancel command:
POST _tasks/node_id:task_id/_cancel

This cancel command don't actually cancel the task, that keeps on running.
**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
The cancellation of a task is not automatic. There's an indirection that requires the thread that executes the request to detect that the task is cancelled. We've also made several changes in the 6x, 7x series so 6.0 shouldn't be used as a baseline. 
The main question here is whether the cancelled task uses any resource on the cluster. We try hard to not waste any resources when a task is cancelled so sub-tasks may appear in the task manager for some time but if that's the case that could mean that they are parked and don't consume anything yet. We also added a flag recently that marked cancelled tasks in the task API output, that was the main source of confusion so I hope that will address your concern.

I invite you to test the latest versions to check the improvements. If you have a specific improvement in mind for request cancellation please don't hesitate to reopen but as such I'd consider this issue as a user question. We reserve github for verified bugs and feature request so I'd also be happy to continue the discussion in the [discuss forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) if you want more explanations on how cancellation works.
