### ISSUE TITLE
Elasticsearch SQL aggregation along with another aggregation

### ISSUE THREAD

**Issue by maltoze** [elastic/elasticsearch#74532]
**Elasticsearch version** (`bin/elasticsearch --version`): `7.13.0`

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): `Linux 48f55a046547 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

When executing SQL like the following:
```sql
SELECT MAX (mycount) 
FROM (SELECT agent_code,COUNT(agent_code) mycount 
FROM orders 
GROUP BY agent_code);
```

**Provide logs (if relevant)**:

"stacktrace": ["java.lang.ClassCastException: class org.elasticsearch.xpack.ql.expression.ReferenceAttribute cannot be cast to class org.elasticsearch.xpack.ql.expression.function.scalar.ScalarFunction (org.elasticsearch.xpack.ql.expression.ReferenceAttribute and org.elasticsearch.xpack.ql.expression.function.scalar.ScalarFunction are in unnamed module of loader java.net.FactoryURLClassLoader @329a1f8d)"

**Comment by Luegg** [comment]
The query in question falls under the limitations discussed in https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-limitations.html#_using_a_sub_select and is currently not supported.

It should not result in a ClassCastException though but the query should be rejected by the verifier and give a more helpful error message. I've also tested it on latest master and we still get the same error.

**Comment by bpintea** [comment]
Original issue is failing due to reasons explained in linked limitations and failing mode has been adjusted in https://github.com/elastic/elasticsearch/pull/75517.
