### ISSUE TITLE
How to use filter operation in top_hits or inner_query

### ISSUE THREAD

**Issue by yanchaoguo** [elastic/elasticsearch#74593]
Inner hits查询是会在主查询上再发起一次查询吗？请问如何在inner hits中对数据进行过滤操作，多个inner hits设置单独的过滤策略

**Comment by fcofdez** [comment]
Hi @yanchaoguo, Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Make sure to use the forum part dedicated to Kibana when asking your question there. Many thanks.
