### ISSUE TITLE
Nodes not joining Elasticsearch cluster . Instead its creating its own cluster

### ISSUE THREAD

**Issue by ramnatan** [elastic/elasticsearch#74598]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: []

**JVM version** (`java -version`): Zulu JDK 1.8.0_262

**OS version** (`uname -a` if on a Unix-like system): It reproducible across different Platforms like SUSE, RHEL

**Description of the problem including expected versus actual behavior**:

I have 3 nodes cluster with below config

Node 1 ::

cluster.name: "as_elasticsearch"
node.name: "node-1"
node.data: true
path.repo: "/var/elasticsearch/snapshot/"
path.data: "/var/lib/elasticsearch"
network.host: "ip1"
http.port: 9200
discovery.seed_hosts:
-ip1
-ip2
-ip3
cluster.initial_master_nodes:

"node-1"
"node-2"
"node-3"

Node 2 ::

cluster.name: "as_elasticsearch"
node.name: "node-3"
node.data: true
path.repo:
"/var/elasticsearch/snapshot/"
path.data: "/var/lib/elasticsearch"
network.host: "ip2"
http.port: 9200
discovery.seed_hosts:
"ip1"
"ip2"
"ip3"
cluster.initial_master_nodes:

"node-1"
"node-2"
"node-3"

Node 3 ::

cluster.name: "as_elasticsearch"
node.name: "node-2"
node.data: true
path.repo:
"/var/elasticsearch/snapshot/"
path.data: "/var/lib/elasticsearch"
network.host: "ip3"
http.port: 9200
discovery.seed_hosts:
-ip1
-ip2
-ip3
cluster.initial_master_nodes:

"node-1"
"node-2"
"node-3"

I updated yml files one by one and restarted Elasticsearch. But as I see, sometimes, one or two nodes went out of the cluster (Not all the times) and created its own.

I guess since all 3 are master eligible, this could happen. I can afford only 3 node cluster. So I wanted all three to be master eligible so that atleast two node cluster work without any issue.

Ideally all nodes should get joined to single cluster

I have not faced this issue in ELK 7.4.2 with same set of config files

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by fcofdez** [comment]
Hi @ramnatan, Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
