### ISSUE TITLE
Mappings: The get field mappings API should raise an error when shards are not allocated

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#7460]
The get fields mapping API is different from the get mappings since it goes to shards instead of the master node, since shards have per-field lookup structures that the master node doesn't have.

However, this can have some disappointing side effects in case no shards of the requested index are allocated: the API will return empty mappings. Instead this API should raise an error when shards are not allocated.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/5368
