### ISSUE TITLE
Documentation is missing for IndexingOperationListener

### ISSUE THREAD

**Issue by kkirsche** [elastic/elasticsearch#7462]
Hey guys,

I would be interested in adding documentation about the IndexingOperationListener but I wanted to check if this was of interest and if so where would be the best place to add this information.

Thanks guys!
Kevin

**Comment by kkirsche** [comment]
Sounds good. I'll look at revising this in the Java docs. I just asked as it is really a helpful thing to use when building plugins for elasticsearch. 

Would you be open though to a more complete "Plugins" section of the documentation http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-plugins.html

This does a fine job of showing you what's available but doesn't really offer much to help someone develop a new plugin.

Thoughts?

**Comment by dadoonet** [comment]
There is a plan to write such a doc. in the meantime, I found this page super useful: https://www.found.no/foundation/writing-a-plugin/

Hope this helps.

**Comment by kkirsche** [comment]
Thanks :)

**Comment by clintongormley** [comment]
No further feedback. Closing
