### ISSUE TITLE
Elasticsearch-users CLI tool results in error when run with FIPS enabled

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#74641]
Looks like tests that depend on setting up a user fail with FIPS enabled because of an error thrown by the `elasticsearch-users` CLI tool.

**Build scan**:
https://gradle-enterprise.elastic.co/s/5qs3ehfyskhf4/console-log?task=:qa:system-indices:javaRestTest

**Repro line**:
I suspect just try running the CLI tool directly to repro this.

**Reproduces locally?**:
Didn't try.

**Applicable branches**:
master

**Failure excerpt**:
```
:qa:system-indices:javaRestTest FAILED
Exec output and error:
| Output for ./bin/elasticsearch-users:ERROR: Error storing the password for the new user
```

**Comment by ywangd** [comment]
FIPS mode requires the length of a password to be at least 14 bytes, i.e. password on [this line](https://github.com/elastic/elasticsearch/blob/master/qa/system-indices/build.gradle#L28) needs to be changed. 

More details can be found in https://github.com/elastic/elasticsearch/pull/65464

I'll raise a fix for the test.
