### ISSUE TITLE
Warn on force merge when index has refresh interval set to -1

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#74649]
This comes up from time to time.

This happens when a user has `refresh_interval` set to `-1` (usually to facilitate bulk indexing/reindexing performance) but forgot to re-enable it before running force merge.  As a result, after force merge ran, they saw that the segment files still remained when using `_cat/segments` and got confused, thinking that force merge didn't run or didn't run successfully.  

It can be helpful to throw a warning to the log file when it detects that force merge is being run against an index with `refresh_interval` set to `-1` to explicitly remind users to reset refresh interval after running force merge.

**Comment by DaveCTurner** [comment]
Perhaps we should just refresh after a force-merge?
