### ISSUE TITLE
Search for IP addresses with CIDR notation, in query_string

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#7464]
Today we can search for ranges IP addresses in fields with a query string query like this:
`ip_address:[10.0.0.0 TO 10.255.255.255]`

It would be great if we could do:
`ip_address:10.0.0.0/8`  or  `ip_address:10/8`.

This is mostly useful in kibana, where all queries are sent at query_string queries. I understand that `ip_range` aggregation currently supports this. Would be nice in a QSQ :-)

**Comment by td-edge** [comment]
+1 This would be a big help if we could search without the ranges.

**Comment by webmstr** [comment]
+1

**Comment by zaakiy** [comment]
+1

**Comment by Pytlicek** [comment]
+1

**Comment by JiounDai** [comment]
but 
"must_not": [
      {
          "query_string": {
                "query": "clientip:[10.44.0.0 TO 10.44.255.255]"
              }
      }
]
can not work well

**Comment by ajmurmann** [comment]
+1

**Comment by torrancew** [comment]
+1

**Comment by anujsrc** [comment]
+1

**Comment by SrikanthKS** [comment]
+1

**Comment by xande** [comment]
+1

**Comment by jjunqueira** [comment]
+1

**Comment by kjelle** [comment]
+1

**Comment by LxiaoGirl** [comment]
How to use this?

**Comment by djwmarks** [comment]
+1

**Comment by daguy666** [comment]
+1

**Comment by kiwiz** [comment]
+1

**Comment by orangey** [comment]
+1

**Comment by german23** [comment]
+1

**Comment by pemontto** [comment]
+1

**Comment by jpountz** [comment]
Closed via #14773

**Comment by ave19** [comment]
Our whole life is CIDR.  +infinity!

**Comment by marvinwankersteen** [comment]
Can please someone tell me how to use it in Kibana? I use elasticsearch 5.6.4 and kibana 5.6.
We push netflows from a cisco asa to elasticsearch. I don't want to see the private networks. So I tried the query filter `netflow.ipv4_src_addr: "172.16.0.0/16"` but that doesn't work.

**Comment by zaakiy** [comment]
thanks @skorpion8909! Do you know which version this was enabled in?

**Comment by skorpion8909** [comment]
It was at least 7.9. In the current ELK 7.17-1 monitor.ip:"10.0.0.0/8" is working.
