### ISSUE TITLE
Add an upperbound for explicit/forced refresh

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#7467]
Have a use case in the field where every document update needs to be refreshed immediately (more often than once per 1s).  We certainly do not recommend issuing extremely frequent forced _refresh calls.  One workaround is to implement client code to store a "state" for when the last forced refresh occurred and to delay subsequent forced refreshes accordingly.    Would be nice to add an upperbound setting for explicit/forced refresh so this can be handled from the server side.

**Comment by clintongormley** [comment]
Closing in favour of #1063
