### ISSUE TITLE
Unclear definition of new node roles when bootstrapping with Elasticsearch-setup-passwords

### ISSUE THREAD

**Issue by philippkahr** [elastic/elasticsearch#74681]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.13.2
**Plugins installed**: []

**JVM version** (`java -version`):
bundled JDK
**OS version** (`uname -a` if on a Unix-like system):
any
**Description of the problem including expected versus actual behavior**:

When bootstrapping a cluster consisting of three master nodes and 2 hot nodes I assigned the `data_hot, ingest` role. I activated `xpack.security.enabled` and setup `tls` and `https`.

When I run `elasticsearch-setup-password auto` it always errored with Read Timeout. In the logs it showed that the cluster was not able to create the `.security` index.

I had to append the `data_content` node role to two hot nodes, as `data_hot` on it's own is not enough. This should be clearly stated in the docs here: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-node.html

The data_content role is described as:
Content data nodes accommodate user-created content. They enable operations like CRUD, search and aggregations.

whilst the data_hot node is described as:
Hot data nodes store time series data as it enters Elasticsearch. The hot tier must be fast for both reads and writes, and requires more hardware resources (such as SSD drives).

I wish there was some clarification going on, as this is really confusing and leads to a lot of debugging until finding.

*Screenshots*

**Comment by jrodewig** [comment]
Thanks @philippkahr. I believe this will be addressed with #74566 which clearly labels `data_content` (or `data`) as required node roles.

**Comment by philippkahr** [comment]
@jrodewig you are right! I will close this issue.
