### ISSUE TITLE
Get rollup index capabilities permissions should work with view_index_metadata

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#74779]
I was working on a bug in Kibana - https://github.com/elastic/kibana/issues/103496 - and it boiled down to this: I can get the fields for an index with `view_index_metadata` privileges UNLESS its a rollup index which requires `read` privs since get rollup index capabilities must be queried - https://www.elastic.co/guide/en/elasticsearch/reference/current/rollup-get-rollup-index-caps.html

I'm trying to collect telemetry data on kibana index patterns using the `kibana_system` user which has `view_index_metadata` but not `read` access.

@elastic/kibana-security

**Comment by jportner** [comment]
So it sounds like there are two paths forward to enable this functionality in Kibana:

1. If the user holds the appropriate rollup cluster privilege (`monitor | monitor_rollup | manage | manage_rollup`) _and_ they hold the appropriate index privilege (`view_index_metadata | manage`), allow them to get rollup index capabilities
2. Add a new `view_rollup_metadata` index privilege, and grant that to the `kibana_system` user

Option 1 makes more sense to me, but I might not have the whole picture here. I'm curious to know what the ES Security team's opinion is!

**Comment by ywangd** [comment]
IIUC, the [Get rollup index capabilities API](https://www.elastic.co/guide/en/elasticsearch/reference/current/rollup-get-rollup-index-caps.html) only needs to read the `mappings._meta` field for its response, it does *not* need to read any data. Since the entire `mappings` field is accessible with the `view_index_metadata` privilege, it makes sense to allow this API to be accessible as well. I personally would consider it a bug for this API to be categorized as `read` instead of `view_index_metadata`.

**Comment by not-napoleon** [comment]
@ywangd That seems reasonable to me.  Is that something security should update or should analytics team fix it?  I'm not really sure where the privilege mappings are set, but I can find out.

**Comment by ywangd** [comment]
@not-napoleon I can handle this if the proposed fix sounds reasonable to your team. Also I'd like to revise my previous proposal a bit based on how [Field capabilities API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html) is handled. You can access the Field capabilities API with either `view_index_metadata`, `read` or `manage` privilege. My impression is that these two APIs have a lot of similarities. If this is the case, I'd suggest having "Get rollup index capabilities API" accessible with either `view_index_metadata`, `read` or `manage` as well. This also has the advantage of no "breaking" change. 

If you are happy with the revised proposal, I can raise a PR and add you as a reviewer. Thanks!

**Comment by csoulios** [comment]
> I'd suggest having "Get rollup index capabilities API" accessible with either view_index_metadata, read or manage as well. This also has the advantage of no "breaking" change.

+1 to using a similar approach to field caps API. I think this make the two similar APIs more consistent and (as @ywangd  said) is not a breaking change
