### ISSUE TITLE
Build Elasticsearch Docker image with Cloud dependencies embedded

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#74795]
As discussed, we want to build an image that is directly deployable to Elastic Cloud. The intent is for this image to mostly identical to the existing Docker images with two main exceptions:

1. The `repository-azure`, `repository-gcs` and `repository-s3` plugins will be pre-installed.
2. Filebeat and Metricbeat will be installed under `/opt/filebeat` and `/opt/metricbeat`, respectively.

The first item should be pretty strait forward, we just want to install these plugins as part of building the image so they are already baked into the image for Cloud.

The second item will require slightly more coordination, we'll need to fetch these things from the Elastic snapshot artifacts repo when building locally (@breskeby can provide guidance here), and for release builds we'll need to use the release-manager built artifacts for those projects.

No need to update download pages or documentation here, this image isn't intended to be used by "normal" users. We also won't be publishing these to Dockerhub for the same reason.

**Comment by pugnascotia** [comment]
I have some changes in #74980 to support an ES Cloud Docker image, and some related changes to `release-manager`, but I need help running it to test everything end-to-end. Ping @mgreau / @nkammah for help 🙏
