### ISSUE TITLE
Remove Nysiis implementation from analyis-phonetic plugin

### ISSUE THREAD

**Issue by uschindler** [elastic/elasticsearch#74821]
The analysis-phonetic plugin has a version of the Nysiis encode which was copypasted long ago from a prerelease (subversion trunk) of Apache Commons Codec.

This implementation is already included in commons-codec 1.11, so the Nysiis class should be removed and the factory adapted to use the version shipped with commons codec.

The copypaste of code is also a license violation, because the code, originating from commons-codec subversion repository, copyrighted by Apache Software Foundation, was relicensed to Elastic License

Here is the code: https://github.com/elastic/elasticsearch/blob/7.13/plugins/analysis-phonetic/src/main/java/org/elasticsearch/index/analysis/phonetic/Nysiis.java

Please note the comment that it was copied and see the ASF license here: 
https://github.com/apache/commons-codec/blob/b70e177f8733e9dd4e5f503620ed0b136b74785b/src/main/java/org/apache/commons/codec/language/Nysiis.java

**Comment by spinscale** [comment]
This has already been done in master https://github.com/elastic/elasticsearch/pull/65259

**Comment by uschindler** [comment]
Nevertheless the license in the 7.x branch has to be corrected. IMHO, this should be reported to Apache Legal mailing list.

**Comment by uschindler** [comment]
https://issues.apache.org/jira/browse/LEGAL-579

**Comment by ywelsch** [comment]
Thank you for raising this. I've opened #74830 as immediate action to backport #65259 to the relevant 7.x branches.

**Comment by tomcallahan** [comment]
I left a comment on the ASF legal issue; from my perspective we're good. We'll re-open if anything else comes up.
