### ISSUE TITLE
SQL: support for nested aggregations

### ISSUE THREAD

**Issue by wade009** [elastic/elasticsearch#74852]
I hope es can support sql's nested multiple group by function.

For example:

**GET /_xpack/sql?format=txt
{
  "query": "select sum(a.cc) from (select mobile,count(mobile) cc from myindex group by mobile) a"
}**

or 

**GET /_xpack/sql?format=txt
{
  "query": "select a.cc,count(a.cc) as sum_cc from (select mobile,count(mobile) cc from myindex group by mobile) a group by a.cc"
}**

But now it’s an error to execute it like this.
**{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Does not know how to convert argument AggregateFunctionAttribute[cc,LONG,a,TRUE,854,false,860,863,860._count] for function Sum[]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Does not know how to convert argument AggregateFunctionAttribute[cc,LONG,a,TRUE,854,false,860,863,860._count] for function Sum[]"
  },
  "status": 500
}**

**Comment by wchaparro** [comment]
Superceded by ES|QL
