### ISSUE TITLE
duplicate records accross multiple indicies of Index Template under an Alis with rollover API

### ISSUE THREAD

**Issue by shoaibhassan007** [elastic/elasticsearch#74878]
I am dealing with time series data through logstash into elasticsearch. And using Index template managed by ILM policy.
logstash reads very and large data files from a mount point and we add a _id filed from logstash to make sure unique records in the Elasticsearch Db. And my configuration some need to update and reload the previous data again and it does not make sure uniqueness across the indices and ingest duplicate records in the next index under the same alias. 
We need to make sure unique records across indices for the consistent and integrated data
please, have a look on the given duplicate records with same_id  but in different indexes. 
[
     {
       "_index" : "searchlite-000136",
       "_type" : "_doc",
       "_id" : "CMS_Risk_Assessmentflask2-searchlite-v22021-05-25 13:18:54.213916rb",
       "_score" : 1.0099684,
       "_source" : {
         "@timestamp" : "2021-05-26T00:00:51.928Z",
         "t" : "rb",
         "hostname" : "flask2-searchlite-v2",
         "url" : "https://www.testalert1.slashdot.systems/",
         "customer_name" : "CMS_Risk_Assessment",
         "created_at" : "2021-05-25 13:18:54.213916",
         "@version" : "1",
         "domain" : "testalert1.slashdot.systems"
       }
     },
     {
       "_index" : "searchlite-000134",
       "_type" : "_doc",
       "_id" : "CMS_Risk_Assessmentflask2-searchlite-v22021-05-25 13:18:54.213916rb",
       "_score" : 1.0096496,
       "_source" : {
         "@timestamp" : "2021-05-25T13:19:32.231Z",
         "t" : "rb",
         "hostname" : "flask2-searchlite-v2",
         "url" : "https://www.testalert1.slashdot.systems/",
         "customer_name" : "CMS_Risk_Assessment",
         "created_at" : "2021-05-25 13:18:54.213916",
         "@version" : "1",
         "domain" : "testalert1.slashdot.systems"
       }
     }
   ]

Thus it create problems of duplication. Uniqueness should be maintained under a Alias of Index Template
Thanks.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_275

**OS version** (`uname -a` if on a Unix-like system): linux 4.18.0-193.19.1.el8_2.x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. create index template with and alias
 2. inseart document with _id in index-000001 with alias
 3.insert same document with same _id in index-000002 with alias

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
This looks more like a question than a bug or a feature request. If that is the case, I would recommend that you post it on our forms at https://discuss.elastic.co/ . Thanks for your cooperation.
