### ISSUE TITLE
Plugin installer want to check everything in the plugin folder

### ISSUE THREAD

**Issue by fbacchella** [elastic/elasticsearch#74879]
All the content of `/usr/share/elasticsearch/plugins` is checked, even hidden files.
Providing a way to filter out some content here could be helpful.
For example, I would like to store in a special file some custom informations about installed plugin. It can be hidden, or with any names. But that's not actually possible.

The problem is at  https://github.com/elastic/elasticsearch/blob/ab23cc06d153eb1368d37407d6de2f16c94804dd/server/src/main/java/org/elasticsearch/plugins/PluginsService.java#L276
A few check to avoid adding everything could be helpfull.

**Comment by MarkRibeiro** [comment]
@fbacchella could it be as simple as this?
```
for (Path plugin : stream) {
   if (FileSystemUtils.isDesktopServicesStore(plugin) ||
      plugin.getFileName().toString().startsWith(".")) {
      continue;
   }
[...]
}
```

Or is it something more elaborate?

**Comment by fbacchella** [comment]
Or it could be checked using https://docs.oracle.com/javase/8/docs/api/java/io/File.html#isHidden--. I don't know if smarter filtering is needed. For example, can a plugin be stored in a file ?

**Comment by rjernst** [comment]
@fbacchella I suggest you store your additional plugin metadata in a different path. The plugins directory is meant to be completely controlled by Elasticsearch. It is not meant as a general directory for users to store anything in. If by chance it is metadata about which plugins should be installed, consider storing it in the configuration directory, but also note that we are planning to [add such a feature](https://github.com/elastic/elasticsearch/issues/70219).

As this is working as designed, and we do not plan to make any changes to that design, I hope you don't mind that I close this issue.
