### ISSUE TITLE
Reindex - 2.4.5 to 5.6.16 - is throwing illegal character error - pls suggest any solution

### ISSUE THREAD

**Issue by SChowdary05** [elastic/elasticsearch#74884]
Hi Team,

When we do reindex we get the following error:

{
"cause": {
"caused_by": {
"reason": "object field starting or ending with a [.] makes object resolution ambiguous: []",
"type": "illegal_argument_exception"
},
"reason": "failed to parse",
"type": "mapper_parsing_exception"
},
"id": "transatlantic",
"index": "publisher-reindexed-5",
"status": 400,
"type": "featured_list_publisher"
},

**Comment by cbuescher** [comment]
> object field starting or ending with a [.] makes object resolution ambiguous: []

The error message suggests that some field name in a particular document is empty. This safeguard was introduced in 22891. Maybe the "id" in the error can help identify the problematic document.
For further questions I'd like to refer you to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, but this to me looks more like an intended safeguard. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
