### ISSUE TITLE
Dynamic mapping updates do not call `fixRedundantIncludes`

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#74899]
RootObjectMapper has a method `fixRedundantIncludes` which will iterate
through its object hierarchy and find nested mappers that have `include_in_root`
set where they don't need it.  However, this method is not called when a dynamic
mapping is built.  This means that a bulk index request that creates a nested mapper
through a dynamic mapping update can end up throwing errors: the dynamic
mapping contains a nested object with both 'include_in_parent' and 'include_in_root'
set to true; this mapping is applied on the master and `include_in_root' is adjusted
to 'false' because it is redundant; the same dynamic mapping on a different shard
is sent to the master; and this mapping will fail because merging is done before
redundant includes are fixed, and so there is a conflict.

**Comment by javanna** [comment]
We've talked in the past about making this validation step part of the creation of a new DocumentMapper. I was surprised that it is called only in some cases and I believe I left as-is, unless I introduced bugs while touching that area of the code. It sounds like it should be made part of creating a new mapping.

**Comment by javanna** [comment]
From my notes: 

>Validate DocumentMapper as part of its construction (by calling fixRedundantIncludes and validate): it seems like there are cases where we create it without validating it, is that a bug or a feature?

**Comment by romseygeek** [comment]
Yeah I think this will be fixed by https://github.com/elastic/elasticsearch/pull/74410 which makes it part of the build/merge logic for NestedObjectMapper itself but I'll do a separate fix for 7.14/7.13.4 anyway and we can re-use the tests.
