### ISSUE TITLE
[CI] FIPS builds failing with deprecated & incompatible Gradle features

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#74900]
I'm assuming the failure is related to FIPS mode as it is in the common factor in the failures I found.

**Build scan**:
https://gradle-enterprise.elastic.co/s/qm5mrwwu7wzky

**Repro line**:
erm `make` 

**Reproduces locally?**:
No

**Applicable branches**:
7.14

**Failure history**:
Since the 28th June

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Deprecated%20Gradle%20features%20were%20used%20in%20this%20build,%20making%20it%20incompatible%20with%20Gradle%208.0&search.relativeStartTime=P7D&search.timeZoneId=Europe/London

**Failure excerpt**:
```
* What went wrong: 
 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0
```

**Comment by jkakavas** [comment]
This is https://github.com/elastic/elasticsearch/pull/74670 that failed to auto-backport to 7.14. Ping @breskeby for visibility

**Comment by breskeby** [comment]
ah seems this cracked through due to 7.x jumping to 7.15. Will double check and cherry pick the 7.x backport down to 7.14 branch

**Comment by breskeby** [comment]
back ported https://github.com/elastic/elasticsearch/pull/74738 and https://github.com/elastic/elasticsearch/pull/74808 from 7.x to the 7.14 branch that should fix this issue
