### ISSUE TITLE
Array clients in /_nodes/stats/http potentially dangerous.

### ISSUE THREAD

**Issue by greenx** [elastic/elasticsearch#74964]
Hello!
I have updated our developer stand to version ES 7.13.2.
The following unpleasant thing was discovered: as a result of an error in the client part, requests to a non-existent index were sent to Elastic.
Elastic answered honestly with HTTP/404, but the client part continued its DDoS.
It turned out to be a small self-DDoS - about 30,000 requests per minute.

1. As far as I understand, this table has no size restrictions.
2. In addition to the fact that it was bad for Elastic, the telegraph was lying next to him. could not parse 60MB JSON.
3. I haven’t found a way to disable the collection of these statistics - I don’t need it. I can get all the same from the logs of the load balancer. 

![image](https://user-images.githubusercontent.com/2979727/124599033-eafa3600-de6d-11eb-89a2-f795cfe9b3d6.png)

**Comment by DaveCTurner** [comment]
Collection of these stats can be disabled with the `http.client_stats.enabled` setting, see [these docs for more info](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html). Have you really had 130k HTTP client connections from the last 5 minutes? That might indicate that your clients are not configured to reuse connections which is pretty inefficient.

**Comment by greenx** [comment]
@DaveCTurner 
Thank you! Apparently I googled badly. ;-)
Or rather, not really me. 

Google at the request "nodes stats clients" gives the page "Node stats API".
Honestly speaking, I also expected to see this page and a description of the parameters that can be adjusted.
The "networking" page isn't even next to the fifth page of search results. 

A search on elastic.co for this query gives anything at all (some old releases from version 2.1, and even 0.7), and the desired page appears on the 10th line of results. 

> Have you really had 130k HTTP client connections from the last 5 minutes? That might indicate that your clients are not configured to reuse connections which is pretty inefficient.

There was a funny moment - the client side caused an exception from an unexpected response. The parent process again raised the child and everything repeated ad infinitum. I agree that this is a error, but no one is immune from them. Therefore, it is better to have a limit for this table.

**Comment by danhermann** [comment]
I'm going to close this issue as Elasticsearch is working as expected here and the collection of HTTP client stats can be disabled. If desired, you could open an enhancement request to allow collection of stats for a bounded number of HTTP clients.

**Comment by greenx** [comment]
Of course yes! Well done! There is a reason to close the problematic appeal!
Elastic introduces indexing pressure so that I don't index aggressively. But makes an unlimited table of connection statistics to make it easier for dDOS. Cool!
