### ISSUE TITLE
Support multi-terms aggregations in Java Rest High Level Client

### ISSUE THREAD

**Issue by IliaIsakhin** [elastic/elasticsearch#75030]
Currently, there is no builder method for [multi-terms aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/search-aggregations-bucket-multi-terms-aggregation.html) in `org.elasticsearch.search.aggregations.AggregationBuilders`.

In another hand, even if I could write multi-terms aggregation builder by my own, there is no multi-terms parser in `org.elasticsearch.client.RestHighLevelClient` and Java Client cannot parse valid response from Elasticsearch cluster.

**Comment by bachden** [comment]
Same here!

**Comment by zimmj** [comment]
There is a possibility to still use it.
Create the normal search with SearchSourceBuilder
Then Convert it to String, you will get a JSON.
After that, you can inject the wished multi_term aggregation into this Jason with JSONPath.

We will then run the search JSON with the low rest client.
That means as well, that we need to parse the result by ourselves.

But that is a normal thing to do, when working with API's

**Comment by bkuberek** [comment]
👍

**Comment by jbaiera** [comment]
The HLRC has been replaced with the new [Java client](https://github.com/elastic/elasticsearch-java). If you still think this is required please open an issue for tracking there. Thanks!
