### ISSUE TITLE
Feature to skip some inner hits

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#75040]
We have many documents that have a `group` field that we'd like to use with `inner_hits` to group related documents. But we also have many more documents that *don't* belong to a group. We'd like to "skip" `inner_hits` for these documents and return them as we would from a normal search.

Here's an example with curl:
```
curl -uelastic:password -XDELETE localhost:9200/test
curl -uelastic:password -XPUT -HContent-Type:application/json localhost:9200/test -d'{
  "mappings": {
    "properties": {
      "group": {
        "type": "keyword"
      },
      "text": {
        "type": "text"
      }
    }
  }
}'

curl -uelastic:password -XPOST -HContent-Type:application/json localhost:9200/test/_bulk?refresh -d'
{"index": {}}
{"group": "red", "text": "the quick brown fox"}
{"index": {}}
{"group": "red", "text": "the quick pink fox"}
{"index": {}}
{"text": "the quick orange fox"}
{"index": {}}
{"group": null, "text": "the quick grey fox"}
'

curl -uelastic:password -XPOST -HContent-Type:application/json localhost:9200/test/_search?pretty -d'{
  "query": {
    "match": {
      "text": "quick brown fox"
    }
  },
  "collapse": {
    "field": "group",
    "inner_hits": {
      "name": "buddies",
      "size": 2
    }
  }
}'
```

This makes:
```
"hits" : [
      {
        "_index" : "test",
        "_id" : "joIQgXoBElE00mI2B6Yl",
        "_score" : 1.4146938,
        "_source" : {
          "group" : "red",
          "text" : "the quick brown fox"
        },
        "fields" : {
          "group" : [
            "red"
          ]
        },
        "inner_hits" : {
          "buddies" : {
            "hits" : {
              "total" : {
                "value" : 2,
                "relation" : "eq"
              },
              "max_score" : 1.4146938,
              "hits" : [
                {
                  "_index" : "test",
                  "_id" : "joIQgXoBElE00mI2B6Yl",
                  "_score" : 1.4146938,
                  "_source" : {
                    "group" : "red",
                    "text" : "the quick brown fox"
                  }
                },
                {
                  "_index" : "test",
                  "_id" : "j4IQgXoBElE00mI2B6Yl",
                  "_score" : 0.21072102,
                  "_source" : {
                    "group" : "red",
                    "text" : "the quick pink fox"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "_index" : "test",
        "_id" : "kIIQgXoBElE00mI2B6Yl",
        "_score" : 0.21072102,
        "_source" : {
          "text" : "the quick orange fox"
        },
        "inner_hits" : {
          "buddies" : {
            "hits" : {
              "total" : {
                "value" : 2,
                "relation" : "eq"
              },
              "max_score" : 0.21072102,
              "hits" : [
                {
                  "_index" : "test",
                  "_id" : "kIIQgXoBElE00mI2B6Yl",
                  "_score" : 0.21072102,
                  "_source" : {
                    "text" : "the quick orange fox"
                  }
                },
                {
                  "_index" : "test",
                  "_id" : "kYIQgXoBElE00mI2B6Yl",
                  "_score" : 0.21072102,
                  "_source" : {
                    "group" : null,
                    "text" : "the quick grey fox"
                  }
                }
              ]
            }
          }
        }
      }
    ]
```

We'd like a way to configure it to make:
```
{
  "took" : 16,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "test",
        "_id" : "joIQgXoBElE00mI2B6Yl",
        "_score" : 1.4146938,
        "_source" : {
          "group" : "red",
          "text" : "the quick brown fox"
        },
        "fields" : {
          "group" : [
            "red"
          ]
        },
        "inner_hits" : {
          "buddies" : {
            "hits" : {
              "total" : {
                "value" : 2,
                "relation" : "eq"
              },
              "max_score" : 1.4146938,
              "hits" : [
                {
                  "_index" : "test",
                  "_id" : "joIQgXoBElE00mI2B6Yl",
                  "_score" : 1.4146938,
                  "_source" : {
                    "group" : "red",
                    "text" : "the quick brown fox"
                  }
                },
                {
                  "_index" : "test",
                  "_id" : "j4IQgXoBElE00mI2B6Yl",
                  "_score" : 0.21072102,
                  "_source" : {
                    "group" : "red",
                    "text" : "the quick pink fox"
                  }
                }
              ]
            }
          }
        }
      },
      {
        "_index" : "test",
        "_id" : "kIIQgXoBElE00mI2B6Yl",
        "_score" : 0.21072102,
        "_source" : {
          "text" : "the quick orange fox"
        }
      },
      {
        "_index" : "test",
        "_id" : "kIIQgXoBElE00mI2B6Yl",
        "_score" : 0.21072102,
        "_source" : {
          "group" : null,
          "text" : "the quick grey fox"
        }
      }
    ]
  }
}
```

We know we get similar-ish behavior by giving each "ungrouped" document a unique group id. But this feels quite wasteful in terms of space and search time. Each individual inner search may be quite quick but it can slow things down when retrieving a hundred documents.

**Comment by mayya-sharipova** [comment]
@nik9000 I wanted to clarify what's the motivation for this request?

Because docs without a group are returned as inner_hits for the "null" group through a single search request. There is no much performance hit returning them this way VS returning as would be from a normal search.

The only advantage for the requested change I can see is if a user wants to get all docs without a group while for other groups they may want to request only a limited number of docs.

**Comment by nik9000** [comment]
I'm passing on a request so I'm going to need to guess - they are looking for performance more than convenience here. They have many single element groups and need those to come back in the order as a regular search. So they are currently assigning unique group ids to all of those empty groups. That makes the search API put them all into single element groups - that's perfect for them in terms of relevance. But it's expensive in terms of performance because we still try and look up siblings for the single element groups. They can see all of the extra queries adding up in the profiler.

My idea (or theirs, I forget who proposed it first) was to have a way to skip the grouping functionality altogether for documents that don't have a group field. So instead of being in the `null` group we wouldn't group them at all. We'd skip the sibling lookup because we saw an empty group field.

> The only advantage for the requested change I can see is if a user wants to get all docs without a group while for other groups they may want to request only a limited number of docs.

After I typed everything out I think this is pretty much exactly what they are looking for - ungrouped documents should count against the full size rather than the `inner_hits` size. I was thinking about it more in terms of relative ordering, but the size argument also makes sense to me.

**Comment by mayya-sharipova** [comment]
@nik9000 Thanks for the clarification.  It makes sense to me to modify a  search response so the docs without a group become top level docs and count against the full size.  Not to break the current API, we can enable this behaviour when a user specifically requests this by, for example, setting a request parameter `separate_null_group_docs`, which by default will be false.

**Comment by nik9000** [comment]
> setting a request parameter `separate_null_group_docs`, which by default will be false.

That make sense to me!

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.

**Comment by jmuscireum** [comment]
We have exactly the same use-case as @nik9000, this would help us tremendously.
