### ISSUE TITLE
TimeValue: Provide java.time.Duration compliant constructor

### ISSUE THREAD

**Issue by amarocco** [elastic/elasticsearch#75049]
I use ELS in a spring-boot application and get scroll timeout value from my application.properties

ie: 
@Value("elasticScrollTimeout")
private final Long elasticScrollTimeout;
 ...   
final Scroll scroll = new Scroll(TimeValue.timeValueMinutes(elasticScrollTimeout));

since spring-boot 2.XX (I don't remember which one version) we can bind properties to java.time.Duration so instead of having in application.properties:

```
# in Minute
elasticScrollTimeout=2

```
or 
`elasticScrollTimeoutInMinutes=2`

we could have 

`elasticScrollTimeout=2M`

more clear and readable at least in my opinion

**Comment by gwbrown** [comment]
We discussed this in today's core/infra sync.

We were split on whether or not to implement this, but came to the conclusion we are unlikely to implement it ourselves. Further, as we're looking to move away from a model where client application are tied to the Elasticsearch codebase with the [work-in-progress Java client](https://github.com/elastic/elasticsearch-java), we are hesitant to add affordances exclusively for clients - and this would be exclusively for clients, as Elasticsearch itself does not use `java.time.Duration`.

As such, I'm going to close this issue to make it clear that we don't intend to make this change. However, if we could find other use cases for this beyond slightly simplifying client configuration, that would make this significantly more compelling and potentially be a reason to reopen this issue.
