### ISSUE TITLE
Only tag the latest version as latest in GitHub Releases

### ISSUE THREAD

**Issue by torblerone** [elastic/elasticsearch#75101]
Hi, all!

First of all, thank you for keeping this project alive, secure and maintained!

#### What are we doing right now?

When we're checking for new releases of `elastic/elasticsearch` on a **daily** base, we are using the GitHub API. It offers us to grab the latest release as a JSON object.

#### What are we trying to achieve?

From the JSON object we can deduce whether our infrastructure is already up to date or whether there is a newer version. For example, our Elasticsearch cluster is currently running on version `7.13.2`. We're using the "latest release" API endpoint, which can be called like so:

```bash
$ curl -X GET \
    -H "Accept: application/vnd.github.v3+json" \
    --silent \
    "https://api.github.com/repos/elastic/elasticsearch/releases/latest"
```

#### What would we like to do?

When evaluating the returned JSON object from above command, we would like to grab the latest release and check our own infrastructure against it.

#### Where's the problem?

Right now, the API endpoint returns `v6.8.17` as the latest version, while I'm _quite_ sure that the latest version should be `7.13.3`.

#### What could we do about it?

Configure the build / release pipeline to set the latest tag to the semantically latest version - not the last version that was pushed to GitHub Releases.

**Comment by pugnascotia** [comment]
The "latest" release is always whichever one was most recently added to GitHub, chronologically speaking. In order for the "latest" release to be the latest according to the semver, we would need to rework our release process to push releases to GitHub in a specific order, and that feels a bit fragile to rely upon. For example, it's conceivable that we need to release an emergency 6.8 patch release without a corresponding 7.13 release, and suddenly the semver ordering is broken.

As an alternative, you could fetch the repository tags, which do appear to be sorted by default on semver. For example, https://api.github.com/repos/elastic/elasticsearch/tags?per_page=1 returns `v7.13.3` as you would hope.

**Comment by antoineco** [comment]
@pugnascotia the "latest" flag can also be manually fixed, regardless of Elastic's release automation.

Since this seems to be an exceptional situation (I haven't seen that happening in over a year, at least), couldn't a release manager simply mark the right release as the latest?

**Comment by DaveCTurner** [comment]
See #75436 for a more in-depth exploration of the possible workarounds, but TLDR no there is no mechanism ("simple" or otherwise) for doing this.
