### ISSUE TITLE
action.auto_create_index isn't a dynamic setting

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#7513]
Looks like ```action.auto_create_index``` can't be set dynamically as it isn't listed in ClusterDynamicSettingsModule.java.  Any objection to me adding it?

**Comment by synhershko** [comment]
+1 for making this dynamic, at least if its on the pattern mode (and not just `false`)

**Comment by pmusa** [comment]
+1 for that as a dynamic setting. I am trying to set it in found and it is not possible currently.

**Comment by djschny** [comment]
+1 for this, it also helps avoid node level configuration inconsistency.

**Comment by florent-rivoire** [comment]
(I'm fairly new to the ES world but) this setting seems more like a cluster-wide dynamic setting to me.

**Comment by itplayer** [comment]
I hope this setting can be a cluster-wide setting.
The reason is, if a node client setting is true(or lack of setting), but other nodes in cluster is false, then unexpected result happen.
