### ISSUE TITLE
Difference in behaviour if `index.number_of_routing_shards` is set to null vs when it’s not set at all

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#75139]
**Elasticsearch version**: 7.9.2+

**Description of the problem including expected versus actual behavior**:

When the `number_of_routing_shards` value in a template is set to null, the value set on a new index is different than if the `number_of_routing_shards` value is not set at all.

For a 6 shard index:
- When the value is null, the `number_of_routing_shards` matches the number of primary shards configured for the index.
- When the value is not set, the `number_of_routing_shards` is calculated as 768.

The logic which results in this behaviour is [found here](https://github.com/elastic/elasticsearch/blob/68817d7ca29c264b3ea3f766737d81e2ebb4028c/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java#L801-L805)

If that `exists` call returns true then we get the value from the setting, but if the value is null then we get the default value, which is just `number_of_shards` because of the fallback [here](https://github.com/elastic/elasticsearch/blob/667f95b7928d03d9ed90bd6f9b14975f77953e7f/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java#L151-L153). 

**Steps to reproduce**:

```
PUT /_template/template_001
{
  "index_patterns" : ["splitting1-*"],
  "order" : 0,
  "settings" : {
    "number_of_shards" : 6,
    "number_of_routing_shards" : null
  },
  "version": 1
}

PUT /_template/template_002
{
  "index_patterns" : ["splitting2-*"],
  "order" : 0,
  "settings" : {
    "number_of_shards" : 6
  },
  "version": 1
}

PUT /splitting1-001
{
  "settings": {
    "index": {
      "number_of_shards": 6
    }
  }
}

POST /splitting1-001/_close

PUT splitting1-001/_settings
{
  "index": 
  {
    "number_of_routing_shards": 162
  }
}

POST /splitting1-001/_open

GET /splitting1-001/_settings

Result:

{
    ...
    "number_of_shards" : "6",
    "number_of_routing_shards" : "162",
    ...
}

PUT splitting1-001/_settings
{
  "index": 
  {
    "blocks.read_only": true
  }
}

POST /splitting1-001/_split/splitting1-001_split
{
  "settings": {
    "index.number_of_shards": 54
  }
}

Result:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "the number of routing shards [6] must be a multiple of the target shards [54]"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "the number of routing shards [6] must be a multiple of the target shards [54]"
  },
  "status" : 500
}

PUT /splitting2-001
{
  "settings": {
    "index": {
      "number_of_shards": 6
    }
  }
}

POST /splitting2-001/_close

PUT splitting2-001/_settings
{
  "index": 
  {
    "number_of_routing_shards": 162
  }
}

POST /splitting2-001/_open

GET /splitting2-001/_settings

Result:

{
    ...
    "number_of_shards" : "6",
    "number_of_routing_shards" : "162",
    ...
}

PUT splitting2-001/_settings
{
  "index": 
  {
    "blocks.read_only": true
  }
}

POST /splitting2-001/_split/splitting1-001_split
{
  "settings": {
    "index.number_of_shards": 54
  }
}

Result:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "the number of routing shards [768] must be a multiple of the target shards [54]"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "the number of routing shards [768] must be a multiple of the target shards [54]"
  },
  "status" : 500
}
```

This issue relates to #75137

**Comment by martijnvg** [comment]
If no `index.number_of_routing_shards` has been specified then logic inside the `MetadataCreateIndexService#getIndexNumberOfRoutingShards(...)` kicks and calculates a default based on number of primary shards use that as the true number of routing shards. If a value is specified (including `null`) then the value the true number of routing shards is determined from the `IndexMetadata.INDEX_NUMBER_OF_ROUTING_SHARDS_SETTING` setting and in the case of when `null` is specified then the default value is gathered from the `IndexMetadata.INDEX_NUMBER_OF_SHARDS_SETTING` setting. 

Whether no value or `null` is specified the same logic should be used and I think therefor the `MetadataCreateIndexService#getIndexNumberOfRoutingShards(...)` method should be changed to also check whether `null` has been specified for the `index.number_of_routing_shards`  setting.
