### ISSUE TITLE
_terms_enum does not work with CCS wildcard syntax

### ISSUE THREAD

**Issue by lukasolson** [elastic/elasticsearch#75152]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.0-BC1

**Description of the problem including expected versus actual behavior**:

When using the `_terms_enum` API with CCS, things seem to work until I start using wildcards (`*`) in the index name. I would expect it to work with wildcard syntax.

**Steps to reproduce**:

 1. Configure CCS with multiple clusters (all on same version, 7.14.0-BC1)
 2. Index data into multiple indices on both clusters than can be accessed using wildcards
 3. Query `*:*/_terms_enum/`

You'll get an error message that the index `*:*` doesn't exist.

**Example scenario**:

When I target specific indices using wildcard syntax, things work properly, however when I use wildcards in my index name (either before the `:` or afterwards), things fall apart:

Request:
```
POST /local:qbserve-2020-11-20/_terms_enum
{
  "field": "activity.source.keyword",
  "string": "",
  "index_filter": {
    "bool": {
      "must": [{
        "terms": {
          "_tier": ["data_hot", "data_warm", "data_content", "data_cold"]
        }
      }]
    }
  }
}
```

Response:
```
{
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "terms" : [
    "App",
    "Domain",
    "Slack",
    "Window"
  ],
  "complete" : true
}
```

(Querying `/remote:qbserve-2020-11-20/_terms_enum` gives the same response.)

However, when I change to either `/*:qbserve-2020-11-20/_terms_enum` or `/remote:qbserve-*/_terms_enum`, I get this error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [remote:qbserve-*]",
        "index_uuid" : "_na_",
        "index" : "remote:qbserve-*"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [remote:qbserve-*]",
    "index_uuid" : "_na_",
    "index" : "remote:qbserve-*"
  },
  "status" : 404
}
```

**Comment by bhavyarm** [comment]
Hey team - this is a blocker for this Kibana blocker - https://github.com/elastic/kibana/issues/104515 Thanks!
