### ISSUE TITLE
Finding documents with empty string as value

### ISSUE THREAD

**Issue by paulovictorv** [elastic/elasticsearch#7515]
Hello, 

I've been trying to find all documents that contains a field with an empty string value (```_textContent```) inside my index using the ```missing``` filter. But I think that this filter doesn't treat empty strings as a null value.

Is this a bug, or the intended behavior for this filter? If it is like this by design, may I suggest adding an ```empty``` filter, if that's even possible?

As a plus, I'll post the mapping that I'm currently using, the document that contains the empty string field and the query that I'm trying to run:

Mapping:
```json
{
  "documents": {
    "mappings": {
      "document": {
        "properties": {
          "_contratante": {
            "type": "string"
          },
          "_dateFields": {
            "type": "nested",
            "properties": {
              "id": {
                "type": "string",
                "index": "not_analyzed"
              },
              "value": {
                "type": "date",
                "format": "dateOptionalTime"
              }
            }
          },
          "_indexadoPor": {
            "type": "string"
          },
          "_textContent": {
            "type": "string"
          },
          "_textFields": {
            "type": "nested",
            "properties": {
              "id": {
                "type": "string",
                "index": "not_analyzed"
              },
              "value": {
                "type": "string"
              }
            }
          },
          "_tipoDocumento": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Document:

```json
{
  "_index": "documents",
  "_type": "document",
  "_id": "xxx",
  "_version": 1,
  "found": true,
  "_source": {
    "_id": "xxx",
    "_contratante": "xxx",
    "_tipoDocumento": "xxx",
    "_indexadoPor": "xxx",
    "_dateFields": [
      {
        "id": "538730ece4b0d13600208d7a:2",
        "value": 1404183600000
      }
    ],
    "_textFields": [
      {
        "id": "538730ece4b0d13600208d7a:0",
        "value": "xxx"
      },
      {
        "id": "538730ece4b0d13600208d7a:1",
        "value": "xxx"
      },
      {
        "id": "538730ece4b0d13600208d7a:3",
        "value": ""
      },
      {
        "id": "538730ece4b0d13600208d7a:4",
        "value": "xxxx"
      }
    ],
    "_textContent": ""
  }
}
```

Query:

```json
{
  "query": {
    "filtered": {
      "filter": {
        "missing": {
          "field": "_textContent"
        }
      }
    }
  }
}
```

Thanks a lot for the amazing tool developed here!

**Comment by clintongormley** [comment]
Here's a workaround:

    PUT t/t/1
    {
      "textContent": ""
    }
    
    PUT t/t/2
    {
      "textContent": "foo"
    }
    
    GET t/t/_search
    {
      "query": {
        "bool": {
          "must": [
            {
              "exists": {
                "field": "textContent"
              }
            }
          ],
          "must_not": [
            {
              "wildcard": {
                "textContent": "*"
              }
            }
          ]
        }
      }
    }

Not optimal, but it works

**Comment by davidhesson** [comment]
You're a life saver @clintongormley

**Comment by JnBrymn-EB** [comment]
I want to do the inverse of this:

```json
"query": {
  "bool": {
    "filter": {
      "wildcard": {
      "name": "*"
    }
  }
}
```

And it appears to work. Any document with a name matches and any doc with null or '' name does not match. But I don't know why it works! I thought that the wildcard filter expands * to some number of terms so that if I have, say, 9999 terms in the name field, if I index a document with name = "zzzzzzzzzzzzebra" then that will be well past the term expansion and it shouldn't match. But it does. Why?

Somehow I guess it's doing the `constant_score` thing [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-multi-term-rewrite.html) and it's using the variant that doesn't hit the 1024 clause error. But how does that work? How can you look up anything in the index w/o having a `should` clause with all the terms inside of it?

@clintongormley ?

**Comment by apuppy** [comment]
Now it's 2020. Still did not found a better solution for "field is not the empty string". 
Used the following solution, but is this the really good practice?
```
{
"wildcard":{"field_name":"*"}
}
```

**Comment by ViktorMasnyi** [comment]
hi, bool query with regexp works well for me

**Comment by ViktorMasnyi** [comment]
for example:
"query":{
    "bool":{
      "must_not": [
        {
          "regexp": {
            "yourFiledName.keyword": ""
          }
        }
      ]
    }
  },
