### ISSUE TITLE
The problems of memory of ES7.13

### ISSUE THREAD

**Issue by lichuandev** [elastic/elasticsearch#75163]
**Elasticsearch version** (`bin/elasticsearch --version`):7.13

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):WinServer 2008 R2 Enterprise

**Description of the problem including expected versus actual behavior**:

I use ES to store files, and the size of each file is within 100kb. The following two problems encountered in the use process have not been solved:
1.We set the requests cache: false, and the memory will still slowly reach 99%. Even if we only use -XHEAD to determine whether there is no other operations, the memory will be 99%. Is there any way to prevent the memory usage from being so high?
2.When we use the 7.4 version, although the memory is 99%, the system can still run normally for a long time, but the updated version after 7.13 will cause the system to fail to run because the memory is 100% every week. The high version cannot roll back the low version, so we are very painful and have to restart the service every two days.

**Provide logs (if relevant)**:

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
