### ISSUE TITLE
High CPU Usage of I/O dispather thread when using RestHighLevelClient (elasticsearch-rest-high-level-client 7.10) 

### ISSUE THREAD

**Issue by communityexplorer** [elastic/elasticsearch#75202]
RestHighLevelClient version: 7.10
when our application run some time later,  the CPU usage of some  I/O dispatcher threads reach always 100%, it seems didn't process any request, this is the thread dump:
![image](https://user-images.githubusercontent.com/45332912/125202305-9c9dca80-e2a5-11eb-8632-6b97c66ce9a8.png)

**Comment by NoSadness** [comment]
Hi, how did you solve this problem？

**Comment by nitishgoyal13** [comment]
Hi, Anyone able to find any work around this? We are facing similar issue where our application is always hitting 100% cpu utilisation
