### ISSUE TITLE
build the arm64 elasticsearch 6.8.17,then run failed

### ISSUE THREAD

**Issue by liyin37** [elastic/elasticsearch#75201]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.8.17

**Plugins installed**: []
no
**JVM version** (`java -version`):
OpenJDK15U-jdk_aarch64_linux_hotspot_15.0.1_9.tar.gz

**OS version** (`uname -a` if on a Unix-like system):
arm64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
docker build  arm64 images by https://github.com/elastic/dockerfiles/blob/6.8/elasticsearch/Dockerfile,the Dockerfile I only change the jdk version to arm64;
the old is :https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz
the new is: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_aarch64_linux_hotspot_15.0.1_9.tar.gz
 2.
then I build it in arm64 system
![image](https://user-images.githubusercontent.com/42507175/125197451-46725c80-e290-11eb-8223-db3d82c4c78c.png)

 3. the end,I run this images,the error have happend ,the error is below:
 [0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
[0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
Error: Could not find or load main class [0.003s][error][cds]
Caused by: java.lang.ClassNotFoundException: [0/003s][error][cds]

how to resovle it ,please help me?

 

**Provide logs (if relevant)**:

**Comment by liyin37** [comment]
when I try to  build the elasticsearch in ubuntu system，then I save the images and load it into the centos arm system,find the same errors ,how to resovle it ?

**Comment by droberts195** [comment]
The first changes to make Elasticsearch work on linux-aarch64 arrived in version 7.7.  GA support came in 7.12.

This is why version 6.8 does not work on linux-aarch64.

If you want to try creating your own 6.8 build that works, look at the PRs that made version 7.7 work: https://github.com/elastic/elasticsearch/pulls?q=is%3Apr+is%3Aclosed+aarch64+-label%3Abackport

But Elastic will never support running 6.8 on linux-aarch64.
