### ISSUE TITLE
Composite DateHistogram more like plain DateHistogram

### ISSUE THREAD

**Issue by xskerik** [elastic/elasticsearch#75256]
Hello there,

as a user of DateHistogram I am pretty happy with the functionality provided by this aggregation.
But time flies and  ranges go wide. To be able to paginate buckets becomes very essential.

What a surprise, after wrapping DateHistogram into Composite aggregation many things stop working.
These two features turned out to be a quite a problem. 

-   no empty buckets;
-   returning key not only as timestamp but key_as_string too.

Especially empty buckets because supporting Elasticsearch time interval calculation at client side is not so trivial.

I have found more requests (e.g.: ExtendedBound ). In the end it would be very nice to work with Composite DateHistogram in the same manner as with plain DateHistogram. 
What is worse, non of these drawbacks are explicitly mentioned in the doc.

**Comment by wchaparro** [comment]
Hey there  @xskerik can you provide us with more details about your use case? We're trying to understand better the context for this need so we can determine the best way to help you out. Thx

**Comment by wchaparro** [comment]
Closing, no feedback.
