### ISSUE TITLE
max_file_descriptors is reported as -1

### ISSUE THREAD

**Issue by Wilfred** [elastic/elasticsearch#7527]
I recently changed the maximum open file limit on my machine from 5,000 to 32,000. I did this by adding the following lines to `/etc/security/limits.conf`:

```
logstash	soft	nofile	32000
logstash	hard	nofile	32000
```

If I switch to this user, I do indeed get these limits:

```
$ ulimit -Sn
32000
$ ulimit -Hn
32000
```

However, after restarting the elasticsearch process, http://localhost:9200/_nodes?os=true&process=true&pretty=true displays the following:

```
      "process" : {
        "refresh_interval" : 1000,
        "id" : 27218,
        "max_file_descriptors" : -1,
        "mlockall" : false
      },
```

Should I be concerned? How can the maximum number be negative?

**Comment by styfle** [comment]
I see `"max_file_descriptors" : -1` running the following:

Windows Server 2012
Elasticsearch-1.7.2
Java 1.8.0_60-b27

Is this a problem?

**Comment by clintongormley** [comment]
@styfle no, it just means that we were unable to retrieve that value on windows.

@tlrx do you know if max_file_descriptors works on windows in 2.0?

**Comment by tlrx** [comment]
open/maximum files descriptors are not supported on Windows platforms, elasticsearch 2.0 will always return `-1`.

**Comment by clintongormley** [comment]
thanks @tlrx 

closing

**Comment by Wilfred** [comment]
> it just means that we were unable to retrieve that value

Is this documented anywhere? I was initially concerned when ES reported -1.

**Comment by tlrx** [comment]
It is documented for 2.0 (see https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-nodes-stats.html#process-stats) but it is not documented for previous versions.
