### ISSUE TITLE
High CPU Usage of I/O dispather thread when using RestHighLevelClient (elasticsearch-rest-high-level-client 7.10.2) 

### ISSUE THREAD

**Issue by communityexplorer** [elastic/elasticsearch#75356]
RestHighLevelClient version: 7.10.2
protocol:  TLS 1.3
when our application run some time later, the CPU usage of some I/O dispatcher threads reach always 100%, it seems didn't process any request, this is the thread dump:
![image](https://user-images.githubusercontent.com/45332912/125732032-ac33d12a-ccbc-45c8-ad92-419d2532bf78.png)

specially, when I use TLS 1.2，it seems no this problem. can you help to check, thank you?

**Comment by nitishgoyal13** [comment]
@communityexplorer Were you able to find any work around the same? Facing similar issue with 7.10.2 version of client

Anyone else aware if this issue is fixed in higher versions or any work around this? Kindly suggest

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
