### ISSUE TITLE
RestHighLevelClient disconnection issues

### ISSUE THREAD

**Issue by mariuszpala** [elastic/elasticsearch#75364]
Hi, we are using ES 7.10 and the same version of the Java client. 
In our app we have a single connection to ES established as below.

`RestHighLevelClient esClient = new RestHighLevelClient(RestClient.builder(new HttpHost(config.getElasticsearch().getHostname(), config.getElasticsearch().getPort(), config.getElasticsearch().getScheme())).setHttpClientConfigCallback(httpClientBuilder -> httpClientBuilder));
`

In production environment  with high concurrency the connection occasionally gets closed somehow and then we see a lot of errors like below. There are no errors prior to that stack trace so we have no idea why the connection gets closed. 
Anyway, I wonder how to make sure that the connection once disconnected gets connected automatically again.
Is there some API that can handle that automatically?
Also can you please change the error when connection is closed? Even if I call client.close() API, then any subsequence request to the ES throws the error below. Can you maybe change is to something more meaningful like "Connection closed"?

`java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:887)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1088)`

Thanks in advance for any help!
Mariusz

**Comment by vpsiddhant** [comment]
The reason for this exception is that you have not provided a exception handler to the ioreactor. If no exception handler is provided then for runtime exception and IOException the reactor stops by default. You need to give an handler and override the `handle` method to return `true` in case of a Runtime exception so that the IOReactor continuous when there is an Runtimeexception.

**Comment by mariuszpala** [comment]
Hi, can you please provide an example? Shouldn't the API by default return some user friendly message? Right now when I call client.close() and then all some API then I get that IO reactor message as well whether I'd expect rather "Your connection has been closed". Thank you

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by mariuszpala** [comment]
Hi, this is actually a feature request - Right now when I call client.close() and then all some API then I get that IO reactor message as well whether I'd expect rather "Your connection has been closed" and maybe client.isActive() or isConnected() API additionally, is it feasible?

**Comment by mariuszpala** [comment]
I get this exception not only on error but after regular client.close() call, so in my opinion this is a bug.

**Comment by DaveCTurner** [comment]
Your question indicates that you are misunderstanding how the client works and how to use it correctly. When used correctly I think the client already behaves as you suggest. Please continue this discussion on the forums. If it turns out that there is a bug in this area then we can reopen this issue.

**Comment by mariuszpala** [comment]
Hi Dave, let me explain the current behavior:

1. I setup a connection with ES - RestHighLevelClient - as `client`
2. I do a set of calls
3. Then I do call client.close();
4. Then any call to the `client` throws "java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED "

Nicely speaking this is counterintuitive, there should be a proper exception thrown saying that connection has been closed.

**Comment by DaveCTurner** [comment]
Once again I'm asking you to continue this discussion on the forums. This is not the right place for this kind of conversation, sorry.
