### ISSUE TITLE
[ML] Anomaly detection job stuck with `revert` block

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#75377]
Found in 7.14.0

**Description of the problem including expected versus actual behavior**:
This bug has been observed after a rolling upgrade from `7.13.4` to `7.14.0`. 

Summary of the situation post-upgrade:
* Job was interrupted by a rolling cluster upgrade while it was still processing historical data 
* ML upgrade mode was enabled before upgrading and disabled after for each node in the cluster
* No job state persisted
* Job ended up blocked with `revert`
* Task described in the `revert` block does not exist
* Job state is `closed`

The only way to recover from this state is to manually revert to the model snapshot with ID `empty`, which will remove the block from the job.

**Steps to reproduce**:
 1. Run an anomaly detection job that takes a long time to process historical data
 2. Disable replica shard allocation & enable ML upgrade mode
 3. Upgrade the node
 4. Enable replica shard allocation & disable ML upgrade mode
 5. Wait for cluster to recover
 6. Notice that anomaly detection job is `closed`, blocked by `revert` and no state is persisted.

⚠️ _Very low reproduction rate_

**Comment by droberts195** [comment]
> The only way to recover from this state is to manually revert to the model snapshot with ID `empty`, which will remove the block from the job.

It should also be possible to revert to the same model snapshot that the upgrade process was originally trying to revert to.  This will be much less disruptive, as the job will not have to re-learn from scratch.
