### ISSUE TITLE
Escaping index name when creating a snapshot

### ISSUE THREAD

**Issue by mateuszkaczynski** [elastic/elasticsearch#7540]
In some cases the index name might not play well with the file system of the snapshot repository. 

For example, trying to snapshot 'index_crawl:1' (which includes a colon) would fail in for plugins using URI-based filesystems (HDFS for example) due to filesystem restrictions.

**Comment by clintongormley** [comment]
@imotov is this already implemented, or do we still need to do it?

**Comment by imotov** [comment]
No, we will just use index name as is (which means we will only observe the index name restrictions).

**Comment by imotov** [comment]
This is getting addressed as part of a bigger changes in snapshot/restore file naming schema in #18156. So, I am going to close it here.
