### ISSUE TITLE
[ML][3rd Party Models] Restrict PyTorch models to loading singly per node

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#75411]
Memory usage peaks when a PyTorch model is loaded because a buffer is temporarily allocated to hold and reconstruct the model definition streamed from elasticsearch before it is loaded into LibTorch. That buffer is the same size as the model on disk so the peak memory required is `model file size + in memory representation size` until the temp buffer is freed and returned to the host. Shared libraries also contribute to the total memory used.  

PyTorch models should be loaded one at a time to prevent memory errors where the host has enough memory to run multiple models but not enough for the peak memory usage of multiple models. Accurate tracking of memory usage is a prerequisite for good model allocation and this is much easier to do with the guarantee that only one model is loaded at a time as the peak memory usage is more predictable.

**Comment by benwtrent** [comment]
FWIW, I think the model allocation service will end up doing this. It can get complicated trying to do this with persistent tasks and persistent tasks are not going to be the way forward.

**Comment by davidkyle** [comment]
Alternatively the [DeploymentManager](https://github.com/elastic/elasticsearch/blob/244a02978ab9076301129b2ac963b80ae13c0b41/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java#L59) is responsible for loading models the constraint could be enforced there by queuing model starts.

**Comment by dimitris-athanasiou** [comment]
@benwtrent Is this already the way the allocation service works?

**Comment by benwtrent** [comment]
Yes, this is the way it works, we can close this.
