### ISSUE TITLE
Jepsen transient failures under network partition conditions

### ISSUE THREAD

**Issue by pilvitaneli** [elastic/elasticsearch#7549]
Hi! Jepsen tests include five nemeses (test scenarios) that introduce different types of network partitions (see [here](http://aphyr.com/posts/317-call-me-maybe-elasticsearch)). The tests add documents to index before, during and after these partitions, and verify that the documents which were acknowledged during the partitions are retrievable afterwards. Sometimes the tests indicate that a number of documents were indexed, but are not retrievable---however, this does not happen on every run (of the same scenario). For example, in a run of 20 times each (against 598854dd72d7fb01a7e26a9dad065de3deaa5eb7), the following :lost-frac amounts were reported:

isolate-self-primaries-nemesis 244/361, 2/733, 1/607, 1/603, 1/213, 65/216 (and 14 times 0)
nemesis/partition-random-halves 1/355, 1/226, 4/733, 1/433 (and 16 times 0)
nemesis/partition-halves 1/65, 1/438, 4/715, 2/457, 6/731, 1/435, 9/433 (and 13 times 0)
nemesis/partitioner nemesis/bridge 2/415, 3/253, 2/383, 7/754, 1/786, 1/767 (and 14 times 0)
nemesis/partition-random-node does not report any lost documents.

In total, out of a 100 runs, 23 failed.

**Comment by dakrone** [comment]
Going to close this as it's been almost 2 years and we have a different issue we are tracking things for the 5.0 release - #20031
