### ISSUE TITLE
SQL: queries with GROUP BY always return a scroll cursor in REST API

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#75528]
For the request
```
http://localhost:9200/_sql
Content-Type: application/json

{
    "query": "SELECT gender FROM test_emp GROUP BY gender"
}
```
the response always includes a `cursor` despite the fact that the result set does not contain any more records:
```
{
  "columns": [
    {
      "name": "gender",
      "type": "keyword"
    }
  ],
  "rows": [
    [
      null
    ],
    [
      "F"
    ],
    [
      "M"
    ]
  ],
  "cursor": "u5mzAwFaAWMBCHRlc3RfZW1waQEBCWNvbXBvc2l0ZQdncm91cGJ5AAD/AQAINDA1MWRjOTABBmdlbmRlcgAAAQAA6AcBCgEINDA1MWRjOTAAAU0AAgEAAAAAAP////8PAAAAAAAAAAAAAAAAAVoDAAICAAAAAAAAAAAKAP////8PAQFrCDQwNTFkYzkwAAABAQA="
}
```

Fetching the cursor returns an empty result set:
```
http://localhost:9201/_sql
Content-Type: application/json

{
    "cursor": "u5mzAwFaAWMBCHRlc3RfZW1waQEBCWNvbXBvc2l0ZQdncm91cGJ5AAD/AQAINDA1MWRjOTABBmdlbmRlcgAAAQAA6AcBCgEINDA1MWRjOTAAAU0AAgEAAAAAAP////8PAAAAAAAAAAAAAAAAAVoDAAICAAAAAAAAAAAKAP////8PAQFrCDQwNTFkYzkwAAABAQA="
}
```
```
{
  "rows": []
}
```

Note, if using the `?format=txt` parameter, this reveals a subsequent bug as the empty response cannot be formatted:

```
http://localhost:9201/_sql?format=txt
Content-Type: application/json

{
    "cursor": "u5mzAwFaAWMBCHRlc3RfZW1waQEBCWNvbXBvc2l0ZQdncm91cGJ5AAD/AQAINDA1MWRjOTABBmdlbmRlcgAAAQAA6AcBCgEINDA1MWRjOTAAAU0AAgEAAAAAAP////8PAAAAAAAAAAAAAAAAAVoDAAICAAAAAAAAAAAKAP////8PAQFrCDQwNTFkYzkwAAABAQA="
}
```
```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Cannot find text formatter - this is likely a bug"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Cannot find text formatter - this is likely a bug"
  },
  "status": 500
}
```

**Comment by bpintea** [comment]
> the response always includes a cursor ...

The `always` bit might change if you add some filters.

> ...despite the fact that the result set does not contain any more records:

I believe the underlying comp aggs have this behaviour which SQL just passes on -- you could try "manual" paging with the translated DSL to observe it. Should be harmless, though.

>  if using the `?format=txt` parameter, this reveals a subsequent bug

This bit could be improved, I guess.

**Comment by Luegg** [comment]
> > the response always includes a cursor ...
> 
> The `always` bit might change if you add some filters.

Indeed, if the result set is empty, you're not getting a cursor.

> 
> > ...despite the fact that the result set does not contain any more records:
> 
> I believe the underlying comp aggs have this behaviour which SQL just passes on -- you could try "manual" paginating with the translated DSL to observe it. Should be harmless, though.

Yes, that's also what I observed. The comp agg always returns an `after_key` even if it's the last key. So it's probably not fixable without having some sort of "done" marker in the aggregation response.

Even if it is relatively harmless, I would still consider it a bug. After all, it can practically double the end to end query time for many queries if the user checks and follows the scroll cursors.

> 
> > if using the `?format=txt` parameter, this reveals a subsequent bug
> 
> This bit could be improved, I guess.

👍

**Comment by bpintea** [comment]
> it can practically double the end to end query time for many queries 

I'd expect that checking on a last "empty" cursor should be faster than getting a first non-empty aggs answer. But if network latencies are very high, your assumption could hold (though in that case the issue would no longer be the 2nd query).

> if the user checks and follows the scroll cursors.

The user should indeed always check, since only a request missing a cursor is a "final" answer.

> I would still consider it a bug.

Possibly, but then not an SQL one?
SQL could maybe do something about it (like prefetching), but at resources expenses, or a very large cursor. Which I suspect had been considered and rejected.

**Comment by Luegg** [comment]
Another partial fix would be to check whether the number of returned buckets is smaller than fetch_size. This would only leave the case where number of buckets is equal to fetch_size.
