### ISSUE TITLE
Same source node is appearing for Primary and Replica shards

### ISSUE THREAD

**Issue by prajwalgmpp** [elastic/elasticsearch#75537]
Scenario:

We have implemented ILM policy and have designated our data nodes as Hot and Warm.

When we move an index from Hot to Warm nodes manually, using the command:

`PUT <index_name>_settings
{
"index.routing.allocation.require.data": "warm"
}`

and monitor the progress through the command:

`GET _cat/recovery?v&s=stage:desc&h=index,shard,time,type,stage,source_node,target_node,bytes_percent`

we observe that for both the primary shard and the replica shard, the source node is appearing as the same node. In this case it is data-0
![image](https://user-images.githubusercontent.com/31845991/126345335-86ab1eb4-87c5-4c65-841a-9eddfe3e70c2.png)

This should not be the case since the primary and replica shards of a single index will not have the same source node.

I have tested this with Kibana 6.8 and 7.13.1.

However, the source nodes are accurately shown in the GUI of Kibana under Monitoring.

**Comment by DaveCTurner** [comment]
This looks correct, the `source_node` here means the node which holds the source of the recovery, i.e. the primary. If a shard has two ongoing recoveries at the same time then they'll both have the same `source_node`.

I'm closing this as it appears to be working as designed so no action is required, but please open a thread on the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) if you have any further questions.
