### ISSUE TITLE
Performance regression on aggs when top level query is single-node bool

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#75542]
@DJRickyB tracked down a performance regression on a sequence of aggs folks use to visualize logs. The rally configuration looks like this:

```
                "query": {
                  "bool": {
                    "must": [],
                    "filter": [
                      {
                        "match_all": {}
                      },
                      {
                        "range": {
                          "@timestamp": {
                            "gte": "2020-12-14T11:02:06.523Z",
                            "lte": "2020-12-15T11:02:06.523Z",
                            "format": "strict_date_optional_time"
                          }
                        }
                      }
                    ],
                    "should": [],
                    "must_not": []
                  }
                },
                "aggs": {
                  "ad64cabc-0bcf-4c39-ab6c-cedd90396a23": {
                    "terms": {
                      "field": "host.name",
                      "order": {
                        "_count": "desc"
                      },
                      "size": 5
                    },
                    "aggs": {
                      "97997d07-3f9f-424f-bb6d-9c698013e64f": {
                        "date_histogram": {
                          "field": "@timestamp",
                          "fixed_interval": "30m",
                          "time_zone": "UTC"
                        }
                      }
                    }
                  }
                }
```

It looks like #74260 slowed it down significantly. I'd test things like this locally when implementing #74260 and didn't see a regression, but the performance testing infrastructure is a lot better at tracking this sort of thing. I'll pick this up soon-ish. Probably not for a few days, but I would like to at least understand it more closely.

![image](https://user-images.githubusercontent.com/215970/126355069-bef2e99e-b91f-4a33-a64c-8abce17c001d.png)

We aren't going to revert #74260 because it is more important not to make complex queries much, much worse. But it is a real shame to have hit the 90% case as hard as we did. I don't imagine we'll have a fix for this regression in 7.14 either, sadly.

**Comment by jpountz** [comment]
Agreed not to revert #74260.

My expectation is that the top-level query rewrites to a `new BoostQuery(new ConstantScoreQuery(<range query on timestamp>))`, so I wonder if the cause of this regression is that the unwrapping logic in `QueryToFilterAdapter` doesn't unwrap `BoostQuery`, which prevents the date histogram from being considered as a candidate for filter-by-filter rewrite.

**Comment by nik9000** [comment]
> Agreed not to revert #74260.
> 
> My expectation is that the top-level query rewrites to a `new BoostQuery(new ConstantScoreQuery(<range query on timestamp>), 0)`, so I wonder if the cause of this regression is that the unwrapping logic in `QueryToFilterAdapter` doesn't unwrap `BoostQuery`, which prevents the date histogram from being considered as a candidate for filter-by-filter rewrite.

I finally picked this up. And, yeah, it's *exactly* what you thought - we don't unwrap the `BoostQuery`.
