### ISSUE TITLE
Add the ability to move index between different ILM phases easier

### ISSUE THREAD

**Issue by hungnguyen-elastic** [elastic/elasticsearch#75552]
Currently, if user would like to move an index from one ILM phase to a different phase, they would have to use the [API](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-move-to-step.html) which can be hard to use. It would be very useful and much better experience if user can do it through UI and is able to have a drop down, for example, to select the phase they would like to move the index to

<img width="1272" alt="Screen Shot 2021-07-20 at 4 25 08 PM" src="https://user-images.githubusercontent.com/70958189/126397667-f83f2a7d-f1ac-43e2-a58f-0ce47cd2db78.png">

**Comment by andreidan** [comment]
@hungnguyen-elastic thanks for logging this enhancement proposal. 

We recognised the API was difficult to use (it was designed like this as jumping steps manually is dangerous and should be an escape hatch only) so we made it more user friendly by not requiring the step name or action name to be specified. This enhancement will be available in `7.15` https://github.com/elastic/elasticsearch/pull/75435

As to an option in the UI for this, I'd recommend opening a proposal like this in the [kibana repo](https://github.com/elastic/kibana/issues/).

Feel free to reopen this issue in case there's more details or remaining issues.
