### ISSUE TITLE
[DOCS] Add filter example to  nested aggregation docs

### ISSUE THREAD

**Issue by biuabiu** [elastic/elasticsearch#75559]
[current-nested-aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-aggregations-bucket-nested-aggregation.html)

I think the following is more representative
[nested_aggs.txt](https://github.com/elastic/elasticsearch/files/6853286/nested_aggs.txt)

**Comment by biuabiu** [comment]
hi @jrodewig ,
Thank you for checking this issue,
1. when use nested filter companyB,the min_price  also is 350 ,this is wrong!  I think the current example is too simple and needs to be exemplified with actual scenario examples
2. The sample documents I provide can be used directly

**Comment by jrodewig** [comment]
> when use nested filter companyB,the min_price also is 350 ,this is wrong!

You can add a `filter` sub-aggregation to correctly filter data in the current example:

```
GET products/_search?size=0
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "name": "led tv"
          }
        }
      ]
    }
  },
  "aggs": {
    "resellers": {
      "nested": {
        "path": "resellers"
      },
      "aggs": {
        "filter_reseller": {
          "filter": {
            "bool": {
              "filter": [
                {
                  "match": {
                    "resellers.reseller": "companyB"
                  }
                }
              ]
            }
          },
          "aggs": {
            "min_price": {
              "min": {
                "field": "resellers.price"
              }
            }
          }
        }
      }
    }
  }
}
```

I can append this example agg search in the docs if wanted.

**Comment by biuabiu** [comment]
@jrodewig  Thanks ,That's great
