### ISSUE TITLE
MutualInformationTests.testBasicScoreProperties fails reproducibly

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#75561]
**Build scan**:
https://gradle-enterprise.elastic.co/s/5aulfo3ieqjn6

**Repro line**:
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.heuristic.MutualInformationTests.testBasicScoreProperties" -Dtests.seed=2036BFB6F863ADFE -Dtests.locale=fr-CA -Dtests.timezone=Australia/Darwin -Druntime.java=16 -Dtests.fips.enabled=true
fails for that seed only

**Reproduces locally?**:
yes
**Applicable branches**:
7.x
**Failure history**:

**Failure excerpt**:
```
06:39:44 org.elasticsearch.search.aggregations.bucket.terms.heuristic.MutualInformationTests > testBasicScoreProperties FAILED
06:39:44     java.lang.AssertionError: 
06:39:44     Expected: a value equal to or greater than <0.0>
06:39:44          but: <-0.46758255981716007> was less than <0.0>
06:39:44         at __randomizedtesting.SeedInfo.seed([2036BFB6F863ADFE:904D11FBE699F9BE]:0)
06:39:44         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
06:39:44         at org.junit.Assert.assertThat(Assert.java:956)
06:39:44         at org.junit.Assert.assertThat(Assert.java:923)
06:39:44         at org.elasticsearch.search.aggregations.bucket.terms.AbstractSignificanceHeuristicTests.testBasicScoreProperties(AbstractSignificanceHeuristicTests.java:150)
```

fails since 15th july
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(process.status),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:process.status,negate:!f,params:(query:FAILURE,type:phrase),type:phrase,value:FAILURE),query:(match:(process.status:(query:FAILURE,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'MutualInformationTests%20testBasicScoreProperties'),sort:!(process.time-start,desc))

**Comment by pgomulka** [comment]
more failures https://gradle-enterprise.elastic.co/s/offdtwuj6rhwo
also failing for ChiSquareTests
the bug might be in `AbstractSignificanceHeuristicTests.testBasicScoreProperties`

**Comment by benwtrent** [comment]
This will be fixed with: https://github.com/elastic/elasticsearch/pull/75452
