### ISSUE TITLE
A way to tell whether more buckets can be fetched with after_key in composite aggregation

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#75573]
The composite aggregation always returns an `after_key` even if it is the last key available and using it with `after` in a subsequent request would return an empty result.

As a result, clients do not always know whether another request is necessary to fetch remaining buckets and have to perform an unnecessary roundtrip to ES to complete the query (at least when number of buckets is equal to `size`). This problem also surfaces in https://github.com/elastic/elasticsearch/issues/75528

The problem could be addressed by adding a something like a `remaining_buckets` flag to the response:

```
{
  ...
  "aggregations": {
    "my_buckets": {
      "after_key": {
        "date": 1494288000000,
        "product": "mad max"
      },
      "remaining_buckets": false,
      "buckets": [
        ...
        {
          "key": {
            "date": 1494288000000,
            "product": "mad max"
          },
          "doc_count": 2
        }
      ]
    }
  }
}
```

**Comment by iansiple** [comment]
I am currently trying to implement this within the src code. I'm not sure how to go about it without searching the after key to see the size returned. Is there another way I'm not thinking of?

**Comment by wchaparro** [comment]
closing as not planned.
