### ISSUE TITLE
Document Security Attribute only supports "OR" Operator and there is a need for "AND" operator 

### ISSUE THREAD

**Issue by magetachew** [elastic/elasticsearch#75604]
So, we are trying to use Elastic Search for a large project but there is a need to apply Document Level Security.   looking at the documentation, that can be set with DLS that could be matched with user Security to grant access to the document.

Example - DOC1 has Security Attribute - "1, 2, 3"   / DOC2 has Security Attr - "2, 3"  / DOC3 has Security Attr- "3, 4, 5"
USER1 - Security Attr - "1, 2, 3"   USER2- Security Attr - "1, 2"  USER3- Security Attr - "2, 3"   , USER4- Security Attr - "1, 2, 3, 4" .
in our model ===> USER2 can not see all 3 documents.  USER1 can see Doc1 and Doc2  User3 can see DOC2 and user 4 can see all 4 documents.

in the current ELS ==> User 2 can see both DOC1 and DOC2 which breaks our model... and that is the reason for needing an "AND".

**Comment by tvernum** [comment]
@magetachew Based on what you've described here, I think you can solve this with a `terms_set` query. See: https://www.elastic.co/blog/attribute-based-access-control-elasticsearch

If I've misunderstood your problem, perhaps we can move this to [the forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). I think this is a matter of being able to produce an Elasticsearch query that covers the required use case, not a core gap in security features.

**Comment by Dinakar4323** [comment]
@tvernum The above security model that @magetachew mentioned is not achievable using the options mentioned in the above link. Can you please let us know, if there any other options/solutions

**Comment by tvernum** [comment]
Let's continue this [conversation in the forums](https://discuss.elastic.co/t/attribute-based-security/280592).

**Comment by tvernum** [comment]
Closing this issue because we do not have a clear, reproducible example of the gap in DLS behaviour.
