### ISSUE TITLE
Data missing when fetched from Mongo Database( 30 documents in mongodb but 29 were in the logstash. )

### ISSUE THREAD

**Issue by KUCHUSISI** [elastic/elasticsearch#75634]
input {
file {
path=>"/home/uvik-sisindri/files/files"
start_position => "beginning"
#ignore_older => 0 
sincedb_path => "/dev/nul
}
  mongodb {
#   codec => "json"
    uri => 'mongodb://localhost:27017/student'
    placeholder_db_dir => '/home/uvik-sisindri/logs/mongodb_logs'
    placeholder_db_name => "datalogstash_monogo_user20.db"
    collection => 'studen4'
    batch_size => 1
    generateId => 'true'
    parse_method => "simple"
  }
}
filter {
mutate {
#copy => { "_id" => "[@metadata][_id]"}
remove_field => ["_id"]
#remove_field => [ "host", "@version", "@timestamp", "logdate", "log_entry" ]
}
}
output {
  stdout {
   #codec => json
  # codec => rubydebug #outputs the same thing as elasticsearch in stdout to facilitate debugging
  }
  elasticsearch {
    hosts => ["http://localhost:9200"]
    loadbalance: true
    index => "std7-%{+YYYY.MM.dd}"
    document_type => "studen4"
  }
}

**Comment by tvernum** [comment]
This issue was not triaged at the time it was opened because the set of labels was modified from the defaults.
I don't think it's possible to diagnose the problem now, so I'm going to close it - if you still have an issue, please re-open and provide more details.
