### ISSUE TITLE
searchable-snapshots:qa:azure various tests

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#75648]
Not sure if this is just a temporary failure, or something must be done to fix it.

Affected tests:

- AzureSnapshotRepoTestKitIT
- AzureStorageCleanupThirdPartyTests
- AzureSearchableSnapshotsIT
- AzureRepositoriesMeteringIT

**Build scan**:
https://gradle-enterprise.elastic.co/s/zf3fsy7bw5wr4
https://gradle-enterprise.elastic.co/s/dkm4qbq6vccpq

**Repro line**:
./gradlew ':x-pack:plugin:searchable-snapshots:qa:azure:integTest' --tests "org.elasticsearch.xpack.searchablesnapshots.AzureSearchableSnapshotsIT.testClearCache" -Dtests.seed=2CD83CF739AF3A7C -Dtests.locale=nn-NO -Dtests.timezone=Asia/Srednekolymsk -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master, 7.13 and 7.14

**Failure history**:
12 times in the last 4 days

**Failure excerpt**:

{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] path [master_searchable_snapshots_tests_2CD83CF739AF3A7C] is not accessible on master node"}],"type":"repository_verification_exception","reason":"[repository] path [master_searchable_snapshots_tests_2CD83CF739AF3A7C] is not accessible on master node","caused_by":{"type":"blob_storage_exception","reason":"Status code 403, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7b5c0312-d01e-00ac-0f2f-7f9b96000000\nTime:2021-07-22T19:30:03.1626424Z</Message><AuthenticationErrorDetail>Signed expiry time [Tue, 20 Jul 2021 13:21:00 GMT] must be after signed start time [Thu, 22 Jul 2021 19:30:03 GMT]</AuthenticationErrorDetail></Error>\"","suppressed":[{"type":"exception","reason":"#block terminated with an error"}]}},"status":500}

**Comment by fcofdez** [comment]
I think the SAS token we were using in these QA tests is expired.

**Comment by valeriy42** [comment]
Another failure here https://gradle-enterprise.elastic.co/s/huk2u7q7g5era

**Comment by mark-vieira** [comment]
> I think the SAS token we were using in these QA tests is expired.

Who owns this? Do we need to request a new set of credentials from infra?

**Comment by fcofdez** [comment]
> Who owns this? Do we need to request a new set of credentials from infra?

Yes, it's infra. I've opened an issue requesting a credentials rotation 👍

**Comment by fcofdez** [comment]
The credentials were refreshed last 29th and the issue should be solved now.
