### ISSUE TITLE
How to set up X-pack on Elasticsearch-6.5.4

### ISSUE THREAD

**Issue by xujun738** [elastic/elasticsearch#75678]
How to set up X-pack on Elasticsearch-6.5.4,Ths anyway

**Comment by pugnascotia** [comment]
The instructions for setting up X-Pack for 6.5 are here:

https://www.elastic.co/guide/en/elasticsearch/reference/6.5/setup-xpack.html

If you have any problems following the documentation, please start a thread at https://discuss.elastic.co/.
