### ISSUE TITLE
cannot delete index

### ISSUE THREAD

**Issue by ghr111** [elastic/elasticsearch#75676]
**Elasticsearch version 7.4.1

**Plugins installed**: [Cerebro]

**JVM version 1.8.0_91 (`java -version`):

**OS version CentOs 3.10.0-327.28.3.el7.x86_64:

**Description of the problem including expected versus actual behavior**:
when the index settings get "blocks": {"read_only_allow_delete": "true"},I can't delete the index anyway ,error info is 
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[][indices:admin/delete]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Values less than -1 bytes are not supported: -2******b"
  },
  "status": 400
}

**Comment by tlrx** [comment]
@ghr111 Can you please provide the relevant Elasticsearch logs so that we can see the whole stack trace?

**Comment by henningandersen** [comment]
@ghr111 would you be able to do one or more of following:

1. Update to a more recent version of Elasticsearch and java to see if there is still an issue on recent versions?
2. Provide Elasticsearch log information from all nodes from a period when this occurred and provide a precise timestamp for when you did the operation.
3. Provide the response from deleting the index when [including `error_trace=true` as a query parameter to the delete request](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-error-options).

We need more information to effectively work this issue.

**Comment by tlrx** [comment]
No feedback since it was opened, I'm closing this issue. Please don't hesitate to reopen if needed
