### ISSUE TITLE
on multiple nodes cluster requests are not following round robin load balancing

### ISSUE THREAD

**Issue by solitudelad** [elastic/elasticsearch#75692]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.14

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

MacBook-Pro Darwin 20.3.0 Darwin Kernel Version 20.3.0: ; ~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

on multiple nodes cluster, requests are not following round-robin load balancing

all requests are served by the first host configured in the RestHighLevelClient

```
final RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(HttpHost.create("http://127.0.0.1:9200"),HttpHost.create("http://127.0.0.1:9201"), HttpHost.create("http://127.0.0.1:9202"))
```

The expectation is nodes which are provided in RestHighLevelClient, all requests from the client should be load balanced in round-robin strategy on configured healthy nodes

curl http://localhost:9200/_cluster/health

Response Host http://localhost:9200

curl http://localhost:9200/_cluster/health
Response Host http://localhost:9200

curl http://localhost:9200/_cluster/health
Response Host http://localhost:9200

As per round robing scheduling requests should be load balanced across nodes
Response should be

Response Host http://localhost:9200
Response Host http://localhost:9201 
Response Host http://localhost:9202

**Steps to reproduce**:

Setup a multinode elastic search cluster (3 nodes, 1 master 2 data nodes)
Build a RestHighLevelClient

```
final RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(HttpHost.create("http://127.0.0.1:9200"), HttpHost.create("http://127.0.0.1:9201"), HttpHost.create("http://127.0.0.1:9202"))
```

**Comment by swallez** [comment]
A possible cause for round-robin not working is that your application creates a new client for every request. The client should be a singleton object that is created during application startup and is reused for the application life time. This will also improve performance as the client is a heavyweight object that contains persistant network connections to the Elasticsearch cluster.
