### ISSUE TITLE
[Indexing] A network partition can cause in flight documents to be lost

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#7572]
This ticket is meant to capture an issue which was discovered as part of the work done in #7493 , which contains a [failing reproduction test](https://github.com/elasticsearch/elasticsearch/blob/596a4a073584c4262d574828c9caea35b5ed1de5/src/test/java/org/elasticsearch/discovery/DiscoveryWithServiceDisruptions.java#L375) with @awaitFix.

If a network partition separates a node from the master, there is some window of time before the node detects it. The length of the window is dependent on the type of the partition. This window is extremely small if a socket is broken. More adversarial partitions, for example, silently dropping requests without breaking the socket can take longer (up to 3x30s using current defaults).

If the node hosts a *primary* shard at the moment of partition, and ends up being isolated from the cluster (which could have resulted in Split Brain before), some documents that are being indexed into the primary *may* be lost if they fail to reach one of the allocated replicas  (due to the partition) and that replica is later promoted to primary by the master.

**Comment by shikhar** [comment]
linking #10708

**Comment by JeanFrancoisContour** [comment]
Since this issue is related to in-flight documents. Do you think there is a risk to loose existing document during primary shard relocation (cluster rebalancing after adding a new node for instance )?

**Comment by bleskes** [comment]
@JeanFrancoisContour this issue relates to documents that are wrongfully acked. I.e., ES acknowledge them but they didn't really reach all the replicas. They are lost when the primary is removed in favour of one of the other replica due to a network partition that isolates the primary. It should effect primary relocation. If you have issues there do please report by opening a different ticket.

**Comment by JeanFrancoisContour** [comment]
Ok thanks, so if we can afford to send data twice (same _id), in real time for the first event and a few hour later (bulk) for the second try, we are pretty confident in ES overall ?

**Comment by bleskes** [comment]
For the record, the majority of the work to fix this can be found at #14252
