### ISSUE TITLE
Warning headers are removed on any failure

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#75739]
Whenever a request fails, the previously emitted response header warnings are removed from a response.
This was intentionally done so that when authentication fails, there would be no warnings presented to a user.
However when a failure is not related to authentication, headers are removed as well.
I suspect this behaviour fails only when security is enabled 

introduced by https://github.com/elastic/elasticsearch/pull/64948

reproduction steps:
1. create an index
2. send a request that emits a warning and also fails. For instance a rest api compatible `typed` search endpoint - emits deprecation warning- and typed query - fails parsing.
3. ```curl --request GET \
  --url http://localhost:9200/test1/sometype/_search \
  --header ‘Accept: application/vnd.elasticsearch+json;compatible-with=7’ \
  --header ‘Authorization: Basic ZWxhc3RpYzpwYXNzd29yZA==’ \
  --header ‘Content-Type: application/vnd.elasticsearch+json;compatible-with=7’ \
  --header ‘X-Opaque-ID: he’ \
  --data ‘{
	“query”: {
		“type”:{
			“value”: “_doc”
		}
	}
}’
```
`Warning` headers are missing

**Comment by BigPandaToo** [comment]
While [adding a warning header when a license is about to expire](https://github.com/elastic/elasticsearch/pull/64948) we also removed all the warning headers from response if it fails when handling the request in `SecurityRestFilter`. But `SecurityRestFilter` handles all exceptions happening during the request including not security related.
We can limit warning headers filtering to only filter 401 (or 401 and 403) in `filterHeaders` like:
`if (headers.containsKey("Warning") && (restStatus == RestStatus.UNAUTHORIZED || restStatus == RestStatus.FORBIDDEN)) {...`

**Comment by tvernum** [comment]
@BigPandaToo Where did we get to with the fix for this?

**Comment by BigPandaToo** [comment]
> @BigPandaToo Where did we get to with the fix for this?

Adding test
