### ISSUE TITLE
invalid_shape_exception thrown despite ignore_malformed true for geo_shape

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#75753]
**Elasticsearch version** (`bin/elasticsearch --version`): `7.13.4`

**Plugins installed**: []

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): `20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

**Description of the problem including expected versus actual behavior**:

Submitting a `geo_shape` of `type: polygon` with an area of 0 results in a rejection despite having `ignore_malformed: true` in the mapping. The shape violates standards, but the document as a whole should still get indexed.

**Steps to reproduce**:
```
DELETE example

PUT example
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_shape",
        "ignore_malformed": true
      }
    }
  }
}

POST example/_doc
{
  "location": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
         12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ]
      ]
    ]
  }
}
```

Results in:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse",
    "caused_by" : {
      "type" : "invalid_shape_exception",
      "reason" : "Cannot determine orientation: signed area equal to 0. Points are collinear or polygon self-intersects."
    }
  },
  "status" : 400
}
```

Submitting a document where `location` is a `string` works as expected:

```
POST example/_doc
{
  "location": "hello world"
}
```

**Comment by imotov** [comment]
@iverase uniform handling of `ignore_malformed` is probably another thing that we should add to the technical debt backlog.

**Comment by iverase** [comment]
It makes sense
