### ISSUE TITLE
AzureStorageRepositoryClientYamlTestSuiteIT fails with: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] 

### ISSUE THREAD

**Issue by BigPandaToo** [elastic/elasticsearch#75777]
AzureStorageRepositoryClientYamlTestSuiteIT fails with: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] 

**Build scan**: 
https://gradle-enterprise.elastic.co/s/icskeofyvjcvk

**Repro line**:
./gradlew ':plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner' -Dtests.seed=1CD7D9C608F2425A -Dtests.class=org.elasticsearch.repositories.azure.AzureStorageRepositoryClientYamlTestSuiteIT -Dtests.method="test {yaml=repository_azure/10_repository/Register a repository with a non existing container}" -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=Africa/Addis_Ababa -Dcompiler.java=11 -Druntime.java=8

**Reproduces locally?**:
Didn't try

**Applicable branches**:
6.8

**Failure history**:
Fails regularly in 6.8  starting July 21st:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,stacktrace),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:AzureStorageRepositoryClientYamlTestSuiteIT),sort:!(time,desc))

**Failure excerpt**:
Failure at [repository_azure/10_repository:6]: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] path [6.8_integration_tests] is not accessible on master node","stack_trace":"RepositoryVerificationException[[repository] path [6.8_integration_tests] is not accessible on master node]; nested: IOException[Can not write blob master.dat]; nested: StorageException[Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.];

**Comment by DaveCTurner** [comment]
I think this duplicates https://github.com/elastic/elasticsearch/issues/75648: we're waiting on a new set of credentials.
