### ISSUE TITLE
[Transform] Checkpointing should not fail due to replica unavailability

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#75780]
When transform creates a checkpoint it uses the [index stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html) to get the global checkpoints for every shard. 

By design (of index stats) this call queries _every_ shard, including replica shards. Internally this information is de-duplicated and `max(gcp)` is taken.

Fleet implemented very similar functionality with the [_global checkpoints API_](https://www.elastic.co/guide/en/elasticsearch/reference/7.x//get-global-checkpoints.html). The implementation for it does **not** query replica shards and only collects the information that is required.

Transform can benefit from a similar implementation, if possible by re-using code/functionality.

This will make transform less likely to fail and reduce the amount of network calls for checkpointing by 50 or more percent.

**Comment by benwtrent** [comment]
Looking more into https://www.elastic.co/guide/en/elasticsearch/reference/7.14/get-global-checkpoints.html

It does seem to fit the bill. We could fairly easily expand the index patterns and send off individual requests for every index and then collapse the global checkpoints. 

This would be slightly more complicated than getting stats as that supports multiple indices, but not too much.

I have two open questions:

 - Mixed cluster support; how does this work against nodes that are <7.13?
 - Remote cluster support; does this work against remote clusters at all? I am assuming it definitely won't work against clusters with data nodes <7.13.
