### ISSUE TITLE
XDocsClientYamlTestSuiteIT fails with : element was a list, but [_shards] was not numeric

### ISSUE THREAD

**Issue by BigPandaToo** [elastic/elasticsearch#75791]
XDocsClientYamlTestSuiteIT fails with : element was a list, but [_shards] was not numeric

**Build scan**:
https://gradle-enterprise.elastic.co/s/ccvlp7dtlezvi

**Repro line**:
REPRODUCE WITH: ./gradlew ':x-pack:docs:integTest' --tests "org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT.test {yaml=en/security/securing-communications/update-tls-certificates/line_525}" -Dtests.seed=9EF27E3866A791EE -Dtests.locale=es-VE -Dtests.timezone=America/Atikokan -Druntime.java=11

**Reproduces locally?**:
Didn't try

**Applicable branches**:
master

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(branch,stacktrace),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:XDocsClientYamlTestSuiteIT),sort:!(time,desc))

**Failure excerpt**:
org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT > test {yaml=en/security/securing-communications/update-tls-certificates/line_525} FAILED |  
-- | --
  | java.lang.RuntimeException: Failure at [en/security/securing-communications/update-tls-certificates:57]: element was a list, but [_shards] was not numeric |  
  | at __randomizedtesting.SeedInfo.seed([9EF27E3866A791EE:16A641E2C85BFC16]:0) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:453) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428) |  
  | at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) |  
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  |   |  
  | Caused by: |  
  | java.lang.IllegalArgumentException: element was a list, but [_shards] was not numeric |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:111) |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:79) |  
  | at org.elasticsearch.test.rest.yaml.ClientYamlTestResponse.evaluate(ClientYamlTestResponse.java:166) |  
  | at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.response(ClientYamlTestExecutionContext.java:173) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.getActualValue(Assertion.java:55) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444) |  
  | ... 37 more |  
  |   |  
  | Caused by: |  
  | java.lang.NumberFormatException: For input string: "_shards" |  
  | at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) |  
  | at java.base/java.lang.Integer.parseInt(Integer.java:652) |  
  | at java.base/java.lang.Integer.valueOf(Integer.java:983) |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:109) |  
  | ... 43 more |  
  | REPRODUCE WITH: ./gradlew ':x-pack:docs:integTest' --tests "org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT.test {yaml=en/security/securing-communications/update-tls-certificates/line_525}" -Dtests.seed=9EF27E3866A791EE -Dtests.locale=es-VE -Dtests.timezone=America/Atikokan -Druntime.java=11 |  
  |   |  
  | org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT > test {yaml=en/security/securing-communications/update-tls-certificates/line_342} FAILED |  
  | java.lang.RuntimeException: Failure at [en/security/securing-communications/update-tls-certificates:43]: element was a list, but [_shards] was not numeric |  
  | at __randomizedtesting.SeedInfo.seed([9EF27E3866A791EE:16A641E2C85BFC16]:0) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:453) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428) |  
  | at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) |  
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  |   |  
  | Caused by: |  
  | java.lang.IllegalArgumentException: element was a list, but [_shards] was not numeric |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:111) |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:79) |  
  | at org.elasticsearch.test.rest.yaml.ClientYamlTestResponse.evaluate(ClientYamlTestResponse.java:166) |  
  | at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.response(ClientYamlTestExecutionContext.java:173) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.getActualValue(Assertion.java:55) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444) |  
  | ... 37 more |  
  |   |  
  | Caused by: |  
  | java.lang.NumberFormatException: For input string: "_shards" |  
  | at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) |  
  | at java.base/java.lang.Integer.parseInt(Integer.java:652) |  
  | at java.base/java.lang.Integer.valueOf(Integer.java:983) |  
  | at org.elasticsearch.test.rest.yaml.ObjectPath.evaluate(ObjectPath.java:109) |  
  | ... 43 more

**Comment by albertzaharovits** [comment]
I think this test failure refers to 
```
[source, console]
----
GET /_ssl/certificates
----
// TEST[skip:creates a lot of noise]
--
```
from https://raw.githubusercontent.com/elastic/elasticsearch/main/docs/reference/security/securing-communications/update-tls-certificates.asciidoc .
I'll label it as `low` priority because the test only checks that the `GET /_ssl/certificates` API returns _something_, and so muting only incurs the low risk that the API is completely broken.
