### ISSUE TITLE
Search - better caching logic for queries on wildcard field

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#75848]
A user reported slow performance with the new wildcard field which, oddly, was thousands of times faster when they ran the same query through a profiler.

The reason for the huge difference was revealed in a stack trace of the unprofiled query:

```
94.2% (4.7s out of 5s) cpu usage by thread 'elasticsearch[instance-0000000032][search][T#13]'
     6/10 snapshots sharing following 51 elements
       app//org.apache.lucene.util.compress.LZ4.decompress(LZ4.java:103)
       app//org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$BinaryDecoder.decode(Lucene80DocValuesProducer.java:856)
       app//org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$19.binaryValue(Lucene80DocValuesProducer.java:904)
       org.elasticsearch.xpack.wildcard.mapper.AutomatonQueryOnBinaryDv$1$1.matches(AutomatonQueryOnBinaryDv.java:56)
       app//org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:282)
       app//org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:232)
       app//org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
       app//org.apache.lucene.search.LRUQueryCache.cacheIntoBitSet(LRUQueryCache.java:503)
       app//org.apache.lucene.search.LRUQueryCache.cacheImpl(LRUQueryCache.java:494)
       app//org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight$1.get(LRUQueryCache.java:766)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:165)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:108)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:90)
       app//org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight$1.get(LRUQueryCache.java:765)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.opt(Boolean2ScorerSupplier.java:198)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:113)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:90)
```

There is query caching going on which is something that doesn't happen with profiled queries, hence the speed difference.

For some unknown reason the query caching logic in `LRUQueryCache.cacheIntoBitSet`  had singled out the very expensive `AutomatonQueryOnBinaryDv` normally used to verify a (hopefully) small set of docs that match an approximation query for wildcard/regex queries and decided to ask it to iterate across ALL docs in the index. This should not have happened - the LRUQueryCache should have [favoured](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/UsageTrackingQueryCachingPolicy.java#L130) caching the BooleanQuery that the wildcard field uses to contain both the approximation query and the expensive AutomatonQueryOnBinaryDv verifying query. I can't explain why this would happen other than a hashing collision or bug somewhere.
A safer approach that @jtibshirani suggested would be for the wildcard field not to rely on returning a BooleanQuery to combine verification and approximation queries and instead use a new custom query class  with a 2 phase iterator (like IndexOrDocValuesQuery) which would be opaque to the caching infrastructure and therefore it could never try use the expensive AutomatonQueryOnBinaryDv in isolation.

While it would be good to get to the bottom of why LRUQueryCache did what it did, the code is complex and Julie's suggestion is a safer way forward - regardless of how the caching logic may change in future.

**Comment by jpountz** [comment]
This sounds to me like a general problem with queries that operate on doc values, I'm afraid we'll see a similar problem with caching when we implement https://github.com/elastic/elasticsearch/issues/52728 and start creating queries on doc values that are not wrapped within an `IndexOrDocValuesQuery`.

There is another level of protection that we have via [`skipCacheFactor`](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.9.0/lucene/core/src/java/org/apache/lucene/search/LRUQueryCache.java#L760-L763), a parameter that prevents queries from being cached if their cost exceeds the cost of the top-level query times `skipCacheFactor`. The current value of this parameter is 250, maybe means that we allow caching clauses that are up to 250x more costly than the top-level query. Maybe this default is too high?

**Comment by markharwood** [comment]
>Maybe this default is too high?

These sort of settings feel brittle. Could we introduce a "boolean neverCache()" method on queries?
That feels cleaner than the alternatives: 
1) tweaking sensitive settings or
2) wrapping what would otherwise be BooleanQuerys (Julie's proposal) or
3) adding to "instanceof .." lists in LRUQueryCache.[shouldNeverCache](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/UsageTrackingQueryCachingPolicy.java#L55).

**Comment by jpountz** [comment]
> Could we introduce a "boolean neverCache()" method on queries?

We have `Weight#isCacheable` which allows disabling caching on queries already. One important difference with `LRUQueryCache#shouldNeverCache` is that `Weight#isCacheable` propagates to any query that wraps it. For instance if you have a `BooleanQuery` with N clauses and one of them returns false in `Weight#isCacheable` then the `BooleanQuery` will be considered not cacheable as well.

**Comment by markharwood** [comment]
Right. So maybe more of a "neverCacheInIsolation()" marker is required.

**Comment by jtibshirani** [comment]
> There is another level of protection that we have via skipCacheFactor... The current value of this parameter is 250, maybe means that we allow caching clauses that are up to 250x more costly than the top-level query. Maybe this default is too high?

The `skipCacheFactor` logic really seems like it was supposed to catch this and prevent the query from being cached. The default of 250 seems high to me too.

I agree this will be a problem when docvalue-only queries are widely used #52728. For the `wildcard` case in particular though, I thought it could make sense to restructure this as a single query containing both an approximation + verification step as we do in `SourceConfirmedTextQuery`. Using a `boolean` query feels surprising to me since the individual clauses don't really have meaning on their own. If it was a single query, it'd be very clear that it should be cached as a whole, and not its separate parts?

**Comment by markharwood** [comment]
> I thought it could make sense to restructure this as a single query containing both an approximation + verification step

Is that not a common enough pattern that we could provide a generic ApproximationPlusVerificationQuery that takes any two Query objects?

**Comment by jpountz** [comment]
> If it was a single query, it'd be very clear that it should be cached as a whole, and not its separate parts?

The combination of this idea plus decreasing the default value for the `skipCacheFactor` feels like it would put us in a better place. :+1:

> Is that not a common enough pattern that we could provide a generic ApproximationPlusVerificationQuery that takes any two Query objects?

We'd have at least `SourceConfirmedTextQuery` and this wildcard query that would fall into this category, so it looks worth exploring if there is code that can be reused indeed. We just need to make sure to call `query.createWeight(searcher)` like `IndexOrDocValuesQuery` rather than `searcher.createWeight(query)` so that the wrapped queries are not considered for caching on their own.
