### ISSUE TITLE
[7.13] Kibana surrounding documents seems to be limited at 50 documents

### ISSUE THREAD

**Issue by katagaStyle** [elastic/elasticsearch#75842]
Open surrounding document. Add 50 documents to the top. Your surrounding documents isn't visible anymore.
Surrounding documents shows always top 50 documents from top to bottom. All other documents are hidden. 
It seems that there is an hidden limit 50 documents.

**Comment by DJRickyB** [comment]
Hi @katagaStyle, please open any issues related to Kibana in [elastic/kibana](https://github.com/elastic/kibana/issues)
