### ISSUE TITLE
use ES_PLUGINS env variable to  Install external plugin to elastic docker at the time of start

### ISSUE THREAD

**Issue by AjayKumar4** [elastic/elasticsearch#75864]
As a User, I like to install list of external plugins before starting up the docker cluster.
use env variable ES_PLUGINS to assign list of plugin need to install at the time of start
first install list of plugin assign in env variable and then start the elastic docker

**Comment by jasontedor** [comment]
Relates #70219. I think that linked issue subsumes this issue here.

**Comment by pugnascotia** [comment]
Will be addressed more comprehensively by #70219.
