### ISSUE TITLE
Interval Usage In Java

### ISSUE THREAD

**Issue by YuLiGod** [elastic/elasticsearch#75867]
I wonder if the Java API of ES7 supports intervals usage

If you support it, please give me a place to view it. Thank you

**Comment by tvernum** [comment]
Hi, thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of conversations.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
