### ISSUE TITLE
Write system indices item for "what's new in 8.0"

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#75862]
Once system indices are hidden in 8.0, users may wonder where their `.security` and `.kibana` indices have gone.
* We should write up an explanation of what system indices are and which indices are likely to "disappear" from certain APIs.
* We also need to document that system indices may appear in `_cat` APIs but won't be available in HTTP index APIs.
* We will also advise users on how to snapshot and restore feature states.
* Whatever the relationship between system indices and index templates is, we should make sure it's well-understood.
* We need to provide guidance on diagnosing issues with system indices, for example, disk usage or readiness state.
* We should explain how to access system indices using a custom security role.
* We should document how system indices will be allocated with regard to data tiers and node roles.

**Comment by debadair** [comment]
Happy to help with this/review.

**Comment by rdnm** [comment]
Closing this issue as no longer required - 8.0 has been released, and the what's new section of the docs included a note on system indices.
