### ISSUE TITLE
Search profiling for fetch phases

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#75892]
I was helping some folks to debug a thing this morning and we had questions about the fetch performance and I was sad that we didn't profile the fetch phase. And I realized I had the *same* issue a week ago when I was helping some other folks. And I'd had the issue many more times before that.

Do folks think it'd be worth profiling the fetch phase?

I know a big chunk of the fetch phase is spent loading stored fields needed by the other phases. But I don't know how much of the time is that vs time spent chewing on the data or on docvalue_fields or whatever.

**Comment by jpountz** [comment]
> Do folks think it'd be worth profiling the fetch phase?

Totally. I think that the only reason why it's not done today is that the query phase is a more common bottleneck, but I remember seeing cases in the past when the fetch phase was a bottleneck too, so +1 to add profiling to the fetch phase.

**Comment by nik9000** [comment]
Cool. I have a prototype. I hope to have a PR today.
