### ISSUE TITLE
Some doubts about elasticsearch OSS

### ISSUE THREAD

**Issue by qiaofeng1227** [elastic/elasticsearch#75913]
1. If I want to set a password on elastic user，is it feasible to Install x-pack on elasticsearch-OSS 
2. The image on the dockhub  have no OSS type， but has both on elastic site. May I use a oss image on Dockhub？
https://hub.docker.com/_/elasticsearch（dockhub）
https://www.docker.elastic.co/r/elasticsearch（elastic site）
https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss（elastic site）

**Comment by pugnascotia** [comment]
Hello @qiaofeng1227. We use GitHub for tracking bugs and issues in Elasticsearch itself - your question is better suited to https://discuss.elastic.co/

To answer your questions:

   1. You can't install X-Pack in the OSS distribution. Instead you can use the default distribution of Elasticsearch for free, which includes security.
   2. DockerHub only hosts the default distribution. You can get an OSS distribution from [our own Docker registry](https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss) up to version 7.10. For more information, see https://www.elastic.co/blog/elastic-license-v2
