### ISSUE TITLE
[BUG] Unable to run gradle check

### ISSUE THREAD

**Issue by patriczek** [elastic/elasticsearch#76056]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14

**OS version** (`uname -a` if on a Unix-like system): Cent OS 7.7

**Description of the problem including expected versus actual behavior**:

 Task :build-conventions:compileJava FAILED
es/build-conventions/src/main/java/org/elasticsearch/gradle/internal/conventions/precommit/PrecommitTaskPlugin.java:36: error: cannot find symbol
            project.getExtensions().getByType(JavaPluginExtension.class).getSourceSets().all(sourceSet ->
                                                                        ^
  symbol:   method getSourceSets()
  location: interface JavaPluginExtension
Note: es/build-conventions/src/main/java/org/elasticsearch/gradle/internal/conventions/PublishPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

**Steps to reproduce**:
 `gradle check`

**Comment by pugnascotia** [comment]
@patriczek do you get the same error with the following?

`./gradlew check`

**Comment by breskeby** [comment]
As Rory mentioned you should always use the gradle wrapper (./gradlew) to build this project. Elasticsearch requires Gradle 7.1.1 to build these days. Using the wrapper always ensures you build with the correct gradle version

**Comment by patriczek** [comment]
Hi,

now it's running, sorry my bad, going to close the issue
