### ISSUE TITLE
Docker Image ARM64 seems to be broken since v7.10.2

### ISSUE THREAD

**Issue by awilhelmer** [elastic/elasticsearch#76077]
**Elasticsearch version** (`bin/elasticsearch --version`): 
docker.elastic.co/elasticsearch/elasticsearch > 7.10.1

**Description of the problem including expected versus actual behavior**:
Installation with official Helm Chart on a k3s cluster (with Raspberry 4 8GB ARM64) 
Docker Image 7.10.1 runs fine.
7.10.2: 
```
kubectl -n elastic logs  elasticsearch-master-0 -c configure-sysctl
standard_init_linux.go:228: exec user process caused: exec format error
```
7.13.4
```
 kubectl -n elastic logs  elasticsearch-master-0 -c configure-sysctl
sysctl: error while loading shared libraries: /lib64/liblzma.so.5: file too short
```
Deactivating configure-sysctl does not help. Same errors on startup.
```
sysctlInitContainer:
  enabled: false
```
**Steps to reproduce**:

 1. Install k3s on Raspberry 4 ARM64
 2. helm -n elastic install elasticsearch 
 3. Pod is in CrashLoopBackOff

**Provide logs (if relevant)**:

```
 kubectl -n elastic logs  elasticsearch-master-0 -c configure-sysctl
sysctl: error while loading shared libraries: /lib64/liblzma.so.5: file too short
```

**Comment by mark-vieira** [comment]
The errors sound suspiciously like it may be trying to run the x86 image. Have you tried running the later docker images directly? Perhaps something with k3s is not playing well with multiarch images.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode

**Comment by awilhelmer** [comment]
i already tried explicit tag "7.13.4-arm64" same error with same image digest...
v7.10.1 runs stable here.

**Comment by mark-vieira** [comment]
Have you attempted to do the install directly via `docker` commands w/o leveraging Helm? I'm just trying to confirm that k3s is indeed pulling the right image. Those errors are exactly what you'd see if you're trying to run an x86 image on an aarch64 platform so I'm still pretty sure it's pulling the wrong image. I'm able to run the 7.10.2 image on my ARM silicon mac w/o issue.

Doing `docker inspect [image hash]` should indicate the architecture.

```
        "Architecture": "arm64",
```

**Comment by awilhelmer** [comment]
You were right. With Docker-CE the image starts on Raspberry ARM64.
Weird, cause all the others (like ten other images) have no problems starting on k3s.
I will investigate this again more closely.

**Comment by awilhelmer** [comment]
Tested v7.140, works fine.
Issue can be closed, although I do not know what was the solution. Several images between version 7.11 and 7.13 didn't work

**Comment by pugnascotia** [comment]
@awilhelmer thanks for confirming. If you do find out more about what was happening, feel free to comment here.
