### ISSUE TITLE
The formula for calculating the shard which a document is routed in reference is wrong.

### ISSUE THREAD

**Issue by ViggoC** [elastic/elasticsearch#76072]
The formula for calculating the shard which a document is routed in reference is wrong. It does not match the actual calculation process in the code.

Formula in [reference](https://github.com/elastic/elasticsearch/blob/5baabff6670a8ed49297488ca8cac8ec12a2078d/docs/reference/mapping/fields/routing-field.asciidoc)
```
shard_num = hash(_routing) % num_primary_shards
```

Code 
```
indexMetaData.routingFactor = routingNumShards / numberOfShards;
Math.floorMod(hash, indexMetaData.getRoutingNumShards()) / indexMetaData.getRoutingFactor();
```

**Comment by jrodewig** [comment]
Thanks for raising this @ViggoC. I'm not sure we need the formulae here at all. It's probably enough to say that we use a hash of the document `_id` to route documents by default and that this evenly distributes documents among an index's shards.

**Comment by ViggoC** [comment]
@jrodewig Thank you for your response, I agree with your opinion that it's enough for some users. But I believe that a link to more detail about how the shard num is calculated will be helpful for senior user and developer. Maybe the information can be appended to where [index.number_of_routing_shards](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-split-index.html#split-index-api-desc) is mentioned.

**Comment by jrodewig** [comment]
Thanks for the feedback @ViggoC. I'll revise #76203 to update the formulae and cross-reference the settings involved. Thanks again for raising this.

**Comment by ViggoC** [comment]
:thumbsup:
