### ISSUE TITLE
OSS distribution is not valid flavor in Java REST High Level Client v7.14.0

### ISSUE THREAD

**Issue by ivanshautsou-gomel-iba-by** [elastic/elasticsearch#76091]
**Elasticsearch version**: 7.9.2 oss

**Plugins installed**: []

**JVM version** (`java -version`): 11

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**: It is impossible to perform any request to OSS elastic search due to broken version validation introduced in Java REST High Level Client v7.14.0. Here is the code: https://github.com/elastic/elasticsearch/blob/dd5a0a2acaa2045ff9624f3729fc8a6f40835aa1/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L2193

**Steps to reproduce**:

 1. Instantiate elasticsearch-oss;
 2. Use elasticsearch-rest-high-level-client version 7.14.0;
 3. Try to make any request to elastic using that library version;
 4. You got the error!

**Provide logs (if relevant)**:
```
Caused by: ElasticsearchException[Invalid or missing build flavor [oss]]
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2084)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1732)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1717)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
        at ...
```

**Comment by sethmlarson** [comment]
Quoting from [this comment thread](https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286):

> With the 7.11 the release of Elasticsearch, we will no longer be releasing oss-only distributions, as stated in the FAQ on license change. The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under Elastic License v2.

and it is [documented that the Java HLRC is forwards-compatible only](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html):

> The High Level Client is guaranteed to be able to communicate with any Elasticsearch node running on the same major version and greater or equal minor version. It doesn’t need to be in the same minor version as the Elasticsearch nodes it communicates with, as it is forward compatible meaning that it supports communicating with later versions of Elasticsearch than the one it was developed for.

So I would recommend upgrading to the [latest version of Elasticsearch](https://www.elastic.co/downloads/elasticsearch) and then upgrading the Java HLRC after that. Let me know if you have further questions about this.
