### ISSUE TITLE
Marvel Sense - allow different themes on panels

### ISSUE THREAD

**Issue by Jrizzi1** [elastic/elasticsearch#7612]
The original sense plugin had a light theme on the left hand coing panel, and a dark theme on the result right hand panel, currently marvel only lets you set a light or dark theme for both...suggestion is to allow setting themes on the individual panels

**Comment by clintongormley** [comment]
@simianhacker Does the new Marvel support light/dark theme?

**Comment by eskibars** [comment]
Given that "Sense" is no more and has moved into Kibana as "dev tools," with a different look and feel, I'm going to close this out.  If it's needed, I recommend re-opening in the Kibana repo
