### ISSUE TITLE
Test execution hangs when building Elasticsearch plugins and extending ESTestCase

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#76136]
When using the `elasticsearch.esplugin` plugin and writing test cases which extend from `ESTestCase`, Gradle test execution hangs. While troubleshooting this I recall running into the same issue when initially moving from the Ant test runner to Gradle and it stems from issues with security manager and `BootstrapForTesting`. We have to explicitly grant some permissions to Gradle worker code to please the security manager, if we don't, instead of an error, everything just grinds to a halt. We do this by injecting certain system properties, which are then referenced in the `gradle.policy` security policy. 

To reproduce simply checkout the `broken-build-7.14` branch of https://github.com/spinscale/elasticsearch-ingest-langdetect and run `./gradlew :test`.

Simply adding the following system properties (which we add in our `ElasticsearchTestBasePlugin` is enough to get test running.

```
test.systemProperties 'gradle.dist.lib': "${gradle.gradleHomeDir}/lib",
        'gradle.worker.jar': "${gradle.gradleUserHomeDir}/caches/${gradle.gradleVersion}/workerMain/gradle-worker.jar",
        'tests.gradle': 'true',
        'tests.task': test.path
```

We may want to move this stuff into a minimal plugin that's applied by `build-tools` as well as `build-tools-internal`.

**Comment by mark-vieira** [comment]
cc @spinscale

**Comment by breskeby** [comment]
From reading the descriptions, there are two issues here?
 
1. external third party plugins hang when extending EsTestCase
2. using EsTestCase in our build-tools / build-tools-internal isn't working

I don't see why 2) is a problem then. I'd suggest moving the tweak of the test system properties a minimal plugin that is used by the `esplugin` plugin.

**Comment by mark-vieira** [comment]
> using EsTestCase in our build-tools / build-tools-internal isn't working

I'm not sure what that means, I think as you say only the first issue is the problem.
