### ISSUE TITLE
Support for snake case in environment variables can lead to Elasticsearch nodes unable to boot on K8s

### ISSUE THREAD

**Issue by pebrc** [elastic/elasticsearch#76148]
**Elasticsearch version** 7.15.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:

We started testing ECK against 7.15 snapshots and it seems that https://github.com/elastic/elasticsearch/pull/74327 breaks our tests as we have called many test clusters `es-something`. ECK generates a Kubernetes service for each cluster to expose the Pods to clients and by convention uses the cluster name as part of the service name e.g. `es-something-http`.
 
Now Kubernetes [generates environment variables](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) of the form ES_SOMETHING from those services which will be present in any Pod.   Elasticsearch will pick those up and fail to boot as `ES_SOMTHING_HTTP` this is not a valid setting (I simplified the names a bit here just to convey the idea). 

We could now simply rename our test clusters and avoid naming things starting with `es-*` but I wonder if users will hit this too, once we ship 7.15 if they happen to have any Kubernetes services whose names start with `es-`

**Steps to reproduce**:

* create a simple ECK deployment of Elasticsearch 7.15.0 on a Kubernetes cluster of your choice e.g. 
```sh
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-quickstart
spec:
  version: 7.15.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
EOF
```

**Provide logs (if relevant)**:
From an actual e2e test run. Cluster was called `es-naming-xgqf-xxxxxxxxxxxxxxxxx` (not relevant to this issue but just to explain the funny name: this test case was testing max length validations on names )

```
java.lang.IllegalArgumentException: unknown setting [naming.xgqf.apm.xxxxxxxxxxxxxxxxx.apm.http.service.port.https] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

cc @pugnascotia

**Comment by pugnascotia** [comment]
@mark-vieira this behaviour in k8s seems opposed to the env var support we added in #74327. So far the only option I've thought of (short of removing the support) would be further proofing the env var handling by requiring that yet another env var be set first e.g. `ES_OPT_IN_TO_EXTENDED_ENV_VAR_HANDLING=1` or something equally unlikely to conflict with a container orchestrator.

I talked to @pebrc about https://github.com/elastic/cloud-on-k8s/issues/2030, which is relevant but of course not everyone is using ECK.

**Comment by mark-vieira** [comment]
I think another option is to use a more unique prefix that's unlikely to clash with existing environment variables.

**Comment by pugnascotia** [comment]
Maybe `ES_CFG_` isn't so bad after all 🤷

**Comment by mark-vieira** [comment]
Yeah, it's _ugly_ but at least it unblocks folks.
