### ISSUE TITLE
null_pointer_exception on GET _cat/snapshots when repository is not specified

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#76158]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): ESS

**Description of the problem including expected versus actual behavior**: 
According to the doc, the `<repository>` path parameter is optional when running `GET _cat/snapshots`.
https://www.elastic.co/guide/en/elasticsearch/reference/7.14/cat-snapshots.html
However when running `GET _cat/snapshots` without repository, it gives the following NPE:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot invoke \"String.indexOf(int)\" because \"str\" is null"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : "Cannot invoke \"String.indexOf(int)\" because \"str\" is null"
  },
  "status" : 500
}
```

**Comment by original-brownbear** [comment]
fixed via https://github.com/elastic/elasticsearch/pull/76161
