### ISSUE TITLE
Strange garbage collector behavior after upgrade from 7.10.2 (OSS) to 7.13.2

### ISSUE THREAD

**Issue by greenx** [elastic/elasticsearch#76183]
Hello!

On July 7, I upgraded several clusters from 7.10.2 (OSS) to 7.13.2.
At first it seemed that everything went well. However, later, errors began to pour. (not enough memory). At the same time, neither the load on the cluster, nor the application software changed. 

> {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [6188306006/5.7gb], which is larger than the limit of [6120328396/5.6gb], real usage: [6188305856/5.7gb], new bytes reserved: [150/150b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=150/150b, model_inference=0/0b, accounting=0/0b]
....
> 
Monitoring has shown that the "old" is constantly growing. 

![GS1s](https://user-images.githubusercontent.com/2979727/128377416-15a470c7-1837-40f4-ad2b-777221619189.png)

The strangest thing is that the heap grows most actively on the dedicated master server (red line). All traffic to the cluster goes only through this master server. This is done preferentially, since this is a test north and it’s easier to sort out problems by traffic. But, there is nothing to take up so much space. In our queries, there is not even aggregation, it only routes traffic to data nodes. 

I did a heap dump and it was over 6GB. VisualVM showed it to take up the most space:  transport.CopyBytesSocketChannel.
![sizes1](https://user-images.githubusercontent.com/2979727/128384668-9d4ea99c-f26d-464d-9384-761ea320f333.png)

And M.A.T. swore at x-pack.....HttpTransport
![mat](https://user-images.githubusercontent.com/2979727/128385436-6780d567-3df2-411d-8bc5-99d5168344fb.png)

Then I remembered that in the beginning there were still problems. Due to an error in the request, I flooded the cluster and put the monitoring system down. It turned out a lot of pairs of sockets, and somewhere between these versions, Elastic included the collection of HTTP connection statistics. 

To prevent this situation from happening again, I disabled the collection of these statistics: 
`http.client_stats.enabled: false`

I decided to check what's there now in these statistics: 
```
curl -s  http://localhost:9200/_nodes/stats|jq '.nodes[].http'
{
  "current_open": 19811,
  "total_opened": 19811,
  "clients": []
}
{
  "current_open": 8011,
  "total_opened": 8011,
  "clients": []
}
{
  "current_open": 8572,
  "total_opened": 8572,
  "clients": []
}

```
How! The number of current connections is equal to the total number of connections. This cluster has at best 5-10 simultaneous connections. IMHO, something, somewhere is clearly not released. In any case, they should not be equal. 

It seems that only statistics output is disabled, but it is still being collected. 
![mat2](https://user-images.githubusercontent.com/2979727/128488693-9ae74408-6671-428c-b5c8-9ac285f2cf1f.png)

P.S: The dump file remains, if you can tell me what else you can find useful from it, I will be grateful.

**Comment by DaveCTurner** [comment]
@greenx is it possible for you to share the heap dump with us? It's pretty much impossible for us to investigate things like this without being able to analyse the actual heap dump. I can arrange a private channel if needed.

The stats you quoted indicate that HTTP channels aren't being closed. It's possible that this is in Elasticsearch but also possible that your client is holding those thousands of channels open too. How have you ruled that out?

**Comment by DaveCTurner** [comment]
Actually we see the problem, it appears that setting `http.client_stats.enabled: false` can cause a HTTP connection leak. You can plug the leak by setting it back to the default.

**Comment by greenx** [comment]
@DaveCTurner 


The number of established connections is almost constant. 
![netstat](https://user-images.githubusercontent.com/2979727/128814704-b6d61431-28fd-4879-be68-fa4fde15dcf6.png)

**Comment by DaveCTurner** [comment]
Thanks @greenx, fortunately we spotted the problem without needing the heap dump and #76257 will fix it. In the meantime you should set `http.client_stats.enabled: true` to avoid the leak.

**Comment by greenx** [comment]
I described a problem due to which I had to disable statistics collection. Of course, we will rewrite the client part, but there is no software without errors and a similar situation may arise again. Therefore, I would prefer that the collection of HTTP connection statistics be disabled. Statistics are already collected in haproxy in front of ElasticSearch. #74964
