### ISSUE TITLE
path.data does not accept the legacy format with a comma-separated list for MDP anymore

### ISSUE THREAD

**Issue by rsommer** [elastic/elasticsearch#76181]
**Elasticsearch version**:
Version: 7.14.0, Build: default/deb/dd5a0a2acaa2045ff9624f3729fc8a6f40835aa1/2021-07-29T20:49:32.864135063Z, JVM: 16.0.1

**JVM version**:
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.12+7-post-Debian-2deb10u1, mixed mode, sharing)

**OS version**:
4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
We upgraded a cluster from 7.13.4 to 7.14.0. This cluster still uses the deprecated MDP path.data-feature and the old config format using just a comma-separated list as config value for path.data

```
path.data: /path/to/disk01,/path/to/disk02
```

Restarting under 7.14.0 yields just one data dir, not both as under 7.13.4.

**Comment by rsommer** [comment]
As a sidenote, this configuration format was once a recommended workaround: https://www.elastic.co/blog/multi-data-path-bug-in-elasticsearch-5-3-0

**Comment by gwbrown** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/71205.

@rjernst Looks like we might have broken this in 7.x - you might want to take a look, as I thought we didn't intend to remove support for this until 8.0.

**Comment by rsommer** [comment]
MDP still works if using the (newer?) config notation:
```
path:
  data:
    - /path/to/disk01
    - /path/to/disk02
```
but still, this seems to be a regression between 7.13.4 and 7.14.0.

**Comment by gboddin** [comment]
Can't believe this kind of changes makes it to stable.

Breaks infra on upgrade/install because in comma mode (`,`) elastic still starts and only uses the first element in the list.

**Comment by jeffkirk1** [comment]
I am experiencing the same problem, but I am using docker-compose.yml to supply the path.data definition, and the recommended YAML config for elasticsearch.yml won't work for me. I would greatly appreciate it if someone could supply a syntactically correct way to define this in docker-compose.yml.

**Comment by geekpete** [comment]
If you're using a docker configuration then any entries underneath an `environment` section that will be used as environment variables need to be dot notation strings rather than a yaml list, in the form of `key=value`. For the `path.data` [yaml list example above](https://github.com/elastic/elasticsearch/issues/76181#issuecomment-893605427) this needs to be a dot notation string for each list item, so you can use:

```
environment:
  - path.data.0=/path/to/disk01
  - path.data.1=/path/to/disk02
```

Also double check your spacing is correct when you update your configuration, especially indent/nesting levels/preceding spaces, as per standard yaml editing fun.

**Comment by jeffkirk1** [comment]
Thanks, geekpete, I was given similar info by Elastic support and my cluster is now back up and operational. I am not happy that this bug made it through testing, but I was very happy with Elastic's responsiveness and professionalism in finding the solution. I suffered no permanent data loss. Can't have a better outcome than that! Not so happy that I have to reconfigure my servers so I can't take advantage of distributing my I/O across my NVMe SSDs, but I can understand the reasons behind the multi data path feature being deprecated.

**Comment by rjernst** [comment]
This issue was fixed by https://github.com/elastic/elasticsearch/pull/76202 and should be out in 7.14.1

**Comment by rsommer** [comment]
Just rolled out 7.14.1, everything works as expected again. Thanks!
