### ISSUE TITLE
EQL sequence query returns inconsistent results

### ISSUE THREAD

**Issue by TonioRyo** [elastic/elasticsearch#76209]
**Elasticsearch version** (`bin/elasticsearch --version`): Elastic Cloud - 7.11.1

**Description of the problem including expected versus actual behavior**: When running an EQL sequence query, the results are inconsistent with the `join_keys` being switched between records: the first sequence result has a `join_keys` set to `user1@domain1.com` and contains documents with `user.email` set to `user2@domain2.com`, the second sequence result has a `join_keys` set to `user2@domain2.com` and contains documents with `user.email` set to `user1@domain1.com`.

**Steps to reproduce**:

 1. An index with HTTP access logs containing user emails to identify the users. Logs are parsed to ECS.
 2. Run the following EQL sequence query:
 ```
GET /my_index/_eql/search?filter_path=hits.sequences.join_keys,hits.sequences.events._source.@timestamp,hits.sequences.events._source.user.email,hits.sequences.events._source.source.ip
{
  "query": """
    sequence by user.email
      [ web where url.path == "/reset"]
      [ web where url.path: ("*download*") ] 
  """,
  "filter": {
    "bool": {
        "should": [
          {
            "match_phrase": {
              "user.email": "user1@domain1.com"
            }
          },
          {
            "match_phrase": {
              "user.email": "user2@domain2.com"
            }
          }
        ],
        "minimum_should_match": 1
      }
  },
  "size": 1000
}
 ```
 3. Check the results for `join_keys` and `user.email` values.

**Provide logs (if relevant)**:

Example of inconsistent results:
```
{
  "hits" : {
    "sequences" : [
      {
        "join_keys" : [
          "user1@domain1.com"
        ],
        "events" : [
          {
            "_source" : {
              "source" : {
                "ip" : "redacted"
              },
              "@timestamp" : "2021-04-16T00:02:07.970Z",
              "user" : {
                "email" : "user2@domain2.com"
              }
            }
          },
          {
            "_source" : {
              "source" : {
                "ip" : "redacted"
              },
              "@timestamp" : "2021-04-20T16:52:18.660Z",
              "user" : {
                "email" : "user2@domain2.com"
              }
            }
          }
        ]
      },
      {
        "join_keys" : [
          "user2@domain2.com"
        ],
        "events" : [
          {
            "_source" : {
              "source" : {
                "ip" : "redacted"
              },
              "@timestamp" : "2021-05-10T08:15:03.777Z",
              "user" : {
                "email" : "user1@domain1.com"
              }
            }
          },
          {
            "_source" : {
              "source" : {
                "ip" : "redacted"
              },
              "@timestamp" : "2021-05-10T08:17:03.559Z",
              "user" : {
                "email" : "user1@domain1.com"
              }
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by TonioRyo** [comment]
Discussion that was opened on Elastic's forum: https://discuss.elastic.co/t/eql-sequence-query-returns-strange-result/280082

**Comment by bpintea** [comment]
Can confirm the issue; the filtering is irrelevant. Depending on the query&results, this could be mitigated by changing/adding the `"result_position": "head"` [parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/eql-search-api.html#eql-search-api-request-body).
