### ISSUE TITLE
Elasticsearch 7.14.0: External plugin cannot run rest tests

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#76215]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.0

**Steps to reproduce**:

Trying to run an external plugin using the yaml rest tests does not work.

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/alr/devel/spinscale/elasticsearch-ingest-langdetect/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'ingest-langdetect'.
> Plugin with id 'elasticsearch.yaml-rest-test' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

You can run this branch to reproduce: https://github.com/spinscale/elasticsearch-ingest-langdetect/tree/broken-build-7.14

```
git clone https://github.com/spinscale/elasticsearch-ingest-langdetect.git
git checkout broken-build-7.14
./gradlew clean check
```

**Comment by breskeby** [comment]
After reworking the build tools project and explicitly declaring public and internal plugins (by _internal_ I mean plugins only supposed to be used by the elasticsearch build itself) we do not ship this plugin as part of build tools anymore. 
I will have a closer look on the `elasticsearch-ingest-langdetect` to see what other `internal` stuff is used there and discuss proceeding with the delivery team and come back to you

**Comment by breskeby** [comment]
After discussing with @mark-vieira I've raised a pr on the `elasticsearch-ingest-langdetect` project to fix this as we won't provider a general yaml rest test plugin for external plugin authors in the near future. see https://github.com/spinscale/elasticsearch-ingest-langdetect/pull/14
