### ISSUE TITLE
[DOC] default node roles

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#76266]
@robin13 @sophiec20 @lcawl, in https://github.com/elastic/elasticsearch/pull/66616#issuecomment-762382596 y'all determined to remove `By default, every node is a {ml} node.` from Elasticsearch Node docs ([7.10](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/modules-node.html) > [7.14](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html)). This removes the understanding of default settings unrelated to ML which was previously

> By default, a node is all of the following types: master-eligible, data, ingest, and (if available) machine learning.

This has caused user confusion in that it appears the default behavior still takes effect, but you may have/be removing it for 8.0. Can you provide context & expectations? They weren't covered in the referenced PR nor linked https://github.com/elastic/elasticsearch/pull/66533.

cc: @jrodewig

**Comment by lcawl** [comment]
I think the behaviour of `node.roles` has taken us quite a few clarification attempts, especially now that we're trying to write with a "Cloud first" point of view too. IMO the info starting with "If you don’t set node.roles, the node is assigned the following roles..." in https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-node.html#node-roles is clearer than the old "By default, a node is all of the following types...".

**Comment by stefnestor** [comment]
Ah, I see what you mean. I can buy in to that. Thanks for the response!
