### ISSUE TITLE
If size:0, automatically set search_type=count

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#7630]
In IRC we were discussing setting `size:0` for a query makes it faster.
@drewr mentioned:

```
drewr | [19:29:42] avleen Balthek: you should use search_type=count which would be even faster
drewr | [19:29:59] different code path
```

It would make sense that if someone does a query with `size:0`. that the search type should automatically get set to count, if the result is the same, and the latter is more performant.

**Comment by jpountz** [comment]
As far as I know `size=0` only has one drawback compared to `search_type=count`, which is that the search contexts are released in a second round-trip to all shards, while the `count` search type always releases the context at the end of the query phase. If the link between the machines is good, this second round-trip is super fast, which would explain why you did not see any difference.

But I agree we should merge the two. Having two ways to do the same thing is confusing (especially given that they're not equivalent).

A more pernicious difference is that some features like the shard query cache are only enabled with the `count` search type.
