### ISSUE TITLE
Native support for rolling index (aka Index Per Day)

### ISSUE THREAD

**Issue by ktonga** [elastic/elasticsearch#7631]
The Index per day is a very common pattern and widely used in projects with ES.
It's a ~~best~~ must practice by this days. Everybody is implementing it by hand, with hard to maintain and error-prone jobs or with extra hits to the cluster.

So it would be nice if it was implemented out of the box. It may be implemented as the well known rolling strategies of the logging frameworks. Something like this:

* Enabled in the index settings (available for using it in templates)
* The index name is just the base part of the final name
* A formatted date(time) is appended to the base name
* A date format could be specified but a default one is used otherwise
* A rolling period could be specified (30m, 6h, 2d). With default to 1d
* Every time a new index is rolled an alias to the base name is created

**Comment by tuckerpm** [comment]
Any chance you can provide insight as to what was discussed?

**Comment by Ghost93** [comment]
+1

**Comment by dakrone** [comment]
I believe we have this in 5.0 with the _rollover API so closing this, see https://github.com/elastic/elasticsearch/pull/18732
