### ISSUE TITLE
`_count` buckets_path syntax doesn't work with filters aggregation

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#76320]
When attempting to get `_count` via `bucket_selector.buckets_path`, I get a path validation error:

`"Invalid path element [filter_thing['phase_create']._count] in path [filter_thing['phase_create']._count]"`

It seems to me that since `filters` is a multi-bucket aggregation, and we are selecting a single bucket, accessing `_count` should be valid.

Here is a minimal repeatable code set:
```
PUT test_index
{
  "mappings": {
    "properties": {
      "special_id": {
        "type": "long"
      },
      "phase": {
        "type": "keyword"
      }
    }
  }
}

POST test_index/_bulk?refresh=true
{"index":{}}
{"special_id":1,"phase":"create"}
{"index":{}}
{"special_id":1,"phase":"update"}
{"index":{}}
{"special_id":2,"phase":"update"}
{"index":{}}
{"special_id":3,"phase":"create"}
{"index":{}}
{"special_id":3,"phase":"update"}


POST test_index/_search
{
  "size": 0,
  "aggs": {
    "All_IDs": {
      "terms": {
        "field": "special_id"
      },
      "aggs": {
        "filter_thing": {
          "filters": {
            "filters": {
              "phase_create": {
                "match": {
                  "phase": "create"
                }
              }
            }
          }
        },
        "select": {
          "bucket_selector": {
            "buckets_path": {
              "c": "filter_thing['phase_create']._count"
            },
            "script": "params.c==0"
          }
        }
      }
    }
  }
}
```

**Comment by wchaparro** [comment]
hey @benwtrent we've got some date-specific issues we're working on now, but after those are complete, we're planning to look into this issue.

**Comment by consulthys** [comment]
@wchaparro I encountered the same issue. Has there been any progress on this?

**Comment by benwtrent** [comment]
For what its worth @consulthys, the work around is to use a `value_count` sub-agg and filter on that. Which does feel redundant :)

**Comment by consulthys** [comment]
Thank you @benwtrent ! Totally redundant indeed, but that might do the job. I wish this would get prioritized and fixed 🤞

**Comment by wchaparro** [comment]
hey there @consulthys , we've prioritized, but there are other items that are higher precedence at this time. Its on our radar! :-)

**Comment by consulthys** [comment]
@wchaparro ! I'm sure there are tons of stuff of higher precedence 😉 I'm glad it's on your radar, though. Appreciate the feedback, thanks!!
