### ISSUE TITLE
Shard count recommendation does not apply to all use cases

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#76328]
https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#shard-count-recommendation

The above recommendation treats all shards as equal.  For use cases where there can be a lot of small/empty shards like Enterprise Search (depending the specific features being used), indices that are rarely used and are almost empty do not contribute to the heap usage much.  

I will suggest updating the above doc section to clarify that the recommendation assumes that shard sizes are 10-50G each as suggested in the [shard sizing recommendation](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#shard-size-recommendation) in the same guide.

**Comment by jrodewig** [comment]
In #76353, I proposed changing the related copy on this page to:

> If your shards are consistently between 10–50GB, we recommend limiting nodes to 20 shards or fewer per GB of heap memory.

@henningandersen commented:

> I think this suggests that with smaller shard sizes you could squeeze more shards. This might be true to some extent, but I think it depends on a variety of parameters and I am not sure that shard size is the main one (number of segments, number of fields etc.). I worry that loosening the description here could encourage some users to for instance use 200 shards / GB if they have 1 GB shards.

I agree that we want to avoid suggesting that you can squeeze in more shards per nodes based on size. We explicitly warn that even small shards have heap overhead earlier on the page.

Would it be enough to say that 20 shards/GB is not a hard limit and that some use cases, such as Enterprise Search, may be able to use more shards per GB of heap?

**Comment by jrodewig** [comment]
Tagging @giladgal for his input.

**Comment by giladgal** [comment]
@jrodewig Your suggestion sounds good to me. I would add that indices that are nearly empty and hardly used should not be taken into consideration. It's true that they have overhead but AFAIK it's very small and can be neglected. @henningandersen do you see this differently?

**Comment by ppf2** [comment]
So far, this has come up for Enterprise Search use case.  Since we have more internal testing related to shard sizes, perhaps for now we can simply update this section of the guide to indicate that if the use case is Enterprise Search (link to [Enterprise Search guide](https://www.elastic.co/guide/en/enterprise-search/current/index.html)), the nearly empty and hardly used _system_ indices do not factor into the shard sizing recommendation?

**Comment by henningandersen** [comment]
@giladgal I never investigated the overhead of small shards enough to really comment on that. But I am ok with the wording in the docs PR.
