### ISSUE TITLE
Elasticsearch hang os for seconds every two hours

### ISSUE THREAD

**Issue by psc0606** [elastic/elasticsearch#76331]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.1.1

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

JVM option:
```
/home/deploy/elasticsearch/ela.pid -Xms30g -Xmx30g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:G1ReservePercent=15 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/home/app_es/elasticsearch/logs/gc/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=32 -XX:GCLogFileSize=64m -XX:+PrintGCApplicationConcurrentTime -XX:+PrintSafepointStatistics -XX:PrintSafepointStatisticsCount=1 -XX:-UseBiasedLocking -XX:+SafepointTimeout -XX:SafepointTimeoutDelay=1000 -Dio.netty.allocator.type=pooled -Des.path.home=/home/deploy/search/app_es/elasticsearch-7.1.1 -Des.path.conf=/home/deploy/search/app_es/elasticsearch-7.1.1/config -Des.distribution.flavor=default -Des.distribution.
```

**OS version** (`uname -a` if on a Unix-like system):
free -g
```
             total       used       free     shared    buffers     cached
Mem:            62         61          1          0          0         22
-/+ buffers/cache:         38         24
Swap:            0          0          0
```

cat /etc/issue
```
CentOS release 6.8 (Final)
Kernel \r on an \m
```

uname -a
```
Linux bj7-search-app-es01.tencn 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

cat /proc/cpuinfo
[cpuinfo.txt](https://github.com/elastic/elasticsearch/files/6965538/cpuinfo.txt)

**Description of the problem including expected versus actual behavior**:
We have a cluster with 10 data nodes.  But the queries will be very slow(took time from es is  2~10 seconds) every two hours. These querying DSLs are very fast normally.  Every time it occurs, it will last for a few seconds with cpu suddently spike. 

Es cluster has 3 master and 10 data node, data-node-01:
![image](https://user-images.githubusercontent.com/7888889/128961957-b6d59006-4844-47b7-b5bf-9f7402d1dd18.png)

![image](https://user-images.githubusercontent.com/7888889/128962291-06d21f44-0a5f-4c13-a6f2-d07edc5a8fa3.png)
![image](https://user-images.githubusercontent.com/7888889/128962316-86344318-412a-44cd-9fa2-ae114d7b8b6e.png)
![image](https://user-images.githubusercontent.com/7888889/128962339-2227487d-61ae-459a-8029-6d33be334674.png)
![image](https://user-images.githubusercontent.com/7888889/128962361-7fed21c4-5c9f-4fc8-b750-75ae4d219d0d.png)

From es slow log:
![image](https://user-images.githubusercontent.com/7888889/128962561-fc2ccbf1-ecc3-4732-9185-ef99a01ffdb6.png)

Can not find any exception in es log and kernerl log.
- No abnormal gc activatity.
- No index request and search request  spike every two hours.
- Ca not get any useful hot threads when the cpu suddenly spike, beacuse the system was hung.
- I use many tools to catch useful infomation when the cpu suddenly spike：

dstat:
![image](https://user-images.githubusercontent.com/7888889/128963244-ba805ed0-4540-4625-b415-a5ecfdea3447.png)

vmstat:
![image](https://user-images.githubusercontent.com/7888889/128963270-15d1a5de-f606-4cc1-94ae-fdc680d78f2d.png)

top -d 1:
![image](https://user-images.githubusercontent.com/7888889/128963377-f5debaeb-c289-40f5-91f4-7f865b38a410.png)
The `top` hang for 6 seconds, then:
![image](https://user-images.githubusercontent.com/7888889/128963400-858a8782-612b-4fe1-bf12-11ed91516332.png)

simple shell script:
```
#!/bin/bash
while true; do echo `date`; sleep 1.0; done
```
![image](https://user-images.githubusercontent.com/7888889/128963532-2f5130f7-74c3-4a38-8024-6840e69ecb1b.png)
The echo cmd hung for seconds.

perf:
![image](https://user-images.githubusercontent.com/7888889/128963815-52f22f4e-2153-4c21-96e1-ee2d55e633f8.png)
![image](https://user-images.githubusercontent.com/7888889/128964170-9f44c2f8-f63c-44df-9c7c-568db9d12b77.png)
Just find  kernel _spin_lock eat most cpu, but I do thinks it is the root cause. I guess it is much more like the elasticsearch java proess hung for seconds and then wake up to process queued requests to cause cpu high.

But why elasticseach cause system pasued for seconds every two hours?  Can someone help me?

update: 
we have two es cluster, but both of two have this problem. If we drop the index and create a new one, the the problem will temporary disappear for hours, but it will reproduce after running for one or two days.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by pugnascotia** [comment]
Hello @psc0606. We use GitHub for tracking bugs and issues in Elasticsearch itself. It's not clear in this case that Elasticsearch is the problem - the JVM is ancient, and there could be other environmental factors causing stress to your system. I think the best option here is for you to start a thread on the [discussion forum](https://discuss.elastic.co/). I hope you don't mind if I close this issue in the meantime.

**Comment by psc0606** [comment]
Update: 
solved this strange problem by upgrading kernel to CentOs 7.2.
