### ISSUE TITLE
Add indexCreated flag to IndexResponse action

### ISSUE THREAD

**Issue by ktonga** [elastic/elasticsearch#7634]
It would be really useful to know if a new index was automatically created after performing an index action. It'd be a much better way to trigger some task, such as alias creation or doing some caching, than cronning jobs.

**Comment by fjarrett** [comment]
+1 Yes! This would be extremely useful.

**Comment by clintongormley** [comment]
This should be simpler than having to pass back this flag...  Closing in favour of #7631

**Comment by Ghost93** [comment]
+1

**Comment by andrewkcarter** [comment]
+1
