### ISSUE TITLE
SearchSourceBuilder documentation is inaccurate

### ISSUE THREAD

**Issue by imavroukakis** [elastic/elasticsearch#76408]
**Description of the problem including expected versus actual behavior**:

`SearchSourceBuilder` documentation for the `from` method (https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L362) states:

>   /**
     * From index to start the search from. Defaults to {@code 0}.
     * Must be a positive value or 0.
     */ 

However the variable's value is initialised as `-1` here https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L138

I expect that the variable's initial value should conform to the documentation or vice versa.

**Comment by imavroukakis** [comment]
> `-1` is used internally to indicate that the user didn't set an explicit value. We don't need to expose the internals here, the default value for users is `10`, not 0 or -1 ;).

So the doc is incorrect anyway ? :-)

**Comment by javanna** [comment]
I had a look, @jimczi mentioned the default for `size`, but @imavroukakis was talking about the default for `from`. The default `size` is `10` and it's correctly mentioned in the javadocs. The default `from` is `0` and it's correctly mentioned in the javadocs. The fact that they are both initialized to `-1` is an internal detail to signal that they were not set, in which case `0` and `10` will still be used. Closing.
