### ISSUE TITLE
CBOR: Improve recognition of CBOR data format

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#7640]
Currently we only check if the first byte of the body is a `BYTE_OBJECT_INDEFINITE` to determine whether the content is CBOR or not.  However, what we should actually do is to check whether the "major type" is an object.

See:

* https://github.com/FasterXML/jackson-dataformat-cbor/blob/master/src/main/java/com/fasterxml/jackson/dataformat/cbor/CBORParser.java#L614
* https://github.com/FasterXML/jackson-dataformat-cbor/blob/master/src/main/java/com/fasterxml/jackson/dataformat/cbor/CBORParser.java#L682

Also, CBOR can be prefixed with a self-identifying tag, `0xd9d9f7`,  which we should check for as well.  Currently Jackson doesn't recognise this tag, but it looks like that will change in the future: https://github.com/FasterXML/jackson-dataformat-cbor/issues/6

**Comment by johnrfrank** [comment]
@clintongormley it'd be great to have this feature.  What are the chances this will get into an upcoming release of Elasticsearch?

**Comment by nik9000** [comment]
@johnrfrank this was merged into 2.0.0. We've since deprecated content detection in favor of providing a content-type header.
