### ISSUE TITLE
[Transform] Preview should work against an existing id

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#76427]
If a continuous transform has failed, it is a useful troubleshooting step to be able to preview it. This gives confidence that the underlying source data has not dramatically changed. [could have]

Currently the `_preview` only works against a supplied configuration. It would be good to extend this to allow it to run against an existing transform.

Other side benefits: The UI already does this, so would benefit from code simplification. And it would be consistent with datafeed preview.

**Comment by droberts195** [comment]
This was implemented by #76697
