### ISSUE TITLE
maxSize must be >= 0 and < 2147483631; got: 2147483647"

### ISSUE THREAD

**Issue by deathcave** [elastic/elasticsearch#76492]
**17.14.0** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**Linux  4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux** (`uname -a` if on a Unix-like system):

**Throwing error search_phase_execution_exception**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"maxSize must be >= 0 and < 2147483631; got: 2147483647"}},"status":400}**:

**Comment by HaoPV-HPT** [comment]
+1, I'm having same problem

**Comment by haodketernal** [comment]
+1, I'm having same problem

**Comment by pugnascotia** [comment]
@deathcave can you please give us more information about what operation triggered the problem? Please also check in the Elasticsearch log for any relevant exceptions, and include them here in full.

**Comment by nik9000** [comment]
Luckily I can reproduce this with something simple:
```
curl -XDELETE -uelastic:password localhost:9200/test
curl -XPOST   -uelastic:password -HContent-Type:application/json localhost:9200/test/_bulk?refresh -d'
{"index": {}}
{"a": "foo"}
{"index": {}}
{"a": "bar"}
'

curl -XPOST   -uelastic:password -HContent-Type:application/json 'localhost:9200/test/_search?pretty&error_trace' -d'{
  "aggs": {
    "t": {
      "terms": {
        "field": "a.keyword",
        "size": 2147483647
      }
    }
  }
}'
```

So we don't have to do another back and forth asking for reproduction steps.

**Comment by nik9000** [comment]
This was caused by me in #74096. It intentionally skips building the (potentially) long list of results, instead building a priority queue to hold the results so we can skip as we go. That's all well and good, but in your case you get far fewer results than the you request. This used to work because you ended up with a short-ish list and built the queue of exactly that size. You set the size to max_int, presumably because you wanted Elasticsearch to get as many terms as it could or die trying.

I believe I can revive the old behavior.

**Comment by nik9000** [comment]
Opened #76578 which should get you back the old behavior and preserve all of the optimization gained in #74096.
