### ISSUE TITLE
Enhance diagnosis of cluster state operations

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#76625]
Inside of Elasticsearch, we would like to be able to support large numbers of indices and shards so that we can accommodate "daily" indices.

To accomplish this, we'd like to have a bit more visibility into the types and lengths of operations occurring with cluster state. Specifically, it would be great if we had:
- metrics around the time it takes to compute the new cluster state output on the master node (reroute, etc)
- metrics around the "sharing" of the cluster state (publish time, etc)
- metrics around how long the cluster state takes to apply

Additionally, it would be great (but certainly not required) if we could tell how big each of the pieces of cluster state is, and how much of our cluster state diffing functionality is being used (or not used) for each cluster state update.

**Comment by DaveCTurner** [comment]
Some more detailed design thoughts: I think we want to track the cumulative time spent in the following places on each node:

- `MasterService#calculateTaskOutputs`, which represents how long it took to compute the cluster state (rerouting etc).
- `MasterService#publish`, which represents how long it took to publish the cluster state (including applying it everywhere).
- Each step in `ClusterApplierService#applyChanges`, which represents how long it took to apply the cluster state and notify listeners.
- `PublicationTransportHandler#newPublicationContext`, which represents the cluster state diff computation.
- `CoordinatorPublication` constructs an `AckListener` whose `onCommit` method receives the time spent waiting for a majority of masters to persist and ack the new cluster state, we should accumulate that.
- We could perhaps track how long the master spends waiting for all the other nodes to apply their state (it doesn't start applying its local state until after everyone else) - `Publication#startTime` is the start time and the end occurs when we call `CoordinatorPublication#onCompletion`.

Also we could track the number of elections that the `Coordinator` starts, and the cumulative number of bytes that the `PublicationTransportHandler` buffers (both up-front and ad-hoc) and sends.

Then it's a question of exposing these data in stats. `Coordinator` and `PublicationTransportHandler` already have plumbing into the stats subsystem, and `Coordinator` holds references to `MasterService` and a `ClusterApplier` that's really the `ClusterApplierService` so I reckon we can consolidate all this stuff into the discovery stats object in the `Coordinator`.

**Comment by DaveCTurner** [comment]
We added some subset of the suggested stats as part of #77466 and I think that's been enough to help us understand the bottlenecks. We're not planning on doing anything else in this area so I'm closing this.
