### ISSUE TITLE
`close_notify` not sent when incoming connection is half-closed and quiescent when using TLS1.3

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#76642]
**Elasticsearch version** (`bin/elasticsearch --version`): confirmed in 7.14.0, likely others

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): confirmed on Mac, likely others

**Description of the problem including expected versus actual behavior**:

When closing an incoming connection that was using TLS1.3 the remote end sends a `close_notify` alert and may then wait for Elasticsearch to indicate there's no more data to receive with its own `close_notify` before starting to tear down the underlying TCP connection. However Elasticsearch does not send a `close_notify` even if it's finished responding to every request on the channel, so the client may wait forever.

This only seems to happen with TLS1.3 due to a change in the spec vs earlier versions, see https://datatracker.ietf.org/doc/html/rfc8446#section-6.1:

>   Each party MUST send a "close_notify" alert before closing its write
>   side of the connection, unless it has already sent some error alert.
>   This does not have any effect on its read side of the connection.
>   Note that this is a change from versions of TLS prior to TLS 1.3 in
>   which implementations were required to react to a "close_notify" by
>   discarding pending writes and sending an immediate "close_notify"
>   alert of their own.  That previous requirement could cause truncation
>   in the read side.  Both parties need not wait to receive a
>   "close_notify" alert before closing their read side of the
>   connection, though doing so would introduce the possibility of
>   truncation.

In particular with TLS1.2 and earlier we react with an immediate `close_notify` even if there's still data to send on the channel.

I expect this happens with transport connections too, but I've only confirmed it for HTTPS ones.

**Steps to reproduce**:

1. Connect to the HTTPS port and complete a TLS1.3 handshake.
2. Optionally perform some HTTP requests and receive the responses.
3. Close the TLS context with a `close_notify` message.
4. Observe that no `close_notify` message is returned.

**Provide logs (if relevant)**:

Here's a packet capture of an example session: [tls1.3.pcapng.gz](https://github.com/elastic/elasticsearch/files/7006162/tls1.3.pcapng.gz)

At t=0s we open the connection; at t=1s we do the TLS handshake; at t=2s we do a HTTP request and get a response, at t=3s we send the `close_notify` but get no response until at t=4s we just drop the connection.

**Comment by arteam** [comment]
@DaveCTurner Would it possible to bring back the TLS1.2 behaviour with the `jdk.tls.acknowledgeCloseNotify` system property?
https://bugs.openjdk.java.net/browse/JDK-8208526?subTaskView=all
https://stackoverflow.com/questions/54687831/changes-in-sslengine-usage-when-going-up-to-tlsv1-3

**Comment by DaveCTurner** [comment]
It is _possible_ but it's not great, the whole point of this change in TLS1.3 is to avoid the possible truncation that might happen in TLS1.2 if the `close_notify` is sent while there's still responses pending. Bringing back that behaviour isn't the right solution IMO.

**Comment by DaveCTurner** [comment]
I investigated this a bit further and discovered that `io.netty.handler.ssl.SslHandler#sslCloseFuture()` exposes a future which is completed on receipt of a `close_notify` from the peer. Today we don't subscribe to this future, but I believe we should do, so I think that's the bug.

This technically affects inbound and outbound transport connections as well as inbound HTTP connections. We don't really have a notion of gracefully closing a transport connection so I think we could reasonably just close the channel straight away:

```diff
diff --git a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/core/security/transport/netty4/SecurityNetty4Transport.java b/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/core/security/transport/netty4/SecurityNetty4Transport.java
index 02533a97e61..cb3393f9503 100644
--- a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/core/security/transport/netty4/SecurityNetty4Transport.java
+++ b/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/core/security/transport/netty4/SecurityNetty4Transport.java
@@ -137,6 +137,7 @@ public class SecurityNetty4Transport extends Netty4Transport {
             serverEngine.setUseClientMode(false);
             final SslHandler sslHandler = new SslHandler(serverEngine);
             ch.pipeline().addFirst("sslhandler", sslHandler);
+            sslHandler.sslCloseFuture().addListener(f -> ch.close());
             super.initChannel(ch);
             assert ch.pipeline().first() == sslHandler : "SSL handler must be first handler in pipeline";
         }
@@ -217,7 +218,10 @@ public class SecurityNetty4Transport extends Netty4Transport {
                 sslParameters.setServerNames(Collections.singletonList(serverName));
                 sslEngine.setSSLParameters(sslParameters);
             }
-            ctx.pipeline().replace(this, "ssl", new SslHandler(sslEngine));
+            final SslHandler sslHandler = new SslHandler(sslEngine);
+            ctx.pipeline().replace(this, "ssl", sslHandler);
+            sslHandler.sslCloseFuture().addListener(f -> ctx.close());
+
             super.connect(ctx, remoteAddress, localAddress, promise);
         }
     }
```

I'm in two minds about HTTP channels however. We could integrate with the `HttpPipeliningAggregator` and delay closing our end of the channel until we've sent all the pipelined responses. That seems like the proper thing to do, and is what I suggested in my previous message, but I now worry that this would delay the cancellation that a client close is trying to trigger. I expect most clients do not eagerly send a `close_notify` to indicate the end of a series of pipelined requests for which it's still awaiting responses. It would be technically correct to do so in TLS1.3 but in earlier TLS versions it just wouldn't work.

**Comment by DaveCTurner** [comment]
FTR the obstacle to fixing this is writing a test which exposes the bug, which needs quite low-level control over a TLS-enabled HTTP client in order to get it into a state where the TLS session is closed but the underlying TCP channel remains open. It should be possible to do something similar to `org.elasticsearch.http.netty4.Netty4HttpClient` by adding in the relevant TLS handlers into its pipeline.
