### ISSUE TITLE
Fuzzy query: Date/Time does not support y (Year) or M (month)

### ISSUE THREAD

**Issue by bly2k** [elastic/elasticsearch#7666]
Executing a Fuzzy query on a date field with fuzziness set to y or M fails. Documentation here states that this should be possible:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html#_numeric_and_date_fields

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/common-options.html#fuzziness

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/common-options.html#time-units

Reproducible using below:

```
curl -XDELETE localhost:9200/test1

curl -XPOST localhost:9200/test1/doc/1 -d '{
  "dt": "2012-05-23T13:56:00"
}'

curl -XPOST localhost:9200/test1/_refresh

curl -XGET localhost:9200/test1/_search?pretty -d'
{
  "query": {
    "fuzzy": {
      "dt": {
        "value": "2012-05-23T13:56:00",
        "fuzziness": "1y"
      }
    }
  }
}'

curl -XGET localhost:9200/test1/_search?pretty -d'
{
  "query": {
    "fuzzy": {
      "dt": {
        "value": "2012-05-23T13:56:00",
        "fuzziness": "1M"
      }
    }
  }
}'
```

We just need to fix TimeValue.parseTimeValue() to include "M" and "y".

**Comment by jpountz** [comment]
Support for fuzzy queries on numeric/date fields has been removed. Closing.
