### ISSUE TITLE
Translog entry markers

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#7668]
In the case of a corrupted translog (whether by OOME, bit corruption or manual intervention) it would be nice if we had a way of marking the beginning and/or end of each operation (0xdeadbeef perhaps? :)). Then when we were reading the translog and an unknown exception was encountered, we could skip to the next marker and write the corrupted portion to a separate file. We could then (optionally) continue reading the rest of the translog after the corruption.

**Comment by ppf2** [comment]
+1 great idea (been seeing a few translog corruption issues in the field and when this happens the shard gets stuck in initializing state).

**Comment by rjernst** [comment]
How would you know that byte sequence doesn't happen to appear in translog entries (good or bad)?

**Comment by rmuir** [comment]
I don't understand how silently losing data is an improvement. The existing exception-catching in this translog is already broken.

If the thing is corrupt, we should just throw an exception.

**Comment by s1monw** [comment]
I think with all the improvements on translog in 2.0 we can close this sicne we now validate checksums ahead of time etc?

**Comment by dakrone** [comment]
Yep, closing this.
