### ISSUE TITLE
Switch to future-proof linux distribution for Docker images

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#76681]
Centos 8 support updates will cease at the end of this year so we need to find a new Linux distro to base our docker images. There are obviously no shortage of options here but ideally:

1. Something with a good LTS scheme
2. Something well established (probably avoid the new up-and-coming CentOS replacements)
3. Ideally something RPM-based to align with UBI (not a hard requirement)

**Comment by mark-vieira** [comment]
cc @bytebilly 

@pugnascotia I believe we discussed some Ubuntu/Debian variants here. I know the UBI stuff is all yum/rpm dependent so it'd be nice if we could _mostly_ align there but maybe that's not really doable. UBI becoming "official" on Dockerhub is not something we can rely on in any concrete timeframe so we might just have to jump to something else.

**Comment by bytebilly** [comment]
Some data points to consider:

- Debian just released version 11, and it should give us less than 3 years (unless counting the LTS effort)
- Ubuntu 20.04 will provide standard support until around 2025
- CentOS 7 will be EOL mid-2024

Since we may expect to maintain ES 8.x for a longer time, would it be possible to update the base image during the 8.x cycle?

**Comment by pugnascotia** [comment]
Support for Rocky Linux seems to improving, e.g. GCP offer a prebuilt image for it now, and there are lots of high-profile backers on the website. The Delivery team's position is that we will wait and see how support improves before deciding to switch to anything.

Note that I was able to build and test the default Docker image using both Rocky and Oracle Linux, so switching to another `yum`-based distro appears very easy. Switch to Debian and keeping our custom base image process is not trivial.

**Comment by bytebilly** [comment]
Since we got green tests on AlmaLinux 8, we're testing if this could be a good base image for our next releases. We don't have a final call yet 🙂
