### ISSUE TITLE
Improve performance of building Elasticsearch modules

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#76726]
The ML native code dependency we use contains native binaries for all supported platforms (Windows, Linux, Mac on both x86 and aarch64). When we actually create the ML module bundle, we indiscriminately include all of these, and then[ later filter out inapplicable ones](https://github.com/elastic/elasticsearch/blob/81616c2fb61feb756d28bc2c3f7cc6e855e92d43/distribution/build.gradle#L329-L342) when actually building the appropriate distribution. The problem is when generating a local distribution for testing, we end up packaging all these files for no reason. On my local machine, _just_ building the ML bundle alone is a 16s operation. It [accounts for over half](https://gradle-enterprise.elastic.co/s/cnc7qhtp4q5u4/timeline?show-only-critical-path) of the time of building a local distro. We can do better here. A few options:

1. Produce multiple variants of the plugin and we grab the right one depending on which distro we're building. This is likely to be a big pain and introduce unneeded complexity though.
2. Don't "bundle" modules anymore. We should do something similar to what we did when we refactored distribution building to no longer create an archive, and instead just provide a directory as an artifact. This way we avoid zipping, then immediately unzipping a ton of artifacts for no reason. We'd still have to unpack the ML binaries, but maybe we could implement that as a cacheable artifact transform?

**Comment by mark-vieira** [comment]
I think just refactoring modules to generated directories instead of archives would be a huge win. For the ML module, building an exploded directory vs a zip file [takes only 2 seconds](https://gradle-enterprise.elastic.co/s/2fwvy2tlgmrng/timeline?details=tmwh7waekguqk&end=1629395563927&start=1629395560448.5).

**Comment by mark-vieira** [comment]
If we end up going this route, it would make even _more_ sense for plugins and modules to be separate Gradle plugins as now how we generate the "artifact" would start to diverge even more.

**Comment by mark-vieira** [comment]
cc @rjernst Just checking that there's no real requirement that we build module "bundles", correct? We don't subsequently publish these zip files anywhere and we simply immediately unpack them into the distribution.

**Comment by rjernst** [comment]
For modules that is correct. We only need the "bundle" zip file for plugins.

**Comment by breskeby** [comment]
I think just changing the build to not bundling the modules into an archive and immediately unpack it again should be easy to achieve and definitely should speed up distribution builds. Good catch!

**Comment by breskeby** [comment]
With having https://github.com/elastic/elasticsearch/pull/84997 merged, I'd call this done. One last thing to discuss is if it is worth to be able to mark certain projects (e.g. qa projects like `xpack:qa:freeze-plugin`) as modules to get the performance benefits for those projects too. @mark-vieira wdyt. Detecting a module vs. a plugin could live in a property on InternalPluginBundle

**Comment by mark-vieira** [comment]
Yes, probably, since these are never published and only used for testing. They are likely small though so not sure how large the benefit would be.

**Comment by mark-vieira** [comment]
> With having https://github.com/elastic/elasticsearch/pull/84997 merged, I'd call this done.

Can we ensure this is all backported all the way to 7.17. We don't want the build stuff continuing to diverge between these branches as it makes our lives harder in the long run. It looks like https://github.com/elastic/elasticsearch/pull/84660 got backported to 8.0 but not 7.17 and https://github.com/elastic/elasticsearch/pull/84997 hasn't been backported at all.
