### ISSUE TITLE
[plugin] support SNAPSHOT version download from sonatype repo

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#7672]
For now, when we use the plugin manager to install a JVM plugin, we download it from:
* elasticsearch download service (official plugins)
* maven central (community based plugins)

Sometime developers would like to share a SNAPSHOT version of a plugin. Artifacts are in that case most of the time available on [Sonatype](https://oss.sonatype.org/) repository.

Plugin manager should try to download the latest SNAPSHOT version available using Sonatype repo in addition to Maven central.

So the following could work:

```
bin/plugin install org.elasticsearch/elasticsearch-analysis-icu/3.0.0-SNAPSHOT
```

**Comment by dadoonet** [comment]
@tlrx I'm assigning this one to you. Could you add this once your work on the plugin manager will be pulled in?

**Comment by clintongormley** [comment]
Closing - no plans on supporting this
