### ISSUE TITLE
Different Deprecation Categorization

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#76754]
At the time of the 8.0 upgrade we want to differentiate these in two buckets:
 
Critical deprecations: These are features that are going away when they move to 8 and the user needs to take action before upgrading.
Informational deprecations: These are features that have been deprecated but aren't actually removed in 8.0. While we would like the user to stop using them now, it's not critical they do so before upgrading.
 
Currently all deprecation log entries are categorised as DEPRECATION. In order to classify these in the UI we would like by default all current deprecations to be level "CRITICAL", but offer teams the option to mark specific deprecations as "INFO". For example if the distributed team deprecated a feature but haven't removed it in 8.0, they could choose to go back to the deprecation log statement and change it to be an INFO level deprecation. By default if teams did nothing any existing deprecations would be marked as CRITICAL.

**Comment by pgomulka** [comment]
Should we also make this consistent with levels of deprecations in Deprecation Info API?
https://github.com/elastic/elasticsearch/blob/dda172e3a44ff3bb9781f92d4f6fbf6d362b6680/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationIssue.java#L37
we define two levels there
```
 /**
         * Resolving this issue is advised but not required to upgrade. There may be undesired changes in behavior unless this issue is
         * resolved before upgrading.
         */
        WARNING,
        /**
         * This issue must be resolved to upgrade. Failures will occur unless this is resolved before upgrading.
         */
        CRITICAL
        ;
```

**Comment by pgomulka** [comment]
closed by #77030

**Comment by kunisen** [comment]
Hi @pgomulka thanks for this issue.
Just a quick confirmation, we said the 2nd category is `INFO` in this ticket,

```
Informational deprecations: These are features that have been deprecated but aren't actually removed in 8.0. While we would like the user to stop using them now, it's not critical they do so before upgrading.
```

But actually per this PR - https://github.com/elastic/elasticsearch/pull/77030/files, we redefined the logger level for deprecation to `WARN` instead of `INFO`, is that correct?

**Comment by pgomulka** [comment]
@kunisen - yes, you are right. It is CRITICAL and WARN levels. I updated the description on the issue
