### ISSUE TITLE
Missing gradle task

### ISSUE THREAD

**Issue by wayneseymour** [elastic/elasticsearch#76760]
`./gradlew localDistro` fails locally, on a newly cloned repo, in master

**Elasticsearch version** (`bin/elasticsearch --version`):
master, from source

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
MAC OS Mojave 10.14.6

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. Clone the repo
 2. Install Gradle
 3. Run `λ ./gradlew localDistro`

**Provide logs (if relevant)**:
```
> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.4.1
  OS Info               : Mac OS X 10.14.6 (x86_64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [OpenJDK 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home
  Random Testing Seed   : 7186968F1868DF20
=======================================

FAILURE: Build failed with an exception.

* What went wrong:
Task 'localDistro' not found in root project 'elasticsearch'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

Looks like someone saw this too: https://github.com/elastic/elasticsearch/issues/27401#issuecomment-870169420

**Comment by mark-vieira** [comment]
Looks like you're checking out an old branch. This task doesn't exist in older branches, like `6.8`. You'll want to run something like `./gradlew :distribution:archives:assemble` instead.

**Comment by wayneseymour** [comment]
Ok, are we going to remove it from the readme?

**Comment by mark-vieira** [comment]
I suspect you're referring to the README file for the `master` branch. The [6.8 readme](https://github.com/elastic/elasticsearch/blob/6.8/README.textile) doesn't mention that task.
