### ISSUE TITLE
Create deprecation logs data stream by default

### ISSUE THREAD

**Issue by sabarasaba** [elastic/elasticsearch#76802]
In the Kibana Upgrade Assistant overview page, we would like to show the users a link to the Discovery app. In order to do so we need to create an index pattern first and it's not currently supported to do so for an inexistent index.

I would like to propose that instead of creating the deprecation logs data stream the first time a document is indexed that its created by ES if the indexing of deprecation logs is enabled (which will soon be enabled by default elastic/elasticsearch#76292).

/cc @pugnascotia

**Comment by pgomulka** [comment]
hey @sabarasaba can you please explain `In order to do so we need to create an index pattern first and it's not currently supported to do so for an inexistent index.` ?
I was wondering if this is really necessary to create that index. I might not see the real problem though
I thought that index will always be `.logs-deprecation.elasticsearch-default` (might have a prefix `.ds` and suffix `date` ) ? Can we not create a pattern based on this?

**Comment by sabarasaba** [comment]
Yeah for sure! So, in UA we need to have a link to the Discovery app and the route we can link to that allows us to show the logs in that app only accepts an `indexPatternId`. So we have to resort to checking if an index pattern for deprecation logs exists and if it doesn't we create a new one that points to the `.logs-deprecation.elasticsearch-default` index and use that ID to generate the link.

The problem we're facing is that the data stream is only created the first time a document is indexed. So when deprecation logs collection is enabled in a, for example, new ES instance since there are no deprecation logs yet, we cannot create the index pattern for a non existing index. We're doing it anyway right now, but a few errors are surfaced to the user in the UI which are not ideal.

**Comment by cjcenizal** [comment]
@pgomulka Doesn't searching a non-existent data stream also return a 404? From a consumer's perspective, it seems like a user who's searching for deprecation logs would expect an empty response (assuming logs are enabled). Getting back a 404 leaks an implementation detail, in my opinion.

**Comment by pgomulka** [comment]
I spoke with @sabarasaba and he clarified to me that it is about the link `Analyze logs in Discover`
![image](https://user-images.githubusercontent.com/11137008/135287490-4111c2d1-5de5-4448-bb8f-53edb2b208de.png)

at first I thought that we could just point to a separate page saying "no deprecation index, nothing to do"
But as it points to a discovery page, it will trigger an error  and I agree it does not look great :D 
 
I will continue working on it

**Comment by cjcenizal** [comment]
FWIW the error also appears when you first enable deprecation logs, which is a poor UX:

![image](https://user-images.githubusercontent.com/1238659/135290197-d11eb97a-f6a4-4c59-a8c3-a13a21c908d9.png)

**Comment by pugnascotia** [comment]
But doesn't Kibana need to interrogate ES anyway about the state of deprecation indexing, since it can be disabled and we'd want to reflect that in the UI? So it's not much of a stretch to include checking for the data stream too?

**Comment by cjcenizal** [comment]
@pugnascotia You're right that UA retrieves cluster state to determine whether deprecation logging (and indexing) is enabled,  so we can render the toggle either on or off. But I'm not sure I'm following your suggestion about checking for the data stream too -- can you walk me through it?

**Comment by pugnascotia** [comment]
I'm just wary about adding complexity to Elasticsearch in order to alleviate a UX concern. I'm thinking that the following ought to be straightfoward:

   - User navigates to page in Kibana
   - Kibana checks:
      - Whether deprecation indexing is enabled
	  - Whether the data stream exists
   - Kibana renders the page accordingly

I've struggled to find other examples of Elasticsearch creating indices or data streams on startup. We load plenty of templates, policies etc, but stop there (as far as I can tell).

**Comment by cjcenizal** [comment]
Thanks for explaining! I understand. The challenge is that Kibana has a number of internal tools (a service for searching index patterns) and user-facing tools (Discover, for example) which are used to retrieve the logs. These tools don't have any knowledge of deprecation indexing, and it would introduce a lot of complexity for us to conditionally interpret 404 errors based on certain conditions.

> I've struggled to find other examples of Elasticsearch creating indices or data streams on startup. We load plenty of templates, policies etc, but stop there (as far as I can tell).

If it helps, I form an analogy with the `logs` directory of Elasticsearch. This directory exists on install. If I want to see if there are any logs, I look inside it and see that it's empty. In the same way, I expect to look inside the deprecation logs index to see that it's empty.

To get more meta, think of the "deprecation logging" concept ES presents to consumers (both users and clients). We want to present an interface of:
* Logging state (`on` or `off`)
* Logs (the number which could be 0, 1, or many)

Given this interface, why would the consumer want to know about whether the index we're using to store the logs exists or not? Why would we want to make this interface more complicated for them?

And at the risk of belaboring the point... :) Kibana creates indices at startup. We present the Elastic Stack as a product, of which ES and Kibana are components. So whether or not historically ES has created its own indices at startup, the Stack has set this precedent, which we could consider to encompass this case, too.

**Comment by sabarasaba** [comment]
We were able to solve this in Kibana side with https://github.com/elastic/kibana/pull/113821
