### ISSUE TITLE
Release tagging differences - Elasticsearch, Kibana

### ISSUE THREAD

**Issue by srikwit** [elastic/elasticsearch#76803]
The release downloads from elastic.co have different tagging for Elasticsearch and Kibana:
Windows - No differences
rpm aarch64 - No differences
deb aarch64 - No differences
Mac - MACOS (Elasticsearch), MAC (Kibana)
Linux - Linux x86_64 for Elasticsearch, Linux 64-bit for Kibana
Debain 64-bit - DEB x86-64 (Elasticserch), 64-bit (Kibana)
RPM 64-bit - RPM x86-64 (Elasticsearch), 64-bit (Kibana)

I would like to request for a consistent naming convention for them:
https://www.elastic.co/downloads/elasticsearch
https://www.elastic.co/downloads/kibana

**Comment by pugnascotia** [comment]
@srikwit as far as I can tell,  the artifacts themselves appear to follow a consistent naming pattern. Is your issue concerning their presentation on the download web page?

**Comment by srikwit** [comment]
Yes this issue is the artefact naming convention on the download web page.

**Comment by mark-vieira** [comment]
These look to be consistent across Elasticsearch and Kibana on the download page now.
