### ISSUE TITLE
[CI] DockerTests test010Install failing: Cloud image should not have any plugins

### ISSUE THREAD

**Issue by BigPandaToo** [elastic/elasticsearch#76861]
org.elasticsearch.packaging.test.SqlCliTests.test010Install failing in 7.x

**Build scan**:
https://gradle-enterprise.elastic.co/s/7mf4urxcgktua

**Repro line**:
No repro

**Reproduces locally?**:
Didn't try 

**Applicable branches**:
7.x

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:test010Install),sort:!(time,desc))

**Failure excerpt**:

org.elasticsearch.packaging.test.SqlCliTests > test010Install FAILED | 
  | java.lang.AssertionError: Cloud image should not have any plugins in /opt/plugins/archive |  
  | Expected: an empty collection |  
  | but: <[]> |  
  | at __randomizedtesting.SeedInfo.seed([4B94504AFEB837D9:6FCBF0D99C156881]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.elasticsearch.packaging.util.docker.Docker.verifyCloudContainerInstallation(Docker.java:456) |  
  | at org.elasticsearch.packaging.util.docker.Docker.verifyContainerInstallation(Docker.java:433) |  
  | at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:232) |  
  | at org.elasticsearch.packaging.test.SqlCliTests.test010Install(SqlCliTests.java:18)

**Comment by BigPandaToo** [comment]
@pugnascotia , seems like you looked at this test before

**Comment by pugnascotia** [comment]
Yes, I am like Captain Ahab, cursed by the whale... 🐳 

I'm looking at it now.

**Comment by pugnascotia** [comment]
I pushed f387ec6cc5a to `7.x` in the hope that it will shed some light on what's going on.

**Comment by mark-vieira** [comment]
@pugnascotia this hasn't failed in a month. Think we can close?

**Comment by pugnascotia** [comment]
Might as well.
