### ISSUE TITLE
Darwin aarch64 startup error

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch#76901]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.0.0-SNAPSHOT - https://github.com/elastic/elasticsearch/commits/2bc4eca52926411143703fb187deea02703914dc

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
```
Darwin Darwin Kernel Version 20.5.0/RELEASE_ARM64_T8101 arm
```
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. tar -xvf elasticsearch-8.0.0-SNAPSHOT-darwin-aarch64.tar.gz
 2. cd elasticsearch-8.0.0-SNAPSHOT && bin/elasticsearch
 3.

**Provide logs (if relevant)**:
```
~/Downloads/elasticsearch-8.0.0-SNAPSHOT » ./bin/elasticsearch                       jbudz@mini
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:532), pid=64619, tid=8707
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment Zulu16.28+11-CA (16.0+36) (build 16+36)
# Java VM: OpenJDK 64-Bit Server VM Zulu16.28+11-CA (16+36, mixed mode, tiered, compressed oops, serial gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/jbudz/Downloads/elasticsearch-8.0.0-SNAPSHOT/hs_err_pid64619.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
bin/elasticsearch-keystore: line 6: 64619 Abort trap: 6           ES_MAIN_CLASS=org.elasticsearch.common.settings.KeyStoreCli ES_ADDITIONAL_CLASSPATH_DIRECTORIES=lib/tools/keystore-cli "`dirname "$0"`"/elasticsearch-cli "$@"
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
```

**Comment by mark-vieira** [comment]
@pugnascotia do you mind taking a look at this? I don't currently have access to my Apple silicon mac.

**Comment by pugnascotia** [comment]
Wow. I can replicate this on my M1. We're already using the latest Zulu build, so it does indeed look like we're triggering a bug somewhere.

**Comment by pugnascotia** [comment]
I think this might due to https://bugs.openjdk.java.net/browse/JDK-8267235, but that's allegedly been backported to 16.0.2 already. However I did confirm that ES will start with JDK 17 EA from Azul, so maybe that will help anyone blocked by this. I'll keep digging.

**Comment by pugnascotia** [comment]
I did check that I can compile and execute a basic Java file on the M1 using 16.0.2 and I can, so it's more specific that "it's broken".

**Comment by pugnascotia** [comment]
Entertainingly, running `./gradlew run` does work. Which is interesting.

**Comment by pugnascotia** [comment]
Hmm, I think `./gradlew run` is working because I have Azul 16.0.1 installed, and that version is working. So something in 16.0.2 is broken on M1.

**Comment by pugnascotia** [comment]
So the version of Azul that we've hacked into `JdkDownloadPlugin` isn't the latest. However, if I updated it, then `java` in the resulting distro dies immediately with `Killed: 9` 😕 

I tried using `cp` to update `jdk.app` in the ES distro to a JDK that I downloaded, but had the same issue. Then I tried copying the JDK with `tar`, and that worked.

So it looks like:

   1. We need to update the Azul JDK for M1
   2. We need to look at how we're copying the JDK into place, because apparently it's breaking something in the Azul distro.

**Comment by pugnascotia** [comment]
No way - I blew away my local distro folder, rebuilt it and this time it worked 🤷 

So I guess we just need to update the Azul version, which is trivial.

**Comment by droberts195** [comment]
> However, if I updated it, then `java` in the resulting distro dies immediately with `Killed: 9`

That sounds like what happens when you run an un-notarized program that was downloaded using a web browser. Downloading via a program that doesn’t add the quarantine attribute (certainly `curl` and probably Gradle) avoids this. Or remove the quarantine attribute manually using `xattr -d`.

**Comment by mark-vieira** [comment]
:+1: thanks for investigating, Rory.

**Comment by pugnascotia** [comment]
> That sounds like what happens when you run an un-notarized program that was downloaded using a web browser.

I think that's exactly what I did 😅
