### ISSUE TITLE
Composite aggs `terms` value source should allow `include` and `exclude`

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#76952]
The `terms` value source in composite aggs does not support `include` or `exclude`. 

Since `composite` aggregation has many optimizations when there is no query present, it would be nice to keep optimizations while reducing the term set bucketed. 

Additionally, it affords a nice API for crafting scrolling buckets when only a subset of terms is desired.

**Comment by not-napoleon** [comment]
I'm closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/50368.
