### ISSUE TITLE
Metric: Track the number of times a Thread is prevented from immediately running in Thread Pools

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#7700]
In the thread pool, we currently track the `largest` number of threads that it has contained, but this will eventually hit the `max` threads. If possible, it would be great to track when a new thread is prevented from starting because the pool is full already, which could help indicate how many times actions are inherently delayed by overloaded thread pools and the rejections would indicate how many times it was just too much to even wait for.

**Comment by clintongormley** [comment]
Closing in favour of #10601
