### ISSUE TITLE
has_parent查询不能使用GET请求方式？

### ISSUE THREAD

**Issue by xueyin220807** [elastic/elasticsearch#77004]
在文档“https://www.elastic.co/guide/en/elasticsearch/reference/7.14/query-dsl-has-parent-query.html”中有提到has_parent查询：
GET /my-index-000001/_search
{
  "query": {
    "has_parent": {
      "parent_type": "parent",
      "query": {
        "term": {
          "tag": {
            "value": "Elasticsearch"
          }
        }
      }
    }
  }
}
我在postman中的has_parent查询：
GET http://localhost:9200/my-index-000001/_serach
{
  "query": {
    "has_parent": {
      "parent_type": "question",
      "query" : {
          "match": {
              "name" : "Central"
          }
      }
    }
  }
}
响应为：
{
    "error": "Incorrect HTTP method for uri [/my-index-000001/_serach] and method [GET], allowed: [POST]",
    "status": 405
}
这是为什么呢？

**Comment by pugnascotia** [comment]
@xueyin220807 I can see that your URL has `_serach` but it should be: `_search`.

**Comment by xueyin220807** [comment]
很抱歉，我竟然犯下这么低级的错误

**Comment by pugnascotia** [comment]
没问题！
