### ISSUE TITLE
Darwin compatibility build fails due to git clone timeout

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#77032]
Darwin compatibility tests have failed more than once due to a git clone timeout. 

This is a weird one to me, seems like its becoming systemic.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+platform-support-darwin/232/

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+platform-support-darwin/232/

In 7.x, it was able to fetch objects and THEN timedout. In the master build, it simply timedout.

**Comment by mark-vieira** [comment]
Hmm, I need to reach out to infra again to rebuild these workings. I think they are beyond repair.

**Comment by mark-vieira** [comment]
Closing as a duplicate of #73070.
