### ISSUE TITLE
Make the elasticsearch blog searchable

### ISSUE THREAD

**Issue by iksnalybok** [elastic/elasticsearch#7705]
Hi,

Reading the blog regularly, there are interesting articles that I don't need for the moment but want do keep in mind for future developments. I'd appreciate to be able to search for them, the same way we can search for the documentation today (http://www.elasticsearch.org/guide/).

Moreover, the types of articles in the blog fall into a few categories. I've listed:
- Weekly news ("This week in Elasticsearch")
- Events & meetings ("Where in the World is Elasticsearch")
- Releases announcements ("Elasticsearch <product> <version> released")
- Others (mainly tips/howto use a particular feature, like "Using the percolator for geo tagging")

Having in the /blog page the possibility to filter by category seems useful to me.

Ik

**Comment by javanna** [comment]
With the new [website](https://www.elastic.co/) all of the blogs have been made searchable too, I think we can close this.
