### ISSUE TITLE
error:[has_parent] no join field has been configured

### ISSUE THREAD

**Issue by xueyin220807** [elastic/elasticsearch#77050]
一个GET请求:http://localhost:9200/my-index-000010/_search
请求正文：
{
  "query": {
    "has_parent": {
      "parent_type": "question",
      "query" : {
          "match_all" : {}
      }
    }
  }
}
响应体：
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "[has_parent] no join field has been configured",
                "index_uuid": "ILas4Cj4SEynC02T1f4juA",
                "index": "my-index-000010"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "my-index-000010",
                "node": "qyWfA-ewRZe_ZLeMwNimGw",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "[has_parent] no join field has been configured",
                    "index_uuid": "ILas4Cj4SEynC02T1f4juA",
                    "index": "my-index-000010"
                }
            }
        ]
    },
    "status": 400
}
请问[has_parent] no join field has been configured错误是什么意思？

**Comment by not-napoleon** [comment]
Hello, and thank you for your interest in Elasticsearch.  In order to investigate this issue, we need more complete reproduction steps.  Specifically, please share the mappings and test data you used to get this error.  Thank you!

**Comment by benwtrent** [comment]
closing due lack of feed back
