### ISSUE TITLE
ECE Admin Console User Profile SAML Attribute Enhancement

### ISSUE THREAD

**Issue by houseall** [elastic/elasticsearch#77090]
When setting up ECE 2.10.1 On-premise SAML provider I mapped name and mail attributes, but when I click on Admin Console user "profile" link the full name and contact email fields are blank (see attached screen image). I looked in security deployment trace log and I can see all the SAML assertion attributes being parsed correctly from the Okta SAML response.

The ECE / ELK Stack documentation references these Elasticsearch supported user properties: 
principal (Required)
groups (Recommended)
name (Optional)
mail (Optional)
dn (Optional)

**Enhancement request:** Add support to map the optional attributes that are available on the ECE Add SAML Provider screen (see attached screen image).

**Additional reference:** Elastic Support Case: # 00772098
My Okta IaC attribute assertions:
  attribute_statements {    
    name         = "name" 
    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    type         = "EXPRESSION"
    values       = [
       "user.firstName + ' ' + user.lastName"
      ]
    }
  attribute_statements {
    name         = "mail" 
    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    type         = "EXPRESSION"
    values       = [
       "user.email"
      ]
    }

![AdminConsoleAddSAMLProvider](https://user-images.githubusercontent.com/1569084/131557668-d78c5a84-d639-45f9-9bf9-c29311862ebb.png)
![AdminConsoleSSOUserProfile](https://user-images.githubusercontent.com/1569084/131557670-5360d7cd-f3f9-47f1-b157-fb935f79f235.png)

**Comment by Kushmaro** [comment]
hey @houseall , thank you for opening this issue. 

We will copy the details over to the proper internal repository where it can be properly addressed and prioritized by our ECE engineering team. Please contact the Elastic account management team or Elastic support for further details.
