### ISSUE TITLE
AssertionError: Found shard snapshot waiting to be assigned...

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#77101]
In a recent `master` (707dd497e489bb6917dc3d0bd58928ce13a33927) I saw a snapshot stress test trip the `Found shard snapshot waiting to be assigned` exception. The problematic shard was `[index-1][1]` and the assertion tripped at the cluster state transition which finalised a snapshot with a future clone queued up. The previous state of this shard was like this:

    snapshot:
    {
      "index": {
        "index_name": "index-1",
        "index_uuid": "kigpd8yeTZm5R6PHbZKpww"
      },
      "shard": 1,
      "state": "FAILED",
      "generation": "CcvNa4iURmCdg0YDvwIM9w",
      "node": "PgoVP627RAqZnA5y4ZQeDQ",
      "reason": "node shutdown"
    },

    clone:
    {
      "index": {
        "name": "index-1",
        "id": "3cG2OCEuSB2MINCVHFxI4g"
      },
      "shard": 1,
      "state": "QUEUED",
      "generation": null,
      "node": null
    }

The finalisation removed the first entry, leaving the dangling `QUEUED` clone. FWIW the shard was in yellow health at the time, although as a clone we should be able to proceed even if it were red.

Full test output in case it helps: [testoutput-1630475019.tar.gz](https://github.com/elastic/elasticsearch/files/7088887/testoutput-1630475019.tar.gz)

**Comment by original-brownbear** [comment]
This one's really trivial to reproduce for a change :)

```java
    public void testCloneAfterFailedShardSnapshot() throws Exception {
        final String masterNode = internalCluster().startMasterOnlyNode();
        final String dataNode = internalCluster().startDataOnlyNode();
        final String repoName = "test-repo";
        createRepository(repoName, "mock");
        final String testIndex = "index-test";
        createIndex(testIndex);
        final String sourceSnapshot = "source-snapshot";
        createFullSnapshot(repoName, sourceSnapshot);
        indexRandomDocs(testIndex, randomIntBetween(1, 100));
        blockDataNode(repoName, dataNode);
        final ActionFuture<CreateSnapshotResponse> snapshotFuture =
            client(masterNode).admin().cluster().prepareCreateSnapshot(repoName, "full-snapshot").execute();
        awaitNumberOfSnapshotsInProgress(1);
        waitForBlock(dataNode, repoName);
        final ActionFuture<AcknowledgedResponse> cloneFuture =
            client(masterNode).admin().cluster().prepareCloneSnapshot(repoName, sourceSnapshot, "target-snapshot")
                .setIndices(testIndex).execute();
        awaitNumberOfSnapshotsInProgress(2);
        internalCluster().stopNode(dataNode);
        assertAcked(cloneFuture.get());
        assertTrue(snapshotFuture.isDone());
    }
```

... little iffier to fix though but on it :)
