### ISSUE TITLE
[Transform] If there are no changes to source indices between checks then all indices are searched

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#77137]
One of the security solution tests is getting this error from transforms:

```
Failed to index documents into destination index due to permanent error: [org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced [1] failures and at least 1 irrecoverable [org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [data_stream.dataset] of type [constant_keyword] in document with id 'Xy_cEPawfBodqd3xVPy9vEgAAAAAAAAA'. Preview of field's value: 'elastic_agent.elastic_agent'; java.lang.IllegalArgumentException: [constant_keyword] field [data_stream.dataset] only accepts values that are equal to the value defined in the mappings [endpoint.metadata], but got [elastic_agent.elastic_agent]].; org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [data_stream.dataset] of type [constant_keyword] in document with id 'Xy_cEPawfBodqd3xVPy9vEgAAAAAAAAA'. Preview of field's value: 'elastic_agent.elastic_agent'; java.lang.IllegalArgumentException: [constant_keyword] field [data_stream.dataset] only accepts values that are equal to the value defined in the mappings [endpoint.metadata], but got [elastic_agent.elastic_agent]]
```

The Elasticsearch log file shows this:

```
    info [o.e.x.t.t.ClientTransformIndexer] [local] [endpoint.metadata_current-default-1.1.1] Failed to create a point in time reader, falling back to normal search.
         org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: [index] is not specified;
           at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:15) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
           at org.elasticsearch.action.search.OpenPointInTimeRequest.validate(OpenPointInTimeRequest.java:67) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
...
```

There are no more errors in the log, but I strongly suspect the next step is then to do a normal search with no indices specified, which means search _all_ indices as in `GET _search` :scream:.

This would then explain why the output of the transform contains information from a logs index rather than a metrics index.

The bug was most likely introduce in #75839 and the line at fault is most likely to be: https://github.com/elastic/elasticsearch/blob/4974a7cd7bb47f3d1921e77a835d30cc6b1539ff/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java#L1159

In the case where `changeCollector.getIndicesToQuery()` returns an empty collection we need to skip the search entirely instead of searching all indices.

It should be possible to put together an integration test that tests the scenario of no changes to the source indices between two successive runs of a transform.  If the theory above is correct then this will reproduce the problem and validate the fix.

This problem is in 7.16 and above, so can easily be fixed before it affects end users.

**Comment by benwtrent** [comment]
>    changeCollector.getIndicesToQuery(lastCheckpoint, nextCheckpoint).toArray(new String[0]);

Returning `new String[0]{}` is a big issue. Just to be 100% certain, was this seen in a `latest` transform?
