### ISSUE TITLE
Exposing the regular fields in SearchHit

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#77171]
At the moment, internal clients of `SearchHit` can only get a list of all fields (regular and metadata) inside a hit, even if those are separated as `metadataFields` and `documentFields`. Filtering out metadata fields is not so straightforward and a dedicated method would be preferred.

**Comment by romseygeek** [comment]
It looks as though the only non-test consumers of `getFields()` are `EventPayload` and `SequencePayload`.  Do both of these classes only want non-metadata fields? In which case we can just switch `getFields()` to only return doc fields.  Alternatively, we can rename it to `getAllFields()`, and two new methods to get doc fields and metadata fields, and then cut over other uses in a followup.

**Comment by astefan** [comment]
Before the `fields` API was introduced, we were looking at the "ignored" fields in the response, but now I don't think we need this information. That's the only connection between QL and "ignored" fields that I'm aware of.
EventPayload and SequencePayload return this information to the user and, since `fields` API doesn't allow metadata fields to be returned, I think it's safe to say that we need only non-metadata fields.

**Comment by cbuescher** [comment]
> the only non-test consumers of `getFields()` are `EventPayload` and `SequencePayload`.

I think that a lot of client side code might accesses this method outside of the ES codebase. Rather than changing the existing behaviour or the naming I would add new methods for this reasion. Just my 10c though.
