### ISSUE TITLE
Warning messages logged when index_prefixes are configured in index mapping

### ISSUE THREAD

**Issue by R0ky** [elastic/elasticsearch#77183]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
For index that has `index_prefixes` configured in the mapping, so similar like this: 

```
"field" : {
          "type" : "text",
          "index_prefixes" : {
            "min_chars" : 1,
            "max_chars" : 17
          }
        },
```

we can see a number of warning events logged in Elasticsearch log. Events look like this: 
```
[index_name][10] no index mapper found for field: [field._index_prefix] returning default postings format
```

**Steps to reproduce**:

N/A

**Provide logs (if relevant)**:
N/A

**Comment by pugnascotia** [comment]
@romseygeek given the Slack conversation, do I need to do anything here? I'm not clear who was going to raise the ES issue.

**Comment by romseygeek** [comment]
@pugnascotia I'll take this one.
