### ISSUE TITLE
Shard rebalance according to index

### ISSUE THREAD

**Issue by jingweiz300** [elastic/elasticsearch#77224]
We have a cluster with 400 data nodes. During the day, the load of some nodes is often too high. Our indexes are created by day.

I used the following command to check and found that there were too many fragments on some nodes on the same day, which was seriously unbalanced,

curl http://xx.xx.xx.xx:9200/_ cat/shards|grep YYYYMMDD|awk {'print $8'}|sort|uniq -c

For example:

100 192.168.1.1

100 192.168.1.2

100 192.168.1.3

10 192.168.1.4

10 192.168.1.5

10 192.168.1.6

10 192.168.1.7

10 192.168.1.8

10 192.168.1.9

10 192.168.1.10

...

This will lead to the very hot of the first three nodes. Most of the write requests on that day are concentrated in the first three nodes. Once this happens, the pressure load of the first three nodes cannot be quickly decomposed, because the current rebrance mechanism can only be controlled by relying on the disk watermark, total partition weight and index weight. The balance range is all the open indexes of the whole cluster, Instead of the hot data index of the day I want to operate, such as the index containing the date of the day. index name like nginx_accesslog_20210903

Whether to add an interface or configure to allow maintenance personnel to filter according to certain conditions, and only provide reblance for the filtered index

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question: there are already mechanisms to prevent this kind of imbalance, so no change seems needed in Elasticsearch itself. We prefer to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by jingweiz300** [comment]
Hi DaveCTurner：
  In my scenario, the total number of partitions is balanced. My cluster stores the indexes of the last 7 days. The partition distribution of the cluster is roughly like this. It is very balanced. However, the heat index data in the last day is unbalanced

500 192.168.1.1

500 192.168.1.2

500 192.168.1.3

500 192.168.1.4

500 192.168.1.5

500 192.168.1.6

500 192.168.1.7

500 192.168.1.8

500 192.168.1.9

500 192.168.1.10

...
