### ISSUE TITLE
Improve testing for Painless fields API conversions

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#77272]
We anticipate adding a large number of conversions moving forward, but our testing isn't easily extendable and will become unmaintainable as it stands. 

I propose we make the following changes to counteract this:

1. Create a set of data for each field type as part of the test setup. This data can then be shared easily amongst tests instead of reproducing a similar set of values many times.
2. Each field conversion should have its own test case for a transition of original type to target type in a similar way to the casting tests we have for the type system in Painless. These should include invalid transitions to ensure we receive the expected error.
3. For type conversions that are non-lossy we should have a test for each one to ensure that a conversion from original type to target type to original type produces equivalent values.

**Comment by stu-elastic** [comment]
We've removed converters in the API change so this issue is no longer relevant.
