### ISSUE TITLE
Make GeoIP database download logging look happier

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#77305]
Users sometimes get confused by how Elasticsearch logs a bunch of stuff at startup and then simply stops, as if the process is blocked trying to do something. This is in general a tricky problem to solve, we're ready to receive HTTP requests well before the logging stops, but there's no well-defined endpoint to these log messages either. In the past it wasn't too bad, the last message would often be something positive-sounding like `Cluster health status changed from [YELLOW] to [GREEN]`, but in recent versions it seems that this is often the last log message:

https://github.com/elastic/elasticsearch/blob/331a44ba425d9ae937a8f49a7f94d8d0a02f3b93/modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseRegistry.java#L311

This is apparently making the confusion much worse ([1](https://discuss.elastic.co/t/installation-seems-to-hang/281116/5), [2](https://discuss.elastic.co/t/database-file-changed-error/281903)), it looks like we're stuck trying to reload a database file that changed. Could we improve the logging in this area to make it clearer that everything is fine and we're not stuck waiting for anything to complete?

Relates https://github.com/elastic/elasticsearch/pull/76709

**Comment by danhermann** [comment]
Closed by #77391
