### ISSUE TITLE
Inconsistent search_after behaviour for the date fields 

### ISSUE THREAD

**Issue by michal-lyson** [elastic/elasticsearch#77448]
**Elasticsearch version** 7.13.1:

**Description of the problem including expected versus actual behavior**:

If we run the `search_after` query against a `date` field using the negative number as a String then elastic throws an exception. 
> "failed to parse date field [-1] with format [epoch_millis]: [failed to parse date field [-1] with format [epoch_millis]]"

Using a positive number as a Number or String works fine. Using a negative number as a Number also works fine.

**Steps to reproduce**:

 1. Create a simple index with the  `date` field
```
PUT lyson_test
{
  "mappings": {
    "properties": {
      "dateField": {
        "type": "date",
        "format": "epoch_millis"
      }
    }
  }
}
```

 2. run the `search_after` query using a positive number
```
GET lyson_test/_search
{
  "sort": [
    {
      "dateField": {
        "order": "desc"
      }
    }
  ],
  "search_after": [
    1
  ]
}
```
**Everything works fine**

 3. run the `search_after` query using a negative number
```
GET lyson_test/_search
{
  "sort": [
    {
      "dateField": {
        "order": "desc"
      }
    }
  ],
  "search_after": [
    -1
  ]
}
```
**Everything works fine**

 4. run the `search_after` query using a positive number as a String
```
GET lyson_test/_search
{
  "sort": [
    {
      "dateField": {
        "order": "desc"
      }
    }
  ],
  "search_after": [
    "1"
  ]
}
```
**Everything works fine**

 5. run the `search_after` query using a negative number as a String
```
GET lyson_test/_search
{
  "sort": [
    {
      "dateField": {
        "order": "desc"
      }
    }
  ],
  "search_after": [
    "-1"
  ]
}
```
Expected: **Everything works fine**

Actual: **The exception is thrown:**
> "failed to parse date field [-1] with format [epoch_millis]: [failed to parse date field [-1] with format [epoch_millis]]"

**Comment by badjr** [comment]
@michal-lyson may I ask what your use case is? Support for negative epoch timestamps was deprecated in PR #36793, so is there still a need for using negative epoch timestamps in `search_after`?

**Comment by michal-lyson** [comment]
@badjr We are using `search_after` queries based on previous queries with the sort field specified. But when the sort field is not populated then elasticsearch is returning a negative number (Long.MIN_VALUE).

```
PUT lyson_test/_doc/1
{
  "message": "test1"
}

PUT lyson_test/_doc/2
{
  "message": "test2"
}

GET lyson_test/_search
{
  "size": 1, 
  "sort": [
    {
      "dateField": {
        "order": "desc"
      }
    }
  ]
}
```
Result:
```
{
  "took" : 485,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "lyson_test",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : null,
        "_source" : {
          "message" : "test1"
        },
        "sort" : [
          -9223372036854775808
        ]
      }
    ]
  }
}
```

I think if the negative numbers are deprecated then the search should return 0. Also queries from the top should be working in a consistent way.

**Comment by mayya-sharipova** [comment]
> We are using search_after queries based on previous queries with the sort field specified. But when the sort field is not populated then elasticsearch is returning a negative number (Long.MIN_VALUE).

@michal-lyson  Sort queries allow you to return a custom missing value. If you define "missing" : 0 than for non populated docs, `0` value will be returned instead of Long.MIN_VALUE

**Comment by benwtrent** [comment]
I followed the steps as laid out in the issue on the latest version, no errors were thrown. Closing.
