### ISSUE TITLE
Upgrade <=6.x to >=7.15 shows warning use of joda time method is deprecated 

### ISSUE THREAD

**Issue by liza-mae** [elastic/elasticsearch#77461]
In the upgrade paths  <=6.x to >=7.15, I am seeing a warning message in that use of joda time method is deprecated.  

Is this an expected warning message or should is this something that should be handled?

![Screenshot from 2021-09-08 15-36-18](https://user-images.githubusercontent.com/23424008/132590215-1c25b413-b0ae-4975-98ab-1dd4a5aa5412.png)

**Comment by pgomulka** [comment]
hey @liza-mae thanks for rising this. I suspect this is caused by a script that this Dashboard is using? Can you confirm if you use scripts there?

**Comment by liza-mae** [comment]
@pgomulka thank you, it is using Kibana sample data which does use a script and and the Kibana core team pointed me to a fix here: https://github.com/elastic/kibana/issues/111654#issuecomment-915938467, we can close.
