### ISSUE TITLE
[CI] TransformRobustnessIT.testTaskRemovalAfterInternalIndexGotDeleted failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#77470]
**Build scan**: https://gradle-enterprise.elastic.co/s/73wp457fa4urk

**Repro line**: `./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformRobustnessIT.testTaskRemovalAfterInternalIndexGotDeleted" -Dtests.seed=E24B8A2C2A37D3FB -Dtests.locale=es-VE -Dtests.timezone=Pacific/Niue -Druntime.java=11 -Dtests.fips.enabled=true`

**Reproduces locally?**: no

**Applicable branches**: 7.14, but probably applicable to other branches as well

**Failure history**: none recently

**Failure excerpt**:

```
java.lang.AssertionError: expected:<0> but was:<1> | 
at __randomizedtesting.SeedInfo.seed([E24B8A2C2A37D3FB:7D69897D91D8C50B]:0) |  
-- | --
  |   | at org.junit.Assert.fail(Assert.java:88) |  
  |   | at org.junit.Assert.failNotEquals(Assert.java:834) |  
  |   | at org.junit.Assert.assertEquals(Assert.java:645) |  
  |   | at org.junit.Assert.assertEquals(Assert.java:631) |  
  |   | at org.elasticsearch.xpack.transform.integration.TransformRobustnessIT.testTaskRemovalAfterInternalIndexGotDeleted(TransformRobustnessIT.java:93)
```

**Comment by hendrikmuhs** [comment]
No failures since ages, closing
