### ISSUE TITLE
[DOCS] Missing concept-level documentation for shard allocation and recovery

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#77515]
We don't currently have high-level concept documentation for shard allocation or shard recovery. The best we have is reference docs for related settings:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/recovery.html

We should consider documenting these processes at a higher level.

**Comment by debadair** [comment]
There are a few other related bits and pieces, but the overall story is sorely lacking.

- https://www.elastic.co/guide/en/elasticsearch/reference/current/add-elasticsearch-nodes.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-allocation.html

**Comment by jrodewig** [comment]
Some additional information pointed out by @Leaf-Lin:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/delayed-allocation.html
* https://www.elastic.co/guide/en/elasticsearch//reference/master/cat-recovery.html

**Comment by Leaf-Lin** [comment]
@henningandersen provided some high level concepts could be worked into the doc:

Relocation and recovery are in fact very similar. They both ensure that a copy of data is established as "in-sync" with the primary.
The primary differences are:
1. The relocation target is extra compared to the replica count and the relocation target for a primary will also be marked as primary (but will in all aspects of recovery function as a replica until the very end).
2. At the end of recovery, a primary relocation will perform a relocation hand-off, which  starts forwarding requests to the new primary and the old primary stands down (becomes replica).
3. Once the target shard is started for a relocation, the master will remove the location source.

The primary is involved in all cases (recovery, relocation of replica (which is mostly just a recovery) and relocation of primary).
