### ISSUE TITLE
[Feature] Geopolygon filter - Even-odd & Non-zero rules

### ISSUE THREAD

**Issue by altitude** [elastic/elasticsearch#7751]
Right now it seems that elasticsearch only supports by default even-odd filling for the geopolygon filter.

It would be great to add an option to choose  between even even-odd & non-zero, especially since some browser `<canvas>` only supports non-zero filling. 

This can lead to situations where you don't have a hole in your web polygon but you have one in elastic, and results that should pop out don't.

See [https://en.wikipedia.org/wiki/Nonzero-rule](https://en.wikipedia.org/wiki/Nonzero-rule)

:-)

**Comment by clintongormley** [comment]
@nknize just a ping about this given that geo2 has been merged

**Comment by nknize** [comment]
relates to #26286

**Comment by iverase** [comment]
we discuss this issue and we decided that in order to support this we should be able to handle polygons that are not complaint with the OCG standard (polygons with self-intersections). We don't think we will ever go that route so we think is better to close the issue.
