### ISSUE TITLE
SQL support for `allow_partial_search_results`

### ISSUE THREAD

**Issue by GedPL** [elastic/elasticsearch#77547]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0

**Plugins installed**: []

**JVM version** (`java -version`): openjdk-11.0.5+10

**OS version** (`uname -a` if on a Unix-like system): Linux RedHat 7.6 Maipo 3.10.0-957.12.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:

Elasticsearch indices are created at midnight UTC by Logstash on daily basis using following pattern:
**index => "my-system-%{+YYYY.MM.dd}"**
so their names look like below:
**my-system-2021.09.07
my-system-2021.09.08**
etc.

My Python script extracts some data hourly using above indices (also at midnight UTC) and SQL API sending query:
**SELECT rq_type, COUNT(\*) FROM "my-system-*" WHERE "@timestamp" >= NOW() - INTERVAL 1 HOURS GROUP BY rq_type**
Usually it works fine and returns just a few rows as expected, but at midnight UTC (and only then) it raises an error (very often but not always):
For example:
_2021-09-08 00:00:04,151 [ERROR  ]  Query execution failed ! ({"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"query","grouped":true,"failed_shards":[],"caused_by":{"type":"search_phase_execution_exception","reason":"Search rejected due to missing shards [[my-system-2021.09.08][0]]. Consider using `allow_partial_search_results` setting to bypass this error.","phase":"query","grouped":true,"failed_shards":[]}},"status":503})_ 

So looks like it occurs only just after creating new index.
I've checked my cluster setting search.default_allow_partial_results and it's set to true.
Also according to documentation allow_partial_search_results can be used for _search API but I can't see such an option in SQL API request body parameters.

**Steps to reproduce**:

In Description

**Comment by bpintea** [comment]
Fixed by #85897.
