### ISSUE TITLE
The java-rest-test plugin is now internal but plugin examples still use it (and existing plugins with rest tests require it)?

### ISSUE THREAD

**Issue by dweiss** [elastic/elasticsearch#77543]
So, somewhere between 7.12.0 and 7.14.1 my (external) plugin stopped compiling. This is due to:
```
A problem occurred evaluating root project 'elasticsearch-carrot2'.
> Plugin with id 'elasticsearch.java-rest-test' not found.
```
I find it weird because the "plugins/examples/rest-handler"  still use it... How is one supposed to write external plugins now without access to this infrastructure? I see #72470 implemented this change - any thoughts on this?

**Comment by dweiss** [comment]
If there is any upgrade path for what previously was:
```
apply plugin: 'elasticsearch.java-rest-test'
apply plugin: 'elasticsearch.yaml-rest-test' 
```
I'd be very grateful for a pointer. Every time you guys change something in the build/ plugin infrastructure it requires an intense deep scan of source code changes on ES side - very time consuming and discouraging. It'd be great if there was a writeup about such changes in release notes (or maybe there is and I missed it?).

**Comment by mark-vieira** [comment]
We added this back with https://github.com/elastic/elasticsearch/pull/76554 although only the YAML plugin, not Java. @breskeby we should probably similarly provide a java rest test plugin.

> Every time you guys change something in the build/ plugin infrastructure it requires an intense deep scan of source code changes on ES side - very time consuming and discouraging.

I totally get it. Ironically, the reason we removed it is specifically to stop this from happening. We previously had no separation between internal and external buid logic. So changing internal stuff very often broke plugin developers like yourself. We started by stripping down what we consider "external" to the absolute bare minimum. Part of this meant making some decisions on what we "thought" folks needed. As issues like this are reported, we tweak what's included in that distribution. Thanks for the patience while we work this out.

**Comment by mark-vieira** [comment]
@breskeby I'll take care of sorting this out and backporting so this makes it into the upcoming 7.14.2 release.

**Comment by breskeby** [comment]
let me know. Otherwise I can take of that the next few days.

**Comment by dweiss** [comment]
Thanks @mark-vieira and @breskeby .
