### ISSUE TITLE
Emit warning when using fuzziness parameter for cross_fields query type of multi_match query

### ISSUE THREAD

**Issue by grmblfrz** [elastic/elasticsearch#7764]
I was using the cross_fields query type with the fuzzyness parameter and got unexpected results. While fuzziness is not documented for cross_fields it is accepted and then leads to strange results. It would be nice to emit a warning in this case (and perhaps add an explicit warning to the documentation). Even better would be the possibility to use fuzziness with cross_fields, see #6866.

Relates to #10217

**Comment by clintongormley** [comment]
@cbuescher any chance this could be added for 5.0?  It not obvious that fuzziness can't be combined with cross_fields - we should throw an exception in this case

**Comment by cbuescher** [comment]
The same seems to be true for `phrase` and `phrase_prefix`, they shouldn’t support `fuzziness` either. `match_phrase` query already throws an exception if you specify fuzziness. So I'll add those two types to the list of exclusions in the PR above.
