### ISSUE TITLE
Composite test failing after #76740

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#77650]
I'm not sure what's up with #76740, but some test failures seem to have snuck in. I'm going to disable the failing tests and link the here.

**Comment by original-brownbear** [comment]
I think this the same as https://github.com/elastic/elasticsearch/issues/77649 right? :)

**Comment by nik9000** [comment]
> I think this the same as #77649 right? :)

Two whole minutes before me! Ah well. I'll close yours because I've already pushed the `@AwaitsFix` linking to this.

**Comment by nik9000** [comment]
@Luegg got this yesterday.
