### ISSUE TITLE
Mapping type Shorthand

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#77665]
As someone that writes a fair number of index mappings, I frequently catch myself writing how I wish the mappings would let me write by specifying the field's name and `type` in one pass:

```json
"mappings": {
  "properties": {
    "my_id": "keyword"
  }
}
```

This would simplify and trim down the size of most of my mappings by at least half when pretty printed and visually make it easier to scan fields at the same level, as well as spot more complexly defined fields.

The pretty printed version of every field is three lines by comparison:

```json
"my_id": {
  "type": "keyword"
}
```

versus

```json
"my_id": "keyword"
```

And, at least theoretically, nothing else is impacted. The current version of the mappings could be returned by default with only the shorthand returned with a flag (`compact`?) to avoid breaking anyone's code.

**Comment by javanna** [comment]
We have seen historically that having two days to do the same thing causes complexity. While we have this in our query DSL, I would be wary of introducing this notion to our index mappings at this stage. Maybe I am missing some advantage though: you mention that using a shorter notation would reduce the size of your mappings, but I don't see how this would affect the internal representation of the mappings. Do you mean that their size would be reduced in terms of what get mappings returns and what the human eye has to go through, plus it would be quicker to write mappings?

**Comment by pickypg** [comment]
> Do you mean that their size would be reduced in terms of what get mappings returns and what the human eye has to go through, plus it would be quicker to write mappings?

Exactly this. It makes visually scanning and typing easier.

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
