### ISSUE TITLE
GeoBoundingBox query should work on bounding box with equal latitude or longitude

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#77717]
Currently when you try to execute a GeoBoundingBox query like:

```
GET /my-index/_search?pretty
{
  "query": {
    "geo_bounding_box": { 
      "location": {
        "top_left": {
          "lat" : 41.1199999647215,
          "lon" : -71.34000004269183
        },
        "bottom_right": {
          "lat" : 41.1199999647215,
          "lon" : -71.34000004269183
        }
      }
    }
  }
}
```

You get an error like:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "top cannot be the same as bottom: 41.1199999647215 == 41.1199999647215"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "top cannot be the same as bottom: 41.1199999647215 == 41.1199999647215"
  },
  "status" : 400
}
```

On the other hand using the same bounding box on a geo_shape query works. Lucene actually supports it so I think this limitation should  be removed from the query builder.

**Comment by jchrys** [comment]
Hello,  @wchaparro .
Could I pick this as my first issue?

**Comment by jchrys** [comment]
@glennvill I think it is not a good move..

**Comment by glennvill** [comment]
@jchrys what do you suggest?

**Comment by iverase** [comment]
I think @jchrys was waiting for an answer (which is our fault that is coming very late). @glennvill would you mind if @jchrys takes care of this issue if he wants to as he was first? I hope you don't mind. 

Note that every change need to have unit test, e.g to make sure nobody adds backs this check.

**Comment by jchrys** [comment]
Thanks, @iverase. I was waiting for the answer form wchaparro.
@glennvill would you mind if I take this issue as my first issue?

**Comment by glennvill** [comment]
@iverase @jchrys no problem mates. Go ahead!

**Comment by glennvill** [comment]
Kindly link me the solution so I can learn from this too  :D

**Comment by iverase** [comment]
Thanks @glennvill, much appreciated. Sure we will ping you in the next PR.

**Comment by jchrys** [comment]
Hi mates!
I've created a https://github.com/elastic/elasticsearch/pull/85788 to try to address this issue.
Please let me know if I am on track to get it done 😃
