### ISSUE TITLE
null values collide with Long.MIN/MAX_VALUE when sorting

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#77720]
Given an index `long_order`:

```
curl -X POST "localhost:9201/long_order/_bulk"  -H 'Content-Type: application/json' -d'{"index": {"_id": 1}}
{"k": "MAX", "l": 9223372036854775807
{"index": {"_id": 2}}
{"k": "NULL","l": null}
{"index": {"_id": 3}}
{"k": "MAX","l": 9223372036854775807}
'
```

And a query like:

```
{
  "sort": [
      {
          "l": {
              "order": "asc",
              "missing": "_last"
          }
      }
  ]
}
```

The order of returned doc ids is `1, 2, 3` but the expected order would be `1, 3, 2` because of the missing value in field `l` of document 2.

I'm mostly opening this issue for discussion because SQL has a couple of related problems and maybe we can avoid some duplication of efforts. E.g. if there would be plans or easy opportunities to address this on the level of runtime fields.

**Comment by Luegg** [comment]
I've updated the PR description since it is a more general problem and also affects indexed fields (not only runtime fields).

**Comment by cbuescher** [comment]
This looks like a tie-breaker problem to me. I would say, technically the order is as expected, since missing values are correctly substituted by Long.MAX_VALUE. But if you really need to sort the docs with missing values at the end, there might be a workaround with using the same field as a tie-breaker, but different missing value setting and ordering:
```
{
  "sort": [
    {
      "l": {
        "order": "asc",
        "missing": "_last"
      }
    },
    {
      "l": {
        "order": "desc",
        "missing": 0  <- or some other small or negative value, maybe even MIN
      }
    }
  ]
}
```
I haven't fully thought this through but wanted to put it out here as an option thats already there.

**Comment by cbuescher** [comment]
> I have a similar problem.

Would you mind describing your use case? I'm interested to hear why missing values would need to appear strictly after Long.MAX_VALUE. Does the tie-breaker suggestion I mentioned above work for you? Why/why not?

**Comment by Luegg** [comment]
@cbuescher one downside I see with the tiebreaker solution is in combination with runtime fields. Because of the double evaluation of the field you might have to pay quite a performance penalty.

**Comment by javanna** [comment]
This seems to me like an edge case to me: docs have a field with long mix/max value as well as null values while results are sorted on that same field. @cbuescher proposed a work-around above: has that been verified as a solution for the problem? 

To follow-up on the performance penalty with runtime fields: while it is true that the runtime field needs then to be evaluated twice, and that has a cost, runtime fields have in general different performance characteristics compared to indexed fields, and I tend to think that this is an acceptable solution for an edge-case scenario despite the additional cost when the field is runtime. Also such runtime field can be made indexed to speed things up.

I would be curious to hear how common this situation is though, to understand if this is in fact an edge case or not.

**Comment by javanna** [comment]
Closing for lack of feedback, please reopen if you think otherwise.
