### ISSUE TITLE
Optimize loop in elasticsearch-env

### ISSUE THREAD

**Issue by jeff-schram** [elastic/elasticsearch#77862]
The loop where the environment variables are being 'filtered' contains a regex check performed by Bash. This can be really slow when dealing with a large amount of environment variables, adding minutes(!) to the start up time.

```bash
  while IFS='=' read -r envvar_key envvar_value
  do
    # Elasticsearch settings need to have at least two dot separated lowercase
    # words, e.g. `cluster.name`
    if [[ "$envvar_key" =~ ^[a-z0-9_]+\.[a-z0-9_]+ ]]; then
      if [[ ! -z $envvar_value ]]; then
        es_opt="-E${envvar_key}=${envvar_value}"
        es_arg_array+=("${es_opt}")
      fi
    fi
  done <<< "$(env)"
```

We currently patch this by replacing the `elasticsearch-env` file in the Docker image:
```
FROM elasticsearch:7.13.3
COPY elasticsearch-env /usr/share/elasticsearch/bin/
```

, where the loop has been modified as follows:
```
  while IFS='=' read -r envvar_key envvar_value
  do
    if [[ ! -z $envvar_value ]]; then
      echo "adding option ${envvar_key}=${envvar_value} to list of arguments"
      es_opt="-E${envvar_key}=${envvar_value}"
      es_arg_array+=("${es_opt}")
    fi
  # Elasticsearch settings need to have at least two dot separated lowercase words, e.g. `cluster.name`
  done <<< "$(env | egrep '^[a-z0-9_]+\.[a-z0-9_]+')"
```
This:
- takes the regex _out_ of the loop, and
- has the regex being performed by _egrep_ instead of _bash_ (=faster)

**Comment by mark-vieira** [comment]
Thanks for the report @jeff-schram. Would you be willing to submit a pull request with your proposed fix?

**Comment by jeff-schram** [comment]
@mark-vieira Yes. I am working on a fix based on the most recent _master_ (as a second regex has been added to the loop after 7.13.3 release). Do you want this "unit" tested (via e.g., [shunit2](https://github.com/kward/shunit2)? If so, what would be an appropriate location for such a test?

**Comment by mark-vieira** [comment]
We have existing test coverage for this capability, that is, passing in arbitrary settings via environment variables so there shouldn't be any need to add extra coverage since we're only refactoring existing code.

**Comment by jeff-schram** [comment]
Could you tell me which test(s) to run? When running ```gradlew check``` I get a single failing test both with and without my fix, but I am not sure this is covering the script. Thus far I am unable to run ```gradlew packagingTest``` successfully, it seems to be too demanding for my laptop.

Another question: do you also want me to submit a pull request for the _7.14_ branch?

**Comment by mark-vieira** [comment]
> Could you tell me which test(s) to run? 

When you open the pull request I can trigger the tests in our CI. Running `check` locally is likely to take hours.

**Comment by mark-vieira** [comment]
> Another question: do you also want me to submit a pull request for the 7.14 branch?

Once the PR against `master` is merged I'll follow up and backport.
