### ISSUE TITLE
MasterService#patchVersions is rather inefficient

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#77888]
Today `MasterService#patchVersions` creates a new `Metadata$Builder`, increments the version, and then calls `build()` which expensively recomputes a bunch of data structures, e.g. `Metadata#indicesLookup`. This is quite inefficient, we could just copy those data structures from the previous `Metadata` and save a bunch of work and garbage-generation.

This is what it looks like in a flamegraph:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/5058284/133643760-2b010f50-af05-49ca-b1d0-efad99f55e84.png">

That's only ~7.5% of the total time on this otherwise busy master, but we could still cut this in half.

**Comment by original-brownbear** [comment]
Closing this, this has disappeared from profiling entirely in `master` now due to the linked fixes.
