### ISSUE TITLE
[DOCS] Error resolution of "disk usage exceeded flood-stage watermark"

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#77906]
### error
@jrodewig I'd like to recommend the following text for resolving the common user encountered [error](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java#L91-L93) (core+variations)

core

> disk usage exceeded flood-stage watermark, index has read-only-allow-delete block. Affected indices [x,y]

variations

> HTTP 429 {'type':'cluster_block_exception','reason':'index [x] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block]'}

> [x] policy [y] for index [z] failed on step [{'phase':'hot','action':'rollover','name':'check-rollover-ready'}]. Moving to ERROR step org.elasticsearch.cluster.block.ClusterBlockException: index [z] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];

### response

I consistently offer this general copy/pasted advice to encountering users:

> Cloud and on-prem Elasticsearch clusters use [disk-based shard allocation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#disk-based-shard-allocation) to manage where they distribute index's shards within the cluster. This benefits spreading the load, preventing data overflow/overwrites, etc. Part of this feature is watermark levels (summarized w/default levels): 
> 
> - 75% UI disk allocation warns red colored but no system action
> - 85% low disk stops allocating shards
> - 90% high disk moves shards off node
> - 95% flood stage sets index to read-only (auto-unsets after)
> 
> Your current deployment status can be seen via API ([GET _cat/allocation?v=true](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-allocation.html)). Kibana may go down at the low disk (85%) mark and is practically guaranteed to go down at the flood stage (95%), because its system indices (`.kibana*`) will not be able to write updates. You may choose to temporarily override disk watermarks to be able to recover your cluster. To override:
> 
> ```
> PUT /_cluster/settings
> { "transient": {
>    "cluster.routing.allocation.disk.watermark.low": "90%",
>    "cluster.routing.allocation.disk.watermark.high": "95%",
>    "cluster.routing.allocation.disk.watermark.flood_stage": "97%" }}
> 
> PUT _all/_settings
> { "index.blocks.read_only_allow_delete": null }
> ```
> 
> After, to reset
> 
> ```
> PUT /_cluster/settings 
> { "transient": { 
>    "cluster.routing.allocation.disk.watermark.low": null,
>    "cluster.routing.allocation.disk.watermark.high": null,
>    "cluster.routing.allocation.disk.watermark.flood_stage": null }}
> ```
> 
> We recommend users scale out their cluster ([similar to hitting max heap](https://www.elastic.co/blog/managing-and-troubleshooting-elasticsearch-memory)), but alternatives/supplements include:
> 
> - decrease shards via deleting unnecessary/old data or turning off replicas for data you don't care to lose 
> - [use ILM](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html) to put data into [warm/cold storage](https://www.elastic.co/blog/hot-warm-architecture) so you can [shrink](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-shrink.html) it

### request

I'd like to recommend/request this be added to Elasticsearch documentation. I couldn't find a smooth way to incorporate it under [Disk-based shard allocation settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#disk-based-shard-allocation) though that seems to be the closet topic-wise. 🙏🏼

**Comment by DaveCTurner** [comment]
> Kibana may go down at the low disk (85%) mark

This deserves further investigation: it means that users must take action to move shards around before a node reaches 85%, but the whole point of disk-based shard allocation is to move shards around automatically so users don't have to think about this.

**Comment by jrodewig** [comment]
I think this may fit in well with [Fix common cluster issues](https://www.elastic.co/guide/en/elasticsearch/reference/master/fix-common-cluster-issues.html).

If there are no objections, I'll get started on a docs PR and add @DaveCTurner as a reviewer. We can update the PR or published docs if we decide to change the low disk watermark's default.
