### ISSUE TITLE
Java Update is required

### ISSUE THREAD

**Issue by markrwilson** [elastic/elasticsearch#78108]
Please update to the latest version of Java.

Thanks,
Mark

**Comment by tvernum** [comment]
@markrwilson 

Current releases of Elasticsearch (at the time of writing, this is v7.14.2 and v8.0.0-alpha2) bundle v16.0.2+7 of OpenJDK which is the latest available build.

If your local cluster is running on a different version, then that is likely to be something specific to your environment, and maybe it's something we can help with on the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).

See
- https://github.com/elastic/elasticsearch/blob/v7.14.2/build-tools-internal/version.properties#L5
- https://github.com/elastic/elasticsearch/blob/v8.0.0-alpha2/build-tools-internal/version.properties#L5

**Comment by droberts195** [comment]
Our tooling has just noticed that a new version is available too - see #78168.  @markrwilson subscribe to that issue if you want to follow the progress of the upgrade.

**Comment by pugnascotia** [comment]
We updated to JDK 17 in #78197.
