### ISSUE TITLE
Expose ability to invalidate deprecation log cache

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#78134]
Elasticsearch maintains an internal cache to represent each unique deprecation message. This helps to prevent spamming the deprecation logs with too much identical information. As a result, a deprecation message is only emitted to the log the first time it is encountered after a fresh start. Normally this is desirable. 

However, recently the Kibana Upgrade Assistant introduced a friendly UI to expose these deprecation logs inside Kibana. As part of the workflow, the user can "reset" the last time they reviewed the deprecation logs. This is to help a user remember the last time they examined the logs. The workflow is a user will read the logs, fix the deprecation, hit "reset", and then after a while has passed review any new log messages since the last "reset". Unless the user also restarts the servers, it will not reset the ability to for Elasticsearch to emit the deprecation logs. 

This request is to expose an API that Kibana can call when the user clicks the "reset" button that will invalidate the cache of emitted deprecation logs. This will allow a user to click "reset" in the Kibana UI and then deprecations will start emitting to the log file again. 

cc @cjcenizal

**Comment by cjcenizal** [comment]
Makes sense to me! Thanks for catching this Jake.

> As a result, a deprecation message is only emitted to the log the first time it is encountered after a fresh start.

I have to admit this isn't the behavior I've observed. When I tested out this feature on a 7.16 Cloud deployment, I saw numerous identical log messages being emitted.

**Comment by rjernst** [comment]
> I saw numerous identical log messages being emitted

The same deprecation can be emitted multiple times, but we *try* to not repeat the same. The cache is 128 entries, and the key includes the xopaqueid. Is it possible the cloud deployment had a lot of deprecations and the cache was thrashing?

Minor implementation note: this issue should not be difficult to do, as we already retain the filter we add to log4j, and have a reset method we expose so that the cache is reset when the deprecation index is enabled/disabled.

**Comment by cjcenizal** [comment]
@rjernst FWIW I just did a different test in which I submitted numerous requests to a deprecated API on 7.16 and I was able to observe the behavior Jake described.

Could you please loop me into work on this so I can verify the UX once it's merged?

**Comment by rdnm** [comment]
Hi @cjcenizal, @pgomulka will be looking into this one in the coming days. He'll reach out so you can validate on the UX side.
