### ISSUE TITLE
Mixed cluster tests failing in release builds due to feature flag

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#78219]
We have an issue which I believe is fallout from #77626. The root issue is that we are passing a feature flag, but when doing BWC tests, the BWC distribution isn't built in release mode.

```
»  Caused by: java.lang.IllegalArgumentException: es.index_mode_feature_flag_registered is only supported in non-snapshot builds
»  	at org.elasticsearch.index.IndexSettings.<clinit>(IndexSettings.java:351) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
»  	... 13 more
```

So in this case we are testing 8.0.0 against 7.16.0-SNAPSHOT. We pass `-Dbuild.snapshot=true` when bulding `master` (8.0.0) but not when building the BWC snapshot version (`7.x` or `7.16` in this case).

What we _should_ do I suppose depends on what we're trying to test here. Our options are:

1. We carry forward the `-Dbuild.snapshot` flag to the BWC builds so we are testing mixed "released" versions.
2. We only enable the feature flag on `master` nodes and omit it when configuring the BWC nodes.

**Comment by mark-vieira** [comment]
@nik9000 your thoughts on this one?

**Comment by nik9000** [comment]
Neat! I guess no matter how many times I run stuff locally I'm bound to miss something. 

I'm not sure the right fix here. I'm pretty sure we shouldn't feed the feature flag into any nodes that aren't snapshots. The build might need to filter them? I dunno. 

My intent with running bwc tests against a feature with the feature flag is so that I can know when we break bwc. And to test wire compatibility between versions. The feature flag gives us wide latitude but we still want to know when things change.

**Comment by mark-vieira** [comment]
> My intent with running bwc tests against a feature with the feature flag is so that I can know when we break bwc. And to test wire compatibility between versions. The feature flag gives us wide latitude but we still want to know when things change.

Right, maybe that's the bit I don't quite comprehend. The feature flag is in fact only _required_ for non-snapshot builds. That is, if I understand correctly, it's effectively implicitly enabled on snapshot builds, yes? So we're _already_ testing wire compatibility with this feature enabled in the normal BWC jobs. The only reason we'd enable the feature flag on release builds is because we have tests we're running that rely on the feature being enabled. I'll assume that's the case here. So in this case if we _don't_ enable the flag we'll get test failures, since our tests rely on the feature being enabled.

So now that I've though aloud for awhile I think what we _want_ to do is only set the flag on the `master` nodes here, yes?

**Comment by nik9000** [comment]
Master nodes or the master branch?

So long as the node isn't -SNAPSHOT it's safe to pass the flag. It won't do
anything on nodes that don't know about it. And the tests should skip on
those versions.

We will likely release 7.16.0 with this feature flag still in place. 7.16.0
will want the flag or it won't be able to run the tests against, say,
7.16.1-SNAPSHOT.

I guess it's a question of "what is a non-snapshot build supposed to test?"
I think maybe don't pass snapshot=false to the sub build and filter the
flag from all snapshot nodes. That feels ok.

**Comment by mark-vieira** [comment]
> Master nodes or the master branch?

In this case they're both the same thing.

> So long as the node isn't -SNAPSHOT it's safe to pass the flag. It won't do anything on nodes that don't know about it.

Right, the issue is for nodes that **do** know about it and **are** snapshots, they blow up.

> I think maybe don't pass snapshot=false to the sub build and filter theflag from all snapshot nodes. That feels ok.

Roger that. I'll get that sorted.

**Comment by nik9000** [comment]
Thanks so much!

**Comment by probakowski** [comment]
Another one: https://gradle-enterprise.elastic.co/s/sm7lkeykmv4ua

**Comment by mark-vieira** [comment]
Fix is in the works, been taking awhile to shake out all the issues.
