### ISSUE TITLE
Using incorrect Accept/Content-Type headers in compatibility mode has bad client-side UX

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch#78214]
Discovered this behavior when testing the compatibility mimetype (`application/vnd.elasticsearch+json?compatible-with=X`) being used with `Accept` and `Content-Type`. When using the compatibility mimetype in either `Accept` or `Content-Type` the other HTTP header if given must be set to the compatibility mimetype as well otherwise an error occurs.

When running the following command:

```
$ curl -k -XPOST -H "Accept: application/vnd.elasticsearch+json;compatible-with=7" \
  -H "Content-Type: application/json" -d '{"query":{"match_all":{}}}' \
  http://localhost:9200/_search
```

The error message server-side in the logs is a good one, can tell exactly what's wrong:

```
A compatible version is required on both Content-Type and Accept headers if either one has requested a compatible version and the compatible versions must match. Accept=application/vnd.elasticsearch+json;compatible-with=7, Content-Type=application/json
```

but client-side this is what's returned:

```
curl: (52) Empty reply from server
```

Elasticsearch doesn't send an HTTP response and instead hangs up the socket. This isn't a great user-experience, perhaps this can be changed to Elasticsearch returning a 4XX HTTP response (maybe 400, 406, 415?) with the error message above?

**Comment by jakelandis** [comment]
@sethpayne - The behavior of needing to setting both mime types the same value when both are sent is intentional. We don't want to allow a non-compatible request with a compatible response (or vice versa).

The lack of a proper response is a bug. Thanks for finding that, and please let me know if ^^ does not make sense or causes difficulty in adoption. 

cc @pgomulka

**Comment by sethmlarson** [comment]
@jakelandis The behavior of requiring both to be set when in compatibility mode is fine for clients.

Also I think you pinged Seth Payne on accident, the curse of multiple Seths on the same small team!

**Comment by pgomulka** [comment]
I totally forgot about this one. We have a separate issue for this one https://github.com/elastic/elasticsearch/issues/79060
will be fixed in https://github.com/elastic/elasticsearch/pull/80253
