### ISSUE TITLE
Create Database Profile for DbVis

### ISSUE THREAD

**Issue by sethpayne** [elastic/elasticsearch#78267]
DBVis is a SQL query tool that uses JDBC to interface with a wide range of databases including SQL Server, MySQL, and Oracle.  These, and other, databases have what DBVis calls "database profiles."  A database profile is a single XML file declaring what object types, actions and viewers/editors should be available in the DbVisualizer user interface for each specific database. For databases without a profile, DbVis uses the "generic" profile.

Today, our JDBC driver works well with this generic profile but usability can be improved by providing DBVis with a profile specifically for Elasticsearch SQL.  Documentation on how to create a profile can be found here:

http://confluence.dbvis.com/display/UG121/Database+Profiles

Once we have a database profile we will work with DBVis to distribute our JDBC driver with their packaged software.

**Comment by bpintea** [comment]
Integrated profile released in 13.0.0 version of [DbVisualiser](https://www.dbvis.com/whatsnew/).
