### ISSUE TITLE
Add `static` attribute for `threadNumber` in SnifferThreadFactory

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#78271]
When I create two highlevel rest clients with Sniffer, I find that the two sniffer threads have the same name `es_rest_client_snifferT#1]`, if we should distinguish the names.
https://github.com/elastic/elasticsearch/blob/1f490bc77506b7dc976f506e9ef43ee861676499/client/sniffer/src/main/java/org/elasticsearch/client/sniff/Sniffer.java#L294

```
"es_rest_client_sniffer[T#1]" #2360 daemon prio=5 os_prio=0 tid=0x00007facae1f4800 nid=0x2fcbd waiting on condition [0x00007fa6dbd34000]
"es_rest_client_sniffer[T#1]" #2282 daemon prio=5 os_prio=0 tid=0x00007facae1d8000 nid=0x2fc9c waiting on condition [0x00007fa6ddd54000]
```

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
