### ISSUE TITLE
Build folder containing doc snippets isn't being cleaned up as expected

### ISSUE THREAD

**Issue by edh-oss** [elastic/elasticsearch#78298]
In [RestTestsFromSnippetsTask](https://github.com/elastic/elasticsearch/blob/master/build-tools-internal/src/main/groovy/org/elasticsearch/gradle/internal/doc/RestTestsFromSnippetsTask.groovy) , it looks like the intended behavior is to delete the folder testRoot/rest-api-spec/test , if it already exists, then recreate it and fill it in with the generated doc snippets.  It doesn't work.  If you put some garbage.txt file in that folder, run "gradle :docs:buildRestTest", then check the results, you find that garbage.txt is still sitting there.  There are two problems.

The contructor includes this, where "outputRoot()" returns the folder to be deleted, as a java.io.File object:

```groovy
doFirst { outputRoot().delete() }
```

The intuitive thing would be for this closure to execute before the executeTask method, with the TaskAction annotation, found in the super class [SnippetsTask](https://github.com/elastic/elasticsearch/blob/master/build-tools-internal/src/main/groovy/org/elasticsearch/gradle/internal/doc/SnippetsTask.groovy) .  That's not what happens.  The executeTask method is called first.  Which means that snippets are being created before the attempted delete.  Related demonstration code below.

Since the delete is attempted after the snippets are created, one would expect the task to delete its own output.  This doesn't happen either, which brings us to the second problem.

We have a File object, pointing to a folder, and we call its delete method.  If the folder isn't empty, the delete fails.  It doesn't respond to failure by throwing an IOException, it just returns false.  We aren't checking the return value from delete(), so this goes unnoticed.

I was surprised by the result of calling doFirst() inside a Task constructor, so I wrote a bit of test code to convince myself the actual behavior was really happening.  Two files:

build.gradle
```gradle
task demoTask(type: SimpleTask)

tasks.named("demoTask").configure {
	doLast {
		println "In doLast block, declared in build.gradle"
	}
	doFirst {
		println "In doFirst block, declared in build.gradle"
	}
}
```
and buildSrc/src/main/java/SimpleTask.java
```java
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;
import org.gradle.api.model.ObjectFactory;

import javax.inject.Inject;


public class SimpleTask extends DefaultTask {

        @Inject
        public SimpleTask(ObjectFactory of) {
                System.out.println("In SimpleTask constructor");
                doFirst( (t) -> System.out.println("In doFirst lambda, added in the SimpleTask constructor") );
        }

        @TaskAction
        public void start() {
                System.out.println("In the start method, which has the TaskAction annotation");
        }
}
```

The resulting output:

$ gradle demoTask

**> Configure project :**
In SimpleTask constructor

**> Task :demoTask**
In doFirst block, declared in build.gradle
In the start method, which has the TaskAction annotation
In doFirst lambda, added in the SimpleTask constructor
In doLast block, declared in build.gradle

**Comment by edh-oss** [comment]
There's a related issue in gradle's github, regarding calling doFirst() from inside a constructor.  The short version is that the behavior we're seeing is the expected behavior.

https://github.com/gradle/gradle/issues/9142

**Comment by mark-vieira** [comment]
Thanks for the detailed report. Yes, the docs stuff is some of the remaining "legacy" build code we have that has a few issues. First, it's still written in Groovy whereas we've ported most everything else to Java, and second, it does task configuration inside a constructor which is not idiomatically sound. The _real_ fix for this is to essentially eliminate the `RestTestsFromSnippets` task and instead move all the logic into the docs plugin, since all we are really doing is applying some custom configuration to a `SnippetTask`.

In the meantime I've opened https://github.com/elastic/elasticsearch/pull/78653 to address the correctness issue described here.

**Comment by edh-oss** [comment]
I've got a pr that addresses this as well, #78299 .  Looking at both, I think your way is cleaner, so I'll go on and close mine.

I've been working on the Groovy->Java conversion for this code, combing out the closures, slashy strings and so forth.  I hadn't been thinking in terms of a broader reworking that would eliminate RestTestsFromSnippets as a separate subclass, but I'll give that some thought now.
