### ISSUE TITLE
[Error]: 'failed to authenticate user [elastic]' showed up while setting up 8.0 self-managed environment.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/elasticsearch#78359]
**Kibana version:**  8.0.0 snapshot self-managed environment

**Host OS**: Windows 10

While setting up on-prem 8.0 environment, we observed 'failed to authenticate user [elastic]' errors after running password interactive command. 
Though initially, on running elasticsearch bat file, host health status changed to green and shards started message was rendered. 
However, later after failure of password set up command, authentication errors showed up.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/135037507-34b9b7cd-fc1b-459c-a10d-37f6a7a88fd8.png)

![image](https://user-images.githubusercontent.com/72375798/135037581-686fad64-5f5f-48e6-ac75-4c699cafadc7.png)

**Logs:** 
[elasticsearch-logs.zip](https://github.com/elastic/elasticsearch/files/7241761/elasticsearch-logs.zip)

Could anybody look and confirm.

Please let us know if anything is required.

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by iverase** [comment]
Not sure if this can be caused by https://github.com/elastic/elasticsearch/pull/78304. How does the initial store gets created?

**Comment by jkakavas** [comment]
`8.0.0-SNAPSHOT` is built from the current master and as such I would suggest against using it for production purposes. That, said, the `setup-passwords-tool` will not be functional in 8.0.0 , at least not in the same way as it is today. See https://github.com/elastic/elasticsearch/pull/76902 for more details. 

For the current version of `8.0.0-SNAPSHOT`, right above your green highlighted square, you should be getting an output from elasticsearch telling you what the auto-generated password of the `elastic` user is. If you missed that or didn't note this down, then you can use `bin\elasticsearch-reset-elastic-password.bat` to set the password for the elastic user. 

We will be updating our docs accordingly as we move closer to the next major version release.

**Comment by dikshachauhan-qasource** [comment]
@jkakavas Thanks for the feedback. We will try this troubleshoot and will let you know if still stuck to proceed upon.

**Comment by dikshachauhan-qasource** [comment]
We are able to set up 8.0 self-managed environment with above provided feedback. Thanks @jkakavas
