### ISSUE TITLE
Fix unnecessary cache evictions when setting indices.fielddata.cache.size 

### ISSUE THREAD

**Issue by craigwi** [elastic/elasticsearch#7836]
As described in user group posts including 
https://groups.google.com/d/msgid/elasticsearch/07cfb705-1f13-40d5-b7b2-c5b84e328ddb%40googlegroups.com and https://groups.google.com/d/msgid/elasticsearch/14703918-0450-42c1-810b-edf3967951b6%40googlegroups.com

Guava needs some changes to better utilize ram when using eviction by size (e.g., when indices.fielddata.cache.size is set in ES).

Proposed changes to Guava are here https://code.google.com/r/craigwi-guava/.

Update: also opened Guava issue: https://code.google.com/p/guava-libraries/issues/detail?id=1854.

**Comment by clintongormley** [comment]
Guava has been removed. Closing
