### ISSUE TITLE
Field alias name is not in response

### ISSUE THREAD

**Issue by BICB4** [elastic/elasticsearch#78375]
If I set field alias I can query it, but the field name in response is not an alias, but an original name, I think if people query using alias field they are expecting it in response, similar to SQL synonyms/alias. Is this planned to be integrated into future releases?

**Comment by danhermann** [comment]
I don't believe there are any plans to change this in the near future. If you have further questions about field aliases, please ask them on the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).
