### ISSUE TITLE
Index overwrites alias

### ISSUE THREAD

**Issue by OlegYch** [elastic/elasticsearch#7838]
using 1.3.2
here is the scenario:
- i have an alias which points to an index
- i constantly write data to that alias
- the cluster (all 4 nodes) failed with an oome (because of an aggregation with lots of nested cardinalities) and i restarted all nodes at once
- i continue to write data while cluster is being restarted
- after restart i see that the alias is gone and is replaced by an index with the same name

**Comment by clintongormley** [comment]
@bleskes can we close this one?

**Comment by bleskes** [comment]
@clintongormley I think so, the chances of finding out what happened are really slim.
