### ISSUE TITLE
Add deprecation log for index template still using the boost parameter

### ISSUE THREAD

**Issue by sebelga** [elastic/elasticsearch#78396]
In https://github.com/elastic/elasticsearch/pull/62639 we removed support for the `boost` parameter.

I tested Kibana Upgrade assistant to make sure a user gets a deprecation warning if he has index templates that use the `boost` parameter and I realised that we don't get any deprecation log.

I have 2 index templates that use the `boost` parameter and this is the only warning that appears in Upgrade assistant

<img width="1421" alt="Screenshot 2021-09-28 at 15 55 55" src="https://user-images.githubusercontent.com/2854616/135112635-85468dfb-1ea1-4896-a768-72729d3f5204.png">

**Comment by jbaiera** [comment]
This is fixed with #81605
