### ISSUE TITLE
HLRC support for analytics plugin aggregations

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#78414]
It looks like we made an oversight when adding aggregations to the analytics plugin, and forgot to add the corresponding builders & response objects to the HLRC.  My understanding is that builders and tests need to be added [here](https://github.com/elastic/elasticsearch/tree/master/client/rest-high-level/src/main/java/org/elasticsearch/client/analytics) for all the aggregations defined in the analytics plugin.

Checklist:
 - [ ] BoxPlot
 - [ ] Cumulative Cardinality
 - [ ] Moving Percentiles
 - [ ] Multiterms
 - [ ] Normalize
 - [ ] Rate
 - [x] String Stats
 - [x] Top Metrics

Tagging the clients team for visibility, and in case there are steps I'm missing, but I think analytics team can do the work for this.

**Comment by wchaparro** [comment]
won't fix, HLRC being deprecated.
