### ISSUE TITLE
[CI] FIPS builds failing due to 'remote-cluster' domain object already registered

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#78477]
I think this might be fallout from https://github.com/elastic/elasticsearch/pull/78397. Seems this is only happening on `7.x` as well:

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=A%20problem%20occurred%20evaluating%20project%20%27:x-pack:qa:multi-cluster-search-security%27.%0A%3E%20Cannot%20add%20a%20ElasticsearchCluster%20with%20name%20%27remote-cluster%27%20as%20a%20ElasticsearchCluster%20with%20that%20name%20already%20exists.&search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles

The error is:
```
Cannot add a ElasticsearchCluster with name 'remote-cluster' as a ElasticsearchCluster with that name already exists.
```

**Comment by breskeby** [comment]
fixed by merging https://github.com/elastic/elasticsearch/pull/78076
