### ISSUE TITLE
Starting day of week configuration that affects DATE_PART / ES SQL

### ISSUE THREAD

**Issue by ghudgins** [elastic/elasticsearch#78515]
**When** I am querying using ES SQL
**And** I am extracting "weeks" from my date using [DATE_PART](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-datetime.html#sql-functions-datetime-part)
**I need** configuration option to specify the starting day of week for my country (not Sunday in Sweden) 
**So I can** use this functionality and return weeks that align with my stakehodlers

_Note: this use case is in SQL but there may be other QL's_

Example SQL from a requesting user:

```
SELECT DATE_PART('weeks', DATE_ADD('days', -1, csl.tid)) AS ....
```

If implemented (as a follow-on) Kibana could pass in its advanced setting "day of week" automatically for users.

**Comment by lucabelluccini** [comment]
Another place when week rounding is not "flexible" enough is with relative date math. E.g. `now-1w/w` is defaulting to Monday as start of the week.

**Comment by wchaparro** [comment]
@ninoslavmiskovic is this a requirement that is applicable to ES|QL as well?

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
