### ISSUE TITLE
[CI]  :distribution:docker:buildCloudDockerImage task failed

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#78513]
**Build scan**: https://gradle-enterprise.elastic.co/s/sw45bbm3ers3i

**Repro line**: Not available

**Reproduces locally?**: I haven't tried

**Applicable branches**: 7.x, possible others?

**Failure history**:

No similar failures in the 7 days.

**Failure excerpt**:

```
-- | --
  | Execution failed for task ':distribution:docker:buildCloudDockerImage'. |  
  | > A failure occurred while executing org.elasticsearch.gradle.internal.docker.DockerBuildTask$DockerBuildAction |  
  | > Process 'command 'docker'' finished with non-zero exit value 35
```

```
| [0m[91mcurl: (35) OpenSSL SSL_connect: SSL[0m[91m_ERROR_SYSCALL in conn[0m[91mection t[0m[91mo g[0m[91mithub-releases.githubuser[0m[91mcontent.com:443 
| [0mThe command '/bin/sh -c set -e ;     TINI_BIN="" ;     case "$(arch)" in         aarch64)             TINI_BIN='tini-arm64' ;             ;;         x86_64)             TINI_BIN='tini-amd64' ;             ;;         *) echo >&2 "Unsupported architecture $(arch)" ; exit 1 ;;     esac ;     curl --retry 10 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/${TINI_BIN}" ;     curl --retry 10 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/${TINI_BIN}.sha256sum" ;     sha256sum -c "${TINI_BIN}.sha256sum" ;     rm "${TINI_BIN}.sha256sum" ;     mv "${TINI_BIN}" /rootfs/bin/tini ;     chmod 0555 /rootfs/bin/tini' returned a non-zero code: 35
```

**Comment by pugnascotia** [comment]
I'd be very surprised if this was something other than a transient error. Mind you, that particular `curl` call is run with retry flags, and I wonder if there are some error conditions that cause `curl` not to retry? In which case we should apply the same `retry.loop` mechanism as we do elsewhere.

@mark-vieira WDYT?

**Comment by mark-vieira** [comment]
Yeah, it's a bit hard to grok with all those escape characters in the log but it's complaining about a connection timeout so yeah, I chaulk that up to transient network instability.

**Comment by martijnvg** [comment]
Apologies for opening this ci issue, the `chmod 0555 /rootfs/bin/tini' returned a non-zero code: 35` bit made me think that this CI failure was a non transient failure,  but several commands are combined together which I guess confused me.

**Comment by mark-vieira** [comment]
Yeah, these logs can be difficult to grok. @pugnascotia I wonder if we should use some combination of `-S -s` so that the download progress output doesn't garble up the console logs and make it overly difficult to read.

**Comment by idegtiarenko** [comment]
Looks like it happened again: https://gradle-enterprise.elastic.co/s/ri74kq7iwx7qa/console-log?anchor=1255
