### ISSUE TITLE
[Licensed Feature Tracking] Searchable Snapshots license level should be Enterprise, not Platinum

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#78573]
In https://github.com/elastic/elasticsearch/pull/77597, we started tracking usage of the Searchable Snapshots feature. The usage is returned by the `GET _license/feature_usage` API like so:

```json
{
  "features" : [
    {
      "family" : null,
      "name" : "searchable-snapshots",
      "context" : null,
      "last_used" : "2021-10-01T18:52:53.996Z",
      "license_level" : "platinum"
    }
  ]
}
```

Notice the `license_level` field in the response. It is set to `platinum`. However, according to https://www.elastic.co/subscriptions, Searchable Snapshots is an Enterprise level feature.

**Comment by ycombinator** [comment]
cc: @rjernst

**Comment by tlrx** [comment]
@ycombinator thanks for catching this!
