### ISSUE TITLE
Impossible to test Java class using SearchTemplateResponse 

### ISSUE THREAD

**Issue by jonathanfostercannon** [elastic/elasticsearch#78791]
**Elasticsearch version** (`bin/elasticsearch --version`):
    compile group: 'org.elasticsearch', name: 'elasticsearch', version: '7.12.1'
    compile group: 'org.elasticsearch.client', name: 'elasticsearch-rest-client', version: '7.12.1'
    compile group: 'org.elasticsearch.client', name: 'elasticsearch-rest-high-level-client', version: '7.12.1'

**Description of the problem including expected versus actual behavior**:

I'm using RestHighLevelClient in a Java codebase making a searchTemplate call, which returns SearchTemplateResponse

In tests, I am trying to instantiate a mock SearchTemplateResponse, similar to this discussion for SearchResponse (https://stackoverflow.com/questions/25425243/create-dummy-searchresponse-instance-for-elasticsearch-test-case). 

I get this error: 

```
error: SearchTemplateResponse(StreamInput) is not public in SearchTemplateResponse; cannot be accessed from outside package
```

In the source code, its unclear to me whether the constructor is public-- 

https://github.com/elastic/elasticsearch/blob/7.12/modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/SearchTemplateResponse.java#L40-L44

Thanks for your help 👋

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
