### ISSUE TITLE
Performance degradation introduced in #74559

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#78836]
Composite aggregation might become slower due to an optimization which was aiming to reduce memory usage in case the aggregated field required global ordinals (e.g. `keywords`), but ended up taking a lot more time in case the cardinality of the field is high.

Relates to #74559

**Comment by wchaparro** [comment]
hey there @jimczi @ywelsch @danielmitterdorfer should we also be backporting the composite changes reverted above also in the 8.x series?

**Comment by pquentin** [comment]
@wchaparro Unfortunately, we can't answer this question with data, as composite aggregations are not benchmarked in https://elasticsearch-benchmarks.elastic.co/, and plans to do so currently appear stalled.

**Comment by wchaparro** [comment]
Thanks @pquentin understood. 

@ywelsch what do you think?

**Comment by ywelsch** [comment]
I'm fine reverting this given the short timeline on which 8.0 is coming up. Either @not-napoleon can look into the forward-port, or I can do it.

**Comment by not-napoleon** [comment]
@ywelsch If you have time to do it, that would be great.  Otherwise I can.

**Comment by ywelsch** [comment]
Forward-port opened here: https://github.com/elastic/elasticsearch/pull/80498
I will give it a CI run and then merge
