### ISSUE TITLE
[DOCS] Document `INCOMPATIBLE` snapshot status

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#78852]
The _cat/snapshots API, snapshot status API, and get snapshot API can return an `INCOMPATIBLE` status:

https://github.com/elastic/elasticsearch/blob/90e340cb64b11bf68e084c11943146199e765322/server/src/main/java/org/elasticsearch/snapshots/SnapshotState.java#L14-L34

We should document this value in the docs and set up reuse to keep the docs synced.

**Comment by original-brownbear** [comment]
@jrodewig No need to document this one. I think we can safely remove that constant from both `8.x` and `7.x` at this point actually.

**Comment by jrodewig** [comment]
Thanks @original-brownbear.
