### ISSUE TITLE
Intermittent SocketTimeouts on upgrading Java Client Library from 6.2.2 to 7.9.2

### ISSUE THREAD

**Issue by amanullah92** [elastic/elasticsearch#79159]
Elasticsearch version: 7.9.2
Java Version: 1.8

We recently migrated ElasticSearch cluster from 6.2.2 to 6.8 to **7.9.2**. This worked well for us as long as we were using 6.2.2 Java client; however as per recommendation we upgraded the Java client library to 7.9.2. Since then, we see periodically see socket timeouts. We can see from monitoring graphs that requests are getting queued up on a single ES data node (on client side we see timeouts from all nodes though). Nature of the workload hasn't changed; when we revert the client version things go back to normal.

![image](https://user-images.githubusercontent.com/7847930/137340129-48acdf88-d374-43b9-bd66-6bb3dbeb5c22.png)

On that node where requests queue, we don't see any spike in CPU, disk activity,GC etc.

What could be amiss here?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
