### ISSUE TITLE
Unexpected length of keyword field in script

### ISSUE THREAD

**Issue by suiriass** [elastic/elasticsearch#79234]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.x

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
I implemented the relevant DSL in the 7.x version,
When we get the size of the field from the keyword field, it is not as expected,
Other types are displayed normally

I don't think this phenomenon is correct, please help me, thank you

![image](https://user-images.githubusercontent.com/49109065/137474850-ba4375f4-fc85-4e93-a28b-f8ad618dc299.png)

 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
@suiriass In addition, if you really want to count the values in the document `_source`, this should work as expected:
```
POST /test/_search
{
  "_source": [], 
  "script_fields": {
    "f1_size" : {
      "script" : {
        "source": "params['_source']['f1'].length"
      }
    },
    "f2_size" : {
      "script" : {
        "source": "params['_source']['f2'].length"
      }
    }
  }
}
```
@rjernst any downsides with this?

**Comment by nik9000** [comment]
> I think this behavior has been around for a lot longer than runtime fields, but, yeah. doc values for string only store unique values - it's a `SortedSetDocValuesField`, the _Set_ part of the name implied the deduplication. Numbers get `SortedNumericDocValuesField` - no deduplication.

Sorry for the lecture of stuff lots of folks know. I just figured it was worth writing it out here to give context.

**Comment by cbuescher** [comment]
@suiriass I hope you don't mind me closing this issue then since it seems to work as expected and there is an alternative that meets your needs.

**Comment by suiriass** [comment]
> @suiriass In addition, if you really want to count the values in the document `_source`, this should work as expected:
> 
> ```
> POST /test/_search
> {
>   "_source": [], 
>   "script_fields": {
>     "f1_size" : {
>       "script" : {
>         "source": "params['_source']['f1'].length"
>       }
>     },
>     "f2_size" : {
>       "script" : {
>         "source": "params['_source']['f2'].length"
>       }
>     }
>   }
> }
> ```
> 
> @rjernst any downsides with this?

This is the right way to use it, I've found it,

This is the right way to use it, I've found it,
This problem also exists in map_script scripted_metric in AGGS, such as doc[' field '].size() is still 2, I hope to get the real size, can handle all the values

**Comment by suiriass** [comment]
> pe you don't mind me closing this issue then since it seems to work as expected and there is an alternative that meets your needs.



> @suiriass I hope you don't mind me closing this issue then since it seems to work as expected and there is an alternative that meets your needs.

Thank you for your reply. The problem is actually from [map_script scripted_metric] in AGGS. The problem still exists, and I cannot get all the items correctly.

You want to see how it works in scripted_metric， thank  you.

**Comment by suiriass** [comment]
I have written a simple example to illustrate this problem and would like your help，thank you ,

![image](https://user-images.githubusercontent.com/49109065/137584369-62bbbcd0-a8c7-49f8-af25-90ddd36a7483.png)

`
PUT /test/
{
  "mappings": {
    "properties": {
      "f1" : {
        "type": "keyword"
      },
      "f2": {
        "type": "integer"
      }
    }
  }
}

PUT /test/_doc/1
{
  "f1" : [ "a", "b", "b", "b"],
  "f2" : [1, 2, 2, 2]
}


POST /test/_search
{
  "_source": [], 
  "script_fields": {
    "f1_size" : {
      "script" : {
        "source": "doc.f1.length"
      }
    },
    "f1_size2" : {
      "script" : {
        "source": "params._source.f1.length"
      }
    },
    "f2_size" : {
      "script" : {
        "source": "doc.f2.length"
      }
    }
  },
   "aggs": {
    "NAME": {
      "scripted_metric": {
        "init_script": "state.data=new HashMap()",
        "map_script": """
            int f1Size = doc['f1'].size();
            state.data.put("f1Size",f1Size);
            for (int i = 0;i < f1Size;i++){
              state.data.put("item--"+i,doc['f1'][i]);
            }
        """,
        "combine_script": "state.data",
        "reduce_script": """
           Map res = null;
           for (  s in states){
             res= s;
           }
           return res;
         """
      }
    }
  }
}
`

**Comment by suiriass** [comment]
Thank you for working correctly.
