### ISSUE TITLE
Packaging: Unify behaviour of executables in bin/

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#7946]
Right now the `bin/plugin` and `bin/elasticsearch` commands are treated very differently, which is not a problem unless the executables are packaged and moved outside the `bin/` folder of the distribution or the configuration files are moved somewhere else like into `/etc/elasticsearch/`

I propose a couple of changes to make it possible to execute `bin/plugin` without additional parameters, even in packaged environments.

* `bin/plugin` and `bin/elasticsearch` should try to parse the distribution configuration files like `/etc/default/elasticsearch` and `/etc/sysconfig/elasticsearch` - so that these can be used to configure the configuration directory. This also requires changes in those files, to make sure these are setting defaults instead of the init scripts like done in the debian script
* both should support `ES_JAVA_OPTS` (right now only `bin/elasticsearch` does)
* both should support the `--path.home` notation for setting properties, which might be needed to execute (right now only `bin/elasticsearch` does)

**Comment by clintongormley** [comment]
This has been resolved in other tickets
