### ISSUE TITLE
Docs build passes despite internal links in migration guide

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#79486]
The migration guide docs are re-used in the stack-wide [Install and Upgrade Guide](https://www.elastic.co/guide/en/elastic-stack/7.x/elasticsearch-breaking-changes.html) which means we cannot use internal links there. I've fallen foul of this rule multiple times, most recently [here](https://github.com/elastic/elasticsearch/pull/79451#discussion_r731974695). Could we fail the PR build on this misuse rather than relying on an eagle-eyed reviewer spotting the problem?

**Comment by lockewritesdocs** [comment]
While valid, we're moving towards a new doc system, and will be investing less time and resources in patching the old one. I'll mark this issue as closed unless someone has the bandwidth to carry it forward.
