### ISSUE TITLE
[CI] 7.x release tests failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#79538]
**Build scan**: https://gradle-enterprise.elastic.co/s/ucjdpa5q77mik

**Reproduces locally?**: yes

**Applicable branches**: 7.x

**Failure history**: A couple of days

**Failure excerpt**:

```
Execution failed for task ':distribution:bwc:maintenance:buildBwcOssTar'.
> Building 6.8.21 didn't generate expected artifact /dev/shm/elastic+elasticsearch+7.x+periodic+release-tests/distribution/bwc/maintenance/build/bwc/checkout-6.8/distribution/archives/oss-tar/build/distributions/elasticsearch-oss-6.8.21-SNAPSHOT.tar
```

Probably has to do with the version bump after release of 6.8.20

cc: @danhermann

**Comment by mark-vieira** [comment]
This is resolved by https://github.com/elastic/elasticsearch/pull/79644.
