### ISSUE TITLE
[CI] SnapshotLifecycleRestIT.testBasicTimeBasedRetention failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#79549]
**Build scan**: https://gradle-enterprise.elastic.co/s/sluoev3ttfqtm/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT/testBasicTimeBasedRetention?top-execution=1

**Repro line**: `./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.testBasicTimeBasedRetention" -Dtests.seed=9C07192018733E66 -Dtests.locale=nl-BE -Dtests.timezone=America/Guatemala -Druntime.java=11`

**Reproduces locally?**: didn't try

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT&tests.test=testBasicTimeBasedRetention

**Failure excerpt**:

```
AssertionError: expected snapshot to exist but it does not: {"error":{"root_cause":[{"type":"snapshot_missing_exception","reason":"[time-based-retention-repo:snap-jtopkav2rvqjzxd0eeljtw] is missing"}],"type":"snapshot_missing_exception","reason":"[time-based-retention-repo:snap-jtopkav2rvqjzxd0eeljtw] is missing"},"status":404} |  
```

**Comment by masseyke** [comment]
I haven't been able to reproduce this. But I put some logging in and found that the timed wait for the snapshot to be ready was always at about 10 seconds (which is the currently-configured limit). The snapshot itself is really fast but it looks like updating the cluster state can take a little time. I also checked that this was equally slow on versions back to 7.14.0, so I don't think it's a regression. It doesn't look like this fails very often (0 times in the last 28 days), so it seems likely that every once in a while we just slightly go over the timeout limit. I'll add a PR to increase that.
