### ISSUE TITLE
"x-elastic-product" header is not provided in 413 response 

### ISSUE THREAD

**Issue by mshustov** [elastic/elasticsearch#79684]
**Elasticsearch version**: the nightly version
Related to https://github.com/elastic/elasticsearch/issues/73424 cc @jbaiera 

**Description of the problem including expected versus actual behavior**:
Kibana is in process of upgrading `elasticsearch-js` dependency. https://github.com/elastic/kibana/pull/113950
The latest version of `elasticsearch-js` library checks `x-elastic-product` header presence in *every* response.
A Kibana integration test started suddenly failing because `413 Payload too large` error response doesn't contain the header.

**Steps to reproduce**:
- install kibana repository
- check out on `issue-108387-es-client-80` branch
- run `yarn kbn bootstrap` command
- run the test `src/core/server/saved_objects/migrationsv2/integration_tests/batch_size_bytes_exceeds_es_content_length.test.ts`

*expected* test passes
*actual* test fails with `Error: Unable to complete saved object migrations for the [.kibana] index. ProductNotSupportedError: The client noticed that the server is not Elasticsearch and we do not support this unknown product.]`

**Comment by rudolf** [comment]
Added the blocker label as this would be a release blocker for Kibana 8.0

**Comment by mshustov** [comment]
fixed in the ES client
