### ISSUE TITLE
Batch Cluster State Updates in Datastream Rollover

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#79782]
When using a large number of data-streams combined with rollover schedules that could cause the rollovers to collide a significant number of slow rollover CS updates can queue up. They are mainly slow due to having to run a reroute on every index creation, but also just come with the latency associated with any CS update.
This could lead to the normal priority CS updates getting blocked for many minutes which is not ideal.

Batching the cluster state updates in the `TransportRolloverAction` would allow for an efficient batching of reroutes out of the box as well as of the cluster state updates in general speed up the functionality.

relates #77466

**Comment by martijnvg** [comment]
Implemented via #79945
