### ISSUE TITLE
more helpful MapperParsingException errors?

### ISSUE THREAD

**Issue by CullyB** [elastic/elasticsearch#7983]
When adding some templates to elasticsearch I had:

dynamic_templates: [{"name": {<stuff>}, "other_name": {<stuff>}}]

when I needed:

[{"name": { <stuff> } }, {"other_name": { <stuff> } }]

however the error message 
 [2014-10-03 11:12:13,837][DEBUG][action.admin.indices.create] [logstash1p] [syslog-iophx-2014.10.03] failed to create org.elasticsearch.index.mapper.MapperParsingException: mapping [_default_]

Was less than helpful for determining where in the template to find the error.  It would be really cool if an error like that could be made a bit more descriptive to help with debugging

cheers

**Comment by clintongormley** [comment]
This has been greatly improved in 2.0

Closing
