### ISSUE TITLE
Disabling doc values silently ignored

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#7985]
If you create a field with `doc_values` set to `false` (or not specified), then trying to update the mapping to `true` throws an exception.

However, if `doc_values` is initially set to `true`, then trying to update it to `false` is silently ignored:

    DELETE /t
    PUT /t
    POST /t/_mapping/t
    {
      "properties": {
        "foo": {
          "type": "long",
          "doc_values": true
        }
      }
    }
    
    POST /t/_mapping/t
    {
      "properties": {
        "foo": {
          "type": "long",
          "doc_values": false
        }
      }
    }
    
    GET /t/_mapping

Returns:

    {
       "t": {
          "mappings": {
             "t": {
                "properties": {
                   "foo": {
                      "type": "long",
                      "doc_values": true
                   }
                }
             }
          }
       }
    }

**Comment by jpountz** [comment]
This has been fixed by @rjernst in the recent mappings fixes.
