### ISSUE TITLE
Security auto configuration assumes node.name == hostname

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#79881]
Security autoconfiguration sets 
```
cluster.initial_master_nodes: ["${HOSTNAME}"]
```

But it is possible that the local node already has a `node.name` configured.
If that's the case then the node cannot bootstrap a cluster.

We should either:
1. Skip auto configuration if the node has a name
2. Respect the node's name in the initial master nodes setting.

**Comment by jkakavas** [comment]
resolved by  #81007
