### ISSUE TITLE
Make org.elasticsearch.action.admin.cluster.state.ClusterStateResponse Compress the Cluster State

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#79906]
Unlike publication which uses a `org.elasticsearch.transport.BytesTransportRequest` that contains the cluster state as a compressed bytes reference, `org.elasticsearch.action.admin.cluster.state.ClusterStateResponse` does not compress the cluster state.

This is not ideal when it comes to very large cluster states that are requested via the get-cluster-state REST API from another node as these messages can become quite sizable. We should align the behavior here and use the same serialization approach in this message that we use for publication to limit the size of a full cluster state transport message (which will generally compress very well because settings and mappings tend to be duplicated heavily across indices). 

relates #77466

**Comment by DaveCTurner** [comment]
Today we compress the cluster state sent for join validation (https://github.com/elastic/elasticsearch/pull/85380) and publication, and we can avoid the need to send cluster states over the wire within a cluster for other reasons (https://github.com/elastic/elasticsearch/issues/86888), and to remote clusters (https://github.com/elastic/elasticsearch/issues/89456), so I think we can close this.
