### ISSUE TITLE
_cat/allocation output should filter non data nodes

### ISSUE THREAD

**Issue by suyograo** [elastic/elasticsearch#7998]
Shard allocation cannot happen on non data nodes, so there is no use showing `0b` for a non data node in the output. It is better to remove those rows

Example -- 
```
5 61.5gb 403.5gb 465.1gb 13 Suyogs-MacBook-Pro.local 192.168.1.6 Sphinxor
0     0b                    Suyogs-MacBook-Pro.local 192.168.1.6 Hoder
```

**Comment by clintongormley** [comment]
Not sure when but this has been implemented in 2.0. Closing
