### ISSUE TITLE
Optimize execute balancer.moveShards and  balancer.balance with control conditional

### ISSUE THREAD

**Issue by GrandFisher** [elastic/elasticsearch#80130]
I found that you are doing related optimization under the larger number of shards [#77466](https://github.com/elastic/elasticsearch/issues/77466)
In the case of hundreds of thousands of shards，balancer.moveShards will have a second-level overhead. 
Observation found that it seems unnecessary to execute moveShards for every operation involving reroute.

Here is a suggestion to help optimize：
Add boolean conditions to control  whether or not execute balancer.moveShards.
     1.    fixed time interval condition( Only allowed to execute a few minutes after the last execution）
     2.   Permission list  (Identify whether balancer.moveShards must be executed through reroute reason）

For a relatively stable ES cluster, it is difficult to become unstable in a short time and have to move the shards. Therefore, if multiple operations involving reroute are executed in a short period of time, there will be redundant balancer.moveShards methods to be executed, which will waste some time.

We did not test the overhead of balancer.balance,  but we think balancer.balance is similar to balancer.moveShards

**Comment by GrandFisher** [comment]
@AndrewO can someone see this issue ?

**Comment by DaveCTurner** [comment]
In a stable cluster `Balancer#moveShards` should just be verifying that every shard can remain in its current location. It's possible we can optimise that computation, but I don't think we can skip it entirely. Could you profile this method so we can understand how long it's really taking and whether there's any obvious optimisations?

**Comment by GrandFisher** [comment]
> In a stable cluster `Balancer#moveShards` should just be verifying that every shard can remain in its current location. It's possible we can optimise that computation, but I don't think we can skip it entirely. Could you profile this method so we can understand how long it's really taking and whether there's any obvious optimisations?

I don’t want to skip this logic entirely, I just want to not execute moveShards as each reroute.
please see the flamegraph(creating index) below,  the `Balancer#moveShards` overhead occupies a total of about 18%(total is 60s)
The cluster has 100 nodes  and more than 30w(300,000) shards
[master_t.svg.zip](https://github.com/elastic/elasticsearch/files/7602020/master_t.svg.zip)
the command for the flamegraph is 
`./profiler.sh -d 60 -f ./master_t.svg -e wall -t  -I  'org/elasticsearch/cluster/service/MasterService*'  pid`

**Comment by DaveCTurner** [comment]
I think the most recent shard allocator should be much cheaper in this respect so I am closing this.

That said, this flame graph shows that some of the allocation deciders become rather expensive in clusters of 100k shards (notably `DiskThresholdDecider`, `FilterAllocationDecider`, and `ShardsLimitAllocationDecider`). I think we'd be interested in optimisations that target these inefficiencies.
