### ISSUE TITLE
[CI] Checkstyle license header check fails on Windows

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#80182]
The task `:docs:checkstyleTest` fails regularly on Windows platforms, looks related to #79603.

**Build scan**:
https://gradle-enterprise.elastic.co/s/v4julezaoxpmk
https://gradle-enterprise.elastic.co/s/c2mi2ziflwcnk
https://gradle-enterprise.elastic.co/s/jzykxzzrjaari
and more

**Repro line**:

**Reproduces locally?**:
No (no windows platforms)

**Applicable branches**:
master

**Failure excerpt**:
```
:docs:checkstyleTest FAILED
[ant:checkstyle] [ERROR] C:\Users\jenkins\workspace\platform-support\365\docs\src\test\java\org\elasticsearch\smoketest\DocsClientYamlTestSuiteIT.java:1: Duplicate header javadocs are forbidden [MultipleHeaderJavadoc]
```

**Comment by breskeby** [comment]
waiting for backport to pass to call this done

**Comment by breskeby** [comment]
Fixes have been back ported
