### ISSUE TITLE
‘exists’ query not working for nested docs with norms=false

### ISSUE THREAD

**Issue by amatoba** [elastic/elasticsearch#80309]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.15.1

**Plugins installed**: []

**JVM version** (`java -version`): 11.0.9

**OS version** (`uname -a` if on a Unix-like system): Darwin Kernel Version 20.6.0

**Description of the problem including expected versus actual behavior**:

For fields within nested docs with norms disabled, querying for their existence via 'exists' query appears to not be working. It does however work when norms are enabled.  This works with 7.10.2, but no longer does in 7.14.1/7.15.1

Thanks for your help!

**Steps to reproduce**:
 1.
```
curl -XPUT localhost:9200/test -d '{
	"mappings": {
		"properties": {
			"user": {
				"type": "nested",
				"properties": {
					"first": {
						"type": "text",
						"norms": false
					},
					"last": {
						"type": "text"
					}
				}
			}
		}
	}
}'
```

 2.
```
curl -XPUT localhost:9200/test/_doc/1 -d '{
  "user" : [
    {
      "first" : "John",
      "last" :  "Smith"
    }
  ]
}'
```

 3.  Fails to find via `user.first`
```
curl -XGET localhost:9200/test/_search -d '{
	"query": {
		"nested": {
			"path": "user",
			"query": {
				"exists": {
					"field": "user.first"
				}
			}
		}
	}
}'
```

 4.  Succeeds to find via `user.last`
```
curl -XGET localhost:9200/test/_search -d '{
	"query": {
		"nested": {
			"path": "user",
			"query": {
				"exists": {
					"field": "user.last"
				}
			}
		}
	}
}'
```
**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Hi @amatoba, thanks for opening this! This was noticed before in https://github.com/elastic/elasticsearch/issues/76362 and has been fixed by https://github.com/elastic/elasticsearch/pull/78841, so I hope you don't mind that I close this as 'already fixed'.

**Comment by amatoba** [comment]
Wonderful!  Thanks!
