### ISSUE TITLE
invalid event name specified [change_password]

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#80326]
I tested in my docker-config with lines below.

      - xpack.security.audit.logfile.events.include=change_password

it threw this exeception.

```
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: invalid event name specified [change_password]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:171) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:158) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114) ~[elasticsearch-cli-7.15.0.jar:7.15.0]",
"at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:123) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.15.0.jar:7.15.0]",
"Caused by: java.lang.IllegalArgumentException: invalid event name specified [change_password]",
"at org.elasticsearch.xpack.security.audit.AuditLevel.parse(AuditLevel.java:78) ~[?:?]",
"at org.elasticsearch.xpack.security.audit.AuditLevel.parse(AuditLevel.java:85) ~[?:?]",
"at org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail.lambda$static$0(LoggingAuditTrail.java:198) ~[?:?]",
"at org.elasticsearch.common.settings.Setting.get(Setting.java:491) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.Setting.get(Setting.java:463) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:567) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:478) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:449) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:420) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-7.15.0.jar:7.15.0]",
uncaught exception in thread [main]
"at org.elasticsearch.node.Node.<init>(Node.java:452) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:288) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:219) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:219) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399) ~[elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167) ~[elasticsearch-7.15.0.jar:7.15.0]",
"... 6 more"] }
java.lang.IllegalArgumentException: invalid event name specified [change_password]
	at org.elasticsearch.xpack.security.audit.AuditLevel.parse(AuditLevel.java:78)
	at org.elasticsearch.xpack.security.audit.AuditLevel.parse(AuditLevel.java:85)
	at org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail.lambda$static$0(LoggingAuditTrail.java:198)
	at org.elasticsearch.common.settings.Setting.get(Setting.java:491)
	at org.elasticsearch.common.settings.Setting.get(Setting.java:463)
```

Looking at the [code](
https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/AuditLevel.java#L78)

and comparing all the events listed at https://www.elastic.co/guide/en/elasticsearch/reference/current/audit-event-types.html

[security_config_change](https://www.elastic.co/guide/en/elasticsearch/reference/current/audit-event-types.html#security-config-change) events appear to be missing from the code.

**Comment by ywangd** [comment]
@TomonoriSoejima This is a documentation issue similar to #78569 and is recently addressed by #79391. We can close this issue if you are happy with the updates in #79391

**Comment by TomonoriSoejima** [comment]
Hey @ywangd 
Thanks for checking.

I looked at the paragraph in https://github.com/elastic/elasticsearch/issues/78569


> The same sentence also states that "one or more of the following values" can be included in the audit config. However, all the security_config_change event actions cannot be specified individually, even if they are listed separately on the list.


And I added


`- xpack.security.audit.logfile.events.include=security_config_change`

Then I can see the audit log, but the limitation as mentioned above all the action will be included, correct?

`
{"type":"audit", "timestamp":"2021-11-05T01:22:32,946+0000", "node.id":"ab_A1RRITHybvK5s2Byuzg", "event.type":"security_config_change", "event.action":"change_password", "request.id":"22GafibTSdKRaPtiNNTiJw", "change":{"password":{"user":{"name":"remote_monitoring_user"}}}}
`

**Comment by ywangd** [comment]
> but the limitation as mentioned above all the action will be included

It's not a limitation, but rather by design. We hold the view that audit logs for security config changes should be either complete or none, because a partial set of logs for security config changes could be of limited usage and, worse, misleading or unexpected dangerous.

**Comment by TomonoriSoejima** [comment]
I totally agree now!
