### ISSUE TITLE
RequestConverters.java bulk(BulkRequest bulkRequest) is missing parameters.withWaitForActiveShards(bulkRequest.waitForActiveShards())

### ISSUE THREAD

**Issue by juels98** [elastic/elasticsearch#80382]
Hi,

We are using the elasticsearch-rest-high-level-client-7.10.0.jar. Also tested with latest jar- 7.15.1

When calling the bulk index call of the high level rest API in our code:

```
private static final BulkOptions indexOptions = BulkOptions.
                                            builder().
                                           withTimeout(TimeValue.timeValueSeconds(240)).
                                           withWaitForActiveShards(ActiveShardCount.from(10)).build();

List<IndexedObjectInformation> bulkResponses = elasticsearchOperations.
                                         bulkIndex(jsonDocs, indexOptions, IndexCoordinates.of(esIndex));
```

We noticed that if the index is in Yellow state, the insert still happens. With less than 10 shards being active the insert call should retry until the index turns green.

Debugging the high level rest client in my ide, I noticed that all the calls such as index, delete, create and so on, all specifically copy in to the RequestConverters.Params object the data for wait for active shards: **parameters.withWaitForActiveShards()** Bulk is the only converther that's missing it in org.elasticsearch.client.RequestConverters.java

Further, if during debug I add the **withWaitForActiveShards** parameter in to the bulk request, the retry actually happens. 

### **Current Bulk converter:**

```
 static Request bulk(BulkRequest bulkRequest) throws IOException {
        Request request = new Request("POST", "/_bulk");
        RequestConverters.Params parameters = new RequestConverters.Params();
        parameters.withTimeout(bulkRequest.timeout());
        parameters.withRefreshPolicy(bulkRequest.getRefreshPolicy());
        parameters.withPipeline(bulkRequest.pipeline());
        parameters.withRouting(bulkRequest.routing());
        XContentType bulkContentType = null;
```

### **Suggested Bulk converter:**

```
 static Request bulk(BulkRequest bulkRequest) throws IOException {
        Request request = new Request("POST", "/_bulk");
        RequestConverters.Params parameters = new RequestConverters.Params();
        parameters.withTimeout(bulkRequest.timeout());
        parameters.withRefreshPolicy(bulkRequest.getRefreshPolicy());
        parameters.withPipeline(bulkRequest.pipeline());
        parameters.withRouting(bulkRequest.routing());

**parameters.withWaitForActiveShards(bulkRequest.waitForActiveShards());**

        XContentType bulkContentType = null;
```

I think the fix should be to add withWaitForActiveShards to the bulk converter-- unless there's a specific reason why it's not there.

Thank you!
Julian

**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.1

**Plugins installed**: []

**JVM version** (`java -version`): java 8

**OS version** (`uname -a` if on a Unix-like system):

**Comment by juels98** [comment]
Hi, any update on this?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
