### ISSUE TITLE
Aggregations order : Escaping the user defined AGG_NAME

### ISSUE THREAD

**Issue by aaneja** [elastic/elasticsearch#8042]
The order by path has the form defined as  -
AGG_SEPARATOR       :=  '>'
METRIC_SEPARATOR    :=  '.'
AGG_NAME            :=  <the name of the aggregation>
METRIC              :=  <the name of the metric (in case of multi-value metrics aggregation)>
PATH                :=  <AGG_NAME>[<AGG_SEPARATOR><AGG_NAME>]*[<METRIC_SEPARATOR><METRIC>]

Since AGG_NAME can contain dots (.) which is the METRIC_SEPARATOR, is it possible to somehow quote the AGG_NAME ?

A similar problem would arise if the multi-value metric aggregation name is a part of AGG_NAME

**Comment by colings86** [comment]
closing in favour of #9059
