### ISSUE TITLE
Exception should be thrown if trying to enable ordinals on numeric/date field

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#8044]
Only string fields can generate eager global ordinals, but the mapper parser will happily accept the setting for numerics and dates.  This only becomes apparent in the logs later, when ES spams a bunch of warnings about being unable to convert the numeric into an ordinal.

It would be better if the mapper parser threw an exception up front so the user knew it was not a valid setting.

E.g.

```bash
PUT /my_index/_mapping/my_type
{
   "my_type":{
      "properties":{
         "my_double_field":{
            "type":"double",
            "fielddata":{
               "loading":"eager_global_ordinals"
            }
         }
      }
   }
}
```
```
{
   "acknowledged": true
}
```

And later in the logs:

```
[WARN ][index.warmer ] [prod-box] [my_index][5] failed to warm-up global ordinals for [my_double_field] 
java.lang.ClassCastException: org.elasticsearch.index.fielddata.plain.DoubleArrayIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexFieldData$WithOrdinals 
at org.elasticsearch.search.SearchService$FieldDataWarmer$3.run(SearchService.java:869) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)
```

**Comment by missinglink** [comment]
I'm also seeing `[2015-07-16 15:41:25,997][WARN ][index.warmer             ] [Omerta] [pelias][0] failed to warm-up global ordinals for [center_point]` for a `geo_point` type.

ref: https://github.com/pelias/schema/blob/master/mappings/partial/centroid.js

We're also seeing a very CPU happy cluster with not much indexing going on, is this possibly related?

**Comment by jpountz** [comment]
Fixed in master: the mapping is checked when parsed and global ordinals on numerics are rejected.
