### ISSUE TITLE
[CI] full cluster restart fails in release mode due to index_mode_feature_flag_registered

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#80479]
Fails similar to #79545 and after the fix #79572.

The problem seems to be a restart from a snapshot build to a non-snapshot one, which might be a broken test scenario.

**Build scan**:
https://gradle-enterprise.elastic.co/s/depvfeos3d5hc
**Repro line**:
```
gradlew :qa:full-cluster-restart:v8.0.0#oldClusterTest -Dbuild.snapshot=false -Dlicense.key="x-pack/license-tools/src/test/resources/public.key"
```
**Reproduces locally?**:
yes
**Applicable branches**:
master
**Failure history**:

**Failure excerpt**:

**Comment by nik9000** [comment]
I'm out for the next two days. @mark-vieira was cleaning up my mess here earlier so he might get to this before I do. But if he doesn't, I'll grab it.

**Comment by mark-vieira** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/80033
