### ISSUE TITLE
Request feature: BSON support

### ISSUE THREAD

**Issue by thangman22** [elastic/elasticsearch#8048]
Please add BSON format with Elasticsearch API because is faster than JSON

**Comment by jpountz** [comment]
@thangman22 Do you need BSON support specifically? The reason why I am asking is that we already support some binary json formats such as Smile.

**Comment by kimchy** [comment]
we also support CBOR

**Comment by marcustconnolly** [comment]
Hi there,I just found this page as I am wondering about the same thing. I am looking to save our MongoDB audit logs to BSON as it is supposed to be much for performant than JSON. We are looking to use the ELK Stack for all our logging and monitoring of logs, and not sure it can parse BSON at this time?

**Comment by clintongormley** [comment]
Hi @marcustconnolly 

As long as BSON is not supported by Jackson core, it is unlikely that we will add support for it.

**Comment by clintongormley** [comment]
We have no plans to support BSON. Closing
