### ISSUE TITLE
Allow RestHandlers for Content-Type outside XContentType 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#80482]
It is currently impossible for `RestHandler` to deal with requests that specify a `Content-Type` that doesn't map to `XCotentType` due to strict validation inside `RestController.`
This makes dealing with binary data (for supporting endpoints/protocols that already exist) impossible since the handler never gets access to the underlying request - the sender receiving the response: `Content-Type header [<non-xcontent-type>] is not supported`

It would be great to allow the validation to be pluggable similar to the `Allow` header - a `RestHandler` could return its own `MediaTypeRegistry` to specify the accepted `Content-Type` (including requests without the header being defined).

**Comment by pgomulka** [comment]
we discussed this on 24th Nov on core infra sync
We have at the moment a homogenous view on what content type is supported in all our apis. A client supporting JSON, YAML, CBOR, SMILE has a guarantee that it can talk with any of the endpoints. 
A new api that do not parse our standard XContent media types will break that guarantee. @bytebilly wants to investigate a little more on this side.

Another concern was this would end up available for all plugins, which might be risky and need to keep this in mind.
We also need to find out if cloud proxy will be able to support a custom media type on content-type header.

**Comment by pgomulka** [comment]
The use case is to allow `external system` to directly communicate with elasticsearch with its `external` content (which ES currently cannot read). At the moment for such `external system` we need to start filebeat/logstash which undersand those non `XContent` requests.
Such endpoints accepting custom content-type will effectively work as a translators for those requests

@philkra or @sethpayne can provide more details

**Comment by bytebilly** [comment]
Thanks @pgomulka for the great summary. Some additional context on the original reasons why this is enforced can be found here: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

I'd like to get some feedback on the following aspects:
- How is the content type handled in our language clients? In case we relax the constraint, would it be a simple way for developers to figure out which content type is allowed on a specific API without going to the documentation? Could language clients perform a per-api check to ensure that and warn developers if it's not the case? (@philkra)
- How could we prevent security implications? Are past concerns still valid and relevant today? Are new attacks possible if we relax this constraint? (@tvernum)
- how would it relate to Cloud? It's about our Cloud Proxy, but also other cloud-native common setups like service mesh. Is it something transparent to them, or should we care about implications? (@jowiho)

Unless we can get no concern by answering these questions, we'd probably need a strong benefit to move forward.
@costin I feel that having a concrete use case would really help to make a decision. Could you please share where the need is coming from?

cc @qhoxie

**Comment by tvernum** [comment]
The _Cross Site Request Forgery_ issue is still relevant, but our content-type protection really only requires that the media type __not__ be any of the following
- `application/x-www-form-urlencoded`
- `multipart/form-data`
- `text/plain`

(Per: https://fetch.spec.whatwg.org/#cors-safelisted-request-header)

As long as the Rest server rejects those content types, our CSRF protection doesn't change.

**Comment by jowiho** [comment]
> how would it relate to Cloud? It's about our Cloud Proxy, but also other cloud-native common setups like service mesh. Is it something transparent to them, or should we care about implications? 

As far as I know the Proxy doesn't care about the content type of ES requests (@igor-kupczynski please correct me if I'm overlooking something). Other Cloud services that connect to ES behave as regular clients, so they shouldn't be affected by a more relaxed content-type check.

**Comment by igor-kupczynski** [comment]
Thanks for the highlight Jochem. Indeed, in general the proxy doesn't  rely on the `Content-Type` header. We parse the http request headers, but then we stream the body (without parsing) to the backend.

There are some exceptions, but I think irrelevant here:
* We rely on `Content-Type` to detect gRPC requests https://github.com/elastic/cloud/blob/c1b0e522871cdf2147ee1a69db2966db6299608e/go/proxy/http/http.go#L375
  * These are fleet/agent IIRC
  * We use http2 for gRPC and http1.1 for all the other requests (don't remember on the top of my head why not http2 across the board)
*  We strip `Content-Type` and `Content-Length` headers for `HEAD` requests before forwarding them to the backends https://github.com/elastic/cloud/blob/41957a1f692166342170cb5748e4d520da862dc0/go/proxy/http/request_proxy.go#L427-L432
  * I don't remember why, some legacy behavior, we should probably look if this is still needed
* We also set the _response_ `Content-Type` when the proxy generates the response (backend not found, gateway timeout, traffic filters, etc.)

**Comment by igor-kupczynski** [comment]
Hey, ACK there should be no impact of changing ES requests `Content-Type`s on the cloud proxy.

**Comment by sethmlarson** [comment]
@bytebilly Language clients set the `Content-Type` documented in API specifications (the value set in `headers.content_type`) for APIs when a request body is given. Adding handlers for additional Content Types shouldn't impact clients.

> Could language clients perform a per-api check to ensure that and warn developers if it's not the case?

Language clients could check an overridden content-type against a list of known-good content-types for the API, however I'm not sure this is worth it as setting a custom content-type is an uncommon case.

**Comment by bytebilly** [comment]
@costin given the feedback above, I feel that there is no strong blocker if we can guarantee CSRF protection.
Do you already have a timeline for the Prometheus direct support?

**Comment by bytebilly** [comment]
@costin given the feedback above, I feel that there is no strong blocker if we can guarantee CSRF protection.
