### ISSUE TITLE
Group by on field with long string becomes null

### ISSUE THREAD

**Issue by alzamon** [elastic/elasticsearch#80491]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.0

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)

**OS version** (`uname -a` if on a Unix-like system):
Linux app-elasticsearch-master-0 5.4.154-1.el7.elrepo.x86_64 #1 SMP Fri Oct 15 13:02:21 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

On essql long strings in group_on key are converted to null.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Add a single document with one of the fields a long string [example document](https://github.com/elastic/elasticsearch/files/7497264/essql_bug_document.json.gz)
.
 2. Query for the document with essql grouping on the long field. For example (canvas): 
    ```
	filters
	| essql 
	  query="
	    SELECT tilsynskvittering_typeTilsynBeskrivelse as beskrivelse
	    FROM \"user_metrics-*\" 
	    GROUP BY beskrivelse"
    ```

    Resulting in one single row with `beskrivelse = null`. It should not be null. It should be the long string.

**Comment by alzamon** [comment]
I tried to work around the bug:

```
filters
| essql 
  query="
    SELECT SUBSTRING(tilsynskvittering_typeTilsynBeskrivelse, 0, 10) as beskrivelse
    FROM \"user_metrics-*\" 
    GROUP BY beskrivelse"
```

But it didn't help. Same result.

**Comment by Luegg** [comment]
@alzamon many thanks for your report. Can you also share the mapping of the index? I suspect that this might be cause by the `ignore_above` setting of the field (https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html). SQL uses the `.keyword` subfield of `text` fields for groupings.

**Comment by alzamon** [comment]
Thank you for the reply. Indeed as you say the field in question has a ignore_above field. 

```
       "tilsynskvittering_typeTilsynBeskrivelse": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
```

Still I didn't expect the outcome. If i do the same query without `group by` the field is populated with the long string. 
The index is created with a spring data elasticsearch entity. Could look into annotating the field there.

**Comment by Luegg** [comment]
Unfortunately, this is a limitation of ES itself. SQL cannot really work around that. If you need access to the original strings longer than 256 you can remove `ignore_above` (most likely with a significant storage cost).

If you want consistent behavior between non-grouping and grouping queries, you can also use the `.keyword` subfield explicitly as in `SELECT tilsynskvittering_typeTilsynBeskrivelse.keyword FROM ...`. This would return `null` for all long strings.

Or is there another outcome that you would have preferred in this situation (one that works with the mapping at hand)?

**Comment by alzamon** [comment]
I realize a big part of the problem was my ignorance to the field ignore_above. 

When I showed it to me the functionality is reasonable, although it is sad that the query just silently mis-groups.

Is there some way to fail hard when group by encounters null or a document exeeding ignore_above?

Maybe the best solution is simply to introduce a word of warning in the ["group by" documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-syntax-select.html#sql-syntax-group-by)?

What would you suggest as best solution?

**Comment by Luegg** [comment]
+1 for adding a warning in the docs. I think though that more features than just `GROUP BY` are affected. using these fields in a more complicated expression in `WHERE` and `ORDER BY` suffers from the same issue.

I don't know of a way to detect wether `ignore_above` applied. The easiest way that comes to my mind (if the field is assumed to always have a value otherwise) is probably to check for nullness and trigger an error on the client side in this case.

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
