### ISSUE TITLE
Kibana event log causes deprecation message

### ISSUE THREAD

**Issue by pmuellr** [elastic/elasticsearch#80512]
Strarting in stack 7.16.0, we're seeing a deprecation message regarding the Kibana event log (`kibana-event-log-*`):

    index name [.kibana-event-log-7.16.0-000001] starts with a dot '.', in the next major version, 
    index names starting with a dot are reserved for hidden indices and system indices

The message is correct; the index starts with a dot, and is not `hidden: true`.  However, in 8.0.0, we are setting `hidden: true` for these - it's been one of our "minor breaking changes" for 8.0.0.

The indices are created by Kibana at startup time (if needed), but the indices are ILM controlled, so we suspect when ILM rolls over another index, we'll see another deprecation message (haven't tested that yet though).

So, it's unfortunate timing to see this message appearing, when it's not the user's fault, and in fact the issue is resolved in the next major version.  There's nothing for the user to do.

Here's the issue on the Kibana side: https://github.com/elastic/kibana/issues/116341

We are currently evaluating making the index hidden in 7.16.0, or ... something else.  For instance, using the `x-elastic-product-origin: kibana` header on the creation request for the index.  However, it's not clear that header will work for that index - only a subset of indices can be affected by that header.  Also not clear whether we'd see the message from an ILM rollover, in which case we don't have an opportunity to use the header to suppress it.

**Comment by droberts195** [comment]
> it's been one of our "minor breaking changes" for 8.0.0

It's interesting that you consider making an internal index hidden a breaking change.

Almost all the other internal indices that were changed into hidden or system indices were changed in minor versions.  For example the ML indices that became hidden indices were made hidden in 7.7.  I think the logic here was that we didn't document that users should search them directly, and even if they did the change was only breaking if they were searching ML hidden indices as part of a broader search that also spanned into non-hidden indices.  (And of course that latter scenario is almost certainly a mistake and exactly what hidden indices are intended to stop people doing accidentally.)

So, unless you've been telling people to search, for example, `*event-log*` to find documents in both the Kibana event logs and other indices that happen to contain `event-log` in their names, I would just make newly created Kibana event log indices hidden.

**Comment by pmuellr** [comment]
Ya, in the end, I think you're right - it's not _that_ big of a change.  I don't _think_ it affects customers at all.

But we've made plenty of changes to our ES structures, that we didn't think were that big of a change, that came back to bite us. :-)  We figured better safe than sorry.

**Comment by pmuellr** [comment]
One option to avoiding the existing deprecation would be for us to use the `x-elastic-product-origin: kibana` header, with an updated list of "system indices", which seems to be here: 

[`modules/kibana/src/main/java/org/elasticsearch/kibana/KibanaPlugin.java`](https://github.com/elastic/elasticsearch/blob/main/modules/kibana/src/main/java/org/elasticsearch/kibana/KibanaPlugin.java)

Not suggesting we do that, neccessarily, just pointing out the change that would be needed if we wanted to use the magic header to resolve https://github.com/elastic/kibana/issues/116341

**Comment by gwbrown** [comment]
> One option to avoiding the existing deprecation would be for us to use the x-elastic-product-origin: kibana header, with an updated list of "system indices"

This is only a path we should take if we want to make the `.kibana-event-log*` indices into protected system indices that can only be queried by superusers, as that's what that list of "system indices" indicates. I think having this index be hidden is the right way to go, given my understand of the intended use of those indices.

If we want to address this in Elasticsearch, I think Colin's suggestion of suppressing the warning given the header (possibly a combination of the header and index name?) is probably the way to go.

**Comment by colings86** [comment]
I just noticed int he docs that the event log is experimental: https://www.elastic.co/guide/en/kibana/7.16/event-log-index.html

This makes me believe the right path here is to change the index to hidden in 7.16

**Comment by colings86** [comment]
Closing this issue as we are going to make the kibana event log hidden: https://github.com/elastic/kibana/issues/116341#issuecomment-965560142
