### ISSUE TITLE
Can not request http://es:9200 remotely

### ISSUE THREAD

**Issue by forfcw** [elastic/elasticsearch#80520]
docker image: 
> elasticsearch:7.13.2

docker command: 
> docker run -d --name es -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms256m -Xmx256m" -v elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml  elasticsearch:7.13.2

elasticsearch.yml:
> network.host: 0.0.0.0

I can access http://localhost:9200 with correct response, but can not access http://ip:9200. I have tried many schemes introduced online, but they are useless.
Looking forward to your reply, thanks!

**Comment by jkakavas** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
