### ISSUE TITLE
SQL: Should SELECT be able to retrieve document metadata fields?

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#80652]
ES offers some [metadata fields](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-fields.html) that offer additional information about a document currently not available through SQL.

There have been feature requests for individual metadata fields in the past. So this issue gives an overview of potential use cases and feature requests:

* `_index`
* `_id`: #30266 and a [feature request from the community](https://discuss.elastic.co/t/is-there-a-way-to-access-internal-id-and-type-fields-in-es-sql-query-xpack/174894)
* `_source` [feature request](https://discuss.elastic.co/t/sql-expose-source-in-sql-queries/170922/6)
* `_size`
* `_doc_count`
* `_field_names`
* `_ignored`: Not directly a feature request but the field could help with work around #80491
* `_routing`
* `_meta`
* `_tier`

It looks like not all metadata fields are available in the script context but some are. So, the feasibility for all of the fields is not yet clear. E.g. a simple sort on `_id` works as expected:

```
POST http://localhost:9201/test_emp/_search
Content-Type: application/json

{
    "sort": [
        {"_script": {
          "type": "string",
          "script": {
            "source": "doc['_id'].value",
            "lang": "painless"
          }
        }
      }
    ]
}
```

But the same query with `_tier` fails.

**Comment by lukaszgryglicki** [comment]
When I query multiple indices via using a wildcard for example `select field1, field2 from "index-*"` how can I get information about which index a particular row belongs to?
I've tried `select _index, field1, field2 from "index-*"` but `_index` is not available - this basically means that when I get the data, I don't know which individual index it comes from. Really?

**Comment by astefan** [comment]
@lukaszgryglicki I understand the frustration, but supporting meta fields is not so straightforward. A field in SQL needs to be covered in multiple areas: GROUP BY, ORDER BY, SELECT, WHERE and most meta fields are treated differently by Elasticsearch and cannot be used in these areas. Thus, our different approach to supporting them.

**Comment by wchaparro** [comment]
Superceded by ES|QL
