### ISSUE TITLE
Return _parent value by default for child documents

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#8068]
When you search or GET to retrieve documents you don't get back the value for `_parent` field (or `_routing` for that matter) which is part of the essential metadata. Meaning the document cannot be retrieved or updated without the value. This is breaking some functionality, example use cases:

* reindex (results of `scan` being fed into `bulk`) cannot work
* persistence layers on top of elasticsearch cannot update a document they retrieved from ES without additional info/queries
* you cannot GET a document you searched for (for example to retrieve fields you excluded)

I believe it would be worth the cost to retrieve the value of `_parent` field when retrieving a child document.

**Comment by colings86** [comment]
+1 for returning any stored fields that are not derived from the _source field

**Comment by clintongormley** [comment]
Fixed by #11816
