### ISSUE TITLE
At ES 7.15.1, The completion suggester is much slower than 7.8.1

### ISSUE THREAD

**Issue by drakejin** [elastic/elasticsearch#80683]
**Elasticsearch version** (`bin/elasticsearch --version`):

7.15.1

**Plugins installed**:
[official]
- discovery-ec2
- repository-s3
- analysis-nori
- analysis-kuromoji

[custom]
- https://github.com/javacafe-project/elasticsearch-plugin
- https://github.com/netcrazy/elasticsearch-jaso-analyzer

**JVM version** (`java -version`):
elasticsearch docker 7.15.1 default

**OS version** (`uname -a` if on a Unix-like system):

Amazon Linux 2 AMI
4.14.186-146.268.amzn2.x86_64
#1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

## In my company application, features of Completion suggester.
- Service Type: SNS
- Peak time 20:00 ~ 23:30
- Peak Traffic: 1700req/s ~2000req/s
- Shard settings: replica: ${nodes.size} / primary: 1
- Completion Suggester Index size: 2mb
- Cluster settings:
    - jvm.options: default JVM options + datanode 30Gb
    - seed/ several masters / several coordinates / several ingest / lots of data nodes/ 
    - offical elaticsearch Dockerfile on AWS EC2

    
**count of timeout / completeion suggester at 7.15.1**

![image](https://user-images.githubusercontent.com/10516961/141406457-c2400cad-b13a-41d1-8d94-ddca86a4109e.png)

**count of timeout / completeion suggester at 7.8.1**

![image](https://user-images.githubusercontent.com/10516961/141406365-a864fbe0-e056-46e5-8d05-bb32ff92b85c.png)

I just notice this report to elastic, I don't know what changes are in 7.15.1. I think there is a problem in elasticsearch 7.15.1.
Completion suggester feature is much slower than older version(in my case 7.8.1)

Thanks for your services.

**Comment by drakejin** [comment]
Oh, I got mistake the error count images were replaced each others 7.8.1 and 7.15.1. So, I was changed. Sorry for giving confuse

**Comment by cbuescher** [comment]
@drakejin does this mean we can close this issue?

**Comment by drakejin** [comment]
Nope, I got modified this issues what just change image's label

**Comment by drakejin** [comment]
7.15.1 still has bad performance at completion suggester. But, 7.8.1 didn't

**Comment by javanna** [comment]
Sorry to ask this after such a long time, but could you post your mappings, some data samples and your search requests? I was also not clear on how slower things get, or whether you get timeouts. Have you perhaps solved the problem by now?

**Comment by javanna** [comment]
This is an old issue that we did not get enough information to follow up on. Feel free to add more info if you have time, or try a more recent version to check out completion suggester performance. For now I am closing.
