### ISSUE TITLE
Concurrent Searching 

### ISSUE THREAD

**Issue by LifeIsStrange** [elastic/elasticsearch#80693]
It looks like Elasticsearch is currently missing support for concurrent searching and that this is a major prospective optimization to reduce latency.

Digression: this is not the topic at hand but I personally consider the fork OpenSearch to be an historical tragedy of duplication of work and a segregation of improvements. What would be even more anti-utilitarist would be to blindly *ignore* each other advances towards making better search.

Lucene concurrent search APIs are probably among the most important feature/optimization currently not leveraged by Elasticsearch.
The fork OpenSearch has a [pull request](https://github.com/opensearch-project/OpenSearch/pull/1500) implementing support for it.

See also the [corresponding issue](https://github.com/opensearch-project/OpenSearch/issues/1286) 

I believe it would be great for end users if you could take inspiration from the PR and work on this feature.

Great blog about the Lucene feature:
https://blog.mikemccandless.com/2019/10/concurrent-query-execution-in-apache.html?m=1
See also those performance results:
https://engineeringblog.yelp.com/2021/09/nrtsearch-yelps-fast-scalable-and-cost-effective-search-engine.html

**Comment by mayya-sharipova** [comment]
This has been discussed multiple times before, and [here](https://github.com/elastic/elasticsearch/issues/33159#issuecomment-426287583) is a good summary why have not done it so far. 

In short, we focus parallelization on processing multiple requests concurrently thus increasing throughput, rather than parallelizing a single request.

**Comment by LifeIsStrange** [comment]
I am not very qualified to defend the optimization but maybe that @mikemccand could do some justification?
1) Improving the latency of a single very complex request seems like a real use case for *niche advanced uses* (maybe some kinds of scientific computing?)
2) inter query and intra query parallelism seems to me like a complementary problem and having parallelism at both level shall in theory yield better latency for common workloads.
3) sure intra query parallelism might in some case adds overhead but 1) it would probably be an opt-in optimization and can be only applied in a fine-grained manner (I don't know if ElasticSearch/lucene has a performance cost model (a popular feature of e.g compiler where they have 1) a time/resource budget for optimizations, and 2) estimate the time/complexity of something), for ELK, if complexity of a query could be estimated (note that it has not to be only an a priori estimate, it can be refined empirically through measurement like PGO) then if complexity score of a query has a certain partern or is above a provided or determined threshold, then and eventually only then, leverage concurrent queries (intra query parallelism)
4) for completeness sake, an option to disable inter query parallelism would be nice or to be able to give precedence of one over the other depending on things such as latency vs throughput user preference?

Note btw that the cost of parallelism can be much lower than Java threads, either by leveraging a minimal amount of Kotlin code (using Coroutines) or through the soon to come Loom green (user space) threads.
Off-topic: I really think ELK should consider leveraging the Vector API.

**Comment by LifeIsStrange** [comment]
@javanna I see it has been privately discussed in march, any feedback about what was said?

BTW as a little update to my original comment, 
1) the opensearch implementation has been merged
2) Java Virtual threads are here, since the stable Java 19 release (as a feature preview, AKA contrary to an incubator JEP, a preview should be expected to have a mostly stable API. Therefore, (although I would prefer Kotlin) you can already tests virtual threads as a way to diminish the cost of simultaneous inter and intra parallelism. Note that the existing inter parallelism could still use regular threads.
But as a reminder, as explained in the original comment, even the regular threads cost is a non-issue, in the case you would use a time/complexity dynamic allocation budget, with automatic shrinkage and optionally speculative threading (growable) and ideally empiric real time metrics feedback (such as total cpu use vs througput/latency evolution). Then one could even implement a cache for which optimal configuration to perform for a given query. Let's say you have a recurrent complex query and that after said monitoring, it has been determined that using X (virtual or not) threads for intra parallelism and Y for inter. and that this configuration is the fastests found for said query (e.g. 50% faster than inter para alone), then the bonus idea would be to cache this configuration (key: query Z UUID, value: optimal configuration for said query, or hints).
Then (if cache not invalidated/expired), in the next hour, the same query is sent, and we can directly use the optimal configuration rather than wait again for the JIT metrics to find back the optimal conf.
Note this optimization is less important than the other mentionned.

**Comment by javanna** [comment]
@LifeIsStrange not much to add, this is quite high in the list of things we want to do. The list is long :) We'd prefer not to compromise and apply concurrency only to the query, but also to aggregations.
