### ISSUE TITLE
PathTrie wrongly adds params

### ISSUE THREAD

**Issue by wy96f** [elastic/elasticsearch#8071]
For instance, PathTrie builds two tries: "/a/{x}/b", "/{y}/c/d".  While retrieving "/a/c/d", it breaks for the params are {x=c, y=a} instead of {y=a}. We should push params before retrieving next token and pop them if we have to use wildcard to retrieve again.

**Comment by jasontedor** [comment]
Is this causing any actual bugs in Elasticsearch today?

**Comment by clintongormley** [comment]
No further feedback.  Closing
