### ISSUE TITLE
Support MaxMind GeoIP2-ISP.mmdb Database for Geoip Processor

### ISSUE THREAD

**Issue by bvader** [elastic/elasticsearch#80748]
Please Support the MaxMind `GeoIP2-ISP.mmdb` Commercially Licensed Database it is part of the commercially available MaxMind Databases.

See [MaxMind DBs Here](https://www.maxmind.com/en/geoip2-databases)

As a User I would like to enrich incoming IPs with ISP information. 

Today Logstash does support enriching with this `GeoIP2-ISP.mmdb` database however Elasticsearch Geoip processor does not. 

```
PUT _ingest/pipeline/isp-lookup
{
  "description": "Adds geoip info for ECS documents",
  "processors": [
    {
      "geoip": {
        "database_file": "GeoIP2-ISP.mmdb",
        "field": "client.ip",
        "ignore_missing": true,
        "target_field": "client.as"
      }
    }
  ]
}
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "[database_file] Unsupported database type [GeoIP2-ISP]",
        "property_name" : "database_file",
        "processor_type" : "geoip"
      }
    ],
    "type" : "parse_exception",
    "reason" : "[database_file] Unsupported database type [GeoIP2-ISP]",
    "property_name" : "database_file",
    "processor_type" : "geoip"
  },
  "status" : 400
}

```

**Comment by jakelandis** [comment]
This would be a great enhancement. We will need to reach out to MaxMind to see if they offer sample/test data bases we could use for testing.

**Comment by joegallo** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/108651
