### ISSUE TITLE
Add flag to Cluster State to return info on only Unassigned Shards

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#80787]
👋🏼 howdy! I believe this is a more global request of https://github.com/elastic/elasticsearch/issues/58030 & not similar ballpark to but believe not duplicate of https://github.com/elastic/elasticsearch/issues/29925. Kindly deduplicate as needed.

### context
 If I understand correctly, humans can use [CAT Shards](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html) to output unassigned reasons/descriptions but should use [Cluster State](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html) for automated programs sitting on top. I personally prefer this view rather than manually requesting against each shard via [Cluster Allocation Explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html). 

So a global manual introspection will be from:

```
GET _cat/shards?v&h=i,s,pr,n,st,dc,ur,ud
```

for any `ur != NULL`. This is effectively a variant of visually combing through

```
GET _cluster/state/routing_table
```

### request

For code automations, is it possible to 

1. add a flag to only return shards of `state:UNASSIGNED`, or dynamic value, or `state:!STARTED`
2. include `unassigned_description` in the Cluster State output (_Note_: I'm not sure this doesn't exist. I may just be missing this from my personal testing.)

### example

From

![image](https://user-images.githubusercontent.com/26751266/142090087-15391221-811e-424a-a5f0-9dbb025b915f.png)

![image](https://user-images.githubusercontent.com/26751266/142090150-ab9a5445-f191-4b86-8f51-0f0de69ceb3f.png)

To 

![image](https://user-images.githubusercontent.com/26751266/142090423-33a32afd-329f-4589-82b0-dfcc590cb028.png)

**Comment by nik9000** [comment]
> but should use [Cluster State](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html) for automated programs sitting on top.

Years ago we talked about cluster state more like a debug API and had hoped to build other more stable things on top. Like allocation explain. But it's been a while. Maybe we've changed out mind.

**Comment by stefnestor** [comment]
@nik9000 that might be totally true, in which case I'd pivot to a global return all unassigned shards at once very similar to either of these call's info 😄

**Comment by DaveCTurner** [comment]
I think we won't add this feature to `GET _cluster/state` in the foreseeable future. Instead, we expect the health API to offer a more user-friendly method for diagnosing cluster problems including unassigned shards. Therefore I'm closing this.

**Comment by stefnestor** [comment]
The [JQ](https://stedolan.github.io/jq/manual) version of this idea is

```
$ cat cluster_state.json | jq -rc '.routing_table.indices|to_entries[]|.key as $i|.value.shards|to_entries[]|.key as $s|.value[] as $v|select($v.state=="UNASSIGNED")|[$v.primary, $s, $i,  $v.unassigned_info.allocation_status, $v.recovery_source.type]|@tsv' | sort -r | column -t | head

# primary, shard, index, allocation_status, recovery_type
true  1  winlogbeat-xquisite-landscaping-7.13.4-2022.10.31                    no_valid_shard_copy  EXISTING_STORE
true  1  winlogbeat-wooster-hospital-7.13.4-2022.11.02                        no_valid_shard_copy  EXISTING_STORE
```

This is helpful vs the closest CAT Shards request reports

```
> GET _cat/shards?v&h=i,s,pr,n,st,dc,ur,ud | grep UNASSIGNED

# index, shard, primary, status, unassigned.reason, unassigned.description
.ds-logs-system.system-512-2022.10.31-000008                        0 p                      UNASSIGNED           INDEX_CLOSED 
.ds-logs-windows.powershell_operational-556-2022.10.31-000003       0 p                      UNASSIGNED           INDEX_CLOSED 
```

@DaveCTurner, could we consider same ballpark but opposite side for adding a flag to CAT Shards to specifically query `state:UNASSIGNED` shards?

**Comment by DaveCTurner** [comment]
I don't think anything has changed on this front since my last comment. We still think the health API is the right place to help users identify and resolve cluster problems, including unassigned shards.
