### ISSUE TITLE
Memory leak occurs after upgrading es version to 7.14.1

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch#80790]
**Elasticsearch version** (`bin/elasticsearch --version`):
14.1
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.
![image](https://user-images.githubusercontent.com/3234989/142177922-15c6f929-ce30-483c-ac83-6941dacdcd93.png)
![image](https://user-images.githubusercontent.com/3234989/142178134-1d7cbf8e-c599-43d5-b944-a7bf57020928.png)
![image](https://user-images.githubusercontent.com/3234989/142178240-41d7a597-37d0-440f-9b63-5306558d645e.png)
11 days have passed since the upgrade, the previous version was 7.9.2 and it worked well for more than a few months

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
Can you reproduce this in 7.15.2 or later? https://github.com/elastic/elasticsearch/pull/80166 addresses a memory leak that might explain this.

**Comment by zcola** [comment]
> Can you reproduce this in 7.15.2 or later? #80166 addresses a memory leak that might explain this.

It has been upgraded 7.15.2, let’s take a look in 12 days, it’s working well now

**Comment by DaveCTurner** [comment]
:+1: ok we'll close this as it seems resolved. If you continue to have problems then please let us know and we can re-open it.

**Comment by ramramase** [comment]
200

**Comment by jgq2008303393** [comment]
we want to know from which version does the bug begin?
