### ISSUE TITLE
Prevent too many agg buckets from causing OOM

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8081]
Once of the last places we see OOM conditions is in aggregations, when combinatorial explosion results in too many buckets being assigned.

We need a way to catch these conditions and abort the request rather than running into OOM.

**Comment by Fizzadar** [comment]
We're not capturing OOM exceptions with a filters aggregations, would this count as a combinatorial aggregation that this issue would fix?

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/9825

**Comment by blavoie** [comment]
+1

**Comment by dakrone** [comment]
@clintongormley do you think this can be considered fixed by https://github.com/elastic/elasticsearch/pull/19394/ ?

**Comment by clintongormley** [comment]
@dakrone yes!  Closing

**Comment by synhershko** [comment]
This still seems to happen, re-opened as https://github.com/elastic/elasticsearch/issues/35896
