### ISSUE TITLE
coordinating node OOM without triggering circuit breakers 7.15.1

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#80872]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.15.1
**JVM version** (`java -version`):
OpenJDK 64-Bit Server VM; 17; 17+35; mixed mode, sharing
**OS version** (`uname -a` if on a Unix-like system):
Red Hat Enterprise Linux Server 7.9 (Maipo)
**Description of the problem including expected versus actual behavior**:
Expected behaviour is parent circuit breaker (and other circuit breakers) should prevent OOM
Coordinating node with 4Gb JVM Heap Space and 2 CPUs OOMed (after 1 month without issue), heap dump shows : 
- 1 of 2 transport_worker (2 CPUs) thread used 52+% of heap (there is a 1000 SearchHits array of 1+Gb. 25+%), and OOM is visible on the other transport_worker thread
- 2 instances on class org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregator$FilterByFilter totalled 58% retained heap
- All 4 search threads were waiting

(refer to linked internal sdh)

**Comment by jtibshirani** [comment]
@jguay I don't think this makes sense as a public issue in this repository: there is no self-contained description of the problem. I think we should continue to investigate the OOM in the internal case, and if we narrow it down to a specific Elasticsearch issue then we can file a bug here.
