### ISSUE TITLE
Should system index migration block Cloud upgrade?

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#80896]
CC @williamrandolph On Cloud, upgrading is currently blocked if the user has any unaddressed `critical` ES deprecation issues or `critical` Kibana deprecation issues. Should we also block the upgrade until the user has executed the system index migration?

**Comment by cjcenizal** [comment]
CC @sabarasaba

**Comment by williamrandolph** [comment]
I'm sorry for missing this. We ought to block the upgrade if system features have not been migrated. The problem is that if a system feature has an unmigrated 6.x index, it will be unreadable in 8.x, and it may not be possible to roll back and recover.

**Comment by cjcenizal** [comment]
Thanks @williamrandolph! This will be fixed by https://github.com/elastic/kibana/issues/121333. Closing in favor of that issue.
