### ISSUE TITLE
CCR unable to open any proxy connections  

### ISSUE THREAD

**Issue by fabry00** [elastic/elasticsearch#80898]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.15

**Plugins installed**: default plugins in the docker image

**JVM version** (`java -version`): docker image

**OS version** (`uname -a` if on a Unix-like system): docker image

**Description of the problem including expected versus actual behavior**:

We have 2 separated  ELK clusters (3 nodes each) deployed in 2 different locations in Openshift. 
To deploy we are using a helm (no operator yet).
We enabled the CCR between them. The CCR connection is going through a F5 LoadBalancer.
The cluster is configured with security and TSL enabled.

The cross cluster replication is working fine but sometimes we see the following exception:

`[2021-11-19T14:16:58,628][WARN ][o.e.t.TcpTransport       ] [elasticsearch-master-0] exception caught on transport layer [Netty4TcpChannel{localAddress=/XXX.XXX.XXX.XXX:47822, remoteAddress=elk-master.local.net/YYY.YYY.YYY.YYY:443, profile=default}], closing connection

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

 

Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

 

[2021-11-19T14:16:58,629][WARN ][o.e.x.c.a.ShardFollowNodeTask] [elasticsearch-master-0] shard follow task encounter non-retryable error

java.lang.IllegalStateException: Unable to open any proxy connections to remote cluster [elasticsearch-cluster-2]
`

Now we do not know exactly what is going on since the CCR before this exception was working fine. Maybe the F5 LB sometimes closes the connections or maybe sometime we have some network issue, we are still investigating.
However after we get that exception the CCR is broken.

To solve this issue we just have to restart the POD without ANY modification and the CCR starts to work again:

`[2021-11-22T10:24:31,168][INFO ][o.e.x.c.a.ShardFollowTasksExecutor] [elasticsearch-master-0] [myindex-2021.11.18-000001][0] Starting to track leader shard [myindex-2021.11.18-000001][0]

[2021-11-22T10:24:31,558][INFO ][o.e.x.c.a.ShardFollowNodeTask] [elasticsearch-master-0] [myindex-2021.11.18-000001][0] following leader shard [myindex-2021.11.18-000001][0], follower global checkpoint=[-1], mapping version=[2], settings version=[1], aliases version=[1]
`

Now I do not know if this is a bug or intended but we would like to find a solution in order to not have this issues again. From my point of view ELK should retry to open the proxy connections automatically.

Here the CCR settings:

`{
  "persistent" : {
    "cluster" : {
      "remote" : {
        "${REMOTE_CLUSTER_NAME}" : {
          "mode": "proxy",
          "proxy_address": "${remote_route}",
          "transport.ping_schedule": "5s"
        }
      }
    }
  }
}
`
**Steps to reproduce**:

Don't really know how to replicate this issue.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. In particular:

> From my point of view ELK should retry to open the proxy connections automatically.

The error `javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` indicates that there is a problem in your TLS config, and it's not appropriate to retry in this case. Config problems are unlikely to be resolved by retrying, and if retrying does help then it's just hiding the underlying problem that should be addressed instead.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by DaveCTurner** [comment]
I looked at this a bit more; while I still think you have a problem in your TLS config that needs to be addressed, I also think that there are similar situations in which we should retry but don't today. I'll open a PR shortly.
