### ISSUE TITLE
[+DOC] Shard Unassigned Reasons

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#80892]
Howdy! I like using [CAT Shards](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html)'s `unassigned.reason` as reference, but just ran into an undocumented one and realized [the code](https://github.com/elastic/elasticsearch/blob/26c86871fc091900952e88e252c36fbfedf8d5fa/server/src/main/java/org/elasticsearch/cluster/routing/UnassignedInfo.java#L67) includes a couple others as well. 

Can you append info on [these](https://github.com/elastic/elasticsearch/blob/26c86871fc091900952e88e252c36fbfedf8d5fa/server/src/main/java/org/elasticsearch/cluster/routing/UnassignedInfo.java#L116-L136)
- PRIMARY_FAILED
- FORCED_EMPTY_PRIMARY
- MANUAL_ALLOCATION
- INDEX_CLOSED
- NODE_RESTARTING

I'm not sure if you're prefer a literal code copy/paste, but am experiencing `MANUAL_ALLOCATION` if you have more information on it. Cheers!

**Comment by DaveCTurner** [comment]
FWIW I think we should expand the description of this field in the docs too. Today we say

> Reason the shard is unassigned.

That's not really true, or at least it's a bit misleading to phrase it like this. The reason the shard is unassigned is often fairly complex and needs someone to use the allocation explain API to investigate. This field describes the event that caused the shard to become unassigned in the first place, which is rarely very interesting.

`MANUAL_ALLOCATION` just means that someone has hit `POST _cluster/reroute?retry_failed` to reset the failed-allocation counter.
