### ISSUE TITLE
Completion Suggester Highlighting

### ISSUE THREAD

**Issue by FabianKoestring** [elastic/elasticsearch#8089]
## Highlighting
Many search-as-you-type implementations highlight the portion of the term which has already been entered. We plan to add this to the response as we well.
[You complete me (August 22, 2013)](http://www.elasticsearch.org/blog/you-complete-me/)

Are there any plans when these feature will be implemented?

**Comment by AIsaac08** [comment]
+1

**Comment by clintongormley** [comment]
Looks unlikely that we'll be able to implement this.  If it is added to Lucene (see https://issues.apache.org/jira/browse/LUCENE-4518) then we'll get access to it.  No need to keep this issue open.
