### ISSUE TITLE
[CI] SnapshotBasedRecoveryIT testSnapshotBasedRecovery failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#80939]
**Build scan**:

https://gradle-enterprise.elastic.co/s/jduqowizzdlzg

**Repro line**:

`gradlew ':qa:rolling-upgrade:v7.16.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=3C3FC5FDBBCA3766 -Dtests.bwc=true -Dtests.locale=en-MT -Dtests.timezone=America/Thule -Druntime.java=17`

**Reproduces locally?**:

No

**Applicable branches**:

Master

**Failure history**:

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.upgrades.SnapshotBasedRecoveryIT&tests.sortField=FAILED&tests.test=testSnapshotBasedRecovery&tests.unstableOnly=true

**Failure excerpt**:

```
ava.lang.AssertionError: timed out waiting for green state for index [snapshot_based_recovery] cluster state
...
```

**Comment by fcofdez** [comment]
It seems like the primary still ends up in the upgraded node sometimes. I'll check why this is happening.

**Comment by davidkyle** [comment]
Another instance this time upgrading from 8.0.0

https://gradle-enterprise.elastic.co/s/onxufud43p4li/tests/:qa:rolling-upgrade:v8.0.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.SnapshotBasedRecoveryIT/testSnapshotBasedRecovery?top-execution=1

**Comment by jrodewig** [comment]
Muting in `master` and 8.0 in https://github.com/elastic/elasticsearch/pull/82436.
