### ISSUE TITLE
[CI] Docker `:test:fixtures:krb5kdc-fixture:composeDown failed with read timeout

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#80935]
The Docker `composeDown` task failed today for the `:test:fixtures:krb5kdc-fixture:composeDown` fixture:

>  ERROR: for 8be6189abbed0e72ab6de2523556c027_krb5kdc-fixture__hdfs_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

It looks very similar to #71866 which seems to have been solved with increasing COMPOSE_HTTP_TIMEOUT in 846537603a4c457a92c9bb80e301a46a6305cded.

**Build scan**:
https://gradle-enterprise.elastic.co/s/q4m4rsc24stok

**Repro line**:
None

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:

**Comment by pugnascotia** [comment]
@mark-vieira could we easily set this env var across all CI jobs?

**Comment by mark-vieira** [comment]
I've added this in 72ded7018885a20f00cb701d126117dcff593353.
