### ISSUE TITLE
New feature - add lookup by Lucene doc ID to ShardTermVectorService.getTermVector

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#8095]
As part of breaking up https://github.com/elasticsearch/elasticsearch/pull/6796 into more digestible pieces we need a service to fetch the tokens in a field.
The existing ShardTermVectorService.getTermVector(..) handles much of the complexity of reading stored TermVectors or using Analyzers on source fields to provide terms but is predicated on the caller providing an es ID (primary key) to identify the required document. In the context of analyzing query results, the caller has a collection of Lucene document IDs and not primary keys and so it would be useful/faster if the ShardTermvectorService could cope with looking up TermVectors given a Lucene document ID.

**Comment by clintongormley** [comment]
@markharwood is this still something you're interested in adding?

**Comment by markharwood** [comment]
I think this could still be useful for any free-text analysis of search results e.g significant_terms.
Not a high priority for me currently but certainly a longer-term nice-to-have

**Comment by markharwood** [comment]
Stale request - we now have significant_text agg. Closing
