### ISSUE TITLE
Adding a synthetic field to documents generated by Transforms

### ISSUE THREAD

**Issue by romainneutron** [elastic/elasticsearch#80953]
**Describe the feature:**

Hello,

I'm playing with [Elastic Transforms](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-transform.html)
I would like to add some synthetic fields to documents generated by Transforms.

**Describe a specific use case for the feature:**

I've created a transform like this:

```json
PUT _transform/transform_test_2s
{
  "source": {
    "index": "server"
  },
  "pivot": {
    "group_by": {
      "grain": {
        "date_histogram": {
          "field": "created_at",
          "fixed_interval": "2s"
        }
      }
    },
    "aggregations": {
      "avg": {
        "avg": {
          "field": "wt"
        }
      }
    }
  },
  "dest": {
    "index": "transform_test"
  },
  "frequency": "30s"
}
```

When I run it:

`POST _transform/transform_test_2s/_start`

I got that kind of output in the target index:

```json
      {
        "_source" : {
          "avg" : 1095432.0,
          "grain" : "2021-10-02T08:44:02.000Z"
        }
      },
      {
        "_source" : {
          "avg" : 709561.0,
          "grain" : "2021-10-02T08:44:22.000Z"
        }
      }
```
I want to add a second transform transform_test_5s that does the same thing with `"fixed_interval": "5s"` instead of 2s.
The issue is that I would not be able to distinct records generated by transform `transform_test_2s` or `transform_test_5s`

What I would like to have is :
```json
      {
        "_source" : {
          "avg" : 1095432.0,
          "grain" : "2021-10-02T08:44:02.000Z",
          "used_period": "2s"
        }
      },
      {
        "_source" : {
          "avg" : 709561.0,
          "grain" : "2021-10-02T08:44:22.000Z",
          "used_period": "2s"
        }
      }
```
A way to achieve this is to use named aggregations like `"grain_2s"`, eg:
```json
    "group_by": {
      "grain_2s": {
        "date_histogram": {
          "field": "created_at",
          "fixed_interval": "2s"
        }
      }
    },
```
When running with both transforms, it results in :
```json
      {
        "_source" : {
          "grain_5s" : "2021-10-05T07:25:05.000Z",
          "avg" : 274935.0
        }
      },
      {
        "_source" : {
          "avg" : 621279.0,
          "grain_2s" : "2021-10-02T08:44:22.000Z"
        }
      }
```
The drawback is that it creates n+1 fields in the index (n is the number of transforms)

So it leads me to this feature request; I'd like to have multiple transforms that result in something like the following. I would need a synthetic field defined in the transform like the "grain" one below.

```json
      {
        "_source" : {
          "date" : "2021-10-05T07:25:05.000Z",
          "grain": "5s",
          "avg" : 274935.0
        }
      },
      {
        "_source" : {
          "date" : "2021-10-02T08:44:22.000Z",
          "grain": "2s",
          "avg" : 621279.0
        }
      }
```

I hope I wrote this issue correctly, and you understand my need.
Thanks,
Romain

**Comment by hendrikmuhs** [comment]
@romainneutron 

You can attach an ingest [pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-transform.html#put-transform-request-body) to a transform, which allows you to use any of the ingest processors [listed on the right](https://www.elastic.co/guide/en/elasticsearch/reference/master/processors.html). Your case can be solved using a _set_ processor.

I think that solves your case.

However, 1 detail you should be aware of. The 2 transforms have equal `group_by's`, if you let them write into the _same_ destination, you might notice that documents of transform 1 overwrite docs from transform 2 and vice versa. Every transform should have it's own destination index. This should not limit you in you application, because using a multi-index query you can still query both at the same time.

**Comment by hendrikmuhs** [comment]
Please confirm this works for you, I will keep the issue open for now.

I will follow up regarding documentation, it looks like we should add at least an example that uses an ingest pipeline.

**Comment by romainneutron** [comment]
Hello @hendrikmuhs 
Thanks for your clear answer!
I now understand how to attach a pipeline to the transform, but it would not work because my transforms do their job using the same group by names. So bad :)

Transforming in multiple indexes is not an option since I would like to create numerous transforms (~15), and I'm already sharding per project (a few hundred). It would produce x15 shards, and I know that elasticsearch does not like it when creating too many shards.

Is there a possibility that defining multiple transforms using the same "group_by" keys and targeting the same index could be a new feature in upcoming versions? I expect the difficulty would be in generating the appropriate document id. What about including the transform name in the sauce :thinking:?

Last question: If I understand correctly, docs Ids are based on the "group_by" keys? If I use multiple transforms targeting the same index and using distinct "group_by" keys, could you confirm I shall not encounter overwriting document issues?

Thank you very much.

**Comment by hendrikmuhs** [comment]
> Is there a possibility that defining multiple transforms using the same "group_by" keys and targeting the same index could be a new feature in upcoming versions?

There is a workaround for this. In an ingest pipeline you can change the `_id` field, but it should be deterministic. If you use the [fingerprint processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/fingerprint-processor.html) you can pretty much replicate what transform does. The fingerprint processor allows you to supply a `salt` value, your transforms should all have a different salt and of course you should not change it later.

When it comes to a feature, I think supplying such a `salt` value and maybe randomly generating one per transform seems like a good idea. Feel free to open a new issue for it.

> Last question: If I understand correctly, docs Ids are based on the "group_by" keys? If I use multiple transforms targeting the same index and using distinct "group_by" keys, could you confirm I shall not encounter overwriting document issues?

Well, this is mathematics, a hash function can produce the same results, but for this case it is extremely unlikely this happens, see the wikipedia entry about [fingerprint and virtual uniqueness](https://en.wikipedia.org/wiki/Fingerprint_(computing)).

**Comment by romainneutron** [comment]
:pray: Thanks @hendrikmuhs
