### ISSUE TITLE
Genericize GeoIP Processor

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#80960]
Discussion forum thread: https://discuss.elastic.co/t/how-does-the-new-7-14-geoip-processor-work/289957

(This request is more of a quality-of-life enhancement.)

In 7.14.0, Elasticsearch changed the GeoIP processor to support reloadability. While this integration is nice if you're using MaxMind, I think it would be a good improvement to expand on this processor to be able to support pulling files from different providers as well as the ability to define different fields.

### **Background on this request:**

Currently, if I want to achieve something similar to what the GeoIP processor does, I need to perform the following steps:
1. Pull the file with the desired contents
2. Ingest a file with the desired contents into Elasticsearch
    - This can be done either with Logstash or Filebeat + additional ingest pipelines (if needed)
3. Create enrich policy (only needed once really)
4. Execute enrich policy

While the above doesn't seem like a lot of steps, it does require additional infrastructure outside of just Elasticsearch to do.

### **Request:**

It would be nice if the GeoIP processor could be genericized so that you could do the following:
1. Provide URL + Method from where to download file
2. Provide target index (assumes the index pattern will be present, or the defaults will be used)
3. Provide fields intended to be used within enrichment (create enrich policy)
4. Provide schedule on when to download file
5. Automatically execute enrich policy after pull and ingest of file is complete.

I recognized that this has a good amount of bleed over into the enrich processor/enrichment policy stuff, but it's more about taking the functionality present in Elasticsearch with the GeoIP processor and making it available for other things.

**Comment by jakelandis** [comment]
We discussed this today in our team meeting and don't think this is a good fit for Elasticsearch.  When prototyping the auto-updateable GeoIP processor we did something similar to what you suggest - trying to marry GeoIP and enrich - however it proved to be considerably slower and we abandoned the idea. The GeoIP database provided by Maxmind is really well optimized and we also provide some custom caching. We wouldn't be able to generalize the GeoIP processor without also taking a decent performance hit. Additionally the request to use a download file as input source for the enrich processor is a reasonable request but all outbound calls especially calls that download files to disk have a considerable amount of overhead to consider and at this time we don't think is a direction we want to go.
