### ISSUE TITLE
Snapshot restore requests allow you to restore data stream alias with conflicting name

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#80972]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 8.1.0-SNAPSHOT, Build: default/tar/e38cadb5283feeea06f09d555dbe47fb1d5e8b39/2021-11-22T22:35:22.825882Z, JVM: 17.0.1

**OS version** (`uname -a` if on a Unix-like system):
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

I expect ES to reject snapshot restore requests that restore a data stream alias with the same name as an existing data stream or index.

However, ES currently accepts these requests. This cluster now has a data stream/index and alias with the same name. A user may not be sure which resource a search request targeting the name will hit.

**Steps to reproduce**:

1. Register a snapshot repository

```
PUT /_snapshot/my_repository
{
  "type": "fs",
  "settings": {
    "location": "my_backup_location"
  }
}
```

2. Create a data stream.

```
POST logs-my_app-default/_doc
{
  "@timestamp": "2099-05-06T16:21:15.000Z"
}
```

3. Add a `logs` alias to the data stream.

```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "logs-my_app-default",
        "alias": "logs"
      }
    }
  ]
}
```

4. Create a snapshot containing the data stream and its alias

```
PUT _snapshot/my_repository/my_snapshot?wait_for_completion=true
```

5. Delete the data stream. This also deletes the alias.

```
DELETE _data_stream/logs-my_app-default
```

6. Create another data stream with same name as the deleted alias (`logs`).

```
PUT _index_template/my-index-template
{
  "index_patterns": ["logs"],
  "data_stream": { },
  "priority": 500
}

POST logs/_doc
{
  "@timestamp": "2099-05-07T16:21:15.000Z"
}
```

7. Restore the data stream and `logs` alias from the snapshot.

```
POST /_snapshot/my_repository/my_snapshot/_restore?wait_for_completion=true
{
  "indices": "logs-my_app-default",
  "include_aliases": true
}
```

I expected this to return an error due to a conflict between the restored `logs`
alias and the pre-existing `logs` data stream. However, the request was
accepted, and both resources now exist.

Retrieve the `logs` data stream:

```
GET _data_stream/logs
```

Retrieve the `logs` alias:

```
GET _alias/logs
```

A search on `logs` only hits the `logs` data stream:

```
GET logs/_search
```

However, a search on `log*` hits both the alias and the data stream:

```
GET log*/_search
```

**Comment by martijnvg** [comment]
If an alias with same name does exist in the cluster then restore logic tries to merge 
the alias from the snapshot with the alias in the cluster. 

This behaviour already existed when restoring indices aliases from a snapshot:

```
PUT /_snapshot/my_repository
{
  "type": "fs",
  "settings": {
    "location": "my_backup_location"
  }
}

POST index1/_doc
{
  "@timestamp": "2099-05-06T16:21:15.000Z"
}

POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "index1",
        "alias": "logs"
      }
    }
  ]
}

PUT _snapshot/my_repository/my_snapshot?wait_for_completion=true

DELETE index1

POST index2/_doc
{
  "@timestamp": "2099-05-07T16:21:15.000Z"
}

POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "index2",
        "alias": "logs"
      }
    }
  ]
}

POST /_snapshot/my_repository/my_snapshot/_restore?wait_for_completion=true
{
  "indices": "index1",
  "include_aliases": true
}
```

After thinking about this more about this, I tend to agree that throwing an error is better.
However I do think there may be cases where this current behaviour may be desired.
Looking back at this, I think it would have made sense to include some kind of a merge parameter,
that allows to control this. And then perhaps defaulting to fail with an error in the case that
an alias is being restored that also exists in the cluster.

**Comment by martijnvg** [comment]
(deleted comment was meant to be posed to #80976)

**Comment by martijnvg** [comment]
Actually I think [my comment](https://github.com/elastic/elasticsearch/issues/80976#issuecomment-977980241) makes more sense here than in #80976.

**Comment by jrodewig** [comment]
Thanks again @martijnvg. However, I don't think the issue here is with merging aliases. It's that a restored data stream alias can have the same name as an existing data stream or index (and vice versa). I've updated the description to better reflect that.

This same issue doesn't seem to occur for index aliases. For example:

1. Register a snapshot repository

```
PUT /_snapshot/my_repository
{
  "type": "fs",
  "settings": {
    "location": "my_backup_location"
  }
}
```

2. Create `index1`.

```
POST index1/_doc
{
  "@timestamp": "2099-05-06T16:21:15.000Z"
}
```

3. Add the `logs` alias to `index1`.

```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "index1",
        "alias": "logs"
      }
    }
  ]
}
```

4. Create a snapshot containing `index1` and its alias.

```
PUT _snapshot/my_repository/my_snapshot?wait_for_completion=true
```

5. Delete the `index1`. This also deletes the `logs` alias.

```
DELETE index1
```

6. Create a new index named `logs`.

```
POST logs/_doc
{
  "@timestamp": "2099-05-07T16:21:15.000Z"
}
```

7. Restore `index1` and the `logs` alias from the snapshot.

```
POST /_snapshot/my_repository/my_snapshot/_restore?wait_for_completion=true
{
  "indices": "index1",
  "include_aliases": true
}
```

This results in an error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "index, alias, and data stream names need to be unique, but the following duplicates were found [logs (alias of [index1/3IRS4FwJRaOZautW1DW1dA]) conflicts with index]"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "index, alias, and data stream names need to be unique, but the following duplicates were found [logs (alias of [index1/3IRS4FwJRaOZautW1DW1dA]) conflicts with index]"
  },
  "status" : 500
}
```

I'd expect a similar error for a data stream alias with the same name as an existing index or data stream.

**Comment by martijnvg** [comment]
Thanks for @jrodewig for explaining this to me. This is a bug and needs to be fixed.

**Comment by martijnvg** [comment]
Note that running the reproduction in tests, qa modules and `./gradlew run` is not possible, because the node fails with an assertion error:

```
[2021-11-25T10:34:10,994][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][masterService#updateTask][T#1]], exiting
»  java.lang.AssertionError: duplicate data stream for logs
»       at org.elasticsearch.cluster.metadata.Metadata$Builder.buildIndicesLookup(Metadata.java:1718) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1634) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1527) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterState$Builder.metadata(ClusterState.java:566) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.snapshots.RestoreService$RestoreSnapshotStateTask.execute(RestoreService.java:1332) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:828) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:395) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:235) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:167) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:712) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
»       at java.lang.Thread.run(Thread.java:833) [?:?]
```

In production we don't run with assertions enabled. What we missed here, is adding a normal check that prevents restoring a an alias if a data stream with the same name already exists.
