### ISSUE TITLE
I think this piece of code              ”if (execution == null) {                  execution = ExecutionMode.GLOBAL_ORDINALS;              } “      Should be in     ”final long maxOrd = execution == ExecutionMode.GLOBAL_ORDINALS? getMaxOrd(valuesSource, context.searcher()): -1; “  Before

### ISSUE THREAD

**Issue by moxiaonian** [elastic/elasticsearch#80980]
the code:
https://github.com/elastic/elasticsearch/blob/0618edb503aead8624ac81bbc4e4cc5136b05e0e/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java#L136

```
            final long maxOrd = execution == ExecutionMode.GLOBAL_ORDINALS ? getMaxOrd(valuesSource, context.searcher()) : -1;
            if (execution == null) {
                execution = ExecutionMode.GLOBAL_ORDINALS;
            }
```

**Comment by nik9000** [comment]
I think you are right, but we've since flipped it into the right order:
https://github.com/elastic/elasticsearch/blob/20c9f756d28d116f0667e19a1b531aa80c55bde7/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java#L110-L113
