### ISSUE TITLE
Can we not always reroute when update index setting?

### ISSUE THREAD

**Issue by ViggoC** [elastic/elasticsearch#80998]
Today I just want to update an index setting like `refresh_interval`, but it triggers a cluster rebalance.
Then I read the code and find the code [here](https://github.com/elastic/elasticsearch/blob/594fe00396ed70a2cd035775badbdb5ef2aecc98/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java#L265) which always call reroute no matter what settings are updated. The comment says: 
> reroute in case things change that require it (like number of replicas) 

SO can we only reroute when number of replicas (or other things that required it) are changed. 

It doesn't look complicated. I can work on it. But I need to confirm that in addition to the number of replicas, are there any settings that need to trigger reroute?

**Comment by ViggoC** [comment]
I see. I think I can just disable `cluster.routing.rebalance.enable` to avoid unexpected rebalance.

**Comment by DaveCTurner** [comment]
Do you intend to work on any of the suggestions I made, or does your last message indicate that this can be closed?

**Comment by ViggoC** [comment]
I did not consider the need to support plugins before. I think this problem cannot be solved by modifying only one function. I'm closing this issue. Thanks for your time.
