### ISSUE TITLE
Remove deprecated usages of X509Certificate.getSubjectDN()

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#81008]
`X509Certificate#getSubjectDN` has been deprecated starting with Java 16. This gets used in a number of places in our security code and is recommended that usages be replaced with `getSubjectX500Principal`.

https://gradle-enterprise.elastic.co/s/2ivni47qk473q

**Comment by jkakavas** [comment]
Thanks Mark, we did discuss this back on March 18 and I could swear we're tracking this with an issue but apparently we didn't * until now!).

**Comment by mark-vieira** [comment]
FWIW, same applies to `getIssuerDN()`.
