### ISSUE TITLE
[ML] A model state created in 7.0-7.9 should not have to be upgraded before upgrading to version 8

### ISSUE THREAD

**Issue by wwang500** [elastic/elasticsearch#81011]
Step to reproduce:
1. On a 7.6.0 cluster, create and run a few of AD jobs,
2. After jobs finish and stop, upgrade the cluster to 7.16.0
3. After upgrade, login kibana and go to Stack Management -> Upgrade Assistant, 

Observed:
there are critical warnings about obsolete minimum version of model snapshot
![image](https://user-images.githubusercontent.com/47184485/143296527-c5882a4a-6081-4b0f-beb3-19676571a19b.png)

Expected:
A model state created in 7.0-7.9 should not have to be upgraded before upgrading to version 8

**Comment by droberts195** [comment]
This is a by-product of elastic/ml-cpp#1545.  We forgot to update the snapshot version in the C++ code for a long time.

As a result I think we'll have to change our policy on which snapshots are acceptable for 8.x to load from >=7.0 to >=6.4 (where 6.4 really means anything between 6.4 and 7.9).
