### ISSUE TITLE
Adjust naming for TLS autoconfiguration directory and artifacts

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#81057]
We currently use a directory name like `tls_auto_config_<timestamp>` for the directory where we store the auto-generated TLS key/certificate material. This was intentional and has certain benefits but we decided that it's complicating the getting started experience and our documentation. Moreover, we are using longer descriptive names for keystores (`http_keystore_local_node.p12` and `http_keystore_local_node.p12` ) and we decided that it might be less confusing for users if we use shorter names such as `http.p12` and `transport.p12`. 

Our generated material should look like: 

```
config/
├── tls_auto_config
│   ├── http_ca.crt
│   ├── http.p12
│   └── transport.p12
```

**Comment by bytebilly** [comment]
I could expect users to replace certificates in the future, and they should change the folder (and so the configuration YML) or put some non-autogenerated content in a directory named `auto_config`.

If we establish a convention (e.g. `certs/`), this could be used for both use cases without any problem.

Could you please explain what's the benefit of an explicit name of the folder?

**Comment by jkakavas** [comment]
I see the benefit of being explicit. We remove the explicitness from the name of the file, it makes sense to me to keep the directory name to indicate that the files in there were automatically generated by elasticsearch. 

I don't see the creation of a directory or the change of the value in the yaml file in the case of certificate rotation/replacement so problematic to be honest. Making it more probable that users are explicit that the new configuration is not the auto-configured one is an advantage, not a problem, in my opinion.

**Comment by bytebilly** [comment]
Uhm, I understand that you see the benefit, but I'm not sure that I get which this benefit is.

> I don't see the creation of a directory or the change of the value in the yaml file in the case of certificate rotation/replacement so problematic to be honest. 

I feel that there is a sensitive difference between replacing files (e.g. renewing certificates) and changing part of the content of `elasticsearch.yml`. The former is an "atomic" action (once you have the right files), while the second is more prone to errors (you need to know which options you need to change, and how, and you may introduce typos in the file by editing it, it's hard to do it with an automated script, etc).

> Making it more probable that users are explicit that the new configuration is not the auto-configured one is an advantage, not a problem, in my opinion.

From a user perspective, why should you care if a certificate has been automatically generated during the first boot, it has been created with `elasticsearch-certutil`, or is coming from your corporate PKI office? I do see value in having a single convention where certificates in use are stored, no matter which is their original source. At the end of the day, once created, they are almost the same.

**Comment by jkakavas** [comment]
I too understand that you don't see it but I think there is one :) 

> I feel that there is a sensitive difference between replacing files (e.g. renewing certificates) and changing part of the content of elasticsearch.yml. The former is an "atomic" action (once you have the right files), while the second is more prone to errors (you need to know which options you need to change, and how, and you may introduce typos in the file by editing it, it's hard to do it with an automated script, etc).

- We actually _warn against_ replacing files in place when doing certificate rotation
- Can't you do typos when you name the files or copy them around ? 
- Is it _really_ harder to see that you need to replace the string `xxxxxxxxx.p12` in your configuration than to see that you need to replace the file with name `xxxxxxxxx.p12` in the directory ?

> From a user perspective, why should you care if a certificate has been automatically generated during the first boot, it has been created with elasticsearch-certutil, or is coming from your corporate PKI office? 

Because one does, I believe. I think there is value in being able to determine what a file is / where it comes from by looking at it without the need to run `openssl` or `keytool` on it. I see the same argument/value in doing this as the one that dictates that we put the auto-configuration stanza on each own with marking that this is auto-configured.

This is not too contentious to me nor I think it makes too much difference to spend our cycles on discussing instead of implementing the change. If you feel strongly about it, let's go with `certs`, otherwise we can do a quick show of hands in the team slack channel to help reach a consensus.
