### ISSUE TITLE
certutil http and auto-configured certificates for http layer should set extended key usage

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#81067]
We generate certificates that are intended to be used for server authentication in a couple of places:

- `bin/elasticsearch-certutil http` command  ( See `CertGenUtils.generateSignedCertificate` in `HttpCertificateCommand` )
- TLS auto-configuraion for node startup ( see [`AutoConfigureNode`](https://github.com/elastic/elasticsearch/blob/814f7f9f52cb8c05db6465b9bfc818ea5d76c575/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java#L454) )

In these cases we know that the certificate is meant to be used for server authentication, so we can set Extended Key Usage extension to `1.3.6.1.5.5.7.3.1`

**Comment by DIABmehdi** [comment]
Hello @jkakavas ,
We are a team of new contributors to your project, we are trying to resolve that ticket: https://github.com/elastic/elasticsearch/issues/81067#issue-1063841016

So the Extended Key Usage will be set to Server Authentication when it's for : 
1- [AutoConfigureNode_Httpcert](https://github.com/elastic/elasticsearch/blob/814f7f9f52cb8c05db6465b9bfc818ea5d76c575/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java#L454)
2- [HttpCommand_certificate](https://github.com/elastic/elasticsearch/blob/814f7f9f52cb8c05db6465b9bfc818ea5d76c575/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java#L356)
3- [HttpCommand_CaCert](https://github.com/elastic/elasticsearch/blob/814f7f9f52cb8c05db6465b9bfc818ea5d76c575/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java#L903)

We will do this by adding a boolean forServerAuth to the call of generateSignedCertificate() to know if we must set the EKU or not .

We want to know if those three are the only concerned certificate with the extended key usage ?
