### ISSUE TITLE
nanosecond aggregation

### ISSUE THREAD

**Issue by liudaoqiangtj** [elastic/elasticsearch#81086]
Is there a plan for nanosecind aggregation，or is there any difficulty to support nanosecond aggregation？

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
