### ISSUE TITLE
[ML] Allocation stats should report actual thread settings used

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#81149]
PyTorch trained model deployments have 2 thread settings `inferenceThreads` and `modelThreads` which determine how compute resources are used. To prevent over-subscription the native process [imposes a limit on the settings](https://github.com/elastic/ml-cpp/blob/main/bin/pytorch_inference/Main.cc#L211) which are checked against `std::thread::hardware_concurrency()`. Any adjustments to the settings are logged but those log messages are not the most visible, it would be better to report back in the deployment stats that a setting was modified. This should be done per node as models are deployed across heterogenous nodes which can have different hardware profiles and values of `std::thread::hardware_concurrency()`.

**Comment by dimitris-athanasiou** [comment]
This issue is now about communicating to the java side the actual settings the process uses for reporting in the _stats API.
