### ISSUE TITLE
Gradle task :distribution:docker:buildCloudDockerImage fails regulary with failing tar command

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#81150]
Building the cloud docker image seems to fail on a regular basis lately (see https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:distribution:docker:buildCloudDockerImage%27.%0A%3E%20A%20failure%20occurred%20while%20executing%20org.elasticsearch.gradle.internal.docker.DockerBuildTask$DockerBuildAction%0A%20%20%20%3E%20Process%20%27command%20%27docker%27%27%20finished%20with%20non-zero%20exit%20value%202&search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin) 

The task fails always on installing `metricbeat` or `filebeat` ( see https://gradle-enterprise.elastic.co/s/va6oiyv35ryhu/console-log?task=:distribution:docker:buildCloudDockerImage#L1170 )

it seems those archives get corrupted somehow during the process.

**Comment by pugnascotia** [comment]
@breskeby I'm not sure what the best thing to do here is. I'd like the build to also download the `.sha512` files for the beats artifacts and validate the checksum, but there doesn't seem to be support anywhere for doing that (e.g. Gradle expect you to know the checksums in advance).

Perhaps we can start with some extra checking in the Dockerfile, so that we can at least know more about what files we downloaded when then build failed?

**Comment by mark-vieira** [comment]
Yeah, I'm really surprised how often these files seem to be corrupted. I don't think the Gradle checksum validation will necessarily help as it'll just fail sooner I guess. Is this something we should bring up with infra?

**Comment by pugnascotia** [comment]
I think I'll add a little more diagnostics / error messages into the build first, then when it fails next we can talk to Infra with (hopefully) a little more info.

**Comment by slobodanadamovic** [comment]
This issue happened again. Here is the most recent failure log:

https://gradle-enterprise.elastic.co/s/n6r4zexaqmt2a/console-log?anchor=5532

```
|  ---> Running in 73c0d8939668	
| [91m+ [ ! -s /tmp/filebeat-8.5.0.tar.gz ]	
| + echo /tmp/filebeat-8.5.0.tar.gz is empty - cannot uncompress	
| + exit 1	
| [0m/tmp/filebeat-8.5.0.tar.gz is empty - cannot uncompress	
| The command '/bin/sh -c set -eux ;     for beat in filebeat metricbeat ; do       if [ ! -s /tmp/$beat-8.5.0.tar.gz ]; then         echo "/tmp/$beat-8.5.0.tar.gz is empty - cannot uncompress" 2>&1 ;         exit 1 ;       fi ;       if ! tar tf /tmp/$beat-8.5.0.tar.gz >/dev/null; then         echo "/tmp/$beat-8.5.0.tar.gz is corrupt - cannot uncompress" 2>&1 ;         exit 1 ;       fi ;       mkdir -p /opt/$beat ;       tar xf /tmp/$beat-8.5.0.tar.gz -C /opt/$beat --strip-components=1 ;     done' returned a non-zero code: 1	

```

**Comment by mark-vieira** [comment]
> This issue happened again. Here is the most recent failure log:

This is actually an unrelated issue due to beats artifacts being unavailable. The build _should_ have failed to even start but the default behavior for `curl` is to return successfully even in the event of a 404. I've pushed 18245ec9ef3637ffb6f5e3300d8de25dbe0b0331 to correct that.

**Comment by mark-vieira** [comment]
I've also seen no instances of the original error recently so I'm closing this for now.

**Comment by n1v0lg** [comment]
Another failure like the one @slobodanadamovic observed. It's on `8.4`:

https://gradle-enterprise.elastic.co/s/kvtmiyvyr67ty/

With failure output:

```
|  ---> Running in 3fbaa1ad1ce5
| [91m+ [ ! -s /tmp/filebeat-8.4.0.tar.gz ]
| [0m[91m+ tar tf /tmp/filebeat-8.4.0.tar.gz
| [0m[91m+ mkdir -p /opt/filebeat
| [0m[91m+ tar xf /tmp/filebeat-8.4.0.tar.gz -C /opt/filebeat --strip-components=1
| [0m[91m+ [ ! -s /tmp/metricbeat-8.4.0.tar.gz ]
| + tar tf /tmp/metricbeat-8.4.0.tar.gz
| [0m[91m
| gzip: stdin: unexpected end of file
| [0m[91mtar: Unexpected EOF in archive
| tar: Error is not recoverable: exiting now
| [0m/tmp/metricbeat-8.4.0.tar.gz is corrupt - cannot uncompress
| [91m+ echo /tmp/metricbeat-8.4.0.tar.gz is corrupt - cannot uncompress
| + exit 1
```

@mark-vieira is it just a matter of backporting your fix to 8.4 or am I off here?

**Comment by astefan** [comment]
Another one today (https://gradle-enterprise.elastic.co/s/p2dj3fdq74nne):
```
|  ---> Running in 58fad5e5f7a2
| [91m+ [ ! -s /tmp/filebeat-8.7.0.tar.gz ]
| + tar tf /tmp/filebeat-8.7.0.tar.gz
| [0m[91m+ mkdir -p /opt/filebeat
| [0m[91m+ tar xf /tmp/filebeat-8.7.0.tar.gz -C /opt/filebeat --strip-components=1
| [0m[91m+ [ ! -s /tmp/metricbeat-8.7.0.tar.gz ]
| + tar tf /tmp/metricbeat-8.7.0.tar.gz
| [0m[91m
| gzip: stdin: unexpected end of file
| [0m[91mtar: Unexpected EOF in archive
| tar: Error is not recoverable: exiting now
| [0m[91m+ echo /tmp/metricbeat-8.7.0.tar.gz is corrupt - cannot uncompress
| + exit 1
| [0m/tmp/metricbeat-8.7.0.tar.gz is corrupt - cannot uncompress
```

**Comment by n1v0lg** [comment]
More on `8.7`: https://gradle-enterprise.elastic.co/s/gfcyye5snswsc

**Comment by mark-vieira** [comment]
This happens when we fail to download release artifacts. I've pushed e5e53e5887469f83c057d7df2820d3fff3f5e029 which will fail the build early in this scenario.
