### ISSUE TITLE
[CI] SearchGroupsResolverInMemoryTests classMethod failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#81169]
I'm seeing thread leak errors in this test suite a couple times a day. Looks like it's been going on for awhile.

**Build scan:**
https://gradle-enterprise.elastic.co/s/o7nddj72ciq3e/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests/classMethod

**Reproduction line:**
`null`

**Applicable branches:**
8.0, master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests&tests.test=classMethod

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests: 
   1) Thread[id=111, name=Timer thread for LDAPConnection(name='test-connection-testSearchTimeoutIsFailure', not connected), state=WAITING, group=TGRP-SearchGroupsResolverInMemoryTests]
        at java.base@17.0.1/java.lang.Object.wait(Native Method)
        at java.base@17.0.1/java.lang.Object.wait(Object.java:338)
        at java.base@17.0.1/java.util.TimerThread.mainLoop(Timer.java:537)
        at java.base@17.0.1/java.util.TimerThread.run(Timer.java:516)

  at __randomizedtesting.SeedInfo.seed([186A445C24CA4E7D]:0)

```

**Comment by jkakavas** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/80305
