### ISSUE TITLE
is version Bug?

### ISSUE THREAD

**Issue by yljcode1** [elastic/elasticsearch#81200]
SpringCloud-version:2020-1
springboot-version:2.4.8
elasticsearch:7.15.2

when I start my project ,it happened 
![image](https://user-images.githubusercontent.com/92766952/144203402-ee67f6cd-0b4a-4a74-9540-d49b3bfbd137.png)

**Comment by yljcode1** [comment]
![image](https://user-images.githubusercontent.com/92766952/144203447-c10c5cd3-5fef-430f-a19b-97c12fe5373e.png)

**Comment by cbuescher** [comment]
Hi @yljcode1 ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
