### ISSUE TITLE
Package cloudflare-zlib with the Docker image

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#81208]
Elasticsearch uses zlib for two purposes:
 - Compression of stored fields with `index.codec: best_compression`, which we use for observability and security data.
 - Request / response compression.

The original zlib, which is usually the one that is installed, optimizes for portability and misses a number of important optimizations such as leveraging vectorization support for x86 and ARM architectures. Several forks have been created in order to address this, notably an [Intel fork](https://github.com/jtkukunas/zlib), [zlib-ng](https://github.com/zlib-ng/zlib-ng) and a [Cloudflare fork](https://github.com/cloudflare/zlib).

Historically, zlib was packaged within the JDK, so that users wouldn't have to have zlib installed for basic usage of Java. A downside of this approach is that it didn't allow using one of these faster forks, but [since version 9 the JDK uses the system's zlib when available](https://bugs.openjdk.java.net/browse/JDK-8031767) and falls back to the zlib that is packaged within the JDK if a system zlib cannot be found.

I performed testing with the Cloudflare zlib, which yielded almost 2x faster compression and decompression for JSON documents that are representative of those produced by the Elastic Observability solution. A run of the `solutions/logs` track with Rally yielded 2.35% faster indexing, 8.28% less cumulative merge time and 4.83% less cumulative indexing time. One particularity of the Cloudflare zlib is that compression levels retain the same semantics as the original zlib (unlike the Intel fork which uses a compatible format but gives different semantics for some compression levels) so the space efficiency of the produced indices was sensibly the same.

This issue suggests that we update our Docker image to use the Cloudflare fork of zlib instead of the original zlib so that users of the Elastic Cloud service and of the Docker image in general would get better performance out of their Elasticsearch clusters.

**Comment by jpountz** [comment]
Note that a possible alternative would be to include the cloudflare-zlib library directly in the tarball. It felt more challenging than doing it in the Docker image (which is a more controlled environment), hence the suggestion to go with the Docker image. But I'd be equally happy with the tarball approach if it has the preference of the Delivery team.

**Comment by pugnascotia** [comment]
Cloudflare helpfully have their own [package repository](https://pkg.cloudflare.com/), with instructions for Debian, Ubuntu and RHEL. Unfortunately, their repo doesn't include Ubuntu packages for ARM / aarch64. The lib is quick to build from source, so maybe we can do something cross-platform.

**Comment by pugnascotia** [comment]
For the record, here are the steps that were used to test the zlib.

```
git clone git@github.com:cloudflare/zlib.git cloudflare-zlib
cd cloudflare-zlib
./configure --prefix=/usr/local/cloudflare-zlib
make
sudo make install
```

And then it's about setting the `LD_LIBRARY_PATH` environment variable, e.g. `LD_LIBRARY_PATH=/usr/local/cloudflare-zlib/lib/ bin/elasticsearch`, the JVM will automatically pick it up.

**Comment by jpountz** [comment]
I didn't check the Cloudflare packages but hopefully they put the lib in a directory that ld gives higher priority to the directory where the original zlib is so that it would get used naturally without additional measures.

**Comment by DJRickyB** [comment]
Or if we do package it, `bin/elasticsearch` itself could check for its presence and set/extend `LD_PRELOAD` or `LD_LIBRARY_PATH` before the JVM initialization

**Comment by pugnascotia** [comment]
TBH I was planning on modifying `LD_LIBRARY_PATH`. We can mostly do what we like in the Docker images.
