### ISSUE TITLE
High system CPU usage with Elasticsearch on Kubernetes (using ECK) using ES v7.10.0+ (but not in v7.6.1).

### ISSUE THREAD

**Issue by yannv** [elastic/elasticsearch#81227]
**Elasticsearch version**: 7.10.0 & 7.14.2 (but not reproduced in ES v7.6.1)

**Plugins installed**: None

**JVM version**: Bundled in official Elasticsearch docker image

**OS version**: Reproduced on CentOS 7.9 with kernel 3.10.0 and 5.4.155 ; as well as on Ubuntu 20.04 with kernel 5.4.0

**OS version**: Kubernetes 1.19.x & Kubernetes v1.21.5

**Description of the problem including expected versus actual behavior**:

Running an **Elasticsearch 7.10.0+ cluster on Kubernetes** (reproduced on two different K8s distributions) using ECK 1.8.0.
While ingesting documents in Elaticsearch and running performance tests, we noticed a high (and unusual) system CPU usage (between 20 and 30% while we are CPU bound, basically user cpu is around 60% and with very little IO-Wait).

We have reproduced this high system CPU usage with ES v7.10.0, as well as with ES v7.14.2 to check if it was still present in newer releases.
It does not seem to be OS specific nor from the OS kernel versions as described above. Similarly for Kubernetes version used, and storage layer (CSI) does not matter either. We have been using statically/local Persistent volumes and OpenEBS, and in all cases the high system CPU usage issue was present with Elasticsearch v7.10.0+.

_However, if we have Elasticsearch on the same topology and same hardware but only running on Docker (so without Kubernetes), this high system CPU usage is not there, so it is not just a containerized ES issue._

Moreover we did not noticed this over a year ago, but we were using the Elasticsearch version released from back then, being v7.6.1. We have just tested it again with this old ES version and sure enough we do not reproduce the high system cpu usage under the exact same condition (same data, same hardware, same ES topology, same K8s cluster, same ECK, just changing the ES version from the manifest). Therefore, we believe that something changed in Elasticsearch between v7.6.1 and v7.10.0 that causes this high system CPU usage when running on top of Kubernetes.

**Steps to reproduce**:

 1. Deploy an **ES v7.10.0+** cluster on Kubernetes with ECK and start ingesting enough documents to reach a CPU bound state (high CPU usage on Elasticsearch Data node). We used _ESRally_ for this with eventdata track. Using one shard per vCores allocated of the ES cluster (ES Data pods). The number of ES Data nodes does not matter we have reproduce it on 2 nodes and 75 nodes clusters. Having dedicated master nodes or without ES master nodes does not matter either we have tested these scenarios.
 2. Check the different CPU usage with something like _dstat -lrvn_ for instance and focus on system CPU value. 
 3. You should see going above 20%.
 4. Now if you do the same test with **ES v7.6.1** then the system cpu usage will be much lower.

This high system CPU usage (20-30%) prevents us to reach our previous ingestion rate we had last year.

![ES-High-system-CPU-usage-on-K8S-DifferentOS-DifferentK8sDistro](https://user-images.githubusercontent.com/1031448/144286430-d9fc867c-49a5-44ac-89f6-e7370fff7dfd.png)
![ES-High-system-CPU-usage-on-K8S-v7 10 0-vs-v7 6 1](https://user-images.githubusercontent.com/1031448/144286455-25be567d-204e-4cca-a382-35955dbdfd56.png)

**Comment by b-deam** [comment]
Hi @yannv - thanks for this post may be better suited to our [Discuss forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), as we prefer to use Github issues only for bug reports and feature requests, and performance issues can blur the line here.

Along with the great data you've already posted, it'd be great to also get a copy of the below items in the Discuss post..

- The manifests you're using to deploy your clusters with
- The output of the [Hot Threads API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/cluster-nodes-hot-threads.html) to see what ES is actually spending CPU time on during the benchmark. Bonus points if you can get comparisons between both 7.6 and 7.10, that'd be even better.

**Comment by yannv** [comment]
Hi @b-deam, thank you for your reply.
This issue should be qualified as a bug as it really impacts ingestion performance in newer versions of Elasticsearch on Kubernetes. It looks like it is something that has been introduced in the code or maybe a Java version upgrade in the container image. It is still a problem in latest version of Elasticsearch.

I will post this in the discussion forums as suggested with the extra information you requested.
Thank you for your help.

**Comment by yannv** [comment]
We have performed more tests on different Elasticsearch versions to narrow this down.
Our conclusion is that this high system CPU usage in Elasticsearch during data ingestion started in Elasticsearch v7.9.0.

![ES-High-system-CPU-usage-on-K8S-v7 8 0-CPU](https://user-images.githubusercontent.com/1031448/144651362-d90150a5-3a15-4ebf-8c66-e9f0fb4959de.png)
![ES-High-system-CPU-usage-on-K8S-v7 9 0-CPU](https://user-images.githubusercontent.com/1031448/144651382-68691958-5a14-4641-8110-25ebc7733263.png)

**Comment by b-deam** [comment]
Closing as discussion is continuing in https://discuss.elastic.co/t/high-system-cpu-usage-with-elasticsearch-on-kubernetes-using-eck-using-es-v7-10-0-but-not-in-v7-6-1/290904, will re-open if we warranted by discovery of a bug etc.

**Comment by yannv** [comment]
Just to let you know, if it can help someone else, we have find the root cause of the problem.
We were using _**node.store.allow_mmap: false**_ in the configuration of our Elasticsearch cluster deployment file and this was the reason behind the high system CPU.

This was clear in the [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html#k8s-virtual-memory):

> _For production workloads, it is strongly recommended to increase the kernel setting vm.max_map_count to 262144 and leave node.store.allow_mmap unset._
