### ISSUE TITLE
[Transform] Transform fails with task encountered irrecoverable failure: org.elasticsearch.index.IndexNotFoundException

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#81252]
**Affected version**: 7.15-
**Fixed with**: TBD

Transform can fail with an `IndexNotFoundException` if you use transform on a data stream, index pattern or alias that covers _multiple indices_ and you use index lifecycle management to delete old indices. In the case a transform updates documents while an index gets deleted by index lifecycle management the transform might fail.

This error is a regression introduced in 7.15, details below. Transform can be used together with index lifecycle management on source indices. 

**Mitigation**

Until a fix is available you have 3 options:

 - stay on an older version or don't upgrade to a version >= 7.15 until a fix is available
 - don't use ILM to delete old data or ensure transform isn't running when ILM deletes an index
 - watch and restart transform after a failure:

```
POST _transform/{job_id}/_stop?force=true&wait_for_completion=true
POST _transform/{job_id}/_start
```

You need `force=true` for jobs that are in failed state.
`wait_for_completion=true` waits until the transform has really stopped, otherwise it might not be stopped if you call _start right after - within nanoseconds - in a script.
You can use a `_stats` call to find out if a transform is in failed state.

**Comment by hendrikmuhs** [comment]
**Bug**

The usage of a point in time reader has been introduced for `7.15` in #74984. This is a performance optimization. The point in time reader is a search context that gets 1st created and than reused. The error happens when an index gets deleted between the point in time reader calls. Transform treats this as permanent error and sets the transform to `failed`.

Before using a point in time reader transform executed ordinary search requests where the indices got resolved per call. It seems however that an index that gets deleted in between is somehow handled internally.

A point in time reader is meant to be a

> lightweight view into the state of the data as it existed when initiated

This works fine if single documents are updated/deleted or added, a new index can be created as well, but not deleting an index.

In the transform use case this is a complex problem, most likely the transform does not care about the the index being deleted, because the deleted index likely does not contain data that transform queries for. For example for `date_histogram` groupings transform only updates buckets that have changed. The deleted index gets pruned away early (`can_match`).

**Comment by hendrikmuhs** [comment]
**Solution**

For the 7.x series we discussed this issue and decided to disable point in time search.

For 8.x we are discussing how we can bring the feature back. Measurements have [shown](https://github.com/elastic/elasticsearch/pull/74984#issuecomment-879729549) a positive effect when using point in time.

**Comment by StephanBenning** [comment]
diagnostic-a16d51-2021-Dec-22--15_35_39.zip (8.4 MB), has been uploaded to Cluster diagnostics 00865174.

You can download it with your browser here:

https://upload.elastic.co/d/9b80c7ce217986092cfb13b26e7d372f062d8ad67e1f58e641d0d33aba0b846b

Use this authorization token: a0475de6dd43f287

You can also download it on the command line:

curl -L -H 'Authorization: a0475de6dd43f287' \
       -o 'diagnostic-a16d51-2021-Dec-22--15_35_39.zip' \
       https://upload.elastic.co/d/9b80c7ce217986092cfb13b26e7d372f062d8ad67e1f58e641d0d33aba0b846b
