### ISSUE TITLE
7.16 should show discovery.zen.minimum_master_nodes as a critical deprecation

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#81260]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 8.0.0-SNAPSHOT, Build: default/rpm/a45e75d1cdaf3dda9af835ec63eb58dc0eeda174/2021-12-02T01:04:51.375129351Z, JVM: 17.0.1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): CentOS 7
Linux localhost.localdomain 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 7.16.0 (latest snapshot) doesn't show that my `discovery.zen.minimum_master_nodes` setting is deprecated but it will prevent 8.0 from starting.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. configure a single node on 7.16.0 with `discovery.zen.minimum_master_nodes: 0` in the elasticsearch.yml (mine was an rpm install but I wouldn't think that matters)
 2. run Kibana 7.16.0 connected to that node and check the Upgrade Assistant for any deprecations about that setting (not found)
 3. Upgrade to 8.0.0 (I used `yum install -y` of the rpm file)
 4. Elasticsearch has a fatal error and exits with a message like;
 ```
java.lang.IllegalArgumentException: unknown setting [discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking chang
```

**Provide logs (if relevant)**:

```
Dec 02 15:30:18 localhost.localdomain systemd-entrypoint[13813]: java.lang.IllegalArgumentException: unknown setting [discovery.zen.minimum_master_nodes] please check that any required plugins are installed, or check the breaking chang
```

**Comment by dakrone** [comment]
@masseyke would you be able to take a look at this one? I think it's small and can be quick to fix, but since it's such a common setting I definitely think we should address it soon.

**Comment by dakrone** [comment]
This has been resolved, but since the PR wasn't targeting master it didn't auto-close this issue. I'm closing this now.
