### ISSUE TITLE
A terminally deprecated method in java.lang.System has been called

### ISSUE THREAD

**Issue by tutengdihuang** [elastic/elasticsearch#81293]
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Elasticsearch (file:/Users/Allen/elasticsearch-7.15.2/lib/elasticsearch-7.15.2.jar)
WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Elasticsearch
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.elasticsearch.bootstrap.Security (file:/Users/Allen/elasticsearch-7.15.2/lib/elasticsearch-7.15.2.jar)
WARNING: Please consider reporting this to the maintainers of org.elasticsearch.bootstrap.Security

**Comment by DaveCTurner** [comment]
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/80344
