### ISSUE TITLE
Remove HLRC docs in 8.0 and master branches

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#81299]
From 8.0 and forward, the HLRC client will no longer be published. 
It currently exists in the codebase (in master and 8.0 branches), 
because a significant number of tests use it. So effectively it is test code now.

The docs for HLRC still exist in the master and 8.0 branches. I think we should remove these docs?
Or at least replace it with a redirect section about the new high level rest client?
Otherwise this can cause confusion about the old HLRC existence?

**Comment by debadair** [comment]
I can open a PR to remove & replace with a redirect page.

**Comment by martijnvg** [comment]
Thanks @debadair for commenting. I wasn't sure whether the HLRC docs were still being published for the 8.0 and master branches. I will open a PR for removing the HLRC docs.
