### ISSUE TITLE
TransformMetadata claims compatibility with all versions since 6.8

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#81292]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13-7.16

**Plugins installed**: []

**JVM version** (`java -version`): Any

**OS version** (`uname -a` if on a Unix-like system): Any

**Description of the problem including expected versus actual behavior**:

In 7.16, `TransformMetadata` declares itself to be wire-compatible with all known versions:

https://github.com/elastic/elasticsearch/blob/bcfbf000748b538884087623113682165abcb92d/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMetadata.java#L55-L58

I think this is false, this feature was introduced in 7.13.

Additionally its diff also does not override `getMinimalSupportedVersion()` so it is implicitly declaring itself to be compatible with all known versions; see https://github.com/elastic/elasticsearch/issues/81262 for details.

**Comment by droberts195** [comment]
Fixed in the 7.16 branch by #81300.  I didn't put the fix in master as that would have just created work when the 7.x version constants are deleted from master.
