### ISSUE TITLE
Script settings validation breaks mixed version cluster (7.15 + 7.16) 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#81486]
In #79508 the default value for `script.max_compilations_rate` [was changed](https://github.com/elastic/elasticsearch/pull/79508/files#diff-d072249a052aa7da92041f1e174a48ea6329987eaf927b8025aba11ddc2b2818L68-R71) from `"use-context"` to `"150/5m"`.

That means, that `validateCacheSetting` now treats `useContext` as false, and rejects any cluster settings on a context.
https://github.com/elastic/elasticsearch/blob/v7.16.0/server/src/main/java/org/elasticsearch/script/ScriptService.java#L349-L360

When in a mixed version cluster, the 7.15 node will accept cluster settings such as 
```
PUT /_cluster/settings
{
  "persistent": {
    "script.context.template.max_compilations_rate": "5000/5m"
  }
}
```
But the 7.16 version will reject them, and will fail to apply the cluster state on the local node.

Consequently, rolling upgrades with context settings will fail unless `script.max_compilations_rate` is explicitly set to `use-context` on the 7.15 node.

**Comment by stu-elastic** [comment]
To resolve this, we'll change the interpretation of `script.max_compilation_rate`.

Users who do not set the `script.max_compilation_rate` setting and have context settings will implicitly use the context cache.  Implicitly using the context cache this way is deprecated and will result in a deprecation warning with the same key as the warning for setting above to `"use-context"`.

We will reject setting `script.max_compilation_rate` to any value _other than_ "use-context" if the user has context settings.

cc: @colings86.

**Comment by stu-elastic** [comment]
Backport complete.
