### ISSUE TITLE
[docs] 7.16 docs referencing 7.6

### ISSUE THREAD

**Issue by cachedout** [elastic/elasticsearch#81499]
The 7.16 docs appear to reference both 7.6 and 7.16. I've highlighted some of this inconsistency in the screenshot below:

<img width="1036" alt="Screen Shot 2021-12-08 at 9 46 09 AM" src="https://user-images.githubusercontent.com/111616/145177900-769fcfcf-d000-40c3-b4fb-05824809cc31.png">

**Comment by DaveCTurner** [comment]
This is deliberate: each version of the docs includes the release notes for all the previous versions in the same major series. When you're upgrading to 7.16 you need to review all the release notes going back to the version from which you're upgrading, so we keep them all in once place. Also, the older branches are no longer maintained but we do sometimes need to make corrections and additions to the older versions' release notes, e.g. adding known issues discovered post-release, which we can do in the maintained 7.16 branch.
