### ISSUE TITLE
Updates causing hotspots in cluster when multiple primary shards for an index exist on a single node

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8149]
Some of our end users are seeing "hotspots" in the cluster when multiple primary shards for an index are allocated to a single node (unbalanced primary shards).  This becomes an issue when there are a lot of updates where the documents are loaded onto the primary shards first.    The http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-update-settings.html#_balanced_shards weight settings do not always help and require re-tuning when new nodes or new shards are added.  It will be nice to provide a setting similar to http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/index-modules-allocation.html#_total_shards_per_node , but only applies to primary shards, like total_primary_shards_per_node which allows the end user to define the maximum # of primary shards an index can have on a single node.  This will ensure that multiple primary shards are not allocated to the same node.

**Comment by s1monw** [comment]
removing the discuss tag since we are all on the same page here and we have #8369

**Comment by clintongormley** [comment]
Closing in favour of #8369
