### ISSUE TITLE
Should we parse search requests on the coordinating node?

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8150]
At the moment, the coordinating node uses the index name from URL and routing values from the query string to forward search requests directly to the shards where they should be executed.

This is very efficient, but does impose some limitations on the choices we can make at execution time.  For instance:

* #4272 asks for per-index routing values, which would need to be passed in the body
* #7298 raises the problem of limited space for index names in the URL
* #7570 complains about parsing errors being returned from all shards, rather than just one
* #6719 would allow terms-lookup filters, geo-shape lookup filters, indexed scripts or indexed templates to be fetched just once, instead of by every shard

All of the above (and possibly more?) could be fixed if we parsed the search request in the body. Should we consider doing this? What are the downsides? Would it be worth making it optional?

**Comment by s1monw** [comment]
we discussed this today and we all agreed that this would be awesome to have.

> Would it be worth making it optional?

I don't think we should make this optional but it's hard to do everything on the coordinating node. For instance we don't have the mappings instantiated for all indices or maybe not at all. But I think we can take a lot of advantage of this if we do a pre-parsing / rewrite stage. I think this would be awesome to have for lots of stuff like error reporting, prefetching, reducers and cacheing. maybe we should decouple parsing of the query and processing of it! I am +1 on that for sure

**Comment by javanna** [comment]
I removed the discuss label, I think we have consensus here. We are working on making this possible in #10217 , more specifically on https://github.com/elastic/elasticsearch/tree/feature/query-parse-refactoring branch

**Comment by javanna** [comment]
I think it's important to draw a line and define what we want to move to the coordinating node. It's clear that we want to parse json on the coordinating node, and throw any parsing error once from there. That said we don't have mappings on all nodes, thus any field related validation (e.g. unmapped field) will still be thrown on each data node, where we are sure we have the mappings.

As for terms/geo-shape lookup filters, it sounds good to reduce the roundtrips and have a single get to retrieve the pre-indexed terms/shapes, but then we would have to serialize them all on the wire to the data nodes, making the intermediate (`Streamable`) filter representation potentially much heavier. What do people think about this?

**Comment by martijnvg** [comment]
@javanna What about having the `IndexService` (with all  index level related services) for all indices available on all nodes, but the `IndexShard` instances should only exist on the nodes that actually hold the shards? I think this is possible without serious downsides? (for example all caches we have are per shard and not per index)

**Comment by javanna** [comment]
@martijnvg that means that even client nodes would have an `IndexService` per index, think of many indices potentially. I am not sure what the effect is going to be on non data nodes (think of master nodes too), sounds scary at first glance.

I am marking this issue back for discussion, I think we should collect thoughts around mappings on coordinating nodes and how to split the work when it comes to pre-indexed terms/shapes/what have you.

**Comment by martijnvg** [comment]
@javanna true, in case of many indices this would increase memory usage, but on the other hand in case of many indices in general this is already quite heavy (for example the size of the cluster state). 

For the (elected) master node, I think we shouldn't even use it is a coordinating node to begin with, but it should simple redirect any incoming request to another data node.

For the client node, I think it ok to do this? It think it is ok to increase the maximum heap space a bit for this purpose. Maybe this behaviour should be controllable via a setting? Maybe this behaviour isn't preferable if a client node is running inside another jvm process.

**Comment by rjernst** [comment]
I agree with @martijnvg. Don't we already (or will soon?) have the cluster state on every node? It seems silly when we have the mappings sitting around, but can't use them to do the validation.

**Comment by kimchy** [comment]
The ability to do validation means we need to materialize the mappings for any potential index that will exist in the cluster, compared to relaying on the natural distribution of indices across the data nodes. 

There is a big difference between storing the mappings in compressed fashion in the cluster state (which is present on each node), and having all the index level data structures around on each node. 

This will be a problem with many indices. Historically, btw, ES used to store the index level data structure on each node (not for any specific reason like validation, just because the optimization was not there), and it ended up being significant, which is why only materializing the index level data structures only where shards are allocated ended up happening.

**Comment by martijnvg** [comment]
Being able to validate a search request in the coordination node is very neat, it is just unfortunate that the many IndexService instances is problematic. I think for most of the many indices cases the mappings between indices are likely to be the same or similar. Maybe it would be less of problem if for example the MapperService was able to share DocumentMapper instances between indices on the same node that are equal.

**Comment by javanna** [comment]
We seem to be on the fence on this, I think that we might want to go ahead with parsing on the coordinating node without moving mappings checks there just yet. We can always do it once we have the infra for it though. 

What do people think about terms lookups etc.? If we lookups on the coordinating node it's going to be a single get call, but then we would need to serialize all of the terms to all of the data nodes which kinda defeats the purpose of terms lookups somehow?

**Comment by kimchy** [comment]
@javanna I think we should make it in steps, and keep the existing behavior as is today, and focus on parsing on the coordinating node, and keep the lookups and such on the shard?

**Comment by javanna** [comment]
sounds good @kimchy I agree

**Comment by clintongormley** [comment]
Closing in favour of #10217
