### ISSUE TITLE
[Transform] Improve instructions for obsolete transform configuration warning

### ISSUE THREAD

**Issue by pheyos** [elastic/elasticsearch#81521]
In the 8.0 Upgrade Assistant we can see the following critical error for old transform configurations:

![image](https://user-images.githubusercontent.com/1945390/145211155-9bd7c7e0-dc05-4191-a0ed-ec8aa8076aec.png)

The help text tells the user to use `_update` or `_upgrade` to fix this issue, but it would be good to include the full endpoint (`/_transform/<transform_id>/_update` or `/_transform/_upgrade`) to give the user a more concrete instruction. It might also be good to mention that `/_transform/_upgrade` will fix this for all transforms while `/_transform/<transform_id>/_update` will only operate on a single transform.
Maybe something like this?
```
Use [/_transform/tf2c/_update] to update the configuration of [tf2c] or [/_transform/_upgrade] to do it for all transforms.
```

**Comment by sophiec20** [comment]
Suggest we point them towards using `_upgrade`.

`Use [/_transform/_upgrade] to prepare all transforms for upgrade.`

**Comment by hendrikmuhs** [comment]
It seems we miss what happens if you don't upgrade, I suggest:

```
This transform configuration uses obsolete syntax which will be unsupported after the next upgrade. Use [/_transform/_upgrade] to prepare all transforms for upgrade.
```

**Comment by przemekwitek** [comment]
@pheyos: The messages have been changed in the PRs listed above.

After verification you can close this issue.

**Comment by pheyos** [comment]
Looks good in 7.17.0 upgrade assistant.
