### ISSUE TITLE
Remove IndexDeprecationChecks#tooManyFieldsCheck?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#81539]
This tries to find all indices that have more than 1024 fields and `index.query.default_field` unset. While this is a good thing to warn our users about, the fact that it shows up in the upgrade assistant suggests that it's a problem for the upgrade while 8.0 is not going to make things worse than 7.x.

I suggest that we remove this check in 8.0 and look if we need to improve the error message when too many fields are queried at once to recommend setting `index.query.default_field` on affected indices?

**Comment by jpountz** [comment]
Note to self: I could not set the version as 7.17 since it's not created yet but it's important that this goes in 7.17 since this is the version that users use to run the upgrade assistant.

**Comment by romseygeek** [comment]
We discussed this briefly in the search team meeting and agreed that we should get this in for 7.17.

**Comment by albertzaharovits** [comment]
Closed in https://github.com/elastic/elasticsearch/pull/82809
