### ISSUE TITLE
7.0 migration guide should not recommend setting `indices.query.bool.max_clause_count`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#81538]
The 7.0 migration guide recommends setting `indices.query.bool.max_clause_count` on indices that have many fields. We shouldn't make this recommendation. This setting is a node setting that cannot be set on Cloud and requires restarting on premise. The only correct way to work around indices with many fields is to set `index.query.default_field` as already documented.

**Comment by javanna** [comment]
This fell through the cracks. I assume it is not too late to fix it given we are at 8.15 :)
