### ISSUE TITLE
[DOCS] Formalize definitions of regular, dot, hidden, and system indices

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#81531]
Based on a comment from @gwbrown in #81226:

> I wonder (not for this PR), could we formalize the definition of a "regular" index somewhere if we haven't already? If we have, I'm going to start using that term in error messages and warnings about system indices.

We now have a few different types of indices. It would be good to formalize definitions for them. I've included some brief notes below based on my understanding. For conciseness, "index" means both "data stream" and "index" in this context.

**System index:** An index containing configurations and other data used internally by the Elastic. System indices are not intended for direct access or modification. All system indices are dot indices.

**Regular index**: Any index that isn't a system index. You can directly access or change regular indices, even if they're hidden. A regular index typically contains user data. However, some features may also create hidden regular dot indices.

**Dot index:** An index with a name that starts with a dot (`.`). Dot indices include system indices, such as `.kibana` and `.security`, and hidden regular indices created by Elastic features, such as `.watcher-history-*`. Only Elastic can create dot indices; users can't.

**Hidden index:** A regular index that's "hidden" from wildcard (`*`) patterns in API requests. To match hidden indices using a wildcard pattern, you can specify the `expand_wildcards` parameter. Some features may create hidden dot indices that can be accessed or changed by the user. Users can also create hidden indices using the respective `data_stream.hidden` and `index.hidden` options.

Relates to https://github.com/elastic/elasticsearch/issues/79679

**Comment by williamrandolph** [comment]
> System index: An index containing configurations and other data used internally by the Elastic. In 8.0+, you cannot directly access or change system indices. All system indices are dot indices.

Unfortunately, in 8.0+, you just get a warning when you try to directly access or change system indices.

**Comment by jrodewig** [comment]
Thanks for pointing that out @williamrandolph. I've updated the issue description accordingly.

**Comment by Leaf-Lin** [comment]
Thank you for this issue!! In addition to improve on the API conventions page: https://www.elastic.co/guide/en/elasticsearch/reference/master/api-conventions.html#system-indices,

I somehow expect this information will be linked from the https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html page naturally.  Perhaps in the `expand_wildcard` option, we can mention different types of indices are available and not shown by default and link to the above API conventions page?

**Comment by ppf2** [comment]
As part of this work, it will be helpful to also provide and maintain the full list of system and dot indices created by Elasticsearch, Kibana, Machine Learning and our solutions so that we have a single source of truth of the list of indices users should not directly modify themselves.

**Comment by consulthys** [comment]
> Dot index: An index with a name that starts with a dot (.). Dot indices include system indices, such as .kibana and .security, and hidden regular indices created by Elastic features, such as .watcher-history-*. Only Elastic can create dot indices; users can't.

It's definitely possible for a user to create a dot index, i.e. the following commands works in ES 8.
```
PUT .ds-logs-foo-bar-2024.05.31-0000001
```
