### ISSUE TITLE
Nested: Change structure of the nested query and filter

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#8155]
Currently the structure of the `nested` query is:
```json
{
   "nested" : {
      "path" : "a-nested-object-path",
      "query ": { <query> } 
   }
}
```

If the structure were to be changed to:

```json
{
   "nested" : {
      "a-nested-object-path" : {
         "query" : { <query> } 
      }  
   }
}
```

Then the structure is streaming parsing friendly and the nested object path is always known when the `query` is parsed. Also the `NestedQueryParser.LateBindingParentFilter` workaround can then be removed.

Like in #8154 nested path validation can then also be added, so that when a `nested` query is wrapped in another `nested` query a parser error can be thrown if the supplied paths don't match with each other.

**Comment by jpountz** [comment]
LateBindingParentFilter was removed on https://github.com/elasticsearch/elasticsearch/pull/9692 so this issue is only about making parsing more friendly I guess?

**Comment by javanna** [comment]
I wonder if this becomes obsolete given that we now parse queries on the coordinating node. Is it still something that we want to consider doing @martijnvg ?

**Comment by martijnvg** [comment]
@javanna yes, the issue can be closed. Looking up field mappings and other things that are type specific  happens when we build the lucene query and at that time the type is already known, because the query has already been parsed on the coordination node.
