### ISSUE TITLE
[DOCS] Document anatomy of a search request

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#81601]
We should consider adding an "anatomy of a search request" section that walks users through the various phases of search execution. While not required to run a search, understanding these phases can be helpful when troubleshooting issues. It can also help users better understand recent improvements made to search execution.

Relates to:

* https://github.com/elastic/elasticsearch/pull/78765
* https://github.com/elastic/elasticsearch/pull/79212

**Comment by lockewritesdocs** [comment]
This is a great idea, and I think that an infographic could be very useful to help explain the different phases.

**Comment by jrodewig** [comment]
Related blog post: https://www.elastic.co/blog/three-ways-improved-elasticsearch-scalability/
