### ISSUE TITLE
Stop unnecessary retries of shard-started tasks

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#81628]
When a data node finishes recovering a shard it notifies the master to move it to state `STARTED`. Today we repeat this request every time we receive a cluster state that hasn't updated the shard state yet:

https://github.com/elastic/elasticsearch/blob/b6fbf5a1548c1924e67c360af2b6dd8ec51508ce/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java#L601-L619

This behaviour means if the master is busy processing (potentially thousands) of other `URGENT` tasks then we'll submit the same task repeatedly (potentially thousands of times). It dates back a long time but is no longer necessary: we can trust that the master will process our original request first (or we get notified that it failed). We should stop sending these unnecessary retries.

Relates https://github.com/elastic/elasticsearch/issues/77466

**Comment by DaveCTurner** [comment]
Unfortunately @original-brownbear I don't think #82089 completely fixes this, because we send the response back as soon as the cluster state update is submitted without waiting for it to complete:

https://github.com/elastic/elasticsearch/blob/212d15ba1e754e80bc2409bdcc5522e19b89cac3/server/src/main/java/org/elasticsearch/cluster/action/shard/ShardStateAction.java#L626-L642

**Comment by original-brownbear** [comment]
Oh wow, you're right. Easy fix by moving the resolving of the listener to after the CS state update is through I guess. Will implement this in a bit. Thanks for catching!
