### ISSUE TITLE
Batch add-block-index-to-close, add-index-block and finalize-index-block tasks

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#81627]
The process of closing an index involves multiple cluster state updates to add and finalise its blocks; there are also other reasons for adding blocks to an index. ILM may close an index to adjust its codec prior to force-merging, and may apply a write block for other reasons. Today the associated cluster state update tasks run at priority `URGENT` and are not batched, so can take a very long time to process and gum up other things.

I encountered a cluster that was processing a few thousand such tasks at a rate of about 20 per minute.

We should batch these tasks together to avoid this causing a problem in future.

Relates https://github.com/elastic/elasticsearch/issues/77466

**Comment by joegallo** [comment]
Handled by way of https://github.com/elastic/elasticsearch/pull/83760, https://github.com/elastic/elasticsearch/pull/84259, and https://github.com/elastic/elasticsearch/pull/84374.
