### ISSUE TITLE
HLRC 7.16.0 was not released on Maven Central

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch#81663]
Looking that the [current clients documentation](https://www.elastic.co/guide/en/elasticsearch/client/index.html), we can see that HLRC is still at version 7.15 while other clients are correctly at version 7.16.

Digging further, I found out that HLRC 7.16 wasn't [published to Maven central](https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-high-level-client).

According to @jakelandis this may be related to not publishing HLRC in 8.0.0 that could mistakenly also have been extended to 7.16.

**Comment by dakrone** [comment]
That's strange, let me check with the @elastic/es-delivery team about whether we removed it in the wrong way.

**Comment by dakrone** [comment]
@swallez the artifacts are on maven central:

    repo1.maven.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/7.16.0
    repo1.maven.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/7.16.1

It's likely that the search portal might not have updated yet, and is just lagging behind.

**Comment by dakrone** [comment]
Going to close this for now, lemme know if I should re-open it.

**Comment by swallez** [comment]
Thanks @dakrone. Indeed the Maven Central front-end seems to be out of sync, as neither 7.16.0 nor 7.16.1 are [present in the portal](https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-high-level-client) yet both are effectively present in [the directory listing](https://repo1.maven.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/).
