### ISSUE TITLE
Missing doPriviliged in deprecation logger 

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#81708]
possibly a doPriviliged in deprecation logger together with a test DeprecationLoggerTests.testLogPermissions
were accidentally removed. 
This is possibly a regression.

Scripts run under reduced privileges. (can @elastic/es-core-infra help?) and
the test was introduced to verify deprecation logger not violating Security Manager permission when rolling over the files. 
7.0+
https://github.com/elastic/elasticsearch/pull/37281/files#diff-70de5a6ba5c637e7f19c51341417760d6e957beb5a1fa5703049095ea2719ee0R322

However the doPriviliged call in deprecation logger was removed in (7.10+) https://github.com/elastic/elasticsearch/pull/55941/files#diff-593ea478a0a8d462fd38ad70838ee6e4a28673478d28812c48d9ed5cf768c132L249

The test itself was removed in 7.10+
https://github.com/elastic/elasticsearch/pull/61474/files#diff-70de5a6ba5c637e7f19c51341417760d6e957beb5a1fa5703049095ea2719ee0L47

@stu-elastic or @jdconrad  do you remember more context about this? Do you think this should be fixed?

**Comment by nik9000** [comment]
I think you are correct, we should revive this test and get it passing.
