### ISSUE TITLE
elasticsearch returns inconsistent result on v7.8.1 and returns correct result on v5.6.7 for the same match_phrase_prefix query

### ISSUE THREAD

**Issue by animeshmdhokare** [elastic/elasticsearch#81702]
Observing inconsistency in the result for match_phrase_prefix query on elasticsearch 7.8.1.

**Steps to Reproduce:**
1.Create index with mappings given below
```
mappings {
                    Test {
                        "properties" {
                            "fullText" {
                                "type" "text"
                            }
                            "name" {
                                "type" "text"
                                "store" true
                                "fielddata" true
                                "copy_to" "fullText"
                                "fields" {
                                    "raw" {
                                        "type" "keyword"
                                    }
                                    "suffix" {
                                        "type" "text"
                                        "analyzer" "suffix_match_analyzer"
                                    }
                                }
                            }
                            "created" { "type" "date" }
                            "dbId" {
                                "type" "long"
                                "copy_to" "fullText"
                            }
                            "empId" {
                                "type" "long"
                                "copy_to" "fullText"
                            }
                            "active" { "type" "boolean" }
                            "salary" { "type" "float" }
                            "category" { "type" "keyword" }
                            "sub-category" { "type" "keyword" }
                            "address" {
                                "type" "keyword"
                                "copy_to" "fullText"
                                "fields" {
                                    "raw" {
                                        "type" "ip"
                                        "ignore_malformed" "true"
                                    }
                                }
                            }
                        }
                    }
                }
```
2.Insert 9901 documents as given in sample data out of which 8910 docs will start with name: "Trust" and remaining docs will start with some other values
**Sample Data**
```
{
                "_index": "match-phase-prefix-test-1",
                "_type": "_doc",
                "_id": "2",
                "_score": null,
                "_source": {
                    "empId": 2,
                    "subCategory": "HR-1",
                    "address": "206.119.194.11",
                    "created": "2021-11-27T08:33:43+0000",
                    "dbId": 2,
                    "name": "Trust_11_29_2021_AAAA_BBBB_CCCC2",
                    "active": true,
                    "category": "HR",
                    "salary": 1.253117561340332
                },
                "sort": [
                    1638002023000
                ]
            }
```

**QUERIES:**
**Query1:  should**
```
{
    "sort": [{
            "created": {
                "order": "desc"
            }
        }
    ],
    "size": 10000,
    "query": {
        "bool": {
            "should": [{
                    "match_phrase_prefix": {
                        "name": {
                            "query": "Trust",
                            "slop": 100,
                            "max_expansions": 50,
                            "boost": 1.0
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1.0
        }    }
}
```
**Query2:  must_not**
```
{
    "sort": [{
            "created": {
                "order": "desc"
            }
        }
    ],
    "size": 10000,
    "query": {
        "bool": {
            "must_not": [{
                    "match_phrase_prefix": {
                        "name": {
                            "query": "Trust",
                            "slop": 100,
                            "max_expansions": 50,
                            "boost": 1.0
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1.0
        }    }
}
```
**RESULTS**

**ELS v5.6.7**
8910 - should -starts with Trust | max_expansion:50 | CORRECT RESULT
991 - must_not -Trust | max_expansion:50 | CORRECT RESULT
9901 - total doc count

**ELS v7.8.1**
250 - should -Trust | max_expansion:50 | WRONG RESULT
9651 - must_not -Trust | max_expansion:50 | WRONG RESULT
9901 - total doc count

250 - should -Trust | max_expansion:500 | WRONG RESULT
7401 - must_not -Trust | max_expansion:500 | WRONG RESULT
9901 - total doc count

8910 - should -Trust | max_expansion:5000 | CORRECT RESULT
991 - must_not -Trust | max_expansion:5000 | CORRECT RESULT
9901 - total doc count

8910 - should -Trust | max_expansion:10000 | CORRECT RESULT
991 - must_not -Trust | max_expansion:10000 | CORRECT RESULT
9901 - total doc count

8910 - should -starts with Trust | max_expansion:50 | CORRECT RESULT | after removing suffix analyzer
991 - must_not -Trust | max_expansion:50 | CORRECT RESULT | after removing suffix analyzer
9901 - total doc count

**MAPPINGS on both versions i.e v7.8.1 and v5.6.7 is same and data inserted is also same**

**NOTE:** It is seen that increasing max_expansion on V7.8.1 to a certain value returns the correct result.

For the same query and mappings, I'm getting the correct result on V5.6.7. How do I get this result on V7.8.1?Do I need to update mappings or form a different query for V7.8.1?and if so why does it work on V5.6.7 and not on V7.8.1?

Thanks, 
Animesh

**Comment by markharwood** [comment]
Hi @animeshmdhokare 
I'm not sure exactly how to interpret the results presented but, speaking generally, a change in relevance rankings of optional search terms is not necessarily a bug. Ranking algorithms and storage formats can change.

For example, newer versions of elasticsearch[ default to using 1 shard ](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#_static_index_settings) rather than the old setting of 5. That may account for most of the differences you see in ranking. Another may be [the introduction of BM25 scoring](https://www.elastic.co/elasticon/conf/2016/sf/improved-text-scoring-with-bm25) 
Even without changing software versions, ranking positions can change simply due to changes to documents that don't even match the search criteria (they change background frequencies of terms and numbers of docs used in scoring).

If you need stable sort orders you will probably need to resort to some custom sort order. 
For these reasons I'm closing this issue, but feel free to reopen if I've overlooked something

**Comment by animeshmdhokare** [comment]
Hi @markharwood,
Thanks for quick reply.

We have created a dataset where 8910 documents contain field "name" which starts with value "Trust"
and 991 documents contain the same field which does not start with "Trust". Hence the total doc count is 9901(8910+991).

In above result section , we are trying to search 
1. String that starts with "Trust" _(should query)_ and expect that it will return correct doc count i.e. 8910 
2. String that does not start with "Trust" _(must_not query)_ and expect that it will return correct doc count i.e. 991

If we try to execute query mentioned in the ticket, on v5.6.7, we get correct results for point 1 and 2. But for the same query we observe different set of results on 7.8.1 **_(i.e for "must_not" query we are getting strings which starts with "Trust" which is wrong result leading to wrong doc count)_**

On v7.8.1, when we increased _max_expansion from 50 to 10000_, the same query started giving correct results(mentioned in point 1 & 2). We are getting the _wrong results in sorted order_ provided in query.

Although, increasing max_expansion to certain number gives correct result, it comes with performance issues. Also, we can not identify correct value for larger datasets available in production environments. 
Below is the result on 1M documents.
<img width="423" alt="els_bug" src="https://user-images.githubusercontent.com/19922659/145986823-869215c5-f902-4be4-b823-2f8f7d40a604.png">

I'm running the same query back to back on an index and results come back different for each hit. How can I get consistent result on v7.8.1? Is there any specific change related to "match_phrase_query" implemented on v7.8.1 as compared to v5.6.7?
Can you please try to reproduce this at your end and see if you can get some pointers over this? Do we need to perform any server side config operations to get consistent result set for "match_phrase_query" on v7.8.1? Please suggest.

**Comment by markharwood** [comment]
Reopened while I review. Closed https://github.com/elastic/elasticsearch/issues/81718

**Comment by markharwood** [comment]
>How can I get consistent result on v7.8.1? 

Increasing max_expansion looks to be the answer (albeit with a performance cost).

I'm generally not a fan of match_phrase_prefix because of the naive way it expands search terms (as it warns about [in the notes](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-query-phrase-prefix.html#match-phrase-prefix-query-notes)).

It would be wise to consider the alternative suggestions the docs outline or index using shingles.

Here is not the place to discuss those alternatives that would be the elasticsearch [forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) so I'll close this as a non-bug (it's a documented quirk of the match_phrase_prefix behaviour).

**Comment by animeshmdhokare** [comment]
Hi @markharwood,
Thanks for the explanation.

I have created a discussion topic few days back on this issue on elastic forum but did not get any response. Please find below link.
https://discuss.elastic.co/t/why-does-elasticsearch-return-inconsistent-result-on-version-7-8-1-and-return-correct-result-on-5-6-7-for-the-same-match-phrase-prefix-query-how-can-i-get-consistent-result-on-elasticsearch-7-8-1/290722

Also, It would be really helpful to us , if you suggest your views on above issue in the forum.
