### ISSUE TITLE
`deprecation.skip_deprecated_settings` is not considered when updating _cluster/settings

### ISSUE THREAD

**Issue by tobio** [elastic/elasticsearch#81700]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16

**Plugins installed**: On Cloud

**JVM version** (`java -version`): On Cloud

**OS version** (`uname -a` if on a Unix-like system): On Cloud

**Description of the problem including expected versus actual behavior**:
`xpack.monitoring.*` settings are deprecated in [7.16](https://github.com/elastic/elasticsearch/pull/79499)

We've added that wildcard to deprecation.skip_deprecated_settings in Cloud. Whilst settings defined in the `elasticsearch.yml` file are correctly skipped and not logged to deprecations.yml, adding monitoring settings via `_cluster/settings` continues to log deprecations for these monitoring settings.

**Steps to reproduce**:

 1. Include the following in elasticsearch.yml

 ```
deprecation.skip_deprecated_settings:
  - "xpack.monitoring.*"

xpack.monitoring.exporters.found-user-defined.enabled: false
xpack.monitoring.exporters.found-user-defined.type: "http"
xpack.monitoring.exporters.found-user-defined.host: "undefined-monitoring-host"
```

 2. Start up Elasticsearch
 3. Verify no deprecation logs related to xpack.monitoring.* are present
 4. Add a new exporter in the persistent settings

```
PUT _cluster/settings
{
  "persistent": {
    "monitoring": {
      "exporters": {
        "found-user-defined": {
          "host": [
            "http://example.com:9244"
          ],
          "type": "http",
          "enabled": "true"
        }
      }
    }
  }
}
```

Expected:
No deprecation logs related to xpack.monitoring.*

Actual:

```
[xpack.monitoring.exporters.found-user-defined.type] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
```

And similar

**Provide logs (if relevant)**:

**Comment by masseyke** [comment]
The test in the description now passes with #81836
