### ISSUE TITLE
[DOCS] Several APIs are missing mapping type parameters

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#81739]
During #45195, we reformatted the documentation for most Elasticsearch APIs. When backporting the changes to 7.x branches, we failed to document the mapping type request path parameter for several APIs.

We should update the docs to include these parameters. This'll prevent confusion when users upgrade to 8.0, where mapping types have been removed.

APIs:

- [ ] [Bulk](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-bulk.html)
- [ ] [Delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-delete-by-query.html)
- [ ] [Delete](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-delete.html)
- [ ] [Explain](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-explain.html)
- [ ] [Get document](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-get.html)
- [ ] [Get field mapping](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-get-field-mapping.html)
- [ ] [Get mapping](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-get-mapping.html)
- [ ] [Graph explore](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/graph-explore-api.html)
- [ ] [Index document](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-index_.html)
- [ ] [mget](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-multi-get.html)
- [ ] [Multi search template](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/multi-search-template.html)
- [ ] [Multi search](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-multi-search.html)
- [ ] [Multi term vectors](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-multi-termvectors.html)
- [ ] [Rollup search](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/rollup-search.html)
- [ ] [Search](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-search.html)
- [ ] [Search template](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-template-api.html)
- [ ] [Term vectors](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-termvectors.html)
- [ ] [Update](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-update.html)
- [ ] [Update by query](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docs-update-by-query.html)
- [ ] [Update mapping](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-put-mapping.html)
- [ ] [Validate](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-validate.html)

**Comment by debadair** [comment]
Manually patching the API ref pages is a low priority as we're trying to move to generating the API ref pages. That said...if this is causing notable migration pain for longtime users, we might want to revisit.

**Comment by javanna** [comment]
This does not seem to be relevant anymore.
