### ISSUE TITLE
[DOCS] Final pipeline limitation on setting _index is missing from 7.x documentation

### ISSUE THREAD

**Issue by a03nikki** [elastic/elasticsearch#81741]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.12-7.16 and 7.x

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:
https://github.com/elastic/elasticsearch/pull/59522 added restrictions to the final pipeline with the documentation updated by https://github.com/elastic/elasticsearch/pull/76997.  The documentation changes were back ported to a number of versions, but they are still missing from the more recent 7.x versions of Elasticsearch.

It appears a few of the back ports were missed on #76997.
Please add the `note` to versions 7.12-7.16 and 7.x.

**Steps to reproduce**:

✅ https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html

>  **index.final_pipeline**
>     Final ingest pipeline for the index. Indexing requests will fail if the final pipeline is set and the pipeline does not exist. The final pipeline always runs after the request pipeline (if specified) and the default pipeline (if it exists). The special pipeline name _none indicates no ingest pipeline will run.
>
> Note  You can’t use a final pipeline to change the _index field. If the pipeline attempts to change the _index field, the indexing request will fail.

✅ https://www.elastic.co/guide/en/elasticsearch/reference/7.9/index-modules.html
✅ https://www.elastic.co/guide/en/elasticsearch/reference/7.10/index-modules.html
✅ https://www.elastic.co/guide/en/elasticsearch/reference/7.11/index-modules.html
✅ https://www.elastic.co/guide/en/elasticsearch/reference/8.0/index-modules.html

❌ https://www.elastic.co/guide/en/elasticsearch/reference/7.12/index-modules.html
> index.final_pipeline
>     The final ingest node pipeline for this index. Index requests will fail if the final pipeline is set and the pipeline does not exist. The final pipeline always runs after the request pipeline (if specified) and the default pipeline (if it exists). The special pipeline name _none indicates no ingest pipeline will run. 

❌ https://www.elastic.co/guide/en/elasticsearch/reference/7.13/index-modules.html
...
❌ https://www.elastic.co/guide/en/elasticsearch/reference/7.16/index-modules.html
❌ https://www.elastic.co/guide/en/elasticsearch/reference/7.x/index-modules.html

**Provide logs (if relevant)**: N/A

**Comment by danhermann** [comment]
This has been backported to all the 7.x branches and will be picked up in the next docs build/publish cycle.
