### ISSUE TITLE
Disable Unsafe usage from Groovy dependency

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#8175]
We should set the system property `groovy.json.faststringutils.disable=true` to ensure Groovy does not use the Unsafe APIs.

**Comment by javanna** [comment]
I wonder it this is still relevant at this point or we need to take some action. @dakrone ?

**Comment by dakrone** [comment]
@javanna it's still a "nice-to-do" even with Groovy as a plugin.

**Comment by rmuir** [comment]
Strong +1 to fix this: security manager will not allow it to do this (https://github.com/groovy/groovy-core/blob/master/subprojects/groovy-json/src/main/java/groovy/json/internal/FastStringUtils.java#L43-L57), but its a big reliability risk if someone disables security manager.

This particular optimization uses Unsafe to change *final fields* of String, which is pretty scary. It has JVM-specific implementations (https://github.com/groovy/groovy-core/blob/master/subprojects/groovy-json/src/main/java/groovy/json/internal/FastStringUtils.java#L155), and although it tries to be a little defensive, who knows if its really correct in all cases.

Just think about stuff like this going forward too: https://bugs.openjdk.java.net/browse/JDK-8134758 and https://bugs.openjdk.java.net/browse/JDK-8054307

IMO: disable it unconditionally!

**Comment by dakrone** [comment]
> IMO: disable it unconditionally!

+1

**Comment by uschindler** [comment]
Nuke that. I don't want to know how many buggy code tries to deoptimize strings and crush! :(

**Comment by s1monw** [comment]
++ I think we are sold! @dakrone feel free to open a PR please

**Comment by clintongormley** [comment]
Has this already been implemented by another change?

**Comment by tlrx** [comment]
@clintongormley We no longer use the `groovy-all` dependency but only the core `groovy`, I think we can close this issue: the system property `groovy.json.faststringutils.disable` was used by the class `FastStringUtils`which is not shipped anymore.
