### ISSUE TITLE
SQL: Name resolution in filter is not consistent with resolution in projection

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#81770]
While looking into #81577 I saw that name resolution in filters does not behave the same way as resolving names in projections which can lead to subtle errors in some edge cases:

E.g. the query `select gender emp_no, emp_no e from test_emp where e > 10099` yields the following result:

```
    emp_no     |       e
---------------+---------------
M              |10001
F              |10002
M              |10003
M              |10004
M              |10005
F              |10006
F              |10007
M              |10008
F              |10009
...
```

The expected result would be equivalent to the result of `select gender emp_no, emp_no e from test_emp where emp_no > 10099`:

```
    emp_no     |       e
---------------+---------------
F              |10100
```

Looking at the analyzed plan reveals that SQL resolves `e > 10099` in the `where` clause to `gender > 10099`. This is not consistent with the projection where `e` resolves to `emp_no`.

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/81800.
