### ISSUE TITLE
Batch index setting update tasks

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#81789]
Similarly to https://github.com/elastic/elasticsearch/issues/81627 sometimes ILM will update some settings on a large number of indices one at a time and today each of these tasks is processed as a separate cluster state update. Worse, every such task runs `AllocationService#reroute`. We should batch such tasks together into a single cluster state update with a single reroute at the very end.

Relates #77466

**Comment by original-brownbear** [comment]
I just realized this is a duplicate of https://github.com/elastic/elasticsearch/issues/79866 -> mine was earlier so closing here
