### ISSUE TITLE
elastic search high cpu usage on OCP(openshift container platform) cluster on s390x platform.

### ISSUE THREAD

**Issue by coldbloodx** [elastic/elasticsearch#81797]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.10.2

**Plugins installed**: [N/A]

**JVM version** (`java -version`):
AdoptJDK/JRE 11
AdoptJDK/JRE 14

**OS version** (`uname -a` if on a Unix-like system):

Linux api.cpdplus64.cp.fyre.ibm.com 4.18.0-348.2.1.el8_5.s390x #1 SMP Mon Nov 8 10:08:25 EST 2021 s390x s390x s390x GNU/Linux
[root@api.cpdplus64.cp.fyre.ibm.com docker]# ssh core@worker0 uname -a
Linux worker0.cpdplus64.cp.fyre.ibm.com 4.18.0-305.19.1.el8_4.s390x #1 SMP Tue Sep 7 06:59:13 EDT 2021 s390x s390x s390x GNU/Linux
[root@api.cpdplus64.cp.fyre.ibm.com docker]#

**Description of the problem including expected versus actual behavior**:

**on S390x platform the cpu usage is 50 times higher than x64 platform:**

[root@api.cpdplus64.cp.fyre.ibm.com docker]# arch ; oc adm top pods --sort-by=cpu --all-namespaces |grep elastic
**s390x**
zen                                                elasticsearch-master-0                                        **1405m**        1313Mi
zen                                                elasticsearch-master-1                                        **1113m**        1299Mi
zen                                                elasticsearch-master-2                                        **1004m**        1281Mi
[root@api.cpdplus64.cp.fyre.ibm.com docker]#

Last login: Wed Dec 15 22:22:44 2021 from 9.197.119.157
[root@api ~]#  arch ; oc adm top pods --sort-by=cpu --all-namespaces |grep elastic
**x86_64**
zen                                                elasticsearch-master-0                                            **22m**          1394Mi
zen                                                elasticsearch-master-1                                            **20m**          1374Mi
zen                                                elasticsearch-master-2                                            **17m**          1378Mi
[root@api ~]# s390x
-bash: s390x: command not found
[root@api ~]#

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. ES does not official support S390x platform, update below SystemCallFilter.java,  ES could run on S390x OCP platform:
 ```    sed -i '/ARCHITECTURES = Collections.unmodifiableMap(m);/ i \ \ \ \ \ \ \ \ m.put("s390x", new Arch(0x80000016, 0xFFFFFFFF, 1, 190, 11, 354, 348));' server/src/main/java/org/elasticsearch/bootstrap/SystemCallFilter.java ```

 2.the jvm.options is configured as below:
```
bash-4.4$ cat jvm.options
## JVM configuration

################################################################
## IMPORTANT: JVM heap size
################################################################
##
## You should always set the min and max JVM heap
## size to the same value. For example, to set
## the heap to 4 GB, set:
##
## -Xms4g
## -Xmx4g
##
## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
## for more information
##
################################################################

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms1g
-Xmx1g

################################################################
## Expert settings
################################################################
##
## All settings below this section are considered
## expert settings. Don't tamper with them unless
## you understand what you are doing
##
################################################################

## GC configuration
8-13:-XX:+UseConcMarkSweepGC
8-13:-XX:CMSInitiatingOccupancyFraction=75
8-13:-XX:+UseCMSInitiatingOccupancyOnly

## G1GC Configuration
# NOTE: G1 GC is only supported on JDK version 10 or later
# to use G1GC, uncomment the next two lines and update the version on the
# following three lines to your version of the JDK
# 10-13:-XX:-UseConcMarkSweepGC
# 10-13:-XX:-UseCMSInitiatingOccupancyOnly
14-:-XX:+UseG1GC
14-:-XX:G1ReservePercent=25
14-:-XX:InitiatingHeapOccupancyPercent=30

## JVM temporary directory
-Djava.io.tmpdir=${ES_TMPDIR}

## heap dumps

# generate a heap dump when an allocation from the Java heap fails
# heap dumps are created in the working directory of the JVM
-XX:+HeapDumpOnOutOfMemoryError

# specify an alternative path for heap dumps; ensure the directory exists and
# has sufficient space
-XX:HeapDumpPath=data

# specify an alternative path for JVM fatal error logs
-XX:ErrorFile=logs/hs_err_pid%p.log

## JDK 8 GC logging
8:-XX:+PrintGCDetails
8:-XX:+PrintGCDateStamps
8:-XX:+PrintTenuringDistribution
8:-XX:+PrintGCApplicationStoppedTime
8:-Xloggc:logs/gc.log
8:-XX:+UseGCLogFileRotation
8:-XX:NumberOfGCLogFiles=32
8:-XX:GCLogFileSize=64m

# JDK 9+ GC logging
```

 3. start ES and check log through "oc logs", found below two exception:
 a).
"stacktrace": ["java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable", 

b).
"stacktrace": ["java.net.SocketException: Connection reset",
"stacktrace": ["java.net.SocketException: Connection reset",
"stacktrace": ["java.net.SocketException: Connection reset",

4. for above exception in a), try add below in jvm.options:
--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
-Dio.netty.tryReflectionSetAccessible=true 

it does not work.

Hope you can give me some input.
Thanks in advance.

**Provide logs (if relevant)**:

[es.log.lastest.tar.gz](https://github.com/elastic/elasticsearch/files/7725741/es.log.lastest.tar.gz)

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

As this issue relates to an unsupported platform, we'd like to direct this to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests on supported platforms. Adding a new supported platform is a big effort in terms of verifying that everything works correctly, and is effectively a feature request all on its own.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
