### ISSUE TITLE
Allow xpack.security.authc.token.enabled: false with tls disabled

### ISSUE THREAD

**Issue by coolbry95** [elastic/elasticsearch#81817]
I am trying to use Istio with eck/elk. The issue I am having is that I cannot disable https for elk because it gives an exception.

Likely root cause: java.lang.IllegalStateException: OpenID Connect Realm requires that the token service be enabled (xpack.security.authc.token.enabled)

This exception is raised when I turn the xpack.security.authc.token.enabled setting to true.
`bootstrap check failure [1] of [1]: HTTPS is required in order to use the API key service; please enable HTTPS using the [xpack.security.http.ssl.enabled] setting or disable the API key service using the [xpack.security.authc.api_key.enabled] setting`

Here are the two related issue/PR.
https://github.com/elastic/cloud-on-k8s/issues/3213
https://github.com/elastic/elasticsearch/pull/76801

I am not quite sure what the OIDC realm matters. Is elastic using OIDC internally for its tokens? I am using OIDC for SSO but the ssl is terminated by the Istio gateway for the callback from the OIDC provider.

Is it possible to turn off https and let Istio handle that part?

**Comment by KnechtionsCoding** [comment]
This is still relevant for others.

**Comment by ywangd** [comment]
Close this to in favour of #88541
