### ISSUE TITLE
Document that upgrades to 8.x must always go via 7.last

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#81862]
Upgrading to the next major version with a rolling restart requires upgrading to the last minor of the previous major first. However you could upgrade from 5.x to 6.x and from 6.x to 7.x via a full cluster restart without upgrading to 5.last (respectively 6.last) first.

For 8.x we will impose the same restriction on both upgrade paths: they must always go via 7.last. This will ensure that folks are notified about all deprecations and other changes before starting the major upgrade. The docs for full cluster restart upgrades need to be modified to account for this change in policy.

/cc @skearns64

Relatedly, the 8.0 upgrade docs speak about upgrading from "7.x" in various places where really we mean "7.last". We should fix them too.

Relates #81865

**Comment by debadair** [comment]
Fixed by: https://github.com/elastic/elasticsearch/pull/83489, https://github.com/elastic/stack-docs/pull/1976, https://github.com/elastic/kibana/pull/124744.
