### ISSUE TITLE
MVT API: meta-layer bounding box with 0 width or height seems malformed

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#81891]
**Elasticsearch version** (`bin/elasticsearch --version`):

8.0/1

**Description of the problem including expected versus actual behavior**:

When using the MVT-API, and setting `exact_bounds` to true, the meta-layer seems to have a malformed bounding-box geometry when the width or height of the bounds is 0.

Bounds with 0 width or height occurs often when the tile only contains a single point (or multiple points sharing the same longitude or latitude).

The geometry from the meta-layer cannot be parsed by a client-side library  @mapbox/vector-tile (used in MapLibre), leading us to think the geometry is malformed (?)

**Steps to reproduce**:

 1. Create index with point
 
```
PUT my-index-000001
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point"
      }
    }
  }
}

PUT my-index-000001/_doc/1
{
  "text": "Geopoint as an object",
  "location": { 
    "lat": 41.12,
    "lon": -71.34
  }
}
```
 2. Request a tile

```
POST my-index-000001/_mvt/location/0/0/0
{
  "exact_bounds": true
}
```
 -> the tile is produced, but the geometry from the `META` layer is not usable. Parsing with @mapbox/vector-tile (https://www.npmjs.com/package/@mapbox/vector-tile) causes failures.

It seems somewhere a command-id of `4` is inserted in the geometry-buffer-array. The only allowed commands are 1 (moveTo), 2 (lineTo), or 7 (closePath). (from https://github.com/mapbox/vector-tile-spec/tree/master/2.1)

cc @iverase

**Comment by iverase** [comment]
The problem is not that the geometry is malformed but that out geometry is empty and that is not allowed. This is a special case as the geometry is degenerated and for example in the case of the hits layer, such features are ignored.

For the meta layer is different because we want to always create the feature so what we should do when the geometry is degenerated? Shall we add it in this case as a point geometry or as a degenerated polygon?


P.S.-in case a tile has not hits, the geometry of the meta layer is the actual tile.

**Comment by thomasneirynck** [comment]
thanks @iverase for the investigation

So just to be sure, a bounding box with 0 width or 0 height would `_not_` be allowed?

so e.g. a bounding box with zero-height e.g.  in geojson `{type: 'Polygon', coordiantes: [[[0,0],[10,0],[10,0],[0,0],[0,0]]]` - vs in mvt-paths - `moveTo(0,0) lineTo(10,0) lineTo(10,0) closePath()` would be considered invalid?

Do you have any recommendations on how we can address?

- pad the bounding box very slightly 
    - @nreese had mentioned this offline as a possibility
    - e.g. with 1 pixel in tile-space
    - imho - this is elegant because clients can handle these 0-width/height edge-cases transparently. 
- use the entire tile as the bounding-box, even when `exact_bounds: false`
    - drawback is that indicating data-extent is no longer accurate (e.g. Kibana Maps draws a dotted outline where the data is)
- use a geometry of a different type
    - e.g. a point for a single point, or a line for a 0-width/height bounding-box
    - this could be considered a breaking change
- remove the geometry altogether
    - add the {x,y,z} tile-coordinate to the properties of the meta-layer as a new property
    - if the geometry is absent, then the client can handle this on its own, based on the properties containing the `{x,y,z}`
    - this could be considered a breaking change
- ...   

cc @nreese

**Comment by iverase** [comment]
The one that makes sense to me is to create a different geometry type depending on the height-width. I don't think it is a breaking change in the sense that only affects layers with invalid geometries.

**Comment by thomasneirynck** [comment]
@iverase thx for the suggestion https://github.com/elastic/elasticsearch/issues/81891#issuecomment-997963047

on 2nd thought, I'd have some reservations of using either a point, line, or polygon interchangeably as the meta#geometry.

- clients will need to handle each geometry-type separately. (for querying, tooltip-popups, symbolization (since points need to be styled significantly differently than shapes, ...). It's more conservative from a client-perspective to just return a bounding-box always.
- the geometry of the meta-feature is the extent of the data. While I can see how we could motivate that a point-geometry indicates an "extent of a single point", that does not really go for line-geometries. e.g. multiple points on the same latitude do not have a data-extent of a line-string. That would seem "off" to me.
- envelope/bounding box functions generally work transparently, regardless of the input-geometry. e.g. `ST_Envelope` will always return a bounds, even on a single point. It's ok to have them be 0 width/height.
- The return would not equivalent to the response of the `geo_bounding` ES-aggregation on a single point (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geobounds-aggregation.html), which _does_ return a 0-width/height bounding box
