### ISSUE TITLE
[CI] Gradle: Accessing unreadable inputs or outputs has been deprecated.

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#81919]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ckx5wz5nnw6xo

**Repro line**:

There isn't one, but the task it failed on was `:qa:full-cluster-restart:v8.0.0#upgradedClusterTest`

**Reproduces locally?**:

No (using `./gradlew :qa:full-cluster-restart:v8.0.0#bwcTest`)

**Applicable branches**:

`master`

**Failure history**:

Hard to search for, but I suspect it's related to the recent upgrade to Gradle 7.3.2.

**Failure excerpt**:

```
00:21:23 > Task :qa:full-cluster-restart:v8.0.0#upgradedClusterTest
00:21:23 Cannot access input property 'clusters.v8.0.0$0.nodes.$0.distributionFiles' of task ':qa:full-cluster-restart:v8.0.0#upgradedClusterTest' (see --info log for details). Accessing unreadable inputs or outputs has been deprecated. This will fail with an error in Gradle 8.0. Declare the task as untracked by using Task.doNotTrackState(). Consult the upgrading guide for further information: https://docs.gradle.org/7.3.2/userguide/upgrading_version_7.html#declare_unreadable_input_output
```

**Comment by breskeby** [comment]
It's not exactly clear to me what happened here. I keep an eye on this

**Comment by mark-vieira** [comment]
There have been no instances of this in over a month so I'm closing this issue.
