### ISSUE TITLE
Version 6.8.22 not stdout the logs

### ISSUE THREAD

**Issue by uvaisibrahim** [elastic/elasticsearch#81920]
**Elasticsearch version** (`6.8.22`):

**JVM version** (`openjdk 15.0.1 2020-10-20`):

**OS version** (`Linux elasticsearch-master-0 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`):

**Description of the problem including expected versus actual behavior**: Not getting logs for containers (`docker logs <container_id>` -f) after sometime the containers started running. Initially getting few logs and then it just stops after upgrading to `6.8.22`.

**Comment by mark-vieira** [comment]
Do you mind elaborating here? You mention upgrading. So are you upgrading an existing node to 6.8.22 via docker? Can you share the logs you _are_ getting?

**Comment by mark-vieira** [comment]
Closing this issue as Elasticsearch 6.8.x is end of life.
