### ISSUE TITLE
Cluster Update Settings timeout shouldn't be a 503

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#8193]
Our standard procedure for doing a full cluster restart is to disable shard allocation, restart, wait for all nodes to come up, and then reenable allocation.

Unfortunately with many shards and many nodes (3 masters, 42 data nodes, and 8800 primaries and replicas) the cluster update to enable allocation can timeout.

```
curl --silent -XPUT  "http://esm1.blah.wordpress.com:9200/_cluster/settings" -d '{ "persistent" : { "cluster.routing.allocation.enable" : "all" } }'
```

```
{"error":"ProcessClusterEventTimeoutException[failed to process cluster event (cluster_update_settings) within 30s]","status":503}
```

When I got this error I assumed it meant the setting was not applied. However, it looks like the master just keeps retrying to set it because eventually the nodes did start allocating shards. The 503 error makes it feel like something is broken when it is not actually.

This is running ES 1.3.4.

**Comment by pickypg** [comment]
I have observed this on a cluster that was unresponsive due to a long pending tasks list during a large recovery and the setting never appears to "take" later.

**Comment by s1monw** [comment]
@gibrown going back to the original issue would you expect a `408` instead a `503`?

**Comment by gibrown** [comment]
@s1monw sorry for the slow response, I broke my GH notifications. :)

408 maybe makes sense if I can resend the request and will eventually get a 200.

Could also be a 202 Accepted response. Ideally I shouldn't have to do anything more for the request to complete processing. I guess there are cases where you want to know that it has completed though. Maybe if it has actually completed there should be a 200 response, and if it doesn't complete in a few seconds, then return 202 and the client can choose to send again and wait for a 200 if it cares?

For this particular use case I don't care. I go into a polling loop after enabling allocation and wait for the cluster to be green.

**Comment by bleskes** [comment]
The 4xx region indicates client side errors, so I don't feel 408 describes the situation correctly, despite of the timeout name. +1 to 202 (accepted for processing but not completed)

**Comment by nik9000** [comment]
> +1 to 202 (accepted for processing but not completed)

@bleskes does this still feel right to you? It feels a little easy to mistake for a 200 so it'd have to be super well documented and folks that have automation to do restarts will need to be super careful with 202. Also, if they get a 202, what can they use to check for when the setting is fully applied? I suppose we have the task management API which feels like a decent fit for this, but I dunno.

**Comment by bleskes** [comment]
>  It feels a little easy to mistake for a 200 

I still think that 202 is technically correct but it is indeed very subtle. I don't mind much leaving as is or changing.

> Also, if they get a 202, what can they use to check for when the setting is fully applied? 

Get the current settings from the master and see it has been applied. 

I suggest picking this up in fix it friday and see where the group tends to go. I'm fine either way.

**Comment by nik9000** [comment]
> I suggest picking this up in fix it friday and see where the group tends to go. I'm fine either way.

A bunch of us talked about this and we're all pretty sure a 202 is going to cause more unhappiness than a 503. While **technically** correct, a 202 is very likely to confuse people who'll just check for a 2xx code and then assume that the request was successful. It just feels like a huge trap.

503 is technically wrong too, because at some point the change request will probably be process. But I think it is less dangerous than the 202. Especially because if you shut down the master this queue is thrown out and the updates won't be processed. 

Given that these requests are idempotent, you should be able to retry them on a 503. That isn't great because a timeout here means the the queue is full and adding more things to the queue doesn't help that, but they should noops so at least they'll be fast.

I do think we someone should have a look at the error message and make sure it is clear and I'll leave the ticket open so someone will do this.

**Comment by gibrown** [comment]
That all makes sense. Ya I agree no great options. A better error message would help a lot.

**Comment by Bukhtawar** [comment]
Would it be better if before queuing the request up for master to process `TransportUpdateSettingsAction` validates if the request from previous execution has actually been acknowledged/succeeded and return a different response on subsequent retries.

**Comment by gibrown** [comment]
If the error message says that it is getting tried, then yes having some way to run it again and get status info would help. Generally when I get a 503 though I scratch my head and don't run the same command again. :)

**Comment by rjernst** [comment]
Coming back to this issue, we (core/infra) discussed the tradeoffs of the various options presented here. None standout as great, and given there was no consensus after many years, we don't think changing the status code in this case is worthwhile.
