### ISSUE TITLE
Need logging for ILM

### ISSUE THREAD

**Issue by zulfaqar7** [elastic/elasticsearch#81991]
The app must log every action it takes on the data - especially if it modifies/deletes data as can be the case with ILM.

This has been a requirement now for almost 3 years and needs to be implemented urgently.  Thank you.

**Comment by astefan** [comment]
@zulfaqar7 this is already possible. Please, see [this reply in a different github issue](https://github.com/elastic/elasticsearch/issues/40552#issuecomment-478071480).
Also, please check [this blog post](https://www.elastic.co/blog/troubleshooting-elasticsearch-ilm-common-issues-and-fixes) that goes in even more details regarding ILM logging and diagnose. If you believe this doesn't answer your needs, please reopen and provide more details about the missing bits.
