### ISSUE TITLE
How to analyze and find unused _mapping and _settings, and back up and remove them

### ISSUE THREAD

**Issue by hktalent** [elastic/elasticsearch#82084]
How to analyze and find unused _mapping and _settings, and back up and remove them
如何分析、发现没有使用过的_mapping、_settings，并进行备份、移除

http://127.0.0.1:9200/cve_index/_settings?pretty

http://127.0.0.1:9200/cve_index/_mapping?pretty

**Comment by albertzaharovits** [comment]
@hktalent Sorry I cannot understand what you are describing here. Please take more time to describe the issue.
Closing this as spam for now, please raise another issue that more clearly states the issue/problem you are observing.

**Comment by hktalent** [comment]
I want to find out which configurations are meaningless and delete them
@albertzaharovits
