### ISSUE TITLE
trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by KshitijaR16** [elastic/elasticsearch#82104]
Hi team,

Want to deploy elasticsearch with v7.16.2 on Ubuntu 16.04.6 LTS (Xenial Xerus).
Deployed openjdk11 on it but after running the script its giving error like trustAnchors parameter must be non-empty.
Also tried this step 
sudo rm /etc/ssl/certs/java/cacerts 
sudo update-ca-certificates -f
Still issue is there.

Can you share fix for the same.

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
