### ISSUE TITLE
Put mapping property update for _default_ type performs a complete replacement instead of a merge

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8215]
Consider the following example.    We are trying to add eager loading of field data to an existing property across all document types in an index:

https://gist.github.com/ppf2/2f49184d1c34a1c9b9b0

This works as expected for custom types.  If you look at the mapping defined for the custom_type type, there are 2 hostname fields (hostname and hostname2), if you update just hostname, it will successfully apply the change and do a merge such that hostname2 is retained and unchanged but hostname is updated.

```
PUT /test_mapping/custom_type/_mapping
{
    "properties": {
      "hostname": {
        "type": "string",
        "index": "not_analyzed",
        "doc_values": true,
        "fielddata": {
          "loading": "eager_global_ordinals"
        }
      }
    }
}
```

But if you execute the same update against `_default_` type, it performs a complete replace of the type. As a result, all other properties in the `_default_` type are deleted and it ends up with just the hostname property.  It doesn't just override the existing values within the property definition with the requested update but essentially create a new `_default_` type definition based on what is passed in via the put mapping API.  The doc description is a bit ambiguous "Any mapping specified in the create-index or put-mapping request _override values_ set in the `_default_` mapping.".   Is there a reason why we are not performing a merge?  The concern here is that this can cause unexpected loss in the default properties since it behaves differently from all the custom types.  So if the end users are going through all the types one by one and updating just 1 property, when they get to `_default_`, they can inadvertently cause the default type to drop everything else from its definition.

**Comment by jbrook** [comment]
While you make up your minds on this, do you think it would be possible to update the documentation for the PUT mapping API to add a warning that you can blow up your '_default_' mapping in this way? It seems like quite an enormous omission from the documentation. This behaviour must be unexpected for a lot of people and must lead to a lot of time wasted reindexing. Someone just replaced our default mapping with *nothing*...

**Comment by clintongormley** [comment]
@bleskes in the interim, (and given that most mapping changes are permanent) I'd opt for merging and being done with it.

**Comment by clintongormley** [comment]
@jbrook would you be up for sending a docs PR?

**Comment by clintongormley** [comment]
Revisiting this after a long time...  I don't think it makes sense to add complicated JSON-patch syntax for this.  If you want to merge with an existing `_default_` mapping, then retrieve it, make changes client side, and PUT it.

I'll document that default mappings are overwritten with the PUT mapping API, and close this issue.
