### ISSUE TITLE
Failed test: InternalTestClusterTests.testBeforeTest

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#82212]
**Build scan**: https://gradle-enterprise.elastic.co/s/cowwkyf3c24sw

**Repro line**:  ./gradlew ':test:framework:test' --tests "org.elasticsearch.test.test.InternalTestClusterTests.testBeforeTest" -Dtests.seed=527909747783BF7C -Dtests.locale=ar-EG -Dtests.timezone=Antarctica/Mawson -Dtests.timestamp=$(date +%S) --info

**Reproduces locally?**: yes, with the given seed

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Chicago&tests.container=org.elasticsearch.test.test.InternalTestClusterTests&tests.sortField=FAILED&tests.test=testBeforeTest&tests.unstableOnly=true

**Failure excerpt**:  
```
org.elasticsearch.test.test.InternalTestClusterTests > testBeforeTest FAILED	
    org.junit.ComparisonFailure: cluster_state.document_page_size expected:<[7036]9b> but was:<[35657]9b>	
        at __randomizedtesting.SeedInfo.seed([527909747783BF7C:832FDF705355B795]:0)	
        at org.junit.Assert.assertEquals(Assert.java:115)	
        at org.elasticsearch.test.test.InternalTestClusterTests.assertSettings(InternalTestClusterTests.java:151)	
        at org.elasticsearch.test.test.InternalTestClusterTests.testBeforeTest(InternalTestClusterTests.java:245)
```

**Comment by mark-vieira** [comment]
I've muted this on `master` with a72817c87bdd92f1357e478a751c424eca323e7f
