### ISSUE TITLE
Top Metrics should support multi-value fields like Top Hits does.

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#82281]
When operating on a field with multiple values, Top Metrics only returns one of the values, while Top Hits returns the whole list.  This came up while looking into adopting Top Metrics in Kibana (see https://github.com/elastic/kibana/issues/98733 and https://github.com/elastic/kibana/issues/102956).  The following example illustrates the problem:

```
POST abc/_doc
{
  "arr": ["x", "a", "y", "b", "z", "c"],
  "timestamp": "2020-02-02T00:00:00.000Z"
}

POST abc/_search
{
  "size": 0,
  "aggs": {
    "a": {
      "top_metrics": {
                "metrics": {"field": "arr.keyword"},
        "sort": {"timestamp": "desc"}
      }
    }
  }
}
```
The top metrics output looks like this:
```
  "aggregations": {
    "a": {
      "top": [
        {
          "sort": [
            "2020-02-02T00:00:00.000Z"
          ],
          "metrics": {
            "arr.keyword": "a"
          }
        }
      ]
    }
  }
```

While a similar top hits 
```
POST abc/_search
{
  "size": 0,
  "aggs": {
    "a": {
      "top_hits": {
        "sort": [
          {
            "timestamp": {
              "order": "desc"
            }
          }
        ],
        "_source": {
          "includes": [
            "arr"
          ]
        }
      }
    }
  }
}
```

Yields this result:
```
"aggregations": {
  "a": {
    "hits": {
      "total": {
        "value": 1,
        "relation": "eq"
      },
      "max_score": null,
      "hits": [
        {
          "_index": "abc",
          "_id": "VT_BK34B9KCu-YSkURdp",
          "_score": null,
          "_source": {
            "arr": [
              "x",
              "a",
              "y",
              "b",
              "z",
              "c"
            ]
          },
          "sort": [
            1580601600000
          ]
        }
      ]
    }
  }
}
```

Note that in this case, all of the values of `arr` are represented in the final result.  I've confirmed those results against the current main branch.

cc/ @flash1293 who discussed this with me on Slack.  My understanding from that conversation is that this is not currently a blocker for Kibana adopting Top Metrics.

**Comment by stephmilovic** [comment]
We have a use case for this on the Threat Hunting team for Host Risk Score/User Risk Score data.

We have data like this that we are querying in order to get the most recent host event from the index:

```
{
  "risk_stats" : {
    "rule_risks" : [
      {
        "rule_name" : "Cool rule",
        "rule_risk" : 99.0
      }
    ],
    "risk_score" : 80.541730474732
  },
  "@timestamp" : "2022-01-25T15:49:52.286Z",
  "host" : {
    "name" : "auditbeat-g62ll"
  },
  "ingest_timestamp" : "2022-01-25T15:56:34.578413941Z",
  "risk" : "High"
}
```

This is our query:
```
GET ml_host_risk_score_default/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "2022-01-28T07:00:00.000Z",
              "lte": "2022-01-29T06:30:00.000Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ]
    }
  },
  "aggregations": {
    "hosts": {
      "terms": {
        "size": 10,
        "field": "host.name",
        "order": {
          "latest_risk_hit[risk_stats.risk_score]": "desc"
        }
      },
      "aggs": {
        "latest_risk_hit": {
          "top_metrics": {
            "metrics": [
              { "field": "host.name" },
              { "field": "risk_stats.risk_score" },
              { "field": "@timestamp" },
              { "field": "risk.keyword" }
            ],
            "sort": {
              "@timestamp": "desc"
            }
          }
        }
      }
    },
  "size": 0
}
```

We also need to get ` { "field": "risk_stats.rule_risks" }`, but top_metrics does not support array values.

**Comment by flash1293** [comment]
@stephmilovic Not sure about performance, but you should be able to fetch the rule_risks with an additional top hit agg (as your not trying to sort by that field it should work fine).

**Comment by ddolcimascolo** [comment]
Hi guys,

Would be interested in this one too. We currently use `top_hits` to fetch array fields but that'd be nice to test `top_metrics` instead to be able to sort a parent `terms` zgg for instance.

Cheers,
David

**Comment by ppisljar** [comment]
if i understand the issue correctly, the problem with top hits is that it does not support sorting ?
one way to work around that would be to keep using top hits, then create a runtime field (on-the-fly) that reduces the multivalue field into a single value (average, sum, min, max, count of values. ...) and then use that field for sorting.

i am guessing es does a similar thing behind the scenes in top metrics agg (reduces the multivalue field using average) so it can sort on that value.

in lens this could happen completely transparent to the user.

**Comment by wchaparro** [comment]
closing as not planned, focus on ES|QL development.
