### ISSUE TITLE
Bootstrap check for process address space

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#82311]
According to https://www.usenix.org/sites/default/files/conference/protected-files/srecon19apac_slides_korchagin.pdf on aarch64 the process address space size is limited by default by the kernel to 2^39 = 512GiB, although some kernel builds permit more space. Elasticsearch uses `mmap()` extensively and larger nodes could easily need to map more than 512GiB of data into their address space. Today on Linux we have a bootstrap check to verify that `vm.max_map_count` is large enough for `mmap()` to be usable. I think we should have a similar bootstrap check about the size of the process address space.

**Comment by ChrisHegarty** [comment]
Closing for now, not experienced or seen in the wild. This issue can be reopened in the future, if needed.
