### ISSUE TITLE
Elasticsearch logs related to Zen discovery 

### ISSUE THREAD

**Issue by bhavya121999** [elastic/elasticsearch#82324]
**Elasticsearch version**:
7.13.4

**JVM version** :
11

**OS version**:
Ubuntu Server 20.04 

**Description of the problem including expected versus actual behavior**:
According to the [Breaking Changes in 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_removing_master_eligible_nodes_sometimes_requires_voting_exclusions), `discovery.zen.minimum_master_nodes` setting is permitted, but ignored, on `7.x` nodes.

I installed Elasticsearch 7.13.4 and started the cluster. In the elasticsearch logs, the following log was present 

`[2022-01-06T17:16:11,062][INFO ][o.e.d.DiscoveryModule    ] [node-1] using discovery type [zen] and seed hosts providers [settings]`

Since **Zen discovery settings** for cluster formation were deprecated in Elasticsearch version 7, so the elasticsearch log (mentioned above) creates confusion.

**Comment by DaveCTurner** [comment]
The fact that various settings (`discovery.zen.minimum_master_nodes` and friends) are deprecated doesn't imply that the `zen` discovery type itself is deprecated. There were some BwC issues in this area that meant we didn't address it in the 7.x series, but it was replaced by `multi-node` discovery in #80410. I don't think we intend to take any further action in this area so I'm closing this.
