### ISSUE TITLE
Elasticsearch output plugin should supprt authentication tokens

### ISSUE THREAD

**Issue by toddboom** [elastic/elasticsearch#82333]
Currently the Elasticsearch output plugin only supports basic HTTP authentication, though Elasticsearch itself supports authentication via bearer tokens in the `Authentication` header.

This appears to be supported by the underlying Elasticsearch library, it just needs to be added to the configuration and passed through.

**Comment by spinscale** [comment]
Is this referring to https://github.com/logstash-plugins/logstash-output-elasticsearch instead of Elasticsearch itself? If so, do you mind to open an issue in that repository, and if not, can you maybe clarify your problem in the context of Elasticsearch? Thanks a ton!

**Comment by toddboom** [comment]
@spinscale Sorry, I should have linked to the Elasticsearch docs. Here's the section of the guide:
https://www.elastic.co/guide/en/elasticsearch/reference/current/token-authentication-services.html

So, this is for writing directly to Elasticsearch. I've also already opened a PR to address it in case that helps clarify the feature:
https://github.com/influxdata/telegraf/pull/10399

**Comment by gwbrown** [comment]
@toddboom It looks like the "Elasticsearch output plugin" you're referring to is part of Telegraf - do you need support from Elasticsearch to implement auth tokens in that output? If so, could you clarify what you're looking for?

**Comment by toddboom** [comment]
@gwbrown ah, yes - i meant to open this on the telegraf repo and somehow, despite @spinscale's initial question, i failed to notice my mistake. sorry for the hassle, closing this out!
