### ISSUE TITLE
Enrich Processor Cache can be Corrupted by Processors that Mutate a Document (E.g. Rename)

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#82340]
Using the enrich processor in a pipeline with a rename or other processor that mutates the mutable maps backing an ingest document can corrupt the caches in the enrich processor.

An easy reproducer for this goes as follows:

have the following enrich policy:

```
PUT /_enrich/policy/device-enrich-policy
{
  "match": {
    "indices": "devices-idx",
    "match_field": "host.ip",
    "enrich_fields": [
      "device.name",
      "host.ip"
    ]
  }
}
```

add a document to the backing index as such:

```
POST devices-idx/_doc
{
  "host": {
    "ip": "10.151.80.8"
  },
  "device": {
    "name": "bla"
  }
}
```

... then execute the enrich policy.

... and finally execute following pipeline simulation:

``` 
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "enrich": {
          "policy_name": "device-enrich-policy",
          "field": "host.ip",
          "target_field": "_tmp.device",
        }
      },
      {
        "rename" : {
          "field" : "_tmp.device.device.name",
          "target_field" : "device.name",
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "host": {
          "ip": "10.151.80.8"
        }
      }
    }
  ]
}
```

this will show the expected result of having the device name added under `_tmp.device`.

Now adjust to a simpler pipeline:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "enrich": {
          "policy_name": "device-enrich-policy",
          "field": "host.ip",
          "target_field": "_tmp"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "host": {
          "ip": "10.151.80.8"
        }
      }
    }
  ]
}
```

which you would expect to show the same result because `device.name` would just be copied under `_tmp`.

What you do get instead is:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_doc",
        "_id" : "_id",
        "_source" : {
          "host" : {
            "ip" : "10.151.80.8"
          },
          "_tmp" : {
            "host" : {
              "ip" : "10.151.80.8"
            },
            "device" : { }
          }
        },
        "_ingest" : {
          "timestamp" : "2022-01-07T16:21:55.868673023Z"
        }
      }
    }
  ]
}
```

This is explained by the fact that the rename processor mutates the map that it works with. It removes and adds a field to a document. This map though is also referenced by: `org.elasticsearch.search.SearchHit#sourceAsMap` which is cached. 

-> rename processor mutates that map by mutating the ingest document from the first run -> cache is corrupted.

This was observed in a complicated to debug user issue where a pipeline would randomly fail during simulate like this for no apparent reason. Digging through the diags it turned out that the same enrich policy was used in another pipeline followed by the rename processor in the way described above, thus corrupting the policy's cache repeatedly.

**Comment by original-brownbear** [comment]
Seems like we had this issue before with copy_from as well:

https://github.com/elastic/elasticsearch/pull/69349

**Comment by nicpenning** [comment]
I am experiencing this issue as well. Talked it out with the community: https://elasticstack.slack.com/archives/CNTP6NLTZ/p1641779140142600

Would very much like to be able to get this fixed. :) Good find!!!

**Comment by martijnvg** [comment]
Good find @original-brownbear! This is a very sneaky bug. I think the enrich processor should make a deep copy of the _source before inserting it to the IngestDocument.

**Comment by original-brownbear** [comment]
> I think the enrich processor should make a deep copy of the _source before inserting it to the IngestDocument.

Sounds good. Additionally we could also look into making whatever we store in the cache immutable to prevent this kind of bug going forward (also looks like we could get away with storing just the search hit map and not the full search hit). Just some thoughts.

**Comment by martijnvg** [comment]
> Additionally we could also look into making whatever we store in the cache immutable to prevent this kind of bug going forward

+1, we should try to recursively wrap the _source in an immutable map when adding a cache entry.

> also looks like we could get away with storing just the search hit map and not the full search hit)

Yes, this makes sense. The value of cache should be List<Map<?, ?>, in case multiple hits were returned.
