### ISSUE TITLE
Compound words filter operator

### ISSUE THREAD

**Issue by MarcusSjolin** [elastic/elasticsearch#8235]
# Compound words
### Ranking and operator type issue

Given the keyword "shoerack" was misspelled into one word, then I would expect it to be split into:

```
"shoerack", "shoe" and "rack"
```

Using this compound word list:

```
["shoe", "rack"]
```

This all works fine. Testing the analyzer returns the above as expected. When I continue to perform the search after this the keywords appear to be searched this way, when I have the operator set on the multi_match query to be AND:

```
"shoerack" || "shoe" || "rack"
```

I would like these keywords to act as they are searched for this way:

```
"shoerack" || ("shoe" && "rack")
```

I would like the second argument to be ranked separately

I'm looking for a way to set up an operator in the filter itself to be AND, or maybe it isn't aware at all that the two or more keywords belong together.

I think this might be a feature request or enhancement, however it might be doable already, just that I have not found a solution to it.

Thanks
/Marcus

**Comment by vineelyalamarthy** [comment]
@clintongormley  How can I assign this bug to myself. This sounds interesting.

**Comment by clintongormley** [comment]
@vineelyalamarthy no need to assign it.  If you see a PR you're interested in working on, you can just go ahead and submit a PR. Although I'd advise discussing the approach in the issue before writing any code.

Not sure this is a good one to start on though, it's more complicated than it looks. I've marked it discuss because I don't think there is an easy way to do this.  Take a look at this example:

    PUT t
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "my_analyzer": {
              "tokenizer": "standard",
              "filter": [
                "lowercase",
                "compound_words"
              ]
            }
          },
          "filter": {
            "compound_words": {
              "type": "dictionary_decompounder",
              "word_list": [
                "shoe",
                "rack"
              ]
            }
          }
        }
      }
    }

    GET t/_analyze?analyzer=my_analyzer&text=My shoerack

returns

    {
       "tokens": [
          {
             "token": "my",
             "start_offset": 0,
             "end_offset": 2,
             "type": "<ALPHANUM>",
             "position": 1
          },
          {
             "token": "shoerack",
             "start_offset": 3,
             "end_offset": 11,
             "type": "<ALPHANUM>",
             "position": 2
          },
          {
             "token": "shoe",
             "start_offset": 3,
             "end_offset": 11,
             "type": "<ALPHANUM>",
             "position": 2
          },
          {
             "token": "rack",
             "start_offset": 3,
             "end_offset": 11,
             "type": "<ALPHANUM>",
             "position": 2
          }
       ]
    }


So `shoerack`, `shoe`, and `rack` are stacked in the same position.  This is the same thing that happens with synonyms (but if you're expanding synonyms at query time, you don't want to enforce matching ALL alternatives).

Queries like the `match` query are constructed by first analyzing the query string to produce a token stream (like the above) then generating low level `term` queries, wrapped in a `bool` query, for each token. There is no way to distinguish between stacked tokens that have been generated by a compound filter and tokens that have been generated by a synonym filter.

To make this change possible, the query generation process would need to understand the analysis chain... that's a big change!

**Comment by clintongormley** [comment]
As of 5.0, this now works correctly:

```
PUT t
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "compound_words"
          ]
        }
      },
      "filter": {
        "compound_words": {
          "type": "dictionary_decompounder",
          "word_list": [
            "shoe",
            "rack"
          ]
        }
      }
    }
  },
  "mappings": {
    "t": {
      "properties": {
        "text": {
          "type": "text",
          "analyzer": "my_analyzer"
        }
      }
    }
  }
}


GET t/_validate/query?explain
{
  "query": {
    "match": {
      "text": {
        "query": "my shoerack",
        "operator": "and"
      }
    }
  }
}
```

The explanation returned by the above is:

    +text:my +Synonym(text:rack text:shoe text:shoerack)

**Comment by gbhatia81** [comment]
I am not sure if it is still working as expected. As explained in _validate query, lucene is still trying to search for following
"my" AND ("rack" OR " shoe" OR "shoerack")
What was originally needed and is still a requirement in my case is a way to do following
"my" AND ("shoerack" OR ("shoe" AND "rack"))

This should be a common use case for others as well. When just "Shoerack" is queried , system is going and finding all results that even contain just shoe or just rack, which in my opinion, not good. There should be a way to force AND query for decompounded words.

**Comment by clintongormley** [comment]
@gbhatia81 the point of decompounding words is to look for some of the sub-words within a compound word.  In a language that uses compound words, you wouldn't have `shoerack` or `shoe rack`, just `shoerack`.

**Comment by kkraus** [comment]
@clintongormley I'm running into a similar issue (using 5.6.3) and it a very valid use-case for Nike. Users will type "airmax" or "air max" or "#BeTrue" or "be true" and we need the query to executed as shown above in the original thread, basically equating the terms. The synonym maintenance would be considerable so I'm wondering if there are any other recommended approaches to make this type of query possible? ("airmax" OR " air" AND "max")

**Comment by clintongormley** [comment]
@kkraus synonyms are the way to go here

**Comment by clintongormley** [comment]
Or possibly shingles
