### ISSUE TITLE
[CI] DateUtilsTests.testTimezoneIds

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#82356]
**Build scan**:
https://gradle-enterprise.elastic.co/s/vum5n2tryvv4o

**Repro line**:
./gradlew ':server:test' --tests "org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds" -Dtests.seed=8018930EAE4AFF0C -Dtests.locale=sr-Latn -Dtests.timezone=America/Indiana/Vincennes -Druntime.java=18

**Reproduces locally?**:
Yes.

**Applicable branches**:
7.17

**Failure history**:
Fails consistently with JDK 18 EA.

**Failure excerpt**:

```
org.elasticsearch.common.time.DateUtilsTests > testTimezoneIds FAILED
  java.lang.AssertionError: Pacific/Niue
    Expected: <-41400000>
       but: was <-39600000>
       at __randomizedtesting.SeedInfo.seed([8018930EAE4AFF0C:5CFDCE94E3E6B62A]:0)
       at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
       at org.junit.Assert.assertThat(Assert.java:956)
       at org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds(DateUtilsTests.java:59)
```

**Comment by ChrisHegarty** [comment]
The test compares the time zone offset for various timezones, at epoch, between java.time and Joda time. The determined offsets are expected to be equal. For the Pacific/Niue time zone this is not the case, hence the failure.

The test determines the offset at 1970 for:
* Joda, to be _41400000_ (11.5 hours).
* Java time (running on JDK 18 EA), to be _39600000_  (11 hrs)
Why the difference?

JDK 18 EA has updated time zone data, see https://bugs.openjdk.java.net/browse/JDK-8274407. This updated time zone data contains a correction to the Pacific/Niue time zone, which is propagated through the java.time API. Specifically, 
```
 - Niue: only observed -11:20 from 1952 through 1964, then went to 
     -11 instead of -11:30 
```

JDK 8274407 also identifies that 17.0.2 will contain the update time zone data, 2021c, so will likely cause the test failure (in addition to JDK 18 EA).

Since Joda has been removed in 8.x, this issue is not applicable to 8.x (since the specific test scenario has been removed).

**Comment by ChrisHegarty** [comment]
Should Joda be updated in 7.17? The test failure shows that the version of Joda is not using updated time zone data.

**Comment by mark-vieira** [comment]
This is now failing across multiple JDK vendors, I presume as latest patch releases include the new TZ data.

**Comment by mark-vieira** [comment]
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.common.time.DateUtilsTests&tests.sortField=FAILED&tests.test=testTimezoneIds&tests.unstableOnly=true

**Comment by ChrisHegarty** [comment]
Looking at a subset of the recent failures, the JDK versions are as follows: 17.0.2 (Oracle), 11.0.14(Zulu), 1.8.0_322(Zulu), 1.8.0_322 (Amazon Corretto), which aligns with the version of the JDK that has the updated TZ data (as can be seen in JDK issue [8274407](https://bugs.openjdk.java.net/browse/JDK-8274407)).

We should mute the test more broadly (than just for JDK 18). We then either update Joda or just leave the test scenario muted permanently.

**Comment by ChrisHegarty** [comment]
Changes in PR #82907 (and related backports), have muted the problematic test scenario on 7.17.x, 7.16.x, and 6.8.x branches. If I've missed a branch, please let the know.

**Comment by thecoop** [comment]
There's nothing more to do here, affected timezone is ignored - closing
