### ISSUE TITLE
Optimize sibling aggs together

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#82373]
If we have sibling aggregations running on the same field there are a few cases where we could collect them with a single aggregation and then split the results. For example, if you run the `min` and `max` aggregations as siblings on the same field you could collect a `stats` aggregation and then split out the results on read. Similarly, if there are two `percentiles` aggregations as siblings we could combine them into one for collection.

**Comment by iverase** [comment]
FWIW: I observed something similar when developing vector tiles. There are some cases where we are running a GeoGrid aggregation with a sibling GeoBounds aggregation. In some cases even the GeoGrid aggregations has a child GeoCentroid aggregation.

For each aggregation we are having to read and decode the doc value (which for geo_shape might be expensive) so optimising them together would be a big win.

**Comment by flash1293** [comment]
The most relevant case for the Lens use case is merging separate percentiles aggs on the same field.

e.g. 
{
   a: { percentiles: { field: x, values: [1,2,3] } },
   b: { percentiles: { field: x, values: [4,5,6] } },
}

and
{
   a: { percentiles: { field: x, values: [1,2,3,4,5,6] } }
 }
 

should have near-identical performance

**Comment by wchaparro** [comment]
we discussed this one as a team, adding to our roadmap as its something we believe we want to do, but we need to spend some time investigating a solution and coming up with a plan for this. removing the team-discuss.

**Comment by wchaparro** [comment]
Closing as not planned, focus is on ES|QL development.
