### ISSUE TITLE
Use filter by filter if top level query is a bool wrapping a match all

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#82384]
Right now filter aggregations run in "compatible" mode if the top level query is `bool: {filter: { match_all: {}}}}` - but this really just just `match_all` in disguise. We should just run in filter-by-filter mode here.

**Comment by jpountz** [comment]
I wonder if the new `Weight#count` API could help with this by checking if `Weight#count` returns `numDocs`? This would be the case for the example query you provided.

**Comment by nik9000** [comment]
Part of the tricky thing here is that building the `Weight` can be slow for some Queries so we don't want to do it unless we're sure it's fast.

**Comment by jpountz** [comment]
True. FWIW Lucene already handles such single-clause queries through rewrites and the above query would rewrite to a `new BoostQuery(new ConstantScoreQuery(new MatchAllDocsQuery()), 0)` so it should work to rewrite the query and then unwrap all layers of `BoostQuery` and `ConstantScoreQuery` before looking at the query.
