### ISSUE TITLE
[ML] Add latest search start and end time in datafeed stats

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#82405]
When a datafeed is running performing searches that scan a long time period (particularly in lookbacks)
it would be very useful to report where the search is in the stats API. For example, in the scenario where the
datafeed is going through an extended period without any data, it could seem like the job does nothing. But
if the user could see the search time progressing they would understand that the job is progressing fine.

**Comment by hendrikmuhs** [comment]
FWIW: In transform the field is called `last_search_time`. I am not sure you need a start _and_ end time, nevertheless :+1:. It is helpful to know if a job is progressing properly.
