### ISSUE TITLE
elasticsearch dockerfile 7.15 file permission

### ISSUE THREAD

**Issue by yxyx520** [elastic/elasticsearch#82460]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.15

**Description of the problem including expected versus actual behavior**:
[elasticsearch 7.15 dockerfile](https://github.com/elastic/dockerfiles/blob/7.15/elasticsearch/Dockerfile#L160)
```
    chown elasticsearch bin config config/jvm.options.d data logs plugins
```
When we use k8s to deploy es cluster, we will use post-start script to write config into `/usr/share/elasticsearch/config/roles.yml`, when we upgrade from 7.13 to 7.15, we get a permission deny.

**Provide logs (if relevant)**:

**Comment by pugnascotia** [comment]
@yxyx520 what UID are you using to update the file? The `root` and `elasticsearch` users can both update that file, e.g.

```
docker run -it --rm -u elasticsearch docker.elastic.co/elasticsearch/elasticsearch:7.15.0 bash -c 'echo hello >> config/roles.yml'
```

**Comment by pugnascotia** [comment]
Without more information it's hard to make progress here. I hope you don't mind but I'm going to close this issue for now, we can reopen if more information becomes available.
