### ISSUE TITLE
Optimize match_phrase query on constant keyword field to match_none if possible

### ISSUE THREAD

**Issue by flash1293** [elastic/elasticsearch#82515]
The `index_filter` option for the field caps API allows to exclude mappings of some indices from the response if the provided filter can be optimized to a match_none based on mapping data.

This works fine for the following case:

```
PUT existence_index_1
{
  "mappings": {
    "properties": {
      "filter_field": {
        "type": "constant_keyword",
        "value": "a"
      },
      "textfield1": {
        "type": "keyword"
      }
    }
  }
}

PUT existence_index_2
{
  "mappings": {
    "properties": {
      "filter_field": {
        "type": "constant_keyword",
        "value": "b"
      },
      "textfield2": {
        "type": "keyword"
      }
    }
  }
}

POST existence_index_*/_field_caps?fields=textfield*
{
  "index_filter": {
    "bool": {
      "filter": [{
        "term": { "filter_field": { "value": "b" } }
      }]
    }
  }
}
// works fine - it only returns textfield2
```

However when using a `match_phrase` query, it seems like the query can't be optimized correctly

```
POST existence_index_*/_field_caps?fields=textfield*
{
  "index_filter": {
    "bool": {
      "filter": [{
        "match_phrase": { "filter_field": "b" }
      }]
    }
  }
}
// returns both textfield1 and textfield2
```

Would it be possible to extend the existing optimization logic to cover this case? It's relevant for the Kibana use case as a lot of filters are built as `match_phrase` and we can't leverage the index filter for filtering down field lists in this case.

**Comment by flash1293** [comment]
cc @nik9000

**Comment by flash1293** [comment]
@jtibshirani @romseygeek would it be difficult to build this?

**Comment by romseygeek** [comment]
I think we should be able to detect when the a match_phrase is functionally equivalent to a term query (keyword analyzer, no slop) and rewrite accordingly.

**Comment by flash1293** [comment]
That's great, it would be pretty difficult to detect this and rewrite the query on the Kibana side.
