### ISSUE TITLE
The sum aggregation return 0 when there is no hit data, which is ambiguous

### ISSUE THREAD

**Issue by waitingF** [elastic/elasticsearch#82607]
**Elasticsearch version** (`bin/elasticsearch --version`):
all versions.
while my test version is lastest master with commit b1c01b12be4239b18fe47c54ff9c08774cfe8b7a.
Version: 8.1.0-SNAPSHOT, Build: default/tar/b1c01b12be4239b18fe47c54ff9c08774cfe8b7a/2022-01-14T01:44:38.298409391Z

**Plugins installed**: []
none

**JVM version** (`java -version`):
openjdk version "17" 2021-10-13 LTS

**OS version** (`uname -a` if on a Unix-like system):
Linux VM_216_34_centos 3.10.107-1 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
ES and Mysql behave inconsistently in the sum aggregate function. When there is no hit data, ES returns 0 while MySQL returns null.
The result 0 is ambiguous. 0 can mean the sum result is 0, or it can mean the hit result is empty.

**Steps to reproduce**:

 1. create mapping
```json
PUT test_sum
{
  "mappings": {
    "properties": {
      "keylong": {
        "type": "long"
      },
      "keydouble": {
        "type": "double"
      }
    }
  }
}
```
 2. add test data
```json
POST test_sum/_doc
{
  "keylong": 0,
  "keydouble": 0
}

POST test_sum/_doc
{
  "keylong": 1,
  "keydouble": 1
}

POST test_sum/_doc
{
  "keylong": -1,
  "keydouble": -1
}
```
 3. test query with sum aggregation
```json
GET test_sum/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "keylong": {
              "gte": 10
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "test-long": {
      "sum": {
        "field": "keylong"
      }
    },
    "test-double": {
      "sum": {
        "field": "keydouble"
      }
    }
  }
}
```
it will produce:
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "test-long" : {
      "value" : 0.0
    },
    "test-double" : {
      "value" : 0.0
    }
  }
}
```

4. test query with stats aggregatioin
```json
GET test_sum/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "keylong": {
              "gte": 10
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "test-long": {
      "stats": {
        "field": "keylong"
      }
    },
    "test-double": {
      "stats": {
        "field": "keydouble"
      }
    }
  }
}
```

it will produce:
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "test-long" : {
      "count" : 0,
      "min" : null,
      "max" : null,
      "avg" : null,
      "sum" : 0.0
    },
    "test-double" : {
      "count" : 0,
      "min" : null,
      "max" : null,
      "avg" : null,
      "sum" : 0.0
    }
  }
}
```

The reason that sum aggregation  produced 0 is:
In the SumAggregator, the member sums is initialized to 0. Init sums with infinity can fix this.

Can I make a pull request to fix this?

**Comment by imotov** [comment]
> Can I make a pull request to fix this?

I don't think it needs to be fixed. Mathematically speaking [Empty Sum](https://en.wikipedia.org/wiki/Empty_sum) is supposed to be 0 after all. So, I would argue SQL implementation is incorrect here. We discussed it a few times in the past and decided not to change it. See [this discussion](https://github.com/elastic/elasticsearch/issues/31887#issuecomment-404839429) for more information. If your use case calls for disambiguation, you can always runs stats instead of sum and check if count is 0, it shouldn't be a big performance hit unless you have a huge number of buckets.
