### ISSUE TITLE
External multicast discovery does not work for Logstash node clients

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#8260]
To repro:

Set external multicast discovery as described in http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#_external_multicast:

discovery:
  zen:
    ping:
      multicast:
        enabled: true
        ping:
          enabled: false
      unicast:
        hosts: ["small1.va.elasticsearch.com", "small2.va.elasticsearch.com"]

Attempt to connect using a Logstash 1.4.2 node client configured for multicast discovery.  This fails.

I have also tested using the perl stub Clint created here: https://github.com/elasticsearch/elasticsearch/issues/1532
Result of the mutlicast query are the same whether discovery.zen.ping.multicast.ping.enabled is true or false.

**Comment by clintongormley** [comment]
Multicast discovery has been removed
