### ISSUE TITLE
[Docs] Elasticsearch Cluster Settings Precedence No Longer Documented

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#82634]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.2

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

In the <7.15 docs, Elasticsearch cluster precedence was [documented](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/cluster-update-settings.html#cluster-update-settings-api-desc):

>The order of precedence for cluster settings is:
    1. transient cluster settings
    2. persistent cluster settings
    3. settings in the elasticsearch.yml configuration file.

In 7.15+ docs this is no longer documented: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/cluster-update-settings.html#_order_of_precedence)
- I checked 7.15, 7.16, 7.17, 8.0, master docs all of which are missing this information

**Comment by jrodewig** [comment]
Hi @BenB196,

Thanks for reaching out. The setting precedence is documented here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/settings.html#dynamic-cluster-setting, which is linked from the top of the page.

I removed the duplicated content as part of https://github.com/elastic/elasticsearch/pull/79579. Keeping these docs in a single place ensures they stay accurate and updated.

Let me know if that helps. Thanks!

**Comment by BenB196** [comment]
Hi @jrodewig, thanks for pointing out where these docs are. Looking into this further from my end, I think the issue actually lies with the document search site.

As where my confusion came in when searching for the term `precedence`, the new doc ranks far lower in the search than on 7.14.

7.14: [10th result in the search](https://www.elastic.co/search?q=precedence&size=n_20_n&filters%5B0%5D%5Bfield%5D=website_area&filters%5B0%5D%5Bvalues%5D%5B0%5D=documentation&filters%5B0%5D%5Btype%5D=all&filters%5B1%5D%5Bfield%5D=product_name&filters%5B1%5D%5Bvalues%5D%5B0%5D=Elasticsearch&filters%5B1%5D%5Btype%5D=all&filters%5B2%5D%5Bfield%5D=product_version&filters%5B2%5D%5Bvalues%5D%5B0%5D=7.14&filters%5B2%5D%5Btype%5D=all)

7.16: [18th result in the search](https://www.elastic.co/search?q=precedence&size=n_20_n&filters%5B0%5D%5Bfield%5D=website_area&filters%5B0%5D%5Bvalues%5D%5B0%5D=documentation&filters%5B0%5D%5Btype%5D=all&filters%5B1%5D%5Bfield%5D=product_name&filters%5B1%5D%5Bvalues%5D%5B0%5D=Elasticsearch&filters%5B1%5D%5Btype%5D=all&filters%5B2%5D%5Bfield%5D=product_version&filters%5B2%5D%5Bvalues%5D%5B0%5D=7.16&filters%5B2%5D%5Btype%5D=all)

And given that the search results use the docs title as the title, `Cluster update settings API` seemed like a far more likely place to find the information than just `Configuring Elasticsearch`.

Given the above, not really sure if this is really an "issue" with the actual docs, or more of an issue with the docs website.

**Comment by jrodewig** [comment]
> Hi @jrodewig, thanks for pointing out where these docs are. Looking into this further from my end, I think the issue actually lies with the document search site.

Thanks for pointing that out. We're currently working on a major overhaul of the docs site and the site search feature with the goal of improving these results.

> And given that the search results use the docs title as the title, `Cluster update settings API` seemed like a far more likely place to find the information than just `Configuring Elasticsearch`.

Thanks for this feedback. I agree that given the situation with site search, we should include this information on the Cluster update settings API page for better discoverability.

I've opened https://github.com/elastic/elasticsearch/pull/82738 to re-add those docs to the page. That implementation uses tagging and include statements so we can still keep the content in a single source file.

Thanks again @BenB196!
