### ISSUE TITLE
Contradicting note for dynamic field mapping  [Documentation bug]

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#82641]
7.16

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Go to dynamic mapping documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html 
 2. See the first important which says `
Dynamic field mappings are only added when a field contains a concrete value — not null or an empty array.`
 3. Now, go to null value documentation https://www.elastic.co/guide/en/elasticsearch/reference/7.13/null-value.html, which says in the beginning `A null value cannot be indexed or searched. When a field is set to null, (or an empty array or an array of null values) it is treated as though that field has no values.`
 4. Basically empty array value is not indexed by default as mentioned correctly in the null_value documentation but in the dynamic template documentation, I guess there is a typo when its mentioned dynamic field mapping is added on not null or an empty array, instead of the non-empty array. 
 

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
The dynamic mapping docs are correct, but I can see how you could misread it.  Dynamic field mappings are only added when a field contains a concrete value: we don't add one when the field contains `null` or an empty array.  Pinging the docs team to see if they want to clarify it a bit.
