### ISSUE TITLE
Improve migration guide for security enabled by default

### ISSUE THREAD

**Issue by bytebilly** [elastic/elasticsearch#82677]
Following up from https://github.com/elastic/elasticsearch/pull/82128#discussion_r786051557_

The migration guide doesn't fully explain how to enable security features in 7.x before migrating to 8.0, and users may be tempted to just disable them explicitly.

We should improve the wording to point to our guides or something along those lines.

**Comment by lockewritesdocs** [comment]
Closed via #82816
