### ISSUE TITLE
SearchableSnapshot: GKE Workload Identity and GCS repository plugin

### ISSUE THREAD

**Issue by barkbay** [elastic/elasticsearch#82702]
It's possible to use GKE Workload Identity to automatically setup the credentials for the GCS repository plugin _(instead of creating a JSON service account file)_.
It works fine as long as snapshots are created or restored "manually" (through the `_snapshot/` API).
It is however no more the case when the bucket must be read from the `SearchableSnapshot` code, for example in the context of a `frozen` or cold `tier`. In this case it fails with the following error:

```json
{
	"type": "server",
	"timestamp": "2022-01-17T16:09:49,963Z",
	"level": "WARN",
	"component": "o.e.r.g.GoogleCloudStorageService",
	"cluster.name": "elasticsearch-sample",
	"node.name": "elasticsearch-sample-es-cold-1",
	"message": "failed to load default project id",
	"cluster.uuid": "lKo5VXDGRGeIg6aQAIEZ5g",
	"node.id": "lC0hhssQRfW9fdow0zYZJg",
	"stacktrace": ["java.security.AccessControlException: access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")",
		"at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]",
		"...",
		"at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.readBlob(GoogleCloudStorageBlobContainer.java:63) [repository-gcs-7.16.1.jar:7.16.1]",
		"at org.elasticsearch.common.blobstore.support.FilterBlobContainer.readBlob(FilterBlobContainer.java:48) [elasticsearch-7.16.1.jar:7.16.1]",
		"at org.elasticsearch.xpack.searchablesnapshots.store.SearchableSnapshotDirectory$RateLimitingBlobContainer.readBlob(SearchableSnapshotDirectory.java:763) [searchable-snapshots-7.16.1.jar:7.16.1]"
	]
}
```

See the following ECK issue for more context: https://github.com/elastic/cloud-on-k8s/issues/5230

I would be happy to help/contribute but I'm not familiar with how the security manager is used in this part of the code.

Thanks

**Comment by tlrx** [comment]
@barkbay Thanks for reporting. Can you please post the complete stacktrace? It seems to be a different issue from the last stacktrace I can see in https://github.com/elastic/cloud-on-k8s/issues/5230#issuecomment-1013217716.

**Comment by barkbay** [comment]
> @barkbay Thanks for reporting. Can you please post the complete stacktrace? It seems to be a different issue from the last stacktrace I can see in [elastic/cloud-on-k8s#5230 (comment)](https://github.com/elastic/cloud-on-k8s/issues/5230#issuecomment-1013217716).

Both stacktraces are available [here](https://gist.githubusercontent.com/barkbay/6dc52962f4ea1a679409f124571b5256/raw/b702700466f6d43bda48ca6e331ed491ad456a58/elasticsearch-sample-es-frozen-0.ndjson).

I think the stacktrace [here](https://github.com/elastic/cloud-on-k8s/issues/5230#issuecomment-1013217716) is a side effect or a consequence of the one I mentioned in the first comment of this issue. Said differently my feeling is that the cold/frozen node is not able to initialize the GCS plugin (` ["java.security.AccessControlException: access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")"`) which leads to the `401` error later when there is an attempt to read the data from the repository.

**Comment by tlrx** [comment]
Thanks @barkbay, having the full stacktrace helps :) Yes it seems that we should run[ some code with privileges](https://github.com/elastic/elasticsearch/blob/7.16/plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageService.java#L215) but are not.
