### ISSUE TITLE
track_total_hits link in doc redirects to URI search

### ISSUE THREAD

**Issue by jenish-jain** [elastic/elasticsearch#82731]
**Elasticsearch version** (`bin/elasticsearch --version`):7.16

**Plugins installed**: [NA]

**JVM version** (`java -version`):NA

**OS version** (`uname -a` if on a Unix-like system):NA

**Description of the problem including expected versus actual behavior**: the link to track_total_hits in [documentation] (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-rank-feature-query.html) point to [URI search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html) instead of [Track total hits](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-your-data.html#track-total-hits) 

**Steps to reproduce**:

 1. open https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-rank-feature-query.html
 2. click on track_total_hits in this line `when the track_total_hits parameter`
 3. will redirect to wrong page

**Comment by jenish-jain** [comment]
let me know if it is ok for me to pick up this correction 😁

**Comment by jrodewig** [comment]
> let me know if it is ok for me to pick up this correction 

Hi @jenish-jain. Yes. Please feel free to open a PR. Thanks!

**Comment by jenish-jain** [comment]
https://github.com/elastic/elasticsearch/pull/82739

**Comment by jrodewig** [comment]
Closed by #82739
