### ISSUE TITLE
Performance degradation for new HitContext constructor when only pulling docvalues

### ISSUE THREAD

**Issue by faithzhou** [elastic/elasticsearch#82777]
**Elasticsearch version** (`bin/elasticsearch --version`): `7.14.2`

**Plugins installed**: []

**JVM version** (`java -version`): `openjdk version "16" 2021-03-16`

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:
In my production environment, I pull only docvalues from es cluster by setting `_source=false` and `stored_fields=_none_` in scroll query for SQL query computed in my own SQL query engine(like presto). In my scenario, the CPU is the performance bottleneck. 
In 7.14.2 es version, #65292 PR will cause each `HitContext`(one doc) to initialize the `FieldsIndexReader` called in `setSegmentAndDocument()` function at least once, and the FieldsIndexReader is not actually used, resulting in a `performance drop` of about `30%`(in my case) compared to 7.10.1 es version. The analysis results of async-profiler are shown in the following figure. 
7.14.2
![image](https://user-images.githubusercontent.com/7687269/150057399-865bb7cd-e564-4015-8171-a0b7f92fec4d.png)
7.10.1
![image](https://user-images.githubusercontent.com/7687269/150061134-10bdd7ab-6b87-451c-b991-1a6241054146.png)

**Steps to reproduce**:
In my environment, there is 25 es data nodes (32C64G,3TB disk), 3 es master node;  and there is 20  nodes(16C32G) in my SQL query engine(like presto).

But the problem can be reproduced by following steps. 

 1. create a 7.14.2 es cluster (can only one data node)
 2. create a index
 `PUT test_column
{
  "mappings" : {
      "_meta" : {
        "vers" : "v4"
      },
      "date_detection" : false,
      "numeric_detection" : false,
      "properties" : {
        "__TIMESTAMP__" : {
          "type" : "long"
        },
        "http_param" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          },
          "analyzer" : "keyword"
        },
        "request_id" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          },
          "analyzer" : "keyword"
        },
        "time" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "number_of_replicas" : "0",
        "number_of_shards" : "1"
    }
  }
}`
 3. insert 1 billion logs to the index test_column
 4. scroll search 
 `POST test_column/_search?scroll=1h&preference=_shards:0
{
    "size": 10000,
    "timeout": "55s",
    "query": {
      "match_all":{}
    },
    "_source": false,
    "stored_fields": "_none_",
    "docvalue_fields": [
        {
            "field": "http_param.raw"
        },
        {
            "field": "request_id.raw"
        },
        {
            "field": "time.raw"
        }
    ],
    "sort": [
        {
            "_doc": {
                "order": "asc"
            }
        }
    ]
}`
then scroll 
`POST _search/scroll?scroll=1min
{
    "scroll_id" : "xxx"
}`

**Provide logs (if relevant)**:

**Comment by faithzhou** [comment]
@jtibshirani

**Comment by jtibshirani** [comment]
Thank you @faithzhou for the detailed report. I understand your use case and how this could cause a significant performance drop. I'll think about how we could address it.

**Comment by faithzhou** [comment]
> Thank you @faithzhou for the detailed report. I understand your use case and how this could cause a significant performance drop. I'll think about how we could address it.

Thanks to @jtibshirani for the answer. Now, we need to upgrade our ES clusters to version 7.14 for some new features, but cannot upgrade due to this performance reason. So I would like to know when it will be fixed

**Comment by jtibshirani** [comment]
Hello again, we just fixed this in https://github.com/elastic/elasticsearch/pull/83693. It will be available in the next 7.17 bugfix release. We don't have performance tests that closely match your set-up, but based on the flame graphs you provided, I believe it should fix the regression.

**Comment by faithzhou** [comment]
> Hello again, we just fixed this in #83693. It will be available in the next 7.17 bugfix release. We don't have performance tests that closely match your set-up, but based on the flame graphs you provided, I believe it should fix the regression.

Thank you @jtibshirani , I'll merge it to my branch and test it again.
