### ISSUE TITLE
doc_values: false Not effective？

### ISSUE THREAD

**Issue by S-Dragon0302** [elastic/elasticsearch#82776]
elasticsearch version:7.15.1
{ - 
  "contentindex_2m_20211109_1412": { - 
    "mappings": { - 
      "dynamic": "false",
      "_source": { - 
        "enabled": false
      },
      "properties": { - 
        "ContentHtml": { - 
          "type": "keyword",
          "doc_values": false
        }
      }
    }
  }
}
![image](https://user-images.githubusercontent.com/30819544/150058885-ff08d18a-f2e3-4600-841f-07bdbf861c68.png)
![image](https://user-images.githubusercontent.com/30819544/150058902-b168404d-94b8-41c0-9a30-c12afd0496e1.png)

**Comment by S-Dragon0302** [comment]
@elasticmachine
can you help me

**Comment by jtibshirani** [comment]
Hello @S-Dragon0302, even if none of your fields use doc values, you might still see disk usage from doc values. This is because Elasticsearch stores some metadata information (like sequence numbers) as doc values.

We just added a new API that shows disk usage information per field: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/indices-disk-usage.html. You might find it helpful to run on your index. I'd expect `ContentHtml` is not using any doc values, but some internal fields like `_seq_no` will be.

**Comment by S-Dragon0302** [comment]
@jtibshirani
thank you.

index: contentindex_2m_20211109_1412
uuid: r9VfuUL0RwWrhGtBMhF3kQ
type: keyword
doc_values: false
doc: 9999901
size: 142.33MB

index: contentindex_2m_20211109_1413
uuid: M-f0bYkQSw6-DLbmK4tPpA
type: keyword
doc: 9999901
size: 141.58MB

![image](https://user-images.githubusercontent.com/30819544/150276707-ec1132e8-532e-41ae-9927-1e3eaee8459a.png)
![image](https://user-images.githubusercontent.com/30819544/150276750-f64e235e-0ce2-408d-94de-e1d8a8bf7ee2.png)
![image](https://user-images.githubusercontent.com/30819544/150276917-631384ad-01dd-477b-b698-b1ef362eb06d.png)
Same data, doc_ Values: false does not save disk space. Why?

**Comment by jtibshirani** [comment]
@S-Dragon0302 that indeed seems surprising and doesn't match the behavior we verify in tests. I'd suggest using the disk usage API to dig into what's happening: `POST /<index>/_disk_usage?run_expensive_tasks=true`.

If you think you've found a bug in Elasticsearch, could you please provide a reproduction using steps like this?
* Create index with mappings with `doc_values: false`
* Index a few documents
* Show that doc values are still being created, for example through the disk usage API

**Comment by S-Dragon0302** [comment]
@jtibshirani
Can you provide your test cases? I want to compare them with yours.

My operation:
![image](https://user-images.githubusercontent.com/30819544/150459091-434a304f-b369-4508-89b3-82f6fd51e9c8.png)
![image](https://user-images.githubusercontent.com/30819544/150460673-c58db707-1313-4033-b125-10007b2089e4.png)
![image](https://user-images.githubusercontent.com/30819544/150460081-83a3a40c-d01e-4cd2-b7de-186d8985a9eb.png)

_disk_usage data:
{"_shards":{"total":1,"successful":1,"failed":0},"contentindex_2m_20211109_1510":{"store_size":"15.5mb","store_size_in_bytes":16276147,"all_fields":{"total":"15.5mb","total_in_bytes":16255760,"inverted_index":{"total":"5.5mb","total_in_bytes":5846851},"stored_fields":"6mb","stored_fields_in_bytes":6316703,"doc_values":"1.9mb","doc_values_in_bytes":2021492,"points":"1.9mb","points_in_bytes":2070714,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"fields":{"ContentHtml":{"total":"46.9kb","total_in_bytes":48053,"inverted_index":{"total":"46.9kb","total_in_bytes":48053},"stored_fields":"0b","stored_fields_in_bytes":0,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_field_names":{"total":"46.9kb","total_in_bytes":48039,"inverted_index":{"total":"46.9kb","total_in_bytes":48039},"stored_fields":"0b","stored_fields_in_bytes":0,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_id":{"total":"7.4mb","total_in_bytes":7806095,"inverted_index":{"total":"5.4mb","total_in_bytes":5750759},"stored_fields":"1.9mb","stored_fields_in_bytes":2055336,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_primary_term":{"total":"0b","total_in_bytes":0,"inverted_index":{"total":"0b","total_in_bytes":0},"stored_fields":"0b","stored_fields_in_bytes":0,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_seq_no":{"total":"3.9mb","total_in_bytes":4092206,"inverted_index":{"total":"0b","total_in_bytes":0},"stored_fields":"0b","stored_fields_in_bytes":0,"doc_values":"1.9mb","doc_values_in_bytes":2021492,"points":"1.9mb","points_in_bytes":2070714,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_source":{"total":"4mb","total_in_bytes":4261367,"inverted_index":{"total":"0b","total_in_bytes":0},"stored_fields":"4mb","stored_fields_in_bytes":4261367,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0},"_version":{"total":"0b","total_in_bytes":0,"inverted_index":{"total":"0b","total_in_bytes":0},"stored_fields":"0b","stored_fields_in_bytes":0,"doc_values":"0b","doc_values_in_bytes":0,"points":"0b","points_in_bytes":0,"norms":"0b","norms_in_bytes":0,"term_vectors":"0b","term_vectors_in_bytes":0}}}}

Is there a problem with the operation?
