### ISSUE TITLE
Terms query format/capabilities is inconsistent with term

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#82825]
Elasticsearch 7.16.3

Elasticsearch states that `terms` query is like `term` but operates on multiple terms. 
That is not entirely true. `terms` query is inconsistent with `term` query in the following

1. Unlike the `term` query, `terms` does not support `field_name: {value:[1,2,3]}` format 
2. Does not support `case_insensitive` option

While #1 is a nuisance that prevents us from seamlessly switching from searching on one term to searching on multiple in our software the #2 limits `terms` functionality and parity with `term`

**Comment by pquentin** [comment]
Thanks very much for your interest in Elasticsearch.

The `case_insensitive` feature missing is an enhancement request, and possibly a docs issue where we could be clearer that term/terms have more differences than explained in the summary. 

I don't understand what the `field_name: {value:[1,2,3]}` format is though, can you please share a sample query explaining what you mean? After I understand this, we can look into separating this issue into multiple issues as it's about multiple things (even though there's a common theme).

**Comment by roytmana** [comment]
Hello @pquentin 
I hope `case_insensitive` support will be added to `terms`
As far as format `term` support two formats short and verbose.
When queries are generated in code and need to switch between term and terms depending on number of tokens this disparity in features (`case_insensitive`) and formats is rather inconvenient 

This is verbose:
```
{
  "query": {
    "term": {
      "user.id": {
        "value": "kimchy",
        "boost": 1.0
      }
    }
  }
}
```

this is abbreviated:
```
{
  "query": {
    "term": {
      "user.id": "kimchy"
    }
  }
}
```
Terms only support what I call abbreviated:
```
{
  "query": {
    "terms": {
      "user.id": [ "kimchy", "elkbee" ],
      "boost": 1.0
    }
  }
}
```

**Comment by mslowiak** [comment]
Hi there @pquentin, @nik9000, @javanna 👋 
So this issue is to add `caseInsensitive` for `terms` as it is done for `term`, am I correct? 
If so, I would like to work on that

**Comment by javanna** [comment]
hi @mslowiak `caseInsensitive` is one of the issues, so addressing that would not close this issue, but it could still be a good starting point. Looking forward to your PR.

**Comment by sharmasiddarth** [comment]
@javanna I would like to start working on this issue, is this issue still open ?

**Comment by shreyash-solanke** [comment]
Is this issue still up for grabs?

**Comment by nik9000** [comment]
This issue is indeed up for grabs.

**Comment by shreyash-solanke** [comment]
I would like to work on this issue then. But I am new to contributing, so if anybody could be guide me in right direction, I will appreciate it.

For instance, as far as I have understood, caseInsensitive is not present in terms query. I can work on that. But I still haven't understood values parameter inconsistency. I find it is correct and there is no need for verbose part of it in terms query. What is the expected output here?

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md should get you started. When I'm playing with things by hand I tend to do use `./gradlew run` documented in https://github.com/elastic/elasticsearch/blob/main/TESTING.asciidoc#running-elasticsearch-from-a-checkout .

For `case_insensitive` I think you'd start with `TermsQueryBuilder`. That's how we parse the query out of the json and send the config for the query between nodes. If you look at how `TermQueryBuilder` (note the lack of `s` in the name) handes `caseInsensitive` you'd do something similar. You'll notice some blocks that look like this:
```
        if (in.getVersion().onOrAfter(Version.V_7_10_0)) {
            caseInsensitive = in.readBoolean();
        }
```
That's how we do wire compatibility - you'd need something similar, but with `Version.V_8_6_0`.

That things goal, in the end, is to call:
```
        if (caseInsensitive) {
            return mapper.termQueryCaseInsensitive(value, context);
        }
        return mapper.termQuery(value, context);
```

`TermsQueryBuilder` won't have the `if` statement and will call `mapper.termsQuery(value, context)`.  You'd have to *make* a `termsQueryCaseInsensitive`. I *think* you'd be safe defaulting that to something similar to the default implementation of `termsQuery`, just case insensitive.

If you are feeling adventurous you could specialize the implementation. I think something like how `TermBasedFieldType` does `termQueryCaseInsensitive` for `terms` could be a real speed up for anyone doing a lot of them. But just adding that one extra parameter and pluming it into the queries is likely enough work for one PR, much less fancy queries.

Testing is kind of it's own thing. Integration tests are written in yml - annoying, but useful. Look at `170_terms_query.yml`. Unit tests are all over the map. Have a look at how the rest of the case insensitive work was unit tested, I think.

**Comment by shreyash-solanke** [comment]
@nik9000 Thank you so much for the detailed explanation. I am working on this and trying to understand how things are implemented.

I have one doubt though. I am going through the current implementation of `TermQueryBuilder` and as mentioned by you, I see a call to `mapper.termQueryCaseInsensitive(value, context)` function inside `doToQuery` function. But in that function definition I see it is only throwing `QueryShardException`. 

```
public Query termQueryCaseInsensitive(Object value, @Nullable SearchExecutionContext context) {
        throw new QueryShardException(
            context,
                "[" + name + "] field which is of type [" + typeName() + "], does not support case insensitive term queries"
        );
    }
```
Why is that so? Where is the actual code which converts the output to lowercase?

**Comment by nik9000** [comment]
I'm not at a laptop at the moment but the short answer is subclasses. There
should be a few that override it.

**Comment by shreyash-solanke** [comment]
Sorry but I am unable to see any overridden method in any of the TermQueryBuilder related subclasses.

**Comment by javanna** [comment]
We discussed this with the team and we did not see reasons to support the same short syntax that term supports (`field_name: {value:[1,2,3]}`). Ideally you would have a single way to query in `term` too, and we are reluctant to introduce a second way to `terms`.

As for supporting `case_insensitive`, it is tracked in #71520.
