### ISSUE TITLE
Marvel is not proxy-friendly

### ISSUE THREAD

**Issue by simpsora** [elastic/elasticsearch#8283]
We have marvel deployed, and it works great.  We'd like to put it behind a proxy, so it's accessible the same way the rest of our monitoring infrastructure is.

However, Marvel isn't playing nice when you access it from a proxy.  It makes relative redirects, it makes HTTP requests to URLs outside its path, etc.

Examples:

Relative redirect:
```
$ curl  $MARVEL_HOST/_plugin/marvel/
  ...
  <meta http-equiv="refresh" content="1;url=kibana/index.html">
  <script type="text/javascript">
    window.location.href = "kibana/index.html"
  </script>
  ...
```

URLs outside the `/_plugin/marvel/` path:
```
GET /_nodes
GET /.marvel-2014.10.30/_aliases?ignore_missing=true
POST /.marvel-2014.10.30/_search
GET /.marvel-2014.10.27,.marvel-2014.10.28,.marvel-2014.10.29,.marvel-2014.10.30/_aliases?ignore_missing=true
GET /.marvel-kibana/appdata/marvelOpts
POST /.marvel-kibana/dashboard/_mget
```

This behavior makes it extremely difficult to put Marvel behind a proxy.  Is this something you'd consider as an improvement to Marvel?

Cheers

**Comment by bleskes** [comment]
@simpsora did you try the config test I suggested?

**Comment by simpsora** [comment]
Hi @bleskes, sorry for the radio silence.  We changed tactics on how we use marvel and are no longer using it with a proxy.  As such, I haven't had a chance to test out your suggestions.  However, I think the config you mention would have solved our problems.

**Comment by bleskes** [comment]
cool. I will close this then. If anything pops up, please re-open.

**Comment by simpsora** [comment]
Hi, just a followup on this, I was able to get Marvel working behind a proxy as you described above, by modifying the `elasticearch` config entry to include a path.

Perhaps when Marvel is updated to use Kibana 4 this will become easier.

Thanks for the tip!

**Comment by lsuryo** [comment]
can someone share their config ? im trying to proxy marvel 1.3 behind nginx and have the same issue
as described by simpsora... the elasticsearch value unchanged 

thanks
