### ISSUE TITLE
TSDB: Confusing error message for start/end dates

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#82832]
If I want to have a single TSDB index it would be reasonable for me to create an index with a broad time range that would look something like this:

```
PUT test
{
  "settings": {
    "index.mode": "time_series",
    "index.routing_path": "key",
    "index.time_series.start_time": "1970-01-01T00:00:00Z",
    "index.time_series.end_time": "9999-12-31T23:59:59.999Z"
  },
  "mappings": {
    "properties": {
      "key": {
        "type": "keyword",
        "time_series_dimension": true
      },
      "val": {
        "type": "double"
      }
    }
  }
}
```

This command is generating the error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "[index.mode=time_series] requires [index.time_series.start_time]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "[index.mode=time_series] requires [index.time_series.start_time]"
  },
  "status" : 400
}
```

Analysis: both `index.time_series.start_time` and `index.time_series.end_time` are there, they just happened to be equal to default values for this setting, which is cause the code think that the settings don't exist and report incorrect error message. Since we require this setting, I don't think we need a default for it.

**Comment by weizijun** [comment]
Let me take a look at this exception

**Comment by csoulios** [comment]
> Since we require this setting, I don't think we need a default for it.

@imotov what if we did not require `index.time_series.start_time` and `index.time_series.end_time` at all and use their default values when missing?

This would allow users to create a single TSDB index without explicitly setting those parameters (see example below). Would this cause any problems when a TSDB index is created in a data stream?
 
```
PUT test
{
  "settings": {
    "index.mode": "time_series",
    "index.routing_path": "key"
  },
  "mappings": {
    "properties": {
      "key": {
        "type": "keyword",
        "time_series_dimension": true
      },
      "val": {
        "type": "double"
      }
    }
  }
}
```

**Comment by weizijun** [comment]
I fixed the exception in https://github.com/elastic/elasticsearch/pull/82851, and push another PR to add more check: https://github.com/elastic/elasticsearch/pull/82847

**Comment by imotov** [comment]
> at all and use their default values when missing?

The more I am thinking about it the more I like that. This will simplify things and we probably don't care about the dates when we create a single index anyway, they are an important part of datastream story, but probably not here.
