### ISSUE TITLE
Clean up range bounds logic

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#82866]
We've made three recent changes to `RangeAggregationBuilder#innerBuild` to address various bugs around parsing, precision, and format for the range `to` and `from` bounds.  The resulting code is getting a little hairy.

Related issues:
 - https://github.com/elastic/elasticsearch/commit/1186e90d09cdda2c5914f612c426ab338df88f73
 - https://github.com/elastic/elasticsearch/commit/3550370c86cfdee60bb5ca991805437f0b87bccc
 - https://github.com/elastic/elasticsearch/commit/b968fcbca1083ee18b2b561e599b6a7d172f7560

**Comment by wchaparro** [comment]
Closing as not planned, focus is on ES|QL development
