### ISSUE TITLE
i need help, thanks

### ISSUE THREAD

**Issue by AccountGc** [elastic/elasticsearch#82916]
In the microservice scenario, the entity class is extracted into a public API for reference by other services:
<dependency>
    <groupId>com.test</groupId>
    <artifactId>api-system</artifactId>
</dependency>

public service, if not introduced，“spring-boot-starter-data-elasticsearch” ，public entity class required @Id etc. Annotation，Is there a solution please ?

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
