### ISSUE TITLE
[User Profiles] Audit/Telemetry APIs

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch#82927]
The existing User Profile APIs `/_security/profile/*` currently allow features like `@mentions` & user-setting storage. For this purpose, when listing all the profiles, the "disabled" ones are not returned in the search.

However, for Audit & Telemetry purposes, we may need to build some APIs to provide full visibility of this feature. For instance, we may want to know how many profiles are "disabled" vs. "active" vs. "inactive".

**Comment by ywangd** [comment]
This is implemented with https://github.com/elastic/elasticsearch/pull/90123
