### ISSUE TITLE
StackOverflow crash - large regex produced by Discover filter not limited by index.regex_max_length

### ISSUE THREAD

**Issue by gplechuck** [elastic/elasticsearch#82923]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: [repository-s3]

**JVM version** (`java -version`): 
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Debian Stretch 

**Description of the problem including expected versus actual behavior**:
It seems to be possible to crash several Elasticsearch nodes by providing a very large string when attempting to filter on a field value (StackOverflow related to regexp processing). When filtering on a field value, a query containing a 'suggestions' aggregation is sent to the cluster in the background before the filter is saved, in order to populate an autocomplete drop down. This aggregation includes a regex which is constructed from taking the large string and suffixing with a ".*" . The resulting regexp does not seem to respect the default index.max_regex_length limit of 1000 - the query is submitted causing an instant crash of nodes. 

`Caused by: java.lang.StackOverflowError
    at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1209) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]`

This might seem like an unlikely scenario, but we have seen end users of Kibana trigger this bug several times (accidentally pasting copied output from a data table visualization into the 'value' field when filtering further for example)

**Steps to reproduce**:

 1. Browse an index in the Kibana Discover pane
 2. Click 'Add Filter'
 3. In 'Edit Filter' - select a field, choose 'is' , paste a large string into the value box 
 
 For a test I pasted 50k chars - I haven't done extensive testing to find where the crashing occurs.

**Provide logs (if relevant)**:
Full crash logs (fatal-error.log) attached.
[fatal-error.log](https://github.com/elastic/elasticsearch/files/7923522/fatal-error.log)

Example suggestions aggregation containing offending regex attached.
[suggestions-query.txt](https://github.com/elastic/elasticsearch/files/7923531/suggestions-query.txt)

Unfortunately, disabling expensive queries is not an option for us as we have users which depend on regex and script query functionality. If you have any suggestions on how to best prevent this issue from re-occurring, that would be great. 

Any questions, shout.

Cheers

**Comment by nik9000** [comment]
I'm not a fan of the regex ctor being recursive. But it is..... Our standard defense against stuff like this is `index.max_regex_length`. We just need to invoke it here.

**Comment by nik9000** [comment]
I had a look at this. Right now we build the `Regexp` when we're parsing the request. But the setting is most naturally available on the data node when we're building the query. I think that's not too bad.

**Comment by dblock** [comment]
We tracked down what looks like this exact problem in OpenSearch, here's a fix that enforces the limit: https://github.com/opensearch-project/OpenSearch/pull/2810.

**Comment by nik9000** [comment]
Thanks for the ping! @ywelsh I think you have a fix for this open.

**Comment by dblock** [comment]
I found https://github.com/elastic/elasticsearch/pull/84624 just now but that doesn’t fix the problem, it wraps the error to avoid the node crash
