### ISSUE TITLE
Where is the official demo data of elasticsearch in 7.16 ？

### ISSUE THREAD

**Issue by Mengbuxiu** [elastic/elasticsearch#82921]
**Build scan**:

**Repro line**:

**Reproduces locally?**:

**Applicable branches**:

**Failure history**:

**Failure excerpt**:

**Comment by DJRickyB** [comment]
Hi,

For general questions please ask in our forums over at https://discuss.elastic.co/. We use issues here for things like bug reports or enhancement requests
