### ISSUE TITLE
Packaging: Confusing configuration override functionality with RPM

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#8294]
When installing via the RPM we add a property file to `/etc/sysconfig`. The configuration in this file overrides the `elasticsearch.yml` file (namely the data dir, work dir, and log dir). This is not clear in the documentation. We should do one of the following:
- Remove the data dir, log dir and work dir options from this file
- Make the config in elasticsearch.yml override this config
- Make the documentation clearer on this

**Comment by clintongormley** [comment]
These docs have been updated
