### ISSUE TITLE
Confusing documentation about dynamic types

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#82965]
In [this section](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-mapping-type) it says (emphasis mine):

> The match_mapping_type is the data type detected by the JSON parser. Because JSON doesn’t distinguish a long from an integer or a double from a float, it always chooses the wider data type such as **long** for integers and **double** for floating-point numbers.

Later on it says in the table (emphasis mine):

| JSON data type  | `"dynamic":"true"` | `"dynamic":"runtime"` |
| ------------- | ------------- | ------------- |
| `double`  | **`float`**  | `double` |
| `integer`  | **`long`**  | `long` |

This two parts of documentation are contradicting. In the table it is picked `float` and not `double` for floating point numbers. For integers, documentation matches.

**Comment by javanna** [comment]
Thanks for bringing this up, I can see how this is confusing to read. In fact, with dynamic mappings we will always choose the wider data type with the exception of `float`. The reason for this is that `float` is much more space efficient than double and is deemed to be enough in most cases. The discrepancy between dynamic:true and dynamic:runtime is due to the fact that runtime fields have no support for `type:float` hence we use `double` in that case. 

I think that we should rephrase the docs to clarify this aspect.

**Comment by mitar** [comment]
If this is so and is not just documentation issue, but `float` is really picked, then this is a bigger problem because I cannot define the following dynamic mapping:

```
		"dynamic_templates": [
			{
				"to_double": {
					"match_mapping_type": "float",
					"mapping": {
						"type": "double"
					}
				}
			}
		],
```

It says that `float` is not one of allowed `match_mapping_type`. Then how can I force `double` if `float` is really the default?

**Comment by javanna** [comment]
This is indeed tricky. `match_mapping_type` refers to the json data type, which is `double` and not `float`. If you don't specify the mapping for a `double` field in the json (really any floating point number), it becomes a `float` by default in the mappings. With your mapping specified above though it should become a `double`. I can see how this is counter-intuitive. Have you tried that?

**Comment by mitar** [comment]
> `match_mapping_type` refers to the json data type

But why can I then specify `long`? `long` is not a JSON data type. This works:

```
		"dynamic_templates": [
			{
				"to_double": {
					"match_mapping_type": "long",
					"mapping": {
						"type": "double"
					}
				}
			}
		],
```

Specifying `integer` does not.

**Comment by javanna** [comment]
@mitar this looks like yet another problem you found in that table. Under JSON data type in the table we should have `long` in place of `integer`.

**Comment by mitar** [comment]
But JSON has only floating numbers of arbitrary precision. How does parser decide if something is `long` or `double`?

**Comment by javanna** [comment]
@mitar the parsing logic for dynamic fields is here if you'd like to look at the code: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/mapper/DynamicFieldsBuilder.java#L114 . In short, any parsed floating point number is considered a double json data type, while any parsed integer number is considered a long. I hope this clarifies things.

**Comment by mitar** [comment]
Thanks.
