### ISSUE TITLE
Provide explanation of 'unassigned' shard state

### ISSUE THREAD

**Issue by kretes** [elastic/elasticsearch#8296]
As stated in http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/states.html shard may be unassigned for variuos reasons. One of them is that it is still pending to be assigned, but another is that index requires more replicas than cluster currently can provide. There are many more, I guess.
It would be good if some explanation would be provided in the response.

Rationale after that is that when cluster starts/node restarts/things happen - it is hard to find out on your own what is the reason behing shard being unassigned

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/11653
