### ISSUE TITLE
Add extra filters to field caps

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#82966]
A number of clients of field caps want to exclude or filter down to a specific subset of fields that are defined by mapping parameters.  For example, Kibana Discover presents users with a list of fields that excludes multifields; ML dataframes and QL want to filter out nested fields; TSDB wants to load only fields marked as dimensions.  We have various heuristics to guide clients on how to identify these type of fields, but it would be a lot simpler in many cases to identify them within ES itself and filter them out on the server side.  It would also reduce the number of bytes sent over the wire.

Looking through internal usages I can see four filters that we could add to start with: `metadata`, `multifield`, `nested`, `dimension`.  Each could be prefixed with a `+` or `-` to indicate an inclusive or exclusive filter.

Adding filters to data nodes should be simple.  These four filters can also be implemented in a best-effort fashion on a co-ordinating node for mixed-cluster or cross-cluster cases where the data node does not have the filter implemented.

**Comment by thomasneirynck** [comment]
Related: it would be great if we could filter by type as well: https://github.com/elastic/elasticsearch/issues/72174

As @romseygeek, searching for fields based on their capabilities, is really useful to bootstrap a UX

Other examples of more advanced filtering: the ability to determine whether fields are sparsely populated or not: https://github.com/elastic/kibana/issues/100779 (this proposes to add this logic into Kibana, but Elasticsearch could support this as well for more broader applicability)

I'm wondering if this could be extended even further to include filtering based on partial matches for the field-name, aka "auto-suggest": https://github.com/elastic/elasticsearch/issues/74816

**Comment by romseygeek** [comment]
We can already match on partial field names in field caps. I think the reason that we were discussion a separate 'field completion' API was that field caps are built entirely from mappings, and so can't introspect into flattened fields.
