### ISSUE TITLE
Support for pattern_replace filter in keyword normalizers

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#83005]
My use case is that I have a field which is storing IDs. Those IDs might be coming from different sources, but in general there might be noise. For example, there might be ID `000123` and I would like to configure normalizer which trims all prefix zeros:

```
"zeros_prefix_trim": {
  "type": "pattern_replace",
  "pattern": "^0+",
  "replacement": "",
  "all": false
}
```

But it seems this is not allowed. Not sure why, because `trim` filter itself works (after #27310, which has not been documented, BTW).

**Comment by mitar** [comment]
But `char_filter` works. The only issue with that is that it is hard to control interaction with filters. For example, I can have:

```
"normalizer": {
	"id_normalizer": {
		"type": "custom",
		"char_filter": ["zeros_prefix_trim"]
		"filter": ["trim"]
	}
},
"char_filter": {
	"zeros_prefix_trim": {
		"type": "pattern_replace",
		"pattern": "^[0\\s]+",
		"replacement": "",
	}
}
```

But I had to use pattern `"^[0\\s]+"` and not `"^0+"` because I cannot control that first `trim` filter is applied, and then `zeros_prefix_trim`.

**Comment by Kiriakos1998** [comment]
Hello, @javanna @nik9000. Can i pick it up? 
The overall goal is to support pattern_replace for any valid pattern correct?
