### ISSUE TITLE
Remove all fields other than a defined list

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#83010]
This came up in a forum thread - https://discuss.elastic.co/t/reindex-identify-fields-to-remove-with-a-regular-expression/295275

The idea being that if you want to remove a bunch of fields, that you may not necessarily know the names of (or don't care), having  a config option for the [remove processor](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/remove-processor.html) that you could simply define a set of fields to keep, thereyby removing everything else, would be a simple solution.

**Comment by harshlancer** [comment]
If this issue is beginner-friendly I would like to start my open source journey with this issue.
Please tell me if I can start working on this...

**Comment by danhermann** [comment]
@harshlancer, you are welcome to start working on this if you would like. I would suggest adding a new option to the existing remove processor rather than creating a whole new processor to perform this function.

**Comment by harshlancer** [comment]
Sorry I don't think this issue is for a complete newbie....

**Comment by zembrzuski** [comment]
Hi @danhermann 
Since @harshlancer is not going to work on this issue, I will give it a try on this issue.

**Comment by zembrzuski** [comment]
Just to keep you guys posted: I am already working on the implementation of this issue, and I expect to raise a PR in 2 or 3 days.
Tks!

**Comment by danhermann** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/83665

**Comment by zez3** [comment]
Wouldn't make more sense to have a correct parser whatever Integration in the first place and not waste those computational resources on ingesting first wrong and delete after?
