### ISSUE TITLE
Discrepancy between multisearch and multisearch template response formats.

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch#83029]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16, 8.0, 8.1.

**Description of the problem including expected versus actual behavior**:

The format of the multisearch response and the multisearch template response are different. The former adds a `status` field in every response item while the latter does not. I guess this is a discrepancy that was introduced when one was updated and not the other.

Reported by a user of the Java API Client: https://github.com/elastic/elasticsearch-java/issues/110, workaround added to the API specification: https://github.com/elastic/elasticsearch-specification/pull/1320

`MultiSearchResponse`:

https://github.com/elastic/elasticsearch/blob/533f6e0eb8fe84c4fcb3b8de58ca125af8f0190d/server/src/main/java/org/elasticsearch/action/search/MultiSearchResponse.java#L153-L171

`MultiSearchTemplateResponse`:

https://github.com/elastic/elasticsearch/blob/533f6e0eb8fe84c4fcb3b8de58ca125af8f0190d/modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/MultiSearchTemplateResponse.java#L144-L160

**Comment by javanna** [comment]
Good catch, `status` was added to multi search responses with #18586 and should have been added to msearch template too. Would be nice to share some code between the two if possible.

**Comment by AbeleMM** [comment]
@javanna Hey! Sorry for resurrecting the issue, but I wondered if help is still wanted for it. If so, I think I have a fix, so I would be happy to have my PR checked out.

**Comment by javanna** [comment]
Help is still wanted, please go ahead @AbeleMM !

**Comment by swallez** [comment]
Thanks @cbuescher! I've opened https://github.com/elastic/elasticsearch-specification/issues/1721 so that we update the API specification for 8.3
