### ISSUE TITLE
Capture IP of Client that Fails API Key Usage

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#83046]
# Feature

Currently when a request is made to an Elasticsearch cluster with an invalid API Key, the request is logged, but the IP of the client which made the request isn't. This makes it extremely hard to track down misconfigured/bad clients trying to access the cluster. It would be nice to have the client's IP address captured within the log so that the issue could more easily be investigated.

## Example Log:

```json
{
    "type": "server",
    "timestamp": "2022-01-25T00:00:00,000Z",
    "level": "WARN",
    "component": "o.e.x.s.a.ApiKeyAuthenticator",
    "cluster.name": "<snipped>",
    "node.name": "<snipped>",
    "message": "Authentication using apikey failed - unable to find apikey with id <snipped>",
    "cluster.uuid": "<snipped>",
    "node.id": "<snipped>"
}
```

**Comment by ywangd** [comment]
External client addresses are available in [audit logs](https://www.elastic.co/guide/en/elasticsearch/reference/current/enable-audit-logging.html). Is it an option for your use case?

**Comment by BenB196** [comment]
Hi @ywangd I've enabled audit logging on the cluster in question, but I think there is still an issue here.

Using the default `xpack.security.audit.logfile.events.include` settings, it doesn't appear to actually capture failures of type `Authentication using apikey failed - unable to find apikey with id <snipped>`.

I would expect to see an audit log with the field `elasticsearch.audit.apikey.id` populated with the value of the API Key which is resulting in the error `Authentication using apikey failed - unable to find apikey with id <snipped>`. However, instead there appears to be no audit logs at all with this API Key present besides the logs that existed before enabling auditing.

Just to be safe, I even just searched the `message` field for the API Key, and it returned no results.

I've confirmed that Filebeat is correctly collecting and indexing the new audit logs, so I'm assuming logs for this type of issue either aren't generated, or they don't properly contain the API Key which failed.

**Comment by ywangd** [comment]
@BenB196 Thanks for the extra information. You are right that audit logging is not issued in this case for the failed API key. I raised https://github.com/elastic/elasticsearch/issues/83304 for this issue. 

For the timebeing, the alternative is to search for any `anonymous_access_denied` audit entries. These should be logged for the failed API keys instead. They should have the client IP information, but unfortunately they do not contain the API key ID. So you'll have to correlate these audit entries with the server logs of (`unable to find apikey with id`) to get the full picture.

**Comment by ywangd** [comment]
I am closing this issue since it is superceded by #83304.
