### ISSUE TITLE
Search Template - conditional clauses not rendering correctly

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#8308]
Is the example of filtered query template [1] working? It seems to contain extra `</6>` string which seems as an issue to me. I am unable to test this example even after I remove this extra string.

[1] http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.3/search-template.html#_conditional_clauses

**Comment by clintongormley** [comment]
Closed by #11512

**Comment by lukas-vlcek** [comment]
@clintongormley correct, this issue was created before I opened more general PR. Closing...
