### ISSUE TITLE
some failures for ElasticsearchSqlClient api

### ISSUE THREAD

**Issue by fanchangjifen** [elastic/elasticsearch#83118]
version: 7.16.3
description: when i use java rest client try to query a sql or translate a sql to dsl , it get a error.  it caused may be by  response a null result and tips java.lang.UnsupportedOperationException
   at co.elastic.clients.json.JsonpDeserializer$2.deserialize(JsonpDeserializer.java:117)

**Comment by DJRickyB** [comment]
Hi! Please ask your question (with as much detail as possible) over at our forums, https://discuss.elastic.co/ so we can best assist you
