### ISSUE TITLE
Shards getting reshuffled across nodes during rolling restart.

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#8313]
There appears to be new behavior (introduced between 1.2.1 and 1.3.4) which causes shards to get juggled around between nodes when they get restarted. This of course makes restart take much longer.

We run some of our rolling restarts where we restart 4 nodes at a time to speed up the rolling restart. The recovery used to favor recovering shards from the local node. In this screenshot of disk space on different nodes (blue is live shards, and brown is other disk space used) the shards are getting randomly assigned across the nodes that were restarting.

![Shard Shuffling](https://i.cloudup.com/xafnWLKeR2.png)

Looking at the disk space on the nodes I see that each node has 75% more shards on disk than it should, which is exactly what you'd expect if ES is re-assigning all the shards randomly.

**Comment by clintongormley** [comment]
Closed by the delayed allocation feature added in 1.7 and improved in 2.0
