### ISSUE TITLE
option to use updateRewriteQuery in wildcard query

### ISSUE THREAD

**Issue by muzzlebeat** [elastic/elasticsearch#8320]
Hi,

For my search solution, i've implemented a custom highlighter and a custom aggregator. Since i need to support wildcard searches as well, each of them internally do a query rewrite if its a wildcard query. 
Instead, what i would like is if anyone does a wildcard query, the query should automatically update the searchContext with the rewritten query (updateRewriteQuery) which will then be accessible by both the modules.
Is this already implemented? if not, would this be taken up as a change in the coming updates?

Thanks
Neeraj Makam

**Comment by clintongormley** [comment]
@jpountz any thoughts on this?

**Comment by jpountz** [comment]
This is very internal to elasticsearch. I don't think we want to support this kind of functionnality for plugins.
