### ISSUE TITLE
Caching in custom aggregation

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#8322]
I am developing a custom metric aggregator using ES 1.3.4 similar to the Stats aggregator. The operation is a bit heavy and I want to leverage caching to improve performance when the same inputs are provided to the aggregation again. Obviously the metrics will change if documents in the shard/segment change. I've figured what I want to cache but I am not sure how to determine when to invalidate the cache. Is any API provided in the aggregation module that can be leveraged here? 

I was reading about Shard Query Cache <a href="http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/index-modules-shard-query-cache.html">here</a> and found <blockquote>Cached results are invalidated automatically whenever the shard refreshes, but only if the data in the shard has actually changed.</blockquote>

Can I implement something similar in my aggregation module too? Any pointers would be really helpful.

**Comment by jpountz** [comment]
Sorry that I missed the previous pings. We haven't had the need to use caches for "regular" aggregations and I don't want to make the framework more complicated.
