### ISSUE TITLE
[DOCS] ES Guide and ESS docs contain redundant snapshot docs

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#83223]
With elastic/elasticsearch#81870, Azure, GCS, and AWS S3 snapshot repositories no longer require a plugin in 8.0+. This removes the biggest UX difference between snapshot/restore on ESS and on-premise deployments. As a result, the ES guide and ESS docs now contain redundant docs.

This is particularly obvious in the snapshot repository docs:

|  Topic  |  ES guide  | ESS docs
| ------- | ----------|-----------|
| Register a snapshot repository | [Link](https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshots-register-repository.html) | [Link](https://www.elastic.co/guide/en/cloud/current/ec-custom-repository.html) |
| Azure snapshot repo | [Link](https://www.elastic.co/guide/en/elasticsearch/reference/master/repository-azure.html) | [Link](https://www.elastic.co/guide/en/cloud/current/ec-azure-snapshotting.html) |
| GCS snapshot repo  | [Link](https://www.elastic.co/guide/en/elasticsearch/reference/master/repository-gcs.html) | [Link](https://www.elastic.co/guide/en/cloud/current/ec-gcs-snapshotting.html) |
| AWS S3 snapshot repo  | [Link](https://www.elastic.co/guide/en/elasticsearch/reference/master/repository-s3.html) | [Link](https://www.elastic.co/guide/en/cloud/current/ec-aws-custom-repository.html) |

### Proposal

We should consider combining the duplicated docs and centrally hosting them in the ES guide. I personally find the ESS docs a little easier to follow so I'd try to include those procedurals if possible.

**Comment by jrodewig** [comment]
Tagging @elastic/cloud-writers for general awareness. No action requested at the moment. However, this will likely require some fun collaboration between teams.

**Comment by kilfoyle** [comment]
I'm happy to help with this.
