### ISSUE TITLE
Java rest-high-level-client support Pinned Query?

### ISSUE THREAD

**Issue by X-rapido** [elastic/elasticsearch#83238]
### Description

Hi
 elasticsearch-rest-high-level-client 7.16  support Pinned Query?

query-dsl-pinned-query
```
GET /_search
{
  "query": {
    "pinned": {
      "ids": [ "1", "4", "100" ],
      "organic": {
        "match": {
          "description": "iphone"
        }
      }
    }
  }
}
```

but i can't find in the `high-level-client` api，How can I support it?

**Comment by X-rapido** [comment]
???

**Comment by jbaiera** [comment]
The HLRC has been replaced with the new [Java client](https://github.com/elastic/elasticsearch-java). This sort of question should be opened there.
