### ISSUE TITLE
Update vulnerable dependencies

### ISSUE THREAD

**Issue by Chavjoh** [elastic/elasticsearch#83260]
### Description

Hello,

I see from Snyk that there are two vulnerable dependencies used in your last version (7.16.3 and also 8.0.0rc1):
- https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-1048058
- https://security.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518

You can find the available dependency updates here:
https://mvnrepository.com/artifact/org.elasticsearch.client/elasticsearch-rest-client/7.16.3

Could you please update those versions ? 
If I'm not mistaken, it's in `build-tools-internal/version.properties`:
```
httpclient        = 4.5.13
httpcore          = 4.4.15
httpasyncclient   = 4.1.5
commonslogging    = 1.2
commonscodec      = 1.15
```

Thank you in advance!

**Comment by jkakavas** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to security@elastic.co

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.
