### ISSUE TITLE
Add support for routing documents with custom timestamp formats for tsdb data streams

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#83272]
When ingesting documents data into a tsdb data streams then documents don't always get resolved to the most recent index. There is logic that parses the `@timestamp` field and based on the timestamp value resolves to a backing index with a start_time and end_time range that matches with the timestamp from that document.

The code that parse the timestamp currently can only handle parsing dates in the strict_date_optional_time and epoch_millis format (provided as string or long). This is kind of the default parse format in Elasticsearch. All data streams are required to have a `@timestamp` field. Documents without this field are rejected. If a new data stream is created and this field isn't defined in the mapping then it is automatically injected (with `date` field type using defaults). 

Users can define their own `date` or `data_nanos` field type in a composable index template. However this information isn't accessible when routing document to right backing index. The code parses the `@timestamp` assumes that the field is mapped as field type `date` with default settings (see [TODO](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstraction.java#L459)). Also part of the issue is that a mapping is part of the metadata of an index and when the `@timestamp` field is parsed, we don't know what the target index is, only the target data stream.

An idea would be to add additional configuration on top of a data stream that indicates how the `@timstamp` field should be parsed and whether it should be parsed into a regular date or data_nanos timestamp. This would allow parsing of `@timestamp` field with custom formats when resolving the right backing index during ingest time and can be used to automatically generate the mapping for the backing indices. Or if in the case when it is defined by the user in a template, verify whether the configuration in the data stream is consistent with the mapping in the template.

**Comment by martijnvg** [comment]
A composable index template with data stream template could look like this:

```
{
   "index_patterns": ...
   "data_stream": {
      "timestamp_field": {
          "type" : "date|date_nanos",
          "format": "...format..."
      }
   }
   "template": {
      ...
   }
}
```

Upon auto creation data streams would be inherit this config and its backing indices would be automatically setup with mappings for timestamp field that match with what is defined on the data stream.

At ingest time when routing document to the right backing index, we do have access to the data stream definition and use this that parse custom timestamp formats in the right way.

**Comment by imotov** [comment]
If we will do that, we will probably have to expand this support for `index.time_series.start_time` and `index.time_series.end_time` index settings for consistency.

**Comment by imotov** [comment]
It will just inconsistent. We have one way to specify format for time stamp, here we are proposing to introduce another way to manage format for routing and these settings are governed by the 3rd way. And all three represent essentially the same information.

**Comment by martijnvg** [comment]
With data streams, the user will not have to interact with the `index.time_series.start_time` and `index.time_series.end_time` index settings, since this is managed by the data stream abstraction. 

I think the format of the timestamp provided in the data doesn't have to match the format of these settings? Since these are different dates. The start_time and end_time settings upon creation of a data stream are based on current time and the `index.look_ahead_time` index setting and have no hard link between the timestamp in the documents being ingested (other than that the timestamp must be around current time too).

**Comment by imotov** [comment]
We have discussed it in a meeting and came to the decision that we will 
- only support only `strict_date_optional_time` while parsing settings (`index.time_series.start_time` and `index.time_series.end_timesettings`) but we will not allow milliseconds part to be non-zero. So boundaries will be always seconds-based.
- we will support only `strict_date_optional_time` or `strict_date_optional_time_nanos` in the mapping for these fields and we will index these timestamps accordingly 
- While routing the document we extract and accept timestamps with both millisecond and nanosecond precision, but millisecond and nanoseconds will be dropped for the purposes of the routing.

**Comment by martijnvg** [comment]
Closing this in favour of #83517
