### ISSUE TITLE
copy_to does not complain if target field does not exist

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#83282]
### Elasticsearch Version

7.16

### Java Version

_bundled_

### OS Version

Docker image

### Problem Description

Based on documentation, I would expect that `copy_to` field has to exist, but this does not seem to be so. See steps to reproduce to see that index is created just fine when `copy_to` is set to nonexistent `foobarX` instead of `foobar`. But it is not possible really to know what is done internally (there seems to be no way to list fields which have really been made), does this make 3 fields? 2? Does this mean that `foobar2` is simply not copied to `foobar` silently?

### Steps to Reproduce

```
curl -X PUT "localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "dynamic": false,
    "properties": {
      "foobar": {
        "type": "keyword"
      },
      "foobar2": {
        "type": "keyword",
        "copy_to": "foobarX"
      }
    }
  }
}
'
```

**Comment by fcofdez** [comment]
It seems like there's a gap in validation here, and it should at least warn that the field won't be copied if `dynamic` is set to false, or fail if it's set to `strict`

**Comment by cbuescher** [comment]
Adding validation here is an option, but I don't see this as a bug since this has been long-standing behaviour. With `"dynamic":"strict"`, adding a document that contains "foobar2" will throw an error as soon as we attempt the dynamic creation of the copy field. With  `"dynamic":"false"` the user is explicitely opting out of such errors or warnings. Adding additional validation can be a potential enhancement we can discuss going forward.

**Comment by mitar** [comment]
I mean, the example for `copy_to` does not talk at all about dynamic fields, but about copying to an existing/defined field. And this is my expectation. That you have to copy to an existing field. And that it does not warn if there is no such existing field.

**Comment by cbuescher** [comment]
> `copy_to` does not talk at all about dynamic fields, but about copying to an existing/defined field

We can probably improve that wording in the documentation a bit.

**Comment by mitar** [comment]
> improve that wording in the documentation a bit

I mean, one reason why I struggled was that it is not really documented how does the path `copy_to` field path looks like when you are somewhere deep inside nested/object fields and you want to copy it out few levels up. Knowing if I manage to find find correct field took me quite some trial&error.

**Comment by mitar** [comment]
Thanks!
