### ISSUE TITLE
Support for limiting flattened field type to just some fields of the JSON based on the field name

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#83293]
### Description

I have an arbitrary JSON structure which contains at various points an `id` field. E.g.:

```json
{
  "id": "1",
  "some": "payload",
  "left": [
    {
      "id": "2",
      "more": ["payload"]
    }
  ],
  "right": {"id": "3"},
  "top": {
    "obj": {
      "id": "4"
    }
  }
}
```

I would like to index this into one keyword field which would contain values `"1"`, `"2"`, `"3"`, and `"4"`. Using a flatten field type would populate it with much more. But if I could limit to the field name (`id`) it would work perfectly. Then I could search for documents which contain `id` with particular value somewhere in the structure.

**Comment by fcofdez** [comment]
It's possible to manipulate documents using ingest pipelines, I think your use case is well served by the [script processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/script-processor.html). Another option is to use [multi-match queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) that allows running a query against different fields.
