### ISSUE TITLE
Document the cases where security auto-configuration is not triggered

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#83306]
In 8.0.0 , with Security on by default, we introduce security auto-configuration when a node starts up for the first time. There are certain cases though, where we either can't proceed with auto-configuration or we determine/assume that the user is intending to configure security on their own and we proceed with starting the node without performing the security auto-configuration steps. We should document the cases where this happens and link it in appropriate places in our Getting started docs so that folks can easily find them / we can point them to these.

##### Environment related
- When the data dir exists and is not empty. This is a **strong** indication that this is not the first time that the node starts and we don't want to run autoconfiguration in this case. 
- When `elasticsearch.yml` doesn't exist, or we can't read it. If we can't read it, then we can't know if elasticsearch security features are already configured or not. This is also an indication that we;re running as a different user ( or a not privileged enough user ) and we can't handle this case. 
- When we can't read `elasticsearch.keystore` for the same reasons as above
- When the configuration directory is not writeable. This means that it is made read only by the admin, or the user starting is not the user that installed elasticsearch. 
- When indices are read-only ( ie, because of low disk space availability, https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#disk-based-shard-allocation ) because we can't write the `elastic` user password and the API key to the security index

##### Configuration related
- When `xpack.security.autoconfiguration.enabled` is set to false. This defaults to true and it's purpose is for users to be able to explicitly disable auto-configuration
- When `xpack.security.enabled` is set ( independent of its value ). We assume that the user wants to configure security features themselves.
- When any `xpack.security.transport.ssl.*` or `xpack.security.http.ssl.*` settings are set. We assume that the users want to configure TLS themselves
- When any of the discovery ( `discovery.type`, `discovery.seed_hosts` ) or initial master nodes (`cluster.initial_master_nodes` ) settings are set. There are two exceptions to this: 
  - When `discovery.type: single-node`
  - When `cluster.initial_master_nodes` exists but contains only the name of the current node. 
- If the current node cannot become a master node ( i.e. node.roles is configured with other values ).
- If the current node cannot have a copy of the security index ( i.e. only has role that can't contain data )  

#### Cases where initial `elastic` password generation doesn't happen

- All the above cases 
- When `bootstrap.password` is set in the `elasticsearch.keystore`
- When `autoconfiguration.password_hash` is set in the `elasticsearch.keystore` ( this is an implementation detail of the installation process for DEB/RPM ) 

#### Cases where an enrollment token for nodes is not generated ( default behavior for anything else than docker ) 

- When elasticsearch is only bound to localhost.

**Comment by lockewritesdocs** [comment]
@jkakavas, I see that you made yourself the owner of this issue. Do you plan on starting a draft, or do you want me to get a PR up for you to review?

**Comment by jkakavas** [comment]
I plan on writing this and I will very much welcome a review @lockewritesdocs !
