### ISSUE TITLE
Confusing blocks.read_only behavior for index write blocking

### ISSUE THREAD

**Issue by matschaffer** [elastic/elasticsearch#83305]
### Elasticsearch Version

8.0 branch - 655669b64e6

### Java Version

_bundled_

### OS Version

macos

### Problem Description

If set `blocks.read_only` on an index to `true`, attempting to set it back to `false` fails due to `FORBIDDEN/5/index read-only (api)`

### Steps to Reproduce

```
POST stuff/_doc
{ "some": "stuff" }

PUT stuff/_settings
{
  "blocks.read_only": true
}

PUT stuff/_settings
{
  "blocks.read_only": false
}
```

### Logs (if relevant)

![Screen Shot 2022-01-31 at 12 39 22](https://user-images.githubusercontent.com/690/151735692-4314f875-7a83-47d3-95a3-43670793bd2d.png)

**Comment by matschaffer** [comment]
Ahh.... Looks like you can use a more complete setting specification for this (found on https://stackoverflow.com/a/50954055/69002):

```
PUT stuff/_settings
{
 "index.blocks.read_only": null
}
```

Still kind of surprising that we wouldn't allow setting it to false, simply inverting the flag used to make the index readonly.

**Comment by DaveCTurner** [comment]
Definitely a bug, but this is already tracked at #48325 so I'm closing this as a duplicate.
