### ISSUE TITLE
Formatting issue in Elasticsearch security autoconfiguration on self-managed setup

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/elasticsearch#83316]
**Describe the bug**
Formatting issue in Elasticsearch security autoconfiguration on self-managed setup

**Build Details:**
```
Version: 8.0.0 RC2 BC3
Build: 49180
Commit: 8f8b91e8ce3b58e28e25caa5c5540ba6c4cc348e
```

**Preconditions**
1. Elasticsearch folder should be exist

**Steps to Reproduce**
1. Run the Elasticsearch through cmd.
2. Observe that extra symbols and 1m is added in autoconfigured Elasticsearch security 

**Actual Result**
Formatting issue in Elasticsearch security autoconfiguration on self-managed setup

**Expected Result**
Correct format should be displayed in autoconfigured Elasticsearch security on self managed setup

**Screen-Shot**
![image](https://user-images.githubusercontent.com/61860752/151759886-53441800-b276-4357-a4a3-44e89a2f97fc.png)

**Comment by jkakavas** [comment]
@deepikakeshav-qasource could you please run the following in the same machine where you get the above behavior

```
java -jar <ES_HOME>/lib/tools/ansi-console/jansi-2.3.4.jar
```

and share the output with us here? (`<ES_HOME>` being the directory where Elasticsearch RC2 is unzipped to )

**Comment by deepikakeshav-qasource** [comment]
Hi @jkakavas ,

Please find the below attached output after run the `java -jar <ES_HOME>/lib/tools/ansi-console/jansi-2.3.4.jar` command.

**Output:**
[elasticSearch.txt](https://github.com/elastic/elasticsearch/files/7970340/elasticSearch.txt)

**Screenshot:**
![image](https://user-images.githubusercontent.com/61860752/151786429-4ce6310a-2614-4a11-a832-af9cb9e13d0f.png)
![image](https://user-images.githubusercontent.com/61860752/151786436-e6831e08-7d9e-4be6-a908-05570faaf25c.png)

Please let us know if anything else is required from our end!!

Thanks!!

**Comment by jkakavas** [comment]
Thank you @deepikakeshav-qasource. @albertzaharovits any ideas what is happening in this case ? Could we be using an `Ansi` output ( when console.ansiEnabled()` at least ) and then call `bold()` on it instead of using the ansi escape characters directly ? This would probably guard against this kind of cases as I understand `bold()` would be a no-op here for instance. WDYT ?

**Comment by deepikakeshav-qasource** [comment]
Hi @jkakavas,

We have validated this issue on **8.0.0 RC2 BC4** and observed that issue is **Fixed**.

Correct formatting is displaying in autoconfigured Elasticsearch security on self managed setup.

**Build Details:**
```
Version: 8.0.0 RC2 BC4
Build: 49192
Commit: 57ca5e139a33dd2eed927ce98d8231a1f217cd15
```

**Screenshot:**

![image](https://user-images.githubusercontent.com/61860752/151915977-fb579ec4-0177-4305-bc7b-49a9404fba56.png)

Thanks!!
