### ISSUE TITLE
Checkstyle should reject `static record` as redundant

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#83311]
### Elasticsearch Version

master

### Installed Plugins

N/A

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

@arteam [observed](https://github.com/elastic/elasticsearch/pull/83221/files#r795474431) that `static record` is redundant, records are apparently implicitly static. I think we should make sure that Checkstyle picks this up rather than needing human involvement.

### Steps to Reproduce

Mark a record declaration as `static` and observe that `./gradlew precommit` still passes.

**Comment by pugnascotia** [comment]
I raised https://github.com/checkstyle/checkstyle/issues/11259 since the existing `RedundantModifer` check ought to be able to handle this.
