### ISSUE TITLE
Possible race condition: Cluster with no master, Indexing call can timeout/fail, but document can still make it into the index

### ISSUE THREAD

**Issue by bly2k** [elastic/elasticsearch#8333]
Boaz, this is from the issue we were working on.

In a single master cluster, when an indexing request is in-flight and the master node leaves, it is possible that there is small race condition between the time the index request is timed-out by ES, and a shard started cluster event happens - leading to successful indexing of the document (even though the client was notified of a failed/time-out error).

**Comment by clintongormley** [comment]
@bleskes is this still an issue?

**Comment by bleskes** [comment]
I'm not sure - I don't recall the issue anymore and I don't follow the description. @bly2k do you remember and can you elaborate?

**Comment by bly2k** [comment]
@clintongormley @bleskes Hey guys, I recall this was happening prior to 1.4. I could not reproduce this since 1.4 came out. I assume it has since been fixed already. Regardless, I believe we had tests for this scenario starting 1.4 so it likely is fixed and no longer an issue.

**Comment by bleskes** [comment]
Ok. Thanks @bly2k ! closing...
