### ISSUE TITLE
Invalid fields are still being evaluated per validate query api

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8334]
Consider the following use case:
https://gist.github.com/ppf2/e2764a37418f4b4e4e6d

The above example shows a query with default operator of AND, and a bogus field in the fields list.  The validate query api shows that it is still trying to do a match of the value "of" against the bogus field (for the other fields, the of has been removed via the stop filter).  As a result, the query returns no documents.  Should the bogus field be ignored completely in the evaluation of the query?

**Comment by clintongormley** [comment]
> Should the bogus field be ignored completely in the evaluation of the query?

I don't think it should be ignored.  If the field is specified, then we should include it.  We don't know whether it should be there or not.
