### ISSUE TITLE
Search Template API Explain Query String Argument Ignored

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#83363]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

I'm looking into a report of a [bug raised against the .NET client](https://github.com/elastic/elasticsearch-net/issues/5040) for use of search templates. The root cause seems to be that while the [REST API spec](https://github.com/elastic/elasticsearch-net/blob/8.0/src/ApiGenerator/RestSpecification/Core/search_template.json#L82) and [docs](https://github.com/elastic/elasticsearch-net/issues/5040) mention that "explain" can be included on the query string, doing so doesn't result in an explanation being returned. Only if it's included in the body is the explanation returned. This appears to be a bug with the parsing of search template rest requests as the `explain` parameter is not retrieved.

### Steps to Reproduce

Make a request with "explain=true" on the query string:

```
GET test/_search/template?explain=true
{
 "id": "my-search-template",
 "params": {
    "query_string": "hello world",
    "from": 0,
    "size": 10
  }
}
```

**Expected result:**
The explanation is included in the results.

**Actual:** 
The explanation is not included.

**Comment by zembrzuski** [comment]
Hi, just to keep you guys posted: I am already working in a PR to address this issue. I expect to raise a PR tomorrow. Thanks!

**Comment by chen-ni** [comment]
Hi @zembrzuski, are you still working on this? If not then I'd like to pick this up :)

**Comment by 1997sanket** [comment]
Hi, @zembrzuski is your PR merged? I am new here and want to contribute.

**Comment by Calabronx** [comment]
Hello @zembrzuski, are you still working with this issue? I would like to pick it up to contribution.

**Comment by timDINOS** [comment]
Hi @zembrzuski are you still working on this issue? I would like to work on it.
