### ISSUE TITLE
Aggregations shouldn't be reduced after final reduction

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#83385]
### Description

While aggregations are being reduced on the coordinating node for final display to the user, it is possible that internal aggregations are reduced again, even after the final reduction has taken place. 

Two specific places where this occurs is `InternalAutoDateHistogram` and `InternalVariableWidthHistogram`. 

It would be prudent to disallow further reductions after a final reduction has taken place. Regardless, it seems that both these histogram aggregations should delay internal aggregation reduction until the final number of buckets is determined and created.

**Comment by wchaparro** [comment]
Closing as not planned, focus on ES|QL development.
