### ISSUE TITLE
Order shards by "changes" when snapshoting

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#83408]
### Description

Snapshotting process when interrupted will return all not copied yet shards as PARTIAL.
If shards were ordered by what changes they have, the snapshoting process could work with "unchanged" shards first and finish them immediately. Then when working on copying a bigger "changed" shard, during interruption (node with shard is shut down) only the shards with changes will be marked as PARTIAL. 
This could be an improvement untill https://github.com/elastic/elasticsearch/issues/71333 is implemented.

**Comment by original-brownbear** [comment]
Just adding a few details about this plan:

We basically want to add another version of `org.elasticsearch.repositories.Repository#snapshotShard` here that will only take do the snapshot in case it's a noop (does not require uploading any data files).
This way we can do one fast pass over all shards on a data node to deal with the quick noop shard snapshots that just update metadata. After that pass we check which shards were not noops and upload those in another pass that does the file uploading.
=> way fewer shard failures when snapshotting while there's node restarts or other node changes going on.
