### ISSUE TITLE
Support  `top-metrics` aggregation within `cardinality` aggregation

### ISSUE THREAD

**Issue by ajosh0504** [elastic/elasticsearch#83474]
### Description

As of today, there is limited support for retrieving elements within a top metrics aggregation. For example, you can use top metrics within a `terms` aggregation to do something to say "find the latest risk level reported for a host". However you can't do much else with metrics obtained from a top metrics aggregation, for example "find the latest count of risky hosts per risk level". Aggregations like the `cardinality` agg would be a good one to support with top metrics aggregations. 

One of the workarounds suggested for this was to use transforms to get the "latest" documents and performing aggregations on the summary indices produced by this transform, which is a bit of an overkill. To provide some context, we are developing a [Host Risk Score](https://www.elastic.co/guide/en/security/8.0/host-risk-score.html) feature in the Security solution which would benefit greatly from queries like the above. In the absence of these, the feature would need to support two transforms, which are already a WIP in terms of maintenance etc.

**Comment by not-napoleon** [comment]
We discussed this at the fixit meeting today (2022-02-14).  

*Expanded Problem Statement*
We are running a `Terms` aggregation to bucket by host, with a `TopMetrics` sub-aggregation to get the most recent record for that host.  One of the fields in the top metrics is the risk level, so we can think of this intermediate result as most recent risk level bucketed by host.  We want to invert this, to get the (count of) hosts bucketed by risk level, but only counting the most recent records for each host.

*Options & Next Steps*

We agree that this is not currently solvable in Elasticsearch, and we discussed two options for solving this going forward:

- The ESQL project that the @elastic/es-ql team is working on should be able to solve this type of ask
    - No one from the query languages team was on the call today, so we should follow up with them offline and see where something like this falls on the roadmap.
- If we can ship all the term buckets back to a coordinating node, we could build a new pipeline aggregation to compute this.  However, this doesn't help if the total result set can't fit on the coordinating node

**Comment by ajosh0504** [comment]
[@elastic/es-ql](https://github.com/orgs/elastic/teams/es-ql) Inputs from y'all on this issue would be greatly appreciated to see if there's a path forward here via ESQL.

**Comment by imotov** [comment]
Just want to add that it looks like if we had #72983 fixed it would've been possible to solve this with bucket_script. It wouldn't be the most optimal solution though.

**Comment by wchaparro** [comment]
Closing as not planned in Aggs, focus is on ES|QL development.
