### ISSUE TITLE
Clarify the intended usage of service-tokens CLI

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#83491]
The documentation around [Service Accounts](https://www.elastic.co/guide/en/elasticsearch/reference/current/service-accounts.html) needs more clarification on how and when to use the [elasticsearch-service-tokens CLI](https://www.elastic.co/guide/en/elasticsearch/reference/current/service-tokens-command.html). 

Currently, it is not clear that the CLI generates token on the single node where the it runs. It also generates different token each time it runs. As such, the CLI is more suitable to be part of an orchestration flow. That is, using it to prepare a service token that can be used on all nodes in a cluster needs roughly the following steps:

1. Run the CLI to generate the service token on one node.
2. Copy the `service_tokens` file generated in the previous step to all other nodes of the cluster.

Alternatively, the [CreateServiceToken API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-service-token.html) can be used to generate a service token that is automatically usable on all nodes (similar to how [CreateUser API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html) works).

**Comment by rsaeks** [comment]
Thanks for clarifying! The API route works successfully!
