### ISSUE TITLE
[CI] JdbcSqlSpecIT » test {unsigned-long.testMod}

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#83516]
### CI Link

https://gradle-enterprise.elastic.co/s/u62fai6tyx2m4/tests/:x-pack:plugin:sql:qa:server:security:with-ssl:integTest/org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT/test%20%7Bunsigned-long.testMod%7D?top-execution=1

### Repro line

./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT" -Dtests.method="test {unsigned-long.testMod}" -Dtests.seed=CCB67441D91FFC5F -Dtests.locale=pt-BR -Dtests.timezone=Africa/Johannesburg -Druntime.java=17

### Does it reproduce?

No

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT&tests.sortField=FAILED&tests.test=test%20%7Bunsigned-long.testMod%7D&tests.unstableOnly=true

### Failure excerpt

```
java.lang.AssertionError: Different result for column [x], entry [1] expected:<4832.0> but was:<3877.0>
```

**Comment by pugnascotia** [comment]
More failures: https://gradle-enterprise.elastic.co/s/fjadwrkp4cds4

**Comment by tlrx** [comment]
Fails again: https://gradle-enterprise.elastic.co/s/fjadwrkp4cds4

`testMod` and `testDivide` failed multiple times recently so I'll mute them in #83532

**Comment by bpintea** [comment]
The fix attempt in https://github.com/elastic/elasticsearch/pull/83501 allows to replicate locally the expected result within the same day; [one of the latest CI failure](https://gradle-enterprise.elastic.co/s/6wyw4nnvuccgw/console-log?anchor=12677) shows that the ES/SQL produced result is valid, but the expected one computed by H2 isn't.
