### ISSUE TITLE
Guava shows up in IntelliJ autocomplete for some tests

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#83545]
x-pack security has a runtime dependency on guava because some of security's dependencies use it internally. Within Elasticsearch we do not want to use Guava (see https://github.com/elastic/elasticsearch/issues/13224). However, classes from guava currently show up within IntelliJ autocomplete when in xpack security tests.

Running `:x-pack:plugin:security:dependencies` shows guava on the `internalClusterTestRuntimeClasspath` (which is expected since it is a runtime dependency). Within IntelliJ guava shows as Runtime scope on the `:x-pack:plugin:security:test` module. It's unclear where it is leaking into autocomplete.

I thought it might be related to https://github.com/elastic/elasticsearch/pull/74411, which refactored how transitive removal worked, and in the resulting code I only see non-test configurations, but I might be missing something.

**Comment by breskeby** [comment]
I created a small project to reproduce the problem. Turns out runtime dependencies are shown in auto completion for test sources in idea. (tested with idea 2021.3.1)

**Comment by breskeby** [comment]
I've created https://youtrack.jetbrains.com/issue/IDEA-288172

**Comment by breskeby** [comment]
Got feedback from the idea team that it works as expected. See https://youtrack.jetbrains.com/issue/IDEA-288172

**Comment by mark-vieira** [comment]
Given this is a bug in IntelliJ and we've made it known to them I'm not sure what else we can do here. I'm closing this issue for now.
