### ISSUE TITLE
Default, recommended config issues a warning

### ISSUE THREAD

**Issue by pauldraper** [elastic/elasticsearch#83561]
### Elasticsearch Version

7.10.2

### Java Version

_bundled_

### OS Version

Ubuntu 20.04

### Problem Description

I expect that Elasticsearch defaults don't produce warnings.

However, I get the following warning:

```txt
gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
```

Weirdly, the docs recommend **not enabling** `auto_import_dangling_indices` (which is indeed the default).

And yet Elasticsearch itself issues a warning when it's not enabled.

So there seems to be some confusion around I can run Elasticsearch in a safe and recommended way.

### Steps to Reproduce

Start elasticsearch.

### Logs (if relevant)

```
{"type": "server", "timestamp": "2022-02-05T18:17:46,465Z", "level": "WARN", "component": "o.e.g.DanglingIndicesState", "cluster.name": "elasticsearch", "node.name": "rivet6", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
```

**Comment by DaveCTurner** [comment]
This is the bug that https://github.com/elastic/elasticsearch/pull/65309 addresses, you should upgrade to pick up the fix.

**Comment by pauldraper** [comment]
Thanks!
