### ISSUE TITLE
[DOCS] Clarify CCS/CCR version compatibility

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#83628]
cc @lockewritesdocs and @giladgal 

It has been pointed out https://github.com/elastic/kibana/issues/124465#issuecomment-1028516829 that our documentation around CCS/CCR version compatibility doc may not be entirely accurate.

I have solicited some of the feedback around the following pages, and we might want to re-architecture the content to make sure they are informative and consistent with the supportability.

### Pages to be updated:
- https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-ccr.html
- https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations
- https://www.elastic.co/guide/en/cloud/current/ec-enable-ccs.html (Elastic Cloud page)

### Issues:
1. On the [remote-clusters](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) page, two `Version compatibility table` are present.  One under `sniff mode`, one under `proxy mode`.
As far as I can see, these two tables are identical and do not serve the purpose for either CCS nor CCR compatibility.
    - This can be super confusing to users because we actually have 3 sets of rules, one for CCS, one for CCR, and one for remote cluster connectivity.  The latter doesn't really serve any purpose other than the clusters can be connected, but individual features supportability constraints are listed elsewhere.  See items 3 and 4.

2. On the [xpack-ccr](https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-ccr.html) page, CCR compatibility should be explicitly pointed out that it relies on both cluster version and _index_ version.  
    - The latter is currently missing from the doc.

3. For CCR cluster version compatibility is stated as follows:
    - In a uni-directional configuration, the cluster containing follower indices must be running the same or newer version of Elasticsearch as the remote cluster. If newer, the versions must also be compatible as outlined in the following matrix.
      - `Version compatibility matrix` (which is the same table as the one in the [remote-cluster](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) page, yet the table does not conform with the above rules. 
    - In a bi-directional configuration, version compatibility is not stated on the doc. 

4. For CCS cluster version compatibility is stated as follows:
    - Elastic only supports searches from a local cluster to a remote cluster running:
      - The previous minor version.
      - The same version.
      - A newer version. This version must also be compatible with the local cluster as outlined in the following matrix.
        - `Version compatibility matrix` (which is the same table as the one in the [remote-cluster](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) page, yet the table does not conform with the above rules. 

5.  Once all these pages have been updated, there should be a cloud doc update linking to the corresponding pages.

### Proposal
- [x] P1. We should also probably spell out explicitly in the [docs on remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) that we’re just talking about connectivity between clusters there, and individual cross-cluster features may impose stricter compatibility constraints.   Since the connectivity doesn't really serve any real purpose, I propose to remove both `Version compatibility table` from the [remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) page and redirect users to [CCS](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations) and [CCR](https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-ccr.html) compatibility pages to avoid duplicated information scattered.

Instead of the following:
```
Important!
Elastic only supports cross-cluster search on a subset of these configurations. See [Supported cross-cluster search configurations](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations).
```
Perhaps:
```
Important!
Individual cross-cluster features may impose stricter compatibility constraints.  See [Supported Cross-cluster search configurations](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations) and [Supported Cross-cluster replication configurations](https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-ccr.html)
```
- [x] P2.  CCR also requires index compatibility which is similar to what we have for the snapshot today: [snapshot index compatibility](https://github.com/elastic/elasticsearch/edit/7.17/docs/reference/snapshot-restore/index.asciidoc)
Perhaps:
```
Any follower index you replicate from leader must also be compatible with the current cluster’s version. If you try to replicate an index created in an incompatible version, the replication attempt will fail. 
```
And we can also add an index compatibility table like this (It's not clear to me whether this applies to both uni- and bi-directional??):
<details>
      <summary> Click to expand the CCR index version compatibility table (⚠️ TBC) </summary>

![Screen Shot 2022-02-08 at 3 10 40 pm](https://user-images.githubusercontent.com/39002973/152917497-2354ee02-75e0-4c32-89e6-976267032776.png)
    </details>
    
- [x] P3.1 As you can see, the CCR uni-directional cluster version compatibility table gets a little bit complicated with all the clauses.  I am happy to remove the table completely if we can state them in some words that make more sense.  If not, we can continue to have the table, but we want to avoid keep adding new versions to the table for maintainability. 
    - the following table removes some of the old 5.x and early 6.x EOL versions.
    - the following table follows the above rule where the follower cluster must be running the same or newer version as the leader.
    - the following table adds an asterisk to all the diagonal element to indicate all the versions in the ranges like `7.1-7.16` still needs to obey the rule where the follower must be running the same or newer version as the leader.
    - It is also much more clear to state `follower/leader` vs `remote/local` cluster for the purpose of CCR.
    - If we decided to keep the table and update the content, can we keep the table uncollapsed by default? This is to ensure the table is visible when users navigate to the page.  There have been several occasions the table has been overlooked.
<details>
  <summary> Click to expand the CCR uni-directional cluster version compatibility table</summary>

  ![Screen Shot 2022-02-07 at 6 09 00 pm](https://user-images.githubusercontent.com/39002973/152911031-94658024-8b8f-48e7-97d6-1fa9566c9fc3.png)
</details>
    
- [x] P3.2 For CCR bi-directional, we don't seem to have any version rule explicitly mentioned on the [xpack-ccr](https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-ccr.html) page.  Can we add something like this to the effect? 
```
the two clusters in bi-directional replication must remain on the same version
```

- [x] P4. CCS cluster version compatibility 
  - Since the table on the [CCS page](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations) does not conform with the stated rules, we might want to either remove the table or update the table like the following: (⚠️ TBC) 
  - If we decided to keep the table and update the content, can we keep the table uncollapsed by default? 
<details>
  <summary> Click to expand the CCS cluster version compatibility table</summary>

  ![Screen Shot 2022-02-08 at 2 37 13 pm](https://user-images.githubusercontent.com/39002973/152914194-f6c7824e-c284-43f0-bfa1-9f206c75f5f6.png) 
</details>

- [x] P5.  Please follow up with a cloud doc update on this page. https://www.elastic.co/guide/en/cloud/current/ec-enable-ccs.html 
  - I think pointing directly to the CCS and CCR compatibility page is the best. 

----
This is a followup on https://github.com/elastic/elasticsearch/pull/81239

**Comment by jrodewig** [comment]
Thanks for raising this @Leaf-Lin. I've read this a couple of times, but I don't understand the following:

>For CCS cluster version compatibility is stated as follows:
>
> Elastic only supports searches from a local cluster to a remote cluster running:
The previous minor version.
The same version.
A newer version. This version must also be compatible with the local cluster as outlined in the following matrix.
Version compatibility matrix (which is the same table as the one in the [remote-cluster](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html) page, yet **the table does not conform with the above rules**.
>>>

> P4. CCS cluster version compatibility
Since the table on the [CCS page](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations) **does not conform with the stated rules**, we might want to either remove the table or update the table like the following: (⚠️ TBC)
If we decided to keep the table and update the content, can we keep the table uncollapsed by default?


What "stated rules" are you referring to here?

**Comment by Leaf-Lin** [comment]
Hi, 

On the [CCS Supported cross-cluster search configurations](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations) page, it is currently showing this table,
![Screen Shot 2022-02-09 at 3 34 44 pm](https://user-images.githubusercontent.com/39002973/153122586-9345a1c8-3bbf-49d3-a2a7-9d78f6878319.png)
 
But many of the points in this table does not follow these three rules:
- Elastic only supports searches from a local cluster to a remote cluster running:
  - The previous minor version.
  - The same version.
  - A newer version. This version must also be compatible with the local cluster as outlined in the following matrix.

For example, local==7.1-7.16 and remote== 6.8 should be a cross, not a tick.

----

I propose to change that table to the following so that all element in the table also satisfy these three rules.
![image](https://user-images.githubusercontent.com/39002973/153122772-3fc26d61-c419-43fd-9003-b3b9e22fdc0b.png)

**Comment by giladgal** [comment]
@Leaf-Lin regarding CCS, the text outside the table describes the current 8.0 (and future) supported combinations. The table describes the supported (and unsupported) combinations between previous releases, e.g. CCS from a local on 7.1-7.16 to a  remote on 6.8 is indeed possible and supported.

**Comment by javanna** [comment]
It looks like all the sub-tasks proposed in the description were completed. Closing.
