### ISSUE TITLE
Elastic should log what's the expected number of nodes to elect master, when it fails

### ISSUE THREAD

**Issue by kretes** [elastic/elasticsearch#8362]
In https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java#L1037 Elastic logs that it was not possible to elect master from active nodes. Since min_number of nodes is a transient value - its current value should be logged here as well, to understand how many was ussing

**Comment by clintongormley** [comment]
The relevant code is now here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java#L508

**Comment by bleskes** [comment]
and here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java#L942
