### ISSUE TITLE
Issues with extracting code snippets from asciidoc files

### ISSUE THREAD

**Issue by edh-oss** [elastic/elasticsearch#83696]
### Elasticsearch Version

current build

### Java Version

_bundled_

### OS Version

mac os 11.2.3

### Problem Description

Two issues with extracting code snippets from asciidoc files:

**Malformed source blocks:**

If a parameter list is clearly the beginning of a source block, then it should be immediately followed by a valid block delimiter.  If it's not, the result should be an error.  This is being ignored.  For instance, from the file

[/docs/reference/how-to/fix-common-cluster-issues.asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/reference/how-to/fix-common-cluster-issues.asciidoc)

```
[source,console]
---
GET /_cat/thread_pool?v&s=t,n&h=type,name,node_name,active,queue,rejected,completed
---
```
and

```
[source,console]
---
GET /_nodes/hot_threads
---
```

Using three dashes as delimiters, rather than the expected four, results in the corresponding snippets not being generated.

The related PR #83624 makes corresponding updates to two doc files.

**Block comments aren't being treated as comments, rather their contents are still being parsed and used**

The asciidoc format allows for block comments, which begin and end with four slashes.  For instance, from the file

[/docs/reference/ingest/common-log-format-example.asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/reference/ingest/common-log-format-example.asciidoc)

```
////
[source,console]
----
DELETE _data_stream/*
DELETE _index_template/*
----
// TEST[continued]
////
```

This should be ignored.  Instead, the source block defined within the block comment is still parsed, and a corresponding snippet is being generated.

### Steps to Reproduce

Call the :docs:buildRestTests tasks, see the corresponding results in the "docs/build/rest/rest-api-spec" folder.

For instance, see the resulting file "docs/build/rest/rest-api-spec/test/reference/ingest/common-log-format-example.yml"

This is the end of the file:

```
  - do:
      raw:
        method: DELETE
        path: "_data_stream/*"
  - is_false: _shards.failures
  - do:
      raw:
        method: DELETE
        path: "_index_template/*"
  - is_false: _shards.failures
  ```

That's being generated from the commented out source block, listed above in the problem description.

**Comment by jrodewig** [comment]
Hi @edh-oss,

Thanks for raising these issues!

**Malformed source blocks**

Thanks for catching these. I'll review your changes in https://github.com/elastic/elasticsearch/pull/83624 and get those merged in.

**Block comments aren't being treated as comments, rather their contents are still being parsed and used**

This is expected behavior. We often use comments to "hide" setup and teardown snippets for examples. Our integration test suite requires these snippets to pass the related tests, but they're often not relevant to the information we're trying to highlight in docs.

If you want to include a snippet in a comment block and not run the related tests, you'll need to omit `[source,console]` from the code block.

**Comment by edh-oss** [comment]
OK.  Is this a good place for other questions, related to expected behavior?

For instance, is there ever a reason to look for snippets in something other than an asciidoc file?  Currently we look through a little over 350 files that aren't asciidoc, mostly png and yaml files.  Any reason not to filter on file names and skip anything that doesn't end with ".asciidoc"?

**Comment by jrodewig** [comment]
> OK. Is this a good place for other questions, related to expected behavior?

Generally, it's probably a good idea to create a separate issue for different enhancement requests or bug fixes.

> For instance, is there ever a reason to look for snippets in something other than an asciidoc file? Currently we look through a little over 350 files that aren't asciidoc, mostly png and yaml files. Any reason not to filter on file names and skip anything that doesn't end with ".asciidoc"?

Someone from the @elastic/es-delivery can provide a better answer. As far I know, we only extract our docs REST tests from .asciidoc files. It's possible to exclude other files (we do that [here](https://github.com/elastic/elasticsearch/blob/04e5823a693332dd9e2ddfdcc91d1551aebf8aef/docs/build.gradle#L17)), but I can't really speak to whether excluding non-asciidoc files is worth the time or risk.

**Comment by lockewritesdocs** [comment]
I don't think that there's anything for the Docs team to do here, so I'm closing this issue.
