### ISSUE TITLE
[Upgrade Assistant] Warn if cluster's node attributes and data tiers may not match

### ISSUE THREAD

**Issue by VimCommando** [elastic/elasticsearch#83800]
**Describe the feature:**

If a node has `node.data: true` defined and includes _any_ `node.attributes.data` value, list a warning the configuration may not be valid for data tiers in 8.0.

The presence of a `node.attribute.data` value _strongly_ indicates a hot/warm or tiered architecture. It is completely valid to run all data tiers on the same nodes if the cluster is not used for timeseries data.

**Describe a specific use case for the feature:**

Historically Elasticsearch has recommended using `node.attributes.data` to identify `hot`, `warm` or `cold` nodes.

In 7.9 we introduced data tiers: https://www.elastic.co/guide/en/elasticsearch/reference/7.16/data-tiers.html

When upgrading to 8.0 the legacy `node.data` is no longer allowed: https://github.com/elastic/elasticsearch/issues/66409

In 7.10 through 7.17 any node with `node.data: true` is assigned all 5 data tiers: `data_content`,  `data_hot`, `data_warm`, `data_cold` and `data_frozen`. This can conflict with the preexisting node attribute, leading to shards being assigned to unexpected nodes. This includes _system_ indices which could end up on cold/frozen tiers and cause unexpected cluster behavior.

In 8.0 we rely on `_tier_preference` so it is critical these are _accurate_ in the nodes' `elasticsearch.yml` files: https://github.com/elastic/elasticsearch/issues/76147

**Comment by masseyke** [comment]
I am going to take this one, but I'm a little unclear on where we settled. Are we just updating the message for the existing deprecation we already have if `node.data` is set? Or are we also adding a separate warning deprecation if `node.attributes.data` is set?

**Comment by masseyke** [comment]
We ought to have this on the 8.x line as well right?

**Comment by jeacott1** [comment]
shouldn't the docs perhaps be updated here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-hot-warm-topologies
it still uses "node.attr.data: hot" etc in the 2.5 version docs which is quite confusing.

**Comment by abdonpijpelink** [comment]
Thanks for reporting @jeacott1 ! I've opened a new issue to fix the documentation here: https://github.com/elastic/cloud-on-k8s/issues/6196
