### ISSUE TITLE
Top 10 Metrics aggregations

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#83825]
### Description

The "Geo & Analytics" team is working towards getting performance tests for aggregations. The idea is to adopt a solution or product driven approach where we, at lest at the beginning, start testing the most important and most used aggregations for each solution. For this reason we would like to have a list of the top 10 aggregations used in the Metrics domain, possibly with at least one example for each, and information about indices and their settings. In summary we need:

1. Top 10 aggregations with relevant parameters ranges (i.e for a date histogram aggregation we would like to know min/max intervals and date ranges, for terms aggregations what level of nesting is used and so on)
2. An example for each of the top 10 aggregations above
3. Fields and type of each field used in each aggregation
4. Which indices each aggregation runs against
5. For each index the typical settings and mappings

**Comment by smith** [comment]
@elastic/infra-monitoring-ui we may be able to get this data by adding more telemetry, but the easiest thing to do probably is to go through our UIs and catalog the types of aggregations we're doing, which probably isn't that many.

One approach we could take is looking at each of our alerts and taking a complex case as an example, like high-cardinality group-by cases, which could be representative for the queries we do.

**Comment by smith** [comment]
I haven't heard any follow up about this in a long time. Closing.
