### ISSUE TITLE
 CPU Utilization (%) 在节点概览中不能正确显示，在节点高级选项中正常

### ISSUE THREAD

**Issue by Andydufresneguohao** [elastic/elasticsearch#83824]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Linux kylin-ThinkPad-T14-Gen-1 5.4.18-35-generic #21-KYLINOS SMP Tue Jul 20 13:33:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

关于 CPU Utilization (%) 这个参数
在一个节点的概览中cpu利用率显示为不可用，但是在这个节点的高级中却能显示cpu利用率

### Steps to Reproduce

https://inqk2zwcbw.feishu.cn/docs/doccnBf3nPxsxyzQ6eXtY4Tuk0d#
这是我搭建的过程文档

**Comment by arteam** [comment]
Hey @Andydufresneguohao Please submit your bug report in English, otherwise we can't be properly triage and verify it.
