### ISSUE TITLE
CPU utilization display exception

### ISSUE THREAD

**Issue by Andydufresneguohao** [elastic/elasticsearch#83877]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Linux kylin-ThinkPad-T14-Gen-1 5.4.18-35-generic #21-KYLINOS SMP Tue Jul 20 13:33:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

In the overview of a node, CPU utilization is displayed as unavailable, but in the advanced of this node, CPU utilization can be displayed
![advanced](https://user-images.githubusercontent.com/30066427/153692205-548b208b-85be-469f-b8c6-0b9c9fbdcf78.png)
![overview](https://user-images.githubusercontent.com/30066427/153692210-34f55182-efc9-4530-beb8-932539f5af2d.png)

### Steps to Reproduce

This link container my file such as docker-compose.yml ,elasticsearch.yml and kibana.yml
https://inqk2zwcbw.feishu.cn/docs/doccnBf3nPxsxyzQ6eXtY4Tuk0d#

**Comment by pquentin** [comment]
Thanks for filing the issue! This appears to be a Kibana issue. I tried to transfer it, but GitHub fails with a unicorn page when I do that. It will need to be retried later. Alternatively, you can close this issue and open a new one in https://github.com/elastic/kibana.

**Comment by Andydufresneguohao** [comment]
Thanks

**Comment by Andydufresneguohao** [comment]
I will transfer it to Kibana issue.
