### ISSUE TITLE
Lucene analysis link is broken from version 8

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#83948]
### Elasticsearch Version

8.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

macos

### Problem Description

Refer to all the latest analysis pieces like [edge-n-gram token filter](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/analysis-edgengram-tokenfilter.html) which mention the underlying Lucene token filter it is using, as shown in attached screen-shot, when you click on the link, it's broken since es version 8.0, before that ES was using lucene 8.X and there path was like `https://lucene.apache.org/core/8_11_1/analyzers-common/org/apache/lucene/analysis` but ES since its 8.0 version is using Lucene 9.X, where analysis path is `https://lucene.apache.org/core/9_0_0/analysis/common/org/apache/lucene/analysis/`, notice that `analyzers-common` is replaces with `analysis/common` in the URL. 

@cbuescher Let me know if I could work on this issue.

### Steps to Reproduce

1. Go to [Edge-n-gram token-filter](url) and open the Lucene link for the token filter.

**Comment by amitmbm** [comment]
@cbuescher please take a look, I found that in analysis.asciidoc its defined as 

```
:lucene-analysis-docs:  https://lucene.apache.org/core/{lucene_version_path}/analyzers-common/org/apache/lucene/analysis
```
which is causing the issue, but couldn't find this file, when I searched in the github repo of elastic, also this is the variable which is changed according to Lucene version, so it would be interesting to see how to handle it for ES version 8 and below.

**Comment by cbuescher** [comment]
@amitmbm yes, I think the link that `:lucene-analysis-docs:` points to probably needs to be updated starting with 8.0. Thanks for spotting that.

**Comment by cbuescher** [comment]
Yep, other documentation pages using that variable are also broken starting with 8.0, so fixing the base URL with the change you already detected would be best. Happy if you can open a PR for that.

**Comment by amitmbm** [comment]
@cbuescher I would be more than happy to work on it, but I need your guidance, as I looked at the way its generated and mentioned this in my previous reply https://github.com/elastic/elasticsearch/issues/83948#issuecomment-1040365177, as link is version dependant, need some suggestions how to handle it in code.

**Comment by cbuescher** [comment]
@amitmbm as far as I can see `lucene_version_path` is defined in `docs/Versions.asciidoc` and gets automatically substituted in `lucene-analysis-docs`, so nothing really to change there, only the part of the URL after that needs updating.

**Comment by amitmbm** [comment]
@cbuescher thanks, now it makes sense to me, PR is coming your way 😄

**Comment by amitmbm** [comment]
@cbuescher Please review the PR https://github.com/elastic/elasticsearch/pull/84094
