### ISSUE TITLE
Add ability to override keyed parameter in filters aggregation

### ISSUE THREAD

**Issue by tilman** [elastic/elasticsearch#83957]
See https://github.com/elastic/elasticsearch/issues/83957#issuecomment-1061038677 for the reproduction and the description of the issue. 

Original bug report: 
----

### Elasticsearch Version

6.4.3

### Installed Plugins

/

### Java Version

_bundled_

### OS Version

linux

### Problem Description

using the bucket_sort in a filters aggregation results in no sorting at all

### Steps to Reproduce

Example query:

````
{
  "aggs": {
    "Category": {
      "filters": {
        "other_bucket": false,
        "other_bucket_key": "No Category",
        "filters": {
          "165422": {
            "term": {
              "product.categories.id": 165422
            }
          },
          "171229": {
            "term": {
              "product.categories.id": 171229
            }
          },
          "165523": {
            "term": {
              "product.categories.id": 165523
            }
          },
          "165530": {
            "term": {
              "product.categories.id": 165530
            }
          }
        }
      },
      "aggs": {
        "cancelation_count": {
          "sum": {
            "script": {
              "inline": "if(doc['order_cancellation_id'].value > 0){return 1} return 0;",
              "lang": "painless"
            }
          }
        },
        "sort_cancelation_count": {
          "bucket_sort": {
            "sort": [ "cancelation_count" ],
            "size": 4
          }
        }
      }
    }
  },
  "size": 0
}
````

### Logs (if relevant)

Example result (filters aggregations are not sorted via the sum:cancelation_count but instead via the bucket key):
```
{
  "took": 620,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 9580162,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "Category": {
      "buckets": {
        "165422": {
          "doc_count": 5835212,
          "cancelation_count": {
            "value": 145488
          }
        },
        "165523": {
          "doc_count": 1974874,
          "cancelation_count": {
            "value": 43586
          }
        },
        "165530": {
          "doc_count": 1231949,
          "cancelation_count": {
            "value": 33821
          }
        },
        "171229": {
          "doc_count": 193478,
          "cancelation_count": {
            "value": 5939
          }
        }
      }
    }
  }
}
```

**Comment by imotov** [comment]
Did you get this result directly from elasticsearch or through some client? I tried to reproduce it and it looks like elasticsearch returns correctly ordered list. But since the order of field in JSON is basically undefined, it makes sorting named buckets a bit of a moot point and any JSON post-processing will mess these values up anyway.

You can reliably sort buckets if they are in an array, but in case of filters aggregation this is only possible for anonymous filters and you will have to do something redundant like adding an additional terms agg to figure out which bucket corresponds to which key:
```
DELETE test
PUT test
{
  "mappings": {
    "properties": {
      "key": {
        "type": "keyword"
      }
    }
  }
}

PUT test/_bulk?refresh
{ "index": {} }
{ "key": "A", "val": 10}
{ "index": {} }
{ "key": "B", "val": 15}
{ "index": {} }
{ "key": "C", "val": 0}


GET test/_search
{
  "size": 0,
  "aggs": {
    "by_key": {
      "filters": {
        "filters": [
          {
            "term": {
              "key": "A"
            }
          },
          {
            "term": {
              "key": "B"
            }
          },
          {
            "term": {
              "key": "C"
            }
          }
        ]
      },
      "aggs": {
        "term": {
          "terms": {
            "field": "key"
          }
        },
        "max_val": {
          "max": {
            "field": "val"
          }
        },
        "sort_by_val": {
          "bucket_sort": {
            "sort": [
                {"max_val": "asc"}
            ]
          }
        }
      }
    }
  }
}
```

@elastic/es-analytics-geo I am adding this for team discuss to see if it makes sense to make `keyed` option user-configurable for cases like this.

**Comment by imotov** [comment]
We have discussed it and decided that we should add an ability to override "keyed" parameter on this aggregation. In case of name filters we only supposed keyed output format that cannot be reliably supported by JSON since it doesn't guarantee the order of the elements in the object. If filters are anonymous, we return them as an array, but then sorting changes the order of elements making it impossible to know which result came from with filter. In this particular case we want named filters with non-keyed result.

**Comment by michal-rozehnal** [comment]
Hello, is this issue available? I am looking for good first issue (I have never contributed into open code yet) I can work on and this one seems appropriate.

**Comment by nik9000** [comment]
It's available, sure. I believe the place to start here is `FiltersAggregatorBuilder#parse`. We can't change the current behavior so we should make sure that we have a test for what we have - sometimes these are lacking. I'd probably dump a REST based test for this into `220_filters_bucket.yml` which you can run with `./gradlew -p rest-api-spec check -Dtests.method='*filters_bucket*'`

**Comment by michal-rozehnal** [comment]
Thank you for hints! I will work on it then.

**Comment by chen-ni** [comment]
@michal-rozehnal Is there any update? I'd also like to help :)

**Comment by michal-rozehnal** [comment]
Hi, I was able to execute mentioned test but didn't find class `FiltersAggregatorBuilder`. Feel free to continue wit this issue, I will be few days away from keyboard.

**Comment by chen-ni** [comment]
@michal-rozehnal Sorry, I got some other stuff to do, won't be able to work on this. Please keep going :)

**Comment by chen-ni** [comment]
@michal-rozehnal It was a typo. It's actually called `FiltersAggregationBuilder`, located in `org/elasticsearch/search/aggregations/bucket/filter/FiltersAggregationBuilder.java` :)

**Comment by chen-ni** [comment]
> We have discussed it and decided that we should add an ability to override "keyed" parameter on this aggregation. In case of name filters we only supposed keyed output format that cannot be reliably supported by JSON since it doesn't guarantee the order of the elements in the object. If filters are anonymous, we return them as an array, but then sorting changes the order of elements making it impossible to know which result came from with filter. In this particular case we want named filters with non-keyed result.

@imotov So what we want is:

- If the request contains named filters followed by bucket sort, then instead of returning a sorted JSON object, we want to return a sorted JSON array;
- Each item of the JSON array represents the result of a named filter, with the explicit name.

The returned JSON array would look like this:
```
{
  "aggregations": {
    "aggregation_name": {
      "buckets": [
        {
          "first_filter": {
            "doc_count": 123,
            "metric_to_sort_by": {
              "value": 1
            }
          }
        },
        {
          "second_filter": {
            "doc_count": 123,
            "metric_to_sort_by": {
              "value": 2
            }
          }
        },
        {
          "third_filter": {
            "doc_count": 123,
            "metric_to_sort_by": {
              "value": 3
            }
          }
        }
      ]
    }
  }
}
```

Is this correct?

**Comment by michal-rozehnal** [comment]
@chen-ni thank you for clarification! Now I can see the class :) I will study current implementation and then I can try to fix this issue

**Comment by nik9000** [comment]
We had some real design trouble on this one because we didn't quite realize how to implement a way to do this without breaking our clients. It looks like https://gist.github.com/sethmlarson/3cc46d8113043408674a878a7f87a76c is the way. Sorry to be so late on this one.
