### ISSUE TITLE
Cannot capture New Zealand using Orientation

### ISSUE THREAD

**Issue by brianalexander** [elastic/elasticsearch#84009]
### Elasticsearch Version

7.16.2

### Java Version

openjdk version "1.8.0_292"

### OS Version

Darwin Kernel Version 20.6.0

### Problem Description

I'm using ES 7.16.2 and trying to capture New Zealand and having a horrible time of it.

This query does not capture NZ no matter the combinations of orientation values that I use.
```
POST /geo-test/_doc
{
  "location" : {
    "type" : "polygon",
    "coordinates" : [
      [
                [-175.1235077, -28.8773225],
                [165.7437641, -28.8773225],
                [165.7437641, -52.7224663],
                [-175.1235077, -52.7224663],
                [-175.1235077, -28.8773225]
       ]     
    ]
  }
}
```

The only way I can get it to work is by translating the negative longitudes by +360.

```
POST /geo-test/_doc
{
  "location" : {
    "type" : "polygon",
    "coordinates" : [
      [
                [185.1235077, -28.8773225],
                [165.7437641, -28.8773225],
                [165.7437641, -52.7224663],
                [185.1235077, -52.7224663],
                [185.1235077, -28.8773225]
       ]     
    ]
  }
}
```
Is that the intended method?

Note: I am viewing these polygons in the Kibana Map viewer. I suppose the issue could be there or I just really don't understand what Orientation is supposed to be doing here.

Thanks!

### Steps to Reproduce

Create index: 

```
PUT /geo-test
{
  "mappings":{
    "properties": {
      "location": {
        "type": "geo_shape"
      }
    }
  }
}
```

Use the queries listed above

View in Kibana Map viewer

**Comment by iverase** [comment]
Hey @brianalexander,

This is a known issue in Elastic maps that will be fix in 8.1:

https://github.com/elastic/kibana/issues/120909

You can check that the polygon crosses the dateline when querying:

```
PUT /geo-test
{
  "mappings":{
    "properties": {
      "location": {
        "type": "geo_shape"
      }
    }
  }
}

POST /geo-test/_doc
{
  "location" : {
    "type" : "polygon",
    "coordinates" : [
      [
                [-175.1235077, -28.8773225],
                [165.7437641, -28.8773225],
                [165.7437641, -52.7224663],
                [-175.1235077, -52.7224663],
                [-175.1235077, -28.8773225]
       ]     
    ]
  }
}

GET /geo-test/_search?pretty
{
  "query": {
    "geo_shape": {
      "location": {
        "shape": {
          "type": "Point",
          "coordinates": [-178, -30]
        }
      }
    }
  }
}
```

This query should return the indexed polygon. 

Still I think there is some information missing about how orientation works. There is some important info that was present in older version that says that orientation of geo_shape field does not affect to GeoJson but only WKT. In order to enforce orientation in GeoJson, you need to add explicit the orientation in the GeoJson itself:

```
IMPORTANT NOTE: WKT does not enforce a specific order for vertices thus ambiguous polygons around the dateline and poles are possible. [GeoJSON](https://tools.ietf.org/html/rfc7946#section-3.1.6) mandates that the outer polygon must be counterclockwise and interior shapes must be clockwise, which agrees with the Open Geospatial Consortium (OGC) [Simple Feature Access](http://www.opengeospatial.org/standards/sfa) specification for vertex ordering.
```

I changed the issue from bug to docs to address it.

**Comment by brianalexander** [comment]
@iverase Okay cool, thanks for the info!

Tangential question that might be relate or not: If I have a polygon that captures one of the poles, do I need to split it into a MultiPolygon? This query results in the error: `"reason" : "Cannot determine orientation: signed area equal to 0. Points are collinear or polygon self-intersects."`
```
POST /geo-test/_doc
{
  "location": {
    "type": "Polygon",
    "coordinates" : [[
      [-45, 85], [-135, 85], [135, 85], [45,85], [-45, 85]
      ]]
  }
}
```
I guess ES cannot infer from the coordinates in which direction to close the polygon? I handled it by splitting the geometry into a MultiPolygon.
```
POST /geo-test/_doc
{
  "location": 
{
         "type": "MultiPolygon",
         "coordinates": [
             [
                 [
                     [0,90],[0,80],[180,80],[180,90],[0,90]
                 ]
             ],
             [
                 [
                     [0,90],[0,80],[-180,80],[-180,90],[0,90]
                 ]

             ]
         ]
     }
}
```

So for any Polygon that contains a pole, I need to preprocess it (and its holes) into a MultiPolygon?

**Comment by iverase** [comment]
Hey @brianalexander,

You cannot define a polygon encapsulating one of the poles. We are using internally cartesian mathematics to define polygon edges and therefore poles are not a singularity.
