### ISSUE TITLE
v8.0 service is running,but cant https test in localhost 

### ISSUE THREAD

**Issue by albertcoolsea** [elastic/elasticsearch#84008]
curl --cacert /etc/elasticsearch/config/certs/http_ca.crt -u elastic https://localhost:9200
Enter host password for user 'elastic':
xxxxx
curl: (77) Problem with the SSL CA cert (path? access rights?)

-----------
rpm install es v8.0 not generated file http_ca.crt.
maybe  file http_ca.crt  not exist result in the curl problem,how to generated the http_ca.crt  again? 
maybe some others reason result in the problem ,need your help .

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by albertcoolsea** [comment]
已收到您的邮件，谢谢。
