### ISSUE TITLE
[code readability improvement] Make SnowballAnalyzerProvider

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#84013]
### Elasticsearch Version

8.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

macos

### Problem Description

English analyzer in [SnowballAnalyzerProvider](https://github.com/elastic/elasticsearch/blob/master/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/SnowballAnalyzerProvider.java) uses the [static variable](https://github.com/elastic/elasticsearch/blob/master/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/SnowballAnalyzerProvider.java#L39) while other analyzers uses the [intuitive method](https://github.com/elastic/elasticsearch/blob/master/modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/SnowballAnalyzerProvider.java#L41) for the same, this reduces the code readability, we should make it consistent.

### Steps to Reproduce

None

### Logs (if relevant)

None

**Comment by amitmbm** [comment]
Would be fixing this in my PR.

**Comment by amitmbm** [comment]
@markharwood

**Comment by cbuescher** [comment]
Sorry to close this one, merge code readability changes are usually not regarded as bugs, see my comment in the PR with more information.
