### ISSUE TITLE
Aggregation support for scaled_float

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#84064]
### Description

Elasticsearch supports `scaled_float` data type that is floating point number backed by long. As we point out in our [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/number.html#_which_type_should_i_use) when you use `scaled_float` 

> [a]ll APIs would work as if the field was stored as a double, but under the hood Elasticsearch would be working with the number of cents, price*100, which is an integer. This is mostly helpful to save disk space since integers are way easier to compress than floating points. scaled_float is also fine to use in order to trade accuracy for disk space.

Unfortunately, the first part of this paragraph might be easily misinterpreted as `scaled_float` can help you to guarantee accuracy to a certain decimal point since internally we are working with integers. This is currently not the case when it comes to aggregations, that convert these integers to doubles immediately after retrieval and work with them as doubles. Here is a simple repro:

```
DELETE test

PUT test
{
  "mappings": {
    "properties": {
      "scaled_val": {
        "type": "scaled_float",
        "scaling_factor": 10
      },
      "val": {
        "type": "double"
      }
    }
  }
}


PUT test/_doc/1
{
  "scaled_val": 7.3,
  "val": 7.3
}

POST test/_search
{
  "size": 0,
  "aggs": {
    "max_scaled_val": {
      "max": {
        "field": "scaled_val"
      }
    },
    "max_val": {
      "max": {
        "field": "val"
      }
    }
  }
}

```

which returns a somewhat unexpected result even though no arithmetic operations were smilingly performed on the value

```
{
   .....
  "aggregations" : {
    "max_scaled_val" : {
      "value" : 7.300000000000001
    },
    "max_val" : {
      "value" : 7.3
    }
  }
}
```

It should be possible to teach the aggregation framework to work with scaled floats as integers as long as scale factors is the same across all indices that participate in the search and apply the scaling only at the end and make sure we round it up to the scaling factor bringing it closer to users' expectations.

**Comment by imotov** [comment]
We might want to consider addressing this as a part of a bigger effort in #60149

**Comment by wchaparro** [comment]
We discussed this as a team and for fintechs, financial institutions, there is a need to maintain precision for aggregations, so we'll add this to our roadmap for consideration. 
we'll plan to add #60149 (the more comprehensive plan) for roadmap consideration. –remove team discuss

**Comment by wchaparro** [comment]
Closing as not planned, would require significant effort in aggs framework, focus on ES|QL development
