### ISSUE TITLE
Getting SunCertPathBuilderException while verifying S3 repository

### ISSUE THREAD

**Issue by ssharma2089** [elastic/elasticsearch#84163]
I am using kubernetes elasticsearch deployment. I am trying to verify (https) MinIO S3 repository. After providing all the below details, getting SunCertPathBuilderException. 

PUT _snapshot/my_s4_repository?
{
"type": "s3",
"settings":{
"bucket": "archive",
"client": "default",
"endpoint": "minio.xxx.xxx.xxx",
"protocol": "https",
"path_style_access": "true"
}
}

### Error:
`"type" : "repository_exception",
    "reason" : "[my_s4_repository] Could not determine repository generation from root blobs",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "Exception when listing blobs by prefix [index-]",
      "caused_by" : {
        "type" : "sdk_client_exception",
        "reason" : "Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
        "caused_by" : {
          "type" : "s_s_l_handshake_exception",
          "reason" : "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
          "caused_by" : {
            "type" : "validator_exception",
            "reason" : "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
            "caused_by" : {
              "type" : "sun_cert_path_builder_exception",
              "reason" : "unable to find valid certification path to requested target"
            }
          }
        }
      }
    }
  },
  "status" : 500`

Provided below env variable for crt authorities 
- name: xpack.http.ssl.certificate_authorities
   value: /usr/share/elasticsearch/config/certs/cbundle.crt

Mounted the CRT in config location
- mountPath: /usr/share/elasticsearch/config/certs
   name: tls-cert 

I am not really knowing, what to do . I am stuck here. can anyone please help me with this.

**Comment by DJRickyB** [comment]
Hi! For general product help, please post on https://discuss.elastic.co
