### ISSUE TITLE
Match boolean prefix query documentation needs correction

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#84181]
### Elasticsearch Version

8.0

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

macos

### Problem Description

In [Match boolean prefix query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-bool-prefix-query.html), doc, its explained that the below query is 

```GET /_search
{
  "query": {
    "match_bool_prefix" : {
      "message" : "quick brown f"
    }
  }
}
```
Is similar to following query..
```
GET /_search
{
  "query": {
    "bool" : {
      "should": [
        { "term": { "message": "quick" }},
        { "term": { "message": "brown" }},
        { "prefix": { "message": "f"}}
      ]
    }
  }
}
```
Which is wrong, **as match queries are analyzed and goes through the analysis process while query shown with multiple bool caluses is using the term query which doesn't go through the analysis process**, so it should have been similar to below query.

```
GET /_search
{
  "query": {
    "bool" : {
      "should": [
        { "match": { "message": "quick" }},
        { "match": { "message": "brown" }},
        { "prefix": { "message": "f"}}
      ]
    }
  }
}
```

This can also be verified using the below sample documents

`DELETE testidx`

```
POST testidx/_doc/1
{
  "name": "quick brown fox"
}
```

```
POST testidx/_doc/2
{
  "name": "QUICK BROWN FOX"
}
```

but if we do the search using explain param it will show below search query terms are in lowercase, which means default **standard analyzer** is applied.

```
```
POST testidx/_search?explain=true
{
  "query": {
    "match_bool_prefix" : {
      "name" : "QUICK BROWN F"
    }
  }
}
```
Output of above query will be

```
"hits": {
        "total": {
            "value": 2,
            "relation": "eq"
        },
        "max_score": 1.3646431,
        "hits": [
            {
                "_shard": "[boolean][0]",
                "_node": "P5x_vmipSFyRhu8tK_bQiA",
                "_index": "boolean",
                "_type": "_doc",
                "_id": "1",
                "_score": 1.3646431,
                "_source": {
                    "name": "quick brown fox"
                },
                "_explanation": {
                    "value": 1.3646431,
                    "description": "sum of:",
                    "details": [
                        {
                            "value": 0.18232156,
                            "description": "weight(name:quick in 0) [PerFieldSimilarity], result of:",
                            "details": [
                                {
                                    "value": 0.18232156,
                                    "description": "score(freq=1.0), product of:",
                                    "details": [
                                        {
                                            "value": 2.2,
                                            "description": "boost",
                                            "details": []
                                        },
                                        {
                                            "value": 0.18232156,
                                            "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                                            "details": [
                                                {
                                                    "value": 2,
                                                    "description": "n, number of documents containing term",
                                                    "details": []
                                                },
                                                {
                                                    "value": 2,
                                                    "description": "N, total number of documents with field",
                                                    "details": []
                                                }
                                            ]
                                        },
                                        {
                                            "value": 0.45454544,
                                            "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                                            "details": [
                                                {
                                                    "value": 1.0,
                                                    "description": "freq, occurrences of term within document",
                                                    "details": []
                                                },
                                                {
                                                    "value": 1.2,
                                                    "description": "k1, term saturation parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 0.75,
                                                    "description": "b, length normalization parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "dl, length of field",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "avgdl, average length of field",
                                                    "details": []
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "value": 0.18232156,
                            "description": "weight(name:brown in 0) [PerFieldSimilarity], result of:",
                            "details": [
                                {
                                    "value": 0.18232156,
                                    "description": "score(freq=1.0), product of:",
                                    "details": [
                                        {
                                            "value": 2.2,
                                            "description": "boost",
                                            "details": []
                                        },
                                        {
                                            "value": 0.18232156,
                                            "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                                            "details": [
                                                {
                                                    "value": 2,
                                                    "description": "n, number of documents containing term",
                                                    "details": []
                                                },
                                                {
                                                    "value": 2,
                                                    "description": "N, total number of documents with field",
                                                    "details": []
                                                }
                                            ]
                                        },
                                        {
                                            "value": 0.45454544,
                                            "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                                            "details": [
                                                {
                                                    "value": 1.0,
                                                    "description": "freq, occurrences of term within document",
                                                    "details": []
                                                },
                                                {
                                                    "value": 1.2,
                                                    "description": "k1, term saturation parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 0.75,
                                                    "description": "b, length normalization parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "dl, length of field",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "avgdl, average length of field",
                                                    "details": []
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "value": 1.0,
                            "description": "name:f*",
                            "details": []
                        }
                    ]
                }
            },
            {
                "_shard": "[boolean][0]",
                "_node": "P5x_vmipSFyRhu8tK_bQiA",
                "_index": "boolean",
                "_type": "_doc",
                "_id": "2",
                "_score": 1.3646431,
                "_source": {
                    "name": "QUICK BROWN FOX"
                },
                "_explanation": {
                    "value": 1.3646431,
                    "description": "sum of:",
                    "details": [
                        {
                            "value": 0.18232156,
                            "description": "weight(name:quick in 0) [PerFieldSimilarity], result of:",
                            "details": [
                                {
                                    "value": 0.18232156,
                                    "description": "score(freq=1.0), product of:",
                                    "details": [
                                        {
                                            "value": 2.2,
                                            "description": "boost",
                                            "details": []
                                        },
                                        {
                                            "value": 0.18232156,
                                            "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                                            "details": [
                                                {
                                                    "value": 2,
                                                    "description": "n, number of documents containing term",
                                                    "details": []
                                                },
                                                {
                                                    "value": 2,
                                                    "description": "N, total number of documents with field",
                                                    "details": []
                                                }
                                            ]
                                        },
                                        {
                                            "value": 0.45454544,
                                            "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                                            "details": [
                                                {
                                                    "value": 1.0,
                                                    "description": "freq, occurrences of term within document",
                                                    "details": []
                                                },
                                                {
                                                    "value": 1.2,
                                                    "description": "k1, term saturation parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 0.75,
                                                    "description": "b, length normalization parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "dl, length of field",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "avgdl, average length of field",
                                                    "details": []
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "value": 0.18232156,
                            "description": "weight(name:brown in 0) [PerFieldSimilarity], result of:",
                            "details": [
                                {
                                    "value": 0.18232156,
                                    "description": "score(freq=1.0), product of:",
                                    "details": [
                                        {
                                            "value": 2.2,
                                            "description": "boost",
                                            "details": []
                                        },
                                        {
                                            "value": 0.18232156,
                                            "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                                            "details": [
                                                {
                                                    "value": 2,
                                                    "description": "n, number of documents containing term",
                                                    "details": []
                                                },
                                                {
                                                    "value": 2,
                                                    "description": "N, total number of documents with field",
                                                    "details": []
                                                }
                                            ]
                                        },
                                        {
                                            "value": 0.45454544,
                                            "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                                            "details": [
                                                {
                                                    "value": 1.0,
                                                    "description": "freq, occurrences of term within document",
                                                    "details": []
                                                },
                                                {
                                                    "value": 1.2,
                                                    "description": "k1, term saturation parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 0.75,
                                                    "description": "b, length normalization parameter",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "dl, length of field",
                                                    "details": []
                                                },
                                                {
                                                    "value": 3.0,
                                                    "description": "avgdl, average length of field",
                                                    "details": []
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "value": 1.0,
                            "description": "name:f*",
                            "details": []
                        }
                    ]
                }
            }
        ]
    }
```

### Steps to Reproduce

Explained in the issue.

### Logs (if relevant)

_No response_

**Comment by amitmbm** [comment]
@markharwood @cbuescher please take a look, I'm having PR ready to fix the sample boolean query with match cause.

**Comment by amitmbm** [comment]
Raised PR https://github.com/elastic/elasticsearch/pull/84182 please take a look, and let me know if you have any suggestions.

**Comment by jrodewig** [comment]
See related comment in https://github.com/elastic/elasticsearch/pull/84182#issuecomment-1055711599.
