### ISSUE TITLE
Move point in time setup to the transport layer?

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#84187]
Some parts of the point in time setup happen on the REST layer, see https://github.com/elastic/elasticsearch/blob/13390dd4d820834a4b0135bfb5d24618accb15f2/server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java#L373-L374 . This causes problems to consumers that call search directly at the transport layer. Either those consumers reploicate the same setup on their side before calling search, or that setup is shared and moved from the REST layer to `TransportSearchAction`?

In practice, this ends up causing EQL to hit all indices when using point in time, instead of the configured indices.

**Comment by javanna** [comment]
@dnhatn do you have opinions on how to proceed? The description of the issue includes two options, but maybe there are other ways.

**Comment by dnhatn** [comment]
Good find. Thanks @ywangd and @javanna. I've opened https://github.com/elastic/elasticsearch/pull/84202.

**Comment by javanna** [comment]
We decided not to proceed with this change, see https://github.com/elastic/elasticsearch/pull/84202#issuecomment-1072547030.
