### ISSUE TITLE
Add a 'timestamp' field mapper

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#84196]
### Description

Data streams and now TSDB have the notion of a timestamp field, which must be present in every document.  We currently are re-using a separately configured date field, but there are a whole bunch of configuration options on date mappers that don't apply here, and it would be useful to also have some per-document checks that the timestamps are a) present and b) single-valued.

We should create a separate `timestamp` field mapper, with a much more restricted set of configuration options.  If it is defined as a metadata mapper then we can also add post-parsing validation checks for presence and singularity (singleton-ness?), and data stream indexes and TSDB indexes can automatically inject it into mappings.  For searching, the mapper will produce a normal DateFieldType.

**Comment by xtxxtxxtx** [comment]
index metadata ha existed timestamp and used range for time correlation calculation。

**Comment by imotov** [comment]
@xtxxtxxtx could you clarify your comment?

**Comment by xtxxtxxtx** [comment]
Create index specify mapping and set @timstamp to enable. The new data is stamped with a time stamp. Using a LogStash for log collection, the LogStash field automatically adds @TIMESTAMP to events based on the current time of event transmission.


Use range to process the time field. The Range filter supports time calculation.
"range" : {
    "timestamp" : {
        "gt" : "now-1h"
    }
}

The time calculation can also specify a specific time, which can be achieved by adding a PIPE after the time.For example: find February 1, 2022 plus January
"range" : {
    "timestamp" : {
        "gt" : "2022-02-01 00:00:00",
        "lt" : "2022-02-01 00:00:00||+1M" 
    }
}

**Comment by martijnvg** [comment]
Most of this has been implemented in case for data streams. The `DataStreamTimestampFieldMapper` performs the validation checks that have been mentioned in the description. Except the validation around single valued timestamp. Today multiple timestamp fields are allowed. Changing this would be a breaking change. 

For now I don't think there is no need ensure the single valueless of the timestamp field. If this becomes important for storage or other reasons, then we will start start the process of making this breaking change. Closing for now.
