### ISSUE TITLE
how to get flattend value from function_score

### ISSUE THREAD

**Issue by reneix** [elastic/elasticsearch#84216]
I want to get flattend value from function_score, but 

zero hits  ---->   "source": "doc['shop_price.S500001'].value"
work well ---->   "source": "doc['base_price'].value"

any suggestion? thx

elastic version: 7.5.2
shop_price mapping as type flattened

doc:
{
  "sku_name": "SanDisk 2TB Extreme PRO Portable",
  "sku_id": "123456789",
  "base_price": 1500,
  "shop_price": { 
    "S500001":     1000,
    "S500002":     1100
  }
}

query:
{
  "query": {
    "function_score": {
      "query": {
        "match": { "sku_name": SanDisk" }
      },
      "script_score": {
        "script": {
          "params": {
            "shop_id": "S500001",
            "b": 1.2
          },
          "source": "doc['shop_price.S500001'].value"
        }
      },
      "boost_mode": "replace"
    }
  }
}

**Comment by gaojiabao1991** [comment]
You can try to change :
`doc['shop_price.S500001'].value` to `_source.shop_price.S500001'`.

But this can be slower than using doc-values(doc[xxx]).

some summary of elasticsearch document:

> The document [_source] can be accessed using the _source.field_name syntax. The _source is loaded as a map-of-maps, so properties within object fields can be accessed as, for example, _source.name.first.

> Accessing the _source field is much slower than using doc-values. The _source field is optimised for returning several fields per result, while doc values are optimised for accessing the value of a specific field in many documents.

you can read this for more infomation: 
[https://www.elastic.co/guide/en/elasticsearch/reference/8.0/modules-scripting-fields.html#modules-scripting-doc-vals](url)

**Comment by reneix** [comment]
@gaojiabao1991 thx,I have located the problem.
when using flattened type, 1000 was saved as string, not long or double.
doc['shop_price.S500001'].value returned string, but in function_score, a double return was expected.
so getting value from flattened type works well.

will close this issue.

**Comment by vasylsenko** [comment]
@reneix can you share how you make it work, flattened type always returns a string, are you able to use flattened type with function_score?
