### ISSUE TITLE
Performance issues when large number of indices used

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#8425]
See this thread for more details

https://groups.google.com/forum/#!topic/elasticsearch/cJ2Y6-KQZus

Basically, when there is a large number of indices system performance degrades dramatically.  We reproduced this in a simple YCSB test case that connects to a remote system.  In my case I had 4200 indices created.  Looking at a heap dump, we found that there were 42,890 instances of IndexRoutingTable and 128,630 instances of IndexShardRoutingTable.

**Comment by jpountz** [comment]
Closing: too many indices will cause various problems anyway.
