### ISSUE TITLE
Do boolean fields really need to index doc values?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#84303]
### Description

`boolean` fields currently index terms (`T` for true and `F` for false) and numeric doc values (0 for false and 1 for true).

I wonder if we really need to index doc values. It would be possible to recompute them from postings lists for `T` and `F`? E.g. an `exists` query would be a disjunction over "`T` OR `F`" and for bucketing via aggregations, we could check the `T` and `F` postings lists to check what the value for a given document is.

**Comment by ywelsch** [comment]
What about sorting, or script access?

**Comment by jpountz** [comment]
Sorting and script access build on top of the fielddata API, so hopefully it should work transparently.

Now that your question forced me to think a bit more about implications, I think that two issues would be:
 - Index sorting doesn't support custom values sources, so it wouldn't work.
 - Archives wouldn't be able to lean on doc values.

**Comment by jpountz** [comment]
Closing for now as it's not straightforward.
