### ISSUE TITLE
Use JSONPath syntax for aggregation paths

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#8434]
@jpountz  pointed out that we could use JSONPath to define paths to properties in aggregations. This would be a new syntax and would replace the old `a>b.c` style syntax. We could add a config option to enable the older syntax for bwc. The new syntax would allow for complex aggregation paths for use in reducers to, for example, get properties from a particular bucket in an aggregation, or retrieve all the values of the property `c` in all the buckets even if c is three levels down the aggregation tree. It would also give a standard way to access the root of the agg tree (with '$').

for reference see: http://goessner.net/articles/JsonPath/

**Comment by colings86** [comment]
After looking at JSONPath it's not 100% good fit for aggregation paths and there are other efforts looking at JSONPath-like functionality elsewhere in the product, so closing this for now

**Comment by thomax** [comment]
> After looking at JSONPath it's not 100% good fit for aggregation paths and there are other efforts looking at JSONPath-like functionality elsewhere in the product, so closing this for now
Have any of these other efforts given results? JSONPath or JSONPath-like functionality would be very useful to me, so I'd be very interested to hear about this.

**Comment by colings86** [comment]
So far just response filtering has been implemented (https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering) which uses a simplified syntax for referencing paths in JSON.
