### ISSUE TITLE
Have `random_sampler` know when sampling would be much slower and skip sampling

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#84353]
### Description

There are various scenarios when sampling would be actually slower than simply gathering the aggregated data.

Here they are:

 - top-level terms agg (with no sub-aggs) over a `match_all` query with no deleted docs. 
 - [x] https://github.com/elastic/elasticsearch/issues/85110 
 - top level value_count agg with `match_all` and no deleted docs

In these situations, the `random_sampler` should intelligently skip sampling altogether and allow the sub-aggregations to calculate in their optimized paths. This will likely require changes to the sub-aggs (to consider being a sub-agg to the random-sampler the same as "top-level") and to the random_sampler aggregation.

**Comment by benwtrent** [comment]
A key problem here is auto scaling of values. Right now, values are scaled on the coordinating node AFTER final reduction. This causes an issue if there is an "optimized path" on a given shard.

Consider the following for an optimized `terms` aggregation and its `doc_count`:

 - shard A has deleted documents, so it cannot use the optimized path and the sampler executes as normal (thus its count is approximately `probability * "the true doc count"`.
 - shard B has NO deleted docs, uses the optimized path, so the aggregation returned from that shard has `"true doc count"` (but its much faster than sampling).
 - Now when these are merged and then scaled, your count is going to be much higher than expected (because shard B wasn't sampled).


I think the solution is one of the following:

 - Solution 1: Scale values at the shard level (so that shard A returns "sampled count" * 1/probability for merging)
 - Solution 2: Scale unsampled values down by the probability (e.g. scale shard B by "true doc count" * probability).

I prefer solution 1. Mathematically, `x(y1 + y2 + y3 + y4 ... yN)` == `xy1 + xy2 + ... xyN` so scaling up these count values (which will also effect `sums`) at the shard should be acceptable.

**Comment by tveasey** [comment]
Another advantage of 1 is we would presumably round values for count when we scale down so you lose some precision.

I don't think this process necessarily introduces bias. However, for example, if you were doing something like a mean, where one shard sampled and one didn't, you would ideally adjust the weighting when combining values to account for actual sample sizes. It sounds like overall mean statistics are not available at the shard level and so this is currently moot.

**Comment by benwtrent** [comment]
@tveasey correct, the idea of "mean" being optimized isn't being considered right now.

The internal design may be a big of an issue. I can dig around to see what it looks like.

**Comment by benwtrent** [comment]
From what I can tell, the internal implementation will have to add a new function to the `Aggregator` class.

```
public InternalAggregation[] buildAggregations(long[] owningBucketOrds, SamplingContext) throws IOException {
```

Default impl would be throw Unsupported. 

Then all the aggregations that support sampling will have to be updated to handle their scaling on the shard level when they build their InternalAggregation classes.

For some aggs, this may prove easier (some multi-bucket buckets that inherit from a parent class and the scaling can be handled there). Others (looking at you Rare terms, categorize text, etc.) use more unique execution paths that will have to satisfy the function.

**Comment by wchaparro** [comment]
Closing as not planned for Aggs, focusing on ES|QL development. Feel free to reopen/reassign as needed.
