### ISSUE TITLE
Support splitting Groups list in SAML

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#84379]
### Description

Our SAML realm has a setting `attribute.groups` that tells the realm which SAML attribute contains the list of "groups" that the user belongs to.
(Note: "groups" here is a generic term, carried over from the LDAP realm. The SAML IdP might refer to this attribute as "roles" or "teams" or something else entirely).

Because SAML supports multi-valued attributes (example below) we assume that each group will be listed as a distinct value.
```
 <saml:Attribute NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
       Name="http://idp.example.org/attributes/groups" FriendlyName="groups">
       <saml:AttributeValue>engineering</saml:AttributeValue>
       <saml:AttributeValue>elasticsearch-admins</saml:AttributeValue>
       <saml:AttributeValue>employees</saml:AttributeValue>
</saml:Attribute>
```
However, it appears some IdPs are incapable of sending the groups list as a list of values and will only ever send it as a comma separated string.
```
 <saml:Attribute NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
       Name="http://idp.example.org/attributes/groups" FriendlyName="groups">
       <saml:AttributeValue>engineering,elasticsearch-admins,employees</saml:AttributeValue>
</saml:Attribute>
```

We currently require that the cluster security admin create a regex based role mapping rule to match on something like `^(.*,)?elasticsearch-admins(,.*)?$` which is non-obvious, cumbersome and error-prone.

An alternative would be to add a setting like `attribute.groups_split: ","` to automatically split a comma separated string into a
real list.  
This would be a reflection that real world IdPs don't always do a good job of conforming with the intent of the SAML spec, and our need to work within their limitations.

**Comment by bytebilly** [comment]
Thanks Tim, I like the approach to make UX better. Do you have a feeling on how common the single-value scenario is, or if it affects common IdP?

Related question: is `,` an allowed character for group names? If not, should we automatically detect and support comma-separated values without requiring the admin to configure a new option?

**Comment by jkakavas** [comment]
> Do you have a feeling on how common the single-value scenario is, or if it affects common IdP?

I don't know of this to be a limitation of any well-known (or even just commonly used) IdP implementations. I think this is mostly a configuration issue on the IdP administration side, rather than a software limitation. I agree with the arguments around doing something about this, nevertheless. 

> If not, should we automatically detect and support comma-separated values without requiring the admin to configure a new option?

`,` is a reserved char in LDAP so in many cases if it exists in an group value name, it will be escaped such as `\,`. But not all IdPs use LDAP as a user repository so there is no universal answer I think. Even if there are just a few that already use commas as part of a groups value, this would be a breaking change with unintended AuthZ consequences. I don't believe this is the right trade-off to make.

**Comment by tvernum** [comment]
We discussed. No one had any objection (though we also didn't think it was urgent).

One question was whether this behaviour should exist as a realm setting (proposed above) or a role mapping rule (split field then match).
We agreed that putting it in the realm is more useful because that would mean it is stored as a list in the user metadata, which will be more useful for DLS query templates.

**Comment by tvernum** [comment]
We also agreed, if we do this, that the split should be done in a simple, naive fashion.

That is, we always split on the configured string (to be decided if it's a plain string, or a regexp) and don't worry about escaping, quoting, etc.
If you need more than that, you'll need to fix it on the IdP side.

**Comment by gavaliamol** [comment]
we really think we need this feature to split the idp groups based on delimiter i.e. comma  and populate _user.metadata.groups metadata attribute as list or array so that we can use them in role mapping or role as templates.

**Comment by jfreden** [comment]
Resolved in: https://github.com/elastic/elasticsearch/pull/102769

**Comment by bytebilly** [comment]
No, this new setting applies to SAML realms only.
