### ISSUE TITLE
What is the upper limit of a document in a single index

### ISSUE THREAD

**Issue by qq1045561395** [elastic/elasticsearch#84382]
In a single index, the upper limit of the document is Integer.MAX_ VALUE?
Because when I add data, there is an error after approaching this value, so I can't add data.

**Comment by ddolcimascolo** [comment]
Hi @qq1045561395

This is a Lucene hard limit. It used to be documented but I can't seem to find it in the docs. See #9932 for instance.

The thing is, it's a limit per _shard_ not per index. I believe your index was created with default settings, which include only 1 primary shard. Should you need to go beyond that limit, you just need to index your data to an index with more shards!

Cheers,
David

**Comment by DJRickyB** [comment]
For general product help or questions, please post at https://discuss.elastic.co
