### ISSUE TITLE
ArchiveGenerateInitialCredentialsTests failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#84407]
In ArchiveGenerateInitialCredentialsTests, we try to capture the output of a node starting in order to validate that the security auto-configuration information is actually printed out and is correct. 
It turns out that the way we run the tests in CI is not compatible to how we try to determine whether there is a terminal attached to elasticsearch. Since we can't determine if a terminal is attached, we do not print the information and thus the tests fail. 

Originally, I assumed that this is because of how we run elasticsearch with `expect`, or because our use of `spawn` but the failure doesn't replicate locally. i.e. I can run

```
expect - <<EXPECT
set timeout 30
spawn -ignore HUP bin/elasticsearch
expect {
   "uncaught exception" { send_user "\nStartup failed due to uncaught exception\n"; exit 1 }
   timeout { send_user "\nTimed out waiting for startup to succeed\n"; exit 1 }
   eof { send_user "\nFailed to determine if startup succeeded\n"; exit 1 }
   "Configure other nodes to join this cluster*"
}
EXPECT
```

which is what we effectively do in https://github.com/elastic/elasticsearch/blob/master/qa/os/src/test/java/org/elasticsearch/packaging/util/Archives.java#L235 

and elasticsearch will print out the auto-configuration information and expect will exit after seeing `Configure other nodes to join this cluster` in the output. 

In CI, https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java#L197 , console is null and so we elect to not print out the security information. We need to determine why that happens. 

Tagging with the delivery team too, in case they have some insights :pray:

**Comment by pugnascotia** [comment]
We could start with `AnsiConsoleLoader.isValidConsole()`. It might be deciding that in CI, the console isn't usable and therefore returning null.

**Comment by tvernum** [comment]
How would we feel about adding a system property like `-Des.force_stdout_is_console=true` so we can test the console output when we need to.

**Comment by mark-vieira** [comment]
This test hasn't failed in the past 30 dyas. Looks like this has been resolved.
