### ISSUE TITLE
log4j configuration for slow log files(search and index) is removed in ES 8.0 ?

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#84405]
### Elasticsearch Version

8.0

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

We are using the text format not the JSON format to log our search and indexing slow logs, but I noticed that in ES 8.0 I am getting these logs only in JSON format, I researched more around the changes and found logging configuration for the text bases logging was removed as part of [this PR](https://github.com/elastic/elasticsearch/pull/47105) but in [its related issue](https://github.com/elastic/elasticsearch/issues/46119) it wasn't mentioned that these changes are meant to remove the support of text-based logging of slow search/index ? 
I also tried to find out other official documentation like the [release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.0.0-alpha1.html) and [all release notes of 8](https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html) but couldn't find the reasoning to remove them.

### Steps to Reproduce

1. Define the search slow log settings of any index created in ES 8.0
2. Go to logs folder and you will notice only the JSON search slow log file is generated not the text one.

**Comment by amitmbm** [comment]
It was removed in 8.0 and added a note in the https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrating-8.0.html but missing in the release notes? 
Shouldn't we add this in the release docs as well? Let me know if we should add that and I would be happy to open a PR for it.

**Comment by amitmbm** [comment]
@pgomulka could you please take a look at it?

**Comment by pgomulka** [comment]
hi @amitmbm 
you can find the release notes mentioning about the change of JSON format to comply with ECS here 
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.0.0-alpha1.html
