### ISSUE TITLE
Create a Github CODEOWNER file

### ISSUE THREAD

**Issue by jlind23** [elastic/elasticsearch#84414]
### Description

We, the Elastic Agent team, would like to have a Github CODEOWNER file setup in order to be notified as soon as there is a PR trying to modify something we own.
It can be either fleet* indices or some java code.
Examples:
- https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/fleet-policies.json
- https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet

cc
@ph

**Comment by mark-vieira** [comment]
> It can be either fleet* indices or some java code.

@jlind23 would this be easily limited to examples you show or is it possible this could be done elsewhere in the codebase? I think if we can narrow this down to very specific bits of code I don't have strong objections about adding a CODEOWNER file, other that we'd want to communicate this to the team around what expectations are around merging said code.

**Comment by jlind23** [comment]
@mark-vieira very specific bits of code can not be owned with a CODEOWNER file, it is only for files or folders. So i do not think that there is any other out of the box mechanism for this.

Purpose is to automatically communicate changes that may occur on code that you own in order to avoid silent changes.

**Comment by mark-vieira** [comment]
> @mark-vieira very specific bits of code can not be owned with a CODEOWNER file, it is only for files or folders. So i do not think that there is any other out of the box mechanism for this.

Of course, when I said "specific bits" I meant narrowing this down to a set of files or folders. Are the examples you mention above an exhaustive list of these assets?

**Comment by jlind23** [comment]
Nope, it should rather be like this:
- https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/core/src/main/resources/fleet-*
- https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet all this folder content.

**Comment by mark-vieira** [comment]
I don't have any objection to this. As mentioned, we'd want to nail down expectations and process here. As I understand it the CODEOWNERS configuration will automatically add a team/person as a reviewer to any PRs that modify those assets. Should it be expected that merging that PR is _blocked_ until the agent team gives the 👍?

**Comment by jlind23** [comment]
There is two options:
- The Elastic Agent team is assigned as reviewer but that review can be optional. It will work more or less like a ping
- The Elastic Agent team is assigned as reviewer but that review becomes mandatory, this will be real ownership.

Both work for me, i'm just scared about the second one being potentially a bottleneck.

@ph @pierrehilbert thoughts?

**Comment by mark-vieira** [comment]
Closed by #85532.

**Comment by jlind23** [comment]
@mark-vieira i do not see any changes regarding the fleet-* resources in the PR you linked. Am i missing something?

**Comment by mark-vieira** [comment]
Sorry @jlind23, I closed this prematurely. Feel free to submit a PR for the assets you'd like the agent team pinged on.
