### ISSUE TITLE
Unable to Calculate score of Phrase Suggester - Direct Candidate Generator

### ISSUE THREAD

**Issue by mukeshdantuluri** [elastic/elasticsearch#84432]
Hi Team,

I am using phrase suggester for spell corrections and observed term frequency of Co-occurrence playing a major role in the suggestion. This is causing issue for Unigram searches where string distance is important than frequency.

while trying to replicate the score from formulae , unable to match the score generated by elasticsearch.

Using the below formulae from :
`errorScore * (((double) termStats.totalTermFreq + 1) / ((double) dictionarySize + 1))`
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java#L241
Line no : 241

Can you please help in correctly replicating the score from the formulae which can help us in using custom scripting (`painless`)
which can suite our requirements.

**Comment by DJRickyB** [comment]
Hi! Please direct any product help questions to our forums at https://discuss.elastic.co
