### ISSUE TITLE
Telemetry: track remote clusters usage

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#84482]
We currently track no information about CCS usage. We don't have the infra to track searches at the coordinator level and report back on remote indices usages, but one thing we could do is start by tracking how many remote clusters are registered. Although that gives no indication about the amount of requests each cluster receives and whether they are used through CCS or CCR or both, it is a starting point to at least monitor how widely remote clusters are configured.

**Comment by linyaru** [comment]
CCR usage stats are currently picked up by the X-pack details usage collector in Kibana: https://github.com/elastic/kibana-team/blob/master/telemetry.md#usage-collector-categories and are available via `GET /_xpack/usage`

I think it makes sense to expose remotes in the same way; Kibana's snapshot telemetry would be able to pick this up with relatively little effort (i.e. not adding a new collector).

**Comment by javanna** [comment]
Implemented by #94862 .
