### ISSUE TITLE
elasticsearch 1.4.0 hanging with rivers starting up

### ISSUE THREAD

**Issue by ankon** [elastic/elasticsearch#8448]
The elasticsearch-river-mongodb river tries to query elasticsearch whether a specific index already exists in its `#start()` method. If there are many of those rivers elasticsearch's startup essentially hangs: all threads in the 'listener' pool are used by the `RiversService#createRiver()` method, and the listener for the 'indexExists' call never gets executed.

A full thread is available at https://gist.github.com/ankon/e000198100ce3d52cb3b#file-thread-dump-txt, and the issue is filed also in the elasticsearch-river-mongodb project: https://github.com/richardwilly98/elasticsearch-river-mongodb/issues/406

Some questions:
1. What is the proper behavior of a river inside `#start()`, in particular: is it allowed to use the elasticsearch client? Should it do anything special when invoking methods on it?
2. Where is the best place for documenting these requirements?

**Comment by clintongormley** [comment]
Given that rivers have been removed in master, I'm going to close this one.
