### ISSUE TITLE
Make vector tile buffer size configurable

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#84492]
Vector tiles buffer is used to include data that is just outside of the tile. This data is used to prevent border effects when rendering the geometries. It is currently [hardcoded to 5 pixels](https://github.com/elastic/elasticsearch/blob/de2781f98696c1e6cfad2b5bf46fe752a5e3edbb/x-pack/plugin/vector-tile/src/main/java/org/elasticsearch/xpack/vectortile/feature/FeatureFactory.java#L63) but it should probably need to be user configurable by adding a new property on the vector tiles API which can change the value.

**Comment by craigtaverner** [comment]
Part of this work was done in https://github.com/elastic/elasticsearch/pull/84710
