### ISSUE TITLE
centos 8 stream  elasticsearch

### ISSUE THREAD

**Issue by nzubarev122** [elastic/elasticsearch#84550]
### Elasticsearch Version

8.0.1-1

### Java Version

openjdk version "1.8.0_322" OpenJDK Runtime Environment (build 1.8.0_322-b06) OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

### OS Version

CentOS Stream release 8

### Problem Description

Elasticsearch won't start with error

### Steps to Reproduce

Hello.

Elasticsearch won't start with error.  Please help

config
xpack.security.enabled: false
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

### Logs (if relevant)

:SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
Mar 02 10:03:55 logger-app01a.infra.hostkey.ru logstash[1549]: [2022-03-02T10:03:55,049][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{"other"=>[{"thread_id"=>34, "name"=>"[main]<rabbitmq", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-integration-rabbitmq-7.3.0-java/lib/logstash/inputs/rabbitmq.rb:278:in `block in push'"}, {"thread_id"=>32, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/interval.rb:95:in `sleep'"}, {"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/interval.rb:95:in `sleep'"}]}}
Mar 02 10:03:55 logger-app01a.infra.hostkey.ru logstash[1549]: [2022-03-02T10:03:55,192][INFO ][logstash.outputs.elasticsearch][main] Failed to perform request {:message=>"Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)", :exception=>Manticore::SocketException, :cause=>org.apache.http.conn.HttpHostConnectException: Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)}
Mar 02 10:03:55 logger-app01a.infra.hostkey.ru logstash[1549]: [2022-03-02T10:03:55,192][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}

**Comment by pugnascotia** [comment]
@nzubarev122 those lots appear to be from Logstash. We will need the Elasticsearch output in order to diagnose what is happening.

**Comment by nzubarev122** [comment]
> @nzubarev122 those lots appear to be from Logstash. We will need the Elasticsearch output in order to diagnose what is happening.

logstash[2420]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

input {
 rabbitmq {
	host => "localhist"
        queue => "syslog"
        heartbeat => 30
        durable => true
        password => "passwd"
        user => "test"
    }
}


filter {
  # your filters here
}

output {
  elasticsearch { hosts => ["localhost:9200"]
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
#    ssl => false
#    ssl_certificate_verification => false
  }
}

**Comment by pugnascotia** [comment]
@nzubarev122 Your question is better suited to the support forums over at https://discuss.elastic.co/. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
