### ISSUE TITLE
Repository GCS Plugin makes the elasticsearch crash on startup when client's proxy settings are specified in elasticsearch.yml.

### ISSUE THREAD

**Issue by jlr-sharma-yash** [elastic/elasticsearch#84569]
### Elasticsearch Version

8.0

### Java Version

_bundled_

### OS Version

win10

### Problem Description

I am using GCP plugin with Elasticsearch 8.0 and it seems that the settings that are specified in the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/repository-gcs.html) are not available to use in Elasticsearch. I have further gone into investigation to investigate GCS repository plugin and below are my observations:
The settings are declared in GoogleCloudStorageClientSettings.java class [here](https://github.com/elastic/elasticsearch/blob/690bac5dc375b5a1e8f6b3b091d38ee6cdeb0b05/modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageClientSettings.java#L101) but they are not loaded in the implementation getSettings() method [here](https://github.com/elastic/elasticsearch/blob/690bac5dc375b5a1e8f6b3b091d38ee6cdeb0b05/modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePlugin.java#L66).
Due to this elasticsearch.bat is throwing error and exiting instead of starting Elasticsearch.

### Steps to Reproduce

1. Specify the below settings in elasticsearch.yml:
gcs.client.default:
  proxy.host: "abc.com"
  proxy.port: 80
  proxy.type: "http"
2. Start elasticsearch.bat and this will generate **java.lang.IllegalArgumentException: unknown setting [gcs.client.default.proxy.host] please check that any required plugins are installed, or check the breaking changes documentation for removed settings** followed by exiting the bat script.

### Logs (if relevant)

@KarenSumner @liladler Could you please help prioritize of fixing this bug?
<img width="947" alt="elastic_bug" src="https://user-images.githubusercontent.com/100778274/156373380-203706a9-ad1d-423d-a51f-4c40189f6c92.PNG">

**Comment by liladler** [comment]
Hi @arteam, @jlr-sharma-yash tried to test the new support for proxy settings and seeing the following issue. 
Is there anything missing? any thoughts?
