### ISSUE TITLE
Change api request timeout

### ISSUE THREAD

**Issue by gerardgorrion** [elastic/elasticsearch#84577]
### Description

We try to do some reindex process and the curl to do it always was stopped at 59s with code error 52. Is there some way to change this timeout to wait all reindex process? thanks,

**Comment by xtxxtxxtx** [comment]
What is the background of the question?
I understand that reindex can do some simple things.
However, if the amount of data and the number of fragments are large, reindex takes a certain amount of time. Reindex allows background processes to run without affecting other work.

If there is any deviation from the author's understanding, welcome to discuss and learn together. Thank you very much！

**Comment by nik9000** [comment]
> We try to do some reindex process and the curl to do it always was stopped at 59s with code error 52. Is there some way to change this timeout to wait all reindex process? thanks,

Elasticsearch doesn't have a timeout on reindex. But proxies between Elasticsearch and the client do. So you should set [wait_for_completion=false](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-task-api) on your request. 

This isn't a bug or enhancement so much as a "how do I use Elasticsearch?" question and those really belong on https://discuss.elastic.co/ .
