### ISSUE TITLE
Support GeoJson on geo_point fields

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#84599]
geo_point field does not support GeoJson which can be a PITA if your data is in such a format. Indexing it as a geo_shape is an option but very wasteful.

**Comment by craigtaverner** [comment]
Related to https://github.com/elastic/elasticsearch/issues/47535

**Comment by craigtaverner** [comment]
Related to https://github.com/elastic/elasticsearch/issues/47815

**Comment by craigtaverner** [comment]
Docmentation added in https://github.com/elastic/elasticsearch/pull/86066 which will come out in 8.3.0 together with GeoJSON support for the cartesian point, done in https://github.com/elastic/elasticsearch/pull/85442
