### ISSUE TITLE
Long.MIN_VALUE considered out of range for type long in range aggregations, even when values passed as JSON strings

### ISSUE THREAD

**Issue by yrodiere** [elastic/elasticsearch#84601]
### Elasticsearch Version

8.0.1

### Java Version

_bundled_

### OS Version

Linux yrodiere.redhat 5.16.9-200.fc35.x86_64 #1 SMP PREEMPT Fri Feb 11 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

NOTE: This is *not* a duplicate of #81529. This is a regression in Elasticsearch 8.0.1. The bug first appeared in 7.16.0 (#81529), but [there was still a workaround](https://github.com/elastic/elasticsearch/issues/81529#issuecomment-994466914): passing long values as strings in the JSON of the search request. As of 8.0.1, the bug affects longs whether they are represented as longs or strings; there is no longer any workaround.

When defining a range aggregation on a field of type `long`, if one of the ranges has a bound equal to `Long.MIN_VALUE` (the java constant, equal to `-(2^63)`) or just a bit higher, and even when passing that value as a JSON string to work around #81529, Elasticsearch raises an error:

```
"Value [-9.223372036854776E18] is out of range for a long"
```

This directly contradicts the [documentation of numeric types](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) which states that a `long` is "A signed 64-bit integer with a minimum value of -2^63 and a maximum value of 2^63-1"

It is a regression compared to 8.0.0, which didn't raise such an error.

### Steps to Reproduce

```
curl -XDELETE -H "Content-Type: application/json" 'localhost:9200/test/' || true
echo
curl -XPUT -H "Content-Type: application/json" 'localhost:9200/test/' -d'{"mappings": {"properties": {"mylong": {"type": "long" } } } }'
echo
curl -XPUT -H "Content-Type: application/json" 'localhost:9200/test/_doc/1?refresh=true' -d '{"mylong": -9223372036854775808 }'
echo
curl -XPOST -H "Content-Type: application/json" 'localhost:9200/test/_search?size=0&pretty' -d '{"query":{"match_all":{}},"aggregations":{"myagg":{"range":{"field":"mylong","ranges":[{"from":"-9223372036854775808","to":"9223372036854775807"}]}}}}'
```

Output of the last command with Elasticsearch 8.0.1:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Value [-9.223372036854776E18] is out of range for a long"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test",
        "node" : "FGgeIHlNTd2ixi5XUcLtFw",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Value [-9.223372036854776E18] is out of range for a long"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Value [-9.223372036854776E18] is out of range for a long",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "Value [-9.223372036854776E18] is out of range for a long"
      }
    }
  },
  "status" : 400
}
```

Output of the last command with Elasticsearch 8.0.0:

```json
{
  "took" : 17,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "myagg" : {
      "buckets" : [
        {
          "key" : "-9.223372036854776E18-9.223372036854776E18",
          "from" : -9.223372036854776E18,
          "to" : 9.223372036854776E18,
          "doc_count" : 1
        }
      ]
    }
  }
}

```

**Comment by wchaparro** [comment]
@salvatore-campagna can you take a look pls?

**Comment by yrodiere** [comment]
@salvatore-campagna it seems Elasticsearch 7.17.7 is affected as well. Just giving you a heads-up so you can reopen this ticket if you deem it necessary.

**Comment by yrodiere** [comment]
For what it's worth, 7.17.8 is affected too.
