### ISSUE TITLE
Possible problem with Fast Vector Highlighter + Multi-Fields between 7.10.2 and 7.16.3

### ISSUE THREAD

**Issue by Mrodent** [elastic/elasticsearch#84690]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Linux (Mint 20), W10

### Problem Description

The same mappings and query DSL dict which work fine to produce multi-word, multi-colour highlighting in v 7.10.2 don't seem to work with v 7.16.3: on both Linux and W10 I have had to revert to 7.10.2. I'd love it if an expert could check on what's going on: maybe there has been a substantive documented change between the two ES versions.

I had a look at the latest version (8.0) for this [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html), but nothing jumped out at me. However, in the section on fvh and multi-fields I noticed that nothing was said about using `pre-tags` and `post-tags`. The point about my example is that different terms are highlighted with different colours (in fact backgrounds).

I have [posted this](https://discuss.elastic.co/t/multi-field-mapping-search-highlighting-difference-between-7-10-2-and-7-16-3/298739) in the ES forum. No replies after a few days, hence my opening of an issue here.

### Steps to Reproduce

Given this mapping:

```
       mappings = \
        {
          "mappings": {
            "properties": {
              "esdoc_text": {
                "type": "text",
                "term_vector": "with_positions_offsets",
                  "fields": {
                    "stemmed": {
                      "type": "text",
                      "analyzer": "english",
                      "term_vector": "with_positions_offsets",
                    }
                  }
                }
              }
            }
          }

```
and this query DSL dict:

```
       data = \
        {
          'query': {
            'simple_query_string': {
              'query': self.search_string,
              'fields': [
                self.text_field
                
              ]
            }
          },
          'highlight': {
            'fields': {
              self.text_field: {
               'type': 'fvh',
               'pre_tags': [
                    '<span style="background-color: yellow">',
                    '<span style="background-color: skyblue">', 
                    '<span style="background-color: lightgreen">', 
                    '<span style="background-color: plum">', 
                    '<span style="background-color: lightcoral">', 
                    '<span style="background-color: silver">',
                ],
               'post_tags': [
                    '</span>', '</span>', '</span>', 
                    '</span>', '</span>', '</span>', 
                ]
              }
            },
            'number_of_fragments': 0
          }
        }

```
... I get beautiful highlighted results using 7.10.2. But using 7.16.3, the hits are returned, but there is no "highlight" key at all in the returned response.json().

NB in the above, clearly and as one might surmise from the mapping, `self.text_field` is set to either "esdoc_text" (for standard analyser results) or "esdoc_text.stemmed" (for english stemmer analyser results).

**Comment by jtibshirani** [comment]
@romseygeek would you be up for looking at this since you're very familiar with #74348 and the highlighting code?

**Comment by Mrodent** [comment]
Thanks for the confirm. Will keep an eye-out for progress.

**Comment by Mrodent** [comment]
Proposing to re-open this. Finally got around (2 years later) to trying this FVH multi-colour highlighting with version 8.6.2 and then version 8.13.1. According to my experiments this is still NOT WORKING and thus the regression has NOT been fixed. I may have this wrong, but I believe romseygeek fixed some other bug which was assumed to be identical with this one.

But this does not appear to be the case.

More details of the errors received using 8.6.2 and 8.13.1 can be found [here](https://discuss.elastic.co/t/what-might-be-wrong-with-this-attempt-to-highlight-es-results/356918):

error:
```
request failed. URL |https://localhost:9500/dev_my_documents/_search| command get deliverable.failure_reason unacceptable status code: 400
    reason: [1:501] [highlight] failed to parse field [fields]

```
failure response's json: 

```
    {
      "error": {
        "root_cause": [
          {
            "type": "x_content_parse_exception",
            "reason": "[1:500] [highlight_field] failed to parse field [post_tags]"
          }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:500] [highlight] failed to parse field [fields]",
        "caused_by": {
          "type": "x_content_parse_exception",
          "reason": "[1:500] [fields] failed to parse field [text_content.stemmed]",
          "caused_by": {
            "type": "x_content_parse_exception",
            "reason": "[1:500] [highlight_field] failed to parse field [post_tags]",
            "caused_by": {
              "type": "json_e_o_f_exception",
              "reason": "Unexpected end-of-input in VALUE_STRING\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 504]"
            }
          }
        }
      },
      "status": 400
    }
```

Of course it may be that this "FVH" query now has to phrased in a different way with 8.13.1. Please enlighten me if so.

**Comment by Mrodent** [comment]
After studying the latest docs I see that you do (apparently) have to tweak the grammar slightly. I find that this works:

```
'highlight': {
    'fields': {
        'text_content.stemmed': {
            'matched_fields': ['text_content.stemmed'],
            'type': 'fvh',
            'pre_tags' : ['<span style="background-color: yellow">', '<span style="background-color: skyblue">', ], 
            'post_tags' : ['</span>', '</span>', ],
        }
    },
}

```

... the key being to add this extra "matched_fields" field ...
