### ISSUE TITLE
Performance slowdown on high cardinality keyword fields - enhancement opt out of terms dictionary compressing

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#84721]
### Elasticsearch Version

7.14.0 and higher

### Problem Description

Segment files created since 7.14.0 are slower for cardinality aggregation on high cardinality (keyword) fields. This is potentially a side effect of https://issues.apache.org/jira/browse/LUCENE-9663 where compression was introduced for terms dictionary

The current issue is to discuss introducing some setting to opt out of this compression

### Steps to Reproduce

1. In 7.13.4, create the following index :
```
PUT test7134
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date",
        "format": "strict_date_optional_time"
      },
      "foo": {
        "type": "keyword"
      }
    }
  },
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "0"
    }
  }
}
```

2. Using logstash add 3 million docs with around 1 million distinct values (optionally set `pipeline.batch.size: 2000` to speed up the test): 
```
input
{
 generator
  {
     id => "generator1" 
     count => 3000000
  }
}
filter {
    mutate {
        id => "mutate1"
        remove_field => [ "message", "host" ]
    }
    ruby {
        id => "ruby1"
        code => "event.set('foo','somefixedprefix-'+rand(1000000).to_s)" # aiming for close to 1 million distinct values
    }
}
output
{
 elasticsearch {
 id => "es1" 
 hosts => [ "https://es0:9200" ]
  user => "elastic"
  password => "changeme"
  cacert => "/usr/share/logstash/config/ca.crt"
  index => "test7134"
  manage_template => false
 }
}
```

3. Upgrade to 7.14.0 (or higher - same performance slowdown observed to segment files created from 7.14.0 to 8.0.1)
4.  Reindex to a new index in 7.14.0 : 
```
PUT test7140-reindexed
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date",
        "format": "strict_date_optional_time"
      },
      "foo": {
        "type": "keyword"
      }
    }
  },
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "0"
    }
  }
}

POST _reindex?wait_for_completion=false
{
  "source": {
    "index": "test7134",
    "size": 2000
  },
  "dest": {
    "index": "test7140-reindexed"
  }
}

#to track - leave a minute after for merge policy to settle down (do not force merge any index)
GET _tasks/wW0seewBRZKjF6S3xSKy_A:2599?human
```

5. compare performance with cardinality aggregation between the index with segment files with older lucene version are faster : 
```
# took : 1000 ms (average over multiple tests)
POST /test7134/_search?size=0
{
  "aggs": {
    "foo_cardinality": {
      "cardinality": {
        "field": "foo"
      }
    }
  }
}

# took : 4000 ms (average over multiple tests - clearing cache the performance is always slower
POST /test7140-reindexed/_search?size=0
{
  "aggs": {
    "foo_cardinality": {
      "cardinality": {
        "field": "foo"
      }
    }
  }
}

#this can be used to test multiple times (file system cache was not found to be a culprit after rebooting the one-node cluster)
POST test*/_cache/clear 
```

This is enough to reproduce but as side note force merge to 1 segment file index `test7134` will cause the segment files in `GET _cat/segments/test7134` in LUCENE 8.8.2 to be replaced by one segment file in LUCENE 8.9.0 at which point response time is increased 250%

**Comment by M-Shash** [comment]
hello @Jguay  why did you remove the bug label?

**Comment by jguay** [comment]
Thank you @not-napoleon I tested and I can also confirm the performance in my testing is back to what it was before 7.14 and good we still have the benefits of dictionary compression (it was slightly faster actually), all the indices below are forced merge to a single segment file in respective `7.13.4`, `7.17.5` and `8.4.1` and contain the exact same data. The searches are run in the final cluster in 8.4.1 (using the segment file of each index in LUCENE `8.8.2`, `8.11.1` and `9.3.0` respectively)

```
#459 1st run
#179 2nd run (after clear cache)
#174 3rd run (after clear cache)
#270.6 ms average
POST /test7134/_search?size=0
{
  "aggs": {
    "foo_cardinality": {
      "cardinality": {
        "field": "foo"
      }
    }
  }
}

#586 1st run
#355 2nd run (after clear cache)
#323 3rd run (after clear cache)
#421.3 average (55% slower than 7.13.4)
POST /test7175/_search?size=0
{
  "aggs": {
    "foo_cardinality": {
      "cardinality": {
        "field": "foo"
      }
    }
  }
}

#412 1st run
#158 2nd run (after clear cache)
#85 3rd run (after clear cache)
#218.3ms average (19% faster than 7.13.4)
POST /test841/_search?size=0
{
  "aggs": {
    "foo_cardinality": {
      "cardinality": {
        "field": "foo"
      }
    }
  }
}
```
