### ISSUE TITLE
Add configurable list of allowed domains for Watcher email action

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#84739]
### Description

When using the Watcher email action, it would be beneficial to be able to specify a list of allowed domains to which emails are allowed to be sent. This would probably be a non-dynamic setting, and allow specifying multiple domains.

**Comment by tomcallahan** [comment]
Why non-dynamic? I assume this would be configured in a Cloud UI and restarting nodes on a config change seems weighty

**Comment by dakrone** [comment]
> Why non-dynamic?

For most allow and block lists, they are non-dynamic because otherwise anyone with access to the cluster can just change the setting to allow any domain and it kind of defeats the purpose of having a list of allowed domains in the first place. Do you think this should be dynamic?

**Comment by jakelandis** [comment]
> Do you think this should be dynamic?

I think it should be dynamic. You raise a good point about access and how non-dynamic settings has an implicit (explicit in some cases) stricter access control. However, I think the ES security roles are more suitable for access control and the need to restart a cluster is a pretty significant price to pay to modify an allow list. We currently have the `manage` and `manage_watcher` [roles](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html) which can be used to separate the concerns of changing the allow list and changing the watches.

**Comment by dakrone** [comment]
Okay, works for me, I will make it dynamic.
