### ISSUE TITLE
[DOCS] DLS/FLS no longer disable shard request cache.

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#84741]
### Description

The [DLS/FLS docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/field-and-document-access-control.html) say:

> **NOTE**: Document- and field-level security disables the [shard request cache](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/shard-request-cache.html).

This feature limitation was resolved in #70191 and the note should be removed from the docs.

**Comment by lockewritesdocs** [comment]
@arpitbhardwaj, if you'd like to make this change, please open a PR and we'll review it!

**Comment by arpitbhardwaj** [comment]
@lockewritesdocs I have raised the PR for the change. Kindly have a look

**Comment by lockewritesdocs** [comment]
Closed by #90885
