### ISSUE TITLE
Implement impacts block for the shards availability indicator

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#84773]
Add "impact" block to indicators and populate it for the shards availability indicator. 
Impacts should include high level language, and wherever possible all the resources that are affected (in the shards availability indicator case the indices).

The impacts should also have a severity assigned.

ie. 
- if primary shards are unavailable (severity 2)
```
Cannot add data to 7 indices [index-1, index-2...] currently. Search results might return incomplete results.
```

- if replica shards are unavailable (severity 3)
```
Redundancy for 7 indices [index-1, index-2...] is currently disrupted. Fault tolerance and search scalability is reduced.
```

- if both primary and replica shards are unavailable (severity 1)
```
Indices [index-1, index-2, ...] are unavailable. You are at risk of losing the data in these indices.
```

**Comment by masseyke** [comment]
I'm thinking a format like this (ignore the actual message and severity).
```
...
            "indicators": {
...
                "shards_availability": {
                    "details": {
                        "creating_primaries": 0,
                        "initializing_primaries": 0,
                        "initializing_replicas": 1,
                        "restarting_primaries": 0,
                        "restarting_replicas": 0,
                        "started_primaries": 3,
                        "started_replicas": 2,
                        "unassigned_primaries": 0,
                        "unassigned_replicas": 0
                    },
                    "impact": {
                        "impact_description": "Searches may be slower than usual",
                        "severity": 3
                    },
                    "status": "yellow",
                    "summary": "This cluster has 1 unavailable replica."
                }
            },
...
```

**Comment by masseyke** [comment]
@andreidan any thoughts on severity, and how it compares to status? Isn't status the same thing as severity? Would I ever have status = red, but severity anything other than 1?

**Comment by andreidan** [comment]
@masseyke I think the severity will provide a way for us to order the impacts reported by all the indicators. I believe even now for the shards availability indicator there's a bit more nuance to the impacts severity (eg. sev 1 and 2 both would report a RED status, however one's more serious than the other)
