### ISSUE TITLE
Auto-expand replicas should clamp to closest value

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#84788]
### Elasticsearch Version

All

### Installed Plugins

N/A

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

Today if an index has an `index.auto_expand_replicas` setting which cannot be realised in the cluster then the number of replicas is left unchanged by `AllocationService#adaptAutoExpandReplicas()`. Instead, I think we should change the number of replicas to the closest value within the permitted range.

For instance: if a cluster has a single data node which is marked as shutting down for restart then auto-expand replicas considers this cluster to have zero data nodes, and hence requires -1 replicas. If an index is created with `index.auto_expand_replicas: "0-1"` then it will not be adjusted to have zero replicas, even though this would be better than leaving it at the default value of 1 replica, and will ultimately be the correct setting.

### Steps to Reproduce

1. Create a cluster with one data node.
2. Put a `RESTART` shutdown marker on the data node.
3. Create an index with `index.auto_expand_replicas: "0-1"`
4. Observe that this results in an unassigned replica.

**Comment by henningandersen** [comment]
> For instance: if a cluster has a single data node which is marked as shutting down for restart

Notice that this example is no longer valid since #85277, but the general problem persists.
