### ISSUE TITLE
Report UNKNOWN health status if the cluster state on the coordinating node is not fully recovered

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#84792]
We should report the health status as UNKNOWN if the cluster state on the coordinating node is not fully recovered (possibly with a reason message stating the node is not ready yet)

If the `instance-has-master` indicator reports RED the other indicators that rely on local cluster state should report UNKNOWN.

The order of statuses should be RED, YELLOW, UNKNOWN, GREEN
If any UNKNOWN is reported by an indicator, the indicator should advise retrying the health API call.

**Comment by jbaiera** [comment]
> Health is determined by fragment status，so I think your statement is wrong or even unnecessary

This issue is for a health reporting API unrelated to the current cluster health mechanic.

**Comment by jbaiera** [comment]
Completed with #86404
