### ISSUE TITLE
Add ability to drill down into the health API

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#84793]
Currently, the API lives under `_internal/_health`.

We should add the ability to drill down into components and indicators.

eg. 
`_internal/_health/data`
`_internal/_health/data/shards_availability`

On drill down the "details" section should be computed for every indicator that's in scope for the request drill down.

The API usage pattern here will be:
1) get the top level `_internal/_health`
2) based on the statuses detected in 1) a second call to drill down into a component or indicator to get a focused view can be executed.
The focused view received at 2) should only contain the information related to the reduced context, the top level status and information should not be returned anymore.

eg. `_internal/_health/data` would evaluate all the indicators that belong to the data component and the response will be like so:
```
{ 
  "data": {
      "status": "yellow",                   
      "indicators": {
        "shards_availability": {
          "status": "green",                
          "summary": "All ok,
          "details": " ... "
        },
        "ilm": {
           "status": "yellow",
           "summary": "...",
           "details": " ... "
        },
          ...
      }
    }
}
```

`_internal/_health/data/shards_availability` would return:
```
"shards_availability": {
        "status": "green",                
        "summary": "All ok,
        "details": " ... "
}
```

**Comment by masseyke** [comment]
Would we ever need to drill down into more than 1 indicator in a given component? Like
`GET _internal/_health/data/ilm,shards_availability`
