### ISSUE TITLE
Support VirtualLock on Windows

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8480]
On *nix boxes, we have the `mlockall` option, but that isn't supported by Windows.  Instead, Windows has [VirtualLock](http://msdn.microsoft.com/en-us/library/aa366895%28VS.85%29.aspx)

Could/should we support this option? Could we make the `bootstrap.mlockall` setting use VirtualLock on Windows boxes?

**Comment by gmarz** [comment]
Need to make a slight amendment to my previous comment above.

After digging a bit further, I've learned that there is no need for `VirtualAlloc`.  It's only useful for allocating and locking *new* memory, where in this case, we need to lock the current memory already allocated by the JVM (Xms).

The only way I've found this possible is to walk the JVM address space using [VirtualQueryEx](http://msdn.microsoft.com/en-us/library/windows/desktop/aa366907) and lock each page individually.

**Comment by s1monw** [comment]
I reverted both 1.x and master commits since tests are failing

**Comment by rmuir** [comment]
I think its just a silly test bug? The failing test asserts that mlockall didn't succeed on windows, but now it can since its supported:

    public void testMlockall() {
        if (Constants.WINDOWS) {
            assertFalse("Memory locking is not available on Windows platforms", Natives.LOCAL_MLOCKALL);
        }
        ...

**Comment by gmarz** [comment]
@rmuir Yup.  I'm fixing this now.

**Comment by rmuir** [comment]
I think we should just remove that whole assert.

**Comment by rmuir** [comment]
+1, my browser was a bit out of date.

**Comment by gmarz** [comment]
I've put back the change and fixed the tests in [1.x](https://github.com/elastic/elasticsearch/commit/1aa5c77d4460d1382aa23c19ffe2b1a389f38295) and [master](https://github.com/elastic/elasticsearch/commit/cc3f02c0a03686b915b846d1aff04cd90cf29914).

**Comment by javadevmtl** [comment]
I would gladly love to test this. Currently getting 100% usage in Windows with mapped files :)
I have 128GB server and twice made it up to 100% mem usage and unresponssive ES node.

Some details here: https://discuss.elastic.co/t/100-windows-memory-usage-but-no-oom/2089/4
And here: http://serverfault.com/questions/697511/setting-memory-mapped-file-limit-for-windows

**Comment by gmarz** [comment]
Hey @javadevmtl this is available in [1.6](https://www.elastic.co/blog/elasticsearch-1-6-0-released), which we just released today.

Would be great if you could test this and provide any feedback.  Really interested in seeing what effect it has on the issue your experiencing.
