### ISSUE TITLE
Cancel searches when heap usage is too high

### ISSUE THREAD

**Issue by Bubbad** [elastic/elasticsearch#84817]
### Description

Hello! 

At my company we've had lots of issues with out of memory spikes on our data nodes.
We have quite large queries, say up to 100k terms and on top of that lots of wildcards.
Given these large queries much of the heap allocations in a search occurs in the QueryPhase when rewriting
queries and creating scorers. 

The built-in request circuit breakers in ES seems to work well to limit the heap usage when calculating 
the aggregations for a search, but our big queries hog all the memory before we reach that point.

What do you think about adding a queryCancellation check in the ContextIndexSearcher that cancels searches
if the heap usage in the jvm is above a limit? The limit can be customizable, but this check should
be a last resort to prevent OOM. Maybe a default value of say 95% heap used would be fine.

We have already implemented such a check in a custom version of an older elasticsearch version and it has
proven to have huge value for us and has saved us many times. 

The implementation we have in our custom version has something similar to a CachedTimeThread, but instead cache
the current heap used. Then we just have another runnable in the MutableQueryTimeout runnables list that throws an exception if the the heap usage is too high.

Happy to hear your thoughts on this. Is this something you would be interested in for the official repo?
We are already porting our changes to work with 7.x so we could easily create a PR for this.

We are of course happy to discuss alternative implementations as well.

**Comment by enodr** [comment]
Hi,

We are having a very similar issue; I posted the details here: https://discuss.elastic.co/t/huge-aggregation-triggers-circuitbreaker-in-loop/299637

Our problem is that the CircuitBreaker is triggered in loop, it seems our queries with aggregations are never canceled, thus creating a kind of denial of service on the whole cluster.

**Comment by rjernst** [comment]
Thanks for your interest in Elasticsearch. We've discussed this issue, and have a couple thoughts.

> What do you think about adding a queryCancellation check in the ContextIndexSearcher that cancels searches
if the heap usage in the jvm is above a limit?

The intent of the circuit breaker is to do exactly what you describe: trip on imminent OOM. It would be confusing to have another mechanism that also trips on high usage. Additionally, a simple query should still be able to get through (for example, many diagnostic queries might be useful which don't need a lot of memory, but could help diagnose why the system is using so much memory).

We would be very interested to get more details on cases where the memory used by a query is not accurately reflected in the circuit breaker. However, this feature as described would be too limiting for the reasons above. Given that, I hope you don't mind that I close this issue. Please feel free to open a new issue with details on your queries that could help us improve the circuit breaker memory tracking.
