### ISSUE TITLE
`copy_to` in object fields added by dynamic templates adds the full object mapping too late

### ISSUE THREAD

**Issue by hbartnick** [elastic/elasticsearch#8483]
I have two issues:
- copy_to should copy values to upper nested_types by dot notation
- copy_to should copy values inside of just created dynamic fields defined with dynamic_template

see https://gist.github.com/hbartnick/9954ef86a1f3285ff5ba

**Comment by hbartnick** [comment]
we compensate the error as follows:
1. after index creation we index only one document, containing all simplified structures of object-fields and delete this document immediately. the necessary structures in elasticsearch are now present.
2. for those fields we don´t know at index creation time we react on the MapperParsingException
   and extract the information for a dummy-document we index and delete in the same manner before:
```java
    public static String createInitializerJson(MapperParsingException e) {
        String message = e.getMessage();
        String field = message.substring(message.indexOf('[') + 1, message.indexOf(']'));
        String initializerJsonPrefix = "{\"" + field.replace(".", "\": { \"");
        int countOpens = initializerJsonPrefix.length() - initializerJsonPrefix.replace("{", "").length();
        return initializerJsonPrefix + "\": \"dummy\"" + stringOfSize(countOpens, '}');
    }
    public static String stringOfSize(int size, char ch) {
        final char[] array = new char[size];
        Arrays.fill(array, ch);
        return new String(array);
    }
```

**Comment by konradkonrad** [comment]
It seems to me, the problem was already expected in this comment?
```java
if (mapper == null) {
    //TODO: Create an object dynamically?
    throw new MapperParsingException("attempt to copy value to non-existing object [" + field + "]");
}
```

https://github.com/elastic/elasticsearch/blob/4f14af21c5b9213e4b1add84d6d880eb20451e7d/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L638

**Comment by konradkonrad** [comment]
possible duplicate #11237 ?

**Comment by clintongormley** [comment]
Agreed - closing in favor of #11237
