### ISSUE TITLE
[CI] :x-pack:qa:full-cluster-restart:v7.6.0#upgradedClusterTest MlHiddenIndicesFullClusterRestartIT

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#84870]
### CI Link

https://gradle-enterprise.elastic.co/s/wikwvfpdkduy6

### Repro line

./gradlew ':x-pack:qa:full-cluster-restart:v7.6.0#upgradedClusterTest'

### Does it reproduce?

Yes

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20process%20was%20found%20dead%20while%20waiting%20for%20cluster%20health%20yellow%2C%20*&search.relativeStartTime=P7D&search.timeZoneId=America/Chicago

### Failure excerpt

```
process was found dead while waiting for cluster health yellow, cluster{:x-pack:qa:full-cluster-restart:v7.6.0}
Caused by: org.elasticsearch.gradle.testclusters.TestClustersException: process was found dead while waiting for cluster health yellow, cluster{:x-pack:qa:full-cluster-restart:v7.6.0} |  
```

Local: `MlHiddenIndicesFullClusterRestartIT`
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:41207], URI [/_ml/anomaly_detectors/ml-hidden-indices-old-cluster-job/_open], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Unexpected job state [failed] while waiting for job to be opened"}],"type":"exception","reason":"Unexpected job state [failed] while waiting for job to be opened"},"status":500}

```

**Comment by stu-elastic** [comment]
This looks like https://github.com/elastic/elasticsearch/issues/84844

**Comment by droberts195** [comment]
I bet https://github.com/elastic/elasticsearch/issues/84869 is the same too - if you download the server side logs for the nodes of that cluster you'll probably see the same assertion failure about the index settings there.

**Comment by stu-elastic** [comment]
> If you want the ML team to investigate the local failure please can you upload the server side logs (from under x-pack/qa/full-cluster-restart/build/testclusters/v7.6.0-?/logs) from the local reproduction on your machine. That is showing a completely different problem.

Here ya go [v7.6.0.mlhidden.logs.zip](https://github.com/elastic/elasticsearch/files/8225431/v7.6.0.mlhidden.logs.zip)

**Comment by droberts195** [comment]
Oh, actually I can guess why you're getting the local failures - you're on Arch Linux: `Linux/5.15.4-arch1-1/amd64`

That is not a supported platform.  From what Nik found you can make it work by installing the package https://archlinux.org/packages/core/x86_64/libxcrypt-compat/

**Comment by droberts195** [comment]
Nik attached his logs to #84844 and having had a look I am sure this is a duplicate.

The details are in https://github.com/elastic/elasticsearch/issues/84844#issuecomment-1064314794 so I'll close this as a duplicate.
