### ISSUE TITLE
ElasticSearch 1.3.4 recovery slow on larger clusters (50+ total nodes)

### ISSUE THREAD

**Issue by TrentStewart** [elastic/elasticsearch#8487]
We are seeing a situation on clusters running 1.3.4 with greater than 50 total nodes where shard recovery/allocation is either failing or is VERY slow.

Full details:
I currently have 6 clusters, 4 with 24 total nodes and 2 larger clusters with 53 & 63 nodes respectively.  Everything is run on VMs running Windows Server 2012 R2 within Azure.

All clusters (except the 63 node) were upgraded from 1.3.2 to 1.3.4 using an offline method of shutting down the cluster clean, swapping out the x64 Windows Service, then restarting all of the nodes.  The 63 node cluster was built last week clean with 1.3.4.

For the 24 node clusters, the clusters returned to a green status after the upgrade in less than 30 minutes and are performing very well.  I also did a rolling reboot of all of the machines to apply OS updates where I have automation that sets allocation to new_primaries, shuts down the service, reboots the machine, waits for the node to rejoin the cluster, sets allocation back to all, then waits for the cluster to return to green before proceeding to the next node.  Again for each of the 24 node clusters, it completed the entire process in just shy of 2 hours.

The 53 node cluster is our oldest cluster (with 144 indices & 3330 shards) and has under gone several upgrades using the offline method and in each scenario, the cluster returned to yellow within 15 minutes and green within 40 minutes.  Monday night we upgraded this cluster and it took 3 hours to get to yellow and 6 hours to get to green.

The 63 node cluster is our newest cluster (currently has 12 indices & 272 shards).  Last night & today while performing a rolling reboot, each node has a max of 3 shards on it, after the machine rebooted, it was taking > 10 minutes for the node to rejoin the cluster and randomly some shards would never finish initialization.

When I query _cat/recovery?pretty=true&v&active_only=true, no shards are listed however _cat/shards would show 1 or 2 shards as INITIALIZING.  If I issued the command for reroute cancel on the initializing shards, they would almost immediately allocation and the cluster would turn green.

**Comment by julien51** [comment]
We are seeing a similar issue where recovery seems to be stuck in the "translog" state.
When checking `/<idx>/_recovery?pretty=true&active_only=true` we do find that translog recovery is in progress:
`
 "translog" : {
        "recovered" : 35516,
        "total_time_in_millis" : 0
      },
`
but extremely slow... and we have no ETA idea. What does `recovered` mean in the context of translog? Are these bytes?

**Comment by bleskes** [comment]
@julien51 those are translog operations . To find out how many there are in total and what the size of the translog is, you can run `GET /<idx>/_stats?level=shards&human` and check the primary shard. I'm working on a change that will supply those as part of the recovery output.  Which version are you on?

**Comment by julien51** [comment]
Version: 1.4.2
The problem: this is a master initializing, so it looks like the number of operations is not available :(

**Comment by bleskes** [comment]
@julien51 I see, this is your primary shard? In this case it's hard to tell indeed. You can check the file system for the size of a file called "translog-????.recovering" (again, working on improving this). 

When you shut down the cluster (did you?) did you have any relocations/recoveries going on? (if you know).

**Comment by julien51** [comment]
Unfortunaty, there was a bit of a disaster and the shutdiwn of the server was unexpected (still trying to understand what happend). We had 2 servers failing (out of 5) and of course they had the primary and secondary for one of our indices.
The file size of 1752285717 bytes. Any idea of how that roughly converts to number of operations?

**Comment by julien51** [comment]
Extra stupid question: this would in theory be an absolutely bad time to upgrade to 1.4.4, but I see 1.4.3 does bring improvements on the recovery front.  
What if I prevent the cluster from doing any re-alloc and then upgrade the node on which this slow initilizating is going on?

**Comment by julien51** [comment]
After 6 hours, it was still processing the translog, but at an excruciatingly slow pace... so I restarted the node, and well, it finished in a matter of seconds on another host. We seem to have the same number of documents. 
Yet, we'll start re-indexing from our main datastore, just in case we miss anything.

**Comment by bleskes** [comment]
> The file size of 1752285717 bytes. Any idea of how that roughly converts to number of operations? 
Is there one operation per line? The file has 511,014 lines... so if that's 1 line per operation, 

The translog is binary. New lines are just there by accident (if viewed as text)

>  this would in theory be an absolutely bad time to upgrade to 1.4.4, but I see 1.4.3 does bring improvements on the recovery front.

1.4.3 helps by being more aggressive in trimming the translog post recovery but we're still chasing this issue. It is very rare but do occur (as you sadly noticed).

> I restarted the node, and well, it finished in a matter of seconds on another host. 
> We seem to have the same number of documents. 

Yes. The translog on replica is being flushed during recovery. It's only the primary than can grow, because we need it a safety measure to catch all the documents indexed between starting to copy lucene files and starting the translog phase. Depending on what exactly happened, there might be none but it is not guaranteed.

**Comment by clintongormley** [comment]
The never-ending-translog bug was fixed several versions ago.  I'm going to close this issue.
