### ISSUE TITLE
[CI] Packaging ':distribution:docker:metricbeat' Could not find beats:metricbeat:8.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#84896]
### CI Link

https://gradle-enterprise.elastic.co/s/dmxf3cbsdhhtg

### Repro line

./gradlew destructivePackagingTest

### Does it reproduce?

Didn't try

### Applicable branches

8.1

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Could%20not%20determine%20the%20dependencies%20of%20task%20*%0A%3E%20Could%20not%20resolve%20all%20task%20dependencies%20for%20configuration%20*%0A%20%20%20%3E%20Could%20not%20find%20*%0A%20%20%20%20%20Searched%20in%20the%20following%20locations:%0A%20%20%20%20%20%20%20-%20https://repo.maven.apache.org/maven2/beats/*/*/maven-metadata.xml%0A%20%20%20%20%20%20%20-%20https://repo.maven.apache.org/maven2/beats/*/*/*%0A%20%20%20%20%20%20%20-%20https://snapshots-no-kpi.elastic.co/downloads/beats/*/*%0A%20%20%20%20%20Required%20by:%0A%20%20%20%20%20%20%20%20%20project%20:distribution:docker&search.relativeStartTime=P7D&search.timeZoneId=America/Chicago

### Failure excerpt
`Could not determine the dependencies of task ':distribution:docker:buildAarch64CloudDockerContext'.`
```
Could not resolve all task dependencies for configuration ':distribution:docker:metricbeat'.
> Could not find beats:metricbeat:8.1.1-SNAPSHOT.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/beats/metricbeat/8.1.1-SNAPSHOT/maven-metadata.xml
    - https://repo.maven.apache.org/maven2/beats/metricbeat/8.1.1-SNAPSHOT/metricbeat-8.1.1-SNAPSHOT.pom
    - https://snapshots-no-kpi.elastic.co/downloads/beats/metricbeat/metricbeat-8.1.1-SNAPSHOT-linux-x86_64.tar.gz
  Required by:
      project :distribution:docker
```

**Comment by mark-vieira** [comment]
This will sort itself out as soon as the first 8.1.1 snapshot build goes out.
