### ISSUE TITLE
COMPOSE_PROJECT_NAME environment variable not in use

### ISSUE THREAD

**Issue by nelsonprsousa** [elastic/elasticsearch#84925]
### Elasticsearch Version

8

### Java Version

_bundled_

### OS Version

Docker (using Linux)

### Problem Description

In documentation, to install elastic stack, here's the folder containing the docker-compose and .env files:
https://github.com/elastic/elasticsearch/tree/master/docs/reference/setup/install/docker

Particularly in the .env file there's this entry:
```
# Project namespace (defaults to the current folder name if not set)
#COMPOSE_PROJECT_NAME=myproject
```

Which is not used in the `docker-compose` file, so elastic will not receive that value - probably there's a misconfiguration here.

### Steps to Reproduce

`docker-compose up` will not take into consideration the value of `COMPOSE_PROJECT_NAME` environment variable

**Comment by mark-vieira** [comment]
I think the intention here is for this just to serve as an example for folks and they can uncomment the line if they so choose.

**Comment by nelsonprsousa** [comment]
> I think the intention here is for this just to serve as an example for folks and they can uncomment the line if they so choose.

But where the variable is used? I couldn't find  where it is used

**Comment by pugnascotia** [comment]
`COMPOSE_PROJECT_NAME` is used by docker-compose to override the project name, otherwise it uses the current directory name. See:

https://docs.docker.com/compose/reference/envvars/#compose_project_name
