### ISSUE TITLE
Specify the number of primary and replica shards for the index on a data instance

### ISSUE THREAD

**Issue by qixian-jiajia** [elastic/elasticsearch#84933]
### Description

Currently，we can use the index.routing.allocation.total_shards_per_node to define the shards number on a data instance,I want to have a feature that supports specifying that the number of primary shards and the number of replica shards can be assigned separately on a data instance

**Comment by henningandersen** [comment]
@qixian-jiajia I am not entirely sure I follow the suggestion. Can you perhaps provide an example of the settings you would add and how you would use it? Is the purpose to avoid too many primaries on one node? Adding a description of what you hope to achieve out of this would definitely help too.

**Comment by ywangd** [comment]
I am closing this issue since we haven't seen any update since Henning's question and it is unclear what we want to achieve here.
