### ISSUE TITLE
LEAK resource not cleaned up RelocationIT testRelocationEstablishedPeerRecoveryRetentionLeases

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#84948]
### CI Link

https://gradle-enterprise.elastic.co/s/coilrchnhdicw

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.recovery.RelocationIT.testRelocationEstablishedPeerRecoveryRetentionLeases" -Dtests.seed=48DD4597C7EC8FF7 -Dtests.locale=es-PA -Dtests.timezone=Europe/Bucharest -Druntime.java=17	

### Does it reproduce?

No

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.recovery.RelocationIT&tests.sortField=FAILED&tests.test=testRelocationEstablishedPeerRecoveryRetentionLeases&tests.unstableOnly=true

### Failure excerpt

  1> [2022-03-14T13:43:38,122][INFO ][o.e.r.RelocationIT       ] [testRelocationEstablishedPeerRecoveryRetentionLeases] [RelocationIT#testRelocationEstablishedPeerRecoveryRetentionLeases]: cleaned up after test
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.recovery.RelocationIT.testRelocationEstablishedPeerRecoveryRetentionLeases" -Dtests.seed=48DD4597C7EC8FF7 -Dtests.locale=es-PA -Dtests.timezone=Europe/Bucharest -Druntime.java=17
  2> java.lang.AssertionError: 
    Expected: an empty collection
         but: <[LEAK: resource was not cleaned up before it was garbage-collected.
    Recent access records: 
    Created at:
    	org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:32)
    	org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:72)
    	org.elasticsearch.transport.BytesRefRecycler.obtain(BytesRefRecycler.java:27)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.ensureCapacityFromPosition(RecyclerBytesStreamOutput.java:211)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.ensureCapacity(RecyclerBytesStreamOutput.java:202)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.writeBytes(RecyclerBytesStreamOutput.java:77)
    	org.elasticsearch.common.io.Streams$FlushOnCloseOutputStream.writeBytes(Streams.java:274)
    	org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:482)
    	java.base/java.io.OutputStream.write(OutputStream.java:127)
    	org.elasticsearch.common.compress.DeflateCompressor.threadLocalOutputStream(DeflateCompressor.java:179)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler.serializeDiffClusterState(PublicationTransportHandler.java:266)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler$PublicationContext.lambda$buildDiffAndSerializeStates$2(PublicationTransportHandler.java:329)
    	java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler$PublicationContext.buildDiffAndSerializeStates(PublicationTransportHandler.java:327)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler.newPublicationContext(PublicationTransportHandler.java:213)
    	org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:1368)
    	org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:416)
    	org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:309)
    	org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:153)
    	org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:114)
    	org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:170)
    	org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717)
    	org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260)
    	org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
    	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	java.base/java.lang.Thread.run(Thread.java:833)]>
        at __randomizedtesting.SeedInfo.seed([48DD4597C7EC8FF7:886D486B4E0323C8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:639)
        at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:427)
        at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:833)
  1> [2022-03-14T13:43:38,149][INFO ][o.e.r.RelocationIT       ] [testIndexSearchAndRelocateConcurrently] before test
  1> [2022-03-14T13:43:38,149][INFO ][o.e.r.RelocationIT       ] [testIndexSearchAndRelocateConcurrently] [RelocationIT#testIndexSearchAndRelocateConcurrently]: setting up test
  1> [2022-03-14T13:43:38,150][INFO ][o.e.t.InternalTestCluster] [testIndexSearchAndRelocateConcurrently] Setup InternalTestCluster [TEST-TEST_WORKER_VM=[471]-CLUSTER_SEED=[-2805428162336455921]-HASH=[1322FA3E367]-cluster] with seed [D9111DF33D0F030F] using [0] dedicated masters, [0] (data) nodes and [0] coord only nodes (master nodes are [auto-managed])

**Comment by DaveCTurner** [comment]
The leak is happening here in the test before the one that reports the failure:

```
  1> [2022-03-14T13:43:36,396][WARN ][o.e.t.TransportService   ] [node_t2] failed to notify channel of error message for action [internal:cluster/coordination/publish_state]
  1> org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of delivery of failure response to [46][internal:cluster/coordination/publish_state]: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: no longer leading this publication's term: PublishRequest{term=2, version=16, state=cluster uuid: xmc0IQTRTVWGJLv3ckm9CQ [committed: true]
  1> version: 16
  1> state uuid: LDCnyZ14S5CAw_gUQOOVHw
  1> from_diff: false
  1> meta data version: 10
  1>    coordination_metadata:
  1>       term: 2
  1>       last_committed_config: VotingConfiguration{_-7kxE-oQ1SdowsVoIwLYw,1S16LPlWT8-87-X3oPncBA,ba8Cl8wBQom9XOXeg0CKHA}
  1>       last_accepted_config: VotingConfiguration{_-7kxE-oQ1SdowsVoIwLYw,1S16LPlWT8-87-X3oPncBA,ba8Cl8wBQom9XOXeg0CKHA}
  1>       voting tombstones: []
  1> metadata customs:
  1>    index-graveyard: IndexGraveyard[[[index=[test/hVXuA7yET8-1Sp8VqzhSMg], deleteDate=2022-03-14T11:43:36.239Z]]]
  1> nodes: 
  1>    {node_t0}{_-7kxE-oQ1SdowsVoIwLYw}{YiffXDKxR062xt4xApnRbw}{127.0.0.1}{127.0.0.1:44947}{cdfhilmrstw}
  1>    {node_t2}{1S16LPlWT8-87-X3oPncBA}{9u8M4n0NRkmz-9WS4c8k1Q}{127.0.0.1}{127.0.0.1:36613}{cdfhilmrstw}, local, master
  1>    {node_t1}{ba8Cl8wBQom9XOXeg0CKHA}{n408iSB9RpqAps-1QjvoQw}{127.0.0.1}{127.0.0.1:43183}{cdfhilmrstw}
  1> routing_table (version 10):
  1> routing_nodes:
  1> -----node_id[1S16LPlWT8-87-X3oPncBA][V]
  1> -----node_id[ba8Cl8wBQom9XOXeg0CKHA][V]
  1> -----node_id[_-7kxE-oQ1SdowsVoIwLYw][V]
  1> ---- unassigned
  1> } on EsThreadPoolExecutor[name = node_t2/cluster_coordination, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@514c57f8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 32]] (shutdown)
  1> 	at org.elasticsearch.common.util.concurrent.EsRejectedExecutionHandler.newRejectedException(EsRejectedExecutionHandler.java:36) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:34) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
  1> 	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:66) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1434) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:928) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:764) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:833) [?:?]
  1> 	Suppressed: org.elasticsearch.cluster.coordination.CoordinationStateRejectedException: no longer leading this publication's term: PublishRequest{term=2, version=16, state=cluster uuid: xmc0IQTRTVWGJLv3ckm9CQ [committed: true]
  1> version: 16
  1> state uuid: LDCnyZ14S5CAw_gUQOOVHw
  1> from_diff: false
  1> meta data version: 10
  1>    coordination_metadata:
  1>       term: 2
  1>       last_committed_config: VotingConfiguration{_-7kxE-oQ1SdowsVoIwLYw,1S16LPlWT8-87-X3oPncBA,ba8Cl8wBQom9XOXeg0CKHA}
  1>       last_accepted_config: VotingConfiguration{_-7kxE-oQ1SdowsVoIwLYw,1S16LPlWT8-87-X3oPncBA,ba8Cl8wBQom9XOXeg0CKHA}
  1>       voting tombstones: []
  1> metadata customs:
  1>    index-graveyard: IndexGraveyard[[[index=[test/hVXuA7yET8-1Sp8VqzhSMg], deleteDate=2022-03-14T11:43:36.239Z]]]
  1> nodes: 
  1>    {node_t0}{_-7kxE-oQ1SdowsVoIwLYw}{YiffXDKxR062xt4xApnRbw}{127.0.0.1}{127.0.0.1:44947}{cdfhilmrstw}
  1>    {node_t2}{1S16LPlWT8-87-X3oPncBA}{9u8M4n0NRkmz-9WS4c8k1Q}{127.0.0.1}{127.0.0.1:36613}{cdfhilmrstw}, local, master
  1>    {node_t1}{ba8Cl8wBQom9XOXeg0CKHA}{n408iSB9RpqAps-1QjvoQw}{127.0.0.1}{127.0.0.1:43183}{cdfhilmrstw}
  1> routing_table (version 10):
  1> routing_nodes:
  1> -----node_id[1S16LPlWT8-87-X3oPncBA][V]
  1> -----node_id[ba8Cl8wBQom9XOXeg0CKHA][V]
  1> -----node_id[_-7kxE-oQ1SdowsVoIwLYw][V]
  1> ---- unassigned
  1> }
  1> 		at org.elasticsearch.cluster.coordination.Coordinator.handlePublishRequest(Coordinator.java:391) ~[main/:?]
  1> 		at org.elasticsearch.cluster.coordination.PublicationTransportHandler.acceptState(PublicationTransportHandler.java:200) ~[main/:?]
  1> 		at org.elasticsearch.cluster.coordination.PublicationTransportHandler.handleIncomingPublishRequest(PublicationTransportHandler.java:183) ~[main/:?]
  1> 		at org.elasticsearch.cluster.coordination.PublicationTransportHandler.lambda$new$0(PublicationTransportHandler.java:103) ~[main/:?]
  1> 		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:67) ~[main/:?]
  1> 		at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:917) [main/:?]
  1> 		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:776) [main/:?]
  1> 		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [main/:?]
  1> 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
  1> 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
  1> 		at java.lang.Thread.run(Thread.java:833) [?:?]
```

I opened #85131 to propose a fix.

**Comment by DaveCTurner** [comment]
Problem reproduces with somewhat higher frequency with artificial delays added as below. Still not very frequently it seems but better than nothing.

```diff
diff --git a/server/src/main/java/org/elasticsearch/transport/TransportService.java b/server/src/main/java/org/elasticsearch/transport/TransportService.java
index 73065a0d8a9..98753863cff 100644
--- a/server/src/main/java/org/elasticsearch/transport/TransportService.java
+++ b/server/src/main/java/org/elasticsearch/transport/TransportService.java
@@ -17,6 +17,7 @@ import org.elasticsearch.action.ActionListener;
 import org.elasticsearch.action.ActionListenerResponseHandler;
 import org.elasticsearch.cluster.ClusterName;
 import org.elasticsearch.cluster.node.DiscoveryNode;
+import org.elasticsearch.common.Randomness;
 import org.elasticsearch.common.Strings;
 import org.elasticsearch.common.component.AbstractLifecycleComponent;
 import org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput;
@@ -1396,6 +1397,7 @@ public class TransportService extends AbstractLifecycleComponent
                 if (ThreadPool.Names.SAME.equals(executor)) {
                     processResponse(handler, response);
                 } else {
+                    randomDelay(executor);
                     threadPool.executor(executor).execute(new Runnable() {
                         @Override
                         public void run() {
@@ -1420,6 +1422,16 @@ public class TransportService extends AbstractLifecycleComponent
             }
         }

+        private static void randomDelay(String executor) {
+            if (executor.equals(ThreadPool.Names.CLUSTER_COORDINATION) && Transports.isTransportThread(Thread.currentThread()) == false) {
+                try {
+                    Thread.sleep(Randomness.get().nextInt(500));
+                } catch (Exception e) {
+                    throw new AssertionError(e);
+                }
+            }
+        }
+
         @Override
         public void sendResponse(Exception exception) throws IOException {
             service.onResponseSent(requestId, action, exception);
@@ -1431,6 +1443,7 @@ public class TransportService extends AbstractLifecycleComponent
                 if (ThreadPool.Names.SAME.equals(executor)) {
                     processException(handler, rtx);
                 } else {
+                    randomDelay(executor);
                     threadPool.executor(handler.executor()).execute(new Runnable() {
                         @Override
                         public void run() {
```
