### ISSUE TITLE
Metadata bug, entity creation fails

### ISSUE THREAD

**Issue by jandres6579** [elastic/elasticsearch#84945]
### Elasticsearch Version

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release. Version: 7.6.2, Build: default/docker/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z, JVM: 13.0.2

### Java Version

openjdk 11.0.14 2022-01-18 OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.18.04) OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

### OS Version

Linux 5.4.0-100-generic #113~18.04.1-Ubuntu SMP Mon Feb 7 15:02:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

The creation of this entity can't be stored in Elasticsearch:

```
{
    "id": "identifier1",
    "type": "type1",
    "name": {
        "type": "Text",
        "value": "value1",
        "metadata1": {
        "type": "Text",
        "value": "textMetadata1"
        },
        "observedAt": {
        "type": "DateTime",
        "value": "2022-03-14T10:05:70.145Z"
        }
    }
 }
```

### Steps to Reproduce

Create this entity in NGSv2 broker, but it's not accessible in Elasticsearch after cygnus  processes it

**Comment by nik9000** [comment]
> Create this entity in NGSv2 broker, but it's not accessible in Elasticsearch after cygnus processes it

This sounds like something you should take up with the NGSv2 folks. There may be an Elasticsearch bug in here somewhere but you'd have to reproduce it using `curl` for us to be able to do anything with it.

**Comment by jandres6579** [comment]
ok, can you say me how can I send directly to Elasticsearch something like  **(index=cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16, type=cygnus_type, data=[{data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"21","attrName":"temperature","attrType":"Number"}, recvTimeTs=1647446429054}, {data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[{"name":"amountOfThisGood","type":"Text","value":"1"},{"name":"timestamp","type":"DateTime","value":"2022-03-15T23:00:00.000Z"}],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"803","attrName":"pressure","attrType":"Number"}, recvTimeTs=1647446429054}])** ? 

You asked me about a curl request of this issue, I understand that it is the body of the request.....

In my opinion, something happens with Elasticsearch when the previous body fails but the next bodies works:

 **(index=cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16, type=cygnus_type, data=[{data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"21","attrName":"temperature","attrType":"Number"}, recvTimeTs=1647446429054}, {data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[{"name":"amountOfThisGood","type":"Text","value":"1"},],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"803","attrName":"pressure","attrType":"Number"}, recvTimeTs=1647446429054}])**

 **(index=cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16, type=cygnus_type, data=[{data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"21","attrName":"temperature","attrType":"Number"}, recvTimeTs=1647446429054}, {data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[{"name":"timestamp","type":"DateTime","value":"2022-03-15T23:00:00.000Z"}],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"803","attrName":"pressure","attrType":"Number"}, recvTimeTs=1647446429054}])**

**Comment by nik9000** [comment]
> In my opinion, something happens with Elasticsearch when the previous body fails but the next bodies works:

Yeah. That's normal. The `attrMetadata.value` field is marked as a date in the mapping - it'll only accept the first ones.

Our docs cover how you could send this to the index - just an HTTP POST really. But this really is in the "how do I use Elasticsearch" territory - which belongs on https://discuss.elastic.co/ . I still think the bug is that the application that is importing the data hasn't set the mapping for the `attrMetadata.value` field to something sensible. Or just isn't designed for Elasticsearch at all.
