### ISSUE TITLE
Elasticsearch won't start on first use

### ISSUE THREAD

**Issue by itzikyis** [elastic/elasticsearch#85009]
### Elasticsearch Version

8.1.0

### Java Version

_bundled_1.8.0_321

### OS Version

Windows 10 Home 21H1

### Problem Description

I have follow the website instructions:

Download the Elasticsearch 8.1.0 Windows zip file from the [Elasticsearch download](https://www.elastic.co/downloads/elasticsearch) page.
Extract the contents of the zip file to a directory on your computer, to C:\Elasticsearch-8.1.0 (No spaces)
Open a command prompt as an Administrator and navigate to the directory that contains the extracted files.
cd C:\Elasticsearch-8.1.0

Start Elasticsearch:
bin\Elasticsearch.bat

getting this Error:

skipping security auto configuration because the configuration file [C:\Elasticsearch-8.1.0\bin\Elasticsearch\Elasticsearch.yml] is missing or is not a regular file.

### Steps to Reproduce

Download the Elasticsearch 8.1.0 Windows zip file from the [Elasticsearch download](https://www.elastic.co/downloads/elasticsearch) page.
Extract the contents of the zip file to a directory on your computer, to C:\Elasticsearch-8.1.0 (No spaces)
Open a command prompt as an Administrator and navigate to the directory that contains the extracted files.
cd C:\Elasticsearch-8.1.0

Start Elasticsearch:
bin\Elasticsearch.bat

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by rjernst** [comment]
@itzikyis Can you please paste the entire output from attempting to start Elasticsearch?

**Comment by itzikyis** [comment]
Hi,
The problem was on 8.1.0
Now it is working on 8.1.1

Thanks,
Itzik

‫בתאריך יום ב׳, 28 במרץ 2022 ב-15:38 מאת ‪Ryan Ernst‬‏ <‪
***@***.***‬‏>:‬
