### ISSUE TITLE
Attribute not stored in Elasticsearch by metadata.

### ISSUE THREAD

**Issue by jandres6579** [elastic/elasticsearch#85026]
### Elasticsearch Version

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release. Version: 7.6.2, Build: default/docker/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z, JVM: 13.0.2

### Java Version

openjdk 11.0.14 2022-01-18 OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.18.04) OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

### OS Version

Linux 5.4.0-100-generic #113~18.04.1-Ubuntu SMP Mon Feb 7 15:02:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

When I send, directly to cygnus this request:

curl --location --request POST 'http://localhost:5058/notify' \
--header 'content-type: application/json; charset=utf-8' \
--header 'Fiware-Service: prueba' \
--header 'Fiware-Servicepath: /' \
--header 'Ngsiv2-AttrsFormat: normalized' \
--data-raw '{
    "subscriptionId":"6231de09c1b7368505294c2b",
    "data":[
        {
            "id":"urn:ngsi-ld:Room:Room3061",
            "type":"Room",
            "temperature":{
                "type":"Number",
                "value":21,
                "metadata":{}
            },
            "pressure":{
                "type":"Number",
                "value":803,
                "metadata":{
                    "timestamp":{
                        "value":"2022-03-15T23:00:00.000Z",
                        "type":"DateTime"
                    }
                    ,"amountOfThisGood":{"type":"Text","value":"1"}
                }
            }
        }
    ]
}
'
Preassure attribute is not stored in Elasticsearch, because "timestamp" and "amountOfThisGood" metadatas "travel" together. If I remove one of them it works. It's strange. In my opinion, something happens when a datetime metadata exists because I can send more than one no metadata datetime and in this case it works.

### Steps to Reproduce

Send the previus request to cygnus component.

**Comment by tlrx** [comment]
Elasticsearch does not expose any `/notify` REST API endpoint. Your problem should be reported or discussed with people maintaining the software you are using (cygnus?)

**Comment by jandres6579** [comment]
The cygnus component sends the following to elasticsearch:

fiware-cygnus       | time=2022-03-16T16:00:29.874Z | lvl=INFO | corr=175d81b1-d93b-402b-9ffc-5171dc3cabf2 | trans=175d81b1-d93b-402b-9ffc-5171dc3cabf2 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=run | msg=com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink$1[111] : [elasticsearch-sink] Persisting data at NGSIElasticsearchSink. **(index=cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16, type=cygnus_type, data=[{data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"21","attrName":"temperature","attrType":"Number"}, recvTimeTs=1647446429054}, {data={"recvTime":"2022-03-16T16:00:29.054+0000","entityType":"Room","attrMetadata":[{"name":"amountOfThisGood","type":"Text","value":"1"},{"name":"timestamp","type":"DateTime","value":"2022-03-15T23:00:00.000Z"}],"entityId":"urn:ngsi-ld:Room:Room3070","attrValue":"803","attrName":"pressure","attrType":"Number"}, recvTimeTs=1647446429054}])**



And in ElasticSearch component I obtain:

db-elasticsearch    | {"type": "server", "timestamp": "2022-03-16T16:00:29,784Z", "level": "DEBUG", "component": "o.e.c.c.C.CoordinatorPublication", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "publication ended successfully: Publication{term=1, version=22}", "cluster.uuid": "LfRZ0XnjRpe5L3H1XZYQpQ", "node.id": "F4TG9aAHRqCMAWafV3DtDw"  }
db-elasticsearch    | {"type": "server", "timestamp": "2022-03-16T16:00:29,785Z", "level": "DEBUG", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "took [0s] to notify listeners on successful publication of cluster state (version: 22, uuid: 2vVUuoMXRN-JveMP1-44Uw) for [put-mapping[cygnus_type]]", "cluster.uuid": "LfRZ0XnjRpe5L3H1XZYQpQ", "node.id": "F4TG9aAHRqCMAWafV3DtDw"  }
db-elasticsearch    | {"type": "server", "timestamp": "2022-03-16T16:00:29,820Z", "level": "DEBUG", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "message": "[cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16][0] failed to execute bulk item (index) index {[cygnus-fiware-service--urn-ngsi-ld-room-room3070-room-2022.03.16][cygnus_type][1647446429054-890AC15FB9F056E7C2B84D93216A9091], source[_na_]}", "cluster.uuid": "LfRZ0XnjRpe5L3H1XZYQpQ", "node.id": "F4TG9aAHRqCMAWafV3DtDw" , 
db-elasticsearch    | "stacktrace": ["java.lang.IllegalArgumentException: mapper [attrMetadata.value] of different type, current_type [date], merged_type [text]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:359) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.DateFieldMapper.doMerge(DateFieldMapper.java:609) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:346) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:56) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.DocumentParser.createDynamicUpdate(DocumentParser.java:237) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:83) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:267) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:793) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:770) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:742) ~[elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:267) [elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:157) [elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.2.jar:7.6.2]",
db-elasticsearch    | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
db-elasticsearch    | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
db-elasticsearch    | "at java.lang.Thread.run(Thread.java:830) [?:?]"] }

**Comment by jandres6579** [comment]
I don't know if with this payload is enough to evaluate it. Thanks.
