### ISSUE TITLE
Elasticsearch-oss-6.8.23 cannot create all relevant AIPS when creating index lifecycle management, and will not take effect

### ISSUE THREAD

**Issue by yongjingwei** [elastic/elasticsearch#85048]
### Elasticsearch Version

Elasticsearch-oss-6.8.23

### Java Version

_bundled_jdk1.8

### OS Version

ubantu20.04.1

### Problem Description

Elasticsearch-oss-6.8.23 cannot create all relevant AIPS when creating index lifecycle management, and will not take effect

![image](https://user-images.githubusercontent.com/45063335/158731449-86ea7a13-2807-4c12-b586-50d3edd0b649.png)

### Steps to Reproduce

Elasticsearch-oss-6.8.23 cannot create all relevant AIPS when creating index lifecycle management, and will not take effect

![image](https://user-images.githubusercontent.com/45063335/158731449-86ea7a13-2807-4c12-b586-50d3edd0b649.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, regarding a version that has [passed EOL](https://www.elastic.co/support/eol), and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
