### ISSUE TITLE
8.x security setup docs don't describe how to set up kibana 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#85046]
### Description

As part of security on by default we removed a lot of the existing "setting up security" documentation, because it was no longer relevant.

However, that means that we have a gap in our docs for people who want to turn on security on an existing cluster.

In particular the 7.x docs have a page for [setting up passwords and configuring Kibana](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html#security-create-builtin-users) but there is no obvious replacement in 8.x  
The docs jump straight into setting up TLS, and skip the Kibana authentication process.

**Comment by debadair** [comment]
I _think_ this is more an issue of discoverability than a gap. There is information about setting passwords for the built-in users at: https://www.elastic.co/guide/en/elasticsearch/reference/8.1/built-in-users.html#set-built-in-user-passwords

The redirect page for the 7.17 topic doesn't link to that, however, it links directly to the reference page for the elasticsearch-reset-password tool.

**Comment by lockewritesdocs** [comment]
We could also consider adding the section for [Creating passwords for built-in users](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html#security-create-builtin-users) to the 8.x docs.
