### ISSUE TITLE
Is ILM (index lifecycle management) supported in Elassticsearch-OSS-6.8.x？

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#85051]

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, regarding a version that has [passed EOL](https://www.elastic.co/support/eol), and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
