### ISSUE TITLE
Shards are relocated while node is restarted and shutdown API has been called

### ISSUE THREAD

**Issue by barkbay** [elastic/elasticsearch#85052]
### Elasticsearch Version

7.17.1

### Java Version

_bundled_

### OS Version

ECK running on GKE 1.22.7-gke.900

### Problem Description

Shards are relocated between nodes in the cold tier while they are restarting, despite the fact that the [shutdown API](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-shutdown.html#put-shutdown-api-request-body) is called with the type `restart`.

It has been first reported by an ECK user [here](https://github.com/elastic/cloud-on-k8s/issues/5464):
> I see the managed Elasticsearch cluster try to reallocate 350+ searchable snapshots from the restart of a cold node.

I also managed to reproduce it consistently:

1. See a first report [here](https://gist.github.com/barkbay/ef1c7b516bf93534d216bfa48827b70d), full logs from the master node are [here](https://gist.githubusercontent.com/barkbay/0f25a9588755a8eb06bea0a70ec6a1a7/raw/bfe10bf910ac2ae0ffab07454395fd4d694e0cc1/master-0.ndjson).

2. I also reproduced the problem while `logger.org.elasticsearch.cluster.routing.allocation.decider` was set to true `TRACE`,  logs are available [here](https://gist.githubusercontent.com/barkbay/0f25a9588755a8eb06bea0a70ec6a1a7/raw/bfe10bf910ac2ae0ffab07454395fd4d694e0cc1/master-0.traces.ndjson). While the node `elasticsearch-gcs-sample-es-cold-2` is restarted, shard `restored-.ds-metricbeat-8.0.0-2022.03.16-000003` has been relocated to `elasticsearch-gcs-sample-es-cold-1`.

It does not seem to happen for other tiers (not sure about the frozen though).

### Steps to Reproduce

1. Deploy a cluster with a cold tier, shards being backed by a snapshot. Without replica.
2. Call the shutdown API with the `restart` type on a node in the cold tier
3. Monitor the shards location
4. Restart the node
5. Shards are being relocated

**Comment by henningandersen** [comment]
Had a look at this and it looks like the `SearchableSnapshotEnableAllocationDecider` needs to also look for a shutdown indication or another mechanism need to ensure that these searchable snapshot shards are not reallocated within the `allocation_delay` period. Notice that these are primaries, which is why the mechanism for replicas does not kick in.

**Comment by BenB196** [comment]
In case anyone comes across this issue before it is fixed, and they don't want their searchable snapshot shards reallocating during a rolling restart. The following hacky script can be run before performing a rolling restart, and should negate searchable snapshots from being reallocated.

## Prerequisites 
- bash
- jq
- curl

## Variables

- `ES_USERNAME` username of the user that has the ability to set index settings
- `ES_PASSWORD` password of the user you're using
- `ES_URL` URL to your Elasticsearch cluster

## Assumptions
1. This script assumes the searchable snapshot indices are managed by ILM and start with the prefix `restored-*`. If your searchable snapshots aren't managed by ILM or don't begin with the `restored-*` prefix. Change the script to use which ever pattern(s) work for you.
2. The script assumes that a single shard is backing each index.
3. Only `open` & `hidden` indices are considered, if you also have closed searchable snapshots change `expand_wildcards=open,hidden` to `expand_wildcards=all`
4. Some `timeout` values are set as some operations might take a bit and its just easier to increase the timeout than trying to add retry logic. Adjust as needed.

## Script

Run this (and wait till finished) before performing a rolling restart.

```bash
#!/bin/bash
echo $(curl -k -X GET "https://${ES_USERNAME}:${ES_PASSWORD}@${ES_URL}:9200/_cat/indices/restored-*?h=i,id,n&v&expand_wildcards=open,hidden&format=json") | jq -rc '.[] ' | while read row; do
        echo "--------------------Start---------------------------------"
        index_name=$(echo "${row}" | jq -r '.i')
        echo "Index Name/Id: ${index_name}"
        echo ""
        echo "Get Shard Data:"
        echo $(curl -k -X GET "https://${ES_USERNAME}:${ES_PASSWORD}@${ES_URL}:9200/_cat/shards/${index_name}?h=i,id,n&format=json")  | jq -rc '.[] ' | while read row1; do
        echo ""
        echo "Shard Data:"
        echo "${row1}"
        index_name1=$(echo "${row1}" | jq -r '.i')
        node_id1=$(echo "${row1}" | jq -r '.id')
        node_name1=$(echo "${row1}" | jq -r '.n')
        echo ""
        echo "Index Name/Id: ${index_name1}"
        echo ""
        echo "Node Id: ${node_id1}"
        echo ""
        echo "Node Name: ${node_name1}"
        echo ""
        echo "Curl Index-level Shard Command"
        curl_command=$(curl -k -X PUT "https://${ES_USERNAME}:${ES_PASSWORD}@${ES_URL}:9200/${index_name1}/_settings?timeout=120s" -H 'Content-Type: application/json' -d "{\"index.routing.allocation.require._name\": \"${node_name1}\"}")
        echo ""
        echo "Curl Command Output"
        echo ""
        echo "${curl_command}"
        done
        echo "---------------------End---------------------------------"
done
```

## Explanation

1. Get a list of all indices that match our pattern (`restored-*`) (including hidden) via `_cat/indices`.
5. Loop through this list
    1. Get the shard information of the index via `_cat/shards`
        1. **Note:** Can't use `_cat/shards` initially because of: https://github.com/elastic/elasticsearch/issues/84656 where `restored-*` doesn't expand `hidden` indices/shards
    2. Get the index name (`index_name1`), node id (`node_id1`), and node name (`node_name1`) of the shard.
        1. **Note:** The script only really uses index name (`index_name1`) and node name (`node_name1`), but include the node id (`node_id1`) for debugging/troubleshooting.
    4. Update the shard's index settings to lock `index.routing.allocation.require._name` to its current node name (`node_name1`)
        1. This locks the shard/index to its current node, therefore when the node restarts, Elasticsearch won't attempt reallocate it.

## Cleanup

After the rolling upgrade is complete, to be able to allow for allocations to go back to normal, `null` out the routing allocation change:

```bash
curl -k -X PUT "https://${ES_USERNAME}:${ES_PASSWORD}@${ES_URL}:9200/restored-*/_settings?timeout=120s&expand_wildcards=open,hidden" -H 'Content-Type: application/json' -d "{\"index.routing.allocation.require._name\": null}"
```

**Comment by rjernst** [comment]
@henningandersen I've reassigned to distributed as you all have the expertise to update `SearchableSnapshotEnableAllocationDecider` to be shutdown aware.
