### ISSUE TITLE
[Feature Request] Have _unmount API for searchable snapshot

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#85088]
## Description

For searchable snapshot, 
- Cold tier will have the primary shard data on cold nodes
- Frozen tier will have the shard cache on frozen nodes 

When we want to disable the cold tier or frozen tier, currently the only flow is to (A) restore it from the snapshot and then (B) let it move to other tiers and then disable it.

However, due to the following 2 reasons,

- Cold node: Given the primary shard data is already sitting on the cold nodes, there's no really need to restore it again. Instead, cutting the connection between the shard and searchable snapshot (established by mount) can make things much faster.
- Frozen tier: While restore operation is needed, it's somehow confusing that, why we say it "restore", but we say it "partially mounted" during the mounting process.

That said, given today we have [mount snapshot API](https://www.elastic.co/guide/en/elasticsearch/reference/current/searchable-snapshots-api-mount-snapshot.html), it would be great if we could have a `_unmount` API, that could serve:
- Cold node: Simpy cut down the connection between primary shards and searchable snapshot (maybe good to remove the prefix `restored-` it too?)
- Frozen node: Same function as `_restore` but being more understandable in the way of calling it

## Addtionally

- Things can be more useful if we add an option to update the index tier preference, to let it rehome to other tiers (as it's the general use case when we need to disable a tier with searchable snapshot).
- There's [another ticket](https://github.com/elastic/elasticsearch/issues/73947) talking about unmount, but seems to be a different context.

**Comment by original-brownbear** [comment]
We discussed this during our team sync and feel that the significant effort required to build this is not worth it at this point when there's the option to manually do what is asked of this API via the restore API (albeit with extra steps).

-> closing here for now
