### ISSUE TITLE
Search User Profiles needs to support "source" paremter

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#85090]
### Description

In Elasticsearch, all GET requests that have a body must also support that body being passed as a URL parameter named `source`. (This is because GET requests with a body are not standardized and not all clients can support it.)

The `RestSearchProfilesAction` does not support the "source" parameter, as shown in this test failure:
```
./gradlew ':x-pack:plugin:yamlRestTest' \
  --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=user_profile/10_basic/Test search user profile}"  \
  -Dtests.seed=70BB2C6E68358B31 -Dtests.locale=lv -Dtests.timezone=Europe/Skopje \
  -Druntime.java=17 -Dtests.fips.enabled=true
```

You can solve this by switching `hasContent` + `contentParser` to `hasContentOrSourceParam()` + `contentOrSourceParamParser()` (for an example, see `RestQueryApiKeyAction`)

**Comment by ywangd** [comment]
Thanks for raising this Tim. Luckily the search API has not been release yet. I'll fix it along with a few other adjustments to the API earlier next week.
