### ISSUE TITLE
Update Gradle wrapper to 7.5

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#85123]
Gradle 7.5 (snapshot) comes with(at least)  two breaking changes in our build.

1) The api of `SharedResource#getResourceLock()` that we use in `StandaloneRestIntegTestTask` has changed
2) Checkstyle tasks are not ran as separate process using the Gradle worker API. That is giving us a huge benefit as it allows us multiple checkstyle tasks for the same gradle project can been run in parallel now. However, how this initially work has finally ended up in Gradle master broke `:server:precommit` as the checkstyleMain and checkstyleTest require more than the default heap. We provided a fix for this to the Gradle team via this PR already: https://github.com/gradle/gradle/pull/20198

**Comment by breskeby** [comment]
With the latest 7.5 snapshot we now see issues with our example plugins build:

```
> Task :custom-suggester:build
11:23:34 Unable to make progress running work. The following items are queued for execution but none of them can be started:
11:23:34   - :elastic+elasticsearch+pull-request+example-plugins:distribution:archives:buildLinuxTar (not ready)
11:23:34   - SymbolicLinkPreservingUntarTransform (dependencies not complete)
11:23:34   - :painless-whitelist:yamlRestTest (dependencies not complete)
11:23:34   - :painless-whitelist:check (dependencies not complete)
11:23:34   - :painless-whitelist:build (dependencies not complete)
11:23:34   - SymbolicLinkPreservingUntarTransform (dependencies not complete)
11:23:34   - :security-authorization-engine:javaRestTest (dependencies not complete)
11:23:34   - :security-authorization-engine:check (dependencies not complete)
11:23:34   - :security-authorization-engine:build (dependencies not complete)
11:23:34   - producer locations for task group 0 (dependencies not complete)
11:23:51 build complete, generating: /dev/shm/elastic+elasticsearch+pull-request+example-plugins/build/583.tar.bz2
11:23:52 
11:23:52 FAILURE: Build failed with an exception.
11:23:52 
11:23:52 * What went wrong:
11:23:52 Unable to make progress running work. There are items queued for execution but none of them can be started
11:23:52 
11:23:52 * Try:
11:23:52 > Run with --info or --debug option to get more log output.
11:23:52 
11:23:52 * Exception is:
11:23:52 java.lang.IllegalStateException: Unable to make progress running work. There are items queued for execution but none of them can be started
11:23:52 	at org.gradle.execution.plan.DefaultPlanExecutor$Queue.assertHealthy(DefaultPlanExecutor.java:283)
11:23:52 	at org.gradle.internal.resources.DefaultResourceLockCoordinationService$2.transform(DefaultResourceLockCoordinationService.java:83)
11:23:52 	at org.gradle.internal.resources.DefaultResourceLockCoordinationService$2.transform(DefaultResourceLockCoordinationService.java:80)

```

**Comment by mark-vieira** [comment]
Hmm, this seems to be only when running in a composite yes? The transforms being in the list are interesting. I'm wondering if something changed there.

**Comment by breskeby** [comment]
I'm pretty sure something must have changed.  I'm reaching out to the gradle team. I've seen this locally once but also noticed that the first listed task actually has been executed correctly. Also you can see from the output that included builds rootProject name is not taken into account.  Seems to pay off to test gradle snapshots early, though I initially only wanted to double check the checkstyle improvements.

**Comment by breskeby** [comment]
raised https://github.com/elastic/elasticsearch/issues/85123

**Comment by mark-vieira** [comment]
> raised #85123

I think you mean https://github.com/gradle/gradle/issues/20254, yes?

**Comment by breskeby** [comment]
Yes 🤦🏻‍♂️

**Comment by breskeby** [comment]
This is now also blocked by a regression in artifact transforms: https://github.com/gradle/gradle/issues/20659
