### ISSUE TITLE
Elasticsearch Stack Monitoring should include the node roles

### ISSUE THREAD

**Issue by philippkahr** [elastic/elasticsearch#85208]
### Description

When I look into the stack monitoring I can see the name, cpu, java heap and so on. It would be practicable if I can sort by node role as well, so I can quickly see if my hot nodes are filling up, or if my warm nodes are getting a lot of searches.

**Comment by DJRickyB** [comment]
Hi @philippkahr this would be a Kibana issue, not Elasticsearch

**Comment by philippkahr** [comment]
@DJRickyB I think it is Elasticsearch first because Elasticsearch needs to expose the node roles for metricbeat to collect. 

If I look into the [node](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node.html) and [node_stats](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-elasticsearch-node_stats.html) metricsets from Metricbeat there is no node role field.

**Comment by DJRickyB** [comment]
Then this would be a Beats issue, as the node roles are exposed already in
the nodes APIs.  Looks like one already exists:
https://github.com/elastic/beats/issues/25968

**Comment by philippkahr** [comment]
Oh thank you! Totally missed that one. Sorry for the noise!
