### ISSUE TITLE
Shard delay aggregation analog for SQL search

### ISSUE THREAD

**Issue by Dosant** [elastic/elasticsearch#85214]
### Description

In Kibana we extensively use [shard_delay](https://github.com/elastic/elasticsearch/pull/62082) agg for manual and automated testing of scenarios with long-running searches and [search-sessions](https://www.elastic.co/guide/en/kibana/master/search-sessions.html)

We would like to have a way to simulate slow searches running through [SQL API](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-async.html)

Since we actually test scenarios around async search APIs slowing down the network doesn't work for all the cases that we'd like to cover.

Some examples:

- When clicking "refresh" Kibana deletes the previous search
- Kibana properly restores a search session with searches that are still running

**Comment by luigidellaquila** [comment]
Hi @Dosant 

As of now in SQL we do not have anything equivalent to `shard_delay`, and unfortunately there is no straight-forward way to  extend it with a plugin running only in the test scope (as DelayedShardAggregationPlugin does).

Can you please share more details on what you need here? Do you only need a slow query response? In this case, would it be possible to just simulate it on the client side (eg. with a proxy)?

Thanks

Luigi

**Comment by Dosant** [comment]
Hi @luigidellaquila, 

We use it in Kibana for manual and automated testing of long-running searches and [search-session feature ](https://www.elastic.co/guide/en/kibana/master/search-sessions.html) implemented with async search.  So since we actually test scenarios around async search APIs slowing down the network doesn't work for all the cases. 
Some examples:
- When clicking "refresh" Kibana deletes the previous search
- Kibana properly restores a search session with searches that are still running 


> and unfortunately there is no straightforward way to extend it with a plugin running only in the test scope (as DelayedShardAggregationPlugin does).

:( 

Do you happen to know if the same is for any other async_search API? e.g. is this also applicable for async search in EQL?

**Comment by wchaparro** [comment]
Superceded by ES|QL
