### ISSUE TITLE
Can `random_sampling` be more CPU and I/O-friendly?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#85231]
### Description

`random_sampling` tries to include about 1 every N docs on average for aggregations.

This is a worst-case scenario both from a I/O perspective, as we might load entire pages into the filesystem cache only to read one entry, and from a CPU perspective as many things in Lucene are stored in blocks so we're forcing full blocks to be decompressed only to read a single value.

Would it be possible for sampling to be more CPU and I/O-friendly, e.g. by including 100 docs every 100*N docs on average, instead of 1 every N docs?

cc @benwtrent

**Comment by benwtrent** [comment]
//CC @tveasey

**Comment by tveasey** [comment]
Yes. I think we can be better here and this is something I considered in the past as well.

I'm not sure I would hard code something like 100 docs every step ~ Geometric(p/100). My inclination was something like flipping between sampling on two scales: step ~ Geometric(10 * p) and step ~ Geometric(p / 10) at random. I believe roughly the same properties will still hold, but this will have somewhat higher variance as an estimator in general. This might mean it isn't as effective for all index styles, for example you might be able to measure a difference in quality if data are sorted.

This should be a simple enough change to try out, the bulk of the work would be checking results. We may actually want to allow the API to take the parameter 100 / 10 for the lumpiness of the sampling.

**Comment by wchaparro** [comment]
Closing as not planned, focus on implementing this in ES|QL.
