### ISSUE TITLE
Runtime field has precision error when creating Geo Point field

### ISSUE THREAD

**Issue by jeffvestal** [elastic/elasticsearch#85253]
### Elasticsearch Version

8.1

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

When creating a Geo Point runtime field, the output has a precision error resulting in a value with a large number of decimal points rather than the exact value. 

Emitting `-37.91, 144.66` creates a point field `144.6599999908358 -37.91000002529472`
rather than just `144.66 -37.91`

Related [code snippet](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/script/GeoPointFieldScript.java#L146..L150) 
```
    protected final void emit(double lat, double lon) {
        int latitudeEncoded = encodeLatitude(lat);
        int longitudeEncoded = encodeLongitude(lon);
        emit(Long.valueOf((((long) latitudeEncoded) << 32) | (longitudeEncoded & 0xFFFFFFFFL)));
    }
```

### Steps to Reproduce

Create a runtime field with the type geo_point and code 
```
emit(-37.91,144.66)
```

**Comment by jeffvestal** [comment]
cc: @stu-elastic

**Comment by iverase** [comment]
This is actually fixed in https://github.com/elastic/elasticsearch/pull/85449, closing.
