### ISSUE TITLE
ClusterHealthStatus.fromString can throw NPE

### ISSUE THREAD

**Issue by Oliverwqcwrw** [elastic/elasticsearch#85258]
### Elasticsearch Version

8.1.1

### Java Version

17.0.2

### OS Version

Mac OS 12.3

### Problem Description

In `org.elasticsearch.cluster.health.ClusterHealthStatus#fromString`

`status` no non-empty verification, easy to occur NPE

### Steps to Reproduce

when `status` is null ,it appears to NPE

**Comment by OlivierCavadenti** [comment]
This NPE cause the problem here : https://github.com/elastic/elasticsearch/issues/84902

**Comment by Oliverwqcwrw** [comment]
Add verify null value?
