### ISSUE TITLE
Use aliases to perform cross cluster searches

### ISSUE THREAD

**Issue by lanerjo** [elastic/elasticsearch#85293]
### Description

This would be a very useful option to have.
I can think of many use cases that this would come in very handy. Consider one of my particular use cases, where we ingest 6tb of primary data per day, with over 4 billion events per day. This scale without cross cluster search is nearly impossible to manage efficiently, the cluster state grows large very quickly.

When architecting data sets (beyond just logs), it is often useful to join multiple datasets together in a single query inside kibana, the best way to handle this is to use aliases.
When architecting a highly resilient, minimal blast radius when having performance issues in a cluster, it is better to have multiple smaller clusters rather than 1 huge all encompassing cluster.
When considering the above 2 points, cross cluster search using aliases would be very helpful, This really wouldn't be too much more difficult than how kibana stores saved objects currently, such that kibana stores index patterns in the .kibana index currently.

**Comment by jtibshirani** [comment]
@lanerjo thanks for reaching out. For your use case, would it work to create a Kibana index pattern containing the remote clusters? Could you explain why it's much more convenient to use index aliases?

For context, we've discussed support for remote clusters in index aliases here: https://github.com/elastic/elasticsearch/issues/43312.

**Comment by lanerjo** [comment]
Let's say you have a subset of data in one cluster due to size, and perhaps some other data in another cluster, but you need to be able to join the data transparent to the user, or perhaps the user needs to search all the data...

Let's imagine that the combined datasets are too large to be in one cluster, due to cluster state, shard sizes, memory limits, cpu limits, etc.

example:
Cluster1:dataset1
Cluster2:datasetsub2
cluster2:datasetsub3

User needs to query all the data in one visualization. 

Honestly, an index pattern would be ideal for this purpose. Kibana however does not really allow this with the way that index patterns are managed.

The best way to implement something like this, would be to rework the way that kibana manages index patterns, allow an "alias" (index pattern) to point to indices with different names, rather than datasset* (or aliases).
So that:
kibana_index_pattern1 can be shortcut to querying Cluster1:dataset1, Cluster2:datasetsub2, and any combination an administrator can dream up.

**Comment by javanna** [comment]
I am no expert but could you not use *:dataset* in the Kibana index pattern to match all relevant indices from all clusters?

**Comment by javanna** [comment]
Given that adding remote indices to aliases is already tracked in #43312, I am closing this issue. Also I'd reroute to the kibana repo for the kibana related issues around accessing remote indices.
