### ISSUE TITLE
Applying a different ILM policy should reset the previous ILM policy's state, also respect the current tier in use

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#85384]
### Elasticsearch Version

7.x, 8.x

### Java Version

_bundled_

### OS Version

major version

## Background & Use case

An effective use case is when user wants to disable a data tier.
For example, the user might want to disable the frozen data tier, restore the index from snapshot to disk, and switch the tier from frozen to i.e. warm tier.
In this situation, since ILM is usually applied for moving phases, the user might want to reapply a new ILM policy, different from the previous one (moving indices to frozen), but the one only handling i.e. moving to cold tier, or defining a delete phase.

In such situation, the user may want to have:
- the new ILM to be applied to the target index
- ILM starts from a new phase (i.e. hot/warm)
- Also because user may restore the index to the warm tier, it could be helpful to move the phase to warm phase as well

However, currently, reapplying ILM will not automatically achieve the above, but it only keeps the previous ILM phase & step.

For example, after reapplying new ILM policy, user may have following index setting

<details>

```

GET test-frozen-index-1/_settings
{
  "test-frozen-index-1" : {
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "test-cold-policy",
          "rollover_alias" : null
        },
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_warm,data_hot"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "test-frozen-index-1",
        "creation_date" : "1648441032685",
        "priority" : "100",
        "number_of_replicas" : "1",
        "uuid" : "56ihOS8tR2iOBoblTDN4Yw",
        "version" : {
          "created" : "7170199"
        }
      }
    }
  }
}
```

</details>

But actually the index is still in frozen phase of the previous policy, without being reset to recognize the new desired ILM policy.

<details>

<img width="600" alt="image" src="https://user-images.githubusercontent.com/30574753/160384790-079dc932-c90c-40a7-97bb-128216064e81.png">

</details>

User has to use move phase API to manually move it to the desired phase, which is not very convenient.

### Steps to Reproduce

1. configure one ILM and let index move to become searchable snapshot
2. restore it from snapshot with following command for example

```
POST _snapshot/found-snapshots/2022.03.28-test-frozen-index-1-test-frozen-policy-vvfkbqe7qkmwvgq1fsouea/_restore
{
  "indices": "*",
  "index_settings": {
    "index.routing.allocation.include._tier_preference": "data_warm,data_hot",
    "number_of_replicas": 1,
    "index.lifecycle.name": test-cold-policy,
    "index.lifecycle.rollover_alias": null
  }
}
```

3. check the index setting and ILM phase. index setting has the new ILM policy, but ILM phase is still holding the old one.

@andreidan  Sorry to ping you directly Andrei but I know you are the expert in this area 🙏 Appreciate if you can share some insights regarding this and thanks!

**Comment by kunisen** [comment]
I had some new findings:

- If I remove the ILM policy as below (per manual: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-lifecycle-policy.html#apply-policy-multiple)

```
POST test-frozen-index-1/_ilm/remove
```

- And then I apply the new ILM policy:

```
PUT test-frozen-index-1/_settings
{
  "index.lifecycle.name": "test-cold-policy"
}
```

Then the ILM policy can be switched to a different one as per desired.

Also I noticed this banner. Now I understand what it means.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/30574753/160395792-2b1e6947-129c-46a8-9625-9739a3fde345.png">

---

While there are still some small confusions here:
- move phase API will reset `index.lifecycle.origination_date` to a new date, thus it will take some time to move to a next phase
- `_remove` will not reset `index.lifecycle.origination_date` to a new one

This can cause a surprise if user restore the index from searchable snapshot and apply an i.e. cold policy/deletion policy, the indices may become another searchable snapshot in cold tier or get deleted suddenly, due to it has stayed in frozen phase for a long time.

---

But aside from above, I think the behavior is clear to me. 
Thanks!

**Comment by andreidan** [comment]
@kunisen Thanks for the ping.

What do you mean by 
```
move phase API will reset index.lifecycle.origination_date to a new date, thus it will take some time to move to a next phase
```

Can you please give an example of which API you used, what is the date reset to, and how did you read this date - ilm explain, or index setting? What's the "new date"?

**Comment by kunisen** [comment]
Sorry for the late reply @andreidan and sorry for not being clear.

Maybe I shouldn't say `index.lifecycle.origination_date` but I should say `min_age`.

Actually my issue is that, during my test, 
- I found that just applying a different ILM policy didn't reset the previous ILM policy's state, which can cause some surprise.
- As you can see by restoring the frozen indices from searchable snapshot and applying another `test-cold-policy`, it got moved to the cold phase right after I applied the new ILM policy (and the ILM picks up it)
- But actually I was expecting it to start from `data_warm` tier at first, and unfortunately it didn't

```
POST _snapshot/found-snapshots/2022.03.28-test-frozen-index-1-test-frozen-policy-vvfkbqe7qkmwvgq1fsouea/_restore
{
  "indices": "*",
  "index_settings": {
    "index.routing.allocation.include._tier_preference": "data_warm,data_hot",
    "number_of_replicas": 1,
    "index.lifecycle.name": test-cold-policy,
    "index.lifecycle.rollover_alias": null
  }
}
```

- Also when I did follow the manual and performed the remove action `POST test-frozen-index-1/_ilm/remove`, and reapplied the `"test-cold-policy"` ILM policy again, it did work as the way I expected, which means start allocated on warm node and then stands for days and then move to cold phase.

---

While I also understand it might depend on user, whether they want to have it move to cold phase right after restore (as said above), or to let the index stay on warm node, I am hoping it might be better for us to have the way to choose this.
Either by having a flag, and 
- setting that to `true` could let ES ignore the `min_age`, and have the remove API running in the backend which means to reset the ILM state in one restore step, 
- or setting that to `false` could make it move to the tier based on the `min_age`

---

Hope the above is clear and thanks again!

**Comment by andreidan** [comment]
@kunisen 

Sorry for the late reply.

> My understanding is that, this is because min_age is elapsed and index moved to the corresponding phase.

ILM doesn't "jump" a phase just because the min_age is lapsed. It'll always go sequentially through the phases (from hot -> frozen) when a policy is applied. The fact that min_age is lapsed will cause the index to not **stay** in a certain phase ie. it will not stay in `warm` after executing `shrink` because the `min_age` condition for `cold` is met so it will go into `cold` immediately after the actions in `warm` are executed.

Hope this clarifies the seen behaviour?

**Comment by kunisen** [comment]
Thanks @andreidan for the detailed explanation!

I know it's by design now (`min_age` is the source of truth and it doesn't get reset even we change the ILM policy).
Maybe it's better to provide an option that we could reset the `min_age` when we want to apply a different ILM policy to the target index, as that should be also a reasonable use case. 

But since this is not a very highly-needed/popular request, please let me close it first.
If we see an increasing trend of such requests, please let me reopen it later if needed.

Thanks again for the great help as always! 🙏 🙇

**Comment by andreidan** [comment]
@kunisen 
>Maybe it's better to provide an option that we could reset the min_age when we want to apply a different ILM policy to the target index, as that should be also a reasonable use case.

If you want to influence `min_age` when applying a new policy so that the index waits in `warm` until the `cold` phase `min_age` is fulfilled (ie. simulate the index is "new" and starts ageing from now on) I recommend setting the `origination_date` setting to `now` just before applying a new policy (this way the age of the index will be calculated based on `now`)

e.g.
```
1. POST my-index-000001/_ilm/remove
2. PUT /my-index-000001/_settings
{
  "index" : {
    "lifecycle_name" : "new-policy",
    "index.lifecycle.origination_date": 1662451359
  }
}
```
