### ISSUE TITLE
[DOCS] Document time series data streams/improved support for metrics data

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#85415]
Document the new time series data stream (TSDS) functionality and how to set up a time series data stream for metrics data.

Initial draft is in the docs_tsds branch: https://github.com/elastic/elasticsearch/commit/0c5ea39eed690a09af6f5a6df6a6c2e13c73a689

Relates to: https://github.com/elastic/elasticsearch/issues/74660

**Comment by wchaparro** [comment]
close as completed with the GA release of TSDS
