### ISSUE TITLE
[DOCS] Review time series vs timestamped data terminology usage

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch#85416]
With the introduction of time series data streams, we need to revisit existing references to "time series data" so we're not overloading the term. The preferred term might be "timestamped data".

Initial audit: https://github.com/elastic/elasticsearch/compare/master...docs__time-series-audit

**Comment by kilfoyle** [comment]
After discussion in PR #87897 it was decided that having multiple terms `time series` and `timestamped` may create more confusion, and that a better approach might be to update some Glossary definitions related to TSDS. That work was completed  via https://github.com/elastic/stack-docs/pull/2193.

**Comment by DanRoscigno** [comment]
:)
