### ISSUE TITLE
[Bug] Not able to update .monitoring-8 templates via API but only able from UI

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#85435]
### Elasticsearch Version

8.1

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

Related to https://github.com/elastic/elasticsearch/issues/85434, I want to increase the `index.mapping.total_fields.limit` to `3000` for the time being.
But I couldn't do that from API.
The following request doesn't work.

```
GET _index_template/.monitoring-es-mb

PUT /_index_template/.monitoring-es-mb
{
  "index_patterns": [ ".monitoring-es-8-*" ],
  "data_stream": {  },
  "template": {
    "settings": {
      "index.mapping.total_fields.limit": "3000"
    }
  }
}
```

I could only do that from UI.

![image](https://user-images.githubusercontent.com/30574753/160563164-07a08578-a049-4b2f-83a9-2e7ea75bc9e4.png)

I don't know the reason but it seems like another bug to me.

### Steps to Reproduce

Run above API to update the index settings.

**Comment by dakrone** [comment]
@kunisen what is the actual error you get back when performing that request using the API?

Also, is this an existing template you're trying to change? If so, then it looks like it would potentially break things to have a template like that with no other mappings or settings.

**Comment by kunisen** [comment]
Thanks! @dakrone 

> what is the actual error you get back when performing that request using the API?

I didn't get any error. I got 200 response

<img width="800" alt="image" src="https://user-images.githubusercontent.com/30574753/160641363-281a88ee-7888-43ce-9da2-36b15e16525a.png">

---

> Also, is this an existing template you're trying to change? If so, then it looks like it would potentially break things to have a template like that with no other mappings or settings.

Yes, this is an existing template I am trying to change.
The reason I wanted to change is stated in https://github.com/elastic/elasticsearch/issues/85434, the default setting of the field count limit is not enough to ingest data.

I followed the manual to perform the change:
https://www.elastic.co/guide/en/elasticsearch/reference/8.0/data-streams-change-mappings-and-settings.html#change-dynamic-index-setting-for-a-data-stream

**Comment by kunisen** [comment]
Thanks again and very sorry for not being clear. @dakrone 
I used the API and it told me 200 ok response, but the value actually remains the same and unchanged.

This is the request and response I got via API.
_Also as mentioned above, using Kibana UI I can change it..._

```bash
# update "index.mapping.total_fields.limit": "3000"
PUT /_index_template/.monitoring-es-mb
{
  "index_patterns": [ ".monitoring-es-8-*" ],
  "data_stream": {  },
  "template": {
    "settings": {
      "index.mapping.total_fields.limit": "3000"
    }
  }
}


# check
GET /_index_template/.monitoring-es-mb?filter_path=**.index.mapping.total_fields.limit


# response
{
  "index_templates" : [
    {
      "index_template" : {
        "template" : {
          "settings" : {
            "index" : {
              "mapping" : {
                "total_fields" : {
                  "limit" : "2000"
                }
              }
            }
          }
        }
      }
    }
  ]
}
```

**Comment by kunisen** [comment]
The reason I want to change from API is, 
- Changing template from UI needs more steps and it's complicated (and it's hidden by default due to it's system template)
- Changing template from API is very logically easily understandable, only changing the required setting seems to be enough

Hope it's clear.

**Comment by lucabelluccini** [comment]
An addendum to this:
- Modifying the built-in template for `.monitoring-8` indices doesn't guarantee the changes will be kept. An upgrade to a newer version of Elasticsearch might overwrite the template or a new template with higher priority might be introduced
- We need to update the docs to document how we can tweak those index templates if necessary (at least number of shards and replicas). The docs only mention 7 indices: https://github.com/elastic/beats/issues/30877 and https://github.com/elastic/elasticsearch/issues/85873
- I think the proper way to handle this would be to introduce a composite template `.monitoring-8@custom` as we do for integrations, which would allow to override some settings with future-proof guarantees

**Comment by lucabelluccini** [comment]
I'm reviewing this in the scope of O11y / Stack Monitoring.

I cannot reproduce the problem, at least in 8.4.0
The `PUT _index_template/<ID>` API doesn't support partial updates so you will need to get the whole original template, you cannot just override a single value.

In any case, we should discourage allowing tweaking the built-in templates and instead possibly open up to customizing them via a default `@custom` composite template.

**Comment by kunisen** [comment]
Thanks @lucabelluccini 
I understand this is discouraged behavior, however, as mentioned in my initial post, I had to try this change because of https://github.com/elastic/elasticsearch/issues/85434.

Also I now understand that, I can perform the change via UI because in UI probably it uses the whole template as the payload but not I just do it via API with partial fields.
That makes sense to me why such behavior discrepancy happened.

I am gonna close this one as the doubt is now clearly solved. Thanks again! 🙇
