### ISSUE TITLE
[Bug] New .monitoring-8 templates can hit "Limit of total fields [2000]" by default

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#85434]
### Elasticsearch Version

8.0.1

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

On ESS, when using a dedicated monitoring cluster to receive the monitoring related metrics from production deployment, the following `Limit of total fields [2000] has been exceeded` may get hit.

```
[.ds-.monitoring-es-8-mb-2022.03.xx-0000xx][0] mapping update rejected by primary
java.lang.IllegalArgumentException: Limit of total fields [2000] has been exceeded
	at org.elasticsearch.index.mapper.MappingLookup.checkFieldLimit(MappingLookup.java:274) ~[elasticsearch-8.0.1.jar:8.0.1]
	at org.elasticsearch.index.mapper.MappingLookup.checkFieldLimit(MappingLookup.java:265) ~[elasticsearch-8.0.1.jar:8.0.1]
	at org.elasticsearch.index.mapper.MappingLookup.checkLimits(MappingLookup.java:257) ~[elasticsearch-8.0.1.jar:8.0.1]
	at org.elasticsearch.index.mapper.DocumentMapper.validate(DocumentMapper.java:116) ~[elasticsearch-8.0.1.jar:8.0.1]
	at org.elasticsearch.index.mapper.MapperService.newDocumentMapper(MapperService.java:353) ~[elasticsearch-8.0.1.jar:8.0.1]
```

It means by default, the field number is not well-fit for the ES default limitation.
It might be great either we reduce the field count (design change), or we increase the total field limitation in the template some thing similar to, i.e. `"index.mapping.total_fields.limit": 3000`

cc @jbaiera as I get inspiration from your below great ticket :) Thanks!
https://github.com/elastic/elasticsearch/issues/81839

### Steps to Reproduce

1. Create 2 deployments on ESS, version both 8.0.1, one for prod, one for dedicated monitoring
2. Enable logging and monitoring, sending the metrics and logs to the dedicated monitoring cluster
3. Check logs

**Comment by kunisen** [comment]
Thanks! @dakrone  Indeed it looks like this one:
https://github.com/elastic/elasticsearch/pull/85447

But it looks like the dynamic template is already utilized in 8.0 and 8.1 version in my case.
Should we change the setting via UI to workaround the error?
Or should we also apply the same change in the template (for internal monitoring ones) and disable dynamic templates?

I understand upgrading to 8.2 is the best way to fix.
But I am a bit lost in how could we workaround this in 8.0 or 8.1.
Appreciate if you can share some more insights and thanks! 🙏

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
