### ISSUE TITLE
[Doc][Bug] Searchable snapshot doesn't have "recovered-" prefix but have "restored-" in 8.x

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#85432]
### Elasticsearch Version

8.x

### Java Version

_bundled_

### OS Version

supported major OS

### Problem Description

In manual, there's such description
https://www.elastic.co/guide/en/elasticsearch/reference/8.1/searchable-snapshots.html

> Indices managed by ILM are prefixed with `recovered-` when fully mounted.

Screenshot:

<details>

<img width="600" alt="image" src="https://user-images.githubusercontent.com/30574753/160521435-be0e0193-79b6-46e0-b30c-b8ebeb7bd784.png">

</details>

However, when testing the behavior, it's actually not using the prefix `recovered-`, but instead, it's using `restored-`.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/30574753/160521823-d7c4b4af-29fb-4ffd-abdb-5fab4dbe3310.png">

---

The prefix `restored-` is the same as 7.x, which is mentioned below.
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/ilm-searchable-snapshot.html

Also additionally, the following page 8.x version also shows the correct spelling.
https://www.elastic.co/guide/en/elasticsearch/reference/8.1/ilm-searchable-snapshot.html

---

Based on that, seemingly it's a simple typo when that line was added into the manual and it caused the confusion.
https://www.elastic.co/guide/en/elasticsearch/reference/8.1/searchable-snapshots.html#searchable-snapshot-mount-storage-options

### Steps to Reproduce

as mentioned above.

Can we have someone double check if this is a simple doc typo please?
I am happy to file a doc fix PR but want to check about the tech part at first.

**Comment by dakrone** [comment]
Just a small doc bug, I opened https://github.com/elastic/elasticsearch/pull/85457 to fix it.
