### ISSUE TITLE
In processPendingDeletes() method ,there is not deletion listener has been triggered。。

### ISSUE THREAD

**Issue by linlihub** [elastic/elasticsearch#85440]
### Elasticsearch Version
7.6.2

### location:
org.elasticsearch.indices.IndicesService

### why in processPendingDeletes() method does not have listener?

![image](https://user-images.githubusercontent.com/19384983/160586445-4320d1b5-6212-43be-ac07-dad0b3fa6c6f.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
