### ISSUE TITLE
Ability to set external request id and enhanced logging

### ISSUE THREAD

**Issue by kmakowski** [elastic/elasticsearch#8547]
I miss setRequestId() method in ES API. It would be good to bind API requests to some value specified on the client side. For example:

client.prepareSearch().setRequestId("SOME_STRING").execute().actionGet();

What I would like to achieve is an ability to group logs from various system components.

Assuming that we have a system containing 3 components:
- A - HTTP frontend
- B - My App 
- C - Elasticsearch

and communication chain is as follows:

CLIENT -> A (generation of unique request id happens here) -> B (with given request id) -> C (with given request id)

Now if there is an exception or warning logged in one of those systems it will be logged with request id bound to the request. So assuming that we have centralized logging infrastructure it would be very easy to track the root causes and side effects of problems that occur in the system.

**Comment by rayward** [comment]
Would love to see this attached to the slow query log so that I can trace bad queries back to an originating http request.

**Comment by IngaFeick** [comment]
I'd love to see this implemented aswell, but my use case would be for the normal logs, not the slow logs.

**Comment by jasontedor** [comment]
We have the `X-Opaque-Id` REST header that can be added to requests and is associated with any tasks triggered by that request and available in the task output API. We have separate issues to considering adding this header to the deprecation logs and will consider adding it to other places in the system. I am going to close this issue given that other work.

Relates #9669
