### ISSUE TITLE
Highlighting in Kibana is not working for match_only_text

### ISSUE THREAD

**Issue by philippkahr** [elastic/elasticsearch#85493]
### Elasticsearch Version

8.1.1.

### Installed Plugins

non

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

When searching for any term in Kibana the highlighting works on any field type except `match_only_text` which has become the default field type in ~7.14 for all of the beats and Elastic Agent integrations.
E.g. here it does not work:
![image](https://user-images.githubusercontent.com/12175559/160823534-7cad2e0e-b898-4a15-9376-1c2993d261bb.png)
E.g. on 7.17 using text and keyword fields:
![image](https://user-images.githubusercontent.com/12175559/160823810-a6024e92-f062-4e39-a399-41c5d087fcdd.png)

Discussed this with @romseygeek already. seems that the highlighter is not capeable of dealing with the specialized match_only_text field type.

### Steps to Reproduce

Index something using a `match_only_text` field.
Run a search on it. It should be highlighted.

**Comment by philippkahr** [comment]
@smnschneider thanks for discovering this!

**Comment by kertal** [comment]
@ywelsch If've got a follow up question, should highlighting work for `constant_keyword` fields, context: https://github.com/elastic/kibana/issues/127947#issuecomment-1084322654

**Comment by ywelsch** [comment]
> @ywelsch If've got a follow up question, should highlighting work for constant_keyword fields, context: https://github.com/elastic/kibana/issues/127947#issuecomment-1084322654

yeah, that would also be useful. Can you open a separate issue for it? Thank you.

**Comment by kertal** [comment]
Will do, thx!
