### ISSUE TITLE
Encounter exception while running Enterprise Search

### ISSUE THREAD

**Issue by ikngoo** [elastic/elasticsearch#85517]
### Elasticsearch Version

7.16.2

### Java Version

openjdk 11.0.14.1

### OS Version

Ubuntu 20.04

### Problem Description

Encounter exception while running Enterprise Search.
![image](https://user-images.githubusercontent.com/60819389/160969605-e6e6589f-7156-4895-92f4-6d14f4d6e948.png)

### Steps to Reproduce

First, I have elastic and kibana installed already and both functioning well.
But when I want to install Enterprise Search, by following the installation steps [here](https://www.elastic.co/downloads/enterprise-search), and encountered error at step 6 Set up Enterprise Search.

**Comment by DJRickyB** [comment]
Hello! This repository is for Elasticsearch, and issues are for Elasticsearch-specific bugs/enhancements. Please ask your question over in https://discuss.elastic.co for the Enterprise Search community to have a look.
