### ISSUE TITLE
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

### ISSUE THREAD

**Issue by hadesvip** [elastic/elasticsearch#85516]
### Elasticsearch Version

7.13

### Java Version

openjdk 15.0.2

### OS Version

Linux VM-16-8-ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

build from source fail

### Steps to Reproduce

1.  `./gradlew localDistro` 
2.  `./gradlew  assemble`

### Logs (if relevant)

 elasticsearch git:(7.13) ✗ ./gradlew assemble
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.0.1
  OS Info               : Linux 4.15.0-159-generic (amd64)
  JDK Version           : 15.0.2 (Oracle)
  JAVA_HOME             : /library/jdk-15.0.2
  Random Testing Seed   : 3BE189DB8DF993F0
  In FIPS 140 mode      : false
=======================================

> Task :distribution:archives:buildLinux UP-TO-DATE
Unable to watch the file system for changes. The inotify watches limit is too low.
Stopping file watching and invalidating VFS after an error happened

> Task :distribution:docker:buildDockerImage FAILED
Exec output and error:
| Output for docker:Sending build context to Docker daemon  327.2MB
> :distribution:docker:buildDockerImage
| Step 1/23 : FROM centos:8 AS builder
|  ---> 5d0da3dc9764
| Step 2/23 : RUN set -eux ;     tini_bin="" ;     case "$(arch)" in         aarch64) tini_bin='tini-arm64' ;;         x86_64)  tini_bin='tini-amd64' ;;         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;;     esac ;     curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ;     curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ;     sha256sum -c ${tini_bin}.sha256sum ;     rm ${tini_bin}.sha256sum ;     mv ${tini_bin} /bin/tini ;     chmod +x /bin/tini
|  ---> Running in 570f05a42cc5
| + tini_bin=
| + case "$(arch)" in
| ++ arch
| + tini_bin=tini-amd64
| + curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
100   647  100   647    0     0    624      0  0:00:01  0:00:01 --:--:--   624
100 24064  100 24064    0     0  10314      0  0:00:02  0:00:02 --:--:--  108k
| + curl --retry 10 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64.sha256sum
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
100   657  100   657    0     0   1207      0 --:--:-- --:--:-- --:--:--  1205
100    77  100    77    0     0     27      0  0:00:02  0:00:02 --:--:--    70
| + sha256sum -c tini-amd64.sha256sum
| tini-amd64: OK
| + rm tini-amd64.sha256sum
| + mv tini-amd64 /bin/tini
| + chmod +x /bin/tini
| Removing intermediate container 570f05a42cc5
|  ---> d4baf4c07d01
| Step 3/23 : RUN mkdir /usr/share/elasticsearch
|  ---> Running in 5c04eec9369e
| Removing intermediate container 5c04eec9369e
|  ---> 4fa22ce0eec1
| Step 4/23 : WORKDIR /usr/share/elasticsearch
|  ---> Running in 6a7e893f333f
| Removing intermediate container 6a7e893f333f
|  ---> df628c6e42a3
| Step 5/23 : COPY elasticsearch-7.13.5-SNAPSHOT-linux-x86_64.tar.gz /opt/elasticsearch.tar.gz
|  ---> 85c61edd2699
| Step 6/23 : RUN tar -zxf /opt/elasticsearch.tar.gz --strip-components=1
|  ---> Running in 6c65cb2fb980
| Removing intermediate container 6c65cb2fb980
|  ---> e0907ffb4172
| Step 7/23 : COPY config/elasticsearch.yml config/
|  ---> ff0c33112359
| Step 8/23 : COPY config/log4j2.properties config/log4j2.docker.properties
|  ---> 0c1da86999d0
| Step 9/23 : RUN sed -i -e 's/ES_DISTRIBUTION_TYPE=tar/ES_DISTRIBUTION_TYPE=docker/' bin/elasticsearch-env &&     mkdir -p config/jvm.options.d data logs plugins &&     chmod 0775 config config/jvm.options.d data logs plugins &&     mv config/log4j2.properties config/log4j2.file.properties &&     mv config/log4j2.docker.properties config/log4j2.properties &&     chmod 0660 config/elasticsearch.yml config/log4j2*.properties &&     find ./jdk -type d -exec chmod 0755 {} + &&     find . -xdev -perm -4000 -exec chmod ug-s {} + &&     find . -type f -exec chmod o+r {} +
|  ---> Running in 50049817df13
| Removing intermediate container 50049817df13
|  ---> 3429d8fd25c5
| Step 10/23 : FROM centos:8
|  ---> 5d0da3dc9764
| Step 11/23 : RUN for iter in {1..10}; do       yum update --setopt=tsflags=nodocs -y &&       yum install --setopt=tsflags=nodocs -y       nc shadow-utils zip unzip  &&       yum clean all &&       exit_code=0 && break ||         exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10;     done;     exit $exit_code
|  ---> Running in f8a699a00529
| CentOS Linux 8 - AppStream                       92  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 1 in 10s
| CentOS Linux 8 - AppStream                       51  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 2 in 10s
| CentOS Linux 8 - AppStream                       99  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 3 in 10s
| CentOS Linux 8 - AppStream                       27  B/s |  38  B     00:01    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 4 in 10s
| CentOS Linux 8 - AppStream                       81  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 5 in 10s
| CentOS Linux 8 - AppStream                       69  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 6 in 10s
| CentOS Linux 8 - AppStream                      101  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 7 in 10s
| CentOS Linux 8 - AppStream                       28  B/s |  38  B     00:01    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 8 in 10s
| CentOS Linux 8 - AppStream                       85  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 9 in 10s
| CentOS Linux 8 - AppStream                       80  B/s |  38  B     00:00    
| Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
| yum error: retry 10 in 10s
| The command '/bin/sh -c for iter in {1..10}; do       yum update --setopt=tsflags=nodocs -y &&       yum install --setopt=tsflags=nodocs -y       nc shadow-utils zip unzip  &&       yum clean all &&       exit_code=0 && break ||         exit_code=$? && echo "yum error: retry $iter in 10s" && sleep 10;     done;     exit $exit_code' returned a non-zero code: 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:docker:buildDockerImage'.
> A failure occurred while executing org.elasticsearch.gradle.docker.DockerBuildTask$DockerBuildAction
   > Process 'command 'docker'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 48s
1454 actionable tasks: 164 executed, 1290 up-to-date
Gradle was unable to watch the file system for changes. The inotify watches limit is too low.

**Comment by mark-vieira** [comment]
CentOS 8 is end of life, and as a result the package repositories have been shutdown. We've since switched away from CentOS as the base of our Docker images for this reason.
