### ISSUE TITLE
[EQL] Needs to work CCS across different versions

### ISSUE THREAD

**Issue by a03nikki** [elastic/elasticsearch#85579]
### Elasticsearch Version

7.16.3

### Installed Plugins

default

### Java Version

_bundled_

### OS Version

ECK managed pods

### Problem Description

EQL does not work if the versions of Elasticsearch do not match.  CCS has the promise that it will work across multiple Elasticsearch versions, unlike the old removed Tribe node architecture.

For large environments where all of the data does not fit in a single Elasticsearch cluster of reasonable size (50 nodes or fewer), more than one cluster needs to be be deployed.  They are "joined" back together by cross cluster search (CCS).  Additionally environments this large do not upgrade simultaneously either.  They take a few days to complete the rolling pod restarts.

It is not acceptable for EQL detection and queries to not work for an extended amount of time.  It reduces the security posture of the organizations using the Elastic Security solution.

### Steps to Reproduce

1. Create cluster running 7.14 to hold log data
2. Create cluster running 7.16 to hold more log data
3. Create 3rd cluster to act as search origin that cross cluster searches into the fist two clusters running 7.16
4. Try to run an EQL query or detection rule across the related data set in two different clusters

**Comment by luigidellaquila** [comment]
Hi @a03nikki 

Yes they do, thank you very much for pointing it out.
I'm closing this issue accordingly

Thanks

Luigi
