### ISSUE TITLE
Remove vim-tiny package from Docker image

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#85634]
For reasons that are unclear, we install the `vim-tiny` package in the Elasticsearch Docker image. Whilst convenient, this package is not actually necessary, therefore we should remove it.

**Comment by bytebilly** [comment]
I'm not against removing the package (even if I love to have a few useful tools when debugging an image), but I'm wondering if this could be considered a breaking change and so subject to our deprecation policy.

I know that users should not rely on the image content, but the reality is that there may be some impact and we need at least to discuss that.

**Comment by mark-vieira** [comment]
Without this would there be any way to inspect textfiles inside the container aside from, say, `cat | less` or similar?

**Comment by jkakavas** [comment]
> but I'm wondering if this could be considered a breaking change and so subject to our deprecation policy.

I don't think we've ever considered the removal of an OS package from our Docker images as a breaking change ( not one that I could find being referenced at least ) and in my view ( which, arguably, bears little importance here) we shouldn't consider this a breaking change. 

> Without this would there be any way to inspect textfiles inside the container aside from, say, cat | less or similar?

Yes there wouldn't be a straightforward way to edit text files (`apt install vim-tiny` is just a step away), but less and cat should be fine to view any configuration files. 

My arguments for removing this are: 

- Reducing our (both perceived and actual) attack surface by removing unnecessary packages from the base image. As an example, there are more than 17 CVEs published for vim only in 2022 and we have to keep responding to users around why we use vim in our images, how we are not affected and when we are going to upgrade. 
- Editing configuration files in the container is probably _not_ the best way to configure elasticsearch in docker. docker-compose files and setting the values in env variables, or mounting a config file from host is what we suggest in docs right ? 
- Viewing configuration files can be done with a number of other, pre-installed, tools 
- There doesn't seem to be an actual need for vim in the image. I deduce that from the fact that Elasticsearch is our only docker image that contains `vim` and I haven't been aware of any complaints or requests to add it to other images. I might be missing information here though, for sure. 


Thanks for the discussion folks :)

**Comment by bytebilly** [comment]
> in my view ( which, arguably, bears little importance here) we shouldn't consider this a breaking change.

That would have been my thinking too, before make it minor 🙂 
I think it's fine since vim is generally not used by automated scripts but rather by interactive humans, but maybe a quick confirmation by @qhoxie may help to remove the concern.

Since removing vim would have relevant benefits, I think that once we're sure about the breaking change this is a good tradeoff.

**Comment by pugnascotia** [comment]
I've merged a PR to remove `vim-tiny`, which will go out in `v8.4.0` and `v7.17.5`.
