### ISSUE TITLE
About IndexShard's maybeSyncGlobalCheckpoint method

### ISSUE THREAD

**Issue by Charele** [elastic/elasticsearch#85658]
public void maybeSyncGlobalCheckpoint(final String reason) {
...

This method, finally, try to run this:
globalCheckpointSyncer.run();

In fact,it's the execute "GlobalCheckpointSyncAction" action, let's see it:
private void maybeSyncTranslog(final IndexShard indexShard) throws IOException {

        if (indexShard.getTranslogDurability() == Translog.Durability.REQUEST
            && ...) {
            indexShard.sync();
        }
    }

However, if this index is "ASYNC"(not REQUEST), it's noop.

So, I think can add this short cut to the begin of IndexShard's maybeSyncGlobalCheckpoint():

    	if (indexSettings().getTranslogDurability() != Translog.Durability.REQUEST) {
    		return;
    	}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
