### ISSUE TITLE
How do I add field comments

### ISSUE THREAD

**Issue by tangjian99** [elastic/elasticsearch#85655]
### Elasticsearch Version

5.3.0

### Java Version

_bundled_

### OS Version

centos

### Problem Description

How do I add field comments

### Steps to Reproduce

1

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
