### ISSUE TITLE
Indicator Match - Rule Type: Correlation - Not Match Result Un Available

### ISSUE THREAD

**Issue by raghulannadurai** [elastic/elasticsearch#85716]
### Description

Good day to you all.

Hope the below example can give you more context to the request,

Let us consider the below,

1. we have a three document doc1, doc2 and doc3.
2. doc1 and doc2 were indexed into a index name A (firewall index)
3. doc 3 was indexed into a index name B (threat feed index)

doc1 in JSON

       {
            "_index": "A",
            "_type": "firewall",
            "_id": "1",
            "domain": "[test.com](http://test.com/)",
            "dstport": "80",
            "srcport": "22000"  
        }

doc2 in JSON

       {
            "_index": "A",
            "_type": "firewall",
            "_id": "2",
            "domain": "test1.com",
            "dstport": "443",
            "srcport": "11000"  
        }

doc3 in JSON

       {
            "_index": "B",
            "_type": "threatfeed",
            "_id": "3",
            "ioc": "test1.com"
        }

We wanted to create a rule/query to trigger an alert or to create visualization using "not match" condition by correlating Index A (Field - domain) and Index B (Field - ioc), i.e., from the above example we expect the result as "domain: test.com" - doc1 to be triggered as an alert or to be called in a visualization, as it does not match the condition.

We tried to achieve this using the rule type "Indicator match" but, it has the "match" option but "not match" option is not available. -Attached the screenshot for reference.

Do we have the feature available in elastic or any other work around to achieve this usecase?

**Comment by williamrandolph** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a question about the [Elastic Security Solution(https://www.elastic.co/guide/en/security/current/index.html), which is is not part of this repository. We don't develop detection rules here. I recommend asking this question in the [Elastic Security section](https://discuss.elastic.co/c/security/83) of our discuss forums.

If you are looking for advice on using Elasticsearch queries directly, we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
