### ISSUE TITLE
Allow spatial filtering by grid id

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch#85727]
### Description

Introduce a new spatial filter type for filtering based on grid-cell id. 

e.g.:

```
GET /example/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "geotile_grid": {
          "location": {
            "key": "12/25/124" 
            "relation": "within"
          }
        }
      }
    }
  }
}
```

or

```
GET /example/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "geohex_grid": {
          "location": {
            "key": "841969dffffffff" 
            "relation": "within"
          }
        }
      }
    }
  }
}
```

This has a few advantages:
- client does not need to know how to reconstruct the geometry from a grid-id. This is especially useful when geometries are spread across tiles.
- intersection calculation can match _exactly_ the intersection-test of Elasticsearch. e,g, if a client has a bounds for a grid-cell at a higher (or lower) precision than what is used by elasticsearch when running the corresponding aggregation, the containment-check might be slightly different. It also side-steps any disconnect based on projection/datum difference between client and Elasticsearch. Elasticsearch becomes the single truth of containment.

Having this spatial filtering more tightly links the idea of "cluster", both on the aggregation-level as well as the query-level. The aggregation is ideal for display (ie. "show the spatial cluster on map"), the filtering is ideal for identification (ie. "query for docs inside the spatial cluster).

**Comment by iverase** [comment]
Added in https://github.com/elastic/elasticsearch/pull/86596
