### ISSUE TITLE
Add top-level documentation page for disk watermarks

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#85741]
### Description

A common problem that Elasticsearch users encounter is reaching the disk watermark levels in their cluster. Information regarding watermarks is currently buried in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#disk-based-shard-allocation , under the heading `Disk-based shard allocation settings`. 

When searching in google, that page comes up first in the results:
<img width="880" alt="google_watermark" src="https://user-images.githubusercontent.com/19267722/162158571-de45b8b3-6076-499e-b9c7-d59a53f64f95.png">

But the result has no mention of the word "watermark". Even worse, several non-Elastic sites in subsequent search results _do_ include the term "watermark".

I think it would be helpful to create a freestanding page for watermarks. This page should also include suggestions for resolving such issues:
* Deleting indices
* Dropping replica shards
* Scaling up the cluster (either adding more nodes, or more disk space to existing nodes)

**Comment by debadair** [comment]
We've improved the troubleshooting information around watermarks, but the referenced topic is still out-performing the relevant troubleshooting information.  Not sure a top-level page for watermarks is the right answer, but we should revisit this to see if we can improve SEO for the most-relevant info.

**Comment by abdonpijpelink** [comment]
We've made some improvements to the watermark troubleshooting page in https://github.com/elastic/elasticsearch/pull/94222, that should make it easier for users to find this information. Let's revisit in a month to see whether findability has indeed improved.

**Comment by abdonpijpelink** [comment]
I think the changes in #94222 have paid off. The "Fix watermark errors" page now ranks as the highest Elastic docs page, for the Google query "elasticsearch watermark":

<img width="842" alt="image" src="https://github.com/elastic/elasticsearch/assets/9715543/32d50ccf-a1e8-4a32-8155-0097124905a5">

(we rank below a third party doc, but that's not something we have control over).

I'll close this issue, but feel free to reopen if you feel we need to make further improvements @bczifra
