### ISSUE TITLE
Strange results More Like This query

### ISSUE THREAD

**Issue by neilcoles** [elastic/elasticsearch#85757]
The documentation says to provide an `_id` and `_index` of the "like" document:
```
GET /_search
{
  "query": {
    "more_like_this": {
      "fields": [ "title", "description" ],
      "like": [
        {
          "_index": "imdb",
          "_id": "1"
        },
        {
          "_index": "imdb",
          "_id": "2"
        },
        "and potentially some more text here as well"
      ],
      "min_term_freq": 1,
      "max_query_terms": 12
    }
  }
}
```
My code hadn't been supplying `_index` and It all seemed to work, afterall the `_id` is enough to find the document. However now that I've included the `_index` the results of the MLT query are different, I can't understand what difference it is making

**Comment by romseygeek** [comment]
If you don't supply an `_index` parameter then it uses the index that the search was launched against. Do you have multiple indexes in your cluster?

**Comment by javanna** [comment]
The problem seems to have been identified. Please open a new topic on our forums at discuss.elastic.co if you need further help.

**Comment by neilcoles** [comment]
> > but with or without the _index being supplied the document being used for the MLT query is exactly the same
> 
> I don't think this is the case? If you ask to compare against document `1` but don't specify an index, then each shard will construct a MLT query using document `1` _from the index the shard belongs to_. And if those documents are different, then each MLT query will be different. Whereas if you do specify an index, then each shard will build its query using document `1` from the same index.

@romseygeek in my case `_id` is unique across all indices, so document 1 only exists once. Whether I supply `_index` or not the query does work, so it must be searching for that document across all indices to find it, so I'm still confused what difference supplying the `_index` could be making

**Comment by romseygeek** [comment]
If the document in question doesn't exist in the local shard, then that part of the MLT query will just be ignored, so you'll be getting results from the `"and potentially some more text here as well"` part of the query only.
