### ISSUE TITLE
Reduce script processor overhead from safety check

### ISSUE THREAD

**Issue by DJRickyB** [elastic/elasticsearch#85790]
Currently 99% of a profiled `script` processor's execution time comes from the invocation of `CollectionUtils.ensureNoSelfReferences()`, not the script itself (this could vary with script intensity, but it stands to reason it would take a lot to change this dramatically).
<img width="2552" alt="image" src="https://user-images.githubusercontent.com/7477841/162812089-a8d9f023-abf5-4249-b676-78b2adc459a1.png">

1. Is there another way we could approach this self-reference guard rail? It's not completely fool-proof but after the first document passes this check we can be reasonably sure the Script doesn't cause self-references, except in the case of some very specific conditional behavior one would almost have to intentionally code in. As this measure is to help users prevent shooting themselves in the foot, an ostensible 100x overhead is too high a cost, surely.
2. As a half-measure, should we not execute the check if the processor has `ignore_errors` set to `true` anyway? This is the case even for some published integrations, and could benefit greatly from the reduced overhead. It's not ideal as this particular problem really should probably not be ignored since it will cause issues in a later step, but this would preserve existing behavior and reduce cost.

**Comment by DJRickyB** [comment]
Note `script`'s status as the topmost contributor in ingest for our logging solution benchmarks: https://elasticsearch-benchmarks.elastic.co/#tracks/logging/nightly/default/30d

**Comment by stu-elastic** [comment]
We've had issues with `ensureNoSelfReferences` in the past: https://github.com/elastic/elasticsearch/issues/49277

**Comment by dakrone** [comment]
> 2. As a half-measure, should we not execute the check if the processor has `ignore_errors` set to true anyway? This is the case even for some published integrations, and could benefit greatly from the reduced overhead. It's not ideal as this particular problem really should probably not be ignored since it will cause issues in a later step, but this would preserve existing behavior and reduce cost.

I believe the cost of skipping this in the event someone does create a self-referential document inside of a script is either an OOME or a StackOverflow, both of which I don't think we want to try to cover by setting `ignore_errors` to true.

I do agree that it's very unfortunate that the overhead of the processor is contained so much in this one method, we should definitely discuss this and see if there's a better way we can handle it.

**Comment by DJRickyB** [comment]
> I believe the cost of skipping this in the event someone does create a self-referential document inside of a script is either an OOME or a StackOverflow, both of which I don't think we want to try to cover by setting ignore_errors to true and skipping the validation.

Currently even unchecked exceptions get silenced by `ignore_errors` https://github.com/elastic/elasticsearch/blob/cce3d924754a06634a8e353fa227be3af2eeca62/server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java#L210

**Comment by dakrone** [comment]
@DJRickyB actually it's not an issue because both an OOME and StackOverflow are errors instead of Exceptions, so they would bypass that `catch` block regardless.

**Comment by DJRickyB** [comment]
Sorry for the lack of clarity, I was referring to the existing `IllegalArgumentException` thrown by the ensureNoSelfReferences check already being ignorable (for the same circular reference condition)
