### ISSUE TITLE
[DOCS] ES docs inventory

### ISSUE THREAD

**Issue by nrichers** [elastic/elasticsearch#85848]
Survey current Elasticsearch guide and categorize non-API ref topics as:

- Freeze
- Carry forward with minor edits
- Reorganize/consolidate/rewrite

Link to the [ES guide inventory spreadsheet](https://docs.google.com/spreadsheets/d/1o0ApWb9Y5aNCnNAKNU26G2FbsvEW_9xMuRtCtAh8xEQ/edit#gid=0).

**Comment by lockewritesdocs** [comment]
Now that Deb and I have completed the inventory in the linked spreadsheet, I'm going to mark this issue as closed.
