### ISSUE TITLE
[DOCS] Consolidate CircuitBreakers

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#85851]
👋🏼 I see most CircuitBreakers returned via [GET Node Stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) `GET _nodes/stats?filter_path=nodes.*.breakers` (v7.17.2, v8.1.2) are listed in the main Elasticsearch [CircuitBreaker Doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html). However, the following are randomly scattered with their parent topic instead of consolidated with the rest. 
- [`eql_sequence`](https://www.elastic.co/guide/en/elasticsearch/reference/current/eql.html#eql-circuit-breaker)
- [`model_inference`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-settings.html#model-inference-circuit-breaker)

Would y'all consider consolidating these from their topics (still referenced/linked) into the main Circuit Breaker page to ease discoverability? 🙏🏼

**Comment by pdsing** [comment]
@stefnestor Please can I work on this issue?

**Comment by stefnestor** [comment]
For sure, thanks!

**Comment by akagra** [comment]
@pdsing is the issue is resolved ? I also want to work on this issue if you need any help?
