### ISSUE TITLE
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch not working on centOS stream.  gives a key import error.

### ISSUE THREAD

**Issue by ingenium21** [elastic/elasticsearch#85876]
### Elasticsearch Version

doesn't matter

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

5.14.0-75.el9.x86_64 #1 SMP PREEMPT Sat Mar 26 08:10:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I am trying to install elasticsearch in a centOS stream using rpm and following elastic's own directions.  
When I try to import the gpg key using rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch I get a 'key 1 import failed' error.  using -v doesn't give me anything useful either.  

### Steps to Reproduce

```rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch```

**Comment by breskeby** [comment]
@ingenium21 which elasticsearch version did you try to install?

**Comment by breskeby** [comment]
ah I see

**Comment by ingenium21** [comment]
I was able to get around it by change `gpgcheck=1` to `gpgcheck=0` in the elasticsearch.repo file.  But yes, ideally I would like to be installing applications with a valid gpg check.

**Comment by ingenium21** [comment]
No problem.  Happy to support such a cool product. 👍

**Comment by Blorpy** [comment]
Seeing the same issue on Alma 9, and I believe you are correct in that changes to RPM are causing this.

**Comment by nerijus** [comment]
A workaround on CentOS 9 is to run `update-crypto-policies --set LEGACY`.

**Comment by ingenium21** [comment]
oh nice.  Thanks Nerijus for the tip!

**Comment by hrw** [comment]
Will something happen here or should we just mark ELK stack as dead on RHEL9 family of systems?

**Comment by mark-vieira** [comment]
I'm reaching out to our release engineering team to get a status update on this. We should be able to update the signing key to sort out this problem.

**Comment by hrw** [comment]
@mark-vieira so how it went?

**Comment by hrw** [comment]
Not tried, but maybe this can help: https://old.nixaid.com/gpg-migration-sha1-to-sha2/ a bit?

Other idea: what about creating second key (modern one) and use it for signing rhel9 repo first (as you lack them anyway) and choose a date to switch old repos to a new key?

**Comment by jameswiggins** [comment]
I'm having the same problem installing logstash on Rocky Linux 9. The workaround from a redhat.com [blog post](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9#:~:text=I%20still%20want%20to%20install%20SHA%2D1%20signed%20packages!):
1. As @nerijus mentioned, switch to legacy crypto policy: `update-crypto-policies --set LEGACY` **OR** Explicitly allow SHA-1: `update-crypto-policies --set DEFAULT:SHA1`
2. Install whatever you need. I need to install logstash so: `dnf install logstash`
3. Switch back: `update-crypto-policies --set DEFAULT`

**Comment by ingenium21** [comment]
Thanks james.  I was considering moving to Rocky Linux 9 recently.  good to know it's happening there too.

**Comment by hrw** [comment]
It is problem on each RHEL9 rebuild. Alma Linux, Rocky Linux, Euro Linux etc.

**Comment by inputvalidation** [comment]
Checking in to see if this is still progressing? We have customers where we can't disable or allow SHA1 anymore due to security policies.

**Comment by matejzero** [comment]
Any news on this issue?

**Comment by Sxderp** [comment]
> We're trying to figure out what exactly needs to be done here. It seems you cannot _remove_ SHA-1 as a supported algorithm from a PGP key. It's actually mandatory according to the spec. I think the issue is the actual signature of the key itself, which implies we'll have to generate a new one and that has the potential to be disruptive for existing users. We're looking at how to sort this out in a backwards-compatible way.

Can you dual publish the RPMs? It's not disruptive for existing OS and it's already an issue with new OS.

**Comment by hrw** [comment]
Like @Sxderp wrote: make separete distro for EL9 family with separate gpg key.

Those on EL7/8 will use old SHA1 one, EL9 users will get new one.

Everything works for everyone.

**Comment by hrw** [comment]
anyway we stopped using elasticsearch in favour of opensearch so I am unsubscribing

**Comment by robertglonek** [comment]
same issue on ubuntu:22.04

Replication:
```
docker run -it --rm --name bob1 ubuntu:22.04 /bin/bash
apt-get update
apt-get -y install apt-transport-https ca-certificates curl gnupg
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list
curl -L https://artifacts.elastic.co/GPG-KEY-elasticsearch |apt-key add -
apt-get update && apt-get -y install elasticsearch
```

Result:
```
W: GPG error: https://artifacts.elastic.co/packages/8.x/apt stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D27D666CD88E42B4
E: The repository 'https://artifacts.elastic.co/packages/8.x/apt stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by robertglonek** [comment]
Nevermind, I just noticed you add the `signed-by` bit.

**Comment by mark-vieira** [comment]
We intend on generating a new signing key for these artifacts that will be used for future versions of Elastic stack releases.

**Comment by Mose-** [comment]
> We intend on generating a new signing key for these artifacts that will be used for future versions of Elastic stack releases.

Is there an ETA on this? I have package requirements in an enterprise environment where `update-crypto-policies --set FIPS:OSPP` is mandatory and rpm signatures are validated through STIG's. None of the aforementioned "work arounds" are acceptable in enterprise environments with audit requirements.

```
Elasticsearch for 8.x                                                                                                                                                              7.6 kB/s | 1.8 kB     00:00    
Importing GPG key 0xD88E42B4:
 Userid     : "Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>"
 Fingerprint: 4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4
 From       : https://lxpvsat0102.idm.aires.com/katello/api/v2/repositories/25/gpg_key_content
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: auditbeat-8.6.1-1.x86_64
 GPG Keys are configured as: https://obfuscated.com/katello/api/v2/repositories/25/gpg_key_content
Public key for filebeat-8.6.1-x86_64.rpm is not installed. Failing package is: filebeat-8.6.1-1.x86_64
 GPG Keys are configured as: https://obfuscated.com/katello/api/v2/repositories/25/gpg_key_content
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
```

**Comment by Cora-young** [comment]
_We intend on generating a new signing key for these artifacts that will be used for future versions of Elastic stack releases._

@mark-vieira we've got some other customers asking for the same update on the signing key.  Any idea of when this may occur?

**Comment by mark-vieira** [comment]
I don't have an estimate on which release this will be targeted for at this time.

**Comment by HOSTED-POWER** [comment]
Still present, also running into it

**Comment by makhomed** [comment]
Same problem on Rocky Linux 9.1
```
# rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://artifacts.elastic.co/GPG-KEY-elasticsearch: key 1 import failed.
```
Is it possible to fix this problem by using SHA-256 hash algorithm for the GPG-KEY-elasticsearch ?

**Comment by whataboutpereira** [comment]
> Like @Sxderp wrote: make separete distro for EL9 family with separate gpg key.
> 
> Those on EL7/8 will use old SHA1 one, EL9 users will get new one.
> 
> Everything works for everyone.

Sounds like the way to go, since the repo is defunct for EL9 by default anyway.

**Comment by c9hariom** [comment]
works really well just fix this rpm import failed issue 
[https://c9ai.org/gpg-key-import-issue-with-update-crypto-policies/](https://c9ai.org/gpg-key-import-issue-with-update-crypto-policies/)

**Comment by SturkenSnure** [comment]
But that just disables the security. Not a fix.

**Comment by bgp-sz** [comment]
I'm surprised. This issue is over a year old and you haven't done anything? Did you forget about it? Is security such an afterthought for this project?

**Comment by afeefghannam89** [comment]
Hi @mark-vieira @breskeby  @elastic-internal-integrations 
The elastic RPMs could be hacked by attackers because of using SHA-1. I think it is an important security matter. Is there any update to this issue?

**Comment by markwalkom** [comment]
FWIW I've chased this up internally and will see if I can get a response.

**Comment by b-a-h-a** [comment]
Elasticseach installation still fails on RHEL9 in July :(!

**Comment by tuxmaster5000** [comment]
The fix is simple, create an GPG key without SHA1. So why will be the  issue so long open?

**Comment by Nirjonadda** [comment]
Do you have any plan add support for AlmaLinux OS 9? Can not install Elasticsearch in AlmaLinux OS 9 because RPM signing key is invalid.

**Comment by ingenium21** [comment]
Once they fix the issue with RPM, it should work with all distros that use
RPM

**Comment by keys1234249** [comment]
Bump it would be great to not have to use workarounds to install this key in EL9 systems.

**Comment by ronald-den-otter** [comment]
SHA1 is not advisable since 2014 something. Why didn't  elasticsearch wakeup. Packages need to be resigned. Switching to legacy is the wrong way in my opinion

**Comment by Nirjonadda** [comment]
This issue created in Apr 13, 2022 but still no fix happened after more 1 years now.

**Comment by chrisberkhout** [comment]
@elastic/release-eng Here's a way to fix the SHA1 signatures without migrating to a new key:
https://github.com/chrisberkhout/sha1-key-fix/blob/master/SHA1KeyFix.ipynb

**Comment by alsayasneh** [comment]
Thanks, @ronald-den-otter & @chrisberkhout for your proposed solutions.
The Release Engineering team has been looking at different options regarding rotating the GPG key. Here is a closed ticket for [testing on RPM](https://elasticco.atlassian.net/browse/REL-142). 
I would like to highlight a few points:

- Generating a new GPG will solve the two issues (SHA1 on RHEL9 and LastPass breach) 
- We would like to have a solution where we have the ability to rotate keys when required for security reasons

This discussion had happened at the Leadership team and today the Release Engineering team with the Infosec are working on that.

cc @elastic/release-eng @jkakavas @levinebw

**Comment by BorysVrublevskyi** [comment]
This works for me:
```bash
wget https://artifacts.elastic.co/GPG-KEY-elasticsearch -O /tmp/elasticsearch-key
gpg --import-options import-show --import /tmp/elasticsearch-key
```

**Comment by tr0k** [comment]
Hello, is there any plan to fix this issue? We need a manual workaround when installing the RPMs in our RHEL9 hosts. That would be very much appreciated.

**Comment by alpar-t** [comment]
We're working on a solution and hope to have something soon.

**Comment by Mose-** [comment]
@alpar-t ,

As @ronald-den-otter pointed out, via this [article](https://access.redhat.com/solutions/185173) (Which is dated over 3 years ago...) just resign the packages.

Rotating GPG keys/resigning packages does not require a new product release, you just have to generate a new gpg private key using modern algorithms, resign the packages and publish the public key. 

From your side all you have to do is:

```shell
gpg --gen-key
gpg -a --export KEYID > RPM-GPG-KEY-ELASTICSEARCH
for i in `ls *.rpm`;do rpm --resign $i;done
cp  RPM-GPG-KEY-ELASTICSEARCH /var/www/html/   # Or wherever your document root is for https://artifacts.elastic.co/
``` 

Update your documentation to include the new URL to the new key along with the following command:
The only steps consumers should have to do after you resign is:

```shell
rpm -e gpg-pubkey-d88e42b4-52371eca
``` 

The above could actually be part of the a minor rpm release to install the new and remove the old for an unattended/automatic update.

GPG key rotation does not require a new release of your software, package distributors rotate GPG keys all of the time, [nVidia](https://docs.nvidia.com/dgx/dgx-rhel8-sw-release-notes/rotate-gpg-key-rhel8.html) regular resigns for security purposes. Making this fix contingent on your next software release is a self imposed restriction for a problem that RedHat provided guidance for 3 years ago and this github issue has been open since April of 2002...

Can we please get these packages updated soon?

**Comment by mcarifio** [comment]
Problem appears in Rocky Linux 9.2 with elasticsearch-8.10.1. https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9 and the comments above provide more context.

**Comment by alpar-t** [comment]
We just updated https://artifacts.elastic.co/GPG-KEY-elasticsearch to have a signature that works on RHEL 9 and similar. Note that this only changes the algorithms that were problematic and is not a key rotation.  Thanks to @chrisberkhout for the suggestion.

**Comment by luischre** [comment]
I am still encountering the very same issue on RHEL 9.1:
`
sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://packages.elastic.co/GPG-KEY-elasticsearch: key 1 import failed.
`

Anything I am missing? Based on https://github.com/elastic/elasticsearch/issues/85876#issuecomment-1733018142 I assumed that this should work now?

Any help greatly appreciated :)
