### ISSUE TITLE
Make the memory stats use Lucene's Accountable APIs

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#8589]
In addition to reporting the memory usage of a given object, the Accountable API also allows to return sub-information about where this memory usage comes from.

We should move memory usage reporting to this API in order to have more fine-grained understanding of where the memory goes. For instance, this could allow the parent/child field data memory report to break down memory usage by type, etc.

**Comment by clintongormley** [comment]
@jpountz is this still something we should pursue?

**Comment by jpountz** [comment]
I don't think this is relevant anymore now that the things that use memory (fielddata, query cache) are in Lucene and implement Accountable. The only thing which is left in Elasticsearch is the request cache, but we don't even report memory usage as it's meant to be tiny (1% memory usage by default).
