### ISSUE TITLE
Cannot order by non-grouped column[column name]

### ISSUE THREAD

**Issue by abubogale342** [elastic/elasticsearch#85894]
I have almost similar issue. count is working fine for me. But I got one problem. My query is like below:

select * from (select street, count(street) as counts, min(grocery) as grocery, min(school) as school, (min(grocery) + min(school)) as score from geo_address group by 1) t order by grocery

I have geo_address index and I am creating column on the fly which is score that is sum of grocery column and school column.
Ther result :
![image](https://user-images.githubusercontent.com/24964470/163251039-53cebbc3-9b5a-4870-8242-8b9e126abe5e.png)
Now it is sorted based on the grocery but I want to sort based on score. when I try to sort by it I get an error : - Cannot order by non-grouped column [score]. can anyone please give me any workaround to solve this problem?

_Originally posted by @abubogale342 in https://github.com/elastic/elasticsearch/issues/32870#issuecomment-1098383096_

**Comment by bpintea** [comment]
This is a [documented limitation](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-limitations.html#_sorting_by_aggregation): `the aggregation(s) used in the ORDER BY must be only plain aggregate functions. No scalar functions or operators can be used, and therefore no complex columns that combine two ore more aggregate functions can be used for ordering.`.

I'll close this issue now, feel free to open a new one on encountered defects or use [the dedicated forum](https://discuss.elastic.co/).
