### ISSUE TITLE
TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated fails with ClassCastException

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#85902]
### CI Link

https://gradle-enterprise.elastic.co/s/72jn3jmotbelc/console-log?task=:x-pack:plugin:security:test

### Repro line

./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated" -Dtests.seed=4C8C62EC8BC30D4A -Dtests.locale=sr-Latn -Dtests.timezone=America/Fortaleza -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

```
org.elasticsearch.xpack.security.authc.TokenServiceTests > testInvalidateRefreshTokenThatIsAlreadyInvalidated FAILED
  java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.elasticsearch.common.bytes.BytesReference (java.util.HashMap is in module java.base of loader 'bootstrap'; org.elasticsearch.common.bytes.BytesReference is in unnamed module of loader 'app') |  
  | at __randomizedtesting.SeedInfo.seed([4C8C62EC8BC30D4A:CD4EFA933E0F14A5]:0) |  
  | at org.elasticsearch.xpack.core.security.authc.Authentication.maybeRewriteMetadataForApiKeyRoleDescriptors(Authentication.java:706) |  
  | at org.elasticsearch.xpack.core.security.authc.Authentication.maybeRewriteForOlderVersion(Authentication.java:165) |  
  | at org.elasticsearch.xpack.security.authc.TokenService.createOAuth2Tokens(TokenService.java:372) |  
  | at org.elasticsearch.xpack.security.authc.TokenService.createOAuth2Tokens(TokenService.java:319) |  
  | at org.elasticsearch.xpack.security.authc.TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated(TokenServiceTests.java:605)
```

**Comment by dakrone** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/htc35azqstb7w

**Comment by dimitris-athanasiou** [comment]
And another: https://gradle-enterprise.elastic.co/s/naxqf73jl6cp6

Preparing mute.

Also, cc @albertzaharovits as it seems relevant to recent work.

**Comment by ywangd** [comment]
@tvernum Do you mind me taking this? This is caused by my latest refactor (https://github.com/elastic/elasticsearch/pull/85590) for randomizing Authentication object for tests. Apparently, there are discrepencies like this one.

**Comment by ywangd** [comment]
PR is #85978
