### ISSUE TITLE
When we do update by query and get response. There immediately when we do search, the update is not reflecting. It is taking 1 or 2 seconds delay to reflect. I have also used refresh= true and wait for completion =true. But still facing same issue.

### ISSUE THREAD

**Issue by kranthi419** [elastic/elasticsearch#85925]
### Elasticsearch Version

8.1

### Java Version

1.8.0_212

### OS Version

LInux

### Problem Description

When we do update by query and  get response. There immediately when we do search, the update is not reflecting. It is taking 1 or 2 seconds delay to reflect. I have also used refresh= true and wait for completion =true. But still facing same issue.

### Steps to Reproduce

When we do update by query and  get response. There immediately when we do search, the update is not reflecting. It is taking 1 or 2 seconds delay to reflect. I have also used refresh= true and wait for completion =true. But still facing same issue.

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
