### ISSUE TITLE
Keyword tokenizer + keep_types filter causing empty string to be returned as only token

### ISSUE THREAD

**Issue by veqryn** [elastic/elasticsearch#85946]
### Elasticsearch Version

8.1.2

### Java Version

_bundled_

### OS Version

latest linux docker version

### Problem Description

Using a custom analyzer with the tokenizer set to "keyword", and putting a "keep_types" filter in it, result in no tokens.

This should return a single token of "1234567890", but instead it returns just an empty string: ""

If I replace the tokenizer with 'standard', I get the correct token back: "1234567890"

Changing the types to ALPHANUM and/or changing the text to include letters, words, or spaces, all still result in an empty string returned.

It is important to me to use the keyword tokenizer instead of the standard tokenizer because I want only 1 token (the entire string) being passed to all the filters.  Using the standard tokenizer would result in a string like "1234 AB 56789" being turned into 3 tokens before it gets passed to the filters, which I don't want.

### Steps to Reproduce

`POST _analyze`
```json
{
  "tokenizer": "keyword",
  "filter": [
    {
      "type": "keep_types",
      "types": [
        "<NUM>"
      ]
    }
  ],
  "text": "1234567890"
}
```

Returns an empty token instead of "1234567890"

**Comment by veqryn** [comment]
My attempt to find a workaround reveals that simple_pattern also causes the same issue:
`POST _analyze`
```json
{
  "tokenizer": {
    "type": "simple_pattern",
    "pattern": ".+"
  },
  "filter": [
    "decimal_digit",
    {
      "type": "keep_types",
      "types": [
        "<NUM>"
      ]
    }
  ],
  "text": "1234567890"
}
```

And also the character split and pattern split also fail.
Probably the issue with keep_types doing something wrong and keeping nothing.

**Comment by romseygeek** [comment]
Neither KeywordTokenizer nor PatternTokenizer set the type attribute, so a type filter won't work here indeed.  You could instead use a `predicate_token_filter` with a regex to check that the input token contains only numbers.

**Comment by veqryn** [comment]
Ok, so you are saying that this is working as intended?
Maybe "keep_types" needs better documentation then, as my understanding of it was that the 'type' of any particular byte was inherent to the byte itself and didn't need anything else done first.

As far as a workaround goes, I am currently using this filter instead:
```json
        "only_numbers": {
          "pattern": "[^0-9]",
          "type": "pattern_replace",
          "replacement": ""
        }
```

**Comment by amitmbm** [comment]
I agree, that we should support `keep_types` as it doesn't give any error while defining in the analyzer definition or improve the documentation. I would be happy to work on it based on the feedback :)

**Comment by amitmbm** [comment]
@romseygeek @javanna let me know if there is consensus on what needs to be done here, would be happy to work on the fix.

**Comment by javanna** [comment]
sorry about the way @amitmbm . @romseygeek would it make sense for KeywordTokenizer & co. to also set the type attribute, in which case this would be merely a lucene issue, or should we just update the docs with a list of tokenizers that don't support keep_types ?

**Comment by romseygeek** [comment]
I think updating the documentation is the best way to go here.  KeywordTokenizer in particular is a very lightweight implementation and I think there would be pushback if we tried to add type identification into it.

We could also look at building a new TypeIdentifierTokenFilter in lucene that could be added into an analysis chain to inject type information for tokenizers that don't generate it themselves.

**Comment by amitmbm** [comment]
I agree with @romseygeek that updating the documentation is the best thing otherwise there will be a pushback for increasing complexity of KeywordTokenizer. 
@javanna I would take this the task to update the document.

**Comment by amitmbm** [comment]
@javanna  @romseygeek can you please assign this issue to me?

**Comment by amitmbm** [comment]
@javanna @romseygeek Thanks for the inputs and bringing back attention to this long pending issue, As mentioned I would like to work on it, but I think we need to decide where to update the documentation, ie in the specifics `tokenizers` which  don't support `type` token filter, or add the list of these `tokenizers` in the [keep types token filter document](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-types-tokenfilter.html).

P.S :- would be great if this issue can be assigned to me.

**Comment by javanna** [comment]
@amitmbm we don't have a way to formally assign the issue to you as you are not a member of the Elastic github org, but it is clear that you took it and are going to work on it based on previous comments. I would update the keep types token filter docs page adding a note that some tokenizers are not supported, with a list of the ones that we know are not.

**Comment by amitmbm** [comment]
@javanna perfect, expect a PR coming on your way soon 😄
