### ISSUE TITLE
flag to disable forward on individual yaml tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#85955]
### Description

Right now we disable forwards compatibility testing with something like:
```
task.skipTest("search.aggregation/20_terms/string profiler via global ordinals filters implementation", "The profiler results aren't backwards compatible.")
task.skipTest("search.aggregation/20_terms/string profiler via global ordinals native implementation", "The profiler results aren't backwards compatible.")
```
This *works* but it's kind of inconvenient both for writing the tests and for reading them. It'd be nice if we had a flag we could put on the tests in the yaml file that'd disable them in the forwards compatibility testing. Mostly for things like profiler output - useful to have tests for but that aren't controlled by semver.

**Comment by mark-vieira** [comment]
The confusing thing about this is these tests actually live in 7.17 so we'd have to annotate them _there_. The benefit of configuring this at the task level is at least this all lives in the branch which you are actually testing, and you don't have to go look in a different branch to see if/why something is being ignored. There's also the question of associating these things with versions. The way it is now the skips and transforms are forward-compatibile version specific, but if this stuff lives in the 7.17 it would apply _everywhere_ which may not the the correct thing to do.

The compatibility tests are... awkward, but I'm not sure moving config into the tests (in the 7.17 branch) would necessarily alleviate any issues and may cause more. I'd be curious what specific workflow this would improve. At this point, the existing 7.17 test suites shouldn't be changing much, so we shouldn't really need to be adjusting these exclusions unless we actually break forward compatibility in a later dev branch, in which case it certainly makes sense that we should make the exclusions there.

**Comment by nik9000** [comment]
> he confusing thing about this is these tests actually live in 7.17 so we'd have to annotate them _there_.

Ooof. Yeah. That's rough. I suppose the reason this comes up for me is that there are some tests that I know really shouldn't be forwards tested when I write them and I don't have a good way to mark them. I suppose I could add them to the filter in build when I write them. But then renames lose it. But, I guess, that's not the end of the world.

**Comment by mark-vieira** [comment]
> I suppose the reason this comes up for me is that there are some tests that I know really shouldn't be forwards tested when I write them and I don't have a good way to mark them.

Yeah, this is awkward and I'm not sure there's a perfect solution here. As I understand it though, new tests being added to 7.17 should be pretty minimal as backports to that branch are kept to critical bug fixes.

**Comment by nik9000** [comment]
A bunch of us talked about this and decided that it isn't worth adding a flag to the 7.14 tests to do this. A flag would indeed be lovely, but having two ways to do mark these tests as skipped is even more confusing then the one way we have. And we would need two ways - there are totally tests skipped in master for reasons other than semver. But there are two important things to do!

- [ ] [Merge the dev guide](https://github.com/elastic/elasticsearch/pull/71879). It should include this consideration. As well as how to find the test configuration and the transform.
- [ ] Enhance error message to include reference to the dev guide.

**Comment by pgomulka** [comment]
Both items were merged, I will close an issue.
