### ISSUE TITLE
Prefix expansions should be based on term frequency

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#8596]
It appears (and I read somewhere) that prefix expansions (for multi-match phrase prefix queries for instance) are sorted alphabetically. This means that the max_expansions limits limit can get hit quickly for short text.

An example I was looking at was searching for "related pos". Should match a bunch of docs I have mentioning "related posts", but matches nothing unless I set max expansions to 5000. My filters are limiting us to a search of about 3000 docs in an index of many millions of docs, so there are a lot of words starting with "pos" that are going to get in the way of the prefix query.

I think a better sorting of which terms to expand on would be to start with the terms with the lowest document frequency since they will be the most discerning of importance. I think this should be a doable change. Any pointers on if there is a reader to get the terms with frequencies?

Even better would be to limit which terms are chosen based on the filters being applied. I'm not sure that's possible though given the query execution order.

**Comment by rmuir** [comment]
> The top_terms_N rewrite method doesn't seem to work in the way described, ie collecting the top N scoring terms from all matching prefixes. Instead, it seems to examine only the first N terms (alphabetically):

It works correctly, but a wildcard query "scores" all terms the same. Because of that, this top-N sorting tie-breaks on term order. Things are different when the query actually assigns a score to terms (such as fuzzy query).

**Comment by clintongormley** [comment]
Given that this change could potentially make wildcards significantly heavier than they already are today, I'm going to close this one.
