### ISSUE TITLE
[DOCS] Node Stats - io_stats.total nesting

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#85974]
👋🏼 howdy! AFAICT [Node Stats API](https://github.com/elastic/elasticsearch/blame/master/docs/reference/cluster/nodes-stats.asciidoc#L1832) sub-object `nodes.fs.io_stats` has children [`devices`, `total`] but the Docs don't show the `total` sub-objects wrapped in it. I can see the doc code [ballpark's here](https://github.com/elastic/elasticsearch/blame/master/docs/reference/cluster/nodes-stats.asciidoc#L1832) but am not familiar enough with Asciidocs to edit (sorry & thanks for your help!).

Example from v8.1

```diff
{"nodes": { "XXXXX": { "fs": { "io_stats": {
    "devices": [{
            "device_name": "dm-1",
            "io_time_in_millis": 7152,
            "operations": 20361,
            "read_kilobytes": 468,
            "read_operations": 58,
            "write_kilobytes": 284356,
            "write_operations": 20303 } ],
+    "total": {
        "io_time_in_millis": 7152,
        "operations": 20361,
        "read_kilobytes": 468,
        "read_operations": 58,
        "write_kilobytes": 284356,
        "write_operations": 20303 }
}}}}}
```

Vs doc:

![image](https://user-images.githubusercontent.com/26751266/163893019-31022603-9fe8-402e-8562-ea4556d50b10.png)

**Comment by ddolcimascolo** [comment]
Hi guys, any news on this?

Cheers,
David
