### ISSUE TITLE
async search extend API

### ISSUE THREAD

**Issue by Dosant** [elastic/elasticsearch#86012]
### Description

Currently, in Kibana we extend async searches using the keep_alive parameter of GET async_search request.

In some cases, we use this API to only extend the running search without retrieving the status or the search results.

We could optimize some scenarios if we had dedicated extension APIs (network transfer overhead + maybe something internal on ES side?) 

Could you please evaluate if this is a worthy addition or otherwise feel free to close?
Please also consider this ask while evaluating: https://github.com/elastic/elasticsearch/issues/86011

**Comment by mayya-sharipova** [comment]
@Dosant Can you please clarify how this issue is different from https://github.com/elastic/elasticsearch/issues/86011? If they are the same, can I close this issue?

**Comment by Dosant** [comment]
> @Dosant Can you please clarify how this issue is different from #86011? If they are the same, can I close this issue?

In this issue I am suggesting to implement an API that allows to extend keep_alive without retrieving the search results 

And in https://github.com/elastic/elasticsearch/issues/86011 we would like to have a way to extend `keep_alive` in a `async_search/<id>` without a risk of hitting a race condition where we could accidentally decrease previously extended keep_alive (basically a new param, convention or a flag, that allows to only increase keep_alive, but not decrease)

**Comment by mayya-sharipova** [comment]
@Dosant Thanks for explaining, so https://github.com/elastic/elasticsearch/issues/86011 is about using the existing GET `async_search/<id>` API with an extra parameter.

**Comment by mayya-sharipova** [comment]
@Dosant Sorry, one more clarification. Why is it important to keep search results in index alive, if they are already retrieved and rendered on screen by Kibana?

**Comment by Dosant** [comment]
@mayya-sharipova, Kibana allows to ["save a search session"](https://www.elastic.co/guide/en/kibana/current/search-sessions.html) even after search complete and results are rendered. After users saves a session they can get back to the results later without re-running the search. 

We are working on the internal implementation improvements and simplification [(rfc with the details)](https://docs.google.com/document/d/1xpvW0xHmdm6w6EyYzYd01JLhiPFWF1Ij-tcJxCRLO7U/edit#)
In the new implementation we want to start all the searches with a short keep_alive and only extend it when user actually saves the session _(in the current implementation we start all searches with long keep alive and then background task in Kibana cleans up no longer needed searches)_. 

But when searches complete and user doesn't leave the search results, they need to be able to save the session. For this we need to periodically extend keep-alive - until either a user leaves or starts a new search, or until they save a session and we extend keepAlive the search one last time, but for a longer value

Current we are extending keepAlive with `async_search/<id>`, but seems like we could improve it with designated API call

**Comment by javanna** [comment]
I am closing this as we have on concrete plans to work on this issue. Please reach out if there are pressing asks that you need help with around async search.
