### ISSUE TITLE
Low level rest client retrying scrolls, skipping pages

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#86041]
### Elasticsearch Version

Doesn't matter

### Java Version

all

### OS Version

doesn't matter

### Problem Description

When you send a `scroll` request to the low level rest client it uses it's standard retry mechanism which catches all errors and just retries against another ES instance. The trouble with that is that you *can't* retry a scroll - it generally consumes state on the server and moves to the next page.

### Steps to Reproduce

Scroll with low level rest client.

**Comment by nik9000** [comment]
Ideas for remediation:
1. Document that you should turn off retry for scroll. Document how to do it.
2. Detect scroll and automatically disable retry.
3. Never retry a `ContentTooLargeException`

This could also be a problem with reindex. I'm not sure. It uses the low level REST client directly.

Certainly the high level rest client shouldn't retry scrolls.

**Comment by swallez** [comment]
I looked at the issue. It was found in version 6 and still exists in 7 and 8.

> Document that you should turn off retry for scroll. Document how to do it.
  Detect scroll and automatically disable retry.
  Never retry a `ContentTooLargeException`

The reliable way to address this is to not retry on `ContentTooLargeException`. This exception is thrown client-side when the ES server has sent a response that is too large (100 MB by default).

Disabling retries alltogether for scroll will also miss some errors were retrying would be ok, such as when the client wasn't able to send the request. Retries should however not happen once the request has been sent: if there's e.g. a connection loss, a read timeout or even a 5xx response. In those cases we don't know if ES has received and (even partially) processed the request and modified its internal state.

Now this not only applies to scroll, but also to any non idempotent request sent to Elasticsearch. Unfortunately it's hard to determine idempotency by looking at the HTTP request without deeper knowledge of API specifics: for example the `/search/_scroll` endpoint accepts the `GET` method that we could assume to be idempotent but isn't.

**Comment by nik9000** [comment]
> @nik9000 I added you as a reviewer since you have some context on this issue.

:+1:

Looks good to me. A shame about the wrapping, but such is life.

**Comment by loupipalien** [comment]
> This could also be a problem with reindex. I'm not sure. It uses the low level REST client directly.
I don't think it be a problem with reindxlocal reindex doesn't use REST client，remote reindex not retry
