### ISSUE TITLE
Security enabled BWC tests fail in FIPS mode for v7.x

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#86144]
### Problem Description

When xpack security and FIPS mode is enabled for a BWC test, the test requires that a FIPS-compliant password hashing algorithm is set via the `xpack.security.authc.password_hashing.algorithm` setting. Without a compliant algorithm, the cluster fails to start and the test fails. This happens automatically via a default setting value for v8.x clusters but does **not** happen for v7.x clusters. 

As such, v7.x BWC tests that have security enabled fail when run in FIPS mode.

The original test failure where this surfaced was `VerifyVersionConstantsIT` (see #85640) for which we put in a temporary fix to remove the test triage noise (#86079).

There are several BWC tests left that will still fail however and we should put a general fix in place. Based on an internal discussion with @es-security, we decided not to backport a default settings change to v7.x clusters. We therefore need to fix this issue within our test setup.

### Steps to Reproduce

`./gradlew -Dtests.fips.enabled=true :x-pack:plugin:shutdown:qa:rolling-upgrade:v7.17.4#oldClusterTest --tests org.elasticsearch.upgrades.NodeShutdownUpgradeIT.testShutdown`

will fail with

```
Exec output and error:
| Output for ./bin/elasticsearch-users:
| ERROR: Only PBKDF2 is allowed for password hashing in a FIPS 140 JVM. Please set the appropriate value for [ xpack.security.authc.password_hashing.algorithm ] setting.
```

**Comment by n1v0lg** [comment]
I see two places we could fix this:

1. Individually, for each bwc test that meets the criteria (i.e., same approach as #86079) or
2. Inside `elasticsearch.fips.gradle` (https://github.com/elastic/elasticsearch/blob/master/build-tools-internal/src/main/groovy/elasticsearch.fips.gradle#L66)

The issue with option 1 is that there are 5 tests currently affected and we might add more in the future which would in turn start failing mysteriously.

Option 2 would apply to all tests, which is nice but feels too broad. In particular, we couldn't even limit this to only apply to v7 clusters because `elasticsearch.fips.gradle` is applied _before_ a bwc test cluster is configured.

**Comment by ywangd** [comment]
The simplest fix is probably forward port https://github.com/elastic/elasticsearch/pull/66841 to `master`, i.e. your option 2. It's more future proof. Explicit configuration is generally required for FIPS mode. So I think explicitly configure the hashing algorithm is reasonable. Also I believe we have other tests for testing default hashing algorithm when FIPS is enabled.

**Comment by n1v0lg** [comment]
@ywangd thanks for the pointer, I totally missed this
