### ISSUE TITLE
 Memory leak related issue with Threadlocals in elasticsearch

### ISSUE THREAD

**Issue by prachicsa** [elastic/elasticsearch#8617]
have a web service, where every time a button is pressed from UI, it connects to elastic search and fires a query. This is the code which is executed every time. The issue is that after a while, intermittently, the UI hangs.

private static final String CONFIG_CLUSTER_NAME = "cluster.name";

private static final String CLUSTER_NAME = "sample_es";
private static final String[] transportAddress = {
    //Machine details
};

private static final int transportPort = 9300;

        public static Client initClient(){
        settings = ImmutableSettings.settingsBuilder().put(CONFIG_CLUSTER_NAME, CLUSTER_NAME).build();

        Client client = new TransportClient(settings);
        for (int i=0 ; i < transportAddress.length-1 ; i++){
            ((TransportClient)client).addTransportAddress(new InetSocketTransportAddress(transportAddress[i], transportPort));
        }
        logger.info("TransportClient Created"); 
        return client;  
}

public static int query( String query) throws Exception
{
    Client client = null;
    try{

            client = initClient();

            //Query search code

    }catch(Exception e){
            e.printStackTrace();
    }finally{
        if(client != null){
            client.close();
            logger.info("TransportClient Closed");
        }
    }
        return result_count;
}

Whenever we restart the tomcat server, this is the error message we are seeing in logs. How should we fix this?

[org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom$1] (value
[org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom$1@5838ce3e]) and a value of type
[org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom] (value 
[org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom@796c75b1]) but failed to remove it
when the web application was stopped. This is very likely to create a memory leak.

**Comment by clintongormley** [comment]
Closing in favour of #283
