### ISSUE TITLE
Documentation uses wrong path for http_ca.crt

### ISSUE THREAD

**Issue by CreaterNo1** [elastic/elasticsearch#86219]
### Elasticsearch Version

8.1.3

### Java Version

_bundled_

### OS Version

Almalinux 4.18.0-348.el8.x86_64 #1 SMP Tue Nov 9 06:28:28 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

"curl --cacert /etc/elasticsearch/config/certs/http_ca.crt -u elastic https://localhost:9200" is uses a wrong path in the https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html#rpm-check-running
document
There is no config folder in the /etc/elasticsearch/ folder. The certs folder is there directly not in subfolder

### Steps to Reproduce

Try a new installation with the instructions on https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html

**Comment by tvernum** [comment]
Fixed in #84856
