### ISSUE TITLE
Enable aggregations for scripts that depend on nested and parent

### ISSUE THREAD

**Issue by bakura10** [elastic/elasticsearch#8623]
Hi,

I came across an interesting use case that does not seem to work currently. I have the following (simplified) schema:

```json
{
		"properties": {
			"rates": {
				"type": "object"
			},
			
			"details": {
				"type": "nested",
				"properties": {
					"amount": {
						"type": "integer"
					},
                                        "type": {
                                               "type": "string"
                                       }
				}
			}
		}
	}
```

rates is an object that contains various exchange rates for different currencies. The details property is nested because I need to do sums on the amount and filter by type.

What I want is, for each amount in the nested property, being able to write a script (in Groovy, Expression...) where the amount is multiplied by a rate:

```json
{
            "aggs": {
                "details": {
                    "nested": {
                        "path": "details"
                    },
        
                    "aggs": {
                        "filter": {
                            "term": {"type": "a"}
                        },
               
                        "aggs": {
                            "sum_amount": {
                                "sum": {
                                    "script": "doc['details.amount'].value * doc['rates.usd'].value
                                }
                            }
                        }
                    }
                }
            }    
        }
```

This does not work however, because I cannot fetch the rates property (and returns 0). If I do a reverse nested, then I can (logically) access again the rates, the I loose access to the amount.

Thanks

**Comment by clintongormley** [comment]
No further ideas during the last year. Closing
