### ISSUE TITLE
Upgrade from Elasticsearch 5.2.1 to 6.8.22 encounter issue: Exception in thread "Thread-126" java.lang.LinkageError: Failed to link org/elasticsearch/transport/netty4/ESLoggingHandler

### ISSUE THREAD

**Issue by maxwellproject** [elastic/elasticsearch#86287]
### Elasticsearch Version

6.8.22

### Installed Plugins

transport-netty4-client;reindex-client;percolator-client;lang-mustache-client;parent-join-client

### Java Version

jdk1.8.0_311

### OS Version

Windows 10 Pro 20H2

### Problem Description

Our project need to upgrade elasticsearch from 5.2.1 to 6.8.22. 
We encounter an issue now. The war can be deployed successfully in jboss server, but will continue to show the error message attached again and again. I have no idea about it. Is there any one can help me? Many thanks!!!

Using versions:

spring.version: 3.2.4.RELEASE
jboss version: 6.4.0 GA
elasticsearch version: 6.8.22

<dependency>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>transport-netty4-client</artifactId>
    <version>6.8.22</version>
</dependency>

### Steps to Reproduce

NA

### Logs (if relevant)

Exception in thread "Thread-126" java.lang.LinkageError: Failed to link org/elasticsearch/transport/netty4/ESLoggingHandler (Module XXX from Service Module Loader)

16:51:50,642 ERROR [stderr] (Thread-126) 	at org.elasticsearch.transport.netty4.Netty4Transport$ClientChannelInitializer.initChannel(Netty4Transport.java:270)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)

16:51:50,642 ERROR [stderr] (Thread-126) 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

16:51:50,642 ERROR [stderr] (Thread-126) 	at java.lang.Thread.run(Thread.java:748)

**Comment by pgomulka** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
