### ISSUE TITLE
OIDC back-channel http client threads hang Window service exit

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#86286]
### Elasticsearch Version

7.17.* 8.*

### Java Version

_bundled_

### OS Version

Windows

### Problem Description

When Elasticsearch runs as a Windows Service, the stop service action hangs indefinitely, when an OIDC realm is configured (doesn't have to be used).

-------------

Elasticsearch tries to gracefully terminate all the threads when the JVM is terminated.
That is true on all platforms supported by ES (though this is not a JVM requirement in general).

For a Windows Service deployment, given our configuration of procrun (the code that installs the ES JVM as a Windows Service) the JVM is terminated in a different way (not via `System.exit`).
The Windows Service stop procedure must necessarily terminate all the non-daemon threads, at which point the JVM will then terminate naturally. Any bug in omitting to terminate non-daemon threads is a serious problem for Windows Service deployments (for other deployment types it is a minor nuisance).

Unfortunately, the `OpenIdConnectRealm` (more specifically the `OpenIdConnectAuthenticator`) creates threads for its http client used for backchannel comms, which it does not close because the `Realm#close` method is never invoked.

### Steps to Reproduce

Configure any OIDC realm and install Elasticsearch as a Service on Windows.
The stop service action will hang indefinitely.

**Comment by ywangd** [comment]
Great find! [JwtRealm](https://github.com/elastic/elasticsearch/blob/bc5cfcf4b2f23801678d9b5bab59a2d5c185d517/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java#L283-L298) might have the same issue since it can also use a HTTP client.

**Comment by adiakbar4** [comment]
Hello @elastic/es-security @albertzaharovits 
Just wanted to check if there's an expectation that can be shared with the customer for the fix?
