### ISSUE TITLE
Add optional result caching for runtime mapping field.

### ISSUE THREAD

**Issue by MOstadi** [elastic/elasticsearch#86318]
### Description

In some cases when the runtime field value is needed for filtering document , adding a result cache for runtime fields can reduce repeated calculations and improve search speeds. This can be an illustration of cache interface:
`
"runtime_mappings": 
{

    "total_price_for_selected_range":{
      "type": "double",
      "script": {
        "lang": "painless",
        "source": " ... some calculations   ",
        "params": {
          "from": "2022-04-01",
          "to": "2022-04-10"
        },
         "cache":{
               "key": "params.from + param.to + doc['id'].value",
               "expire_in": 86400   
         }
      }
    }
  },
`
cache key is an expression with access to script params and document fields.
and expire_in is optional and defaults to unlimited. 
another option could be result_cache_size_limit configuration for removing old entries on exceeding size limitation.

**Comment by javanna** [comment]
Thanks for opening this issue. To give you some context, runtime fields performance has come up quite a few times while developing them, and we had to force ourselves to embrace the fact that runtime fields may be slow, depending on what their script does. We have today the async search API to execute long-running searches and making runtime fields faster has not been our focus so far.

We may want to get back to this at some point in the future, mostly in the context of making composite runtime fields faster, as grok is a very expensive operation, like it's been tried in #81124, but I don't foresee us adding a new caching layer to speed runtime fields queries up. There are quite some aspects that could be optimized when it comes to runtime fields execution (for instance every time the same runtime field is mentioned in the search request, the script is being executed again, against the same document) without introducing the complexity of a caching layer.
