### ISSUE TITLE
Add notes about scripting and bulk api

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#8632]
I think it would be good to encourage use of scripts that take parameters versus unique script for each document, so that the script cache is effective. Its currently not very intuitive to the user that this can have a big impact on indexing performance.

**Comment by clintongormley** [comment]
Script compilation stats were added in https://github.com/elastic/elasticsearch/pull/12733

Docs could still be improved.

**Comment by clintongormley** [comment]
The docs were improved in https://github.com/elastic/elasticsearch/pull/18132
