### ISSUE TITLE
[Docs] "Add and remove nodes" docs should link to security "Enroll additional nodes" docs

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#86334]
### Description

In the **Set up Elasticsearch** section of the docs, there is a page for [Add and remove nodes in your cluster](https://www.elastic.co/guide/en/elasticsearch/reference/current/add-elasticsearch-nodes.html).

It has these instructions:
> 1. Set up a new Elasticsearch instance.
> 2. Specify the name of the cluster with the cluster.name setting in elasticsearch.yml. For example, to add a node to the logging-prod cluster, add the line cluster.name: "logging-prod" to elasticsearch.yml.
> 3. Start Elasticsearch. The node automatically discovers and joins the specified cluster.

However, if security (including TLS between nodes) is enabled (which it is by default) those instructions will not work, because each node will generate its own set of certificates.

Those steps should include some sort of link to the relevant security docs to [Enroll additional nodes in your cluster](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-stack-security.html#stack-enroll-nodes)

**Comment by DaveCTurner** [comment]
I think the security team is better placed to address this than the distrib team so I'm removing labels to clarify ownership.
