### ISSUE TITLE
Ensure the service is started after network is up

### ISSUE THREAD

**Issue by bennysan** [elastic/elasticsearch#8636]
I encountered an issue with the systemd process ordering. The network target starts after ES then it crashes at boot time because the interface wasn't up.

In the rpm package, the systemd service doesn't ensure that the network is up before starting ES.

I suggest to add an After param : 

[Unit]
Description=Starts and stops a single elasticsearch instance on this system
<b>After=network.target</b>
Documentation=http://www.elasticsearch.org
[...]

**Comment by tlrx** [comment]
Thanks for reporting and your contribution.

I agree with @t-lo it should be `network-online.target` and it how it is configured now (see https://github.com/elastic/elasticsearch/blob/master/core/src/packaging/common/systemd/elasticsearch.service). It has been tested on various distributions including Fedora21, OpenSUSE13, Ubuntu15.04, Debian8, CentOS7.

Closing this one, feel free to reopen if needed.
