### ISSUE TITLE
[CI] CustomAuthorizationEngineTests.java:56: error: no suitable constructor found for Authentication(User,RealmRef,RealmRef)

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#86378]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+example-plugins/930/console

### Repro line

cd plugin/examples; ./gradlew build --include-build ../..

### Does it reproduce?

Yes

### Applicable branches

master

### Failure excerpt

The example projects fails with a compile error caused by this change here: https://github.com/elastic/elasticsearch/pull/86206

This is blocking current PR checks as example pr build is failing.

the stack trace:
> Task :security-authorization-engine:compileTestJava FAILED
09:14:22 /dev/shm/elastic+elasticsearch+pull-request+example-plugins/plugins/examples/security-authorization-engine/src/test/java/org/elasticsearch/example/CustomAuthorizationEngineTests.java:56: error: no suitable constructor found for Authentication(User,RealmRef,RealmRef)
09:14:22                 new Authentication(new User("joe", new String[]{"custom_superuser"}, new User("bar", "not_superuser")),
09:14:22                 ^
09:14:22     constructor Authentication.Authentication(User,RealmRef,RealmRef,Version,AuthenticationType,Map<String,Object>) is not applicable
09:14:22       (actual and formal argument lists differ in length)
09:14:22     constructor Authentication.Authentication(StreamInput) is not applicable
09:14:22       (actual and formal argument lists differ in length)
09:14:22 /dev/shm/elastic+elasticsearch+pull-request+example-plugins/plugins/examples/security-authorization-engine/src/test/java/org/elasticsearch/example/CustomAuthorizationEngineTests.java:73: error: no suitable constructor found for Authentication(User,RealmRef,RealmRef)
09:14:22                 new Authentication(new User("joe", new String[]{"not_superuser"}, new User("bar", "custom_superuser")),
09:14:22

**Comment by ywangd** [comment]
Interesting the CI on pr didn't pick this up. Will raise a fix

**Comment by breskeby** [comment]
I'm surprised this didn't cause your PR checks to fail (example/build). The daily example build resolves its libraries for the example plugins as binaries from the maven repo. Therefore it will not fail before your changes actually make it into the snapshot repo. In general this should be fine as we have that guard in our PR checks.

**Comment by ywangd** [comment]
I raised #86385 for fix.

On the PR (#86206) that removed the constructors, was the example plugin also built against the downloaded snapshot as well as running with it? That could explain why it didn't fail on the PR. But isn't it a bit unintuitive? For errors like this one, we won't get to see it until the PR is merged. Also example projects do not show up as Java projects in my IDE. I think that's why it was left out from the usage search.

**Comment by breskeby** [comment]
For our PR example builds we run against the sources and not against the prebuilt artifacts. that's why I'm surprised this didn't materialise as an issue within your PR. I'll have another look to see if I find some root cause of this. thanks for the quick pick up

**Comment by mark-vieira** [comment]
> that's why I'm surprised this didn't materialise as an issue within your PR

We don't run that check on every PR, only those with the `Delivery/Build` label. Maybe we should, but that job also has the issue of blowing up on a missing java client whenever we bump versions and I didn't want that to be disruptive.

**Comment by breskeby** [comment]
ah okay

**Comment by breskeby** [comment]
probably it makes sense to revisit this. We hit today another of those issues: https://github.com/elastic/elasticsearch/issues/86421
