### ISSUE TITLE
Auto unlocking after recovering from flood-stage watermark (high disk usage) not working with threshold_enabled disabled

### ISSUE THREAD

**Issue by EtienneBruines** [elastic/elasticsearch#86383]
### Elasticsearch Version

Version: 8.1.3, Build: default/rpm/39afaa3c0fe7db4869a161985e240bd7182d7a07/2022-04-19T08:13:25.444693396Z, JVM: 18

### Installed Plugins

translations,licensing,globalSearch,globalSearchProviders,features,mapsEms,licenseApiGuard,usageCollection,taskManager,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,sharedUX,share,embeddable,uiActionsEnhanced,screenshotMode,screenshotting,banners,telemetry,newsfeed,fieldFormats,expressions,dataViews,charts,esUiShared,bfetch,data,savedObjects,presentationUtil,expressionShape,expressionRevealImage,expressionRepeatImage,expressionMetric,expressionImage,customIntegrations,home,searchprofiler,painlessLab,grokdebugger,management,watcher,licenseManagement,advancedSettings,spaces,security,savedObjectsTagging,reporting,lists,fileUpload,ingestPipelines,encryptedSavedObjects,dataEnhanced,cloud,snapshotRestore,eventLog,actions,alerting,triggersActionsUi,transform,stackAlerts,ruleRegistry,savedObjectsManagement,console,controls,graph,fleet,indexManagement,remoteClusters,crossClusterReplication,indexLifecycleManagement,visualizations,canvas,visTypeXy,visTypeVislib,visTypeVega,visTypeTimeseries,rollup,visTypeTimelion,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeHeatmap,visTypeMarkdown,dashboard,maps,dashboardEnhanced,expressionTagcloud,expressionPie,visTypePie,expressionMetricVis,expressionHeatmap,expressionGauge,dataViewFieldEditor,lens,cases,timelines,discover,osquery,observability,discoverEnhanced,dataVisualizer,ml,uptime,securitySolution,infra,upgradeAssistant,monitoring,logstash,enterpriseSearch,apm,dataViewManagement

### Java Version

_bundled_

### OS Version

Linux kibana.q-mex.net 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Some parts of the internet / stackoverflow / forums, advise to disable the `cluster.routing.allocation.disk.threshold_enabled` setting. This also disables the unlocking if the cluster is in a locked state, effectively creating a perma-lock (until someone changes the setting back). 

This means indices stay locked even after disk usage dropped significantly. This is especially bothersome for indices like `.security` and `.async-search` which do not allow manual intervention.

(Not that big of a deal, having figured out now what caused my lockup. I wanted to create this GH issue for sake of documentation - I'd be OK if this were closed as `wontfix`)

### Steps to Reproduce

- Have a high disk usage to cause the lockup - ideally in a single-node deployment
- Get your disk usage back to normal levels (63% in my case)
- See that nothing happens

**Comment by DaveCTurner** [comment]
AFAICT if `cluster.routing.allocation.disk.threshold_enabled` is `false` then Elasticsearch won't even apply the flood-stage index block, but it would indeed not remove any blocks that were in place when you disable disk thresholds. I guess you hit the flood stage and then disabled disk thresholds?

I think we could reasonably remove any existing `index.blocks.read_only_allow_delete` blocks when changing this setting to `false`. We could also just clarify in the docs that disabling disk thresholds also disables the release of these blocks, but that's not as helpful. Marking this for team discussion to see what others think.

**Comment by EtienneBruines** [comment]
Thank you for your quick and useful reply. 

-------

> I guess you hit the flood stage and then disabled disk thresholds?

Correct.

> I think we could reasonably remove any existing index.blocks.read_only_allow_delete blocks when changing this setting to `false`

That does sound like a good solution to the problem we had. I cannot imagine someone wanting to keep the blocks when they disable the thresholds. (Why would someone want to keep their system in a locked state?)

> Marking this for team discussion to see what others think.

:+1:

**Comment by DaveCTurner** [comment]
We (the @elastic/es-distributed team) discussed this today and agreed that removing the blocks seems like the right thing to do.

**Comment by chen-ni** [comment]
Hi, is anyone working on this? If not can I take it?

**Comment by chen-ni** [comment]
@DaveCTurner Can I take this one?

**Comment by Leaf-Lin** [comment]
Hi, @chen-ni , I have added the label by mistake, sorry for the confusion. This one has been assigned to @kingherc and @pxsalehi

**Comment by chen-ni** [comment]
@Leaf-Lin Got it :)
