### ISSUE TITLE
[DOCS] SAML role mapping of groups does not parse comma separated lists to string array

### ISSUE THREAD

**Issue by KnowMoreIT** [elastic/elasticsearch#86409]
### Description

Following the documentation for setting up SAML integration with Elastic, it mentions using a "groups" attribute so the SAML server can pass a list of groups back to ElasticSearch/Kibana: https://www.elastic.co/guide/en/elasticsearch/reference/current/saml-guide-stack.html

You will notice here that the role mapping is specifying the group name "finance-team".
```
PUT /_security/role_mapping/saml-finance
{
  "roles": [ "finance_data" ],
  "enabled": true,
  "rules": { "all": [
        { "field": { "realm.name": "saml1" } },
        { "field": { "groups": "finance-team" } }
  ] }
}
```

In my case, we were unable to get this to work because the SAML server is actually passing a string that contains a comma separated list of security groups that the user belongs to and not just one single group.

Therefore, it appears that Elastic is not converting this string to an array. I do not know if this is by design but the purpose of opening this feature request is to document that you can actually use wildcards in the role mapping:
![image](https://user-images.githubusercontent.com/5861587/166572732-c8121586-bc54-453c-8be7-6ab9148d30f4.png)

To document this better, I think these questions will need to be answered:
- Is Elastic supposed to parse the "groups" string from SAML into an array if it detects it is a comma separated string?
- Are the wildcards actually supported on the "text" type for the user field "groups". It works, but I didn't see it documented and wondering if it could stop working in the future.

This is what the SAML server is returning to Elastic/Kibana (example):
```
"rows": [
            {
                "name": "mail",
                "value": "jdoe@domain.com",
                "claimType": null,
                "attrNameFormat": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
                "responsePosition": "BODY",
                "checkRequest": false,
                "returnResponse": true,
                "getInput": false
            },
            {
                "name": "nameid",
                "value": "jdoe@domain.com",
                "claimType": null,
                "attrNameFormat": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
                "responsePosition": "BODY",
                "checkRequest": false,
                "returnResponse": true,
                "getInput": false
            },
            {
                "name": "groups",
                "value": "Organization Management,Discovery Management,Mailbox Import and Export Role,Domain Admins,Denied RODC Password Replication Group,VPN Users,Offer Remote Assistance Helpers,MSSQL - Admins,Systems Analyst",
                "claimType": null,
                "attrNameFormat": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
                "responsePosition": "BODY",
                "checkRequest": false,
                "returnResponse": true,
                "getInput": false
            }
        ],
```

**Comment by ywangd** [comment]
This is the same issue as #84379. In short, we intend to support the split but haven't prioritize it yet. In the meantime, you can use regex workaround as described in #84379.

**Comment by KnowMoreIT** [comment]
> This is the same issue as #84379. In short, we intend to support the split but haven't prioritize it yet. In the meantime, you can use regex workaround as described in #84379.

Thank you @ywangd and I apologize for missing that one. However, I think it may be worth upgrading the documentation to make this known to new customers setting this up that it doesn't split and wildcards are supported. The current documentation makes you assume it supports splitting.

**Comment by ywangd** [comment]
@KnowMoreIT The documentation does have [examples](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role-mapping.html#security-api-put-role-mapping-example) for using wildcards for role mapping. 

> The current documentation makes you assume it supports splitting.

Could you please share exactly which section of the docs that gives that impression? It will help us for a more effective update. Thanks!

**Comment by KnowMoreIT** [comment]
@ywangd This is the guide I was following: https://www.elastic.co/guide/en/elasticsearch/reference/current/saml-guide-stack.html#:~:text=SAML%20authentication%20is%20enabled%20by,in%20detail%20in%20Security%20settings which does not mention anything about the limitation of the split groups. I understand it is on the other document you sent but I do not see where the SAML guide actually links to this. For better visibility it probably should be listed on the role mapping section for the SAML guide.

Down to the role mapping section it provides you an example:
```
PUT /_security/role_mapping/saml-finance
{
  "roles": [ "finance_data" ],
  "enabled": true,
  "rules": { "all": [
        { "field": { "realm.name": "saml1" } },
        { "field": { "groups": "finance-team" } }
  ] }
}
```

In my case I would assume it supports splitting because a member of Active Directory would not contain only the security group "finance_data". They may contain only "Domain Users" and "finance_data". I may be reading into it wrong but it gives the impression of group splitting (plus since most software that supports SAML does split them)

**Comment by ywangd** [comment]
Thanks for the providing more details. Sorry for the delayed the resposne. Ping @lockewritesdocs to see what we can do to the docs to improve our message about "we don't currently support spliting SAML string claims".
