### ISSUE TITLE
Tests failing on Graalvm due to thread leak detection errors

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#86494]
Looks like Graalvm is leaving behind some threads during test execution and our thread leak detection is picking this up. I suspect we may need to add a `ThreadFilter` for these things.

https://gradle-enterprise.elastic.co/s/2xkuaearkjocy/tests/:client:sniffer:test/org.elasticsearch.client.sniff.SnifferTests/classMethod?top-execution=1

cc @ChrisHegarty

**Comment by droberts195** [comment]
There's another example today in https://gradle-enterprise.elastic.co/s/qriqkhlpilozc/tests/:qa:no-bootstrap-tests:test/org.elasticsearch.bootstrap.SpawnerNoBootstrapTests/classMethod?top-execution=1

**Comment by grcevski** [comment]
We fixed something similar for the RestClientTests, we need to add the filter to the SpawnerNoBootstrapTests too.
