### ISSUE TITLE
starter script ignores errors when running Elasticsearch in background

### ISSUE THREAD

**Issue by herenowcoder** [elastic/elasticsearch#8652]
Hi!

`bin/elasticsearch` script does not handle errors from java app properly.
The example errors can be: inaccessible/missing log dir, data dir or conf file.

This causes init scripts to give false positives - eg. on CentOS6, `/etc/init.d/elasticsearch start` happily announces that daemon has started while it's not under above conditions like missing dirs or permissions.

Misbehaviour like this can have various funny consequences, like: invalidating logic inside Chef cookbooks and making services which depend on ElasticSearch go wild (depending on your setup/ Chef env).

The offending fragment is here:
https://github.com/elasticsearch/elasticsearch/blob/1664355f3/bin/elasticsearch#L153-L155

First, you can't do `exec` here as you did in the foreground case. I believe this `exec` could've been just copypasted from the foreground case few lines above :)

Second, there should be some check that the process is still running and behaving properly - for some values of "properly".
A most dumb trick would be something like `sleep 2; kill -0 $!` hoping that any early errors would make the background process exited.

A more elegant approach would be to handle daemonizing in an app only *after* it validated it actually can run as a daemon, but that's a story Java does not handle well I guess.

**Comment by bdharrington7** [comment]
Hi, what happened to this? is this still going to be merged? I'm running 1.7.1 on CentOS and still having this issue where elasticsearch will fail silently, and no logs pick anything up.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/13643
