### ISSUE TITLE
词库热刷新机制？

### ISSUE THREAD

**Issue by YanoDorian** [elastic/elasticsearch#86552]
### Description

请问elasticsearch-analysis-icu是否支持类似IK分词器词库热刷新机制

**Comment by cbuescher** [comment]
Hi @YanoDorian! There is not enough information for us to act on this issue.  Your question might better be suited to the support forums over at https://discuss.elastic.co where we also provide help in various languages. We prefer to use Github issues only for bug reports and feature requests. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
