### ISSUE TITLE
Client tests failing with ThreadLeakError

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#86567]
### CI Link

https://gradle-enterprise.elastic.co/s/mw2zhgjnaroxk
https://gradle-enterprise.elastic.co/s/og2cnfo5yzhyi

In both cases the tests ran on the `graalvm-ce17` JVM.

### Repro line
NA

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/London&tests.container=org.elasticsearch.client.RestClientMultipleHostsTests&tests.test=classMethod

### Failure excerpt
```
com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated: 
  | 1) Thread[id=24, name=Libgraal MBean Registration, state=TIMED_WAITING, group=main] |  
  | at java.base@17.0.3/java.lang.Thread.sleep(Native Method) |  
  | at platform/jdk.internal.vm.compiler.management/org.graalvm.compiler.hotspot.management.Factory.run(Factory.java:111) |  
```

**Comment by DaveCTurner** [comment]
https://gradle-enterprise.elastic.co/s/netzaya5gosq2 is another example. I don't think this is a :Clients issue tho, I'm relabelling it for core/infra attention.

**Comment by fcofdez** [comment]
A couple of new instances of this failure 
- https://gradle-enterprise.elastic.co/s/rybn62g4rsjly 
- https://gradle-enterprise.elastic.co/s/3nknf2hruzw2a
