### ISSUE TITLE
Log snapshot restores at INFO level

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#86610]
Today we don't record the start or end of a snapshot restore in the server logs by default (or even at `DEBUG` level). In contrast we do record regular index creation, and also the start and end of every snapshot. Snapshot restores are relatively rare, and it would definitely be helpful to see them in the logs.

I think we wouldn't want to see restores related to mounting searchable snapshots, nor creation of CCR followers, so we'd need a `silent` parameter rather like we have for index creation requests. I think we would usually want to see details of the restore request (e.g. the index pattern) in the log message.

**Comment by chen-ni** [comment]
If nobody is working on this, can I take it? It could be my first open source contribution other than fixing typos...  :)

**Comment by chen-ni** [comment]
@DaveCTurner Got it, thanks!

**Comment by kingherc** [comment]
Hi @DaveCTurner ,

> so we'd need a silent parameter rather like we have for index creation requests.

Could you point me to where this silent parameter is in the code, so I can get an idea?

**Comment by DaveCTurner** [comment]
The one I meant was e.g. a parameter to `MetadataCreateIndexService#applyCreateIndexRequest`.

In this case however I think it could reasonably be a new field in `RestoreSnapshotRequest`. We wouldn't expose this parameter in the REST layer (so external clients can't change it) but `TransportPutFollowAction` and `TransportMountSearchableSnapshotAction` have full control over the transport-layer request so they can set it to `silent`.
