### ISSUE TITLE
Error: [400]: mapper_parsing_exception: failed to parse field [geometry] of type [geo_shpe]: invalied_shape_exception: Self-intersection at or near point 

### ISSUE THREAD

**Issue by minias-tdi** [elastic/elasticsearch#86651]
### Elasticsearch Version

7.11

### Java Version

_bundled_

### OS Version

ubuntu 18.04

### Problem Description

There was a problem during bulk insert using [go-elasticsearch](https://github.com/elastic/go-elasticsearch).

[260/341]   Error: [400]: mapper_parsing_exception: failed to parse field [geometry] of type [geo_shape]: invalid_shape_exception: invalid_shape_exception: Self-intersection at or near point [127.87372734091298,37.03558631808967, 0.0]

but, the original data in the geojson file does not have a value of 0.0.

### Steps to Reproduce

It is presumed that there was a problem with the following code.

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/geo/GeoPolygonDecomposer.java#L624

```java
    private static Point[] coordinates(Edge component, Point[] coordinates, double[] partitionPoint) {
        for (int i = 0; i < coordinates.length; i++) {
            coordinates[i] = (component = component.next).coordinate;
        }
        // First and last coordinates must be equal
        if (coordinates[0].equals(coordinates[coordinates.length - 1]) == false) {
            if (Double.isNaN(partitionPoint[2])) {
                throw new IllegalArgumentException(
                    "Self-intersection at or near point [" + partitionPoint[0] + "," + partitionPoint[1] + "]"
                );
            } else {
                throw new IllegalArgumentException(
                    "Self-intersection at or near point [" + partitionPoint[0] + "," + partitionPoint[1] + "," + partitionPoint[2] + "]"
                );
            }
        }
        return coordinates;
    }
```

**Comment by iverase** [comment]
Hi @minias-tdi,

There has been many changes on that area so probably an upgrade would help but without more information (e.g a geometry that reproduces the error) it is very difficult to help here.

**Comment by iverase** [comment]
For lack of feedback, I am closing this issue. feel free to reopen it if information can be provided.
