### ISSUE TITLE
Allow wildcard "*" character in both front and back of words in SimpleQueryStringQuery

### ISSUE THREAD

**Issue by zlepper** [elastic/elasticsearch#86652]
### Description

The normal "QueryStringQuery" allows using wildcards in front of words to allow both suffix and prefix searching. (Although suffix searching requires passing another flag). 

However `SimpleQueryStringQuery` only allows for the wildcard in the end of words. We prefer to use the `SimpleQueryStringQuery` as it is tolerant towards errors, unlike `QueryStringQuery`, however we do need the ability to do both suffix and prefix searching. 

We are aware of the cost of allowing it, and it is something our customers explicitly has to enable in their system (With the proper warnings). 

The downside of the less tolerant `QueryStringQuery` is that we might sometimes have to show errors to our clients if they don't pass an actual valid query, and we don't find that entirely acceptable, considering that there is an _almost_ perfect alternative.

**Comment by javanna** [comment]
Thanks for opening this issue. The simple query string uses the simple query parser from Lucene, that only supports prefix wildcard searches. Using query_string is sadly the way to go here. In alternative, you could open an issue to [Lucene](https://issues.apache.org/jira/projects/LUCENE).
