### ISSUE TITLE
Incosistent behaviour while setting `rewrite_to_filter_by_filter` to true or false

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#86663]
### Elasticsearch Version

8.3.0

### Java Version

_bundled_

### OS Version

All

### Problem Description

In `rest-api-spec/test/analytics/nested_top_metrics_sort.yml` there are the following two tests:

* `terms order by top metrics size greater than 1 rewrite_to_filter_by_filter false`
* `terms order by top metrics size greater than 1 rewrite_to_filter_by_filter true`

Both tests execute the same query. The only difference is in the setting of `rewrite_to_filter_by_filter`, in one case it is `true` in the other it is `false`. The setting determines if the query is rewritten using the so called "filter by filter" optimisation. Query rewriting is an implementation detail and we should make sure the response provided to the client is the same no matter the value of the setting.

Here one query fails with an exception while the other not. We need to make sure the result is the same. We either fail both or we return the same aggregation result.

NOTE: right now the test is not failing because they are written in such a way to highlight the difference. After fixing the issue we expect to have the same result.

### Steps to Reproduce

Just execute the YAML tests.

**Comment by nik9000** [comment]
Do you mean #86582? I think that is *probably* ok because the documentation for `top_metrics` talks about not having a defined order for which document "wins" ties. I *think* that's what's happened here. But if you have another theory please post it.

**Comment by salvatore-campagna** [comment]
@nik9000 what I mean is that in one case passing `size > 0` is treated as an error and in the other not.

**Comment by nik9000** [comment]
Ah! That makes sense. Sorry, that's a bug.
