### ISSUE TITLE
Verify auto follower recover after full leader cluster restart

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#86672]
### Description

Currently we have a test that verifies auto following behavior regarding leader and follower cluster restart.

However remote cluster is disabled before the leader restart and configured again after:

https://github.com/elastic/elasticsearch/blob/33b3ccaabc6960f02c005b6bc14a1c527a24875b/x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java#L92-L96

This happens as leader cluster changes the port during the restart and otherwise would become not accessible.

**Comment by tlrx** [comment]
@idegtiarenko you recently worked on this test in #89116, do you think the current issue is still valid/needs to be fixed?

**Comment by idegtiarenko** [comment]
@tlrx it looks like this is no longer required locally. Let me open a pr to see if this passes on CI as well.
