### ISSUE TITLE
[CI Failure] failed to delete a dummy doc

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#8669]
We have a couple of occurrences where `ElasticsearchIntergrationTest` fails to delete a dummy document when `indexRandom` is used in tests.

See:
- http://build-us-00.elasticsearch.org/job/es_core_master_metal/5614/testReport/org.elasticsearch.recovery/RelocationTests/testRelocationWhileRefreshing/
- http://build-us-00.elasticsearch.org/job/es_core_master_metal/5618/testReport/junit/org.elasticsearch.recovery/RelocationTests/testRelocationWhileRefreshing/
- http://build-us-00.elasticsearch.org/job/es_core_master_debian/2529/
- http://build-us-00.elasticsearch.org/job/es_core_master_metal/5639/

**Comment by clintongormley** [comment]
Closing in favour of #13719
