### ISSUE TITLE
Clarify behaviour of terms query lookup across clusters

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#86745]
The `terms` query supports looking up the query terms by specifying an index/doc/path parameter from which to load a documetn with the query value. To me its not entirely sure whether and how this should work in a scenario where we search across multiple clusters.
For reproduction: connect two clusters (remote, local) via CCS, then setup the remote index like so:
```
PUT remote_test_index/_bulk
{ "index" : { "_id" : "1"}}
{ "animal" : "pig"}
{ "index" : { "_id" : "2"}}
{ "animal" : "pig"}
{ "index" : { "_id" : "3"}}
{ "animal" : "cow"}
{ "index" : { "_id" : "4"}}
{ "animal" : "dog"}
```
And the local index:
```
PUT /test_index/_bulk
{ "index" : { "_id" : "1"}}
{ "animal" : "pig"}
{ "index" : { "_id" : "2"}}
{ "animal" : "pig"}
{ "index" : { "_id" : "3"}}
{ "animal" : "cow"}
{ "index" : { "_id" : "4"}}
{ "animal" : "dog"}
```

The following query works and returns two documents, one from each cluster:
```
POST /test_index,my_remote:test_index/_search
{
  "query": {
    "terms" : {
      "animal.keyword": {
        "index" : "test_index",
        "id" : "3",
        "path" : "animal"
      }
    }
  }
}
```

while trying the same but getting the document from the remote cluster doesn't seem to work:
```
POST /test_index,my_remote:test_index/_search
{
  "query": {
    "terms" : {
      "animal.keyword": {
        "index" : "my_remote:test_index",
        "id" : "3",
        "path" : "animal"
      }
    }
  }
}
```
This returns the following error:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Cross-cluster calls are not supported in this context but remote indices were requested: [my_remote:test_index]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Cross-cluster calls are not supported in this context but remote indices were requested: [my_remote:test_index]"
  },
  "status" : 400
}
```

**Comment by javanna** [comment]
Terms lookup can only work when using CCS if the lookup index is local, under the coordinating cluster that receives the search. This is because terms lookup uses the get API to fetch the document with the id in it, and the get API does not support executing against remote clusters. This is briefly mentioned in the docs for the [terms query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup).
