### ISSUE TITLE
Range query does not respect date format of underlying field

### ISSUE THREAD

**Issue by pattersp** [elastic/elasticsearch#86768]
### Elasticsearch Version

8.2.0

### Java Version

_bundled_

### OS Version

Running docker.elastic.co/elasticsearch/elasticsearch:8.2.0 in minikube

### Problem Description

I have created a schema with a date field with format set to "epoch_second". A `range` query of this date field does not work unless I specifically specify the format as "epoch_second" in the range query. This is confusing because the docs [1] indicate that the format is optional if the format is specified in the field mapping:

"(Optional, string) Date format used to convert date values in the query.

By default, Elasticsearch uses the [date format](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) provided in the <field>'s mapping. This value overrides that mapping format."

[1]  https://www.elastic.co/guide/en/elasticsearch/reference/8.2/query-dsl-range-query.html

### Steps to Reproduce

Command to create the index:

```
curl -X PUT "$MINIKUBE_IP:12002/my_index" -H 'Content-Type: application/json' -d'
{
    "settings": {
       "number_of_shards": 1,
       "max_ngram_diff": 3,
       "analysis": {
          "filter": {
             "edge_ngram_filter": {
                "type": "edge_ngram",
                "min_gram": 3,
                "max_gram": 6,
                "preserve_original": true
             }
          },
          "analyzer": {
             "edge_ngram_filter_analyzer": {
                "type": "custom",
                "tokenizer": "standard",
                "filter": [
                   "stop",
                   "lowercase",
                   "edge_ngram_filter"
                ]
             }
          }
       }
    },
   "mappings" : {
       "dynamic": "strict",
       "properties" : {
         "start_time" : {
           "type" : "date",
           "format": "epoch_second"
         }
       }
     }
 }'
```

Command to index a document:

```
curl -X PUT "$MINIKUBE_IP:12002/my_index/_doc/my_doc" -H 'Content-Type: application/json' -d'
{
  "start_time" : 1652388420
}'
```

Command to fetch the document:

```
curl -X GET "$MINIKUBE_IP:12002/my_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
	"query": {
		"range": {
			"start_time": {
				"lte":1652388460
			}
		}
	}     	
}                              
'
```

Output: 
```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

If I explicitly specify epoch_second in the query, the output is what I expect:
```
pattersp@pattersp:/google/src/cloud/pattersp/sandboxing/google3$ curl -X GET "$MINIKUBE_IP:12002/my_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
        "query": {
                "range": {
                        "start_time": {
                                "lte":1652388460,
                                "format": "epoch_second"
                        }
                }
        }       
}                              
'
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "my_index",
        "_id" : "my_doc",
        "_score" : 1.0,
        "_source" : {
          "start_time" : 1652388420
        }
      }
    ]
  }
}
```

**Comment by ywelsch** [comment]
This is (unfortunately) the expected behavior, see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#numeric-date

> When no date format is specified and the range query is targeting a date field, numeric values are interpreted representing milliseconds-since-the-epoch. If you want the value to represent a year, e.g. 2020, you need to pass it as a String value (e.g. "2020") that will be parsed according to the default format or the set format.

This means that "lte":"1652388460" should do the trick

**Comment by javanna** [comment]
Closing based on the explanation above.
