### ISSUE TITLE
Stuck shard causing client nodes to run out of memory

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8677]
We had an instance where a shard is stuck during recovery (in initializing state) due to peer node connectivity issues during recovery.  When this occurs with concurrent indexing and searching to the cluster, all the client nodes started to run out of memory (adding a new client node does not help for that new client node will also end up running out of memory).  We collected the heap dump on OOM and it looks like a lot of heap is used in the netty buffer which doesn't seem right.

![screen shot 2014-11-26 at 2 49 04 pm](https://cloud.githubusercontent.com/assets/7216393/5208066/4368750a-7565-11e4-966c-a8cedbe2abff.png)

**Comment by kimchy** [comment]
@bleskes I think that potentially adding a circuit breaker on "public" actions, count towards it and down it when we send the response back through the channel might help in a more generic fashion, for most use cases.

**Comment by bleskes** [comment]
@kimchy yeah, that's another more generic solution. I wonder if we shouldn't just add indexing request to the current request circuit breaker, which is currently only used for big arrays, i.e., per requests aggs. We might want to split it into "bigarrays" and "indexing" sub breakers so it will be easy to monitor. I briefly looked at the code and it seems doable.

**Comment by clintongormley** [comment]
Fixed by the inflight circuit breaker https://github.com/elastic/elasticsearch/pull/17133
