### ISSUE TITLE
ANN support for nested vector fields

### ISSUE THREAD

**Issue by arozantsev** [elastic/elasticsearch#86787]
### Description

The ANN feature is great, however, it would also be great to have the possibility of running ANN queries on the nested vector fields. Right now from the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html#index-vectors-knn-search) it appears to be not possible.

**Comment by mayya-sharipova** [comment]
@arozantsev Thanks for submitting this issue. We are wondering what's your use case for nested vector fields.

**Comment by arozantsev** [comment]
Hey thank you for your reply! 

Our problem is the following. We have a collection of documents, which have some metadata information like creation dates, size, etc. For each document we also have a collection of embeddings which are generated by a neural network. The neural network generates not a single embedding but multiple ones and the number of embeddings per document can vary (e.g. depending on the document size).

So we would like to search through both metadata and embeddings (within the document and across all the documents in index) efficiently, for which (as far as I understand) we need to keep all this info in a single index. 

The what will be the best way to store varying number of embeddings per document without replicating metadata info? The current solution that we have is to store them in a nested field, as it allows for having variable number of embeddings per document. Is there an alternative approach to that?

**Comment by mayya-sharipova** [comment]
@arozantsev Thanks for explaining your use case. Right, currently we don't support having multiple vectors per document. But we are exploring ways to implement this functionality including having nested vector fields and ways to combine scores from multiple vectors to get a unified score for a document (sum of all scores, max, avg etc).

**Comment by arozantsev** [comment]
Ok, thank you very much for your reply! I think that would be really cool to have :)

**Comment by mayya-sharipova** [comment]
We are closing this issue in favour of https://github.com/elastic/elasticsearch/issues/72068 (allow to have multiple vectors per field).

Disadvantages of nested API over a native support of multiple vectors per field:
- Less performant indexing and querying (nested documents are separate docs in Lucene)
- There is no real use case for nested use case (Nested fields are usually used when there are multiple filters on different nested fields).
- Not clear and more complicated APIs for mapping and querying

**Comment by ezorita** [comment]
> We are closing this issue in favour of #72068 (allow to have multiple vectors per field).
> 
> Disadvantages of nested API over a native support of multiple vectors per field:
> 
>     * Less performant indexing and querying (nested documents are separate docs in Lucene)
> 
>     * There is no real use case for nested use case (Nested fields are usually used when there are multiple filters on different nested fields).
> 
>     * Not clear and more complicated APIs for mapping and querying

@mayya-sharipova would you reconsider the possibility of knn prefilters using nested fields for the use case described in #106994 ?
