### ISSUE TITLE
Some Changes In elasticsearch.service

### ISSUE THREAD

**Issue by al-ah** [elastic/elasticsearch#86794]
### Description

Review changes within the elastic service `/usr/lib/systemd/system/elasticsearch.service` and, if possible, apply the following.

The first is to prevent the elastic service from being killed by the operating system (OOM killer) :
```
# for prevent kill elasticsearch.service by OOM killer
OOMScoreAdjust=-1000
```

The second case is to increase the downtime (the current value of 75 seconds is problematic on some systems at startup time):
```
# Allow a slow startup before the systemd notifier module kicks in to extend the timeout
TimeoutStartSec=200
```

thanks

**Comment by pquentin** [comment]
While it's nice that those changes work for you, I don't think they're generally useful. For example, making the system (including Elasticsearch) does not use too much memory would solve the first case. And a 75 seconds timeout seems long enough on most systems, why did you need more?

**Comment by al-ah** [comment]
I recently installed elastic cluster on Ubuntu 22, but when I restarted the servers, the service was not running and it was time out.
