### ISSUE TITLE
BWC tests failing due to git permissions failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#86803]
BWC fail to run as git clone fails.

This has failed a couple of times on ubuntu:

 - https://gradle-enterprise.elastic.co/s/62qrl2o67t5ja
 - https://gradle-enterprise.elastic.co/s/sc7o4hgjwfrpk

```
fatal: unsafe repository ('/var/lib/jenkins/workspace/elastic+elasticsearch+8.2+multijob+packaging-tests-upgrade/BWC_VERSION/7.17.4/os/ubuntu-20.04-packaging' is owned by someone else) |  
  | To add an exception for this directory, call: |  
  |   |  
  | git config --global --add safe.directory /var/lib/jenkins/workspace/elastic+elasticsearch+8.2+multijob+packaging-tests-upgrade/BWC_VERSION/7.17.4/os/ubuntu-20.04-packaging
```

**Comment by benwtrent** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/3kjslsfgvonq6

**Comment by Luegg** [comment]
@mark-vieira not sure wether still relevant but I just got two more instances of what looks like the same issue:
https://gradle-enterprise.elastic.co/s/purnexge7kiky
https://gradle-enterprise.elastic.co/s/s32dnzwbfwirq

**Comment by mark-vieira** [comment]
Sorry for the back and forth on this, there ended up being a few things going on here which caused this issue to happen in our periodic builds, but not in the pull request checks. I've now got this sorted so we should be good to go.
