### ISSUE TITLE
[CI] CorruptedTranslogIT testCorruptTranslogFiles failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#86817]
### CI Link

https://gradle-enterprise.elastic.co/s/xantmxl3f5cgq

### Repro line

./gradlew ':server:integTest' -Dtests.seed=1C6001185BE7864D -Dtests.class=org.elasticsearch.index.store.CorruptedTranslogIT -Dtests.method="testCorruptTranslogFiles" -Dtests.security.manager=true -Dtests.locale=vun -Dtests.timezone=Kwajalein -Dcompiler.java=11 -Druntime.java=11

### Does it reproduce?

No

### Applicable branches

6.8

### Failure excerpt

```
FAILURE 10.3s J10 | CorruptedTranslogIT.testCorruptTranslogFiles <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: not null
   >      but: was null
   > 	at __randomizedtesting.SeedInfo.seed([1C6001185BE7864D:10515CAA0222AADE]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.store.CorruptedTranslogIT.lambda$testCorruptTranslogFiles$0(CorruptedTranslogIT.java:96)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:927)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:901)
   > 	at org.elasticsearch.index.store.CorruptedTranslogIT.testCorruptTranslogFiles(CorruptedTranslogIT.java:90)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:829)
   > 	Suppressed: java.lang.AssertionError: 
```

Creating a new issue, previous issues: https://github.com/elastic/elasticsearch/issues/72849

I am not sure if this contains the desired logging or not.

**Comment by DaveCTurner** [comment]
Sadly the extra logging wasn't backported to 6.8, but this branch is now closed for everything except extremely serious security issues so we aren't addressing occasional test failures like this one. It doesn't look like it's failed in any more recent branches since the last investigation so I'm closing this.
