### ISSUE TITLE
Feature Request: Keyed facet buckets for terms facets etc

### ISSUE THREAD

**Issue by NodexTech** [elastic/elasticsearch#8681]
Hi there. First off great tool, picked it up very quickly. One thing that's quite annoying from a normalisation point of view is the fact that one cannot set facet buckets for terms facets to keyed : true.

I know it's possible with ranges/date ranges and this makes life nice and easy when looping buckets but when trying to normalise the output i/e make sure all KEYS are the actual bucket name makes for unneeded code client side. 

The buckets for terms are numbered 0,1,2,3,4 etc and it would be much better to have a "keyed" option as we have in ranges/date ranges to have ES key the buckets with the key of the facet.

Just an idea ;)

**Comment by clintongormley** [comment]
Reread this ticket and I still don't get the point.  There has been no further interest in the last year, so I'm going to close this
