### ISSUE TITLE
Support fields under body as well as in url for field_caps API.

### ISSUE THREAD

**Issue by pryadko** [elastic/elasticsearch#86875]
### Description

Before ES 7.x it was possible to provide a list of fields by URL or BODY request for field_caps API.
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-field-caps.html
`POST _field_caps
{
   "fields" : ["rating"]
}`

Starting from 7.x this feature was removed, and only one possible way it uses URI but in this case, it is possible to have an error 414 (Request-URI Too Long).

I would like to return this feature back.

**Comment by pryadko** [comment]
@jtibshirani 
This error comes from the Elasticsearch server.
* isn't an option because you may receive fields that you don't request

**Comment by javanna** [comment]
This is somehow similar to #61141 , but for fields and very specific to the field_caps API. I do worry that there are possibly many other places where a similar change should be made if we go down this route. I marked it for discussion with the team.

**Comment by jtibshirani** [comment]
@pryadko sorry for the slow reply. I discussed with the team, and confirmed that Elasticsearch should not be throwing "414 "Request-URI Too Long". This must be coming from some other place, like a web server. Maybe it's possible to change the server configuration to allow larger requests?

We also recognized how the change we made could cause inconvenience. In other places like `search` you can pass parameters like `fields` in the body.

**Comment by pryadko** [comment]
@jtibshirani thank you for your answer. 
Allowing larger requests on ES server doesn't really solve this issue because nobody guarantee that tomorrow we won't have "414 "Request-URI Too Long" for some combination of request, also I don't think it is good idea to configure ES server in such a way to allow actually any request with such long URI.

Do you have a plan to fix this? or it still continues discussion? 
It will be good to allow user to choose which way to provide `fields`  via URI or payload.

**Comment by jtibshirani** [comment]
We don't have immediate plans to change this. The motivation for removing the ability to specify `fields` in the body was that we wanted only one way to specify the parameter. When there are multiple ways, it's unclear which one takes precedence (or if they're somehow merged together). This is part of our API design guidelines so we'd prefer not to undo that change.

We are still discussing the topic internally though, I'll post an update if anything changes.

**Comment by pryadko** [comment]
@jtibshirani thanks, 
I see it as a general issue for all APIs 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params
> Several options for this API can be specified using a query parameter or a request body parameter. If both parameters are specified, only the query parameter is used.

I'm looking forward to your decision.

**Comment by jtibshirani** [comment]
@elastic/es-clients do you have a suggestion for how to move forward? We want to avoid making a breaking change, like removing the ability to pass `fields` through a URI parameter. I see two options:
* Re-add support for `fields` in the request body. This violates our convention of "one single way to pass a parameter", but follows the convention of "passing variable-length request components in the request body". 
* Just close without making changes to minimize disruption.

**Comment by pryadko** [comment]
@jtibshirani thank you, I will try to help with this.

**Comment by gcamach0** [comment]
Hi! I would love to help, you think I can give it a try?
