### ISSUE TITLE
[Certs]: Java exceptions while creating certs using `elasticsearch-certutil` tool.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elasticsearch#86940]
**Kibana version:**  8.3 Snapshot Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.3.0 Snapshot self-managed
BUILD: 52512
COMMIT: df225b213b188c81888141cee2ec191424fc0649
Elasticsearch artifact link: https://snapshots.elastic.co/8.3.0-6ba9f710/downloads/elasticsearch/elasticsearch-8.3.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 8.3 Snapshot Kibana self-managed environment should be available.

**Steps to reproduce:**
1. Navigate to `C:\elk\elasticsearch\bin>` through cmd.
2. Run below command:
`elasticsearch-certutil ca --pem`
3. Observe Java exceptions on running cert creation command.

**Expected Result:**
 CA cert should be created on running `elasticsearch-certutil ca --pem` command.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/167078819-20c28e8e-5886-443f-8ab7-1e58d80fb1e2.JPG)

**Comment by slobodanadamovic** [comment]
@amolnater-qasource Since you are using Windows, try running `.bat` script instead. 
Meaning, you should run this command:
`elasticsearch-certutil.bat ca --pem`

There was a change introduced in 8.3.0 for all CLI tools (see #85821) which would result in `StringIndexOutOfBoundException` if you don't call `.bat` script on Windows.

I think we could improve this and handle it more gracefully. 
But someone from @elastic/es-core-infra team might be better commenting on this issue.

**Comment by rjernst** [comment]
Sorry this slipped through our filters and I'm just seeing this now. I've opened a PR with a fix:
https://github.com/elastic/elasticsearch/pull/86944

**Comment by amolnater-qasource** [comment]
Hi @slobodanadamovic 
Thanks for the detailed information regarding this update.
We have revalidated this issue on latest 8.3 Snapshot and found it not reproducible when elasticsearch tools are run with `.bat`.
- We are now successfully able to create certs.

**Screenshot:**
![12](https://user-images.githubusercontent.com/77374876/169506856-f40cc6e4-683d-449e-9cda-cbca09090c0c.JPG)

Further as per PR: https://github.com/elastic/elasticsearch/pull/86944
We are now able to run elasticsearch tools without `.bat` too.

**Screenshot:**
![14](https://user-images.githubusercontent.com/77374876/169507336-310c2383-1070-4d06-8909-11732dd41194.JPG)

**Artifact link:** https://snapshots.elastic.co/8.3.0-3a5a0cd2/downloads/elasticsearch/elasticsearch-8.3.0-SNAPSHOT-windows-x86_64.zip

Hence marking this as **QA:Validated**.
cc: @rjernst 
Thanks

**Comment by amolnater-qasource** [comment]
## Bug Conversion

- Test-Case not required as this particular checkpoint is already covered in the following test plan:
   - https://elastic.testrail.io/index.php?/cases/view/147842
 
Thanks!
