### ISSUE TITLE
[CI Failure] IndexAliasesTests.testWaitForAliasSimultaneousUpdate

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#8699]
Test failure aside the assertion/ debug information is not very helpful in figuring out what went wrong in case the test fails:

Expected: <true>      got: <false>
http://build-us-00.elasticsearch.org/view/ES%20Master/job/es_core_master_metal/5632/testReport/junit/org.elasticsearch.aliases/IndexAliasesTests/testWaitForAliasSimultaneousUpdate/

**Comment by s1monw** [comment]
this hasn't failed in a long time.... closing
