### ISSUE TITLE
[CI Failure] MinimumMasterNodesTests.multipleNodesShutdownNonMasterNodes

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#8700]
MockDirectoryWrapper: cannot close: there are still open files: {_0.si=1}

http://build-us-00.elasticsearch.org/view/ES%201.4/job/es_core_14_centos/966/testReport/junit/org.elasticsearch.cluster/MinimumMasterNodesTests/multipleNodesShutdownNonMasterNodes/

**Comment by s1monw** [comment]
this hasn't failed in a long time.... closing
