### ISSUE TITLE
bad indexing performance in elasticsearch 8.2.0

### ISSUE THREAD

**Issue by AlexanderOtt85** [elastic/elasticsearch#87036]
### Elasticsearch Version

8.2.0

### Java Version

_bundled_

### OS Version

docker-image = docker.elastic.co/elasticsearch/elasticsearch:8.2.0

### Problem Description

We are trying to migrate from Elasticsearch 6.7.1 to Elasticsearch 8.2.0.

With the same amount of documents per bulk request (100 docs per request), we always get a socket timeout in Elasticsearch 8.2.0. Everything works fine in Elasticsearch 6.7.1.

I noticed that indexing the same document in Elasticsearch 8.2.0 takes 44152ms. In Elasticsearch 6.7.1, indexing takes 50ms.

### Steps to Reproduce

[elasticsearch_8.2.0.txt](https://github.com/elastic/elasticsearch/files/8754299/elasticsearch_8.2.0.txt)
[elasticsearch_6.7.1.txt](https://github.com/elastic/elasticsearch/files/8754300/elasticsearch_6.7.1.txt)

**Comment by ywelsch** [comment]
I've run the steps and was able to reproduce the issue. The document takes multiple seconds to index on 8.x while it takes fractions of a second to index on 6.x. There looks to be a regression here, hot_threads have not been very helpful pinpointing it though.

I've minimized the example that shows the issue (only the `"du": { "bc": [ ... ]` part of the document seems to be relevant, and adding more items to that array looks to lead to blow-up of indexing time). I suspect it has to do something with these weird copy_to clauses.

Can you provide more context on why there is so much cross-copying?
