### ISSUE TITLE
Runtime fields and _source disabled

### ISSUE THREAD

**Issue by trengrj** [elastic/elasticsearch#87072]
### Elasticsearch Version

8.2

### Java Version

_bundled_

### OS Version

Ubuntu 20.04.4 LTS

### Problem Description

Currently when using runtime fields it is not possible to search using `fields` when the index has `_source` disabled.

It will fail with `Unable to retrieve the requested [fields] since _source is disabled in the mappings for index [example-disabled]` even if `_source` isn't being used in a runtime field. Steps below.

Ideally this would fail only if the runtime field referenced `_source` fields.

Usecase is that certain logging platforms configure Elasticsearch indices with `_source` disabled (even though this is not recommended) and `store: true` for fields. Having more flexibility in using runtime fields in this instance would make migrations easier.

### Steps to Reproduce

Create indices with `_source` enabled or disabled.

```
PUT example-enabled
{
  "mappings": {
    "_source": {
      "enabled": true
    }, 
    "runtime": {
      "age": {
        "type": "long",
        "script": {
          "source": "emit(1)"
        }
      }
    }
  }
}

PUT example-disabled
{
  "mappings": {
    "_source": {
      "enabled": false
    }, 
    "runtime": {
      "age": {
        "type": "long",
        "script": {
          "source": "emit(1)"
        }
      }
    }
  }
}

PUT example-disabled/_doc/1
{}

PUT example-enabled/_doc/1
{}
```

Search over both indices:

```
GET example-*/_search
{
  "fields": [
    "age"
  ]
}
```

Response

```
{
  "took" : 459,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 1,
    "failures" : [
      {
        "shard" : 0,
        "index" : "example-disabled",
        "node" : "fNuQNb81QsC6Yb0jAnUATw",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Unable to retrieve the requested [fields] since _source is disabled in the mappings for index [example-disabled]"
        }
      }
    ]
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "example-enabled",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : { },
        "fields" : {
          "age" : [
            1
          ]
        }
      }
    ]
  }
}
```

**Comment by javanna** [comment]
This is definitely a bug, we should have adapted the code back when we added support for fetching runtime fields, as they can totally be retrieved with _source disabled. Looks like we did not have tests that covered this scenario.
