### ISSUE TITLE
Add `force-recover` corrupted shards command to reroute

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#8708]
we give advice to `rm` shards on the FS if they got corrupted like here https://github.com/elasticsearch/elasticsearch/issues/8707 I personally think we should have an endpoint to force recovery for these shards to make it easier for users.

**Comment by jayc89** [comment]
+1

**Comment by nabheet** [comment]
+1

**Comment by nick4eva** [comment]
+1

**Comment by Bertg** [comment]
:+1:

**Comment by erikringsmuth** [comment]
:+1:

**Comment by phreakinggeek** [comment]
:+1: :+1:

**Comment by ishare** [comment]
does it mean propose to be added to v2.0.0 ?

**Comment by pataditya** [comment]
+1

**Comment by s1monw** [comment]
I think we can close this @bleskes since we now allocate them fresh on the corrupted node from the primary?

**Comment by bleskes** [comment]
+1 to close this.  A corrupted shard should be replaced with a fresh copy now.

**Comment by phreakinggeek** [comment]
Is that true for single node ES instances as well?
