### ISSUE TITLE
[CI] Compile failure in example plugins :security-authorization-engine:compileJava

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#87113]
### CI Link

	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+example-plugins/131/console

### Repro line

none

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

Two times today already

### Failure excerpt

13:43:40 > Task :security-authorization-engine:compileJava
13:43:40 /dev/shm/elastic+elasticsearch+main+periodic+example-plugins/plugins/examples/security-authorization-engine/src/main/java/org/elasticsearch/example/CustomAuthorizationEngine.java:189: error: cannot find symbol
13:43:40             new PrivilegesCheckResult.Details(clusterPrivMap, indices, privilegesByApplication));
13:43:40                                      ^
13:43:40   symbol:   class Details
13:43:40   location: class PrivilegesCheckResult
13:43:40 Note: /dev/shm/elastic+elasticsearch+main+periodic+example-plugins/plugins/examples/security-authorization-engine/src/main/java/org/elasticsearch/example/CustomAuthorizationEngine.java uses or overrides a deprecated API.
13:43:40 Note: Recompile with -Xlint:deprecation for details.
13:43:40 1 error
13:43:40 
13:43:40 > Task :security-authorization-engine:compileJava FAILED

**Comment by cbuescher** [comment]
Probably related to 346abf9816e20057192776092ed6646a3cbb1fbf, so I'm assigning to @albertzaharovits

**Comment by mark-vieira** [comment]
This actually was fixed in the related PR but we are waiting on an updated snapshot build with the changes.

**Comment by slobodanadamovic** [comment]
The issue with`CustomAuthorizationEngine` been resolved and as such I will close it.
