### ISSUE TITLE
enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS

### ISSUE THREAD

**Issue by dylex** [elastic/elasticsearch#87146]
### Description

This is to reopen #2863 as a feature request.  It would be nice to have some option to enable non-numeric numbers in the json parser, to allow things like NaN in float values, at least for stored fields.  Unless there is some underlying reason in Lucene that this won't work?

**Comment by pgomulka** [comment]
@dylex, can you please reopen and ask on #2863?
I will close this one as it would be a duplicate

**Comment by dylex** [comment]
@pgomulka yes that's what I was asking -- I don't have permission to reopen issues, I think only maintainers can.
