### ISSUE TITLE
[CI failure] GetIndexBackwardsCompatibilityTests.testGetAliases

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#8718]
See http://build-us-00.elasticsearch.org/job/es_bwc_1x/5370/CHECK_BRANCH=tags%2Fv1.1.2,jdk=JDK7,label=bwc/testReport/junit/org.elasticsearch.bwcompat/GetIndexBackwardsCompatibilityTests/testGetAliases/

after wading through the logs the following happens here:
* One node starts up with 1.x version
* Two external nodes with 1.1.2 startup
* An external transport client tries to connect to an external node and fails

The test reproduces, using 1.x branch and 1.1.2 snapshot on my machine, and I am not sure what happens there yet.

The `IllegalStateException` is a followup exception due to exception handling on the wrong thread on netty level in earlier versions and can be ignored.

Call to reproduce after installing 1.1.2

```
mvn test -Dtests.seed=C459A34B357EFF9A -Dtests.class=org.elasticsearch.bwcompat.GetIndexBackwardsCompatibilityTests -Dtests.bwc=true -Dtests.filter=@backwards -Dtests.method="testGetAliases" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.heap.size=512m -Dtests.bwc=true -Dtests.bwc.version=1.1.2 -Dtests.locale=iw -Dtests.timezone=Asia/Yakutsk -Dtests.processors=8
```

**Comment by s1monw** [comment]
this hasn't failed in a long time.... closing
