### ISSUE TITLE
Add the possibility to hide/show a series programmatically

### ISSUE THREAD

**Issue by Gianlo98** [elastic/elasticsearch#87197]
### Description

I'm using elastic charts for a class project, and we came up with a line chart with lots of series. 
Having all of them enabled by default brings the chart to be unreadable. An idea to solve this issue could be to put the property `isSeriesHidden` in the `SeriesSpec` interface. 

Ideally, it should differ from `hideInLegend` because it brings the series to be always shown and hidden in the legend, instead `isSeriesHidden` should show the series in the legend but already hidden (so you can click to show it)

**Comment by gmarouli** [comment]
Hi @Gianlo98, thank you for your interest in elastic charts. This appears to be related to [elastic-charts](https://github.com/elastic/elastic-charts) and not elasticsearch. Would you mind opening this enhancement request in that GitHub repo? 

I hope you do not mind that I close this issue.
