### ISSUE TITLE
difference between Elastic search and Solr

### ISSUE THREAD

**Issue by HelloTo4x** [elastic/elasticsearch#87200]
### Description

Hi all, do anyone know what difference between Elastic search and Solr

**Comment by gmarouli** [comment]
Hi @HelloTo4x, thank you very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by HelloTo4x** [comment]
no problem, can u refer the link of this
