### ISSUE TITLE
Random score changes after update

### ISSUE THREAD

**Issue by KPGDL** [elastic/elasticsearch#87245]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Ubuntu

### Problem Description

As per documentation - using `_seq_no` can keep scores consistent but will regenerate random score as document get's updated because `_seq_no` is changed as well. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random

> A good default choice might be to use the _seq_no field, whose only drawback is that scores will change if the document is updated since update operations also update the value of the _seq_no field.

So what I did - I used a field from the document that is unique `id` and it's not subject of an update (it's not changing at all - never) - still after partial update of document the random score is changing - why?

### Steps to Reproduce

1. Use search query with function_score with following function - where the field (`id`) is unique field in document:
    {
          "script_score": {
            "script": "_score + randomScore(10, 'id')"
          }
    }
2. Update any other document (or the same) but do it on other field.
3. Run the search query - the score has changed for all documents but should not as per documentation (as we are not using a field that is changing during update).

**Comment by KPGDL** [comment]
```
PUT randomscore-bug

POST randomscore-bug/_doc
{
  "id": 342,
  "name": "apple tree",
  "description": "Apple tree, is not a pinapple tree"
}

POST randomscore-bug/_doc
{
  "id": 531,
  "name": "cherry tree",
  "description": "Cherry tree, is not a pinapple tree and not apple tree."
}

POST randomscore-bug/_doc
{
  "id": 234,
  "name": "plum tree",
  "description": "Plum tree, is not a pinapple tree, not apple tree and not cherry tree."
}


GET randomscore-bug/_search
{
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "minimum_should_match": 1,
          "should": [
            {
              "simple_query_string": {
                "query": "tree",
                "fields": [
                  "name^5",
                  "description^1"
                ]
              }
            }
          ]
        }
      },
      "functions": [
        {
          "script_score": {
            "script": "_score + randomScore(10, 'id')"
          }
        }
      ]
    }
  }
}

#partial update of document
POST randomscore-bug/_update/7dp8I4EBH5Mk-bLc0PGe
{
  "doc": {
    "description": "Cherry tree, is not a pinapple tree and not apple tree."
  }
}
```

**Comment by ywelsch** [comment]
You're using both _score and randomScore in your script. The randomScore is not changing after the update here (i.e. as you wanted it to be), but _score is (which is to be expected).

You can validate this by removing `_score +` from the script, leaving only the `randomScore(10, 'id')` in.

The reason the _score is changing not only for the document that you updated, but also for other documents is that the inverse document frequency (IDF) is changing (see https://www.elastic.co/blog/found-similarity-in-elasticsearch).

I'm closing the issue as this isn't a bug.
