### ISSUE TITLE
Add support for random sampling `time_series` aggregation

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#87300]
### Description

`time_series` aggregation provides an exceptionally powerful tool for aggregating various timeseries metric buckets in a fast and efficient way. 

As it stands, it currently must be the top level aggregation in the request. This, by definition, prevents it from being nested under the `random_sampler` aggregation.

This can be remedied, and would provide some pretty incredible speed improvements for ginormous timeseries data streams.

To complete this work, investigation needs to be done around making `TimeSeriesIndexSearcher` aware of the sampling context.

Since this is created within the prefetch phase and is aware of the aggregator factories, it is possible to construct and pass a `SamplingContext` object to the `TimeSeriesIndexSearcher`.

This would then allow the user provided query to be boolean-ed with the `RandomSamplingQuery` background filtering query.

The leaf iterators should then be able to read the docs via the sampled set and along with user provided filters without issue. 

The trick will be in how to tell the `random_sampler` agg that it shouldn't attempt to feed its docs down directly itself and rely on `TimeSeriesIndexSearcher` to do the work.

**Comment by martijnvg** [comment]
The `time_series` aggregation and related time series aggregation capabilities is still in tech preview and will stay in tech preview. When tsdb support is added to es|ql, then the `time_series` aggregation and related time series aggregation capabilities will be removed from aggregations. Besides missing random sampling support, there are currently also other usability and performance issues around using the `time_series` aggregation. Which we are unlikely to fix anytime soon.

When building time series support in es|ql we will need to take into account supporting (random) sampling. Similar challenges that exist now with `time_series` aggregation will need to be solved too in es|ql.

With this said, I'm closing this issue.
