### ISSUE TITLE
[DOC] Improve/clarify multi-field addition requires update by query or reindex

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/elasticsearch#87339]
### Description

The documentation pages linked below mention it is possible to add multi-fields after the index creation, which is correct.

- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#add-multi-fields-existing-field-ex
- https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html

But we do not mention the fact the documents need to be updated in order to be populated.

It would be useful to add a banner to warn the users about it.

A simple `POST <index>/_update_by_query` would be enough (or eventually a query to filter documents where the "root" field exist to reduce the amount of modified documents)

**Comment by nik9000** [comment]
> A simple `POST <index>/_update_by_query` would be enough (or eventually a query to filter documents where the "root" field exist to reduce the amount of modified documents)

You'd probably want to add whatever incantation it needs to ignore version conflicts. That way it wouldn't stop if someone changes the documents after you issue the command.

**Comment by anthonymcglone2022** [comment]
@debadair @abdonpijpelink could I take a look at this issue?

**Comment by abdonpijpelink** [comment]
Sure, go for it. Thank you, @anthonymcglone2022

**Comment by abdonpijpelink** [comment]
Addressed in https://github.com/elastic/elasticsearch/pull/91541. Closing.
