### ISSUE TITLE
[CI] plugins:analysis-icu:test and :x-pack:plugin:old-lucene-versions:test fail due to leaked libgraal thread

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#87332]
Relates #86976

**Build scan:**
https://gradle-enterprise.elastic.co/s/o6zmy6tk2ehii/tests/:plugins:analysis-icu:test/org.elasticsearch.plugin.analysis.icu.IcuAnalyzerTests/classMethod

https://gradle-enterprise.elastic.co/s/hrsc7jvznkaho/tests/:x-pack:plugin:old-lucene-versions:test/org.elasticsearch.xpack.lucene.bwc.codecs.lucene50.BlockPostingsFormat2Tests/classMethod

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.analysis.icu.IcuAnalyzerTests&tests.test=classMethod

https://gradle-enterprise.elastic.co/s/hrsc7jvznkaho/tests/:x-pack:plugin:old-lucene-versions:test/org.elasticsearch.xpack.lucene.bwc.codecs.lucene50.BlockPostingsFormat2Tests/classMethod

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.plugin.analysis.icu.IcuAnalyzerTests: 
   1) Thread[id=25, name=Libgraal MBean Registration, state=WAITING, group=main]
        at java.base@17.0.2/java.lang.Object.wait(Native Method)
        at java.base@17.0.2/java.lang.Object.wait(Object.java:338)
        at platform/jdk.internal.vm.compiler.management/org.graalvm.compiler.hotspot.management.Factory.run(Factory.java:100)

  at __randomizedtesting.SeedInfo.seed([AE066ACAC77B5412]:0)

```

**Comment by rjernst** [comment]
@grcevski We should probably have the graal threadleak filter on ESTestCase?
