### ISSUE TITLE
Better error message for GrantApiKey API

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#87438]
Users with only `manage_own_api_key` privilege is not allowed to use the [GrantApiKey API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-grant-api-key.html#security-api-grant-api-key). The overall behaviour is correctly implemented but the error message could use some improvements. Currently it is something like the follows:

```
POST _security/api_key/grant
{
  "password": "password",
  "grant_type": "password",
  "username": "foo",
  "api_key": {
    "name": "k1"
  }
}

===
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "manage own api key privilege only supports API key requests (not org.elasticsearch.xpack.core.security.action.apikey.GrantApiKeyRequest)"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "manage own api key privilege only supports API key requests (not org.elasticsearch.xpack.core.security.action.apikey.GrantApiKeyRequest)"
  },
  "status": 400
}
```

This is different from other unauthorized error messages which should be along the line of 
> action [..] is unauthorized for user [...] with roles [...], this action is granted by ..

The status code should also be `403` instead of `400`.

**Comment by n1v0lg** [comment]
@ywangd I'd be happy to take a stab at this, unless you're already working on it/want to pick this one up yourself. lmk!

**Comment by ywangd** [comment]
> I'd be happy to take a stab at this, unless you're already working on it/want to pick this one up yourself. lmk!

I don't plan working on it anytime soon. Thanks for picking it up!
