### ISSUE TITLE
matrix_stats aggregation doesn't work with bucket_selector aggregation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#87454]
### Elasticsearch Version

latest unreleased (main), latest released - 8.2.2

### Java Version

_bundled_

### OS Version

irrelevant

### Problem Description

It is not possible to reference the `kurtosis` calculation from a `matrix_stats` aggregation in a `bucket_selector` aggregation.

### Steps to Reproduce

```
POST /test/_bulk?refresh

{"index":{"_id":1}}
{"name":"test","numeric":123}
```

Running the following query

```
{
    "size": 0,
    "_source": false,
    "aggs": {
        "matrix": {
        	"filters": {
        		"filters": [
        			{"match_all":{}}]
        	},
        	"aggs": {
        		"my_stats": {
		            "matrix_stats": {
		                "fields": [
		                    "numeric"
		                ],
		                "mode": "AVG"
		            }
		        },
		        "filter_stats": {
		            "bucket_selector": {
		                "buckets_path": {
		                    "a0": "stats['numeric'].kurtosis"
		                },
		                "script": {
		                    "source": "params.a0 > params.v0",
		                    "lang": "painless",
		                    "params": {
		                        "v0": 1
		                    }
		                }
		            }
		        }
        	}
    	}
    }
}
```

Results in this error message

```
{
    "error": {
        "root_cause": [
            {
                "type": "aggregation_execution_exception",
                "reason": "Invalid path element [stats['numeric'].kurtosis] in path [stats['numeric'].kurtosis]"
            }
        ],
        "type": "aggregation_execution_exception",
        "reason": "Invalid path element [stats['numeric'].kurtosis] in path [stats['numeric'].kurtosis]"
    },
    "status": 500
}
```

According to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline.html#buckets-path-syntax where one can use the syntax `sale_type['hat']>sales` where `hat` is an actual term from the index, I should be able to reference a specific statistic for a specific field (since `matrix_stats` allows multiple field names in its definition) with a syntax like `agg_name['field_name'].statistical_value` (ie `stats['numeric'].kurtosis`).

**Comment by benwtrent** [comment]
Can confirm, matrix_stats does not allow you to filter by "bucket" (field name). It only allows you to grab the statistics stored in the individual maps. 

See: https://github.com/elastic/elasticsearch/blob/fa4953adca7c82a749c983bef86f3e562138e31e/modules/aggs-matrix-stats/src/main/java/org/elasticsearch/search/aggregations/matrix/stats/InternalMatrixStats.java#L204

The change to support getting by field first and then by stats shouldn't be difficult.
