### ISSUE TITLE
SQL: make automatic type conversion consistent

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#87500]
Currently, most of the SQL implementation relies on the usage of the Search API, that in many circumstances does automatic type conversion.
Eg. both the following queries

```
SELECT * FROM foo WHERE id = "1";
SELECT * FROM foo WHERE id = 1;
```

will return results where `id` property value is `1` (numeric).

This behavior should be preserved in all the SQL operations that are not pushed to Search, like during query optimization/folding, local execution and on operations translated to Painless scripts.

Particular attention has to be put on date math expressions (eg. "now-10") that have to be evaluated and then converted.

**Comment by luigidellaquila** [comment]
Related issues:
https://github.com/elastic/elasticsearch/issues/77055
https://github.com/elastic/elasticsearch/issues/87268

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
