### ISSUE TITLE
Power BI Desktop

### ISSUE THREAD

**Issue by ineo00048** [elastic/elasticsearch#87512]
Power BI Desktop https://apps.microsoft.com/store/category/Business?hl=en-us&gl=US

**Comment by pugnascotia** [comment]
Hello @ineo00048, it's not clear whether this is a bug report, feature request, or question. If you have a question about Elasticsearch, I encourage you to ask on [discuss.elastic.co](https://discuss.elastic.co/).

Note that you can use the Elasticsearch ODBC driver to access Elasticsearch data from Microsoft Power BI Desktop](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/sql-client-apps-powerbi.html).

I'm going to close this issue, but feel free to reopen it if you have more information to give us.
