### ISSUE TITLE
Painless script error in Kibana, works fine in discover - request error:string_index_out_of_bounds_exception begin 0 end -1 length 10

### ISSUE THREAD

**Issue by danilansible** [elastic/elasticsearch#87547]
### Elasticsearch Version

7.17.1

### Java Version

_bundled_1.8.0_322

### OS Version

3.10.0-1160.59.1.el7.x86_64

### Problem Description

Below scripted field works fine in preview and also in discover showing the first part of a string in xx-yy-zz i.e xx
But throws below error in kibana visualization when selecting this term variable.
**request error:string_index_out_of_bounds_exception begin 0 end -1 length 10 in if ( doc['var'].size()==0  || doc['var'].empty || doc['var'].value=='') { ... painless script**

below is my scripted field, excuse my experience in painless, relatively new

if ( doc['var'].size()==0  || doc['var'].empty || doc['var'].value=='') { 
    return "NA";
} else {
    def m = /([a-zA-Z0-9].*-*-*)$/.matcher(doc['var'].value);
    if ( m.matches() ) {
        String str = doc['var'].value;
        String id =str.substring(0,str.indexOf("-")); 
        return(id);
        //return m.group(0); 
    } else {return "NoMatch"}
}

### Steps to Reproduce

create a scripted field in kibana index, try to visualise the term in kibana

**Comment by nik9000** [comment]
We try to keep github for bug reports rather than requests for help using Elasticsearch. It's probably better to open this on https://discuss.elastic.co/

For what it's worth, it looks like `indexOf` is returning `-1` because it can't find `-`. I don't really know why because the matches matched, but bugs are sneaky sometimes. Sorry!

**Comment by danilansible** [comment]
Thank you for the comment @nik9000 . Will do that.
