### ISSUE TITLE
Extend the Runtime Fields API to allow for removing fields via shadowing

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#87585]
### Description

Provide for extended functionality with Runtime Fields to shadow an existing field for the purposes of hiding or removing it from to behave in the same way as if the field was not there.

Using the example from: https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-indexed.html

If you wanted to remove the `voltage` field you might shadow it to remove it like:

```
PUT my-index-000001/_mapping
{
  "runtime": {
    "voltage": null    
  }
}
```

or 

```
PUT my-index-000001/_mapping
{
  "runtime": {
    "voltage": {
      "hidden": true
    }
  }
}
```

So that this field then behaves like doesn't exist.

Benefits to this might be easily reducing the impact of a field explosion if you were able to hide all the unwanted fields from existing indices without having to reindex or allowing you to reindex at a later point without the need to delete the index or remove it from any aliases and still be able to search/agg the data without the impact from field explosion.
For example a response from the Field Caps API with field explosion might be many megabytes and without it might be much smaller that then avoids impact on downstream systems or processes to avoid having to process a large json payload.

You'd want to be clear of the purpose of this feature so that users don't use it for less suitable purposes like trying to hide PII with runtime field shadow removal as the data is still there and can likely be gotten to again without much effort.

**Comment by javanna** [comment]
I think I understand what you mean, but I would like to know more about what problem you are after solving here, especially as you mentioned field explosion and field_caps. Would you hide fields so that field_caps does not return them when called with `fields=*` ? Are there other aspects to this enhancement request that I am missing?

**Comment by geekpete** [comment]
The general idea would be the dynamic ability to delete a field without reindex, the potentially extreme use case for it could be preventing impact of something like field caps API by having that API return a much smaller payload with shadowed runtime field hiding in the case of hiding a large amount of fields.

For field explosion, it'd basically provide an alternative to removing an index from an alias/deleting it to avoid it being searchable to avoid the impact or reindexing it to get rid of the fields. 
Field caps was mentioned as it turned out to be a particularly expensive call (in this [SDH](https://github.com/elastic/enhancements/issues/16363)) in both latency for such a large payload to transfer around and processing that payload if the amount of fields was quite large (eg over 10k).

And generally yes the usual APIs wouldn't see hidden fields returned as part of the payload because the runtime mappings hiding them would prevent it and it'd be like those fields were just not there.
(Obviously the mapping would still be potentially huge with lots of fields being shadowed and likely there's some overhead doing it this way, but it's dynamic and would be a functionality we don't have today).

**Comment by javanna** [comment]
I am still struggling to understand where this feature would help other than reducing the response size of field_caps, which can be reduced by trimming down the number of requested fields. I suspect this has to do with Kibana always asking for all fields, unfortunately.

You mentioned the scenario of "deleting a field without reindex", but the field would still be there, so what is the advantage other than reducing the size of field_caps, given that mappings size stays the size as well as the disk size used by the field? I am trying to see an advantage with e.g. time based indices for hiding a field that will be later removed, but the real solution for that usecase is really to stop indexing the field at the next rollover and phase it out like that.

**Comment by geekpete** [comment]
Perhaps with non-time based indices the ability to delete a field and have it not searchable (though still stored) could be more useful especially if reindex is particularly painful or inconvenient. 

If we think this isn't really worth the probably considerable effort to build it due to less scape and lack of "force multiplier" value where other use cases and products/solutions can utilise this feature then I'm happy to close it out.

**Comment by javanna** [comment]
What I'm torn on is that hiding a field is considered to not have it returned by field_caps, which accepts a fields parameter to request specific fields. If trimming down field_caps output is all there is to it, I would much rather work on consumers filtering which fields request. I will mark this for discussion just to double check how the team feels about this. Thanks for your input!

**Comment by javanna** [comment]
I am closing this as other improvements have been identified by Kibana when processing many fields returned by field_caps. This enhancement was more of a short term work-around which we decided not to go ahead with.

**Comment by geekpete** [comment]
Possibly a related idea: https://github.com/elastic/elasticsearch/issues/91440
