### ISSUE TITLE
Unassigned Shards After 8.2 Upgrade

### ISSUE THREAD

**Issue by simps7b2** [elastic/elasticsearch#87611]
This is a cross-post from this forum question: https://discuss.elastic.co/t/unassigned-shards-after-upgrade-to-8-2/304717.

I am managing an Elasticsearch cluster deployed to our Azure environment. I am trying to upgrade our test single-node cluster from 7.x to 8.2. I have done the following:

- Upgraded to 7.17.3 and confirmed all shards were in working order
- Installed Kibana and walked through the upgrade assistant and modified my Elasticsearch.yml as recommended (used the node.roles config item instead of the deprecated node.xxx config items)
- Stopped ES using service elasticsearch stop. I did not perform a flush or anything.
- Manually installed the Debian 8.2 package
- Restarted ES.

I also tried getting Kibana to upgrade, but it won't start, so I'm leaving it be for now. The upgraded ES will start, but 5 of the 62 shards are unassigned. Looking in the ES log I see this error multiple times:

`Caused by: java.lang.IllegalArgumentException: cannot change field "attachment.content" from storeTermVector=true to inconsistent storeTermVector=false`

A full startup log up to the first error is here: https://1drv.ms/u/s!AkKqV4fHPyyeg7dlVkgh5ZyqcRT3qQ?e=6joLFI. 

We are indexing attachments using the attachment plugin where file content may be as large as 120MB.

**Comment by simps7b2** [comment]
I did do some disk partitioning to accommodate a larger data partition before the upgrade. But ES was reporting all shards as online right before the upgrade, so I'm pretty sure that didn't have anything to do with it. I may get a chance to retry the upgrade in a couple weeks as I now have a fully healthy test cluster up and running on 17.x after I restored the old VM image.

**Comment by dnhatn** [comment]
@simps7b2 We identified this bug and fixed it in Lucene 9.2. Please see https://issues.apache.org/jira/browse/LUCENE-10518 for the detail. The fix was released in Lucene 9.2, and will be included in Elasticsearch 8.3. We are sorry that we hit this bug. A workaround is to force merge unassigned shards with Elasticsearch 7.17 before opening them with Elasticsearch 8.2.

**Comment by dnhatn** [comment]
Thanks @simps7b2 for the reply. I am closing this issue as it was fixed in https://issues.apache.org/jira/browse/LUCENE-10518.
