### ISSUE TITLE
Setup elasticsearch dependency monitoring with Snyk

### ISSUE THREAD

**Issue by breskeby** [elastic/elasticsearch#87620]
We want to monitor the elasticsearch dependencies on a regular basis using Snyk to be able to recognise vulnerabilities faster and being able to proactively react on security issues within the production dependencies. 

- [x] Setup Gradle plugin for monitoring dependencies in snyk ( [#88036](https://github.com/elastic/elasticsearch/pull/88036) )
- [x] Allow configuring snyk target reference and lifecycle properties ( [88220](https://github.com/elastic/elasticsearch/pull/88220) )
- [x] Setup CI job for automated update of snyk dependency monitoring of versions under development ( [88522](https://github.com/elastic/elasticsearch/pull/88522) )
- [x] Setup automation to update of snyk dependency monitoring of released versions

**Comment by mark-vieira** [comment]
> My assumption (possibly mistaken) has been that published SBOMs would include only what is included in the released product and would not include test code.

This would be my understanding as well. I think publishing test dependencies would only cause confusion for folks. From my perspective test dependencies are completely internal and have nothing to do with the delivered software. I'd argue we should explicitly omit them for that reason, completely independent of the level of effort of including this information.

**Comment by breskeby** [comment]
Understood. So for now we will only monitor dependencies for now that are shipped with our distro and can be a potential security thread for our customers.

**Comment by breskeby** [comment]
We've integrated the snyk monitoring data publishing of released versions as part of the elasticsearch finalize release step
