### ISSUE TITLE
How to use nested type to store multiple vector fields and retrieve vectors

### ISSUE THREAD

**Issue by dyyTT** [elastic/elasticsearch#87626]
### Description

How to use nested type to store multiple vector fields and retrieve vectors,Thanks

**Comment by mayya-sharipova** [comment]
@dyyTT Thank you for filing this issue. 

When you say "multiple vector fields", do you mean multiple vector values for the same field in a document?  If yes, currently there is no way to do this at Elasticsearch. And there is already a [duplicate issue](https://github.com/elastic/elasticsearch/issues/86787)  on this.

Or do you really mean multiple vector fields? Then why do you need nested type for it? You can create multiple vector fields on the top level.

**Comment by dyyTT** [comment]
> Or do you really mean multiple vector fields? Then why do you need nested type for it? You can create multiple vector fields on the top level, and it is supported.
@mayya-sharipova  I have some dialogue text. I need to split each dialogue text into each sentence and convert it into vectors, so I want to store these vectors in the same field with nested type for easy query.

**Comment by dyyTT** [comment]
> @dyyTT感谢您提交此问题。
> 
> 当您说“多个向量字段”时，您是指文档中同一字段的多个向量值吗？如果是的话，目前 Elasticsearch 没有办法做到这一点。并且已经有一个[重复的问题](https://github.com/elastic/elasticsearch/issues/86787) 。
> 
> 或者你真的是指多个向量场？那你为什么需要嵌套类型呢？您可以在顶层创建多个矢量场，并且它是受支持的。

I have some dialogue text. I need to split each dialogue text into each sentence and convert it into vectors, so I want to store these vectors in the same field with nested type for easy query

**Comment by dyyTT** [comment]
> @dyyTT感谢您提交此问题。
> 
> 当您说“多个向量字段”时，您是指文档中同一字段的多个向量值吗？如果是的话，目前 Elasticsearch 没有办法做到这一点。并且已经有一个[重复的问题](https://github.com/elastic/elasticsearch/issues/86787) 。
> 
> 或者你真的是指多个向量场？那你为什么需要嵌套类型呢？您可以在顶层创建多个矢量场，并且它是受支持的。

@mayya-sharipova   I have some dialogue text. I need to split each dialogue text into each sentence and convert it into vectors, so I want to store these vectors in the same field with nested type for easy query

**Comment by mayya-sharipova** [comment]
@dyyTT Thanks for explaining your use case.  This is a duplicate [duplicate issue](https://github.com/elastic/elasticsearch/issues/86787) on this.  So I will be closing this issue.

Feel free to add more about your use case in https://github.com/elastic/elasticsearch/issues/86787 (for example it would be useful to know if need to know which particular vector of the document was matched?).
