### ISSUE TITLE
Performance regression with geoshape queries in 7.10

### ISSUE THREAD

**Issue by mhugo** [elastic/elasticsearch#87651]
### Elasticsearch Version

7.10

### Java Version

_bundled_

### OS Version

Linux hugods 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

### Problem Description

When preparing a migration from ES 6.8 to ES 7.17, we found what looks like a performance regression on some shape queries.

After searching the ES commit that introduces this regression, we found it is when Lucene version was updated from 8.6.2 to 8.7.0 (in [this PR](https://github.com/elastic/elasticsearch/pull/61957))

The regression is better observed on a multisearch where for some configurations, we can see a x2-x4 slowdown. It still exists on simple/non-multi search, but to a lesser extent (something like 15% slowdown).

It occurs when lots of polygons are indexed and we try to issue a "point in polygon" query.

I would be happy to give additional information to help investigate the problem. Thanks for your help.

### Steps to Reproduce

So far, the reproduction involves an important amount of data. Here are some steps to reproduce with a small (unix) shell script.

1. Download a geojson file with several polygons. I've used shapes coming from one of our public datasets. A good example is `curl "https://public.opendatasoft.com/api/explore/v2.0/catalog/datasets/georef-france-commune-millesime/exports/geojson?select=geo_shape&where=reg_code=53&refine=year:2021" -o reg53.geojson` which contains 1208 shapes of cities
2. Create an index with one field of type geo_shape
3. Index all shapes of the geojson. Calling `jq -c '.features[]|({"index":{}},{"geoshape":.geometry})'` can convert GeoJSON's features into documents that can be ingested by the bulk API
4. Issue a multisearch that repeats, say 50000 times, the following query: `{"query":{"bool":{"filter":[{"geo_shape":{"geoshape":{"shape":{"type":"Point","coordinates":[-3.383390,47.757460]},"relation": "intersects"}}}]}}}`
5. Test the multisearch query on a version before the aforementioned commit and again on a version after the commit

A (bash) script that helps to reproduce the issue can be found [here](https://gist.github.com/mhugo/724320454f14a39ec3809ece5d9e00b4)

I observe a 50% slowdown with this example on my machine. On a larger dataset (all polygon cities, but this is too large for the simple script described here) with >34000 polygons and the exact same multisearch query I can see a 4x-5x regression.

**Comment by wchaparro** [comment]
@craigtaverner,  @iverase

**Comment by iverase** [comment]
I think this is a known issue, see https://github.com/elastic/elasticsearch/issues/67574.

Could you run your performance test [disabling stored fields](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-fields.html#disable-stored-fields)? That would tell us if you are hitting this issue.

**Comment by mhugo** [comment]
@iverase Thanks for your answer.
I confirm disabling stored fields cancels the performance degradation observed here.

However ... disabling stored fields means we won't be able to retrieve values from `_source` anymore ?

**Comment by iverase** [comment]
I would hope that this issue should be less important in 7.17. 

Lucene developers changed again the way stored fields are compressed to recover most of the lost [performance](https://issues.apache.org/jira/browse/LUCENE-9917) lost in version 8.1.0  which it is used from Elasticsearch 7.16 onwards. Do you still see such a degradation in 7.17?

**Comment by mhugo** [comment]
We initially detect the performance regression on 7.17.
After some quick tests, it seems indeed the regression is less important in 7.17 than in 7.10 but it is still not neglectable. I have to run some more tests to have more precise numbers though.

**Comment by iverase** [comment]
@mhugo what is the state of your investigation here? we have no actionable data here so I am wondering if it is ok to close this issue.

**Comment by iverase** [comment]
I am closing this issue as there was no feedback for a long time. Please feel free to open it again if there is any input we can work with.
