### ISSUE TITLE
Cumbersome default value like boot and adjust_pure_negative

### ISSUE THREAD

**Issue by BruceZu** [elastic/elasticsearch#87671]
### Description

In the test case to verify the `BoolQueryBuilder` result, I do not want to see the cumbersome default value like boot and adjust_pure_negative, I want to focus on the business logic only.
Especially when I check the  `BoolQueryBuilder` result where it is not all about must-not logic, the adjust_pure_negative still appears in the result of method `toString()`. So confusing and noisy. 

I hope there is a method that can be provided to let `toString(boolean humanreadable )` to filter them out 

"{\"bool\":{\"adjust_pure_negative\":true,\"boost\":1.0}}"

=>

"{\"bool\":{}}"

**Comment by javanna** [comment]
Makes sense. We have also figured that it's not great to print out all the default values, and this is not only a test issue. It causes problems for instance when slow queries are logged in the slowlog, as huge queries are logged including all of their default values which would be omitted. This will be addressed with #76515 . Bool query is already in the list.

**Comment by BruceZu** [comment]
@javanna  Hi Luca, thank you for your feedback! And I am glad to see it is accepted and put in plan now. :)
