### ISSUE TITLE
Define a NWordGram analyser (similar to NGram analyser)

### ISSUE THREAD

**Issue by fraf** [elastic/elasticsearch#87677]
### Description

Hi searchers,

I was reading the elastic search documentation about analyser/tokenizer/token filters possibilities. And I didn't found what I'am looking for. A tokenizer is missing : the NWordGram analyser.
Consider it exactly the as NGram or EdgeNGram tokenizer, but considers not per character analysis but per word analysis.
Of course, the concept of word delimiter would be possible through a param for this NWordGram (or EdgeNWordGram) tokenizer.
By default, it should be whitespace ("\s+" in java's regexp).

Here is the algorithm : 

POST _analyze
{
  "analyzer": "nwordgram",
  "text": "The Brown-Foxe jumped over dog's bone."
}

suppose params "min_word" set to 1, max_word set to 2, "worddelimiter" set to blank characters, we should obtain following tokens : 

- word size = 1 (similar to standard tokenizer)

The, Brown-Foxe,  jumped, over, dog's, bone.

- word size = 2
The Brown-Foxe, Brown-Foxe jumped,  jumped over, over dog's, dog's bone.

- word size = x (x <= max_word) etc.

Of course, the analyser's parameters should allow to define what is a word. E.g., the token "bone." should not contain the final point of course.

**Comment by cbuescher** [comment]
The functionality you are looking for already exists as the [Shingle Analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-shingle-tokenfilter.html). Please let us know if anything is missing there in terms of functionality, I will close this issue in the meantime.
