### ISSUE TITLE
[Telemetry] Report cluster health in _xpack/health

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/elasticsearch#87686]
### Description

The health issues of the cluster should be reported under `_xpack/health` and collected as part of the telemetry so that Elasticsearch health can be aggregated by health indicators to understand what are the common health issues.

The output may look like this `GET _xpack/health`:
```
{
  "global_status" : "yellow",
  "indicators" : [ 
    "instance_has_master" : {
      "status" : "red",
      "causes": [
        "master_resource_saturated"
      ] 
    },
    "shards_availability" : {
      "status" : "yellow",
      "causes": [
        "no_valid_copy", "cluster_routing_disabled", "index_routing_disabled"
      ]
    },
    "ilm" : {
      "status" : "red",
      "causes": [
        "disk_full_on_warm_tier"
      ]
    },   
    "repository_integrity" : {
      "status" : "green"
    },
    "slm" : {
      "status" : "green"
    } 
  ] 
}
```
The output above is very similar to the output of `_internal/health` but without any summary or details. It only needs to contain the `indicator` level `status` and `causes` so that we can aggregate data and find out what % of clusters are having a yellow or red status for certain indicators and the causes of these status.

**Comment by Kushmaro** [comment]
@Leaf-Lin I think its actually more worthwhile to pin point specific issues here. The point of this telemetry (in my mind) is to understand what *specific* issues are most common in ES (and in my viewpoint, on ES managed by ECK)

**Comment by andreidan** [comment]
Given that telemetry runs once a day I think it'd rather be a function of chance to get an overview of a fleet deployments ie. is the telemetry _catching_ the deployment in that poor YELLOW state it's been all day, or is it catching it just at the tail as it's just switched to GREEN? 

I think elasticsearch could record some in-memory stats whenever a health API request is received and if the RCA is performed record diagnosis. 

When telemetry is collected we could attempt to retrieve these stats from all the nodes in an elasticsearch cluster, which baring node restarts, would represent the state that was read via the health API for a cluster. Telemetry could perform diffs between reads to get periodic health data trends.

**Comment by andreidan** [comment]
Closed in favour of https://github.com/elastic/elasticsearch/issues/90877
