### ISSUE TITLE
Upgrade assistant: Check back here when it's time to upgrade to Elastic 8.0.

### ISSUE THREAD

**Issue by knyttl** [elastic/elasticsearch#87715]
### Elasticsearch Version

7.17.3

### Java Version

_bundled_

### OS Version

Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

### Problem Description

I would like to use the migration assistant to prepare migration to ES8, however the assistant says:

> Check back here when it's time to upgrade to Elastic 8.0.

It is time :-)

![Screenshot 2022-06-16 at 8 27 22](https://user-images.githubusercontent.com/401107/174006050-378224c3-b870-421f-ae13-6f0bc21dd546.png)

**Comment by andy250** [comment]
Getting the same. What was the solution @vojkny ?

**Comment by vojkny** [comment]
I don't remember exactly, but I think I did the migration manually.

**Comment by a2741890** [comment]
For anyone come to here, before upgrade to 8.0, you need to at least upgrade to 7.17.0 and then you will be able to use Upgrade Assistant.

FYI (if you are using Elastic Cloud):
Go to https://www.elastic.co/ and log in -> Click Manage button of your deployment -> Click "Your deployment name" on the left panel -> Check your Deployment version and click Upgrade to choose your preferred version
