### ISSUE TITLE
[CI] Real-cluster tests pick ports that clash with ESTestCase port ranges

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#87734]
In https://github.com/elastic/elasticsearch/issues/87448 we saw a test failure because the failing test was using port 35677 which was also in use by a different test case. I think the other test case involved a real cluster since it had a build hash, and since we shouldn't have any clashes between `ESTestCase`-based tests running with different test workers thanks to #85777. As far as I can tell we set `http.port: 0` and `transport.port: 0` in these real-cluster tests which causes Elasticsearch to choose some arbitrary free port from the ephemeral port range. Is it possible 35677 is considered an ephemeral port on some workers?

If so, I see a couple of options:

- reduce the ephemeral port range on all workers so it doesn't overlap the ports chosen by an `ESTestCase`, or
- be specific about which ports each node should use, chosen using the same algorithm as `ESTestCase` to avoid collisions:

https://github.com/elastic/elasticsearch/blob/06d5baaba5f85bf72ad29ead79566721d2cefa62/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java#L1691-L1756

**Comment by mark-vieira** [comment]
I don't think this was caused by a test cluster taking that port but by another unit test. See [my comment](https://github.com/elastic/elasticsearch/issues/87448#issuecomment-1158028326) in the linked issue.

**Comment by mark-vieira** [comment]
I guess would just configuring these settings with a port range < 13301 work? ES would then choose a port within that range, yes?

**Comment by DaveCTurner** [comment]
That will stop us binding to a port that another test thinks it owns indeed. I think we also use these ephemeral ports for outbound connections but AIUI this won't cause the same kinds of problem.
