### ISSUE TITLE
[CI] JdbcCsvSpecIT » test {unsigned-long.testMedianAbsoluteDeviationLargeInput}

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#87738]
### CI Link

https://gradle-enterprise.elastic.co/s/ljbuxje5wvnwi

### Repro line

`./gradlew ':x-pack:plugin:sql:qa:server:security:without-ssl:javaRestTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT" -Dtests.method="test {unsigned-long.testMedianAbsoluteDeviationLargeInput}" -Dtests.seed=8EEFD52BB968E6D2 -Dtests.locale=ar-IQ -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=19`

### Does it reproduce?

Didn't try

### Applicable branches

8.3

### Failure excerpt

    java.lang.AssertionError: Different column type for column [mad] (KEYWORD != DOUBLE) expected:<12> but was:<8>

There are actually 4 tests that fail:

[JdbcCsvSpecIT » test {unsigned-long.testExtendedStatsAggregateFunctionsWith...](https://gradle-enterprise.elastic.co/s/ljbuxje5wvnwi/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT/test%20%7Bunsigned-long.testExtendedStatsAggregateFunctionsWithScalarsLargeInput%7D)
[JdbcCsvSpecIT » test {unsigned-long.testMedianAbsoluteDeviationLargeInput}](https://gradle-enterprise.elastic.co/s/ljbuxje5wvnwi/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT/test%20%7Bunsigned-long.testMedianAbsoluteDeviationLargeInput%7D)
[JdbcCsvSpecIT » test {unsigned-long.testExtendedStatsAggregateFunctionsWith...](https://gradle-enterprise.elastic.co/s/ljbuxje5wvnwi/tests/:x-pack:plugin:sql:qa:server:security:without-ssl:javaRestTest/org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT/test%20%7Bunsigned-long.testExtendedStatsAggregateFunctionsWithScalarsLargeInput%7D)
[JdbcCsvSpecIT » test {unsigned-long.testMedianAbsoluteDeviationLargeInput}](https://gradle-enterprise.elastic.co/s/ljbuxje5wvnwi/tests/:x-pack:plugin:sql:qa:server:security:without-ssl:javaRestTest/org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT/test%20%7Bunsigned-long.testMedianAbsoluteDeviationLargeInput%7D)

**Comment by bpintea** [comment]
Happened again, https://gradle-enterprise.elastic.co/s/2uqqs6ltmzwlu
It seems to only occur with Java 19, does not repro locally with Java 18.

**Comment by astefan** [comment]
The latest Java 19 ea (early access) is `openjdk-19-ea+26` released on June 10th. With `openjdk-19-ea+19` this test doesn't fail. Definitely related to the most recent release of Java 19.

**Comment by ChrisHegarty** [comment]
@astefan This test passes for me with `openjdk-19-ea+26`. Have you been able to reproduce?

```
$ ./gradlew ':x-pack:plugin:sql:qa:server:security:without-ssl:javaRestTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT" -Dtests.method="test {unsigned-long.testMedianAbsoluteDeviationLargeInput}" -Dtests.seed=8EEFD52BB968E6D2 -Dtests.locale=ar-IQ -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=19
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 12.4 (aarch64)
  Runtime JDK Version   : 19-ea (Oracle)
  Runtime java.home     : /Users/chegar/binaries/jdk-19-ea-b26.jdk/Contents/Home
  Gradle JDK Version    : 18.0.1.1 (Oracle)
  Gradle java.home      : /Users/chegar/binaries/jdk-18.0.1.1.jdk/Contents/Home
  Random Testing Seed   : 8EEFD52BB968E6D2
  In FIPS 140 mode      : false
=======================================

BUILD SUCCESSFUL in 3s
476 actionable tasks: 4 executed, 472 up-to-date
```

**Comment by astefan** [comment]
@ChrisHegarty hm... I did see it fail for me.
Can you try one more thing please? Go to `SpecBaseIntegrationTestCase`, `test` method and add to this method the `@Seed` annotation with the second seed from the failure? Like this `@Seed("6BBEAF117948B2A")`. And then run the same test with the same seed in the `gradlew` command.

**Comment by astefan** [comment]
I don't think it's necessary, unless your curiosity and time allows it :-). As a wild guess, it may be related to how Java is parsing the value with "E" as a string/double and decides it's a String and not a number.
