### ISSUE TITLE
Latest snapshot attempt failed

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#87758]
This is related to `Last successful snapshot was {lastSuccess}`. 

Imagine a scenario where "Latest snapshot attempt failed", and "last successful was 3 months ago" vs "Latest snapshot attempt failed", and "last successful was 40 mins ago".  The former is more severe and the latter is less severe.  Both of them need to make aware to users, but with a different impact/severity warning. 

Cloud will look in the health response to get the `cloud-snapshot-policy` policy information on the `found-snapshots` repo.

**Comment by jbaiera** [comment]
@andreidan is it fair to say that this is covered by https://github.com/elastic/elasticsearch/pull/88523? Did you have any thoughts on anything else this issue should cover?

**Comment by andreidan** [comment]
@jbaiera With the new changes proposed by @Leaf-Lin 
(ie. the impact copy change and including the timestamps of the last successful snapshot) we can close this issue
