### ISSUE TITLE
Last successful snapshot was {lastSuccess}

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#87757]
Is it possible to read the SLM policies and compare `last_success` to current time. 

- If (`last_success.time` - `current_time`) > `scheduled_frequency`+ `threshold` : red
- If (`last_success.time` - `current_time`) < `scheduled_frequency`: green

I added a `threshold` here to tolerate a possible delay.  We might want to tune this threshold because if the snapshot was a few minutes late, things might still be ok.  If the snapshot was few hours late, users would be interested to know.  

Ensuring ES take a regular snapshot in the `found-snapshot` repo is our responsibility https://www.elastic.co/cloud/shared-responsibility as part of the agreement to users. 

The SLM policy is in `cloud-snapshot-policy` (which is the one we provide) and stored on `found-snapshots` repo. Cloud will be able to filter the results of this indicator and look for the specific `found-snapshots` repository and the `cloud-snapshot-policy` policy.

**Comment by LeonardoMMFontoura** [comment]
Hey there. I would love to help with this issue. Can I work on it? Is there a way to reproduce the problem in the code? I mean get some more clarification, like which file would we need to change and etc.

**Comment by jbaiera** [comment]
The concept of `scheduled_frequency` (and relatedly, `threshold`) here is a bit of a challenge. SLM operates on a cron mechanism which allows for finer grained control over the scheduling frequency compared to a simple frequency. The snapshot might be executed every 30 minutes, but it could also be "scheduled at the bottom of the hour, hourly, for a 5 hour window, on weekends only". 

A policy that executes on the formerly mentioned "every 30 minute" schedule could probably handle a few failures in a row before we put up a health warning, whereas a policy running the latter "weekly small window" schedule requires a bit more thought in how many failures it can reasonably accept before throwing up a red status.

I started looking into maybe a maths solution where we have exponentially smaller tolerance for failures the longer the period between executions, but it just doesn't work with Cron expressions that are more complicated than fixed delays. We should keep this real simple - if the last failure is more recent than the last success, return a yellow result, unless a universal threshold is passed. We'll make it configurable, let's say a default of 24 hours. If that threshold is passed then return a red health status. 

If we wanted to get more fancy than that, perhaps we could configure the failure warning threshold on the policy itself? I could see users wanting to know immediately if a data set that is critical to their use case is behind on snapshots by more than 30 minutes. Same applies for the opposite case where some data may not be as important, and 24 hour period of failure is acceptable on snapshots that only run daily.

Final thought here - I know we want to keep users from becoming desensitized to yellow status, so we should probably have a yellow warning threshold as well. I figure we can base these on our current cloud usage? Maybe default to a 3 hour window for yellow and a 24 hour window for red?

**Comment by andreidan** [comment]
Thanks for zooming in on this issue Jimmy.

I agree it can get complex to parse the cron job into something we can reason about in the context of tolerance for failure.

I like your proposal of starting simple with a configurable "grace period" and just checking the `last_success.time` against this grace period and issuing a `red` status if the period lapsed? (maybe 24 hours - configurable?). I'm thinking we could potentially avoid the `yellow` status altogether here.

**Comment by jbaiera** [comment]
This is completed with https://github.com/elastic/elasticsearch/pull/88523
