### ISSUE TITLE
7.17.1 Kubernetes/Helm Chart - Failing with master_not_discovered_exception

### ISSUE THREAD

**Issue by beckyjmcdabq** [elastic/elasticsearch#87766]
We are deploying Elasticsearch version 7.17.1 to Kubernetes along with Fluentd and Kibana.  Everything runs fine for 3-6 days and we eventually get exceptions in the elasticsearch pod logs.  We are deployig using the "Official Elastic helm chart for Elasticsearch".

The endpoint:  https://elasticsearch.fqdn.gov/_cat/indices?v
shows:  {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}

We have this same helm chart deployed to other clusters and we don't get this error (elasticsearch is stable for weeks/months).

The cluster where we see the problem does have the following characteristics:
1) Single node barmetal cluster
2) Application/workload logging has more volume on this cluster

Here is the elasticsearch values that we override:

`elasticsearch:`
`  imagePullPolicy: "Always"`

`  replicas: 3`
`  minimumMasterNodes: 2`

`  clusterHealthCheckParams: "wait_for_status=green&timeout=1s"`

`  rbac:`
`    create: true`

`  podSecurityPolicy:`
`    create: true`

`  volumeClaimTemplate:`
`    accessModes: [ "ReadWriteOnce" ]`
`    resources:`
`      requests:`
`        storage: 300Gi`
`persistence:`
`    enabled: true`
`    labels:`
`      # Add default labels for the volumeClaimTemplate fo the StatefulSet`
`      enabled: true`
`    annotations: {}`

`  # Hard means that by default pods will only be scheduled if there are enough nodes for them`
`  # and that they will never end up on the same node. Setting this to soft will do this "best effort"`
`  antiAffinity: "soft"`

`  # Enabling this will publically expose your Elasticsearch instance.`
`  # # Only enable this if you have security enabled on your cluster`
`  ingress:`
`    enabled: true`
`    annotations: {}`
`      # kubernetes.io/ingress.class: nginx`
`      #     # kubernetes.io/tls-acme: "true"`
`    path: /`
`    hosts:`
`      - elasticsearch.some.domain.com`
`    tls:`
`      - secretName: ingress-default-cert`
`        hosts:`
`          - elasticsearch.some.domain.com`

`  esJavaOpts: "-Xmx16g -Xms16g"`
`  resources:`
`    requests:`
`      cpu: "4000m"`
`      memory: "32Gi"`
`    limits:`
`      cpu: "4000m"`
`      memory: "32Gi"`

And we have a kubernetes job that sets the following settings through the API:

`"settings": {`
`    "index": {`
`      "lifecycle": {`
`        "name": "fluentd-policy",`
`        "rollover_alias": "fluentd"`
`      },`
`      "routing": {`
`        "rebalance": {`
`          "enable": "all"`
`        },`
`        "allocation": {`
`          "include": {`
`            "_tier_preference": "data_content"`
`          }`
`        }`
`      },`
`      "mapping": {`
`        "total_fields": {`
`          "limit": "2000"`
`        }`
`      },`
`      "refresh_interval": "10s",`
`      "number_of_shards": "3",`
`      "provided_name": "fluentd-000001",`
`      "creation_date": "1655387882509",`
`      "number_of_replicas": "1",`
`      "uuid": "ZgYyOcAOTomuDl-zkPKX-w",`
`      "version": {`
`        "created": "7170199"`
`      }`
`    }`

Do you have any idea why were are getting the **master_not_discovered_exception/503** message?

We are in the process of adding 3 additional Kubernetes worker nodes that will be dedicated to scheduling elasticsearch only.  But, it will take a while to get this in place and we aren't 100% confident that it is going to solve this issue.

**Comment by beckyjmcdabq** [comment]
In looking at one of the elasticsearch-master pod logs, I see:

"type": "server", "timestamp": "2022-06-16T13:25:15,090Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "**this node is unhealthy: health check failed due to broken node lock**", "cluster.uuid": "D0Wo5puETIiSZOZNiDHaqg", "node.id": "IklrHUxVS_OFTiVn-fC1KA"  }
{"type": "server", "timestamp": "2022-06-16T13:25:18,358Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "path: /*/_mapping, params: {index=*, filter_path=*.mappings._meta.beat,*.mappings._meta.package.name,*.mappings._meta.managed_by,*.mappings.properties.ecs.properties.version.type,*.mappings.properties.data_stream.properties.type.value,*.mappings.properties.data_stream.properties.dataset.value}", "cluster.uuid": "D0Wo5puETIiSZOZNiDHaqg", "node.id": "IklrHUxVS_OFTiVn-fC1KA" ,
"stacktrace": ["**org.elasticsearch.discovery.MasterNotDiscoveredException: null**",

**Comment by original-brownbear** [comment]
@beckyjmcdabq there should be a warn level log line with the message "lock assertion failed" before the messages you pasted in your master pod logs. Could you find it and paste it here, it will tell us why the lock was broken. Likely it's a result of your volume being backed by nfs or some other network file system which tends to have compatibility issues with Lucene's file lock mechanism.
Thanks!

**Comment by beckyjmcdabq** [comment]
> lock assertion failed

The problem just happened again, this time after 7d23h of pod uptime.

I'm only getting partial logs but the following is repeated quite a bit:

{"type": "server", "timestamp": "2022-06-24T09:57:01,075Z", "level": "WARN", "component": "o.e.i.c.IndicesClusterStateService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "[fluentd-000008][1] marking and sending shard failed due to [shard failure, `reason [already closed by tragic event on the index writer]`]", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ" ,
"stacktrace": ["org.apache.lucene.store.AlreadyClosedException: `Underlying file changed by an external force at 2022-06-23T16:17:41Z,` (lock=NativeFSLock(path=/usr/share/elasticsearch/data/nodes/0/indices/9iOhvTUcSvilrhFLptUHSw/1/index/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2022-06-23T16:17:41.882277033Z))"

"Caused by: org.apache.lucene.store.AlreadyClosedException: `Underlying file changed by an external force at 2022-06-16T13:57:29Z,` (lock=NativeFSLock(path=/usr/share/elasticsearch/data/nodes/0/node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2022-06-16T13:57:29.048350936Z))",

The interesting thing about this Kubernetes environment is that it is running on a baremetal machine.  Our other environments are Virtual Machines.

The kubernetes storage class is "localpath-provisioner":

`$ kubectl get pv -n logging | grep elasticsearch`
`pvc-279dea35-a7e7-4fe5-b5f4-86a05e24c256   300Gi      RWO            Delete           Bound    logging/elasticsearch-master-elasticsearch-master-2   local-path              40m`
`pvc-71fa7a67-2dfd-45f0-a57a-4e8229bc9473   300Gi      RWO            Delete           Bound    logging/elasticsearch-master-elasticsearch-master-1   local-path              40m`
`pvc-8ba93cc2-27a7-4ddb-98a9-e7753bbaffd4   300Gi      RWO            Delete           Bound    logging/elasticsearch-master-elasticsearch-master-0   local-path              40m`

Would attach log files but they are too big.

Any insights?  We do not see this on our VM based clusters and it happens on this single node baremetal cluster after a period of time (6-7 days).

We are in the process of moving elasticsearch to its own dedicated nodes (VMs) so hoping that alleviates the problem but would still like to gain insight into why this happens on our current node.

The theory was that total disk space was exceeding the watermark thresholds and ES was locking itself.  But we've put in alerts for total disk space hitting 80% and we didn't get any alerts when this happened today.

**Comment by beckyjmcdabq** [comment]
Looking a little more closely at the log.  Everything looks fine up until 06/24/2022.  Note these logs are in UTC time and local time is -6 hours from the times in the logs.  The last good log message was on 06/24/2022:05:52:39 (which would be just before midnight local time) - log line 119.

Then on log line 119, things start to get weird with the **GeoIpDownloader**

Log context:
```
   118 {"type": "server", "timestamp": "2022-06-23T07:22:11,377Z", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "[gc][580622] o       verhead, spent [279ms] collecting in the last [1s]", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   119 {"type": "server", "timestamp": "2022-06-24T05:52:39,262Z", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "[gc][661589] o       verhead, spent [325ms] collecting in the last [1s]", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   120 {"type": "server", "timestamp": "2022-06-24T09:54:22,665Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "removed {{el       asticsearch-master-2}{asQl7UtKRleecTFkByOjfg}{NEjkzLvOQfuGYGWDMlNAWw}{10.42.0.97}{10.42.0.97:9300}{cdfhilmrstw}}, term: 3, version: 439, reason: ApplyCommitRequest{term=3, version=439, sourceNode={elasticsearch-master-0       }{woGWdzCwToKEUS_a66LQGg}{fQrCFCisQnyQ9NJ_dfR2lQ}{10.42.0.98}{10.42.0.98:9300}{cdfhilmrstw}{ml.machine_memory=34359738368, ml.max_open_jobs=512, xpack.installed=true, ml.max_jvm_size=17179869184, transform.node=true}}",        "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   121 {"type": "server", "timestamp": "2022-06-24T09:54:22,726Z", "level": "INFO", "component": "o.e.i.s.IndexShard", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": " [.kibana_7.17.1_001][0       ] primary-replica resync completed with 0 operations", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   122 {"type": "server", "timestamp": "2022-06-24T09:54:23,136Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "updating geoip dat       abases", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   123 {"type": "server", "timestamp": "2022-06-24T09:54:23,136Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "fetching geoip dat       abases overview from [https://geoip.elastic.co/v1/database?elastic_geoip_service_tos=agree]", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ"  }
   124 {"type": "server", "timestamp": "2022-06-24T09:54:33,248Z", "level": "ERROR", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "exception during        geoip databases update", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ" ,
   125 "stacktrace": ["java.net.SocketTimeoutException: Connect timed out",
   126 "at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]",
   127 "at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]",
   128 "at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]",
   129 "at java.net.Socket.connect(Socket.java:633) ~[?:?]",
   130 "at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]",
   131 "at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]",
   132 "at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]",
   133 "at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]",
   134 "at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]",
   135 "at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]",
   136 "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]",
   137 "at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]",
   138 "at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]",
   139 "at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]",
   140 "at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]",
   141 "at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]",
   142 "at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]",
   143 "at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]",
   144 "at org.elasticsearch.ingest.geoip.HttpClient.lambda$get$0(HttpClient.java:55) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   145 "at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]",
   146 "at org.elasticsearch.ingest.geoip.HttpClient.doPrivileged(HttpClient.java:97) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   147 "at org.elasticsearch.ingest.geoip.HttpClient.get(HttpClient.java:49) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   148 "at org.elasticsearch.ingest.geoip.HttpClient.getBytes(HttpClient.java:40) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   149 "at org.elasticsearch.ingest.geoip.GeoIpDownloader.fetchDatabasesOverview(GeoIpDownloader.java:141) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   150 "at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:129) ~[ingest-geoip-7.17.1.jar:7.17.1]",
   151 "at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:266) [ingest-geoip-7.17.1.jar:7.17.1]",
   152 "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:100) [ingest-geoip-7.17.1.jar:7.17.1]",
   153 "at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:46) [ingest-geoip-7.17.1.jar:7.17.1]",
   154 "at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.17.1.jar:7.17.1]",
   155 "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.1.jar:7.17.1]",
      156 "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.1.jar:7.17.1]",
   157 "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
   158 "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
   159 "at java.lang.Thread.run(Thread.java:833) [?:?]"] }
   160 {"type": "server", "timestamp": "2022-06-24T09:57:01,067Z", "level": "WARN", "component": "o.e.i.e.Engine", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": " [fluentd-000008][1] failed        engine [already closed by tragic event on the index writer]", "cluster.uuid": "1DMfzf_YREun8hOKTsk_bg", "node.id": "9e76-rmjTv-WDH83GPwSnQ" ,
   161 "stacktrace": ["org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2022-06-23T16:17:41Z, (lock=NativeFSLock(path=/usr/share/elasticsearch/data/nodes/0/indices/9iOhvTUcSvilrhF       LptUHSw/1/index/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2022-06-23T16:17:41.882277033Z))",
```

We are suspecting an antivirus scan and have disabled these scans.  But, we have to wait until 6-7 days to see if the problem happens again (elasticsearch runs for 6-7 days before experiencing this issue and killing itself)

**Comment by original-brownbear** [comment]
> Underlying file changed by an external force at

This strongly indicates issues with the file system that Elasticsearch is mounted into. This is not an Elasticsearch bug in all likelihood and I would suggest investigating the Kubernetes setup to figured out what's breaking the file locks.
Hope you don't mind if I close here as there's nothing that can be done on our end.

**Comment by beckyjmcdabq** [comment]
It's fine that it is closed.  Just some additional info ... we install Elasticsearch the exact same way on all of our Kubernetes clusters but this is the only cluster where we see this problem.  This cluster is on a different network and due to the cyclical nature of the problem, we assume it is the Antivirus software running on the actual PVs where the lucene index is stored.  Today we completely uninstalled the Antivirus software on that cluster and are going to wait another 6-7 days to see if it resolves the issue.  If so, we can turn antivirus on and configure it not to scan the elasticsearch PVs.
