### ISSUE TITLE
App Search Documents page doesn't render array correctly, only shows first item

### ISSUE THREAD

**Issue by eliezra236** [elastic/elasticsearch#87818]
### Elasticsearch Version

8.2

### Java Version

_bundled_

### OS Version

irrelevant

### Problem Description

On App Search control panel, under Document, where I can see all my indexed documents, arrays are not rendered correctly.

This is how it shows on the page itself.
https://i.imgur.com/LygbVpn.png

Here is the full document, when spectated (clicking the eye icon):
https://i.imgur.com/ddjhFAA.png

As you can see, the colors only shows the first one, unless showing more details.

This is really confusing as I was sure there was a problem with the indexing and that App Search doesn't support arrays.

### Steps to Reproduce

1. Start a new engine
2. Add the following document:
`{
  "id": 1,
  "name": "Metallica T-Shirt",
  "colors": ["Red", "Black"]
}`

3. See the result on the control panel Document page.

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by eliezra236** [comment]
@iverase it's not a user question, there's literally a bug with the way it renders.
See the screenshots I attached, the view literally don't support array field, and it make it look like the field was not indexed correctly.

**Comment by iverase** [comment]
Hi @eliezra236,

Even if this is a bug it seems not related to Elasticsearch but with AppSearch. I kindly recommend you to post your issue in here https://discuss.elastic.co/c/enterprise-search where you should get proper support from the community.
