### ISSUE TITLE
The explanation of the code does not match the results

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch#87848]
At the link  https://www.elastic.co/guide/en/elasticsearch/reference/8.2/runtime-examples.html, there is a such a piece of code:

`PUT my-index-000001/_mappings
{
  "runtime": {
    "http.client_ip": {
      "type": "ip",
      "script": """
        String clientip=grok('%{COMMONAPACHELOG}').extract(doc["message"].value)?.clientip;
        if (clientip != null) emit(clientip); 
      """
    }
  }
}`

The explanation in the text:

` If the pattern doesn’t match (clientip != null), the script just returns the field value without crashing.`

My understanding is that clientip != null, it indicates a match instead of a mismatch.

Thanks

**Comment by lockewritesdocs** [comment]
@nik9000, you and I collaborated on this information together. Did I misinterpret what's happening in the code?

**Comment by kilfoyle** [comment]
Here's a PR to fix this, if anyone would like to take a look:
https://github.com/elastic/elasticsearch/pull/87851
