### ISSUE TITLE
ResourceWatcherService performs IO on main scheduler thread

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#87844]
The `ResourceWatcherService` runs all its scheduled actions on `SAME`:

https://github.com/elastic/elasticsearch/blob/0699c9351f1439e246d408fd6538deafde4087b6/server/src/main/java/org/elasticsearch/watcher/ResourceWatcherService.java#L97-L99

Typically these actions are `FileWatcher` instances which check a file for changes and process the file if changes are detected. We shouldn't be doing this on the main scheduler thread because IO can be quite slow. I saw some instances where some checks were taking a couple of _minutes_ each. I suggest setting up a separate scheduler for this service to avoid delaying other scheduled activity.

I'm labelling this as `:Security/Security` because we seem to use this most heavily in hot-reloading of security config.

**Comment by DaveCTurner** [comment]
To give a sense of the scale of the issue, here's the warnings we see about this today:

<img width="1167" alt="image" src="https://github.com/elastic/elasticsearch/assets/5058284/9fc1f19c-5d19-47b1-91b4-10ef8adbbf93">

@jakelandis could we find some way to make progress here?

**Comment by gwbrown** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/96251.
