### ISSUE TITLE
Docs: local build distributions was output to `build/distribution/local...` not  `distributions/archives`

### ISSUE THREAD

**Issue by wangjie-fourth** [elastic/elasticsearch#87867]
### Elasticsearch Version

latest master

### Java Version

17

### OS Version

windows

### Problem Description

i try build local distributions from latest source code with README. 
when i run `./gradlew localDistro`, local build distributions was output to `build/distribution/local` not  `distributions/archives` as `README`.

### Steps to Reproduce

follow README on [Build from source](https://github.com/elastic/elasticsearch#build-from-source)

**Comment by wangjie-fourth** [comment]
![es_build_result](https://user-images.githubusercontent.com/46479343/174715839-68511742-9708-499b-8950-7e9597fd697d.png)

**Comment by abdonpijpelink** [comment]
`./gradlew localDistro` prints its output location upon completion. The reference to the `distribution/archives` output directory is related to the other build commands. 

The README seems correct to me as-is. Closing.
