### ISSUE TITLE
Data too large ElasticSearch issue along with Readiness probe failed

### ISSUE THREAD

**Issue by halfcipher** [elastic/elasticsearch#87907]
### Elasticsearch Version

latest

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

We have set up an EFK stack for our project and from yesterday kibana seems down. When we initially troubleshooted we have found the following errors:

```Readiness probe failed: Error: Got HTTP code 503 but expected a 200``` & ```Readiness probe failed: Error: Got HTTP code 000 but expected a 200```

When we dig down further we found the same issue with **elasticsearch** as well. along with this we found the following issue with **Data request limit**: 

> FATAL 
> {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent]
> Data too large, data for [indices:admin/template/get] would be
> [1036909172/988.8mb], which is larger than the limitof
> [1020054732/972.7mb], real usage: [1036909056/988.8mb], new bytes
> reserved: [116/116b], usages [request=0/0b, fielddata=420/420b,
> in_flight_requests=67310/65.7kb, model_inference=0/0b,
> eql_sequence=0/0b,
> accounting=110294544/105.1mb]","bytes_wanted":1036909172,"bytes_limit":1020054732,"durability":"PERMANENT"}],"type":"circuit_breaking_exception","reason":"[parent]
> Data too large, data for [indices:admin/template/get] would be
> [1036909172/988.8mb], which is larger than the limit of
> [1020054732/972.7mb], real usage: [1036909056/988.8mb], new bytes
> reserved: [116/116b], usages [request=0/0b, fielddata=420/420b,
> in_flight_requests=67310/65.7kb, model_inference=0/0b,
> eql_sequence=0/0b,
> accounting=110294544/105.1mb]","bytes_wanted":1036909172,"bytes_limit":1020054732,"durability":"PERMANENT"},"status":429}

We have tried changing the REDINESS_PROBE_TIMEOUT, Initial Delay, Timeout, Probe Period, Success Threshold, and Failure Threshold. Also tried increasing the Indicess Breaker limit but it's not reflecting we can see error still taking old limits, tried fixing circuit_breaking_exception by adding ES_JAVA_OPTS values as well.

Nothing seems to be working, any help would be appreciated.
 

### Steps to Reproduce

Try deleting a pod

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
