### ISSUE TITLE
[CI] TestingConventionsPrecommitPluginFuncTest skips convention check if no tests available failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#87913]
It seems all suite is failing in windows.

**Build scan:**
https://gradle-enterprise.elastic.co/s/odbr7rn44bbja/tests/:integTest/org.elasticsearch.gradle.internal.precommit.TestingConventionsPrecommitPluginFuncTest/skips%20convention%20check%20if%20no%20tests%20available

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.precommit.TestingConventionsPrecommitPluginFuncTest&tests.test=skips%20convention%20check%20if%20no%20tests%20available

**Failure excerpt:**
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\jenkins\AppData\Local\Temp\junit5057803447775395944 with arguments [precommit, -Dtest.external=true]

Output:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jenkins\AppData\Local\Temp\junit5057803447775395944\build.gradle' line: 16

* What went wrong:
Could not compile build file 'C:\Users\jenkins\AppData\Local\Temp\junit5057803447775395944\build.gradle'.
> startup failed:
  build file 'C:\Users\jenkins\AppData\Local\Temp\junit5057803447775395944\build.gradle': 16: Unexpected character: '"' @ line 16, column 19.
                 url = "C:\Users\jenkins\AppData\Local\Temp\junit7233216055668629539\local-repo"
                       ^
  
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 81ms

  at org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.precommit.TestingConventionsPrecommitPluginFuncTest.skips convention check if no tests available(TestingConventionsPrecommitPluginFuncTest.groovy:54)

```

**Comment by breskeby** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/88240

**Comment by albertzaharovits** [comment]
https://gradle-enterprise.elastic.co/s/7ux2xnhzycccy
https://gradle-enterprise.elastic.co/s/ecb6ke4oy77rs
https://gradle-enterprise.elastic.co/s/rnvhiihf4uaa2
https://gradle-enterprise.elastic.co/s/nfriqoqxk22xa

**Comment by mark-vieira** [comment]
Probably fallout from the backport. Do you mind taking a look @breskeby?

**Comment by breskeby** [comment]
checking

**Comment by breskeby** [comment]
Should be fixed by this backport: https://github.com/elastic/elasticsearch/pull/88524 I'll keep an eye on this till confirmed

**Comment by breskeby** [comment]
Seems fixed https://gradle-enterprise.elastic.co/scans/tests?search.rootProjectNames=elasticsearch&search.tags=7.17&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.gradle.internal.precommit.TestingConventionsPrecommitPluginFuncTest
