### ISSUE TITLE
_upgrade workflow?

### ISSUE THREAD

**Issue by temal-** [elastic/elasticsearch#8792]
Hi,

I just did an update from 1.3.6 to 1.4.1 on a one node instance (small dataset (~300 indices@1GB each) and single shard per index). Since we started with 1.0.2, I was curious about the "_upgrade" feature.

After reading
> Upgrading is an I/O intensive operation, and is **limited to processing a single shard per node at a time**. It also is not allowed to run at the same time as optimize.

and some tests with one and more indices, I did an:
```
curl -X POST http://localhost:9200/*/_upgrade
```

This killed the node in a matter of minutes because of OutOfMemory exceptions. Nothing serious happened, but I was thinking on how to do this _uprade process with hundreds of indices.
Should I write some $SHELL script to check the status of the upgrade of every index or did I just miss something?

Thanks in advance!

Regards,
Malte

**Comment by rjernst** [comment]
Given the original command shown in this issue, I think the problem would now be fixed with #9639.  The wait_for_completion flag was defaulting to false, and the limiting of optimize never correctly worked when running asynchronously, so this is removed altogether for 2.0 (#9640).
