### ISSUE TITLE
Docs unclear that restoring a feature state also restores all other indices

### ISSUE THREAD

**Issue by rudolf** [elastic/elasticsearch#87957]
Although higher up in the docs we state:

> By default, a restore request attempts to restore all regular indices and
regular data streams in a snapshot.

In [restore-feature-state](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-restore-snapshot.html#restore-feature-state) the documentation only mentions the feature state itself. So I assumed that the example would only restore the feature state, not all other indices too. I think we should update the example to:

```
POST _snapshot/my_repository/my_snapshot_2099.05.06/_restore
{
  "indices": "-*", <1>
  "feature_states": [ "geoip" ]
}
```
<1> Restore only the geoip feature state by excluding all regular indices and data streams

**Comment by romain-chanu** [comment]
Similar to https://github.com/elastic/elasticsearch/issues/88232.

**Comment by abdonpijpelink** [comment]
Addressed in https://github.com/elastic/elasticsearch/pull/90328. Closing.
