### ISSUE TITLE
[DEB, RPM] init script double-daemonizes elasticsearch

### ISSUE THREAD

**Issue by t-lo** [elastic/elasticsearch#8796]
Both the deb and the rpm init script will daemonize elasticsearch - deb by using `start-stop-daemon`, rpm by using `daemon`. Additionally they will _also_ tell the starter script to daemonize itself (again). Since the elasticsearch starter script is well able to daemonize by itself (and correctly report errors if the backgrounded elasticsearch fails to initialize) it would be reasonable to not do a second backgrounding in the init scripts.

**Comment by clintongormley** [comment]
Closing in favour of #12716
