### ISSUE TITLE
failed to get data back using "@timestamp" as epoch_second in range query

### ISSUE THREAD

**Issue by iamorchid** [elastic/elasticsearch#88048]
### Elasticsearch Version

8.2.0

### Java Version

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### OS Version

Linux test 5.14.0+ #4 SMP PREEMPT Tue Sep 7 12:04:46 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Within my data, there is a field named "@timestamp" whose value is epoch second (in index mapping, I model it as "epoch_second"). 
```
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date",
        "format": "epoch_second"
      }
    }
  }
}
```

However, I failed to get my data using range query.  After some investigation, I found that this is casued by the following logic in [DateFieldMapper.java](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java#L554) . Namely, from/to in range query would always be parsed as epoch millis (they are integers). I think this is not correct.

```
            if (forcedDateParser == null) {
                if (lowerTerm instanceof Number || upperTerm instanceof Number) {
                    // force epoch_millis
                    parser = EPOCH_MILLIS_PARSER;
                } else {
                    parser = dateMathParser;
                }
            }
```

### Steps to Reproduce

I think my query is clear enough.

**Comment by ywelsch** [comment]
This is how it's documented (see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#numeric-date). If you want the value to represent an epoch_second, you need to pass it as a String value (e.g. "1656327911") that will be parsed according to the set format.
