### ISSUE TITLE
Java 17 requirement on elasticsearch built as maven package breaks applications that rely on "org.elasticsearch.index.query" or "SearchSourceBuilder" package to function

### ISSUE THREAD

**Issue by Enerccio** [elastic/elasticsearch#88044]
### Elasticsearch Version

8.2.2

### Java Version

_bundled_

### OS Version

doesn't matter

### Problem Description

As elasticsearch is now compiled for java 17 this breaks any java <=17 application that was using elasticsearch as dependency for building queries (such as any application using rest api) because now all classes from `org.elasticsearch.index.query` can't be used and there is no drop-in alternative. Same with `org.elasticsearch.search` package and using `SearchSourceBuilder`. 

### Steps to Reproduce

Have a java 8 project that uses `QueryBuilders`. 

Try to update elasticsearch to version 8 to match server version.

You can't run the code because it's java 17.

**Comment by swallez** [comment]
`QueryBuilders` is part of the High Level Java Client, which has been deprecated and is only available in the 7.x branch.

You can still use HLRC version 7.17 with a 8.x Elasticsearch cluster by [enabling the compatibility mode](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html). You should also consider migrating to the newer Java API client that has been built to remove the dependency to the Elasticsearch server code base (see [migration scenarios](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html)).
