### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by zamazan4ik** [elastic/elasticsearch#88058]
Hi!

I have found a veeeery small typo in the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#traceparent

Here `trade.id` shall be replaced with `trace.id`.

Related PR: https://github.com/elastic/elasticsearch/pull/88056

**Comment by dnhatn** [comment]
Hi @zamazan4ik, I am closing this issue as we will proceed with the PR in https://github.com/elastic/elasticsearch/pull/88056.
