### ISSUE TITLE
Feature request: sorting using the output of multiple script scores

### ISSUE THREAD

**Issue by jayaddison** [elastic/elasticsearch#88086]
### Description

Hello Elasticians :wave: 

As part of planning migration away from using [`function_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html) -- based on a sense from elastic/elasticsearch#42811 that it may be deprecated in future -- I'm looking for alternative query workflows to support search operations that involve a combination of script evaluation and sorting.

**Background**
The specific search use case is [described here](https://github.com/openculinary/api/blob/72075f66cd6fda5b809f85b2ba90150f3feb4984/reciperadar/search/recipes.py#L265-L380).

My explanation of the process: after matching documents are discovered, scoring is performed by evaluating a scoring script on them.  The script emits a value that is a combination of two numeric calculations: a core "rank", and a subsequent "tiebreaker" that provides second-level sorting within groups of equally-ranked documents.

The only reason that `function_score` is used in the code is to [`replace`](https://github.com/openculinary/api/blob/72075f66cd6fda5b809f85b2ba90150f3feb4984/reciperadar/search/recipes.py#L207) the `_score` value on each document with the script's return value.

**Feature Request**
The feature request is to allow _multiple_ scripts to be evaluated against matched documents, and to request sorting based on the output of those.

In other words: the feature would provide migration from a (pseudocode) query of the form:

- `run script {rank+tiebreaker} on each document => replace the {_score} with the {rank+tiebreaker} output => sort based on: {_score desc}`

...to a query of the form:

- `run scripts [{rank}, {tiebreaker}] on each document => sort based on: [{rank desc}, {tiebreaker desc}]`

Where the latter query form does not involve a `function_score` step.

**Other considerations**
- I realize that there could be architectural/design challenges implementing something like this - query request format does not necessarily correspond to query plan representation
- I'm not aware of other users with a similar request/requirement -- I have searched around for any in the issue tracker
- It seems like allowing multiple scripts to be evaluated could introduce potential performance risks (up-to-and-including denial-of-service concerns) -- although to some extent I think that risk already exists for any search appliance where script-eval per result is enabled
- Although it might be a bit strange/awkward, I think I'll open this feature request against both `elasticsearch` and `opensearch` - it's not intended as a competition, I'm not running an academic study, I don't want to waste anyone's time, and I have no particular relationship with either project - I'm just not aware of a better way (currently?) to raise awareness of a feature request that could be relevant to both projects other than duplicating the feature request itself

Please let me know if there's any more information I can add or details that I can clarify.

**Comment by mayya-sharipova** [comment]
@jayaddison Thanks for filing this issue and explaining your use case. 

> I'm not aware of other users with a similar request/requirement 

I think a reason why you have not encountered similar requests is that  this kind problem is usually approached differently. If you have several features, instead of using multiple sort values on them, you try to combine them into a single score using different weights. For example `weight1 * number_of_matched_ingredients + weight2 * recipe_rating`.  
And there are different ways how you find these weights: hand tuning, Learning to Rank, using ML models etc.

**Comment by jayaddison** [comment]
Thanks @mayya-sharipova - my reply here might seem a bit repetitive, so my apologies in advance: I'd like to try to demonstrate some understanding of the weights and combination techniques you mentioned, and then to communicate the remaining concerns I have.

The query currently uses a boosting/weighting approach to make ingredients that appear earlier in the user's query [score more highly](https://github.com/openculinary/api/blob/72075f66cd6fda5b809f85b2ba90150f3feb4984/reciperadar/search/recipes.py#L14) (`tomato, onion, pepper` -> `100, 10, 1`) and also to boost exact-match ingredients [even more than that](https://github.com/openculinary/api/blob/72075f66cd6fda5b809f85b2ba90150f3feb4984/reciperadar/search/recipes.py#L29) (`roma tomatoes`, `yellow onion`, `black pepper` -> `200, 20, 2`).

Summation (value-combination) is used to "multiplex" those into a single per-document `_score`, so a document with one partial match and two exact matches might be scored as `111` + `202` = `313`).  [Count](https://github.com/openculinary/api/blob/72075f66cd6fda5b809f85b2ba90150f3feb4984/reciperadar/search/recipes.py#L64-L67) the `1`s to find partial matches, and count the `3`s to find exact matches -- and then we can use the results to calculate other tiebreaker variables.

It's possible, but it requires some logical acrobatics, and it feels like there could be a simpler way to express the query in code.  Raising term index positions to the power of 10, potentially adding a further multiple of two, and summing them seemed like a clever way to encode the match count when I wrote the code a couple of years ago, but I worry that in 10 years I (or someone attempting to read/modify the code) might not understand.

If it were possible to output multiple values from the per-document `script` stage and then provide instructions about how to use those values during sorting, then I think the client-side query code would become more logical and readable.

More specifically: `found_count`, `exact_found_count` could simplify down to something more like `sum(constant_score(1))` at the document-level, and then the sort script would receive those (as [something like `params`](https://www.elastic.co/guide/en/elasticsearch/painless/7.17/painless-sort-context.html#painless-sort-context)?), calculate the tiebreaker values, and emit the document score for sorting purposes.

That would, I think, allow removal of the multiplexing/demultiplexing of the values, and also removal of the use of `function_score` to replace the document score.  But there would have to be a way to communicate the term match counts down to the sort context.

**Comment by jayaddison** [comment]
> That would, I think, allow removal of the multiplexing/demultiplexing of the values, and also removal of the use of `function_score` to replace the document score. But there would have to be a way to communicate the term match counts down to the sort context.

To clarify a detail about this paragraph: I didn't mean to imply that implementation of a feature like this would allow migration of all cases where `function_query` is currently used; it would allow removing it in the example query environment mentioned, but that likely does not generalize to many other usages.

**Comment by jayaddison** [comment]
I think this can be closed; as far as I know, this feature hasn't been requested by others, and more recently I've begun to think that it may be possible to use runtime fields (v7.11+) to achieve some/all of the use-case.  Thank you @mayya-sharipova for your time responding to this request.
