### ISSUE TITLE
[CI] Jar hell on fips compatibility matrix checks (ingest-attachment)

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#88118]
### CI Link

https://gradle-enterprise.elastic.co/s/luobrp6alugn2

### Repro line

there is no repro line

### Does it reproduce?

Didn't try

### Applicable branches

8.4

### Failure excerpt

The build reports the following:

```
 Caused by: java.lang.IllegalStateException: jar hell!
class: org.bouncycastle.LICENSE
jar1: /dev/shm/elastic+elasticsearch+main+periodic+java-fips-matrix/docs/build/testclusters/yamlRestTest-0/distro/8.4.0-DEFAULT/modules/ingest-attachment/bcprov-jdk15on-1.64.jar
jar2: /dev/shm/elastic+elasticsearch+main+periodic+java-fips-matrix/docs/build/testclusters/yamlRestTest-0/distro/8.4.0-DEFAULT/lib/bc-fips-1.0.2.jar
```

The failure could be related to a recent refactoring of `ingest-attachment` plugin (see [this](https://github.com/elastic/elasticsearch/commit/eed8da3919682243f35a09dbd852795db58c2ea5) )

@rjernst you probably have more context.

**Comment by rjernst** [comment]
Bouncy castle was removed as a dependency of ingest-attachment, so this should no longer be an issue.
