### ISSUE TITLE
can not find accounts.json in the official documentation

### ISSUE THREAD

**Issue by wangjie-fourth** [elastic/elasticsearch#88146]
### Elasticsearch Version

7.5.2

### Java Version

java11

### OS Version

windows

### Problem Description

can not find accounts.json in [the official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/getting-started-index.html#getting-started-batch-processing).
![2](https://user-images.githubusercontent.com/46479343/176359489-9eb207f0-beb2-4f6e-98bd-3a29e4841efb.png)

### Steps to Reproduce

see above

**Comment by chen-ni** [comment]
The link is broken.

It should be this link: https://github.com/elastic/elasticsearch/blob/7.5/docs/src/test/resources/accounts.json
