### ISSUE TITLE
Getting error while running elasticsearch 8.3.0

### ISSUE THREAD

**Issue by infosecayush** [elastic/elasticsearch#88157]
`#systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
     Loaded: loaded (/etc/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-06-29 19:57:07 IST; 10min ago
       Docs: https://www.elastic.co
    Process: 1396 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
   Main PID: 1396 (code=exited, status=1/FAILURE)
        CPU: 3.346s

Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:744)
Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceFirstEntry.produce(ParserImpl.java:732)
Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:176)
Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:403)
Jun 29 19:57:07 Windows systemd-entrypoint[1396]:         ... 11 more
Jun 29 19:57:07 Windows systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 19:57:07 Windows systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Jun 29 19:57:07 Windows systemd[1]: Failed to start Elasticsearch.
Jun 29 19:57:07 Windows systemd[1]: elasticsearch.service: Consumed 3.346s CPU time.`

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
