### ISSUE TITLE
Shingles don't get properly filtered in aggregations

### ISSUE THREAD

**Issue by KPGDL** [elastic/elasticsearch#88152]
### Elasticsearch Version

7.16.3

### Java Version

_bundled_

### OS Version

Ubuntu

### Problem Description

When applying wildcard filter on shingles field I'm still getting bucket keys that not match the filter.

### Steps to Reproduce

```
"aggregations": {
    "test": {
      "filter": {
        "wildcard": {
          "name.shingles": {
            "value": "*red*"
          }
        }
      },
      "aggs": {
        "shingles": {
          "terms": {
            "field": "name.shingles",
            "size": 3
          }
        }
      }
    }
  }
```

Results (expectation is to have only first bucket as it contains "red"):

```
 "aggregations" : {
    "test" : {
      "doc_count" : 7,
      "shingles" : {
        "doc_count_error_upper_bound" : 0,
        "sum_other_doc_count" : 57,
        "buckets" : [
          {
            "key" : "turning red",
            "doc_count" : 3
          },
          {
            "key" : "aces of",
            "doc_count" : 2
          },
          {
            "key" : "aces of the",
            "doc_count" : 2
          }
        ]
      }
    }
```

**Comment by nik9000** [comment]
> When applying wildcard filter on shingles field I'm still getting bucket keys that not match the filter.

The `filter` aggregation filters the documents that downstream aggregation see. It doesn't filter the value fed into that aggregation. So if you only want keys that match `*red*` you'll want to [filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_4) the values. It's certainly possible you've hit a bug that I'm not seeing, but I don't *think* so.

I'm going to close this issue. We won't change the semantics of the `filter` aggregation. But if you are seeing different behavior than what I described please reopen this issue with instructions that create a test index including the mappings and the documents. This is the kind of thing where we'd have to be pretty specific.
