### ISSUE TITLE
cURL method does not work for api_key

### ISSUE THREAD

**Issue by vicosurge** [elastic/elasticsearch#88195]
### Elasticsearch Version

8.2.3

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

Linux debian-11-elastic 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux

### Problem Description

For testing purposes, I was attempting to create a key through the API endpoint for /_security/api_key, this, in turn, resulted in a series of messages which made me round down the request to the minimum requirements, but I could not make it work.

If I copy the cURL request directly from dev tools, which is where this works without issue, and run it through the terminal, I get the same error as before. I am a bit confused as to why this works directly on the dev tools page but not through cURL.

### Steps to Reproduce

Use curl to run the following:

curl -k -XPOST "https://<my_server>:9200/_security/api_key" \
-H "Authorization: ApiKey <my_api_key>" \
-H 'Content-Type: application/json' -d'
{
  "name": "test",
  "expiration": "30d",
  "role_descriptors": {}
}'

The result is this:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"creating derived api keys requires an explicit role descriptor that is empty (has no privileges)"}],"type":"illegal_argument_exception","reason":"creating derived api keys requires an explicit role descriptor that is empty (has no privileges)"},"status":400}

**Comment by tvernum** [comment]
Hi, thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are better suited to these sorts of troubleshooting and problem diagnosis conversations.

Before opening a topic on the forum, I recommend that you check the [Create API Key docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) and read through the first `IMPORTANT` section, and the `NOTE` that it links to.
The difference between your Dev Console example and your cURL example is that your curl command line is using an API key for authentication, which Dev Console would not be doing.
  
There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
