### ISSUE TITLE
Elasticsearch 7.17.x Docker image does not declare an explicit non-root user

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#88218]
@mark-vieira @pugnascotia The Elasticsearch image failed the red hat scan, and so cannot be published.

We were not able to see it before the day of the release because of issues with the Red Hat API/workflow.
The goal is now to make sure we can fix it before 7.17.6. I do not think we need to move 7.17.6 earlier because the security issue that led to 7.17.6 was not related to Elasticsearch. cc @elastic/release-eng 

-----

Here is the report from the Red Hat system

```
Checking if container runs as the root user because a container that does not specify a non-root user will fail the automatic certification, and will be subject to a manual review before the container can be approved for publication

Help
Check RunAsNonRoot encountered an error. Please review the preflight.log file for more information.

Suggestion
Indicate a specific USER in the dockerfile or containerfile

Knowledge base
https://access.redhat.com/documentation/en-us/red_hat_openshift_certification/4.9/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction
```
<img width="1011" alt="Screen Shot 2022-06-30 at 10 14 50 AM" src="https://user-images.githubusercontent.com/501525/176700980-000d2c12-f14a-47d6-aa93-50e81267c233.png">

<img width="1011" alt="Screen Shot 2022-06-30 at 10 14 50 AM" src="https://user-images.githubusercontent.com/501525/176701018-315feceb-88d2-4fb8-8390-1d7941c13009.png">

_Originally posted by @mgreau in https://github.com/elastic/dev/issues/2052#issuecomment-1171281509_

**Comment by pugnascotia** [comment]
You could make the argument that switching the user is a breaking change, which is why we didn't do it across the board in `7.x`. I'm confident we would break users' existing workflows for e.g. adding plugins to the base image. We could change the user just for UBI, which would address this specific problem with the scans?

**Comment by mark-vieira** [comment]
> We could change the user just for UBI, which would address this specific problem with the scans?

@bytebilly what are your thoughts here?

**Comment by bytebilly** [comment]
If I get it correctly, we cannot get our UBI out without that change.
Changing the UBI is the minimum change possible, so I'd suggest go with that and avoid introducing other changes in the standard image.

**Comment by mark-vieira** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/88262.
