### ISSUE TITLE
why first query was very slow

### ISSUE THREAD

**Issue by cookiejoo** [elastic/elasticsearch#88212]
### Elasticsearch Version

7.13.2

### Java Version

1.8.2xx

### OS Version

linux 7

### Problem Description

Under a large amount of data, my first query was very slow, but every subsequent query was very fast?

### Steps to Reproduce

Under a large amount of data, my first query was very slow, but every subsequent query was very fast?

**Comment by zekaifeng** [comment]
Elasticsearch will make full use of the operating system cache. The first cache penetration will index the disk. After the cache, subsequent operations will hit the cache first.

**Comment by cookiejoo** [comment]
> 

But after 10 minutes, the query is similar. The first query is slow

**Comment by zekaifeng** [comment]
> > 
> 
> But after 10 minutes, the query is similar. The first query is slow

Are there any other operations in the process? The cache will be evicted.

**Comment by cookiejoo** [comment]
> > > 
> > 
> > 
> > But after 10 minutes, the query is similar. The first query is slow
> 
> Are there any other operations in the process? The cache will be evicted.

Yes, there is no query operation during this period.

**Comment by pugnascotia** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
