### ISSUE TITLE
An error ocurred while migrating system indices for kibana: resource_already_exists_exception

### ISSUE THREAD

**Issue by romain-chanu** [elastic/elasticsearch#88233]
### Elasticsearch Version

7.17.3

### Java Version

_bundled_

### OS Version

Red Hat Enterprise Linux (3.10.0-1160.36.2.el7.x86_64)

### 1. Problem

We have observed this issue in the field. 

1) User was preparing to upgrade from version 7.17.3 to version 8.2.2. 

2) When using the Kibana Upgrade Assistant to migrate the system indices, the user observed the following error message: 

`An error ocurred while migrating system indices for kibana: resource_already_exists_exception`

Note: under the hood, `migrate system indices` = [Feature Migrations API](https://www.elastic.co/guide/en/elasticsearch/reference/current/feature-migration-api.html).

3) While this error message is rather cryptic (which resource already exists?), we identified that:

a) a bunch of system indices created in version 6 were still present in the cluster: 
- `.logstash, .security-6, .triggered_watches, .kibana_1, .watches`

b) There was an index named `.kibana_1-reindexed-for-8` as well. 

Based on these two points, we concluded that the migration of system indices never completed. 

4) We worked around the situation by:

a) Deleting index `.kibana_1-reindexed-for-8` - this index already existed and was the cause of the `resource_already_exists_exception` message.

b) Retrying the migration of system indices via the Kibana Upgrade Assistant.

### 2. Suggestions

a) The Feature Migrations API should call out exactly what specific existing indices are preventing the migration. In the above error message, there is no index name (but we know it was something related to Kibana indices).

b) Perhaps, we should have a retry mechanism in case something goes wrong during the migration of system indices?  To be brainstormed.

### Steps to Reproduce

We have not been able to reproduce this issue.

### Logs (if relevant)

No logs were collected.

**Comment by arpadkiraly** [comment]
I'm going to close this issue for now as it has been open for a while, it has no reproduction and it does not contain sufficient information to investigate. Feel free to reopen if you can provide more specifics and a reproduction.
