### ISSUE TITLE
Write index metadata on data nodes where shards allocated

### ISSUE THREAD

**Issue by bobpoekert** [elastic/elasticsearch#8823]
If the master node thinks that an index does not exist, and another node thinks that it does, the conflict is currently resolved by having the node that has the index delete it. This can easily result in sudden unexpected data loss. The correct behavior would be for the conflict to be resolved by both nodes accepting the state of the node that thinks that the index exists.

**Comment by mkliu** [comment]
+1111
This bug really burnt me! We had multiple master node, but there was one time all master nodes are down, so I promote one data node as master node. And all data are gone! It freaked the hell out of me. And because people are still ingesting data, the data are overwritten. By the time I realize what's happening, it's already too late, we lost lots of data...

**Comment by polgl** [comment]
Can the deletion be delayed for a longer period by setting a high value for `gateway.local.dangling_timeout` (couple of days maybe?)?

**Comment by s1monw** [comment]
@polgl we remove the deleting and always import now since https://github.com/elasticsearch/elasticsearch/pull/10016 is pushed to 2.0

**Comment by polgl** [comment]
I'm running 1.4 and can not update now, so i would prefer to change the settings and have more time to react.

**Comment by s1monw** [comment]
@polgl you can modify the settings yourself and just to import always?

**Comment by polgl** [comment]
Hi, I did some tests and it seems like our cluster does not show this behavior.
We have a single dedicated master node, if this node does not have an index in the meta data / cluster state. nothing happens. The data nodes don't delete any files (the dangling indices part in the code is not executed). That sounds ok, I can live with that.

Thanks for you help

**Comment by saurabh24292** [comment]
ES Version 2.2

Previous state - A cluster with 6 nodes (3 Master cum data nodes, 3 client nodes).
Index has data for two months (1st April 2016 to 31st May 2016.) Actually, everyday, previous day's data is added and two months old data is deleted.
I restarted the cluster. All of a sudden, 90% of data for the date range 5th May 2016 to 31st May 2016 is gone (average record for these days goes down from 100000 per day to 10000 per day) and, surprisingly, deleted data fro date range 5th March 2016 to 31st March 2016 reappears.

What's the problem?

**Comment by saurabh24292** [comment]
correction - version is 2.1.1

**Comment by bleskes** [comment]
@saurabh24292 I'm not sure what your problem is, but maybe you can ask on discuss.elastic.co? if we figure out it's related to this issue or is cause by something other problem we can re-open this or (more likely) open a new one
