### ISSUE TITLE
'?' matching in index name wildcard patterns

### ISSUE THREAD

**Issue by rashidkpc** [elastic/elasticsearch#8824]
Currently `*` is supported for wildcards in index names, eg: `http://localhost:9200/users-*/_mapping`. However there are situations were `*` may be overly broad. To solve this `?` could be made available so that we can match `users-2014` and `users-2013` with `users-????` without matching `users-disabled-2012`

**Comment by clintongormley** [comment]
I think this requirement has been better addressed by index date math https://github.com/elastic/elasticsearch/pull/12209 so I'm going to close
