### ISSUE TITLE
[GEO] Add TopoJSON support to geo_shape parsing

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#8825]
GeoJSON is currently the only supported format for geo_shape mapping.  This feature will add support for the TopoJSON specification to geo_shape mapping.  No change will be made to the mapping.  It will simply add the arc element to the existing ShapeParser.  An example of a topojson formatted GeometryCollection geo_shape is as follows:

``` java
{
    "location" : {
      "type" : "GeometryCollection",
      "geometries": [
        {
          "type": "Point",
          "properties": {
            "Name": "Point"
          },
          "coordinates": [-96.422, 32.963]
        },
        {
          "type": "LineString",
          "properties": {
            "Name": "LineString",
            "prop1": 0
          },
          "arcs": [0]
        },
        {
          "type": "Polygon",
          "properties": {
            "Name": "Polygon",
            "prop1": {
              "this": "that"
            }
          },
          "arcs": [[0, 1]]
        }
      ],
      "arcs": [
        [[-96.322, 32.994], [-96.322, 32.963], [-96.422, 32.963], [-96.422, 32.994] ],
        [[-96.522, 32.963], [-96.522, 32.994]]
      ]
    }
}
```

The example geovisualization can be found at https://gist.github.com/nknize/f504f855f536792e96a9

**Comment by juanpujol** [comment]
No news on this issue yet? Thanks.

**Comment by amogh-jrules** [comment]
Is this issue still available?

**Comment by imotov** [comment]
@nknize is this still something we want to do?

**Comment by wchaparro** [comment]
after team discussion, closing as won't do.
