### ISSUE TITLE
`eql_sequence` circuit breaker sometimes has negative `used` value

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#88300]
Seen in several production clusters running 8.3 (thanks to the changes in #87881) but this also explains #86059 in earlier versions:

    [instance-0000000011] negative value in circuit breaker: [eql_sequence,limit=8589934592/8gb,estimated=-7961288

My guess is that somehow this circuit breaker is releasing bytes it didn't already hold. Seems pretty rare, and not covered by tests since it would trip assertions there.

**Comment by luigidellaquila** [comment]
@iverase yes, it seems a good candidate, but it's not the only possible reason. 
TBH I had to check the implementation of `addEstimateBytesAndMaybeBreak()` to understand if the estimated bytes were added anyway, even in case of failure. The `And` in the method name made me think to "do both", ie. add the estimate and then, in case, break. For the record, it's not the case.

I'm also investigating another possible inaccuracy in this memory calculation; I'll keep you updated
