### ISSUE TITLE
_terms_enum returns terms even after documents removal

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch#88317]
### Elasticsearch Version

7.17.3

### Java Version

_bundled_

### OS Version

Ubuntu 18.04

### Problem Description

The `_terms_enum_ API returns terms even after documents containing the terms are deleted from the index. Index was refreshed and flushed.

### Steps to Reproduce

The below Kibana script can be used to reproduce the issue.
You'll notice I'm using `?refresh` in the `_bulk` call and in the `_delete_by_query` call, but refreshing manually afterwards, just to be sure. I'm also flushing the index, though I'm unsure it should be required.

```
DELETE /testing

PUT /testing
{
  "mappings": {
    "properties": {
      "id": {
        "type": "keyword"
      }
    }
  }
}

PUT /testing/_bulk?refresh
{ "index": {} }
{ "id": "id1" }
{ "index": {} }
{ "id": "id2" }

POST /testing/_delete_by_query?q=*&refresh

POST /testing/_refresh

POST /testing/_flush

POST /testing/_terms_enum
{
  "field": "id"
}
```

The last call returns
```
 {
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "terms" : [
    "id1",
    "id2"
  ],
  "complete" : true
}
```

Thanks in advance !

Cheers,
David

### Logs (if relevant)

N/A

**Comment by nik9000** [comment]
The API was designed to do exactly this but I can't see the docs mentioning it.

**Comment by ddolcimascolo** [comment]
Hi @nik9000

This looks wrong to me. The docs says this API is used to discover terms _in_ the index, but as the index has no documents it has no terms... Or am I missing a point?

If for instance I run a `terms` agg on the field right after the `_delete_by_query` I get no buckets.
Also indexing a new document kind-of "resets" the terms and `_terms_enum` correctly returns a single term (the one from the new document).

Cheers,
David

**Comment by javanna** [comment]
This is a trade-off of the terms enum API. It's implemented to return fast term suggestions, and to do that, it won't honour documents deletions. Those terms will no longer be returned after once a merge operation has effectively removed deleted documents. We will work on documenting this.

**Comment by ddolcimascolo** [comment]
Thx @javanna for your confirmation. Yeah I suppose documenting this behavior would be a nice addition.

Cheers,
David
