### ISSUE TITLE
Custom Rescorer That Returns a TopDocs With Zero ScoreDocs Causes ArrayIndexOutOfBoundsException Within RescorePhase

### ISSUE THREAD

**Issue by nselvitelli** [elastic/elasticsearch#88325]
I have a custom rescorer that filters out documents below a certain threshold. If all documents within the rescorer have a score below the threshold, an empty `TopDocs` is returned. When an empty TopDocs is returned, `RescorePhase` throws an `ArrayIndexOutOfBoundsException` as the code directly references `topDocs.scoreDocs[0].score` without checking the size of the TopDocs.

Empty TopDocs: `new TopDocs(new new TotalHits(0, TotalHits.Relation.EQUAL_TO), new ScoreDocs[0]);`

The bug appears to have been first introduced in **v7.0.0-alpha1** and has been confirmed to appear on master to this day. The commit responsible can be found in the [Upgrade to a Lucene 8 snapshot](https://github.com/elastic/elasticsearch/commit/7ad71f906a9608e1c168358624f4b0a39b240296) commit (PR #88284). In the linked commit, you can see that the method signature for `context.queryResult().topDocs(...)` changed, which inadvertently requires the TopDocs to not be empty at this stage.

A fix for this bug could be to check the size of the TopDocs returned after running through all rescorers.

**Comment by javanna** [comment]
I see the problem in RescorePhase, though I am wondering if excluding documents is something that should be supported as part of the rescore phase. Even before the change that broke your plugin we had an assertion in place that was accessing scoreDocs without checking the size, which would break if you run with assertions enabled. The [rescore docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/filter-search-results.html#query-rescorer) seem to confirm that what the rescore phase should do is tweak the score and reorder the top-K results. I would not expect hits to be discarded following a rescore. The [search request](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html) does support a min_score parameter though, would that help in your situation?

**Comment by nselvitelli** [comment]
The search request parameter affects documents after the first pass, right? We need functionality that can filter out documents during or after the rescore period. Is there another way for a plugin to incorporate this functionality?

**Comment by javanna** [comment]
Correct, min_score filters documents out before the rescore phase. I had understood that all that your rescorer does is filtering documents out, in which case it would not need to be a rescorer in the first place. I do not see a way to filter out documents based on how the rescorer scored them. @jpountz do you have an opinion on whether this is something that should be supported?

**Comment by nselvitelli** [comment]
The idea is that this rescorer could be used with multiple other rescorers, e.g., query a name, dob, address, and rescore based on the first name, then filter out all docs with a score below 0.8.

**Comment by javanna** [comment]
We have no plans to allow dropping documents from the rescore phase. Closing.
