### ISSUE TITLE
Improve coverage of aggregations by circuit breakers

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#88373]
Our recent discussions about supportability identified that improving the coverage of aggregations by the circuit breaker framework would help a significant proportion of users help themselves without needing to escalate questions to the support or development teams. We did not go into much depth on what that might mean in practice, but I'm opening this issue to record the need for further discussions in this area. Feel free to take this issue forwards as you see fit, for instance by filling it out into a full meta-issue or by closing it in favour of some other more specific action items.

**Comment by wchaparro** [comment]
Discussed, we created a [meta issue](https://github.com/elastic/elasticsearch/issues/89437) to address this area, closing in favor of that issue.
