### ISSUE TITLE
Provide PUT and/or PATCH request to update meta engine

### ISSUE THREAD

**Issue by crystalcleardesigns** [elastic/elasticsearch#88407]
### Description

Hi there,

Using meta engines within App Search, it doesn't seem possible to switch from one source to another within the same API call. In order to do this right now you need one API call to remove the current source, and one API call to add the new source.

This has issues as depending on what order these calls are done, any searches made in between the two may result in either more results (if there are hits from both sources by doing the add first), or no results (if no source is currently present by doing the remove first).

I'm not sure if there's a reason why it's not possible, but ideally i'd like to have an end point which can just update the source (and possibly other fields?) for a meta engine, something like: 

```
PUT /engines/123
{
  "type": "meta",
  "source_engines": [
    'A', 'B',
  ]
}
```

More background / discussion here: https://discuss.elastic.co/t/can-you-specify-default-source-for-a-meta-engine/308038/7

Thanks!

**Comment by DaveCTurner** [comment]
Thanks @crystalcleardesigns. This repo is for tracking work on Elasticsearch itself, not App Search, and there's nothing for the Elasticsearch dev team to do here so I am closing this. We've copied your idea to a private repo that tracks App Search work but unfortunately you won't be able to see that. If you want further info about this item in future please contact the support team linking this ticket and they'll be able to find the private version from here.
