### ISSUE TITLE
Need explanation of how to run tests in rest-api-spec test guide

### ISSUE THREAD

**Issue by chen-ni** [elastic/elasticsearch#88406]
[The rest-api-spec tests guide](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/README.asciidoc) is confusing because after all the explanations of the test file structure, it doesn't tell us how to actually _RUN_ an individual test or a test suite.

Luckily for me, I happened to run into [this comment](https://github.com/elastic/elasticsearch/issues/83957#issuecomment-1121014066) that explains how to run such a test.

It would be better if we could add an explanation of how to run tests (or a link to some doc located elsewhere) to the guide. It won't be much work but would save a lot of time for the developers.

I'd be glad to create a PR for this.

**Comment by mark-vieira** [comment]
We have a whole separate README specifically about test execution. It might be as simple as just linking to [this section](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#testing-the-rest-layer) from the rest-api-spec guide.

**Comment by chen-ni** [comment]
@mark-vieira Thanks, I'll create a PR adding the link :)
