### ISSUE TITLE
Description about the detailed param of _tasks api is not accurate

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#88469]
### Elasticsearch Version

8.3

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

NA

### Problem Description

Please refer the para in the [get_more_information_about_tasks](https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html#_get_more_information_about_tasks) as shown below

```
You can also use the detailed request parameter to get more information about the running tasks. This is useful for telling one task from another but is more costly to execute. For example, fetching all searches using the detailed request parameter:
```

Here `This is useful for telling one task from another but is more costly to execute` seems to be incomplete, would be better if we can add a more meaningful sentence.

### Steps to Reproduce

Documentation issue and provided in the Problem Description

### Logs (if relevant)

NA

**Comment by DaveCTurner** [comment]
Yes it means you can use the information to distinguish tasks from each other. It's acceptable English as written (see e.g. https://en.wiktionary.org/wiki/tell, sense 6: "To discern, notice, identify or distinguish."). The information you receive depends on the task, but docs immediately give an example.

**Comment by amitmbm** [comment]
@DaveCTurner Thanks for the link, and explaining what the meaning of `tell` in the given context, while I agree, its a proper english but it could be improved  if we mention it explicitly like `This is useful for distinguish one task from another task`, this would be certainly useful for community users who are not native english speakers.

**Comment by DaveCTurner** [comment]
:+1: makes sense, I think we can do that.

**Comment by amitmbm** [comment]
Thanks @DaveCTurner , will raise a PR soon to add the text as `This is useful for distinguish one task from another task`.

**Comment by idegtiarenko** [comment]
Closed via: https://github.com/elastic/elasticsearch/pull/88493
