### ISSUE TITLE
[Terms] Allow multiple regex patterns into include/exclude

### ISSUE THREAD

**Issue by stratoula** [elastic/elasticsearch#88532]
### Description

When you want to use the include/exclude filtering feature on the terms aggregation you can either give an array of strings (exact match) or a regex pattern as a string.

This means that:
- Passing the pattern as an array doesn't work
- User can't have something like `['J.*', 'E.*', term1, term2]` (a combination of terms and regexes)

We want to support this feature in [Lens](https://github.com/elastic/kibana/pull/136179). In order to help the users understand how this works we are introducing a UI like this
<img width="430" alt="image" src="https://user-images.githubusercontent.com/17003240/178931714-e31fab4f-041f-4c1a-bd08-4eb1012dfd37.png">

The user can start selecting terms from a multi-select dropdown or open the switch and add a regex. We thing that it would be more powerful if we could combine exact matches and patterns.

**Comment by not-napoleon** [comment]
I think you can just compose a multi-branch regular expression to get this behavior?  something like `([JE].*)|term1|term2` should do exactly what you describe.  That said, it is possible to add this feature on the server side, although it does require us to do some careful thinking about the precedence rules.  What use cases would that enable?

This was last discussed two years ago on https://github.com/elastic/elasticsearch/pull/63325

**Comment by stratoula** [comment]
I see, I missed that on the documentation tbh. I think we can work like that. I am closing it :)

**Comment by Aassifh** [comment]
Multi branch regex has its down sides in terms of perfomance issues, i hope that we can have the combination of both (regex and exact match array) some day !
