### ISSUE TITLE
[DOCS] kill $(cat pid) spurious?

### ISSUE THREAD

**Issue by desnij** [elastic/elasticsearch#88558]
In line 19 of the [shut down node](https://github.com/elastic/elasticsearch/blame/master/docs/reference/upgrade/shut-down-node.asciidoc#L19) doc, it suggests to type `kill $(cat pid)` to stop a daemon process, but this would only work if the user had a file containing the pid, called `pid` in the working directory.  Unfortunately each linux distribution  has its own location to place pid files. So this is not really easy to describe for a wide audience. Perhaps, just state users must confirm the process is no longer running.  

Alternatives:
both have issues if run on a system that is running elastic in docker containers
1. `killall elasticsearch` also requires killall be installed
1. `kill $(pgrep elasticsearch)` also requires pgrep be installed

**Comment by desnij** [comment]
Although it has moved here, this doc is still incorrect.

1. [on the web](https://www.elastic.co/guide/en/elastic-stack/master/upgrading-elasticsearch.html)
1. [source doc](https://github.com/elastic/elasticsearch/blob/main/docs/reference/upgrade/shut-down-node.asciidoc)

thanks for the update abdon
 

Sorry 20 minutes to fix one line of  code ( all the requirements to be a contributor... totally tl;dr for such a small fix) ,  after all this time... https://github.com/elastic/elasticsearch/pull/92164
someone else can copy that code and add it

thanks guys PLEASE take my code and fix this, I dont have the time to become a contributor

**Comment by amyjtechwriter** [comment]
Closing this ticket as a fix has been merged https://github.com/elastic/stack-docs/pull/2282. Thanks everyone!
