### ISSUE TITLE
Same query dsl with different parameter result in different execution order and huge cost

### ISSUE THREAD

**Issue by win0909** [elastic/elasticsearch#88572]
### Elasticsearch Version

7.13.4

### Java Version

_bundled_

### OS Version

centos

### Problem Description

query dsl 1
```
POST d2d_test/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "user_id": "1"
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```

profile
![image](https://user-images.githubusercontent.com/25101356/179342479-924a9e10-f1e2-4635-a8ba-0455c2d0646c.png)

query dsl 2
```
POST d2d_test/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "user_id": "-1"
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```
profile
![image](https://user-images.githubusercontent.com/25101356/179342511-31a8dcec-7d04-41fe-9ad7-f841ce393211.png)

The only difference between these two queries is the value of the field  `use_id`.
`user_id : 1` is in test data set while `user_id : -1` is not in test data set. 

Why `ScriptQuery` execute before `TermQuery` in query dsl 1? 
Is there any way to change this execution order?
Any help would be appreciated!

### Steps to Reproduce

the mapping:
```
PUT d2d_test
{
  "mappings": {
    "properties": {
      "user_id": {
        "type": "keyword"
      },
      "full_address": {
        "type": "keyword"
      }
    }
  }
}
```

the test data:
```
POST d2d_test/_bulk
{"index":{"_id":"1"}}
{"user_id":1,"full_address":"test_1"}
{"index":{"_id":"2"}}
{"user_id":1,"full_address":"test_2"}
{"index":{"_id":"3"}}
{"user_id":1,"full_address":"test_3"}
```

the dsl 1:
```
POST d2d_test/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "user_id": "1"
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```

the dsl 2:
```
POST d2d_test/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "user_id": "-1"
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```

**Comment by win0909** [comment]
Use `ids` query also have the same problem.
```
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "ids": {
            "values": [
              "1"
            ]
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```
![image](https://user-images.githubusercontent.com/25101356/179343658-caadae71-5bfe-43eb-873d-acd599cabcf5.png)


```
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "ids": {
            "values": [
              "-1"
            ]
          }
        },
        {
          "script": {
            "script": {
              "lang": "painless",
              "source": "doc['full_address'].value.contains('123')"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```
![image](https://user-images.githubusercontent.com/25101356/179343643-35d8c187-9da7-4b6b-88b3-4d6322231213.png)

**Comment by win0909** [comment]
Use `ids` query and `wildcard` query also has the same problem.
```
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
                {
          "ids": {
            "values": [
              "1"
            ]
          }
        },
        {
          "wildcard": {
            "full_address": {
              "wildcard": "*123*"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```
![image](https://user-images.githubusercontent.com/25101356/179343823-56958f39-1f8f-4a29-adbd-cf6ebbff247b.png)

```
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
                {
          "ids": {
            "values": [
              "-1"
            ]
          }
        },
        {
          "wildcard": {
            "full_address": {
              "wildcard": "*123*"
            }
          }
        }
      ]
    }
  },
  "_source": false
}
```
![image](https://user-images.githubusercontent.com/25101356/179343844-b1844cf3-0e97-4f4a-a6bd-a752bc25cfdb.png)

**Comment by jtibshirani** [comment]
@win0909 could you please attach the full profile output (not just screenshots)? I've looked into the code and don't see evidence of a bug. Also, what is the size of the dataset, and how many docshave `user_id: 1`?

Overall I'm not sure if we can really draw a strong conclusion from 34 microseconds vs. 119 microseconds, especially when the first query does not match any documents at all and never needs to execute the script.

**Comment by jtibshirani** [comment]
@win0909 could you please attach the full profile output (not just screenshots)? I've looked into the code and don't see evidence of a bug. Also, what is the size of the dataset, and how many docs have `user_id: 1`?

Overall I'm not sure if we can really draw a strong conclusion from 34 microseconds vs. 119 microseconds.

**Comment by win0909** [comment]
The test data set is shown above.

**Comment by win0909** [comment]
> 

The test data set is shown above: **`Steps to Reproduce`**
There are 3 test docs in total, and 3 docs have `user_id: 1`.

**Comment by win0909** [comment]
> @win0909 could you please attach the full profile output (not just screenshots)? I've looked into the code and don't see evidence of a bug. Also, what is the size of the dataset, and how many docs have `user_id: 1`?
> 
> Overall I'm not sure if we can really draw a strong conclusion from 34 microseconds vs. 119 microseconds.

The test data set is shown above: **`Steps to Reproduce`**
There are 3 test docs in total, and 3 docs have `user_id: 1`.

**Comment by jtibshirani** [comment]
Oh okay, I didn't understand that is the full dataset. I don't think we can draw a real conclusion about performance from such a small dataset. From the behavior you're seeing, I don't see evidence of a bug or issue.

If you end up running at higher scale and see surprising performance or profile output, then feel free to open a Discuss issue (https://discuss.elastic.co/) and tag me. We prefer to debug issues there as opposed to GitHub, which is for bug reports/ feature requests.
