### ISSUE TITLE
An unreleased file exists in tmp

### ISSUE THREAD

**Issue by mazhiyuan-aiit** [elastic/elasticsearch#88580]
### Elasticsearch Version

6.8.23 and 7.16.3

### Java Version

_bundled_

### OS Version

docker Elasticsearch6.8.23 and Elasticsearch7.16.3

### Problem Description

**issue:**
When I run a Elasticsearch6.8.23 container ,I found some files is deleted status in host .
as follow：
/tmp/elasticsearch.N9lMSyFv/controller_log_1 (deleted)
When I run a Elasticsearch7.16.3 container ,I found some files is deleted status in host .
as follow：
java      10949 11215 GC\x20Thr   secur1ty    0r      REG               0,43           1    2266679 /tmp/sh-thd.FsfTKR (deleted)

I wanted to know why this problem exists and under what conditions it occurs. Looking forward to your reply.

### Steps to Reproduce

1. run a container 
`docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" 10.11.105.11:8181/elasticsearch/elasticsearch:6.8.23`
2. executive command lsof 
`lsof | grep deleted`
result：
/tmp/elasticsearch.N9lMSyFv/controller_log_1 (deleted)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
