### ISSUE TITLE
logstash can not connect elasticsearch

### ISSUE THREAD

**Issue by Js0nMar2** [elastic/elasticsearch#88591]
### Elasticsearch Version

8.3.2

### Java Version

_bundled_

### OS Version

centos 8

### Problem Description

When I use logstash to integrate the elasticsearch cluster, the configuration of logstash is configured according to the official document, but it just cannot connect to elasticsearch, and the error is reported that the certificate path is invalid, but if the certificate path of logstash is wrong, it will report that the path does not exist or cannot be typed. open file

### Steps to Reproduce

Use the latest version (8.3.2) of elasticsearch to build a cluster, start logstash, copy the certificate of elasticsearch (certs folder) to logstash, configure the elasticsearch output plug-in of pipeline, set hosts (HTTPS), user name, password and certs certificate path, restart logstash, and fail to connect elasticsearch with an error

### Logs (if relevant)

[WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"https://logstash_system:xxxxxx@192.168.16.2:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [https://192.168.16.2:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}

**Comment by Js0nMar2** [comment]
I solved it, configure xpack.monitoring.elasticsearch.ssl.certificate_authority: "your cacert" in logstash.yml

**Comment by rest17** [comment]
Error meesage for logs is really confusing. Have deployed elk stack on debian linux on gcp cloud. All the cmponents came up and was able to check the status of servcies active and running.  After installing the logstash_http_poller plugin ran into the error. Have tried all the solution mentioned above .Adding certs file to conf but don't understand why logstashoutput still tryinh to connect to http://elasticsearch:9200/. Conf file says https://localhost:9200/. Please help need the service to start running with this plugin polling the logs.

**Comment by rest17** [comment]
[2023-02-01T04:25:51,686][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://elastic:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch: Name or service not known"}
[2023-02-01T04:25:56,688][INFO ][logstash.outputs.elasticsearch][main] Failed to perform request {:message=>"elasticsearch", :exception=>Manticore::ResolutionFailure, :cause=>#<Java::JavaNet::UnknownHostException: elasticsearch>}

**Comment by HarimbolaSantatra** [comment]
> I solved it, configure xpack.monitoring.elasticsearch.ssl.certificate_authority: "your cacert" in logstash.yml

I tried this and it gives me another error:

```
# ["File does not exist or cannot be opened /etc/elasticsearch/certs/http_ca.crt"]
ssl_certificate_authorities => "/etc/elasticsearch/certs/http_ca.crt"
```

Here is the permission of the files:
```
$ ls -lh /etc/elasticsearch/certs/http_ca.crt
-rw-rw-r--. 1 root elasticsearch 1,9K 13 june  15:28 /etc/elasticsearch/certs/http_ca.crt
```
