### ISSUE TITLE
"IMMEDIATE" tasks getting queued up in pending tasks

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8860]
Have a situation where the cluster had to be restarted.  Upon restarting, there was a ton of recovery activity (at times, we observed >100 `EMERGENCY` tasks in pending_tasks).  As a result, attempts to update the cluster (eg. to increase the concurrency setting for recovery) started failing with 
`ProcessClusterEventTimeoutException` errors.

```
Request:

{"transient":{"cluster.routing.allocation.node_concurrent_recoveries": 10}}

Response:

HTTP/1.1 503 Service Unavailable

{"error":"RemoteTransportException[[Rush][inet[/IP:9300]][cluster/settings/update]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (cluster_update_settings) within 30s]; ","status":503}
```

https://github.com/elasticsearch/elasticsearch/blob/1816951b6b0320e7a011436c7c7519ec2bfabc6e/src/main/java/org/elasticsearch/common/Priority.java#L45 seems to indicate that `IMMEDIATE` tasks are of higher priority of `EMERGENCY` tasks.  But for some reason, these update cluster setting calls are being queued up still.

```
Partial pending_tasks output:

{ 
"insert_order" : 2125, 
"priority" : "IMMEDIATE", 
"source" : "cluster_update_settings", 
"executing" : false, 
"time_in_queue_millis" : 5908, 
"time_in_queue" : "5.9s" 
}

{ 
"insert_order" : 1949, 
"priority" : "URGENT", 
"source" : "shard-started ([index20141116][8], node[nodeID], [P], s[INITIALIZING]), reason [master [Rush][nodeID][node][inet[/172.16.0.6:9300]]{http=false, data=false, master=true} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]", 
"executing" : true, 
"time_in_queue_millis" : 2463692, 
"time_in_queue" : "41m" 
}
```

Is the cluster too busy to even go and re-prioritize its running tasks?  Or is it because once an `EMERGENCY` task starts to run, even if an `IMMEDIATE` task comes in, it will still have to wait till these running `EMERGENCY` tasks have completed?  In other words, if the `IMMEDIATE` task comes in at the same time as an `EMERGENCY` task, it will get prioritized higher, but it will not go and suspend any running `EMERGENCY` task to allow for the `IMMEDIATE` task to run first, etc..?

**Comment by clintongormley** [comment]
This has probably been resolved by async shard store fetching.  Please reopen if you still see this on recent versions
