### ISSUE TITLE
TopSuggestDocsCollector duplication check

### ISSUE THREAD

**Issue by pgrebien** [elastic/elasticsearch#88613]
### Elasticsearch Version

master, 6.8, 7.7

### Java Version

_bundled_

### OS Version

ubuntu/maxOSX/windows

### Problem Description

the duplication check in the TopSuggestDocsCollector.collect() method is wrong in case of context suggestions. in our case our documents contain multiple persons and calling the completionSuggester results in filtering additional person names after the first one. Removing the if statement 'if (isNewDoc) {' results in a correct response

### Steps to Reproduce

 - create an index with a completion type and contexts (I don't think the contexts are the problem but we use them)
   this is our dynamic template:
   {
            "template_suggest_persons": {
                "path_match": "persons.*_suggest",
                "match_pattern": "regex",
                "mapping": {
                    "type": "completion",
                    "contexts": [
                        {
                            "name": "assetGroups",
                            "type": "category"
                        }
                    ],
                    "analyzer": "lowercase_keyword_analyzer",
                    "search_analyzer": "lowercase_keyword_analyzer",
                    "max_input_length": 250
                }
            }
        }

 - put one document with multiple e.g. persons.actor.perLanguage.de_suggest values with a sharing prefix
 - call the suggester:
   {
	"_source": false,
	"suggest": {
		"persons.actor.perLanguage.de_suggest": {
			"text": "prefix",
			"completion": {
				"field": "persons.actor.perLanguage.de_suggest",
				"size": 1000,
				"contexts": {
					"assetGroups": [{
							"context": "xrm_default2",
							"boost": 2
						}, {
							"context": "xrm_default1",
							"boost": 1
						}
					]
				}
			}
		}
	}
}

you will see that not all of the names are showing up

**Comment by jtibshirani** [comment]
Hello @pgrebien , I believe this issue is the same as https://github.com/elastic/elasticsearch/issues/31738 and it's not something we plan to change/ fix. In summary, the suggesters work on a document level and are designed to return one hit per document. They cannot return multiple suggestions from the same document. I'm going to close this in favor of https://github.com/elastic/elasticsearch/issues/31738, but feel free to comment there if you have more to add.
