### ISSUE TITLE
[DOCS] Provide more detail on using search_after in pagination docs

### ISSUE THREAD

**Issue by travisestill** [elastic/elasticsearch#88624]
### Elasticsearch Version

8.x, 7.x

### Problem Description

Throughout the 7.x and 8.x docs, we instruct users to use `search_after` instead of scroll and link to the `search_after` anchor on this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after.

Yet, we immediately go into discussing PIT searches without providing any `search_after` examples. By comparison, here's an example of the `search_after` documentation for 6.8: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-search-after.html

Because we heavily link to the current pagination docs, can we please update these to have clearer examples of using `search_after`, ideally, before we start explaining PIT searches.

**Comment by anthonymcglone2022** [comment]
@nik9000 Does Elasticsearch allow external contributors to help with these bugs? I'm a QA Engineer that wants to get into Technical Writing. I'd love to learn more about Elasticsearch as well.

**Comment by nik9000** [comment]
> @nik9000 Does Elasticsearch allow external contributors to help with these bugs? I'm a QA Engineer that wants to get into Technical Writing. I'd love to learn more about Elasticsearch as well.

Be my guest! There are some docs here: https://github.com/elastic/elasticsearch/blob/main/docs/README.asciidoc - those'll link you to the docs repo which has a tool to build a copy of the ES docs. But if it's fairly simple stuff you can just code the changes blind and open a PR. If you add any new snippets you'll want to follow the instructions in that README to run the tests that those snippets make. It's cool to ping us if you have any trouble too.

Once you open a PR there'll be a check that wants you to sign our cla: https://www.elastic.co/contributor-agreement . We need it for everything - docs or code changes, no matter how small. 

Good luck! Let me know if you need anything.

**Comment by anthonymcglone2022** [comment]
> > @nik9000 Does Elasticsearch allow external contributors to help with these bugs? I'm a QA Engineer that wants to get into Technical Writing. I'd love to learn more about Elasticsearch as well.
> 
> Be my guest! There are some docs here: https://github.com/elastic/elasticsearch/blob/main/docs/README.asciidoc - those'll link you to the docs repo which has a tool to build a copy of the ES docs. But if it's fairly simple stuff you can just code the changes blind and open a PR. If you add any new snippets you'll want to follow the instructions in that README to run the tests that those snippets make. It's cool to ping us if you have any trouble too.
> 
> Once you open a PR there'll be a check that wants you to sign our cla: https://www.elastic.co/contributor-agreement . We need it for everything - docs or code changes, no matter how small.
> 
> Good luck! Let me know if you need anything.

Thanks, will do!
