### ISSUE TITLE
Remove top level `filter` parameter

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#8862]
Let's remove top level filter (https://github.com/elasticsearch/elasticsearch/issues/4119) from the product.  It can be confusing to end users given that we no longer document the top level filter in our guides (we only talk about post_filter now), but Marvel auto-fill still shows it as a valid clause at the top level.

**Comment by Mpdreamz** [comment]
Should we do the same for percolator requests:

http://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html

and rename its `filter` to `post_filter`? or does its `aggs` behave slightly different from `_search`'s aggs?

**Comment by clintongormley** [comment]
@Mpdreamz the `filter` on percolators is different - it's essentially just like a filtered query in that case.

**Comment by javanna** [comment]
Given that #11600 is in, does this need to stay open? Is there anything left to do?

**Comment by clintongormley** [comment]
@javanna that change was reverted, so yes this still needs to be done.
