### ISSUE TITLE
Add a check for unassigned shards residing on the node being removed in the shutdown status check

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#88635]
`TransportGetShutdownStatusAction` has a few checks that prevents the node from being shut down if there are shards without a copy that we can't move. We should also check that whether the node has unassigned shard and if it does, return the `STALLED` status and prevent the node from being shut down.

Relates #73873, #78578

**Comment by kingherc** [comment]
Also check that any unassigned shards did not reside lastly on one of the nodes being shut down, else return STALLED. cc @idegtiarenko

**Comment by kunisen** [comment]
Also logically thinking, shutdown should be done safely.
That said, if a shutdown can result in a red cluster (from either green or yellow), then it should fail. Otherwise, it causes data loss. 

(cc @idegtiarenko )

**Comment by idegtiarenko** [comment]
> Or alternatively, node shutdown API should also check cluster health, and if it's red (no matter at the beginning of the plan it's green or yellow), it should fail.

I do not think that we should rely on a cluster health in this case. Instead we should check the `org.elasticsearch.cluster.routing.UnassignedInfo#lastAllocatedNodeId` on every unallocated primary shard and only stall if it is the node we are trying to permanently shutdown.

We should be able to shut down a node in a red cluster if the node is not holding any last copy of the data. It is also okay to shut down a node in a yellow cluster as the yellow shard could be migrated somewhere else and the replicas could be rebuild from the new primary.

**Comment by grcevski** [comment]
We'll use the approach @idegtiarenko suggested and implement that. Before we say we are in progress of shutting down we'll run the checks on lastAllocatedNodeId.

**Comment by grcevski** [comment]
I wrote some additional tests and I had to modify the condition slightly, it's not enough to check for primary shard always, what I did instead is ask if this unassigned shard is found somewhere else, on a node that's not shutting down. So primary or not found elsewhere. Does that make sense?
