### ISSUE TITLE
description param explanation for _reindex  task is not correct

### ISSUE THREAD

**Issue by amitmbm** [elastic/elasticsearch#88668]
### Elasticsearch Version

8.3

### Java Version

_bundled_

### OS Version

NA

### Problem Description

[detailed param explanation in the document](https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html#_get_more_information_about_tasks) has below sentence about `_reindex` task

> like [_reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) which has the search and the destination

while _reindex has source and destination index, and not the search, so it should have been 

> like [_reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) which has the source and the destination index information

Apart from fixing the `search` to `source` which is definitely required we can also explain it bit more by adding `index information` in the sentence.

### Steps to Reproduce

NA

### Logs (if relevant)

NA

**Comment by abdonpijpelink** [comment]
This was fixed in https://github.com/elastic/elasticsearch/pull/88669. Closing.
