### ISSUE TITLE
Improve ability to identify where a query is originating from

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/elasticsearch#88699]
### Description

Many times, queries can be seen running in clusters that are consuming resources and impacting overall cluster throughput of other queries or indexing.  The ability to identify where a query is coming from, via raw ES api, Kibana user, Kibana alert ID, Watcher alert ID, Transform job, ML job, cross cluster version of any of the above, or wherever it is coming from will help identify where to find a way to stop future executions of the query in a timely fashion.

**Comment by benwtrent** [comment]
This capability is available in logging systems when utilizing header information. Additionally, the tasks API will include this information as well.
