### ISSUE TITLE
Ingest pipeline date processor - text could not be parsed at index 0

### ISSUE THREAD

**Issue by TopSecretShares** [elastic/elasticsearch#88727]
### Elasticsearch Version

7.12

### Java Version

_bundled_

### OS Version

debian

### Problem Description

I am trying to parse the 7 digits date 2022611 with a pattern yyyyMdd.

In the sample I use _ingest pipeline, but same issue exists in Logstash

### Steps to Reproduce

```
POST /_ingest/pipeline/_simulate
{
  "pipeline" :
  {
    "description": "_description",
    "processors": [
      {
        "date" : {
          "target_field" : "timestamp",
          "formats" : [ "yyyyMdd" ],
          "field" : "ts"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "ts": "2022611"
      }
    }
  ]
}
```

### Logs (if relevant)

```
{
  "docs" : [
    {
      "error" : {
        "root_cause" : [
          {
            "type" : "illegal_argument_exception",
            "reason" : "unable to parse date [2022611]"
          }
        ],
        "type" : "illegal_argument_exception",
        "reason" : "unable to parse date [2022611]",
        "caused_by" : {
          "type" : "illegal_argument_exception",
          "reason" : "failed to parse date field [2022611] with format [yyyyMdd]",
          "caused_by" : {
            "type" : "date_time_parse_exception",
            "reason" : "Text '2022611' could not be parsed at index 0"
          }
        }
      }
    }
  ]
}

```

**Comment by HiDAl** [comment]
Hello @TopSecretShares , 

from [Elasticsearch's documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#custom-date-formats), the Date processor uses the patterns defined by [`DateTimeFormatter`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html). Sadly, it doesn't support this kind of pattern out-of-the-box:

<img width="965" alt="Screenshot 2022-12-27 at 15 19 45" src="https://user-images.githubusercontent.com/284537/209679630-9c72debe-549a-4545-b12e-79440c7e7de4.png">

you must separate the pattern using some sign (I used slashes in this case)

thanks
