### ISSUE TITLE
ILM tests have switches with impossible branches

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#88743]
The following ILM tests all contain switch statements with branches that will never execute. The tests use a `between(x, y)` switch expression, but there are `case` values that are outside the randomised range. We need to fix these before #88739 can be merged. By "fix", I mean either remove the spurious cases, or if we actually want them, then extend the randomized range.

   * ActionConfigStatsTests
   * AllocateActionTests
   * CopyExecutionStateStepTests
   * RolloverActionTests
   * WaitForRolloverReadyStepTests

**Comment by joegallo** [comment]
I fixed some of these already on https://github.com/elastic/elasticsearch/pull/83345, I'll get a clean PR up that just addresses only these and fixes them. Thanks, @pugnascotia!
