### ISSUE TITLE
jakarta.json.stream.JsonParsingException: Property name 'key' is not in the 'type#name' format. Make sure the request has 'typed_keys' set.

### ISSUE THREAD

**Issue by houbbbbb** [elastic/elasticsearch#88750]
### Elasticsearch Version

7.16

### Java Version

_bundled_11

### OS Version

win10

### Problem Description

when use ElasticsearchClient adjacencyMatrix

jakarta.json.stream.JsonParsingException: Property name 'key' is not in the 'type#name' format. Make sure the request has 'typed_keys' set.

### Steps to Reproduce

normal operation

**Comment by astefan** [comment]
@houbbbbb please provide a more descriptive reproduction scenario for the problem you are facing. The current description is not enough for understanding the issue.
