### ISSUE TITLE
Support updates of API key attributes (bulk mode)

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#88758]
### Description

Currently, we support [updating the attributes of a single API key](https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-update-api-key.html).

To address scalability requirements, we should support a bulk mode for this operation. In particular, we should implement a route that applies the same update to a batch of API keys, `POST _security/api_key/_bulk_update`.

The route takes a list of API key IDs (`ids`), which to update, along with the same request parameters as the single operation route:

- `role_descriptors` - The list of role descriptors specified for the key. This is one of the two parts that determines an API key’s privileges.
- `metadata_flattened` - The searchable metadata associated to an API key

Analogously to the single operation route, a call to `_bulk_update` will automatically update the `limited_by_role_descriptors`, `creator`, and `version` fields for each API key.

This breaks down into the following tasks:

- [x] REST, transport, and service layer implementation
- [x] Audit logging
- [x] REST spec and YAML tests
- [x] [DOCS] API

**Comment by amitkanfer** [comment]
@n1v0lg Thank you! Will this be available in 8.4 or 8.5?

**Comment by n1v0lg** [comment]
@amitkanfer this will be out in 8.5 -- I think the label wasn't available yet when I created the issue. Fixed now!
