### ISSUE TITLE
Allow updating the excludes setting for the _source field

### ISSUE THREAD

**Issue by mrkamel** [elastic/elasticsearch#88769]
### Description

We find ourselves adding fields to an index which contain lots of data. However the data is only relevant for searching and there is no need to ever retrieve it. Of course we can use query time source filtering, but as the fields are very large we want to disable it by excluding it from the source via the mapping for performance reasons:

```json
    {   
      "_source":    {   
        "excludes": [
          "package_blocks",
          "mapped_keywords",
          "..."
        ]
      }
    }
```

Unfortunately, it's not possible to dynamically change the list of fields to exclude, because elasticsearch complains: `Cannot update excludes setting for [_source]`. Of course we could create a new index with the mapping change in place and reindex everything, but it would be nice if we'd be able to avoid that. Therefore, i'd like to request changing that to make it possible to dynamically change the fields to be excluded from `_source`. Please note that it would be totally fine for us if already indexed documents are not affected by the mapping change, such that already indexed documents need to be reindexed to get rid of the excluded fields. Thanks in advance.

**Comment by wchaparro** [comment]
We discussed this as a team, and will close this as “won’t fix”.  The excludes setting allows us to reason about the state of the index.  If portions of the index are in one state and others are in different states, then we need to build in logic to adjust behaviors at the individual document level, which is not trivial. And… this gets even more complicated in a distributed scenario, where these changes need to be inspected on multiple shards/nodes.

**Comment by javanna** [comment]
> Of course we could create a new index with the mapping change in place and reindex everything, but it would be nice if we'd be able to avoid that. 

One suggestion I may add: you can rollover to a new index, and apply the new mappings only to new documents that go into the new index, given that you said you are fine with existing documents and you prefer not to reindex them.

**Comment by mrkamel** [comment]
i understand, thx for discussing it and for letting me know.
