### ISSUE TITLE
Specify custom analyzers in the analyze API

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8878]
For testing purposes, it would be nice to be able to construct custom analyzers on the fly in the `analyze` API.  Currently you have to create a temporary index instead.

With the change to accept JSON in the body of the `analyze` request (https://github.com/elasticsearch/elasticsearch/issues/5866), we would be able to specify the tokenizer, filters etc in the body itself.

**Comment by johtani** [comment]
I try to implement this, however it is hard to get any TokenFilter/Tokenizer/CharFilterFactory without IndexService.
implementing this needs to re-factor AnalysisModule I think...

**Comment by johtani** [comment]
#14355 and #8961 are related to this

**Comment by celesteking** [comment]
This was a very bad decision, to separate _analyze API from index settings API.

I can't find a way to make this work in /_analyze:
```
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "tokenizer": "my_tokenizer"
        }
      },
      "tokenizer": {
        "my_tokenizer": {
          "type": "pattern",
          "pattern": ","
        }
      }
```

The whole point of _anazlye, is to try YOUR OWN custom analyzer, not the one that's defined in the book. Becaues the one in book is already known to work and explained in details.

**Comment by javanna** [comment]
> This was a very bad decision, to separate _analyze API from index settings API.

I am not sure I follow, this issue refers to an improvement, an addition that allows to include tokenizers etc. as part of the request body of the analyze api. What was the bad decision exactly?

You can test your tokenizer by defining it as an anonymous tokenizer, you don't have to create an analyzer for it:

```
curl -XGET localhost:9202/_analyze -d '{    
  "text" : "tes1,test2",
  "tokenizer": {
    "type": "pattern",
    "pattern": ","
  }
}
'
```

The analyzer can only be a string, referring to an existing analyzer, but the nice thing is that you can create an anonymous analyzer on the fly by just combining an anonymous tokenizer and anonymous token filters. Hope this clarifies things for you.

**Comment by celesteking** [comment]
Decision to choose 2) over 1) in  https://github.com/elastic/elasticsearch/issues/8878#issuecomment-66663806 

Your query is the first thing I tried, it fails:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unknown parameter [tokenizer] in request body or parameter is of the wrong type[START_OBJECT] "
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Unknown parameter [tokenizer] in request body or parameter is of the wrong type[START_OBJECT] "
  },
  "status": 400
}
```

Also, whole doc is wrong https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-analyze.html -- the method should be POST not GET. 
GET requests should not contain a body, according to REST guides.

**Comment by javanna** [comment]
@celesteking which version are you running against? I have tried it before posting it against 5.0.1 and it worked fine.

> Also, whole doc is wrong https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-analyze.html -- the method should be POST not GET.
GET requests should not contain a body, according to REST guides.

Yes that is a big debate in IT, we went for supporting body with GET requests, as that is no mistake in our docs.

You are welcome.
