### ISSUE TITLE
[CI] Window builds fail with "Unable to delete file"

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#88806]
### CI Link

https://gradle-enterprise.elastic.co/s/6wrucnjdgjjdm https://gradle-enterprise.elastic.co/s/5c56fglmqlk4s https://gradle-enterprise.elastic.co/s/vwzb3ppw7p4ww https://gradle-enterprise.elastic.co/s/tqamvqdpkzzi4 https://gradle-enterprise.elastic.co/s/rniwyfcmjmkyi https://gradle-enterprise.elastic.co/s/k3xxqjli6mxye

### Repro line

Not provided

### Does it reproduce?

No

### Applicable branches

main

### Failure history

-

### Failure excerpt

Seemingly unrelated build tasks fail with "Unable to delete file" similar to

```
...

build complete, generating: C:\Users\jenkins\workspace\platform-support\253\build\253.tar.bz2

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\jenkins\workspace\platform-support\253\x-pack\plugin\security\qa\basic-enable-security\build.gradle' line: 67

* What went wrong:
Execution failed for task ':x-pack:plugin:security:qa:basic-enable-security:javaRestTestWithSecurityEnabled'.
> java.io.IOException: Unable to delete file 'C:\Users\jenkins\workspace\platform-support\253\x-pack\plugin\security\qa\basic-enable-security\build\testclusters\javaRestTest-0\config'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to stop service 'reaper'.
> org.gradle.api.GradleException: Reaper process failed. Check log at C:\Users\jenkins\workspace\platform-support\253\.gradle\reaper\build-6028\error.log for details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2h 16m 17s
3630 actionable tasks: 3402 executed, 228 from cache
```

Note that the console output usually presents a different exception but these are warnings and probably not the cause of the test failure.

All of the failed builds failed to delete some config in paths like `C:\Users\jenkins\workspace\platform-support\253\x-pack\plugin\security\qa\basic-enable-security\build\testclusters\javaRestTest-0\config`

**Comment by pugnascotia** [comment]
Another one here: https://gradle-enterprise.elastic.co/s/ej25bgovouves

**Comment by ChrisHegarty** [comment]
Quite a few similar looking failures:

https://gradle-enterprise.elastic.co/s/v3xtchxnk6tqs
Unable to delete file 'C:\Users\jenkins\workspace\platform-support\257\qa\rolling-upgrade\build\testclusters\v8.5.0-2\config'

https://gradle-enterprise.elastic.co/s/7wfnjuh5jhexc
Unable to delete file 'C:\Users\jenkins\workspace\platform-support\257\qa\rolling-upgrade\build\testclusters\v8.5.0-1\config'

https://gradle-enterprise.elastic.co/s/cohmf44ibam76
Unable to delete file 'C:\Users\jenkins\workspace\platform-support\257\x-pack\plugin\security\qa\basic-enable-security\build\testclusters\javaRestTest-0\config'

Just a hunch, without any investigation, but it may be that the recently added file-based setting support is not releasing the file watcher on the config direction in all node termination situations. cc/ @grcevski

**Comment by grcevski** [comment]
I can take a look, I have a windows machine and I can try to reproduce this.

**Comment by ChrisHegarty** [comment]
Many many daily failures, e.g.

```
Execution failed for task ':x-pack:qa:rolling-upgrade-multi-cluster:v8.4.0#leader#upgradedClusterTest'.
> java.io.IOException: Unable to delete file 'C:\Users\jenkins\workspace\platform-support\11\x-pack\qa\rolling-upgrade-multi-cluster\build\testclusters\v8.4.0-leader-2\config'
  > Unable to delete file 'C:\Users\jenkins\workspace\platform-support\11\x-pack\qa\rolling-upgrade-multi-cluster\build\testclusters\v8.4.0-leader-2\config'
```

https://gradle-enterprise.elastic.co/s/ed7zj6wyzqlju

Some cluster integration REST tests do not seem to terminate the server gracefully, therefore the file settings service NIO watcher, on the config directory, will not be released (closed).

**Comment by mark-vieira** [comment]
Yeah, the Windows tests on 8.4 and main are in a very bad shape. This issue seems to be exclusive to those branches so it's unlikely to be an environmental issue. My other thought was perhaps this was related to the Gradle 7.5 upgrade but that was done about a week before all these failures started.

**Comment by ywangd** [comment]
It also fails for arm https://gradle-enterprise.elastic.co/s/evdybcrdtdn5i

**Comment by mark-vieira** [comment]
> It also fails for arm https://gradle-enterprise.elastic.co/s/evdybcrdtdn5i

That root failure is unrelated and I believe 9cf85c0708d1c6a54cbf44cc3ffb55112be3a69b will take care of the issue with the reaper process reporting an error.

**Comment by ChrisHegarty** [comment]
By means of an instrumented build, I managed to capture the stacktrace from the failing test:

```
Failed to create working directory for node{:x-pack:plugin:ccr:qa:restart:follow-cluster-0},
with throwable: org.gradle.api.UncheckedIOException: java.io.IOException: Unable to delete file
'C:\Users\jenkins\workspace\pr-part-2\148\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\config 'org.gradle.api.UncheckedIOException:
  java.io.IOException: Unable to delete file 'C:\Users\jenkins\workspace\pr-part-2\148\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\config'
  at org.gradle.api.internal.file.DefaultFileOperations.delete(DefaultFileOperations.java:266)
  at org.gradle.api.internal.file.DefaultFileSystemOperations.delete(DefaultFileSystemOperations.java:46)
  at org.elasticsearch.gradle.testclusters.ElasticsearchNode.deleteFileWithRetry0(ElasticsearchNode.java:1244)
  at org.elasticsearch.gradle.testclusters.ElasticsearchNode.deleteWithRetry(ElasticsearchNode.java:1221)
  at org.elasticsearch.gradle.testclusters.ElasticsearchNode.createWorkingDir(ElasticsearchNode.java:1290)
  at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:518)
  at org.elasticsearch.gradle.testclusters.ElasticsearchNode.restart(ElasticsearchNode.java:625)
  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  at org.elasticsearch.gradle.testclusters.ElasticsearchCluster.restart(ElasticsearchCluster.java:379)
  at org.elasticsearch.gradle.testclusters.TestClusterConfiguration$restart$2.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
  at build_cup6v6rlnk2cj48sf7v2bkks8$_run_closure6$_closure11.doCall(C:\Users\jenkins\workspace\pr-part-2\148\x-pack\plugin\ccr\qa\restart\build.gradle:51)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)

  ...
  Caused by: java.io.IOException: Unable to delete file 'C:\Users\jenkins\workspace\pr-part-2\148\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\config'
    at org.gradle.internal.file.impl.DefaultDeleter.throwWithHelpMessage(DefaultDeleter.java:181)
    at org.gradle.internal.file.impl.DefaultDeleter.deleteRecursively(DefaultDeleter.java:114)
    at org.gradle.internal.file.impl.DefaultDeleter.deleteRecursively(DefaultDeleter.java:65)
    at org.gradle.api.internal.file.DefaultFileOperations.delete(DefaultFileOperations.java:264)
    ... 172 more
```

Of note:

 * the exception is coming from within the Gradle `DefaultFileOperations` (rather than some custom ES test logic)

 * Gradle has its own unchecked `org.gradle.api.UncheckedIOException` (which is clearly different from Java's `java.io.UncheckedIOException`)

**Comment by ChrisHegarty** [comment]
The current working theory, that explains the failures we're seeing, is that the node processes in the test cluster retain a "handle" to the config directory for a short period of time after they have been terminated. This is not surprising, has been observed in other projects, and is explained by the asynchronous nature of deletions on the Windows file-system.

We believe that this issue was always possible, but is now exacerbated by the fact that the file settings service is watching the config directory while the node it forcibly terminated.

There is already significant IO error handling in the test cluster infrastructure, but the unchecked Gradle `UncheckedIOException` evades any of this - since it's unchecked and also not of type `java.io.IOException`. 

We're currently experimenting with catching the unchecked Gradle exception, and retrying the delete after a short wait period.
