### ISSUE TITLE
Add search.knn section into the _nodes/usage API

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#88821]
### Description

Similarly, how `GET _nodes/usage` API has a section for `aggregations `,  we need to add a section for `search`, and within it `knn`. This is necessary for telemetry to track the number of knn searches used by a node(s).

**Comment by jtibshirani** [comment]
@mayya-sharipova maybe we can close this one out since we decided to go with cluster stats instead (https://github.com/elastic/elasticsearch/pull/90176) ?
