### ISSUE TITLE
Installation failure of Elastic 6.8.23 on Win2016

### ISSUE THREAD

**Issue by ImGuna** [elastic/elasticsearch#88857]
### Elasticsearch Version

6.8.23

### Java Version

11.0.14

### OS Version

Windows Server 2016

### Problem Description

I have downloaded elasticsearch6.8.23.msi and tried to install. Though I have given proxy for installing ICU and Kuromoji plug-ins, I got an exception message and unchecked them to proceed further on installation.
At the end, I got a message that an error occurred during installation. Attached the installation log message. Can you pls help on fixing the issue? In addition, if I couldnt able to install the plug-ins during the installation process, how to enable them post installation of Elastic search?

### Steps to Reproduce

install elasticsearch6.8.23 using msi installer

### Logs (if relevant)

I am unable to attach the log and also copy/paste the same due to character limitation

**Comment by ImGuna** [comment]
is there any other options to upload the installation log file, such as curl to an s3? I could see Error appearing from the below:
******* Product: D:\elasticsearch-6.8.23.msi
           ******* Action: INSTALL
           ******* CommandLine: **********
MSI (s) (E8:7C) [15:38:27:696]: Machine policy value 'DisableUserInstalls' is 0
MSI (s) (E8:7C) [15:38:27:703]: Note: 1: 2203 2: C:\Windows\Installer\inprogressinstallinfo.ipi 3: -2147287038 
MSI (s) (E8:7C) [15:38:27:705]: Machine policy value 'LimitSystemRestoreCheckpointing' is 0
MSI (s) (E8:7C) [15:38:27:705]: Note: 1: 1715 2: Elasticsearch 6.8.23 
MSI (s) (E8:7C) [15:38:27:705]: Note: 1: 2205 2:  3: Error 
MSI (s) (E8:7C) [15:38:27:705]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1715 
MSI (s) (E8:7C) [15:38:27:705]: Calling SRSetRestorePoint API. dwRestorePtType: 0, dwEventType: 102, llSequenceNumber: 0, szDescription: "Installed Elasticsearch 6.8.23".
MSI (s) (E8:7C) [15:38:27:705]: The call to SRSetRestorePoint API failed. Returned status: 0. GetLastError() returned: 127
MSI (s) (E8:7C) [15:38:27:709]: File will have security applied from OpCode.
MSI (s) (E8:7C) [15:38:27:864]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'D:\elasticsearch-6.8.23.msi' against software restriction policy
MSI (s) (E8:7C) [15:38:27:866]: SOFTWARE RESTRICTION POLICY: D:\elasticsearch-6.8.23.msi has a digital signature
MSI (s) (E8:7C) [15:38:28:574]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (E8:7C) [15:38:28:575]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (E8:7C) [15:38:28:576]: SOFTWARE RESTRICTION POLICY: D:\elasticsearch-6.8.23.msi is permitted to run at the 'unrestricted' authorization level.
MSI (s) (E8:7C) [15:38:28:576]: MSCOREE not loaded loading copy from system32
MSI (s) (E8:7C) [15:38:28:587]: End dialog not enabled
MSI (s) (E8:7C) [15:38:28:587]: Original package ==> D:\elasticsearch-6.8.23.msi
MSI (s) (E8:7C) [15:38:28:587]: Package we're running from ==> C:\Windows\Installer\b5260.msi
MSI (s) (E8:7C) [15:38:28:589]: APPCOMPAT: Compatibility mode property overrides found.
MSI (s) (E8:7C) [15:38:28:589]: APPCOMPAT: looking for appcompat database entry with ProductCode '{249BC889-95E3-4DD5-9B05-DB04755F0E9E}'.
MSI (s) (E8:7C) [15:38:28:589]: APPCOMPAT: no matching ProductCode found in database.
MSI (s) (E8:7C) [15:38:28:594]: Machine policy value 'TransformsSecure' is 1
MSI (s) (E8:7C) [15:38:28:594]: Machine policy value 'DisablePatch' is 0
MSI (s) (E8:7C) [15:38:28:594]: Machine policy value 'AllowLockdownPatch' is 0
MSI (s) (E8:7C) [15:38:28:594]: Machine policy value 'DisableLUAPatching' is 0
MSI (s) (E8:7C) [15:38:28:594]: Machine policy value 'DisableFlyWeightPatching' is 0
MSI (s) (E8:7C) [15:38:28:595]: APPCOMPAT: looking for appcompat database entry with ProductCode '{249BC889-95E3-4DD5-9B05-DB04755F0E9E}'.
MSI (s) (E8:7C) [15:38:28:595]: APPCOMPAT: no matching ProductCode found in database.
MSI (s) (E8:7C) [15:38:28:595]: Transforms are not secure.
MSI (s) (E8:7C) [15:38:28:595]: Note: 1: 2205 2:  3: Control 
MSI (s) (E8:7C) [15:38:28:595]: PROPERTY CHANGE: Adding MsiLogFileLocation property. Its value is 'C:\Users\glbm62m\AppData\Local\Temp\MSI36ab1.LOG'.
MSI (s) (E8:7C) [15:38:28:596]: Command Line: INSTALLDIR=D:\Elastic\Elasticsearch\6.8.23 DATADIRECTORY=D:\Elastic\Elasticsearch\data CONFIGDIRECTORY=D:\Elastic\Elasticsearch\config LOGSDIRECTORY=D:\Elastic\Elasticsearch\logs NODENAME=WT80B10057DV00 USELOCALSYSTEM=false CURRENTDIRECTORY=D:\ CLIENTUILEVEL=3 CLIENTPROCESSID=9180 ACTION=INSTALL USERNAME=User COMPANYNAME=Org SELECTEDMEMORY=2048 MINIMUMMASTERNODES=0 USEEXISTINGUSER=true USER=ams\glbm62m PASSWORD=********** XPACKSECURITYENABLED=false SKIPSETTINGPASSWORDS=false XPACKLICENSE=Basic MSICLIENTUSESEMBEDDEDUI=1 ACTION=INSTALL 
MSI (s) (E8:7C) [15:38:28:596]: PROPERTY CHANGE: Adding PackageCode property. Its value is '{F7C723BB-844A-4D0A-BB71-C3279B33C527}'.
MSI (s) (E8:7C) [15:38:28:596]: Product Code passed to Engine.Initialize:           ''
MSI (s) (E8:7C) [15:38:28:596]: Product Code from property table before transforms: '{249BC889-95E3-4DD5-9B05-DB04755F0E9E}'
MSI (s) (E8:7C) [15:38:28:596]: Product Code from property table after transforms:  '{249BC889-95E3-4DD5-9B05-DB04755F0E9E}'
MSI (s) (E8:7C) [15:38:28:596]: Product not registered: beginning first-time install
MSI (s) (E8:7C) [15:38:28:596]: Product {249BC889-95E3-4DD5-9B05-DB04755F0E9E} is not managed.
MSI (s) (E8:7C) [15:38:28:596]: MSI_LUA: Credential prompt not required, user is an admin
MSI (s) (E8:7C) [15:38:28:596]: PROPERTY CHANGE: Adding ProductState property. Its value is '-1'.
MSI (s) (E8:7C) [15:38:28:596]: Entering CMsiConfigurationManager::SetLastUsedSource.
MSI (s) (E8:7C) [15:38:28:596]: User policy value 'SearchOrder' is 'nmu'
MSI (s) (E8:7C) [15:38:28:596]: Adding new sources is allowed.
MSI (s) (E8:7C) [15:38:28:596]: PROPERTY CHANGE: Adding PackagecodeChanging property. Its value is '1'.
MSI (s) (E8:7C) [15:38:28:596]: Package name extracted from package path: 'elasticsearch-6.8.23.msi'
MSI (s) (E8:7C) [15:38:28:597]: Package to be registered: 'elasticsearch-6.8.23.msi'
MSI (s) (E8:7C) [15:38:28:597]: Note: 1: 2205 2:  3: Error 
MSI (s) (E8:7C) [15:38:28:598]: Note: 1: 2262 2: AdminProperties 3: -2147287038 
MSI (s) (E8:7C) [15:38:28:598]: Machine policy value 'DisableMsi' is 1
MSI (s) (E8:7C) [15:38:28:598]: Machine policy value 'AlwaysInstallElevated' is 0
MSI (s) (E8:7C) [15:38:28:598]: User policy value 'AlwaysInstallElevated' is 0
MSI (s) (E8:7C) [15:38:28:598]: Product installation will be elevated because user is admin and product is being installed per-machine.
MSI (s) (E8:7C) [15:38:28:598]: Running product '{249BC889-95E3-4DD5-9B05-DB04755F0E9E}' with elevated privileges: Product is assigned.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding INSTALLDIR property. Its value is 'D:\Elastic\Elasticsearch\6.8.23'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding DATADIRECTORY property. Its value is 'D:\Elastic\Elasticsearch\data'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding CONFIGDIRECTORY property. Its value is 'D:\Elastic\Elasticsearch\config'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding LOGSDIRECTORY property. Its value is 'D:\Elastic\Elasticsearch\logs'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding NODENAME property. Its value is 'WT80B10057DV00'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Modifying USELOCALSYSTEM property. Its current value is 'true'. Its new value: 'false'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding CURRENTDIRECTORY property. Its value is 'D:\'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding CLIENTUILEVEL property. Its value is '3'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding CLIENTPROCESSID property. Its value is '9180'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding ACTION property. Its value is 'INSTALL'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding USERNAME property. Its value is 'User'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding COMPANYNAME property. Its value is 'Org'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding SELECTEDMEMORY property. Its value is '2048'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding MINIMUMMASTERNODES property. Its value is '0'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding USEEXISTINGUSER property. Its value is 'true'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding USER property. Its value is 'ams\glbm62m'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding PASSWORD property. Its value is '**********'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding XPACKSECURITYENABLED property. Its value is 'false'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding SKIPSETTINGPASSWORDS property. Its value is 'false'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding XPACKLICENSE property. Its value is 'Basic'.
MSI (s) (E8:7C) [15:38:28:598]: PROPERTY CHANGE: Adding MSICLIENTUSESEMBEDDEDUI property. Its value is '1'.
MSI (s) (E8:7C) [15:38:28:598]: Machine policy value 'DisableAutomaticApplicationShutdown' is 0
MSI (s) (E8:7C) [15:38:28:608]: PROPERTY CHANGE: Adding MsiRestartManagerSessionKey property. Its value is '6fa46c4fe576974e9fa62ef1d531616a'.
MSI (s) (E8:7C) [15:38:28:608]: RESTART MANAGER: Session opened.
MSI (s) (E8:7C) [15:38:28:608]: TRANSFORMS property is now: 
MSI (s) (E8:7C) [15:38:28:608]: PROPERTY CHANGE: Adding VersionDatabase property. Its value is '200'.
MSI (s) (E8:7C) [15:38:28:610]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming
MSI (s) (E8:7C) [15:38:28:611]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\Favorites
MSI (s) (E8:7C) [15:38:28:613]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Network Shortcuts
MSI (s) (E8:7C) [15:38:28:614]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\Documents
MSI (s) (E8:7C) [15:38:28:615]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Printer Shortcuts
MSI (s) (E8:7C) [15:38:28:616]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Recent
MSI (s) (E8:7C) [15:38:28:618]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\SendTo
MSI (s) (E8:7C) [15:38:28:619]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Templates
MSI (s) (E8:7C) [15:38:28:619]: SHELL32::SHGetFolderPath returned: C:\ProgramData
MSI (s) (E8:7C) [15:38:28:620]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Local
MSI (s) (E8:7C) [15:38:28:622]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\Pictures
MSI (s) (E8:7C) [15:38:28:624]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools
MSI (s) (E8:7C) [15:38:28:625]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
MSI (s) (E8:7C) [15:38:28:626]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
MSI (s) (E8:7C) [15:38:28:627]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu
MSI (s) (E8:7C) [15:38:28:629]: SHELL32::SHGetFolderPath returned: C:\Users\Public\Desktop
MSI (s) (E8:7C) [15:38:28:632]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Administrative Tools
MSI (s) (E8:7C) [15:38:28:633]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
MSI (s) (E8:7C) [15:38:28:635]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
MSI (s) (E8:7C) [15:38:28:636]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\AppData\Roaming\Microsoft\Windows\Start Menu
MSI (s) (E8:7C) [15:38:28:637]: SHELL32::SHGetFolderPath returned: C:\Users\glbm62m\Desktop
MSI (s) (E8:7C) [15:38:28:639]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Templates
MSI (s) (E8:7C) [15:38:28:639]: SHELL32::SHGetFolderPath returned: C:\Windows\Fonts
MSI (s) (E8:7C) [15:38:28:640]: Note: 1: 2898 2: MS Sans Serif 3: MS Sans Serif 4: 0 5: 16 
MSI (s) (E8:7C) [15:38:28:644]: MSI_LUA: Setting MsiRunningElevated property to 1 because the install is already running elevated.
MSI (s) (E8:7C) [15:38:28:645]: PROPERTY CHANGE: Adding MsiRunningElevated property. Its value is '1'.
MSI (s) (E8:7C) [15:38:28:645]: PROPERTY CHANGE: Adding Privileged property. Its value is '1'.
MSI (s) (E8:7C) [15:38:28:645]: PROPERTY CHANGE: Adding DATABASE property. Its value is 'C:\Windows\Installer\b5260.msi'.
MSI (s) (E8:7C) [15:38:28:645]: PROPERTY CHANGE: Adding OriginalDatabase property. Its value is 'D:\elasticsearch-6.8.23.msi'.
MSI (s) (E8:7C) [15:38:28:645]: Machine policy value 'MsiDisableEmbeddedUI' is 0
MSI (s) (E8:7C) [15:38:28:645]: EEUI - Disabling MsiEmbeddedUI due to existing external or embedded UI
MSI (s) (E8:7C) [15:38:28:645]: EEUI - Disabling MsiEmbeddedUI for service because it's not a quiet/basic install

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
