### ISSUE TITLE
elastic agent not sending logs back tok ELK 8.x

### ISSUE THREAD

**Issue by theb47m4n** [elastic/elasticsearch#88879]
Hi!
My team has installed two elastic agents one on an internal server which is sending logs perfectly and the other on the public server which is not sending logs when we check in the fleet agent section of the logs stream and in discover also. ELK is accessible on private and public IP both.
using elk 8.x 
also have no idea how to change the default output settings on the Fleet settings page.
check the attached screenshots if by chance anyone can figure out the issue.

![fleet error 1](https://user-images.githubusercontent.com/110153627/181439240-14300b40-2528-4564-96b4-dc4d14f17719.png)
![es error 3](https://user-images.githubusercontent.com/110153627/181439247-7e66d79c-079f-4fce-93c9-3f90feca2436.png)
![es error 4](https://user-images.githubusercontent.com/110153627/181439257-237748cf-a741-4402-a65c-35d4eca6da6b.png)
![kibana error 1](https://user-images.githubusercontent.com/110153627/181439262-a6dd6b90-12a5-4b8d-a2d8-c9dec4e3eac5.png)
![kibana error 2](https://user-images.githubusercontent.com/110153627/181439266-9e09ba47-6754-4b10-af66-93dd78011d42.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by theb47m4n** [comment]
I already did, a week ago on the discussion platform of ELK, when I received no reply, I came here for help. 
refer https://discuss.elastic.co/t/how-can-i-use-elk-8-3-3-without-security-enabled/310501/2
thanks btw
