### ISSUE TITLE
elastic-logging-plugin disable SSL certificate validation

### ISSUE THREAD

**Issue by amandradzhiyski** [elastic/elasticsearch#88896]
### Description

Hello,

Is it possible to disable SSL certificate validation when elastic-logging-plugin docker plugin communicate with elasticsearch by HTTPS and server's certificate is selfsigned or untrusted?
Or is it possible to trust it somehow?

**Comment by ebuildy** [comment]
Use stackoverflow for questions.

You can read how to configure elasticsearch beat output here : https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#client-verification-mode

**Comment by astefan** [comment]
@amandradzhiyski Thank you for posting your question here, but this is an ask that can better be handled in our [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. As such, I hope you don't mind that I close this.
