### ISSUE TITLE
Add queries section into the _nodes/usage API

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#88908]
Similarly, how GET [_nodes/usage](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-usage.html)  API has a section for `aggregations` , we want to add a section for `queries`.

Requirements:
- Unlike`aggregations` section, `queries` section will be without break up on field types
    -  Many queries have only a single field type (e.g. knn query)
     - For some queries it is difficult/ impossible to deduce field type, or it doesn't make sense (e.g. bool)

- We want to deduplicate query types per search request (e.g. if a search request contained 1 bool query and 10 terms query, we want to count it as 1 bool query and 1 term query).

Sub-tasks:

- [x] https://github.com/elastic/elasticsearch/issues/88821

**Comment by javanna** [comment]
Closing as superseded by #91528 (already implemented).
