### ISSUE TITLE
[CI] RandomSamplerIT testRandomSamplerHistogram failing

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#88930]
### CI Link

https://gradle-enterprise.elastic.co/s/xwgyyheje4ife

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerHistogram" -Dtests.seed=F60BD0BD3B588271 -Dtests.locale=en-AU -Dtests.timezone=Asia/Dili -Druntime.java=17

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
org.elasticsearch.search.aggregations.bucket.RandomSamplerIT > testRandomSamplerHistogram FAILED
    java.lang.AssertionError: 
    Expected: a value less than <248.6234180564282>
         but: <260.03999999999996> was greater than <248.6234180564282>
        at __randomizedtesting.SeedInfo.seed([F60BD0BD3B588271:53E4F638EA46C4F6]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerHistogram(RandomSamplerIT.java:158)
```

**Comment by idegtiarenko** [comment]
Another one in 8.4 branch: https://gradle-enterprise.elastic.co/s/n6zstnjul262c/tests/:server:internalClusterTest/org.elasticsearch.search.aggregations.bucket.RandomSamplerIT/testRandomSamplerHistogram?top-execution=1

**Comment by slobodanadamovic** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/l2etgzzy2nlbm/tests/:server:internalClusterTest/org.elasticsearch.search.aggregations.bucket.RandomSamplerIT/testRandomSampler
