### ISSUE TITLE
`/_cluster/reroute` should not return a cluster state in its response

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#88978]
### Description

Currently the result of `POST /_cluster/reroute` command execution contains the entire cluster state after it was applied.

Probably it was added there to provide the user with overview of a shards allocation after command was executed, however cluster state is excessive for it, not documented, might cause OOM in smaller clusters while rendering and contains a lot of unnecessary details. I believe it should be removed from the response or replaced with some other shard allocation representation.

**Comment by VimCommando** [comment]
On very large clusters this can generate a response in the hundreds of megabytes. Manually calling the `_cluster/reroute`  typically happens when there is already some kind of issue in the cluster, this extra load does _not_ help the situation.

**Comment by DaveCTurner** [comment]
We discussed this internally and agreed that `?metric=none` will remove the `state` field altogether, and other values of `?metric` (including its absence) will be deprecated and removed in the next major.

**Comment by volodk85** [comment]
The issue is sitting in silos until 9.0.x work is started. Development is done and is awaiting right moment for review and merge.
