### ISSUE TITLE
Example plugin test compile error

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#88985]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+example-plugins/268/console

### Repro line

gradlew :rescore:compileJava

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

Looks like a regression caused by https://github.com/elastic/elasticsearch/pull/88735

/CC @jdconrad

**Comment by jtibshirani** [comment]
I wonder if we should make sure example compile errors fail PR builds. I'm not sure why this compile task didn't run as part of the main build. CC @elastic/es-delivery
