### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by Ron-Nefyodov** [elastic/elasticsearch#88989]
So i have many alerts with the same cause (some maware send messages to C2) with the same source IP address. Can i aggregate such alerts in one (aggregation by source IP address)?

**Comment by michaelbaamonde** [comment]
Hi, thanks for your interest. This question is best suited for our [Discuss forums](https://discuss.elastic.co/). GitHub is primarily for bug reports and feature requests. 

Create a topic in the [Elastic Stack category](https://discuss.elastic.co/c/elastic-stack/81) and someone will help you out. Thanks!
