### ISSUE TITLE
Remove docker export projects

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#89031]
Our integration tests are set up so that the test task depends on the project
that creates the required artifacts. Note, it doesn't depend on a task, but a
project! This means we have a number of docker sub-projects purely for exporting
the image. This was somewhat useful then we used to use Vagrant for testing,
but this has largely since been abandoned. We should rework the testing so that
we can remove all this docker save / load nonsense.

**Comment by mark-vieira** [comment]
I don't think we can remove these since we export the docker images so they can be uploaded by the release manager.
