### ISSUE TITLE
Installation of Elasticsearch service fails when a whitespace is in the path

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#89043]
### Elasticsearch Version

8.3.0

### Java Version

_bundled_

### OS Version

Windows

### Problem Description

```
C:\>"C:\a b\elasticsearch-8.5.0-SNAPSHOT\bin\elasticsearch-service.bat" install
warning: ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8
warning: ignoring JAVA_HOME=c:\Users\christopher_hegarty\Downloads\jdk-17.0.2; using bundled JDK
Installing service : elasticsearch-service-x64
Using ES_JAVA_HOME : C:\a b\elasticsearch-8.5.0-SNAPSHOT\jdk
'C:\a' is not recognized as an internal or external command,
operable program or batch file.

ERROR: Failed installing 'elasticsearch-service-x64' service
```

### Steps to Reproduce

Place Elasticsearch in a directory path that contains a whitespace, then try to install the Windows service.

### Workaround (if relevant)

Install into a directory without a whitespace in the file-system path.

**Comment by ChrisHegarty** [comment]
The CLI startup scripts (#https://github.com/elastic/elasticsearch/pull/85821) have been reworked in 8.3 - mostly rewritten in Java, rather than shell scripts. There would appear to be an issue with missing quotes in some paths.

**Comment by digger73** [comment]
Any work around for this ?

**Comment by ChrisHegarty** [comment]
@digger73 - there is no known workaround ( except installing in a folder without white space ).
