### ISSUE TITLE
Completion Suggester Version 2

### ISSUE THREAD

**Issue by areek** [elastic/elasticsearch#8909]
# Overview
The main features of the new Completion Suggester are:
 - **Near real-time** - ensures no deleted docs are ever suggested (addresses https://github.com/elasticsearch/elasticsearch/issues/7761), allows returning arbitrary fields as payload 
 - **Flexible scoring** - exposed through the new geo scorer (addresses https://github.com/elasticsearch/elasticsearch/issues/6444#issuecomment-64408912, https://github.com/elasticsearch/elasticsearch/issues/4759)
 - **Flexible filtering with categories** - suggestions can be associated with arbitrary categories, `AND` and `OR` operators on categories can be used at query-time. (addreses https://github.com/elasticsearch/elasticsearch/issues/6444)

Apart from the features above, the new suggester will be able to return multiple outputs matching an input upon configuration (`duplicate_output`) (addresses https://github.com/elasticsearch/elasticsearch/issues/8129, https://github.com/elasticsearch/elasticsearch/issues/7641, https://github.com/elasticsearch/elasticsearch/issues/4255)

The new Completion Suggester will be using `NRTSuggester` instead of the previous `XAnalyzingSuggester`.

**Sample use-cases:**
 - **Filtering with categories** - get completion for some prefix for all or any provided `categories`
 - **Flexible scoring (geo)** - get completion for some prefix for all or any provided `categories` sorted by the distance (between provided `score_context` and completion `weight`).

# Usage

**NOTE:** The API presented is experimental and may change.

## Mapping
```bash
curl -X PUT localhost:9200/<index>/<type>/_mapping -d '{
    "<type>": {
        "properties": {
            "name": {
                "type": "string"
            },
            "suggest": {
                "type": "completion",
                "index_analyzer": "..",
                "search_analyzer": “..”,
                "preserve_separators": true | false,
                "preserve_position_increments": true | false,
                "duplicate_output" : true | false, (default: false)
                "has_categories": true | false, (default: false)
                "scorer": "default" | "geo" (default: "default")
            }
        }
    }
}'
```
### Indexing with `categories` and default `scorer`
```bash
curl -X PUT 'localhost:9200/music/song/1?refresh=true' -d '{
    "name": "completion_with_default_scorer",
    "suggest": {
        "categories" : ["rock", "grunge"]
        "input": [ "Nevermind", "Nirvana" ],
        "output": "Nirvana - Nevermind",
        "weight": 34
    }
}'
```
### Indexing with `categories` and geo `scorer`
```bash
curl -X PUT 'localhost:9200/places/food/1?refresh=true' -d '{
    "name": "completion_with_geo_scorer",
    "suggest": {
        "categories" : ["cafe", "snacks"]
        "input": [ "timmis", "timhorton" ],
        "output": "Tim Hortons",
        "weight": {
            "lat": ...,
            "lon": ...
        }
    }
}'
```
### Indexing with no `categories` and default `scorer`
same as the current Completion Suggester

## Querying

**Note:** `payload_template` can have references to one or more fields that will be retrieved at query-time.

### Querying on suggesters with `categories` and default `scorer`

Query all completions associated with `category` "rock" with payload
```bash
curl -X POST 'localhost:9200/music/_suggest?pretty' -d '{
    "song-suggest" : {
        "text" : "nir",
        "categories" : ["rock"],
        "payload_template" : "attr1: {{field1Name}}, attr2: {{field2Name}}"
        "completion" : {
            "field" : "suggest"
        }
    }
}'
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "song-suggest" : [ {
    "text" : "nir",
    "offset" : 0,
    "length" : 4,
    "options" : [ {
      "text" : "Nirvana - Nevermind",
      "score" : 34.0, 
      "categories" : ["rock"],
      "payload" : "attr1: field1Value, attr2: field2Value"
    } ]
  } ]
}
```
Query all completions which are either associated with rock `category` or metal `category`.
**Note:** `category_operation` defaults to "AND"
```bash
curl -X POST 'localhost:9200/music/_suggest?pretty' -d '{
    "song-suggest" : {
        "text" : "nir",
        "categories" : ["rock", "metal"],
        "category_operation": "OR", 
        "completion" : {
            "field" : "suggest"
        }
    }
}'
```
### Querying on suggesters with `categories` and geo `scorer`

Query all completions which are associated with `category` "cafe" with some `score_context` (e.g. current location). The result will be sorted by the distance of the geo `score` for the completion w.r.t. provided `score_context`
```bash
curl -X POST 'localhost:9200/places/_suggest?pretty' -d '{
    "place-suggest" : {
        "text" : "tim",
        "categories" : ["cafe"],
        "score_context" : { "lat": ..., "lon": ... }
        "payload_template" : "attr1: {{field1Name}}, attr2: {{field2Name}}"
        "completion" : {
            "field" : "suggest"
        }
    }
}'
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "place-suggest" : [ {
    "text" : "tim",
    "offset" : 0,
    "length" : 4,
    "options" : [ {
      "text" : "Tim Hortons",
      "score" : <Distance between `score_context` and `completion score`>, 
      "categories" : ["cafe"],
      "payload" : "attr1: field1Value, attr2: field2Value"
    } ]
  } ]
}
```

### Querying on suggesters with no `categories` and default `scorer`
same as the current Completion Suggester

# NRTSuggester
The new Completion Suggester will be using a new `NRTSuggester`. Currently the `NRTSuggester` is under development and is planned to support at least the functionalities described so far.

In the second phase, the following will be considered:
 - enable 'fuzziness' (edit distance) to influence suggestion scoring (addresses https://github.com/elasticsearch/elasticsearch/issues/4441)
 - [TENTATIVE] experiment with enabling filter support (addresses https://github.com/elasticsearch/elasticsearch/issues/8096)

# Migration plan 

New Completion Suggester will use a new completion index format under the hood, so some work needs to be done to upgrade from existing completion suggester to the new one. The migration strategy still needs to be decided.

**Comment by missinglink** [comment]
hey @areek @s1monw happy new year!

After using the existing completion suggester extensively over the last 6+ months for https://github.com/pelias/pelias we are now looking at replacing our autocomplete functionality with an `ngram` solution, for a variety of reasons:

1. unable to achieve POI classification as per: https://github.com/elasticsearch/elasticsearch/issues/6444
- unable to sort results, by geographic distance or otherwise
- payload fields take a huge amount of RAM, we ended up just storing IDs and saving >100GB RAM.
- when not using payload fields the double-query approach negates the speed gains from the FST
- FST traversal is strictly anchored on the left and so will never be able to return "121 mapzen place" for the query "122 mapzen place"
- unable to provide 2x fields such as `name,city` separately and boost at query time
- unable to query the whole planet due to `precision:0` issue

I hope this might give you some insights in to how the new context suggester could be better. If you need any more info about any specific point I'd be happy to help.

**Comment by areek** [comment]
Hey @missinglink happy new year to you too!

Thanks for the detailed feedback. The work on the new 'suggester' is being done on https://github.com/elasticsearch/elasticsearch/pull/9643 (Lucene API; work on the ES API will be started soon). I will update this issue with the new ES API for it.

Some comments based on https://github.com/elasticsearch/elasticsearch/pull/9643 (WIP):

> unable to achieve POI classification as per: #6444

can be achieved through query-time filtering/fine grained lookup field(s)

>  unable to sort results, by geographic distance or otherwise

can be done through a "geo scorer", which will return the completions sorted by the distance between the completion document and the provided geo location

> payload fields take a huge amount of RAM, we ended up just storing IDs and saving >100GB RAM.

no more payload fields, one can simply return other field(s) from a document

> unable to query the whole planet due to `precision:0` issue

It will be possible to get completions with no context

**Comment by Godstermx** [comment]
hi  

the Completion Suggester Version 2 source code is in master ?

**Comment by areek** [comment]
Hi @Godstermx, the completion suggester V2 is not in master yet. It is still being worked on.

**Comment by areek** [comment]
closing in favour of https://github.com/elastic/elasticsearch/issues/10746, sorry for the noise

**Comment by violaivy** [comment]
Is there any way to sort completion suggester results. Need help
