### ISSUE TITLE
Permit no-op reregistration of a snapshot repository if marked corrupted

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#89130]
Today if we detect concurrent modification of a snapshot repository then we mark it with `CORRUPTED_REPO_GEN` which blocks further writes to try and prevent additional damage to its contents. You can remove the marker by calling the register-repository API again, but this API will discard no-op re-registrations without taking any action. You can work around this by unregistering the repository first (which may be impossible if it's still in use for searchable snapshots) or by re-registering it with some trivial setting change (which seems hacky).

We should not consider it a no-op re-registration if the repository is currently marked with `CORRUPTED_REPO_GEN`, because doing this re-registration will re-read the repo contents and clear the corruption marker and therefore is not a no-op.

**Comment by kingherc** [comment]
I am considering to tackle this issue since it seems it needs to be tackled first before the related issue https://github.com/elastic/elasticsearch/issues/89696 .

> You can remove the marker by calling the register-repository API again, but this API will discard no-op re-registrations without taking any action.

Any pointers in the code as to where this "discard" happens? cc @tlrx

**Comment by tlrx** [comment]
Thanks for volunteering for fixing this.

> > You can remove the marker by calling the register-repository API again, but this API will discard no-op re-registrations without taking any action.
> 
> Any pointers in the code as to where this "discard" happens?

I think that this sentence refers to https://github.com/elastic/elasticsearch/blob/2a44a8982faa64d8abab770e55c801090195bbf9/server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java#L216-L217

**Comment by kingherc** [comment]
And furthermore, in related issue https://github.com/elastic/elasticsearch/issues/89696 we discovered that re-registering a repository changes the UUID, which then creates issues when (re-)allocating shards of searchable snapshots. I think this may be an issue in this case as well?

**Comment by kingherc** [comment]
OK, looking at the mentioned code I see:

```
                        if (canUpdateInPlace(newRepositoryMetadata, existing)) {
                            if (repositoryMetadata.settings().equals(newRepositoryMetadata.settings())) {
                                // Previous version is the same as this one no update is needed.
                                return currentState;
                            }
                            // we're updating in place so the updated metadata must point at the same uuid and generations
                            updatedMetadata = repositoryMetadata.withSettings(newRepositoryMetadata.settings());
                        } else {
                            ensureRepositoryNotInUse(currentState, request.name());
                            updatedMetadata = newRepositoryMetadata;
                        }
```

I think solving this issue would be just removing `if (repositoryMetadata.settings().equals(newRepositoryMetadata.settings())) {`.

And 

solving related issue https://github.com/elastic/elasticsearch/issues/89696 would be to extend `ensureRepositoryNotInUse()` to consider if there are any mounted searchable snapshots using the repos.
