### ISSUE TITLE
java.lang.OutOfMemoryError: PermGen space within node() call (elastic 1..4.1)

### ISSUE THREAD

**Issue by alexdharma91** [elastic/elasticsearch#8916]
My code is
        ImmutableSettings.Builder settings = ImmutableSettings.settingsBuilder();
        settings.put("client.transport.sniff", false);
        settings.put("path.home", "/path/to/elastic/home");
        settings.put("index.number_of_replicas", 0);
        settings.put("index.number_of_shards", 1);
        settings.put("action.write_consistency", "one");
        settings.build();
        NodeBuilder nb = new NodeBuilder().settings(settings).local(true).data(true);
        Node node = nb.node();

Within calling node() call method i
 get java.lang.OutOfMemoryError: PermGen space

That code i run within web app and get this error. When i run the same code in main method in simple class - all is ok.

More details about error:
Excepton caused in IndexingMemoryController.class in methond doStart()
this part trow exception - new ShardsIndicesStatusChecker()
Class ShardsIndicesStatusChecker exists and state in IndexingMemoryController class.
And before call node method in console appears text that "class ShardsIndicesStatusChecker not found" but this going not every time(i mean class not found exception)

Where is wrong code or settings?

**Comment by jpountz** [comment]
The class loader does not seem to have enough memory to load all classes.
