### ISSUE TITLE
Remove wait_for_merge from optimize API

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#8921]
This method used to call IndexWriter.waitForMerges(), but this is no longer a public API in IndexWriter. We should not call it with reflection.

**Comment by s1monw** [comment]
@rmuir I removed the `IndexWriter.waitForMerges()` calls in master, 1.5 and 1.x and the option is also gone in those branches... closing

**Comment by heffergm** [comment]
So I have a lot of automated processing built around ingesting data into an index, optimizing, then snapshotting. With wait_for_merge I could ensure that the snapshotted index was fully merged before loading it into another (production) cluster. With that option gone, I don't see any way to accomplish this now.

Is this functionality going to be re-introduced?

**Comment by mikemccand** [comment]
@heffergm the option is now hardwired to `true`, i.e. we now always wait for merges to finish, which should work for your usage?

**Comment by heffergm** [comment]
It should. Weirdly what I saw was a snapshot happen during an optimize, which in my setup should only occur if the optimize exited with a 0 exit status and the code moved on to take the snapshot. But testing against another 1.5.2 cluster now, I see that's it's behaving as expected, so I'll need to dig in a bit more.

Thanks for confirming the behavior.
