### ISSUE TITLE
Wrapper query docs refer to transport client and HLRC

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#89263]
The [docs for wrapper queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wrapper-query.html) say:

> This query is more useful in the context of the Java high-level REST client or transport client to also accept queries as json formatted string.

The HLRC and transport client no longer exist in 8.x.

**Comment by javanna** [comment]
good catch, I think that we should deprecate the wrapper query.

**Comment by javanna** [comment]
Thanks @sethmlarson it's great to have an example so that we can replace the mention of transport client in the docs with this real usage from the field. I will relabel this.

**Comment by apurvsibal** [comment]
Hey @javanna,

Thank you for maintaining such a wonderful library. I really appreciate how proactive you are with the commits. 

Please can I work on this issue? 

If I understood it correctly we have to change the documentation on https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wrapper-query.html to replace 
"This query is more useful in the context of the Java high-level REST client or transport client to also accept queries as json formatted string. In these cases queries can be specified as a json or yaml formatted string or as a query builder (which is a available in the Java high-level REST client)." 

page with the following

"This query is more useful in the context of Spring Data Elasticsearch. It's the way a user can add custom queries when using Spring Data repositories. The user can add a @Query() annotation to a repository method. When such a method is called we do a parameter replacement in the query argument of the annotation and then send this as the query part of a search request.".

I have made the changes on my local. Let me know how to proceed?

**Comment by abdonpijpelink** [comment]
@apurvsibal Thank you - go right ahead. You can submit a PR against this repo. Please ensure it targets the `main` branch.

**Comment by nilanjanH** [comment]
@DaveCTurner , @javanna  - I can see @apurvsibal is already working on this issue & I want to pitch in as well. Please let me know your thoughts.

Thanks.

**Comment by apurvsibal** [comment]
@abdonpijpelink Thank you. I have submitted a pull request. Please let me know any changes that are required? 
@nilanjanH - would love to hear your thoughts?

**Comment by amyjtechwriter** [comment]
Closing as fix is merged. Thanks everyone!
