### ISSUE TITLE
[DOC] Search Template - remove conditional clause section until it is implemented

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#8928]
The official guide for [Search Template](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-template.html#search-template) explains how to use queries with [conditional clauses](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-template.html#_conditional_clauses). My understanding is that this is not supported yet. If it is not supported should the guide reflect this?

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/11512

**Comment by lukas-vlcek** [comment]
@clintongormley If I am not mistaken the issue #11512 has been fixed for ES 2.x, but this ticket was created to make sure online documentation for previous ES versions are updated accordingly. For example online documentation for ES 1.4 still contains chapter about [conditional clauses](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-template.html#_conditional_clauses), but is it really working for ES 1.4.x?
