### ISSUE TITLE
[Transform] Disable index creation for transforms to allow writing to a datastream

### ISSUE THREAD

**Issue by simianhacker** [elastic/elasticsearch#89291]
### Description

I would like to set the destination index for a pivot transform top a datastream.  Currently when you try to do this, the transform service fails with the following message when you attempt to start a transform which uses a datastream as the destination index.

```
{
  "error": {
    "root_cause": [
      {
        "type": "runtime_exception",
        "reason": "Could not create destination index [slo-data-default] for transform [slo-example]"
      }
    ],
    "type": "runtime_exception",
    "reason": "Could not create destination index [slo-data-default] for transform [slo-example]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "cannot create index with name [slo-data-default], because it matches with template [slo-datastream-template] that creates data streams only, use create data stream api instead"
    }
  },
  "status": 500
}
```

I tried to create the datastream before starting the transform hoping that would solve the problem; it did not.

### Acceptance Criteria

- Allow destination indices to be datastreams
- Provide a setting which disables index creation similar to `deduce_mappings `

**Comment by sophiec20** [comment]
Transforms update, therefore writing to a datastream is problematic. What is your use case?

**Comment by hendrikmuhs** [comment]
@sophiec20 was quicker, I already worked on this answer:

The reason why transform does not support data streams: Transform updates documents in the destination, but data streams are append only[*]. That means you will run into duplicates[**]. Only date_histogam together with aligned checkpoints and syncing on the same timestamp don't create dups under normal conditions, however on failover you might run into them again.

What we suggest to users that want something like ILM - a rolling index index basically - is using an output ingest pipeline with a date index name processor.

[*] I know a data stream is just a set of indices and there are ways to hack this.
[**] There have been discussions about allowing updates in data streams, which involves finding the old doc and deleting it or updating the doc in the data stream, but this got rejected. We see data stream as _append only_.
