### ISSUE TITLE
Do aarch64-architecture  support x-pack？

### ISSUE THREAD

**Issue by calvin2020** [elastic/elasticsearch#89297]
### Description

Hi:

My server CPU architecture is aarch64, my elasticsearch version is 6.2.4，now I want to use x-pack for security, Do aarch64-architecture  support x-pack？please help me ,thank you

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
