### ISSUE TITLE
Field Support on Function Scores Weight

### ISSUE THREAD

**Issue by erayarslan** [elastic/elasticsearch#89305]
### Description

Hi I want to propose "field support on function scores weight" like these:

```
{
    "query": {
        "function_score": {
            "query": {
                "match_all": {}
            },
            "functions": [
                {
                    "weight": {
                        "field": "test",
                        "missing": 1
                    }
                }
            ]
        }
    }
}
```
Also support old format for backward compatibility like these:
```
{
    "query": {
        "function_score": {
            "query": {
                "match_all": {}
            },
            "functions": [
                {
                    "weight": 3
                }
            ]
        }
    }
}
```

I thought it would be useful for creating more flexible weights based on document.
Also I developed this feature to clarify propose. I will send pull request soon.
Waiting for your valuable feedback. Thanks.

**Comment by mayya-sharipova** [comment]
@erayarslan Thanks for your proposal, but to my mind there is no need for this function, as this could be already achieved through `script_score` query like:

```js
"script_score": {
  "query": {..},
  "script": {
      "source": "doc['my_field'].value * <weight> "
  }
}
```

What's the reason, you can't use `script_score` for this?

----

Also, not to waste your time, before submitting a PR for your proposed feature, it is better first to get a team approval that it is something we want to implement.

**Comment by erayarslan** [comment]
@mayya-sharipova  Thanks for your feedbacks.
Actually I have a case like this query
```
{
    "query": {
        "function_score": {
            "query": {
                "match_all": {}
            },
            "functions": [
                {
                    "weight": ?, // i want to give different weight for every document
                    "linear": {
                        "exampleTimestampField": {
                            "origin": "2022-08-16 10:00:00",
                            "scale": "4h",
                            "offset": "90m",
                            "decay": 0.5
                        }
                    }
                }
            ]
        }
    }
}
```
For these query I cannot give document specific weight with function_score. 
And I cannot use field_value_factor cause I already using linear here.
But you are right. I know to solve this problem with script_score(so i did) but script_score decreasing our performance dramatically.
Because of these I want to propose this feature.
Sorry for giving lazy details at first.

**Comment by mayya-sharipova** [comment]
@erayarslan You can have multiple functions within `functions` and combine them through `score_mode` which is by default is `multiply`.  For example, the here the output from `linear` function is multiplied by `field_value_factor`, could be different for each document.

```js
"functions": [
    {
        "field_value_factor": {
            "field": "my_field",
            "factor": 1,
            "missing": 1
        }
    },
    {
        "linear": {
            "exampleTimestampField": {
                "origin": "2022-08-16 10:00:00",
                "scale": "4h",
                "offset": "90m",
                "decay": 0.5
            }
        }
    }
]
```

>  know to solve this problem with script_score(so i did) but script_score decreasing our performance dramatically.

We are aware of a small performance degradation (10-20%) while switching from `function_score` to `script_score` query. If you degradation is worse, please open a new github issue with the detailed performance analysis between `function_score` and `scrip_score` queries, and our team will look into this.  

----
Since what you are proposing can be already achieved in Elasticsearch, I will be closing your issue.

**Comment by erayarslan** [comment]
but in my case, i want to use `score_mode: sum`. i have a lot of functions to sum. this example small part of it.

**eg**: (linear * different weight per document) + (another function) + ...

so i cannot solve with `field_value_factor`. still need to multiply specific function with weight.
but in the current situation, i can't see any solution other than script_score.
sorry for not being able to give a specific example at first. i thought that was enough.

this feature is better than the `script_score` in terms of performance. (in my tests)
because 10-20% not small difference for my search business.

anyway. thanks for your feedbacks and time @mayya-sharipova

**Comment by mayya-sharipova** [comment]
but in my case, i want to use score_mode: sum. i have a lot of functions to sum. this example small part of it.

eg: (linear * different weight per document) + (another function) + ...

@erayarslan You can do this by stacking a number of function_score queries through a boolean `should` option, where each function_score query combines `field_value_factor` with  `linear`.

**Comment by erayarslan** [comment]
this method covering my search cases perfectly. and working better than `script_score`.
thank you so much for helping and your time @mayya-sharipova
