### ISSUE TITLE
Elasticsearch returns an error when field is not specified in Lucene query and index has fields which are not indexed nor have doc values

### ISSUE THREAD

**Issue by e40pud** [elastic/elasticsearch#89314]
### Elasticsearch Version

8.5.0

### Java Version

_bundled_

### OS Version

macOS Monterey Version 12.5

### Problem Description

We have an [issue](https://github.com/elastic/kibana/issues/137815) in kibana where we try to do Custom Query Rule preview using Lucene language where the field is missing and only the value is provided (example query: `host.name`). In this case Elasticsearch returns the next error:
```
reason: "failed to create query: Cannot search on field [Target.process.thread.Ext.parameter_bytes_compressed] since it is not indexed nor has doc values." type: "query_shard_exception" caused by reason: "Cannot search on field [Target.process.thread.Ext.parameter_bytes_compressed] since it is not indexed nor has doc values." caused by type: "illegal_argument_exception"
```
<img width="923" alt="Screenshot 2022-08-12 at 16 25 19" src="https://user-images.githubusercontent.com/2700761/184374531-b8188231-e398-4715-a1d5-b8adda1974e7.png">

Our assumption is that the search will try to match the query value to all the fields (because we don't provide a specific field in the query) in the index and since some fields might not be indexed it will throw an exception.

cc @marshallmain 

### Steps to Reproduce

Here are the index mappings, settings and details of request that we send to elasticsearch:

[mapping.txt](https://github.com/elastic/elasticsearch/files/9316981/mapping.txt)
[settings.txt](https://github.com/elastic/elasticsearch/files/9316982/settings.txt)
[request-details.txt](https://github.com/elastic/elasticsearch/files/9316983/request-details.txt)

To visualise the issue:
1. Open Kibana
2. Go to Security > Alerts > Manage rules > Create new rule
3. Select Custom Query rule type
4. Switch to Lucene language
5. Add `host.name` as a query
6. Click Preview results button

**Comment by jtibshirani** [comment]
@e40pud thanks for reporting this, it also looks like unexpected behavior to me. To clarify, did you just start observing this with recent builds (8.4.0 release candidate, and 8.5.0 snapshots) whereas it worked before?

**Comment by javanna** [comment]
This is not a bug: you have a long list of fields in your index settings under `query.default_field`. That list includes the `Target.process.thread.Ext.parameter_bytes_compressed` that is not searchable, which causes the error that you are getting back. The solution here is to remove non-searchable fields from the default fields, or given that you have such a long list, use `*` instead and Elasticsearch is going to expand it to all the searchable ones.
