### ISSUE TITLE
Set default node.max_local_storage_nodes to 1

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#8932]
A number of users over the years have been punished by unintentionally running two ES nodes simultaneously on the same server and then losing data because of mixed and lost data between `nodes/0` and `nodes/1` directories.

One such example: https://groups.google.com/d/msg/logstash-users/1JKLLa4YUw4/g0vcCcxmeiMJ

This occurs most frequently by accident, I think, under some weird situation where someone is running Elasticsearch, intends to restart it, and either has ES still running when the new node comes up or has some race condition during restart that causes 2 nodes to exist temporarily so the `nodes/0` directory is locked.

It would be very helpful for new users and operators to have `node.max_local_storage_nodes` default to 1.

**Comment by damm** [comment]
This is set by the Chef cookbook by default.  https://github.com/elastic/cookbook-elasticsearch/blob/master/libraries/resource_configure.rb#L102

Thank you for whomever did it.  It really should be set by default.

**Comment by pickypg** [comment]
Perhaps instead of making it to `1`, it should be limited to a more sane default, like `5` rather than `50` (the current). `5` would be inline with our current default port range for convenient development.

We should consider setting this when we install via the RPM/DEB installers.

**Comment by dakrone** [comment]
Resolved in 5.0 by  #19964

**Comment by Ankiewicz** [comment]
If you find you have two, how do you kill them?

`ls -al /usr/local/var/elasticsearch/elasticsearch_Jonathan
total 0
drwxr-xr-x  2 Jonathan  admin   68 Jan 20 23:32 .
drwxr-xr-x  4 Jonathan  admin  136 Jan 20 23:32 ..
Karries-iMac:simpleFi_Main Jonathan$ 

`
