### ISSUE TITLE
fix a typo in Security.java

### ISSUE THREAD

**Issue by dh-cloud** [elastic/elasticsearch#89327]
### Elasticsearch Version

8.4

### Java Version

11.0.16

### OS Version

Linux  3.10.0-1062.el7.x86_64 GNU/Linux

### Problem Description

In "org/elasticsearch/bootstrap/Security.java" class of the "addFilePermissions" method,there is a redundant "'" mistake in "path.conf'" of the parameter "configurationName" passed in "addDirectoryPath" method.

### Steps to Reproduce

1、Paths may not exist yet, this also checks accessibility
2、Will print 【Unable to access 'path.conf''】

**Comment by dh-cloud** [comment]
There's a pull request I made. #89248

**Comment by grcevski** [comment]
This is now closed via #89248
