### ISSUE TITLE
The name field must be added with keyword to query the data. why

### ISSUE THREAD

**Issue by caomingjie-code** [elastic/elasticsearch#89342]
### Elasticsearch Version

7.7.0

### Java Version

[root@7dce41543e56 bin]# ./java -version openjdk version "14" 2020-03-17 OpenJDK Runtime Environment AdoptOpenJDK (build 14+36) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

### OS Version

Linux mi-A35R 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

"name":{
					"type":"text",
					"fields":{
						"keyword":{
							"ignore_above":256,
							"type":"keyword"
						}
					}
				},

"class":{
					"type":"text",
					"fields":{
						"keyword":{
							"ignore_above":256,
							"type":"keyword"
						}
					}
				},

query 1 ----------------------------------------------------------------------------------------------------------------------------------------------------
{
    "query": {
        "bool": {
            "should": [
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "score": 80
                                }
                            }, 
                            {
                                "term": {
                                    "class": "chinese"
                                }
                            }
                        ]
                    }
                }, 
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "score": 85
                                }
                            }, 
                            {
                                "term": {
                                    "class": "english"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}

response:
	"hits":{
		"hits":[
			{
				"_index":"a",
				"_type":"b",
				"_source":{
					"score":80,
				
					"name":"mingJie",
					"id":10,
					"class":"chinese",
					"age":15
				},
				"_id":"c1",
				"_score":1.9808291
			},
			{
				"_index":"a",
				"_type":"b",
				"_source":{
					"score":85,
					"name":"wenJie",
					"id":12,
					"class":"english",
					"age":15
				},
				"_id":"c3",
				"_score":1.9808291
			}
		],
		"total":{
			"value":2,
			"relation":"eq"
		},

query 2----------------------------------------------------------------------------------------------------------------------------------------------------

{
    "query": {
        "bool": {
            "should": [
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "score": 80
                                }
                            }, 
                            {
                                "term": {
                                    "name": "mingJie"
                                }
                            }
                        ]
                    }
                }, 
                {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "score": 85
                                }
                            }, 
                            {
                                "term": {
                                    "name": "wenJie"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    }
}

response:
{
	"_shards":{
		"total":1,
		"failed":0,
		"successful":1,
		"skipped":0
	},
	"hits":{
		"hits":[],
		"total":{
			"value":0,
			"relation":"eq"
		}
	},
	"took":0,
	"timed_out":false
}

why this reponse data is blank ?

### Steps to Reproduce

why this reponse data is blank ?

**Comment by romseygeek** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
