### ISSUE TITLE
Incorrect client spec for create index body settings.index.mapping

### ISSUE THREAD

**Issue by rudolf** [elastic/elasticsearch#89381]
The Elasticsearch-js client typings for `client.indices.create` has type definitions for `body.settings.index.mappings` but according to the docs (and testing against main) this should be `body.settings.index.mapping`
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-settings-limit.html#mapping-settings-limit

My understanding is that this needs to be fixed in the Elasticsearch repo because the client types are derived from the api specs contained here.

**Comment by sethmlarson** [comment]
Hey @rudolf, is an issue with the elasticsearch-js client or the Java client? The JS client doesn't live in this repository so if that's the case I can transfer the issue or you can open a new one at https://github.com/elastic/elasticsearch-js.

**Comment by rudolf** [comment]
This is for the Elasticsearch-js client. Closing in favour of https://github.com/elastic/elasticsearch-js/issues/1753
