### ISSUE TITLE
AllocationService should use time injection

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#89382]
### Description

`AllocationService#currentNanoTime` is relying on `System.nanoTime()`.
Instead we should inject time using `ThreadPool#relativeTimeInNanos`

**Comment by DaveCTurner** [comment]
One slight wrinkle here is that `DeterministicTaskQueue` doesn't support nanosecond-resolution timestamps at the moment. So we'd have to add that.
