### ISSUE TITLE
date_histogram fails for year buckets >1, like "10y"

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#8939]
Attempting to do a date_histogram with 10-year sized buckets, passing "10y" to the `interval` setting results in this error:

```
ElasticsearchParseException[Failed to parse [10y]]; nested: NumberFormatException[For input string: \"10y\"]; 
```

As a workaround, I can specify large values for "weeks", so swapping in `520w` (or `3650d`) might be inaccurate, but possibly acceptable to some folks.

Sample agg (taken from Kibana 4) that causes the NumberFormatException:

```
          "date_histogram": {
            "field": "@timestamp",
            "interval": "1y",
            "min_doc_count": 1,
            "extended_bounds": {
              "min": -1767196800000,
              "max": 1418425008298
            }
          }
```

**Comment by rkalyankumar** [comment]
for more than 1 year, let's say 2 year interval the interval should be specified as 730d (365 * 2) & it works well. I have tested this until 3650d (10 year intervals) & works good.

**Comment by clintongormley** [comment]
Related to #14802

**Comment by dadoonet** [comment]
If we'll support it, we should try to support this also for months. Like a bucket every 3 months.

**Comment by animageofmine** [comment]
@dadoonet the support for months or years added? I attempted a '6M' date histogram, but doesn't look like it is supported.

**Comment by cbuescher** [comment]
@animageofmine no it is not yet supported and we recently added documentation to make this clear: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-aggregation. Hope this helps.

**Comment by animageofmine** [comment]
Thank you @cbuescher. Is there a plan to support it in future?

**Comment by cbuescher** [comment]
@animageofmine yes, this issue is still open. It's not a trivial change though, and since we are moving from joda-time to the new time library in java, I don't expect it to happen before that move.

**Comment by dadoonet** [comment]
Where did you see that quarter are or could be supported?

**Comment by colings86** [comment]
@animageofmine @dadoonet quarters are indeed supported but only when using the interval `quarters` or `1q` you cannot use `3M` as quarters. 6 months would be possible to implement if we added a `half-year` option but we don't want to add loads of different options like that as it makes things pretty complicated. 

Instead we would like to support arbitrary calendar intervals. The problem is that with the library we are currently using (joda-time) we cannot support arbitrary calendar intervals in a way that we are happy with. The library just doesn't allow it. We are hopeful that when we have moved to java.time (a big project in itself) this might change and we will be able to add support for arbitrary calendar intervals but this issue is stalled at least until then.

**Comment by dadoonet** [comment]
Oh? Then I'm curious as well on how quarters are implemented? Specifically with years having a Feb 29th day.

**Comment by dadoonet** [comment]
Great explanation. Thanks @colings86

**Comment by not-napoleon** [comment]
This is resolved by https://github.com/elastic/elasticsearch/pull/75000 which drops support for the `interval` parameter in favor of `calendar_interval` and `fixed_interval`.  Confusion like this issue motivated that change.  In the new paradigm, calendar intervals will allow for using natural units of time, like a year, a month, and a quarter.  But it only allows single unit bucket widths.  Fixed intervals use (relatively) fixed time intervals, defined as a set number of milliseconds regardless of calendar alignment.  You can read more [about calendar intervals](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#calendar_intervals) and [about fixed intervals](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#fixed_intervals) in the Elasticsearch reference documentation.
