### ISSUE TITLE
8.3.3 CLI_JAVA_OPTS set fail，but ES_JAVA_OPTS success

### ISSUE THREAD

**Issue by dly667** [elastic/elasticsearch#89454]
### Elasticsearch Version

8.3.3

### Java Version

_bundled_

### OS Version

Linux dai-server 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

1. memory exhausted
`docker run --name es -p 9200:9200 -p 9300:9300 -e CLI_JAVA_OPTS="-Xms1g -Xmx1g" -e "discovery.type=single-node" elasticsearch:8.3.3 `
top -c|grep elasticsearch
<img width="861" alt="image" src="https://user-images.githubusercontent.com/26707226/185362949-67a0b4b4-16c0-454e-b867-1cf1e6198f4e.png">

2. it,s ok 
`docker run --name es -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms1g -Xmx1g" -e "discovery.type=single-node" elasticsearch:8.3.3  `
top -c|grep elasticsearch
<img width="920" alt="image" src="https://user-images.githubusercontent.com/26707226/185363556-64cd202d-041c-4f25-9d97-0f898dec947b.png">

### Steps to Reproduce

`docker run --name es -p 9200:9200 -p 9300:9300 -e CLI_JAVA_OPTS="-Xms1g -Xmx1g" -e "discovery.type=single-node" elasticsearch:8.3.3 `

`docker run --name es -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms1g -Xmx1g" -e "discovery.type=single-node" elasticsearch:8.3.3  `

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by SansDK** [comment]
@DaveCTurner this seems to be a problem in the documentation.
The 8.x docs says you can use `CLI_JAVA_OPTS` environment variable to set `Xms` and `Xmx` options, but setting this has no effect. Using `ES_JAVA_OPTS` **does** however have the desired effect.
