### ISSUE TITLE
Enhancement of "Text fields are not optimised for operations ..." log message

### ISSUE THREAD

**Issue by sakurai-youhei** [elastic/elasticsearch#89485]
### Description

Users may see the below log message under various circumstances,

> https://github.com/elastic/elasticsearch/blob/v8.3.3/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java#L899-L906
> Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [FIELD_NAME] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

as people seem to have mentioned this message in [Elasticsearch](https://github.com/elastic/elasticsearch/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+), [Kibana](https://github.com/elastic/kibana/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+), and [Beats](https://github.com/elastic/beats/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+) GH issues as well as at [forums](https://discuss.elastic.co/search?q=%22Text%20fields%20are%20not%20optimised%20for%20operations%22).

I don't intend to suggest revise of this well-known message but want to propose an insertion of contextual information - i.e. field and index name to clarify where to start troubleshooting at a glance.

**Proposal**

```diff
diff --git a/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java b/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
index 045be484f09..74df90ffc0f 100644
--- a/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
+++ b/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
@@ -909,7 +909,8 @@ public class TextFieldMapper extends FieldMapper {
             } else if (operation == FielddataOperation.SEARCH) {
                 if (fielddata == false) {
                     throw new IllegalArgumentException(
-                        "Text fields are not optimised for operations that require per-document "
+                        "Field data is disabled on [" + name() + "] in [" + fieldDataContext.fullyQualifiedIndexName() + "]. "
+                            + "Text fields are not optimised for operations that require per-document "
                             + "field data like aggregations and sorting, so these operations are disabled by default. Please use a "
                             + "keyword field instead. Alternatively, set fielddata=true on ["
                             + name()
```

If this proposal sounds reasonable, please let me know, and I will open PRs accordingly. Thanks.

**Comment by javanna** [comment]
++ @sakurai-youhei what you are suggesting makes sense, I would be glad to review your PR!

**Comment by sakurai-youhei** [comment]
@javanna Thank you for your confirmation and kind offer. I've opened PR accordingly.
