### ISSUE TITLE
Documentation format for Elasticsearch Official Documentation is incorrect.

### ISSUE THREAD

**Issue by bhavyaidr** [elastic/elasticsearch#89504]
### Elasticsearch Version

8.3

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 21.4.0

### Problem Description

Elasticsearch's documentation is in the wrong format. Right now, the sidebar is completely unresponsive, which makes it challenging for us to read the documentation.

![image](https://user-images.githubusercontent.com/46423346/185917046-326576d0-0976-41c8-bba4-1813dd498c60.png)

### Steps to Reproduce

You will notice that the sidebar is unresponsive when you open any documentation page, such as https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro.html, making it challenging to navigate the page sidebar

**Comment by lockewritesdocs** [comment]
@bhavyaidr, what browser are you using? Can you empty your browser cache and reload the page? I'm not seeing this issue in either Firefox or Chrome.

**Comment by lockewritesdocs** [comment]
This issue was also reported in the Elastic Discuss forums. The [suggested fix](https://discuss.elastic.co/t/the-new-version-of-the-official-documentation-is-too-bad-to-use/313312/7) is to clear the cache, which should fix your issue.
