### ISSUE TITLE
Shutdown replace contracts auto-expand replicas

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#89527]
### Elasticsearch Version

7.17.1

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

Shutdown with mode REPLACE will move all shards from the node being replaced (source) to a new node (target node).

However, it also affects auto-expand replicas. Today, it will contract the auto-expand replicas by considering them to not expand to neither the source nor the target node. This is wrong, instead the source/target pair should be considered one node.

The REPLACE indication is expected to be added prior to starting the new target node (but we should be lenient towards it appearing later). This adds a bit of complexity to how to handle auto-expand replicas. I propose to:

1. disregard a shutdown for REPLACE record when there is no corresponding target node.
2. not expand to the source node when the target node is present.

We discussed this topic during original implementation [here](https://github.com/elastic/elasticsearch/pull/76247#discussion_r695529067) as well. The problem with the current implementation is that we risk reducing the number of replicas to 0 during a shutdown for REPLACE, potentially putting data at risk.

### Steps to Reproduce

N/A

### Logs (if relevant)

```
...  updating number_of_replicas to [0] for indices [ ...
```

**Comment by kingherc** [comment]
This is still relevant for 7.17.x so re-opening this with the main aim to backport the PR to 7.17.x.
