### ISSUE TITLE
Usage stats of user profiles

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#89525]
As we are rolling out the user profile feature, we'd like to expand the [Usage API](https://www.elastic.co/guide/en/elasticsearch/reference/current/usage-api.html) to report usage stats of user profiles such as (1) number of enabled user profiles and (2) number of user profiles that are [activated](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-activate-user-profile.html) over the past X days. 

Response of the Usage API already contains a `security` field that groups relevant stats from security related features. We expect the new stats for user profiles should be added under it as well, for example:
```
{
  "security: {
    "user_profile": {
      "activated": 78,
      "recently_activated": 42  <1>
    }
  }
}
```
<1> The use of `recently_` is chosen to avoid the field to be tied to a specific time period so it is easier to evolve the definition in future.

**Comment by bytebilly** [comment]
Given the current approach of the Usage API, it seems that we don't provide stats over a period of time (even if this is one of the goals of a possible telemetry evolution) but just the picture of the current state.
There are a few fields for other features that may be incremental counters, but from the docs it's not clear if they are related to a fixed period of time (e.g. "last 24 hours") or an event (e.g. "since the last boot").

If we want to introduce the number of "recently_activated", we should understand which is our reference and make it consistent with what's already there (one way or the other).

I'd also make field names more consistent to track the difference between activated (existing) and enabled profiles. Something along these lines (similar to `role_mappings`):

```
{
  "security: {
    "user_profile": {
      "enabled": 42,
      "size": 78
    }
  }
}
```

What do you think?

**Comment by ywangd** [comment]
I noticed the existing usage stats uses field names like `size`. I don't particularly like it. It's the reason that I didn't suggest it. But I can definitely see the argument for being consistent. So I have no objection for reusing `size`.

As for `enabled`, existing fields with the same name are all of `boolean` type. It's the reason that I went for `activated`. Is it a concern?

**Comment by legrego** [comment]
Thanks for opening this issue, @ywangd.

I spoke with @arisonl today about the timeframe we'd want to see for `recently_activated`. We would both like @alexfrancoeur to give his thoughts on this, once he is back. If we don't have a decision in time to land this in 8.5, then we may decide to ship just `activated` by itself, and followup with `recently_activated` once we have a consensus.

Starting in 8.0, we have a default session lifespan of `30 days`, which means that we require users to re-login (and hence re-activate their profile) once every 30 days, unless an administrator has adjusted this value higher or lower. For this reason, having a `recently_activated` window of `30 days` might also be beneficial, but again, we'd like to discuss with Alex before finalizing this.

------

I don't have a strong opinion about the naming of these fields. I'm happy to defer to y'all on what you feel makes the most sense in the context of the broader Usage Stats payload.

**Comment by alexfrancoeur** [comment]
Sorry for the delay here, I just caught up on the slack thread. I touched base with the journey team and they measure most of their metrics in 30, 60 and 90 days. Any 30 day block would be good for them. Taking into consideration that the default session lifespan is 30 days and the journey team measures in blocks of 30 day increments, having `recently_activated` default to 30 days makes sense to me. 

As for naming, I don't have a strong opinion here. It is worth considering who the folks are that will be consuming these metrics and I'm not necessarily sure `activated` equates to `login count` at first glance. The data is what's most important to me. If a naming convention is up for debate, I'm happy to provide some suggestions, but if there are patterns we're already following it probably makes most sense to stick with those.

Throwing this out there as a suggestion

```
{
  "security: {
    "user_profile": {
      "recent_logins": 42,
      "total_logins": 78
    }
  }
}

```

**Comment by legrego** [comment]
> What are the metrics?  Candidates are (a) recent (b) enabled (c) total. We can have all of them or just one or two of them.

My vote is to include them all, if it won't materially impact the level of effort.

> What should they be called. I am happy with logins. It is easier to prefix it to mean different logins, e.g. recent_logins. Or we can be consistent with other existing metrics and use size. But it does not read well with prefix, e.g. recent_size? Or we can just drop logins or size altoghther and just use recent, enabled, total on its own. Or some mix between these options?

I have a weakly-held preference for just using `recent`, `enabled`, and `total`, but I'll defer to others if there are stronger opinions.
