### ISSUE TITLE
Doc website incorrectly displays Index/TOC in Chrome

### ISSUE THREAD

**Issue by roablep** [elastic/elasticsearch#89533]
### Elasticsearch Version

current

### Java Version

_bundled_

### OS Version

Mac

### Problem Description

This is an issue with the doc website not ES itself.
Table of Contents/index nav is unusable. 
Works fine in Safari, not Chrome. 
Disregard adblockers...issue persists even if they are disabled

<img width="1510" alt="Screen Shot 2022-08-23 at 8 43 49 AM" src="https://user-images.githubusercontent.com/1090728/186162061-2deb4e62-be7e-49d1-9ba7-b0461ef06aad.png">

### Steps to Reproduce

MacOS Monterey 12.5.1 
Chrome Version 104.0.5112.101

**Comment by debadair** [comment]
There were transient caching issues when the revised nav was introduced that likely caused this problem. If there are ongoing issues, you can raise an issue in https://github.com/elastic/docs.
