### ISSUE TITLE
Boolean field to support ignore_malformed

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#89542]
The `ignore_malformed` option is supported by a few of our field types, mainly numerics and dates, to still accept the document when such fields hold malformed values. See https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html. Also `ignore_malformed` is an index level setting that gets applied to all field types that support it. 

The boolean field type does not support `ignore_malformed` but it should, so that if a boolean field cannot be parsed as a boolean, the document can still be accepted.

**Comment by devnamrits** [comment]
Hello @javanna, I would like to start my contribution to elasticsearch from this issue. Can I pick this up??

cc: @elasticsearchmachine

**Comment by javanna** [comment]
Yes @devnamrits thanks for offering your help, feel free to open a PR around this. let us know if you need guidance.

**Comment by devnamrits** [comment]
Hi @javanna, Please assign this to me. I've built the project in my local and currently I'm going through the documentation. Also, it would be great if you can streamline things from the code point of view for this issue.

**Comment by devnamrits** [comment]
@javanna I've been working on it. I went through the test cases where you are testing the ignore_malformed. Can you please tell me where within code, ignore_malformed setting is enabled for currently supported data types. It would be really help as then I can deliver this fast if I get to know how { ignore_malformed: true } is being enabled for currently supporting data types.

**Comment by devnamrits** [comment]
@javanna Raised PR for this issue. #90122

**Comment by javanna** [comment]
@devnamrits thanks, I've seen it, I will review it. It will take me a few days to get to it though, thanks for your patience.

**Comment by devnamrits** [comment]
Hi @javanna Thank you for your kind reply. Let me know if changes are required.
Also it would be great, meanwhile, if you can assign me some other issue. Would love to pick them up.

**Comment by jem-n-em** [comment]
Hello, would you mind if I worked on this issue as well?  This will be my first open source contribution of any sort; I am (hopefully-understandably) a little nervous about contributions, but this issue and the elasticsearch project look interesting to me.

**Comment by devnamrits** [comment]
Hi @jem-n-em I've already raised PR for this. @javanna  is reviewing. So @javanna can tell whether you should pick or not.

**Comment by jem-n-em** [comment]
> Hi @jem-n-em I've already raised PR for this. @javanna is reviewing. So @javanna can tell whether you should pick or not.

oh I'm sorry, didn't see the conversation above, thank you anyways.

**Comment by khunt-miral** [comment]
Hi @javanna , I want to contribute in open source and I don't know from where to start so could you please help me to get started with open source and give any beginner friendly issues which I can solve.
