### ISSUE TITLE
[ML] Starting trained models with a ridiculously large queue_capacity crashes the node

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#89555]
### Elasticsearch Version

Found in 8.4.0

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 21.6.0

### Problem Description

Although unlikely, if a user tries to start a trained model deployment with a ridiculously large `queue_capacity` (for example `9999999999999`, the node that tries to allocate the model will immediately crash.

Furthermore, the node will continue to crash when restarted, as soon as the node attempts to allocate the trained model deployment.

### Steps to Reproduce

1. [Import a trained model](https://www.elastic.co/guide/en/machine-learning/master/ml-nlp-deploy-models.html#ml-nlp-import-model)
1. Start the trained model deployment with `queue_capacity=9999999999999`
1. Notice that the ML node that attempted to start the trained model deployment has crashed
1. Try restarting the node
1. Notice that the node continues the crash as soon as it tries to allocate the trained model deployment

### Logs (if relevant)

The Elasticsearch instance crashes immediately after logging the attempt to start the trained model deployment. No logs after that.

**Comment by dimitris-athanasiou** [comment]
I suspect the same issue exists for the `enrich.coordinator_proxy.queue_capacity` setting for the enrich plugin. Pinging @elastic/es-data-management .
