### ISSUE TITLE
I need help Thank you!

### ISSUE THREAD

**Issue by AccountGc** [elastic/elasticsearch#89569]
### Elasticsearch Version

Version: 7.12.1, Build: default/tar/3186837139b9c6b6d23c3200870651f10d3343b7/2021-04-20T20:56:39.040728659Z, JVM: 1.8.0_291

### Installed Plugins

ik,ingest-attachment

### Java Version

java version "1.8.0_291"

### OS Version

Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description
```
{
	"error": {
		"root_cause": [{
			"type": "parse_exception",
			"reason": "Error parsing document in field [content]"
		}],
		"type": "parse_exception",
		"reason": "Error parsing document in field [content]",
		"caused_by": {
			"type": "tika_exception",
			"reason": "Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser@3b5e180a",
			"caused_by": {
				"type": "array_index_out_of_bounds_exception",
				"reason": "351"
			}
		}
	},
	"status": 400
}
```

**Comment by DJRickyB** [comment]
Hello, for product help please visit https://discuss.elastic.co. We use Github issues for enhancement requests and confirmed product bugs.

Thank you
