### ISSUE TITLE
Snapshot deletion and creation slow down as number of snapshots in repository grows

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#8958]
In order to create a new snapshot or delete an existing snapshot, elasticsearch has to load all existing shard level snapshots to figure out which files need to be copied and which files can be cleaned. The number of files to be checked is equal to `number_of_shards * number_of_snapshots`, which on a large clusters and frequent snapshots can lead to very long operation times especially with non-filesystem repositories. See https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/150 and [this group post](https://groups.google.com/d/msg/elasticsearch/cXl9UrqgwBI/gEX0gSj2yqgJ) for examples of issues that this behavior is causing.

**Comment by nickcanz** [comment]
Just wanted to chime in, this issue has affected us a great deal as well. It made "sense" after I thought it through, how ES snapshotting works, but was an unpleasant surprise.

**Comment by niemyjski** [comment]
I seem to be seeing this behavior with azure blob storage after upgrading to 1.7.5

**Comment by imotov** [comment]
@niemyjski It was fixed in #8969 in 2.0.0 and above. The fix wasn't backported to 1.7.5.

**Comment by tamsky** [comment]
And, if you've read this far and were wondering if the fix for this might ever get backported to 1.x... the answer is apparently not:

@ https://github.com/elastic/elasticsearch/pull/8969#issuecomment-199348984 :  imotov says
> this was a significant change that required changing the snapshot file format and it was too big of a change for a patch level release. So we didn't port to 1.x and there are no current plans to do it.
