### ISSUE TITLE
Remove and/or/not in favour of `bool` filter

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8960]
Today we have the `bool` filter and the `and`, `or`, and `not` filters, which do the same thing but slightly differently.  Nobody knows when it is better to use one over the other, and they shouldn't have to.

We should deprecate the `and`,  `or`, and `not` filters in favour of the `bool` filter, and the `bool` filter should be made smart enough so that it can:

* execute fast filters (eg bitsets) before slow filters (eg scripts or geo)
* take the cost of each filter into account
* leapfrog with the query when appropriate

**Comment by jpountz** [comment]
If I understand correctly, the current state of the discusson is as follows:
 1. we need to fold advantages that tha and/or/not filters have to the bool filter
 2. we need to deprecate the and/or filters, and make their parsers generate a bool filter
 3. the discussion is still open whether `not` should be deprecated or not

**Comment by jpountz** [comment]
> We should deprecate the and, or, and not filters in favour of the bool filter, and the bool filter should be made smart enough so that it can:
>
>    execute fast filters (eg bitsets) before slow filters (eg scripts or geo)
>    take the cost of each filter into account
>    leapfrog with the query when appropriate


I was just thinking that if we manage to get something like https://issues.apache.org/jira/browse/LUCENE-6198 in Lucene, then we could probably just make the `bool`, `and`, and `or` filters parse to a BooleanQuery which will do the right thing.

**Comment by clintongormley** [comment]
@jpountz I'd still be in favour of removing `and` and `or`, just to reduce clutter.

**Comment by jpountz** [comment]
Sure, my point that this way we would make the right decision all the time. I'm also in favour of removing them - having several ways to do the same thing introduces confusion.
