### ISSUE TITLE
how to set elasticsearch in AWS ECS fargate

### ISSUE THREAD

**Issue by Nareshsam95** [elastic/elasticsearch#89638]
### Description

I have pull the image from dockerhub using ec2 machine and then push to ECR with that i create the ECS FARGATE. But my elasticsearch container got into exited state. I need a help on this.
Thanks in advance.

**Comment by DJRickyB** [comment]
Hi! For product help please visit https://discuss.elastic.co. We use Github issues for confirmed bugs and enhancement requests.
