### ISSUE TITLE
Warn when using deprecated syntax

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8963]
Currently, users have to read the release notes for every version to check what syntax/functionality has been deprecated. We should make it easier, by warning or even throwing an exception.

This can be controlled by the `deprecations` setting which accepts:

* `warn` - logs and returns a warning in the request body when deprecated syntax/functionality/end points  are used
* `error` - throw an exception when deprecated syntax/functionality/end points are used
* `ignore` - silently ignore deprecations

The default setting should be `warn`, to inform users during development of problems with their code.  The user can set it to `error` to be sure that they are catching all problems, and they can set it to `ignore` in production so that known usage of deprecated functionality does not obscure real problems.

**Comment by clintongormley** [comment]
Closed in favour of https://github.com/elastic/elasticsearch/pull/11033

**Comment by clintongormley** [comment]
Reopening.  We should always log deprecations (based on the deprecation logging settings).

For warn, we should add a "warnings" section to the response, which lists all warnings.  Strict throws an exception.

The `index.query.parse.strict` setting (see #11996) should be repurposed and renamed to `response.deprecations.level`, and should accept `ignore`, `warn`, `strict`.

The parse fields behaviour should be changed to collect deprecations, instead of throwing an exception, so that all warnings can be collected.

**Comment by nik9000** [comment]
I know we send a header when some usersIs this done or just partly done?

**Comment by clintongormley** [comment]
I think this can be closed now - we have enough tooling around deprecations

**Comment by javanna** [comment]
> The index.query.parse.strict setting (see #11996) should be repurposed and renamed to response.deprecations.level, and should accept ignore, warn, strict.

> The parse fields behaviour should be changed to collect deprecations, instead of throwing an exception, so that all warnings can be collected.

Did we do any of these? I hope we did and I missed them :)

**Comment by nik9000** [comment]
> The parse fields behaviour should be changed to collect deprecations, instead of throwing an exception, so that all warnings can be collected.

We did this one, but only in non-strict mode. It just collects deprecated stuff and sends `Warning` headers for them. I we're certainly talking about the other one in https://github.com/elastic/elasticsearch/issues/19552.
