### ISSUE TITLE
Use `parseField` to parse all parameter names

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#8964]
Much of the code for parsing parameter names looks like this:

```
                } else if (  "slop".equals(currentFieldName) 
                             || "phrase_slop".equals(currentFieldName) 
                             || "phraseSlop".equals(currentFieldName)) {
```

The `parseField` method already handles the parsing of alternatives (including camelCase and deprecated syntax).  It also provides a central point for warning when deprecated parameter names are used (see https://github.com/elastic/elasticsearch/pull/11033).

All existing code should be migrated to use `parseField`.

**Comment by markharwood** [comment]
As part of a mass tidy-up of the parse logic it would make sense to also add the expanded error reporting introduced in issue https://github.com/elasticsearch/elasticsearch/issues/3303 and related PR https://github.com/elasticsearch/elasticsearch/pull/7891

**Comment by MaineC** [comment]
Ran into a question when going through the query parsers:

Look at https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-ids-query.html - we've documented a query option called "type".

In the current implementation here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/IdsQueryParser.java we accept all of _type, types and type for the same parameter.

When switching to ParseFields I believe I need to promote one of the three as preferred parameter name. As per the docs it seems obvious this should be type.

In our tests here https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/index/query/IdsQueryBuilderTests.java#L99 we generate all alternate versions for the json representation of this query. Unfortunately when running with strict parsing enabled this will fail the test entirely.

Question @clintongormley am I right in assuming that there should really only be one name for the parameter, here the one that is documented?

Question @cbuescher

**Comment by MaineC** [comment]
@colings86 Updated your list of classes to touch here: https://gist.github.com/MaineC/2c630dea38077a2852cc

(clumsy bash command that generated the list on top of the gist, manually deleted references of aggregations and queries after running the command assuming #14249 and your aggregations refactorings fix those)

**Comment by dakrone** [comment]
I think this has been resolved with the query refactor? At least when I run @MaineC's script I no longer see any classes that need to be touched.

**Comment by javanna** [comment]
Not all queries were migrated to parse field while working on the query refactoring, only some were. Also, using parse field is necessary everywhere in our parsing code, not only in our queries. We should update the list and re-evaluate what needs to be done, but this can't be closed just yet ;)

**Comment by dakrone** [comment]
> We should update the list and re-evaluate what needs to be done, but this can't be closed just yet ;) 

I didn't see any more when using Isabel's script, maybe we need to update the script if there are other its missing?

**Comment by MaineC** [comment]
Looked at the bash thingy again - first of all it only checked stuff in core/*, second of all looking closer it looks like there's some copy'n'paste mix-up in there. Going through the code there still seem to be a few classes where we could be using ParseField, see below.

https://gist.github.com/MaineC/ce2bf46d228230a1f676037a40614112

**Comment by dakrone** [comment]
Thanks for coming up with the new list @MaineC !

**Comment by javanna** [comment]
That seems to mean that all queries have been migrated though, which I wasn't expecting. that's great!

**Comment by MaineC** [comment]
@javanna They should have all been covered as part of #14249 - unless we've overlooked some back then.
