### ISSUE TITLE
Add visitor and accessor support to the Java Query DSL

### ISSUE THREAD

**Issue by btiernay** [elastic/elasticsearch#8970]
## Visitors

When creating dynamic [query engines](http://hillside.net/europlop/HillsideEurope/Papers/EuroPLoP2004/2004_Wellhausen_QueryEngine.pdf) that use Elasticsearch as a storage / search backend, it would be incredibly useful to provide [visitor](http://en.wikipedia.org/wiki/Visitor_pattern) support for `FilterBuilder`, `QueryBuilder`, et al. to iterate over the query structure. This would allow general purpose AST transformations for a number of use cases:

- query translation from a custom language recognizer (e.g. from an ANTLR visitor / [listener](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Parse+Tree+Listeners))
- query canonicalization (standard forms for readability and debugging)
- query simplification (pruning semantically useless nodes (ex: `match_all: {}`, degenerate `should` / `must` clauses) for readability and debugging)
- query optimization (recognizing common patterns that could be transformed [using best practices](http://www.elasticsearch.org/blog/all-about-elasticsearch-filter-bitsets/))

## Accessors

Currently the `FilterBuilder`, `QueryBuilder`, etc. classes are "write only" in the sense that their contents cannot be accessed once built. It would be very useful to be able to access the various properties specific to each AST node as well as children and parent. This would enhance navigation / introspection of AST nodes while performing the types of processing  described in the "Visitors" section.

### CQL
One known example of this type of application is the [elasticsearch-sru](https://github.com/xbib/elasticsearch-sru) plugin by @jprante which translates [CQL](http://en.wikipedia.org/wiki/Contextual_Query_Language) into Elasticsearch queries. However, it seems as though this approach requires that the application create a [parallel AST](https://github.com/xbib/elasticsearch-sru/tree/master/src/main/java/org/xbib/query/cql/elasticsearch/ast) in order to support query translation.

### RQL
In our particular use case, we are intending to use a dialect of [RQL](http://www.sitepen.com/blog/2010/11/02/resource-query-language-a-query-language-for-the-web-nosql/) as a basis for encapsulating our query engine, insulating the user from the full power and complexity of the Elasticsearch Query DSL while protecting our infrastructure from resource intensive queries.

**Comment by btiernay** [comment]
@jprante  Any progress here?

**Comment by clintongormley** [comment]
Nothing seems to have happened for the last 11 months, during which major refactoring has happened in the way search requests are parsed.  Closing this for now.
