### ISSUE TITLE
Additional detail on the custom GeoIP Endpoint documentation

### ISSUE THREAD

**Issue by m-hoskin-unisa** [elastic/elasticsearch#89742]
The current documentation for using a custom GeoIP Endpoint is a bit unclear on the specific requirements for what value needs to be provided for the ingest.geoip.downloader.endpoint setting.
https://www.elastic.co/guide/en/elasticsearch/reference/8.3/geoip-processor.html#use-custom-geoip-endpoint

Currently the process lists:

> Specify the service’s endpoint URL in the [ingest.geoip.downloader.endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/geoip-processor.html#ingest-geoip-downloader-endpoint) setting of each node’s elasticsearch.yml file.

And for the cluster settings:
>ingest.geoip.downloader.endpoint
([Static](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/settings.html#static-cluster-setting), string) Endpoint URL used to download updates for GeoIP2 databases. Defaults to https://geoip.elastic.co/v1/database. Elasticsearch stores downloaded database files in each node’s [temporary directory](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/important-settings.html#es-tmpdir) at $ES_TMPDIR/geoip-databases/<node_id>.

However this doesn't detail that the endpoint URL needs to end with /overview.json. Instead it may be better to provide an example value the same way the Logstash documentation does:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html
>Specify the service’s endpoint URL using the xpack.geoip.download.endpoint=http://localhost:8080/overview.json setting in logstash.yml.

**Comment by grcevski** [comment]
I believe these are docs owned by the Geo team, please re-route if I made a mistake.

**Comment by nik9000** [comment]
It's actually part of `ingest node`
