### ISSUE TITLE
total hit count is wrong for exists query

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch#89760]
### Elasticsearch Version

8.4.1

### Java Version

_bundled_

### OS Version

macOs 10.15.7, Elasticsearch running in docker container

### Problem Description

I index 5 documents containing a minmal set of fields. One field is named `name` and for one of the docs it is empty (`""`) and for one it does not exist.

I then search for documents where this field exists. The returned hits a alright, but the value value in the total relation object is wrong. This worked in 8.3.3, but erros in 8.4.1

Expected behaviour: the total hit value is 4

Actual behaviour: the value of 3 is returned

### Steps to Reproduce

Post the following documents to `testindex`:

```
{
	"name": "name-1",
}

{
	"name": "name-2",
}

{
	"name": "name-3",
}

{
	"name": "",
}

{
	value: 42
}
```

send the following query:
```
POST /testindex/_search 
{
  "query": {
    "exists": {
      "field": "name"
    }
  }
}
```

This returns:
```
{
  "_shards": {
    "failed": 0,
    "skipped": 0,
    "successful": 1,
    "total": 1
  },
  "hits": {
    "hits": [
      {
        "_id": "4T0z9YIBgYaqNSSuHK8i",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-1"
        }
      },
      {
        "_id": "4j0z9YIBgYaqNSSuOK80",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-2"
        }
      },
      {
        "_id": "4z0z9YIBgYaqNSSuSq8F",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-3"
        }
      },
      {
        "_id": "5D0z9YIBgYaqNSSuX68P",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": ""
        }
      }
    ],
    "max_score": 1.0,
    "total": {
      "relation": "eq",
      "value": 3
    }
  },
  "timed_out": false,
  "took": 62
}

```

Although 4 documents are returned, the total value returned is 3.

This is a problem for me as I use queries with a size of 0 and track_total_hits set to true to do a count query. This now returns wrong results.

**Comment by stu-elastic** [comment]
I can reproduce this, thanks @sothawo

**Comment by stu-elastic** [comment]
It looks like d3b1a61f for a very odd reason.  In 8.4, the condition 
> } else if (query.getClass() == FieldExistsQuery.class && reader.hasDeletions() == false) {

passes, whereas in 8.3, the condition failed

> } else if (query.getClass() == DocValuesFieldExistsQuery.class && reader.hasDeletions() == false) {

Because it passes, the doc count comes from
`reader.leaves().get(0).reader().terms("name").getDocCount()`, which returns 3 in both versions.  So if the condition passed in 8.3, it would has return the incorrect hits, however it fails and uses the consequent branch of the conditional at 266
```
topDocsCollector = createCollector(sortAndFormats, numHits, searchAfter, trackTotalHitsUpTo);
topDocsSupplier = new CachedSupplier<>(topDocsCollector::topDocs);
totalHitsSupplier = () -> topDocsSupplier.get().totalHits;
```

which returns the correct count.
