### ISSUE TITLE
Support 8-bit integer values in `dense_vector`

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#89784]
Lucene recently added support for vectors with 8-bit integer values, in addition to the default of floats. This decreases the amount of memory needed to hold the vector data, and can slightly speed up searches.

Once it's released in Lucene, we should look into surfacing it in Elasticsearch. Maybe we would add a new mapping option called `element_type`. By default it would be `float`, but it could also be set to `byte`:
```
PUT index
{
  "mappings": {
    "properties": {
      "vector": {
        "type": "dense_vector",
        "dims": 96,
        "element_type": "byte",
        "index": true,
        "similarity": "dot_product",
      }
    }
  }
}
```

When `element_type: byte`, Elasticsearch would verify that all vectors fall in the valid 8-bit range [-128, 127). This applies to both indexing and querying.

Some questions:
* Would we want to support `element_type` even when vectors aren't indexed for ANN? In this case we use custom (non-Lucene) data structures, so it'd require extra work.
* Lucene uses the word "encoding", which we could consider this instead of `element_type`.

**Comment by jtibshirani** [comment]
@javanna this is a good question! Using `element_type` made sense to me, so it leaves flexibility in the future (we've seen half-precision floats used, as well as a single bit per element).

**Comment by mayya-sharipova** [comment]
I was also thinking if a user is confident in their data, can we skip validation phase at all? In this case indexing can be faster, as we don't need to parse vectors, we can just pass them a string when creating a Lucene `KnnVectorField`

```
new KnnVectorField(<field_name>, new BytesRef(<json_vector_string> ), similarity.function);
```

**Comment by jtibshirani** [comment]
I just noticed, we can also update the kNN search tuning guide (https://www.elastic.co/guide/en/elasticsearch/reference/8.5/tune-knn-search.html) to suggest trying `element_type: byte`. We might need to work with the ML team to come up with a concrete recommendation -- we discussed putting together an example in Python showing how to take a float vector and reduce it to byte precision.

**Comment by benwtrent** [comment]
This has been completed thanks to all the good work by @jdconrad
