### ISSUE TITLE
Can we select history source in peer recovery by settings When both Lucene soft-deletes and Translog are available

### ISSUE THREAD

**Issue by LiuDui** [elastic/elasticsearch#89787]
### Description

I seen  peer recovery  slow on translog stage sometimes. Ioutil of source node full intermittently. 
![image](https://user-images.githubusercontent.com/26088415/188093998-9c4ac3d0-abd9-4945-abb9-27db8a78b115.png)

We don't have much read/write tasks and from Jstack, we see source node use LuceneChange snapshot as history source which search document from segment.
![image](https://user-images.githubusercontent.com/26088415/188094169-9a5977d5-d7d3-4c3d-a3e4-fa769793f950.png)

So if want to keep soft delete enable, is there any way to use Translog as a HistorySource during recovery, or is there any risk if translog is forced used by some settings.

https://discuss.elastic.co/t/can-we-select-history-source-in-peer-recovery-by-settings-when-both-lucene-soft-deletes-and-translog-are-available/304203

**Comment by slobodanadamovic** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by LiuDui** [comment]
@slobodanadamovic Thanks for your replay. This does have a great impact on the cluster. Building translog operations from Lucene segment lead to high read IOPS, as a result, other query failed for timeout. I have try to ask this question from  [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) but get non answer. Could you please help to confirm this problem? It does cause the cluster to be very unstable, when the disk performance is low, such as HDD.
