### ISSUE TITLE
How to use scroll query with JDBC SQL

### ISSUE THREAD

**Issue by Zengweilu** [elastic/elasticsearch#89812]
### CI Link

JDBC SQL不支持scroll查询，能给个例子不

### Repro line

JDBC SQL不支持scroll查询，能给个例子不

### Does it reproduce?

Yes

### Applicable branches

JDBC SQL不支持scroll查询，能给个例子不

### Failure excerpt

JDBC SQL不支持scroll查询，能给个例子不

**Comment by fcofdez** [comment]
We reserve Github for confirmed bug reports and feature requests. I think your question is better suited for our forums at https://discuss.elastic.co/.
