### ISSUE TITLE
Add unique identifier to impacts,user actions, and indicators

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#89825]
Add URN identifiers to impacts, diagnosis, and TBD indicators. 

e.g. 

The  `shards_availability` diagnosis that the total shards per node setting is preventing
shards from allocating ( [ela.st/index-total-shards](http://ela.st/index-total-shards) )
will also return an `id` with value in the form of: 
`urn:elasticsearch:health:shards_availability:increase_shard_limit_index_setting`

Similar IDS will be provided for all the diagnosis and impacts.

**Comment by jbaiera** [comment]
Completed with #90072
