### ISSUE TITLE
warmers delete _all Exception

### ISSUE THREAD

**Issue by julianhille** [elastic/elasticsearch#8991]
If an index does not contain any warmers, the delete function does raise an exception.
This should fail with an info but not raise an exception right?!

curl 'http://localhost:9200/indexing/_warmers/_all' -X DELETE

{"error":"RemoteTransportException[[Kamehameha][inet[/192.168.1.11:9300]][indices:admin/warmers/delete]]; nested: IndexWarmerMissingException[index_warmer [[_all]] missing]; ","status":404}

**Comment by jpountz** [comment]
Agreed, tagged as an `adoptme`.
