### ISSUE TITLE
[CI-Failure] RecoveryWhileUnderLoadTests.recoverWhileUnderLoadWithNodeShutdown

### ISSUE THREAD

**Issue by c-a-m** [elastic/elasticsearch#8994]
http://build-us-00.elasticsearch.org/job/es_core_14_debian/1951/testReport/org.elasticsearch.recovery/RecoveryWhileUnderLoadTests/recoverWhileUnderLoadWithNodeShutdown/

I'm not able to reproduce this locally. It seems to be failing [on this line of the code](https://github.com/elasticsearch/elasticsearch/blob/master/src/test/java/org/elasticsearch/recovery/RecoveryWhileUnderLoadTests.java#L228)

**Comment by s1monw** [comment]
this hasn't failed in a long time.... closing
