### ISSUE TITLE
[GEO] Refactor unit test to follow correct naming and codeStyle convention

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#8998]
Per review of PR #8978 the following was noted:

1. the mixed camel underscore case of the GEO unit tests do not conform to the naming convention.
2. ```@Test``` annotation is unnecessary.

This issue is to document the need to refactor the Geo unit tests to conform to the correct naming and code style conventions.  Since this has impact on 'legacy' code, it is slightly bigger task than what is required for the scope of PR #8978

**Comment by clintongormley** [comment]
@nknize is this still relevant?

**Comment by javanna** [comment]
I think the `@Test` annotation is gone, as we removed all those in master. Problem solved. I tried to find what tests need to be refactored but I am not sure. @nknize can you shed light on this or close this issue if nothing needs to be done?

**Comment by javanna** [comment]
thanks for getting back to this @nknize !
