### ISSUE TITLE
starting issue

### ISSUE THREAD

**Issue by martin82dd** [elastic/elasticsearch#90001]
Hello,

I don't know why elastic doesn't want to start. 

OS : Centos 9

Logs : 

[root@server1 ~]# systemctl status  elasticsearch.service
× elasticsearch.service - Elasticsearch
     Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2022-09-12 13:24:41 CEST; 1min 11s ago
       Docs: https://www.elastic.co
    Process: 8155 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
   Main PID: 8155 (code=exited, status=1/FAILURE)
        CPU: 2.510s

Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:225)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:219)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1038)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:69)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         ... 10 more
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Sep 12 13:24:41 server1.centos systemd[1]: Failed to start Elasticsearch.
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Consumed 2.510s CPU time.
[root@server1 ~]# journalctl -u elasticsearch.service
Sep 12 13:20:19 server1.centos systemd[1]: Starting Elasticsearch...
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]: Exception in thread "main" org.elasticsearch.common.settings.SettingsException: Failed to load settings from [elasticsearch.yml]
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1194)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.node.InternalSettingsPreparer.loadConfigWithSubstitutions(InternalSettingsPreparer.java:126)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:52)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.cli.Command.main(Command.java:50)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]: Caused by: org.elasticsearch.xcontent.XContentParseException: [115:29] Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.newXContentParseException(JsonXContentParser.java:52)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:71)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:719)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1190)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         ... 7 more
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]: Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:225)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:219)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1038)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:69)
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]:         ... 10 more
Sep 12 13:20:21 server1.centos systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 13:20:21 server1.centos systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Sep 12 13:20:21 server1.centos systemd[1]: Failed to start Elasticsearch.
Sep 12 13:20:21 server1.centos systemd[1]: elasticsearch.service: Consumed 2.731s CPU time.
Sep 12 13:20:51 server1.centos systemd[1]: Starting Elasticsearch...
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]: Exception in thread "main" org.elasticsearch.common.settings.SettingsException: Failed to load settings from [elasticsearch.yml]
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1194)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.node.InternalSettingsPreparer.loadConfigWithSubstitutions(InternalSettingsPreparer.java:126)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:52)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.cli.Command.main(Command.java:50)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]: Caused by: org.elasticsearch.xcontent.XContentParseException: [115:29] Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.newXContentParseException(JsonXContentParser.java:52)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:71)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:719)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1190)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         ... 7 more
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]: Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:225)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:219)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1038)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:69)
Sep 12 13:20:52 server1.centos systemd-entrypoint[7477]:         ... 10 more
Sep 12 13:20:52 server1.centos systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 13:20:52 server1.centos systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Sep 12 13:20:52 server1.centos systemd[1]: Failed to start Elasticsearch.
Sep 12 13:20:52 server1.centos systemd[1]: elasticsearch.service: Consumed 2.836s CPU time.
Sep 12 13:24:39 server1.centos systemd[1]: Starting Elasticsearch...
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]: Exception in thread "main" org.elasticsearch.common.settings.SettingsException: Failed to load settings from [elasticsearch.yml]
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1194)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.node.InternalSettingsPreparer.loadConfigWithSubstitutions(InternalSettingsPreparer.java:126)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:52)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.cli.Command.main(Command.java:50)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]: Caused by: org.elasticsearch.xcontent.XContentParseException: [115:29] Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.newXContentParseException(JsonXContentParser.java:52)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:71)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:719)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:687)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1190)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         ... 7 more
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]: Caused by: com.fasterxml.jackson.core.JsonParseException: Duplicate field 'cluster.initial_master_nodes'
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:  at [Source: (ByteArrayInputStream); line: 115, column: 29]
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:225)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:219)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:456)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1038)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         at org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextFieldName(JsonXContentParser.java:69)
Sep 12 13:24:41 server1.centos systemd-entrypoint[8155]:         ... 10 more
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Sep 12 13:24:41 server1.centos systemd[1]: Failed to start Elasticsearch.
Sep 12 13:24:41 server1.centos systemd[1]: elasticsearch.service: Consumed 2.510s CPU time.

**Comment by kingherc** [comment]
Hi @martin82dd , Thanks very much for your interest in Elasticsearch. As the thread dump states: 

```
Sep 12 13:20:21 server1.centos systemd-entrypoint[7318]: Caused by: org.elasticsearch.xcontent.XContentParseException: [115:29] Duplicate field 'cluster.initial_master_nodes'
```

there is a duplicate field in the elasticsearch.yml file. Please check that file and remove one of them. This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this. Please also feel free to read the Elasticsearch documentation for the version you are using for help on configuration.
