### ISSUE TITLE
geo_shape filter should work on geo_point fields that have geohash/geohash_prefix enabled

### ISSUE THREAD

**Issue by hudsonb** [elastic/elasticsearch#9008]
Would it be possible for the geo_shape filter to support filtering fields mapped as geo_points which have geohash (and perhaps geohash_prefix) enabled?

I would like to use a geo_shape filter using an indexed geo_shape field to filter other documents that have a geo_point field but currently this is not possible. These geo_point fields have both geohash and geohash_prefix enabled which I *think* should make it technically possible to apply a geo_shape filter on them.

**Comment by natebrunette** [comment]
Has any work been done on this?  We need to create a field as a geo_point to do distance-based sorting, but we need a geo_shape (type: Point) to do boundary filtering.

Am I correct in this?  Is there any way to make this work?

**Comment by hudsonb** [comment]
You can do boundary filtering with geo_point using the geo_polygon filter, but this is significantly slower than a geo_shape filter (which does not work on geo_point fields).

**Comment by nknize** [comment]
@hudsonb @natebrunette with the 2.0 release there is now a ```points_only``` option in the ```geo_shape``` field mapper that optimizes performance for a points only ```geo_shape``` field. Performance is comparable to a ```geo_point``` field with ```geohash : true``` and you can use all of the same queries available for ```geo_shape``` types.

**Comment by hudsonb** [comment]
If I'm understanding correctly, I should change my fields which are mapped as geo_points to fields mapped as geo_shapes w/points_only?

Luckily for me, I can do this as I'm in the process of upgrading to ES 2.0 and we will be reindexing all of our data.

I still think the ticket is valid however. I haven't assessed the technical feasibility of it, but it seems if you have a geo_points field with geo_hashes enabled it may be possible to apply a geo_shape filter to it.

**Comment by mattjanssen** [comment]
Does geo_shape w/points_only allow for distance sorting? Like geo_point does?
