### ISSUE TITLE
Upgrade google-oauth-client for discovery-gce plugin

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#90126]
The same library is upgraded to [1.34.1](https://mvnrepository.com/artifact/com.google.oauth-client/google-oauth-client/1.34.1) for the repository-gcs plugin as part of #87800. It would be great to keep consistent and upgrade [its usage](https://github.com/elastic/elasticsearch/blob/3603aa71516b4d0e35ef41510ff8995a2580136c/plugins/discovery-gce/build.gradle#L13) in the discovery-gce plugin as well.

**Comment by jkakavas** [comment]
@jakelandis are there any blockers for https://github.com/elastic/elasticsearch/pull/91722 ? Looks like all tests passed the first time around
