### ISSUE TITLE
Aliases in templates with placeholders

### ISSUE THREAD

**Issue by korpa** [elastic/elasticsearch#9019]
I use logstash to add data in timebased indices like this:

```
log-id-<id>-day-2014.12.20
```

Currently templates just make use of the ```{index}``` placeholder which don't help me when I want to create aliases per Id per month automatically like:

```
log-id-<id>-month-2014.12
```

I also tried to find a solution via logstash and curator, but both are not flexible enough.

A solution would be something like:
```
{
    "template" : "log-id-*-day-*.*.*",
    "aliases" : {
        "log-id-{1}-month-{2}.{3}" : {}
    }
}   
```
If you add multiple wildcards in the template, you could use these as numbered parameters in the aliases definition.

**Comment by javanna** [comment]
Closing in favour of #5359.
