### ISSUE TITLE
`siem.savedQueryRule` is not registered error.

### ISSUE THREAD

**Issue by c-rolling** [elastic/elasticsearch#90273]
### Elasticsearch Version

v.8.4.0

### Java Version

_bundled_

### OS Version

Ubuntu 20.04.5 LTS

### Problem Description

**Expected Behavior:**
    Selecting a previously made "Saved Query Rule" opens up a pannel/page with details about that rule.

**Actual Behavior:**
    Selecting a previously made "Saved Query Rule" takes me to a new page with a error popup in the bottom right-hand corner that reads "Unable to load rules: Object type `siem.savedQueryRule` is not registered." (see image below). 
![Screen Shot 2022-09-22 at 11 52 15 AM](https://user-images.githubusercontent.com/113935499/191808119-e3fecc0c-724d-4af6-84e7-0dc4d15ca8f5.png)

To get back to the "Rules and Connectors" page, I first must click on a different page within the sidebar, go to it, and then click back on the "Rules and Connectors" page link. Clicking on the "Rules and Connectors" page without navigating elsewhere first changes the URL, but does not change the blank page that I am on.

I should mention that when I go to create a new event, the "Saved Query Rule" isn't even an option on the list. When I search for "query" the only two options that show up are "Elasticsearch query" and "Index threshold" (see image below).

![Screen Shot 2022-09-22 at 12 05 22 PM](https://user-images.githubusercontent.com/113935499/191808853-31f79ab8-9808-4b7c-a5e3-52d68d4b91ee.png)

### Steps to Reproduce

1. To reproduce, open the sidebar and select "Stack Management" under the "Management" heading.
2. From within the "Management" sidebar menu, select "Rules and Connectors" under the "Alerts and Insights" heading.
3. Find a "Saved Query Rule" that has been previously made (in my case by a coworker) and click on the name of the rule.
4. Observe error message as detailed above.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a Kibana question/bug report. Could you please create a new issue with the same content in the [Kibana repo](https://github.com/elastic/kibana/issues) instead? If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

I am going to close this issue in this repo; and thanks again for your interest and help.
