### ISSUE TITLE
Re-enable :qa:apm project

### ISSUE THREAD

**Issue by grcevski** [elastic/elasticsearch#90308]
### Description

The `:qa:apm` project was disabled entirely in https://github.com/elastic/elasticsearch/pull/90291. We need to work out a better way to enable this back for future releases. Some ideas on how to do this can be found here:

https://github.com/elastic/elasticsearch/issues/89340#issuecomment-1256059879

**Comment by pgomulka** [comment]
I am wondering if we could rewrite this test (or perhaps to have an additional one) and not use full docker images.
Instead we could write a java rest test that would have an fake apm server running (simple http server that allows to assert about messages received).
we have a similar test implemented for Metrics sent with apm agent https://github.com/elastic/elasticsearch/blob/main/test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/ApmIT.java#L60

While I see value in testing end-to-end with real components like in the current tracing apm it (real ES, real apm server shipping to real ES) but I think this test should belong to some e2e repo not elasticsearch.

@pugnascotia I wonder what you think about this?

**Comment by pugnascotia** [comment]
We only need to check that ES has managed to send its traces, not that that the APM server or anything else is working, so if we can throw away the Docker stuff and use a the fake APM server, that would be great.

**Comment by pgomulka** [comment]
we have the right coverage with integration tests in modules:apm now.
I suggest we close this
