### ISSUE TITLE
Master node return a error when Elastic upgrade from 6.8 to 7.10

### ISSUE THREAD

**Issue by qiujun623** [elastic/elasticsearch#90324]
When I upgraded Elastic to 7.10, the master node completed normally. After the Work node was upgraded, the master log showed the following error msg.  When I checked cluster health, I found that AVTIVE_SHARDS_PERCENT was pending at 81%:
`
{"error":{"root_cause":[{"type":"action_not_found_transport_exception","reason":"No handler for action [cluster:admin/xpack/enrich/coordinator_stats[n]]"}],"type":"failed_node_exception","reason":"Failed node [CU3Jc1eTSVysRfJzC4HxgA]","node_id":"CU3Jc1eTSVysRfJzC4HxgA","caused_by":{"type":"action_not_found_transport_exception","reason":"No handler for action [cluster:admin/xpack/enrich/coordinator_stats[n]]"},"suppressed":[{"type":"failed_node_exception","reason":"Failed node [ZDUBoBBZRv60-lvWvCzVfA]","node_id":"ZDUBoBBZRv60-lvWvCzVfA","caused_by":{"type":"action_not_found_transport_exception","reason":"No handler for action [cluster:admin/xpack/enrich/coordinator_stats[n]]"}}
`
  I used a configuration on the Work node: **stack.templates.enabled: false**, and I'm not sure if it had any effect

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). Specifically, both of the versions involved are long past [EOL](https://www.elastic.co/support/eol) and no longer supported so there's no action for the dev team to take here. If you can stop by the forums, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
