### ISSUE TITLE
elasticsearch does not provide configurable socket backlog

### ISSUE THREAD

**Issue by kaniini** [elastic/elasticsearch#9038]
hello,

we run a sizeable elasticsearch cluster on freebsd 10.  unfortunately, elasticsearch does not provide a configurable socket backlog for it's listeners, so this results in failures that do not happen on a similarly configured linux machine (but the linux machine runs systemd, and systemd makes me sad, so using RHEL 7 is not an option to us at this time).

the reason why is because many people incorrectly assume that linux's handling of `somaxconn` (see `listen(2)` manual page) is the correct behaviour, though it is not really.

for the time being we have deployed a freebsd kernel patch allowing us to override the hardcoded socket backlog length with one more appropriate for our environment.  other elasticsearch users on freebsd may find this patch here: http://turtle.dereferenced.org/~kaniini/fix-hardcoded-backlog-on-freebsd.patch.txt

we would like to not have to carry this patch on our systems since upstream has no interest in it (and rightly so), so that could be corrected by adding configurable socket backlog.  we would be happy to assist with this, if you could tell us which parts of the code need to be modified.

**Comment by clintongormley** [comment]
@spinscale or any ideas about configuring the listener backlog via netty?  This looks related: https://github.com/netty/netty/issues/2407

**Comment by kaniini** [comment]
that's interesting.  in this case, it may be possible to modify netty to check the sysctl table for the value, as it does on linux.

in the meantime, http://turtle.dereferenced.org/~kaniini/freebsd-somaxconn.patch is a patch that can be applied to enforce a desired SOMAXCONN for all processes on freebsd 10...

**Comment by spinscale** [comment]
setting the backlog seems to be a netty 4.0/1 feature only. I dont see anything that makes this work with netty 3.

**Comment by dakrone** [comment]
Now that we're on Netty 4 it sounds like this is possibly something we can accomplish, @spinscale do you know how to set it for Netty 4?

**Comment by spinscale** [comment]
So, what can be set is the `ChannelOption.SO_BACKLOG`, but not the somaxconn setting, as it is read by netty4 either from the proc file system or assumed 128 to be by default, but there is no explicit possibility to set this. Closing
