### ISSUE TITLE
ES should reserve file descriptors for cluster operations

### ISSUE THREAD

**Issue by kaniini** [elastic/elasticsearch#9039]
when ES runs out of file descriptors during a high CPU-use event, the entire cluster comes crashing down because nodes cannot reconnect to each other.

if a certain percentage of file descriptors were reserved for intra-node comms, this would not be an issue.

of course, this is not an excuse to justify incorrectly written code on the application layer.  obviously the application should not flood ES with junk, however, if an application may DoS the cluster to the point where cluster connections are timed out and have to be brought back up, then this is a problem.

**Comment by jpountz** [comment]
I don't think we can do much about it: there are so many ways that an application that has access to elasticsearch can bring a cluster down. File descriptors are only one out of many potential issues.
