### ISSUE TITLE
Basic Auth and SSO (SAML) for App Search

### ISSUE THREAD

**Issue by cpmohe** [elastic/elasticsearch#90424]
### Description

Currently Basic auth and SSO are not supported for App Search version 7.16.3. We tried 8.2, Basic Search is supported but SSO is not supported. Also, 8.2 App Search requires other clusters upgrade to 8.2 also. We have many use cases that require crawling SharePoint,  Confluence and other internal authenticates web sites. Looking for options to enable Basic Auth and SSO for the version 7.16.3.

**Comment by original-brownbear** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
