### ISSUE TITLE
[Feature Request] Support rolling restart via cluster commands

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#9046]
Since the cluster manages its own state, it has the best knowledge of how to perform rolling restarts. It will basically perform all steps outlined [here](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_rolling_restarts.html) but in addition it can probably be made to do this in a much smarter way to make sure nodes do not become too busy during the restart wherever possible (e.g. let nodes warm up before restarting another node containing same indexes and restarting another node in the meantime if possible).

This is a nice feature that exists in Hadoop (Cloudera Manager for example has a nice Rolling Restart UI button) and something that can definitely come in handy with ES.

**Comment by faxm0dem** [comment]
:+1:

**Comment by clintongormley** [comment]
We have removed the shutdown API so performing a rolling restart via the API won't be possible (the restart API was quickly removed because it suffered from issues).  However, we have made the restart process much smoother and faster than it used to be.

Closing
