### ISSUE TITLE
RPM init.d script does not pass CONF_FILE to ES

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9050]
The RPM init.d script makes use of `CONF_FILE` to verify that it exists, but then it does not pass that file onto the ES process.

https://github.com/elasticsearch/elasticsearch/blob/master/src/rpm/init.d/elasticsearch#L89

This should pass in the `es.default.config` setting along with the rest [to match the Debian init.d script's behavior](https://github.com/elasticsearch/elasticsearch/blob/master/src/deb/init.d/elasticsearch#L107) and [the Windows service launcher's behavior](https://github.com/elasticsearch/elasticsearch/blob/master/bin/service.bat#L146).

    -Des.default.config=$CONF_FILE

**Comment by clintongormley** [comment]
CONF_FILE has been removed
