### ISSUE TITLE
[Feature Request] Allow modifying the mapping for an existing field

### ISSUE THREAD

**Issue by janmejay** [elastic/elasticsearch#9052]
The proposal is to allow user to modify mapping of certain existing fields. I see atleast has 3 possible ways to do this:
1. Allow user to delete all documents that have that field populated, that is, != NULL, and then let the mapping be changed, so new mapping applies to documents indexed going forward.
2. Allow user to delete existing indexed data for the field(s) to be modified and apply new mapping for documents indexed going forward.
3. Allow user to re-index existing documents according to the new mapping for the field(s), and let new mapping be used for documents indexed going forward.

Also I am willing to get this implemented if we are convinced about the approach(either one of the options above or some totally different way).

Thoughts/Suggestions?

PS: I haven't checked feasibility/design-alignment of either of the approaches yet, so any details/corrections are welcome.

**Comment by clintongormley** [comment]
We talked through this at length and decided against going down this route.  It gets very complex indeed, especially when dealing with replication.

The way to do this in elasticsearch is to reindex, which will be made easier once we have the reindex API. https://github.com/elastic/elasticsearch/issues/492

Closing
