### ISSUE TITLE
Identify client for whom warning headers were dropped

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#90527]
Today if a client make a request that generates too many warning headers, Elasticsearch will log a warning message of the form `Dropping a warning header, as their total size reached the maximum allowed ...`. Elasticsearch typically adds warning headers because the client is doing something wrong, but the message doesn't identify the affected client, which makes it hard for users to investigate and address the problem.

Could we add some identifying information (address & port, user agent, ...) about the affected client to messages like these? Presumably we'd need to capture these things on the coordinating node and plumb them around the system via the thread context.

**Comment by mosche** [comment]
We briefly discussed this today, we're concerned about logging potentially sensitive information such as the address.
Would it help to add productOrigin and xOpaqueId to the mentioned logs? We'll have a look to see how feasible that is.

**Comment by lkwatciscodotcom** [comment]
Any information that does not compromise security has the potential to help with debugging.

From: Moritz Mack ***@***.***>
Date: Thursday, June 6, 2024 at 9:37 AM
To: elastic/elasticsearch ***@***.***>
Cc: Ladye Wilkinson (lkw) ***@***.***>, Manual ***@***.***>
Subject: Re: [elastic/elasticsearch] Identify client for whom warning headers were dropped (Issue #90527)

We briefly discussed this today, we're concerned about logging potentially sensitive information such as the address.
Would it help to add productOrigin and xOpaqueId to the mentioned logs? We'll have a look to see how feasible that is.
