### ISSUE TITLE
Slow index creation on MacOS

### ISSUE THREAD

**Issue by diachedelic** [elastic/elasticsearch#90568]
### Elasticsearch Version

8.4.2

### Java Version

_bundled_

### OS Version

Darwin 00236c87d925 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

### Problem Description

It takes several times longer to create an index (`PUT /my_index`) using the native MacOS build of ElasticSearch than the Docker container.

Creating several indexes at once takes several times as long as creating a single index, yet ElasticSearch's process does not seem to be CPU or memory bound. I would expect the MacOS build to create indexes much faster than the Docker container, seeing as the container is running in Docker Desktop's VM.

This is not a problem in production, but it is slowing down our automated tests in development.

### Steps to Reproduce

1. Download ElasticSearch from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.2-darwin-x86_64.tar.gz
2. Set `xpack.security.enabled: false` in config/elasticsearch.yml
2. Start elasticsearch with `bin/elasticsearch`
3. Run `time curl -XPUT localhost:9200/my_index`

Output:
```
$ time curl -XPUT localhost:9200/my_index4
{"acknowledged":true,"shards_acknowledged":true,"index":"my_index4"}
real    0m1.960s
```

4. Now, install elasticsearch using `docker pull elasticsearch:8.4.2`
5. Start container with `docker run -p 9200:9200 -e "xpack.security.enabled=false" -e "discovery.type=single-node" elasticsearch:8.4.2`
6. Run `time curl -XPUT localhost:9200/my_index`

Output:
```
$ time curl -XPUT localhost:9200/my_index3
{"acknowledged":true,"shards_acknowledged":true,"index":"my_index3"}
real    0m0.283s
```

**Comment by mark-vieira** [comment]
The root cause of this is that `fsync` performance on modern macs is quite slow and Elasticsearch (any many other databases) use this extensively for durability purposes. There's really not a whole lot we can do here and we have the same issue with slow test execution on Macs.

See: https://twitter.com/marcan42/status/1494213855387734019

**Comment by diachedelic** [comment]
Thank you for the explanation. For anybody who is interested, I am guessing that these are the hot lines of code:

https://github.com/opensearch-project/OpenSearch/blob/31a360fc87419cd3a6d5621754f8ad9e8819f1e8/libs/core/src/main/java/org/opensearch/core/internal/io/IOUtils.java#L301

https://github.com/openjdk/jdk/blob/master/src/java.base/macosx/native/libnio/ch/FileDispatcherImpl.c#L51

**Comment by diachedelic** [comment]
Commenting out every call I could find to the FileChannel's `force` method (which uses fsync under the hood) did not yield the performance improvement I was expecting. I should also note that I am using a Mac from 2012, not a modern one.

**Comment by mark-vieira** [comment]
> I should also note that I am using a Mac from 2012, not a modern one.

If that's the case then it's probably just a generally slow disk.

**Comment by diachedelic** [comment]
The disk seems fast in general, it is an SSD. Even so, slow hardware would not explain why index creation is slower for ElasticSearch for MacOS than it is for ElasticSearch for Linux running in a VM running on MacOS.

**Comment by mark-vieira** [comment]
It could certainly be something else but we're unlikely to investigate this further as MacOS is not an _officially_ supported platform. I agree, it does make local testing unnecessarily slow though.

**Comment by diachedelic** [comment]
I totally understand. I will report back if I discover anything.
