### ISSUE TITLE
wont start without configuration file only with -E options and  wrong error message

### ISSUE THREAD

**Issue by hillar** [elastic/elasticsearch#90575]
### Elasticsearch Version

8.*

### Installed Plugins

na

### Java Version

_bundled_

### OS Version

na

### Problem Description

wont start without configuration file only with -E options and  wrong error message: Skipping security auto configuration because it appears that the node is not starting up for the first time. The node might already be part of a cluster and this auto setup utility is designed to configure Security for new clusters only.
 

### Steps to Reproduce

start without configuration file only with -E options

### Logs (if relevant)

na

**Comment by pquentin** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
