### ISSUE TITLE
can not set node role to coordinating only on the command line

### ISSUE THREAD

**Issue by hillar** [elastic/elasticsearch#90578]
### Elasticsearch Version

8.*

### Installed Plugins

na

### Java Version

_bundled_

### OS Version

na

### Problem Description

```
bin/elasticsearch -Enode.roles=''

ERROR: setting [node.roles] must not be empty
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-node
> This means that a node that has an **explicit empty list of roles** via node.roles will only act as a coordinating node

### Steps to Reproduce

```
bin/elasticsearch -Enode.roles=''

ERROR: setting [node.roles] must not be empty
```

**Comment by slobodanadamovic** [comment]
@hillar To set node's role as coordinating only you have to pass `-Enode.roles="[]"`. This is possible since version 8.2.0 (see https://github.com/elastic/elasticsearch/pull/85186). If you are using version <=8.2.0, I suggest updating to the latest version.
