### ISSUE TITLE
[ML] Investigate how aggregate_metric_double fields affect data frame analytics

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#90590]
Since #87849 and #88534 it is possible that data frame analytics jobs will encounter the `aggregate_metric_double` type.

We need to investigate how this will affect certain aspects of their behaviour:

1. Copying mappings from the source index to the destination index
2. Explain API
3. How best to specify an `aggregate_metric_double` field as a data frame input field

Based on this investigation decide what changes we should make to either code or documentation.

**Comment by dimitris-athanasiou** [comment]
`aggregated_metric_double` fields are currently considered incompatible fields for DFA. If the field is used as the dependent variable the user will get an error:

```
required field [presum] is missing; analysis requires fields [presum]
```

If the field is intended to be just a feature then in the _explain api response we get:

```
...
{
            "name": "presum",
            "mapping_types": [
                "aggregate_metric_double"
            ],
            "is_included": false,
            "is_required": false,
            "reason": "unsupported type; supported types are [boolean, byte, double, float, half_float, integer, ip, keyword, long, scaled_float, short, text, unsigned_long]"
        }
...
```
