### ISSUE TITLE
Exchange versions during node handshake

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9061]
Introduce a handshake during transport connection where we validate that the other side is an ES node of the same cluster and exchange node versions for future communication. This will also allow us to extend APIs that are used during the initial cluster recovery (unicast ping) without waiting for a major version change.

**Comment by clintongormley** [comment]
@bleskes is this still relevant?

**Comment by bleskes** [comment]
yes. it is. Added an adopt me label.
