### ISSUE TITLE
Searches against a large number of unavailable shards result in very large responses

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#90622]
Searching a large number of unavailable shards through e.g. the `*` pattern while a large cluster is recovering from a full restart or so, leads to extremely large responses containing an exception for each shard.

![](https://user-images.githubusercontent.com/6490959/193701098-868888bc-cdc7-4104-a32a-d9c84d74aef2.png)

This example shows a 375M on heap response for ~25k unavailable shards being returned. Over the wire, this serialises with a similar size and we'd have 700M+ peak heap usage for a search request when the valid search response in a green cluster might be much smaller than this.
It seems to me that we could mostly resolve this by not returning the stack trace in this specific case of the shard not available exception (it doesn't seem valuable for users and we made a similar fix around unavailable shards in snapshots state responses)?

**Comment by benwtrent** [comment]
@original-brownbear 

It seems originally we did not record these failures at all but behavior was changed in: https://github.com/elastic/elasticsearch/pull/64337

So, it seems a good middle ground is as you said, let's not return the trace in these class of failures. 

Sounds fair?

**Comment by benwtrent** [comment]
Well, including unavailable shards as shard failures, but adjusting their exception serialization is a bit more complicated. 

Will need to discuss the best way to approach this.
