### ISSUE TITLE
TransportRolloverAction retains as many cluster state as there are rollover tasks waiting in a batch consuming too much memory

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#90620]
The way, the CS batching in `TransportRolloverAction` is written is broken for large batches of tasks. Each task result will contain the cluster state after applying the task. This consumes unmanageable amounts of memory for large cluster states if a larger number of rollovers gets batched, causing master nodes to run out of heap from endless `RolloverResult` getting retained.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/6490959/193704411-85979256-69bf-4db4-818e-f5d8d7888605.png">

We must find a way to not retain cluster states like this in the task results.

**Comment by DaveCTurner** [comment]
Ugh my bad, I introduced this in #84166 (8.2.0). Subtle stuff, not sure if there's a good way to protect against it. I opened #90626 with a fix.
