### ISSUE TITLE
Fix links to Apache HTTP Client doc

### ISSUE THREAD

**Issue by fdartayre** [elastic/elasticsearch#90630]
Links to the Java doc in the [Java Api Client documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.4/index.html) point to non-existing pages `https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/...`. 

For example in this [page](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.4/java-rest-low-usage-initialization.html), `HttpHost` link points to https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/HttpHost.html.

**Comment by satyamkale27** [comment]
I want to work on this issue

**Comment by abdonpijpelink** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/91945

**Comment by abdonpijpelink** [comment]
Thanks for spotting @fdartayre . I had missed that.

**Comment by ekrylovich** [comment]
Hello @abdonpijpelink and @fdartayre , 
I created PR to fix broken links. I also reviewed source code and aligned versions of classes in documentation with versions in dependencies. 
Please review it: https://github.com/elastic/elasticsearch/pull/92174

**Comment by ekrylovich** [comment]
Please inform me if I need to do something else with it.

**Comment by ekrylovich** [comment]
@fdartayre PR https://github.com/elastic/elasticsearch/pull/92174 was merged, so I believe issue can be closed. Feel free to ask if something is missed
