### ISSUE TITLE
Bind to localhost by default

### ISSUE THREAD

**Issue by kxepal** [elastic/elasticsearch#9064]
Current config says:

```
# Elasticsearch, by default, binds itself to the 0.0.0.0 address, and listens
# on port [9200-9300] for HTTP traffic and on port [9300-9400] for node-to-node
# communication. (the range means that if the port is busy, it will automatically
# try the next port).
```

Such default choice for binding interface is terrible and cause security issues. By default, newly installed ES shouldn't expose itself to the public unless it was configured for that. By this action, people approves that ES configuration is done and made properly to face terrors of the real world.

**Comment by jpountz** [comment]
Fixed via #11483
