### ISSUE TITLE
sample docker-compose.yml doesn't set kibana_system password

### ISSUE THREAD

**Issue by getorca** [elastic/elasticsearch#90658]
### Elasticsearch Version

8.4

### Java Version

_bundled_

### OS Version

ubuntu 22.04

### Problem Description

I noticed running the docker-compose.yml from https://github.com/elastic/elasticsearch/blob/main/docs/reference/setup/install/docker/docker-compose.yml and show in the documentation, that kibana can't connect and throws the following error:

`Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]`

However setting the kibana_system password manually by posting a request to update the password to `[HOST]/_security/user/kibana_system/_password` everything works as it should. So it would appear the kibana_system password is not getting set.

Expected behaviour:
kibana_system user password is set and everything works as expected. 

### Steps to Reproduce

run the docker compose as found in https://github.com/elastic/elasticsearch/blob/main/docs/reference/setup/install/docker/docker-compose.yml with appropiate .env settings

**Comment by ppumkin** [comment]
No.. because versions 8+ / 8.2+ ??
 I think now require a service account. And you need to do these stupid manual steps scroll in the logs to get a token that ES generates on first load only , then somehow put that into kibana somewhere with another special link.

This completely breaks docker composition and for sure makes "quick-start" a complete PITA!

**Comment by ppumkin** [comment]
I have dissected this yml file a bit - I am not sure why you are having problems. Maybe the "command" that is running is not setting the kibana user password properly. I ran the post request manually and everything spun up fine for me (on a much simpler compose file)

**Comment by mark-vieira** [comment]
You'll see the message above until the `setup` container completes it's job. Is that what you are observing or does Kibana never succeed?

**Comment by phamngocquy** [comment]
I face with same error, seem KIBANA_PASSWORD not effect

**Comment by mark-vieira** [comment]
> I face with same error, seem KIBANA_PASSWORD not effect

What's the error you are receiving? What version are you using?

**Comment by alcarraz** [comment]
> > I face with same error, seem KIBANA_PASSWORD not effect
> 
> What's the error you are receiving? What version are you using?

I have the same problem, version 8.5.3 using whats in https://www.elastic.co/guide/en/elasticsearch/reference/8.5/docker.html

**Comment by jackadam1981** [comment]
https://github.com/elastic/dockerfiles/raw/8.6/elasticsearch/bin/docker-entrypoint.sh

Docker entrypoint without kibana_ System.
Not familiar with elastic, unable to repair.

**Comment by jabulon** [comment]
> Well, in my case it seems it was because of this:
> 
> ```
> es01_1    | {"@timestamp":"2023-01-11T21:43:15.498Z", "log.level": "WARN", "message":"high disk watermark [90%] exceeded on [NW2WRv2JQSWeqOJ6eqQJeQ][es01][/usr/share/elasticsearch/data] free: 14.3gb[5.6%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor","elasticsearch.cluster.uuid":"eZQWTz-dSPW0VrrOu9rrtg","elasticsearch.node.id":"NW2WRv2JQSWeqOJ6eqQJeQ","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
> ```
> 
> Since mine is a development machine, I fixed it by addind this to the `setup` service `command`:
> 
> ```
>         curl -s --cacert config/certs/ca/ca.crt -u  "elastic:${ELASTIC_PASSWORD}" -X PUT "https://es01:9200/_cluster/settings" -H "Content-Type: application/json" -d"
>         {
>           \"transient\": {
>             \"cluster.routing.allocation.disk.watermark.low\": \"30mb\",
>             \"cluster.routing.allocation.disk.watermark.high\": \"20mb\",
>             \"cluster.routing.allocation.disk.watermark.flood_stage\": \"10mb\",
>             \"cluster.info.update.interval\": \"1m\"
>           }
>         }
>         "  
> ```
> 
> after the lines:
> 
> ```
>         echo "Waiting for Elasticsearch availability";
>         until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
> ```

Thank you @alcarraz !
This has resolved the same issue I had in 8.7

**Comment by mark-vieira** [comment]
These docs have been reworked and we now set the kibana system password.
