### ISSUE TITLE
Random sort in regular sort and not just in function_score

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#90652]
### Description

Currently random sort is possible only through function_score which augments existing sorting value into a new value. But one advantage regular sort has is that it can be an array of sorting descriptions. In my use case I would like to use seeded random sort to break ties between results which have the same score. This is currently possible with function_score by [adding a small random value to break ties](https://stackoverflow.com/a/65688680/252025) but the issue is that the small value can still influence the original order between results which do not have exactly the same score, but differences are just very small.

I would propose that the following would be possible:

```
{
    "query": {....},
    "sort": [
        "_score",
        "_function": {
          "random_score": {
            "seed": 10,
            "field": "_seq_no"
          }
        }
    ]
}
```

So special keyword `_function` would introduce a way to use a sorting function which would then be used in sorting specification. So this would first sort by `_score` and only if score is exactly the same, a random value would be used.

This could be beneficial also because random score could be computed only when needed (when comparing two results with same score) and not for all results, like what is needed by function_score.

**Comment by mitar** [comment]
I have two use cases which [I described in more detail here](https://gitlab.com/peerdb/search/-/issues/1), but to explain:
* One use case is that I would like to randomly change the order of results which have the same score, and I would like that is seeded and stable, so that if user retries the query, for that particular user (because it is seeded based on the user) they get the same order. One thing to consider in my case is that I want users to be able to "save" the search and if they open it later I would want that they get results as close to what they had initially. So if there is random ordering, it should be possible to get the same order. This is why I am interested in using `_id` as input to the random order, which seems to have its own issues.
* A special case of that is if score is 0 for all documents and one is getting all documents in the index as results. For that I would like to return to the user only random 1000 results. But again, seeded and possibly to get the same 1000 results at a later time for stored search queries.

My experience with `function_score` is that it is very slow. For example, a query over 160 million documents take with sorting on `_score` around 3 second for me, but with adding random small noise with `function_score` to scores, it takes 50 seconds to me (I used `_seq_no` as field, and I could not use `_id` because it triggered the circuit breaker). That is simply too slow, just to get 1000 random, but stable and reproducible results (given seed).

To me the second use case is more important and the first use case is a good to have. But I was hoping that having a random sort could improve performance here.

**Comment by javanna** [comment]
@mitar If generating the random score is what slows things down would it be a possibility to do that only for a subset of the documents. I would imagine that you have other queries that documents need to match. Could you use a rescorer for this?

**Comment by mitar** [comment]
Oh, the main use case for me is to have a random sample when there is no other filter/query to limit results down (which generally do add to score). So when user just wants to see some results, but there is no restrictions on which, I would like to show like 1000 of results. I tried random sampling for that, but it does not support limiting based on the result size (#90670).

**Comment by javanna** [comment]
Ok thanks for the context. I still don't follow how random sort, which you asked for above, would be faster than function score. After all, wouldn't you need to compute the random score for all documents anyways? That feels like the root of the problem and I am not sure there is a way around it other than reducing the set of documents that you compute the random score for.

**Comment by benwtrent** [comment]
@mitar 

> I tried random sampling for that, but it does not support limiting based on the result size (https://github.com/elastic/elasticsearch/issues/90670).

For context.

One issue here is that sampling based on size creates biases in how representative each shard is in the sample.

If you said "I want 1000 results for each shard", but one shard only had 1000 documents, this would mean the shard is over represented. This is troublesome if shards contain documents with statistically similar values (which is possible depending on index sort or ingest behavior).

I will comment on that issue.

**Comment by mitar** [comment]
> I still don't follow how random sort, which you asked for above, would be faster than function score. After all, wouldn't you need to compute the random score for all documents anyways?

OK, I have to clarify here because yes I tried initially to approach two use cases with the same approach:

* First use case is that I have search results where many many results have a different score but only few have score the same and I want to randomize (in a deterministic fashion based on seed) how those documents with the same score are ordered. This is what really this issue is about. You have 99% of documents with different score and my current naive approach is to use function_score with small noise to effectively randomize that 1% while hoping that I will not change order of the rest. But this is very slow and this is why I got an idea that it would be nice if I could compute random score only for the 1%. Which is this issue.
* Then I thought that the same feature could also be used when there is no query so all documents have the same score, because that would be neat as I could just make always the same request to ES (only now it would be 100% of documents to add this random score to). So it is a simpler implementation for me, but as you note, this would be as slow as current function_score approach. So it is not really viable. #90670 is probably a better approach in this case.

**Comment by mitar** [comment]
I have not tried with runtime field, only with function_score. I think you are right that using runtime field might be faster because it would run the tie breaking function only in cases when there is a tie. I will have to try it out.

> I was wondering about how this would work if you add or remove a document from the index?

Yes, in this case the order could change. I think it would be hard to prevent that. I mean, maybe there could be some way to simple ignore new documents.

I am realizing this is really a hard problem to solve with not many solutions in existing database technologies. The problem I am realizing I am trying to solve is escaping the filter bubble. So if you have a full text search which produces a score or some other similarity function then sorting by that score is fine. Tie breaking improves things a bit but it is generally rare on large datasets.

But if you want to just filter results (e.g., show me all results which are images), then in which order you show those results matter and to improve experience and to break out of the filter bubble I would like to show results in a random order. But if user reloads the page the order should not change (so I use and store the seed for the session).

Now the issue is that if the user adds additional filter (e.g., images which are larger than 1024px), the original random order should be preserved, only some results should be filtered out.

This is why I think sampling does not help here. It is really that I need seeded random sorting. But to me it is really surprising that it is slower than sorting by the full-text search score. I mean, both values have to be computed and then sorted on, so why it is random function so slow?

Because of this I am thinking of introducing 16 random 8-bit number fields for each document (so a 128 bit number all together) where I would then sort by these 16 fields, where based on the seed I would select the order in which I list those fields. I think that would give me 16! different sorting orders. Not sure how efficient such sorting by 16 fields would be though.

**Comment by javanna** [comment]
We have discussed this with the team and provided advice. We don't plan on adding support for random sorting, hence I am closing this issue.
