### ISSUE TITLE
[CI] SnapshotBasedIndexRecoveryIT testNodeDisconnectsDoNotOverAccountRecoveredBytes failing

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#90665]
**Build scan:**
https://gradle-enterprise.elastic.co/s/n2rdnntuvhw64/tests/:x-pack:plugin:snapshot-based-recoveries:internalClusterTest/org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT/testNodeDisconnectsDoNotOverAccountRecoveredBytes

**Reproduction line:**
`./gradlew ':x-pack:plugin:snapshot-based-recoveries:internalClusterTest' --tests "org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT.testNodeDisconnectsDoNotOverAccountRecoveredBytes" -Dtests.seed=2725E4BEF73A48D3 -Dtests.locale=sr-Latn -Dtests.timezone=Turkey -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT&tests.test=testNodeDisconnectsDoNotOverAccountRecoveredBytes

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([2725E4BEF73A48D3]:0)

```

**Comment by fcofdez** [comment]
Looking into the logs I noticed that we retry the first snapshot file download, while the test expects to bail out right away, see:
```
  1> org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:23743][internal:index/shard/recovery/restore_file_from_snapshot]
  1>    Suppressed: org.elasticsearch.transport.NodeDisconnectedException: [node_t2][127.0.0.1:23743][internal:index/shard/recovery/restore_file_from_snapshot] disconnected
  1> Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: runtime_exception: java.lang.InterruptedException
  1>    at org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT$1.read(SnapshotBasedIndexRecoveryIT.java:1334) ~[internalClusterTest/:?]
  1>    at org.elasticsearch.index.snapshots.blobstore.SlicedInputStream.read(SlicedInputStream.java:81) ~[elasticsearch-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
  1>    at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
  1>    at org.elasticsearch.index.snapshots.blobstore.RateLimitingInputStream.read(RateLimitingInputStream.java:62) ~[elasticsearch-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
  1>    at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
  1>    at org.elasticsearch.index.snapshots.blobstore.RateLimitingInputStream.read(RateLimitingInputStream.java:62) ~[elasticsearch-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
```
The suppressed exception comes from the first try.

I _think_ that the clock used to compute the timeout does not provide enough granularity to use `1ms` as the timeout, it uses the cached clock. I'll open a fix.
