### ISSUE TITLE
Random sampling based on the size of the result set and not probability

### ISSUE THREAD

**Issue by mitar** [elastic/elasticsearch#90670]
### Description

Currently, random sampling aggregation takes probability and creates a result set of documents included based on that probability. What I would like instead is that I could specify target result set size (number of documents in the result set) and sampling would then sample this number of documents.

My use case for this is that I would like to offer my users a "random result" experience, but not really just one, but like 1000 of them, for them to see (like, show me 100 random photos). Current approach of using random score function is in fact pretty slow when you have 100s of millions of documents, because it has to attach a random score to each of them, sort them, and then pick top 100 (or 1000). I would hope random sampling would be much faster, when you need like only 100 random documents from 100 million of documents.

So I know the final number of results I want to display, but I do not know the number of input documents into sampling. Currently, I would have to make two queries, first query to get the number of documents matching the query, and then run another query with random sampling aggregation with probability set based on previous count to get around target number of documents. But that would never really be exactly the target number. So having a dedicated way to set this number would be really beneficial.

**Comment by benwtrent** [comment]
> Currently, I would have to make two queries, first query to get the number of documents matching the query, and then run another query with random sampling aggregation with probability set based on previous count to get around target number of documents. But that would never really be exactly the target number. So having a dedicated way to set this number would be really beneficial.

You could do TWO randomly sampled calls. One with an smaller probability, then another adjusting the probability to account for getting at least the number of documents you want.

The key issue is that sampling is done per shard. Consequently, requiring a minimum number of documents matched per shard could introduce unwanted biases in the resulting set. 

If you said "I want 1000 documents", and per shard we get "1000" docs, it is possible for tiny shards (only about 1000 docs) are over sampled compared to larger (1m+ docs). This is a bad idea if you want your sample to be representative of the whole population of documents.


There may be a way to account for the bias, some thought will be needed here...

**Comment by mitar** [comment]
My feature request is about how the API would look like and not that implementation would then just forward this to shards as you describe as this has bias issues you mention. Internal implementation wise I was more thinking that this would do count + compute probability in one call. So currently I could approximate this call by first counting the number of documents in the result and then computing probability based on the target set size. But this would have some increased latency as I would have to do two API calls to ES. So ideally this could be done in just one call.

So first counting documents and then computing probability would also work across shards. But I am not sure how much is gained if this is done internally inside ES vs. me doing two API calls to ES.

**Comment by JVerwolf** [comment]
@benwtrent I was thinking about your comment
> There may be a way to account for the bias, some thought will be needed here...

Conceptually, at least, I think this could be done as follows: 
Suppose we want 100 random docs from an index of size 250 with  `shard_a` containing 200 docs and `shard_b` containing 50 docs. 

If we know the size of the index and the size of each shard from the DFS phase, we can create a "plan" for random querying. First we sample 100 numbers in 250, then count the occurrences between 1-200 for `shard_a` (call this `count_a`) and 201-250  for `shard_b` (call this `count_b`).  We then make a request to `shard_a` where we sample `count_a` random numbers within the range of the shard's size of 200.  We store these as a sorted list, and fetch the doc at each position. Likewise for `shard_b`.

This allows truly random sampling for a specified number of docs, even allowing the random possibility of not fetching any docs from a given shard.

**Comment by mitar** [comment]
@JVerwolf This looks good. But it it not something user can do today, because we do not have access to each individual shard? It is something ES would have to do internally? Or expose somehow?
