### ISSUE TITLE
When using must not clause and should clause together, setting minimum_should_match = 0 does not work.

### ISSUE THREAD

**Issue by eoghks0521** [elastic/elasticsearch#90737]
### Elasticsearch Version

7.2

### Java Version

11

### OS Version

ubuntu

### Problem Description

Hi, This is daehwan working as a search developer
While creating a search query, I found out that there was a query that worked differently than I intended, so I shared it with you.
I may be mistaken because I lack knowledge, but please check.

If I use 'must not' clause and 'should' clause together, minimum_should_match=0 setting won't work as expected. It seems like when minimum_should_match variable is smaller than 1, it is changed to 1.

But currently I'm trying to make a query that increases the score of the documents that are excluded by 'must not' clause, but matches the 'should' clause by setting minimum_should_match into 0 (which I can't due to issue above). Can you check if this is bug?

Thanks in advance

### Steps to Reproduce

`
{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "id": {
              "value": "1"
            }
          }
        }
      ],
      "should": [
        {
          "term": {
            "id": {
              "value": "2"
            }
          }
        }
      ],
      "minimum_should_match": 0 // not working -> thought to be replaced by 1.
    }
  }
}
`

**Comment by javanna** [comment]
Hi @eoghks0521 , 

> I'm trying to make a query that increases the score of the documents that are excluded by 'must not' clause

this is not supported, must_not clauses are executed in a filter context, hence they don't contribute to scoring, see the [boolean query docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html). This behaviour is inherited from the underlying Lucene (see [javadocs](https://javadoc.io/doc/org.apache.lucene/lucene-core/latest/org/apache/lucene/search/BooleanClause.Occur.html)): 

_Use this operator for clauses that must not appear in the matching documents. Note that it is not possible to search for queries that only consist of a MUST_NOT clause. These clauses do not contribute to the score of documents._
 
This is also the explanation for the `minimim_should_match` being adjusted to `1`, similar to the previous discussion in #52735, with the only difference being that you do have a must not and it's suprising that is not seen as a mandatory clause. I will raise this for discussion with the team.

**Comment by javanna** [comment]
We discussed with the team and we were not clear on what you are trying to achieve:

>  I'm trying to make a query that increases the score of the documents that are excluded by 'must not' clause

Must not is treated as a filter. Documents that are filtered out are not returned and not scored. We were joking with folks that a more intuitive name would be `filter_not`. As surprising as it is, this is the expected behaviour hence I am closing this issue.
