### ISSUE TITLE
Rollup tests (:x-pack:plugin:rollup:test) are failing

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#90751]
### CI Link

https://gradle-enterprise.elastic.co/s/sw5gt4d265ona

### Repro line

./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.RollupResponseTranslationTests.testUnsupportedMetric" \   -Dtests.seed=C0E3FFEC5FB68BC0 \   -Dtests.locale=cs-CZ \   -Dtests.timezone=Arctic/Longyearbyen \   -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

10:38:04 org.elasticsearch.xpack.rollup.RollupResponseTranslationTests > testUnsupportedMetric FAILED
10:38:04     java.lang.AssertionError: 
10:38:04     Expected: an empty collection
10:38:04          but: <[LEAK: resource was not cleaned up before it was garbage-collected.
10:38:04     Recent access records: 
10:38:04     Created at:
10:38:04     	org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:32)
10:38:04     	org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:72)
10:38:04     	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:525)
10:38:04     	org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:537)
10:38:04     	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus$HyperLogLog.<init>(HyperLogLogPlusPlus.java:211)
10:38:04     	org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus.<init>(HyperLogLogPlusPlus.java:75)
10:38:04     	org.elasticsearch.search.aggregations.metrics.CardinalityAggregator.<init>(CardinalityAggregator.java:75)

**Comment by idegtiarenko** [comment]
Duplicates: https://github.com/elastic/elasticsearch/issues/90661
