### ISSUE TITLE
[CI] StableBuildPluginPluginFuncTest can scan and create named components file failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#90793]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3zut2ls7dbaeo/tests/:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file

**Reproduction line:**
`null`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest&tests.test=can%20scan%20and%20create%20named%20components%20file

**Failure excerpt:**
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477 with arguments [:assemble, -Dtest.external=true]

Output:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle' line: 13

* What went wrong:
Could not compile build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle'.
> startup failed:
  build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle': 13: Unexpected character: '\'' @ line 13, column 38.
                     implementation files('C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\jars\plugin-api.jar')
                                          ^
  
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 129ms

  at org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.test.ConfigurationCacheCompatibleAwareGradleRunner.build(ConfigurationCacheCompatibleAwareGradleRunner.java:153)
  at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:147)
  at org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest.can scan and create named components file(StableBuildPluginPluginFuncTest.groovy:99)

```

**Comment by craigtaverner** [comment]
Several new failures today:

* https://gradle-enterprise.elastic.co/s/rjwxyhw6w4olu/tests/:build-tools:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file?top-execution=1
* https://gradle-enterprise.elastic.co/s/uamwm4bmvsiju/tests/:build-tools:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file?top-execution=1
* https://gradle-enterprise.elastic.co/s/q2722t5rvhw2y/tests/:build-tools:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file?top-execution=1
* https://gradle-enterprise.elastic.co/s/oouetr2odr2sm/tests/:build-tools:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file?top-execution=1
