### ISSUE TITLE
What is Elastic Observability & how to get started?

### ISSUE THREAD

**Issue by bshetti** [elastic/elasticsearch#90817]

**Comment by dliappis** [comment]
Hey @bshetti you can take a look at https://www.elastic.co/guide/en/observability/current/observability-introduction.html and https://www.elastic.co/observability

However, this appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
