### ISSUE TITLE
[REST API] «/<index_name>-*/_status» + «curator» ≈ massive data loss

### ISSUE THREAD

**Issue by linux01d** [elastic/elasticsearch#9081]
curator 1.0.0 still uses «localhost:9200/<index_name>-*/_status», which is deprecated in ES 1.2.0
Anyway, ES has a bug in /<index_name>-*/_status — it returns the list of ALL indices if wildcard doesn't match to any index and this may lead to data loss if curator takes a list of all existent indices and attempts to remove them.
In our installation we have lost 40T of data when last index named «intape-logstash-YYYY.MM.DD» has gone by the next time cron started job «curator -p intape-logstash- -C space -g1000».

**Comment by bleskes** [comment]
I did some research here. The problem seems to lie in a collision between APIs of lower components. The  `MetaData#concreteIndices()` method takes a list of wildcards/aliases/index names and resolves it to a concrete list of indices to operate on where an empty return means nothing is to be done.  The _status API (which is deprecated btw) and the _recovery API both pass this list to `RoutingTable#allAssignedShardsGrouped` which interprets an empty list to mean all of the indices. Gut feeling says the latter should change and return no shards (because it was *probably* not updated when the `IndexOptions` mechanics were introduced) but it's a deep component - we need research the implications.

**Comment by cbuescher** [comment]
Starting to look into this one. Since I'm not familiar with the _recovery api so far I started there and just saw that from the example about also

GET /vfoobar/_recovery?ignore_unavailable=true
returns the full list of indices.

**Comment by cbuescher** [comment]
Removing the expansion of empty list of indices in RoutingTable#allAssignedShardsGrouped solves the problem for the `_recovery` endpoint, but I'm not sure what the implications are for other operations using that method. From what I see so far these are

* TransportRefreshAction
* TransportIndicesStatsAction

Not sure if the semantics of "empty indices" can mean "all indices" in these cases.

An alternative on changing the RoutingTable implementaion would be to set always set the RecoveryRequest "allowNoIndices" option to false. In that case when after expanding wildcards no index is matched we throw an IndexMissingException in MetaData#convertFromWildcards.

There are also at least four other places in RoutingTable where empty index lists are expanded like:
```
if (indices == null || indices.length == 0) {
            indices = indicesRouting.keySet().toArray(new String[indicesRouting.keySet().size()]);
}
```
Not sure if all of these should be looked at. I experimentally tried removing all of them but got some test failures after that, so it seems to depend on context when empty index list as input should be treated as "all" or "none".

**Comment by cbuescher** [comment]
I had a closer look at how the index wildcard pattern get resolved to concrete indices in `MetaData#concreteIndices()`. 
If it would be 100% sure that any input that could means "all indices" (that is: null or empty String[] or "_all") resolves to concrete list of names, then any empty list that is returned from that method would actually mean that there actually really is no indices or aliases for that input. Then in Routingtable we could get rid of handling the cases where indices=null / empty are treated like "all". 
I think that is almost the case already. If wildcard-expansion is on (for open or closed) then the "_all" case is sure to be resolved in `MetaData#concreteIndices()`. I think there are some edge cases where `MetaData#concreteIndices()` with empty input index names can lead to NPEs (when both expand_open, expand_closed) are false. Not sure if those cases should be allowed at all?

**Comment by cbuescher** [comment]
I pushed a version where I removed the empty list expansion from the RoutingTable to https://github.com/cbuescher/elasticsearch/commit/5f52f9bc57094bc8703f522738ec562ae0313f57
Fixed all tests to pass there, not sure if I should open a PR for discussion?
