### ISSUE TITLE
thirdPartyAudit failure on analysis api plugin

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#90862]
### CI Link

https://gradle-enterprise.elastic.co/s/ssqkx6qintb4a

### Repro line

n/a

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath! |  
-- | --
  | ==end of forbidden APIs== |  
  | Missing classes: |  
  | * java.lang.foreign.MemorySegment |  
  | * java.lang.foreign.MemorySession |  
  | * java.lang.foreign.ValueLayout |  
  | * java.lang.foreign.ValueLayout$OfByte |  
  | * java.lang.foreign.ValueLayout$OfFloat |  
  | * java.lang.foreign.ValueLayout$OfInt |  
  | * java.lang.foreign.ValueLayout$OfLong |  
  | * java.lang.foreign.ValueLayout$OfShort
```

It looks as though forbidden APIs can't load the preview classes in the lucene MR-JAR

**Comment by ywangd** [comment]
Failed again on main https://gradle-enterprise.elastic.co/s/fcmlasitvunoy

**Comment by fcofdez** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/h5mvx53aymyrw

**Comment by breskeby** [comment]
This seems like a duplicate of https://github.com/elastic/elasticsearch/issues/91264
