### ISSUE TITLE
RangeQueryBuilder does end an object twice

### ISSUE THREAD

**Issue by nicenemo** [elastic/elasticsearch#90867]
### Elasticsearch Version

7.x

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

`RangeQueryBuiler.doXContent(...)`  performs an `endobject` twice.
Solution: remove one call to `endObject`.

## Context

We generate a Query in Java with the RangeQueryBuilder. This code generates deprecated queries using ,` from`/`to` etc.
I investigated whether it was possible to let the code generate the more modern `lt`, `gt` etc by decompiling and browsing the code of ` RangeQueryBuilder`. This confirmed that that was not possible. I confirmed that this code was still present in the current version of `RangeQueryBuilder` on github.  

 Need a merge request for this one?

### Steps to Reproduce

Look at the source code on Github  [RangeQueryBuilder.doXContent(...)]( https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L339) 

```Java
@Override
    protected void doXContent(XContentBuilder builder, Params params) throws IOException {
        [...]
        builder.endObject();
        builder.endObject();
    }

```

**Comment by benwtrent** [comment]
This is because of higher up the call chain: 

https://github.com/elastic/elasticsearch/blob/a2615289b3ceb952b05cc01ec260833c26683bd5/server/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L308-L309

If this were broken, serialization and deserialization would not work at all. Is that what you are seeing?

**Comment by nicenemo** [comment]
Nope, I missed that one. looked like some past autmatic merge that might have been missed.  I was a bit too new to this part of the code base I gueess.

Closing.
