### ISSUE TITLE
primary_interface map empty

### ISSUE THREAD

**Issue by jasperla** [elastic/elasticsearch#9087]
The following output from my OpenBSD host on `_nodes` is incorrect:

```
     "network" : {
        "refresh_interval_in_millis" : 5000,
        "primary_interface" : {
          "address" : "",
          "name" : "",
          "mac_address" : ""
        }
      },
```

On my Linux nodes these are properly populated. Could someone please shed some light on how these get set? I looked at `readNodeInfo()` but there's no low-level functionality there that would explain why it's empty. Or could someone explain where the `StreamInput in` is based on?

**Comment by clintongormley** [comment]
The stats APIs have been reimplemented relying solely on what the JVM reports.  Closing
