### ISSUE TITLE
[upgrade] Runtime field is throwing index_out_of_bounds_exception

### ISSUE THREAD

**Issue by liza-mae** [elastic/elasticsearch#90893]
In some of my upgrade cases, terminating with ```8.6.0``` version, I recently noticed I am getting failures with runtime field on my kibana sample data.  The error is ```index_out_of_bounds_exception: null``` can someone help me understand why this is now failing?  Is it a bug or is there some other change I need to do? 

I checked a new install of 8.6 to match the field, the only other change I see is the index pattern name is now the title, but I was not sure if that would cause this issue.

![Screenshot from 2022-10-13 15-43-58](https://user-images.githubusercontent.com/23424008/195717092-92f2cfb9-8659-43ac-b138-2aeb1515de3d.png)

**Comment by javanna** [comment]
Hi @liza-mae could you post the definition of the runtime field, the search request and the response you are getting please?

**Comment by romseygeek** [comment]
This should be fixed by #90901
