### ISSUE TITLE
Doc - Mistake for defining runtime fields in search requests

### ISSUE THREAD

**Issue by saryeHaddadi** [elastic/elasticsearch#90937]
Hello,
I saw a documentation mistake for [runtime fields](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/runtime-search-request.html).
The documentation says, to define runtime fields in **search requests**: "Just copy the field definition from the `runtime_mappings in the search request` to `the runtime section of the index mapping`."

If should be the opposite: "Just copy the field definition from `the runtime section of the index mapping` to the `runtime_mappings in the search request`."

**Comment by javanna** [comment]
Good catch @saryeHaddadi , would you be willing to contribute a fix? We would be happy to merge it if so, otherwise we are going to make the required change ourselves.

**Comment by saryeHaddadi** [comment]
Yes, with pleasure.
I repost a new message to notify I have created the pull request.

**Comment by saryeHaddadi** [comment]
Hey @javanna,☝️above is the link to the Pull Request
