### ISSUE TITLE
Inconsistent deleted docs count between single shard primary/replicas

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#90967]
### Elasticsearch Version

7.17.6

### Installed Plugins

analysis_icu

### Java Version

_bundled_

### OS Version

Ubuntu 20.04.5 LTS

### Problem Description

I have a small index (5K documents) with 1 primary shard and 2 replicas in a total of 3 different hosts making up the local cluster.

Following the index creation and initial indexing process, and after changes to 12 documents (replacements, using the bulk API's index mode), the primary shard reports the same docs count as the replicas, but a different deleted docs count (primary: 9, replicas: 12). This has the consequence of inconsistent scoring for the same queries between the 3 nodes.

This is not some edge case that can be fixed with a simple reindex, since we have many (>30) such indices in the cluster and it happens with almost all of them.

Please not that the deleted docs count is not always the same between the replicas; in many cases, each node has a different count.

Is this normal behavior? I was under the impression that replicas should be identical replications of the shard.

### Steps to Reproduce

There is no easy/short way of reproducing this.

**Comment by dnhatn** [comment]
> Is this normal behavior? I was under the impression that replicas should be identical replications of the shard.

Yes, the behavior is normal for shards with a small number of documents. Deleted documents are pruned independently by each shard. I hope you don't mind that I close this issue.
