### ISSUE TITLE
TransportListTaskAction: wait for tasks to finish asynchronously

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#90988]
> Yikes that's definitely a bug, although we did this sort of thing a lot back in 2016 when the code was first written. Ideally we wouldn't poll at all, tasks are only unregistered in one place so we should just be able to subscribe to an event triggered from there.

_Originally posted by @DaveCTurner in https://github.com/elastic/elasticsearch/issues/89564#issuecomment-1239306458_

**Comment by arteam** [comment]
See  https://github.com/elastic/elasticsearch/issues/89564#issuecomment-1239297988

> I think this is happening because the test framework waits for task completion which uses the `management` thread pool:
> 
> ```
> "elasticsearch[yamlRestTest-0][management][T#1]" #43 daemon prio=5 os_prio=31 cpu=53.50ms elapsed=25.32s tid=0x00007fbe9e3c1200 nid=84739 waiting on condition  [0x000070000597d000]
>    java.lang.Thread.State: TIMED_WAITING (sleeping)
>         at java.lang.Thread.sleep(java.base@18.0.2.1/Native Method)
>         at org.elasticsearch.tasks.TaskManager.waitForTaskCompletion(org.elasticsearch.server@8.5.0-SNAPSHOT/TaskManager.java:543)
>         at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.lambda$processTasks$0(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:78)
>         at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction$$Lambda$8023/0x0000000801d8b330.accept(org.elasticsearch.server@8.5.0-SNAPSHOT/Unknown Source)
>         at java.util.function.Consumer.lambda$andThen$0(java.base@18.0.2.1/Consumer.java:65)
>         at java.util.function.Consumer$$Lambda$6918/0x0000000801affa78.accept(java.base@18.0.2.1/Unknown Source)
>         at org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:174)
>         at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:81)
>         at org.elasticsearch.action.admin.cluster.node.tasks.list.TransportListTasksAction.processTasks(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportListTasksAction.java:29)
>         at org.elasticsearch.action.support.tasks.TransportTasksAction.nodeOperation(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:95)
>         at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:331)
>         at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportTasksAction.java:327)
>         at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:254)
>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(org.elasticsearch.server@8.5.0-SNAPSHOT/AbstractRunnable.java:26)
>         at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:316)
>         at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:306)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$5(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:398)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6315/0x0000000801bb8af8.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:962)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:926)
>         at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ContextPreservingActionListener.java:31)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$6(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:412)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6326/0x0000000801bb9e18.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
>         at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeClusterAction(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:172)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:402)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:378)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$2(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:263)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService$$Lambda$6282/0x0000000801bab700.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
>         at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ContextPreservingActionListener.java:31)
>         at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:140)
>         at org.elasticsearch.xpack.security.authz.RBACEngine$$Lambda$6292/0x0000000801bb2cb0.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
>         at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$1(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:185)
>         at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore$$Lambda$6303/0x0000000801bb1860.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
>         at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:193)
>         at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(org.elasticsearch.security@8.5.0-SNAPSHOT/CompositeRolesStore.java:175)
>         at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(org.elasticsearch.security@8.5.0-SNAPSHOT/RBACEngine.java:137)
>         at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthorizationService.java:265)
>         at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(org.elasticsearch.security@8.5.0-SNAPSHOT/ServerTransportFilter.java:112)
>         at org.elasticsearch.xpack.security.transport.ServerTransportFilter$$Lambda$5971/0x0000000801b0e2a0.accept(org.elasticsearch.security@8.5.0-SNAPSHOT/Unknown Source)
>         at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:162)
>         at org.elasticsearch.action.ActionListener$MappedActionListener.onResponse(org.elasticsearch.server@8.5.0-SNAPSHOT/ActionListener.java:127)
>         at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthenticatorChain.java:93)
>         at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(org.elasticsearch.security@8.5.0-SNAPSHOT/AuthenticationService.java:199)
>         at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(org.elasticsearch.security@8.5.0-SNAPSHOT/ServerTransportFilter.java:104)
>         at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(org.elasticsearch.security@8.5.0-SNAPSHOT/SecurityServerTransportInterceptor.java:327)
>         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(org.elasticsearch.server@8.5.0-SNAPSHOT/RequestHandlerRegistry.java:71)
>         at org.elasticsearch.transport.TransportService$6.doRun(org.elasticsearch.server@8.5.0-SNAPSHOT/TransportService.java:971)
>         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(org.elasticsearch.server@8.5.0-SNAPSHOT/ThreadContext.java:892)
>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(org.elasticsearch.server@8.5.0-SNAPSHOT/AbstractRunnable.java:26)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@18.0.2.1/ThreadPoolExecutor.java:1136)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@18.0.2.1/ThreadPoolExecutor.java:635)
>         at java.lang.Thread.run(java.base@18.0.2.1/Thread.java:833)
> ```
> 
> So presumably there's an ML task that's being waited for that performs a sub-action that also runs in the `management` thread pool.
> 
> To me it seems dodgy that this code uses `sleep`:
> 
> https://github.com/elastic/elasticsearch/blob/5f14c79320473605764840fd715ebbb31ec7491e/server/src/main/java/org/elasticsearch/tasks/TaskManager.java#L537-L549
> 
> @nik9000 `git blame` says you originally wrote that. Is there any reason it couldn't be rewritten to schedule checks of the task state periodically instead of blocking a thread by sleeping? Or do @dnhatn or @DaveCTurner have any insights on this since you've done work on the task manager by the look of it?

**Comment by nik9000** [comment]
I believe I used sleep because we thought it was ok to block the thread at the time. I have no objections at all to scheduling a task that wakes periodically for it. I don't like sleep at all. I think I had to be talked into using it at the time.

**Comment by DaveCTurner** [comment]
https://github.com/elastic/elasticsearch/issues/89564 was closed in error it seems but I reopened it. This is a duplicate.

**Comment by javanna** [comment]
@arteam I believe this has been implemented?

**Comment by arteam** [comment]
Yes, it's been implemented in #90977!
