### ISSUE TITLE
Readiness port should not only be available on the loopback device

### ISSUE THREAD

**Issue by pebrc** [elastic/elasticsearch#90997]
### Description

The new [readiness port](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/advanced-configuration.html#readiness-tcp-port) makes readiness checks on Kubernetes much easier. However the current implementation only allows connections through localhost. TCP probes on Kubernetes are run by the kubelet which is a process running on the Kubernetes node (and not from within the container or the Pod). The [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#tcp-probes) mentions it, but it is kind of subtle: 

> For a TCP probe, the kubelet makes the probe connection at the node, not in the pod, which means that you can not use a service name in the host parameter since the kubelet is unable to resolve it.

That means a standard Kubernetes readiness probe cannot be used for Elasticsearch:
```
          readinessProbe:
            tcpSocket:
              port: 8080
```

Instead, only an `exec` probe that runs a shell command inside the container can be used that relies in this case on the presence of the `nc` command in the container image:

```
    readinessProbe:
      exec:
        command: ["nc", "-z", "-v", "-w5", "127.0.0.1", "8080"] 
```

**Comment by grcevski** [comment]
The initial design was scoped to be localhost only, but since this is an opt-in feature I don't see a reason why we wouldn't be able to expose it just like the other ports if configured.
