### ISSUE TITLE
Support a score_mode parameter with collapse

### ISSUE THREAD

**Issue by tombrisland** [elastic/elasticsearch#90992]
### Description

I have a query which makes use of collapse to de-duplicate results. I'm expecting some collapsed results to have multiple duplicates, and some to be unique. I would like to sort the entries in such a way that the results with the most duplicates come first.

Currently there isn't much control available over the scoring of collapsed results. It seems like there's something analogous to what I'm talking about in the `score_mode` parameter of nested queries [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html#nested-top-level-params).

If we had a similar `score_mode` parameter for collapsed, the `sum` option would hit my use-case, but I can see potential value in other options as well.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch and the well written/formatted issue!

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by tombrisland** [comment]
Thanks for the reply @dliappis. To clarify, this is a feature request for an extra parameter in the `collapse` block.

An example query might look something like this:

```
{
  "query": {
    "match": {
      "message": "GET /search"
    }
  },
  "collapse": {
    "field": "user.id",
    "score_mode": "sum"
  }
}
```

When the documents are collapsed on the `user.id` field, a document is chosen to represent the collapsed documents within the results. Here, the `score_mode` option would mean that instead of using the score of that document, the `inner_hits` would have their scores summed and that final score would represent the collapsed documents.

This allows the results to be sorted based on the scores of all the documents under the collapsed key, rather than just one of them.
