### ISSUE TITLE
load balancing appeared not balancing when some nodes die  

### ISSUE THREAD

**Issue by hust419** [elastic/elasticsearch#91005]
### Elasticsearch Version

7.5.2

### Java Version

openjdk version "13.0.1" 2019-10-15

### OS Version

Linux VECS013828 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Hello everyone,
Maybe, I  found a bug in the load balancing implementation on the restclient , 
Sometimes theload balancing appeared not balancing when some nodes die  
We use high level client and call RestClient.performRequest() to search 
and set  host list  A:9200,B:9200,C:9200 and more . 
When a node is dies then the next living node will receive more request .
For example , When server B dies, then the server c will recevie more request than other nodes . 

I think  this is because all failed request from B will retry on server C  , maybe we can use random instead of  next node  in retry logical. 

![20221019154337](https://user-images.githubusercontent.com/3736029/196628136-89f2f4b6-2bce-419f-bf9a-fe8a2fda760c.jpg)

Servers in the  es cluster are all the same, there is only one index and only one primary shard and one shard on each server. 

### Steps to Reproduce

1. set the serverlist  A:9200,B:9200,C:9200,D:9200 in distributed java application restclient
2. server B dies in es cluster
3. server C will receive more request than other server
4. remove B from server list , the cluster recovers to a load balancing state again

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question/non-verified bug report, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
