### ISSUE TITLE
allow to disable retry logic

### ISSUE THREAD

**Issue by hust419** [elastic/elasticsearch#91003]
### Description

Hello everyone, 
We have a response time sensitive application, 
We use high level client and call RestClient.performRequest() to search  and we set timeout 1.5s to except to return in 1.5 seconds.
But when the first timeout occurs,  the RestClient considered this a error and continued to try other nodes 
finnaly it takes more than 1.5 seconds not what we expected
So, can you allow to customize retry logical ,for example can disable it ?
I think maybe it is  a little bug ?

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
