### ISSUE TITLE
Cannot use own java version in ES 8

### ISSUE THREAD

**Issue by olegs1993** [elastic/elasticsearch#91017]
Hello, I have ES version 8.1.2 and have env var for ES_JAVA_HOME
![image](https://user-images.githubusercontent.com/23138783/196688939-779deb29-e19c-4b65-9125-e84ea563d57d.png)

But anyway, when I start ES with systemctl start elasticsearch.service it uses bundled jdk.

I found a way how to start it with my own, using override.conf file:
Environment=ES_JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")" >> /etc/systemd/system/elasticsearch.service.d/override.conf
With these settings, it successfully starts with my own JDK.

Can you explain is this an issue?

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
