### ISSUE TITLE
allow to disable retry logic

### ISSUE THREAD

**Issue by hust419** [elastic/elasticsearch#91020]
### Description

Hi, 
In RestClient.java  function performRequest() 
The retry logic runs on every exception.
This is giving us a lot of trouble .
I configured a 1 second timeout，So I expect to return after 1 second no matter what happens

can you allow to customize retry logical  allow us to disable it  

`  if (nodeTuple.nodes.hasNext() && retryEnable) {
                return performRequest(nodeTuple, request, cause);
    }`

**Comment by qzhello** [comment]
Has this problem been solved?
