### ISSUE TITLE
Scan not counted against query total in search stats

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9109]
Running a search with `search_type` as `scan` does not get counted against the query total.

```
$ curl -XGET 'localhost:9200/test/_search?search_type=scan&scroll=1m&pretty' -d '{
  "query": { "match_all": {}},
  "size":  1000
}'
{
   "_scroll_id": "c2NhbjsxOzE5NDk6YWw2M3lVOGpTUjY2LVhFZGFhVW9JQTsxO3RvdGFsX2hpdHM6MTs=",
   "took": 10,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0,
      "hits": []
   }
}

$ curl -XGET localhost:9200/test/_stats?pretty
{
  ...
          "search": {
            "open_contexts": 2,
            "query_total": 0,
            "query_time_in_millis": 0,
            "query_current": 0,
            "fetch_total": 0,
            "fetch_time_in_millis": 0,
            "fetch_current": 0
         },
  ...
}
```

The number of open contexts increases with the number of open scans, but there's no way to capture this unless you happen to catch the `"open_contexts"` incrementing because it is not cumulative.

Perhaps a few things should probably happen:

- The actual query should be counted.
- Total number of scrolls should be maintained (`scroll_total` and `scroll_current`).
- The amount of time that scrolls were held open (e.g., `scroll_time_in_millis_total`).

**Comment by eeeebbbbrrrr** [comment]
As a paying customer, please make this happen in 2.0.  Please please please please please please please please please.

**Comment by eebbrr** [comment]
Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you, Thank you!
