### ISSUE TITLE
API inconsistency in current version

### ISSUE THREAD

**Issue by ferchundo9** [elastic/elasticsearch#91111]
### Description

I am contacting you because I am migrating to the current version of Elasticsearch and I have noticed an inconsistency in the API format.

I have been able to see how the use of the mapping types has disappeared. This change resulted in the disappearance of /_doc/ in urls such as:  

-      POST  /<target>/_update_by_query 

but instead the Index API continues to keep methods such as:

-     PUT  /<target>/_doc/<_id>
-     POST /<target>/_doc/

And this is where I see the inconsistency, **why hasn't the use of "_doc" disappeared definitively from all the APIs?**

**Do you plan to make this change and unify the format of all APIs in future versions?**

**Comment by ywangd** [comment]
I am closing this issue since I don't believe there is anything to do for it. The `_doc` in the url path of indexing API should not be considered as mapping types but instead a path to available actions, similar to `_bulk`, `_source`, `_create` etc.
