### ISSUE TITLE
Extend `knn` section to support multiple fields

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#91187]
Currently the `knn` section in the search request only accepts one field. We should extend it to allow ANN search over multiple fields:

```
POST image-index/_search
{
  "knn": [{
    "field": "image-vector",
    "query_vector": [-5, 9, -12],
    "k": 10,
    "num_candidates": 50
  }, {
    "field": "caption-vector",
    "query_vector": [0.91, -0.21, 0.43],
    "k": 10,
    "num_candidates": 100
  }],
  "fields": [ "title", "file-type" ]
}
```

Each section would be combined like a disjunction (the same as we do when both `knn` and `query` are specified). Note that it's already possible for documents to have more than one `dense_vector` field. It's just not currently possible to search them in the same request.

**Comment by nirmalc** [comment]
@benwtrent , do you plan to support `boost` to each field in `knn` ? TIA !!

**Comment by benwtrent** [comment]
@nirmalc Gotta think on this a bit more :). There are some other things in flight that may have knock on effects here.

But, I do think individual boosts per field make sense. You would want to boost title over body, for example.

**Comment by benwtrent** [comment]
Just for completion's sake, another possible way for this to look (which I don't particularly like) is:

```json
POST image-index/_search
{
  "knn": {
    "field": ["image-vector","caption-vector"],
    "query_vector": [[-5, 9, -12], [0.91, -0.21, 0.43]],
    "k": [10, 10],
    "num_candidates": [50, 100],
    "boost": [1, 2.0]
  },
  "fields": [ "title", "file-type" ]
}
```

Downsides here are:
 - API needs to validate that all these array values are the same size
 - Not as intuitive as simply supplying multiple configuration objects
 - If one configuration is changed, the other MUST be provided (e.g. no easy way for one vector search to have "default" values where the others are provided).

**Comment by nirmalc** [comment]
field such as `query_vector` could get very lengthy , but other than that - it might be useful if we can allow syntax for same vector to multiple fields , allowing multiple boosts . sort of like `multi_match`

```
{
  "knn": {
    "field": ["text-vector","description-vector"],
    "query_vector": [0.91, -0.21, 0.43],
    "k": 10,
    "num_candidates":50
    "boost": [1, 2.0]
  },
  "fields": [ "title", "file-type" ]
}
```

or 

```
{
  "knn": {
    "field": ["text-vector^10","description-vector^12"],
    "query_vector": [0.91, -0.21, 0.43],
    "k": 10,
    "num_candidates":50
  },
  "fields": [ "title", "file-type" ]
}

```

**Comment by benwtrent** [comment]
@nirmalc I have had the same thoughts. The downside there is the assumption that all fields are within the same vector space. There is a real use-case behind being able to query an "image embedding" and a "text embedding" in different vector spaces with separate query vectors (originating from the same text).

So, I suppose, I see the use of BOTH syntaxes. Your suggestion could be considered syntactic sugar for @jtibshirani's design when the vector fields are in the same space.

**Comment by jdconrad** [comment]
I agree with @benwtrent that the first approach should be the original design. If there's enough demand then we can add the second approach as syntactic sugar as a follow up.
