### ISSUE TITLE
Missing value type is disregarded in aggregations on dynamic templated fields

### ISSUE THREAD

**Issue by daviddusa** [elastic/elasticsearch#91183]
### Elasticsearch Version

7.17.1

### Java Version

openjdk 17.0.4 2022-07-19

### OS Version

Ubuntu Focal Fossa 20.04.5 LTS

### Problem Description

When trying to execute terms aggregation with missing value specified as number on fields whose mapping is defined by dynamic mapping, in case none of the documents have data for a field that falls under the dynamic template's match path, Elasticsearch always returns the missing value as string for the bucket key.

If at least a document exists with numeric data for the field aggregation is being done besides the document having no data, Elasticsearch returns the bucket key as numbers correctly.

A similar issue existed in the past:
https://github.com/elastic/elasticsearch/issues/20163

### Steps to Reproduce

Given a blogs index exists with the following mapping:
```
curl -X PUT localhost:9200/blogs?pretty -H "Content-Type: application/json" -d'
{
  "mappings": {
    "dynamic_templates": [
      {
        "score_details": {
          "mapping": {
            "properties": {
              "reason": {
                "type": "text"
              },
              "score": {
                "type": "long"
              }
            }
          },
          "path_match": "score.details.*"
        }
      }
    ]
  }
}
'
```

Create a document that does not have data for the field falling under the dynamic template path:
```
curl -X PUT localhost:9200/blogs/_doc/1?pretty -H "Content-Type: application/json" -d'
{
  "title": "Famous Fictious Novels",
  "category": "Literature",
  "date": "July 15, 2015",
  "author": {
    "first_name": "John",
    "last_name": "Doe"
  }
}
'
```

Run an aggregation query in which missing value is specified for the field in question:
```
curl -X GET "localhost:9200/blogs/_search?pretty" -H "Content-Type: application/json" -d'
{
  "size": 0,
  "aggs": {
    "score_details_favorite_score": {
      "terms": {
        "field": "score.details.favorite.score",
        "size": 10,
        "missing": -1
      }
    }
  }
}
'
```

Elasticsearch returns with the correct value as bucket key, but as string, even though the missing value was specified as a number:
```
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "score_details_favorite_score" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "-1",
          "doc_count" : 1
        }
      ]
    }
  }
}
```

Add another document with data for the field in question:
```
curl -X PUT localhost:9200/blogs/_doc/2?pretty -H "Content-Type: application/json" -d'
{
  "title": "Famous Fictious Poems",
  "category": "Literature",
  "date": "August 30, 2015",
  "author": {
    "first_name": "Jane",
    "last_name": "Doe"
  },
  "score": {
    "details": {
      "favorite": {
        "score": 4
      }
    }
  }
}
'
```

Run aggregation query again:
```
curl -X GET "localhost:9200/blogs/_search?pretty" -H "Content-Type: application/json" -d'
{
  "size": 0,
  "aggs": {
    "score_details_favorite_score": {
      "terms": {
        "field": "score.details.favorite.score",
        "size": 10,
        "missing": -1
      }
    }
  }
}
'
```

Elasticsearch returns with the correct values and correct types as bucket keys:
```
{
  "took": 16,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "score_details_favorite_score": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": -1,
          "doc_count": 1
        },
        {
          "key": 4,
          "doc_count": 1
        }
      ]
    }
  }
}
```

**Comment by scampi** [comment]
Using [`value_type: long`](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-aggregations-bucket-terms-aggregation.html#_failed_trying_to_format_bytes) seems to work as a temporary workaround.

**Comment by daviddusa** [comment]
Thank you for the suggestion! It works indeed. 👍
I hope this will get fixed nonetheless.

**Comment by wchaparro** [comment]
won't fix, workaround exists and is appropriate. Mapping is not known at search time, so it will fall back to default of string.
