### ISSUE TITLE
Support WKT syntax in geo_point and geo_shape

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#9120]
So indexing stuff like `POINT (30 10)` and `POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))` can be done into geo_point and geo_shape field types

**Comment by sckott** [comment]
+!

**Comment by clydedacruz** [comment]
yes adding support for WKT would be awesome!

**Comment by clintongormley** [comment]
@nknize is WKT on your roadmap?

**Comment by kovrus** [comment]
+1

**Comment by bneff** [comment]
+100

**Comment by dakrone** [comment]
@nknize ping about this and whether it's on the roadmap?

**Comment by ebclark2** [comment]
+1

**Comment by synhershko** [comment]
ping again @dakrone @nknize @clintongormley. The recent geo performance boost will probably require WKT support to ease work with geo-shape with Elastic.

**Comment by panchicore** [comment]
thanks. helped a lot, I had a serializer for each type of shape, now I just had to set it as a string and works for all types of shapes, also the overhead to json-serialize this data is now zero. thanks.
