### ISSUE TITLE
Painless def eq binding - avoid using null pointer handler

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#91236]
When resolving the equals handler for a `null` def-type, use a custom `boolean eq(Object a, Object b)` check to avoid throwing a `NullPointerException` in [`checkLHS`](https://github.com/elastic/elasticsearch/blob/0699c9351f1439e246d408fd6538deafde4087b6/modules/lang-painless/src/main/java/org/elasticsearch/painless/DefBootstrap.java#L416).

Right now, that exception is [caught](https://github.com/elastic/elasticsearch/blob/0699c9351f1439e246d408fd6538deafde4087b6/modules/lang-painless/src/main/java/org/elasticsearch/painless/DefBootstrap.java#L402) and replaced by a call to [`lookupGeneric()`](https://github.com/elastic/elasticsearch/blob/0699c9351f1439e246d408fd6538deafde4087b6/modules/lang-painless/src/main/java/org/elasticsearch/painless/DefBootstrap.java#L334) which does the [null comparison](https://github.com/elastic/elasticsearch/blob/0699c9351f1439e246d408fd6538deafde4087b6/modules/lang-painless/src/main/java/org/elasticsearch/painless/DefMath.java#L528).

We may be able to special case when `leftObject` is `null` and avoid using `NullPointerException` as control flow.

**Comment by thecoop** [comment]
@stu-elastic Do you have an example of the painless that actually hit this?

**Comment by stu-elastic** [comment]
def has to change types with initial call site depth 0.

**Comment by thecoop** [comment]
Implemented by #91347
