### ISSUE TITLE
Autocomplete  when select item in dropdown- Uncaught TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Juliet-Brown** [elastic/elasticsearch#91239]
### Elasticsearch Version

1.18.2

### Installed Plugins

Using Elastic Site Search with Swiftype (BED)

"@elastic/search-ui-site-search-connector": "^1.18.2",    "@elastic/search-ui": "^1.18.2",   "@elastic/react-search-ui": "^1.18.2",     "@elastic/react-search-ui-views": "^1.18.2",

### Java Version

_bundled_

### OS Version

mac

### Problem Description

When I select the item in the dropdown it comes up with this error below.
its also  happening in the example [Elastic Site Search (Swiftype)](https://codesandbox.io/s/github/elastic/search-ui/tree/master/examples/sandbox?from-embed=&initialpath=/site-search&file=/src/pages/site-search/index.js)

<img width="600" alt="Screen Shot 2022-11-02 at 12 32 07 PM" src="https://user-images.githubusercontent.com/39931151/199361428-b9d3915f-8a96-4f05-b800-671a4fd543e1.png">

I can see it isn't picking up result id  which could be a bug on this end? Could I please have some guidance around this.

<img width="1516" alt="Screen Shot 2022-11-02 at 12 56 41 PM" src="https://user-images.githubusercontent.com/39931151/199363714-8ef64fa8-5768-4b01-a3f0-36e9c7312234.png">

<img width="1480" alt="Screen Shot 2022-11-02 at 12 33 09 PM" src="https://user-images.githubusercontent.com/39931151/199361522-4dc78916-278c-4b56-aec5-3171814fbd63.png">

Thankyou :) 

### Steps to Reproduce

Elastic Site Search (Swiftype) autocomplete searchbox dropdown add item  it wont add item to search box.

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch and Enterprise Search.

This appears to be a user question, and we'd like to direct these kinds of things to the [Enterprise Search forum](https://discuss.elastic.co/c/enterprise-search/84). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/enterprise-search) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
