### ISSUE TITLE
RangeQueryBuilder gt("")  && lt("") is not equals to value <> "",  but RangeQueryBuilder.gt(0) result is same as value<> ""

### ISSUE THREAD

**Issue by albericgenius** [elastic/elasticsearch#91263]
### Elasticsearch Version

Latest

### Java Version

_bundled_

### OS Version

X86_64

### Problem Description

RangeQueryBuilder gt("")  && lt("") is not equals to value <> ""
but RangeQueryBuilder.gt(0) result is same as value<> ""

Here is relative ticket for Trino. https://github.com/trinodb/trino/pull/14683

### Steps to Reproduce

use RangeQueryBuilder gt("")  && lt("") to query

**Comment by benwtrent** [comment]
I don't understand what the desired behavior is here. 

From what I can tell, doing a `gt: "", lt: ""` results in no hits, which is what I would expect. 

Closing unless there is clarification from the original author with example data and expected behavior.
