### ISSUE TITLE
ThirdPartyAudit failure for JDK19

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#91264]
### CI Link

https://gradle-enterprise.elastic.co/s/mq6p6fx7hwtoc

### Repro line

./gradlew :libs:elasticsearch-plugin-analysis-api:thirdPartyAudit -Druntime.java=19

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

Forbidden APIs output:
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfByte' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfByte'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfShort' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfShort'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfInt' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfInt'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfLong' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfLong'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySegment' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySegment'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.MemorySession' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.MemorySession'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfShort' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfShort'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfShort' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfShort'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfInt' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfInt'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfInt' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfInt'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfLong' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfLong'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfLong' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfLong'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath!
==end of forbidden APIs==
Missing classes:
  * java.lang.foreign.MemorySegment
  * java.lang.foreign.MemorySession
  * java.lang.foreign.ValueLayout
  * java.lang.foreign.ValueLayout$OfByte
  * java.lang.foreign.ValueLayout$OfFloat
  * java.lang.foreign.ValueLayout$OfInt
  * java.lang.foreign.ValueLayout$OfLong
  * java.lang.foreign.ValueLayout$OfShort

**Comment by rjernst** [comment]
@ChrisHegarty This looks like a result of the tricks played to use the foreign memory api while it is in preview, right? So we should just add these as "missing" since we don't rung with preview enabled?

**Comment by ChrisHegarty** [comment]
> @ChrisHegarty This looks like a result of the tricks Lucene plays to use the foreign memory api while it is in preview, right? So we should just add these as "missing" since we don't rung with preview enabled?

@rjernst Yes.

**Comment by kingherc** [comment]
This is appearing a lot in test failures recently. See history [here](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:libs:elasticsearch-plugin-analysis-api:thirdPartyAudit%27.%0A%3E%20Audit%20of%20third%20party%20dependencies%20failed&search.timeZoneId=Europe/Athens). Would appreciate if there's a way to mute this?

**Comment by kingherc** [comment]
Once more [here](https://github.com/elastic/elasticsearch/issues/91264).

**Comment by pgomulka** [comment]
just adding a `ignoreMissingClasses` section won't help here. It is not a problem in JDK<19 
and also in JDK19 when added that gradle configuration it does not fix the problem either
```
tasks.named("thirdPartyAudit").configure {
  ignoreMissingClasses(
    'java/lang/foreign/MemorySegment',
    'java/lang/foreign/MemorySession',
    'java/lang/foreign/ValueLayout',
    'java/lang/foreign/ValueLayout$OfByte',
    'java/lang/foreign/ValueLayout$OfFloat',
    'java/lang/foreign/ValueLayout$OfInt',
    'java/lang/foreign/ValueLayout$OfLong',
    'java/lang/foreign/ValueLayout$OfShort'
  )
}

```

in JDK19 
```
the same as previous beginning...
WARNING: Class 'java.lang.foreign.ValueLayout' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath!
WARNING: Class 'java.lang.foreign.ValueLayout$OfFloat' cannot be loaded (while looking up details about referenced class 'java.lang.foreign.ValueLayout$OfFloat'). Please fix the classpath!
==end of forbidden APIs==

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libs:elasticsearch-plugin-analysis-api:thirdPartyAudit'.
> All excluded classes seem to have no issues. This is sometimes an indication that the check silently failed
```

in JDK18
```
* What went wrong:
Execution failed for task ':libs:elasticsearch-plugin-analysis-api:thirdPartyAudit'.
> All excluded classes seem to have no issues. This is sometimes an indication that the check silently failed
```

I wonder why would it fail in `plugin-analysis-api` in the first place? It probably affects any other gradle module?

**Comment by pgomulka** [comment]
another thought. Gradle is still running jdk17 for this build. 
```
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Linux 5.10.0-19-cloud-amd64 (amd64)
  Runtime JDK Version   : 19.0.1 (Oracle, 19.0.1+10-21)
  Runtime java.home     : /var/lib/jenkins/.java/openjdk19
  Gradle JDK Version    : 17.0.2 (Oracle)
  Gradle java.home      : /var/lib/jenkins/.java/openjdk-17.0.2+8-linux
  Random Testing Seed   : 179CD6AE5E04473B
  In FIPS 140 mode      : false
=======================================
```
when I tried to set JAVA_HOME to 19 I got this
`* What went wrong:
Could not open cp_settings generic class cache for settings file '/Users/przemyslawgomulka/workspace/pgomulka/elasticsearch/settings.gradle' (/Users/przemyslawgomulka/.gradle/caches/7.5.1/scripts/7qmvoju8mixp2m0jts3x9vuw8).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
`
I tried removing the cache, but this did no help
Anyone from @elastic/es-delivery would know if we can run gradle with jdk19?

**Comment by ChrisHegarty** [comment]
@pgomulka I'm testing suppressing these warnings in PR #91397 

What we want to test, is running Gradle with JDK 17/18, but using the compiler from JDK 19 to compile the source code. For example:

```
$ env | grep JAVA
JAVA_HOME=/Users/chegar/binaries/jdk-17.0.2.jdk/Contents/Home/
RUNTIME_JAVA_HOME=/Users/chegar/binaries/jdk-19.jdk/Contents/Home/
$ 
$ 
$ ./gradlew precommit
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Mac OS X 12.6.1 (aarch64)
  Runtime JDK Version   : 19 (Oracle, 19+36-2238)
  Runtime java.home     : /Users/chegar/binaries/jdk-19.jdk/Contents/Home
  Gradle JDK Version    : 17.0.2 (Oracle)
  Gradle java.home      : /Users/chegar/binaries/jdk-17.0.2.jdk/Contents/Home
  Random Testing Seed   : F32C29CA25D58313
  In FIPS 140 mode      : false
=======================================

```

**Comment by pgomulka** [comment]
closed by https://github.com/elastic/elasticsearch/pull/91412
