### ISSUE TITLE
Kibana Dashboard does not reflect changes after changing timestamp

### ISSUE THREAD

**Issue by Neelam-zanvar** [elastic/elasticsearch#91262]
I have a dashboard A created manually. I want to automate this entire process using ansible. so ansible is creating an index . Now i have changed the index for dashboard A to the index created by ansible( both indexes are having same fields) and exported it. i will import it on another instance of elk using ansible. The problem is that the dashboard is not working according to the time i select
![image](https://user-images.githubusercontent.com/98389856/199651318-e0b95f49-da03-44a4-9e88-5a7e91dae075.png)
as u can see in the image i've selected last 15 minutes but its showing me data of yesterday as well.
Steps to reproduce.
I have a dashboard A index A
I changed index in Dashboard A to index B(created by ansible) as highlighted  in image below
![image](https://user-images.githubusercontent.com/98389856/199651686-c2f6b657-62b1-4454-a2dc-4c6fabe75795.png)
After changing the index the control to set the time intervals is missing . Help please

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
