### ISSUE TITLE
Missing lucene plugin

### ISSUE THREAD

**Issue by patriczek** [elastic/elasticsearch#91308]
### Elasticsearch Version

8.5.0

### Java Version

_bundled_

### OS Version

Docker build 

### Problem Description

Hi, 

I'm running single node elasticsearch (built from sourcecode) running in k3s, and I'm not able to upgrade elasticsearch from 8.3.4 to 8.5.0 because of the missing Lucene plugin (More info in the log). 

But if I'll run the docker image directly on the host using docker:
docker run -it <image> 
elasticsearch start without problems.

### Steps to Reproduce

Upgrade running elasticsearch from 8.3.4 to 8.5.0

### Logs (if relevant)

{"@timestamp":"2022-11-04T10:47:29.612Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"elasticsearch-75c865dcbb-thtbw","elasticsearch.cluster.name":"docker-cluster","error.type":"java.lang.IllegalArgumentException","error.message":"Could not load codec 'Lucene93'. Did you forget to add lucene-backward-codecs.jar?","error.stack_trace":"java.lang.IllegalArgumentException: Could not load codec 'Lucene93'. Did you forget to add lucene-backward-codecs.jar?\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:515)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:404)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:363)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:299)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:88)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:77)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:809)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:109)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:67)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:60)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:322)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:599)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:326)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.node.Node.<init>(Node.java:474)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.node.Node.<init>(Node.java:318)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.5.1-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\n\tSuppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (832e5021). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path=\"/usr/share/elasticsearch/data/_state/segments_mm9\")))\n\t\tat org.apache.lucene.core@9.4.1/org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:500)\n\t\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:370)\n\t\t... 15 more\nCaused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene93' does not exist. You need to add the corresponding JAR file supporting this SPI to your classpath. The current classpath supports the following names: [Lucene94, Lucene70, Lucene80, Lucene84, Lucene86, Lucene87, Lucene90, Lucene91, Lucene92, BWCLucene70Codec, Lucene62, Lucene60, SimpleText]\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.codecs.Codec.forName(Codec.java:118)\n\tat org.apache.lucene.core@9.4.1/org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:511)\n\t... 17 more\n"}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

> at [org.elasticsearch.server@8.5.1-SNAPSHOT](mailto:org.elasticsearch.server@8.5.1-SNAPSHOT)

Upgrades between `-SNAPSHOT` builds are only expected to work under very specific circumstances and it looks like whatever you have done is not one of those. See e.g. [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html):

> You can upgrade from a previously released version to a pre-release build, if following a supported upgrade path. Upgrading from a pre-release build to any other build is not supported, and can result in errors or silent data loss. If you run a pre-release build for testing, discard the contents of the cluster before upgrading to another build of Elasticsearch.

It's possible that someone on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) might be able to help, but we reserve GitHub for verified bug reports, feature requests, and pull requests and this issue is none of those things. As such, I hope you don't mind that I close this.
