### ISSUE TITLE
Most Implementations of TransportBroadcastByNodeAction needlessly hold on to a full cluster state reference

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#91351]
This is pretty much the same issue as fixed in #90724 but for `TransportBroadcastByNodeAction`.
Most implementations of `org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction#newResponse(Request, int, int, int, java.util.List<ShardOperationResult>, java.util.List<org.elasticsearch.action.support.DefaultShardOperationFailedException>, org.elasticsearch.cluster.ClusterState)` don't actually use the `ClusterState` provided in the callback.
For potentially very long running actions like a force merge this means a lot of heap is needlessly used in some cases as the cluster changes away from the state that is retained more and more.
For a coordinating node that might handle a large number of such requests over an extended period of time this has been practically seen to consume up to O(1GB) of heap.

**Comment by Tim-Brooks** [comment]
I think this is complete now? By #92255?

**Comment by original-brownbear** [comment]
Yes that sounds right => this can be closed :)
