### ISSUE TITLE
Feature Request - ability to send alarms when a threshold is reached

### ISSUE THREAD

**Issue by TomJoons** [elastic/elasticsearch#9138]
Hello,
I came here from the "feature request" link on elasticsearch community page and hope I am in the right place.

So my use of various terms makes sense; I work for a company that sells solutions, each made up of many proceses or components.  One such component is a monitoring system which monitors all the other components and this is done 24/7.  Our customers are typically large companies that have their own in house monitoring departments.  A common requirement is that our monitoring component integrates into theirs such that all support is driven via their helpdesk and 1st line support.

I love ELK and have found the "insights" it provides from our logs far more useful than the various metrics available from our own monitoring product!  However, the one thing that prevents me from adopting it is that I cannot integrate it into 3rd party monitoring systems; I cannot generate "northbound" alarms from ELK to our customers monitoring system, which is typically Nagios.

What I would like is to be able to set a threshold on a particular graph and generate an alarm if this threshold is breached.

For instance, lets say I have a graph in Kibana of HTTP responses.  I would like to set an alarm that triggers if the number of responses with status 200 falls to 0 averaged over a configurable period.

Is this at all feasible?  It is the alarming that regrettably steers customers towards Splunk over ELK.

Thanks!

**Comment by adiworkoholic** [comment]
@ElasticSearch folks : I am also interested in an answer for this question. Can folks from elastic.co kindly comment on this ?

**Comment by clintongormley** [comment]
The ability to alert once a threshold has been crossed is available in our Watcher commercial plugin.  There are also other community supported plugins with alerting capabilities.
