### ISSUE TITLE
Could not resolve all files for configuration ':x-pack:plugin:ml:nativeBundle'

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91382]
### CI Link

https://gradle-enterprise.elastic.co/s/udr4zarqelpuw

### Repro line

Appears a lot recently - see failure history

### Does it reproduce?

Yes

### Applicable branches

main, 7.17, 8.5

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.expandedAnalyses=WyJycTZ2YzRzMndobHk2IiwidWRyNHphcnFlbHB1dyIsIjN2dWpiY3Q1NHh0NGUiXQ&failures.failureClassification=all_failures&failures.failureMessage=Could%20not%20determine%20the%20dependencies%20of%20task%20*%0A%3E%20Could%20not%20resolve%20all%20files%20for%20configuration%20%27:x-pack:plugin:ml:nativeBundle%27.%0A%20%20%20%3E%20Could%20not%20download%20*%0A%20%20%20%20%20%20%3E%20Could%20not%20get%20resource%20%27https://artifacts-snapshot.elastic.co/ml-cpp/*/downloads/ml-cpp/*%0A%20%20%20%20%20%20%20%20%20%3E%20Premature%20end%20of%20Content-Length%20delimited%20message%20body%20(expected:%20*%20received:%20*&search.timeZoneId=Europe/Athens

### Failure excerpt

```
Could not determine the dependencies of task ':x-pack:plugin:ml:explodedBundlePlugin'

Build file 'C:\Users\jenkins\workspace\platform-support\463\x-pack\plugin\ml\build.gradle' line: 58
Could not resolve all files for configuration ':x-pack:plugin:ml:nativeBundle'.
> Could not download ml-cpp-8.6.0-SNAPSHOT-deps.zip (org.elasticsearch.ml:ml-cpp:8.6.0-SNAPSHOT)
  > Could not get resource 'https://artifacts-snapshot.elastic.co/ml-cpp/8.6.0-SNAPSHOT/downloads/ml-cpp/ml-cpp-8.6.0-SNAPSHOT-deps.zip'.
    > Premature end of Content-Length delimited message body (expected: 340,418,397; received: 8,388,544)
```

Probably some robustness is needed for such a large file? Maybe some way for gradle to retry it?

**Comment by kingherc** [comment]
Also [here](https://github.com/elastic/elasticsearch/issues/91382) among others.

**Comment by kingherc** [comment]
This looks similar to https://github.com/elastic/elasticsearch/issues/91395 where I've tagged the Delivery/Build team. If ML team believes this is a build issue as well, please re-label appropriately. Note that this issue appears much more frequently than https://github.com/elastic/elasticsearch/issues/91395 .

**Comment by mark-vieira** [comment]
This is a duplicate issue of many others all related to a infra ticket.

**Comment by ruthwik3690** [comment]
what is the solution/workaround for this issue?
facing the same.

**Comment by mark-vieira** [comment]
> what is the solution/workaround for this issue?

Is it consistently happening? The workaround is simply to retry the build given this is just an ephemeral network error.

**Comment by ruthwik3690** [comment]
```
Could not find org.elasticsearch.ml:ml-cpp:7.17.9-SNAPSHOT.
     Searched in the following locations:
       - https://artifacts-snapshot.elastic.co/ml-cpp/7.17.9-SNAPSHOT/downloads/ml-cpp/ml-cpp-7.17.9-SNAPSHOT.zip
     Required by:
         project :x-pack:plugin:ml`
```
actually the ml-cpp-<version>-SNAPSHOT is not available in the location.
This is the exact error, could you help me out with this?

**Comment by wdongyu** [comment]
exactly the same error on 8.6.0 when I run `./gradlew test`

```
Could not determine the dependencies of task ':x-pack:plugin:ml:explodedBundlePlugin'.
    Could not resolve all task dependencies for configuration ':x-pack:plugin:ml:nativeBundle'.
     Could not find org.elasticsearch.ml:ml-cpp:8.6.0-SNAPSHOT.
     Searched in the following locations:
       - https://artifacts-snapshot.elastic.co/ml-cpp/8.6.0-SNAPSHOT/downloads/ml-cpp/ml-cpp-8.6.0-SNAPSHOT-deps.zip
     Required by:
         project :x-pack:plugin:ml
```

**Comment by nileiqing** [comment]
gradlew run --debug-jvm -x :x-pack:plugin:ml:explodedBundlePlugin
