### ISSUE TITLE
Could not download elasticsearch-8.5.0-linux-x86_64.tar.gz

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#91395]
### CI Link

https://gradle-enterprise.elastic.co/s/y5bghb3xfyt54/failure#1

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main, 8.5 in failure history

### Failure history

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Could%20not%20resolve%20all%20files%20for%20configuration%20*%0A%20%20%20%3E%20Failed%20to%20transform%20*%20to%20match%20attributes%20%7BartifactType%3Ddirectory%2C%20org.gradle.status%3Dintegration%7D.%0A%20%20%20%20%20%20%3E%20Could%20not%20download%20*%0A%20%20%20%20%20%20%20%20%20%3E%20Could%20not%20get%20resource%20%27https://artifacts-no-kpi.elastic.co/downloads/elasticsearch/*%0A%20%20%20%20%20%20%20%20%20%20%20%20%3E%20Premature%20end%20of%20Content-Length%20delimited%20message%20body%20(expected:%20*%20received:%20*&search.timeZoneId=Europe/Athens

### Failure excerpt

```
Could not resolve all files for configuration ':x-pack:plugin:transform:qa:multi-cluster-tests-with-security:es_distro_extracted_testclusters-x-pack-plugin-transform-qa-multi-cluster-tests-with-security-remote-cluster-0-8.5.0'.
> Failed to transform elasticsearch-8.5.0-linux-x86_64.tar.gz (elasticsearch-distribution:elasticsearch:8.5.0) to match attributes {artifactType=directory, org.gradle.status=integration}.
  > Could not download elasticsearch-8.5.0-linux-x86_64.tar.gz (elasticsearch-distribution:elasticsearch:8.5.0)
    > Could not get resource 'https://artifacts-no-kpi.elastic.co/downloads/elasticsearch/elasticsearch-8.5.0-linux-x86_64.tar.gz'.
      > Premature end of Content-Length delimited message body (expected: 580,444,068; received: 436,204,288)
```

Probably some robustness is needed for such a large file? Maybe some way for gradle to retry it?

This looks similar to https://github.com/elastic/elasticsearch/issues/91382 which appears much more frequently and may be able to be resolved together if it's a general Delivery/Build robustness issue.

**Comment by mark-vieira** [comment]
We have an open issue with the infra folks about this already.
