### ISSUE TITLE
Improve static backwards index tests

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#9143]
There are a few things that make it possible for problems like #9140 to go undetected.

1. we don't test all the versions we support? e.g. there arent 0.20.x indexes in the 1.x branch.
2. the current indexes are trivial, and only consist of flushed segments in .cfs/.cfe format. So they wouldn't detect problems like that one where only .tis and .tii are impacted.

finally, if we dont already, i think we should increase numbers of replicas in the test to force the files to get shuffled around.

**Comment by rmuir** [comment]
We should fix the python generation scripts to add more docs as another improvement. the 0.20.6 index is larger than the rest (i manually hacked scripts to do that) and it found corruption issues on #9822

**Comment by mikemccand** [comment]
+1

**Comment by rmuir** [comment]
index sizes were increased in #10143 

There is still a lot to do:
* ensure stuff in translog.
* ensure indexes have some pending deletes.
* ensure there are both cfs/nocfs segments / merges have happened.
* increase types of mappers used (numeric, date, text, string, etc).
* use multiple data paths.
* improve verification in the test (numDocs is correct, etc)

**Comment by rjernst** [comment]
Another improvement we should make, from @bleskes on #10247:
> can we add a test that turns off real time and checks you get the old doc back?

**Comment by bleskes** [comment]
some clarification - the test already have a checks that verifies we can retrieve a doc after indexing a new version of it but before refresh/(lucene flush). The request is to validate that we can retrieve the old version when turning off real time get.

**Comment by clintongormley** [comment]
I believe this has all been implemented.  Closing
