### ISSUE TITLE
Make it clear script score functions don't work in a loop

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#91496]
There have been a couple of issues trying to run script score functions in a loop, #70437, #89602 - which doesn't work properly (and is not intended to work).

There should be some mention on the [documentation about scoring functions](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html#script-score-predefined-functions) that they are optimised for single documents and not for use in a loop. If customers need these functions in a loop they should implement the function themselves.

**Comment by Gkleinereva** [comment]
I would add that this issue isn't exclusive to loops - it has the potential to appear any time the function is called multiple times within a script.
