### ISSUE TITLE
Add ability in Script API to retrieve all Scripts

### ISSUE THREAD

**Issue by eprice881** [elastic/elasticsearch#91518]
In the Script APIs (https://www.elastic.co/guide/en/elasticsearch/reference/current/script-apis.html), can there be an addition made such that a list of the existing scripts can be retrieved?

This functionality exists for other Kibana Objects, such as Watchers (GET _watcher/_query/watches) or Transforms (GET _transform/_all)

Something like this: GET _scripts/_all

**Comment by rjernst** [comment]
Closing as a duplicate of https://github.com/elastic/elasticsearch/issues/25179.
