### ISSUE TITLE
Add benchmarks for comparison of byte versus float vectors in scripting

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#91527]
We should have benchmarks for each of the class bindings `dotProduct`, `l1Norm`, `l2Norm`, and `cosineSimilarity` for comparison of byte vectors versus float vectors in scripting. This can also help us determine if there's regressions in the future.

**Comment by benwtrent** [comment]
We have JMH benchmarks, but are still missing nightly rally benchmarks :(

**Comment by benwtrent** [comment]
closing as we have an issue for byte rally tracks: https://github.com/elastic/rally-tracks/issues/408
