### ISSUE TITLE
Size JVM pools based on node.processors

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#91543]
### Description

In #89662 we changed the `node.processors` setting to be a double, enabling precise representation of the environment (often docker container) that ES is running in.

However, we still require configuration of the JVM thread pools, preferably through `-XX:ActiveProcessorCount`. In order to simplify it would be good to instead derive this from the `node.processors` setting such that the only setting we need about the environment is that setting. This is slightly complicated because it is in the startup process, but seems doable to parse out the setting from the yaml.

Relates #65905 and #89662

**Comment by mark-vieira** [comment]
> This is slightly complicated because it is in the startup process, but seems doable to parse out the setting from the yaml.

The complex bit is that you can pass settings via multiple ways, not just `elasticsearch.yaml`. Right now our auto-heap is somewhat naive and assumes that node roles will _only_ exist in the YAML config and not via environment variables, CLI args, etc.

**Comment by rjernst** [comment]
This was addressed with #101846
