### ISSUE TITLE
Marvel: Not able to update settings using cluster API

### ISSUE THREAD

**Issue by mosiddi** [elastic/elasticsearch#9154]
ES Version: 1.3.4 
Marvel plugin: Latest

What I was trying?
http://www.elasticsearch.org/guide/en/marvel/current/configuration.html 
Setting the indices names for which I want to collect the stats - 
PUT _cluster/settings 
{
  "presistent" : {
    "marvel.agent.indices" : "mosiddi"
  }
}

What I get? An exception:
{
   "error": "ActionRequestValidationException[Validation Failed: 1: no settings to update;]",
   "status": 500
}

**Comment by bleskes** [comment]
The marvel.agent.indices settings allows for both a single value (comma separated) and an array. However, only the array version is registered for dynamic updates. I will fix this but as a work around, you should be able to use: 

```
PUT _cluster/settings 
{
"presistent" : {
"marvel.agent.indices" : ["mosiddi"]
}
}
```

Can you confirm this works for you?

**Comment by mosiddi** [comment]
Still getting the same exception... I ensured I have the latest marvel plugin by doing this - 
plugin -r elasticsearch/marvel/latest
plugin -i elasticsearch/marvel/latest

**Comment by bleskes** [comment]
double reading - I see you have a typo in your command - it's "presistent"->"persistent" . That said, there is still the issue I mentioned :)

**Comment by mosiddi** [comment]
Awesome! My bad:(

I verified and it works fine... Thanks @bleskes 
{
   "acknowledged": true,
   "persistent": {
      "marvel": {
         "agent": {
            "indices": [
               "mosiddi"
            ]
         }
      }
   },
   "transient": {}
}

**Comment by mosiddi** [comment]
And just for data in this issue (for other folks), if the settings is something that ES doesn't support changing OR difference in the value type, we will get
PUT _cluster/settings 
{
  "persistent" : {
    "marvel.agent.indices" : "mosiddi"
  }
}

And when we have a typo in the setting type, example - 
PUT _cluster/settings 
{
  "random" : {
    "marvel.agent.indices" : "mosiddi"
  }
}
We will get this - 
{
   "error": "ActionRequestValidationException[Validation Failed: 1: no settings to update;]",
   "status": 500
}

**Comment by clintongormley** [comment]
Marvel 2 has been completely rewritten. Closing
