### ISSUE TITLE
rescore doc iterate bug

### ISSUE THREAD

**Issue by tangtang2013** [elastic/elasticsearch#91583]
https://github.com/elastic/elasticsearch/blob/90e3728a6c32c214b8ae82aa2fcce2a823c50daf/plugins/examples/rescore/src/main/java/org/elasticsearch/example/rescore/ExampleRescoreBuilder.java#L171

this line have a bug, doc iterate need a ordered list(order by docid). it may use 'sortedByDocId' to replace 'topDocs.scoreDocs'.

Arrays.sort(sortedByDocId, (a, b) -> a.doc - b.doc); // Safe because doc ids >= 0 Iterator

**Comment by javanna** [comment]
Duplicate of #39665
