### ISSUE TITLE
"input automaton is too large" when using a "prefix" over 1000 characters

### ISSUE THREAD

**Issue by jamshid** [elastic/elasticsearch#91594]
### Elasticsearch Version

Version: 7.17.6, Build: default/rpm/f65e9d338dc1d07b642e14a27f338990148ee5b6/2022-08-23T11:08:48.893373482Z, JVM: 18.0.2

### Java Version

_bundled_

### OS Version

Linux c2ea4a1d523e 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

A search with prefix larger than 1000 characters fails with a 400 error "input automaton is too large". Hopefully limit is configurable?

### Steps to Reproduce

Create an index with a very long field value and search for it with a <1000 character `prefix`, it succeeds:
```
curl -i -XPUT http://elasticsearch:9200/longname -H 'Content-type: application/json' --data-binary '
{
    "mappings" : { "properties" : { "name" : {"type" : "keyword" }} }
}
'

curl -i -XPOST http://elasticsearch:9200/longname/_doc/ -H 'Content-type: application/json' --data-binary '{"name": "mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/long.txt"}'

curl -i -XPOST 'http://elasticsearch:9200/longname/_search' -H 'Content-type: application/json' --data-binary '
{ "query" : { "bool" :
{ "must" : [
    { "prefix" : { "name" : { "value" : "mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaa" } } } ] } } }
'
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json; charset=UTF-8
content-length: 1441

{"took":11,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"longname","_type":"_doc","_id":"_N1wfIQBGWLmWEk8wh0E","_score":1.0,"_source":{"name": "mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/long.txt"}}]}}
```
But using a longer prefix fails:
```
curl -i -XPOST 'http://elasticsearch:9200/longname/_search' -H 'Content-type: application/json' --data-binary '
{ "query" : { "bool" :
{ "must" : [
    { "prefix" : { "name" : { "value" : "mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa/mumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaamumblejjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaa" } } } ] } } }
'

HTTP/1.1 400 Bad Request
X-elastic-product: Elasticsearch
content-type: application/json; charset=UTF-8
content-length: 647

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: input automaton is too large: 1001","index_uuid":"FG1GWmLRRrSYm9robZfurQ","index":"longname"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"longname","node":"YHW49_6lQWGv6fvmcCPb0g","reason":{"type":"query_shard_exception","reason":"failed to create query: input automaton is too large: 1001","index_uuid":"FG1GWmLRRrSYm9robZfurQ","index":"longname","caused_by":{"type":"illegal_argument_exception","reason":"input automaton is too large: 1001"}}}]},"status":400}
```

**Comment by cbuescher** [comment]
> "type":"illegal_argument_exception","reason":"input automaton is too large: 1001"

This error message comes from Lucenes [Operations](https://github.com/apache/lucene/blob/b292151f216424a65fdebbf0552e3c62c4505da7/lucene/core/src/java/org/apache/lucene/util/automaton/Operations.java#L1311) class and the underlying constant seems to be baked in at 1000 to protect against large automata.
Since >1000 character prefixes are not exactly standard use cases, it would be interesting to understand under which circumstances this problem arises for you and to think about potential workarounds before upping the limit here.

**Comment by jamshid** [comment]
Thanks for identifying the limiting code, @cbuescher. The real index's field has a filename like structure that sometimes gets very long and deep. Users can search using a prefix e.g. to find only the objects underneath a deep "directory". This isn't doing anything fancy like regex or case-insensitive searching. Hopefully this is not a bad use case for search?

I see https://github.com/elastic/elasticsearch/issues/82923 but not sure it's related, that's only about regex searches? 

Is there any workaround or different way to do the prefix search that doesn't hit this limit?

**Comment by cbuescher** [comment]
> Is there any workaround or different way to do the prefix search that doesn't hit this limit?

If you are able to map the field differently, you might be able to use the [wildcard field type](https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html#wildcard-field-type) that typically improves wildcard search performance on keyword-like fields. See [this blog post for more information](https://www.elastic.co/de/blog/find-strings-within-strings-faster-with-the-new-elasticsearch-wildcard-field) about the tradeoffs.

**Comment by cbuescher** [comment]
I'm going to close this issue for now since using wildcard field seems reasonable with such long prefix queries instead of extending the protection limit. Please reopen if you want to discuss this issue further.

**Comment by jamshid** [comment]
Thanks, can this be reopened as a feature request? 
A 1000 character string is not very long. 
A wildcard search does not solve the problem because that could match other subdirectories. 
The Lucene code has a TODO comment that the recursion is not ideal.
If that limit were configurable even just to 2000 that would help a lot. I guess at worst the stack size would have to be increased in the Elasticsearch jvm.

**Comment by cbuescher** [comment]
@jamshid I think there's a misunderstanding here

>  A wildcard search does not solve the problem because that could match other subdirectories.

I wasn't suggesting a wildcard query but mapping the current "keyword" fields as a "wildcard" field. That comes with some internal optimizations outlined in the blog post I linked and from my experiments isn't affected by the limit. You should be able to just run a prefix query agains that field.
Also I don't understand why a `{"wildcard" : { "myfield" : { "value" : "someverylargestring*" }}}` would be different from prefix in terms of the result set. However I'm not sure this query doesn't also suffer from the limit and it might not be as performant as switching to the wildcard field.

I'll reopen here but still think this is a good alternative strategy.

**Comment by jamshid** [comment]
Ah sorry @cbuescher I missed that. I thought you meant a wildcard search and didn't see the blog, didn't know there is a keyword-like type `wildcard`. 
I see it works but I'm worried about the sizing and performance of indexing and searching after using `keyword` since 2.x days. 
I still feel like 1000 characters is not long but will review.

**Comment by cbuescher** [comment]
Seems like we have an alternative solution here and don't need to increase the prefix limit. Closing again.
