### ISSUE TITLE
403 Error when pull Elastic Images

### ISSUE THREAD

**Issue by FabienZa** [elastic/elasticsearch#91621]
### Elasticsearch Version

8.5.1

### Java Version

_bundled_

### OS Version

4.15.0-189-generic #200-Ubuntu

### Problem Description

Hello,

I am trying to install an elastic-agent on a new server but cannot pull the elastic-agent container image (same problem with other elastic images). For example I have the same error with the kibana image, even though I don't need it on this server.

When I use the `docker pull` command, I receive an 403 error from CloudFront.

I don't have this problem on my other servers (about twenty).
I have this problem for several months.

However, images from another source doesn't have the problem. For example, I can pull an ubuntu:bionic image.

My temporary solution is to download the image to another server, save it with `docker save`, transfer it to the server that cannot pull the image and do a `docker load`. But it is very tedious during updates.

Do you know how I could remove or bypass this block from CloudFront?

Thanks a lot for your help

### Steps to Reproduce

`docker pull docker.elastic.co/beats/elastic-agent:8.5.1`

### Logs (if relevant)

Here is the output of the docker pull command :  
```bash
~/elastic-agent$ docker pull docker.elastic.co/beats/elastic-agent:8.5.1
8.5.1: Pulling from beats/elastic-agent
d0eb0fe83e8a Pulling fs layer                                                                 0.4s
92a5cd8bc972 Pulling fs layer                                                                 0.4s
1b7f5f9553b8 Pulling fs layer                                                                 0.4s
a43e85a017fe Waiting                                                                          0.4s
f9ccd3e1a8a4 Waiting                                                                          0.4s
a4267372ab5d Waiting                                                                          0.4s
4c657e194db6 Waiting                                                                          0.4s
1a7ecbb7a05b Waiting                                                                          0.4s
6de42ae596d2 Waiting                                                                          0.4s
2868e8b67592 Waiting                                                                          0.4s
032978dbe8f8 Waiting                                                                          0.4s
2cb1b2bed2a5 Waiting                                                                          0.4s
47cc0939abea Waiting                                                                          0.4s
error pulling image configuration: download failed after attempts=1: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nThe Amazon CloudFront distribution is configured to block access from your country.\nWe can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: xxx\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>"
```

> <BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size=\"1px\">The Amazon CloudFront distribution is configured to block access from your country.We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.<BR clear=\"all\">If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.<BR clear=\"all\"><HR noshade size=\"1px\"><PRE>Generated by cloudfront (CloudFront) Request ID: xxx</PRE><ADDRESS></ADDRESS></BODY>

**Comment by michaelbaamonde** [comment]
Hi, there's a [thread on our Discuss forums](https://discuss.elastic.co/t/are-you-getting-403s-when-downloading-please-read-here-first/307340/56) related to this. If you post over there, someone will help you out. I'm closing this issue since it's not an Elasticsearch-related issue. Thanks!
