### ISSUE TITLE
elasticsearch # 8.6 - DRA snapshot #2 fails

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#91635]
### CI Link

https://gradle-enterprise.elastic.co/s/qeqffkslgmx44

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.6

### Failure excerpt

Looking into the [CI log](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+periodic+dra-snapshot/2/console), the only exception that I can find is 

```
09:10:41 /tmp/jenkins2784644110295498766.sh: line 37: RM_BRANCH: unbound variable
09:10:42 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
09:10:42 runbld>>> DURATION: 658507ms
09:10:42 runbld>>> STDOUT: 284962 bytes
09:10:42 runbld>>> STDERR: 0 bytes
09:10:42 runbld>>> WRAPPED PROCESS: FAILURE (1)
```

**Comment by mark-vieira** [comment]
We're in the process of getting these jobs working.
