### ISSUE TITLE
_cat/nodes missing version number

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#9170]
[The docs](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cat-nodes.html#cat-nodes) state that `curl $host:9200/_cat/nodes` should look like;
```
% curl 192.168.56.10:9200/_cat/nodes
SP4H 4727 192.168.56.30 9300 1.4.2 1.8.0_25 72.1gb 35.4 93.9mb 79 239.1mb 0.45 3.4h d m Boneyard
```

Instead, on a 1.4.2 instance I see this;
```
$ curl localhost:9200/_cat/nodes
bender.local 192.168.69.30 7 72 1.46 d * Shanna the She-Devil
$ curl localhost:9200/_cat/nodes?v
host         ip            heap.percent ram.percent load node.role master name
bender.local 192.168.69.30            8          72 1.34 d         *      Shanna the She-Devil
```
Where there is no version reported.

This was mentioned in [this posting](https://groups.google.com/d/msgid/elasticsearch/f2fc1ffe-be74-47f8-8bd6-53c9a917b77b%40googlegroups.com?utm_medium=email&utm_source=footer) to the google group.

**Comment by clintongormley** [comment]
This appears to have been the case since the `cat` API was first added.  Perhaps the fix is just to update the documentation.

**Comment by markwalkom** [comment]
Came across an instance where having JVM/ES version info would be super handy in the output. It'd be nicer if we could add rather than update docs :)

**Comment by danielmitterdorfer** [comment]
@markwalkom Is this ticket still valid? The columns "jdk" and "version" are available in the cat API, they are just not included by default. Does that solve your problem or do you want to appear those two columns by default?

**Comment by markwalkom** [comment]
Docs are now inline with output, so happy to close :)
