### ISSUE TITLE
Make expired API keys retention period configurable

### ISSUE THREAD

**Issue by lloydmeta** [elastic/elasticsearch#91738]
## Context

1. [Invalidated](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-invalidate-api-key.html) and expired API key documents are purged (actually deleted) by `ExpiredApiKeysRemover`.
2. The expiry job at a configurable interval, defaulting to once every 24 hrs https://github.com/elastic/elasticsearch/blob/d1c5ca257e53ffb1e8e68d502c82d3b4f2c22264/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ApiKeyService.java#L161-L164
3. When the job runs, API keys that are https://github.com/elastic/elasticsearch/blob/d1c5ca257e53ffb1e8e68d502c82d3b4f2c22264/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ExpiredApiKeysRemover.java#L62-L66:
   1. Invalidated are deleted right away 
   2. Keys that are expired are kept around for a hard-coded 7 days past expiry https://github.com/elastic/elasticsearch/blob/d1c5ca257e53ffb1e8e68d502c82d3b4f2c22264/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ExpiredApiKeysRemover.java#L40

## Ask

For the use case we have, we're using API keys extensively and a great number of them have a low TTL / expiry that is quite soon after creation. It would be great to be able to set a lower threshold for deleting _expired_ API keys instead of the hardcoded threshold (3.2), similar to how the purging job run interval is configurable (2). This could potentially allow us to keep a much smaller number of expired API key documents that are of no use to us and possibly putting load on the cluster.

If this is a desirable I'd be happy to put something together.

**Comment by ywangd** [comment]
Technically this should be straightforward to implement. But from a feature perspective, it is rather odd that a setting for renetion period works only for expired keys but *not* invalidated keys. We could either:
1. Make the setting work for both with some additional work (this implies a change of behaviour for cleanning up invalidated keys but I don't think it has bwc concern)
2. Just make it work for expired keys only and come back to it in future

Also, do you need it backported to some prior version?

**Comment by lloydmeta** [comment]
> it is rather odd that a setting for renetion period works only for expired keys but _not_ invalidated keys. We could either:

You'd be in a better position to make a call on that :) 

My reading of the intent behind the code was that invalidation doesn't have a retention period because there's a obvious point in time, expressed through the user calling the invalidation endpoint, when they're not meant to be useful so there's no point keeping them around. For expiry, typically there's usually some "grace period" to account for time sync differences, etc, so a retention could be helpful for that (I've not looked through the code to see if there's some expiry tolerance built when authc API Keys in ES though) ? Just a thought.

I don't think we need this backported to a prior version.

**Comment by ywangd** [comment]
We have wanted some retention period for invalidated keys as well https://github.com/elastic/elasticsearch/issues/54391

Maybe this can be a step towards it. I personally prefer option 1. Ping @tvernum for advices.

**Comment by tvernum** [comment]
> I think the current behaviour might not have been a very conscious choice.

I'd agree with that.

Like @ywangd, I don't think there's a lot of value in having separate retention periods for invalidated vs expired keys. We know we have scenarios where one or more keys are incorrectly invalidated and then they vanish from the system almost immediately (perhaps up to 24h, but potentially within a few minutes).

I would be in favour of:
- Making the retention time configurable
- Applying it to both expired & invalidated API keys
- Increasing the default value (21d? 42d?) in a future major

**Comment by ywangd** [comment]
> We know we have scenarios where one or more keys are incorrectly invalidated and then they vanish from the system almost immediately (perhaps up to 24h, but potentially within a few minutes).

Yes, this has been causing issues in SDHs. The logs show some clients tried to authenticated with invalidated keys. But we know almost nothing about these keys (except maybe its ID). This in turns makes it hard to track down which clients are using them especially when the number of clients is high. Having invalidated keys retained for longer would be very helpful in these cases.

I can take on this work. Based on the discussion so far. I'll approach this in a few steps:
1. Recording the time when an API key is invalidated[^1]
2. Apply the existing 7 days retention logic to both expired and invalidated keys
3. Add a new setting to make the retention period configurable
4. Expose the invalidation time in responses to API calls like GetApiKey 

For "Increasing the default value (21d? 42d?) in a future major", do we need to begin now with deprecation? 

[^1]: Ideally we'd like to record who invalidate the key as well. But that can be done separately in future.

**Comment by tvernum** [comment]
> For "Increasing the default value (21d? 42d?) in a future major", do we need to begin now with deprecation?

Yes, if we decide we want to do that it would start by proposing a deprecation style warning for anyone relying on the existing default. That implies it would need to be done after the _new setting to make the retention period configurable_.

I don't think it's super urgent (I'm not too worried about whether that process leads to us changing the default in ES9,10 or 11) and we can come back to it after the setting is in place.

**Comment by ywangd** [comment]
I am closing this issue since the main ask is now implemented and will be part of 8.7.

As for exposing the new `invalidate_time` field, I created a separate issue (https://github.com/elastic/elasticsearch/issues/92404) to track it.
For future discussion of potentially changing the default retention period (7 days) to a different value, it will be tracked with the existing issue of https://github.com/elastic/elasticsearch/issues/54391
