### ISSUE TITLE
ECE: Allow user to select different monitoring deployments for different log datasets when shipping ECE deployment logs to a monitoring deployment

### ISSUE THREAD

**Issue by face0b1101** [elastic/elasticsearch#91761]
### Description

In ECE, deployments can be configured to ship log events to a monitoring deployments. However, it is not currently possible to send different log event datasets to different deployments, e.g. `elasticsearch.audit` events to a dedicated audit deployment.

I can see two convenient (for the end-user) ways of implementing this:

1. Present the user with options in the ECE Deployment UI to direct log event datasets to different deployments
2. Allow ingest pipelines to modify the `_index` metadata field, use conditionals to move documents to a new index other than `elastic-cloud-logs`, set a short lifecycle on that index using ILM, then use CCR to replicate documents to the appropriate deployments.

Proposal 1. would clearly be the easiest option for an end user. However, proposal 2. could have added benefits for other use-cases where it is desirable to move documents to different indices based on conditions.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
