### ISSUE TITLE
Recovery docs default units are unclear

### ISSUE THREAD

**Issue by brian-brazil** [elastic/elasticsearch#9177]
Hi,

On http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-indices.html the defaults are unclear as for example indices.recovery.max_bytes_per_sec has a default of 20 millibits or .0025 bytes per second - which doesn't sound right. It could be interpreted as Mb or MB (given it controls network traffic, either interpretation is plausible).

Could you check all the units and prefixes are correct on that page? I suspect they are meant to be kB and MB.

Thanks,
Brian

**Comment by clintongormley** [comment]
Hi @brian-brazil 

All of the measurements given there are in giga/mega/kilo/bytes, and lowercased for simplification.  That said, we should add a section to the "common options" page in the docs explaining this: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/common-options.html

**Comment by brian-brazil** [comment]
> lowercased for simplification

Lowercasing them doesn't simplify them unfortunately, it makes them incorrect and causes confusion and mistakes.

`kb` means kilobits, anywhere that you mean kilobytes you should either spell out the full unit name or say `kB` rather than using names which disagree with the common usage across all parts of computing.

**Comment by clintongormley** [comment]
Sometimes convenience wins over correctness.  Nobody else has found this to be an issue in the last year, so I'm going to close
