### ISSUE TITLE
`match` query on `date` field returns more than expected

### ISSUE THREAD

**Issue by marko-bekhta** [elastic/elasticsearch#91850]
### Elasticsearch Version

8.5.1

### Java Version

_bundled_

### OS Version

Linux fedora 6.0.8-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 11 15:03:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Having an index with `date` property with a couple of documents in it having different timezones running a match query results in more than one match. 

Issue discovered after upgrading from 8.5.0 to 8.5.1. It is important for the steps to reproduce that the server where ES is running is in the UTC timezone.

### Steps to Reproduce

Precondition: system timezone set to UTC.

1. Create index:
```http
PUT http://localhost:9200/zonedatetime-000001
Content-Type: application/json

{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "field0_ZonedDateTime": {
        "type": "date",
        "format": "uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSSZZZZZ'['VV']'"
      }
    }
  }
}
```
2. Add two documents:
```http
PUT http://localhost:9200/zonedatetime-000001/_doc/1
Content-Type: application/json

{
  "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]"
}
```
```http
PUT http://localhost:9200/zonedatetime-000001/_doc/2
Content-Type: application/json

{
  "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000+00:19:32[Europe/Amsterdam]"
}
```
3. Run match query (on the first document):
```http
POST http://localhost:9200/zonedatetime-000001/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": {
        "match": {
          "field0_ZonedDateTime": {
            "query": "1900-01-01T00:00:00.000000000Z[UTC]"
          }
        }
      }
    }
  }
}
```
Expected results - receive only document with ID = 1
Actual results - both documents returned.

Repeating the same steps on Elasticsearch 8.5.0 returns a single document with ID = 1.

Elasticsearch is running in docker using:
```shell
docker run --rm -ti -p 9200:9200 -p 9300:9300 --ulimit memlock=-1:-1 --memory-swappiness=0  --name es-8.5-it -e "discovery.type=single-node" -e "xpack.security.enabled=false" -e "ES_JAVA_OPTS=-Xms1g -Xmx1g" -e "cluster.routing.allocation.disk.threshold_enabled=false" elastic/elasticsearch:8.5.1
```

### Logs (if relevant)

Results of executed requests:
```json
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "zonedatetime-000001"
}
```
```json
{
  "_index": "zonedatetime-000001",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}
```
```json
{
  "_index": "zonedatetime-000001",
  "_id": "2",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 1,
  "_primary_term": 1
}
```
```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "zonedatetime-000001",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]"
        }
      },
      {
        "_index": "zonedatetime-000001",
        "_id": "2",
        "_score": 1.0,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000+00:19:32[Europe/Amsterdam]"
        }
      }
    ]
  }
}
```

**Comment by marko-bekhta** [comment]
hey @cbuescher thanks for taking a look. Yes sure. Here's the query with sorting:
```http
POST http://localhost:9200/zonedatetime-000001/_search
Content-Type: application/json

{
  "sort": [
    {
      "field0_ZonedDateTime": {
        "order": "asc"
      }
    }
  ],
  "query": {
    "match_all": {}
  }
}
```
and the results when the order is `asc`:
```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
      {
        "_index": "zonedatetime-000001",
        "_id": "1",
        "_score": null,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]"
        },
        "sort": [
          -2208988800000
        ]
      },
      {
        "_index": "zonedatetime-000001",
        "_id": "2",
        "_score": null,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000+00:19:32[Europe/Amsterdam]"
        },
        "sort": [
          -2208988800000
        ]
      }
    ]
  }
}
```
and then when the order is `desc`:
```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": null,
    "hits": [
      {
        "_index": "zonedatetime-000001",
        "_id": "1",
        "_score": null,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]"
        },
        "sort": [
          -2208988800000
        ]
      },
      {
        "_index": "zonedatetime-000001",
        "_id": "2",
        "_score": null,
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000+00:19:32[Europe/Amsterdam]"
        },
        "sort": [
          -2208988800000
        ]
      }
    ]
  }
}
```
Anything additional I check or provide you with to help identify a problem?

**Comment by cbuescher** [comment]
That is indeed odd, I see two different time values stored in my local attempt to reproduce. For the record, I also set the timezone to UTC/GMT and verified that running `date`. I'm on OSX laptop and not using docker though.
The fact that the timestamps are already not indexed correctly rule out a problem with the query. I suspect this is a weird combination of OS/JVM specific things that lead to parsing the date format incorrectly.

**Comment by cbuescher** [comment]
What JDK are you using / is the docker instance using internally. I'm not too familiar with docker, can we maybe also try to rule that out as a source of the problem if you try installing directly from the tar.gz distribution?

**Comment by marko-bekhta** [comment]
I was also looking at the release notes here - https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.5.1.html and couldn't see any potential change that would lead to this except the JDK update 🙈 

The image we are using is the official one from here - https://hub.docker.com/layers/elastic/elasticsearch/8.5.1/images/sha256-c00ffbda25f43fb24ab9ec199b0f162087cd0a7d2fa8d17fd0dd926b97f8e4e3?context=explore

and here're the results going into the container:
```bash
docker exec -it es-8.5-it /bin/bash
elasticsearch@78cdce69d66e:~$ java --version
bash: java: command not found
elasticsearch@78cdce69d66e:~$ ls -la
total 2212
drwxrwxr-x. 1 root          root     212 Nov 24 09:22 .
drwxr-xr-x. 1 root          root     508 Nov 10 01:14 ..
-rw-r--r--. 1 root          root     220 Nov 10 01:14 .bash_logout
-rw-r--r--. 1 root          root    3771 Nov 10 01:14 .bashrc
drwxrwxr-x. 1 elasticsearch root       6 Nov 24 09:22 .cache
-rw-r--r--. 1 root          root     807 Nov 10 01:14 .profile
-r--r--r--. 1 root          root    3860 Nov  9 21:01 LICENSE.txt
-r--r--r--. 1 root          root 2235851 Nov  9 21:05 NOTICE.txt
-r--r--r--. 1 root          root    8107 Nov  9 21:01 README.asciidoc
drwxrwxr-x. 1 elasticsearch root    1020 Nov 10 01:14 bin
drwxrwxr-x. 1 elasticsearch root     352 Nov 24 09:22 config
drwxrwxr-x. 1 elasticsearch root      82 Nov 24 09:52 data
dr-xr-xr-x. 1 root          root      68 Nov  9 21:08 jdk
dr-xr-xr-x. 1 root          root    1790 Nov  9 21:08 lib
drwxrwxr-x. 1 elasticsearch root      48 Nov 24 09:22 logs
dr-xr-xr-x. 1 root          root    1864 Nov  9 21:09 modules
drwxrwxr-x. 1 elasticsearch root       0 Nov  9 21:05 plugins
elasticsearch@78cdce69d66e:~$ ./jdk/bin/java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-21)
OpenJDK 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
```

**Comment by marko-bekhta** [comment]
and I'm downloading the tar to try it without docker ⏳

**Comment by marko-bekhta** [comment]
Startup log showing the system/JDK info:

```bash
[2022-11-24T10:07:02,327][INFO ][o.e.n.Node               ] [fedora] version[8.5.1], pid[22388], build[tar/c1310c45fc534583afe2c1c03046491efba2bba2/2022-11-09T21:02:20.169855900Z], OS[Linux/6.0.9-200.fc36.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21]
[2022-11-24T10:07:02,330][INFO ][o.e.n.Node               ] [fedora] JVM home [/home/marko/development/tools/elasticsearch-8.5.1-linux-x86_64/elasticsearch-8.5.1/jdk], using bundled JDK [true]
[2022-11-24T10:07:02,330][INFO ][o.e.n.Node               ] [fedora] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-11608535201898835008, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms31744m, -Xmx31744m, -XX:MaxDirectMemorySize=16642998272, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=25, -Des.distribution.type=tar, --module-path=/home/marko/development/tools/elasticsearch-8.5.1-linux-x86_64/elasticsearch-8.5.1/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]
```
And the results are the same - two documents are found and same result for sorting 😢

**Comment by cbuescher** [comment]
Thanks for your work helping to get closer to a reproduction. It seems we can rule out docker and have a concrete JVM (Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21]) and OS (Linux fedora 6.0.8-200.fc36.x86_64) combo to try next. I'll try this later today on a Linux box, probably not Fedora but maybe using the same JVM already shows something on my end.

**Comment by cbuescher** [comment]
Might indeed be a matter of the JVM. I tried running the repro above on Ubuntu with the bundled JVM (Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21) and searching all docs with sort shows they get indexed with the same UTC timestamp. When switching to another older JVM (Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/18.0.2/18.0.2+9-61) I get different sort values. 
Maybe @pgomulka or somebody else from the core infra team know how different JVMs might differ in the date parsing behaviour and what might have changed here recently? Maybe also in combo with the Linux distros.

**Comment by thecoop** [comment]
Those two times do have different representations between jdks...

18:

    1900-01-01T00:00Z[UTC]
    1900-01-01T00:00+00:19:32[Europe/Amsterdam]

19:

    1900-01-01T00:00Z[UTC]
    1899-12-31T23:40:28Z[Europe/Amsterdam]

**Comment by grcevski** [comment]
I wonder if this is related to the same issue that you found earlier @thecoop ? https://bugs.openjdk.org/browse/JDK-4511638

**Comment by thecoop** [comment]
Hmm, I don't think so, `ZonedDateTime` doesn't use floating point anywhere in its representation, and parsing uses `BigDecimal`

**Comment by cbuescher** [comment]
fyi my reproductions on Ubuntu 22.04.1 LTS:

ES 8.5.0, bundled JVM Oracle Corporation/OpenJDK 64-Bit Server VM/19/19+36-2238
* both of the above timestamps get parsed to different long values (shown when matching on all docs and sorting)

ES 8.5.1, bundled JVM Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21
* both of the above timestamps get parsed to same long value

**Comment by thecoop** [comment]
The difference is probably due to https://bugs.openjdk.org/browse/JDK-8292579, which changedtzdata to 2022c - this affects several time zones, including `Europe/Amsterdam`. These are probably the root cause of the behaviour changes.

**Comment by marko-bekhta** [comment]
Hey, @thecoop, thanks for figuring this one out! 😃 and thanks to the rest of the team too!
