### ISSUE TITLE
Unable to start ElasticSearch in Windows 11

### ISSUE THREAD

**Issue by yuvrajbset** [elastic/elasticsearch#91867]
### CI Link

NA

### Repro line

NA

### Does it reproduce?

Didn't try

### Applicable branches

NA

### Failure excerpt

Hello ES Team,

I was unable to run the ElasticSearch in Windows 11 system with Java 19 installed. Please find the screenshot of the command prompt and Web browser below.
![image](https://user-images.githubusercontent.com/9104063/203617738-c985f9b1-a071-4d7b-843b-93fa67e01e75.png)
![image](https://user-images.githubusercontent.com/9104063/203617883-463a54d7-8e44-4ea7-ab35-d367bbcac00f.png)

Please help me out with running the ElasticSearch in my system.

Thanks and Regards,
yuvrajbset

**Comment by cbuescher** [comment]
Hi @yuvrajbset! Your question is better suited to the support forums over at https://discuss.elastic.co/. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by yuvrajbset** [comment]
Thanks for your reply. I would raise the issue at  https://discuss.elastic.co/.
