### ISSUE TITLE
Elasticsearch validate query API fails for query with highlight

### ISSUE THREAD

**Issue by Kaushal28** [elastic/elasticsearch#91941]
### Elasticsearch Version

8.5

### Java Version

_bundled_

### OS Version

Linux - Ubuntu

### Problem Description

I am trying to use `highlight` with my query as mentioned here: https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html.

This query works correctly with `search` API but before actually executing the expensive query, I want to validate it using `validation` API provided by elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html

But this fails with an error message:

    org.elasticsearch.common.ParsingException: request does not support [highlight]

So how can I validate the query with highlight without executing it?

I found a similar problem on ES discussion forum: https://discuss.elastic.co/t/validation-api-got-error-with-highlight-org-elasticsearch-common-parsingexception-request-does-not-support-highlight/248953 but it doesn't have any solution.

### Steps to Reproduce

Call `_validate` endpoint with following body:

```
{
  "query": {
    "match": { "content": "kimchy" }
  },
  "highlight": {
    "fields": {
      "content": {}
    }
  }
}
```

**Comment by javanna** [comment]
The validate endpoint supports only the `query` section of a search request, as it is used to validate a query. Any other section is rejected, `highlight` included. There is no way to validate the `highlight` section of a search request without executing the search itself.
