### ISSUE TITLE
JCenter for plugins

### ISSUE THREAD

**Issue by stackmagic** [elastic/elasticsearch#9198]
From what I gathered, one can [install plugins from maven](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-plugins.html). Do you also support jcenter as a source? If not, would you consider adding it?

**Comment by dadoonet** [comment]
@stackmagic Is it the link to use? http://jcenter.bintray.com/
It sounds like to me that jcenter also act as a maven central mriror. What is on jcenter which is not available on maven central?

**Comment by stackmagic** [comment]
Yes, that's the root url of the jcenter repo. It is a mirror for central and also includes packages by people like you and me.

You can have your personal repo and have [your own packages included in jcenter](https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html) if they fulfill a few criterias (signing is not one of them. this lower entry barrier being the reason why I chose jcenter for my own packages: [example](https://bintray.com/stackmagic/maven)).

So it's a grand unified repo for everything maven (plus they can do debian repos and all kinds of stuff but that's not in the scope of this discussion, I guess).

**Comment by nik9000** [comment]
> packages by people like you and me

Just my 2 cents and this probably isn't the right place for this, but huh?  Sonatype made the process of getting my code into central pretty simple.  Is there some barrier to entry I blundered through without paying attention?

I'm all for there being another path into maven central that's relatively easy.  It doesn't sit well with me that its mostly Sonatype these days unless you are with a foundation.  But why another central?

**Comment by stackmagic** [comment]
I just couldn't be bothered to set up the signing stuff for central. Bintray makes it all pretty easy with gradle and their upload plugin.

I opened this ticket primarily to see what you think about jcenter (assuming everybody already knows jcenter/bintray) and because I'm in the process of revamping an outdated river plugin which I would like to distribute trough a repo once I'm done (instead of having to manually download and install a zip file). Since I'm already using bintray and am happy with them I figured having their repo supported too would be nice.

In a wider context: gradleware does all their new community-plugins management via bintray. They have a repo and every user can apply to have their gradle plugin included in their repo. They'll then show up at [http://plugins.gradle.org/](http://plugins.gradle.org/) and can be used from the build script without having to add a repo or anything. It's a pretty neat way to allow users to easily publish their own plugins and make them available to the world.

I've never used ES before and maybe you already have something similar like the gradle guys do. I only scrolled trough the ES docs today and may have skipped over that part. If not, a similar approach to community plugins might liven up your plugin ecosystem and make it more accessible to plugin writers?

Just a few thoughts. But I'd be happy if you'd simply support the jcenter repo. The rest may be something for the longer term.

**Comment by dadoonet** [comment]
@stackmagic Thanks for the suggestion. We will change the plugin manager code in a near future so we can try to see how to make JCenter or any other repository (such as enterprise repository) more easily integrable. It could be with another option within the plugin manager or using a setting in `elasticsearch.yml`.

cc @tlrx

**Comment by clintongormley** [comment]
Given that plugins can be installed from any URL, and there have no further requests for this, I'm going to close this issue
