### ISSUE TITLE
What is the correct Query DSL like to get same result from sql like this

### ISSUE THREAD

**Issue by biggerdamage** [elastic/elasticsearch#91996]
### Elasticsearch Version
8.4.1

### Installed Plugins
No response

### Problem Description
Here is a sql:

`select tname,userId,ip,time from tableA group by tname,userId,ip`

How to generate Query DSL to get same result from sql above?

**Comment by gmarouli** [comment]
Hello @biggerdamage thank you for your question. I think this question would fit better in our [forum](https://discuss.elastic.co/).  Please feel free to post it there. For now, I will close this issue.
