### ISSUE TITLE
Chunked HTTP APIs send (final/empty) chunk in response to HEAD requests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#92032]
Responses to `HEAD` requests should contain no body, but we send an empty body instead. That's indistinguishable for one-shot APIs, but with chunked encoding this means we send a single empty chunk as a terminator:

```
00000000  48 45 41 44 20 2f 5f 61  6c 6c 20 48 54 54 50 2f   HEAD /_a ll HTTP/
00000010  31 2e 31 0d 0a 48 6f 73  74 3a 20 6c 6f 63 61 6c   1.1..Hos t: local
00000020  68 6f 73 74 3a 39 32 30  30 0d 0a 41 63 63 65 70   host:920 0..Accep
00000030  74 2d 45 6e 63 6f 64 69  6e 67 3a 20 67 7a 69 70   t-Encodi ng: gzip
00000040  0d 0a 0d 0a                                        ....
    00000000  48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d   HTTP/1.1  200 OK.
    00000010  0a 58 2d 65 6c 61 73 74  69 63 2d 70 72 6f 64 75   .X-elast ic-produ
    00000020  63 74 3a 20 45 6c 61 73  74 69 63 73 65 61 72 63   ct: Elas ticsearc
    00000030  68 0d 0a 63 6f 6e 74 65  6e 74 2d 74 79 70 65 3a   h..conte nt-type:
    00000040  20 61 70 70 6c 69 63 61  74 69 6f 6e 2f 6a 73 6f    applica tion/jso
    00000050  6e 0d 0a 54 72 61 6e 73  66 65 72 2d 45 6e 63 6f   n..Trans fer-Enco
    00000060  64 69 6e 67 3a 20 63 68  75 6e 6b 65 64 0d 0a 0d   ding: ch unked...
    00000070  0a 30 0d 0a 0d 0a                                  .0....
              ^^ should have stopped here!
```

This became particularly noticeable with https://github.com/elastic/elasticsearch/pull/92016 because `HEAD /<index>` is the recognised way to determine if an index exists, but really this is a general problem with the infrastructure introduced in https://github.com/elastic/elasticsearch/pull/88311.

**Comment by original-brownbear** [comment]
@DaveCTurner yea looks suspicious, on it now.

**Comment by DaveCTurner** [comment]
For the record the only other endpoint I can see that supports `HEAD` requests and chunked responses today is `/{index}/_mapping/{type}` and only from 8.5.0 onwards (#89906). This API only works in v7-compatibility mode, it's removed in the v8 API, and it kind of ceased to be useful way back when we removed the ability for indices to have multiple mapping types back in 6.0. So I expect that in practice this bug has no impact in any released versions.

**Comment by original-brownbear** [comment]
> So I expect that in practice this bug has no impact in any released versions.

++ also I hunted this down. Fix incoming, it's Netty indeed but there's an "official" fix for this.

**Comment by pencakj** [comment]
Response to HEAD has empty body HEAD/<index> on es8.13.2
`0000   52 54 00 73 98 09 00 22 bd f8 19 ff 08 00 45 00   RT.s..."......E.
0010   01 71 f5 c8 40 00 3d 06 8b 3b 0a 07 39 34 0a 06   .q..@.=..;..94..
0020   6e 42 e0 b2 79 17 39 d4 e3 49 60 fa 28 31 50 18   nB..y.9..I`.(1P.
0030   02 94 8e bd 00 00 48 45 41 44 20 2f 63 61 6d 2d   ......HEAD /cam-
0040   70 73 74 64 65 76 30 31 2d 6f 70 65 72 61 74 65   pstdev01-operate
0050   2d 65 76 65 6e 74 2d 38 2e 33 2e 30 5f 20 48 54   -event-8.3.0_ HT
0060   54 50 2f 31 2e 31 0d 0a 61 63 63 65 70 74 3a 20   TP/1.1..accept: 
0070   61 70 70 6c 69 63 61 74 69 6f 6e 2f 76 6e 64 2e   application/vnd.
0080   65 6c 61 73 74 69 63 73 65 61 72 63 68 2b 6a 73   elasticsearch+js
0090   6f 6e 3b 20 63 6f 6d 70 61 74 69 62 6c 65 2d 77   on; compatible-w
00a0   69 74 68 3d 37 0d 0a 78 2d 65 6c 61 73 74 69 63   ith=7..x-elastic
00b0   2d 63 6c 69 65 6e 74 2d 6d 65 74 61 3a 20 65 73   -client-meta: es
00c0   3d 38 2e 31 33 2e 34 2c 6a 76 3d 32 31 2c 74 3d   =8.13.4,jv=21,t=
00d0   38 2e 31 33 2e 34 2c 68 63 3d 34 2e 31 2e 35 0d   8.13.4,hc=4.1.5.
00e0   0a 68 6f 73 74 3a 20 68 61 70 72 6f 78 79 2d 64   .host: haproxy-d
00f0   65 76 2e 6b 62 2e 63 7a 3a 38 30 0d 0a 75 73 65   ev.kb.cz:80..use
0100   72 2d 61 67 65 6e 74 3a 20 65 6c 61 73 74 69 63   r-agent: elastic
0110   73 65 61 72 63 68 2d 6a 61 76 61 2f 38 2e 31 33   search-java/8.13
0120   2e 34 20 28 4a 61 76 61 2f 32 31 2e 30 2e 31 29   .4 (Java/21.0.1)
0130   0d 0a 61 75 74 68 6f 72 69 7a 61 74 69 6f 6e 3a   ..authorization:
0140   20 42 61 73 69 63 20 57 46 68 66 52 56 4e 66 51    Basic WFhfRVNfQ
0150   30 46 4e 58 30 35 66 55 45 78 42 56 45 5a 50 55   0FNX05fUExBVEZPU
0160   6b 30 36 4a 48 56 71 4d 54 45 74 59 6e 51 34 4e   k06JHVqMTEtYnQ4N
0170   30 31 54 4d 7a 5a 55 56 53 34 3d 0d 0a 0d 0a      01TMzZUVS4=....`

`0000   00 22 bd f8 19 ff 52 54 00 73 98 09 08 00 45 00   ."....RT.s....E.
0010   01 df 3a 98 40 00 3e 06 44 fe 0a 06 6e 42 0a 07   ..:.@.>.D...nB..
0020   39 34 79 17 e0 b2 60 fa 28 31 39 d4 e4 92 50 18   94y...`.(19...P.
0030   00 20 db 9f 00 00 48 54 54 50 2f 31 2e 31 20 32   . ....HTTP/1.1 2
0040   30 30 20 4f 4b 0d 0a 78 2d 65 6c 61 73 74 69 63   00 OK..x-elastic
0050   2d 70 72 6f 64 75 63 74 3a 20 45 6c 61 73 74 69   -product: Elasti
0060   63 73 65 61 72 63 68 0d 0a 63 6f 6e 74 65 6e 74   csearch..content
0070   2d 74 79 70 65 3a 20 61 70 70 6c 69 63 61 74 69   -type: applicati
0080   6f 6e 2f 76 6e 64 2e 65 6c 61 73 74 69 63 73 65   on/vnd.elasticse
0090   61 72 63 68 2b 6a 73 6f 6e 3b 63 6f 6d 70 61 74   arch+json;compat
00a0   69 62 6c 65 2d 77 69 74 68 3d 37 0d 0a 78 2d 65   ible-with=7..x-e
00b0   6e 76 6f 79 2d 75 70 73 74 72 65 61 6d 2d 73 65   nvoy-upstream-se
00c0   72 76 69 63 65 2d 74 69 6d 65 3a 20 31 30 0d 0a   rvice-time: 10..
00d0   73 74 72 69 63 74 2d 74 72 61 6e 73 70 6f 72 74   strict-transport
00e0   2d 73 65 63 75 72 69 74 79 3a 20 6d 61 78 2d 61   -security: max-a
00f0   67 65 3d 33 31 35 33 36 30 30 30 3b 20 69 6e 63   ge=31536000; inc
0100   6c 75 64 65 53 75 62 44 6f 6d 61 69 6e 73 3b 20   ludeSubDomains; 
0110   70 72 65 6c 6f 61 64 0d 0a 78 2d 78 73 73 2d 70   preload..x-xss-p
0120   72 6f 74 65 63 74 69 6f 6e 3a 20 31 3b 20 6d 6f   rotection: 1; mo
0130   64 65 3d 62 6c 6f 63 6b 0d 0a 78 2d 66 72 61 6d   de=block..x-fram
0140   65 2d 6f 70 74 69 6f 6e 73 3a 20 53 41 4d 45 4f   e-options: SAMEO
0150   52 49 47 49 4e 0d 0a 78 2d 63 6f 6e 74 65 6e 74   RIGIN..x-content
0160   2d 74 79 70 65 2d 6f 70 74 69 6f 6e 73 3a 20 4e   -type-options: N
0170   6f 73 6e 69 66 66 0d 0a 72 65 66 65 72 72 65 72   osniff..referrer
0180   2d 70 6f 6c 69 63 79 3a 20 73 74 72 69 63 74 2d   -policy: strict-
0190   6f 72 69 67 69 6e 2d 77 68 65 6e 2d 63 72 6f 73   origin-when-cros
01a0   73 2d 6f 72 69 67 69 6e 0d 0a 64 61 74 65 3a 20   s-origin..date: 
01b0   57 65 64 2c 20 30 38 20 4a 61 6e 20 32 30 32 35   Wed, 08 Jan 2025
01c0   20 30 39 3a 33 36 3a 34 32 20 47 4d 54 0d 0a 74    09:36:42 GMT..t
01d0   72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69 6e 67   ransfer-encoding
01e0   3a 20 63 68 75 6e 6b 65 64 0d 0a 0d 0a            : chunked....`

**Comment by pencakj** [comment]
Response to `HEAD/<index>` contain EMPTY body, causing troubles for HAProxy, es8.13.2:

```
0000   52 54 00 73 98 09 00 22 bd f8 19 ff 08 00 45 00   RT.s..."......E.
0010   01 71 f5 c8 40 00 3d 06 8b 3b 0a 07 39 34 0a 06   .q..@.=..;..94..
0020   6e 42 e0 b2 79 17 39 d4 e3 49 60 fa 28 31 50 18   nB..y.9..I`.(1P.
0030   02 94 8e bd 00 00 48 45 41 44 20 2f 63 61 6d 2d   ......HEAD /cam-
0040   70 73 74 64 65 76 30 31 2d 6f 70 65 72 61 74 65   pstdev01-operate
0050   2d 65 76 65 6e 74 2d 38 2e 33 2e 30 5f 20 48 54   -event-8.3.0_ HT
0060   54 50 2f 31 2e 31 0d 0a 61 63 63 65 70 74 3a 20   TP/1.1..accept: 
0070   61 70 70 6c 69 63 61 74 69 6f 6e 2f 76 6e 64 2e   application/vnd.
0080   65 6c 61 73 74 69 63 73 65 61 72 63 68 2b 6a 73   elasticsearch+js
0090   6f 6e 3b 20 63 6f 6d 70 61 74 69 62 6c 65 2d 77   on; compatible-w
00a0   69 74 68 3d 37 0d 0a 78 2d 65 6c 61 73 74 69 63   ith=7..x-elastic
00b0   2d 63 6c 69 65 6e 74 2d 6d 65 74 61 3a 20 65 73   -client-meta: es
00c0   3d 38 2e 31 33 2e 34 2c 6a 76 3d 32 31 2c 74 3d   =8.13.4,jv=21,t=
00d0   38 2e 31 33 2e 34 2c 68 63 3d 34 2e 31 2e 35 0d   8.13.4,hc=4.1.5.
00e0   0a 68 6f 73 74 3a 20 68 61 70 72 6f 78 79 2d 64   .host: haproxy-d
00f0   65 76 2e 6b 62 2e 63 7a 3a 38 30 0d 0a 75 73 65   ev.kb.cz:80..use
0100   72 2d 61 67 65 6e 74 3a 20 65 6c 61 73 74 69 63   r-agent: elastic
0110   73 65 61 72 63 68 2d 6a 61 76 61 2f 38 2e 31 33   search-java/8.13
0120   2e 34 20 28 4a 61 76 61 2f 32 31 2e 30 2e 31 29   .4 (Java/21.0.1)
0130   0d 0a 61 75 74 68 6f 72 69 7a 61 74 69 6f 6e 3a   ..authorization:
0140   20 42 61 73 69 63 20 57 46 68 66 52 56 4e 66 51    Basic WFhfRVNfQ
0150   30 46 4e 58 30 35 66 55 45 78 42 56 45 5a 50 55   0FNX05fUExBVEZPU
0160   6b 30 36 4a 48 56 71 4d 54 45 74 59 6e 51 34 4e   k06JHVqMTEtYnQ4N
0170   30 31 54 4d 7a 5a 55 56 53 34 3d 0d 0a 0d 0a      01TMzZUVS4=....
```
```
0000   00 22 bd f8 19 ff 52 54 00 73 98 09 08 00 45 00   ."....RT.s....E.
0010   01 df 3a 98 40 00 3e 06 44 fe 0a 06 6e 42 0a 07   ..:.@.>.D...nB..
0020   39 34 79 17 e0 b2 60 fa 28 31 39 d4 e4 92 50 18   94y...`.(19...P.
0030   00 20 db 9f 00 00 48 54 54 50 2f 31 2e 31 20 32   . ....HTTP/1.1 2
0040   30 30 20 4f 4b 0d 0a 78 2d 65 6c 61 73 74 69 63   00 OK..x-elastic
0050   2d 70 72 6f 64 75 63 74 3a 20 45 6c 61 73 74 69   -product: Elasti
0060   63 73 65 61 72 63 68 0d 0a 63 6f 6e 74 65 6e 74   csearch..content
0070   2d 74 79 70 65 3a 20 61 70 70 6c 69 63 61 74 69   -type: applicati
0080   6f 6e 2f 76 6e 64 2e 65 6c 61 73 74 69 63 73 65   on/vnd.elasticse
0090   61 72 63 68 2b 6a 73 6f 6e 3b 63 6f 6d 70 61 74   arch+json;compat
00a0   69 62 6c 65 2d 77 69 74 68 3d 37 0d 0a 78 2d 65   ible-with=7..x-e
00b0   6e 76 6f 79 2d 75 70 73 74 72 65 61 6d 2d 73 65   nvoy-upstream-se
00c0   72 76 69 63 65 2d 74 69 6d 65 3a 20 31 30 0d 0a   rvice-time: 10..
00d0   73 74 72 69 63 74 2d 74 72 61 6e 73 70 6f 72 74   strict-transport
00e0   2d 73 65 63 75 72 69 74 79 3a 20 6d 61 78 2d 61   -security: max-a
00f0   67 65 3d 33 31 35 33 36 30 30 30 3b 20 69 6e 63   ge=31536000; inc
0100   6c 75 64 65 53 75 62 44 6f 6d 61 69 6e 73 3b 20   ludeSubDomains; 
0110   70 72 65 6c 6f 61 64 0d 0a 78 2d 78 73 73 2d 70   preload..x-xss-p
0120   72 6f 74 65 63 74 69 6f 6e 3a 20 31 3b 20 6d 6f   rotection: 1; mo
0130   64 65 3d 62 6c 6f 63 6b 0d 0a 78 2d 66 72 61 6d   de=block..x-fram
0140   65 2d 6f 70 74 69 6f 6e 73 3a 20 53 41 4d 45 4f   e-options: SAMEO
0150   52 49 47 49 4e 0d 0a 78 2d 63 6f 6e 74 65 6e 74   RIGIN..x-content
0160   2d 74 79 70 65 2d 6f 70 74 69 6f 6e 73 3a 20 4e   -type-options: N
0170   6f 73 6e 69 66 66 0d 0a 72 65 66 65 72 72 65 72   osniff..referrer
0180   2d 70 6f 6c 69 63 79 3a 20 73 74 72 69 63 74 2d   -policy: strict-
0190   6f 72 69 67 69 6e 2d 77 68 65 6e 2d 63 72 6f 73   origin-when-cros
01a0   73 2d 6f 72 69 67 69 6e 0d 0a 64 61 74 65 3a 20   s-origin..date: 
01b0   57 65 64 2c 20 30 38 20 4a 61 6e 20 32 30 32 35   Wed, 08 Jan 2025
01c0   20 30 39 3a 33 36 3a 34 32 20 47 4d 54 0d 0a 74    09:36:42 GMT..t
01d0   72 61 6e 73 66 65 72 2d 65 6e 63 6f 64 69 6e 67   ransfer-encoding
01e0   3a 20 63 68 75 6e 6b 65 64 0d 0a 0d 0a            : chunked....
```
