### ISSUE TITLE
SQL: Get data from multiple indices

### ISSUE THREAD

**Issue by alissan** [elastic/elasticsearch#92057]
### Description

I have monthly indices like this:

```
nasa-2022.01
nasa-2022.02
.
.
nasa-2022.12
```

I want to create a query on nasa-2020.05, nasa-2022.06 and nasa-2022.07
So i can't create query like this:

`select * from "nasa-2020.*"`

I need create query on multiple indices like this:

`select * from "nasa-2022.05,nasa-2022.06,nasa-2022.07"`

aliases doesn't meet this need, because the months changing with every query.

**Comment by bpintea** [comment]
@alissan thanks for giving SQL a try.
The functionality asked for, as described, is practically a JOIN, which we don't plan to implement.
However, if the indices share the same (or very similar) mapping, you'll want to use an index pattern, as you are actually trying. To that end, why not make your pattern more inclusive, like `"nasa-20*"`, or more selective to fit your pattern? You can also create an [alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/aliases.html) to those indices you're interested in.
I'll go ahead and close this issue for now, but feel free to reopen it if you think I misunderstood your case.
There's also a forum where you can get more help, https://discuss.elastic.co/ , feel free to make use of it as well.
