### ISSUE TITLE
Dynamic configuration load via "conf.d" folder (to change settings without editing elasticsearch.yml)

### ISSUE THREAD

**Issue by ZaneCEO** [elastic/elasticsearch#92075]
### Description

I'd like to edit a few Elasticsearch settings (for example: `network.host`), but I don't want to edit `/etc/elasticsearch/elasticsearch.yml` directly. What I'd like to do is to add my settings to my own file and put it in an hypothetical `/etc/elasticsearch/conf.d` folder, do be included automatically.

This approach is widespread with multiple other software I use (Nginx, Apache, MySQL, PHP just to name a few).

Elasticsearch already does what i need with `/etc/elasticsearch/jvm.options.d`, but that folder is just for the the JVM options, not for ES own settings.

[Related discuss](https://discuss.elastic.co/t/elasticsearch-8-is-there-a-conf-d-folder-to-change-settings-without-editing-elasticsearch-yml/320076)

**Comment by stu-elastic** [comment]
We had this feature in ES 1 but there were issues (can't recall the exact issues right now), so we removed it.  If this features is still desirable, please reopen and vote for it.  I'm closing it since we do not plan on working on it.
