### ISSUE TITLE
Attempt to convert string to json rather than rejecting entire document. (Converse use case of #12366)

### ISSUE THREAD

**Issue by billfnt** [elastic/elasticsearch#92079]
### Description

Our elasticsearch cluster is currently rejecting documents because the mapping is expecting an object for a given field, but instead of an object the value is a string representation of a json object.  We're observing this in 7.17.1 and it is assumed to be the same across all versions.

To highlight he current behavior, one can create a new index and ingest two documents:
```
PUT test-index
PUT test-index/_doc/doc1
{
  "spec": {
    "color": "blue",
    "size": "large"
  }
}
PUT test-index/_doc/doc2
{
  "spec": "{\"color\": \"green\",\"size\": \"medium\"}"
}
```

The current behavior is to reject the second document with this message:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "object mapping for [spec] tried to parse field [spec] as object, but found a concrete value"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "object mapping for [spec] tried to parse field [spec] as object, but found a concrete value"
  },
  "status" : 400
}
```

If elasticsearch detects this type of mapper_parsing_exception, we would like to see elasticsearch attempt to convert the provided concrete value to an object.  Doing so would save organizations considerable data engineering effort.  If the data cannot be converted to an object, then rejecting the document or optionally just ignoring the field based on an `ignore_malformed` setting would of course be appropriate.

There certainly are tools available to handle this with an ingest or logstash pipeline or adjusting the data format at the source.  Implementing any of those, however, typically leads to discussions/debates between the originators of the data and teams responsible for the ELK stack. Having elasticsearch handle these level of variance would free up those organizations to spend more time generating value from the data in elasticsearch as opposed to expending that effort on getting the data into elasticsearch.

If performing this function within elasticsearch proper is not considered viable or acceptable, for this particular use case, it would be acceptable to have this capability added to the core of logstash, meaning that if logstash were to receive this message from elasticsearch, we would want logstash to attempt to convert the field to json automatically and then attempt to index the document again.

**Comment by DaveCTurner** [comment]
I wasn't sure to which team to direct this. I don't think Elasticsearch should do this by default but it seems like the sort of thing for which you might be able to write a script (maybe it's even possible via a script already) so I'm starting with the Core/Infra folks.

**Comment by stu-elastic** [comment]
You can have an script ingest processor that checks the type of the value and deserializes it if it's a string.
