### ISSUE TITLE
Investigate painless execute API for CCS

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#92126]
Trying to hit the [execute API](https://www.elastic.co/guide/en/elasticsearch/painless/8.5/painless-execute-api.html) with an index that in available via cross cluster search will fail with an `IllegalArgumentException`: `Cross-cluster calls are not supported in this context but remote indices were requested`

That is because `PainlessExecuteAction`'s [`TransportAction`](https://github.com/elastic/elasticsearch/blob/8.5/modules/lang-painless/src/main/java/org/elasticsearch/painless/action/PainlessExecuteAction.java#L462) is a [`TransportSingleShardAction`](https://github.com/elastic/elasticsearch/blob/8.5/server/src/main/java/org/elasticsearch/action/support/single/shard/TransportSingleShardAction.java#L153) which uses [`IndexNameExpressionResolver.concreteIndices`](https://github.com/elastic/elasticsearch/blob/8.5/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L331), which does not support remote clusters.

What would it take it enable PainlessExecuteAction to support CCS?

Kibana uses the execute api to validate runtime fields on edit, see https://github.com/elastic/kibana/issues/145861

**Comment by javanna** [comment]
Is this somehow connected to https://github.com/elastic/elasticsearch/issues/73488 ? How is Kibana going from an index pattern to an index right now?

**Comment by stu-elastic** [comment]
@javanna both relate to resolving mappings for indices, but this is about getting the mappings for a CCS index in execute so that kibana can use execute to validate the script.

**Comment by javanna** [comment]
Agreed, I just don't follow why we would be solving the CCS scenario if we don't know yet how Kibana deals with calling painless execute on the local cluster, which is why I asked how Kibana picks an index out of the index pattern.

**Comment by stu-elastic** [comment]
Perhaps I'm missing something.

Kibana passes the index name and the document to painless execute, painless execute fetches the mappings.

So the question is what would it take for painless execute to get the mapping for a CCS index so that kibana can call painless execute against the CCS index.

**Comment by stu-elastic** [comment]
@mattkime, do you have any insight into @javanna's question?

> How is Kibana going from an index pattern to an index right now?

**Comment by thecoop** [comment]
I've had an initial look, and how we could do this is:
* Refactor `TransportSearchAction` to separate out the cross-cluster parts from the search parts
* Rewrite `PainlessExecuteAction` to use the cross-cluster base class to execute painless queries cross-cluster.

The two classes are completely different at the moment, so it would likely be a full re-implementation of `PainlessExecuteAction`. This would be quite a lot of work to do.

**Comment by javanna** [comment]
@thecoop I thought that what is missing in painless execute is retrieving mappings for a remote index. What are the bits that you'd reuse from TransportSearchAction?

**Comment by mattkime** [comment]
>How is Kibana going from an index pattern to an index right now?

Its looking at the `_index` field on a given document

**Comment by thecoop** [comment]
@javanna I'm referring to all the cross-cluster messsaging & management code - eg `remoteClusterService`, `executeRequest` handling cross-cluster comms & listeners, remote shards interactions, maybe a version of `ccsRemoteReduce` to combine painless requests on remote clusters. All these will also need to be used by a cross-cluster painless execute action. So we'll need to pull these out into a base class, suitably refactored, to then use it in a new painless execute action.

**Comment by javanna** [comment]
If we do want to make painless execute cross-cluster compatible, I would expect the implementation to leverage remote cluster service which handles the cross-cluster communication. The API currently goes to a single shard to validate the script, hence there should be no reason to handle remote shards interactions and reductions like search does. I would think that painless execute for a remote index would simply forward the request to the remote cluster, but I may be missing something.
