### ISSUE TITLE
Unassigned replica shards turning cluster yellow when shard per node property set to 1 for primary shards

### ISSUE THREAD

**Issue by DivyeMahajan** [elastic/elasticsearch#92121]
### Elasticsearch Version

8.4.1

### Java Version

_bundled_

### OS Version

20.04.1-Ubuntu

### Problem Description

On creating a cluster with 3 master and 5 data nodes. An index was created with replication factor as 1. Once the setup was completed, whenever a new index is formed, 1 replica shard is always left unassigned and only available node is where the primary shard for the same index is allocated.
Observed the same trend for multiple days and seems like a bug. Ideally elasticsearch should pick up the data node where the primary shard for the same index is not present.

### Steps to Reproduce

`{
  "index": {
    "routing": {
      "allocation": {
        "total_shards_per_node": "2"
      }
    },
    "analysis": {
      "filter": {
        "truncate_256": {
          "length": "256",
          "type": "truncate"
        }
      },
      "analyzer": {
        "keyword_truncated": {
          "filter": [
            "truncate_256"
          ],
          "char_filter": [],
          "type": "custom",
          "tokenizer": "keyword"
        }
      }
    },
    "number_of_shards": "5",
    "number_of_replicas": "1"
  }
}`

Above index setting was used for one of the index on a cluster with 3 master and 5 data nodes.

Replica shard 4 remains unassigned for multiple new indices with error:
**the shard cannot be allocated to the same node on which a copy of the shard already exists**

**Comment by idegtiarenko** [comment]
Thanks, for reporting this issue. It looks similar to the one reported before: https://github.com/elastic/elasticsearch/issues/12273 so I am closing this one as duplicate.
