### ISSUE TITLE
[Ingest Pipeline] Rename Processor support Override

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#92125]
### Description

I would like to have the ability to make the [Rename Processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/rename-processor.html) be able to `override` an existing field, similar to how the [Set Processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-processor.html) can override a field.

## Use Case

If I have a sub-pipeline (pipeline called via the Pipeline Processor), if I'm not in control of the parent pipeline (example: Fleet Integration pipelines), Fleet might set a field to a value that I might want to override from a temp field (if I'm doing some calculation or other advanced work)

Today if I want to do this, I must first use a Set processor to override the desired field with my temp field value, then have a remove processor remove the temp field I no longer need/want. This adds extra code/logic, that could possibly be rolled up into just a setting of allowing the Rename processor, override the targeted field.

**Comment by joegallo** [comment]
This ended up being implemented as https://github.com/elastic/elasticsearch/pull/103565
