### ISSUE TITLE
docker build 6.8.22 version images run faild

### ISSUE THREAD

**Issue by liyin37** [elastic/elasticsearch#92132]
### Elasticsearch Version

6.8.22

### Installed Plugins

no

### Java Version

openjdk15

### OS Version

aarch64

### Problem Description

docker run 6.8.22 faild

### Steps to Reproduce

when I  use https://github.com/elastic/dockerfiles/tree/6.8/elasticsearch to build the 6.8.22 version images
![image](https://user-images.githubusercontent.com/42507175/205857495-dde266af-0fec-4516-85ef-519537986772.png)
then I docker run -it --rm elasticsearch:6.8.22 
[0.018s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
[0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 4096 actual: 65536
Error: Could not find or load main class [0.003s][error][cds]
Caused by: java.lang.ClassNotFoundException: [0/003s][error][cds]

**Comment by stu-elastic** [comment]
This appears to be related to running a 6.8 image in aarch64 which is unsupported.  https://github.com/elastic/elasticsearch/issues/75201#issuecomment-878910498
