### ISSUE TITLE
phrase search not working for wildcard search

### ISSUE THREAD

**Issue by orhan-erday** [elastic/elasticsearch#92131]
### Elasticsearch Version

Version: 7.9.3, Build: default/docker/c4138e51121ef06a6404866cddc601906fe5c868/2020-10-16T10:36:16.141335Z, JVM: 15

### Java Version

_bundled_

### OS Version

Linux 6200f3117fb3 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I have a word index and I can't search phrases on elasticsearch. there is no result. I check tons of solutions but I can't implement them to my query.

My mapping looks like this;

```
PUT /words/_mapping
{
  "properties": {
    "text": {
      "type": "keyword"
    }
  }
}
```
(if the type is `text` everything worked as expected)

My elastic query looks like this;

```
GET /words/_search
{
  "from": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "should": [
              {
                "query_string": {
                  "default_field": "text",
                  "default_operator": "AND",
                  "query": "*foo bar baz*"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 100,
  "track_total_hits": true
}
```

But there is no data

| \_id | \_index | \_score | \_type | text |
| --- | --- | --- | --- | --- |
|  |  |  |  |  |

I expect the record that has \`foo bar baz\` value,

| \_id | \_index | \_score | \_type | text |
| --- | --- | --- | --- | --- |
| drDzzYQBu3ncIuw4vn10 | words | 0.0 | \_doc | ***foo bar baz*** |

What is the problem? Could someone help?

### Steps to Reproduce

- set the mapping

```
PUT /words/_mapping
{
  "properties": {
    "text": {
      "type": "keyword"
    }
  }
}
```
- add value to the `text` field as `foo bar baz`
- Run the query
```
GET /words/_search
{
  "from": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "should": [
              {
                "query_string": {
                  "default_field": "text",
                  "default_operator": "AND",
                  "query": "*foo bar baz*"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "size": 100,
  "track_total_hits": true
}
```
- Expected results: 

| \_id | \_index | \_score | \_type | text |
| --- | --- | --- | --- | --- |
| drDzzYQBu3ncIuw4vn10 | words | 0.0 | \_doc | ***foo bar baz*** |

- Actual results:

| \_id | \_index | \_score | \_type | text |
| --- | --- | --- | --- | --- |
|  |  |  |  |  |

`(no data)`

**Comment by stu-elastic** [comment]
Hi @orhan-erday the `text` field should be used for phrase search, as noted in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#wildcard-field-type).

We'd like to direct user questions of this kind to the [forums](https://discuss.elastic.co/).
If you can stop there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
