### ISSUE TITLE
cat api for /allocation lists non-data nodes

### ISSUE THREAD

**Issue by nirmalc** [elastic/elasticsearch#9214]
cat api for allocation currently lists non data nodes as well ,with 0/blank  under hards disk.used disk.avail disk.total disk.percent. May be we can filter them out ..

**Comment by markwalkom** [comment]
It's better to be explicit, ie make note of these nodes and that they have no allocation, than not display them and potentially have discrepancies between nodes showing in some _cat API calls and not in others.

Just my opinion though.

**Comment by clintongormley** [comment]
Hmm, given that the `cat` API is supposed to show you the relevant info, I think it makes sense to filter out non-data nodes here.

**Comment by bleskes** [comment]
Thx @nirmalc I had to rebase and juggle a bit due to the restructuring on master, but it's in now. Thx!
