### ISSUE TITLE
ThreadPool.java looks for a config setting it itself prohibits

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#9216]
ThreadPool.java creates a background thread to updated an estimated clock time at an interval that is controlled by a configuration setting called `estimated_time_interval`.
Due to the way the component's settings are parsed this must be declared in configuration with the name `threadpool.estimated_time_interval` - BUT, earlier in the constructor of this class the call here throws an error if this name is defined in the configuration:

    Map<String, Settings> groupSettings = settings.getGroups(THREADPOOL_GROUP);

The reason is that the getGroups call checks that all settings prefixed with `threadpool.` must be "grouped" i.e. qualified with the name of a threadpool e.g. `threadpool.search.size`. 
Consequently we cannot possibly change the default setting of this interval and the need to do so has emerged as part of controlling search timeouts (see "Setting timer accuracy" section of https://github.com/elasticsearch/elasticsearch/issues/9156). A [PR](https://github.com/elasticsearch/elasticsearch/pull/9168) for this timeout issue includes a fix that changes the setting name to `threadpool.search.estimated_time_interval`.

**Comment by clintongormley** [comment]
@markharwood is this issue still relevant?

**Comment by jasontedor** [comment]
This will be addressed by #18674.
