### ISSUE TITLE
Add support for geo pluscodes

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#92182]
### Description

It would be great to add support for [Plus Codes](https://maps.google.com/pluscodes/technology/).

That'd would help to support geo points with the following definition: `9C5M8QQ7+V8R`

There's a [Java lib](https://github.com/google/open-location-code/tree/main/java) which allows conversion:

```
com.google.openlocationcode:openlocationcode:1.0.4
```

Sounds "easy" to encode from lat, lon (precision is optional - 10 is the default value):

```java
String encoded = OpenLocationCode.encode(latitude, longitude);
String encoded = OpenLocationCode.encode(latitude, longitude, precision);
```

The decode part looks like this:

```java
OpenLocationCode.CodeArea decoded = new OpenLocationCode(testData.code).decode();
decoded.getSouthLatitude();
decoded.getNorthLatitude();
decoded.getWestLongitude();
decoded.getEastLongitude();
```

This [CSV file](https://github.com/google/open-location-code/blob/main/test_data/encoding.csv) and [this one](https://github.com/google/open-location-code/blob/main/test_data/decoding.csv) contain lot of example we could use for testing.

**Comment by wchaparro** [comment]
Hello @dadoonet can you provide a use case / use cases that can help us understand the problem space / needs a bit better? Thanks!

**Comment by dadoonet** [comment]
I don't have any use case for it. Just a nice thing to have.

Feel free to close it. I might come with something else like a generic coordinate translator as an ingest processor plugin... Either published on my personal repo or as an official plugin for Elasticsearch depending on what the team would like. :)

**Comment by wchaparro** [comment]
Closing (please reopen if something new pops up as a use case), no plans
