### ISSUE TITLE
`new CountDown(0)` is trappy and should be forbidden

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#92196]
Today in a few places we create a `new CountDown(0)`. This is kind of trappy because it will never return `true` from `#countDown()` or `#fastForward()` which risks never completing whatever action needs completing unless the caller handles the empty case specially.

We should refactor the places that do this so that they all avoid creating an empty `CountDown`, instead just handling the fact that the action is already complete:

- [ ] `TransportIndicesShardStoresAction$AsyncShardStoresInfoFetches`
- [ ] `ClearScrollController`
- [ ] `TransportBroadcastReplicationAction#doExecute`
- [ ] `Realms#usageStats`

Once we've done that, we can forbid the creation of an empty `CountDown`.

**Comment by thecoop** [comment]
Would a better solution be to make a factory method that returns an already-completed `CountDown` when init'd with `0`? It might be valid to wait for 0 tasks in certain situations, and rather than special-casing that, just let `CountDown` handle it (but properly)?

**Comment by thecoop** [comment]
Hmm, looking closer, it is tricky, as `CountDown` is currently edge-triggered...

**Comment by thecoop** [comment]
So, I've considered this a bit more.

There are some situations where it is ok to initialise `CountDown` with 0 - this indicates you are not expecting any count down or fallback - no operations are going on. You might still want to access `isCountedDown`, or it's just easier to create `CountDown` and not special-case it.

In this situation, it is then a proper programming error to call `countDown` or `fastForward` - you told countdown there were no operations happening, but then an operation happened. So you've screwed up somewhere, and you need to fix the bug.

I note that both `TransportIndicesShardStoresAction$AsyncShardStoresInfoFetches` and `ClearScrollController` correctly ensure `countDown` is not called when it is zero - so those uses are ok.

To this end, #92388 deliberately makes this bug in your code visible, so you know about it and fix it (it passes all tests).

What do you think?

**Comment by DaveCTurner** [comment]
I'd rather keep these as assertion errors to make it clearer that it really is an error to do this, rather than something that makes sense to catch and handle. I'm ok with also throwing something if assertions are disabled, but I don't think this helps much.

You're right that many callers in `main` today construct the potentially-bad `CountDown` object and then work around the special case. I think this is trappy. It caught me out in a PR on which I was working: I forgot the special case, and that caused a leak. Fortunately a test showed me my mistake before anything bad happened, but that won't be true in all cases.

You always have to have special handling for the empty case because of the edge-triggering, and the point here is that I think we should handle the special case _before_ even constructing the trappy object. Compare, for instance, `GroupedActionListener` which does prevent this kind of misuse.

**Comment by thecoop** [comment]
So I looked at all the places that an empty countdown could be created in server, and added extra checks - https://github.com/elastic/elasticsearch/commit/7bcb6c033e14276fee847cf6af266416a0b94152

I'm really not sure this change is worth it, a lot of the uses are of the pattern

    CountDown remaining = new CountDown(elements.size());
    for (var e : elements) {
        ...
    }

in which case it's harmless that the empty countdown is created, as nothing uses it - and adding an extra check beforehand is a bit superfluous. Or it's just not assigning a CountDown variable, and leaving it as `null` - which then is a NPE waiting to happen if you do try to access it erroneously, no different to `IllegalStateException` thrown from the class itself. 

Is there a specific class you had in mind that this change would work well with?

**Comment by DaveCTurner** [comment]
Yes replacing them with `null` is not helping, in fact it's a bit worse because a NPE is not as strong as the `AssertionError` you get today.

Expanding the pattern you mention a bit, I see a lot of this:

```
CountDown remaining = new CountDown(elements.size());
for (var e : elements) {
    ...
    if (remaining.countDown()) {
        listener.onResponse(...);
    }
}
```

That's dangerous, it means if `elements` is empty then that listener leaks. See for instance `org.elasticsearch.transport.RemoteClusterService#collectNodes` - it's very much non-obvious that this method just silently doesn't work if you give it an empty set of `clusters`. Fortunately all its callers today get it right, but I feel we should much more visibly explode in these situations instead.

**Comment by thecoop** [comment]
In that specific class, the checks are in the _callers_ of `collectNodes` that does not call that method if `clusters` is empty - and I saw that a lot, which is why there are so few changes in that example commit. So `collectNodes` should really have an assert at the top that `clusters` is not empty.

I agree this problem should be made clearer, but the majority of the existing uses already handle this properly, meaning there's not actually much to change in the uses here. So then we need to make sure that any modifications that use `CountDown` incorrectly fail as loudly as possible. How about this:
1. Scan existing uses, fix any egregious errors, and add some asserts where it's not entirely clear it's safe.
2. Add `IllegalStateException` alongside the assertion in `CountDown` to fail more obviously if incorrectly used in the future.

**Comment by DaveCTurner** [comment]
The unsafe thing I would like to prevent is effectively the snippet in my previous message, and the only way I can see to do that would be to forbid `new CountDown(0)`. It's not a huge change, there's a few spots where we need to move the special-case handling before the line which makes the now-forbidden object.

I know we do this right in all the places today, my concern is about as-yet-unwritten code.

**Comment by ChrisHegarty** [comment]
I agree that `new CountDown(0)` is trappy, and given the sample usages it's not immediately obvious that the _count_ is actually _0_ or not.  But there is some limited usage of a _0_ count, e.g. for `isCountedDown`. And there is a desire to avoid the proliferation of _null_ by sidestepping the assignment of a CountDown instance.

Maybe there is a sweetspot here, where we ban the anonymous creation of instances with a zero count, but allow a singleton. The singleton still asserts when `countDown` or `fastForward` is called. If desired, code can use `EMPTY` rather than leaving the field unassigned.

```
diff --git a/server/src/main/java/org/elasticsearch/common/util/concurrent/CountDown.java b/server/src/main/java/org/elasticsearch/common/util/concurrent/CountDown.java
index 17611f4372b..3df68c13d62 100644
--- a/server/src/main/java/org/elasticsearch/common/util/concurrent/CountDown.java
+++ b/server/src/main/java/org/elasticsearch/common/util/concurrent/CountDown.java
@@ -25,13 +25,24 @@ public final class CountDown {
     private final int originalCount;
 
     public CountDown(int count) {
-        if (count < 0) {
-            throw new IllegalArgumentException("count must be greater or equal to 0 but was: " + count);
+        if (count <= 0) {
+            throw new IllegalArgumentException("count must be greater than 0 but was: " + count);
         }
         this.originalCount = count;
         this.countDown = new AtomicInteger(count);
     }
 
+    private CountDown() {
+        this.originalCount = -1;
+        this.countDown = new AtomicInteger(0);
+    }
+
+    private static final CountDown EMPTY = new CountDown();
+
+    public static CountDown empty() {
+        return EMPTY;
+    }
+
     /**
      * Decrements the count-down and returns <code>true</code> iff this call
      * reached zero otherwise <code>false</code>
```

**Comment by thecoop** [comment]
So that would result in code lines like

    this.expectedOps = shards.isEmpty() ? CountDown.empty() : new CountDown(shards.size());

    CountDown countDown = totalClusters.isEmpty() ? CountDown.empty() : new CountDown(totalClusters);

Why not just have a method:

    public static CountDown of(int count) {
        return count == 0 ? CountDown.empty() : new CountDown(count);
    }

**Comment by ChrisHegarty** [comment]
>I think everywhere we can move the special-case handling up and just get rid of the whole concept of an empty countdown.

Seems ok, to me.
