### ISSUE TITLE
Unable to restore the fleet feature state

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#92272]
### Elasticsearch Version

8.6, 8.7

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

In 8.x we made using the feature states mandatory when restoring a snapshot.
When you restore a feature state, Elasticsearch closes and overwrites the feature's 
existing indices however attempting to restore the `fleet` feature state yields:
```
[found-snapshots:cloud-snapshot-2022.12.08-jfwylsm3sqylehlntm2ciw/EEIRWboOR3euBjnR1D5-Dw] cannot restore index [.ds-.fleet-actions-results-2022.12.08-000001] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name
```

Potentially related or caused by https://github.com/elastic/elasticsearch/issues/92271

### Steps to Reproduce

We only have one feature state that has a system data stream - the `fleet` 
feature state - the `.fleet-actions-results` one.

To reproduce, enroll a fleet agent and have it send some data to fleet (maybe
using the `system` integration).
We'll need to perform an action for the `.fleet-actions-results` system data stream
to be created - I navigated to Agents under Management > Fleet  and added 
some tags to the agent (click on the `...` on the right hand side for the agent you 
enrolled).

Take a snapshot after the `.fleet-actions-results` system data stream is created
using
```
POST _slm/policy/cloud-snapshot-policy/_execute
```

Attempt to restore the `fleet` feature state from the newly created snapshot:
```
POST _snapshot/my_repository/snapshot_name/_restore
{
  "feature_states": [ "fleet" ],
  "include_global_state": false,    
  "indices": "-*"                   
}
```

**Comment by romain-chanu** [comment]
@andreidan - this looks like a duplicate of https://github.com/elastic/elasticsearch/issues/89261?

**Comment by andreidan** [comment]
@romain-chanu good shout ! Closing this as duplicate of #89261
