### ISSUE TITLE
Add a rules-based query

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#92273]
### Description

A rules-based query takes a metadata map and a query template and builds a new DSL query by applying rules to the metadata and then parsing the template.
```
GET /my_index/_search
{
  "query" : { 
    "apply-rules" : {
      "rule-set" : "my-rules",
      "metadata" : { "user" : "kimchy", "sign-up-date" : "2022-12-12", "platinum" : true, "query_text" : "televisions" },
      "template" : { ... }
    }
  }
}
```

Rule sets (referred to in the above query by the `rule-set` parameter) are collections of rules and metadata mappings managed by a new `_rule_set` API

```
PUT /my_index/_rule_set/rule_set_1
{
  "mappings" : {
    "user" : "keyword",
    "query_text" : "text",
    "sign_up_date" : "date",
    "platinum" : "boolean"
  },
  "rules" : [
    { 
      "condition" : { ... },      // a DSL query to be applied to the rules-query metadata
      "rule" : { "edit-metadata" : { "script" : { ... } } }   // various rule types are available
    },
   ....
  ]
}
```

We will implement rules to do the following:
* mutate the metadata object to be passed to the final template
* pin documents by id to the top of the query by wrapping the parsed template
* exclude documents by id from the query results by wrapping the parsed template
* add filters, exclusions or boosts as DSL queries which wrap the parsed template

Rulesets will be stored in a system index, and maintained using a basic CRUD api.

We may also add the ability to pass in an organic query rather than a query template to the top-level query.

**Comment by javanna** [comment]
@romseygeek can this be closed?

**Comment by romseygeek** [comment]
I think enterprise search has moved in a different direction now, right @jimczi ?  If so we can close this.
