### ISSUE TITLE
Could DataStreamTimestampFieldMapperTest not iterate over all fields?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#92297]
### Description

`DataStreamTimestampFieldMapperTest#postParse` scans over all fields that have been created during the parsing process to verify that there is exactly one `@timestamp` field. This even happens twice with the TSDB mode because `TsidExtractingFieldMapper#createField` does another pass to extract the timestamp that it needs to generate the ID.

Could we instead hook into the parsing logic of `DateFieldMapper#parse` to record the timestamp value of the document somewhere on the `LuceneDocument` so that it's ready to use for `DataStreamTimestampFieldMapperTest#postParse` and `TsidExtractingFieldMapper#createField` and we don't have to scan over fields again?

**Comment by romseygeek** [comment]
+1.  I tried a while ago to make `@timestamp` a metadata field in #84294 but ended up getting bogged down in trying to make it magically re-write mappings.  But it could probably be revived without the magic bits.

**Comment by OlivierCavadenti** [comment]
If it's ok, I can investigate and take this one.
