### ISSUE TITLE
Docs missing for delayed allocation diagnosis case in shards availability health indicator

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#92313]
### Elasticsearch Version

8.5.0, 8.6.0

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

The delayed allocation diagnosis case (#89056) gives https://ela.st/fix-delayed-shard-allocation as the URL for more information. However that URL returns a 404. As far as I can tell the user documentation does not exist for this case.

### Steps to Reproduce

n/a

**Comment by andreidan** [comment]
This diagnosis doesn't require any user action. I believe it's ok for now to point `/fix-delayed-shard-allocation` to https://www.elastic.co/guide/en/elasticsearch/reference/current/delayed-allocation.html

I've fixed the alias to do so
