### ISSUE TITLE
Add support for Brotli Compression

### ISSUE THREAD

**Issue by lawrencek76** [elastic/elasticsearch#92376]
### Description

Brotli is widely supported and can offer better compression ratios and performance.  In some situations, reducing the bytes sent / received saves money for data transfer on cloud platforms.

[Dependent Request](https://github.com/elastic/elasticsearch-net/issues/4199)

**Comment by thefreakingmind** [comment]
Hey I am kind of new to this. Can I pick this up?

**Comment by DaveCTurner** [comment]
As far as I can tell there's no pure-Java implementation of Brotli so we'd need to bind to a native C++ library to achieve this, and that's something we would rather avoid if at all possible. It introduces a lot more risk which means we have to do more careful due diligence, and the fact that recent-ish versions have had [security bugs](https://github.com/advisories/GHSA-5v8v-66v8-mwm7) is a little concerning.

If you want to use Brotli compression for HTTP traffic then your best bet at the moment is to add the compression outside ES. There's an [Nginx module](https://docs.nginx.com/nginx/admin-guide/dynamic-modules/brotli/) that would work here, but I note that [HAProxy has also avoided adding Brotli support](https://github.com/haproxy/haproxy/issues/21) so far. IMO that's also a worrying sign and another good reason to be cautious here.

I'm closing this to indicate that we're not going to do this work in the foreseeable future. If the situation changes (e.g. a well-supported, stable  and performant pure Java port appears) then we can reopen this.
