### ISSUE TITLE
Repository verification failed

### ISSUE THREAD

**Issue by robjamsinterit** [elastic/elasticsearch#92371]
### Elasticsearch Version

8.4

### Java Version

_bundled_

### OS Version

Linux 6aa5a567b9f1 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I added bucket json file generated on GCS to keystore on all 4 elsasticsearch nodes and always verification failed

### Steps to Reproduce

generate bucket json 
add to key store
create repository for GCS
click Verification

### Logs (if relevant)

Verification status log: 

`{
  "name": "ResponseError",
  "meta": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "repository_verification_exception",
            "reason": "[gcs_sinterit] path  is not accessible on master node"
          }
        ],
        "type": "repository_verification_exception",
        "reason": "[gcs_sinterit] path  is not accessible on master node",
        "caused_by": {
          "type": "security_exception",
          "reason": "access denied (\"java.io.FilePermission\" \"/usr/share/elasticsearch/.config/gcloud/active_config\" \"read\")"
        }
      },
      "status": 500
    },
    "statusCode": 500,
    "headers": {
      "x-opaque-id": "ec07c253-8a49-4604-9262-2a31040558ab;kibana:application:management:",
      "x-elastic-product": "Elasticsearch",
      "content-type": "application/json;charset=utf-8",
      "content-length": "420"
    },
    "meta": {
      "context": null,
      "request": {
        "params": {
          "method": "POST",
          "path": "/_snapshot/gcs_sinterit/_verify",
          "querystring": "",
          "headers": {
            "user-agent": "elastic-transport-js/8.2.0 (linux 5.15.0-53-generic-x64; Node.js v16.16.0)",
            "x-elastic-product-origin": "kibana",
            "authorization": "Basic ZWxhc3RpYzplbGFzdGlj",
            "x-opaque-id": "ec07c253-8a49-4604-9262-2a31040558ab;kibana:application:management:",
            "x-elastic-client-meta": "es=8.3.0p,js=16.16.0,t=8.2.0,hc=16.16.0",
            "accept": "application/vnd.elasticsearch+json; compatible-with=8,text/plain"
          }
        },
        "options": {
          "opaqueId": "ec07c253-8a49-4604-9262-2a31040558ab;kibana:application:management:",
          "headers": {
            "x-elastic-product-origin": "kibana",
            "authorization": "Basic ZWxhc3RpYzplbGFzdGlj",
            "x-opaque-id": "ec07c253-8a49-4604-9262-2a31040558ab",
            "x-elastic-client-meta": "es=8.3.0p,js=16.16.0,t=8.2.0,hc=16.16.0"
          }
        },
        "id": 1
      },
      "name": "elasticsearch-js",
      "connection": {
        "url": "https://elasticsearch:9200/",
        "id": "https://elasticsearch:9200/",
        "headers": {},
        "status": "alive"
      },
      "attempts": 0,
      "aborted": false
    },
    "warnings": null
  }
}`

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
