### ISSUE TITLE
Invalid Maven descriptor for 7.17.8 release

### ISSUE THREAD

**Issue by PerfectSlayer** [elastic/elasticsearch#92383]
### Elasticsearch Version

7.17.8

### Java Version

_bundled_

### OS Version

All

### Problem Description

Hello,

I think there is an issue the latest `org.elasticsearch:elasticsearch:7.17.8` release.
When checking its Maven metadata, it does like an integration artifact:
```xml
  <groupId>org.elasticsearch.distribution.integ-test-zip</groupId>
  <artifactId>elasticsearch</artifactId>
  <version>7.17.8</version>
  <packaging>zip</packaging>
  <name>integ-test-zip</name>
  <description>Elasticsearch subproject :distribution:archives:integ-test-zip</description>
```

Where the `7.17.7` contains expected values:
```xml
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch</artifactId>
  <version>7.17.7</version>
```

Please check https://search.maven.org/artifact/org.elasticsearch/elasticsearch/7.17.8/jar and https://search.maven.org/artifact/org.elasticsearch/elasticsearch/7.17.7/jar for all details.

Best,
Bruce

### Steps to Reproduce

Download the artifact on Maven Central using Maven

**Comment by mark-vieira** [comment]
The maven POM in maven central has been updated to fix this issue.
