### ISSUE TITLE
EQL Samples feature documentation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#92384]
### Add documentation for new EQL Samples feature

- [x] Reword the [Required fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/eql.html#eql-required-fields) section as Samples don't require a timestamp
- [x] Add a section similar to [Search for a sequence of events](https://github.com/elastic/elasticsearch/edit/8.5/docs/reference/eql/eql.asciidoc) for Samples to the EQL main page
- [x] Add a section similar to [Sequences](https://github.com/elastic/elasticsearch/edit/8.5/docs/reference/eql/syntax.asciidoc) for Samples to the Syntax page
  - Refer to Sequences syntax, but mention that there's no support for `with maxspan`, `until`, and `with runs`
 
For the 8.7.0 release:

-  [x] Add documentation for [`max_samples_per_key`](https://github.com/elastic/elasticsearch/pull/91783) to the Syntax page.

**Comment by abdonpijpelink** [comment]
Addressed in #92504 and #92634
