### ISSUE TITLE
Expose the invalidation_time field in Get/Query ApiKey APIs

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#92404]
Since #91873, a timestamp is recorded when an API key is invalidated. It will be useful if this new field is exposed in:
* Responses from [GetApiKey](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-api-key.html) and [QueryApiKey](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-query-api-key.html) API
* As a valid [query value](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-query-api-key.html#security-api-query-api-key-request-body) for QueryApiKey API

**Comment by jfreden** [comment]
This has been completed in https://github.com/elastic/elasticsearch/pull/102472 and https://github.com/elastic/elasticsearch/pull/102590.
