### ISSUE TITLE
ByteSizeCachingDirectory can't use cached size because numOpenOutputs is a negative value when close method was invoked more than once

### ISSUE THREAD

**Issue by loupipalien** [elastic/elasticsearch#92434]
### Elasticsearch Version

7.10.2

### Installed Plugins

repository-hdfs

### Java Version

_bundled_

### OS Version

Linux 4.14.81.bm.26-amd64 #1 SMP Debian 4.14.81.bm.26 Mon Sep 14 09:46:45 UTC 2020

### Problem Description

The size of shard should't  be computed again instead of using cached when no pending write。we migrated a lot of indicess to a new cluster by snapshot, nodes and indices stats api become very slow because some shards that were restored from snapshots always computed shard directory size even no write，not use cached because the numOpenOutputs was decreased to a negative number

### Steps to Reproduce

snapshot a index then restore, the shard that recovery from snapshot will always compute directory size instead of using cached

### Logs (if relevant)

![image](https://user-images.githubusercontent.com/17610965/208378334-c814a7ab-c78e-439d-8444-99a511868604.png)

**Comment by pxsalehi** [comment]
@loupipalien thank you for reporting the issue. I do not think 7.10.2 is supported anymore and actively being maintained. Do you encounter the same issue on the latest 7.17 or 8.x Elasticsearch?

**Comment by loupipalien** [comment]
@pxsalehi yes, 7.17.8 and 8.5.3 Elasticsearch also have this issue
