### ISSUE TITLE
[Self-managed]: 'Password' and 'Enrollment token' are not auto-generated on running elasticsearch command on Ubuntu Linux

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elasticsearch#92485]
**Kibana version:** 8.6 Kibana Self-Managed environment

**Host OS and Browser version:** Ubuntu Linux

**Build Details:**

```
Version: 8.6.0 BC8
Build: 58807	
Commit: 335b86a633af9ce1d9c8a92187ed1c8697ab139f

```
**Preconditions:**

- 8.6 BC8 Elasticsearch Linux tar artifacts should be available.

**Steps to reproduce:**

1. Open the terminal.
2. Navigate to the folder 
   `elk\elastcisearch\bin`
3. Run the command
    ` ./elasticsearch`
4. Observe that the `'Password'` and `'Enrollment token'` are not auto-generated on running `./elasticsearch` command on Ubuntu Linux.

**Expected Result:**

- `'Password'` and `'Enrollment token'` should be auto-generated on running `./elasticsearch` command on Ubuntu Linux.

**What's not working**: 

- `Fleet Server` is not getting installed on the `Ubuntu Linux`  `Self-managed environment` on `8.6.0 BC7` and below error is shown:

   `Error: fleet-server failed: context canceled`
   `Error: enroll command failed with exit code: 1`

**Screenshots:**

- **Elasticsearch (8.6.0 BC8)**

![image](https://user-images.githubusercontent.com/97870262/208865499-efb170b8-5cbc-4688-9ec4-802dcb029833.png)

- **Fleet Server (8.6.0 BC7)**

![image](https://user-images.githubusercontent.com/97870262/208856099-b9f09a9b-e242-4333-b540-62313faa4466.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done.

**Comment by dikshachauhan-qasource** [comment]
cc @kpollich @cmacknz

**Comment by prachigupta-qasource** [comment]
cc @joshdover 

We have re-attempted to execute the `enrollment` and `reset password` commands individually. However, `Command not found` response is displayed. 

![image](https://user-images.githubusercontent.com/97870262/208917571-b4816543-41ec-46b6-b85e-aed558c979c1.png)

Further, we have attached `elasticsearch logs` for your reference.

- [logs.zip](https://github.com/elastic/elasticsearch/files/10278089/logs.zip)

Thanks!

**Comment by joshdover** [comment]
@prachigupta-qasource I think you need to add the `./` to the beginning of the commands: `./elasticsearch-reset-password`

**Comment by prachigupta-qasource** [comment]
Hi @joshdover,

We have re-attempted the `./elasticsearch` command on `Ubuntu Linux Desktop 22.04` environment and found that the issue is **fixed now**.

**Build details:**

```
Version: 8.6.0 BC8
Build: 58807	
Commit: 335b86a633af9ce1d9c8a92187ed1c8697ab139f
```
**Below are the observations:**

- `'Password'` and `'Enrollment token'` is auto-generated on running `./elasticsearch` command on `Ubuntu Linux`.

**Screenshot:**

- **Elasticsearch (8.6.0 BC8)**

![image](https://user-images.githubusercontent.com/97870262/209285331-b32fe0e5-c145-472f-b0d3-a70326850e6f.png)

Hence, marking this as QA: Validated and `closing` this ticket..

Thanks!
