### ISSUE TITLE
ES Field Capabilities API does not return fields inside disabled objects when include_unmapped=true 

### ISSUE THREAD

**Issue by Alsheh** [elastic/elasticsearch#92506]
### Elasticsearch Version

7.16.2

### Java Version

_bundled_

### OS Version

Linux be4fea268934 4.4.0-1020-aws #29-Ubuntu SMP Wed Jun 14 15:54:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Hi

I'm trying to list all fields in a certain index, indexed and non-indexed fields. I'm using the ES Field capabilities API: `GET <index-name>/_field_caps?fields=*&include_unmapped=true`. However, the API is not returning non-indexed fields. Is there a way to make the API return both indexed and non-indexed fields?

Elasticsearch version: 7.16.2

### Steps to Reproduce

Fields inside disabled objects don't show up:

```
PUT idx_fields
{
  "mappings": {
    "properties": {
      "name": {
        "type": "text"
      },
      "object_not_index":{
        "type": "object", 
        "enabled": false
      }
    }
  }
}
POST idx_fields/_doc
{
  "unmapped_name": "any",
  "object_not_index": {
    "a": 1
  }
}
GET idx_fields/_field_caps?include_unmapped=true&fields=*
```
`object_not_index.a` is missing from the response:
```
{
  "indices" : [
    "idx_fields"
  ],
  "fields" : {
   ...
   "name" : {
      "text" : {
        "type" : "text",
        "metadata_field" : false,
        "searchable" : true,
        "aggregatable" : false
      }
    },
    "unmapped_name" : {
      "text" : {
        "type" : "text",
        "metadata_field" : false,
        "searchable" : true,
        "aggregatable" : false
      }
    },
    "unmapped_name.keyword" : {
      "keyword" : {
        "type" : "keyword",
        "metadata_field" : false,
        "searchable" : true,
        "aggregatable" : true
      }
    }
  }
}
```

**Comment by romseygeek** [comment]
Fields inside disabled objects are ignored entirely at parsing time, so no new mappings will be added when one is encountered and field caps won't know anything about them. If you want them to appear in mappings but still not be indexed, then I'd suggest adding a dynamic mapping for fields that match `object_not_index.*` that creates a non-indexed text field.
