### ISSUE TITLE
Allow time series data streams to be migrated back to regular data streams

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#92544]
Currently it is possible to migrate an existing data stream to a time series data stream.
This is done by updating the index template that created the data stream. 
Then after a rollover the data stream is a time series data stream. 

Via a similar way it should be possible to change time series data stream back 
to a regular data stream. Currently when changing the `index.mode` setting
on an index template from `time_series` to `standard` (or removing the setting)
results in a validation error.

**Comment by ruflin** [comment]
This feature is important for Fleet. Today in Fleet there is an experimental feature to turn on TSDB on a data stream but no option to turn it off again. Would be great to have this to encourage more users to try it out but still have a path out.

![Screenshot 2022-12-23 at 11 19 57](https://user-images.githubusercontent.com/244900/209318554-f93a6b10-a9a0-43df-ba20-be4e73dc93bc.png)

@kpollich @joshdover

**Comment by martijnvg** [comment]
Implemented via #92644
