### ISSUE TITLE
Reinstate AbstractXContentFilteringTestCase#testDotsAndDoubleWildcardInExcludedFieldName

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#92559]
`AbstractXContentFilteringTestCase#testDotsAndDoubleWildcardInExcludedFieldName` is marked as `AwaitsFix`, linking #80160, but this issue is closed. We should either remove the AwaitsFix marker, open a new issue to track the bug, or remove the test if it is invalid.

**Comment by thecoop** [comment]
The test is still failing, but for a different reason. I'm opening a new ticket to cover it.

**Comment by thecoop** [comment]
#92632 opened for the new failure reason
