### ISSUE TITLE
Add nested path validation 

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#9255]
Follow up from #7805. The following features should have (better) nested validation:
- nested query and filter.
- nested aggregator.
- reverse_nested aggregator.
- nested inner hits.
- nested sorting.

Closes #11830

**Comment by rbnacharya** [comment]
+1 , Aggregations don't have validation (we get undesired result when error occur) ,  as facet does.

**Comment by clintongormley** [comment]
This is now in place
