### ISSUE TITLE
[CI] repository-gcs:thirdPartyAudit failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#92577]
### CI Link

https://gradle-enterprise.elastic.co/s/643p72k2g5sig/console-log?task=:modules:repository-gcs:thirdPartyAudit

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.6

### Failure excerpt

```
Unnecessary exclusions, following classes are not missing: |  
-- | --
  | * org.graalvm.nativeimage.hosted.Feature |  
  | * org.graalvm.nativeimage.hosted.Feature$BeforeAnalysisAccess |  
  | * org.graalvm.nativeimage.hosted.Feature$DuringAnalysisAccess |  
  | * org.graalvm.nativeimage.hosted.Feature$FeatureAccess |  
  | * org.graalvm.nativeimage.hosted.RuntimeReflection
```

**Comment by albertzaharovits** [comment]
There is a long list of daily failures for graalvm builds: https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Third%20party%20audit%20task%20is%20not%20configured%20correctly&search.startTimeMax=1672426869334&search.startTimeMin=1671746400000&search.timeZoneId=Europe/Bucharest

**Comment by iverase** [comment]
Failure in main: https://gradle-enterprise.elastic.co/s/w6fc2tfsafjdm

Failure in 8.6: https://gradle-enterprise.elastic.co/s/4obb2uqfezfxi
