### ISSUE TITLE
On demand - Elasticsearch Engineer training

### ISSUE THREAD

**Issue by amyjtechwriter** [elastic/elasticsearch#92598]
Enrolled via docebo on Okta.

**Comment by gmarouli** [comment]
Hi @amyjtechwriter , welcome to the team :) . If I understand correctly the issue description, this is an issue about you following the Elasticsearch engineer training. Am I correct? If that is the case, usually we do not open issues in this repo for this type of things. Do you mind closing it?

**Comment by amyjtechwriter** [comment]
...Ops sorry

**Comment by gmarouli** [comment]
No worries at all :)
