### ISSUE TITLE
elasticsearch快照恢复时无法发现快照文件

### ISSUE THREAD

**Issue by liyale123** [elastic/elasticsearch#92595]
elasticsearch做完快照后无法恢复，识别不到快照。看本地发现缺少快照文件，如index-2/3/4......和index.latest
![企业微信截图_1672300889147](https://user-images.githubusercontent.com/37055934/209921553-4c287a73-8af6-4b2a-9740-d7ab1c70b5a8.png)
正常的应该如下图：
![企业微信截图_16723009453826](https://user-images.githubusercontent.com/37055934/209921667-71a693f3-a269-46f0-97d0-2aa819b68797.png)

**Comment by original-brownbear** [comment]
This post does not include very much information that might be helpful to start to try and answer it. Questions like this often go unanswered. You can make it more likely to receive an answer by adding more information that you think would be helpful to readers, such as:
* details of the investigations that you have already performed
* things you have already tried when looking for a solution
* requests made to Elasticsearch and their responses (properly formatted using the </> button or pairs of triple backticks (```)
* log messages, including any stack traces (also properly formatted using </> or backticks)

It would be great if you could update your post to solve this.
