### ISSUE TITLE
Compose script execution error.

### ISSUE THREAD

**Issue by freemankevin** [elastic/elasticsearch#92605]
### Elasticsearch Version

latest

### Java Version

_bundled_

### OS Version

centos7.9

### Problem Description

The 'setup' part cannot be executed repeatedly, there is a problem with the shell script, can you update the description in the official document ([Install Elasticsearch with Docker | Elasticsearch Guide [8.5] | Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-file)) .

```shell
$ docker logs -f --tail 1000  efk-setup-1
Setting file permissions
Waiting for Elasticsearch availability
Setting kibana_system password
All done!
```

![image](https://user-images.githubusercontent.com/71524776/210041518-a5bd9173-0070-4dfb-82d5-96f559c65493.png)

### Steps to Reproduce

1

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/210041829-49931ed5-85b5-4cb0-ba57-020c3f2fcfed.png)

**Comment by freemankevin** [comment]
Not completely resolved, but resolved.
See link：
https://discuss.elastic.co/t/docker-compose-start-false/322189

**Comment by mark-vieira** [comment]
I don't believe there's anything else to do here. It seems your concerns were addressed in that forum thread.
