### ISSUE TITLE
Update default value for index.translog.flush_threshold_size

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#9265]
Per the recommendation here - http://www.elasticsearch.org/blog/performance-considerations-elasticsearch-indexing/ - can/should we set `index.translog.flush_threshold_size` to `1g` by default in latest releases?

**Comment by clintongormley** [comment]
@markwalkom not sure it is always appropriate.  It increases indexing throughput, but also increases recovery time in case of shard failure.

@mikemccand what do you think?

**Comment by mikemccand** [comment]
That's a good point (higher recovery time); the blog post should have mentioned that tradeoff.  It does also mean added disk usage.

But then, fsync is often quite costly on the IO system, and if you are indexing with enough client side concurrency, you can burn through 200 MB quickly enough (I've seen that equate to ~ 5 seconds wall clock time).  Maybe we should increase to 500 MB?

**Comment by clintongormley** [comment]
Seems reasonable to me

**Comment by kimchy** [comment]
@mikemccand I see you pushed it, should this also go to 1.5? I think it should, no?

**Comment by mikemccand** [comment]
@kimchy OK, I agree ... I'll push.

**Comment by mikemccand** [comment]
This was fixed in 1.5.0
