### ISSUE TITLE
RangeFilterBuilder gte,lte notation

### ISSUE THREAD

**Issue by nizsheanez** [elastic/elasticsearch#9266]
In ES documentation:
The from, to, include_lower and include_upper parameters have been deprecated in favour of gt,gte,lt,lte.
http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/query-dsl-numeric-range-filter.html

In current documentation it's already from, to, include_lower and include_upper already not exists:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-range-filter.html

But Java client still use old format:
https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/query/RangeFilterBuilder.java#L384

**Comment by clintongormley** [comment]
Yeah, I think the Java API should switch to gt/gte etc as well.

**Comment by javanna** [comment]
We do support `gt`/`gte` and `lt`/`lte` in `RangeQueryBuilder` (filters have been merged with queries to RangeFilterBuilder doesn't exist anymore), as well as `from` and `to`. Does this mean we should remove support for setting `from` and `to`?

**Comment by nizsheanez** [comment]
Then ok, probably i didn't find it. Let's close it then.
