### ISSUE TITLE
conflict checker decides (wrongly?) that deprecated aliases can't be fixed in place

### ISSUE THREAD

**Issue by JoranDox** [elastic/elasticsearch#92704]
### Elasticsearch Version

7.17

### Java Version

whatever is included on es cloud

### OS Version

whatever is included on es cloud

### Problem Description

When checking what we need to do to upgrade to elastic 8.x, the upgrade assistant tells me we've got some 50 indices with the following issue:
`Convert [dt] format [dateOptionalTime] which contains deprecated camel case to snake case. [dateOptionalTime] to [date_optional_time].`

Why can't this be automatically solved? Looks like they're literally aliases for the same internal thing, no?
https://github.com/elastic/elasticsearch/blob/be7c7415627377a1b795400fb8dfcc6cbdf0e322/server/src/main/java/org/elasticsearch/common/time/FormatNames.java#L32
https://github.com/elastic/elasticsearch/blob/5af8ec52fe8b7e6b2a9e644f7da8d21dc3e58351/server/src/main/java/org/elasticsearch/common/time/LegacyFormatNames.java#L36

What's more, why can't I just 
```
PUT my_index/_mapping
{
  **old_mapping, but replace dateOptionalTime with date_optional_time
}
```
? 
The result is 
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Mapper for [dt] conflicts with existing mapper:\n\tCannot update parameter [format] from [dateOptionalTime] to [date_optional_time]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Mapper for [dt] conflicts with existing mapper:\n\tCannot update parameter [format] from [dateOptionalTime] to [date_optional_time]"
  },
  "status" : 400
}
```

Which to me seems to make no sense. Is there a good reason this triggers the conflict error or is that an internal inconsistency that could just be skipped in the conflict checker?

### Steps to Reproduce

- have a cluster v7.17
- have an index with a date field mapping like `{          "type" : "date",          "format" : "dateOptionalTime"        }`
- want to upgrade to 8.x
- check upgrade assistant
- notice "Date fields use deprecated camel case formats"
- try to fix
- can't fix without downtime

**Comment by JoranDox** [comment]
So any movement on this? we're going to have downtime aren't we?

I don't get how this is a problem even, it really feels like the **name** of the same underlying format (dateOptionalTime vs date_optional_time) shouldn't make that much of a difference, no? Why wouldn't I be able to change that in place if the underlying implementation is literally an alias for the same thing?

**Comment by stu-elastic** [comment]
We should allow changing the format for date field mapper in this special case, that the camelCase format is equal to the snake case.  We will have to backport the change to 7.17 so an upgrade to the latest 7.17 will be required (as is always the case for major version upgrades).

**Comment by rjernst** [comment]
Closing this as I believe it was already addressed by the linked PR.
