### ISSUE TITLE
Some (not all) elasticsearch snapshot indices failing to write to azure blob with I/O error

### ISSUE THREAD

**Issue by danfinn** [elastic/elasticsearch#92731]
### Elasticsearch Version

7.17.8

### Installed Plugins

repository-azure

### Java Version

_bundled_

### OS Version

Linux elasticsearch-master-0 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Elasticsearch running on kubernetes, installed via helm.

Snapshot repo has been added and pointing to azure blob.  Around 1/3 of the indices are failing when running the snapshot with the following error:

```
INTERNAL_SERVER_ERROR: UncategorizedExecutionException[Failed execution]; nested: ExecutionException[java.io.IOException: Unable to write blob indices/8FpoPDnXTWi4UEwmpsTqPA/0/__uTMAzEiZQAGT5uSvunSJiw]; nested: IOException[Unable to write blob indices/8FpoPDnXTWi4UEwmpsTqPA/0/__uTMAzEiZQAGT5uSvunSJiw]; nested: ReactiveException[java.io.IOException: null: NIOFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/indices/a8W12fUDQPerYspC0uCgXA/0/index/_kup.fdt")]; nested: IOException[null: NIOFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/indices/a8W12fUDQPerYspC0uCgXA/0/index/_kup.fdt")]; nested: ClosedChannelException
```

This smells to me like an azure issue however posting here first to try and get some kind of confirmation or consensus before I reach out to them.

### Steps to Reproduce

add azure blob snapshot repo, create snapshot policy to capture everything, run policy

**Comment by kingherc** [comment]
Please note you can also attempt to run the [verification API and/or the repository analysis API](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/snapshots-register-repository.html#snapshots-repository-verification) to confirm whether the repository is working as expected.

The current ticket description details do not warrant an Elasticsearch bug for me yet. This appears to be a user question as Azure is a supported/tested snapshot repository, the ticket description mentions adding an Azure blob repo, and resulting in connectivity errors when taking snapshots. I believe you will gain more insight into any connectivity issues by running the verification/analysis APIs above. Please also read the guide pages around [configuring the Azure repository](https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/repository-azure.html) which may help better configuring the repository settings.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by 617m4rc** [comment]
@danfinn We see the same problem, but I am doubtful that it is purely an Azure problem. Have you found a solution?

**Comment by danfinn** [comment]
I don't think we've been seeing this error since upgrading to 8.x

**Comment by danfinn** [comment]
Actually, I take that back.  We very much are still seeing this issue on 8.7.0 and trying to figure out why.

**Comment by d-mankowski-synerise** [comment]
We have also encountered this issue - it turned out that we've reached Storage Account capacity limit (500TB) :)
