### ISSUE TITLE
Redundant Code at line 73 in the source file MembersInjectorStore.java

### ISSUE THREAD

**Issue by liweixiesysu** [elastic/elasticsearch#92732]
### Elasticsearch Version

master branch

### Java Version

_bundled_

### OS Version

no

### Problem Description

Redundant Code at line 73 in the source file MembersInjectorStore.java

### Steps to Reproduce

no

**Comment by thecoop** [comment]
@liweixiesysu You can easily open a PR for this change yourself if you would like to get involved directly in ES development.

**Comment by liweixiesysu** [comment]
@thecoop OK, thanks!

**Comment by ayushsinghal90** [comment]
can I pick this up, looking for an issue to contribute.

**Comment by thecoop** [comment]
Fixed by #93112
