### ISSUE TITLE
[Watcher docs] meetup example not working due to discontinued Meetup public API

### ISSUE THREAD

**Issue by vincetrumental** [elastic/elasticsearch#92764]
Hello, 
there is a very valuable Watcher example for alerting on streaming data, but the Meetup API on whitch it is based does not work anymore (http://stream.meetup.com/2/rsvps) .
I tried to search for a simple replacement (or another public, unauthentified json streaming API) but did not find anything so far. 
file: example-watch-meetupdata.asciidoc

**Comment by kingherc** [comment]
I believe the referenced page is [this one](https://www.elastic.co/guide/en/elasticsearch/reference/current/watching-meetup-data.html).

**Comment by vincetrumental** [comment]
it is ! 
Not an elastic-related issue but it would be nice to find a replacement for this external API endpoint. Or change the documentation in order to avoid frustration.
