### ISSUE TITLE
Default fuzzy transpositions to true

### ISSUE THREAD

**Issue by grmblfrz** [elastic/elasticsearch#9278]
The [documentation](https://github.com/elasticsearch/elasticsearch/blob/d9165d/docs/reference/api-conventions.asciidoc#string-fields) states:

`0..1`:: must match exactly
`1..4`:: one edit allowed
`>4`:: two edits allowed

whereas the [source](https://github.com/elasticsearch/elasticsearch/blob/d9165d/src/main/java/org/elasticsearch/common/unit/Fuzziness.java#L138-L147) contains:
```java
final int len = termLen(text);
if (len <= 2) {
    return 0;
} else if (len > 5) {
    return 2;
} else {
    return 1;
}
```
For backwards compatibility the documentation should be adapted to:

`0..1`:: must match exactly
`1..5`:: one edit allowed
`>5`:: two edits allowed

(though I personally would prefer to change the implementation - then 'Flyod' would match 'Floyd' with fuzziness 'AUTO', now I'm needing fuzziness 2)

**Comment by clintongormley** [comment]
Hi @grmblfrz 

Thanks for spotting this.  

> (though I personally would prefer to change the implementation - then 'Flyod' would match 'Floyd' with fuzziness 'AUTO', now I'm needing fuzziness 2)

Actually, you can set `fuzzy_transpositions` to `true`, which will mean that swapping `yo` is a single step:

    DELETE t
    
    PUT /t/t/1
    {
      "text": "Floyd"
    }

    GET /_search
    {
      "query": {
        "match": {
          "text": {
            "query": "flyod",
            "fuzziness": 1,
            "fuzzy_transpositions": true
          }
        }
      }
    }

So I wonder if the right thing is to change the cutoff from 5 to 4, or to default to fuzzy transpositions?

**Comment by clintongormley** [comment]
@mikemccand any thoughts on this?

**Comment by mikemccand** [comment]
+1 to default to fuzzy_transpositions = true.

A cutoff for 4 to allow 2 edits seems a bit to eager...

**Comment by clintongormley** [comment]
I've updated the docs to correct the string lengths, and changed this issue to set fuzzy transpositions to true by default

**Comment by grmblfrz** [comment]
Please document the fuzzy_transpositions parameter, I did not know about it before and could not find anything in the documentation.

**Comment by devinrsmith** [comment]
I also don't see documentation around "fuzzy_transpositions", nor do I see the ability to set it in the java client code.
