### ISSUE TITLE
Document SQL Search Profiling

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#92804]
### Description

The Elasticsearch SQL implementation doesn't natively support using something like the [profile API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html), but it's not impossible to profile a SQL search (although not 100% similar).

The following steps could be taken:

1. Write your Elasticsearch SQL query
2. Run the [`_sql/translate`](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-translate.html) API
3. Use the output of step 2, to run a profile query using the native Elasticsearch query.

Today, I wasn't able to find any mention of this workflow to profile SQL queries. It might be valuable to others to have this documented.

**Comment by wchaparro** [comment]
Superceded by ES|QL
