### ISSUE TITLE
Wrong details for recovery state 

### ISSUE THREAD

**Issue by bax1989** [elastic/elasticsearch#9281]
The same steps & ENV as for issue #8914 
Observed :
The object (org.elasticsearch.indices.recovery.RecoveryState#Index) returned by 
client.admin().indices().prepareRecoveries().get().shardResponses() ... recoveryState().getIndex()
has reusedByteCount & recoveredByteCount fields always = 0.

**Comment by clintongormley** [comment]
@bax1989 could you provide more background as to what you mean here? and what version you are on?

**Comment by bax1989** [comment]
ES 1.4.2, in the previous version it was ok.
These fields are useful for providing progress information.
There are two other fields serving ~ the same purpose totalFileCount & recoveredFileCount, they seems to work ok.

**Comment by s1monw** [comment]
@bleskes we worked on this afaik - is this still present in 1.5?

**Comment by bleskes** [comment]
I think all of this is cleaned up (I did a lot of work there). The setup is very specific, so I would love to get  a confirmation from @bax1989 , once 1.5 is out.

**Comment by bax1989** [comment]
Verified with 1.5.0-SNAPSHOT, it works.

**Comment by s1monw** [comment]
perfect thanks for verifying
