### ISSUE TITLE
Documentation missing for the "keep" option of the Remove ingest processor

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch#92826]
### Elasticsearch Version

8.5.1

### Java Version

_bundled_

### OS Version

Ubuntu 22.04

### Problem Description

The docs for the Remove enrich processor (https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html) does not mention the remove option introduced in https://github.com/elastic/elasticsearch/pull/83665 in v8.2.0

It would be nice to document it, it's very useful.

Cheers,
David

### Steps to Reproduce

Create a pipeline with a Remove processor

```
{
  processors: [
    {
      remove: {
        keep: ['myField']
      }
    }
  ]
}
```

**Comment by kilfoyle** [comment]
Thanks a lot for opening this @ddolcimascolo! The docs fix is in #92836.
