### ISSUE TITLE
[Doc] params['_source'] is unavailable to runtime scripts

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#92850]
The [context docs](https://www.elastic.co/guide/en/elasticsearch/painless/8.6/painless-runtime-fields-context.html) for runtime fields stats that `params['_source']` is available for runtime fields but that key is not populated.

The docs need to be updated to remove that line.

**Comment by kilfoyle** [comment]
Thanks @stu-elastic! This will be fixed soon via #92860.

**Comment by kilfoyle** [comment]
@stu-elastic  I added you as a reviewer on #92860, but based on Abdon's comment above it seems we may not need to change anything. Please let us know what you think.

**Comment by stu-elastic** [comment]
Hrm, I came across this when debugging something else, I'll close for now and cut a new issue if I can repro what I came across.
