### ISSUE TITLE
[CI] 7.17 amazon-2022 test fails due to Temporary file directory no longer exists

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#92885]
[Amazon-2022 tests on 7.17](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=amazon-2022&&immutable/)  has been failing for a while (since 14th December, first failure [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=amazon-2022&&immutable/727/))

The failure message looks something like this:

    Execution failed for task ':qa:full-cluster-restart:v6.8.24#oldClusterTest'.
    > process was found dead while waiting for ports files, node{:qa:full-cluster-restart:v6.8.24-0}

Some clusters in the tests fail to start up, due to an underlying error

    ERROR: Temporary file directory 
    [/var/lib/jenkins/workspace/elastic+elasticsearch+7.17+multijob+platform-support-unix/os/amazon-2022${ES_TMPDIR}${ES_TMPDIR}immutable/qa/full-cluster-restart/build/testclusters/v6.8.24-0/tmp] does not exist or is not accessible

**Comment by mark-vieira** [comment]
This looks to be somethign odd happening with environment variable expansion on older 6.8 cluster versions. I've disabled BWC testing on this system for now with 4ea6d4031035c4428da58970e507b7178e3d1e89.

**Comment by mark-vieira** [comment]
We're not going back to enable these, in fact we may very well disable _all_ BWC testing on our platform matrix jobs for other reasons.
