### ISSUE TITLE
[8.6.0] Highlighting error with type: 'plain'

### ISSUE THREAD

**Issue by toannv1803** [elastic/elasticsearch#92919]
### Elasticsearch Version

8.6.0

### Java Version

_bundled_

### OS Version

Elastic cloud

### Problem Description

unsupported_operation_exception

### Steps to Reproduce

```
POST test/_doc
{ "message": "hello", "create_at": "2022-01-01T00:00:00Z" }
```
```
GET test/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "message": {
              "query": "hello"
            }
          }
        }
      ],
      "filter": [
        {
          "range": {
            "create_at": {
              "gte": "2022-01-01T00:00:00Z"
            }
          }
        }
      ]
    }
  },
  "highlight": {
    "fields": {
      "message": {
        "type": "plain"
      }
    }
  }
}
```

Response
```json
{
  "error": {
    "root_cause": [
      {
        "type": "unsupported_operation_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "4Tv7xngaTACefPDHHMNrIg",
        "reason": {
          "type": "unsupported_operation_exception",
          "reason": null
        }
      }
    ],
    "caused_by": {
      "type": "unsupported_operation_exception",
      "reason": null,
      "caused_by": {
        "type": "unsupported_operation_exception",
        "reason": null
      }
    }
  },
  "status": 500
}
```

**Comment by romseygeek** [comment]
Thanks for reporting! This looks like a bug in lucene: in WeightedSpanTermExtractor, if we don't recognise a query then we try rewriting it using a special LeafReader that doesn't support field infos.  In the case of this search, the range filter gets parsed into a FieldExistsQuery, which uses fieldinfos during its rewrite.  WeightedSpanTermExtractor doesn't know about FieldExistsQuery, so it tries to rewrite, and then gets the unsupported operation exception.

I'll open a PR to fix this in lucene.  In the meantime, you should be able to workaround it by using one of the other highlighters.

**Comment by romseygeek** [comment]
This will be fixed in the next elasticsearch release that includes lucene 9.5, which I would expect to be 8.7.  Thanks again for reporting!
