### ISSUE TITLE
Version 7.9.2 snapshots cannot be restored in version 7.17.2 (and cannot be restored in 7.12-17.x)

### ISSUE THREAD

**Issue by Frank-hfj** [elastic/elasticsearch#92924]
### Elasticsearch Version

7.9.2

### Java Version

_bundled_11.0.5+10-LTS

### OS Version

centos 7.5.1804 3.10.0-862.el7.x86_64

### Problem Description

First of all thanks for taking the time to review my question。

Old cluster:
ES version: 7.9.2
Number of cluster nodes: 5
Description: The NFS shared disk is used as the snapshot backup directory (/es/backup), which can be accessed by all nodes in the cluster.
Create a snapshot repository named 444 and create a snapshot named snapshot_444.
Pack the snapshot files and transfer them to the new cluster

New cluster:
ES version: 7.17.2
Number of cluster stages: 11
Description: The NFS shared disk is used as the snapshot backup directory (/es/backup), which can be accessed by all nodes in the cluster.
Create a snapshot warehouse named 444, decompress the files of the old cluster to this directory, and modify the relevant permissions so that the elk user can read and write.

question:
Execute curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty on the new cluster
, the snapshot shows empty

According to the official instructions, the 7.X version snapshots are all compatible. Why does this happen?

And after I tested, I found that only the 7.10.x version can load the content of the 7.9.x snapshot normally, and neither 7.11.x-7.17.x can load the snapshot content.

Is this normal? Is there something I did wrong?
thanks for help

### Steps to Reproduce

Overview: Perform a snapshot backup on a server with ES 7.9.2 installed, then transfer it to a server with versions 7.11.x-7.17.x for viewing.

【old cluster】
(My backup directory is /es/backup/ , make sure the elk user has sufficient permissions, and other nodes in the cluster can access this directory)

1.Create a snapshot repository:

$ curl -XPOST http://192.168.91.90:9200/_snapshot/444 -H 'content-Type:application/json' -d '{
"type": "fs",
"settings": {
"location": "/es/backup/444",
"max_snapshot_bytes_per_sec": "50mb",
"max_restore_bytes_per_sec": "50mb"
}
}'

2.View the snapshot repository
$ curl -XGET http://192.168.91.90:9200/_snapshot/_all?pretty

3. Take a snapshot backup (the snapshot name is snapshot_444)
$ curl -XPUT http://192.168.91.90:9200/_snapshot/444/snapshot_444?wait_for_completion=true

4. View the snapshot under the snapshot repository
$ curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty

5.View snapshot content:
$ curl -XGET http://192.168.91.71:9200/_snapshot/444/snapshot_444?pretty

6.Pack the /es/backup/444 directory and transfer it to the new cluster

$ tar zcvf 444.targz 444
$ scp 

-------

【new cluster】

(The backup directory is /es/backup/ , make sure the elk user has sufficient permissions, and other nodes in the cluster can access this directory)

Create a snapshot repository (make sure it has the same name as the old cluster repository 444)

1.Create a snapshot repository:

$ curl -XPOST http://192.168.91.80:9200/_snapshot/444 -H 'content-Type:application/json' -d '{
"type": "fs",
"settings": {
"location": "/es/backup/444",
"max_snapshot_bytes_per_sec": "50mb",
"max_restore_bytes_per_sec": "50mb"
}
}'

2.View the snapshot repository
$ curl -XGET http://192.168.91.90:9200/_snapshot/_all?pretty

3.Extract 444.tar.gz to /es/backup/444

$ tar zxvf 444.tar.gz 

4.Make sure the directory permissions of the decompressed file

$ chown -R elk:elk /es/backup/444

5. View the snapshot under the snapshot repository

$ curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty

### Logs (if relevant)

------------------Old cluster: 7.9.2------------------------------
[root@k8s-master backup]# curl  http://192.168.91.71:9200
{
  "name" : "es-node01",
  "cluster_name" : "es-cluster",
  "cluster_uuid" : "FftlWwfITnu1lN8H86A_Vg",
  "version" : {
    "number" : "7.9.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "d34da0ea4a966c4e49417f2da2f244e3e97b4e6e",
    "build_date" : "2020-09-23T00:45:33.626720Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[root@k8s-master backup]# curl -XGET http://192.168.91.71:9200/_snapshot/_all?pretty
{
  "222" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/222",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  },
  "333" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/333",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  },
  "444" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/444",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  }
}
[root@k8s-master backup]# curl -XGET http://192.168.91.71:9200/_snapshot/444/_all?pretty
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_444",
      "uuid" : "aylC1ZBCQQ6lRYeCaanVMg",
      "version_id" : 7090299,
      "version" : "7.9.2",
      "indices" : [
        "bb_index-2",
        "aa_index-1",
        "bb_index-3",
        "test_index-2",
        "test_index-4",
        "test_index-3",
        "test_index-1",
        "aa_index-2"
      ],
      "data_streams" : [ ],
      "include_global_state" : true,
      "state" : "SUCCESS",
      "start_time" : "2023-01-13T09:02:03.712Z",
      "start_time_in_millis" : 1673600523712,
      "end_time" : "2023-01-13T09:02:10.733Z",
      "end_time_in_millis" : 1673600530733,
      "duration_in_millis" : 7021,
      "failures" : [ ],
      "shards" : {
        "total" : 8,
        "failed" : 0,
        "successful" : 8
      }
    }
  ]
}

------------------Test cluster: 7.10.2---ok----------------------

[elk@es0001 src]$ curl -XGET http://192.168.91.90:9200
{
  "name" : "es-node0001",
  "cluster_name" : "es-test-cluster",
  "cluster_uuid" : "axmV6MSISfS5iAt4K8gXPw",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[elk@es0001 src]$ curl -XGET http://192.168.91.90:9200/_snapshot/_all?pretty
{
  "444" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/444",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  }
}
[elk@es0001 src]$ curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_444",
      "uuid" : "aylC1ZBCQQ6lRYeCaanVMg",
      "version_id" : 7090299,
      "version" : "7.9.2",
      "indices" : [
        "bb_index-2",
        "aa_index-1",
        "bb_index-3",
        "test_index-2",
        "test_index-4",
        "test_index-3",
        "test_index-1",
        "aa_index-2"
      ],
      "data_streams" : [ ],
      "include_global_state" : true,
      "state" : "SUCCESS",
      "start_time" : "2023-01-13T09:02:03.712Z",
      "start_time_in_millis" : 1673600523712,
      "end_time" : "2023-01-13T09:02:10.733Z",
      "end_time_in_millis" : 1673600530733,
      "duration_in_millis" : 7021,
      "failures" : [ ],
      "shards" : {
        "total" : 8,
        "failed" : 0,
        "successful" : 8
      }
    }
  ]
}

------------------Test cluster: 7.12.1---Failed----------------------

[elk@es0001 elasticsearch-7.12.1]$ curl -XGET http://192.168.91.90:9200
{
  "name" : "es-node0001",
  "cluster_name" : "es-test-cluster",
  "cluster_uuid" : "6ekVdL9_T9udAVzWZLYuMw",
  "version" : {
    "number" : "7.12.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "3186837139b9c6b6d23c3200870651f10d3343b7",
    "build_date" : "2021-04-20T20:56:39.040728659Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[elk@es0001 elasticsearch-7.12.1]$ curl -XGET http://192.168.91.90:9200/_snapshot/_all?pretty
{
  "444" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/444",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  }
}
[elk@es0001 elasticsearch-7.12.1]$ curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty
{
  **"snapshots" : [ ]**
}

------------------Test cluster: 7.13.2---Failed----------------------

[elk@es0001 elasticsearch-7.13.2]$ curl -XGET http://192.168.91.90:9200
{
  "name" : "es-node0001",
  "cluster_name" : "es-test-cluster",
  "cluster_uuid" : "Us41art3QoKhlJpwP0lilA",
  "version" : {
    "number" : "7.13.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "4d960a0733be83dd2543ca018aa4ddc42e956800",
    "build_date" : "2021-06-10T21:01:55.251515791Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[elk@es0001 elasticsearch-7.13.2]$ curl -XGET http://192.168.91.90:9200/_snapshot/_all?pretty
{
  "444" : {
    "type" : "fs",
    "settings" : {
      "location" : "/es/backup/444",
      "max_restore_bytes_per_sec" : "50mb",
      "max_snapshot_bytes_per_sec" : "50mb"
    }
  }
}
[elk@es0001 elasticsearch-7.13.2]$ curl -XGET http://192.168.91.90:9200/_snapshot/444/_all?pretty
{
  **"snapshots" : [ ]**
}

※ 7.17.2 version result same as 7.13.2 ，snapshots is empty。

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by DaveCTurner** [comment]
In particular, I think your question is answered by [this section of the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#snapshots-repository-backup), noting also [this warning](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html#snapshot-repository-contents). If you need further help, please ask on the forum rather than here on Github.
