### ISSUE TITLE
Prevent searching unsearchable shards

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#93010]
#92996 is only a temporary measure, we should revert it in due course. Opening this to track that task.

- [x] Regular searches: https://github.com/elastic/elasticsearch/pull/93053
- [x] PITs: https://github.com/elastic/elasticsearch/pull/93615
- [x] Search shard API: https://github.com/elastic/elasticsearch/pull/93615
- [x] GET API: https://github.com/elastic/elasticsearch/pull/93612
- [ ] [CCR leader indices](https://github.com/elastic/elasticsearch/blob/ea0d1a315f5324e024b39f8a5593170c0da88b32/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardChangesAction.java#L504-L506)?

**Comment by dnhatn** [comment]
I am closing this issue as I think we don't need to take any action for CCR leader indices now.
