### ISSUE TITLE
Version 8.6.0 doesn't show default_pipeline for index templates in the GET call to ES

### ISSUE THREAD

**Issue by lahsivjar** [elastic/elasticsearch#93051]
### Elasticsearch Version

8.6.0

### Java Version

_bundled_

### OS Version

NA

### Problem Description

For the APM index templates, I can see the `default_pipeline` set while visiting ```Stack Management -> Index Management -> Index Templates -> Search for `metrics-apm.app` -> Preview``` but when I query using dev-tools or via CURL to ES server I see the `default_pipeline` missing (attaching snapshot for both the cases).

<img width="809" alt="Screenshot 2023-01-17 at 2 15 09 PM" src="https://user-images.githubusercontent.com/1427601/213205435-c2f9524e-60eb-4d47-995e-0268ea37f4d4.png">
<img width="1728" alt="Screenshot 2023-01-17 at 2 16 21 PM" src="https://user-images.githubusercontent.com/1427601/213205467-f0c65c9d-f3a4-4e22-b943-b9f24a144b96.png">

The same is true for all index templates. I can successfully ingest data to APM-Server and it seems that the default_pipeline is indeed working so not sure what is wrong with the ES server.

### Steps to Reproduce

1. Create a deployment with version 8.6.0
2. Check `default_pipeline` for the APM installed index template, example: `Stack Management -> Index Management -> Index Templates -> Search for `metrics-apm.app` -> Preview`
3. Get the index template via devtools `GET _index_template/metrics-apm.app` and confirm that `default_pipeline` is missing.

**Comment by lahsivjar** [comment]
CC: @kpollich @joshdover @cmacknz @simitt

**Comment by kpollich** [comment]
Hi @lahsivjar - the `default_pipeline` value is defined on the `@package` component template. You can see this component template listed under the `composed_of` field in the parent index template. 

![image](https://user-images.githubusercontent.com/6766512/213214886-fa415fd7-d477-4b96-8a0b-55e8dba8f5b5.png)

Closing as this is a non-issue.

**Comment by lahsivjar** [comment]
@kpollich Thanks for the quick response. For 8.5 version I can see the `default_pipeline` in the index_template call; has this changed in version 8.6?

**Comment by kpollich** [comment]
Looks like it moved in https://github.com/elastic/kibana/pull/144329 as a solve for https://github.com/elastic/kibana/issues/144059
