### ISSUE TITLE
Debian Start Script passes potentially conflicting configurations

### ISSUE THREAD

**Issue by stefan79** [elastic/elasticsearch#9308]
Hi,
we have a setup under debian, under which two separate elasticsearch instances are started, which share a common /etc directory but use distinct xxx.yml files. We were unable to start two instances using the respective yaml configruations.

InternalSettingsPreparer.java will search for a configuration file using `es.default.config`, `es.config` or `elasticsearch.config`. If it finds a setting using `es.default.config`, it will assume to load everything from the environment. Thus it will simply search for a `elasticsearch.yml`, `elasticsearch.json` or `elasticsearch.properties` in the root configuration file, even though it has already loaded the configuration from the `es.default.config` setting. 

Basically it is ignoring the stated specific configuration file and reloads the configuration from the default file in the specified directory.

The provided init.d script passes a combination of `es.default.config` and `es.default.path.conf` which can lead to the conflict. 

I know we have an edge case, but it cost us lots of coffee and headaches nonetheless.

In my opinion one should either:
* refactor InternalSettingsPreparer to be more intuitive,
* log the potential conflict from the java console,
* rewrite the provided init.d script to pass a different parameter configuration, or
* at least comment the init.d script to point to the potential conflict.

I would be happy to assist and write a pach, but I would need an expert to point me into the right direction. Also I have no idea how backwards compatible one should be.

Regards

Stefan from codecentric

**Comment by tlrx** [comment]
@stefan79 thanks for reporting.

For now, maybe can you put the config files in 2 distincts folders like /etc/elasticsearch/instance-1/ and /etc/elasticsearch/instance-1/?

I agree with you, the current config loading mechanism is not so evident and we are currently updating few scripts to make them more consistent. We'll be happy to have your opinion / review once the scripts are updated.

I add"packaging" label to keep this in mind.

**Comment by stefan79** [comment]
Hi Tanguy
thanks for the quick response. We have done exactly what you have proposed as a solution and are fine with it. So we are no longer interested in a fix from the community, but I wanted to point out the issue for everybody else :-)

I will stay subscribed to the issue and callback, as soon as something happens.

Thanks again

Stefan

**Comment by clintongormley** [comment]
Custom config file paths are no longer supported, and separate config dirs are the official way to go.  Closing
