### ISSUE TITLE
Hard limit on from/size

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9311]
Requesting a million hits, or page 100,000 is always a bad idea, but users may not be aware of this.  We should impose a per-index limit on the maximum `size` + `from` that can be requested, eg 10,000.

This should not interfere with deep-scrolling.

**Comment by rjernst** [comment]
+1

**Comment by nik9000** [comment]
We should make sure that the error message returns a reference to scan/scroll too.

I'm grabbing this because I keep hearing about it being trouble.
