### ISSUE TITLE
create filed with type and format by api

### ISSUE THREAD

**Issue by AsedMorteza** [elastic/elasticsearch#93122]
hi
can create a field with the following request?
```
{"mappings":
    {"properties":
        {"address": 
            {"type":"text","format":"url"}
}
}
}
```
If not,How can it be created by request with specifying the format?
It can be created manually in Kibana But I want it to be created by request

**Comment by Gagan-1804** [comment]
You can use the Elasticsearch's Update Mapping API to create a field with a specific format. The request would look something like this:


`PUT index_name/_mapping
{
  "properties": {
    "address": {
      "type": "text",
      "format": "url"
    }
  }
}`
You can use this request to create the field in your Elasticsearch index.
This request creates or updates the mapping of the "address" field as text and specifying "url" as format.

You can also use the Elasticsearch's Put Mapping API to create a mapping for a new index.


`PUT index_name
{
  "mappings": {
    "properties": {
      "address": {
        "type": "text",
        "format": "url"
      }
    }
  }
}`
Please note that you can't update the format of a field after it is created, you need to re-create the index or use script to update the format.
It's also important to note that after creating the field, you will need to reindex your data for it to be searchable and usable with the new field type and format.

**Comment by AsedMorteza** [comment]
@Gagan-1804 this is the answer given in Dev tools:
`
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "unknown parameter [format] on mapper [address] of type [text]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_doc]: unknown parameter [format] on mapper [address] of type [text]",
    "caused_by" : {
      "type" : "mapper_parsing_exception",
      "reason" : "unknown parameter [format] on mapper [address] of type [text]"
    }
  },
  "status" : 400
}

`

**Comment by AsedMorteza** [comment]
anyone have an answer?
@elastic-crm

**Comment by michaelbaamonde** [comment]
As @dadoonet [suggested](https://github.com/elastic/elasticsearch/issues/93122#issuecomment-1401820764), this is best served on the discussion boards, so I'm closing this issue. Please post your question there and we'll be able to help you out. Thanks!

**Comment by AsedMorteza** [comment]
@Gagan-1804 
Thank you very much for your attention
I want this field to be clickable (be a link).
I don't think your explanation is useful for this
