### ISSUE TITLE
Preallocate when writing files on Windows

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9312]
When writing files in Windows, it is more efficient to preallocate the full file size before writing.  We should have a single method for creating all new files which, on Windows, performs this preallocation if the file size is known.

**Comment by jpountz** [comment]
Is it worth doing in Elasticsearch when most writes that we perform are done through Lucene?

For the record, this sounds pretty hard to do to me. There are some files that we don't know in advance how much we are going to write, eg. stored fields of flushed segments, but even for merges this is much more complicated than summing up the size of the merged segments... So I am quite skeptical about this change.

**Comment by rmuir** [comment]
There is no method in java to do this (e.g. `posix_fallocate` and so on is not exposed). If there were, I'd be more interested in its uses for improving reliability on disk full in critical places (like the old lucene segments.gen could have used it, and probably the current transaction log code). 

This would need to be added to the JDK first.

Separately, in lucene we still couldn't use this for general purpose output, as we write to streams: we don't know the size of what we are doing in advance as @jpountz mentions.
