### ISSUE TITLE
--debug-server-jvm option doesn't work for YAML tests any more

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#93144]
In the past you could tell the nodes in a test cluster to attach themselves to a waiting debugger on startup by passing the `--debug-server-jvm` option documented here:

https://github.com/elastic/elasticsearch/blob/c0228c73fea5caf279bf7141eabea50813c4528b/TESTING.asciidoc#L383-L390

I think this changed in #92379 and no longer seems to work. In fact I really wanted to attach a debugger to just one of the nodes in the cluster, and I believe #92379 might make this much easier to use (e.g. maybe via a method `LocalNodeSpecBuilder#debuggerPort(int)`). That'd be even better.

**Comment by mark-vieira** [comment]
> In fact I really wanted to attach a debugger to just one of the nodes in the cluster, and I believe #92379 might make this much easier to use (e.g. maybe via a method `LocalNodeSpecBuilder#debuggerPort(int)`). That'd be even better.

I've opened https://github.com/elastic/elasticsearch/pull/93355 to address this just emulating the current behavior or attaching to all nodes on incrementing ports. So if you have a three node cluster you'll need to start three debuggers. We can potentially improve this if it becomes increasingly annoying. I'm happy to chat about these scenarios to find the most ergonomic way to debug the node you're specifically interested in.

**Comment by DaveCTurner** [comment]
That's fine with me, I don't use a debugger on these things very much.

**Comment by mark-vieira** [comment]
> That's fine with me, I don't use a debugger on these things very much.

Fair enough. A very quick and easy thing to do would be to generate multiple "Debug Elasticsearch" run configurations in intellij on project import. That way at least you won't have to create them manually.

**Comment by pgomulka** [comment]
> So if you have a three node cluster you'll need to start three debuggers. 

this is what I do and I think this makes sense. IMHO it does not need an improvement.
