### ISSUE TITLE
Set log level to WARN (or ERROR?) if HTTP or Transport modules publish on 169.254.x.x

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#9316]
[2015-01-15 11:27:46,954][INFO ][transport                ] [myserver] bound_address {inet[/0.0.0.0:9300]}, publish_address {inet[/169.254.0.2:9300]}

[2015-01-15 11:28:16,972][INFO ][http                     ] [myserver] bound_address {inet[/0.0.0.0:9200]}, publish_address {inet[/169.254.0.2:9200]}

This is a symptom of networking not configured as intended in 99% of cases

See http://tools.ietf.org/html/rfc5735#section-3

"Cotton & Vegoda          Best Current Practice                  [Page 3]
 
RFC 5735               Special Use IPv4 Addresses           January 2010

   127.0.0.0/8 - This block is assigned for use as the Internet host
   loopback address.  A datagram sent by a higher-level protocol to an
   address anywhere within this block loops back inside the host.  This
   is ordinarily implemented using only 127.0.0.1/32 for loopback.  As
   described in [RFC1122], Section 3.2.1.3, addresses within the entire
   127.0.0.0/8 block do not legitimately appear on any network anywhere.

   169.254.0.0/16 - This is the "link local" block.  As described in
   [RFC3927], it is allocated for communication between hosts on a
   single link.  Hosts obtain these addresses by auto-configuration,
   such as when a DHCP server cannot be found."

**Comment by rjernst** [comment]
+1 to have some kind of messaging to the user.  But maybe should it be an *additional* message (ERROR)? Or is it even useful for us to actually bind to these addresses, or should we fail startup?

**Comment by clintongormley** [comment]
Can anybody provide more info about whether binding to a 169.254 block is ever valid?

**Comment by jpountz** [comment]
Don't know if it is ever valid, but agreed that a warning would be helpful.

**Comment by clintongormley** [comment]
Networking now has to be configured explicitly.  Closing
