### ISSUE TITLE
Shift more work over to the SNAPSHOT_META pool

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#93220]
Dedicated master nodes only really manipulate snapshot metadata, but they do quite a lot of this work in the limited-size `SNAPSHOT` pool instead of the much larger `SNAPSHOT_META` pool. It's important to throttle some of this work, particularly the parts where we delete a lot of blobs which may require overwhelming amounts of heap otherwise, but the parts where we upload metadata blobs should be fairly lightweight and would benefit from more parallelism.

Possibly we should be using `SNAPSHOT_META` for this all, with a `PrioritizedThrottledTaskRunner` to throttle the deletes instead of relying on the limited size of the `SNAPSHOT` pool.

**Comment by pxsalehi** [comment]
@DaveCTurner do you mean we should have a `PrioritizedThrottledTaskRunner` on top of the  `SNAPSHOT_META` threadpool that has two types of tasks: `DeleteBlockTask`, and `UploadMetadataBlobTask`, with the `UploadMetadataBlobTask` taking precedence over `DeleteBlockTask`, or just a ThrottledRunner for the deletes (have to check whether the priority part can be used or is useful here) and for metadata upload only changing the threadpool?

**Comment by pxsalehi** [comment]
(to me the latter seems more desirable, but I guess they are kind of similar)

**Comment by DaveCTurner** [comment]
I suspect we want a dedicated `ThrottledRunner` for the delete tasks only - this would mean that the deletes would interleave amongst the other metadata tasks, allowing them to make some progress even while other snapshot finalisation is happening.

**Comment by pxsalehi** [comment]
Makes sense. I'll start with this, and we can discuss more over the draft PR.

**Comment by DaveCTurner** [comment]
We decided not to do this.
