### ISSUE TITLE
[CI] Error building main / 8.6 DRA snapshot

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#93241]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+dra-snapshot

### Repro line

-

### Does it reproduce?

Didn't try

### Applicable branches

8.6

### Failure excerpt

Second gradle build scan (https://gradle-enterprise.elastic.co/s/at74d6kn5l7gi) in this job fails with this:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'release-manager'.
> Failed to notify project evaluation listener.
   > .mvn/wrapper/maven-wrapper.properties (No such file or directory)
```

 Not sure if this needs intervention so I'm opening this issue, please close if this is more likely to be temporary.

**Comment by cbuescher** [comment]
Also seems to be a thing on the `main` branch now:

https://gradle-enterprise.elastic.co/s/ne6srecmry65e

**Comment by mark-vieira** [comment]
This has been resolved.
