### ISSUE TITLE
[CI] MLModelDeploymentFullClusterRestartIT:: testDeploymentSurvivesRestart failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#93325]
### CI Link

https://gradle-enterprise.elastic.co/s/u2lcxs24nfi2q/tests/:x-pack:qa:full-cluster-restart:v8.4.3%23bwcTest/org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT/testDeploymentSurvivesRestart%20%7Bcluster=UPGRADED%7D?expanded-stacktrace=WyIwIl0&page=eyJvdXRwdXQiOnsiMCI6MX19&top-execution=1

### Repro line

./gradlew ':x-pack:qa:full-cluster-restart:v8.4.3#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT" -Dtests.method="testDeploymentSurvivesRestart {cluster=UPGRADED}" -Dtests.seed=498A9316A1FD5CFF -Dtests.bwc=true -Dtests.locale=cs-CZ -Dtests.timezone=Asia/Yangon -Druntime.java=17

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

{"error":{"root_cause":[{"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized"}],"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized","caused_by":{"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized"}},"status":409} 

at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) 
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)  
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)  
at org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.infer(MLModelDeploymentFullClusterRestartIT.java:220) at org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.assertInfer(MLModelDeploymentFullClusterRestartIT.java:132) at org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.testDeploymentSurvivesRestart(MLModelDeploymentFullClusterRestartIT.java:108)

**Comment by davidkyle** [comment]
The full cluster restart test fails because it tries to call infer on a model that isn't ready after the full cluster restart. This should not happen as the previous line waits for the model to be _started_.

https://github.com/elastic/elasticsearch/blob/2bc739875465d2e3048e51a81a5d973537c6c460/x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java#L101

The _started_ status of the model is read from clusterstate. When the nodes return from the full cluster restart the status is still set to _started_ even though the model(s) have not been deployed. 

The trained model allocator notices that the cluster has changed and inspects the model assignment and finds the model assignment is perfectly satisfied by the current configuration. 

Individual nodes will notice if they should be hosting a model and deploy the model accordingly. The status is still at _started_ while all this is happening. If the node fails to deploy the model only then is the status updated with a failure reason. 

This is difficult to fix as the trained model allocator does not know that a full cluster restart has just occurred and that the status should be set back to _starting_. Eventually the status will be correct as either the model is started or fails in which case the status is updated.

**Comment by kingherc** [comment]
Happened again on https://gradle-enterprise.elastic.co/s/drn54phcm3bwi :

```


:x-pack:qa:full-cluster-restart:v8.6.2#bwcTest FAILED |  
-- | --
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  | Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 |  
  |   |  
  | REPRODUCE WITH: ./gradlew ':x-pack:qa:full-cluster-restart:v8.6.2#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT" -Dtests.method="testDeploymentSurvivesRestart {cluster=UPGRADED}" -Dtests.seed=748DE12E08CFFE64 -Dtests.bwc=true -Dtests.locale=zh-Hant-HK -Dtests.timezone=Africa/Nouakchott -Druntime.java=17 |  
  |   |  
  | org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT > testDeploymentSurvivesRestart {cluster=UPGRADED} FAILED |  
  | org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:37784], URI [/_ml/trained_models/trained-model-full-cluster-restart/deployment/_infer], status line [HTTP/1.1 409 Conflict] |  
  | Warnings: [[POST /_ml/trained_models/{model_id}/deployment/_infer] is deprecated! Use [POST /_ml/trained_models/{model_id}/_infer] instead.] |  
  | {"error":{"root_cause":[{"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized"}],"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized","caused_by":{"type":"status_exception","reason":"Trained model [trained-model-full-cluster-restart] is not initialized"}},"status":409} |  
  | at __randomizedtesting.SeedInfo.seed([748DE12E08CFFE64:9DD6E84E7E611844]:0) |  
  | at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) |  
  | at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) |  
  | at app//org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.infer(MLModelDeploymentFullClusterRestartIT.java:222) |  
  | at app//org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.assertInfer(MLModelDeploymentFullClusterRestartIT.java:134) |  
  | at app//org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.lambda$testDeploymentSurvivesRestart$1(MLModelDeploymentFullClusterRestartIT.java:109) |  
  | at app//org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1136) |  
  | at app//org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.testDeploymentSurvivesRestart(MLModelDeploymentFullClusterRestartIT.java:108) |  
  |   |  
  | Tests with failures: |  
  | - org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT.testDeploymentSurvivesRestart {cluster=UPGRADED} |  
  |   |  
  | 78 tests completed, 1 failed, 12 skipped


```

Also https://github.com/elastic/elasticsearch/issues/93377 seems related.

**Comment by droberts195** [comment]
It's failing because `assertBusy` only loops on `AssertionError`, not `ElasticsearchStatusException`. We just need to make it catch `ElasticsearchStatusException` and convert to `AssertionError` so it waits for the right situation as expected. Should be a quick fix.

**Comment by kingherc** [comment]
Another one https://gradle-enterprise.elastic.co/s/weqp2ykvhsyng . Will mute.
