### ISSUE TITLE
why do you use Elastic Search

### ISSUE THREAD

**Issue by MaryLilian** [elastic/elasticsearch#93367]
### Description

Hi, I am reading your project and I love this project
I have a question, why do you choose Elastic search in your project instead of others like Redis Search or Full text search extension for RDBMS , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose KubeMQ instead of others like Redis Search or Full text search extension

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
