### ISSUE TITLE
spring boot insert es loss data with single loop insert

### ISSUE THREAD

**Issue by qw4285632q** [elastic/elasticsearch#93372]
### Elasticsearch Version

8.2.2

### Java Version

_bundled_1.8.0_212-b10

### OS Version

3.10.0-1160.el7.x86_64

### Problem Description

spring boot batch insert es 200 records. Data will not be lost. If a single insert loops 200 times, dozens of records will be lost. and es opens the debug log. insert trace for missing record's id not caught

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/27714601/215724161-96da4170-855a-4b9a-8a4b-0d106f79e97d.png)

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
