### ISSUE TITLE
403 Forbidden, when trying to download your software 

### ISSUE THREAD

**Issue by DartPower** [elastic/elasticsearch#93411]
HTTP request sent, awaiting response... 403 Forbidden and can't download anything from repository

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by DartPower** [comment]
i think im found a answer to my question

![image](https://user-images.githubusercontent.com/2005369/216072373-02b8416f-8998-48f7-b25b-724fc1c6faf5.png)

Please stop this racism and nationalism, and unblock Russian IPs
