### ISSUE TITLE
Index recovery API time-based filtering

### ISSUE THREAD

**Issue by klacabane** [elastic/elasticsearch#93463]
### Description
Add a parameter to the index recovery API to allow more control over the data returned. While the API currently accepts an `active_only` parameter that enables this, it would be interesting to also limit the old recoveries returned as the payload can become massive and expensive to process.

### Use case
The `_recovery` API is consumed by metricbeat agents to enable monitoring of Elasticsearch in Kibana's [Stack Monitoring application](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/configuring-metricbeat.html). The agent is configured to periodically hit `/_recovery` and store the data for further analysis.
Agents can be configured by users to only retrieve the active recoveries, but when configured to retrieve all of them it can get expensive to parse the response (memory consumption) and to store the data (lots of duplicates, but this point may be improved on the ingestion side).
Note that this workflow is used in Cloud environments when enabling metrics collection and the agent configuration defaults to `active_only=false`. In Cloud the agent configuration is managed and users can't control that behavior.

Reducing the amount of data returned by the API, for example by accepting a `since` timestamp filtering out the recoveries inactive at that time, would make the monitoring workflow more efficient while still allowing the same informations to be ingested.

**Comment by DaveCTurner** [comment]
Could've sworn there was already an issue open for this idea but I don't see it now. It's a good idea for sure. Is it really only a `?since` parameter, or do you want more advanced features like pagination, sorting, other kinds of filter?

Note that when a cluster starts it must do a recovery of every shard, so in this case the response will be huge and expensive to parse even with a `?since` filter. Pagination would be a more robust way to limit the response size.

**Comment by klacabane** [comment]
Hi @DaveCTurner, this was previously suggested in a thread but never logged :)

Additional filters could be beneficial but I don't think we could make great use of them within an agent that periodically polls the API. The startup cost sounds reasonable as it would be a one time operation with subsequent calls being lightweight.

[Here is the list of properties](https://github.com/elastic/beats/blob/main/metricbeat/module/elasticsearch/index_recovery/data.go#L35-L83) we're looking for in the recoveries to be used in the Stack Monitoring's shard activity[1]. I don't have full context on the implementation of this component, but the inactive recoveries may be a useful tool when investigating past incidents.

[1]
<img width="1578" alt="Screenshot 2023-02-28 at 13 25 57" src="https://user-images.githubusercontent.com/5239883/221853842-39d6f628-d790-4d64-9f47-e556f55f6e7f.png">

**Comment by DaveCTurner** [comment]
> the inactive recoveries may be a useful tool when investigating past incidents.

Are you sure it's worth recording all this detail (repeatedly) in the monitoring indices tho? Inactive recoveries don't change so you can get them from the recoveries API directly if they're needed. Are there any dashboards or other visualisations which rely on this info, or is it really just a "may be useful" situation?

**Comment by sparrowt** [comment]
For reference I [posted here](https://discuss.elastic.co/t/possible-bug-with-monitoring-creating-thousands-of-elasticsearch-index-recovery-duplicate-docs/324673/1) about this excessive recording of duplicate data about inactive recoveries in cloud.elastic.co monitoring and was pointed here - just adding the reverse link for context.

This (event.dataset=elasticsearch.index.recovery) accounts for ~60% of _all_ documents arriving in our `.monitoring-es-8-mb` datastream so it would be much appreciated if this could be reduced.

**Comment by klacabane** [comment]
Are the inactive recoveries always guaranteed to be returned by the API or could this information be somewhat ephemeral ? The latter could justify storing these informations,. There are not other visualisations that builds on top of this data, and the use case I can think about is a 'may be useful' when root causing incident.
If the information is recoverable from the API the obvious path forward would be to only collect active recoveries.

**Comment by DaveCTurner** [comment]
It's a little ephemeral, but I am not sure that I've ever needed to look for this information in the monitoring indices when analysing an incident because the information in the ES logs is pretty detailed when something related to shard movements go wrong. https://github.com/elastic/elasticsearch/issues/60747 notes that it might be useful to track some (much less detailed) info about shard movements, but the recovery API is not the right way to do that.

**Comment by klacabane** [comment]
Thanks for the insights. At which level are these logs enabled ? Curious to see if they are available by default in cloud environments.
If ES logs provide similar capabilities for tracking shard movements then disabling retrieval of inactive recoveries sounds natural given the performance and storage cost that comes with it. This would solve the referenced cloud issue where the behavior cannot be tweaked as the configuration is managed.

**Comment by DaveCTurner** [comment]
Problems related to shard movements will appear at level `WARN` so yes we see them by default.

**Comment by klacabane** [comment]
Perfect. So I think the monitoring use case is no longer valid for the suggested enhancement since it stores redundant information expensively. I'll follow up to tweak the default behavior on the metrics collection side.

**Comment by clemmyb25** [comment]
I was wondering if there was any update on this excessive recording of duplicate data issue that @sparrowt mentioned above? We are experiencing the same issue, it is generating thousands of records every 10 seconds and filling up our storage space.

**Comment by DaveCTurner** [comment]
I think the conclusion of the above conversation is that the existing `?active_only` flag is enough for the monitoring use case, so there's no further action needed on the Elasticsearch side. Therefore I'm closing this. If that's not an accurate summary and there is more to do then please let me know and we can reopen it.

**Comment by sparrowt** [comment]
Just to follow up here, is there (or can there be somewhere) a ticket for the cloud.elastic.co folks to update their monitoring configuration to only get details of _active_ recovery?

https://discuss.elastic.co/t/possible-bug-with-monitoring-creating-thousands-of-elasticsearch-index-recovery-duplicate-docs/324673 has been closed so I can't reply there

**Comment by DaveCTurner** [comment]
The Cloud infra just uses Metricbeat so https://github.com/elastic/beats/issues would be the right place to track this publically. I don't see a Beats issue about this today but I did not search very hard.

**Comment by DaveCTurner** [comment]
I don't have an opinion about this, sorry. It's not something the Elasticsearch dev team can help with really.
