### ISSUE TITLE
Ability to link fired and recovered documents indexed by alert action

### ISSUE THREAD

**Issue by xgodon** [elastic/elasticsearch#93474]
### Description

The alerts actions allows to index a document when firing an alert, and when recovering it.
But i can't link the 2 resulting docs : 

- alert_id seems to be determined by my "group by" clause, but as it is my hostname, it isn't unique.
- context.viewInAppUrl could be used but doesn't seem ideal as collisions seem to be possible

i need to link the two to be able to represent current alerts in vega

**Comment by dnhatn** [comment]
@xgodon This appears to be an issue of another product. I hope you don't mind that I close this issue.
