### ISSUE TITLE
Add node name to _cat/recovery output

### ISSUE THREAD

**Issue by nemonster** [elastic/elasticsearch#9353]
If multiple hosts are running on a single server hostname doesn't provide an accurate picture of the recovery process.  Addition of node name, or at least the ports would differentiate between the different  running processes.

**Comment by cmims** [comment]
+1

**Comment by drewr** [comment]
:+1: This is true for `_cat/thread_pool` as well. Will fix.

**Comment by drewr** [comment]
Duplicate of #8041
