### ISSUE TITLE
Trigger snapshot backup before deployment

### ISSUE THREAD

**Issue by razine-bensari** [elastic/elasticsearch#93571]
### Description

As a dev team, each time we do deployment we trigger a manual snapshot backup of all indices. By default elastic takes care of that every 30 minutes and adds the additional snapshot to the repository. But as a measure of precaution, we also trigger a snapshot before each deployment so we have the latest update snapshot we can recover from if we need to rollback or there is a deployment issue.

It would be nice if this feature can be part of the snapshot policy somewhere that we can enable.

:)

**Comment by DaveCTurner** [comment]
Hi @razine-bensari, thanks for your interest in Elasticsearch. I'm afraid I don't understand your suggestion. Elasticsearch doesn't know when you're about to do a deployment so you must do _something_ to tell it that it needs to take another snapshot, but it seems sensible to me for that _something_ to be taking the snapshot as you do today. What am I missing here?

**Comment by DaveCTurner** [comment]
Not heard anything further in a while here, so I'm closing this. We can reopen it if it later turns out that there is some action to take.
