### ISSUE TITLE
action.auto_create_index_from_template

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9359]
`action.auto_create_index` works great if you know all of the index names up front. It also tends to work well if there's a pattern to your index names.

However, where index names aren't named consistently, which is pretty common, then it's a hassle to whitelist them all. It also may be difficult to do with plugins.

I think that that it would make a lot of sense to have an additional whitelist option that allows users to whitelist any template-created index, like `action.auto_create_index_from_template: true` that you can use _if_ disabling normal auto creation. This would allow any index created by templates to be created even if they're not explicitly listed in `action.auto_create_index`.

**Comment by pickypg** [comment]
To go a little deeper into this, I think that #788 was loosely similar to this issue (and rejected).

I think that we could still provide for security with this behavior by allowing/requiring the whitelisting of template names similar to index name whitelisting. This way that template names could be given consistent names even if their associated index names are not consistent.

**Comment by rjernst** [comment]
Rather than having a separate setting, I think it would make more sense to add an additional value to `action.auto_create_index`, so that valid values are `true`, `false`, or `template_only`.

**Comment by clintongormley** [comment]
> However, where index names aren't named consistently, which is pretty common, then it's a hassle to whitelist them all. It also may be difficult to do with plugins.

@pickypg Template already use patterns, so there is *some* consistency in their naming (otherwise the templates wouldn't work). It does seem redundant to have to specify them in two places though.  Templates can of course also be applied to manually created indices.

How many templates do people generally have? I'm guessing one or two max, which means specifying one or two patterns in `auto_create_index`, which doesn't seem terribly burdensome.

> Rather than having a separate setting, I think it would make more sense to add an additional value to action.auto_create_index, so that valid values are true, false, or template_only.

@rjernst the problem with reusing `auto_create_index` with the string `template_only` is that it already accepts strings representing index names.  See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation

**Comment by rjernst** [comment]
@clintongormley Ah, I did not realize that was an existing feature.  IMO it would be better to have the trinary setting, and leave the templates to specify the patterns.  If it is true that only a small number of templates are normally used (which seems likely to me), then specifying the patterns here and in the templates seems cumbersome, and without added benefit (if you only have a few templates, why would you need to disable creation with some and not others?).

**Comment by clintongormley** [comment]
@rjernst you may want to control index creation regardless of your use of templates, eg allowing .marvel and disallowing .script.

but your idea of a ternary setting might be a nice way of doing that  - maybe a quarternary setting: true/false/templates_only/custom.  With custom, you could specify your own patterns.

**Comment by pickypg** [comment]
> Template already use patterns, so there is some consistency in their naming (otherwise the templates wouldn't work).

@clintongormley I guess that I meant that the indices created aren't necessarily related between different templates. Since template names are much more arbitrary, they could be named consistently even when index names aren't. Therefore a setting that works for templates could easily match them like people do with index names.

> How many templates do people generally have? I'm guessing one or two max, which means specifying one or two patterns in auto_create_index, which doesn't seem terribly burdensome.

For me, the problem is that plugins (like Marvel) and tools (like Logstash) will add their own templates as well, so ideally you can just blindly accept them while blocking accidental indices. For other cases, I would say that there are only a few templates (if any), but I have seen some users making heavier use of templates, which triggered this feature request.

It can also be a burden to constantly have to keep it up to date, which would be eliminated if something like `template_only` could be allowed. Perhaps problematically, that would allow dynamic whitelisting of indices by creating empty templates for the given index names, which I could see as both a positive and a big negative because it could allow a template to match `*` to effectively ignore the setting's intent. Adding it this way may also require adding blacklists to avoid things like `.script` from being enabled when it isn't expected to be.

> you may want to control index creation regardless of your use of templates, eg allowing .marvel and disallowing .script.

I agree with this.

**Comment by rjernst** [comment]
> you may want to control index creation regardless of your use of templates, eg allowing .marvel and disallowing .script.

Doesn't marvel create its indexes explicitly?

**Comment by bleskes** [comment]
Marvel creates indices by indexing into them.

**Comment by rjernst** [comment]
Ah, thanks @bleskes, good to know.

A quaternary setting sounds fine to me.

**Comment by clintongormley** [comment]
It'd be nice to support real regexes for index names as well. See #9480

**Comment by jaymode** [comment]
> It also may be difficult to do with plugins.

I'd like to revisit this part and consider plugins that need to create indices. Autocreate can simplify code, especially in the case of timeseries data being written. If a user disables auto-create completely, and installs a plugin that requires auto-create it is up to the plugin to detect this or it will wind up in a broken state. This same issue also holds true for custom patterns that restrict creation of the indices a plugin needs to create.

I'd propose that we allow plugins to declare the indices (patterns for time based) that it will be creating via autocreate. With the specific names and patterns declared we could do one of the following:

1. Check on startup that the setting allows all of the indices that plugins are going to create via autocreate and fail startup until the setting is fixed
2. The plugin patterns are explicitly allowed to be created (maybe we disallow specify `*` as the pattern)

My preference is 2 for simplicity. If a user is installing a plugin, then I feel that they are accepting the plugin's interaction with the system. I realize some may see this as a security issue; my take is that if an adversary can install a plugin on a node then you have far worse problems and regardless of plugins being explicitly allowed to auto create an index, whatever plugin gets installed could create an index.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/20640
