### ISSUE TITLE
Reduce getNumberOfInFlightFetches iterator in ClusterHealthAction of AllocationService

### ISSUE THREAD

**Issue by luyuncheng** [elastic/elasticsearch#93631]
### Description

When we restart a  ES 7.10 cluster, we found lead master cpu hot_threads much cost in `org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.getResponse` -> `org.elasticsearch.cluster.routing.allocation.AllocationService.getNumberOfInFlightFetches`

![image](https://user-images.githubusercontent.com/12760367/217780556-8a6c2dd3-49b5-4ef0-b61d-447ea38a1ca0.png)

we trace the function `getNumberOfInFlightFetches` 

![80940a22-3935-408d-a967-c4b98cd98165](https://user-images.githubusercontent.com/12760367/217780978-c52aa94a-4191-4ec1-843f-faf7da8690a4.jpeg)

it shows that **all time cost in `GatewayAllocator.getNumberOfInFlightFetches`** ,

https://github.com/elastic/elasticsearch/blob/b29399e2daa56afc926d610f8e0e59274a5ed952/server/src/main/java/org/elasticsearch/gateway/GatewayAllocator.java#L85-L93

In some case,  **it will scan all `shards * ndoes` every time**.

https://github.com/elastic/elasticsearch/blob/b29399e2daa56afc926d610f8e0e59274a5ed952/server/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L77-L84

BUT,  in most cases, the fetching status is all false after scanned once. 
there is no need to iterator nodes every time. we can add a fetching cache to ignore this at PR: #93632 

![08a8984c-5268-41c6-a002-c328737e5a08](https://user-images.githubusercontent.com/12760367/217784086-a2cc86aa-1843-424b-bd5f-d9a5764ef7f5.jpeg)

**Comment by DaveCTurner** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/93632
