### ISSUE TITLE
Add more translog details to recovery API output

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9368]
We have seen recovery processes appearing to be stuck in translog state (or taking a very long time to recover) on various occasions.  The recovery API currently shows how much it has recovered and the total_time spent recovering:

```json
      "translog" : {
        "recovered" : 7308178,
        "total_time" : "0s",
        "total_time_in_millis" : 0
      }
```

It will be helpful to also show (similar the recovery output for index files):

* The size of the translog that is being recovered
* % recovered so far
* Elasped time specific to the translog recovery operation

**Comment by clintongormley** [comment]
+1

**Comment by bleskes** [comment]
while we at it, can we also increment the total_time as we go along? right now it's only update at the end. Also, it seems it is only updated on recovery from gateway , not peer recovery.

**Comment by mikemccand** [comment]
+1
