### ISSUE TITLE
Search shards API to rewrite query and skip shards

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#93730]
The search shards API is a public API, that the search and async search API use internally when executing cross-cluster search requests (and roundtrips are not minimized). For each remote cluster involved in the search request, search shards will be invoked to collect information about the remote shards that have to be queried. The API accepts a set of indices and returns a set of shards that the coordinating node includes in the search request.  Ideally, such API would accept a query and perform the coordinator can_match phase, so that it does not return shards that could be easily skipped. The coordinator can_match phase skips shards based on index metadata (min and max) that is present in the cluster state, which the CCS coordinating cluster is not aware of for remote indices.

This would help unify the search behaviour between local and remote searches. Today searchable snapshots allow to skip shards completely when the query has a timerange filter against the `@timestamp` field that can not possibly match, and this is good to avoid throwing shards failures for irrelevant shards in the situation where frozen indices are not available (can happen as they don't have replicas).

**Comment by DaveCTurner** [comment]
> Ideally, such API would accept a query and perform the coordinator can_match phase

I think it should perform the _whole_ `can_match` phase, both the coordinator-side work based on index metadata and the data-node-side work based on query rewriting.

**Comment by javanna** [comment]
I find that surprising, I view search shards as a coordinator action, as it does not go to the data nodes. This would change the search shards API execution significantly. Also, we would need to account for remote shards that already executed can_match as part of the ordinary search execution, which sounds like it would introduce complexity. On the other hand, it would minimize the number of shard level requests from the coordinating node to the remote shards to (dfs +)  query + fetch. Is that the goal you are looking to achieve or is there more to it?

**Comment by DaveCTurner** [comment]
I think that's about it. The coordinator-side can-match phase is very weak, since it only looks at timestamp range queries on a field called `@timestamp`. The full can-match phase handles all timestamp ranges and `constant_keyword` fields, and may extend to more rewrites in future.

When we reach out to a remote cluster to get a list of shards for the subsequent phases of the search, it seems a bit odd to me not to try and reduce the length of that list as far as possible within the remote cluster before responding.

**Comment by wrathagom** [comment]
I see that #94534 has an 8.8 tag and was curios if the changes to CCS to use the new API would be coming in 8.8 as well or likely slated for 8.9 or later?

**Comment by javanna** [comment]
@wrathagom we can't guarantee that the full set of changes will make it into 8.8. #94534 focuses on the downstream clusters, and we will have to then make adjustments to the coordinating side of the execution.
