### ISSUE TITLE
Elasticsearch latest versions still packaged with vulnerable log4j 2.12.4 package

### ISSUE THREAD

**Issue by murtaza-mmc** [elastic/elasticsearch#93746]
### Elasticsearch Version

8.6.1

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

All

### Problem Description

All the latest versions of elasticsearch are still bundled with the vulnerable log4j 2.12.4 package. This is in contrast with all the announcements made by elastic which inform about remediation steps being taken (including packaging newer versions of log4j) e.g.: https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2. This was discovered due to sysdig scans failing for our docker images, which were created using the latest elasticsearch binaries. I have also confirmed the same by drilling in to the elasticsearch binary package, and finding the above said log4j 2.12.4 package.

Elasticsearch was download using the following command: `curl --retry 8 -s -L -o /tmp/elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.1-linux-x86_64.tar.gz`

List of vulnerable packages which are packaged with elasticsearch binaries:
- log4j (2.12.4)
- tika (2.4.0)
- protobuf (3.21.1)
- jackson-databind (2.13.3)

Please inform as to when this can be investigated and mitigated.

### Steps to Reproduce

- `curl --retry 8 -s -L -o /tmp/elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.1-linux-x86_64.tar.gz`

- Unpackage the archive
- Navigate to this path: /path/to/tmp/elasticsearch-8.6.1/modules/apm/agent/META-INF/maven/org.apache.logging.log4j/log4j-api
- Open the file `pom.properties`
- Verify the version for log4j: `2.12.4`

**Comment by stu-elastic** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to [security@elastic.co](mailto:security@elastic.co)

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.
