### ISSUE TITLE
action_request_validation_exception","reason":"Validation Failed: 1: type is missing

### ISSUE THREAD

**Issue by a1242902560** [elastic/elasticsearch#93762]
### Problem Description

my es server  6.8.0
The client version number of my original es is 6.7
now  The client version was upgraded to 7.15.2

###  when i use bulk to add doc it throws ```

Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://es:9200], URI [/_bulk?refresh=true&timeout=1m], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;"},"status":400}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

6.8.0 passed end-of-life a very long time ago, so I am closing this issue.
