### ISSUE TITLE
[TRANSFORM] Destination index alias management options

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#93796]
To solve https://github.com/elastic/kibana/issues/137278 it will be necessary to change the approach to creating the transform destination index for transforms installed as part of Fleet packages.

Currently when Fleet installs a transform it creates an index template with the destination index mappings, but then still has to create the destination index as well in order to set up the aliases that support subsequent upgrades of the transform.

In the future the Fleet package installer will not necessarily have permissions to create the destination index or aliases, as it runs as the `kibana_system` user and it is undesirable to keep adding extra index permissions to this.

Given the index template, the transform is capable of creating its own destination index with the desired mappings, so if it could also manage aliases then the package installer would not need to worry about any of this.

Therefore two new alias management features are needed in the transform configuration:

1. Ability to move an alias to the destination index when it is created, i.e. remove that alias from any indices that it is currently applied to and add it to the newly created destination index
2. Extend an alias to the destination index when it is created, i.e. add the alias to the destination index but leave it as-is on any other indices that it may already be applied to

**Comment by hendrikmuhs** [comment]
Afaik index templates have alias support. So _adding_ an alias should be possible already. Requirement 1, moving an alias, however does not seem possible with templates.

Something to be aware of: The destination index is created as part of `_start` at the very beginning. However the transform - which I guess will run `unattended` - won't do anything until validation passes, likely triggered by creating the necessary source indices. I don't know the use case for this, but if it is expected that transform seamless replaces functionality than this might be a problem and moving the alias should only happen after validation passed and the transform is active. Another way to look at this: it may  be better and easier to move the alias after the 1st checkpoint (similar to `retention_policy` which gets executed after every checkpoint).

**Comment by droberts195** [comment]
Implemented by #94943.
