### ISSUE TITLE
Percolator is ignoring position_offset_gap

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#9386]
I'm testing span queries on percolator and encountered a problem. It seems that percolator is ignoring position_offset_gap. Below there is an example.

    $ curl "localhost:9200/test1/_mapping/type?pretty" -XPUT -d '{"type" : {"properties" : {"field1" : {"type" : "string", "position_offset_gap" : 100}}}}'
    $ curl "localhost:9200/test1/.percolator" -d '{"type" : "type", "query" : {"span_near" : {"slop" : 90, "clauses" : [{"span_term" : {"field1" : "foo"}}, {"span_term" : {"field1":"bar"}}]}}}'
    {"_index":"test1","_type":".percolator","_id":"sK3bC-XYQ9SQ4qC3SpyXfg","_version":1,"created":true}
    $ curl "localhost:9200/test1/type/_percolate?pretty" -XGET -d '{"doc" : {"field1" : ["foo", "bar"]}}'{
      "took" : 3,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "total" : 1,
      "matches" : [ {
        "_index" : "test1",
        "_id" : "sK3bC-XYQ9SQ4qC3SpyXfg"
      } ]
    }

To verify the mapping I also run queries on ES index

    $ curl "localhost:9200/test1/type" -d '{"field1" : ["foo", "bar"]}'
    {"_index":"test1","_type":"type","_id":"HPMTUjVtS0utxr2USt6UGA","_version":1,"created":true}
    $     curl "localhost:9200/test1/type/_search?pretty" -d '{"query" : {"span_near" : {"slop" : 90, "clauses" : [{"span_term" : {"field1" : "foo"}}, {"span_term" : {"field1":"bar"}}]}}}'
    {
      "took" : 6,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 0,
        "max_score" : null,
        "hits" : [ ]
      }
    }

**Comment by prog8** [comment]
This resolves the problem
https://github.com/elasticsearch/elasticsearch/pull/9387

**Comment by synhershko** [comment]
:+1:
