### ISSUE TITLE
The ES writes consume a large amount of CPU during the process of releasing read/write locks

### ISSUE THREAD

**Issue by smallsmall-sea** [elastic/elasticsearch#93880]
### Elasticsearch Version

7.6.0

### Java Version

13

### OS Version

CentOS 7.2

### Problem Description

When the ES cluster is running, the CPU usage of a DataNode increases. When analyzing the CPU usage, it is found that the release of read and write locks occupies a large amount of CPU. It is speculated that MAP data in Threadlocal is not cleaned, leading to MAPA data inflation.
The flame diagram is as follows:
![image](https://user-images.githubusercontent.com/64074025/219570185-bcb73759-9d9e-464b-8158-e035b033b372.png)
![image](https://user-images.githubusercontent.com/64074025/219570262-32637b44-db6f-40f6-9735-3a1df438dd33.png)

### Steps to Reproduce

Can anything be done about it?

**Comment by smallsmall-sea** [comment]
I don't think ThreadLocal should consume so much CPU if it only holds a single copy of read and write state

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to 7.6.0 which is long past end-of-life, so I am closing this. If you can reproduce this in a supported version then we can reopen it.
