### ISSUE TITLE
Dynamic Mapping interprets "2021-51" as a [date] field.

### ISSUE THREAD

**Issue by anttiviljami** [elastic/elasticsearch#93888]
### Elasticsearch Version

8.5.0

### Java Version

elastic.co customer

### OS Version

elastic.co customer

### Problem Description

Dynamic mapping eagerly interprets a string with this format `2021-51` as a date field, but then fails to index due to 51 not being a valid month.

Expected behaviour would be to index `2021-51` as a text field.

### Steps to Reproduce

With [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html) turned on attempt to index this document in a fresh, empty index:

```http
POST /bugreport/_doc
{
  "not_a_date": "2022-51"
}
```

Returned error message is:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "date_time_exception",
        "reason": "date_time_exception: Invalid value for MonthOfYear (valid values 1 - 12): 51"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [not_a_date] of type [date] in document with id 'U1f9Y4YBXO70bNmhk658'. Preview of field's value: '2022-51'",
    "caused_by": {
      "type": "date_time_exception",
      "reason": "date_time_exception: Invalid value for MonthOfYear (valid values 1 - 12): 51"
    }
  },
  "status": 400
}
```

### Logs (if relevant)

Mappings on index `bugreport`

```http
GET /bugreport/_mapping
```

```json
{
  "bugreport": {
    "mappings": {}
  }
}
```

**Comment by SohailAlvi** [comment]
Hi,
I would like to take up this issue.

**Comment by anttiviljami** [comment]
Thanks @cbuescher 

🤝🤝🤝

**Comment by cbuescher** [comment]
@anttiviljami np, thanks for reporting, its an annoying bug I think.
