### ISSUE TITLE
[UNFI] AWS integrations - Billing Metrics

### ISSUE THREAD

**Issue by dharanihj** [elastic/elasticsearch#93885]
Elastic Integration - AWS billing & Metrics integration(Elasticsearch version 8.30.) is calling the billing API 2x every minute instead of every 24 hours. This is configured in the integration but is not being honored and is a bug that needs to get fixed.

Out of the box dashboards also does not display the proper metrics. Seems like the sum of all events are considered in the visualizations.

**Comment by ajmeyers42** [comment]
Related to SFDC issues https://github.com/elastic/elasticsearch/issues/93885 to link with customer implementation effort

**Comment by vinaychandrasekhar** [comment]
@dharanihj could you please provide more details - 
- what is the symptom / user facing issue that was observed re the billing API frequency of calls? How is frequency impacting operations and/or monitoring and/or something else?
- Why is it important for you/customer to set frequency to 24 hours?
- Logs that show the issue being seen
- For the dashboards, what does "does not display the proper metrics" mean? Can you put in some screen shots and explain expected values vs. currently displayed values? Also please attach any indicators of where you are seeing the numbers accurately that we can use to validate the error seen in the dashboard? (Perhaps insert a corresponding screenshot from AWS console or other)

The more detailed the bug description, the easier it will be for our engineering team to understand and troubleshoot.

**Comment by ajmeyers42** [comment]
The team willl get the collateral, and as before we can post the customer specific examples here: https://elastic.lightning.force.com/lightning/r/Case/5008X00002Jpc0rQAB/view?ws=%2Flightning%2Fr%2FAccount%2F001b00000133CR2AAM%2Fview.  

As for the 24 hour frequency, the customer feels only a daily view of the billing data is required for their needs.  is there anything about the frequency setting that would affect the dashboard aggregation?  our initial research yesterday that higher frequency records were aggregating the same data, reflecting a $9mm spend in less than 24 hours, signifncantly different than what is visible on the AWS console.

**Comment by ajmeyers42** [comment]
per guidance from mgmt, we'll add the findings on other integrations and dashboards to SFDC first for transparency and consistency for escalation

**Comment by tommyers-elastic** [comment]
hey @ajmeyers42 - just a heads up that the development team don't have access to sfdc. myself included. 

please can we move this issue to an SDH where we can keep all the information in one place? 

@dharanihj in the furture, for known bug reports on integrations (not customer specific), the https://github.com/elastic/integrations/ repo is the place, where the relevant team can be tagged.

**Comment by tommyers-elastic** [comment]
in addition to the information requested by vinay - we would also need the following to start investigating this:

* the integration version
* the exported metricbeat configuration

**Comment by dliappis** [comment]
> please can we move this issue to an SDH where we can keep all the information in one place?
> 
> @dharanihj in the furture, for known bug reports on integrations (not customer specific), the https://github.com/elastic/integrations/ repo is the place, where the relevant team can be tagged.

With this in mind, @dharanihj I'd like to close this issue as it's opened in the wrong (public Elasticsearch) repository and it's customer specific. I suggest it gets reopened as an SDH as mentioned here: https://github.com/elastic/elasticsearch/issues/93885#issuecomment-1438114172

**Comment by kingherc** [comment]
I'm closing this. Please re-open elsewhere as mentioned above if needed.
