### ISSUE TITLE
In script, doc['title'].value.contains(something),Chinese is not supported?

### ISSUE THREAD

**Issue by pcloth** [elastic/elasticsearch#93887]
### Elasticsearch Version

7.17.7

### Installed Plugins

IK

### Java Version

_bundled_

### OS Version

Linux elasticsearch 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

In script, doc['title'].value.contains(something),
When something is English and numeric, the return is correct.
When it is Chinese, it cannot return the correct result

### Steps to Reproduce

`
{
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "filter": [
            {
              "term": {
                "delete_flag": 0
              }
            },
            {
              "term": {
                "show_flag": 1
              }
            }
          ]
        }
      },
      "script_score": {
        "script":{
          "source": """
            float score = 0;
            if (doc['title'].value.contains('2023')){
              score += 100;
            }
            if (doc['title'].value.contains("工作")){
              score += 100;
            }
            return score;
"""}
            
      }, 
      "boost_mode":"sum",
      "score_mode": "sum"
    }
  }
}
`
In this example, 2023 can get +100, but "工作" can't get +100
Even if the title contains this string

**Comment by cbuescher** [comment]
@pcloth thanks for raising this, in order to reproduce and verify if this is truly a bug we would need an example document containing the title field you are trying to boost and the analysis definition that contains the analysis chain for that title field.

**Comment by pcloth** [comment]
It was verified that it was my problem. doc['title'].value is an array containing tokens instead of a string

**Comment by cbuescher** [comment]
Closing then.
