### ISSUE TITLE
Auto disable high disk watermak checks on single data node ecluster

### ISSUE THREAD

**Issue by kul** [elastic/elasticsearch#9391]
Even when there is only one data node in cluster with less than 10% disk elasticsearch tries to relocate shards which is not possible.

**Comment by markwalkom** [comment]
The default is set to 85%, see [this page](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/index-modules-allocation.html#disk) in the docs.

You should be able to increase this, or disable it entirely, though.

**Comment by clintongormley** [comment]
good point - @dakrone what do you think?

**Comment by dakrone** [comment]
@kul @clintongormley we already have this, see: https://github.com/elasticsearch/elasticsearch/blob/83fa7bfaba6a82fa312e5a57dc6226e669b8b6df/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L293-L299 and https://github.com/elasticsearch/elasticsearch/blob/83fa7bfaba6a82fa312e5a57dc6226e669b8b6df/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L444-L447

**Comment by clintongormley** [comment]
@dakrone thanks - closing

**Comment by kul** [comment]
:+1:

**Comment by kul** [comment]
@dakrone does this takes care of a cluster with one non-data master and a data slave, wouldn't `RoutingAllocation.nodes()` just give the count of nodes with non-data as well?

**Comment by dakrone** [comment]
@kul It does not currently, though it would be nice to fail open when there is only one data node (instead of only one node total).

I'll reopen this as a feature request for that.

**Comment by xuzha** [comment]
I think @metadave is not going to do this. Did a PR to close this issue.
