### ISSUE TITLE
Dynamic mode to allow only dynamic mapping of fields with explicitly named template

### ISSUE THREAD

**Issue by axw** [elastic/elasticsearch#93951]
### Description

In https://github.com/elastic/elasticsearch/pull/69948 Elasticsearch clients grew the ability to explicitly specify the name of a dynamic template to use when indexing a field that may require dynamic mapping. APM uses this for mapping self-describing metrics whose names are not known ahead of time.

To use the above mentioned feature, we must allow dynamic mapping for all fields. We would ideally like to have more control than this, so we could prevent dynamic mapping of non-metric fields. This would be useful during upgrades of stack components, where APM Server might be upgraded ahead of the integration package, potentially leading to improperly mapped fields.

I would like the ability to set `dynamic: strict`, or some new mode, but still be allowed to dynamically map fields when a template is explicitly specified.

**Comment by javanna** [comment]
hey @axw thanks for raising this. Elasticsearch considers dynamic mappings and dynamic templates kind of the same thing, as both are applied when dynamic is true and not applied when dynamic is false or strict. I can see how users may perceive dynamic templates as a concise way to provide mappings for their fields, and would want to make a distinction between applying dynamic templates only vs dynamically mapping any incoming field. This sounds very similar to what was requested and discussed in #12358 , what do you think?

**Comment by axw** [comment]
> This sounds very similar to what was requested and discussed in https://github.com/elastic/elasticsearch/issues/12358 , what do you think?

@javanna yes, I think that issue covers what I'm after. I should have searched issues first, sorry!

We could also use the trick in https://github.com/elastic/elasticsearch/issues/12358#issuecomment-1100325098, though it feels little a bit dirty.

I'll close this and track #12358.
