### ISSUE TITLE
Refactor search uses of Version.transportVersion

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#93962]
Refactor search-related uses of `Version.transportVersion` for serialisation to not use that.

Affected classes:
* AbstractSearchAsyncAction
* AsyncTaskIndexService
* PercolateQueryBuilder
* PercolatorFieldMapper
* TransportSearchHelper

**Comment by thecoop** [comment]
@dnhatn What's the search context id in `AbstractSearchAsyncAction` used for? Does it use transport version serialisation just for convenience?

**Comment by thecoop** [comment]
What is the desired behaviour of `TransportSearchHelper.checkCCSVersionCompatibility` for cloud deployments without on-prem versions?

**Comment by dnhatn** [comment]
@thecoop 

The `min_compatible_shard_node` parameter in the SearchRequest specifies the minimum version of the node that can handle the request, and any handling node with a lower version will fail the request. However,  the current implementation uses the transport version of a connection, which I think is incorrect.

The SearchContextId is returned to the client as a Base64-encoded string, and can be used in subsequent scroll or point-in-time requests. To ensure that the SearchContextId can be deserialized by any node in the cluster, the minimum node version of the cluster is used when serializing a SearchContextId. Your change in https://github.com/elastic/elasticsearch-internal/blob/d270aa87bc8f7afdad132e36e0aa92991a214e91/server/src/main/java/org/elasticsearch/action/search/SearchContextId.java#L64 to switch to the transport version seems incorrect.

Let me know if I can help on this.

**Comment by thecoop** [comment]
OK, so the key line here is [out.setTransportVersion(version)](https://github.com/elastic/elasticsearch/blob/4c46ccacaad6651e92443be8e2591f3b15df2840/server/src/main/java/org/elasticsearch/action/search/SearchContextId.java#L75) - this requires a link between node version and transport version, which is going away.

Do you need to set the transport version of this stream? All the serialised objects here are pretty simple, so I dont think the serialization version matters here, does it?

**Comment by dnhatn** [comment]
> Do you need to set the transport version of this stream? --All the serialised objects here are pretty simple, so I dont think the serialization version matters here, does it?

Yes, we need a versioned stream here as I I explained above.

> using the min node version is unstable, as an older node could bounce in & out of the cluster at the wrong time, affecting the min node version.

The cluster ensures that the min node version never goes backward.

**Comment by pgomulka** [comment]
hey @dnhatn 
let's stick with AbstractSearchAsyncAction -> SearchContextId example for now.

> The min_compatible_shard_node parameter in the SearchRequest specifies the minimum version of the node that can handle the request, and any handling node with a lower version will fail the request. However, the current implementation uses the transport version of a connection, which I think is incorrect.

why do you think taking a transport version off a connection is incorrect? the transport version used in  https://github.com/elastic/elasticsearch-internal/blob/d270aa87bc8f7afdad132e36e0aa92991a214e91/server/src/main/java/org/elasticsearch/action/search/SearchContextId.java#L64  is the global minimum transport version that the cluster supports. https://github.com/elastic/elasticsearch/blob/4c46ccacaad6651e92443be8e2591f3b15df2840/server/src/main/java/org/elasticsearch/action/search/AbstractSearchAsyncAction.java#L714
See this [PR](https://github.com/elastic/elasticsearch/pull/94157) for details
I also understand `min_compatible_shard_node` is a rest facing Version object, so we will have to map it somehow (to be discussed, but should not be a blocker) 

>> using the min node version is unstable, as an older node could bounce in & out of the cluster at the wrong time, affecting the min node version.
>
>The cluster ensures that the min node version never goes backward.

also agree. min node version will never go backwards. We were unsure for a while, but there will be a check to ensure this https://github.com/elastic/elasticsearch/pull/94157/files#diff-e3aa21a3197c1d879ef80138e64cad789dcfe69af78313183b428a745a8d4406R347

**Comment by thecoop** [comment]
In particular, we could do with help on the following areas:

* What relationship does the serialization in `PercolatorFieldMapper` and `PercolateQueryBuilder` have with the node version, and what constraints are required here?
* How is the CCS check in `TransportSearchHelper` expected to work with frequent cloud deployments?

**Comment by dnhatn** [comment]
> What are the requirements for the data serialized in AbstractSearchAsyncAction and AsyncTaskIndexService around multiple node versions & frequent cloud deployments?

It's perfectly fine to replace `getMinNodeVersion` with the `minClusterTransportVersion` introduced in https://github.com/elastic/elasticsearch/pull/94157.

**Comment by javanna** [comment]
@thecoop as for the CCS check, it's a check enabled through an undocumented node setting, that Kibana uses to verify that its functionalities don't rely on any feature that would not work in a supported CCS scenario (effectively, current node version talking to the previous minor). The check relies on the fact that the serialization code throws an exception whenever trying to serialize something that is not supported on the other end (e.g. a new feature that only the newer version supports).

As for the percolator: the query is stored in a lucene field in binary format, generated by calling writeTo on the query builder, against the version that the index was created with (`context.indexSettings().getIndexVersionCreated()`). The exact same version needs to be used when loading the query later (`PercolateQueryBuilder#createStore`).

**Comment by thecoop** [comment]
All search uses have been refactored
