### ISSUE TITLE
How to get the doc.freq hit by tokens in the similarity context, that is, remove the duplicate count tokens in doc.freq

### ISSUE THREAD

**Issue by pcloth** [elastic/elasticsearch#93970]
### Description

Just ignore the keyword token that appears multiple times in the document field.

Some users who are more experienced in keyword search need to sort by keyword hit rate instead of the system-recommended sorting

Thanks!

**Comment by benwtrent** [comment]
@pcloth have you dug into the similarity settings yet, you can manually set the similarly to be used per field, so you could have a specific multi-field that is your `keyword-doc-freq` similarity or something.

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html

**Comment by benwtrent** [comment]
closing due to lack of feedback. This sort of thing should be doable with custom similarity scripting.
