### ISSUE TITLE
Refactor Grok library

### ISSUE THREAD

**Issue by HiDAl** [elastic/elasticsearch#93982]
### What?

Grok library has the concept of a pattern bank. This pattern bank is modeled as a plain `Map<String, String>`. This makes that when dealing with pattern bank we repeat some code, like when we want to create a new `GrokProcessor`: in case the user passes custom pattern definitions, we have to check the nullity of the pattern defs, also if it's empty and then create the real pattern bank (this could be seen at `GrokProcessor, RedactProcessor, NamedGroupExtractor, and GrokCreator` classes). We could do better here, introducing our own data structure (`PatternBank`) with handy APIs that encapsulate all the related logic. Also, the `Grok` class currently has 2 different responsibilities (matching patterns & loading built-in patterns), which goes against the Single-responsibility principle. 

### How?
The idea here is to create a set of PRs that will, pace to pace, improve the environment of the internal Grok library. 

1. `Grok` class should have only 1 responsibility.
2. Introduce the concept of `PatternBank`, but the code should still be compatible with using `Map<String, String>` as a pattern bank. This will allow us to speed up the PR review process because Grok is being used by different teams.
3. Refactor the code still using `Map`s as a pattern bank to use the new data structure and involve other teams.

**Comment by joegallo** [comment]
Adding https://github.com/elastic/elasticsearch/pull/93987#discussion_r1120437661 onto the list of things to do here so that those two tasks aren't forgotten.
