### ISSUE TITLE
Refactor SQL uses of Version.transportVersion

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#93989]
SqlStreamInput/Output use TransportVersion from a read-in Version constant. We need to remove the useage of `transportVersion` field

**Comment by luigidellaquila** [comment]
Hi @thecoop 

Is the method being completely removed? Or will it be replaced by something else?
We are using it in many places to guarantee backward compatibility, so we'll have to find an alternative

**Comment by thecoop** [comment]
We are looking to remove the `Version.transportVersion` field. This is currently used by SqlStreamInput/Output to go from 'node cursor version' to 'serialisation version'. We're looking to completely separate `Version` and `TransportVersion`, so we're looking at all the existing uses.

Previously we discussed this & decided to keep the SQL uses as `Version`, as they represent a node version. However, this is less meaningful in upcoming cloud deployments.

So what does the version number used here actually mean, and what will it mean in cloud deployments? And can we remove the use of the `transportVersion` field somehow?

**Comment by thecoop** [comment]
@luigidellaquila The previous discussion was https://github.com/elastic/elasticsearch/pull/93384#discussion_r1092113914 - how will this work in cluster deployments?
