### ISSUE TITLE
i cannot to r=generate cert 

### ISSUE THREAD

**Issue by NSH531** [elastic/elasticsearch#94049]
### Elasticsearch Version

7.5

### Java Version

_bundled_

### OS Version

centos 7 

### Problem Description

It seems like you have tried to start the Elasticsearch service using the command sudo systemctl start elasticsearch.service and then used the wget command to access Elasticsearch on port 9200. However, there was a typo in the URL http://localhsot:9200, which resulted in a failure to resolve the host. When you corrected the URL to http://localhost:9200, the request succeeded.

You then attempted to install Logstash using sudo yum install logstash, but encountered an error. The error message suggests that there was an issue with one of the repositories being used, and it provides a link to a CentOS wiki article that may help to resolve the issue. You then removed the Logstash package using sudo yum remove logstash-7.17.9-1.x86_64 and attempted to install it again using sudo yum install logstash. However, when prompted to confirm the installation, you chose not to proceed by entering "N".

If you want to install Logstash, you can try running sudo yum install logstash again and this time choose "y" when prompted to confirm the installation. If you continue to encounter issues with the repositories, you may want to investigate further by following the link provided in the error message or seeking assistance from the CentOS support community.

### Steps to Reproduce

IRRELVART

**Comment by cbuescher** [comment]
Hi @NSH531! Your question is better suited to the support forums over at https://discuss.elastic.co/. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
