### ISSUE TITLE
[CI] FileSettingsServiceTests testStopWorksIfProcessingDidntReturnYet failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#94096]
Looks like the watcher thread was interrupted but the interrupt was lost somewhere along the way.

**Build scan:**
https://gradle-enterprise.elastic.co/s/tkibjrfrug5pw/tests/:server:test/org.elasticsearch.reservedstate.service.FileSettingsServiceTests/testStopWorksIfProcessingDidntReturnYet

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.reservedstate.service.FileSettingsServiceTests.testStopWorksIfProcessingDidntReturnYet" -Dtests.seed=2A90D2A7A2E74E69 -Dtests.locale=sl-SI -Dtests.timezone=America/Fortaleza -Druntime.java=17
```

**Applicable branches:**
8.7

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.reservedstate.service.FileSettingsServiceTests&tests.test=testStopWorksIfProcessingDidntReturnYet

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([2A90D2A7A2E74E69]:0)

```

**Comment by thecoop** [comment]
Only two failures from last week, it's been clear for a month otherwise

**Comment by thecoop** [comment]
Although just had another reoccurance: https://gradle-enterprise.elastic.co/s/mfcjzimc775r6/tests/:server:test/org.elasticsearch.reservedstate.service.FileSettingsServiceTests/testStopWorksIfProcessingDidntReturnYet

**Comment by cbuescher** [comment]
Another one https://gradle-enterprise.elastic.co/s/qtdz5q4ycrlso

**Comment by thecoop** [comment]
I've identified the issue - an InterruptedException was getting thrown in a mocked override that wasn't spec'd to throw it, leading to mush confusion & lost interrupts. Created #94548 for a fix
