### ISSUE TITLE
Testclusters: mechanism for asserting things about node logs

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#94118]
When running single-JVM tests we can assert things about the contents of logs using `MockLogAppender`. This doesn't work with testclusters today because we just copy across the raw `stderr` from each node. It'd be awfully useful to have the ability to assert things about the logs of a real node sometimes.

See e.g. #93133 which uses a system property to adjust the behaviour of some logging.

**Comment by mark-vieira** [comment]
This is available via `ElasticsearchCluster#getNodeLog`. See [here](https://github.com/elastic/elasticsearch/blob/5ce03f24c09feff4037a48839ca17dd8d89b33d4/test/external-modules/die-with-dignity/src/javaRestTest/java/org/elasticsearch/qa/die_with_dignity/DieWithDignityIT.java#L64) for an example usage.
