### ISSUE TITLE
Internal: Aggregation framework should construct buckets in a consistent manner

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#9411]
The way top level buckets are constructed is different than how buckets that are constructed on the fly in the aggregation framework. In the first case all the parent buckets are constructed before the a child bucket is constructed at construct time and in the latter case this isn't the case (the parent buckets are constructed/assigned lazily, so eventually the parent buckets are there). 

Would be nice if the parent buckets would always be constructed and accessible at the time the child buckets are constructed.

This behaviour lead to a bug in `nested` aggregator, which was quick fixed in PR #9335.

**Comment by clintongormley** [comment]
@martijnvg is this still the case?

**Comment by jpountz** [comment]
I think this is still the case but I don't think this is something we will change, so I'd be leaning towards closing this issue. @martijnvg what do you think?
