### ISSUE TITLE
Build: Snyk dependency monitoring job failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#94155]
### CI Link

https://gradle-enterprise.elastic.co/s/ln7lw3kbookou

### Repro line

no

### Does it reproduce?

Didn't try

### Applicable branches

8.7

### Failure excerpt

These look like uploading errors. Might be temorary and I'm not even sure we are monitoring these builds but here it is anyway, feel free to close if not of interest:

https://gradle-enterprise.elastic.co/s/ln7lw3kbookou/console-log?page=1#L472

**Comment by mark-vieira** [comment]
This is a transient error with the Synk API.
