### ISSUE TITLE
[CI] Multiple failures for unix-compatibility>>amazon-2&&immutable

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#94181]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&&immutable/690/

### Repro line

not available

### Does it reproduce?

Didn't try

### Applicable branches

main, 8.6, 8.7, 7.17

### Failure excerpt

The console contains many pages of errors, starting with `Connection refused` and moving on to many, many pages of repeated `java.io.IOException: Invalid argument` and finally ending with:

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

It is not clear what the root cause is. The final build failure seems to be reported as a result of:

```
ERROR: [Google Cloud Storage Plugin] No artifacts found matching pattern: build/*.tar.bz2
```

**Comment by craigtaverner** [comment]
Some more build failure links:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&&immutable/690/
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.6+multijob+platform-support-unix/os=amazon-2&&immutable/208/
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=amazon-2&&immutable/878/
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.7+multijob+platform-support-unix/os=amazon-2&&immutable/38/
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=amazon-2&&immutable/689/

It should also be noted that the link in #es-test-triage contain `&amp;&amp;` which is invalid and needs to be manually edited to `&&` before getting to the build failure page. I already did those edits on the links above.

**Comment by craigtaverner** [comment]
I noticed that some, not all, of the above links refer to build numbers that also report other failures in separate messages, I presume they are in the same build-chain. For example, the `878` above also resulted in the error:

```
Execution failed for task ':qa:snapshot-based-recoveries:gcs:javaRestTest'.
> Can't run bin script: `elasticsearch-plugin` does not exist. Is this the distribution you expect it to be ?
```

Which is similar to one reported last year at https://github.com/elastic/elasticsearch/issues/89341

I wonder if some of these build failures are causing cascading failures? However, in each of these build chains the reported OS is different. For example, all of the links for this issue are for `os=amazon-2`, while the other failures in the same chain have different os. The above error was reported on `os=debian-10`.

**Comment by mark-vieira** [comment]
> I wonder if some of these build failures are causing cascading failures? However, in each of these build chains the reported OS is different. For example, all of the links for this issue are for `os=amazon-2`, while the other failures in the same chain have different os. The above error was reported on `os=debian-10`.

If there are different failures across different build excutions (even in the same chain) they may be related (the commit actually introduced a problem) but they are not "cascading" in the sense that the builds don't interact with eachother in any way.

**Comment by iverase** [comment]
it seems a duplicated of https://github.com/elastic/elasticsearch/issues/93651

**Comment by mark-vieira** [comment]
Closing as duplicate.
