### ISSUE TITLE
Specify scan order of documents

### ISSUE THREAD

**Issue by sanvir10** [elastic/elasticsearch#94209]
### Description

Currently we have this scenario: 
- Total of documents in the index: **25085**
- Number of documents with _attribute_values.keyword: 2004|Chevrolet/GMC|YUKON XL DENALI_ : **2**
- Number of documents with _fitment_applicability:Universal_ : **8359**

Version of **Elasticsearch 7.17 and 8.6** samem results: 

So let me explain we are using this query: 
 `{
        "index": "index_name",
        "body": {
            "size": 20,
            "from": 0,
            "terminate_after": 5000,
            "query": {
                "bool": {
                    "minimum_should_match": 1,
                    "must_not": {
                        "term": {
                            "availability.keyword": "To be Deleted"
                        }
                    },
                    "should": [
                        {
                            "match_all": {}
                        }
                    ],
                    "must": [
                        {
                            "bool": {
                                "should": [
                                    {
                                        "term": {
                                            "attribute_values.keyword": "2004|Chevrolet/GMC|YUKON XL DENALI"
                                        }
                                    },
                                    {
                                        "term": {
                                            "fitment_applicability": "Universal"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "fitment_applicability": {
                    "terms": {
                        "field": "fitment_applicability",
                        "size": 30
                    }
                }
            }
        }
    }`

In the query we are using this params:
- terminate_after: 5000

So we would like to get products with _attribute_values.keyword_ but we only  get products with **Universal**, we did some tests removing **terminate_after** and with this change we get desired results.

Query without **terminate_after** -> desired results (Because the number of items in th result is 8359), but if the number of results is greater than 10000(default terminate_after value) again we will get undesired result, so i want to know if exist an parameter to change the scan order, or try different algorithms to scan documents in Elasticsearch.

**Comment by HiDAl** [comment]
Hi @sanvir10 

Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
