### ISSUE TITLE
ElasticsearchIllegalArgumentException[script_lang not supported [groovy]];

### ISSUE THREAD

**Issue by jonathanaf1** [elastic/elasticsearch#9422]
When attempting to use elasticsearch in conjunction with CirrusSearch, I receive the error in the title (ElasticsearchIllegalArgumentException[script_lang not supported [groovy]];) when attempting to run php $MW_INSTALL_PATH/extensions/CirrusSearch/maintenance/forceSearchIndex.php --skipLinks --indexOnSkip

I have tried the following:

*Installed Groovy on both my wiki vm and the search vm
*Enabled dynamic scripting
*Added more allowed invocations for CirrusSearch
*Merged the files in the ZIP from https://github.com/elasticsearch/elasticsearch with elasticsearch's official release

Environment:
Windows 2008 R2 (wiki server)
Windows 2012 R2 (search server)

**Comment by dakrone** [comment]
@jonathanaf1 if you are using an Elasticsearch version prior to 1.3, then the groovy script engine is not included in Elasticsearch itself, you will need to install the elasticsearch-lang-groovy plugin, which you can find here: https://github.com/elasticsearch/elasticsearch-lang-groovy

**Comment by jonathanaf1** [comment]
I'm sorry, I forgot to mention I'm using elasticsearch 1.4.2 and I also installed the groovy lang plugin but am still getting this error

**Comment by dadoonet** [comment]
You should not install this plugin for elasticsearch 1.4 and superior.
Try to remove it.

**Comment by jonathanaf1** [comment]
It is uninstalled, but I still receive the same error. I had only installed it as a troubleshooting step. I have confirmed the plugin is no longer running as it does not show in the elasticsearch startup console.

**Comment by clintongormley** [comment]
@jonathanaf1 any more news on this?

**Comment by jonathanaf1** [comment]
@clintongormley I switched to a different search, which works nicely, but I'd still like to know how to fix this so that I can test it in the dev environment. @dadoonet @dakrone or anyone else have any advice?

**Comment by dadoonet** [comment]
Do you know what is the exact request sent by CirrusSearch? Any chance you could share it with the logs of your node?

**Comment by clintongormley** [comment]
No idea what is going on here. We test on Windows 2008 and 2012 and Groovy scripting works.  Can only assume there is an installation problem, but without any further info no hope of diagnosing.

Closing this ticket, feel free to reopen if you can have more info
