### ISSUE TITLE
Improve the shard balancing heuristics settings documentation

### ISSUE THREAD

**Issue by luizgpsantos** [elastic/elasticsearch#94233]
### Description

The Elastic [subscription](https://www.elastic.co/subscriptions) page mentions that "Advanced cluster rebalancing" is an Enterprise feature. The same page says that:

> Advanced cluster rebalancing is based on observed data stream write loads described in [cluster-level shard allocation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#shards-rebalancing-heuristics).

However, the [Shard balancing heuristics settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#shards-rebalancing-heuristics) does not mention that rebalancing based on the data stream write load is an enterprise feature.

It would be great to update the documentation to reflect the following:

- Mention that rebalancing based on the data stream write load is an enterprise feature;
- The behavior when running a non-enterprise license;
- Are any of the settings (like `cluster.routing.allocation.balance.write_load`) invalid for a cluster running a non-enterprise license?

Thank you!

**Comment by abdonpijpelink** [comment]
@luizgpsantos We do not mention license levels in the documentation. The subscriptions page is the source of truth, and users should refer to that page to determine whether a feature is available to them. I'll close this issue.

**Comment by mussi** [comment]
In some parts of the docs you say, this lack of standard generates disappointment
