### ISSUE TITLE
Provide an option to only assign shards to nodes that already have them as part of allocation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9425]
Consider the following repro:

![image](https://cloud.githubusercontent.com/assets/7216393/5904896/e6ce34ea-a540-11e4-8140-d51257fd5acc.png)

![image](https://cloud.githubusercontent.com/assets/7216393/5904901/edec01a8-a540-11e4-8b2a-418d0b87c6a9.png)

![image](https://cloud.githubusercontent.com/assets/7216393/5904905/f5ee80c4-a540-11e4-8f5e-38480eac83c4.png)

![image](https://cloud.githubusercontent.com/assets/7216393/5904908/fba44abc-a540-11e4-9f50-ac5c47d4a0b5.png)

![image](https://cloud.githubusercontent.com/assets/7216393/5904912/07b3db74-a541-11e4-85b0-c38232bad05f.png)

![image](https://cloud.githubusercontent.com/assets/7216393/5904916/0d9cef44-a541-11e4-89bc-99c9e8902701.png)

* node 2 has [0], [1], [4] as its original allocation.
* cluster.routing.allocation.node_concurrent_recoveries is set to 1 (on purpose for the reproduction).
* allocation is disabled, and then node 2 is stopped.
* node 2 is started back up and then allocation is enabled again.
* [0] and [1] get allocated back to node 2 successfully when allocation is enabled (after its restart)
* [4] ends up on node 1 (instead of node 2) because node 2 already has 1 target recovery outstanding (so it decides to find another node to allocate [4] to while node 2 is performing its recovery) while node 1 has 1 source recovery (but capable of being a target for the recovery of [4]).
* At the end, rebalancing kicks in and moved [2] from node 1 to node 2, so node 2 now has [0], [1], and [2] instead of [0], [1], [4] .

It will be helpful to provide an additional option to `cluster.routing.allocation.enable` so that it will only assign shards to nodes that already have them to prevent it from performing unnecessary allocation of a shard to a different node as part of rolling restarts.  While increasing cluster.routing.allocation.node_concurrent_recoveries (from the default of 2) is a potential workaround for small deployments, it is not a viable solution for deployments with a large # of shards on each node due to its potential network and i/o implications.  For example, we can add an `existing` option to cluster.routing.allocation.enable that also works in conjunction with settings like new_primaries (eg. "existing,new_primaries”).

**Comment by martijnvg** [comment]
@ppf2 I think delayed shard allocation already helps here? and #12421 would kind of do what is desired in an automatic manner?

**Comment by clintongormley** [comment]
I agree with @martijnvg.  Adding hard rules will break allocation in ways that could lose data.  Closing in favour of #12421 and #11438
