### ISSUE TITLE
Maker checker or requester approver option for alert configuration and enable upon approval 

### ISSUE THREAD

**Issue by dhinesh260** [elastic/elasticsearch#94312]
### Description

Good to have a maker checker option.

somebody will setup the alert and admin or someone will approve that based on user role privilege, then the alert should be enabled until then it should not enable and run.

**Comment by HiDAl** [comment]
Hi @dhinesh260 

Thanks for your interest in adding a new feature. Sadly, this seems to be more related to https://github.com/elastic/kibana/ rather than Elasticsearch. So please, feel free to create a Feature Request on their repo. Thanks :)
