### ISSUE TITLE
Alerts: Give control to admin to set maximum interval allowed to select in alerting

### ISSUE THREAD

**Issue by dhinesh260** [elastic/elasticsearch#94311]
### Description

Add a option or config to admin to control maximum interval allowed  by a user to check for last X (minute/hour/days) to avoid cluster overload.

(last 5 minute / last 30 minutes) in screenshot for ref

![Elastic discover alert](https://user-images.githubusercontent.com/41980071/222922400-269ccc18-79cf-4c2d-8c79-eebb007c349f.png)

**Comment by HiDAl** [comment]
Hi @dhinesh260 

Thanks for your interest in adding a new feature. Sadly, this seems to be more related to https://github.com/elastic/kibana/ rather than Elasticsearch. So please, feel free to create a Feature Request on their repo. Thanks :)
