### ISSUE TITLE
Response 500 when I create a snapshot repository

### ISSUE THREAD

**Issue by GhostFaceZ** [elastic/elasticsearch#94316]
request body:

```json
{
    "type":"s3",
    "settings":{
        "endpoint":"xxx.com",
        "bucket":"my_bucket",
        "client":"oss_dev"
    }
}
````

I have add keystore:
```
elasticsearch-keystore add s3.client.oss_dev.access_key
elasticsearch-keystore add s3.client.oss_dev.secret_key

```

response: 
```json
{
  "error":
    {"root_cause": [
      {
        "type":"repository_exception",
        "reason":"[dev_snapshot_repository] Could not determine repository generation from root blobs"}],
        "type":"repository_exception",
        "reason":"[dev_snapshot_repository] Could not determine repository generation from root blobs",
        "caused_by":{"type":"illegal_argument_exception","reason":"Unknown s3 client name [oss_dev]. Existing client configs: default"}
     },
        "status":500
```

**Comment by HiDAl** [comment]
Hi @GhostFaceZ 

Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by woodliu** [comment]
@elastic-crm why don't remove this gay @HiDAI out of the maintainer? Wease of time and irresponsible
