### ISSUE TITLE
Temporarily remove 'search.check_ccs_compatibility' hidden option

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#94341]
Relates to #93962

The `search.check_ccs_compatibility` option is a hidden option used during Kibana development & testing to ensure there are no features introduced that are incompatible with the current running version of Elasticsearch. It does this by serializing a request, checking if it throws any exceptions, then throwing away the result.

The version to check against is the previous minor node version (`TransportServiceHelper.checkCCSVersionCompatibility`). This uses the `Version.transportVersion` field, which we need to remove. This check is only used for on-prem deployments

Using serialization in this way is not great. I am proposing we temporarily remove this option (or at least make it do nothing), allowing the transportversion work to proceed to remove the `transportVersion` field, and re-implement this check at a later point with something more robust that doesn't use serialization in this way.

**Comment by thecoop** [comment]
FYI @javanna @rjernst @DaveCTurner

**Comment by javanna** [comment]
Heya, let's connect to figure out a path forward. I don't see removing this option as a solution given that Kibana relies on this check to surface incompatibilities. It may be a test only check but it's still an important one and we'll need to figure out how to replace it with something else that is equivalent.

**Comment by thecoop** [comment]
The difficulty here is going from `Version` -> `TransportVersion`, there needs to not be a connection there. And using serialization in this way is not great. Could this be a check somewhere else? An integration test somewhere maybe?

**Comment by thecoop** [comment]
@javanna @julio-santana #95024 is the workaround to introduce a static constant that would be updated on minor releases, to maintain the existing external behaviour for kibana.

**Comment by thecoop** [comment]
We've gone with the workaround for now. This adds a bit more version management on the ES side, but getting the change done on the Kibana side is a lot of work
