### ISSUE TITLE
connection issue upgrading from 1.3.2 to 1.4.2

### ISSUE THREAD

**Issue by jeacott** [elastic/elasticsearch#9435]
I'd like to preface this by first saying that I'm using spring data elasticsearch, and in this particular case its not clear to me with which project the issue lies.

the crux of the problem is that I can connect to a remote ES cluster with 1.3.2 but not 1.4.2 regardless of the version running on the remote cluster (tried it with both)

I have an ES client constructed by spring data ES, attempting to connect to a remote ES cluster.
using ES version 1.3.2 

```
  log: 
    [main] o.s.d.e.c.TransportClientFactoryBean     : adding transport node : x.x.x.x:9300
    no errors
```

client settings (copied directly from the debug of the running instance)

```
{cluster.name=my-remote-cluster, client.transport.sniff=true, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s, name=Jim Hammond, path.logs=C:/logs, network.server=false, node.client=true}
 ```

however, using 1.4.2

```
  log:
   [           main] o.s.d.e.c.TransportClientFactoryBean     : adding transport node : x.x.x.x:9300
   [           main] .d.e.r.s.AbstractElasticsearchRepository : failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
```

client settings

```
{cluster.name=my-remote-cluster, client.transport.sniff=true, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s, name=Wolverine, path.logs=C:/logs, network.server=false, node.client=true, client.type=transport}
```

**note** the extra client.type=transport setting on the end of the 1.4.2 client.

the code I'm attempting to run is trivial, pure ES api. and the same in both cases:

```java
public void createIndexTemplate() throws Exception {
		String sourceMapping = IOUtils.toString(this.getClass().getResourceAsStream("/mappings/mappings.json"), "UTF-8");
		String sourceSettings = IOUtils.toString(this.getClass().getResourceAsStream("/settings/settings.json"), "UTF-8");

		PutIndexTemplateResponse response = client.admin().indices()
				.preparePutTemplate("sometemplate")
				.setTemplate("sometemplate*")
				.addMapping("mymap", sourceMapping)
				.setSettings(sourceSettings)
				.get();
}
```

is this an elasticsearch bug? or an issue with the way spring data is creating the client? both?
something else? is there some documentation I missed regarding the upgrade?

Thanks in advance

**Comment by dadoonet** [comment]
Nothing else in logs?
Any chance you could try to set logs to TRACE level?

**Comment by jeacott** [comment]
nothing helpful,
 this is on TRACE

2015-01-27 17:12:38.720  INFO 13860 --- [           main] o.s.d.e.c.TransportClientFactoryBean     : adding transport node : 209.160.26.57:9300
2015-01-27 17:13:21.362 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Eagerly caching bean 'elasticsearchClient' to allow for resolving potential circular references
2015-01-27 17:13:21.385 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2015-01-27 17:13:21.385 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2015-01-27 17:13:21.388 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Finished creating instance of bean 'elasticsearchClient'
2015-01-27 17:13:21.389 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Autowiring by type from bean name 'elasticsearchTemplate' via factory method to bean named 'elasticsearchClient'
2015-01-27 17:13:21.648 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Eagerly caching bean 'elasticsearchTemplate' to allow for resolving potential circular references
2015-01-27 17:13:21.657 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2015-01-27 17:13:21.657 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor'
2015-01-27 17:13:21.659 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Finished creating instance of bean 'elasticsearchTemplate'
2015-01-27 17:13:21.660 DEBUG 13860 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Invoking afterPropertiesSet() on bean with name 'esEntityRepository'
2015-01-27 17:13:21.711 ERROR 13860 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []



it's probably worth noting that since spring data doesnt support ES 1.4.2 directly, that I've 
simply replaced elasticsearch with the later version. everything else seems to work fine, 
 and indeed connecting on localhost,  and on the same local network also works ok.

fyi, my remote ES network config looks like this (2 nics, one public one private):
discovery.zen.ping.multicast.address: _eth1:ipv4_
network.publish_host: _eth1:ipv4_

I can access the public ip 9200/xx http interfaces just fine,
 and the cluster discovery on the private network works properly,
 but I cannot access the 9300 port remotely. (I can telnet to it, and I can connect via 1.3.2).
its definitely the client end of 1.4.2 that wont connect.

**Comment by dadoonet** [comment]
Your cluster is 1.4.2, right?

From an elasticsearch point of view, a client 1.4.2 should be able to connect to this cluster.

Wondering why you have here empty content.

        None of the configured nodes are available: []

**Comment by jeacott** [comment]
Yep. 1.4.2 cluster and literally the only change I'm making for the client is changing the maven dependency from 1.3.2 to 1.4.2  
1.3.2 client works. 1.4.2 doesn't. But it does connect to a local cluster if i try that.
it doesnt matter if the target cluster is 1.3.2 i tried downgrading it. The 1.4.2 client refuses to connect.

**Comment by dadoonet** [comment]
I would try opening an issue in Spring data project and may be add a link to it here.

And may be change the label of this one as it's most likely an issue when using Spring data.

To make sure, any chance you could create a Java class using 1.4.2 elasticsearch jar and create manually a Transport Client so we can check everything is correct, elasticsearch wise ?

**Comment by jeacott** [comment]
Can do. Will post result.

**Comment by jeacott** [comment]
ok, I created a simple pure java/es, and can confirm that it works just fine with 1.4.2, but not with the same settings as above. something has changed and I cant quite pinpoint what just yet. 
I've hunted through the spring data source, and its not doing anything special to configure the client at all.  
the ONLY difference is that with 1.4.2, there is an extra value evident in the settings "client.type=transport"

I have managed to figure out how to get my client to connect again though, by setting client.transport.sniff=false (which was true in both cases above, so perhaps this was a fixed bug in ES?). it's true by default.

Cheers

**Comment by dadoonet** [comment]
Hi @jeacott 


So you did succeed in connecting your pure java application to elasticsearch, right? 
Or did I misunderstand your last comment?

If you succeed in it, I believe you should open an issue in spring data elasticsearch project and close this one.

If not, could you share your pure Java project so I can look at it?

Thanks!

**Comment by jeacott** [comment]
yes, I did succeed,
  should it always have been the case that it required client.transport.sniff=false in order to connect?
In that case it looks like an ES bug that was fixed, and just happened that my project had sniff=true (it could also be that Spring Data defaults to sniff=true, haven't checked).

feel free to close this assuming the ES behaviour has changed deliberately.
I'd suggest its a change worth documenting somewhere too.

Cheers.

**Comment by dadoonet** [comment]
I missed the sniff part. Sorry. Will do more tests. Thanks for the update.

**Comment by dadoonet** [comment]
I just did some basic testing (start a node and create a trivial transport client with `client.transport.sniff` set to `true`) and everything looks fine.
Note that I tested with 2.1.0 but I'm pretty sure it's also OK in previous versions.

```java
        Settings settings = Settings.settingsBuilder()
                .put("client.transport.sniff", true)
                .build();

        Client client = TransportClient.builder().settings(settings).build()
                .addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("127.0.0.1", 9300)));
```

So I'm closing this.

**Comment by jeacott** [comment]
thats a local socket though. I only ever had an issue with a remote connection. It might be worth testing against an actual remote location? 
Spring data have since made it easy to set whatever config is required for ES so its easier to fix if you know what the problem is. I havent yet tried against ES2.x anything because there isn't yet a spring data version for it.

**Comment by dadoonet** [comment]
The same code works against a node on another machine. But in 2.0, you need to define network.host in your elasticsearch.yml file.
