### ISSUE TITLE
Revisit indices options and make default values consistent

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#9438]
We currently support different indices options within apis that execute against multiple indices:  http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/multi-index.html .

We should revisit these indices options and defaults for each api and try to make them less confusing and more consistent.

Also, the code that applies these options, more specifically `MetaData#concreteIndices`, could use some love :)

**Comment by colings86** [comment]
+1

**Comment by javanna** [comment]
Note: as part of this review process for indices options, we should probably have a look and fix this special case [here])(https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L91). It is not clear why we treat a single index expression differently compared to multiple expressions.

**Comment by clintongormley** [comment]
See #14102

**Comment by javanna** [comment]
One thing that recently came up is we should make a clearer distinction between internal options (e.g. forbidCloseIndices and ignoreAliases) and external ones (settable from REST e.g. ignore_unavailable, allow_no_indices and expand_wildcards). Unfortunately the internal ones are currently settable through java API while they should be unmodifiable (either one api can work against closed indices or it can not, it is a characteristics of the API itself).

Also, I would consider unifying allow_no_indices and ignore_unavailable, my head starts spinning anytime I have to remember what the subtle differente between the two is.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
