### ISSUE TITLE
Taking snapshot is slow when indices are migrating to cold tier

### ISSUE THREAD

**Issue by NiuBlibing** [elastic/elasticsearch#94415]
### Elasticsearch Version

7.15.2

### Java Version

_bundled_Temurin-17.0.1+12

### OS Version

Linux  Centos7 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I found that some snapshot is very slow when some indices are migrating from warm to cold.
`GET _snapshot/_status` shows that:
```
"ods_ilm-000417" : {
          "shards_stats" : {
            "initializing" : 0,
            "started" : 1,
            "finalizing" : 0,
            "done" : 0,
            "failed" : 0,
            "total" : 1
          },
          "stats" : {
            "incremental" : {
              "file_count" : 0,
              "size_in_bytes" : 0
            },
            "total" : {
              "file_count" : 0,
              "size_in_bytes" : 0
            },
            "start_time_in_millis" : 0,
            "time_in_millis" : 0
          },
          "shards" : {
            "0" : {
              "stage" : "STARTED",
              "stats" : {
                "incremental" : {
                  "file_count" : 0,
                  "size_in_bytes" : 0
                },
                "total" : {
                  "file_count" : 0,
                  "size_in_bytes" : 0
                },
                "start_time_in_millis" : 0,
                "time_in_millis" : 0
              }
            }
          }
        }
```

### Steps to Reproduce

1. set a ilm policy and trigger it
2. take a snapshot when indices is migrating.

**Comment by kingherc** [comment]
Hi @NiuBlibing , thank you for the ticket. Unfortunately it contains minimal information to try to understand if anything is wrong and why. Please give more info, for example around:

* What repository you are using and its settings (e.g. the [`max_snapshot_bytes_per_sec`](https://www.elastic.co/guide/en/elasticsearch/plugins/7.15/repository-azure-repository-settings.html))
* What other tasks are running in the meantime
* The information of the thread pools at the time
* CPU load and network traffic

**Comment by DaveCTurner** [comment]
We haven't been able to reproduce this, and the version to which it pertains is now EOL so possibly it has been fixed in the meantime. I'm closing this.
