### ISSUE TITLE
Mapper-Size Plugin Does Not Work on 8.6.2

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/elasticsearch#94468]
### Elasticsearch Version

8.6.2

### Installed Plugins

mapper-size

### Java Version

_bundled_

### OS Version

3.10.0-1160.83.1.el7.x86_64

### Problem Description

Elastic mapper-size plugin fails on version 8.6.2 with updated templates for global, index, and component (both custom and managed).  It does work in 8.5.0

### Steps to Reproduce

Enable plugin, enable _size field, ingest data
![image](https://user-images.githubusercontent.com/11168913/224350960-498d5abd-62f5-4564-9f62-ac0702c2dd20.png)
![image](https://user-images.githubusercontent.com/11168913/224351072-977a4d34-68cb-448b-9fc3-86f223171de9.png)
![image](https://user-images.githubusercontent.com/11168913/224351165-e5ee1a54-216f-4b20-a571-a09ece65274c.png)
![image](https://user-images.githubusercontent.com/11168913/224351286-13593e3a-d9a2-4b47-ad3c-fa55ea63f4f5.png)

**Works in 8.5.0 though!**
![image](https://user-images.githubusercontent.com/11168913/224351648-5184f1df-0579-4d53-a7a1-97230570a1d5.png)

**Comment by iamhowardtheduck** [comment]
8.6.0 is where the mapper-size plugin breaks
![image](https://user-images.githubusercontent.com/11168913/224359322-29d31e50-0714-4a3d-9c52-6d1a63c4c4cc.png)
![image](https://user-images.githubusercontent.com/11168913/224359423-ab0a0410-fcab-47e3-ad10-b1a81d8a0e97.png)

**Comment by benwtrent** [comment]
@iamhowardtheduck I just deployed an 8.6.2 cluster, and was able to get the `_size` field without an issue. However, I did have to specify `"fields": ["_size"]`. 

Kibana Discover, etc. use `fields: [*]` there might be a regression where we skip including `_size` when `fields: [*]` is provided. Digging deeper.

**Comment by benwtrent** [comment]
Ah, I have narrowed it down to `"stored_fields": ["*"]` being changed between the versions.

**Comment by benwtrent** [comment]
OK, its is a regression caused by: https://github.com/elastic/elasticsearch/pull/91269

Will see about getting a fix done soon

//CC @romseygeek
