### ISSUE TITLE
Building an index produces error messages

### ISSUE THREAD

**Issue by arnowelzel** [elastic/elasticsearch#94479]
### Elasticsearch Version

7.17.9

### Installed Plugins

ingest-attachment

### Java Version

openjdk 11.0.18 2023-01-17

### OS Version

Ubuntu 22.02

### Problem Description

When using the command `occ fulltextsearch:index` the following error is displayed, however the index itself seems to work:

```
┌─ Errors ────
│ Error:     72/72
│ Index: files:821361
│ Exception: Elasticsearch\Common\Exceptions\BadRequest400Exception
│ Message: field [content] not present as part of path [attachment.content]
│
│
└──
```

### Steps to Reproduce

Call `occ fulltextsearch:index`.

**Comment by stu-elastic** [comment]
Hi @arnowelzel, this appears to be a user question for the next cloud community, I recommend you reach out to them first.

If there are Elasticsearch specific user questions, you can ask them in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch).  This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

**Comment by arnowelzel** [comment]
Yes, I posted it hear by accident since the original project refers to Elasticsearch in many places and I just got confused with this, sorry.
