### ISSUE TITLE
Support Elasticsearch 8.x or OpenSearch 2.x

### ISSUE THREAD

**Issue by arnowelzel** [elastic/elasticsearch#94480]
### Description

Elasticseach 7 is already end of life but using Elasticsearch 8 or OpenSearch 2.x seems not to be possible.

**Comment by DaveCTurner** [comment]
> Sorry, wrong project!

Ah ok that makes more sense :smile:

> But about supported versions: the end-of-life page lists version as end of life since February 2, 2023.

Here's a screenshot of how the relevant bit looks at the moment:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/5058284/224398433-35e63454-3b5e-4bb2-8a59-880ba6d3a195.png">

So 7.15 will go EOL March 22nd, 7.16 will go EOL June 7th, and 7.17 will remain supported until the release of 9.0.0 which will happen at some yet-to-be-announced date in the distant future.
