### ISSUE TITLE
timeout [10s] waiting for inference result

### ISSUE THREAD

**Issue by mjzcng** [elastic/elasticsearch#94490]
### Elasticsearch Version

8.6.2

### Installed Plugins

ELAND

### Java Version

_bundled_

### OS Version

Debian 11.1

### Problem Description

Failed index says '"failure": "timeout [10s] waiting for inference result"' after reindexing via a text-embeddings which ml-model is handling by eland.

### Steps to Reproduce

I build my enviroment by using official ElasticSearch, Kibana and eland docker images. After I started all of these above, I tried to create a embedding index by using a huggingface model named 'Erlangshen'. Here is what I did:

Createing a pipeline:
PUT _ingest/pipeline/text-embeddings
{
  "description": "Text embedding pipeline",
  "processors": [
    {
      "inference": {
        "model_id": "erlangshen",
        "target_field": "text_embedding",
        "field_map": {
          "text": "text_field"
        }
      }
    }
  ],
  "on_failure": [
    {
      "set": {
        "description": "Index document to 'failed-<index>'",
        "field": "_index",
        "value": "failed-{{{_index}}}"
      }
    },
    {
      "set": {
        "description": "Set error message",
        "field": "ingest.failure",
        "value": "{{_ingest.on_failure_message}}"
      }
    }
  ]
}

Creating a new index for save embeddings:
PUT dt_data-with-embeddings
{
  "mappings": {
    "properties": {
      "text_embedding.predicted_value": {
        "type": "dense_vector",
        "dims": 768,
        "index": true,
        "similarity": "cosine"
      },
      "text": {
        "type": "text"
      }
    }
  }
}

Reindex:
POST _reindex?requests_per_second=1&wait_for_completion=false
{
  "source": {
    "index": "dt_data"
  },
  "dest": {
    "index": "dt_data-with-embeddings",
    "pipeline": "text-embeddings"
  }
}

Then I found the procedure is done and I tried to do some searching by embeddings. However, I noticed that only 13 records can be hit from 'dt_data-with-embeddings' while there were actually 19000 records in 'dt_data' index.
Then I found there are greater than 10000 records in 'failed-dt_data-with-embeddings' and the 'ingest' of every record says '"failure": "timeout [10s] waiting for inference result"'.
I want to know where I did wrong or which parameter I can modify to avoid these problems.
Thanks!!!

### Logs (if relevant)

one of hits in 'failed-dt_data-with-embeddings' is as following:
    "hits": [
      {
        "_index": "failed-dt_data-with-embeddings",
        "_id": "jlaL1oYB72RNdgQbwKxb",
        "_score": 1,
        "_ignored": [
          "text.keyword"
        ],
        "_source": {
          "id": 1554,
          "text": """A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT
                         A LONG TEXT CONTENT“”“,
          "ingest": {
            "failure": "timeout [10s] waiting for inference result"
          }
        }
      },

**Comment by davidkyle** [comment]
Hi @mjzcng 

This is a known issue that unfortunately effects 8.6.1 and 8.6.2. The problem -as you correctly identified- is that inference is timing out at ingest after 10 seconds but it should not time out at all.  

It was fixed in https://github.com/elastic/elasticsearch/pull/93731, I suggest reverting to 8.6.0 to avoid the problem. Apologies for the the problems it has caused you

**Comment by shaimole** [comment]
This Issue seems to reoccur in 8.11.0

Should I create a new issue or add the information here?

**Comment by jrizz24** [comment]
We are also experiencing this on 8.11.0

**Comment by mrklaney** [comment]
same - 8.11.0

**Comment by mrklaney** [comment]
Also experiencing with 8.11.0.   I removed that eland docker image and used 8.9.0:
`docker pull docker.elastic.co/eland/eland:8.9.0`
Which now works fine and does not time out. (f.y.i using .elser_model_2_linux-x86_64)

**Comment by caseydm** [comment]
If you're seeing this problem with 8.11.0, the problem was fixed in 8.11.1. I upgraded and it's fixed for me.
