### ISSUE TITLE
_search_shards api return errors when wildcards targets aliases that include closed indices only

### ISSUE THREAD

**Issue by rainp1ng** [elastic/elasticsearch#94495]
### Elasticsearch Version

6.8.2

### Java Version

_bundled_

### OS Version

CentOS 3.10

### Problem Description

when I try
`/<index_name>*/_search_shards`
targets a index that is closed, no error will return (response: {"nodes": {}, "indices": {}, "shards": []})

but when i try
`/<alias_name>*/_search_shards`
though targets a alias that contains the same index above, but errors will return, response:
`{"error": {"root_cause": [{"type": "index_not_found_exception", "reason": "no such index", "index_uuid": "_na_", "index": "<index_name>"}], "type": "index_not_found_exception", "reason": "no such index", "index_uuid": "_na_", "index": "<index_name>"}, "status": 404, "code": 400, "msg": "no such index", "data": null}`

didn't find a param to skip this, anybody help? thanks!

### Steps to Reproduce

process this api the same as /<index_name>*/_search_shards

**Comment by thecoop** [comment]
@rainp1ng 6.8.1 is quite an old version of ES, the earliest supported version is 7.17, although 8.x is better. Does this reproduce on a newer version of ES?

**Comment by dnhatn** [comment]
@rainp1ng Adding the parameter `allow_no_indices=true` should help.

Also, this appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
