### ISSUE TITLE
Add support for index templates to field caps API

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elasticsearch#94513]
### Description

The response from the field caps API is used to guide users as they build Kibana assets. Kibana apps also use it to detect problematic configurations that use missing fields or fields of the wrong type.

However, sometimes an index isn't available, but an index template is. For example, this occurs every time a user installs an integration. An index template is installed, but an index isn't created until the first document is ingested (sometimes a matter of hours or days).

In the meantime, Kibana is left without an idea of what fields are valid, leading to a false error state.

Field caps should support index templates so that Kibana gets a field list in this and similar scenarios.

**Comment by dnhatn** [comment]
@drewdaemon If I understand correctly, you're asking for a new API that would provide the field caps from matching index templates. While I'm not certain whether we'll be implementing such an API, have you considered using the mapping returned from the [_simulate_index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-simulate-index.html) API instead?

**Comment by drewdaemon** [comment]
@dnhatn I don't think this would be a new Elasticsearch endpoint per se. I imagine that behind the scenes it might make sense to use the output of the `_simulate_index` routine, but as a consumer my hope would be to simply receive an augmented field_caps response.

For example, say I have two fields, `rating` and `title`. `rating` exists in an index, but `title` only exists on an index template.

On the Kibana side, we could make a single call to `field_caps` and receive a response the matches the existing structure, but with the addition of some sort of flag to denote when a field is coming from a template (I called it `from_template` below).

```
{
  "indices": [ "index1", "index2", "index3", "index4", "index5" ],
  "fields": {
    "rating": {                                   
      "keyword": {
        "metadata_field": false,
        "searchable": false,
        "aggregatable": true,
        "indices": [ "index3", "index4" ],
        "non_searchable_indices": [ "index4" ]    
      }
    },
    "title": {                                    
      "text": {
        "from_template": true,
        "metadata_field": false,
        "searchable": true,
        "aggregatable": false
      }
    }
  }
}
```

In order to prevent a breaking change, perhaps the field_caps endpoint could accept a new flag like `include_templates` to turn on the new functionality.

**Comment by javanna** [comment]
We discussed this on another channel and decided not to move forward with this proposal, as supporting templated fields in the field caps API would add complexity, and potentially cause confusion as index templates may change over time, and field caps would have to reverse engineer how templates would be applied to a new index being created.We could rather rely on integrations to create an empty index instead of relying on automatic index creation when the first document gets ingested.
