### ISSUE TITLE
Add support for custom Azure endpoints in azure repository

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#94537]
Currently we only support adding an endpoint suffix for azure repositories. This is not enough when a custom Azure DNS  zone is used since the URI that's created using an endpoint suffix is incorrect.
```java
primaryUri = new URI(protocol + "://" + accountName + "." + service + "." + endpointSuffix);
``` 

We should add the ability to provide a custom endpoint to cover this situations.

**Comment by sabz90** [comment]
This is not a "custom" Azure DNS Zone, but just setting the endpoint type to "Azure DNS Zone" under the Networking tab while creating a storage account.
![Storage](https://user-images.githubusercontent.com/16514261/226319792-713ab79f-762a-4530-a65c-caf99ddeb229.jpg)

**Comment by fcofdez** [comment]
The SDK doesn't have that concept built in, you have to adjust the endpoint used to connect to the service, that's why I phrased this issue in that way.

**Comment by iqsarv** [comment]
@fcofdez 

is it possible to patch the 7.17 version of the plugin with this fix? what would be the typical turn around time to release a patch a version? thanks!

**Comment by iqsarv** [comment]
@fcofdez thanks for the fix and quick turnaround!

is this released to all versions of the plugin. we use 7.17 &
can this be consumed from artifacts of 7.17 as presented in 
https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/repository-azure.html

**Comment by sabz90** [comment]
@fcofdez Is it possible for this to be shipped in a 7.x version as well? (perhaps 7.17.10?)
we're using elastic 7.17.x and unfortunately, we won't be able to move to 8.x anytime soon.
