### ISSUE TITLE
Optimize ContentPath#pathAsText

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#94544]
### Description

`ContentPath#pathAsText` returns the current full field name in the JSON document that is being parsed. It's not especially wasteful, but it's called on every field of every indexed, which can often in the order of tens of thousands of times per second per CPU core, so any help there is welcome.

It looks like the following cases could be improved:
 - When at the root, return the provided string directly.
 - Avoid appending the same top-level fields over and over again. E.g. today if the document is `{ "top": { "inner1": 1, "inner2": 2 }}`, and `ContentPath#pathAsText` gets called on the two leaf fields, `top` would need to be appended twice to the `StringBuilder`. Could the second call only replace the end of the content of the `StringBuilder`?

**Comment by Calabronx** [comment]
Hello, im currently working on this issue as my first contribution. Already forked the project.

**Comment by Calabronx** [comment]
> Is anyone working on this at the moment? @Calabronx ? I am a first time contributer and i would like to give a try on this issue

Hello, i commit the fix already and i am waiting for a response from the team.

**Comment by Calabronx** [comment]
Hello @jpountz sorry to bother, i wanted to know if there is something missing on the pull request like a documentation or how the feedback works on this contribution, im a first timer. Thanks.

**Comment by javanna** [comment]
hey @Calabronx we have yet to look at your change, we will get back to you.

**Comment by sawilkhan** [comment]
Hey. Is anyone currently working on this issue? I would like to work on it as a first time contributer.

**Comment by cbuescher** [comment]
@sawilkhan according to [this comment](https://github.com/elastic/elasticsearch/pull/94585#issuecomment-1604212989) on the referenced PR, somebody wants to continue working on the PR.

**Comment by Utsavk** [comment]
@cbuescher Let me know if I can pick this issue as I am a first time contributor

**Comment by cbuescher** [comment]
@Utsavk I just closed the open PR, so feel free to try something. Its important for any PR to add unit tests for some of the existing behaviour of this class and particularly the method that will be optimized, then also demonstrate the behaviour is the same for any changes you make.

**Comment by dorukguner** [comment]
Hello, I've created the above pull request to address this issue. I'm a first time contributor, please let me know if there are any issues or anything needs changing

**Comment by keshav08** [comment]
Hey, Is there anyone working in this optimisation? I want to do my first contribution.

**Comment by keshav08** [comment]
@jpountz can you add the label to the PR?

**Comment by keshav08** [comment]
@jpountz how can I get write access to this repository can merge pull requests?

**Comment by benwtrent** [comment]
@keshav08 
> @jpountz how can I get write access to this repository can merge pull requests?

External contributors don't get write access. We will have to review and merge within the Elastic organization.

**Comment by keshav08** [comment]
@benwtrent Hi, can you assign a reviewer for me? Or else is there any other way I can contribute?

**Comment by 239yash** [comment]
@benwtrent Can I pick this up? Is this still open?

**Comment by cbuescher** [comment]
@239yash sorry, this has been addressed by #98244 now I think
