### ISSUE TITLE
Log the last cluster UUID that wrote to a snapshot repository

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#94558]
### Description

If multiple Elasticsearch clusters write to the same snapshot repository, the repository
will be corrupted.

As part of the solution to this problem, one has to identify the multiple clusters that write 
to the repository, remove the repository from all clusters, and re-add it to only one (the one
that's meant to be written in this repository)

It's sometimes difficult to identify the clusters that are configured to use a repository. 
Elasticsearch could log/save the last UUID that wrote to a repository to help debug this situation.

**Comment by DaveCTurner** [comment]
We record this already and should report it in the logs - see `org.elasticsearch.repositories.blobstore.BlobStoreRepository#previousWriterMessage`. Do you have a specific scenario in mind in which you didn't see these logs?

**Comment by andreidan** [comment]
Ah, I missed you folks added this already ❤️ 
Thanks, that is what I was looking for (8.7 🚀 )

**Comment by DaveCTurner** [comment]
> (8.7 🚀)

fwiw this was added in #68002, i.e. 7.12 😁
