### ISSUE TITLE
The length of keyword array is always 1

### ISSUE THREAD

**Issue by lyq2333** [elastic/elasticsearch#94570]
I create an index by
`PUT my-index-000002
{
  "mappings": {
    "properties": {
      "content":{
        "type": "keyword",
        "index_options": "freqs"
      },
      "id":{
        "type": "integer"
      }
    }
  }
}`

Then I add a doc by
`POST my-index-000002/_doc/1
{
  "content": ["apple","apple"]
}`

I search the doc by
`GET my-index-000002/_search
{
  "query": {
    "term": {
      "content": {
        "value": "apple"
      }
    }
  },
  "explain": true
}`

But the dl in explanation is 1.
![image](https://user-images.githubusercontent.com/50293466/226532348-3dcb1404-74bc-4373-ad65-0f4c7ad0e45c.png)

Is it a bug or by design？Can anyone help me？

**Comment by cbuescher** [comment]
Hi @lyq2333! Your question is better suited to the support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
