### ISSUE TITLE
Close to zero aggregation

### ISSUE THREAD

**Issue by RolfDeVries** [elastic/elasticsearch#94603]
### Description

Hi,

First time for me to request a new feature/need for documentation, so excuse me if the format is not as expected.

Elastic is really good at aggregation data. I use min/max aggeragations a lot.
Is there also a aggregation to determine a value close to zero? 
So basically min if the value is positive, and max if the value is negative...

I would like to apply this in some kibana vizualizations with lens, with/ or without scripting.
Optionally I would also like to configure the close by aggregation to be anything other than zero.

Is there any documentation on how to do this, and/or would this be a feature that others want as well?

With kind regards,
Rolf de Vries

**Comment by cbuescher** [comment]
I think a simple [range aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/search-aggregations-bucket-range-aggregation.html) with two buckets [-smalldelta -> zero][zero -> smalldelta] should do it. If that doesn't help I would like to refer you to the support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests. Many thanks.
