### ISSUE TITLE
There may be an extra row in the unordered list

### ISSUE THREAD

**Issue by jackpan123** [elastic/elasticsearch#94619]
### Elasticsearch Version

8.8.0

### Java Version

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### OS Version

Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

### Problem Description

This unorder list row statement may need to be revised when I read the CONTRIBUTING doc.
in CONTRIBUTING doc 72-73 rows, like below
* For contributions involving the elasticsearch build you can find (details about the build setup in the
* [BUILDING](BUILDING.md) file

### Steps to Reproduce

It is a document bug.

**Comment by ydv-ankit** [comment]
i'm working on it
