### ISSUE TITLE
_cat APIs add space at the end of a line

### ISSUE THREAD

**Issue by ankon** [elastic/elasticsearch#9464]
I was trying to use the _cat/master API to get the name of the current master in a shell script, and then to determine whether the current host is the master.

~~~~
#!/bin/sh

name=`curl -sf 'http://localhost:9200' | jq --raw-output .name`
master=`curl -sf 'http://localhost:9200/_cat/master?h=node' `

[ "${name}" = "${master}" ]
~~~~

The problem here is that `master` will actually contain the name of the node *and a space character*, so the line needs to be fixed to look like this:
~~~~
master=`curl -sf 'http://localhost:9200/_cat/master?h=node' | xargs echo`
~~~~

This was very surprising, and makes using these APIs for scripting harder (without adding anything for the human reader).

Quick reading through the code: this space seems to come from `org.elasticsearch.rest.action.support.RestTable#buildTextPlainResponse()`.

PS: Is there a "nicer" way to determine whether the current node is a master from shell script, without having to parse JSON?

**Comment by drewr** [comment]
No, this should be the "nice" way. :cold_sweat: We should `.trim()` lines before adding them to the response.

**Comment by drewr** [comment]
We don't build up the `UTF8StreamWriter` line-by-line, not sure if it's efficient enough to potentially build hundreds or thousands of those per request?

**Comment by clintongormley** [comment]
@drewr we could just add "\n" to the last column instead of " "
