### ISSUE TITLE
Nicer exception when no scroll ID is provided

### ISSUE THREAD

**Issue by p-run** [elastic/elasticsearch#9469]
I am trying to use elasticdump (https://www.npmjs.com/package/elasticdump) to dump/restore elasticsearch data. One elasticdump invocation yields the following:

<pre>
% elasticdump --input=http://localhost:9200/ --output=\$ 
Wed, 28 Jan 2015 18:07:28 GMT | {"error":"ElasticsearchIllegalArgumentException[Malformed scrollId []]","status":400}
[
]
</pre>

What is a scrollId and why is it malformed? Google is of no help in understanding this error message.

This exception seems like a low-level one. It should be caught by higher level code and converted to a more meaningful error message, like, say, "index was not specified".

**Comment by clintongormley** [comment]
Hi @p-run 

A scroll ID is used to track the progress of the scroll request on each shard.  The scroll ID changes on every request, and the new ID needs to be passed to the next scroll request.

If you have many shards, then the scroll ID can be very long.  In fact it can be too long to pass in the URL or query string.  For this reason, we also support passing the scroll ID in the body. 

I'm guessing that elasticdump is passing the ID in the query string, which is being truncated, and results in a malformed ID.  I suggest you open an issue against that project.

**Comment by p-run** [comment]
This exception seems to occur when I am trying to dump an empty elasticsearch instance, leading me to think that an excessively long scrollid due to huge shard count is probably not the cause.

In fact, looking at the code in https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/action/search/type/TransportSearchHelper.java and the error message again, the scrollid is empty, and this can be checked for and helpfully reported.

**Comment by clintongormley** [comment]
Ah right - so there is no scroll ID because there are no indices.  Yes, I suppose we could provide a nicer message there.

**Comment by clintongormley** [comment]
Fixed by #10178

**Comment by clintongormley** [comment]
That PR wasn't merged. Reopening

**Comment by gfyoung** [comment]
Is this an issue anymore?  From the related code <a href="https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java">here</a>, the issue seems non-existent IINM.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/10813 - thanks for spotting @gfyoung
