### ISSUE TITLE
API to return info/details on why shards are in unassigned state

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9471]
For admins, it will be nice to have an API that will return info/details on why shards are in an unassigned state (eg. is it waiting in a queue to be assigned, is it not getting assigned because there are not enough nodes for the replicas, is it not getting assigned because the shard data is corrupted, etc..).  Perhaps this can be added to the reroute API where we can issue an empty reroute request + dry_run + explain and get an explanation for the unassigned shards, etc..

**Comment by runningman84** [comment]
+1

**Comment by ppf2** [comment]
For shard corruption where it cannot open the shard, it looks like the new API here will help https://github.com/elastic/elasticsearch/pull/11545

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/14593
