### ISSUE TITLE
breaking changes : document CCS compatibility 1 minor version down from 8.0.0

### ISSUE THREAD

**Issue by jguay** [elastic/elasticsearch#94748]
### Elasticsearch Version

8.6.2

### Java Version

_bundled_

### OS Version

Any

### Problem Description

In 7.x supported remote cluster for CCS was from 6.8 upwards and in 8.x we support only one minor version down (so 8.6 can connect to 8.5+ remote cluster). This is documented here :
- [https://www.elastic.co/guide/en/elasticsearch/reference/8.6/modules-cross-cluster-search.html#ccs-supported-configurations](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/modules-cross-cluster-search.html#ccs-supported-configurations)
- [https://www.elastic.co/guide/en/elastic-stack/8.6/upgrading-elastic-stack.html#prepare-to-upgrade:~:text=Remote%20cluster%20compatibility](https://www.elastic.co/guide/en/elastic-stack/8.6/upgrading-elastic-stack.html#prepare-to-upgrade:~:text=Remote%20cluster%20compatibility)
However I am not finding this documented as breaking change here :
- https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.0.0.html (or all of the breaking changes in 8.x)
- https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html

Issue to discuss if we should add to breaking change point with a statement similar to CCS documentation to mention CCS/CCR compatibility from 8.0 is one minor version down

### Steps to Reproduce

N/A

### Logs (if relevant)

N/A

**Comment by abdonpijpelink** [comment]
Hi @jguay There is a breaking change documented here: https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_rest_api_changes (third item, "Cross-cluster search (CCS) is now only backward-compatible with the previous minor version.") 

Do you feel we need to add it somewhere else?

**Comment by jguay** [comment]
Thank you very much @abdonpijpelink sorry I missed that point so will close this issue
