### ISSUE TITLE
Unable to backup to Azure.

### ISSUE THREAD

**Issue by Mariusko82** [elastic/elasticsearch#94797]
### Elasticsearch Version

Version: 8.2.3, Build: default/docker/9905bfb62a3f0b044948376b4f607f70a8a151b4/2022-06-08T22:21:36.455508792Z, JVM: 18.0.1.1

### Java Version

_bundled_

### OS Version

Linux elasticsearch-ss-0 5.4.0-1103-azure #109~18.04.1-Ubuntu SMP Wed Jan 25 20:53:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

We are not able to create, verify and use repository in Azure storage account. We are receiving the following message: 
curl -X PUT "localhost:9200/_snapshot/lab_backup/%3Cmy_snapshot_%7Bnow%2Fd%7D%3E?pretty"
{
  "accepted" : true
}
elasticsearch@elasticsearch-ss-0:~$ curl -X PUT "localhost:9200/_snapshot/lab_backup/lab_snapshot_`date +"%Y.%m.%d"`?wait_for_completion=true"
{"error":{"root_cause":[{"type":"snapshot_exception","reason":"[lab_backup:lab_snapshot_2023.03.27/Jf2Dej8lTqOQ0L3kYXf8yg] failed to update snapshot in repository"}],"type":"snapshot_exception","reason":"[lab_backup:lab_snapshot_2023.03.27/Jf2Dej8lTqOQ0L3kYXf8yg] failed to update snapshot in repository","caused_by":{"type":"blob_storage_exception","reason":"Status code 400, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported.\nRequestId:bc4cb5e8-a01c-004b-4985-60dd95000000\nTime:2023-03-27T08:24:16.9573320Z</Message></Error>\"","suppressed":[{"type":"exception","reason":"#block terminated with an error"},{"type":"blob_storage_exception","reason":"Status code 400, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported.\nRequestId:bc4cb5f6-a01c-004b-5785-60dd95000000\nTime:2023-03-27T08:24:16.9712714Z</Message></Error>\"","suppressed":[{"type":"exception","reason":"#block terminated with an error"}]},{"type":"blob_storage_exception","reason":"Status code 400, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTypeNotSupported</Code>

elasticsearch@elasticsearch-ss-0:~$ curl -X PUT "localhost:9200/_snapshot/lab_backup?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "azure",
  "settings": {
    "client": "default",
    "container": "backupes"
  }
}
'
{
  "acknowledged" : true
}

### Steps to Reproduce

1. create Azure storage account of type StorageV2 (general purpose v2), performance Premium, replication Locally-redundant storage (LRS).  Into this SA create container "backupes". 
2. Create keystore (bin/elasticsearch-keystore add azure.client.default.key). with account name and secret.
3. create repository:elasticsearch@elasticsearch-ss-0:~$ curl -X PUT "localhost:9200/_snapshot/lab_backup?pretty" -H 'Content-Type: application/json' -d'
{
  "type": "azure",
  "settings": {
    "client": "default",
    "container": "backupes"
  }
}
'
{
  "acknowledged" : true
}
4.send snapshot to the repository:elasticsearch@elasticsearch-ss-0:~$ curl -X PUT "localhost:9200/_snapshot/lab_backup/lab_snapshot_`date +"%Y.%m.%d"`?wait_for_completion=true"
{"error":{"root_cause":[{"type":"snapshot_exception","reason":"[lab_backup:lab_snapshot_2023.03.27/Jf2Dej8lTqOQ0L3kYXf8yg] failed to update snapshot in repository"}],"type":"snapshot_exception","reason":"[lab_backup:lab_snapshot_2023.03.27/Jf2Dej8lTqOQ0L3kYXf8yg] failed to update snapshot in repository","caused_by":{"type":"blob_storage_exception","reason":"Status code 400, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported.\nRequestId:bc4cb5e8-a01c-004b-4985-60dd95000000\nTime:2023-03-27T08:24:16.9573320Z</Message></Error>\"","suppressed":[{"type":"excepti

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, there's been several bug fixes and other improvements to the Azure snapshot support in newer versions than the one you're using.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
