### ISSUE TITLE
[CI] main - unix compatibility » oraclelinux-7&&immutable failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#94803]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=oraclelinux-7&&immutable/752/console

This test suite has been failing since March 19, 2023. 

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main and other branches

### Failure history

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=oraclelinux-7&&immutable/

### Failure excerpt

```
04:51:04   1> java.io.IOException: Invalid argument
04:51:04   1> 	at sun.nio.ch.Net.accept(Native Method) ~[?:?]
04:51:04   1> 	at sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:433) ~[?:?]
04:51:04   1> 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:399) ~[?:?]
04:51:04   1> 	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:119) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:116) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
04:51:04   1> 	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:116) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at org.elasticsearch.transport.netty4.CopyBytesServerSocketChannel.doReadMessages(CopyBytesServerSocketChannel.java:45) ~[transport-netty4-8.8.0-SNAPSHOT.jar:8.8.0-SNAPSHOT]
04:51:04   1> 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:79) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.89.Final.jar:4.1.89.Final]
04:51:04   1> 	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
04:51:04   1> [2023-03-27T08:40:36,431][ERROR][o.e.t.TcpTransport       ] [node_t0] exception from server channel caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:20141}]
```

**Comment by pxsalehi** [comment]
More of this: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=oraclelinux-7&&immutable/816/

**Comment by pxsalehi** [comment]
They seem to be similar to https://github.com/elastic/elasticsearch/issues/93651

**Comment by kingherc** [comment]
More at `https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.7+multijob+platform-support-unix/os=oraclelinux-7&&immutable/191/console`

**Comment by kingherc** [comment]
More at `https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=oraclelinux-7&&immutable/1031/`

**Comment by kingherc** [comment]
This keeps failing a lot. I am unsure if we can mute it?

**Comment by mark-vieira** [comment]
We can't mute an entire platform set of tests. This certainly looks to be the same issue in https://github.com/elastic/elasticsearch/issues/93651 but amazon linux jobs seem to have magically resolved themselves and this problem has jumped to OEL-7.

**Comment by craigtaverner** [comment]
Happening quite frequently today. Some examples:

* [main] https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+multijob+platform-support-unix/os=oraclelinux-7&&immutable/872/console
* [7.17] https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.17+multijob+platform-support-unix/os=oraclelinux-7&&immutable/1052/

**Comment by mark-vieira** [comment]
This was consistently failing but has since stopped. Not sure what solved the problem, maybe the bump in the bundled JDK fixed the underlying bug?
