### ISSUE TITLE
Add a flat option to GetMappingsRequest

### ISSUE THREAD

**Issue by gogodjzhu** [elastic/elasticsearch#94809]
### Description

Now the `org.elasticsearch.client.indices.GetMappingsResponse` store mappings in a nestd map like:
```json
{
  "properties": {
    "filedA": {
      "properties": {
        "fieldAA": {
          "type": "text",
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        }
      }
    },
    "filedB": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    }
  }
}
```

It may be more readable and convenient for parser if we provide a option to return like this:
```json
{
  "properties": {
    "filedA.fieldAA": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    },
    "filedB": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    }
  }
}
```

**Comment by javanna** [comment]
hi @gogodjzhu this is kind of what the field capabilities API exposes. We consider the get mappings API more for admin consumption, but for regular users, we'd recommend consulting the field caps API which gives you a flat list of fields and their features (whether they are searchable, aggregatable etc.). See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html .
