### ISSUE TITLE
Add Index option in Preference API

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#9483]
The Preference API is great for _scoping_ or _pinning_ a search request to a certain node or shard. However it does not support specifying an index which is problematic when dealing with an alias.
To go around this, one essentially has to use a query to filter out other indices within the alias that might reside on the same node and have shards with the given id (potentially replicas).

See elasticsearch/elasticsearch-hadoop#363 as an example where such an option would be useful.

**Comment by clintongormley** [comment]
One possibility would be to add an `_only_index:index_one,index_two` option to the preference.

**Comment by clintongormley** [comment]
Suggested by @bleskes - instead of adding `_only_index`, change `_shards` to accept an index name, eg `_shards:foo[2],bar[1]`

**Comment by costin** [comment]
@clintongormley @bleskes Raised PR #9939

**Comment by clintongormley** [comment]
Copying Simon's comment from https://github.com/elastic/elasticsearch/pull/9939#issuecomment-76674898

> * what if an index has [ in it's name?
> * do we need to push complex parsing logic into Elasticsearch just to fit stuff into URL parameters, IMO we shouldn't.
> * Can we expose a safe API to wherever its needed ie. { shards : { idx : [1, 3], idx1 : [1] } and move the parsing logic for the _shards somewhere else for BWC (maybe in the REST endpoint)?

With the changes happening in https://github.com/elastic/elasticsearch/issues/10217, we could add this condition into the request body itself, which will be parsed by the coordinating node before fanning the request out to the relevant shards.

**Comment by costin** [comment]
Closing this issue in favour of https://github.com/elastic/elasticsearch/issues/13494.
@clintongormley Not sure what labels to add in this case so... I'll simply not touch anything.
