### ISSUE TITLE
ECK Faild To Pull Image

### ISSUE THREAD

**Issue by Ibrahimogod** [elastic/elasticsearch#94966]
### Elasticsearch Version

8.7.0

### Java Version

_bundled_

### OS Version

default Elasticsearch artifact

### Problem Description

trying to deploy Elasticsearch on minikube by following this instruction https://www.elastic.co/downloads/elastic-cloud-kubernetes my artifact after installing crds
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: monitoring
spec:
  version: 8.7.0
  image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
```

### Steps to Reproduce

1. install minikube 
2. run `kubectl create -f https://download.elastic.co/downloads/eck/2.7.0/crds.yaml`
3. run `kubectl apply -f https://download.elastic.co/downloads/eck/2.7.0/operator.yaml`
4. copy apply above es artifact on your minikube cluster 
5. wait for pod to be initialized and created, it will fail with error `Failed to pull image "docker.elastic.co/elasticsearch/elasticsearch:8.7.0": rpc error: code = Unknown desc = context deadline exceeded` after about 2min and 2 seconds  

### Logs (if relevant)

Name:             es-cluster-es-default-0
Namespace:        monitoring
Priority:         0
Service Account:  default
Node:             minikube/{ip}
Start Time:       Sat, 01 Apr 2023 04:24:34 +0200
Labels:           common.k8s.elastic.co/type=elasticsearch
                  controller-revision-hash=es-cluster-es-default-57d66b5598
                  elasticsearch.k8s.elastic.co/cluster-name=es-cluster
                  elasticsearch.k8s.elastic.co/http-scheme=https
                  elasticsearch.k8s.elastic.co/node-data=true
                  elasticsearch.k8s.elastic.co/node-data_cold=true
                  elasticsearch.k8s.elastic.co/node-data_content=true
                  elasticsearch.k8s.elastic.co/node-data_frozen=true
                  elasticsearch.k8s.elastic.co/node-data_hot=true
                  elasticsearch.k8s.elastic.co/node-data_warm=true
                  elasticsearch.k8s.elastic.co/node-ingest=true
                  elasticsearch.k8s.elastic.co/node-master=true
                  elasticsearch.k8s.elastic.co/node-ml=true
                  elasticsearch.k8s.elastic.co/node-remote_cluster_client=true
                  elasticsearch.k8s.elastic.co/node-transform=true
                  elasticsearch.k8s.elastic.co/node-voting_only=false
                  elasticsearch.k8s.elastic.co/statefulset-name=es-cluster-es-default
                  elasticsearch.k8s.elastic.co/version=8.7.0
                  statefulset.kubernetes.io/pod-name=es-cluster-es-default-0
Annotations:      co.elastic.logs/module: elasticsearch
                  elasticsearch.k8s.elastic.co/config-hash: 2921960909
                  kubectl.kubernetes.io/restartedAt: 2023-04-01T04:10:11+02:00
                  update.k8s.elastic.co/timestamp: 2023-04-01T02:26:37.526262873Z
Status:           Pending
IP:               ip
IPs:
  IP:           ip
Controlled By:  StatefulSet/es-cluster-es-default
Init Containers:
  elastic-internal-init-filesystem:
    Container ID:
    Image:         docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
      /mnt/elastic-internal/scripts/prepare-fs.sh
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_IP:                     (v1:status.podIP)
      POD_NAME:                  es-cluster-es-default-0 (v1:metadata.name)
      NODE_NAME:                  (v1:spec.nodeName)
      NAMESPACE:                 monitoring (v1:metadata.namespace)
      PROBE_PASSWORD_PATH:       /mnt/elastic-internal/probe-user/elastic-internal-probe
      PROBE_USERNAME:            elastic-internal-probe
      READINESS_PROBE_PROTOCOL:  https
      HEADLESS_SERVICE_NAME:     es-cluster-es-default
      NSS_SDB_USE_CACHE:         no
    Mounts:
      /mnt/elastic-internal/downward-api from downward-api (ro)
      /mnt/elastic-internal/elasticsearch-bin-local from elastic-internal-elasticsearch-bin-local (rw)
      /mnt/elastic-internal/elasticsearch-config from elastic-internal-elasticsearch-config (ro)
      /mnt/elastic-internal/elasticsearch-config-local from elastic-internal-elasticsearch-config-local (rw)
      /mnt/elastic-internal/elasticsearch-plugins-local from elastic-internal-elasticsearch-plugins-local (rw)
      /mnt/elastic-internal/probe-user from elastic-internal-probe-user (ro)
      /mnt/elastic-internal/scripts from elastic-internal-scripts (ro)
      /mnt/elastic-internal/transport-certificates from elastic-internal-transport-certificates (ro)
      /mnt/elastic-internal/unicast-hosts from elastic-internal-unicast-hosts (ro)
      /mnt/elastic-internal/xpack-file-realm from elastic-internal-xpack-file-realm (ro)
      /usr/share/elasticsearch/config/http-certs from elastic-internal-http-certificates (ro)
      /usr/share/elasticsearch/config/operator from file-settings (ro)
      /usr/share/elasticsearch/config/transport-remote-certs/ from elastic-internal-remote-certificate-authorities (ro)
      /usr/share/elasticsearch/data from elasticsearch-data (rw)
      /usr/share/elasticsearch/logs from elasticsearch-logs (rw)
  elastic-internal-suspend:
    Container ID:
    Image:         docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
      /mnt/elastic-internal/scripts/suspend.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  2Gi
    Requests:
      memory:  2Gi
    Environment:
      POD_IP:                     (v1:status.podIP)
      POD_NAME:                  es-cluster-es-default-0 (v1:metadata.name)
      NODE_NAME:                  (v1:spec.nodeName)
      NAMESPACE:                 monitoring (v1:metadata.namespace)
      PROBE_PASSWORD_PATH:       /mnt/elastic-internal/probe-user/elastic-internal-probe
      PROBE_USERNAME:            elastic-internal-probe
      READINESS_PROBE_PROTOCOL:  https
      HEADLESS_SERVICE_NAME:     es-cluster-es-default
      NSS_SDB_USE_CACHE:         no
    Mounts:
      /mnt/elastic-internal/downward-api from downward-api (ro)
      /mnt/elastic-internal/elasticsearch-config from elastic-internal-elasticsearch-config (ro)
      /mnt/elastic-internal/probe-user from elastic-internal-probe-user (ro)
      /mnt/elastic-internal/scripts from elastic-internal-scripts (ro)
      /mnt/elastic-internal/unicast-hosts from elastic-internal-unicast-hosts (ro)
      /mnt/elastic-internal/xpack-file-realm from elastic-internal-xpack-file-realm (ro)
      /usr/share/elasticsearch/bin from elastic-internal-elasticsearch-bin-local (rw)
      /usr/share/elasticsearch/config from elastic-internal-elasticsearch-config-local (rw)
      /usr/share/elasticsearch/config/http-certs from elastic-internal-http-certificates (ro)
      /usr/share/elasticsearch/config/operator from file-settings (ro)
      /usr/share/elasticsearch/config/transport-certs from elastic-internal-transport-certificates (ro)
      /usr/share/elasticsearch/config/transport-remote-certs/ from elastic-internal-remote-certificate-authorities (ro)
      /usr/share/elasticsearch/data from elasticsearch-data (rw)
      /usr/share/elasticsearch/logs from elasticsearch-logs (rw)
      /usr/share/elasticsearch/plugins from elastic-internal-elasticsearch-plugins-local (rw)
Containers:
  elasticsearch:
    Container ID:
    Image:          docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    Image ID:
    Ports:          9200/TCP, 9300/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  2Gi
    Requests:
      memory:   2Gi
    Readiness:  exec [bash -c /mnt/elastic-internal/scripts/readiness-probe-script.sh] delay=10s timeout=900s period=5s #success=1 #failure=3
    Environment:
      POD_IP:                     (v1:status.podIP)
      POD_NAME:                  es-cluster-es-default-0 (v1:metadata.name)
      NODE_NAME:                  (v1:spec.nodeName)
      NAMESPACE:                 monitoring (v1:metadata.namespace)
      PROBE_PASSWORD_PATH:       /mnt/elastic-internal/probe-user/elastic-internal-probe
      PROBE_USERNAME:            elastic-internal-probe
      READINESS_PROBE_PROTOCOL:  https
      HEADLESS_SERVICE_NAME:     es-cluster-es-default
      NSS_SDB_USE_CACHE:         no
    Mounts:
      /mnt/elastic-internal/downward-api from downward-api (ro)
      /mnt/elastic-internal/elasticsearch-config from elastic-internal-elasticsearch-config (ro)
      /mnt/elastic-internal/probe-user from elastic-internal-probe-user (ro)
      /mnt/elastic-internal/scripts from elastic-internal-scripts (ro)
      /mnt/elastic-internal/unicast-hosts from elastic-internal-unicast-hosts (ro)
      /mnt/elastic-internal/xpack-file-realm from elastic-internal-xpack-file-realm (ro)
      /usr/share/elasticsearch/bin from elastic-internal-elasticsearch-bin-local (rw)
      /usr/share/elasticsearch/config from elastic-internal-elasticsearch-config-local (rw)
      /usr/share/elasticsearch/config/http-certs from elastic-internal-http-certificates (ro)
      /usr/share/elasticsearch/config/operator from file-settings (ro)
      /usr/share/elasticsearch/config/transport-certs from elastic-internal-transport-certificates (ro)
      /usr/share/elasticsearch/config/transport-remote-certs/ from elastic-internal-remote-certificate-authorities (ro)
      /usr/share/elasticsearch/data from elasticsearch-data (rw)
      /usr/share/elasticsearch/logs from elasticsearch-logs (rw)
      /usr/share/elasticsearch/plugins from elastic-internal-elasticsearch-plugins-local (rw)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  elasticsearch-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  elasticsearch-data-es-cluster-es-default-0
    ReadOnly:   false
  downward-api:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
  elastic-internal-elasticsearch-bin-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  elastic-internal-elasticsearch-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-default-es-config
    Optional:    false
  elastic-internal-elasticsearch-config-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  elastic-internal-elasticsearch-plugins-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  elastic-internal-http-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-http-certs-internal
    Optional:    false
  elastic-internal-probe-user:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-internal-users
    Optional:    false
  elastic-internal-remote-certificate-authorities:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-remote-ca
    Optional:    false
  elastic-internal-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      es-cluster-es-scripts
    Optional:  false
  elastic-internal-transport-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-default-es-transport-certs
    Optional:    false
  elastic-internal-unicast-hosts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      es-cluster-es-unicast-hosts
    Optional:  false
  elastic-internal-xpack-file-realm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-xpack-file-realm
    Optional:    false
  elasticsearch-logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  file-settings:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-cluster-es-file-settings
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  4m3s               default-scheduler  Successfully assigned monitoring/es-cluster-es-default-0 to minikube
  Warning  Failed     2m1s               kubelet            Failed to pull image "docker.elastic.co/elasticsearch/elasticsearch:8.7.0": rpc error: code = Unknown desc = context deadline exceeded
  Warning  Failed     2m1s               kubelet            Error: ErrImagePull
  Normal   BackOff    118s (x3 over 2m)  kubelet            Back-off pulling image "docker.elastic.co/elasticsearch/elasticsearch:8.7.0"
  Warning  Failed     118s (x3 over 2m)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    107s (x2 over 4m)  kubelet            Pulling image "docker.elastic.co/elasticsearch/elasticsearch:8.7.0"

**Comment by craigtaverner** [comment]
Hi @Ibrahimogod. This looks like an issue with on-prem ECK, not Elasticsearch, and we have another repository for reporting issues for that at https://github.com/elastic/sdh-control-plane. I recommend you report this issue there.

In the meantime, since this is related to the 8.7.0 release which we made at the end of last week, I've notified the Elasticsearch delivery team in case there were any known issues with releasing the 8.7.0 version to docker.

**Comment by craigtaverner** [comment]
Just as a test, I tried myself, following the instructions at https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html, and it seemed to work. One difference I notice between those instructions and your spec is that the instructions on that page only mention `version 8.7.0` in the spec, and do not specify the `image`, which you have specified above. Perhaps it is worth trying without that explicit `image` line?

**Comment by Ibrahimogod** [comment]
> Just as a test, I tried myself, following the instructions at https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html, and it seemed to work. One difference I notice between those instructions and your spec is that the instructions on that page only mention `version 8.7.0` in the spec, and do not specify the `image`, which you have specified above. Perhaps it is worth trying without that explicit `image` line?

I actually tried with and without specifing the image and I had the same error, but since its ECK related I'll close this issue here and open a new one on the ECK repo
