### ISSUE TITLE
Some missing User Privileges in built-in roles in Kibana

### ISSUE THREAD

**Issue by davidchoi-aus** [elastic/elasticsearch#95000]
There are some missing built-in user roles that can be seen in Kibana.
  
https://www.elastic.co/guide/en/elasticsearch/reference/master/built-in-roles.html#built-in-roles
https://www.elastic.co/guide/en/elasticsearch/reference/8.7/built-in-roles.html#built-in-roles

e.g:
- rollup_user
- transport_user
- rollup_admin

It would great if we could put them into our doc.

**Comment by amyjtechwriter** [comment]
@davidchoi-aus I've created a PR to add `rollup_user` and `rollup_admin` to the docs, but I cannot see `transport_user` listed in my spin up. If you still see it listed in roles please let me know.
