### ISSUE TITLE
Wrong step in documentation for downsampling

### ISSUE THREAD

**Issue by andrei-gutierrez** [elastic/elasticsearch#95017]
### Elasticsearch Version

8.6.2

### Java Version

_bundled_

### OS Version

any

### Problem Description

Documentation manual is having a problem in a step
https://www.elastic.co/guide/en/elasticsearch/reference/8.7/downsampling-manual.html
"
Re-run your search query to view the aggregated time series data.
`GET /sample-01*/_search`
"

### Steps to Reproduce

The search query is a search not an aggregation, the step is either wrong or is missplaced

**Comment by csoulios** [comment]
@andrei-gutierrez thanks for reporting this. You are right, the query should be an agg query requesting the same aggs as in the original index. This is clear from the results shown below in the page.

**Comment by salvatore-campagna** [comment]
I am re-assigning this to the docs team.
