### ISSUE TITLE
LocalGatewayAllocator should fetch node shard info asynchronously and with batches

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#9502]
To assign shards the master needs to reach out to the nodes and get information about what's available on their disks. We do so in the LocalGatewayAllocator, using TransportNodesListGatewayStartedShards . Currently this is done in a blocking fashion on the cluster state update thread on a *per* shard basis. 

Although the information is cached, we can still end up preventing cluster state processing from continuing in a normal fashion. Instead we should move to an async model and try to batch requests, asking nodes for all the shards they have instead of reaching out for every shard we want information about.

**Comment by shikhar** [comment]
> Currently this is done in a blocking fashion on the cluster state update thread on a per shard basis.

I believe this is why the deadlock in #11170 was preventing cluster init.
