### ISSUE TITLE
node left ,then node jonin  again and again 

### ISSUE THREAD

**Issue by loveyang2012** [elastic/elasticsearch#95099]
### Elasticsearch Version

elasticsearch-7.3.1

### Java Version

java version "1.8.0_181"

### OS Version

centos7.7

### Problem Description

I have a cluster for 24 nodes, now i get a problem about the node left and join again and again, i found some logs like this:
![image](https://user-images.githubusercontent.com/24237714/230602642-c3533c7a-a87d-4427-bcd9-63f8911a7638.png)

this is production env, I need help, please...

### Steps to Reproduce

i add some config to es cluster ,like this:
client.transport.ping_timeout: 120s
discovery.zen.fd.ping_timeout: 120s  
discovery.zen.fd.ping_retries: 6  
discovery.zen.fd.ping_interval: 30s 

but it does not work.
![image](https://user-images.githubusercontent.com/24237714/230603165-86185e70-c42e-4d27-b071-e883b0f00688.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 7.3.1 which has passed end-of-life, so I am closing this. If you can reproduce this issue in a supported version then we will reopen it.
