### ISSUE TITLE
Add total_data_set_size_in_bytes to _cat/indices

### ISSUE THREAD

**Issue by henrikno** [elastic/elasticsearch#95092]
### Description

`_cat/indices` does not currently show any size for searchable snapshots

`green  open   partial-.ds-mydatastream-2023.03.01-000579             7yUK80vZTHiqtWjX-q_hWQ   3   0     100047            0         0b             0b`
I couldn't find any extra columns that show this either.

The size of the actual backing index is available by querying stats:
`GET /partial-.ds-mydatastream-2023.03.01-000579/_stats`
```
      "store": {
        "size_in_bytes": 0,
        "total_data_set_size_in_bytes": 40627182,
        "reserved_in_bytes": 0
      },
```

It would be great if this was added as a column so that we can see the size of old indices (e.g. to see if they are increasing in size, how much space we could save if we delete them etc)

**Comment by joegallo** [comment]
++ to this issue, makes a lot of sense to me. I ran into the same need today and was about to file exactly this kind of issue.

Adding some additional detail:

```
GET _cat/indices/tweets*?s=index
yellow open tweets-1 wDapuRt1SdKGCWTPt_terg 1 1 2 0 11kb 11kb
green  open tweets-2 ghYEADbJTkCevkSVSEU05w 1 0 1 0   0b   0b
```

`tweets-2` is a partially mounted searchable snapshot index, and while it does have a size (in some abstract sense), the reported size from `_cat/indices` and `_cat/shards` is `0b`. By way of contrast the number of documents is correctly reported for it (there's just the one).

Running the [Index stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html) for those indices, though, we see:

```
{
  "_shards": {
    "total": 3,
    "successful": 2,
    "failed": 0
  },
  "_all": {
    [...]
  },
  "indices": {
    "tweets-1": {
      "uuid": "wDapuRt1SdKGCWTPt_terg",
      "health": "yellow",
      "status": "open",
      "primaries": {
        "docs": {
          "count": 2,
          "deleted": 0
        },
        "store": {
          "size_in_bytes": 11360,
          "total_data_set_size_in_bytes": 11360,
          "reserved_in_bytes": 0
        }
      },
      "total": {
        "docs": {
          "count": 2,
          "deleted": 0
        },
        "store": {
          "size_in_bytes": 11360,
          "total_data_set_size_in_bytes": 11360,
          "reserved_in_bytes": 0
        }
      }
    },
    "tweets-2": {
      "uuid": "ghYEADbJTkCevkSVSEU05w",
      "health": "green",
      "status": "open",
      "primaries": {
        "docs": {
          "count": 1,
          "deleted": 0
        },
        "store": {
          "size_in_bytes": 0,
          "total_data_set_size_in_bytes": 5541,
          "reserved_in_bytes": 0
        }
      },
      "total": {
        "docs": {
          "count": 1,
          "deleted": 0
        },
        "store": {
          "size_in_bytes": 0,
          "total_data_set_size_in_bytes": 5541,
          "reserved_in_bytes": 0
        }
      }
    }
  }
}
```

So it would be grand if we grew the ability to have `total_data_set_size_in_bytes` reported on the `_cat/indices` and `_cat/shards` APIs. Given that there's an option for there for controlling which columns are displayed, this could be a new column that we support displaying but we could evaluate later/elsewhere whether it's something we want to display by default.

Related, the docs for `_cat/shards` ([link](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-shards.html#cat-shards-query-params)) mention the various columns that are available for the `h` parameter, but the docs for `_cat/indices` do not ([link](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html#cat-shards-query-params)) -- the ideal PR for closing this issue would add `total_data_set_size_in_bytes` to the list of supported columns for `_cat/shards` (and audit that list for completeness!) and then create the missing list for `_cat/indices`.

**Comment by joegallo** [comment]
I haven't looked into the details enough to say, but it's possible that we can only (easily) add this new column to `_cat/indices` and that we couldn't (easily) add it to `_cat/shards`. We should do whatever is easy/straightforward/possible.

**Comment by DaveCTurner** [comment]
I'm pretty sure this is all easy/straightforward/possible:

```diff
diff --git a/server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java b/server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java
index 5d8e5fa3aa70..a068cb0cd11f 100644
--- a/server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java
+++ b/server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java
@@ -170,6 +170,8 @@ public class RestIndicesAction extends AbstractCatAction {
         table.addCell("store.size", "sibling:pri;alias:ss,storeSize;text-align:right;desc:store size of primaries & replicas");
         table.addCell("pri.store.size", "text-align:right;desc:store size of primaries");

+        table.addCell("dataset.size", "default:false,text-align:right;desc:total size of dataset");
+
         table.addCell("completion.size", "sibling:pri;alias:cs,completionSize;default:false;text-align:right;desc:size of completion");
         table.addCell("pri.completion.size", "default:false;text-align:right;desc:size of completion");

@@ -585,6 +587,7 @@ public class RestIndicesAction extends AbstractCatAction {

             table.addCell(totalStats.getStore() == null ? null : totalStats.getStore().size());
             table.addCell(primaryStats.getStore() == null ? null : primaryStats.getStore().size());
+            table.addCell(primaryStats.getStore() == null ? null : primaryStats.getStore().totalDataSetSize());

             table.addCell(totalStats.getCompletion() == null ? null : totalStats.getCompletion().getSize());
             table.addCell(primaryStats.getCompletion() == null ? null : primaryStats.getCompletion().getSize());
diff --git a/server/src/main/java/org/elasticsearch/rest/action/cat/RestShardsAction.java b/server/src/main/java/org/elasticsearch/rest/action/cat/RestShardsAction.java
index 5d79ae51967c..18bb84d85e98 100644
--- a/server/src/main/java/org/elasticsearch/rest/action/cat/RestShardsAction.java
+++ b/server/src/main/java/org/elasticsearch/rest/action/cat/RestShardsAction.java
@@ -116,6 +116,7 @@ public class RestShardsAction extends AbstractCatAction {
             .addCell("state", "default:true;alias:st;desc:shard state")
             .addCell("docs", "alias:d,dc;text-align:right;desc:number of docs in shard")
             .addCell("store", "alias:sto;text-align:right;desc:store size of shard (how much disk it uses)")
+            .addCell("dataset", "default:false;text-align:right;desc:total size of dataset")
             .addCell("ip", "default:true;desc:ip of node where it lives")
             .addCell("id", "default:false;desc:unique id of node where it lives")
             .addCell("node", "default:true;alias:n;desc:name of node where it lives");
@@ -287,6 +288,7 @@ public class RestShardsAction extends AbstractCatAction {
             table.addCell(shard.state());
             table.addCell(getOrNull(commonStats, CommonStats::getDocs, DocsStats::getCount));
             table.addCell(getOrNull(commonStats, CommonStats::getStore, StoreStats::getSize));
+            table.addCell(getOrNull(commonStats, CommonStats::getStore, StoreStats::getTotalDataSetSize));
             if (shard.assignedToNode()) {
                 String ip = state.getState().nodes().get(shard.currentNodeId()).getHostAddress();
                 String nodeId = shard.currentNodeId();
```

(plus tests/docs ofc). I don't see any good reason not to do this. But I would prefer we don't change the default columns: one can argue that changing the default columns is a breaking change, and although _technically_ we can do this according to the disclaimer in the docs it's still something I think we should avoid unless there's a strong need.

**Comment by dakrone** [comment]
Thanks for the quick implementation David!

> But I would prefer we don't change the default columns

I'm on the other side, I'll lay out my reasons. First, this is an additive change, we aren't changing any of the existing columns. A user that relies on specific columns at specific locations (e.g., in a script) should be using the `?h=…` parameter to specify the exact columns in the exact order they're needed. Second, the intent for these APIs is to be user friendly, and arguably a large portion of the cat indices usefulness is seeing the relative size of an index compared to other indices. If we don't add the column, this makes the output in Serverless much less useful, since every index will report `0b`.

I plan to open two PRs, one adding the column as an option, another to include the column by default. That way we don't block adding the column on whether it should be included by default.

**Comment by DaveCTurner** [comment]
> should be using the `?h=…` parameter to specify the exact columns

Ok, you've convinced me 😄
