### ISSUE TITLE
 Add Exact Match option to phrase suggester query

### ISSUE THREAD

**Issue by sujata1993** [elastic/elasticsearch#95157]
### Description

doc in index:
POST myindex_suggester/_doc?refresh=true
{"title": "novel prize"}

search query:
POST myindex_suggester/_search
{
  "suggest": {
    "text" : "novel prize",
    "simple_phrase" : {
      "phrase" : {
        "field" :  "title.trigram",
        "size" :   3,
        "real_word_error_likelihood":1,
        "gram_size":2,
        "direct_generator" : [ {
          "field" :            "title.trigram",
          "suggest_mode" :     "always",
          "min_word_length" :  1
        } ],
        "collate": {
          "query": { 
            "source" : {
              "match": {
                "title" : "{{suggestion}}" 
              }
            }
          },
          "prune": true 
        }
      }
When I am searching with excat correct term in search query , I am getting  result :
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "suggest" : {
    "simple_phrase" : [
      {
        "text" : "novel prize",
        "offset" : 0,
        "length" : 11,
        "options" : [ ]
      }
    ]
  }
}

result is empty!!!!

So, its bit confusing that if it is wrong search which does not have suggestions in index or its is correct search.
It is should return something in result that ,it is correct match to identify this

Need help in this. Its urgent

ES version is 7.17

**Comment by astefan** [comment]
@sujata1993 Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
