### ISSUE TITLE
[monitoring] Customization mechanism for `.monitoring-*` templates

### ISSUE THREAD

**Issue by klacabane** [elastic/elasticsearch#95197]
The index templates defined for monitoring (eg [elasticsearch .monitoring-es-mb](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json)) don't allow an upgrade-proof way of customization. Any updates to the original templates (directly or through an attached component template) would be overridden on stack upgrades (given that the template actually changed). We can clone the template and apply customization on the clone but any updates to the original template applied through upgrades won't be picked up by the clone.

Kibana integration packages solve that by shipping templates with a `@custom` component template attached. This component template is untouched during upgrade so it keeps customization applied.Setting up a similar mechanism for monitoring templates would allow upgrade-compatible customization.

For each monitoring template, a custom component template already attached exists and can be updated by users. The component template with its updates survives stack upgrades.

**Comment by wrathagom** [comment]
Following as I have a customer asking for this.

**Comment by tylerperk** [comment]
Also following as I also am aware of customers who have the same need so their custom Stack Monitoring dashboards don't break on upgrade.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
