### ISSUE TITLE
Terms agg: sort null buckets below numeric buckets

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elasticsearch#95239]
### Summary
When a terms aggregation is sorted by a sub aggregation, null buckets are ranked above the largest number. This is confusing since null feels both smaller and less useful than any numeric value.

### Example
For example, create an index like this

```
POST ordertest/_doc
{
  "key": "A",
  "val": 1
}

POST ordertest/_doc
{
  "key": "B",
  "val": 0
}

POST ordertest/_doc
{
  "key": "B",
  "val": 0
}

POST ordertest/_doc
{
  "key": "B",
  "val": 2
}

POST ordertest/_doc
{
  "key": "C"
}
```

And run this query:
```
POST ordertest/_search
{
  "size": 0, 
  "aggs": {
    "t": {
      "terms": {
        "field": "key.keyword",
        "size": 10,
        "order": {
          "avg": "desc"
        }
      },
      "aggs": {
        "avg": {
          "avg": {
            "field": "val"
          }
        }
      }
    }
  }
}
```

The null bucket `C` is ranked at the top.
```
"buckets": [
        {
          "key": "C",
          "doc_count": 1,
          "avg": {
            "value": null
          }
        },
        {
          "key": "A",
          "doc_count": 1,
          "avg": {
            "value": 1
          }
        },
        {
          "key": "B",
          "doc_count": 3,
          "avg": {
            "value": 0.6666666666666666
          }
        }
      ]
```

**Comment by martijnvg** [comment]
Hey @drewdaemon thanks for opening this issue.
We have discussed this in the past and then we decided not the add support this see: #20237
In this case using missing option on average aggregation can be used as a workaround here: https://www.elastic.co/guide/en/elasticsearch/reference/8.7/search-aggregations-metrics-avg-aggregation.html#_missing_value_6
