### ISSUE TITLE
RangeFilterBuilder doesn't handle one of "from" or "two" being null

### ISSUE THREAD

**Issue by thomas11** [elastic/elasticsearch#9523]
ES range filters allow omitting one of "from", "to". (Actually the docs don't say anything about this but it works in 1.4.3 at least).

RangeFilterBuilder doesn't handle this, though, and emits filters with
"from": "null"
or
"to": "null"

The doXContent method doesn't check the from and to fields for null.

Tested on 1.4.3 but the code is still the same in head: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/query/RangeFilterBuilder.java

**Comment by knoxxs** [comment]
There should be a null check before setting `from` and `to` in the builder.

```java
builder.startObject(name);
if (from != null) {
    builder.field("from", from);
    builder.field("include_lower", includeLower);
}
if (to != null) {
    builder.field("to", to);
    builder.field("include_upper", includeUpper);
}
if (timeZone != null) {
    builder.field("time_zone", timeZone);
}
builder.endObject();
```

@clintongormley is this fine. Should I do it?

**Comment by clintongormley** [comment]
@knoxxs looks good - please go ahead and open a PR (and sign the CLA if you haven't done so already).  Also, would be good to do the same thing for RangeQueryBuilder, and to add tests as well

thanks!

**Comment by knoxxs** [comment]
@clintongormley 
I have changed both the files and wrote some tests, but my tests are behaving weird. Sometimes they run fine sometime they break. For example see the following excerpt of my test
```java
@Test
    public void testRangeQueryWithNullLimits() {
        String indexName = "test";
        String type = "type1";
        createIndex(indexName);

        String doc1 = "{\n" +
                "  \"field\": 1\n" +
                "}";
        String doc2 = "{\n" +
                "  \"field\": 5\n" +
                "}";
        String doc3 = "{\n" +
                "  \"field\": 10\n" +
                "}";
        index(indexName, type, "1", doc1);
        index(indexName, type, "2", doc2);
        index(indexName, type, "3", doc3);

        RangeQueryBuilder rangeQueryBuilder = QueryBuilders.rangeQuery("field");
        rangeQueryBuilder.from(null);
        rangeQueryBuilder.to(5);
        SearchResponse searchResponse = search(rangeQueryBuilder, indexName);
        assertSearchHits(searchResponse, "1", "2");
}
```

The query is 
```json
{
  "range" : {
    "field" : {
      "to" : 5,
      "include_upper" : true
    }
  }
}
```

Sometimes I am getting this response:
```json
{
  "took" : 267,
  "timed_out" : false,
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "type1",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
  "field": 5
}
    }, {
      "_index" : "test",
      "_type" : "type1",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
  "field": 1
}
    } ]
  }
}
```

and sometimes this
```json
{
  "took" : 101,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

I think I am doing some naive mistake. I am not able to understand why this could happen for same code. Can you help?

**Comment by rjernst** [comment]
@knoxxs You will want to do a refresh after indexing the docs, to ensure all are visible.

Try something like this.  I've added comments to explain what some parts are doing.
```
createIndex("test")
ensureGreen("test") // technically only ensureYellow is necessary, to make sure we can start indexing
indexRandom(true, // this flag indicates we should refresh after indexing these docs
            client().prepareIndex("test", "type1", "1").setSource("field", 1),
            client().prepareIndex("test", "type1", "2").setSource("field", 5),
            client().prepareIndex("test", "type1", "3").setSource("field", 10));
```

**Comment by cbuescher** [comment]
In current versions we decided to always render `null` as a valid from/to value, the parser also accepts those. So I think this can be closed.
