### ISSUE TITLE
Query string can be used with multiword synonyms

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#9525]
In http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/multi-word-synonyms.html

"We have tried to avoid discussing the query_string query because we don’t recommend using it."

because

"As part of this parsing process, it (the query_string) breaks up the query string on whitespace, and passes each word that it finds to the relevant analyzer separately. This means that your synonym analyzer will never receive a multiword synonym. Instead of seeing United States as a single string, the analyzer will receive United and States separately."

Though using simple_query_string flags we can specify using a subset of flags not containing the WHITESPACE flag which would effectively overcome the challenge of using query_string with multiword synonyms mentioned in the above documentation.

So perhaps worth rephrasing this to leave the door open to use of simple_query_string when searching using multiword synonyms?

See scenario below

```
DELETE my_index

PUT /my_index
{
  "settings": {
    "analysis": {
      "filter": {
        "my_synonym_filter": {
          "type": "synonym",
          "synonyms": [
            "kerningenieur,ingeniero nuclear,ingegnere nucleare,ingenieur nucleaire=>nuclear engineer"
          ]
        }
      },
      "analyzer": {
        "my_synonyms": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "my_synonym_filter"
          ]
        }
      }
    }
  }
}

PUT my_index/_mapping/job
{
  "properties": {
    "title":{
      "type": "string",
      "analyzer": "my_synonyms"
    }
  }
}


PUT my_index/job/1
{
    "title":"ingenieur nucleaire"
}

POST my_index/_search
{ 
  "query":{
      "simple_query_string" : {
        "query" : "nuclear engineer",
        "analyzer": "my_synonyms",
        "fields": ["title","_all"],
        "flags" : "OR|AND|PREFIX"
    }
  }
}

{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0.07795621,
      "hits": [
         {
            "_index": "my_index",
            "_type": "job",
            "_id": "1",
            "_score": 0.07795621,
            "_source": {
               "title": "ingenieur nucleaire"
            }
         }
      ]
   }
}
```

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-definitive-guide#450
