### ISSUE TITLE
Large search hits can cause an OOM

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#95312]
We should investigate adding a circuit breaker to prevent large search hits from potentially causing an OOM.

**Comment by JinLiu1210** [comment]
1

**Comment by DaveCTurner** [comment]
Relates #67478

**Comment by benwtrent** [comment]
Related also to: https://github.com/elastic/elasticsearch/issues/89656

I think we should close this as duplicate and use the linked issue. What say you @javanna & @jdconrad ?
