### ISSUE TITLE
Expose a API to customize the dynamical mapping rule(type reference), so that we can develop some plugins to support our own business

### ISSUE THREAD

**Issue by pengrongbo** [elastic/elasticsearch#95344]
### Description

Current behavior:
"Elasticsearch" should be categorized as Keyword type but text.

SO can you expose the API to the user to customize the rule for type reference?

**Comment by jbaiera** [comment]
This is something that might be better asked about on the forum, but I'm wondering if you have looked at [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) for mappings?

Either way, this issue isn't really something that is actionable, so I'm going to close it out for now.
