### ISSUE TITLE
TDigest & HdrHistogram fork

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#95355]
### Description

We would like to have our own fork for both the following libraries:
 * TDigest: https://github.com/tdunning/t-digest
 * HdrHistogram https://github.com/HdrHistogram/HdrHistogram

There are two main reasons behind this choice:
1. We would like to control semantic version and backward compatibility according to our definition. Right now, for instance, TDigest does not match our usage of semantic versioning when changing the library code and that makes upgrading quite challenging because exposes us to backward compatibility issues.
2. We would like to change those libraries to use some specific Elasticsearch libraries/tools/frameworks such as BigArrays. Right now when running some aggregations (percentiles, boxplot,...) we experience OOMs due to large memory usage. Using BigArrays, for instance, would allow us to deal with OOMs using Circuit Breakers.

**Comment by wchaparro** [comment]
Should we split this issue? @kkrik-es  @salvatore-campagna @martijnvg

**Comment by martijnvg** [comment]
Closing in favour of #95903 and #95904
