### ISSUE TITLE
Test aggregations on counters and gauges in TSDB Rally track

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#95358]
### Description

Right now the aggregation queries we have in the TSDB Rally track mainly run on fields that are not counters nor gauges.
The only gauge field we aggregate on is `kubernetes.container.memory.usage.bytes`.

Time series indices exist to collect and aggregate metrics. As a result we should increase our coverage when it comes to running aggregation queries on time series indices.
Other tracks (noaa, nyc_taxis) already cover aggregations on non-metric fields (as a result of operating on regular non-time series indices). For this reason we should change TSDB aggregation queries to operate on counters and gauges rather then on labels.

NOTE: probably it would also be useful to have a cardinality aggregation running on a dimension field and on a non-dimension field.

**Comment by wchaparro** [comment]
@salvatore-campagna are we testing functionality or performance?  If both, perhaps we could split this issue into two, one for rally performance (in the rally repo), and then functionality.

**Comment by wchaparro** [comment]
closing per https://github.com/elastic/elasticsearch/issues/95358#issuecomment-1545854387
