### ISSUE TITLE
Example plugin failure  `could not find org.elasticsearch:preallocate:8.8.0-SNAPSHOT`

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#95376]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+periodic+example-plugins/778/

### Repro line

from plugin examples dir: `./gradlew :security-authorization-engine:bundlePlugin`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

This is failing for several example plugins, e.g., `security-authorization-engine` or `stable-analysis`:

```
> Could not resolve all files for configuration ':stable-analysis:yamlRestTestCompileClasspath'.
    > Could not find org.elasticsearch:preallocate:8.8.0-SNAPSHOT.
      Searched in the following locations:
        - https://snapshots.elastic.co/maven/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/maven-metadata.xml
        - https://snapshots.elastic.co/maven/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/preallocate-8.8.0-SNAPSHOT.pom
        - https://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/dcc2154a1d3/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/maven-metadata.xml
        - https://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/dcc2154a1d3/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/preallocate-8.8.0-SNAPSHOT.pom
        - https://repo.maven.apache.org/maven2/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/maven-metadata.xml
        - https://repo.maven.apache.org/maven2/org/elasticsearch/preallocate/8.8.0-SNAPSHOT/preallocate-8.8.0-SNAPSHOT.pom
      Required by:
          project :stable-analysis > org.elasticsearch.test:yaml-rest-runner:8.8.0-SNAPSHOT > org.elasticsearch.test:framework:8.8.0-SNAPSHOT
```

I _think_ this is related to https://github.com/elastic/elasticsearch/pull/94884 (cc @rjernst) -- at least in terms of content and failure history -- PR was merged on the 10th of April and first plugin build failure happened on the 11th, and has been happening since then. Apologies if this is a red herring.

**Comment by mark-vieira** [comment]
Looks like this was added but isn't being published. @breskeby can you get this added to release manager and all that?

**Comment by breskeby** [comment]
I've raised a PR https://github.com/elastic/infra/pull/38898 to fix this by adding preallocate to the published artifacts of our release

**Comment by itizir** [comment]
Hello! Has this been sorted out yet?
Not seeing it in https://repo.maven.apache.org/maven2/org/elasticsearch/ ...

**Comment by mark-vieira** [comment]
> Hello! Has this been sorted out yet? Not seeing it in https://repo.maven.apache.org/maven2/org/elasticsearch/ ...

This was an issue with the 8.8.0 release and those artifacts are not included. Are you running into issues building your plugin against 8.8.0?

**Comment by mark-vieira** [comment]
I've opened a separate issue specifically relating to the 8.8.0 release.

https://github.com/elastic/elasticsearch/issues/96360

**Comment by itizir** [comment]
Yup, indeed trying to build a plugin. Thanks for the workaround suggested in that issue! But indeed tests don't work...

**Comment by alexklibisz** [comment]
Likewise, seeing this issue in a plugin. For now I'm using the workaround suggested above (just exclude the dependency and hope for the best). Would be nice to have it published.
