### ISSUE TITLE
"validate" option for type "geo_point" in mapping is not loading

### ISSUE THREAD

**Issue by obierlaire** [elastic/elasticsearch#9539]
If i create a mapping with geo_point field, other options such as "normalize", "lat_on"... are well loaded. But `"validate": true` or `"validate": false` is removed from the mapping. 
This option is described here:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html#mapping-geo-point-type

I tried the following with elastic search version 1.1.2, 1.3.6, 1.3.7 and 1.4.2:

```
PUT my_index
```
Response: `{"acknowledged": true}`

```
PUT my_index/simple/_mapping
{
  "simple": {
    "properties": {
      "name": {
        "type": "string"
      },
      "location": {
        "type": "geo_point",
        "normalize": false,
        "validate": true
      }
    }
  }
}
```
Response: `{"acknowledged": true}`

```
GET my_index/simple/_mapping
```
Response:
```
{
   "my_index": {
      "mappings": {
         "simple": {
            "properties": {
               "location": {
                  "type": "geo_point",
                  "normalize": false
               },
               "name": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```

As you can see, "validate" option is removed from the mapping!
Same behaviour if you try a bogus field (`"foo": true`).

In the logs:
```
[2015-02-03 12:33:24,343][INFO ][cluster.metadata         ] [Harpy] [my_index] creating index, cause [api], shards [5]/[1], mappings []
[2015-02-03 12:33:25,397][INFO ][cluster.metadata         ] [Harpy] [my_index] create_mapping [simple]
```
Nothing more.

According to the source code and documentation, "validate" is well a valid option. 

I also tried with `validate_lat` and `validate_lon`, and they are removed from the mapping too.

**Comment by clintongormley** [comment]
@obierlaire Out of interest, are you interested in turning on validation or turning it off?

I'm wondering if we should ever accept invalid geopoints?

**Comment by obierlaire** [comment]
I definitely want to not accept invalid geopoint. Currently I have few documents where the geopoint is malformed (array of null) and the entire document is rejected. However, according to the documentation, it should reject the field (and not the document) if I enable validation.

**Comment by RolphH** [comment]
As this "validate" option is deprecated and will be removed, how should we deal invalid values (null, null)? I don't want the document to rejected

**Comment by lauramoraes** [comment]
Any solution for this? I'm in the same situation.

**Comment by clintongormley** [comment]
@nknize other field types have the `ignore_malformed` option - wondering if we should add this to geo points to allow skipping invalid points?
