### ISSUE TITLE
Extract http stats from nodes stats into separate API

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#95391]
### Description

From the nodes stats API, we should extract the `http` stats into their own endpoint. This endpoint can then be non-node-centric, and present a global view of the number of connections, recent clients, etc.

**Comment by dakrone** [comment]
I think those comments about the response body match what I was thinking. For the URL, the problem with `/_stats/<anything>` is that it's already reserved for index stats, so in this case perhaps just introducing a `/_http_stats` would be worthwhile. It's at least worth discussing as a team for the URL part (especially since we may have multiple of these, having a pattern could be useful).

> This has to be available only in the case the cluster is in serverless mode, right?

I think this would be fine for any running case, i.e., both Serverless and Serverful.

**Comment by HiDAl** [comment]
thanks @dakrone !
