### ISSUE TITLE
[GEO] GeoJSON parser doesn't support more than two elements in a position

### ISSUE THREAD

**Issue by clement-tourriere** [elastic/elasticsearch#9540]
GeoJSON specification allows 2 or more elements for a position (x, y [z, ...]).
http://geojson.org/geojson-spec.html#positions

When trying to index a Polygon with coordinates containing more than 2 elements, Elasticsearch throws : 
`org.elasticsearch.ElasticsearchParseException: Invalid number of points in LinearRing (found 2 - must be >= 4)`

Here the gist for a simple test : 
https://gist.github.com/clement-tourriere/aa2abdc94de7d1456c58

**Comment by nknize** [comment]
Thanks for reporting!  While Elasticsearch doesn't spatially index anything beyond 2 dimension (yet) this is indeed a bug.  Will look into throwing a warning that the z position will be ignored.  The other option is to silently ignore it.

**Comment by colings86** [comment]
@nknize I don't think that a warning in the logs is a good solution. The user causes this but putting a warning in logs will not inform the user that something is not right with the request, and even if it did, in many cases the user indexing the document will not have access to the log files. Also, if someone indexes a bulk load of document with extra dimensions they are going to create massive amounts of logs without any knowledge that there is any warnings. Throwing an exception gives the user feedback saying that something is not right. We need a solution here that is obvious to the user. Maybe something like having an option in the mapping to either throw an error on extra dimensions or to ignore them?

**Comment by nknize** [comment]
Fixed in #10539 by silently ignoring values beyond the 2nd dimension.
