### ISSUE TITLE
AsyncActionStep can't move forward

### ISSUE THREAD

**Issue by fudongyingluck** [elastic/elasticsearch#95417]
### Elasticsearch Version

7.10.2

### Java Version

15

### OS Version

debian

### Problem Description

When I test ilm, I got a status where index stale on the {"phase":"delete","action":"delete","name":"delete"}, although the ilm run periodic, the index don't move any.

### Steps to Reproduce

I think It's happened as follow

1. index in the step before {"phase":"delete","action":"delete","name":"delete"}
2. after the the step finish, we try to move to next step, ie. {"phase":"delete","action":"delete","name":"delete"}
3. it commit a task MoveToNextStepUpdateTask, then publish() -> onClusterStateProcessed() -> maybeRunAsyncAction()
4. in maybeRunAsyncAction() it send request to master to delete index, with TimeValue.MAX_VALUE
5. I restart master at this time
6. the callback onFailure can't submit tasks now

### Logs (if relevant)

relate #95140 

although ilm requests execute faster after batch, I think it's still a problem. for example when I delete 20k indices by ilm policy it still took at least 5 mins. If I restart the node, then it will trappped again
![image](https://user-images.githubusercontent.com/30896830/233370520-27c7e362-7eb9-4384-9404-ce25efffa103.png)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 7.10 which has passed end-of-life, so I am closing this. If you can reproduce this issue in a supported version then we will reopen it.
