### ISSUE TITLE
[DOCS] inaccuracy in node stats API -> index_metric -> query_cache docs

### ISSUE THREAD

**Issue by ruibinma21** [elastic/elasticsearch#95510]
Stumbled across some inaccurate language in the docs (node stats API -> index_metric -> query_cache):
[the current doc](https://github.com/elastic/elasticsearch/blob/0ca5dc2eac3804f9542d643cc26239076a4f0d7b/docs/reference/cluster/nodes-stats.asciidoc?plain=1#L680-L687) says:
> `cache_size`::
(integer)
Size, in bytes, of the query cache.

>`cache_count`::
(integer)
Count of queries
in the query cache.

For the first one it looks like the `cache_size` metric is actually a count of cache items instead of "bytes". 

For the second one it's probably not technically wrong but could sound a bit misleading, in that this metric actually includes the evicted cache items, which can hardly be interpreted as from the language "Count of queries in the query cache."

I haven't looked further into the code but from the data I got it seems like these two doc entries are not accurate. Would be nice if someone can confirm and update the docs if need be. Thanks!

**Comment by slobodanadamovic** [comment]
@ruibinma21 Thank you for reporting this. Looking at the code, it seems that:
 
- `cache_size` actually represents a **current** number of cached queries (not bytes)
- `cache_count` represents the number of all queries that have ever been cached - this number is only incremented and used to calculate the number of `evictions` = `cache_count` - `cache_size`
