### ISSUE TITLE
Unbounded (-1 values) queues

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#9553]
I recently saw a user that had set `threadpool.bulk.queue_size: -1`, which is an unbounded/infinite queue length and seems very dangerous to allow.

Is this intended? 
Is this something we should be explicitly denying to ensure Elasticsearch continuity?

eg - https://github.com/elasticsearch/elasticsearch/blob/6f73c93692d8ceeb5e6a9594cf378c568fbba8df/src/main/java/org/elasticsearch/common/util/concurrent/EsExecutors.java#L68

**Comment by bleskes** [comment]
This is tricky. We need unbounded queues for thread pools like GENERIC (and until we change a couple of things, also MANAGEMENT). For the fixed type ones we might get away with removing the -1 (agreed it doesn't buy us anything) but it would not result in more safety - people can still set it to something extremely high. Not sure it's worth the inconsistency. I tend to leave it as is.

**Comment by s1monw** [comment]
I tend to agree with boaz here, I mean we should maybe work towards making the defaults to be bounded in the future and maybe use a new issue to track it?

**Comment by colings86** [comment]
We discussed this in FixItFriday and said that these are expert settings anyway and should only be changed if you know what you are doing. Rejected -1 would not stop people from setting very large values anyway and we need unbounded thread pools for some of the thread pools as well.
