### ISSUE TITLE
[Logs+] Make default logs-*-* pipeline customizable

### ISSUE THREAD

**Issue by felixbarny** [elastic/elasticsearch#95537]
Call out to a missing `@custom` pipeline so that users can add custom processors to the default logs pipeline.

Open questions
* Can we make the custom pipeline specific for a dataset?
* Should this pipeline also be called by integrations?
* Align with https://github.com/elastic/kibana/issues/149484

Relates to https://github.com/elastic/elasticsearch/pull/95481

cc @joshdover @kpollich

**Comment by eyalkoren** [comment]
This issue is currently blocked on https://github.com/elastic/elasticsearch/pull/95782
