### ISSUE TITLE
Trigger a refresh when a shard becomes search active instead of waiting for it.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#95544]
When a shard becomes search active then trigger a refresh instead of waiting for the next scheduled refresh.
The `IndexShard#awaitShardSearchActive(...)` method registers a refresh listener and then often waits for the refresh scheduler to trigger a refresh. By default this is one second. In order to avoid increasing the query time of the Search API, the mentioned method should trigger a refresh instead for waiting it to happen.

As part of this change we also need to disable the refresh scheduler completely. Otherwise we run at risk of running two refreshes next after each other. One triggered from making shard search active and one from the refresh scheduler.

**Comment by salvatore-campagna** [comment]
@martijnvg I understand that testing this requires the ability to wait for a shard to go into "search-idle" state. This way a subsequent search targeting that shard would trigger the activation of the shard and the refresh. Is there a way, other than waiting (30 seconds by default) to put a shard into search idle state?  At least for testing purposes.

**Comment by martijnvg** [comment]
>  Is there a way, other than waiting (30 seconds by default), to put a shard into search idle state?

I think in unit tests `IndexShardTestCase` base class can be used. And I think there it is easier to set a shard into search-idle state.
