### ISSUE TITLE
elasticsearch binds to all interfaces even with network.host commented out

### ISSUE THREAD

**Issue by aliber4079** [elastic/elasticsearch#95646]
### Elasticsearch Version

8.2

### Installed Plugins

na

### Java Version

_bundled_

### OS Version

CentOS Stream release 8

### Problem Description

elasticsearch binds to all interfaces even with network.host commented out

### Steps to Reproduce

start elastic search with network.host commented out
expected result: curl https://public-ip:9200 will fail
actual result: curl https://public-ip:9200 connects to elasticsearch

### Logs (if relevant)

start elastic search with network.host commented out
expected result: curl https://public-ip:9200/ will fail
actual result: curl https://public-ip:9200/ connects to elasticsearch

**Comment by wangzhenhui1992** [comment]
1

**Comment by JinLiu1210** [comment]
1

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
