### ISSUE TITLE
Setting number_of_replicas on a closed index can put it in an unopenable state

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#9566]
From an irc conversation, someone did this:
```bash
curl -XPUT "localhost:9200/my_index/_settings" -d '{
  "index": {
    "number_of_replicas": 0
  }
}'
curl -XPOST "localhost:9200/my_index/_close"
curl -XPUT "localhost:9200/my_index/_settings" -d '{
  "index": {
    "number_of_replicas": 2
  }
}'
curl -XPOST "localhost:9200/my_index/_open"
```
and the index wouldn't open properly.  Setting number_of_replicas back to 0 and then opening the index, and then setting number_of_replicas to 2 fixed the issue.  It'd be nice if setting the number_of_replicas to something that prevents the index from opening wasn't possible.

**Comment by clintongormley** [comment]
Hmm agreed... although I'm not sure how easy it would be to do.  While the index is closed, we don't keep track of where or how many shards there are I believe.

**Comment by nik9000** [comment]
Yeah- I dunno. Maybe its better to just stop all replica count changes on
closed indexes or only allow it with some dangerous=OK flag or something.

Or more documentation but I doubt that's enough.

**Comment by jpountz** [comment]
> Or more documentation but I doubt that's enough.

Not sure how hard it is to fix but agreed that we should document this behaviour until it's fixed.

**Comment by bleskes** [comment]
I tend to say that we should forbid changing these settings while the index is closed as it is not clear what the effect of it would be. I also can't think of a use case where it will be helpful. I briefly looked at the code and it looks easy to add a black list of settings for closed indices.

**Comment by s1monw** [comment]
@bleskes +1 on not allowing to change these settings! Can you open a PR for this? I think the fact that you can do this is actually a bug?
