### ISSUE TITLE
top_metrics aggregation should fail if it contains sub aggregations

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#95663]
top_metrics is a metric aggregation that does not support sub aggregations. Currently if you add sub aggregation they will be silently ignored. Instead it should throw an error reporting it to the user. It is very easy to reproduce by using the example in the docs:

```
POST /test/_bulk?refresh
{"index": {}}
{"s": 1, "m": 3.1415}
{"index": {}}
{"s": 2, "m": 1.0}
{"index": {}}
{"s": 3, "m": 2.71828}

POST /test/_search?filter_path=aggregations
{
  "aggs": {
    "tm": {
      "top_metrics": {
        "metrics": {"field": "m"},
        "sort": {"s": "desc"}
      },
      "aggs": {
        "min": {
          "min": {
            "field": "m"
          }
        }
      }
    }
  }
}
```

**Comment by divinenaman** [comment]
@iverase can I pick this up  ?

**Comment by iverase** [comment]
sure

**Comment by adamgonzo** [comment]
@iverase how would you test this ?

**Comment by iverase** [comment]
I expect that the error will be thrown when building the aggregation, so I expect a test on `TopMetricsAggregationBuilderTests` that tries to create a a top_metrics aggregation with an expected exception.

**Comment by adamgonzo** [comment]
@iverase so then to run the test we would run 

`./gradlew TopMetricsAggregationBuilderTests`

**Comment by sroopsai** [comment]
@adamgonzo No `./gradlew test` will run all the tests.

**Comment by adamgonzo** [comment]
@sroopsai okay I see. So would the best way just be to run that test locally as 

`java [test-file]`

**Comment by Sudo-Aryan** [comment]
As a first time contributor can I pick this up?
