### ISSUE TITLE
Elasticsearch Geo_Point doesn't follow WGS standards for coordinate order 

### ISSUE THREAD

**Issue by kkirsche** [elastic/elasticsearch#9567]
Currently, the [geo_point array](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html#_lat_lon_as_array_5) is in the `[long, lat]` format. 

The World Geodetic System (WGS), a standard for use in cartography, geodesy, and navigation, as well as the International Maritime Organization (IMO) and the International Civil Aviation Organization (ICAO) recommend to write `[lat, long]`.

Is there any reason Elasticsearch doesn't follow the recommended standards for coordinate pairs?

**Comment by dadoonet** [comment]
It's explained here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html#_lat_lon_as_array_5

Hope this helps.
Closing.

**Comment by kkirsche** [comment]
Thanks for the clarification about that as it is specifically attempting to conform to GeoJSON. I'm sorry to have opened the issue, I had missed that. It's just hard that Elasticsearch isn't consistent in it's implementation throughout the application as to this order. E.g. strings are lat, long, arrays are long, lat, etc.

Either way, thank you though.

**Comment by dadoonet** [comment]
Yeah. That's why I prefer using this notation: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html#_lat_lon_as_properties_5

**Comment by clintongormley** [comment]
Wondering if we should fix this in 2.0.  It'd break existing indices, but possibly we could support a bwc per-index setting? 

Either way it'd be pretty nasty... @nknize thoughts?

**Comment by nknize** [comment]
We had a discussion about this (some of it is available at: https://github.com/elasticsearch/elasticsearch/pull/9339/files#r23233769 )  tldc (too lazy didn't click); it was left as is to avoid breaking existing user integration. 

I like the idea of fixing this in 2.0 and having a a per-index bwc setting.

**Comment by dakrone** [comment]
@nknize ping again about this and whether it's something we want to investigate for 6.0?

**Comment by nknize** [comment]
Closing this issue...again. Its a never ending debate with the standards committees so there is no problem us sticking with the way it is. Also, since adding WKT (which specifies X, Y) order I'd rather stick with arrays complying with this order than adding a bunch of code to handle projection specific ordering.

**Comment by kkirsche** [comment]
To each their own. I still feel that the whole point of specifications is to follow them. This just causes more work for the users of your tools to normalize data when standards and projects do not adhere to them
