### ISSUE TITLE
ReadOnly user can create role and user with "Write" permission 

### ISSUE THREAD

**Issue by RaanaRostampour** [elastic/elasticsearch#95691]
### Elasticsearch Version

7.14.0

### Installed Plugins

xpack

### Java Version

java-8-openjdk-amd64

### OS Version

4.15.0-124-generic

### Problem Description

I created an index and a role to have read-only privileges to this index. then I created a user to have this role. I expected this user couldn't have access to writing a role with "Write" permission on the same index and created a user to be in that role. but it can. and that's dangerous. 

### Steps to Reproduce

1. curl -XPOST 'http://localhost:9200/_xpack/security/role/test_readonly_role' -H 'Content-Type: application/json' -d'{"cluster":["all"], "indices":[{"names":[ "test_index" ],"privileges":["read"]}]}'

2. curl -XPOST  "http://localhost:9200/_security/user/zombe?pretty" -H 'Content-Type: application/json' -d' { "password" : "mypassword", "roles" : [ "test_readonly_role" ], "full_name" : "zombe", "email" : "zombe@example.com" }'
3. curl -XPOST --user zombe:mypassword "http://localhost:9200/_xpack/security/role/write_role' -H 'Content-Type: application/json' -d'{"cluster":["all"], "indices":[{"names":[ "test_index" ],"privileges":["write"]}]}'
4. curl -XPOST  "http://localhost:9200/_security/user/hacker?pretty" -H 'Content-Type: application/json' -d' { "password" : "mypassword", "roles" : [ "write_role" ], "full_name" : "hacker", "email" : "hacker@example.com" }'

and zombe with hacker user can write on index now.

**Comment by ywangd** [comment]
Thanks very much for your interest in Elasticsearch.

This behaviour is expected because your `test_readonly_role` has the `all` cluster privilege. As [documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html#privileges-list-cluster), this cluster privilege allows
> All cluster administration operations, like snapshotting, node shutdown/restart, settings update, rerouting, or **managing users and roles**.  

For the role to be "truly" read-only, you need to drop the cluster privilege, i.e.:

> curl -XPOST 'http://localhost:9200/_xpack/security/role/test_readonly_role' -H 'Content-Type: application/json' -d'{"indices":[{"names":[ "test_index" ],"privileges":["read"]}]}'

As such, I hope you don't mind that I close this issue.

**Comment by RaanaRostampour** [comment]
thank you so much for answering.
I supposed that  "cluster: all " means I want this role on all distances in the cluster.
