### ISSUE TITLE
Phrase Suggester, Term suggester documentation: typo (shards_size -> shard_size)

### ISSUE THREAD

**Issue by vladr** [elastic/elasticsearch#95692]
### Elasticsearch Version

7.17.5

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

In the [Phrase Suggester docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters.html#phrase-suggester),

> A factor that is used to multiply with the `shards_size` in order to...

...should be:

> A factor that is used to multiply with the `shard_size` in order to...

There is no `shards_size` (plural) option.

The same issue also occurs in the [Term Suggester section](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters.html#term-suggester).

### Steps to Reproduce

https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters.html#_other_term_suggest_options

**Comment by abdonpijpelink** [comment]
Thank you for reporting this @vladr ! This has been fixed in https://github.com/elastic/elasticsearch/pull/95696
