### ISSUE TITLE
Get missing aggregation to work for nested documents

### ISSUE THREAD

**Issue by mal** [elastic/elasticsearch#9571]
Currently the `missing` aggreation doesn't work for nested documents (v1.4.2). It would be nice to have a simple way to count all the top level documents that do not have any nested documents within a specific key.

For example (in a school setting) to find all pupils with no detentions. Where detentions is a key of student (if it exists at all), containing a 0-n length array of nested documents describing the date, duration and reason for each detention.

**Comment by martijnvg** [comment]
+1 this would be helpful. I think we can detect this by seeing how many Lucene docs are between the current and previous root (top level) document. If this is equal to 0 then there are no inner nested objects and a value > 0 indicates that there're inner nested objects.

**Comment by clintongormley** [comment]
We have decided to deprecate the `missing` filter instead: https://github.com/elastic/elasticsearch/issues/14112

**Comment by mal** [comment]
@clintongormley this issue was aimed at the aggregation side of things. Is the `missing` aggregation also being deprecated? Is there a good way to achieve the desired result if it turns out that there'll be no `exists`, `missing` or `not` aggregations?

**Comment by clintongormley** [comment]
Ah whoops... too hasty.  However, it is a symptom of the same problem.  I'll reopen

**Comment by neilime** [comment]
Hi,

I have the same issue, please will it be fixed ?

An example to reproduce the issue : 

Mapping :
```json
POST /mli_test2 {
   "mappings": {
      "participations": {
         "properties": {
            "participationProducts": {
               "type": "nested",
               "properties": {
                  "label": {
                     "type": "string"
                  },
                  "quantity": {
                     "type": "long"
                  }
               }
            }
         }
      }
   }
}
```

Data :

```json
POST /mli_test2/participations/1
{
   "number": "xxxx"
}

POST /mli_test2/participations/2
{
   "participationProducts": [
      {
         "label": "TEST_LABEL",
         "quantity": 1
      }
   ],
   "number": "xxxx"
}

POST /mli_test2/participations/3
{
   "participationProducts": [
      {
         "label": "TEST_LABEL",
         "quantity": 1
      }
   ]
}

POST /mli_test2/participations/4
{
   "number": "xxxx"
}
POST /mli_test2/participations/5
{
   "number": "xxxx"
}
```

Elasticsearch query :

```json
POST /mli_test2/participations/_search?search_type=count
{
   "aggs": {
      "participationProducts_agg": {
         "nested": {
            "path": "participationProducts"
         },
         "aggs": {
            "participationProducts_empty_agg": {
               "missing": {
                  "field": "participationProducts"
               }
            },
            "label_agg": {
               "terms": {
                  "field": "participationProducts.label"
               },
               "aggs": {
                  "participationProducts_agg": {
                     "sum": {
                        "field": "participationProducts.quantity"
                     }
                  }
               }
            }
         }
      },
      "number_agg": {
         "terms": {
            "size": 1000,
            "field": "number"
         }
      },
      "number_empty_agg": {
         "missing": {
            "field": "number"
         }
      }
   }
}
```

What we expect to retrieve from elasticsearch response : 

* number = xxxx                                      => 4        (participations 1,2,4,5)
* number_empty                                     => 1        (participation 3)
* participationProducts = TEST_LABEL    => 2        (participations 2,3)
* participationProducts_empty                => 3        (participations 1,4,5)

But here is the result : 

* number = xxxx                                        => 4        OK
* number_empty                                       => 1        OK
* participationProducts = TEST_LABEL      => 2        OK
* participationProducts_empty                  => 3        **_KO_**

Thank you for your help

**Comment by dam0vm3nt** [comment]
Hello any news on this ? workaround ?

My use case is that I'm counting on documents aggregated by a nested field that can be missing, but  I need to know also how many of them miss that field.

**Comment by dam0vm3nt** [comment]
I've resolved by indexing an extra field used only for aggregation that is not nested and using the normal "missing". In case this may help.

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by oeph** [comment]
Are there any news on this?

**Comment by leandrohlsilva** [comment]
Hello guys, any updates on this?

**Comment by dannyrscott** [comment]
Is this being worked on at all? Is there an alternate solution?

**Comment by imotov** [comment]
> Is this being worked on at all? Is there an alternate solution?

As far as I know nobody is working on this at the moment. A workaround would be to use a filter aggregation with the `nested` query wrapped into the `must_not` clause of the `bool` query. Here is how it would look in @neilime's example updated to work on v7.x: 

```
PUT mli_test2
{
  "mappings": {
    "properties": {
      "participationProducts": {
        "type": "nested",
        "properties": {
          "label": {
            "type": "keyword"
          },
          "quantity": {
            "type": "long"
          }
        }
      },
      "number": {
        "type": "keyword"
      }
    }
  }
}

POST mli_test2/_doc/1
{
   "number": "xxxx"
}

POST mli_test2/_doc/2
{
   "participationProducts": [
      {
         "label": "TEST_LABEL",
         "quantity": 1
      }
   ],
   "number": "xxxx"
}

POST mli_test2/_doc/3
{
   "participationProducts": [
      {
         "label": "TEST_LABEL",
         "quantity": 1
      }
   ]
}

POST mli_test2/_doc/4
{
   "number": "xxxx"
}

POST mli_test2/_doc/5
{
   "number": "xxxx"
}


POST mli_test2/_search
{
  "size": 0,
  "aggs": {
    "participationProducts_agg": {
      "nested": {
        "path": "participationProducts"
      },
      "aggs": {
        "label_agg": {
          "terms": {
            "field": "participationProducts.label"
          },
          "aggs": {
            "participationProducts_agg": {
              "sum": {
                "field": "participationProducts.quantity"
              }
            }
          }
        }
      }
    },
    "number_agg": {
      "terms": {
        "size": 1000,
        "field": "number"
      }
    },
    "number_empty_agg": {
      "missing": {
        "field": "number"
      }
    },
    "missing_nested_agg": {
      "filter": {
        "bool": {
          "must_not": {
            "nested": {
              "query": {
                "match_all": {}
              },
              "path": "participationProducts"
            }
          }
        }
      }
    }
  }
}
```

**Comment by wchaparro** [comment]
Discussed as team, something we want to do, so added to the enhancement list. Also, we should open an issue to address the response message.

**Comment by wchaparro** [comment]
closing as not planned, focus is on ES|QL development
