### ISSUE TITLE
Improve MatchNoDocsQuery description

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#95741]
### Description

Our MatchNoneQueryBuilder currently creates Lucene MatchNoDocsQuery with a not-so useful reason description ("User requested  "match_none" query").
This doesn't tell us much about the origin of this query builder, since we often use it in the rewrite stage to rewrite other query parts to.
As an enhancement we could extend that little decription part which e.g. is printed in the "explain" output of a query to include some additional information, for example for the case of rewriting, what the original query was etc...

**Comment by alexgorunescu97** [comment]
I would like to work on this, but I would need some guidance since this would be my first contribution. What additional information needs to be included and how can this information be accessed? Is the info available on the `SearchExecutionContext` passed to this method inside `MatchNoneQueryBuilder`?
https://github.com/alexgorunescu97/elasticsearch/blob/a876ee61f391bf3e94c6d21ce3d6947481a150e2/server/src/main/java/org/elasticsearch/index/query/MatchNoneQueryBuilder.java#L82-L85

**Comment by javanna** [comment]
Thanks @alexgorunescu97 ! The idea would be to look at all the places where we internally create a `MatchNoneQueryBuilder` and provide a more meaningful reason of what led ES to rewrite the query to match none. I would think that including the name of the original builder that rewrites to match none would be a good starting point.

**Comment by alexgorunescu97** [comment]
I did a little bit of debugging and I see that the rewriting process goes through the `toQuery` method that has the original query builder as a parameter in the `SearchExecutionContext` class https://github.com/elastic/elasticsearch/blob/0c8bb467675430b95cb602716562b0990f2cab70/server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java#L557-L569

I was thinking that maybe we could have a new field in the `SearchExecutionContext` class that would hold the original query builder and set it in the above mentioned method. And then use it when building the description for the `MatchNoneQueryBuilder`. This way I think we only have to make changes in only a couple of places. What do you think about this?

**Comment by javanna** [comment]
I am not too sure about such a generic approach that adds complexity to `SearchExecutionContext`. That requires an `instanceof` check also, I think. I was under the impression that we could add this info to all places where the rewrite method rewrites to `MatchNoneQueryBuilder`, manually.

**Comment by alexgorunescu97** [comment]
@javanna I've opened a pull request for this issue. Could you please have a look when you have some time? Thanks
