### ISSUE TITLE
[CI Failure] SearchWithRandomExceptionsTests.testRandomDirectoryIOExceptions

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#9577]
http://build-us-00.elasticsearch.org/job/es_core_master_centos/2884/testReport/junit/org.elasticsearch.search.basic/SearchWithRandomExceptionsTests/testRandomDirectoryIOExceptions/

Error Message:

failed to process cluster event (delete-index [test]) within 30s

Reproduces with:

mvn clean test -Dtests.seed=FBB4EC8352AFE950 -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomExceptionsTests -Dtests.method="testRandomDirectoryIOExceptions" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=792m -Dtests.jvm.argline="-server -XX:+UseSerialGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=ar_YE -Dtests.timezone=Asia/Kuwait -Dtests.processors=4

**Comment by bleskes** [comment]
closing this for now. We have had field data cache clearing issues , which haven't failed in a while and fsync was taking a long time. It's not 100% clear that these are the cause for this issue, but this ticket has run stale. We can re-open if it fails again.
