### ISSUE TITLE
Searching a filtered and a non-filtered data stream alias filters the result

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#95786]
### Elasticsearch Version

8.x

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

Searching a filtered and a non-filtered data stream alias that both point to the same datastream currently filter the result set 
(relevant [code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L714)  )

The desired behaviour is to **not** consider the filter in this case and return the (wider) un-filtered result.

(the desired behaviour for data stream aliases currently exists for indices aliases - relevant code that abandons applying the filter for _index aliases_ is [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L743) )

### Steps to Reproduce

```
PUT _index_template/datastream-template
{
  "index_patterns": [
    "my-datastream"
  ],
  "data_stream": {
  }, 
  "template": {
    "aliases": {
      "first_alias": {
        "filter": {
          "term": {
            "message": "first"
          }
        }
      },
      "second_alias": {}
    }
  },
  "composed_of": []
}



POST my-datastream/_doc
{
  "message":"first",
  "@timestamp":"2023-05-02T08:02:40.420Z"
}


POST my-datastream/_doc
{
  "message":"second",
  "@timestamp":"2023-05-02T08:02:40.420Z"
}

GET first_alias,second_alias/_search
```

The `GET first_alias,second_alias/_search` call only returns one hit, while it should return 2.

**Comment by javanna** [comment]
An alias can be seen as a logical view over an index. The fact that two aliases point to the same index is not necessarily known to users searching against them, and can be seen as an implementation detail. If `alias1` has no filters and has visibility over the whole index, while `alias2` has a filter associated to it that restricts the amount of documents that it exposes, searching both aliases should return all documents that belong to the index and not apply the filter. I understand that this is already case for indices backed aliases, but not for aliases that point to data streams, which I think means this is a bug on how aliases that point to data streams are expanded to their concrete indices and filters.
