### ISSUE TITLE
Get _source fails if original document is not JSON

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9579]
Index a document in YAML:

    curl -X PUT localhost:9200/test/test/1 -d '---
        text:  bar
    '

Retrieve the document:

    GET /test/test/1

Returns:

    {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_version" : 1,
      "found" : true,
      "_source" : {
        "text" : "bar"
      }
    }

But get-source:

    GET /test/test/1/_source
    
Fails with:

    EmitterException[expected NodeEvent, but got <org.elasticsearch.common.jackson.dataformat.yaml.snakeyaml.events.DocumentEndEvent()>]

**Comment by brwr** [comment]
Hey :smile: 

I'm new to Elasticsearch, but I'd like to give this a shot if someone can point me in the right direction. Is [RestGetSourceAction.java](https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/rest/action/get/RestGetSourceAction.java) a good place to start?

**Comment by javanna** [comment]
Hi @brwr it would be fantastic if you can have a look at it, sorry it took a while to get back to you. `RestGetSourceAction` seems exactly where things go wrong trying to print out the yaml document. Let me know if you have any other question.

**Comment by tlrx** [comment]
I think this one is fixed on 5.0.0-alpha5:

```
GET /test/test/1/_source
---
text: "bar"

```
