### ISSUE TITLE
Several DRA job build failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#95823]
### CI Link

https://gradle-enterprise.elastic.co/s/c4ck3salv5yqw

### Repro line

-

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

This job doesn't seem happy since early this morning:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+dra-snapshot/

Several other DRA jobs seem to have similar problem that looks like there is a file missing after the recent version bump.

https://elasticsearch-ci.elastic.co/view/Elasticsearch%20main/job/elastic+elasticsearch+main+dra-snapshot/
https://elasticsearch-ci.elastic.co/view/Elasticsearch%208.7/job/elastic+elasticsearch+8.7+dra-staging/
https://elasticsearch-ci.elastic.co/view/Elasticsearch%208.7/job/elastic+elasticsearch+8.8+dra-staging/

and probably a few others. 

This is the error from "main":
```
Some problems were found with the configuration of task ':checksumElasticsearchSnapshotSHA1' (type 'DefaultTask').
  - Property '$101' specifies file '/artifacts/plugins-files/build/distributions/analysis-icu-8.9.0-SNAPSHOT.zip' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
```

**Comment by mark-vieira** [comment]
This was an infra issue with the release manager which has been resolved.
