### ISSUE TITLE
ES crash on OpenVZ 

### ISSUE THREAD

**Issue by shastox** [elastic/elasticsearch#9582]
Server: VPS, OpenVZ, 32G RAM (~20 free), 50GB free disk space.
DB: ~ 1 million documents.
Proccess "elasticsearch" disappears during 5-60 minutes after ES start.

Log: /var/log/elasticsearch
There are many rows: "..failed to reconnect to node ... Caused by: java.net.ConnectException: Connection refused...", but this is no reason of crashing.

/etc/default/elasticsearch: ES_HEAP_SIZE=4g 
/var/elasticsearch/logging.yml: es.logger.level: DEBUG

Restarting ElasticSearch:
/etc/init.d/elasticsearch restart
[ ok ] Stopping Elasticsearch Server: Elasticsearch Server is not running but pid file exists, cleaning up.
[....] Starting Elasticsearch Server:sysctl: permission denied on key 'vm.max_map_count'

Please help find a reason of crashing.

**Comment by tlrx** [comment]
It looks like there are 2 things:

The connection refused exception indicates that a node cannot connect to another node. This usually happen when 1) the configuration is wrong (check again the configuration, specially multicast/unicast settings), or 2) the other node is running but not reachable (check anything that can block communication between the nodes, usually a firewall rule) or 3) the node is down (not started, or crashed... log messages and stacktrace can help here).

The second thing is the `permission denied` that has been reported before : https://github.com/elasticsearch/elasticsearch/issues/4978

Can you check if the file `/proc/sys/vm/max_map_count` exists please?

**Comment by clintongormley** [comment]
@shastox Any more info here?

**Comment by shastox** [comment]
Sorry.

ALL configuration is default, becide of:

/etc/default/elasticsearch: ES_HEAP_SIZE=4g
/var/elasticsearch/logging.yml: es.logger.level: DEBUG

There are no nodes.

ES works ~20 days withouth crashing, but yesterday it down every 5-10mins. This problem is in few diffrent servers. 

/proc/sys/vm/max_map_count - exists: 65530

**Comment by adamcstephens** [comment]
I've been experiencing this same issue on CentOS on top of Virtuozzo (Parallels openvz). I debugged this for a few days before giving up and moving the ES cluster to KVM.

Something has changed, either in the VZ or ES stack, or both, to cause this to no longer be stable. We ran this configuration for 10 months before it started crashing consistently but at a random runtime.

I have a dev system, and control of the VZ stack if there are any suggested troubleshooting steps.

**Comment by shastox** [comment]
Thank you,  adamcstephens. The problem is, but the reasons are not clear.

**Comment by dwerder** [comment]
This ticket should be renamed to "ES crash on OpenVZ"

It also discused in anouter Ticket at OpenVZ:

https://bugzilla.openvz.org/show_bug.cgi?id=3187

And also at https://github.com/elastic/elasticsearch/issues/4978

The crash has something to do with OpenVZ Kernel newer vzkernel-2.6.32-042stab100 and ploop.

**Quickfix**: dont use ploop (instead use simfs)

**Comment by VasilyAverin** [comment]
Dear ElasticSearch developers,
I'm OpenVZ kernel developer, I'm investigate OpenVZ bug 3187 and would like to share results.
1) we got a number reports from different users, all complains on crash of ElasticSearch application inside  OpenVZ container. We have reproducer, on my test node it crashes ES in ~45 minutes after start.
2) We have collected few core dumps, java crashes in few different places, obviously because of memory corruption.
3) max_map_count sysctl is not related to this problem. This setting can be adjusted from host but issue is still reproduces after this change.
4) Obviously the problem was somehow triggered by some changes in our kernel,
however at the moment we can neither confirm kernel problem nor exclude it.

We need your assistance to clarify the reason of this problem.
Could you please explain which information you need for investigation?
I can provide you lot of hs_err_pidXXX.log files and few core dumps.
Could you please advise some way to troubleshoot memory corruption problems in java?
Please let me know if you cannot reproduce the problem locally but want to get an access to affected environment.

Thank you,
      Vasily Averin

**Comment by adamcstephens** [comment]
@dwerder We experienced this with simfs and not ploop, so that may not be a fix.

**Comment by spinscale** [comment]
@VasilyAverin hey, how can we help you best? Take a look at the core dumps? Feel free to share them. If you want, just contact me a FIRSTNAME.LASTNAME@elastic.co (just check my profile for my full name) and I'll try to take a look at them or find another Elasticsearch developer

**Comment by VasilyAverin** [comment]
@spinscale 
Please take look at http://fe.parallels.com/c8fdcd56b823534a938983e64604e815/
I've uploaded hs_err* log files and started core dumps uploading, it will be finished in few hours.
I would like to know what do you think about possible reasons of this problem.
As kernel developer, I see that crashes are caused by incorrect data, but I can say nothing about nature of this corruptions and do not understand how it can be related to kernel.
At the moment looks like userspace problem for me, but I cannot explain why this happen inside our containers only, and why other environments are not affected.

Also for our customers it would like to know how its possible to workaround this problem.
It would be great if you could advise them something.

**Comment by tatsushid** [comment]
Hi guys, I'm also investigating the issue and I believe I found the one of the cause of it in sigar library.

Today, I saw odd `open` system calls from elasticsearch like

```
/root/debug_data2/syscalls.8009:11:17:54.450233 read(42, "/dev/ploop50957p1 / ext4 rw,relatime,barrier=1,data=ordered,balloon_ino=12 0 0\nproc /proc proc rw,relatime 0 0\nsysfs /sys sysfs rw,relatime 0 0\nnone /dev devtmpfs rw,relatime,size=131072k,nr_inodes=32768,mode=755 0 0\nnone /dev/pts devpts rw,relatime,gid=5,"..., 1024) = 405
/root/debug_data2/syscalls.8009:11:17:54.459160 read(42, "/dev/ploop50957p1 / ext4 rw,relatime,barrier=1,data=ordered,balloon_ino=12 0 0\nproc /proc proc rw,relatime 0 0\nsysfs /sys sysfs rw,relatime 0 0\nnone /dev devtmpfs rw,relatime,size=131072k,nr_inodes=32768,mode=755 0 0\nnone /dev/pts devpts rw,relatime,gid=5,"..., 1024) = 405
/root/debug_data2/syscalls.8009:11:17:54.459632 open("/sys/block/ploop/ploop50957/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:18:35.476467 open("/sys/block/ploop/ploop0/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:19:05.461589 open("/sys/block/ploop/ploop957/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:19:35.463044 open("/sys/block/ploop/ploop57/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:20:05.466241 open("/sys/block/ploop/ploop7/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:20:35.467345 open("/sys/block/ploop/ploop1/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
/root/debug_data2/syscalls.8128:11:21:05.470296 open("/sys/block/ploop/ploop0/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
```

It seems the path name is corrupted gradually. This is processed at https://github.com/hyperic/sigar/blob/master/src/os/linux/linux_sigar.c#L1180 and I think the following has something wrong.

```C
while (!sigar_isdigit(*fsdev)) {
    fsdev++;
}

partition = strtoul(fsdev, NULL, 0);
*fsdev = '\0';
```

For example, if the device name is `ploop50957`, it works but replaces `5` by NULL. The `fsdev` value originates `sigar_iodev_get` function but it keeps the value in a cache so the replaced value is used next time. The second time, it tries to find no number chars but ignores the NULL value set previously (`sigar_isdigit` returns false if the value is NULL char) so this time `0` value is replaced by NULL. It replaces memory by NULL time and time again and finally causes a crash

**Comment by tlrx** [comment]
@tatsushid awesome, thanks! According your explanation it seems you found the source of this issue :)

Do you think you can create an issue for the Sigar lib and link it here?

**Comment by tatsushid** [comment]
@tlrx OK, I'll create an issue for Sigar project

**Comment by VasilyAverin** [comment]
Dear Tatsushi,
thank you very much.
I believe this bug can happen inside simfs containers too,
according device file does not have partition number in end of name.
ct # ls /dev/simfs  -al
b-----x--- 1 root root 0, 24 May 14 10:51 /dev/simfs

On old openVZ kernels containers had no /sys/block directory.
When it was added on new kernels Sigar library was switched to using of IOSTAT_SYS handler
that calls incorrect get_iostat_sys() function.
https://github.com/hyperic/sigar/blob/189843858ecd8da7fb94a6b274269877c2416b3a/src/os/linux/linux_sigar.c#L188

 else if (stat(SYS_BLOCK, &sb) == 0) {
        (*sigar)->iostat = IOSTAT_SYS;

**Comment by spinscale** [comment]
thank you so much for digging into this @tatsushid

@VasilyAverin you can test the assumption, by starting an elasticsearch instance, but remove the `lib/sigar` directory before running. This will disable almost all your monitoring capabilities, but should be sufficient to find out if the crashes keep happening.

**Comment by VasilyAverin** [comment]
@spinscale thank you for hint.
To workaround the problem I've "removed" /sys/block in my test container,
Seems it helps, ES testcases worked stable and was not crashed.
But your workaround is more simple, I'll advise it to affected OpenVZ users.

**Comment by nonotest** [comment]
hello,
im sorry im not sure I understand what you mean by " by starting an elasticsearch instance, but remove the lib/sigar directory before running" @spinscale 
do I start the service and just rename the folder right after?

Thanks,

**Comment by spinscale** [comment]
sorry for not being. You need to remove (or move out it out of the `lib` directory) the directory first and then start, and then start elasticsearch.

Again this will remove a lot of monitoring capabilities and should be considered a workaround, a temporary one! I will monitor the sigar issue and hope someone works on it.

**Comment by nonotest** [comment]
thanks!

**Comment by s1monw** [comment]
I closed this issue since I just added a setting to disable `sigar` loading altogether so on openVZ you can just set this setting instead of removing libraries.

**Comment by citronbleuv** [comment]
Hi, I try on a LXC VM to add " bootstrap.sigar: true " in elasticsearch.yml and restart the service but I have always the same problem. I use to install Elasticsearch 1.6.0 (deb).

What's is my error ?
