### ISSUE TITLE
Compilation failure with JDK 20

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#95839]
### Description

ElasticSearch compilation is failing when using jdk 20. The failure is caused by number of (new?) `warning: [lossy-conversions] implicit cast from long to int in compound assignment is possibly lossy` emitted by the compiler that are not supressed/permitted.

This could be reproduced when using:
```
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```
and running
```
./gradlew compileJava
```

**Comment by mark-vieira** [comment]
Looks like the Java 20 compiler is picking up on potential lossy conversions when doing compound assignment using bitwise operations. We might have to put in some suppressions here.
