### ISSUE TITLE
Normalise case for boolean settings

### ISSUE THREAD

**Issue by moos3** [elastic/elasticsearch#9589]
So if you put in the elasticsearch.yml file True or False with capitals, it will fail to start or load the configuration and throw a error in the logs. 

```
- ElasticsearchIllegalArgumentException[value cannot be parsed to boolean [ true/1/on/yes OR false/0/off/no ]  ]
```
It should be able to accept both lower case and upper case for True or False as most scripting languages will default to True if you put in true or False for false. I noticed this with python scripts for generating the configuration files. Work around for python is to wrap them in single quotes and convert it from boolean to a string.

**Comment by clintongormley** [comment]
Looks like "most scripting languages" is really "python" :)

But that's fine, we could extend boolean settings to normalise case.

**Comment by walro** [comment]
This was a problem for me as well, on version 1.3.8. However it seems like `marvel.agent.enabled: False` was completely ignored, causing the agent to in fact be enabled which was not so desirable.

**Comment by clintongormley** [comment]
Closing in favour of #6732
