### ISSUE TITLE
Using IK analyzer makes N and avgdl different when check the result's explain after searching.

### ISSUE THREAD

**Issue by tyzhong** [elastic/elasticsearch#95929]
### Elasticsearch Version

8.3.1

### Installed Plugins

ik 

### Java Version

1.8

### OS Version

elasticsearch operate on Centos 7

### Problem Description

My data mapping is
{
  "testz_keyword3": {
    "mappings": {
      "properties": {
        "RelatedIssuesList": {
          "type": "object"
        },
        "answer": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart"
        },
        "firstLevelDirectory": {
          "type": "text"
        },
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "keyword": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart"
        },
        "modelId": {
          "type": "keyword"
        },
        "question": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart"
        },
        "relatedIssuesList": {
          "properties": {
            "id": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "issue": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "secondLevelDirectory": {
          "type": "text"
        },
        "thirdLevelDirectory": {
          "type": "text"
        },
        "updateTime": {
          "type": "text"
        }
      }
    }
  }
}
total data number is 
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 2,
    "successful": 2,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 3242,
      "relation": "eq"

search request is :
GET testz_keyword3/_search?explain=true
{
  "query": {
    "bool": {
      "must": [
        {"match": {
          "modelId": "1"
        }},
        {
          "match": {
            "question": "A股开户条件"
          }
        }
        
      ]
    }
  }
}

get the hightest reault:
"_explanation": {
          "value": 8.400638,
          "description": "sum of:",
          "details": [
            {
              "value": 0.00031831927,
              "description": "weight(modelId:1 in 1099) [PerFieldSimilarity], result of:",
              "details": [
                {
                  "value": 0.00031831927,
                  "description": "score(freq=1.0), computed as boost * idf * tf from:",
                  "details": [
                    {
                      "value": 2.2,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 0.00031831927,
                      "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                      "details": [
                        {
                          "value": 1570,
                          "description": "n, number of documents containing term",
                          "details": []
                        },
                        {
                          "value": 1570,
                          "description": "N, total number of documents with field",
                          "details": []
                        }
                      ]
                    },
                    {
                      "value": 0.45454544,
                      "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                      "details": [
                        {
                          "value": 1,
                          "description": "freq, occurrences of term within document",
                          "details": []
                        },
                        {
                          "value": 1.2,
                          "description": "k1, term saturation parameter",
                          "details": []
                        },
                        {
                          "value": 0.75,
                          "description": "b, length normalization parameter",
                          "details": []
                        },
                        {
                          "value": 1,
                          "description": "dl, length of field",
                          "details": []
                        },
                        {
                          "value": 1,
                          "description": "avgdl, average length of field",
                          "details": []
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "value": 8.400319,
              "description": "sum of:",
              "details": [
                {
                  "value": 3.974638,
                  "description": "weight(question:开户 in 1099) [PerFieldSimilarity], result of:",
                  "details": [
                    {
                      "value": 3.974638,
                      "description": "score(freq=1.0), computed as boost * idf * tf from:",
                      "details": [
                        {
                          "value": 2.2,
                          "description": "boost",
                          "details": []
                        },
                        {
                          "value": 3.035335,
                          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                          "details": [
                            {
                              "value": 75,
                              "description": "n, number of documents containing term",
                              "details": []
                            },
                            {
                              "value": 1570,
                              "description": "N, total number of documents with field",
                              "details": []
                            }
                          ]
                        },
                        {
                          "value": 0.59520733,
                          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                          "details": [
                            {
                              "value": 1,
                              "description": "freq, occurrences of term within document",
                              "details": []
                            },
                            {
                              "value": 1.2,
                              "description": "k1, term saturation parameter",
                              "details": []
                            },
                            {
                              "value": 0.75,
                              "description": "b, length normalization parameter",
                              "details": []
                            },
                            {
                              "value": 7,
                              "description": "dl, length of field",
                              "details": []
                            },
                            {
                              "value": 16.57516,
                              "description": "avgdl, average length of field",
                              "details": []
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "value": 4.425681,
                  "description": "weight(question:条件 in 1099) [PerFieldSimilarity], result of:",
                  "details": [
                    {
                      "value": 4.425681,
                      "description": "score(freq=1.0), computed as boost * idf * tf from:",
                      "details": [
                        {
                          "value": 2.2,
                          "description": "boost",
                          "details": []
                        },
                        {
                          "value": 3.379786,
                          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                          "details": [
                            {
                              "value": 53,
                              "description": "n, number of documents containing term",
                              "details": []
                            },
                            {
                              "value": 1570,
                              "description": "N, total number of documents with field",
                              "details": []
                            }
                          ]
                        },
                        {
                          "value": 0.59520733,
                          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                          "details": [
                            {
                              "value": 1,
                              "description": "freq, occurrences of term within document",
                              "details": []
                            },
                            {
                              "value": 1.2,
                              "description": "k1, term saturation parameter",
                              "details": []
                            },
                            {
                              "value": 0.75,
                              "description": "b, length normalization parameter",
                              "details": []
                            },
                            {
                              "value": 7,
                              "description": "dl, length of field",
                              "details": []
                            },
                            {
                              "value": 16.57516,
                              "description": "avgdl, average length of field",
                              "details": []
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },

the second result explain is 
"_explanation": {
          "value": 8.219678,
          "description": "sum of:",
          "details": [
            {
              "value": 0.000298909,
              "description": "weight(modelId:1 in 18) [PerFieldSimilarity], result of:",
              "details": [
                {
                  "value": 0.000298909,
                  "description": "score(freq=1.0), computed as boost * idf * tf from:",
                  "details": [
                    {
                      "value": 2.2,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 0.000298909,
                      "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                      "details": [
                        {
                          "value": 1672,
                          "description": "n, number of documents containing term",
                          "details": []
                        },
                        {
                          "value": 1672,
                          "description": "N, total number of documents with field",
                          "details": []
                        }
                      ]
                    },
                    {
                      "value": 0.45454544,
                      "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                      "details": [
                        {
                          "value": 1,
                          "description": "freq, occurrences of term within document",
                          "details": []
                        },
                        {
                          "value": 1.2,
                          "description": "k1, term saturation parameter",
                          "details": []
                        },
                        {
                          "value": 0.75,
                          "description": "b, length normalization parameter",
                          "details": []
                        },
                        {
                          "value": 1,
                          "description": "dl, length of field",
                          "details": []
                        },
                        {
                          "value": 1,
                          "description": "avgdl, average length of field",
                          "details": []
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "value": 8.219379,
              "description": "sum of:",
              "details": [
                {
                  "value": 3.3087745,
                  "description": "weight(question:股 in 18) [PerFieldSimilarity], result of:",
                  "details": [
                    {
                      "value": 3.3087745,
                      "description": "score(freq=1.0), computed as boost * idf * tf from:",
                      "details": [
                        {
                          "value": 2.2,
                          "description": "boost",
                          "details": []
                        },
                        {
                          "value": 2.782802,
                          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                          "details": [
                            {
                              "value": 103,
                              "description": "n, number of documents containing term",
                              "details": []
                            },
                            {
                              "value": 1672,
                              "description": "N, total number of documents with field",
                              "details": []
                            }
                          ]
                        },
                        {
                          "value": 0.54045826,
                          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                          "details": [
                            {
                              "value": 1,
                              "description": "freq, occurrences of term within document",
                              "details": []
                            },
                            {
                              "value": 1.2,
                              "description": "k1, term saturation parameter",
                              "details": []
                            },
                            {
                              "value": 0.75,
                              "description": "b, length normalization parameter",
                              "details": []
                            },
                            {
                              "value": 10,
                              "description": "dl, length of field",
                              "details": []
                            },
                            {
                              "value": 16.355263,
                              "description": "avgdl, average length of field",
                              "details": []
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "value": 4.910605,
                  "description": "weight(question:开户 in 18) [PerFieldSimilarity], result of:",
                  "details": [
                    {
                      "value": 4.910605,
                      "description": "score(freq=2.0), computed as boost * idf * tf from:",
                      "details": [
                        {
                          "value": 2.2,
                          "description": "boost",
                          "details": []
                        },
                        {
                          "value": 3.181047,
                          "description": "idf, computed as log(1 + (N - n + 0.5) / (n + 0.5)) from:",
                          "details": [
                            {
                              "value": 69,
                              "description": "n, number of documents containing term",
                              "details": []
                            },
                            {
                              "value": 1672,
                              "description": "N, total number of documents with field",
                              "details": []
                            }
                          ]
                        },
                        {
                          "value": 0.7016851,
                          "description": "tf, computed as freq / (freq + k1 * (1 - b + b * dl / avgdl)) from:",
                          "details": [
                            {
                              "value": 2,
                              "description": "freq, occurrences of term within document",
                              "details": []
                            },
                            {
                              "value": 1.2,
                              "description": "k1, term saturation parameter",
                              "details": []
                            },
                            {
                              "value": 0.75,
                              "description": "b, length normalization parameter",
                              "details": []
                            },
                            {
                              "value": 10,
                              "description": "dl, length of field",
                              "details": []
                            },
                            {
                              "value": 16.355263,
                              "description": "avgdl, average length of field",
                              "details": []
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
 why N and avgdl number are different in different result .The total number of documents with field and average length of field should be same in single search request?

### Steps to Reproduce

use the index_patterns such as 
PUT _template/test_template
{
    "index_patterns": ["testz_*"],  
    "order": 0,                
    "settings": {
        "number_of_shards": 2,  
        "number_of_replicas": "1",        
        "refresh_interval": "5s"          
    },
    "aliases": {
        "alias_1": {}          
    },
    "mappings": {
            "_source": {            
                "enabled":true
            },
            "properties": {        
			        	"question": {
                    "type": "text",
				          	"analyzer":"ik_max_word",
			       		"search_analyzer":"ik_smart"
        }
    }
}

question should be Chinese .

### Logs (if relevant)

can use data test 

{"index": {"_index": "testz_keyword1", "_id": 1}}
{"question": "Q：年龄满16周岁但未满18周岁可以开户吗？"}
{"index": {"_index": "testz_keyword1", "_id": 2}}
{"question": "Q：未成年人因遗产继承需要开户怎么开？"}
{"index": {"_index": "testz_keyword1", "_id": 3}}
{"question": "Q：个人和机构客户都可以开通B股账户吗？"}
{"index": {"_index": "testz_keyword1", "_id": 4}}
{"question": "Q：个人开通融资融券账户需要什么条件吗？"}
{"index": {"_index": "testz_keyword1", "_id": 5}}
{"question": "Q：机构开通融资融券账户有要求吗？"}
{"index": {"_index": "testz_keyword1", "_id": 6}}
{"question": "Q：开通融资融券账户有年龄限制吗？"}
{"index": {"_index": "testz_keyword1", "_id": 7}}
{"question": "Q：外籍人员是否可以开融资融券账户？"}
{"index": {"_index": "testz_keyword1", "_id": 8}}
{"question": "Q：期货的含义是什么？"}
{"index": {"_index": "testz_keyword1", "_id": 9}}
{"question": "Q：个人开通期货账户需要什么条件吗？"}
{"index": {"_index": "testz_keyword1", "_id": 10}}
{"question": "Q：机构开通期货账户有什么条件？"}
{"index": {"_index": "testz_keyword1", "_id": 11}}
{"question": "Q：个人开通期权账户有什么要求？"}
{"index": {"_index": "testz_keyword1", "_id": 12}}
{"question": "Q：机构开通期权账户有什么要求？"}
{"index": {"_index": "testz_keyword1", "_id": 13}}
{"question": "Q：请问港澳台居民开立A股需要什么证件？"}
{"index": {"_index": "testz_keyword1", "_id": 14}}
{"question": "Q：请问港澳台居民开立B股需要什么证件？"}
{"index": {"_index": "testz_keyword1", "_id": 15}}
{"question": "Q：请问港澳台居民开立封闭式基金账户需要什么证件？"}
{"index": {"_index": "testz_keyword1", "_id": 16}}
{"question": "Q：请问港澳台居民开立股转系统账户需要什么证件？"}
{"index": {"_index": "testz_keyword1", "_id": 17}}
{"question": "Q：请问港澳台居民开立信用账户需要什么证件？"}
{"index": {"_index": "testz_keyword1", "_id": 18}}
{"question": "Q：港澳台未成年人是否可以开户？"}
{"index": {"_index": "testz_keyword1", "_id": 19}}
{"question": "Q：外籍人员开立A股需要什么资料？"}
{"index": {"_index": "testz_keyword1", "_id": 20}}
{"question": "Q：外籍人员开立B股需要什么资料？"}
{"index": {"_index": "testz_keyword1", "_id": 21}}
{"question": "Q：请问个人开通A股账户开户费是多少？"}
{"index": {"_index": "testz_keyword1", "_id": 22}}
{"question": "Q：机构开通A股账户开户费是多少？"}
{"index": {"_index": "testz_keyword1", "_id": 23}}
{"question": "Q：请问开户费有优惠吗？"}
{"index": {"_index": "testz_keyword1", "_id": 24}}
{"question": "Q：开户费什么时候扣取？"}
{"index": {"_index": "testz_keyword1", "_id": 25}}
{"question": "Q：开户费要扣多久？"}
{"index": {"_index": "testz_keyword1", "_id": 26}}
{"question": "Q：在查询开户进度的时候怎么判断是否要收取开户费？"}
{"index": {"_index": "testz_keyword1", "_id": 27}}
{"question": "Q：港澳台居民开A股账户怎么收取开户费？"}
{"index": {"_index": "testz_keyword1", "_id": 28}}
{"question": "Q：个人开通B股账户开户费是多少？"}
{"index": {"_index": "testz_keyword1", "_id": 29}}
{"question": "Q：机构开通B股账户开户费是多少？"}
{"index": {"_index": "testz_keyword1", "_id": 30}}
{"question": "Q：请问封闭式基金账户开户是否要收取开户费？"}
{"index": {"_index": "testz_keyword1", "_id": 31}}
{"question": "Q：请问开放式基金账户开户是否要收取开户费？"}
{"index": {"_index": "testz_keyword1", "_id": 32}}
{"question": "Q：个人开立融资融券账户开户费怎么收取？"}
{"index": {"_index": "testz_keyword1", "_id": 33}}
{"question": "Q：机构开立融资融券账户开户费怎么收取？"}
{"index": {"_index": "testz_keyword1", "_id": 34}}
{"question": "Q：请问A股开户可以通过哪些渠道进行开户？"}
{"index": {"_index": "testz_keyword1", "_id": 35}}
{"question": "Q：什么是网上开户？"}
{"index": {"_index": "testz_keyword1", "_id": 36}}
{"question": "Q：网上开户支持办理哪些业务？"}
{"index": {"_index": "testz_keyword1", "_id": 37}}
{"question": "Q：通过手机软件怎么操作开通A股呢？"}
{"index": {"_index": "testz_keyword1", "_id": 38}}
{"question": "Q：通过官网怎么操作开通A股账户呢？"}
{"index": {"_index": "testz_keyword1", "_id": 39}}
{"question": "Q：A股现场开户需要携带什么资料"}
{"index": {"_index": "testz_keyword1", "_id": 40}}
{"question": "Q：境内个人开B股账户怎么开？"}
{"index": {"_index": "testz_keyword1", "_id": 41}}
{"question": "Q：境外个人开B股账户怎么开？"}
{"index": {"_index": "testz_keyword1", "_id": 42}}
{"question": "Q：境外机构开B股账户怎么开？"}
{"index": {"_index": "testz_keyword1", "_id": 43}}
{"question": "Q：上海B股股东账户有几种类型？"}
{"index": {"_index": "testz_keyword1", "_id": 44}}
{"question": "Q：B股开户注意事项？"}
{"index": {"_index": "testz_keyword1", "_id": 45}}
{"question": "Q：请问融资融券账户是否可以网上开通？"}
{"index": {"_index": "testz_keyword1", "_id": 46}}
{"question": "Q:融资融券账户现场开户如何办理？"}
{"index": {"_index": "testz_keyword1", "_id": 47}}
{"question": "Q:期货账户如何开通？"}
{"index": {"_index": "testz_keyword1", "_id": 48}}
{"question": "Q：期权账户开户如何开通？"}
{"index": {"_index": "testz_keyword1", "_id": 49}}
{"question": "Q：已开通上海期权账户如何开通深市期权账户？"}
{"index": {"_index": "testz_keyword1", "_id": 50}}
{"question": "Q：请问港澳台居民非现场开户怎么操作？"}

**Comment by jimczi** [comment]
By default the index statistics for a single search request are computed per shard. That's why you see different values for  the total number of documents with field and average length of field, it depends on which shard the document belongs to.
If you want to use global statistics you'll have to set the `dfs_query_then_fetch` option. See  https://www.elastic.co/guide/en/elasticsearch/reference/8.7/consistent-scoring.html#_relevancy_looks_wrong for a detailed explanation.
