### ISSUE TITLE
Terms aggs: Sort by avg sub aggregation support

### ISSUE THREAD

**Issue by crespocarlos** [elastic/elasticsearch#95925]
## Summary

In Infrastructure Observability, we would like to provide on the [hosts view page](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts) the capability of showing the Top X hosts sorted by a metric field, to help surface possible problems to users in their infra.

```json
GET metricbeat-*,metrics-*/_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "now-15m",
              "lte": "now"
            }
          }
        }
      ]
    }
  },
  "runtime_mappings": {
    "rx_bytes_per_period": {
      "type": "double",
      "script": "emit((doc['host.network.ingress.bytes'].value/(doc['metricset.period'].value / 1000)));"""
    },
    "tx_bytes_per_period": {
      "type": "double",
      "script": "emit((doc['host.network.egress.bytes'].value/(doc['metricset.period'].value / 1000)))"
    },
    "disk_latency": {
      "type": "double",
      "script": "emit((doc['system.diskio.write.time'].value + doc['system.diskio.read.time'].value) / ((doc['system.diskio.read.count'].value + doc['system.diskio.write.count'].value)));"
    },
    "cpu_usage": {
      "type": "double",
      "script": "emit((doc['system.cpu.user.pct'].value + doc['system.cpu.system.pct'].value) / (doc['system.cpu.cores'].value));"
    }
  },
  "aggs": {
    "grouping": {
      "terms": {
        "field": "host.name",
        "order": {
          "rx>value": "desc"
        },
        "size": 10,
        "min_doc_count": 1
      },
      "aggs": {
        "diskLatency": {
          "filter": {
            "bool": {
              "must": [
                {
                  "exists": {
                    "field": "system.diskio.read.time"
                  }
                },
                {
                  "exists": {
                    "field": "system.diskio.write.time"
                  }
                },
                {
                  "exists": {
                    "field": "system.diskio.read.count"
                  }
                },
                {
                  "exists": {
                    "field": "system.diskio.write.count"
                  }
                }
              ]
            }
          },
          "aggs": {
            "value": {
              "min": {
                "field": "disk_latency"
              }
            }
          }
        },
        "cpuUsage": {
          "filter": {
            "bool": {
              "must": [
                {
                  "exists": {
                    "field": "system.cpu.user.pct"
                  }
                },
                {
                  "exists": {
                    "field": "system.cpu.system.pct"
                  }
                },
                {
                  "exists": {
                    "field": "system.cpu.cores"
                  }
                }
              ]
            }
          },
          "aggs": {
            "cc": {
              "avg": {
                "field": "cpu_usage",
                "missing": 0
              }
            }
          }
        },
        "rx": {
          "filter": {
            "exists": {
              "field": "host.network.ingress.bytes"
            }
          },
          "aggs": {
            "value": {
              "avg": {
                "field": "rx_bytes_per_period",
                "missing": 0
              }
            }
          }
        },
        "tx": {
          "filter": {
            "exists": {
              "field": "host.network.egress.bytes"
            }
          },
          "aggs": {
            "value": {
              "avg": {
                "field": "tx_bytes_per_period",
                "missing": 0
              }
            }
          }
        },
        "memoryTotal": {
          "filter": {
            "exists": {
              "field": "system.memory.total"
            }
          },
          "aggs": {
            "value": {
              "avg": {
                "field": "system.memory.total"
              }
            }
          }
        },
        "memory": {
          "avg": {
            "field": "system.memory.actual.used.pct"
          }
        }
      }
    }
  }
}
```

However, the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_ordering_by_a_sub_aggregation) says that sorting by sub-aggregations usually produces wrong results and it only works in 2 situations: sort by `max` `desc` and `min` `asc`. 

An alternative would be to use `composite` aggregation instead to fetch all hosts + metrics and sort on the client side, but when considering enterprise datasets, where thousand of hosts can be found, ordering on the client side has proven to be problematic because it can take too much time.

I'm not sure if it's feasible, but what I'd like to propose is that Elasticsearch also supports sorting by `avg` besides `min` and `max` in terms aggs.

**Side note:** Possibly because it's not supported, another thing that can happen when sorting by `avg` is what's been described [here](https://github.com/elastic/elasticsearch/issues/95239), where null buckets are ranked higher than buckets with values when sorting by `avg` `desc` (missing value doesn't really work, because it influences the avg result, producing wrong results)

**Comment by martijnvg** [comment]
Unfortunately sorting accurately by avg sub agg is not something that we can support in aggregations. With the terms aggregation sorting by sub aggregation like avg need to see the whole group in order to be accurate. In order to do that we need to send all matching buckets to the coordinating node for the reduce. The coordinating node will likely run out of memory as part of doing this. This is one of the reason why by default only the top term buckets are returned to the coordinating node for the reduce. When sorting by min or max aggregation this works well, but not so for the other metric aggregations. There is just no way to do this safely with aggregations.

I do like to add that these kind of queries will be supported in esql.  And these queries will also produce an accurate result. Esql will have the infrastructure to spill to disk, so that not everything needs to be kept in memory. Which is what is currently Search API (and aggregations) is doing.
