### ISSUE TITLE
Analyzers starting with _ are silently ignored

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#9596]
When an analyzer is defined that has a name starting with _ then this analyzer is silently dropped from the mapping once the mapping source is propagated through the cluster (https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/mapper/core/AbstractFieldMapper.java#L795).  The local document mapper and mapping in the cluster state are then out of sync on some nodes and documents might be analyzed with the default analyzer on some or the analyzer that was defined by the user on others. After restarting the nodes, the analyzer setting is completely lost. Example below.

When an analyzer is configured in the index settings, there should be a check to make sure the name does not start with an _. 

See also: https://github.com/elasticsearch/elasticsearch/issues/3544#issuecomment-73203535

Example:

```
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "_some_name": {
          "tokenizer":"keyword"
        }
      }
    }
  }
}

PUT test/_mapping/page
{
  "page": {
    "properties": {
      "text": {
        "type": "string",
        "analyzer": "_some_name"
      }
    }
  }
}

GET test/_mapping

```

results in

```

{
   "test": {
      "mappings": {
         "page": {
            "properties": {
               "text": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```

**Comment by rjernst** [comment]
+1
