### ISSUE TITLE
xpack.searchable.snapshot.allocate_on_rolling_restart causes cluster red state

### ISSUE THREAD

**Issue by PixelOrange** [elastic/elasticsearch#96009]
### Elasticsearch Version

8.4.3 (ECK 2.3)

### Java Version

_bundled_

### OS Version

Ubuntu 5.4.0-135-generic

### Problem Description

`xpack.searchable.snapshot.allocate_on_rolling_restart` defaults to `false` (https://github.com/elastic/elasticsearch/pull/66369) when disabling shard allocation for upgrades/maintenance (https://www.elastic.co/guide/en/elastic-stack/8.7/upgrading-elasticsearch.html). This can cause the cluster to go red if data is on frozen pods and those pods are restarted. There appear to be two issues.

The first issue is that because frozen pods do not behave in the same manner as hot/warm/cold tier pods, they do not pick the indices back up when they recover. Instead, the shards remain unassigned until the shard allocation is restored. Since frozen does not use replicas, data remains unavailable for much longer than it should.

The second issue applies to cross-cluster-search. Any cross-cluster activity is disrupted with shard errors `no_shard_available_action_exception`. Preventing a cluster from going red is impossible but attempts should be made to minimize the duration of that state as much as possible.

Recommendation: default this setting to `true` as unnecessary movement is less impactful than a cluster in a red state and update both the documentation (https://github.com/elastic/elasticsearch/issues/82610) as well as the Upgrading Elasticsearch page above to indicate that this behavior exists for users that want to use it or prevent it.

### Steps to Reproduce

1. Deploy two clusters, one with data and one as a cross cluster search cluster.
2. Move data into the frozen tier with ILM
3. Enable `"cluster.routing.allocation.enable": "primaries"`
4. Restart the frozen pod
5. Watch the cluster state
6. Once it is red, attempt to search for any data from the CCS cluster to see shard errors.
7. Once the pod has returned, validate that the shards to not restore to the frozen pod until you set `"cluster.routing.allocation.enable": null`

**Comment by PixelOrange** [comment]
Did the ping for this request get missed or is it being considered internally and just no updates yet?

**Comment by DaveCTurner** [comment]
Sorry, we did look at this but failed to follow up it seems. According to the [rolling restart instructions](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/restart-cluster.html#restart-cluster-rolling) you should set `cluster.routing.allocation.enable: null` as soon as the node comes back up and joins the cluster. Don't wait at this point. If you delay this step, we'd expect some shards to remain unallocated indeed.

To complete avoid a `red` cluster during a rolling restart of your frozen nodes, you'll either need to enable replicas on your frozen indices or else completely vacate each node with a shard allocation filter before restarting it.

I'm closing this as it doesn't look like there's any action for the ES dev team to take here. If you have further questions, we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
