### ISSUE TITLE
Params stored with search templates are ignored

### ISSUE THREAD

**Issue by abdonpijpelink** [elastic/elasticsearch#96006]
The search templates documentation has an [example of storing params with a search template](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html#create-search-template). However, these stored params seem to be ignored. 

This could be:
- a bug in Elasticsearch, but it's unclear what the function of stored params would be. Default values? Mustache templates already [offer another mechanism to set default values](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html#search-template-set-default-values).
- a bug in the documentation. Maybe we should not be storing params with search templates.

To reproduce (on a vanilla 8.7 cluster on Elastic Cloud):

```
PUT _scripts/my-search-template
{
  "script": {
    "lang": "mustache",
    "source": {
      "size": "{{size}}"
    },
    "params": {
      "size": 1
    }
  }
}

POST _render/template
{
  "id": "my-search-template"
}
```

Returns:

```
{
  "template_output": {
    "size": ""
  }
}
```

(note that `size` is an empty string instead of `1`)

Explicitly passing `params` to the `_render` request does work correctly:

```
POST _render/template
{
  "id": "my-search-template",
  "params": {
    "size": 2
  }
}
```

The same happens with the `_search` API (to rule out an issue with `_render`). The following request fails:

```
GET /_search/template
{
  "id": "my-search-template"
}
```
("number_format_exception", "reason": "empty String")

While this one works correctly:

```
GET /_search/template
{
  "id": "my-search-template",
  "params": {
    "size": 3
  }
}
```

**Comment by ioanatia** [comment]
I have to look more closely into this, but I don't think we even store the params?

Given:
```
PUT _scripts/my-search-template
{
  "script": {
    "lang": "mustache",
    "source": {
      "size": "{{size}}"
    },
    "params": {
      "size": 1
    }
  }
}
```

Retrieving the template with `GET _scripts/my-search-template`:

```
{
  "_id": "my-search-template",
  "found": true,
  "script": {
    "lang": "mustache",
    "source": """{"size":"{{size}}"}""",
    "options": {
      "content_type": "application/json;charset=utf-8"
    }
  }
}
```

It also looks like we are lacking some parameter validation, because we can pass anything and still store the template:

```
PUT _scripts/my-search-template
{
  "script": {
    "lang": "mustache",
    "source": {
      "size": "{{size}}"
    },
    "gaga": {
      "size": 1
    }
  },
  "something": "yes, I am an invalid param, but I am ignored :("
}
```

**Comment by benwtrent** [comment]
Indeed, the bug is that we allow unknown parameters and we are not strict on the parsing. 

Additionally, the docs should be updated to indicate that users shouldn't supply parameters.
