### ISSUE TITLE
Unable to generate export: Either `type` or `objects` are required

### ISSUE THREAD

**Issue by khteh** [elastic/elasticsearch#96011]
### Elasticsearch Version

8.7.1

### Java Version

_bundled_

### OS Version

Ubuntu 23.04

### Problem Description

Trying to export ALL objects from the top-right button but hit the error "Unable to generate export: Either `type` or `objects` are required." on Kibana 8.7.1
![image](https://github.com/elastic/elasticsearch/assets/3871483/6c8f2293-a61c-4ba8-a877-6bb492ef1d37)

### Steps to Reproduce

Export ALL objects from the top-right button from Kibana 8.7.1

**Comment by thecoop** [comment]
@khteh This looks like a kibana issue, which should be reported to https://github.com/elastic/kibana/. Please open an issue there, and the kibana team will take a look.
