### ISSUE TITLE
[CI] CcsCommonYamlTestSuiteIT test {p0=search/160_exists_query/Test exists query on unmapped date field} failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#96073]
**Build scan:**
https://gradle-enterprise.elastic.co/s/xavaeoxg72uha/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT/test%20%7Bp0=search%2F160_exists_query%2FTest%20exists%20query%20on%20unmapped%20date%20field%7D

**Reproduction line:**
```
./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT.test {p0=search/160_exists_query/Test exists query on unmapped date field}" -Dtests.seed=9BECCAB8252C419 -Dtests.locale=el-GR -Dtests.timezone=Australia/West -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch/160_exists_query/Test%20exists%20query%20on%20unmapped%20date%20field%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([9BECCAB8252C419]:0)

```

**Comment by benwtrent** [comment]
Again, the suite timeout is likely NOT due to this individual test, but because all previous tests took so long to run :/

**Comment by benwtrent** [comment]
The test failed quickly due to suite timeout. Suite timeout has been increased to 60m, closing this as the individual test isn't to blame, but instead the entire suite runtime and infra.

Related: https://github.com/elastic/elasticsearch/pull/100585
