### ISSUE TITLE
Expose term frequency in Painless script score context

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#96087]
### Description

In our current Solr setup, we make heavy use of [Solr functions](https://solr.apache.org/guide/8_11/function-queries.html) for implementing query time multiplicative and additive boosting. We are in the process of migrating from Solr to Elasticsearch, and porting our querying logic over. The majority of Solr functions can be implemented with Painless scripting in a [function score query script score](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score) to provide multiplicative boosting, however there are a few functions that cannot be, such as

- [`termfreq`](https://solr.apache.org/guide/8_11/function-queries.html#termfreq-function)
- [`tf`](https://solr.apache.org/guide/8_11/function-queries.html#tf-function)
- [`totaltermfreq`](https://solr.apache.org/guide/8_11/function-queries.html#totaltermfreq-function)
- [`sumtotaltermfreq`](https://solr.apache.org/guide/8_11/function-queries.html#sumtotaltermfreq-function)
- [`payload`](https://solr.apache.org/guide/8_11/function-queries.html#payload-function)

the biggest pain in particular is the lack of `termfreq`, which we use as part of a boost for calculating popularity, a calculation that incorporates a baseline value so that new content of unknown popularity is factored in.

In order to work around not having access to `termfreq` in a script score context, we have to write a custom script engine and script plugin that is able to look up term frequencies from the [`PostingsEnum`](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/index/PostingsEnum.html). This is less than desirable because 

1. we need to maintain a plugin to provide functionality across versions
2. A script engine approach is either constrained to a particular usage/application of term frequencies, or, the complexity of a script engine approach dramatically increases if we want to support all other functions, and allow them to be combined in arbitrary ways i.e. replicate functions that are already exposed in Painless.

I'm opening this issue to request that Painless support retrieving term frequencies in a script score context.

**Comment by russcam** [comment]
@astefan has this been discussed at triage?

**Comment by rjernst** [comment]
This has been implemented in https://github.com/elastic/elasticsearch/pull/108634
