### ISSUE TITLE
Feature request: graceful stop/restart

### ISSUE THREAD

**Issue by blacktek** [elastic/elasticsearch#96147]
I'd like to have a feature in elasticsearch server that allows to perform a graceful stop or restart.

Basically after executing a systemctl stop/restart command I would like that the current pending requests are completed first (with a customizable timeout), while not accepting any new request.

This would simplify the draining of inflight requests, without forcing the application to retry connections abruptly closed

You already have something similar with https://www.elastic.co/guide/en/cloud/current/ec-maintenance-mode-deployments.html - but it should work with base elasticsearch server too.

**Comment by blacktek** [comment]
Hello,
  Thank you for this quick add-on!

I've only two small questions:
1) when will it be released? I see it's merged to main branch. Now I'm running 7.17.10 - will it be released with the next minor version I'll get from apt? (of course, it depends on Ubuntu too)
2) what is/will be the default value for http.shutdown_grace_period ?

Thank you again

**Comment by stu-elastic** [comment]
@blacktek 
It will be released with 8.9, which is the next minor in the 8 series.  We don't share dates, but you can check out our minor release history to get an expectation of our cadence.

We have no plans to backport it to 7.17.

The default value for `http.shutdown_grace_period` is zero, which means there is no grace period.  It takes a `TimeValue`.  There will be docs for it in 8.9.

**Comment by blacktek** [comment]
> @blacktek It will be released with 8.9, which is the next minor in the 8 series. We don't share dates, but you can check out our minor release history to get an expectation of our cadence.

Hello,
  can you confirm if this features has been released in the elasticsearch 8.9 just released? it seems the case, but I want to double check :)

**Comment by blacktek** [comment]
verified and it's merged.

now https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.9.0.html is complete.

Infra/Node Lifecycle
Gracefully shutdown elasticsearch [#96363](https://github.com/elastic/elasticsearch/pull/96363)

thank you!

**Comment by stu-elastic** [comment]
Yeah, it's there.  Thanks for the verification.

**Comment by blacktek** [comment]
Hi @stu-elastic ,
> That tells me there was a 5 second grace period but requests kept coming into the node

This is surely possible: during the grace period (only known to elasticsearch, not to the proxy) the new requests should be rejected, according to the expected behaviour.

Am I wrong? This issue happened only once, so far.

Should I open a ticket on https://discuss.elastic.co/ ? What else can I add?

tnx

**Comment by stu-elastic** [comment]
I wasn't accurate.  There were outstanding requests that took more than 5 seconds to complete.  ES stops accepting new connections as soon as it sees the sigterm and closes all idle connections as well.

> Unit process 1565 (java) remains running after unit stopped.

This tells me the elasticsearch unit does is not allowing the process to fully shutdown and so is force killing it.  Please check the definition of the unit and make sure it matches the timeout settings being used.

**Comment by blacktek** [comment]
@stu-elastic 
thank you again for your quick feedback.

Please look:
root@ip-172-23-0-61:~# systemctl cat elasticsearch|grep -i timeout
# Disable timeout logic and wait until process is stopped
TimeoutStopSec=0
# Allow a slow startup before the systemd notifier module kicks in to extend the timeout
TimeoutStartSec=900
root@ip-172-23-0-61:~#

WIth TimeoutStopSec=0 we should not have basically any Stop Timeout.

Tomorrow we change this setting too:
RestartSec=5s
to
RestartSec=11s 

But I think it will have no effect because that timeout is the timeout to wait before restarting a service.

It seems that our configuration of the systemd unit is correct.

Do you have any other idea?

Thank you

**Comment by stu-elastic** [comment]
@blacktek 
Please follow up with a discuss post in the support forum.
