### ISSUE TITLE
ignore_z_value is not supported

### ISSUE THREAD

**Issue by gabi939** [elastic/elasticsearch#96155]
### Elasticsearch Version

7.7.0

### Java Version

1.8.0_252

### OS Version

Ubuntu 18.04

### Problem Description

According to:
https://www.elastic.co/guide/en/elasticsearch/reference/7.7/geo-point.html

I should be able to use parameter ignore_z_value to ignore z values indexed to geo_point field.

But it doesn't work, instead I get the following exception:

{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "field must be either [lat], [lon] or [geohash]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [location] of type [geo_point]",
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "field must be either [lat], [lon] or [geohash]"
    }
  },
  "status" : 400
}

### Steps to Reproduce

1) I have created an index with the following mapping:
`{
  "eren" : {
    "mappings" : {
      "properties" : {
        "location" : {
          "type" : "geo_point"
        }
      }
    }
  }
}

2) I have tried to upload the following document:
{
  
  "location": {
	"lat":40,
	"lon":40,
	"z":20
   }
  
}

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
