### ISSUE TITLE
Cardinality aggregation returns incorrect count for the specific values in the doc 

### ISSUE THREAD

**Issue by karthi-keyan-n** [elastic/elasticsearch#96231]
### Elasticsearch Version

7.17.10

### Installed Plugins

-

### Java Version

_bundled_

### OS Version

Linux ebc75fd6a302 5.15.49-linuxkit

### Problem Description

Cardinality aggregation is returning wrong count consistently if the specific values **8171399** and **5299771** are present in the document. Can you please educate me on why this inconsistency in count is occurring for these 2 values present together at the set of aggregated records? Also can you please help me on how to mitigate this?

### Steps to Reproduce

**ES data setup:**
URL : `localhost:9200/_bulk`
HTTP verb : POST
BODY :  
`{"index" : {"_index": "test_index","_id": "8171399"}}
{"field1":"8171399"}
{"index" : {"_index": "test_index","_id": "5299771"}}
{"field1":"5299771"}`

**Aggregation Query:**
URL : `localhost:9200/test_index/_search`
HTTP verb : GET
BODY :  
`{
	"aggregations": {
        "field1.keyword_cardinality": {
            "cardinality": {
                "field": "field1.keyword",
                "precision_threshold":40000
            }
        },
        "field1.runtime_cardinality": {
            "cardinality": {
							"script": {
								"lang": "painless",
								"source": "'x'+doc['field1.keyword'].value"
							},
                "precision_threshold":40000
            }
        }
    },
    "size": 0
}`

**Actual Response:**
`{
	"took": 77,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": {
			"value": 2,
			"relation": "eq"
		},
		"max_score": null,
		"hits": []
	},
	"aggregations": {
		"field1.runtime_cardinality": {
			"value": 2
		},
		"field1.keyword_cardinality": {
			"value": 1
		}
	}
}`

In the above example, I'm doing aggregation couple of times as below,
1. With the actual value in the index which returns the cardinality count in **field1.keyword_cardinality** field.
2. By appending a text **X** at run time for all the field1 and then aggregate on the same updated value. Cardinality count is returned in **field1.runtime_cardinality** field which returns the expected count.

**Excepted Response:**
`	"aggregations": {
		"field1.runtime_cardinality": {
			"value": 2
		},
		"field1.keyword_cardinality": {
			"value": 2
		}
	}
`

Expectation is both the **field1.runtime_cardinality** and **field1.keyword_cardinality** should be returning the same result.

**Comment by iverase** [comment]
Hello @karthi-keyan-n,

Our documentation is explicit about cardinality being approximated: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate

We never hold the exact value what values are hashed and encoded in particular ways so collisions are possible. This is one case. Here is the hash algorithm: https://github.com/elastic/elasticsearch/blob/0b194b5fd9293f1220ad43fa2abaf379886bb2a0/server/src/main/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregator.java#L417

It is easy to find the the mumur hashes for the provided strings are:

"8171399" -> -554258503214267073
"5299771" -> -554258848804646776

We further encode those hashed values to a 32 encoded hash that depends on the precision using the following method: https://github.com/elastic/elasticsearch/blob/a92a647b9f17d1bddf5c707490a19482c273eda3/server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractLinearCounting.java#L65

In both cases, even using the maximum allowed precision gives the same number: 65092482

Therefore for the algorithm, those two values are the same.
 
Therefore, this result is expected and there is nothing to do, I hope you don't mind I am closing this issue.
