### ISSUE TITLE
’_source’ filtering is slower than query without ‘_source’ field

### ISSUE THREAD

**Issue by nadeem-akhter** [elastic/elasticsearch#96237]
I have an elasticsearch 8.6.0 instance with some data on it, and when trying queries on the data, it is slower to filter '_source' in query than not mentioning the '_source' key at all. Is there any specific reason for this?

Profiling the queries showed **FetchSourcePhase** taking much more time with source filtering on the order of seconds, compared to without '_source'

**Comment by astefan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. Thanks again.
