### ISSUE TITLE
Debian init script doesn't use /etc/alternatives

### ISSUE THREAD

**Issue by calston** [elastic/elasticsearch#9627]
Instead of looping through a fixed list of JDK directories, why not simply use the symlinks already in /etc/alternatives to use the one the user actually wants

**Comment by s1monw** [comment]
removed the discuss label, @tlrx will get back to this in the near future.

**Comment by tlrx** [comment]
Thanks for your suggestion @calston but I think it's better to rely on environment variables like `$JAVA_HOME` for this. Debian alternatives are system wise where env vars can be easily defined per user.

Closed in favor of #13514
