### ISSUE TITLE
Kubernetes dashboard not shown data 

### ISSUE THREAD

**Issue by ahmedhkhalil** [elastic/elasticsearch#96319]
### Elasticsearch Version

Version: 8.7.1, Build: rpm/f229ed3f893a515d590d0f39b05f68913e2d9b53/2023-04-27T04:33:42.127815583Z, JVM: 20.0.1

### Installed Plugins

Kubernetes 

### Java Version

_bundled_

### OS Version

Linux npr-dos-elk01.t2.local 4.18.0-425.19.2.el8_7.x86_64 #1 SMP Tue Apr 4 22:38:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

i have installed Kubernetes agent on my Kubernetes cluster and also installed metric service on ali baba cloud Kubernetes engine 
but there is no dashboard showing data also drop down menu for cluster name is blank 

### Steps to Reproduce

install kuberentes agent on ack cluster alibaba and view dashboard from Kibana

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
