### ISSUE TITLE
Simple query string: minus (-) not honoured if WHITESPACE not specified in flags

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#9633]
Refers to scenario described in #9525

```
{ 
"query":{ 
"simple_query_string" : { 
"query" : "php developer -superguru", 
"analyzer": "my_synonyms", 
"fields": ["title","_all"], 
"flags" : "AND|OR|NOT", 
"default_operator": "AND" 
} 
} 
}
```

translates to

```
         "explanation": "(+title:php +title:developer +title:superguru) (+_all:php +_all:developer +_all:superguru)"
```

which is not desirable.

Adding the WHITESPACE flag resolves 

```
{ 
"query":{ 
"simple_query_string" : { 
"query" : "php developer -superguru", 
"analyzer": "my_synonyms", 
"fields": ["title","_all"], 
"flags" : "AND|OR|NOT|WHITESPACE", 
"default_operator": "AND" 
} 
} 
}

"explanation": "+(title:php _all:php) +(title:developer _all:developer) +(-(title:superguru _all:superguru) *:*)"
```

Had a chat with @rmuir suspecting the - is removed by the analyzer, suggesting replacing it with ^

**Comment by clintongormley** [comment]
@jdconrad is this a bug?

**Comment by jdconrad** [comment]
It depends on if without whitespace we want to separate terms based on other delimiters.  I would say we probably do.  Anyone else have a thought on this?

**Comment by dakrone** [comment]
@jdconrad that makes sense to me.

**Comment by rmuir** [comment]
the main confusion will be that this "operator" is also frequently found in ordinary text.

**Comment by jdconrad** [comment]
@rmuir If we changed the operator to '^' will that be confusing to the users? It's normally a '-' for not in other parsers?

**Comment by clintongormley** [comment]
@jdconrad (I'm guessing not, but) any chance you could define the `-` operator as `-` preceded by whitespace or the beginning of the string?

**Comment by ancabaranga** [comment]
Hi all,

I am facing the same issue. We try to expose to our clients the simple query string ( just + - and phrase). 
I was expecting minus(-) to behave as NOT from the query_string, but the search like "brad -pitt" ignores the - sign. It works instead if I query just "-pitt".

Is there any change to get this issue fixed?

Cheers,
Anca

**Comment by mayya-sharipova** [comment]
Closing this issue as `-` behaviour has been documented in [Simple Query String query documentation](doc/_validate/query?explain)

**Comment by fhaase2** [comment]
This is still the behaviour in the newer Elasticsearch versions. However, this is not documented in the description of the simple query string query documentation anymore.

**Comment by tinhte96** [comment]
I have the same problem with elastic version 7.4.1 too, i created a thread for this https://discuss.elastic.co/t/simple-query-string-minus-doesnt-work-if-whitespace-not-specified-in-flags/237347?u=pilo

**Comment by vadymhimself** [comment]
Any updates here?
