### ISSUE TITLE
Unable to create time series index without setting routing_path

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#96330]
### Elasticsearch Version

main

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

macos

### Problem Description

Running the PUT command below results in a 400 with the error "[index.mode=time_series] requires a non-empty [index.routing_path]". This error conflicts with the documenation that states [Defaults to the list of dimension fields with a time_series_dimension value of true defined in your component template](https://www.elastic.co/guide/en/elasticsearch/reference/master/tsds-index-settings.html#tsds-index-settings).

<img width="500" alt="Screen Shot 2023-05-24 at 8 58 16 AM" src="https://github.com/elastic/elasticsearch/assets/373691/8a81693f-76b2-464c-8f0d-49694ddaf7db">

```
PUT /tracks
{
  "settings": {
    "mode": "time_series"
  },
  "mappings": {
    "properties": {
        "location": {
          "type": "geo_point",
          "time_series_metric": "position"
        },
        "entity_id": {
            "type": "keyword",
            "time_series_dimension": true
        },
        "azimuth": {
            "type": "double"
        },
        "speed": {
            "type": "double"
        },
        "@timestamp": {
            "type": "date"
        }
    }
  }
}
```

### Steps to Reproduce

Run the PUT command below. Notice the 400 response. This conflicts with documentation from https://www.elastic.co/guide/en/elasticsearch/reference/master/tsds-index-settings.html#tsds-index-settings. This command should return a 200 with routing_path defaulting to the list of dimension fields with a time_series_dimension value of true defined in the mappings.

```
PUT /tracks
{
  "settings": {
    "mode": "time_series"
  },
  "mappings": {
    "properties": {
        "location": {
          "type": "geo_point",
          "time_series_metric": "position"
        },
        "entity_id": {
            "type": "keyword",
            "time_series_dimension": true
        },
        "azimuth": {
            "type": "double"
        },
        "speed": {
            "type": "double"
        },
        "@timestamp": {
            "type": "date"
        }
    }
  }
}
```

**Comment by martijnvg** [comment]
I don't think this is a bug. The `index.routing_path` only gets generated when a data stream gets created. This means the index template needs be configured to create data streams.

**Comment by martijnvg** [comment]
Also when creating an index with `index.mode` set to `time_series`, the `index.time_series.start_date` and `index.time_series.end_date` index setting need to be defined. In case when the index template is configured to create a data stream, then this also gets generated based on current time.
