### ISSUE TITLE
Attempting to build or test a classic Elasticsearch plugin against 8.8.0 fails

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#96360]
With the 8.8.0 release if you are attempting to use [this guide](https://www.elastic.co/guide/en/elasticsearch/plugins/8.8/creating-classic-plugins.html) to build an Elasticsearch plugin against 8.8.0 it will fail. You'll see an error similar to this:

```
* What went wrong:
Execution failed for task ':rescore:bundlePlugin'.
> Could not resolve all files for configuration ':rescore:resolveableCompileOnly'.
   > Could not find org.elasticsearch:elasticsearch-preallocate:8.8.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-preallocate/8.8.0/elasticsearch-preallocate-8.8.0.pom
     Required by:
         project :rescore > org.elasticsearch:elasticsearch:8.8.0
```

It seems the artifact for the `elasticsearch-preallocate` library was not published to maven central as part of this release. Right now the workaround for _building_ plugins is to add this to the `build.gradle` file:

```
configurations.all { exclude group: 'org.elasticsearch', module: 'elasticsearch-preallocate' }
```

This doesn't help with test execution though if you are leveraging the Elasticsearch testing framework as we attempt to dynamically load classes from that JAR at runtime.

**Comment by rob-mccann** [comment]
On a related note, elasticsearch-plugin-api is also behind (at 8.6.2)

**Comment by mark-vieira** [comment]
> On a related note, elasticsearch-plugin-api is also behind (at 8.6.2)

Starting with version 8.7 to group has changed to `org.elasticsearch.plugin`.

https://central.sonatype.com/artifact/org.elasticsearch.plugin/elasticsearch-plugin-api/8.8.0/versions

**Comment by mark-vieira** [comment]
ES 8.8.0 is now EOL.
