### ISSUE TITLE
Agg results consistency issue - same operation returns Null in JSON vs Infinity in Java api

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#9636]
Scenario is

performing min agg on a date field when the query does not match any documents (empty resultset) does return:

Null via REST API
Infinity via Java API

The reason for this is given by the fact that there is no feasible/obvious representation in JSON for infinite value.

At the least it would be desirable to have this behaviour documented.

**Comment by abonuccelli-es** [comment]
briefly discussed this with @jpountz

**Comment by dadoonet** [comment]
@abonuccelli-es Wanna create a PR to update https://github.com/elasticsearch/elasticsearch/blob/master/docs/java-api/aggregations/metrics/min-aggregation.asciidoc ?

**Comment by abonuccelli-es** [comment]
yes - assigning this to myself

**Comment by clintongormley** [comment]
Nobody else seems to have had a problem with this in 2.5 years. Closing

**Comment by polyfractal** [comment]
@larry-hernandez Was there a specific reason this was re-opened?

**Comment by polyfractal** [comment]
Closing again for the reasons Clint mentioned: several years and no additional complaints.  The HLRC will soon make this issue moot anyway.
