### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by ruwwi** [elastic/elasticsearch#96387]
### Elasticsearch Version

7.10.2

### Java Version

1.8

### OS Version

Oracle Linux Server 8.5

### Problem Description

Hi all,

I create indexes on a daily basis using fluentd in Elasticsearch. I don't do any mapping on elasticsearch side. After a while, the related index could not be created in Elasticsearch and I got the following error. 

### Steps to Reproduce

There is a template for ilm policy. I deleted the previously created indexes, template and ilm policy. I restarted Elasticsearch and Kibana. When I create an index with an index name that matches the old index pattern and send data to Kibana, I still get the same error. But when I give the index name different, there is no problem. Is this a bug? How can I solve it?

### Logs (if relevant)

{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "object mapping for [Direction] tried to parse field [Direction] as object, but found a concrete value"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "object mapping for [Direction] tried to parse field [Direction] as object, but found a concrete value"
  },
  "status" : 400
}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
