### ISSUE TITLE
[CI] Execution failed for task ':x-pack:qa:mixed-tier-cluster:v8.8.0#mixedClusterTest'

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#96382]
### CI Link

https://gradle-enterprise.elastic.co/s/4gqhiblled2fu

### Repro line

n/a

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

There were many connection refused and none shutdown errors, but the first error seemed to be related to versioning in the PublicationTransportHandler:

```
[2023-05-26T13:14:51,373][WARN ][o.e.d.FileBasedSeedHostsProvider] [v8.8.0-0] expected, but did not find, a dynamic hosts list at [/dev/shm/elastic+elasticsearch+main+periodic+bwc/x-pack/qa/mixed-tier-cluster/build/testclusters/v8.8.0-0/config/unicast_hosts.txt] |  
-- | --
  | »   ↑ repeated 7 times ↑ |  
  | » [2023-05-26T13:14:46,659][WARN ][stderr                   ] [v8.8.0-0] May 26, 2023 1:14:46 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init> |  
  | » [2023-05-26T13:14:51,368][WARN ][o.e.c.c.ClusterBootstrapService] [v8.8.0-0] this node is locked into cluster UUID [gyX4fCUfQZmqBiQWJ2HozQ] but [cluster.initial_master_nodes] is set to [v8.8.0-0, v8.8.0-1, v8.8.0-2]; remove this setting to avoid possible data loss caused by subsequent cluster bootstrap attempts; for further information see https://www.elastic.co/guide/en/elasticsearch/reference/master/important-settings.html#initial_master_nodes |  
  | » [2023-05-26T13:14:52,380][WARN ][o.e.c.c.PublicationTransportHandler] [v8.8.0-0] unexpected error while deserializing an incoming cluster state java.lang.IllegalStateException: unexpected byte [0x02]
```

**Comment by idegtiarenko** [comment]
It might be related to https://github.com/elastic/elasticsearch/blob/e8d4211de73ad498df865e7df935feb890808eb9/server/src/main/java/org/elasticsearch/cluster/metadata/Template.java#L135 if feature flag is not consistent across the nodes

**Comment by mark-vieira** [comment]
> if feature flag is not consistent across the nodes

Indeed. Since 8.8.0 is a released version, that feature would be disabled by default, but it would be enabled by default in the current snapshot version.

You'll need to add the following to the cluster configuration for that QA project:

```
requiresFeature 'es.dlm_feature_flag_enabled', Version.fromString("8.8.0")
```
