### ISSUE TITLE
knn search in `has_child`

### ISSUE THREAD

**Issue by puppylpg** [elastic/elasticsearch#96405]
### Description

I've tried new knn/ann search in elasticsearch 8 and feels very good. Thanks for your work!

We're now using elasticsearch to do some parent-child search. For example, searching article comments that match `pikachu` with `has_child` query to get the topK articles. But it seems that knn search can't be used in the `query` body of `has_child`:
```
GET <index>/_search
{
  "query": {
    "has_child": {
      "type": "<child type>",
      "query": {
        "knn": {
          "field": "text_vector",
          "query_vector": [<a vector>],
          "k": 10,
          "num_candidates": 1000
        }
      }
    }
  }
}
```
will cause:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "[knn] queries cannot be provided directly, use the [knn] body parameter instead"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "[knn] queries cannot be provided directly, use the [knn] body parameter instead"
  },
  "status": 400
}
```
Is there any plan to support knn search in `has_child`?

**Comment by mayya-sharipova** [comment]
@puppylpg Indeed, this is not supported, as `knn` is not a query, but a top level parameter of a search request.

Currently the way to achieve what what you are looking for is duplication, having an index of comments, and for each comment store info about its article.

I will leave this for the team to discuss if we want to support this.

**Comment by mayya-sharipova** [comment]
@puppylpg From 8.12, we have a new [knn query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-knn-query.html). And `has_child` query can be used with `knn` query, like this:

```js
{
    "query": {
        "has_child": {
            "type": "paragraph",
            "query": {
                "knn": {
                    "field": "my_vector",
                    "query_vector": [<>],
                    "num_candidates": 2
                }
            }
        }
    }
}
```

But we don't recommend this, as  `has_child` query is slow because it needs to do these extra joins.

The recommended way to address this problem is through [nested knn search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#nested-knn-search).

**Comment by puppylpg** [comment]
Thanks for your dedicated work :+1:

**Comment by Milan-Helios** [comment]
> [@puppylpg](https://github.com/puppylpg) From 8.12, we have a new [knn query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-knn-query.html). And `has_child` query can be used with `knn` query, like this:
> 
> {
>     "query": {
>         "has_child": {
>             "type": "paragraph",
>             "query": {
>                 "knn": {
>                     "field": "my_vector",
>                     "query_vector": [<>],
>                     "num_candidates": 2
>                 }
>             }
>         }
>     }
> }
> But we don't recommend this, as `has_child` query is slow because it needs to do these extra joins.
> 
> The recommended way to address this problem is through [nested knn search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#nested-knn-search).

if i tried to run as knn_search then it throw me an error ` [knn-search] unknown field [has_child]` . and if i use it with search then it doesn't give me correct answer. please help
