### ISSUE TITLE
Kubernetes deployment - 3rd Stateful set replica always fail with java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by kolsgithub** [elastic/elasticsearch#96414]
I am trying to build a three replica stateful set Elasticsearch cluster in EKS using helm chart. When I deploy with one or two replicas the PODs are getting created and attached in the cluster mode. When I increase the replica count to 3 then the new pod always gets fails with the below error during startup. I am trying to create all three stateful set POD's using role MASTER+DATA. Wondering how come other two POD's using the same image got started successfully whereas the 3rd one always ends up with a class not found issue.

1) Docker image : elasticsearch:8.7.1

`
{"@timestamp":"2023-05-29T19:29:31.036Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"elasticsearch-master-2","elasticsearch.cluster.name":"elasticsearch","error.type":"java.lang.NoClassDefFoundError","error.message":"com/fasterxml/jackson/core/io/JsonStringEncoder","error.stack_trace":"java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/io/JsonStringEncoder\n\tat com.azure.core.util.logging.LoggingEventBuilder.<clinit>(LoggingEventBuilder.java:43)\n\tat com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:103)\n\tat com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:67)\n\tat com.azure.core.util.logging.ClientLogger.<init>(ClientLogger.java:57)\n\tat com.azure.core.util.serializer.JacksonAdapter.<clinit>(JacksonAdapter.java:29)\n\tat org.elasticsearch.repositories.azure.AzureRepositoryPlugin.<clinit>(AzureRepositoryPlugin.java:57)\n\tat java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)\n\tat java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)\n\tat java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)\n\tat java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)\n\tat java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)\n\tat java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:547)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:497)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:634)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:495)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:292)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:161)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$15(PluginsService.java:668)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.node.Node.<init>(Node.java:417)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.node.Node.<init>(Node.java:324)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)\n\tat org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\nCaused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.io.JsonStringEncoder\n\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)\n\tat java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)\n\t... 24 more\n"}
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elasticsearch.log

ERROR: Elasticsearch exited unexpectedly
`

2) Getting the below error when I try to use the docker image : [docker.elastic.co/elasticsearch/elasticsearch:7.17.9]

`
ElasticsearchException[Could not find plugin class [org.elasticsearch.xpack.security.Security]]; nested: ClassNotFoundException[org.elasticsearch.xpack.security.Security];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.xpack.security.Security
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:495)
    at java.base/java.lang.Class.forName(Class.java:474)
    at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:777)
    at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:738)
    at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:533)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170)
    at org.elasticsearch.node.Node.<init>(Node.java:411)
    at org.elasticsearch.node.Node.<init>(Node.java:309)
    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169)
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160)
    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
    at org.elasticsearch.cli.Command.main(Command.java:77)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log
2023-05-23 19:03:59,695328 UTC [432] INFO  Main.cc@111 Parent process died - ML controller exiting
`
whatever the image I use, the 3rd stateful set POD always gets stuck in some class not found issue.

**Comment by mark-vieira** [comment]
It's hard to say without knowing more about your k8s configuration. It certainly sounds like there are files missing from the Elasticsearch distribution. Are you doing anything odd with volume mounts?

**Comment by mark-vieira** [comment]
Since there's been no follow up and we cannot recreate this problem I'm closing this issue.
