### ISSUE TITLE
[CI] SharedClusterSnapshotRestoreIT classMethod failing

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#96425]
This failure seems related: https://gradle-enterprise.elastic.co/s/hbx32w3mmvsiu/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT/testUnrestorableIndexDuringRestore?top-execution=1

**Build scan:**
https://gradle-enterprise.elastic.co/s/hbx32w3mmvsiu/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT" -Dtests.seed=52861D7778F38700 -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

  at __randomizedtesting.SeedInfo.seed([52861D7778F38700]:0)

```

**Comment by DaveCTurner** [comment]
This is a genuine bug, there is a race condition between the end of the restore and the registration of the restore listener: the restore listener is only triggered by cluster state updates received after registration, but there may never be another such cluster state update if the restore completed before registration. It reliably reproduces thusly:

```diff
diff --git a/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java b/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
index 73b66fa5d1b..e15d6a5ed6c 100644
--- a/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
+++ b/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
@@ -72,6 +72,13 @@ public class TransportRestoreSnapshotAction extends TransportMasterNodeAction<Re
     ) {
         restoreService.restoreSnapshot(request, listener.delegateFailure((delegatedListener, restoreCompletionResponse) -> {
             if (restoreCompletionResponse.getRestoreInfo() == null && request.waitForCompletion()) {
+
+                try {
+                    Thread.sleep(500);
+                } catch (InterruptedException e) {
+                    throw new AssertionError(e);
+                }
+
                 RestoreClusterStateListener.createAndRegisterListener(
                     clusterService,
                     restoreCompletionResponse,
```

**Comment by DaveCTurner** [comment]
Moreover the same bug exists in CCR's usage of the restore-snapshot API. Ugh.

**Comment by DaveCTurner** [comment]
The way we watch for the end of a restore seems kinda broken, or at least it relies on certain updates not being batched together which is something on which we’d rather not rely. I could make it more like how we watch for the end of a snapshot (i.e. a listener that the end-restore task explicitly completes) but that would change the behaviour slightly: today if the master fails over then we’ll sometimes (often?) return a good result anyway, whereas with my proposed change we’d have to always fail the waiting listener on a master failover. Does anyone have a strong preference for continuing to try and send a success response even after a master failover here?

**Comment by henningandersen** [comment]
Reopening this, since I think the fix reference in 0e710eee1a13cfbf7a4d8acaa0c2aa844999fd34 was not intended.

**Comment by original-brownbear** [comment]
> Does anyone have a strong preference for continuing to try and send a success response even after a master failover here?

IMO it's not worth the complexity, how many scenarios are there really where master fails over but the client stays connected to it throughout the process?

**Comment by DaveCTurner** [comment]
I'm inclined to agree, `wait_for_completion` on these long-running APIs is just naturally fragile because of potential network flakiness and the arbitrary timeout behaviour of proxies.

However Henning said (in another channel) that he'd prefer to keep this unless it's too difficult.

**Comment by original-brownbear** [comment]
>  he'd prefer to keep this unless it's too difficult.

IF we want to return a proper `RestoreInfo` still it's very difficult if not impossible to do so (if the node gets disconnected and then re-connects, how would it tell if the restore completed properly once it's been removed from the CS? I suppose we could do some magic with the recoveries or so but it hardly seems worth it).
