### ISSUE TITLE
Update API: Return noop information

### ISSUE THREAD

**Issue by snikch** [elastic/elasticsearch#9642]
It would be great if we could get an indication in the response of an `_update` request as to whether the operation was a noop or not.

Currently when passing `detect_noop`, the response has no indication of whether there was an update or not. In our system we have differing level of denormalization, and it would make life a lot easier if we could understand whether an update caused a change, so we could start updating our denormalized data.

I had a look in the code and it doesn't look like the noop information is being passed into the UpdateResponse instance, so I'm a bit out of my depth on best practice to pass this in and surface it in the response api, but if it's a feature that you'd sign off on then I'm happy to get it done.

**Comment by nik9000** [comment]
Makes sense to me.  It'd be nice also to tell if you have a script that sets the operation to a noop but one thing at a time.

I could review the implementation but I can't speak for the Elasticsearch team who'd also have to review it and merge it.

**Comment by clintongormley** [comment]
Sounds good to me.  @nik9000 - we'd be happy to review if you're up for adding it.

While we're talking about it, any reason you can think of for not making detect_noop the default in master?

**Comment by snikch** [comment]
I've added the flag for the `_update` endpoint, but just wanted to check I'm on the right track before going too far.

* I've forked from the 1.4 branch, is that the best thing to be doing?

https://github.com/snikch/elasticsearch/commits/noop-response

**Comment by nik9000** [comment]
> While we're talking about it, any reason you can think of for not making detect_noop the default in master?

@clintongormley sorry for the super late response. I think setting detect_noop to true by default in master is a good call - but its a breaking, 2.0 style change.

**Comment by nik9000** [comment]
@clintongormley #11282.

**Comment by clintongormley** [comment]
@snikch sorry for the late reply.  You should submit a PR rather than linking to a branch

**Comment by clintongormley** [comment]
@snikch sorry i see you already have (#9736)
