### ISSUE TITLE
[CI Failure] OldIndexBackwardsCompatibilityTests.testOldIndexes timeout

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#9646]
http://build-us-00.elasticsearch.org/job/es_core_1x_debian/3945/console

Test times out. Can't see any other information or a mvn reproduce command in the logs

**Comment by martijnvg** [comment]
The suite timed out again: http://build-us-00.elasticsearch.org/job/es_core_master_metal/8071

**Comment by martijnvg** [comment]
Just running this test takes 10 minutes, so it possible that it times out on a machine that runs the entire build.

**Comment by s1monw** [comment]
this hasn't failed in a long time.... closing
