### ISSUE TITLE
default_search analyzer is not applied on dynamically added fields

### ISSUE THREAD

**Issue by KPGDL** [elastic/elasticsearch#96513]
### Elasticsearch Version

8.5.1

### Java Version

_bundled_

### OS Version

Ubuntu

### Problem Description

Following official documentation configuring "default_search" does not getting appliec on new dynamic fields added to the mapping.

https://www.elastic.co/guide/en/elasticsearch/reference/current/specify-analyzer.html#specify-search-default-analyzer

### Steps to Reproduce

1. Configure "default_search" index analyzer
2. Add a sub field (via document put) to the "parent" field
`        "parent": {
          "properties": {
          }
        },`
3. See only "analyzer" is added in field stats
`
{
  "indexxxx": {
    "mappings": {
      "parent.child": {
        "full_name": "parent.child",
        "mapping": {
          "child": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            },
            "analyzer": "default"
          }
        }
      }
    }
  }
}
`

**Comment by javanna** [comment]
hi @KPGDL couuld you please post a full recreation with complete API calls instead of portions of them? That way it is way easier for us to reproduce the problem and fix it. Thanks!

**Comment by benwtrent** [comment]
closing due to lack of feedback
