### ISSUE TITLE
Static backcompat tests need better behavior with new releases

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#9652]
When we do a new release (actually when the `Version` constants are changed from snapshot to released), the static bwc tests will begin to fail since they are missing indexes for the newly released version.  However, there is a non trivial amount of time between changing the snapshot state of a version, and having a release complete.

We should either allow for leniency in the check on the "last" version of each minor release (what we do in Lucene) or build the backcompat indexes as part of the release process and check them in with the same commit that updates the snapshot state (I personally think this is better).

**Comment by clintongormley** [comment]
This has been fixed within the release process. Closing
