### ISSUE TITLE
DeleteByQueryResponse doesn't return count of deleted records

### ISSUE THREAD

**Issue by marucristiani** [elastic/elasticsearch#9654]
It would be good if DeleteByQueryResponse returns the number of deleted documents, and even better if it returns a sample of some of those who were eliminated, otherwise you have to search before delete.

**Comment by vierja** [comment]
+1

That would be cool, I'm always terrified of using that API and check the index constantly after.

**Comment by clintongormley** [comment]
Returning the count should be possible once #7052 is done.

**Comment by clintongormley** [comment]
This has been implemented in the delete by query plugin
