### ISSUE TITLE
The GET _ilm/policy API runs on the transport_worker thread

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#96568]
### Elasticsearch Version

ALL

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

The `GET _ilm/policy` API could return many records (for clusters that have
many ILM policies). 
The API runs on the `transport_worker` thread so this can cause master instability
issues ( https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/action/TransportGetLifecycleAction.java#L58 ).

This proposes moving the API on the `MANAGEMENT` thread pool and making
the API cancellable.

### Steps to Reproduce

Have thousands of ILM policies.
Repeatedly issue `GET _ilm/policy`

**Comment by DaveCTurner** [comment]
+1 but we should also make it cancellable, checking for cancellation within those inner loops too. There's no sense in continuing with a minutes-long computation when the client has already given up, and simply moving it to `MANAGEMENT` without cancellability will just cause similar problems, just jamming up the a different threadpool.
