### ISSUE TITLE
Core: add optional logging for slow low-level Directory operations

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#9656]
If we had a simple wrapper around Lucene's Directory and perhaps IndexInput/Output that you can optionally enable (off by default) that would log whenever certain operations were "slow" it can help debug cases where IO level slowness is causing cluster level slowness.

**Comment by mikemccand** [comment]
Here's a first cut: https://github.com/mikemccand/elasticsearch/commit/5b7b9a50359ac902b45a9790f317ff166a3e3f84

I added a new setting "index.store.fs.log_slow_io", defaults to false.  If you set it to true, we wrap with SlowIOLoggingDirectoryWrapper which logs if any ops take >= 50 msec.

I only log the Directory ops and not ops off of the IndexInput/Output opened from the wrapped directory for starters.

We could also extend this to do metrics tracking and expose them in node stats but I think that's a bigger change...

**Comment by rmuir** [comment]
One concern i have is when its not slowness of any individual operation, but instead the aggregate. This could happen if File.exists() takes 6ms but something calls it for 10,000 files. I know this means adding some counters but it would be great if we could do something for this case.

**Comment by bleskes** [comment]
@rmuir I believe that was part of the plan - add counters for total ops  / total time  and capture any above >Xms op . 

@mikemccand i'll do my best look asap . Can't do it in the coming hours. I think the the IndexInput/output is important for what we need now.

**Comment by mikemccand** [comment]
> One concern i have is when its not slowness of any individual operation, but instead the aggregate.

I agree this is a limitation with the "log horribly slow single events only" approach, but I'm leary of adding lots of low-level node stats here.  It would be N ops * M shards * O store.data's of raw stats.

Additional node stats have a real cost, that all future users who look at node stats will now see them, have to dig through them trying to figure out if the results are good or bad or what.

That said, since this would be opt-in, maybe it's OK?

Or, then again, if you run ES on a box with horribly slow IO ... things will be slow.  There are OS-level tools for watching IO performance...

>  I think the the IndexInput/output is important for what we need now.

Thinking about this more ... it worries me: I think wrapping at this level can impact indexing and searching performance.

**Comment by mikemccand** [comment]
Won't fix ...
