### ISSUE TITLE
The _terms_enum endpoint has no limits on the size of its prefix

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#96572]
### Elasticsearch Version

8.8

### Java Version

_bundled_

### OS Version

all

### Problem Description

`_terms_enum` queries against a `keyword` field build automata out of their prefix string, to be intersected with the terms dictionary on the relevant field.  We don't have a limit on the size of this prefix, meaning that if somebody (either accidentally or maliciously) passes a very large string here, we can run out of memory.

### Steps to Reproduce

Send a very large string as part of a `_terms_enum` request against a keyword field.

**Comment by romseygeek** [comment]
In fact, there are several places in the code where we call `MinimizationOperations.minimize()` with `Integer.MAX_VALUE` as the work limit, where we should really be passing `Operations.DEFAULT_DETERMINIZE_WORK_LIMIT` instead.

**Comment by cbuescher** [comment]
Slightly related: Regex queries [max_determinized_states](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) also allows upping this to way beyond 10000 (default) intentionally. This shouldn't be an accident but maybe we also need to add an internal cluster setting limit here to prevent misuse.

**Comment by cbuescher** [comment]
Also slightly related: security has a setting that caps automata "max_determinized_states" at 100.000 by default and seems to use the Operations.DEFAULT_DETERMINIZE_WORK_LIMIT as a minimal value: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html.

**Comment by cbuescher** [comment]
There seems to be several cases in out code where we minimize "just in case" but is is a no-op because the input automaton is already determiniztic.
