### ISSUE TITLE
`GET _alias/<alias>` returns aliases for non-matching data streams

### ISSUE THREAD

**Issue by sqren** [elastic/elasticsearch#96589]
### Elasticsearch Version

8.9.0-SNAPSHOT

### Java Version

_bundled_

### OS Version

MacOS 13.2.1 (arm64)

### Problem Description

In 8.9.0-SNAPSHOT if a data stream `my-data-stream` is created and has the alias `my-alias` it is returned when running `GET _alias/foobarbaz*`. 

My expectation is that only data streams starting with “foobarbaz” should be returned. 

### Steps to Reproduce

```
--
# Create index template
PUT _index_template/my-index-template
{
  "index_patterns": ["my-data-stream*"],
  "data_stream": { },
  "priority": 500
}

--
# Create data stream
PUT _data_stream/my-data-stream

--
# Create alias for data stream
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "my-data-stream",
        "alias": "my-alias"
      }
    }
  ]
}

--
# List aliases
GET _alias/foobarbaz*
```

This returns:

```
{
  "my-data-stream": {
    "aliases": {
      "my-alias": {}
    }
  }
}
```

**Comment by mattc58** [comment]
Just tested this on `8.11.3` and can reproduce. I ran the steps in the issue and got this result:
```
{
  "my-data-stream": {
    "aliases": {
      "my-alias": {}
    }
  }
}
```
