### ISSUE TITLE
[DOCS] File-based scripts should use "file" and not "script"

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9659]
The scripting module's example for using on-disk scripts suggests that users should use "script" and supply the script's name, but the "file" is a much better and clearer choice for on-disk scripts:

```json
          "script_score": {
            "script": "calculate-score",
            "params": {
              "my_modifier": 8
            }
          }
```

works, but it should be the much clearer:

```json
          "script_score": {
            "file": "calculate-score",
            "lang" : "groovy",
            "params": {
              "my_modifier": 8
            }
          }
```

Note: I added `lang` to it as well to emphasize the best practice here.

**Comment by clintongormley** [comment]
LGTM - go ahead and update the docs!

**Comment by javanna** [comment]
looking at other similar issues (e.g. #10011), I am confused on whether it should be `file` or `script_file`. In any case, we should replace `script` as that only works in 1.x for bw comp reasons.

**Comment by javanna** [comment]
@pickypg are you working on this? If not I am happy to take this over, just let me know ;)

**Comment by GlenRSmith** [comment]
In master, it's already "script_file", which does seem preferred, as @javanna 's comment points out.
This issue can probably be closed, then, unless it's waiting for the "lang" param addition.
Going to generate a pull request for that.

**Comment by javanna** [comment]
Thanks @GlenRSmith ! Indeed this can be closed, was addressed here: https://github.com/elastic/elasticsearch/commit/7d3856c9d33111534ec20fdad7584ccf509578b6#diff-1ffc331caacd3f8a44aa8f4eab953ed3 .

**Comment by hyhsoftware** [comment]
but how can i use it by java api?  i cannot find the method, do you have some idea?

**Comment by markwalkom** [comment]
@hyhsoftware please ask your question on the mailing list - https://groups.google.com/forum/#!forum/elasticsearch
