### ISSUE TITLE
ElasticSearch Docker Volume Bind Mount Errors

### ISSUE THREAD

**Issue by joshxyzhimself** [elastic/elasticsearch#96601]
### Elasticsearch Version

8.8.0

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

Ubuntu 22.04

### Problem Description

The docker page is a mess.

When you docker volume mount, you get permission errors on both data dir and logs dir.

- https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user

> elasticsearch-1  | Could not rename log file 'logs/gc.log' to 'logs/gc.log.03' (Permission denied).
> elasticsearch-1  | {"@timestamp":"2023-06-06T09:41:21.503Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"9a8a73e358ed","elasticsearch.cluster.name":"elasticsearch","error.type":"java.lang.IllegalStateException","error.message":"failed to obtain node locks, tried [/usr/share/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?","error.stack_trace":"java.lang.IllegalStateException: failed to obtain node locks, tried [/usr/share/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:291)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.node.Node.<init>(Node.java:483)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.node.Node.<init>(Node.java:327)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\nCaused by: java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:236)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:204)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:283)\n\t... 5 more\nCaused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/node.lock\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\tat java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:833)\n\tat org.apache.lucene.core@9.6.0/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:94)\n\tat org.apache.lucene.core@9.6.0/org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)\n\tat org.apache.lucene.core@9.6.0/org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)\n\tat org.elasticsearch.server@8.8.0/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:229)\n\t... 7 more\n\tSuppressed: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/node.lock\n\t\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)\n\t\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\t\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\t\tat java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)\n\t\tat java.base/java.nio.file.Files.newByteChannel(Files.java:379)\n\t\tat java.base/java.nio.file.Files.createFile(Files.java:657)\n\t\tat org.apache.lucene.core@9.6.0/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:84)\n\t\t... 10 more\n"}

### Steps to Reproduce

```
version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    ports:
      - 9200:9200
    volumes:
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/volumes/elasticsearch/logs:/usr/share/elasticsearch/logs
```

**Comment by mark-vieira** [comment]
This sounds like there are insufficient permissions to the logs directory. Did you give write access to the appropriate gid?

**Comment by joshxyzhimself** [comment]
Fixed on host side.

```sh
# directories
mkdir -p ./docker/volumes/elasticsearch
mkdir -p ./docker/volumes/elasticsearch/docs
mkdir -p ./docker/volumes/elasticsearch/logs

# permissions
chmod -R 777 ./docker/volumes/
```

Getting this persistent warning though, any ideas how to disable them?

```sh

805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.124Z", "log.level": "WARN", "message":"SLF4J: No SLF4J providers were found.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.130Z", "log.level": "WARN", "message":"SLF4J: Defaulting to no-operation (NOP) logger implementation", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.130Z", "log.level": "WARN", "message":"SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.132Z", "log.level": "WARN", "message":"SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.132Z", "log.level": "WARN", "message":"SLF4J: Ignoring binding found at [jar:file:///usr/share/elasticsearch/modules/repository-azure/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
```

**Comment by mark-vieira** [comment]
> Getting this persistent warning though, any ideas how to disable them?

Those are normal and can be safely ignored.

**Comment by yashwantram97** [comment]
> Fixed on host side.
> 
> ```shell
> # directories
> mkdir -p ./docker/volumes/elasticsearch
> mkdir -p ./docker/volumes/elasticsearch/docs
> mkdir -p ./docker/volumes/elasticsearch/logs
> 
> # permissions
> chmod -R 777 ./docker/volumes/
> ```
> 
> Getting this persistent warning though, any ideas how to disable them?
> 
> ```shell
> 805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.124Z", "log.level": "WARN", "message":"SLF4J: No SLF4J providers were found.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
> 805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.130Z", "log.level": "WARN", "message":"SLF4J: Defaulting to no-operation (NOP) logger implementation", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
> 805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.130Z", "log.level": "WARN", "message":"SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
> 805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.132Z", "log.level": "WARN", "message":"SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
> 805a-elasticsearch-1  | {"@timestamp":"2023-06-07T10:07:12.132Z", "log.level": "WARN", "message":"SLF4J: Ignoring binding found at [jar:file:///usr/share/elasticsearch/modules/repository-azure/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"stderr","elasticsearch.node.name":"7a97cbc72216","elasticsearch.cluster.name":"docker-cluster"}
> ```

Can you please share the complete docker-compose file

**Comment by josh-i386g** [comment]
Example docker compose file is here: https://github.com/elastic/elasticsearch/issues/85463#issuecomment-2299705984
