### ISSUE TITLE
Optimisation opportunities in LuceneVerifyingIndexOutput

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#96614]
As mentioned in https://github.com/elastic/elasticsearch/pull/96216, `LuceneVerifyingIndexOutput` always copies the last chunk byte-by-byte. This might be a pretty big chunk. We should be able to copy all the bytes up to the start of the checksum in bulk (and then I guess bulk-copy the checksum too not that this matters so much).

In the same area, `LuceneVerifyingIndexOutput` is the only subclass of `VerifyingIndexOutput` and there's no need for it to be an inner class of `Store`. `VerifyingIndexInput` also doesn't need to be an inner class.

**Comment by rhluo** [comment]
@DaveCTurner Hi, I'm very glad to see your issue. I wish to share with you a new solution. As follows: 
speed up the process in LuceneVerifyingIndexOutput [#96670](https://github.com/elastic/elasticsearch/pull/96670)
