### ISSUE TITLE
Processor to clone messages to remote system

### ISSUE THREAD

**Issue by secoprooster** [elastic/elasticsearch#96636]
### Description

**User Story**
As a user I would like to be able to send a duplicate message received by an Elasticsearch pipeline using a processor that enables me to send to one or many remote destinations including Elasticsearch.

**Intended Outcome**
The original unparsed "message" field (or any specified field) is sent to one or many remote systems using a protocol of the users choice, preferably syslog using RFC5424 format or a raw TCP stream supporting TLS optionally.

**Benefits of Feature**
- Provides the end user more flexibility without introducing extra components into the solution (e.g. fronting the platform with Logstash or another solution that allows you to create multiple "outputs" - which would achieve the intended outcome but with an extra service required and adjustment of outputs for agents and other log forwarding solutions already sending direct to Elasticsearch)
- Increase flexibility for pipeline configuration, enabling the ability to send specific field data at various stages of a pipeline to a remote system [e.g. providing a way to perform some additional processing of a raw message earlier in the pipeline before sending a specific field data to a remote destination system]
- Enables customers who have transitioned to Elastic Agent with direct Elasticsearch output configurations to feed data received on Elasticsearch ingest pipelines, in near real time to remote destinations as per processor configuration without needing to update log source configurations to send to multiple destinations [essentially allowing Elasticsearch to also be used as a central ingestion point and forwarder for specific use-cases].

**Alternate ways to achieve this currently**
Introduce Logstash as an extra component in the overall deployment and configuration of elastic agents to output direct to Logstash for then on-forwarding to Elasticsearch and remote destinations using multiple Logstash outputs.

Configure log sources to send to multiple destinations [problematic in large multi-tenant environments where getting changes made to hundreds/thousands of systems may be subject to cost implications] or where source systems may have exceeded the number of remote destinations that logs can be sent to e.g. limitations on upstream appliances etc.

Other various third party/bespoke solutions fronting Elasticsearch to achieve the outcome.

It would be awesome if this feature request could be reviewed for feasibility. I'm sure there are many more useful use-cases here that simplifies configuration and reduces overall complexity with reduced management overhead if this functionality could be a dedicated forwarding processor that can be used within an Elasticsearch pipeline configuration.

Thanks heaps
Andrew

**Comment by dakrone** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/56769

**Comment by tylerperk** [comment]
@secoprooster Thanks for submitting this idea with such a well thought out writeup. We discussed it within the team and at this time we don't see such a forwarding capability fitting within the scope of Elasticsearch capabilities. As you mentioned, there are alternative ways to accomplish the same goals (Logstash, etc) which you rightly pointed out do have some downsides and additional burden, but we don't see that outweighing the downsides of adding this complexity into Elasticsearch. It is possible there might be other lighter weight options in the future but they wouldn't be within the Elasticsearch database itself, as proposed above.

**Comment by secoprooster** [comment]
Excellent, thanks for taking the time to review and consider this feature request.  Much appreciated. Happy of this to be closed out. Agree, the complexities involved in introducing such a feature when their are alternate already established solutions out there to achieve the desired outcome would probably be more duplication of effort and not a good use of time. Will design with other components in mind to achieve the outcome :)

Regards
