### ISSUE TITLE
Lua for scripting

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#9665]
You might want to have a look at Lua for scripting.  In its standard incarnation its quite sandboxable.  [We use it.](https://en.wikipedia.org/w/index.php?search=module%3A&title=Special%3ASearch&go=Go)  We haven't had security issues with it.

The trouble is that its the C runtime that does that for us.  I see two Java runtimes:
* http://sourceforge.net/projects/luaj/
* https://github.com/krka/kahlua2
but I have no idea how sandboxed they are.

**Comment by s1monw** [comment]
I am pretty convinced that all general purpose languages have the same problems when it comes to java security. We will evaluate the possibilities that we have here and will take our time to make a good move along the lines. I think before we think about re-enabling dynamic scripting we will need to fix other problems or add better APIs / Services that allow users to pass their scripts in a safe way. I will close this issue for now (we can reopen if there times are changing on the security end).

thanks for providing the idea.

**Comment by nik9000** [comment]
I certainly don't have the time or background to prove that any script
interpreters are safe. Our security folks validated the traditional lua
interpreter but I doubt any JVM ones are as good.

Someone seems to have taken a crack at it:
https://github.com/empirephoenix/Hardened-Luaj
I'm not sure how complete it is.

I winder if there are any other projects that do this on the JVM.

**Comment by yehosef** [comment]
+this would be great.  We already use Lua in Redis and Aerospike.

**Comment by nik9000** [comment]
Lua would probably be best for people used to redis but it isn't a clear
win because none of the java backed luas are designed to be easily
embeddable as the c backed lua. They don't have good sandboxes or memory
limits or cpu limits iirc. I remember someone starting down that route for
a mincraft plugin but I don't remember it being finished. Its been a few
months since I looked so things might have changed or I might be
remembering wrong.

+this would be great. We already use Lua in Redis and Aerospike.

—
Reply to this email directly or view it on GitHub
<https://github.com/elastic/elasticsearch/issues/9665#issuecomment-124076031>
.

**Comment by clintongormley** [comment]
Closing in favour of #13084
