### ISSUE TITLE
Percentage calculation for stats bucket agg

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#96680]
### Description

I have seen this request/question pop up a few times, eg https://github.com/elastic/elasticsearch/issues/89435, https://discuss.elastic.co/t/using-doc-count-to-calculate-percentage-after-aggregation/243611/2 and https://discuss.elastic.co/t/how-to-calculate-percentage-of-a-field-over-all-documents-present-in-index/334544.

Does it make sense to have the option to have Elasticsearch calculate this in something like the stats bucket aggregation?

**Comment by wchaparro** [comment]
not planned
