### ISSUE TITLE
java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-core-4.10.2.jar

### ISSUE THREAD

**Issue by florentgarin** [elastic/elasticsearch#9674]
Just after a fresh install of elasticsearch on Ubuntu 14.10 64bit server from repo deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main, we are not able to create an index:

Caused by: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-core-4.10.2.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.lucene.util.SPIClassIterator.loadNextProfile(SPIClassIterator.java:92)
	... 22 more
[2015-02-11 22:53:33,145][DEBUG][action.admin.indices.create] [Valkin] [demo] failed to create
org.elasticsearch.indices.IndexCreationException: [demo] failed to create index
	at org.elasticsearch.indices.InternalIndicesService.createIndex(InternalIndicesService.java:303)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:382)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:329)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.index.codec.postingsformat.PostingFormats
	at org.elasticsearch.index.codec.CodecModule.configurePostingsFormats(CodecModule.java:126)
	at org.elasticsearch.index.codec.CodecModule.configure(CodecModule.java:178)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.InternalIndicesService.createIndex(InternalIndicesService.java:299)

As a workaround we created a symbolic link lucene-core-4.10.2.jar => lucene-core-4.10.3.jar

Details about the service:
{
  "status" : 200,
  "name" : "Vibraxas",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.3",
    "build_hash" : "36a29a7144cfde87a960ba039091d40856fcb9af",
    "build_timestamp" : "2015-02-11T14:23:15Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

**Comment by clintongormley** [comment]
HI @florentgarin 

It sounds like you're loading classes from different versions somehow. Perhaps the installation went wrong and you ended up with mixed libraries in the same path?  Or perhaps you're using a plugin that hasn't been updated?

I'd try uninstalling and reinstalling and see if that fixes it.

**Comment by florentgarin** [comment]
The machine was a fresh Ubuntu server installation + ansible script that
installs our software (mostly std apt-get cmd). No weird manipulation on
the server.

2015-02-12 14:08 GMT+01:00 Clinton Gormley <notifications@github.com>:

> HI @florentgarin <https://github.com/florentgarin>
>
> It sounds like you're loading classes from different versions somehow.
> Perhaps the installation went wrong and you ended up with mixed libraries
> in the same path? Or perhaps you're using a plugin that hasn't been updated?
>
> I'd try uninstalling and reinstalling and see if that fixes it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9674#issuecomment-74067419>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by clintongormley** [comment]
Hi @florentgarin 

We've just tried the latest debian package on Ubuntu, and all works correctly.  Could you try again please?

**Comment by jpountz** [comment]
Could you also list the content of `/usr/share/elasticsearch/lib/`?

**Comment by florentgarin** [comment]
drwxr-xr-x 3 root root     4096 févr. 11 23:14 ./
drwxr-xr-x 4 root root     4096 févr. 11 18:14 ../
-rw-r--r-- 1 root root 13527606 févr. 11 15:25 elasticsearch-1.4.3.jar
-rw-r--r-- 1 root root  7265222 févr. 11 15:25 groovy-all-2.3.2.jar
-rw-r--r-- 1 root root   914597 févr. 11 15:25 jna-4.1.0.jar
-rw-r--r-- 1 root root   794991 févr. 11 15:25 jts-1.13.jar
-rw-r--r-- 1 root root   489884 févr. 11 15:25 log4j-1.2.17.jar
-rw-r--r-- 1 root root  1699874 févr. 11 15:25
lucene-analyzers-common-4.10.3.jar
lrwxrwxrwx 1 root root       22 févr. 11 23:14 lucene-core-4.10.2.jar ->
lucene-core-4.10.3.jar
-rw-r--r-- 1 root root  2562626 févr. 11 15:25 lucene-core-4.10.3.jar
-rw-r--r-- 1 root root    75488 févr. 11 15:25 lucene-expressions-4.10.3.jar
-rw-r--r-- 1 root root   107782 févr. 11 15:25 lucene-grouping-4.10.3.jar
-rw-r--r-- 1 root root   138281 févr. 11 15:25 lucene-highlighter-4.10.3.jar
-rw-r--r-- 1 root root    64019 févr. 11 15:25 lucene-join-4.10.3.jar
-rw-r--r-- 1 root root    36076 févr. 11 15:25 lucene-memory-4.10.3.jar
-rw-r--r-- 1 root root    97172 févr. 11 15:25 lucene-misc-4.10.3.jar
-rw-r--r-- 1 root root   213026 févr. 11 15:25 lucene-queries-4.10.3.jar
-rw-r--r-- 1 root root   391514 févr. 11 15:25 lucene-queryparser-4.10.3.jar
-rw-r--r-- 1 root root   119448 févr. 11 15:25 lucene-sandbox-4.10.3.jar
-rw-r--r-- 1 root root   126792 févr. 11 15:25 lucene-spatial-4.10.3.jar
-rw-r--r-- 1 root root   179007 févr. 11 15:25 lucene-suggest-4.10.3.jar
drwxr-xr-x 2 root root     4096 févr. 11 18:14 sigar/
-rw-r--r-- 1 root root   102177 févr. 11 15:25 spatial4j-0.4.1.jar



2015-02-12 14:28 GMT+01:00 Adrien Grand <notifications@github.com>:

> Could you also list the content of /usr/share/elasticsearch/lib/?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9674#issuecomment-74069900>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by florentgarin** [comment]
The bad lib seems to be loader from META-INF/services standard mecanism. It
probably references the old version (4.10.2 instead of 4.10.3).

Caused by: java.util.ServiceConfigurationError: Error loading SPI class
list from URL:
jar:file:/usr/share/elasticsearch/lib/lucene-core-4.10.2.jar!/META-INF/services/org.apa
che.lucene.codecs.PostingsFormat




2015-02-12 14:28 GMT+01:00 Clinton Gormley <notifications@github.com>:

> Hi @florentgarin <https://github.com/florentgarin>
>
> We've just tried the latest debian package on Ubuntu, and all works
> correctly. Could you try again please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9674#issuecomment-74069815>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by jpountz** [comment]
Not sure how it could cause the error since this service file references class names but no particular JAR version.

Can you try to do the following steps and tell us when things go wrong:
 1. uninstall elasticsearch
 2. remove existing data: rm -r /var/lib/elasticsearch/*
 3. verify that /usr/share/elasticsearch does not exist
 4. verify that no java process is running (especially elasticsearch)
 5. reinstall elasticsearch
 6. start elasticsearch
 7. make sure that there is a single elasticsearch process running
 7. try to create an index: curl -XPUT 'localhost:9200/demo'
 8. try to index a document: curl -XPUT 'localhost:9200/demo/type/1' -d '{}'

And if you still have errors, can you copy and paste the command-line that runs elasticsearch (essentially the output of `ps aux | grep java`)? Thanks

**Comment by florentgarin** [comment]
"Not sure how it could cause the error since this service file references
class names but no particular JAR version."
...not exactly are sure you do not reference jar directly inside Manifest
class-path entry?

2015-02-12 16:55 GMT+01:00 Adrien Grand <notifications@github.com>:

> Not sure how it could cause the error since this service file references
> class names but no particular JAR version.
>
> Can you try to do the following steps and tell us when things go wrong:
>
>    1. uninstall elasticsearch
>    2. remove existing data: rm -r /var/lib/elasticsearch/*
>    3. verify that /usr/share/elasticsearch does not exist
>    4. verify that no java process is running (especially elasticsearch)
>    5. reinstall elasticsearch
>    6. start elasticsearch
>    7. make sure that there is a single elasticsearch process running
>    8. try to create an index: curl -XPUT 'localhost:9200/demo'
>    9. try to index a document: curl -XPUT 'localhost:9200/demo/type/1' -d
>    '{}'
>
> And if you still have errors, can you copy and paste the command-line that
> runs elasticsearch (essentially the output of ps aux | grep java)? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/issues/9674#issuecomment-74094636>
> .
>



-- 
Florent Garin
DocDoku - http://www.docdoku.com
digital enterprise applications
37 rue Lancefoc
31000 Toulouse
Mobile : + 336 81 91 01 71
Tel : + 335 61 72 24 09
DocDokuPLM - http://www.docdokuplm.com - OWF Innovation Awards 2012 winner

**Comment by jpountz** [comment]
Yes, neither the elasticsearch nor the lucene jars have classpath entries in their manifest. The classpath is only set on the command-line (which is the reason why I asked for the java command in the previous message to see how the classpath is set).

**Comment by florentgarin** [comment]
oky fine. I asked because I remembered that Apache POI make use of classpath entries in the manifest.
below the command line:
elastic+  5879  0.2 16.3 3509956 334972 ?      Sl   févr.11   2:51 /usr/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.4.3.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch

**Comment by nemonster** [comment]
Also happening on the rpm distribution.  Haven't done the full reinstallation yet though.

**Comment by clintongormley** [comment]
Hi @florentgarin 

Was this issue resolved by the release of v1.4.4 last week?

**Comment by florentgarin** [comment]
seems to be fixed on 1.4.4
