### ISSUE TITLE
Provide a way to get to the "_id" as part of an update

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9680]
It doesn't look like there is a way to get to the _id field as part of an update from scripting (https://github.com/elasticsearch/elasticsearch/blob/ca4f27f40ea63a3a0435beca8a5b127fced64753/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L94).
When referencing it using `ctx._id`, it returns a null value.  Same for ctx._type and ctx._index.

**Comment by clintongormley** [comment]
This was fixed in 1.5 with https://github.com/elastic/elasticsearch/pull/5724
