### ISSUE TITLE
Performance problems after upgrade to 1.4.2

### ISSUE THREAD

**Issue by nikolaialex** [elastic/elasticsearch#9681]
A few days ago I have upgraded an cluster from `1.2.x` to version `1.4.2`. Since the upgrade, the performance dropped significant. Especially calling `/_nodes` takes up to a minute.

As suggested by @kimchy on [twitter](https://twitter.com/kimchy/status/565622790037204993), I have collected some `hot_thread` stats during calling `/_cat/nodes`. The collected data is [here](https://gist.github.com/nikolaialex/c4cadd31521ea760ac69).

### Calling /_cat/nodes
```
while true; do curl myserver:9200/_cat/nodes; done
```

### Collecting thread data
```
while true; do
date
curl myserver:9200/_nodes/hot_threads -s  | grep usage
done
```

### Cluster specs
The cluster runs on pretty old hardware, but was snappy before the update.

+ 2 blades with 16GB and 2 dual cores
+ 5 million docs per index
+ 8GB per index
+ index are created monthly
+ 5 shards per index
+ 1 replica

**Comment by bleskes** [comment]
Thanks @nikolaialex . The stack traces in the hot_threads would help pin point what exactly is taking long. Right now those are filtered out. Any chance you can run this again and share the complete output? a couple of iteration would be enough.

**Comment by nikolaialex** [comment]
Sorry, I will upload the unfiltered logs next week. I am back in office on Wednesday.

**Comment by bleskes** [comment]
@nikolaialex thx. your help is appreciated.

**Comment by drewr** [comment]
@nikolaialex Thanks for the report. Have you seen anything else change besides `/_cat/nodes` slowing down?

**Comment by nikolaialex** [comment]
Hard to say, which of the gazillion endpoints deteriorated. I will try to check some. Any suggestions? Which endpoints hit disk or the whole cluster? Maybe it´s just a problem in these areas. The root page for example is delivered fast.

Users reported, that the search performance dropped in Kibana. Not as much as  `/_nodes`, but noticeable.

Are there any performance or smoke tests or tools, that I can run against the cluster?

**Comment by aanuprab** [comment]
I agree with @nikolaialex I updated es to 1.4.2 and my query performances are slower compared to 1.3.4

**Comment by clintongormley** [comment]
@nikolaialex any more info that you can provide?  Hard data is a bit thin on the ground in this ticket ;)

**Comment by nikolaialex** [comment]
Sorry for the delay, I was out of the office. [Here](https://gist.github.com/nikolaialex/21db0c4ba7ce19490165) you can find the hot thread logs, that I´ve collected. Hope it helps.

**Comment by clintongormley** [comment]
HI @nikolaialex 

Sorry for the delay. This looks like an issue that has been fixed by caching FS lookups.
thanks
