### ISSUE TITLE
How to highlight multifields? Iis there a way to highlight all results with the same multifield (same source, different analyzers) - Multi-fields with multiple analyzers 

### ISSUE THREAD

**Issue by martinenkoEduard** [elastic/elasticsearch#96840]
### Elasticsearch Version

1

### Java Version

_bundled_

### OS Version

1

### Problem Description

How to highlight multifield? Is there a way to highlight all results with the same multifield (same source, different analyzers)?
Multi-fields with multiple analyzers

### Steps to Reproduce

1

**Comment by mayya-sharipova** [comment]
Thanks very much for your interest in Elasticsearch.

  This appears to be a user question, and we'd like to direct these kinds
  of things to the [forums](https://discuss.elastic.co/). If you can stop
  by there, we'd appreciate it. This allows us to use GitHub for verified
  bug reports, feature requests, and pull requests.

  There's an active community in the [forums](https://discuss.elastic.co/)
  that should be able to help get an answer to your question. As such, I
  hope you don't mind that I close this.

**Comment by mayya-sharipova** [comment]
@martinenkoEduard But just to answer short, `fvh` highlighter has `matched_fields` option for this use case. Check our [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html) for an example how to use  the `matched_fields` option.
