### ISSUE TITLE
Docker Image is massive (1.3 GB)

### ISSUE THREAD

**Issue by kale1d0code** [elastic/elasticsearch#96858]
### Elasticsearch Version

8.8.0

### Java Version

_bundled_

### OS Version

ubuntu

### Problem Description

The offical docker image weighs 1.3 GB.
this may be due to it being based on Ubuntu.
ubuntu is a great operating system to run end-user systems and prehaps servers but it is not a great fit for containerisation due to its huge size.

I recommend creating an alpine version or switching to another, slimmer base image

### Steps to Reproduce

docker pull elasticsearch

**Comment by mark-vieira** [comment]
There are a few things that contribute to the size of the docker image that are unrelated to the base image being used. In any case, there are currently no plans to change the base Docker image but we might revisit this in the future.
