### ISSUE TITLE
Allow for Build information extension

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#96861]
### Description

Build.java which currently lives in server contains information about hash (git revision) that is contained inside elasticserach-X.X.X.jar metadata.
This information would not be correct if elasticsearch would be used as a submodule. We would like to see a commit hash from a git project that is using elasticsearch as a module (i.e. serverless repo).

Perhaps we could move Build.java to its own module and allow it to be overriden when elasticsearch is used as submodule (like it is in serverless repo)?

**Comment by pgomulka** [comment]
My understanding was that we could just override the module and pretty much the same logic would work

**Comment by mark-vieira** [comment]
Addressed by #97768.
