### ISSUE TITLE
Cluster bootstrap warning incorrectly emitted for `discovery.type: single-node`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#96874]
In #86101 we added a warning if bootstrapping was incorrectly configured (and in #92744 we changed it to be emitted every 12h). The logic introduced doesn't take account of `discovery.type: single-node`, so explicitly-single-node clusters will always emit this warning even though they are correctly configured.

Relates https://github.com/elastic/elasticsearch/issues/58393.

**Comment by ekrylovich** [comment]
I would like to work on this issue

**Comment by ekrylovich** [comment]
ah, it looks like there is already PR created by other contributor. stepping back)
