### ISSUE TITLE
Dense vector dimension limitations should go much higher beyond 2048, better more than 10000

### ISSUE THREAD

**Issue by firezym** [elastic/elasticsearch#96902]
### Description

As the official description: `Number of vector dimensions. Can’t exceed 1024 for indexed vectors ("index": true), or 2048 for non-indexed vectors.` and in technical preview `The number of dimensions for indexed vectors can be extended up to 2048`. 

Is there a possibility to let go the limitation? Open source llms develop very fast. Many 7B models can run on single GPU now. Some of the popular models' last layer dim can be as much as 4096. Can ES dev team break the indexed dim ceiling to at least 5000? That will make your product competitive to a lot of the current popular vector bases. I don't think machine capability is an issue to consider.

**Comment by benwtrent** [comment]
> Open source llms develop very fast. Many 7B models can run on single GPU now. Some of the popular models' last layer dim can be as much as 4096.

What is the zero shot performance of retrieval for these models?

One model released very recently: https://github.com/microsoft/unilm/tree/master/e5

Is nowhere near this expensive and performs excellently in zero-shot first stage retrieval.

**Comment by benwtrent** [comment]
Dimension limit in ES is 4096 for float and byte. 

With new `bit` vector support, the dimension limit for bits is `32768`.

closing this issue.
