### ISSUE TITLE
Concurrent search segments for particular queries.

### ISSUE THREAD

**Issue by vsop-479** [elastic/elasticsearch#96903]
### Description

Is there any problem if ES gives an executor to Lucene's IndexSearcher, for queries which only need score(without other collector),
to support concurrent search?
In my opinion, concurrent search can gives the correct result for these queries.

**Comment by javanna** [comment]
Hi @vsop-479 it is not a matter of correctness but mostly a matter of completeness, in that when we discussed this, it felt like aggs were the part that could benefit inter-segment search concurrency the most. That said, we have been working on this, and it may be that we will enable concurrency only in some cases once we are ready. This effort is tracked in #80693 , hence I am closing this issue as a duplicate.
