### ISSUE TITLE
[GEO] geoshape filter ignores tree_levels and precision parameter mappings

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#9691]
The docs at http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-filter.html state that the ```geo_shape``` filter will "...use the same PrefixTree configuration as defined for the field mapping."  Unfortunately at query time the ```precision``` and ```tree_levels``` parameters are overridden by the ```distance_error_pct```  This parameter is used as a percentage of the shortest diagonal distance (in degrees) of the bounding box for the defined filter shape and has the unfortunate side effect of degrading accuracy for larger filters (worst at the equator).  This leads to the results containing a number of false positives. 

An example of this can be seen at the following gist https://gist.github.com/nknize/abbcb87f091b891f85e1

A work around is to set the ```distance_error_pct``` to something reasonable based on the size of your filter and location of your data.  For the worst case, (i.e., you expect a LOT of global filtering over global data spanning the map - and majority is at the equator) then set ```distance_error_pct``` to 0 and ```tree_levels``` to 32.  Doing this will force the filter to use a tree level of 32 which will give ~1m accuracy for results at the equator.  Note that this will also increase memory usage and the overall size of the index.

**Comment by jacobstr** [comment]
> Unfortunately at query time the precision and tree_levels parameters are overridden by the distance_error_pct

To me *query time* suggests when you're POST'ing to `:9200/index/_search` but the docs give no indication that `distance_error_pct` is a valid property for a [GeoShape query](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/querying-geo-shapes.html). `distance_error_pct` is discussed in the section on indexing.
