### ISSUE TITLE
org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed failed on main

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#96919]
### CI Link

https://gradle-enterprise.elastic.co/s/g5lnen3vqybaa

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed" \   -Dtests.seed=BFEB6603081AAC8A \   -Dtests.locale=lv \   -Dtests.timezone=America/Cancun \   -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

10:13:46 REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed" -Dtests.seed=BFEB6603081AAC8A -Dtests.locale=lv -Dtests.timezone=America/Cancun -Druntime.java=20
10:13:46 
10:13:46 org.elasticsearch.health.node.DiskHealthIndicatorServiceIT > testRed FAILED
10:13:46     java.lang.AssertionError: 
10:13:46     Expected: <RED>
10:13:46          but: was <GREEN>
10:13:46         at __randomizedtesting.SeedInfo.seed([BFEB6603081AAC8A:955469E053FFD5D6]:0)
10:13:46         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
10:13:46         at org.junit.Assert.assertThat(Assert.java:956)
10:13:46         at org.junit.Assert.assertThat(Assert.java:923)
10:13:46         at org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed(DiskHealthIndicatorServiceIT.java:62)

**Comment by luigidellaquila** [comment]
more failures https://gradle-enterprise.elastic.co/s/jxuiedf53v7o4/tests/:server:internalClusterTest/org.elasticsearch.health.node.DiskHealthIndicatorServiceIT/testRed?top-execution=1
