### ISSUE TITLE
org.elasticsearch.search.internal.ShardSearchRequestTests.testForceSyntheticUnsupported failed in main

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#96922]
### CI Link

	https://gradle-enterprise.elastic.co/s/ul5kocplwtqhi

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.search.internal.ShardSearchRequestTests.testForceSyntheticUnsupported" \   -Dtests.seed=AB03FB86BD3363F4 \   -Dtests.locale=el-GR \   -Dtests.timezone=Universal \   -Druntime.java=17 \   -Dtests.fips.enabled=true

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

11:00:14 REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.internal.ShardSearchRequestTests.testForceSyntheticUnsupported" -Dtests.seed=AB03FB86BD3363F4 -Dtests.locale=el-GR -Dtests.timezone=Universal -Druntime.java=17 -Dtests.fips.enabled=true
11:00:14 
11:00:14 org.elasticsearch.search.internal.ShardSearchRequestTests > testForceSyntheticUnsupported FAILED
11:00:14     org.junit.ComparisonFailure: expected:<[cannot serialize [sub_searches] to version [8030099]]> but was:<[force_synthetic_source is not supported before 8.4.0]>
11:00:14         at __randomizedtesting.SeedInfo.seed([AB03FB86BD3363F4:47D6818C8F377732]:0)
11:00:14         at org.junit.Assert.assertEquals(Assert.java:115)
11:00:14         at org.junit.Assert.assertEquals(Assert.java:144)
11:00:14         at org.elasticsearch.search.internal.ShardSearchRequestTests.testForceSyntheticUnsupported(ShardSearchRequestTests.java:270)

**Comment by javanna** [comment]
Same as #96910 .
