### ISSUE TITLE
Leader not elected for 8 minutes after existing leader shutdown.

### ISSUE THREAD

**Issue by bseibel** [elastic/elasticsearch#9694]
We have an 11 node cluster, this morning we noticed one of the nodes with a fairly full heap was spending far too much time in gc compared to the others, this happened to be our master node, so I issued it a shutdown (via: /_cluster/nodes/_local/_shutdown) so that it could be quickly restarted. 

I had expected, like many times before that a new leader would be very quickly elected and we wouldnt incur an outage, however this time all nodes just started throwing the no known master exception for about 8 minutes.

In my tweet to @kimchy I had thought it wasn't until the original master came back up that a new leader was elected, it looks like the original master was back up far before a new leader was chosen.

I have the logs of the original master and the new master, I would rather email them than put them up publicly if I could be directed where to send them.

**Comment by bleskes** [comment]
@bseibel if you can e-mail them to me (first dot last name at elasticsearch.com) it would be great. Also can you indicate which ES version this concerns?

**Comment by bleskes** [comment]
@bseibel just saw the tweet. Apparently 1.4.2. Curious to see the logs.

**Comment by clintongormley** [comment]
No further info. Closing for now
