### ISSUE TITLE
es 1.4.2 - Geo filter does not work

### ISSUE THREAD

**Issue by aanuprab** [elastic/elasticsearch#9700]
Updated es to 1.4.2 - Geo filter does not work. Even tried the basic example listed on es website and that does not work either.

This used to work in previous versions.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html

Also overall performance of 1.4.2 is slower than es 1.2 and es 1.3.4

**Comment by clintongormley** [comment]
@aanuprab Please can you provide a complete recreation of what exactly isn't working.  "Doesn't work" isn't sufficient to diagnose problems.

**Comment by clintongormley** [comment]
No further info. Closing
