### ISSUE TITLE
.yaml extension doesn't work for elasticsearch?

### ISSUE THREAD

**Issue by devinrsmith** [elastic/elasticsearch#9706]
I was trying to figure out why my CORS setting weren't getting picked up, and it turned out that my file `/usr/share/elasticsearch/config/elasticsearch.yaml` wasn't being parsed (I verified by creating junk in the file, and elasticsearch happily came up). As soon as I moved the file to `/usr/share/elasticsearch/config/elasticsearch.yml` things started working.

I'm not sure if this is expected behavior. Note though, my `/usr/share/elasticsearch/config/logging.yaml` was getting picked up just fine. Either way, it seems like there should at least be consistency between configuration file extensions.

**Comment by ericlee996** [comment]
Hey folks, I'm looking for a simple fix to contribute to get warmed up. Is anyone planning on fixing this? If not I'll grab it.

Thanks!

Eric.

**Comment by aleph-zero** [comment]
Hey @ericlee996. Thanks for offering, but we already have a PR about to go in to fix this issue.  

I recommend looking at the open issues with these attributes: is:open is:issue label:"low hanging fruit". There are quite a few there that should be suitable for getting your feet wet. 

Have fun.

**Comment by ericlee996** [comment]
Will do, thanks!

Eric.

On Wed, May 6, 2015 at 5:55 PM, Andrew Selden <notifications@github.com>
wrote:

> Hey @ericlee996 <https://github.com/ericlee996>. Thanks for offering, but
> we already have a PR about to go in to fix this issue.
>
> I recommend looking at the open issues with these attributes: is:open
> is:issue label:"low hanging fruit". There are quite a few there that should
> be suitable for getting your feet wet.
>
> Have fun.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/9706#issuecomment-99663444>
> .
>



-- 
WonderAffect

http://www.wonderaffect.com
http://www.wonderaffect.com/blog
