### ISSUE TITLE
JAVA_HOME is not set error

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#9715]
Hi,

When installing ES 1.4.3 using RPM, we get an error JAVA_HOME is not set. This is despite the fact that JAVA_HOME path is correctly set. 

It gets fixed once we explicitly set JAVA_HOME path in /etc/sysconfig/elasticsearch.

**Comment by markwalkom** [comment]
How did you install java?
Where is it installed?

**Comment by nithyanv** [comment]
Hi,

The path, as displayed using 
>echo $JAVA_HOME
> /usr/java/jdk1.7.0_67-cloudera

The same path was then again set by editing the following 
>vi /etc/sysconfig/elasticsearch
> JAVA_HOME=/usr/java/jdk1.7.0_67-cloudera

**Comment by clintongormley** [comment]
This has been fixed in recent versions
