### ISSUE TITLE
Improve Performance of Script-less Runtime Fields when the Backing Field is Indexed

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#97187]
### Description

Elasticsearch runtime fields support script-less shadowing.

```json
"runtime_mappings": {
  "okta.target.alternate_id": {
    "type": "keyword"
  }
}
```

The current implementation of this seems to be inefficient when shadowing a field that has been indexed.

## Example

Assume we have a mapping like: 

```json
{
  "properties": {
    "okta": {
      "properties": {
        "target": {
          "type": "flattened"
        }
      }
    }
  }
}
```

And in our flattened doc, we have a field `alternate_id`.

If we run a query (aggregation) against the native field:

Example

```json
{
  "aggs": {
    "0": {
      "terms": {
        "field": "okta.target.alternate_id",
        "order": {
          "_count": "desc"
        },
        "size": 50
      }
    }
  },
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2023-06-28T11:00:00.000Z",
              "lte": "2023-06-28T12:00:00.000Z"
            }
          }
        }
      ]
    }
  }
}
```

The aggregation will take ~5-20ms

<details>

<summary>Screenshot of test</summary>

![image](https://github.com/elastic/elasticsearch/assets/8277432/7bba3210-907a-4460-b4e3-79e5ff9e6b95)

</details>

If we then add a script-less runtime field to shadow this exact same field, we see a significant performance degradation.

```json
{
  "aggs": {
    "0": {
      "terms": {
        "field": "okta.target.alternate_id",
        "order": {
          "_count": "desc"
        },
        "size": 50
      }
    }
  },
  "size": 0,
  "runtime_mappings": {
    "okta.target.alternate_id": {
      "type": "keyword"
    }
  },
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2023-06-28T11:00:00.000Z",
              "lte": "2023-06-28T12:00:00.000Z"
            }
          }
        }
      ]
    }
  }
}
```

This aggregation now takes ~2 seconds

<details>

<summary>Screenshot of test</summary>

![image](https://github.com/elastic/elasticsearch/assets/8277432/9c021cd2-c216-4155-a010-99f9144a9aae)

</details>

I would expect that a runtime field shadowing an indexed field would be able to leverage the pre-existing index of the field to achieve similar performance to the actual field.

## Use Case

This might seem like an odd thing to do, but the main use case for doing something like this, is dealing with applications/implementations (ex: Kibana) that don't support some of the Elasticsearch field types (ex: `flattened`).

**Comment by javanna** [comment]
This behaviour is expected, as script-less runtime fields load values from `_source` which is quite expensive, see https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html#runtime-fields-scriptless . That is regardless of whether the field being referred to is indexed or not.

There is though a workaround: define a runtime field with a script that loads the indexed field and returns values retrieved from doc_values using the doc notation (https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-mapping-fields.html#runtime-mapping-fields) , in your case `emit('okta.target.alternate_id')`
