### ISSUE TITLE
Add index version numbers to cluster upgrade tests

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#97200]
BwC & upgrade cluster tests have the node versions to use passed in as environment variables (eg https://github.com/elastic/elasticsearch/blob/main/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/AbstractRollingTestCase.java#L32, https://github.com/elastic/elasticsearch/blob/main/x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/AbstractMultiClusterUpgradeTestCase.java#L69). After we migrate to the IndexVersion class, there will not be a mapping between Version and IndexVersion. This means we will need to add index version to the test setup & environment variables in various tests.

How will we map between the node version & corresponding indexversion? Or does that not particularly matter once they're separated?

**Comment by mark-vieira** [comment]
> How will we map between the node version & corresponding indexversion? Or does that not particularly matter once they're separated?

There's a map between `Version` and `IndexVersion` in the `Version` class. Is that going to go away?

**Comment by thecoop** [comment]
> There's a map between `Version` and `IndexVersion` in the `Version` class. Is that going to go away?

Yes, it will be similar to `TransportVersion` - a simple incrementing integer.

**Comment by rjernst** [comment]
> There's a map between Version and IndexVersion in the Version class. Is that going to go away?

That mapping exists as a temporary measure to allow migrating from the old to new strategy without the need for a big bang change. After the migration is complete, production code should not need to know what IndexVersion a particular Version of Elasticsearch used.

For integration tests, we currently pass the property statically. Could we determine the value dynamically at runtime, like we do the http port? We could get the index version from the info api as the first step after starting the node, then have it available in the tests. I like this strategy because it decouples the version being started (which at least in non-serverless would still be a semver version) from _most_ of the feature logic in tests. There is likely still an edge case for determining node configuration, but I think that could stay based on real node version (or some other TBD mechanism in serverless).

**Comment by mark-vieira** [comment]
> We could get the index version from the info api as the first step after starting the node, then have it available in the tests.

I'd also prefer a solution like this rather than make the _build_ know anything about index versions.

**Comment by thecoop** [comment]
I've had a look at this; it is not trivial, with some tests expecting to get the old cluster version regardless of the version of the running cluster. Currently the node info is queried at the start of each test & then fixed for the test. It'll need a broader re-work of how versions are handled in upgrade tests.

Could #97368 be merged to progress the IndexVersion migrations, and we can look at this broader work separately?

**Comment by rjernst** [comment]
Yes, I think #97368 can be merged, but I think this index versions in tests work needs to happen as part of the index version work, it can't be put off to some indeterminate future.

**Comment by thecoop** [comment]
So there are two places this is used:

The first is in a [snapshot recovery test](https://github.com/elastic/elasticsearch/blob/52a6820813577abcb23191d862a01e32e652ed42/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/FullClusterRestartIT.java#L1313), checking that the version of the old snapshot is the index version of the code that created it before upgrade.
The second is in a [test](https://github.com/elastic/elasticsearch/blob/52a6820813577abcb23191d862a01e32e652ed42/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/FullClusterRestartIT.java#L967) that has been [defunct since 2020](https://github.com/elastic/elasticsearch/issues/52031).

It's going to be very difficult to get the index version to check against here - the old/mixed/upgraded clusters run in separate test suites, so in order to get the IndexVersion we'll need to checkout the code & parse the IndexVersion.java class for the current version, probably with help from a new gradle task. That is a lot of work in a codebase that I'm not familiar with.

Given that it's only these two places - one is a minor test check, and the other is ignored - what are your thoughts on just removing the snapshot version check & deleting the defunct test completely? If we find we've got more places we need to get the index version we can then implement it properly using git checkouit & version parsing, then re-instate these tests.

**Comment by thecoop** [comment]
https://github.com/elastic/elasticsearch/pull/98536 unblocks this issue in 8.10 (turns it into an 8.11 blocker)

**Comment by thecoop** [comment]
To do this we need some endpoint where the index version is exposed - this is still TBD from the comment in https://github.com/elastic/elasticsearch/pull/97675

**Comment by thecoop** [comment]
This has been done by migrating the relevant tests to the junit-based bwc test infrastructure, which shares a JVM between all the test runs. This allows the index version to be read from the old version nodes & stored in the class, so it can be compared against the new version after upgrade
