### ISSUE TITLE
IndexUpgraderMergeSpecification strips any overridden merge reader logic

### ISSUE THREAD

**Issue by ebradshaw** [elastic/elasticsearch#9731]
In a first try to write a plugin that implements Lucene's SortingMergePolicyProvider in ES [(Gist)](https://gist.github.com/ebradshaw/d29c80a9b843a5d1e77a), I ran into an issue where the logic introduced by SortingMergePolicy.SortingOneMerge was being stripped.  This is caused by the following code in ElasticsearchMergePolicy: 

    static class IndexUpgraderMergeSpecification extends MergeSpecification {

            @Override
            public void add(OneMerge merge) {
                super.add(new IndexUpgraderOneMerge(merge.segments));
            }

            ...

    }

I'm assuming this was done because the current merge policies are only responsible for determining when a merge should a occur, not how it should affect the output.  Has anyone given any consideration to modifying IndexUpgraderOneMerge to delegate some of it's responsibility to the calling OneMerge?

**Comment by rjernst** [comment]
@ebradshaw That sounds like a fine idea to me. Do you want to create a PR making IndexUpgraderOneMerge have a delegate OneMerge instead of calling the current super?

**Comment by ebradshaw** [comment]
@rjernst I'll go ahead and get on that.  Thanks.

**Comment by ebradshaw** [comment]
@rjernst So I started digging into this, only to quickly realize that Lucene's current rendition of MergePolicy.OneMerge will not support delegation.  This is due to the direct member variable access of the various variables used by IndexWriter.  When a wrapping OneMerge delegates to another OneMerge, it quickly runs into issues since the member variables of the delegate have not and cannot be initialized by the IndexWriter.

This bummed me out for a bit, because I think that the ability to apply the decorator pattern to the merge/CodecReader logic would be useful in more cases than this one.  After some more digging, I realized that this could be resolved by making all of the member variables in OneMerge private and adding appropriately restricted getters and setters.  It requires a fair amount of variable access code change in the IndexWriter and a few other classes, but will have no impact on the overall logic involved.  Once this is done, a DelegatingOneMerge could be created and used as the base class for most of the other OneMerges.  Here are some Gists:

[DelegatingOneMerge](https://gist.github.com/ebradshaw/e0b74e9e8d4976ab9e0a)
[OneMerge](https://gist.github.com/ebradshaw/d72116a014f226076303)

I've begun a PR in Lucene for this change.  Do you or anyone else see any reasons why these modifications might be a problem?  The only API change that I see occuring as a result would be that the public variable access of estimatedMergeBytes, segments and totalDocCount would have to be locked down and changed to public getters.

If you have any alternative thoughts or suggestions, I'm all ears.

**Comment by clintongormley** [comment]
No progress on this since Feb. Closing for now
