### ISSUE TITLE
EsAbortPolicy should show thread pool name

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9732]
Whenever `EsAbortPolicy` aborts an action, it should report the thread pool's name to make it easier to diagnose where it's coming from (usually the stacktrace is enough, but it would be a lot faster to have its name).

An `instanceof` check needs to be done to run it against the `EsThreadPoolExecutor`, and each `EsThreadPoolExecutor` needs to be given its name to allow reporting of it.

**Comment by jpountz** [comment]
> An instanceof check needs to be done to run it against the EsThreadPoolExecutor, and each EsThreadPoolExecutor needs to be given its name to allow reporting of it.

We could even skip the instanceof call and make sure that the thread pool name is included in the `toString()` representation of the thread pool?

**Comment by nik9000** [comment]
This turned out a to be a little more extensive then I'd thought it would be at first. Adding the name involves lots of fun ductwork and making EsThreadPoolExecutor's toString nice gives you lots of fun diagnostic information.

**Comment by nik9000** [comment]
Old message: ```EsRejectedExecutionException[rejected execution (shutdown) on dummy runnable]```
New message: ```EsRejectedExecutionException[rejected execution of dummy runnable on EsThreadPoolExecutor[some-name, queue capacity = 78, state = Terminated, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 1231241234]]```


Old message: ```EsRejectedExecutionException[rejected execution (queue capacity 78) on dummy runnable]```
New message: ```EsRejectedExecutionException[rejected execution of dummy runnable on EsThreadPoolExecutor[some-name, queue capacity = 78, state = Running, pool size = 2, active threads = 2, queued tasks = 78, completed tasks = 0]]```
