### ISSUE TITLE
Fuzzy query is not honoring value set in the 'rewrite' parameter.

### ISSUE THREAD

**Issue by ricardo-leon-pureinsights** [elastic/elasticsearch#97376]
### Elasticsearch Version

8.8.1

### Java Version

_bundled_

### OS Version

Linux 50f548cdddb5 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Setting `rewrite` parameter to `constant_score_boolean`  (or `constant_score`) in a fuzzy query is not having the expected effect of setting the score to `1`. Actually, no matter what value is set (see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-term-rewrite.html), the score is always the same.

This used to work well in ES 7.x, whereby changing the `rewrite` value would affect the score.

### Steps to Reproduce

**Create index**
`PUT test_index`

**Insert sample data**
```
POST _bulk
{ "index" : { "_index" : "test_index", "_id" : "1" } }
{"my_field": "streaming platform"}
{ "index" : { "_index" : "test_index", "_id" : "2" } }
{"my_field": "streaming revenue"}
{ "index" : { "_index" : "test_index", "_id" : "3" } }
{"my_field": "ads revenue"}

```
**Run query**
```
POST test_index/_search
{
    "query": {
        "fuzzy": {
            "my_field": {
                "value": "streameng",            
                "rewrite": "constant_score_boolean"
            }
        }
    }
```
}

**Comment by benwtrent** [comment]
I have verified that in the latest version of Elasticsearch, `constant_score_boolean` and `constant_score` both set the value to the `boost` parameter as it states in the docs.
