### ISSUE TITLE
Clarify no master block

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#9739]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#no-master-block

"For a node to be fully operational, it must have an active master."

It may help to clarify the above with something like the following?

"For the cluster to be fully operational, it must have an active master and the number of running master eligible nodes must satisfy the discovery.zen.minimum_master_nodes setting if set."

**Comment by ebuildy** [comment]
I believe this is to control replication consistency in case of there is no master in your cluster. Looks like you can configure it in order to still allow reading operation (but with a probability to have stale data) or not (same for write operation).

**Comment by javanna** [comment]
Thanks @ppf2 I have pushed the change that you suggested. Feel free to send a PR next time instead ;)
