### ISSUE TITLE
[DOCS] elasticsearch-keystore add-file example should use regular text file

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#97459]
We use a `.json` file in the example command:

```
bin/elasticsearch-keystore add-file the.setting.name.to.set /path/example-file.json
```

However, no secure setting in Elasticsearch is going to have a JSON value. If the contents of `example-file.json` was something like:

```JSON
{ "foo" : "bar" }
```
Then the above command would create a keystore entry of `the.setting.name.to.set : { "foo" : "bar" }`. 

It'd be better to have a plain `.txt` file in the example and show the contents so users understand the expected format.

```
cat example-file.txt
changeme
```
```
bin/elasticsearch-keystore add-file the.setting.name.to.set /path/example-file.txt
```

**Comment by rjernst** [comment]
Hi @n0othing . Thanks for your interest in Elasticsearch, and for opening this issue.

> no secure setting in Elasticsearch is going to have a JSON value

This isn't quite true. The GCS repository has a credentials file which is json (that is what the google sdk client expects).

So I think keeping .json as an example is ok. But I do agree we need some better clarity on the behavior of add-file, so I opened https://github.com/elastic/elasticsearch/pull/97474. Hopefully that addresses at least some of the underlying issue you have with the example using .json.
