### ISSUE TITLE
Field fetcher performance issue with lots of nested fields

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#97461]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

Not relevant

### Problem Description

Mappings that contain a lot of nested fields at multiple levels suffer from a very slow `fields` option in the `_search` request.
The `FieldFetcher` initialisation seems to create a lot of redundant `FieldFetcher` for every nested field paths. 
The following gist reproduces the [issue](https://gist.github.com/jimczi/87fd6bb6a4428cccbabb986de917f234). 
Retrieving a single empty doc without providing any field in the `field` option takes several seconds due to the initialisation of the nested field fetcher.
I believe that the performance bug was introduced in https://github.com/elastic/elasticsearch/pull/67432.
 I marked the issue as a performance bug since having lots of nested fields shouldn't make every query using the `fields` option slow.

### Steps to Reproduce

See https://gist.github.com/jimczi/87fd6bb6a4428cccbabb986de917f234

**Comment by romseygeek** [comment]
I think we can get a quick fix here by only creating the nested fetchers if they are actually required, but we should also make this behave well for requests that specifically ask for nested values.  The problem at the moment is that all nested lookups are O(n^2) in the number of nested mappers, which is fine for situations where there are only one of two but not so good for mappings with 50-odd of them.

**Comment by romseygeek** [comment]
Fixed by #97683
