### ISSUE TITLE
[TESTS] Unit tests for IndexLookup

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#9749]
The tests IndexLookupTests are tricky to debug (see https://github.com/elasticsearch/elasticsearch/pull/9746) because they rely on scripted field mechanics, script engine etc. 
It should be easy to unit test IndexLookup because it only relies on LeafReaderContext.

**Comment by clintongormley** [comment]
@brwe is this still relevant?

**Comment by brwe** [comment]
the test moved to https://github.com/elastic/elasticsearch/tree/master/modules/lang-groovy/src/test/java/org/elasticsearch/messy/tests and waits to be refactored like many others. It is certainly still relevant.

**Comment by javanna** [comment]
IndexLookupIT was moved out of the messy tests package with #19621. Its tests still rely on scripting though. Is there anything that needs to be done? Especially given that, AFAIK, we decided to remove `IndexLookup` ?

**Comment by brwe** [comment]
I don't think so. Closing.
