### ISSUE TITLE
Enable indexing by default on `dense_vector`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#97531]
### Description

`dense_vector` is the only field type that supports indexing but doesn't enable it by default, so users end up needing to set `index:true` in mappings almost all the time. Let's change the default.

**Comment by carlosdelest** [comment]
`similarity` needs to be specified when `dense_vector` is being `indexed`. 

Is there a default value that we want to provide as part of this change, or do we want to fail in case `similarity` is not provided explicitly?

cc @benwtrent

**Comment by carlosdelest** [comment]
Draft [PR opened](https://github.com/elastic/elasticsearch/pull/98268). 

I'd like to make some test pass without having to explicitly serialize `index`.

**Comment by jimczi** [comment]
> we should default to cosine allowing users to provide something different if necessary.

Similarity is not updatable currently. Should we allow it to change on an existing field if we create the mapping dynamically?

**Comment by benwtrent** [comment]
>  Should we allow it to change on an existing field if we create the mapping dynamically?

We could if that mapping saw no documents. But as soon as one is seen, the similarity is set in stone.

**Comment by jimczi** [comment]
> But as soon as one is seen, the similarity is set in stone.

Why? I can see an issue with `dot_product` since some vectors might not be accepted but with https://github.com/apache/lucene/pull/12479 that shouldn't be an issue anymore?

**Comment by benwtrent** [comment]
@jimczi the graph being built with a specific similarity and then adjusting it later requires some testing and knowledge I do not have nor have time to do. 

I would rather have that be a separate discussion than this issue.

**Comment by jimczi** [comment]
> the graph being built with a specific similarity and then adjusting it later

Each segment has a different graph so not sure what needs to be adjusted?
Maybe you're saying that if the default is not picked correctly then it's better to simply create a new index and reindex there?

> I would rather have that be a separate discussion than this issue.

Sure, I can open a new issue but we need to make sure that the default here makes sense. Why is `cosine` the best default? Is it more used than the other similarity?

**Comment by jimczi** [comment]
> My biggest concern is that different similarities can scale the resulting _score differently. Meaning different segments could have different scaling on its scores and thus, things that are actually closer in one segment could score lower than something further away in another segment.
Consistency is very important here.

But we don't store the _score on the graph, it it recomputed on the fly on each search so the scaling won't affect it since we'd use the same similarity on every segment. The only thing that could happen is that segments built with the "wrong" similarity would be less optimal and could lead to slower search when another similarity is used.

**Comment by kderusso** [comment]
Closed with merged PR https://github.com/elastic/elasticsearch/pull/98268
