### ISSUE TITLE
Support setting the number of dimensions dynamically on dense_vector

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#97530]
### Description

It would be nice if `dense_vector` supported setting its number of dimensions dynamically, when the first document that has a value for this vector gets indexed. This could simplify getting-started guides, and would enable users to not have to change their index templates when trying out a different model that has a different number of dimensions.

For reference, `constant_keyword` has a similar mechanism for setting its `value` parameter.

**Comment by kderusso** [comment]
I plan to combine this with https://github.com/elastic/elasticsearch/issues/97532
PR: https://github.com/elastic/elasticsearch/pull/98512
