### ISSUE TITLE
Add default dynamic mappings for `dense_vector`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#97532]
### Description

Dynamic mappings can greatly help the getting started experience but they currently don't apply to all types, one example is `dense_vector`.

It's been suggested to automatically map float arrays as dense vectors when there are more than 100 values, or a heuristic along these lines.

**Comment by jimczi** [comment]
Given that many of the vector dimensions are typically powers of two, my suggestion would be to consider utilizing a threshold such as 64 or 128.

**Comment by kderusso** [comment]
PR: https://github.com/elastic/elasticsearch/pull/98512
