### ISSUE TITLE
Numbers getting represented wrong when using aggregations

### ISSUE THREAD

**Issue by Schorrym** [elastic/elasticsearch#97558]
### Elasticsearch Version

7.17.11

### Java Version

17.02

### OS Version

Windows 10 22H2

### Problem Description

We got a document and put a number in like 100.2. With dynamic mapping it gets mapped to a float.
Now using an aggregations function like max it gets represented as 100.19999694824219

100.3 will result into 100.30000305175781

What is going on here? As the aggregation sum is doing the same implicit, there are incorrect results coming up.

### Steps to Reproduce

Adding document (dynamic mapping) with a field 'test' and number 100.3 or 100.2 (or others may do the same). Running a query on the index with the single document

POST your_index/_search
{
    "size": 0,
    "_source": false,
    "aggregations": {
        "groupby": {
            "filters": {
                "filters": [
                    {
                        "match_all": {
                            "boost": 1.0
                        }
                    }
                ],
                "other_bucket": false,
                "other_bucket_key": "_other_"
            },
            "aggregations": {
                "d2b54a77": {
                    "min": {
                        "field": "test"
                    }
                }
            }
        }
    }
}

**Comment by pquentin** [comment]
Thanks very much for your interest in Elasticsearch.

The result is expected: this is how floating point numbers work in Java and many other languages, see https://stackoverflow.com/questions/588004/is-floating-point-math-broken/588014#588014 for an explanation if you're interested in the details.

We'd like to direct these kinds of user questions to the [forums](https://discuss.elastic.co/). If you can stop by there for any additional question you may have, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
