### ISSUE TITLE
[CI] MlConfigIndexMappingsFullClusterRestartIT  testMlConfigIndexMappingsAfterMigration {cluster=UPGRADED}

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#97568]
### CI Link

https://gradle-enterprise.elastic.co/s/6fz3bd6iyk3w2/tests/:x-pack:qa:full-cluster-restart:v8.9.0%23bwcTest/org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT/testMlConfigIndexMappingsAfterMigration%20%7Bcluster=UPGRADED%7D?top-execution=1

### Repro line

./gradlew ':x-pack:qa:full-cluster-restart:v8.9.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT" -Dtests.method="testMlConfigIndexMappingsAfterMigration {cluster=UPGRADED}" -Dtests.seed=6797AED811CA653B -Dtests.bwc=true -Dtests.locale=mk-MK -Dtests.timezone=America/Chicago -Druntime.java=17 -Dtests.fips.enabled=true

### Does it reproduce?

Didn't try

### Applicable branches

8.9

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1689078932794&search.startTimeMin=1688418000000&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT&tests.test=testMlConfigIndexMappingsAfterMigration%20%7Bcluster%3DUPGRADED%7D

### Failure excerpt

```
[2023-07-11T01:00:00,014][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [test-cluster-0] fatal error in thread [elasticsearch[test-cluster-0][generic][T#3]], exiting java.lang.AssertionError: initial cluster state not set yet
	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
	at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
There has also been another failure 7 days before (https://gradle-enterprise.elastic.co/s/lvz7p73vogyzq/tests/:x-pack:qa:full-cluster-restart:v8.2.0%23bwcTest/org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT/testMlConfigIndexMappingsAfterMigration%20%7Bcluster=UPGRADED%7D?top-execution=1
), with a different stacktrace:
```
  1> [2023-07-06T01:00:00,012][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [test-cluster-0] fatal error in thread [elasticsearch[test-cluster-0][generic][T#3]], exiting java.lang.AssertionError: initial cluster state not set yet
  1> 	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.state(ClusterApplierService.java:181)
  1> 	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterService.state(ClusterService.java:141)
  1> 	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporter.onCleanUpIndices(LocalExporter.java:598)
  1> 	at org.elasticsearch.xpack.monitoring.cleaner.CleanerService$IndicesCleaner.doRunInLifecycle(CleanerService.java:164)
  1> 	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractLifecycleRunnable.doRun(AbstractLifecycleRunnable.java:56)
  1> 	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  1> 	at org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  1> 	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by edsavage** [comment]
Another example here: https://gradle-enterprise.elastic.co/s/dmgl764bcek2s/console-log?task=:x-pack:qa:full-cluster-restart:v7.3.1%23bwcTest

**Comment by droberts195** [comment]
Although it's an ML test that's failing, the failure is actually in monitoring code. It's happening in the nodes of the test cluster.

I imagine some other change has been made that means an `AbstractLifecycleComponent` can be started up before the initial cluster state is set. It seems that monitoring's `CleanerService` needs to be adapted to cope with that. Maybe it only affects upgrades from really old versions if only those really old versions have monitoring indices that need cleaning?

Reassigning to data management.

**Comment by cbuescher** [comment]
One more on main today: https://gradle-enterprise.elastic.co/s/qu7s7cztphpxu

**Comment by bpintea** [comment]
One more failure of the test, but seamingly different failure mode: https://gradle-enterprise.elastic.co/s/enwd2qxv5jb4w

**Comment by droberts195** [comment]
With this latest failure 51 tests failed owned by a variety of different teams. But the server-side logs contain this:

```
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (64375534). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/dev/shm/bk/bk-agent-prod-gcp-1703085808727606297/elastic/elasticsearch-pull-request/x-pack/qa/full-cluster-restart/build/testrun/v8.12.0_bwcTest/temp/test-cluster3050742063131988079/test-cluster-0/data/indices/s2RoeTieTPG-Q_EIpuX5fw/0/index/_0.cfs") [slice=_0_ES87BloomFilter_0.bfm]))
```

@elastic/es-search has there recently been a Lucene upgrade? If so then this latest error looks a bit worrying.

(That error can be seen in https://gradle-enterprise.elastic.co/s/enwd2qxv5jb4w/tests/task/:x-pack:qa:full-cluster-restart:v8.12.0%23bwcTest/details/org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT/testMlConfigIndexMappingsAfterMigration%20%7Bcluster%3DUPGRADED%7D/1/output)

**Comment by iverase** [comment]
```
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'ES812Postings' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [ES85BloomFilter, ES87BloomFilter, Lucene99, Lucene50, Lucene84, Lucene90, completion, Completion84, Completion90, Completion99, IDVersion, BlockTreeOrds, BloomFilter, Direct, FST50, UniformSplit, SharedTermsUniformSplit]
```

Iguess this is cause from the PR I just merged today, need to understand why: https://github.com/elastic/elasticsearch/pull/103601

**Comment by ChrisHegarty** [comment]
^^ 
> One more failure of the test, but seamingly different failure mode: https://gradle-enterprise.elastic.co/s/enwd2qxv5jb4w

Non-issue.

Failure log contains:
  An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'ES812Postings' does not exist.

The repo where the failure was seen does not have [#103601 Introduce Elasticsearch PostingFormat based on Lucene 90 positing format using PFOR](https://github.com/elastic/elasticsearch/pull/103601). But the 8.12 branch does. So B

A new posting format, ES812Postings, was added to main and backported to the currently-unreleased 8.12 branch. BWC tests that checkout the 8.12 branch and create indexes will use this, so all outstanding PR branches will need to have it!

**Comment by droberts195** [comment]
I am going to close this issue now. It’s reporting two completely different failures neither of which were related to the ML test named in the issue title. The first one clearly hasn’t been recurring often, so might already be fixed via a different issue that reported the same thing, and the second has been proven to be a non-issue.

If the test fails again a fresh issue should be opened as this one is just too confusing to append to any further.
