### ISSUE TITLE
please upstream changes in Base64 class and use the upstream one instead of bundling

### ISSUE THREAD

**Issue by judovana** [elastic/elasticsearch#9759]
The patch for upstream may be found:
http://pkgs.fedoraproject.org/cgit/java-base64.git/commit/?id=91b0f788584f10f8502a44b6c9d945b1055e2e35

Also please consider moving form http://iharder.net/base64 to jdk8's  http://docs.oracle.com/javase/8/docs/api/java/util/Base64.Encoder.html

**Comment by colings86** [comment]
The current plan would be to do this when we move to requiring java 8 as default. Have you found issues with the current Base64 code which suggest we should move to this sooner?

**Comment by judovana** [comment]
nope :) Only need to patch bundled out out and replace it by dependency for 
creation of Fedora rpms.



Thanx!



-- 

Mgr. Jiri Vanek

judovana@email.cz






---------- Původní zpráva ----------

Od: Colin Goodheart-Smithe <notifications@github.com>

Komu: elastic/elasticsearch <elasticsearch@noreply.github.com>

Datum: 31. 7. 2015 12:16:25

Předmět: Re: [elasticsearch] please upstream changes in Base64 class and use
the upstream one instead of bundling (#9759)


"

The current plan would be to do this when we move to requiring java 8 as 
default. Have you found issues with the current Base64 code which suggest we
should move to this sooner?

—

Reply to this email directly or view it on GitHub
(https://github.com/elastic/elasticsearch/issues/9759#issuecomment-126634746)
. 





"=

**Comment by clintongormley** [comment]
@colings86 should we do this in master now?

**Comment by judovana** [comment]
That would be nice ;)



-- 

Mgr. Jiri Vanek

judovana@email.cz






---------- Původní zpráva ----------

Od: Clinton Gormley <notifications@github.com>

Komu: elastic/elasticsearch <elasticsearch@noreply.github.com>

Datum: 5. 12. 2015 17:03:11

Předmět: Re: [elasticsearch] please upstream changes in Base64 class and use
the upstream one instead of bundling (#9759)


"

@colings86(https://github.com/colings86) should we do this in master now?

—

Reply to this email directly or view it on GitHub
(https://github.com/elastic/elasticsearch/issues/9759#issuecomment-162216128)
. 





"=

**Comment by colings86** [comment]
@clintongormley my previous comment was made form the outcome of a FixItFriday so I think we should discuss this again in FixItFriday to decide when and where we should do this

**Comment by jpountz** [comment]
Fixed via #18413
