### ISSUE TITLE
Health Report API should not return RED for unassigned cold/frozen shards of ILM moves

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#97606]
### Elasticsearch Version

8.8.1+ but probably all versions

### Java Version

_bundled_

### OS Version

cloud

### Problem Description

This is a follow-up of [#97370](https://github.com/elastic/elasticsearch/issues/97370). 

In a case where disk spaces are reaching limits, if ILM suddenly tries to move a lot of hot shards to cold/frozen shards, it can tip the cluster health to RED because a lot of cold/frozen shards may be created and stay unassigned as long as there is not enough disk space. However, this is not a suitable indicator for service unavailability, since the data is still safely in the respective hot shards that are becoming cold/frozen, and will remain there until the cold/frozen shards are assigned so that searches can still search them.

Thus the [Health Report API](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/health-api.html) should not return RED for unassigned cold/frozen shards of ILM moves.

### Steps to Reproduce

In a case where disk spaces are reaching limits, if ILM suddenly tries to move a lot of hot shards to cold/frozen shards, it can tip the cluster health to RED because a lot of cold/frozen shards may be created and stay unassigned (as long as there is not enough disk space).

**Comment by andreidan** [comment]
@kingherc Can you please detail a bit more which indicator was RED?

> as long as there is not enough disk space.

I'm assuming it's the `disk` indicator? If my assumption is correct I'd argue this indicator is something that must continue to alert on (note that before RED this disk space indicator was likely YELLOW for quite some time). 
I think our users are definitely interested in low disk space scenarios.

**Comment by kingherc** [comment]
Hi @andreidan , we are mostly worried about the unassigned_primaries indicator I believe (cc @DaveCTurner ). Cold shards are primaries by themselves, but until they are allocated, their respective hot shards are not removed by ILM. Thus, the situation should not be characterized as RED.

**Comment by andreidan** [comment]
That is technically correct (and perhaps we should have a conversation about how the individual `shards_availability` indicator behaves - its mantra has to be the equivalent of `cluster/health, but perhaps we want to diverge where it makes sense). 

However, the culprit here is the low disk space in the `cold` tier which will cause the _overall status_ of the health report to `RED`.

**Comment by DaveCTurner** [comment]
I don't think we should have any indicators in `RED` when this happens, at least not until we've concluded that autoscaling isn't going to come and rescue us (whether by timeout or some other mechanism).

I would expect the disk health indicator might have gone from `GREEN` straight to `RED` for the cold tier. It was a sudden increase in the space requirements there.

> perhaps we should have a conversation about how the individual shards_availability indicator behaves - its mantra has to be the equivalent of `cluster/health, but perhaps we want to diverge where it makes sense

Yeah I don't think we should maintain equivalence with cluster/health for this indicator. Cluster health is far too sensitive to non-issues like the one described here, leading to false alerts.

**Comment by mattc58** [comment]
Is there example output of the `/_health_report` call to see what actually triggered this issue?

@DaveCTurner mentioned the possibility of autoscaling coming to rescue us. Could we have some sort of `unassigned_primaries_waiting_to_be_autoscaled` indicator? If not, is a timeout the best we can do for this?

**Comment by kingherc** [comment]
Hi @mattc58 , I believe I do not have an example output. However, you can check the last (internal) linked issue above for an example where we believe the current issue would help. In a nutshell, we believe that a cluster whose health indicator is not RED due to this situation can be considered safe to be autoscaled.

**Comment by nerophon** [comment]
I'll just add a quick note to this discussion. The user-experience goal here is to ensure that autoscaling does happen successfully in the cold tier when it ought to. Therefore, please bear in mind when finalising a plan what ESS/ECE is able to do. Even if autoscaling does manage to kick in, the scaling activity will subsequently fail during the `Validate Plan Prerequsites` step if the cluster status is "red". For example:
```
Failed to validate cluster health/prerequisites. Please resolve each of the errors identified and retry.
{
  "failure_type": "ClusterFailure:ClusterPrerequisiteValidationFailed",
  "caused_by": "no.found.constructor.validation.ValidationException: 1. Unhealthy cluster state: red state"
}
```
I would hope this validation uses the Health Report API. But I am concerned it might use the Cluster Health API. If there is any doubt, perhaps we should double check the code or ask someone from Cloud?

**Comment by DaveCTurner** [comment]
We can't really discuss the Cloud implementation details here @nerophon, I'll reply to that in a different channel.

**Comment by andreidan** [comment]
We discussed this yesterday and a potential solution here is to report the fully and partially mounted indices health only if the source indices are missing (or red themselves).
e.g.
- if `restored-logs-2023.07.11-000024` is `RED` but `logs-2023.07.11-000024` is `GREEN` the health API returns `GREEN`
- if `restored-logs-2023.07.11-000024` is `RED` AND `logs-2023.07.11-000024` is missing or RED itself, then the health API starts reporting on the health of the `restored-logs-2023.07.11-000024` (which would be RED already due to the source/original index being RED in the case when it still exists)

**Comment by tylerperk** [comment]
We think we can fix this and have added it to the short term roadmap to do so.
