### ISSUE TITLE
Would be useful to be able to specify inner_hits at top level without specifying a query

### ISSUE THREAD

**Issue by tstibbs** [elastic/elasticsearch#9763]
I've been trying out the new 'nested_hits' stuff (see #8153, I built a 1.5 snapshot from commit 75b6d8e on the 1.x branch) and the two options for specifying it, and noticed that my use case seems to fall into a gap between the two options. Basically, I want to specify the inner_hits element at the top level, but I want it to return the inner hits based on the children that actually matched, rather than me specifying a whole new query (note I tried just leaving the query element out of the inner_hits bit, but that just seemed to return all my children regardless of whether they were part of the match).

My use case involves my users entering a query like this:

> find a parent who has a child which is blue and another child which is red.

So my queries end up looking something like this (hopefully the pseudo-query-syntax made up for brevity will make sense to you): 

````
(nested(blue)) AND (nested(red))
````

What would be really useful is a way to say “give me the three children that contributed most to the score of the overall result”. But I can’t see any way to do that with the current ways to specify the inner_hits element.

Option one seems to be to specify inner hits for each of the nested queries. That will give me back three hits for each nested query so it’s difficult to tell which contributed most overall. I’d have to start taking the scores from the results for each nested query and combining them to work out which the top three matching children are. At which point I’m re-implementing a lot of lucene’s scoring maths. And it gets worse if the above query actually had “AND NOT” in it, or when the nested queries are deeply nested within boolean and constantscore queries.

Option two seems to be to specify inner hits for the query as a whole. But I have to give it its own query – which means I have to somehow transform the query above into a new query. It would end up something like this:

````
(blue) OR (red)
````

Note it has to change from AND to OR because it needs to match the single child.

Transforming the query sounds hard (particularly if I let my users enter an arbitrary query and try to transform it in code), and although I can’t come up with a compelling example I feel that it could result in highlights from children that didn’t actually contribute to the match of the parent. If transforming the query really is the right way to go about this, then maybe this logic should be put into elasticsearch (e.g. if you specify a top level inner_hits element but don’t specify a query, then it runs the main search query through the transformer and uses that for the inner_hits query). Regardless of whether I do this in my own code or whether it is done in elasticsearch, this approach has the problem that dealing with nested queries within nested queries could be tricky, and might require multiple levels of transformation.

So, another approach (sounds simpler but probably isn’t) might be to simply return the top x children that contributed most strongly to the parent match, regardless of how far down the tree of nested queries they are. So in my example above, I’d expect that a child containing both ‘blue’ and ‘red’ would be one of the top matches. This (I think, conceptually at least) is no different to lucene working out which fields matched most strongly in a document that matches a query with many levels of nested boolean queries. If this approach is possible, it sounds like it would be most robust than the transformer approach above.

I’m not sure how much of what I’m proposing is even possible, or if my grasp of the situation is at all correct. I'd be interested to hear what people think.

**Comment by clintongormley** [comment]
I've been playing around with this today - took me a while to figure out what you were asking.  Sorry to deliver the news, but I don't think this can be implemented in any generic way without dramatically changing the way all of Lucene's queries work.
