### ISSUE TITLE
The naming of getMasterNodeId in DiscoveryNodes and isMasterNode in DiscoveryNode can be easily confused.

### ISSUE THREAD

**Issue by lude1994** [elastic/elasticsearch#97640]
### Description

elasticsearchVersion : 8.1.0
The getMasterNodeId in DiscoveryNodes means leaderNodeId but the IsMasterNode method in DiscoveryNode means master-eligible node .This is troubling and requires a unified and clear semantic.

**Comment by DaveCTurner** [comment]
Thanks for the suggestion @lude1994. You are technically correct, but this is an internal API and in practice I don't really ever see anyone get confused about the difference between "master-eligible node" and "the elected master node". You could make a similar case about `node.roles: [master]`. I'm going to close this issue as won't-fix.
