### ISSUE TITLE
query_string is not using default analyzer inside of function_score

### ISSUE THREAD

**Issue by vovikdrg** [elastic/elasticsearch#9764]
I have query 
```javascript
{
  "from": 0,
  "size": 10,
  "fields": [
    "Url",
    "Id",
    "Title",
    "Description",
    "Date",
    "Breadcrumb",
    "FileBlob.title",
    "FileBlob.content_type"
  ],
  "query": {
    "function_score": {
      "query": {
        "query_string": {
          "query": "tip en ven",
          "fields": [
            "Id_analyzed^1.5",
            "Title_analyzed^1.5",
            "Description_analyzed^1",
            "Breadcrumb_analyzed^1",
            "FileBlob^1",
            "netmesterrankingterms"
          ],
          "default_operator": "and"
        }
      },
      "script_score": {
        "script": "double boost = 1;  return boost; ",
        "params": {
          "searchTerm": "tip en ven"
        }
      }
    }
  }
}
```

And i have defined default_search and index analyzer which uses stop words. 
In query which i use "tip en ven",  **en** is danish stop word, and will be removed on index time as my default_index analyzer uses stop words. So when i search i have default_operator and so it expect all words to be found in document but it will not be. 
Question is why query_string is not using default_search by default? because when i set directly analyzer to it it works as expected

**Comment by clintongormley** [comment]
Perhaps you have fields with their own analyzers defined?  Could you provide a full (but simple) recreation of the whole problem (ie including creating the index, indexing the doc, the query, and the demonstration of the problem itself).

**Comment by clintongormley** [comment]
No further info. Closing
