### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=search/160_exists_query/Test exists query on float field in empty index} failing

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#97645]
There seem to be very many test failures every day on MixedClusterClientYamlTestSuitIT, but always for different tests. This one only failed once in the last seven days, so I will not mute it.

**Build scan:**
https://gradle-enterprise.elastic.co/s/p6cptxbyvowmm/tests/:qa:mixed-cluster:v7.17.12%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=search%2F160_exists_query%2FTest%20exists%20query%20on%20float%20field%20in%20empty%20index%7D

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.12#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/160_exists_query/Test exists query on float field in empty index}" -Dtests.seed=783A2FD0B4A9E923 -Dtests.bwc=true -Dtests.locale=it -Dtests.timezone=America/Nome -Druntime.java=20
```

**Applicable branches:**
8.9

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch/160_exists_query/Test%20exists%20query%20on%20float%20field%20in%20empty%20index%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([783A2FD0B4A9E923]:0)

```

**Comment by andreidan** [comment]
Some more: https://gradle-enterprise.elastic.co/s/3lmhrzpitdfc6 and https://gradle-enterprise.elastic.co/s/2sijhkbekqx2w

**Comment by benwtrent** [comment]
These suite timeouts, I honestly don't know if these individual tests are to blame but instead that the entire suite ran longer than the configured timeout and it HAPPENED to fail on this test.

**Comment by benwtrent** [comment]
The test failed quickly due to suite timeout. Suite timeout has been increased to 60m, closing this as the individual test isn't to blame, but instead the entire suite runtime and infra.

Related: https://github.com/elastic/elasticsearch/pull/100585
