### ISSUE TITLE
[CI] TransportTasksActionTests testCancellingTasksThatDontSupportCancellation failing

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#97641]
Failed at the same time as a related YAML test, which could have failed for the same reason: https://gradle-enterprise.elastic.co/s/4t34kebh2m2og/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fccr%2Fapis%2Ffollow%2Fput-follow%2Fline_87%7D?top-execution=1

**Build scan:**
https://gradle-enterprise.elastic.co/s/4t34kebh2m2og/tests/:server:test/org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests/testCancellingTasksThatDontSupportCancellation

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testCancellingTasksThatDontSupportCancellation" -Dtests.seed=DADFBFD0C01AA0A5 -Dtests.locale=id -Dtests.timezone=Asia/Ulan_Bator -Druntime.java=20
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests&tests.test=testCancellingTasksThatDontSupportCancellation

**Failure excerpt:**
```
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:16785][internal:transport/handshake] request_id [10] timed out after [30016ms]

  at __randomizedtesting.SeedInfo.seed([DADFBFD0C01AA0A5:506107C930750E1]:0)

```

**Comment by arteam** [comment]
This one hasn't failed in the last 90 days, so I'm going to close it. Feel free to re-open the issue if it starts reproducing.
