### ISSUE TITLE
The CPU usage of the data node becomes unbalanced after the deployment of multiple Available Zones

### ISSUE THREAD

**Issue by cmh200704** [elastic/elasticsearch#97676]
### Elasticsearch Version

7.17.3

### Installed Plugins

analysis-ik

### Java Version

1.8.0_241

### OS Version

 3.10.0-957.21.3.el7.x86_64

### Problem Description

We perform geo query performance torture testing on the cluster index. When "cluster.route.allocation.awardance.attributes" is set, the cpu usage of the data node becomes unbalanced. After removing this setting, it is normal. The same torture testing concurrency and request。

I found this description in the official doc, I don't know if it has anything to do with this phenomenon：

By default Elasticsearch uses [adaptive replica selection](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-shard-routing.html#search-adaptive-replica) to route search or GET requests. However, with the presence of allocation awareness attributes Elasticsearch will prefer using shards in the same location (with the same awareness attribute values) to process these requests. This behavior can be disabled by specifying export ES_JAVA_OPTS="$ES_JAVA_OPTS -Des.search.ignore_awareness_attributes=true" system property on every node that is part of the cluster.

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/modules-cluster.html#enabling-awareness

### Steps to Reproduce

#index settings
PUT test
{
  "settings": {
    "refresh_interval": "1s",
    "number_of_shards": 4,
    "number_of_replicas": "2"
  },

# cluster settings
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.awareness.attributes": "zone",
"cluster.routing.allocation.awareness.force.zone.values": "zone1,zone2"
  }
}

# data1 node Configure
node.attr.rack_id: zone1
node.attr.zone: zone1

# data2 node Configure
node.attr.rack_id: zone2
node.attr.zone: zone2

### Logs (if relevant)

no

**Comment by swyu** [comment]
please upload the data node cpu picture

**Comment by cmh200704** [comment]
Not set: "cluster.routing.allocation.awareness.attributes"
![image](https://github.com/elastic/elasticsearch/assets/84950439/fb0337f7-ecf7-45cc-9b5f-c0386c395d92)

set: "cluster.routing.allocation.awareness.attributes"
![image](https://github.com/elastic/elasticsearch/assets/84950439/91e6f21b-aa66-47e9-8180-db3b00e68aca)

**Comment by cfangpp** [comment]
how about the shard allocation on cluster?

**Comment by DaveCTurner** [comment]
There's not really enough information for us to take action here, I'm closing this.
