### ISSUE TITLE
Fleet Server is not Healthy

### ISSUE THREAD

**Issue by john850625** [elastic/elasticsearch#97678]
### Elasticsearch Version

8.8.2

### Java Version

openjdk version "11.0.19" 

### OS Version

Linux  5.15.0-76-generic

### Problem Description

In a self-managed cluster(all in one), I installed elasticsearch(8.8.2), kibana(8.8.2) and fleet server(8.8.2) for self-learning.
The status of Fleet Server is healthy at first, but usually lost heartbeat to kibana after a while.
It resume healthy when ever restart elastic agent, and lost heartbeat as a loop.
Is any suggestion to find out the cause to this problem?

### Steps to Reproduce

 I have checked the log and status of elastic-agent.service but not found anything strange.

### Logs (if relevant)

Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.039+0800","message":"Beat ID: d13562d0-3fcf-4635-89d5-4593d7386b8f","component":{"binary":"metricbeat",">
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.040+0800","message":"Output reload is enabled, the beat will restart as needed on change of output confi>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.040+0800","message":"Set gc percentage to: 100","component":{"binary":"metricbeat","dataset":"elastic_ag>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.215+0800","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.215+0800","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.215+0800","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.215+0800","log.origin":{"file.name":"coordinator/coordinator.go","file.line":821},"message":"Updating ru>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.294+0800","message":"Home path: [/opt/Elastic/Agent/data/elastic-agent-cdc5ba/components] Config path: [>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.299+0800","message":"Beat ID: 8d528693-44ff-4daf-8706-0332aa028689","component":{"binary":"metricbeat",">
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.300+0800","message":"Output reload is enabled, the beat will restart as needed on change of output confi>
Jul 07 10:14:23 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:23.300+0800","message":"Set gc percentage to: 100","component":{"binary":"metricbeat","dataset":"elastic_ag>
Jul 07 10:14:24 d02408elk elastic-agent[2961]: {"log.level":"info","@timestamp":"2023-07-07T10:14:24.215+0800","log.origin":{"file.name":"cmd/run.go","file.line":295},"message":"reexec shutdown channel tri>
Jul 07 10:21:38 d02408elk systemd[1]: Stopping Elastic Agent is a unified agent to observe, monitor and protect your system....
Jul 07 10:21:38 d02408elk systemd[1]: elastic-agent.service: Deactivated successfully.
Jul 07 10:21:38 d02408elk systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 07 10:21:38 d02408elk systemd[1]: elastic-agent.service: Consumed 16.323s CPU time.
-- Boot 57e33d123ee441d1a69df12bd03fd96c --
Jul 07 11:55:06 d02408elk systemd[1]: Started Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 07 12:03:54 d02408elk systemd[1]: Stopping Elastic Agent is a unified agent to observe, monitor and protect your system....
Jul 07 12:03:54 d02408elk systemd[1]: elastic-agent.service: Deactivated successfully.
Jul 07 12:03:54 d02408elk systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 07 12:03:54 d02408elk systemd[1]: elastic-agent.service: Consumed 12.120s CPU time.
Jul 07 12:03:54 d02408elk systemd[1]: Started Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 07 12:10:38 d02408elk systemd[1]: Stopping Elastic Agent is a unified agent to observe, monitor and protect your system....
Jul 07 12:10:38 d02408elk systemd[1]: elastic-agent.service: Deactivated successfully.
Jul 07 12:10:38 d02408elk systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 07 12:10:38 d02408elk systemd[1]: elastic-agent.service: Consumed 12.815s CPU time.
Jul 07 12:10:38 d02408elk systemd[1]: Started Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 08 06:00:15 d02408elk systemd[1]: Stopping Elastic Agent is a unified agent to observe, monitor and protect your system....
Jul 08 06:00:15 d02408elk systemd[1]: elastic-agent.service: Deactivated successfully.
Jul 08 06:00:15 d02408elk systemd[1]: Stopped Elastic Agent is a unified agent to observe, monitor and protect your system..
Jul 08 06:00:15 d02408elk systemd[1]: elastic-agent.service: Consumed 27min 3.083s CPU time.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in the Elastic stack.

This appears to be a user question, and not one that relates directly to Elasticsearch. We'd like to direct these kinds of things to the [Elastic community forum](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
