### ISSUE TITLE
Inaccessibility of Artifact Link for Elasticsearch Versions 2.x and 5.x: Seeking Clarification

### ISSUE THREAD

**Issue by AmitPhulera** [elastic/elasticsearch#97707]
RE - https://discuss.elastic.co/t/inaccessibility-of-artifact-link-for-elasticsearch-versions-2-x-and-5-x-seeking-clarification/338457

We have been using the following link ( `https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-linux-x86_64.tar.gz`) to download and test various components on elasticsearch versions `2.4.6` and `5.6.16`. Up until a few weeks ago, this link worked perfectly fine. However, we have noticed that it has been consistently returning a 404 error lately. Despite our efforts to find any official announcements regarding this change, we have not come across any information.

Considering that elasticsearch versions `2.x` and `5.x` are no longer within their support window, we understand their diminished priority. Nonetheless, we are eager to learn about the reason behind this alteration. If the unavailability of these artifacts was unintentional, we would greatly appreciate it if the issue could be resolved.

Please note that the mentioned artifact link continues to function properly for elasticsearch versions greater than 7.0.0.

**Comment by mark-vieira** [comment]
@mgreau Are you aware of any changes to availability of older artifacts on artifacts.elastic.co?

@AmitPhulera for what its worth, these older artifacts _are_ still accessible from https://www.elastic.co/downloads.

**Comment by jmlrt** [comment]
👋🏻 @AmitPhulera,

There were no recent changes on Elastic side. Are you sure that you were previously able to download these specific versions using `https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-linux-x86_64.tar.gz` URL?

Elasticsearch 5.6.16 artifact is available at https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.16.tar.gz as the `-linux-x86_64` suffix was only introduced in 7.0.0.

Elasticsearch 2.4.6 artifact is available at https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.6/elasticsearch-2.4.6.tar.gz (we used https://download.elastic.co for all artifacts before 5.0.0 where we migrated new artifacts to https://artifacts.elastic.co).

https://www.elastic.co/downloads/past-releases#elasticsearch is where you can find all the links to download our old artifacts.

**Comment by mark-vieira** [comment]
Closing since these artifacts look to still be available.
