### ISSUE TITLE
[DOCS] User with manage_own_api_key cannot view its own api_key even though it is documented

### ISSUE THREAD

**Issue by essodjolo** [elastic/elasticsearch#97712]
### Elasticsearch Version

8.8

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

There's a mismatch between documentation and the API results.
Despite [being documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-api-key.html), a user with the `manage_own_api_keys` cannot view (in general cannot successfully run `GET _security/api_key`).

### Steps to Reproduce

1. Create apikey with only `manage_own_api_key` role:
```
POST /_security/api_key
{
  "name": "manage_own_api_key_role2",
  "expiration": "1d",
  "role_descriptors": {
    "manage_own_api_key_role": {
      "cluster": [
        "manage_own_api_key"
      ],
      "indices": [],
      "applications": [],
      "run_as": [],
      "metadata": {},
      "transient_metadata": {
        "enabled": true
      }
    }
  }
}
```
2. Then run `curl -X GET "https://xxxx/_security/api_key?owner=true" -H "Authorization: ApiKey xxxx"`
3. You'll get `this action is granted by the cluster privileges [read_security,manage_api_key,manage_security,all]"}`

### Might be related
- https://github.com/elastic/elasticsearch/pull/93606
- https://github.com/elastic/elasticsearch/issues/75205
- https://github.com/elastic/elasticsearch/issues/97459

**Comment by essodjolo** [comment]
CC @herrBez

**Comment by abdonpijpelink** [comment]
Would someone from @elastic/es-security be able to clarify this behavior?

**Comment by n1v0lg** [comment]
Hi @essodjolo! 

This one is indeed a known limitation documented under one of the issues you linked to: https://github.com/elastic/elasticsearch/issues/75205 

In particular:

> If an API key only has manage_own_api_key privilege, it is [not allowed](https://github.com/elastic/elasticsearch/blob/2e64ef12f7eb8bd2959ec3f7147f1a403f0c4200/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ManageOwnApiKeyClusterPrivilege.java#L97-L99) to call GET _security/api_key?owner=true"

Note that `GET _security/api_key?owner=true` will work if you authenticate using the owner user's basic credentials instead. Authenticating with an API key, you can get details about the API key by passing the ID of the API key instead: `GET _security/api_key?id=<API key ID here>`.

Currently it's not on our road map to fix this behavior. @abdonpijpelink we could document this limitation in the docs for the time being. WDYT?

**Comment by abdonpijpelink** [comment]
I'll add this limitation to the documentation.

**Comment by n1v0lg** [comment]
@abdonpijpelink thanks! Happy to review -- note that we have a similar limitation documented for the invalidate API key API already: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-invalidate-api-key.html#security-api-invalidate-api-key-prereqs
