### ISSUE TITLE
Pki test certs expired

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#97756]
### CI Link

https://gradle-enterprise.elastic.co/s/jze725jpxi7ki/console-log?task=:x-pack:plugin:security:internalClusterTest

### Repro line

./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.authc.pki.PkiAuthDelegationIntegTests.testDelegateThenAuthenticate" -Dtests.seed=F5EC1FEFFC2FC08B -Dtests.locale=en-GB -Dtests.timezone=SystemV/PST8PDT -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

The pki integ test began failing today. Looking at the certs the test uses, they are all expired:

```
❯ openssl x509 -enddate -noout -in testClient.crt
notAfter=Jul 18 13:33:41 2023 GMT
❯ openssl x509 -enddate -noout -in testIntermediateCA.crt
notAfter=Jul 18 13:32:34 2023 GMT
❯ openssl x509 -enddate -noout -in testRootCA.crt
notAfter=Jul 18 13:32:20 2023 GMT
```

**Comment by mark-vieira** [comment]
Not sure if this test is using the same certs but I hit a similar error on 7.17: https://gradle-enterprise.elastic.co/s/qgvxjj7ajxu6u/tests/:client:rest-high-level:asyncJavaRestTest/org.elasticsearch.client.documentation.SecurityDocumentationIT/testDelegatePkiAuthentication?top-execution=1

**Comment by mark-vieira** [comment]
FYI, I cherry-picked the test mute to 8.8 and 8.9 branches as well.

**Comment by jakelandis** [comment]
> Not sure if this test is using the same certs but I hit a similar error on 7.17

I likely is the same root cause but failing on a test suite that no longer exists in 8.x. I will backport the [fix](https://github.com/elastic/elasticsearch/pull/97766) to 7.x as well.
