### ISSUE TITLE
copy_to description does not mention usage of path

### ISSUE THREAD

**Issue by unglud** [elastic/elasticsearch#97817]
### Elasticsearch Version

8.8

### Java Version

_bundled_

### OS Version

Docker

### Problem Description

I have recently encountered an issue regarding the copy_to field in Elasticsearch mappings, specifically when combined with dynamic mappings set to strict.

According to the current Elasticsearch documentation, the copy_to parameter allows the value of one field to be copied into another field automatically during indexing. However, it seems that when the full path is not specified in the copy_to directive, it points to the root of the field structure rather than the nested field, which may not be intuitive to users.

In cases where dynamic mapping is set to strict, this behavior can lead to a strict_dynamic_mapping_exception if a document is indexed with a field that has not been explicitly defined in the mapping. This happens even if the field is present as a target in a copy_to directive, but the full path is not specified.

I suggest that the documentation be updated to clarify this point. It would be beneficial to highlight the importance of using the full path in copy_to directives, particularly when dynamic mapping is set to strict. Additionally, the potential exception that could be thrown due to the non-fully qualified path in copy_to under strict dynamic mapping should also be mentioned.

This clarification could prevent future misunderstandings and exceptions for Elasticsearch users.

### Steps to Reproduce

1. Create an index with dynamic mapping set to `strict` and a `copy_to` directive without a fully qualified path:

```json
PUT /test_index
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "description": {
        "properties": {
          "notes": {
            "type": "text",
            "copy_to": [
              "notes_raw"
            ],
            "analyzer": "standard",
            "search_analyzer": "standard"
          },
          "notes_raw": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```

2. Attempt to index a document:

```json
PUT /test_index/_doc/1
{
  "description": {
    "notes": "This is a test note"
  }
}
```

3. Observe the resulting `strict_dynamic_mapping_exception`, stating that dynamic introduction of `notes_raw` within `[_doc]` is not allowed.

This error occurs because Elasticsearch interprets the `copy_to` target of `notes_raw` as a root-level field, not a nested field under `description`. However, since `notes_raw` is not explicitly defined in the root of the mapping but under the `description` field and dynamic mapping is set to `strict`, indexing fails with the mentioned exception.

The solution would be to use a fully qualified path in the `copy_to` directive, like so: `"copy_to": [ "description.notes_raw" ]`. But this is currently not clear in the documentation, leading to potential confusion.

Please consider updating the documentation to highlight this behavior.

**Comment by leemthompo** [comment]
Thanks for suggestion @unglud!
