### ISSUE TITLE
too many NodeStats cause memory leak

### ISSUE THREAD

**Issue by xufenxu** [elastic/elasticsearch#97829]
### Elasticsearch Version

5.2.2

### Java Version

1.8

### OS Version

redhat7.0

### Problem Description

ES cluster has running about 1 month, and it will be oom,the jvm size：31G. the NodeStats instances occupied about 60% JVM memory.
the jvm dump file in MAT show as below :
![111](https://github.com/elastic/elasticsearch/assets/5284670/b0c411e7-3ea6-4941-bd00-aafd7a255c9d)
![222](https://github.com/elastic/elasticsearch/assets/5284670/ac5e8b4d-cfc8-4000-9458-7d2b818197e7)
![333](https://github.com/elastic/elasticsearch/assets/5284670/4dbd835d-da41-4d6f-9c3f-c2e291d7b7e6)

### Steps to Reproduce

show as the problem desc.

**Comment by xufenxu** [comment]
I guess maybe the es-exporter cause this issue, exporter will request the client node to get monitor data per 30 secs. but I don't know why.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 5.2.2 which has passed end-of-life, so I am closing this. If you can reproduce this issue in a supported version then we will reopen it.
