### ISSUE TITLE
Unable to tesselate shape

### ISSUE THREAD

**Issue by mhugo** [elastic/elasticsearch#97904]
### Elasticsearch Version

7.17.6

### Installed Plugins

icu

### Java Version

_bundled_

### OS Version

Linux ThinkPad-P15s-Gen-1 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

With some geo shapes, the indexing fail with an "Unable to tesselate" error, whereas the geo shapes seem to be valid polygons.

Example of such a shape: 
[sample.geojson.txt](https://github.com/elastic/elasticsearch/files/12146847/sample.geojson.txt)

This shape is valid according to gdal/ogr/geos tools.
I suspected initially a difference between GEOS-based tools that work with a default precision model of 32bit floating points when ES works in 16bit. I've then tested for validity using JTS with the FLOATING_SINGLE precision model and it is still valid ...

### Steps to Reproduce

- Create an index with a column mapped to a geo_shape type
- Index the supplied example as a new doc using the geo_shape column

ES should respond with an "unable to tesselate" error.

**Comment by iverase** [comment]
Hello @mhugo,

The version 7.17.6 is not the latest 7. 17.x version and there has been some fixes in the Lucene tessellator on [later versions](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/es-release-notes.html). In particular there has been fixes introduced in 7.17.9 and 7.17.11.

I tried to index the provided example in 7.17.6 and indeed it failed, but after upgrading to 7.17.9, I was able to ingest the polygon successfully. Therefore I recommend to upgrade to 7.17.11+ to get the fixes.

I will close this issue now, please feel free to open an issue if you have issues after the upgrade.

**Comment by mhugo** [comment]
@iverase Thank you very much for your feedback, I should have tried the last version first
