### ISSUE TITLE
EQL: Specify join keys only impacting on specified events inside one whole EQL query

### ISSUE THREAD

**Issue by MagpieRYL** [elastic/elasticsearch#97905]
# Problem Description
As described [eql-sequence](https://www.elastic.co/guide/en/elasticsearch/reference/current/eql-syntax.html#eql-sequences) here, eql's join key constrant is align across all items in a sequence matching.

There are situations writing a rule matching a sequence like, one process established a socket, received data from the socket into a buffer and finally passed the buffer to an execve syscall for command execution, which is a typical reverse-shell attacking behavior. To detecting it with EQL, we need:
* Firstly, use a join key `fd_return` and a join key `arg_sock_fd` correlating the socket establishing event and the data receiving event. `fd_return` and `arg_sock_fd` will have the same integer file descriptor value.
* Secondly, use a join key `p_buff_ret` and a join key `arg_cmd_str` correlating the data receiving event and the `execve` event.`p_buff_ret` and `arg_cmd_str` will have the same string buffer pointer integer value.
* Globally, use a global join key `pid` limiting them within one process.

With mentioned above, we can describe a precise data flow of reverse-shell attacking. But when I tried writing it with EQL:

> rule 1:
```
sequence by pid
      [ any where syscall_event_type == "socket" ] by fd_return
      [ any where syscall_event_type == "recvfrom" ] by arg_sock_fd
```
> rule 2:
```
sequence by pid
      [ any where syscall_event_type == "recvfrom" ] by p_buff_ret
      [ any where syscall_event_type == "execve" ] by arg_cmd_str
```
👆 But I cannot describe this three-events sequence with only one EQL query.
# Feature Request
* Specify join keys only impacting on specified events inside one whole EQL query.

It may looks like:
```
define join key
      group.0: {fd_return, arg_sock_fd}
      group.1: {p_buff_ret, arg_cmd_str}
sequence by pid
      [ any where syscall_event_type == "socket" ] by group.0.fd_return
      [ any where syscall_event_type == "recvfrom" ] by group.0.arg_sock_fd, group.1.p_buff_ret
      [ any where syscall_event_type == "execve" ] by group.1.arg_cmd_str
```

**Comment by wchaparro** [comment]
Superceded by ES|QL
