### ISSUE TITLE
[Fleet Plugin] Add upgrade details field to `.fleet-agents` index

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#97912]
### Description

Future versions of Fleet will be able to show users details about an ongoing Agent upgrade.  Agents will communicate these details to Fleet Server which will, in turn, persist them in the Agent's document in the `.fleet-agents` index.  This will allow the Fleet UI to read the same details and present them to the user.

This issue is the elasticsearch mapping changes required for the new agent upgrade fields.

The proposed structure of the upgrade details field is:

```json
{
  "upgrade_details": { // new field; present when upgrade is in progress
    "target_version": "8.12.0", // version being upgraded to; always present
    "action_id": "xxxxxxxx", // ID of the UPGRADE action
    "state": "UPG_*",
    "metadata": {
      "scheduled_at": "2023-08-09T10:11:12Z", // when state == "UPG_SCHEDULED"
      "download_percent": 16.4, // when state == "UPG_DOWNLOADING"
      "failed_state": "UPG_*" // when state == "UPG_FAILED"
      "error_msg": "" // when state == "UPG_FAILED"
    }
  }
}
```

Where `upgrade_details.state` is expected to hold one of the following values:

| State | Meaning |
| -- | -- |
| `UPG_REQUESTED` | Upgrade requested by user |
| `UPG_SCHEDULED` | Upgrade scheduled for <date/time> |
| `UPG_DOWNLOADING` | Downloading new Agent artifact version <version> |
| `UPG_EXTRACTING` | Extracting new Agent artifact version <version> |
| `UPG_REPLACING` | Replacing old Agent artifact version <version> with new one version <version> |
| `UPG_RESTARTING` | Starting new Agent version <version> |
| `UPG_WATCHING` | Monitoring new Agent version <version> |
| `UPG_ROLLBACK` | Upgrade unsuccessful; rolling back to Agent version <version> |
| `UPG_FAILED` | Upgrade failed due to error <error> from state <state> |

**Comment by juliaElastic** [comment]
@ycombinator Is the work on Elastic Agent side dependent on new fields in ES?

**Comment by ycombinator** [comment]
> @ycombinator Is the work on Elastic Agent side dependent on new fields in ES?

No. By design, all the changes to the system are strictly additive, allowing any version of one component to work with any versions of other components in the system. This also means that the changes (additions) can be made to the system components in any order.
