### ISSUE TITLE
TransportService does not raise exceptions correctly

### ISSUE THREAD

**Issue by polgl** [elastic/elasticsearch#9794]
Hy

I found a bug in the ES Java client (TransportClient):

After one node gets unavailable, our application takes several minutes to reconnect to ES again.
After some investigations it seems like the TransportService can not raise exceptions to the RequestHolders.
raiseNodeDisconnected() cannot match the disconnected node (Object from listedNodes in TransportClientNodesService) with the RequestHolder node (Object from nodes in TransportClientNodesService).

The nodes get matched by their Id but listedNodes contain dummy ids ("#transport#-1") while nodes contains real ids from the cluster.

**Comment by polgl** [comment]
This is a BUG in the Java API: the list with listed nodes never gets updated and thus never contains the right IDs.

**Comment by clintongormley** [comment]
Hi @polgl 

Sorry it has taken a while to look at this.  Are you still seeing this problem in Elasticsearch 2.0?  If so, any chance you'd like to send a PR?

**Comment by polgl** [comment]
Hi @clintongormley here is the diff of a quick fix
I did not manage to write a test with the right conditions for this (netty client, one slow/ blocking request, killing the server without normal shutdown)
This change ensures that the DiscoveryNode object that was connected before is used for disconnecting.
```
--- a/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
+++ b/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
@@ -54,6 +54,7 @@ import java.util.Iterator;
 import java.util.List;
 import java.util.Locale;
 import java.util.Map;
+import java.util.HashMap;
 import java.util.Set;
 import java.util.concurrent.ConcurrentMap;
 import java.util.concurrent.CountDownLatch;
@@ -86,6 +87,7 @@ public class TransportClientNodesService extends AbstractComponent {
 
     private final Object mutex = new Object();
 
+    private volatile Map<DiscoveryNode, DiscoveryNode> discoveredNodesMap = new HashMap<>();
     private volatile List<DiscoveryNode> nodes = Collections.emptyList();
     private volatile List<DiscoveryNode> filteredNodes = Collections.emptyList();
 
@@ -372,7 +374,9 @@ public class TransportClientNodesService extends AbstractComponent {
                     } else if (livenessResponse.getDiscoveryNode() != null) {
                         // use discovered information but do keep the original transport address, so people can control which address is exactly used.
                         DiscoveryNode nodeWithInfo = livenessResponse.getDiscoveryNode();
-                        newNodes.add(new DiscoveryNode(nodeWithInfo.name(), nodeWithInfo.id(), nodeWithInfo.getHostName(), nodeWithInfo.getHostAddress(), listedNode.address(), nodeWithInfo.attributes(), nodeWithInfo.version()));
+                        DiscoveryNode discoveredNode = new DiscoveryNode(nodeWithInfo.name(), nodeWithInfo.id(), nodeWithInfo.getHostName(), nodeWithInfo.getHostAddress(), listedNode.address(), nodeWithInfo.attributes(), nodeWithInfo.version());
+                        newNodes.add(discoveredNode);
+                        discoveredNodesMap.put(listedNode, discoveredNode);
                     } else {
                         // although we asked for one node, our target may not have completed initialization yet and doesn't have cluster nodes
                         logger.debug("node {} didn't return any discovery info, temporarily using transport discovery node", listedNode);
@@ -381,6 +385,10 @@ public class TransportClientNodesService extends AbstractComponent {
                 } catch (Throwable e) {
                     logger.info("failed to get node info for {}, disconnecting...", e, listedNode);
                     transportService.disconnectFromNode(listedNode);
+                    // disconnect from the node that was connected before
+                    if (discoveredNodesMap.containsKey(listedNode)) {
+                        transportService.disconnectFromNode(discoveredNodesMap.get(listedNode));
+                    }
                 }
             }
```

**Comment by clintongormley** [comment]
@bleskes could you take a look at this please?

**Comment by bleskes** [comment]
@polgl I looked at this and I'm a bit puzzled. Here is what I  understand:

1) During the issue of the liveness test the target node disconnects.
2) This somehow makes the liveness request not being canceled but just hang.
3) That causes new nodes not to be picked up.

I don't see how the node disconnect event is missed based on the client code alone - the disconnect even should come for both the "official" node and the one that is connected "light" for the liveness call. Can you elaborate? Also - which version of ES are you referring to? it might something subtle I miss by looking at the wrong version.

**Comment by polgl** [comment]
sorry I may went to fast in my explanation:

1) The node disconnects between 2 liveness tests
2) an other request (search request for example) that was started before but is not yet finished hangs
3) causes the search request not to be canceled and/or retried 

I added a graph the show the sequence of events in the client and the server:

![graph](https://docs.google.com/drawings/d/13sqI2AJ67ljEpGYG-wy6qgaibWCxL8IMlZ3imT2RYAc/pub?w=960&amp;h=720)

What I understood from the code:
1) add node at with a given address
`org.elasticsearch.client.transport.TransportClientNodesService#addTransportAddresses`
creates `DiscoveryNode object 1` with id = `#transport#-0` 

2) test liveness
`org.elasticsearch.client.transport.TransportClientNodesService.SimpleNodeSampler#doSample`
tests liveness for `DiscoveryNode object 1` with id = `#transport#-0` 
gets response with real id and creates `DiscoveryNode object 2` with id = `abcd` 

3) send search request
`org.elasticsearch.transport.TransportService.RequestHolder` holds reference to `DiscoveryNode object 2`  with id = `abcd` 

4) connection loss

5) test liveness again
`org.elasticsearch.client.transport.TransportClientNodesService.SimpleNodeSampler#doSample`
tests liveness for `DiscoveryNode object 1` with id = `#transport#-0` 
node is not available
disconnects from `DiscoveryNode object 1`
`org.elasticsearch.transport.TransportService.Adapter#raiseNodeDisconnected` does not match the `RequestHolder` from 3)
request from 3) is not stopped

**Comment by bleskes** [comment]
Thanks for clarifying @polgl . I think I understand where things go wrong. The NodeSampler is mainly in charge of maintaining a connection to the specified nodes (by sending a liveness command) and validating that the nodes on the other side indeed belong to the same cluster. It isn't responsible for maintaining the nodes that the client is currently connected to and cancelling in flight request. Both of those are the responsibility of the TransportService, which should have detected the connection loss (socket break) in step 4 above and failed all inflight requests to the node.  Something else is going on...

**Comment by clintongormley** [comment]
@bleskes did you ever get anywhere with this?

**Comment by bleskes** [comment]
@clintongormley not really - something was wrong but not exactly fitting the discreption. I think we can close it for now and reopen if something similar pops up - it will be hard to continue debugging without a concrete issue. @polgl if this is still happening for you, feel free to reopen.
