### ISSUE TITLE
8.9.0 Release notes includes PRs not released in 8.9.0

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#97957]
At time of writing the [8.9.0 release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.9.0.html) indicate that this release includes #97840:

<img width="669" alt="image" src="https://github.com/elastic/elasticsearch/assets/5058284/5c1fea7f-6767-4020-adcf-3b2f941650dc">

However that change did not make it to 8.9.0 (it should be released in 8.9.1). I haven't checked for any other PRs like this.

**Comment by abdonpijpelink** [comment]
The erroneous entries for the 8.9.0 release notes have been removed in https://github.com/elastic/elasticsearch/pull/97963

Maybe someone on the @elastic/es-delivery team can take the next piece: ensure it doesn't happen again in the future. 

It sounds like the release manager instructions need to be clarified. They currently instruct the release manager to check out the appropriate branch to generate the release notes. But that may pull in PRs for future patch releases, like in this case, where the 8.9.0 release notes included 8.9.1 PRs. The instructions should clarify that the branch needs to be on the actual git commit of the BC / release in question when generating the release notes.
