### ISSUE TITLE
when bumped up beats version from 7.16 to 8.6.2, indices are not created

### ISSUE THREAD

**Issue by skumarya-tibco** [elastic/elasticsearch#97955]
### Elasticsearch Version

8.6.2

### Java Version

17.0.7 2023-04-18 LTS

### OS Version

MAC OS Darwin Kernel Version 22.5.0

### Problem Description

we were using Elasticsearch version 7.16 earlier since we have bumped up the version to 8.6.2 for elasticsearch, kibana and filebeat indices are not created.
we are using Helm version 3.12.2
Kubernetes version 1.25.4/1.27.3

Have tried your many elastic,kibana and beats pages and tried a few changes in our Yaml
but still, the indices are not created

I don't know if I am missing any part when we bump into version 8.6.2

### Steps to Reproduce

deploy elasticseach,kibana,filebeat version 8.6.2 on the above env of helm and Kubernetes

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by skumarya-tibco** [comment]
Hey i have created an account in the forum as it is on hold, And this work it urgent 
Can you please help me over here with this

**Comment by DaveCTurner** [comment]
I have released the hold on your forum account. But please note that the community forum is staffed by volunteers, there is no SLA for response times. For more details see [the community code of conduct](https://www.elastic.co/community/codeofconduct), particularly the section labelled **Be patient**.
