### ISSUE TITLE
Adjust terminal tests to jdk22 behavior

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#98033]
In JDK22, the behavior of System.console() when the terminal is redirected will change. System.console() will no longer return null in this case. Our Terminal abstraction currently relies on seeing null returned to decide which implementation to use. This issue is a reminder to adjust our Terminal code to understand the new jdk behavior.

See https://bugs.openjdk.org/browse/JDK-8308591

**Comment by rjernst** [comment]
Note to future self: I suspect we will need to add an MRJAR so we can access the new Console.isTerminal() while still compiling against Java 17.

**Comment by mosche** [comment]
@rjernst I just had a brief look at this, @arpadkiraly suggested the ticket. Looks fairly straight forward. Though, considering the lack of support for Java 22 in Gradle at this point, this is probably not feasible yet. WDYT?

**Comment by rjernst** [comment]
This should be doable now with 22 ea builds. You can install the ea build, then run tests with the env var RUNTIME_JAVA_HOME pointing to your build. This should work since the behavior mentioned here is at runtime. Note we will need to continue to support the "old" return value from System.console(), so some logic will be needed in the Terminal to look at the jdk version (see `Runtime.version()`).
