### ISSUE TITLE
Make restore either incremental or full (recovery too?)

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#9806]
today we might reuse files when we restore a snapshot and make recoveries. In snapshot and restore the restore operation should be full or incremental but if the diff between target and source has files that are different in the target we should force a full restore instead of overwriting existing files. Otherwise we might run into situations where future .si files reference the worng files.

**Comment by clintongormley** [comment]
@abeyad can this issue be closed yet?

**Comment by abeyad** [comment]
@clintongormley 
> if the diff between target and source has files that are different in the target we should force a full restore instead of overwriting existing files.

We don't currently do this, so this still needs to be done.

> Otherwise we might run into situations where future .si files reference the worng files

@s1monw could you elaborate on what you mean by this?

**Comment by tlrx** [comment]
@s1monw can you please tell us if that's still something that needs to be done?

**Comment by s1monw** [comment]
@tlrx I think we can close!
