### ISSUE TITLE
Will doc values support ip type in future?

### ISSUE THREAD

**Issue by stonith** [elastic/elasticsearch#9809]
Wondering if doc values will support the ip type in the future. Running a query for unique client ip's across large timespans is a fairly common web log query. We could use not_analyzed string fields but we'd then lose searching via cidr notation.

Thanks.

**Comment by jpountz** [comment]
A quick look at the code looks like doc values should already be supported on ip fields. Is it just a documentation issue or did you try to use doc values on an ip field and it failed?

**Comment by stonith** [comment]
I guess it's a documentation issue, I didn't bother trying it as the docs didn't list IP types as a supported type. I can submit a PR to update the doc if it's already supported.

http://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html
