### ISSUE TITLE
Display error for text_expansion if the queried field does not have the right type

### ISSUE THREAD

**Issue by ioanatia** [elastic/elasticsearch#98098]
### Description

When `text_expansion` receives a field that does not have the `rank_features` type, it simply returns an empty list of results:

```
GET search-books/_search
{
   "query":{
      "text_expansion":{
         "wrong_inexistent_field":{
            "model_id":".elser_model_1",
            "model_text":"What wild animals live in Colorado?"
         }
      }
   }
}
```
response:
```
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  }
}
```
The [`text_expansion` docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-text-expansion-query.html) clearly state that the queried field must be of `rank_features` type, but this is not enforced at the API level.

Other Elasticsearch queries return an error message when the queried field is missing or it does not have a compatible type.

With `rank_features` fields and the ELSER pipeline that users can create in Kibana in the Enterprise Search plugin, it is very easy to miss exactly what field needs to be queried, because the `rank_features` fields are deeply nested under `ml.inference`. For example, this is a working query:

```
GET search-books/_search
{
   "query":{
      "text_expansion":{
         "ml.inference.description_expanded.predicted_value":{
            "model_id":".elser_model_1",
            "model_text":"What wild animals live in Colorado?"
         }
      }
   }
}
```

**Comment by jimczi** [comment]
It seems reasonable to go with the option of triggering an error. However, I think it might be a good idea to include support for `ignore_unmapped` similar to how it's implemented in other queries. This way, we can address situations where certain indices in the query might not have the specified field in their mapping.

**Comment by kderusso** [comment]
Correct @saikatsarkar056 this should work for both field types and error for others.

**Comment by saikatsarkar056** [comment]
The [PR](https://github.com/elastic/elasticsearch/pull/105581) has been merged. We can close this issue since the PR has covered the required changes.

**Comment by kderusso** [comment]
@saikatsarkar056 FYI - next time if you put "resolves <your issue link>" in the PR it will auto close the issue 🙂

**Comment by saikatsarkar056** [comment]
> @saikatsarkar056 FYI - next time if you put "resolves " in the PR it will auto close the issue 🙂

Can we put "resolves " as comment in the PR? Can you please provide me with an example PR?

This is something new I learned about GitHub. 😃
