### ISSUE TITLE
Elastic Security Dashboard: Ad-hoc Data View Creation Error Despite Successful Log Transfer from Logstash to Elasticsearch

### ISSUE THREAD

**Issue by akash0009922** [elastic/elasticsearch#98109]
![Stream](https://github.com/elastic/elasticsearch/assets/124325075/0473453f-1043-4557-9376-5f3f3b9fef2a)
![Report 3](https://github.com/elastic/elasticsearch/assets/124325075/84558e71-bccc-4870-8871-0a11b6151c2d)
![Report 2](https://github.com/elastic/elasticsearch/assets/124325075/bb6b9de8-3307-4a95-8ee2-451d9737ab4f)
![Report 1](https://github.com/elastic/elasticsearch/assets/124325075/4e55ac7b-cb7c-48c4-85cb-4670e3b6dfdf)

### Elasticsearch Version

Elasticsearch version: 8.9

### Installed Plugins

No additional plugins installed.

### Java Version

java version "20.0.1"

### OS Version

Windows 10 Pro

### Problem Description

While working with the Elastic Security dashboard, I've been consistently encountering an issue when I attempt to create or access a data view. The error message that displays is as follows:

"An error has occurred creating the ad-hoc data view
Could not locate that data view (id: c5085743-9c9f-4e3a-a97d-15e61407cadd), 
[click here to re-create it](management/kibana/dataViews)"

This issue persists despite several troubleshooting steps I've undertaken, including deleting and re-creating the data view, as well as updating to the latest version of Elasticsearch and Kibana.

Despite sending logs through Logstash to Elasticsearch successfully, and being able to visualize the logs in the Kibana Discover section, I am unable to utilize them in the Elastic Security dashboard due to this error. This has impeded my progress on creating custom rules for the audit logs, as I am unable to get alerts in the Elastic Security dashboard.

This issue seems to persist across different data view ids and doesn't seem to be tied to a specific data view id.

### Steps to Reproduce

Send logs from Logstash to Elasticsearch.
Verify that the logs have been successfully received in Kibana's discover section.
Attempt to create an ad-hoc data view in the Elastic Security Dashboard.
Encounter the error "Could not locate that data view (id: [insert your ID]), click here to re-create it."
Delete the data view and attempt to recreate it, but encounter the same error again.

### Logs (if relevant)

```[tasklist]
### Tasks
```

**Comment by astefan** [comment]
@akash0009922 this looks like something for the Kibana team to have a look at, or to be discussed outside github (where there is a place for confirmed bugs). Do you mind either taking this issue to [discuss.elastic.co](https://discuss.elastic.co/) or recreate the issue in https://github.com/elastic/kibana/issues
