### ISSUE TITLE
error while making a request

### ISSUE THREAD

**Issue by LuisRG98** [elastic/elasticsearch#98178]
I got this error on my database reports, but I can't get the isuue

Reason: class org.elasticsearch.index.fielddata.plain.SortedNumericIndexFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexGeoPointFieldData (org.elasticsearch.index.fielddata.plain.SortedNumericIndexFieldData and org.elasticsearch.index.fielddata.IndexGeoPointFieldData are in unnamed module of loader 'app'

Here is how my index settings look like
{
  "latdeal_products" : {
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "mapping" : {
          "total_fields" : {
            "limit" : "100000"
          }
        },
        "number_of_shards" : "3",
        "provided_name" : "latdeal_products",
        "creation_date" : "1691080834398",
        "number_of_replicas" : "2",
        "uuid" : "GUJHyjctTOCR6Wr07Lk99Q",
        "version" : {
          "created" : "7130099"
        }
      }
    }
  }
}

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
