### ISSUE TITLE
Identify master (if known) in discovery troubleshooting messages

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#98191]
We recently spent some time troubleshooting a node that would not join a cluster because it could not connect to the master, although it could connect to the other nodes in the cluster. In this situation the `ClusterFormationFailureHelper` indicates that it has discovered a possible quorum of nodes but does not call out that this quorum does not include the node that the discovered nodes consider to be the elected master, which prevents another election from occurring. Yet the `PeerFinder` does know that there's an elected master out there, so it would help to call out that we cannot ourselves discover it in the `ClusterFormationFailureHelper` message.

Additionally the `PeerFinder` reports that it is failing to connect to a node in its logs but fails to call out that the failing node is apparently the elected master. It would also help to mention this fact in the relevant failure logs.

**Comment by DiannaHohensee** [comment]
In https://github.com/elastic/elasticsearch/pull/108107 I'm improving the NotMasterException response to include who is the master, which the ClusterFormationFailureHelper (on the node failing to join) will eventually log after 10 seconds. I'm not sure whether you only wanted to identify the known master for debugging via the logs, or also take some action in the code to try to join the identified new master.

**Comment by DaveCTurner** [comment]
It's only for debugging via the logs (we already try and join a master once we've identified it) but we need to log this information even if we can't contact the master for some reason -it can't just rely on a response to a join request.

**Comment by nicktindall** [comment]
> Additionally the PeerFinder reports that it is failing to connect to a node in its logs but fails to call out that the failing node is apparently the elected master. It would also help to mention this fact in the relevant failure logs.

Appears to have been addressed by #104396

**Comment by DaveCTurner** [comment]
Ah you're right, sorry, I didn't realise we'd already basically addressed this. Yeah no further action needed here I think.
