### ISSUE TITLE
Allow store property on object type.

### ISSUE THREAD

**Issue by kiljag** [elastic/elasticsearch#98274]
### Description

Hi.
I have a use case where I need to store a small nested json as a stored field and to skip indexing on it. But below combination is not supported while creating index templates.

{
   "type": "object",
   "enabled": false,
   "store": true
}

I tested below on Elastic search v8.9.0

```
PUT _index_template/metadata_template
{
  "index_patterns": ["index-*"],
  "template": {
    "mappings": {
      "dynamic_templates": [
        {
          "metadata_fields": {
            "match": "metadata*",
            "mapping": {
              "type": "object",
              "enabled": false,
              "store": true
            }
          }
        }
      ]
    }
  }
}
```
Error: "Unknown mapping attributes [{store=true}]"

Any particular reason why this is not supported? and if there is no technical constraint, can this be included as a new feature?

Thank you.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
