### ISSUE TITLE
Discovery service as endpoint provider not recognised

### ISSUE THREAD

**Issue by nealder** [elastic/elasticsearch#98284]
### Elasticsearch Version

8.8.1

### Installed Plugins

analysis-stempel, analysis-icu

### Java Version

_bundled_

### OS Version

 AKSUbuntu-2204gen2containerd-202307.12.0

### Problem Description

In previous version like 7.17 (deprecated, but working) and before, the discovery.zen option was used to handle discovery of other nodes in our multi-node cluster. While migrating to 8.8.1 following [this guide](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/breaking-changes.html) and [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/modules-discovery-settings.html) we tried to replace `discovery.zen.ping.unicast.hosts: "discovery-service-name"` with `discovery.seed_hosts: "discovery-service-name"` as it is stated

> This setting was previously known as discovery.zen.ping.unicast.hosts.

. However after building the cluster (hosted in azure on AKS, using HELM charts) we experienced that the master nodes are started as single-node cluster mode and the data and client pods are unable to discover master nodes. 
Log: 
`{"@timestamp":"2023-08-02T14:15:49.950Z", "log.level": "WARN", "message":"address [127.0.0.1:9304], node [null], requesting [false] discovery result: [][127.0.0.1:9304] connect_exception: Failed execution: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9304: Connection refused: /127.0.0.1:9304: Connection refused", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[company-elastic-elasticsearch-client-8499ff9b9-rzszb][generic][T#2]","log.logger":"org.elasticsearch.discovery.PeerFinder","elasticsearch.node.name":"company-elastic-elasticsearch-client-8499ff9b9-rzszb","elasticsearch.cluster.name":"elasticsearch"}`

We figured out that the 127.0.0.1 IP is being used as a fall back method like if we forgot to put something in the discovery.seed_hosts setting. After further investigation we found that the java code used in 7.17 under [zen discovery ping](https://github.com/elastic/elasticsearch/tree/v7.17.0/server/src/main/java/org/elasticsearch/discovery/zen) is different in behavior to the [discovery used in 8.8.1](https://github.com/elastic/elasticsearch/tree/8.8/server/src/main/java/org/elasticsearch/discovery) . 

We eliminated all other causes for our discovery service not being called from other nodes BY NAME. In case we used the IP of the discovery service like `discovery.seed_hosts: - 10.244.105.109` the discovery succeeded. However it should work by name resolution, since the IP of the discovery Service can change thorough the lifetime of the cluster (months).

### Steps to Reproduce

1. Create a new elasticsearch cluster with multi-node setup with the following YAML (this is just part of the YAML I can't provide the rest):
`apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  elasticsearch.yml: |-
    cluster.name: {{ .Values.cluster.name }}
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    xpack.security.enabled: ${XPACK_SECURITY_ENABLED:false}
    discovery.seed_hosts: 
      - company-elastic-elasticsearch-discovery
    cluster.initial_master_nodes:
      - company-elastic-elasticsearch-master-0
      - company-elastic-elasticsearch-master-1`
      
2. Nodes fail readiness probes as data and client nodes would require master node(s) to report ready/running.

**Comment by dliappis** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

In the meain time, instead of self deploying on AKS, you might be interested using the [Elastic Cloud on Kubernetes Operator](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-quickstart.html) which supports AKS and `helm`.
If you aren't using Azure ARM, you might also want to look into [Azure Classic hosts providers](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/discovery-hosts-providers.html#azure-classic-hosts-provider).
