### ISSUE TITLE
MoreLikeThis (MLT, more_like_this) results regression (ES 6.8 vs 8.9)

### ISSUE THREAD

**Issue by rand0m86** [elastic/elasticsearch#98293]
### Elasticsearch Version

8.9.0

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

We are working on migration from ES 6.8 to version 8.9.
One of the issues that we came around is that for some of our queries which use MLT we started getting more results (anything betwen 0% and +58%) for the index containing 45M records.
The query looks like the following:

```json
"more_like_this": {
  "fields": [
    "fulltext"
  ],
  "like": [
    {
      "_id": "xxxxx"
    }
  ],
  "min_doc_freq": 25,
  "minimum_should_match": "50%",
  "min_term_freq": 1
}
```

In this example, `fulltext` field is an array of all string and numeric values (type: text), which is searched by default if we do not know which field to search for.

I started looking at the documents which are now matching the query but did not in 6.8.
I used `Term Vectors API` to query for `fulltext` field on both documents (original and the matched one) and found that in total, the first document (the one which is used in MLT query) has 318 unique terms.
The document which matched this query has 359 unique terms.
In total, fulltext field has `76` overlapping terms, which is much less than `50%` specified in a search query.

Was there, maybe, a breaking change for this feature? I could not find anything in the changelogs.

### Steps to Reproduce

**Mappings**
```json
{
  "properties": {
    "fulltext": {
      "type": "text",
      "analyzer": "custom_analyzer"
    },
```

**Settings**
Mostly normalization, removal of hyphens, etc

**Sample of fulltext field**
```json
    "fulltext": [
      "pyridoxic acid",
      "12345613",
      "Johnson",
      "paracetamol",
      "Doe J.M.",
      "A.",
      "blood level",
      "Vitamin D",
     "18",
     ...
]
```

**Comment by benwtrent** [comment]
I am pretty sure this is caused by: https://issues.apache.org/jira/browse/LUCENE-8333

Lucene switched to use maxDoc which includes deleted docs. I am guessing in your test you have deleted docs in the index, which contribute to limit considered.
