### ISSUE TITLE
default timezone per index

### ISSUE THREAD

**Issue by Kallin** [elastic/elasticsearch#9830]
I'm doing a lot of time-based reporting using elastic, and have to remember to always set the offset to -5 (EST) whenever I do something like a date-range agg, otherwise I get documents from the wrong day in my buckets. It would be nice if I could specify a default timezone per index, that would be used for all time-based filters/aggs etc, but that could be overridden if necessary.

**Comment by golenazfazli** [comment]
Note:report issue

**Comment by clintongormley** [comment]
Sorry it has taken a while to get to this.  Unfortunately, this wouldn't work on multi-index search.  All timezones need to be the same across all indices, otherwise the results would be meaningless.
