### ISSUE TITLE
security manager for groovy?

### ISSUE THREAD

**Issue by Kallin** [elastic/elasticsearch#9831]
Was a bummer to see that dynamic groovy support has been knocked out. I read that the groovy team was consulted, but is there really nothing that can be done? I saw this article from a few years back, though I am not familiar with the java SecurityManager:

http://www.chrismoos.com/2010/03/24/groovy-scripts-and-jvm-security/

Would be great to have a way to do arithmetic and basic loops etc. in scripts. I'm using groovy for a scripted metric agg, and I don't see any way to do that anymore other than storing 4 separate groovy scripts on each node (init/map/combine/reduce). I would even say that groovy scripting would be great even if no classes were supported other than a predefined list used for these basic calculations. I understand the dynamic nature might make it impossible to ensure security, but if it could be done with severe limitations, I'd still say it's tremendously valuable.

**Comment by clintongormley** [comment]
The Java security manager is now used extensively in Elasticsearch.  And on top of that, we're writing our own scripting language which can be enabled by default  #13084.

Closing
