### ISSUE TITLE
Group all synonym APIs under a single namespace in the rest-api-spec

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch#98364]
### Description

The recently introduced synonyms API has its rest-api-spec definition spread over 3 different namespaces: `synonyms`, `synonym_rule` and `synonyms_sets`. These namespaces translate directly into packages/modules in Elasticsearch clients who use these namespace identifiers in code generations.

It would be better to have all of the synonyms API endpoints under a single `synonyms` namespace. This ensures a cleaner structure of client libraries, and is also more consistent with other namespaces. The renaming can be as follows:
* `synonym_rule.{x}` --> `synonyms.{x)_synonym_rule`
* `synonyms.{x}` --> `synonyms.{x)_synonym`
* `synonyms_sets.{x}` --> `synonyms.{x}_synonyms_set`

Furthermore, it would be better for the path parameter to be named `id` when there is a single id, and named `set_id`, `rule_id`, etc when there are multiple identifiers. This is firstly more consistent with the property names in request/response bodies (`id`), and avoids conflicts with the properties with the same name in the request bodies (e.g. `synonyms_set`).

My understanding is that this only requires to rename and update the rest-api-spec files and update the yaml-test files (which BTW are under a single `synonyms` namespace).

Assigning to @carlosdelest since he originated this new API.

**Comment by carlosdelest** [comment]
Opened Draft PRs:
- https://github.com/elastic/elasticsearch/pull/98383
- https://github.com/elastic/elasticsearch-specification/pull/2234
