### ISSUE TITLE
Unix packaging tests failure

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#98442]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.9+multijob+packaging-tests-unix/os=debian-10-packaging/226/

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

8.9, 7.17

### Failure excerpt

11:36:49 Err:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
11:36:49   400   [IP: 34.74.126.177 443]
11:36:49 Get:8 https://deb.debian.org/debian buster-backports InRelease [51.4 kB]
11:36:50 Get:9 https://deb.debian.org/debian-security buster/updates/main Sources [422 kB]
11:36:50 Get:10 https://deb.debian.org/debian-security buster/updates/main amd64 Packages [547 kB]
11:36:50 Get:11 https://deb.debian.org/debian-security buster/updates/main Translation-en [296 kB]
11:36:51 Reading package lists...
11:36:51 E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/buster/InRelease  400   [IP: 34.74.126.177 443]
11:36:51 E: The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease' is no longer signed.

**Comment by mark-vieira** [comment]
Sounds like a transient issue talking to the apt repos. These jobs are passing now.
