### ISSUE TITLE
Writing a snapshot with 8.10.0 makes its repository unreadable for older versions

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#98454]
### Elasticsearch Version

8.10.0, 8.10.1, 8.10.2

### Java Version

_bundled_

### OS Version

macOS 13.5

### Problem Description

While investigating https://github.com/elastic/elasticsearch/issues/94459, we found that re-enabling tests in MultiVersionRepositoryAccessIT uncovers a different bug in step3 of MultiVersionRepositoryAccessIT, specifically inside [`testUpgradeMovesRepoToNewMetaVersion`](https://github.com/elastic/elasticsearch/blob/ef5077011bfb7f2a9a3f1a3b31506c412d3f34ee/qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java#L176C17-L176C53). 

This multi-step test verifies that a snapshot repository is not getting corrupted and continues to function properly when accessed by multiple clusters of different versions.
Steps are:
1. create and restore repositories and snapshots in a old (e.g. 8.9.0 here) cluster
2. does the same in a new (current - 8.11.0-SNAPSHOT) cluster
3. re-do it in a old (e.g. 8.9.0 here) cluster

Step 3 is where the test fails:
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:57095], URI [/_snapshot/testUpgradeMovesRepoToNewMetaVersion], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"repository_exception","reason":"[testUpgradeMovesRepoToNewMetaVersion] Unexpected exception when loading repository data"}],"type":"repository_exception","reason":"[testUpgradeMovesRepoToNewMetaVersion] Unexpected exception when loading repository data","caused_by":{"type":"illegal_argument_exception","reason":"the version needs to contain major, minor, and revision, and optionally the build: 8100099"}},"status":500}
```
The repository metadata is saved in the cluster shared repo (a BlobStore based implementation of snapshot repository in these tests) by serializing a RepositoryData object to JSON (XContent).

It seems that code in RepositoryData.java, starting from 8.10, wants to write the minimum version as an int instead of a string (`snapshotsToXContent` in `RepositoryData.java`, around [lines 681-686](https://github.com/elastic/elasticsearch/blob/ef5077011bfb7f2a9a3f1a3b31506c412d3f34ee/server/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L681-L686)) and tries to read it accordingly (`parseIndexVersion` also in `RepositoryData.java`, [lines 963 and following](https://github.com/elastic/elasticsearch/blob/ef5077011bfb7f2a9a3f1a3b31506c412d3f34ee/server/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L956-L965)). 

However, code in 8.9 read and parses the serialized version as a string. This means that if a 8.9 cluster tries to read the shared repository metadata, the serialized integer version (8100099) is seen and parsed as a string by `Version.fromString(parser.text())`)and since it is not in the dotted format, it fails with the IllegalArgumentException above.

Therefore a 8.9 cluster cannot read the repository metadata at all - the test for example does not fail creating or restoring a snapshot, but while creating a repository. Snapshot info with the new (8.10) integer version format prevents the XContent from being parsed correctly.

### Steps to Reproduce

It can be reproduced locally with:
```
./gradlew :qa:repository-multi-version:v8.9.0#Step3OldClusterTest --tests "org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testUpgradeMovesRepoToNewMetaVersion"
```
or on CI (see for example [this](https://gradle-enterprise.elastic.co/s/dqeqlteqabo5m/console-log?anchor=2375&page=3)).
Just remember to remove the `AwaitsFix` on top of `MultiVersionRepositoryAccessIT.java`.

**Comment by williamrandolph** [comment]
We believe this is a blocker because it will break any setup where multiple clusters of different versions are trying to read from the same repository. Analysis:

Let’s say a user has an 8.9.x cluster that's taking snapshots to some repository in S3. They want to take some indices from that snapshot into a different cluster, running 8.10. When the user creates the repository on the 8.10 cluster, it will rewrite the repository metadata using the version format that we changed to in 8.10. At this point, the 8.9 cluster will fail when it reads repository data, and this might break its ability to take snapshots, risking data loss. (I can try to verify that scenario at some point.)

We probably should have done what we did with system indices, and keep a placeholder version in the metadata for compatibility with old nodes, while writing the new version format into a new field.

**Comment by gwbrown** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/5mqw64kr4gftm

**Comment by DaveCTurner** [comment]
We missed that #100605 needed to be backported to 8.11. Doing that now.

**Comment by DaveCTurner** [comment]
Ok backport done, I think this is resolved now.

**Comment by ldematte** [comment]
Thank you Dave for taking good care of this!
