### ISSUE TITLE
_all field setting should allow for excluding fields by default

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#9846]
The current behavior of the _all field is to be enabled by default and `include_in_all` on all fields by default.

While fields can be individually opted-out of _all, and _all completely disabled for a type, a way to enable _all but use a white-list approach on fields is missing.

E.g. something like

```json
{
    "person" : {
        "_all" : {"enabled" : true, "include_by_deafult": false},
        "properties" : {
            "simple1" : {"type" : "string", "include_in_all" : true},
            "simple2" : {"type" : "string"}
        }
    }
}
```

So enabled and include_by_default are true by default to match the current behavior, but with a simple change to `include_by_default` you can change _all's behavior to be a white-list approach as opposed to the current black-list approach

**Comment by dadoonet** [comment]
I would really use copy_to feature instead of _all field.

**Comment by synhershko** [comment]
This is mostly a concern for Kibana users who don't want everything searchable by default - real world documents can become rather big, and Kibana still searches on _all by default.

Would copy_to preserve per-field analysis like _all does? if so, that should be specified in the docs.

**Comment by clintongormley** [comment]
@synhershko The `_all` field doesn't preserve per-field analysis.  It has its own analyzer.

**Comment by synhershko** [comment]
@clintongormley ok, must be confusing this with another feature (preserving boosts maybe?)

Nevertheless, would love an easy way to exclude fields by default from _all - right now I have to use a template or use _default in mapping

**Comment by javanna** [comment]
I second @dadoonet , I would even disable the `_all` field for this usecase and use the `copy_to` to have your own custom catch_all field(s), which will hold only the content that you want it to contain.

**Comment by clintongormley** [comment]
This can be done today:

    PUT t
    {
      "mappings": {
        "t": {
          "include_in_all": false,
          "properties": {
            "foo": {
              "type": "string",
              "include_in_all": true 
            },
            "bar": {
              "type": "string"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "foo": "one",
      "bar": "two"
    }
    
This matches:

    GET t/_search?q=one

This doesn't:
    
    GET t/_search?q=two
