### ISSUE TITLE
Ability to search by geo via the querystring

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#9847]
I was trying to search by one of my geo fields via a query string (search at a single location) and was unable to do so. It would be great to also be able to do a geo search and put a radius (kinda like a number range query) via the query string.

I came across the following post where others were also asking for this: http://stackoverflow.com/questions/26371753/elasticsearch-query-string-query-on-geo

**Comment by niemyjski** [comment]
I think this would be an awesome feature. I could find all the ice cream shops in a 5 mile radius in 20 characters or less :).

**Comment by clintongormley** [comment]
This would have to be implemented in Lucene, as we use their query parser.
