### ISSUE TITLE
Aggs: Terms filtering should leverage Terms.intersect

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#9848]
Our approach at terms filtering today is naive (and slow) since we check the regular expression against every possible term in order to figure out whether is is included or not. We should switch to Lucene's RegExp and terms intersection in order to advance quickly to the next matching term and build the bit that that contains allowed terms ordinals more quickly.

This would be a breaking change since the regexp syntax is not exactly the same, but it would also have the benefit of becoming consistent with regexp queries.

**Comment by jpountz** [comment]
This would likely fix #7526.

**Comment by clintongormley** [comment]
+1

**Comment by jpountz** [comment]
Closed through https://github.com/elastic/elasticsearch/pull/10418
