### ISSUE TITLE
Stable plugins have null `org.elasticsearch.plugins.PluginDescriptor#classname` which causes NPEs

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#98584]
We pass `null` for the class name here:

https://github.com/elastic/elasticsearch/blob/f086dd18ddc705bf84a1ff99d35196ec2498fd52/server/src/main/java/org/elasticsearch/plugins/PluginDescriptor.java#L261

However the class name is mandatory for the transport protocol today:

https://github.com/elastic/elasticsearch/blob/f086dd18ddc705bf84a1ff99d35196ec2498fd52/server/src/main/java/org/elasticsearch/plugins/PluginDescriptor.java#L156

This prevents various APIs from working in a cluster with stable plugins installed.

**Comment by dreamquster** [comment]
So how to solve this bug? From 2022.7, stable plugin has no 'classname' field.  Should it adjust serialize 'classname' as optional string when it's writing into stream, then read optionally from streeam ? Or forcing stable plugin to have 'classfield'?
