### ISSUE TITLE
Recent images are missing on docker hub 7.17.11+ / 8.8.2+

### ISSUE THREAD

**Issue by IT-Cru** [elastic/elasticsearch#98645]
### Elasticsearch Version

7.17.x / 8.8.x / 8.9.x

### Installed Plugins

- No extra plugins.

### Java Version

_bundled_

### OS Version

docker / docker hub

### Problem Description

Currently latest releases of Elasticsearch docker images are not available at docker hub.

Latest version which you could pull from docker hub are:

* 7.17.10
* 8.8.1

Would be nice if all missing releases for 7.17.x, 8.8.x and 8.9.x could be also pulled from docker hub again. Thx.

### Steps to Reproduce

Check https://hub.docker.com/_/elasticsearch/

**Comment by mark-vieira** [comment]
@elastic/release-eng any ideas why our recent releases are not available on DockerHub?

**Comment by DaveSys911** [comment]
@mark-vieira yeap, we had a bug misplacing some of the tags. Fix already in progress and can be tracked here https://github.com/docker-library/official-images/issues/15091

**Comment by IT-Cru** [comment]
I think this issue could be closed. New Elasticsearch release tags are available on docker hub again.

- [x] 7.17.12
- [x] 7.17.13
- [x] 8.8.2
- [x] 8.9.0
- [x] 8.9.1
- [x] 8.9.2

**Comment by alsayasneh** [comment]
Closing this issue as Elasticsearch release tags are available on docker hub
