### ISSUE TITLE
Non-atomic operation on volatile field "org.elasticsearch.indices.IndicesQueryCache#sharedRamBytesUsed"

### ISSUE THREAD

**Issue by oleg-smith** [elastic/elasticsearch#98647]
### Elasticsearch Version

8.8.0

### Java Version

_bundled_

### OS Version

centos

### Problem Description

Non-atomic operation on volatile field "org.elasticsearch.indices.IndicesQueryCache#sharedRamBytesUsed" could cause incorrect results in IndexQueryCache statistics calculation when this field is updated concurrently

https://github.com/elastic/elasticsearch/blob/51d1a33c994e6296033309b45ab5b3af1bcd7954/server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java#L309

There are similar instances for other fields:

https://github.com/elastic/elasticsearch/blob/51d1a33c994e6296033309b45ab5b3af1bcd7954/server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java#L317

### Steps to Reproduce

N/A

**Comment by javanna** [comment]
As far as I understand, the caller acquires a write lock, hence there are no concurrent writes happening, which is why non-atomic volatile fields are fine in this specific case. I will close this for now, feel free to add comments if you think otherwise.
