### ISSUE TITLE
Reconsider which aggregations can support parallel execution

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#98669]
Currently parallel execution isn't enabled by default, but even when it is enabled then the following aggregations are set up the never execute in parallel: `scripted_metric`, `parent` , `terms`, `multi_terms`, and `significant_terms`.

There two main raisons for this is either precision of an aggregation will be different when execution in parallel mode or the aggregation couldn't be accessed from different threads. For latter, as part of #98204, the post collection happens on the same thread as the actual collection. 

For the former reason, we properly need to get a better feeling what the impact in precision is in practise for the aggregations in question (for `terms`, `multi_terms` and `significant_terms`) and update the documentation about the additional loss in precision (next to the loss of precision when running these aggs on multiple shards).

**Comment by wchaparro** [comment]
Close as completed @iverase

**Comment by vanschelven** [comment]
> Currently parallel execution [of aggregations] isn't enabled by default, but even when it is enabled

This would seem to imply it's a possibility using some parameter/configuration method. I can't find any documentation on that though.
