### ISSUE TITLE
[GEO] Expose JTS SelfTouchingRingFormingHoleValid in GeoShape mapping

### ISSUE THREAD

**Issue by clement-tourriere** [elastic/elasticsearch#9871]
Indexing a polygon with a self touching condition raises an exception. 

For an example, look at this valid geojson (take from natural earth) : https://gist.github.com/clement-tourriere/d544420ebb0490a194d0

It would be great to expose, in geo_shape mapping, the possibility to make this type of polygon valid (set JTS isSelfTouchingRingFormingHoleValid to true).

**Comment by nknize** [comment]
Similar to #9511 

tldr; The proposed behavior violates the OGC SFA specification - which ES 1.4.3+ is now compliant. Per the spec, self touching polys should be converted to ```multipolygon``` or multiple ```polygon``` objects.  

In many areas JTS functionality is overridden for performance and correctness (e.g., winding order) so allowing this behavior not only violates the OGC spec, but is not as trivial as enabling the JTS flag.

**Comment by nknize** [comment]
Resolved in commit 0ed8d47f37b22aa4a2c03ef4c2d8c227d319f332
