### ISSUE TITLE
Prevent create automatically data views

### ISSUE THREAD

**Issue by mkatana-silkycoders** [elastic/elasticsearch#98804]
### Description

Hi,

prevent create automatically data views by Elasticsearch or whatever this creates? I dont want to elasticsearch or kibana create data views like metrics-*, filbeat-* etc.

**Comment by stu-elastic** [comment]
Hi, @mkatana-silkycoders this is more appropriate for the https://github.com/elastic/kibana/ repo.  The elasticsearch engine does not create any dataviews by default.
