### ISSUE TITLE
Highlighting on wildcard fields should only include appropriate fields

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#9881]
If you highlight on `*` fields today, it includes all fields, regardless of whether they are appropriate for highlighting or not.

Instead, we should automatically include only fields that can be highlighted by the specified highlighter, ie ignore `not_analyzed` fields, numbers, dates, etc.  If the `fvh` is specified, then only highlight on fields with positions and offsets, and similar for the postings highlighter.

Fixes https://github.com/elasticsearch/elasticsearch/issues/5836

**Comment by kimchy** [comment]
I think that `*` should be expanded to any case where there is a wildcard used, like here: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java#L82

**Comment by ppf2** [comment]
+1 

This is ultimately causing Kibana 4's document table component to fail loading when there are large text fields present (even when it is not necessary to highlight the large text field).   Here is an example query generated by Kibana 4's document table visualization:

https://gist.github.com/ppf2/f4e27207c70b99c67248

**Comment by ppf2** [comment]
There is an increasing # of Kibana 4 users running into this (https://github.com/elastic/kibana/issues/2782)

**Comment by bobrik** [comment]
I really hope that could be fixed soon, kibana is unusable for us because of this issue.

**Comment by nik9000** [comment]
> https://gist.github.com/ppf2/f4e27207c70b99c67248

Without a stack trace its hard to be sure this is highlighting but I suspect you tried it without and it works.

Maybe we can add an excludes expression so Kibana can do:
```json
"*": {
  "excludes": "comments/commont.raw|_*"
}
```
or whatever it needs to do.That'd be pretty simple.
