### ISSUE TITLE
Lucene Expressions can't subtract two date values

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#9884]
We have many docs in Elasticsearch with two date fields. When trying to have a scripted field to compute the date differences we get `0`s. The date fields are in the format of `dd/mm/yyyy` with proper mapping. I can confirm date field values are represented as a number (as expected).

Only subtraction between two fields didn't work; adding two date fields or adding or subtracting a constant worked perfectly fine.

From Kibana:

```
{
  "size": 0,
  "query": {
    "query_string": {
      "analyze_wildcard": true,
      "query": "*"
    }
  },
  "aggs": {
    "2": {
      "terms": {
        "script": "doc['dispatchDate'].value-doc['registrationDate'].value",
        "lang": "expression",
        "size": 5,
        "order": {
          "_count": "desc"
        },
        "valueType": "float"
      }
    }
  }
}
```

```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1001,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": 0,
          "doc_count": 1001
        }
      ]
    }
  }
}
```

FWIW it may be a Kibana bug marking this as `type:float`

**Comment by clintongormley** [comment]
Hi @synhershko 

This worked for me on 1.4.3:

    DELETE t
    
    PUT /t/t/1
    {
      "one": "2014-11-01",
      "two": "2014-12-01"
    }
    
    GET /t/_search
    {
      "size": 0,
      "aggs": {
        "2": {
          "terms": {
            "script": "doc['two'].value-doc['one'].value",
            "lang": "expression",
            "size": 5,
            "order": {
              "_count": "desc"
            },
            "valueType": "float"
          }
        }
      }
    }

returns:

    {
       "took": 3,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 1,
          "max_score": 0,
          "hits": []
       },
       "aggregations": {
          "2": {
             "doc_count_error_upper_bound": 0,
             "sum_other_doc_count": 0,
             "buckets": [
                {
                   "key": 2592000000,
                   "doc_count": 1
                }
             ]
          }
       }
    }

Perhaps your dates aren't mapped as dates?

**Comment by synhershko** [comment]
@clintongormley they were mapped as dates, we were able to do other types of math. This was using 1.4.4 IIRC, will look again later

**Comment by synhershko** [comment]
Closing this for now, will reopen if I can come up with a minimal repro
