### ISSUE TITLE
Allow highlighting to work on script fields

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9890]
I have a use case where it would be helpful to use the `highlight_query` to highlight script fields to minimize returning/highlighting an otherwise massive string (or even just highlighting general, but this might be easier):

```
{
  "query": {
    "match_all": {}
  },
  "script_fields": {
    "my_script_field": {
      "script": "doc['my.enormous.string.field'].value.substring(x, y)"
    }
  },
  "highlight": {
    "fields": {
      "other": {
        "highlight_query": {
          "match": {
            "my_script_field": {
              "query": "whatever",
              "analyzer": "standard"
            }
          }
        }
      }
    }
  }
}
```

Naturally that is specifying the _search_ analyzer, but it could be treated as _both_ the index and search analyzer for highlighting (if it even needs to do that much).

**Comment by clintongormley** [comment]
Hi @pickypg 

What is the use case exactly? Not returning an enormous string doesn't sound valid, because you should get back fragments of the specified size.

**Comment by pickypg** [comment]
@clintongormley The intended use case is effectively to page an enormous string field, while still supporting highlighting.

**Comment by nik9000** [comment]
> @clintongormley The intended use case is effectively to page an enormous string field, while still supporting highlighting.

Not to steal any thunder from elasticsearch itself but I'm happy to work with you at https://github.com/wikimedia/search-highlighter - I can't really tell what you are looking for but you might want to have a look at the [Segmenter](https://github.com/wikimedia/search-highlighter/blob/master/experimental-highlighter-core/src/main/java/org/wikimedia/search/highlighter/experimental/Segmenter.java) interface.  Its designed to allow relatively fine grained control over what segments _might_ be acceptable.

Either here or in the highlighter plugin you'd need some kind of curl recreation of what sort of paging you are going for.

**Comment by clintongormley** [comment]
@pickypg how many highlighted snippets (or fragments) are you intending to retrieve from each doc?  If you want (eg) the best 5 snippets, then you'd be better of by indexing the string with `index_options` set to `offsets`, and using the postings highlighter (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-highlighting.html#postings-highlighter)

That way Elasticsearch already knows the positions of each word in the original string, and it can return them without have to reanalyze any text on the fly.

Alternatively, if you're really wanting multiple fragments from each "page" (or whatever), then perhaps you'd be better indexing the document as multiple documents.

**Comment by pickypg** [comment]
I have created the issue over at the wikimedia/search-highlighter#12 per @nik9000's suggestion and we can close this issue here.
