### ISSUE TITLE
Inconsistent definition of <code>size</code> field in https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/util/BigArrays.java#L577

### ISSUE THREAD

**Issue by i-plusplus** [elastic/elasticsearch#98912]
### Elasticsearch Version

current repo

### Java Version

All

### OS Version

All

### Problem Description

The definition of Size field ByteStreamOutput changes from size of store data at the [initialisation](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/util/BigArrays.java#L544) of BigByteArray to capacity of the BigByteArray at the time of [growing](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/util/BigArrays.java#L577) the Array.

What is the correct definition of size field  here ? 

### Steps to Reproduce

Code bug

```[tasklist]
### Tasks
```

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by i-plusplus** [comment]
This seems to be a code bug. I have updated the title of the issue to make it more clear. I have also [posted](https://discuss.elastic.co/t/inconsistent-definition-of-size-field-in-bytestreamoutput-java/341874) this bug in a elasicsearch forum.
