### ISSUE TITLE
Return additional information about API Key creator in Get/Query API Keys responses

### ISSUE THREAD

**Issue by legrego** [elastic/elasticsearch#98939]
### Description

The [`Get API Key information API`](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-api-key.html) and `Query API Key API` currently returns the `username` of the API Key creator.

![image](https://github.com/elastic/elasticsearch/assets/3493255/2792ff2f-828c-4aaa-89a7-0a568da60423)

While the `username` is helpful in many contexts (particularly for self-hosted installations), it isn't all that useful for users authenticating via Elastic's Cloud SSO, as these usernames are unhelpful numeric identifiers:
![image](https://github.com/elastic/elasticsearch/assets/3493255/fcbc22af-a0bf-4c75-a028-3ff4e227b96d)

In order to display more relevant information to our administrators, we would like to have additional fields from the creator exposed in the API response. It looks like we are capturing quite a bit of these fields already:

![Larry Gregory 2023-08-28 at 08 46 47@2x](https://github.com/elastic/elasticsearch/assets/3493255/3831ff44-6cf4-4442-ad1b-e018a8fe67f1)

----

At a minimum, we would like to have the existing `full_name` and `email` returned in the API response.

This isn't captured in the API Key document as far as I can tell, but _ideally_, we would also like to have the creator's [User Profile](https://www.elastic.co/guide/en/elasticsearch/reference/current/user-profile.html) ID included in the response when available. The profile id would allow us to provide the most consistent experience across Kibana, as we could then leverage their preferred avatar and display name.

**Comment by tvernum** [comment]
> This isn't captured in the API Key document as far as I can tell, but ideally, we would also like to have the creator's [User Profile](https://www.elastic.co/guide/en/elasticsearch/reference/current/user-profile.html) ID included in the response when available. The profile id would allow us to provide the most consistent experience across Kibana, as we could then leverage their preferred avatar and display name.

That sounds like a dangerous path to go down. We don't want to create an association between API Keys and Profiles.
An API key doesn't have a profile; though the creator might have one, that profile is not guaranteed to be related to the API key, and we've intentionally avoided anything that would make it look like they are related.
I think it would be better to require that Kibana do a separate lookup of the owner's profile than create a connection between API keys and Profiles in the ES APIs.

**Comment by legrego** [comment]
> > This isn't captured in the API Key document as far as I can tell, but ideally, we would also like to have the creator's [User Profile](https://www.elastic.co/guide/en/elasticsearch/reference/current/user-profile.html) ID included in the response when available. The profile id would allow us to provide the most consistent experience across Kibana, as we could then leverage their preferred avatar and display name.
> 
> That sounds like a dangerous path to go down. We don't want to create an association between API Keys and Profiles. An API key doesn't have a profile; though the creator might have one, that profile is not guaranteed to be related to the API key, and we've intentionally avoided anything that would make it look like they are related.

I need help understanding this concern. The profile id is another property of the creator. The API Key also doesn't have a `username`, but we store and return this property today. The internal document structure for API Keys makes it clear that these are properties of the creator, and I imagine we could make the response body follow a similar pattern.

>  I think it would be better to require that Kibana do a separate lookup of the owner's profile than create a connection between API keys and Profiles in the ES APIs.

We would likely need a new API to reliably lookup profiles for each API Key creator. I don't expect the `suggest` API would be fit for this purpose. If the profile id were already on the API Key response body, then Kibana could use the existing `get` API to retrieve these profiles.
