### ISSUE TITLE
ESQL to_version doesn't fail

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#98989]
### Description

`to_version` seems to convert just about any string you give it, even if it has nothing to do with a version:

```
$ curl -HContent-Type:application/json -uelastic:password -XPOST localhost:9200/_query?pretty -d'{
  "query": "ROW a=\"random stuff\" | EVAL v = TO_VERSION(a)"
}'
{
  "columns" : [
    {
      "name" : "a",
      "type" : "keyword"
    },
    {
      "name" : "v",
      "type" : "version"
    }
  ],
  "values" : [
    [
      "random stuff",
      "random stuff"
    ]
  ]
}
```

Do we want this?

**Comment by nik9000** [comment]
Yeah! I'm wondering if we really want this in a function called `to_version`. Maybe. Probably? It lines up with how the field works on indexing. but it confused me.

**Comment by not-napoleon** [comment]
Based on the above discussion, this appears to be working as intended.  Closing as "not a bug".
