### ISSUE TITLE
ESQL: Make query results "predictable" by default

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#98995]
### Description

Currently when running ESQL queries against multi-node clusters, results are being returned based on what shards responds first - which while correct, makes for a poor user experience since the same query returns apparently different results (in different order) when streaming commands as oppose to aggregations (where the order does not matter).

The overall solution is to push an order yet for performance reasons we'd like for this to be efficient.

- For non-aggregates:
At a shard level, by default the docs are returned in _docs order. We can support the same order at the coordinator by performing shards ordering and thus preserve the order across queries.
- For aggregates
A similar situation to the above however since there's no doc limit, we would have to rely on a natural sorting likely on the key or if it's missing on the computed values.
This can be added at planning time based on what commands follow (a stat followed by a stat does not require any order in between).

**Comment by costin** [comment]
Had a discussion with @nik9000 and @dnhatn on this topic and concluded that:
1. any sorting behavior has to be explicit. Having the language add an implicit behavior is difficult and won't work in many cases
2. internally we'll have improve the tests to either have the queries sorted explicitly OR have the assertion happen out of order (we know the expected results before hand)

Based on 1, UI/Kibana would have to add an explicit sort in the query if the results are meant to be consistent - one idea is to have the `sort @timestamp` explicitly added in the query right after `from logs*| ` if the `@timestamp` field exists.
/cc @stratoula

**Comment by thomasneirynck** [comment]
> one idea is to have the sort @timestamp explicitly added in the query right after from logs*| 

It depends on what this means. (1) do this in the background (2) have the wizard insert it in the statement in the query-box

(1) I don't think we should rewrite a user's query without their knowledge. We've done similar simplifications wrt e.g. dataviews (the ESQL-editor no longer tries to match with a dataview. Instead, the user has to be 100% explicit)
(2) this seems weird

That said, I think enforced sorting would be great to add when Kibana will be building the "guided experience". E.g. in Lens, Maps, ... The guided experience will "in the background" construct ES|QL based on a user's selections in the UX.

**Comment by abatsakis** [comment]
Let's keep out of the picture where what I am gonna say should be implemented. I think it's a good behavior to have a default sorting key. It makes sense to be @timestamp for datastreams and the first field alphabetically for non-datatstreams.
We can document it and also say that this behavior may change. This is not about query rewriting, but more about a default behavior when something is not specified. It goes without saying that any user-provided sort param takes precedence. 

It may be easier to implement in Kibana for 8.11, and later push to ES, but I am open if people think differently. For example, I don't know what's the effort to make the CSV tests robust, maybe it's the same as this.

cc @nik9000 @costin @thomasneirynck @dnhatn @stratoula

**Comment by stratoula** [comment]
I agree with @thomasneirynck tbh.

1. Add this magically if a @timestamp is detected can be a poor experience. Imagine that I have a query with an index that has @timestamp. The user magically sees a @timestamp being added to the query. He removes it because he doesnt understand what is going on. Then it is added again. This seems weird to me both from the UX and from the code perspective. 
2. Add this to the background is less weird than the above but it will cause a lot of confusion. What happens if the user adds a sorting pipe later in the query? Even if we document it, it is not clear and prominent to the users what is going on.

Can we discuss it in our next sync @abatsakis ?

**Comment by abatsakis** [comment]
No I don't mean to add new fields. 
All we are talking about is having a default sorting key, i.e. timestamp, if timestamp is present. 

It may be too complicated for Kibana actually. Yeah, let's talk more offline and we can report back
