### ISSUE TITLE
Attachment search not working in Elasticsearch 1.4.3 if search string contains more than three characters

### ISSUE THREAD

**Issue by rhdip** [elastic/elasticsearch#9900]
The attachment search does not work if the search string contains more than three characters in ElasticSearch 1.4.3 whereas it works fine for the same settings in ElasticSearch 1.4.2. Can you tell me if there are any particular settings to get this working?

**Comment by dadoonet** [comment]
Could you give details on What you exactly did?
And versions?

**Comment by rhdip** [comment]
Sorry for the delayed response. I am trying to search for a given string in the content of the file. Say I have a file abc.docx and it contains the word "shark" in it. If I search for "sha", it returns the file abc.docx. However, if I search for "shar", it does not return that file i.e it seems to process only 3 character search strings while doing content search. I checked this in the latest version(1.5.0) as well and it din't work either. This seems to be working in Elasticsearch 1.4.2. Please let me know if you need further inputs on this.

**Comment by clintongormley** [comment]
Hi @rhdip 

A full recreation (including the index settings, mappings, how you index the attachment, and the doc itself) would be helpful.

**Comment by rhdip** [comment]
Yes I am using the mapper-attachments plugin. The file I am trying to search can be any file word, excel etc. 

I am providing the C# code. The UpdateIndex() method indexes the file name and its contents and the Search() method searches within the indexes.

The mapper class:

    public class AttachmentES
    {
        /// <summary>
        /// Index for Attachments table
        /// </summary>    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public ICollection<string> title { get; internal set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public string name { get; internal set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public ICollection<string> text { get; set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public string content { get; internal set; }
    
       public string Id { get; internal set; }
 
       [ElasticProperty(Type = Nest.FieldType.Attachment, Store = false, TermVector = Nest.TermVectorOption.WithPositionsOffsets)]
       public ESAttachment File { get; set; }
    }

The UpdateIndex method:

    public void UpdateIndex(int attachmentID)
    {
        //get the attachment details from database
        var atta = from a in dbES.GetAttachmentES(attachmentID).ToList()
                   select new AttachmentES
                   {
                       name = a.FileName,                      
                       Id = a.AttachmentID,                     
                   };

        AttachmentES objAttachmentES = new AttachmentES();
        objAttachmentES = atta.FirstOrDefault();

        client.CreateIndex("attachment", c => c.AddMapping<AttachmentES>(m => m.MapFromAttributes()));

        setting.SetDefaultIndex("attachment");
        foreach (AttachmentES itm in atta)
        {
            
            int id;
            id = Convert.ToInt32(itm.Id.Split('_')[0]);
            var rootPath = (CommonClass.AttachmentRootPath());


            if (string.IsNullOrEmpty(itm.name) == false)
            {
                string filePath = rootPath + "\\" + id;// +new FileInfo(itm.name).Extension;


                var attachment = new ESAttachment();

                string fileExt = Path.GetExtension(itm.name);

                if (File.Exists(filePath))
                    attachment._content = Convert.ToBase64String(File.ReadAllBytes(filePath));

                else if (File.Exists(filePath + fileExt))
                    attachment._content = Convert.ToBase64String(File.ReadAllBytes(filePath + new FileInfo(itm.name).Extension));

                switch (new FileInfo(itm.name).Extension)
                {
                    case ".txt":
                        attachment._content_type = "text/plain";
                        break;
                    case ".doc":
                        attachment._content_type = "application/msword";
                        break;
                    case ".docx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
                        break;
                    case ".xls":
                        attachment._content_type = "application/vnd.ms-excel";
                        break;
                    case ".xlsx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        break;
                    case ".ppt":
                        attachment._content_type = "application/vnd.ms-powerpoint";
                        break;
                    case ".pptx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
                        break;
                    case ".pdf":
                        attachment._content_type = "application/pdf";
                        break;

                    //Images
                    case ".png":
                        attachment._content_type = "image/png";
                        break;
                    case ".jpeg":
                    case ".jpg":
                        attachment._content_type = "image/jpeg";
                        break;
                    case ".bmp":
                        attachment._content_type = "image/bmp";
                        break;
                    case ".gif":
                        attachment._content_type = "image/gif";
                        break;

                    //Videos
                    case ".wmv":
                        attachment._content_type = "video/x-ms-wmv";
                        break;
                    case ".avi":
                        attachment._content_type = "video/x-msvideo";
                        break;
                    case ".flv":
                        attachment._content_type = "video/x-flv";
                        break;
                    case ".mp4":
                        attachment._content_type = "video/mp4";
                        break;


                    //zip
                    case ".zip":
                        attachment._content_type = "application/zip";
                        break;

                    //xml
                    case ".xml":
                        attachment._content_type = "application/xml";
                        break;
                }

                attachment._name = itm.name;
                itm.File = attachment;
                client.Index<AttachmentES>(itm);
            }
        }
    }

The Search method:

    public List<ESSearchResult> Search(string searchString, int userId = 0)
        {
        List<ESSearchResult> lstIDs = new List<ESSearchResult>();
        ESSearchResult objItem = new ESSearchResult();

        string ElasticSearchPath = ConfigurationManager.AppSettings["ElasticSearchURL"].ToString();
        Uri o = new Uri(ElasticSearchPath);
        setting = new ConnectionSettings(o);
        client = new ElasticClient(setting);

        setting.SetDefaultIndex("attachment");

        string q1 = "*" + searchString + "*";

        var result12 = client.Search<AttachmentES>(body1 =>
                     body1.Index("attachment").Query(query12 =>
     query12.QueryString(qs1 => qs1.Query(q1))
     ).Fields("id"));

        List<string> lst = (from p in result12.FieldSelections
                            select p.FieldValues(item => item.Id).ElementAt(0).ToString()).ToList();

        List<String> lstAttachments = new List<String>();
        foreach (var i in lst)
        {                        
            lstAttachments.Add(i);            
        }

        objItem = new ESSearchResult();
        objItem.ObjectEntity = Enums.ESEntity.AttachmentES;
        objItem.ObjectRowIDs = lstAttachments.Distinct().ToList<string>();


        lstIDs.Add(objItem);

        return lstIDs;
    }
