### ISSUE TITLE
From and size values doesn't work in Search api with sub_searches and rank.

### ISSUE THREAD

**Issue by adrianpbv** [elastic/elasticsearch#99011]
### Elasticsearch Version

8.9.1

### Java Version

_bundled_

### OS Version

mac_os Ventura 13.4

### Problem Description

I ran into an issue with the [_search api](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html). When I use RRF with [sub_searches](https://www.elastic.co/guide/en/elasticsearch/reference/current/rrf.html#rrf-using-sub-searches) I cannot paginate with from and size values because it returns no hits when the search continues to next values.

### Steps to Reproduce

Step 1: (Run this query to get )
`GET example-index/_search
{
    "sub_searches": [
        {
            "query": {
                "term": {
                    "text": "blue shoes sale"
                }
            }
        },
        {
            "query": {
                "text_expansion":{
                    "ml.tokens":{
                        "model_id":"my_elser_model",
                        "model_text":"What blue shoes are on sale?"
                     }
                }
            }
        }
    ],
    "rank": {
        "rrf": {
            "window_size": 50,
            "rank_constant": 20
        }
    },
"from":10,
"size":11
}`

You will get the item rank 11 but it is the same as "from":0, "size":1 (item rank # 1). Although this is wrong as described in step 2, it should return 11 items starting by the ranked item 11.

Step 2:
`GET example-index/_search
{
    "sub_searches": [
        {
            "query": {
                "term": {
                    "text": "blue shoes sale"
                }
            }
        },
        {
            "query": {
                "text_expansion":{
                    "ml.tokens":{
                        "model_id":"my_elser_model",
                        "model_text":"What blue shoes are on sale?"
                     }
                }
            }
        }
    ],
    "rank": {
        "rrf": {
            "window_size": 50,
            "rank_constant": 20
        }
    },
"from":10,
"size":5
}`

It does return No hits.

This is something fundamental as it is used for pagination purposes.

**Comment by freost** [comment]
This also happens when performing a query + knn search with RRF.

Elastic Version: 8.10.4

**Comment by benwtrent** [comment]
We are doing a major refactor in regards to RRF and sub_searches which should address this bug. The current implementation is experimental and expect the API to change.

**Comment by ZEROdcFRAME** [comment]
Is this bug fixed in version 8.11?

**Comment by rakesh-nayak** [comment]
We are looking to use RRF for our use case(Since it can provide better relevancy in results). @benwtrent could you help us when this could be fixed?

**Comment by jdconrad** [comment]
This is being looked into. Unfortunately, we cannot give a timeline.
