### ISSUE TITLE
[ILM] Always show step if show step_info

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#99030]
### Description

👋🏼 howdy, team! 

I've noticed when troubleshooting ILM that I sometimes miss (very obvious user error) problems because I filter by `step:ERROR`. However, it appears if you create a test index with bogus ILM policy, you can return the step's error under `step_info` BUT not get `step:ERROR` to filter on

## setup
```
PUT test
{
    "settings": {
        "lifecycle": {
            "rollover_alias": "oops",
            "name": "also_oops"
        }
    }
}
```
(wait for ILM to poll at least once)

## results

```diff
> GET test/_ilm/explain?only_errors=true
{
  "indices": {
    "test": {
      "policy": "also_oops",
      "index": "test",
-    # no step:ERROR
      "managed": true,
      "step_info": {
        "reason": "policy [also_oops] does not exist",
        "type": "illegal_argument_exception"
      }
    }
  }
}
```

## effect

The ILM Explain with `only_errors=true` (above) does NOT agree with the Kibana UI which filters `ilm.step:ERROR` which causes indices requiring manual intervention to fall between the cracks when they shouldn't.

<img width="892" alt="image" src="https://github.com/elastic/elasticsearch/assets/26751266/c941d36e-8f2d-49b1-9fbc-020a807e4b0b">

<img width="893" alt="image" src="https://github.com/elastic/elasticsearch/assets/26751266/ea5d9211-09ea-41b5-96f6-ffe1682312ed">

**Comment by dakrone** [comment]
We discussed this as a team and we'll add the column so that it can be part of a filter (even though it's not strictly in the `ERROR` step). We've added this as something we'll todo, but it's not currently prioritized over other work.
