### ISSUE TITLE
 I have different indexes that contain different fields I need to aggregate all of them, what i mean i have index1 and index2  in index1 I have ch and in index2 I have ch2 how can i add ch to ch2 with script or script field

### ISSUE THREAD

**Issue by ghramcode18** [elastic/elasticsearch#99039]

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
