### ISSUE TITLE
Search right after bulk update of existing document return wrong (older) timestamp  

### ISSUE THREAD

**Issue by uhaham** [elastic/elasticsearch#9905]
Hi 

I"m using version 1.4.2. 
The scenario is as follows:
1. In the index there are set of documents in a given structure.
2. search the index using searchRequestBuilder for the latest timestamp of that set.
3. performing index update using IndexRequestBuilder with setRefresh=true on the same set with identical documents.
4. immediately after the indexing I search again for the latest timestamp

The excepted result is to get newer timestamp on the second search, but occasionally it return same timestamp. 
Putting a sleep of few second between update and search solve the issue. 
Is there other solution for this issue beside sleep ?
Shouldn't the setRefresh=true flag guarantees that the update will be reflected in immediate query after the update ?

Thanks,
Uri

**Comment by clintongormley** [comment]
Hi @uhaham 

Could you provide your test code please?  I'd imagine that the setRefresh flag should cause the shard to refresh, but I don't know the java API.

**Comment by clintongormley** [comment]
No further info. Closing
