### ISSUE TITLE
IP aggregation by CIDR length

### ISSUE THREAD

**Issue by jammib** [elastic/elasticsearch#99064]
### Description

We store a lot of network related data in ES - firewall hits, proxy logs, syslog etc., a lot of times I find the need to aggregate the results into subnets.  I can do this by manually defining IP buckets for the results to go into, but if i want to group the results by say /24 ranges, I would need to build an awful lot of buckets to do this - more than is probably possible, and the results would only populate a small number of buckets.

It would be great to define a CIDR aggregation type with the prefix length being the only required value, and the resulting aggregated values being bucketed by CIDR range.

We use a cloud data app that does something similar to this, see attached images

![cidr-picker](https://github.com/elastic/elasticsearch/assets/12939628/11631f1e-a2d2-49b9-a704-ef2c5b52e55c)

![cidr-results](https://github.com/elastic/elasticsearch/assets/12939628/119e414e-6240-4748-bfce-867dc9b140e7)

**Comment by martijnvg** [comment]
Apologies for the late reply.

@jammib Does the [`ip_prefix` aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/search-aggregations-bucket-ipprefix-aggregation.html) do what is requested here?  I think using this aggregation with a `prefix_length` of 24 would what you describe?
