### ISSUE TITLE
[bug] Inconsistent definition of size field in ByteStreamOutput.java

### ISSUE THREAD

**Issue by i-plusplus** [elastic/elasticsearch#99067]
Previous reference Issue: #98912

The definition of Size field in ByteStreamOutput changes from size of store data at the [initialisation](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/util/BigArrays.java#L544) of BigByteArray to capacity of the BigByteArray at the time of [growing](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/util/BigArrays.java#L577) the Array.

### Steps to Reproduce

[This](https://github.com/elastic/elasticsearch/pull/98915/files#diff-cd2ab389c37d714c1b107e9455a6c836902824dad9bc2baeee6c972eecc6b107R46) test case explains the steps to reproduce.

**Comment by i-plusplus** [comment]
Previous reference Issue: https://github.com/elastic/elasticsearch/issues/98912

@DaveCTurner I am not sure if this is right way of doing this but I created this issue because I don't have permissions to reopen the issue.

**Comment by DaveCTurner** [comment]
Sorry @i-plusplus I'm not understanding the bug you're trying to report. There is no field called `size` in `ByteStreamOutput`, and the test you linked looks ok as-is.

**Comment by i-plusplus** [comment]
Oh Sorry, Let me add more context. 

Point 1. 

ByteStreamOutput class uses BigArrays to modify the underlying BigByteArray. 

While creating the BigByteArray object in the following method of BigArrays. If the value of size = PageCacheRecycler.BYTE_PAGE_SIZE + 1. It will create BigByteArray and size = PageCacheRecycler.BYTE_PAGE_SIZE + 1

```
    public ByteArray newByteArray(long size, boolean clearOnResize) {
        if (size > PageCacheRecycler.BYTE_PAGE_SIZE) {
            // when allocating big arrays, we want to first ensure we have the capacity by
            // checking with the circuit breaker before attempting to allocate
            adjustBreaker(BigByteArray.estimateRamBytes(size), false);
            return new BigByteArray(size, this, clearOnResize);
        } else if (size >= PageCacheRecycler.BYTE_PAGE_SIZE / 2 && recycler != null) {
            final Recycler.V<byte[]> page = recycler.bytePage(clearOnResize);
            return validate(new ByteArrayWrapper(this, page.v(), size, page, clearOnResize));
        } else {
            return validate(new ByteArrayWrapper(this, new byte[(int) size], size, null, clearOnResize));
        }
    }

```
Point 2:
BigByteArray uses below constructor and creates the internal array with combined length = PageCacheRecycler.BYTE_PAGE_SIZE * 2. While assign PageCacheRecycler.BYTE_PAGE_SIZE + 1 to size variable

```
BigByteArray(long size, BigArrays bigArrays, boolean clearOnResize) {
        super(BYTE_PAGE_SIZE, bigArrays, clearOnResize);
        this.size = size;
        pages = new byte[numPages(size)][];
        for (int i = 0; i < pages.length; ++i) {
            pages[i] = newBytePage(i);
        }
    }
```
Please note here value stored in size is PageCacheRecycler.BYTE_PAGE_SIZE + 1 while internal DS has length of PageCacheRecycler.BYTE_PAGE_SIZE * 2. 

Point 3:
While growing the array as shown below, if we pass minSize = PageCacheRecycler.BYTE_PAGE_SIZE *2 + 1. It will call resize method with newSize = PageCacheRecycler.BYTE_PAGE_SIZE * 3. 
```

public ByteArray grow(ByteArray array, long minSize) {
        if (minSize <= array.size()) {
            return array;
        }
        final long newSize = overSize(minSize, PageCacheRecycler.BYTE_PAGE_SIZE, 1);
        return resize(array, newSize);
    }
```


Point 4: 
resize method as shown below  will increase the size of internal DS to PageCacheRecycler.BYTE_PAGE_SIZE * 3 and assign size = newSize. 

```
public ByteArray resize(ByteArray array, long size) {
        if (array instanceof BigByteArray) {
            return resizeInPlace((BigByteArray) array, size);
        } else {
            AbstractArray arr = (AbstractArray) array;
            final ByteArray newArray = newByteArray(size, arr.clearOnResize);
            final byte[] rawArray = ((ByteArrayWrapper) array).array;
            newArray.set(0, rawArray, 0, (int) Math.min(rawArray.length, newArray.size()));
            arr.close();
            return newArray;
        }
    }
```

Please note that now value of size = PageCacheRecycler.BYTE_PAGE_SIZE*3 which is not the size of data it holds but the size of internal DS. 



In the test case below 1st assert is checking size of data stored while 2nd assert is checking size of internal DS. 

```
1. assertEquals((long) PageCacheRecycler.BYTE_PAGE_SIZE + 1, out.bytes.size());
2. assertEquals((long) PageCacheRecycler.BYTE_PAGE_SIZE * 3, out.bytes.size());
```

**Comment by DaveCTurner** [comment]
This all sounds true, but why is it a bug? These are pretty deep internals of ES.

**Comment by i-plusplus** [comment]
Got it. I might be dead wrong about the design decisions here but I thought there should be 1 definition to size field based on which other functions on top of which can be written. Otherwise the client of ByteArray has to be aware of the internal working of ByteArray. For example client of hashCode method below has to understand the value of size before comparing the 2 hashcodes. 

```
    public static int hashCode(ByteArray array) {
        if (array == null) {
            return 0;
        }

        int hash = 1;
        for (long i = 0; i < array.size(); i++) {
            hash = 31 * hash + array.get(i);
        }

        return hash;
    }

```

**Comment by DaveCTurner** [comment]
I think this is working exactly as the docs for `BigArrays#grow` say it should:

```
    /** Grow an array to a size that is larger than <code>minSize</code>,
     * preserving content, and potentially reusing part of the provided array. */
```

Therefore I'm closing this.
