### ISSUE TITLE
It is impossible to create a follower index with `$` character in its name

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#99078]
### Description

It is impossible to create a follower index with a `$` character in its name (please note, it is possible to create a regular index with `$` in its name).

This could be reproduced by rest request:
```
PUT /my-index/_ccr/follow
{
    "remote_cluster": "my-remote-cluster",
    "leader_index": "my-index$follower"
}
```

or `CcrIntegTestCase`:

```
    public void testFollowIndex() throws Exception {
        assertAcked(leaderClient().admin().indices().prepareCreate("my$index"));
        setupRemoteCluster();
        final PutFollowAction.Request followRequest = putFollow("my$index", "my$index");
        followerClient().execute(PutFollowAction.INSTANCE, followRequest).get();
    }
```

This is happening as during initial follow phase we restore the leader cluster from the remote using a snapshot restore.
Corresponding request is created with index name added to `RestoreSnapshotRequest#renamePattern` (regexp) without escaping `$`.

**Comment by MaxTElastic** [comment]
Hey team - this is being escalated by the customer as they are due to implement Elastic at a customer sight, but are unable to do so without implementing DR. Amdocs is an OEM Partner with a total Business Value to Elastic of over $3m. 

Do we know whether this code change is going to be prioritised for the 8.10 release in September?

**Comment by Maxwellk-Gib** [comment]
Hi @idegtiarenko just checking in if you know when this change maybe released and which version ? also would it be back ported ?

**Comment by DaveCTurner** [comment]
This task isn't currently scheduled. We'll assess whether it's safe to backport during development, once we have a better sense of the scale of the changes required and the risks that a backport might entail.

**Comment by Maxwellk-Gib** [comment]
Thanks @DaveCTurner , this bug has a big impact on the customer (see https://github.com/elastic/sdh-elasticsearch/issues/7443) , this customer 'acts' like a MSP in that they manage services on behalf of their customers so the impact is not just our customer but their customers also. Appreciate that providing a timeframe is difficult but would it be appropriate if we could have it scheduled ?

**Comment by DaveCTurner** [comment]
The public Github repo is really not the right place for this discussion.
