### ISSUE TITLE
[Docs] Zen Discovery references deprecated ping_timeout setting

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#9908]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#master-election

> As part of the ping process a master of the cluster is either elected or joined to. This is done automatically. The `discovery.zen.ping_timeout` (which defaults to `3s`)

This is _still_ true, but the setting should be `discovery.zen.ping.timeout`.

**Comment by vedil** [comment]
i see in code "ZenDiscovery.java" that both properties are used and "discovery.zen.ping.timeout" over-rides " discovery.zen.ping_timeout"
below is the code snippet:
TimeValue pingTimeout = this.settings.getAsTime("discovery.zen.initial_ping_timeout", timeValueSeconds(3));
        pingTimeout = this.settings.getAsTime("discovery.zen.ping_timeout", pingTimeout);
        pingTimeout = settings.getAsTime("discovery.zen.ping_timeout", pingTimeout);
        this.pingTimeout = settings.getAsTime(SETTING_PING_TIMEOUT, pingTimeout);

**Comment by pickypg** [comment]
Hi @vedil, I definitely agree that that's in the code, but the `SETTING_PING_TIMEOUT` is the last one, which means that it gets the final say-so.

**Comment by jasontedor** [comment]
Closed by d8b29f7beb37993c77bfb3298a77513651ef81d4.
