### ISSUE TITLE
ES 7.17 Exponentially growing query cache

### ISSUE THREAD

**Issue by oleg-smith** [elastic/elasticsearch#99139]
### Elasticsearch Version

7.17,8.8.0

### Java Version

_bundled_

### OS Version

centos7

### Problem Description

We recently migrated our Elastic cluster from version 7.7.1 to 7.17.0, and have been noticing that the query cache keeps growing exponentially if indexing is running on the nodes simultaneously with reasonably high search load. This leads to high latency on the search queries. We have the same heap, cache, and cluster settings on both the old and the new versions but this was not an issue on the old version.

Full description of the problem on ElasticSearch discussion forum https://discuss.elastic.co/t/es-7-17-exponentially-growing-query-cache/298784/1

### Steps to Reproduce

https://discuss.elastic.co/t/es-7-17-exponentially-growing-query-cache/298784/1

**Comment by gareth-ellis** [comment]
Thanks very much for your interest in Elasticsearch.

Are you able to provide more information regarding reproducing the issue? 

- Specific queries to reproduce the issue
- More details regarding the cluster setup and configuration (discuss post does include some detail, though it is from 1.5 years ago so may no longer be valid)
- What volume of indexing and queries were happening concurrently?

**Comment by kow1011b** [comment]
hi @gareth-ellis, let me try to provide some more info:

Specific queries to reproduce the issue
We don't believe this is triggered by certain queries; at least we have not identified similar queries at each occurrence of this issue.  

More details regarding the cluster setup and configuration (discuss post does include some detail, though it is from 1.5 years ago so may no longer be valid)
We have a ~170 node cluster, 5 of which are master or eligible nodes, 10 are coordinating nodes.  Rest are data nodes.  The data nodes have a 30GB heap.  We kept the 10% default value for query cache but ES's own metric (es.indices.query_cache.memory_size_in_bytes) shows that it could reach into TBs if the issue left unchecked.  

What volume of indexing and queries were happening concurrently?
the es.indices.search.query_total ranges from 10K to 50K/min on each node
we do bulk index to ES.  In terms of documents, it's around 4 to 5M docs per min.

**Comment by romseygeek** [comment]
I wonder if this is related to https://github.com/apache/lucene/pull/12614?  Although I think that lucene bug has been around for a while so it wouldn't necessarily explain why you see this manifest in 7.17 but not 7.7

**Comment by kow1011b** [comment]
Thanks @romseygeek!  That fix and the bug mentioned in it seem like exactly what we have observed!  This is promising.

**Comment by spinscale** [comment]
Are you planning to backport the Lucene fix somehow to 7.17? We are running into this as well after upgrading to the latest 7.17. We did not have this issue with 7.12 according to our metrics.

Clearing the cache seems to make it work again, but we have not yet measured for how long.

**Comment by mrnonz** [comment]
Hi,

I faced this problem too.

Cluster version: 7.17.18
Node memory: 32GB and Heap 16GB
Query cache: 10% default value for query cache

![Screenshot 2024-04-13 at 23 07 53](https://github.com/elastic/elasticsearch/assets/9113726/49ba4f65-e1b0-46b7-ae3e-ffbf2826100d)
You can see those some node cache just 1.6GB (10% of heap), but some node got higher and higher query cache.

That query cache on some node bloat more than total memory on that node, that not make sense.

How to solve this problem? Are you guy have interim to clear this? Thanks

**Comment by mrnonz** [comment]
Hi @spinscale,

Could you please share us that how you clear those cache? Or just `POST /_cache/clear` ?

**Comment by spinscale** [comment]
Yes, you can just specify the query cache in that API call and leave the other ones untouched.

**Comment by kow1011b** [comment]
@mrnonz since the real bug behind this issue is in Lucene, it's better to upgrade to an ES version that has the Lucene fix.  In this case, that looks to be ES version 8.12 or newer.

**Comment by benwtrent** [comment]
This bug is fixed & likely won't be backported to 7.17.
