### ISSUE TITLE
ESQL: default request timeout

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99141]
### Description

We need to improve the default timeout of ESQL requests so long queries don't end up timing out or being cancelled by various proxies. Internally this should leverage the task API.
In tandem we should tie this to timeout specified on the REST endpoint.

**Comment by costin** [comment]
See https://github.com/elastic/elasticsearch/pull/99526#issuecomment-1755916395

**Comment by felixbarny** [comment]
This would be really useful to be able to properly support the [`timeout`](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-queries) parameter in our implementation of the Prometheus query APIs.
