### ISSUE TITLE
[CI] `CsvTests` hit suite timeout (and Gradle runner hit OOME)

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#99154]
This build failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+main+intake+multijob+part2/6729/consoleText

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {string.In3VLWithComputedNull}" -Dtests.seed=81DA78149F2DAC1A -Dtests.locale=es-ES -Dtests.timezone=Africa/Djibouti -Druntime.java=20

org.elasticsearch.xpack.esql.CsvTests > test {string.In3VLWithComputedNull} FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([81DA78149F2DAC1A]:0)

> Task :x-pack:plugin:snapshot-repo-test-kit:qa:minio:javaRestTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8

> Task :x-pack:plugin:searchable-snapshots:qa:rest:yamlRestTest

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
```

The OOME suggests that the quantity of logs was overwhelming.

**Comment by ChrisHegarty** [comment]
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
> ..
> The OOME suggests that the quantity of logs was overwhelming.

@DaveCTurner I'm sure you know better than I, but OOM is an exhaustion of Java heap. How does this related to logs? Are the logs buffered in memory or something?  ( I'm just trying to understand the connection here between OOM and logs )

**Comment by DaveCTurner** [comment]
Yeah I think that OOME was the Gradle process falling over, not the ES test process.

**Comment by costin** [comment]
Trace logging used for debugging was enabled for CsvTests in main - likely a leftover. I've just pushed a fix to fix that.

**Comment by costin** [comment]
Forgot to say thanks @DaveCTurner for the diagnostics, it made the fix easy!
