### ISSUE TITLE
Execution failed for task ':distribution:docker:buildDockerImage'

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#99175]
### CI Link

https://gradle-enterprise.elastic.co/s/tzfgs4b3ng3nw

### Repro line

./gradlew :distribution:docker:buildDockerImage

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
Execution failed for task ':distribution:docker:buildDockerImage'.
> A failure occurred while executing org.elasticsearch.gradle.internal.docker.DockerBuildTask$DockerBuildAction
  > Process 'command 'docker'' finished with non-zero exit value 1
```

**Comment by mark-vieira** [comment]
This looks like a transient error and I haven't seen any more instances of it. Closing for now. We can reopen if this crops up again.
