### ISSUE TITLE
ESQL: fallback to source extraction for numeric fields that have fielddata disabled

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99213]
### Description

Some numeric fields that are rarely used, are not indexed causing their retrieval to throw errors due to missing field data.
For example `file.x509.public_key_exponent` in ECS: https://github.com/elastic/ecs/blob/main/schemas/x509.yml#L200C24-L200C24

To address, we can:
- [ ] at planning side, check if there's any sub-field we can use
- [ ] if there's none, perform source extraction and give a warning to the user that field-data is disabled for said fields and that slow source extraction is used instead

**Comment by luigidellaquila** [comment]
For now, after https://github.com/elastic/elasticsearch/pull/99588, the query should not throw errors anymore but just return `null`.
Keeping this issue open for a better solution in the long term (eg. extract from _source)

**Comment by luigidellaquila** [comment]
Fixed as a consequence of https://github.com/elastic/elasticsearch/pull/101235
