### ISSUE TITLE
[DOCS] text_similarity : Expected exactly [1] value in text_similarity result; got [2]

### ISSUE THREAD

**Issue by llermaly** [elastic/elasticsearch#99211]
### Elasticsearch Version

8.9

### Java Version

_bundled_

### OS Version

cloud

### Problem Description

Hello team, we are trying to run the text_similarity example from this link: https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-search-compare.html#ml-nlp-text-similarity

```
POST /_ml/trained_models/sentence-transformers__all-distilroberta-v1__text_similarity/_infer
{
  "docs": [
    {
      "text_field": "Berlin has a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers."
    },
    {
      "text_field": "New York City is famous for the Metropolitan Museum of Art."
    }
  ],
  "inference_config": {
    "text_similarity": {
      "text": "How many people live in Berlin?"
    }
  }
}
```

Seeing this error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Expected exactly [1] value in text_similarity result; got [2]",
        "suppressed": [
          {
            "type": "status_exception",
            "reason": "Expected exactly [1] value in text_similarity result; got [2]"
          }
        ]
      }
    ],
    "type": "status_exception",
    "reason": "Expected exactly [1] value in text_similarity result; got [2]",
    "caused_by": {
      "type": "status_exception",
      "reason": "Expected exactly [1] value in text_similarity result; got [2]",
      "suppressed": [
        {
          "type": "status_exception",
          "reason": "Expected exactly [1] value in text_similarity result; got [2]"
        }
      ]
    }
  },
  "status": 500
}
```

We tried with different models and the error is the same.
Is there any specific model we should use for this feature?

### Steps to Reproduce

1. Push a sentence similarity model, eg: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
2. Run the query example from this link: https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-search-compare.html#ml-nlp-text-similarity

**Comment by llermaly** [comment]
We could get it working by changing the task from `text_classification` to `text_similarity` .

Text similarity is not part of the tasks list:
https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch

And not every model works for text_similarity ,so would be good to also mention the compatible models the list:
https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-model-ref.html

**Comment by davidkyle** [comment]
The `text_similarity` task requires a cross encoder model, for each input the cross encoder model produces a similarity score for the `text` field ("How many people live in Berlin?") and the text in the input doc.  

There are a number of Cross Encoder models on Hugging Face to choose from: https://huggingface.co/models?search=cross%20encoder

I tested with https://huggingface.co/cross-encoder/ms-marco-TinyBERT-L-2-v2 and https://huggingface.co/cross-encoder/mmarco-mMiniLMv2-L12-H384-v1, both worked on Elasticsearch v8.9.1.

The Sentence Transformer models you reference are not cross encoder models they produce text embeddings. Assuming you used Eland to upload the model, the Eland [code](https://github.com/elastic/eland/blob/eb69496627089c4851e2513f0d8c0ca3236e69c6/eland/ml/pytorch/transformers.py#L809) imports the model as a `AutoModelForSequenceClassification` but those Sentence Transformer models have not been fine tuned for sequence classification, the results you get using the model is this way will not be good quality.

If you want to use text embeddings to measure text similarity calculate the cosine distance between the vectors. You can do this in Elasticsearch with the vector search functionality. Use the sentence transformer model to generate text embeddings as you ingest your data and index them as `dense_vectors`. Then you can search for similar text using knn search, the search score is the similarity measure chosen in index mapping (use cosine). Here's a [tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search.html) taking you through those steps.

I think the action here is to update the docs with examples of cross encoder models as you rightly noted.

**Comment by llermaly** [comment]
Thanks @davidkyle , we could find that by looking at the PR for `text_similarity`. Would be nice to have more documentation around text_similarity , there is almost nothing and it seems like is a good option for reranking.

**Comment by davidkyle** [comment]
> there is almost nothing and it seems like is a good option for reranking.

👍 that's the idea, thanks for the feedback @llermaly

**Comment by davidkyle** [comment]
Text similarity models have now been added to the list of compatible models, the update should appear soon

https://www.elastic.co/guide/en/machine-learning/master/ml-nlp-model-ref.html
