### ISSUE TITLE
New sparse_vector YAML tests fail in serverless

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#99238]
#98996 introduced some YAML tests that set `number_of_replicas: 0`, which doesn't work in serverless.

See for instance [this build scan](https://gradle-enterprise.elastic.co/s/4fchm3fbkx5ey/tests/task/:qa:core-rest-test:yamlRestTest/details/co.elastic.elasticsearch.qa.rest.ServerlessClientYamlTestSuiteIT/test%20%7Byaml=search.vectors%2F90_sparse_vector%2FIndexing%20and%20searching%20sparse%20vectors%7D?page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1).

**Comment by DaveCTurner** [comment]
I am muting these tests in serverless with https://github.com/elastic/elasticsearch-serverless/pull/866, please unmute when fixed.

**Comment by javanna** [comment]
@carlosdelest can this be closed?

**Comment by carlosdelest** [comment]
Closed as both https://github.com/elastic/elasticsearch-serverless/pull/869 and https://github.com/elastic/elasticsearch/pull/99241 have been closed
