### ISSUE TITLE
Snapshot/Restore: snapshot during rolling restart of a 2 node cluster might get stuck

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#9924]
The issue was originally reported in https://github.com/elasticsearch/elasticsearch/issues/7980#issuecomment-76151889 If a current master node that contains all primary shards is restarted in the middle of snapshot operation, it might leave the snapshot hanging in `ABORTED` state.

**Comment by cxxr** [comment]
:+1: ran into this a few times.

**Comment by srgclr** [comment]
Ran into a similar issue and tried the snapshot cleanup utility. It didn't work as all shards were ignored:

> Ignoring shard [[dev1_10_event.2015-03-15][4]] with state [ABORTED] on node [kyU3N9lpTIuTbdeUGp5ThQ] - node exists : [true]

What's the reason for ignoring shards when the node exists?

**Comment by imotov** [comment]
@srgclr if a node exists and a shard is in ABORTED state it can mean one of the two things - we hit #11314 or the shard is stuck in the I/O operation and we need to wait until the I/O operation is over or we need to restart the node. It's impossible for the cleanup utility to determine which state we are in. Because of this, it takes a safer route - assume that we are stuck in I/O operation and skip such shards.

**Comment by imotov** [comment]
This should be solved by #11450. Closing.
