### ISSUE TITLE
Make default dense_vector similarity dot_product

### ISSUE THREAD

**Issue by kderusso** [elastic/elasticsearch#99258]
Currently the default similarity for dense_vector if not specified is cosine, because this will work without normalized vectors. Dot_product offers better performance but requires normalization. 

Since we are not auto-normalizing query and index vectors, we should update this default for new indices created in 8.11+. 

Note: This could potentially be a breaking change for certain cases which is why it's a separate issue.

**Comment by benwtrent** [comment]
FYI, @carlosdelest we are not ready to make this change.

**Comment by carlosdelest** [comment]
Thanks for the heads up @benwtrent ! What do we need for this to be merged?

**Comment by benwtrent** [comment]
@carlosdelest its a breaking change and due diligence is required. Please refrain from working on this until we make sure its 100% justified.

**Comment by carlosdelest** [comment]
Got it, thanks! This task is blocked until this breaking change is approved in https://github.com/elastic/dev/issues/2348

**Comment by carlosdelest** [comment]
Already done work is in this [draft PR](https://github.com/elastic/elasticsearch/pull/99269) (it breaks compat tests)

**Comment by kderusso** [comment]
Per @benwtrent in 2023-09-20 Search Area Sync this is likely not going to happen. Should we close this issue as won't do and reopen if and when it becomes an issue? 
CC: @liranabn

**Comment by carlosdelest** [comment]
Let's close it and reopen if needed. Thanks @kderusso !
