### ISSUE TITLE
ESQL: document nested documents limitation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#99283]
### Description

The current Limitations page  - https://www.elastic.co/guide/en/elasticsearch/reference/master/esql.html#esql-limitations - documents the supported data types, implying that the data types not listed there are not supported. That's fair.

But, there is a slight difference in supportability when it comes to `nested` documents: these field types cannot be returned at all, in any query. To give an example, create an index with the following mapping:

```
{
  "mappings": {
    "properties": {
      "binary_value": {
        "type": "binary"
      },
      "integer_value": {
        "type": "integer"
      },
      "nested_field": {
        "type": "nested",
        "properties": {
          "text": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```

With a query `from test` and URL `localhost:9200/_query?format=json` one gets back this:

```
{
    "columns": [
        {
            "name": "binary_value",
            "type": "unsupported"
        },
        {
            "name": "integer_value",
            "type": "integer"
        }
    ],
    "values": []
}
```

Which shows that a `binary` data type is unsupported, but `nested` is not even listed there. Same goes when trying to show the values of such fields: `from test | keep nested_field` results in `"Found 1 problem\nline 1:18: Unknown column [nested_field]"` while `from test | keep binary_value, integer_value` results in:

```
 binary_value  | integer_value 
---------------+---------------
<unsupported>  |5              
```

Also, I believe the **documentation needs to include the fact that we return `<unsupported>` "constant"** value for those fields that we DO want to return but their types are unsupported.

**Comment by abdonpijpelink** [comment]
Completed in https://github.com/elastic/elasticsearch/pull/101673
