### ISSUE TITLE
SQL DBA excited, almost a convert to NOSQL and it wont start

### ISSUE THREAD

**Issue by JRRan64** [elastic/elasticsearch#9930]
Newbie trying to get ElasticSearch 1.4.2. or 1.4.4 simple quick start in Windows accomplished.  Dipping big toe into Open Source NOSQL waters and ... "The system cannot find the path specified".   

Been trying to debug but without minimum requirements document I don't know what is wrong.  I have played with paths (\ vs /).   Java_Home is set java -version works (1.8.0_31 Java SE Runtime).
On Windows 7.   Will try on heftier box but big disappoint this afternoon. 

So open source community, please help.  Following is result of adding echo statements to .bat and .in.bat

C:\Program Files\elasticsearch-1.4.4>bin\elasticsearch.bat
SCRIPT_DIR  C:\Program Files\elasticsearch-1.4.4\bin\
ES_HOME     C:\Program Files\elasticsearch-1.4.4
ES_HOME     C:\Program Files\elasticsearch-1.4.4
ES_CLASSPATH   nothing
ES_CLASSPATH  ;C:\Program Files\elasticsearch-1.4.4\lib\elasticsearch-1.4.4.jar;C:\Program Fil
es\elasticsearch-1.4.4\lib\*;C:\Program Files\elasticsearch-1.4.4\lib\sigar\*
ES_PARAMS -Delasticsearch -Des-foreground=yes -Des.path.home="C:\Program Files\elasticsearch-1.4.4"

ABOUT_TO_START at bottom of .bat
JAVA_HOME C:\Program Files\Java\jre1.8.0_31\bin
JAVA_OPTS  -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8

ES_PARAMS -Delasticsearch -Des-foreground=yes -Des.path.home="C:\Program Files\elasticsearch-1.4.4"
ES_CLASSPATH ;C:\Program Files\elasticsearch-1.4.4\lib\elasticsearch-1.4.4.jar;C:\Program Files\elasticsearch-1.4.4\lib\*;C:\Program Files\elasticsearch-1.4.4\lib\sigar\*

The system cannot find the path specified.   

C:\Program Files\elasticsearch-1.4.4>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

**Comment by bgiromini** [comment]
Did you download the program from the github repo or did you get it from the official site? I only ask because I ran into a similar issue when trying to download from the github releases. It seems there are files missing that are only available in the official package. 

https://www.elastic.co/downloads/elasticsearch

**Comment by markwalkom** [comment]
Please also join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)

**Comment by JRRan64** [comment]
It was a java home and path issue.  Working great now.

**Comment by clintongormley** [comment]
Awesome, thanks for letting us know
