### ISSUE TITLE
sparse_vector fields should support exists queries

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#99319]
### Description

When using a ML model with that outputs sparse vectors (like ELSER), it's possible that some times the inference pipeline fails when indexing new documents and new ingested documents are not enriched with the `sparse_vector` fields.

One approach in this case is to run an update by query and issue a reindexing with the ml pipeline of the documents in place in the same index.
In this case, we would want to only update the documents that do not have `sparse_vector` fields, for example:

```
POST search-books/_update_by_query?pipeline=ml-inference-books
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "ml.inference.description_expanded.predicted_value"
        }
      }
    }
  }
}
```
In theory this a much simpler approach then duplicating all the data to reindex in another index or to reissue bulk indexing requests from scratch. It only requires a single Elasticsearch API request.

the problem is that `sparse_vector` fields do not support `exists` queries.

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: [sparse_vector] fields do not support [exists] queries",
        "index_uuid": "WkxxefxdTuCiNeLy4b33jw",
        "index": "search-books"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "search-books",
        "node": "l5lxDFkeSwOyiwOEkQtWZA",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: [sparse_vector] fields do not support [exists] queries",
          "index_uuid": "WkxxefxdTuCiNeLy4b33jw",
          "index": "search-books",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "[sparse_vector] fields do not support [exists] queries"
          }
        }
      }
    ]
  },
  "status": 400
}
```

This also makes it difficult to get an accurate count of how many fields are missing the `sparse_vector` fields and users have to rely on other fields/mechanisms to do a reindexing in place with update by query.

NOTE: This will only be for the top level sparse_vector field. NOT for any of its sparse dimensions.

**Comment by benwtrent** [comment]
I am not sure `exists` works currently as is or not, I am guessing it doesn't. Right now we don't support `docValues`, and I am not sure we will for this mapping type.

I think adding to the `_fields_names` makes the most sense to me.

**Comment by ioanatia** [comment]
related https://github.com/elastic/elasticsearch/issues/98096
