### ISSUE TITLE
Wildcard queries and regex don't run on indices (_id)s

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#9935]
Hi,

I have been trying to run wildcard queries against .kibana indices on ES 1.4.4. I am querying on _id. While prefix query runs, wildcard queries don't. 

Example 
> curl localhost:9200/,kibana/_search?pretty -d '{"query":{"prefix":{"_id":"TC"}}}'

Gives results, but 

> curl localhost:9200/,kibana/_search?pretty -d '{"query":{"wildcard":{"_id":"TC*"}}}'

Gives me an empty result.

**Comment by clintongormley** [comment]
Duplicate of #15070
