### ISSUE TITLE
Ubuntu update breaks ES ?

### ISSUE THREAD

**Issue by greg0ire** [elastic/elasticsearch#9941]
Friday, at ~ 9 a.m. UTC, an update popped in and everyone in my office did it. Here is the apt log for this update :

> Start-Date: 2015-02-27  10:12:28
Upgrade: multiarch-support:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), cups-core-drivers:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), cups-server-common:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), nscd:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), libcups2-dev:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libcups2:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), cups-daemon:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libcupsmime1:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), cups-client:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libc-dev-bin:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), libcupsimage2:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libc-bin:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), libc6:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), libc6:i386 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), cups:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), cups-bsd:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libcupscgi1:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libcupsppdc1:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libc6-i386:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), cups-common:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), cups-ppdc:amd64 (1.7.5-3ubuntu3, 1.7.5-3ubuntu3.1), libc6-dbg:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3), libc6-dev:amd64 (2.19-10ubuntu2.2, 2.19-10ubuntu2.3)
End-Date: 2015-02-27  10:13:46

 I do not use ES personally, but 2 of my colleagues do, and have been complaining about memory problems since the update : during the index population, the index would revert to a previous state. I can't see how cups could cause this bug, whereas libc6 seems to be about memory management. Did anyone else experience this problem after this upgrade ?

@clebeaupin , you experienced this bug, could you please add more details to this issue ?

**Comment by clintongormley** [comment]
@greg0ire @clebeaupin you upgraded all of these packages (including libc) while still running Elasticsearch?  Did you restart Elasticsearch and continue to see these problems?

**Comment by clebeaupin** [comment]
Yes ElasticSearch was running during the upgrade.
After the upgrade, I restarted my computer and I still got the same issue.
To continue to work with ElasticSearch, I had to install it on a separate virtual machine that was not upgraded with the last version of libc6. I have not test it again on my local computer.

**Comment by clintongormley** [comment]
@clebeaupin could you provide more info about what you saw going wrong?  at the moment it's in the "it doesn't work" category...

**Comment by clintongormley** [comment]
a recreation would be great...

**Comment by sfaribault** [comment]
Hi, I also experienced this issue.
I managed to work around it by decommenting this line in elasticsearch.yml:
discovery.zen.ping.multicast.enabled: false

I found this error in my logs :
failed to connect to master [[Bart Hamilton][7livEvjOQ8uCTGOeMuAH2A][ubuntu-parallels][inet[/192.168.0.13:9300]]], retrying...
   org.elasticsearch.transport.ConnectTransportException: [Bart Hamilton][inet[/192.168.0.13:9300]] connect_timeout[30s]
           at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:807)
          at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:741)
          at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:714)
          at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:150)
          at org.elasticsearch.discovery.zen.ZenDiscovery.joinElectedMaster(ZenDiscovery.java:441)
          at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:393)
          at org.elasticsearch.discovery.zen.ZenDiscovery.access$6000(ZenDiscovery.java:80)
          at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1320)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
          at java.lang.Thread.run(Thread.java:745)   

By googling it, I was redirected toward this page which hinted toward the solution : 
http://elasticsearch-users.115913.n3.nabble.com/exception-at-startup-failed-to-send-ping-request-over-multicast-td2097917.html

Hope this helps

**Comment by clintongormley** [comment]
No more info. Closing
