### ISSUE TITLE
ServiceNow ITOM Connector does populate severity in connector while we test it but not while using connector to add action in rule

### ISSUE THREAD

**Issue by sgaybhup** [elastic/elasticsearch#99420]
### Elasticsearch Version

v 8.5.1

### Java Version

_bundled_

### OS Version

k8s

### Problem Description

ServiceNow ITOM Connector does populate severity in connector while we test it but not while using connector to add action in rule

### Steps to Reproduce

Add Service Now ITOM Connector
Test Connector --> Severity  
 It populates Severity  e.g. Critical, Minor etc.

Create Rule
Add Action (ServiceNow ITOM)
Expand Severity drop down
Expected Result - It should Populate list of Severities 
Actual Result : Its Empty

**Comment by kingherc** [comment]
Hi @sgaybhup , thanks for the issue. This connector bug should be reported in https://github.com/elastic/kibana rather than in elasticsearch. Please create a new issue there. Closing this one.
