### ISSUE TITLE
ESQL: Expose _source as a metadata field

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99456]
### Description

Similar to `_id`, `_version` and the rest, _source should be available as a metadata field.
One thing to consider is using `_content` as a synonym for it to allow for slightly different semantics than those in ES such as dealing with synthetic source or the raw storage outside ES in the future (CSV files, etc...).

```
FROM index [metadata _content] | KEEP _content
```

**Comment by nik9000** [comment]
I think `_source` would render synthetic _source. It'd just be slow.

We never built it into scripts,  but I imagine it does belong in ESQL. And, honestly, probably in scripts as well, even though it's slow.

**Comment by costin** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/102391
