### ISSUE TITLE
ElasticSearch cannot perform an effective directory search. Cannot search in subdirectories.

### ISSUE THREAD

**Issue by themiralay** [elastic/elasticsearch#99478]
### Description

I have a drive application that uses Ceph S3 and has the ability to index on elasticsearch.
When ElasticSearche assigns the default idnex and writes data, it writes in the following format.

```
                "bucket": "enes-test-123",
		"name": "enesbaba/tester/ronaldo/test.svg",
		"instance": "null",
		"versioned_epoch": 0,
		"owner": {
			"id": "user1",
			"display_name": "user1"
		},
		"permissions": [
			"user1"
		]
		
```
But I'm searching in the name field in the Elastic document. The name field is a directory path, but elasticsearch cannot find a solution to the following problem even if any tokenizer or hierarchy is used when searching in the path:

```
For example Name Field
 "enesbaba/tester/ronaldo/tester.svg"
"abc/folder/ronaldo/tester.svg"
"test/trial/folder2/folder3/draft.pdf"
"enes1/fodler1/folder2/reco.mp4
"enes2/fodler4/folder5/fodler6/"
```

When I search for "est", all objects under "enesbaba/tester/", "test/" appear. However, elasticsearch should search in the bottom directory here. For example: the bottom directory for "enesbaba/tester/ronaldo/tester.svg" is "/tester.svg", or the bottom directory for "enes2/fodler4/folder5/fodler6/" is "/fodler6/".

This causes a problem on all drives using S3. Therefore, coming up with a future on this issue will make things much easier on the drive side.
```[tasklist]
### Tasks
```

**Comment by cbuescher** [comment]
Hi @themiralay! Your question is better suited to the support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
