### ISSUE TITLE
[ES|QL] Improve `show functions` output

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#99507]
### Description

It would be nice to have more information about function signatures with the `show functions`, like argument names, types and function return type.
The documentation partially contains this information, but it is not complete nor with a single format.

Something like that would enable to build a documentation like this:

```
cos( field: double | long | ... ) => double
```

Which is pretty close to what we're trying to build in Kibana:

<img width="621" alt="Screenshot 2023-09-12 at 16 11 51" src="https://github.com/elastic/elasticsearch/assets/924948/e17b5318-7d4a-41c3-ac49-7314669a4301">

<img width="631" alt="Screenshot 2023-09-12 at 16 10 48" src="https://github.com/elastic/elasticsearch/assets/924948/8fc99e2b-b250-4256-b6c7-f37c2401b029">

Right now signatures are hardcoded but leveraging `show functions` would be great, but the current format is not sufficient:

<img width="414" alt="Screenshot 2023-09-12 at 16 13 04" src="https://github.com/elastic/elasticsearch/assets/924948/d6b0f97b-2780-4445-ade9-b3a14f4f512c">

A table like the following would be nice, but other alternatives who return the same information would be ok as well:

| name | arg1 | arg2 | arg3 | arg4 | argsRepeat | returnType |
| --- | --- | --- | --- | --- | --- | --- |
| cos | n: double - long - ... | null | null | null | false | double |
| concat | string: text - keyword | null | null | null | true | string |
| date_format | field : date | [ date_format : string ] | null | null | false | string |

Perhaps this format would be a bit challenging for `case` function particular case with odd args, but I think it can be overcome with some documentation description.
For polymorphic functions like `auto_bucket` duplicates I think makes sense here.

**Comment by nik9000** [comment]
That'd be neat! I do pretty similar tricks when I build the signature blocks for the docs.

You are right this being funny for the varargs functions. Case is the worst offender because it's not just the same type over and over.
