### ISSUE TITLE
Use "binary" Gradle distribution instead of the "complete" one

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#99511]
### Description

The "complete" Gradle distribution additionally contains docs and sources which are not needed for building.
https://gradle.org/install/#manually

Using the "complete" distribution consumes more time and traffic to download:
gradle-8.3-all.zip is 191 MB and gradle-8.3-bin.zip is 125 MB

It also occupies additional 270 MB of disk space when unpacked under .gradle/wrapper/dists
(On Windows with NTFS more than 300 MB actually due to file system cluster allocation.)

**Comment by mark-vieira** [comment]
This is intentional. We use the "all" distribution because it includes documentation and sources that improve the experience in the IDE for developers.
