### ISSUE TITLE
ESQL: adding `_query` endpoint to the Elasticsearch specification

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#99533]
### Description

Add `_query` ESQL endpoint to https://github.com/elastic/elasticsearch-specification

**Comment by pquentin** [comment]
Closing as the initial version of the ES|QL endpoint was merged: https://github.com/elastic/elasticsearch-specification/pull/2354. Thanks @Anaethelion for working on this, and @bpintea / @swallez for the reviews!
