### ISSUE TITLE
Translog stored at the wrong place

### ISSUE THREAD

**Issue by setaou** [elastic/elasticsearch#9961]
When using option --default.path.data at startup and configuring path.data with a different path in /etc/elasticsearch/elasticsearch.yml, indices are correctly stored in the path defined in elasticsearch.yml, but translogs are still stored in the path defined by --default.path.data.

Removing --default.path.data solves the problem, but when using packages for ES, it involves modifying /etc/init.d/elasticsearch, which is a packaged file.

This situation is a problem, because in my case the default data path (/var/lib/elasticsearch) is a small partition while data paths i configured in elasticsearch.yml are a group of huge SSD. I think translogs should be stored in the correct data.path in order to efficiently use available storage.

**Comment by dakrone** [comment]
@setaou I haven't been able to reproduce this yet, but I am trying to. What version of ES are you using and what operating system are you using? It sounds like you are using either the RPM or DEB package as well?

**Comment by setaou** [comment]
@dakrone Thanks for working on this bug. I am using ES 1.4.4 on Ubuntu 14.04 using the official ES deb package. 
Here is the config file with which I can reproduce the problem : https://gist.github.com/setaou/7a65a242251f897aab35 .

After testing on a vanilla install with this config file and a very simple index (the example at https://github.com/elasticsearch/elasticsearch#indexing), I discovered that the problem seems to affect more than just translogs. Here is the listing of files after the indexing: https://gist.github.com/setaou/7ca4f2b8abdcae55b8de . I suppose this did not appear on my previous setup because /data/ partitions had a lot more free space than /var/lib, so segments were only stored on /data/.

**Comment by clintongormley** [comment]
I'm unable to replicate this.  Lots has changed in this area recently, so I think this is fixed.  Please reopen if it is still a problem
