### ISSUE TITLE
Java Api: every request, builder and response to implement toString() consistently

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#9962]
Follw-up of discussion we had in #9944. After #9201, we should look into having consistent `toString()` implementations for all of our requests (I think builders will be gone by then) and responses.

Topics to discuss: when it comes to search requests we currently print out only part of the requests in json format. I'd propose to move away from json format in general, which is trappy as it makes users think that the json can be sent back to elasticsearch as is (although not complete). I would just make sure that we print out every single bit that the request holds (e.g. at the moment search request builder ignores index, type, routing etc.). 

In general, `toString` should only be a way to nicely debug requests and their content and quickly log them, it doesn't need to be json and it needs to contain all the relevant info for every class that implements it.

**Comment by javanna** [comment]
Given what we plan on doing for the java api (deprecate soon, use only internally in the future) I am wondering if it makes sense to invest time on this issue. I would vote for closing.

**Comment by javanna** [comment]
This is still valid as the high level REST client is reusing requests and responses from the Java api.

**Comment by dakrone** [comment]
I'm going to close this one, as we've removed the high level rest client in favor of the Java client.
