### ISSUE TITLE
reloading cluster state using PUT /_cluster/settings

### ISSUE THREAD

**Issue by jillesvangurp** [elastic/elasticsearch#9964]
I was experimenting with ways to make elasticsearch reload its cluster state to e.g. detect and fix dangling indices that I created by copying or moving indices. Elasticsearch detects and fixes those on start up.

Then I figured it probably does this as well when you update the cluster settings and indeed it does, which is nice. This provides me a way to copy/move/rename indices without a cluster restart. So, for example this does the trick. Elasticsearch will detect any dangling indices and fix them:

```
PUT /_cluster/settings
{
    "transient" : {
        "discovery.zen.minimum_master_nodes" : 1
    }
}
```

However, it would be nicer if I could just do a PUT /_cluster/settings without a body since I don't actually want to change the settings and just reload the cluster state.

This currently fails with a somewhat obscure error (you may want to fix that)

```
{
   "error": "ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@1]",
   "status": 400
}
```

fixing that with a 
```
{}
```

doesn't work either since it requires some kind of settings in there.

```
{
   "error": "ActionRequestValidationException[Validation Failed: 1: no settings to update;]",
   "status": 400
}
```

A nice enhancement would be for PUT /_cluster/settings without a body to simply reload the cluster state. Unless I missed something, there's currently no other way to trigger this behavior via the API than as I described above. A PUT to /_cluster/state, which might be a better alternative, does not seem to work for example.

**Comment by dakrone** [comment]
> Unless I missed something, there's currently no other way to trigger this behavior via the API than as I described above

This is already available by sending an empty body to `/_cluster/reroute`, which increments the cluster state and causes a new state to be sent to all nodes (with no changes).

Going to close this since there currently exists a way to do this.

**Comment by jillesvangurp** [comment]
What does it mean to "increment" the cluster state?

**Comment by dakrone** [comment]
> What does it mean to "increment" the cluster state?

It means the master node increments the number of the cluster state, which prompts it being sent to all other nodes in the cluster.

**Comment by jillesvangurp** [comment]
Right, none of this is really obvious from the documentation page for this
API. Somebody may want to follow up with this to improve the documentation.
Anyway, thanks for clarifying.
