### ISSUE TITLE
EQL sequence queries open PIT against indices not included in search request

### ISSUE THREAD

**Issue by marshallmain** [elastic/elasticsearch#99684]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

Linux 5.3.0-64-generic

### Problem Description

EQL search requests with sequence queries open a PIT internally, but the PIT includes indices that were not part of the EQL search request. The final results are correct because the searches include a `terms` filter on the `_index` field that limits the returned results to the correct indices, however, performance suffers when there are many indices in the system. Performance is noticeably worse when some indices are on frozen nodes and get included in the PIT despite not being included in the original search request. In this case frozen node CPU usage spikes even when the EQL search request from the user does not include any frozen indices in the request.

Since the indices in the PIT are not respecting the list of indices from the search request, users have no means to tune and prevent EQL sequence searches from impacting their frozen nodes.

### Steps to Reproduce

Script to create 2 indices, then query `test_eql_sequence_pit` with an EQL sequence in a loop:
```
#!/bin/sh

ES=http://elastic:changeme@localhost:9200
ESIDX=test_eql_sequence_pit
ESIDX_UNRELATED=test_unrelated_index

curl -s -XDELETE $ES/$ESIDX >/dev/null

curl -s -XPUT $ES/$ESIDX?pretty=true -H 'Content-Type: application/json' -d '{
    "settings": {}
}'

curl -s -XPUT $ES/$ESIDX_UNRELATED?pretty=true -H 'Content-Type: application/json' -d '{
    "settings": {}
}'

curl -s -XPOST $ES/$ESIDX/_mapping?pretty=true -H 'Content-Type: application/json' -d '{
    "properties": {
        "@timestamp": {
            "type": "date"
        }
    }
}'

for i in {1..100}
do
echo "$i"
curl -s -XPOST $ES/$ESIDX/_bulk?pretty=true\&refresh=true -H 'Content-Type: application/json' -d \
'{"index": {}}
{"@timestamp": "1695149097000"}
{"index": {}}
{"@timestamp": "1695149097001"}
{"index": {}}
{"@timestamp": "1695149097002"}
{"index": {}}
{"@timestamp": "1695149097003"}
{"index": {}}
{"@timestamp": "1695149097004"}
{"index": {}}
{"@timestamp": "1695149097005"}
{"index": {}}
{"@timestamp": "1695149097006"}
{"index": {}}
{"@timestamp": "1695149097007"}
'>/dev/null
done

for (( ; ; ))
do
curl -s -XPOST $ES/$ESIDX/_eql/search -H 'Content-Type: application/json' -d \
'{
  "size": 100,
  "query":"sequence [any where true][any where true][any where true][any where true][any where true][any where true][any where true][any where true]"
}
'>/dev/null

done
```

While the first script is running, fetch active tasks with this second script:
```
#!/bin/sh

ES=http://elastic:changeme@localhost:9200
ESIDX=test_eql_sequence_pit

curl -s -XGET "$ES/_tasks?actions=*search&detailed=true"
```

Example response:
```
{
  "nodes": {
    "8MqMka6cR1KWtajIGSmW3A": {
      "name": "marshall-X570-AORUS-PRO-WIFI",
      "transport_address": "127.0.0.1:9300",
      "host": "127.0.0.1",
      "ip": "127.0.0.1:9300",
      "roles": [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes": {
        "ml.machine_memory": "33683869696",
        "transform.config_version": "10.0.0",
        "xpack.installed": "true",
        "ml.config_version": "10.0.0",
        "ml.max_jvm_size": "1610612736",
        "ml.allocated_processors_double": "24.0",
        "ml.allocated_processors": "24"
      },
      "tasks": {
        "8MqMka6cR1KWtajIGSmW3A:3727": {
          "node": "8MqMka6cR1KWtajIGSmW3A",
          "id": 3727,
          "type": "transport",
          "action": "indices:data/read/search",
          "description": "indices[test_unrelated_index,test_eql_sequence_pit], search_type[QUERY_THEN_FETCH], source[{\"size\":1000,\"timeout\":\"30s\",\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"time_zone\":\"UTC\",\"format\":\"epoch_millis\",\"boost\":1.0}}},{\"term\":{\"_index\":{\"value\":\"test_eql_sequence_pit\"}}}],\"boost\":1.0}},\"_source\":false,\"fields\":[{\"field\":\"@timestamp\",\"format\":\"epoch_millis\"}],\"sort\":[{\"@timestamp\":{\"order\":\"desc\",\"missing\":\"_last\",\"unmapped_type\":\"date\"}}],\"track_total_hits\":-1,\"pit\":{\"id\":\"6-aGBAEVdGVzdF9lcWxfc2VxdWVuY2VfcGl0FnRuOU42aGVlVHdLcWc2ay0wRjZFcXcAFjhNcU1rYTZjUjFLV3RhaklHU21XM0EAAAAAAAAAAHAWYURhZ0N4MzRSckstM0NpanE2SFRDUQABFnRuOU42aGVlVHdLcWc2ay0wRjZFcXcAAA==\"}}]",
          "start_time_in_millis": 1695163108456,
          "running_time_in_nanos": 5185143,
          "cancellable": true,
          "cancelled": false,
          "parent_task_id": "8MqMka6cR1KWtajIGSmW3A:3722",
          "headers": {}
        }
      }
    }
  }
}
```
The task description shows a query going to both indices even though the EQL search request is made to `test_eql_sequence_pit` specifically with no wildcards.

**Comment by astefan** [comment]
@marshallmain The observation you made regarding PIT and its broad list of targeted indices is something that recently also caught the attention of the Search team, following a series of other related issues: https://github.com/elastic/elasticsearch/issues/99740
Even though the main observable issue in there is a significantly increased PIT ID size this will consequently have an impact on CPU usage (by simply creating and storing in memory the ID) and on data transfer rates (the bigger the ID the larger the transfer amount).

Irrespective of the information I provided above, this report shouldn't be regarded as a bug since the [EQL usage of the PIT API is correct](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/point-in-time-api.html). Relevant extract from the previous docs link:

> A search request with the pit parameter must not specify index, routing, or preference as these parameters are copied from the point in time.

However, I am keeping this issue open as a placeholder for a future improvement to EQL usage of PIT in line with Elasticsearch's work around https://github.com/elastic/elasticsearch/issues/99740 (ie making sure that any filter passed to an EQL `sequence` or `samples` query will also be copied in the opening PIT request).

**Comment by javanna** [comment]
Heads up: it is now possible to provide an index_filter as part of the open point in time API, to restrict the indices that a pit will be opened against. All indices that cannot possibly match the filter will be filtered out.

**Comment by MikePaquette** [comment]
@astefan @siposea Can we please have an update on this issue?

**Comment by astefan** [comment]
@MikePaquette there is no immediate concrete plan for integrating this, but it is on my radar.

**Comment by marshallmain** [comment]
I dug into this issue more today and found a key difference in EQL's usage of Point-in-time compared to the REST `_search` API. When Elasticsearch [parses a search request](https://github.com/elastic/elasticsearch/blob/8.12/server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java#L223) that includes a PIT id, it calls `preparePointInTime`. This function verifies that the incoming request does not have indices specified, but [at the end](https://github.com/elastic/elasticsearch/blob/8.12/server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java#L413) it extracts the actual index names from the provided PIT id and injects them into the `SearchRequest`. The result is a `SearchRequest` object that **does** specify indices to search against. The final `SearchRequest` with indices can then be passed to the internal `Client` and the request is limited to the correct indices.

The [PITAwareQueryClient](https://github.com/elastic/elasticsearch/blob/8.12/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/PITAwareQueryClient.java#L107) in the EQL implementation also builds a `SearchRequest` object, but explicitly sets the indices on the `SearchRequest` object to be empty, whereas in the REST API the indices are extracted from the PIT. Since the final `SearchRequest` built by `PITAwareQueryClient` specifies no indices, when it gets passed to the internal `Client` the query ends up being sent to all indices.

The public facing Elasticsearch docs would apply if EQL used a PIT with the REST API, but since the logic in the REST API that extracts the indices from the PIT id is bypassed when a `SearchRequest` is sent directly to the internal client I don't think the public docs apply here.

As a test I was able to delete the [lines in `PITAwareQueryClient` ](https://github.com/elastic/elasticsearch/blob/8.12/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/PITAwareQueryClient.java#L105-L110) that remove the indices from the `SearchRequest`. This way the `SearchRequest` still contains the same indices that were used to open the PIT. After that change the search task created by following the repro steps for this issue had only the single expected index.
