### ISSUE TITLE
PIT IDs can grow to many MiB in size

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#99739]
Today, the length of a PIT ID scales with the number of shards captured by the PIT. In a large cross-cluster scenario there may be 100k or more shards, leading to IDs that are several MiB in size. Simply creating these IDs in memory burns a bunch of CPU (see https://github.com/elastic/elasticsearch/pull/99219 for some optimizations there) but we still have to send them over the wire as part of each request, and the cross-region transit costs for this traffic can be several US cents per GiB so the cost of that traffic can be eyewatering.

**Comment by henningandersen** [comment]
This looks similar to #80187, so linking them.

**Comment by javanna** [comment]
Closing in favour of #80187 .
