### ISSUE TITLE
Incorporate can-match phase into PIT creation

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#99740]
When a user creates a PIT today they will often have a good sense of the queries for which they will be using it, and in particular all those queries may target a very limited time range. However the PIT will be created to target entire data streams, many of whose backing indices will not match any of the future queries, so Elasticsearch does unnecessary work creating the PIT on shards that will never contain any matches, and further unnecessary work re-running the can-match phase on all those shards for every search.

IMO it would be good if the creation of a PIT could include a filter, and we ran the can-match phase up-front while creating the PIT to limit the shards it targets. We'd need to make it an error if searches using the PIT did not include the same filter (or perhaps something more restrictive).

Relates https://github.com/elastic/elasticsearch/issues/99739 in that this would substantially reduce the size of PIT IDs in many cases.

**Comment by jpountz** [comment]
+1 I just opened an issue with a proposed solution before being pointed to this issue you had already opened. A natural way of addressing this would consist of adding an `index_filter` parameter to `_pit` creation. This is the same solution we implemented for `_field_caps` for the same problem.

```javascript
POST /logs-*/_pit?keep_alive=1m
{
  "index_filter": {
    "bool": {
      "filter": [
        { "range": { "@timestamp": { "gte": "now-1d" } } },
        { "match": { "data_stream.dataset": "kubernetes.state_deployment" } }
      ]
    }
  }
}
```

**Comment by dnhatn** [comment]
We have a list of enhancements for PIT in https://github.com/elastic/elasticsearch/issues/96775, but only one of them has been implemented.
