### ISSUE TITLE
[Transform] Don't use PIT in scenarios where it can be problematic

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#99742]
Today transforms defaults to using point-in-time (PIT) readers. These can make the transform more efficient in many scenarios, however, there are some where they can make the transform considerably less efficient.

Transforms should not use PIT in the following situations:

1. When some of the source indices are on remote clusters
2. After PIT has been used once and the PIT handle was more than 500KB in size

**Comment by droberts195** [comment]
I recommend implementing 1 and 2 in separate PRs, because 1 is _really_ simple and we should aim to get it into 8.10.3.

**Comment by DaveCTurner** [comment]
IMO we should consider these things to be temporary workarounds and also strive for a world where there are no such problematic scenarios for using PITs (see for instance #99739 and #99740). So once this is done let's make sure to track any follow-up work to expand the usage of PITs again.
