### ISSUE TITLE
Improve performance of Cat Nodes API

### ISSUE THREAD

**Issue by NEUpanning** [elastic/elasticsearch#99744]
### Description

We found that executing the Cat Nodes API (query parameters do not matter) on the coordinate node of a large cluster can require a huge amount of CPU.This could have a significant impact on cluster stability.I reproduced this problem in the cluster with 200 data nodes and 140k shards. 
When I used the 'top' command to query, the result showed that CPU usage fluctuated between 726% and 1173% for 3 seconds.
The most CPU usage comes from [`ShardStats.<init>`](https://github.com/elastic/elasticsearch/blob/f35f7bcabf3a6dabe46d08344d28db7242cb2ae3/server/src/main/java/org/elasticsearch/action/admin/indices/stats/ShardStats.java#L50-L71) and [`DiscoveryNode.writeTo`](https://github.com/elastic/elasticsearch/blob/f35f7bcabf3a6dabe46d08344d28db7242cb2ae3/server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java#L362-L385). `ShardStats.<init>` is called when coordinate node deserializes response that is responded by other nodes. `DiscoveryNode.writeTo` is called when coordinate node serializes request that will be sent to other nodes.Here is [Flame Graph](https://github.com/NEUpanning/ESFlameGraph/blob/main/cpu.html)
<img width="1895" alt="Screen Shot 2023-09-21 at 4 42 53 PM" src="https://github.com/elastic/elasticsearch/assets/33685703/1ac377e4-055f-4f84-8bf7-04dcf2a4bcb7">

###  Several superficial ideas try to solve this issue:
1. Coordinate node could construct `NodesStatsRequest#indices` based on query parameters to filter indices stats rather than calling [`NodesStatsRequest.indices(true)`](https://github.com/elastic/elasticsearch/blob/f35f7bcabf3a6dabe46d08344d28db7242cb2ae3/server/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java#L103C24-L103C24) that contains all indices stats.For instance if users call `_cat/nodes?h=m`,coordinate node should not fetch indices stats from other nodes.This would avoid a lot of unnecessary deserialization of the response content from `ShardStats.<init>`.
2. Set `NodeInfoRequest#concreteNodes` to null after using `NodeInfoRequest#concreteNodes` [to build iterator](https://github.com/elastic/elasticsearch/blob/f35f7bcabf3a6dabe46d08344d28db7242cb2ae3/server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java#L149) that used to send requests.This would avoid unnecessary serialization of the request content from `DiscoveryNode.writeTo`.

**Comment by DaveCTurner** [comment]
The `_cat` APIs are intended to be convenient wrappers around the more flexible JSON APIs, intended for occasional use by humans. I'm a little impressed that it only takes 3s to respond in such a huge cluster. If you need more control over the execution, use the JSON APIs directly.

> For instance if users call `_cat/nodes?h=m`, coordinate node should not fetch indices stats from other nodes. This would avoid a lot of unnecessary deserialization of the response content from ShardStats.<init>.

This seems like a nice idea but it would be fragile, we'd need to keep track of the columns that included stats to know whether or not the stats request was needed, and make sure to keep that list up to date as the columns change over time. Also the `_cat` APIs generally don't have a way to get a list of the requested columns when processing the request. So this idea seems possible but a little tricky and requiring quite some effort.

> Set `NodeInfoRequest#concreteNodes` to `null`

IMO this is a valid point, although I would not want to solve it as described. Today every node-level `TransportNodesInfoAction.NodeInfoRequest` carries the entire top-level `NodesInfoRequest`, but it only needs to carry the metrics. We should trim these things down for sure.

**Comment by DaveCTurner** [comment]
Just to add: another idea would be to indicate in the stats request that we don't care about stats for individual shards, we are only going to use a summary. That'd save a bunch of effort and network traffic with the nodes stats and indices stats APIs too.

**Comment by NEUpanning** [comment]
@DaveCTurner Thanks for the reply. 

 In the most scenarios we will use the JSON APIs instead of `_cat/nodes`.
> If you need more control over the execution, use the JSON APIs directly.

This is a great idea that is more elegant than i think and avoids unnecessary serialization of the request content from `DiscoveryNode.writeTo`.

> Today every node-level `TransportNodesInfoAction.NodeInfoRequest` carries the entire top-level `NodesInfoRequest`, but it only needs to carry the metrics. We should trim these things down for sure.

This is also a great idea that would trim useless shard stats from responses and avoid unnecessary deserialization of `ShardStats.<init>`.
>another idea would be to indicate in the stats request that we don't care about stats for individual shards, we are only going to use a summary. 

I think implementaion of these ideas could solve this issue.

**Comment by NEUpanning** [comment]
I don't quite understand why [indices stats APIs](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/indices-stats.html) can be optimized.I see coordinate node needs shard stats to [build indices stats](https://github.com/elastic/elasticsearch/blob/343cc8047cce51a82c018c3d382463be75ef0e0b/server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsResponse.java#L126-L138).
> That'd save a bunch of effort and network traffic with the nodes stats and indices stats APIs too.

**Comment by NEUpanning** [comment]
I would like to do it, do you think I could give it a try?

>I think implementaion of these ideas could solve this issue.

**Comment by DaveCTurner** [comment]
> I see coordinate node needs shard stats to [build indices stats](https://github.com/elastic/elasticsearch/blob/343cc8047cce51a82c018c3d382463be75ef0e0b/server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsResponse.java#L126-L138).

I think we can reduce the work here if the user specifies `?level=cluster`, but I'm not sure it's worth the effort.

> I would like to do it, do you think I could give it a try?

Sure, go for it. I recommend you don't do it all in one PR tho, try and separate the independent changes out to make them easier to review.

**Comment by NEUpanning** [comment]
@DaveCTurner I've opened a pull request(#99938) for this idea . Could you please have a look when you have some time? Thanks
> Today every node-level TransportNodesInfoAction.NodeInfoRequest carries the entire top-level NodesInfoRequest, but it only needs to carry the metrics.

**Comment by NEUpanning** [comment]
> another idea would be to indicate in the stats request that we don't care about stats for individual shards, we are only going to use a summary. 

I've opened a pull request for this idea in #100466.

**Comment by DaveCTurner** [comment]
Thanks @NEUpanning, I'll take a look next week. You might also be interested in https://github.com/elastic/elasticsearch/issues/90631 which is kind of the same thing but for the `GET _cluster/health` API.

**Comment by NEUpanning** [comment]
I would like to resolve this issue. After that PR is merged, I will try it using the similar approach.

**Comment by NEUpanning** [comment]
After we have implemented these ideas mentioned above, the CPU usage and cost time of fetching nodes stats (without shards-level stats) reduce to 1/1000th of their original levels. So this issue is closed as completed.

**Comment by DaveCTurner** [comment]
Nice work @NEUpanning, thanks for the report, the fixes, and for confirming that the problems are fixed.

**Comment by NEUpanning** [comment]
Thanks again David. Thanks for your help and patience in code review.
