### ISSUE TITLE
Remove lowercase_expanded_terms option

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#9978]
for the record, i think we should remove this lowercasing option completely in parsers, disable it, and let the analysis chain take care. For multitermqueries, its a little tricky, which subset of the filters should be used? For example lowercasing is reasonable, stemming is not. 

But lucene already annotates each analyzer component deemed to be "reasonable" for wildcards with a marker interface (MultiTermAwareComponent). Things like lowercasefilter have it and things like stemmers dont have it.  This is enough to build a "chain", automatically from the query analyzer, that acts reasonably for multitermqueries. 

I know we don't use the lucene factories (es has its own), but we have a table that maps between them, i know because its in a test I wrote. So the information is there :)

All queryparsers have hooks (e.g. factory methods for prefix/wildcard/range) that make it possible to use this, for example solr does it by default, as soon as it did this, people stopped complaining about confusing behavior: both for the unanalyzed, and the analyzed case. it just works.

Sorry for the long explanation.

Compare:
- http://svn.apache.org/viewvc/lucene/dev/branches/branch_5x/lucene/analysis/common/src/java/org/apache/lucene/analysis/core/LowerCaseFilterFactory.java?view=markup
- http://svn.apache.org/viewvc/lucene/dev/branches/branch_5x/lucene/analysis/common/src/java/org/apache/lucene/analysis/en/PorterStemFilterFactory.java?view=markup

**Comment by rmuir** [comment]
background: #9973 (i copied my comment here)

**Comment by dakrone** [comment]
@rmuir can you explain a little bit more how the `MultiTermAwareComponent` should be used? When I look for usages of it in the Lucene 4.x branch, but the only users are tests and Solr.

Looking at the `QueryBuilder`, it looks like it uses the analyzer to get the tokenStream for the text to get tokens, but that this doesn't seem to interface with choosing whether or not to do things like stemming? Do you think this is something that we should hold off on doing until we figure out how to exclude things like stemming from the analysis chain when analyzing expanded terms, or should we let the user deal with it by specifying a separate query-time analyzer?

(I originally merged a change for this that did it in the generic way but then reverted it when Ryan reminded my about the MultiTermAwareComponent part of this)

**Comment by rmuir** [comment]
> @rmuir can you explain a little bit more how the MultiTermAwareComponent should be used?

You create a separate chain (analyzer) for multitermqueries by iterating thru the query analysis chain. implicitly the tokenizer should be keywordtokenizer.

imagine query analysis chain is: lowercase + snowball. you look at lowercase (http://svn.apache.org/viewvc/lucene/dev/branches/branch_5x/lucene/analysis/common/src/java/org/apache/lucene/analysis/core/LowerCaseFilterFactory.java?view=markup) and with instanceof you see it has that interface, so you call getMultiTermComponent() and add that to the chain. On the other hand snowball does not implement it, so nothing gets added.

**Comment by javanna** [comment]
As a side note, if we remove this option we should be able to remove the locale parameter from simple_query_string and query_string as well, that would help with solving #13229 .
