### ISSUE TITLE
Integrate TDigestState with circuit breakers

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#99815]
### Description

`TDigest`is missing integration with circuit breakers. The latter can track memory allocation and throw an exception before exhausting the heap. While the latest (forked) version of the TDigest library has constant memory footprint of < 100kB, it's still possible to create thousands of such instances (one per bucket) so it's still valuable to complete this task.

**Comment by ivancea** [comment]
A little late update:
The TDigest with CircuitBreaker was only integrated within ES|QL. For `_search` aggs, it would require bigger refactors, and was discarded
