### ISSUE TITLE
[DOC] inference processor docs doesn't contain text_expansion config

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#99825]
### Elasticsearch Version

8.10.2

### Installed Plugins

-

### Java Version

_bundled_

### OS Version

Darwin iMac 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Problem Description

The latest documentation on the [`inference` ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/inference-processor.html) doesn't contain the `text_expansion` parameters to be put in `inference_config`.

According to the [Semantic search with ELSER](https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search-elser.html#inference-ingest-pipeline) tutorial, there should at least be a `results_field` configuration parameter.

### Steps to Reproduce

1. Go to the [Semantic search with ELSER](https://www.elastic.co/guide/en/elasticsearch/reference/current/semantic-search-elser.html#inference-ingest-pipeline) tutorial, move to the section titled "Create an ingest pipeline with an inference processor"
2. Observe that the `inference` ingest processor has a `text_expansion` configuration in the `inference_config` section
3. Go to the latest official documentation of the [`inference` ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/inference-processor.html)
4. Search for `text_expansion`
5. Find nothing

**Comment by jrodewig** [comment]
@szabosteve Can you take a look at this when able? Thanks!

**Comment by szabosteve** [comment]
@consulthys @jrodewig  Thanks for the heads-up! I added the missing config via https://github.com/elastic/elasticsearch/pull/99900.
