### ISSUE TITLE
[ES|QL] New `show aggs` command for stats supported functions

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#99853]
### Description

We currently have the `show functions` command who prints the current supported functions for the `EVAL` command.
It would be helpful to have also an equivalent `show aggs` for the `STATS` command and its relative signatures.

**Comment by dej611** [comment]
An alternative approach here can be to leverage the existing `show functions` command, and add a new `supported commands` column in the returned table result with the `eval`/`stats`/`where`.
This would also provide a coverage for `where` command functions, which otherwise might need yet another command option.

**Comment by luigidellaquila** [comment]
> I've just noticed that since https://github.com/elastic/elasticsearch/pull/99736 the show functions is returning also aggregation functions,

Actually the behavior was the same before that change.
I think it would be useful to have one more column in the result (eg. boolean `aggregate` ) to distinguish the two types
