### ISSUE TITLE
ES 1.2.4 is crashing suddenly

### ISSUE THREAD

**Issue by rvller** [elastic/elasticsearch#9988]
Full dump: https://gist.github.com/rvller/beca1245584e8158a50f

Stack: [0x00007f2e3cbb1000,0x00007f2e3cbf2000],  sp=0x00007f2e3cbf06b0,  free space=253k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 2442 C2 sun.nio.ch.SelectorImpl.select(J)I (34 bytes) @ 0x00007f2e5d6602e8 [0x00007f2e5d6600e0+0x208]
J 2561% C2 org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run()V (409 bytes) @ 0x00007f2e5d315d68 [0x00007f2e5d315b40+0x228]
j  org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run()V+1
j  org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run()V+1
j  org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run()V+55
j  org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run()V+14
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6000f5]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feb58]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x5fee27]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x197
V  [libjvm.so+0x5fef47]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x67bf65]  thread_entry(JavaThread*, Thread*)+0xe5
V  [libjvm.so+0x95a08f]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0x95a195]  JavaThread::run()+0xf5
V  [libjvm.so+0x820c28]  java_start(Thread*)+0x108

**Comment by cooniur** [comment]
Is it because of SELinux? (enabled in CentOS7 by default)

**Comment by silentmoose** [comment]
Have we tested on different operating systems? It seems a logging class that uses the system properties util would be handy to make debugging much easier.

**Comment by clintongormley** [comment]
@rvller What changed on your system?

**Comment by rvller** [comment]
@clintongormley really nothing was changed before this starts happening. Same indecies on the same ES. Currently it's up and running. 
Can it be related to the SELinux as @cooniur mentioned?

**Comment by rvller** [comment]
here is what. I've updated ES to 1.4.3. So it creashed again:

Full log here: https://gist.github.com/rvller/3cea11802f861f9e9233 

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f2e991ce1f0, pid=30884, tid=139837175879424
#
# JRE version: Java(TM) SE Runtime Environment (7.0_72-b14) (build 1.7.0_72-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.72-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9251f0]  SystemDictionary::resolve_or_null(Symbol*, Thread*)+0x20
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007f2e94934000):  JavaThread "elasticsearch[Man-Spider][scheduler][T#1]" daemon [_thread_in_vm, id=30907, stack(0x00007f2e612dd000,0x00007f2e6131e000)]

siginfo:si_signo=SIGILL: si_errno=0, si_code=2 (ILL_ILLOPN), si_addr=0x00007f2e991ce1f0

Registers:
RAX=0x0000000000000000, RBX=0x00007f2e94934000, RCX=0x0000000000000000, RDX=0x0000000000000000
RSP=0x00007f2e6131c428, RBP=0x00007f2e6131c460, RSI=0x0000000000000000, RDI=0x00007f2e948db280
R8 =0x00007f2e94934000, R9 =0x0000000000000000, R10=0x00007f2e909c0d6c, R11=0x00007f2e998a1420
R12=0x0000000000000000, R13=0x00007f2e949341e8, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007f2e991ce1f0, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000000
  TRAPNO=0x0000000000000006

Top of Stack: (sp=0x00007f2e6131c428)
0x00007f2e6131c428:   00007f2e98f2066a 000000062514fd28
0x00007f2e6131c438:   00007f2e94934000 00007f2e6131c520
0x00007f2e6131c448:   00007f2e94934000 0000000000000000
0x00007f2e6131c458:   00007f2e948db280 00007f2e6131c4f0
0x00007f2e6131c468:   00007f2e98f3102d 00007f2e94934000
0x00007f2e6131c478:   00007f2e3000a2e0 0000000000000000
0x00007f2e6131c488:   00000000000003d8 00007f2e949341e8
0x00007f2e6131c498:   0000000000000000 00007f2e94934000
0x00007f2e6131c4a8:   0000000000000001 00007f2e94934000
0x00007f2e6131c4b8:   0000000000000025 00007f2e6131c4f0
0x00007f2e6131c4c8:   00007f2e6131c520 00007f2e949341e8
0x00007f2e6131c4d8:   00007f2e6131c680 00007f2e6131c520
0x00007f2e6131c4e8:   0000000000000025 00007f2e6131c5d0
0x00007f2e6131c4f8:   00007f2e93de2690 00007f2e6131c520
0x00007f2e6131c508:   0000000000000000 0000000000000000
0x00007f2e6131c518:   0000000004dd5000 6e616c2f6176616a
0x00007f2e6131c528:   6567616e616d2f67 6675422f746e656d
0x00007f2e6131c538:   4d6c6f6f50726566 0000006e61654258
0x00007f2e6131c548:   00007f2e9905de77 00007f2e0000000e
0x00007f2e6131c558:   00007f2efb17ab98 00007f2e30009b40
0x00007f2e6131c568:   00007f2e9492d730 00007f2e30009b30
0x00007f2e6131c578:   00007f2e94934000 0000000000000000
0x00007f2e6131c588:   0000000000000005 00007f2e94934000
0x00007f2e6131c598:   000000000000009a 00007f2e6131c5f0
0x00007f2e6131c5a8:   00000007fae0e9a8 0000000000000000
0x00007f2e6131c5b8:   00000007fae0e9a0 00007f2e6131c680
0x00007f2e6131c5c8:   00007f2e94934000 00007f2e6131c648
0x00007f2e6131c5d8:   00007f2e909c0d98 00007f2e6131c680
0x00007f2e6131c5e8:   00007f2e94934000 000000000000009a
0x00007f2e6131c5f8:   00007f2e622a3cc8 00007f2e6131c630
0x00007f2e6131c608:   00007f2e6131c608 0000000000000000
0x00007f2e6131c618:   00007f2e6131c680 00000007faeb40c8 

Instructions: (pc=0x00007f2e991ce1f0)
0x00007f2e991ce1d0:   55 48 89 f1 31 d2 31 f6 48 89 e5 c9 e9 0f ef ff
0x00007f2e991ce1e0:   ff 90 66 66 66 66 66 2e 0f 1f 84 00 00 00 00 00
0x00007f2e991ce1f0:   55 48 89 e5 48 89 5d d8 4c 89 6d e8 4c 89 c3 4c
0x00007f2e991ce200:   89 75 f0 4c 89 7d f8 49 89 d6 4c 89 65 e0 48 83 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007f2e94934000 is a thread
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00007f2e6131c428 is pointing into the stack for thread: 0x00007f2e94934000
RBP=0x00007f2e6131c460 is pointing into the stack for thread: 0x00007f2e94934000
RSI=0x0000000000000000 is an unknown value
RDI=0x00007f2e948db280 is an unknown value
R8 =0x00007f2e94934000 is a thread
R9 =0x0000000000000000 is an unknown value
R10=0x00007f2e909c0d6c is at code_begin+620 in an Interpreter codelet
method entry point (kind = native)  [0x00007f2e909c0b00, 0x00007f2e909c1360]  2144 bytes
R11=0x00007f2e998a1420: <offset 0x181420> in /lib64/libc.so.6 at 0x00007f2e99720000
R12=0x0000000000000000 is an unknown value
R13=0x00007f2e949341e8 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value


Stack: [0x00007f2e612dd000,0x00007f2e6131e000],  sp=0x00007f2e6131c428,  free space=253k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x9251f0]  SystemDictionary::resolve_or_null(Symbol*, Thread*)+0x20
V  [libjvm.so+0x68802d]  JVM_FindClassFromCaller+0x26d
C  [libjava.so+0xd690]  Java_java_lang_Class_forName0+0x130
j  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class;+0
J 6115 C2 sun.reflect.GeneratedMethodAccessor22.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (49 bytes) @ 0x00007f2e917e42ec [0x00007f2e917e3ee0+0x40c]
J 4597 C2 org.elasticsearch.monitor.jvm.JvmStats.jvmStats()Lorg/elasticsearch/monitor/jvm/JvmStats; (1055 bytes) @ 0x00007f2e9178cb24 [0x00007f2e9178be20+0xd04]
J 5314 C2 org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor.monitorLongGc()V (1098 bytes) @ 0x00007f2e91945ec0 [0x00007f2e91945e40+0x80]
j  org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor.run()V+1
J 5941 C2 org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run()V (43 bytes) @ 0x00007f2e9143836c [0x00007f2e91438320+0x4c]
J 5945 C2 java.util.concurrent.FutureTask.runAndReset()Z (128 bytes) @ 0x00007f2e90fdf2c4 [0x00007f2e90fdf200+0xc4]
J 4617 C2 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x00007f2e9175b5ac [0x00007f2e9175b400+0x1ac]
J 3482% C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f2e91406710 [0x00007f2e91406500+0x210]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6000f5]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feb58]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x5fee27]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x197
V  [libjvm.so+0x5fef47]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x67bf65]  thread_entry(JavaThread*, Thread*)+0xe5
V  [libjvm.so+0x95a08f]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0x95a195]  JavaThread::run()+0xf5
V  [libjvm.so+0x820c28]  java_start(Thread*)+0x108

**Comment by rvller** [comment]
I 've updated ES to 1.4.3. So it crashed again...

See full log: https://gist.github.com/rvller/3cea11802f861f9e9233

 A fatal error has been detected by the Java Runtime Environment:
  SIGILL (0x4) at pc=0x00007f2e991ce1f0, pid=30884, tid=139837175879424

 JRE version: Java(TM) SE Runtime Environment (7.0_72-b14) (build 1.7.0_72-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.72-b04 mixed mode linux-amd64 compressed ops)
 Problematic frame:
 V  [libjvm.so+0x9251f0]  SystemDictionary::resolve_or_null(Symbol*, Thread*)+0x20

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c nlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp


---------------  T H R E A D  ---------------

Current thread (0x00007f2e94934000):  JavaThread "elasticsearch[Man-Spider][scheduler][T#1]" daemon [_thread_in_vm, id=30907, stack(0x00007f2e612dd000,0x00007f2e6131e000)]

siginfo:si_signo=SIGILL: si_errno=0, si_code=2 (ILL_ILLOPN), si_addr=0x00007f2e991ce1f0

Registers:
RAX=0x0000000000000000, RBX=0x00007f2e94934000, RCX=0x0000000000000000, RDX=0x0000000000000000
RSP=0x00007f2e6131c428, RBP=0x00007f2e6131c460, RSI=0x0000000000000000, RDI=0x00007f2e948db280
R8 =0x00007f2e94934000, R9 =0x0000000000000000, R10=0x00007f2e909c0d6c, R11=0x00007f2e998a1420
R12=0x0000000000000000, R13=0x00007f2e949341e8, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007f2e991ce1f0, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000000
  TRAPNO=0x0000000000000006

Top of Stack: (sp=0x00007f2e6131c428)
0x00007f2e6131c428:   00007f2e98f2066a 000000062514fd28
0x00007f2e6131c438:   00007f2e94934000 00007f2e6131c520
0x00007f2e6131c448:   00007f2e94934000 0000000000000000
0x00007f2e6131c458:   00007f2e948db280 00007f2e6131c4f0
0x00007f2e6131c468:   00007f2e98f3102d 00007f2e94934000
0x00007f2e6131c478:   00007f2e3000a2e0 0000000000000000
0x00007f2e6131c488:   00000000000003d8 00007f2e949341e8
0x00007f2e6131c498:   0000000000000000 00007f2e94934000
0x00007f2e6131c4a8:   0000000000000001 00007f2e94934000
0x00007f2e6131c4b8:   0000000000000025 00007f2e6131c4f0
0x00007f2e6131c4c8:   00007f2e6131c520 00007f2e949341e8
0x00007f2e6131c4d8:   00007f2e6131c680 00007f2e6131c520
0x00007f2e6131c4e8:   0000000000000025 00007f2e6131c5d0
0x00007f2e6131c4f8:   00007f2e93de2690 00007f2e6131c520
0x00007f2e6131c508:   0000000000000000 0000000000000000
0x00007f2e6131c518:   0000000004dd5000 6e616c2f6176616a
0x00007f2e6131c528:   6567616e616d2f67 6675422f746e656d
0x00007f2e6131c538:   4d6c6f6f50726566 0000006e61654258
0x00007f2e6131c548:   00007f2e9905de77 00007f2e0000000e
0x00007f2e6131c558:   00007f2efb17ab98 00007f2e30009b40
0x00007f2e6131c568:   00007f2e9492d730 00007f2e30009b30
0x00007f2e6131c578:   00007f2e94934000 0000000000000000
0x00007f2e6131c588:   0000000000000005 00007f2e94934000
0x00007f2e6131c598:   000000000000009a 00007f2e6131c5f0
0x00007f2e6131c5a8:   00000007fae0e9a8 0000000000000000
0x00007f2e6131c5b8:   00000007fae0e9a0 00007f2e6131c680
0x00007f2e6131c5c8:   00007f2e94934000 00007f2e6131c648
0x00007f2e6131c5d8:   00007f2e909c0d98 00007f2e6131c680
0x00007f2e6131c5e8:   00007f2e94934000 000000000000009a
0x00007f2e6131c5f8:   00007f2e622a3cc8 00007f2e6131c630
0x00007f2e6131c608:   00007f2e6131c608 0000000000000000
0x00007f2e6131c618:   00007f2e6131c680 00000007faeb40c8 

Instructions: (pc=0x00007f2e991ce1f0)
0x00007f2e991ce1d0:   55 48 89 f1 31 d2 31 f6 48 89 e5 c9 e9 0f ef ff
0x00007f2e991ce1e0:   ff 90 66 66 66 66 66 2e 0f 1f 84 00 00 00 00 00
0x00007f2e991ce1f0:   55 48 89 e5 48 89 5d d8 4c 89 6d e8 4c 89 c3 4c
0x00007f2e991ce200:   89 75 f0 4c 89 7d f8 49 89 d6 4c 89 65 e0 48 83 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007f2e94934000 is a thread
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00007f2e6131c428 is pointing into the stack for thread: 0x00007f2e94934000
RBP=0x00007f2e6131c460 is pointing into the stack for thread: 0x00007f2e94934000
RSI=0x0000000000000000 is an unknown value
RDI=0x00007f2e948db280 is an unknown value
R8 =0x00007f2e94934000 is a thread
R9 =0x0000000000000000 is an unknown value
R10=0x00007f2e909c0d6c is at code_begin+620 in an Interpreter codelet
method entry point (kind = native)  [0x00007f2e909c0b00, 0x00007f2e909c1360]  2144 bytes
R11=0x00007f2e998a1420: <offset 0x181420> in /lib64/libc.so.6 at 0x00007f2e99720000
R12=0x0000000000000000 is an unknown value
R13=0x00007f2e949341e8 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value


Stack: [0x00007f2e612dd000,0x00007f2e6131e000],  sp=0x00007f2e6131c428,  free space=253k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x9251f0]  SystemDictionary::resolve_or_null(Symbol*, Thread*)+0x20
V  [libjvm.so+0x68802d]  JVM_FindClassFromCaller+0x26d
C  [libjava.so+0xd690]  Java_java_lang_Class_forName0+0x130
j  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class;+0
J 6115 C2 sun.reflect.GeneratedMethodAccessor22.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (49 bytes) @ 0x00007f2e917e42ec [0x00007f2e917e3ee0+0x40c]
J 4597 C2 org.elasticsearch.monitor.jvm.JvmStats.jvmStats()Lorg/elasticsearch/monitor/jvm/JvmStats; (1055 bytes) @ 0x00007f2e9178cb24 [0x00007f2e9178be20+0xd04]
J 5314 C2 org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor.monitorLongGc()V (1098 bytes) @ 0x00007f2e91945ec0 [0x00007f2e91945e40+0x80]
j  org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor.run()V+1
J 5941 C2 org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run()V (43 bytes) @ 0x00007f2e9143836c [0x00007f2e91438320+0x4c]
J 5945 C2 java.util.concurrent.FutureTask.runAndReset()Z (128 bytes) @ 0x00007f2e90fdf2c4 [0x00007f2e90fdf200+0xc4]
J 4617 C2 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x00007f2e9175b5ac [0x00007f2e9175b400+0x1ac]
J 3482% C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f2e91406710 [0x00007f2e91406500+0x210]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6000f5]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feb58]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x5fee27]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x197
V  [libjvm.so+0x5fef47]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x67bf65]  thread_entry(JavaThread*, Thread*)+0xe5
V  [libjvm.so+0x95a08f]  JavaThread::thread_main_inner()+0xdf
V  [libjvm.so+0x95a195]  JavaThread::run()+0xf5
V  [libjvm.so+0x820c28]  java_start(Thread*)+0x108

**Comment by clintongormley** [comment]
What OS are you running on?  Could it be OpenVZ? (see https://github.com/elastic/elasticsearch/issues/9582)

Try with SELinux disabled, try upgrading Java, try removing lib/sigar...

**Comment by dakrone** [comment]
Closing since we have not heard back in over 6 months.
