### ISSUE TITLE
ESQL: document language syntax escaping

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#99933]
### Description

The ESQL syntax uses backticks for escaping different names, but this is missing from documentation. For example, ``FROM employees | EVAL DATE_EXTRACT("year", birth_date) | rename `DATE_EXTRACT("year",birth_date)` AS year | keep year``

**Comment by abdonpijpelink** [comment]
This has been addressed in https://github.com/elastic/elasticsearch/pull/101790
