### ISSUE TITLE
Reduce the number of objects allocated by SLM when listing the snapshots to retain

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#99953]
The SLM retention clean up task `SnapshotRetentionTask` lists all snapshots in order to identify the snapshots to retain and the snapshots to delete. While doing so it retrieves the full snapshot information, including shard snapshot details and shard snapshot failures, to later  only use snapshot metadata and snapshot timestamp to select the snapshots to retain. When the snapshots contain thousands of shards it represents of lot of objects that are unnecessary created, putting a lot of pressure on the garbage collector.

We should improve the way SLM retrieves snapshots to reduce the huge allocations of objects. David made some [interesting](https://github.com/elastic/elasticsearch/issues/99953#issuecomment-1738534389) [suggestions](https://github.com/elastic/elasticsearch/issues/99953#issuecomment-1738626743) in comments.

- #100044
- #100053
- #100054
- #100058
- #100065
- #100070
- #100092

**Comment by DaveCTurner** [comment]
I was wondering if we should instead introduce a new master-node transport action, to be called by SLM, which calls `BlobStoreRepository#getSnapshotInfo` and `SnapshotsService#deleteSnapshots` itself, avoiding the need to accumulate the intermediate list of `SnapshotInfo` objects at all. We don't need most of the logic of the get-snapshots API here, and we could do some nicer things like more intelligent throttling if we weren't working directly with the client-facing get-snapshots and delete-snapshots actions.

**Comment by DaveCTurner** [comment]
Another thing worth considering is whether we could refine `SnapshotInfo#fromXContentInternal` to use `parser.skipChildren()` on fields we aren't going to use. That's going to save a huge amount of allocation for cases where we just drop those fields later on.

**Comment by tlrx** [comment]
That makes perfect sense, thanks David.
