### ISSUE TITLE
Change QueryTemplateParser to use script naming convention

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#9995]
At the moment the QueryTemplateParser uses `query`, `file` and `id` for inline, file and indexed scripts respectively. Since the naming convention for scripts is now `script`, `script_file` and `script_id` (enforced by using the ScriptParameterParser) we should change this API to follow the same convention. We may want to keep `query` as an option for inline scripts as it makes sense in this context but we should support `script` too. `file` and `id` should be replaced with `script_file` and `script_id`.

Original comment in: https://github.com/elasticsearch/elasticsearch/pull/9992/files#r25855691

**Comment by clintongormley** [comment]
>  file and id should be replaced with script_file and script_id.

Or `query_file` and `query_id`?  Not sure it is obvious to users that "templates" are a form of scripting.

Also, we can leave `file` and `id` and just mark them as deprecated, no?

**Comment by colings86** [comment]
@clintongormley yep, good point. It should be noted that ScriptParameterParser can still be used for this since it accepts arbitrary prefixes as well as the default `script` prefix. As for deprecation, yes we can but as will the script options we could also deprecate in 1.5 and remove in 2.0?

**Comment by javanna** [comment]
I think we should come up with a `Script` construct that holds all the relevant parsing code, which needs to be streamlined whenever we support scripts in the codebase. `Script` would then hold 'lang', 'type', the script itself etc. and could be passed as a single argument to `ScriptService` etc. instead of the different arguments that we currently have.

**Comment by uboness** [comment]
+1 on the `Script` construct... it should also implement `ToXContent`.

**Comment by clintongormley** [comment]
Closed in favour of #11164
