### ISSUE TITLE
ESQL: improve COUNT documentation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#99954]
### Description

At the moment, the COUNT documentation is very slim and the example provided there is the most basic one.
Would be better with a more complex example with multiple `by` keys and, also, to be specific about how `count(column)` deals with `null` keys:

`from employees | stats c = count(gender) by gender`

```
       c       |    gender     
---------------+---------------
0              |null           
57             |M              
33             |F              

```

**Comment by bpintea** [comment]
This has been mostly done. However, I'd like to keep it open to add the justification in #110820 to the documentation: the 3VL of ESQL's boolean expression: (T && null -> T, F && null -> null) x (count(null) == 0, count(false) == 1). This is essential to understand how count with a condition works.
