### ISSUE TITLE
ESQL: Remove FilteredBlock 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#99997]
### Description

Filtering of blocks happens externally through a FilteredBlock implementation required for every block type.
As filtering is the same across blocks and the `FilteredBlock` impacts the hot path, an improvement is to 'fuse' the move the filtering logic inside each block.
This removes the unnecessary FilteredBlock hierarchy and also opens up a few looping implementations (raw iteration vs filtered iteration).
Additionally enables filter fusing - adding an addition filter will not create another FilteredBlock but rather enhance the existing filter.

**Comment by alex-spies** [comment]
I think this can be closed as the `FilteredBlock` hierarchy was removed [in this PR.](https://github.com/elastic/elasticsearch/pull/100465)

**Comment by alex-spies** [comment]
Closing as completed by https://github.com/elastic/elasticsearch/pull/100465.

Let's re-open this or a separate issue, @costin if you think there's additional work that was not already addressed by removing the filtered blocks.
